### ISSUE TITLE
[Feature Request] Add the repository of google by default in deepin

### ISSUE THREAD

**Issue by ghost** [linuxdeepin/developer-center#1000]
Google chrome is outdated in deepin.
i sugguest you to add the repository of google in deepin OS by default ,
please , thank you
![DeepinScreenshot_synaptic_20190316092844](https://user-images.githubusercontent.com/26883220/54477487-ece7e900-47cd-11e9-98d0-063fc39e78e6.png)

**Comment by alexwender1** [comment]
@chemel9 It was opening the same topic. :stuck_out_tongue_closed_eyes:

@hualet Please bring this natively to the system... as is already the case with Spotify and Skype in 15.9.2 Beta.

Add to the "/etc/apt/sources.list.d" repository the "google-chrome-stable.list" file; containing within this file the instruction:

deb [arch=amd64] http://dl.google.com/linux/chrome/deb stable main

The Flash Player that comes by default installed by Deepin Store should be removed. For it is a technology in disuse and insecure.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
