### ISSUE TITLE
Settings panel remains opened on lock screen

### ISSUE THREAD

**Issue by ocherniavskyi-lohika-tix** [linuxdeepin/developer-center#1001]
## Describe the bug
Settings panel stays active on lock screen. So any unauthenticated user can change settings.

## To Reproduce
1. Open settings panel
2. Wait for screen lock timeout or close the lid
3. Wake up pc or open the lid 
4. Observe settings panel appearance on lock screen  

## Expected behavior
Settings panel should not be visible and intractable 

## Screenshots
![DeepinScreenshot_20190317161656](https://user-images.githubusercontent.com/47743040/54492533-1f7a0a80-48d0-11e9-96c8-6a874af4f361.png)

## Enviroments:
Lenovo s720-15ikb

### Distro & Version
Linux Deepin 15.9.2

### Related package version
dde-launcher/panda,now 4.6.6-1 amd64
dde-desktop/panda,now 4.7.7.1-1 amd64

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
