### ISSUE TITLE
dde-calendar 集成申请

### ISSUE THREAD

**Issue by myml** [linuxdeepin/developer-center#10029]
### package information | 软件包信息

org.dde.calendar | 5.14.2.1

### Package repository address | 软件包仓库地址

name: old url: http://repo-dev.cicd.getdeepin.org/

### changelog | 更新信息

需要使用最新版玲珑 https://github.com/linuxdeepin/developer-center/issues/10013

1. 修改玲珑仓库，ll-cli repo modify http://repo-dev.cicd.getdeepin.org --name old
2. ~安装或者更新 org.dde.calendar~ 由于测试仓库有一个高版本的runtime, 请卸载再安装,不要更新
3. 验证bug是否解决

### Sphere of influence | 影响范围

- https://github.com/linuxdeepin/developer-center/issues/7495
- https://github.com/linuxdeepin/developer-center/issues/9744

### ADDITIONAL INFORMATION | 额外补充

玲珑的更新问题正在做修复,切换old仓库时不要使用更新

**Comment by babyfengfjx** [comment]
@vivianxf  请开展回归验证，提前与研发确认好环境信息。

**Comment by vivianxf** [comment]
集成测试通过，请及时合入：
1.添加仓库升级成功，包版本正确
2.日历安装成功
3.issues: #7495, #9744 验证通过
4.新增issue： #10044 不影响日历整体功能
5.玲珑基本功能正常，安装，运行，卸载，查看正常
6.系统基本功能正常

综上所述，本次集成通过～

**Comment by myml** [comment]
已推送到外网stable仓库
