### ISSUE TITLE
Increase/Decrease volume sticks when using dedicated buttons on laptop

### ISSUE THREAD

**Issue by ocherniavskyi-lohika-tix** [linuxdeepin/developer-center#1002]
## Describe the bug
As a use of laptop i have dedicated buttons for changing volume level: decrease Fn+F2, increase - Fn-F3. When using Windows 10 to change volume level for few points at once i click and hold Fn+F2/F3 and release buttons when volume level becomes acceptable. But same behavior in deepin leads to volume indicator sticks and change level until maximum or minimum level was achieved or any other buttons was clicked (e.g. Escape).  

## To Reproduce
1. Use dedicated button to increase/decrease volume 
2. Click the button, hold for 1-2  second and release
3. Volume indicator sticks and proceed to change level to the boundary value and remains on the screen

## Expected behavior
Volume indicator should stop when button was released or on of hotkey buttons was released

## Enviroments:
Lenovo s720-15ikb

### Distro & Version
Linux Deepin 15.9.2

### Related package version
dde-desktop 4.7.7.1-1 amd64
dde-launcher 4.6.6-1 amd64

### Additional context
Also i noticed that alphanumeric buttons doesn't work after this bug happens. Workaround is clicking on Caps Lock, Ctrl, Alt, Shift, Num Lock

**Comment by keybreak** [comment]
That seems to be hardware specific bug, i don't have this with both of my laptops (even though i use Manjaro Deepin, not Linux Deepin).

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
