### ISSUE TITLE
待机唤醒，偶尔出现失败

### ISSUE THREAD

**Issue by jay763190097** [linuxdeepin/developer-center#1003]
![IMG_20190318_073143](https://user-images.githubusercontent.com/16317178/54499913-45e08a00-4952-11e9-99e9-02c5679dfbf5.jpg)
有使用无线键盘，但也只是偶尔失败。可能swap存的东西多的时候，会失败。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
