### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【发散测试】【系统】开机提示“x86/cpu: SGX disabled by BIOS”

### ISSUE THREAD

**Issue by kobe337** [linuxdeepin/developer-center#10032]
### SUMMARY | 问题概要

开机提示“x86/cpu: SGX disabled by BIOS”

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像版本：Deepin OS-23-20240619094316-1_x86_64
内核版本：Linux deepin-PC 6.6.40-amd64-desktop-hwe #23.01.00.33 SMP PREEMPT_DYNAMIC Thu Jul 25 15:29:39 CST 2024 x86_64 GNU/Linux
```

### PRE-REQUIREMENT | 预置条件

使用intel 8代设备

### STEPS TO REPRODUCE | 复现步骤

1. 重启系统，查看开机显示信息

### OBSERVED RESULT | 观察到的结果

开机提示“x86/cpu: SGX disabled by BIOS”
![624bc361f607df1302039386b8b0dd47_compress](https://github.com/user-attachments/assets/eb2a3c45-5f74-4a1d-9f85-ce412baf04ac)
![image](https://github.com/user-attachments/assets/78603187-d7d4-44b5-b0ae-86bdb49983fc)

### EXPECTED RESULT | 期望的结果

开机不会提示让用户产生疑惑的信息

**Comment by xzl01** [comment]
非bug，主板bios关闭了SGX，正常内核提醒

**Comment by Avenger-285714** [comment]
https://lore.kernel.org/all/D345627B0A699F37+20240730024931.1026933-1-wangyuli@uniontech.com/

**Comment by babyfengfjx** [comment]
@kobe337  请确认上述结论。

**Comment by kobe337** [comment]
与研发同事沟通，目前研发同事已将提示信息更新并提交上游，实际未有功能影响，通过讨论，此提示为内核正常输出，此issue关闭。

**Comment by Avenger-285714** [comment]
https://lore.kernel.org/all/D3C34BA892161BCF+20240731153056.303909-1-wangyuli@uniontech.com/
