### ISSUE TITLE
[New-Feature] - Sound volume effects

### ISSUE THREAD

**Issue by saymoncoppi** [linuxdeepin/developer-center#1004]
Hello Guys!I really like the effects but what do you think to add a volume option for that?This way we will have differente values for the system effects/notifications and the genaral use such as Spotfy, Netflix, Skype, VoIP and others stuffs.Follow my suggestion bellow:

![image](https://user-images.githubusercontent.com/22059715/54499374-b73b2100-48ef-11e9-8f5a-801d0dbdc87e.png)

![image](https://user-images.githubusercontent.com/22059715/54499369-aab6c880-48ef-11e9-9832-43356877deda.png)

Another useful feature considering the notification effects is decrease de other sounds when a notification will be played to get attention from the user.

I thought to add a buttom like a "decreased sound during notifications" ON/OFF bellow the original notification switch from the sound settings at Control center.
![image](https://user-images.githubusercontent.com/22059715/54499839-0b94cf80-48f5-11e9-839a-fd9be520d20c.png)

The guys from ITFOSS teachs how to do this on Ubuntu:
https://itsfoss.com/reduce-system-sound-ubuntu/

And thinking on free tones/sounds/themes, I reached this great and professional project:
http://www.iringpro.com

others sites:
https://www.lifewire.com/free-ringtone-download-sites-1356654
http://cleartones.net/
https://www.themefoxx.com/2017/08/android-oreo-stock-ringtones.html#Download_Android_Oreo_Stock_Ringtones

**Comment by saymoncoppi** [comment]
Guys! Any update about that?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
