### ISSUE TITLE
How to move our current unstable installations to the stable release ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1005]
Hey congratulations to the Deepin Team on successfully moving to Debian Stable ... I have one question though ... how can people with the Debian Unstable installations move to Debian Stable release ?

Please don't tell us to re-install afresh from an iso**(it will totally mess out daily driving machines)** ... an organic upgrade from unstable to stable would be much appreciated

**Comment by alexwender1** [comment]
The stable version released is a test version. If all goes well, this version is a kind of "15.10 Beta".
For now, the only way to use Deepin "stable" is to install this Beta.

**Comment by mpetrovic99** [comment]
15.10 stable is here so how to switch from 15.10 unstable to 15.10 stable?

**Comment by aiamuzz** [comment]
> 15.10 stable is here so how to switch from 15.10 unstable to 15.10 stable?

i really hate to have to re-install 15.10 stable from scratch ... :cry :sob: :cry: 
would be nice if there was a way to do that as a system update ... or some custom command(pointing to the stable branch) to do the same !!!

**Comment by alexwender1** [comment]
Support for the unstable version is until July 2019.

**Comment by aiamuzz** [comment]
> Support for the unstable version is until July 2019.

i am just hoping i can run a command to upgrade from unstable to stable without reinstalling from scratch !
