### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【内测反馈】【玲珑】邮箱中点击UOS AI，每次都提示“UOS AI”未安装

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#10056]
### SUMMARY | 问题概要

邮箱中点击UOS AI，每次都提示“UOS AI”未安装

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240729/
```

### PRE-REQUIREMENT | 预置条件

安装上述最新镜像
UOS AI 已安装

### STEPS TO REPRODUCE | 复现步骤

1.打开邮箱登录
2.新建邮件，在邮件中点击UOS AI图标
3.观察提示展示

### OBSERVED RESULT | 观察到的结果

1.UOS AI 已安装，邮箱中点击UOS AI，每次都提示“UOS AI”未安装
![截图_deepin-mail_20240730144149](https://github.com/user-attachments/assets/fbdadb55-bf07-4162-be35-2e99d4a89cf7)

### EXPECTED RESULT | 期望的结果

1.UOS AI 已安装，点击图标可以直接使用UOS AI

**Comment by babyfengfjx** [comment]
@dengbo11  看这个是因为玲珑的原因还是说是邮箱这边的问题。

**Comment by vivianxf** [comment]
镜像： https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240802/
org.deepin.mail:6.4.10.0
验证步骤：提单的步骤
验证结果：通过
![截图_deepin-mail_20240802155820](https://github.com/user-attachments/assets/e79faee4-5f12-4fee-85e7-b52a79c6f8b8)
