### ISSUE TITLE
The network does not rise after resuming from sleep mode

### ISSUE THREAD

**Issue by vers-2071** [linuxdeepin/developer-center#1006]
###   Adding. It would be nice to prohibit the transition to sleep mode if the computer performs work. Currently, if the transition to sleep mode is configured by the clock, the computer goes into sleep mode in any case, regardless of the processor load. Even if the computer does useful work in the background. Currently, the transition to sleep mode is based on signals from the mouse and keyboard? If so, then this is not quite the right option. It is necessary to add monitoring of the processor and network activity at least.

**Comment by ElectroPositiv** [comment]
Anyone answer me?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
