### ISSUE TITLE
换到 Debian Stable 的 Qt 版本变低了? 

### ISSUE THREAD

**Issue by CareF** [linuxdeepin/developer-center#1007]
https://github.com/CareF/deepin-dock-plugin-neoweather/issues/10

不记得是哪里看到的了但印象中以前用的是 Qt5.8, 现在降级到 5.7 了? 
这下又少了功能了.. 
会考虑把官方源里的 Qt 版本更新吗? 
尤其是 embed_translations 还是很好用的...

**Comment by BLumia** [comment]
基于目前 stable 的版本大概不会升级 Qt 版本，所以适配当前 stable 版本的时候还是考虑不要用 5.7.1+ 后面引入的新特性比较好。

目前的状况应该是会持续同时维护当前的社区版 repo 和 stable repo 的，至于其它的事情现在还没有确定下来。
