### ISSUE TITLE
[BUG] Pulseaudio - LADSPA_PATH not recognized

### ISSUE THREAD

**Issue by saymoncoppi** [linuxdeepin/developer-center#1008]
Hello guys!
I'm trying to deploy this tip below and I discovered a issue on Deepin 15.9.2 with pulseaudio 10.

**Normalize volume level with PulseAudio** [link](https://gist.github.com/lightrush/4fc5b36e01db8fae534b0ea6c16e347f)

The plugins are there:
![image](https://user-images.githubusercontent.com/22059715/54577073-20e32a00-49d9-11e9-877f-e342e9cecd0d.png)

But when I ran the next step I got this error:
![image](https://user-images.githubusercontent.com/22059715/54577093-3eb08f00-49d9-11e9-8645-7075e775084d.png)

So when I got the error messages, I researched about how to fix and I found [this](https://bbs.archlinux.org/viewtopic.php?id=238251):

> Add "export LADSPA_PATH=$libdir/ladspa:/usr/local/lib/ladspa:/usr/lib/ladspa" to ~/.xprofile 

And this other possible fix [link](https://forum.manjaro.org/t/pulseaudio-equalizer-ladspa-does-not-work-after-updating-xfce/51475/5)

Do as your normal user, not with sudo,

> systemctl edit --user pulseaudio.service
> a text editor sould open, add these lines
> 
> [Service]
> Environment="LADSPA_PATH=/usr/lib/ladspa"
> save the file and restart PulseAudio
> 
> systemctl restart --user pulseaudio.service

**Is there any plan to update the pulseaudio v10 to v12?**
Bc its fixed on that version (https://patchwork.freedesktop.org/patch/236297)

### What else happens with this issue?
If I kept the ~/.config/pulse/default.pa I got this issues:
- Volume Icon inst loaded on startup;
- Keyboard Shortcuts +/- light, +/- volume and power button stop working;
- Sound Devices properties are missing from Control Center;
- Sometimes no sound.

### Why I discovered this?
I'm planning new features to Sound Settings on Control Center,  bc this I discovered this issue.
See you guys!
Great job!
Tks!!!

**Comment by saymoncoppi** [comment]
### Adding more issues to the last list (If I kept the ~/.config/pulse/default.pa)
- Decreased boot speed
- Delay on typing password on greeter
- Key combinations like Super+D or just Super key not work

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
