### ISSUE TITLE
[Arch Linux] Dock items change their position after update

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#1009]
## Describe the bug
If, for example Firefox before update stayed first on the left, after update it will be on the most right position.

## To Reproduce
1. Dock any program
2. Update it

## Expected behavior
Should stay on exactly same position, as it was before update! :smiley: 

## Enviroments:
OS: Manjaro 18.0.4 Illyria
Kernel: x86_64 Linux 4.19.28-1-MANJARO
Shell: bash 5.0.0
DE: Deepin 15.9.2
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
bits: 64
compiler: gcc 8.2.1
tk: Qt 5.12.1
dm: LightDM

### Distro & Version
Manjaro Deepin 18.0.4

### Additional context
Applies both for Arch & Manjaro Deepin.
While thankfully this one https://github.com/linuxdeepin/developer-center/issues/831 was solved, it is still not complete experience)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
