### ISSUE TITLE
[archlinux]深度截图的添加文字功能，fcitx无法输入中文

### ISSUE THREAD

**Issue by kirigayakazushin** [linuxdeepin/developer-center#101]
不怎么用添加文字的功能，刚才突然发现不能打中文了。
警告：fcitx-gtk2-4.2.9.1-2 已经为最新 -- 重新安装
警告：fcitx-gtk3-4.2.9.1-2 已经为最新 -- 重新安装
警告：fcitx-qt4-4.2.9.1-2 已经为最新 -- 重新安装
警告：fcitx-qt5-1.0.5-3 已经为最新 -- 重新安装
环境变量也设置了，qt程序和gtk程序下均能使用fcitx进行输入。

**Comment by fasheng** [comment]
没有遇到这种问题..
```
$ pacman -Q deepin-screenshot fcitx
deepin-screenshot 3.1.8-2
fcitx 4.2.9.1-2

$ env | grep -i fcitx
GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx
```

**Comment by kirigayakazushin** [comment]
- -||  今天发现又能输入了，莫非真的重启大法好？
