### ISSUE TITLE
[Arch Linux] Now there’s a non working screensaver icon

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/developer-center#1010]
@felixonmars 
- [Screencast](https://www.youtube.com/watch?v=FZYSHWEqMU0)
- [Conversation at Manjaro](https://forum.manjaro.org/t/now-theres-a-non-working-screensaver-icon/79740/2)

**Comment by es20490446e** [comment]
--- SYSTEM SPECS ---
Manjaro Deepin Stable
xscreensaver 5.42
deepin-screensaver 0.0.7
deepin-screensaver-pp 0.0.2
deepin-file-manager 1:4.7.7.2

**Comment by felixonmars** [comment]
deepin-screensaver depends on xscreensaver for its resources. Arch did not split the xscreensaver package which brought in that desktop entry.

That's the case for many other packages too, like the qt5-tools icons in a previous bug report. Unfortunately it's the Arch way to deal with dependencies.

**Comment by keybreak** [comment]
Therefore, best thing you can do is to hide any unwanted dependency / program from your starter by editing it's **.desktop** file as root and adding:
```
NoDisplay=true
```
to
```
/usr/share/applications/xscreensaver-properties.desktop
```

**Comment by es20490446e** [comment]
Reported to Arch:
https://bugs.archlinux.org/task/62107

**Comment by es20490446e** [comment]
Won't be implemented upstream, needs to be work-around in Manjaro.

**Comment by es20490446e** [comment]
Can the desktop environment work well without deepin-screensaver installed?

**Comment by es20490446e** [comment]
I have requested Arch to make deepin-screensaver an optional dependency of deepin-daemon instead.
https://bugs.archlinux.org/task/62109

**Comment by es20490446e** [comment]
Fixed!
