### ISSUE TITLE
[文档]dde-dock的文档存在部分描述不准确

### ISSUE THREAD

**Issue by PikachuHy** [linuxdeepin/developer-center#1012]
比如

> 出于篇幅的原因这里 applet 控件就【没有，根据上下文判，这里应该少了没有】添加交互性的特性了，只用来显示一些文字

> 增减【加还是减？？？】右键菜单功能需要实现以下两个接口：

顺带试一下pr
https://github.com/linuxdeepin/dde-dock/pull/152

**Comment by listenerri** [comment]
已在 pr 回复
