### ISSUE TITLE
[Arch Linux] Settings doesn't update active theme icon

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#1013]
## Describe the bug
Settings doesn't update active theme icon on changing theme.

## To Reproduce
1. Choose any theme

## Expected behavior
Should be like before: you choose - you see the change! :smiley: 

## Screenshots
https://i.imgur.com/hO7Hi31.mp4

## Enviroments:
OS: Manjaro 18.0.4 Illyria
Kernel: x86_64 Linux 4.19.30-1-MANJARO
Shell: bash 5.0.0
DE: Deepin 15.9.2
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
bits: 64
compiler: gcc 8.2.1
tk: Qt 5.12.1
dm: LightDM

### Distro & Version
Manjaro Deepin 18.0.4

### Additional context
Confirmed on Manjaro Deepin & Arch Deepin

Tested closing and opening Settings | reboot - active icon still doesn't update.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
