### ISSUE TITLE
深度文管挂载sftp无法自动刷新的问题

### ISSUE THREAD

**Issue by lolimay** [linuxdeepin/developer-center#1014]
## 缺陷描述

使用深度文件管理器挂载 `sftp` 后，打开 `sftp` 中的某个文件夹，然后通过其它方式新建或删除该文件夹下的文件，深度文管无法及时刷新该目录（需要通过 F5 键手动刷新）。同理，右击使用 VS Code 打开该目录后，文件的删除和新建也没有及时在 VS Code 目录树上刷新（这个算深度文管的锅吗？）。
## 复现步骤

复现步骤为:
1. 打开深度文管
2. 点击地址栏，输入`sftp://192.168.2.227` 挂载 `sftp`
3. 打开sftp挂载目录
4. 通过其它方式修改该目录下的文件
5. 深度文管中无法及时刷新该目录下的文件变动（需要 F5 手动刷新）
6. 右击使用 VS Code 打开该目录，VS Code 的目录树也不能做到刷新（是深度文管没通知它刷新吗? 这一部分的具体实现机制不是很清楚就不乱说了）

## 期望行为
得到和正常使用本地磁盘一样的体验，`sftp` 目录下的文件如果因为其它方式发生了变动则在文件管理器和
VS Code 中都能立刻得到刷新，而不是需要使用 <kbd>F5</kbd> 去手动刷新一下。
## 截图

![demo](https://user-images.githubusercontent.com/32427260/54830919-5f882580-4cf4-11e9-973a-45846146b36c.gif)
<p align="center">只有手动按下 <kbd>F5</kbd>才会刷新</kbd></p>

## 复现环境:

100%复现
### 发行版以及版本

deepin 15.9.2
### 相关的软件包版本
dde-file-manager/panda,now 4.7.7.1-1 amd64 [已安装]

**Comment by lolimay** [comment]
继续跟踪了这个问题，ssh 进服务器后**重命名**相关文件后，使用 VS Code 继续编辑源文件时，发现报错如下:
````bash
[Error - 下午5:19:17] One or more errors occurred. 
(failed to parse file file:///run/user/1000/gvfs/sftp:host%3D192.168.2.227/home/
lolimay/vision/SiamFC/RGBT234_branch/curation/gen_imdb_VID.py)
````

**Comment by BLumia** [comment]
不算，gio如果没有通知文件变动的话，文管和 vscode 肯定也不会获得到这个变动通知。

不过就个人而言，我不太建议远程挂载后直接用 vscode 之类的工具编辑项目这种操作，合理使用 vcs （比如 git ）要好一些。

**Comment by lolimay** [comment]
谢谢回复和你的建议，我会尝试使用 git 去做同步的。
