### ISSUE TITLE
【deepin_V23_Release】【一般】【有空】【内测反馈】【DDE】【启动器】建议启动器屏蔽 ‘Win+向上’快捷键  和  按‘Win+向下’快捷键

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#10142]
### SUMMARY | 问题概要

![截图_选择区域_20240802131236](https://github.com/user-attachments/assets/5e185ccc-6ebb-4dd0-a26f-a0091bf40441)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
dde-shell 0.0.33
```

### STEPS TO REPRODUCE | 复现步骤

 1、点开启动器 - 按‘Win+向上’快捷键，最大化启动器 - 按‘Win+向下’快捷键

### OBSERVED RESULT | 观察到的结果

1. 启动器最大后，不可恢复
![录屏_选择区域_20240802130717](https://github.com/user-attachments/assets/b4921cf4-2c73-4f6e-a104-cc23d9f5bd8d)

### EXPECTED RESULT | 期望的结果

1. 启动器屏蔽 ‘Win+向上’快捷键  和  按‘Win+向下’快捷键

**Comment by babyfengfjx** [comment]
@yixinshark  请安排优化~

**Comment by xionglinlin** [comment]
关联 #10122
