### ISSUE TITLE
org.deepin.mail 6.4.10.0 集成

### ISSUE THREAD

**Issue by dengbo11** [linuxdeepin/developer-center#10143]
### package information | 软件包信息

org.deepin.mail | 6.4.10.0

### Package repository address | 软件包仓库地址

name: old url: http://repo-dev.cicd.getdeepin.org/

### changelog | 更新信息

1. 修改玲珑仓库，ll-cli repo modify http://repo-dev.cicd.getdeepin.org --name old
2. 安装最新org.deepin.mail(ll-cli install org.deepin.mail/6.4.10.0)
3. 验证bug是否解决

### Sphere of influence | 影响范围

- https://github.com/linuxdeepin/developer-center/issues/10056
- https://github.com/linuxdeepin/developer-center/issues/8733
- https://github.com/linuxdeepin/developer-center/issues/9639

**Comment by babyfengfjx** [comment]
@vivianxf  请开展回归验证。

**Comment by vivianxf** [comment]
集成测试通过，请及时合入：

1.切换仓库，安装邮箱成功
2.issues： #10056， #8733, #9639 验证通过
3.玲珑基本功能正常

综上所述，本次集成通过～

**Comment by dengbo11** [comment]
已同步外网
