### ISSUE TITLE
Magnetic borders for Desktop arrangements

### ISSUE THREAD

**Issue by ChimPthePimP** [linuxdeepin/developer-center#1016]
Would be great to get magnetic borders for multiple desktop usage, i ve experienced quite some moments where the shown desktop was overlaying on the one next to it.. So maybe with magnetic borders it would get way easy to allign the desktops correctly, the way you want it

**Comment by alexwender1** [comment]
It seems that they will adopt the KWin and insert these features.

A screenshot that appeared last year shows a little of what can be done:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/45263160/54867665-98121880-4d61-11e9-8cf2-11f1cb4660a3.gif)

**Comment by ChimPthePimP** [comment]
I love these kwin features but what my suggestion was aiming at or what i intended was to use multiple monitor arrangement and being able to adjust the position of desktops with aid of magnetic borders...

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
