### ISSUE TITLE
文件管理器通过右键菜单彻底删除文件时不进行二次确认

### ISSUE THREAD

**Issue by CJ6922G1CH** [linuxdeepin/developer-center#1017]
## 缺陷描述
文件管理器中，按住Shift键，在右键菜单中选择删除文件，没有二次确认对话框，直接永久删除。而使用Shift+Del快捷键有二次确认对话框

## 复现步骤
在文管中删除文件即可复现

## 期望行为
永久删除文件之前弹出二次确认对话框

### 发行版以及版本
Deepin 15.9.2
### 相关的软件包版本
dde-file-manager最新版

**Comment by hualet** [comment]
@BLumia

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
