### ISSUE TITLE
[Feature Request] 深度截图集成OCR

### ISSUE THREAD

**Issue by PikachuHy** [linuxdeepin/developer-center#1019]
深度截图是非常棒的截图软件，只是不支持OCR在某些时候不方便。
OCR的使用场景：
- 从扫描版 PDF 中提取文字
- 从朋友发来的图片中识别文字
- 从任意图片中识字

难点：
- 识别的准确率
想要高准确率就可能需要使用第三方平台OCR服务，离线的识别比如OCRFeeder可能不能保证准确率。使用第三方服务，量大的话，需要付费。如果让用户自己配置，体验上会不好，与deepin理念有冲突。
- 识别出来的文字的展示
第三方平台比如百度OCR是按行返回的识别结果，需要客户端对识别结果进行优化再展示。比如
    - 自动识别段落
    - 中文环境使用全角标点符号
    - 中文与英文字母、数字间增加空格
    - 删除中文字符间、英文字符与标点符号间的多余空格
    - 英文首字母大写
其他扩展功能：
- 识别的文字进行翻译
- 识别公式

其他OS的实现
mac: [iText](https://toolinbox.net/iText/)  每月可免费识别 20 次，付费可以无限次识别
windows: [天若ocr文字识别工具](https://www.52pojie.cn/thread-692917-1-1.html) 原本免费，后来出了专业版，开源版本由新的人维护

deepin上与深度截图集成的参考实现DEMO
![demo](https://raw.githubusercontent.com/PikachuHy/deepin-screenshot/learn/ocr_demo.gif)
代码： [深度截图集成OCR Demo](https://github.com/PikachuHy/deepin-screenshot/tree/learn)

**Comment by BLumia** [comment]
其实可以考虑给截图做插件支持，然后允许第三方的这类实现。

**Comment by PikachuHy** [comment]
插件倒是一个不错的主意，还可以集成截图上传图床（比如七牛云）等

**Comment by lolimay** [comment]
学长是真的强！提issue直接就带demo了...

**Comment by ziqiangxu** [comment]
同志们，很给力啊

**Comment by rekols** [comment]
可以集成个 tesseract

**Comment by sonichy** [comment]
没有免费的OCR服务啊

**Comment by jahentao** [comment]
很棒啊，文字识别急需的，赶紧PR啊

**Comment by jahentao** [comment]
> 深度截图是非常棒的截图软件，只是不支持OCR在某些时候不方便。
> OCR的使用场景：
> 
> * 从扫描版 PDF 中提取文字
> * 从朋友发来的图片中识别文字
> * 从任意图片中识字
> 
> 难点：
> 
> * 识别的准确率
>   想要高准确率就可能需要使用第三方平台OCR服务，离线的识别比如OCRFeeder可能不能保证准确率。使用第三方服务，量大的话，需要付费。如果让用户自己配置，体验上会不好，与deepin理念有冲突。
> * 识别出来的文字的展示
>   第三方平台比如百度OCR是按行返回的识别结果，需要客户端对识别结果进行优化再展示。比如
>   
>   * 自动识别段落
>   * 中文环境使用全角标点符号
>   * 中文与英文字母、数字间增加空格
>   * 删除中文字符间、英文字符与标点符号间的多余空格
>   * 英文首字母大写
>     其他扩展功能：
> * 识别的文字进行翻译
> * 识别公式
> 
> 其他OS的实现
> mac: [iText](https://toolinbox.net/iText/) 每月可免费识别 20 次，付费可以无限次识别
> windows: [天若ocr文字识别工具](https://www.52pojie.cn/thread-692917-1-1.html) 原本免费，后来出了专业版，开源版本由新的人维护
> 
> deepin上与深度截图集成的参考实现DEMO
> ![demo](https://raw.githubusercontent.com/PikachuHy/deepin-screenshot/learn/ocr_demo.gif)
> 代码： [深度截图集成OCR Demo](https://github.com/PikachuHy/deepin-screenshot/tree/learn)

老哥，能先release一个版本吗

**Comment by PikachuHy** [comment]
我很早就放了一个自己用的二进制文件
把深度截图原来的换掉就好了
https://github.com/PikachuHy/deepin-screenshot/releases

**Comment by lolimay** [comment]
> 我很早就放了一个自己用的二进制文件
> 把深度截图原来的换掉就好了
> https://github.com/PikachuHy/deepin-screenshot/releases

学长加油，争取早日发布到商店里😀

**Comment by hualet** [comment]
@PikachuHy 不来个PR么？

**Comment by hualet** [comment]
> @PikachuHy 不来个PR么？

Sorry，被同事喷了，还是支持插件机制好一点 :sob:

**Comment by PikachuHy** [comment]
@hualet 
基于以下考虑，我认为不能PR
- 这个仅仅是一个演示Demo，刚刚好满足我现在的需求
- 没有免费的高质量OCR服务，想要识别效果好，第三方服务要收费的。需要支持订阅，或者引导用户配置第三方服务
- 未来要支持公式识别，翻译等。（可以对标天若OCR）
- 未来要支持多种图床，截图直接上传到七牛云（用户可选）等，转换为url地址或者md格式的图片
这要是PR上去，我就没法改了。做插件，我的自由度就比较高了。

最后催一下这个PR： 
https://github.com/linuxdeepin/dde-dock/pull/152
@BLumia  @listenerri  (13 days ago 😂)
review都过了，到底是合还是不合。。。

**Comment by BLumia** [comment]
> @hualet
> 基于以下考虑，我认为不能PR
> 
> * 这个仅仅是一个演示Demo，刚刚好满足我现在的需求
> * 没有免费的高质量OCR服务，想要识别效果好，第三方服务要收费的。需要支持订阅，或者引导用户配置第三方服务
> * 未来要支持公式识别，翻译等。（可以对标天若OCR）
> * 未来要支持多种图床，截图直接上传到七牛云（用户可选）等，转换为url地址或者md格式的图片
>   这要是PR上去，我就没法改了。做插件，我的自由度就比较高了。

未来考虑做插件支持吧。不过如果你这边想要给截图直接增加插件支持的话也可以做一做发个 PR :)

> 最后催一下这个PR：
> [linuxdeepin/dde-dock#152](https://github.com/linuxdeepin/dde-dock/pull/152)
> @BLumia @listenerri (13 days ago )
> review都过了，到底是合还是不合。。。

build 失败了，刚重新触发了一下，等编译过了再合（（（（（

**Comment by jahentao** [comment]
@PikachuHy  为啥实现DEMO被删除了

**Comment by PikachuHy** [comment]
@jahentao 不用deepin了，之前的代码应该都删除，忘了存档
你可以自己实现一个，很简单的
