### ISSUE TITLE
Add keybinding support for xkill just like KDE did

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/developer-center#102]
From  @bigbruno
> I'm use kde for long years and migrate for Deepin, in kde shortcut Esc+Alt+Ctrl open xkill, this is simple, but very good feature.
> 
> Maybe if add this feature in default configuration of Deepin, and maybe adding one alert about usage of this feature.

https://github.com/linuxdeepin/dde-desktop/issues/4

**Comment by manateelazycat** [comment]
User can do this through add keybind in dde-control-center. We won't provide this feature to confuse generic user.
