### ISSUE TITLE
[Feature Request] Pre-Installed Applications and Deepin Introdution

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#1020]
## Describe the bug
Currently, Deepin brings 30 pre-installed applications (and continues to grow with each new version of the system).

Users are starting to talk that Deepin is the bloatwares system. For many applications, they present the very specific use; and does not need to come pre-installed on the system.

My suggestion is that you substantially reduce the number of pre-installed applications (leaving essential applications). In return, Deepin Introduction should display a page suggesting the installation of some useful applications (the user would choose to download or not).

I think of these applications as essential (they must come pre-installed on the system):
Deepin AppStore
Deepin Editor
Deepin File Manager
Deepin Graphic Manager
Deepin Image Viewer
Deepin Introdution
Deepin Movie
Deepin Music
Deepin Repair
Deepin Screenshot
Deepin System Monitor
Deepin Terminal
Evince
File Roller
Google Chrome

I consider these applications as specific functionality (which should not come pre-installed). If they do not agree, I'm happy to discuss the functionality of each application; for you to understand me:
*Adobe Flash Player for Chrome
*Deepin Boot Maker
*Deepin Calculator
*Deepin Cloud Print
*Deepin Cloud Scan
*Deepin Font Installer
*Deepin Manual
*Deepin OpenSymbol
*Deepin Package Manager
*Deepin Voice Recorder
*GParted
*Simple Scan
*Thunderbird

I do not know if there is any commercial agreement to license these applications; would also put them on the list of "specific functions" ... When the user comes across Deepin Introduction, you will see the download suggestion for these applications:
*Skype
*Spotify
*WPS Office

### Additional context
If possible, we will try to deliver Deepin with a maximum of 15 pre-installed applications. And give (make useful) more features to Deepin Introduction.

I repeat again, if someone does not agree to the removal of any application; I am willing to explain why it is in my interest to remove it.

**Comment by keybreak** [comment]
I'd personally disagree with you on everything, except:
*Deepin Cloud Print
*Deepin Cloud Scan
*Simple Scan
*Skype
*Spotify

Because those are not intended for every user...
And everything from a Microsoft should be shameful & strictily optional :+1: 

Why would you want to remove GParted ?
You need to have something in the system, for working with disks in simple GUI fashion.

And also i really don't get how can someone possibly hate WPS Office (as much as people for some reason actually do on Linux). At least outside of some agreement business...

In my opinion it's the best alternative for Microsoft Office in terms of:
1. Real full compatibility with any documents unlike let's say Libre Office (i've used WPS for year on Windows and can approve it)
2. It's really lightweight
3. It's extremely fast (You can actually write whole document on WPS, before Libre even launch :rofl: )

So i personally highly appreciate it's included and available in repo by default :smile_cat:

**Comment by alexwender1** [comment]
> I'd personally disagree with you on everything, except:
> *Deepin Cloud Print
> *Deepin Cloud Scan
> *Simple Scan
> *Skype
> *Spotify
> 
> Because those are not intended for every user...
> And everything from a Microsoft should be shameful & strictily optional 
> 
> Why would you want to remove GParted ?
> You need to have something in the system, for working with disks in simple GUI fashion.
> 
> And also i really don't get how can someone possibly hate WPS Office (as much as people for some reason actually do on Linux). At least outside of some agreement business...
> 
> In my opinion it's the best alternative for Microsoft Office in terms of:
> 
> 1. Real full compatibility with any documents unlike let's say Libre Office (i've used WPS for years on Windows and can approve it)
> 2. It's really lightweight
> 3. It's extremely fast (You can actually write whole document on WPS, before Libre even launch rofl )
> 
> So i personally highly appreciate it's included and available in repo by default 
> 
> P.S. Maybe installer should just have some **Advanced** option, where you can choose which programs should be isntalled?

I do not want to discuss whether a certain tool is good or bad ... on the contrary, I want the user to have access to the most varied tools.

I would like to see Deepin Introduction behave like the MATE Desktop Environment's Boutique Software; suggesting applications that have been curated by the community.

Why offer the WPS Office pre-installed, if the user can opt for LibreOffice, Only Office and Free Office (we will give option of choice to users).

When someone has just installed Deepin, it is not logical to create a bootable pendrive (that's why I'm talking about removing Deepin Boot Maker) ... the user wants to enjoy the system.

And the disk management provided by GParted is performed by more advanced and specific users (and generally, who formats the computer will not be tinkering with the disk later ... this is not common). Therefore, I classify GParted as a tool for specific users (as well as Spotify, as you rated above).

Instead of forcing the user to use the tools chosen by the development team; the community will have more importance in suggesting such applications (the user will see the options when launching Deepin for the first time)... and the user (especially the layman) will have autonomy in choosing their applications.

It is noticeable that we have pre-installed applications that are not used by most users (only by a small, specific audience).

**Comment by keybreak** [comment]
Well, you got point.
Giving choise - would be good.

> And the disk management provided by GParted is performed by more advanced and specific users (and generally, who formats the computer will not be tinkering with the disk later ... this is not common). 

But this i can not agree at all. This is absolute must for any user-friendly OS to be installed from the start, without internet and any form of additional interaction.

It's basic system task, since you not limited to single install only, far more than 50% users tend to change their drives, add new, remove, format phsyical drives (it's not all about partitions of system drive).

**Comment by alexwender1** [comment]
> Well, you got point.
> Giving choise - would be good.
> 
> > And the disk management provided by GParted is performed by more advanced and specific users (and generally, who formats the computer will not be tinkering with the disk later ... this is not common).
> 
> But this i can not agree at all. This is absolute must for any user-friendly OS to be installed from the start, without internet and any form of additional interaction.
> 
> It's basic system task, since you not limited to single install only, i'm sure that far more than 50% of users tend to change their drives, add new, remove, format phsyical drives (it's not all about partitions of system drive).

Do you talk about removable storage devices?

For basic tasks ... the File Manager itself can handle (format and change the file system). Obviously, more advanced things are done by GParted or with Gnome Disks.

My concern is that the layman can mess with it ... and ruin everything. And for the advanced user, it does not cost anything to download the Store (since GParted is not as popular as Google Chrome, for example).

**Comment by keybreak** [comment]
All of them, HDD / SSD / USB it doesn't really matter...
I personally wouldn't rely on Deepin file manager yet, since it's rapid development phase now.

My point:
- It's way too overkill to drop one of the main important tools of any OS
- Worst thing could happen to layman if he try to open this program - he'll close it out of fear or learn something new :laughing: 
- It's really bad not to have it installed by default and rely on store for such basic stuff, because there are some situations in many parts of the World that you would have to be completely offline with your .iso.

**Comment by alexwender1** [comment]
> All of them, HDD / SSD / USB it doesn't really matter...
> I personally wouldn't rely on Deepin file manager yet, since it's rapid development phase now.
> 
> My point:
> 
> * It's way too overkill to drop one of the most important tools of any OS
> * Worst thing could happen to layman if he try to open this program - he'll close it out of fear or learn something new laughing
> * It's really bad not to have it installed by default and rely on store for such basic stuff, because there are some situations in many parts of the World that you would have to be completely offline with your .iso.

For locations without internet access, Endless OS is the best choice! Unfortunately, this is just a "justification" for maintaining this huge amount of pre-installed applications.

But I appreciate the interest in discussing your doubts about it.

**Comment by Maxximo88** [comment]
I agree on mandatory software!
Let users choose their preferred pre-installare software!

**Comment by alexwender1** [comment]
![photo5037719046337964113](https://user-images.githubusercontent.com/45263160/61997309-03ecf080-b076-11e9-837f-a440c03613cf.jpg)

Nearly 30???

The release note of version 15.11 mentions that the system comes with approximately 30 preinstalled applications (deepin apps?).

I identified a total of 40 preinstalled applications (2 of these, hidden - FlashPlayer and OpenSymbol).

Again, I suggest reducing the amount of applications preinstalled on the system.

**Comment by aiamuzz** [comment]
Well ... 2 opinions already IN ... 3rd one entering ...

I personally would say ... **all Deepin Applications being pre-installed in principle is perfectly in order** ... including the exceptions marked by @keybreak ... :smile: 

1. Sweat and Blood have gone into its creation.
2. If its not pre-installed in all probability people wouldn't know of their existenc at all, wasting sweat and blood that has gone into their creation.
3. As we have come to realize ... Deepin seems like a low budget low resource endeavor ... marketing and advertising their hard work(Deepin Applications) is best done when they are pre-installed with their OS as well as on their DDE ports for other distro's

Coming to non-deepin pre-installed apps ... they are only a few ...

**Gparted**
I agree with @keybreak ... that 'gparted' is a mandatory pre-installed on all linux distro's not just Linux Deepin ... in spite of it being an advanced tool ... there are **So this app too in principle clears the pre-installed whitelist** ... 

**Simple Scan**
Its just like how a print manager is an app to support a printer hardware ... Simple Scan is kind of a similar utility that give the user an out of the box option to manage another hardware(a scanner) just like a printer.

**WPS Office(or any other Office document handling app)**
Again an OS which cannot have an out-of-the-box option to open office documents will be a no brainer ... Just like how a pre-installed browser is a necessity

**ThunderBird**
Again in principle a mail client on an OS pre-installed isn't too much of an over head on the OS ... similar to the above non-deepin pre-installed apps

that leaves us with ...
Skype
Spotify

**So are we ... arguing on how 2 apps are bloating the OS ?**

:laughing: ...

In principle any OS has to have some basic functionalities out of the box ... and of all the apps that you've listed @alexwender1 ... they seem to follow that principle ...

We should not forget that certain apps could even provide incentive to OS developers to pre-install their apps on their OSes ... and an incentive to a low budget ... low resource endeavor should have some room to maneuver so they can profit from such initiatives.

**Linux Deepin can never be accused of being a bloatware mule !!!**

**We should be raising an issue only if they restrict certain pre-installed from being uninstalled ... are they ???**

**Comment by alexwender1** [comment]
In the list (March) we had 33 applications preinstalled; now there are 40!

I hope Deepin ID brings more information. And we need to discuss (with the development team) this situation.
