### ISSUE TITLE
org.deepin.browser 集成申请

### ISSUE THREAD

**Issue by dengbo11** [linuxdeepin/developer-center#10217]
### package information | 软件包信息

org.deepin.browser | 6.5.5.1

### Package repository address | 软件包仓库地址

name: old url: http://repo-dev.cicd.getdeepin.org/

### changelog | 更新信息

1. 修改玲珑仓库，ll-cli repo modify http://repo-dev.cicd.getdeepin.org --name old
2. 安装最新org.deepin.browser(ll-cli install org.deepin.browser/6.5.5.1)
3. 验证bug是否解决

### Sphere of influence | 影响范围

https://pms.uniontech.com/bug-view-267437.html
https://pms.uniontech.com/bug-view-267421.html
关联的github issues 也请更新状态

**Comment by babyfengfjx** [comment]
@vivianxf  请开展回归验证。

**Comment by vivianxf** [comment]
集成验证通过，请及时合入：

1.新版镜像中已经合入最新版本浏览器，版本正确
2.pms bug验证通过:https://pms.uniontech.com/bug-view-267437.html https://pms.uniontech.com/bug-view-267421.html
3.浏览器基本功能正常
4.系统基本功能正常

综上所述，本次集成通过～

**Comment by dengbo11** [comment]
@myml ,浏览器可以推送外网仓库了
