### ISSUE TITLE
能不能在右键菜单增加发送到手机功能

### ISSUE THREAD

**Issue by jinshuichengliu** [linuxdeepin/developer-center#1021]
## 缺陷描述

比如说手机微信，选择聊天窗口中的图片后，就可以调用出手机中装的可以发送图片的应用，比如sendanywhere。
如果可以右键菜单加个这样的功能会方便很多。

**Comment by hualet** [comment]
有插件接口，要试着撸一个么？
https://linuxdeepin.github.io/dde-file-manager/context-menu-ext-zh.html

**Comment by meiyixiang** [comment]
商店有手机助手这个应用可以试一下
