### ISSUE TITLE
[Manjaro] Dual-Monitor: dde-desktop non-functional on launch in dual monitor set-up, only works on primary monitor after pkill

### ISSUE THREAD

**Issue by bentrop** [linuxdeepin/developer-center#1022]
## Describe the bug
This is on the latest Manjaro Deepin flavor. The desktop part of Deepin DE is non-functional after boot on all monitors. No right-click menu, no visible icons or folders. dde-desktop is running but effectively 100% non-functional.
This isn't a new bug but coming from "we don't need a desktop" Gnome 3 it took me a while to even notice. :-)

## To Reproduce
With a single monitor connected everything is working as expected.
Attaching a secondary monitor causes dde-desktop be non-functional after startup/login.
Killing and relaunching the dde-desktop process manually after boot makes the desktop functional again, but on the primary display _only_
Icons can't be dragged an dropped to the secondary display and the right-click menu is only functional on the primary monitor.

## Expected behavior
Desktop icons and desktop right click menu are functional on all attached monitors upon launch.

### Distro & Version
Manjaro Deepin Stable & Testing

This is on an i5-3750k with AMD graphics (RX 580)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
