### ISSUE TITLE
[dev] setIcon 频率过高会导致托盘图标无法正常显示

### ISSUE THREAD

**Issue by lolimay** [linuxdeepin/developer-center#1023]
![image](https://user-images.githubusercontent.com/32427260/54925827-1204f600-4f4a-11e9-9ec9-68b7ef862327.png)

最近发现如果 `systemTrayIcon->setIcon` 被调用的时间间隔低于 150ms，则托盘中的图标无法正常显示。之前是没有问题的，是不是最近的 dde-dock 更新后导致的呢?

If it is by design, 当我什么都没说 😂

**Comment by keybreak** [comment]
@BLumia @hualet @zccrs @oberon-manjaro

> My Deepin dock is constantly resetting itself randomly (very frequently - every couple minutes), it disappears and then has to take a few short seconds to reload everything again in the tray. I did not have this issue at all until today when one update for dtkwidget came out. I think I may have to figure out how to revert an update because this bug is not a good one to have.

https://forum.manjaro.org/t/deepin-bug-after-dtkwidget-update/80470

I confirm it dock constantly crash, especially if you load some program with tray icon like Deluge, it came with Manjaro update of dtkwidget  **2.0.9.17-2.2**

Stop breaking things please :smiley_cat:

**Comment by BLumia** [comment]
> Not sure entirely, since i have to use chinese-english translate, but it seems to be same issue here
> > My Deepin dock is constantly resetting itself randomly (very frequently - every couple minutes), it disappears and then has to take a few short seconds to reload everything again in the tray. I did not have this issue at all until today when one update for dtkwidget came out. I think I may have to figure out how to revert an update because this bug is not a good one to have.

It's probably not the same issue, the issue caused by dtkwidget is fixed recently (https://github.com/linuxdeepin/dtkwidget/pull/17) and maybe we just need a new tag release.

> Stop breaking things please

We both don't want to break things........

**Comment by keybreak** [comment]
@BLumia 
@oberon-manjaro mentioned it was caused with intent to fix this old bug (timer patch):
https://github.com/linuxdeepin/developer-center/issues/250

**Comment by listenerri** [comment]
> 最近发现如果 `systemTrayIcon->setIcon` 被调用的时间间隔低于 150ms，则托盘中的图标无法正常显示。之前是没有问题的，是不是最近的 dde-dock 更新后导致的呢?

请描述下 “不能正常显示” 的现象或者给个录屏

**Comment by listenerri** [comment]
可能是因为 dock 的代码里限制了图标刷新的频率

**Comment by zccrs** [comment]
dock 托盘图标绘制可以改成用 x damage实现

**Comment by sonichy** [comment]
150ms你反应的过来么？

**Comment by lolimay** [comment]
> 150ms你反应的过来么？

实测设置刷新间隔为 200ms 也不会太影响体验，但如果能设低我偏向于设低一点。

**Comment by listenerri** [comment]
> > 150ms你反应的过来么？
> 
> 实测设置刷新间隔为 200ms 也不会太影响体验，但如果能设低我偏向于设低一点。

你是打算显示动画吗？

**Comment by lolimay** [comment]
![Peek 2019-04-01 17-05](https://user-images.githubusercontent.com/32427260/55316272-a0283180-54a0-11e9-8434-a2e20adce791.gif)

显示小飞机的流量上下标

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
