### ISSUE TITLE
[BUG] pulseaudio-equalizer from deepin repository doens't run. Missing files

### ISSUE THREAD

**Issue by saymoncoppi** [linuxdeepin/developer-center#1025]
Hello Guys!
Tks for your attention again. These days I shared an issue ([isseu report #1008](https://github.com/linuxdeepin/developer-center/issues/1008)) about the pulseaudio current version from the deepin repository. I guess you already seen.

So since that i discovered another one related with pulseaudio-equilizer.
If i get the [latest .deb](https://launchpad.net/~nilarimogard/+archive/ubuntu/webupd8/+sourcepub/9584592/+listing-archive-extra) from [webupd8](https://launchpad.net/~nilarimogard/+archive/ubuntu/webupd8/+packages?field.name_filter=pulseaudio&field.status_filter=published&field.series_filter=) and install here, its works for a few days and "boom" desapear from the system.

Due this i thought to use the version from the deepin current repository (v10.0-7) but it doens't work... 

## It isn't present at the laucher after the installation 
_The installation process doesn't create gpaeq.desktop (or pulseaudio-equalizer.desktop) at /usr/share/applications folder._

![Captura de Tela_20190327092649](https://user-images.githubusercontent.com/22059715/55075752-8470f580-5072-11e9-9b58-359ea313fbe7.png)

## It is there:
![Captura de Tela_selecionar área_20190327093015](https://user-images.githubusercontent.com/22059715/55075951-fb0df300-5072-11e9-8c42-4475390de82b.png)

## If I ran by terminnal:

![Captura de Tela_selecionar área_20190327093220](https://user-images.githubusercontent.com/22059715/55076063-3c9e9e00-5073-11e9-916e-01cf25417db6.png)

**I got this:**

> (python:10356): Gtk-WARNING **: 09:31:06.382: Não foi possível localizar a ferramenta de temas no module_path: "adwaita",
> 
> (python:10356): Gtk-WARNING **: 09:31:06.383: Não foi possível localizar a ferramenta de temas no module_path: "adwaita",
> There was an error connecting to pulseaudio, please make sure you have the pulseaudio dbus module loaded, exiting...

## Checking the resource differences betwen the deepin pkg and the latest from webupd8:
![Captura de Tela_selecionar área_20190327094241](https://user-images.githubusercontent.com/22059715/55076629-b1bea300-5074-11e9-8dd3-40ed6abee843.png)

saymoncoppi@ultrabook:~$ dpkg -L pulseaudio-equalizer 
/.
/usr
/usr/bin
/usr/bin/pulseaudio-equalizer
/usr/bin/pulseaudio-equalizer-gtk
/usr/share
/usr/share/pulseaudio-equalizer
/usr/share/pulseaudio-equalizer/presets
/usr/share/pulseaudio-equalizer/presets/Club.preset
/usr/share/pulseaudio-equalizer/presets/Ska.preset
/usr/share/pulseaudio-equalizer/presets/Full Treble.preset
/usr/share/pulseaudio-equalizer/presets/Reggae.preset
/usr/share/pulseaudio-equalizer/presets/Pop.preset
/usr/share/pulseaudio-equalizer/presets/Large Hall.preset
/usr/share/pulseaudio-equalizer/presets/Live.preset
/usr/share/pulseaudio-equalizer/presets/Techno.preset
/usr/share/pulseaudio-equalizer/presets/Laptop.preset
/usr/share/pulseaudio-equalizer/presets/Full Bass.preset
/usr/share/pulseaudio-equalizer/presets/Dance.preset
/usr/share/pulseaudio-equalizer/presets/Soft.preset
/usr/share/pulseaudio-equalizer/presets/Rock.preset
/usr/share/pulseaudio-equalizer/presets/Headphones.preset
/usr/share/pulseaudio-equalizer/presets/Flat.preset
/usr/share/pulseaudio-equalizer/presets/Soft Rock.preset
/usr/share/pulseaudio-equalizer/presets/Classical.preset
/usr/share/pulseaudio-equalizer/presets/Full Bass & Treble.preset
/usr/share/pulseaudio-equalizer/presets/Party.preset
/usr/share/pulseaudio-equalizer/pulseaudio-equalizer.py
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/pulseaudio-equalizer
/usr/share/applications
/usr/share/applications/pulseaudio-equalizer.desktop
/usr/share/menu
/usr/share/menu/pulseaudio-equalizer
/usr/share/doc
/usr/share/doc/pulseaudio-equalizer
/usr/share/doc/pulseaudio-equalizer/copyright
/usr/share/doc/pulseaudio-equalizer/changelog.Debian.gz

## Could you update pulseaudio version on next release?
PLS pls Pls pLs plS

best regards! See you guys.

**Comment by hualet** [comment]
We're now working on a version based on Debian Stable, you can try it when it's available hopefully in April.

**Comment by saymoncoppi** [comment]
hello @hualet tks for your answer... did u check the other issue related here? About pulseaudio path? I guess maybe the relevance of this is higher than eqs. what do u think? Maybe the upgrade do stable also fix this.

**Comment by hualet** [comment]
@electricface

**Comment by electricface** [comment]
https://stackoverflow.com/questions/13403314/contacting-pulse-audio-over-dbus

**Comment by electricface** [comment]
The pulseaudio-equalizer package does not provide any *.desktop files, so you can't find it from dde-launcher.

**Comment by lxwndr** [comment]
The application continues with the same problems; without displaying the audio presets.

![Captura de Tela_qpaeq_20210205143246](https://user-images.githubusercontent.com/45263160/107098933-304b0680-67ef-11eb-8b4b-d8d8d4cf46c3.png)

deepin 20.1 (1030) | OsBuild=11031.002

**Comment by Zeno-sole** [comment]
what application is this? Does the app configuration fail?

**Comment by Zeno-sole** [comment]
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue
