### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【内测反馈】【DDE】【任务栏】新装镜像或者在使用过程中，会报错“Tray Plugin Crashed”,偶现问题（出现几次）

### ISSUE THREAD

**Issue by kobe337** [linuxdeepin/developer-center#10256]
### SUMMARY | 问题概要

论坛反馈链接：1、 https://bbs.deepin.org/post/276183 2、https://bbs.deepin.org/zh/post/276126 3、https://bbs.deepin.org/post/275794
新装镜像或者在使用过程中，会报错“Tray Plugin Crashed”

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像版本：Deepin OS-23-20240802022253-1_x86_64
组件版本：dde-shell: 0.0.33
```

### STEPS TO REPRODUCE | 复现步骤

1、新装镜像或者在日常使用过程中，观察通知中心内的消息

### OBSERVED RESULT | 观察到的结果

新装镜像或者在使用过程中，会报错“Tray Plugin Crashed”
![image](https://github.com/user-attachments/assets/363f4753-fc7b-460a-b3d2-e7fa1f99288c)

### EXPECTED RESULT | 期望的结果

新装镜像或者在使用过程中，不会报错“Tray Plugin Crashed”，插件组件均稳定运行

**Comment by yixinshark** [comment]
之前有些插件未有适配dde-tray-loader的接口导致的问题，目前已无此情况。请验证。

**Comment by kobe337** [comment]
【环境】：
镜像：Deepin OS-23-20240813103808-1_x86_64
内核：Linux hhh-PC 6.6.47-amd64-desktop-hwe #23.01.00.37 SMP PREEMPT_DYNAMIC Tue Aug 20 17:33:52 CST 2024 x86_64 GNU/Linux

【结论】：
回归测试通过，暂无严重问题及影响, 安装镜像，观察通知中心消息，验证通过。
