### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【发散测试】【深度之家】 不要默认自启动深度之家

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#10265]
### SUMMARY | 问题概要

2.不要默认自启动深度之家
深度之家改为，不自启动

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
dde-shell 0.0.34
```

### STEPS TO REPRODUCE | 复现步骤

1. 安装最新镜像，查看深度之家是否自启动

### OBSERVED RESULT | 观察到的结果

深度之家自启动

### EXPECTED RESULT | 期望的结果

深度之家不自启动

**Comment by babyfengfjx** [comment]
@myml  请优先帮忙处理。

**Comment by myml** [comment]
已提交集成
https://github.com/linuxdeepin/developer-center/issues/10274
