### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【发散测试】【系统】桌面上放置 我的电脑 浏览器 深度之家 帮助

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#10266]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
dde-shell 0.3.34
```

### STEPS TO REPRODUCE | 复现步骤

1. 安装最新镜像，查看桌面默认应用

### OBSERVED RESULT | 观察到的结果

桌面上默认应用不符合需求

### EXPECTED RESULT | 期望的结果

桌面上放置 我的电脑 浏览器 深度之家 帮助

**Comment by babyfengfjx** [comment]
@Zeno-sole 请优先处理~

**Comment by babyfengfjx** [comment]
@luodeepin  这个应该已经处理了，可以回归。

**Comment by luodeepin** [comment]
验证通过
https://cdimage.uniontech.com/daily-iso/image-beige/release/amd64/deepin-desktop-community-23-amd64.iso
