### ISSUE TITLE
request to make deepin-anything optional

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/developer-center#1026]
There have been repeated rumors that Deepin Desktop is collecting and sending data. Although this has never been proven and also officially been denied by Deepin, in my eyes the concept of **deepin-anything** and its imperative installation with Deepin Desktop adds to this less than ideal image.
Afaik the only purpose of this kernel-module is to enhance speed of file searches, at least that's what I gathe from the README.
Now I must say that I am not at all happy with my system being completely searched and indexed like that and I would definitely want an option to deactivate this feature.
My understanding is further that no other parts of the Deepin environment actually need the module to work.
So I would like to request to make the installation optional.
Thank you.
@felixonmars

**Comment by felixonmars** [comment]
libdde-file-manager links to libanything, so it cannot be made optional without some upstream splitting, unless we split deepin-anything further (which we would like to avoid in Arch).

**Comment by oberon-manjaro** [comment]
Thanks for the explanation @felixonmars

**Comment by BLumia** [comment]
Fedora had a "no external kernel modules" rule, not sure if they still have that rule. Fedora seems got DDE support, maybe you can checkout how they did the packaging job.

FYI the deepin-anything kernel module uses the `vfs_monitor` to provide the file state indexing/monitor job, the file manager app itself use deepin-anything to do "fast search" and "tag color". Actually there is a `CONFIG += DISABLE_ANYTHING` which can be used to disable deepin-anything related features from the file manager side, as the result, "fast search" and "tag color" will be disabled. You can use that build option if you really want to get rid of deepin-anything.

Some off-topic thing: As you mentioned, the "Deepin Desktop is collecting and sending data" rumor may probably referenced to the old behavior of Deepin Store. Deepin Store is a Q[CEF](https://en.wikipedia.org/wiki/Chromium_Embedded_Framework) application which embed the deepin store website inside the application, and the website was used a Chinese locale traffic analysis service (just like google-analysis) provider's service (cnzz). Thus it makes deepin-store behavior like it is sending data to 3rd party service provider. (ps. [there is a official statement for that](https://www.deepin.org/en/2018/04/14/linux-deepin-is-not-spyware/), and the cnzz service is already removed from the deepin store website for a long time).

**Comment by oberon-manjaro** [comment]
@BLumia this sounds very promising and it would be great if we had the option to build **deepin-file-manager** without the module. Unfortunately with the config `DISABLE_ANYTHING` set, build fails with errors:
```
controllers/filecontroller.cpp:208:54: error: expected ‘)’ before ‘*’ token
     DFMAnythingDirIterator(ComDeepinAnythingInterface *u,
                           ~                          ^~
                                                      )
controllers/filecontroller.cpp:281:5: error: ‘ComDeepinAnythingInterface’ does not name a type
     ComDeepinAnythingInterface *interface;
     ^~~~~~~~~~~~~~~~~~~~~~~~~~
controllers/filecontroller.cpp: In member function ‘virtual bool DFMAnythingDirIterator::hasNext() const’:
controllers/filecontroller.cpp:234:30: error: ‘interface’ was not declared in this scope
             searchDirList << interface->hasLFTSubdirectories(dir_path);
                              ^~~~~~~~~
controllers/filecontroller.cpp:234:30: note: suggested alternative: ‘GFileIface’
             searchDirList << interface->hasLFTSubdirectories(dir_path);
                              ^~~~~~~~~
                              GFileIface
controllers/filecontroller.cpp:244:33: error: ‘interface’ was not declared in this scope
             const auto result = interface->search(100, 500, searchStartOffset, searchEndOffset, searchDirList.first(), keyword, true);
                                 ^~~~~~~~~
controllers/filecontroller.cpp:244:33: note: suggested alternative: ‘GFileIface’
             const auto result = interface->search(100, 500, searchStartOffset, searchEndOffset, searchDirList.first(), keyword, true);
                                 ^~~~~~~~~
                                 GFileIface
controllers/filecontroller.cpp:246:50: error: expected primary-expression before ‘)’ token
             searchResults = result.argumentAt<0>();
                                                  ^
controllers/filecontroller.cpp:247:54: error: expected primary-expression before ‘)’ token
             searchStartOffset = result.argumentAt<1>();
                                                      ^
controllers/filecontroller.cpp:248:52: error: expected primary-expression before ‘)’ token
             searchEndOffset = result.argumentAt<2>();
                                                    ^
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=gnu++11 -pthread -pthread -Wall -W -D_REENTRANT -fPIC -DPLUGINDIR=\"/build/deepin-file-manager/src/dde-file-manager-4.7.8/common/..//plugins:/usr/lib/dde-file-manager/plugins\" -DTOOLDIR=\"/build/deepin-file-manager/src/dde-file-manager-4.7.8/common/..//tools:/usr/lib/dde-file-manager/tools\" -DQMAKE_TARGET=\"dde-file-manager\" -DQMAKE_VERSION=\"1.8.2\" -DQMAKE_ORGANIZATION_NAME=\"deepin\" -DQT_MESSAGELOGCONTEXT -DDISABLE_QUICK_SEARCH -DDISABLE_TAG_SUPPORT -DAPPSHAREDIR=\"/usr/share/dde-file-manager\" -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_CONCURRENT_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_SQL_LIB -DQT_CORE_LIB -I. -I/build/deepin-file-manager/src/dde-file-manager-4.7.8 -I../utils -Iinterfaces -Iinterfaces/plugins -I../dde-file-manager-plugins/plugininterfaces -I../chinese2pinyin -Iio -Iinterfaces/vfs -isystem /usr/include/qt/QGSettings -isystem /usr/include/libsecret-1 -isystem /usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/uuid -isystem /usr/include/gio-unix-2.0 -isystem /usr/include/poppler/cpp -isystem /usr/include/poppler -isystem /usr/include/libdtk-2.0.10/DWidget -isystem /usr/include/libdtk-2.0.10/DCore -isystem /usr/include/udisks2-qt5 -isystem /usr/include/qt -isystem /usr/include/qt/QtSvg -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtX11Extras -isystem /usr/include/qt/QtMultimedia -isystem /usr/include/qt/QtGui/5.12.2 -isystem /usr/include/qt/QtGui/5.12.2/QtGui -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtDBus -isystem /usr/include/qt/QtConcurrent -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtXml -isystem /usr/include/KF5/KCodecs -isystem /usr/include/qt/QtCore/5.12.2 -isystem /usr/include/qt/QtCore/5.12.2/QtCore -isystem /usr/include/qt/QtSql -isystem /usr/include/qt/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/qt/mkspecs/linux-g++ -o fileutils.o shutil/fileutils.cpp
make[1]: *** [Makefile:4007: filecontroller.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/build/deepin-file-manager/src/dde-file-manager-4.7.8/dde-file-manager-lib'
make: *** [Makefile:104: sub-dde-file-manager-lib-make_first] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by oberon-manjaro** [comment]
Full build log is [here](https://pastebin.com/sqcrJM15)

**Comment by BLumia** [comment]
> Full build log is [here](https://pastebin.com/sqcrJM15)

Should be fixed in https://github.com/linuxdeepin/dde-file-manager/commit/1358fa39a3331d1cd4bc7f9879f63133623b21a5 .

Still, it's not recommended to disable deepin-anything support from dde-file-manager.

**Comment by oberon-manjaro** [comment]
Thanks a lot for your cooperation! I will add a package **deepin-file-manager-legacy** to the Manjaro repos for users who prefer it this way. We will continue to offer the original upstream version.

**Comment by felixonmars** [comment]
@BLumia fedora also had deepin-anything disabled from beginning.
