### ISSUE TITLE
depends udisks2-qt5 for deepin-file-manager not present on Archlinux

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/developer-center#1027]
I have been trying to compile **deepin-file-manager** on Manjaro and ran into this error message
```
Project ERROR: udisks2-qt5 development package not found
```
Now this package does not exist on Archlinux, so I am wondering how @felixonmars has been able to build this package for Arch... ? :wink: 
Thank you for your advice.

**Comment by felixonmars** [comment]
Because I added that package to Arch before compiling... Not sure why you didn't see it?

https://www.archlinux.org/packages/community/x86_64/udisks2-qt5/

**Comment by oberon-manjaro** [comment]
I'm sorry @felixonmars ! I didn't sync my mirror and like that **pacman** couldn't see the new package, yet :wink:
