### ISSUE TITLE
按 deepin-version 显示 DDE 版本

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#1028]
现在发行版版本和 DDE 版本均显示为了发行版的版本。
@zccrs 
![2019-03-27-230306-f0fd2d](https://user-images.githubusercontent.com/1006477/55087149-94292200-50e4-11e9-9ef6-59408e47e5f7.png)

**Comment by antechdesigns** [comment]
@felixonmars 

its been like that for a while. It used to show the version you we're using e.g 15.8 DDE

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
