### ISSUE TITLE
warning sign in the dock since update

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/developer-center#1029]
I just installed all the latest packages from upstream Archlinux on Manjaro and suddenly have this 'warning' icon in the dock. I have no idea what it is. It has no text on mouseover and cannot be clicked ... ?

![Screenshot_2019-03-27_18-50-27](https://user-images.githubusercontent.com/11800714/55103863-3cc58a80-50c1-11e9-91d6-5b6f1ffd0575.png)

**Comment by keybreak** [comment]
Weird, i don't have it on VM with up to date Arch Deepin...

It happens to you on Manjaro only with Fashion panel mode or when switching to Efficient mode it's gone?

**Comment by felixonmars** [comment]
This is weird. Did you try a reboot after upgrading?

**Comment by oberon-manjaro** [comment]
@felixonmars , I see this on a new ISO, built with latest packages on first boot, but only in the live environment. It is gone when I install the system in vbox.
My guess is it has something to do with auto-mounted partitions maybe?

**Comment by felixonmars** [comment]
If it first appears with new packages, would it be possible that some components are missing?

I moved some of the dependencies of deepin-file-manager to optdepends.

**Comment by oberon-manjaro** [comment]
unmounting the vbox hd doesn't make the icon disappear btw.

**Comment by oberon-manjaro** [comment]
installing all the optdepends didn't change it either.

**Comment by oberon-manjaro** [comment]
I have now verified that it also has nothing to do with any mounted partitions, because after removing the vbox hd from the virtualbox and re-booting the ISO, the icon is still there :stuck_out_tongue_winking_eye:

**Comment by listenerri** [comment]
Please run the follow cmd and put the result here:
```
mount | grep overlay
df
lsblk
```

This plugin will only show when the root is mounted on the overlay.

**Comment by BLumia** [comment]
> but only in the live environment.

Is there any way to check if we are in a live environment or not?

The overlay warning plugin is intended to warn user they are in overlay mode (root are mounted on overlay), and currently it only check the `/proc/cmdline` ([contains `boot=live`](https://manpages.debian.org/testing/live-boot-doc/live-boot.7.en.html#Kernel_Parameters)) to know if it's in a live mode (and the warning plugin will not be shown).

**Comment by oberon-manjaro** [comment]
Here you go @listenerri 
```
[manjaro@manjaro-deepin ~]$ mount | grep overlay
overlay_root on /run/miso/overlay_root type tmpfs (rw,relatime,size=7786804k,mode=755)
overlay on / type overlay (rw,relatime,lowerdir=/run/miso/sfs/livefs:/run/miso/sfs/mhwdfs:/run/miso/sfs/desktopfs:/run/miso/sfs/rootfs,upperdir=/run/miso/overlay_root/upper,workdir=/run/miso/overlay_root/work,index=off)
[manjaro@manjaro-deepin ~]$ df
Filesystem      Size  Used Avail Use% Mounted on
dev             5.0G     0  5.0G   0% /dev
run             5.0G   92M  4.9G   2% /run
/dev/sr0        1.6G  1.6G     0 100% /run/miso/bootmnt
cowspace        256M     0  256M   0% /run/miso/cowspace
overlay_root    7.5G   69M  7.4G   1% /run/miso/overlay_root
/dev/loop0       74M   74M     0 100% /run/miso/sfs/livefs
/dev/loop1      276M  276M     0 100% /run/miso/sfs/mhwdfs
/dev/loop2      698M  698M     0 100% /run/miso/sfs/desktopfs
/dev/loop3      477M  477M     0 100% /run/miso/sfs/rootfs
overlay         7.5G   69M  7.4G   1% /
tmpfs           5.0G   53M  4.9G   2% /dev/shm
tmpfs           5.0G     0  5.0G   0% /sys/fs/cgroup
tmpfs           5.0G   57M  4.9G   2% /tmp
tmpfs           5.0G  1.7M  5.0G   1% /etc/pacman.d/gnupg
tmpfs          1014M   28K 1014M   1% /run/user/1000
/dev/sr1         82M   82M     0 100% /run/media/manjaro/VBox_GAs_6.0.4
[manjaro@manjaro-deepin ~]$ lsblk
NAME  MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0   7:0    0  73.4M  1 loop /run/miso/sfs/livefs
loop1   7:1    0 275.2M  1 loop /run/miso/sfs/mhwdfs
loop2   7:2    0 697.3M  1 loop /run/miso/sfs/desktopfs
loop3   7:3    0 476.9M  1 loop /run/miso/sfs/rootfs
sr0    11:0    1   1.6G  0 rom  /run/miso/bootmnt
sr1    11:1    1    82M  0 rom  /run/media/manjaro/VBox_GAs_6.0.4
```

**Comment by antechdesigns** [comment]
I just built a new archdeepin ISO when it boots up into the live user I get the warning sign, however after install it has gone ;)

I still have the ISO if you would like anymore info, let me know ;)

**Comment by antechdesigns** [comment]
So this is a feature now??

**Comment by felixonmars** [comment]
I never saw that on my machine. @justforlxz any idea?

**Comment by antechdesigns** [comment]
@felixonmars 
It happens on a live environment, everything is fine after install ;)

New ISO built today and is still there:
![DeepinScreenshot_dde-desktop_20190430111929](https://user-images.githubusercontent.com/29888048/56956265-8e878780-6b3b-11e9-8f99-205344b8fd24.png)

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/developer-center/issues/1029#issuecomment-477490970

**Comment by oberon-manjaro** [comment]
@BLumia sorry for not responding to that quesion. On Manjaro we check for the existence of `/run/miso` to verify that we are currently in a live session. Not sure if there is a better and more general way ...

**Comment by BLumia** [comment]
Thanks for the info and you can simply remove the overlay warning plugin (it's just a single `.so` file as a dde-dock plugin) in live environment. 

FYI the reason of this overlay warning plugin is, the graphics card driver manager will try to install the driver in overlay environment and check if it failed (so we can stop install graphics driver with specific issues). But in some uncovered case we found sometimes the overlay mode cannot be disabled by the graphics card manager app, thus any data will get lost if user are under a overlay root but doesn't know about it, then the overlay warning plugin will warning user and help user disable overlay mode.

As I said before ( https://github.com/linuxdeepin/developer-center/issues/1029#issuecomment-477490970 ), we check if user are under a live system (which the overlay is intended) by checking the kernel argument (by reading `/proc/cmdline`) since all debian based distro will works with this check. Adding a `/run/miso` check is also okay but I think maybe just remove the `.so` file will be a better approach if you just would like to make this warning disappear in live environment :)

btw, there may have new gsettings value which also can be used to hide dde-dock plugins after the v20 release. I'm not very sure about it since I'm not working on dde-dock now.

Feel free to let us know if you have any other questions :)

**Comment by oberon-manjaro** [comment]
Thank you! Removing **/urs/lib/dde-dock/plugins/liboverlay-warning.so** in the live environment certainly disappears the icon :wink:

**Comment by BLumia** [comment]
Glad to know that, feel free to let us know if you need further help ;)
