### ISSUE TITLE
Update nemo in repository

### ISSUE THREAD

**Issue by bigbruno** [linuxdeepin/developer-center#103]
In Debian nemo file manager is 3.0, but in deepin is 2.8, lot improvements in nemo file manager implemented in 3.0, please update in repository.

**Comment by fasheng** [comment]
As I know, we took a snapshot for upstream debian sid repo in May 16, I the testing work finished we will merge it to deepin repo. And then nemo 3.0 will be there, please have a wait~

**Comment by bigbruno** [comment]
Is there a place where users can track how the distribution is going to work then merge or to volunteer to test the packages?

**Comment by fasheng** [comment]
I asked our system maintainer just now, there is a public repo review site now, but need deepin id to login, and the review site always used internal so looks there is no english translation now...
https://rr.deepin.io/
https://account.deepin.org/register?lang=en

**Comment by manateelazycat** [comment]
We will release deepin file manager in next month to be better than other file manager, include nemo.
