### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【DDE】【UI】控制中心deepin ID中插图拉伸严重的问题

### ISSUE THREAD

**Issue by Dora1387** [linuxdeepin/developer-center#10308]
### SUMMARY | 问题概要

deepin ID控制中心首页未登录的插图变形的问题

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240802/
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1810:/dde/testing/ ./
```

### STEPS TO REPRODUCE | 复现步骤

打开控制中心进入到deepin ID模块；未登录ID；将窗口竖向拉伸

### OBSERVED RESULT | 观察到的结果

首页插图非正常扩展，上下被严重拉伸
![截图_选择区域_20240809170744](https://github.com/user-attachments/assets/7b85c5cd-d847-4067-816d-b54d1bde218a)

### EXPECTED RESULT | 期望的结果

与1070实现效果一致，无论怎么拉伸插图不会变形，会根据内容区大小展示更多的插图内容
![截图_dde-control-center_20240809173832](https://github.com/user-attachments/assets/04fbb129-6efc-4197-9358-302238bf945c)

### ADDITIONAL INFORMATION | 额外补充

@babyfengfjx 大佬帮忙看看~

**Comment by babyfengfjx** [comment]
@yixinshark  这个看是否好处理，优先安排一下。

**Comment by xuqi27837288** [comment]
【验证环境】：v23 RC2镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240812
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.9.6-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
