### ISSUE TITLE
newly created user, password not accepted

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/developer-center#1030]
## Describe the bug
The correct password of a newly created user is not accepted for login

## To Reproduce
1. create new user in control-center
2. log out
3. select the new user for login
4. the input field already has a note 'wrong password' before I even try to enter one
5. all attempts to enter the correct password are denied
### Distro & Version
Manjarolinux, dde 15.9.2

### Related package version
dde-session-ui 4.9.0

**Comment by keybreak** [comment]
Confirmed on Arch Deepin.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
