### ISSUE TITLE
deepin-app-store 8.0.7.0004 集成申请

### ISSUE THREAD

**Issue by xionglinlin** [linuxdeepin/developer-center#10301]
### package information | 软件包信息

包名 |  版本 
------ | --------
deepin-app-store | 8.0.7.0004

### Package repository address | 软件包仓库地址

```
deb  [trusted=yes]  https://aptly.uniontech.com/pkg/nonfree-beige-v2/release-candidate/56S-5Yy654mIVjIz5bqU55So5ZWG5bqXMjAyNC43Ljjmj5DmtYsyMDI0LTA3LTA4IDExOjIzOjA0/ unstable non-free
```

### changelog | 更新信息

fix: 部分网络环境下搜索应用后查看应用信息提示检查网络连接

### test suggestion | 测试建议

测试步骤参考社区反馈的问题：https://bbs.deepin.org/post/276231

### Sphere of influence | 影响范围

请求创建应用界面

**Comment by babyfengfjx** [comment]
@baicailio  请开展集成验证，优先处理。

**Comment by baicailio** [comment]
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240809/deepin-23-beige-release-amd64-20240809-202810.iso 
仓库：deb  [trusted=yes]  https://aptly.uniontech.com/pkg/nonfree-beige-v2/release-candidate/56S-5Yy654mIVjIz5bqU55So5ZWG5bqXMjAyNC43Ljjmj5DmtYsyMDI0LTA3LTA4IDExOjIzOjA0/ unstable non-free
应用商店搜索软件正常，未提示网络连接
应用商店下载，安装，更新软件正常
