### ISSUE TITLE
org.deepin.browser 集成

### ISSUE THREAD

**Issue by dengbo11** [linuxdeepin/developer-center#10311]
### package information | 软件包信息

org.deepin.browser | 6.5.5.2

### Package repository address | 软件包仓库地址

name: old url: http://repo-dev.cicd.getdeepin.org/

### changelog | 更新信息

1. 修改玲珑仓库，ll-cli repo modify http://repo-dev.cicd.getdeepin.org --name old
2. 安装最新org.deepin.browser(ll-cli install org.deepin.browser/6.5.5.2)
3. 验证bug是否解决

### Sphere of influence | 影响范围

https://pms.uniontech.com/bug-view-267635.html
https://pms.uniontech.com/bug-view-265043.html
关联的github issues 也请更新状态

**Comment by xuqi27837288** [comment]
【验证环境】：v23 RC2镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240809
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.9.6-amd64-desktop-hwe
【验证步骤】:问题单中描述的步骤
【验证结果】:集成测试通过

**Comment by dengbo11** [comment]
已推送外网
