### ISSUE TITLE
switching window effects on/off in vbox not working

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/developer-center#1031]
When I first launch deepin in virtualbox, wmchooser offers to choose between 'Effect mode' and 'Normal mode'. 
When I select 'Effect mode' here and then use the switch in control-center later, effects are actually turned off, but the slider in the control-center, after moving for a moment, immediately jumps back to the 'on' position.
When I now try to switch window effects back on, the slider again doesn't really move and window effects are actually NOT turned back on.
At the same time this broken message with cut off text is being displayed:
![effect_error_window](https://user-images.githubusercontent.com/11800714/55110534-82418200-50d8-11e9-8f6b-5848b93ba26d.png)

When I select 'Normal mode' from the beginning, I am never able to turn on window effects because I run in the situation described above immediately, where window effects cannot be changed with the slider in the control-center.

**Comment by felixonmars** [comment]
I'm not sure if current deepin-wm supports virtualbox correctly. The cut-off text should be fixed though.

**Comment by keybreak** [comment]
Which graphic controller do you use in machine settings?
For Manjaro Deepin it should work correctly only with VBoxVGA, even before you install guest-additions.

I have seen behaviour like this after switching graphic controller, for something else on VM with installed Arch Deepin, it showed this box and i couldn't get it back whatever i done, only reinstall helped.

Aaaand yes, cut-off text should be fixed :smiley:

**Comment by oberon-manjaro** [comment]
In any case wmchooser doesn't work at all. I just started over again and when I select 'Normal mode' from the start, the session is still launched with window effects enabled.
Isn't the wmchooser specifically designed to work in virtualbox?

**Comment by oberon-manjaro** [comment]
> Which graphic controller do you use

yes, vboxVGA with 3D acceleration enabled.

**Comment by antechdesigns** [comment]
@oberon-manjaro 

you are right, its been like that for a while, it does work, if you do a
 `deepin-wm --replace` it works 

at first I thought it was a VBox problem but it is defo a deepin problem

**Comment by keybreak** [comment]
@antechdesigns 
In my case above when i tested it haven't worked though, still had to reinstall)

Wonder if it will work for @oberon-manjaro

**Comment by antechdesigns** [comment]
@keybreak 
Really? Even though it worked initially e.g selecting Effect Mode after install ?

Either way, its still a bug :(

**Comment by oberon-manjaro** [comment]
@antechdesigns , switching between deepin-wm and deepin-metacity via `--replace` commands works perfectly fine. So it seems it's just the switcher which is broken ...
btw:
```
![Screenshot from 2019-03-27 22-14-43](https://user-images.githubusercontent.com/11800714/55112836-c97e4180-50dd-11e9-8766-09f56ebf3fa0.png)
```

**Comment by oberon-manjaro** [comment]
I'll open another issue for the deepin-metacity error, I guess ... :stuck_out_tongue_winking_eye:

**Comment by antechdesigns** [comment]
@keybreak @oberon-manjaro @felixonmars 
Just thinking, is it worth bothering with all these DDE bugs, since deepin are moving to kwin?
I doubt they will spend time on fixing them if kwin is going to be released (April) I believe ??

**Comment by keybreak** [comment]
Depends on how well **deepin-kwin** will go, i think :smile_cat:

**Comment by oberon-manjaro** [comment]
Does switching wms from control-center work for you guys at all on hardware?
@keybreak @antechdesigns

**Comment by keybreak** [comment]
@oberon-manjaro 
On Manjaro Stable - yes. Arch Deepin i can't test on hardware, @antechdesigns should know better :)

**Comment by antechdesigns** [comment]
@oberon-manjaro 
Works fine on my archdeepin on (hardware, nvidia, kernel 5.0.4)

**Comment by antechdesigns** [comment]
@felixonmars  @oberon-manjaro  @keybreak 

this seems to be fixed for me ;)

**Comment by hualet** [comment]
@oberon-manjaro can you test this with the latest packages?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
