### ISSUE TITLE
deepin-metacity error message

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/developer-center#1032]
![Screenshot from 2019-03-27 22-14-43](https://user-images.githubusercontent.com/11800714/55112968-1e21bc80-50de-11e9-8790-603b368502f0.png)

**Comment by hualet** [comment]
@sonald

**Comment by sonald** [comment]
@oberon-manjaro Will you please provide a backtrace of this situation and describe some background information.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
