### ISSUE TITLE
【deepin_V23_Release】【一般】【有空】【集成测试】【DDE】【任务栏】控制中心没有飞行模式，建议任务栏和快捷面板右键菜单中去掉调转控制中心的 飞行模式设置 选项

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#10335]
### SUMMARY | 问题概要

关联集成：https://github.com/linuxdeepin/developer-center/issues/10281

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
dde-shell 0.0.36
```

### STEPS TO REPRODUCE | 复现步骤

1. 将飞行模式 驻留在任务栏 - 右键点击飞行模式图标 - 查看右键菜单选项

### OBSERVED RESULT | 观察到的结果

右键菜单中显示 调转控制中心的 飞行模式设置 选项
快捷面板的要同步去掉
![企业微信截图_17235138437244](https://github.com/user-attachments/assets/f65a64d6-cf56-43fa-888b-94afbfaad112)

![截图_选择区域_20240812204647](https://github.com/user-attachments/assets/015e4259-984b-4346-ae3c-adbacd10f5cb)

### EXPECTED RESULT | 期望的结果

右键菜单中去掉调转控制中心的 飞行模式设置 选项
快捷面板的要同步去掉

**Comment by yixinshark** [comment]
请基于dde-tray-loader 0.0.9版本验证。

**Comment by luodeepin** [comment]
验证通过
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240813/deepin-23-beige-release-amd64-20240813-224846.iso
