### ISSUE TITLE
Media Play/Pause key only pauses, doesn't resume

### ISSUE THREAD

**Issue by kode54** [linuxdeepin/developer-center#1034]
## Describe the bug
When using a keyboard's Media Play/Pause key, it does not trigger the Play action, only the Pause action.

## To Reproduce
1. Start a media player, such as Google Play Music Desktop Player.
2. Start playing a file.
3. Press the Play/Pause button on the keyboard.
4. Press it again.

## Expected behavior
Media should pause on first press, and resume playing on the second.

### Distro & Version
Arch Linux

### Related package version
deepin-wm 1.9.37-1
gpmdp-git 4.6.1.13.gf52b9436-1

### Additional context
I have verified that the media key issue does not occur with any other desktop environment that I have installed on my system.

**Comment by kode54** [comment]
I found a fix already, it was as simple as changing the configure default for the `audio-pause` key from `XF86AudioPause` to `XF86AudioPlayPause`.

```
gsettings set com.deepin.dde.keybinding.mediakey audio-pause '["XF86AudioPlayPause"]'
```

It would still be helpful if this were the default, or if it would be possible to detect if a keyboard model doesn't have an explicit audio-play key.

**Comment by DiNitride** [comment]
I have the same issue, above fix renders play/pause button useless. Running on a Dell XPS 15 9570, running Arch.

**Comment by kode54** [comment]
In which case, I'd recommend finding which media key option applies to your key. The configuration I posted should have worked, as it did for me, since that PlayPause action is the default for a pause key under most other desktop environments.

**Comment by DiNitride** [comment]
Fixed! audio-play for some reason had been modified, and wasn't set to ["XF86AudioPlay"], changing that back to default value gave the button the intended effect.

**Comment by profran** [comment]
Had the same issue on Arch also, based on Dinitride and kod54's posts, these two commands fixed the issue:
`$ gsettings set com.deepin.dde.keybinding.mediakey audio-pause '["XF86AudioPlayPause"]'`
then:
`$ gsettings set com.deepin.dde.keybinding.mediakey audio-play '["XF86AudioPlay"]'`

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
