### ISSUE TITLE
deepin-app-store 8.0.7.0005 集成申请

### ISSUE THREAD

**Issue by fly602** [linuxdeepin/developer-center#10367]
### package information | 软件包信息

deepin-app-store | 8.0.7.0004

### Package repository address | 软件包仓库地址

deb  [trusted=yes] https://aptly.uniontech.com/pkg/nonfree-beige-v2/release-candidate/56S-5Yy654mIVjIz5bqU55So5ZWG5bqXMjAyNC4wOC4xM-aPkOa1izIwMjQtMDgtMTMgMTY6MDg6Mzc/  unstable non-free

### changelog | 更新信息

fix: dbus启动适配am，openBusinessUri的参数utf8转码

### test suggestion | 测试建议

https://github.com/linuxdeepin/developer-center/issues/10334

**Comment by xuqi27837288** [comment]
【验证环境】：v23 RC2镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240812
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.9.6-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：集成测试通过
