### ISSUE TITLE
Lock screen with actions

### ISSUE THREAD

**Issue by rafaeldev** [linuxdeepin/developer-center#1036]
I leave my desk and I return my computer are locked automatically but with start opened. A click on "settings" for test and its open the configure offcanvas menu (see image below)

![image](https://user-images.githubusercontent.com/4596160/54637819-5125d980-4a68-11e9-8001-c658684a296b.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
