### ISSUE TITLE
how to change default file-manager auto-mount behavior

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/developer-center#1037]
On Manjaro install media we usually disable disk auto-mount for the live-environment.
In the past I used to do this via the config file that used to exist in **~/.config/deepin/dee-file-manager/dde-file-manager.conf**
It seems, this config file is no longer in use.
I was also not able to find this setting in **dconf**
Could you please let me know where dde-file-manager stores this config now?
Thank you.

**Comment by BLumia** [comment]
Whoops, the application name changed so maybe that caused your config no longer works, will look into this issue later.

But there is another question, actually the mount plugin will check if it is in the live enviroment in deepin. As I mentioned [here](https://github.com/linuxdeepin/developer-center/issues/1029#issuecomment-477490970), is there any universal way to check if we are in a live environment or not? The `boot=live` kernel parameter only be used in debian based distro.

**Comment by BLumia** [comment]
I've checked the behavior, `~/.config/deepin/dde-file-manager.conf` should works fine.

`~/.config/deepin/dde-file-manager.conf` means this config file is a generic config file which control all file manager components related stuff, for example, `dde-mount-plugin` and `dde-desktop` are also a part of dde-file-manager, so the config related to `dde-mount-plugin` like the auto-mount behavior are inside `~/.config/deepin/dde-file-manager.conf`.

`~/.config/deepin/dee-file-manager/dde-file-manager.conf` is the config file for the file manager application itself, so if there is a file-manager-only config, it should be here.

But anyway, I think the right way to solve this sort of issue is find/make a universal way to check if user is under a live environment or not. The debian way (use the `boot=live` kernel parameter seems very good and it seems will not hurt anything so I'm not sure if we can make it as a sort of "standard".

**Comment by oberon-manjaro** [comment]
Since a year ago I have been using the following config in **~/.config/deepin/dee-file-manager/dde-file-manager.conf** in the live-overlay of the Manjaro ISOs. Like this it will only be applied in the live environment and not in the final install.
But as I said, the config has stopped working and partitions present are now bein auto-mounted, with the result that the installer **calamares** will only offer manual partitioning until you unmount any partitions and re-launch the installer.
When I change auto-mount setting in the file-manager, the config file does not change, which for me is more confirmation that this file is not being used be the application.
I will check not if the path you mention (~/.config/deepin/dde-file-manager.conf) has any effect.

**Comment by BLumia** [comment]
dde-file-manager already refactored the configure related codebase for a while (since June 2018), the new json format config file should be used. This is a working config file can be used for test.

``` json
{
    "GenericAttribute": {
        "AutoMount": false,
        "AutoMountAndOpen": false
    }
}
```

Still, could you tell us if there is any generic way to check if user is under a live install environment?

**Comment by oberon-manjaro** [comment]
What is very strange here is, that the file **~/.config/deepin/dde-file-manager/dde-file-manager.json** is created empty and whichever changes I make in the GUI, there is never anything written to the file. It remains empty.
This doesn't really look like a working config file to me and obviously **deepin-file-manager** must write its config elsewhere.

**Comment by oberon-manjaro** [comment]
> could you tell us if there is any generic way to check if user is under a live install environment?

On Manjaro we check for the existence of **/run/miso**

**Comment by oberon-manjaro** [comment]
I have now tried installing a file **~/.config/deepin/dde-file-manager/dde-file-manager.json** of the content
```
{
    "GenericAttribute": {
        "AutoMount": false,
        "AutoMountAndOpen": false
    }
}
```
It has absolutely no effect.
The setting 'Auto mount' in the Filemanager is ticked and, as expected, all drives present are mounted in the live session.
I will now try again installing the **.json** file to ``~/.config/deepin/dde-file-manager.json`` and see if that helps.

**Comment by oberon-manjaro** [comment]
Ok. I can now confirm that the ``.json`` file works when it is placed in ``~/.config/deepin/dde-file-manager.json``
