### ISSUE TITLE
deepin.org 被挂马了? 

### ISSUE THREAD

**Issue by CareF** [linuxdeepin/developer-center#1038]
![image](https://user-images.githubusercontent.com/11715538/55251474-13bf0a00-5227-11e9-820a-c5d24954e2e9.png)

https://transparencyreport.google.com/safe-browsing/search?url=http:%2F%2Fdeepin.org%2F&hl=en-US

**Comment by felixonmars** [comment]
百度的JQuery公共库也被Chrome/火狐/Safari报毒了：
https://www.ithome.com/0/416/916.htm

我在 Google 后台没看到 deepin.org 域名有问题，尚不清楚是什么原因。

**Comment by hualet** [comment]
应该已经恢复正常了
