### ISSUE TITLE
[MS AD] [Fedora]External user not showing on DDE

### ISSUE THREAD

**Issue by Dragnell87** [linuxdeepin/developer-center#1039]
## Describe the bug

User with external authentication are no recognized by the system, there are not show in the control center or lightdm( not really a problem as long as the user can type the username)
## To Reproduce

Join the system to a Microsoft Windows AD or FreeIPA server
Enter to the system with a user from AD or FreeIPA

-->

## Screenshots

![photo_2019-03-29_18-52-10](https://user-images.githubusercontent.com/8634449/55266546-f05e8400-5253-11e9-9c31-d80cf183ba07.jpg)
![photo_2019-03-29_18-52-19](https://user-images.githubusercontent.com/8634449/55266548-f05e8400-5253-11e9-9047-8def0015e5cd.jpg)

## Enviroments:
DDE
### Distro & Version
Fedora 30

**Comment by tsic404** [comment]
deepin 15 no maintain anymore. this still happen on v20?

**Comment by tsic404** [comment]
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue
