### ISSUE TITLE
Deepin V23 upgrade wants to remove dde-dock

### ISSUE THREAD

**Issue by Vistaus** [linuxdeepin/developer-center#10395]
### SUMMARY | 问题概要

I'm trying to install the latest upgrade to Deepin V23 (I installed V23 a few months ago) and it now wants to remove dde-dock.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
Distribution: Deepin V23
```

### STEPS TO REPRODUCE | 复现步骤

* Run sudo apt update
* Run sudo apt dist-upgrade

Or run the upgrade through system settings (same result).

### OBSERVED RESULT | 观察到的结果

_The following packages are about to be REMOVED:

dde-dock dock-network-plugin_

### EXPECTED RESULT | 期望的结果

I don't want to lose the dock. No dock = no usable desktop.

**Comment by BLumia** [comment]
Yeah, dde-dock is replaced by dde-shell. It's intended.

**Comment by Vistaus** [comment]
Ah, I didn't know that, thanks. 🙂 Could such things be made a little clearer next time? Because it did gave me a scare.

**Comment by BLumia** [comment]
> Could such things be made a little clearer next time?

We actually mentioned it in our RC release but not in today's stable release. We'll check if we can provide a clearer message for people who prefer use `apt` to upgrade the system instead of using the Control Center app. Thanks for the feedback :)

**Comment by Vistaus** [comment]
No problem! And thank you for listening and using my feedback. :)
