### ISSUE TITLE
[archlinux]桌面右键新建文档的问题

### ISSUE THREAD

**Issue by kirigayakazushin** [linuxdeepin/developer-center#104]
读取的都是用户主目录的文件，正常的话应该是读取模板文件夹吧。而且在一个全新的arch系统直接安装dde，用户目录并没有直接生成图片、下载等目录。

**Comment by fasheng** [comment]
应该是Arch上没有移植deepin-default-settings这个包导致的，可以用户手动设置 `~/.config/user-dirs.dirs`，然后 `xdg-user-dirs-update`。

**Comment by kirigayakazushin** [comment]
明白了。

**Comment by manateelazycat** [comment]
深度文件管理器马上就要发布了， 一旦深度文件管理器发布以后， 新建文件就会走 mime type 和 app store 的数据， 不再会用模板文件的模板这种坑爹的设计来做新建文件了。
