### ISSUE TITLE
Widgets are are too big in deepin gtk theme

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#1040]
Here are  some photos,
![DeepinScreenshot_google-chrome_20190330081524](https://user-images.githubusercontent.com/33563064/55270025-5256d200-52c4-11e9-82ab-00f8267eca7e.png)
![DeepinScreenshot_google-chrome_20190330081612](https://user-images.githubusercontent.com/33563064/55270026-5256d200-52c4-11e9-9217-a9fbb67f1fb9.png)
![DeepinScreenshot_20190330081746](https://user-images.githubusercontent.com/33563064/55270027-52ef6880-52c4-11e9-9d6b-b6db18c258dd.png)

**Comment by keybreak** [comment]
As far as i know it's more of a program's data organization & implementation problem, than Deepin design. Spacing is nice :smiley_cat:

**Comment by hualet** [comment]
That has nothing to do with deepin-gtk-theme I think, it's just the App choose to put so many things into one single menu.

**Comment by SiamSami** [comment]
@hualet I'm not talking about that. I am talking about the spacing. If I change the theme into something different, then I don't have any issue.
Let me make it simple for you, I am only talking the spacing. I think that widgets have too many spaces.

**Comment by hualet** [comment]
@shule1987 what do you think?

**Comment by shule1987** [comment]
> @shule1987 what do you think?

I don't think this would be good, it's ok to reduce the spacing, but, it's not comfortable if the spacing become crowd while other spacings in deepin interface are very loose.

**Comment by SiamSami** [comment]
Note that the only reason I opened this issue is that so much space makes it harder to use some programs which have too many options. It becomes hard to switch to the next option. For example, you can try and use LibreOffice. You notice that due to the spacing, it's hard to switch between the options.
![deepin-screen-recorder__20190403211708](https://user-images.githubusercontent.com/33563064/55490829-3ea9c380-5656-11e9-878a-ceb097cdec09.gif)

It should also be noted that I do not get that problem when I use some other GTK themes.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
