### ISSUE TITLE
[Arch Linux] Date format in dde-lock is wrong

### ISSUE THREAD

**Issue by bloomvdomino** [linuxdeepin/developer-center#1041]
## Describe the bug
On the deepin lockscreen in Arch, the date format "yyyy-MM-dd dddd" aren't changeable, even if you recompile the binaries with an changed format string in the translation file.
For example in German, the right format would be "dddd, dd.MM.yyyy" or something very similiar.

## Expected behavior
The date string on lockscreen should be the same as on the workspace and the same as the correctly defined string in the translation file.

### Distro & Version
Arch Linux & arch-rolling

### Related package version
deepin-session-ui 4.9.0 (dde-session-ui 4.9.0)

**Comment by hualet** [comment]
@zhuxiujuancindy

**Comment by zhuxiujuancindy** [comment]
yyyy-MM-dd dddd was translated to dddd, dd.MM.yyyy (changed the translation) in German.
