### ISSUE TITLE
【deepin_V23_Release】【一般】【正常】【内测反馈】【玲珑】ll-builder在构建后替换desktop中的exec指令为ll-cli run APPID 替换出错

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#10419]
### SUMMARY | 问题概要

ll-builder在构建后替换desktop中的exec指令为ll-cli run APPID 替换出错

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240814/deepin-23-beige-release-amd64-20240814-174055.iso 
linglong-bin:1.6.0.-1
```

### PRE-REQUIREMENT | 预置条件

sudo apt install linglong-builder

### STEPS TO REPRODUCE | 复现步骤

1.ll-builder create org.dde.demo
2.cd org.dde.demo
3.ll-builder build
4.查看exec指令

### OBSERVED RESULT | 观察到的结果

1.ll-builder在构建后替换desktop中的exec指令为ll-cli run APPID 替换出错
![image](https://github.com/user-attachments/assets/002bfd0d-2802-4e86-88ca-a0b24663be62)

### EXPECTED RESULT | 期望的结果

1.ll-builder在构建后替换desktop中的exec指令为ll-cli run APPID 替换不会出错

**Comment by kamiyadm** [comment]
这看上去并不像一个bug，desktop Exec指令解析是dde-application-manager做的解析，且修改上去的指令看上去也没法工作

**Comment by vivianxf** [comment]
https://pms.uniontech.com/bug-view-271473.html
