### ISSUE TITLE
【deepin_V23_Release】【一般】【正常】【内测反馈】【玲珑】应用异常退出时，提示couldn't open "/proc/8511/task/8511/children" ll-box: unknown command /opt/apps/org.arctime.arctime.linyaps/files/bin/start.sh 

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#10410]
### SUMMARY | 问题概要

应用异常退出时，提示couldn't open "/proc/8511/task/8511/children" ll-box: unknown command /opt/apps/org.arctime.arctime.linyaps/files/bin/start.sh

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240814/deepin-23-beige-release-amd64-20240814-174055.iso 
linglong-bin：1.6.0-1
```

### STEPS TO REPRODUCE | 复现步骤

1.终端安装一个玲珑应用：ll-cli install  org.arctime.arctime.linyaps 
2.终端安装一个玲珑应用：ll-cli run org.arctime.arctime.linyaps 
3.应用正常使用中异常退出
4.观察报错信息

### OBSERVED RESULT | 观察到的结果

1.应用异常退出时，提示couldn't open "/proc/8511/task/8511/children" ll-box: unknown command /opt/apps/org.arctime.arctime.linyaps/files/bin/start.sh
ll-cli run org.arctime.arctime.linyaps 
[ERR | 4026531836:8595 | operator():115 ] couldn't open "/proc/8511/task/8511/children" ll-box: unknown command /opt/apps/org.arctime.arctime.linyaps/files/bin/start.sh
Try `ll-box --help' or `ll-box --usage' for more information.Error: CODE=-1/build/linglong-1.5.0.6/libs/linglong/src/linglong/cli/cli.cpp:252 command run: run command failed: /usr/bin/ll-box exec --user 1000:1000 bWFpbjpvcmcuYXJjdGltZS5hcmN0aW1lLmxpbnlhcHMvMi40LjEuMC94ODZfNjQtezRmZDRmMjVkLWNhZTktNDgyOS04MTdhLTE2ZjBiMzA3ZmMzYn0= /opt/apps/org.arctime.arctime.linyaps/files/bin/start.sh retval=16384

### EXPECTED RESULT | 期望的结果

1.应用不会异常退出

**Comment by ComixHe** [comment]
可能已修复，等待再次复现

**Comment by vivianxf** [comment]
https://pms.uniontech.com/bug-view-271489.html
