### ISSUE TITLE
【deepin_V23_Release】【一般】【正常】【内测反馈】【玲珑】 ll-builder 重复export，输出的layer安装包大小会无限叠加

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#10418]
### SUMMARY | 问题概要

 ll-builder 重复export，输出的layer安装包大小会无限叠加

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240814/deepin-23-beige-release-amd64-20240814-174055.iso 
linglong-bin:1.6.0.-1
```

### PRE-REQUIREMENT | 预置条件

sudo apt install linglong-builder

### STEPS TO REPRODUCE | 复现步骤

1.ll-builder create org.dde.demo
2.cd org.dde.demo
3.ll-builder build
4.多次执行ll-builder export
5.观察导出的文件大小

### OBSERVED RESULT | 观察到的结果

1. ll-builder 重复export，输出的layer安装包大小会无限叠加
![image](https://github.com/user-attachments/assets/dbbd471a-50fd-41e2-abf0-52aacbe60f20)
![image](https://github.com/user-attachments/assets/c3cb60d6-03ca-4f5e-a119-db06f5214570)

### EXPECTED RESULT | 期望的结果

1. ll-builder 重复export，添加提示文件已存在

**Comment by dengbo11** [comment]
此问题已修复

**Comment by vivianxf** [comment]
验证镜像：https://cdimage.uniontech.com/community/releases/23/amd64/deepin-desktop-community-23-amd64.iso
linglong-bin:1.6.0-1
验证步骤：提单的步骤
验证现象：多次重复导出，文件大小没有叠加
验证结果：通过
![截图_deepin-terminal_20240829173115](https://github.com/user-attachments/assets/08e904d0-7c59-43da-a41a-b8f1a491ac48)
