### ISSUE TITLE
Terminal deepin theme

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#1042]
Please, bring back beautiful full green on black deepin theme.
It's new look with faded yellow is awful! :crying_cat_face: 

Killed whole The Matrix aesthetics

**Comment by lolimay** [comment]
Haha...

**Comment by BLumia** [comment]
The default one is green on black theme, maybe the package maintainer changed the default theme?

**Comment by keybreak** [comment]
@BLumia 
Yep, it seems changed)
Now it's with ugly faded yellow 2nd level color:

![test](https://user-images.githubusercontent.com/47599989/55285854-5fdf8b00-539c-11e9-8264-393a3a4abada.png)

____
At first i was also skeptical, but after few days i felt completely in love with default one)
And sure, it's easy to make a custom one....
But such defaults was really good before, i think.

**Comment by BLumia** [comment]
So I think you should find the one who did the packaging job for `deepin-terminal` from Manjaro packaging team?

**Comment by keybreak** [comment]
P.S. It's not Manjaro, it's on Arch too)
So i guess @felixonmars

**Comment by felixonmars** [comment]
I won't change that of course.. My terminal theme is also broken after recent updates. It's still the same theme but shown with broken colors.

**Comment by keybreak** [comment]
@felixonmars 
So it's actually bug of theme colors interpretation?

**Comment by felixonmars** [comment]
Just did a bit investigation. Downgrading vte3 from 0.56.0 -> 0.54.3 fixes the issue.

Might be related to https://gitlab.gnome.org/GNOME/vte/commit/ab5161c7df07e09bc7796812d6fa6fdf79f61830

**Comment by BLumia** [comment]
Thanks for the info, will take a look later :)

**Comment by BLumia** [comment]
Guys please check if https://github.com/linuxdeepin/deepin-terminal/pull/135 can solve this issue :)

The default value is `false` since I think they must have enough reason changing the default value from vte side ([maybe related](https://bugzilla.gnome.org/show_bug.cgi?id=762247#c25)). You can change it to `true` to bring back the old behavior :)

**Comment by keybreak** [comment]
@BLumia 
Have added **bold_is_bright=true** to [advanced] even after reboot still same for me :smirk_cat: 
@felixonmars what about you?

**Comment by BLumia** [comment]
> Have added **bold_is_bright=true** to [advanced] even after reboot still same for me...
> Tried **false**, just in case - still same 😼
> 
> To test it no updates required, expected to work as is now, right?

Nope, you need fetch the source code (with that Pull Request) and build it by yourself. 😹

**Comment by keybreak** [comment]
@BLumia 
Oh ok, sorry)
Can't do this at the moment, @felixonmars should be faster to test :smile_cat:

**Comment by keybreak** [comment]
Why it's still an issue?

By default it shouldn't alter themes and should be full green.

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/developer-center/issues/1042#issuecomment-478560152

We think VTE have its reason to change its default value (https://github.com/linuxdeepin/developer-center/issues/1042#issuecomment-478356680) so we decided to keep the same behavior as VTE did. So if you like you can change the config to `bold_is_bright=true` to keep the old behavior or it will be `false` by default.

**Comment by aiamuzz** [comment]
@BLumia ... is the Deepin Terminal based on the Kitty project ?
the comment and discussions lead to that project ...

**Comment by BLumia** [comment]
No, it's based on VTE.

**Comment by keybreak** [comment]
@BLumia 
But this doesn't answer aesthetic question.

It means that either this option, or themes are wrong.
If that's a decision - then redesign themes, so it would match initial design...

Now it looks really bad with this strange yellow, and more than that leads to more bugs:
1. Each time you launch new terminal there's a chance that you'll have different colors (for example headers in inxi sometimes shows as deep blue, sometimes as white).
2. Sometimes when you launch terminal shows bolds, sometimes not.
3. All the above sometimes can be triggered if you just click on same theme in theme switcher.

So no, i'm afraid it's not wise decision at all to keep things as they are it's buggy now, and worst part it's random.

**Comment by BLumia** [comment]
> Now it looks really bad with this strange yellow,

Maybe we can't say it's bad just because it's yellow. (imo the default green theme with `bold_is_bright=true` is extremely bad since it make almost all text color pattle become green which makes there are almost no way to differentiate varieties of process simply by color when watching `htop` result or `ip -c addr` or anything else which may print colorful text). You can treat it as a design change btw.

And I don't know if anyone is willing to contribute a new green-on-black theme and we may be able to merge it :)

**Comment by keybreak** [comment]
@BLumia 
Which means it was designed or redesigned based on bug...
Seems that people who designed Deepin in first place are at the bad place now :laughing: 

Anyway, check this out - i've made better defaults which is in line with Deepin style (unlike now):
```
[theme]
color_1=#073642
color_2=#b9300d
color_3=#00cd00
color_4=#ffc005
color_5=#2aa198
color_6=#d33682
color_7=#198fcc
color_8=#eee8d5
color_9=#427682
color_10=#8b0000
color_11=#7bc91f
color_12=#ffd00a
color_13=#1e90ff
color_14=#6c71c4
color_15=#93a1a1
color_16=#fdf6e3
background=#08080A
foreground=#00cd00
tab=#2CA7F8


```

![image](https://user-images.githubusercontent.com/47599989/62416450-cb37b300-b643-11e9-93c5-7a0d8dca970c.png)

![image](https://user-images.githubusercontent.com/47599989/62416460-f15d5300-b643-11e9-8294-d32bf010634d.png)

![image](https://user-images.githubusercontent.com/47599989/62416458-e5719100-b643-11e9-9182-2363121b246b.png)

Oh, and also coredumps and Deepin errors looks way better with proper red! :rofl:
Maybe they'll get fixed faster then :smile_cat: 

![image](https://user-images.githubusercontent.com/47599989/62416479-4d27dc00-b644-11e9-9521-742b729d455f.png)

Please consider using this theme as default.
________
Also what about this?
You haven't answered, but it started with those updates of **bold_is_bright**, behavior is pretty random.

> Now it looks really bad with this strange yellow, and more than that leads to more bugs:

> Each time you launch new terminal there's a chance that you'll have different colors (for example headers in inxi sometimes shows as deep blue, sometimes as yellow, sometimes as white).
>  Sometimes when you launch terminal shows bolds, sometimes not.
> All the above sometimes can be triggered if you just click on same theme in theme switcher.

________

Also, maybe it's a good idea to have checkbox in terminal settings
[ ] Use bold styles

Notice, i mean bold text, not **bold_is_bright** option...

**Comment by aiamuzz** [comment]
> Anyway, check this out - i've made better defaults which is in line with Deepin style (unlike now):
> 
> ```
> [theme]
> color_1=#073642
> color_2=#b9300d
> color_3=#00cd00
> color_4=#ffc005
> color_5=#2aa198
> color_6=#d33682
> color_7=#198fcc
> color_8=#eee8d5
> color_9=#427682
> color_10=#8b0000
> color_11=#7bc91f
> color_12=#ffd00a
> color_13=#1e90ff
> color_14=#6c71c4
> color_15=#93a1a1
> color_16=#fdf6e3
> background=#08080A
> foreground=#00cd00
> tab=#2CA7F8
> ```

I use the theme Freya ... @keybreak ... have you used the theme Freya and changed the Blue to Green ?

this is the Freya theme ...

![image](https://user-images.githubusercontent.com/3283676/62416590-3b9dfe80-b65b-11e9-8bbd-af99076b8d83.png)


and this is your theme file from above ...

![image](https://user-images.githubusercontent.com/3283676/62416595-4c4e7480-b65b-11e9-8b15-a57a09ca1dce.png)

As Blue is the primary color of the overall Deepin OS and its UI(Deepin File Manager, Deepin Clone, etc ) ... i have found Freya more in line with the UI of Deepin ... :smile:

**Comment by BLumia** [comment]
> Seems that people who designed Deepin in first place are at the bad place now 😆

Actually there will be a huge design change in the next few month, within the redesigned control center, new deepin look-and-feel and other stuff. Since almost all devs are working on that, the current published project will keep it as-is and avoid change to take dev resource (I asked about the deepin movie titlebar height few days ago and they told me to keep it as-is to avoid another new release cycle). ah it's sort of off-topic then.

> Anyway, check this out - i've made better defaults which is in line with Deepin style 

Good, would able to merge it if you would like to send a Pull Request (No promise about if it can become the default one).

> You haven't answered, but it started with those updates of **bold_is_bright**, behavior is pretty random.

The color change is due to the package `vte` deliveried by your distro changed its default setting, actually deepin-terminal doesn't change the setting (as you can see when you open this issue, we don't even release any update, and that's also why I think maybe the package maintainer of your distro changed the default theme).

> > and more than that leads to more bugs:
> 
> > 1. Each time you launch new terminal there's a chance that you'll have different colors (for example headers in inxi sometimes shows as deep blue, sometimes as yellow, sometimes as white).
> > 2. Sometimes when you launch terminal shows bolds, sometimes not.
> > 3. All the above sometimes can be triggered if you just click on same theme in theme switcher.

Maybe you can open another issue? :)

> Also, maybe it's a good idea to have checkbox in terminal settings
> [ ] Use bold styles
> 
> Notice, i mean bold text, not **bold_is_bright** option...

I'll ask our PM and see if that's possible :)

**Comment by aiamuzz** [comment]
> Actually there will be a huge design change in the next few month, within the redesigned control center, new deepin look-and-feel and other stuff.

:eyes: ... :roll_eyes: ... :eyes: 
I am scared to wake up next to a wife different than the one i slept last night ... that too when i have just begun to be used to the last switch(deepin-wm to kwin)

:fearful: ... @BLumia ... :fearful:

**Comment by BLumia** [comment]
> > Actually there will be a huge design change in the next few month, within the redesigned control center, new deepin look-and-feel and other stuff.
> 
>  ...  ... 
> I am scared to wake up next to a wife different than the one i slept last night ... that too when i have just begun to be used to the previously switched wife (deepin-wm to kwin)

I'm surprised you are scared about that since bring back the deepin-wm (similar but not the very same) UI and UX to deepin-kwin is a part of the change :)

No more off-topic now :)

**Comment by aiamuzz** [comment]
> No more off-topic now, and shh, it's a secret now, there are no official statement/news about the next big version update since now :)

you mean brace yourself for the shock !!!
:wink: ... :stuck_out_tongue_winking_eye: ... :wink:
