### ISSUE TITLE
【deepin_V23_Release】【一般】【正常】【内测反馈】【玲珑】ll-builder 构建完成后自动添加的share/systemd/user文件

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#10420]
### SUMMARY | 问题概要

ll-builder 构建完成后自动添加的share/systemd/user文件

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240814/deepin-23-beige-release-amd64-20240814-174055.iso 
linglong-bin:1.6.0.-1
```

### PRE-REQUIREMENT | 预置条件

sudo apt install linglong-builder

### STEPS TO REPRODUCE | 复现步骤

1.ll-builder create org.dde.demo
2.cd org.dde.demo
3.ll-builder build
4.查看share/systemd/user文件

### OBSERVED RESULT | 观察到的结果

1.ll-builder 构建完成后自动添加的share/systemd/user文件

### EXPECTED RESULT | 期望的结果

1.ll-builder 构建完成后不会自动添加的share/systemd/user文件

**Comment by kamiyadm** [comment]
问题已修复，等待下次集成回归

**Comment by kamiyadm** [comment]
https://github.com/OpenAtom-Linyaps/linyaps/commit/263b86b3f7a1589fc928ff15f00e3c4da147f34d

**Comment by vivianxf** [comment]
https://pms.uniontech.com/bug-view-271459.html
