### ISSUE TITLE
【deepin_V23_Release】【一般】【正常】【内测反馈】【玲珑】ll-cli ps 命令输出缺少pid 和path信息

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#10430]
### SUMMARY | 问题概要

ll-cli ps 命令输出缺少pid 和path信息

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240814/deepin-23-beige-release-amd64-20240814-174055.iso 
linglong-bin:1.6.0.-1
```

### STEPS TO REPRODUCE | 复现步骤

1.在终端执行ll-cli ps 命令
2.观察输出结果

### OBSERVED RESULT | 观察到的结果

1.ll-cli ps 命令输出缺少pid 和path信息
![image](https://github.com/user-attachments/assets/1add2da0-a1b9-4029-8b6a-f4368169c044)

### EXPECTED RESULT | 期望的结果

1.ll-cli ps 命令输出包含pid 和path信息

**Comment by babyfengfjx** [comment]
@dengbo11  请安排优化~

**Comment by vivianxf** [comment]
https://pms.uniontech.com/bug-view-271451.html
