### ISSUE TITLE
【deepin_V23_Release】【一般】【正常】【内测反馈】【玲珑】玲珑版本zeal-文档阅读器打开tools报：SSL handshake failed

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#10437]
### SUMMARY | 问题概要

玲珑版本zeal-文档阅读器打开tools报：SSL handshake failed

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240814/deepin-23-beige-release-amd64-20240814-174055.iso 
linglong-bin:1.6.0.-1
```

### STEPS TO REPRODUCE | 复现步骤

1.在应用商店下载玲珑版本zeal-文档阅读器
2.打开应用-点击tools-docsets-available
3.观察提示信息

### OBSERVED RESULT | 观察到的结果

1.玲珑版本zeal-文档阅读器打开tool报：SSL handshake failed
![截图_dde-desktop_20240819162826](https://github.com/user-attachments/assets/e299641d-e801-4c1f-b755-bcf888ee4a92)

### EXPECTED RESULT | 期望的结果

1.玲珑版本zeal-文档阅读器打开tools能正常展示工具，和普通版本保持一致
![截图_zeal_20240819170127](https://github.com/user-attachments/assets/7146bd80-d496-4980-9112-43b77a8c1987)

**Comment by babyfengfjx** [comment]
@dengbo11  可以简单看下是不是应用本身的问题，如果是应用本身的问题，需要晓飞转到运营处理。

**Comment by vivianxf** [comment]
验证镜像：https://cdimage.uniontech.com/community/releases/23/amd64/
仓库：ll-cli repo modify http://repo-dev.cicd.getdeepin.org/ --name old
o.github.marktext： 0.17.4.1
验证步骤：提单的步骤
验证现象：玲珑版本zeal-文档阅读器打开tools能正常展示工具，和普通版本保持一致
![截图_zeal_20240830171703](https://github.com/user-attachments/assets/e61dbbd0-a4b0-446d-9a25-ad43be6c1298)
