### ISSUE TITLE
【deepin_V23_Release】【一般】【正常】【内测反馈】【玲珑】ll-cli run io.github.marktext报错

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#10433]
### SUMMARY | 问题概要

ll-cli run io.github.markttext报错

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240814/deepin-23-beige-release-amd64-20240814-174055.iso 
linglong-bin:1.6.0.-1
```

### STEPS TO REPRODUCE | 复现步骤

1.ll-cli install  io.github.marktext 安装应用
2.ll-cli run io.github.marktext 运行应用
3.观察现象

### OBSERVED RESULT | 观察到的结果

1.ll-cli run io.github.marktext报错
![image](https://github.com/user-attachments/assets/e373e63f-6336-4e51-9b3f-3aa13b67e978)

### EXPECTED RESULT | 期望的结果

1.1.ll-cli run io.github.marktext 可以正常运行应用

**Comment by babyfengfjx** [comment]
@dengbo11  请安排分析~

**Comment by vivianxf** [comment]
验证镜像：https://cdimage.uniontech.com/community/releases/23/amd64/
仓库：ll-cli repo modify http://repo-dev.cicd.getdeepin.org/ --name old
o.github.marktext： 0.17.4.1
验证步骤：提单的步骤
验证现象：l-cli run io.github.marktext 可以正常运行应用
![截图_dde-desktop_20240830171820](https://github.com/user-attachments/assets/ef1e8fb1-ff70-4920-9077-096e687ef649)
