### ISSUE TITLE
org.deepin.browser 集成

### ISSUE THREAD

**Issue by dengbo11** [linuxdeepin/developer-center#10447]
### package information | 软件包信息

org.deepin.browser | 6.5.5.3

### Package repository address | 软件包仓库地址

name: old url: http://repo-dev.cicd.getdeepin.org/

### changelog | 更新信息

1. 修改玲珑仓库，ll-cli repo modify http://repo-dev.cicd.getdeepin.org --name old
2. 安装最新org.deepin.browser(ll-cli install org.deepin.browser/6.5.5.3)
3. 验证bug是否解决

### Sphere of influence | 影响范围

https://pms.uniontech.com/bug-view-237841.html

**Comment by babyfengfjx** [comment]
@vivianxf  请开展回归验证。

**Comment by vivianxf** [comment]
集成验证通过，请及时合入：

1.切换仓库升级浏览器成功
2.https://pms.uniontech.com/bug-view-237841.html 验证通过
3.玲珑基本功能，安装，运行，卸载，查看 正常运行

 综上所述，本次集成通过～
