### ISSUE TITLE
开启自动调节色温后亮度调整失效

### ISSUE THREAD

**Issue by ShuiHuo** [linuxdeepin/developer-center#1044]
## 缺陷描述
开启自动调节色温后，显示器亮度会被覆盖。

## 复现步骤
描述可以重现缺陷（BUG）的操作步骤，以便我们复现缺陷并进行修复
复现步骤为:
1. 打开 '自动调节色温'
2. 点击 '任意显示器亮度条'，此时显示器变暗或变亮
3. 等待几秒钟
4. 缺陷 '亮度没有一直保持' 发生

## 期望行为
开启自动调节色温后，显示器亮度仍然可以调整。

## 截图
![自动调节色温和亮度冲突](https://user-images.githubusercontent.com/7471938/55296599-4d258e80-544e-11e9-9684-3dd859c1ed1c.gif)

### 发行版以及版本
Arch Linux

**Comment by hualet** [comment]
你的显示器应该是没有背光调节，只能调节gamma来模拟，但是色温也是调节gamma值，所以就冲突了。这个有需求记录会在没有背光支持的显示器不启动（显示）色温调节。

**Comment by justforlxz** [comment]
@electricface  后端能知道支持调节背光么

**Comment by electricface** [comment]
可以

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
