### ISSUE TITLE
[Feat. Request] 尝试使用 featurehub 收集收集用户对特性的需求

### ISSUE THREAD

**Issue by lolimay** [linuxdeepin/developer-center#1045]
在浏览 996.ICU 项目时无意看到 996.ICU 使用 [FeatHub](https://feathub.com/) 来进行需求收集，照抄官网的介绍如下:

> Give advice on projects you use.
>
> Find what users expect from your project.

其承诺对开源项目永久免费，deepin 可不可以试用一下呢? 然后看看社区反应如何。

其实用 github issues 也可以用于收集 issues，但是缺少排名功能，但对其他用户来说不直观。但有排名系统就不一样了，如果一个用户提出了一个请求，其它用户也有类似需求，则可以给这个需求 `+1`，deepin 也能通过这个需求排行榜作为参考，了解社区真正的需求是什么。

另请参见: [需求墙 - Dcloud](https://dev.dcloud.net.cn/wish/)，这个公司比较硬核，直接自己实现了一个类似的系统，但是用户只能给每个需求投票，不能在每个需求下发表看法，比较简陋。

**Comment by lolimay** [comment]
突然发现投票功能是与github账号关联的，总不能要求社区中的每个用户注册个github账号。这无疑增加了这个系统的使用门槛。唉...

**Comment by lolimay** [comment]
Seems no response, so close.

**Comment by listenerri** [comment]
![图片](https://user-images.githubusercontent.com/7995379/55525887-72700200-56c5-11e9-8d86-c2793f75fcef.png)

hub 的排序功能也差不多可以满足你说的需求
