### ISSUE TITLE
[Feature Request] Shortcut Suggestion

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#1046]
## Describe the bug
Can not open Control Center through shortcuts.

## Expected behavior
I suggest that the "Super + C" shortcut opens the Control Center.

## Screenshots
![Captura de Tela_selecionar área_20190402143814](https://user-images.githubusercontent.com/45263160/55423779-ffe01480-5554-11e9-9f0a-0dc7f1923447.png)

### Distro & Version
Deepin 15.9.3

**Comment by lolimay** [comment]
+1

**Comment by lolimay** [comment]
It's the design bug.

**Comment by saymoncoppi** [comment]
Great idea! 
I gave a tip these days [#999](https://github.com/linuxdeepin/developer-center/issues/999) about to include shortcuts to hotcorners. seems like they will do!

I guess they will also listen you

Best regards

**Comment by alexwender1** [comment]
Not yet resolved.
