### ISSUE TITLE
Support embedded album art and lyrics

### ISSUE THREAD

**Issue by nihil21** [linuxdeepin/developer-center#1047]
Hi,
I would suggest to support artworks and lyrics embedded in songs tags, since the fetch from online sources very often results in wrong album covers and in wrong lyrics.
Thanks in advance.

**Comment by BLumia** [comment]
目前的代码基础改这个支持做过一次，但是实现不太干净所以没合并。目前没太多时间，鉴于这个需求的优先级不是特别高所以还没时间去搞这个。有意愿和能力的话欢迎直接在 GitHub 上发起 PR 。

We have limited time and resources to working on these issues, since this issue's priority is not very high, we'll work on this issue once we have time. Patches are welcome.

**Comment by meiyixiang** [comment]
11/5000 
This feature is already in the works
