### ISSUE TITLE
[Deepin Integration]~[V23-Beta3]  from nvidia-driver by @Zeno-sole to V23-release

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#10483]
### Package information | 软件包信息

包名 | 版本
--  | --
nvidia-graphics-drivers|  535.183.06-1

### Package repository address | 软件包仓库地址

    deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1910:/commercial/testing/  ./

#### nvidia-graphics-drivers (535.183.06-1) unstable; urgency=medium

  * update version 535.183.06-1

**Comment by Zeno-sole** [comment]
**Integration Test Info**
### Test suggestion | 测试建议
在nvidia设备上更新驱动，查看更新后显示、硬件解码等功能是否正常
安装常用 nvidia-smi nvidia-setting等工具 查看是否正常使用


### Influence | 影响范围
nvidia驱动


### ADDITIONAL INFORMATION | 额外补充

**Comment by babyfengfjx** [comment]
@kobe337  请开展集成验证。

**Comment by kobe337** [comment]
【环境】：
镜像：Deepin OS-23-20240813103808-1_x86_64
内核：Linux deepin-PC 6.6.40-amd64-desktop-hwe #23.01.00.33 SMP PREEMPT_DYNAMIC Thu Jul 25 15:29:39 CST 2024 x86_64 GNU/Linux

【结论】：
测试通过，暂无严重问题及影响, 安装校验，版本核对，播放分辨率8K视频、不同格式mkv/wmv/webm/avi/mp4,视频流h264、vp9、vcl、hevc、vp8,均渲染正常， 验证通过。
