### ISSUE TITLE
LightDM + Deepin session not saving/launching last DE used

### ISSUE THREAD

**Issue by raenk** [linuxdeepin/developer-center#1048]
## Describe the bug

I'm on Arch linux using lightDM + Deepin session (lightdm-deepin-greeter) and since a month or so, I need to manually select the DE because it's not remembering the last one used.
## To Reproduce
1. Boot machine
2. Log in without changing anything else
3. The first DE of the list gets launched.

## Expected behavior

After login, the last used DE should be launched.
## Enviroments:
LightDM + Deepin Session
Deepin Desktop
### Distro & Version

Arch Linux up to date
### Related package version

lightdm?
deepin session?

**Comment by lolimay** [comment]
Do you mean that you need to select display manager whenever you startup?

**Comment by raenk** [comment]
I have these in order:
Budgie desktop
Deepin desktop
Gnome
S3

My everyday use is Deepin and, since a month or so (after an update obviously), i need to manually select it, otherwise Budgie desktop gets launched (first option)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
