### ISSUE TITLE
Keyboard layout reset to US and speed settings changes after USB unplugged

### ISSUE THREAD

**Issue by raenk** [linuxdeepin/developer-center#1049]
## Describe the bug

I used a bluetooth keyboard and, from time to time I need to unplug the USB receptor while the machine is on. After I plugging it back in, the keyboard layout gets changed to US even when the US layout it's not even present in the settings.

Also, the repeat rate/speed pressed key is slower than before.

To fix it I need to add any other layout, switch to it, switch back to my layout of choice and remove the extra layout.
## To Reproduce
1. Use a bluetooth keyboard.
2. Unplug the USB receptor with the machine on.
3. Type anything, anywhere and the keyboard layout has changed to US.
4. Keep any key pressed down and the repeat rate/speed is slower.

## Expected behavior

Keep the set keyboard layout and settings.
## Enviroments:
Deepin Desktop
### Distro & Version

Arch Linux up to date

**Comment by listenerri** [comment]
@electricface 
I confirmed this issue and after reconnect my usb keyboard, the repeat speed i set before is not work too, even throngh the value of repeat speed in control center is still display as before, i have to change this value again to get it works.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
