### ISSUE TITLE
[deepin]dock的应用程序图标显示问题

### ISSUE THREAD

**Issue by kirigayakazushin** [linuxdeepin/developer-center#105]
这次是在deepin下发现的，我安装了Plex media server，然后有运行过一次启动器的plex manager，是通过浏览器打开本地的32400，当我关闭掉页面以后，再启动chrome，图标还是Plex的。
只有把chrome完全关闭，才回复正常。
![20160708160057](https://cloud.githubusercontent.com/assets/12298476/16681144/81f18fa0-4525-11e6-8d3f-99855a440beb.png)
![20160708160126](https://cloud.githubusercontent.com/assets/12298476/16681143/81f1560c-4525-11e6-9fc9-c5a54592424e.png)

**Comment by electricface** [comment]
Plex media server 下载不了，老是失败
