### ISSUE TITLE
[Suggestion] - Deepin System Monitor 

### ISSUE THREAD

**Issue by saymoncoppi** [linuxdeepin/developer-center#1050]
Guys pls someone could gimme a clue about why the default shortcut isnt "**Ctrl Shift Esc**"?

Considering UX maybe the its the best option to users that comes from Windows 10.
![image](https://user-images.githubusercontent.com/22059715/55499045-66c80100-561b-11e9-929b-562f2d6f3ebe.png)

### Deepin System Monitor
![image](https://user-images.githubusercontent.com/22059715/55498777-ceca1780-561a-11e9-9b86-b0cd25a76f18.png)

Best regards!

**Comment by keybreak** [comment]
Don't know how about you, but for me it's physically little easier on hand to press, than Window's Ctrl+Shift+ESC

**Comment by saymoncoppi** [comment]
Someone knows where is the keybind file from Deepin?

**Comment by keybreak** [comment]
Not sure about file, but if you click on buttons in settings you can change keybinding for action

**Comment by hualet** [comment]
> Someone knows where is the keybind file from Deepin?

@electricface

**Comment by saymoncoppi** [comment]
@electricface I'v already found :)
https://github.com/saymoncoppi/deepin-shortcuts... Later I'll share the results

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
