### ISSUE TITLE
玲珑相关应用问题修复集成

### ISSUE THREAD

**Issue by dengbo11** [linuxdeepin/developer-center#10511]
### package information | 软件包信息

org.zealdocs.zeal.linyaps | 1.7.1.0
io.github.YesPlayMusic | 0.4.8.0

### Package repository address | 软件包仓库地址

name: old url: http://repo-dev.cicd.getdeepin.org/

### changelog | 更新信息

1. 修改玲珑仓库，ll-cli repo modify http://repo-dev.cicd.getdeepin.org --name old
2. 安装最新org.zealdocs.zeal.linyaps(ll-cli install org.zealdocs.zeal.linyaps/1.7.1.0)
   安装最新io.github.YesPlayMusic(ll-cli install io.github.YesPlayMusic/0.4.8.0)
   安装最新io.github.marktext(ll-cli install io.github.marktext/0.17.4.1)
4. 验证bug是否解决

### Sphere of influence | 影响范围

- https://github.com/linuxdeepin/developer-center/issues/10437
- https://pms.uniontech.com/bug-view-271281.html
- https://github.com/linuxdeepin/developer-center/issues/10433

**Comment by babyfengfjx** [comment]
@vivianxf  请开展回归验证。

**Comment by dengbo11** [comment]
- https://github.com/linuxdeepin/developer-center/issues/10064

**Comment by vivianxf** [comment]
集成测试通过，请及时合入：

1.切换仓库成功
2.安装测试版本成功，运行正常
3.issues：#10064， #10473 ，#10433 验证通过
4.pms：271281 验证通过
5.玲珑基本功能正常

综上所述，本次集成通过～

**Comment by dengbo11** [comment]
已推送外网
