### ISSUE TITLE
system monitor: RAM memory usage wrong?

### ISSUE THREAD

**Issue by star-buck** [linuxdeepin/developer-center#1051]
memory usage in deepin system monitor is always higher than top or ksysguard:
![Screenshot_20190403_214648](https://user-images.githubusercontent.com/840070/55508678-a3ffb380-565a-11e9-9f94-daab46b30c4e.png)

Maybe its better to use MiB like the other two?

**Comment by antechdesigns** [comment]
is this because one is showing you cached system memory and the other is not ?

**Comment by star-buck** [comment]
You mean the other two are not?

**Comment by antechdesigns** [comment]
> You mean the other two are not?

Yes, its a guess mind, only thing that would make sense. If you do a `free -m` in a terminal it will show you: total  used  free  shared  buff/cache   available etc

**Comment by SiamSami** [comment]
@BLumia @felixonmars @electricface Any idea on this?

**Comment by justforlxz** [comment]
https://github.com/linuxdeepin/deepin-system-monitor/blob/master/src/status_monitor.cpp#L288

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
