### ISSUE TITLE
网站连通性检测仍未修复

### ISSUE THREAD

**Issue by lolimay** [linuxdeepin/developer-center#1055]
## 缺陷描述
Dock栏有线连接图标显示 `Connected but no internet access`。

## 复现步骤
复现步骤为:
1. 开机
2. 等待3~5分钟直到显示有线连接已连接
3. 打开网页浏览器访问百度 -> 打开百度
4. 缺陷 Dock 栏有线连接图标仍显示为 <img  height="26" src="https://user-images.githubusercontent.com/32427260/55673460-f6e79e00-58da-11e9-9b08-e6dd8ec75c1f.png">

## 期望行为

当网络确实连通时，Dock 栏有线连接图标显示正常。
## 截图

![image](https://user-images.githubusercontent.com/32427260/55673500-475efb80-58db-11e9-8381-d4d52c29e5de.png)

### 发行版以及版本
 Linux Deepin 15.9.3

### 相关的软件包版本

dde-dock/panda,now 4.9.2.1-1 amd64 [installed]

**Comment by hualet** [comment]
最近的更新就会修复的。

**Comment by lolimay** [comment]
> 最近的更新就会修复的。

Thx
