### ISSUE TITLE
【deepin 25】【一般】【立即】【集成测试】【treeland】在第一个工作区里打开工作区后，按super ←键切换工作区时，任务栏会晃动

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#10564]
### SUMMARY | 问题概要

关联集成：https://github.com/linuxdeepin/developer-center/issues/10003

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23/amd64/deepin-desktop-community-23-amd64.iso
升级到最新内测环境（0830）
```

### PRE-REQUIREMENT | 预置条件

1. 当前在第一个工作区 

### STEPS TO REPRODUCE | 复现步骤

1. 打开进入工作区 -  按 super ←键切换工作区

### OBSERVED RESULT | 观察到的结果

1. 任务栏会晃动 没有切换到最后一个工作区
![录屏_选择区域_20240905104701](https://github.com/user-attachments/assets/bd341bba-2f6f-4b27-848d-167be5230bc0)

### EXPECTED RESULT | 期望的结果

1. 进入最后一个工作区，切换动画界面没有异常

**Comment by baicailio** [comment]
设计如此，工作区不会循环，非问题
