### ISSUE TITLE
[特性需求]-文件管理器

### ISSUE THREAD

**Issue by yangpanda** [linuxdeepin/developer-center#1056]
## 缺陷描述

当列视图很宽以至于需要横向滚动查看时，按着 shift 键滑动滚轮，页面表现为上下滚动。

## 期望行为

按着 shift 键滑动滚轮，页面横向滚动。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
