### ISSUE TITLE
[bug] - deepin-editor

### ISSUE THREAD

**Issue by yangpanda** [linuxdeepin/developer-center#1057]
## 缺陷描述

将系统语言设置为英文后, 在 deepin-editor 里敲一些中文, 保存之后再打开, 中文乱码.

## 截图

![deepin-screen-recorder_deepin-editor_20190407225031](https://user-images.githubusercontent.com/40874532/55685381-0113a600-5988-11e9-92f3-8b9529d83728.gif)

## 复现环境:

系统及软件均为deepin15.9.3最新版本.

## 日志
[deepin-feedback-all-20190407-224528.tar.gz](https://github.com/linuxdeepin/developer-center/files/3051635/deepin-feedback-all-20190407-224528.tar.gz)

**Comment by BLumia** [comment]
保存后的文件，在文件管理器中使用空格预览，会乱码吗？

**Comment by yangpanda** [comment]
预览也乱

**Comment by alexwender1** [comment]
I use Deepin in Brazilian Portuguese. When saving a text file with a few words with specific language characters (eg accentuation)... When you open the file again, other terms appear in place.

![Captura de Tela_selecionar área_20190408151601](https://user-images.githubusercontent.com/45263160/55747518-d6226400-5a12-11e9-9458-9ad2b115566c.png)

![Captura de Tela_selecionar área_20190408151618](https://user-images.githubusercontent.com/45263160/55747524-d9b5eb00-5a12-11e9-870c-4eec316d1cc6.png)

When saving the file, with a blank line below... Characters change when you open the file again:

![Captura de Tela_selecionar área_20190408151752](https://user-images.githubusercontent.com/45263160/55747534-dcb0db80-5a12-11e9-889a-0cb123e823f3.png)

![Captura de Tela_selecionar área_20190408151805](https://user-images.githubusercontent.com/45263160/55747542-dfabcc00-5a12-11e9-9b01-48c4ff1941ee.png)

**Comment by BLumia** [comment]
> I use Deepin in Brazilian Portuguese. When saving a text file with a few words with specific language characters (eg accentuation)... When you open the file again, other terms appear in place.
> 
> ![Captura de Tela_selecionar área_20190408151601](https://user-images.githubusercontent.com/45263160/55747518-d6226400-5a12-11e9-9458-9ad2b115566c.png)
> 
> ![Captura de Tela_selecionar área_20190408151618](https://user-images.githubusercontent.com/45263160/55747524-d9b5eb00-5a12-11e9-870c-4eec316d1cc6.png)
> 
> When saving the file, with a blank line below... Characters change when you open the file again:
> 
> ![Captura de Tela_selecionar área_20190408151752](https://user-images.githubusercontent.com/45263160/55747534-dcb0db80-5a12-11e9-889a-0cb123e823f3.png)
> 
> ![Captura de Tela_selecionar área_20190408151805](https://user-images.githubusercontent.com/45263160/55747542-dfabcc00-5a12-11e9-9b01-48c4ff1941ee.png)

Could you also screenshot the encoding of the text file? on the right-down side of the window. Thanks.

**Comment by alexwender1** [comment]
![1](https://user-images.githubusercontent.com/45263160/55772616-48bb3000-5a63-11e9-9675-7e08ba0dfefc.png)
![2](https://user-images.githubusercontent.com/45263160/55772622-4a84f380-5a63-11e9-949e-ea9a6a16eb49.png)
![3](https://user-images.githubusercontent.com/45263160/55772623-4c4eb700-5a63-11e9-916a-c8ecd694d148.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
