### ISSUE TITLE
【deepin 25】【一般】【有空】【集成测试】【treeland】关闭窗口的 X 图标样式与设计不符

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#10572]
### SUMMARY | 问题概要

关联集成：https://github.com/linuxdeepin/developer-center/issues/10003

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23/amd64/deepin-desktop-community-23-amd64.iso
升级到最新内测环境（0830）
```

### STEPS TO REPRODUCE | 复现步骤

1. 打开多个窗口 - 进入多任务图标中，查看关闭窗口的 X 图标样式

### OBSERVED RESULT | 观察到的结果

1. X 关闭的样式显示错误
![937254d748b29956487188fa809ff407_origin(1)](https://github.com/user-attachments/assets/5b180a8d-249d-4124-a306-af613f24fb2e)

### EXPECTED RESULT | 期望的结果

1. X 关闭窗口的样式应为：
![截图_选择区域_20240905112216](https://github.com/user-attachments/assets/d7dd8dc7-4489-477b-b77d-fd1a1d859818)

**Comment by Groveer** [comment]
图标已更换

**Comment by baicailio** [comment]
2024.09.24
镜像：https://cdimage.uniontech.com/community/releases/23/amd64/deepin-desktop-community-23-amd64.iso
升级到最新内测环境（0830）
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1793:/dde/testing/ ./
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1793:/commercial/testing/ ./
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1918:/community/testing/ ./
验证步骤：提单步骤
验证现象：按预期结果更换多任务视图中窗口右上角x的图标
验证结论：验证通过
