### ISSUE TITLE
集成hplip-plugin

### ISSUE THREAD

**Issue by winexw** [linuxdeepin/developer-center#10599]
### package information | 软件包信息

| 包名 | 版本号 |
| :--: | :--: |
| hplip-plugin | 3.22.10deepin0 |

### Package repository address | 软件包仓库地址

deb  [trusted=yes] https://aptly.uniontech.com/pkg/nonfree-beige/release-candidate/aHBsaXAtcGx1Z2luXzMuMjIuMTAyMDI0LTA5LTA1IDE5OjQxOjU4/  unstable non-free

### changelog | 更新信息

更新和V23仓库hplip版本一致的hplip-plugin

### test suggestion | 测试建议

1、验证添加HP LaserJet 1020打印机选择HP LaserJet 1020, hpcups 3.22.10, requires proprietary plugin 驱动验证是否能够成功打印
2、没有打印机的情况可以添加file:///tmp/test.raw 这个uri作为打印机选择HP LaserJet 1020, hpcups 3.22.10, requires proprietary plugin驱动进行模拟打印

### Sphere of influence | 影响范围

只推送到V23仓库

**Comment by Zeno-sole** [comment]
关联集成 https://github.com/linuxdeepin/developer-center/issues/10601

**Comment by babyfengfjx** [comment]
@kobe337  请开展集成验证。

**Comment by kobe337** [comment]
【环境】：
镜像：Deepin OS-23-20240813103808-1_x86_64
内核：Linux hhh-PC 6.6.47-amd64-desktop-hwe #23.01.00.37 SMP PREEMPT_DYNAMIC Tue Aug 20 17:33:52 CST 2024 x86_64 GNU/Linux

【结论】：
测试通过，暂无严重问题及影响,安装校验、版本核对，使用命令sudo apt install hplip,安装成功同步完成hplip-plugin安装，安装hp laserjet 1200驱动，验证本地file:///tmp/test.raw,显示驱动被正常加载，验证通过
![hp111](https://github.com/user-attachments/assets/9703021b-f03e-400c-adb5-3ab4b5215082)
![image](https://github.com/user-attachments/assets/80eae2cb-6621-47af-9a31-81551dc82f7d)
