### ISSUE TITLE
[archlinux]手动更换登录壁纸出现的问题

### ISSUE THREAD

**Issue by kirigayakazushin** [linuxdeepin/developer-center#106]
根据帖子：https://bbs.deepin.org/forum.php?mod=viewthread&tid=41412&extra=
的描述，我进行了文件替换和删除cache。然后开机lightdm无背景。cache只有启动器的模糊背景图片。
想确认一下该替换是否有效。image-blur，怎么想都是和启动器有关系，和登录锁屏的壁纸有什么关系= = 
原步骤为
> 
1、首先自己替换掉 /usr/share/backgrounds/desktop.jpg 这张图片为自己喜欢的
2、sudo rm -rf /var/cache/image-blur/*
3、好好享受自己的壁纸啦。

**Comment by pangpangpang3** [comment]
这个操作存在一定的问题，稍后会统一根据设计进行新的修改，请等待一段时间。
