### ISSUE TITLE
[Deepin Integration]~[V23-Release] integrate by zeno / v25-stage2

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#10618]
包名 | 版本

Package: akonadi
Version: 4:22.12.3-1

Package: asciidoc
Version: 10.2.1-1

Package: botan
Version: 2.18.2+dfsg-1deepin1

Package: cairocffi
Version: 1.7.1-2

Package: cfgrib
Version: 0.9.12.0-1

Package: cherrypy3
Version: 18.9.0-2

Package: clisp
Version: 1:2.49.20210628.gitde01f0f-3.1deepin1

Package: cln
Version: 1.3.6-4deepin1

Package: cluster-glue
Version: 1.0.12-22deepin1

Package: command-not-found
Version: 23.04.0-1deepin1

Package: constantly
Version: 23.10.4-2

Package: crash
Version: 8.0.5-1

Package: cryfs
Version: 0.11.4-1deepin1

Package: cue2toc
Version: 0.4-5.1

Package: dblatex
Version: 0.3.12py3-4

Package: debhelper
Version: 13.16

Package: debputy
Version: 0.1.48

Package: dlm
Version: 4.3.0-1

Package: e2fsprogs
Version: 1.47.0-2deepin1

Package: ell
Version: 0.67-1

Package: ffcall
Version: 2.4-2.1deepin1

Package: fmtlib
Version: 10.1.1+ds1-2

Package: freeipmi
Version: 1.6.13-3

Package: gcl
Version: 2.6.14-11

Package: gnome-online-accounts
Version: 3.45.2-1

Package: gnupg2
Version: 2.2.43-8

Package: graphite2
Version: 1.3.14-2

Package: gyp
Version: 0.16.2-1

Package: hwloc
Version: 2.11.0-2

Package: ieee-data
Version: 20240722

Package: ipython-genutils
Version: 0.2.0-6

Package: isodate
Version: 0.6.1-2

Package: iwd
Version: 2.19-1

Package: jackd2
Version: 1.9.22~dfsg-3

Package: jeepney
Version: 0.8.0-3

Package: joblib
Version: 1.3.2-2

Package: libaec
Version: 1.1.3-1

Package: libaio
Version: 0.3.113-8deepin1

Package: libcommons-cli-java
Version: 1.6.0-1

Package: libffado
Version: 2.4.9-1

Package: libhandy-1
Version: 1.8.3-1

Package: libmodule-manifest-perl
Version: 1.09-2

Package: libpwquality
Version: 1.4.5-3

Package: librest
Version: 0.9.1-6

Package: librsvg
Version: 2.58.0+dfsg-1

Package: libsecret
Version: 0.21.4-1

Package: libyuv
Version: 0.0.1888.20240710-3

Package: libzstd
Version: 1.5.6+dfsg-1

Package: log4cpp
Version: 1.1.4-1

Package: lvm2
Version: 2.03.22-1

Package: mercurial
Version: 6.8-3

Package: network-manager-openconnect
Version: 1.2.10-2deepin1

Package: node-assume
Version: 2.3.0-4

Package: node-follow-redirects
Version: 1.15.6+~1.14.4-2

Package: node-grunt-contrib-nodeunit
Version: 4.0.0-2

Package: node-gulp-util
Version: 3.0.36+~cs7.1.15-2

Package: node-gyp
Version: 9.3.0-3

Package: node-mock-fs
Version: 5.1.4-1

Package: node-rollup
Version: 3.29.4-3

Package: node-sha
Version: 3.0.0-3

Package: node-stealthy-require
Version: 1.1.1-6

Package: node-temp
Version: 0.9.4+~0.9.1-2

Package: numba
Version: 0.59.0+dfsg-2

Package: openpace
Version: 1.1.2+ds+git20220117+453c3d6b03a0-1.1

Package: opensc
Version: 0.25.1-1

Package: pacemaker
Version: 2.1.6-4

Package: pci.ids
Version: 0.0~2024.06.23-1

Package: pexpect
Version: 4.9-2

Package: platformdirs
Version: 4.2.1-1

Package: postgresql-16
Version: 16.3-1

Package: pycryptodome
Version: 3.20.0+dfsg-3

Package: pydevd
Version: 3.1.0+ds-2

Package: pydocstyle
Version: 6.3.0-1.1

Package: pyflakes
Version: 3.2.0-1

Package: pylint
Version: 3.2.6-1

Package: pytest-forked
Version: 1.6.0-2

Package: pytest-localserver
Version: 0.8.1-2

Package: pytest-mpi
Version: 0.6-5

Package: pytest-mpl
Version: 0.17.0-1

Package: python-argcomplete
Version: 3.4.0-2

Package: python-argh
Version: 0.31.2-1

Package: python-astor
Version: 0.8.1-4

Package: python-cliapp
Version: 1.20180812.1-6

Package: python-coverage-test-runner
Version: 1.13.1-6

Package: python-croniter
Version: 2.0.1-3

Package: python-distutils-extra
Version: 3.0

Package: python-django-formtools
Version: 2.4.1-2

Package: python-ecdsa
Version: 0.19.0-2

Package: python-etcd
Version: 0.4.5+git20240809.d2889f7-0deepin1

Package: python-eventlet
Version: 0.35.1-3

Package: python-flake8
Version: 7.1.1-1

Package: python-fs
Version: 2.4.16-4

Package: python-gmpy2
Version: 2.1.5-3

Package: python-graphviz
Version: 0.20.2-1

Package: python-h5netcdf
Version: 1.3.0-1

Package: python-handy-archives
Version: 0.2.0-3

Package: python-httplib2
Version: 0.22.0-1

Package: python-hypothesis
Version: 6.111.2-1

Package: python-imageio
Version: 2.35.1-1

Package: python-jaraco.functools
Version: 4.0.2-1

Package: python-logutils
Version: 0.3.5-3

Package: python-magic
Version: 2:0.4.27-3

Package: python-mccabe
Version: 0.7.0-1

Package: python-mitogen
Version: 0.3.9-1

Package: python-munch
Version: 4.0.0-1

Package: python-oauthlib
Version: 3.2.2-1

Package: python-padme
Version: 1.1.1-5

Package: python-public
Version: 4.1.0-1

Package: python-pyelftools
Version: 0.31-1

Package: python-pyfakefs
Version: 5.6.0-1

Package: python-pyftpdlib
Version: 1.5.9-2

Package: python-pymysql
Version: 1.1.1-1

Package: python-pytest-asyncio
Version: 0.20.3-1.3

Package: python-pytest-subtests
Version: 0.13.1-1

Package: python-pytest-trio
Version: 0.8.0-3

Package: python-repoze.sphinx.autointerface
Version: 1.0.0-2

Package: python-snuggs
Version: 1.4.7-4

Package: python-sphinxcontrib.apidoc
Version: 0.3.0-5

Package: python-sure
Version: 2.0.1+git.2023.02.06.3aef950b7c-3

Package: python-tomli
Version: 2.0.1-2

Package: python-trie
Version: 0.4.0+ds-1

Package: python-versioneer
Version: 0.29-1

Package: python-whoosh
Version: 2.7.4+git6-g9134ad92-8

Package: python-zstandard
Version: 0.23.0-2

Package: qscintilla2
Version: 2.14.1+dfsg-1

Package: quart
Version: 0.19.6-1

Package: r-cran-sp
Version: 1:2.1-2+dfsg-1

Package: rdflib
Version: 7.0.0-1

Package: rdma-core
Version: 50.0-1

Package: rich
Version: 13.7.1-1

Package: routes
Version: 2.5.1-3deepin1

Package: ruby-builder
Version: 3.2.4-2

Package: ruby-em-spec
Version: 0.2.7-1.1

Package: ruby-eventmachine
Version: 1.3~pre20220315-df4ab006-5

Package: ruby-http-parser
Version: 1.2.3-1

Package: ruby-jwt
Version: 2.7.1-1

Package: ruby-kgio
Version: 2.11.2-2

Package: ruby-multi-json
Version: 1.14.1-2

Package: ruby-mysql2
Version: 0.5.5-3

Package: ruby-nio4r
Version: 2.7.3-1

Package: ruby-prof
Version: 1.7.0-1

Package: ruby-rbnacl
Version: 7.1.1-1

Package: ruby-remcached
Version: 0.4.1-3.1

Package: ruby-rest-client
Version: 2.1.0-3

Package: ruby-sassc
Version: 2.4.0+ds-2

Package: ruby-sqlite3
Version: 1.6.9-2

Package: ruby-tilt
Version: 2.0.11-2

Package: sane-frontends
Version: 1.0.14-18

Package: sass-stylesheets-bulma
Version: 0.9.4~ds-1

Package: scalapack
Version: 2.2.1-3.1

Package: sddm
Version: 0.21.0-1

Package: sigscheme
Version: 0.9.1-2deepin1

Package: sip6
Version: 6.8.6-1

Package: skimage
Version: 0.24.0-2

Package: slurm-wlm
Version: 22.05.8-4+deb12u2deepin1

Package: sphinx-argparse-cli
Version: 1.17.0-1

Package: sphinx-click
Version: 5.1.0-1

Package: sphinx-design
Version: 0.6.1-1

Package: sphinx-notfound-page
Version: 1.0.0-1

Package: sphinx-panels
Version: 0.6.0-4

Package: sphinx-tabs
Version: 3.4.4-1

Package: sphinxcontrib-autoprogram
Version: 0.1.9-1

Package: sphinxcontrib-qthelp
Version: 2.0.0-1

Package: sphinxcontrib-serializinghtml
Version: 2.0.0-1

Package: sphinxcontrib-spelling
Version: 7.7.0-1

Package: sphinxcontrib-trio
Version: 1.1.2-3

Package: sphinxtesters
Version: 0.2.3-5

Package: spirv-llvm-translator-17
Version: 17.0.0-4deepin1

Package: stringencoders
Version: 3.10.3+git20180306-1.1

Package: sysstat
Version: 12.7.5-2

Package: tcsh
Version: 6.24.13-2

Package: tl-expected
Version: 1.1.0-2

Package: toolz
Version: 0.12.1-1

Package: tqdm
Version: 4.66.5-1

Package: utf8proc
Version: 2.9.0-1

Package: uucp
Version: 1.07-30

Package: waitress
Version: 3.0.0-1

Package: webkit2gtk
Version: 2.44.2-1

Package: websocketpp
Version: 0.8.2-4

Package: wpewebkit
Version: 2.44.2-1

Package: xmlbeans
Version: 4.0.0-2

Package: yard
Version: 0.9.36-1

Package: zbar
Version: 0.23.93-5

Package: zenity
Version: 4.0.2-1

Package: zlib
Version: 1:1.3.dfsg+really1.3.1-1deepin1

**Comment by Zeno-sole** [comment]
**Integration Test Info**
### Test suggestion | 测试建议



### Influence | 影响范围









































































































### ADDITIONAL INFORMATION | 额外补充

**Comment by Zeno-sole** [comment]
仓库地址： deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1952/testing/ ./

**Comment by babyfengfjx** [comment]
@xuqi27837288  请开展集成验证。

**Comment by xuqi27837288** [comment]
【验证环境】：v23 Release镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240814
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.9.6-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：集成测试通过
