### ISSUE TITLE
deepin-compressor crashes on launch on ArchLinux

### ISSUE THREAD

**Issue by Ernest-su** [linuxdeepin/developer-center#10611]
### SUMMARY | 问题概要

deepin-compressor: error while loading shared libraries: libcompressor-interface.so: cannot open shared object file: No such file or directory

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
Distribution: archlinux
Package: deepin-compressor-5.12.23-5
```

### STEPS TO REPRODUCE | 复现步骤

❯ deepin-compressor
deepin-compressor: error while loading shared libraries: libcompressor-interface.so: cannot open shared object
file: No such file or directory

**Comment by Ernest-su** [comment]
ADDITIONAL INFORMATION | 额外补充
https://gitlab.archlinux.org/archlinux/packaging/packages/deepin-compressor/-/issues/1
https://github.com/linuxdeepin/developer-center/issues/7329

**Comment by UTsweetyfish** [comment]
@felixonmars may have a look?
