### ISSUE TITLE
google浏览器图标显示模糊问题修复

### ISSUE THREAD

**Issue by dengbo11** [linuxdeepin/developer-center#10623]
### package information | 软件包信息

cn.google.chrome.linyaps | 128.0.6613.120

### Package repository address | 软件包仓库地址

name: old url: http://repo-dev.cicd.getdeepin.org/

### changelog | 更新信息

1. 修改玲珑仓库，ll-cli repo modify http://repo-dev.cicd.getdeepin.org --name old
2. 安装最新cn.google.chrome.linyaps(ll-cli install cn.google.chrome.linyaps/128.0.6613.120)
3. 验证bug是否解决

### Sphere of influence | 影响范围

https://pms.uniontech.com/bug-view-271385.html

google浏览器在高分屏上图标正常显示

**Comment by babyfengfjx** [comment]
@vivianxf  请开展回归验证。

**Comment by dengbo11** [comment]
已推送外网
