### ISSUE TITLE
玲珑应用大小裁剪集成

### ISSUE THREAD

**Issue by dengbo11** [linuxdeepin/developer-center#10624]
### package information | 软件包信息

org.deepin.browser/6.5.5.4
org.deepin.mail/6.4.10.1
org.dde.calendar/5.14.5.1

### Package repository address | 软件包仓库地址

name: old url: http://repo-dev.cicd.getdeepin.org/

### changelog | 更新信息

1. 修改玲珑仓库，ll-cli repo modify http://repo-dev.cicd.getdeepin.org --name old
2. 安装上面三款应用
3. 测试应用功能是否正常

### Sphere of influence | 影响范围

应用正常使用

**Comment by babyfengfjx** [comment]
@vivianxf  请开展回归验证。

**Comment by vivianxf** [comment]
集成验证通过，请及时合入：

1.切换仓库成功，更新安装应用成功
2.玲珑安装，卸载，运行正常
3.系统基本功能正常，暂时无严重影响

综上所述，本次集成通过~
