### ISSUE TITLE
hi, i also fond a err 

### ISSUE THREAD

**Issue by liubailin2017** [linuxdeepin/developer-center#1062]
本来 
1+2*2(2+2) =  17
但是计算结果为 [24[] 
![_deepin-calculator_20190110215819](https://user-images.githubusercontent.com/30728091/50973347-a0f59b00-1523-11e9-978d-4c005c3b54c8.png)

**Comment by licardoY** [comment]
![深度截图_deepin-calculator_20190409111656](https://user-images.githubusercontent.com/20562449/55771040-06244280-5ab9-11e9-943c-dc3854ade24c.png)

**Comment by lolimay** [comment]
![image](https://user-images.githubusercontent.com/32427260/55787466-e7d63b00-5ae8-11e9-8b8c-b83118a1771f.png)

**Comment by lolimay** [comment]
确实有毒

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
