### ISSUE TITLE
[Deepin Integration]~[V23] 23 integrated  by zeno@  镜像裁剪

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#10628]
### Package information | 软件包信息

包名 | 版本
--  | --
null

### Package repository address | 软件包仓库地址

    镜像地址：  https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240911/deepin-23-beige-release-amd64-20240911-174753.iso  

### Changelog | 更新信息
裁剪镜像大小

**Comment by Zeno-sole** [comment]
**Integration Test Info**
### Test suggestion | 测试建议
玲珑、 镜像构建裁剪月500M 
请覆盖常见的 dde 刻盘、ventoy 、光盘刻录等方式安装


### Influence | 影响范围
更新、内核安装


### ADDITIONAL INFORMATION | 额外补充

**Comment by babyfengfjx** [comment]
@xuqi27837288  请开展验证，主要覆盖镜像的安装，系统基本功能的使用，中文，海外的安装场景，初步分析至少包含以下内容：

# 安装方式
- 通过自带镜像制作工具制作启动盘；
- 通过ventoy制作启动盘；
- 通过其他软件制作启动盘
- 通过光盘刻录制作启动盘

# 安装类型
- 支持安全启动方式
- 支持关闭安全启动方式

# 安装类型

- 高级安装
- 全盘安装
- 自定义安装
- 创建lvm安装
- 多盘安装
- 单盘安装

# 国际化支持

- 中文语言安装，正常使用
- 海外语言安装，正常使用

上述场景可以交叉进行，确保都有覆盖到即可。

**Comment by xuqi27837288** [comment]
【验证环境】：v23 Release镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240911
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.9.6-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：集成测试通过

已验证场景如下:
![image](https://github.com/user-attachments/assets/7073d380-9dfe-4d82-9854-aa284429c671)

新引入问题:
0911镜像中开启和关闭内测通道有报错,待解决修复
