### ISSUE TITLE
请求测试Treeland定制镜像

### ISSUE THREAD

**Issue by Groveer** [linuxdeepin/developer-center#10642]
### package information | 软件包信息

软件包已集成到镜像中

### Package repository address | 软件包仓库地址

不需要额外仓库地址

### test suggestion | 测试建议

两个测试镜像：
1. 6.6内核：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240913/deepin-23-beige-release-treeland-amd64-20240913-183046.iso 
2. 4.19内核：https://ci.deepin.com/repo/deepin/deepin-ports/cdimage/treeland/deepin-23-beige-release-treeland-419-amd64-20240913-190248.iso

### ADDITIONAL INFORMATION | 额外补充

本次镜像为Treeland 定制镜像，已设置为默认启动Treeland，测试Treeland能否正常登录，桌面环境能否正常启动，打开终端和文管能否正常显示，dde-shell启动慢的问题暂不处理

**Comment by babyfengfjx** [comment]
@luodeepin  请开展测试，覆盖两个镜像，确保treeland环境能够正常进入，基本场景可正常工作即可，有相关问题可以及时与郭垚沟通推进。

**Comment by luodeepin** [comment]
测试通过
1. 6.6内核：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240913/deepin-23-beige-release-treeland-amd64-20240913-183046.iso 本镜像中 6.6内核可以安装登录启用
2. 终端 和 文件管理器 可以正常运行

按照测试范围评估结论通过

其他信息：
1.在镜像 https://ci.deepin.com/repo/deepin/deepin-ports/cdimage/treeland/deepin-23-beige-release-treeland-419-amd64-20240913-190248.iso  中只单独测试了 内核 4.19 安装完重启后，设置用户界面一直没显示
2. 部分应用（控制中心、文本编辑器、音乐、邮箱、影院、截图录屏、看图、相册、画板、文档查看器、帮助手册、系统监视器、日志收集工具、欢迎、相机、）无法运行
3. 深度之家打开后显示网络错误
4. 磁盘管理器认证框不能输入密码

**Comment by Groveer** [comment]
收到  已完成测试
