### ISSUE TITLE
深度文管搜索建议

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#1065]
15.9.3升级后，deepin-everything读死机械硬盘，杀死又启动，无奈，找到文件路径，改名，反应的人不多，可能是大多数人用的是固态硬盘，官方始终没人出来解释。
后来发现文管搜索崩溃，后来又发现搜索无结果，大胆猜想：deepin-everything是文管搜索的后台，大概是做建立索引之类的功能。
系统什么最重要？流畅，速度，低资源消耗。
如果是小白，遇到系统卡，早就转粉了。
我想要什么搜索功能？我只想要过滤（只能当前目录），基本上无延时。
```
void QFileSystemModel::setNameFilters(const QStringList &filters)
```
所以，我建议将快搜（过滤）和精搜拆分给不同的需求。
![](https://www.simipic.com/images/2019/04/10/search43d9503f88d4c015.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
