### ISSUE TITLE
我们尝试制作的 Fedora 30 DDE LiveISO，startdde 高概率启动失败

### ISSUE THREAD

**Issue by cheese** [linuxdeepin/developer-center#1066]
## 缺陷描述

我们尝试制作的 Fedora 30 DDE LiveeISO，使用一个叫 liveuser 的新用户并设置无密码自动登录。

在首次登录时，startdde 高概率启动失败。只报一行日志：
```
Apr 04 01:36:45 deepin-desktop-live startdde[1365]: main.go:77: x protocol authentication refused: No protocol specified
```

完整日志：https://paste.fedoraproject.org/paste/b-RtUakC9gqATFFvM4LaiQ

startdde 退出后会回到 lightdm，再点击登录的话必然成功登录。
退出回到 lightdm 后，如果重启 lightdm，也必然能实现 liveuser 自动登录。

## 复现步骤

可以从下面网盘地址下载 iso，可以用虚拟机测试
https://pan.baidu.com/s/1F7LKfptwc_zZteMHVGLXcw
code: 2xzv

## 期望行为

liveuser 必然可以自动登录成功。

### 发行版以及版本

Fedora 30

### 相关的软件包版本

尝试了多个版本。最新的 startdde-3.14.1 也有问题。

### 其他内容

我们在 Fedora 30 开发周期完成了 DDE 的打包工作，如果要将 DDE 添加为一种官方的 live ISO，那这个问题必须解决。

**Comment by hualet** [comment]
@electricface 你试试？

**Comment by cheese** [comment]
定位出来是 Fedora livecd hostname 设置跟 lightdm 有 race condition，在 Fedora 内部提交了 PR https://pagure.io/fedora-kickstarts/pull-request/529
