### ISSUE TITLE
系统开机音效总是以最大音量播放

### ISSUE THREAD

**Issue by lolimay** [linuxdeepin/developer-center#1067]
## 缺陷描述
开机时音效总是以最大音量播放开机音效

## 期望行为

根据当前的设置的系统音量播放开机音效

## 截图

![image](https://user-images.githubusercontent.com/32427260/55879671-bc7b4b00-5bd1-11e9-9601-45dbe82fea26.png)
<img src="https://user-images.githubusercontent.com/32427260/55879895-357aa280-5bd2-11e9-8e7d-69fbe5cfe22f.jpg" width="250">

### 发行版以及版本
deepin 15.9.3

### 相关的软件包版本
无

**Comment by lolimay** [comment]
不对，我尝试在控制中心关闭了系统音效，但是重启电脑后仍会以最大音量播放开机音效。

**Comment by electricface** [comment]
会记录声音配置，然后在播放之前恢复声音配置的。

**Comment by lolimay** [comment]
> 会记录声音配置，然后在播放之前恢复声音配置的。

但是我在关机之前已确认系统声音已调整到0了，重启后还会以最大声音播放。而且似乎我关闭了系统音效后仍有开机音乐。
