### ISSUE TITLE
[Deepin Integration]~[V23-Release] integrate by UTsweetyfish

### ISSUE THREAD

**Issue by UTsweetyfish** [linuxdeepin/developer-center#10676]
### package information | 软件包信息

包名 | 版本
--  | --

请转 OBS: https://build.deepin.com/project/show/deepin:CI:TestingIntegration:test-integration-pr-2016

### Package repository address | 软件包仓库地址

    deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-2016/testing/ ./

**Comment by UTsweetyfish** [comment]
**Integration Test Info**

### Test suggestion | 测试建议

gcc版本降级 相关软件包rebuild 
验证升级场景，验证常用软件安装，自行发散各场景
pre: #10577 

### Influence | 影响范围

工具链、系统底层

### ADDITIONAL INFORMATION | 额外补充

**Comment by babyfengfjx** [comment]
@kobe337  请开展集成验证。

**Comment by kobe337** [comment]
【环境】：
镜像：Deepin OS-23-20240925022724-1_x86_64
内核：Linux deepin-PC 6.6.52-amd64-desktop-hwe #23.01.00.38 SMP PREEMPT_DYNAMIC Tue Sep 24 17:30:32 CST 2024 x86_64 GNU/Linux

【结论】：
测试通过，暂无严重问题及影响,安装校验，版本核对，验证覆盖以下场景：
1、验证fcitx5输入法相关内容,包括搜狗输入法
2、ffmpeg基本功能-播放视频
3、验证opencc简繁互转
4、验证vlc播放器基本功能
5、验证WPS的基本功能
6、验证lshw命令
7、验证packagekit软件包基本功能，服务状态检查
8、验证vlc播放器基本功能
9、批量安装应用商店应用-装机必备
10、常用应用的基本功能使用，如文件管理器、浏览器、启动器等
