### ISSUE TITLE
[BUG] 使用IPhone开USB热点拖小米笔记本有高概率死机

### ISSUE THREAD

**Issue by lolimay** [linuxdeepin/developer-center#1068]
## 缺陷描述
在正常使用我的小米笔记本时，经常出现无故死机，体现为屏幕凝固（所有动画暂停），键盘鼠标无法控制，无法进入tty，只能长按电源键关机重启。发生频率极高，最高记录为一个小时内死机三次。目前仅个人的小米笔记本有该问题，已严重影响到正常使用；另一台神舟笔记本则没有上诉问题。

## 复现步骤
复现步骤为：
1. 开机
2. 使用USB将IPONE连接至电脑，手机开机USB热点，笔记本连接至有线连接2
3. 正常使用电脑（如使用Chrome浏览网页、使用WPS2019编辑文档）
4. 电脑突然死机，屏幕冻结。

## 期望行为
不再发生屏幕冻结现象

## 截图
无

### 发行版以及版本
deepin 15.9.3
小米 15.6 指纹版 （i7-8250u）
### 相关的软件包版本
未知

### 其他内容
请问可以通过什么方式获取相应的日志，来进一步分析死机的原因呢？

**Comment by bighua** [comment]
换一个吧，哈哈哈

**Comment by lolimay** [comment]
这两天尝试不去使用手机开USB热点拖小米笔记本上网，竟然连续三天没有死机。有充分理由怀疑是由于手机的有线热点导致笔记本死机的。

请问官方有什么方法进一步定位问题发生的原因吗？或者有没有什么方法获取相应的日志呢？

**Comment by listenerri** [comment]
> 这两天尝试不去使用手机开USB热点拖小米笔记本上网，竟然连续三天没有死机。有充分理由怀疑是由于手机的有线热点导致笔记本死机的。
> 
> 请问官方有什么方法进一步定位问题发生的原因吗？或者有没有什么方法获取相应的日志呢？

是 cpu/ram 占用很高还是单纯的界面无任何相应？

**Comment by lolimay** [comment]
死机的时候根本无法操作，连tty都进不去，整个屏幕就和冻住了一样。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
