### ISSUE TITLE
[Feature Request] 双屏显示的时候多任务视图将窗口根据所在的显示器显示

### ISSUE THREAD

**Issue by CareF** [linuxdeepin/developer-center#1069]
比如我几个浏览器窗口在显示器 A, 文本编辑器在显示器 B, 进入多任务视图 (multitasking view) 时, 希望浏览器窗口也只显示在显示器 A 上, 编辑器在 B. 也可以通过在多任务视图中拖动窗口来移动到不同的显示器上.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
