### ISSUE TITLE
[archlinux]快捷键部分失效

### ISSUE THREAD

**Issue by kirigayakazushin** [linuxdeepin/developer-center#107]
当第三次注销或重启以后，部分快捷键失效。
刚开始我以为是我把系统玩坏了，然后重装了系统，但是不知道第几次登录用户以后，ctrl alt t,ctrl alt a,super tab，徽标键，热区全部失效。配置文件删除的话，依旧是过几次重启就无法正常使用这几个快捷键了。

**Comment by fasheng** [comment]
应该是keybinding模块挂了吧，之前gccgo编译时若频繁按快捷键也能重现，不过用go编译后我这边就好了，你下次再遇到可以上传下goroutine panic信息
```journalctl /usr/lib/deepin-daemon/dde-session-daemon```

**Comment by kirigayakazushin** [comment]
➜  ~ journalctl /usr/lib/deepin-daemon/dde-session-daemon
-- Logs begin at 一 2016-06-27 17:31:55 CST, end at 四 2016-07-14 13:41:22 CST. --
6月 27 18:41:51 kazushin daemon/dde-session-daemon[556]: proc.c:626: App log level: 5
6月 27 18:41:51 kazushin daemon/loader[556]: .:0: enable module keybinding
6月 27 18:41:51 kazushin daemon/loader[556]: .:0: enable module keybinding done, cost 193.6583ms
6月 27 18:41:51 kazushin daemon/loader[556]: .:0: enable module appearance
6月 27 18:41:51 kazushin daemon/loader[556]: .:0: enable module appearance done, cost 108.285723ms
6月 27 18:41:51 kazushin daemon/loader[556]: .:0: enable module clipboard
6月 27 18:41:51 kazushin daemon/loader[556]: .:0: enable module clipboard done, cost 58.806µs
6月 27 18:41:51 kazushin daemon/loader[556]: .:0: enable module inputdevices
6月 27 18:41:52 kazushin daemon/loader[556]: .:0: enable module inputdevices done, cost 620.534383ms
6月 27 18:41:52 kazushin daemon/loader[556]: .:0: enable module timedate
6月 27 18:41:52 kazushin daemon/loader[556]: .:0: enable module timedate done, cost 124.999607ms
6月 27 18:41:52 kazushin daemon/loader[556]: .:0: enable module network
6月 27 18:41:52 kazushin daemon/network[556]: .:0: initialize network
6月 27 18:41:52 kazushin daemon/network[556]: .:0: config file: /home/kirigaya/.config/deepin/network.json
6月 27 18:41:52 kazushin daemon/dde-session-daemon[701]: proc.c:626: There already has a dde daemon running.
6月 27 18:41:53 kazushin daemon/network[556]: .:0: add device &network.device{nmDev:(*networkmanager.Device)(0xc208351860), nmDevWireless:(*networkmanag
6月 27 18:41:53 kazushin daemon/network[556]: .:0: add device &network.device{nmDev:(*networkmanager.Device)(0xc208007ef0), nmDevWireless:(*networkmanag
6月 27 18:41:53 kazushin daemon/network[556]: .:0: add device &network.device{nmDev:(*networkmanager.Device)(0xc2080a83c0), nmDevWireless:(*networkmanag
6月 27 18:41:53 kazushin daemon/network[556]: .:0: add connection &network.connection{nmConn:(*networkmanager.SettingsConnection)(0xc2082d83c0), connTyp
6月 27 18:41:53 kazushin daemon/network[556]: .:0: add connection &network.connection{nmConn:(*networkmanager.SettingsConnection)(0xc2082d9b40), connTyp
6月 27 18:41:53 kazushin daemon/network[556]: .:0: add connection &network.connection{nmConn:(*networkmanager.SettingsConnection)(0xc2082d9580), connTyp
6月 27 18:41:53 kazushin daemon/network[556]: .:0: add connection &network.connection{nmConn:(*networkmanager.SettingsConnection)(0xc208346b00), connTyp
6月 27 18:41:53 kazushin daemon/network[556]: .:0: add connection &network.connection{nmConn:(*networkmanager.SettingsConnection)(0xc208192f40), connTyp
6月 27 18:41:53 kazushin daemon/network[556]: .:0: add connection &network.connection{nmConn:(*networkmanager.SettingsConnection)(0xc2081ca580), connTyp
6月 27 18:41:53 kazushin daemon/loader[556]: .:0: enable module network done, cost 723.056728ms
6月 27 18:41:53 kazushin daemon/loader[556]: .:0: enable module sessionwatcher
6月 27 18:41:53 kazushin daemon/loader[556]: .:0: enable module sessionwatcher done, cost 29.006999ms
6月 27 18:41:53 kazushin daemon/loader[556]: .:0: enable module mounts
6月 27 18:41:53 kazushin daemon/loader[556]: .:0: enable module mounts done, cost 44.718759ms
6月 27 18:41:53 kazushin daemon/loader[556]: .:0: enable module screenedge
6月 27 18:41:53 kazushin daemon/loader[556]: .:0: enable module screenedge done, cost 201.020374ms
6月 27 18:41:53 kazushin daemon/loader[556]: .:0: enable module audio
6月 27 18:41:53 kazushin daemon/loader[556]: .:0: enable module audio done, cost 23.829804ms

**Comment by kirigayakazushin** [comment]
昨天发issues的时候，是刚确认问题所在。然后就新建用户了，现在又挂了。

**Comment by kirigayakazushin** [comment]
-- Logs begin at 一 2016-06-27 17:31:55 CST, end at 四 2016-07-14 13:45:59 CST. --
7月 14 21:33:08 mkacg daemon/dde-session-daemon[870]: main.go:70: App log level: 5
7月 14 21:33:08 mkacg daemon/loader[870]: loader.go:150: enable module sessionwatcher
7月 14 21:33:08 mkacg daemon/loader[870]: loader.go:158: enable module sessionwatcher done, cost 162.441668ms
7月 14 21:33:08 mkacg daemon/loader[870]: loader.go:150: enable module keybinding
7月 14 21:33:09 mkacg daemon/loader[870]: loader.go:158: enable module keybinding done, cost 84.201821ms
7月 14 21:33:09 mkacg daemon/loader[870]: loader.go:150: enable module screenedge
7月 14 21:33:09 mkacg daemon/loader[870]: loader.go:158: enable module screenedge done, cost 182.322211ms
7月 14 21:33:09 mkacg daemon/loader[870]: loader.go:150: enable module network
7月 14 21:33:09 mkacg daemon/network[870]: manager.go:108: initialize network
7月 14 21:33:09 mkacg daemon/network[870]: manager_config.go:58: config file: /home/kirigaya/.config/deepin/network.json
7月 14 21:33:09 mkacg daemon/network[870]: manager_device.go:242: add device &network.device{nmDev:(*networkmanager.Device)(0xc820388000), nmDevWireless
7月 14 21:33:09 mkacg daemon/network[870]: manager_device.go:242: add device &network.device{nmDev:(*networkmanager.Device)(0xc82011b0e0), nmDevWireless
7月 14 21:33:09 mkacg daemon/network[870]: manager_device.go:242: add device &network.device{nmDev:(*networkmanager.Device)(0xc82011ac30), nmDevWireless
7月 14 21:33:09 mkacg daemon/network[870]: manager_device.go:242: add device &network.device{nmDev:(*networkmanager.Device)(0xc8203530e0), nmDevWireless
7月 14 21:33:09 mkacg daemon/network[870]: manager_connection.go:143: add connection &network.connection{nmConn:(*networkmanager.SettingsConnection)(0xc
7月 14 21:33:09 mkacg daemon/network[870]: manager_connection.go:143: add connection &network.connection{nmConn:(*networkmanager.SettingsConnection)(0xc
7月 14 21:33:09 mkacg daemon/network[870]: manager_connection.go:143: add connection &network.connection{nmConn:(*networkmanager.SettingsConnection)(0xc
7月 14 21:33:09 mkacg daemon/network[870]: manager_connection.go:143: add connection &network.connection{nmConn:(*networkmanager.SettingsConnection)(0xc
7月 14 21:33:09 mkacg daemon/network[870]: manager_connection.go:143: add connection &network.connection{nmConn:(*networkmanager.SettingsConnection)(0xc
7月 14 21:33:09 mkacg daemon/network[870]: manager_connection.go:143: add connection &network.connection{nmConn:(*networkmanager.SettingsConnection)(0xc
7月 14 21:33:09 mkacg daemon/network[870]: manager_connection.go:143: add connection &network.connection{nmConn:(*networkmanager.SettingsConnection)(0xc
7月 14 21:33:09 mkacg daemon/network[870]: manager_connection.go:143: add connection &network.connection{nmConn:(*networkmanager.SettingsConnection)(0xc
7月 14 21:33:09 mkacg daemon/loader[870]: loader.go:158: enable module network done, cost 500.817206ms
7月 14 21:33:09 mkacg daemon/loader[870]: loader.go:150: enable module audio
7月 14 21:33:09 mkacg daemon/loader[870]: loader.go:158: enable module audio done, cost 6.607271ms
7月 14 21:33:09 mkacg daemon/loader[870]: loader.go:150: enable module appearance
7月 14 21:33:09 mkacg daemon/loader[870]: loader.go:158: enable module appearance done, cost 29.761295ms
7月 14 21:33:09 mkacg daemon/loader[870]: loader.go:150: enable module clipboard
7月 14 21:33:09 mkacg daemon/loader[870]: loader.go:158: enable module clipboard done, cost 65.255µs
7月 14 21:33:09 mkacg daemon/loader[870]: loader.go:150: enable module timedate
7月 14 21:33:10 mkacg daemon/loader[870]: loader.go:158: enable module timedate done, cost 319.389708ms
7月 14 21:33:10 mkacg daemon/loader[870]: loader.go:150: enable module bluetooth
7月 14 21:33:10 mkacg daemon/loader[870]: loader.go:158: enable module bluetooth done, cost 12.018µs
7月 14 21:33:10 mkacg daemon/loader[870]: loader.go:150: enable module screensaver
7月 14 21:33:10 mkacg daemon/bluetooth[870]: config.go:34: load bluetooth config file: /home/kirigaya/.config/deepin/bluetooth.json
7月 14 21:33:10 mkacg daemon/loader[870]: loader.go:158: enable module screensaver done, cost 5.904315ms
7月 14 21:33:10 mkacg daemon/loader[870]: loader.go:150: enable module power
7月 14 21:33:10 mkacg daemon/bluetooth[870]: agent.go:182: Register agent failed:  org.freedesktop.systemd1.NoSuchUnit:Unit dbus-org.bluez.service not f
7月 14 21:33:10 mkacg daemon/bluetooth[870]: utils_bluez.go:343: bluezWatchRestart &{/org/freedesktop/DBus org.freedesktop.DBus 0xc8203f58f0 map[] {0 0}
7月 14 21:33:10 mkacg daemon/bluetooth[870]: utils_bluez.go:69: org.freedesktop.systemd1.NoSuchUnit:Unit dbus-org.bluez.service not found.
                                                ->  config.go:57
                                                ->  asm_amd64.s:1998
7月 14 21:33:10 mkacg daemon/bluetooth[870]: bluetooth.go:121: org.freedesktop.systemd1.NoSuchUnit:Unit dbus-org.bluez.service not found.
                                                ->  asm_amd64.s:1998
7月 14 21:33:10 mkacg daemon/screensaver[870]: screensaver.go:144: SetTimeout to  895 0 false
7月 14 21:33:10 mkacg daemon/loader[870]: loader.go:158: enable module power done, cost 46.647691ms
7月 14 21:33:10 mkacg daemon/loader[870]: loader.go:150: enable module mounts
7月 14 21:33:10 mkacg daemon/dde-session-daemon[1042]: main.go:60: There already has a dde daemon running.
7月 14 21:33:10 mkacg daemon/loader[870]: loader.go:158: enable module mounts done, cost 241.073341ms
7月 14 21:33:10 mkacg daemon/loader[870]: loader.go:150: enable module inputdevices
7月 14 21:33:10 mkacg daemon/loader[870]: loader.go:158: enable module inputdevices done, cost 227.974162ms
7月 14 21:33:10 mkacg daemon/loader[870]: loader.go:150: enable module mpris
7月 14 21:33:10 mkacg daemon/loader[870]: loader.go:158: enable module mpris done, cost 2.253199ms
7月 14 21:33:10 mkacg daemon/loader[870]: loader.go:150: enable module systeminfo
7月 14 21:33:10 mkacg daemon/loader[870]: loader.go:158: enable module systeminfo done, cost 23.065974ms

**Comment by jouyouyun** [comment]
killall dde-session-daemon; env DDE_DEBUG_MATCH="keybinding" DDE_DEBUG_LEVEL="debug" /usr/lib/deepin-daemon/dde-session-daemon

@kirigayakazushin  执行这个命令后，按下失效的快捷键，贴下输出信息，tks！

**Comment by kirigayakazushin** [comment]
@jouyouyun  执行你给的命令以后，失效的快捷键是可以用了。我按下了CTRL+ALT+T&CTRL+ALT+A&徽标键。输出信息如下：

BUG_LEVEL="debug" /usr/lib/deepin-daemon/dde-session-daemon
<info> main.go:67: Log level is none and debug env exists, so ignore cmd.loglevel
Added: Mediakey

** (dde-session-daemon:2780): WARNING **: Data not from X server...
org.freedesktop.systemd1.NoSuchUnit:Unit dbus-org.bluez.service not found.
org.freedesktop.systemd1.NoSuchUnit:Unit dbus-org.bluez.service not found.
org.freedesktop.systemd1.NoSuchUnit:Unit dbus-org.bluez.service not found.
get DDE_SESSION_PROCESS_COOKIE_ID failed
<debug> handle_event.go:33: Handle key event: 28 control-mod1-mod2 28 t true
<debug> handle_event.go:56: Exec action: /usr/lib/deepin-daemon/default-terminal
<debug> handle_event.go:33: Handle key event: 28 control-mod1-mod2 28 t false
<debug> handle_event.go:33: Handle key event: 28 control-mod1-mod2 38 a true
<debug> handle_event.go:56: Exec action: deepin-screenshot
<debug> handle_event.go:33: Handle key event: 28 control-mod1-mod2 38 a false
<debug> handle_event.go:33: Handle key event: 0  133 Super_L true
<debug> handle_event.go:56: Exec action: dbus-send --print-reply --dest=com.deepin.dde.Launcher /com/deepin/dde/Launcher com.deepin.dde.Launcher.Toggle
<debug> handle_event.go:33: Handle key event: 0  133 Super_L true
<debug> handle_event.go:56: Exec action: dbus-send --print-reply --dest=com.deepin.dde.Launcher /com/deepin/dde/Launcher com.deepin.dde.Launcher.Toggle

**Comment by jouyouyun** [comment]
@kirigayakazushin  正常登录时，快捷键就失效？

**Comment by kirigayakazushin** [comment]
@jouyouyun  刚刚进行了一次注销和重启，都是失效的。

**Comment by jouyouyun** [comment]
@kirigayakazushin dde-session-daemon 这个进程确定存在？

**Comment by kirigayakazushin** [comment]
@jouyouyun 
刚开机。

![20160714150242](https://cloud.githubusercontent.com/assets/12298476/16830866/1bdcd026-4967-11e6-9cde-86b9e2ae1873.png)

**Comment by kirigayakazushin** [comment]
@fasheng @jouyouyun  对了，还有一个问题，当发生快捷键失效的时候，文件的关联似乎也有问题了。
比如我打开一张图片，我安装的有eog，可是关联里只有毫不相干的几个，打开文本也是。
![20160714161755](https://cloud.githubusercontent.com/assets/12298476/16832785/924ea946-4971-11e6-92a9-74e3a0b17e0f.png)
