### ISSUE TITLE
[BUG] Frequently video freezes and randomly crashes

### ISSUE THREAD

**Issue by saymoncoppi** [linuxdeepin/developer-center#1070]
Hello guys! Just to share...
I have 2 Samsungs NP530 running Linux Deepin (15.9.3) but they dont have the same hw.
One of them was facing an weird behavior (same as the subject) after the last release.

So since the user (my wife lol) didin't care about discover what happens and just need the system up again to work, I made a several moves togetter and I cant determine which of them fixes. But I can guarantee that one of them fixed.

No crashes, freezes or surprises.

# Newest video driver
sudo apt install xserver-xorg-video-intel 
https://www.vivaolinux.com.br/topico/Suporte/Instalar-drivers-onboard-intel-Debian
https://askubuntu.com/questions/166224/how-do-i-install-the-intel-graphics-driver-in-my-system

# Newest Mesa Utils
sudo apt-get install mesa-utils
http://www.cgl.ucsf.edu/chimera/graphics/updatelinux.html
https://askubuntu.com/questions/166224/how-do-i-install-the-intel-graphics-driver-in-my-system

# Disable Google Chrome Hardware Acceleration
https://askubuntu.com/questions/1059397/videos-hang-freeze-for-a-few-seconds-on-ubuntu-18-04
https://www.technize.net/google-chrome-disable-hardware-acceleration/

# Disable Intel hyperthreading 
https://askubuntu.com/questions/1059397/videos-hang-freeze-for-a-few-seconds-on-ubuntu-18-04

# Fix "acpi = force" on /etc/default/grub
https://www.youtube.com/watch?v=ZZBTSUbzT0g

# Custom Xorg conf
Workaround:
sudo nano /usr/share/X11/xorg.conf.d/20-intel.conf
...add
Section "Device"
 Identifier "Intel Graphics"
  Driver "intel"
 Option	"AccelMethod" "sna"
 Option "TearFree" "true"
 Option "DRI" "3"
EndSection
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1798961

# SSD issues
I didn't this but is also a reference if you facing something similar. Pay attention bc the tool is only for MS
https://askubuntu.com/questions/1107053/ubutnu-18-04-ssd-sometimes-freeze-for-seconds

See u guys! I hope it helps...
If some one discover which of them is really the fix, pls let me know. Bc here its working perfectly :)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
