### ISSUE TITLE
UOS AI 1.5.0集成请求

### ISSUE THREAD

**Issue by Clauszy** [linuxdeepin/developer-center#10718]
### package information | 软件包信息

包名 | 版本
-- | --
uos ai | 1.5.0
deepin-ai-daemon | 1.1.3 
deepin-systemassistant-knowledge | 0.0.9
deepin-modelhub  | 0.0.16 

### Package repository address | 软件包仓库地址

deb  [trusted=yes] https://aptly.uniontech.com/pkg/beige-v2/release-candidate/44CQVU9TIEFJ44CR5LiK5p625ZWG5bqXMjAyNC0wNC0zMCAxMDoyODo1MA/  unstable main

deb  [trusted=yes] https://aptly.uniontech.com/pkg/beige-v2/release-candidate/44CQdjIz44CR44CQVU9TIEFJ44CR5omT5YyF5rWL6K-V5Li76aKYLTIwMjQwOS0xMDIwMjQtMDktMzAgMDk6NTI6NTg/  unstable main

### changelog | 更新信息

UOS AI 1.5 新功能特性。

**Comment by luodeepin** [comment]
测试通过
1. uos ai可正常更新
2. deepin-ai-daemon 、deepin-systemassistant-knowledge 、deepin-modelhub 需要手动安装
3. 发散测试基础功能使用正常

**Comment by Clauszy** [comment]
### package information | 软件包信息

包名|版本
--|--
uos ai| 1.5.0.1 
deepin-ai-daemon| 1.1.4  
deepin-systemassistant-knowledge | 0.0.9  
deepin-modelhub| 0.0.16

### Package repository address | 软件包仓库地址

deb  [trusted=yes] https://aptly.uniontech.com/pkg/beige-v2/release-candidate/44CQVU9TIEFJ44CR5LiK5p625ZWG5bqXMjAyNC0wNC0zMCAxMDoyODo1MA/  unstable main

**Comment by UTsweetyfish** [comment]
@babyfengfjx uos ai 做了更新

**Comment by babyfengfjx** [comment]
@luodeepin  请开展集成验证。

**Comment by luodeepin** [comment]
测试通过
1. 新增引入一个BUG，与项目组沟通BUG先做遗留处理，之后修复优化，当前按测试通过处理
