### ISSUE TITLE
智能隐藏在屏幕左侧的dock,用鼠标快速移动到屏幕最左侧无法触发dock显示

### ISSUE THREAD

**Issue by ffftwo** [linuxdeepin/developer-center#1072]
## 缺陷描述
自动隐藏在屏幕左侧的dock,用鼠标快速移动到屏幕最左侧无法触发dock显示,慢慢移过去就可以
屏幕4个方向只有左侧会这样,时尚和简洁两种模式情况相同.
## 复现步骤

1. 设置dock状态为智能隐藏
2. 设置dock位置为左
3. 任意打开一个最大化窗口使dock自动隐藏
4. 以较快的速度将鼠标移动到屏幕最左侧
5. dock很大几率无法触发显示

## 期望行为

正常显示

### 发行版以及版本

archlinux lightdm dde
### 相关的软件包版本

 ~  yay -Qs deepin
local/deepin-account-faces 1.0.11-1 (deepin)
    Account faces for Linux Deepin
local/deepin-anything 0.0.6-1 (deepin)
    Deepin Anything file search tool
local/deepin-anything-dkms 0.0.6-1
    Deepin Anything file search tool
local/deepin-api 3.18.3-1 (deepin)
    Golang bindings for dde-daemon
local/deepin-boot-maker 2.0.4.11-1 (deepin-extra)
    Tool to create a bootable usb stick quick and easy
local/deepin-calculator 1.0.11-1 (deepin-extra)
    An easy to use calculator for ordinary users
local/deepin-calendar 1.2.6-1 (deepin)
    Calendar for Deepin Desktop Environment
local/deepin-clone 1.1.2-1 (deepin-extra)
    Disk and partition backup/restore tool
local/deepin-clutter 1.26.2-2
    A toolkit for creating fast, portable, compelling dynamic UIs for Deepin
local/deepin-cogl 1.22.5-2
    An object oriented GL/GLES Abstraction/Utility Layer for Deepin
local/deepin-community-wallpapers 1:1.7.7-1 (deepin-extra)
    Community wallpapers for DDE
local/deepin-control-center 4.9.12-1 (deepin)
    New control center for linux deepin
local/deepin-daemon 3.25.2-1 (deepin)
    Daemon handling the DDE session settings
local/deepin-desktop-base 2:2019.04.03-1 (deepin)
    Base component for Deepin
local/deepin-desktop-schemas 3.13.0-1 (deepin)
    GSettings deepin desktop-wide schemas
local/deepin-dock 4.9.6-1 (deepin)
    Deepin desktop-environment - dock module
local/deepin-draw 1.0.0-2 (deepin-extra)
    A lightweight drawing tool for Linux Deepin
local/deepin-file-manager 1:4.8.0-1 (deepin)
    Deepin File Manager
local/deepin-gtk-theme 17.10.10-1 (deepin)
    Deepin GTK Theme
local/deepin-icon-theme 15.12.69-1
    Deepin Icons
local/deepin-image-viewer 1.3.11-1 (deepin)
    Deepin Image Viewer
local/deepin-kwin 0.0.3.1-1
    KWin configures on DDE
local/deepin-launcher 4.6.9-1 (deepin)
    Deepin desktop-environment - Launcher module
local/deepin-manual 2.0.19-1 (deepin)
    Deepin User Manual
local/deepin-menu 3.4.1-1 (deepin)
    Deepin menu service for building beautiful menus
local/deepin-metacity 3.22.24-1
    2D window manager for Deepin
local/deepin-mutter 3.20.38-1
    Base window manager for deepin, fork of gnome mutter
local/deepin-network-utils 0.1.3-1 (deepin)
    DDE network utils
local/deepin-picker 1.6.5-1 (deepin-extra)
    Color picker tool for deepin
local/deepin-polkit-agent 0.2.6-1
    Deepin Polkit Agent
local/deepin-polkit-agent-ext-gnomekeyring 0.1.0-1 (deepin)
    GNOME keyring extension for dde-polkit-agent
local/deepin-qt-dbus-factory 1.1.1-1
    A repository stores auto-generated Qt5 dbus code
local/deepin-qt5dxcb-plugin 1.1.25-1 (deepin)
    Qt platform plugins for DDE
local/deepin-qt5integration 0.3.10-1 (deepin)
    Qt platform theme integration plugins for DDE
local/deepin-screen-recorder 2.7.8-1 (deepin-extra)
    Deepin Screen Recorder
local/deepin-screenshot 4.1.8-1 (deepin-extra)
    Easy-to-use screenshot tool for linuxdeepin desktop environment
local/deepin-session-ui 4.9.2-1 (deepin)
    Deepin desktop-environment - Session UI module
local/deepin-shortcut-viewer 1.3.5-1 (deepin)
    Deepin Shortcut Viewer
local/deepin-sound-theme 15.10.3-1 (deepin)
    Deepin sound theme
local/deepin-system-monitor 1.5.0-1 (deepin)
    A more user-friendly system monitor
local/deepin-terminal 3.2.2-1 (deepin-extra)
    Default terminal emulation application for Deepin
local/deepin-turbo 0.0.2-1 (deepin)
    A daemon that helps to launch applications faster
local/deepin-voice-recorder 1.3.9-1 (deepin-extra)
    Deepin Voice Recorder
local/deepin-wallpapers 1:1.7.7-1 (deepin)
    Default wallpapers for DDE
local/deepin-wm 1.9.38-1
    Deepin Window Manager
local/dtkwidget 2.0.10-1
    Deepin graphical user interface library
local/dtkwm 2.0.9-5
    Deepin Tool Kit Wm
local/startdde 3.14.2-1 (deepin)
    starter of deepin desktop environment

**Comment by ffftwo** [comment]
另外发现屏幕最左侧这一条是鼠标的真空区,任何点击滚动都没有反应

**Comment by listenerri** [comment]
kwin 下有这个问题
