### ISSUE TITLE
深度终端网址右键菜单添加【在浏览器中打开】

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#1073]
![](https://www.simipic.com/images/2019/04/12/-722294d487e99ca0.png)

**Comment by BLumia** [comment]
<kbd>Ctrl + 点击</kbd> 即可直接在浏览器中打开。

**Comment by justforlxz** [comment]
> Ctrl + 点击 即可直接在浏览器中打开。

恭喜 @sonichy 掌握了新的打开方式。

**Comment by lolimay** [comment]
> > Ctrl + 点击 即可直接在浏览器中打开。
> 
> 恭喜 @sonichy 掌握了新的打开方式。

他的意思是当鼠标移至链接上是，右击菜单会出现这个选项。诚然 <kbd>Ctrl</kbd > + 左击 也可以完成相同的效果，但是使用场景不一样(或许有的用户就是偏爱鼠标的方式)。
