### ISSUE TITLE
[Deepin Integration]~[V23-Beta3] feat: update kernel to 6.6.51 by Zeno-sole@deepin-community/linux-deepin-hwe by deepin-community-ci-bot[bot]

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#10733]
### Package information | 软件包信息

包名 | 版本
--  | --
kernel | 6.6.51

### Package repository address | 软件包仓库地址

    deb [trusted=yes] https://ci.deepin.com/repo/deepin/deepin-community/obs-repos/ kernel main

#### linux-deepin-hwe (6.6.51) unstable; urgency=medium

  * Update kernel to 6.6.51.

**Comment by Zeno-sole** [comment]
**Integration Test Info**
### Test suggestion | 测试建议
临时分支测试版本
文件复制IO测试是否有提升，使用cp测试

### Influence | 影响范围
内核


### ADDITIONAL INFORMATION | 额外补充

**Comment by babyfengfjx** [comment]
@kobe337  请开展集成验证。

**Comment by kobe337** [comment]
【环境】：
镜像：Deepin OS-23-20240814092717-1_x86_64
内核：Linux deepin-PC 6.6.51-amd64-desktop-hwe #23.01.00.38.1 SMP PREEMPT_DYNAMIC Fri Oct 11 09:55:36 CST 2024 x86_64 GNU/Linux

【结论】：
测试通过，暂无严重问题及影响, 安装校验、版本核对，使用cp命令与6.6.40内核进行对比数据如下：
![Image](https://github.com/user-attachments/assets/ce2d2532-2e3d-4a39-a64f-6598e67d472a)
