### ISSUE TITLE
topics oci 集成

### ISSUE THREAD

**Issue by UTsweetyfish** [linuxdeepin/developer-center#10746]
### package information | 软件包信息

共 208 golang 包，详见: [Show deepin:CI:topics:oci - OBS](https://build.deepin.com/project/monitor/deepin:CI:topics:oci?defaults=0&succeeded=1&failed=1&unresolvable=1&broken=1&blocked=1&dispatching=1&scheduled=1&building=1&finished=1&signing=1&locked=1&deleting=1&arch_aarch64=1&arch_loong64=1&arch_riscv64=1&arch_x86_64=1&repo_testing=1) 页面

<details><summary>Details</summary>

- containerd
- docker-libkv
- docker.io
- etcd
- go-containerregistry
- golang-bitbucket-creachadair-shell
- golang-dbus
- golang-github-14rcole-gopopulate
- golang-github-acarl005-stripansi
- golang-github-adamkorcz-go-fuzz-headers-1
- golang-github-aead-serpent
- golang-github-agext-levenshtein
- golang-github-antlr-antlr4
- golang-github-armon-go-socks5
- golang-github-asaskevich-govalidator
- golang-github-aws-aws-sdk-go-v2
- golang-github-aws-smithy-go
- golang-github-azure-azure-sdk-for-go
- golang-github-azure-go-ansiterm
- golang-github-cenkalti-backoff
- golang-github-checkpoint-restore-checkpointctl
- golang-github-checkpoint-restore-go-criu
- golang-github-cloudflare-backoff
- golang-github-cloudflare-cfssl
- golang-github-cockroachdb-cockroach-go
- golang-github-common-nighthawk-go-figure
- golang-github-containerd-btrfs
- golang-github-containerd-cgroups
- golang-github-containerd-errdefs
- golang-github-containerd-go-cni
- golang-github-containerd-go-runc
- golang-github-containerd-imgcrypt
- golang-github-containerd-log
- golang-github-containerd-nri
- golang-github-containerd-platforms
- golang-github-containerd-stargz-snapshotter
- golang-github-containerd-typeurl
- golang-github-containers-buildah
- golang-github-containers-common
- golang-github-containers-image
- golang-github-containers-libtrust
- golang-github-containers-luksy
- golang-github-containers-storage
- golang-github-coreos-bbolt
- golang-github-coreos-go-oidc
- golang-github-coreos-go-oidc-v3
- golang-github-creack-pty
- golang-github-deckarep-golang-set
- golang-github-disiqueira-gotree
- golang-github-distribution-reference
- golang-github-dnaeon-go-vcr
- golang-github-eapache-go-resiliency
- golang-github-evanphx-json-patch
- golang-github-fortytw2-leaktest
- golang-github-fsouza-go-dockerclient
- golang-github-fxamacker-cbor
- golang-github-getkin-kin-openapi
- golang-github-gin-contrib-sse
- golang-github-gin-gonic-gin
- golang-github-go-jose-go-jose.v3
- golang-github-go-kit-kit
- golang-github-go-openapi-analysis
- golang-github-go-openapi-errors
- golang-github-go-openapi-jsonpointer
- golang-github-go-openapi-jsonreference
- golang-github-go-openapi-loads
- golang-github-go-openapi-runtime
- golang-github-go-openapi-spec
- golang-github-go-openapi-strfmt
- golang-github-go-openapi-swag
- golang-github-go-openapi-validate
- golang-github-go-playground-assert-v2
- golang-github-go-playground-locales
- golang-github-go-playground-universal-translator
- golang-github-go-playground-validator-v10
- golang-github-go-test-deep
- golang-github-gofrs-uuid
- golang-github-golang-groupcache
- golang-github-golang-leveldb
- golang-github-google-cel-go
- golang-github-google-certificate-transparency
- golang-github-google-gnostic-models
- golang-github-google-go-cmp
- golang-github-google-go-github
- golang-github-google-go-intervals
- golang-github-google-uuid
- golang-github-gregjones-httpcache
- golang-github-grpc-ecosystem-go-grpc-middleware
- golang-github-grpc-ecosystem-go-grpc-prometheus
- golang-github-grpc-ecosystem-grpc-gateway
- golang-github-grpc-ecosystem-grpc-opentracing
- golang-github-hashicorp-golang-lru-v2
- golang-github-howeyc-gopass
- golang-github-ibm-sarama
- golang-github-imdario-mergo
- golang-github-invopop-yaml
- golang-github-jedisct1-go-minisign
- golang-github-jellydator-ttlcache
- golang-github-jinzhu-copier
- golang-github-jmhodges-clock
- golang-github-josharian-intern
- golang-github-klauspost-pgzip
- golang-github-konsorten-go-windows-terminal-sequences
- golang-github-kubernetes-cri-api
- golang-github-kubernetes-gengo
- golang-github-kylelemons-godebug
- golang-github-leodido-go-urn
- golang-github-mailru-easyjson
- golang-github-manifoldco-promptui
- golang-github-minio-sha256-simd
- golang-github-mitchellh-hashstructure
- golang-github-moby-docker-image-spec
- golang-github-moby-patternmatcher
- golang-github-moby-pubsub
- golang-github-moby-sys
- golang-github-mohae-deepcopy
- golang-github-montanaflynn-stats
- golang-github-munnerz-goautoneg
- golang-github-mxk-go-flowrate
- golang-github-nytimes-gziphandler
- golang-github-oklog-run
- golang-github-oklog-ulid
- golang-github-onsi-ginkgo-v2
- golang-github-op-go-logging
- golang-github-opencontainers-runtime-tools
- golang-github-openshift-imagebuilder
- golang-github-openzipkin-zipkin-go
- golang-github-ostreedev-ostree-go
- golang-github-otiai10-copy
- golang-github-perimeterx-marshmallow
- golang-github-peterbourgon-diskv
- golang-github-pkg-browser
- golang-github-pquerna-cachecontrol
- golang-github-pquerna-ffjson
- golang-github-proglottis-gpgme
- golang-github-rabbitmq-amqp091-go
- golang-github-rs-cors
- golang-github-rs-xid
- golang-github-sebdah-goldie
- golang-github-secure-systems-lab-go-securesystemslib
- golang-github-segmentio-ksuid
- golang-github-shibumi-go-pathspec
- golang-github-shopspring-decimal
- golang-github-sigstore-fulcio
- golang-github-sigstore-protobuf-specs
- golang-github-sigstore-sigstore
- golang-github-spiffe-go-spiffe
- golang-github-stoewer-go-strcase
- golang-github-sylabs-sif
- golang-github-thales-e-security-pool
- golang-github-thalesignite-crypto11
- golang-github-theupdateframework-go-tuf
- golang-github-transparency-dev-merkle
- golang-github-ugorji-go-codec
- golang-github-ulikunitz-xz
- golang-github-urfave-cli-v2
- golang-github-vbauerster-mpb
- golang-github-veraison-go-cose
- golang-github-vividcortex-ewma
- golang-github-weppos-publicsuffix-go
- golang-github-x448-float16
- golang-github-xdg-go-pbkdf2
- golang-github-xdg-go-scram
- golang-github-xdg-go-stringprep
- golang-github-xlab-treeprint
- golang-github-xrash-smetrics
- golang-github-zalando-go-keyring
- golang-github-zeebo-errs
- golang-github-zmap-rc2
- golang-github-zmap-zcrypto
- golang-github-zmap-zlint
- golang-go.opencensus
- golang-gogottrpc
- golang-golang-x-sync
- golang-golang-x-time
- golang-goleveldb
- golang-gomega
- golang-gomemcache
- golang-google-cloud
- golang-google-genproto
- golang-google-grpc
- golang-gopkg-natefinch-lumberjack.v2
- golang-gopkg-rethinkdb-rethinkdb-go.v6
- golang-k8s-api
- golang-k8s-apimachinery
- golang-k8s-apiserver
- golang-k8s-client-go
- golang-k8s-kube-openapi
- golang-k8s-sigs-json
- golang-k8s-sigs-release-utils
- golang-k8s-sigs-structured-merge-diff
- golang-k8s-utils
- golang-mongodb-mongo-driver
- golang-opentelemetry-contrib
- golang-opentelemetry-otel
- golang-opentelemetry-proto
- golang-sslmate-src-go-pkcs12
- golang-tags.cncf-container-device-interface
- golang-toml
- golang-webpki-org-jsoncanonicalizer
- in-toto-golang
- notary
- protobuild
- rekor
- relic
- rootlesskit
- runc
- trillian

</details> 

绝大多数为 golang-* 依赖。本次集成主要涉及容器相关。

可能较为重要的包 包括：

- containerd
- docker.io
- etcd-client
- etcd-server
- rootlesskit
- runc

### Package repository address | 软件包仓库地址

```
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/topics:/oci/testing/ ./
```

**Comment by Zeno-sole** [comment]
@kobe337  需要测一下x86 arm64 riscv64 loong64 docker.io的基础使用场景，参考之前提测的docker.io即可

**Comment by babyfengfjx** [comment]
@kobe337  请开展集成验证。

**Comment by kobe337** [comment]
【环境】：
镜像：Deepin OS-23-20240925022724-1_x86_64
Linux node1 6.6.52-amd64-desktop-hwe #23.01.00.38 SMP PREEMPT_DYNAMIC Tue Sep 24 17:30:32 CST 2024 x86_64 GNU/Linux

【结论】：
测试通过，暂无严重问题及影响, 安装校验，版本核对，基于x86、arm、loong与riscv架构，验证docker.io基本功能通过，验证本次提测预装包buildah、golang-github-containers-common与golang-github-containers-image通过，验证预装包关联包podman安装通过
x86:
![Image](https://github.com/user-attachments/assets/909d4e94-41c1-42ca-940a-7e114f43a214)
![Image](https://github.com/user-attachments/assets/3f631234-dc5f-437d-a4c2-ccc43d6ad3c8)
arm:
![Image](https://github.com/user-attachments/assets/fe8916fa-3d29-4afe-8c2f-57ffafa12a98)
loong:
![Image](https://github.com/user-attachments/assets/6ea71f2b-3de7-440d-82ae-abc75d1f6a5f)
riscv:
![Image](https://github.com/user-attachments/assets/904edcd6-1b7c-41ce-9760-729f310adc08)
预装关联包：
![Image](https://github.com/user-attachments/assets/561019d1-e192-43a9-8b1d-7ab12bfa17e8)
