### ISSUE TITLE
深度截图：增加填充工具

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#1074]
方便覆盖一些不想显示区域
![](https://www.simipic.com/images/2019/04/12/20190412105236c63c5bf5a7a27f74.jpg)

**Comment by justforlxz** [comment]
善用方块里的模糊

**Comment by sonichy** [comment]
> 善用方块里的模糊

模糊和覆盖能一样吗，模糊和马赛克都知道哪里有东西，同颜色覆盖就不知道那有东西了。

**Comment by justforlxz** [comment]
> > 善用方块里的模糊
> 
> 模糊和覆盖能一样吗，模糊和马赛克都知道哪里有东西，同颜色覆盖就不知道那有东西了。

你覆盖了，我不就知道那里有东西了么

**Comment by listenerri** [comment]
> > 善用方块里的模糊
> 
> 模糊和覆盖能一样吗，模糊和马赛克都知道哪里有东西，同颜色覆盖就不知道那有东西了。

同颜色覆盖倒是比较简单就能实现，但是有什么用呢？有多少图有多少区域是纯色的？

不是纯色的区域用了纯色去填充，这还没有马赛克看起来好看。

如果不使用纯色的话，也就要取区域样板然后填充，具体纹理也会有问题的。

我觉得这种需求就不是一个截图工具应该做的了。

**Comment by BLumia** [comment]
如果选项的功能是在绘制框选区域时直接绘制实心（而不是油漆桶那种先绘制再填充）的话，我觉得还行。油漆桶那种的话我觉得还是算了。

可以考虑 PR。

cc @wangjia12 。

**Comment by sonichy** [comment]
我就是实心绘制的意思，主要用于截图文章覆盖无关开场白。

**Comment by wangjia12** [comment]
截图暂时不会为了多种不同遮挡需求而做太多功能，目前支持简单的遮挡一下，如果要精确的遮挡最好还是用作图软件。
