### ISSUE TITLE
[BUG] dde-file-manager doesn't show new file/folder

### ISSUE THREAD

**Issue by RMoroni** [linuxdeepin/developer-center#1075]
## Describe the bug
When i create or paste a file to a folder the file-manager doesn't it, so i need to press "F5". 
Then dde-file-manager shows me the new file or paste.

## To Reproduce
Just open de dde-file-manager, create new folder or paste a file.

## Expected behavior
dde-file-manager won't show the new file/folder.

### Distro & Version
15.9.3 Desktop

### Related package version
dde-file-manager version 4.7.8.3-1

### Additional context
I'm using a Dell Inspirion 14, Intel i5 5200, Nvidia Geforce 920M.

**Comment by RMoroni** [comment]
at terminal i have this message: 2019-04-12, 16:49:51.102 [Warning] [                                                         0] QXcbConnection: XCB error: 152 (Unknown), sequence: 2305, resource id: 0, major code: 143 (Unknown), minor code: 2

**Comment by BLumia** [comment]
Did you open `vistual studio code` or `intellij idea` or other software which may take too many inotify watch handle? If you do, try close them or set `fs.inotify.max_user_watches` to a bigger value.

 - http://man7.org/linux/man-pages/man7/inotify.7.html
 - https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit
 - https://unix.stackexchange.com/questions/444998/how-to-set-and-understand-fs-notify-max-user-watches

**Comment by RMoroni** [comment]
Hi, thanks for your help...i changed the fs.inotify.max_user_watches from 8192 to 20000 and it works! 
Thanksssss!
