### ISSUE TITLE
Deepin DE and Gnome 3 conflict: double desktop icons bug

### ISSUE THREAD

**Issue by brofjst** [linuxdeepin/developer-center#1077]
## Describe the bug
I've just installed deepin on my arch linux system and i've found the following bug: [screenshot](https://i.ibb.co/8Y8tcXP/Deepin-Screenshot-20190413105000.png)
On the right you can see my deepin desktop icons, they are clickable and works perfectly.
On the left, you can see copies of them, they are generated automatically when i create a new desktop icon, but they appears just as images: i mean that they are not clickable nor selectable, they seems to be part of the wallpaper.
On my system are installed both gnome and deepin and atm i'm using lightdm as desktop manager but i've also installed gdm.
I've tried to use this command:

`gsettings set org.gnome.desktop.background show-desktop-icons false`

but it did not work.
After some researches trying to find the solution, i've realized that if i login into a gnome session and then i do the logout and start a new deepin session, the issue dissapears: on my desktop i find only the right desktop icons.
The bug reappears at reboot.
I find this problem on my desktop pc: on my laptop i've a system strongly similar (almost same applications installed, almost same settings, etc..) and on it the icons works perfectly, so i'm sure that gnome and deepin can coexist, but i do not understand what generates the conflict on my desktop PC.
An interesting fact is that the "image icons" on the left on deepin are exactly the icons showed on gnome: if you take a look at the pic, the icons on the left are all rapresented by a gear icon, except for deluge.
The icons with a gear are the ones that i've not marked as trusted yet on gnome while the deluge one is marked as trustable and infact the deluge's icon appears in both gnome and deepin.

## To Reproduce
i do not know how to reproduce it, because i do not know what generates the conflict between gnome and deepin DE.

### Distro & Version

Arch Linux

### Related package

.
I post all deepin and gnome packages installed, the issue should be somewhere here.
deepin-account-faces
deepin-anything
deepin-anything-arch
deepin-api
deepin-boot-maker
deepin-calculator
deepin-calendar
deepin-clone
deepin-clutter
deepin-cogl
deepin-community-wallpapers
deepin-control-center
deepin-daemon
deepin-desktop-base
deepin-desktop-schemas
deepin-dock
deepin-draw
deepin-editor
deepin-file-manager
deepin-gtk-theme
deepin-icon-theme
deepin-image-viewer
deepin-launcher
deepin-manual
deepin-menu
deepin-metacity
deepin-movie
deepin-music
deepin-mutter
deepin-network-utils
deepin-picker
deepin-polkit-agent
deepin-polkit-agent-ext-gnomekeyring
deepin-qt-dbus-factory
deepin-qt5dxcb-plugin
deepin-qt5integration
deepin-screen-recorder
deepin-screensaver
deepin-screensaver-pp
deepin-screenshot
deepin-session-ui
deepin-shortcut-viewer
deepin-sound-theme
deepin-system-monitor
deepin-terminal
deepin-turbo
deepin-voice-recorder
deepin-wallpapers
deepin-wm

gnome-autoar
gnome-backgrounds
gnome-bluetooth
gnome-boxes
gnome-calculator
gnome-calendar
gnome-characters
gnome-clocks
gnome-color-manager
gnome-control-center
gnome-desktop
gnome-dictionary
gnome-disk-utility
gnome-font-viewer
gnome-keyring
gnome-logs
gnome-maps
gnome-menus
gnome-nettool
gnome-online-accounts
gnome-online-miners
gnome-photos
gnome-remote-desktop
gnome-screenshot
gnome-session
gnome-settings-daemon
gnome-shell
gnome-shell-extension-add-on-desktop-git
gnome-shell-extension-appindicator-git
gnome-shell-extension-dash-to-panel
gnome-shell-extension-gsconnect
gnome-shell-extension-night-light-slider-git
gnome-shell-extension-topicons-plus
gnome-shell-extensions
gnome-terminal
gnome-themes-extra
gnome-todo
gnome-tweaks
gnome-user-share

**Comment by hualet** [comment]
Please run the attached python scripts to find if there's another desktop window running and what it is.

you may need to install python3-xlib and python3-ewmh first.

[get_desktop_window.py.zip](https://github.com/linuxdeepin/developer-center/files/3096697/get_desktop_window.py.zip)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
