### ISSUE TITLE
[Feature Request] Animated wallpaper support

### ISSUE THREAD

**Issue by gokhanyildirimlar** [linuxdeepin/developer-center#1079]
Animated wallpaper support is a step forward from ordinary wallpapers. This allows users to use a video file as a wallpaper. There is a tool named [Komorobi](https://github.com/cheesecakeufo/komorebi) to achieve this functionality, however, native support would make it easier to use by everyone. Additionally, this approach makes it more stable than using another tool. At least, I believe so. Deepin team is busy with movement to KWin and Debian Stable, right now but this feature can be taken into consideration for the future.

**Comment by nmatavka** [comment]
Who gives a fuck?

**Comment by BLumia** [comment]
I'm afraid there is no plan about support animated wallpaper for now. Consider use the 3rd-party app for this requirement, e.g. https://github.com/justforlxz/deepin-dreamscene .

**Comment by gokhanyildirimlar** [comment]
> I'm afraid there is no plan about support animated wallpaper for now. Consider use the 3rd-party app for this requirement, e.g. https://github.com/justforlxz/deepin-dreamscene .

Thanks for responding, @BLumia. There is no plan about this, so, you can close the issue if you will not add this into the plan in the future also.
