### ISSUE TITLE
Automatically forcing CD ejection if unmounting isn't working

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/developer-center#1081]
If a CD has read errors, the computer could fail to be able eject it by unmounting it or pressing the physical button itself. So the only way to get the disc out is reboot.

Meanwhile the computer performance could sensibly slow down, or even prever some applications like the file manager from launching. This can be permanent.

Instead, if after a timeout, the disc fails to eject, it should be forced. Aka the command "eject --force".

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
