### ISSUE TITLE
Deepin DE does not save desktop icon position

### ISSUE THREAD

**Issue by brofjst** [linuxdeepin/developer-center#1082]
## Describe the bug

If i move my icons on the desktop, at reboot they back to a default position imposed by the system.
It seems that deepin can't save permanently their position.

### Distro & Version

Arch Linux

**Comment by BLumia** [comment]
@justforlxz could you test it? thanks.

**Comment by keybreak** [comment]
@BLumia 
Yes this is super annoying.
Both for Arch and Manjaro Deepin stable sadly, since today.

**Comment by keybreak** [comment]
I'm damn sure it's because auto merge feature was pushed poorly tested.

If you auto-merge and then back in normal mode 0 it will not restore previous icons position (just like at reboot)

**Comment by BLumia** [comment]
Should already be fixed in https://github.com/linuxdeepin/dde-file-manager/commit/7f2acf0 , but there are no new tag currently (we got a bunch of bug fix for the merged desktop feature, will got a new tag maybe at tomorrow).

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
