### ISSUE TITLE
UOS AI 1.6.0集成请求

### ISSUE THREAD

**Issue by Clauszy** [linuxdeepin/developer-center#10822]
### package information | 软件包信息

包名 | 版本
-- | --
uos ai | 1.6.0
deepin-ai-daemon | 1.1.6
deepin-modelhub  |  0.0.19 
uos-ai-rag | 1.0.7 
dde-grand-search| 5.5.6

### Package repository address | 软件包仓库地址

deb  [trusted=yes] https://aptly.uniontech.com/pkg/beige-v2/release-candidate/44CQVU9TIEFJ44CR5LiK5p625ZWG5bqXMjAyNC0wNC0zMCAxMDoyODo1MA/  unstable main
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-2162:/dde/testing/ ./
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-2162:/commercial/testing/ ./

### changelog | 更新信息

UOS AI 1.6 与全局搜索新功能特性。

**Comment by babyfengfjx** [comment]
@luodeepin  请开展集成验证。

**Comment by luodeepin** [comment]
测试通过
1. 基础功能正常
2. 发散测试没有新增验证问题
