### ISSUE TITLE
Copying and moving files and folders with Drag and Drop

### ISSUE THREAD

**Issue by damian101** [linuxdeepin/developer-center#1083]
1. ~~Dragging and dropping files/folders on the same partition should cause the file to be moved and not copied. Copying of the file as the standard action should be only an option in the settings and not the default (and definitely not the only option as it is now).~~
EDIT: Dragging and dropping files/folders on the permanent shortcuts in the left pane always results in copying, regardless if origin- and destination-path are on the same partition or not.
2. Drag and Drop of files/folders on the "folder buttons" in the path bar is currently not possible but should be.

**Comment by keybreak** [comment]
1. I don't have it, at least on Manjaro Deepin files / folders are moved, not copied

More info on what drive it is. what file system it's formatted and what are permission on files/folders are, would be helpful for Deepin team to debug :smile:

**Comment by BLumia** [comment]
Also cannot reproduce under Deepin here. Any details?

**Comment by damian101** [comment]
@keybreak @BLumia
1. It is a more specific problem. Drag and Drop only always results in copying when you drag and drop files on the permanent shortcuts on the left pane in the file explorer.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
