### ISSUE TITLE
linux-firmware update

### ISSUE THREAD

**Issue by matrix-wsk** [linuxdeepin/developer-center#10831]
### package information | 软件包信息

linux-firmware|1.202.17

### Package repository address | 软件包仓库地址

https://aptly.uniontech.com/pkg/beige-v2/release-candidate/bGludXgtZmlybXdhcmUtdXBkYXRlMjAyNC0xMC0zMSAxMDo0Mzo0MQ/pool/main/l/linux-firmware/

### changelog | 更新信息

update base to 20240913.gita34e7a5f-0ubuntu2
reference:
git://git.launchpad.net/ubuntu/+source/linux-firmware
git@github.com](mailto:git@github.com):thesofproject/sof-bin.git

### test suggestion | 测试建议

1、新ultra设备反馈的音频固件加载问题
pms 275293 276981
2、已有设备12/13代设备覆盖，防止有降级问题。

**Comment by Zeno-sole** [comment]
该集成仅提供了x86架构， 缺少arm64 loong64 riscv64 架构软件包，驳回处理
