### ISSUE TITLE
全局搜索集成5.5.7

### ISSUE THREAD

**Issue by Clauszy** [linuxdeepin/developer-center#10843]
### package information | 软件包信息

deepin-ai-daemon | 1.1.7
dde-grand-search| 5.5.7

### Package repository address | 软件包仓库地址

deb  [trusted=yes] https://aptly.uniontech.com/pkg/beige-v2/release-candidate/44CQdjIz44CR44CQVU9TIEFJ44CR5omT5YyF5rWL6K-V5Li76aKYLeaOqOS7kzExMDEyMDI0LTExLTAxIDE1OjQ4OjAy/  unstable main
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-2176:/dde/testing/ ./

### changelog | 更新信息
优化 AI搜索默认开关状态逻辑
修复 打开全局搜索设置时，自动更新索引一直显示正在更新 的问题
_No response_

**Comment by luodeepin** [comment]
测试通过
1. 问题单回归通过
2. 开关状态符合需求
3. 发散测试没有新增严重问题
