### ISSUE TITLE
Qt-based deepin apps unusable on kde-wayland

### ISSUE THREAD

**Issue by cheese** [linuxdeepin/developer-center#1086]
## Describe the bug

Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1699621
```
all the deepin applications are basically unusable if on KDE-wayland.
all of the deepin apps when you start resizing them will become stuck resizing thus the resizing is never stopped even when you release the mouse or press escape

```
### Distro & Version

Fedora 30
### Related package version

Tested with deepin-editor 1.2.7.2

**Comment by BLumia** [comment]
assoc: https://github.com/linuxdeepin/developer-center/issues/641

Seems it is a issue of `qt5dxcb-plugin`. I can also reproduce it with lxqt and [qt5dxcb-plugin 1.1.24-1](https://packages.debian.org/buster/qt5dxcb-plugin) under debian, will test it with the current newest release later.

**Comment by cheese** [comment]
Just tested with qt5dxcb 1.2.0 but the issue does not change

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
