### ISSUE TITLE
更新在v23上com.hp.hplip因python兼容性及依赖引起的打印问题

### ISSUE THREAD

**Issue by yangkun0219** [linuxdeepin/developer-center#10865]
### package information | 软件包信息

com.hp.hplip | 3.23.5.2deepin2

### Package repository address | 软件包仓库地址

deb  [trusted=yes] https://aptly.uniontech.com/pkg/beige-v2/release-candidate/44CQ5omT5Y2w5LiT6aG544CRY29tLmhwLmhwbGlw6amx5Yqo5YyFcHl0aG9u5YW85a655oCn5pa55qGI5rWL6K-VMjAyNC0xMS0wOCAxMToxNzoxNQ/  unstable main

### changelog | 更新信息

1. 解决v23上com.hp.hplip包依赖未写全导致的打印问题。 https://bbs.deepin.org/post/280971
2. 解决在v23上因python环境不兼容导致的hp自带打印管理不能使用的问题

### test suggestion | 测试建议

1.运行com.hp.hplip自带的打印管理脚本hp-setup，hp-toolbox, hp-systray等，并添加该包支持的惠普厂商的usb直连的打印机或网络打印机，执行打印相关测试。

### Sphere of influence | 影响范围

v23上com.hp.hplip的打印相关

**Comment by babyfengfjx** [comment]
@luodeepin  请开展集成验证。

**Comment by luodeepin** [comment]
测试通过
1. 安装后通过hp-setup命令可以使用USB连接打印可正常打印
2. 打印管理器打印正常
