### ISSUE TITLE
dock preview closes fast

### ISSUE THREAD

**Issue by abijahm** [linuxdeepin/developer-center#1088]
the taskbar preview closes so fast that i cannot select a window

![deepin-screen-recorder_select area_20190214004757](https://user-images.githubusercontent.com/8830245/52746330-553a8380-2ff2-11e9-8102-9f3ee0007357.gif)

**Comment by listenerri** [comment]
This should be fixed by https://github.com/linuxdeepin/dde-dock/pull/178

**Comment by liuwen123** [comment]
已修复
