### ISSUE TITLE
dock keeps restarting at boot

### ISSUE THREAD

**Issue by brofjst** [linuxdeepin/developer-center#1090]
## Describe the bug

At system boot, the deepin dock keeps crashing and restarting for 5-10 times.
i've tried to disable network manager and start the system but it keeps to present the issue.
The problem is aleatory: sometimes it crashes just one time, sometimes it does not crash (rarely), but most of the time it crashes many times which is very annoying.
I've also tried to disable some applications to startup like redshift and kdeconnect but the issue persists.
I've also tried to uninstall wpa_supplicant (which is very buggy) because i read in another thread that seems a problem related to the wifi connection but it does not seem to be my case.

## To Reproduce

Boot the system.

## Expected behavior

The dock should start correctly without any crash.

## Screenshots

Can't do a screenshot, the dock keeps to appear and disappear constantly for 5-10 times at boot.

### Distro & Version

Arch Linux

### Related package version

wpa_supplicant 2:2.6-2
deepin-network-utils 0.1.3-1
glib-networking 2.60.1+2+g1ce6b40-1
networkmanager 1.16.0-1
networkmanager-qt 5.56.0-1
redshift 1.12-2
deepin-dock 4.9.6-1
gnome-desktop 1:3.32.1-1
deepin-desktop-base 2:2019.04.03-1
deepin-file-manager 1:4.8.0-1
deepin-daemon 3.25.2-1
deepin-api 3.18.3-1
startdde 3.14.3-1
deepin-network-utils 0.1.3-1

### Additional context

Is there any way to debug deepin environment? is there a smart way to check the workflow of deepin's components like the docker and find where the problems arises?
I post [here](https://pastebin.com/4BmtQLVQ) my journal, some interesting lines could be these:
`Apr 15 12:35:46 brofjst kernel: dde-dock[726]: segfault at 0 ip 00007f1a5494b5a7 sp 00007ffcaf266ea0 error 4 in libdde-network-utils.so.1.0.0[7f1a54940000+28000]
-- This usually indicates a programming error in the crashing program and
`

`Apr 15 12:36:03 brofjst dde-dock[892]: "dde-dock" can not find qm files
`

`Apr 15 14:47:19 brofjst startdde[557]: session_process.go:91: Wait command /usr/bin/dde-dock [] failed: signal: aborted (core dumped)
`

**Comment by BLumia** [comment]
Seems already fixed, did you still have this issue now?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
