### ISSUE TITLE
Install on Arch Linux fails

### ISSUE THREAD

**Issue by seniordevel** [linuxdeepin/developer-center#10907]
### SUMMARY | 问题概要

Seems to be an issue with build of gnethogs.
Building gnethogs separately fails for the same reason.
Building Deepin-system-monitor github version fails for other reason.

`Makefile.am: installing './INSTALL'
Makefile.am: installing './COPYING' using GNU General Public License v3 file
Makefile.am:     Consider adding the COPYING file to the version control system
Makefile.am:     for your code, to avoid questions about which license your project uses
src/Makefile.am: installing './depcomp'
Setting up intltool
Now run ./configure, make, and make install.
checking for a BSD-compatible install... /usr/bin/install -c
checking whether sleep supports fractional seconds... yes
checking filesystem timestamp resolution... 0.01
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking xargs -n works... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking whether make supports the include directive... yes (GNU style)
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for glib-compile-resources... /usr/bin/glib-compile-resources
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for gtkmm-3.0 ... yes
checking for pthread_attr_init in -lpthread... yes
checking for nethogsmonitor_loop in -lnethogs... no
Error! You need to have libnethogs-dev installed.
==> ERROR: A failure occurred in build().
    Aborting...`

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
Deepin-system-monitor version  6.0.16-4
Official repostory-extra

Operating System: Manjaro Linux 
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.8.0
Qt Version: 6.7.2
Kernel Version: 6.10.13-3-MANJARO (64-bit)
Graphics Platform: X11
Processors: 4 × AMD A10-7870K Radeon R7, 12 Compute Cores 4C+8G
Memory: 14,6 GiB of RAM
Graphics Processor: KAVERI
```

### STEPS TO REPRODUCE | 复现步骤

...

### OBSERVED RESULT | 观察到的结果

...

### EXPECTED RESULT | 期望的结果

...

**Comment by BLumia** [comment]
> `Deepin-system-monitor version  6.0.16-4`

This is way too outdated, we would suggest upgrading to a newer version. If you still would like to build that specific version, it will then require some code changes (patches) to get it working. For example, you might need to add `dtklog` as dependencies and maybe needs to replace `deepin-dock` dependency to `deepin-shell`.

> `Error! You need to have libnethogs-dev installed.`

If you are trying to use the PKGBUILD, use `pacman -si`, ensure it install all the dependencies that was required for the specific revision.

I don't think `libnethogs-dev` is needed for `deepin-system-monitor`, maybe you are confused with some other package?

By the way, please fill the `STEPS TO REPRODUCE` field when you open another issue.
