### ISSUE TITLE
AI 画板演示版本集成测试

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#10901]
### package information | 软件包信息

包名 | 版本
-- | --
cn.photosir.flashpaint |   1.0.4.41111

### Package repository address | 软件包仓库地址

https://cdn.photosir.cn/package/flashpaint/deepin/cn.photosir.flashpaint_1.0.4.41111-amd64.deb

### test suggestion | 测试建议

下载deb手动安装
重点测试：草图+提示词生成图片的内容，保证 AI 生图的流程性。

**Comment by babyfengfjx** [comment]
@luodeepin  请开展系统验证，此应用作为AI生态大会演示应用，保持与其他AI应用同样的质量要求，验收结论直接在issue上处理即可。
对应测试用例请参考：https://vjxs22vadq.feishu.cn/sheets/J87EshmfehxM84tVZQKcpyfRnbc?from=from_copylink

**Comment by luodeepin** [comment]
测试不通过
1. 新增2个严重问题，1个一般问题
