### ISSUE TITLE
kde环境下无法使用剪切板功能

### ISSUE THREAD

**Issue by Wangrong23** [linuxdeepin/developer-center#1091]
manjaro系统,深度取色器也有这个问题

**Comment by BLumia** [comment]
等有时间看看，最近事情有点多抱歉。

如果任何人有兴趣跟进这个 bug 或者是提交 patch 的话也欢迎帮忙 :joy:

**Comment by Core00077** [comment]
感谢reopen。我会尽可能提供所需要的信息。
以下是使用原生截图下截图可以被复制到剪贴板的效果与深度截图后剪贴板的效果
这是kde自带截图spetacle，会显示图片内容：
![这是kde自带截图spetacle](https://user-images.githubusercontent.com/28624864/56178689-b5bb6080-6035-11e9-9491-35c3aedae852.png)
这是深度截图后剪贴板的内容，空，但是有一串字符串`0x0x0 %4`（就是那一行空白的部分）
![深度截图](https://user-images.githubusercontent.com/28624864/56178742-e56a6880-6035-11e9-92b0-a6b7ddd3ccdd.png)

**Comment by iceqing** [comment]
这个问题还有人跟进么？manjaro kde环境依然不生效

**Comment by Core00077** [comment]
> 这个问题还有人跟进么？manjaro kde环境依然不生效

据我所知，似乎木有，推荐flameshot，目前我在linux下使用的最爽的截屏软件没有之一。
https://coreja.com/DailyHack/2019/04/Linux%E6%88%AA%E5%B1%8F%E7%A5%9E%E5%99%A8%E2%80%94%E2%80%94Flameshot/

**Comment by BLumia** [comment]
暂时没进度 :joy:

**Comment by iceqing** [comment]
@Core00077 问题已解决了。

需要依赖 gnome-settings-daemon，否则复制到剪切板可能会出现问题。
```
sudo pacman -S gnome-settings-daemon
``

**Comment by BLumia** [comment]
任何剪切板管理工具应该都可以(比如 deepin/DDE 上就不需要 `gnome-settings-daemon`)，看上去不是深度截图的问题，那就先关掉了。感谢反馈 :)

**Comment by glide-the** [comment]
https://github.com/linuxdeepin/developer-center/issues/1091#issuecomment-535765751 通过安装gnome-settings-daemon包依然没有解决，剪切板的问题，这个bug在kde的桌面上，目前为止都是时好时坏，
gnome-settings-daemon安装后需要配置一些设置吗？

**Comment by m4rsquake** [comment]
目前arch plasma 6, spectale 仍然有此问题，怀疑根源在wayland 或粘贴板。因为许多截图工具都有类似问题。

**Comment by BLumia** [comment]
只是顺带说一下，历史讨论是针对深度截图/录屏在 KDE 下的表现的。KDE wayland 下 Spectale 应该是能用的，如果不能用可能需要检查下版本，但这里不会跟进 KDE 应用自身的问题。
