### ISSUE TITLE
[Deepin Integration] Auto integrate from topic: treeland by @zeno to V25 by deepin-ci-robot

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#10947]
### Package repository address | 软件包仓库地址

    deb [trusted=yes] https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main community commercial

**Comment by Zeno-sole** [comment]
**Integration Test Info**
### Test suggestion | 测试建议



### Influence | 影响范围





### ADDITIONAL INFORMATION | 额外补充

**Comment by babyfengfjx** [comment]
@baicailio  请先弄清楚该笔集成所涉及的内容，再开展集成验证。

**Comment by baicailio** [comment]
专业版和社区版treeland0.5.1的bug验证通过

集成验证通过
