### ISSUE TITLE
Ad/remove Categories and edit menu category for an application

### ISSUE THREAD

**Issue by jerome-diver** [linuxdeepin/developer-center#1094]
Add/remove menu Categories
And edit menu.
I kow i can change menu category from applications.desktop fies (then add them to .local/share/applications for not loose them from next update)
But first it is not easy to do for many application, and then i didn't find how to just add/remove Categories.
Maybe i can try to find time to make a little application with Qt5 GUi (i see in your source code you use Qt5 with python code... correct ?) if i can know where the category menu is coming from and what is the convention for read a menu file (who should be a xml file maybe ?) ?

**Comment by BLumia** [comment]
`deepin-menu` is not for that purpose, so transfer this issue to developer-center now.

Currently no plan about creating an new menu management application project, but you can use `menulibre` as alternative which allow you edit the `.desktop` files with a fancy GUI.

But there are still some problem here, the current dde-launcher implementation does not fully followed the [Desktop Menu Spec](https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html) (no `$XDG_MENU_PREFIX`, no `applications.menu` file under `$XDG_CONFIG_DIRS/menus/`, etc), and we should probably consider support it first (cc @electricface @hualet @justforlxz ).

**Comment by jerome-diver** [comment]
@BLumia ok, well understand, thank you.
Then, how to add a Category to the menu ? what is the way to go with that if i want to create a little GUI with pyQt ? (not about pyQt, but about how to implement a new menu Category or edit one ? how the menu is constructed ?)

**Comment by BLumia** [comment]
> Then, how to add a Category to the menu ?

We need support *Desktop Menu Spec* first, the current implementation doesn't allowed to do that.

> how to implement a new menu Category or edit one ? how the menu is constructed ?

The current implementation only take care of the `.desktop` files (you may want to look at the `Categories` key), see [Desktop Entry Specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-1.1.html) for more details. And you can also take a look at [PyXDG](https://pyxdg.readthedocs.io/en/latest/menu.html) and [qtxdg](https://github.com/lxqt/libqtxdg) which can be very handy to use if you decided to create a new menu editing software.

Although we currently doesn't followed the *Desktop Menu Spec*, it's still recommended to make your implementation support that spec, so your tool can be still useful under all desktop environments which followed the spec.

**Comment by nodefive** [comment]
Indeed I got the code and all the cats are **pretty hard-coded**. It would be so much simpler (and clever) if one implemented a launcher that reads a config file in /etc and set the user menu accordingly. If on full screen with just the categories being added, if on Dozer-like mode with options such as categories, what to display, if is to display history (as it does in a horrendous way) or pinned apps, display or not shutdown,reboot,logoff buttons and the behavior of them. I mean, the aim is to be better right? Making this would make the Launcher far better.

**Comment by jerome-diver** [comment]
@nodelive yes, true. But it seems that deepin-menu dev doesn't want that deepin-menu become very useful and user-friendly, it sseems that the idea is to be a kind of demo menu application instead of a real nice menu application. Why ? because they refuse user's ideas to grow up the application.

As @BLumia said: "you can use menulibre..." and go to the church to light on a candle and priest God for devs want to grow up this menu one day (maybe).
Or no more use Deepin.

**Comment by nodefive** [comment]
I don't need to light candles, **God is ALWAYS with me.** But the Deepin Launcher is not His concern about me, that's for sure.

About the menu, yeah, maybe I'll try to recompile the launcher with my own hard-coded categories, that would solve my problem, but only my own. Everybody else: **Other**

**Comment by BLumia** [comment]
> About the menu, Menulibre **won't** solve any problems here as the Launcher does not support the "Desktop Menu Specification", so 0 (zero) solutions here. Maybe I'll try to recompile the launcher with my own hard-coded categories,
> 
> That will solve my problem, but only my own... for everybody else: **Other**

Seems currently dde-launcher team still doesn't have any plan about supporting the desktop-menu-spec (ps. I don't maintain the dde-launcher project), so actually I recommend you create a fork and share it to others if you like.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.

**Comment by jerome-diver** [comment]
@justforlxz please, explain why you choose to close this issue. Is it resolved ?

**Comment by justforlxz** [comment]
this issue will be recorded as a new feature. But this feature may not provide.
