### ISSUE TITLE
[Deepin Integration]~[25] add dde-print  by Zeno-sole

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#10956]
### Package information | 软件包信息

包名 | 版本
--  | --
dde-printer | [None](https://github.com/linuxdeepin/dde-printer/commit/upstream/master)

### Package repository address | 软件包仓库地址

    deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-2192:/commercial/testing/ ./

**Comment by Zeno-sole** [comment]
**Integration Test Info**
### Test suggestion | 测试建议

关联 https://cooperation.uniontech.com/app/1c4062ac-cc50-4f6c-9d7d-52906b78a291/660a4df2cf2f26268845b6b6/660a4df2cf2f26268845b6b9/row/ba6f05f7-5036-4062-ba64-c14b81faa12b


### Influence | 影响范围

打印管理器

### ADDITIONAL INFORMATION | 额外补充

**Comment by babyfengfjx** [comment]
@luodeepin  请开展集成验证。

**Comment by luodeepin** [comment]
无法安装驱动当前环境阻塞，待可以安装驱动后再进行测试
