### ISSUE TITLE
1、手动待机出现损坏磁盘系统 2、紧急模式不能重启

### ISSUE THREAD

**Issue by jay763190097** [linuxdeepin/developer-center#1096]
昨天晚上打开了一个Idea和两个浏览器，内存占用60%左右吧。

锁屏，5分钟过后，发现电脑仍亮屏，于是手动待机。

今天早上，启不动，You are in emergence mode..............
Ctrl+D 没用仍然回到这个地方。
输入root密码，重启。

还好不是特别小白，所以进入紧急模式，fsck 修复。。
可恶，修复之后不能退出，这个是bug 

强制关机重启仍然和之前一样

于是进入recovery系统
进入命令行
umount /dev/sda9        卸载出现文件系统问题的磁盘
fsck /dev/sda9

看到提示 按 y
修复完毕后重启系统，就可以了。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
