### ISSUE TITLE
UOS AI 1.6.1集成请求

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#10961]
### package information | 软件包信息

包名 | 版本
-- | --
uos ai | 1.6.1
deepin-ai-daemon | 1.1.16

### Package repository address | 软件包仓库地址

deb  [trusted=yes] https://ci.deepin.com/repo/deepin/deepin-community/testing/  unstable/25 main community commercial

### test suggestion | 测试建议

同步 https://cooperation.uniontech.com/app/1c4062ac-cc50-4f6c-9d7d-52906b78a291/660a4df2cf2f26268845b6b6/660a4df2cf2f26268845b6b8/row/419a284b-5192-4d4a-b1e2-2faa0fca1f6f

**Comment by Zeno-sole** [comment]
https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20241126/deepin-25-beige-immutable-amd64-20241126-230944.iso

**Comment by babyfengfjx** [comment]
@luodeepin  请开展集成验证。

**Comment by luodeepin** [comment]
测试不通过
1. 问题单回归失败
2. 新增严重问题

对应问题单为：
https://pms.uniontech.com/bug-view-287343.html
https://pms.uniontech.com/bug-view-290087.html
