### ISSUE TITLE
UOS AI 2.0 商店上架集成

### ISSUE THREAD

**Issue by Clauszy** [linuxdeepin/developer-center#10978]
### package information | 软件包信息

包名 | 版本
-- | --
uos-ai |2.0.0   
deepin-ai-daemon  | 1.1.18  
deepin-systemassistant-knowledge  | 0.0.15

### Package repository address | 软件包仓库地址

deb  [trusted=yes] https://aptly.uniontech.com/pkg/beige/release-candidate/44CQVjIz44CRVU9TIEFJ5LiK5ZWG5bqXMjAyNC0xMS0yOCAxNzowNzoxNA/  unstable main

### test suggestion | 测试建议

1、【新功能】智能体商店上架，支持第三方智能体；
2、AI随航：新增文本纠错功能，帮你快速发现文案错误；
3、AI随航：新增支持对原文双击复制；
4、AI随航：优化了划词后随航工具栏出现的时机，减少误触和打扰；
5、AI写作：已生成内容新增了原提示词；
6、AI写作：优化了提示词模版的修改和切换交互；
7、其他：界面样式和操作体验优化。
8、更新logo

**Comment by babyfengfjx** [comment]
@luodeepin  请开展集成验证。
