### ISSUE TITLE
更新v23上com.hp.hplip的版本

### ISSUE THREAD

**Issue by yangkun0219** [linuxdeepin/developer-center#10976]
### package information | 软件包信息

com.hp.hplip | 3.24.7.2deepin0

### Package repository address | 软件包仓库地址

deb  [trusted=yes] https://aptly.uniontech.com/pkg/nonfree-beige-v2/release-candidate/44CQ5omT5Y2w5LiT6aG544CRY29tLmhwLmhwbGlw6amx5Yqo5YyFcHl0aG9u5YW85a655oCn5pa55qGI5rWL6K-VMjAyNC0xMS0wOCAxMToxNzoxNQ/  unstable non-free

### changelog | 更新信息

继承解决#10865的问题，因com.hp.hplip更新了原生版本覆盖了解决问题的版本导致问题复现，所以从最新的原生版本更新了deepin的版本.

### test suggestion | 测试建议

1.运行com.hp.hplip自带的打印管理脚本hp-setup，hp-toolbox, hp-systray等，并添加该包支持的惠普厂商的usb直连的打印机或网络打印机，执行打印相关测试。

### Sphere of influence | 影响范围

v23上com.hp.hplip的打印相关

**Comment by babyfengfjx** [comment]
@luodeepin  请开展集成验证。

**Comment by luodeepin** [comment]
测试通过
1. 手动安装成功
2. 使用hp-setup，hp-toolbox命令可以正常打印
