### ISSUE TITLE
[abrt] deepin-control-center: QXcbScreen::screen(): dde-control-center killed by SIGSEGV

### ISSUE THREAD

**Issue by cheese** [linuxdeepin/developer-center#1098]
## Describe the bug

https://bugzilla.redhat.com/show_bug.cgi?id=1701436
Version-Release number of selected component:
deepin-control-center-4.9.4-1.fc30

Additional info:
reporter:       libreport-2.10.0
backtrace_rating: 4
cmdline:        /usr/bin/dde-control-center
crash_function: QXcbScreen::screen
executable:     /usr/bin/dde-control-center
journald_cursor: s=69b78e2b054e40608a2cda63628178ea;i=b8705b;b=568c0fcb164c456e92be11543e1cb26b;m=13637e1fa6;t=586cb8156ae82;x=696c10be85d4e1c1
kernel:         5.0.7-300.fc30.x86_64
rootdir:        /
runlevel:       N 5
type:           CCpp
uid:            1000
```
Truncated backtrace:
Thread no. 1 (10 frames)
 #0 QXcbScreen::screen at /usr/include/qt5/QtXcb/qxcbconnection_basic.h:70
 #1 QXcbScreen::root at /usr/include/qt5/QtXcb/qxcbscreen.h:178
 #2 deepin_platform_plugin::DForeignPlatformWindow::handleConfigureNotifyEvent at dforeignplatformwindow_x11.cpp:114
 #3 QXcbConnection::handleXcbEvent at qxcbconnection.cpp:596
 #4 QXcbConnection::processXcbEvents at qxcbconnection.cpp:1028
 #5 xcbSourceDispatch at qxcbeventdispatcher.cpp:103
 #9 g_main_context_iteration at ../glib/gmain.c:3988
 #10 QEventDispatcherGlib::processEvents at kernel/qeventdispatcher_glib.cpp:422
 #11 QEventLoop::exec at ../../include/QtCore/../../src/corelib/global/qflags.h:140
 #12 QCoreApplication::exec at ../../include/QtCore/../../src/corelib/global/qflags.h:120
```
### Distro & Version

Fedora 30
### Related package version

deepin-control-center-4.9.4-1.fc30

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
