### ISSUE TITLE
[Deepin Integration] v23~20241203 内测更新关键模块集成清单

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#10994]
### Package information | 集成信息
https://github.com/linuxdeepin/developer-center/issues/10986
[#10980](https://github.com/linuxdeepin/developer-center/issues/10980)
[#10904](https://github.com/linuxdeepin/developer-center/issues/10904)
[#10935](https://github.com/linuxdeepin/developer-center/issues/10935)
[#10883](https://github.com/linuxdeepin/developer-center/issues/10883)
[#10934](https://github.com/linuxdeepin/developer-center/issues/10934)
[#10983](https://github.com/linuxdeepin/developer-center/issues/10983)
[#10874](https://github.com/linuxdeepin/developer-center/issues/10874)
[#10880](https://github.com/linuxdeepin/developer-center/issues/10880)
[#10965](https://github.com/linuxdeepin/developer-center/issues/10965)
[#10957](https://github.com/linuxdeepin/developer-center/issues/10957)
[#10924](https://github.com/linuxdeepin/developer-center/issues/10924)
[#10944](https://github.com/linuxdeepin/developer-center/issues/10944)
[#10882](https://github.com/linuxdeepin/developer-center/issues/10882)
[#10895](https://github.com/linuxdeepin/developer-center/issues/10895)
[#10903](https://github.com/linuxdeepin/developer-center/issues/10903)
[#10915](https://github.com/linuxdeepin/developer-center/issues/10915)
[#10951](https://github.com/linuxdeepin/developer-center/issues/10951)
[#10971](https://github.com/linuxdeepin/developer-center/issues/10971)
[#10914](https://github.com/linuxdeepin/developer-center/issues/10914)
[#10968](https://github.com/linuxdeepin/developer-center/issues/10968)
[#10976](https://github.com/linuxdeepin/developer-center/issues/10976)
[#10955](https://github.com/linuxdeepin/developer-center/issues/10955)
[#10928](https://github.com/linuxdeepin/developer-center/issues/10928)
https://github.com/linuxdeepin/developer-center/issues/10889
20241217
https://github.com/linuxdeepin/developer-center/issues/11052
https://github.com/linuxdeepin/developer-center/issues/11051
https://github.com/linuxdeepin/developer-center/issues/11064
https://github.com/linuxdeepin/developer-center/issues/11064
https://github.com/linuxdeepin/developer-center/issues/11065
https://github.com/linuxdeepin/developer-center/issues/11058
[#11036](https://github.com/linuxdeepin/developer-center/issues/11036)
https://github.com/linuxdeepin/developer-center/issues/11070

### Package repository address | 软件包仓库地址

    deb [trusted=yes] https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main community commercial

**Comment by babyfengfjx** [comment]
| 集成ID | 验证责任人  |
| ------ | ------ |
| #10986 | 许琪   |
| #10983 | 吴波   |
| #10980 | 吴波   |
| #10976 | 罗鑫思 |
| #10971 |        |
| #10968 | 吴波   |
| #10965 | 吴波   |
| #10957 | 许琪   |
| #10955 | 许琪   |
| #10951 | 吴波   |
| #10944 | 吴波   |
| #10935 | 许琪   |
| #10934 | 许琪   |
| #10928 | 李晓飞 |
| #10924 | 罗鑫思 |
| #10915 | 吴波   |
| #10914 | 陈姣   |
| #10904 | 李晓飞 |
| #10903 | 吴波   |
| #10895 | 吴波   |
| #10889 | 许琪   |
| #10883 | 许琪   |
| #10882 | 吴波   |
| #10880 | 吴波   |
| #10874 | 许琪   |

**Comment by babyfengfjx** [comment]
计划本周五推送内测，上述集成为本次计划推送的相关内容，请大家准备外网环境，打开内测通道，并添加上述仓库（内网仓库），完成升级、升级后功能、场景发散验证，每个人均需备注最后的验证结论，如果发现新的问题，需要备注说明，经过评审后再做是否推送的决策。

**Comment by xuqi27837288** [comment]
291913
291949
291911

**Comment by luodeepin** [comment]
新增：
https://pms.uniontech.com/bug-view-292211.html

**Comment by babyfengfjx** [comment]
| Bug编号                                                  | BUG描述                                                      | 问题单级别 | Bug创建者 |
| -------------------------------------------------------- | ------------------------------------------------------------ | ---------- | --------- |
| [292197](https://pms.uniontech.com/bug-view-292197.html) | 将微信驻留到任务栏上，打开微信后关闭聊天窗口，点击驻留的微信图标无法打开微信 | 一般       | 罗鑫思    |
|[292021](https://pms.uniontech.com/bug-view-292021.html) |~~未执行数据迁移命令，从玲珑1.7.0升级到1.7.1，玲珑应用不可用~~ | 严重       | 陈姣      |
| [291949](https://pms.uniontech.com/bug-view-291949.html) | 1129内测环境,窗口最大化时删除看图应用程序中最后一张图片后,窗口位置发生变化,未保持最大化 | 一般       | 许琪      |
| [292351](https://pms.uniontech.com/bug-view-292351.html) | 1129内测环境,任务栏设置为智能隐藏时,桌面无窗口展示时,任务栏仍然隐藏无法展示 | 严重       | 许琪      |
| [291913](https://pms.uniontech.com/bug-view-291913.html) | 1129内测环境,任务栏设置为隐藏时,将任务栏位置调整为左侧时,桌面图标未从第一列开始展示 | 严重       | 许琪      |
| [291911](https://pms.uniontech.com/bug-view-291911.html) | 1129内测环境,任务栏设置为隐藏时,鼠标移动至任务栏边缘时,任务栏不停被唤起 | 一般       | 许琪      |
| [292211](https://pms.uniontech.com/bug-view-292211.html) | 1129内测环境,打开终端设置，使用鼠标滚轮下滑时，左侧列表出现很多横线 | 一般      | 罗鑫思      |
| [292229](https://pms.uniontech.com/bug-view-292229.html) | 1129内测环境,在设置中开启普通删除提示，删除任意文件后，删除提示框的回收站图标与任务栏上的图标显示不一致 | 一般      | 罗鑫思      |
| [286533](https://pms.uniontech.com/bug-view-286533.html) | 更新到Qt6.8后，切换默认程序中的菜单时，选项边缘有残线 | 一般      | 罗鑫思      |
| [286409](https://pms.uniontech.com/bug-view-286409.html) | ~~更新到Qt6.8后，打开启动器，将鼠标移动到启动器中的任意应用上时，没有出现hover效果~~ | 一般      | 罗鑫思      |
| [286289](https://pms.uniontech.com/bug-view-286289.html) | 更新到Qt6.8后，鼠标逐个遍历hover到任务栏应用图标上，查看tips提示时，tips提示框会先消失一半再变长后再消失一半 | 一般      | 罗鑫思      |
| [285321](https://pms.uniontech.com/bug-view-285321.html) | 桌面多次点击右键菜单时,弹出的对话框样式展示出现不一致 | 严重       | 许琪      |
| [289531](https://pms.uniontech.com/bug-view-289531.html) | ~~拖动不透明度调节按钮时会出现系统卡顿~~ | 一般       | 许琪      |
| [292265](https://pms.uniontech.com/bug-view-292265.html) | 1129内测环境,多点击任务栏插件图标时,弹出的对话框列表样式展示混乱 | 严重       | 许琪      |
| [292345](https://pms.uniontech.com/bug-view-292345.html) | 1129内测环境,onboard图标在浅色模式下图标样式展示不正确,展示为白色 | 一般       | 许琪      |
| [290649](https://pms.uniontech.com/bug-view-290649.html) | 屏幕键盘右键菜单中菜单命令未国际化,展示为英文 | 一般       | 许琪      |
| [292247](https://pms.uniontech.com/bug-view-292247.html) | ~~登录企业微信和微信，在托盘和插件区域的任意图标上，点击鼠标左键再点右键再点左键时，整个桌面环境崩溃~~| 严重       | 罗鑫思      |
|[292361](https://pms.uniontech.com/bug-view-292361.html)|~~执行./*.uab --extract 不带目录参数，应用直接运行，不提醒缺少参数~~|一般|李晓飞|
|[292365](https://pms.uniontech.com/bug-view-292365.html)|~~执行./*.uab --extract abc ,解压的uab文件目录为空~~|一般|李晓飞|
|[292369](https://pms.uniontech.com/bug-view-292369.html)|~~执行./*.uab 安装uab文件后，启动器没有应用图标~~|一般|李晓飞|
|[292367](https://pms.uniontech.com/bug-view-292367.html)|~~登录企业微信和微信，开启录屏后，在托盘和插件区域的任意图标上，点击鼠标左键再点右键再点左键时，托盘和插件没了~~|严重|罗鑫思|
|[292371](https://pms.uniontech.com/bug-view-292371.html)|~~登录企业微信和微信，开启录屏后，多次快速点击托盘中的图标，dde-shell崩溃堆栈报错~~|严重|罗鑫思|
|[290533](https://pms.uniontech.com/bug-view-290533.html)|~~同时点击安装多个玲珑应用，应用一直转圈或者部分应用提示安装失败~~|严重|李晓飞|
|[292427](https://pms.uniontech.com/bug-view-292427.html)|应用商店下载玲珑应用没有进度显示，转圈加载后直接显示安装成功|严重|李晓飞|

**Comment by baicailio** [comment]
| Bug编号                                                  | BUG描述                                                      | 问题单级别 | Bug创建者 |
| -------------------------------------------------------- | ------------------------------------------------------------ | ---------- | --------- |
|[296111](https://pms.uniontech.com/bug-view-296111.html)| 【deepin V23】【集成测试】【玲珑】商店下载玲珑应用，暂停后再恢复下载，会下载失败 | 一般       | 陈姣    |
|[296103](https://pms.uniontech.com/bug-view-296103.html)| ~~【deepin V23】【集成测试】【DDE】切换到主题square，鼠标hover到右键菜单，窗口右键菜单没有与主题的活动色保持一致~~ | 一般       | 陈姣    |
|[296145](https://pms.uniontech.com/bug-view-296145.html)| 1129内测环境,控制中心-用户-未保存上传的自定义图片时，用户头像已经被修改| 一般       | 李晓飞 |
|[296169](https://pms.uniontech.com/bug-view-296169.html)| 1129内测环境,命令安装应用，桌面没有应用图标显示，命令卸载应用在桌面有图标残留| 一般       | 李晓飞 |
|[296267](https://pms.uniontech.com/bug-view-296267.html)|【deepin V23】【发散测试】【DDE】【控制中心】1129内测环境,修改主题样式后,鼠标移动至桌面时,鼠标样式未修改未跟随变化| 严重      |许琪    |
|[296177](https://pms.uniontech.com/bug-view-296177.html)|  【deepin V23】【发散测试】【DDE】1129内测环境,自定义图片中只有一张图片时,不展示可删除的按钮及进行删除操作| 一般      |许琪    |
|[296153](https://pms.uniontech.com/bug-view-296153.html)|  【deepin V23】【集成测试】【DDE】1129内测环境,切换分类类别及在按分类和按名称中进行首字母索引操作后,启动器出现闪退崩溃| 一般      |许琪    |
|[295977](https://pms.uniontech.com/bug-view-295977.html)|  【deepin V23】【集成测试】【DDE】1129内测环境,缩放2.0及以上时,调整任务栏高度后,应用程序图标会堆叠在一起展示| 一般      |许琪    |
|[295975](https://pms.uniontech.com/bug-view-295975.html)|  【deepin V23】【集成测试】【DDE】1129内测环境,缩放1.75倍及以上时,在任务栏图标或插件面板点击鼠标右键时,鼠标样式变大展示| 一般      |许琪    |

**Comment by baicailio** [comment]
当前无新引入的严重问题，上述bug清单中已加删除线的为已经修复并验证通过的bug，其余遗留的bug后续继续优化
本次集成验证通过
