### ISSUE TITLE
Clipboard support for greenclip

### ISSUE THREAD

**Issue by haldai** [linuxdeepin/developer-center#1099]
`deepin-screenshot` is the best scrot program I've used under Linux. The "save to clipboard" function is extremely convenient when I was using [xfce4-clipman-plugin](https://www.archlinux.org/packages/extra/x86_64/xfce4-clipman-plugin/) .

However, recently I have changed my clipboard manager to [greenclip](https://github.com/erebe/greenclip), which is a more modern and popular, and the "save to clipboard" function of `deepin-screenshot` cannot be used.

Would it be possible for you to add the support for `greenclip`? Thanks!

**Comment by BLumia** [comment]
Not sure but maybe you can take a look at the [FAQ](https://github.com/erebe/greenclip#faq) and see if it's by design?

> Q. I cannot paste images !
>
> A. You can only keep in your history small images (~ <500 kb). I disabled the support for bigger images as it will turn your CPU into a heater for winter.

**Comment by lolimay** [comment]
Why not have a try of CopyQ? It's really powerful and full-configurated.

**Comment by haldai** [comment]
> Why not have a try of **CopyQ**? It's really powerful and full-configurated. Hope you like it!

CopyQ cannot make direct change with scrot images, so I have switched to [flameshot](https://github.com/lupoDharkael/flameshot) now.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
