### ISSUE TITLE
[archlinux]dde-dock显示问题和电量显示问题

### ISSUE THREAD

**Issue by kirigayakazushin** [linuxdeepin/developer-center#110]
可以很清楚的看到两个问题，电量问题和三角的位置不对。

![20160801200241](https://cloud.githubusercontent.com/assets/12298476/17293481/222c0afc-57b6-11e6-9776-fc9eeb040878.png)
![20160801200302](https://cloud.githubusercontent.com/assets/12298476/17293482/225a3a9e-57b6-11e6-994e-0dcfb0c45de3.png)
![20160801200319](https://cloud.githubusercontent.com/assets/12298476/17293483/228341a0-57b6-11e6-8594-996bdd784384.png)

**Comment by sbwtw** [comment]
内部已经修复

**Comment by funilrys** [comment]
Is it fixed on arch too ?

**Comment by oberon2007** [comment]
I'm not sure which pkgrel we are talking about, but the problem persists with arch package **deepi-dock 3.0.11**

**Comment by funilrys** [comment]
Since this afternoon I don't have this issue anymore in arch (I'm gonna confirm it tomorrow i'm away from my computer)

**Comment by funilrys** [comment]
No it's definitely not solved !

**Comment by fasheng** [comment]
@sbwtw Well, which tag will fixed this issue?

**Comment by sbwtw** [comment]
last dde-dock tag 3.0.12 contains this change, but it's new dock on DDE, and it's NOT released now, just a alpha test version. please wait.

**Comment by Iceyer** [comment]
@funilrys we well use new designed dock in 15.3 that has fixed this problem,  you should wait a new release in master branch, and it will come in one month or sooner。
Or we has fixed it in raccoon branch， but it will not merge to Arch. you should build it you by yourself.

**Comment by funilrys** [comment]
Thanks @Iceyer :+1:
