### ISSUE TITLE
[Feature request] Deepin-calendar: reminder

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#1101]
I think it would be cool if Deepin-calendar had a "reminder" feature which would remind us about various events.

**Comment by Galvanize87** [comment]
Yup, I just now noticed that this simple feature is not available, please add reminders/events to 
 deepin Calendar. Also can't see as day or week calendar.

**Comment by SiamSami** [comment]
The latest Deepin v20 has this feature. Closing.
