### ISSUE TITLE
[Deepin Integration]~[V25-Release] add dde-print  by Zeno-sole

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#11013]
### Package information | 软件包信息

包名 | 版本
--  | --
dde-printer | [None](https://github.com/linuxdeepin/dde-printer/commit/upstream/master)

### Package repository address | 软件包仓库地址

    deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-2192:/commercial/testing/ ./

**Comment by Zeno-sole** [comment]
**Integration Test Info**
### Test suggestion | 测试建议


### Influence | 影响范围

打印管理器

### ADDITIONAL INFORMATION | 额外补充

**Comment by kingjinni** [comment]
https://pms.uniontech.com/bug-view-289465.html

**Comment by babyfengfjx** [comment]
@luodeepin  请开展回归验证。

**Comment by luodeepin** [comment]
测试通过
1. 问题单回归通过
2. 发散测试打印机正常
