### ISSUE TITLE
BUG : File manager deletion popup ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1102]
## Describe the bug / To Reproduce

Note : make a copy of the video you are testing as this involves deleting it ...

1. copy this test video file to a separate folder
2. play this test video file in deepin-movie player
3. when the movie is playing try to delete this folder which is playing this test video, you'll encounter the following error(screenshot)

## Screenshots
![image](https://user-images.githubusercontent.com/3283676/56460745-5ce92080-63c5-11e9-8604-42421e988501.png)

further when i encounter this above error ... i open the folder that's refusing to get deleted and instead of finding the orginal video file, i see a file in a new file name with some weird naming format to it ...

![image](https://user-images.githubusercontent.com/3283676/56460923-e568c080-63c7-11e9-8107-c9d7fd0410b9.png)

Note : that only if i close the deepin movie window or switch to another video in the playlist is when i am able to delete this folder.

remember the above steps would work perfectly fine without any bug until recently ...

I could easily delete the folder without problem before ... you see i have this habit when i am watching the movies ... when the movies are towards the end ... i just go back and delete the folder containing the movie i was just finishing ... thanks to this strange habit i could identify this bug.

**Comment by aiamuzz** [comment]
i just discovered the above is happening on the external hdd ntfs partition ... if that helps determine the bug easier ...

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
