### ISSUE TITLE
[Deepin Integration]~[V23-release] 应用商店服务端loong64玲珑格式适配

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#11032]
### Package information | 软件包信息

包名 | 版本
--  | --
null | null

### Package repository address | 软件包仓库地址

    null

#### xxxx (1.8.4+ds-3) unstable; urgency=medium

  * xxxxx

**Comment by Zeno-sole** [comment]
**Integration Test Info**
### Test suggestion | 测试建议

需升级至v23最新内测版本，loong64架构 需手动安装 deepin-app-store 

### Influence | 影响范围



### ADDITIONAL INFORMATION | 额外补充

**Comment by xuezhi** [comment]
PMS需求：https://pms.uniontech.com/story-view-37651.html

**Comment by xuezhi** [comment]
验证应用： wts-linglong-loong64-test

**Comment by kobe337** [comment]
【环境】：
镜像：Deepin OS 23 20241022 loongarch64
内核：Linux deepin-PC 6.12.1-loong64-desktop-rolling #23.01.01.14+STE SMP PREEMPT Wed Dec  4 21:01:50 CST 2024 loongarch64 GNU/Linux

【结论】：
测试通过，暂无严重问题及影响, 基于loong64架构，验证玲珑应用上架安装，验证通过，请研发同事确认，相关内容是否合入仓库。
![Image](https://github.com/user-attachments/assets/21da22e0-f00e-4980-892f-ca85ebcef67e)
![Image](https://github.com/user-attachments/assets/92e832f1-f03d-431a-897f-2e8c468b1391)
