### ISSUE TITLE
Deepin image viewer ignores svg masks

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#1106]
## Describe the bug
Deepin image viewer seems to disrespect svg masks. Although preview of same file seems fine in deepin-file-manager.

## To Reproduce
```
/usr/share/icons/deepin/mimetypes/256/package-x-ddf.svg
```

## Expected behavior
Should respect svg masks! :smiley: 

## Screenshots
![test](https://i.imgur.com/grHFsuH.png)

## Enviroments:
OS: Manjaro 18.0.4 Illyria
Kernel: x86_64 Linux 4.19.34-1-MANJARO
Shell: bash
DE: Deepin 15.10
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
compiler: gcc 8.2.1
tk: Qt 5.12.2
dm: LightDM

### Distro & Version
All distros / latest versions

### Related package version
deepin-image-viewer 1.3.13-1

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
