### ISSUE TITLE
Settings Open / Save dialog low z-index

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#1107]
## Describe the bug
In settings z-index of open / save window is lower than settings.

## To Reproduce
1. Open settings
2. Try any open / save window (for example for default programs)

## Expected behavior
This window should be on top of Settings! :smiley: 

## Screenshots
https://i.imgur.com/qeL0IAU.gifv

## Enviroments:
OS: Manjaro 18.0.4 Illyria
Kernel: x86_64 Linux 4.19.34-1-MANJARO
Shell: bash
DE: Deepin 15.10
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
compiler: gcc 8.2.1
tk: Qt 5.12.2
dm: LightDM

### Distro & Version
All distros / up to date

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
