### ISSUE TITLE
QT applications are no longer scaled

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/developer-center#1108]
https://youtu.be/jDeFdGGoA10

**Comment by es20490446e** [comment]
Keybreak reports that it's potentially ALREADY fixed in Arch:
https://forum.manjaro.org/t/qt-applications-are-no-longer-scaled/84247/4

**Comment by keybreak** [comment]
Yep, i confirmed it on VirtualBox VM VLC scales, on current Manjaro Stable don't yet...So we'll have to wait for an update
