### ISSUE TITLE
[abrt] deepin-terminal: XInternAtom(): deepin-terminal killed by SIGSEGV

### ISSUE THREAD

**Issue by cheese** [linuxdeepin/developer-center#1109]
## Describe the bug

Version-Release number of selected component:
deepin-terminal-3.2.1.1-2.fc30

Additional info:
reporter:       libreport-2.10.0
backtrace_rating: 4
cmdline:        deepin-terminal
crash_function: XInternAtom
executable:     /usr/bin/deepin-terminal
journald_cursor: s=2c1d801324d249ab8f264156b110a8f1;i=1248;b=83760063af654e7bbb2ce73ed99cdb4a;m=329f4aab;t=587053e7c29d4;x=c27a607d6857af69
kernel:         5.0.7-300.fc30.x86_64
rootdir:        /
runlevel:       N 5
type:           CCpp
uid:            1000
```
Truncated backtrace:
Thread no. 1 (10 frames)
 #0 XInternAtom at IntAtom.c:174
 #1 widgets_window_update_blur_status at /usr/src/debug/deepin-terminal-3.2.1.1-2.fc30.x86_64/widget/window.c:1402
 #2 __lambda62_ at /usr/src/debug/deepin-terminal-3.2.1.1-2.fc30.x86_64/widget/window.c:955
 #3 ___lambda62__gtk_widget_configure_event at /usr/src/debug/deepin-terminal-3.2.1.1-2.fc30.x86_64/widget/window.c:967
 #4 _gtk_marshal_BOOLEAN__BOXED at gtkmarshalers.c:83
 #9 gtk_widget_event_internal at gtkwidget.c:7744
 #11 gtk_main_do_event at gtkmain.c:1855
 #13 _gdk_event_emit at gdkevents.c:73
 #19 gtk_main at gtkmain.c:1323
 #20 application_main at /usr/src/debug/deepin-terminal-3.2.1.1-2.fc30.x86_64/main.c:1448
```
### Distro & Version

Fedora 30
### Related package version

deepin-terminal-3.2.1.1-2.fc30

**Comment by hualet** [comment]
这些都是在 kde-wayland 上出的问题么？

**Comment by cheese** [comment]
这个是转发其它用户的自动上报(abrt)的 bug，那个人没有其它的描述。调用栈也可以看：
https://retrace.fedoraproject.org/faf/reports/2531291/

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
