### ISSUE TITLE
[archlinux] Dock and Java applications don't play well

### ISSUE THREAD

**Issue by bmentink** [linuxdeepin/developer-center#111]
Hi,

It seems running Java apps, that then launch there own windows, don't behave well with the Launcher.
I created a desktop file and icon for a java app that is launched with " java -jar application-name" and the icon is present in the launch bar.

I click the icon and the program runs, then I get the program to open some windows .... all the windows appear when I hover over the icon in the launch bar as it should.

However, if I close the windows with the window close button, the window does not go away all the time in the icon, and even when you close the program down with the window button, the icon remains in the bar. You cannot now get rid of it, or un-dock it, you have to logout/in again ...
If instead of closing with the windows icon, I close with the icon hover close button in the dock, then everything behaves correctly ..

Eventually by opening/closing windows with the window decoration, the Dock is un-responsive.

I hope I have explained this clearly ..

PS: I am running Arch installed with "Arch Everywhere ISO and chose the Deepin Desktop + extras

**Comment by bmentink** [comment]
anyone?

**Comment by hualet** [comment]
Hi @bmentink , what java application, can you be more specific ?

**Comment by bmentink** [comment]
It's a stockmarket program called "screenulator", it can be freely downloaded from here:

[http://www.screenulator.com/ischarts.jar](url)

**Comment by hualet** [comment]
@electricface

**Comment by electricface** [comment]
This problem has been resolved

**Comment by snyh** [comment]
which commit solved this ?

**Comment by bmentink** [comment]
And will that be fed downstream to ArchLinux? How does that work?

**Comment by felixonmars** [comment]
The Arch packages will be updated as soon as there is a new tag. I assume @electricface meant that it's already included in a tagged release.

**Comment by hualet** [comment]
@bmentink @felixonmars Yeah, we've tested the java application you provided,  it worked pretty well with the new Dock.

**Comment by hualet** [comment]
@snyh The dock daemon is somewhat rewritten  by @electricface , so there's no one specific commit  solves this issue, it's a huge code base change.

**Comment by bmentink** [comment]
I'll look forward to trying it when Arch gets updated ..
Many Thanks guys ...

**Comment by bmentink** [comment]
Hi Guys,

Unfortunately my bug is not resolved.

I got the latest deepin-launcher from testing and I have the same problem with the Java application, eventually if you open/close windows, a window or two stays in the icon and can not be removed. Also, it stops the launcher starting other programs via their launch icon.

Note you have to do about 10..20 window open/close for this to show up.

Cheers,

**Comment by bmentink** [comment]
Solved with the most recent update :)
