### ISSUE TITLE
[abrt] deepin-file-manager: __gnu_cxx::__verbose_terminate_handler()(): dde-file-manager killed by SIGABRT

### ISSUE THREAD

**Issue by cheese** [linuxdeepin/developer-center#1111]
## Describe the bug

https://bugzilla.redhat.com/show_bug.cgi?id=1702514

Version-Release number of selected component:
deepin-file-manager-4.7.7-2.fc30

Additional info:
reporter:       libreport-2.10.0
backtrace_rating: 4
cmdline:        /usr/bin/dde-file-manager -n
crash_function: __gnu_cxx::__verbose_terminate_handler()
executable:     /usr/bin/dde-file-manager
journald_cursor: s=69b78e2b054e40608a2cda63628178ea;i=b8e58e;b=568c0fcb164c456e92be11543e1cb26b;m=73da346e8f;t=5872bf80cfd6b;x=4e98c7fbb7bbb3d7
kernel:         5.0.7-300.fc30.x86_64
rootdir:        /
runlevel:       N 5
type:           CCpp
uid:            1000

backtrace:
https://bugzilla.redhat.com/attachment.cgi?id=1557926

### Distro & Version

Fedora 30
### Related package version

deepin-file-manager-4.7.7-2.fc30

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
