### ISSUE TITLE
sound effects /control center doesn't work

### ISSUE THREAD

**Issue by chemel9** [linuxdeepin/developer-center#1116]
i have installed deepin 15.9 and then i updated to deepin 15.9.3
then check the sound,and it gave me the surprise, that when activating or deactivating them, the changes are not maintained, in the control center.

but the strange thing is that the sound effects works for example when there are notifications
![deepin-screen-recorder_Desktop_20190425213335](https://user-images.githubusercontent.com/26883220/56779719-e885f700-67a1-11e9-88fc-91b79473b79b.gif)

**Comment by BLumia** [comment]
Did you still got this issue when you upgrade to 15.10?

**Comment by chemel9** [comment]
i installed deepin 15.10 , and works correctly :+1: 
![DeepinScreenshot_Desktop_20190428133128](https://user-images.githubusercontent.com/26883220/56868606-2d847600-69ba-11e9-8428-2fcebef49eae.png)

**Comment by BLumia** [comment]
Enjoy :tada:
