### ISSUE TITLE
Deepin File Manager abruptly closing

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#1117]
## Describe the bug
When checking file or folder Properties in File Manager Search; the same is suddenly closed.

## To Reproduce
1. Open the File Manager;
2. Click on the magnifying glass to start the search;
3. Search for any file or folder;
4. In the displayed results, check the Properties of any item displayed;
5. The File Manager is closed abruptly.

## Expected behavior
Let Properties be displayed.

## Screenshots
![Captura de Tela_dde-file-manager_20190426130118](https://user-images.githubusercontent.com/45263160/56822110-7dcacf00-6826-11e9-9bc7-e3e5bacf116e.png)
![Captura de Tela_dde-file-manager_20190426130347](https://user-images.githubusercontent.com/45263160/56822112-7f949280-6826-11e9-9d2a-2fbba6895bd4.png)

### Distro & Version
Deepin 15.9.3
### Related package version
Deepin File Manager 4.7.8.3

### Additional context
I ran File Manager through Terminal. The messages displayed in the Terminal saved in the .txt; who knows, it is possible to detect the problem.

[File Manager.txt](https://github.com/linuxdeepin/developer-center/files/3122178/File.Manager.txt)

**Comment by BLumia** [comment]
This should already fixed in the most recent version of the file manager, next release will comes in around 2~3 days.

**Comment by alexwender1** [comment]
Problem solved!
