### ISSUE TITLE
deepin-kwin

### ISSUE THREAD

**Issue by antechdesigns** [linuxdeepin/developer-center#1118]
I have been using deepin-kwin for the past two weeks and I must say its looking and feeling quite promising, good job guys!! I also created a new archdeepin ISO with deepin-kwin pre-installed and installs without problems :+1: 

I know its not officially released yet, I was just wondering if its a bit premature to be reporting bugs yet or wait for the official release?

No point in reporting bugs if you are aware of them.

Thanks again, keep up the great work :+1:

**Comment by aiamuzz** [comment]
@antechdesigns ... could you post a gif video using deepin screen recorder and post the deepin-kwin and its workings ... would like to see the deepin specific modifications and enhancments ...

I believe we still can test drive it on Deepin OS ... @hualet ... @BLumia ... can we ?

**Comment by antechdesigns** [comment]
all I did was install deepin-kwin and its dependencies, which overrides deepin-wm, so when you reboot it uses deepin-kwin, at least on arch. I also added some extra effects to `kwinrc` found in `.config` folder:

`[Compositing]
Enabled=true
OpenGLIsUnsafe=false

[Desktops]
Id_1=64877165-815b-447b-8e1c-6200ab869491
Id_2=b068e0fd-b6c0-4245-a6a4-5af41f44ecb2

[Plugins]
blurEnabled=true
colorpickerEnabled=false
contrastEnabled=false
cubeslideEnabled=false
desktopchangeosdEnabled=false
desktopgridEnabled=false
highlightwindowEnabled=true
kscreenEnabled=false
kwin4_effect_dialogparentEnabled=false
kwin4_effect_fadeEnabled=true
kwin4_effect_fadedesktopEnabled=true
kwin4_effect_frozenappEnabled=false
kwin4_effect_loginEnabled=true
kwin4_effect_logoutEnabled=true
kwin4_effect_maximizeEnabled=true
kwin4_effect_morphingpopupsEnabled=false
kwin4_effect_windowapertureEnabled=false
minimizeanimationEnabled=true
presentwindowsEnabled=false
screenedgeEnabled=true
screenshotEnabled=false
slideEnabled=true
slidingpopupsEnabled=false
startupfeedbackEnabled=false
wobblywindowsEnabled=true
zoomEnabled=true

[Script-closewindowaction]
BorderActivate=

[Script-runcommandaction]
BorderActivate=

[Windows]
BorderlessMaximizedWindows=true

[org.kde.kdecoration2]
theme=__aurorae__svg__deepin-dark`

and yes the windows do wobble ;)

I am going to do a youtube video preview tomorrow if you can wait ;)

**Comment by aiamuzz** [comment]
> all I did was install `deepin-kwin` and its dependencies, which overrides deepin-wm, so when you reboot it uses `deepin-kwin`

oh ... ok ... `deepin-kwin` package is still not part of the Deepin OS repo ... i guess i'll have to wait until then ... 

If you are going to add audio to the video then youtube is fine ... but if the video is going to be a muted on then ... deepin-recorder in gif format is sufficient and the same can be added here on github ...

**Comment by antechdesigns** [comment]
@aiamuzz 
https://youtu.be/q7ljxRWCPIM

If you want to test it, you can download my archdeepin and follow the instructions above?
https://sourceforge.net/projects/archdeepin/

**Comment by aiamuzz** [comment]
> @aiamuzz
> https://youtu.be/q7ljxRWCPIM
> 
> If you want to test it, you can download my archdeepin and follow the instructions above?
> https://sourceforge.net/projects/archdeepin/

thanks for the video but i could only see the wobbly window(which i honestly hate ... its the same effect i had tried way back on ubuntu using compiz) ... 

@antechdesigns  ... can you please record another video which involves ... the following views which i have captured on deepin-wm ?


![deepin-screen-recorder_Select area_20190427200631](https://user-images.githubusercontent.com/3283676/56851079-a804b580-6928-11e9-9404-efaf7ad31beb.gif)


could you also include the hot corners along with dock view and the small and full screen menu launcher view ...

**Comment by BLumia** [comment]
For Deepin (distro) user, the dde-kwin package will be in the 15.10 release.

Feel free to report any bug you got, whatever you are using Deepin or Arch or any other distro which provide the dde-kwin package, just don't forget to provide the package version, the distro you are using, and other info which may related when you are going to fire a new bug :)

Closing

**Comment by antechdesigns** [comment]
@BLumia thanks ;)

@aiamuzz i turn most of that stuff off in dconf, have no need for it, Looks like your gonna get to test it yourself ;)
