### ISSUE TITLE
Window preview stuck

### ISSUE THREAD

**Issue by ojoakua-10bit** [linuxdeepin/developer-center#1119]
## Describe the bug

Window preview stuck when clicking on small preview window on dock. The window preview will remain there until I Alt+Tab to other window or switching to other workspace via shortcut key. Also multitasking view doesn't work when the window preview is stuck.

## Steps To Reproduce

1. Hover to minimized application icon on dock, a small preview window will pop up.
2. Hover to the small preview window, the full-size preview of application window will appear.
3. Click on the small preview window, the main application appear. But the full-size preview still stuck there.

## Expected behavior

Window preview shouldn't stuck.

## Screenshots

![deepin-screen-recorder_Desktop_20190427204336](https://user-images.githubusercontent.com/33028351/56850546-48110d80-692e-11e9-9ac4-54771c29a040.gif)
![deepin-screen-recorder_Desktop_20190427210639](https://user-images.githubusercontent.com/33028351/56850791-73492c00-6931-11e9-8c72-3d7dd975ec1b.gif)

### Distro & Version

Arch Linux

### Related package version

These packages might be related
```
deepin-clutter 1.26.2-2
deepin-daemon 3.27.0-1
deepin-desktop-base 2:2019.04.03-1
deepin-desktop-schemas 3.13.0-1
deepin-dock 4.9.8-2
deepin-launcher 4.6.9-1
deepin-mutter 3.20.38-1
deepin-wm 1.9.38-1
```

**Comment by hualet** [comment]
@ojoakua-10bit Have you tried dde-kwin?

**Comment by ojoakua-10bit** [comment]
Already tried it. Still has a lot of bugs.


Like dock preview now doesn't work on minimized window, workspace-specific wallpaper doesn't work, window decoration doesn't follow current GTK theme (I know I have to use KDE-version of the theme but theme settings only show GTK themes) and also #1133

**Comment by Lokke** [comment]
#1200

**Comment by SiamSami** [comment]
Fixed!

**Comment by SiamSami** [comment]
https://github.com/linuxdeepin/dde-dock/pull/280
Fixed and merged. Can anyone close it?
