### ISSUE TITLE
关于dbus的问题，请教一下

### ISSUE THREAD

**Issue by kirigayakazushin** [linuxdeepin/developer-center#112]
目前对dbus还是一知半解，我想将音频里面的输入反馈的值应用到我的程序上，deepin-daemon封装了dbus，我通过dbus-monitor也查看到了相关的值，在实际代码中，我无法获取到这个值。代码参考的是dcc中的代码。
`signal time=1471338550.537787 sender=:1.18 -> destination=(null destination) serial=295466 path=/com/deepin/daemon/Audio/Metersource2; interface=org.freedesktop.DBus.Properties; member=PropertiesChanged
   string "com.deepin.daemon.Audio.Meter"
   array [
      dict entry(
         string "Volume"
         variant             double 0.105865
      )
   ]
   array [
   ]`

![20160816172729](https://cloud.githubusercontent.com/assets/12298476/17694563/109495ba-636a-11e6-9cb6-ede1bdcd2181.png)

**Comment by sbwtw** [comment]
可以参考 controlcenter 里面 sound 模块的代码

**Comment by kirigayakazushin** [comment]
@sbwtw  参考的就是controlcenter的sound模块代码，可是qt输出的结果是这样的。

(QVariant(QString, "com.deepin.daemon.Audio.Meter"), QVariant(QDBusArgument, ), QVariant(QStringList, ()))

**Comment by Iceyer** [comment]
@kirigayakazushin 方便贴下完整的源码吗，这样说也看出问题啊...

**Comment by kirigayakazushin** [comment]
```
void Voice::startInput() {
// m_baiduVop("pxxHWz9KmNsleFBsuWHQ77Hd", "b5a9a0eb50d410b0dccd3eec5fc30388");
     m_baiduVop.start();
//     QString meterPath = m_defaultSource->GetMeter().value().path();
//     QString meterName = meterPath;
//     meterName = meterName.replace("/", ".").mid(1);

//     if (m_dbusMeter) {
//         m_dbusMeter->deleteLater();
//     }

//     m_dbusMeter = new QDBusInterface("com.deepin.daemon.Audio",
//                                      meterPath,
//                                      meterName,
//                                      QDBusConnection::sessionBus(),
//                                      this);
//     connect(m_meterTimer, &QTimer::timeout, m_dbusMeter, [&] {
//         m_dbusMeter->call("Tick");
//         m_meterTimer->start(5000);
//     });

     QDBusConnection::sessionBus().connect("com.deepin.daemon.Audio",
                                           "/com/deepin/daemon/Audio/Metersource2",
                                           "org.freedesktop.DBus.Properties",
                                           "PropertiesChanged", "sa{sv}as",
                                           this, SLOT(handleMeterVolumeChanged(QDBusMessage)));
//     m_meterTimer->start(5000);
}
```

**Comment by kirigayakazushin** [comment]
我觉得问题可能来自这里
```
 QString meterPath = m_defaultSource->GetMeter().value().path();
```
我把dbusaudiosource.h/.cpp都复制到本地引用了，把关联的部分都引用了过来，但是运行这句的时候，就出错了，我就改成"/com/deepin/daemon/Audio/Metersource2"了，对比输出信息，第二行和后面都是空的，所以我觉得可能是path写的有问题。

**Comment by sbwtw** [comment]
返回的那个 QDBusArgument 应该就是数据，只不过这是一个复杂类型的，你不能直接输出而已，转换成 QMap<QString, double> 试试

**Comment by Iceyer** [comment]
@kirigayakazushin  slot 函数这样写
void SoundControl::handleMeterVolumeChanged(const QDBusMessage &msg)
{
    QList<QVariant> arguments = msg.arguments();

    QVariantMap changedProps = qdbus_cast<QVariantMap>(arguments.at(1).value<QDBusArgument>());
    if (changedProps.contains("Volume")) {
//        qDebug() << "meter change to " << changedProps.value("Volume").toDouble();
        emit inputMeterVolumeChanged(changedProps.value("Volume").toDouble() * 100);
    }
}

返回数据类型是QVariantMap， 不是QString

**Comment by kirigayakazushin** [comment]
@Iceyer  @sbwtw  多谢，原来是我理解错了。已经拿到数据了。

**Comment by kirigayakazushin** [comment]
@Iceyer  我想获取电量来着

`    
QDBusConnection::sessionBus().connect("com.deepin.daemon.Power",
                                          "/com/deepin/daemon/Power",
                                          "org.freedesktop.DBus.Properties",
                                          "PropertiesChanged", "sa{sv}as",
                                          this, SLOT(propertyChanged(QDBusMessage)));
`

但是提示我
error: no matching function for call to 'QDBusConnection::connect(const char [24], const char [25], const char [32], const char [18], const char [9], Hpbar*, const char*)'
                                           this, SLOT(propertyChanged(QDBusMessage)));
                                                                                    ^
看了一下dde-dock和dcc的shutdown和power代码，貌似用的是不同的方法来处理电量。

`
public slots:
    void propertyChanged(const QDBusMessage &msg);
`

**Comment by Iceyer** [comment]
@kirigayakazushin 你参考新版dde-dock的代码吧，控制中心用的是旧版的方法。

https://github.com/linuxdeepin/dde-dock/blob/master/plugins/shutdown/powerstatuswidget.cpp#L14
