### ISSUE TITLE
Updated 15.10 : SOS !!! ... How to switch back to deepin-wm ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1121]
I just updated to 15.10 on my Deepin Unstable ... and i believe the update is running `kwin` ... 

everything is messed up ... isn't DeepinOS's primary selling point is visual eye candy ?
with kwin everything is off ... I am sorry but Deepin OS is not longer a visual eye candy ... its just like any other linux distro that isn't visually appealing ...  **A BIG LETDOWN DISAPPOINTMENT !!!**

1. default shortcuts have been deleted ... 
2. All windows in a workspace view is ugly ...
3. All windows in all workspace view is ugly ...
4. unable to switch between workspaces ...

CAN SOMEBODY HELP ME RETURN TO THE OLDER 'WM' ???

**Comment by aiamuzz** [comment]
can somebody convince me how is this UI visually appealing ?
unless something is broken on my recently upgraded system ... this is not eye-candy by any standards !!!


![deepin-screen-recorder_google-chrome_20190428134606](https://user-images.githubusercontent.com/3283676/56861183-23fc0d80-69bc-11e9-9e9a-471e2567dfa6.gif)

**Comment by antechdesigns** [comment]
@aiamuzz 

On arch if I want to switch back to deepin-wm I do a `deepin-wm --replace` in terminal. 
If everything runs fine you could then add the .desktop file to autostart folder in your .config from usr/share/applications Deepin Window Manager.

**Comment by iamhyc** [comment]
```
sudo apt purge dde-kwin
```
then reboot; it will use `deepin-wm` as default.

P.S. If you are not sure whether `deepin-wm` is still there, execute `sudo apt install deepin-wm`.

**Comment by keybreak** [comment]
@aiamuzz 
Yeah man, chill out and wait until it's finished, like @antechdesigns said - it's work in progress and you should generally avoid unstable branch i might add)

Kwin is not meant to take any aesthetic aspect of Deepin OS, it's just technical means of delivering visuals ,so when it'll be ready and released it shouldn't change anything in looks / workflow.

**Comment by aiamuzz** [comment]
> Don't forget this is a work in progress, which is my only gripe with deepin development, get it working and looking right before release, anybody trying deepin while this is going on will run a mile and go to something else, imho ;)

exactly ... @antechdesigns ...

> Yeah man, chill out and wait until it's finished, like @antechdesigns said - it's work in progress and you should generally avoid unstable branch i might add)

@keybreak ... the reason i panic raise alarms such as this is because of what @antechdesigns ... nicely put it !!! ... its all negative PR ... any user happens to pass by our OS during such times will never look back ... you might want to consider it next time you make a decision that renders the familiar DeepinOS into a strange and unfamiliar one !!!

> Kwin is not meant to take any aesthetic aspect of Deepin OS, window manager - is just technical means of delivering visuals (and mutter, which is used now is known to be buggy / lag in some nvidia setups), so when it'll be ready and released it shouldn't change anything in looks / workflow.

@keybreak ... @shule1987 ... @hualet ... @BLumia ... and the @whole-deepin-team ... **make no mistake ...** the success and popularity of DeepinOS is its visual appeal ... its aesthetics ... its eye candy look which drives even the oldest of linux users to think that this may be some non-linux OS ... like the lightweight chrome OSes and the andriod x86 OSes ... when the reality is that its a full blown LInux OS under the whole UI/UX !!!

**Any decision the team takes that drops/meddle's this appeal / aesthetics / eye-candy experience is driving an otherwise perfect OS(in terms of appeal/aesthetics) directly into the ground !!!**

@keybreak ... can you honestly put your hand to heart and tell us that the current "kwin workspace management screen" is better than this ... 

![deepin-screen-recorder_Select area_20190428153509](https://user-images.githubusercontent.com/3283676/56862803-6fb6b300-69cc-11e9-833b-c645f382fe2f.gif)

**i don't know whether you guys realize or not ... but the whole animation(that plays out on the screen) when users are moving between the workspaces and managing their windows is the soul of the UI/UX and ### is the signature of DeepinOS ... you can't change this signature and tell us to chill !!! ... 
it is the face of DeepinOS ... you can't change someone's face and ask us to relax saying the body is the same ... changing the face means a different person ... an unfamiliar person ... panic is the only justified reaction ... imagine you go to sleep with your wife and when you wake up in the morning she has a whole new face ... what would your reaction be !!!**

@keybreak ... if you are telling kwin is just the technical under the hood stuff ... then i'd ask only one question to the Deepin-Team ...

**Can you recreate the signature of DeepinOS meaning the workspace management layout and flow to match exactly to what existed before this switch**  ...  if its possible then that's the **first thing you should have done** ... created this signature/face before introducing/integrating it into the OS and make us scream !!!

If recreating the same signature/face and its layout/flow is not possible then please provide an additional setting in the control settings which will let the users choose ... mutter based WM or kwin WM ... the usage stats will give you the feedback of what users prefer more !!!

**Comment by aiamuzz** [comment]
> On arch if I want to switch back to deepin-wm I do a `deepin-wm --replace` in terminal.

@antechdesigns ... i did try that out ... and the thing switches back to the old WM ... but the fluidity is no longer there ... the thing crashes when i try to switch from one workspace to another ... and i have to re run the replace command ...

**Comment by keybreak** [comment]
@aiamuzz 
I'm just user / heavy tester though, not part of Deepin team :smile: 

> Any decision the team takes that drops/meddle's this appeal / aesthetics / eye-candy experience is driving an otherwise perfect OS(in terms of appeal/aesthetics) directly into the ground !!!

And sure as hell i agree with that :smiley: 
But anyway, **unstable** - means unstable, so i think your alarm sounds very very early on yet...

If this will be out in stable in such condition as now - i will sound my alarm too as many others)

**Comment by aiamuzz** [comment]
> ```
> sudo apt purge dde-kwin
> ```
> then reboot; it will use `deepin-wm` as default.
> 
> P.S. If you are not sure whether `deepin-wm` is still there, execute `sudo apt install deepin-wm`.

thanks ... this worked ... i think i am regaining my composure ... whew !!!

**Comment by aiamuzz** [comment]
> @keybreak ... if you are telling kwin is just the technical under the hood stuff ... then i'd ask only one question to the Deepin-Team ...
> 
> **Can you recreate the signature of DeepinOS meaning the workspace management layout and flow to match exactly to what existed before this switch** ... if its possible then that's the **first thing you should have done** ... created this signature/face before introducing/integrating it into the OS and make us scream !!!

@keybreak ... are you part of the Deepin Dev Team ... then i'd like to hear an answer to the above !!!

if this is not achievable ... i don't think i'll ever switch to kwin WM ... mutter based deepin-WM is my choice ... the day that will be decommissioned will be the day i probably bid adios to DeepinOS ... unless @shule1987 ... surprises us with new face/signature that will beat the mutter based Deepin-WM signature !!!

**Comment by aiamuzz** [comment]
@shule1987 ... @hualet ... @BLumia ... @wangjia12 ... 

a word of advise/caution ... i hope you've not pushed kwin to all the DDE ports for various distro's ... you might want to defer/delay it until you've either created an option in the Deepin Control Settings where the user can choose `mutter based WM` or `kwin based WM` ... or ... until you;ve recreated/replicate exactly the workspace windows management / workflow that we have on mutter based deepin-wm ... if that's possible ... **I don't see why the users of other distros using our DDE need to be scared to death with this half baked new face kwin implementation !!!**

**Comment by keybreak** [comment]
> are you part of the Deepin Dev Team ... then i'd like to hear an answer to the above !!!

1. I am **NOT** part of anything related to Deepin development (just user that reports a lot of bugs).

2. You don't have to be part of dev team, to have some basic knowledge of what is [window manager](https://en.wikipedia.org/wiki/Window_manager) & how extremely different [mutter](https://www.google.com/search?q=mutter+window+manager&newwindow=1&client=firefox-b-d&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiwlaaczvLhAhWpyqYKHSuIALwQ_AUIDigB&biw=1643&bih=1452#imgrc=_) and [kwin](https://www.google.com/search?newwindow=1&client=firefox-b-d&biw=1643&bih=1452&tbm=isch&sa=1&ei=r4TFXLD0G63AmwW98IKYAg&q=kwin+window+manager&oq=kwin+window+manager&gs_l=img.3..0i19.406594.406975..407088...0.0..0.76.280.5......1....1..gws-wiz-img.......0i7i30.zuD6528m_rA) **can** look.

3. Default implementation of mutter usually looks like s***, **deepin-mutter** is a heavily tweaked fork.

4. With **deepin-kwin** they're in the process of making same with default **kwin**.

So even though i'm not part of Deepin team, i can with 100% certainty answer:
Q: Is it technically possible to make **deepin-kwin** look and feel exactly same as **deepin-mutter**?
A: Yes.

But rest is up for actual deepin team and us as users, since nobody (? :rofl: ) want to wake up with another face of his wife as you've said! :smiley:

**Comment by aiamuzz** [comment]
> 1. I am **NOT** part of anything related to Deepin development (just user that reports a lot of bugs).

same here ...

> 2. You don't have to be part of dev team, to have some basic knowledge of what is [window manager](https://en.wikipedia.org/wiki/Window_manager) & how extremely different [mutter](https://www.google.com/search?q=mutter+window+manager&newwindow=1&client=firefox-b-d&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiwlaaczvLhAhWpyqYKHSuIALwQ_AUIDigB&biw=1643&bih=1452#imgrc=_) and [kwin](https://www.google.com/search?newwindow=1&client=firefox-b-d&biw=1643&bih=1452&tbm=isch&sa=1&ei=r4TFXLD0G63AmwW98IKYAg&q=kwin+window+manager&oq=kwin+window+manager&gs_l=img.3..0i19.406594.406975..407088...0.0..0.76.280.5......1....1..gws-wiz-img.......0i7i30.zuD6528m_rA) **can** look.

well i haven't really gone to the extent of knowing the technical stuff ...

> 3. Default implementation of **mutter** usually looks like s***, **deepin-mutter** is a heavily tweaked fork.

yeah i agree ... i was using UbuntuGnome for more than 3 years and i had no idea the WM there the WM here on Deepin where sisters ... I never used workspaces on UbuntuGnome back then ... it was just not appealing ... like you put it ... Sh*** ... :stuck_out_tongue: 

> 4. With **deepin-kwin** they're in the process of making same with default **kwin**.
> 

I really hope so ...

> So even though i'm not part of Deepin team, i can with 100% certainty answer:
> Q: Is it technically possible to make **deepin-kwin** look and feel exactly same as **deepin-mutter**?
> A: Yes.

thank you really helps to know that ... then its a blunder that the deepin team decided to implement/introduce kwin without fully recreating the face and features of the Deepin Damsel :stuck_out_tongue_winking_eye: ...

seems they have just attached a new head without the skin and the beautiful features of the face ... anybody would shriek at seeing a face with the muscles and veins instead of a proper face and all its beautiful features !!! ... :wink: 

> But rest is up for actual deepin team and us as users, since nobody (?  ) want to wake up with another face of his wife as you've said ! 

hahahaha ... :joy: ... then what ... definitely not one which is bad !!!

**Comment by aiamuzz** [comment]
@iamhyc ... @hualet ...

can you please tell me how can make deepin-wm default on Deepin 15.10 freshly(stable) installed system ?

I installed the package ...
`sudo apt-get install deepin-wm`

running the following command will switch to deepin-wm in the given session 
`deepin-wm --replace`

However when i reboot it defaults to `kwin`

I tried to run the 'remove' and 'purge' commands ... as you can see below ...
```
$ sudo apt-get remove dde-kwin
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  dde dde-kwin
0 upgraded, 0 newly installed, 2 to remove and 0 not upgraded.
After this operation, 690 kB disk space will be freed.
Do you want to continue? [Y/n] 
```
its prompting to remove/purge `dde` ...

**I would like to make deepin-wm default on this fresh installation ... any help is appreciated !!!**

**Comment by iamhyc** [comment]
@aiamuzz `dde` is just one pseudo-package which describe the dependency of dde, a.k.a remove any dde related package will **break** the dependency of the `dde` package.

Anyway, just remove it. It will not affect anything until you want to run `apt autoremove` :)

**Comment by aiamuzz** [comment]
> @aiamuzz `dde` is just one pseudo-package which describe the dependency of dde, a.k.a remove any dde related package will **break** the dependency of the `dde` package.
> 
> Anyway, just remove it. It will not affect anything until you want to run `apt autoremove` :)

I am not sure ... i don't want to break any package dependencies that may be important for the OS ... as i have done a fresh install ... can somebody show me a non-destructive way to make `deepin-wm` as the default window manager ?

**Comment by antechdesigns** [comment]
@aiamuzz 
Look in usr/share/applications for Deepin Window Manager icon, (should be a cog) see below

![DeepinScreenshot_dde-desktop_20190429110440](https://user-images.githubusercontent.com/29888048/56889629-cb397d00-6a6e-11e9-9407-2cff28ec8ef8.png)

right click copy, and paste it into home/.config/autostart folder then reboot.

See if that works for you ;)

**Comment by hualet** [comment]
@aiamuzz You can remove `/usr/bin/kwin_no_scale` without deleting the whole package I think.

You can use deepin-wm without any problem, but we've decided that Kwin is the future, so the earlier we prompt Kwin the earlier it can get grown, stable and of course the eye candy thing.

**Comment by aiamuzz** [comment]
> @aiamuzz You can remove `/usr/bin/kwin_no_scale` without deleting the whole package I think.

ok ... i'll give it a try ...

> but we've decided that Kwin is the future, so the earlier we prompt Kwin the earlier it can get grown, stable and of course the eye candy thing.

@hualet ... i am not against any stuff that technically strengthens the under-the-hood stuff ... am not against kwin ... **i am against the bland UI/UX experience kwin currently offers or any other linux distro for that matter that exist in the market currently  !!!**

I am just not with you(the team) when you say things like ... **'ofcourse the eye candy thing'** ... the eye-candy thing can never by an **'of course'** thing ... it is the "Main Course" ... it is Why WE have been drawn to DeepinOS ... if the Deepin Team considers that low down the priority ... then i am sure we have far powerful(stable) Linux OSeS than Deepin OS to look up to and consider !!!


> Have you guys worked on the usage stats scientifically ? ... 
> 
> say for an hour of usage on DeepinOS ... 
> 
> 1. How many times will a user access the app launcher ?
> even on a higher side less than 10 times ... lasting for 10 secs (for searching and launching the app) each time ... amounting to 100 secs of visual play time
> 
> 2. How many times will a user access the Control Center Settings panel ?
> 1-2 times or not even once ... lets say 1-2 times ... lasting 25 secs of visual play ... amounting to 50 secs of visual play time
> 
> 3. Now Lets get to the visual play time of moving between workspaces ... moving app windows between them ... moving between workspaces ... viewing all apps of a particular workspace ... apps across all workspaces ... 
> 
> An hour of has 3600 secs ... except (1+2) 150 ... the rest of 3450 secs of visual play time happens to fall in the 3rd category ...
> 
> I hope you realize that THIS THIRD CATEGORY IS `deepin-wm` ... this is the category which gives us the whole DeepinOS and its UI & UX ... THE WHOLE EYE-CANDY APPEAL !!!
> 
> 

If the Deepin Team does not put the **"The eye candy Thing"** as the top most priority then why should anybody bother migrating to DeepinOS ... we might as well move on to other older and more powerful(stable) linux distro's ... don't you think ???

**The Deepin Team CANNOT lose sight of "The Eye Candy" character of Deepin OS ... that is the engine that powers DeepinOS ...**

If you guys loose sight of this and moved your resources to under the hood stuff (yes they are equally important but cannot be traded off)... then you go weak in experience and expertise ... as there are far more seasoned(in the years of their existence and in their vast organizational existence) linux distro's that the industry swears by ... especially their power and stability !!!


PS : I personally wouldn't stick on to it if DeepinOS loses the eye candy thing ... So i am pretty clear If your kwin integration cannot beat `deepin-wm's` eye candy looks ... then i'd stay with DeepinOS only as long as @sonald ... keeps the deepin-wm up and running ... the day you pull the plug on deepin-wm ... will be the end of my ride on DeepinOS (except if kwin can wow us all with an even better look for DeepinOS)

**Comment by aiamuzz** [comment]
Note : when i am referring to `deepin-wm` ... i am ONLY referring to its visual UI/UX & not its under-the-hood-stuff ... So please don't mistake me to be lobbying to keep `deepin-wm` underlying technology !!!

Simple put ... `kwin` ... HAS to beat the visual UI/UX & appeal to a minimum of the current ... `deepin-wm` and its appeal !!!

the best way to start would be to do what i have written here ... [create this exact same look, feel and flow as we have with deepin-WM](https://github.com/linuxdeepin/developer-center/issues/573#issuecomment-487456076)

**Comment by alexwender1** [comment]
Calm @aiamuzz dde-kwin is in development. The deepin team started working on this a few weeks ago.

Really, it was a surprise to see this tool already on release. The benefits are greater than the bugs present.

Be patient! The dde-kwin will not be ugly.

**Comment by sonald** [comment]
@aiamuzz please wait and see in patience. the whole deepin-wm development cycle was almost across over three years, and yet dde-kwin is just as young as a baby. we need time to advance and improve.

**Comment by hualet** [comment]
@aiamuzz I get you, deepin will eventually be good looking as it always is. And we don't want to lose you and anybody not just contributing to this project but actively contributing to this project :smiley:

**Comment by aiamuzz** [comment]
> @aiamuzz You can remove `/usr/bin/kwin_no_scale` without deleting the whole package I think.
> 
> And you can use deepin-wm without any problem, but we've decided that Kwin is the future, so the earlier we prompt Kwin the earlier it can get grown, stable and of course the eye candy thing.

@hualet ...

i ran the following commands ...

 ```
sudo mv /usr/bin/kwin_no_scale /usr/bin/kwin_no_scale.backup
sudo mv /usr/bin/kwin /usr/bin/kwin.backup
sudo mv /usr/bin/kwin_x11 /usr/bin/kwin_x11.backup
```
after reboot deepin-wm is the default wm ...

> @aiamuzz I get you, deepin will eventually be good looking as it always is. And we don't want to lose you and anybody not just contributing to this project but actively contributing to this project

thanks ... Its the eye candy appeal and the team's willingness to listen to users is what powers this OS !!!

> The deepin team started working on this a few weeks ago. Really, it was a surprise to see this tool already on release.

it has scared the shit out of me ... i went to sleep with deepin-wm and woke with deepin with a totally different face to it ... i literally shrieked ... :cry: ... a break in the routine isn't easy to handle ... when you are in complete 'zen' with something it shakes you ... lucky i can still run deepin-wm ... 

> @aiamuzz please wait and see in patience. the whole deepin-wm development cycle was almost across over three years, and yet dde-kwin is just as young as a baby. we need time to advance and improve. by releasing it soon and frequently, we can steadily move forward and any sincere comments are welcomed as always.

thanks @sonald ... I just wanted to know ... as you seem to be the primary developer of Deepin-WM ... **is kwin flexible enough so one could duplicate the deepin-wm's exact same UI/UX ? ... i mean exactly like it ... with the workspace previews on top with and the application previews on the screen ... the same shortcuts to move between different workspaces and all ?**

**Comment by sonald** [comment]
> is kwin flexible enough so one could duplicate the deepin-wm's exact same UI/UX ? ... i mean exactly like it ... with the workspace previews on top with and the application previews on the screen ... the same shortcuts to move between different workspaces and all ?

they are completely architecturally different. so I'll leave it to @zccrs to answer.

**Comment by hualet** [comment]
@sonald you bad guy.

@aiamuzz, Of course, it can, but it takes time and we may change a little bit on the current deepin-wm design.

**Comment by aiamuzz** [comment]
> @sonald you bad guy.

@hualet ... well, come to think of it ... @sonald ... has a right to be bad ... after all you seem to have culled(killed) his cute baby(deepin-wm) ... i can understand Sian ... if i am feeling so bad ... you reactions are perfectly in order ... :stuck_out_tongue_closed_eyes:

**Comment by aiamuzz** [comment]
> @aiamuzz, Of course, it can, but it takes time and we may change a little bit on the current deepin-wm design doing the new implementation on Kwin.

![deepin-screen-recorder_google-chrome_20190430112936](https://user-images.githubusercontent.com/3283676/56943035-4bc5af80-6b3b-11e9-98ff-24507cdbd6f5.gif)

how can somebody beat something as beautiful as this ... i sure hope `kwin` is up for the challenge !!!

@sonald ... i just noticed ... you like baby's ... your profile pic has a cute one !!!

**Comment by aiamuzz** [comment]
@hualet ... @BLumia ...

I just ran the latest set of updates on the 15.10 stable installation ... 

i thought i'd test `kwin` after this update ... but after rebooting the 'window effect' is failing continuously ... i am forced to return to `deepin-wm`

**Comment by keybreak** [comment]
@aiamuzz 
I was really shocked to see release of deepin-kwin on stable - this is insane move.
And to be fair - If you'll manage to launch it on Linux Deepin it will look way better than before, but still very raw.

And even more, compared to Arch Deepin variant of **deepin-kwin** - it's reeeaaally polished and bug-free :laughing: 

______

Here's part of another thread:

> Nobody sane would argue that and rush you if it was clear what's going on (on contrary there are a lot of people asking to slow down the rush and reduce bugs / improve testing).
@keybreak 

> Sometimes I think if there is a community fork of DDE would be quite good, there are a bunch of reason we release 15.10 in a hurry (actually 15.10 got delayed twice internally), a main reason is the enterprise repo / codebase migration, so we got very limited time working on that release (as you can see we still very busy these days). We are sorry about it bring some bad experience but the release itself doesn't as bad as you imaged (for example, something breaks we find out it is because of the repo changed to debian stable, not because 15.10 codebase). Community fork will probably comes with much less pressure from enterprise user, project management deadline and etc.
@BLumia 

That was actually news to me - i never knew Deepin team have enterprise versions / overlords, i always perceived it as just open-source project.

This explains rush, but still by any standard as a professionals you should know that releasing simultaneously such a huge changes as:
1. Debian stable codebase
2. Clearly unfinished deepin-kwin

Will just crush in all possible ways, especially considering that you're saying team is just a few people.
Just please, never repeat this mistake again.

Only one big change at a time, and only when it's really finished and tested.

Also allow to disagree - it is exactly as bad as i imaged, we all have eyes and terminal journals - **deepin-kwin** is really raw and buggy still.

Even though i agree that Linux Deepin variant is way better than what's available on Arch / Manjaro now, in there it's:
1. Not default yet (which is for now definitely a good thing)
2. Just barely usable (unless i did something very wrong).

**Comment by aiamuzz** [comment]
> I was really shocked to see release of deepin-kwin on stable - this is insane move.

@keybreak ... `deepin-kwin` is not installed on the stable ... i believe they have used some other way of implementation/configuration possible by way of the package `dde-kwin` ...

Just yesterday i was browsing the `dde-kwin` and `deepin-kwin` repos here and found that the `deepin-kwin` repo shows a lot of features which aren't found currently on linux deepin ... 

what is found on linux deepin is a bland and ugly UI / UX ... no where close to the beauty of `deepin-wm` !!!

**Comment by keybreak** [comment]
@aiamuzz 
It is, you can try on VM or just new 15.10 .iso
https://www.deepin.org/en/download/
