### ISSUE TITLE
[15.10 stable] 常用软件在stable中缺失

### ISSUE THREAD

**Issue by iamhyc** [linuxdeepin/developer-center#1122]
## 缺陷描述
部分常用软件在stable仓库中不存在

## 复现步骤
1. 商店/apt源 中查找flatpak package
2. 商店 中查找Typora
3. ~~商店 中安装Oracle VirtualBox~~（不能复现）

## 期望行为
1.2.3. 有

### 发行版以及版本
Linux Deepin 15.10 stable

### 其他内容
1. Typora的ppa源也无法使用，错误如下：
```
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Deepin/stable
```
P.S. 这真的可以叫release？这比内测还beta

**Comment by BLumia** [comment]
stable 直接找对应 debian stretch 的包应该就没问题，商店上架相关 cc @deepinzhangshuang @wangjia12 

Unstable 源应该还是有这些应用的，部分应用尚未上架 stable 源应该不至于“比内测还beta”吧...

顺便关于 ppa ，不建议找适配别的发行版但未适配 Deepin 的 ppa 使用，你提供的错误也是这个意思，表示那个 ppa 目前并没有提供对应 Deepin/stable 的内容。

**Comment by iamhyc** [comment]
> stable 直接找对应 debian stretch 的包应该就没问题，商店上架相关 cc @deepinzhangshuang @wangjia12
> 
> Unstable 源应该还是有这些应用的，部分应用尚未上架 stable 源应该不至于“比内测还beta”吧...
> 
> 顺便关于 ppa ，不建议找适配别的发行版但未适配 Deepin 的 ppa 使用，你提供的错误也是这个意思，表示那个 ppa 目前并没有提供对应 Deepin/stable 的内容。

那个是Typora官网提供的安装方法，https://typora.io/#linux，至少unstable的时候还有效

**Comment by BLumia** [comment]
> 那个是Typora官网提供的安装方法，https://typora.io/#linux; 至少unstable的时候还有效

毕竟发行版版本比较多，Deepin 的新 stable 版本是刚刚才发布，第三方仓库维护者大概没有那么快的速度做支持。如果“假装”成 debian stretch 的话大概就可以了，不过不建议这么做。 Typora 的话可以尝试反馈给 Typora 的 ppa 维护者，看看有没有意向支持？
 
> 顺便问下flatpak为什么也移除了……

毕竟稳定版仓库和不稳定版仓库差距挺大的，一部分包不是直接搬过来就能用，这些软件会逐渐加回来。

**Comment by hualet** [comment]
typora按照官方的安装方式加源可以安装，我今天刚装了…… 不过@deepinzhangshuang 啥时候放仓库啊。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
