### ISSUE TITLE
深度编辑器：便签增加菜单 - 打开文件所在路径

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#1123]
有时候把文管全关了，重新去找文件很麻烦，在标签右键菜单加一个菜单打开文件所在路径。

![](https://www.simipic.com/images/2019/04/28/openpath1c90e8d59a75f22a.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
