### ISSUE TITLE
[archlinux] lightdm-deepin-greeter crash

### ISSUE THREAD

**Issue by amit-gshe** [linuxdeepin/developer-center#1125]
## Describe the bug

Lightdm-deepin-greeter generates a segment falt.

## To Reproduce
Normal boot and then `sudo journalctl -b` will find the following lines:
```
4月 29 10:27:22 Arch systemd-coredump[766]: Process 725 (lightdm-deepin-) of user 620 dumped core.
                                             
                                             Stack trace of thread 725:
                                             #0  0x0000555e4a57bc87 n/a (lightdm-deepin-greeter)
                                             #1  0x0000555e4a57e1d2 n/a (lightdm-deepin-greeter)
                                             #2  0x00007f19d6a15af8 _ZN7QWidget5eventEP6QEvent (libQt5Widgets.so.5)
                                             #3  0x00007f19d69d4da4 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                             #4  0x00007f19d69dc3c1 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                             #5  0x00007f19d73f3ca9 _ZN3Dtk6Widget12DApplication6notifyEP7QObjectP6QEvent (libdtkwidget.so.2)
                                             #6  0x00007f19d5f31849 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                             #7  0x00007f19d6a12388 _ZN14QWidgetPrivate11show_helperEv (libQt5Widgets.so.5)
                                             #8  0x00007f19d6a15645 _ZN14QWidgetPrivate10setVisibleEb (libQt5Widgets.so.5)
                                             #9  0x0000555e4a5896ea n/a (lightdm-deepin-greeter)
                                             #10 0x0000555e4a5897a9 n/a (lightdm-deepin-greeter)
                                             #11 0x00007f19d6a15af8 _ZN7QWidget5eventEP6QEvent (libQt5Widgets.so.5)
                                             #12 0x00007f19d6abd71f _ZN6QFrame5eventEP6QEvent (libQt5Widgets.so.5)
                                             #13 0x00007f19d69d4da4 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                             #14 0x00007f19d69dc3c1 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                             #15 0x00007f19d73f3ca9 _ZN3Dtk6Widget12DApplication6notifyEP7QObjectP6QEvent (libdtkwidget.so.2)
                                             #16 0x00007f19d5f31849 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                             #17 0x00007f19d6a12388 _ZN14QWidgetPrivate11show_helperEv (libQt5Widgets.so.5)
                                             #18 0x00007f19d6a15645 _ZN14QWidgetPrivate10setVisibleEb (libQt5Widgets.so.5)
                                             #19 0x0000555e4a5b331c n/a (lightdm-deepin-greeter)
                                             #20 0x00007f19d6a15af8 _ZN7QWidget5eventEP6QEvent (libQt5Widgets.so.5)
                                             #21 0x00007f19d69d4da4 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                             #22 0x00007f19d69dc3c1 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                             #23 0x00007f19d73f3ca9 _ZN3Dtk6Widget12DApplication6notifyEP7QObjectP6QEvent (libdtkwidget.so.2)
                                             #24 0x00007f19d5f31849 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                             #25 0x00007f19d69db3cd n/a (libQt5Widgets.so.5)
                                             #26 0x00007f19d6a2f3cc n/a (libQt5Widgets.so.5)
                                             #27 0x00007f19d6a33d01 n/a (libQt5Widgets.so.5)
                                             #28 0x00007f19d69d4da4 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                             #29 0x00007f19d69dc3c1 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                             #30 0x00007f19d73f3ca9 _ZN3Dtk6Widget12DApplication6notifyEP7QObjectP6QEvent (libdtkwidget.so.2)
                                             #31 0x00007f19d5f31849 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                             #32 0x00007f19d63da83c _ZN22QGuiApplicationPrivate17processEnterEventEPN29QWindowSystemInterfacePrivate10EnterEventE (libQt5Gui.so.5)
                                             #33 0x00007f19d63df976 _ZN22QGuiApplicationPrivate24processWindowSystemEventEPN29QWindowSystemInterfacePrivate17WindowSystemEventE (libQt5Gui.so.>
                                             #34 0x00007f19d63b8d9c _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Gui.so.5)
                                             #35 0x00007f19cf3edb8c n/a (libQt5XcbQpa.so.5)
                                             #36 0x00007f19d56537bf g_main_context_dispatch (libglib-2.0.so.0)
                                             #37 0x00007f19d5655739 n/a (libglib-2.0.so.0)
                                             #38 0x00007f19d565577e g_main_context_iteration (libglib-2.0.so.0)
                                             #39 0x00007f19d5f86969 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                             #40 0x00007f19d5f304dc _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                             #41 0x00007f19d5f38596 _ZN16QCoreApplication4execEv (libQt5Core.so.5)
                                             #42 0x0000555e4a5777fc main (lightdm-deepin-greeter)
                                             #43 0x00007f19d596ace3 __libc_start_main (libc.so.6)
                                             #44 0x0000555e4a577bce n/a (lightdm-deepin-greeter)
                                             
                                             Stack trace of thread 733:
                                             #0  0x00007f19d5a370d1 __poll (libc.so.6)
                                             #1  0x00007f19d5267630 n/a (libxcb.so.1)
                                             #2  0x00007f19d52692db xcb_wait_for_event (libxcb.so.1)
                                             #3  0x00007f19cf3ecb69 n/a (libQt5XcbQpa.so.5)
                                             #4  0x00007f19d5d7663c n/a (libQt5Core.so.5)
                                             #5  0x00007f19d46e3a92 start_thread (libpthread.so.0)
                                             #6  0x00007f19d5a41cd3 __clone (libc.so.6)
                                             
                                             Stack trace of thread 736:
                                             #0  0x00007f19d5a370d1 __poll (libc.so.6)
                                             #1  0x00007f19d5655690 n/a (libglib-2.0.so.0)
                                             #2  0x00007f19d565577e g_main_context_iteration (libglib-2.0.so.0)
                                             #3  0x00007f19d56557d2 n/a (libglib-2.0.so.0)
                                             #4  0x00007f19d5630c21 n/a (libglib-2.0.so.0)
                                             #5  0x00007f19d46e3a92 start_thread (libpthread.so.0)
                                             #6  0x00007f19d5a41cd3 __clone (libc.so.6)
                                             Stack trace of thread 737:
                                             #0  0x00007f19d5a370d1 __poll (libc.so.6)
                                             #1  0x00007f19d5655690 n/a (libglib-2.0.so.0)
                                             #2  0x00007f19d565577e g_main_context_iteration (libglib-2.0.so.0)
                                             #3  0x00007f19cdf5ebde n/a (libdconfsettings.so)
                                             #4  0x00007f19d5630c21 n/a (libglib-2.0.so.0)
                                             #5  0x00007f19d46e3a92 start_thread (libpthread.so.0)
                                             #6  0x00007f19d5a41cd3 __clone (libc.so.6)
                                             
                                             Stack trace of thread 738:
                                             #0  0x00007f19d5a370d1 __poll (libc.so.6)
                                             #1  0x00007f19d5655690 n/a (libglib-2.0.so.0)
                                             #2  0x00007f19d565577e g_main_context_iteration (libglib-2.0.so.0)
                                             #3  0x00007f19d5f86969 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                             #4  0x00007f19d5f304dc _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                             #5  0x00007f19d5d75239 _ZN7QThread4execEv (libQt5Core.so.5)
                                             #6  0x00007f19d623dba6 n/a (libQt5DBus.so.5)
                                             #7  0x00007f19d5d7663c n/a (libQt5Core.so.5)
                                             #8  0x00007f19d46e3a92 start_thread (libpthread.so.0)
                                             #9  0x00007f19d5a41cd3 __clone (libc.so.6)
                                             
                                             Stack trace of thread 740:
                                             #0  0x00007f19d5a370d1 __poll (libc.so.6)
                                             #1  0x00007f19d5655690 n/a (libglib-2.0.so.0)
                                             #2  0x00007f19d56566d2 g_main_loop_run (libglib-2.0.so.0)
                                             #3  0x00007f19d57c7568 n/a (libgio-2.0.so.0)
                                             #4  0x00007f19d5630c21 n/a (libglib-2.0.so.0)
                                             #5  0x00007f19d46e3a92 start_thread (libpthread.so.0)
                                             #6  0x00007f19d5a41cd3 __clone (libc.so.6)
                                             
                                             Stack trace of thread 763:
                                             #0  0x00007f19d5a370d1 __poll (libc.so.6)
                                             #1  0x00007f19d5267630 n/a (libxcb.so.1)
                                             #2  0x00007f19d52692db xcb_wait_for_event (libxcb.so.1)
                                             #3  0x00007f19d779d029 _XReadEvents (libX11.so.6)
                                             #4  0x00007f19d778bee1 XNextEvent (libX11.so.6)
                                             #5  0x00007f19d73bc268 _ZN3Dtk6Widget16DKeyboardMonitor6listenEP9_XDisplay (libdtkwidget.so.2)
                                             #6  0x00007f19d73bc3c9 _ZN3Dtk6Widget16DKeyboardMonitor3runEv (libdtkwidget.so.2)
                                             #7  0x00007f19d5d7663c n/a (libQt5Core.so.5)
                                             #8  0x00007f19d46e3a92 start_thread (libpthread.so.0)
                                             #9  0x00007f19d5a41cd3 __clone (libc.so.6)
                                             
                                             Stack trace of thread 764:
                                             #0  0x00007f19d5a370d1 __poll (libc.so.6)
                                             #1  0x00007f19d5267630 n/a (libxcb.so.1)
                                             #2  0x00007f19d52692db xcb_wait_for_event (libxcb.so.1)
                                             #3  0x00007f19d779d029 _XReadEvents (libX11.so.6)
                                             #4  0x00007f19d778bee1 XNextEvent (libX11.so.6)
                                             #5  0x0000555e4a5af0a8 n/a (lightdm-deepin-greeter)
                                             #6  0x0000555e4a5af209 n/a (lightdm-deepin-greeter)
                                             #7  0x00007f19d5d7663c n/a (libQt5Core.so.5)
                                             #8  0x00007f19d46e3a92 start_thread (libpthread.so.0)
                                             #9  0x00007f19d5a41cd3 __clone (libc.so.6)


```
## Enviroments:
Archlinux with deepin desktop environment

### Related package version
```
Name            : deepin-session-ui
Version         : 4.9.6-1
Description     : Deepin desktop-environment - Session UI module
Architecture    : x86_64
URL             : https://github.com/linuxdeepin/dde-session-ui
Licenses        : GPL3
Groups          : deepin
Provides        : lightdm-deepin-greeter  deepin-notifications
Depends On      : gsettings-qt  deepin-qt5integration  liblightdm-qt5  qt5-svg  deepin-daemon  xorg-server  deepin-control-center  startdde  xorg-xrandr  deepin-qt-dbus-factory
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : dde-workspace  dde-session-ui  deepin-notifications
Replaces        : dde-workspace  dde-session-ui  deepin-notifications
Installed Size  : 10.19 MiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Fri Apr 26 15:23:06 2019
Install Date    : Fri Apr 26 18:09:34 2019
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : SHA-256 Sum
```

Please tell me if more message needed.

**Comment by antechdesigns** [comment]
`

Apr 30 14:58:38 archdeepin systemd-coredump[841]: Process 797 (lightdm-deepin-) of user 620 dumped core.
                                                  
                                                  Stack trace of thread 797:
                                                  #0  0x000056059d305c87 n/a (lightdm-deepin-greeter)
                                                  #1  0x000056059d3081d2 n/a (lightdm-deepin-greeter)
                                                  #2  0x00007f9b72129af8 _ZN7QWidget5eventEP6QEvent (libQt5Widgets.so.5)
                                                  #3  0x00007f9b720e8da4 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                                  #4  0x00007f9b720f03c1 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                                  #5  0x00007f9b72b1cca9 _ZN3Dtk6Widget12DApplication6notifyEP7QObjectP6QEvent (libdtkwidget.so.2)
                                                  #6  0x00007f9b71639849 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                                  #7  0x00007f9b72126388 _ZN14QWidgetPrivate11show_helperEv (libQt5Widgets.so.5)
                                                  #8  0x00007f9b72129645 _ZN14QWidgetPrivate10setVisibleEb (libQt5Widgets.so.5)
                                                  #9  0x000056059d3136ea n/a (lightdm-deepin-greeter)
                                                  #10 0x000056059d3137a9 n/a (lightdm-deepin-greeter)
                                                  #11 0x00007f9b72129af8 _ZN7QWidget5eventEP6QEvent (libQt5Widgets.so.5)
                                                  #12 0x00007f9b721d171f _ZN6QFrame5eventEP6QEvent (libQt5Widgets.so.5)
                                                  #13 0x00007f9b720e8da4 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                                  #14 0x00007f9b720f03c1 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                                  #15 0x00007f9b72b1cca9 _ZN3Dtk6Widget12DApplication6notifyEP7QObjectP6QEvent (libdtkwidget.so.2)
                                                  #16 0x00007f9b71639849 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                                  #17 0x00007f9b72126388 _ZN14QWidgetPrivate11show_helperEv (libQt5Widgets.so.5)
                                                  #18 0x00007f9b72129645 _ZN14QWidgetPrivate10setVisibleEb (libQt5Widgets.so.5)
                                                  #19 0x000056059d33d31c n/a (lightdm-deepin-greeter)
                                                  #20 0x00007f9b72129af8 _ZN7QWidget5eventEP6QEvent (libQt5Widgets.so.5)
                                                  #21 0x00007f9b720e8da4 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                                  #22 0x00007f9b720f03c1 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                                  #23 0x00007f9b72b1cca9 _ZN3Dtk6Widget12DApplication6notifyEP7QObjectP6QEvent (libdtkwidget.so.2)
                                                  #24 0x00007f9b71639849 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                                  #25 0x00007f9b720ef3cd n/a (libQt5Widgets.so.5)
                                                  #26 0x00007f9b721433cc n/a (libQt5Widgets.so.5)
                                                  #27 0x00007f9b72147d01 n/a (libQt5Widgets.so.5)
                                                  #28 0x00007f9b720e8da4 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                                  #29 0x00007f9b720f03c1 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                                  #30 0x00007f9b72b1cca9 _ZN3Dtk6Widget12DApplication6notifyEP7QObjectP6QEvent (libdtkwidget.so.2)
                                                  #31 0x00007f9b71639849 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                                  #32 0x00007f9b71aea83c _ZN22QGuiApplicationPrivate17processEnterEventEPN29QWindowSystemInterfacePrivate10EnterEventE (libQt5Gui.so.5)
                                                  #33 0x00007f9b71aef976 _ZN22QGuiApplicationPrivate24processWindowSystemEventEPN29QWindowSystemInterfacePrivate17WindowSystemEventE (libQt5Gu>
                                                  #34 0x00007f9b71ac8d9c _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Gui.so.5)
                                                  #35 0x00007f9b6b4f5b8c n/a (libQt5XcbQpa.so.5)
                                                  #36 0x00007f9b70d4b7bf g_main_context_dispatch (libglib-2.0.so.0)
                                                  #37 0x00007f9b70d4d739 n/a (libglib-2.0.so.0)
                                                  #38 0x00007f9b70d4d77e g_main_context_iteration (libglib-2.0.so.0)
                                                  #39 0x00007f9b7168e969 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                                  #40 0x00007f9b716384dc _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                                  #41 0x00007f9b71640596 _ZN16QCoreApplication4execEv (libQt5Core.so.5)
                                                  #42 0x000056059d3017fc main (lightdm-deepin-greeter)
                                                  #43 0x00007f9b7106bce3 __libc_start_main (libc.so.6)
                                                  #44 0x000056059d301bce n/a (lightdm-deepin-greeter)
                                                  
                                                  Stack trace of thread 798:
                                                  #0  0x00007f9b711380d1 __poll (libc.so.6)
                                                  #1  0x00007f9b70954630 n/a (libxcb.so.1)
                                                  #2  0x00007f9b709562db xcb_wait_for_event (libxcb.so.1)
                                                  #3  0x00007f9b6b4f4b69 n/a (libQt5XcbQpa.so.5)
                                                  #4  0x00007f9b7147e63c n/a (libQt5Core.so.5)
                                                  #5  0x00007f9b6fda7a92 start_thread (libpthread.so.0)
                                                  #6  0x00007f9b71142cd3 __clone (libc.so.6)
                                                  
                                                  Stack trace of thread 801:
                                                  #0  0x00007f9b711380d1 __poll (libc.so.6)
                                                  #1  0x00007f9b70d4d690 n/a (libglib-2.0.so.0)
                                                  #2  0x00007f9b70d4e6d2 g_main_loop_run (libglib-2.0.so.0)
                                                  #3  0x00007f9b70ec3568 n/a (libgio-2.0.so.0)
                                                  #4  0x00007f9b70d28c21 n/a (libglib-2.0.so.0)
                                                  #5  0x00007f9b6fda7a92 start_thread (libpthread.so.0)
                                                  #6  0x00007f9b71142cd3 __clone (libc.so.6)
                                                  
                                                  Stack trace of thread 838:
                                                  #0  0x00007f9b711380d1 __poll (libc.so.6)
                                                  #1  0x00007f9b70954630 n/a (libxcb.so.1)
                                                  #2  0x00007f9b709562db xcb_wait_for_event (libxcb.so.1)
                                                  #3  0x00007f9b72ed1029 _XReadEvents (libX11.so.6)
                                                  #4  0x00007f9b72ebfee1 XNextEvent (libX11.so.6)
                                                  #5  0x00007f9b72ae5268 _ZN3Dtk6Widget16DKeyboardMonitor6listenEP9_XDisplay (libdtkwidget.so.2)
                                                  #6  0x00007f9b72ae53c9 _ZN3Dtk6Widget16DKeyboardMonitor3runEv (libdtkwidget.so.2)
                                                  #7  0x00007f9b7147e63c n/a (libQt5Core.so.5)
                                                  #8  0x00007f9b6fda7a92 start_thread (libpthread.so.0)
                                                  #9  0x00007f9b71142cd3 __clone (libc.so.6)
                                                  
                                                  Stack trace of thread 799:
                                                  #0  0x00007f9b711380d1 __poll (libc.so.6)
                                                  #1  0x00007f9b70d4d690 n/a (libglib-2.0.so.0)
                                                  #2  0x00007f9b70d4d77e g_main_context_iteration (libglib-2.0.so.0)
                                                  #3  0x00007f9b70d4d7d2 n/a (libglib-2.0.so.0)
                                                  #4  0x00007f9b70d28c21 n/a (libglib-2.0.so.0)
                                                  #5  0x00007f9b6fda7a92 start_thread (libpthread.so.0)
                                                  #6  0x00007f9b71142cd3 __clone (libc.so.6)
                                                  
                                                  Stack trace of thread 809:
                                                  #0  0x00007f9b711380d1 __poll (libc.so.6)
                                                  #1  0x00007f9b70d4d690 n/a (libglib-2.0.so.0)
                                                  #2  0x00007f9b70d4d77e g_main_context_iteration (libglib-2.0.so.0)
                                                  #3  0x00007f9b6a0b4bde n/a (libdconfsettings.so)
                                                  #4  0x00007f9b70d28c21 n/a (libglib-2.0.so.0)
                                                  #5  0x00007f9b6fda7a92 start_thread (libpthread.so.0)
                                                  #6  0x00007f9b71142cd3 __clone (libc.so.6)
                                                  
                                                  Stack trace of thread 839:
                                                  #0  0x00007f9b711380d1 __poll (libc.so.6)
                                                  #1  0x00007f9b70954630 n/a (libxcb.so.1)
                                                  #2  0x00007f9b709562db xcb_wait_for_event (libxcb.so.1)
                                                  #3  0x00007f9b72ed1029 _XReadEvents (libX11.so.6)
                                                  #4  0x00007f9b72ebfee1 XNextEvent (libX11.so.6)
                                                  #5  0x000056059d3390a8 n/a (lightdm-deepin-greeter)
                                                  #6  0x000056059d339209 n/a (lightdm-deepin-greeter)
                                                  #7  0x00007f9b7147e63c n/a (libQt5Core.so.5)
                                                  #8  0x00007f9b6fda7a92 start_thread (libpthread.so.0)
                                                  #9  0x00007f9b71142cd3 __clone (libc.so.6)
                                                  
                                                  Stack trace of thread 810:
                                                  #0  0x00007f9b711380d1 __poll (libc.so.6)
                                                  #1  0x00007f9b70d4d690 n/a (libglib-2.0.so.0)
                                                  #2  0x00007f9b70d4d77e g_main_context_iteration (libglib-2.0.so.0)
                                                  #3  0x00007f9b7168e969 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                                  #4  0x00007f9b716384dc _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                                  #5  0x00007f9b7147d239 _ZN7QThread4execEv (libQt5Core.so.5)
                                                  #6  0x00007f9b7194cba6 n/a (libQt5DBus.so.5)
                                                  #7  0x00007f9b7147e63c n/a (libQt5Core.so.5)
                                                  #8  0x00007f9b6fda7a92 start_thread (libpthread.so.0)
                                                  #9  0x00007f9b71142cd3 __clone (libc.so.6)
-- Subject: Process 797 (lightdm-deepin-) dumped core

`

**Comment by ValeTheVioletMote** [comment]
Does this produce the blank white screen? Because I've gotten that on Deepin 15.10. I had to install the gnome greeter as a temporary workaround.

**Comment by antechdesigns** [comment]
> Does this produce the blank white screen? Because I've gotten that on Deepin 15.10. I had to install the gnome greeter as a temporary workaround.

No, I can login & logout, it just dumps its core, however when you login there is no login sound, maybe that's whats causing it? and if you auto login everything is fine, sound & no dump ;)

White screen is something else I think, do you have an nvidia card?

**Comment by ValeTheVioletMote** [comment]
@antechdesigns I do. I did download the "closed-source" drivers per Deepin's installer....

My issue looks like [this](https://cdn.discordapp.com/attachments/511952566427451405/574353132000247851/DSC_0180.JPG)

**Comment by antechdesigns** [comment]
> @antechdesigns I do. I did download the "closed-source" drivers per Deepin's installer....
> 
> My issue looks like [this](https://cdn.discordapp.com/attachments/511952566427451405/574353132000247851/DSC_0180.JPG)

Here is the wallpaper fix for nvidia non-free drivers. Have a read through this:
https://antechdesigns.000webhostapp.com/wallpaper-fix-for-nvidia-non-free-driver/

Have a look in `var/cache/image-blur` for blank images, if you have any, then use the fix above.

**Comment by amit-gshe** [comment]
The latest updates(2019-5-10) seems fix this issue. Many thx for the developers.

**Comment by antechdesigns** [comment]
Why did this get closed? Its not fixed, still no login sound or shutdown sound now!!

`lightdm[727]: gkr-pam: unable to locate daemon control file`

**Comment by BLumia** [comment]
> @BLumia Why did this get closed? Its not fixed, still no login sound or shutdown sound now!!
> 
> `lightdm[727]: gkr-pam: unable to locate daemon control file`

@amit-gshe closed this issue a day ago, not me. It seems it works on @amit-gshe 's machine.

@antechdesigns Could you check if the update mentioned above fixed this issue?

**Comment by amit-gshe** [comment]
@antechdesigns After the latest update, the core dump logs disappear and no flash before entering the login screen. My office pc has no speaker so I'm not sure if the sound issue has been fixed.

**Comment by BLumia** [comment]
Thanks for the info. Since this issue is not related to the login/shutdown sound in any form, won't reopen this issue because that. Feel free to create another issue about that.

**Comment by antechdesigns** [comment]
> Thanks for the info. Since this issue is not related to the login/shutdown sound in any form, won't reopen this issue because that. Feel free to create another issue about that.

@BLumia I have better things to do than keep reporting the same bugs  https://github.com/linuxdeepin/developer-center/issues/1011

**Comment by BLumia** [comment]
> have better things to do than keep reporting the same bugs #1011

Then please track that issue at #1011 , thanks.

**Comment by SalahAdDin** [comment]
Can you re open this? I get this problem after the last _Manjaro_ update.

**Comment by justforlxz** [comment]
> Can you re open this? I get this problem after the last _Manjaro_ update.

Can you provide a coredump of lightdm-deepin-greeter?

**Comment by SalahAdDin** [comment]
I had to take a screenshot:
![WhatsApp Image 2020-11-09 at 14 00 52](https://user-images.githubusercontent.com/5034215/98534156-199b1f00-2295-11eb-9da3-5fc3b8dd7f50.jpeg)
