### ISSUE TITLE
dde-file-manager menuextensions 建议

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#1126]
深度文管扩展 menus.json
"MenuType": "EmptyArea" 会出现所有空白区域，包括桌面，如果是一个下一张壁纸的扩展，非桌面不需要显示这个菜单。建议增加 "MenuType": "Desktop"，使这个菜单只在桌面显示。
"Exec": 参数有时候需要传递当前目录的路径或者选中文件的路径，建议加通配符，%p 目录路径，%f 文件路径 来传递参数。

**Comment by BLumia** [comment]
哦这个已经有了，不过我没顾得上更新文档。

你只需要增加一项叫做 `"NotShownIn"` 的字段（后面跟一个array，里面是需要隐藏的位置）表示需要在哪里隐藏该选项即可。目前可供使用的值为 `Desktop` 和 `FileManager` 。

比如：

``` plain
"NotShowIn": ["FileManager"],
```

此时会仅在桌面显示而在文件管理器中隐藏。

**Comment by BLumia** [comment]
https://linuxdeepin.github.io/dde-file-manager/context-menu-ext-zh.html#json

文档已更新。

**Comment by sonichy** [comment]
可以了。
"Icon" : "computer" 参数是否能支持 QIcon::fromeTheme("computer")

**Comment by BLumia** [comment]
> "Icon" : "computer" 参数是否能支持 QIcon::fromeTheme("computer")

五一放完假我加一下（
也可以考虑另开一个 issue 提这个免得我忘了 😂
