### ISSUE TITLE
深度文管搜索 - 取消

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#1127]
点击搜索，稍等片刻，点击取消，返回原目录。
实际使用中不是这样的，不需要搜索结束，搜索到了想要的结果，即可中止搜索，然后对文件操作，操作完再返回原目录。
即，取消搜索后，不要自动返回原目录，而是手动返回原目录，搜索 - 停止 - 返回 三态按钮。

**Comment by BLumia** [comment]
我觉得终止搜索这个操作没必要啊，你本来就可以直接操作...

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
