### ISSUE TITLE
[右键]解压缩无效,缺少相应程序

### ISSUE THREAD

**Issue by naixzzz** [linuxdeepin/developer-center#1128]
Deepin发行版,我用的是有效
.但是啊ARCH+deepin DE,就无效
是缺少相应程序,未打包进去
我想知道Deepin发行版
右键解压缩是 什么程序
--

![d](https://user-images.githubusercontent.com/50109171/56900571-b558a600-6ac8-11e9-88db-6ddc9d741fdc.png)

**Comment by felixonmars** [comment]
deepin-file-manager 的可选依赖有写：
file-roller: for compress/decompress
