### ISSUE TITLE
深度看图图片信息没跟随窗口调整大小

### ISSUE THREAD

**Issue by ShuiHuo** [linuxdeepin/developer-center#1129]
## 缺陷描述
深度看图中的图片信息不随窗口大小变化而变化

## 复现步骤
描述可以重现缺陷（BUG）的操作步骤，以便我们复现缺陷并进行修复
复现步骤为:
1. 打开 文件管理器双击打开图片
2. 点击 鼠标右键 点击 图片信息
3. 移动鼠标将窗口调整大小
4. 缺陷 图片信息栏不会随着窗口的大小变化而变化 发生

## 期望行为
图片信息栏跟随窗口大小变化

## 截图

![深度截图_dde-desktop_20190430153148](https://user-images.githubusercontent.com/7471938/56957828-f01b1680-6b7a-11e9-9587-d7c24ca36b2c.png)
![深度截图_dde-desktop_20190430153243](https://user-images.githubusercontent.com/7471938/56957829-f0b3ad00-6b7a-11e9-9d9e-9c04f301fe4c.png)
视频链接：https://mega.nz/#!Qc0xVQQT!LkuQYfZeLuXm82zb3TyJHZFQnE1vfgZDga-_fNdZZeE
~~gif 太大了，webm 大法好~~

### 发行版以及版本
Linux Deepin 15.10
Arch Linux 20190430

### 相关的软件包版本
deepin-image-viewer v1.3 (1.3.13-1)

### 其他内容
视频中包含了一个 Arch Linux 下鼠标经过边框就会导致窗口大小调节的问题，但没经过测试

**Comment by sonichy** [comment]
又让我想起了安卓的 height=fill_parent
