### ISSUE TITLE
Cannot Change Primary Monitor on Arch Linux

### ISSUE THREAD

**Issue by thebeav26** [linuxdeepin/developer-center#113]
**My Specs**
Running Arch Linux x86_64
ASUS Laptop
ACER LED monitor

**Issue**
Can't set the secondary monitor, the ACER LED monitor, as my primary monitor. Deepin defaults to my laptop monitor being the primary. I cannot find a way to change it via the Control Center -> Display dialog.
(In fact, I also can't seem to find a way to move the monitors around to change their relative position. Not sure if this is even a feature or not.)

**Steps to Recreate**
Try to change the primary monitor via the control center.

**Comment by thebeav26** [comment]
Sorry, I didn't notice the little arrow on the "Custom Settings" menu. User error. Pay no attention to the man behind the curtain. I can now change my primary monitor and change the relative position of the monitors to each other.

**Comment by Iceyer** [comment]
@thebeav26  The Display Settings module of Control Center  is really not a good designed, it make people confused. however, we will improve it in the next major release. Thanks for you report.
