### ISSUE TITLE
Artifacts on the desktop

### ISSUE THREAD

**Issue by gokhanyildirimlar** [linuxdeepin/developer-center#1131]
## Describe the bug
Artifacts stay on the desktop when show desktop shortcut used.

## To Reproduce
Open a few windows and click show desktop button at the right below.

## Expected behavior
Must show the desktop clearly, without any artifact from running softwares.

## Video
http://sendvid.com/jeefbmsm

### Distro & Version
Linux Deepin 15.10

### Note: I freshly installed Deepin 15.10, didn't upgrade from previous versions.

**Comment by hualet** [comment]
It's not artifacts, it's a feature of Kwin called `Window Aperture` I think. 
Anyway it's been disabled by default, see https://github.com/linuxdeepin/dde-kwin/pull/51
