### ISSUE TITLE
Window preview does not work.

### ISSUE THREAD

**Issue by gokhanyildirimlar** [linuxdeepin/developer-center#1132]
## Describe the bug
Window preview does not work when pointer comes on it on the taskbar.

## To Reproduce
Open some windows and try to see the window preview from the taskbar.

## Expected behavior
Must show what's going on in a window.

## Video
http://sendvid.com/nhwvaejk

### Distro & Version
Linux Deepin 15.10

### Note: I freshly installed Deepin 15.10, didn't upgrade from previous versions.

**Comment by SiamSami** [comment]
Are you using `deepin-kwin`?

**Comment by gokhanyildirimlar** [comment]
@SiamSami, yes. Fresh installation of 15.10, so, obviously KWin.

**Comment by zccrs** [comment]
Fix in 15.10.1

**Comment by zccrs** [comment]
https://github.com/linuxdeepin/deepin-kwin/commit/923b3baa17f2f375e15bdb2eb6fdebc25183d659
https://github.com/linuxdeepin/dde-kwin/commit/42e18684f0ec58f21b7da04e193d6f20193c1a38
https://github.com/linuxdeepin/dde-kwin/commit/9516ab8a5757feda8bbdea7f23a2dcfe32dcf4c1

**Comment by gokhanyildirimlar** [comment]
@zccrs, It's not fixed properly.
![deepin-screen-recorder_Select area_20190516181809](https://user-images.githubusercontent.com/45146702/57865897-155c8580-7807-11e9-9dbd-277ae230024d.gif)

**Comment by SiamSami** [comment]
@gokhanyildirimlar Can I ask how did you set the time and date on the wallpaper? I know it's out of topic but can you still please tell me how you did that?

**Comment by gokhanyildirimlar** [comment]
> @gokhanyildirimlar Can I ask how did you set the time and date on the wallpaper? I know it's out of topic but can you still please tell me how you did that?

@SiamSami, it's **Gotham** widget from **Conky Manager**. Install **Conky Manager** and you'll have it by default.

**Comment by SiamSami** [comment]
@gokhanyildirimlar thanks!

**Comment by gokhanyildirimlar** [comment]
Should I open this again to make it visible again, @zccrs? Or you guys noted this and take care of this later?

**Comment by gokhanyildirimlar** [comment]
> Should I open this again to make it visible again, @zccrs? Or you guys noted this and take care of this later?

@BLumia

**Comment by gokhanyildirimlar** [comment]
It seems like it's working fine with the latest update. I am closing this if someone is not asking about it. Thanks, @BLumia @zccrs @justforlxz @hualet.
