### ISSUE TITLE
Cursor doesn't change while resizing windows.

### ISSUE THREAD

**Issue by gokhanyildirimlar** [linuxdeepin/developer-center#1134]
## Describe the bug
Some windows are not resizable, at least with the pointer. Using Alt+F8 shortcut works but makes things harder. And some of them can be resizable only from four corners and not sides.

**Correction: Windows are resizable but cursor doesn't change.**

## To Reproduce
Open some windows and try to resize them. Some of them work as it should(mostly Deepin applications) but some of them(like Telegram Desktop) are not resizable, some of them(like Deepin Movie) are resizable only from for corners.

## Expected behavior
All windows should be resizable from corners and sides.

**Correction: Cursor should change when it reached to sides and corners to let user that he/she can pull and resize.**

## Video
http://sendvid.com/bzwit9kt

### Distro & Version
Linux Deepin 15.10

### Note: I freshly installed Deepin 15.10, didn't upgrade from previous versions.

**Comment by BLumia** [comment]
Does Alt+RightMosueButton Drag on the window works? and what about just drag from the window border whatever the mouse cursor changed or not?

Not sure but it seems the cursor doesn't changed but probably you can still drag to resize the window.

cc @zccrs

**Comment by gokhanyildirimlar** [comment]
> Does Alt+RightMosueButton Drag on the window works?

It works, Alt+Right mouse button resizes windows.

> Not sure but it seems the cursor doesn't changed but probably you can still drag to resize the window.

You were right. I didn't try this before but it's resizable when I tried to pull from sides and corners but the cursor doesn't change.

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/1585#issuecomment-492041006

Should be fixed after `kwin-x11` upgrade to `5.8.6.8`. Please wait for the upcoming release :)

**Comment by zccrs** [comment]
fix in https://github.com/linuxdeepin/deepin-icon-theme/commit/362e0cd8856e7b63e2ae10a4165a82a92f580297

**Comment by aiamuzz** [comment]
> [linuxdeepin/internal-discussion#1585 (comment)](https://github.com/linuxdeepin/internal-discussion/issues/1585#issuecomment-492041006)
> 
> Should be fixed after `kwin-x11` upgrade to `5.8.6.8`. Please wait for the upcoming release :)

System updated to 15.10.2

```
kwin_x11 -v
kwin 5.8.6

```
`Alt+left mouse click` not dragging windows
`Alt+right mouse click` not resizing windows

**Comment by BLumia** [comment]
Alt drag is no longer enabled by default (since deepin-wm also get alt-drag disabled by default). You can enable it by edit your config file or via `systemsettings`(not officially supported by deepin), though.

**Comment by aiamuzz** [comment]
> Alt drag is no longer enabled by default (since deepin-wm also get alt-drag disabled by default). You can enable it by edit your config file or via `systemsettings`(not officially supported by deepin), though.

@BLumia ...

you mean like this ... is the path to the setting correct ... ?

![image](https://user-images.githubusercontent.com/3283676/61197346-f177cc00-a6f1-11e9-910a-561eb3860c82.png)

**Comment by BLumia** [comment]
> > Alt drag is no longer enabled by default (since deepin-wm also get alt-drag disabled by default). You can enable it by edit your config file or via `systemsettings`(not officially supported by deepin), though.
> 
> @BLumia ...
> 
> you mean like this ... is the path to the setting correct ... ?
> 
> ![image](https://user-images.githubusercontent.com/3283676/61197346-f177cc00-a6f1-11e9-910a-561eb3860c82.png)

No, via `systemsettings`, not gsettings. In the kwinrc config file there will be a section named `[MouseBindings]`  with these keys (I use <kbd>Meta</kdb> instead of <kbd>Alt</kbd> to avoid some shortcut conflict):

``` plain
CommandAll1=Move
CommandAll3=Resize
CommandAllKey=Meta
```

Do **not** touch the config file if you are not sure what you are doing. If you wish to do, figure it out first.

btw, it's offtopic, so please open another issue if you still have any question about using this feature.

**Comment by aiamuzz** [comment]
> > > Alt drag is no longer enabled by default (since deepin-wm also get alt-drag disabled by default). You can enable it by edit your config file or via `systemsettings`(not officially supported by deepin), though.
> > 
> > 
> > @BLumia ...
> > you mean like this ... is the path to the setting correct ... ?
> > ![image](https://user-images.githubusercontent.com/3283676/61197346-f177cc00-a6f1-11e9-910a-561eb3860c82.png)
> 
> No, via `systemsettings`, not gsettings. In the kwinrc config file there will be a section named `[MouseBindings]` with these keys (I use Meta instead of Alt to avoid some shortcut conflict):
> 
> ```
> CommandAll1=Move
> CommandAll3=Resize
> CommandAllKey=Meta
> ```
> 
> Do **not** touch the config file if you are not sure what you are doing. If you wish to do, figure it out first.
> 
> btw, it's off-topic, so please open another issue if you still have any question about using this feature.

thanks i modified the config file and i now have this functionality !!!

> Alt drag is no longer enabled by default (since deepin-wm also get alt-drag disabled by default). You can enable it by edit your config file or via `systemsettings`(not officially supported by deepin), though.

@BLumia ... do we have any app like 'Dconf Editor' to change systemSettings easily like we change gsettings through dconfEditor ?

#

Does the following mean this ... "cursor not showing up while resizing issue" ... is still not pushed as an update ?
```
kwin_x11 -v
kwin 5.8.6

```

**Comment by BLumia** [comment]
> do we have any app like 'Dconf Editor' to change systemSettings easily like we change gsettings through dconfEditor ?

You can tweak these kwin settings via `systemsettings`(yeah that's the package name), but you should know currently these feature are **not** officially supported from Deepin, if there are officially support, there will be an option in the control center, so although you can tweak some settings via `systemsettings`, some of the settings may not works(you cannot set dde's window decoration from systemsettings for example), so before you do any custom configure outside the Control Center, figure out what actually you are doing since it's unsupported.

> Does the following mean this ... "cursor not showing up while resizing issue" ... is still not pushed as an update ?
> 
> ```
> kwin_x11 -v
> kwin 5.8.6
> ```

https://github.com/linuxdeepin/developer-center/issues/1134#issuecomment-492484286

**Comment by aiamuzz** [comment]
> #1134 (comment)

does it mean ... we can expect this in the next round of updates ?

**Comment by BLumia** [comment]
> > #1134 (comment)
> 
> does it mean ... we can expect this in the next round of updates ?

We already fixed this issue in previous updates, or did you means the cursor won't change to resize icon cursor when you move your cursor to the edge of the window? If you still have this issue, feel free to open up a new issue.
