### ISSUE TITLE
[Feature Request] Move between images with mouse wheel

### ISSUE THREAD

**Issue by gokhanyildirimlar** [linuxdeepin/developer-center#1138]
Deepin Image Viewer zooms in and out with mouse wheel. This is the opposite of so many people's habit. Mouse wheel can be set to move between images and Ctrl+Mouse Wheel combo can zoom in and out.

Edit: It appears like some people want it to stay this way but it's not really comfortable. The default behavior can be like I wrote above(like in Windows 10) but Deepin can provide an option to change the behavior as Microsoft did in Photos app of Windows 10.

**Comment by keybreak** [comment]
https://github.com/linuxdeepin/developer-center/issues/963

**Comment by gokhanyildirimlar** [comment]
Side buttons would be good also but I don't agree with Ctrl+Mouse Wheel. Moving between images with mouse wheel is more intuitive since it's always being used for looking around. Ctrl+Mouse Wheel combo is better for zooming in and out because it's not often used in comparison to moving around. No one would want to hold the Ctrl button while looking for an image. When the image is found, we can hold the button and zoom in if we want to. Also, Ctrl+Mouse Wheel is being used to zoom in file manager, web pages, documents, etc. So, it'll be consistent this way.

**Comment by keybreak** [comment]
I don't know man, all image-viewers i had experience with, include web-based (and even stuff like google maps and such) always use just scroll for zoom...

**Comment by gokhanyildirimlar** [comment]
> I don't know man, all image-viewers i had experience with, include web-based (and even stuff like google maps and such) always use just scroll for zoom...

For example, Windows Image Viewer and XnView are using mouse wheel to move between images. Image Editors are different things. You open an image to edit, so it makes sense to zoom in and out. Image Editors should keep it that way.

But think about it, do you zoom or move between images more? The answer is obvious, we skip images more than zooming in. You don't look at every image closely, do you? So why press and hold Ctrl key all the time?

**Comment by keybreak** [comment]
> Windows Image Viewer
Maybe tweaked one?

On Windows 7 - 10 default image viewer without any tweaks is zooming on scroll.

> But think about it, do you zoom or move between images more? The answer is obvious, we skip images more than zooming in. You don't look at every image closely, do you? So why press and hold Ctrl key all the time?

I always use either mouse side buttons or left / right on keyboard.

**Comment by gokhanyildirimlar** [comment]
> On Windows 7 - 10 default image viewer without any tweaks is zooming on scroll.
> 

No, it doesn't. It moves around images with mouse wheel by default and Ctrl+mouse wheel zooms in and out. This way, you don't move your right hand between mouse and arrow keys or you don't hold Ctrl key all the time with your left hand. Move around with mouse wheel, use left Ctrl button when you want to zoom in or out. So simple and you don't even have to move your hands.

**Comment by aiamuzz** [comment]
scroll wheel is associated with zoom in - zooming out images ...

its so on google maps ...
its so on almost all popular graphic graphic softwares ... photoshop, coreldraw, inkscape, illustrator, picasa image viewer, etc ... so that is kind of a standard across image handling softwares ...

So there is no point arguing about it ... the best way forward for the deepin team would be to expose settings dialog and provide an option for users to choose 'Scroll Wheel' action between zoom and forward backward ...

**Comment by gokhanyildirimlar** [comment]
> scroll wheel is associated with zoom in - zooming out images ...
> 
> its so on google maps ...
> its so on almost all popular graphic graphic softwares ... photoshop, coreldraw, inkscape, illustrator, picasa image viewer, etc ... so that is kind of a standard across image handling softwares ...
> 
> So there is no point arguing about it ... the best way forward for the deepin team would be to expose settings dialog and provide an option for users to choose 'Scroll Wheel' action between zoom and forward backward ...

Yeah, that's what I want also. Making something "optional" is always good. But why do you put Google Maps and editors here? Google Maps is not an image viewer and editors are not image viewer also. You give an image to edit, so it makes sense to zoom in or out. And no, this is not the "standard" across image viewers, image editors yes, image viewers no. Does Deepin Image Viewer edit? No. At the same time, Ctrl+mouse wheel combo is associated with zoom in file managers, office softwares, browsers, etc. 

I'm repeating myself here but this is the easiest way to navigate between images. In your way, one should press and hold Ctrl key all the time or move a hand between arrow keys(forward/backward) and mouse(zoom). Why would one want it? Your one hand will be on the keyboard and other one on the mouse, right? Why change this? Navigate with mouse, use Ctrl key to zoom in or out. Microsoft handles it this way and in my opinion, this is the easiest way.

**Comment by keybreak** [comment]
@gokhanyildirimlar 
I can assure you as long time Windows user that it does, at least with any fresh installation of licensed & untweaked Windows.

It's easy to test in VirtualBox VM, just download Windows 10 and install it without activating for example.

@aiamuzz is right - optional is the best way, but still i'd say that default should be scroll for zoom, because it's used everywhere really.

**Comment by gokhanyildirimlar** [comment]
> @gokhanyildirimlar
> I can assure you as long time Windows user that it does, at least with any fresh installation of licensed & untweaked Windows.

It doesn't, it navigates between images and I am talking about Windows 10. The default behavior is not zooming in and out in Windows 10.

> @aiamuzz is right - optional is the best way, but still i'd say that default should be scroll for zoom, because it's used everywhere really.

Yes, like I said before also. This is the only solution.

**Comment by keybreak** [comment]
@gokhanyildirimlar 
Maybe it's hardware / mouse / drivers dependent?

I mean it's weird why we have it different, i have Windows 7 in front of me, and just tested fresh Windows 10 on VM - seriously both zooms in and out with just scroll out of the box for me...

**Comment by gokhanyildirimlar** [comment]
> @gokhanyildirimlar
> Maybe it's hardware / mouse / drivers dependent?
> 
> I mean it's weird why we have it different, i have Windows 7 in front of me, and just tested fresh Windows 10 on VM - seriously both zooms in and out with just scroll out of the box for me...

Yeah, this is weird but anyway, Microsoft lets us change the behavior. So, Deepin can do the same.

**Comment by aiamuzz** [comment]
hahahaha ... @gokhanyildirimlar ... when something is used at more places than others, it becomes an un said standard ... FYI scroll wheel and zoom has been so even on Picasa Image viewer ... 

the reason why zoom works better on a scroll wheel is because images are moments ... they capture the beauty of the place or the moment of the time it was taken ... so when one is viewing those images its natural for one to zooming on to them to enjoy the details, be it CG images, photos or even a scenery , it just makes the whole experience rich ...

when you look at an image and feel you need to view it closely ... 'scroll wheel' is the only hardware feedback that gives you the ease of doing it ... zooming IN and zooming OUT with a single hardware element ... and is effortless ... just point the area you want zoomed and use the scroll wheel to zoom in and out ... some image viewers even move the focus of the pointed area to the center of the screen and zoom it all the way ...

**so you see the lack of any other 'single' element of hardware cannot do this action more efficiently ... hence its preferred as a zoom option !!!**

so its pointless arguing on one's personal choices or habits ... if we look a little harder without a bias or prejudice to one's own habit ... you start to see why a certain thing has turned into a standard and why others have failed ...

**Comment by gokhanyildirimlar** [comment]
Stop the nonsense and lecturing! I don't say quit scrolling at all, @aiamuzz. If you didn't get the point, read what I wrote again. We don't zoom in and out to every picture and everybody navigates between pictures more than zooming in and out. So, there is no need to press and hold Ctrl key all the time or move your hand to arrow keys. So, stop repeating the same thing and tell me how does wheel zooming make things easier than Ctrl+wheel. Also, stop talking about standards. It's not a standard and it's not going to be because you are saying this. Picasa edits too, so it makes sense there, not in Deepin Image Viewer. You don't even say why is it easier, you just want it this way but think about the majority, not only yourself.

End of argument because this is not really an argument.

**Comment by aiamuzz** [comment]
> Stop the nonsense and lecturing! I don't say quit scrolling at all, @aiamuzz. If you didn't get the point, read what I wrote again. We don't zoom in and out to every picture and everybody navigates between pictures more than zooming in and out. So, there is no need to press and hold Ctrl key all the time or move your hand to arrow keys. So, stop repeating the same thing and tell me how does wheel zooming make things easier than Ctrl+wheel. Also, stop talking about standards. It's not a standard and it's not going to be because you are saying this. Picasa edits too, so it makes sense there, not in Deepin Image Viewer. You don't even say why is it easier, you just want it this way but think about the majority, not only yourself.
> 
> End of argument because this is not really an argument.

hahahahaha ... @gokhanyildirimlar  ... i am a little confused ... is your anger/irritation towards me or all those software's who for some reason found the scroll wheel fits the function of zooming in and out better and does so efficiently therefore implementing it ???

**Comment by gokhanyildirimlar** [comment]
Should I be irritated or angry with you or the default behavior of the mouse wheel on Deepin Image Viewer? What's really important with any of these to irritate me? Your behavior towards me is childish, so, I said: "Stop the nonsense and lecturing!". Is that why you think that way?

**Comment by aiamuzz** [comment]
well ... after agreeing that its best to have an option to do as per one's choise ... and you say this ... that seemed childish to me ...

> I'm repeating myself here but this is the easiest way to navigate between images.

and when another person presents an opposite view or a possible justification and you call him as lecturing ... sounds childish to me ...

cutting short to the issue at hand ... it will be resolved once deepin team decides to provide it as an option for the user to decide ... so its best you desist from posting your criticism and opinions if you aren't open to others do the same !!!

**Comment by gokhanyildirimlar** [comment]
[Standard](https://github.com/Bionus/imgbrd-grabber/issues/691)

**Comment by gokhanyildirimlar** [comment]
There is no need for further discussion since inactivity for long enough.
