### ISSUE TITLE
libqt5keychain1  install error

### ISSUE THREAD

**Issue by dance707** [linuxdeepin/developer-center#1140]
## Describe the bug
unable to install libqt5keychain1/lion 0.7.0-3 amd64

## To Reproduce
sudo apt-get install libqt5keychain1

## Expected behavior
installed
## Screenshots

![DeepinScreenshot_select-area_20190430145756](https://user-images.githubusercontent.com/11428397/56993995-1af57280-6b5b-11e9-869c-6bae002b4f0b.png)

### Distro & Version
deepin 15.10 stable

**Comment by hualet** [comment]
![image](https://user-images.githubusercontent.com/2023967/57004046-01593700-6bfe-11e9-8394-d26f8b1d711c.png)

I tried without any problem, give it another try?

**Comment by dance707** [comment]
I tried again here on 2 different computers, both give same error as my screen shot above.

**Comment by dance707** [comment]
I can download the package with web browser at http://packages.deepin.com/deepin/pool/main/q/qtkeychain/
I see that it is old dated 29-Oct-2016 libqt5keychain1_0.7.0-3_amd64  I see the current version is libqt5keychain1_0.7.0-4deepin_amd64.deb dated 15-feb-2019 but is uninstallable because the current version of libqt5core5a is 5.7.1 and needs >= 5.10.0
Is that why the error here ? ,and is it safe to install the manually downloaded libqt5keychain1_0.7.0-3_amd64 ?

**Comment by dance707** [comment]
15.11 update fixed issue
