### ISSUE TITLE
[Feature Request] 锁屏界面多次输错密码的设置项

### ISSUE THREAD

**Issue by CareF** [linuxdeepin/developer-center#1145]
在锁屏界面多次输错密码会触发一定时间后再试. 
是否可以添加设置项禁用这个功能, 或者把试错次数改多?

**Comment by wangjia12** [comment]
密码输入错误会锁定一段时间是制定的安全策略，暂时会保持这个策略。添加开关的需求已经记录，优先级低，后续根据用户反馈的实际情况看是否添加。感谢反馈！

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
