### ISSUE TITLE
桌面右键：增加 隐藏图标

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#1147]
有时候想看一个干净的桌面，特别是在看电影的时候，或者非第一个工作区不显示桌面图标也行。

**Comment by wangjia12** [comment]
试试打开桌面自动整理，能让桌面比之前干净一点。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
