### ISSUE TITLE
Blur the background on Deepin Terminal is broken.

### ISSUE THREAD

**Issue by gokhanyildirimlar** [linuxdeepin/developer-center#1148]
## Describe the bug
Background blurring does not work on Deepin Terminal.

## To Reproduce
Open a Deepin Terminal window and go to settings. Find the related option to blur the background and try to enable it.

## Expected behavior
Should blur the background of Deepin Terminal instantly.

## Video
http://sendvid.com/53i3iukk

### Distro & Version
Linux Deepin 15.10

### Note: I freshly installed Deepin 15.10, didn't upgrade from previous versions.

**Comment by BLumia** [comment]
#1133 :)
