### ISSUE TITLE
inconsistent theming in Deepin 15.3

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/developer-center#115]
I have tested all packages that are now available in Arch-testing and I am extremely pleased and impressed by the new features and the overall look and feel. Congratulations! :smile: :+1: 
My biggest criticism is the inconsistent theming and - above all - that some native deepin-applications now apparently have hard coded features and colors and are not following gtk-theming, meaning that the user cannot change the theming of the desktop and doesn't even have an option to use a dark look at all? This would contradict my understanding of a customizable Linux desktop completely.
Also, even as it is now, there are some obvious problems:
**deepin-filemanager** uses similar but not the same assets as deepin-gtk-theme for other windows:

![](http://imgur.com/9ZaB4G2l.png)

and the hightlight color of desktop dialogs are a different blue than the highlighting of deepin-gtk-theme:

![blues](https://cloud.githubusercontent.com/assets/11800714/17815892/94def634-6636-11e6-81b7-3efc674f178d.png)

So many people like to play with their desktops and themes, wallpapers, icons ... I am convinced that most of them will be very disappointed when they will be left with a fixed, pre-themed environment.

kind regards
oberon

**Comment by funilrys** [comment]
I'm already disappointed I'm a fan of arc-dark ;) !!

**Comment by fasheng** [comment]
Looks the hard coded color theme will be a problem later...
@Iceyer @zccrs @dragondjf

**Comment by oberon2007** [comment]
meanwhile the dark variant of deepin-gtk has arrived and I think it looks really great. But unfortunately deepin-filemanager is seriously staying bright ... :laughing:

**Comment by hualet** [comment]
It's a known issue that deepin-gtk-theme is not playing well with gtk2 windows, still working on it.
Also making our apps dark theme compatible is undergoing and planned to be working on 15.4 :)

**Comment by oberon2007** [comment]
That sounds promising :) Also deepin-gtk's dark variant seems to produce some theme parsing errors at the moment :wink: :
```
(startdde:607): Gtk-WARNING **: Theme parsing error: gtk-dark.css:2439:33: '-gtk-gradient' is not a valid color name
(startdde:607): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3923:35: 'linear-gradient' is not a valid color name
(polkit-gnome-authentication-agent-1:884): Gtk-WARNING **: Theme parsing error: gtk-dark.css:2439:33: '-gtk-gradient' is not a valid color name
(polkit-gnome-authentication-agent-1:884): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3923:35: 'linear-gradient' is not a valid color name
(pamac-tray:873): Gtk-WARNING **: Theme parsing error: gtk-dark.css:2439:33: '-gtk-gradient' is not a valid color name
(pamac-tray:873): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3923:35: 'linear-gradient' is not a valid color name
```

**Comment by Skillzore** [comment]
Well, the Deepin file manager still does not work with the dark theme. And the dark theme has this parsing error:
`Gtk-WARNING **: Theme parsing error: gtk.css:3601:22: 'none' is not a valid color name"`

**Comment by RocketLR** [comment]
I Seriously LOVE deepin. The Dark theme works so well with most programs except Deepin File manager and some other Deepin native programs. Only think that sucked a bit was my Surface keyboard would not pair.. so Im using a windows -> Deepin Synergy config. Way of topic but still.. Really love Deepin.

If you REALLY need a dark file browser, i suggest Konqueror.

**Comment by hualet** [comment]
Deepin file manager dark theme will be available soon, hopefully within next month.
