### ISSUE TITLE
Firefox [66.0.3 (64-bit)] stops receiving mouse input

### ISSUE THREAD

**Issue by ValeTheVioletMote** [linuxdeepin/developer-center#1150]
## Describe the bug
After a while of having Firefox open, it suddenly stops receiving mouse input. Firefox itself is not frozen and can still be used as normal. Keyboard shortcuts work fine.

I have switched out mice to no avail.

A newly opened firefox window detects mouse just fine, but the mouse is not restored to the original window.

Thus far, it appears to only occur on the _first_ window I create. My second window has not encountered an issue like this yet. I'll update this if that changes.

Strangely, and this is why I've come to the conclusion that it's likely a deepin issue: if I quickly move from one window to another, mouse input is, for a moment, detected, as you can see in the gif I'll provide.

## To Reproduce
Download Firefox Quantum 66.0.3 from the firefox website.
Extract Firefox Quantum.
Run Firefox Quantum from the Firefox binary.
Open some tabs and wait. If you've the same issue, mouse input will eventually stop being taken.

## Expected behavior
Expecting mouse input to always be taken.

## Screenshots
[Example](https://i.imgur.com/UX0UhIh.gifv)

### Distro & Version
Linux Deepin 15.10

### Related package version
Unsure of which it is. Here's my listing of what I presume contain the relevant one:
dde-api (3.18.3-1+comsta).
dde-control-center (4.10.2-1+comsta).
dde-daemon (3.27.1-1+comsta).
dde-desktop  (4.8.3-1+comsta).
dde-dock  (4.9.9-1+comsta).
dde-file-manager (4.8.3-1+comsta).
dde-launcher  (4.6.9-1+comsta).
deepin-menu (3.4.4-1+comsta).

**Comment by antechdesigns** [comment]
Not much to go on, If you run `firefox` from a terminal it should spit out some info when it happens, post it here if it does!?

**Comment by ValeTheVioletMote** [comment]
Will do. I'll close everything out in a moment and try to reproduce the issue with terminal running it.

Also, thus far, second window is fine when normally it would freeze up if it was the first window.

**Comment by hualet** [comment]
I encountered this situation for ~3 times, I thought it was an upstream issue :(

**Comment by ValeTheVioletMote** [comment]
It just happened to me again after a few hours. I don't know if it's relevant, but it wasn't until I had been focusing on another tool in the same monitor for a while that when I switched back, Firefox stopped polling that input.

Log:

```

(firefox:23784): Gtk-WARNING **: Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name

(/home/vale/Tools/firefox/firefox-bin:23860): Gtk-WARNING **: Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name

(/home/vale/Tools/firefox/firefox-bin:23938): Gtk-WARNING **: Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name

(/home/vale/Tools/firefox/firefox-bin:24046): Gtk-WARNING **: Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name

(/home/vale/Tools/firefox/firefox-bin:24098): Gtk-WARNING **: Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name

(/home/vale/Tools/firefox/firefox-bin:24182): Gtk-WARNING **: Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name

(/home/vale/Tools/firefox/firefox-bin:24372): Gtk-WARNING **: Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name

(/home/vale/Tools/firefox/firefox-bin:24444): Gtk-WARNING **: Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name

(/home/vale/Tools/firefox/firefox-bin:24569): Gtk-WARNING **: Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name

(/home/vale/Tools/firefox/firefox-bin:24808): Gtk-WARNING **: Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name

(/home/vale/Tools/firefox/firefox-bin:24851): Gtk-WARNING **: Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name
[Parent 23784, Gecko_IOThread] WARNING: pipe error (247): Connection reset by peer: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 357
[Parent 23784, Gecko_IOThread] WARNING: pipe error (193): Connection reset by peer: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 357

(/home/vale/Tools/firefox/firefox-bin:32103): Gtk-WARNING **: Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name

(/home/vale/Tools/firefox/firefox-bin:32103): dconf-WARNING **: Unable to open /var/lib/snapd/desktop/dconf/profile/user: Permission denied

(/home/vale/Tools/firefox/firefox-bin:32152): Gtk-WARNING **: Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name

(/home/vale/Tools/firefox/firefox-bin:32276): Gtk-WARNING **: Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name

(/home/vale/Tools/firefox/firefox-bin:32427): Gtk-WARNING **: Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name
```

**Comment by ValeTheVioletMote** [comment]
The theme parsing errors appear irrelevant. They unleash out the gate on startup. So, if it's anything, probably one of these:

```
[Parent 23784, Gecko_IOThread] WARNING: pipe error (247): Connection reset by peer: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 357
[Parent 23784, Gecko_IOThread] WARNING: pipe error (193): Connection reset by peer: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 357
(/home/vale/Tools/firefox/firefox-bin:32103): dconf-WARNING **: Unable to open /var/lib/snapd/desktop/dconf/profile/user: Permission denied
```

**Comment by ValeTheVioletMote** [comment]
Is there a DDE log I should upload, perhaps?

**Comment by hualet** [comment]
I still think this is an upstream issue since it does not restore even if I switch the WM when it firefox's not responsive.

**Comment by ValeTheVioletMote** [comment]
Meaning? I'm sorry, not sure what "upstream" is in this context. I'm somewhat new to linux

**Comment by ValeTheVioletMote** [comment]
The same issue occurred on latest FF on a Windows machine my friend has. Not a Deepin problem! It's Firefox!
