### ISSUE TITLE
[Feature Request] 整合xdroid

### ISSUE THREAD

**Issue by fwinac** [linuxdeepin/developer-center#1156]
使用了一段时间的xdroid，xdroid能够流畅的运行应用(网易蜗牛阅读)和游戏(率土之滨)，而且xdroid的cpu和内存占用都很低(远低于wine应用)。
但是现阶段xdroid有两个问题：
一、xdroid应用本身不论是在外观还是在功能上(退出一个应用所有应用就得退出)都有一些问题。
二、xdroid使用起来“不够流畅”，表现在:
  1、安装应用得进入xdroid，然而xdroid不论是应用商店还是自己选择apk都做的都不够好。而且进入xdroid安装应用本身就不够顺畅。
  2、安装应用后得进入xdroid打开，不会出现在系统启动器中。
如果deepin能够像安装deb一样顺畅的安装apk，这对于普通用户来说，deepin的可用性无疑极大的提高了。而且，和xdroid合作是个双赢的做法，deepin也不需要花费太多精力。
\- - - - - - - -  - - - - - - 一个普通用户的想法，不喜勿喷，承受能力低- - - - - - - - - - -  -  -  - - - -  -

**Comment by hualet** [comment]
敬请期待 :smirk:
