### ISSUE TITLE
Taskbar appears while watching a video in fullscreen mode on Deepin Movie.

### ISSUE THREAD

**Issue by gokhanyildirimlar** [linuxdeepin/developer-center#1157]
## Describe the bug
Taskbar appears while watching a video in fullscreen mode on Deepin Movie. It happens when mouse cursor comes on timeline 

## To Reproduce
Play a video with Deepin Movie and drag the mouse cursor on the timeline. 

## Expected behavior
Nothing interrupts the video.

## Video
http://sendvid.com/z60xpqdo

### Distro & Version
Linux Deepin 15.10(Fresh install)

### Related package version
deepin-movie v3.2.7( 3.2.22.1-1+comsta)

**Comment by hualet** [comment]
I submitted a PR to fix this, but I'm not sure if the fix is proper. @zccrs @sonald

**Comment by gokhanyildirimlar** [comment]
This is fixed with the latest update. So, I am closing this if someone is not asking about it. Thanks, @hualet.
