### ISSUE TITLE
Resizing lag on DDE File Manager

### ISSUE THREAD

**Issue by gokhanyildirimlar** [linuxdeepin/developer-center#1158]
## Describe the bug
Crowder the folder gets, struggles show up on DDE File Manager the most.

## To Reproduce
Open a crowded folder and try to resize DDE File Manager window.

## Expected behavior
Must resize smoothly since this is not a heavy task to accomplish.

## Video
http://sendvid.com/lxfa9j3h

### Distro & Version
Linux Deepin 15.10(Fresh installation)

### Related package version
dde-file-manager v4.8.3(4.8.3-1+comsta)

### Additional context
I haven't tried this on all applications but overall animation play degraded with KWin. Sometimes fps drops during animation play time. (I am not talking about resizing here, this is a general issue.)

**Comment by keybreak** [comment]
Sounds bad...

Since whole point was to kill bugs like this & improve performance:
https://github.com/linuxdeepin/developer-center/issues/890

**Comment by gokhanyildirimlar** [comment]
It seems like this one is fixed too with 15.10.1 release. It's not like in the video anymore. The issue can be closed as soon as developers or other users confirmed.

**Comment by BLumia** [comment]
We improved the file information fetching preformance for file view which solved this issue. Thanks for reporting :)
