### ISSUE TITLE
[archlinux] deepin-movie播放视频出错

### ISSUE THREAD

**Issue by kirigayakazushin** [linuxdeepin/developer-center#116]
![20160823212943](https://cloud.githubusercontent.com/assets/12298476/17893785/90952052-690c-11e6-94a0-932442484214.png)

所有视频格式都会这样。

**Comment by fasheng** [comment]
我这里测试播放mp4没有问题，看画面感觉和硬件加速有关
@hualet

**Comment by kirigayakazushin** [comment]
@fasheng  我重新安装了deepin-extra，能正常播放了。

**Comment by fasheng** [comment]
好的，硬件加速相关的问题可以直接提给qtav，这里先关闭了.
