### ISSUE TITLE
KWin window effects reset while moving large files.(When running generic kernel 5.1/5.1.1)

### ISSUE THREAD

**Issue by gokhanyildirimlar** [linuxdeepin/developer-center#1160]
## Describe the bug
While moving large folders, interface freezes for a few seconds and system notification arrives that says "KWin window manager desktop effects were restarted due to a graphics reset". This happens when running the newest generic kernel, not with stock Deepin kernel.

## To Reproduce
1. Move some large files around.
2. Keep doing daily things during this time
3. Wait for the interface freeze and notification.

## Expected behavior
Desktop effects shouldn't be restarted with no reason behind.

## Video
http://sendvid.com/csa6267h
**Time - around 2.55**

### Distro & Version
Linux Deepin 15.10(fresh installation), then installed a generic kernel that downloaded from [here](https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.1.1/).

### Related package version
dde-file-manager v4.8.3(4.8.3-1+comsta)

### Additional context
I don't know if this is related to DDE File Manager but this happens while moving files. At least, didn't happen before. Probably logs needed if developers can't reproduce it by themselves. I can provide necessary logs if you help me to get them.

**Note: You can close the issue if this is not an appropriate issue since it includes non-stock kernel.**

**Comment by gokhanyildirimlar** [comment]
I close this since this is not officially supported by Deepin and developers are pretty busy already. It's not necessary to look into something specific to my device.

**Comment by BLumia** [comment]
If i remember correctly, kwin do io sync in somewhere and @zccrs fixed this issue, but I'm not quite sure about details. Could you test if this issue still happens in most recent version of dde-kwin package? Thanks.

**Comment by gokhanyildirimlar** [comment]
> If i remember correctly, kwin do io sync in somewhere and @zccrs fixed this issue, but I'm not quite sure about details. Could you test if this issue still happens in most recent version of dde-kwin package? Thanks.

I tried with 15.10.2 and it still happens but it's not really important if it's specific to my hardware alone. Developers are pretty busy and there are much more important things to take care of, such as KWin, lion repository, default kernel, driver manager, etc. So, I am fine with the stock kernel because it doesn't do the same thing with newer generic kernels. Thanks @BLumia. :)
