### ISSUE TITLE
Lock screen doesn't lock all monitors

### ISSUE THREAD

**Issue by ikogan** [linuxdeepin/developer-center#1162]
## Describe the bug
When I lock my screen, either with the keyboard shortcut or choosing it from the shutdown menu, only 2 of 3 monitors lock. The other not only remains unlocked but also interactible. 

## To Reproduce
I'm not exactly sure what causes it but I _am_ using [autorandr](https://pypi.org/project/autorandr/) to automatically set my screen resolution since Deepin apparently doesn't properly auto-adjust after changing monitors. The lock screen problem persists even if I select my profile from the settings menu and even if I switch away from it (by selecting "Extend" for example, and then switching back. I can then unlock the screen by selecting one of the monitors using the mouse.

Curiously, if I position the cursor on the monitor that is not locked, the text entry field and photo disappear from both monitors.

## Expected behavior
When I lock the screen, I expect all screens to lock.

## Screenshots
I'm not sure how to take a screenshot when locked.

### Distro & Version
```
Fedora release 30 (Thirty)
Linux chislobog 5.0.9-301.fc30.x86_64 #1 SMP Tue Apr 23 23:57:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Installed Packages
Name         : deepin-desktop
Version      : 4.7.7
Release      : 2.fc30
Architecture : x86_64
Size         : 5.0 M
Source       : deepin-file-manager-4.7.7-2.fc30.src.rpm
Repository   : @System
From repo    : fedora
Summary      : Deepin desktop environment - desktop module
URL          : https://github.com/linuxdeepin/dde-file-manager
License      : GPLv3
Description  : Deepin desktop environment - desktop module.
```

**Comment by justforlxz** [comment]
Execute xrandr to see the output.

**Comment by ikogan** [comment]
Should I wait until I get the issue again? It hasn't happened in a bit.

**Comment by BLumia** [comment]
Feel free to let us know if that happend again :)
