### ISSUE TITLE
Full Screen Issue while playing Online Videos

### ISSUE THREAD

**Issue by eMSiBi** [linuxdeepin/developer-center#1164]
## Describe the bug

I just realized that when using full screen on any online video video player shows with little spaces on screen's right and down part. Tried different browser such as opera and chrome or different media player such youtube, Dailymotion, Vimeo, etc...

## To Reproduce

1. Go to any Internet browser on deepinOS (tried with opera and chrome)
2. Click on any video on the Internet (tried with youtube, Dailymotion, Vimeo)
3. Play video with full screen option
4. See spaces on right and down of screen

## Expected behavior
Real full screen while playing video

## Screenshots
![DeepinScreenshot_Opera_20190507214943](https://user-images.githubusercontent.com/33521853/57327895-a69d6f00-7118-11e9-833a-b738bd578fb2.png)
![DeepinScreenshot_Opera_20190507215629](https://user-images.githubusercontent.com/33521853/57327896-a69d6f00-7118-11e9-8a7d-91107511d6e6.png)

### Distro & Version
Linux Deepin 15.10 - DDE-Kwin

### Related package version
Package: opera - Version: 12.16.1860
Package: google-chrome-stable - Version 73.0.3683.86-1

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
