### ISSUE TITLE
Window sticking on resize after drag

### ISSUE THREAD

**Issue by Stoope** [linuxdeepin/developer-center#1166]
## Describe the bug
After drag window with double click on title bar cursor starts to resize window when moved out.
It happens on file manager, system monitor, deepin manual and may be some other deepin apps. For most of the apps(like deepin terminal, calendar and all external apps) this bug doesn't exist.
## To Reproduce
1. Double click on title bar
2. Move window
3. Key up mouse button
4. Try to move cursor out of window

## Expected behavior
Cursor should move out of window

## Screenshots
![deepin-screen-recorder_Select area_20190509192736](https://user-images.githubusercontent.com/17287557/57470279-1a628780-7291-11e9-826b-a4dc9393f5e2.gif)

### Distro & Version
Arch linux

### Related package version
dde-file-manager 1.8.2
deepin-system-monitor 1.4.2

### Additional context
It happened before deepin-kwin and happens after

**Comment by zhtengw** [comment]
I can reproduce this issue with all the window-resizable packages built with dtkwidget ( such as deepin-draw, deepin-manual, deepin-image-viewer, deepin-editor ).

**Comment by BLumia** [comment]
Assoc: https://github.com/linuxdeepin/developer-center/issues/641 https://github.com/linuxdeepin/developer-center/issues/1086

**Comment by zhtengw** [comment]
When update qt5dxcb-plugin to version 1.2.1, the window won't sticking on resize now.
But It seems that this issue has not been fixed completely: 
![深度录屏_dde-desktop_20190523180515](https://user-images.githubusercontent.com/3148769/58245013-667bf480-7d86-11e9-9f83-f0f11edf4160.gif)

As shows above, first I resize the window on its top edge. Then when I try to resize on its right side, the mouse pointer shows just as it's on the top edge. I should do a click to make the mouse normal back before I can perform another resizing.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
