### ISSUE TITLE
kwin: keyboard shortcuts

### ISSUE THREAD

**Issue by Stoope** [linuxdeepin/developer-center#1167]
## Describe the bug
After switching to kwin some keyboard shortcuts  (super+a, super+w, super+s) works only on English (us) keyboard layout, other work fine.

## To Reproduce
1. Add Russian (ru) keyboard layout
2. Switch to ru keyboard layout
3. Try to use keyboard shortcuts (super+a, super+w, super+s)

## Expected behavior
super+a, super+w, super+s should works on any keyboard layout

### Distro & Version
Arch linux

### Related package version
deepin-kwin 0.0.6-1

**Comment by gokhanyildirimlar** [comment]
Work fine with Turkish, it may be related to the alphabet. Nice catch.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
