### ISSUE TITLE
kwin: windows arrangement

### ISSUE THREAD

**Issue by Stoope** [linuxdeepin/developer-center#1168]
## Describe the bug
Deepin apps doesn't fill all space

## To Reproduce
![deepin-screen-recorder_dde-desktop_20190510000404](https://user-images.githubusercontent.com/17287557/57486696-485ac280-72b7-11e9-9fc2-5bbeff616784.gif)

## Expected behavior
Deepin apps work like other (inkscape in this example)

### Distro & Version
Arch linux

### Related package version
deepin-kwin 0.0.6-1

**Comment by gokhanyildirimlar** [comment]
https://github.com/linuxdeepin/developer-center/issues/1136

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
