### ISSUE TITLE
kwin: touch bar gestures

### ISSUE THREAD

**Issue by Stoope** [linuxdeepin/developer-center#1169]
## Describe the bug
After switching to kwin touch bar gestures (three finger swipe left/right/top ) don't work with any window, for example it works with deepin terminal but doesn't work with deepin file manager or chrome

## Expected behavior
Touch bar gestures work with any window

## Screenshots
![deepin-screen-recorder_dde-desktop_20190510001220](https://user-images.githubusercontent.com/17287557/57487191-98865480-72b8-11e9-8de7-7e0fd255fa25.gif)

### Distro & Version
Arch linux

### Related package version
deepin-kwin 0.0.6-1

**Comment by gokhanyildirimlar** [comment]
https://github.com/linuxdeepin/developer-center/issues/1136

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
