### ISSUE TITLE
deepin-emacs

### ISSUE THREAD

**Issue by PlumpMath** [linuxdeepin/developer-center#117]
set-face-attribute: Font not available: #<font-spec nil nil ~~blah~blah~~ nil nil nil nil nil 12.0 nil nil nil ((:name . "~~blah~blah~~" ) (user-spec . "~~blah~blah~~" ))>

my linux not deepin (so downloading that.) 
how can I execute/init-setup deepin-emacs?

**Comment by hualet** [comment]
It's just complaining that the font is not installed on your machine,  go get the font installed and it'll be fine.
