### ISSUE TITLE
[Feature Request]深度截图增加贴图功能

### ISSUE THREAD

**Issue by PikachuHy** [linuxdeepin/developer-center#1174]
最近发现Snipaste的贴图挺好用的，深度截图没有，就简单写了几行代码。
PR: https://github.com/linuxdeepin/deepin-screenshot/pull/65

当前的功能
- 图片的窗口支持拖动，无边框
- 支持对图片的简单操作：复制到剪贴板，保存到文件，缩放。

最后的效果

![在这里插入图片描述](https://img-blog.csdnimg.cn/20190511205929177.png)

未完成的功能
- 国际化
- 贴图按钮的图标

可能的缺陷
因为深度截图是单例，我在贴图前把`com.deepin.Screenshot`注销了，这样才能重新起一个深度截图，其他部分不影响。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
