### ISSUE TITLE
"Used space" bar doesn't appear for ext4 formatted partitions 

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#1175]
## Describe the bug
Deepin file manager doesn't show the "used space" bar for ext4 formatted partitions.

## Expected behavior

It should show that bar for all partitions.
## Screenshots

![DeepinScreenshot_dde-desktop_20190511234103](https://user-images.githubusercontent.com/33563064/57573249-9d790e80-7446-11e9-8355-cd2ef537fdcd.png)

### Distro & Version

Distro: Arch Linux (With latest updates)
### Related package version

dde-file-manager v1.8.2

**Comment by keybreak** [comment]
Duplicate: https://github.com/linuxdeepin/developer-center/issues/998 - it's not ext4, just longer disk name

**Comment by SiamSami** [comment]
Since it's a duplicate, I am closing it.
