### ISSUE TITLE
dde-file-manager: dde-dock-plugins/disk-mount/diskpluginitem.h: constants.h not found

### ISSUE THREAD

**Issue by romildo** [linuxdeepin/developer-center#1176]
## Describe the bug

When building `dde-file-manager-4.8.4` on NixOS I am getting the error:

```
In file included from diskpluginitem.cpp:25:0:
diskpluginitem.h:28:10: fatal error: constants.h: No such file or directory
 #include "constants.h"
          ^~~~~~~~~~~~~
```

Is `constants.h` missing there? Where should it be from?

**Comment by BLumia** [comment]
The `constants.h` it use is a part of `dde-dock`, should be in the `dde-dock` development package. I'm not fimilar with NixOS so I don't know where it should be in your distro :/

by the way, `dde-dock-plugin` is a componment/plugin for `dde-dock` to indicate the mounted devices/partition. If you are just planned to build the file manager, you will not need this plugin.

**Comment by romildo** [comment]
It is clear now. Thanks.
