### ISSUE TITLE
can't resize some applications with deepin-kwin

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#1178]
We can't resize some applications with deepin-kwin, can you fix that?

Thanks in advance.

**Comment by SiamSami** [comment]
can anyone fix it?

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/developer-center/issues/1134

Seems already fixed, closing. Let us know if you still have this issue.

**Comment by keybreak** [comment]
@BLumia 
I think he means not cursor, but actual resize on Arch Deepin with deepin-kwin, example:
**pamac** (GTK), compared to qt / Deepin programs - actual resize area seems to be super-small, so it is possible to resize, but very very hard.

I've tested with VirtualBox VM, so not sure if hardware have same problems...But still

**Comment by SiamSami** [comment]
@keybreak  Yes, I am talking about the resize area. It's super small.
On KDE, we can go to settings and change the border size which helps us to resize the windows very easily.

**Comment by keybreak** [comment]
@BLumia 
Yeah, so following all this information i think that goal is to make default resizing area closer to what we had in deepin-mutter + solve issue that left, bottom & left/bottom areas are not resizable at all on GTK programs.

**Comment by es20490446e** [comment]
[Screencast](https://youtu.be/9O6v6Slb_x8)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
