### ISSUE TITLE
deepin-kwin switches to an application automatically.

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#1179]
## Describe the bug

deepin-kwin switches another program automatically.

## Expected behavior

It should not switch to that program.
## Screenshots

![deepin-screen-recorder_Select area_20190512095100](https://user-images.githubusercontent.com/33563064/57577549-89abc780-749b-11e9-824d-3141f12c7b78.gif)

## Enviroments:
Deepin DE 15.9
### Distro & Version

Archlinux (Latest)
### Related package version

deepin-kwin v0.0.6-1

**Comment by BLumia** [comment]
Thanks for reporting, did you click the preview thumbnail? btw, are u sure you are using DDE 15.9? consider upgrade first if you sure you are using 15.9.

**Comment by SiamSami** [comment]
> Thanks for reporting, did you click the preview thumbnail? btw, are u sure you are using DDE 15.9? consider upgrade first if you sure you are using 15.9.

No, I didn't click on the preview thumbnail. I am not sure about the version of DDE.
To make it clear, I have the latest version. I don't see any update of DDE in pamac.

**Comment by BLumia** [comment]
Can be reproduced on my machine.

**Comment by zccrs** [comment]
This is the window preview feature, is not a bug.

**Comment by BLumia** [comment]
It probably is a bug, feel free to close it if you still think it's a feature

### Steps to reproduce:

 1. Open a new window and minimize the window.
 2. Hover on the dde-dock icon and then hover the preview thumbnail.
 3. After window shows up, move the mouse cursor outside the preview thumbnail.

### Expected:

 The previewed window should not bring up to front.

**Comment by zccrs** [comment]
https://github.com/linuxdeepin/deepin-kwin/pull/18

**Comment by SiamSami** [comment]
Seems to be fixed...
