### ISSUE TITLE
[ArchLinux]安装deepin依赖问题

### ISSUE THREAD

**Issue by SunRain** [linuxdeepin/developer-center#118]
出在最新版(2016-0825)，似乎打包依赖有问题，安装时候提示如下:
 有 2 个软件包可提供 libegl ：
:: 软件库 extra
   1) mesa-libgl  2) nvidia-libgl

按照archlinux的wiki上的说明，nvidia-libgl是只适用于新版的nv显卡的驱动，应该加上nv的老板驱动支持，即nvidia-304xx依赖。希望能尽快修正此问题。

**Comment by CarloQ** [comment]
这个应该是 Xorg 的依赖吧～

**Comment by felixonmars** [comment]
这个应当已经解决了，新的 nvidia-304xx-libgl 已经提供了 libegl、libgles。

**Comment by CarloQ** [comment]
@felixonmars  我是被打脸了咩

**Comment by felixonmars** [comment]
@CarloQ 没，我忘记在这里回复，你提醒了我 :P
