### ISSUE TITLE
[deepin system monitor] display CPU temperature

### ISSUE THREAD

**Issue by denisoster** [linuxdeepin/developer-center#1180]
Please add a display of the CPU temperature and the number of fan speeds.

**Comment by alexwender1** [comment]
Excelent idea.

I have one more suggestion: It is important for System Monitor to display the speed (in GHz) oscillation of the CPU - as does the Windows Task Manager.

![Captura de Tela_selecionar área_20190512130148](https://user-images.githubusercontent.com/45263160/57584824-2e3b0300-74b6-11e9-9363-706f9860198d.png)

**Comment by alexwender1** [comment]
I ask you to check the application icon. The icon of the application in the store is different from the one displayed on the launcher after installation.

In the store:
![Captura de Tela_selecionar área_20190512130605](https://user-images.githubusercontent.com/45263160/57584931-8b838400-74b7-11e9-9d45-c2e1e30354cd.png)

In the launcher:
![Captura de Tela_selecionar área_20190512130639](https://user-images.githubusercontent.com/45263160/57584937-9807dc80-74b7-11e9-8635-1d15255b49fe.png)

**Comment by wangjia12** [comment]
Thank you for your suggestion, it has been recorded that any changes will be notified to you here.
We will solve the problem of icons as soon as possible.

**Comment by nmatavka** [comment]
Agreed, a temperature stat would be *very* helpful.  Gratias tibi ago.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
