### ISSUE TITLE
deepin-kwin: doesn't show window when hovering on the dock

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#1181]
## Describe the bug

If we hover over an open application on the dock, then we don't get the preview of the opened window.
## To Reproduce

1. Open an application.
2. Minimize it.
3. Hover over it from the dock (dde-dock).
4. There is no window preview.
## Expected behavior

It should show a preview of the opened window.

## Screenshots

![deepin-screen-recorder_Select area_20190512191641](https://user-images.githubusercontent.com/33563064/57582887-3d3ca800-74ec-11e9-923b-b39b11c1f679.gif)

## Enviroments:
Deepin DE 15.9

### Distro & Version

Distro: Archlinux
### Related package version

deepin-kwin v0.0.6-1

**Comment by gokhanyildirimlar** [comment]
https://github.com/linuxdeepin/developer-center/issues/1132

**Comment by SiamSami** [comment]
@zccrs when will it get fixed?

**Comment by zccrs** [comment]
> @zccrs when will it get fixed?

In dde-kwin 0.0.7

**Comment by SiamSami** [comment]
@zccrs The bug only appears if the window is minimized.

**Comment by SiamSami** [comment]
@zccrs The problem is within `kwin` itself. I just installed KDE plasma but I still this glitch. (Yes, I was running `kwin` then). We either have to tell the developers of KDE about it or we have to configure `dde-kwin` to fix it.

**Comment by SiamSami** [comment]
Here is what I found, we can fix it in KDE. In KDE, we have to go to settings>Display and monitor>compositor>Change the value of "keep windows thumbnail" to "Always".

**Comment by SiamSami** [comment]
It's fixed now. Closing.
