### ISSUE TITLE
come back to debian unstable ,please

### ISSUE THREAD

**Issue by chemel9** [linuxdeepin/developer-center#1185]
i would like to give a suggestion to deepin.
come back to debian unstable , please
debian stable has old packages. 
and I think everyone likes, have the latest version of the software.

**Comment by aiamuzz** [comment]
@chemel9 ... hmmmmmm ... i guess this one step will be very hard to take back ... besides its just launched recently ...

**Comment by BLumia** [comment]
[Don't suffer from Shiny New Stuff Syndrome](https://wiki.debian.org/DontBreakDebian#Don.27t_suffer_from_Shiny_New_Stuff_Syndrome) from Debian wiki.

Debian will also release a new major version (buster) later this year and deepin will also follow-up :)
