### ISSUE TITLE
Disable hidden data file creation

### ISSUE THREAD

**Issue by Modelmat** [linuxdeepin/developer-center#1186]
## Describe the bug
When using the dde-file-manager, the `.__deepin.{db,lft,num}` get created. These remain behind and pollute file directories even after removing deepin entirely.
This should be able to be disabled.

## To Reproduce
1. Open a writeable directory in dde-file-manager.
2. Type `ls -a` in a terminal in that directory
3. Files `.__deepin.db` `.__deepin.lft` and `.__deepin.num` appear.

## Expected behavior
N/A

### Distro & Version
Arch Linux

### Related package version
deepin-file-manager 1:4.8.4.1-1

**Comment by BLumia** [comment]
FYI these file will only be created at your local mounted partition, not every writeable folders. `.__deepin.{lft,num}` should also no longer be used now, only `.__deepin.db` will be created at root of your local mounted partition. 

The file manager requires these file which store the tagging information and quick search index data to work. Although dde-file-manager can be used without these features which provided by `deepin-anything` (with `DISABLE_ANYTHING` build option enabled), it may still create that file, though.

We currently don't have very enough time to do that code clean-up, but any patches about this request can be accepted so patches are welcome if anyone would like to help :)

**Comment by Modelmat** [comment]
Could these files not be stored in a `~/.config/dde-file-manager/tags.db` file.
I'll take a look at the code, though I'm not familiar with the code nor much of the language.

**Comment by BLumia** [comment]
These data are not stored in that location, since the volume name / mount point path can be changed so the data we saved can be no longer valid for using.

**Comment by Modelmat** [comment]
Good point. [Apparently, Dolphin stores tag data via xattr](https://www.reddit.com/r/kde/comments/3t4b6f/permanence_of_dolphin_file_commentstags/) but that has caveats.
Also I noticed there's `.__main.db`, so that'd be good to disable too.

**Comment by BLumia** [comment]
DFM tagging feature also support partition type like NTFS so xattr was considered but not choosed from the beginning of the feature development. I haven't checked if these `.db` file will be created even if we are using a file manager without deepin-anything support.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
