### ISSUE TITLE
Dead zone when dock position is left

### ISSUE THREAD

**Issue by Stoope** [linuxdeepin/developer-center#1187]
Dock has 1-2 width dead zone from the left screen edge
![deepin-screen-recorder_Select area_20190514134930](https://user-images.githubusercontent.com/17287557/57692480-8b1df100-764f-11e9-8bf9-d9630a3c51aa.gif)
Manjaro Linux
deepin-dock 4.9.9-1

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
