### ISSUE TITLE
[archlinux]在高效模式下左上角出现fcitx

### ISSUE THREAD

**Issue by kirigayakazushin** [linuxdeepin/developer-center#119]
![20160828133658](https://cloud.githubusercontent.com/assets/12298476/18031861/64aa064c-6cb8-11e6-827e-c3b11239984a.png)

只有高效模式会出现，切换回时尚模式就正常。在高效模式下右键任务区的fcitx，就会恢复正常。

**Comment by sbwtw** [comment]
已知问题
