### ISSUE TITLE
dde-dock 插件版本检查

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#1193]
插件无法加载的时候看不到插件版本，希望增加一个命令行检查：
dde-dock -version
dde-dock version: 1.5
datetime plugin version: 1.5, loaded
HTYCMDU plugin version: 1.4, unload
HTYWeather plugin version: 1.4, unload

**Comment by felixonmars** [comment]
unload -> ignored 可能好一些

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
