### ISSUE TITLE
[Feature Request] Bluetooth Quick Control from Task-bar

### ISSUE THREAD

**Issue by tanvir-10** [linuxdeepin/developer-center#1195]
If Bluetooth is turned on from settings than a quick Bluetooth access button (similar to Wireless Network button) will be shown. As currently there is no way of telling if my BT is on or paired with any other device without going into Settings > Bluetooth >  Bluetooth-Device-Name.

![image](https://user-images.githubusercontent.com/47321309/57973837-b5193f80-79d0-11e9-89e2-4bb14c4c8714.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
