### ISSUE TITLE
Keyboard does not work for "Save As" inside Chrome

### ISSUE THREAD

**Issue by sdlins** [linuxdeepin/developer-center#1197]
## Describe the bug
When I try to save some file via Google Chrome, the window "Save As" is open, the filename is selected but when I type nothing changes, the filename remains just selected. Tab key does not work too, no effect, it only used to play a *beep* (like a terminal), but after update deepin to 15.10.1, tab does not make sounds anymore.

Note: Firefox "Save As..." has no problem. Everything works as expected.

I am not sure this issue could be in `google-chrome` or in a way of `dde-desktop` deals with it, this is why I am opening this issue.

## To Reproduce
1) Open Google Chrome (73.0.3683.86 (official) 64 bits)
2) Right click in any link > "Save As..."
3) When "Save As..." open, try to type;

### Distro & Version
Linux Deepin 15.10.1

### Related package version
dde-desktop 4.8.4
Google Chrome (73.0.3683.86 (official) 64 bits)

### Additional context
Using `wmctrl` tfo see info about open windows, it shows the list below. It seems `dde-desktop` is the resposible to show "Save As..." (5th result: `0x020000d8  0 dde-desktop.dde-desktop          N/A Salvar arquivo`). Should it not to be `deepin-file-manager`? Not sure.
```
sdlins@rotadosbits:~$ wmctrl -lx
0x01a00009  0 dde-dock.dde-dock             N/A DDE Dock
0x02000005  0 dde-desktop.dde-desktop          N/A dde-desktop
0x03a00001  0 google-chrome.Google-chrome  rotadosbits Unidade V - Pluralidade Cultural, Educação e Políticas ... - Google Chrome
0x04600003  0 deepin-terminal.Deepin-terminal  rotadosbits sdlins@rotadosbits: ~ - Terminal
0x020000d8  0 dde-desktop.dde-desktop          N/A Salvar arquivo
0x03800050  0 google-chrome-stable.Google-chrome-stable  rotadosbits Salvar arquivo
```

**Comment by BLumia** [comment]
It seems the open file dialog doesn't get focus when it shows up.

**Comment by sdlins** [comment]
The same problem for Save As... in VSCode.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
