### ISSUE TITLE
功能需求：希望DTK应用程序风格（主题）可定制并统一GTK、DTK、QT应用样式

### ISSUE THREAD

**Issue by xiaoc-arch** [linuxdeepin/developer-center#1198]
目前deepin-gtk-theme已经大致“统一”（看起来差不多）gtk，qt，dtk应用。但是目前dtk应用窗口边框线不透明（关闭特效看是白灰边）；打开特效时窗口圆角像素太大导致dtk应用贴靠屏幕两侧时能看到四角的圆角空隙，不美观；全屏时不存在以上情况。可不可以考虑以下方案：

1、将dtk应用设置为窗口无边框，像vscode设置成无边框那样全部直角，同时改deepin-gtk-theme，达到gtk，qt，dtk应用样式“统一”；
2、将dtk应用窗口圆角像素缩小到mac那样，同时改deepin-gtk-theme达到应用样式“统一”；
3、增加特效功能，当dtk、qt、gtk应用贴靠屏幕左右两侧时自动变为直角（这样就看不到圆角空隙），同时用kde应用替换归档管理器和文档查看器两个默认gtk应用（这两个应用窗口下边两角是直角，上边两角又是圆角，不协调）；
4、dtk是基于qt的，也可以考虑提供统一接口让kde窗口主题统一qt和dtk，gtk应用

**Comment by BLumia** [comment]
其实新设计的圆角比现在还大。。。。。。

很大可能是不会默认调小的，但看看是不是考虑支持基础的主题定制？ @wangjia12

**Comment by xiaoc-arch** [comment]
"新设计的圆角比现在还大“？是要搞手机操作系统吗？pc端再大真的丑了

**Comment by BLumia** [comment]
请保证您在创建 Issue 的时候，一个 Issue 专注讨论一件事情...这个 Issue 我理解为你请求 DTK 应用程序风格（主题）可定制的特性请求，但你补充的描述和标题并没有什么关系..

**Comment by keybreak** [comment]
I agree with @xiaoc-arch unified UI to rule the World! :)

And even more importantly: https://github.com/linuxdeepin/developer-center/issues/613
On Arch / Manjaro right now it's really annoying to have some random open / save dialog styles on non-qt programs...

**Comment by BLumia** [comment]
> On Arch / Manjaro right now it's really annoying to have some random open / save dialog styles dialog on non-qt programs, instead of beautiful Deepin qt-style...

https://github.com/linuxdeepin/dde-file-dialog-gtk/tree/gtk3

**Comment by keybreak** [comment]
@BLumia 
It means it's ready, but just have to be repacked for Arch?
What's up with @felixonmars, still having health problems? :crying_cat_face:

**Comment by fwinac** [comment]
我赞成这个提议。现在自带应用的程序风格，确实和第三方程序的风格不一样。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
