### ISSUE TITLE
FAST FW150US USB无线网卡免驱版本没有驱动无法使用

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#1199]
lsusb 命令显示：
0bda:1a2b Realtek Semiconductor Corp. 
安装驱动的方法：https://www.cnblogs.com/gudaxiong/p/10098092.html
make 报错，好像要编译内核。

**Comment by felixonmars** [comment]
需要安装 kernel headers。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
