### ISSUE TITLE
Corrupted background after suspend while using nvidia drivers

### ISSUE THREAD

**Issue by BrozzSama** [linuxdeepin/developer-center#120]
After resuming the computer from standby mode once I unlock the screen the background is white with some color noise on it. The problem goes away if I change the wallpaper.

It seems to be related to a feature in the NVIDIA drivers that prevents the storing of content in FBOs during modeswitches: 

https://bugs.archlinux.org/task/42511?project=1

https://devtalk.nvidia.com/default/topic/787748/linux/-nvidia340xx-archlinux64-gnome3-14-the-background-of-desktop-and-lockscreen-mess-after-resume-from-/post/4367179/#4367179

The GNOME team apparently found a workaround and it's currently available in the mutter upstream, however deepin-wm still has this issue.

I'm currently using Arch Linux 64-bit with the latest NVIDIA drivers
My graphics card is: NVIDIA Corporation GM206 [GeForce GTX 950](rev a1)

**Comment by fasheng** [comment]
Thanks for the report.
The upstream gnome-shell bug url is:
https://bugzilla.gnome.org/show_bug.cgi?id=739178

And the patches are:
mutter(3.21.4): https://git.gnome.org/browse/gnome-shell/commit/?id=358f64d
gnome-shell: https://mail.gnome.org/archives/commits-list/2016-June/msg05835.html

The solution is simple, mutter emit a new signal named `GL_VIDEO_MEMORY_PURGED` in `Display` and gnome-shell refresh the screen once received it. But we'd better try to solved it after deepin-mutter upgrade to 3.22.x.
@sonald

**Comment by manateelazycat** [comment]
@sonald This issue can close now?

**Comment by avently** [comment]
@fasheng mutter is 3.23.3 now. The problem is not fixed. Can you take a look at it? Maybe you will find a solution.

**Comment by sonald** [comment]
@avently deepin use a forked and customized version of mutter, which makes it a little hard to keep up with upstream. I'll try to port fix from mutter later.

**Comment by avently** [comment]
@sonald ok, I will wait. Now I can't find a workaround

**Comment by BrozzSama** [comment]
@avently When I was using deepin I found a workaround and posted it to the Arch Wiki, it might help you as well if you're affected by this issue: https://wiki.archlinux.org/index.php/Deepin_Desktop_Environment#No_background_after_resuming_from_standby

**Comment by sonald** [comment]
gala has a workaround of this problem, I'll port it later.

**Comment by sonald** [comment]
I port a workaround from gala: https://github.com/linuxdeepin/deepin-wm/commit/a64fd1fa5d3da2598a504678fedfb4b16f7ab41e

**Comment by avently** [comment]
@sonald  any binary available?

**Comment by sonald** [comment]
I'm afraid not. this fix will be shipped with deepin 15.4, if you use archlinux, this will be available recently.

**Comment by avently** [comment]
I updated my Manjaro from testing channel and deepin-wm is 1.9.2-1 now. Background is corrupted as before. No changes in this issue. I can test new fixes you will make. Just upload it here. It will be faster then wait a new update

**Comment by sonald** [comment]
You may try these deb files for amd64 platform.
[deepin-wm.zip](https://github.com/linuxdeepin/developer-center/files/743964/deepin-wm.zip)

**Comment by avently** [comment]
How can i install it on archlinux-based system? I can build myself but no new commits added to git.

**Comment by sonald** [comment]
try to checkout this [commit](https://github.com/linuxdeepin/deepin-wm/commit/a64fd1fa5d3da2598a504678fedfb4b16f7ab41e), build and test.

**Comment by avently** [comment]
made & install

suspend
wakeup and background is fine
suspend
wakeup and background is fine
...other tries gives a correct background.

rebooted
suspend
wakeup and background is Corrupted
suspend
wakeup and background is fine
...other tries gives a correct background.

rebooted
suspend
wakeup and background is Corrupted
suspend
wakeup and background is fine
suspend
wakeup and background is fine
...other tries gives a correct background.

As you can see, first time after restart fix Is not working. But next time it works fine.

**Comment by avently** [comment]
Hello. 
Take a look. This is how Deepin Dock looks like after wakeup. Background of the other places of the screen looks as it should. Only dock has this problem.
![dock](https://cloud.githubusercontent.com/assets/7953703/23972340/71f78faa-09e2-11e7-9c87-16a1fcbc041b.png)

**Comment by sonald** [comment]
It seems that blurring background is broken after wakeup.

**Comment by avently** [comment]
@sonald now everything is fine on Arch. Thank you, guys
