### ISSUE TITLE
深度修复工具磁盘清理看不到磁盘全名

### ISSUE THREAD

**Issue by jetmit** [linuxdeepin/developer-center#1203]
<img width="525" alt="深度截图_deepin-repair-tools_20190520154312" src="https://user-images.githubusercontent.com/20562449/58004753-873e1300-7b16-11e9-821a-ac4c67f24007.png">

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
