### ISSUE TITLE
[bug] dde-kwin closes the active window automatically

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#1204]
## Describe the bug

`dde-kwin` closes the active window automatically when we move the mouse to the closing hot screen.

## To Reproduce

Steps to reproduce the bug:
1. Open any program.
2. Make sure it is the active window.
3. Move your mouse to the hot screen which helps us to close the active window. But don't click anything.
4. The active window closes itself.
## Expected behavior

The active window should not close itself. It should close only when we click on the hot screen.
## Screenshots

![deepin-screen-recorder_Select area_20190520175525](https://user-images.githubusercontent.com/33563064/58019935-83b38780-7b28-11e9-93b1-720e7c1c0faf.gif)

**It should be noted that in the photo above, I did NOT click on the hot screen.**
### Related package version

dde-kwin v0.0.6-1
kwin v5.15.5-1

**Comment by SiamSami** [comment]
Fixed

**Comment by SiamSami** [comment]
We still have this issue..

**Comment by BLumia** [comment]
Not sure but seems you have set a hot corner setting?

**Comment by SiamSami** [comment]
@BLumia Yes

**Comment by SiamSami** [comment]
fixed
