### ISSUE TITLE
虚拟机安装后从windows拖拽文件出现卡死现象

### ISSUE THREAD

**Issue by braxtong** [linuxdeepin/developer-center#1207]
VirtualBox安装后从windows7拖拽文件出现卡死现象

**Comment by BLumia** [comment]
windows7 是宿主还是虚拟机？从宿主拖拽到虚拟机还是从虚拟机拖拽到宿主？从哪个应用程序拖拽到哪个应用程序？

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
