### ISSUE TITLE
[Arch Linux] Sound effects cannot turn off completely

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#1208]
## Describe the bug
Sound effects off - doesn't turn off all effects completely.
Some like system login / logout seems to be off, but some like errors / warnings still active.

## To Reproduce
There are lots of way, but fastest is:
1. Turn off Sound effects in Deepin settings
2. Create new file in Sublime text and try to close it - it will make error / warning sound

## Expected behavior
When Sound effects turned off - it should be completely turned off.

## Enviroments:
OS: Manjaro 18.0.4 Illyria
Kernel: x86_64 Linux 4.19.42-1-MANJARO
Shell: bash 5.0.7
DE: Deepin 15.10.1
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
compiler: gcc 8.3.0
tk: Qt 5.12.3
dm: LightDM

### Distro & Version
Arch / Manjaro Deepin

### Related package version
deepin-daemon  3.27.2-1
manjaro-deepin-settings  20181231-1

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
