### ISSUE TITLE
[archlinux]dde-file-manager rightbutton open terminal not run

### ISSUE THREAD

**Issue by kirigayakazushin** [linuxdeepin/developer-center#121]
I can't open terminal.

**Comment by fasheng** [comment]
@dragondjf @zccrs Any idea?

**Comment by renanmarcs** [comment]
Same here. In nautilus I can open installing "file-roller" and "nautilus-open-terminal"... But this fix doens't apply to Deepin File Manager.

**Comment by mmetak** [comment]
If I make a symlink ''ln -s /usr/bin/xterm /usr/bin/x-terminal-emulator'' for examaple, then it works.

**Comment by renanmarcs** [comment]
Thank you @mmetak ! I linked to deepin terminal instead xterm.

**Comment by Chathula** [comment]
i tried this.. worked well.. 

but after i installed again the os (Manjaro). this isn't work.. why?

**Comment by oberon2007** [comment]
The symlink overwrites the properly installed executable of **xterm**. You have to uninstall it or use the symlink in **/usr/local/bin** instead.
In any case this is not a solution but a dirty workaround. It would need to be fixed properly in **dde-filemanager**

**Comment by stychu** [comment]
This is anoyyig a little bit also is there an option to change dde-file-manager to dark theme ???

**Comment by apolbox** [comment]
deepin-terminal fix open in terminal on deepin file manager:
$ cd /usr/bin/
$ sudo nano x-terminal-emulator

add comment to line:
exec('xterm',@args)

and replace to :
exec('deepin-terminal',@args)

and save.

work for me.

**Comment by fadjoker13** [comment]
my file manager is not found

**Comment by BLumia** [comment]
> my file manager is not found

@fadjoker13 We won't track different issues in closed issue ticket. Please consider creating a new issue ticket for different issue reports, thanks!
