### ISSUE TITLE
Window Title Bar Scale

### ISSUE THREAD

**Issue by adriansnetlis** [linuxdeepin/developer-center#1210]
Now I don't know whether this is the place to ask for this, but I'll post it down here anyway.
I installed Deeping Desktop Environment and I'm loving it generally, but there's one serious flaw (in my opinion). The title bars take a large amount of screen real estate and don't look that grade proportion-vise (on my low-DPI monitor), especially with the panel being set to small size. It'd be great if there was an option to change their size. A slider in options, for example, that controls the height of the title bars of windows.

**Comment by doooooit** [comment]
+1，标题栏宽度太大，实在不好看。如果应用本身是白色的还好说，对于黑色背景的应用这个标题栏特别突兀，喧宾夺主。

**Comment by licardoY** [comment]
![深度截图_选择区域_20190522145658](https://user-images.githubusercontent.com/20562449/58153548-e7ad8b80-7ca1-11e9-9ae2-01d1057ffa72.png)

设计师的初衷是想统一DTK和其他程序顶栏高度吗？但是考虑到dtk应用比如商店在顶栏有搜索，登录，文件管理器在顶栏有地址栏，有搜索菜单等等所以看起来不显得那么宽(也确实需要这么宽才放的下)，还是比较和谐自然的。但gtk顶栏什么都没有看起来就显得很宽的白条，字体也非常的大，很突兀。希望设计师考虑到这点不同

**Comment by keybreak** [comment]
Nice idea!

@BLumia @shule1987 @wangjia12 
Before that feature come, to avoid further complications, i'd also recommend to make all Deepin programs same height in the first place, **deepin-movie** have smaller title bar, than other programs right now.

**Comment by BLumia** [comment]
assoc: https://bbs.deepin.org/forum.php?mod=viewthread&tid=178447&extra=

**Comment by shule1987** [comment]
之所以这样做的原因有几个:
1.为了deepin设计的统一性,因为有dtk应用和gtk应用,所以这两者的体验没法达到完全的一致
2.为了方便用户操作, 让用户很好的点击关闭按钮意味着关闭按钮的区域要增大,增大了的同时必然会让gtk带传统标题栏的应用显得不是很舒服
3.gtk3应用的关闭按钮和带传统标题栏的gtk应用是共用一套关闭按钮资源, 意味着要么都跟着一起大,或者一起小, 我们选择了跟着一起大, 因为为了方便用户操作

**Comment by doooooit** [comment]
> 之所以这样做的原因有几个:
> 1.为了deepin设计的统一性,因为有dtk应用和gtk应用,所以这两者的体验没法达到完全的一致
> 2.为了方便用户操作, 让用户很好的点击关闭按钮意味着关闭按钮的区域要增大,增大了的同时必然会让gtk带传统标题栏的应用显得不是很舒服
> 3.gtk3应用的关闭按钮和带传统标题栏的gtk应用是共用一套关闭按钮资源, 意味着要么都跟着一起大,或者一起小, 我们选择了跟着一起大, 因为为了方便用户操作

既然是为了用户方便，为什么广大用户都在吐槽标题栏宽度太高？

**Comment by JiangXiaoBei** [comment]
真的丑……请一定要改回去，或者提供一个结构让允许用户改回去

**Comment by denjay** [comment]
> 之所以这样做的原因有几个:
> 1.为了deepin设计的统一性,因为有dtk应用和gtk应用,所以这两者的体验没法达到完全的一致
> 2.为了方便用户操作, 让用户很好的点击关闭按钮意味着关闭按钮的区域要增大,增大了的同时必然会让gtk带传统标题栏的应用显得不是很舒服
> 3.gtk3应用的关闭按钮和带传统标题栏的gtk应用是共用一套关闭按钮资源, 意味着要么都跟着一起大,或者一起小, 我们选择了跟着一起大, 因为为了方便用户操作

的确丑，以前比较窄的时候从来没有用户觉得不好，自从变宽了以后，用户反馈觉得丑的经常有。并没觉得窄不方便操作，deepin最大的特色就是美观，这点真的很影响，所以还是希望改回去

**Comment by WilliamYangShuai** [comment]
> 之所以这样做的原因有几个:
> 1.为了deepin设计的统一性,因为有dtk应用和gtk应用,所以这两者的体验没法达到完全的一致
> 2.为了方便用户操作, 让用户很好的点击关闭按钮意味着关闭按钮的区域要增大,增大了的同时必然会让gtk带传统标题栏的应用显得不是很舒服
> 3.gtk3应用的关闭按钮和带传统标题栏的gtk应用是共用一套关闭按钮资源, 意味着要么都跟着一起大,或者一起小, 我们选择了跟着一起大, 因为为了方便用户操作

真的很丑，这是我对deepin最不喜欢的地方，我希望我可以有选择

**Comment by lotuso** [comment]
窗口 标题的居中方式不符合视觉吧，还不如直接左对齐呢，还有一个标题栏占的高度有点过分了，难道是打算兼容着做平板系统？

**Comment by BLumia** [comment]
> 窗口 标题的居中方式不符合视觉吧，还不如直接左对齐呢，还有一个标题栏占的高度有点过分了，难道是打算兼容着做平板系统？

居中问题下次推送更新就会解决了。

另外请大家讨论问题的时候理性讨论，不要夹带负面情绪，非常感谢！

**Comment by sunnyes** [comment]
还没变宽的是哪个版本，我要回去。。。

**Comment by BLumia** [comment]
assoc: https://bbs.deepin.org/forum.php?mod=viewthread&tid=180262&extra=

btw, there will be a config for the titlebar height in the upcoming dde-kwin update, more details will be provided here after it's ready, but the default height is still the current value and it also won't be a option inside the control center unless the design decided to change.

**Comment by BLumia** [comment]
From dde-kwin **0.0.11** version, you can config the titlebar height by create a config file at (please create the path if the path is not existed):

``` bash
# If you use light theme
~/.local/share/deepin/themes/deepin/light/titlebar.ini
# If you use dark theme
~/.local/share/deepin/themes/deepin/dark/titlebar.ini
```

and put the following content in the config file (replace `25` with the height you want):

``` ini
[Active]
height=25

[Inactive]
height=25
```

After save the config file, open the control center and switch your theme to any other one and switch back so the config file will be loaded.

**Comment by YugeCse** [comment]
是啊，于是我又用回了unstable的版本，dde-wm了.

**Comment by fanhengyuan** [comment]
I found this problem. I don't know if it is a bug.

As shown in the following GIF diagram, the right deepin terminal is normal.

Non-deepin official software such as teamview, VirtualBox cursors are placed on the edge, and no icon for changing the window is displayed.

But you can change the window size.

![pic](https://tva1.sinaimg.cn/large/006Xmmmggy1g5rifogeobg31hc0t04qq.gif)


Do not display the icon for the red box below.

![avatar](https://tva1.sinaimg.cn/large/006Xmmmggy1g5tgrjxfvdj309j0demxx.jpg)

Forum link here:
https://bbs.deepin.org/forum.php?mod=viewthread&tid=181702

**Comment by gitQqqHs** [comment]
~/.local/share/deepin/themes/deepin/light/titlebar.ini
我改了这个文件,但是没有任何效果
如何查看dde-kwin版本呢??

**Comment by bibichuan** [comment]
windows标题栏，mac os标题栏都很小，也没人说过，影响用户操作了啊？用户又不是眼瞎，怎么可能点不中呢？

**Comment by gitQqqHs** [comment]
# If you use light theme
~/.local/share/deepin/themes/deepin/light/titlebar.ini
# If you use dark theme
~/.local/share/deepin/themes/deepin/dark/titlebar.ini
内容如下: 修改25即可  保存后重启电脑
[Active]
height=25

[Inactive]
height=25

**Comment by xuanyuan100** [comment]
真的是太丑了,用户还没有选择的余地,而且所说的里有完全不成立

**Comment by 90du** [comment]
他们本来就是两个东西，为什么非要统一，只要外观一样就可以，减低高度不会影响效果的

**Comment by gitQqqHs** [comment]
深度有些美过头了：）

**Comment by ysy950803** [comment]
确实应该提供途径让用户自定义三方软件的bar高度，系统自带的UI这个高度还是很好看，但是三方软件真的太丑。

**Comment by licardoY** [comment]
> From dde-kwin **0.0.11** version, you can config the titlebar height by create a config file at (please create the path if the path is not existed):
> 
> ```shell
> # If you use light theme
> ~/.local/share/deepin/themes/deepin/light/titlebar.ini
> # If you use dark theme
> ~/.local/share/deepin/themes/deepin/dark/titlebar.ini
> ```
> 
> and put the following content in the config file (replace `25` with the height you want):
> 
> ```ini
> [Active]
> height=25
> 
> [Inactive]
> height=25
> ```
> 
> After save the config file, open the control center and switch your theme to any other one and switch back so the config file will be loaded.
> 
> Please notice this could not affact the applications who use client side decoration(ie. titlebar is not drawed by window manager), like almost all GTK3 applications, and all DTK applications.

这样可以调节高度了， 请问一下有没有配置能调一下颜色

**Comment by licardoY** [comment]
> From dde-kwin **0.0.11** version, you can config the titlebar height by create a config file at (please create the path if the path is not existed):
> 
> ```shell
> # If you use light theme
> ~/.local/share/deepin/themes/deepin/light/titlebar.ini
> # If you use dark theme
> ~/.local/share/deepin/themes/deepin/dark/titlebar.ini
> ```
> 
> and put the following content in the config file (replace `25` with the height you want):
> 
> ```ini
> [Active]
> height=25
> 
> [Inactive]
> height=25
> ```
> 
> After save the config file, open the control center and switch your theme to any other one and switch back so the config file will be loaded.
> 
> Please notice this could not affact the applications who use client side decoration(ie. titlebar is not drawed by window manager), like almost all GTK3 applications, and all DTK applications.

这样可以调节高度了， 请问一下有没有配置能调节颜色

**Comment by 90du** [comment]
要修改headerbar的背景色



在 2020-02-18 20:11:09，"licardoY" <notifications@github.com> 写道：

From dde-kwin 0.0.11 version, you can config the titlebar height by create a config file at (please create the path if the path is not existed):

# If you use light theme~/.local/share/deepin/themes/deepin/light/titlebar.ini

# If you use dark theme~/.local/share/deepin/themes/deepin/dark/titlebar.ini

and put the following content in the config file (replace 25 with the height you want):

[Active]height=25



[Inactive]height=25

After save the config file, open the control center and switch your theme to any other one and switch back so the config file will be loaded.

Please notice this could not affact the applications who use client side decoration(ie. titlebar is not drawed by window manager), like almost all GTK3 applications, and all DTK applications.

这样可以调节高度了， 请问一下有没有配置能调节颜色

**Comment by leon0625** [comment]
> From dde-kwin **0.0.11** version, you can config the titlebar height by create a config file at (please create the path if the path is not existed):
> 
> ```shell
> # If you use light theme
> ~/.local/share/deepin/themes/deepin/light/titlebar.ini
> # If you use dark theme
> ~/.local/share/deepin/themes/deepin/dark/titlebar.ini
> ```
> 
> and put the following content in the config file (replace `25` with the height you want):
> 
> ```ini
> [Active]
> height=25
> 
> [Inactive]
> height=25
> ```
> 
> After save the config file, open the control center and switch your theme to any other one and switch back so the config file will be loaded.
> 
> Please notice this could not affact the applications who use client side decoration(ie. titlebar is not drawed by window manager), like almost all GTK3 applications, and all DTK applications.

在开启窗口的特效的情况下，上面的修改可以生效，但我是关闭窗口特效的（开启窗口特效有时会出现有弹出小窗时闪屏的问题），上面的修改就不能生效了，有办法吗？

**Comment by 90du** [comment]
你用的那个版本啊



At 2020-02-24 17:26:52, "leon0625" <notifications@github.com> wrote:

From dde-kwin 0.0.11 version, you can config the titlebar height by create a config file at (please create the path if the path is not existed):

# If you use light theme~/.local/share/deepin/themes/deepin/light/titlebar.ini

# If you use dark theme~/.local/share/deepin/themes/deepin/dark/titlebar.ini

and put the following content in the config file (replace 25 with the height you want):

[Active]height=25



[Inactive]height=25

After save the config file, open the control center and switch your theme to any other one and switch back so the config file will be loaded.

Please notice this could not affact the applications who use client side decoration(ie. titlebar is not drawed by window manager), like almost all GTK3 applications, and all DTK applications.

在开启窗口的特效的情况下，上面的修改可以生效，但我是关闭窗口特效的（开启窗口特效有时会出现有弹出小窗时闪屏的问题），上面的修改就不能生效了，有办法吗？

**Comment by leon0625** [comment]
> 你用的那个版本啊 At 2020-02-24 17:26:52, "leon0625" <notifications@github.com> wrote: From dde-kwin 0.0.11 version, you can config the titlebar height by create a config file at (please create the path if the path is not existed): # If you use light theme~/.local/share/deepin/themes/deepin/light/titlebar.ini # If you use dark theme~/.local/share/deepin/themes/deepin/dark/titlebar.ini and put the following content in the config file (replace 25 with the height you want): [Active]height=25 [Inactive]height=25 After save the config file, open the control center and switch your theme to any other one and switch back so the config file will be loaded. Please notice this could not affact the applications who use client side decoration(ie. titlebar is not drawed by window manager), like almost all GTK3 applications, and all DTK applications. 在开启窗口的特效的情况下，上面的修改可以生效，但我是关闭窗口特效的（开启窗口特效有时会出现有弹出小窗时闪屏的问题），上面的修改就不能生效了，有办法吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

15.11

**Comment by SwimmingTiger** [comment]
All options from [linuxdeepin/dde-kwin/.../titlebar.ini](https://github.com/linuxdeepin/dde-kwin/blob/master/plugins/kdecoration/deepin/light/titlebar.ini)

来自 [linuxdeepin/dde-kwin/.../titlebar.ini](https://github.com/linuxdeepin/dde-kwin/blob/master/plugins/kdecoration/deepin/light/titlebar.ini) 的所有可用选项

```
[Active]
height=40
area=1

textColor=#303030
backgroundColor=white

menuIcon.normal=:/deepin/themes/deepin/light/icons/menu_normal.svg
menuIcon.hover=:/deepin/themes/deepin/light/icons/menu_hover.svg
menuIcon.press=:/deepin/themes/deepin/light/icons/menu_press.svg
menuIcon.disabled=:/deepin/themes/deepin/light/icons/menu_disabled.svg

minimizeIcon.normal=:/deepin/themes/deepin/light/icons/minimize_normal.svg
minimizeIcon.hover=:/deepin/themes/deepin/light/icons/minimize_hover.svg
minimizeIcon.press=:/deepin/themes/deepin/light/icons/minimize_press.svg
minimizeIcon.disabled=:/deepin/themes/deepin/light/icons/minimize_disabled.svg

maximizeIcon.normal=:/deepin/themes/deepin/light/icons/maximize_normal.svg
maximizeIcon.hover=:/deepin/themes/deepin/light/icons/maximize_hover.svg
maximizeIcon.press=:/deepin/themes/deepin/light/icons/maximize_press.svg
maximizeIcon.disabled=:/deepin/themes/deepin/light/icons/maximize_disabled.svg

unmaximizeIcon.normal=:/deepin/themes/deepin/light/icons/unmaximize_normal.svg
unmaximizeIcon.hover=:/deepin/themes/deepin/light/icons/unmaximize_hover.svg
unmaximizeIcon.press=:/deepin/themes/deepin/light/icons/unmaximize_press.svg
unmaximizeIcon.disabled=:/deepin/themes/deepin/light/icons/unmaximize_disabled.svg

closeIcon.normal=:/deepin/themes/deepin/light/icons/close_normal.svg
closeIcon.hover=:/deepin/themes/deepin/light/icons/close_hover.svg
closeIcon.press=:/deepin/themes/deepin/light/icons/close_press.svg
closeIcon.disabled=:/deepin/themes/deepin/light/icons/close_disabled.svg

[Inactive]
textColor=#969696
```

**Comment by bibichuan** [comment]
The height of the third-party title bar has been like this for more than a decade.I want to change.

**Comment by A-stranger** [comment]
install plugin: Window Decorate Mode Switcher 安装插件: 窗口装饰模式切换器
select view->switch decorate mode 选择 view-> switch decorate mode

**Comment by YugeCse** [comment]
OK, thanks!

**Comment by meiyixiang** [comment]
Now I don't know whether this is the place to ask for this, but I'll post it down here anyway.
I installed Deeping Desktop Environment and I'm loving it generally, but there's one serious flaw (in my opinion). The title bars take a large amount of screen real estate and don't look that grade proportion-vise (on my low-DPI monitor), especially with the panel being set to small size. It'd be great if there was an option to change their size. A slider in options, for example, that controls the height of the title bars of windows.

**Comment by meiyixiang** [comment]
24/5000 
This issue is temporarily designed to be based on a 1920X1080 environment

**Comment by bibichuan** [comment]
Deepin 20.5没有titlebar.ini这个配置文件了，怎么修改标题栏高度呢？

**Comment by BLumia** [comment]
> Deepin 20.5没有titlebar.ini这个配置文件了，怎么修改标题栏高度呢？

> please create the path if the path is not existed

不存在的情况你需要新建这个文件。

**Comment by bibichuan** [comment]
感谢您的来信，敝人已收到。敝人会尽快给您回复，谢谢。

**Comment by meiyixiang** [comment]
We have plans to provide global title bar height Settings to our users as plugins ourselves, which we will provide this year

**Comment by minesunny** [comment]
哈哈，进来考古挖掘，原来苹果刘海是抄这里的，deepin极为先进

**Comment by BLumia** [comment]
作为后续，由社区驱动开发的 [deepin-tweak](https://github.com/linuxdeepin/deepin-tweak/) 会自带调节标题栏大小的功能，不再需要手动编写配置文件。

如果有任何其它问题， **请开新的 issue 讨论** 。请保持讨论始终有助于发现和解决问题，不要阴阳怪气。

Somewhat related: the community-driven tool [`deepin-tweak`](https://github.com/linuxdeepin/deepin-tweak/) will support adjust titlebar height directly, users will no longer need to write the config file manually.

If you have any other related issues, please create a new issue thread instead of replying to this one. Thanks!
