### ISSUE TITLE
[easy fix] deepin-gtk-theme: one place with 'border-color: none'

### ISSUE THREAD

**Issue by cheese** [linuxdeepin/developer-center#1211]
## Describe the bug

bamfdaemon blames: `Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name`
Here `gtk.css` is deepin-dark/gtk-3.0/gtk.css:
```
3611:    border-color: none;
```
Change to a valid color and bamfdaemon will stop blaming.

### Distro & Version

Fedora 30
### Related package version

deepin-gtk-theme-17.10.10-2.fc30.noarch
bamf-daemon-0.5.3-6.fc29.x86_64

**Comment by zhangdeshuai409930360** [comment]
1

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
