### ISSUE TITLE
Doesn't pause when minimized

### ISSUE THREAD

**Issue by KimHono** [linuxdeepin/developer-center#1212]
The choice "Pause when minimized" in the settings, doesn't work.
I mean, the movie is still going on.
Version : 3.2.7

**Comment by antechdesigns** [comment]
works fine here archdeepin - deepin-movie 3.2.7 on Kernel: x86_64 Linux 5.1.3-arch1-1-ARCH

Try running `deepin-movie` from terminal, see if it pumps out any errors
also look at `sudo journalctl -p 3 -xb` & `dmesg` see if any errors

**Comment by SiamSami** [comment]
Antergos is discontinued. You should probably change your distro.

**Comment by antechdesigns** [comment]
@KimHono I have an archdeepin iso & tutorials if you'd like to try that, link in my profile.

Although I do believe over time, antergos will essentially become arch as they fade away.

**Comment by BLumia** [comment]
Closed since this issue seems no longer exist. Feel free to let us know if you still have this issue :)

**Comment by KimHono** [comment]
> Try running `deepin-movie` from terminal, see if it pumps out any errors
> also look at `sudo journalctl -p 3 -xb` & `dmesg` see if any errors

Yes, I've got the errors **"dtkwidget2" can not find qm files "deepin-movie" can not find qm files** in a terminal. But nothing in dmesg.

**Comment by BLumia** [comment]
@KimHono so did you still have that issue? btw, minimize it will pause the video but restore the window will let it continue play.

**Comment by KimHono** [comment]
Unfortunately, yes.
As expected, the video stops for 3 or 4 seconds, but still goes on while minimized.

**Comment by antechdesigns** [comment]
@KimHono 
Try reinstalling deepin-movie see if that help
I have never had this happen.
