### ISSUE TITLE
[Feature] Option to hide files on Desktop

### ISSUE THREAD

**Issue by LeCharlatan** [linuxdeepin/developer-center#1213]
Hi,

I'd like to see an option to hide files and folders on Desktop.
I don't mean delete those files and dolfers, just hide them like KDE or XFCE does :)

Thanks for making such a nice Desktop

**Comment by BLumia** [comment]
assoc: https://github.com/linuxdeepin/developer-center/issues/1147

**Comment by zccrs** [comment]
See: https://docs-blog.wh-redirect.deepin.cn/?p=703

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
