### ISSUE TITLE
Deepin Mutter fails to draw Chromium window when maximized

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/developer-center#1214]
* [Chromium bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=965258)

**Comment by dmmaz** [comment]
same here.

**Comment by sonald** [comment]
I can not reproduce on Deepin 15.10 with chrome 74.0.3729.169. I'm not quite sure this is a deepin-mutter, but mostly likely this is mesa related.

**Comment by es20490446e** [comment]
deepin-mutter 3.20.38
mesa 19.0.4
chromium 74.0.3729.196

**Comment by sonald** [comment]
I have reproduced this problem only on manjaro.  My first intuition is that mesa is to blame. but I found a workaround by just adjust chromium flags. 
go to **about:flags** in chromium and search for zero-copy rasterizer, by disabling it, the problem disappeared.

**Comment by sonald** [comment]
The weird thing is that when I reset it to the default value, the problem can not be reprodcued.

**Comment by es20490446e** [comment]
It seems gone now.
