### ISSUE TITLE
Theme wrong on deepin root file manager

### ISSUE THREAD

**Issue by nmatavka** [linuxdeepin/developer-center#1215]
## Describe the bug
If you select a different icon theme in Deepin settings, then open a root file manager, the theme won't show up.

## To Reproduce
1. Go to deepin menu
2. Settings -> Personalisation -> Theme
3. Click on any icon theme
4. Deepin menu
5. Start typing "root..."
6. Click "root-file manager"
7 Icon theme is wrong.

## Expected behavior
Icon theme in root file manager is the one you picked in Personalisation

## Enviroments:
Latest manjaro-deepin on Unstable stream.

**Comment by BLumia** [comment]
Root file manager will only the correct DPI scale from current non-root user, for other settings, it will use the root user's setting, which included the icon theme.

Would like to looking for a proper way to fix this, but fyi it's always not recommended to use the root file manager to do your daily work.

**Comment by nmatavka** [comment]
I *don't* use the root file manager to do my daily work... I'm a Unixer of about 15 years, so I know it's not good practice.

I only use Root-Fileman if the user file manager won't let me drag and drop because of permissions.  In other words, I use it as designed.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
