### ISSUE TITLE
[Feature request] Desktop effects customisation?

### ISSUE THREAD

**Issue by nmatavka** [linuxdeepin/developer-center#1216]
Now that Deepin is Kwin-based, we can have wobbly windows, translucency, and all manner of awesome desktop effects.  Unfortunately, creating those effects either involves installing the KDE control panel and about a million dependencies, or hand-massaging the kwin configuration files.  Deepin should have its own personalisation, so we can pick wobbly/fire/disintegrating windows with less hassle.

**Comment by es20490446e** [comment]
I believe that customizing those effects really doesn't matter, at least on a default installation. It's rather a nice to have optional tool.

Nevertheless I feel that the default window animations speed is too slow.

**Comment by es20490446e** [comment]
[Improved kwinrc](https://github.com/linuxdeepin/developer-center/issues/1232)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
