### ISSUE TITLE
功能需求：增加应用窗口贴靠屏幕左右两侧时的特效

### ISSUE THREAD

**Issue by xiaoc-arch** [linuxdeepin/developer-center#1218]
## 缺陷描述
拖动应用窗口贴向屏幕左右两侧时，应用窗口仍然是圆角，导致留有圆角空隙

## 复现步骤
1、打开一个应用如文件管理器
2、拖动窗口贴靠屏幕左右两侧
3、窗口仍然是圆角，四个角留有圆角空隙
## 期望行为
希望应用拖动贴靠屏幕左右两侧时能将圆角窗口变直角

### 发行版以及版本
Linux Deepin 15.10.1

**Comment by zccrs** [comment]
这是个bug，后续会修复

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
