### ISSUE TITLE
高分屏1.5倍缩放之后,微信聊天的图片也被放大了,很模糊

### ISSUE THREAD

**Issue by jetmit** [linuxdeepin/developer-center#1219]
高分屏1.5倍缩放之后,微信聊天的图片点击打开被放大了,看起来很模糊,需要缩小才能清晰.
能不能只放大微信的界面,不放大聊天图片

**Comment by zccrs** [comment]
有截图吗？

**Comment by licardoY** [comment]
https://github.com/licardoY/fish-style/blob/master/%E6%B7%B1%E5%BA%A6%E5%BD%95%E5%B1%8F_%E9%80%89%E6%8B%A9%E5%8C%BA%E5%9F%9F_20190525145500.mp4

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
