### ISSUE TITLE
No wallpaper in 32bit version

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/developer-center#122]
Don't know which package is responsible for this...  I just built a 32bit ISO with the identical configuration and packages as the 64bit. The 32bit version has just a black background. When I switch to the lockscreen or open the dialog to set the wallpaper, I can see the background, but the normal desktop is just black. It doesn't make a difference if I use mutter or metacity.

**Comment by fasheng** [comment]
Well, I tested my 32bit arch with the latest packages just now, it's fine. I know the normal wallpaper is paint by dde-desktop, how about you kill it in your machine?

**Comment by hualet** [comment]
It should be an issue of dde-desktop though it doesn't draw the wallpaper. Desktop just went black and covered the wallpaper, so you see a whole black background.
I've seen this once,  kill dde-desktop works, but I didn't find out what is causing dde-desktop to be like that.

**Comment by oberon2007** [comment]
That's right. Killling dde-desktop shows the wallpaper until it is restarted.

**Comment by oberon2007** [comment]
For some reason with the 32bit version vbox-video driver doesn't get installed, though it works fine with the 64bit version. Any thoughts, @philmmanjaro ?

**Comment by philmmanjaro** [comment]
@oberon2007: for that I've to know which **manjaro-tools** was used. Stable branch only runs with **mt-0.12.x** series and needs an older **profile-set** to work. With **testing** and **unstable** we are currently at **mt-0.13.x** series. With my [current development releases](https://manjaro.org/manjaro-preview-releases/) I see no issues in regard of **vbox-video driver** on x32. It might be a mix-up on **manjaro-live** and the wrong **manjaro-tools** used.

**Comment by oberon2007** [comment]
I use the same setup as for the 64bit (which works fine): **mt-0.12.x** profile branch **16.08-preX** and stable branch.

**Comment by oberon2007** [comment]
and also there were no issues with cinnamon and i3 in 32bit - so this seems weird. I'm just wondering were here could be any difference from the viewpoint of **mhwd** when installing the driver maybe?

**Comment by philmmanjaro** [comment]
check the **mhwd.log** when you're in live-session. It should be located in /tmp or /etc/log

**Comment by philmmanjaro** [comment]
I just tested a new **dev-build**. **mhwd** works there on **x32**:

```
[manjaro@manjaro Desktop]$ cat /var/log/mhwd*
Running MHWD...
> Using config 'video-virtualbox' for device: 0000:00:02.0 (0300:80ee:beef) Display controller InnoTek Systemberatung GmbH VirtualBox Graphics Adapter
> Installing video-virtualbox...
warning: database file for 'core' does not exist
warning: database file for 'extra' does not exist
warning: database file for 'community' does not exist
Sourcing /var/lib/mhwd/db/pci/graphic_drivers/virtualbox/MHWDCONFIG
Processing classid: 0300
Sourcing /var/lib/mhwd/scripts/include/0300
warning: database file for 'core' does not exist
warning: database file for 'extra' does not exist
warning: database file for 'community' does not exist
:: Synchronizing package databases...
downloading gfx-pkgs.db...
resolving dependencies...
looking for conflicting packages...

Packages (2) linux44-virtualbox-guest-modules-5.1.4-2  virtualbox-guest-utils-5.1.4-0.1

Total Download Size:   1.29 MiB
Total Installed Size:  7.64 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
downloading linux44-virtualbox-guest-modules-5.1.4-2-i686.pkg.tar.xz...
downloading virtualbox-guest-utils-5.1.4-0.1-i686.pkg.tar.xz...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
:: Processing package changes...
installing linux44-virtualbox-guest-modules...
===> You may want to load vboxguest, vboxsf and vboxvideo
installing virtualbox-guest-utils...
modprobe: ERROR: could not insert 'vboxvideo': Invalid argument
libGl: '/usr/lib/mesa/libGL.so.1.2.0'
libGLESv1: '/usr/lib/mesa/libGLESv1_CM.so.1.1.0'
libGLESv2: '/usr/lib/mesa/libGLESv2.so.2.0.0'
libEGL: '/usr/lib/mesa/libEGL.so.1.0.0'
libglx: '/usr/lib/xorg/modules/extensions/libglx.xorg'
> Successfully installed video-virtualbox
MHWD DONE
```

**Comment by oberon2007** [comment]
@philmmanjaro this is weird. mhwd-live.log:
```
:: Synchronizing package databases...
downloading gfx-pkgs.db...
error: target not found: virtualbox-guest-utils
error: target not found: linux44-virtualbox-guest-modules
Error: pacman failed!
script failed!
```
I've double checked: this is stable branch, mt-0.12 series and profile branch 16.08-preX. Deepin 64bit works, so did cinnamon and i3 a few days ago. Now I suddenly have this issue with deepin only with 32bit.

**Comment by oberon2007** [comment]
Is there a reason why I should adopt [this commit](https://github.com/manjaro/manjaro-tools-iso-profiles/commit/2d778759ccede32cb55a84eed1f5d97b43ad2394)? I haven't until now because I think on stable branch nothing should have changed recently in the live packages, and also deepin control-center mouse-settings-plugin still needs **xf86-input-synaptics** and will not work with **xf86-input-libinput** installed. So I have commented it out here locally.
In any case I am wondering why **linux44-virtualbox-guest-modules** isn't present - shouldn't they be preinstalled anyway??

**Comment by oberon2007** [comment]
Sorry, @hualet and @fasheng I think this is not a Deepin issue at all ! :wink:

**Comment by fasheng** [comment]
OK, that's fine :)



2016年9月10日 20:05, 20:05，在 Bernhard Landauer <notifications@github.com> 已写:

**Comment by philmmanjaro** [comment]
@oberon2007: please check your build.log and **mhwd-overlay** if the driver was added to that local repository. Might be a local issue on your end due some file-conflict.

**Comment by oberon2007** [comment]
Somehow I must have screwed up the **mhwd-image** locally before squashing the ISO. All is well. Sorry for that. :no_mouth:
