### ISSUE TITLE
No window manager when using deepin-kwin

### ISSUE THREAD

**Issue by antechdesigns** [linuxdeepin/developer-center#1220]
## Describe the bug
Using deepin-kwin no WM at boot, just wallpaper

## To Reproduce
Just done a full system Update archlinux then reboot using kwin WM

I can get it working if I manage to open a terminal and do a `kwin_x11 --replace` and works as expected, deepin-wm is fine on my other machine ;)

This is what I get in the terminal when I do `kwin_x11 --replace`

> kwin_x11 --replace
OpenGL vendor string:                   NVIDIA Corporation
OpenGL renderer string:                 GeForce GTX 970/PCIe/SSE2
OpenGL version string:                  3.1.0 NVIDIA 430.14
OpenGL shading language version string: 1.40 NVIDIA via Cg compiler
Driver:                                 NVIDIA
Driver version:                         430.14
GPU class:                              Unknown
OpenGL version:                         3.1
GLSL version:                           1.40
X server version:                       1.20.4
Linux kernel version:                   5.1.4
Requires strict binding:                no
GLSL shaders:                           yes
Texture NPOT support:                   yes
Virtual Machine:                        no
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1348, resource id: 58720279, major code: 3 (GetWindowAttributes), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 1349, resource id: 58720279, major code: 14 (GetGeometry), minor code: 0
Module 'org.kde.kwin.decoration' does not contain a module identifier directive - it cannot be protected from external registrations.
Icon theme "gnome" not found.
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3440, resource id: 62914566, major code: 20 (GetProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3441, resource id: 62914566, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3442, resource id: 62914566, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3448, resource id: 62914566, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3449, resource id: 62914566, major code: 20 (GetProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3454, resource id: 62914566, major code: 25 (SendEvent), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3455, resource id: 62914566, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3456, resource id: 62914566, major code: 42 (SetInputFocus), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3457, resource id: 62914566, major code: 25 (SendEvent), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3460, resource id: 62914566, major code: 12 (ConfigureWindow), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3461, resource id: 62914566, major code: 25 (SendEvent), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3467, resource id: 62914566, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3468, resource id: 62914566, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3469, resource id: 62914566, major code: 20 (GetProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3511, resource id: 62914566, major code: 15 (QueryTree), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3944, resource id: 56623109, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 5655, resource id: 56623111, major code: 15 (QueryTree), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 8578, resource id: 65011715, major code: 15 (QueryTree), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 10250, resource id: 58720772, major code: 18 (ChangeProperty), minor code: 0

**Comment by felixonmars** [comment]
@zccrs kwin_no_scale is no longer installed as executable in 0.0.7. After fixing that, a symbol error appears: _ZN4KWin6TabBox6TabBox22slotWalkThroughWindowsEv but doesn't seem to break the program.

@antechdesigns Please try again with 0.0.7-2

**Comment by antechdesigns** [comment]
wow that was quick, thanks guys ;) seems fine now

**Comment by SiamSami** [comment]
@antechdesigns Then you should close it then.
