### ISSUE TITLE
[bug] dde-file-manager crashes when emptying the trash

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#1222]
## Describe the bug

If we try to empty the trash which takes up around 20 GB of space, then it crashes.
## To Reproduce

1. Make sure that trash takes up around 20 GB of total space.
2. Right-click on "Trash" and select "Empty trash"
3. Deepin file manager should crash then.
## Expected behavior

Deepin file manager should not crash
## Enviroments:
Deepin DE
### Distro & Version

Distro: Archlinux
### Related package version

dde-file-manager v1.8.2(1:4.8.5-1)

### Additional context

If we run `dmesg` on the terminal after the crash, then we get this message,

> [13004.051751] dde-file-manage[13992]: **segfault at 20 ip 00007fd0a49760d0 sp 00007ffe82357e38 error 4 in libQt5Core.so.5.12.3[7fd0a4821000+2cc000]**

**Comment by BLumia** [comment]
Cannot reproduce here. Did you still have the stacktrace? Thanks.

**Comment by SiamSami** [comment]
weird... I'm not getting the crash anymore either. But can you please fix the error with `libQt5Core.so.5.12.3` mentioned above? Thanks.

**Comment by BLumia** [comment]
> can you please fix the error with libQt5Core.so.5.12.3 mentioned above? Thanks.

Sorry I'm not sure why you get that error, either. So I cannot fix it without knowing what happended..

**Comment by SiamSami** [comment]
Closing it for now then...
