### ISSUE TITLE
Faster animations on Kwin

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/developer-center#1224]
I think it would be nicer if Kwin animations under Deepin were a little faster.

**Comment by antechdesigns** [comment]
Yes we need a control panel for kwin effects ;)
for now you can edit the kwinrc file found in home/.config folder
add AnimationSpeed= under the [Compositing] heading

**Example**
```
[Compositing]
AnimationSpeed=0
```
=0 being the fastest =6 being the slowest

**Comment by es20490446e** [comment]
I believe that customizing those effects really doesn't matter, at least on a default installation.

But the default speed is too slow.

**Comment by keybreak** [comment]
I think defaults are good starting point, but having some advanced tweaks in control panel is good idea

**Comment by es20490446e** [comment]
[Improved kwinrc](https://github.com/linuxdeepin/developer-center/issues/1232)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
