### ISSUE TITLE
File Manager window doesn't cover the whole screen on Kwin

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/developer-center#1225]
https://youtu.be/GU5gRFQrI8U

**Comment by antechdesigns** [comment]
that's because deepin apps have a shadow around them, I don't think you can turn them off, they are hard-coded I believe, if you full screen a gtk app it looks fine.

**Comment by keybreak** [comment]
Ain't it already fixed in Linux Deepin variant of deepin-kwin?

**Comment by es20490446e** [comment]
At least not on deepin-kwin 0.0.6.

**Comment by keybreak** [comment]
I mean original Deepin, not Manjaro / Arch one

**Comment by es20490446e** [comment]
I personally don't know.

**Comment by gokhanyildirimlar** [comment]
It's normal I think, it doesn't fill the left side because there is the dock. But sticking to corners is still waiting for a fix.
[Here is how it's in Deepin.](http://sendvid.com/md860xyw)

**Comment by nmatavka** [comment]
Whole*.  A hole is a woman's pussy.

**Comment by es20490446e** [comment]
@nmatavka Ummm, yeah. I wonder why we are talking on GitHub, when we could just be having a hole in our lives.

By the way you have been reported for being a whore.

**Comment by keybreak** [comment]
@gokhanyildirimlar 
Oh ok, than it's must be fixed.
It's not like that in deepin-mutter also, so it's not impossible)

**Comment by antechdesigns** [comment]
@nmatavka really...

**Comment by gokhanyildirimlar** [comment]
@BLumia, @nmatavka did the same thing as he did in animated wallpaper support issue. Can you give him a big hug?

**Comment by gokhanyildirimlar** [comment]
> @gokhanyildirimlar
> Oh ok, than it's must be fixed.
> It's not like that in deepin-mutter also, so it's not impossible)

Yes, it's already [here](https://github.com/linuxdeepin/developer-center/issues/1136).

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
