### ISSUE TITLE
[Deepin 15.10.1] Scaling Issues

### ISSUE THREAD

**Issue by lucamarcelpeters** [linuxdeepin/developer-center#1226]
## Describe the bug
When setting the scaling above 1.0 on my 4k monitor it results in different behavior of windows. It changes from one installation to another and even after some reboots. Sometimes the border of a windows becomes very thick and sometimes the font is just too tiny, or to big(!). And if you drag a window in a corner it will be smaller than it should and there will be a line under the window, where it should have ended. In addition there appear random lines in the settings, after hovering over a button.

## To Reproduce
1. Set the scaling of the 4k monitor above 1.0 (See the best at 2.0+)
2. Open different applications (Not all are affected. Changes from installation to another.)
3. Drag window in a corner (optional)

## Expected behavior
Should look like 1080p with a scaling of 1.0

## Screenshots
![image](https://user-images.githubusercontent.com/9435787/58326455-2c196280-7e2d-11e9-994e-f8e2a2d12722.png)

![e4b6d421-b720-4a01-9b15-f0aeaebcb05b](https://user-images.githubusercontent.com/9435787/58326467-3176ad00-7e2d-11e9-9538-84428b08b115.jpeg)

![image](https://user-images.githubusercontent.com/9435787/58326620-a813aa80-7e2d-11e9-89f9-ef5900c4d48d.png)

![image](https://user-images.githubusercontent.com/9435787/58326401-fc6a5a80-7e2c-11e9-86ba-fa01392d1b20.png)

![06d268f5-aa08-476e-83af-4a934d6779fd](https://user-images.githubusercontent.com/9435787/58326490-3dfb0580-7e2d-11e9-9660-76dae321067c.jpeg)

![image](https://user-images.githubusercontent.com/9435787/58326523-5834e380-7e2d-11e9-85b6-099c7069ea7f.png)

![image](https://user-images.githubusercontent.com/9435787/58326789-21ab9880-7e2e-11e9-8e7b-97ff316b6f31.png)

### Distro & Version
Deepin 15.10.1

### Related package version
dde-file-manager 4.8.4

**Comment by zccrs** [comment]
Are you using archlinux?

````
rm ~/.dde_env
````

and restart

**Comment by lucamarcelpeters** [comment]
Hi @zccrs,
No, I'm using the Debian based one, that comes from the deepin website.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
