### ISSUE TITLE
[Feature Request] Option to have Deepin menu in categories mode.

### ISSUE THREAD

**Issue by nmatavka** [linuxdeepin/developer-center#1227]
As it stands right now, Deepin-dock doesn't remember what view was used.  It remembers "full-screen or corner menu" (so if you use the fullscreen button and use it that way, next time it opens full screen also).  But if I click "All Categories", and use it in category mode, next time it still opens in "last used apps" mode. 

For those of us switching from Cinnamon or Budgie, it would make sense to have Deepin remember what mode it opened in.  Or at least have an option in the context mode to open in one or the other.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
