### ISSUE TITLE
Feature request - Scientific and RPN modes in Calculator

### ISSUE THREAD

**Issue by nmatavka** [linuxdeepin/developer-center#1228]
Right now I can write something in deepin-calc like, "sin(90)" and it comes out 0.893....  Anyway, since we can already solve scientific calculations like that, wouldn't it be nice to have a "scientific mode" to show sin, cos, tan, sec, arcsin, arccos, arctan, arcsec, etc.  and switch from deg/rad/grad, decimal/hex/oct/bin?

also, an rpn mode would be helpful, so we can do calculations like 1 1 + 2 * 9 / in other words, (((1+1)*2)/9)?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
