### ISSUE TITLE
[Feature request] Android continuity

### ISSUE THREAD

**Issue by nmatavka** [linuxdeepin/developer-center#1229]
I like to recommend Deepin to my friends because above all it is *user friendly*.  One of the features I miss about the Mac OS X and the Windows experience is so-called continuity: if I have my Key2 on my desk next to me, I can receive notifications and texts and make calls through my laptop.  There are third party services to do this (like pushbullet) but I think it should be a standard Deepin feature, especially with standards like bluetooth.

It shouldn't be too hard to have a "phone dashboard", through which I can set up things like "echo mobile notifications on screen", or transmit and receive files.  The closest equivalent piece of software I could find is KDE connect, but this installs a fuck ton of dependencies.

**Comment by aiamuzz** [comment]
https://bgr.com/2014/12/03/airdroid-3-download-now-live/

**Comment by keybreak** [comment]
I would argue strongly against it in terms of privacy.

Better let 3rd party programs do this on user's will than having one more security hole on OS level...it is not a good idea.

**Comment by BLumia** [comment]
Maybe you can try out `kdeconnect` from KDE which is pretty good for that purpose?

**Comment by nmatavka** [comment]
> Maybe you can try out `kdeconnect` from KDE which is pretty good for that purpose? just simply `apt install kdeconnect`.

I am a satisfied KDE Connect user.  I was hoping that Deepin might decide to do its own spin on the idea.

**Comment by nmatavka** [comment]
> I would argue strongly against it in terms of privacy.
> 
> Better let 3rd party programs do this on user's will than having one more security hole on OS level...
> It is not a good idea.

I would argue strongly for it in terms of freedom of choice.  Better let the OS allow the user to choose whether he wants basic continuity or not.  We already have Bluetooth on Deepin, this would simply be better Bluetooth integration.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
