### ISSUE TITLE
关机界面没有翻译

### ISSUE THREAD

**Issue by cosct** [linuxdeepin/developer-center#1231]
## 复现步骤
1. 开机但不登录
2. 点击电源按钮进入关机界面
3. 关机界面没有翻译

## 期望行为

关机界面为中文
### 发行版以及版本

Linux Deepin 15.10.1（直接升级上来的）

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
