### ISSUE TITLE
[Arch Linux] Telegram minimize / maximize window position shift

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#1233]
## Describe the bug
Minimize / Maximize Telegram from tray shifts it up each time.

## Expected behavior
Stay on it's position :face_with_head_bandage: 

## Screenshots
https://i.imgur.com/cDyzrXK.mp4

## Enviroments:
OS: Manjaro 18.0.4 Illyria
Kernel: x86_64 Linux 4.19.42-1-MANJARO
Shell: bash 5.0.7
DE: Deepin 15.10.1
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
compiler: gcc 8.3.0
tk: Qt 5.12.3
dm: LightDM

### Distro & Version
Arch / Manjaro Deepin

### Related package version
Not sure which packages are responsible

**Comment by keybreak** [comment]
Just to make clear - it's not Telegram issue per se, it came somewhere on cycle of moving to **deepin-kwin** updates lately.

**Comment by keybreak** [comment]
@BLumia 
Also happens with Cadence...That's really annoying :smile_cat: 
Seems to happen for some programs specifically when you minimize / reopen them from tray.

**Comment by BLumia** [comment]
> @BLumia
> Also happens with Cadence...That's really annoying 
> Seems to happen for some programs specifically when you minimize / reopen them from tray.

Sorry I'm not familar with this issue, but it most likely a deepin-wm issue so could you test if dde-kwin also have this issue?

**Comment by keybreak** [comment]
It's hard to say (because of https://github.com/linuxdeepin/developer-center/issues/1250) since i had no animations whatsoever on kwin, and i suspect it's connected to animations...

But without it - seems to be ok on deepin-kwin.

Although last time i've checked kwin on hardware was yesterday, and it's full of bugs, like you can maximize window and can't minimize it back etc.

So if someone could fix this bug on **deepin-wm** a lot f people from Arch / Manjaro would be grateful (i suspect it's easier fix, than fixing whole lot of bugs on deepin-kwin).

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
