### ISSUE TITLE
从休眠恢复，亮度自动到最大

### ISSUE THREAD

**Issue by ziqiangxu** [linuxdeepin/developer-center#1234]
## 缺陷描述

从休眠恢复，亮度自动被调到最大

## 期望行为

维持休眠之前的亮度

### 发行版以及版本
如. Linux Deepin 15.10.1（stable）

**Comment by leewp14** [comment]
这比较像是驱动的问题。我的Debian运行NVIDIA官方驱动也是有类似问题，但如果运行nouveau就没有这个问题。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
