### ISSUE TITLE
deepin-editor 不要限制打开文件的类型

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#1236]
gpx 文件打不开，请不要在源码里限制打开文件的类型，这个问题早就说过了！

**Comment by BLumia** [comment]
这个最初为啥要做类型白名单来着..如果是为了避免编辑某些特定类型的文件（比如 binary），不如用黑名单？ @wangjia12

**Comment by duanyao** [comment]
我觉得文本编辑器对二进制文件警告一下就行了，如果用户坚持要打开，就打开呗。有些文件实际上是文本/二进制混合的，比如PDF。

**Comment by sonichy** [comment]
纵观各种文本编辑器，没有一个限制打开文件类型，是典型的设计者替用户做决定的权力滥用行为。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
