### ISSUE TITLE
深度文管启动desktop，参数丢失

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#1237]
某些情况Chrome打开本地网页加载本地文件会出现跨域问题：Access to XMLHttpRequest at 'file:///media/sonichy/job/HY/HTML/LocusMap/20190515091138UC.gpx' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
在 Chrome 的 desktop 的 exec 加上 --allow-file-access-from-files 参数可以解决。
但是，从深度文管启动 desktop，双击打开、打开方式打开、拖放打开，参数都会丢失。
其他文管（Thunar、Caja、海天鹰文管）没有此问题。
从其他文管启动带参数的desktop，再在深度文管打开文件，也没有此问题。
如需演示程序，请联系我。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
