### ISSUE TITLE
[Bug] Deepin apps don't maximise properly

### ISSUE THREAD

**Issue by nmatavka** [linuxdeepin/developer-center#1238]
## Describe the bug
Most of the apps included with Deepin do not cover the screen fully when "told" to maximise.  This issue affects, for example, Deepin File Manager, Image Viewer, Music, Deepin Draw... but NOT Terminal or Movie.  This bug can be reproduced on the latest Deepin.

## To Reproduce
1. Go to Start Menu
2. Type M-U-S
3. Click Music
4. Click Maximise button on title bar

## Expected behavior
Window maximises (i.e. covers the whole screen except for the task bar)

### Distro & Version
Manjaro Deepin unstable

**Comment by BLumia** [comment]
Tested under Deepin (deepin-wm) with dde-file-manager and deepin-music and it seems works fine.

Could you take a screenshot for your case and could any other Manjaro user reproduce this issue? Thanks.

**Comment by antechdesigns** [comment]
@BLumia I think hes referring to the shadow around the deepin apps, seems to have gone with the latest updates, archdeepin deepin-wm. Maybe Manjaro need to update?

**Comment by keybreak** [comment]
Manjaro Deepin unstable = Arch Deepin, except custom Kernel and MHWD...

So theoretically if there's problem it should also be on Arch, i don't have it on Manjaro Stable and Arch Deepin VM (if i get description of bug correctly)

**Comment by ojoakua-10bit** [comment]
I can reproduce this bug on Plasma 5.15.5 + kwin 5.15.5 on Arch Linux

I've tested on Deepin (both deepin-wm and deepin-kwin) and Plasma (using kwin and deepin-wm) and this problem only appear on Plasma+kwin

Here is the example on deepin-image-viewer:

Before maximized
![2019-05-27-224430_1366x768_scrot](https://user-images.githubusercontent.com/33028351/58429862-6f93fb00-80d1-11e9-8716-fc172f0a13a4.png)

After maximized
![2019-05-27-224537_1366x768_scrot](https://user-images.githubusercontent.com/33028351/58429885-85092500-80d1-11e9-9b09-dbb13c86c56d.png)

**Comment by nmatavka** [comment]
@ojoakua-10bit has done my work for me.  Yes, that is exactly the issue I am experiencing, but I do not have Plasma.

I am running Manjaro Deepin with Deepin-Kwin as the window manager.

**Comment by nmatavka** [comment]
> @BLumia I think hes referring to the shadow around the deepin apps, seems to have gone with the latest updates, archdeepin deepin-wm. Maybe Manjaro need to update?

No, not the shadow at all, I don't experience that (and wouldn't remember if I historically _did_ experience it, because to me that's a non-issue)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
