### ISSUE TITLE
fictx托盘图标异常

### ISSUE THREAD

**Issue by ListenerRi** [linuxdeepin/developer-center#124]
>当前操作系统: archlinux
>当前桌面环境: dde
>输入法框架: fcitx
>输入法: cloudpinyin

当处于高校模式时一切正常.
当处于时尚模式时, 中英文图标显示相反, 鼠标划过托盘时变为正常.

**Comment by felixonmars** [comment]
我这里没有这个问题……

**Comment by sbwtw** [comment]
fixed, please wait nexxt tag
