### ISSUE TITLE
Preview on multitasking view doesn't match with workspace-specific wallpaper

### ISSUE THREAD

**Issue by ojoakua-10bit** [linuxdeepin/developer-center#1240]
## Describe the bug
Preview on multitasking view doesn't match with workspace-specific wallpaper. It shows the wallpaper of current workspace for all workspace on preview instead showing the wallpaper of that workspace. 

For the example, if I open the multitasking view from workspace 1, preview for workspace 1 must show the wallpaper for workspace 1, preview for workspace 2 must show the wallpaper for workspace 2 and so on. But the preview of all workspace show the wallpaper of workspace 1.

This is deepin-kwin specific issue. It doesn't happen on deepin-wm/deepin-mutter.

## To Reproduce
1. Apply different wallpaper for each workspace/virtual desktop
2. Open multitasking view

## Expected behavior
Workspace preview show the wallpaper of that workspace.

## Screenshots
![deepin-screen-recorder_Select area_20190528002535](https://user-images.githubusercontent.com/33028351/58433698-8b53cd00-80e2-11e9-8578-63bf3bcc2417.gif)

### Distro & Version
Arch Linux

### Related package version
deepin-kwin 0.0.7-2
kwin 5.15.5-1

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
