### ISSUE TITLE
dde-polkit-agent

### ISSUE THREAD

**Issue by antechdesigns** [linuxdeepin/developer-center#1241]
## Describe the bug
Right clicking on a system folder and 'open in new window as admin' password is not accepted

## To Reproduce
Right click on a system folder and 'open in new window as admin' enter password

## Expected behavior
accept my password and open said window

## Enviroments:
dde deepin-wm 

### Distro & Version
archlinux 
Deepin 15.10.1

### Related package version
deepin-polkit-agent 0.2.7-1

### Additional context
Urgent please fix ;)

**Comment by keybreak** [comment]
I confirm this one, needs to be fixed asap, as it was just came from deepin-polkit-agent update...

**Comment by antechdesigns** [comment]
@BLumia  thanks ;)
