### ISSUE TITLE
dde-system-daemon log level should change

### ISSUE THREAD

**Issue by antechdesigns** [linuxdeepin/developer-center#1243]
**sudo journalctl -p 3 -xb**

> May 28 07:19:17 archdeepin daemon/dde-system-daemon[723]: main.go:97: failed to request name: name com.deepin.daemon.Daemon already taken
                                                            ->  proc.go:200
                                                            ->  asm_amd64.s:1337
May 28 07:19:17 archdeepin daemon/dde-system-daemon[721]: main.go:97: failed to request name: name com.deepin.daemon.Daemon already taken
                                                            ->  proc.go:200
                                                            ->  asm_amd64.s:1337

archlinux - deepin-daemon 3.27.2.1-1

**Comment by keybreak** [comment]
This was stated before by @electricface as not error, but warning and normal behavior, but again:

Please lower the error level to warning, because **sudo journalctl -p 3 -xb** is strictly for serious errors, and not for warnings / debug purposes.

**Comment by keybreak** [comment]
@BLumia 
Please reopen this and solve, so it wouldn't get lost.

> journalctl -p 0 -xb the number zero is for Emergency and needs fixing, if possible
> journalctl -p 1 -xb the number one is for Alert and should be fixed, if possible
> journalctl -p 2 -xb the number two is for Critical and should be fixed, if possible
> journalctl -p 3 -xb the number three is for Error and should be investigated for a possible fix

Meaning that not errors and warnings must go to this level or even lower:
> journalctl -p 4 -xb the number four will display Warnings, normally not a problem, but looking through may yield interesting info.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
