### ISSUE TITLE
DTK窗口最小化、最大化、关闭按钮鼠标指针手形

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#1244]
DTK窗口的最小化、最大化、关闭按钮鼠标指针需要和GTK主题保持一致！
只需要去掉类似这行即可：
~~pushButton_close->setCursor(Qt::PointingHandCursor);~~

**Comment by doooooit** [comment]
就是说：窗口按钮的指针样式不要用手形，用三角形默认样式更符合习惯

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
