### ISSUE TITLE
Rounded corners for GTK applications

### ISSUE THREAD

**Issue by navdeepio** [linuxdeepin/developer-center#1245]
Deepin has some sweet rounded corners for its native apps but all gtk based applications appear without rounded corners, even with deepin-default gtk theme..

Here's a screenshot, using the Sweet gtk theme

![image](https://user-images.githubusercontent.com/9297865/58471902-9c442300-8162-11e9-9b5d-76d20fcd60a9.png)

**Comment by Lokke** [comment]
can't confirm
![](https://abload.de/img/deepinbildschirmfoto_2yj0z.png)

**Comment by navdeepio** [comment]
Here's what it looks like for me
![image](https://user-images.githubusercontent.com/9297865/58493329-52723180-8190-11e9-8c56-8d8293297a35.png)

Using the deepin default theme...

**Comment by navdeepio** [comment]
I deleted my .config/gtk-3.0 folder and now everything's back to normal. :)
