### ISSUE TITLE
深度文管：去除文件打开选择对话框

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#1247]
![](http://wx1.sinaimg.cn/large/66ad7667gy1g3hza1tq6wj20ts0jj0u2.jpg)

**Comment by BLumia** [comment]
你错误的设置了文件权限导致了这个问题，对于纯文本的非可执行文件，请不要设置可执行权限标记。

**Comment by sonichy** [comment]
这些文件都是【深度文管 - 新建文档 - 文本文档】创建的。

**Comment by BLumia** [comment]
对应的挂载目录的权限是不是不对....... ntfs 吗？

**Comment by redchenjs** [comment]
ntfs文件系统的锅，它不支持使用chmod命令设置文件属性，只能通过挂载选项来给分区内的所有文件设置一个相同的属性。
