### ISSUE TITLE
dde-file-manager: Window maximized state won't remember when closing

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#1248]
## Describe the bug
File Manager does not save the size of the window when closing.

If the window is maximized when closing, the application opens with the window in normal size. This problem has been occurring since version 15.6 or 15.7.

In 15.10.1 (Lion) the problem still persists.

## Expected behavior
Allow File Manager to open in maximized view.

## Screenshots
Attached.

The System Monitor and the Application Store appear to start at the maximized screen. The icon shows this (as pointed by the cursor in the video). File Manager does not start at the maximized screen.

[window.zip](https://github.com/linuxdeepin/developer-center/files/3230698/window.zip)

### Distro & Version
Deepin 15.10.1 (Lion)

### Related package version
dde-file-manager 4.8.4

### Additional context
@BLumia

**Comment by BLumia** [comment]
Would like to fix it later. Patches are also welcome :)

**Comment by keybreak** [comment]
I thought it's intended feature (which at least for my personal workflow works good)

**Comment by alexwender1** [comment]
Recent [post](https://github.com/linuxdeepin/developer-center/issues/1388) on the same subject.

**Comment by BLumia** [comment]
Whoops, I checked the product requirement and position will not be remembered (it's intended). It will remember window size as well.

Thanks for reporting :)

**Comment by alexwender1** [comment]
This fix did not arrive in version 15.11.

**Comment by aiamuzz** [comment]
seems like a **kwin** bug(or a conflict with some default setting) ... however the size and position is perfectly recorded when we switch to `deepin-wm` !

**Comment by BLumia** [comment]
Oh you means remember maximize state, this is a known bug. I remember there is an old issue about this bug but I cannot find that issue atm.. anyway reopened this issue for ya :)

**Comment by alexwender1** [comment]
The problem remains at 20 BETA

**Comment by alexwender1** [comment]
The problem in File Manager was resolved in deepin 20 (1001).

@xmuli If possible, check the App Store; because it presents the same problem.

**Comment by xmuli** [comment]
@alexwender1  Thank you
