### ISSUE TITLE
15.10.1 stable系统中RTL8723BE网卡蓝牙问题

### ISSUE THREAD

**Issue by CJ6922G1CH** [linuxdeepin/developer-center#1249]
## 缺陷描述
RTL8723BE网卡在15.10.1 stable系统中无法使用蓝牙

## 复现步骤
$ dmesg|grep bluetooth输出
[    6.149018] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723b_config.bin failed with error -2

## 截图
![image](https://user-images.githubusercontent.com/47511859/58555515-46e44080-824c-11e9-8135-d929814b3d08.png)
无法搜索到蓝牙设备

### 发行版以及版本
Deepin 15.10.1 stable

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
