### ISSUE TITLE
esc键关闭搜索框与雷神模式时无法全屏

### ISSUE THREAD

**Issue by ListenerRi** [linuxdeepin/developer-center#125]
>当前操作系统: archlinux
>当前桌面环境: dde
>虚拟终端: deepin-terminal

1. ctrl+shift+f调出搜索框后, 按esc键会退出整个terminal
2. 当处于雷神模式时无法全屏(难道是故意这样设计的?)

**Comment by manateelazycat** [comment]
这个估计是 arch 在输入法的问题, 具体可以问 @felixonmars

**Comment by felixonmars** [comment]
这还是之前说的 xim 输入法问题吧……？

**Comment by manateelazycat** [comment]
@felixonmars 是哒是哒

**Comment by felixonmars** [comment]
DDE 快捷方式启动 deepin-terminal 会导致环境变量清空吗？
如果不是这个问题，请检查你的 fcitx 环境变量设置。我放在 /etc/environment 是没问题的。

**Comment by ListenerRi** [comment]
@felixonmars 我的fcitx环境变量应该是没有问题的, 我将其配置到了~/.xinitrc文件中, 在xfce4和i3wm下都可以正常使用, 唯有dde有问题, 而且并不是一开始就有问题, 好象是更新了某个dde相关的包之后才有的(可能是deepin-wm??不能确定..), 我现在已经换到ibus+rime了

**Comment by felixonmars** [comment]
某些方式启动可能会清空环境变量。你可以在运行的终端里打 env 确认。

**Comment by hualet** [comment]
可以对比一下快捷键启动的时候和从Launcher/Dock启动的时候，环境变量的差异
