### ISSUE TITLE
[Arch Deepin] deepin-kwin have no animations on virtual box VM

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#1250]
## Describe the bug
All in title, it doesn't have any animations on Virtual box VM, Linux Deepin 15.10 and KDE have them  for example.

This is big deal for testing.

**Comment by BLumia** [comment]
Are you using dde-kwin without compositing enabled? If you do, it should have animations, if not, of course it will not have any animation.

**Comment by keybreak** [comment]
@BLumia 
If you mean **Window Effect** in settings it is enabled

**Comment by BLumia** [comment]
`Window Effect` actually is compositing enabled.

We didn't do anything with virtualbox checking so there will have animation if compositing is enabled, and KDE should works the same (please notice that, by saying "the same", I means the KDE vendored from Linux Deepin 15.10) as DDE's dde-kwin.

You can also check the behavior of kwin by installing `systemsettings` package from Deepin, btw.

Any screen record available so we can check what happend?

**Comment by keybreak** [comment]
> Any screen record available so we can check what happend?

No, but i'm not sure what to screencapture - there are just no animations at all (0 fade times), if you need something specific i can provide it :)

What i did was:
1. Install fresh Arch Deepin
2. Install **deepin-kwin**
3. Reboot

Nothing fancy, and it's repeatable.

VMWare is a little different, i think it must be VirtualBox specific, something must be missing in Arch, since Linux Deepin 15.10 works fine and have animations.

> btw, and kwin itself have a failsafe mode, it will disable compositing when OpenGLIsUnsafe=true (kwin will set it to true if compositing caused crash or unstable behavior).

**~/.config/kwinrc**
```
[Compositing]
OpenGLIsUnsafe=false
...
```

> You can also check the behavior of kwin by installing systemsettings package from Deepin

From Deepin? There's only KDE / Plasma **systemsettings** for me in Arch..

**Comment by BLumia** [comment]
> if you need something specific i can provide it 

So did you check the settings inside `systemsettings` matched what you got?

> From Deepin? There's only KDE / Plasma systemsettings for me in Arch..

I means the `systemsettings` package vendored by Deepin package repo, it used names `systemsettings5` in deepin unstable. It of course is a KDE app.

**Comment by BLumia** [comment]
Whoops, sorry I misunderstand a little bit.. I though Deepin 15.10 inside VirtualBox also doesn't have animations (so that's why I want you install systemsettings from Deepin).

So on the same Arch installation, in DDE there is no animations but compositing is enabled, but in KDE both of them works? If it is, could you launch KDE system settings from your Arch installation inside DDE and check if the settings matchs what you actually got?

**Comment by keybreak** [comment]
> So on the same Arch installation, in DDE there is no animations but compositing is enabled, but in KDE both of them works?

Yes

> If it is, could you launch KDE system settings from your Arch installation inside DDE and check if the settings matchs what you actually got?

Sure, but what exactly should i look for?

![image](https://user-images.githubusercontent.com/47599989/58625564-64142000-82db-11e9-8c99-b21b93adf87e.png)


I expect **deepin-kwin** on Arch having animations exactly as on Linux Deepin 15.10 out of the box by default, so assuming there shouldn't be any additional manual settings needed after **deepin-kwin** installation on Arch?

**Comment by keybreak** [comment]
Here's fore example no animation on menu:
https://i.imgur.com/MYJOtvj.mp4

Same for windows and anything else in the system.

**Comment by justforlxz** [comment]
> Here's fore example no animation on menu:
> https://i.imgur.com/MYJOtvj.mp4
> 
> Same for windows and anything else in the system.
> 
> Could it be that Arch Deepin by default miss something from OpenGL, that KDE have as dependency?

On my laptop is normal, I am running archlinux and the latest dde.

![深度录屏_dde-desktop_20190530184340](https://user-images.githubusercontent.com/12298476/58627974-131c2000-830b-11e9-94e1-c664214c22b7.gif)

**Comment by antechdesigns** [comment]
@justforlxz @BLumia 

Just so we are clear here, @keybreak is talking about Arch - `deepin-kwin` under virtualbox not `dde-kwin` under virtualbox which is Original deepin.

I will check on my **archlinux deepin-kwin** and report back ;)

**Comment by keybreak** [comment]
@justforlxz 
Yes, i know that it works on hardware, but specifically on VirtualBox for some reason it's not..

**Comment by antechdesigns** [comment]
adding
```
[Compositing]
Enabled=true
OpenGLIsUnsafe=false
```
to the kwinrc gets the blur working...

**Comment by keybreak** [comment]
>  does it work if you change 'Rendering Backend' to 'Xrender' I don't have the 'systemsettings' installed?

Yes, animations of menus / windows works this way, but blur is gone :laughing:

**Comment by keybreak** [comment]
Just checked original Linux Deepin 15.10 on virtualbox VM, it have both animations and OpenGL enabled...

Very interesting :thinking:

**Comment by keybreak** [comment]
@felixonmars 
How about you on Arch VirtualBox VM?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
