### ISSUE TITLE
QIcon::fromTheme 的 edit-delete 图标不对

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#1251]
删除变垃圾桶
![](http://wx3.sinaimg.cn/large/66ad7667gy1g3j8the0xpj20vi0jrb2a.jpg)

**Comment by BLumia** [comment]
垃圾桶表示删除也没毛病啊？

**Comment by redchenjs** [comment]
:laughing:

**Comment by BLumia** [comment]
![(H2~BGOOU_~8`3NDTUG$VDP](https://user-images.githubusercontent.com/10095765/58610555-69269e80-82de-11e9-9b8b-f55120d874f0.png)

左到右分别是：Papirus，breeze，deepin。

垃圾桶图标没有问题，你可能要找的不是这个名字。你可能想要的是 `edit-clear` ？
