### ISSUE TITLE
dde-kwin在无特效状态下，通过任务组切换窗口，会导致任务栏异常退出

### ISSUE THREAD

**Issue by izee** [linuxdeepin/developer-center#1252]
## 缺陷描述
dde-kwin在无特效状态下，通过任务组切换窗口，会导致任务栏异常退出

## 复现步骤
1. 关闭窗口特效
2. 打开 '应用商店'
3. 通过应用商店启动`2`个firefox进程
4. 在任务栏中，选择firefox任务组中的任意一个窗口
5. 任务栏消失并自动恢复。

## 期望行为
正常切换窗口

## 截图
![image](https://user-images.githubusercontent.com/1017740/58619575-bb27ee00-82f7-11e9-922b-db6f2033db18.png)
![image](https://user-images.githubusercontent.com/1017740/58619611-cd099100-82f7-11e9-8287-e247f09a2680.png)

## 复现环境:
esxi虚拟机

### 发行版以及版本
Linux Deepin 15.10.1

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
