### ISSUE TITLE
Visual Studio Code Icon doesn't display correctly in the dock

### ISSUE THREAD

**Issue by navxio** [linuxdeepin/developer-center#1256]
![image](https://user-images.githubusercontent.com/9297865/58694180-0bfb1d80-83b0-11e9-9da7-ca4415a856f7.png)
In the dock, it's a generic Electron icon although in the launcher menu everything shows up fine..
![image](https://user-images.githubusercontent.com/9297865/58694206-1ddcc080-83b0-11e9-918d-f504b9a2a851.png)

When I dock this icon, the it stores a reference to Electron rather than VS Code..

I'm using archlinux and the package in question is `community/code`

**Comment by Paradoxeuh** [comment]
If you go to /usr/share/applications and open code-oss.desktop and comment the line #StartupWMClass=Code, then it works. I have no idea why though.

**Comment by BLumia** [comment]
@electricface any idea?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
