### ISSUE TITLE
Hot corners bug

### ISSUE THREAD

**Issue by dusatvoj** [linuxdeepin/developer-center#1257]
## Describe the bug
Hot corners are not on primary monitor but on the top monitor. And settings etc. opened from corners are shown on primary monitor.

## To Reproduce
To reproduce connect two monitors, assign them above each other and set the lower one as primary

## Expected behavior
Corners and settings should be locked on primary screen

### Distro & Version
 - Newest arch linux with deepin desktop

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
