### ISSUE TITLE
1 workspace for secondary monitor [feature request]

### ISSUE THREAD

**Issue by atishpatel** [linuxdeepin/developer-center#1258]
Currently every monitor has a workspace, but for the workflow i use, it's better for me to have a static workspace on my external monitor and 4 workspaces on my main monitor. 

There is a setting similar to this in the Gnome Tweak tools. 
![Screenshot from 2019-05-31 15-51-39](https://user-images.githubusercontent.com/6618430/58735354-c3e3f700-83bf-11e9-85ea-435647ac08ce.png)

Does the feature request make sense?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
