### ISSUE TITLE
调用 Electron 接口添加文件到最近文件列表,使用深度的文件管理器无效

### ISSUE THREAD

**Issue by 1797890817** [linuxdeepin/developer-center#1263]
# 问题

使用 Electron 提供的添加文件到最近文件的接口添加最近文件，深度文件管理器不会显示添加的项目。

# 详细信息

附件为对应出错的 xbel 文件和复现代码

[ch6.zip](https://github.com/linuxdeepin/dde-file-manager/files/3246304/ch6.zip)
[recently-used.xbel.zip](https://github.com/linuxdeepin/dde-file-manager/files/3246305/recently-used.xbel.zip)

``` plain
dbdu@dbdu:~/.local/share$ cat recently-used.xbel | grep deepin15.10
  <bookmark href="file:///home/dbdu/Desktop/deepin15.10%E9%97%AE%E9%A2%98.txt" added="2019-05-09T00:37:06Z" modified="2019-05-16T08:34:49Z" visited="2019-05-16T08:34:49Z">
  <bookmark href="file:///media/dbdu/Data/deepin15.10%E9%97%AE%E9%A2%98.txt" added="2019-06-03T06:16:50Z" modified="2019-06-03T06:19:03Z" visited="2019-06-03T06:16:50Z">
14:39:42
```

原始 issue 内容请参见编辑记录。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
