### ISSUE TITLE
[bug] deepin-kwin enlarges deepin-terminal everytime when it is unminimized

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#1264]
## Describe the bug

deepin-kwin enlarges deepin-terminal's window when we unminimize it after minimizing it.
## To Reproduce

1. Open `deepin-terminal` from the dock.
2. Minimize it.
3. Unminimize it by clicking on it in the dock.
4. `deepin-terminal` gets bigger each time you repeat the steps from step 2.
## Expected behavior

deepin-terminal should not get bigger.
## Screenshots

![deepin-screen-recorder_Select area_20190603141742](https://user-images.githubusercontent.com/33563064/58786897-68f21000-860a-11e9-9886-f15b6a4c36b8.gif)

## Enviroments:
Deepin Desktop Environment

### Distro & Version

Distro: Archlinux

### Related package version

deepin-kwin v.0.0.7-2
deepin-terminal v.3.2.5-1

**Comment by BLumia** [comment]
There should be a hot fix version soon. Please track this issue at: https://github.com/linuxdeepin/deepin-terminal/issues/168
