### ISSUE TITLE
VirtualBox机器运行中键盘被捕获模式下，deepin休眠后唤醒（锁屏）无法输入密码等

### ISSUE THREAD

**Issue by ihipop** [linuxdeepin/developer-center#1265]
## 缺陷描述
VirtualBox机器运行中键盘被捕获模式下，deepin休眠后唤醒（锁屏）无法输入密码
## 复现步骤

1. 开启合盖子自动休眠和休眠后恢复需要输入密码（锁屏）

1. 开启一个VirtualBox虚拟机，移动鼠标进入虚拟窗口区域，并且在里面打开文本编辑器打字，确保键盘处于捕获模式

1. 直接合上Deepin的笔记本盖子使其休眠，观察指示灯确保休眠已经成功进入

1. 打开笔记本盖子 确保deepin唤醒，出现登录界面 发现无法输入密码

## 期望行为

期望登录界面可以正常输入密码登录，实际上会发现登录界面的输入框没有光标，输入任何东西都没反应，通过tty控制vbox正常挂起
```bash
export DISPLAY=:0
vboxmanage  controlvm  'Windows 7 X64'  savestate
killall dde-lock
```
以后，锁屏界面才能正常输入密码解锁，登录后恢复在tty里面被挂起的虚拟机 会发现之前的密码输入到了虚拟机的文本编辑器里面

### 发行版以及版本

很早就发现了这个问题 以前都是直接tty下`killall dde-lock` 现在的版本（15.10）有锁屏守护，所以只能通过命令行休眠vb虚拟机

**Comment by ihipop** [comment]
# 场景2 非休眠时候锁屏导致的无法解锁

1. 开启一个VirtualBox虚拟机，移动鼠标进入虚拟窗口区域，并且在里面打开文本编辑器打字，确保键盘处于捕获模式

1. 按下键盘的右边的CTRL按键，脱离捕获模式，然后立刻按下deepin的锁屏快捷键 win+L

1. 出现登录界面 发现无法输入密码

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
