### ISSUE TITLE
越用越卡

### ISSUE THREAD

**Issue by caicry** [linuxdeepin/developer-center#1266]
deepin感觉并不是合适用来做编译服务器，比如android的编译，效率很差。
换装了ubunut后，速度恢复正常，是否与anything有关呢？

**Comment by caicry** [comment]
现在已经装了Ubuntu了，之前观察，在编译安装的时候，everything有一定的资源占用，不高2%左右，i7的CPU，但确实影响到了磁盘的IO。
以上纯属使用体验，没有做详细的数据测试

**Comment by BLumia** [comment]
everything? 是想说 anything 吗

anything 创建索引时的资源占用优先级已经下调了，应该下次推送会更新。

没有详细信息的话这 issue 我就先关掉了，不然开着也没法解决..
