### ISSUE TITLE
Deepin安装器不要限制/boot只能用ext2/3/4

### ISSUE THREAD

**Issue by abcfy2** [linuxdeepin/developer-center#1267]
## 缺陷描述
到了今时今日，grub已经不止支持ext系列做/boot了，我测试过除了ext系列之外，xfs, btrfs, jfs都可以做/boot

## 复现步骤

打开安装器，在分区安装步骤，如果/boot不是ext系列报错不让过

## 期望行为

可以支持其他grub支持的文件系统，对于我这种一根到底的分区方式强迫症有帮助。实在不怎么想用ext4了

### 发行版以及版本

Linux Deepin 15.10.1

**Comment by meiyixiang** [comment]
26/5000 
Currently, the installer is planned to support BTRFS and install the BOOT partition
