### ISSUE TITLE
Could not load wine-gecko. HTML rendering will be disabled.

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#1268]
deepin-wine SpeedPan.exe，点击登录，登录窗口一片空白。
apt-get install libwine-gecko-2.21 后依然不行。
deepin-wine iexplore http://www.163.com 同样空白，同样错误。

**Comment by BLumia** [comment]
尝试直接使用 wine （而不是 deepin-wine ）呢？

**Comment by sonichy** [comment]
将SpeedPan的Chromium插件下载解压到SpeedPan目录，再运行程序，登录时程序将自动调用Chormium完成登录，对于IE有问题或者XP系统（Wine）可以使用此扩展。
