### ISSUE TITLE
鼠标双击打开可执行的desktop文件方式

### ISSUE THREAD

**Issue by ListenerRi** [linuxdeepin/developer-center#127]
目前, dde下鼠标双击打开可执行的desktop文件, 当desktop文件要求在terminal下运行时会调用xterm, 而不会使用系统默认的terminal来执行, 如何修改为系统默认的terminal呢? 如deepin-terminal?

**Comment by manateelazycat** [comment]
@ListenerRi 你用的是 deepin 系统还是 arch linux ? ；）

**Comment by ListenerRi** [comment]
@manateelazycat 使用的是arch linux

**Comment by manateelazycat** [comment]
@ListenerRi GLib 里面写死了用 gnome-terminal, xterm, 如果 gnome-terminal 没有在系统中预装， 就会强制用 xterm, 这个需要 @felixonmars 给 GLib 打补丁才行。

**Comment by ListenerRi** [comment]
@manateelazycat 既然是dde的环境, 再怎么的也得第一个检测deepin-terminal吧...

**Comment by manateelazycat** [comment]
@ListenerRi 你没有明白， GLib把gnome-terminal, xterm写死在代码里面， deepin/debian 里面也是要给 glib 打补丁 deepin 系统才能发现当前设置的终端， 而不是像 glib 那样写死。

需要 @felixonmars 打补丁， 补丁 deepin 团队有。 :)

**Comment by manateelazycat** [comment]
@ListenerRi DDE 也允许设置成其他终端， 打完补丁以后， 要把 glib/gio 从写死终端的行为变成查找用户设置的默认终端。

**Comment by ListenerRi** [comment]
那这个问题能不能在下个更新解决呢? : )

**Comment by manateelazycat** [comment]
@ListenerRi 只要 @felixonmars 给 glib 打上补丁就行了， 不需要等下一个dde版本。

**Comment by ListenerRi** [comment]
@manateelazycat 好滴

**Comment by ListenerRi** [comment]
@manateelazycat 怎么这个问题还在...

**Comment by CarloQ** [comment]
@ListenerRi 你得留意下 glib 的更新。。。
