### ISSUE TITLE
Replace hard-coded '/usr/lib/' with macro/variable in codes

### ISSUE THREAD

**Issue by cheese** [linuxdeepin/developer-center#1271]
## Describe the bug

This will benefit packaging for other distributions. Other distributions like Arch or Fedora use a different filesystem layout convention, especially where to put shared libraries and private executables.

For example, Fedora uses `/usr/lib64` as the directory for shared libraries of x86_64 arch, and uses `/usr/libexec` for private executables.

Currently, we use `sed` to fix the hard-coded `/usr/lib` in codes. But this is not easy to maintain. Packages may contains new or less usages of `/usr/lib` in new commits. And packagers may be not aware and fail to fix them or remove redundant usages of `sed`.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
