### ISSUE TITLE
user with empty password cannot resume from deepin-lock

### ISSUE THREAD

**Issue by cheese** [linuxdeepin/developer-center#1273]
## Describe the bug

A user was created with no password and autologin. The user can login session at boot. But if the screen is locked, the user cannot resume from deepin-lock since it does not acept empty password.

It is reproducible with Fedora Live ISO. The default user is `liveuser`.
ISO can be download from Baidu Yunpan:
https://pan.baidu.com/s/1HZcYRDXIUze2pQjPmqTDcw 
code: ikog 
## To Reproduce

1. Boot the LiveISO
2. Lock the sreen
3. Try to resume 

## Expected behavior

Resume succeeded
### Distro & Version

Fedora 30
### Related package version

deepin-session-ui-4.9.8

**Comment by Lokke** [comment]
https://github.com/linuxdeepin/developer-center/issues/162

**Comment by cheese** [comment]
> #162

Adding `liveuser` to `autologin` group does not help

**Comment by cheese** [comment]
Adding `liveuser` to `nopasswdlogin` group also does not help.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
