### ISSUE TITLE
File searching no longer works

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/developer-center#1274]
https://youtu.be/DSzbKrMug4c

**Comment by keybreak** [comment]
Yeah i confirm this. on all of my machines, happens for example with .pacnew files on Arch / Manjaro after updates - you can see new files, but they're not included in search.

Looks like live search is not actually working properly...

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
