### ISSUE TITLE
设置标准字体为Zfull-gb以后，很多地方字体并没有使用我设置的这款点阵字体

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1275]
我在个性化-》字体里面配置了我选择的字体Zfull gb（一款点阵字体），我的显示器分辨率较低，所以希望使用点阵字体显示效果好些。
然后发现文件管理器字体，桌面图标文件名，还有几乎所有deepin自己开发自带的软件都没有使用我设置的这款字体，还有几乎所有地方右键菜单字体也没有使用我设置的。

deepin在美化上是做了功夫的，看得见成效，但是字体是美化中非常重要的一环，如果没有好的字体，显示效果要大大打折扣。

在gnome下，我可以使用gnome tweak把所有字体设置成Zfull gb，然后所有gnome开发的软件齐刷刷的就是用我选择的字体，效果很好。这也是我选择gnome的原因之一。

希望deepin重视、加强一下这方面。我想要的效果是设置了字体为我选择的点阵字体Zfull gb以后，所有系统软件、应用软件菜单、右键菜单等等地方都是用我设置的这款字体，如果想做的更好一些，还可以像gnome、或者windows一样分开各个部分设置，但是首先字体设置了，效果要有，不要不生效。

**Comment by widon1104** [comment]
我现在在真机上装了deepin15.10.1，上传一张图，可以对比一下终端的那一句话“这才是Zfull gb字体的显示效果”字体的显示效果和桌面图标文件名的显示效果，差距很大。
![字体显示效果](https://user-images.githubusercontent.com/12093211/59552599-addb5680-8fbb-11e9-96fb-8c3e6219acad.png)

**Comment by widon1104** [comment]
提醒一下qt5渲染点阵字体有bug，qt5程序如果开启抗锯齿点阵字体会渲染的像矢量字体，变得很丑
我已经报了一个bug，但是没人fix这个bug
https://bugreports.qt.io/browse/QTBUG-71867

**Comment by justforlxz** [comment]
![image](https://user-images.githubusercontent.com/12298476/59838671-ea270200-9381-11e9-9e85-4a5141fa08fc.png)

我觉得吧，也不是所有的gtk都支持 ：）

**Comment by widon1104** [comment]
今天用 sudo apt-get install xfonts-wqy 安装了wqy点阵宋体，设置了这款点阵字体以后，设置界面字体，右键菜单，桌面图标字体，深度文件管理器等都设置成了wqy点阵宋体，我感觉deepin系统自带软件对这款软件支持还是比较好的
但是wqy点阵宋体这款字体有问题，在很多流行软件上面都有很差的效果，具体可以看
https://github.com/linuxdeepin/developer-center/issues/1304
最后我widon1104的在16楼的留言，wqy点阵宋体在firefox浏览器，网易云音乐，liteide，terminator终端上面都有不好的表现，我直接弃用了这款字体。

如果deepin能够支持wqy点阵宋体这款字体，也能支持Zfull gb这款字体，Zfull gb我用了几年了，几乎没有啥问题，无论作为系统字体，浏览器字体，还是终端字体，编程编辑器字体都能很好的胜任。而wqy点阵宋体 0.99版居然是07年的产物。早就落后于时代了。

**Comment by widon1104** [comment]
Zfull gb里面的点阵是基于zpix-pixel-font
zpix pixel font个人使用是免费的，所以deepin支持Zfull gb以后可以让用户自己安装这款字体使用
![zpix pixel font](https://user-images.githubusercontent.com/12093211/59909679-d1325580-9442-11e9-8b1a-eef372811c49.png)

**Comment by widon1104** [comment]
从deepin只支持wqy点阵宋体不支持其他点阵比如宋体，Zfull gb，wqy点阵正黑的情况来看，难道底层代码是对wqy点阵宋体进行特判处理的吗？
我觉得特判不好，其实如果让qt5在开启抗锯齿的情况下也能正确显示点阵字体的话，所有点阵字体显示应该都会正常。

**Comment by BLumia** [comment]
> 个人使用是免费的

免费不等于自由。

> 而wqy点阵宋体 0.99版居然是07年的产物。早就落后于时代了

 1. 软件开发功能完备的情况下，仅仅因为没有必要更新，就应该被称呼为“落后”？
 2. [文泉驿仍有在活跃的开发中](https://wenq.org/wqy2/index.cgi?action=rc&days=90)
 3. 文泉驿是自由字体，如果你认为存在问题，应该考虑反馈给维护者一同完善软件，或者直接参与到它的开发中。吐槽无助于字体本身的改善

> 我觉得特判不好

在你不确定行为的时候请不要把观点建立在你的假设上来评判。

另：我认为你应该读一下 [提问的智慧](https://www.dianbo.org/9238/stone/tiwendezhihui.htm) 和 [有效沟通](https://opensource.guide/zh-cn/how-to-contribute/#%E6%9C%89%E6%95%88%E6%B2%9F%E9%80%9A) 。

**Comment by widon1104** [comment]
> 我认为你应该读一下 [提问的智慧](https://www.dianbo.org/9238/stone/tiwendezhihui.htm) 和 [有效沟通](https://opensource.guide/zh-cn/how-to-contribute/#%E6%9C%89%E6%95%88%E6%B2%9F%E9%80%9A) 。

我觉得你老是喜欢挑刺，还希望教育别人，这是不好的。
我作为一个deepin用户说了那么多，但是你们总是拒绝做任何改进，感觉和gnome那帮人差不多，非常懒惰。

**Comment by BLumia** [comment]
错了就是错了，我们没有使用特判的情况下就枉然按我们以特判的形式来批评我们是不对的，请先矫正自己的错误再来指责开发人员。（另：无论是对开发人员还是社区贡献者，枉然而无意义的指责都是无助于整个社区的生态的，请拿出切实依据来帮助改善整个过程，而不是完全建立在自己的假设上，不付出任何努力工作的单纯的指责）

另外，社区版作为社区产品，我们希望的是所有社区人员一同努力来改善产品，而不是随着个人喜好而不顾缘由的乱改一通，对于产品/设计已定义行为的情况更是如此。

请保持内容在主题上，感谢。

字体制作过程中存在很多比较复杂的地方，个人制作的字体很可能在部分属性元信息中存在问题，对于非自由字体（Zfull-gb），我们没有理由耗费额外的工时对其进行支持甚至是特判，所以此类问题请优先考虑找作者寻求支持。对于文泉驿，我无法在我的任何 DDE 环境（包含一个 Virtual Box 的 Deepin stable 安装，以及实体机开发环境）重现所述问题，故请提供进一步的信息帮助定位问题。

**Comment by widon1104** [comment]
> 对于文泉驿，我无法在我的任何 DDE 环境（包含一个 Virtual Box 的 Deepin stable 安装，以及实体机开发环境）重现所述问题
#1304 16楼的问题你那边不能重现？我这边台式机和一台笔记本都会出现同样的问题，文泉驿点阵宋体论坛打不开，bugzilla需要翻墙也打不开，咋个去报问题。

我现在改用苹方字体了。

**Comment by BLumia** [comment]
> > 对于文泉驿，我无法在我的任何 DDE 环境（包含一个 Virtual Box 的 Deepin stable 安装，以及实体机开发环境）重现所述问题
> 
> #1304 16楼的问题你那边不能重现？我这边台式机和一台笔记本都会出现同样的问题，文泉驿点阵宋体论坛打不开，bugzilla需要翻墙也打不开，咋个去报问题。

不能复现，能我就 reopen 那个 issue 了。

那个问题的相关讨论请到那个 issue 下。抱歉我刚刚看错 issue 号了。

**Comment by widon1104** [comment]
不是15楼，是16楼
https://github.com/linuxdeepin/developer-center/issues/1304#issuecomment-504307127
这几个问题你那边都不能重现？

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
