### ISSUE TITLE
deepin设置显示不全，只显示一半

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1276]
系统deepin15.10.1 装在虚拟机virtualbox6里面的，跟系统分辨率没啥关系，我把分辨率调成1360*768也是同样的问题  
明明可以2列把设置选项全部显示出来，但就显示一列，另一列呢，显示不出来  
![deepin15 10设置界面不正常](https://user-images.githubusercontent.com/12093211/59112938-a6da9580-8976-11e9-83ed-9054d7fbbc8d.png)

**Comment by justforlxz** [comment]
https://github.com/linuxdeepin/developer-center/issues/1304
