### ISSUE TITLE
sogou输入法候选词后面有黑框 

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1278]
系统deepin15.10.1 CPU和显卡都是AMD的，应该跟显卡没啥关系，原版ubuntu下好好的，没这个问题  
![095830aw6we4ewuxxve17h](https://user-images.githubusercontent.com/12093211/59114802-8f9da700-897a-11e9-9495-c78ad7c35774.png)

**Comment by BLumia** [comment]
从你之前提到的几个 Issue 推测，可能是由于你在使用 VirtualBox 导致的性能原因，你可能没开混成（或者由于性能或其他原因，被认为混成无法正常工作所以被自动关掉了）。

如果确认是混成没有开启的原因的话，没有混成是不支持透明效果的，这个是正常现象，请考虑打开混成（在控制中心切换为 “3D” 窗管）。

**Comment by widon1104** [comment]
我不知道什么叫做“混成”，可否告诉我具体在哪里打开混成，我在控制中心没有找到切换为3D的地方

**Comment by BLumia** [comment]
是指窗口管理器的 Compositing ，控制中心切换窗口特效那里会显示 3D 窗管还是 2D 窗管。目前手头没有在跑 DDE 所以没法截图具体位置给你了，还请先自己找一下。

**Comment by widon1104** [comment]
我把窗口特效打开，搜狗输入法黑框的问题解决了，但是我其实不想开特效，因为我的CPU比较慢，电脑比较老，我希望的是高性能，不要卡就可以了，特效我倒不是特别需要。

**Comment by BLumia** [comment]
> 我把窗口特效打开，搜狗输入法黑框的问题解决了，但是我其实不想开特效，因为我的CPU比较慢，电脑比较老，我希望的是高性能，不要卡就可以了，特效我倒不是特别需要。

或许可以考虑换不需要透明支持的搜狗输入法皮肤，也可以考虑尝试其他的输入法，比如 RIME。

确认是搜狗输入法的问题的话可以考虑反馈给搜狗那边了。由于搜狗输入法并不是深度的产品，所以深度的开发也没法解决这个问题..
