### ISSUE TITLE
请求置顶功能，和录入帐户名功能

### ISSUE THREAD

**Issue by htqx** [linuxdeepin/developer-center#1279]
## 期望行为
1. 希望增加窗口置顶功能，这是kwin的能力范畴，能增加工作效率。
2. 希望登录账户时可以选择录入帐户名，解决登录windows域的问题。

### 发行版以及版本
15.10.1

### 相关的软件包版本
deepin-kwin
lightdm

**Comment by BLumia** [comment]
下次推送更新就会把标题栏右键菜单加回来了（虽然和kwin本身的有区别），不过下次社区版推送时间还没确定。

**Comment by htqx** [comment]
> 下次推送更新就会把标题栏右键菜单加回来了（虽然和kwin本身的有区别），不过下次社区版推送时间还没确定。

希望增加一个快捷键，因为我现在通过黑客的手段使用了kwin来设置快捷键，感觉还是挺好用的。因为它同时适用与wine程序，我不知道你说的菜单能不能作用于wine程序。
总之，如果可以，请增加一个快捷键。

**Comment by BLumia** [comment]
快捷键的需求可以另开一个 issue （也希望尽可能保持一个 Issue 只专注讨论一个问题）。

**Comment by BLumia** [comment]
目前的版本已经涵盖窗口置顶了，先关掉了。

其它需求和问题请开新的独立 issue 讨论以便 issue 索引和管理～
