### ISSUE TITLE
Unable to delete Pictures Directory  in $HOME

### ISSUE THREAD

**Issue by Nhoya** [linuxdeepin/developer-center#128]
Hey there, actually i'm trying to delete the Pictures directory in my home but after each reboot it is recreated by something, i actually disabled the xdg-user-dirs config so i can delete Directories like Downloads and Documents but still can't remove the Pictures dir, any suggestions?

**Comment by funilrys** [comment]
Any feedback @Nhoya ?

We (maybe) can close this @hualet

**Comment by hualet** [comment]
@jouyouyun ?

**Comment by funilrys** [comment]
I'm sorry I have a ton of pictures on that folder, can't test it now @hualet Gonna keep you up after test :+1:

**Comment by jouyouyun** [comment]
The `dde-session-daemon` need the directory`$PICTURE` , if no-exists, will create it.
