### ISSUE TITLE
nano快捷键不正常

### ISSUE THREAD

**Issue by htqx** [linuxdeepin/developer-center#1280]
## 缺陷描述
1. nano 快捷键，复制alt+6 无效
2. konsole + nano 正常。

## 复现步骤
1. alt + 6 复制一行
2. ctrl + u 粘贴

## 期望行为
alt + 6 复制正常

### 发行版以及版本
15.10.1

### 相关的软件包版本
nano
deepin-terminal

**Comment by BLumia** [comment]
确认可复现，Alt+上方数字键均无效。回头看看。

**Comment by BLumia** [comment]
:sweat: 这个确认是 feature 了，是用来切换终端标签页的...

cc: @wangjia12

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
