### ISSUE TITLE
The applet for wifi shows wrong network.

### ISSUE THREAD

**Issue by daxid** [linuxdeepin/developer-center#1281]
## Describe the bug

The applet for wifi network shows that I am connected to a wrong network.
It happens for instance after resuming from suspend, but not only. Refreshing available networks does nothing.

See first screeshot for what is shown in the control centre (right), and second screenshot for what is shown in the applet (wrong).

## To Reproduce

See the description.

## Expected behavior

Well, to show the correct network I am connected to in the applet !

## Screenshots

![screenshot2](https://user-images.githubusercontent.com/12066206/59148529-662c5c00-8a0a-11e9-8b21-24e3ea81fb50.png)
![screenshot1](https://user-images.githubusercontent.com/12066206/59148530-66c4f280-8a0a-11e9-9d41-278693b6733d.png)

### Distro & Version

Antergos

### Related package version

Last available packages in Arch repositories

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
