### ISSUE TITLE
Grub Screen Delay

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#1282]
## Describe the bug
In the boot settings, when the boot delay is disabled; the Grub takes the standby time of 1 second:

_GRUB_TIMEOUT=1_ in **/etc/default/grub**

## Expected behavior
Is it possible that this value is _**0 seconds**_? If the user has disabled the startup delay; he has no interest in seeing the Grub screen.

## Screenshots
![Captura de Tela_selecionar área_20190609015829](https://user-images.githubusercontent.com/45263160/59155172-1bd2cb80-8a5a-11e9-94cd-7139753a1966.png)

### Distro & Version
Deepin 15.10.1 Lion

**Comment by TeknoMobil** [comment]
Can systemd-boot support for the menu?

systemd-boot is a clean boot with vendor logo.
If you use systemd-boot instead of grub in Arch setup

**Comment by alexwender1** [comment]
> Can systemd-boot support for the menu?
> 
> systemd-boot is a clean boot with vendor logo.
> If you use systemd-boot instead of grub in Arch setup

Is that what you mean? Interesting.
https://bbs.deepin.org/forum.php?mod=viewthread&tid=176236&extra=page%3D7

@BLumia Is it possible for Deepin to use this boot?
