### ISSUE TITLE
请求显卡驱动管理器增加 vulkan 支持

### ISSUE THREAD

**Issue by ShuiHuo** [linuxdeepin/developer-center#1284]
## 缺陷描述
显卡驱动管理器没有提供 vulkan 的支持

## 期望行为
1. 安装驱动的时候同时安装 vulkan 有关的包
2. 给当前勾选的驱动提供 vulkan 有关的按钮

## 截图

大概是这个意思
![深度截图_选择区域_20190612053255](https://user-images.githubusercontent.com/7471938/59308826-960e8480-8cd4-11e9-9092-d2e536a084f1.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
