### ISSUE TITLE
Translations do not appear

### ISSUE THREAD

**Issue by TeknoMobil** [linuxdeepin/developer-center#1285]
Hi
Right-click deepin-menu only appears in English. The Turkish translation has been fully done but does not appear.

Distro tested: Arch Linux, Deepin offical, Fedora
All have the same problem

Currently one of the distribution I use current Arch Linux

![Ekran Görüntüsü - 2019-06-11 22-51-26](https://user-images.githubusercontent.com/42881121/59302045-b706b380-8c9b-11e9-8912-c1958b9a6383.png)

**Comment by zhuxiujuancindy** [comment]
> Well this is a part of dde-kwin, did that project has been fully translated to Turkish?
> 
> cc @zhuxiujuancindy

dde-kwin is fully translated into Turkish

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/dde-kwin/blob/0.0.9/plugins/kwin-xcb/plugin/translations/dde-kwin-xcb_tr.ts

Seems it already contains the translation, I'm not sure about this.

cc @zccrs

**Comment by keybreak** [comment]
This was known bug, as far as i remember, same on russian and any other language for this menu

**Comment by TeknoMobil** [comment]
deepin-kwin is not installed by default.
Now I have setup, the menu does not appear at all, The system now looks like Kde

dde-kwin seems to be not a ready project, thanks

**Comment by TeknoMobil** [comment]
Only the existing layout needs to be given language support.

dde-kwin and kwin do not fit into the deepin window layout, resulting in a bad Kde appearance.

**Comment by BLumia** [comment]
Oops, I though you are reporting a dde-kwin issue, sorry.

Then maybe you can look at [`deepin-wm`](https://github.com/linuxdeepin/deepin-wm) and check if translation is completed?

**Comment by TeknoMobil** [comment]
Yes deepin-wm translation ready.
Right-click works as a deepin-menu service

![Ekran Görüntüsü - 2019-06-12 15-37-30](https://user-images.githubusercontent.com/42881121/59351887-15797380-8d28-11e9-9e69-6e5e358426d3.png)
