### ISSUE TITLE
官方仓库是否考虑引入debian backports仓库源？

### ISSUE THREAD

**Issue by abcfy2** [linuxdeepin/developer-center#1286]
无论是debian还是ubuntu，都有一个名为backports的仓库源，用于提供main仓库中低版本的维护，一些能兼容当前发行的补丁，升级也会出现在backports中。

是否考虑官方仓库引入backports仓库支持？不然只是用debian上游的main仓库很多软件版本太低了。比如nodejs停留在4.8，而backports已经更新到8.11 LTS。再比如openjdk-8-jre在main的版本为1.8.0-181，而backports仓库的版本更新到1.8.0-212。不一而足

某种程度上，backports是为main仓库软件版本太低的一种补偿维护，并且基本是可以兼容当前版本的发行版的。不知Deepin是否考虑引入backports，或者干脆直接引用Debian的backports作为自己的backports仓库？

**Comment by BLumia** [comment]
恐怕目前没人手维护。不过我不确定。 cc @zhaofangfangdeepin 

不过，[Debian Buster 快发布了](https://wiki.debian.org/DebianBuster) ，到时候社区版仓库也会随之更新的。

**Comment by abcfy2** [comment]
main仓库一旦发布，软件版本几乎就不变了。所以即使第一时间跟进了debian stable，也会面临近三年main软件不升级的问题。所以才会加一个backports，通常官方也会推荐开启这个仓库源，以保证软件不至于太落后

**Comment by BLumia** [comment]
> main仓库一旦发布，软件版本几乎就不变了。所以即使第一时间跟进了debian stable，也会面临近三年main软件不升级的问题。所以才会加一个backports，通常官方也会推荐开启这个仓库源，以保证软件不至于太落后

是两年。以及官方本身会维护一些特别常用软件的更新（现在的 deepin lion 仓库并不是和 debian stretch 完全一致的，已经有一部分软件有打过 deepin 的 patch 来 backport 一部分提交了）。

Debian 的 backport 是从 testing 仓库选取一部分包然后在 stable 上直接重编译的，[debian 自己也不提供对 stable 仓库内包的兼容保证](https://backports.debian.org/)，以及也[无法及时跟进额外的安全问题补丁](https://www.debian.org/security/faq#testing) ，Debian 官方也不建议所有的包都优先使用 backport 源内的版本。

**Comment by SuperEndermanSM** [comment]
如此说来深度的软件版本落后就是新常态咯？

**Comment by BLumia** [comment]
> 如此说来深度的软件版本落后就是新常态咯？

[软件并非新版并非坏事](https://wiki.debian.org/DontBreakDebian#Don.27t_suffer_from_Shiny_New_Stuff_Syndrome)。

另外，用户常用的桌面软件 Deepin 会跟进维护（比如浏览器等），大部分软件用户也可以自行安装官方提供的包，并且使用特定的软件包管理来更新这些包（比如 npm 和 nodejs，pip 和 python，以及 cargo 和 rust 等）。

如果 deepin 自己维护一份脱离 debian 比较远的仓库的话，本来大部分第三方软件开发者都没有单独适配 deepin （尤其是国外的主流软件），那么安装那些软件的时候反而会像之前的 unstable 那样面临安装问题（现在大部分情况，如果开发者没有适配 Deepin 但适配了 Debian ，就可以直接参考 debian stable 的方式安装）。

**Comment by SuperEndermanSM** [comment]
OK，明白了，希望不影响日常使用

**Comment by abcfy2** [comment]
归根结底还是个人软件的生态问题。对于个人桌面级的软件来说，目前Ubuntu的确是做的最好的一个，不但本身官方维护的仓库中的软件包数量远多于debian，几乎第三方开发商都会有ubuntu软件仓库。另外lanchpad还有ubuntu的ppa，对于个人开发者来说也能很容易给ubuntu扩充软件数量，丰富软件生态。

所以deepin看看有没有好办法解决这一类的问题。如果能做到兼容Ubuntu的仓库就更好了。目前我看deepin的软件仓库还是比较奇特的，主要来源于debian stable，但是又引入了一些ubuntu的源，比如linux-firmware这个软件包，导致一定程度上破坏了软件仓库的依赖，这样会导致其他软件依赖被破坏无法安装，比如deepin就不能安装linux-firmware-nonfree这个包。希望官方有好办法解决

**Comment by abcfy2** [comment]
另外我的看法是对于底层软件，求稳。比如libc, python, openssl等等，这些软件包牵一发动全身，轻易不能乱升级大版本(小的BUG fix肯定是要的)

对于上层的桌面软件或个人软件，可以适当追新，因为这样可以保证用户桌面级的新特性或者BUG可以尽快得到解决。所以我就非常喜欢Ubuntu的仓库，因为它非常符合我的胃口。每个LTS版本直接基于当年年初的debian sid进行fork，然后提供backports对上层软件进行更新，比如firefox，openjdk等软件包在Ubuntu官方仓库就会得到持续更新。

**Comment by BLumia** [comment]
> 另外我的看法是对于底层软件，求稳。比如libc, python, openssl等等，这些软件包牵一发动全身，轻易不能乱升级大版本(小的BUG fix肯定是要的)
> 
> 对于上层的桌面软件或个人软件，可以适当追新，因为这样可以保证用户桌面级的新特性或者BUG可以尽快得到解决。所以我就非常喜欢Ubuntu的仓库，因为它非常符合我的胃口。每个LTS版本直接基于当年年初的debian sid进行fork，然后提供backports对上层软件进行更新，比如firefox，openjdk等软件包在Ubuntu官方仓库就会得到持续更新。

补充一点，目前尽可能和 debian stable 持平而不盲目追新的最主要原因是安全团队维护，人力是另一方面原因。

另外，由于不同发行版的策略是肯定会导致仓库的区别的，而独立维护异于其它发行版的仓库需要大量的人力物力（只是编译和放置软件包倒是挺简单，但 Deepin 不止做这些）。

对于喜欢 ubuntu （和/或它的仓库）的用户，其实可以考虑保持使用 ubuntu （毕竟混用仓库永远是不建议且不受支持的行为）。Deepin 的 [DDE 各个应用和桌面组件也有逐渐进入 Debian 仓库](https://tracker.debian.org/teams/pkg-deepin/)，到时候喜欢 ubuntu 的用户也可以直接在 ubuntu 使用其发行版所维护的 DDE 了。

ps. Debian 的 backport 仓库的大部分软件包是可以在 Deepin stable 上用的，但即使 Debian 官方都不会担保软件包与稳定仓库的兼容性和安全问题，Deepin 也无法在这个程度上提供进一步的支持了。故如果你打算使用，请像 Debian wiki 提到的那样，仅使用必要的软件包，并自行处理可能发生的任何问题。

**Comment by htqx** [comment]
软件不是越新越好，非常赞赏deepin转到stable。
随着新版debian的更新，deepin的stable的软件也不至于像现在那么落后，毕竟一个版本达到寿命的周期，总是会显得特别落后。

deepin还是应该把精力放在推动dde的相关组件进入标准的debian库，这样兼容性会得到更大的保证。

**Comment by hxhlb** [comment]
虽然不是越新越好, 但总感觉对开发人员来说不是那么友好...

**Comment by redchenjs** [comment]
@hxhlb 开发人员就用Arch+DDE呗，Arch的自身定位就是一个对开发人员友好的发行版

**Comment by SuperEndermanSM** [comment]
> @hxhlb 开发人员就用Arch+DDE呗，Arch的自身定位就是一个对开发人员友好的发行版
deepin用户-1成功/滑稽😂

**Comment by SuperEndermanSM** [comment]
> @hxhlb 开发人员就用Arch+DDE呗，Arch的自身定位就是一个对开发人员友好的发行版

deepin用户 -1  😂😂😂

**Comment by emfox** [comment]
> > 另外我的看法是对于底层软件，求稳。比如libc, python, openssl等等，这些软件包牵一发动全身，轻易不能乱升级大版本(小的BUG fix肯定是要的)
> > 对于上层的桌面软件或个人软件，可以适当追新，因为这样可以保证用户桌面级的新特性或者BUG可以尽快得到解决。所以我就非常喜欢Ubuntu的仓库，因为它非常符合我的胃口。每个LTS版本直接基于当年年初的debian sid进行fork，然后提供backports对上层软件进行更新，比如firefox，openjdk等软件包在Ubuntu官方仓库就会得到持续更新。
> 
> 补充一点，目前尽可能和 debian stable 持平而不盲目追新的最主要原因是安全团队维护，人力是另一方面原因。
> 
> 另外，由于不同发行版的策略是肯定会导致仓库的区别的，而独立维护异于其它发行版的仓库需要大量的人力物力（只是编译和放置软件包倒是挺简单，但 Deepin 不止做这些）。
> 
> 对于喜欢 ubuntu （和/或它的仓库）的用户，其实可以考虑保持使用 ubuntu （毕竟混用仓库永远是不建议且不受支持的行为）。Deepin 的 [DDE 各个应用和桌面组件也有逐渐进入 Debian 仓库](https://tracker.debian.org/teams/pkg-deepin/)，到时候喜欢 ubuntu 的用户也可以直接在 ubuntu 使用其发行版所维护的 DDE 了。
> 
> ps. Debian 的 backport 仓库的大部分软件包是可以在 Deepin stable 上用的，但即使 Debian 官方都不会担保软件包与稳定仓库的兼容性和安全问题，Deepin 也无法在这个程度上提供进一步的支持了。故如果你打算使用，请像 Debian wiki 提到的那样，仅使用必要的软件包，并自行处理可能发生的任何问题。

你好，请问关于DDE各个组件和应用进入Debian的事，有一个总列表和进度跟踪之类的页面吗？如果 我没有理解错，debian tracker 似乎只有已进入的列表？我想为DDE完整进入 Sid 做一点微小的贡献。

**Comment by BLumia** [comment]
> 你好，请问关于DDE各个组件和应用进入Debian的事，有一个总列表和进度跟踪之类的页面吗？如果 我没有理解错，debian tracker 似乎只有已进入的列表？我想为DDE完整进入 Sid 做一点微小的贡献。

其实对比目前 GitHub 项目列表和那个 tracker ，缺失的就是还没进去的。我这边也不是很清楚是谁在推进这项工作，可能可以考虑问一下 @hualet 或者邮件 `pkg-deepin-devel`维护团队（邮件地址在 tracker 列表最上方)。其它的我就也不清楚了 :joy:

**Comment by emfox** [comment]
> > 你好，请问关于DDE各个组件和应用进入Debian的事，有一个总列表和进度跟踪之类的页面吗？如果 我没有理解错，debian tracker 似乎只有已进入的列表？我想为DDE完整进入 Sid 做一点微小的贡献。
> 
> 其实对比目前 GitHub 项目列表和那个 tracker ，缺失的就是还没进去的。我这边也不是很清楚是谁在推进这项工作，可能可以考虑问一下 @hualet 或者邮件 `pkg-deepin-devel`维护团队（邮件地址在 tracker 列表最上方)。其它的我就也不清楚了 😂

好的，感谢~

**Comment by felixonmars** [comment]
> > 你好，请问关于DDE各个组件和应用进入Debian的事，有一个总列表和进度跟踪之类的页面吗？如果 我没有理解错，debian tracker 似乎只有已进入的列表？我想为DDE完整进入 Sid 做一点微小的贡献。
> 
> 其实对比目前 GitHub 项目列表和那个 tracker ，缺失的就是还没进去的。我这边也不是很清楚是谁在推进这项工作，可能可以考虑问一下 @hualet 或者邮件 `pkg-deepin-devel`维护团队（邮件地址在 tracker 列表最上方)。其它的我就也不清楚了 joy

本来是我找了 @hosiet 等大佬在推进，不过最近因为临近新版发布，以及新版的源码仍然没有开放，我没有进一步推进旧版了，以免遇到问题上游也无法及时处理。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
