### ISSUE TITLE
[Arch Linux] deepin-wm & deepin-file-manager segfaults

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#1287]
## Describe the bug
Segfaults which caused **deepin-wm** crash and recovery.
```
[11417.879064] deepin-wm[769]: segfault at 0 ip 00007f1355eff4f4 sp 00007ffcb86cdb58 error 4 in libdeepin-mutter.so.0.0.0[7f1355eb5000+91000]
[20073.464875] dde_file_manage[2242]: segfault at 10 ip 00007f51a2138510 sp 00007f51899fd108 error 4 in libQt5Core.so.5.12.3[7f51a1f0b000+2cc000]
```

## To Reproduce
I wasn't able to reproduce it, but got it unexpectedly this way:
1. foobar2000 with PlayOnLinux 4.3.4 under Wine 4.9-staging with GTK 3 theming enabled
2. Changing tags in edit mode using ctrl+c / ctrl+v inside properties dialog

## Enviroments:
OS: Manjaro 18.0.4 Illyria
Kernel: x86_64 Linux 5.1.8-1-MANJARO
Shell: bash 5.0.7
DE: Deepin 15.10.1
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
compiler: gcc 8.3.0
tk: Qt 5.12.3
dm: LightDM

### Distro & Version
Manjaro Deepin

### Related package version
deepin-wm  1.9.38-1
deepin-file-manager  1:4.8.6.2-1

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
