### ISSUE TITLE
systemd-sysctl 的配置文件优先级倒置了

### ISSUE THREAD

**Issue by duanyao** [linuxdeepin/developer-center#1288]
## 缺陷描述
deepin 里面目前有两个 sysctl 的配置文件：
    /etc/sysctl.d/99-sysctl.conf （链接到 /etc/sysctl.conf ）
    /usr/lib/sysctl.d/deepin.conf

根据 systemd-sysctl 服务的文档（ https://www.freedesktop.org/software/systemd/man/sysctl.d.html  ），前者的优先级要高于后者，但是在 deepin 上的实际结果却是相反的，后者的优先级要高于前者。

所以，在 deepin 上修改 /etc/sysctl.conf 很可能没有用，如果相同属性也在 /usr/lib/sysctl.d/deepin.conf 中被设置了的话。

## 复现步骤
要验证的话，修改 /etc/sysctl.conf，在里面加上
  vm.swappiness=100
  net.core.somaxconn = 10000

然后运行 sudo systemctl restart systemd-sysctl ，再运行 sysctl vm.swappiness 和 sysctl net.core.somaxconn ，它们应该还是 /usr/lib/sysctl.d/deepin.conf 里面设置的值（10 和 512）。

## 期望行为
/etc/sysctl.conf 的优先级应高于 /usr/lib/sysctl.d/deepin.conf

## 复现环境:
15.6 - 15.10.1 应该都可以复现，更早的版本不记得了。

### 发行版以及版本
Linux Deepin 15.10.1

### 相关的软件包版本
systemd 232-25+deb9u6

### 其他内容
systemd 文档里关于优先级的描述是：

> Configuration files are read from directories in /etc/, /run/, /usr/local/lib/, and /usr/lib/, in order of precedence. Each configuration file in these configuration directories shall be named in the style of filename.conf. Files in /etc/ override files with the same name in /run/, /usr/local/lib/, and /usr/lib/. Files in /run/ override files with the same name under /usr/.

以前在论坛里报告过，但看起来问题一直存在：
https://bbs.deepin.org/forum.php?mod=viewthread&tid=146882

**Comment by duanyao** [comment]
又调研了一番后发现，上面的描述不够准确，实际上 systemd-sysctl 程序本身的行为没有bug，但是deepin 对配置文件的命名有些问题。

其一，从 2013 年左右开始，/etc/sysctl.conf 文件就被废弃了，systemd-sysctl 会无视它（ https://www.archlinux.org/news/deprecation-of-etcsysctlconf/ ）。不过 `sysctl --system` 命令仍会加载这个文件。deepin 让 /etc/sysctl.d/99-sysctl.conf 链接到 /etc/sysctl.conf 是不合适的，这造成了 systemd-sysctl 和  `sysctl --system` 之间的矛盾。建议去掉 /etc/sysctl.conf ，内容移动到 /etc/sysctl.d/ 下面。

其二，没有正确理解 sysctl.d 配置文件的优先级。实际上 /etc/sysctl.d/, /run/sysctl.d/, /usr/lib/sysctl.d/ 这三个目录里的文件是 **一起** 按文件名升序排列应用的，不是说 /etc/sysctl.d/ 里面的就优先于 /usr/lib/sysctl.d/ 里面的。所以，/usr/lib/sysctl.d/deepin.conf 要优先于 /etc/sysctl.d/99-sysctl.conf 。我认为 deepin 的本意是让 deepin.conf 的优先级较低，那么就应该把它为 00-deepin.conf 之类，或者把 99-sysctl.conf 改为 zz-sysctl.conf 之类。只有同名的文件才是按照  /etc/sysctl.d/, /run/sysctl.d/, /usr/lib/sysctl.d/ 的顺序覆盖（前边的优先级高），注意这个覆盖是对文件整体的，被覆盖的文件就完全不生效。

第二点也怪 systemd 的文档没说清楚，我之前也没能理解这个优先级规则，是做了实验才确定的。

**Comment by hualet** [comment]
差点忘记处理这个了。

> 又调研了一番后发现，上面的描述不够准确，实际上 systemd-sysctl 程序本身的行为没有bug，但是deepin 对配置文件的命名有些问题。
> 
> 其一，从 2013 年左右开始，/etc/sysctl.conf 文件就被废弃了，systemd-sysctl 会无视它（ https://www.archlinux.org/news/deprecation-of-etcsysctlconf/ ）。不过 `sysctl --system` 命令仍会加载这个文件。deepin 让 /etc/sysctl.d/99-sysctl.conf 链接到 /etc/sysctl.conf 是不合适的，这造成了 systemd-sysctl 和 `sysctl --system` 之间的矛盾。建议去掉 /etc/sysctl.conf ，内容移动到 /etc/sysctl.d/ 下面。
> 

这个我认为是Debian为了兼容性做的处理，想让 /etc/sysctl.conf 的修改也会被 systemd-sysctl 应用，我理解应该没有什么冲突问题。

> 其二，没有正确理解 sysctl.d 配置文件的优先级。实际上 /etc/sysctl.d/, /run/sysctl.d/, /usr/lib/sysctl.d/ 这三个目录里的文件是 **一起** 按文件名升序排列应用的，不是说 /etc/sysctl.d/ 里面的就优先于 /usr/lib/sysctl.d/ 里面的。所以，/usr/lib/sysctl.d/deepin.conf 要优先于 /etc/sysctl.d/99-sysctl.conf 。我认为 deepin 的本意是让 deepin.conf 的优先级较低，那么就应该把它改为 00-deepin.conf 之类，或者把 99-sysctl.conf 改为 zz-sysctl.conf 之类。只有同名的文件才是按照 /etc/sysctl.d/, /run/sysctl.d/, /usr/lib/sysctl.d/ 的顺序遮蔽（前边的遮蔽后面的），注意这个遮蔽是对文件整体的，被遮蔽的文件就完全不生效。
> 
> 第二点也怪 systemd 的文档没说清楚，我之前也没能理解这个优先级规则，是做了实验才确定的。

这个多谢进行说明。

**Comment by duanyao** [comment]
@hualet 
`sysctl --system` 和 `systemd-sysctl` 都会处理 `/etc/sysctl.d/*.conf` ，所以最简单的兼容处理是将配置文件放在这里。让 `/etc/sysctl.conf` 链接到  `/etc/sysctl.d/99-sysctl.conf` 的问题是两者的优先级差很多，前者很高，后者较低，所以并没有很好地实现兼容。debian 大概是因为没有类似 `/usr/lib/sysctl.d/deepin.conf` 的文件，所以没有暴露这个问题？

**Comment by hualet** [comment]
deepin的问题我理解应该是需要把 deepin.conf 修改为数字前缀的文件，比如 51-deepin.conf，这样应该就能解决问题了把？ @duanyao

**Comment by duanyao** [comment]
@hualet 是的，改为 51-deepin.conf 可以解决此问题，不过我觉得最好是 00-deepin.conf ，其它数字都留给用户自定义文件。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
