### ISSUE TITLE
增加 sysctl fs.inotify.max_user_watches 的默认值

### ISSUE THREAD

**Issue by duanyao** [linuxdeepin/developer-center#1289]
## 缺陷描述
fs.inotify.max_user_watches 的当前默认值是 8K，很多情况下是不够用的，而且一旦不够用，会出现一些奇怪的bug，例如文件管理器不会自动刷新。

## 复现步骤
我所知道的大量使用 inotify watch 的程序主要是各种 IDE 和具有监视功能的编译器（如 typescript），用它们处理文件很多的工程时应该会触发这个问题。

## 期望行为
fs.inotify.max_user_watches 的默认值增加到 IDEA 建议的 512K：
https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit

按这里的数据（ https://stackoverflow.com/questions/535768/what-is-a-reasonable-amount-of-inotify-watches-with-linux ），这最多会占用 512MB 内存，还算合理。

不过我不确定 fs.inotify.max_user_instances 是否也要增加，没查到确切的说法。

### 发行版以及版本
Linux Deepin 15.10.1

**Comment by hualet** [comment]
可以改大。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
