### ISSUE TITLE
Mirror switcher should write in /etc/apt/sources.list

### ISSUE THREAD

**Issue by Nhoya** [linuxdeepin/developer-center#129]
Actually i really don't understand the function of the mirrors switcher form the DE, changing the mirrors should write the new one in /etc/apt/source.list

**Comment by snyh** [comment]
The "mirror" in control center is not same as the debian repository mirror. 

1. DDE always download file from official repository if the file in mirror server is not same as official one.
2. the config file is store in /etc/apt/apt.conf.d/99mirrors.conf  and implement by [lastore-smartmirror](https://github.com/linuxdeepin/lastore-daemon/tree/master/src/lastore-smartmirror) with a apt-get [patch](https://github.com/linuxdeepin/lastore-daemon/blob/master/smartmirror.patch)
