### ISSUE TITLE
deepin15.10stable版之后字体明显变细

### ISSUE THREAD

**Issue by jetmit** [linuxdeepin/developer-center#1290]
## 缺陷描述

`deepin15.10stable`版之后字体明显变细

## 期望行为
`stable` 与 `unstable`表现能一致

## 截图

![深度截图_选择区域_20190613164339](https://user-images.githubusercontent.com/20562449/59420958-62c91400-8e00-11e9-97fc-09205f61ce0f.png)![x](https://user-images.githubusercontent.com/20562449/59420986-6e1c3f80-8e00-11e9-8937-57a0745bf053.png)

左边`unstable`,右边`stable`

![深度截图_选择区域_20190613164410](https://user-images.githubusercontent.com/20562449/59421092-9f950b00-8e00-11e9-8e48-131a80dfc5be.png)![x2](https://user-images.githubusercontent.com/20562449/59421107-a6238280-8e00-11e9-820d-3ce4ff3ed810.png)
左边`unstable`,右边`stable`

![ic](https://user-images.githubusercontent.com/20562449/59422515-1a5f2580-8e03-11e9-90a0-9b104645273b.png)![x3](https://user-images.githubusercontent.com/20562449/59422531-1fbc7000-8e03-11e9-901e-a94e6b6681d4.png)

上边`unstable`,下边`stable`

可以看到`unstable`的比`stable`的字体浓郁一些,黑一些,字体都是 `Noto Sans CJK SC`
其他的桌面图标字体,设置中心字体等都是这样的现象,是`stable`有意调整设置成这样的吗还是bug?

**Comment by hualet** [comment]
不是有意调整的，是fontconfig版本不一样、配置文件也不太一致造成的。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
