### ISSUE TITLE
安装官方驱动后，窗口特效无法开启

### ISSUE THREAD

**Issue by htqx** [linuxdeepin/developer-center#1291]
## 缺陷描述
安装nvidia430.14版驱动后，窗口特效无法开启（貌似安装完毕之后曾经是开启的，但是切换关闭之后再也无法开启，记不太清楚）。

## 复现步骤
不清楚是否能够复现，但是我百度也有人提到这个问题。

## 期望行为
定位这个bug是什么原因导致，下一版本不要再出现这个bug。

## 截图
![image](https://user-images.githubusercontent.com/42466118/59484975-8fd00200-8ea6-11e9-9596-57eda431a8f6.png)

## 复现环境:
15.10.1 + nvidia 430.14

### 发行版以及版本
15.10.1

### 相关的软件包版本
nvidia

**Comment by BLumia** [comment]
官方驱动效果不一定好，这种问题大概只有 nvidia 自己能解决吧。

kwin 是会在检测到使用目前驱动开启混成容易出问题的情况的话就会自动禁用混成的。

**Comment by aiamuzz** [comment]
@BLumia ... i am unable to use kwin on the Stable branch installation after the last update that was pushed ... i thought i'd test kwin when free ... but the windows effect crashes every time ... so i have renamed the kwin executables and reverted back to `deepin-wm` ... my daily driver ...

any way i can collect data diagnostics when kwin crashes ... let me know the commands to grab data and i'll post it back here for troubleshooting.

**Comment by hualet** [comment]
@aiamuzz  install systemd-coredump，after kwin crash, use `coredumpctl gdb kwin_x11` and show us the backtrace.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
