### ISSUE TITLE
Deepin movie shows taskbar in fullscreen mode, when using timeline

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#1292]
## Describe the bug
Deepin movie shows taskbar in fullscreen mode, while using timeline.

## To Reproduce
1. Play something with deepin-movie in fullscreen
2. Hover over / use timeline

## Expected behavior
Do not show taskbar of course & stop bugging what was working good)

## Enviroments:
OS: Manjaro 18.0.4 Illyria
Kernel: x86_64 Linux 5.1.8-1-MANJARO
Shell: bash 5.0.7
DE: Deepin 15.10.1
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
compiler: gcc 8.3.0
tk: Qt 5.12.3
dm: LightDM

### Distro & Version
Arch / Manjaro Deepin

### Related package version
deepin-movie  1:3.2.23.2-1

**Comment by BLumia** [comment]
Seems fixed in this patch https://github.com/linuxdeepin/deepin-movie-reborn/pull/34 but not sure if it can also works under deepin-wm. Did you tested if dde-kwin works?

@hualet any idea?

**Comment by keybreak** [comment]
@BLumia 
> Did you tested if dde-kwin works?

Yes, just now - it seems to work good at least on VM.

So, hopefully fix for deepin-wm

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
