### ISSUE TITLE
The World of Deepin OS ... User Interface(UI) and User Experience(UX) ... that should not be messed !!!

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1293]
A brief analysis of the whole **Never-Seen-Before-On-Linux-Experience** ... The Deepin OS's holistic experience !!!

a statistical analysis ...

## Defining the Key Elements

The User Interface of Deepin primarily consistes of the following elements/categories ...

**1. Deepin Dock
2. Deepin Windows manager
3. Deepin Desktop Hot corners
4. Deepin Menu (Android style and Windows OS style)
5. Deepin Control Panel
6. Deepin Wallpaper/Screensaver Option**

All the above Interfaces and accessing the above 6 elements/categories constitutes the whole **Never-Seen-Before-On-Linux-Experience** !!!

## Analyzing Usage

an approximate statistical usage analysis ... the usage/access by a typical/average user on each of the above elements in an 8 hour work shift ...

I'll be analysing it in the reverse order 6-1 for emphasis on the criticality of each sections  ... 

**6. Deepin Wallpaper/Screensaver Screen/Option**

This option/screen is a very nicely designed and a visually appealing screen, a user in an 8 hour workflow will not be accessing it regularly ... This option is something the user may think of accessing it occasionally once in a week or a month or in months ... this is accessed only when he wants a new look for his desktop.

**So 'Deepin Wallpaper/Screensaver Screen/Option' on the user experience scale, rates the lowest(in comparison) going by a users impressions(visual impressions & use in his/her workflow) ... in an 8 hour workflow**

**5. Deepin Control Panel**

This is a very nice and pretty Control panel setting drawer designed by the Deepin OS team (however the previous design was far more appealing than the current home screen of this panel/drawer which had a nice music applet and more squarish tiles for separate categories/sections/hardware)

In terms of accessing and using it in an 8 hour workflow just like the Deepin Menu, this too is used only occassionally when one may want to access some setting ... I'd say out of personal experience this may be accessed 1-2 times or may be not even once in a given day. 

_Please Note that in the previous design the access time for the very same element(control settings panel) was very high, as it had the music widget running in it which was a very good and appealing option to have and made for a great user experience._

**So 'Deepin Control Panel' on the user experience scale, rates relatively low(in comparison) going by a users impressions(visual impressions & use in his/her workflow) ... in an 8 hour workflow**

**4. . Deepin Menu**

This option is again a very nicely designed and a visually appealing screen with well laid out categories and animations, This element is used more than the wallpaper/screensaver screen, the user certainly accesses it quite a few times in an 8 hour work on their machines. The regularly used application in all probability will either be placed on the dock or shortcuts mapped to them so they can be launched directly from the dock or by invoking the assigned shortcuts(thanks to a very nice option provided by Deepin OS to setup cutom shortcuts in the keyboard setting control panel).

So in effect a user may access the Deepin Menu only to launch/open the not so regular options, statistically it could range between 3-5 applications or a couple more in an 8 hour workflow.

**So 'Deepin Menu' on the user experience scale, rates slightly better(when compared to the 6th and 5th elements above) going by a users impressions(visual impressions & use in his/her workflow) ... in an 8 hour workflow**

**3. Deepin Desktop Hot corners**

The option to assign certain actions when the mouse cursor is moved to the four corners of the screen is a very appealing option created by the Deepin team. Its one of those options that is very frequently used to access the 'All windows in a workspace' view or to 'Close' an application from the top right corner.

I'd say this option in an 8 hour workflow is used considerably especially the above 2 options. Its kind of a signature of the plesant Deepin OS experince !!!

**So 'Deepin Desktop Hot corners' on the user experience scale, rates higher than the above 3 sections/elements ... going by a users impressions(visual impressions & use in his/her workflow) ... in an 8 hour workflow**

**2. Deepin Windows manager**

This is the highlight and the core of the Deepin OS experience that is so frequently used through an 8 hour workflow, this has the registers the maximum impressions of a user actively using his machine throughout his 8 hour workflow.

This was the soul of the whole Deepin OS experience thanks to the Deepin team who created the Deepin WM based on Mutter, Sadly this soul has been sucked out of the Deepin OS holistic experience as a result of very bad design decision by the Deepin Team, This decision could cost them dearly if its not corrected quickly which i have shared in this thread.

**So 'Deepin Windows manager' on the user experience scale, rates the maximum/highest ... going by a users impressions(visual impressions & use in his/her workflow) ... in an 8 hour workflow**

**1. Deepin Dock**

This is again the Deepin Signature element that lends to the Whole Deepin OS experience, This too just like the Deepin Windows Manager registers the maximum impressions of a user in his 8 hour workflow as its visible all the time or pops up everytime the cursor brushes the bottom of the screen.

**So 'Deepin Dock' on the user experience scale, rates the maximum/highest ... going by a users impressions(visual impressions & use in his/her workflow) ... in an 8 hour workflow**

## User impressions(like the impressions considered while monetizing the ad banners)

User Impressions(what the eye sees and the mind gets accustomed on a subconscious level) of the above categories/elements that constitute the Deepin User Interface and Experience could be summed up as the following.

1. **Deepin Dock**
**Maximum No. of Impressions in an 8 hour workflow.**

2. **Deepin Windows manager**
**Maximum No. of Impressions in an 8 hour workflow.**

3. **Deepin Desktop Hot corners**
**Moderate/High No of Impressions in an 8 hour workflow.**

4. Deepin Menu (Android style and Windows OS style)
Low No. of Impressions in an 8 hour workflow.

5. Deepin Control Panel
Low No. of Impressions in an 8 hour workflow.

6. Deepin Wallpaper/Screensaver Option
Very Low/None No. of Impressions in an 8 hour workflow.

As you can see the first 3 elements of a users 8 hour workflow bears a users maximum experience ... his holistic experience of the Deepin OS !!!

##

**What's most important to UI/UX designers is to respect the fact that users subconsciously get immersed in an enviroment which includes visual cues and habits of processes(a certain feature, a certain shortcut to invoke a feature, ets) ... this gets deep rooted in his/her subconscious which in other words becomes a users holistic experience !!!** 

When UI/UX designers take liberties of changing the design(visuals) of a UI or withdraw or drop a certain feature or the ability of shortcuts to invoke features, they disrupt the 'zen' the user has subconsciously gained over time 

If i have to explain by example ... 

look at the recent implementation of replacing of **a feature rich 'deepin-wm' and its UI** with **a half baked rather unbaked & bland 'kwin' into the OS**, with no option for users to choose between the former and latter is the worst decision any team could ever take ... and If we went by the above analysis of the maximum impression(maximum impact of this decision) this decision is nothing short of a Big Disaster !!!

_I know the team is Highly defensive about this move of theirs_ ... but nevertheless damage is done ... the existing users are left with a featureless wm to live through ... and the new users will certainly not be attracted to the current state of 'kwin' ... there is no denying it was a bad and hasty move all in all **(look at the impression/user's holistic experience stats above !!!)**

##
I have opened this following thread with the hope that the team stops being defensive and work towards restoring the former glory of DeepinOS into kwin wm ... i have listed out all the great features/options the former Windows Manager had, so the team can try and rebuild each one of them(as they can see that none of the features deserves to be dropped) into the new kwin construction !!!

PS : Hope the team going forward will create their own template(on similar lines) ... from a **'User experience perspective',**

such a measure could prevent any future disasters like the hasty implementation of kwin ... such a template can guide the team in taking future decisions on delivering high quality features without compromising a user's holistic experience**(its UI/UX)** ... **which will keep the goodwill and good-feel building over brick by brick ... rather than razing the current structure to the ground and starting a new structure from scratch !!!**

**Comment by BLumia** [comment]
I personally think discussing UX is [bikeshedding](https://www.freebsd.org/doc/en/articles/mailing-list-faq/bikeshed.html).

But anyway, @shule1987 .

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
