### ISSUE TITLE
Implementation of 'kwin' ... how much we have lost ... how much has to be restored !!!

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1294]
This is the second part of my efforts to reduce / minimize shocks to users that mess the whole flow ... 

The first part of the effort can be read here ... [**The World of Deepin OS ... User Interface(UI) and User Experience(UX) ... that should not be messed !!!**](https://github.com/linuxdeepin/developer-center/issues/1293)

This is a thread i have started to point out and document the features we have lost as a result of the hasty design decision of the team in implementing kwin when the same thing could have been done in very subtle manner ... An option for user to continue to choose the older WM until the new WM matures and rises up to its predecessor !!!

Also i have opened this thread so ... the users don't have to start afresh for features that were already great in the previous implementation and there is no reason to lose them in this transition from the older WM to the newer WM !!!

**What we have missed ... What deserves restoration !!!**

## Viewing all windows of the current workspace

A customizable shortcut optionn to view all windows/application in the current workspace. Further we can use the arrow keys and tab key to move between the windows previews and hit enter to make it active ... a very convenient option to navigate between open windows/applications

- [x] Deepin WM
- [ ] Deepin Kwin

## Viewing all windows in all workspaces

A customizable shortcut optionn to view all windows/application in the current workspace. Further we can use the arrow keys and tab key to move between the windows previews and hit enter to make it active ... a very convenient option to navigate between open windows/applications

- [x] Deepin WM
- [ ] Deepin Kwin

## Navigating between workspaces

Super+right/left key
... a great way to navigate.

- [x] Deepin WM
- [ ] Deepin Kwin

Super+1/2/3/../5/.. 	(Nos. 1,2,3 ... are workspace numbers from left to right)
... an even more efficient way to navigate between the workspaces compared to the above option.

- [x] Deepin WM
- [ ] Deepin Kwin

## Moving Windows to a particular workspace

Super+Shift+1/2/3/../5/.. 	(Nos. 1,2,3 ... are workspace numbers from left to right)
... the window will be moved to the workspace number ... a fantastic way to manage windows.

- [x] Deepin WM
- [ ] Deepin Kwin

## Workspace preview screen

A nice shortcut option to view workspace preview as well as windows preview in each workspace.

1. One can drag and drop the very small thumbnails previews of open applications windows in the top workspace previews
2. Also one can drag and drop the bigger application windows previews to any of the worspaces on top
3. In this Worspace preview screen hitting nos 1/2/3/../5/... will bring into focus the respective workspace and the open windows in it.
4. There is a very very appealing animation when we take the mouse over one of the workspaces with the open windows in that workspace separating and letting us drag them to other workspaces

one can navigate to the preferred workspace and hit enter and one will be taken to those workspaces and the open applications in it.

- [x] Deepin WM
- [ ] Deepin Kwin

## Viewing all open windows of a particular application across all workspaces.

All open Windows of a single application can be viewed separately by moving the mouse over that particular application icon in the dock and using the scroll button ...Further we can use the arrow keys and tab key to move between the windows previews and hit enter to make it active ... a very convenient option to navigate between open windows/applications

- [x] Deepin WM
- [ ] Deepin Kwin

##
PS : any other users who feel a certain feature from the older wm which they feel deserves to be restored can post those options/features and i'll edit the same into the checklist form below ... so the team/devs can have a quick view of the ground they have to cover ... **if they so wish** !!!

##
- [x] Deepin WM
- [ ] Deepin Kwin

##
- [x] Deepin WM
- [ ] Deepin Kwin

##
- [x] Deepin WM
- [ ] Deepin Kwin

##
- [x] Deepin WM
- [ ] Deepin Kwin

##
- [x] Deepin WM
- [ ] Deepin Kwin

##
- [x] Deepin WM
- [ ] Deepin Kwin

##
- [x] Deepin WM
- [ ] Deepin Kwin

**Comment by BLumia** [comment]
For your info, switching to dde-kwin is a project direction change and deepin-wm is no longer maintained by Deepin dev team[^1]. Most of these user experence differences which deepin-wm have will port (re-implemented, actually) to dde-kwin in future updates. For users who love deepin-wm and really doesn't feel good with dde-kwin, deepin-wm is still there so user can always switch to deepin-wm if they like.

You can open feature request for dde-kwin for these feature which deepin-wm have but dde-kwin doesn't, btw.

----------

[^1]: But a community fork is still okay if anyone want to give deepin-wm user some love and would like to maintain that project. Patches is also okay if @sonald or other maintainer from Deepin would like to review patches and get them merged.

**Comment by aiamuzz** [comment]
> For your info, switching to dde-kwin is a project direction change and deepin-wm is no longer maintained by Deepin dev team[^1]

we have no issue with that decision ... except that it has resulted in the loss of so many options/features



> Most of these user experence differences which deepin-wm have will port (re-implemented, actually) to dde-kwin in future updates.

Glad to finally hear it from you, its great to know that the team is willing to port deepin-wm UX/UI's into future updates of kwin ... 


> For users who love deepin-wm and really doesn't feel good with dde-kwin, deepin-wm is still there so user can always switch to deepin-wm if they like.

Wouldn't it be nice if there was a simple 'switch' for the user somewhere or a simple command that will let users move between the WM that they have grown to love ... and the budding WM (so we can test its developement) ?

It would be nice to see a temporary option/setting in the control panel to switch between ... kwin and deepin-wm 

currently its more of a hack ... i am sure which not all users pull off ... hence a temporary switch would have been ideal ... until kwin matures into an even better WM for the DeepinOS !!!


> But a community fork is still okay if anyone want to give deepin-wm user some love and would like to maintain that project. Patches is also okay if @sonald or other maintainer from Deepin would like to review patches and get them merged.

it would be nice if somebody can volunteer and the current official maintainer can oversee/monitor the volunteers to such a community fork !!!

**Comment by BLumia** [comment]
> Wouldn't it be nice if there was a simple 'switch' for the user somewhere

No, since deepin-wm is not going to have any *official* support from Deepin dev team (maybe someone from Deepin dev team would like to help you out personally but it's not a kind of *official* support).

> or a simple command

`deepin-wm --replace` and `kwin_no_scale --replace`. Many other wm also support the `--replace` argument if you fimilar with window manager concept and the frequency used window managers.

**Comment by aiamuzz** [comment]
> `deepin-wm --replace` and `kwin_no_scale --replace`. Many other wm also support the `--replace` argument if you fimilar with window manager concept and the frequency used window managers.

that's a no go ... have already tried it ... running a `deepin-wm --replace` command freezes and crashes the deepin-wm ... unless the team is willing to probe and fix why its crashing/freezing ... are you willing to probe and fix it ?

**Comment by BLumia** [comment]
> running a `deepin-wm --replace` command freezes and crashes the deepin-wm under certain use cases

`deepin-wm --replace` is used to replace your window manager to deepin-wm (from other wm, dde-kwin for example). It's the very same thing as you run deepin-wm manually when there are no wm running.

A coredump stacktrace can be helpful to associate issue, but I'm don't know much about how x11 wm works, nor deepin-wm's codebase. Sorry I cannot help you out on this domain.

**Comment by aiamuzz** [comment]
## Viewing all windows of the current workspace

A customizable shortcut optionn to view all windows/application in the current workspace. Further we can use the arrow keys and tab key to move between the windows previews and hit enter to make it active ... a very convenient option to navigate between open windows/applications

- [x] Deepin WM
- [x] Deepin Kwin

**This functionality(the visual appeal still needs to matched which could be WIP i suppose) has finally made it to kwin ... the tab key to navigate between the window previews is missing though.** 


## Viewing all windows in all workspaces

A customizable shortcut optionn to view all windows/application in the current workspace. Further we can use the arrow keys and tab key to move between the windows previews and hit enter to make it active ... a very convenient option to navigate between open windows/applications

- [x] Deepin WM
- [x] Deepin Kwin

**This functionality(the visual appeal still needs to matched which could be WIP i suppose) has finally made it to kwin ... the tab key to navigate between the window previews is missing though.** 


## Navigating between workspaces

Super+right/left key
... a great way to navigate.

- [x] Deepin WM
- [x] Deepin Kwin -

**this functionality is made available, however we are unable to set `Super+left/right key` does not work(could be a bug of some kind) ... any other key combination ... Eg. `Ctrl+Alt+left/right key` ... works**


## Viewing all open windows of a particular application across all workspaces.

All open Windows of a single application can be viewed separately by moving the mouse over that particular application icon in the dock and using the scroll button ...Further we can use the arrow keys and tab key to move between the windows previews and hit enter to make it active ... a very convenient option to navigate between open windows/applications

- [x] Deepin WM
- [ ] Deepin Kwin




# Functionalities yet to be attained


## Navigating between workspaces

Super+1/2/3/../5/.. 	(Nos. 1,2,3 ... are workspace numbers from left to right)
... an even more efficient way to navigate between the workspaces compared to the above option.

- [x] Deepin WM
- [ ] Deepin Kwin
 
**Hopefully in due time we'll have it up and running**


## Moving Windows to a particular workspace

Super+Shift+1/2/3/../5/.. 	(Nos. 1,2,3 ... are workspace numbers from left to right)
... the window will be moved to the workspace number ... a fantastic way to manage windows.

- [x] Deepin WM
- [ ] Deepin Kwin 

This functionality too has made it to kwin but through a different key combination ... one can move it sequentially ... the functionality of DeepinWM where we could direct move windows to a numbered workspace is still not implemented ... for this reason i'll still keep it under yet to be achieved category.


## Workspace preview screen

A nice shortcut option to view workspace preview as well as windows preview in each workspace.

1. One can drag and drop the very small thumbnails previews of open applications windows in the top workspace previews
2. Also one can drag and drop the bigger application windows previews to any of the worspaces on top
3. In this Worspace preview screen hitting nos 1/2/3/../5/... will bring into focus the respective workspace and the open windows in it.
4. There is a very very appealing animation when we take the mouse over one of the workspaces with the open windows in that workspace separating and letting us drag them to other workspaces

one can navigate to the preferred workspace and hit enter and one will be taken to those workspaces and the open applications in it.

- [x] Deepin WM
- [ ] Deepin Kwin


##
PS : any other users who feel a certain feature from the older wm which they feel deserves to be restored can post those options/features and i'll edit the same into the checklist form below ... so the team/devs can have a quick view of the ground they have to cover ... **if they so wish** !!!
