### ISSUE TITLE
一点提高系统稳定性的建议

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1295]
因为现在有很多人有待机唤不醒的问题（以前我在真机装deepin也遇到过），参考ubuntu系统，我做2个建议
1）如果没有合上电脑盖子，系统默认只关闭屏幕，而不待机（我经常整个晚上开着电脑，ubuntu是绝对不会待机的）
2）如果用户合上电脑盖子，系统挂起而不是待机。

我测试过，这样做是没有问题的，这也是ubuntu默认的设置。如果deepin也这样做，应该会提升系统的稳定性。因为如果遇到待机唤不醒的问题，用户马上就会放弃。
放在论坛deepin开发人员看不到，所以写在这里。

**Comment by justforlxz** [comment]
https://github.com/linuxdeepin/dde-control-center/pull/234

虽然这么做并不会提升稳定性，但是功能是开发了。
