### ISSUE TITLE
[Feature request] configure dde-kwin from dde-control-centre

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#1296]
We can configure `dde-kwin` from this file `~/.config/kwinrc`. It would be great if we could configure `dde-kwin` from the settings.

Also, we can enable a very cool switch animation by writing the following lines to that file,

> [Effect-CoverSwitch]
> TabBox=true
> TabBoxAlternative=true
> [Plugins]
> coverswitchEnabled=true

We can make the "open and close" animation look better by writing the following lines to that file,

> [Plugins]
> glideEnabled=true

**Comment by Iiari** [comment]
Thanks for that tip!  Any way to make hot corners faster/more responsive with kwin?

**Comment by SiamSami** [comment]
@Iiari I just updated the message. Does it work now?

**Comment by Iiari** [comment]
It does!  Great work.  I added, based upon my online skulking, Reflection=true under [Effect-CoverSwitch] for additional eye candy...  Great work!  I'll post this on the Manjaro forums as well.

**Comment by BLumia** [comment]
Currently seems no plan about adding this feature, but you actually can tweak these configs via `systemsettings` (unsupported from deepin, though).

**Comment by Iiari** [comment]
> Currently seems no plan about adding this feature, but you actually can tweak these configs via `systemsettings` (unsupported from deepin, though).

And, I've read elsewhere, a good chance after installing systemsettings that future Deepin updates could break the system as a result, so if one does that, proceed with care :).

**Comment by Iiari** [comment]
Actually, a question for those who have installed systemsettings, is it possible to have windows that are being opened appear in the center of the screen by systemsettings options?  Thanks!

**Comment by SiamSami** [comment]
By the way, I made a small program which lets us enable and disable some of those settings.

You can download the source code from here, https://github.com/SiamSami/Deepin-kwin-settings

Let me know if you encounter any problem while using the program.

**Comment by Iiari** [comment]
Terrific!  Can't wait to try it... You probably already know, but in [Windows] in kwinrc typing:
Placement=Centered
Will center windows, as I was asking about above.  Thanks!

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
