### ISSUE TITLE
Wine钉钉能出来不?

### ISSUE THREAD

**Issue by BruceWang666** [linuxdeepin/developer-center#1298]
deepin挺好，就是Wine钉钉没有，因为公司买了密盾，网页版登录之后啥消息都看不到，深度官方是否考虑搞个wine钉钉出来？或者让钉钉出个国产系统专版。。。。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
