### ISSUE TITLE
dock 上的 WiFi 菜单会动态增高, 容易造成点击 ssid 失误

### ISSUE THREAD

**Issue by duanyao** [linuxdeepin/developer-center#1299]
## 缺陷描述
dock 上的 WiFi 菜单会动态增高, 容易造成点击失误.

## 复现步骤
机器新进入多个 wifi 接入点的环境下, 点击 dock 上的 WiFi 菜单, 菜单上的ssid是随着信号扫描逐渐增多的, 菜单也会随着ssid的增多而逐渐向上增高. 这时, 用户将鼠标瞄准了一个 ssid, 但等点下去的时候, 因为菜单的增高, 那个ssid就向上移动了, 结果就误点了下方的另一个 ssid.

或者连上一个ssid后多等一会儿, networkmanager 似乎就会"忘记" 其它的ssid, 这可以用 nmcli d wifi 查看, 这时展开 wifi 菜单,就能看到菜单在动态增高.

## 期望行为
信号扫描不应该造成 ssid 在 wifi 菜单中的位置移动. 可能的解决办法有:
1. wifi 菜单中倒置排列 ssid, 即后出现的 ssid 排在上面. 同时, 应该把刷新和开关等按钮也放在下边.
2. wifi 菜单采用固定高度, 不随着ssid的数量增长.

## 截图

![图片](https://user-images.githubusercontent.com/1684137/59547184-164f1700-8f6d-11e9-9056-42d75fabf036.png)

## 复现环境:
见上面.

### 发行版以及版本
Linux Deepin 15.10.1

**Comment by licardoY** [comment]
确实是这样，连上一个WiFi后，过会在点击WiFi图标，只显示当前链接的图标，然后又突然刷新出其他WiFi，列表高度就会变化，造成误点击。体验有点不好

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
