### ISSUE TITLE
Deepin Screenshot not starting

### ISSUE THREAD

**Issue by bijanbina** [linuxdeepin/developer-center#130]
Hi,
Lately on Gnome 3.20.4, gtk 3.20.9 and gtk 2.24.31, Qt 5.7, Deepin Screenshot stop working and doesn't start.
After some debugging I found that the problem is from loading `wnck` in [window_info.py](https://github.com/linuxdeepin/deepin-screenshot/blob/master/src/).
The error appeared on screen if `with no_error_output():` comment out

```
/usr/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed
  from gtk import _gtk
/usr/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_set_qdata: assertion 'node != NULL' failed
  from gtk import _gtk
/usr/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: cannot register existing type 'GtkWidget'
  from gtk import _gtk
/usr/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
  from gtk import _gtk
/usr/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: cannot register existing type 'GtkBuildable'
  from gtk import _gtk
/usr/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed
  from gtk import _gtk
/usr/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_once_init_leave: assertion 'result != 0' failed
  from gtk import _gtk
/usr/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_register_static: assertion 'parent_type > 0' failed
  from gtk import _gtk
```

Finally the simplest code that reproduce the problem is

```
#! /usr/bin/env python2
from PyQt5.QtWidgets import QApplication
QApplication([''])

print "Hello there"
import wnck
print "This line never run"
```
It seems using QApplication and `wnck` simultanuosly can not be done anymore.
## Info

DE: Gnome shell 3.20.4
Distribution: Arch Linux
Deepin Screenshot: 3.1.10

**Comment by hualet** [comment]
What if you just do `import wnck' ? it'll be load with any trouble ?

**Comment by bijanbina** [comment]
Yes, if QApplication(['']) comment out codes run flawlessly and wnck can be loaded and used.

**Comment by hualet** [comment]
@felixonmars any info?

**Comment by bijanbina** [comment]
I also test Deepin Screenshot on another fresh installed Arch linux and the same result occured.
I suspect that if it's because of installation of [Qt Android 5.7](https://download.qt.io/official_releases/qt/5.7/5.7.0/qt-opensource-linux-x64-android-5.7.0.run) without package manager (qt5 is installed from pacman too) which is in common on my two test enviroments.

**Comment by felixonmars** [comment]
It was reported some months ago: https://bbs.deepin.org/forum.php?mod=redirect&goto=findpost&ptid=41013&pid=235195

Since it's only reproducible with some gtk3-based desktop environments, I guess the issue is about importing gtk3 (somehow via its qt platform plugin?) and gtk2 (wnck -> pygtk) into one process.

**Comment by pyriand3r** [comment]
Any news about this bug? Wanted to use deepin screenshot under Arch Linux with Gnome 3.24 but it won't start (and no error message), so i believe it's related to this bug...

**Comment by hualet** [comment]
A new version of deepin-screenshot, rewrote in Qt/C++,  will be available soon. And we're not able to invest any effort to address old issues like this one at the moment.

**Comment by felixonmars** [comment]
Is this still reproducible with the new Qt/C++ version?

**Comment by justforlxz** [comment]
This question has not been answered for too long and will be closed. If there is a need to continue the discussion, it will be reopened.
