### ISSUE TITLE
File Manager - Reset Search Buffer On Enter

### ISSUE THREAD

**Issue by nakst** [linuxdeepin/developer-center#1300]
Feature Request:
I usually navigate folders by typing the folder name in the file manager to highlight the folder I want to enter, then press the Enter key. I then start typing the name of the next folder, however I have to wait for the search buffer's timer to expire so that I can start typing the new folder name. I think that the search buffer should automatically be cleared when you enter a new folder.

**Comment by hualet** [comment]
@BLumia @wangjia12

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
