### ISSUE TITLE
Window's title bar background decoration off on default (Light) theme  for QT-based app

### ISSUE THREAD

**Issue by apit** [linuxdeepin/developer-center#1301]
![DeepinScreenshot_select-area_20190614202830](https://user-images.githubusercontent.com/98901/59512554-2ae6cd00-8ee3-11e9-9b75-786bff7ba078.png)

This happens on Deepin 15.10 only for QT apps, on fresh install. On Dark theme, they are all right.

**Comment by zccrs** [comment]
Fix in https://github.com/linuxdeepin/dde-kwin/commit/596800228ece3778e6670a13fcc2c1f921758912

**Comment by apit** [comment]
ah, didnt know that repo. waiting for it to appear on system update.

you guys rock. thx for the fix, and beautiful desktop 👍
