### ISSUE TITLE
系统安装时候多余硬盘不能自定义挂载位置 （严重）

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1302]
## 缺陷描述

我的笔记本电脑有2块硬盘，一块是固态硬盘，一块是机械硬盘
我是从ubuntu系统转到deepin的，/home我都是单独分区，以免丢资料，所以我选择自己分区
固态硬盘我挂载了1) efi分区，2) 根分区'/' 3) /home分区（不格式化）4) 交换空间
问题就出在我的那个机械硬盘上，装ubuntu时候我把这个分区挂载在 /warehouse上面，这个是我自定义的，但是deepin安装的时候只有可怜几个选项可以选，不能自己自定义挂载的位置，最后没办法，我把整整500G的机械硬盘挂载在了/opt下面，这显然是不好的，因为/opt已经默认安装了很多东西，我希望我的硬盘保持整洁，不能随便写东西进去
## 复现步骤

硬盘不能自己自定义挂载点，一块硬盘都可以复现
## 期望行为

我可以自己定义硬盘挂载位置，比如说把硬盘挂载在  /xxx_yyy_zzz下面，我想取啥名字就取啥名字
## 截图

![IMG_20190615_200806](https://user-images.githubusercontent.com/12093211/59551754-02c59f80-8fb1-11e9-906a-fefe7ad295a9.jpg)

### 发行版以及版本

deepin15.10.1 

### 其他内容

希望尽快修复这个问题

**Comment by BLumia** [comment]
产品设计如此，这种需求可能需要你自行配置。

**Comment by widon1104** [comment]
这个产品设计有严重问题，满足不了用户的基本需求，现在有2块硬盘的人非常多，希望改进

**Comment by BLumia** [comment]
cc @wangjia12

**Comment by widon1104** [comment]
我可以系统安装好以后自己挂载，但是这样很麻烦。我觉得加了这个功能可以提升linux的易用性。而且加这个功能开发量并不大吧。

**Comment by BLumia** [comment]
开不开发得产品确认啊.. 也欢迎这样功能的 PR （如果你认为开发工作量不大的话）
