### ISSUE TITLE
deepin.com.thunderspeed  7.10.35.366deepin18僵死

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1305]
## 缺陷描述

打开7.10.35.366deepin18，然后复制一个迅雷下载链接，迅雷本来应该弹出下载框，但是实际上软件会僵死
7.10.35.366deepin17是好的
## 期望行为

打开迅雷以后复制迅雷下载链接，会弹出下载框，软件不应该僵死

## 复现环境:

真机环境

### 发行版以及版本

deepin15.10.1

**Comment by BLumia** [comment]
@linuxdeepin/wine-team

**Comment by widon1104** [comment]
这个bug可能不限于7.10.35.366deepin18这个版本
当我们复制了一个迅雷下载链接，然后迅雷会弹出一个下载框，如果这时候你不点击这个下载框，而是点击迅雷主窗口，这个下载框会被主窗口遮挡，这时候迅雷就会僵死

这个问题是必现的

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
