### ISSUE TITLE
希望设置中提供忽略某一款软件更新的功能（建议）

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1306]
## 缺陷描述

现在更新界面提醒我迅雷软件有更新，让我更新到18版本，但是我不想更新，因为我知道18版本有严重的问题，但是我不知道如何忽略这一款软件的更新
打个比方，比如说现在系统有更新，我想更新系统，这个软件也有更新，我不想更新，是不是一点更新好的不好的都一股脑全部装上了，我又要自己去安装旧版本软件强制回退，很麻烦
## 期望行为

期望提供忽略某一款软件某一版本更新的功能，如果我点击了，这一款软件的更新不再提示，点更新不更新这款软件的这一版本（这个软件的下一版本更新还是继续提示）
### 发行版以及版本

deepin15.10.1

**Comment by BLumia** [comment]
官方仅会在认为更新不会导致问题时推送更新，如果发现更新可能导致潜在的问题，官方不会推送更新，故此方面官方建议且用户应当总是及时更新软件，并希望社区用户可以在确实发现问题时直接反馈问题以变问题的定位和处理。

如果确实遇到问题或由于个人原因希望保持软件版本而不更新，请参阅 `apt-mark hold` 相关的文档，例如 manpage 。
