### ISSUE TITLE
希望在底层面板上面添加插件功能（功能请求）

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1307]
## 缺陷描述

我使用ubuntu18.04的时候发现gnome shell extension中有很多有用的插件，其中有一款叫system monitor，这款插件会以图标动画的方式显示CPU，网络，内存，硬盘的读写情况，非常直观。我截了system monitor的一张图
![system monitor](https://user-images.githubusercontent.com/12093211/59552998-6d7ed700-8fc1-11e9-941c-d32c278ff3ed.png)
system monitor还可以吧，
如果deepin能够提供类似插件安装在底层面板上面就好了，现在已经有deepin-topbar但是有几个问题
1) topbar占空间，笔记本用户本来空间就有限，不希望再加一个topbar占空间
2) topbar上面有类似系统监控的功能，但是功能很弱，只是显示一个CPU数字，只能显示瞬时CPU的情况，这样不直观不说，也看不到历史CPU的情况，不太实用
3) topbar的字体也没有使用个性化-字体-标准字体设置的字体，其实现在gnome-shell-extension也不能使用gnome tweak设置的字体，但是我看到有人已经提供了patch就等merge了，应该很快gnome shell extensions的字体也可以设置了
## 期望行为

我希望能做成这样，在底层面板上面，或者topbar上面，按右键提供一些插件可以添加在面板上面，比如说system monitor插件，让用户自定义面板，这样应该比较好
### 发行版以及版本

deepin15.10.1

**Comment by BLumia** [comment]
dde-dock 是支持插件开发的，并且已经有一部分第三方开发者 （比如 @sonichy ）开发过比较类似的插件了。

和其他桌面环境一样，第三方提供的组件均需要额外安装才可以出现在插件菜单中可用，故你需要自行下载和安装这些插件才可以使其出现在右键插件列表中。

如果你希望自行开发插件，可以安装 `dde-dock-dev` 包并参阅相关头文件内容、[文档](https://github.com/linuxdeepin/dde-dock/blob/master/technology-overview.md#%E6%8F%92%E4%BB%B6)、以及现有代码来开发自己的插件以供使用。

由于你的功能需求是本来就已经存在的功能，就先关掉了..

**Comment by sonichy** [comment]
这不仅仅是我的刚需，更是大家的刚需，给项目上星，早日进商店！
https://github.com/sonichy/CMDU_DDE_DOCK
![](https://github.com/sonichy/CMDU_DDE_DOCK/raw/master/preview.png)
