### ISSUE TITLE
deepin没有一个网站专门管理dde插件

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1308]
## 缺陷描述

gnome有https://extensions.gnome.org/ 这个网站专门管理针对gnome的插件，查找，安装gnome插件都非常方便
dde却没有类似的网站，导致查找，安装插件都非常不方便
## 期望行为

希望有一个网站，可以使deepin.org子域名，专门用来列出现在可以安装在dde dock上面的插件，并显示这款插件支持什么版本的deepin，方便用户查找安装插件
### 发行版以及版本

deepin15.10.1

**Comment by BLumia** [comment]
深度应用商店。

对于第三方还没有开发完或者没有打算提交到深度应用商店的插件开发者和它们的插件，这个没有办法主动收集插件（除非插件的许可协议是允许主动再分发的）。

**Comment by justforlxz** [comment]
目前没有这个计划，我们推荐插件开发者提交到深度商店，而不是提供一个专门的网站来分割体验。

**Comment by widon1104** [comment]
![分类中没有插件](https://user-images.githubusercontent.com/12093211/59838967-76392980-9382-11e9-866b-89499af3a2e8.png)
分类中没有插件，用户咋个找插件啊
