### ISSUE TITLE
[archlinux] Please remove "uninstall" on left button click 

### ISSUE THREAD

**Issue by corrosiontears** [linuxdeepin/developer-center#131]
I try to make this function work on Arch like on original Deepin but without sucess. 
I think be more easy simply remove this function. Thanks for the project! Sorry for my english.

**Comment by funilrys** [comment]
I personnaly didn't see the code source but maybe manjaro user can give a possible solution ... Personnaly I always use the terminal to uninstall. But in a way you right it's actually an unworking feature in arch

**Comment by funilrys** [comment]
We can close this @hualet

**Comment by hualet** [comment]
The uninstall should've been disabled for a long time.
