### ISSUE TITLE
希望deepin-boot-maker提供linux版本下载

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1310]
## 缺陷描述

https://www.deepin.org/original/deepin-boot-maker/
上面的网址提供了，windows版本和macos版本下载，但是没有提供linux版本，希望能够提供linux版本方便使用其他linux发行版的人迁移到deepin

## 期望行为

希望直接提供deb和rpm包下载，不要让用户自己编译，自己编译很麻烦
ubuntu都提供了usb-creator-gtk来制作u盘启动器，不过只支持ubuntu镜像

**Comment by BLumia** [comment]
需求 cc @wangjia12

**Comment by widon1104** [comment]
我在 http://mirrors.ustc.edu.cn/deepin/pool/main/d/deepin-boot-maker/
找到了deepin-boot-maker deb版本下载，但是
deepin-boot-maker_2.0.4.11-1_amd64.deb
deepin-boot-maker_2.0.4.9-1+stable_amd64.deb
在ubuntu18.04上面都装不上，依赖太强了，可否优化一下，不要依赖太强了，让其他linux发行版也能用啊

**Comment by BLumia** [comment]
扩展名是 deb 不代表在所有基于 debian 的发行版都通用啊，Qt 版本都不一致怎么用...

如果提供这个独立工具的话，就是相当于把依赖都打包进去。你直接拿适用于 deepin 的版本肯定只能在 deepin 上用。

**Comment by widon1104** [comment]
那就把依赖都打包进去，然后发布到
https://www.deepin.org/original/deepin-boot-maker/ 
上面吧

**Comment by wangjia12** [comment]
大家都可以尝试着打包哦！

**Comment by BLumia** [comment]
欢迎社区贡献者打包 deepin-boot-maker 到你喜欢的发行版 :)
