### ISSUE TITLE
UEFI安装系统自定义分区时没有EFI分区选项，导致安装失败（严重）

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1311]
## 缺陷描述

我的系统BIOS设置是LEGACY+UEFI，原先系统是ubuntu18.04，安装的时候没有任何问题。第一个分区是EFI分区，第二个是根分区，第三个是swap，第四个分区是/home。
今天我想换成deepin15.10.1，前面没啥问题（安装过程中卡了一下，鼠标过了几秒钟才能动），到了自定义分区挂着/efi分区的时候，发现没有efi分区可选，，
![no efi](https://user-images.githubusercontent.com/12093211/59652087-d7180480-91be-11e9-989a-03296c855dcc.jpg)
郁闷了，这让我情可以堪，结果我直接选择不使用这个分区，想蒙混过关，其他分区挂载好，然后继续，希望显示安装失败：
![安装失败](https://user-images.githubusercontent.com/12093211/59652156-16465580-91bf-11e9-861e-de9a54732430.jpg)
然后我原来的系统就挂了，进不去了，然后我在bios里面选择启动从LEGACY+UEFI改为UEFI，这时候在重新装系统，显示：
![警告](https://user-images.githubusercontent.com/12093211/59652219-5ad1f100-91bf-11e9-9eed-2593c4009235.jpg)
然后我只有格式化整个硬盘，这时候就可以选择EFI分区，可以安装了，但是我硬盘东西都丢了

我的BIOS启动里面只有2个选项，1）LEGACY+UEFI 2）UEFI，我想说如果我装ubuntu绝对不会出现这种问题，问题是不是出在启动项是LEGACY+UEFI，deepin安装程序就不能选择EFI分区了，导致安装失败

## 期望行为

BIOS启动项是LEGACY+UEFI也能选择EFI分区

### 发行版以及版本

deepin15.10.1

**Comment by justforlxz** [comment]
看样子应该是第一次引导的时候选了legacy，所以没有efi，安装失败应该看下日志的。第二次看起来是选择了uefi启动，所以检测到和分区表不匹配，所以才要求格式化。不过这是安装器的正常功能，我们在产品层面上约束了legacy+mgr和uefi+gpt，所以才会有这个情况的发生。而且已经提醒了继续会导致数据丢失，应该先求助再选择下一步操作的。

**Comment by widon1104** [comment]
我的BIOS只有2个设置，1：LEAGACY+UEFI 2：UEFI
我装ubuntu18.04的时候，BIOS设置是LEAGACY+UEFI啊，可以选择EFI分区，然后我装deepin15.10.1，BIOS设置没变也是LEAGACY+UEFI，但是这时候却不能选择EFI分区了，这肯定有问题。

**Comment by widon1104** [comment]
而且我感觉安装程序一定要改进，不要动不动就让用户格式化整个硬盘，这个非常不友好

**Comment by BLumia** [comment]
产品定义如此（不允许 legacy 和 efi 混用），并非技术限制。

如有特殊需求，请考虑使用 debootstrap 安装，自行定制安装器或联系购买专业版帮助您定制安装方式。

**Comment by justforlxz** [comment]
都说了是产品规定，你不能总是拿着别人的产品设计来对标我们的产品设计啊，不然大家不都一样了。深度安装器是为了方便普通用户的，高阶用户可以自己动手处理提醒中的问题。

而且不是动不动就让用户格式化整个硬盘，而是你的操作不符合我们的要求，而且我们也提示了如何解决，不能解决的情况也提醒了备份数据等，如果看了提醒仍然下一步导致数据丢失，那应该是用户需要对自己的行为负责。

**Comment by widon1104** [comment]
> 都说了是产品规定，你不能总是拿着别人的产品设计来对标我们的产品设计啊，不然大家不都一样了

我觉得安装系统行为就是做的一样，不然的话还会有很多人要掉坑。

**Comment by BLumia** [comment]
https://www.freebsd.org/doc/en/articles/mailing-list-faq/bikeshed.html
