### ISSUE TITLE
默认终端设置为terminator，深度文件系统中点击"在终端中打开"会有若干问题

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1313]
## 缺陷描述

我会选择使用terminator，因为terminator有好的配色，淡黄背景黑字，深度终端配色不习惯，而且terminator可以分割终端，很强大，所以我把默认终端改成了terminator
在ubuntu系统中没有这个问题的，我在复现步骤中详述如何复现

## 复现步骤

1）先安装terminator，然后把默认终端改成terminator
2）打开一个terminator终端，进入一个目录（比如Desktop)，然后最小化
3）打开深度文件管理器，进入一个目录，右键“在终端中打开”，这时候会弹出一个新的终端，这时候会出现几个问题
1. 原来那个隐藏的terminator这时候也会弹出来显示，这是我不希望的
2. 新打开的终端，目录没有切到文件系统所在目录
3. 新打开的终端，没有在屏幕中间，而且跑在屏幕角落，这也是不友好的

## 期望行为

1. 右键“在终端中打开”，弹出一个新的终端，老的终端不要弹出来
2. 新弹出的终端，目录要切到文件系统所在目录
3. 新弹出的终端，出现在屏幕中间

### 发行版以及版本

deepin15.10.1

**Comment by BLumia** [comment]
右键的打开终端行为实际上就是单纯的调用默认终端程序，调用时终端模拟器的行为是终端模拟器程序自身控制的，不在深度自身的支持范畴内。

作为 workaround ，请创建脚本间接调用你所希望使用的终端模拟器，确保你的脚本调用终端模拟器的行为为你期望的行为，并设置默认终端程序为你的辅助脚本。

**Comment by widon1104** [comment]
让用户自己写脚本调用并不是好的解决方案，如果有10万人想用terminator，就要分别写10万份脚本，写出成千上万的bug，想想都可怕。

**Comment by BLumia** [comment]
所以您的建议解决方案是？

**Comment by widon1104** [comment]
当然是deepin官方来搞啊，搞好一次所有人都收益

**Comment by BLumia** [comment]
> 当然是deepin官方来搞啊，搞好一次所有人都收益

具体的可行方案？如果有特判 terminator 和直接修改 terminator 之外的方案，可以回复到下方。

**Comment by widon1104** [comment]
流行的终端就那么几款，terminator, gnome-terminal, 最多再加一个xterm，如果deepin系统能很好的支持这几款终端，肯定是会加分的。
因为终端并不多，就算特判我觉得应该也不是特别麻烦。

**Comment by BLumia** [comment]
不是深度的 issue 况且深度推荐你使用深度终端的前提下（你提到的几个问题显然是 terminator 这个终端模拟器的行为问题），为啥要 reopen ...

> 深度终端配色不习惯，而且terminator可以分割终端

深度终端是支持自定义配色的，你甚至可以自己写主题然后分享给整个社区。并且深度终端也可以分割终端。

> 失去一个改进系统的机会

个人认为，停止对异样化行为的特判支持有助于改善生态。

**Comment by widon1104** [comment]
深度终端确实可以分割窗口，还可以。但是我还有一个不喜欢深度终端的地方，就是终端字体不能选择我安装在系统的点阵字体Zfull gb，我已经习惯用点阵字体了。而gnome-terminal，terminator都可以选择终端字体为Zfull gb.

**Comment by BLumia** [comment]
> 深度终端确实可以分割窗口，还可以。但是我还有一个不喜欢深度终端的地方，就是终端字体不能选择我安装在系统的点阵字体Zfull gb，我已经习惯用点阵字体了。而gnome-terminal，terminator都可以选择终端字体为Zfull gb.

这并非该 Issue 所对应的内容，请保持一个 Issue 尽可能专注只讨论一个问题。

**Comment by widon1104** [comment]
深度终端中，可执行文件居然是蓝色，而不是其他linux发行版统一使用的绿色，真的是太奇葩了
而且不可执行的文件居然弄成绿色，使用惯了其他终端的人估计很难适应深度终端

而且在深度终端中切换主题也不能改变这些配色，，

**Comment by BLumia** [comment]
1. 请在【分开的 issue】里汇报和原 issue 不相关的问题
2. 请自己看一下你的 bashrc ，显然是会使用 `dircolors` 的配置，这个配置应该是来自 debian stretch 的，不喜欢你自己改就是了
