### ISSUE TITLE
deepin15.10.1 光标放在dock应用图标上面，软件预览是空白

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1314]
## 缺陷描述

deepin15.10.1 光标放在dock应用图标上面，软件预览是空白，值得一提的是我截图下面所有打开软件的预览都是空白

## 期望行为

预览不应该是空白

## 截图

![所有软件预览是空白](https://user-images.githubusercontent.com/12093211/59666122-d1ceb000-91e6-11e9-937f-d20a2123f724.png)

### 发行版以及版本

deepin15.10.1

**Comment by BLumia** [comment]
15.10.2 推送更新会解决此 issue
