### ISSUE TITLE
deepin-wm failed to build on Fedora 31 (Rawhide) with vala 0.44.4

### ISSUE THREAD

**Issue by cheese** [linuxdeepin/developer-center#1316]
## Describe the bug

Full build log: https://gist.github.com/cheese/888afa6ceceabd94e0765acfe48e0315
koji record: https://koji.fedoraproject.org/koji/taskinfo?taskID=35546180
### Distro & Version

Fedora 31 (Rawhide)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
