### ISSUE TITLE
第三方程序打开文件管理器时左边目录框太窄隐藏了文字

### ISSUE THREAD

**Issue by licardoY** [linuxdeepin/developer-center#1317]
## 缺陷描述

第三方程序调用文件管理器时左边目录框太窄,文字被隐藏,需要手动拉宽,而且是每款应用都单独拉宽.比如chrome上传文件时太窄我拉宽了,但是到了火狐里上传文件依旧太窄需要再次手动拉宽
## 复现步骤

第三方程序调用文管如:
- 浏览器上传文件时,
- 浏览器下载文件选择保存位置时,
- IDE导入项目时等等这些第三方程序调用文件管理器的场景
## 期望行为

- 期望以直接打开文件管理器时左边目录框宽度显示,所有应用调用文管都以这个宽度显示;
- 或者手动调整一次其他程序打开都以调整后的宽度而不需要每个第三方应用都要都调整一次;
- 或者统一以文字宽度显示不至于文字被遮挡住.
**总之 期望是1.不要遮挡文字 2.调整一次宽度后全局有效,不要每一款应用都需手动拉宽调整**
## 截图

![0dde-desktop_20190619142510](https://user-images.githubusercontent.com/20562449/59742052-4b29d980-929f-11e9-8b7f-39ce006bbf9c.png)

### 发行版以及版本

`deepin 15.10.1`
### 相关的软件包版本

`dde-file-manager 4.8.4`

**Comment by BLumia** [comment]
> 调整一次宽度后全局有效,不要每一款应用都需手动拉宽调整

这个问题我在我的环境无法复现，不过值得注意的是，文件打开对话框的侧边栏宽度和文件管理器的侧边栏宽度是分开存储的，文件打开对话框实际是 `dde-desktop` 提供的。

我这边试图重现的步骤是：

 - 打开 Google Chrome 并按 Ctrl+O，调整侧边栏到最小，然后关闭文件打开窗口
 - 打开 Firefox ESR 并按 Ctrl+O，观察侧边栏大小，发现是最小，此时调整到最大
 - 回到 Google Chrome 并按 Ctrl+O，观察侧边栏大小，发现是最大。

**Comment by licardoY** [comment]
可恶,怎么我这里也没重现了, 不过这个问题困扰我很久了,我手动调整过很多次宽度了, 后面我再看下什么情况会复现再跟帖吧.

**Comment by BLumia** [comment]
好的，那暂时先关掉了 :)
