### ISSUE TITLE
Deepin 15.10.1 clean install ... freezing intermittently ... eventually crashing out ... the unsaved session is logged off !!

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1318]
## Describe the bug
Deepin 15.10.1 is crashing and logging off on the slightest stress ...

stresses include ...

When a VM is restored from its state of suspend or when its booting up ...
When a few GB's of data is moved/copied from one location to the other ...
any other intensive operation of opening movies and using the file manager whilst the deepin-movie application is yet to open ...

## To Reproduce
As it happens without any particular pattern ... don't' think we can foresee the crashing ... so can't really reproduce 

## Expected behavior
work without issues ... especially given that my system has 16GB of RAM and 16 GB of swap ...

PS : is this some kind of 'Kernel Panic situation ? ... because whilst the crashing takes place the screen briefly goes back to the command prompt and a little while later the login screen is presented.

Please let me know if you want any data out of my affected system immediately after such a panic episode ... let me know the files / commands that will grab the logs for trouble shooting !

**Comment by aiamuzz** [comment]
great ... no response yet ...

the new debian stable seems anything but stable ... even basic operations like trying to save an image from the browser is crashing the OS ... black screen followed by login screen all unsaved data lost !!!

Even if a clean ISO install can throw such instability its hard to run our daily operations on such instability ... to top it all you are ending support to the debian unstable version as early as July given such high instability of the debian stable version !!!

sorry but some really shitty decisions taken by the deepin team ... seems to have rushed into without proper testing ... never ever have i found Deepin OS so unstable right from my first 15.4 versions i started with !!!

assuming my use of deepin-wm on this installation could be causing this crash ... i can't even return to the default kwin bcos the windows effect is in a crashed state continually !!!

SOS ... @BLumia ... @hualet ... @wangjia12 ...

**Comment by aiamuzz** [comment]
@BLumia ... @hualet ... @wangjia12 ...

its becoming unbearable ... the freezes and the subsequent log off is at unbearable levels ... i shutdown ... boot up ... open chrome restore my tabs from the last crash ... rearrange my chrome windows on their designated workspaces ... open deepin file manager ... double click folder ... **BAAM ... system freeze for sometime ... not responding ... SYSTEM CRASH ... SIGNED OFF ...**

relogin ... repeat the above ... open my VMWare VM ... right click image on website to save in chrome  ... **BAAM ... system freeze for sometime ... not responding ... SYSTEM CRASH ... SIGNED OFF ...**

relogin ... repeat the above ... open quake terminal ... not opening ... hit shortcut ... no response ... hit shortcut again ... **BAAM ... system freeze for sometime ... not responding ... SYSTEM CRASH ... SIGNED OFF ...**

relogin ... repeat any of the above ... open something ... delay in opening ... alt tab go to other workspace or other application ... **BAAM ... system freeze for sometime ... not responding ... SYSTEM CRASH ... SIGNED OFF ...**

when system freezes even for the simplest and routine task ... an attempt to move to another open application ... is just crashing the system !!!

**IS THERE AN END TO THIS ?**

**Comment by hualet** [comment]
@aiamuzz can you record a video, please ?

**Comment by aiamuzz** [comment]
> @aiamuzz can you record a video, please ?

the problem is it happens all of a sudden no specific pattern ... but now that you asked ... i'll put it on a stress test ... but i will have to record it on a mobile(with not so great a quality) as the screen recorder will  not be able to record it as all applications get killed !!!

I'll report back once i have the video ...

**Comment by aiamuzz** [comment]
fed up of this fragile issue which would log off ... i reinstalled the OS from scratch ... closing it for now ... hope i don't encounter this issue in my newly installed system.
