### ISSUE TITLE
deepin file manager settings (Arch Linux)

### ISSUE THREAD

**Issue by thedeli** [linuxdeepin/developer-center#132]
Hi, first of all thanks to everyone helping us to use deepin desktop on Arch linux :) I use deepin file manager but I cannot reach settings for it. when I click the help section nothing happens. Are there any settings for file manager?

**Comment by manateelazycat** [comment]
@felixonmars I think we should add deepin-user-manual in depends of dde-file-manager to show deepin-user-manual window when user press F1 or click help menuitem in dde-file-manager.

**Comment by felixonmars** [comment]
I don't think we have deepin-user-manual ported yet... Will do this soon.

**Comment by felixonmars** [comment]
`deepin-manual` has entered [community] today, and deepin-file-manager has been updated to depend on it. Please try again :P
