### ISSUE TITLE
AppImage在深度启动器中消失

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#1321]
昨天安装了米聊，启动器中有，刚开始没图标，通过切换highcolor类主题修复，今天开机，图标消失了，第三方启动器没问题。
自己复制到 ~/.local/share/applications 目录下的 desktop 不显示，反映很久了，你们不承认我也没办法，我的全家桶都在这了。

**Comment by BLumia** [comment]
啥“你们不承认”啊...

cc @electricface

**Comment by electricface** [comment]
使用 desktop-file-validate 检查 desktop 文件格式。最好能相关上传 .desktop 文件。https://specifications.freedesktop.org/desktop-entry-spec/latest/

**Comment by hualet** [comment]
@sonichy

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
