### ISSUE TITLE
[建议]系统监视器快捷键

### ISSUE THREAD

**Issue by lanseyujie** [linuxdeepin/developer-center#1322]
现在默认的打开 **系统监视器** 快捷键是 Ctrl + Alt + Esc, 此组合键通常需要双手配合才能实现, 虽然可以自行修改, 但希望能默认为同 Windows 任务管理期器可单手实现的 Ctrl + Shift + Esc 组合键.
![深度截图_选择区域_20190623130731](https://user-images.githubusercontent.com/16262938/59971999-44f66e80-95b9-11e9-88db-7f46ed8a822e.png)

**Comment by hualet** [comment]
好像都可以单手按出来 :joy:

**Comment by BLumia** [comment]
Ctrl+Alt+Esc 我单手按起来的确也觉得难受（（

**Comment by izee** [comment]
我建议可以考虑改为SYS+M，即System Monitor

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
