### ISSUE TITLE
Deepin 15.10.1 stable 只要使用一段时间（休眠后醒来尤其频繁），火狐或者deepin-wine的程序开一会就没法响应点击

### ISSUE THREAD

**Issue by ihipop** [linuxdeepin/developer-center#1324]
## 缺陷描述
<del>使用双屏办公，主屏幕在副屏幕的左侧，</del>只要使用一段时间（休眠后醒来尤其频繁），火狐或者deepin-wine的程序开一会就没法响应鼠标点击 **（但是响应鼠标hover或者键盘操作）** ，能看见界面上的东西正常闪烁跳动，但是点击不了，托盘图标可以操作。呼出界面一样做不了任何操作。
<del>如果不接双屏 可以正常使用一整天没问题。
从接上双屏到出现无法点击出现的时间不固定，但是如果开多个wine应用或者最小化到托盘一段时间以后再打开 或者</del> 休眠后再恢复 出现的概率会提高。
大部分原生程序不受影响，除了火狐（官网下载的最新国际版）

![深度录屏_选择区域_20190624101559](https://user-images.githubusercontent.com/423077/59986377-336c9f80-9669-11e9-9f07-633918b14f89.gif)

### 发行版以及版本
Deepin 15.10.1 stable 

### 相关的软件包版本
deepin-wine                                     2.18-18

**Comment by ihipop** [comment]
@hualet

**Comment by hualet** [comment]
OK， 我看看内部能不能重现。

**Comment by ihipop** [comment]
@hualet  我安装 gnome-settings-daemon （但是不运行） 出现的概率就很小了，不知怎么才能提供更多调试信息给你们。
出现这个问题的时候 QQ通过托盘点击出的新消息窗口还能操作，但是QQ面板就点击不了。

**Comment by ihipop** [comment]
而且我火狐也有类似的问题，界面能看见点不动。和wine一模一样，不响应鼠标点击，但是响应键盘快捷键刷新和鼠标hover， 长时间双屏锁屏再解锁很容易出现。
![深度录屏_选择区域_20190702131810](https://user-images.githubusercontent.com/423077/60484379-f7ba8100-9ccb-11e9-843f-9581d8d45386.gif)

**Comment by hualet** [comment]
下次再出现这种情况的时候，找一个可以用的终端或者tty，输入一下命令：
```
DISPLAY=:0 xdotool key XF86LogGrabInfo
```
然后，再拿一下 /var/log/Xorg.0.log

**Comment by ihipop** [comment]
@hualet 单屏下遇到一次火狐的不响应点击，我抓了log发你gmail邮箱吧。

**Comment by duanyao** [comment]
我使用微信的时候也遇到类似的情况。
不过我并不使用双屏，这个问题经常发生在刚从待机中恢复的时候（待机前微信就开着），但不是每次待机恢复都会发生。
而且，如果待机前微信和firefox一起开着，那么他们的窗口也都会无法点击。
无法点击的窗口还是可以键盘操作的；如果新打开一个firefox窗口，则新窗口一切正常。
一开始怀疑是 dde-kwin 的问题，但用系统监视器杀掉 kwin_x11 进程，让它重启也没有效果。

这是微信无法点击时按 @hualet 的方法产生的日志：

[Xorg.0.log](https://github.com/linuxdeepin/developer-center/files/3375522/Xorg.0.log)

**Comment by ihipop** [comment]
@duanyao 我一直使用双屏 用着用着就会这样，最近开始用单屏，发现也有小概率会这样，经常发生在待机恢复的时候，不只是微信，QQ和火狐也会这样，就是你说的官网下载的最新版本 但是是国际版
而且你会发现，火狐不响应点击 可以响应键盘刷新，也能响应鼠标hover，我曾经怀疑过是Kwin的问题，但是换了deepin-wm也一样，除了火狐和wine程序，其他应用都正常，感觉可能真的和X有关
@hualet

**Comment by duanyao** [comment]
是的，键盘操作都是正常的。
论坛里可能相关的bug：
https://bbs.deepin.org/forum.php?mod=viewthread&tid=177733

**Comment by kt286** [comment]
无意中发现的临时解决方法
按  Win + →   切换到第个二工作区  然后  win + ←  再切回来就好了

**Comment by duanyao** [comment]
@kt286 我试了你的方法，可惜并没有效果。

**Comment by duanyao** [comment]
更新：

其它会中招的程序：WPS 表格（11.1.0.8392）、dbeaver（6.0.2），均为 deepin 仓库版本。

从未发现中招的程序：vs code、nautilus、deepin-editor、kate，均为 deepin 仓库版本。

其它触发条件：插入USB鼠标，不过概率也不高，可能十几次遇到一次吧。电脑是笔记本，型号 HP Pavilion 14 AL030TX。

**Comment by ihipop** [comment]
开来 双屏不是必然触发的，我现在用单屏也会触发 所以我修改了标题描述以便更好的描述这个问题，@kt286 的方法么有用。

**Comment by ihipop** [comment]
升级到15.11 长时间休眠后醒来还是老样子 火狐不响应鼠标点击

**Comment by duanyao** [comment]
前两天升级 deepin 到最新后，重新插入鼠标对于官方版 firefox 是必然导致问题的了，见 #1455 。

**Comment by ihipop** [comment]
@duanyao 我猜休眠会触发的原因是休眠醒来的时候，USB设备发生了reset，然后系统重新识别相当于是重新插拔了

**Comment by HuangGuSheng** [comment]
> 更新：
> 
> 其它会中招的程序：WPS 表格（11.1.0.8392）、dbeaver（6.0.2），均为 deepin 仓库版本。
> 
> 从未发现中招的程序：vs code、nautilus、deepin-editor、kate，均为 deepin 仓库版本。
> 
> 其它触发条件：插入USB鼠标，不过概率也不高，可能十几次遇到一次吧。电脑是笔记本，型号 HP Pavilion 14 AL030TX。

正解，移除设备（拔出硬件，断开蓝牙等）必然触发此bug

**Comment by ihipop** [comment]
这么久了还是没有解决啊

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
