### ISSUE TITLE
Markdown 空白文件默认应用关联问题

### ISSUE THREAD

**Issue by lanseyujie** [linuxdeepin/developer-center#1325]
## 缺陷描述

新建空白 md 格式文件，设置默认打开的应用为 typora。
当 md 文件没有内容时双击打开默认使用的是 deepin-editor；
有内容时才能双击默认使用 typora 打开；
卸载 deepin-editor 双击空白 md 文件使用的程序又是 vscode 了，总之对于空白文件默认应用无效。

## 复现步骤

创建空白的 md 后缀文件，并设置默认打开应用为 typora ，
双击打开此空白 md 文件，**会使用非 typora 的文本编辑器打开。**

## 期望行为

空白文件时也能通过后缀正确使用默认的关联应用打开。

### 发行版以及版本

Deepin 15.10.1 stable

### 相关的软件包版本

typora
deepin-editor

**Comment by BLumia** [comment]
`mimetype -a <文件名>` 贴一下输出看看？
然后 `xdg-open <文件名>` 看看是不是也有问题？

**Comment by lanseyujie** [comment]
```bash
~$ touch Markdown.md
~$ mimetype -a Markdown.md
Markdown.md: text/markdown
Markdown.md: text/plain
~$ xdg-open Markdown.md
~$ load translate "/usr/share/dtkwidget/translations/dtkwidget2_zh_CN"
load translate "/usr/share/deepin-editor/translations/deepin-editor_zh_CN"
^C
# 使用 deepin-editor 打开了

~$ echo 1111 > Markdown.md 
~$ mimetype -a Markdown.md
Markdown.md: text/markdown
Markdown.md: text/plain
~$ xdg-open Markdown.md
~$ Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
^C
# 使用设置默认的 typora 打开了
```

**Comment by BLumia** [comment]
不知道是不是 qt 的 mimetype 认错了，晚些时候我写个测试程序

另外希望有 arch 或者其它在使用高版本 qt 的发行版的用户测试一下是不是也有这个问题 :joy:

**Comment by BLumia** [comment]
奇怪，我本地看到文件管理器拿到的 mimetype 是正确的。

感谢汇报，有空之后单独追一下这个问题。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
