### ISSUE TITLE
[建议] 右键菜单 - 新建文件

### ISSUE THREAD

**Issue by lanseyujie** [linuxdeepin/developer-center#1326]
安装 wps 会创建在模板目录创建 文件模板，但此路径并不是系统默认的 Templates 目录。
将文件模板正确放在 ~/.Templates 下 右键菜单 - 新建文件 会显示相应模板文件。
但是系统也有默认 4 个文件模板，重复且创建的都是旧版的 doc、xls、ppt 文件。
建议取消此 4 个文件模板并通过预置在 ~/.Templates 文件模板 显示菜单。 
![深度截图_选择区域_20190624093950](https://user-images.githubusercontent.com/16262938/59989377-67e45980-9671-11e9-807e-b06ef60981f5.png)

**Comment by BLumia** [comment]
创建“模板”目录是 WPS 的行为，不是 deepin 的。我也不清楚 WPS 为什么要把模板文件放到那里。

预制到 `~/.Templates` (`xdg-user-dir TEMPLATES`) 其实也不太好，因为显示到右键菜单的项目是需要做本地化（根据语言显示不同的文案）的，直接在模板目录放置是只能使用放置进去的文件名的，故深度文件管理器推荐给第三方的 OEM 新建文档方式是使用[元信息模板](https://linuxdeepin.github.io/dde-file-manager/new-file-templates-zh.html#)，把文件根据规则配置并放到 `/usr/share/templates` 下。实际上 WPS 之前的版本有做这个模板但它的配置是无效的，所以也没有显示，在 WPS 2019 后这个错误的配置直接被移除了。

**Comment by sonichy** [comment]
我的 /usr/share/templates 下有模板，但是深度文管没有显示。

**Comment by BLumia** [comment]
> 我的 /usr/share/templates 下有模板，但是深度文管没有显示。

没有正确配置的模板是不会显示的，可以 `cat` 看看里面指向的文件是不是不存在（
WPS 之前的版本的问题就是配置指向的模板文件不存在）。

**Comment by lanseyujie** [comment]
直接放在 `xdg-user-dir TEMPLATES` 确实会有本地化问题哈，我没想到这一点

**Comment by BLumia** [comment]
暂时先关掉了，这个问题可以考虑联系一下 wps 的人员反馈，感谢汇报问题～
