### ISSUE TITLE
蓝灯程序图标在系统托盘中显示为空白

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1329]
## 缺陷描述

在https://github.com/getlantern/lantern下载lantern以后启动lantern，系统托盘图标无法显示
![看右小角](https://user-images.githubusercontent.com/12093211/60029222-4f0c9000-96d3-11e9-9e00-ad2895d289d7.png)
看截图右小角，lantern确实已经运行，按右键有弹出菜单，但是图标没有显示

## 期望行为

lantern图标显示在系统托盘上

### 发行版以及版本

deepin15.10.1

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
