### ISSUE TITLE
KMail system tray icon not showing

### ISSUE THREAD

**Issue by alexandre1985** [linuxdeepin/developer-center#1330]
## Describe the bug

KMail icon does not show in system tray dock.
## Expected behavior
Show KMail icon on system tray dock

## Screenshots
![taskbar-systemtray](https://user-images.githubusercontent.com/5586308/60135650-b8eb6f00-9791-11e9-8797-4d830b450be5.png)

## Enviroments:
Deepin

### Distro & Version
Manjaro Linux Deepin x64

### Related package version
`kmail` version 19.04.2

### Additional context
When I close KMail window the process `kmail` is still running. So this is working as expected. The only thing that is not working is showing KMail's icon on Deepin system tray Dock.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
