### ISSUE TITLE
希望在 lion 源里添加 earlyoom 包

### ISSUE THREAD

**Issue by duanyao** [linuxdeepin/developer-center#1332]
## 缺陷描述
2年前因为我的推荐，deepin 的仓库里增加了 earlyoom 包 （ https://github.com/rfjakob/earlyoom/   https://bbs.deepin.org/forum.php?mod=viewthread&tid=144358&  ）。目前 panda 源里仍然有这个包，但 lion 源里就没有了。

根据我的体验，earlyoom 对于防止 deepin 系统卡死是不可或缺的，所以希望添加到 lion 源。我认为 deepin 最好能默认安装它。在我2年多的使用中，未发现 earlyoom 有什么缺陷。

**Comment by BLumia** [comment]
https://packages.debian.org/source/buster/earlyoom

后续应该会有

cc @deepinzhangshuang

**Comment by Zeno-sole** [comment]
v20的仓库中添加了earlyoom https://community-packages.deepin.com/deepin/  deepin 15已经停止更新, 请使用deepin 20版本
