### ISSUE TITLE
File manager does not detect changes on shared folders

### ISSUE THREAD

**Issue by ErikEklund** [linuxdeepin/developer-center#1333]
## Describe the bug
If files are dragged from any program except File Manager to a folder on a mounted share, the file list does not refresh.

## To Reproduce
1. Open a program from which you can drag and drop files. For example, double click a ZIP file to open Archive Manager
2. Open a File Manager window and navigate to a mounted share
3. Select a file in Archive Manager and drag/drop it to the File Manager window
4. Observe that the file list does not update (but the file is extracted and copied correctly). To see the file, you must navigate away from the directory and back again.

## Expected behavior
The file list should update as soon as new files has appeared in the directory

### Distro & Version
Arch Linux 5.14.1, fully updated rolling Deepin as of 2019-06-26

### Related package version
dde-file-manager 1:4.8.6.4-2

### Additional context
Mount is a CIFS samba mount

**Comment by BLumia** [comment]
Hey thanks for the report. What's the value of your `fs.inotify.max_user_watches`?, did you open intellij-idea or visual studio code or something else which may take all your inotify watcher since the default value is small?

assoc: https://github.com/linuxdeepin/developer-center/issues/1289

**Comment by ErikEklund** [comment]
It was shortly after a reboot with only Chrome, terminal and file manager opened. I'm currently at work so can't check the max_user_watches value right now, but I will get back to you on that in a few hours. I don't think that's the issue however.

It does work if you copy from another File Manager window to the share, it only seems to happen if you drag files from other applications to the share window. Even if Samba does not support directory change signals, I guess you should be able to recognise files being dropped onto the file manager and trigger a refresh that way?

**Comment by ErikEklund** [comment]
`
cat /proc/sys/fs/inotify/max_user_watches 
524288
`

**Comment by BLumia** [comment]
Oh will check this issue later, btw you can actually press <kbd>F5</kbd> to refresh the file module(also file view).

**Comment by ErikEklund** [comment]
> Oh will check this issue later, btw you can actually press F5 to refresh the file module(also file view).

Ah, I did not know that. I checked the menus / settings for a refresh option or keybind but did not see one. Thanks for the tip.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
