### ISSUE TITLE
[建议]文件管理器右键菜单增加“显示隐藏的文件”开关项

### ISSUE THREAD

**Issue by joseph1002** [linuxdeepin/developer-center#1334]
打开深度文件浏览器，如果想显示隐藏文件，需要点击右上角菜单栏"设置"弹出对话框以打开显示开关。如果想隐藏，也要同样这么操作。一来一回相当麻烦。

因为Home目录有很多隐藏的文件，一般找到想要的文件后，为了保持列表干净，同时避免误操作，都会再去关闭显示开关。

希望右键菜单增加个"显示隐藏文件"的菜单项，方便操作，提高效率。

**Comment by licardoY** [comment]
CTRL+H

**Comment by BLumia** [comment]
产品设计上应该不会加，可以考虑使用 <kbd>Ctrl+H</kbd>，感谢反馈 :)
