### ISSUE TITLE
deepin-editor 打不开3M文本文件

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1335]
## 缺陷描述

我发现deepin-editor打开文件慢，然后自己生成了一个3M的文本文件，发现用deepin-editor CPU100%等了2分种都打不开，然后用vim在终端2秒种左右就能打开，
打开不开的文件就在下面，可以试试分别用deepin-editor和vim打开，看看效果
[CanNotOpen.txt](https://github.com/linuxdeepin/developer-center/files/3338617/CanNotOpen.txt)

## 期望行为

deepin-editor能够在合理的时间打开较大的文本文件

### 发行版以及版本

deepin15.10.1 deepin-editor1.2.7.3

**Comment by BLumia** [comment]
![image](https://user-images.githubusercontent.com/10095765/60379947-37386180-9a6f-11e9-91f2-7f5238420021.png)

单行大文件大概是大多编辑器硬伤。

感谢汇报问题。

**Comment by BLumia** [comment]
由于和 https://github.com/linuxdeepin/developer-center/issues/1408 是同一个问题，挪到那个 issue 跟进此缺陷。
