### ISSUE TITLE
[BUG] Hot Corners do not function when running some Citrix Workplaces/Receiver apps 

### ISSUE THREAD

**Issue by Iiari** [linuxdeepin/developer-center#1338]
## Describe the bug

When running some apps on Citrix Receiver (a popular client software for remote access to corporate and enterprise environments) that seem to break the Deepin hot corners, which no longer respond.

## To Reproduce
Run apps using Citrix, and try hot corners.  They work fine, however, switching to a non-Citrix app.

## Expected behavior
Normal hot corners behavior. 

## Enviroments:
Manjaro Deepin

### Distro & Version
Deepin 15.10.1

### Related package version
N/A

### Additional context
Given the similarity of Deepin to Cinnamon hot corners (I've always presumed Deepin's were forked from Cinnamon's), I tested Citrix apps there and the Cinnamon hot corners work without difficulty.  Same for KDE and the hot corners app skippy-XD with Citrix apps.

**Comment by hualet** [comment]
KDE should have the same issue if we have this since our WM's based on KWin now.

**Comment by Iiari** [comment]
Thank you for your reply.  I'm not sure what to tell you.  No problems on KDE at all, yet with some Citrix Apps the hot corners don't detect on Deepin.  Do you want me to take a screen video capture?  Anything I can do to help diagnose?

**Comment by Iiari** [comment]
As an update, it seems to be only the top left hot corner which isn't working with Citrix.  The others seem to be working well....

**Comment by Iiari** [comment]
As an update, it seems to be only the top left hot corner which isn't working with Citrix.  The others seem to be working well....  This is the same corner that seems to require more effort than the others to activate as well.  Perhaps that area needs to be remapped-rezoned?
