### ISSUE TITLE
建议deepin在.bashrc中不要默认使用dircolors改变颜色

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1340]
## 缺陷描述

我以前用ubuntu，ubuntu默认的.bashrc使用
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
的方式，使得ls，grep等工具输出带颜色，我感觉这个颜色比dircolors配置的颜色自然

这里面我贴出ubuntu .bashrc的设置，可以和deepin自带的对比一下
[bashrc_ubuntu.txt](https://github.com/linuxdeepin/developer-center/files/3352904/bashrc_ubuntu.txt)
ubuntu .bashrc开启了一些deepin没有开启的东西，使用--color=auto没有使用dircolors

### 发行版以及版本

deepin15.10.1

**Comment by BLumia** [comment]
同学，请您看一下 dircolors 的 man page 。

**Comment by widon1104** [comment]
linux系统默认不同类型文件所使用的颜色：
    白色：表示普通文件
    蓝色：表示目录
    绿色：表示可执行文件
    红色：表示压缩文件
    浅蓝色：链接文件
    红色闪烁：表示链接的文件有问题
    黄色：表示设备文件
    灰色：表示其它文件

希望deepin还是按默认的来
