### ISSUE TITLE
Tag information isn't working properly

### ISSUE THREAD

**Issue by herculesgabriel** [linuxdeepin/developer-center#1342]
## Describe the bug
Issue 1: When you rename a tag this change doesn't happen unless you close the file manager and open it again.
Issue 2: When you use customized titles for tag and you mark new files with the same colors of a customized tag, it creates another group of files with the name of the color instead of group those files with the others.

## To Reproduce

1. Take some files to test (PDF files, for example).
2. Tag it with a color. Let's say red.
It will be showed in the "red" group in the file manager. 
3. Now rename the group with a custom title ("work files").
At this point you could see the group isn't renamed. You will need to close the Deepin File Manager and open it again. Now it's renamed.
4. Tag another file with the same color (red).
You could see that another group was created with the name of the color instead of being part of the "work files".
-

## Expected behavior
1 - The tags you rename it's not supposed to need a restart to be showed.
2 - New tagged files should appear on the customized tag you renamed before.

## Screenshots
https://drive.google.com/open?id=1HTf29hwsUUvRYB7gsbc5q01rAc133NgQ

### Distro & Version
Deepin 15.10.1 x86_64

### Related package version
dde-file-manager (4.8.4-1+comsta)

### Additional context

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
