### ISSUE TITLE
系统监视器导致系统假死

### ISSUE THREAD

**Issue by codexvn** [linuxdeepin/developer-center#1343]
## 缺陷描述
打开系统监视器之后立即进行切换选项卡操作会导致系统假死

## 复现步骤
打开系统监视器之后立即操作右上角选项卡 [应用进程|我的进程|所有进程] 会导致系统假死，此时可以进入tty2

## 期望行为
系统监视器可以正常使用

### 发行版以及版本
Arch Linux 
Kernel: x86_64 Linux 5.1.15-arch1-1-ARCH
dde最新版
### 相关的软件包版本
deepin-system-monitor 1.5.2-1

**Comment by fwinac** [comment]
我也遇到了这个问题，在切换显示的后台程序的类别的时候。
deepin 15.10.2。 @BLumia @hualet

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/developer-center/issues/1377

下次更新中修复，感谢反馈 :)

**Comment by licardoY** [comment]
这种严重的bug修好了就应该推送一次吧，轻则要强制重启电脑，重则写文档之类的保存不了造成的损失是难以估量的。用户遇到这种致命bug对deepin绝对产生会很不好的印象。真的建议这种**破坏力太强**的bug及早修复及早推更新，按常规的更新节奏推不知要让多少人掉到这个坑里坑死用户了

**Comment by BLumia** [comment]
> 这种严重的bug修好了就应该推送一次吧，轻则要强制重启电脑，重则写文档之类的保存不了造成的损失是难以估量的。用户遇到这种致命bug对deepin绝对产生会很不好的印象。真的建议这种**破坏力太强**的bug及早修复及早推更新，按常规的更新节奏推不知要让多少人掉到这个坑里坑死用户了

预计更新是今天或明天，因为目前情况来看推 hotfix 和推普通更新需要的时间基本差不多一样 - -||
