### ISSUE TITLE
Deepin file manager iso mount can't install anything in Wine

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#1345]
## Describe the bug
Deepin's mounted .iso can't install anything to Wine.
I have tested 4 games, which worked perfectly fine if you just unzip this iso to folder.

## To Reproduce
1. Mount any program / game
2. Try to install it in Wine
3. It will surely fail

## Expected behavior
Should just work, since now it's little bit useless for any Windows related .iso...

### Distro & Version
Arch / Manjaro Deepin / Pretty sure Linux Deepin too

### Additional context
I'm no expert here, but knowing Windows programs - maybe it's caused by too long mount path?
```
/run/user/1000/gvfs/archive:host=file%253A%252F%252F%252Frun%252Fmedia%252Fx133%252FSTORAGE%2525202%252FGames1%252FBatman%252520Arkham%252520city%252FDVD%2525201.iso/
```
Generally windows programs don't like this kind of long paths.

**Comment by BLumia** [comment]
Also not familiar with wine but FYI all gvfs mounted(in dde-file-manager, it include smb, ftp, sftp, mtp, and archive scheme) file location's path is in that format. Maybe you can test if nautilus or pcmanfm-qt also have this issue since they also use gio/gvfs as their backend.

**Comment by keybreak** [comment]
Tested on Arch:
**Nautilus** mounts to (with rmb - Open With Disk Image Mounter):
```
/run/media/username/isoname
```
- It's default mount point for real drives on Arch / Manjaro
- Correctly installs game from .iso

So i guess it would make total sense to do same, because mostly i think people would use .iso for programs / games from Windows, and more rarely for disks with data (which have no issues in both cases)

**Comment by BLumia** [comment]
> Tested on Arch:
> **Nautilus** mounts to (with rmb - Open With Disk Image Mounter):
> 
> ```
> /run/media/username/isoname
> ```

Well FYI for local device processing we are planned to move to udisks2 and after that the mount location will be a more reasonable one. The current implement is just simply a `gio` call in the following format(see `AppController::actionMountImage` if anyone interested in this action):

``` shell
$ gio mount archive://<url_encoded_file_scheme_url_to_your_iso_file>
```

Currently no ETA for when will the udisks2 refactor will start, please keep tracking the process on dde-file-manager repo and [udisks2-qt](https://github.com/linuxdeepin/udisks2-qt5) repo.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
