### ISSUE TITLE
[BUG] Left Upper Hot-Corner Less Sensitive (Issue from closed Citrix and Hot Corner Report)

### ISSUE THREAD

**Issue by Iiari** [linuxdeepin/developer-center#1346]
## Describe the bug
Previously in the closed thread, I described that the hot corners weren't working with Citrix Receiver.  Doing some tinkering with kwin/dconf/kwinrc, I found that it's really only the left upper hot corner that doesn't work with Citrix.  The others do.  Interestingly, this is also the hot-corner location that in normal use is the hardest to trigger and seems to need the most "pressure."  Perhaps this area needs to be rezoned/remapped?
 
## To Reproduce
Hot corner use with/without Citrix.

## Expected behavior
The the left upper corner be as snappy as the others, which it isn't.

## Screenshots
None

## Enviroments:
Manjaro Deepin 

### Distro & Version
Deepin 15.10.1

**Comment by BLumia** [comment]
Not sure but maybe you can also test if kwin (under kde) also have this issue?

cc @zccrs

**Comment by Iiari** [comment]
Hello.  Thank you for your interest, and thank you all for the Deepin DE, which so many of us use and enjoy so much.  15.11 looks like another great upgrade.

So, I actually run KDE on a few other machines (and Cinnamon as well as Gnome and Budgie... I use them all) and have never had this hot corner problem.  As of my last attempt on 15.10, it was just the upper left corner with Citrix and only in Deepin (both in mutter and kwin).  That corner, for me, has also always seemed the hardest to activate.

I've been playing with my system and last night tried to install the (excellent) Low Latency Kwin package (https://github.com/tildearrow/kwin-lowlatency) over Deepin-Kwin, and it seems to work shockingly well (I also installed the KDE System Settings to have access to some of the Low Latency Settings).  That might actually solve the above problem, but I'm still experimenting and will get back to you.

I don't know if you have many other user running Citrix apps, but they're pretty vital in the enterprise and if you're ever looking to test stuff, I'm happy to help.  I'll post how Citrix works with the low latency overlay later.  Thanks!

**Comment by Iiari** [comment]
Even with low-latency kwin, while everywhere else on the screen works (hot corners and edges), that left upper one doesn't.  I can make you a video if needed.  Any debug suggestions?

**Comment by Iiari** [comment]
[Nearly identical bug reported on KDE/Kwin in 2012 onward](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&cad=rja&uact=8&ved=2ahUKEwjkjv3LzuXjAhWi2FkKHZQpC7EQFjACegQIBRAB&url=https%3A%2F%2Fforum.kde.org%2Fviewtopic.php%3Ff%3D111%26t%3D102161&usg=AOvVaw0WGMsG2Jgm7XpOigsc_MGK).

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
