### ISSUE TITLE
取色器移动有残影

### ISSUE THREAD

**Issue by jetmit** [linuxdeepin/developer-center#1347]
## 缺陷描述

取色器移动有残影
## 复现步骤

打开取色器,移动但不取色,会出现很多圆圈

## 截图

![深度录屏_选择区域_20190705140413](https://user-images.githubusercontent.com/20562449/60701513-96461c80-9f2e-11e9-91f0-2490dc32d994.gif)

### 发行版以及版本

15.10.1 stable
### 相关的软件包版本

1.6.5-1+comsta

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
