### ISSUE TITLE
不能在多个设备同时安装同一应用

### ISSUE THREAD

**Issue by ziqiangxu** [linuxdeepin/developer-center#1348]
## 缺陷描述
我有多个设备，应用商店都登录同一账户，在安装应用商店 `3D Slicer` 的时候，在一台设备上安装之后，其他设备的应用商店中，此应用的页面则显示已下载，无法安装。

## 期望行为

同一账号所有设备均能同时安装任意一款应用

### 发行版以及版本
其中两台设备是15.10（`stable`），一台设备是 `unstable`

**Comment by Iceyer** [comment]
@ziqiangxu 能提供一些截图以及商店的版本信息吗，目前测试环境无法重现这个问题。

**Comment by ziqiangxu** [comment]
> @ziqiangxu 能提供一些截图以及商店的版本信息吗，目前测试环境无法重现这个问题。

现在这个问题消失了（unstable的应用商店找不到这个应用了已经）
