### ISSUE TITLE
What is qt5dxcb-plugin?

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/developer-center#135]
I just noticed that this new package has been introduced on Archlinux. It is not required by any other package and I wonder when or if I will need it... Could you give me a little info on this, please? :wink: 
Thank you.

**Comment by hualet** [comment]
It's a platform plugin for Qt by dde team, aimed to provide better rendering of custom Qt windows. As development of multiple Qt plugins going on, we've merged the project into [qt5integration](https://github.com/linuxdeepin/qt5integration) project, and the package will later replaced by dde-qt5integration. So a better choice is to wait for the dde-qt5integration release :)

**Comment by hualet** [comment]
Issue closed.
