### ISSUE TITLE
蓝牙连不上会不停报警

### ISSUE THREAD

**Issue by htqx** [linuxdeepin/developer-center#1351]
## 缺陷描述
蓝牙连不上设备会不停报警，dingdingding～～，右上角会不停冒泡信息。只有关闭蓝牙才会停止。

## 复现步骤
1. 之前连接过的设备
2. 某种原因连不上（可能被其他链接占用）

## 期望行为
不要一直响

## 复现环境:
15.10.1

### 发行版以及版本
15.10.1

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
