### ISSUE TITLE
应用商店回退能不能保持当前位置？

### ISSUE THREAD

**Issue by htqx** [linuxdeepin/developer-center#1354]
## 缺陷描述
软件商店点某个软件，然后回退到之前的页面，它没有记录当前浏览的位置，而是恢复到top状态，如果能记住当前位置，那么就更加愉快了。

## 复现步骤
1. 点应用商店
2. 点系统管理
3. 滚动到中间，点任意一个软件进入软件详情页
4. 点右上角的 < ，回到系统管理，但是并不处于页面中间，而是重新回到顶部

## 期望行为
记录位置，提高易用性

### 发行版以及版本
15.10.2

### 相关的软件包版本
应用商店

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
