### ISSUE TITLE
BUG : partition property window showing \x20 instead of spaces

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1355]
Hi,

partition property window showing characters instead of spaces ... seems this is the case only for NTFS partitions

![image](https://user-images.githubusercontent.com/3283676/60752771-470ff280-9fe7-11e9-8488-bbbfa81ef9be.png)

**Comment by BLumia** [comment]
Thanks for reporting. This is a known bug of qtbase and should be fixed after Deepin catched up the new Deepin buster release :)

**Comment by myml** [comment]
after the new update It seems fixed.

**Comment by myml** [comment]
Because there no confirm for a long time, I close it.
