### ISSUE TITLE
Windows Effects Issues on 15.10 ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1356]
Hi,

**Problem 1 :** Unable to enable 'Windows Effect' option on kwin windows manager ... this has been since 15.10.2 ... continues on 15.10.3 which i have updated yesterday ... I tried downloading dde-kwin and reinstalled but the windows effect continues to crash ... a fix is appreciated as i am not able to test kwin windows manager(even though Deepin-WM is my daily driver)

**Problem 2 :** with the above issue i am on Deepin-WM currently ... after i updated yesterday to 15.10.3 the settings show Window effect is disabled but as you can see in the screen grab that the shortcuts for windows views, workspace views are working but the bottom left corner gives the Window effect is disabled error.

![deepin-screen-recorder_google-chrome_20190706123715](https://user-images.githubusercontent.com/3283676/60753091-90624100-9feb-11e9-81f4-cac2042ff311.gif)

**Comment by thukuwanjiku** [comment]
I've been struggling with Failed to enable window effect error for weeks too. In system update to 15.11 the changelog said they had fixed this error but it still persists. URGENT HELP NEEDED!

**Comment by aiamuzz** [comment]
> I've been struggling with Failed to enable window effect error for weeks too. In system update to 15.11 the changelog said they had fixed this error but it still persists. I cannot even open Deepin ScreenRecorder! URGENT HELP NEEDED!

@thukuwanjiku ... have you modified the kwinrc file at ~/.config/kwinrc ... then rename it to kwinrc.backup and reboot ...

**Comment by thukuwanjiku** [comment]
@aiamuzz thaanks bigtime! Your solution did it for me. I'm now a happy user.

**Comment by aiamuzz** [comment]
> @aiamuzz thaanks bigtime! Your solution did it for me. I'm now a happy user.

good to know your issue got fixed ...

@thukuwanjiku ... can you share you `kwinrc.backup` file with us ? ... It could help in troubleshooting what the actual issue was !

**Comment by thukuwanjiku** [comment]
@aiamuzz how do I share it with you please?

**Comment by aiamuzz** [comment]
@thukuwanjiku ... you could just drag and drop the 'kwinrc.backup' file to this github posting window ... as its a text file it will get attached automatically and we'll be able to download it ...

can you share your current newly created 'kwinrc' file along with the 'kwinrc.backup' file ?

**Comment by aiamuzz** [comment]
@thukuwanjiku ... this issue of Windows effect failing ... since when are you facing ?
Did you do a fresh iso install ? ... Are you facing it right from the moment of this fresh install ?

**Comment by thukuwanjiku** [comment]
> @thukuwanjiku ... you could just drag and drop the 'kwinrc.backup' file to this github posting window ... as its a text file it will get attached automatically and we'll be able to download it ...
> 
> can you share your current newly created 'kwinrc' file along with the 'kwinrc.backup' file ?

I had to rename and add the .txt extension github wasn't recognizing the format



[kwinrc.txt](https://github.com/linuxdeepin/developer-center/files/3417033/kwinrc.txt)
[kwinrc.backup.txt](https://github.com/linuxdeepin/developer-center/files/3417039/kwinrc.backup.txt)

**Comment by thukuwanjiku** [comment]
> @thukuwanjiku ... this issue of Windows effect failing ... since when are you facing ?
> Did you do a fresh iso install ? ... Are you facing it right from the moment of this fresh install ?

Yes I did a fresh install about 3 weeks ago. The first week it all was working fine. Into the second week I realized I couldn't user the screen recorder and the window effects toggle on control panel was off and gave the error anytime I tried.

**Comment by aiamuzz** [comment]
@BLumia ... @zccrs ...

seems the setting `OpenGLIsUnsafe=true` has been causing this problem ... if i remember right initially after a fresh install of 15.10 ... the window effect worked ok ... as i was pretty annoyed with kwin i had installed deepin-wm and moved on ... when later i tried coming back to kwin i faced this window effect issue ... i thought i might have broken it somehow as i was using deepin-wm all the while ...

now @thukuwanjiku ... and his account suggests that somewhere in 15.10.1 or may be later the 'OpenGLIsUnsafe' setting got set to 'True' causing this issue ... 

Hope you are able to identify what operation changed this value from 'false' to 'true' and fix the same ...

**Comment by thukuwanjiku** [comment]
> @BLumia ... @zccrs ...
> 
> seems the setting `OpenGLIsUnsafe=true` has been causing this problem ... if i remember right initially after a fresh install of 15.10 ... the window effect worked ok ... as i was pretty annoyed with kwin i had installed deepin-wm and moved on ... when later i tried coming back to kwin i faced this window effect issue ... i thought i might have broken it somehow as i was using deepin-wm all the while ...
> 
> now @thukuwanjiku ... and his account suggests that somewhere in 15.10.1 or may be later the 'OpenGLIsUnsafe' setting got set to 'True' causing this issue ...
> 
> Hope you are able to identify what operation changed this value from 'false' to 'true' and fix the same ...

Honestly I cannot tell what operation changed that value. Using my laptop on a daily basis, it's hard to tell what operation changed what.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
