### ISSUE TITLE
[Arch Linux] Deepin terminal no blur background in quake

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#1358]
## Describe the bug
When Deepin terminal blur background enabled - quake terminal still doesn't have it.

## Expected behavior
Should be blurred when option enabled, like main terminal window :smiley_cat: 

## Enviroments:
OS: Manjaro 18.0.4 Illyria
Kernel: x86_64 Linux 5.1.15-1-MANJARO
Shell: bash 5.0.7
DE: Deepin 15.10.1
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
compiler: gcc 9.1.0
tk: Qt 5.12.4
dm: LightDM

### Distro & Version
Arch / Manjaro Deepin

### Related package version
deepin-terminal  3.2.7-1

**Comment by BLumia** [comment]
Should be easy to fix, will do it later, patches are welcome (https://github.com/linuxdeepin/deepin-terminal/commit/28a4438cf15726eb2ae7eb8c1ab28298e27f17b2 can be take as a reference).

**Comment by Mark-AAAA** [comment]
![ezgif com-optimize](https://user-images.githubusercontent.com/52075807/60825447-6445ec00-a1b4-11e9-9c19-7fc5e408ada2.gif)

Everything works fine x86_64 Linux 5.1.16-arch1-1-ARCH, Deepin 15.10.2.

**Comment by keybreak** [comment]
It's under deepin-kwin only now, it seems

**Comment by Mark-AAAA** [comment]
> It's under deepin-kwin only now, it seems

Maybe. I'm currently using deepin-wm 1.9.38-1.

**Comment by BLumia** [comment]
> It's under deepin-kwin only now, it seems

Of course since the blur use kwin's `_KDE_NET_WM_BLUR_BEHIND_REGION` atom (on deepin-wm, it use `_NET_WM_DEEPIN_BLUR_REGION_ROUNDED`).

**Comment by BLumia** [comment]
Thanks to @timothyvanderaerden and it will be fixed in the next release :)

**Comment by gchamon** [comment]
Hey there! How are you doing?

How is the status on this issue? `deepin-wm`, which is now deprecated, broke on arch and, after installing `deepin-kwin` I got almost everything back, except for quake terminal background blur. What am I doing wrong?

Thanks!

**Comment by BLumia** [comment]
> Hey there! How are you doing?
> 
> What is the status on this issue? `deepin-wm`, which is now deprecated, broke on arch and, after installing `deepin-kwin` I got almost everything back, except for quake terminal background blur. What am I doing wrong?
> 
> Thanks!

What's your deepin-terminal version? The fix is in https://github.com/linuxdeepin/deepin-terminal/commit/6b03f796f0ac5624d3515f692e55ad9f7b47a8d3 so you should make sure your version included the fix.

**Comment by gchamon** [comment]
![image](https://user-images.githubusercontent.com/9471861/65967649-5a8cf700-e438-11e9-8c87-1d284eb37f56.png)
![image](https://user-images.githubusercontent.com/9471861/65967697-6d9fc700-e438-11e9-9995-a07f00ab45e6.png)

`Deepin Terminal 5.0.0`

I use rolling release arch linux

**Comment by BLumia** [comment]
We don't have a new tag which include that fix right now, and it seems deepin-terminal doesn't have a `-git` version in Arch, so if you don't want to wait (I guess it will comes at the same time as other deepin product with their v20 initial release) for the tag release, you can build the terminal by yourself :)

**Comment by gchamon** [comment]
Thanks for the update! :D

**Comment by xmuli** [comment]
It looks like it can be closed,, plus a new terminal address:[deepin-terminal](https://github.com/linuxdeepin/deepin-terminal)
 and [deepin-terminal-old](https://github.com/linuxdeepin/deepin-terminal-old)
