### ISSUE TITLE
开始菜单能不能设置大小和高度？

### ISSUE THREAD

**Issue by htqx** [linuxdeepin/developer-center#1359]
## 缺陷描述
开始菜单是固定的，希望能够调整大小，在大屏幕下，它所占空间太小，感觉有点浪费空间。

## 复现步骤
1.点击开始按钮
2.无法调整大小

## 期望行为
可以拖动大小或者可以用配置文件设置宽度和高度。

## 截图

![image](https://user-images.githubusercontent.com/42466118/60762933-44bba000-a09c-11e9-9bc8-b34b60c096fa.png)

## 复现环境:
15.10.2

### 发行版以及版本
15.10.2

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
