### ISSUE TITLE
【待机唤醒问题】当打开占用比较大内存的时候，容易待机失败甚至卡死

### ISSUE THREAD

**Issue by jay763190097** [linuxdeepin/developer-center#1360]
比如：浏览器在播放视频。或者打开Idea、eclipse这样的内存大户，或者打开一些wine应用。

![深度截图_选择区域_20190707113244](https://user-images.githubusercontent.com/16317178/60763630-f2ce4680-a0aa-11e9-9da0-10fafc8e4394.png)

有直接卡死的情况，也有读取swap分区失败，也有进入桌面没有任何之前打开应用的情况。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
