### ISSUE TITLE
【显卡驱动问题】尝试升级英伟达显卡驱动失败

### ISSUE THREAD

**Issue by jay763190097** [linuxdeepin/developer-center#1361]
![深度截图_选择区域_20190707155913](https://user-images.githubusercontent.com/16317178/60765642-312a2c80-a0d0-11e9-99c9-9369c9132bb6.png)
![230359kn7ezlynrmfbfvjr](https://user-images.githubusercontent.com/16317178/60765651-50c15500-a0d0-11e9-88f9-649eb1b607c4.png)
![深度截图_选择区域_20190707155952](https://user-images.githubusercontent.com/16317178/60765653-5454dc00-a0d0-11e9-8751-d8f05d43e34b.png)

尝试从300升级到400，可是卸载不掉。。。。。。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
