### ISSUE TITLE
【BUG】dde-kwin 将全屏窗口拖拽成普通窗口后光标错位

### ISSUE THREAD

**Issue by lolimay** [linuxdeepin/developer-center#1362]
## 缺陷描述

在 dde-kwin 下，将全屏窗口往下拖拽时，光标会从标题栏跳到窗口上方一段距离。
## 复现步骤

1. 打开 deepin-terminal
2. 双击标题栏使得窗口充满屏幕
3. 鼠标左键长按标题栏往下拖拽，使得 deepin-terminal 恢复成正常窗口大小
4. 发现光标往上偏移一段距离

## 期望行为

光标与窗口的相对位置保持不变

## 截图

![深度录屏_选择区域_20190708014639](https://user-images.githubusercontent.com/32427260/60772060-1c2ab900-a123-11e9-862d-60a9dd8eddd8.gif)
### 发行版以及版本

Deepin 15.10.2
### 相关的软件包版本

dde-kwin/panda,now 0.0.11-1 amd64 [已安装]

**Comment by BLumia** [comment]
只有深度终端会这样吧。应该是因为深度终端的阴影也是深度终端自己画的而不是窗管。

**Comment by lolimay** [comment]
原来不是 dde-kwin 的锅

**Comment by zccrs** [comment]
> 只有深度终端会这样吧。应该是因为深度终端的阴影也是深度终端自己画的而不是窗管。
> 
> edit: 看上去gtk3的大多应用也都有这问题，cc @zccrs

使用了 _GTK_FRAME_EXTENTS 窗口属性的窗口都会存在这个问题，kwin本身是不支持 _GTK_FRAME_EXTENTS 属性的，目前是 deepin-kwin 项目中加了临时支持。但是效果还不够理想，等所有 DDE 应用都不再依赖 _GTK_FRAME_EXTENTS 属性后，将去除对此属性的临时支持。
