### ISSUE TITLE
System interface stops responding when copying/moving or extracting heavy files

### ISSUE THREAD

**Issue by mathpfvr** [linuxdeepin/developer-center#1363]
Deepin 15.10.2 when opening the system monitor and clicking on "user open process tab" the system stops responding

**Comment by hbhgwtf** [comment]
> Deepin 15.10.2 when opening the system monitor and clicking on "user open process tab" the system stops responding

I also encountered this bug after update 15.10.2, but I could go into tty mode, and the bug did not reappear on my PC after I restarted the machine.

**Comment by BLumia** [comment]
cc @zccrs

**Comment by gokhanyildirimlar** [comment]
Can it be related? 
https://github.com/linuxdeepin/developer-center/issues/1160

**Comment by dance707** [comment]
> > Deepin 15.10.2 when opening the system monitor and clicking on "user open process tab" the system stops responding
> 
> I also encountered this bug after update 15.10.2, but I could go into tty mode, and the bug did not reappear on my PC after I restarted the machine.

Same issue on my Arch deepin with deepin-kwin installed. no need to be copying files to reproduce freeze

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
