### ISSUE TITLE
Integrate snap and flatpak into the Deepin Store so you can focus more on system updates than keeping your repositories up to date

### ISSUE THREAD

**Issue by mathpfvr** [linuxdeepin/developer-center#1365]

**Comment by alexwender1** [comment]
As already exist websites (Flathub and Snapcraft), it is essential to integrate the Deepin with such services; developing "one-click installation".

Flathub.org
![Captura de Tela_selecionar área_20190707215005](https://user-images.githubusercontent.com/45263160/60776256-3b185380-a101-11e9-974e-2f016d717f0f.png)

Snapcraft.io/store
![Captura de Tela_selecionar área_20190707215016](https://user-images.githubusercontent.com/45263160/60776257-3d7aad80-a101-11e9-882b-6c8f9698fe25.png)

When the user accesses Flathub (or Snapcraft) and clicks on install; an interface will open, informing that certain application is being downloaded.

![appimage](https://user-images.githubusercontent.com/45263160/60776528-5be1a880-a103-11e9-98b9-96338f1fb263.png)
We can not forget AppImage! There are two websites that catalog the applications (appimagehub.com/browse and appimage.github.io/apps); but none, presents itself as a store.

It would be important to have an AppImage session inside the Deepin App Store.

![Linux-App-Store-Main](https://user-images.githubusercontent.com/45263160/60776533-6308b680-a103-11e9-94ba-ff3dc036a406.jpg)
This website (linuxappstore.io) has the purpose of cataloging the AppImage, Flatpak and Snappy applications from their respective App Store.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.

**Comment by lxwndr** [comment]
I opened a new topic in https://github.com/linuxdeepin/developer-center/issues/2084
