### ISSUE TITLE
Use Wayland on Deepin, please!

### ISSUE THREAD

**Issue by mathpfvr** [linuxdeepin/developer-center#1366]

**Comment by gpen365** [comment]
Maybe don't remove xorg, but it would be awesome to have Wayland for dde

**Comment by aiamuzz** [comment]
Isn't the jury still out on which one is better ?
whatever ... certainly don't want to end up with another shocker like the recent `deepin-wm` to `dde-kwin` ...

@mathpfvr ... @gpen365 ... 

It would be better if you could point out a specific feature / option that currently deepin under Xorg can't accomplish but it could do better if it was running/using wayland !!!

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
