### ISSUE TITLE
Text tool does not work in Deepin 15.10.1 screenshot

### ISSUE THREAD

**Issue by mathpfvr** [linuxdeepin/developer-center#1368]
The tools arrow, dash, rectangle, the screen captures work correctly, but the text mode does not work
For example, when you type a letter, nothing is displayed, but if you type with accent, the letters

**Comment by BLumia** [comment]
Thanks for reporting, please upgrade your system to Deepin 15.10.2 which delivered deepin-screenshot 4.2.1.
