### ISSUE TITLE
Use Fedora or Ubuntu base for next version of Deepin, please!

### ISSUE THREAD

**Issue by mathpfvr** [linuxdeepin/developer-center#1369]

**Comment by aiamuzz** [comment]
i guess you need to suffice by installing DDE on Fedora / Ubuntu ...

https://computingforgeeks.com/install-deepin-desktop-environment-ubuntu-linux-mint/

**Comment by BLumia** [comment]
There is no plan about switch to ubuntu (ubuntu have no arm and mips arch support which we need).

There are people from Fedora community working on Fedora port of DDE applications. You can also take part in the process :)

**Comment by pranavvv** [comment]
bring tencent gaming buddy on deepin
