### ISSUE TITLE
[建议]“登录界面”模糊效果

### ISSUE THREAD

**Issue by cctfc** [linuxdeepin/developer-center#1370]
这时现在的模糊：
![深度截图_选择区域_20190708090639](https://user-images.githubusercontent.com/38755949/60776763-0e942400-a161-11e9-8bc0-7d24ffee1e41.png)
这是 feren os kde 登录界面
![深度截图_选择区域_20190708091213](https://user-images.githubusercontent.com/38755949/60776792-32f00080-a161-11e9-90d5-fd59b932ea19.png)
很明显，deepin 的模糊，太透了一点。我觉得没有后一种好看；而且 deepin 现在的模糊也影响看文字。

**Comment by licardoY** [comment]
我更喜欢kde和Windows10那种直接能看清晰壁纸的,很好看,本来一张很美的壁纸做背景干嘛要模糊呢
之前论坛也有帖子建议直接壁纸的,喜欢的人挺多的

**Comment by SuperEndermanSM** [comment]
我喜欢现在这种比较透的模糊，之前deepin-wm的那种感觉是糊了一层shi

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
