### ISSUE TITLE
【BUG】多任务视图不能正确地显示多个工作区的桌面背景

### ISSUE THREAD

**Issue by lolimay** [linuxdeepin/developer-center#1371]
## 缺陷描述

启动 dde-kwin 的`多任务视图`，发现其不能正确地显示多个工作区的桌面背景，表现为所有的工作区的背景全都为当前工作区的背景。

## 复现步骤
复现步骤为:
1. 新建一个工作区，并将两个工作区设置为不同的桌面背景
2.  打开 `多任务视图`
2. 发现所有屏幕的背景都与当前工作区的背景相同

## 期望行为

不同屏幕应显示其所在工作区的背景
## 截图

![深度截图_选择区域_20190708225704](https://user-images.githubusercontent.com/32427260/60820284-bb0eee00-a1d3-11e9-8f72-6fc2d35bc768.png)

![1](https://user-images.githubusercontent.com/32427260/60820213-9286f400-a1d3-11e9-965d-5e513b57c367.jpg)

![2](https://user-images.githubusercontent.com/32427260/60820113-5eabce80-a1d3-11e9-829c-2aacffa14bee.jpg)

### 发行版以及版本

Deepin 15.10.2
### 相关的软件包版本

```bash
[Desktop Entry]
Type=Application
Name=Multitasking View
GenericName=Multitasking View
Icon=deepin-multitasking-view
Terminal=false
Categories=GNOME;GTK;System;
Exec=dbus-send --session --dest=com.deepin.wm --print-reply /com/deepin/wm com.deepin.wm.PerformAction int32:1
OnlyShowIn=Deepin;
X-AppStream-Ignore=true
```

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
