### ISSUE TITLE
之前版本可添加多个桌面，新版本最多只能添加４个桌面，可否增加桌面数量

### ISSUE THREAD

**Issue by mrleemz** [linuxdeepin/developer-center#1372]
## 缺陷描述
之前版本可添加多个桌面，新版本最多只能添加４个桌面，可否增加桌面数量

### 发行版以及版本
Linux Deepin 15.10.2

**Comment by lolimay** [comment]
4个工作区还不够用啊...我觉得你缺的应该不是工作区，而是分屏>_<

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
