### ISSUE TITLE
3000x2000分辨率下扩展屏幕分辨率显示问题

### ISSUE THREAD

**Issue by mrleemz** [linuxdeepin/developer-center#1373]
## 缺陷描述
3000x2000分辨率下扩展屏幕分辨率显示偏大，无法设置扩展屏幕缩放比例
## 复现步骤
复现步骤为:
1. 连接扩展屏幕

## 期望行为
可以设置扩展屏幕缩放比例

## 复现环境:
matebook x pro 2019, 外接屏幕分辨率1920*1080

### 发行版以及版本
Linux Deepin 15.10.2

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
