### ISSUE TITLE
文件管理器无法复制文件到 WebDAV 目录

### ISSUE THREAD

**Issue by ShuiHuo** [linuxdeepin/developer-center#1374]
## 缺陷描述
文件管理器中将文件复制到挂载了 WebDAV 的目录会提示空间不足

## 复现步骤
描述可以重现缺陷（BUG）的操作步骤，以便我们复现缺陷并进行修复
复现步骤为:
1. 通过 davfs2 挂载到一个目录
2. 打开文件管理器，随便复制一个文件到之前挂载的位置
3. 缺陷 '文件管理器提示空间不足' 发生

## 期望行为
文件管理器能正确识别 WebDAV 的可用空间，并且有更快的读取速度

## 截图

![复制到 WebDAV 目录提示空间不足](https://user-images.githubusercontent.com/7471938/60930731-5776e480-a2e9-11e9-8e0a-5a6d41d07a5a.png)

### 发行版以及版本
Arch Linux

### 相关的软件包版本
deepin-file-manager v1.8.2 (4.8.6.4-3)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
