### ISSUE TITLE
nvidia 940mx/intel hd driver not working 

### ISSUE THREAD

**Issue by pranavvv** [linuxdeepin/developer-center#1375]
## Describe the bug
I have Nvidia 940mx/Intel HD 520 card but Nvidia card is not detected when I type nvidia-smi .i have download all necessary packages but it not working

## To Reproduce

-->

### Distro & Version
 Linux Deepin 15.10.2
![DeepinScreenshot_dde-desktop_20190710173529](https://user-images.githubusercontent.com/34711035/60969250-d3e7e280-a33e-11e9-84d2-c56c03269bd7.png)
![photo_2019-07-10_18-17-06](https://user-images.githubusercontent.com/34711035/60969310-f4b03800-a33e-11e9-8f3e-6f8476202ebb.jpg)
![photo_2019-07-10_18-17-06](https://user-images.githubusercontent.com/34711035/60969325-fb3eaf80-a33e-11e9-981a-2234631ea473.jpg)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
