### ISSUE TITLE
[CRITICAL] Deepin system monitor freeze system on view mode swtich

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#1377]
## Describe the bug
Whenever you switch system monitor to this mode - whole system becomes completely unresponsive and freeze.

You can't do absolutely nothing with it, except hard reset.
It's 100% repeatable bug.

## Screenshots
![image](https://user-images.githubusercontent.com/47599989/61041782-9a18e980-a3db-11e9-99ef-7573a92521a8.png)

## Enviroments:
OS: Manjaro 18.0.4 Illyria
Kernel: x86_64 Linux 5.1.16-1-MANJARO
Shell: bash 5.0.7
DE: Deepin 15.10.1
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
compiler: gcc 9.1.0
tk: Qt 5.13.0
dm: LightDM

### Distro & Version
Manjaro Deepin

### Related package version
deepin-system-monitor  1.5.2-1

**Comment by Mark-AAAA** [comment]
It crashes unexpectedly, with no reason, but, no one of the developers cares...https://github.com/linuxdeepin/deepin-system-monitor/issues/31

**Comment by dance707** [comment]
see  #1363

**Comment by keybreak** [comment]
@dance707 
Thx, sorry i haven't realized it was same!

**Comment by BLumia** [comment]
This issue will be fixed in the next update in the upcoming days (within https://github.com/linuxdeepin/qt5dxcb-plugin/commit/8ee20d5751120bb1d1005f9a9dc47bef8f15dd12), but I'm not sure if it is same as #1363 ( I cannot reproduce #1363 ).

**Comment by keybreak** [comment]
Solved with recent Arch update
