### ISSUE TITLE
[BUG] SPACE BAR PREVIEW EXIT BUTTON IS WRONG!

### ISSUE THREAD

**Issue by Mark-AAAA** [linuxdeepin/developer-center#1378]
For some reason after latest updates, when you tap spacebar on a selected file, the preview has an white-blue when is hovered button instead of an "X".

x86_64 Linux 5.2.0-arch2-1-ARCH, Deepin 15.11

![DeepinScreenshot_dde-desktop_20190711224352](https://user-images.githubusercontent.com/52075807/61080324-7c747000-a42d-11e9-94ae-e7e73a4d7ce8.png)
![DeepinScreenshot_dde-desktop_20190711224430](https://user-images.githubusercontent.com/52075807/61080328-7da59d00-a42d-11e9-94d3-14326c492127.png)
![deepin-screen-recorder_dde-file-manager_20190711223931](https://user-images.githubusercontent.com/52075807/61080330-7da59d00-a42d-11e9-96db-31ac0cd4f950.gif)

**Comment by BLumia** [comment]
Should fixed in the next update within https://github.com/linuxdeepin/dtkwidget/commit/3128c340bded20d34bea5d3c2fdf8571b1aec3f8 . There is not a new tag yet due to the QA period is not done.

**Comment by Mark-AAAA** [comment]
Just go fixed!
