### ISSUE TITLE
系统监视器卡死整个桌面

### ISSUE THREAD

**Issue by htqx** [linuxdeepin/developer-center#1379]
## 缺陷描述
系统监视器卡死

## 复现步骤
1. 打开系统监视器
2. 点右上角头像图标

## 期望行为
修复bug

## 截图

![系统监视器卡死bug](https://user-images.githubusercontent.com/42466118/61099346-8d0c0100-a494-11e9-9ed4-05abae825c55.png)

## 复现环境:
15.10.2

### 发行版以及版本
deepin 15.10.2

### 相关的软件包版本
1.deepin-system-monitor

**Comment by BLumia** [comment]
和 https://github.com/linuxdeepin/developer-center/issues/1343 与 https://github.com/linuxdeepin/developer-center/issues/1377 重复，先关掉了，请移步那两个 issue 追踪这个问题的进度。

这个问题下次推送的更新就会修复，感谢反馈～
