### ISSUE TITLE
[greeter] Intrusive behavior and non-compliance to desktop standards

### ISSUE THREAD

**Issue by sim590** [linuxdeepin/developer-center#138]
I have the feeling that the deepin lightdm greeter is causing intrusive and standard non-compliant behavior upon launching desktop environments in addition to #108 which I suspect to be related, but the latter is totally out of guess.

## My setup

I'm using archlinux with lightdm as desktop manager and awesomeWM as standalone window manager. I do have all of the archlinux deepin packages installed too.

## Bad experiences

A first bad exeperience I've had recently is the following. I had the locales `fr_CA.UTF-8` and `en_CA.UTF-8` enabled through my `/etc/locale.gen` file conf. I launched deepin desktop and used the right configuration panel to set my locale appropriately because it was not honoring my configuration from /etc/locale.conf which contained `fr_CA.UTF-8`. Only `fr_FR.UTF-8` was available for french, so I picked it up to try. Then, I went back to awesome window manager and decided to change my locale to `en_US.UTF-8` through `/etc/locale.conf`. I also removed `fr_FR.UTF-8` which had been added automatically through using the right configuration panel from deepin desktop. But then, after relogging back in (even rebooting the pc) my locale was all broken. Some programs said locale was not availale and were crashing while `localectl status` was outputing `System Locale: LANG=en_US.UTF-8` as expected. I could not understand as my `/etc/locale.conf` was showing `LANG=en_US.UTF-8`, but in a terminal, doing `echo $LANG` was outputting the old and removed locale `fr_FR.UTF-8`. Then, I understood that deepin was doing some custom configuration override EVEN THOUGH I'm logged inside awesome window manager and not deepin. I went back to deepin and turned the locale to english and logged back into awesome and it was alright again.

The above shows that the deepin lightdm greeter is doing some nasty standard non-compliant things when launching any desktop environment.

Another experience I've had which supports my above claim is the following. I have `~/.config/autostart/` desktop files which should be loaded when loading deepin, but it should absolutely not be loaded when loading awesomeWM. One of my `~/.config/autostart/*.desktop` file contains this:
```
notify-send <some_title> <some_text>
```
When launching awesome, I can see the file executed and it is decorated with deepin theme. The greeter is clearly provoking this which is I think is a bad, buggy and dangerous thing.

**Comment by justforlxz** [comment]
This question has not been answered for too long and will be closed. If there is a need to continue the discussion, it will be reopened.
