### ISSUE TITLE
深度编辑器编辑的内容无法对齐

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1380]
## 缺陷描述

[buduiqi.txt](https://github.com/linuxdeepin/developer-center/files/3385890/buduiqi.txt)
上面buduiqi.txt是一个非常简单的文档，使用gedit和vim打开2行的“1”是对齐的，但是用deepin-editor打开2个1就是不对齐的，很奇怪，其实这个文档很简单，第一行1前面2个tab，第二行1前面8个空格，如果一个tab解释为4个空格，2个1就应该是对齐的，但是就是不对齐
deepin-editor的截图如下：
![buduiqi](https://user-images.githubusercontent.com/12093211/61118812-1c80d680-a4cc-11e9-9024-419c28b4454a.png)

gedit的截图如下 ：
![duiqi](https://user-images.githubusercontent.com/12093211/61118885-4508d080-a4cc-11e9-8bc9-f6bef487fad3.png)

## 期望行为

2个1能够对齐
### 发行版以及版本

deepin15.10.2 deepin-editor1.2.9

**Comment by BLumia** [comment]
复现步骤?

判断可能是你用了非等宽字体并分别使用了 tab 和 space 进行缩进。

**Comment by BLumia** [comment]
哦 noto mono 可以复现。问题待查。

**Comment by widon1104** [comment]
deepin-editor 1.2.9.1 这个问题还没有修复

**Comment by xmuli** [comment]
文本编辑器 5.6.12 可以复现

**Comment by z966768** [comment]
![截图录屏_选择区域_20200728140026](https://user-images.githubusercontent.com/54103531/88626576-71928900-d0dd-11ea-9cd2-6b48b124634e.png)
查看一下设置界面的tab宽度是否设置为4

**Comment by z966768** [comment]
暂时关闭这个issue,有新的问题,请重新开启

**Comment by widon1104** [comment]
就这样一个小bug,1年半了未修复,还要关issue....

**Comment by z966768** [comment]
更新一下,求你了
![image](https://user-images.githubusercontent.com/54103531/106248726-57806180-624c-11eb-9673-fe054b1ecf06.png)
开发可能顺手就改掉了,但是我这边是没有通知的,没法掌握每个issues的进度,长时间没有动态的issues需要关闭,避免冗余

**Comment by widon1104** [comment]
deepin文件编辑器5.9.0.24 还是有问题，并没有修复这个bug

**Comment by z966768** [comment]
5.9.0.24还属于内测不稳定版,可能新的修改中又引出了这个bug。目前已对外发布的最新版本为5.9.0.10,麻烦暂时换这个版本使用

**Comment by widon1104** [comment]
deepinV20.2文件编辑器5.9.0.49还没有修复这一个问题

**Comment by pgxppp** [comment]
家庭版5.9.0.53已修复

**Comment by widon1104** [comment]
我现在使用deepinV20.2.1，深度编辑器如何升级到5.9.0.53 ？

**Comment by YutianGe** [comment]
> 我现在使用deepinV20.2.1，深度编辑器如何升级到5.9.0.53 ？
你试试5.9.0.48
