### ISSUE TITLE
Freshly Installed ISO 12th July ... i can't enable Windows Effect !!!

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1381]
Hi,

@BLumia ... @hualet ... considering the lack of resources to fix issues already reported previously ... I decided to re-install Deepin OS 15.10 (ISO) afresh today ...

Letting bygones be bygones ... i am reporting things afresh after this fresh and clean ISO install i did today ... hope the issues are looked into and resolved consistently.

I am unable to enable the 'Windows Effect' ... as a result i am unable to run Deepin Screen Recorder so i could record and post it here ...

**Comment by aiamuzz** [comment]
Let me know if this 'Windows Effect' bug is a known one and its fix is a WIP ...

FYI ... after the fresh install i ran the update wizard and the OS has successfully upgraded to 15.10.2 ... the 'Windows effect' seems hasn't been resolved.

PS : As a result of this i am unable to use conky(which is a standard on my desktop), unable to run screen recorder, the shortcuts for screenshot, screen recorder, to move between workspaces none of them are working.

**Comment by aiamuzz** [comment]
the whole experience 'alt-tab' to switch between open applications/windows is very very slow and buggy ...

Deepin File manager is taking forever to load folders its very unresponsive(operations like scrolling/selecting items)

hoping to make life a little easier and livable given the overall i tried attempting to install deepin-wm ... facing the following problem ...

```
sudo apt-get install deepin-wm
[sudo] password for muz: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 deepin-wm : Depends: libdeepin-mutter0g but it is not installable
             Depends: libdeepin-wm0 (= 1.9.35-1+stable) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

```
$ sudo apt-get install libdeepin-wm0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libdeepin-wm0 : Depends: libdeepin-mutter0g but it is not installable
E: Unable to correct problems, you have held broken packages.

```

```
$ sudo apt-get install libdeepin-mutter0g
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libdeepin-mutter0g is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libdeepin-mutter0g' has no installation candidate

```

hmmmmm ... life continues to be miserable ... no reprieve until one of you helps ...

@keybreak ... any help you can offer ?

**Comment by keybreak** [comment]
Sorry, i'd like to help if i could, but it's devs business here :smile_cat:

**Comment by aiamuzz** [comment]
windows effect is working after i deleted the kwinrc files and all its backups in the format kwinrc-xxxx
