### ISSUE TITLE
[Bug]deepin-anything占用过高

### ISSUE THREAD

**Issue by fwinac** [linuxdeepin/developer-center#1382]
![深度截图_选择区域_20190712203554](https://user-images.githubusercontent.com/38755949/61128582-d5530f80-a4e4-11e9-9381-aaa6f961ecc1.png)
deepin-anything 每过几天就会出现一次“长时间高占用”情况，这次已经过去两三个小时了。
系统：deepin 15.10.2
intel i5 8250u
想另外再多说几句。deepin 的小问题真的太多了。就不说这个功能 bug，界面 bug 都不少。
就拿应用商店来说。
翻译不完全：
![深度截图_选择区域_20190712204255](https://user-images.githubusercontent.com/38755949/61128880-b1dc9480-a4e5-11e9-8170-c85144f1ee6b.png)
拖动卡顿：
![深度录屏_选择区域_20190712204118](https://user-images.githubusercontent.com/38755949/61128798-7c37ab80-a4e5-11e9-8dc3-969b50e7228e.gif)
虽然接下来说的比较过分，不吐不快。
这些 bug 又不是什么逻辑无解、又不是什么难得一见的稀罕事，仔细用一下，都能发现吧。其他系统也有不少 bug，但是 deepin 犯的大多是低级错误，这真是个大问题。

**Comment by BLumia** [comment]
anything 占用是调低过优先级的，cc @zccrs .

商店和其他 dde 应用是分开开发和测试的，我就不太熟悉了.. cc @Iceyer .

:sweat_smile: 另外考虑不同的 bug 请单独开 issue 提（一个 issue 提多个问题会让 bug tracking 变困难），谢了。

**Comment by zccrs** [comment]
anything的运行时间没有问题。cpu占用的确是不应该长时间那么高，在cpu占用高期间有文件搜索或者大量的文件创建/删除/移动等操作？

**Comment by fwinac** [comment]
> anything的运行时间没有问题。cpu占用的确不应该长时间那么高，在cpu占用高期间有没有文件搜索或者大量的文件创建/删除/移动等操作？

没有的，在看 pdf。

**Comment by zccrs** [comment]
> > anything的运行时间没有问题。cpu占用的确不应该长时间那么高，在cpu占用高期间有没有文件搜索或者大量的文件创建/删除/移动等操作？
> 
> 没有的，在看 pdf。

这个问题可以总结一下，比如看一下能否找到出现问题的规律，如果每次使用某个软件时，或者做某些特定操作时都会出现这样的问题。发现了这样的规律后可以在任务里说明一下详情，这样更方便排查和解决问题。
