### ISSUE TITLE
Deepin screensaver - flurry error

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#1383]
## Describe the bug
There's at least 50%+ chance that if you use flurry screensaver it will be just black screen. This was bug since day 1 of deepin-screensaver.

Here's what i've found **journalctl -p 4 -xb**:
```
jul 12 20:03:43 x133-pc deepin-screensaver[27464]: requestActivate() called for  ScreenSaverWindow(0x560c22404b30)  which has Qt::WindowDoesNotAcceptFocus set.jul 12 20:03:43 x133-pc com.deepin.ScreenSaver[730]: X error in flurry:
jul 20:03:43 x133-pc com.deepin.ScreenSaver[730]: X Error of failed request:  BadWindow (invalid Window parameter)
jul 12 20:03:43 x133-pc com.deepin.ScreenSaver[730]:   Major opcode of failed request:  20 (X_GetProperty)
jul 12 20:03:43 x133-pc com.deepin.ScreenSaver[730]:   Resource id in failed request:  0x6e00015
jul 12 20:03:43 x133-pc com.deepin.ScreenSaver[730]:   Serial number of failed request:  233
jul 12 20:03:43 x133-pc com.deepin.ScreenSaver[730]:   Current serial number in output stream:  233

```

## To Reproduce
1. Set scrensaver to 1 minute
2. Choose flurry
3. Wait
4. Repeat until black screen

## Expected behavior
Never fail.

## Enviroments:
OS: Manjaro 18.0.4 Illyria
Kernel: x86_64 Linux 5.1.16-1-MANJARO
Shell: bash 5.0.7
DE: Deepin 15.10.1
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
compiler: gcc 9.1.0
tk: Qt 5.13.0
dm: LightDM

### Distro & Version
Any

**Comment by keybreak** [comment]
@BLumia 
Also, maybe there's some hidden config file in **deepin-screensaver** to change default flurry mode from random to classic like it's in xscreensaver?

**Comment by BLumia** [comment]
Not sure, @zccrs

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
