### ISSUE TITLE
Deepin Flatpak apps and other flatpak apps decommissioned ... please upgrade package dependencies to run higher versions of flatpak

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1384]
@BLumia ... @hualet ...

Has Deepin decommissioned the Deepin flatpak apps as well as other flatpaks on Deepin Store ? I am guessing these flatpak apps where acting as the stone that tied very old versions of flatpak ...

If the flatpak apps are no longer supported instore then could you please upgrade the dependencies to run atleast one of the following ... 

[flatpak (1.2.4-1)](https://packages.debian.org/buster/flatpak) - Buster(Stable)
[flatpak (1.4.2-2)](https://packages.debian.org/sid/flatpak) - Sid(Unstable)

Currently Deepin OS runs a very very old and primitive flatpak version as a result we are unable to install latest version of Flatpak application as well as applications that or based on it.

```
flatpak --version
Flatpak 0.8.9
```

Now that we are on stable ... shouldn't Deepin's package dependencies too be in line with the Debian Stable branch ?

In the older unstable version of DeepinOS ... i had managed to install and run Flatpak 1.0 ... but here on the DeepinOS stable branch i am not able to install even that ...

**Appreciated your help in upgrading backend dependencies on Deepin OS ...**

**Comment by aiamuzz** [comment]
I am having trouble installing all these ...

Breaks existing package 'libc-bin' dependency libc6 (< 2.25)
Dependency is not satisfiable: libc6 (> 2.28)
libostree
;
etc

All my flatpak apps that could run on Flatpak 1.0 on my DeepinOS unstable have been rendered unusable here on DeepinOS Stable installation.

**Comment by aiamuzz** [comment]
strange dependency problem ... when i am trying to install flatpak 1.2 ...
```
sudo gdebi flatpak_1.2.2-1_amd64.deb
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: xdg-desktop-portal (>= 0.10)
```

though the asking dependency for xdg-desktop-portal is >=0.10 ... this dependency issue is showing even though the the system shows version 0.5

```
apt list xdg-desktop-portal
Listing... Done
xdg-desktop-portal/lion,now 0.5-1 amd64 [installed]
```

**Comment by BLumia** [comment]
FYI we have plan to upgrade our package repo to catch up buster release, but it need some time to do migrating(since buster just released a few days ago, we also need repackage dde package and test compatibility). No plan to switch back to sid for now, though.

**Comment by aiamuzz** [comment]
> FYI we have plan to upgrade our package repo to catch up buster release, but it need some time to do migrating(since buster just released a few days ago, we also need repackage dde package and test compatibility). No plan to switch back to sid for now, though.

good to know that in future our package repo will be in line with the latest of the debian releases ...

But can the flatpak specific dependencies be resolved a little faster ... all my flatpak apps from DeepinOS unstable branch which allowed me to install and run Flatpak 1.1 are dead in the water as they are not able to run on the current DeepinOS stable ... i specifically install Flatpak apps to its own separate partitions so i can run the same apps across multiple boot installations.

the above libc and related dependencies are really what we need to run higher versions of flatpak directly from upstream releases.

**Comment by dance707** [comment]
@alamuzz For now I use flatpak version 1.2.4-1~bpo9+1 with stretch-backports until we up to Buster

**Comment by aiamuzz** [comment]
> @alamuzz For now I use flatpak version 1.2.4-1~bpo9+1 with stretch-backports until we up to Buster

@dance707 ... which OS are you using ?

If you are using DeepinOS and not a DDE port ... then can you tell me how did you get `flatpak 1.2.4-1~bpo9+1` to work on DeepinOS ?

**Comment by dance707** [comment]
@alamuzz  https://backports.debian.org/Instructions/
Deepin stable/lion is based on Debian Stretch until we up to Buster. Stretch/backports is for some packages recompiled so they will run without new libraries when possible. 
sudo apt-get -t stretch-backports install flatpak

**Comment by aiamuzz** [comment]
> @alamuzz https://backports.debian.org/Instructions/
> Deepin stable/lion is based on Debian Stretch until we up to Buster. Stretch/backports is for some packages recompiled so they will run without new libraries when possible.
> sudo apt-get -t stretch-backports install flatpak

Yay !!!
thanks a ton ... @dance707 !!! ... you made my day !!! ... Didn't know of the backports

**Comment by aiamuzz** [comment]
I can manage this way ... until Deepin update package repo's matching Buster !!!

**Comment by myml** [comment]
This has been done
