### ISSUE TITLE
[Feature Request] Support for 10 bit / 12 bit displays

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#1385]
## Description
Even when all main components are met:
1. GPU supports it
2. Display supports it
3. Cable (display port) supports it

Now if you choose this nvidia option and reboot there will be no Deepin DE (at least no dock or settings).

I know it is probably technically heavy request, but since we're not in a hurry...It would be nice to have one day :smile_cat: 

P.S. Tested only with **deepin-wm**, but i doubt it's because of compositor.

## Screenshots
![image](https://user-images.githubusercontent.com/47599989/61172974-14d93480-a595-11e9-9023-cb60f26e658f.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
