### ISSUE TITLE
Window size not recording their last size ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1388]
Hi,

I have freshly installed DeepinOS 15.10.2 and have been testing stuff one by one ... i have come across this issue where the Window sizes aren't being recorded ... i have tried to set my desired windows sizes for application like ... DeepinEditor ... DeepinTerminal ... DeepinFileManager ... GoogleChrome ... none of these window sizes are set as per the sizes i require ... a new instance of these applications ends up opening window sizes at some default setting ... user setting is not getting written/recorded over this default windows size settings.

Cheers.

**Comment by aiamuzz** [comment]
as you can see here ... the dock was showing only on Workspace 1 ... i was recording this screen on workspace 3 ... when i wanted to turn the recorder off ... i couldn't draw the dock from the edge of the workspace 3 screen ... i had to navigate to workspace 1 and then access the dock over there to turn off the screen recorder.

#

![deepin-screen-recorder_google-chrome_20190715124259](https://user-images.githubusercontent.com/3283676/61201124-28a1a980-a701-11e9-86e5-b41b3a7ba71c.gif)

**Comment by BLumia** [comment]
I cannot reproduce the window size issue on my machine. FYI if you opened multiple window of an app, it will only remember the size of last closed one.

**Comment by aiamuzz** [comment]
> I cannot reproduce the window size issue on my machine. FYI if you opened multiple window of an app, it will only remember the size of last closed one.

I know that ... even the last window size is not being recorded ... 
could you tell me the config file where the windows size and window placement information recorded ... would deleting or modifying it manually help set a window size ...?

**Comment by BLumia** [comment]
The application itself managed its own behavior about where and how to show the window, for dde-file-manager it's in `~/.config/deepin/dde-file-manager/dde-file-manager.obtusely.json`.

Please notice that window-manager can also affact this behavior (like force resize the window), so maybe you can also try remove your current kwinrc file (if you are using dde-kwin with your own custom config) and logout to check if it's a wm config issue.

**Comment by aiamuzz** [comment]
> The application itself managed its own behavior about where and how to show the window, for dde-file-manager it's in `~/.config/deepin/dde-file-manager/dde-file-manager.obtusely.json`.

Are you referring to this part of the file which determines the size of the window ?
```
    },
    "WindowManager": {
        "SplitterState": {
            "sidebar": 193
        },
        "ViewColumnState": {
            "259": 140,
            "260": 140,
            "262": 140,
            "265": 613
        },
        "WindowState": {
            "height": 695,
            "width": 1226
        }
    }
```
@BLumia ... so if i manually alter the height and width and restart file manager ... it should show the window in that size ... right ?


> Please notice that window-manager can also affact this behavior (like force resize the window), so maybe you can also try remove your current kwinrc file (if you are using dde-kwin with your own custom config) and logout to check if it's a wm config issue.

I have tried deleting the current kwinrc and rebooted ... the issue remains ... so i guess the possibility of window-manager being the spoil sport can be safely ruled out ...

**Comment by BLumia** [comment]
> o if i manually alter the height and width and restart file manager ... it should show the window in that size ... right ?

In your case, next time you launch a new dde-file-manager instance, the window size should be:

``` json
        "WindowState": {
            "height": 695,
            "width": 1226
        }
```

And every time when you close the dde-file-manager window, this value will be updated to the size of the last closed dde-file-manager window.

**Comment by aiamuzz** [comment]
> > o if i manually alter the height and width and restart file manager ... it should show the window in that size ... right ?
> 
> In your case, next time you launch a new dde-file-manager instance, the window size should be:
> 
> ```json
>         "WindowState": {
>             "height": 695,
>             "width": 1226
>         }
> ```
> 
> And every time when you close the dde-file-manager window, this value will be updated to the size of the last closed dde-file-manager window.

yeah even i understood it to work that way ... but unfortunately it isn't working that way ...
the size is working well in Deepin-WM ... seems kwin is conflicting with the File manager design architecture with regard to the size and position of windows ... 

@BLumia ... you might want to identify the issue that's conflicting with deepin rules ... let me know if you need any data off my machine to diagnose the issue further ...

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
