### ISSUE TITLE
Dock showing on only one of the workspace !

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1389]
Hi,

I have freshly installed DeepinOS 15.10.2 and have been testing stuff one by one ... I am facing this issue where the dock seems to be available only on one of the 4 workspaces ... i restart the dock and it turns out it shows up on the workspace where i have initiated the dock restart ... the rest of the workspaces are dock'less

Is this a known issue ... a little irritating having to keep restarting the dock on every workspace i visit ... even with a shortcut to restart it its pretty annoying !!!

Cheers.

**Comment by BLumia** [comment]
I cannot reproduce this issue, any details to reproduce?

(using the issue template is always recommended, we need know more information to reproduce a bug)

**Comment by aiamuzz** [comment]
more information ... 

a 3-4 day fresh ISO install of DeepinOS 15.10 updated to 15.10.2
dde-dock 2.0

and proof of the issue ... let me know if you want any logs to identity the issue in more detail ...

![deepin-screen-recorder_dde-desktop_20190716114409](https://user-images.githubusercontent.com/3283676/61270889-9eb91580-a7c0-11e9-96bb-d4329b570787.gif)

actually there is nothing really to reproduce ... i login on boot up ... the first workspace has the dock and the other 3 don't ... As i spend most time on my 3rd workspace ... i have to kill the dock to reload on workspace 3 ... and i work ...

**Comment by BLumia** [comment]
@justforlxz @zccrs any idea?

**Comment by aiamuzz** [comment]
@BLumia ... @justforlxz ... @zccrs ...

issue continues in 15.11 as well ...

**Comment by aiamuzz** [comment]
Doesn't seem to be a Dock issue ... but rather an issue with kwin ... the moment i change to DeepinWM the dock is visible on all workspaces ... hope this helps identify this issue i am facing !

Any idea what part of kwin is causing this ?

tryin to trouble shoot kwin I backed up my current kwinrc and restarted kwin which created a barebone default kwinrc file ... but the dock still shows only on one workspace only !!!

**Comment by aiamuzz** [comment]
@BLumia ... @zccrs ... @justforlxz ... 

anybody ... ?

**Comment by gchamon** [comment]
I described the same issue in another topic to @aiamuzz. Only a single dock present in the first workspace. A friend of mine with a similar installation (arch through anarchy distribution, vanilla deepin and Linux lts kernel) does not present the same issue.

So I took to my workspace at home. Installed deepin-kwin kwin-lowlatency and systemsettings and after reboot I get Dock on all workspaces.

I will try uninstalling everything on my notebook related to deepin, then I will install deepin and deepin extra groups, then I will install deepin-kwin (on arch, deepin comes with startdde which in turn installs deepin-wm). Will post results tomorrow

**Comment by aiamuzz** [comment]
@gchamon ... i am using a vanilla Linux Deepin installation ... but i face this issue ... i would appreciated any help in resolving this issue ...

**Comment by gchamon** [comment]
I pinpointed the offending file by creating a new user, with an empty home folder, and then comparing what files were missing in the new user's `.config` folder.

It turns out, in my case, deleting the file `$HOME/.config/kwinrulesrc` solves the problem of the dock only showing in one workspace. Unfortunately, I mistakenly deleted the file from both my `.config` and by backup folder, so I can't investigate further. Maybe you @aiamuzz could share your `.config/kwinrulesrc`.

But possible workaround:

`rm $USER/.config/kwinrulesrc`

Could you confirm this?

**Comment by aiamuzz** [comment]
@gchamon ... thanks for discovering the culprit ... you are right ... i just renamed the `kwinrulesrc` as a backup ... and on reboot the dock is back on all workspaces !!!

however i was hoping a new default `kwinrulesrc` file would be created ... and i could compare the new one and the backup one to see the problematic entry ... to my surprise there is no new default `kwinrulesrc` after reboot ... turns out that file may not really be needed ... or may be it was needed in the older Linux Deepin versions and when we upgraded that remnant file from the previous OS caused this issue 

Its such a travesty that we the users had to do this trial and error find the issue as a layman ... the Deepin Team could have resolved this in a jiffy ... well ... their responses aren't like before ...

**Comment by gchamon** [comment]
It is ok, it took a while to go over my `.config`, but that wasn't too much of a hassle. Considering the alternatives, Deepin is still by far the cleanest, most elegant DE, I only wish I could do more to improve this project

**Comment by aiamuzz** [comment]
@BLumia ... @hualet ... could you please tell us how this file `kwinrulesrc` was causing this problem ?

my guess is that file was an artefact of the older version of Linux deepin ... which the current version has no use for but caused a conflict nevertheless !

**Comment by gchamon** [comment]
I think two unrelated persons with the same issue, both able to circumvent the problem with the same procedure accounts for bug confirmation at least. If we were to document it somewhere so that other people running into the same issue could find the solution easily, I think it would be enough.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
