### ISSUE TITLE
[dde-file-manager] Deepin File Manager Segmentation fault in libdde-file-manager.so.1.3.0 

### ISSUE THREAD

**Issue by pierrechapelet** [linuxdeepin/developer-center#139]
Description: 

Deepin desktop was working like a charm. That's a very nice UI! Congrats to the developers !!!!!

After last upgrade on dde-file-manager (deepin-file-manager-1:1.3.6-1
) on arch linux , the right click on the desktop wallpaper creates a segfault: All Icons on the desktop disappear for few seconds and the reappear, context menu is not showing. Journald reports a segfault for dde-desktop in libdde-file-manager.so.1.3.0.
Note that clicking on any file folder on the desktop works well, with context menu showing.
Any idea how to fix that? issue with QT5?

Steps to reproduce:
Right click on the desktop wallpaper (Note that the right click context menu works fine on files/folder icons on the desktop)

Additional info:
* package version(s): deepin-file-manager-1:1.3.6-1, libdde-file-manager.so.1.3.0
* Here is the core dump:

Dec 31 10:53:49 cassiopeia kernel: dde-desktop[12024]: segfault at 400000019 ip 00007f4d618f32b4 sp 00007ffcef617fb0 error 4 in libdde-file-manager.so.1.3.0[7f4d61698000+3de000]
Dec 31 10:53:49 cassiopeia systemd[1]: Started Process Core Dump (PID 12339/UID 0).
Dec 31 10:53:50 cassiopeia systemd-coredump[12340]: Process 12024 (dde-desktop) of user 1000 dumped core.

Stack trace of thread 12024:
#0 0x00007f4d618f32b4 _ZN16DFileMenuManager18genereteMenuByKeysERK7QVectorIN9DFMGlobal10MenuActionEERK4QSetIS2_EbRK4QMapIS2_S3_Eb (libdde-file-manager.so.1)
#1 0x000000000041f348 n/a (dde-desktop)
#2 0x00000000004209e4 n/a (dde-desktop)
#3 0x00007f4d60fd79b8 _ZN7QWidget5eventEP6QEvent (libQt5Widgets.so.5)
#4 0x00007f4d610bfe1e _ZN6QFrame5eventEP6QEvent (libQt5Widgets.so.5)
#5 0x00007f4d611e6e83 _ZN17QAbstractItemView13viewportEventEP6QEvent (libQt5Widgets.so.5)
#6 0x00007f4d5fe26641 _ZN23QCoreApplicationPrivate29sendThroughObjectEventFiltersEP7QObjectP6QEvent (libQt5Core.so.5)
#7 0x00007f4d60f90335 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
#8 0x00007f4d60f98c10 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
#9 0x00007f4d5fe268e0 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
#10 0x00007f4d60ff220b n/a (libQt5Widgets.so.5)
#11 0x00007f4d60ff4ac3 n/a (libQt5Widgets.so.5)
#12 0x00007f4d60f9035c _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
#13 0x00007f4d60f97ad1 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
#14 0x00007f4d5fe268e0 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
#15 0x00007f4d605f7663 _ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE (libQt5Gui.so.5)
#16 0x00007f4d605f91e5 _ZN22QGuiApplicationPrivate24processWindowSystemEventEPN29QWindowSystemInterfacePrivate17WindowSystemEventE (libQt5Gui.so.5)
#17 0x00007f4d605d715b _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Gui.so.5)
#18 0x00007f4d465c6dc0 n/a (libQt5XcbQpa.so.5)
#19 0x00007f4d5c63a587 g_main_context_dispatch (libglib-2.0.so.0)
#20 0x00007f4d5c63a7f0 n/a (libglib-2.0.so.0)
#21 0x00007f4d5c63a89c g_main_context_iteration (libglib-2.0.so.0)
#22 0x00007f4d5fe7b2bf _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#23 0x00007f4d5fe24d3a _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#24 0x00007f4d5fe2d23c _ZN16QCoreApplication4execEv (libQt5Core.so.5)
#25 0x000000000041091a main (dde-desktop)
#26 0x00007f4d5f282291 __libc_start_main (libc.so.6)
#27 0x0000000000410e8a n/a (dde-desktop)

Stack trace of thread 12030:
#0 0x00007f4d5f34148d poll (libc.so.6)
#1 0x00007f4d5c63a786 n/a (libglib-2.0.so.0)
#2 0x00007f4d5c63a89c g_main_context_iteration (libglib-2.0.so.0)
#3 0x00007f4d5fe7b2bf _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4 0x00007f4d5fe24d3a _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5 0x00007f4d5fc47063 _ZN7QThread4execEv (libQt5Core.so.5)
#6 0x00007f4d5fc4bcf8 n/a (libQt5Core.so.5)
#7 0x00007f4d5c186454 start_thread (libpthread.so.0)
#8 0x00007f4d5f34a7df __clone (libc.so.6)

Stack trace of thread 12027:
#0 0x00007f4d5f34148d poll (libc.so.6)
#1 0x00007f4d5c63a786 n/a (libglib-2.0.so.0)
#2 0x00007f4d5c63a89c g_main_context_iteration (libglib-2.0.so.0)
#3 0x00007f4d3d97d4bd n/a (libdconfsettings.so)
#4 0x00007f4d5c6620d5 n/a (libglib-2.0.so.0)
#5 0x00007f4d5c186454 start_thread (libpthread.so.0)
#6 0x00007f4d5f34a7df __clone (libc.so.6)

Stack trace of thread 12026:
#0 0x00007f4d5f34148d poll (libc.so.6)
#1 0x00007f4d5c63a786 n/a (libglib-2.0.so.0)
#2 0x00007f4d5c63a89c g_main_context_iteration (libglib-2.0.so.0)
#3 0x00007f4d5fe7b2bf _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4 0x00007f4d5fe24d3a _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5 0x00007f4d5fc47063 _ZN7QThread4execEv (libQt5Core.so.5)
#6 0x00007f4d6028cde5 n/a (libQt5DBus.so.5)
#7 0x00007f4d5fc4bcf8 n/a (libQt5Core.so.5)
#8 0x00007f4d5c186454 start_thread (libpthread.so.0)
#9 0x00007f4d5f34a7df __clone (libc.so.6)

Stack trace of thread 12028:
#0 0x00007f4d5f34148d poll (libc.so.6)
#1 0x00007f4d5c63a786 n/a (libglib-2.0.so.0)
#2 0x00007f4d5c63a89c g_main_context_iteration (libglib-2.0.so.0)
#3 0x00007f4d5c63a8e1 n/a (libglib-2.0.so.0)
#4 0x00007f4d5c6620d5 n/a (libglib-2.0.so.0)
#5 0x00007f4d5c186454 start_thread (libpthread.so.0)
#6 0x00007f4d5f34a7df __clone (libc.so.6)

Stack trace of thread 12032:
#0 0x00007f4d5f34148d poll (libc.so.6)
#1 0x00007f4d5c63a786 n/a (libglib-2.0.so.0)
#2 0x00007f4d5c63a89c g_main_context_iteration (libglib-2.0.so.0)
#3 0x00007f4d5fe7b2bf _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4 0x00007f4d5fe24d3a _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5 0x00007f4d5fc47063 _ZN7QThread4execEv (libQt5Core.so.5)
#6 0x00007f4d5fc4bcf8 n/a (libQt5Core.so.5)
#7 0x00007f4d5c186454 start_thread (libpthread.so.0)
#8 0x00007f4d5f34a7df __clone (libc.so.6)

Stack trace of thread 12031:
#0 0x00007f4d5f34148d poll (libc.so.6)
#1 0x00007f4d5c63a786 n/a (libglib-2.0.so.0)
#2 0x00007f4d5c63a89c g_main_context_iteration (libglib-2.0.so.0)
#3 0x00007f4d5fe7b2bf _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4 0x00007f4d5fe24d3a _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5 0x00007f4d5fc47063 _ZN7QThread4execEv (libQt5Core.so.5)
#6 0x00007f4d5fc4bcf8 n/a (libQt5Core.so.5)
#7 0x00007f4d5c186454 start_thread (libpthread.so.0)
#8 0x00007f4d5f34a7df __clone (libc.so.6)

Stack trace of thread 12025:
#0 0x00007f4d5f34148d poll (libc.so.6)
#1 0x00007f4d5f0458e0 n/a (libxcb.so.1)
#2 0x00007f4d5f047679 xcb_wait_for_event (libxcb.so.1)
#3 0x00007f4d46590789 n/a (libQt5XcbQpa.so.5)
#4 0x00007f4d5fc4bcf8 n/a (libQt5Core.so.5)
#5 0x00007f4d5c186454 start_thread (libpthread.so.0)
#6 0x00007f4d5f34a7df __clone (libc.so.6)

Stack trace of thread 12029:
#0 0x00007f4d5f34148d poll (libc.so.6)
#1 0x00007f4d5c63a786 n/a (libglib-2.0.so.0)
#2 0x00007f4d5c63ab12 g_main_loop_run (libglib-2.0.so.0)
#3 0x00007f4d5cc20316 n/a (libgio-2.0.so.0)
#4 0x00007f4d5c6620d5 n/a (libglib-2.0.so.0)
#5 0x00007f4d5c186454 start_thread (libpthread.so.0)
#6 0x00007f4d5f34a7df __clone (libc.so.6)
Dec 31 10:53:54 cassiopeia dbus-daemon[2034]: Activating service name='com.deepin.dde.desktop'
Dec 31 10:53:54 cassiopeia dbus-daemon[2034]: Successfully activated service 'com.deepin.dde.desktop'
Dec 31 10:53:54 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:54.696[Debug][main 48 0x2233f90 ] start "dde-desktop" "5cf7b65c53b2a6366c242e6a5194bd6eace1e5be"
Dec 31 10:53:54 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:54.852[Debug][CanvasGridView::initUI 1098 0x2233f90 ] qApp->primaryScreen() QScreen(0x2238660, name="LVDS-1")
Dec 31 10:53:54 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:54.852[Debug][CanvasGridView::initUI 1099 0x2233f90 ] qApp->primaryScreen()->availableGeometry() QRect(0,0 1440x900)
Dec 31 10:53:54 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:54.941[Warning][ 0 0x2233f90 ] QWidget::setMinimumSize: (/QLabel) Negative sizes (-1,-1) are not possible
Dec 31 10:53:54 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:54.942[Debug][Config::Config 35 0x2233f90 ] "/home/pierre/.config/deepin/dde-desktop/dde-desktop.conf"
Dec 31 10:53:54 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:54.942[Warning][Dtk::Widget::DApplicationPrivate::loadTranslator 141 0x2233f90 ] "dtkwidget" can not find qm files
Dec 31 10:53:54 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:54.942[Warning][Dtk::Widget::DApplicationPrivate::loadTranslator 141 0x2233f90 ] "dde-desktop" can not find qm files
Dec 31 10:53:54 cassiopeia com.deepin.dde.desktop[2034]: QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed: No such file or directory
Dec 31 10:53:54 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:54.948[Debug][PluginManager::loadPlugin 38 0x2233f90 ] "/usr/lib/dde-file-manager/plugins"
Dec 31 10:53:54 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:54.949[Debug][PluginManager::loadPlugin 42 0x2233f90 ] load plugin in: "/usr/lib/dde-file-manager/plugins/menu"
Dec 31 10:53:54 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:54.949[Debug][PluginManager::loadPlugin 42 0x2233f90 ] load plugin in: "/usr/lib/dde-file-manager/plugins/view"
Dec 31 10:53:54 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:54.949[Debug][PluginManager::loadPlugin 64 0x2233f90 ] menu plugin size: 0
Dec 31 10:53:54 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:54.949[Debug][PluginManager::loadPlugin 65 0x2233f90 ] expand info size: 0
Dec 31 10:53:54 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:54.949[Debug][PluginManager::loadPlugin 38 0x2233f90 ] "/usr/lib/dde-file-manager/plugins"
Dec 31 10:53:54 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:54.949[Debug][PluginManager::loadPlugin 42 0x2233f90 ] load plugin in: "/usr/lib/dde-file-manager/plugins/menu"
Dec 31 10:53:54 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:54.949[Debug][PluginManager::loadPlugin 42 0x2233f90 ] load plugin in: "/usr/lib/dde-file-manager/plugins/view"
Dec 31 10:53:54 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:54.950[Debug][PluginManager::loadPlugin 64 0x2233f90 ] menu plugin size: 0
Dec 31 10:53:54 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:54.950[Debug][PluginManager::loadPlugin 65 0x2233f90 ] expand info size: 0
Dec 31 10:53:54 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:54.952[Warning][ 0 0x2233f90 ] inotify_add_watch("/usr/local/share/applications/)") failed: "No such file or directory"
Dec 31 10:53:54 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:54.953[Warning][ 0 0x2233f90 ] inotify_add_watch("/usr/share/gnome/applications/") failed: "No such file or directory"
Dec 31 10:53:55 cassiopeia daemon/watchdog[2030]: manager.go:76: Launch 'dde-desktop' failed: org.freedesktop.DBus.Error.UnknownInterface:No such interface 'com.deepin.dde.Desktop' at object path '/com/deepin/dde/desktop'
Dec 31 10:53:55 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:55.038[Debug][CanvasGridView::initConnection::lambda 1230 0x2233f90 ] init GridManager cells
Dec 31 10:53:55 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:55.955[Debug][MimesAppsManager::getMimeTypeApps 342 0x23fca10 ] getMimeTypeApps in QThread(0x23fca10) QThread(0x2233f90)
Dec 31 10:53:56 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:56.492[Warning][ 0 0x23fca10 ] link g5692 hasn't been detected!
Dec 31 10:53:56 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:56.496[Warning][ 0 0x23fca10 ] link g5692 hasn't been detected!
Dec 31 10:53:56 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:56.496[Warning][ 0 0x23fca10 ] link g5692 hasn't been detected!
Dec 31 10:53:56 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:56.496[Warning][ 0 0x23fca10 ] link g5692 hasn't been detected!
Dec 31 10:53:56 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:56.496[Warning][ 0 0x23fca10 ] link g5692 hasn't been detected!
Dec 31 10:53:56 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:56.498[Warning][ 0 0x23fca10 ] Could not resolve property : radialGradient4319
Dec 31 10:53:56 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:56.504[Warning][ 0 0x23fca10 ] link g5692 hasn't been detected!
Dec 31 10:53:56 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:56.507[Warning][ 0 0x23fca10 ] link g5692 hasn't been detected!
Dec 31 10:53:56 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:56.507[Warning][ 0 0x23fca10 ] link g5692 hasn't been detected!
Dec 31 10:53:56 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:56.507[Warning][ 0 0x23fca10 ] link g5692 hasn't been detected!
Dec 31 10:53:56 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:56.508[Warning][ 0 0x23fca10 ] link g5692 hasn't been detected!
Dec 31 10:53:56 cassiopeia com.deepin.dde.desktop[2034]: 20161231.10:53:56.509[Warning][ 0 0x23fca10 ] Could not resolve property : radialGradient4319

**Comment by avently** [comment]
I also had this problem. I thought I made a mistake in system files and reinstalled Manjaro. But this does not help. Latest package of Deepin Desktop seems broken. 
I build from source and problem is gone. 
Guys, please, remove Deepin file manager from dependencies. Desktop works great without it. I prefer Nautilus because your file manager doesn't have all Nautilus' features. With Deepin file manager I can't select Nautilus as a default manager

**Comment by felixonmars** [comment]
The OP's issue has been fixed in deepin-desktop 4.0.0-3.

@avently /usr/bin/dde-desktop links to libdde-file-manager.so, it won't even start without dde-file-manager installed.

**Comment by avently** [comment]
@felixonmars it can not start without libdde-file-manager.so but can start without usr/bin/dde-file-manager. Deep in desktop <4.0 can start even without lib...

**Comment by felixonmars** [comment]
That's an upstream decision and we don't split packages for this.

**Comment by pierrechapelet** [comment]
This is to confirm that my issue was  solved after upgrading to deepin-desktop 4.0.0-3.
Many thanks for the follow-up!
