### ISSUE TITLE
Window Tiling ... state to ... restore window size ... not working !!!

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1390]
Hi,

I have freshly installed DeepinOS 15.10.2 and have been testing stuff one by one ... 

I have come across this issue which wasn't the case in the last DeepinOS versions(unstable) ...

I have configured a shortcut to tile windows to the left or right ... and i have also configured a shortcut to restore the window from a maximized state ...

Earlier when i tiled the window to either side ... hitting the shortcut to restore the windows used to bring the window from the tiled state to a size and position of the window i have preset for a given application. This however isn't happening currently ...

Hope to see this functionality restored soon.

Cheers.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
