### ISSUE TITLE
希望能显示/home分区大小

### ISSUE THREAD

**Issue by htqx** [linuxdeepin/developer-center#1392]
## 缺陷描述
不知道什么原因，deepin默认并没有列出/home分区的大小，而只是列出了根分区的大小，并不清楚这样做的理由，倒是会让人疑问：怎么我新装的系统不见了几十G空间？

## 复现步骤
1. 打开文件管理器
2. 点计算机，只是显示/分区大小，和原先的windows分区，并没有/home分区

## 期望行为
希望能列出/home分区大小

## 截图
![image](https://user-images.githubusercontent.com/42466118/61202273-a5d91880-a719-11e9-9be7-ae5c452ff415.png)
![image](https://user-images.githubusercontent.com/42466118/61202457-23048d80-a71a-11e9-89bc-9cc6e5bbf931.png)

## 复现环境:
15.10.2
### 发行版以及版本
deepin 15.10.2

### 相关的软件包版本
dde-file-manager

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/developer-center/issues/545 cc @wangjia12

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
