### ISSUE TITLE
BUG ? ... "Always on Visible Workspace" setting implementation in Workspace view ... Issue 2/2

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1393]
Hi,

I have freshly installed DeepinOS 15.10.2 and have been testing stuff one by one ...

**Issue 2**
When i enable this settings with the mouse ... i can see that its implementation is a little off ... the following screen recorder should give you an idea of what i mean be its implementation being off ...

![deepin-screen-recorder_google-chrome_20190715131521](https://user-images.githubusercontent.com/3283676/61201615-b4680580-a702-11e9-85b8-d334e0b0b0b4.gif)

turns out enabling this option is placing this window on all the workspaces increasing unnecessary clutter !!!

might need to be restored to the pre 15.10 stable state ... where it should just move the window to the active workspace rather than placing it on all workspaces.

Cheers.

**Comment by aiamuzz** [comment]
> That's what "Always on Visible Workspace" means (so it's not a bug). If you just would like to move the window to another workspace, use the move to left/right workspace menu, or drag the window to the new workspace in your Meta+S view.

@BLumia ...

Well if its not a bug then ...

1. Its not elegant ... looks rather crude implementation(not to the high standard of Deepin UI/UX) ... this only increases the clutter on the workspace view ...

2. It wasn't the case with the deepin-wm ... the implementation there was far more elegant and classy ... so if you elegant and classy is something you wish to return then i guess another feature option requires optimization on kwin ... You wan't

**Comment by keybreak** [comment]
@aiamuzz 
While i agree with a lot what you say, and also see same bugs, please try to be as short and on point in your reports, like that for example https://github.com/linuxdeepin/developer-center/issues/1377

I bet it's really hard to read your titles and track such freely organized reports later :wink:
That way we all have more chances to get things solved faster :smile

**Comment by aiamuzz** [comment]
> @aiamuzz
> While i agree with a lot what you say, and also see same bugs, please try to be as short and on point as it possible in your reports, like that for example #1377
> 
> I bet for devs it's really hard to read your titles and track such freely organized reports later 
> That way we all have more chances to get things solved faster

@keybreak ...

I try to follow that form when i am reporting a bug that i encounter in the middle ... like after an update suddenly it stopped working as intended or ... or say i came across the bug very late after the last update ...

but when i report bugs/issues on an OS level i report it in this fashion saving the trouble of mentioning the environment which is very cumbersome having to go to the terminal each time to grab a version of a particular application ... I agree the way you report is pretty organized and neat ... but i guess i don't have that much time to organize and report ... if that is sought as a mandatory item then i guess i might just skip the reporting of the bug altogether ...

its all about time you see ... and the state of mind i am in ... 

thanks for the pointer though ... :smile: 

As you can see my state of mind with regarding to reporting the issues is clearly evident considering the number of issues i have reported ... all this will i was pretty pissed of with the whole Deepin having switched from deepin wm to kwin ... my state of mind has since improved firstly because i see progress on kwin's gradual addition of features and having factored the team's situation of being severely short staffed !!!

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
