### ISSUE TITLE
Bug : Top-right corner Close Button issue 2/2 ... mere mouse over the top-right hot corner is closing maximized windows ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1394]
Hi,

I have freshly installed DeepinOS 15.10.2 and have been testing stuff one by one ...

As you can see in the following screen recording ... the top-right hot corner which is configured to close a window when one one clicks on the orange close button animation is actually closing windows without even clicking ... just moving the mouse cursor to the top-right  hot corner is closing windows that are in the maximized state ...

![deepin-screen-recorder_google-chrome_20190715152514](https://user-images.githubusercontent.com/3283676/61208362-dff3eb80-a714-11e9-8986-d7ce12fdc849.gif)

as you can see i opened a new chrome window and a file manager window in their un-maximized state the top-right hot corner didn't close the windows but the same window when it was maximized ... mere moving the mouse cursor in that corner closed those windows ...

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
