### ISSUE TITLE
Bug : Top-right corner Close Button. the orange 'x' marked button is not showing ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1395]
Hi,

I have freshly installed DeepinOS 15.10.2 and have been testing stuff one by one ...

As you can see in the following screen recording the orange 'x' marked 'Close Button' is not showing on the top-right hot corner ...

![deepin-screen-recorder_google-chrome_20190715152125](https://user-images.githubusercontent.com/3283676/61208104-44627b00-a714-11e9-9e8c-50330bd001a5.gif)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
