### ISSUE TITLE
No of Workspaces capped to 4 ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1396]
Hi,

After i freshly installed the DeepinOS ISO recently and ran the  `15.10.2` update i noticed somewhere in the update description that the no. of workspaces will be capped at 4 ... Is this true ?

**I am wondering what is the rationale behind this move ... are workspaces more than 4 causing issues that are difficult to handle / maintain for the team ?** ... If one had sufficiently decked up hardware RAM and processing speed ... i thing the user should have the freedom !!!

I mean just today when i was introduced to the 'SystemSettings' package for kwin, i saw in one of the settings windows & it had a listing of workspaces all the way to 20 for setting up shortcuts ... Yes we do know practically speaking nobody will realistically use 20 workspaces, but the fact that there is NO cap to it, is a positive thing, it is freedom to the users, who can exercise discretion(based on their hardware) and most importantly it means that kwin was designed to handle a large number of workspaces and the discretion ended in the hands of the user !!!

And this sudden and regressive step of capping it to 4 is not a step in the right direction ... i myself am missing a 5th workspace given my workflow ... but due to this regressive capping ... i am forced to write this post !!!

Deepin team could always state in their specifications just like they state the specs for hardware that will run the OS in an optimum manner ... they could state somewhere in the UI(like when a user tries to create a 5th workspace you could put out an 'info bubble' stating why its not optimum to have additional workspaces given the RAM they might have ... for eg. I have 16 GB RAM so i do not have any hardware bottlenecks so i could be allowed more than 4 upto whatever number my hardware will allow to run the setup with the least issues ... its a very baaad idea to withdraw something that was already available ... letting user decide and respecting his workflow is good practice and principle to operate out of.

And if capping is imminent and will still be forced upon the user(given kwin users have the freedom on other distro's), then i guess you might want to consider a higher number than just 4 workspaces ... may be the highest single digit number ... 9 ... this way at least we will have the option of setting shortcuts to navigate to the workspaces with the shortcut combination of "Meta+1/2/3/4/5/6/7/8/9"

PS : Instead of forcing a complete block on the number of workspaces to 4 ... a softer move would be to at least allow more than 4 workspaces with a under the hood hack ... that way the geeky users can be happy hacking their way into more than 4 workspaces according to their hardware setup and workflow and the non-geeky can be hoped to be happy with the capped no. which come out of the box as a default.

**Comment by brunobmello25** [comment]
Did you figure out a solution or at least a reason for this? I am currently using DeepinOS 15.11 and already tried changing both **com.deepin.wrap.gnome.desktop.wm.preferences.num-workspaces** and **org.gnome.desktop.wm.preferences.num-workspaces** to 16 on dconf-editor but I still can't create more than four workspaces.

**Comment by meiyixiang** [comment]
Thank you for suggesting workspaces, currently you can only create a maximum of 4 workspaces. I have documented your suggestion and will consider the geek user's request for more workspaces.

**Comment by meiyixiang** [comment]
24/5000 
Later consideration will increase the number of workspaces, but there will still be a limiting mechanism.
