### ISSUE TITLE
Workspace View shows the same wallpaper across all workspace previews ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1398]
Hi,

I have freshly installed DeepinOS 15.10.2 and have been testing stuff one by one ...

As you can see in the following screen recording ... the Workspace View shows all workspaces as having the same wallpaper when in fact all four have different wallpaper ...

Further i have tried to demonstrate a certain method to this madness ... the workspace from which the workspace view shortcut is invoked is the wallpaper of that workspace that show across all the workspace in the workspace view. In the following recording i have tried to invoke this view from all 4 workspaces and as you can see the wallpaper of that workspace is plastered on to all four workspace view previews.

![deepin-screen-recorder_google-chrome_20190716012918](https://user-images.githubusercontent.com/3283676/61245343-e6608280-a769-11e9-863c-f59160fdaf41.gif)

I guess this would be a WIP as part of the transition from DeepinWM to KWIN ... DeepinWM was very elegant in all its implementation ... it would show the respective wallpapers of the workspaces in the workspace view preview thumbnails.

Hope to see that elegance implemented in Kwin as we progress ...

Cheers.

**Comment by BLumia** [comment]
It's known issue and will be fixed in future dde-kwin updates.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
