### ISSUE TITLE
deepin-wm eats too much RAM

### ISSUE THREAD

**Issue by avently** [linuxdeepin/developer-center#140]
After one hour after reboot system uses 1.5 GB of RAM. I closed all my apps except geary and made a screenshot. Take a look.
As you can see deepin-wm has two much memory (915 MB). If i just closes it memory looks better - 897MB used (~200 MB for deepin-wm).
![screenshot](https://cloud.githubusercontent.com/assets/7953703/21736110/5bbac4a2-d47f-11e6-8264-9a92cf66b0ed.png)
Can you fix it? Because 4 GB is not a good choice for Manjaro Deepin...
I use Manjaro Deepin 16.10.3 and default kernel. Also i tried to limit number of desktops via this property - com.deepin.wrap.gnome.desktop.wm.preferences num-workspaces 2   - but looks like it can not help with RAM issue.

**Comment by sonald** [comment]
I never experience any memory problem. after several days of using (without logout), the memory usage is predicable and reasonable. this may be caused by some corner case. paste your xrandr output. what is your video card ?

**Comment by avently** [comment]
`Screen 0: minimum 8 x 8, current 1600 x 900, maximum 16384 x 16384
VGA-0 disconnected (normal left inverted right x axis y axis)
LVDS-0 connected primary 1600x900+0+0 (normal left inverted right x axis y axis) 382mm x 215mm
   1600x900      59.98*+
HDMI-0 disconnected (normal left inverted right x axis y axis)
`
Nvidea 410M

**Comment by avently** [comment]
I closed all other windows and here is the result. I should kill this application tens times in a day.

![screenshot](https://cloud.githubusercontent.com/assets/7953703/21841979/bbbaa038-d7f5-11e6-9a36-135bf494022c.png)

**Comment by avently** [comment]
can someone answer me what can i do? How can i help you to fix this issue? Maybe you already did or find a fix?

**Comment by sonald** [comment]
Can you try to run deepin-wm with valgrind to locate the memory leak ? I never receive such huge memleak before? how many windows did you open ?

**Comment by avently** [comment]
i can run it, but please tell what command i should run.
This is a log for valgrind --leak-check=full deepin-wm --replace
[valgrind.txt](https://github.com/linuxdeepin/developer-center/files/707609/valgrind.txt)

**Comment by sonald** [comment]
Sorry, I forgot to mention that for this to work, you should first kill deepin-wm-switcher by `kill `deepin-wm-switcher`, and then run `valgrind --tool=memcheck deepin-wm --replace`

**Comment by avently** [comment]
This is the results.
[valgrind.txt](https://github.com/linuxdeepin/developer-center/files/708064/valgrind.txt)

**Comment by sonald** [comment]
I can not found any special info. the most probable leak source is from your nvidia proprietary driver.

**Comment by avently** [comment]
OK, I will install open source driver and will post a new information

**Comment by avently** [comment]
Oh, you are right. I removed Nvidia driver, then rebooted. I started 10 apps (Android Studio, Chromium and Gitkraken included) + 3 daemons. Only 3 GB of RAM is used (1.9 GB without Android Studio). Deepin-wm use <80 MB (~50 MB after restart). Its awesome. Thank you, @sonald !
So, as i understand, i can not use Nvidia driver... Or can i use Nvidia driver only for games and Nouveau for everything else? Is it real?

**Comment by felixonmars** [comment]
You may try some legacy branch of the driver, like 340xx. I never experienced this problem with the latest nvidia driver, though :/

**Comment by avently** [comment]
oh, i have news.
I tried to use mutter (not deepin-wm) and it does not leak so much memory. I think it uses with nvidia driver as much memory as deepin-wm with nouveau. i also tried more wm managers and its does not leak. 
And one more thing. Background stays the same after waking up from sleep (no corruption). 
What do you think about it? Can i somehow help you to find a peace of code that works bad in this situation?
P.S. Replace deepin-wm with mutter is not an option.
![mutter](https://cloud.githubusercontent.com/assets/7953703/22395938/75db8062-e55d-11e6-95c5-0d2a3f16e988.png)

**Comment by aedancullen** [comment]
The same problem still exists in DDE 15.5.1 with the latest NVIDIA driver 396 on newer GPUs. On Lenovo ThinkPad P50 (Quadro M1000M), this occurs with BIOS set to discrete-only graphics mode.

I can confirm that switching wallpapers consistently increases `deepin-wm` RAM usage. It should be interesting to see if the same memory leak exists on desktop systems, or if it is somehow specific to Optimus laptops running in discrete-only mode (which I assume was @avently's configuration). Possibly it is related to `deepin-wm` not playing nicely with the driver's GL libraries?

**Comment by aedancullen** [comment]
Actually, a similar thing is occurring even with no NVIDIA driver on the system at all (only i915, with Intel graphics running). Repeatedly opening and closing large numbers of workspaces in Multitasking Mode causes memory to leak, although possibly at a slower rate than with NVIDIA. After opening/closing maybe about 30-40 workspaces, `deepin-wm` is already larger than 200MB.

**Comment by sonald** [comment]
valgrind indicates the leak may reside into cogl layer. that is hard to debug and fix.
