### ISSUE TITLE
Add global menu on DDE, please

### ISSUE THREAD

**Issue by mathpfvr** [linuxdeepin/developer-center#1400]
Please, add global menu on DDE for Deepin.

**Comment by BLumia** [comment]
There are no plan about add a global menu if you means a mac-like menu (also there are no plan to add official support of topbar, you may want to use a 3rd-party one).

**Comment by MaximKiselev** [comment]
> There are no plan about add a global menu if you means a mac-like menu (also there are no plan to add official support of topbar, you may want to use a 3rd-party one).
hi, why you said mac-like menu... add only as i3... coders like tags, menu,window, and custom plugin on vala/python or lua...
de must be full... if u want not have gnome with 100 tweakers....tweaker will be broke system
if u will not plan to create universal api to easy integration into deepin ecosystem.

**Comment by BLumia** [comment]
> > There are no plan about add a global menu if you means a mac-like menu (also there are no plan to add official support of topbar, you may want to use a 3rd-party one).
> 
> hi, why you said mac-like menu... add only as i3/polybar... coders like tags, menu,window, and custom plugin on vala/python or lua...
> de must be full... if u want not have gnome with 100 tweakers....tweaker will be broke system
> if u will not plan to create universal api to easy integration into deepin ecosystem.

So maybe we should define the word `global menu` first. This issue thread seems too casual with just a title and a one line description, no one knows what does the "global menu" means exactly.

If you would like to request some features, feel free to open another issue with more details and then Deepin or other 3rd-party developer from the community may help to make it happens :)
