### ISSUE TITLE
Transparent Dock

### ISSUE THREAD

**Issue by SPFxDeveloper** [linuxdeepin/developer-center#1404]
Hi.

Use Deepin Desktop 15.10.2, I have the Dock configured to hide and show automatically, however, I have the following problem:

After about 20 minutes of working with Audacity. By minimizing Audacity and reappearing the Dock it remains transparent, only the Dock box is displayed, but in a transparent way, it does not show the icons of the applications and if you click it, it does not take any action.

NOTE: I'm currently looking to migrate to Linux, but I'm still working on Windows 10. While Deepin virtualized it with Hyper-V and assigned it 4 processors and 8Gb of RAM. My PC is HP EliteBook 840 G4 with 16GB of RAM.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
