### ISSUE TITLE
文件管理器和编辑器的设置界面切换选项卡导致背景透明

### ISSUE THREAD

**Issue by codexvn** [linuxdeepin/developer-center#1405]
## 缺陷描述
打开文件管理器或编辑器的设置界面后切换选项卡会出现部分背景变得透明

## 复现步骤
打开文件管理器或编辑器的设置界面后开始切换选项卡
多次切换之后部分背景变得透明
## 期望行为
文件管理器或编辑器正常使用

## 截图
![深度截图_dde-desktop_20190716124514](https://user-images.githubusercontent.com/24852067/61266847-4423b780-a7c8-11e9-84fc-140b4237e93e.png)
![深度截图_dde-desktop_20190716124605](https://user-images.githubusercontent.com/24852067/61266849-44bc4e00-a7c8-11e9-95e5-c17db4858c49.png)

## 复现环境:
OS: Arch Linux 
Kernel: x86_64 Linux 5.2.0-arch2-1-ARCH
Resolution: 1920x1080
DE: Deepin 15.11
WM: Deepin WM
WM Theme: deepin
Icon Theme: deepin

### 相关的软件包版本
deepin-file-manager 1:4.8.6.4-3
deepin-editor 1.2.6.4-1

**Comment by BLumia** [comment]
手头有别的事情暂时没尝试切换窗管重现，请问如果尝试安装并使用 deepin-kwin 还会出现这个问题吗？

**Comment by codexvn** [comment]
> 手头有别的事情暂时没尝试切换窗管重现，请问如果尝试安装并使用 deepin-kwin 还会出现这个问题吗？
![Uploading 深度截图_dde-desktop_20190716130832.png…]()
![Uploading 深度截图_dde-desktop_20190716130927.png…]()

安装deepin-kwin 0.0.11.1-1之后注销重新登录问题依然存在

**Comment by codexvn** [comment]
> 手头有别的事情暂时没尝试切换窗管重现，请问如果尝试安装并使用 deepin-kwin 还会出现这个问题吗？

安装deepin-kwin 0.0.11.1-1之后注销重新登录问题依然存在
![深度截图_dde-desktop_20190716130832](https://user-images.githubusercontent.com/24852067/61267705-7be02e80-a7cb-11e9-9f91-acad8c8f42bc.png)
![深度截图_dde-desktop_20190716130927](https://user-images.githubusercontent.com/24852067/61267707-7be02e80-a7cb-11e9-8e74-a95418d8a9d8.png)

**Comment by BLumia** [comment]
在同事的电脑测试也没复现，可以考虑装一个 `systemsettings5` 然后调一下 Rendering backend 看看效果？

**Comment by codexvn** [comment]
> 在同事的电脑测试也没复现，可以考虑装一个`systemsettings5`然后调一下渲染后端看看效果？
装deepin-kwin之后，使用谷歌浏览器滚动页面的时候会出现画面撕裂，随后我通过systemsettings调Rendering backend可以解决画面撕裂的问题，但是背景变透明的问题依然存在。
有没有可能和我设置的1.25放大有关？

**Comment by codexvn** [comment]
> 在同事的电脑测试也没复现，可以考虑装一个 `systemsettings5` 然后调一下 Rendering backend 看看效果？

装deepin-kwin之后，使用谷歌浏览器滚动页面的时候会出现画面撕裂，随后我通过systemsettings调Rendering backend可以解决画面撕裂的问题，但是背景变透明的问题依然存在。
有没有可能和我设置的1.25放大有关？

**Comment by BLumia** [comment]
我这边缩放也没复现，暂时不太清楚情况。目前关注一下这个问题吧，找到复现方式一定会处理。

感谢反馈～

**Comment by codexvn** [comment]
1.0倍缩放问题消失，1.25就会复现，应该是屏幕缩放的锅了。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
