### ISSUE TITLE
深度文件编辑器打开单行不大的普通的大文本文件很慢

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1408]
## 缺陷描述

我有时要读一些比较大的文本文件（几兆以上），发现用深度文件编辑器打开这种文本文件很慢，我觉得需要改进。下面是一个单行不大的普通的文本文件，用gedit和pluma都是秒开，而深度文件编辑器要很久才能打开这个文件。需改进。
[a.txt](https://github.com/linuxdeepin/developer-center/files/3396345/a.txt)

## 期望行为

秒开大普通文本文件

### 发行版以及版本

deepin15.10.2 deepin-editor1.2.9

**Comment by widon1104** [comment]
#1335和#1408不是同一个问题吧，#1335是文件单行很大，根本打不开，#1408是文件单行不大，但是打开很慢

**Comment by BLumia** [comment]
源头上是同一个问题。本来是都可以挺快的，最初是项目缘故在触屏支持和打开速度之间权衡选了触屏支持较好的方案，revert 某个提交（ https://cr.deepin.io/#/c/deepin-editor/+/41268/ ）是可以解决打开速度上的问题的（当然，因为代码没打算并入所以没有严格进行测试）。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
