### ISSUE TITLE
解决蜂鸣器（pc speeker）的问题

### ISSUE THREAD

**Issue by duanyao** [linuxdeepin/developer-center#1409]
## 缺陷描述
目前 deepin 中很多应用程序会让蜂鸣器会发声，除了终端，还有 nautilus，另外有用户报告 Tim 也会： https://bbs.deepin.org/forum.php?mod=viewthread&tid=180676

我认为蜂鸣器给普通用户带来的困扰大于帮助，这是因为随着蜂鸣器的应用越来越少，很多新用户对其不了解，甚至不知道有这个东西，他们可能试图用关闭“系统音效”的方式去关闭蜂鸣声，然后发现是徒劳的（上面的链接）。我猜想，很多用户也会对静音、音量调节、耳机插入等对蜂鸣声无效感到困扰。

## 复现步骤
略

## 期望行为
我认为可以有几个选项：

1. 系统默认禁用蜂鸣器，将 pcspkr 和 snd_pcsp 内核模块加入黑名单。

2. 让“系统音效”和“静音”设置也对蜂鸣器生效。

3. 增加专门开关蜂鸣器的设置。

我倾向于 1，简单直接。现代的应用程序不应该再依赖蜂鸣器了。让各个应用程序自己设置是否使用蜂鸣器并不是好的解决方式，我们还是需要一个全局设置。

## 复现环境:
deepin 15.10.2

### 发行版以及版本
deepin 15.10.2

**Comment by keybreak** [comment]
1 option! :+1:

**Comment by BLumia** [comment]
终端的嗡鸣器声音问题应该在上次还是上上次来着的更新中修复了，不过这个问题是由于仓库换到 debian stretch （实质降级）导致的，应该到 buster 就不再存在了。不过仓库升级估计还得一段时间。

**Comment by duanyao** [comment]
@BLumia 并不只是终端的问题，如前所述 nautilus 和 tim 等也会触发蜂鸣，这些也会随着升级到 buster 解决吗？

**Comment by BLumia** [comment]
> @BLumia 并不只是终端的问题，如前所述 nautilus 和 tim 等也会触发蜂鸣，这些也会随着升级到 buster 解决吗？

我知道不只是终端有这个问题，终端在仓库迁移 stretch 的时候代码也是一行没变，后续终端的修复是额外加了个默认配置禁用了嗡鸣器声音。

这个 issue 先留着，如果 buster 仓库迁移完了还有问题那还是要处理的（

**Comment by meiyixiang** [comment]
谢谢你的建议这个问题，我记录了。
