### ISSUE TITLE
dde-desktop does not start

### ISSUE THREAD

**Issue by psykotik1** [linuxdeepin/developer-center#141]
after using xinit to start dde, i am left with no wallpaper and i cant click on the desktop (no menu). journalctl shows this: dbus-daemon[775]: Activated service 'com.deepin.dde.desktop' failed: Process com.deepin.dde.desktop received signal 6

when i start dde-desktop from the terminal i still get no wallpaper and no right click menu

**Comment by hualet** [comment]
@sonald @Iceyer

**Comment by sonald** [comment]
@psykotik1 wallpaper is rendered by window manager (deepin-wm or deepin-metacity), which should be started by startdde. It seems that dde-desktop and dde-session-daemon have problem to launch. what is in your .xinitrc file?

**Comment by psykotik1** [comment]
exec startdde

**Comment by psykotik1** [comment]
update: after deepin-desktop update, wallpaper shows and right click menu works
