### ISSUE TITLE
Remove the big title bar on non deepin apps

### ISSUE THREAD

**Issue by tnaffh** [linuxdeepin/developer-center#1412]
Is it possible to get rid of the ugly **Window Title bar** on non deepin apps and move the app title with the window action buttons (minimize,maximize,close), more like how it is on macOS and deepin default apps like File Manager?

Currently the title bar on top off all non deepin apps look really ugly and space consuming especially n small screens.

See image bellow for what I am talking about.

![DeepinScreenshot_select-area_20190718084159](https://user-images.githubusercontent.com/9331942/61435777-96381a80-a939-11e9-86b6-f80bb74e0365.png)

**Comment by BLumia** [comment]
Duplicated with https://github.com/linuxdeepin/developer-center/issues/1210 , and see https://github.com/linuxdeepin/developer-center/issues/1210#issuecomment-508703525 for a workaround.

**Comment by gitQqqHs** [comment]
什么都不说了,这个标题栏真的够丑了

**Comment by Xeunyx-Cypher** [comment]
found any proper solution yet? JUST installed deepin 20.7 today and its giving me a headache

**Comment by Decodetalkers** [comment]
> found any proper solution yet? JUST installed deepin 20.7 today and its giving me a headache

See https://github.com/linuxdeepin/developer-center/issues/1210
