### ISSUE TITLE
Qt: setShortcut(QKeySequence::FullScreen) 类似快捷键不触发

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#1413]
QPushButton->setShortcut(QKeySequence::FullScreen);
F11, Ctrl+Shift+F, Ctrl+F11 都无效

**Comment by BLumia** [comment]
能够复现，并且之前尝试过字符串形式构建的快捷键序列，三个组合键的快捷键也会失效。

不过上次我测试发现 debian buster 没有这个问题，等仓库升级完我再测试一下。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
