### ISSUE TITLE
Deepin file manager | DVD-ROM drive invisible icon

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#1414]
## Describe the bug
- Deepin 15.11
- Deepin file manager - Dark theme
- DVD-ROM drive - invisible icon.

@BLumia

**Comment by BLumia** [comment]
Could you provide a screenshot for this issue (is it on the sidebar or on the Computer view) and the dde-file-manager version? Thanks!

**Comment by keybreak** [comment]
Sure.
Yes sidebar, for all Deepin distros current up to date versions (deepin-file-manager 1:4.8.8.1-1)

Here's normal:
![image](https://user-images.githubusercontent.com/47599989/61581287-0060e300-ab25-11e9-97db-6a267f5b76ec.png)

Here's dark:
![image](https://user-images.githubusercontent.com/47599989/61581291-0b1b7800-ab25-11e9-93b0-6a5e3bf58475.png)

Obviously just same variant of icon is used as for light theme.

____

Also i must note that for every new recent feature there was design mistakes or unfinished states, especially with icons (and non of them are still fixed):
https://github.com/linuxdeepin/developer-center/issues/991
https://github.com/linuxdeepin/developer-center/issues/899 (issue 2.1)
https://github.com/linuxdeepin/developer-center/issues/913

As well as small but noticeable stuff like this:
https://github.com/linuxdeepin/developer-center/issues/941
https://github.com/linuxdeepin/developer-center/issues/1013
https://github.com/linuxdeepin/developer-center/issues/1344

Please be more careful and test all changes of design live (new function which requires icons obviously must be tested with light / dark themes). :+1:

**Comment by aiamuzz** [comment]
@BLumia ...
I am assuming this DVD burning option introduced newly with 15.11 into the Deepin File Manager will be accessible(can be tested) only if we have a DVD drive, isn't it ?

**Comment by BLumia** [comment]
Seems the qss icon doesn't matched, cc @chirs241097 

> I am assuming this DVD burning option introduced newly with 15.11 into the Deepin File Manager will be accessible(can be tested) only if we have a DVD drive, isn't it ?

Yes it is.

**Comment by chirs241097** [comment]
I've noticed the icon issue during feature development... however it was put off for some reason. A fix will be available soon.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
