### ISSUE TITLE
[Feature request] show progressbar in dde-dock

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#1415]
It would be great if dde-dock showed a progress bar on the icons of programs.

Almost all modern desktop environments have this feature. So, I guess Deepin DE should have this feature as well.

**Comment by aiamuzz** [comment]
> Almost all modern desktop environments have this feature.

hmmmm ... can you please post a screenshot of these feature you are requesting ?

I can fathom only a browser having this feature ... but you suggest icons of programs ... which other programs show stuff downloading ... ?

**Comment by Mark-AAAA** [comment]
That's true, every, modern OS does have this feature!
Here you can see an example from Chromium on Windows 10, downloading a file, while the user can see the progress from the task bar (or dock)!
![DeepinScreenshot_select-area_20190719180937](https://user-images.githubusercontent.com/52075807/61545565-6d567900-aa50-11e9-8e9e-104a1554baf3.png)

**Comment by Mark-AAAA** [comment]
> > Almost all modern desktop environments have this feature.
> 
> hmmmm ... can you please post a screenshot of these feature you are requesting ?
> 
> I can fathom only a browser having this feature ... but you suggest icons of programs ... which other programs show stuff downloading ... ?

@aiamuzz 
That's true, every, modern OS does have this feature!
Here you can see an example from Chromium on Windows 10, downloading a file, while the user can see the progress from the task bar (or dock)!
![DeepinScreenshot_select-area_20190719180937](https://user-images.githubusercontent.com/52075807/61545761-de962c00-aa50-11e9-972e-becc819884e2.png)

**Comment by SiamSami** [comment]
> > Almost all modern desktop environments have this feature.
> 
> hmmmm ... can you please post a screenshot of these feature you are requesting ?
> 
> I can fathom only a browser having this feature ... but you suggest icons of programs ... which other programs show stuff downloading ... ?

Sorry, I actually meant progress bar on almost every program... Not sure if it's possible or not but it's a feature that I really want in Deepin DE.

**Comment by aiamuzz** [comment]
> Sorry, I actually meant progress bar on almost every program...

I meant it can't apply to every program ... 

# browsers download so progress bar makes sense ...
# file manager copy/move/delete operations too could have a case for a progress bar ...

besides these 2 i don't think any other applications have progress info to be shown ...

**Comment by BLumia** [comment]
This require dde-dock support [the Unity launcher D-Bus API](https://wiki.ubuntu.com/Unity/LauncherAPI).

cc @wangjia12

**Comment by SiamSami** [comment]
What do you think about this @wangjia12?

**Comment by SiamSami** [comment]
@BLumia When will it come?

**Comment by SiamSami** [comment]
@wangjia12 Any update?

**Comment by BLumia** [comment]
FYI in **dtkgui** already included such feature which implemented the unity launcher dbus interface which I mentioned above (also supported by KDE and some other dock implementation so it will not be a DDE-only feature). It still requires **dde-dock** to support such feature but I'm not sure about when will that comes then.

cc @xmuli

**Comment by xmuli** [comment]
The team at dock said it would be a while before they could do it.
