### ISSUE TITLE
please add criptext to the deepin store

### ISSUE THREAD

**Issue by alvarosamudio** [linuxdeepin/developer-center#1416]
It would be good to have this program in the store, it is the client to the criptext mail which is a mail client that could be the safest mail that has ever existed.

- End to end encryption
- Doesn‘t manage your keys
- Doesn‘t collect email data
- Forward Secrecy
- Signal Protocol
- And the best thing is free code

https://criptext.com/

**Comment by alvarosamudio** [comment]
![Criptext Security](https://ibb.co/48tBrTr)

**Comment by alvarosamudio** [comment]
![DeepinScreenshot_Seleccionar área_20190719095227](https://user-images.githubusercontent.com/25090546/61544660-86890680-aa0b-11e9-807d-da019179e9a6.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
