### ISSUE TITLE
(+) or (-) can not been shown!

### ISSUE THREAD

**Issue by Mark-AAAA** [linuxdeepin/developer-center#1417]
For some reason the deepin calculator fails to show (+) or (-)!
x86_64 Linux 5.2.1-arch1-1-ARCH, Deepin 15.11, deepin-calculator 1.0.12-1.

![deepin-screen-recorder_deepin-calculator_20190718214026](https://user-images.githubusercontent.com/52075807/61483168-f31cea80-a9a4-11e9-9ee9-776fc53d01e9.gif)

**Comment by Mark-AAAA** [comment]
> Which is the font you're using? Thanks.

I had Droid Sans and now Noto Sans Display.
In both cases, this issue appears!

**Comment by aiamuzz** [comment]
on my system it shows as an ugly stretch horizontally for the plus and minus symbol ...

![image](https://user-images.githubusercontent.com/3283676/61876584-d6376880-af0a-11e9-9403-8d8aafaeb143.png)

**Comment by BLumia** [comment]
Maybe we should use the normal plus (`+`) and minus (`-`) symbol? cc @hualet

**Comment by BLumia** [comment]
ref: https://github.com/linuxdeepin/developer-center/issues/689

**Comment by Mark-AAAA** [comment]
Fixed by installing ttf-hannom, but not every symbol appears with the same format...

**Comment by Mark-AAAA** [comment]
> ref: #689

Fixed by installing ttf-hannom, but not every symbol appears with the same format...

**Comment by BLumia** [comment]
Package maintainer can add a suitable font as a dept so when user install the package, the correct font will also get installed.

> but not every symbol appears with the same format...

I would like to reopen this issue then. Maybe using the normal `+` and `-` character  can be a better way then user will no longer need to install an extra font to display it.

**Comment by adrienluitot** [comment]
@BLumia Where do you see that deepin-calculator does not use normal character?

**Comment by meiyixiang** [comment]
现在这个问题已经解决
10/5000 
This problem has now been solved
