### ISSUE TITLE
Deepin Movie: Green tick on ALL notification toasts ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1418]
@BLumia ...

I noticed after upgrading to 15.11 ... that Deepin Movie has this tick mark ... 

- firstly it has no use or significance to show the tick mark
- secondly its size visual aesthetics are ugly ... deepin movie already has a great black & white theme with subtle blue ... now this third color green and its proportions is just ugly

![image](https://user-images.githubusercontent.com/3283676/61576059-5700f980-aaf2-11e9-8682-0aeaddf43269.png)

might want to drop that feature and revert back to the earlier elegance of Deepin movie which worked without the green tick mark and a transparent background ... i see a dark grey background to the cue text (when volume, subtlitles and video speed are changed through the shortcut) ... making it transparent would increase its elegance as well.

edit by maintainer:

## To reproduce:

 1. play some movie
 2. drag a subtitle file, you'll see the green tick besides the message subtitle loaded
 3. increase/decrease volume or advance/delay subtitles or increase/decrease the video speed 
 4. green tick besides all of the above operations in (3)

**Comment by BLumia** [comment]
How to reproduce this issue? This tick icon shouldn't be here and when I adjust the volume, it's not here.

Please try use the issue report template if possible :joy:

**Comment by aiamuzz** [comment]
> How to reproduce this issue? This tick icon shouldn't be here and when I adjust the volume, it's not here.

Whaaat ... Its not reproduce'able even to me now ... what did you do @BLumia ... :open_mouth:

**Comment by BLumia** [comment]
Closing now, let us know with steps to reproduce once you can reproduce this issue :)

**Comment by aiamuzz** [comment]
> Closing now, let us know with steps to reproduce once you can reproduce this issue :)

@blumia ... i think i discovered the green tick bug ...

here's how you can reproduce it ...

play some movie ... drag a subtitle file ... you'll see the green tick besides the message subtitle loaded ... after that you increase/decrease volume ... or ... advance/delay subtitles ... or ... increase/decrease the video speed ... and you'll notice this ugle green tick besides all of the above operations !!!

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
