### ISSUE TITLE
Windows View Labels showing ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1419]
Hi,

after upgrading to 15.11 ... i notice that there are application labels and icons to the application window previews ... where as the 15.11 official video(screenshot below) shows no labels or icons

![deepin-screen-recorder_Select area_20190720134849](https://user-images.githubusercontent.com/3283676/61576248-41d99a00-aaf5-11e9-85b1-b681dbd6f094.gif)

Is this a bug that the labels and icons are showing ?

15.11 official video has an elegant preview without the label, icons and the ugly close button
![image](https://user-images.githubusercontent.com/3283676/61576202-92042c80-aaf4-11e9-9ef9-25de9ce29cad.png)

**Comment by Mark-AAAA** [comment]
And the blurred background is missing unlike the deepin-wm... :(

**Comment by BLumia** [comment]
More likely a feature? @zccrs

**Comment by aiamuzz** [comment]
> More likely a feature? @zccrs

@BLumia ... @zccrs ...

for now i would just like to get rid of the ugle lables and icons and rather prefer to have a nameless iconless form as shown in the official Deepin 15.11 video ...

If the labels and icons are introduced in an elegant way then yes would like to have it as a feature ... but if can't be elegant it rather stay without a label and icon !!!

**Comment by aiamuzz** [comment]
> More likely a feature? @zccrs
@BLumia ... @zccrs ...

for now I guess i was able to disable these three from systemsettings application ... but you might want to have this implement in an elegant way as part of bringing up kwin to deepin-wm's elegance !!!

**Comment by BLumia** [comment]
As we've said before, this ui will be changed after next big version change, but we're not able to get it implemented in a very short term, so won't fix for now, sorry about it.

**Comment by aiamuzz** [comment]
> As we've said before, this ui will be changed after next big version change, but we're not able to get it implemented in a very short term, so won't fix for now, sorry about it.

Hope that UI will be a great one ... but in the meantime `systemsettings` has enabled me to switch off all 3 ugly elements ... 

![deepin-screen-recorder_google-chrome_20190726141004](https://user-images.githubusercontent.com/3283676/61938710-5a432c00-afaf-11e9-9616-1b3f166b4fdc.gif)
