### ISSUE TITLE
[Gentoo Porting]compile error for dde-daemon-3.0.24: m.audioDaemon.GetDefaultSink undefined

### ISSUE THREAD

**Issue by zhtengw** [linuxdeepin/developer-center#142]
Hi, errors occured when I compiled dde-daemon. I have installed deepin-go-lib, dde-api, deepin-metacity. And I have installed dependent go libs into /usr/share/gocode. 
Can any one help me to point out the key problem? Thank you very mush.

Gentoo Deepin Overlay: https://github.com/zhtengw/deepin-overlay

------build log------
\>\>\> GOPATH=/usr/share/gocode/ make               
gcc -o out/bin/default-terminal -pthread -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -lgio-2.0 -lgobject-2.0 -lglib-2.0 bin/default-terminal/default-terminal.c
gcc -o out/bin/desktop-toggle -lX11 bin/desktop-toggle/main.c
env GOPATH="/var/tmp/portage/dde-base/dde-daemon-3.0.24/work/dde-daemon-3.0.24/gopath:/usr/share/gocode/" go build -ldflags '-s -w' -o out/bin/dde-session-initializer  pkg.deepin.io/dde/daemon/bin/dde-session-initializer
\# pkg.deepin.io/lib/sound
/usr/share/gocode/src/pkg.deepin.io/lib/sound/player.c: In function ‘connect_canberra_context’:
/usr/share/gocode/src/pkg.deepin.io/lib/sound/player.c:111:4: warning: format ‘%s’ expects a matching ‘char *’ argument [-Wformat=]
    g_warning("Set '%s' as backend device failed");
    ^
env GOPATH="/var/tmp/portage/dde-base/dde-daemon-3.0.24/work/dde-daemon-3.0.24/gopath:/usr/share/gocode/" go build -ldflags '-s -w' -o out/bin/dde-session-daemon  pkg.deepin.io/dde/daemon/bin/dde-session-daemon
\# pkg.deepin.io/lib/sound
/usr/share/gocode/src/pkg.deepin.io/lib/sound/player.c: In function ‘connect_canberra_context’:
/usr/share/gocode/src/pkg.deepin.io/lib/sound/player.c:111:4: warning: format ‘%s’ expects a matching ‘char *’ argument [-Wformat=]
    g_warning("Set '%s' as backend device failed");
    ^
\# pkg.deepin.io/dde/daemon/appearance
gopath/src/pkg.deepin.io/dde/daemon/appearance/manager.go:280: assignment count mismatch: 2 = 1
\# pkg.deepin.io/dde/daemon/inputdevices
gopath/src/pkg.deepin.io/dde/daemon/inputdevices/keyboard.go:270: assignment count mismatch: 2 = 1
gopath/src/pkg.deepin.io/dde/daemon/inputdevices/keyboard.go:286: assignment count mismatch: 2 = 1
\# pkg.deepin.io/dde/daemon/mpris
gopath/src/pkg.deepin.io/dde/daemon/mpris/manager.go:207: m.audioDaemon.GetDefaultSink undefined (type *audio.Audio has no field or method GetDefaultSink)
make: *** [Makefile:46: out/bin/dde-session-daemon] Error 2

**Comment by zhtengw** [comment]
It seems that it is an issue relate to the dbus-factory. I use the release version of dbus-factory in https://github.com/linuxdeepin/dbus-factory/releases. Compiling errors occur when built against dbus-factory-3.0.8, and it works fine without errors against dbus-factory-3.0.7.

Here are some differents in **/usr/share/gocode/src/dbus/com/deepin/daemon/audio/audio.go** of dbus-factory-3.0.8 and dbus-factory-3.0.7.

dbus-factory-3.0.8:
```
 19 type Audio struct {
 20         Path     dbus.ObjectPath
 21         DestName string
 22         core     *dbus.Object
 23 
 24         signals       map[<-chan *dbus.Signal]struct{}
 25         signalsLocker sync.Mutex
 26 
 27         SinkInputs       *dbusPropertyAudioSinkInputs
 28         Cards            *dbusPropertyAudioCards
 29         ActiveSinkPort   *dbusPropertyAudioActiveSinkPort
 30         ActiveSourcePort *dbusPropertyAudioActiveSourcePort
 31         DefaultSink      *dbusPropertyAudioDefaultSink
 32         DefaultSource    *dbusPropertyAudioDefaultSource
 33         MaxUIVolume      *dbusPropertyAudioMaxUIVolume
 34 }
```

dbus-factory-3.0.7:
```
19 type Audio struct {
 20         Path     dbus.ObjectPath
 21         DestName string
 22         core     *dbus.Object
 23 
 24         signals       map[<-chan *dbus.Signal]struct{}
 25         signalsLocker sync.Mutex                          
 26                                                           
 27         Sinks             *dbusPropertyAudioSinks         
 28         Sources           *dbusPropertyAudioSources       
 29         SinkInputs        *dbusPropertyAudioSinkInputs    
 30         GetDefaultSink_   *dbusPropertyAudioGetDefaultSink_
 31         GetDefaultSource_ *dbusPropertyAudioGetDefaultSource_
 32         MaxUIVolume       *dbusPropertyAudioMaxUIVolume   
 33 }                                                         
 34 
```

**Comment by felixonmars** [comment]
Yes, please use 3.0.7.

**Comment by zhtengw** [comment]
Thank you. @felixonmars
