### ISSUE TITLE
玩完游戏后桌面闪烁

### ISSUE THREAD

**Issue by htqx** [linuxdeepin/developer-center#1420]
## 缺陷描述
首先，玩3d游戏dota2，大约30多分钟后，退回桌面，这时还是正常的。但是打开kwrite等工具，桌面就在闪烁。

## 复现步骤
1. steam -->dota2
2. kwrite or kate or calculator or evolution or...

## 期望行为
不闪烁

## 截图
![深度截图_20190720162756](https://user-images.githubusercontent.com/42466118/61576326-693b6180-ab0b-11e9-9ccc-b012cc26c629.png)

黑帧

## 复现环境:
15.11

### 发行版以及版本
Linux Deepin 15.11

**Comment by loaden** [comment]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=180895&extra=page%3D1

deepin-kwin:
* 修复多次切换3D/2D模式后打开新的有标题栏的窗口时会导致屏幕闪烁的问题；
* 修复多次切换3D/2D模式后打开新的有标题栏的窗口时其它未激活窗口的阴影显示为黑色
-------------
这两个问题并没有修复。切换成deepin-wm后，这两个问题就没有了。

**Comment by BLumia** [comment]
cc @zccrs

**Comment by loaden** [comment]
一个比重启电脑好的暂时解决方案：重启DDE。
命令：
[code]sudo service lightdm restart[/code]
或者：
[code]sudo systemctl restart lightdm[/code]
@zccrs @BLumia

**Comment by loaden** [comment]
升级内核至5.1.20，Nvidia驱动至430.34问题依然存在。
重启后问题可消失，改成deepin-wm窗口管理器问题也消失。
说明是KWin的锅。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
