### ISSUE TITLE
bug: Properties dialog in DFM reports 1 extra item

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#1423]
## Describe the bug

If a folder contains x items, then the property dialog of that folder says that it contains (x+1) items.
## To Reproduce

1. Open the property dialog of any folder
2. Check how many items does it contain.
3. It should show 1 number extra.
## Expected behavior

It should not show 1 extra number
## Screenshots

![DeepinScreenshot_dde-desktop_20190720231552](https://user-images.githubusercontent.com/33563064/61581778-5c872f80-ab44-11e9-84cf-1db9ad39ee91.png)

## Enviroments:
DDE version: 15.11

### Distro & Version

Archlinux (With all the latest updates from DDE)
### Related package version

DFM v1.8.2 (1:4.8.8.1-1)

**Comment by keybreak** [comment]
Weird, i can't reproduce it on few of my Arch test-machines...
____

btw, how can it be that your DDE is 15.9, and Arch Linux is up to date?
It should be 15.11

**Comment by BLumia** [comment]
We discussed this issue internally few times ago, as the result It's the designed behavior since the property dialog count include the folder itself :joy:

cc @wangjia12

**Comment by keybreak** [comment]
@BLumia 
That's very wrong, why would you decide this? :laughing:

**Comment by SiamSami** [comment]
> btw, how can it be that your DDE is 15.9, and Arch Linux is up to date?
> It should be 15.11

@keybreak Oops! Sorry, my mistake! It's actually 15.11 and not 15.9.

**Comment by BLumia** [comment]
> That's very wrong, why would you decide this?

Not me, I can change this behavior btw, but I need product manager approve this change.

**Comment by keybreak** [comment]
I don't mean you specifically, but i really don't get why would anyone want to count property dialog as file inside folder...It's insane :laughing: 

Please change this and ask them to be more rational

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
