### ISSUE TITLE
[FEATURE REQUEST] EXPAND THE BLUR/TRANSPARENT EFFECT

### ISSUE THREAD

**Issue by Mark-AAAA** [linuxdeepin/developer-center#1424]
Please, expand the blur/transparent effect or at least give the users the ability to turn it on, on title bars or the left side of applications, like Windows 10, macos and KDE Neon(https://akava-design.github.io/)!
![DeepinScreenshot_select-area_20190720214216](https://user-images.githubusercontent.com/52075807/61582852-9ce0b080-ab38-11e9-82e4-adc03fcd5a42.png)
![DeepinScreenshot_select-area_20190720214702](https://user-images.githubusercontent.com/52075807/61582853-9ce0b080-ab38-11e9-926b-3051c07f54a8.png)
![DeepinScreenshot_select-area_20190720214838](https://user-images.githubusercontent.com/52075807/61582854-9ce0b080-ab38-11e9-8430-bb54796f8544.png)
![DeepinScreenshot_select-area_20190720213742](https://user-images.githubusercontent.com/52075807/61582855-9d794700-ab38-11e9-86bc-d1899899e21d.png)
![DeepinScreenshot_select-area_20190720214118](https://user-images.githubusercontent.com/52075807/61582856-9d794700-ab38-11e9-8589-5022999448a6.png)

**Comment by mathpfvr** [comment]
Oh nice

**Comment by hbhgwtf** [comment]
beautiful

**Comment by Mark-AAAA** [comment]
![Screenshot_20190831_004144](https://user-images.githubusercontent.com/52075807/64052691-35327200-cb88-11e9-8115-ccec49505bf1.png)
I got an KDE Neon configuration, like macos, bugsfree.
So, i don't care any more, bye!

**Comment by gardotd426** [comment]
@Mark-AAAA reopen this, you don't close things just because you switched to something else and don't care anymore. Because now, only you or a dev can reopen it, and filing a new issue for the same problem is bad practice, so you need to reopen it. If you don't care, then just don't deal with it, but reopening just takes a click.
