### ISSUE TITLE
[FEEDBACK] Add a top pane to the desktop with the global menu

### ISSUE THREAD

**Issue by mathpfvr** [linuxdeepin/developer-center#1425]
A very interesting and welcome visual feature would be a top panel with the global menu

Unity 7

![00_global_menu](https://user-images.githubusercontent.com/7264001/61583497-f633ea00-ab0e-11e9-89a0-96fc3a14342b.png)

MATE DESKTOP
![vala-panel-topmenu-ubuntu-mate](https://user-images.githubusercontent.com/7264001/61583498-ff24bb80-ab0e-11e9-988c-07ca9f2d6c81.png)

KDE PLASMA
![Screenshot_20190329_034608](https://user-images.githubusercontent.com/7264001/61583499-06e46000-ab0f-11e9-8c0a-5512f436bee2.png)

I know there are no plans for this native feature in the system, but please consider adding this, it would make the system very practical.

**Comment by RailRanger** [comment]
Imo that top bar is an ugly waste of space. Windows doesn't implement that either for a good reason.

**Comment by aiamuzz** [comment]
@BLumia ...

I understand that the team has communicated more than a few times about its decision not to support a top bar ... But the request of people(@mathpfvr ) coming from other Linux distro's and MacOS's to Deepin OS will always feel a need for the topbar and a global menu ...

Long time users of Deepin OS know that all Deepin Applications do not have the typical menu bar's ... it has a single menu on the application title bar and right-click menu's inside the application windows ... that cover all the options Deepin Applications ...

however the point to note is that this is not the case with thousands of other third party linux applications, they do have full fledged menubar's which follow the age old system of various options spread across under the tittle bar ... such applications will surely benefit from a topbar and their menu bars moved on a topbar.

So i guess as Deepin OS users increase as we go ... they will find the need of a menu based topbar just like Elementary, Mate, Untiy, KDE Plasm, MacOS and other distro's that have it !!!

**Given the above ... i think this subject will need to be revisited(as and how more users get added to DeepinOS) and the Deepin Team needs to review their earlier decision.**

**Comment by BLumia** [comment]
There are no plan to implement a mac-like topbar and a global menu from Deepin officially, but [deepin-topbar](https://github.com/justforlxz/deepin-topbar) is a kind of project which would like to add such feature but still need more time and help to implement it. Maybe consider support the developer @justforlxz via deepin-store and/or open a feature request to [deepin-topbar](https://github.com/justforlxz/deepin-topbar) or send a patch to this project directly?
