### ISSUE TITLE
Possibility to use the old look of the dock

### ISSUE THREAD

**Issue by mathpfvr** [linuxdeepin/developer-center#1426]
The current look of the Deepin 15.11 dock is beautiful and intuitive, but I particularly find the interface of the deepin 15.2 dock much more beautiful and modern, it would be very interesting to be able to choose between the two visuals

15.2
![Linux-Deepin-2014-2-RC-Is-Simply-a-Mind-Blowing-OS-Screenshot-Tour-468148-2](https://user-images.githubusercontent.com/7264001/61591909-72c3d880-aba2-11e9-9903-a69591906b0d.jpg)

15.11
![deepin-1511-lancado](https://user-images.githubusercontent.com/7264001/61591918-7b1c1380-aba2-11e9-9031-b2bdfa27df53.jpg)

**Comment by aiamuzz** [comment]
> The current look of the Deepin 15.11 dock is beautiful and intuitive, but I particularly find the interface of the deepin 15.2 dock much more beautiful and modern, it would be very interesting to be able to choose between the two visuals

@mathpfvr ... wouldn't it be nice if you posted a screenshot of the 15.2 dock and 15.11 dock ... and let us know why you prefer the old look ?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
