### ISSUE TITLE
开机不登录会卡死

### ISSUE THREAD

**Issue by htqx** [linuxdeepin/developer-center#1427]
## 缺陷描述
开机，出现登录框，但是不操作，过一段事件后再操作，画面凝固，鼠标可以动，但无法操作，无法切换到其他终端，完全死机状态。

## 复现步骤
1.开机然后不动

## 期望行为
不知道是不是bug

## 复现环境:
15.11

### 发行版以及版本
Linux Deepin 15.11

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
