### ISSUE TITLE
时间描述不正确

### ISSUE THREAD

**Issue by htqx** [linuxdeepin/developer-center#1428]
## 缺陷描述
右下角时间描述不正确，而且设置无效。比如设置12小时制，开机又返回24小时制。

12小时制的凌晨0:35显示： 12:35 下午， 这和中午12:35有什么区别？请优化一下显示，更加符合中国人习惯，我知道外国是什么am pm，但至少避免这种低级错误。

## 期望行为
正确记录设置和准确描述时间

### 发行版以及版本
Linux Deepin 15.11

**Comment by BLumia** [comment]
两种写法都见过..这个不算错误吧...

设置无效的问题我记得有同样问题的 issue ，一时半会没找到，明天再看看..

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
