### ISSUE TITLE
新功能刻录不可用

### ISSUE THREAD

**Issue by htqx** [linuxdeepin/developer-center#1429]
## 缺陷描述
可以显示光驱，但是根本打不开，手动mount sr0，然后去文件管理器点击光驱设备，让输入密码，打开了，但是内容是空的。

## 期望行为
优化

### 发行版以及版本
 Linux Deepin 15.11

### 相关的软件包版本
dde-file-manager

**Comment by BLumia** [comment]
提供的信息好像没法判断出什么问题..

cc @chirs241097

**Comment by chirs241097** [comment]
卸载并弹出光盘，执行 `xorriso -devices` （若找不到命令则用 `sudo apt install xorriso` 或你的发行版对应的包管理器安装），然后任意放一张光盘，执行 `xorriso -dev /dev/sr0` （假设光驱设备是 `/dev/sr0`）。粘贴以上两个命令的输出。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
