### ISSUE TITLE
新功能同步，显示区域不可用

### ISSUE THREAD

**Issue by htqx** [linuxdeepin/developer-center#1430]
## 缺陷描述
可以登录，但是显示区域不可用，用户名貌似也是错的。本人广东电信。

## 复现步骤
1. 打开 设置
2. 点击 云同步
3. 登录正常
4. 显示不可用

## 期望行为
正常使用

## 截图
![image](https://user-images.githubusercontent.com/42466118/61586313-3fce1480-aba3-11e9-9cff-c3e117c17109.png)

![image](https://user-images.githubusercontent.com/42466118/61586318-53797b00-aba3-11e9-8107-5fb988deae6f.png)

## 复现环境:
15.11
### 发行版以及版本
Linux Deepin 15.11

**Comment by BLumia** [comment]
需要去你的 deepin id 设置那里改一下地区，在账号中心。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
