### ISSUE TITLE
商店安装应用进度圈显示移位

### ISSUE THREAD

**Issue by htqx** [linuxdeepin/developer-center#1431]
## 缺陷描述
如题

## 复现步骤
1. 应用商店
2. 安装应用，进度圆圈出现位移

## 期望行为
修复样式

## 截图
![商店进度bug](https://user-images.githubusercontent.com/42466118/61587021-284b5780-abb4-11e9-9db5-0d164be45334.jpg)

## 复现环境:
15.11

### 发行版以及版本
Linux Deepin 15.11

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
