### ISSUE TITLE
Tablet configuration, button assignment

### ISSUE THREAD

**Issue by samvila** [linuxdeepin/developer-center#1432]
On the control panel the option to set up a tablet (wacom or any other brand) is very limited, it only allows the user to select the type of movement when using the pen but not the assignment of the buttons. Without this option using a tablet in Deepin is a nightmare, you have to stick to the default button configuration which limits the users in the way they use the tablet on the operating system and the applications in general.

Please add a setting to configure individual buttons on the pen when using a tablet.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
