### ISSUE TITLE
[Manjaro] Wine apps in system tray not clickable

### ISSUE THREAD

**Issue by MasterJubei** [linuxdeepin/developer-center#1434]
If an application in Wine is minimized to system tray, it is not clickable with either left or right click. No context menus will appear, so the app is not able to be opened.

This issue is NOT present on Deepin 15.11 but is on every version of Manjaro Deepin I have tried. (18.04 and 18.1.0). It is not related to the Wine version, issue is not present on Manjaro KDE.

## To Reproduce
An easy app to test with is Fraps even with the text corruption with Wine
http://www.fraps.com/free/setup.exe
1. After installed click Minimize to system tray on the bottom left
2. Minimize
3. The context menus do not appear.

Here is a gif of it:
https://media.giphy.com/media/ehIDd5k4caoPCOGnKA/giphy.gif

Manjaro forum thread:
https://forum.manjaro.org/t/cant-right-click-wine-apps-in-system-tray/95685

**Comment by RailRanger** [comment]
@chenjunyy19
https://bugs.kde.org/show_bug.cgi?id=399234 this might be the same bug

**Comment by BLumia** [comment]
Thanks for the info <3

> but the link might be handy if/when it affects v20.

Need test if this happens in v20. cc @liuwen123

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
