### ISSUE TITLE
[FEEDBACK] More customization options for the deepin dock

### ISSUE THREAD

**Issue by mathpfvr** [linuxdeepin/developer-center#1435]
- Add the option to adjust the size of the dock and icons

- Possibility to change between light and dark theme

- Possibility to use colors as highlight (blue, green, yellow) or the color of the dock adapt to the wallpaper

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
