### ISSUE TITLE
[feature request]Multiple monitors enable different desktop wallpapers for different monitors

### ISSUE THREAD

**Issue by hbhgwtf** [linuxdeepin/developer-center#1436]

**Comment by RailRanger** [comment]
This would be a very nice feature to have. Currently, hydrapaper does not work with Deepin. If you apply backgrounds with hydrapaper it just puts both images on each monitor.

**Comment by hbhgwtf** [comment]
> This would be a very nice feature to have. Currently, hydrapaper does not work with Deepin. If you apply backgrounds with hydrapaper it just puts both images on each monitor.

Indeed it is

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
