### ISSUE TITLE
Wifi plugin on dock shows only one wifi access point ... the one connected ... but shows the list when not connected ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1438]
Hi,

This is not a recent issue ... i think its been from a pretty long time ... may be even from version 15.7 ... I don't know if this is a bug or its by design ... if its by design it doesn't make sense given the possible uses cases.

##

as you can see in this screenshot ... you can see only one wifi access point in the list ... the one the system is connected to ...
![image](https://user-images.githubusercontent.com/3283676/61640214-91b58e00-acba-11e9-922b-6cfe00d71ddd.png)

##

But when i switch off the wifi slider and switch it back on then you see the list differently ...

![image](https://user-images.githubusercontent.com/3283676/61640345-c7f30d80-acba-11e9-9a1e-5d6f18e0a1a8.png)

##

**So if i have to switch between my 2 routers at home i can't switch from one to another ... the only way is i have to disable the wifi switch and re-enable it back and then make a switch to the second router in my setup.**

**Comment by keybreak** [comment]
Hmm...But when you connected if you wait ain't it show more after some time?

For me sometimes this list just take longer than it should to find spots

**Comment by aiamuzz** [comment]
> Hmm...But when you connected if you wait, ain't it show more after some time?

no ... i don't remember seeing other points when its connected ... used to work well before 15.7 or may be earlier ... **sorry, i was just lazy to report it sooner** ... i work from the same place so there isn't really any impact to me at least !!!

> For me sometimes this list just take longer than it should to find spots

so this is happening to you too @keybreak ... only the connected access point showing in the list ?

**Comment by keybreak** [comment]
Nope, like i've said - for me if i wait some time - they will show (but at first yes, it shows connected).

**Comment by aiamuzz** [comment]
> Nope, like i've said - for me if i wait some time - they will show (but at first yes, it shows only connected for few seconds).

oh yeah ... it shows for me too after waiting sometime ... hahahahaha ... 

@BLumia ... is this a bug ?

**Comment by BLumia** [comment]
I'm not sure, I don't maintain the dde-dock codebase, sorry about that..

**Comment by aiamuzz** [comment]
> I'm not sure, I don't maintain the dde-dock codebase, sorry about that..

If hovering the mouse over wifi and then the AP list populating is an intended behavior ... then close it ... if not label this as a bug !!!

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
