### ISSUE TITLE
Deepin File Manager keybindings file location ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1439]
Hey,

Currently Deepin File Manager does not provide the option to modify/change the default shortcut key bindings ...

However I would like to manually modify a particular keybindings(shortcuts) configured on the File Manager I want to change `Ctrl+l` to `Alt+d` ...

I was hoping there is a file somewhere with those bindings that i can manually change to a shortcut of my choice.

Can somebody point me to the location(path) to such a file ?

If such an option of manually changing keybindings isn't possible ... can the devs provide me with the command that's configured so `Ctrl+l` works ? ... that way i can configure that command and assign a shortcut in the control panel.

**Comment by BLumia** [comment]
Currently it's hardcoded in [`dfilemanagerwindow.cpp`](https://github.com/linuxdeepin/dde-file-manager/blob/31f0ea9bdd668c1ab10de5dd201378af6bdfcc03/dde-file-manager-lib/views/dfilemanagerwindow.cpp#L194) so the only way works is change the code and re-compile it by yourself.

**Comment by aiamuzz** [comment]
@BLumia ... that means there will not be a command either ?
:((

**Comment by BLumia** [comment]
No, sadly currently no such support :(

For product design there are no plan to implement shortcut setting for dde-file-manager. Config file for this purpose is possible but still need to refact the code for a little bit.

Closing then.
