### ISSUE TITLE
[archlinux] Control Center is not integrated correctly

### ISSUE THREAD

**Issue by Fs02** [linuxdeepin/developer-center#144]
I've  fresh archlinux installation with deepin desktop environment. I have several problem as you can see from screenshot below:

![deepinscreenshot20170115100409](https://cloud.githubusercontent.com/assets/3049307/21959946/05638a9e-db0a-11e6-8a2e-1538fa96ed65.png)
There's some option missing there, but the brightness control is working

![deepinscreenshot20170115100630](https://cloud.githubusercontent.com/assets/3049307/21959954/522cbda0-db0a-11e6-9deb-b65e856bc5f8.png)
Option also missing in default applications

![deepinscreenshot20170115100724](https://cloud.githubusercontent.com/assets/3049307/21959958/72e186f2-db0a-11e6-8e26-29a8d5dab2cc.png)
Monoscpaced and Size seems to be resetted after reboot, but it doesn't seem to be affecting the system.

![deepinscreenshot20170115100920](https://cloud.githubusercontent.com/assets/3049307/21959973/bdb403f8-db0a-11e6-9f68-6c6b987f8454.png)
Volume and Microphone input in control panel is not displayed correctly, modifying the value also doesn't affect the system.  The volume control in the bottom of the screen also doesn't work.

Sorry for the long post, thanks

**Comment by dfstorm** [comment]
So, I was wondering if it was just me. I've got these problems too.

**Comment by kirigayakazushin** [comment]
I think the dde-session-daemon crash resulted in the front end did not get the data。

**Comment by Fs02** [comment]
fixed after enabling multilib and doing full system upgrade and deepin control center is replaced with newest version

**Comment by funilrys** [comment]
@Fs02  I think you can close this now then :)
