### ISSUE TITLE
[BUG] Lists being displayed after increasing the screen scale

### ISSUE THREAD

**Issue by mathpfvr** [linuxdeepin/developer-center#1440]
These stripes appear in the dock and in the system settings, after enlarging the screen scale

This bug ocorrer on Deepin 15.10.1 and 15.11

![photo_2019-07-22_16-51-06](https://user-images.githubusercontent.com/7264001/61661116-c0733a80-aca1-11e9-9bdf-65aa57d0f20a.jpg)
![photo_2019-07-22_16-49-41](https://user-images.githubusercontent.com/7264001/61661117-c0733a80-aca1-11e9-8009-660a01457bcd.jpg)
![Captura de Tela_dde-desktop_20190722164530](https://user-images.githubusercontent.com/7264001/61661222-f7495080-aca1-11e9-9958-3d09b8c7603e.png)

**Comment by BLumia** [comment]
Duplicated with https://github.com/linuxdeepin/developer-center/issues/1352 , Thanks for reporting!
