### ISSUE TITLE
[建议]标题栏菜单和右键菜单风格保持一致

### ISSUE THREAD

**Issue by jetmit** [linuxdeepin/developer-center#1441]
这是状态栏右键菜单,选中状态的✔ , 桌面右键菜单也是这样

![me10](https://user-images.githubusercontent.com/20562449/61681507-3fb74b80-ad40-11e9-86a4-502b8515915f.png)

但是系统标题栏✔有方框,并且比较小,和右键菜单不一致
![me08](https://user-images.githubusercontent.com/20562449/61681658-ee5b8c00-ad40-11e9-8562-fef7cdde2a4e.png)

期望能和右键菜单保持一致
OS: deepin 15.11

**Comment by BLumia** [comment]
重复 https://github.com/linuxdeepin/developer-center/issues/1421 

感谢反馈

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
