### ISSUE TITLE
dde terminal won't minimize

### ISSUE THREAD

**Issue by ThatComputerKid** [linuxdeepin/developer-center#1443]
Occasionally when minimizing the deepin terminal, it remains visible but impossible to interact with and always on top, and it transparent value remains active.

I'm running deepin on arch linux

### Related package version
dde-terminal 3.2.7.1-1

**Comment by keybreak** [comment]
Is this caused by infamous dock preview bug?
https://github.com/linuxdeepin/developer-center/issues/1200

**Comment by gpen365** [comment]
Possibly

**Comment by keybreak** [comment]
@BLumia @zccrs 
Can you please fix this  https://github.com/linuxdeepin/developer-center/issues/1200 already? :bug: :beetle:

**Comment by BLumia** [comment]
Are you using deepin-kwin or deepin-wm? If you are still using deepin-wm, maybe consider try out deepin-kwin then?

**Comment by keybreak** [comment]
What @gpen365 reference here will also happen for deepin-kwin (just like i was referencing it in https://github.com/linuxdeepin/developer-center/issues/1200 when you've asked).

Try to click when having preview item this bug exists in different forms for both compositors and it's serious bacause everyone have it and it breaks workflows.

**Comment by gpen365** [comment]
How do I know?

**Comment by BLumia** [comment]
The simplest way is `screenfetch`.

But since @keybreak mentions it happens on both dde-kwin and deepin-wm, maybe try do a `killall dde-dock` once this issue happended?

Sorry I cannot offer more help since I doesn't know much about how x11 wm works, maybe the dde-kwin maintainer @zccrs  can give us some help?

**Comment by gpen365** [comment]
@keybreak I am using deepin-wm. I found deepin-kwin to be ugly. just my opinion.

**Comment by Mark-AAAA** [comment]
> @keybreak I am using deepin-wm. I found deepin-kwin to be ugly. just my opinion.

That's true.
deepin-wm is far more elegant than the deepin-kwin!

**Comment by BLumia** [comment]
Sadly deepin-wm is no longer maintained by deepin team, the current deepin-kwin also planned to bring some deepin-wm look'n'feel back to deepin-kwin in future updates, it need some time to implement these features, though.

Maybe you guys from community can create a fork of deepin-wm and continue maintain it and even add new features to it if you really want to give deepin-wm some love?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
