### ISSUE TITLE
bug: dde-dock shows time in 24 hour format instead of 12 hour format

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#1444]
## Describe the bug

dde-dock shows time in 24 hour format instead of showing it in 12 hour format.
## To Reproduce

1. Make sure you have set the time to 12-hour format
2. Restart the computer
3. If it shows in 12-hour format, then restart the computer again.
4. This time the time should be in 24-hour format.
## Expected behavior

The clock should show time in 12-hour format if it is set to.
## Screenshots

![DeepinScreenshot_select-area_20190725082327](https://user-images.githubusercontent.com/33563064/61841336-3f40c100-aeb6-11e9-93ba-8c5e729ace34.png)

## Enviroments:
DDE v15.11
### Distro & Version

Archlinux
### Related package version

dde-dock v.4.10.8-1

**Comment by mathpfvr** [comment]
DDE need new icon for show time

**Comment by BLumia** [comment]
Associate https://github.com/linuxdeepin/developer-center/issues/1454

**Comment by SiamSami** [comment]
@BLumi When will it get fixed?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
