### ISSUE TITLE
自家应用界面不一致

### ISSUE THREAD

**Issue by licardoY** [linuxdeepin/developer-center#1446]
![fee](https://user-images.githubusercontent.com/20562449/61859237-51dce980-aefa-11e9-84b5-ef1b91927e38.png)

**Comment by BLumia** [comment]
@shule1987 哪个应该是对的？

**Comment by Iceyer** [comment]
@BLumia 文管那个有点偏吧

**Comment by shule1987** [comment]
准确来说实现的都有问题，两个都不对，下个版本控件我会强制修改的
