### ISSUE TITLE
DVD-RW drive is now always visible, even if there's no disc in it

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/developer-center#1447]
[Screen-cast](https://youtu.be/c8gA6QCu02Y)

**Comment by BLumia** [comment]
Yes it's the new designed behavior, so it will allow you right click and eject the tray so you can put your disc in it.

btw It's recommended to also fill the issue template so we can process issue way more effective.

Thanks for reporting!

**Comment by es20490446e** [comment]
But it doesn't allow to close the tray... 😏
