### ISSUE TITLE
[arch linux] windows are laggy when moving

### ISSUE THREAD

**Issue by psykotik1** [linuxdeepin/developer-center#145]

**Comment by sonald** [comment]
Can you provide some info about running system ? what kind of display card do you have ? did you install  any proprietary video card driver ? Does cpu load is high ?

**Comment by dantheman213** [comment]
Title with no description? No specifications or detailed description of what happened? No log dump, terminal output, steps to replicate, or screenshots of said issue?

Why even fill out a bug report? This is like taking your car into a mechanic's shop and saying "it doesn't work".

**Comment by funilrys** [comment]
Please refer  to https://github.com/linuxdeepin/dde-control-center/issues/45

**Comment by sonald** [comment]
> Please refer to linuxdeepin/dde-control-center#45
this is helpful

**Comment by funilrys** [comment]
@sonald Yeah at least we (maybe) can figure out where is the problem from there cause this issue doesn't provide any consistent description.

**Comment by sonald** [comment]
@funilrys fasheng was no longer in deepin project. I'll close this for now, since no useful details to reproduce the problem.

**Comment by funilrys** [comment]
@sonald who's in charge of arch linux now (so I can update it) ? cause actually his username is still in the Arch Wiki page. 

@sonald Did you see linuxdeepin/dde-control-center#45 ?

**Comment by sonald** [comment]
> @sonald who's in charge of arch linux now (so I can update it) ? cause actually his username is still in the Arch Wiki page.
I believe there is no special person in charge, the whole deepin team will response to the problems from other distributions. 

> @sonald Did you see linuxdeepin/dde-control-center#45 ?
Yes, I did. I think this is irrelavant to that problem.
