### ISSUE TITLE
Deepin 从15.10.2升级到15.11后，启动速度变慢了

### ISSUE THREAD

**Issue by loaden** [linuxdeepin/developer-center#1452]
## 缺陷描述

启动速度明显变慢了，比之前大约慢了10～20秒。
15.10.2启动速度挺快的。
四台单deepin系统都如此，两笔记本两台式机，其中一个台式机是固态硬盘。

## 期望行为

查找原因。

### 发行版以及版本

15.11

### 其他内容

loaden@yuchen:~$ systemd-analyze
Startup finished in 8.980s (firmware) + 5.562s (loader) + 3.403s (kernel) + 23.250s (userspace) = 41.197s

**Comment by loaden** [comment]
这个userspace占用的时间很大。在我的另一台联想笔记本上，首次启动，userspace用时61秒，第二次启动用时44秒，缩短了17秒。不知道这个userspace是不是指加载DDE的时间。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
