### ISSUE TITLE
deepin15.11桌面黑屏，dde dock还在，几秒以后恢复

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1453]
## 缺陷描述

deepin15.11，偶尔会黑屏，整个桌面漆黑一片，但是dde dock还在，然后几秒钟以后自动恢复。

## 复现步骤

偶尔出现，难以复现

## 期望行为

不要黑屏

### 发行版以及版本

deepin15.11

**Comment by BLumia** [comment]
尝试安装 systemd-coredump 后在下次复现此情况时通过 `coredumpctl list` 查看最后崩溃的 `dde-desktop` 进程 pid ，然后汇报 `coredumpctl info <pid>`的输出结果，到时候我 reopen 这个 issue 。感谢汇报。

**Comment by widon1104** [comment]
widon@widon-PC:~$ coredumpctl list
TIME                            PID   UID   GID SIG COREFILE EXE
Sat 2019-07-27 14:07:20 CST   10490  1000  1000  11 present  /usr/bin/dde-desktop
Sat 2019-07-27 14:07:49 CST   14370  1000  1000  11 present  /usr/bin/dde-desktop
Sat 2019-07-27 14:07:59 CST   14511  1000  1000  11 present  /usr/bin/xrandr
Sat 2019-07-27 14:08:00 CST   14481  1000  1000  11 present  /usr/bin/dde-desktop
Sat 2019-07-27 14:08:12 CST   14583  1000  1000  11 present  /usr/bin/dde-desktop
Sat 2019-07-27 14:08:22 CST   14687  1000  1000  11 present  /usr/bin/dde-desktop
Sat 2019-07-27 14:09:01 CST   14748  1000  1000  11 present  /usr/bin/dde-desktop
Sat 2019-07-27 14:09:24 CST   14912  1000  1000  11 present  /usr/bin/dde-desktop
Sat 2019-07-27 14:12:44 CST   14970  1000  1000  11 present  /usr/bin/dde-desktop
Sat 2019-07-27 14:17:19 CST   15136  1000  1000  11 present  /usr/bin/dde-desktop
Sat 2019-07-27 14:17:24 CST   15315  1000  1000  11 present  /usr/bin/dde-desktop
Sat 2019-07-27 14:17:32 CST   15406  1000  1000  11 present  /usr/bin/dde-desktop
Sat 2019-07-27 14:18:06 CST   15432  1000  1000  11 present  /usr/bin/dde-desktop
Sat 2019-07-27 14:32:27 CST   15569  1000  1000  11 present  /usr/bin/dde-lock
Sat 2019-07-27 14:32:27 CST   15590  1000  1000   5 present  /usr/bin/python3.5
Sat 2019-07-27 14:32:27 CST   15537  1000  1000  11 present  /usr/bin/dde-desktop

没多久就crash了很多次，我随便贴几个coredumpctl info <pid>输出到这里，不够我再多弄点
[10490.txt](https://github.com/linuxdeepin/developer-center/files/3437926/10490.txt)
[14370.txt](https://github.com/linuxdeepin/developer-center/files/3437927/14370.txt)
[15537.txt](https://github.com/linuxdeepin/developer-center/files/3437929/15537.txt)
[15569.txt](https://github.com/linuxdeepin/developer-center/files/3437930/15569.txt)
[14511.txt](https://github.com/linuxdeepin/developer-center/files/3437931/14511.txt)
[15590.txt](https://github.com/linuxdeepin/developer-center/files/3437932/15590.txt)

**Comment by widon1104** [comment]
我发现了一个让dde desktop不停奔溃的方法
https://kernel.ubuntu.com/~kernel-ppa/mainline/
下载ubuntu kernel 5.1.7，然后安装，重启以后dde desktop就会不停的奔溃

然后卸载ubuntu kernel 5.1.7，重启，内核回到4.15.0，dde desktop还是不停的奔溃

现在我的电脑已经完全不能用了，dde desktop几秒奔溃一次，屏幕不停地闪动。

除了重装有办法恢复吗？比如说关闭kwin用老的窗口管理器，如何切换窗口管理器呢？

**Comment by BLumia** [comment]
非官方的内核不再支持范围内...如果官方的没问题并且自己没有维护能力的话，不建议自行安装。

上面我忘记提到了抱歉，需要安装一下 `dde-desktop-dbgsym` 包然后再把新的 coredump 提供一下，不然看不到崩溃到哪里了，只能看到个(n/a) :joy:

**Comment by widon1104** [comment]
我的系统现在不停地闪，几乎无法操作，如何恢复啊

**Comment by BLumia** [comment]
我没崩溃啊... 你的情况你可以直接暂时把 dde-desktop 二进制移走到别的地方就是了。很容易崩溃我们是不会发更新的，所以才需要社区反馈我们没覆盖到的问题啊...

有新的崩溃后烦请贴一下 coredump 以便定位问题..

**Comment by widon1104** [comment]
系统没有dde-desktop也能运行吗？可否加一个你的微信，有问题直接请教你

**Comment by BLumia** [comment]
我不使用微信抱歉 :joy: ，公开讨论也可以帮助遇到类似问题的人查看相关讨论和结果。

dde-desktop 包只负责桌面相关功能，如果不需要桌面图标/相应的右键菜单和桌面壁纸的话你卸载掉也是可以正常使用的，为了调试方便我平时是不装 dde-desktop 包，直接 gdb 启一个带调试符号的 dde-desktop 二进制来用的。

得到桌面崩溃的 coredump 和你之前获得的方式一样，只不过你需要额外装 `dde-desktop-dbgsym` 这个包来得到调试符号，以便崩溃的时候能得到具体位置。

**Comment by widon1104** [comment]
![crash 70+ times](https://user-images.githubusercontent.com/12093211/62043714-a0102680-b233-11e9-9750-1a25e4e49787.png)
先发出来看看，确实是奔溃了70+次，但是现在我安装了dde-desktop-dbgsym，coredumpctl info输出的内容还是 n/a，难道以前的crash包都没用了，还要重新复现才可以吗？

我上传一个info信息，最后是死在dde desktop里面，但是看不出来是哪一个函数，哪一行
[8389.txt](https://github.com/linuxdeepin/developer-center/files/3441728/8389.txt)

**Comment by BLumia** [comment]
你的确需要看你装了dbgsym包之后的新的崩溃 :joy:

**Comment by BLumia** [comment]
我先打开吧，然后等一个新的崩溃的 coredump stacktrace 看。

**Comment by widon1104** [comment]
我装了dde-desktop-dbgsym以后，昨天晚上用了几个小时，又不崩溃了，真是让人琢磨不透啊。

**Comment by BLumia** [comment]
显然不会..虽然文管最近是有个更新而且我不清楚目前推送到社区版没有，但是即便那个更新推送出去应该也和你的问题没关系。你可以看 `/var/log/apt/history.log` 来关注你软件包安装的 log。

那就先关掉了。如果再遇到问题的话可以直接开个新 issue ，因为不一定和这个 issue 相关。

**Comment by widon1104** [comment]
还有一个问题，我的电脑上个星期进过水，不知道是不是硬件故障导致问题，而代码没有做好处理导致奔溃。

**Comment by widon1104** [comment]
今天我发现dde-desktop又奔溃过很多次，同时奔溃的还有dde-lock python3.5
我输出了一些信息，希望排查
[3516_dde-desktop.txt](https://github.com/linuxdeepin/developer-center/files/3525425/3516_dde-desktop.txt)
[8027_dde-lock.txt](https://github.com/linuxdeepin/developer-center/files/3525427/8027_dde-lock.txt)
[8048_python3.5.txt](https://github.com/linuxdeepin/developer-center/files/3525428/8048_python3.5.txt)
[23619_dde-desktop.txt](https://github.com/linuxdeepin/developer-center/files/3525429/23619_dde-desktop.txt)
[24476_dde-desktop.txt](https://github.com/linuxdeepin/developer-center/files/3525430/24476_dde-desktop.txt)
[26279_dde-desktop.txt](https://github.com/linuxdeepin/developer-center/files/3525431/26279_dde-desktop.txt)

**Comment by widon1104** [comment]
希望reopen这个bug。
10月8日，我的电脑又出现在deepin15.11环境下屏幕闪、黑屏的现象，同时伴随有dde-desktop程序的奔溃。
**送到华硕维修中心经过检测没有发现硬件问题。**
