### ISSUE TITLE
重插鼠标会导致firefox浏览器标签切换失败

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1455]
## 缺陷描述

这个问题是必现的，我勾选了插入鼠标就关闭触摸板，鼠标插在usb接口上
1）打开firefox（68.0.1）打开2个标签（或者多个标签），都打开baidu.com
2)  拔出鼠标，然后插上
3）用鼠标切换firefox标签，发现点不动了，无法切换到别的标签

## 期望行为

重插鼠标不能影响firefox正常工作

### 发行版以及版本

deepin15.11

**Comment by duanyao** [comment]
似乎类似这个问题 #1324 。楼主是只有切换标签不行，还是鼠标操作都不行？

**Comment by widon1104** [comment]
用鼠标切换firefox标签不行，用鼠标做其他事比如关掉firefox是可以的啊

**Comment by duanyao** [comment]
@widon1104  我能复现这个问题，不过页面内的鼠标操作都是不行的，例如选中文字、点击链接、右键菜单都是不行的，你是这样吗？

以前插入鼠标只是偶尔触发这个问题，安装几天前的deepin更新后，这个问题在firefox上必现，但在微信、WPS、dbeaver上倒是还没有出现过。

**Comment by ihipop** [comment]
@BLumia @hualet @duanyao  同复现 以前是偶然事件现在变成必然事件 不光不能切换标签页 页面内也不响应鼠标点击，但是可以响应键盘操作，Firefox 68.0.1 (64 位)  (官方国际版中文版)，Wine程序插拔鼠标不能触发。

**Comment by widon1104** [comment]
> 不过页面内的鼠标操作都是不行的，例如选中文字、点击链接、右键菜单都是不行的，你是这样吗？

我的现象跟你一样的，在firefox页面内选中文字、点击链接、右键菜单都是不行的。

**Comment by BLumia** [comment]
cc @jouyouyun @electricface

**Comment by ihipop** [comment]
Title bar改成 client渲染好像好了@duanyao 

> env MOZ_GTK_TITLEBAR_DECORATION=client /home/ihipop/App/Mozilla/firefox/firefox

**Comment by duanyao** [comment]
@ihipop 的确，我这里有效。

**Comment by BLumia** [comment]
这问题竟然和这个有关的么.. 有没有人有兴趣把这个 bug 报到 mozilla ，我目前实在太忙没时间确认问题和开 bug  :joy: ，另外修改这个值不会影响 deepin-wm 的行为，这个是我之前确认过的。

顺便关联一下 https://github.com/linuxdeepin/developer-center/issues/1460

**Comment by piggyking** [comment]
我这边也是一样的问题，我在论坛已经发了帖子了。
我这边的问题是，只要拔插已经连接的usb/蓝牙鼠标或者键盘，就会导致微信/wps/filezilla/雷鸟失去对鼠标的响应。
而且是每一次都会发生。
我的火狐倒是没有问题，因为用的是国际版的。
这些发生问题的软件都是仓库版本。
我记得我这个问题发生在那时论坛说unstable不能切换到stable时，我重装了系统之后。
之前似乎unstable升级上来也没问题。。
具体时间和版本记不清了，就是刚换成kwin的那个版本。

**Comment by ihipop** [comment]
@piggyking 我用的也是国际版

@BLumia 现在火狐的问题有办法零临时解决了，deepin wine的鼠标响应怎么办呢？#1324

**Comment by duanyao** [comment]
@BLumia 能确定是firefox的bug吗？大致是那一块儿？我想象不出firefox为什么会对插拔鼠标有反应。`MOZ_GTK_TITLEBAR_DECORATION` 好像是跟窗口管理器有关？

**Comment by BLumia** [comment]
> @BLumia 能确定是firefox的bug吗？大致是哪一块儿？我想象不出firefox为什么会对插拔鼠标有反应。`MOZ_GTK_TITLEBAR_DECORATION` 好像是跟窗口管理器有关？如果有个大概的方向，我可以编译个firefox来调试一下。

我只能确认 `MOZ_GTK_TITLEBAR_DECORATION` 的那个问题的确是会影响你应用内设置“隐藏标题栏”有没有效。详细请参考 #1460 和 https://bugzilla.mozilla.org/show_bug.cgi?id=1462227 。是不是这个地方影响到了火狐的鼠标事件响应这点我也不太清楚（我也很意外 @ihipop 说 `MOZ_GTK_TITLEBAR_DECORATION` 改成 client 可以解决这个问题）。

简单的说就是，`MOZ_GTK_TITLEBAR_DECORATION` 的确应该改成 `client` （因为 firefox 判断桌面环境是 Deepin 就会用 `system` ，而后来深度窗管从 deepin-wm 换成 dde-kwin 了），但我也不清楚 firefox 的代码基础而言的客户端窗口修饰的 `system` 和 `client` 是什么区别，所以不清楚这个 issue 的问题是不是和这个相关 :joy:

**Comment by duanyao** [comment]
@BLumia 了解。你们试过 ihipop 说的方法了吗？

**Comment by ihipop** [comment]
> > @BLumia 能确定是firefox的bug吗？大致是哪一块儿？我想象不出firefox为什么会对插拔鼠标有反应。`MOZ_GTK_TITLEBAR_DECORATION` 好像是跟窗口管理器有关？如果有个大概的方向，我可以编译个firefox来调试一下。
> 
> 我只能确认 `MOZ_GTK_TITLEBAR_DECORATION` 的那个问题的确是会影响你应用内设置“隐藏标题栏”有没有效。详细请参考 #1460 和 https://bugzilla.mozilla.org/show_bug.cgi?id=1462227 。是不是这个地方影响到了火狐的鼠标事件响应这点我也不太清楚（我也很意外 @ihipop 说 `MOZ_GTK_TITLEBAR_DECORATION` 改成 client 可以解决这个问题）。
> 
> 简单的说就是，`MOZ_GTK_TITLEBAR_DECORATION` 的确应该改成 `client` （因为 firefox 判断桌面环境是 Deepin 就会用 `system` ，而后来深度窗管从 deepin-wm 换成 dde-kwin 了），但我也不清楚 firefox 的代码基础而言的客户端窗口修饰的 `system` 和 `client` 是什么区别，所以不清楚这个 issue 的问题是不是和这个相关

@BLumia 这个**不是不识别鼠标，是不响应鼠标点击，但是响应鼠标hover的**，是不是可能和窗管没正确处理鼠标点击，点穿透了有关，当改完client渲染后程序自己处理就正常了。

@duanyao  这个严格山来说不是firefox的bug，应该是错误的平台差异处理。而且deepin-wine之类的程序也受到影响。肯定是其他哪里有不对的才会导致这么多程序受到影响。换其他桌面就没问题

**Comment by BLumia** [comment]
> 是不是可能和窗管没正确处理鼠标点击，点穿透了有关，当改完client渲染后程序自己处理就正常了。

system 和 client 是 firefox 自己处理不同窗口修饰的模式，我觉得很大可能不是窗管问题，不然也不会搞两个模式出来（可以在 kde+kwin 下尝试一下 system 是不是也有一样的问题）。

> 这个严格山来说不是firefox的bug

就 `MOZ_GTK_TITLEBAR_DECORATION` 的值而言，是。我是觉得 firefox 应该直接获取和判断窗管来决定它自身应该使用什么模式，而不是判断桌面环境。

--------

还是要重复一下我的意思，毕竟我目前没法也没时间研究 #1455 和 #1460 是不是完全一个问题：

 1. （针对 #1460 ）在 firefox 检查到桌面环境是 Deepin 时 `MOZ_GTK_TITLEBAR_DECORATION` 应当更换为 `client`，这个的确是 firefox 的 bug ，并且非常明确应该报给 firefox 那边。
 2. （针对 #1455 ）我暂不能确定 `MOZ_GTK_TITLEBAR_DECORATION`为 `client` 时 firefox 响应正确是窗管的问题还是 firefox 的问题。

不过可以补充一下：

有一些应用的窗管支持之前是不规范的，比如刚切换到 kwin 后， deepin-terminal 的雷神模式获取不到焦点的问题就属于 deepin-terminal 之前的写法不规范（raise 需要正确的时间戳但没有提供）。kwin 的一部分支持是（相对别的窗管）比较严格的，所以当遇到 kwin 有问题而别的窗管没有的时候，不一定总是 kwin 的问题，deepin-wine 可能也存在类似的情况，在没实际定位到问题之前这个的确不好说。

**Comment by duanyao** [comment]
今天deepin系统更新之后，情况发生了变化： 重插鼠标导致firefox不响应鼠标的问题不再是必现的了，其中 68.0.2 、68.0.1、67.0.4 出现的概率较小，大概插拔鼠标十来次才会出现一次，而且几乎不会连续出现。65.0.1 和 66.0.5 出现的概率较大，而且会连续出现。以上测试没有设置 `MOZ_GTK_TITLEBAR_DECORATION` 。

dbeaver 6.0.2 和 mysql workbench 6.3.8 出现此问题的概率仍然不小。没有观察到更新后的微信（ 2.6.8.52）出现此问题。

我看了一下更新的日志（ /var/log/apt/history.log ），是

```
Start-Date: 2019-08-26  10:33:36
Commandline: apt-get -y -o APT::Status-Fd=3 -c /var/lib/lastore/apt.conf --allow-downgrades --allow-change-held-packages dist-upgrade
Upgrade: deepin.com.wechat:i386 (2.6.2.31deepin0, 2.6.8.52deepin0), deepin-wine-helper:i386 (1.2deepin0, 1.2deepin7), deepin-wine-plugin-virtual:amd64 (1.0deepin2, 1.0deepin3)
End-Date: 2019-08-26  10:33:38
```

这个真的跟 deepin-wine 有关吗？

**Comment by piggyking** [comment]
我前两天更换了一个鼠标，从logitech的M336换成了RAPOO的M500，然后，关闭鼠标开启鼠标会导致wps系列软件/微信/雷鸟等失去鼠标响应的问题没有了。

但是拔插键盘还是会100%发生这个问题。

**Comment by piggyking** [comment]
另外更新一个事情。
上面说到kwin的问题，实际上不存在的，我试过切换回wm，还是一样的。

**Comment by ihipop** [comment]
@piggyking 你在deepin上装KDE试试 好像是没问题的 同一套系统。

**Comment by ihipop** [comment]
这个问题新版没有了 但是很好奇是什么导致的？

**Comment by xmuli** [comment]
已解决那就暂时关闭, 后面对此问题感兴趣, 想讨论详细, 后面可以再自行打开
