### ISSUE TITLE
New organization of icons in Launcher

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#1458]
## Describe the bug
Let the user automatically arrange shortcuts in the Launcher, in alphabetical order.

### Distro & Version
Deepin 15.11 Lion

### Additional context

**Comment by aiamuzz** [comment]
yes this and a separate category that list out the most recently used apps in the launcher would make life easier to a user ... the window styled launcher mode has this recent apps option but the full screen launcher lacks the same !

**Comment by alexwender1** [comment]
I reiterate the request for deepin 20
