### ISSUE TITLE
Slow Transfer Files

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#1459]
## Describe the bug
After the release of version 15.11, I noticed a drop in file transfer performance. The speed drops sharply.

When you connect the flash drive to the computer, the system is slow. And the transfer speeds are slow.

I have Deepin installed on SSD; and file transfer is low between partitions (EXT4 format). The normal is 400mb/s. But the transfer is at 35-45mb/s.

And the transfer pop-up screen is still displayed. Until the speed reaches 0mb/s; until it disappears.

### Distro & Version
Deepin 15.11 Lion

### Related package version
dde-file-manager 4.8.8.1

### Additional context
This problem did NOT occur in earlier versions of the system.

I did a clean install of version 15.11.

**Comment by aiamuzz** [comment]
generally the copy/move operations on Deepin have always been very slow compared(right from the time i have switched to DeepinOS) to other distro's ... Also i have experienced freezes and crashes on multiple copy/move operations or operations that involve a very large chunk of data from one place to the other ...

Is Deepin's way of carrying out these operations different under the hood in comparison to other distro's ?
