### ISSUE TITLE
Firefox Title Bar

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#1460]
## Describe the bug
By disabling the title bar in Firefox settings; When maximizing the application window, the bar still displays.

The full size window does not display the title bar.

The instruction in the file “**~/.Config/kwinrc**”, allows not to display the title bar in ALL GTK applications.

_[Windows]
BorderlessMaximizedWindows=true_

A specific instruction is required for Mozilla Firefox. Otherwise, other applications will be harmed.

### Distro & Version
Deepin 15.11 Lion

**Comment by BLumia** [comment]
Before launching firefox, set the `$MOZ_GTK_TITLEBAR_DECORATION=client`enviroment variable should works :)

**Comment by BLumia** [comment]
This issue caused by https://bugzilla.mozilla.org/show_bug.cgi?id=1462227

The old `sCSDSupportLevel = CSD_SUPPORT_SYSTEM;` is for `deepin-wm` but now we are on `deepin-kwin` or say `kwin` so it should be `client` now. We also tested the `client` value should also works under `deepin-wm` so it's totally okay to switch to `client`. I haven't have time to report to upstream, anyone would like to help can report this or send a patch to mozilla :)

btw, IMHO firefox shouldn't check the desktop enviroment to decide its `CSDSupportLevel`, detect window manager directly should be a better approach. For example once it found kwin, it can use `client` CSD support level.

**Comment by keybreak** [comment]
@BLumia 
I highly doubt it's the cause, since Manjaro have same Firefox package for all it's DE editions, and none of them except Deepin have this problem.

**Comment by BLumia** [comment]
> since Manjaro have same Firefox package for all it's DE editions, and none of them except Deepin have this problem.

If you have check that bug out you will know, firefox will use `sCSDSupportLevel=CSD_SUPPORT_CLIENT` if   `XDG_CURRENT_DESKTOP` is set to `Deepin`.

**Comment by keybreak** [comment]
Oh sorry i missed your point at first, so Firefox detects which DE is in use by XDG_CURRENT_DESKTOP...

That would explain, i thought at first that decision is made by compositor, therefore it would be weird that Gnome and KDE works on Manjaro :laughing:

**Comment by alexwender1** [comment]
> Before launching firefox, set the `$MOZ_GTK_TITLEBAR_DECORATION=client`enviroment variable should works :)

How can I add this command to the launcher shortcut?

**Comment by BLumia** [comment]
Find the `.desktop` file and update the `Exec` key I guess? Maybe you can try out `menulibre` which can help you manage your desktop files :)

**Comment by keybreak** [comment]
Something like:
```
Exec=env $MOZ_GTK_TITLEBAR_DECORATION=client /usr/lib/firefox/firefox --new-window %u
```

**Comment by alexwender1** [comment]
Thank you so much @keybreak and @BLumia.
Now Firefox is behaving well in Deepin (Lion).

![Captura de Tela_dde-desktop_20190806092406](https://user-images.githubusercontent.com/45263160/62540562-478dea00-b82e-11e9-871d-41d5d1ad65fe.png)

**Comment by BLumia** [comment]
associate: https://bugzilla.mozilla.org/show_bug.cgi?id=1606791

**Comment by heregoesnoth** [comment]
My desktop file has three entries so i needed to put the env variable in each one for cover all cases.

**Comment by alexwender1** [comment]
Since the problem is specific to Firefox, I will be closing this issue.

Note:
1 - Some developer needs to check if Mozilla is aware of the problem or the fix has been rejected (we have been waiting for this fix in Firefox for over 1 year).
2 - With the information that appeared in this topic, I will be making a new issue suggesting that Firefox (not ESR) comes pre-installed on the system (with all corrections included).
