### ISSUE TITLE
Translation Update (pt-BR)

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#1461]
## Describe the bug
Some corrections to the Brazilian Portuguese translation (pt-BR) were not delivered in version 15.11 (especially in Deepin Apps).

Please release ALL translation fixes for pt-BR in the next update. If not, the reviewers have to wait for months to detect a problem and correct it).

### Distro & Version
Deepin 15.11 Lion

### Additional context
@zhuxiujuancindy

**Comment by zhuxiujuancindy** [comment]
The translation of Deepin Appstore will be released in next system update, fixing some issues.
The translations of other projects have indeed been released in 15.11. Maybe the translations were merged earlier than the time they were finished.

For other projects, you can test and review them as following:

1. Convert the .ts language package in .qm format. Download and install Qt Creator from Deepin Store. Open the .ts file in the Qt5 Linguist program and save it in the .qm format. 

2. Move file to usr/share/deepin-appname/translations, and then open deepin application to test the translations.
