### ISSUE TITLE
Deepin Miraclecast

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#1462]
## Describe the bug
The Wireless Screen Projection (Deepin Miraclecast?) Of the system does not connect to Philips Smart TV (not Android TV).

The TV displays which device you want to connect. When accepting the connection, only a black screen is displayed. At the same time, Deepin disconnects from the internet (from the router).

Allow Deepin to connect to TV via router; just like Android smartphones. Because the user can consume internet content through the connection to the TV (a wireless connection between devices - without internet access - is not interesting).

### Distro & Version
Deepin 15.11 Lion

### Additional context
https://github.com/linuxdeepin/miraclecast

**Comment by BLumia** [comment]
cc @electricface
