### ISSUE TITLE
Plugins only show but not toggle on left mouse click

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#1463]
###  Describe the bug
Plugin icons like disks / Sound **always** act on left mouse click with 'show' action, and doesn't hide back once you press lmb again if plugin is shown and visible.

### Distro & Version
Manjaro / Arch Deepin current versions

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
