### ISSUE TITLE
Deepin File Manager [Language Bug]

### ISSUE THREAD

**Issue by locknet11** [linuxdeepin/developer-center#1464]
## Describe the bug
I install Deepin Linux 15.11 and select Spanish as the default language , after the installation I decide to change my default language to English , everything works fine but when I open the Deepin File Manager as Admin all the options are in Spanish and not in English.

## To Reproduce
1-Install Deepin Linux 15.11 in Spanish
2-After the installation change the default language to English
3-Open a normal Deepin File Manager window.
4-Right click and select "open in new window as admin"

## Expected behavior
It will open a new Deepin File Manager as admin but all the options will be in Spanish.

## Screenshots
![ENGLISH OPTIONS](https://user-images.githubusercontent.com/52685437/62010944-f869fa00-b147-11e9-9116-d42d45d9dfc1.png)
And then:
![SPANISH OPTIONS](https://user-images.githubusercontent.com/52685437/62010950-0cadf700-b148-11e9-9a6b-9e4de34c2091.png)

### Distro & Version
Linux Deepin 15.11 Desktop

**Comment by BLumia** [comment]
Control center won't change the root user's settings so a root file manager will still use the root user's settings.

The setting location should be `/etc/default/locale` and you can update this value to the one you want.

cc @electricface

**Comment by locknet11** [comment]
> Control center won't change the root user's settings so a root file manager will still use the root user's settings.
> 
> The setting location should be `/etc/default/locale` and you can update this value to the one you want.
> 
> cc @electricface

Thank you very much for your reply!
It works. Just change the locale file and change it for "en_US" and now it's completly in English.
