### ISSUE TITLE
deepin开机选项画面分辨率非常低，不正常

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1466]
## 缺陷描述

deepin开机画面分辨率很低，我的电脑分辨率1920*1080，我截了一张图
![分辨率不正常，很低](https://user-images.githubusercontent.com/12093211/62019274-b8ab1d00-b1f0-11e9-8e6f-24c9304db3d4.jpg)
我还有一个笔记本装的deepin，开机画面分辨率就是正常的，所以这个问题是偶现

### 发行版以及版本

deepin15.11

**Comment by FurryWolfX** [comment]
我觉得最好附上硬件型号吧

**Comment by widon1104** [comment]
我不知道怎么在deepin获取硬件信息，deepin-feedback-cli输出的信息够吗？
[deepin-feedback-cli-Deepin-15.11-all-20190802-135324.tar.gz](https://github.com/linuxdeepin/developer-center/files/3459776/deepin-feedback-cli-Deepin-15.11-all-20190802-135324.tar.gz)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
