### ISSUE TITLE
wine的阿里旺旺对话窗口从最小化到显示时窗口会明显黑屏闪动一下

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1467]
## 缺陷描述

把阿里旺旺对话窗口打开，然后最小化对话窗口，然后打开显示对话窗口，这时候对话窗口会明显的黑屏闪一下

## 期望行为

不要闪

### 发行版以及版本

deepin15.11

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
