### ISSUE TITLE
Window glitches when minimizing.

### ISSUE THREAD

**Issue by MrVenison** [linuxdeepin/developer-center#1468]
## Describe the bug
Every time I minimize a window, a glitched "ghost" of the window remains on the screen. When I click somewhere else on the screen, the ghost of the window vanishes. Sometimes from bringing a window back up, the window glitches and only a part of it will appear until it is clicked on/ interacted with.

## To Reproduce
Just minimize a window, probably more prevalent when there are multiple programs running.

## Expected behavior
There should be a smooth transition of minimizing and un-minimizing a window, without having it glitch and have a ghost of it remain on the screen.

### Distro & Version
Linux Deepin 15.11

**Comment by Mark-AAAA** [comment]
That is a known issue but never got fixed...
https://github.com/linuxdeepin/developer-center/issues/1337

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
