### ISSUE TITLE
Low brightness level when a device wakes up

### ISSUE THREAD

**Issue by Mark-AAAA** [linuxdeepin/developer-center#1470]
After the latest deepin updates on Arch, when my laptop wakes up, it still has low brightness level and I have to manually change it every time...

**Comment by Mark-AAAA** [comment]
@BLumia 
I found out that the issue is related with the very broken deepin-daemon 5.0.0-2.
I downgrade the deepin-daemon to 3.28.0 and then it works fine.

**Comment by BLumia** [comment]
Sorry I'm not working on dde-daemon. Maybe @electricface can help you out.

**Comment by Mark-AAAA** [comment]
I've switched to kde with a nice configuration, do i don't care anymore.
