### ISSUE TITLE
Package 'ia32-libs' has no installation candidate ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1471]
how do we install this package ... i remember it was present in the earlier Deepin unstable version ... has this package missed out from being added to the Deepin Stable branch ?

```
sudo apt-get install ia32-libs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package ia32-libs is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  lib32z1 lib32ncurses5

E: Package 'ia32-libs' has no installation candidate

```

**Comment by abcfy2** [comment]
`ia32-libs` has been deprecated. See: https://askubuntu.com/questions/107230/what-happened-to-the-ia32-libs-package

You can install `package_name:i386` for a 32 bit lib or application.
