### ISSUE TITLE
Design of Cursor Wait / Busy

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#1472]
## Describe the bug
In older versions of Deepin, a different cursor is used for the "cursor waiting".

Since version 15.6, another design (more rustic and ugly) has been adopted; and not seem to me to be intentional.

Adopt the old cursor. Or, work on a better option (the current wait cursor is ugly).

## Screenshots

OLD CURSOR
![photo5044108742198667317](https://user-images.githubusercontent.com/45263160/62148366-f03cc680-b2cf-11e9-955f-4b0730cee466.jpg)
![photo5044108742198667316](https://user-images.githubusercontent.com/45263160/62148374-f337b700-b2cf-11e9-9d73-466ff47469fa.jpg)

CURRENT CURSOR
![51366516-2dc4c980-1acd-11e9-9285-8915d2d447c8](https://user-images.githubusercontent.com/45263160/62148376-f5017a80-b2cf-11e9-916f-35f219c285b8.jpg)

### Distro & Version
Deepin 15.11 Lion

### Additional context
@shule1987

**Comment by alexwender1** [comment]
https://github.com/linuxdeepin/developer-center/issues/816#issuecomment-455443517

**Comment by aiamuzz** [comment]
yup ... uggggggly ... 'loading' cursor icon

**Comment by keybreak** [comment]
I don't get why it's not universally orb filling with water - it's really cool

**Comment by aiamuzz** [comment]
> I don't get why it's not universally orb filling with water - it's really cool

:smile: ... are you referring to the deepin clone application which has the orb with the blue liquid filling up ?
