### ISSUE TITLE
希望deepin编辑器添加终端的搜索和打开链接功能

### ISSUE THREAD

**Issue by jetmit** [linuxdeepin/developer-center#1474]
### 希望deepin编辑器添加两个功能
- 像终端的搜索功能: 能选中后右键搜索

- 像终端的打开链接功能: ctrl+左键直接打开链接

## 截图
![sse](https://user-images.githubusercontent.com/20562449/62274634-d5ef1e00-b472-11e9-9546-5be804038161.png)

### 发行版以及版本
deepin15.11

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
