### ISSUE TITLE
解压多个压缩包只需要输入一次密码

### ISSUE THREAD

**Issue by abcfy2** [linuxdeepin/developer-center#1476]
## 缺陷描述

按住ctrl键选中多个需要密码的压缩包选择解压，每个压缩包都会要一次密码。

## 期望行为

像Winrar / 7z 那样一批密码一样的压缩包只需要输入一次密码即可，后面的压缩包使用相同的密码尝试解压，只有密码不正确的情况下再提示用户尝试新密码

### 发行版以及版本

Linux Deepin 15.11

**Comment by BLumia** [comment]
实质是调的 file-roller ，密码框应该是 file-roller 的，似乎目前没别的比较好的办法，先记录一下。

感谢反馈～

**Comment by myml** [comment]
现在deepin有自己的归档管理器，看要不要实现这个功能

**Comment by meiyixiang** [comment]
因为我无法判断是否你都是使用的同一个密码去压缩的文件，这个需求算是一个点，但是不算高优先级的需求。

**Comment by meiyixiang** [comment]
这个问题，我已经记录下来了。
