### ISSUE TITLE
Deepin Movie's window comes to foreground by hovering on the timeline of a video.

### ISSUE THREAD

**Issue by gokhanyildirimlar** [linuxdeepin/developer-center#1477]
## Describe the bug
Deepin Movie's window comes to the foreground by hovering on the timeline of a video. Clicking is not needed, it's enough to contact mouse pointer with the timeline.

## To Reproduce
1. Open a video file with Deepin Movie.
2. Open a different window and bring to the foreground.
3. Drag the mouse pointer towards Deepin Movie and contact to the timeline.
4. Deepin Movie comes to the foreground.

## Expected behavior
Deepin Movie should retain its ground.

## Video
https://sendvid.com/814xsvw8

### Distro & Version
Linux Deepin 15.11

### Related package version
deepin-movie v3.2.7(3.2.24.2-2+comsta)

**Comment by Mark-AAAA** [comment]
This is a known issue https://github.com/linuxdeepin/deepin-movie-reborn/issues/47

**Comment by aiamuzz** [comment]
> 3\. Drag the mouse pointer towards Deepin Movie and contact to the timeline.

not just the contact timeline this happens all around ... If the mouse moves into the Deepin-Movie window behind the foreground window it switches to the deepin movie ... and this happens only when the Deepin-Movie is in full screen mode.

actually this is really annoying ... say when we pull the file manager on top of the full screen and for some reason have to access the dock ... the fact that the mouse passes over the movie window before it can reach the dock ... triggers this bug(or a bad design) and one can never access the dock ... we have to bring a maximized window to the foreground and only then the dock can be accessed.

**Comment by gokhanyildirimlar** [comment]
> Also [linuxdeepin/deepin-movie-reborn#47](https://github.com/linuxdeepin/deepin-movie-reborn/issues/47)

I tried and it doesn't happen on my system. Maybe something about Arch only.

**Comment by gokhanyildirimlar** [comment]
> not just the contact timeline this happens all around

It happens as I said on my system when the mouse pointer contacts to the timeline. Perhaps, this needs to be checked deeper.

**Comment by aiamuzz** [comment]
> > not just the contact timeline this happens all around
> 
> It happens as I said on my system when the mouse pointer contacts to the timeline. Perhaps, this needs to be checked deeper.

ok ... @gokhanyildirimlar ... can you open some other video application or even an online video(youtube) and run it full screen ... then test this bug with that video full screen and post the result ...

**Comment by gokhanyildirimlar** [comment]
> > > not just the contact timeline this happens all around
> > 
> > 
> > It happens as I said on my system when the mouse pointer contacts to the timeline. Perhaps, this needs to be checked deeper.
> 
> ok ... @gokhanyildirimlar ... can you open some other video application or even an online video(youtube) and run it full screen ... then test this bug with that video full screen and post the result ...

Are you talking about this? @aiamuzz 

![deepin-screen-recorder_deepin-movie_20190802124336](https://user-images.githubusercontent.com/45146702/62361246-45bce180-b523-11e9-9fbc-7e6cbc48d2c9.gif)

**Comment by aiamuzz** [comment]
yes ... for me it happens if i drag my cursor on both the sides as well as on the top of the file manager window ... This is happening not only for Deepin Movie Window but its happening for other online video player full screen windows as well ...

**Comment by gokhanyildirimlar** [comment]
> yes ... for me it happens if i drag my cursor on both the sides as well as on the top of the file manager window ... This is happening not only for Deepin Movie Window but its happening for other online video player full screen windows as well ...

Well, it happens only on Deepin Movie for me. I tried VLC and Google Chrome after you said but they are fine. Plus, this is what I said, this happens when the mouse cursor touched to the timeline.

![deepin-screen-recorder_deepin-movie_20190802131100](https://user-images.githubusercontent.com/45146702/62363176-6c7d1700-b527-11e9-9b8d-bf64f8d57db7.gif)

**Comment by keybreak** [comment]
https://github.com/linuxdeepin/developer-center/issues/1292

Nobody gives a crap since june, relax :)

**Comment by aiamuzz** [comment]
for me it happens on online video player, including youtube ... vlc ... when played in fullscreen mode ...

![deepin-screen-recorder_google-chrome_20190802154944](https://user-images.githubusercontent.com/3283676/62363571-3fd3fa00-b53d-11e9-9c5e-c59b72078aa3.gif)

i suspect some kwin setting plying spoil sport just like [this](https://github.com/linuxdeepin/developer-center/issues/1389) other kwin settings conflict ...

**Comment by gokhanyildirimlar** [comment]
> #1292
> 
> Nobody gives a crap since june, relax :)

It's fixed already. I don't have this issue. https://github.com/linuxdeepin/developer-center/issues/1157

**Comment by gokhanyildirimlar** [comment]
Closed since this is not the case with v20 beta anymore.
