### ISSUE TITLE
深度文件管理器在系统监视器中中划线显示错误

### ISSUE THREAD

**Issue by dongfengweixiao** [linuxdeepin/developer-center#1478]
![_deepin-system-monitor_20181026225554](https://user-images.githubusercontent.com/1300822/47574597-8b37f700-d972-11e8-97a9-bcbacb69e899.png)

如图，正常情况下其他的应用，在活动状态和应用名称之间，显示的是英文状态下的中划线，但是文件管理器显示的是“加长”的中划线（全角？）。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
