### ISSUE TITLE
[Gentoo Linux] dde-control-center tearing view

### ISSUE THREAD

**Issue by zhtengw** [linuxdeepin/developer-center#148]
The dde-control-center appears tearing when I scroll the mouse. As the screenshots show below.
![2017-01-19 17 57 05](https://cloud.githubusercontent.com/assets/3148769/22102212/9bf94470-de71-11e6-8a3b-6fb5bd957269.png)
![2017-01-19 17 58 41](https://cloud.githubusercontent.com/assets/3148769/22102216/9fee84e6-de71-11e6-92d7-154dfea6f983.png)

**Comment by sbwtw** [comment]
@zccrs

**Comment by hualet** [comment]
@zhtengw You need the qt5integration package, which is necessary to make the UI more smooth.
As to the tearing, I think it's because there's bug in the upstream cogl package, which we've forked a new project from, @sonald can give you more details on this.

**Comment by zhtengw** [comment]
Thanks. I already have deepin version of cogl installed, but not qt5integration. I will install qt5integration for a try. May I ask, whether is the qt5integration a build time dependency or runtime dependency?

Best regards,
Aten

**Comment by hualet** [comment]
Runtime dependency obviously 😄, it contains some Qt5 plugins that help DDE being more Qt5-Apps friendly. I should've fill the README, sorry.

**Comment by sonald** [comment]
FYI 
you need deepin version of cogl and a patched clutter.  plus, upgrade deepin-mutter up to 3.20.8 fix some partial blurring problem.

here is the patch : https://gist.github.com/sonald/2b7fd83c2e357fe92b815e34150e858f

**Comment by zhtengw** [comment]
Thank you @hualet. Installing qt5integration worked. But it is not just a runtime dependency. The dde-control-center should rebuild with qt5integration intalled to take effect.

**Comment by zhtengw** [comment]
Thanks @sonald. I will bump new ebuild for deepin-mutter-3.20.8 then.

**Comment by hualet** [comment]
@zhtengw That's strange, it shouldn't be like that :fearful:

**Comment by funilrys** [comment]
Any feedback after the recent updates @zhtengw ?

**Comment by zhtengw** [comment]
@funilrys Since I had added qt5integration as a dependent of dde-control-center, this issue have never occurred after many version bump.
