### ISSUE TITLE
Inconsistent Print preview

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#1483]
## Describe the bug
Some time ago Deepin updated style of **Print preview**, but only for Image viewer, for example Deepin editor still has old style.

## Expected behavior
Consistent across all programs.

### Distro & Version
Arch / Manjaro Deepin / Linux Deepin

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
