### ISSUE TITLE
Calculator theme change is not properly rendered

### ISSUE THREAD

**Issue by prazooo** [linuxdeepin/developer-center#1484]
## Describe the bug
When you change the theme of the calculator (In my case I changed from light to Dark theme), it doesn't change all the elements in the calculator window. (Please check screenshots)
If you close the calculator and open it back it shows the correctly themed calculator window.

## To Reproduce

1. Open Deepin Calculator
2. Click on the context menu on the top right of the address bar.
3. Toggle  'Dark Theme' option
4. See screen shot

## Screenshots
![cal 3](https://user-images.githubusercontent.com/29881917/62410347-0f09c880-b602-11e9-8105-3344aaa1b9eb.png)

### Distro & Version
OS: Manjaro Deepin
Desktop Environment: Deepin 
Window Manager: Mutter(DeepinGala)

**Comment by Mark-AAAA** [comment]
I confirm this, x86_64 Linux 5.2.5-arch1-1-ARCH, Deepin 15.11.

**Comment by keybreak** [comment]
Also happens here:
https://github.com/linuxdeepin/developer-center/issues/1422

Seems to be universal problem...

**Comment by RailRanger** [comment]
For what it's worth I have tried 15.11 with updates and haven't noticed this issue even on clean installs. But I have noticed it on 15.10 and on Manjaro versions.

**Comment by Mark-AAAA** [comment]
> For what it's worth I have tried 15.11 with updates and haven't noticed this issue even on clean installs. But I have noticed it on 15.10 and on Manjaro versions.

Yes, we are talking about Arch Linux/Manjaro versions!

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
