### ISSUE TITLE
Calculator not showing addition and subtract symbols

### ISSUE THREAD

**Issue by prazooo** [linuxdeepin/developer-center#1485]
## Describe the bug
Deepin calculator does not show addition (+) and subtract (-) symbols. Shows as boxes. (Check screenshot)
Divition (/) and Multiplication (*) are shown properly

## To Reproduce

1. Open Deeping calculator
2. Enter a simple formula with addition and subtraction (Example 25 + 10 - 5)

## Expected behavior
Calculator should show 25 + 10 - 5

## Actual behavior
Check screenshot

## Screenshots

![cal1](https://user-images.githubusercontent.com/29881917/62410483-d23ed100-b603-11e9-9ade-4426a3c47aa9.png)

### Distro & Version
OS: Manjaro Deepin
Desktop Environment: Deepin 
Window Manager: Mutter(DeepinGala)

**Comment by Mark-AAAA** [comment]
This is a known issue https://github.com/linuxdeepin/developer-center/issues/1417 but haven't got fixed yet...

**Comment by BLumia** [comment]
Please track this issue at https://github.com/linuxdeepin/developer-center/issues/1417 , installing `ttf-hannom` can solve your issue btw :)

**Comment by Mark-AAAA** [comment]
> ttf-hannom

yes but the format is not the same for all symbols...
![DeepinScreenshot_dde-desktop_20190813145953](https://user-images.githubusercontent.com/52075807/62939975-1b98d880-bddb-11e9-9dd4-8e7184095f04.png)
