### ISSUE TITLE
deepin-daemon导致WiFi无法正常使用

### ISSUE THREAD

**Issue by codexvn** [linuxdeepin/developer-center#1486]
## 复现步骤
将包升级到deepin-daemon-5.0.0-1之后会出现以下问题
1. 开机有小几率wifi连不上
2. 切换wifi时需要好久才能连上，具体的现象为一直提示正在连接
3. 回退deepin-daemon-3.28.0-1之后一切正常
## 期望行为
希望尽快修复，这个问题很严重了

## 录屏
[录屏.mp4.zip](https://github.com/linuxdeepin/developer-center/files/3464136/mp4.zip)

## 复现环境:
OS: Arch Linux 
Kernel: x86_64 Linux 5.2.5-zen1-1-zen
DE: Deepin 15.11
WM: Deepin WM
无线网卡:Intel Wireless-AC 9560
    
### 相关的软件包版本
deepin-daemon-5.0.0-1
deepin-daemon-3.28.0-1
### 其他内容
这个问题以前也得过
>https://bbs.deepin.org/forum.php?mod=viewthread&tid=137071

**Comment by Mark-AAAA** [comment]
I confirm that super annoying issue.

**Comment by A-Siam** [comment]
> I confirm that super annoying issue and the solve with deepin-daemon-3.28.0-1

+1

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
