### ISSUE TITLE
iwlwifi.conf导致网速很慢

### ISSUE THREAD

**Issue by codexvn** [linuxdeepin/developer-center#1487]
## 缺陷描述
iwlwifi.conf参数设置下网速很慢，删除"/etc/modprobe.d/iwlwifi.conf"文件后执行
```shell
modprobe -rv iwlmvm
modprobe -v iwlwifi
```
网速恢复正常。

## 建议
删除这个文件

## 截图
删除前
![深度截图_选择区域_20190804020312](https://user-images.githubusercontent.com/24852067/62415422-1e1d6480-b65c-11e9-9b44-1a448b164ef4.png)
删除后
![深度截图_选择区域_20190804020322](https://user-images.githubusercontent.com/24852067/62415423-207fbe80-b65c-11e9-8dec-5295bc5f9014.png)

## 复现环境:
OS:Deepin最新版
无线网卡:Intel Wireless-AC 9560

**Comment by gokhanyildirimlar** [comment]
I have slow internet problem by default and I am solving this by changing **11n_disable** parameter to 8 in iwlwifi.conf.

**Comment by lidanger** [comment]
The same with @gokhanyildirimlar.But it's not a absolute solution.And it only return to about 60% of the full speed with the option 8.

@derekdai

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
