### ISSUE TITLE
如果不插在/etc/fstab挂载的硬盘第二块硬盘，系统就无法启动

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1488]
## 缺陷描述

我的电脑有2块硬盘，一个挂载在/是系统启动盘，一个挂载在/warehouse，是存储数据用，我换屏的时候拆了电脑，发现如果我不插那个挂载在/warehouse下的硬盘的话，系统启动就会报错，报进入了emergency mode，然后无论如何都进不了桌面了，我觉得这个不是很合理，因为第二块硬盘只是做数据存储之用，就算挂载失败了，也应该让系统正常启动，大不了进去找不到/warehouse这个目录就可以了。这样直接让系统不能启动，很不友好。
## 期望行为

硬盘挂载到非关键节点，如果挂载失败，不应该影响系统启动
### 发行版以及版本

deepin15.11

**Comment by BLumia** [comment]
那你为什么要把那块盘写到fstab里...不写在那里又不是不能挂载...

意图内的行为。
