### ISSUE TITLE
Unable to fully use the deepin Store.

### ISSUE THREAD

**Issue by dance707** [linuxdeepin/developer-center#1489]
## Describe the bug

After seeing an update today for deepin-sync-daemon. I noticed most of my installed apps are only shown in the Uninstall section of the deepin Store.

## To Reproduce

login the deepin Store or deepin Cloud Sync

## Expected behavior

For those abroad or not on the mainland, expect to be able to fully use the deepin store like we were always able to before.

## Enviroments:

Other Regions 

### Distro & Version

Deepin 15.11 stable

### Related package version

deepin-sync-daemon/lion,now 1.1.1+c1-1+comsta amd64 [installed]

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
