### ISSUE TITLE
problems with automatic screen resolution

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/developer-center#149]
I have a new problem when running a Manjaro-Deepin ISO (built with latest 15.4 packages) in virtualbox:
The "recommended screen resolution" in control center is set automatically, which makes the window content too big for my screen. When I then change the setting to a smaller resolution it will be reset to the recommended one with every new login. Sometimes - depending on the used host DE or WM I even run into the problem that I cannot reach neither the control-center or the dock to navigate at all because they are too far at the bottom and right to be accessible. 
So, for one I am looking for a way to make the change permanent - which it should be in any case I think - and also it would be great if the behaviour could be improved altogether because for people running a prebuilt ISO, like Manjaro-Deepin in a vbox the result will not good and undesireable :wink:

**Comment by oberon2007** [comment]
My actual screenresolution is 1366x768, still in the vbox window deepin recommends 2560x1600 - which, as you can see, doesn't work out too well 😜 

![recommended](https://cloud.githubusercontent.com/assets/11800714/22223977/37733cfa-e1bd-11e6-9ed8-c746eacb6b57.png)

**Comment by jouyouyun** [comment]
Please update the startdde to last version and test it.

**Comment by justforlxz** [comment]
This question has not been answered for too long and will be closed. If there is a need to continue the discussion, it will be reopened.
