### ISSUE TITLE
Shortcuts cannot be saved!

### ISSUE THREAD

**Issue by Mark-AAAA** [linuxdeepin/developer-center#1490]
After the latest Deepin updates on Arch, my screenshot shortcut has gone and when I try to set it 
 back (Alt-Control-A), it works until power off my device.
In the next boot it gets wiped/removed...
System info:
x86_64 Linux 5.2.5-arch1-1-ARCH
Deepin 15.11
![DeepinScreenshot_select-area_20190805221604](https://user-images.githubusercontent.com/52075807/62489305-16ca9800-b7cf-11e9-89d9-454651fa39e2.png)

**Comment by BLumia** [comment]
@electricface

**Comment by Mark-AAAA** [comment]
> @electricface

I found out that the issue is related with the very broken deepin-daemon 5.0.0-1.
I downgrade the deepin-daemon to 3.28.0 and then it works fine.

**Comment by Mark-AAAA** [comment]
nobody cares
