### ISSUE TITLE
个性化->标准字体选择范围太窄

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1492]
## 缺陷描述

我发现Dejavu Sans Mono这款等宽字体显示效果不错，但是个性化->标准字体却不能设置这款字体为标准字体。我觉得应该把等宽字体的所有字体加入标准字体的选择列表，让标准字体也能选择等宽字体。

## 期望行为

个性化->标准字体要能够选择系统的等宽字体

### 发行版以及版本

deepin15.11

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
