### ISSUE TITLE
imac theme from store not supported

### ISSUE THREAD

**Issue by theagostino** [linuxdeepin/developer-center#1494]
The imac theme from the store does not seem to be supported at all. Most of the applications continue to display the deepin standard theme. This not only affects the deepin applications (file-manager, video, music...), but also vlc, firefox, chrome etc. Please fix this error! I'm waiting for a long time for a bug fix. Thank you!

**Comment by BLumia** [comment]
The GTK theme only apply to GTK applications, so all non-GTK app (like all DTK app and Qt app) will use its theme than the GTK one.
