### ISSUE TITLE
怀疑关机功能偶尔不正常

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1496]
## 缺陷描述

昨天晚上关机的时候，关的非常快，deepin log都没有显示就关了。
今天开机的时候第一次按电源键没有反应，第二次按电源键系统才启动。
昨天我测试过睡眠功能，但是重启过，应该不会是这个影响到关机吧。
我怀疑关机那块还是有点问题。

### 发行版以及版本

deepin15.11

**Comment by BLumia** [comment]
信息不足以复现缺陷。如有可能相关的信息供复现（简单的说就是一个完全不认识你的人能够通过你的描述复现 bug ），可以贴到下面，我好 reopen ..
