### ISSUE TITLE
The cursor is placed at the edge of the window, and the icon that changes the size of the window is not displayed.

### ISSUE THREAD

**Issue by fanhengyuan** [linuxdeepin/developer-center#1497]
## Describe the bug

I found this problem. I don't know if it is a bug.

As shown in the following GIF diagram, the right deepin terminal is normal.

Non-deepin official software such as teamview, VirtualBox cursors are placed on the edge, and no icon for changing the window is displayed.

But you can change the window size.

## Screenshots

![pic](https://tva1.sinaimg.cn/large/006Xmmmggy1g5rifogeobg31hc0t04qq.gif)

Do not display the icon for the red box below.

![avatar](https://tva1.sinaimg.cn/large/006Xmmmggy1g5tgrjxfvdj309j0demxx.jpg)

Forum link here:
https://bbs.deepin.org/forum.php?mod=viewthread&tid=181702

**Comment by BLumia** [comment]
Consider switch to another GTK theme (the official deepin theme for example) and check if it still happens?

**Comment by fanhengyuan** [comment]
@BLumia Thanks Reply.
I changed to the default settings, This problem will also appear.
I have both computers with this problem, even if I try to reinstall the system.
How should I check the `dde-kwin` version?

## Screenshots
![1](https://tva1.sinaimg.cn/large/006Xmmmggy1g5vjd1zfzsg31dm0lnk3b.gif)

![2](https://tva1.sinaimg.cn/large/006Xmmmggy1g5vjf2nfpuj30b20kegmy.jpg)

**Comment by BLumia** [comment]
> How should I check the dde-kwin version?

`apt policy dde-kwin` :)

**Comment by fanhengyuan** [comment]
My company computer:
```
$ apt policy dde-kwin
dde-kwin:
  已安装：0.1.0-1+comsta
  候选： 0.1.0-1+comsta
  版本列表：
 *** 0.1.0-1+comsta 500
        500 https://mirrors.aliyun.com/deepin stable/main amd64 Packages
        100 /var/lib/dpkg/status

```

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
