### ISSUE TITLE
Bug : Deepin Notifications at times keep repeating ... stuck on the screen ... no way to get rid ..

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1498]
This is not a recent observation, has been the case over right from the time i started using Deepin ... 

Ideally Deepin Notification bubbles should show up briefly and disappear ... but there are instances where they are rigid and don't vanish ... some times they keep looping(the same notification reappearing again and again)

an example where they are stuck on the screen spoiling the screen view ...
![image](https://user-images.githubusercontent.com/3283676/62830036-09753980-bc25-11e9-8e8d-d6d6af47ab64.png)

an example where its rigid and doesn't vanish ...
![image](https://user-images.githubusercontent.com/3283676/62830042-20b42700-bc25-11e9-82dc-a936b5eda279.png)

an example of looping even though its not in the notification list ... seems like some old notification keeps popping way after the first instance of it ...
![image](https://user-images.githubusercontent.com/3283676/62830047-5d801e00-bc25-11e9-85de-a7014c7eb427.png)

Note ... this behaviour is mostly encountered with notifications of the package qBittorrent ...

A suggestion/enhancement ... **how about adding a close button to the notification bubble popup ?**

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
