### ISSUE TITLE
Request Features In Image Viewer.

### ISSUE THREAD

**Issue by sarojpoudel33** [linuxdeepin/developer-center#1499]
Can We Provide PDF Viewer In Imager Viewer? Only Read Only Like MacOS.

## Describe the bug
This Features help us to be an Independent.

## To Reproduce

-->

**Comment by sarojpoudel33** [comment]
@hualet @BLumia Thank for Response.

**Comment by sarojpoudel33** [comment]
Can We Provide PDF Viewer In Deepin Image Viewer? Read Only! Like MacOS.

**Comment by BLumia** [comment]
Since PDF is not a image file, I guess no? cc @wangjia12

**Comment by sarojpoudel33** [comment]
https://support.apple.com/guide/preview/view-pdfs-and-images-prvw11470/mac
Have a look @BLumia

**Comment by alexwender1** [comment]
We now have WPS PDF (but haven't removed Evince from .iso). Another complaint: https://github.com/linuxdeepin/developer-center/issues/1353

The proposal of @sarojpoudel33 is interesting; having a Deepin Apps compatible with the .pdf view.

Alternatively, you can view .pdf (local / downloaded) files directly in your web browser.
