### ISSUE TITLE
multi user no password textbox at login

### ISSUE THREAD

**Issue by LorenzoGas** [linuxdeepin/developer-center#1500]
## Describe the bug
Missing user login password text box at boot (more than one account), the issue occurs only with the old user, the new user can log in.

## To Reproduce
create a new user, shutdown/reboot, can only log in with last user account because there is no way to insert the password with the old account

## Expected behavior
have a password text box for all the users 

## Screenshots
the issue is described with pictures here https://forum.manjaro.org/t/manjaro-deepin-no-password-box-popup-in-login-screen/98491

## Distro & Version
Manjaro with deepin 15.10.1

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
