### ISSUE TITLE
希望deepin能够wine一下迅雷X

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1502]
## 缺陷描述

为什么要wine迅雷X呢，因为现在极速迅雷不支持高分屏，高分屏下很难受，而迅雷X支持2k、4k高分屏，而且迅雷X是最新版本软件，不太容易出现，下载失败的情况。

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
