### ISSUE TITLE
Deepin Movie : running more than one instance of the application

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1503]
Hi,

Given that we now live in multi monitor, multi workspace environments of Linux ... Doesn't it make sense that Deepin Movie too had the option of running multiple instances of the application ?

a Use Case where it applies ...

Say a user watch movies ... and he watches TV Shows ... Also he may watch educational tutorials ...

The current multiworkspaces and multi monitor designs help us to have the above activities set out on separate workspaces/monitors ... but the Deepin Movie and its lack of running multiple instances messes the above use case.

The team might want to consider allowing running of multiple instances of Deepin Movie ...

The whole idea of a multiworkspace/monitor system is so the user can switch and continue from where he left ... Deepin Movie with a multiple instance running will further enable this system.

**Comment by BLumia** [comment]
> Doesn't it make sense that Deepin Movie too had the option of running multiple instances of the application ?

If you take a look at the deepin-movie setting dialog you can see there is an option about enable this feature :)

![image](https://user-images.githubusercontent.com/10095765/63206897-dbde3380-c0ef-11e9-80aa-206ea8757007.png)

**Comment by aiamuzz** [comment]
:open_mouth:  ...
hahahahahaah ... i didn't know that ... should have checked before opening this post ... 
thanks.
