### ISSUE TITLE
Deepin Movie : Enhancement - Ability to create playlist and save them ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1504]
Hi,

In continuation to the #1503 request ... wouldn't it make sense to have the ability of creating and saving different playlists ... This particularly will greatly aid and enhance the educational tutorials viewing / managing experience ...

Use Case ... 

We live in a age where videos are saved based on topics ... if Deepin Movie would allow us to create and save playlist of the videos on such topics ... it would be a breeze to open those playlists and launch the tutorials for a particular topic/subject.

Cheers.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
