### ISSUE TITLE
Deepin Movie : Enhancement - Ability to launch Deepin Movie when a previously saved playlist is double clicked ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1505]
Hi,

In continuation to to #1503 & #1504 ... If these 2 requests are adopted ... it would be really great to have the ability to launch a previously saved playlist directly from the file manager ... as against opening the Deepin Movie application and browsing to the path where the playlist is saved and loading it !

Cheers.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
