### ISSUE TITLE
Deepin Movie : Enhancement - Deepin Movie playlist content ... deleting the orange entries automatically ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1506]
Hi,

Currently Deepin Movie Playlist has entries of added videos or previously watched videos ...

The videos that are still on disk are shown as playable but those videos that are deleted from the disk after watching show up as red/orange entries ...

![image](https://user-images.githubusercontent.com/3283676/63001776-fc10b700-be91-11e9-8312-8ccc09aa48e8.png)

Wouldn't it be a nice idea to remove those red/orange entries automatically once they are no longer on the disk(or at the path where they were originally present when it was first watched) ... 

Automatically dropping them would be nice ... if that's difficult to achieve then an option in the playlist right click menu can have an additional entry to clear playlist of these disconnected(red/orange) entries ... We already have an option called 'Clear Playlist' ... and option called 'Clean Playlist' could be a great enhancement and ease a user workflow while using Deepin Movie.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
