### ISSUE TITLE
dock的问题

### ISSUE THREAD

**Issue by 90du** [linuxdeepin/developer-center#1507]
## 缺陷描述

dock设置自动隐藏然后点击显示过程有问题

## 期望行为

期待能好好优化下dock的动画，不期望macos那样流畅，起码要不卡顿，不出现肉眼能看见的问题吧
## 截图

![深度录屏_选择区域_20190814222316](https://user-images.githubusercontent.com/35375370/63029235-c47e2b00-bee2-11e9-80b6-c9fbf96e35e7.gif)

**Comment by BLumia** [comment]
这也不是卡顿啊..看上去是模糊区域先被指定好了，但是dock窗口由于需要动画，还没移动到对应的位置。

dock 无论是代码结构还是界面上，后续都会有较大的改动，目前的版本不会处理这个问题了，不过还是感谢汇报问题～
