### ISSUE TITLE
文件管理器多标签功能 file manage multi tabs

### ISSUE THREAD

**Issue by lizhuangs** [linuxdeepin/developer-center#1508]
## [Feature Request]文件管理器多标签功能
文件管理器多标签功能什么时候出来，可以参考win下面的clover那样简单的就可以了。但我相信深度的会更好看，等了太久了。

**Comment by BLumia** [comment]
这个功能一直都有啊，按<kbd>Ctrl+T</kbd>就可以新建标签了，在侧边栏和文件夹右键也都可以在新标签中打开。
