### ISSUE TITLE
Icon Theme Issues (Deepin Dark)

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#1511]
## Describe the bug
Some icons are not adapted to the dark icon theme. With the extension .AppImage, .pptx; .url.
Dialog screens also do not have the dark theme.

## Screenshots
![Captura de Tela_Área de Seleção_20190812143408](https://user-images.githubusercontent.com/45263160/63104432-5e7ebb80-bf55-11e9-9c97-d7e3192ec914.png)
![Captura de Tela_Área de Seleção_20190812143135](https://user-images.githubusercontent.com/45263160/63104435-5f175200-bf55-11e9-9e8d-1fa55b4a6de0.png)
![Captura de Tela_Área de Seleção_20190812144040](https://user-images.githubusercontent.com/45263160/63104436-5f175200-bf55-11e9-8cac-08f7a82d1f5a.png)
![Captura de Tela_Área de Seleção_20190812160228](https://user-images.githubusercontent.com/45263160/63104438-5f175200-bf55-11e9-9c3c-c3d770066b62.png)
![Captura de Tela_Área de Seleção_20190812165759](https://user-images.githubusercontent.com/45263160/63104434-5f175200-bf55-11e9-9e7d-ca1a8d74cfa3.png)

### Distro & Version
Deepin 15.11 (Lion)

**Comment by BLumia** [comment]
Two different issue:

Maybe deepin-dark theme are missing some icons.

Dialogs will got its theme support in the next big version release :)

**Comment by alexwender1** [comment]
Another addition to the problem (device removed notification).

![Captura de Tela_Área de Seleção_20190825182351](https://user-images.githubusercontent.com/45263160/63656032-c909d580-c765-11e9-8d93-dbb3bb76fb9b.png)
