### ISSUE TITLE
应用商店窗口最大化的情况下还是会被系统任务栏遮挡一小部分

### ISSUE THREAD

**Issue by lidanger** [linuxdeepin/developer-center#1513]
## 缺陷描述

应用商店窗口最大化的情况下还是会被系统任务栏遮挡一小部分，没道理啊

## 截图

![深度截图_20190720122454](https://user-images.githubusercontent.com/4464921/63326833-a2abfa80-c35f-11e9-87a7-5ff973fcfe86.png)

### 发行版以及版本

deepin 15.11 stable

### 相关的软件包版本

deepin-appstore 5.3.1.0-1

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
