### ISSUE TITLE
终端-远程管理-添加服务器，名称不同 IP 相同会覆盖原有的相同 IP 的配置

### ISSUE THREAD

**Issue by lidanger** [linuxdeepin/developer-center#1514]
## 缺陷描述

终端-远程管理-添加服务器，名称不同 IP 相同会覆盖原有的相同 IP 的配置，不知道算不算 bug。

### 发行版以及版本

deepin 15.11 stable

### 相关的软件包版本

deepin-terminal 3.2.7.1-1

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
