### ISSUE TITLE
建议启动器布局再增加固定常用软件图标到最顶端的功能，减少点击

### ISSUE THREAD

**Issue by lidanger** [linuxdeepin/developer-center#1515]
## 缺陷描述

建议启动器布局再增加固定常用软件图标到最顶端的功能，减少点击。

毕竟，同一个功能，点两次以上才能访问，与点一次就能访问的感受大大不同。更不要说，点了之后进去还要找一会儿。
而搜索什么的，对于不常用的东西很方便，但对常用的来说体验就差远了。毕竟要用脑子回忆，脑子有惰性，一用脑子就会增加痛苦感。
还有那个打开过的软件记录，也不知道排列规则是什么。增加得太多了，找起来也不方便。

## 期望行为

期望可以将启动器中的软件图标固定到最顶端或什么显眼的位置，而不是现在的使用记录会越来越多。
或者在最近打开软件记录中可以设置置顶也不错。当然，希望设计师再设计设计。

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
