### ISSUE TITLE
wine 版软件的对话框长期不关闭，常常跑到主界面后面，没法选择

### ISSUE THREAD

**Issue by lidanger** [linuxdeepin/developer-center#1517]
## 缺陷描述

wine 版软件切换后对话框长期不关闭，常常跑到主界面后面，如选择文件对话框，没法选择，只能用快捷键切换窗口或强制关闭进程。

### 发行版以及版本

deepin 15.11 stable 

### 相关的软件包版本

dde 2019.07.11

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
