### ISSUE TITLE
自带的编辑器修改保存 windows 下文本文件时可能出现截断文件的情况

### ISSUE THREAD

**Issue by lidanger** [linuxdeepin/developer-center#1518]
## 缺陷描述

自带的编辑器修改保存 windows 下文本文件时可能出现截断文件的情况，几M的文件可能变成几百K。

## 复现环境:

文本文件在 ntfs 分区上

### 发行版以及版本

deepin 15.11 stable 

### 相关的软件包版本

deepin-editor 1.2.9.1-1

**Comment by BLumia** [comment]
无法复现。

不提供复现方式我们没法修啊...

**Comment by lidanger** [comment]
那就先关了吧，等我再找到相关文件的时候，传上来你们再修。先前的文件我已经用别的编辑器编辑过了。

@BLumia
