### ISSUE TITLE
Deepin File Manager suddenly close

### ISSUE THREAD

**Issue by uisyudha** [linuxdeepin/developer-center#152]
I have installed deepin in arch linux in new deepin version the dde file manager suddenly close when open folder that contains video file. 

The kernel message said : 
![image](https://cloud.githubusercontent.com/assets/25357230/22315573/1856e46e-e39a-11e6-8066-b68cedcccf3b.png)

How to fix this?

**Comment by felixonmars** [comment]
Should have been fixed in deepin-file-manager-1:1.3.8-2.

**Comment by uisyudha** [comment]
yeah thanks, its working
