### ISSUE TITLE
Enable horizontal scrolling by default

### ISSUE THREAD

**Issue by douglara** [linuxdeepin/developer-center#1522]
## Describe the bug
By default Deepin does not come with a touchpad enabled to perform horizontal scrolling, this generates a poor experience in places that have horizontal scrolling.

## To Reproduce
1 - Open Deepin Editor
2 - Disable line break by going to settings and uncheck line break in "Basic"
3 - Write a large line that activates the vertical scroll
4 - Try using a horizontal scroll on the touchpad.
5 - To enable this, open a terminal and run: synclient HorizTwoFingerScroll = 1
6 - Now try the vertical scroll again in the Deepin editor.

## Expected behavior

Horizontal scrolling enabled by default.
Today I solved in my version of deepin but I wish other people had this ability too.
## Screenshots

![Captura de Tela_selecionar área_20190822232311](https://user-images.githubusercontent.com/14988496/63562414-e9eae480-c533-11e9-8df6-69444bfde202.png)

### Distro & Version
Linux Deepin 15.10.1

### Additional context

Sorry if I raised in the wrong place, if yes just direct me to the right place
Thanks!

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
