### ISSUE TITLE
Chrome Apps icons now are all like Google Chrome

### ISSUE THREAD

**Issue by lolimay** [linuxdeepin/developer-center#1523]
The problem of issue #394 reproduced :(

## Describe the bug

Please see #394 for detail

## Expected behavior

Should show this logo instead of google chrome icon
![image](https://user-images.githubusercontent.com/32427260/63599607-88d71580-c5f4-11e9-85bb-14dfb2517342.png)

## Screenshots

![image](https://user-images.githubusercontent.com/32427260/63599563-7230be80-c5f4-11e9-9acc-e50a550283e8.png)

### Distro & Version

Linux Deepin 15.11

### Related package version

- dde-launcher/panda,now 4.6.14+c1-1 amd64 
- dde-desktop/panda,now 4.8.8.2+c1-1 amd64 
- dde-kwin/panda,now 0.1.0-1 amd64

**Comment by lolimay** [comment]
Related information:

Icon | Icon to display in file manager, menus, etc. If the name is an absolute path, the given file will be used. If the name is not an absolute path, the algorithm described in the Icon Theme Specification will be used to locate the icon. | localestring | NO | 1-3
-- | -- | -- | -- | --


Ref: https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html

**Comment by lolimay** [comment]
[Icon Theme Specification- Icon Lookup algorithm](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html)

**Comment by lolimay** [comment]
The icon lookup mechanism has two global settings, the list of base directories and the internal name of the current theme. Given these, we need to specify how to lookup an icon file from the icon name, the nominal size, and the scale.

The lookup is done first in the current theme, and then recursively in each of the current theme's parents, and finally in the default theme called "hicolor" (implementations may add more default themes before "hicolor", but "hicolor" must be last). As soon as there is an icon of any size that matches in a theme, the search is stopped. Even if there may be an icon with a size closer to the correct one in an inherited theme, we don't want to use it. Doing so may generate an inconsistant change in an icon when you change icon sizes (e.g. zoom in).

The lookup inside a theme is done in three phases. First, all the directories are scanned for an exact match, e.g. one where the allowed size of the icon files matches what was looked up. Then all the directories are scanned for any icon that matches the name. If that fails we finally fall back on unthemed icons. If we fail to find any icon at all it is up to the application to pick a good fallback, as the correct choice depends on the context.

The exact algorithm (in pseudocode) for looking up an icon in a theme (if the implementation supports SVG) is:

```cpp
FindIcon(icon, size, scale) {
  filename = FindIconHelper(icon, size, scale, user selected theme);
  if filename != none
    return filename

  filename = FindIconHelper(icon, size, scale, "hicolor");
  if filename != none
    return filename

  return LookupFallbackIcon (icon)
}
FindIconHelper(icon, size, scale, theme) {
  filename = LookupIcon (icon, size, scale, theme)
  if filename != none
    return filename

  if theme has parents
    parents = theme.parents

  for parent in parents {
    filename = FindIconHelper (icon, size, scale, parent)
    if filename != none
      return filename
  }
  return none
}
```

With the following helper functions:

```cpp
LookupIcon (iconname, size, scale, theme) {
  for each subdir in $(theme subdir list) {
    for each directory in $(basename list) {
      for extension in ("png", "svg", "xpm") {
        if DirectoryMatchesSize(subdir, size, scale) {
          filename = directory/$(themename)/subdir/iconname.extension
          if exist filename
	    return filename
        }
      }
    }
  }
  minimal_size = MAXINT
  for each subdir in $(theme subdir list) {
    for each directory in $(basename list) {
      for extension in ("png", "svg", "xpm") {
        filename = directory/$(themename)/subdir/iconname.extension
        if exist filename and DirectorySizeDistance(subdir, size, scale) < minimal_size {
	   closest_filename = filename
	   minimal_size = DirectorySizeDistance(subdir, size, scale)
        }
      }
    }
  }
  if closest_filename set
     return closest_filename
  return none
}

LookupFallbackIcon (iconname) {
  for each directory in $(basename list) {
    for extension in ("png", "svg", "xpm") {
      if exists directory/iconname.extension
        return directory/iconname.extension
    }
  }
  return none
}

DirectoryMatchesSize(subdir, iconsize, iconscale) {
  read Type and size data from subdir
  if Scale != iconscale
     return False;
  if Type is Fixed
    return Size == iconsize
  if Type is Scaled
    return MinSize <= iconsize <= MaxSize
  if Type is Threshold
    return Size - Threshold <= iconsize <= Size + Threshold
}

DirectorySizeDistance(subdir, iconsize, iconscale) {
  read Type and size data from subdir
  if Type is Fixed
    return abs(Size*Scale - iconsize*iconscale)
  if Type is Scaled
    if iconsize*iconscale < MinSize*Scale
        return MinSize*Scale - iconsize*iconscale
    if iconsize*iconscale > MaxSize*Scale
        return iconsize*iconscale - MaxSize*Scale
    return 0
  if Type is Threshold
    if iconsize*iconscale < (Size - Threshold)*Scale
        return MinSize*Scale - iconsize*iconscale
    if iconsize*iconsize > (Size + Threshold)*Scale
        return iconsize*iconsize - MaxSize*Scale
    return 0
}
```

In some cases, you don't always want to fall back to an icon in an inherited theme. For instance, sometimes you look for a set of icons, preferring any of them before using an icon from an inherited theme. To support such operations implementations can contain a function that finds the first of a list of icon names in the inheritance hierarchy. I.E. It would look something like this:

```cpp
FindBestIcon(iconList, size, scale) {
  filename = FindBestIconHelper(iconList, size, scale, user selected theme);
  if filename != none
    return filename

  filename = FindBestIconHelper(iconList, size, scale, "hicolor");
  if filename != none
    return filename

  for icon in iconList {
    filename = LookupFallbackIcon (icon)
    if filename != none
      return filename
  }
  return none;
}
FindBestIconHelper(iconList, size, scale, theme) {
  for icon in iconList {
    filename = LookupIcon (icon, size, theme)
    if filename != none
      return filename
  }

  if theme has parents
    parents = theme.parents

  for parent in parents {
    filename = FindBestIconHelper (iconList, size, scale, parent)
    if filename != none
      return filename
  }
  return none
}
```

This can be very useful for example when handling mime-type icons, where there are more and less "specific" versions of icons.

**Comment by BLumia** [comment]
Probably caused by the `libqt5xdg3` package, could you try if `qtxdg-iconfinder` can return the correct result?

**Comment by lolimay** [comment]
Thanks, I tried `qtxdg-iconfinder` but it not worked. Does it is an executable binary program? It's nice for me to wait for new `buster` repo release to fix problem.

**Comment by lolimay** [comment]
reopen it for tracking

**Comment by BLumia** [comment]
Whooops, it's a part of `qtxdg-dev-tools` but it seems this package is not available in the stretch / deepin lion package repo, sorry my wrong :joy:

If I remember correctly deepin backported some libqt5xdg3 patches to deepin lion, I'm not quite sure if that solved this issue. Maybe you can try build and install it from source and check if newer version can fix this issue :)

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
