### ISSUE TITLE
bug: dde-session-daemon doesn't detect audio settings

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#1525]
## Describe the bug

Sometimes, after starting the computer I notice that I can't increase nor decrease the volume from the dock because the volume button is missing.
But if I manually restart the `dde-session-daemon`, then the volume button appears and then I can change the volume again.

## To Reproduce

1. Start the computer.
2. You will notice that the volume button is missing.
## Expected behavior

The volume button should always be there.

### Distro & Version

Distro: Archlinux
### Related package version

`deepin-daemon`  v5.0.0-2

**Comment by Mark-AAAA** [comment]
Just downgrade that extremely buggy and broken update back to deepin-daemon to 3.28.0.
https://github.com/linuxdeepin/developer-center/issues/1509
https://github.com/linuxdeepin/developer-center/issues/1490
 https://github.com/linuxdeepin/developer-center/issues/1470
From [here](http://delta.archlinux.fr/pool-backup/deepin-daemon-3.28.0-1-x86_64.pkg.tar.xz) you can download it, pre-compiled so you can install it easily with a click if you have pamac!

**Comment by SiamSami** [comment]
Fixed
