### ISSUE TITLE
bug: dde-file-manager shows hard drives incorrectly

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#1526]
## Describe the bug

Deepin file manager sometimes shows the partitions of hard drives incorrectly.

## To Reproduce

1. Start the computer
2. Open Deepin file manager
3. See the error

## Screenshots

![DeepinScreenshot_select-area_20190825184008](https://user-images.githubusercontent.com/33563064/63650099-c6f54600-c768-11e9-8230-51d1f616709e.png)

### Distro & Version

Distro: Archlinux
### Related package version

`dde-file-manager` v1:5.0.0-1
`deepin-kwin` v0.1.0-1
### Additional context

In the above picture, all those partitions are actually internal disks.
I think it's happening because of `deepin-kwin`. Before switching to this wm, I used to use `deepin-mutter` and I never got this type of glitch back at that time.

**Comment by aiamuzz** [comment]
do you mean the icon next to the disks in the disk list panel on the left ?
or
are you referring to the UID showing up instead of the disk label ?

**Comment by SiamSami** [comment]
@aiamuzz Both

**Comment by BLumia** [comment]
Did you check if you renamed your partition label the same as its uuid? Did nautilus display the same result? Thanks.

**Comment by SiamSami** [comment]
@BLumia 
1. No, I did not rename my partition label the same as its UUID.
2. Yes, Nautilus displayed the same result.
And by the way, this glitch happens sometimes only. Not all the time.

**Comment by BLumia** [comment]
> Yes, Nautilus displayed the same result.

Then it's a gio issue and restart your gvfsd can be a workaround :)

**Comment by SiamSami** [comment]
Looks like it has been fixed.
