### ISSUE TITLE
Bug:deepin的缩放，放大以后有，lyx，teamviewer等软件出现虚化现象，我提出以下两点解决方案

### ISSUE THREAD

**Issue by deepincold** [linuxdeepin/developer-center#1527]
第一，相对容易的解决方案，提供不同应用程序是否参与缩放的选项，不缩放的程序可以自行选择，不缩放的话就不会导致软件发虚严重的问题。
第二，对字体进行算法处理，显示时不直接放大，而是在原有的像素放大后进行插值算法，拟合出清晰的字体。
由于虚化严重，影响体验，导致现在在1080*1920的屏幕只能用1.0倍率，并不舒适，该分辨率最适合1.25倍率的缩放，望尽早修复。

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
