### ISSUE TITLE
[Feature  request] Folders

### ISSUE THREAD

**Issue by Mark-AAAA** [linuxdeepin/developer-center#1528]
Could you provide such a function for folders view?
From KDE Neon:
![deepin-screen-recorder_plasmashell_20190828212133](https://user-images.githubusercontent.com/52075807/63882660-22c70580-c9db-11e9-9f27-260e62fcb99d.gif)

**Comment by keybreak** [comment]
Ain't it overkill functionality?

I pesonally don't see why, since you can open those folders in file manager with pretty much same result...

**Comment by Mark-AAAA** [comment]
Never mind I've switched to kde neon.
