### ISSUE TITLE
Add Icon Theme

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#1529]
I suggest adding - natively - 2 icon packs to the system:

[**Candy Icon**](https://github.com/EliverLara/candy-icons) - popular in KDE.
![image](https://user-images.githubusercontent.com/45263160/64057175-250e9880-cb70-11e9-9b7a-6984c0b748ac.png)

[**Dexter Icon**](https://repositorio.deepines.com/pub/deepines/pool/main/d/dexter-icon-theme/) - developed by the [Deepin en Español Community](https://deepinenespañol.org/dexter-un-hermoso-pack-de-iconos-para-deepin/);
![image](https://user-images.githubusercontent.com/45263160/64057171-1cb65d80-cb70-11e9-80c0-5ede13b4e7dd.png)

### Additional context
The **Papirus Icon Theme** doesn't seem "compatible" with Deepin - it doesn't have the same beauty of the system. Personally, I find it valid to remove it from the system.

**Comment by BLumia** [comment]
Hi and you can check if they are already in the debian buster package repo, if it is, then you can use them in the next big version upgrade :)
