### ISSUE TITLE
Grub2 daemon clears all my settings in /etc/default/grub

### ISSUE THREAD

**Issue by avently** [linuxdeepin/developer-center#153]
There is a Grub's config file located at /etc/default/grub. I'm adding some config at
GRUB_CMDLINE_LINUX_DEFAULT=...
But after two restarts grub menu is rebuilding automatically and my changes just removes. I can not make a permanent change to /etc/default/grub because your deepin-daemon changes this file in incorrect way. Take a look at the logs:

00:40:18 dbus-daemon: <error> grub2ext.go:122: get image size failed, /boot/grub/themes/deepin/background_source
00:40:18 dbus-daemon: <info> grub2.go:138: update loop started
00:40:18 dbus-daemon:   ->  grub2.go:96
00:40:18 dbus-daemon: <error> theme.go:101: open /boot/grub/themes/deepin/theme_tpl.json: no such file or directory
00:40:18 dbus-daemon:   ->  grub2.go:96
00:40:18 dbus-daemon: <error> theme.go:173: open /boot/grub/themes/deepin/theme_tpl.json: no such file or directory
00:40:18 dbus-daemon: [system] Successfully activated service 'com.deepin.daemon.Grub2Ext'
00:40:17 dbus-daemon: [system] Activating service name='com.deepin.daemon.Grub2Ext' (using servicehelper)
00:40:17 grub2: grub2.go:104: open /boot/grub/grub.cfg: permission denied
  ->  grub2.go:95
  ->  module.go:39
  ->  main.go:80
  ->  main.go:67
  ->  proc.go:183
  ->  asm_amd64.s:2086
00:40:17 dbus-daemon:   ->  grub2.go:95
00:40:17 dbus-daemon: <error> grub2.go:104: open /boot/grub/grub.cfg: permission denied
00:40:17 grub2: grub2.go:189: open /boot/grub/grub.cfg: permission denied
  ->  grub2.go:102
  ->  grub2.go:95
  ->  module.go:39
  ->  main.go:80
  ->  main.go:67
  ->  proc.go:183
  ->  asm_amd64.s:2086
00:40:17 dbus-daemon:   ->  grub2.go:95
00:40:17 dbus-daemon:   ->  grub2.go:102
00:40:17 dbus-daemon: <error> grub2.go:189: open /boot/grub/grub.cfg: permission denied
00:40:17 grub2: config.go:53: config file: /var/cache/deepin/grub2.json
00:40:17 dbus-daemon: <info> config.go:53: config file: /var/cache/deepin/grub2.json
00:40:17 dbus-daemon: Successfully activated service 'com.deepin.daemon.Grub2'
00:40:17 dbus-daemon: Activating service name='com.deepin.daemon.Grub2'

Something bad, right? I really need to add GRUB_CMDLINE_LINUX_DEFAULT ...

**Comment by avently** [comment]
Maybe someone can answer me?

**Comment by funilrys** [comment]
@avently what's your distribution? Are you sure you have root access ? Did you ran `grub-mkconfig -o /boot/grub/grub.cfg` ? I think your issue is actually incomplete ...

**Comment by avently** [comment]
Of course i have root access:) I just disabled Grub2 service and the problem disappeared. So, yes, it is Deepin related. 
My system is Manjaro Deepin, Arch based. 
What i did:
sudo nano /usr/share/dbus-1/services/com.deepin.daemon.Grub2.service
then i commented all lines and saved the file. I should do this every dde-daemon's update.
Now after restart this service does not wipe my configuration. 
Maybe you can take a look closer on the source?

**Comment by funilrys** [comment]
cc @oberon2007

**Comment by oberon2007** [comment]
This is very strange! I had no idea and I think it's definitely not right that deepin-daemon should mess with **/etc/default/grub** under Archlinux. I assume this has to do with customizing the grub screen in dde-control-center, which is a feature that will not work anyway in Manjaro afaik and I doubt it does in pure Archlinux, does it?

**Comment by funilrys** [comment]
I tried it from the control center but it doesn't seem to work on fresh install... I personally use grub-customizer for such things under arch :) 

cc @hualet Do I have to create an issue about it or not?

**Comment by avently** [comment]
Now config exists after a few restarts. Issue can be closed. Thank you!
