### ISSUE TITLE
[Feature Request] Change Monitor Refresh Rate in Settings

### ISSUE THREAD

**Issue by MasterJubei** [linuxdeepin/developer-center#1530]
## Expected behavior
Being able to change the refresh rate per monitor in the monitor settings

This would be a welcome addition. For new Linux users, it is important to keep them away from the terminal. This is most useful for people with 120hz+ monitors, Deepin in my experience defaults to 60hz even if a monitor supports a higher refresh rate.

**Comment by glossed** [comment]
Bumping this because this is way overdue in my opinion.

**Comment by meiyixiang** [comment]
We will give that some refresh rate based on the current resolution options, the default choice the most recommended refresh rate, if there is no recommended the refresh rate is the default choice high refresh rate.
