### ISSUE TITLE
lion源中，linux-libc-dev:i386这个包版本不对

### ISSUE THREAD

**Issue by izee** [linuxdeepin/developer-center#1531]
## 缺陷描述
无法安装linux-libc-dev:i386包，当前源中linux-libc-dev:i386的版本，与linux-libc-dev不匹配，导致apt的安装方案会卸载linux-libc-dev包。

## 复现步骤
sudo aptitude install linux-libc-dev:i386

## 期望行为
更新安装源中linux-libc-dev:i386包的版本

### 发行版以及版本
Linux Deepin 15.11

### 相关的软件包版本
linux-libc-dev:i386 (4.9.130-2)

**Comment by ihipop** [comment]
我也是这个问题，操作以后没注意按了回车，然后还修复不了，然后然把我把系统重装了
@BLumia

**Comment by BLumia** [comment]
@deepinzhangshuang @hualet

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
