### ISSUE TITLE
Window Effect Issue on 15.11

### ISSUE THREAD

**Issue by furkanydn** [linuxdeepin/developer-center#1532]
When the use of ram is forced, the window effect is turned off.
I was getting 'failed to window effect' error when I tried to open the window effect from the settings on 15.11

## Solution
You need to open the file "kwinrc" in the main directory and type "Enabled = true" under the "BorderActivate =" line, then change the file extension to "kwinrc.backup" and restart the computer.

### Distro & Version
Linux Deepin 15.11

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
