### ISSUE TITLE
Deepin terminal with color emojis

### ISSUE THREAD

**Issue by peter-developer** [linuxdeepin/developer-center#1533]
I have a question, why if deepin-terminal in ubuntu 18.04, 19.04,  debian 10 etc .. supports color emojis but in official deepin it has no support, does it have to do with some library of outdated debian 9? Does this mean we will have to wait for deepin based on debian 10? (post-data: by the time they plan to take out that deepin).

**Comment by BLumia** [comment]
![image](https://user-images.githubusercontent.com/10095765/64308167-f3139100-cfca-11e9-808d-be3959aacd07.png)

I don't have deepin lion installed so I'm not able to test, but the deepin-terminal from debian buster based deepin package repository (not yet ready for release) works fine with emoji :D

**Comment by peter-developer** [comment]
everything indicates that if I have to wait for deepin with debian 10 base thz
