### ISSUE TITLE
[Feature Request] Option to group a newly opened file manager to existing window

### ISSUE THREAD

**Issue by Vigilans** [linuxdeepin/developer-center#1534]
## Motivation
Currently, dde file manager could use `Ctrl + T` to open a new tab in current window, while using `Super + E` will just open a new window.

I'm familiar with using `Super + E` to pop up the file manager, and it does not require a file manager window currently being focused. 

So, would it be possible to provide an option, to make dde file manager try to group into an existing window when created? Thus the exec command used in `.desktop` file can be changed to achieve the expectation.

### Distro & Version
Linux Deepin 15.10

### Related package version
dde-file-manager 4.8.8.1

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
