### ISSUE TITLE
Folder which have & symbol in name looks like _ in addressbar's breadcrumbs

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#1535]
![image](https://user-images.githubusercontent.com/47599989/64279806-8069cd80-cf58-11e9-8b32-92ac5a0ca8c9.png)

**Comment by BLumia** [comment]
Did a quick check of the v20 file manager and this bug is no longer exists :D 

You can still leave this issue open until we release the v20 file manager :)

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
