### ISSUE TITLE
desktop menu won't apper after loggin user

### ISSUE THREAD

**Issue by AnnisaNurika** [linuxdeepin/developer-center#1536]
I use deepin os 15.11, grub appears and after logging in the desktop display only loads cursos, the desktop menu won't appear. how to solve it?

**Comment by BLumia** [comment]
I guess you can google `grub nomodeset` and try the search result?

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
