### ISSUE TITLE
dde-launcher 无法显示 ~/.local/share/applications/ 目录 exec 指向非系统盘的 *.desktop

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#1537]
## 缺陷描述
dde-launcher 无法显示 ~/.local/share/applications/ 目录exec指向非系统盘的 *.desktop

## 复现步骤
系统启动必现，理论上重启 dde-launcher 应该重新生成列表，然而并没有，说明有缓存或者后台。
应该是列表在非系统盘挂载前生成造成的，即启动顺序问题，类似的还有搜狗输入法设置丢失。

## 期望行为
显示 ~/.local/share/applications/ 路径下所有 desktop

## 复现环境:
路径：~/.local/share/applications/
desktop：exec=非系统盘的程序

### 发行版以及版本
Linux Deepin 15.11

### 相关的软件包版本
dde-launcher/panda,now 4.6.14+c1-1 amd64

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
