### ISSUE TITLE
What is the keyboard shortcut to move application window from one monitor

### ISSUE THREAD

**Issue by thissayantan** [linuxdeepin/developer-center#1538]
I was looking for to move an application window from one monitor to another with a keyboard shortcut. Tried couple of different ways. 

1. https://unix.stackexchange.com/a/517192
2. gsettings set com.deepin.wrap.gnome.desktop.wm.keybindings move-to-monitor-left '["<Super><Shift>Left"]'

gsettings set com.deepin.wrap.gnome.desktop.wm.keybindings move-to-monitor-right '["<Super><Shift>Right"]'

Didn't really worked. Can anyone please help ?

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
