### ISSUE TITLE
Last couple of updates pushed seems to have broken printing ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1539]
Hi,

I ran 2 updates inside of a week ... and it turns out printing to a network printer is broken ...

I have another older version of Linux Deepin in a multiboot setup ... printing is working just fine over there ... which rules out any problem with my printer or the network.

Could someone please help fix this issue ?

Cheers.

**Comment by aiamuzz** [comment]
@hualet ... @BLumia ...

so many issues i have reported ... seems they are unattended ... can somebody at least help troubleshoot them ...

serious issues like ...

[Dock showing on only one of the workspace !](https://github.com/linuxdeepin/developer-center/issues/1389)

[Bug : Top-right corner Close Button issue 2/2 ... mere mouse over the top-right hot corner is closing maximized windows ...](https://github.com/linuxdeepin/developer-center/issues/1394)

[Bug : Top-right corner Close Button. the orange 'x' marked button is not showing ... ](https://github.com/linuxdeepin/developer-center/issues/1395)

along with this current printing broken issue ... these are more serious one's that affect the daily usability of the OS ... would appreciate if somebody looked into at least these critical one's !!!

**Comment by aiamuzz** [comment]
FYI ... in the hope to fixing this issue i removed the printing package `sudo apt-get remove system-config-printer` and reinstalled the same ... after reinstallation everytime i try to add a new printer it asks for the root password ... is this normal ? ... I don't recollect it asking before ... has my removing and reinstalling has resulted in this password prompt before adding a new printer ?

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
