### ISSUE TITLE
apply theming -change top bar of apps

### ISSUE THREAD

**Issue by pranavvv** [linuxdeepin/developer-center#1540]
### Additional context

![DeepinScreenshot_select-area_20190912101051](https://user-images.githubusercontent.com/34711035/64754324-940fc800-d546-11e9-8d2d-5d4d4d1fa319.png)
![DeepinScreenshot_select-area_20190912101125](https://user-images.githubusercontent.com/34711035/64754325-940fc800-d546-11e9-8551-f95871d78968.png)

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
