### ISSUE TITLE
Deepin 15.11 repo is based on oldstable Debian, not Debian 10

### ISSUE THREAD

**Issue by igormcoelho** [linuxdeepin/developer-center#1542]
## Describe the bug
From the news, I expected Deepin 15.11 to be using Debian 10 repositories (current stable), not Debian 9 (oldstable). As a result, I couldn't upgrade to newest applications, and even important ones, like newest firefox. This also caused many problems with docker and ros packages.
Main issue is that Deepin 15.11 is using libc 2.24, where a much newer version is expected, like 2.28 at least.

## To Reproduce
Install Deepin 15.11, and verify libc package: apt-cache show libc6

## Expected behavior
A newer version like 2.28 should be standard.

## Screenshots
none

### Distro & Version
Deepin 15.11

### Additional context
Please fix this, I believe this is a serious problem. News have misled people like me, that use Deepin from a long time, that the shift to Debian stable repo would bring nice improvements to the platform. Sticking to an old stable is terrible for user experience, and specially for those of us that are software developers... too obsolete packages may also bring several security issues.

**Comment by alexwender1** [comment]
The next version - Deepin 20 - will bring the Debian Buster base. There were contingencies that did not allow launching Deepin 15.11 with the Buster base.

As for Firefox, you can download it directly from the Mozilla website; that he has internal updater.

**Comment by igormcoelho** [comment]
@alexwender1 where can I know more from deepin launch timeline? Will it jump directly from 15.11 to 20?

**Comment by alexwender1** [comment]
> @alexwender1 thanks for the answer!
> Where can I know more from deepin launch timeline? Will it jump directly from 15.11 to 20?

It was posted on Twitter and the Forum by the team.

**Comment by igormcoelho** [comment]
May I ask you the specific tweet? Or at least the deepin account on twitter... I started now to follow @ linux_deepin, but couldn't find it there. And the link to the forum, if possible... usually I come directly here on github to fix things. Thanks a lot!

**Comment by BLumia** [comment]
The v20 release will be based on buster repo, it's not yet ready for release now :P

**Comment by alexwender1** [comment]
@BLumia The [release plan](https://deepin.org/en/developer-community/planning) needs to be updated! Some recurring questions can be addressed at that location (System Base, Kernel version, Nvidia Driver version, updated applications... and new functions).

**Comment by RMoroni** [comment]
@igormcoelho acho que eles estão falando desses posts: https://bbs.deepin.org/forum.php?mod=viewthread&tid=182036&extra=page%3D1 e https://bbs.deepin.org/forum.php?mod=viewthread&tid=181437&extra=page%3D1
no próprio fórum rola uma discussão sobre essa parada de ir para do 15.12 para 20, loucura haha

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
