### ISSUE TITLE
Adding new keyboard layout doesn't do anything

### ISSUE THREAD

**Issue by xster** [linuxdeepin/developer-center#1543]
## Describe the bug

After fresh install, adding a new keyboard layout in the same language is a no-op

## To Reproduce

Open the control panel, go to keyboards, (English US is present by default). 
Choose add layout. Select English (dvorak). The page pops back to the previous page but only English US is still present. No Dvorak added. 

## Expected behavior

Dvorak should be added after choosing dvorak in the layout to add page. 

### Distro & Version
15.11

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
