### ISSUE TITLE
Change keyboard layout shortcut doesn't work on lock screen

### ISSUE THREAD

**Issue by ahmadidev** [linuxdeepin/developer-center#1544]
I'm running Deepin Desktop 15.11. In the lock screen, changing keyboard layout using shortcuts `Alt + Shift` or `Win + Space` to enter password doesn't work.

**Comment by xepozz** [comment]
I have the same issue

**Comment by jhessin** [comment]
I have a bigger issue. I use programmer dvorak layout. It is set as that from boot and I log in with it, but when deepin's lock screen comes up it resets my keyboard layout to QWERTY for no apparent reason, and it stays that way even after I log back in.

**Comment by xmuli** [comment]
If possible, please upgrade to deepin v20 beta

**Comment by zmj1010** [comment]
Designed like this, the shortcut keys for switching languages are not available on the lock screen

**Comment by zmj1010** [comment]
Designed like this, the shortcut keys for switching languages are not available on the lock screen

**Comment by harshilletspresscontinue** [comment]
In my case the default keyboard is english but on lock screen it becomes hindi and then i have to restart a computer few times and out of 2-3 times once the keyboard is english and i am able to enter the password. Any solution for this?
