### ISSUE TITLE
深度音乐希望添加单曲播放一次就停止播放的功能

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1545]
## 缺陷描述

深度音乐3.1.18，现在有单曲循环、随机播放、列表循环3个播放选项，希望添加单曲一次的功能，这个功能比较实用，有时候我只想听一个歌，听一编就可以了，用单曲循环老是不停地播放，我都不知道什么时候歌曲播放完的。
### 发行版以及版本

deepin15.11

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
