### ISSUE TITLE
u盘卸载成功没有系统通知

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1547]
## 缺陷描述

如果我的u盘卸载成功应该提示“你的u盘可以安全拔出"类似的提示，这样用户感觉更好。
不应该等到用户拔出才提示，这样没有多少意义，如果这时候正在传输文件，用户拔出u盘提示”设备已被移除”有啥意义呢，损坏已经产生了。

### 发行版以及版本

deepin15.11

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
