### ISSUE TITLE
深度音乐添加了音乐文件以后没有自动排序

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1549]
## 缺陷描述

深度音乐我通过添加文件夹或者一次添加多个文件以后文件在列表中是随机排列没有自动排序，我每次都要选择如何排序，感觉麻烦，希望能够设置默认排序方法，默认如何排序。
设置如何排序希望设计的精细一点，是升序还是降序都可以指定，不要用户每次都点2次来排序。

### 发行版以及版本

deepin15.11

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
