### ISSUE TITLE
Accept pull requests?

### ISSUE THREAD

**Issue by 1dot75cm** [linuxdeepin/developer-center#155]
Deepin 不使用 github 作为主要的代码托管仓库。Fedora 打包需要修改一些 Makefile，所以，直接为这些项目提交 PR，可以被接受吗？ @hualet

**Comment by hualet** [comment]
我记得谁说gerrit有插件支持导入github PR，不过我们都是github单向同步gerrit的仓库的，还要试下看看有没有什么问题。另外，我们gerrit是对外公开的，可以直接在那上面提交CL的。

**Comment by 1dot75cm** [comment]
我注册了一个，然后 `git clone https://1dot75cm@cr.deepin.io/a/dde/dde-file-manager` 修改再提交，我应该没有权限提交吧？ @hualet

**Comment by Iceyer** [comment]
@1dot75cm   用git review，都有提交CL的权限。提交了找人给你submit一下就好了。

**Comment by 1dot75cm** [comment]
@lceyer 好的，我一会试试
