### ISSUE TITLE
文件打开方式中没有正确的选项可选

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1551]
## 缺陷描述

.local/share/applications中有firefox.desktop，而且开始菜单中可以搜索出firefox应用图标并正常打开firefox。
我想设置默认使用firefox打开html文件，但是发现打开方式-》选择默认程序中没有firefox选项，就算我选择添加应用程序，选择我在.local/share/applications中的firefox.desktop文件也不行，没有提示添加失败，但是还是没有firefox选项。
无奈我只有在选项应用程序的时候选择firefox安装目录的firefox可执行文件，这时候默认程序候选项中出现了firefox图标，但是这是不行的，我必须使用firefox.desktop在exec最后面添加%f参数才能正确打开html文件，不然只可以打开firefox不能打开html文件。
我附上我的firefox.desktop这个文件是我手写的。
[firefox.desktop.zip](https://github.com/linuxdeepin/developer-center/files/3635158/firefox.desktop.zip)

### 发行版以及版本

deepin15.11

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
