### ISSUE TITLE
After update of deepin-wm, the dde-dock is not shown.

### ISSUE THREAD

**Issue by carlosal1015** [linuxdeepin/developer-center#1552]
## Describe the bug

The following eventualities were presented, after an update. The deepin dock is not visualized, it became a dark theme.

Before the update I had deepin-wm with Mutter activated and after the update I have Metacity activated.

I have followed these instructions, but they have not worked.

- [Arch Linux Deepin: Dock has a plain black background ](https://github.com/linuxdeepin/developer-center/issues/316)
- [How to switch back to deepin-wm](https://github.com/linuxdeepin/developer-center/issues/1121)

## To Reproduce

1. Log in the session.
2. Scroll down to the dock.
3. The dock is not seen.

## Expected behavior

I would expect to see the dock at the bottom and that the theme of the system is normal and not very dark.

## Screenshots
![DeepinScreenshot_select-area_20190921113230](https://user-images.githubusercontent.com/21283014/65376255-6f60d200-dc63-11e9-87ef-47f234584237.png)
![DeepinScreenshot_select-area_20190921113439](https://user-images.githubusercontent.com/21283014/65376303-e26a4880-dc63-11e9-813c-416df7e634a7.png)
![DeepinScreenshot_select-area_20190921113448](https://user-images.githubusercontent.com/21283014/65376306-f44beb80-dc63-11e9-9429-125be4c2e3ca.png)
![DeepinScreenshot_select-area_20190921113527](https://user-images.githubusercontent.com/21283014/65376312-029a0780-dc64-11e9-836f-4fe01142bb79.png)

### Distro & Version

OS: Arch Linux x86_64
Shell: zsh 5.7.1
DE: Deepin
WM: Metacity
WM Theme: deepin
Theme: deepin [GTK2/3]
Icons: deepin [GTK2/3]
Terminal: deepin-terminal
GPU: Intel HD Graphics 620
### Related package version

Upgrade succesfully to
deepin-anything-arch (5.0.1-11 -> **5.0.1-12**)
gnome-desktop (1:3.32.2-1 -> **1:3.34.0-1**)
deepin-mutter (3.20.38-1 -> **3.20.38-2**)
deepin-wm (1.9.38-1 -> **1.9.38-2**)

### Additional context

Thanks :smile: :

**Comment by BLumia** [comment]
Hi, the old deepin-wm is deprecated and please consider install `deepin-kwin` package, DDE will use the new deepin-wm automatically next time you login into a new DDE session :)

**Comment by carlosal1015** [comment]
Hi @BLumia, thank you very much, naturally, I opted for [`deepin-kwin`](https://www.archlinux.org/packages/community/x86_64/deepin-kwin/), it was enough to install, it is amazing. voilà! Everything was fixed :)

![DeepinScreenshot_select-area_20190921132641](https://user-images.githubusercontent.com/21283014/65377692-37fb2100-dc75-11e9-9218-61bca1911bc4.png)
![DeepinScreenshot_select-area_20190921132656](https://user-images.githubusercontent.com/21283014/65377693-3d586b80-dc75-11e9-846a-7134ece8b7c3.png)
![DeepinScreenshot_select-area_20190921133119](https://user-images.githubusercontent.com/21283014/65377696-421d1f80-dc75-11e9-98cd-3a56151db559.png)

Please, close this issue if you consider it necessary.

**Comment by ssilvestri15** [comment]
Hi! I have the same issue but if I install deepin-kwin It freeze all. Only fix is to  revert the update and use deepin-wm

**Comment by abufalbo** [comment]
Hello! I have same issue from last update. I already have deepin-kwin installed. 
I also tried to reinstall the whole deepin desktop but the result is the same. 

**Distro Info:** 
Operating System: Fedora 31 (Thirty One)
CPE OS Name: cpe:/o:fedoraproject:fedora:31
Kernel: Linux 5.3.16-300.fc31.x86_64
Architecture: x86-64

**Package info:**
```
deepin-account-faces.noarch                       1.0.11-3.fc31                       @fedora                
deepin-api.x86_64                                 5.0.0-1.fc31                        @fedora                
deepin-calculator.x86_64                          5.0.1-1.fc31                        @fedora                
deepin-calendar.x86_64                            5.0.1-1.fc31                        @fedora                
deepin-control-center.x86_64                      5.0.0-1.fc31                        @fedora                
deepin-daemon.x86_64                              5.0.0-1.fc31                        @fedora                
deepin-desktop.x86_64                             5.0.0-3.fc31                        @fedora                
deepin-desktop-base.noarch                        2019.07.10-1.fc31                   @fedora                
deepin-desktop-schemas.noarch                     3.13.9-1.fc31                       @fedora                
deepin-dock.x86_64                                5.0.0-1.fc31                        @fedora                
deepin-editor.x86_64                              1.2.9.1-2.fc31                      @fedora                
deepin-file-manager.x86_64                        5.0.0-3.fc31                        @fedora                
deepin-gtk-theme.noarch                           17.10.11-1.fc31                     @fedora                
deepin-icon-theme.noarch                          15.12.71-1.fc31                     @fedora                
deepin-image-viewer.x86_64                        5.0.0-1.fc31                        @fedora                
deepin-kwin.x86_64                                0.1.0-2.fc31                        @fedora                
deepin-launcher.x86_64                            5.0.0-2.fc31                        @fedora                
deepin-menu.x86_64                                3.4.8-1.fc31                        @fedora                
deepin-network-utils.x86_64                       5.0.1-1.fc31                        @fedora                
deepin-picker.x86_64                              5.0.1-1.fc31                        @fedora                
deepin-polkit-agent.x86_64                        5.0.0-1.fc31                        @fedora                
deepin-qt-dbus-factory.x86_64                     5.0.1-2.fc31                        @fedora                
deepin-qt5dxcb-plugin.x86_64                      5.0.1-2.fc31                        @fedora                
deepin-qt5integration.x86_64                      5.0.0-2.fc31                        @fedora                
deepin-screensaver.x86_64                         0.0.10-1.fc31                       @fedora                
deepin-screensaver-data.noarch                    0.0.10-1.fc31                       @fedora                
deepin-screenshot.x86_64                          5.0.0-1.fc31                        @fedora                
deepin-session-ui.x86_64                          5.0.0-1.fc31                        @fedora                
deepin-shortcut-viewer.x86_64                     5.0.0-1.fc31                        @fedora                
deepin-sound-theme.noarch                         15.10.3-3.fc31                      @fedora                
deepin-system-monitor.x86_64                      5.0.0-1.fc31                        @fedora                
deepin-terminal.x86_64                            5.0.0-1.fc31                        @fedora                
deepin-terminal-data.noarch                       5.0.0-1.fc31                        @fedora                
deepin-wallpapers.noarch                          1.7.6-7.fc31                        @fedora
```

Have you some idea? 
Thanks :-)
