### ISSUE TITLE
deepin下面使用firefox播放网络视频没有硬解 

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1554]
## 缺陷描述

 我在deepin下面，腾讯视频网页端，使用html5播放器播放蓝光1080p视频，cpu占用很高，风扇呼呼叫。
我是amd gpu，使用sudo radeontop发现播放视频时显卡几乎没有工作。

希望优化让浏览器使用html5播放器播放网络视频的时候使用硬解，而不是cpu来解码。

### 发行版以及版本

deepin15.11

### 相关的软件包版本

firefox 69.0.1

**Comment by BLumia** [comment]
firefox 在任何桌面环境下都没硬解吧..

**Comment by widon1104** [comment]
firefox在windows下是硬解的
我专门测试了一下，我有一台奔腾4405U的电脑装的win7，在windows下用firefox打开腾讯视频播放蓝光1080p视频，查看cpu占用为20%~30%很低，同时打开gpu-z查看gpu load为30%~40%，可以确认是硬解的。

**Comment by widon1104** [comment]
![图片](https://user-images.githubusercontent.com/12093211/65674359-fe645480-e07e-11e9-9597-c7cbf9fe20fb.png)
Mozilla员工明确告知firefox在windows是硬解的

链接：http://mozilla.com.cn/forum.php?mod=viewthread&tid=418813&page=1#pid419328

**Comment by redchenjs** [comment]
试过其他linux发行版吗，其他发行版中firefox能硬解吗，同平台对比比较好，跟windows对比没有啥么用，底层实现不同。

**Comment by widon1104** [comment]
我没有其他linux发行版的环境，
我的想法是deepin能否和firefox合作搞一下，使得firefox for linux能够硬解html5视频。

**Comment by widon1104** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1584049
我在mozilla bugzilla上面报了一个bug，有人回复说他在ubuntu16.04下面无法复现我播放网络视频cpu高的问题，我怀疑是不是ubuntu系统比deepin对gpu的支持更好。

**Comment by redchenjs** [comment]
@widon1104 看archwiki里有说明，目前firefox在linux下还不支持硬解（实际上是调用ffmpeg软解的），chromium的修改版可以实现硬解（测试过确实可用）。
![Deepin 截圖_select-area_20191009130956](https://user-images.githubusercontent.com/9910809/66453285-614de680-ea96-11e9-918e-8d98723eff65.png)

**Comment by hillwoodroc** [comment]
Firefox 不支持 linux 下硬解。

**Comment by widon1104** [comment]
chromium在deepin15.11下，播放腾讯视频1080p视频，cpu占用还是很高
chrome在deepin15.11下，播放腾讯视频1080p视频，cpu占用比chromium还高

**Comment by BLumia** [comment]
https://mozillagfx.wordpress.com/2020/01/14/moz-gfx-newsletter-50/
https://bugzilla.mozilla.org/show_bug.cgi?id=1616680
一些主线支持硬解相关的链接供参考。

**Comment by redchenjs** [comment]
Wayland？DDE目前也是不支持的吧:joy:

**Comment by BLumia** [comment]
> Wayland？DDE目前也是不支持的吧😂

DDE 有 wayland 支持计划的。
