### ISSUE TITLE
Arch Linux recent updates have broken deepin-wm, no windows effect, screen tearing

### ISSUE THREAD

**Issue by taolin96** [linuxdeepin/developer-center#1555]
## Describe the bug

recent update of the following packages break deepin-wm, no windows effect. tried enable windows effect from Control Center but failed with error "Failed to enable window effects". tried "deepin-wm --replace", it crash with coredump

## To Reproduce

update the following packages caused the issue. once i downgraded the packages via "pacman -U" and the issue is gone.

## Expected behavior

deepin-wm should not crash and windows effect is enabled after the packages update

## Enviroments:

system info (working with windows effect, you can see the terminal background is transparent):
![image](https://user-images.githubusercontent.com/7938311/65386627-50149280-dd92-11e9-8769-874afbbf6dc4.png)

system info (bronken not windows effect, no transparent terminal background )
![image](https://user-images.githubusercontent.com/7938311/65386515-cdd79e80-dd90-11e9-80e4-c2453a8d33cd.png)

### Distro & Version

Arch Linux with Deepin desktop environment 15.11
lightdm 1:1.30.0-2
kernel 5.3.0-arch1-1-ARCH
nvidia driver  435.21-5

### Related package version

deepin-mutter (3.20.38-1 -> 3.20.38-2)
deepin-wm (1.9.38-1 -> 1.9.38-2)
gnome-desktop (1:3.32.2-1 -> 1:3.34.0-1)

### Additional context

coredump info
Message: Process 877 (deepin-wm) of user 1000 dumped core.
                
                Stack trace of thread 877:
                #0  0x00007fd006149755 raise (libc.so.6)
                #1  0x00007fd006134851 abort (libc.so.6)
                #2  0x00007fd00618ba38 __libc_message (libc.so.6)
                #3  0x00007fd00619225a malloc_printerr (libc.so.6)
                #4  0x00007fd0061939cc _int_free (libc.so.6)
                #5  0x000055cee89a985f gala_deepin_utils_clutter_set_mode_cubic_bezier (deepin-wm)
                #6  0x000055cee89a949e gala_deepin_utils_start_animation_group (deepin-wm)
                #7  0x000055cee89a970f gala_deepin_utils_start_fade_in_back_animation (deepin-wm)
                #8  0x000055cee89c1bf0 n/a (deepin-wm)
                #9  0x000055cee89c25cc n/a (deepin-wm)
                #10 0x00007fd00642d564 n/a (libgobject-2.0.so.0)
                #11 0x00007fd00642e2f9 g_object_new_valist (libgobject-2.0.so.0)
                #12 0x00007fd00642ec6a g_object_new (libgobject-2.0.so.0)
                #13 0x000055cee89a763b n/a (deepin-wm)
                #14 0x00007fd00642d564 n/a (libgobject-2.0.so.0)
                #15 0x00007fd00642e2f9 g_object_new_valist (libgobject-2.0.so.0)
                #16 0x00007fd00642ec6a g_object_new (libgobject-2.0.so.0)
                #17 0x000055cee899eaf9 n/a (deepin-wm)
                #18 0x00007fd00760b05a n/a (libdeepin-mutter.so.0)
                #19 0x00007fd0074b7ef5 n/a (libclutter-1.0.so.0)
                #20 0x00007fd0074b8d63 n/a (libclutter-1.0.so.0)
                #21 0x00007fd00633c3ae g_main_context_dispatch (libglib-2.0.so.0)
                #22 0x00007fd00633e1c1 n/a (libglib-2.0.so.0)
                #23 0x00007fd00633f0d3 g_main_loop_run (libglib-2.0.so.0)
                #24 0x00007fd0075fdef0 meta_run (libdeepin-mutter.so.0)
                #25 0x000055cee8983063 gala_main (deepin-wm)
                #26 0x00007fd006135ee3 __libc_start_main (libc.so.6)
                #27 0x000055cee897b11e _start (deepin-wm)
                
                Stack trace of thread 923:
                #0  0x00007fcff96b12c3 n/a (libjpeg.so.8)
                #1  0x00007fcff96a8eaf n/a (libjpeg.so.8)
                #2  0x00007fcff96b39de n/a (libjpeg.so.8)
                #3  0x00007fcff96a7479 jpeg_read_scanlines (libjpeg.so.8)
                #4  0x00007fd000158057 n/a (libpixbufloader-jpeg.so)
                #5  0x00007fd000158451 n/a (libpixbufloader-jpeg.so)
                #6  0x00007fd006616c2c gdk_pixbuf_loader_write (libgdk_pixbuf-2.0.so.0)
                #7  0x00007fd006617259 n/a (libgdk_pixbuf-2.0.so.0)
                #8  0x00007fd00661731e gdk_pixbuf_new_from_stream (libgdk_pixbuf-2.0.so.0)
                #9  0x00007fd0075e15fe n/a (libdeepin-mutter.so.0)
                #10 0x00007fd006513a81 n/a (libgio-2.0.so.0)
                #11 0x00007fd006313f97 n/a (libglib-2.0.so.0)
                #12 0x00007fd00631abc1 n/a (libglib-2.0.so.0)
                #13 0x00007fd00606c57f start_thread (libpthread.so.0)
                #14 0x00007fd00620b0e3 __clone (libc.so.6)
                
                Stack trace of thread 927:
                #0  0x00007fd006200667 __poll (libc.so.6)
                #1  0x00007fd000604c14 n/a (libpulse.so.0)
                #2  0x00007fd000612059 pa_mainloop_poll (libpulse.so.0)
                #3  0x00007fd00061c301 pa_mainloop_iterate (libpulse.so.0)
                #4  0x00007fd00061c3b1 pa_mainloop_run (libpulse.so.0)
                #5  0x00007fd00060c61e n/a (libpulse.so.0)
                #6  0x00007fd000590d1c n/a (libpulsecommon-13.0.so)
                #7  0x00007fd00606c57f start_thread (libpthread.so.0)
                #8  0x00007fd00620b0e3 __clone (libc.so.6)
                
                Stack trace of thread 879:
                #0  0x00007fd006200667 __poll (libc.so.6)
                #1  0x00007fd00633e130 n/a (libglib-2.0.so.0)
                #2  0x00007fd00633f0d3 g_main_loop_run (libglib-2.0.so.0)
                #3  0x00007fd0064acb18 n/a (libgio-2.0.so.0)
                #4  0x00007fd00631abc1 n/a (libglib-2.0.so.0)
                #5  0x00007fd00606c57f start_thread (libpthread.so.0)
                #6  0x00007fd00620b0e3 __clone (libc.so.6)
                
                Stack trace of thread 924:
                #0  0x00007fd006200667 __poll (libc.so.6)
                #1  0x00007fd00633e130 n/a (libglib-2.0.so.0)
                #2  0x00007fd00633e201 g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007fd0006bce5e n/a (libdconfsettings.so)
                #4  0x00007fd00631abc1 n/a (libglib-2.0.so.0)
                #5  0x00007fd00606c57f start_thread (libpthread.so.0)
                #6  0x00007fd00620b0e3 __clone (libc.so.6)
                
                Stack trace of thread 1154:
                #0  0x00007fd006205e3d syscall (libc.so.6)
                #1  0x00007fd0062ef11b g_cond_wait_until (libglib-2.0.so.0)
                #2  0x00007fd00636cf33 n/a (libglib-2.0.so.0)
                #3  0x00007fd0063140eb n/a (libglib-2.0.so.0)
                #4  0x00007fd00631abc1 n/a (libglib-2.0.so.0)
                #5  0x00007fd00606c57f start_thread (libpthread.so.0)
                #6  0x00007fd00620b0e3 __clone (libc.so.6)
                
                Stack trace of thread 878:
                #0  0x00007fd006200667 __poll (libc.so.6)
                #1  0x00007fd00633e130 n/a (libglib-2.0.so.0)
                #2  0x00007fd00633e201 g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007fd00633e252 n/a (libglib-2.0.so.0)
                #4  0x00007fd00631abc1 n/a (libglib-2.0.so.0)
                #5  0x00007fd00606c57f start_thread (libpthread.so.0)
                #6  0x00007fd00620b0e3 __clone (libc.so.6)

**Comment by keybreak** [comment]
Duplicate: https://github.com/linuxdeepin/developer-center/issues/1552

@BLumia 
Yeah...And thx for forcing super-buggy unfinished **deepin-kwin**. :unamused: 
Was that really necessary?

**Comment by aiamuzz** [comment]
> Yeah...And thx for forcing super-buggy unfinished **deepin-kwin**

yeah ... with kwin

1. I am left with dock visible only on one workspace ...
2. the window resize seems has a mind of its own ... not remembering the sizes and position that i want it to remember ...

thanks to the `systemsettings` package ... i was able to iron out the bland kwin ... and to top it all ... deepin-wm is orphaned ... the one thing that won users in favor of Linux Deepin now stands abandoned ... i still wish Deepin Team re thought about **Deepin-WM** and froze it as it stands currently ... **maintaining on a bare bone run'nable condition** ... they can end any further development(no more new features accepted) of Deepin-WM ... that way people can always enjoy its beauty & simplicity, its ease of use ... as long as they just repackage it to run after every system update ... keepin Deepin-WM alive this way will certainly be good for Linux Deepin !!!

**Comment by TryAztec** [comment]
Greetings! I have exactly the same problem! @taolin96 
The desktop effects stopped working after the update.
I can also attach dumps.
I really look forward to when correct. It is not convenient to work :-)

**Comment by Mark-AAAA** [comment]
DDE is not meant for Arch Linux.
Just move away from it and if you want build something like this, easy with KDE.
![Screenshot_20190922_163745](https://user-images.githubusercontent.com/52075807/65388759-ccd64b00-dd57-11e9-81a4-41b2211aaaf5.png)
![Uploading Screenshot_20190922_163822.png…]()

**Comment by RailRanger** [comment]
Deepin kwin on Manjaro is quite useable now, I use it on my main system. Combined with kwin-lowlatency from aur it's very fast too. I don't think deepin-wm needs to continue to be supported at this point. Just make sure you disable opengl 3 in your kwinrc file if experience any bugs. Using opengl 2.0 fixed so many bugs for me on Nvidia.
The mouse hovering over apps in the taskbar ghost window bug is still here though, that affects wm and kwin.
https://forum.manjaro.org/t/manjaro-deepin-blur-on-windows-turns-black-after-running-steam-games/93679/11

**Comment by BLumia** [comment]
> @keybreak : ..for forcing..

I think it's just because no-one is going to maintain deepin-wm now... *Vala got updates and breaks deepin-wm build all the time* and I believe @felixonmars try his best make deepin-wm compilable under Arch. It's not a easy job keep maintaining such a project, and I still hope anyone who love to use deepin-wm can give the project some love, by contributing, or create a fork or some other way..

> @Mark-AAAA : DDE is not meant for Arch Linux. Just move away from it and if you want build something like this

Actually there are almost only developers from official deepin dev team working on non-deepin distro support. We'd love to do but still doesn't have enough time and energy to working on all other distro, so we really hope anyone who can also help to build a better DE.

It's also okay if you decided not to help us and hop into another DE, but what you've said really doesn't help on anything at all rather than annoying other contributers.

> @RailRanger : Deepin-wm ran very poorly on Nvidia. Just make sure you disable opengl 3 in your kwinrc file if you experience any bugs. Using opengl 2.0 fixed so many bugs for me on Nvidia.

That's one of the reasons the wm team deprecated deepin-wm.

btw KDE also did very good job by creating a flexable and powerful DE, and both GNOME, KDE and DDE have very different UI design principle which may fit to different people, thank you for the kind words about DDE :)

**Comment by keybreak** [comment]
@BLumia 
> I still hope anyone who love to use deepin-wm can give the project some love, by contributing, or create a fork or some other way..

I don't know man...Doubt it will work out that way, otherwise it would already happen.
Devs who could actually contribute are stopped by a lot of issues / controversy / forced decisions around Deepin.

Maybe you was right before, and only way is to make community driven fork, which will not be affected by mad political decisions of current workflow.

For example, i haven't seen any actual Deepin user around internet who demanded full redesign - everyone loves Deepin the way it is, it is perfect. Most of users just want bugs to be fixed & introduce features / new concepts only if it's fully tested & ready - that's all.

But corporate clients want some non-sense features, redesigns, forced decisions and stuff like that...

That's just very different models of behavior.
I'd be glad to this fork myself, but have 0 experience and busy with other stuff.
Hopefully you'll figure out a way to push this from your side, so professional devs would actually like to work on it!

**Comment by TryAztec** [comment]
@taolin96 installed deepin-kwin, install the dependencies and the problem goes away.
It helped me.

**Comment by majidg** [comment]
> @taolin96 installed deepin-kwin, install the dependencies and the problem goes away.
> It helped me.

that worked for me, thank you

**Comment by mikhama** [comment]
@TryAztec thank you, it's worked for me too.

**Comment by felixonmars** [comment]
I have tried to debug the crash during my trip but it looks mysterious to me. Since it seems no one is going to fix it in months I am considering to drop support for it (along with super out-of-date deepin patched version of cogl and mutter) and make deepin-kwin the default.

**Comment by taolin96** [comment]
@felixonmars yeah, windows effect is back and no more screen tearing after i installed deepin-kwin. the deepin-kwin is bit buggy, but good thing takes time to build. I am happy switching to deepin-kwin. keep up the good work guys. Don't get annoyed by the comment like @Mark-AAAA. I think most of people like me wont move away from DDE just because of the little glitch like this. I really enjoy using DDE as my daily work and home use environment.
我感到非常自豪 DDE 出自国人之手。感谢你们的团队给我们带来便捷漂亮的深度系统和桌面环境 加油！！

**Comment by cursorme** [comment]
After kwin install problem goes away but my regular gnome apps like remmina and timeshift have a very weird theme now and not consistent with the rest of native deepin windows... Anyone with the same issue ?

**Comment by gpen365** [comment]
> DDE is not meant for Arch Linux.
> Just move away from it and if you want build something like this, easy with KDE.
> ![Screenshot_20190922_163745](https://user-images.githubusercontent.com/52075807/65388759-ccd64b00-dd57-11e9-81a4-41b2211aaaf5.png)
> ![Screenshot_20190922_163822](https://user-images.githubusercontent.com/52075807/65388777-0ad36f00-dd58-11e9-95bc-8879008be9d5.png)

What are you using for the dock and windows tranperancy?

**Comment by gpen365** [comment]
@Mark-AAAA 
What are you using for the dock and windows transparency?

**Comment by Mark-AAAA** [comment]
It's a [Kvantum](https://github.com/tsujan/Kvantum/tree/master/Kvantum) theme, called [Akava-Kv](https://github.com/Akava-Design/Akava-Kv)!
For the dock/top panel I'm using the [Latte Dock](https://github.com/KDE/latte-dock).

**Comment by Mark-AAAA** [comment]
> @Mark-AAAA
> What are you using for the dock and windows transparency?
@gpen365 
It's a [Kvantum](https://github.com/tsujan/Kvantum/tree/master/Kvantum) theme, called [Akava-Kv](https://github.com/Akava-Design/Akava-Kv)!
For the dock/top panel I'm using the [Latte Dock](https://github.com/KDE/latte-dock).

**Comment by Mark-AAAA** [comment]
> @felixonmars yeah, windows effect is back and no more screen tearing after i installed deepin-kwin. the deepin-kwin is bit buggy, but good thing takes time to build. I am happy switching to deepin-kwin. keep up the good work guys. Don't get annoyed by the comment like @Mark-AAAA. I think most of people like me wont move away from DDE just because of the little glitch like this. I really enjoy using DDE as my daily work and home use environment.
> 我感到非常自豪 DDE 出自国人之手。感谢你们的团队给我们带来便捷漂亮的深度系统和桌面环境 加油！！

Little glitch...
Have these(https://github.com/linuxdeepin/developer-center/issues/1337) major, super annoying issues got fixed?

**Comment by mitchellkrogza** [comment]
Thank you so much @TryAztec that fix worked like a charm. I was about to start crying when all my smooth graphics broke yesterday.

**Comment by profran** [comment]
@taolin96 I have the same issue. How did you downgrade the whole deepin package group? I don't want to downgrade each package manually.

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/deepin-wm/issues/64#issuecomment-535737647

**Comment by gchamon** [comment]
@aiamuzz I am also experiencing dock on the first workspace only with `deepin-kw`. Curiously, a friend of mine has a similar installation (anarchy linux with vanilla deepin, just switched to kwin) and does not have this issue, so I believe there must be a workaround/fix for this

**Comment by mitchellkrogza** [comment]
Sorry to post this here, but can please can anyone possibly point me to the correct component / part of deepin where I can report / fix a problem with wired networking that keeps on disconnecting at random times. It appears the moment there is internet connectivity problems the network connection disconnects and reconnects.

**Comment by gchamon** [comment]
@mitchellkrogza could you try this and see if it helps? https://wiki.archlinux.org/index.php/Deepin_Desktop_Environment#Wireless_network_does_not_connect

**Comment by aiamuzz** [comment]
> @aiamuzz I am also experiencing dock on the first workspace only with `deepin-kw`. Curiously, a friend of mine has a similar installation (anarchy linux with vanilla deepin, just switched to kwin) and does not have this issue, so I believe there must be a workaround/fix for this

@gchamon ... kindly post the same here ... https://github.com/linuxdeepin/developer-center/issues/1389

**Comment by mitchellkrogza** [comment]
Thank you so much @gchamon that has definitely fixed my networking issue. :ok_hand:

**Comment by keiichiiownsu12** [comment]
A few weird things happened after installing deepin-kwin:

All gtk apps lost their title bars. Deepin apps displayed theirs, however I could not drag them, resize, or select by clicking. Cannot click to focus/select (i.e. you click on a window to select it), for ANY app.

Window effects still do not work.

I have kde installed as well, snce I  wanted to give deepin-de another spin. Does anyone know if there's compatibility issues here?

**Comment by aiamuzz** [comment]
> Window effects still do not work.

@keiichiiownsu12 ... please check the contents of the file `/home/USER/.config/kwinrc` for this setting ...

```
[Compositing]
Enabled=true
OpenGLIsUnsafe=false
```

OpenGL has to be set to `false` for windows effect to work ...

**Comment by keiichiiownsu12** [comment]
kwinrc is already configured the way you mention:
`[Compositing]
AnimationSpeed=3
Backend=OpenGL
Enabled=true
GLCore=true
GLPreferBufferSwap=a
GLTextureFilter=2
HiddenPreviews=5
OpenGLIsUnsafe=false
WindowsBlockCompositing=true
XRenderSmoothScale=false`

I can post the whole kwinrc if needed. It has settings enabled in kde-plasma, so they might conflict.

Here are a few bugs I can showcase:

![DeepinScreenshot_20191001025128](https://user-images.githubusercontent.com/37505464/65952750-65736780-e3f7-11e9-8fc7-f5c626f4e888.png)
Firefox has no titlebar. Cannot select it, drag, or close. Have to kill in terminal.

![DeepinScreenshot_20191001025248](https://user-images.githubusercontent.com/37505464/65952900-b2efd480-e3f7-11e9-990f-26e087310899.png)
Similar story for opera. Has a title bar. Can close it. But cannot resize, minimize, or even drag.

**Comment by felixonmars** [comment]
Please try again with deepin-wm 1.9.38-3. Sorry for taking so long, I am still travelling around.

**Comment by dwlsalmeida** [comment]
This seems to be broken again...

**Comment by felixonmars** [comment]
@dwlsalmeida deepin-kwin 0.1.0-2 is broken with latest kwin >= 5.17.0. Should have been fixed in 0.1.0-3. deepin-wm is unaffected.

**Comment by BLumia** [comment]
Closed since it fixed now.

If deepin-kwin breaks again due to other reason(another kwin upgrade for example), please consider open another issue :)
