### ISSUE TITLE
无线网络关闭时提示"无线网络 ''已断开"

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1559]
## 缺陷描述

我的无线网络一直都是在设置里面关闭的，但是这几天总是会时不时提示"无线网络 ''已断开"，我感觉很奇怪，我觉得如果我已经关闭了无线网络，无线网络不应该有任何连接、关闭通知
![无线网络‘’已断开](https://user-images.githubusercontent.com/12093211/66263368-3e1c0080-e824-11e9-9000-6bb8407175ca.png)

### 发行版以及版本

deepin15.11

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
