### ISSUE TITLE
[archlinux] Cannot input text in Control Center.

### ISSUE THREAD

**Issue by Suantovith** [linuxdeepin/developer-center#156]
I've just installed Deepin Desktop Environment, and I cannot do anything in Control Center. I can get menu by right clicking but if I try to write something nothing is happening.

I think that text field look normal by itself, but I will still give screenshot:
![zrzut ekranu deepin20170205131813](https://cloud.githubusercontent.com/assets/17232570/22626089/d1b8225c-eba5-11e6-8da8-53b588a32f80.png)

**Comment by HylianArcher** [comment]
I notice this too when attempting to connect to a hidden SSID via the control center it will not allow for entry of any text into the fields SSID or Password.

**Comment by felixonmars** [comment]
Please test again with deepin-control-center 4.0.2-3.

**Comment by Suantovith** [comment]
It works great right now!
