### ISSUE TITLE
deepin-kwin在Firefox和chromium最大化时会显示标题栏

### ISSUE THREAD

**Issue by felinae98** [linuxdeepin/developer-center#1560]
## 缺陷描述

deepin-kwin在Firefox和chromium最大化时会显示标题栏

## 复现步骤

1. 在Firefox的定制中关闭标题栏
2. 在非最大化的Firefox中不显示标题栏（期待的结果）
3. Firefox最大化后出现标题栏（不期待的结果）
4. 使用Chromium也存在这样的问题

## 期望行为

最大化不显示标题栏（在关闭标题栏的情况下）

### 发行版以及版本

Archlinux

### 相关的软件包版本

deepin-kwin 0.1.0-2

**Comment by BLumia** [comment]
火狐请参见： https://github.com/linuxdeepin/developer-center/issues/1460 （欢迎帮忙向 Mozilla Firefox 提 bug）。
Chrome 右键 chrome 标签页栏空白位置就可以选择隐藏系统标题栏了。

同样请在 https://github.com/linuxdeepin/developer-center/issues/1460 跟进这个问题，感谢反馈~
