### ISSUE TITLE
[Arch Linux] deepin-file-manager no video previews

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#1562]
@BLumia @felixonmars 
I think **deepin-file-manager** also requires update because of new **ffmpegthumbnailer 2.2.2-1** perhaps?

**Comment by BLumia** [comment]
Sorry I don't have permission to do a code release right now, maybe adding patch to downstream(distro) is more feasible. The v20 (code) release *may* at middle November btw.

**Comment by keybreak** [comment]
@BLumia 
Yeah i know, thx :+1: 

To be honest with you...
I'm not looking forward to it, based on experience of a past and new design.

After seeing V20 preview videos - i'm actively seeking for alternative DE for daily use, because i think (at least based of what is shown now) design is ruined. Those circle-round corners, inverted contrast of panel / text and all that is complete non-sense, compared to what we had.

In my opinion you guys absolutely nailed it in current version at the end of 2018 and one thing that absolutely does **not** need any change was the design.

I think that is a huge mistake.
Although, i wish you best of luck!

P.S. Is there any way to clone whole source code for one of current tags to get all needed packages?
Maybe some day i'll get to fork or something based on 15.9, i don't want loose this design / UX.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
