### ISSUE TITLE
Hide icons from Desktop

### ISSUE THREAD

**Issue by saymoncoppi** [linuxdeepin/developer-center#1563]
Hello Guys! Is there any trick to keep the desktop area clear like Elementary Desktop. Sure considering that there are files inside the folder.
I've already tried removing or cleaning the ~/.config/deepin/dde-desktop/dde-desktop.conf

![image](https://user-images.githubusercontent.com/22059715/66438934-842fba80-ea04-11e9-9115-57762dc1ae67.png)

Some suggestions?

**Comment by BLumia** [comment]
Currently no direct support for this, maybe you can do:

1. Move your files inside the Desktop folder to other places so it will not be shown.
2. edit your `~/.config/user-dirs.dirs` and map your Desktop folder to a empty folder.

Actually both of these ways are the same.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
