### ISSUE TITLE
Dock/Control Panel High Transparency mode

### ISSUE THREAD

**Issue by saymoncoppi** [linuxdeepin/developer-center#1564]
Hello Guys!
Could you think about to split this dconf setting?
With this way the user could choose an high transparency mode for each component (dock or control panel)

![image](https://user-images.githubusercontent.com/22059715/66439609-8e52b880-ea06-11e9-8af3-b42c76abbaab.png)

Bug on light backgrounds

**Comment by BLumia** [comment]
Hi and FYI the control center will no longer be transparent in next major release (it will become a standalone window btw).

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
