### ISSUE TITLE
深度系统监视器不显示GPU使用情况

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1566]
## 缺陷描述

深度系统监视器缺失重要的系统设备GPU的监控，GPU的使用情况非常重要，可以让用户感知系统GPU设备是否正常工作，而深度系统监视器不支持GPU使用情况显示。
据我所知win10的系统监视器是支持显示GPU使用情况，deepin应该向win10看齐。

### 发行版以及版本

deepin15.11

**Comment by sonichy** [comment]
这需求好难啊

**Comment by redchenjs** [comment]
intel核显有intel_gpu_top工具，amd显卡有radeontop工具，N卡有nvtop，官方可以考虑在系统监视器中做个前端集成进来。

**Comment by widon1104** [comment]
deepin仓库里面有intel-gpu-tools和radeontop，但是没有nvtop这个工具，希望能够把nvtop这个工具集成进仓库

**Comment by sonichy** [comment]
还有这些东西啊，有源码就好办了，可惜老王不在了。

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
