### ISSUE TITLE
开机选择界面按键盘上下选择反应迟钝

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1567]
## 缺陷描述

![2](https://user-images.githubusercontent.com/12093211/66828587-0596c800-ef84-11e9-889d-8195bfbcd18b.jpg)
就是上图这个界面，我的罗技k120键盘已经点亮，按“下”起码5秒中才反应过来，按回车也要好几秒才反应过来，连续按了很多次以后可能恢复到1到2秒反应过来，这显然不正常。
[deepin-feedback-cli-Deepin-15.11-all-20191015-194128.tar.gz](https://github.com/linuxdeepin/developer-center/files/3729026/deepin-feedback-cli-Deepin-15.11-all-20191015-194128.tar.gz)

### 发行版以及版本

deepin15.11

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
