### ISSUE TITLE
Arch-Deepin kde updates break deepin-kwin

### ISSUE THREAD

**Issue by dance707** [linuxdeepin/developer-center#1568]
## Describe the bug
dde_shutdown.go:38:dde-kwin exit with error:exit status 127

## To Reproduce
install todays kde 5.17.0-1 udpdates

### Distro & Version
arch deepin

**Comment by gchamon** [comment]
workaround is to remove `deepin-kwin` and reinstall `deepin` and `deepin-extra`

this will return with the `deepin-wm` that comes with `startdde`. I find this a little tiring to go back and forth with window managers, but until deepin stabilizes with either kwin or wm, we will have to do this

**Comment by carlosal1015** [comment]
Today I updated the programs, including kwin, a dependency of deepin-kwin that I have installed yet. Unless you run kwin_x11 by terminal, everything is ok, but when you start the system kwin is not running by default, I think you should configure something like kwinrc.

![DeepinScreenshot_select-area_20191015164308](https://user-images.githubusercontent.com/21283014/66873667-a24e6b00-ef6e-11e9-9f3a-98192e27fce7.png)

**Comment by taolin96** [comment]
same here, log shows
`startdde[833]: session_process.go:91: Wait command kwin_no_scale [] failed: exit status 127`
tried ran kwin_no_scale in terminal error `kwin_x11: symbol lookup error: /usr/lib/libkwin-xcb.so.0: undefined symbol: _ZN4KWin10Compositor7suspendENS0_13SuspendReasonE`

ran 'kwin_x11 &' in terminal, everything is work again

**Comment by dance707** [comment]
Yes @carlosal1015 suggestion of kwin_x11 by terminal works. So I was thinking of a startup script. Then I also noticed another possible related issue. When systemctl default is multi-user.target mode, a user login triggers a graphical display. It should be a normal runlevel 3 text based mode.

**Comment by felixonmars** [comment]
Please try deepin-kwin 0.1.0-3

**Comment by dance707** [comment]
> Please try deepin-kwin 0.1.0-3

Looks good , Thank you !

**Comment by carlosal1015** [comment]
> Please try deepin-kwin 0.1.0-3

Thank you!
