### ISSUE TITLE
深度文管无法启动desktop的exec的参数

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#1569]
## 缺陷描述
深度文管双击desktop，无法启动 desktop 的 exec 的参数，其他文管没问题。
例如：启动暗黑主题的Chrome：Exec=/usr/bin/google-chrome-stable --force-dark-mode

### 发行版以及版本
Linux Deepin 15.11 unstable

### 相关的软件包版本
dde-file-manager 4.8.8.2+c1

**Comment by sonichy** [comment]
在终端用命令行可以对比。
如果不支持暗主题，你可以加其他参数测试。

**Comment by BLumia** [comment]
给一下具体的复现步骤和细节啊。

文件管理器在不同地方调的地方也不一样，比如双击desktop文件是调的 `com.deepin.SessionManager`下的 `/com/deepin/StartManager/LaunchApp`，其他一部分地方可能调用别的方式运行，目前社区版这部分还不太一样。要不你直接试试在你的环境调这个 dbus 接口看看有没有问题？

参数是：

|类型|解释|
|:-:|:-:|
|QString | desktop文件名|
|int|调用接口时的时间戳|
|QStringList|传入的文件列表（以便`%u`之类的转义用）|

**Comment by sonichy** [comment]
第一个参数是文件名？这个QDBus并没有涉及desktop解析exec。

**Comment by BLumia** [comment]
当然是你传过去然后后端解析啊，对于直接双击执行的场景，是直接调后端执行的，文件管理器压根不负责运行它。

当然对于别的一部分场景可能不是调的后端，所以才问你到底怎么复现的啊，比如到底是双击还是右键菜单插件之类的（

**Comment by sonichy** [comment]
当然是双击啦，还能怎么操做？文管有插件？

**Comment by BLumia** [comment]
你又不是不知道之前提供过那个oem插件......

所以那个接口试过了吗（

**Comment by sonichy** [comment]
Chrome.desktop 的 Exec=/usr/bin/google-chrome-stable 后面加上 “ --force-dark-mode”
接口怎么检查？

**Comment by BLumia** [comment]
我把 google-chrome.desktop 拷贝出来了一份，然后直接修改了 `.desktop` 文件内 `Exec` 字段的内容为 `Exec=/home/username/Temp/test.sh --force-dark-mode`, 这个对应的脚本内容为

``` shell
~/Temp$ cat test.sh                                                                                                    
#!/bin/bash
echo "$*" > /home/wzc/username/test.sh.log
```

通过 qdbusviewer 执行此 desktop 文件，时间戳参数留 0 ，文件列表留空，调用 `LaunchApp` DBus 接口后观察 `/home/username/username/test.sh.log` 的文本内容为：

```
~/Temp$ cat test.sh.log 
--force-dark-mode
```

也未能复现问题。

不过注意到 chrome 的暗色主题的确未生效，只能认为是 chrome 本身可能有问题，测试使用的是 `77.0.3865.90`。

**Comment by sonichy** [comment]
终端是正常的，终端运行 google-chrome-stable --force-dark-mode 即可测试。

**Comment by BLumia** [comment]
我这边终端运行 `google-chrome-stable --force-dark-mode` 暗色也无效，不过我建议你那边自行按照上述方式，自己写一个简单的脚本，修改 desktop 文件的 Exec 字段调用脚本，传递你希望测试的参数，并使用 dbus 调用来模拟文件管理器双击运行来查看是否实际起作用，毕竟我环境和你不一样，但这么做是可以排查出是否是后端问题的。

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
