### ISSUE TITLE
wifi password not accepted

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/developer-center#157]
I think this issue was already present a while ago and is now back. maybe a regression with the new control-center?
Anyway, this is what happens:
When I try to connect to a new password connected wifi and enter the code, deepin tries to connect to the network for a long time and then finally quits with "password not provided".
Neither the dock-applet nor the dialog in the control-center work.
When I install **network-manager-applet** I can connect without problem to the same network with the same password.

**Comment by sbwtw** [comment]
whats your dde-dock version?
do u have wireless plugin item on the dock panel(its a blue sector item
with wifi-signal)

**Comment by osomfinch** [comment]
It does that with the two latest versions of Manjaro Deepin iso(so it is the dde dock version that is in them). 
I had the wireless plugin item. 
Please, fix this. Manjaro Deepin is such a promising distro. 
Thank you for your work!

**Comment by oberon2007** [comment]
@sbwtw Sorry, for taking so long, I missed your inquiry...
I use Archlinux package **v 4.0.8** and, yes the wifi plugin is present - that's what I first tried. Then I attempted to connect via the control-center - with the same issue as described above.

**Comment by funilrys** [comment]
I also have the same issue with the same version as @oberon2007 !

**Comment by sbwtw** [comment]
@jouyouyun

**Comment by osomfinch** [comment]
Is there a way to know when you have sold the issue?
Thank you!

**Comment by sbwtw** [comment]
i think latest version is worked

**Comment by oberon2007** [comment]
The issue is not solved for me and also other Manjaro users tell me the same.
I just need to use **network-manager-applet** or even **nmtui** one time and enter the wifi password and in the future connection will also work with builtin Deepin wifi plugin/module.
It still doesn't work when connecting for the first time with a new password-protected network.

**Comment by oberon2007** [comment]
Please re-open. I can't for some reason. Or should I open a new issue?

**Comment by funilrys** [comment]
Strange it working on Arch but not on Manjaro ...

**Comment by felixonmars** [comment]
The error was fixed long ago in deepin-tool-kit. Please do check your sources and make sure they are recent :S

**Comment by oberon2007** [comment]
I am using your packages straight from arch community repo!

**Comment by oberon2007** [comment]
right. I can't seem to be able to reproduce it now :wink: sorry for that. must have been some other problem here with the network of whatever ... :)
