### ISSUE TITLE
ALT + TAB Spamming 

### ISSUE THREAD

**Issue by phanirithvij** [linuxdeepin/developer-center#1570]
## Describe 

When using ALT + TAB the display flashes like crazy.
There should be some cooldown time implemented.

## To Reproduce

Open two or more windows and hold ALT + TAB

## Expected behavior

Only after the alt+tab is released the window should be brought to the front.
## Screenshots

[VIDEO](https://res.cloudinary.com/rootworld/video/upload/v1571529326/ss.mp4)
## Enviroments:
?

### Distro & Version

Linux Deepin 15.11

### Related package version

dde-desktop 4.8.8.1

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
