### ISSUE TITLE
网易云音乐搜索输入框在搜狗输入法打开的情况下偶尔会出现输入错乱

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1572]
## 缺陷描述

![深度截图_选择区域_20191024202322](https://user-images.githubusercontent.com/12093211/67486525-c876b800-f69e-11e9-80d7-6114b3037739.png)
就像上图这样，不是必现的，我输入的是“告白气球”，结果就出来倒叙英文字母

## 复现步骤

偶现的

## 期望行为

搜索框能够正常输入中文

### 发行版以及版本

deepin15.11

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
