### ISSUE TITLE
Wireless bluetooth headset connection not Reusable

### ISSUE THREAD

**Issue by YannisZhao** [linuxdeepin/developer-center#1573]
## Describe the bug

Bluetooth headset Connection won't work when reboot.
## To Reproduce

1. Try bluetooth pairing and establish a connection
2. Reboot bluetooth headset
3. Got a notification tips device has been connected 
4. Not actually work

## Expected behavior

Should be work after reboot
### Distro & Version

deepin os v15.11

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
