### ISSUE TITLE
网易云音乐应用声音设置和面板上面应用声音设置不一致

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1574]
## 缺陷描述

![网易云音乐声音不一致](https://user-images.githubusercontent.com/12093211/67579716-9be29f00-f777-11e9-9555-72565e013f6f.png)
如图，网易云音乐应用声音设置和面板上面应用声音设置不一致
生效的声音设置还是面板上面的声音设置，这时候网易云音乐是没有声音的，这时候调整网易云音乐应用的声音是没用的，必须调整面板上应用的声音设置才行

## 期望行为

声音设置要一致，不然会出问题

### 发行版以及版本

deepin15.11

**Comment by widon1104** [comment]
昨天我刚装好deepin15.11复现了这个问题。
面板上面网易云音乐声音是0，但是网易云音乐app上面声音打开了一大半，我调整面板上面声音以后开始和网易云音乐声音同步，后面没有再出现这个问题。
我觉得应该是刚开始的音量同步没有做好。

**Comment by BLumia** [comment]
右下角提供的音量合成器控制的是按应用独立控制的音量，和应用本身提供的音量功能本身就是两码事，不是bug。
