### ISSUE TITLE
file preview of pictures and videos broken

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/developer-center#1575]
In my videos folder all the thumbnails of the videos are gone. Instead they just have normal icons.

**Comment by keybreak** [comment]
@BLumia 
Nope, he's good.

https://github.com/linuxdeepin/developer-center/issues/1562

This is because of **ffmpegthumbnailer**.

**Comment by BLumia** [comment]
> @BLumia
> Nope, he's good.
> 
> #1562
> 
> This is because of **ffmpegthumbnailer**.

Yep, so it is not a **window** manager(dde-kwin) issue, but a **file** manager(dde-file-manager) issue. fyi v20 release still require some work..

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
