### ISSUE TITLE
Terminal doesn't take focus after drag-drop from deepin file manager

### ISSUE THREAD

**Issue by womotu** [linuxdeepin/developer-center#1577]
## Describe the bug
When you drag and drop a file or folder from deepin file manager into terminal the full filename/path appears on the terminal command line as expected, however focus does not shift to terminal, it remains on file manager.

## To Reproduce
1. Drag and drop a jpg file from deepin file manager into an open terminal window where you have entered "ls ". 
2. The full file path appears on the terminal window command line as expected, and the terminal window appears to take focus.
3. Press Enter key to execute the ls command on the file path name. 
4. Notice the jpg pic opens (or whatever the associated program is for the file type) because focus has not changed to terminal, but is still on file manager.

## Expected behavior
When file name path is successfully received by and entered into terminal command line after drag drop from file manager, focus should switch to terminal, not stay in file manager. If unsuccessful for any reason focus should remain on file manager.

### Distro & Version
 Linux Deepin 15.11

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
