### ISSUE TITLE
Deepin installation problem: not booting

### ISSUE THREAD

**Issue by londonuk371** [linuxdeepin/developer-center#1578]
On this cold Sunday day I wanted to install to test the famous Chinese Linux distribution Deepin. But here it is, impossible to start the boot.

So at installation I select "Install Deepin" as on this screenshot: 
![d14](https://user-images.githubusercontent.com/22617037/67633818-182ecc80-f8b5-11e9-9ce4-6105a162b2cc.png)

And then nothing! So I downloaded older versions up to 15.9 but get the same problem. I also put on my USB key an Ubuntu 19 and the installation process started well. I also disabled all the security on the Bios but always the same.

And I can't find any log files to understand the problem!

My PC is a Lenovo Yoga 720 with a GTX 1050 graphics card. https://www.lenovo.com/us/en/laptops/yoga/700-series/Yoga-720-15/p/88YG7000828

Anyone have any ideas?

**Comment by RailRanger** [comment]
Deepin 15.11 kernel is probably a bit too old based on your specs. I would wait around a month for the new v20 release of Deepin.

**Comment by londonuk371** [comment]
OK, I understand. I would have appreciated a kernel error message instead of just nothing happening...that's important to let users know what is going wrong.
Is there preview or beta of the future V20 to download? 
I looked at your Youtube [V20](https://www.youtube.com/watch?v=p9WkZSIReK0) videos and I must admit that I am admiring such an beautiful work. Congratulations ;)

**Comment by RailRanger** [comment]
I'm just a user :), maybe Blumia or one of the other devs can give more insight. But Deepin 15.11 is based on kernel 4.15, so I'm fairly confident that's the issue, but you never know.

**Comment by londonuk371** [comment]
Hope this issue will be read by a @BLumia or any other Deepin devs. I'm really disappointed that I couldn't install Deepin! I wanted so much to test it...

**Comment by BLumia** [comment]
The v20 release will be based on kernel 4.19, the beta release is still not ready now, so please keep an eye on it :)

**Comment by meftunca** [comment]
the v20 release not opening on after insttaling

**Comment by chaim1221** [comment]
same same ... lenovo yoga 3

**Comment by hamster4n** [comment]
I try deepIn 20 on my laptop Acer Aspire 5 (AMD Ryzen 7 4700U (2.0 - 4.1 ГГц) / RAM 16 ГБ / SSD 512 ГБ / AMD Radeon Vega Graphics). I have the same as @londonuk371 (((
On a stationary computer, installation from the same flash drive starts normally. But I need to install it on a laptop.

**Comment by xmuli** [comment]
@londonuk371 @hamster4n   Now deepin v20 supports both 5.4 and 5.7 versions of your

**Comment by ProxFun** [comment]
Same problem honor magikbook pro ryzen 4600h

**Comment by nvhk** [comment]
Same problem on Matebook 14, Ryzen 4600h. Deepin 20.1. Can't install this distro.

**Comment by Zeno-sole** [comment]
The latest version already supports Matebook 14. Can your Lenovo Yoga be installed normally?

**Comment by Zeno-sole** [comment]
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue
