### ISSUE TITLE
Settings panel got weird background in Arch

### ISSUE THREAD

**Issue by kaymio** [linuxdeepin/developer-center#158]
Every time opening the panel in Arch Linux the background changes to some weird pattern. The pattern is each time different and seems to get its pattern from the video buffer.

It's a great desktop, that is why I try to help this DE on the way.

**Comment by sonald** [comment]
@kaymio the reason is deepin uses a patched clutter for background blurring and that patch is not included in archlinux. maybe we'll find a way to fix that.

**Comment by justforlxz** [comment]
This question has not been answered for too long and will be closed. If there is a need to continue the discussion, it will be reopened.
