### ISSUE TITLE
深度文管上下文菜单 OEM 支持插件扩展的菜单如何让它只在桌面右键显示，其他区域不显示？

### ISSUE THREAD

**Issue by Lyvnee** [linuxdeepin/developer-center#1581]

**Comment by BLumia** [comment]
目前版本不能，在随后 v20 大更新后会支持（也会提供完整文档）。这个问题相关的段落我贴在下面：

-------------------

`X-DFM-NotShowIn` 可以决定是否在桌面或者文件管理器显示菜单，此字段可包含一个或多个类型，其中包括 `FileManager`, `Desktop` 两种，字段不存在或字段为空时在桌面和文件管理均可显示。

| 名称 | 含义 |
| :- | :- |
| `FileManager` | 在文件管理器中触发上下文菜单 |
| `Desktop` | 在桌面触发上下文菜单 |

**Comment by Lyvnee** [comment]
期待V20版本的发布。

**Comment by BLumia** [comment]
顺便贴一下，[适用于 v20 版本的文件管理器右键菜单扩展格式文档](https://github.com/linuxdeepin/dde-file-manager-menu-oem/wiki/%E9%80%82%E7%94%A8%E4%BA%8E-v20-%E7%89%88%E6%9C%AC%E7%9A%84%E6%96%87%E4%BB%B6%E7%AE%A1%E7%90%86%E5%99%A8%E5%8F%B3%E9%94%AE%E8%8F%9C%E5%8D%95%E6%89%A9%E5%B1%95%E6%A0%BC%E5%BC%8F%E6%96%87%E6%A1%A3)
