### ISSUE TITLE
网易云音乐1.2.0(build 0408) 有时候界面会变成白屏，变为完全无响应状态

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1582]
## 缺陷描述

![网易云音乐 for deepin](https://user-images.githubusercontent.com/12093211/68207711-7755b500-000a-11ea-8df5-c6f8470bb9e0.png)
上面是我截的图，只进行了很普通的操作都会导致这种僵死状态

### 发行版以及版本

deepin15.11

**Comment by widon1104** [comment]
有时候网易云音乐for deepin播着歌不动它，它自己偶尔也会变成这种白屏状态，鼠标点击它不会有任何反应

**Comment by widon1104** [comment]
今天抓到了crash堆栈，但是看不懂，不知道如何做才能提供更多信息
widon@widon-deepin:~$ netease-cloud-music
[00007f8aa0005450] access stream error: HTTP connection failure
[00007f8aa0005450] http stream error: cannot connect to m8.music.126.net:80
[00007f8aa0000d50] access stream error: HTTP connection failure
[00007f8aa0000d50] http stream error: cannot connect to m7.music.126.net:80
Received signal 11 <unknown> 000000000000
#0 0x7f249edcc526 <unknown>
#1 0x7f249edcc909 <unknown>
#2 0x7f24a4f02060 <unknown>
#3 0x7f24a171a694 <unknown>
#4 0x7f24a172acd9 <unknown>
#5 0x7f24a174e241 <unknown>
#6 0x7f24a12fabda <unknown>
#7 0x7f24a12fb76e <unknown>
#8 0x7f24a134b192 <unknown>
#9 0x7f24a12f9411 <unknown>
#10 0x7f24a168c342 <unknown>
#11 0x7f24a1756d62 <unknown>
#12 0x7f249ec5d16b <unknown>
#13 0x7f249ec5d43e <unknown>
#14 0x7f249ec66e8f <unknown>
#15 0x7f249ec6765d <unknown>
#16 0x7f24a1198672 <unknown>
#17 0x7f24a1198eec <unknown>
#18 0x7f249edcdd21 <unknown>
#19 0x7f249edf2800 <unknown>
#20 0x7f249edf3baf <unknown>
#21 0x7f249edf40f1 <unknown>
#22 0x7f249edf4fa9 <unknown>
#23 0x7f249ee1c38a <unknown>
#24 0x7f24a1c03b50 <unknown>
#25 0x7f249ed0f8ea <unknown>
#26 0x7f249ed0fb7f <unknown>
#27 0x7f24a00a0dd6 <unknown>
#28 0x7f24a00a0e6a <unknown>
#29 0x7f249ed0ece8 <unknown>
#30 0x7f249ed31670 <unknown>
#31 0x7f249da9ea03 cef_execute_process
#32 0x7f24a7e63d8f <unknown>
#33 0x7f24a7e321da QCefInit()
#34 0x562a63356522 <unknown>
#35 0x7f24a4eef2e1 __libc_start_main
#36 0x562a6335868a <unknown>
  r8: 0000000000000000  r9: 0000000000008000 r10: 00007f24a4287968 r11: 000015edae0e8008
r12: 000013f6546a3b18 r13: 000009ea1559de48 r14: 0000000000000001 r15: 0000562a657bb800
  di: 000032cca9e8c488  si: 0000562a65bd8120  bp: 0000562a65bd8120  bx: 000009ea15567ad0
  dx: 0000562a65bd8120  ax: a17334d200007f24  cx: 0000562a65bd8120  sp: 00007fff23e038e8
  ip: 00007f24a171a694 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000000
trp: 000000000000000d msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
