### ISSUE TITLE
希望deepin系统支持safe-rm，并默认安装safe-rm

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1584]
## 缺陷描述

现在系统安装了safe-rm会报找不到rm命令的错误
widon@widon-PC:/tmp$ ls /usr/bin/rm -lh
lrwxrwxrwx 1 root root 7 1月  20  2016 /usr/bin/rm -> safe-rm
widon@widon-PC:/tmp$ rm 1.txt 
safe-rm cannot find the real "rm" binary

### 发行版以及版本

deepin15.11

**Comment by BLumia** [comment]
在基于 buster 的仓库上（v20）未能复现，手边没有其它环境供测试。另外请注意，你**不需要**也**不应该**把 `rm` 链接到 `safe-rm`。

暂时没有默认安装 safe-rm 的计划，有需要请自行安装。

**Comment by widon1104** [comment]
不安装safe-rm的deepin下，执行sudo rm -rf / 会发生什么？

**Comment by BLumia** [comment]
不加 `--no-preserve-root` 的话什么都不会发生（
