### ISSUE TITLE
Glaring Security Issue's

### ISSUE THREAD

**Issue by mikepuerto** [linuxdeepin/developer-center#1587]
## Describe the bug
When using an external monitor, it is possible to bypass the lock screen.

## To Reproduce
1. Plug in an external monitor to a notebook/laptop
2. Close the lid and put it to sleep
3. Open the lid
4. "Enjoy" controlling someone else's machine to steal their private information or break into  someone else's without hiding your identity. (yes that was sarcasm)

## Expected behavior
The login screen scales back to the size of the laptop screen 

## Screenshots
![image](https://user-images.githubusercontent.com/104170/68730601-2e1ddc00-059b-11ea-8254-4ceb80d57184.png)

## Enviroments:
Deepin Linux Latest Stable on a Matebook XPRO and a 27" Dell with nvidia gsync 144hz

### Distro & Version
Deepin Linux 15.11 

### Related package version
Trying to avoid using the word "latest" but I'm using the latest stable version of the login screen, lol?

### Additional context
I can reproduce this everytime I've tried. The only thing I'm not able to do it open the launcher. I can click anything in the Dock... all it takes is a quick click on the terminal icon and I'm golden. I also found that passwords are stored in pretty much plain text as I was digging around looking for a syslog not too long ago. Maybe not the most constructive way to end this but I've never seen a Linux distro that was so insecure. Deepin certainly has something going for itself but with these issues it's a deal breaker and I'm surprised no one else has brought these things up.... at least not that I can find. As much as I love the ui and speed it's back to Ubuntu for me.

**Comment by Mark-AAAA** [comment]
:O

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
