### ISSUE TITLE
Settings panel is scrolling in a stuttery motion in Arch

### ISSUE THREAD

**Issue by kaymio** [linuxdeepin/developer-center#159]
The movement is not fluid but is stuttering along with a 0,5-1 second delay.

**Comment by oberon2007** [comment]
https://github.com/linuxdeepin/dde-control-center/issues/45

**Comment by jouyouyun** [comment]
@sbwtw

**Comment by justforlxz** [comment]
This question has not been answered for too long and will be closed. If there is a need to continue the discussion, it will be reopened.
