### ISSUE TITLE
启动器分类排序和拖动

### ISSUE THREAD

**Issue by lizhuangs** [linuxdeepin/developer-center#1590]
deepin20将大改启动器，但是实话说15.11以前的启动器太难用了。我很少用。基本都是放在任务栏。偶尔会用一下搜索。
1、启动器默认分类顺序不能修改，比如第一个是网络应用，第二个是社交。做为开发人员，我希望的是第一个是编程开发，而不是我每次进来都要点一下分类，希望后面的版本可以拖动修改这个分类顺序，满足不同人的需要。
2、图标顺序和分类，默认启动器不分类，图标顺序是可以拖动的。分类之后，图标也不能拖动了。
心累的是，图标的分类还是错误的。这个问题我另外提了一个issue。我希望的是分类以后，我也可以拖动图标的顺序和分类。比如eletrem默认显示在系统管理是错误的，我可以拖到编程开发中任何一个位置。

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
