### ISSUE TITLE
Seems like dock application showing up in the dock ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1591]
As you can see the dock is showing as a dock application(see the preview window) in the dock ...

![image](https://user-images.githubusercontent.com/3283676/68989756-02d40f00-0871-11ea-91ea-6b1973f95536.png)

right click of this icon on dock is showing "Window 39845900" ... force quitting closes the whole dock ...

![image](https://user-images.githubusercontent.com/3283676/68989773-4e86b880-0871-11ea-860e-73d22c5570b3.png)

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
