### ISSUE TITLE
文件管理器的打开/另存为对话框能否增加“选项”按钮？

### ISSUE THREAD

**Issue by zwpwjwtz** [linuxdeepin/developer-center#1593]
有些第三方软件（e.g. Audacity）的打开/另存为对话框包含“选项”(Options)按钮，用于选择打开/保存文件的格式和属性等。如果使用深度文管自带的对话框，则无法修改这些选项，必须手动关闭“使用Deepin文件管理器的文件选择对话框”（来回切换不方便）。

不知道技术上能否实现：增加一个额外的“选项”按钮，点击后可以弹出第三方的选项对话框呢？

**Comment by BLumia** [comment]
方便提供一下截图吗，我在我目前环境下没看到有“选项”这个按钮，可能和我复现方式不对有关系（我的步骤是打开 audacity 后直接按保存）。

如果应用程序有设置的话，事实上文件管理器提供的打开文件对话框也会有格式选择的位置的（下方部分的下拉框）。文件管理器提供的打开文件对话框应该可以满足至少 `QFileDialog` 提供的所有对应接口所对应的对等功能，同时也以 DFileDialog 接口提供了一些额外的功能供 DTK 应用使用，不过 GTK 应用的打开文件对话框可能会有一部分功能差异，还待收集。

**Comment by zwpwjwtz** [comment]
我做的操作是导出音频（Ctrl+Shift+E），而不是保存项目。

使用Audacity自带的对话框（应该是wx的原生对话框）：
![Audacity_ExportAudio_NativeDialog](https://user-images.githubusercontent.com/8875892/69725092-a0ef9100-111d-11ea-8c36-7a47a6778ac3.jpg)

使用深度文管提供的对话框：
![Audacity_ExportAudio_DtkDialog](https://user-images.githubusercontent.com/8875892/69725095-a1882780-111d-11ea-9eb4-6d0d1c85352a.jpg)

**Comment by BLumia** [comment]
感谢提供进一步信息，我们会考虑后续支持 :)

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
