### ISSUE TITLE
深度看图：GIF增加快捷键暂停、继续

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#1595]
需求：https://bbs.deepin.org/forum.php?mod=viewthread&tid=185843&extra=
实现：https://github.com/sonichy/HTYImageViewer/blob/master/mainwindow.cpp#L597

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
