### ISSUE TITLE
Adjust position in context menu

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#1597]
To create a new document in the context menu; There are 2 text document options. The last option is Plain Text (from Deepin Editor) - as this application is native to the system, is there any way to make Plain Text your first choice? Leaving Office Text as second option.

Note: Users often need to create a Plain Text document... and end up clicking on the Office Text document.

![DeepinScreenshot_Select area_20191127021611](https://user-images.githubusercontent.com/45263160/69695790-4ffb8080-10bc-11ea-93c4-e88e80e2a426.png)

**Comment by BLumia** [comment]
We have plan to make the default new document template tweakable by user, but this feature probably won't comes with next major release. Thanks for the feedback :)

**Comment by alexwender1** [comment]
> We have plan to make the default new document template tweakable by user, but this feature probably won't comes with next major release. Thanks for the feedback :)

You did not understand. I say reorder the position of the items:
1. _Plain Text_ (**from the last position, it will be in the first position**)
2. Office Text
3. Spreadsheet
4. Presentation

**Comment by BLumia** [comment]
> > We have plan to make the default new document template tweakable by user, but this feature probably won't comes with next major release. Thanks for the feedback :)
> 
> You did not understand. I say reorder the position of the items:
> 
> 1. _Plain Text_ (**from the last position, it will be in the first position**)
> 2. Office Text
> 3. Spreadsheet
> 4. Presentation

I know, but actually we plan to remove these three office file templates and make it customizable for different applications. For example, if you didn't got any office suite software installed(which means maybe the current user don't need to create and edit these type of files at all), there won't be any option about create an new `doc`, `ppt` or `xls` file. If you install WPS for example, WPS can vendor its supported template files so you can create these files with template provided by WPS. If you install a new Markdown editor or PHP IDE, it can vendor its `.md` and `.php` template file for user to use.
