### ISSUE TITLE
深度系统监视器不显示cpu温度

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1598]
## 缺陷描述

深度系统监视器不显示cpu温度，希望添加cpu温度的显示，我觉得这个参数比较有用

**Comment by redchenjs** [comment]
装个lm_sensors包，然后运行sensors就能看了

**Comment by redchenjs** [comment]
不过基于向win10看齐的原则，此参数不应该在系统监视器中显示

**Comment by widon1104** [comment]
1) deepin仓库里面没有lm_sensors包，安装麻烦
2) win10没有的，deepin也可以有

**Comment by redchenjs** [comment]
@widon1104 误，是lm-sensors :joy:

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
