### ISSUE TITLE
dde-kwin vs deepin-kwin

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/developer-center#1599]
May I ask what the deal is with the two different repos **dde-kwin** and **deepin-kwin**?
Both had releases on July 30, one of **v5.0.0**, the other of **v5.14.5.1**. So it looks to me, they are both relevant...!?
Which one is being used in the official Deepin v20?

**Comment by BLumia** [comment]
AFAIK **deepin-kwin** is a fork of the original kwin repo with some bugfix patches from deepin which not (yet) get merged into the kwin codebase and **dde-kwin** add dde integration with kwin. Not sure about other details.

cc @hualet @zccrs

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
