### ISSUE TITLE
在控制中心選擇字體後並沒有作用，調整字體大小也沒作用

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#160]
在控制中心不管怎么选，永远都会回到 unsupported font，调整字体大小也失效
OS: antergos (archlinux)

![deepinscreenshot20170212221737](https://cloud.githubusercontent.com/assets/20014762/22976674/bb1e4be2-f3c6-11e6-8ece-0d79f5bcbc39.png)
![deepinscreenshot20170212221746](https://cloud.githubusercontent.com/assets/20014762/22976675/bb26786c-f3c6-11e6-89b5-7a6d57d00b0d.png)
![deepinscreenshot20170212221753](https://cloud.githubusercontent.com/assets/20014762/22976673/bb1b573e-f3c6-11e6-8aa6-091589538830.png)

**Comment by GreatFive** [comment]
我也遇到了这个问题

**Comment by JulianLai** [comment]
希望有辦法修復，否則字體太小眼睛滿累的

**Comment by Acris** [comment]
@hualet @sbwtw 一样的问题，无法设置字体和大小，而且默认字体比较难看，请问下这是已知BUG还是我系统的问题？系统是Arch Linux。

**Comment by Acris** [comment]
@JulianLai 安装dconf-editor 然后使用dconf-editor修改一次字体设置后，deepin control center中的字体设置就变为可用了，你可以尝试一下，不过请谨慎使用dconf-editor。

**Comment by BobbyBabes** [comment]
@Acris `dconf` doesn't resolve anything (for me).

It doesn't recognise the existing keywords `font-monospace` and `font-standard` when trying to `write` new values. But it does `read` and `dump` these 2 keywords.
It does recognise and allow all operations on the keyword `font-size`. But that doesn't change the font size.
In Deepin Terminal I can change `font` and `font size` successfully. To mono spaced or proportional spaced. So the fonts themselves are not damaged.
Prior to issueing the commands below, I've also ran `mkfontscale` followed by `mkfontdir` in all font directories.

```Bash
sudo mkfontscale -- "/usr/share/fonts/100dpi" "/usr/share/fonts/75dpi" "/usr/share/fonts/misc" "/usr/share/fonts/TTF" "/usr/share/fonts/OTF" "/usr/share/fonts/noto"
sudo mkfontdir -- "/usr/share/fonts/100dpi" "/usr/share/fonts/75dpi" "/usr/share/fonts/misc" "/usr/share/fonts/TTF" "/usr/share/fonts/OTF" "/usr/share/fonts/noto"
```


```Bash
dconf dump /com/deepin/dde/appearance/
[/]
icon-theme='Paper'
font-size=12.0
font-monospace=''
font-standard=''
background-uris=['file:///home/BobbyBabes/Pictures/Wallpapers/halle_berry_catwoman_pose_pants_mask_ears_patience_phillips_17647_1920x1080.jpg', 'file:///home/BobbyBabes/Pictures/Wallpapers/catwoman-anne-hathaway-3.jpg', 'file:///home/BobbyBabes/Pictures/Wallpapers/Summer-Glau-Wallpapers-Shoot-Gun.jpg', 'file:///home/BobbyBabes/Pictures/Wallpapers/barbarella_desktop_1920x1080_hd-wallpaper-1119737.jpg', 'file:///home/BobbyBabes/Pictures/Wallpapers/adhemas.com-front-cropped-to-16-9.jpg']
gtk-theme='Arc-Grey'
```

```Bash
dconf read /com/deepin/dde/appearance/font-size
12.0
dconf read /com/deepin/dde/appearance/font-monospace
''
dconf read /com/deepin/dde/appearance/font-standard
''
```

```Bash
dconf write /com/deepin/dde/appearance/font-size 16.0
dconf read /com/deepin/dde/appearance/font-size
16.0
```

```Bash
dconf write /com/deepin/dde/appearance/font-monospace 'Fira Mono'
error: 0-1:unknown keyword

Usage:
  dconf write KEY VALUE 

Write a new value to a key

Arguments:
  KEY         A key path (starting, but not ending with '/')
  VALUE       The value to write (in GVariant format)

```

```Bash
dconf write /com/deepin/dde/appearance/font-standard 'Fira Sans'
error: 0-1:unknown keyword

Usage:
  dconf write KEY VALUE 

Write a new value to a key

Arguments:
  KEY         A key path (starting, but not ending with '/')
  VALUE       The value to write (in GVariant format)

```

```Bash
sudo dconf update
[sudo] password for BobbyBabes: 
error: Error opening directory '/etc/dconf/db': No such file or directory

Usage:
  dconf update

Update the system dconf databases


```


Changing the value of the keywords directly in "`/usr/share/glib-2.0/schemas/com.deepin.dde.appearance.gschema.xml`" doesn't change anything either.

So still `(Unsupported font)` in `Deepin Control Center` at "`Personalization >> Font >> Standard Font` and `Personalization >> Font >> Monospace Font`".

This was also reported at the Deepin website : https://translate.google.com/translate?hl=en&sl=zh-CN&tl=en&u=https%3A%2F%2Fbbs.deepin.org%2Fforum.php%3Fmod%3Dviewthread%26tid%3D134884

**Comment by Acris** [comment]
@BobbyBabes Dconf editor worked for me, you can try to use dconf editor GUI to set font
 Maybe it's a known issue, we should wait a official fix.

**Comment by hualet** [comment]
@jouyouyun

**Comment by BobbyBabes** [comment]
I can't wait any longer. Dual 4K and one 1440p screen connected (web design and dev testlab). Headache and burning watery eyes (from too small font size with fonts I don't want to use) is what will happen while I have to wait. I will be reinstalling Arch (just to be sure) and a different desktop today. I need to use my desktop for work again tomorrow.

**Comment by timhere** [comment]
I also cannot set the standard font, the monospaced font, nor change the font size on arch deepin DE. 

I haven't tried the dconf option - I will explore that.

**Comment by jouyouyun** [comment]
Please install `noto-fonts`, then exec `gsettings reset com.deepin.dde.appearance font-standard` and `gsettings reset com.deepin.dde.appearance font-monospace`.
Then try to change font size again.

**Comment by BobbyBabes** [comment]
@jouyouyun I restored the last full backup of Arch+Deepin that I had to an old SSD and booted from that. Then I tried your fix.
I'm confirming that it resolved the issue. After the reset, Noto was selected for standard and mono fonts. Font-size needed a reboot. I could select any font from Deepin Control Centre.
I'm adding this as a new multi-boot option to Grub.

**Comment by oberon2007** [comment]
Something is strange here and it seems the default gsettings are not respected for some reason. My suspicion is that some gsettings/wrapping/overriding interfere or contradict each other.

I just built a new ISO and when I boot it up for the first time and open dconf editor before doing anything else, font settings are already showing as if the settings would have been changed by the user and they are empty:

![font_dconf](https://cloud.githubusercontent.com/assets/11800714/24459541/1ba71250-149c-11e7-9269-1ed6c5a0456c.png)

When I reset them to the default, they show correctly 'Noto Mono' and 'Noto Sans'. And, yes noto-fonts are installed here aswell.
When I now open the control-center, Noto fonts are correctly specified and I can change the settings, too. But when I open control-center before resetting gsettings to the default it just says "Standard Font" and "Monospaced Font" and the checkmark sits at the bottom of the list on "(Unsupported Font)" and I cannot change it.

**Comment by jouyouyun** [comment]
@oberon2007 Oh, this is a bug when font name empty, I will fix it in the near future.

**Comment by timhere** [comment]
@jouyouyun Happy to confirm executing `gsettings reset com.deepin.dde.appearance font-standard` and `gsettings reset com.deepin.dde.appearance font-monospace` resolved this issue for me.

**Comment by jouyouyun** [comment]
@oberon2007 I check the font settings codes, it should reset font when name is empty.
Can you paste the log for dde-session-daemon when problem occurred? Try to exec `killall dde-session-daemon;/usr/lib/deepin-daemon/dde-session-daemon -v`, thanks!

**Comment by oberon2007** [comment]
```
$ grep "font" log
<warning> manager.go:142: load default font config failed: open /usr/share/deepin-default-settings/fontconfig.json: no such file or directory
<debug> manager.go:203: resetFonts fonts.SetFamily failed Invalid standard id ''
<warning> handle_gsetting.go:61: Set font-standard failed: Invalid font family ''
<warning> handle_gsetting.go:61: Set font-size failed: Invalid standard id ''
<warning> handle_gsetting.go:61: Set font-monospace failed: Invalid font family ''
```

**Comment by oberon2007** [comment]
What should have provided **/usr/share/deepin-default-settings/fontconfig.json** file?

**Comment by oberon2007** [comment]
The missing fontconfig however doesn't seem to be the real problem here...

**Comment by jouyouyun** [comment]
@oberon2007  download the file: [dde-session-daemon](https://drive.google.com/file/d/0B4hDvVIwZ49ESjZIS3YydDMzZWc/view?usp=sharing), then exec `chmod +x dde-session-daemon` and `killall dde-session-daemon;./dde-session-daemon`, then check dde-control-center whether normally, thanks!

**Comment by oberon2007** [comment]
Thanks @jouyouyun . It works as a workaround :stuck_out_tongue_winking_eye: 

![](http://imgur.com/JxYwFT8.png)

As you can see dconf-editor still highlights the entries, indicating that they have been modified, not really set to the default. So something is still just not right with the default gsettings...

**Comment by jouyouyun** [comment]
GSettings default value is not very good deal with the language under the multi-language, so add a file to handle, it is recommended to install this file by default.
The file(/usr/share/deepin-default-settings/fontconfig.json)  in deepin-default-settings

**Comment by oberon2007** [comment]
Ok good to know. I'll install the fontconfig then 👍 Thanks!

**Comment by BobbyBabes** [comment]
@jouyouyun 
> GSettings default value is not very good deal with the language under the multi-language

This means application settings for Gnome desktop, and for all Gnome/GTK based desktops ?
(Just for my understanding. )

**Comment by jouyouyun** [comment]
@BobbyBabes Just need for DDE, which is what the product manager requires, and need to use different fonts for different languages.

**Comment by BobbyBabes** [comment]
@jouyouyun OK that's reassuring. I thought that this could also happen with the other Gnome and GTK based installations I have.
Thanks.

**Comment by funilrys** [comment]
Just a question what should I do when it's happen in fresh install ? :smile_cat:

**Comment by funilrys** [comment]
Finally found it :+1:

>Please install `noto-fonts` firstly, then exec `gsettings reset com.deepin.dde.appearance font-standard` and `gsettings reset com.deepin.dde.appearance font-monospace.`
Then try to change font size again.

I think we should add it to troubleshooting section of arch wiki or even better add noto-fonts to dependencies somewhere ...

**Comment by oberon2007** [comment]
I agree. Since no to is specified in gsettings it should be a depends of **deepin-desktop-schemas**

**Comment by jouyouyun** [comment]
This bug has been fixed in dde-daemon, please be patient waiting for updates.

**Comment by Acris** [comment]
@jouyouyun Hello, I have a question, I set the font size to 12 in control center, but in dconf editor the font size is 9. When I change it to 16 in control panel, the dconf editor shown is 12 ,is this a bug ?

**Comment by funilrys** [comment]
Same here @Acris didn't notice it :+1:

**Comment by jouyouyun** [comment]
@sbwtw

**Comment by Acris** [comment]
The deepin file manager's font size don't changed when I change font size in control center...

**Comment by BobbyBabes** [comment]
@Acris Yes you're correct. That's why I installed Nautilus.
For the rest, it's a bit of a mixed bag. For instance, I have Nautilus installed and the fonts in that are changed instantly when clicking or dragging the font size slider in CC.
Google Chrome requires a restart to pickup the new font size from CC, in its tabs and right-click menu,. And so on.

**Comment by jouyouyun** [comment]
@Acris The font size in dde-control-center is PX, in dconf-editor is PT, so not equal!

**Comment by Acris** [comment]
@jouyouyun Thank you, it's my mistake, haha

**Comment by BobbyBabes** [comment]
@jouyouyun @Acris
> The deepin file manager's font size don't changed when I change font size in control center...

Where was dconf-editor mentioned ?

Also, Deepin File Manager is oblivious of all styling attempts.

**Comment by jouyouyun** [comment]
@BobbyBabes  dde-file-manager's font size will work after re-open.

**Comment by Acris** [comment]
@jouyouyun I even tried reboot my laptop after chang font size, but the file manager's font size still not changed :(

**Comment by BobbyBabes** [comment]
@jouyouyun Not here. Just tried it again. The font size in CC is set to 16 px. Opened Deepin File Manager. The font size in Deepin File Manager looks too small for 16 px already.
Changed the font size in CC from 16 px to 11 px. Closed then opened Deepin File Manager. No change in font size. Changed the font size in CC back to 16 px. Closed and opened Deepin File Manager. No change. The same small font size.
The Settings in Deepin File Manager do not offer a font size setting.

**Comment by jouyouyun** [comment]
@dragondjf

**Comment by JulianLai** [comment]
@jouyouyun The font size won't change for every QT app.

**Comment by jouyouyun** [comment]
QT apps need to restart

**Comment by JulianLai** [comment]
@jouyouyun It doesn't work, I even reboot my computer.

**Comment by jouyouyun** [comment]
@sbwtw

**Comment by jouyouyun** [comment]
Fixed!
