### ISSUE TITLE
dde-kwin 有时候不显示带参数启动的程序

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#1601]
为了是Firefox在kwin下隐藏标题栏，Exec加上了启动参数：env MOZ_GTK_TITLEBAR_DECORATION=client，变成：Exec=env MOZ_GTK_TITLEBAR_DECORATION=client /media/sonichy/soft/Linux/firefox/firefox %u
有时候，Firefox在任务栏有图标，但是没有窗口，一度以为是参数问题，杀死kwin_x11，窗口显示了，但是内容是历史桌面，后来发现窗口虽然看不见，但是鼠标可以响应，所以确定是窗管的问题。

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
