### ISSUE TITLE
启动器文件夹功能支持或自定义分组

### ISSUE THREAD

**Issue by lizhuangs** [linuxdeepin/developer-center#1603]
### 缺陷描述
希望启动器支持文件夹功能，这样可以自定义分组，文件夹与文件夹之间或与快捷方式之间可以直接拖动。
现有的分类不好用，而且许多分类是错误的。当然，如果不支持文件夹功能，那么启动器可以自己新建分组功能，也是不错的。

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
