### ISSUE TITLE
deepin-screen-recorder does not record a second monitor

### ISSUE THREAD

**Issue by xereda** [linuxdeepin/developer-center#1604]
deepin-screen-recorder does not record a second monitor

## To Reproduce
With two monitors enabled, try recording an animated gif on the second screen. In the expanded screen.

## Expected behavior
Be able to record videos from any screen connected to the operating system.

### Distro & Version
Ubuntu 19.04
Gnome 3.32.1

### Related package version
deepin-screen-recoreder 2.7.7-1

**Comment by jerome-diver** [comment]
I try it and yes, same problem there. If i want to record from an other one screen, i need to start the deepin-scree-recorder command from this other one screen. There is no other way to select a screen or to record all screen in the same file.
Also, try to start from terminal and you would see at end time that QThread process finished with an error (core dumped).
So i think Qt Thread is badly managed (don't finish thread before to finish process correctly).

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.

**Comment by jerome-diver** [comment]
Why do you close this issue ? Do you resolve it ? What is the idea to close an issue who is not fixed ?

**Comment by justforlxz** [comment]
> @justforlxz Why do you close this issue ? Do you resolve it ? What is the idea to close an issue who is not fixed ?

Currently only supports recording a single screen, this issue will be recorded as a new feature.

**Comment by meiyixiang** [comment]
Now it can record 2 screens, please upgrade the system.
