### ISSUE TITLE
The new document dialogue could use open formats

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/developer-center#1605]
On the file manager, when you right clic on the background of any folder you get a "new document" dialogue.

This dialogue allows to create office documents using old Microsoft Office formats. I think it would be interesting those to be in Open Document format instead.

**Comment by alexwender1** [comment]
https://github.com/linuxdeepin/developer-center/issues/1597

**Comment by BLumia** [comment]
The most easy way to customize it right now is check out your `xdg-user-dir TEMPLATES` (make sure it's not pointed to your home path which means disable this type of user directory), and drop your templates files inside this folder. Then next time you launch a new dde-file-manager instance, the files in that folder will get shown in that context menu :)

As @alexwender1 mentioned, we are planned to make that context menu customizable for application developers, like adding entries in the create new file menu and etc. The application developers still need to manually adding the support so new entries can be shown btw.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
