### ISSUE TITLE
[bug] Arrow keyboard keys disable the touchpad

### ISSUE THREAD

**Issue by patyiscoding** [linuxdeepin/developer-center#1606]
## Describe the bug
Every couple of days, my arrow keyboard keys get into a mode in which
- **down arrow** disables the touchpad
- **top and right arrows** stop working
- and the **left** arrow works as usual

I found that the insert key enables the touchpad back, though the arrow keys still remain as before.

## To Reproduce
That's the catch; I'm not sure what causes the issue to appear over and over again. I suspect it's a combination of some keyboard keys though. Maybe there's someone who experiences the issue as well and has found that out.

### Distro & Version
Linux Deepin 15.8

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
