### ISSUE TITLE
文件选择对话框总会启动 dde-desktop 造成桌面重叠

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#1609]
Deepin 环境安装 mate 和 xfce，并在深度文管取消了使用深度文件选择对话框，在 mate 和 xfce 系统拉起文件选择对话框仍然会启动  dde-desktop，覆盖当前桌面，视觉上2个桌面重叠，实际上只能点击深度桌面的内容，严重影响其他系统的使用体验。

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
