### ISSUE TITLE
Arch+DDE桌面DOCK栏时间显示问题

### ISSUE THREAD

**Issue by MeansonChen** [linuxdeepin/developer-center#1610]
## Describe the bug
我喜欢使用24小时显示模式，当我设置成功后，重启机器后就会导致该设置失败。

## To Reproduce
1.设置时间为24小时显示模式
2.重启机器。注：不断电重启，而并不是先关机，在开机，后者这样做不会出现这个bug。
3.此时时间显示模式回到12小时模式

## Enviroments:
archlinux + dde桌面环境

### Distro & Version
deepin-dock 5.0.0-
Linux archlinux 5.4.2-arch1-1
deepin 15.11

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
