### ISSUE TITLE
Addons for Deepin File Manager

### ISSUE THREAD

**Issue by wuniversales** [linuxdeepin/developer-center#1611]
Hi,
It would be great to give the possibility to create add-ons for Deepin File Manager.
For example, in dolphin, I have created an add-on, which, using the secondary mouse button, allows you to analyze the file chosen by the user with several online antivirus programs.
It would be great to implement it in Deepin File Manager.
Greetings and good work

**Comment by BLumia** [comment]
It's possible to do but I don't have time to write an English version of the document for now, you can take https://github.com/linuxdeepin/dde-file-manager/issues/21 as a reference for the current released version :)

**Comment by wuniversales** [comment]
Great :D
Is there any kind of "store" to be able to put the Deepin File Manager plugins?
Thanks

**Comment by BLumia** [comment]
Currently no. Thanks for the suggestion :)

**Comment by wuniversales** [comment]
As a subject, I would like the deepin plugins to be uploaded in Pling.
https://www.pling.com/
But well, do as you see fit.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
