### ISSUE TITLE
deepin-control-center (v 4.10..) QLayout error

### ISSUE THREAD

**Issue by alexk136** [linuxdeepin/developer-center#1613]
Hi every body!
So after last update dde-control-center not working. If you click on icon in panel .. nothing happen, calling ddecc from main menu opens ddecc shorly and close.

on lunch ddecc from comand line i recive error:

QLayout: Attempting to add QLayout "" to MainWidget "", which already has a layout

restarting, updating, reinstalling.. nothing helps.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
