### ISSUE TITLE
Using Arch as base

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/developer-center#1616]
This just a suggestion, in case you ever decided to implement it. It's more for you to be informed than anything else.

I used to be involved in Ubuntu Quality assurance for a long time. I coordinated the Papercuts project for a while, I mentored in Google events in regard of the Ubuntu Quality Team, and for some time I was the person with the greatest karma in Launchpad who wasn't paid by Canonical for handling bug reports. I'm also trained in Lean Manufacturing and quality assurance in general.

This is my note to you: counter-intuitively Arch Linux, even when the software is fresher, has way less bugs than Ubuntu or Debian. Planned releases are an inferior paradigm of software quality than rolling releases. With rolling bugs come gradually, with releases they come all together and you never have time to fix them.

Deepin will likely greatly benefit of using Arch as base.

**Comment by BLumia** [comment]
Then deepin on MIPS for example will become a big issue I guess ;)

**Comment by es20490446e** [comment]
Is people using Deepin on MIPS?

**Comment by BLumia** [comment]
Yep, we have loongson support for example.

**Comment by es20490446e** [comment]
Makes sense, not depending entirely on Trump Land technology 😂

Just hypotetically, for my own info. Do you think that if Arch supported MIPS could Deepin change to it?

Or do you see any other disadvantage of doing so?

**Comment by BLumia** [comment]
Beside mips we also have other CPU arch support for enterprise user, and since enterprise customer probably won't want a rolling-update distro to use, so use debian as base is still the better choice for current state I think.

BTW I do think using Arch as base is a good idea if we have a separated team to maintain the community version of Deepin.

**Comment by es20490446e** [comment]
This is a recurring conversation (due to the frequent issues people experience within their companies).

I think that Enterprises has various limiting beliefs on their approach to managing infrastructure. They are using a model adequate for the 90s, when developing software was slow and networks were not very reliable. They fail to see that the world has changed so much since then.

For example they assume that a rolling distribution is something like Debian testing. Debian, compared with modern rolling distributions, is _notably_ buggy. This is because on Debian fixing any bug takes a while, where in modern rolling distributions the package maintainer can instantly clone the package definition, change it and even roll back it if needed.

They also think that by freezing the release they can have tighter control about the compatibility of the applications they use and the operating system.

What happens in practice is that, by using a long release model, like that provided by Ubuntu or Debian stable, all the bugs and incompatibilities come all together on the next release. So updating is always a nightmare, and they avoid it as much as possible.

As result they usually end with a system that is _many_ years behind the state of the art, that doesn't allow to install modern applications, and that has issues that have been fixed a long time ago. So employees hate it, and if possible try to use their own machines.

When I changed to Manjaro, derived from Arch, it wasn't because for having more up to date apps. But mainly because it was notably less buggy. I no longer had to worry about my system no longer booting one day, or Network Manager being broken till the next Ubuntu release.

The solution for Enterprises is:
- Making fixing any bugs as easy as possible. Rely on speed, not on control, for fixing them. Counterintuitively quality assurance shall only be for critical parts, beyond that is _waste_.
- Release as soon as possible for applications, so fixes always reach as soon as possible. If a particular application is always buggy, interpret it as badly maintained, and drop it.
- Release system components weekly, after _manually_ testing that the thing still boots and has no major perceptible defects.
- Instead of using in home monolithic solutions for all employees, leverage already existing platforms on the Internet and allow the employees to choose their own technology. Do not control the infrastructure, but the security policies. Educate the user on how to securely store their passwords and data, putting that info in an easily accessible and brief page.

**Comment by BLumia** [comment]
Things is way mo complex than managing a single product line and doing regular release. When enterprises customer requires us maintain their standalone repository (almost each customer have different standalone repository with different version of our product and also with different OEM stuffs), In some case access package repository and do a system upgrade via Internet is not even an option for some of our customers. Also rolling update will cost way more resources than do cycle release, it's not just a bugfix thing.

I actually agree with you in some point, believe me, it's possible but may not that easy to make that change. But still, different CPU arch support is a way more important reason why deepin choose debian as base :)

I haven't notice that Manjaro have its enterprises edition or enterprises service btw..

**Comment by es20490446e** [comment]
I see. Thanks and happy 2020 👍
