### ISSUE TITLE
Alt Left/Right not working

### ISSUE THREAD

**Issue by vincenzocaselli** [linuxdeepin/developer-center#1618]
In Eclipse (or other applications) **Alt-Left / Alt-Right** are not working as expected (=navigate to the previous/next view).
Alt-Up/Down instead are working right (so it's not a matter of Alt not recognized).

Is this problem related to Arch (I am using Manjaro) and to the fact that this key combination is reserved for switching to previous/next Virtual Console
https://wiki.archlinux.org/index.php/Linux_console#Keyboard_shortcuts

or (like other Arch users with other DEs are suggesting to me) is this related to Deepin keyboard bindings?

I already checked in Control Center, Shortcuts, but there is not any of them mapped.
I already checked also all the gsettings, but didn't find any hint.
Where this mapping may be located and fixed?

Thank you very much in advance
Vincenzo

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
