### ISSUE TITLE
网易云音乐1.2.0(build 0408) 播放歌曲提示网络失败

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1620]
## 缺陷描述

在我这边经常会出现播放歌曲等很久不能播放，然后失败的情况
提示网络失败的时候终端会打印如下信息：
12-25, 22:18:15 [Error  ] [                          0] void netease::AudioPlayer::handleMediaStatusChanged(netease::VlcMediaPlayer::MediaStatus) Invalid Media: "1409382131_4_7763-bitrate-320-mQUysP"
[00007ff8d40020f0] access stream error: HTTP connection failure
[00007ff8d40020f0] http stream error: cannot connect to m8.music.126.net:80

### 发行版以及版本

deepin15.11

**Comment by widon1104** [comment]
我试了一下，关闭ipv6可以修复这个问题

sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1

**Comment by imxys** [comment]
（挖坟）1.2.1 版本也是还有这个问题（我用的版本是Ubuntu 18.04.5）
命令行运行仍然是这个报错
我试过 https://blog.csdn.net/chauncygu/article/details/109143966 Ubuntu 下网易云音乐出现“加载失败，网络错误，可以在设置中发送反馈”问题及解决_AndrewGSD的博客-CSDN博客 的做法，不行

但现象有点不同
实际上这次软件打开时候点击听不了报错的歌，下次重启再打开，这首歌是缓存好了的，双击可以听

**Comment by myml** [comment]
执行`ping -c 3 m8.music.126.net;dig dig m8.music.126.net`贴下结果

**Comment by imxys** [comment]
> 执行`ping -c 3 m8.music.126.net;dig dig m8.music.126.net`贴下结果

感谢大佬回复疑问；如果是我这边提出的问题，不知道什么时候已经解决了，现在听网易云音乐都可以正常使用；我的电脑也已经更新到Ubuntu 20.04.3 with KDE。如果有出现问题我再用这个方法确认一下。

**Comment by myml** [comment]
好的，那我先关闭这个Issues了，谢谢你的反馈

**Comment by Zhiwei-Zhai** [comment]
ping -c 3 m8.music.126.net;dig dig m8.music.126.net
访问被拒绝。选项 -c 需要具有管理权限。
