### ISSUE TITLE
[BUG]无法解除DDE对Super+Space(切换键盘布局)快捷键的占用

### ISSUE THREAD

**Issue by Acris** [linuxdeepin/developer-center#1625]
## 缺陷描述
因为在使用JetBrains系列IDE，占用了Ctrl+Space用于代码补全，故希望将Fcitx的切换输入法快捷键由Ctrl+Space更改为Super(Windows)+Space，这样也和之前Windows 10切换语言的快捷键保持一致。

在更改快捷键的过程中，发现Super+Space已经被DDE占用，用来修改键盘布局，尝试了多种方法，均无法解除DDE对Super+Space的占用。

### 表现一
1、进入设置->键盘布局，取消勾选用于切换键盘布局的Super+Space，仅保留Alt+Shift。
2、打开Fcitx配置工具，将切换输入法快捷键设置为Super+Space。
缺陷表现：Super+Space无法切换输入法，Fcitx设置的快捷键不生效。
### 表现二
1、进入设置->键盘布局，取消勾选用于切换键盘布局的Super+Space，仅保留Alt+Shift。
2、进入设置-> 快捷键，随便更改一个快捷键为Super+Space，提示快捷键被切换键盘布局占用，是否替换，选择是，让后再将其恢复到之前的快捷键（此处也表明即使第一步取消勾选Super+Space了，但是快捷键仍然被占用）。
3、打开Fcitx配置工具，将切换输入法快捷键设置为Super+Space。
缺陷表现：设置完毕后，Super+Space生效，可以按预期切换输入法了。
**但是，注销/重启之后失效，需要重复以上步骤才行，说明注销/重启之后快捷键再次被DDE占用**

## 期望行为
在设置->键盘布局取消勾选Super+Space以后，该快捷键不再被DDE占用，可以任意分配给其他程序。

## 截图
待补充

## 复现环境:
无需特定环境

### 发行版以及版本
Arch Linux + Deepin Desktop 15.11 均已更新到最新版

### 相关的软件包版本
```
fcitx 4.2.9.7-1
fcitx-configtool 0.4.10-3
deepin-control-center 5.0.0-1
deepin-daemon 5.0.0-2
deepin-desktop-base 2:2019.07.10-1
deepin-desktop-schemas 3.13.9-1
startdde 5.0.1-2
```
更详细的Deepin软件列表参见：https://www.archlinux.org/groups/x86_64/deepin/

### 其他内容
其他用户反馈：https://bbs.deepin.org/forum.php?mod=viewthread&tid=179694

**Comment by Acris** [comment]
有人跟进吗？

**Comment by sunxfancy** [comment]
完全一样的现象，我希望把Ulancher的快捷键切到Ctrl+Space，输入法放到Super+Space就完全做不到，另外Alt+Space也被占用，希望Settings里面赶快把占用的快捷键补上吧

**Comment by z4yx** [comment]
遇到同样的问题，希望解决

**Comment by disburden** [comment]
19年的问题了，到现在没有任何进展吗？很影响体验

**Comment by tsic404** [comment]
在当前版本（V20）上测试了设置了super+space案件后，在jetbrains中可以使用Ctrl+Space进行补全操作。

**Comment by tsic404** [comment]
这个issue会被关闭
