### ISSUE TITLE
[bug] cannot open wine programs from dde-dock

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#1627]
## Describe the bug

We cannot open wine programs that are running on the applet by clicking on them.
## To Reproduce
1. Install any wine program(e.g. IDM) that runs on the applet.
2. Click on the program icon from the applet.
3. It will not open.

## Expected behavior

The wine app should start/open.

## Screenshots

[deepin-screen-recorder_Select area_20200102233405.mp4.zip](https://github.com/linuxdeepin/developer-center/files/4016732/deepin-screen-recorder_Select.area_20200102233405.mp4.zip)

## Environments:
DE: Deepin v15.11
### Distro & Version

Manjaro linux v18.1.5
### Related package version

deepin-dock  v5.0.0-4

**Comment by myml** [comment]
Sorry! deepin v15 is no longer maintained. try update to new version
