### ISSUE TITLE
热区设置可否添加自定义的命令

### ISSUE THREAD

**Issue by Eric-LGF** [linuxdeepin/developer-center#1630]
如题
我主要目的是为了，能够通过热区设置实现更快捷的方式查看雷神终端的内容，而不必使用快捷键。因为这个过程持续时间并不就，基本看一眼就行

**Comment by BLumia** [comment]
热区设置的界面里提供的选项是写死的（并且即将发布的 v20 版本以目前的情况来看热区设置界面也会默认禁掉），所以暂时不支持通过那个界面设置热区行为，不过热区设置界面实际就是把预设的值传到后端提供的对应 DBus 接口中，所以有兴趣的话可以考虑用 d-feet 或者 qdbusviewer 之类的工具看一下 `com.deepin.daemon.Zone` 这个下面提供的 DBus
 接口来满足你的需求。

**Comment by Eric-LGF** [comment]
非常感谢你的回复，对我的帮助很大
