### ISSUE TITLE
Missing Bluetooth option on the sidebar

### ISSUE THREAD

**Issue by javid-abd** [linuxdeepin/developer-center#1632]
## Describe the bug
Unexpectedly Bluetooth stops and disappears (connected to headphone). I attached a screen record  to make it much cleaner.

## Screenshots

![deepIn](https://user-images.githubusercontent.com/32272345/72244721-50b68a80-3608-11ea-915c-2bd7704d28ec.gif)

### Distro & Version
Edition: 15.11 Desktop
Type: 64Bit
Processor: Intel(R) Core(TM) I7 8750 CPU @ 2.20HGz x  12
Memory: 16gb

### Additional context

It happened more than once time to time, current fix is to reboot.

**Comment by myml** [comment]
Sorry! Try Deepin V20.
