### ISSUE TITLE
deepin可否模仿windows，死机也显示蓝屏界面 

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1633]
## 缺陷描述

 deepin有时候死机的时候完全就是僵死不动，很不友好，用户一脸懵逼
我建议deepin也像windows一样，死机蓝屏（或者绿屏），在蓝屏界面显示死机堆栈等信息，便于排查问题，这样要友好很多
有时候只是应用软件崩溃，可以想办法的恢复的可以不蓝屏，我说的蓝屏是系统出了不能恢复的严重问题必须重启才蓝屏，比如说内核崩溃

## 期望行为

死机蓝屏或者绿屏，在里面显示所有有用的信息

### 发行版以及版本

deepin15.11

**Comment by widon1104** [comment]
我觉得有必要加蓝屏界面，现在我的电脑内存有问题，用win10经常蓝屏，但是如果有蓝屏的话，蓝屏以后直接轻按一下电源键就可以关闭电脑
linux没有蓝屏，必须要长按电源键才能关闭电脑，这样用户体验不好，对电脑也很不好的

**Comment by xmuli** [comment]
Personally, I'm against it (personal opinion), and every time I see WIN10, it gives the impression that it's crashing.
Even on unix (mac), there is no blue screen effect, and very few people can really take advantage of the message, and more people choose to reboot or reinstall the system.

**Comment by justforlxz** [comment]
Unnecessary features, this issue will be closed soon.
