### ISSUE TITLE
打开空白文档时默认打开方式无效

### ISSUE THREAD

**Issue by wudidada** [linuxdeepin/developer-center#1634]
## Describe the bug

在设置.md文件默认打开方式为Typora后，当打开有内容的markdown文件时会正常使用Typora打开，但创建一个空白markdown文件后，则默认打开方式无效，会使用深度编辑器打开。
而只要文档中有一个空格，默认打开方式就会生效。

### Distro & Version

Deepin 15.5 sp2专业版

**Comment by BLumia** [comment]
专业版建议以专业版的渠道反馈问题。

自检的话，检查一下你的空白文件的 MimeType 是不是 Markdown 类型（text/markdown），默认打开方式认的是 MimeType 而不是扩展名（比如 .ts 文件可能是流媒体也可能上 Qt 翻译文件，我们并不是简单的根据扩展名来执行打开方式的，尽管变更扩展名可能会影响到 MimeType 的推断）。

**Comment by IceZero610** [comment]
找到编辑器对应的*.desktop文件，通常，这个文件位于~/.local/share/applications/ 或者是位于 /usr/share/applications/
打开，找到“Exec”行，正常情况下里面的内容应该是运行这个编辑器程序，没有传入文件的参数，在后面加上%U %f参数

**Comment by justforlxz** [comment]
https://wiki.archlinux.org/title/XDG_MIME_Applications 可以看一下这篇wiki，我们是严格按照 mimetype 标准实现的。
