### ISSUE TITLE
下载/上传行为呼出窗口长时间打开卡死

### ISSUE THREAD

**Issue by NorthWardTop** [linuxdeepin/developer-center#1635]
## 缺陷描述

类似于下载、上传、插入图片等类似动作，呼出的类似于下载的子窗口，这个子窗口若打开超过30-60秒或者更长，bug出现（子窗口消失，父窗口卡死无法关闭）

**Comment by BLumia** [comment]
"类似于下载的子窗口"是指什么窗口，方便贴个截图吗？

**Comment by NorthWardTop** [comment]
不知什么原因, 无法插入图片, 已使用邮件回复, 感谢

Attach files to your comment
Something went really wrong, and we can’t process that file.

**Comment by justforlxz** [comment]
似乎，现在没有这个问题了？
