### ISSUE TITLE
UOS 高分屏qt程序有缩放问题

### ISSUE THREAD

**Issue by htqx** [linuxdeepin/developer-center#1638]
## 缺陷描述
qt应用的面板会放大两倍，导致某些文字不可见。

## 复现步骤

安装vbox6.1 ，打开即可。
kmail 也会这样，这两个都是qt应用。

## 期望行为
正确的qt应用缩放。

## 截图
![{6DB{Q9@CSDSC)Y{RCT1GS3](https://user-images.githubusercontent.com/42466118/72773379-e58d3980-3c41-11ea-9ae1-5006f2ba7553.png)

## 复现环境:
uos rc 升级到正式版

### 发行版以及版本
uos 20

### 相关的软件包版本
qt5应用

**Comment by htqx** [comment]
我是4k屏幕，貌似安装kde也会自动给我调成两倍大。但是可以设置回来。但是dde不知道哪里设置。设置里面已经是1倍，并且其他dde应用正常。gnome应用也正常。

**Comment by justforlxz** [comment]
我这里没有问题呀，可能已经修复好了？
