### ISSUE TITLE
Feature Request : Deepin-Movie audio latency ... delay/advance option ... much needed modern(bluetooth TWS Headphones/earphones) age audio devices

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1639]
Hi Team Deepin,

Is it time to consider the TWS Bluetooth earphones/headphones **Audio Latency ... Delay / advance option** to be introduced into Deepin-Movie ?

After Apple Airpods ... which seems to have made $ 8 billion in its airpods sales alone which has triggered every other smartphone OEM's to follow suit and race into producing TWS Bluetooth earphones/headphones ... its crazy out there with the range of Wireless Bluetooth audio devices !!!

VLC has already got that feature ... so given my newly purchased TWS Bluetooth earphones ... i have no choice but to move to TLC player for now ... Until you people consider and add this requested feature !

thanks.

**Comment by meiyixiang** [comment]
Hello to maintenance phase current theater, will not develop new function in the late may be in the open source community to maintain, if don't know whether you are a developer
