### ISSUE TITLE
Network Error In Deepin App Store

### ISSUE THREAD

**Issue by nuvish04** [linuxdeepin/developer-center#1640]
## Describe the bug

The Store displays the "Network Error" message always.
## To Reproduce

The problem starts randomly (after formatting, cleaning the system and/or "suddenly").
## Expected behaviour

Deepin Store working perfectly.
## Screenshots

Error 
![DeepinScreenshot_20200122205101](https://user-images.githubusercontent.com/43933340/72906975-1dd36b80-3d59-11ea-8f16-1601ab17bbb3.png)

### Distro & Version

Deepin 15.11
### Related package version

deepin-appstore v5.3(5.3.1.2)

**Comment by justforlxz** [comment]
It has no problems now.
