### ISSUE TITLE
Deepin file manager window status

### ISSUE THREAD

**Issue by awh6al** [linuxdeepin/developer-center#1641]
## Describe the bug
deepin file manager does not remember the previous window status defined by the user    

## To Reproduce
1. Open new window from deepin file manager  
2. Make that window fit all the screen
3. Open any folder in new window context
4. See that new window does not follow the previous window setting, this behavior produced even if we close the main window and reopen it 

## Expected behavior
I expect to see the new opened window to fit all the screen  

## Screenshots
![DeepinScreenshot_select-area_20200123003716](https://user-images.githubusercontent.com/15833995/72944285-c0e7ad80-3d78-11ea-82ec-48020103199c.png)

## Enviroments:
Linux manjaro 5.4.13-3-MANJARO x86_64 GNU/Linux
Desktop xfce4-panel 4.14.3
Deepin file manager 1.8.2

**Comment by BLumia** [comment]
Hi and the file manager will not going to remember maximum state, it's by design.
