### ISSUE TITLE
deepin file manager inconsistent dark theme 

### ISSUE THREAD

**Issue by awh6al** [linuxdeepin/developer-center#1642]
## Describe the bug
open a new window from deepin file manager with dark theme 

## Screenshots
Before : 
![DeepinScreenshot_select-area_20200123005010](https://user-images.githubusercontent.com/15833995/72944865-8848d380-3d7a-11ea-8e11-a72b7853992a.png)

After : 
![DeepinScreenshot_select-area_20200123005130](https://user-images.githubusercontent.com/15833995/72944874-8ed74b00-3d7a-11ea-8c8b-6dd7426e981a.png)

## Enviroments:
Linux manjaro 5.4.13-3-MANJARO x86_64 GNU/Linux
Desktop xfce4-panel 4.14.3
Deepin file manager 1.8.2

**Comment by Lokke** [comment]
had the same issue but did a few things at the same time to fix other issues as well.
first i downgraded:
warning: gvfs: ignoring package upgrade (1.40.0-1 => 1.42.2-1)
warning: gvfs-afc: ignoring package upgrade (1.40.0-1 => 1.42.2-1)
warning: gvfs-goa: ignoring package upgrade (1.40.0-1 => 1.42.2-1)
warning: gvfs-google: ignoring package upgrade (1.40.0-1 => 1.42.2-1)
warning: gvfs-gphoto2: ignoring package upgrade (1.40.0-1 => 1.42.2-1)
warning: gvfs-mtp: ignoring package upgrade (1.40.0-1 => 1.42.2-1)
warning: gvfs-nfs: ignoring package upgrade (1.40.0-1 => 1.42.2-1)
warning: gvfs-smb: ignoring package upgrade (1.40.0-1 => 1.42.2-1)
that fixed the log loading time for me

then i've removed "qt5-style-plugins"

**Comment by awh6al** [comment]
I believe that is a dependency problem.

**Comment by justforlxz** [comment]
<img width="981" alt="image" src="https://user-images.githubusercontent.com/12298476/147644185-0b68c5ab-fcc7-4f47-8c98-fc33dec0ec5e.png">

it's normal now.
