### ISSUE TITLE
background transparent in fonts in details mode

### ISSUE THREAD

**Issue by alexnfsc175** [linuxdeepin/developer-center#1643]
## Describe the bug
The fonts stay with the colors of the window that was overlaid by the current window

## To Reproduce
leave your desktop with images with strong colors, and with abrupt subdivisions between colors, and then open dde-file-explorer in list view mode

## Screenshots
![bug_file_mananger_01](https://user-images.githubusercontent.com/8923075/73137197-5498d280-4034-11ea-9e9b-e7af9c16d3d1.png)

backgrond

![bug_file_mananger_02](https://user-images.githubusercontent.com/8923075/73137217-932e8d00-4034-11ea-8667-78075794777c.png)

### Distro & Version
ArchLinux Linux 5.4.14-arch1-1 
deepin-account-faces 1.0.11-1
deepin-anything 5.0.1-1
deepin-anything-arch 5.0.1-43
deepin-api 5.0.0-3
deepin-boot-maker 5.0.1-1
deepin-calculator 5.0.1-1
deepin-calendar 5.0.1-1
deepin-clone 5.0.1-1
deepin-clutter 1.26.2-2
deepin-cogl 1.22.5-3
deepin-community-wallpapers 1:1.7.7-1
deepin-control-center 5.0.0-1
deepin-daemon 5.0.0-2
deepin-desktop-base 2:2019.07.10-1
deepin-desktop-schemas 3.13.9-1
deepin-dock 5.0.0-4
deepin-draw 1.0.0-2
deepin-editor 1.2.6.4-1
deepin-file-manager 1:5.0.0-4
deepin-grub2-themes 1.0.0-3
deepin-gtk-theme 17.10.11-1
deepin-icon-theme 15.12.71-1
deepin-image-viewer 5.0.0-1
deepin-launcher 5.0.0-1
deepin-manual 5.0.0-1
deepin-menu 3.4.8-1
deepin-metacity 3.22.24-1
deepin-movie 1:5.0.0-2
deepin-music 5.0.1-2
deepin-mutter 3.20.38-2
deepin-network-utils 5.0.1-1
deepin-picker 5.0.1-1
deepin-polkit-agent 5.0.0-1
deepin-polkit-agent-ext-gnomekeyring 0.1.0-1
deepin-qt-dbus-factory 5.0.1-4
deepin-qt5dxcb-plugin 5.0.1-4
deepin-qt5integration 5.0.0-6
deepin-screen-recorder 5.0.0-1
deepin-screensaver 0.0.10-1
deepin-screenshot 5.0.0-1
deepin-session-ui 5.0.0-1
deepin-shortcut-viewer 5.0.0-1
deepin-sound-theme 15.10.3-1
deepin-system-monitor 5.0.0-1
deepin-terminal 5.0.0-1
deepin-turbo 0.0.3-1
deepin-voice-recorder 5.0.0-1
deepin-wallpapers 1:1.7.7-1
deepin-wm 1.9.38-3

### Related package version
dde-file-manager 1.8.2
![bug_file_mananger_03](https://user-images.githubusercontent.com/8923075/73137391-3338e600-4036-11ea-9db3-5150332ea23d.png)

**Comment by BLumia** [comment]
Duplicate with https://github.com/linuxdeepin/developer-center/issues/1619
