### ISSUE TITLE
商店安装的火狐浏览器中国版总是提示“Firefox无法更新至最新版本”

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1647]
## 缺陷描述

商店安装的火狐浏览器中国版总是提示“Firefox无法更新至最新版本”，这个很恼人，而且书签工具栏上面的火狐官方站点，新手上路等书签删不掉，应该是有问题
我比较喜欢用火狐浏览器，每次我遇到这个问题都要手动下载firefox安装包到/home/widon/soft下面，然后写desktop文件，就没有这个问题了，感觉很麻烦，希望deepin修复这个问题，让用户能够简简单单使用firefox

### 发行版以及版本

deepin15.11

**Comment by Leewen0802** [comment]
可能是深度商店的版本未与火狐官方同步所致。

**Comment by justforlxz** [comment]
系统的firefox是没有权限写入更新文件的，当然无法升级。
