### ISSUE TITLE
光标可以挪到屏幕之外

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1648]
## 缺陷描述

我的笔记本电脑上面，发现光标可以挪到屏幕右边去比较远的地方，屏幕上、下、左都是正常的，不能挪到屏幕上面以上，下面以下，左边更左，但是光标可以挪到屏幕右边以外，有时候我要费力的把光标挪向左边，光标才从右边缓慢的出来，应该是一个bug
[deepin-feedback-cli-Deepin-15.11-all-20200217-121034.tar.gz](https://github.com/linuxdeepin/developer-center/files/4211777/deepin-feedback-cli-Deepin-15.11-all-20200217-121034.tar.gz)

我的电脑屏幕分辨率1080p，屏幕缩放1.25

### 发行版以及版本

deepin15.11

**Comment by Leewen0802** [comment]
应该是系统萤幕判别出了错，就是大小侦测错了。

**Comment by widon1104** [comment]
这个issue可以关掉了，我发现我的笔记本在并没有连接外部显示器的情况下，在设置-》显示-》多屏设置-》模式 设置成了扩展，导致了这一个问题。
