### ISSUE TITLE
更新完 Deepin 後 Dock 消失了、桌面右鍵選單無法使用

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#165]
OS: antergos(arch based)

[user@user-PC ~]$ dde-dock 
qt5ct: using qt5ct plugin
"dtkwidget" can not find qm files
load translate "/usr/share/dde-dock/translations/dde-dock_zh_TW"
2017-02-17, 22:58:41.538 [Debug  ] [main.cpp             main                                50] 

dde-dock startup
程式記憶體區段錯誤 (核心已傾印)

**Comment by felixonmars** [comment]
Please try again with deepin-qt5integration-0.0.7-2

**Comment by JulianLai** [comment]
@felixonmars 更新後已解決，感謝
