### ISSUE TITLE
DFM: build error- DGuiApplication not found

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#1650]
## Describe the bug
As the title says, whenever I try to build DFM(master), I get the error that a file called "DGuiApplication" was not found

## Expected behavior

We should be able to build it without any issue

## Enviroments:
DE: Deepin DE v15.11
### Distro & Version

Manjaro Linux v19.0
### Related package version

DTKGui (Compiled and installed from Github's master branch)
DTKCore v 2.1.1-2
DTKWidget v 2.1.1-5

**Comment by BLumia** [comment]
The current master branch is actually the v20 codebase which requires other depts also using the v20 codebase, since v20 codebase for other DDE components are still not ready for release, you cannot build current DFM master right now.

You can checkout the last tag version and build it for using it. For the master branch, please wait for the DDE v20 codebase release, thanks.

**Comment by SiamSami** [comment]
So, when will DDE v20 codebase get released?

**Comment by BLumia** [comment]
No official ETA at this moment but source release may probably ready in March.

**Comment by SiamSami** [comment]
@BLumia I think you guys probably should release the code as fast as possible. Because then we can take part in fixing various bugs. So, there will be less complain about bugs after Deepin v20 is released.

**Comment by BLumia** [comment]
I do also want to release the source code to community now but it's not what I can make the decision. Sorry about that.

**Comment by SiamSami** [comment]
No problem :)

**Comment by SiamSami** [comment]
Speaking of Deepin V20, why is it taking so long to develop?

**Comment by BLumia** [comment]
Probably because the enterprise support always cost more time thing. Not sure. :-/

**Comment by SiamSami** [comment]
Closing as we don't have this issue anymore.
