### ISSUE TITLE
笔记本屏幕快要暗的时候按空格，卡死了

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1651]
## 缺陷描述

我在屏幕快要暗的时候，按了一下空格，然后悲剧了，按什么都没有反应了，只有重启，照片如下，就那个样子，按啥都没有反应了
![img](https://user-images.githubusercontent.com/12093211/74900034-8013a080-53d9-11ea-8aa5-39a4eedf0a79.jpg)

### 发行版以及版本

deepin15.11

**Comment by sodiven** [comment]
uos也有类似毛病，FN+调暗键，到最暗的时候就，卡一下，黑了，再也调不亮了。只能硬启动

**Comment by justforlxz** [comment]
> uos也有类似毛病，FN+调暗键，到最暗的时候就，卡一下，黑了，再也调不亮了。只能硬启动

公司给的华为的笔记本，调到最低变成纯黑以后，再按两次加就可以调亮了，但是看你们的情况，可能是内核的bug了吧。

**Comment by tsic404** [comment]
15的问题不再处理了，请在20上验证并反馈。
