### ISSUE TITLE
Kernel AHS or 5+

### ISSUE THREAD

**Issue by saymoncoppi** [linuxdeepin/developer-center#1652]
Guys its not a real issue... Its a S.O.S!!!
 
I switched from my Samsung Ultrabook to a brand new dell notebook buuut latest Deepin installer hasnt support. Im a regular deepin user since 2017 and I want to remain a user.

Is there some plans to upgrade the Deepin kernel with “Advanced Hardware Support” or some kernel 5+? AHS is 64 bit and ships with a debian 5.4 kernel, Mesa 19.2 as well as newer xserver drivers.

Any ideia to how boot and instal Deepin 15.11 until any new version with new kernel is released? one month using windows :( due this issue.

This is the notebook (I5, 8gb Ram, 240gb SSD m2):
https://www.dell.com/pt-br/work/shop/notebooks-dell/novo-vostro-14-5000/spd/vostro-14-5490-laptop/cv5490w4105brw1

**Comment by BLumia** [comment]
For the upcoming v20 release, 5.4 LTS is very possible but still not decided yet. Please keep an eye on that :)

**Comment by justforlxz** [comment]
now we use 5.15 version. Maybe it solved your problem?

**Comment by tsic404** [comment]
This issue will close, if you still have problem, you can reopen this issue.
