### ISSUE TITLE
提两个建议：置顶和分屏

### ISSUE THREAD

**Issue by htqx** [linuxdeepin/developer-center#1653]
## 缺陷描述

置顶有什么用？比如打开浏览器，在4k屏幕下两边都大量留白，其实这两侧可以置顶两个应用。比如电影（电影应用一般自带置顶），或者虚拟终端，编辑器等。

置顶是堆叠窗口必须具备的功能，否则窗口只能平铺，某一个窗口不可能占满屏幕，占满屏幕后就无法多任务处理，这对堆叠式窗口是致命的功能缺失。

另外还有一种叫平铺窗口的管理方式。比如i3就很流行，流行的原因在于它可以很方便的平铺窗口，而堆叠式的传统窗口，就要手动移动窗口，调整大小，相当麻烦。deepin 在这方面也有改进，最新的uos比一般系统多了两个分区，就是上下左右，而一般的只有左右。但是相关的快捷键没有设计完备，操作流程不友好。建议设计人员可以参考i3 或者dwm的设计，对平铺进行优化。

我认为平铺只是一种窗口管理方式，主流用户不会为此而使用i3这种桌面（缺乏必要的其他元素，任务栏什么的），但是主流的桌面可以参考这种窗口管理设计，这样有助提升dde的竞争力。

希望dde的设计者可以改进窗口这两种使用模式，让dde变得更加高效实用。谢谢！

## 复现步骤
多窗口管理不舒服

## 期望行为
高效的多窗口

## 复现环境:
dde

### 发行版以及版本
uos

### 相关的软件包版本
dde

### 其他内容
加油深度！加油武汉！

**Comment by meiyixiang** [comment]
谢谢你的建议，产品在持续优化中....
