### ISSUE TITLE
super+shift+l 屏幕变黑

### ISSUE THREAD

**Issue by htqx** [linuxdeepin/developer-center#1654]
## 缺陷描述
这个是什么快捷键，快捷键在哪里修改，在设置面板的键盘快捷键里面没有这个快捷键，看不到它的作用。按住不松开屏幕一直黑，松开屏幕就亮。

我希望deepin能够统一一下快捷键，找不到地方修改，也不知道是干嘛的。

## 复现步骤
super（windows键）+shift+l 立即屏幕变黑，过一段时间屏幕显示没有信号，松开屏幕就恢复。

## 期望行为
我希望deepin能够统一一下快捷键，老找不到地方修改，也不知道是干嘛的。
之前提过的深度终端快捷键，也有很多莫名其妙的，却又不能修改的快捷键，比如alt+1。 关键意见提了，也没有被重视，不知道谁在管理用户体验的。

## 复现环境:
uos更新到最新版2月21号

### 发行版以及版本
uos

### 相关的软件包版本
uos

**Comment by BLumia** [comment]
讲实话 GTK 版本的深度终端自从勇哥走了之后就是我们个别开发顺手修复一些我们能修的 bug ，这个项目并没有对应的维护人员了，我们只能抽出时间修复一部分 bug ，实际上并不算在进行项目层面上的维护了。因为我们大多是 Qt/C++ 开发并且手上都有不少事情要做，所以没太多时间来彻底接盘这个项目。

我们大家其实也都知道这个情况，所以在即将到来的 v20 以及后续的一系列更新过程中，会有一个 DTK 版本的终端出现，所以可以期待一下新版本的终端。另外如果你仍然喜欢目前的 GTK 版本深度终端的话，也可以考虑 fork 并维护自己的版本。

PS. 对于商业版（UOS）的支持是有对应的支持渠道的，建议走对应渠道反馈，会有人来对接跟进，效率会比这里反馈高很多。

**Comment by justforlxz** [comment]
这个问题…我可以关闭了么？
