### ISSUE TITLE
deepin15.11 wine的阿里旺旺若干bug

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1655]
## 缺陷描述

wine的这个阿里旺旺，9.12.03Cdeepin0，上一次更新是18年11月份
1） 这个阿里旺旺退出以后后台还有大量进程，我如果不挨着杀掉这些进程，使用浏览器点击淘宝客服图标无法弹出阿里旺旺，这个比较恼人，杀掉这些进程感觉很麻烦，希望修复这个问题
2）这个阿里旺旺还有一个问题，就是右键面板图标弹出窗口菜单没有字，如果应用没有最小化，还弹不出菜单
3）软件右上角反馈，提示提交失败
这款软件其实问题比较多，属于wine的不是特别好的，比起wine的QQ来感觉差很多，希望deepin再花点精力wine的好一点,提升用户购物体验

### 发行版以及版本

deepin15.11

**Comment by sodiven** [comment]
我也是期待。阿里巴巴能搞出个旺旺linux版本来。那么牛逼的公司，居然linux的旺旺没有。。。。。气死人，看样子阿里巴巴也只是看钱办事的主

**Comment by widon1104** [comment]
不知道使用deepin-wine5 wine的阿里旺旺能不能修复一些上面列出来的问题

**Comment by justforlxz** [comment]
旺旺的问题现在wine组没有时间处理。

**Comment by widon1104** [comment]
希望reopen这个issue，uos&deepin上面阿里旺旺都是有明显问题的

**Comment by justforlxz** [comment]
> 希望reopen这个issue，uos&deepin上面阿里旺旺都是有明显问题的

uos/deepin 上的软件不全部都是我们开发的，我们无法保障所有的程序都可以100%没问题运行呀。

**Comment by widon1104** [comment]
1）可以花时间尝试解决
2）希望wine7.0出来以后，deepin-wine尽快升级到7.0
