### ISSUE TITLE
QQ 启动十分钟后崩溃，请求删除 deepin-wine 中的一行代码

### ISSUE THREAD

**Issue by vincent-163** [linuxdeepin/developer-center#1658]
## 缺陷描述

QQ 启动后运行一切正常，可以登录以及收发消息，但每次启动后约几分钟至十几分钟内崩溃。

## 复现步骤

使用官方安装包或 deepin 提供的安装包安装 QQ 并登录，并等待约十几分钟，QQ 崩溃并弹出错误报告。

## 期望行为
QQ 应该能持续运行。

## 复现环境:

QQ 是通过 https://github.com/wszqkzqk/deepin-wine-ubuntu 安装。

### 发行版以及版本

KUbuntu 18.04

### 其他内容

每次崩溃时所在的 EIP 对应的代码都一样，且终端出现以下内容：
```
ent\QQ\Bin\QQ.exe: netconnection.c:300：create_netconn_socket: 假设 ‘server->addr_len’ 失败。
```
怀疑可能是 QQ 错误地使用了 API 导致的 assertion 出错。希望在 deepin-wine 代码中 netconnection.c 中删除对应的 assertion 提高兼容性。

**Comment by vincent-163** [comment]
刚刚去下载了 wine 的源代码，删除掉这行 assert 并重编译替换 deepin-wine 中的版本后，QQ 顺畅运行，没有崩溃。

希望 deepin-wine 的开发者能把这行删掉或改成 warning。

**Comment by justforlxz** [comment]
正在内部沟通，现在还有这个问题吗？

**Comment by tsic404** [comment]
这个issue将被关闭，如果问题还存在，可以重新打开这个issue。
