### ISSUE TITLE
Archlinux Crash Update 

### ISSUE THREAD

**Issue by vagkaefer** [linuxdeepin/developer-center#166]
Hello people,

I just upgraded Arch Linux through 'Pacman-Su' and Deepin stopped working.

After login the wallpaper appears and nothing else.

> ./startdde

 
![Logs](https://uploaddeimagens.com.br/images/000/839/982/full/DeepinScreenshot20170217202940.png?1487370770)

**Comment by felixonmars** [comment]
Please try again with deepin-qt5integration-0.0.7-2

**Comment by funilrys** [comment]
@fasheng is it normal ? :D  I got it too --"

**Comment by vagkaefer** [comment]
@felixonmars The package (deepin-qt5integration) installation/update solved the problem! <3

Thank you very much. The deepin is wonderful!
