### ISSUE TITLE
阿里旺旺的问题

### ISSUE THREAD

**Issue by sodiven** [linuxdeepin/developer-center#1662]
我们公司找产品必须要实用道旺旺这个聊天工具，deepin对qq，微信的wine还算可以，但是旺旺真的毛病太多。旺旺的1688账号无法登陆，截图不是透明框，退出找不到地方退出，等好多问题

**Comment by justforlxz** [comment]
现在wine组没有多少时间去处理旺旺的问题，很抱歉。
