### ISSUE TITLE
xorg high cpu usage

### ISSUE THREAD

**Issue by tnduc** [linuxdeepin/developer-center#1666]
## 缺陷描述

`xorg high cpu usage`
## 复现步骤

command: `top`

## 截图

![DeepinScreenshot_select-area_20200316212415](https://user-images.githubusercontent.com/26267956/76767839-d1426480-67cc-11ea-8a74-608333a2c292.png)

![DeepinScreenshot_select-area_20200316212348](https://user-images.githubusercontent.com/26267956/76767675-904a5000-67cc-11ea-9985-e6dd25ce7bad.png)

### 发行版以及版本

Linux Deepin 15.11

**Comment by justforlxz** [comment]
Lack of details, xorg's cpu usage is not a simple problem.
