### ISSUE TITLE
控制中心个性化栏子菜单显示问题

### ISSUE THREAD

**Issue by tarzanfan** [linuxdeepin/developer-center#1668]
## 缺陷描述
第一次安装deepin，几乎把控制中心的功能都点击了一遍，没有注销。后续又试了终端等功能，第二次打开控制中心后个性化栏子菜单显示问题
## 复现步骤

这个我还真复现不了，我使用录屏软件保存了mp4。反正是调过分辨率，屏幕缩放，感觉这两个影响

## 截图
![image](https://user-images.githubusercontent.com/43024508/77242054-7af27d00-6c35-11ea-8095-cdf6d341f062.png)

## 复现环境:
win10+deepin

### 发行版以及版本
![image](https://user-images.githubusercontent.com/43024508/77242098-e9373f80-6c35-11ea-9f10-70c8c2c09912.png)

**Comment by tarzanfan** [comment]
重启后该现象消失、无法复现了

**Comment by felixonmars** [comment]
在 Arch + DDE 我有复现过这个问题，不限于这个位置，有时候还会出现在鼠标设备等其他地方。

**Comment by justforlxz** [comment]
这个问题…  内部查了很久，也没有找到问题，现在这个版本的控制中心也不在了…
