### ISSUE TITLE
Terminal blur is displaced with deepin-kwin

### ISSUE THREAD

**Issue by enigmaestro** [linuxdeepin/developer-center#1669]
Bug: with deepin-kwin, the blur on the terminal seems to be displaced. 
![DeepinScreenshot_dde-desktop_20200322083648](https://user-images.githubusercontent.com/62511778/77253559-5045fb80-6c18-11ea-9db5-ddeb3ce8c199.png)

Update: issue is not present when the terminal is fullscreen.

**Comment by BLumia** [comment]
I guess there is something wrong with your graphics card driver or window manager render backend. Maybe you can try install `systemsettings` and try switch between different compositor render backends and see if that can fix your issue.

**Comment by enigmaestro** [comment]
> I guess there is something wrong with your graphics card driver or window manager render backend. Maybe you can try install `systemsettings` and try switch between different compositor render backends and see if that can fix your issue.

Yea I've switched backends, but I haven't installed another driver. Maybe I should run the normal linux kernel with nvidia (I'm running linux-zen with nvidia-dkms). Thanks for the response!

**Comment by luisdecker** [comment]
Got the same issue using deepin-kwin on arch

**Comment by felixonmars** [comment]
@xmuli It's for the old terminal.

**Comment by xmuli** [comment]
Try the new terminal below; it looks like this

![image](https://user-images.githubusercontent.com/33887845/86424240-954bf480-bd14-11ea-85c1-eef6fa171a3a.png)

![image](https://user-images.githubusercontent.com/33887845/86424374-f673c800-bd14-11ea-800c-78979dce7f1f.png)

**Comment by justforlxz** [comment]
Now we only maintain new deepin terminal.
