### ISSUE TITLE
[Archlinux] What to do if we don't want the following ?

### ISSUE THREAD

**Issue by funilrys** [linuxdeepin/developer-center#167]
After update this came up : 
![deepinscreenshot20170218081338](https://cloud.githubusercontent.com/assets/14127285/23091270/63846676-f5b2-11e6-8157-1d12f8284c57.png)

How do disable this ugly thing? (I personally don't like it)

**Comment by JulianLai** [comment]
Since it become this, the response time of the hot corner becomes longer.

**Comment by funilrys** [comment]
so much longer @JulianLai --'

**Comment by funilrys** [comment]
I think we can live with this but @hualet, it'll be great to have the option some days :wink:

**Comment by sonald** [comment]
@funilrys  right click on desktop and select menu item 'zone' or something similar, and just set to none for every corner. or disable hot zone by `qdbus com.deepin.wm /com/deepin/wm  com.deepin.wm.EnableZoneDetected false`.

**Comment by funilrys** [comment]
Thanks for the tips :+1: But it'll be great to have the option to disable the "gray trail" only :wink:
