### ISSUE TITLE
希望deepin默认使用新内核

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1671]
## 缺陷描述

新找的公司是18年成立的公司，买的电脑都是8代cpu、主板，硬盘是M.2固态，不仅deepin15.11装不起，ubuntu最新版也装不起（装的时候识别不到硬盘），确实让人失望
最后没办法，找了一台硬盘是sata接口的主机，把ubuntu装上了，但是还是装不起deepin

### 发行版以及版本

deepin15.11

**Comment by justforlxz** [comment]
the kernel updated to 5.8.
