### ISSUE TITLE
界面是可以的，可能我是菜鸟吧，搞两天搞不定

### ISSUE THREAD

**Issue by Rex-Guo** [linuxdeepin/developer-center#1672]
![image](https://user-images.githubusercontent.com/23191389/77445726-662a0b00-6e28-11ea-95a4-cdcdbac62474.png)
![image](https://user-images.githubusercontent.com/23191389/77445793-7c37cb80-6e28-11ea-84d8-afef0d00ddc1.png)

**Comment by Rex-Guo** [comment]
gitlab 安不上，缺这少那的，建议附带一个 功能补丁包，常见的功能我可以自由选择安装 和centeros一样就好了，，启动部分做的没的说可以说是众多系统里的第一，苹果上都可以安装，其他linux 就不行，
这一点做的的确是好。

**Comment by Rex-Guo** [comment]
奇怪我刚才安装到MacAir上之后 安不了，这会在虚拟机里好像又好了，，我可能太菜了

**Comment by BLumia** [comment]
> 缺这少那的

建议在反馈问题时把实际遇到的情况尽可能详细的反馈，错误报告对于定位错误和解决问题非常有用。您跳过了反馈问题的模板表格却也没有提供详细信息的话，别人很难帮到你。

-----------

目前已有的 Deepin v15.11 仓库基于 debian stretch，所以可以检查您安装的是否为 debian stretch 适用的 GitLab debian 包。
