### ISSUE TITLE
deepin的大佬能不能上极客时间讲一下桌面linux的原理 

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1673]
## 缺陷描述

本人使用linux多年，但是感觉还是抓瞎，很多基本的都不懂，希望能在极客时间开一个或者多个专栏，给大家讲讲linux桌面所有用到的所有的组件的原理，包括内核的原理（可以单独开一个专栏），以及linux桌面现在欠缺的东西都可以讲，给大家扫扫盲可好
极客时间：https://time.geekbang.org/
极客时间是付费专栏，讲专栏的人也会有收益的，感觉不错

**Comment by justforlxz** [comment]
这种资料遍地都是，我们也发布过相关的内容在论坛，实在不行去知乎上看也可以。
