### ISSUE TITLE
Missing Chromium shortcuts icons

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/developer-center#1675]
This [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1066364) seems only to happen in Deepin.

**Comment by justforlxz** [comment]
We've had some reports of what appears to be a problem with the lookup icon.

**Comment by BLumia** [comment]
Should be the same issue as https://github.com/linuxdeepin/developer-center/issues/2457, should be fixed when https://github.com/linuxdeepin/startdde/pull/106 get merged :)
