### ISSUE TITLE
deepin-editor (ArcoLinux)  first save segfaults.

### ISSUE THREAD

**Issue by GrimKalma** [linuxdeepin/developer-center#1676]
## Describe the bug
 Seg faults on first save of file.
 I wrote some text and when i tried to save it, the editor crashes after saving the file.  
 Great thing is that it saves the file, but crashes affer saving.

Seems it crashes also if  you try to save on a already existing empty file.

## To Reproduce
  open deepin-edit
  Press   [CTRL]+[S]  to save and [Enter]
  -> crash

## Expected behavior
  Return to editor.

## Screenshots

qt5ct: using qt5ct plugin
"dtkwidget" can not find qm files
"deepin-editor" can not find qm files
2020-04-09, 16:34:23.907 [Debug  ] [qsettingbackend.cpp  Dtk::Core::QSettingBackend::QSettingBackend 54] create config "/home/mate/.config/deepin/deepin-editor/config.conf"
2020-04-09, 16:34:24.090 [Debug  ] [                                                         0] load finished:  "/home/mate/.local/share/deepin/deepin-editor/blank-files/blank_file_2020-04-09_16-18-56-656" ,  "UTF-8" endOfLine:  0
Segmentation fault (core dumped)

### Distro & Version
DISTRIB_ID=ArcoLinux
DISTRIB_RELEASE=v19.12.17
DISTRIB_CODENAME=ArcoLinux
DISTRIB_DESCRIPTION="ArcoLinux"

### Related package version
deepin-editor 1.2.6.4-1 
dtkwm-2.0.12-6 
dtkwidget-2.1.1-6 
dtkcore-1:2.1.1-2 

### Additional context
  Message: Process 21843 (deepin-editor) of user 1000 dumped core.
                
                Stack trace of thread 21843:
                #0  0x000056421816c2ad n/a (deepin-editor + 0x452ad)
                #1  0x000056421819d279 n/a (deepin-editor + 0x76279)
                #2  0x000056421819e919 n/a (deepin-editor + 0x77919)
                #3  0x000056421819fca9 n/a (deepin-editor + 0x78ca9)
                #4  0x00007f3c237297c6 _ZN7QWidget5eventEP6QEvent (libQt5Widgets.so.5 + 0x19f7c6)
                #5  0x00007f3c23843435 _ZN11QMainWindow5eventEP6QEvent (libQt5Widgets.so.5 + 0x2b9435)
                #6  0x00007f3c236e5352 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x15b352)
                #7  0x00007f3c236eef5f _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x164f5f)
                #8  0x00007f3c23fac34f _ZN3Dtk6Widget12DApplication6notifyEP7QObjectP6QEvent (libdtkwidget.so.2 + 0x11f34f)
                #9  0x00007f3c22c4a4f2 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x2a54f2)
                #10 0x00007f3c23747ace n/a (libQt5Widgets.so.5 + 0x1bdace)
                #11 0x00007f3c236e5352 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x15b352)
                #12 0x00007f3c236ee829 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x164829)
                #13 0x00007f3c23fac34f _ZN3Dtk6Widget12DApplication6notifyEP7QObjectP6QEvent (libdtkwidget.so.2 + 0x11f34f)
                #14 0x00007f3c22c4a4f2 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x2a54f2)
                #15 0x00007f3c2300e64d _ZN22QGuiApplicationPrivate15processKeyEventEPN29QWindowSystemInterfacePrivate8KeyEventE (libQt5Gui.so.5 + 0x13064d)
                #16 0x00007f3c2301399a _ZN22QGuiApplicationPrivate24processWindowSystemEventEPN29QWindowSystemInterfacePrivate17WindowSystemEventE (libQt5Gui.so.5 + 0x13599a)
                #17 0x00007f3c22febc5c _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Gui.so.5 + 0x10dc5c)
                #18 0x00007f3c1d219e2c n/a (libQt5XcbQpa.so.5 + 0x66e2c)
                #19 0x00007f3c21f9b9be g_main_context_dispatch (libglib-2.0.so.0 + 0x6b9be)
                #20 0x00007f3c21f9d831 n/a (libglib-2.0.so.0 + 0x6d831)
                #21 0x00007f3c21f9d871 g_main_context_iteration (libglib-2.0.so.0 + 0x6d871)
                #22 0x00007f3c22ca2890 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2fd890)
                #23 0x00007f3c22c4905c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a405c)
                #24 0x00007f3c22c51066 _ZN16QCoreApplication4execEv (libQt5Core.so.5 + 0x2ac066)
                #25 0x0000564218150c7d main (deepin-editor + 0x29c7d)
                #26 0x00007f3c224bb023 __libc_start_main (libc.so.6 + 0x27023)
                #27 0x00005642181510be n/a (deepin-editor + 0x2a0be)
                
                Stack trace of thread 21845:
                #0  0x00007f3c22588abf __poll (libc.so.6 + 0xf4abf)
                #1  0x00007f3c21f9d7a0 n/a (libglib-2.0.so.0 + 0x6d7a0)
                #2  0x00007f3c21f9d871 g_main_context_iteration (libglib-2.0.so.0 + 0x6d871)
                #3  0x00007f3c21f9d8c2 n/a (libglib-2.0.so.0 + 0x6d8c2)
                #4  0x00007f3c21f74e71 n/a (libglib-2.0.so.0 + 0x44e71)
                #5  0x00007f3c2147546f start_thread (libpthread.so.0 + 0x946f)
                #6  0x00007f3c225933d3 __clone (libc.so.6 + 0xff3d3)
                
                Stack trace of thread 21847:
                #0  0x00007f3c22588abf __poll (libc.so.6 + 0xf4abf)
                #1  0x00007f3c21f9d7a0 n/a (libglib-2.0.so.0 + 0x6d7a0)
                #2  0x00007f3c21f9e843 g_main_loop_run (libglib-2.0.so.0 + 0x6e843)
                #3  0x00007f3c20a03df8 n/a (libgio-2.0.so.0 + 0x59df8)
                #4  0x00007f3c21f74e71 n/a (libglib-2.0.so.0 + 0x44e71)
                #5  0x00007f3c2147546f start_thread (libpthread.so.0 + 0x946f)
                #6  0x00007f3c225933d3 __clone (libc.so.6 + 0xff3d3)
                
                Stack trace of thread 21846:
                #0  0x00007f3c22588abf __poll (libc.so.6 + 0xf4abf)
                #1  0x00007f3c21f9d7a0 n/a (libglib-2.0.so.0 + 0x6d7a0)
                #2  0x00007f3c21f9d871 g_main_context_iteration (libglib-2.0.so.0 + 0x6d871)
                #3  0x00007f3c17e9ce5e n/a (libdconfsettings.so + 0x4e5e)
                #4  0x00007f3c21f74e71 n/a (libglib-2.0.so.0 + 0x44e71)
                #5  0x00007f3c2147546f start_thread (libpthread.so.0 + 0x946f)
                #6  0x00007f3c225933d3 __clone (libc.so.6 + 0xff3d3)
                
                Stack trace of thread 21844:
                #0  0x00007f3c22588abf __poll (libc.so.6 + 0xf4abf)
                #1  0x00007f3c217c263b n/a (libxcb.so.1 + 0xc63b)
                #2  0x00007f3c217c437b xcb_wait_for_event (libxcb.so.1 + 0xe37b)
                #3  0x00007f3c1d218e01 n/a (libQt5XcbQpa.so.5 + 0x65e01)
                #4  0x00007f3c22a6edd6 n/a (libQt5Core.so.5 + 0xc9dd6)
                #5  0x00007f3c2147546f start_thread (libpthread.so.0 + 0x946f)
                #6  0x00007f3c225933d3 __clone (libc.so.6 + 0xff3d3)
                
                Stack trace of thread 21848:
                #0  0x00007f3c22588abf __poll (libc.so.6 + 0xf4abf)
                #1  0x00007f3c21f9d7a0 n/a (libglib-2.0.so.0 + 0x6d7a0)
                #2  0x00007f3c21f9d871 g_main_context_iteration (libglib-2.0.so.0 + 0x6d871)
                #3  0x00007f3c22ca2890 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2fd890)
                #4  0x00007f3c22c4905c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a405c)
                #5  0x00007f3c22a6dc62 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc8c62)
                #6  0x00007f3c23d37b28 n/a (libQt5DBus.so.5 + 0x15b28)
                #7  0x00007f3c22a6edd6 n/a (libQt5Core.so.5 + 0xc9dd6)
                #8  0x00007f3c2147546f start_thread (libpthread.so.0 + 0x946f)
                #9  0x00007f3c225933d3 __clone (libc.so.6 + 0xff3d3)
                
                Stack trace of thread 21851:
                #0  0x00007f3c2147bcf5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfcf5)
                #1  0x00007f3c22a74ac4 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xcfac4)
                #2  0x00007f3c22a74ba2 _ZN14QWaitCondition4waitEP6QMutexm (libQt5Core.so.5 + 0xcfba2)
                #3  0x00007f3c23921836 n/a (libQt5Widgets.so.5 + 0x397836)
                #4  0x00007f3c22a6edd6 n/a (libQt5Core.so.5 + 0xc9dd6)
                #5  0x00007f3c2147546f start_thread (libpthread.so.0 + 0x946f)
                #6  0x00007f3c225933d3 __clone (libc.so.6 + 0xff3d3)
                
                Stack trace of thread 21849:
                #0  0x00007f3c22588abf __poll (libc.so.6 + 0xf4abf)
                #1  0x00007f3c21f9d7a0 n/a (libglib-2.0.so.0 + 0x6d7a0)
                #2  0x00007f3c21f9d871 g_main_context_iteration (libglib-2.0.so.0 + 0x6d871)
                #3  0x00007f3c22ca2890 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2fd890)
                #4  0x00007f3c22c4905c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a405c)
                #5  0x00007f3c22a6dc62 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc8c62)
                #6  0x00007f3c22a6edd6 n/a (libQt5Core.so.5 + 0xc9dd6)
                #7  0x00007f3c2147546f start_thread (libpthread.so.0 + 0x946f)
                #8  0x00007f3c225933d3 __clone (libc.so.6 + 0xff3d3)

**Comment by Zeno-sole** [comment]
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue
