### ISSUE TITLE
Deepin desktop V20 beta source code

### ISSUE THREAD

**Issue by JunioCalu** [linuxdeepin/developer-center#1677]
Hi Guys,
I know that here is not the most suitable place to ask this question, but where can I find the source code for the deepin desktop V20 beta?

**Comment by BLumia** [comment]
We are working on the source release and hopefully the source release (will be on GitHub) will be ready in next month.

**Comment by BLumia** [comment]
Hi and as you can see, we are already in the source release process now. Some repo already sync to GitHub and some other repo are still in the code and license review stage. These will be done before the final v20 iso image release, please keep an eye on it and hope you enjoy :)
