### ISSUE TITLE
Screen doesn't wake up after suspend.

### ISSUE THREAD

**Issue by gokhanyildirimlar** [linuxdeepin/developer-center#1681]
## Describe the bug
The screen doesn't lit unless I touch the mouse after suspend and wake up.

## To Reproduce
1. Close the lid and suspend a laptop.
2. Open the lid and wake up the device.

## Expected behavior
The screen should lit automatically after the device has woken up. 

### Distro & Version
Linux Deepin 20 Beta

**Comment by sayoojsamuel** [comment]
This issue was persistant prior to V20 beta.  Are you using Arch by any chance?

**Comment by gokhanyildirimlar** [comment]
> This issue was persistant prior to V20 beta. Are you using Arch by any chance?

No, I am not using Arch Linux and this issue didn't exist on the previous releases. I am using Deepin for years and this is the first time I encountered this issue but this is beta and this is not an important issue anyway. I got what you wanted to say. Yes, Arch Linux has issues that don't exist on Deepin due to porting and this always has been that way.

**Comment by xmuli** [comment]
Thanks for your feedback, you can try to update your system to this version --> [深度系统更新（2020.06.04）](https://www.deepin.org/2020/06/04/deepin-system-updates%ef%bc%882020-06-04%ef%bc%89/) if the problem still persists

If you can tell us the model number of your notebook, we will be able to reproduce the problem and determine if it is a common problem.

**Comment by gokhanyildirimlar** [comment]
> Thanks for your feedback, you can try to update your system to this version --> [深度系统更新（2020.06.04）](https://www.deepin.org/2020/06/04/deepin-system-updates%ef%bc%882020-06-04%ef%bc%89/) if the problem still persists
> 
> If you can tell us the model number of your notebook, we will be able to reproduce the problem and determine if it is a common problem.

Thanks, the issue still persists with the latest update. My device model is Lenovo Thinkpad T430 and Jingle has the same device, I guess. This issue wasn't present on v15.11 if that helps. So, it must be something that appeared with the complete overhaul of DDE v20. @xmuli

**Comment by xmuli** [comment]
Okay, we'll send it back to the relevant programmer to locate and fix the problem; your suggestions will help us make it even better.

**Comment by gokhanyildirimlar** [comment]
This problem has been fixed with the internal testing source.
