### ISSUE TITLE
minimized app 

### ISSUE THREAD

**Issue by GuilhermeLis** [linuxdeepin/developer-center#1683]
When the app is minimized and I wanna open it I can't just double click on the icon's app I have to use the right click and click in open.

## To Reproduce
I double click in the minimized app and it doesn't open.
I use the right click and click in open to the app really open

## Expected behavior
It should open just with double click

### Distro & Version
Linux Deepin 20 beta

**Comment by gokhanyildirimlar** [comment]
That's weird. It works for me.
![Minimized](https://user-images.githubusercontent.com/45146702/79642755-13820b80-81a8-11ea-8929-fc7de8acebb0.gif)

**Comment by GuilhermeLis** [comment]
Try to use the other tool bar, I was using it

**Comment by gokhanyildirimlar** [comment]
> Try to use the other tool bar, I was using it

It's not about that but even if it's about that, you should have given details.
![Dock mode](https://user-images.githubusercontent.com/45146702/79644983-15060080-81b5-11ea-9aad-9b62b3e7b3f0.gif)

**Comment by babyfengfjx** [comment]
> 
Thanks for your feedback, I don't know if there is any problem that you said in V20.3  version. I have discovered that issues on the latest version may have no longer exist.

**Comment by babyfengfjx** [comment]
I haven't received your feedback for a long time,we close  this  issue now , any new issue  are welcome to feedback~
