### ISSUE TITLE
Can't open a folder with double click

### ISSUE THREAD

**Issue by GuilhermeLis** [linuxdeepin/developer-center#1685]
## Describe the bug
when I'm navigating into the file-manager I can't just open a folder with double click 

## To Reproduce
On the Home's file-manager try to navigation into the file-manger
If you double click on the folder name it opens normal, but if you click on the icon's folder it open to you rename the folder
the folder don't open it just opens the option to rename the folder

## Expected behavior
the double click must open the folder

### Distro & Version
Linux Deepin 20 beta

### Related package version
dde-file-manager 5.1.0.28-1

**Comment by gokhanyildirimlar** [comment]
Double click works just fine for me. Are you sure about you're not clicking too slow?
![Double-click](https://user-images.githubusercontent.com/45146702/79643119-0403c200-81aa-11ea-8d1b-433016d45bef.gif)

**Comment by GuilhermeLis** [comment]
try not to use the list organization

**Comment by gokhanyildirimlar** [comment]
> try not to use the list organization

Also, it's not about icons or list mode. Even if your issue is about it, you should have said that in the bug description. 
![Icons mode](https://user-images.githubusercontent.com/45146702/79645038-7037f300-81b5-11ea-8c00-ed72368be78b.gif)

**Comment by xmuli** [comment]
Previous Reply to Man's .gif demo looks cool🥳;.
Or do you try to modify it here?

![image](https://user-images.githubusercontent.com/33887845/82422330-e41b3300-9ab4-11ea-9683-adb5784861c9.png)

**Comment by babyfengfjx** [comment]
Thanks for reporting this issue，I wonder if this phenomenon still exists in the latest version？

We can't reproduce this problem

**Comment by babyfengfjx** [comment]
Because this issue  is for too long, we have not received your reply,we close  this  issue now , any questions are welcome to feedback~
