### ISSUE TITLE
[V20 BETA] Remove the 64GB requirement for installation

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#1691]
## Describe the bug

The installer does not allow the user to proceed with the installation when the HD / SSD is less than 64GB. Some touch devices are sold with 32GB (soldered memory) and system installation is not possible.

In advanced mode, the /root partition requires 15GB (as long as the HD / SSD is 64GB). There is no point in employing this 64GB limitation.

### Distro & Version
Deepin 20 BETA

**Comment by yarecco** [comment]
32GB? The cheap mobile from China has more nowadays

**Comment by alexwender1** [comment]
> 32GB? The cheap mobile from China has more nowadays

deepin is not compatible with ARM

**Comment by gabrielbrise** [comment]
Just installed with no problems in a VM with 18gb by using the advanced mode where you create the partitions

**Comment by xmuli** [comment]
When deepin was installed, the 64G size bug has been fixed. The next version should be reflected @justforlxz

**Comment by alexwender1** [comment]
> Just installed with no problems in a VM with 18gb by using the advanced mode where you create the partitions

Yes, it is possible to install deepin on a partition of at least 15 GB. But, the installer requires the total size of the HD/SSD to be 64 GB.

In the virtual machine, you can create dynamic disks and bypass this limitation (as confirmed by @xmuli, this actually was a bug).

**Comment by alexwender1** [comment]
The problem was solved in deepin 20 (1001).

**Comment by dhunter** [comment]
Just tried installing Deepin, (1002) in a virtual machine, (VMWare, 20 gb fixed drive space, which is the default space suggested, and which I always use when first installing a new distro) and am afraid it still said that I needed a min of 64 gb disk space, (128 preferred).

**Comment by xmuli** [comment]
@dhunter As far as I know, after adjustment, they adjusted to "manual setting" minimum 20G; default full disk installation, minimum 64G

**Comment by itzTheMeow** [comment]
is there a fix for this? i have a 64gb SD card but the useable size is 59gb so i cant install :(

**Comment by alexwender1** [comment]
> is there a fix for this? i have a 64gb SD card but the useable size is 59gb so i cant install :(
> i tried 1002

At installation, choose Advanced Mode. Full Disk Mode requires this size.

**Comment by bh013** [comment]
@xmuli i have Deepin20.1 installed on my machine, OS used space is ~**6.5GB** 
may its new version include ~13GB movies for our entertainment 
 
Then i can not install it on my device with 16GB SSD, then we never upgrade it

**Comment by mikebeaton** [comment]
A way to override this setting (e.g. flag when starting installer?) would be very useful.

**Comment by justforlxz** [comment]
> > A way to override this setting (e.g. flag when starting installer?) would be very useful.
> 
> We use the 64g full disk partitioning strategy because we must reserve the necessary space. When you use manual partitioning, there will be no such limitation.

If the restriction is removed, the installation process will fail (because it is assumed that the partition capacity is sufficient

**Comment by bh013** [comment]
This is Deepin 20.2.2

![deepin_installation_211012_145240](https://user-images.githubusercontent.com/29511505/136947331-9711a412-4e8a-4a13-8a25-1a8f674f5b37.png)

@justforlxz is this error has changes in new version ?

**Comment by mikebeaton** [comment]
> > > A way to override this setting (e.g. flag when starting installer?) would be very useful.
> > 
> > 
> > We use the 64g full disk partitioning strategy because we must reserve the necessary space. When you use manual partitioning, there will be no such limitation.
> 
> If the restriction is removed, the installation process will fail (because it is assumed that the partition capacity is sufficient

I understand that if there is too little space, the installation will fail.

I believe the 64GB limit is however a very large safety margin over what is needed to get started with an working install.

I also am quite prepared to accept that 64GB may be a reasonable minimum to at least strongly recommend, if not enforce, for a normal end-user - but I don't think that's the main issue here.

I believe it is more about whether it is even _possible_ to install Deepin with automatic layout onto a drive which is _in fact_ large enough to get a working Deepin install (e.g. maybe just to test something), but where the current Deepin automatic installer would refuse to allow it.

I hope that makes sense!
