### ISSUE TITLE
Dash symbol isn't available to use in a user password.

### ISSUE THREAD

**Issue by gokhanyildirimlar** [linuxdeepin/developer-center#1692]
## Describe the bug(or decision?)
Dash(-) symbol can not be used in a user password. 

## Expected behavior
Dash and other symbols should be available to use in a password to increase its security level.

### Distro & Version
Linux Deepin 20 Beta

**Comment by xmuli** [comment]
Sorry, I didn’t see this issue, (I was also very curious, thought it was due to some kind of strategy), but just now, I asked specifically if there is no special reason, and then the'-' setting was disabled As a password variable. This problem will be fixed later

**Comment by gokhanyildirimlar** [comment]
No response and action since the beginning. I am closing this issue since I am switching to another distro and I can't track this anymore.

**Comment by gokhanyildirimlar** [comment]
I guess this has been fixed but I can not check. I just wanted to comment on this.
