### ISSUE TITLE
[Feature Request] Make possible to have blue filter always on

### ISSUE THREAD

**Issue by devtud** [linuxdeepin/developer-center#1694]
It would be nice to be able to always have blue filter active, not only at night. Currently, in Control Center > Display > Brightness > Night Shift, it is stated: "**The screen hue will be auto adjusted according to your location**".

Suggestion: Let the user control if the blue filter should be **always on** (aka not location dependent) or **only at night**.

**Comment by meiyixiang** [comment]
You can upgrade to our latest version 20.4 which already supports self-adjusting color temperature in the display
