### ISSUE TITLE
Crash On Play The Video

### ISSUE THREAD

**Issue by marcellino03** [linuxdeepin/developer-center#1695]
My deepin is crash when am play the video use default mp4 player.

**Comment by xmuli** [comment]
Without a detailed description, it can be difficult to reproduce, leading to omissions or delays

**Comment by justforlxz** [comment]
Can you add detailed information, such as software, test videos, etc.

**Comment by Zeno-sole** [comment]
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue
