### ISSUE TITLE
 Graphics error

### ISSUE THREAD

**Issue by azaderdogan** [linuxdeepin/developer-center#1696]
## Describe the bug

When I was at Deepin15, I wasn't getting such graphic errors. In the beta version of Deepin20, I get these errors when opening a window on the terminal. So I get errors in the Android Studio emulator. I think it's graphical.
## To Reproduce

I think the error was due to missing libraries when moving from Deepin15 to Deepin20.
cd /usr/share/android-studio/bin
./studio.sh
See ERROR
errors are in the pictures about the terminal.

## Screenshots

![Screen Capture_20200417025645](https://user-images.githubusercontent.com/61507227/79910578-a381b880-8427-11ea-91bd-1d103201b354.png)
![Screen Capture_20200421232432](https://user-images.githubusercontent.com/61507227/79910606-aed4e400-8427-11ea-911b-a3662b11a2ab.png)
![Screen Capture_20200421232436](https://user-images.githubusercontent.com/61507227/79910612-b09ea780-8427-11ea-9b63-fb814d6a7b16.png)
![Screen Capture_20200421232440](https://user-images.githubusercontent.com/61507227/79910616-b1cfd480-8427-11ea-9cc8-b9376f970623.png)
![Screen Capture_20200421232449](https://user-images.githubusercontent.com/61507227/79910623-b4322e80-8427-11ea-9ca6-9e9841aadf1b.png)
![Screen Capture_20200421232445](https://user-images.githubusercontent.com/61507227/79910626-b4cac500-8427-11ea-9adc-cc776400f7fc.png)
![Screen Capture_20200417025645](https://user-images.githubusercontent.com/61507227/79910639-b85e4c00-8427-11ea-9959-d043b7a83433.png)
![Screen Capture_select-area_20200418124121](https://user-images.githubusercontent.com/61507227/79910645-bac0a600-8427-11ea-82fd-1824fcdb38e6.png)
![Screen Capture_20200418120825](https://user-images.githubusercontent.com/61507227/79910662-c01df080-8427-11ea-8156-6de17c66f157.png)

## Enviroments:
Graphic driver 
### Distro & Version

Deepin 20 beta
### Related package version

nvidia version is default

**Comment by Zeno-sole** [comment]
20.3 can open android-studio normally

**Comment by Zeno-sole** [comment]
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue
