### ISSUE TITLE
Battery Indicator Error

### ISSUE THREAD

**Issue by furkanydn** [linuxdeepin/developer-center#1698]
## Describe the bug
Although there is no battery in the laptop, it seems to be charging something.

## Expected behavior
When there is no battery, a broken icon is shown on the battery indicator on the laptop.

## Screenshots
![Screen Capture_20200423171445](https://user-images.githubusercontent.com/47810525/80110033-ea39f480-8586-11ea-9515-e795265a5e4d.png)

### Distro & Version
Linux Deepin 20 Beta

**Comment by Zeno-sole** [comment]
This should not be a problem on 20.3

**Comment by furkanydn** [comment]
This issue resolved.
