### ISSUE TITLE
[20 BETA] eBook in the Document Viewer

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#1701]
## Expected behavior
Allow the Document Viewer to view eBook formats; e.g. .epub and .odf

### Distro & Version
deepin 20 BETA

### Related package version
deepin-reader 5.6.2

**Comment by meiyixiang** [comment]
The latest version is now 20.4. Please update

**Comment by lxwndr** [comment]
The latest version of the system and application does not allow opening (reading) .epub files.

![Capturar_deepin-terminal_20220305142501](https://user-images.githubusercontent.com/45263160/156894146-9b51ca0c-e09f-4ef1-8565-0e8690abc568.png)

![Capturar_select-area_20220305143632](https://user-images.githubusercontent.com/45263160/156894150-2a7fa53c-192c-4f77-a12e-aa2f1899fca3.png)
