### ISSUE TITLE
[20 BETA] Offer 2 stable kernel versions.

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#1702]
## Describe the bug
Many users are experiencing anomalies with the 5.3 kernel; but compatibility is better with newer devices.

Users who have reverted to the 4.19 kernel (from the repository) are experiencing faster and more stable performance.

### Distro & Version
deepin 20 BETA

### Additional context
Offer the last 2 kernel LTS launched (4.19 and 5.4); and with a click on the Control Center, it is possible to change the kernel in use (or facilitate this change at startup).

**Comment by alexwender1** [comment]
The request was granted in version 20 (1001).

**Comment by xmuli** [comment]
The current community version is now dual kernel, 5.4 and 5.7
