### ISSUE TITLE
[20 BETA] Compact date information

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#1703]
## Describe the bug
Allow the date on the dock to be displayed in the format:

2020/04/28 -> **28 APR**

## Screenshots
![Screen Capture_select-area_20200428005643](https://user-images.githubusercontent.com/45263160/80445763-729ff880-88eb-11ea-9122-a7ad74721352.png)

### Distro & Version
deepin 20 BETA

### Related package version
dde-dock 5.0.27

### Additional context
I sent this suggestion directly to Shule; but I don't know if he ignored

**Comment by alexwender1** [comment]
The chosen date format is not displayed on the dock. The default for Brazil is DD / MM / YY.

![image](https://user-images.githubusercontent.com/45263160/103373573-0f86e700-4ab4-11eb-8439-c35169781971.png)

The suggestion I propose above, makes the date more visible in the dock; that it is already quite compacted below the hour.

**Comment by lxwndr** [comment]
I will centralize the demand on another topic.
