### ISSUE TITLE
Flicker Free Boot

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#1710]
## Describe the bug
Adopt a smooth boot for the deepin.

Note: In this case, adopt the horizontal logo

### Additional context
https://bbs.deepin.org/forum.php?mod=viewthread&tid=176236
https://fedoraproject.org/wiki/Changes/FlickerFreeBoot
https://fedorapeople.org/~jwrdegoede/flickerfree-videos/workstation-bgrt-logo.webm
https://fedorapeople.org/~jwrdegoede/flickerfree-videos/laptop-diskcrypt-bgrt-logo.webm
https://www.omgubuntu.co.uk/2019/07/ubuntu-flicker-free-boot

**Comment by Dziban-dev** [comment]
that would be nice. boot times are a bit shorter too.

**Comment by Zeno-sole** [comment]
Will it work on non-i915 devices?

**Comment by lxwndr** [comment]
> 

Currently, Ubuntu and Fedora already have this functionality implemented; it is important for the development team to verify these software.

**Comment by Zeno-sole** [comment]
I need to verify that it works fine on deepinv20, Thank you for your suggestion, if it works properly, we will update the function in the next version

**Comment by Zeno-sole** [comment]
We will support it in the next version, please pay attention to our release log

**Comment by lxwndr** [comment]
We can reopen this issue?

**Comment by meiyixiang** [comment]
First of all, I am very sorry for replying to your question so late. There is something missing when dealing with this feedback. We have communicated with the designer about the problem of the launcher animation style you gave us, and simulated the design adopted by other releases, but it is not suitable for our own design style to adopt such a way. Therefore, we have not changed this problem, from the perspective of UI vision, we think the current way is more suitable for us.
