### ISSUE TITLE
Laptop immediately shuts down after plugging earphone

### ISSUE THREAD

**Issue by GustavoAle** [linuxdeepin/developer-center#1711]
## Describe the bug
Every time I plug the earphone on the audio jack the laptop immediately shuts down, but sometimes the shutdown can occur almost 5 seconds after plugging the earphone. This first happened some days ago but I didn't notice the cause, today I noticed that this happens every time I plug the earphone.
Ps.: My earphone is fine and I tested with some other earphones with the same result.

## To Reproduce
1. Use your laptop on battery (I'm not sure if it happens on AC power too)
2. Plug any earphone or headset on the audio jack
3. See your laptop suddenly off 

## Enviroments:
Acer E5-574

### Distro & Version
Linux Deepin 15.11

**Comment by cacarr-pdxweb** [comment]
Does that only happen running Deepin? It sounds like a hardware issue.

**Comment by GustavoAle** [comment]
Unfortunately this only happen with Deepin when the laptop is using the battery.

**Comment by Zeno-sole** [comment]
Can you provide kernel logs?

**Comment by GustavoAle** [comment]
I no longer have this laptop, so I can't provide the kernel logs. Sorry.

**Comment by Zeno-sole** [comment]
Sorry this issue cannot be dealt with at the moment, we will close

**Comment by Zeno-sole** [comment]
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue
