### ISSUE TITLE
Security concerns /media/logonid/acess_to_private_partitions

### ISSUE THREAD

**Issue by lsatenstein** [linuxdeepin/developer-center#1713]
V20 dated 5 May 2020
## Describe the bug
In a multi-boot environment, only the partitions shown in the /etc/fstab should be mounted.
/media/logonid has read/write access to every partition and directory therein. 
There should be no automatic mount of any partitions to /media

## Enviroments:

Deepin Beta dated 3 May 2020

**Comment by justforlxz** [comment]
maybe automount by gvfs or other client's implementation.

You can check if automount is turned on in the settings of your file manager.
