### ISSUE TITLE
[bug report] - Small Graphical Glitch - deepinV20

### ISSUE THREAD

**Issue by Dziban-dev** [linuxdeepin/developer-center#1717]
## Describe the bug
Small graphical glitch small dark squares on every corner of windows and widgets with blur, like right-click contextual menu, notification center and the dock etc

## To Reproduce
-Unlocking a locked session from the Locked Screen or visiting the Power Options Screen.
-Changing the system theme from dark to light or from light to dark.

## Expected behavior
no squares on corners.

## Screenshots

![image](https://user-images.githubusercontent.com/36001673/81244001-7b20bf00-8fce-11ea-8d47-cf1e4bdd045c.png)

## Enviroments:

CPU: AMD A8 7800
GPU: AMD A8 R7
RAM:12GB

### Distro & Version
DeepinV20 beta

### Additional context
I tested this issue with both **radeon** and **amdgpu** graphic drivers. and in both cases the issue persists. As a way to get everything back to normal I have to turn window efects off and on from the control center, but whenever i lock the screen or visit the Power Options Screen issue comes back,

**Comment by Zeno-sole** [comment]
All should be fixed in the new version
