### ISSUE TITLE
Megasync seg fault

### ISSUE THREAD

**Issue by danmrc** [linuxdeepin/developer-center#1719]
## Describe the bug

Whenever one opens megasync (either megasync megasync-nopdfium from aur), it gives a segfault or a bus error. 

## To Reproduce

1. install megasync (yay -S megasync)
2. open it via terminal
3. segmentation fault (or bus fault)

## Expected behavior

The program would open

### Distro & Version

Archlinux kernel 5.6.11
Deepin 20
Intel i5 3210M
6 GB

### Additional context

It worked fine until the latest update and megasync works fine under xcfe, so I guess its some problem with deepin?

**Comment by danmrc** [comment]
Latest update to deepin fixed it

**Comment by nuwonda** [comment]
issue persists. will open a new issue ...
