### ISSUE TITLE
Wallpaper/Screensaver Deepin V20

### ISSUE THREAD

**Issue by BRENDAAR** [linuxdeepin/developer-center#1722]
## Describe the bug
Selecting Wallpaper/Screensaver menu from dropdown menu on desktop causes menu bar to stop, as well as the background/screensaver to stop.

## Expected behavior
wallpaper and screensaver menu appear on bottom of screen

### Distro & Version
Arch Linux Deepin V20 

### Related package version
deepin-desktop 2:2020.04.12.2-1

### Additional context
This happened after the V20 update pushed yesterday.  I reinstalled with a new installer, thinking that it may have been the update, but the problem persists with clean install.

**Comment by BRENDAAR** [comment]
I solved the issue by removing deepin-anything-arch and installing deepin-anything-dkms, deepin-kwin,and reinstalled deepin-dock.  I have a feeling that deepin-anything-arch is the problem with most of these bugs.

**Comment by felixonmars** [comment]
That sounds strange to me as deepin-anything-arch is always kept up-to-date with the official kernel.

**Comment by BLumia** [comment]
More likely caused by deepin-kwin :/
