### ISSUE TITLE
Upgrading more continuously

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/developer-center#1724]
I think that the ideas of the new upgrades of Deepin are quite good, but even then the bugs and inconsistencies are quite noticeable. Making my system hang in a variety of ways is quite easy to me, with plenty of visual sizing inconsistencies among applications.

I would like to make a simple suggestion which worked for me wonders when developing software: freely and recklessly change anything you want, but do in the smallest most continuous upgrades. Instead of upgrading all the product all together, upgrade specific things and fix any arising problem before developing more. Manually thoroughly test any change before uploading.

The idea is having a stable base with some beta in it. Upgrade small and upgrade often, make it easy to change any arising issue. It's not about being careful or having advanced quality processes, it's about **one at a time**.

**Comment by felixonmars** [comment]
I can't agree more :)

**Comment by es20490446e** [comment]
Sorry, but this isn't the bare minimum to get a functional desktop.

The desktop keeps hanging in a variety of ways, the visual inconsistencies are all over the place, many core features like file indexing don't work, and the computer now hangs on reboot.

In a couple of weeks I would have a look at the state of Deepin, and reevaluate it as a desktop of choice.

**Comment by Zeno-sole** [comment]
Your suggestion is very useful, because the desktop components were too coupled before and we were updating many applications together every time, we are working hard to decouple

**Comment by Zeno-sole** [comment]
We will plan a new upgrade in v23
