### ISSUE TITLE
On Arch-based distributions, Deepin system apps don't respect their own colorscheme. 

### ISSUE THREAD

**Issue by gardotd426** [linuxdeepin/developer-center#1727]
## Describe the bug
When you select "Dark" for the theme in the Control Center, all Deepin apps (Control Center, Boot Maker, Music, Movie, etc.) refuse to actually use a dark color scheme. I have seen first-hand that this is DOES work in the actual Deepin V20 Beta, but outside of Deepin, on Arch and Manjaro, it doesn't work. Everything in Deepin is stuck on a light colorscheme, no matter what you do. The system theme IS reported as "dark/deepin," but it doesn't work, except for non-Deepin apps. I suspect this has a common cause to the icons not working in the control center, which I have also seen DO work in the Beta, but not in Arch/Manjaro.

## To Reproduce
1. Be running the latest Deepin DE packages on an Arch-based Linux system.
2. Open Control Center
3. Select "Personalization," then "Dark" under the "Theme" section.
4. See error. Reboot or log out if you like, the error will persist. Other, non-Deepin apps will appear with the dark topbar, but all Deepin applications remain bleach-white. 

## Expected behavior
For the theming to actually work in any way whatsoever. Like this:

![workingdeepin](https://user-images.githubusercontent.com/54234607/81650787-35b22680-9400-11ea-99ed-f2cefbe31f89.png)

## Screenshots
But instead, you get this:
![noicons1](https://user-images.githubusercontent.com/54234607/81650912-50849b00-9400-11ea-9823-e6078485f9fa.png)

Hell, you can even see in this photo that the "Dark" theme is supposedly active in the Control Center though it's very obviously not: 

![deepinbug1](https://user-images.githubusercontent.com/54234607/81650956-58dcd600-9400-11ea-9bb8-93c9ce6e6589.png)

### Distro & Version
Arch Linux, Manjaro Linux 20.0.1 Lysia

### Related package version
```
pacman -Q | egrep -i "deepin|dde"


deepin-account-faces 1.0.11-1.1
deepin-anything 5.0.1-2
deepin-anything-dkms 5.0.1-2
deepin-api 5.1.11.1-1
deepin-boot-maker 5.4.8-1
deepin-calculator 5.5.9-1
deepin-calendar 5.6.2-1
deepin-clone 5.0.3-1
deepin-clutter 1.26.2-2
deepin-cogl 1.22.5-3
deepin-control-center 5.1.0.5-1
deepin-daemon 5.9.4.2-1
deepin-desktop-base 3:2019.07.10-1
deepin-desktop-schemas-manjaro 5.4.0099.0-1
deepin-dock 5.1.0.8-1
deepin-draw 5.8.0.15-2
deepin-editor 5.6.7-2
deepin-file-manager 1:5.1.1.25-1
deepin-gtk-theme 17.10.11-1
deepin-icon-theme 2020.05.09-1
deepin-iconthemes-manjaro 20170918-1
deepin-image-viewer 5.6.3.2-1
deepin-launcher 5.1.0099.0-1
deepin-menu 5.0.1-1
deepin-metacity 3.22.24-1
deepin-movie 1:5.7.6.29-1
deepin-music 6.0.1.8-1
deepin-mutter 3.20.38-4
deepin-network-utils 5.1.0.0-1
deepin-picker 5.0.6-1
deepin-polkit-agent 5.1.0-1
deepin-polkit-agent-ext-gnomekeyring 0.1.0-1
deepin-qt-dbus-factory 5.1.0.0-1
deepin-qt5dxcb-plugin 5.0.11-1
deepin-qt5integration 5.1.0-1
deepin-screen-recorder 5.8.0.11-1
deepin-screensaver 0.0.10-1
deepin-screensaver-pp 0.0.4-1
deepin-session-shell 5.0.0098.0-2
deepin-session-ui 5.1.0099.4-1
deepin-shortcut-viewer 5.0.2-1
deepin-sound-theme 15.10.4-1
deepin-system-monitor 5.6.1-1
deepin-terminal 5.0.4.1-1
deepin-turbo 0.0.3-1
deepin-voice-recorder 5.0.0-1
deepin-wallpapers 2:1.7.7-1
deepin-wm 1.9.38-4
manjaro-deepin-settings 20191111-1
plymouth-theme-manjaro-deepin-circle 1.0-4
startdde 5.3.0.1-2
```

### Additional context
Again, it very obviously works on the Deepin Beta (at least for some people), but it very clearly is not working here. No idea why, I've looked everywhere. I tried deepin-mutter even though it's deprecated after Deepin-Kwin wouldn't work no matter what. I removed all QT environment variables, installed qt5ct, uninstalled qt5ct, nothing works.

**Comment by es20490446e** [comment]
Everything is completely broken:

https://forum.manjaro.org/uploads/default/optimized/3X/1/f/1f0392b0ee81eee24e43bcab4a3255b248245453_2_1035x582.png

**Comment by Y0ngg4n** [comment]
Same behavior here on Manjaro, missing Icons everywhere and the Dark Mode does not apply if you select it.
Also the Transparency Slider is non existent.
Missing Icons everywhere aswell as in the login screen.
If you tell me, where i can find some usefull logs i can paste them here.

**Comment by polluxmaster** [comment]
Same here, everything is broken after last update

![image](https://user-images.githubusercontent.com/65246178/81724464-cd446300-945a-11ea-9f02-b62a05dd450a.png)

**Comment by felixonmars** [comment]
I cannot reproduce any of these on my Arch system though. Can you try to replace deepin-desktop-schemas-manjaro with Arch's deepin-desktop-schemas and see if anything changes?

**Comment by es20490446e** [comment]
When I have a moment I will test.

Discussion on Manjaro [here](https://forum.manjaro.org/t/manjaro-deepin-edition-on-hold/106251/195).

**Comment by es20490446e** [comment]
Dalto confirms there it's the same on Arch.

**Comment by Y0ngg4n** [comment]
After uninstallation of deepin-desktop-schemas-manjaro i had some problems with plymout-theme-manjaro-deepin and my system won´t boot. After some tries to fix it i just restored a backup with Deepin 15 so i can get my work done until they fix this issues.

**Comment by felixonmars** [comment]
@es20490446e Figured it out. Please try deepin-qt5integration 5.1.0.1-2.

For more info: https://github.com/linuxdeepin/qt5integration/pull/26

**Comment by dalto8** [comment]
deepin-qt5integration 5.1.0.1-2 fixes it for me.

Thanks!

**Comment by Hsins** [comment]
The icons are shown after I update to deepin-qt5integration 5.1.01-2 on my Manjaro system. But there are problems with the sidebar (control center) and login screen.

**Comment by felixonmars** [comment]
The login screen works correctly here. Do you have same issues with the lock screen etc?

**Comment by nalakawula** [comment]
+1 instaal deepin in arch based distro, today. And this issue happen to me

**Comment by Y0ngg4n** [comment]
I can verify that it works on Manjaro with deepin-qt5integration 5.1.0.1-2. The icons are there and the Theme do also apply, but the Search bar in Settings does not work and the Transparency Bar in Appeareance is missing.

**Comment by gardotd426** [comment]
@Y0ngg4n if you're using the default deepin installation on Manjaro, then you have to instead install `deepin-kwin`, as `sudo pacman -S deepin deepin-extra` on Manjaro will install `deepin-mutter` as the window manager instead, which is deprecated. With `deepin-mutter` as the WM, you won't get the transparency slider or window effect button, because `deepin-mutter` was deprecated months ago, and Deepin v20 is a complete overhaul of the DE so obviously it won't work with the deprecated window manager.

Install `deepin-kwin` and remove `deepin-mutter`. Actually, you shouldn't need to remove `deepin-mutter` because it will default to `deepin-kwin`, but I would uninstall it just in case.

**Comment by dalto8** [comment]
@felixonmars should the default packaging on Arch be changed to use deepin-kwin instead of deepin-mutter?

**Comment by gardotd426** [comment]
@dalto8 I would say that's a pretty objectively clear yes, look for yourself:
https://github.com/linuxdeepin/deepin-mutter
The title of the page is literally "deepin-mutter DEPRECATED," the repo is archived read-only (which by definition should make it removed from the deepin group on Arch as bugs can't even be fixed anymore), and the last commit was 5 years ago. 

Meanwhile deepin-kwin is the actual window manager for the Deepin desktop environment.

**Comment by felixonmars** [comment]
Okay. I think it's enough reason to make it the default for now regardless of the bug. I added deepin-kwin to deepin group in 5.0.14.1-3, which will effectively make it the default in new installations while users are still able to uninstall it if they prefer deepin-wm somehow. Old installations won't be affected.

**Comment by gardotd426** [comment]
@felixonmars absolutely, I mean sure there are some bugs left in the new Deepin DE but that's to be expected, but at least with `deepin-kwin` those bugs can be addressed, they'll never be fixed in `deepin-mutter`. Which is unfortunate, because I preferred deepin-mutter on the old pre-v20 deepin de, but still.

**Comment by dalto8** [comment]
Thanks @felixonmars, can we also remove dependencies on deepin-mutter?

**Comment by felixonmars** [comment]
Will do shortly.

**Comment by gardotd426** [comment]
Are the window titlebars supposed to stay white even when the theme is set to dark? Because that's the behavior I'm getting.

**Comment by dalto8** [comment]
@gardotd426 which applications?  It is working fine here for me with the apps I have tested.

**Comment by gardotd426** [comment]
@dalto8 Every non-deepin application. Alacritty, chrome, firefox, radeon-profile, kitty, a million of them. Someone else has already filed a bug for it so obviously it's an issue for other people too.

Ignore the hideous black borders, that's yet *another* bug (like the 6th I've encountered so far), but I've filed a separate issue for that. Note how every window essentially has a white titlebar. 

![deepintitlebarbug1](https://user-images.githubusercontent.com/54234607/82765426-f367ec80-9de4-11ea-8987-ebd61e565e90.png)

**Comment by Y0ngg4n** [comment]
@gardotd426 Same behavior here on Manjaro.

**Comment by Y0ngg4n** [comment]
@gardotd426 @dalto8 Here an example image of the behavior:
![Screen Capture_deepin-terminal_20200527171011](https://user-images.githubusercontent.com/30302975/83038941-d37f3580-a03d-11ea-8f37-fbf2fe25aaa1.png)

**Comment by gardotd426** [comment]
@Y0ngg4n try opening the Control Center, clicking on "Light" for the theme, and then clicking on "Dark" again. That's what I had to do.

**Comment by Y0ngg4n** [comment]
@gardotd426 Thanks for this workaround!

**Comment by SiamSami** [comment]
One thing that needs to be mentioned is that manjaro by default makes use of qt5ct. You should **remove** the following line
`export QT_QPA_PLATFORMTHEME="qt5ct"`
from `~/.xprofile`.

**Comment by gardotd426** [comment]
I don't have that in my `~/.xprofile`, and Manjaro actually doesn't do that by default anyway (it doesn't even install qt5ct unless you tell it to, or you can just remove qt5ct, nothing in Deepin DE requires it). 

But either way, it seems it's been fixed, I'm gonna go ahead and close it. Plenty more bugs to track down, but this one's fixed.

**Comment by YuriFontella** [comment]
This old problem still persists in the current Deepin packages on Arch Linux.

In the control center, even when switching between dark and light, the applications do not receive the theme. It is necessary to manually change the theme option in each application.

In Deepin 23, the dock also has its theme changed. In Deepin with Arch Linux, the dock refuses to receive the dark theme in any way.

There are still problems with animations and shortcut keys that do not work.

deepin-account-faces 1.0.16-1
deepin-album 6.0.4-7
deepin-anything 5.0.18-1
deepin-anything-arch 6.1.2-99
deepin-api 6.0.11-1
deepin-app-services 1.0.25-1
deepin-appearance 1.1.29-1
deepin-application-manager 1.2.2-1
deepin-calculator 5.8.24-7
deepin-calendar 5.12.3-2
deepin-camera 1.4.16.20230919-2
deepin-clipboard 6.0.8-2
deepin-clone 5.0.15-2
deepin-community-wallpapers 1:1.7.7-3
deepin-compressor 5.12.24-1
deepin-control-center 6.0.47-1
deepin-daemon 6.0.40-1
deepin-desktop-base 2:2024.01.03-1
deepin-desktop-schemas 6.0.5-3
deepin-desktop-theme 1.0.9-1
deepin-dock 6.0.37-2
deepin-draw 6.0.10-5
deepin-editor 6.0.17-3
deepin-file-manager 1:6.0.42-5
deepin-grand-search 5.4.5-5
deepin-gtk-theme 2020.06.10-2
deepin-icon-theme 2024.06.21-2
deepin-image-editor 1.0.44-1
deepin-image-viewer 5.9.14-3
deepin-kwin 5.25.18-4
deepin-launchpad 0.5.0-3
deepin-menu 5.0.1-17
deepin-movie 1:5.10.34-1
deepin-network-core 2.0.15-3
deepin-network-utils 5.4.13-1
deepin-pdfium 1.0.2-3
deepin-picker 6.0.1-2
deepin-polkit-agent 6.0.7-1
deepin-polkit-agent-ext-gnomekeyring 5.0.1-2
deepin-pw-check 6.0.2-2
deepin-qt-dbus-factory 6.0.1-1
deepin-qt5integration 5.6.28-2
deepin-qt5platform-plugins 5.6.28-2
deepin-qt6integration 6.0.12-2
deepin-qt6platform-plugins 6.0.12-2
deepin-screen-recorder 5.12.15-5
deepin-screensaver 5.0.18-1
deepin-screensaver-pp 0.0.4-3
deepin-session 1.2.6-2
deepin-session-shell 6.0.19-1
deepin-session-ui 6.0.19-1
deepin-shortcut-viewer 5.0.9-1
deepin-sound-theme 15.10.6-2
deepin-system-monitor 6.0.16-4
deepin-terminal 6.0.14-1
deepin-turbo 0.0.6-2
deepin-util-dfm 1.2.24-1
deepin-voice-note 6.0.18-1
deepin-wallpapers 1:1.7.7-3
deepin-widgets 6.0.14-2
deepin-wloutput-daemon 2.0.3-2
startdde 6.0.14-2
xdg-desktop-portal-dde 1.0.5-5

![Image](https://github.com/user-attachments/assets/fba71797-23ad-46f4-9564-df798459957a)

PS: "Escuro = Dark"
