### ISSUE TITLE
Can't change wallpaper through context menu option

### ISSUE THREAD

**Issue by infinitepr0** [linuxdeepin/developer-center#1728]
## Describe the bug
As the title says, changing wallpaper is not working through the 'wallpaper and screensaver settings' option in the context menu settings. Selecting the option simply causes all icons from the desktop to temporarily disappear

## To Reproduce
1. Right click on the desktop
2. Select 'wallpaper and screensaver settings'
## Expected behavior
The available wallpapers to be shown in the option bar below

## Screenshots
After clicking on the option :
![Screen Capture_20200513105606](https://user-images.githubusercontent.com/45997896/81774557-7a28e980-9508-11ea-912e-c86412ad75d5.png)

Also, I'm on the testing branch (latest updates downloaded), if that info helps.

**Comment by nalakawula** [comment]
+1 this issue also happen to me.

**Comment by infixint943** [comment]
Seems like its a problem with `deepin-wm`. Installing `deepin-kwin` fixes the issue

**Comment by Ferrmolina** [comment]
Thanks, @infixint943  after installing `deepin-kwin` it work.

**Comment by ojrcampos** [comment]
> +1 here, in my case, while clicking "wallpaper and screensaver settings", all the desktop icons and (sometimes) the dock disappear. Sometimes restart `dde-dock` is needed
> 
> ![Record](https://camo.githubusercontent.com/fa932a80a4920ee99580cdedb3d32d5cf2888748/68747470733a2f2f692e696d6775722e636f6d2f6956384e41436d2e676966)
> [Link to full gif](https://i.imgur.com/iV8NACm.gif)
> 
> **dmesg output**
> 
> ```
> [34306.712951] dde-desktop[84542]: segfault at 40 ip 0000561e0914b639 sp 00007ffc92e9a740 error 4 in dde-desktop[561e0912e000+93000]
> [34306.712963] Code: 20 ff 15 22 34 49 00 be 07 00 00 00 48 8d 3d ed 60 07 00 ff 15 b8 38 49 00 48 89 85 60 ff ff ff 48 8b 03 48 8b 80 e8 00 00 00 <48> 8b 50 40 48 89 95 70 ff ff ff 8b 02 83 c0 01 83 f8 01 0f 87 3e
> [34306.713008] audit: type=1701 audit(1589768243.985:887): auid=1000 uid=1000 gid=1000 ses=3 pid=84542 comm="dde-desktop" exe="/usr/bin/dde-desktop" sig=11 res=1
> [34306.729952] audit: type=1334 audit(1589768244.002:888): prog-id=81 op=LOAD
> [34306.730019] audit: type=1334 audit(1589768244.002:889): prog-id=82 op=LOAD
> [34306.731496] audit: type=1130 audit(1589768244.005:890): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@11-85004-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
> [34307.432000] audit: type=1131 audit(1589768244.705:891): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@11-85004-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
> [34307.694915] audit: type=1334 audit(1589768244.968:892): prog-id=82 op=UNLOAD
> [34307.694921] audit: type=1334 audit(1589768244.968:893): prog-id=81 op=UNLOAD
> ```
> 
> **Edit:**
> Thanks, @infixint943 after installing `deepin-kwin` it work.

Me Arch LInux + Deepin too. All the desktop icons and dock disappear.

Any solutuion for this problem?

**Comment by felixonmars** [comment]
For now, please install `deepin-kwin`. We are still working on https://github.com/linuxdeepin/deepin-kwin/issues/38 before making this a default.

**Comment by rshanule** [comment]
Switching to deepin-kwin no longer appears to solve this problem. Testing on 

` OS: Arch Linux x86_64 Host: VirtualBox 1.2 
Kernel: 5.15.11-arch2-1  
Packages: 766 (pacman) 
Shell: bash 5.1.12 
Resolution: 1920x1080 
DE: Deepin 20.2.2 
WM: Mutter(DeepinGala) 
Theme: deepin-dark [GTK2/3] 
Icons: ePapirus-Dark [GTK2/3] 
Terminal: deepin-terminal 
CPU: AMD Ryzen 5 3600 (4) @ 3.593GHz 
GPU: VirtualBox Graphics Adapter 
`

**Comment by rshanule** [comment]
Switching to deepin-kwin no longer appears to solve this problem. Instead, windows become un-draggable (major problem) and all transparency effects are lost (minor problem). Testing on:

OS: Arch Linux x86_64 
Host: VirtualBox 1.2 
Kernel: 5.15.11-arch2-1 
Shell: bash 5.1.12 
Resolution: 1920x1080
DE: Deepin 20.2.2 
WM: Mutter(DeepinGala) 
Theme: deepin-dark [GTK2/3] 
Icons: ePapirus-Dark [GTK2/3]
Terminal: deepin-terminal 
CPU: AMD Ryzen 5 3600 (4) @ 3.593GHz
GPU: VirtualBox Graphics Adapter
Memory: 668MiB / 7950MiB

**Comment by justforlxz** [comment]
now it's no problem, it can be work in those version:

```
deepin-kwin 5.4.26-3
kwin 5.24.5-1
deepin-file-manager 1:5.5.10-2
```
