### ISSUE TITLE
[20 BETA] Mix of white and black icons?!

### ISSUE THREAD

**Issue by atar-axis** [linuxdeepin/developer-center#1729]
## Describe the bug
I would call it a visual inconsistency, not a bug. The icons in the taskbar and the menu are sometimes white - others are black. That's not very consistent

## To Reproduce
Install Deepin v20 beta

## Expected behavior
To be consistent and more readable

## Screenshots
![Screen Capture_select-area_20200514142541](https://user-images.githubusercontent.com/11148588/81934864-f813f000-95ef-11ea-84db-76befb3a0fd3.png)

### Distro & Version
Linux Deepin 20 beta

**Comment by github-young** [comment]
Same problem here on Manjaro

**Comment by xmuli** [comment]
maybe？   @shule1987  ?
![image](https://user-images.githubusercontent.com/33887845/82401641-e36ea680-9a8c-11ea-8b98-d675c6d1d89a.png)
![image](https://user-images.githubusercontent.com/33887845/82401651-ec5f7800-9a8c-11ea-9283-8e89a8d87f73.png)

**Comment by xmuli** [comment]
Perhaps it can be thought of here as colored.

**Comment by github-young** [comment]
I just find there is no "Transparency" on Manjaro DDE settings
![图片](https://user-images.githubusercontent.com/19162282/82409072-84665d00-9a9f-11ea-9ceb-99706eee4f0f.png)

**Comment by xmuli** [comment]
> I just find there is no "Transparency" on Manjaro DDE settings
> ![图片](https://user-images.githubusercontent.com/19162282/82409072-84665d00-9a9f-11ea-9ceb-99706eee4f0f.png)

It's a magical place. @felixonmars

**Comment by github-young** [comment]
Could you please @ someone who may be in charge of the colors on title bar?
 See #1734 for details. Thank you.
![](https://user-images.githubusercontent.com/19162282/82125668-03c30a80-97da-11ea-8ed5-bd57f978a30c.png)

**Comment by xmuli** [comment]
@atar-axis 
I just updated the system to execute the `sudo apt dist-upgrade` command.
Dock icon changes found; expected to be brought to deepin v20 for release

![image](https://user-images.githubusercontent.com/33887845/82415092-939ed800-9aaa-11ea-9299-6f7480e53261.png)
![image](https://user-images.githubusercontent.com/33887845/82415122-9d284000-9aaa-11ea-98ba-7cba7caf3289.png)

**Comment by xmuli** [comment]
> @xmuli Could you please @ someone who may be in charge of the colors on title bar?
> See #1734 for details. Thank you.
> ![](https://user-images.githubusercontent.com/19162282/82125668-03c30a80-97da-11ea-8ed5-bd57f978a30c.png)

I've replied to you below #1734.

**Comment by felixonmars** [comment]
> > I just find there is no "Transparency" on Manjaro DDE settings
> > ![图片](https://user-images.githubusercontent.com/19162282/82409072-84665d00-9a9f-11ea-9ceb-99706eee4f0f.png)
> 
> It's a magical place. @felixonmars 

Perhaps you need to install deepin-kwin and restart to get that setting. Arch still has deepin-wm as default window manager.

**Comment by atar-axis** [comment]
> @atar-axis
> I just updated the system to execute the `sudo apt dist-upgrade` command.
> Dock icon changes found; expected to be brought to deepin v20 for release
> 
> ![image](https://user-images.githubusercontent.com/33887845/82415092-939ed800-9aaa-11ea-9299-6f7480e53261.png)
> ![image](https://user-images.githubusercontent.com/33887845/82415122-9d284000-9aaa-11ea-98ba-7cba7caf3289.png)

Thanks! Are There any release Dates fixed already?

**Comment by github-young** [comment]
> Perhaps you need to install deepin-kwin and restart to get that setting. Arch still has deepin-wm as default window manager.

I tried `` deepin-kwin `` and it shows transparency, but I found tons of other bugs on my Manjaro... I have to switch back to `` deepin-wm ``. Thanks anyway.

**Comment by xmuli** [comment]
> > @ atar-axis 
> > 我刚刚更新了系统以执行`sudo apt dist-upgrade`命令。
> > 找到码头图标更改；预计将被带入Deepin v20发布
> 
> @xmuli谢谢！是否有发布日期已确定？
> 您是如何得到它们的？我也跑`dist-upgrade`了，但没什么事。

The sources we use are different.
Expect the official release of deepin v20 in June, so look for it.

**Comment by atar-axis** [comment]
Looks like the Final one is out now, right?
Unfortunately those icons are still the same :(

**Comment by atar-axis** [comment]
Moreover, look at the battery icon
![Screen Capture_dde-dock_20200811131311](https://user-images.githubusercontent.com/11148588/89891201-ec2ad080-dbd4-11ea-8249-164125c5a190.png)
![Screen Capture_dde-dock_20200811131542](https://user-images.githubusercontent.com/11148588/89891204-ed5bfd80-dbd4-11ea-9463-a9a97fd352e4.png)

**Comment by xmuli** [comment]
#1844  repeat

**Comment by xmuli** [comment]
> Moreover, look at the battery icon
> ![Screen Capture_dde-dock_20200811131311](https://user-images.githubusercontent.com/11148588/89891201-ec2ad080-dbd4-11ea-8249-164125c5a190.png)
> ![Screen Capture_dde-dock_20200811131542](https://user-images.githubusercontent.com/11148588/89891204-ed5bfd80-dbd4-11ea-9463-a9a97fd352e4.png)

Already under repair

**Comment by Zeno-sole** [comment]
The latest version should not have these problems anymore
