### ISSUE TITLE
使用 Arch+DDE 时，Qt 应用中的图片会模糊

### ISSUE THREAD

**Issue by ChungZH** [linuxdeepin/developer-center#1732]
## 缺陷描述

在 Arch Linux 里使用 DDE，所有 Qt 应用中的图片都会变得模糊。包括 SVG / PNG。

但是，当我把我写的 Qt 应用换为 DDE 的 `chameleon` Qt 主题之后，一切都正常了～哦，PNG 还是有点模糊（图4）。
由于多个 Qt 应用都出现此问题，基本上可以排除是我写应用时操作不当的情况。

BTW，DDE 自带的一些应用也没有此问题。

## 复现步骤

1. 打开 Qt 应用（DDE 自带的除外）
2. 找到图片
3. 缺陷发生

## 期望行为

清晰
## 截图

我的一个小 Qt 应用：
![image](https://user-images.githubusercontent.com/42088872/82023855-7f7d6400-96c1-11ea-9e81-0acdc59efa5d.png)

Qt Creator：
![image](https://user-images.githubusercontent.com/42088872/82024057-cbc8a400-96c1-11ea-9fbc-89fa3e6193f9.png)

[Qv2ray](https://github.com/qv2ray/qv2ray)
![image](https://user-images.githubusercontent.com/42088872/82025050-565dd300-96c3-11ea-865c-789f350b4f56.png)

我的应用切换主题后：
![image](https://user-images.githubusercontent.com/42088872/82024114-df740a80-96c1-11ea-9ef6-8719867c8b2d.png)
![image](https://user-images.githubusercontent.com/42088872/82024395-4db8cd00-96c2-11ea-9291-bf2b06d66349.png)

### 发行版以及版本

Arch Linux 
DDE
### 其他内容

:dove: :dove: :dove: :dove: :dove: :dove:

**Comment by ChungZH** [comment]
BTW 顺便问一句，DDE 的 `chameleon` Qt 主题源码在哪里呀～真的好漂亮啊！

**Comment by xmuli** [comment]
这个问题，后面定位一下，暂时不知到原因，可能是 Qt 绘画导致的？；
另外 dde 的 chameleon 源码见 [chameleonstyle.cpp](https://github.com/linuxdeepin/qt5integration/blob/master/styleplugins/chameleon/chameleonstyle.cpp)

关于如何绘画 dtk ，以及它们之间的关系，可参见 [第五章](https://github.com/xmuli/QtExamples)，尤其带有小表情的文章

**Comment by xmuli** [comment]
刚更新了一章 关于 dtk 的历史说明 [DTK的历史起源、发展，和简单入门](https://xmuli.blog.csdn.net/article/details/106189533)，希望能够帮助到你

**Comment by ChungZH** [comment]
喔，谢谢大佬啦！
