### ISSUE TITLE
[20 BETA] Package Installer does not resolve dependencies

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#1733]
## Expected behavior
Allow the package installer to resolve the dependencies; downloading the required additional packages.

This command "sudo apt install ./package-name.deb" summarizes my request,

## Screenshots
![Screen Capture_deepin-deb-installer_20200515102958](https://user-images.githubusercontent.com/45263160/82055710-4cbe7600-9697-11ea-9946-bb899d49bc91.png)
![Screen Capture_select-area_20200515103121](https://user-images.githubusercontent.com/45263160/82055730-51832a00-9697-11ea-89e0-84563cf40c13.png)

### Distro & Version
deepin 20 BETA

### Related package version
deepin-deb-installer 5.3.13.1

**Comment by gokhanyildirimlar** [comment]
https://github.com/linuxdeepin/developer-center/issues/1684

**Comment by github-young** [comment]
You can try gdebi

**Comment by alexwender1** [comment]
> You can try gdebi

Yes, it is possible. But deepin's own application is in trouble and needs to be fixed; the deepin user does not need to leave the "deepin ecosystem".

**Comment by crazy-noray** [comment]
Hello, I am the developer of the deepin-deb-installer. Have you tried using the new version of the deepin-deb-installer? If you are using a newer version, please contact me again. It is best to provide the software package that failed to install, which can help us better locate the problem

**Comment by lxwndr** [comment]
> Hello, I am the developer of the deepin-deb-installer. Have you tried using the new version of the deepin-deb-installer? If you are using a newer version, please contact me again. It is best to provide the software package that failed to install, which can help us better locate the problem

At the moment, my deepin is on a production machine and the installation is already old (many of the dependencies have already been installed).

As soon as I do a new installation of the system, I will do these tests.

**Comment by Zeno-sole** [comment]
Has been fixed in the new version
