### ISSUE TITLE
[20 BETA] Non-Deepin software title bar not distinguisable in dark theme. 深色主题下第三方软件标题栏文字不反色，导致无法看清

### ISSUE THREAD

**Issue by github-young** [linuxdeepin/developer-center#1734]
## Describe the bug 缺陷描述
Non-Deepin software title bar is not distinguisable in dark theme. The text in title bar do not hvae their color inversed in dark theme.
深色主题下，第三方（即非Deepin）软件标题栏文字不反色，导致无法看清。

## To Reproduce 复现步骤
Change the icon theme to dark in control center.
在控制中心将系统主题改为深色模式。

## Expected behavior 期望行为
Non-Deepin software should also have a distinguisbale title bar.
非Deepin软件也应该保持标题栏内容清晰可辨。

## Screenshots 截图
1. Normal behaviour: Light theme 正常情况：亮色主题
![light](https://user-images.githubusercontent.com/19162282/82125661-f86fdf00-97d9-11ea-952b-f5dea4cf5c90.png)
2. Abnormal behaviour: Dark theme 异常情况：暗色主题
The text within the red rectangle can hardly be seen. 红框里的文字几乎无法看清。
![dark](https://user-images.githubusercontent.com/19162282/82125668-03c30a80-97da-11ea-8ed5-bd57f978a30c.png)

## 复现环境:
No special environment.

### Distro & Version 发行版以及版本
Manjaro Linux 20.0.1 Lysia
Deepin Desktop Environment

### Related package version 相关的软件包版本
```sh
pacman -Q | egrep -i "deepin|dde"

deepin-account-faces 1.0.11-1.1
deepin-anything 5.0.1-2
deepin-anything-dkms 5.0.1-2
deepin-api 5.1.11.1-1
deepin-calculator 5.5.9-1
deepin-calendar 5.6.2-1
deepin-clutter 1.26.2-2
deepin-cogl 1.22.5-3
deepin-control-center 5.1.0.5-1
deepin-daemon 5.10.0.1-1
deepin-desktop-base 3:2019.07.10-1
deepin-desktop-schemas-manjaro 5.5.0.0-1
deepin-dock 5.1.0.9-1
deepin-draw 5.8.0.16-1
deepin-file-manager 1:5.1.1.25-1
deepin-fonts-wine 2.18_22-1
deepin-gtk-theme 17.10.11-1
deepin-icon-theme 2020.05.09-1
deepin-iconthemes-manjaro 20170918-1
deepin-image-viewer 5.6.3.2-1
deepin-launcher 5.1.0099.0-1
deepin-libwine 2.18_22-1
deepin-menu 5.0.1-1
deepin-metacity 3.22.24-1
deepin-movie 1:5.7.6.29-1
deepin-music 6.0.1.8-1
deepin-mutter 3.20.38-4
deepin-network-utils 5.1.0.0-1
deepin-picker 5.0.6-1
deepin-polkit-agent 5.1.0-2
deepin-polkit-agent-ext-gnomekeyring 0.1.0-1
deepin-qt-dbus-factory 5.1.0.1-1
deepin-qt5dxcb-plugin 5.0.11-1
deepin-qt5integration 5.1.0.1-2
deepin-screen-recorder 5.8.0.11-1
deepin-session-shell 5.0.0098.0-2
deepin-session-ui 5.1.0099.4-1
deepin-shortcut-viewer 5.0.2-1
deepin-sound-theme 15.10.4-1
deepin-system-monitor 5.6.1-1
deepin-terminal 5.0.4.1-1
deepin-turbo 0.0.3-1
deepin-udis86 1.72_2-3
deepin-wallpapers 2:1.7.7-1
deepin-wine 2.18_22-3
deepin-wine-binfmt 2.18_22-1
deepin-wine-helper 1.2-2
deepin-wine-plugin 1.0.2-2
deepin-wine-plugin-virtual 1.0.3-1
deepin-wine-uninstaller 0.1.2-2
deepin-wine32 2.18_22-1
deepin-wine32-preloader 2.18_22-1
deepin-wine32-tools 2.18_22-1
deepin-wm 1.9.38-4
deepin.com.qq.office 2.0.0_4-2
manjaro-deepin-settings 20191111-1
startdde 5.3.0.1-2
```

### Additional context 其他内容
I want to have the taskbar (dock) to be able to customize color theme independent to system theme, just as other deepin apps like dde-file-manager, monitor...
我希望任务栏（dock栏）也可以独立调节亮/暗主题，就像其它的deepin软件一样，比如文件管理器、系统监视器等。

**Comment by xmuli** [comment]
@github-young The third party software you use, and the dde used above Manjaro, (not deepin or uos), see the screenshot is typora (a software I also like).

I tested typora + notepadqq on top of uos v20 sp1, under the dark theme, it is possible to see clearly

And there is no separate person in charge of the title bar, and I think this could be a result of some other reason. If you are interested, you can try to find the cause yourself, and if there is a follow-up result, I'm looking forward to it; I'll keep an eye on it later.

![image](https://user-images.githubusercontent.com/33887845/82415795-a239bf00-9aab-11ea-893b-c2456e4846c2.png)

**Comment by github-young** [comment]
> @github-young The third party software you use, and the dde used above Manjaro, (not deepin or uos), see the screenshot is typora (a software I also like).
> 
> I tested typora + notepadqq on top of uos v20 sp1, under the dark theme, it is possible to see clearly
> 
> And there is no separate person in charge of the title bar, and I think this could be a result of some other reason. If you are interested, you can try to find the cause yourself, and if there is a follow-up result, I'm looking forward to it; I'll keep an eye on it later.
> 
> ![image](https://user-images.githubusercontent.com/33887845/82415795-a239bf00-9aab-11ea-893b-c2456e4846c2.png)

I tried install `` deepin-kwin `` but it causes more bugs than it fixes, so I just give up. I don't think I can figure out the reason so I just accept this issue. Only using the light theme is OK. Thank you.
