### ISSUE TITLE
[20 BETA] WineHQ 5+ does not install

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#1735]
## Describe the bug
It is not possible to install Wine 5, due to lack of dependencies.

As of Wine 5, it is mandatory to install the _FAudio_ package; which is not available in the Wine or debian Buster repository.

FAudio will be provided in the repository from debian Bullseye.

Can you add this package to the deepin repository?

## Screenshots
![photo5046610792576821432](https://user-images.githubusercontent.com/45263160/82174369-d8f2b800-98a6-11ea-8c44-a4ee8ebbba92.jpg)

### Distro & Version
deepin 20 BETA

### Related package version
winehq-stable 5.0 (from the official website)

### Additional context
More information: https://forum.winehq.org/viewtopic.php?f=8&t=32192

**Comment by gokhanyildirimlar** [comment]
I don't remember exactly but a library is missing in the repository. It might be **libfaudio0** if I recall correctly. Once you install this manually, you should be able to install Wine 5.0. But yeah, dependency problems should be solved and repository should be maintained.

**Comment by xmuli** [comment]
Try using deepin-wine? It is a custom version of the deepin team
Let's see if it meets your needs.

[Deepin-wine](https://wiki.deepin.org/wiki/Deepin-wine)
