### ISSUE TITLE
[20 BETA] Allow certain applications to run on the Dedicated GPU (AMD)

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#1736]
## Describe the bug

Although **AMD GPU**s are natively compatible with Linux; it is not possible to use them in a practical way in deepin. The system's _Graphics Driver Manager_ itself does not recognize some cards (although the driver is active).

![Screen Capture_deepin-graphics-driver-manager_20200506162153](https://user-images.githubusercontent.com/45263160/82177896-28d67c80-98b1-11ea-9d5a-201df22ef54b.png)
![Screen Capture_deepin-terminal_20200518024253](https://user-images.githubusercontent.com/45263160/82177963-4c99c280-98b1-11ea-8b96-cb10ce7bddf3.png)

For laptops, there is the **PRIME GPU Offloading**, which allows you to run certain applications on the Dedicated GPU (while the system runs on the Integrated GPU).

For example, GNOME presents this functionality in a practical way; with one click, the user is already running any application on the Dedicated GPU.

![36631645-d2c69328-19b6-11e8-97fc-3106805eb5d6](https://user-images.githubusercontent.com/45263160/82177982-591e1b00-98b1-11ea-9c67-ea99886273c7.png)

The [PRIME Settings](https://github.com/LinuxbuzzSoftware/prime-settings) presents a similar proposal, but is limited to some applications. The application displays an error message; I believe it is due to the lack of drivers (which I will detail below). I will contact the developer for more information.

### Additional context
When following the driver installation guidelines for the AMD GPU (Vulkan, OpenCL and Firmware), practically everything installed normally; with the exception of _firmware-linux_ and _firmware-linux-nonfree_ packages.

![001](https://user-images.githubusercontent.com/45263160/82179266-46591580-98b4-11ea-9836-dfd7c114d00d.png)
![002](https://user-images.githubusercontent.com/45263160/82179273-4a853300-98b4-11ea-95db-8681c2b3673f.png)
![003](https://user-images.githubusercontent.com/45263160/82179282-4e18ba00-98b4-11ea-8cdf-99c4c644bab8.png)

**Comment by alexwender1** [comment]
The _firmware-linux-nonfree_ package is required to run DRI Offloading; but an installation error occurs (it cannot be installed).

https://wiki.debian.org/AtiHowTo

![82245032-98338700-9918-11ea-87d3-858bdcb10ced](https://user-images.githubusercontent.com/45263160/82260715-25380980-9934-11ea-810a-b18e1ba659c7.png)

**Comment by alexwender1** [comment]
The problem persists in version 20 (1001). When installing the _firmware-linux-nonfree_ package, an error occurs.

> **sudo apt install firmware-linux-nonfree libgl1-mesa-dri libglx-mesa0 mesa-vulkan-drivers xserver-xorg-video-all**
> 
> https://wiki.debian.org/AtiHowTo
> 

![Screen Capture_deepin-terminal_20200826125851](https://user-images.githubusercontent.com/45263160/91333407-f12a7b00-e7a3-11ea-9591-77f1afdf62fc.png)
![Screen Capture_deepin-terminal_20200826125859](https://user-images.githubusercontent.com/45263160/91333421-f4be0200-e7a3-11ea-80ab-011e7a206132.png)

**Comment by alexwender1** [comment]
The problem persists in the new version: deepin 20.1 (1010) / OsBuild=11031.108

**Comment by lxwndr** [comment]
I open a new topic in https://github.com/linuxdeepin/developer-center/issues/2083
