### ISSUE TITLE
"Join user experience Program" setting cannot be turned off

### ISSUE THREAD

**Issue by franklinnowell** [linuxdeepin/developer-center#1738]
## Describe the bug
The setting "Join user experience Program" doesn't work

## To Reproduce
Just try to turn if off, if you go back, it's still on! (See gif bellow)

## Expected behavior
It should be turned off

### Additional context
Anyway, there has been serious alert concerning this daunting feature https://github.com/linuxdeepin/developer-center/issues/1261
But at least it should be possible to disable it.
![deepin_user_experience_consent](https://user-images.githubusercontent.com/2970623/82445085-e37e9e80-9aac-11ea-9f6d-16ab85f6cb1c.gif)

Regards,
Thanks

**Comment by xmuli** [comment]
Deepin v20 beta found on it? I tested on UOS V20 that it is off by default and that it is possible to allow switching on and off

![image](https://user-images.githubusercontent.com/33887845/82450126-dda1b100-9ade-11ea-9708-19987376306d.png)

**Comment by franklinnowell** [comment]
Thanks for the reply @xmuli . It's on archLinux using dde, And as I did a full system upgrade this morning, I should be running the latest versions found here https://www.archlinux.org/groups/x86_64/deepin/.

**Comment by xmuli** [comment]
If you have time, can you take a look? I'm not very good at arch linux yet. @felixonmars ；

**Comment by felixonmars** [comment]
We apparently have a broken dde-control-center release and the underlying "deepin-user-experience-daemon" was not packaged or perhaps even open-sourced. So currently the switch is a no-op and should be hidden after further fix-ups.

**Comment by felixonmars** [comment]
Please try deepin-control-center 5.1.0.12.20200429-1.

**Comment by franklinnowell** [comment]
As of deepin-control-center-5.1.0.12.20200427-1 which the latest available in rolling arch, the setting "Join User experience Program" totally disappeared, I don't know if it is intended on purpose and this feature is completely removed. It would be great if someone shed some light on this.
Thanks again

**Comment by felixonmars** [comment]
> As of deepin-control-center-5.1.0.12.20200427-1 which is the latest available in rolling arch, the setting "Join User experience Program" totally disappeared, I don't know if it is intended on purpose and the feature is completely removed. It would be great if someone shed some light on this.
> Thanks again

Like I said in https://github.com/linuxdeepin/developer-center/issues/1738#issuecomment-632269281, the switch was always a no-op since the underlying daemon implementing this was never packaged on Arch.

**Comment by franklinnowell** [comment]
Thanks for the clarification @felixonmars and thanks for the fix.
Regards
