### ISSUE TITLE
[Deepin20Beat] 登录界面和启动器界面背景有点问题（Archlinux）

### ISSUE THREAD

**Issue by sheriby** [linuxdeepin/developer-center#1747]
## 截图
![](https://s1.ax1x.com/2020/05/25/tpRiKf.png)
![](https://s1.ax1x.com/2020/05/25/tp2LDO.png)

## 缺陷描述
升级到Deepin20Beat之后，这些界面的背景变得非常奇怪。
没升级之前都是Blur的背景看起来很舒服，现在好像变成了蒙了一层纯色的背景。

## 期望行为
通过什么设置可以恢复到升级之前的背景呢？

### 发行版以及版本
Archlinux x86_64
Linux 5.4.42-1-lts

### 相关的软件包版本
sudo pacman -Q | grep -E "deepin|dde" 
deepin-account-faces 1.0.11-1
deepin-album 5.6.9.13-1
deepin-anything 5.0.1-2
deepin-anything-arch 5.0.1-82
deepin-api 5.1.11.1-1
deepin-boot-maker 5.4.8-1
deepin-calculator 5.5.10-1
deepin-calendar 5.6.3-1
deepin-clone 5.0.3-1
deepin-clutter 1.26.2-2
deepin-cogl 1.22.5-3
deepin-community-wallpapers 1:1.7.7-1
deepin-control-center 5.1.0.12.20200429-1
deepin-daemon 5.10.0099.2-1
deepin-desktop-base 2:2020.04.12.2-1
deepin-desktop-schemas 5.5.0.0-1
deepin-dock 5.1.0.9-1
deepin-draw 5.8.0.18-1
deepin-editor 5.6.9-1
deepin-file-manager 1:5.1.1.25-1
deepin-fonts-wine 2.18_22-1
deepin-gtk-theme 17.10.11-1
deepin-icon-theme 2020.05.21-1
deepin-image-viewer 5.6.3.2-1
deepin-launcher 5.2.0.0-1
deepin-libwine 2.18_22-1
deepin-menu 5.0.1-1
deepin-metacity 3.22.24-1
deepin-movie 1:5.7.6.29-1
deepin-music 6.0.1.8-1
deepin-mutter 3.20.38-4
deepin-network-utils 5.1.0.0-1
deepin-picker 5.0.6-1
deepin-polkit-agent 5.1.0-2
deepin-polkit-agent-ext-gnomekeyring 0.1.0-1
deepin-qt-dbus-factory 5.1.0.1-1
deepin-qt5dxcb-plugin 5.0.11-1
deepin-qt5integration 5.1.0.1-2
deepin-reader 5.6.4-1
deepin-screen-recorder 5.8.0.11-2
deepin-screensaver 5.0.3-1
deepin-screensaver-pp 0.0.4-1
deepin-session-shell 5.0.0098.0-2
deepin-session-ui 5.1.0101.0-1
deepin-shortcut-viewer 5.0.2-1
deepin-sound-theme 15.10.6-1
deepin-system-monitor 5.6.2-1
deepin-terminal 5.0.4.1-1
deepin-turbo 0.0.3-1
deepin-udis86 1.72_2-3
deepin-wallpapers 1:1.7.7-1
deepin-wine 2.18_22-3
deepin-wine-binfmt 2.18_22-1
deepin-wine-helper 1.2-2
deepin-wine-plugin 1.0.2-2
deepin-wine-plugin-virtual 1.0.3-1
deepin-wine-uninstaller 0.1.2-2
deepin-wine-wechat 2.8.0.133-2
deepin-wine32 2.18_22-1
deepin-wine32-preloader 2.18_22-1
deepin-wine32-tools 2.18_22-1
deepin-wm 1.9.38-4
deepin.com.qq.im 9.1.8-1
startdde 5.3.0.1-3

**Comment by gardotd426** [comment]
I think they got rid of the blur on the launcher. But yeah, I have no blur either. 

![blurbug1](https://user-images.githubusercontent.com/54234607/82868253-497a8400-9efa-11ea-9e21-37e05d50de47.jpg)

**Comment by HUSTERGS** [comment]
Mine is functioning normally
![image](https://user-images.githubusercontent.com/32388319/82868939-05ba6580-9f60-11ea-87cc-7d7c0d6c6cb1.png)

**Comment by gardotd426** [comment]
Definitely a bug then

**Comment by sheriby** [comment]
I have partial blur background....
![](https://s1.ax1x.com/2020/05/26/tiVFbj.png)

**Comment by gardotd426** [comment]
Yeah same here, if I use the category view the categories are blurred but only the same sections as yours in the above picture, but in regular view there's zero blur.

**Comment by sheriby** [comment]
That is unpleasant without blur in login and launcher view. I have tried to rollback DDE through Arch ALA, but failed due to some unknown system environment problem. Annoyed. :(

**Comment by gardotd426** [comment]
Use downgrade from the AUR. You'll have to downgrade every deepin/dde package you have installed, but all you have to do is run "downgrade packagename1 packagename2 packagename3 packagename4 ...." Then you get an option for which version of each package you want.

**Comment by sheriby** [comment]
I have tried it. That is too slow to rollback from official ala repository from Chinese Mainland. Therefore I rollback through Tsinghua University Arch Linux Rollback Machine, and then my system crashed with no reason...

**Comment by gardotd426** [comment]
I guess you've cleared your cache and don't have them locally? And are there not any other repos?

I can pull things from a mirror on the other side of the planet and it still doesn't slow down that much, I would just try different mirrors. Use fetchmirrors, have it rank 20 mirrors or so, and try again.
Alternatively, backup your current mirrorlist, and create a new one with this. There should be plenty of mirrors for you to download a few hundred MB.
#Taiwan
Server = http://archlinux.cs.nctu.edu.tw/$repo/os/$arch
Server = http://shadow.ind.ntou.edu.tw/archlinux/$repo/os/$arch
Server = http://ftp.tku.edu.tw/Linux/ArchLinux/$repo/os/$arch
Server = https://shadow.ind.ntou.edu.tw/archlinux/$repo/os/$arch
Server = http://ftp.yzu.edu.tw/Linux/archlinux/$repo/os/$arch
Server = https://ftp.yzu.edu.tw/Linux/archlinux/$repo/os/$arch
#Mainland China
Server = https://mirrors.neusoft.edu.cn/archlinux/$repo/os/$arch
Server = http://mirrors.cqu.edu.cn/archlinux/$repo/os/$arch
Server = http://mirror.redrock.team/archlinux/$repo/os/$arch
Server = http://mirror.lzu.edu.cn/archlinux/$repo/os/$arch
Server = http://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch
Server = https://mirrors.bfsu.edu.cn/archlinux/$repo/os/$arch
Server = https://mirror.redrock.team/archlinux/$repo/os/$arch
Server = https://mirrors.sjtug.sjtu.edu.cn/archlinux/$repo/os/$arch
Server = http://mirrors.zju.edu.cn/archlinux/$repo/os/$arch
Server = http://mirrors.163.com/archlinux/$repo/os/$arch

**Comment by sheriby** [comment]
Here is my mirriorlist.
```
## Arch Linux repository mirrorlist
## Filtered by mirror score from mirror status page
## Generated on 2020-02-01
##
## China
# Rollback My Arch
#Server = https://arch-archive.tuna.tsinghua.edu.cn/2020/03-30/$repo/os/$arch
Server = http://mirrors.163.com/archlinux/$repo/os/$arch
Server = http://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch
Server = http://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch
Server = http://mirrors.zju.edu.cn/archlinux/$repo/os/$arch
Server = http://mirrors.cqu.edu.cn/archlinux/$repo/os/$arch
Server = http://mirrors.neusoft.edu.cn/archlinux/$repo/os/$arch
Server = http://mirror.lzu.edu.cn/archlinux/$repo/os/$arch
```
Use `Server = https://arch-archive.tuna.tsinghua.edu.cn/2020/03-30/$repo/os/$arch` to rollback.

**Comment by gardotd426** [comment]
I'd get rid of zju and cqu, and add the bfsu mirror from the list I gave you. Also, get rid of the Use Server line. Well don't get rid of it, just comment it out for now. downgrade doesn't require a rollback mirror. You just type downgrade and then the list of package names each separated by a space.

Sorry I'm replying by email so can't use code tags, but here look at what "downgrade deepin-control-center" returns just for example:
downgrade deepin-control-center
Available packages:

1) deepin-control-center 4.8.7.2 1 x86_64 (remote)
2) deepin-control-center 4.9.0 1 x86_64 (remote)
3) deepin-control-center 4.9.1 1 x86_64 (remote)
4) deepin-control-center 4.9.2 1 x86_64 (remote)
5) deepin-control-center 4.9.2.1 1 x86_64 (remote)
6) deepin-control-center 4.9.2.1 2 x86_64 (remote)
7) deepin-control-center 4.9.4 1 x86_64 (remote)
8) deepin-control-center 4.9.5 1 x86_64 (remote)
9) deepin-control-center 4.9.6 1 x86_64 (remote)
10) deepin-control-center 4.9.6 2 x86_64 (remote)
11) deepin-control-center 4.9.7 1 x86_64 (remote)
12) deepin-control-center 4.9.8 1 x86_64 (remote)
13) deepin-control-center 4.9.9.1 1 x86_64 (remote)
14) deepin-control-center 4.9.9.2 1 x86_64 (remote)
15) deepin-control-center 4.9.9.3 1 x86_64 (remote)
16) deepin-control-center 4.9.9.4 1 x86_64 (remote)
17) deepin-control-center 4.9.10 1 x86_64 (remote)
18) deepin-control-center 4.9.12 1 x86_64 (remote)
19) deepin-control-center 4.9.13 1 x86_64 (remote)
20) deepin-control-center 4.10.0 1 x86_64 (remote)
21) deepin-control-center 4.10.2 1 x86_64 (remote)
22) deepin-control-center 4.10.3 1 x86_64 (remote)
23) deepin-control-center 4.10.4 1 x86_64 (remote)
24) deepin-control-center 4.10.5 1 x86_64 (remote)
25) deepin-control-center 4.10.6 1 x86_64 (remote)
26) deepin-control-center 4.10.7 1 x86_64 (remote)
27) deepin-control-center 4.10.8 1 x86_64 (remote)
28) deepin-control-center 4.10.9 1 x86_64 (remote)
29) deepin-control-center 4.10.10 1 x86_64 (remote)
30) deepin-control-center 4.10.11 1 x86_64 (remote)
31) deepin-control-center 4.10.12 1 x86_64 (remote)
32) deepin-control-center 4.10.13 1 x86_64 (remote)
33) deepin-control-center 4.10.14 1 x86_64 (remote)
34) deepin-control-center 5.0.0 1 x86_64 (remote)
35) deepin-control-center 5.1.0.0 1 x86_64 (remote)
36) deepin-control-center 5.1.0.1 1 x86_64 (remote)
37) deepin-control-center 5.1.0.1 2 x86_64 (remote)
38) deepin-control-center 5.1.0.1 3 x86_64 (remote)
39) deepin-control-center 5.1.0.5 1 x86_64 (remote)
40) deepin-control-center 5.1.0.11 1 x86_64 (remote)
41) deepin-control-center 5.1.0.12 1 x86_64 (remote)
- 42) deepin-control-center 5.1.0.12.20200429 1 x86_64 (remote)
- 43) deepin-control-center 5.1.0.12.20200429 1 x86_64 (local)
+ 44) deepin-control-center 5.1.0101.0.20200427 1 x86_64 (remote)
+ 45) deepin-control-center 5.1.0101.0.20200427 1 x86_64 (local)

select a package by number:
Those are packages going back like a year, and I don't have any rollback server in my mirrorlist. That's what's killing you, you don't need to use a rollback server. They're way too slow. Just comment out the "Use Server" line, install downgrade from the AUR if you don't have it already, and run "downgrade pkg1 pkg2 pkg3 pkg4 pkg5 pkg6 pkg7 ...." Or to make it easy you could just run:
downgrade $(yay -Qq | egrep "deepin|dde")
That way you don't have to worry about typing all the deepin packages or copying a list.

**Comment by sheriby** [comment]
There's no response when using downgrade.
`downgrade` is just a tool to help us rollback from official ala repository(archive.archlinux.org). But in Chinese Mainland, it is too slow to download from this website, so I don't use tools like 'downgrade'.(Maybe it is the problem of my network?)
Perhaps I can use downgrade through 'downgrade --ala-path "https://arch-archive.tuna.tsinghua.edu.cn/2020/03-30/$repo/os/$arch" pkg1 pkg2 pkg3'
see [archwiki ala](https://wiki.archlinux.org/index.php/Arch_Linux_Archive)

**Comment by justforlxz** [comment]
this is our new design.
