### ISSUE TITLE
Deepin's End User License Agreement (EULA) is incompatible with the GPL v3 License it's issued under

### ISSUE THREAD

**Issue by gardotd426** [linuxdeepin/developer-center#1749]
So, I spent some time reading the EULA today, and there are some serious issues. 

Namely, it's illegal. 

The Deepin Desktop Environment (and I imagine all of Deepin OS, but I'm on Arch) is licensed under GPL version 3. GPL v3 guarantees the user the right to redistribute modified or non-modified copies of all software licensed under the GPL. In it's own words:

> To protect your rights, we need to prevent others from denying you these rights or asking you to surrender the rights. Therefore, you have certain responsibilities if you distribute copies of the software, or if you modify it: responsibilities to respect the freedom of others.

> Developers that use the GNU GPL protect your rights with two steps: (1) assert copyright on the software, and (2) offer you this License **giving you legal permission to copy, distribute and/or modify it**.

> **You may convey verbatim copies of the Program's source code as you receive it, in any medium**, provided that you conspicuously and appropriately publish on each copy an appropriate copyright notice; keep intact all notices stating that this License and any non-permissive terms added in accord with section 7 apply to the code; keep intact all notices of the absence of any warranty; and give all recipients a copy of this License along with the Program. 

>You may convey a covered work in object code form

And yet, the Deepin EULA states:

>Redistribution. You are not permitted to redistribute (including but not limited to software sales, pre-installation, bundling, etc) any of the software or its components, whether they have been modified or not. 

The EULA is directly incompatible with the License the software is issued under. We are free to redistribute modified or unmodified code under the GPL, and the GPL bars you from revoking that right.

**Comment by chemel9** [comment]
deepin developers can't answer this question?

**Comment by gardotd426** [comment]
I guess not. I'm going to go ahead and freely modify and redistribute as much as I want, because it's under the GPL and including a bullshit EULA that tries and negate the GPL doesn't actually negate the GPL.

**Comment by xmuli** [comment]
The EULA will be updated later (revision in progress).

**Comment by gardotd426** [comment]
Fair enough, thanks for the update
