### ISSUE TITLE
Use GTK3 instead of GTK2

### ISSUE THREAD

**Issue by City-busz** [linuxdeepin/developer-center#175]
Currently the following components still use the old GTK+ 2 toolkit. Please either port them to GTK+ 3 or remove the GTK+ dependency.

- [x] [dde-file-manager](https://github.com/linuxdeepin/dde-file-manager)
- [x] [dde-launcher](https://github.com/linuxdeepin/dde-launcher)
- [x] [deepin-notifications](https://github.com/linuxdeepin/deepin-notifications)
- [x] [qt5integration](https://github.com/linuxdeepin/qt5integration)
- [x] [dde-session-ui](https://github.com/linuxdeepin/dde-session-ui)

**Comment by City-busz** [comment]
Is there any progress?

**Comment by hualet** [comment]
Some of projects list above is ported to use QIcon now, which is powered by QtXdg on deepin, but it's still experimental, so the others like dde-launcher are still stick to the gtk implementation to look up icons. They sure will be eventually all ported to use QIcon, but the QtXdg based QIcon should be proved to be stable before that happen.

**Comment by hualet** [comment]
Dependency declaration of some already ported project may need to be updated by the developers though :joy:

**Comment by City-busz** [comment]
Only three projects left that still use GTK+ 2. Could anyone finish the port?

**Comment by hualet** [comment]
deepin-qml-widgets is obsolete and will no longer be used when the new version of deepin-movie is out.
dde-qt5integration can not be changed to use GTK3 because DDE is currently still targeting Qt5.6.
dde-file-manager @dragondjf

**Comment by City-busz** [comment]
Is there any progress?

**Comment by City-busz** [comment]
It seems to be done.
