### ISSUE TITLE
自带pdf阅读器退出时逻辑问题

### ISSUE THREAD

**Issue by honyxiao** [linuxdeepin/developer-center#1750]
## 缺陷描述
deepin自带的pdf阅读器,当添加注释后,关闭文档,提示是否保存或取消,
点击取消按钮,会直接退出软件

## 期望行为
点击取消按钮,不退出软件,只关闭提示框

### 发行版以及版本
Linux Deepin 20 beta

**Comment by xmuli** [comment]
Thankfully, it has been verified that it did not reappear above UOS 20, but did reappear in deepin 20; will be fixed later
