### ISSUE TITLE
[Feature request] Change transparency of every Deepin applications

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#1757]
We can now change the transparency of Deepin-dock but not the transparency of other Deepin programs. It would be really great if we could.

**Comment by xmuli** [comment]
The transparency of Deepin-dock can be changed all the time, as well as in its own terminal, but some of them may not be suitable for other types of software (not all the rest).

**Comment by meiyixiang** [comment]
13/5000 
Thank you for your opinion opinion record and feedback
