### ISSUE TITLE
Deepin Editor fails to detect Turkish characters

### ISSUE THREAD

**Issue by gokhanyildirimlar** [linuxdeepin/developer-center#1761]
## Describe the bug
Deepin Editor fails to detect Turkish characters and it shows weird symbols when I opened the document later. 

## To Reproduce
1. Create a plain text document.
2. Type something Turkish and save.
3. Open to edit or to see what's written inside.

## Expected behavior
Deepin Editor must detect characters and set the document as UTF-8 by itself.

## Video
https://sendvid.com/ao7bfq1j
(Correction of a grammar mistake on the video. I wanted to say it also fails to set the document as UTF-8.)

### Distro & Version
Linux Deepin 20 Beta

### Related package version
deepin-editor v5.6.5 (5.6.5-1)

**Comment by xmuli** [comment]
Thanks for your feedback, I reproduce it here too, and have passed it on to the editor's staff, your suggestions will help make this tool even better!

**Comment by HalfGodJ** [comment]
Detect characters bothers me a lot,so does translation.

**Comment by gokhanyildirimlar** [comment]
I can see this issue has resolved with hard coding. 
https://github.com/linuxdeepin/deepin-editor/commit/5e3a1bc28b133c194cdae77192bb5fbae71fcda8
