### ISSUE TITLE
where is the source code?

### ISSUE THREAD

**Issue by chemel9** [linuxdeepin/developer-center#1762]
deepin Developers
could you please tell me , where is the source code of  deepin-user-experience-deamon ?
Why not found? , 
**is it not open source?**
**is proprietary code?**

![image](https://user-images.githubusercontent.com/53887207/84328524-d3a42880-ab47-11ea-9210-ffd97f2eef8c.png)
![ffds](https://user-images.githubusercontent.com/53887207/84328529-d6068280-ab47-11ea-85e6-2122d6562f6b.png)

**Comment by xmuli** [comment]
This part is not part of open source, please understand; by the way, I would like to ask, how Figure 2 is exported (or viewed there), quite curious!
![b7aaa005-bcef-4cd9-91d8-b2b2c7ea9609](https://user-images.githubusercontent.com/33887845/84347776-f84edd80-abe5-11ea-985d-f22b1465dd35.png)

**Comment by chemel9** [comment]
> This part is not part of open source, please understand; by the way, I would like to ask, how Figure 2 is exported (or viewed there), quite curious!
> ![b7aaa005-bcef-4cd9-91d8-b2b2c7ea9609](https://user-images.githubusercontent.com/33887845/84347776-f84edd80-abe5-11ea-985d-f22b1465dd35.png)
> 

So If it is not open source, it is proprietary code, and therefore nobody knows that it has that code, also that code can be spyware. In conclusion deepin is spyware

**Comment by xmuli** [comment]
I'm referring to the names and version information of all the software in this picture (I've been meaning to compile a table like this); is there a command that can be used to get it? 

Also, for privacy considerations, you can see here that it is disabled by default, and requires a manual click to turn it on. #1261  #1738

**Comment by chemel9** [comment]
> I'm referring to the names and version information of all the software in this picture (I've been meaning to compile a table like this); is there a command that can be used to get it? 
> 
> Also, for privacy considerations, you can see here that it is disabled by default, and requires a manual click to turn it on. #1261  #1738

Ah , The image is from the distrowatch website, I found that table right there, with the names of the packages and their versions.

**Comment by gokhanyildirimlar** [comment]
Did someone come here after seeing the video of Quidsup? :smile: 

That kind of people only spread Anti-China propaganda and you should be aware of this before believing what he says and calling something spyware. It's been stated by me and others in the comments that User Experience Program comes disabled out of the box and it collects data only if you opt-in. So there is no need to concern about this. If you're too concerned about the situation, you can always choose not to use Deepin. 

Anyway, it's not even possible to opt-in right now because Deepin 20 Beta doesn't have this functionality built-in yet.

**Comment by xmuli** [comment]
@gokhanyildirimlar Thanks, there was some thought given to this situation, and the screenshot of it shows that he was searching directly for the process with the specified name, and then mentioned This issuse, obviously, is purposeful, but we still believe that the users of deepin aren't just trying to get their hands on it. It's malicious. And a lot of questions would be nice to have explained.
