### ISSUE TITLE
【deepin_V23_alpha2】【提示】【有空】【github反馈】【DDE】【控制中心】系统语言为阿拉伯语时，控制中心显示存在异常

### ISSUE THREAD

**Issue by ghost** [linuxdeepin/developer-center#1765]
Deepin V20 BETA looks promising as a good replacement for windows and macOS. 

The problem with some languages like the Arabic language is that they have the Right-to-left system and that forces the whole system layout to be shown from right to left instead of the regular left to right. Some graphical issues like showing content over other content will be the result. This problem is fixed in windows and macOS since forever, they managed to rearrange the whole system to fit this kind of RTL systematic layout, but in DeepinOS, the problem is still there. 

Here are some pictures from the Deepin Environment with Arabic:

![photo_2020-06-14_18-57-44](https://user-images.githubusercontent.com/32032636/84599266-12e8b700-ae71-11ea-992a-302df5ccc52f.jpg)
![photo_2020-06-14_18-57-49](https://user-images.githubusercontent.com/32032636/84599267-1419e400-ae71-11ea-8630-20e5534826ae.jpg)
![photo_2020-06-14_18-57-55](https://user-images.githubusercontent.com/32032636/84599268-14b27a80-ae71-11ea-8f71-1b48fa1636e4.jpg)

I suggest:
The team do not have to rearrange the whole layouts as Apple and Microsoft did, the easy way to fix this issue is to force the system to stay in the LTR (Left to right, like in Eglish and other Latin Languages) mode even though the user might choose Arabic 

Credits:
@markopejovic or Пеја for being such a great person in the first place and for being such an amazing contributor in the Deepin Community in the second place.
Me, the one who didn't do anything :) all pictures are from Пеја, see, I literally didn't do anything.

**Comment by xmuli** [comment]
Thanks for the feedback, it helped us find an overlooked area,
Forcing left to right is an uncomfortable habit for some regions; it's like forcing us (English/Chinese) to go from right to left. To the left of the reading experience, a brief experience of the Arabic language, as if the control center was slightly different, here is Let me talk to the engineer, and we'll fix it as soon as possible. If there's time, we'd like to do the best we can.

**Comment by THEMAXIMUMPOWER** [comment]
@xmuli thank you very much, your help is highly appreciated

**Comment by Zeno-sole** [comment]
@babyfengfjx  请确认这个bug，阿拉伯语下的图形布局存在很多问题

**Comment by SuperEffie** [comment]
当系统语言为阿拉伯语时，控制中心存在显示问题（截图如下）：

1. 控制中心主菜单图标显示位置往左偏移；
2. 控制中心各模块导航栏应显示在右侧；
3. 控制中心模块导航栏中显示的省略号位置异常；
4. 账户类型：Administrator显示不全；
5. 自动登录、无密码登录项勾选框应显示在左侧

![لقطة شاشة_dde-control-center_٢٠٢٣٠٢٠٩١٤٢٩٤٧](https://user-images.githubusercontent.com/58986464/217736443-72e2423e-e930-4946-a26a-d792cdcd84fe.jpg)

**Comment by Decodetalkers** [comment]
看起来把dtk软件直接反转了，可能qt软件都反转了下

**Comment by babyfengfjx** [comment]
阿拉伯界面的布局是从右往左的一种布局，看起来与我们的使用习惯正好相反，这中布局性的问题，当前可能不用处理，主要处理一下界面上文字展示不全这类问题即可。

**Comment by 18202781743** [comment]
https://github.com/linuxdeepin/qt5integration/pull/211 修改 ComboBox显示不全的问题，

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240201
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
