### ISSUE TITLE
Deepin v20 beta language packs

### ISSUE THREAD

**Issue by mahtiankka** [linuxdeepin/developer-center#1768]
The Deepin v20 beta has already received six updates. During this time, the language packs have not been updated. This dde-control-center is not the only one. All other programs and icon texts are in the old language packs. It is absolutely essential to get them in v20 beta. Translators also need to be able to test that everything looks and feels good.

I want to say and remind all that language is part of design too.

Thanks!

**Comment by hugok79** [comment]
As the coordinator and translator of the Portuguese(pt) team, I also couldn't help showing my discontent in seeing that the translations are not loaded and updated. 
There is a great effort on the part of translators to make deepin available in other languages.  I hope that the v20 will be released with all translations included.

**Comment by xmuli** [comment]
I've already talked to my supervisor yesterday, hoping to get the attention of the developers; there should be changes later, and if this happens again, everyone can @ me.
