### ISSUE TITLE
[Bug] Deepin Control Centre not running after upgrading Qt to 5.15

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#1775]
## Describe the bug

Deepin Control Centre is not running after upgrading Qt to 5.15

## Expected behavior

The control centre should run.

## Enviroments:
Deepin v20
### Distro & Version

Manjaro(With latest updates)

### Related package version

Deepin Control Centre v5.2.0.6-1

**Comment by felixonmars** [comment]
Can you examine if you still have manjaro-deepin-settings installed? If so please take a look at https://github.com/linuxdeepin/developer-center/issues/1764#issuecomment-643806394

**Comment by SiamSami** [comment]
So, I just moved from Manjaro to Arch and apparently I'm not facing this issue anymore.
