### ISSUE TITLE
Bug - "Connected to internet, but not access" after wake up from suspend mode.

### ISSUE THREAD

**Issue by ulises-castro** [linuxdeepin/developer-center#1778]
## Describe the bug
When I suspend and wake up (usually after 3 times), I don't have internet access, it's appears like i have connect but I don't have access to internet, I tried restarting network manager and Wifi, but I didn't work, Change to another wifi networking and so on.

## To Reproduce

1. Just supend and use computer for a while.
2. Wake up from suspend
3. reproduce 1 and 2 steps again, until get "Connect to internet, but not access"

## Expected behavior
Wake up and have internet access...

### Distro & Version
Deepin V20 Beta

**Comment by xmuli** [comment]
I'll help you with feedback.

**Comment by ulises-castro** [comment]
@xmuli What do you mean?

**Comment by xmuli** [comment]
I will report this issue to the testers, to locate the bug and help the developers fix the

**Comment by ulises-castro** [comment]
@xmuli This is was fixed in the last update, thanks for the report.

Also I reported another bug, I hope you have time to take a look in.

Regards.

**Comment by xmuli** [comment]
You've solved your problem. It feels wonderful.
