### ISSUE TITLE
加入開機啟動清單（autostart）無作用

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#178]
我裝了 SVP4 並從 Launcher 把它加到開機自動啟動的選單內，但是無作用，另外我原本在 ~/.config/autostart/ 內原本可正常自動啟動的 .desktop 檔也失效，但手動點擊是可以用的。

這是我其中一個 .desktop 檔的內容
```
[Desktop Entry]
Comment[zh_TW]=xrandr --output HDMI1 --set "Broadcast RGB" "Full"
Exec=xrandr --output HDMI1 --set "Broadcast RGB" "Full"
Icon=application-default-icon
Name[zh_TW]=FullRangeRGB
Type=Application
```

OS: antergos(arch)

**Comment by jouyouyun** [comment]
Add the line `Terminal=true`, see alse: htop.desktop.
