### ISSUE TITLE
Control panel crash when click icons

### ISSUE THREAD

**Issue by RlZkhere** [linuxdeepin/developer-center#1786]
Hi, i'm using deepin DE on Arch Linux, at the last upgrade when i switch from deepin-control-center-5.2.0.1 to deepin-control-center-5.2.0.3 i had a problem: the program crash when i select the account icon. 
When i downgrade to the older version it works, i think that is a problem of the newest version.

**Comment by xmuli** [comment]
I remember a long time ago that it was fixed. It's always open issues, and many forget about close issues. (I feel sorry for myself)
