### ISSUE TITLE
Missing Kb layouts

### ISSUE THREAD

**Issue by alypo** [linuxdeepin/developer-center#1795]
There is no keyboard layouts for Finnish and Russian in Settings.

Linux Deepin 20
Update 30.06.2020

**Comment by grigoriy-a** [comment]
@alypo you need to add desired system language first in the menu below, then layout languages will be available. I don't know why it was designed this way, but it is. :-P

**Comment by xmuli** [comment]
> @alypo，您需要先在下面的菜单中添加所需的系统语言，然后才能使用布局语言。我不知道为什么要这样设计，但事实如此。:-P

In that case, I'll close it for now.
