### ISSUE TITLE
dde-dock not working properly

### ISSUE THREAD

**Issue by hugeblank** [linuxdeepin/developer-center#180]
Apologies for the vagueness of the title, but that's really the only way I can describe the issue I'm having with dde-dock. This was originally a comment in issue #177 but according to @hualet was unrelated. Here's an excerpt from my comment there:

This is when I use dde-dock without sudo
![image](https://cloud.githubusercontent.com/assets/16393543/23197319/5b080a5e-f8b7-11e6-9d0a-348789382490.png)

Is this a totally different issue, am I doing something wrong? Should I open up a new issue?

It may be useful to see exactly what is on my dock for the following list, so I put a screenshot of that here:
![image](https://cloud.githubusercontent.com/assets/16393543/23197612/704e3db4-f8b9-11e6-8cd6-48dfaf9c51fd.png)

Here are the evident problems I see (other than the error messages above):

-The dock takes a long time to properly load, and update with icons when I open an application.

-Hovering over the applications in the dock sometimes work, and sometimes does not. (partly having to do with the problem after this one, and partly because the dock takes a ridiculously long time to load.)

-The dock when not completely frozen and partly usable will work until I hover over the 'shut down' icon, and only with that icon it will freeze. After a while it will start working again.

-Right clicking on the anything to the right of the shutdown button on the dock is a bad idea. Similar to the shutdown button, it freezes. But after a while it unfreezes and gives this error message:
![image](https://cloud.githubusercontent.com/assets/16393543/23197540/e8f641c2-f8b8-11e6-9aa1-8b0a4ba8c2c6.png)

**Comment by hualet** [comment]
Oops...didn't see your last picture in [the previous issue](https://github.com/linuxdeepin/developer-center/issues/180). Let's see if update of deepin-menu can save your Dock ;)

When will the updates available? @felixonmars

**Comment by felixonmars** [comment]
We have deepin-menu 3.0.10-1 packaged 20 hours ago.

**Comment by hualet** [comment]
@hugeblank have you tried the new version of deepin-menu ?

**Comment by hugeblank** [comment]
@hualet I will tomorrow, currently too late at night for me to want to boot it up (on mobile)

**Comment by funilrys** [comment]
@hugeblank any feedback on this ?

**Comment by hugeblank** [comment]
@funilrys I am pretty sure I had the latest version of deepin-menu when I reported this issue. since February I have opted for just installing Deepin OS. I no longer have this issue with the OS, so I suppose that's a plus haha!

**Comment by hualet** [comment]
@hugeblank It's been here ~2 months now, close this issue for now and I will reopen it if someone else has the same issue again.
