### ISSUE TITLE
PC Freez with Kernel 5.7.7...

### ISSUE THREAD

**Issue by eddyii** [linuxdeepin/developer-center#1800]
## Describe the bug

The PC runs fine since April with Deepin 20beta
Since Kernel 5.7.7 freezing afte 4-6min

### Distro & Version

Deepin 20beta

**Comment by gokhanyildirimlar** [comment]
That's not something that Deepin provided in the operating system. If you customize system parts, you are responsible of your actions. Developers can't do anything if you upgrade some packages arbitrarily. So do you expect them to solve the problems that you created on your own?

**Comment by eddyii** [comment]
Sorry to send to you that information!

**Comment by tsic404** [comment]
this issue will close, please use the latest offical kernel.
