### ISSUE TITLE
Graphical glitch on blender aftar update

### ISSUE THREAD

**Issue by Dziban-dev** [linuxdeepin/developer-center#1803]
## Describe the bug
so i did sudo apt udpate and notice i have a huge amount of packages to update for V20, so i updated deepin through sudo apt full-upgrade, all went great. the only problem is now I get weird artifacts on blender 2.80, 2.81,2.82, 2.83 and 2.90's viewport, on the on solid view (workbench) eevee rendering and cycles rendering works just fine. here is an image that shows the graphical glitch, https://ibb.co/5hHbqHb the viewport renders the materials in a weird way with random squares all over it. i'm assuming it had to do with one of the packages that got updated. I'm using AMD APU A8 7600.
## To Reproduce

1.open blender, 2.8x or 2.9alpha 
2. set the viewport to solid mode
3.enable specular lighting on viewport shading options(on by default i think).

## Expected behavior
no random squares on the surface of objects.

## Screenshots
 https://ibb.co/5hHbqHb 

## Environments:
deepin dde

### Distro & Version
deepin v20 beta

**Comment by tsic404** [comment]
Still have this problem?

**Comment by tsic404** [comment]
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue
