### ISSUE TITLE
Headphones just disconnect itself and reconnect after a few seconds again and again.

### ISSUE THREAD

**Issue by ulises-castro** [linuxdeepin/developer-center#1805]
## Describe the bug

I have my headphones connected to bluetooh and suddenly it just disconnect from bt, and reconnect. This happend after last uptate.

Kernel 5.7.7

**Comment by xmuli** [comment]
Laptops using wifi? and are using Intel-related?

---
Try changing the value 11n_disable=1 to 8, or delete the file and try again(you completely remove `/etc/modprobe.d/iwlwifi.conf`), (remember to back it up beforehand); the reason could be the following:
![image](https://user-images.githubusercontent.com/33887845/86867867-2b618f80-c106-11ea-85d6-0d643f1a696e.png)
![image](https://user-images.githubusercontent.com/33887845/86867880-31f00700-c106-11ea-9b2e-b8ee92ab2b24.png)

Also refer to this? #1682,  Emmm, maybe?

**Comment by ulises-castro** [comment]
it did't work, It used to work...

**Comment by tsic404** [comment]
this still hapen?

**Comment by tsic404** [comment]
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue
