### ISSUE TITLE
Deepin 20 Manjaro wrong Login Screen 

### ISSUE THREAD

**Issue by Y0ngg4n** [linuxdeepin/developer-center#1809]
## Describe the bug
If i disable automatic login and login with Password in Settings and i reboot Manjaro Login Screen Appears and not Deepin Login Screen.

## To Reproduce
1. Goto Settings -> Accounts
2. Disable Automatic Login
3. Disable Login without Password
4. Reboot

## Expected behavior
Deepin 20 Login Screen should appear.

### Distro & Version
Manjaro Kernel 5.7.0-3

### Related package version
```
pacman -Q | grep deepin
deepin-account-faces 1.0.11-1.1
deepin-album 5.6.9.13-2
deepin-anything 5.0.1-2
deepin-anything-dkms 5.0.1-2
deepin-api 5.1.11.1-1
deepin-boot-maker 5.4.8-1
deepin-calculator 5.5.12-2
deepin-calendar 5.6.5-1
deepin-clone 5.0.3-1
deepin-control-center 5.2.0.0-1
deepin-daemon 5.11.0.1-1
deepin-desktop-base 3:2019.07.10-1
deepin-desktop-schemas 5.6.0.1-1
deepin-dock 5.1.0.11-1
deepin-draw 5.8.0.19-2
deepin-editor 5.6.11-1
deepin-file-manager 1:5.1.1.25-3
deepin-gtk-theme 17.10.11-1
deepin-icon-theme 2020.05.29-1
deepin-iconthemes-manjaro 20170918-1
deepin-image-viewer 5.6.3.2-2
deepin-kwin 5.1.0-1
deepin-launcher 5.2.0.0-1
deepin-menu 5.0.1-2
deepin-movie 1:5.7.6.29-1
deepin-music 6.0.1.8-1
deepin-network-utils 5.1.0.0-1
deepin-picker 5.0.6-1
deepin-polkit-agent 5.2.0.1-1
deepin-polkit-agent-ext-gnomekeyring 0.1.0-1
deepin-qt-dbus-factory 5.2.0.0-1
deepin-qt5dxcb-plugin 5.0.11-2
deepin-qt5integration 5.1.0.1-3
deepin-reader 5.6.7-1
deepin-screen-recorder 5.8.0.11-3
deepin-screensaver 5.0.3-1
deepin-screensaver-pp 0.0.4-1
deepin-screenshot 5.0.0-4
deepin-session-shell 5.1.0.1-2
deepin-session-ui 5.2.0.0-1
deepin-shortcut-viewer 5.0.2-1
deepin-sound-theme 15.10.6-1
deepin-system-monitor 5.6.3.1-1
deepin-terminal 5.0.4.1-1
deepin-turbo 0.0.3-1
deepin-wallpapers 2:1.7.7-1
plymouth-theme-manjaro-deepin-circle 1.0-4
```

**Comment by balibebas** [comment]
Didn't Manjaro drop Deepin support last year? I ended up leaving Manjaro for Arch Linux so I could use Deepin. You can still use Pamac but I recommend using Yay instead for managing AUR packages.

**Comment by balibebas** [comment]
Didn't Manjaro drop Deepin support last year? I ended up leaving Manjaro for Arch Linux so I could continueu using Deepin Desktop. You can still use Pamac but I recommend using Yay instead for managing AUR packages. If you need an Arch set-up guide let me know.

**Comment by balibebas** [comment]
Didn't Manjaro drop Deepin support last year? I ended up leaving Manjaro for Arch Linux so I could continueu using Deepin Desktop. You can still use Pamac but I recommend using Yay instead for managing AUR packages.

**Comment by Y0ngg4n** [comment]
@balibebas don´t know but i love deepin desktop and it works fine on manjaro with some small bugs.

**Comment by tsic404** [comment]
Lightdm?

**Comment by tsic404** [comment]
this issue will close, if you stil have problem, you can reopen this issue.
