### ISSUE TITLE
open in terminal 無作用

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#181]
https://youtu.be/fGDakcRQUNs

**Comment by Chathula** [comment]
have you fixed this?

**Comment by Acris** [comment]
Try this:
`sudo ln -s /usr/bin/deepin-terminal /usr/bin/x-terminal-emulator`

**Comment by manateelazycat** [comment]
@felixonmars It's a bug of glib that won't find terminal in system, you should add deepin patch for arch linux .;)

**Comment by funilrys** [comment]
@felixonmars We should create the link in the `PKGBUILD` of `deepin-terminal `

> @Acris : Try this:
sudo ln -s /usr/bin/deepin-terminal /usr/bin/x-terminal-emulator

It's working perfectly if we add it to PKGBUILD :+1: :smile_cat: :smiley:

**Comment by felixonmars** [comment]
Added to deepin-terminal 2.3.1-2. Also added an optional dependency on deepin-file-manager.
