### ISSUE TITLE
深度终端远程管理服务服编辑按钮点击无效

### ISSUE THREAD

**Issue by licardoY** [linuxdeepin/developer-center#1810]
## 缺陷描述
深度终端远程管理服务服编辑按钮点击无效，点击直接链接服务器了而非编辑

## 截图
![截图录屏_deepin-terminal_20200710214820](https://user-images.githubusercontent.com/20562449/87161974-de450f80-c2f7-11ea-9561-8a7c676a4aab.gif)

### 发行版以及版本
deepin 20 beta

### 相关的软件包版本
 终端 5.0.4.1

### 其他内容
系统已更新到最新

**Comment by xmuli** [comment]
请尝试使用新终端， 你这是旧终端
![image](https://user-images.githubusercontent.com/33887845/87247581-38c0a600-c487-11ea-9e5b-e8190750b0cc.png)

**Comment by licardoY** [comment]
> 请尝试使用新终端， 你这是旧终端
> ![image](https://user-images.githubusercontent.com/33887845/87247581-38c0a600-c487-11ea-9e5b-e8190750b0cc.png)

需要自己编译安装? deepin20里没看到这个新终端

**Comment by xmuli** [comment]
The terminal in the source should be replaced by a new terminal with the following style
![image](https://user-images.githubusercontent.com/33887845/87368569-a4526280-c5b0-11ea-81ce-922b989180ca.png)

**Comment by licardoY** [comment]
建议如果是bug还是修复一下,或者推送新终端给用户吧. 太影响使用了.
