### ISSUE TITLE
Missing Feature to create new virtual Desktop

### ISSUE THREAD

**Issue by Y0ngg4n** [linuxdeepin/developer-center#1811]
I miss the feature to create, name and remove Virtual Desktops.

**Comment by xmuli** [comment]
You mean this feature?

![截图录屏_选择区域_20200714091708](https://user-images.githubusercontent.com/33887845/87369443-19269c00-c5b3-11ea-80ef-81d5016f8d03.png)

**Comment by Y0ngg4n** [comment]
Yes this icon is missing in my view.

**Comment by Y0ngg4n** [comment]
This button is missing on multi monitor setup. 

![image](https://user-images.githubusercontent.com/30302975/88202677-85576e80-cc49-11ea-8d71-8e0b8b595425.png)

**Comment by tsic404** [comment]
this problem still exist?

**Comment by Y0ngg4n** [comment]
@tsic404 dont know dont use deepin anymore

**Comment by tsic404** [comment]
Sorry for the bad experience, this issue will close.
