### ISSUE TITLE
Shortcuts not working. Features not implemented yet?

### ISSUE THREAD

**Issue by Y0ngg4n** [linuxdeepin/developer-center#1812]
There are some confusing Shortcuts in Settings.
Are these Features that are not implemented yet?
When will they come?
I did not found any Documentation about them

![Screen Capture_select-area_20200710184122](https://user-images.githubusercontent.com/30302975/87178300-36224d00-c2dd-11ea-87c1-2602477fbdbf.png)

**Comment by xmuli** [comment]
My guess is that some of the "voice" features have been turned off or removed, but the shortcuts have not been removed.

**Comment by Y0ngg4n** [comment]
How can i get those functions in my Settings? I find them usefull.

**Comment by xmuli** [comment]
This is a feature of the personal and professional editions of uos (not available in the community edition of deepin)

**Comment by Y0ngg4n** [comment]
ah ok thank you.

**Comment by xmuli** [comment]
However, Ai may be integrated into the community version at a later date.

[https://www.bilibili.com/video/BV1FC4y1h729](https://www.bilibili.com/video/BV1FC4y1h729)

![image](https://user-images.githubusercontent.com/33887845/87696882-0800a980-c7c4-11ea-99d2-964b299b1289.png)

**Comment by Y0ngg4n** [comment]
@xmuli ok thank you.
