### ISSUE TITLE
CPU load excessive and very poor performance when copying files from HDD in Deepin 20 beta

### ISSUE THREAD

**Issue by igatjens** [linuxdeepin/developer-center#1813]
## Describe the bug

I copied 46GB of files from my SSD to my HDD (mechanical disk) using the rsync command and the processor load is triggered.

The same thing happens when I copy with the cp command or when I copy files with Deepin File Manager to my HDD.

I have observed an excessive processor load when using the HDD, it also happens during the system startup, just started the system, the CPU load is high.

My CPU is a 4-core AMD FX-4100, a full load is 4, and the CPU load has reached 10.

## To Reproduce

Copying several GB of files to the HDD, with 4GB is enough to see how the CPU load shoots up.

You can use the command cp or rsync or Deepin File Manager to make the copy of the files.

You can monitor the CPU load with the uptime, top or htop command. I usually monitor the performance of the computer with conky.

## Expected behavior

While the CPU load is greater than 4, the performance of the system is very bad, the pointer still responds normally, but opening an application takes minutes, taking screenshots takes about 20 to 30 seconds to do. It takes several seconds to resize or move windows to respond.

## Screenshots

I include captures with conky, htop, neofech and uptime information.

Here is one of the times during the copying process when one of the highest CPU load values was reached.

It is observed that the hard disk is sucking a lot and that the CPU load is very high, but the CPU usage is not at its maximum and it goes up and down constantly (light blue graphic). There is also not much use of RAM (green graph).

Even the processor temperature is not high, but the system performance is very very bad, it is almost hung up, almost unresponsive.

![Captura de pantalla_20200710223757](https://user-images.githubusercontent.com/66392244/87217213-15212280-c304-11ea-9057-aea941bce445.png)

![Captura de pantalla_20200710224109](https://user-images.githubusercontent.com/66392244/87217253-692c0700-c304-11ea-9e57-1c176185be9c.png)

The following screenshot is shortly after finishing copying the files as you can see in the READ disk graph, the purple one.

![Captura de pantalla_20200710224801](https://user-images.githubusercontent.com/66392244/87217267-8fea3d80-c304-11ea-97ad-ead03e7457be.png)

This capture is a few minutes later when the CPU load returns to normal.

![Captura de pantalla_20200710225416](https://user-images.githubusercontent.com/66392244/87217291-c627bd00-c304-11ea-8f19-59208905efb2.png)

## Enviroments:
CPU: AMD FX-4100
RAM: 8GB
GPU: Nvidia GTX 650

[hardware.zip](https://github.com/linuxdeepin/developer-center/files/4906351/hardware.zip)

### Distro & Version

Deepin 20 beta full update

### Related package version

rsync  version 3.1.3  protocol version 31

cp (GNU coreutils) 8.30

dde-file-manager 5.1.0.28

Linux titan 5.3.0-3-amd64 #1 SMP deepin 5.3.15-6apricot (2020-04-13) x86_64 GNU/Linux

### Additional context

I currently have Deepin 20 beta installed on the HDD and I have Deepin 15 on the SSD. I'm going to test how Deepin 20 beta works on the SSD and check if it has the same problem when installed on the SSD.

Some Deepin users comment that this problem was already occurring on Deepin 15, but with Deepin 15 installed on an SSD I have not noticed that problem.

**Comment by dcruz1990** [comment]
Having the same behaviour here, i have an HDD , tried to copy a 1.2 GB ISO and system freeze.

**Comment by babyfengfjx** [comment]
Sorry for taking so long time to respond. We also found that the system was stuck during the copying process. In the latest version, the problem of high CPU usage is no longer there. We will submit an optimization request for this problem. Thanks for your feedback.

**Comment by babyfengfjx** [comment]
I apologize for the prolonged lack of optimization for this issue. Currently, there will be no major updates for deepin V20. The development and optimization of new features will be carried out in the upcoming V23 version. For this issue, we will close it for now. If you encounter any problems while using the V23 version, please don't hesitate to provide feedback. We will also track this performance issue as part of the V23 iteration. Thank you once again for your feedback~
