### ISSUE TITLE
[20 BETA] VirtualBox breaks the system

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#1818]
## Describe the bug
The installation of VirtualBox (.deb - Debian 10 - provided by the official website) goes smoothly. Upon restarting the system, it is unable to start and displays an error message (image).

Since I couldn't solve it, I just had to format the laptop. It is the 2nd time that I have problems with VirtualBox (from the site) with the deepin 20 BETA.

When using the command (below) to install VirtualBox, the Okular application ("org.kde.okular", not the "okular" package) is installed as a dependency:

> sudo apt install ./virtualbox.deb

During installation, an error appears in the kernel (I'm not sure).

## Screenshots
![IMG_20200710_145629](https://user-images.githubusercontent.com/45263160/87237164-326bf480-c3c9-11ea-81ea-9f013833dc70.jpg)

### Distro & Version
deepin 20 BETA

### Related package version
virtualbox 6.1 (provided by the website)

### Additional context
I didn't test the repository's virtualbox, because I thought it was out of date.

**Comment by igatjens** [comment]
The virtualbox.org installer for Debian 10 expects a 4.19 kernel, but Deepin 20 beta has a 5.3 kernel and so the virtualbox.org installer breaks the system.

Install VirtualBox from the Deepin repository

`sudo apt install virtualbox-6.1`

I use it and it works very well.

**Comment by alexwender1** [comment]
I believe there is a relationship with the extra dependencies that are created. In this topic (https://github.com/linuxdeepin/developer-center/issues/1900), this problem has been fixed with the repository package; but with the .deb version (https://www.virtualbox.org) the problem still persists and can damage the system.

You can work around the problem if the user uses the following command when installing:

> sudo apt install ./virtualbox.deb **--no-install-recommends**

If any adjustments can be made it is better; in any case, we must guide users to use only the repository's VirtualBox.

![Captura de Tela_deepin-terminal_20201229103826](https://user-images.githubusercontent.com/45263160/103287721-061d5200-49c2-11eb-86f7-1e23ed627e16.png)
