### ISSUE TITLE
Copy Paste Delete Window not correctly showing

### ISSUE THREAD

**Issue by Y0ngg4n** [linuxdeepin/developer-center#1819]
## Describe the bug
If you copy or paste something or delete something in deepin file manager it is looking like this:

![Screen Capture_dde-file-manager_20200712150316](https://user-images.githubusercontent.com/30302975/87246953-0d22c900-c451-11ea-94db-817d46520b8a.png)

## To Reproduce
1. Copy Paste something in Deepin File Manager or delete something

## Expected behavior
A window which shows me the stats of my action

## Screenshots
![Screen Capture_dde-file-manager_20200712150316](https://user-images.githubusercontent.com/30302975/87246953-0d22c900-c451-11ea-94db-817d46520b8a.png)

### Distro & Version
Manjaro 5.7

### Related package version
```
pacman -Q | grep deepin
deepin-account-faces 1.0.11-1.1
deepin-album 5.6.9.13-2
deepin-anything 5.0.1-2
deepin-anything-dkms 5.0.1-2
deepin-api 5.1.11.1-1
deepin-boot-maker 5.4.8-1
deepin-calculator 5.5.12-2
deepin-calendar 5.6.5-1
deepin-clone 5.0.3-1
deepin-control-center 5.2.0.0-1
deepin-daemon 5.11.0.1-1
deepin-desktop-base 3:2019.07.10-1
deepin-desktop-schemas 5.6.0.1-1
deepin-dock 5.1.0.11-1
deepin-draw 5.8.0.19-2
deepin-editor 5.6.11-1
deepin-file-manager 1:5.1.1.25-3
deepin-gtk-theme 17.10.11-1
deepin-icon-theme 2020.05.29-1
deepin-iconthemes-manjaro 20170918-1
deepin-image-viewer 5.6.3.2-2
deepin-kwin 5.1.0-1
deepin-launcher 5.2.0.0-1
deepin-menu 5.0.1-2
deepin-movie 1:5.7.6.29-1
deepin-music 6.0.1.8-1
deepin-network-utils 5.1.0.0-1
deepin-picker 5.0.6-1
deepin-polkit-agent 5.2.0.1-1
deepin-polkit-agent-ext-gnomekeyring 0.1.0-1
deepin-qt-dbus-factory 5.2.0.0-1
deepin-qt5dxcb-plugin 5.0.11-2
deepin-qt5integration 5.1.0.1-3
deepin-reader 5.6.7-1
deepin-screen-recorder 5.8.0.11-3
deepin-screensaver 5.0.3-1
deepin-screensaver-pp 0.0.4-1
deepin-screenshot 5.0.0-4
deepin-session-shell 5.1.0.1-2
deepin-session-ui 5.2.0.0-1
deepin-shortcut-viewer 5.0.2-1
deepin-sound-theme 15.10.6-1
deepin-system-monitor 5.6.3.1-1
deepin-terminal 5.0.4.1-1
deepin-turbo 0.0.3-1
deepin-wallpapers 2:1.7.7-1
plymouth-theme-manjaro-deepin-circle 1.0-4
```

**Comment by balibebas** [comment]
I had this same problem. Resolved by deleting `~/.config/kwinrc` and rebooting as mentioned here: https://forum.manjaro.org/t/various-deepin-desktop-and-kwin-related-issues-window-effects-wallpapers-etc/152061/4

**Comment by balibebas** [comment]
I had this same problem. Resolved by deleting `~/.config/kwinrc` and rebooting as mentioned here: https://forum.manjaro.org/t/various-deepin-desktop-and-kwin-related-issues-window-effects-wallpapers-etc/152061/6

**Comment by Y0ngg4n** [comment]
@balibebas if i remove my `~/.config/kwinrc` i have the Problem that `OpenGLisUnsafe=true` is always set to true like mentioned in this issue: #1797

**Comment by Y0ngg4n** [comment]
Any Updates here?

**Comment by bear-bulloff** [comment]
I have this same problem. This deleting the file kwinrc didn't solve the problem.
![DeepinScreenshot_dde-desktop_20201011225054](https://user-images.githubusercontent.com/59369672/95689010-b6c35300-0c16-11eb-88dd-1e3212d7019f.png)

**Comment by tsic404** [comment]
still have this problem?

**Comment by tsic404** [comment]
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue
