### ISSUE TITLE
關鍵字搜尋找到不相關的 APP

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#182]
以這兩張圖為例，前兩個 APP 和關鍵字基本上沒什麼關係，但卻被排在最前面

![deepinscreenshot20170222204844](https://cloud.githubusercontent.com/assets/20014762/23212210/a59713f6-f940-11e6-8ed8-0128d725dae6.png)
![deepinscreenshot20170222204934](https://cloud.githubusercontent.com/assets/20014762/23212212/a5d6084a-f940-11e6-81d8-2da5b3044923.png)

**Comment by hualet** [comment]
@electricface

**Comment by justforlxz** [comment]
This question has not been answered for too long and will be closed. If there is a need to continue the discussion, it will be reopened.
