### ISSUE TITLE
[20 BETA] Adjustments to the light/dark theme

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#1820]
### Indicators
The indicators (Volume / Brightness / Caps Lock) are not integrated into the system themes.

For example, when the system tray icons are displayed in white color; these indicators must adopt the same color. And  vice versa.

### Dock
When using the dock with maximum transparency (on any theme), the tray icons are invisible, depending on what is displayed behind the dock.

When I use the browser and need to see some information on the tray; I need to minimize the browser, as the system tray icons are invisible.

### Indicators Screenshots
![Screen Capture_select-area_20200712104701](https://user-images.githubusercontent.com/45263160/87248985-d5a52400-c432-11ea-977a-9e3f5a9fd822.png)

![Screen Capture_select-area_20200712104614](https://user-images.githubusercontent.com/45263160/87248966-b0181a80-c432-11ea-95b3-234b91867d6f.png)

![Screen Capture_select-area_20200712105146](https://user-images.githubusercontent.com/45263160/87248988-ddfd5f00-c432-11ea-9985-e12689de9acc.png)

### Dock Screenshots
![Screen Capture_select-area_20200712110534](https://user-images.githubusercontent.com/45263160/87249142-bd81d480-c433-11ea-8587-7bf94684e06d.png)

![Screen Capture_select-area_20200712110405](https://user-images.githubusercontent.com/45263160/87249147-c07cc500-c433-11ea-9abf-ccd3cfd6b7c5.png)

### Distro & Version
deepin 20 BETA

### Additional context
I use the dock in smart hide mode and in the smallest size.

**Comment by alexwender1** [comment]
@xmuli https://github.com/linuxdeepin/developer-center/issues/1729

**Comment by xmuli** [comment]
Thank you, can be used as a supplement to such problems

**Comment by xmuli** [comment]
![image](https://user-images.githubusercontent.com/33887845/101325427-b4901480-38a6-11eb-8246-d04fac475d1e.png)
![image](https://user-images.githubusercontent.com/33887845/101325467-c70a4e00-38a6-11eb-9882-15b9cd702afc.png)
**Seems to have been solved**

**Comment by zccrs** [comment]
Hi @lxwndr ，I am see the Dock is resolved, do you have other problems?
