### ISSUE TITLE
外接显示器使用问题反馈

### ISSUE THREAD

**Issue by licardoY** [linuxdeepin/developer-center#1826]
## 缺陷描述
一台14寸1080分辨率的笔记本外接24寸4k显示器，设置只外接屏幕显示，目前发现以下几个问题
1 笔记本开机后直到在笔记本上输入完密码外接屏幕才会接管显示
2 不能为每一个屏幕单独设置缩放，造成拔掉外接显示器后笔记本屏幕显示很大，或者从笔记本接上外接屏幕时显示很小，每一次切换都要去控制中心重新设置缩放。

## 期望行为
能为每一个屏幕单独设置缩放比例

设置了仅外接屏幕显示后，笔记本开机能直接在外接屏幕显示画面而不必等到输入完密码登录之后

### 发行版以及版本

deepin20 beta

**Comment by zmj1010** [comment]
1、If your phenomenon is not reproduced, the secondary screen of the login lock screen will also blur the wallpaper
2、The function is so, it is not currently supported to set the screen zoom separately
