### ISSUE TITLE
deepin-appstore

### ISSUE THREAD

**Issue by liushuncheng** [linuxdeepin/developer-center#1828]
## 缺陷描述
can not install deepin-appstore
## 复现步骤
lsc@lsc:~$ sudo apt install -y deepin-appstore
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
有一些软件包无法被安装。如果您用的是 unstable 发行版，这也许是
因为系统无法达到您要求的状态造成的。该版本中可能会有一些您需要的软件
包尚未被创建或是它们已被从新到(Incoming)目录移出。
下列信息可能会对解决问题有所帮助：

下列软件包有未满足的依赖关系：
 libgtk2-perl : 依赖: perlapi-5.26.0
                依赖: libpango-perl 但是它将不会被安装
 libqcef1 : 依赖: qtbase-abi-5-10-0
 libqt5qml5 : 依赖: qtbase-abi-5-10-0
              推荐: libgl1-mesa-glx 但是它将不会被安装
 libqt5sql5 : 依赖: qtbase-abi-5-10-0
 libqt5sql5-sqlite : 依赖: qtbase-abi-5-10-0
 libqt5webchannel5 : 依赖: qtbase-abi-5-10-0
E: 无法修正错误，因为您要求某些软件包保持现状，就是它们破坏了软件包间的依赖关系。

## 期望行为
can install deepin-appstore
## 复现环境:

debootstrap deepin unstable
### 发行版以及版本

Linux Deepin v20

### 相关的软件包版本

deepin-appstore
libgtk2-perl : 依赖: perlapi-5.26.0
                依赖: libpango-perl 但是它将不会被安装
 libqcef1 : 依赖: qtbase-abi-5-10-0
 libqt5qml5 : 依赖: qtbase-abi-5-10-0
              推荐: libgl1-mesa-glx 但是它将不会被安装
 libqt5sql5 : 依赖: qtbase-abi-5-10-0
 libqt5sql5-sqlite : 依赖: qtbase-abi-5-10-0
 libqt5webchannel5 : 依赖: qtbase-abi-5-10-0

**Comment by xmuli** [comment]
商店是自带就有的啊，以及你的源是否正确？
