### ISSUE TITLE
希望deepin或者统信软件和亚马逊合作开发kindle阅读软件 for linux 

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1833]
## 缺陷描述

kindle for pc不支持linux，感觉很不爽，wine的有bug，一些书code不能显示，很恼火
kindle for pc是qt写的，移植到linux应该不难
希望deepin或者统信软件和亚马逊合作开发kindle阅读软件for linux
主要让我不爽的wine kindle for pc bug是这一个：
https://bugs.winehq.org/show_bug.cgi?id=45319
感觉还是原生的软件好啊

## 期望行为

kindle for pc支持linux

### 发行版以及版本

deepin15.11

**Comment by xmuli** [comment]
这个可以在[deepin论坛](https://bbs.deepin.org/)里面表明用户意向。收集希望适配的软件，那里面对此讨论更多

**Comment by widon1104** [comment]
我已经在论坛发过类似的帖子，效果很不好，在这里发，是希望官方人士看到

**Comment by xmuli** [comment]
论坛里面，有官方管理员专门收集此类的用户反馈的；后面适配会优先考虑用户实际所需要的建议的软件的

**Comment by xmuli** [comment]
已经看到了 [https://bbs.deepin.org/result?keyword=kindle&search_type=1](https://bbs.deepin.org/result?keyword=kindle&search_type=1)； github 重复，关闭。
