### ISSUE TITLE
[20 BETA] The deepin installer does not allow you to enter passwords with special characters

### ISSUE THREAD

**Issue by wuniversales** [linuxdeepin/developer-center#1837]
## Describe the bug
The deepin installer does not allow you to enter passwords with special characters, I try to enter for example a hyphen "-" in the password and it is impossible for me to use that password.

## To Reproduce
Follow the steps of the deepin installer until you reach the option to enter the password.

## Expected behavior
You should let passwords with special characters be created, for everyone's safety.

### Distro & Version
Linux Deepin 20 Beta (Installer)

**Comment by wuniversales** [comment]
It seems that "-" does not work either in the option to change password in the control center.

It just seems that the character "-" is not supported by deepin in passwords.

**Comment by xmuli** [comment]
Yes, certain characters are allowed to set the password, this is the original design, not a bug
