### ISSUE TITLE
无法在uefi模式装系统，机型lenovo legion y7000 (deepin-installer)

### ISSUE THREAD

**Issue by foresee-io** [linuxdeepin/developer-center#1841]
## 缺陷描述

[相关帖子 https://bbs.deepin.org/forum.php?mod=viewthread&tid=198161&extra=](https://bbs.deepin.org/forum.php?mod=viewthread&tid=198161&extra=)
我的电脑为Lenovo Legion Y7000 2019 PG0，
**系统只预留了256MB的esp**，但我在此时无法装系统。

最终我只好用legacy模式装系统，然后再在live系统手动安装efi版grub。

## 复现步骤

1. 下载Deepin 20 Beta安装盘，刻录进U盘中；
2. 以efi模式进入安装器；
3. 指定/和/home位置（**esp已被系统识别，无需手动指定**）
4. 报错，说我未指定esp

## 期望行为

降低对esp的要求，确保即使OEM预留的esp没有300MB，也能使系统正确安装。
**ubuntu等系统均不强制设定这么大的esp**

## 复现环境
Lenovo Legion Y7000 PG0
Pure UEFI
厂商预留256MB的esp

## 发行版以及版本
Deepin 20 Beta

### 相关的软件包版本
deepin-installer

**Comment by ProfileFZY** [comment]
很多电脑出厂没有那么大的esp(efi分区)，乱调esp极可能破坏预装系统。还请考虑下调或取消对esp的限制

**Comment by chaim1221** [comment]
I cannot read this very well but may be having the same issue on a Lenovo Yoga 720. I can't get the installer past the GRUB bootloader.

I cannot enable Legacy UEFI mode on this BIOS. Secure Boot and Fast Boot are disabled, however.

(May also be related to the AMD graphics issue, I'll comment there as well.)

**Comment by ProfileFZY** [comment]
It still remains unsolved after the official release of `deepin-desktop-community-1002-amd64`. Here are the details in Legion Y7000 2019 PG0 in pure `UEFI` mode.
![Screen Capture_select-area_20200919204813](https://user-images.githubusercontent.com/32860378/93667768-f0db8200-faba-11ea-9edc-e6a4a9f0da10.png)
![Screen Capture_deepin-installer_20200919204742](https://user-images.githubusercontent.com/32860378/93667772-f5079f80-faba-11ea-9640-49df79ccd26d.png)
![Screen Capture_select-area_20200919204752](https://user-images.githubusercontent.com/32860378/93667776-f8029000-faba-11ea-9d70-aab92b6277b3.png)

**Comment by ProfileFZY** [comment]
> I cannot read this very well but may be having the same issue on a Lenovo Yoga 720. I can't get the installer past the GRUB bootloader.
> 
> I cannot enable Legacy UEFI mode on this BIOS. Secure Boot and Fast Boot are disabled, however.
> 
> (May also be related to the AMD graphics issue, I'll comment there as well.)

Actually I'm facing a difficult problem (see above). 
Maybe Deepin 20 Installer is not compatible with **Ventoy** (https://www.ventoy.net/en/index.html), 
or Installer's **requirement of ≥300MB EFI partition** is quite hard to meet for many PCs with Windows pre-installed.

**Comment by foresee-io** [comment]
现在 deepin 20.3 终于允许 64MB 的 EFI 分区了，希望 deepin 再接再厉。
