### ISSUE TITLE
dde-kwin窗口效果在DDE不正常, 但在Xfce等正常 (dde-kwin, dde-dock 等)

### ISSUE THREAD

**Issue by foresee-io** [linuxdeepin/developer-center#1842]
## 缺陷描述

dde-kwin由kwin修改而来，兼容kwin效果。
其自带的“魔灯”效果在dde不能正确识别dock的位置，但

**在xfce4下居然正常**。
说明这大概率是DDE其他组件的问题。

## 复现步骤

1. 安装并打开systemsettings (KDE 系统设置)
2. 进入“桌面行为-桌面特效”
3. 勾选“魔灯”效果并Apply
4. 将dde任务栏的位置设为“上”
5. 缩小任意窗口
_“魔灯”误认为dock位置在下方，动画不正确_

## 期望行为

kwin“魔灯”效果正确识别任务栏位置，做出正确动画。

**再次强调**，在xfce混搭kwin --replace，“魔灯”效果可以正确识别panel位置，
说明问题大概率出在dde窗管以外的组件上。

## 截图

**动态图片，可能需先点击才能正常显示**
在dde下的表现（异常）
![截图录屏_dde-desktop_20200806101611](https://user-images.githubusercontent.com/32860378/89484447-1a717000-d7d1-11ea-91b4-43af21e56159.gif)
在xfce下的表现（正常）
![2zn7z-wrvft](https://user-images.githubusercontent.com/32860378/89484616-71774500-d7d1-11ea-870b-d4ceb3a16288.gif)

### 发行版以及版本
Deepin 20 beta，已于2020-8-6保持最新

### 相关的软件包版本

dde-kwin/未知,now 5.0.13+c1-1 amd64 [已安装]
dde-dock/未知,now 5.0.27+c3-1 amd64 [已安装]
dde-desktop/未知,now 5.1.0.28-1 amd64 [已安装]
dde-launcher/未知,now 5.0.16+c1-1 amd64 [已安装]

下列组件可用于复现kwin在dde、xfce下的表现
systemsettings/未知,stable,now 4:5.14.5-1.1 amd64 [已安装]
xfce4/未知,未知,stable,stable,now 4.12.5 all [已安装]

**Comment by justforlxz** [comment]
@xmuli 给dock和窗管的开发报告一下，推测可能是dock位置切换以后，没有给窗管更新位置信息，导致kwin用的还是旧的信息。

**Comment by ProfileFZY** [comment]
It still remains unsolved in Deepin 20 1002, even though DDE's personalization settings officially supports "Magic Lamp" effect.

**Comment by foresee-io** [comment]
本问题已亲测解决，现关闭此issue。感谢！

**Comment by xmuli** [comment]
nice, thanks (sometimes forget to close the issues they raise, even if they have been resolved)
