### ISSUE TITLE
Battery tray icon deepin v20 (last update)

### ISSUE THREAD

**Issue by app4deepin** [linuxdeepin/developer-center#1844]
I have updated deepin v20 beta to the latest version.

Since then, the battery icon in the tray has worked weird. from time to time the icon is normal and from time to time the icon is different (see screenshot)

I try to:

- change the icon theme
- clear caches
- reinstall the system

Nothing helps, there is a bug with the battery tray indicator.

![Screen Capture_select-area_20200808112524](https://user-images.githubusercontent.com/64970977/89706976-abc81a00-d96a-11ea-81c6-e57877e8bdd0.png)

**Comment by xmuli** [comment]
Please update the icon library `deepin-icon-theme` and try again

**Comment by alexwender1** [comment]
I also confirm the problem!

Other users in the Brazilian community also report the same problem.

**Comment by xmuli** [comment]
Already under repair

**Comment by xmuli** [comment]
＃1729
