### ISSUE TITLE
dtk应用的控件、图标显示不正常，即使已切至缺省主题 (libdtk-*)

### ISSUE THREAD

**Issue by foresee-io** [linuxdeepin/developer-center#1845]
## 缺陷描述
deepin使用dtk以便统一应用的样式。但存有缺陷：

若不搭配使用dde，dtk应用的控件、图标将有异常，即使切至deepin提供的主题、图标。
这对dtk应用的移植推广将可能有不利影响。
相关帖子：[https://bbs.deepin.org/forum.php?mod=viewthread&tid=198665](https://bbs.deepin.org/forum.php?mod=viewthread&tid=198665)

下面将举具体例子。

## 复现步骤

导航：1-4为准备工作，5-6为观察环节。

1. 从官方源运行`sudo apt install xfce4 com.iflytek.iflyime`
2. 注销并切换至`xfce`会话
3. 在`xfce4-settings-manager`中，
调整“窗口管理器”“外观-样式”为`deepin`，
“外观-图标”为`bloom`
4. 注销，重新登录至`xfce`会话

5. 运行自带“截图录屏”app，观察控件的外观
6. 切至“UOS输入法”，进入“属性设置”，观察控件的外观

## 期望行为

改善dtk设计，使其在其他桌面环境拥有同在dde中一致的美观。

## 截图

依次为“截图录屏”“UOS输入法-属性设置”的界面，
可见图标缺失、控件不美观等现象。
![IMG_20200808_215542~01](https://user-images.githubusercontent.com/32860378/89712780-b368dc80-d9c5-11ea-9324-8f02e021b61e.jpg)
![截图录屏_20200808215723](https://user-images.githubusercontent.com/32860378/89712766-93391d80-d9c5-11ea-8246-aef9845642a0.png)

### 发行版以及版本

deepin 20 社区版，在2020-8-8最新

### 相关的软件包版本

![截图录屏_选择区域_20200808222147](https://user-images.githubusercontent.com/32860378/89712809-dd220380-d9c5-11ea-8733-2d04d7697880.png)

下列包可用于复现问题
deepin-screen-recorder, 5.8.0.11-1
xfce4, 4.12.5
com.iflytek.iflyime, 1.0.0

**Comment by ProfileFZY** [comment]
Additional information:
DTK widgets will **display properly using `sudo`**, even if I'm NOT using DDE. For example,

1. Open a Xfce Session. (`/usr/share/xsessions/xfce.desktop`)
2. Open a Terminal.
3. Run `sudo -i dde-file-manager`.

You'll see that everything in the new window is applied with the correct DTK style.
