### ISSUE TITLE
[Feature Request] add support for copy the absolute full path of file in dde-file-manager

### ISSUE THREAD

**Issue by shengdexiang** [linuxdeepin/developer-center#1852]
In dde-file-manager, when right click a file, a menu pop up. There is no option to copy the absolute full path of the file(including the file name). Please add a shutcut or option on the popup menu.

P.S. my OS version:
```
OS: Deepin 20
Kernel: x86_64 Linux 5.3.0-3-amd64
Uptime: 2h 56m
Packages: 2982
Shell: bash
Resolution: 2720x1024
DE: Deepin 20
WM: KWin
GTK Theme: deepin-dark [GTK2/3]
Icon Theme: bloom
CPU: Intel Core i7-6700 @ 8x 4GHz [27.8°C]
GPU: Mesa DRI Intel(R) HD Graphics 530 (Skylake GT2) 
RAM: 5032MiB / 15966MiB
```
...and the dde-file-manager version is `5.1.1.92`.

Best regards.

**Comment by xmuli** [comment]
Thanks for your suggestion, products will consider this suggestion

**Comment by alexwender1** [comment]
This shortcut already exists! It's Ctrl + C... After pasting into the Text Editor, the full path will appear.

![Screen Capture_dde-file-manager_20200815230609](https://user-images.githubusercontent.com/45263160/90324976-fd187080-df4b-11ea-924c-8615ed99ef5e.png)
![Screen Capture_deepin-editor_20200815230635](https://user-images.githubusercontent.com/45263160/90324977-ff7aca80-df4b-11ea-8348-5a1337da83f2.png)

**Comment by shengdexiang** [comment]
> This shortcut already exists! It's Ctrl + C... After pasting into the Text Editor, the full path will appear.
> 
> ![Screen Capture_dde-file-manager_20200815230609](https://user-images.githubusercontent.com/45263160/90324976-fd187080-df4b-11ea-924c-8615ed99ef5e.png)
> ![Screen Capture_deepin-editor_20200815230635](https://user-images.githubusercontent.com/45263160/90324977-ff7aca80-df4b-11ea-8348-5a1337da83f2.png)

Got. Thanks.

**Comment by xmuli** [comment]
This is another supplement
![image](https://user-images.githubusercontent.com/33887845/90350688-7f01ba00-e070-11ea-9ea8-977c5543fd0e.png)
