### ISSUE TITLE
deepin V20图标模式下点中文件也无法看文件名全名

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1855]
## 缺陷描述

有些文件名比较长，我想看文件名全名看不了，图标模式下点中也看不了
![截图录屏_选择区域_20200814202211](https://user-images.githubusercontent.com/12093211/90248756-dc78e980-de6b-11ea-94fb-d70556034e01.png)
上面这张图，谁知道20.04后面是什么内容？
我觉得deepin V20作为社区版本也要注重细节

### 发行版以及版本

deepin V20

**Comment by xmuli** [comment]
图标模式下，文件名过长，都是默认缩略的。要观看在图标模式下可看，或者点击重名名可看。
例如 win, 以前是有文件名称 256 字节长度限制的。全部展开， 能现象一下你的桌面的样子应该会变得很糟糕？

**Comment by widon1104** [comment]
我觉得可以分文件名长度解决这个问题
1）文件名长度不超过100个字节，点中就直接展开显示（这可以覆盖绝大多数场景）
2）文件名特长的提示用户按空格弹窗显示全名，这个功能现在应该已经有了

**Comment by xmuli** [comment]
> 2）文件名特长的提示用户按空格弹窗显示全名，这个功能现在应该已经有了

依据惯例，按空格一般都是预览功能
