### ISSUE TITLE
设置中心的网络详情下拉滚动条遮挡文字

### ISSUE THREAD

**Issue by licardoY** [linuxdeepin/developer-center#1857]
## 缺陷描述

设置中心的网络详情下拉滚动条遮挡文字
## 复现步骤

1. 打开 设置
2. 点击 网络
3. 点击 网络详情，可以发现右侧下拉滚动条遮挡了文字
![001](https://user-images.githubusercontent.com/20562449/90308883-e0614600-df15-11ea-9014-62f3e6dbb189.png)
4.点击键盘和语言
5.点击快捷键 ，右侧滚动条也遮挡了文字部分

对比蓝牙这里的滚动条是没有遮挡文字的
![002](https://user-images.githubusercontent.com/20562449/90308898-00910500-df16-11ea-97ca-1c811810bfac.png)

## 期望行为

网络详情和快捷键的滚动条能和蓝牙这里一样不遮挡文字部分
## 复现环境:

24寸4k分辨率 2倍缩放
### 发行版以及版本
deepin20（更新到最新）

**Comment by xmuli** [comment]
感谢你的反馈，滚动条有的地方遮住文字，有些是属于设计如此（滚动条会智能隐藏）。然后有的出现是在外面的，是早期实现的方案不统一，目前设计师和 DTK 和应用的团队，正在逐渐统一中标准中，，，
