### ISSUE TITLE
[20 RC][Feature Request] Adjust the refresh rate to reduce power consumption on a laptop

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#1859]
## Describe the bug
Deepin has never had a good energy efficiency in laptops.

By following some reports from GNOME developers; they say that reducing the refresh rate makes the system / interface more "battery friendly".

On my hardware, deepin offers the minimum update rate at 48Hz (maximum / default at 60Hz).

The content displayed on platforms such as Netflix, YouTube and Cable or Open TV has a rate of 24 FPS to 60 FPS. For this reason, I suggest that deepin offer the **minimum refresh rate at 24Hz**.

## Screenshots
![Screen Capture_select-area_20200816110602](https://user-images.githubusercontent.com/45263160/90336663-ae062600-dfb3-11ea-8909-c6435481d0b3.png)

### Distro & Version
deepin 20 RC (or 20 (1000))

### Additional context
The Samsung Galaxy Note 20 Ultra and Apple iPad Pro will offer a variable refresh rate. I don't know if this is directly related to hardware (it's probably software). At some point, DDE may offer a variable refresh rate on laptops, depending on the user's needs.

**Comment by justforlxz** [comment]
Hi, The refresh rate is provided by X11. We did not force the creation of a new refresh rate. The list is the refresh rate supported by the obtained screen. We need relevant developers to evaluate this behavior. Thanks！

**Comment by xmuli** [comment]
Someone will confirm this issue later; in addition, I personally suggest that you still use a 60+ Hz screen, which will be more comfortable for the eyes. You should not force yourself to use or experience (all) for the sake of "scientific" parameters or the best performance. Please focus on your own comfort); no matter how you use a notebook, it is only a tool, and the user’s health is more of concern

**Comment by alexwender1** [comment]
Aiming to ensure the health of users; I'm closing this issue.
