### ISSUE TITLE
請問設定完 PPPoE 後要怎麼連線？

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#186]
找不到有連線的選項
![deepinscreenshot20170301154135](https://cloud.githubusercontent.com/assets/20014762/23450359/ad36f8d8-fe95-11e6-9f04-d49e8c1c0fa6.png)

**Comment by felixonmars** [comment]
点击底下的“储存”？

**Comment by justforlxz** [comment]
This question has not been answered for too long and will be closed. If there is a need to continue the discussion, it will be reopened.
