### ISSUE TITLE
UOS专业版1021 sudo apt-key add 失败

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1860]
## 缺陷描述

我已经打开了开发者模式，我觉得在这种模式下面用户应该有任何自由
我现在想安装wine5.15，add key的时候失败了，导致我无法安装

widon@widon-UOS:/tmp$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 76F1A20FF987672F
Executing: /tmp/apt-key-gpghome.C26zYMHz76/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 76F1A20FF987672F
gpg: 密钥 76F1A20FF987672F：公钥 “WineHQ packages <wine-devel@winehq.org>” 已导入
gpg: 处理的总数：1
gpg:               已导入：1
gpg: invalid key resource URL '/etc/apt/trusted.gpg.d/home:smplayerdev.gpg'
gpg: 密钥区块资源‘(null)’：一般错误
gpg: key 7721F63BD38B4796: 2 个签名因密钥遗失而未被检查
gpg: key DC30D7C23CBBABEE: 4 个签名因密钥遗失而未被检查
gpg: key 4DFAB270CAA96DFA: 4 个签名因密钥遗失而未被检查
gpg: key DCC9EFBF77E11517: 2 个签名因密钥遗失而未被检查
gpg: key 7638D0442B90D010: 4 个签名因密钥遗失而未被检查
gpg: key 9D6D8F6BC857C906: 4 个签名因密钥遗失而未被检查
gpg: key CBF8D6FD518E17E1: 2 个签名因密钥遗失而未被检查
gpg: key E0B11894F66AEC98: 5 个签名因密钥遗失而未被检查
gpg: key EDA0D2388AE22BA9: 5 个签名因密钥遗失而未被检查
gpg: key EF0F382A1A7B6500: 2 个签名因密钥遗失而未被检查
gpg: key 6FD77D5EDF966437: 1 个签名因密钥遗失而未被检查
gpg: 处理的总数：15
gpg:       已跳过的新密钥：15

deepin论坛上有人说UOS作了限制只能添加UOS认证的key，
我觉得UOS的这种功能不应该做的那么死，应该给用户自由自己判断自己的行为是否合理，就像mac一样开了权限就可以放行
不然肯定会流失很多用户

### 发行版以及版本

UOS专业版1021

**Comment by juteman** [comment]
这个我没有权限决定策略。
但是我这里有让你加入key 的方法
```bash
wget -nc https://dl.winehq.org/wine-builds/winehq.key
sudo apt-key add winehq.key
```
然后将源加入到 sourcelist 里面，应该就能用apt 下载wine了

**Comment by widon1104** [comment]
UOS限制太多了，我已经改用deepin V20了

**Comment by juteman** [comment]
> UOS限制太多了，我已经改用deepin V20了

那还是俺为你服务，俺是社区版的开发者之一

**Comment by jouyouyun** [comment]
`UOS` 没对这个做过限制

**Comment by widon1104** [comment]
如果UOS没对这个做过限制，那就是bug了

**Comment by justforlxz** [comment]
我看到有这么一行提示。
`gpg: invalid key resource URL '/etc/apt/trusted.gpg.d/home:smplayerdev.gpg'`

我认为是你的环境存在问题。

这里是我在一台uos sp2上运行的结果。

```
# deepin @ deepin-PC in ~ [15:08:33]
$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 76F1A20FF987672F
[sudo] deepin 的密码：
Executing: /tmp/apt-key-gpghome.8BFKAVdHGc/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 76F1A20FF987672F
gpg: 密钥 76F1A20FF987672F：公钥 “WineHQ packages <wine-devel@winehq.org>” 已导入
gpg: 处理的总数：1
gpg:               已导入：1

```

**Comment by justforlxz** [comment]
https://askubuntu.com/questions/1246031/gpg-invalid-key-resource-url-following-docker-official-guide  看看这个能不能帮到你

**Comment by widon1104** [comment]
我只是用命令行安装过smplayer，然后smplayer版本太低了就卸载了
我打开开发者模式并没有做过什么特别的操作就破坏了UOS环境，说明UOS环境还比较脆弱，需要加强

**Comment by mal1029** [comment]
我V20上安装wine也遇到同样问题。

**Comment by jouyouyun** [comment]
@xmuli 内部测试下？有问题就提个单

**Comment by wukuy** [comment]
在ubuntu 20.04 安装wine也出现这个问题，
```bash
sudo apt-key add winehq.key
gpg: invalid key resource URL '/tmp/apt-key-gpghome.EMB1v6cYsK/home:manuelschneid3r.asc.gpg'
gpg: 密钥区块资源‘(null)’：一般错误
gpg: key 7721F63BD38B4796: 2 个签名因密钥遗失而未被检查
gpg: key 1488EB46E192A257: 1 个签名因密钥遗失而未被检查
gpg: key 7721F63BD38B4796: 2 个签名因密钥遗失而未被检查
gpg: key 1488EB46E192A257: 1 个签名因密钥遗失而未被检查
gpg: key 3B4FE6ACC0B21F32: 3 个签名因密钥遗失而未被检查
gpg: key D94AA3F0EFE21092: 3 个签名因密钥遗失而未被检查
gpg: key 871920D1991BC93C: 1 个签名因密钥遗失而未被检查
gpg: key 76F1A20FF987672F: 1 个签名因密钥遗失而未被检查
gpg: 处理的总数：11
gpg:       已跳过的新密钥：11

```

我电脑安装了albert

删除
```bash
sudo rm -r /etc/apt/trusted.gpg.d/home:manuelschneid3r.asc
```

参考: https://askubuntu.com/questions/1246031/gpg-invalid-key-resource-url-following-docker-official-guide

希望能帮助你.
