### ISSUE TITLE
Now no sound

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/developer-center#1862]
Everything new is a new problem.

[Record.zip](https://github.com/linuxdeepin/developer-center/files/5085943/Record.zip)

**Comment by vesterlay** [comment]
You have exactly the same ability to fix this problem, as all people in this project. If you have any issues just fix it on your own and make a pull request. You basically demand a fix, when you get a completely free, opensource, next-gen desktop environment. Don't behave like spoiled brat.

**Comment by es20490446e** [comment]
@vesterlay Lets say I have another 25 own open source projects I keep fixed at any given time.

How I do it? If there are bugs I fix those first, instead of keeping adding more code full of sheet. Substituting working software for untested code.

I'm sure people just keep committing without even testing.

**Comment by vesterlay** [comment]
I see you didn't get what I've said. **They have no obligations to provide you anything nor do things like you want.** It's not like you are their customer that gave something or paid in exchange for this DE. Obviously constructive suggestions are definitely wanted, but what you just did is a total boorishness.

You should be grateful to all deepin developers for providing us such a wonderful piece of software. If you don't like something, use the power of opensource, fork this project and make it better or make a pull request with a fix.

Not to mention, your video is most likely not even from their supported release of Deepin.

**Comment by es20490446e** [comment]
@vesterlay Contributing fixes won't work, if any other new commit leads to garbage. Hope you get it now, otherwise crap.

**Comment by juteman** [comment]
Well, I think that who use deepin-desktop is potential customer for us. And the man who can find bugs and take a issus is also a greate contribution for the deepin community.

But there are insufficient information for this issues. We don't know which linux distribution is used. And We don't know which package version is used. I have seen this issues yesterday, but I don't know how to reply U.

So could you give me more information?

**Comment by juteman** [comment]
```
arecord -l
```
This command can give the audio input device information

```
aplay -l
```
This command can give the audio output device information.

And It will give us more information if you can download D-feet or qt5-dbusviewer.
1. Open the **D-feet**
2. Choose **session bus**
3. Search *com.deepin.daemon.Audio*
4. On the right, click /com/deepin/daemon/Audio, click com.deepin.daemon/Audio. there are some **Properties**. Click all the properties and show us the information.

**Comment by es20490446e** [comment]
```
$ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: Intel [HDA Intel], device 0: VT1705 Analog [VT1705 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: U0x46d0x821 [USB Device 0x46d:0x821], device 0: USB Audio [USB Audio]
  Subdevices: 1/1                                                           
  Subdevice #0: subdevice #0                                                
card 3: Device [USB Audio Device], device 0: USB Audio [USB Audio]          
  Subdevices: 1/1                                                           
  Subdevice #0: subdevice #0                                                
```

```
$ aplay -l                                          
**** List of PLAYBACK Hardware Devices ****                                 
card 0: Intel [HDA Intel], device 0: VT1705 Analog [VT1705 Analog]     
  Subdevices: 1/1                                                           
  Subdevice #0: subdevice #0                                                
card 2: HDMI [HDA ATI HDMI], device 3: HDMI 0 [HDMI 0]  
  Subdevices: 1/1          
  Subdevice #0: subdevice #0 
card 3: Device [USB Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1 
  Subdevice #0: subdevice #0 
```

System specs:
- Manjaro Linux Stable
- Linux 5.7
- PulseAudio 13.0
- ALSA 1.2.3
- Deepin Control Center 5.3.0

**Comment by es20490446e** [comment]
On D-Feet no audio daemon is on the list.

**Comment by juteman** [comment]
![screen](https://user-images.githubusercontent.com/13850064/90710643-63e1b500-e2d1-11ea-9bea-daa388a93ab6.png)
like this
@es20490446e

**Comment by es20490446e** [comment]
![Screen Capture_20200820052351](https://user-images.githubusercontent.com/9594332/90713334-5e6e7580-e2a5-11ea-870d-ffc149a216f5.png)

**Comment by juteman** [comment]
click all the Properties and get screenshot again

**Comment by es20490446e** [comment]
![Screen Capture_20200820053948](https://user-images.githubusercontent.com/9594332/90714293-a2fb1080-e2a7-11ea-911c-aa7b8eb5140e.png)

**Comment by zhangxiangsong** [comment]
Your can execute this command:
aplay -D hw:0,0  videofile
example: aplay -D hw:0,0  /usr/share/sounds/deepin/stereo/system-shutdown.wav
If you can`t hear the video, it means the alsa driver can not work.

**Comment by es20490446e** [comment]
This doesn't work:
```
$ aplay -D hw:0,0 /usr/share/sounds/deepin/stereo/system-shutdown.wav
aplay: main:830: audio open error: No such file or directory
```
This works:
```
$ aplay --device=default /usr/share/sounds/deepin/stereo/system-shutdown.wav
Playing WAVE '/usr/share/sounds/deepin/stereo/system-shutdown.wav' : Signed 24 bit Little Endian in 3bytes, Rate 48000 Hz, Stereo
```

**Comment by xmuli** [comment]
In archlinux + dde, it has been fixed after I updated (Manjaro has also been repaired).
![2020-09-09_10-25](https://user-images.githubusercontent.com/33887845/92547494-9014a400-f287-11ea-87c3-3fa5e2f88df0.png)

**Comment by juteman** [comment]
> In archlinux + dde, it has been fixed after I updated (Manjaro has also been repaired).
> ![2020-09-09_10-25](https://user-images.githubusercontent.com/33887845/92547494-9014a400-f287-11ea-87c3-3fa5e2f88df0.png)

The package in manjaro  community has not been repair, but remove deepin-desktop in manjaro community reinstall deepin-desktop in aur will fix

**Comment by xmuli** [comment]
There are solutions on arch and manjaro. If there are new questions later, please open this question again
