### ISSUE TITLE
Arch Linux is not getting the latest update from the branch 'uos'

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#1868]
Last month, I sent a patch to 'dde-dock' in the branch 'uos' which got accepted.

But after waiting for over 1 month, that patch still hasn't reached Archlinux. The version of 'dde-dock' that Archlinux uses, doesn't seem to have that patch.

Is there anything wrong?

**Comment by tsic404** [comment]
is this [pull request](https://github.com/linuxdeepin/dde-dock/pull/283) ?

**Comment by tsic404** [comment]
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue
