### ISSUE TITLE
Deepin File Manager 沒有套用翻譯

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#187]
從終端機來看明明是中文，但在 Deepin File Manager 卻還是顯示英文
![deepinscreenshot20170306112137](https://cloud.githubusercontent.com/assets/20014762/23595769/691ff460-025f-11e7-948e-4edc99faf43a.png)

**Comment by kirigayakazushin** [comment]
这些目录是[xdg user director](https://wiki.archlinux.org/index.php/XDG_user_directories) 控制的，文件管理器会使用当前用户设置的语言进行国际化处理。

**Comment by zccrs** [comment]
尝试把系统语言切换到中文。文件管理器中是自己做了这几个特殊目录的国际化，所以显示的名称并不是目录名。

**Comment by JulianLai** [comment]
可是我的系統語言一直是中文

**Comment by JulianLai** [comment]
@kirigayakazushin 
完全沒效果
![deepinscreenshot20170306113850](https://cloud.githubusercontent.com/assets/20014762/23596025/b03e7e0a-0261-11e7-8567-24e6945ef9dd.png)

**Comment by zccrs** [comment]
@JulianLai 你的是什么系统？截图中文件管理器并没有加载中文翻译，你的系统现在应该不是中文吧

**Comment by JulianLai** [comment]
@zccrs 
剛剛的圖
![deepinscreenshot20170306113038](https://cloud.githubusercontent.com/assets/20014762/23595881/58e228ec-0260-11e7-8cce-b5df11f61810.png)

**Comment by zccrs** [comment]
@JulianLai 哦，是这样的，文件管理器现在还没有加入对繁体中文的翻译，所以显示的是英文

**Comment by JulianLai** [comment]
@zccrs 了解了
