### ISSUE TITLE
使用冬青黑体字体有重叠

### ISSUE THREAD

**Issue by zoze0** [linuxdeepin/developer-center#1870]
## 缺陷描述

使用冬青黑体字体有重叠
## 复现步骤

1.下载冬青黑体安装
我用的这个http://www.fonts.net.cn/font-32380384471.html
2.重启电脑在设置里选冬青黑字体

## 期望行为

字体不要重叠
## 截图

![截图录屏_选择区域_20200825205722](https://user-images.githubusercontent.com/20562449/91180586-7a956b00-e71a-11ea-8d27-002b18d62456.png)
![截图录屏_选择区域_20200825205754](https://user-images.githubusercontent.com/20562449/91180616-85500000-e71a-11ea-9a6b-8f078962d5bf.png)

## 复现环境:

24寸 1080p
### 发行版以及版本

deepin20(0825版iso全新安装)
### 其他内容

PS:安装完字体在设置里选不到，要重启电脑后才能选择，算不算缺陷呢

**Comment by licardoY** [comment]
1002正式版全新安装这个bug依旧存在。
```
➜ ~ cat /etc/os-version
[Version] 
SystemName=deepin
SystemName[zh_CN]=深度操作系统
ProductType=Desktop
ProductType[zh_CN]=桌面
EditionName=Community
EditionName[zh_CN]=社区版
MajorVersion=20
MinorVersion=1002
OsBuild=11031.104
```

**Comment by tsic404** [comment]
最新的版本已经修复了问题，而且不需要重启便可以读取安装的字体
![image](https://user-images.githubusercontent.com/48748112/148516454-4b87d757-30d0-4eb9-9996-d0769e835f01.png)

**Comment by tsic404** [comment]
这个issue将会被关闭，如果你还有任何问题，可以重新打开此issue
