### ISSUE TITLE
安装界面选择磁盘时,磁盘的容量条异常

### ISSUE THREAD

**Issue by zoze0** [linuxdeepin/developer-center#1872]
## 缺陷描述

- 问题1:安装界面选择磁盘时,磁盘的容量条异常,选中的√和磁盘容量条重叠了

- 问题2: 磁盘容量条长度是以什么维度确定的?如果以容量大小,应该224G的长度比112G长,实际上显示的是更短,
 如果蓝色代表使用百分比,则应该不同容量磁盘总长度保持一致

## 复现步骤

1. 0825版iso刻录U盘启动盘
2. 启动安装到硬盘选择界面

## 截图

![1](https://user-images.githubusercontent.com/20562449/91250647-1d3a0200-e78c-11ea-8d75-4bd1e7c3fc28.png)

## 复现环境:

24寸 1080p
### 发行版以及版本

deepin20(0825)

**Comment by xmuli** [comment]
好像后面采取了新版本的安装器

**Comment by tsic404** [comment]
![image](https://user-images.githubusercontent.com/48748112/148034303-698778a0-56fb-407d-af1e-5220bd76d284.png)
问题已经修复，这个issue将被关闭。
