### ISSUE TITLE
DDE Povides icons (Enhancement, dev side)

### ISSUE THREAD

**Issue by N1coc4colA** [linuxdeepin/developer-center#1874]
Hello, this isn't a bug but more a suggestion. I see that DDE uses its own icons/images in many apps. But could it be possible to provide a way in libdtk to get any of these icons that could be used when using C/C++ with Qt/Dtk? Like a QIcon::fromTheme("icon") but for DDE ones, as a separate libs or embbeded in an existing one? The apps will be lighter and more "unified" as it can make developping with your toolkit easier., I thought that was a good idea... :)

**Comment by xmuli** [comment]
Some of the most basic icons are not directly included in dtk and can be obtained by using `QIcon :: fromTheme ("xxx")`. In addition, picture resources need to correspond to the project. Put the resources into the project by yourself (pay attention to the path), which can also take effect


![image](https://user-images.githubusercontent.com/33887845/91676811-9d3cdf00-eb73-11ea-8713-7d8ea8c59f31.png)
![image](https://user-images.githubusercontent.com/33887845/91676824-a2019300-eb73-11ea-98bf-5fa6f12b31e4.png)

You can view the details here
![image](https://user-images.githubusercontent.com/33887845/91676878-ceb5aa80-eb73-11ea-95e9-117a55ce0b6f.png)

**Comment by N1coc4colA** [comment]
> Some of the most basic icons are not directly included in dtk and can be obtained by using `QIcon :: fromTheme ("xxx")`. In addition, picture resources need to correspond to the project. Put the resources into the project by yourself (pay attention to the path), which can also take effect
Yes, I know QRC, I made a wrapper to get those like QIcon::fromTheme("xxx"), but it more for things like the little trash icon at the left, the heart for liked songs and albums (...) such things that are usefull, I want to make an app but I need these icons, and it is complicated to look in the project, locate the image and import it when you don't know if it's in a lib or not.... But I'll wait, if you implement such things I'll use it

**Comment by meiyixiang** [comment]
Hello, this is a problem. I will record it and consult r&d to see if it can provide this type of interface

**Comment by meiyixiang** [comment]
Later we will provide a wiki to tell you how to use it
