### ISSUE TITLE
deepin V20 20200826升级失败

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1876]
## 缺陷描述

sudo apt install -f的输出：
widon@widon-deepin:~$ sudo apt install -f
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。
有 5 个软件包没有被完全安装或卸载。
解压缩后会消耗 0 B 的额外空间。
正在设置 deepin-anything-dkms (5.0.1-1-1) ...
Removing old deepin-anything-0.0 DKMS files...

*------------------------------
Deleting module version: 0.0
completely from the DKMS tree.
*------------------------------
Done.
Loading new deepin-anything-0.0 DKMS files...
Building for 5.6.5-050605-generic
Building initial module for 5.6.5-050605-generic
Error! Bad return status for module build on kernel: 5.6.5-050605-generic (x86_64)
Consult /var/lib/dkms/deepin-anything/0.0/build/make.log for more information.
dpkg: 处理软件包 deepin-anything-dkms (--configure)时出错：
 已安装 deepin-anything-dkms 软件包 post-installation 脚本 子进程返回错误状态 10
dpkg: 依赖关系问题使得 dde-file-manager 的配置工作不能继续：
 dde-file-manager 依赖于 deepin-anything-dkms；然而：
  软件包 deepin-anything-dkms 尚未配置。

dpkg: 处理软件包 dde-file-manager (--configure)时出错：
 依赖关系问题 - 仍未被配置
正在设置 bcmwl-kernel-source (6.30.223.271+bdcom-5uos) ...
Removing old bcmwl-6.30.223.271+bdcom DKMS files...

*------------------------------
Deleting module version: 6.30.223.271+bdcom
completely from the DKMS tree.
*------------------------------
Done.
Loading new bcmwl-6.30.223.271+bdcom DKMS files...
Building for 5.6.5-050605-generic
Building for architecture x86_64
Building initial module for 5.6.5-050605-generic
Error! Bad return status for module build on kernel: 5.6.5-050605-generic (x86_64)
Consult /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/make.log for more information.
dpkg: 处理软件包 bcmwl-kernel-source (--configure)时出错：
 已安装 bcmwl-kernel-source 软件包 post-installation 脚本 子进程返回错误状态 10
dpkg: 依赖关系问题使得 deepin-anything-server 的配置工作不能继续：
 deepin-anything-server 依赖于 deepin-anything-dkms；然而：
  软件包 deepin-anything-dkms 尚未配置。

dpkg: 处理软件包 deepin-anything-server (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 dde 的配置工作不能继续：
 dde 依赖于 dde-file-manager；然而：
  软件包 dde-file-manager 尚未配置。

dpkg: 处理软件包 dde (--configure)时出错：
 依赖关系问题 - 仍未被配置
在处理时有错误发生：
 deepin-anything-dkms
 dde-file-manager
 bcmwl-kernel-source
 deepin-anything-server
 dde
E: Sub-process /usr/bin/dpkg returned an error code (1)

希望以后发更新的时候谨慎一点，软件包升级失败最近经常发生，不知道怎么恢复

### 发行版以及版本

deepin V20

**Comment by justforlxz** [comment]
你好，麻烦上传一下/var/lib/dkms/deepin-anything/0.0/build/make.log文件，我看一下dkms编译信息。

**Comment by justforlxz** [comment]
请问是否自行安装了不同版本的内核，系统提供的内核版本是5.4/5.7，不存在5.6.5，如果以升级到仓库的5.7版本的内核，那么这个版本的内核就可以卸载了。不然dkms仍然会编译失败。

**Comment by widon1104** [comment]
我是自己安装了ubuntu提供的5.6.5的内核，请问一下我现在这种情况如何恢复呢？
我现在sudo apt install -f失败，sudo apt install linux-deepin-image-5.7能够安装5.7的内核吗？

**Comment by widon1104** [comment]
> 请问是否自行安装了不同版本的内核，系统提供的内核版本是5.4/5.7，不存在5.6.5，如果以升级到仓库的5.7版本的内核，那么这个版本的内核就可以卸载了。不然dkms仍然会编译失败。

你的意思是以后使用deepin必须使用官方提供的内核，不能自己安装其它的内核，如果安装了其它的内核就可能导致升级失败？
我觉得这样不太人性化，因为官方的内核版本往往很低，希望也能支持其它的内核像ubuntu编译的内核

**Comment by justforlxz** [comment]
> > 请问是否自行安装了不同版本的内核，系统提供的内核版本是5.4/5.7，不存在5.6.5，如果以升级到仓库的5.7版本的内核，那么这个版本的内核就可以卸载了。不然dkms仍然会编译失败。
> 
> 你的意思是以后使用deepin必须使用官方提供的内核，不能自己安装其它的内核，如果安装了其它的内核就可能导致升级失败？
> 我觉得这样不太人性化，因为官方的内核版本往往很低，如果玩家使用很新的硬件希望升级到高版本内核获得更好的硬件支持，希望也能支持其它的内核像ubuntu编译的内核

不能随便用其他内核是因为dkms内核模块都是要手动匹配的，不然就会出现某个内核模块不能为该内核编译成功。内核版本过低这件事内部开会也有讨论，我记得好像是同意以后deepin会尽可能的使用最新的内核。目前的解决办法是安装linux-image-deepin-amd64和linux-headers-deepin-amd64，并卸载安装的ubuntu内核。卸载ubuntu的内核可以在确认deepin的内核可正常使用的情况下执行。

**Comment by widon1104** [comment]
我这种情况，执行
sudo apt install linux-image-5.7.7-deepin-amd64 linux-headers-5.7.7-deepin-amd64
sudo reboot
sudo apt install -f
就好了
