### ISSUE TITLE
Cannot switch keyboard layout in installer

### ISSUE THREAD

**Issue by nslynx** [linuxdeepin/developer-center#1878]
## Describe the bug
Cannot switch keyboard layout during installation

## To Reproduce
Just select non-latin layout and try to enter user/password (they have to be latin)
-->

## Expected behavior
Can switch to latin layout (using some hotkeys, for example) or automatically switch to latin layout

## Distro & Version
deepin v20

### Related package version
Installer

**Comment by justforlxz** [comment]
The keyboard layout can be modified during installation.

**Comment by tsic404** [comment]
The keyboard layout can be modified during installation.
