### ISSUE TITLE
[Feature Request] 请增加固定dock栏在指定屏幕的选项

### ISSUE THREAD

**Issue by happyd0ggie** [linuxdeepin/developer-center#1879]
# 问题描述
2020.8.26 系统更新后, 一项新功能被引入: 当鼠标指向屏幕底部时, dock栏会自动切换至该屏幕. 这很有意思, 但体验并不好.
**因为经常会误触发此操作, 并且会引发已打开窗口大小改变, 样式改变.**
# 期望行为
请添加固定dock栏的选项, 可固定在指定的屏幕.

**Comment by xmuli** [comment]
这个建议或许不错；
对于其他方案的一个参考， 在mac 上同样也是，鼠标会在底部几秒钟，dock 也会迁移到其他屏幕上；另外 win 的解决方案也不错，两个屏幕都可以显示 dock

**Comment by shengdexiang** [comment]
> 这个建议或许不错；
> 对于其他方案的一个参考， 在mac 上同样也是，鼠标会在底部几秒钟，dock 也会迁移到其他屏幕上；另外 win 的解决方案也不错，两个屏幕都可以显示 dock

是的, 但 dde 貌似只要鼠标指向底部, 感觉胡立马迁移, 速度有点快

**Comment by xmuli** [comment]
see [https://bbs.deepin.org/post/202404](https://bbs.deepin.org/post/202404)
