### ISSUE TITLE
dtk控件库扩充完善方案和意见征集

### ISSUE THREAD

**Issue by zhangxiangsong** [linuxdeepin/developer-center#1885]
## 征集背景

​	dtk界面库是统信uos和deepin系统UI的底层控件库，为应用层开发提供丰富的UI控件和统一的操作系统样式。经过多个版本的迭代，尽管dtk已经提供了非常多的控件，但覆盖面仍然不是非常全面和广泛，因此我们想通过合理的方式，接受外部开发者提供控件，建立一个控件备选库，将一些功能不重叠的优秀的外部控件整合到备选库，然后由公司内部重新设计样式保持与dtk风格统一化，并对代码做出优化，之后将该控件合入dtk控件库。

## 面向群体
​	本次征集主要面向统信软件各个研发中心的开发者、deepin社区开发者、第三方自由开发者以及活跃在软件行业的专业人员，只要是提供的扩充完善方案和意见能实现我们的目标，我们都会加入评估采纳。

## 采纳方式
​	方案和意见可以在该issue下方回复，我们会实时关注采集大家的反馈，汇总后上报，经过公司内部的小组进行评审讨论，并将讨论结果反馈给提出者。

​	针对有这方面经验的专业人士，您也可以向我们毛遂自荐，提供电子邮箱或者联系方式，我们评审小组将直接与您沟通，我们非常期待能与您一起扩充和完善dtk控件库。

**Comment by jiangzc** [comment]
参考 飞扬青云 的 Qt 控件 系列， https://github.com/feiyangqingyun/QWidgetDemo

推荐控件：  仪表盘  （下图）

![image](https://user-images.githubusercontent.com/13901512/91535852-61710200-e946-11ea-81dc-f3c21b348299.png)

**Comment by jiangzc** [comment]
Qt编写自定义控件大全   （飞扬青云）

https://www.cnblogs.com/feiyangqingyun/p/6128288.html

**Comment by jiangzc** [comment]
推荐： 树状导航栏 
 https://www.cnblogs.com/feiyangqingyun/p/6128288.html 

（下图）

![image](https://user-images.githubusercontent.com/13901512/91536758-c9741800-e947-11ea-87cf-3074e15a5d07.png)

**Comment by jiangzc** [comment]
导航进度条控件

![image](https://user-images.githubusercontent.com/13901512/91536838-f0324e80-e947-11ea-9a3d-99832c7e514b.png)

**Comment by myflash163** [comment]
DTK 能适配一下flutter吗？

**Comment by 2947452532** [comment]
qml

**Comment by xmuli** [comment]
@2947452532  qml 的样式已经提上了日程

**Comment by justforlxz** [comment]
> DTK 能适配一下flutter吗？

不同图形库之间基本不存在可移植性，只能遵守同样的设计文稿重新做实现，欢迎flutter大佬们贡献对应的库 😄

**Comment by ZhongYic00** [comment]
- DIconButton希望能提供一个接口，分别设置light mode和dark mode下的第三方图标
- 类似于QWidget的底层DWidget，能够设置圆角、阴影。有时候需要自绘控件，若需设置圆角除了qss就只能想到重写PaintEvent，而自行设置qss不易匹配DTK的主题
略表拙见，以上。

**Comment by myflash163** [comment]
> > DTK 能适配一下flutter吗？
> 
> 不同图形库之间基本不存在可移植性，只能遵守同样的设计文稿重新做实现，欢迎flutter大佬们贡献对应的库 😄
dtk 开发人员 比较少，大家都想转战移动端了。现在官方给gtk 适配了flutter 使用 snappy 打包，后面 移动应用 适配到 ubuntu的会非常多，deepin 应该先入局，以后就不愁 开发人员少了

**Comment by Primal123** [comment]
不太懂这些……不过我想能不能通过一些按钮的颜色来表示软件的某种状态/功能的打开和关闭。
以一个文本编辑软件为例吧：
![示例](https://user-images.githubusercontent.com/70436680/92556876-84f74f00-f25a-11ea-8f4f-145be41eee77.png)

**Comment by xmuli** [comment]
@Primal123 假设只是 DToolButton 控件，想表达的意思是，希望开放此的设置背景色和前景色的接口

**Comment by justforlxz** [comment]
这条信息已经太久没有人跟进了，关闭了。
