### ISSUE TITLE
[Bug Report] 企业微信设置文件存储路径出错

### ISSUE THREAD

**Issue by shengdexiang** [linuxdeepin/developer-center#1889]
## 缺陷描述

企业微信设置文件存储路径时报错, 无法自定义文件存储路径

## 复现步骤

1. 打开 '企业微信'
2. 打开 '更多'/'设置'/'文档/文件管理'
3. 点击文件存储 '更改'
4. 选择其他位置
5. 提示 '目录不可访问, 请重新选择'

## 期望行为

能够自定义文件存储路径

## 截图

[自定义设置文件存储路径报错](https://ftp.bmp.ovh/imgs/2020/08/c904e8c8f0d88648.png)
[APP内看到的企微版本](https://ftp.bmp.ovh/imgs/2020/08/9acfd0947b325dd5.png)

### 发行版以及版本

```
 OS: Deepin 20
 Kernel: x86_64 Linux 5.3.0-3-amd64
 Uptime: 3d 14m
 Packages: 2991
 Shell: bash
 Resolution: 2720x1024
 DE: Deepin 20
 WM: KWin
 GTK Theme: deepin-dark [GTK2/3]
 Icon Theme: bloom
 CPU: Intel Core i7-6700 @ 8x 4GHz [27.8°C]
 GPU: Mesa DRI Intel(R) HD Graphics 530 (Skylake GT2) 
 RAM: 10571MiB / 15966MiB
```

### 相关的软件包版本

```
$ deepin-wine --version
wine-2.18
$ dpkg -l | grep -i deepin.com.weixin.work
ii  com.qq.weixin.work.deepin:i386                3.0.20.1618deepin5                  i386         Tencent WeChat Work Client on Deepin Wine
rc  deepin.com.weixin.work:i386                   2.8.10.2010deepin0                  i386         Tencent WeChat Work Client on Deepin Wine
```

### 其他内容

自定义文件存储路径时选择的是 veracrypt 加密盘中的目录

**Comment by shengdexiang** [comment]
通过 deepinwine-mgr 重新设置容器的映射和驱动器位置后, 删除原本想映射的文件夹再新建,  最后在企微里设置文件存储路径成功

**Comment by xmuli** [comment]
这个解决方案，可以给其他人一个参考

**Comment by shengdexiang** [comment]
> 通过 deepinwine-mgr 重新设置容器的映射和驱动器位置后, 删除原本想映射的文件夹再新建, 最后在企微里设置文件存储路径成功

升级v20正式版后, 问题又出现了, 且这个方法不管用了

**Comment by shengdexiang** [comment]
> > 通过 deepinwine-mgr 重新设置容器的映射和驱动器位置后, 删除原本想映射的文件夹再新建, 最后在企微里设置文件存储路径成功
> 
> 升级v20正式版后, 问题又出现了, 且这个方法不管用了

[解决方案](https://shengdexiang.github.io/2020/09/14/let-deepin-wxwork-support-truecrypt-volumn-as-storage-location/)
