### ISSUE TITLE
Dock 的圖示都變得怪怪的，Deepin-icon-theme 失效

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#189]
Deepin 原本的圖示都不見了
![deepinscreenshot20170307230804](https://cloud.githubusercontent.com/assets/20014762/23662599/15c08398-038b-11e7-8116-d395bf5de2f3.png)
原本只是偶而發生，但在最近的一次更新就變這樣，不管登出幾次都沒用

OS: antergos(arch)

移除掉 Numix-icon-theme 後更是慘不忍睹
![deepinscreenshot20170307232204](https://cloud.githubusercontent.com/assets/20014762/23663211/e4f669b0-038c-11e7-8191-929ea4207351.png)
目前為止只有 Numix-icon-theme-square 有效

**Comment by hualet** [comment]
@zccrs

**Comment by JulianLai** [comment]
有後續嗎？

**Comment by hualet** [comment]
貌似Arch上使用没有问题，但是基于Arch的两个发行版 Manjaro和Antergos都有问题，还没有找到原因；

**Comment by JulianLai** [comment]
#240
