### ISSUE TITLE
[Bug Report] Visual Studio Code 在 dock 栏显示两个图标

### ISSUE THREAD

**Issue by happyd0ggie** [linuxdeepin/developer-center#1894]
## 缺陷描述

Visual Studio Code 在 dock 栏显示两个图标, 但只开启了一个窗口

## 复现步骤

1. 打开 'Visual Studio Code'
2. dock 栏显示两个图标
3. 点击任意一个图标都可打开窗口
4. 关闭窗口后 dock 栏依然显示一个图标
5. ps 搜索不到相关进程
6. 右键图标, 点击 '关闭所有'/'前置退出', 图标依然存在(P.S. 图标并未设置驻留在 dock 栏)

## 期望行为

打开一个窗口只显示一个图标, 关闭vscode后图标不应存在在dock栏

## 截图

[显示两个图标](https://ftp.bmp.ovh/imgs/2020/09/e964e57601ac6dce.png)
[关闭vscode后依然显示一个图标](https://ftp.bmp.ovh/imgs/2020/09/571ef22f85029699.png)

### 发行版以及版本

```
 OS: Deepin 20                                                                                                                                                                     
 Kernel: x86_64 Linux 5.4.50-amd64-desktop
 Uptime: 1d 38m
 Packages: 2971
 Shell: bash
 Resolution: 2720x1024
 DE: Deepin 20
 WM: KWin
 GTK Theme: deepin-dark [GTK2/3]
 Icon Theme: bloom
 CPU: Intel Core i7-6700 @ 8x 4GHz [27.8°C]
 GPU: Mesa DRI Intel(R) HD Graphics 530 (Skylake GT2) 
 RAM: 5522MiB / 15897MiB
```

### 相关的软件包版本

```
$ code --version
1.48.2
a0479759d6e9ea56afa657e454193f72aef85bd0
x64
$ dde-dock --version
dde-dock 2.0
```

### 其他内容

升级 v20 之前不存在这个问题

**Comment by RigoLigoRLC** [comment]
据测试，应该是VSC在使用custom标题栏才会出现这个问题

**Comment by shengdexiang** [comment]
> 据测试，应该是VSC在使用custom标题栏才会出现这个问题

是的，忘记补充了，设置了不使用系统标题栏

**Comment by RigoLigoRLC** [comment]
解决了吗？我看你把issue关闭了

**Comment by happyd0ggie** [comment]
> 解决了吗？我看你把issue关闭了

20.1未出现问题了
