### ISSUE TITLE
[BUG] Calculator

### ISSUE THREAD

**Issue by dagda87** [linuxdeepin/developer-center#1895]
Calculator is not showing some icons in Spanish languaje
![Captura de pantalla_deepin-calculator_20200901094632](https://user-images.githubusercontent.com/70589808/91866356-0c7c0700-ec38-11ea-93d7-9609b0bd94db.png)

**Comment by xmuli** [comment]
@z966768

**Comment by alexwender1** [comment]
For Brazilian Portuguese (pt-BR) this also occurs.

![Screen Capture_deepin-calculator_20200904143936](https://user-images.githubusercontent.com/45263160/92270493-89b7ae00-eebc-11ea-80b4-d32c8ff850aa.png)

**Comment by eldelinux** [comment]
Same issue here with spanish languaje, in both modes, basic and scientific calculator.

![screeshot_20201227105854](https://user-images.githubusercontent.com/26395314/103168378-076c4480-4833-11eb-8669-ba80391d9075.png)

**Comment by z966768** [comment]
Please try the new version

**Comment by eldelinux** [comment]
Hi.

The new version 5.6.0.10 solve the problem. Thanks a lot.

![Captura de pantalla_área-de-selección_20210105103059](https://user-images.githubusercontent.com/26395314/103630072-74718f80-4f41-11eb-96e8-13a82a6c545b.png)

Cheers.

**Comment by z966768** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
