### ISSUE TITLE
[deepin 20] Virtualbox installs unnecessary dependencies

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#1900]
## Describe the bug
Virtualbox 6.1 from the repository is pulling in other unnecessary dependencies during installation. The Okular application and parts of the Kernel 5.3 are being installed.

## Screenshots
![Screen Capture_deepin-terminal_20200904123303](https://user-images.githubusercontent.com/45263160/92268736-59badb80-eeb9-11ea-9682-86fd0eb4905b.png)

### Distro & Version
deepin 20 (1001)

### Related package version
virtualbox-6.1

### Additional context
The hidden installation of the Okular application with Virtualbox was already an old problem of deepin 20.

**Comment by xmuli** [comment]
This should be reported to the upstream Virtualbox, the dependency is written by them

**Comment by alexwender1** [comment]
> This should be reported to the upstream Virtualbox, the dependency is written by them

Isn't the VirtualBox from the repository repackaged by you?

The Buster version of VirtualBox is the only one compatible with deepin 20 (debian Buster = kernel 4.19). Only the deepin 20 BETA (and RC) that used the 5.3 kernel.

Note: About the Okular application, I'm not sure if it's something native to Oracle (dependency placed by them). I'm pretty sure that the repository's VirtualBox is repackaged; and that unnecessary dependency could be removed when repackaging is done.

![Screen Capture_deepin-terminal_20200909090632](https://user-images.githubusercontent.com/45263160/92596956-052eac00-f27d-11ea-9fdd-507df38b1847.png)

**Comment by xmuli** [comment]
@justforlxz Maybe, can help solve this problem?

**Comment by justforlxz** [comment]
Thank you, I can notify the system group and let them check dependencies.

偕臧 <notifications@github.com> 于2020年9月10日周四 下午3:10写道：

**Comment by alexwender1** [comment]
Issue fixed in version 20.1 (1010)

![Captura de Tela_deepin-terminal_20201229095547](https://user-images.githubusercontent.com/45263160/103286111-804bd780-49be-11eb-9b0b-6309291d3093.png)
