### ISSUE TITLE
DTitlebar内控件位置错误

### ISSUE THREAD

**Issue by ZhongYic00** [linuxdeepin/developer-center#1902]
## 缺陷描述

dtkwidget库中DTitleBar的setFixedHeight函数使用后，titlebar的已添加控件不会自动垂直居中

## 复现步骤

使用DMainWindow时，调用titlebar()函数自定义默认的titlebar，代码如下：
`titlebar()->setFixedHeight(40);`
直接渲染出的titlebar中最小化、最大化、关闭按钮均位置偏下。
窗口最大化一次后，按钮正常居中，此后任意更改按钮均正常居中。

## 期望行为

使用setFixedHeight后titlebar自动重新计算控件位置，使控件正常居中

## 截图

![截图录屏_选择区域_20200906115654](https://user-images.githubusercontent.com/38401412/92317867-1dfa5000-f038-11ea-81cc-23787957b7cb.gif)

## 复现环境:

任意

### 发行版以及版本

deepin v20(1001)

### 相关的软件包版本

libdtkwidget5:amd64 5.2.2.2-1

**Comment by kegechen** [comment]
dtitlebar默认固定高度50,  里面的iconbutton高度都是50，当设置低于这个50是自然就绘制超过底部区域了， 导致看起来像偏下, 不建议修改这个高度， 保持和原生应用一致性。

如果一定需要改高度40，可以通过objectname找到optionButton/minButton/maxButton/closeButton/quitFullButton等 setIconSize(40)

**Comment by xmuli** [comment]
若是后面还有问题，请再重新打开此问题。

**Comment by ZhongYic00** [comment]
了解，问题已解决
