### ISSUE TITLE
Cannot install Deepin 20 Beta

### ISSUE THREAD

**Issue by chaim1221** [linuxdeepin/developer-center#1903]
## Describe the bug

I cannot install Deepin. The grub loader freezes before install. Here are the default options.
```
getparams 'Install Deepin 20 Beta desktop'
set gfxpayload=keep
linux /live/vmlinuz.efi boot=live union=overlay installer.disable.scale livecd-installer locale=zh_CN quiet splash --
initrd /live/initrd.lz
```
Typed so may contain errors.
I tried changing the locale to en-US see if it made a difference. It didn't.

I followed the troubleshooting steps in #1699 to no avail (note: I have an nvidia gpu, _not_ AMD)

I cannot even get to where I can give you logs.

## To Reproduce
1. With Etcher and SHA256 verified ISO create UEFI boot USB
2. Use Lenovo Yoga 720, 2.8GHz, Nvidia GTX 1050
3. Disable `Secure Boot` and `Fast Boot` in the BIOS (F2), then save.
4. Boot to USB (F12). Does not boot with default options.

## Expected behavior
Installer loads and I can install.

## Screenshots
Unfortunately the screenshots would be too low quality to help. It doesn't get past GRUB and the text is very small.

### Distro & Version
Deepin 20 Beta

**Comment by chaim1221** [comment]
I tried with Ubuntu DDE and got the same result. Went to the EFI settings and somehow Secure Boot was reenabled. I'm flashing a new drive and will try again.

**Comment by chaim1221** [comment]
That wasn't the issue. I disabled it and got the same result. I think I reloaded the defaults at one point. In any case, I'm still stuck.

**Comment by chaim1221** [comment]
_non_-DDE Ubuntu installer loads. Would love to troubleshoot this at some point, but going ahead with that for now. :-(

**Comment by chaim1221** [comment]
It complained about hardware RAID (or iRST or whatever they're calling it these days); does Deepin support hardware RAID configurations? (It's just one disk anyway.)

**Comment by chaim1221** [comment]
Disabling iRST didn't change anything. :-(

**Comment by chaim1221** [comment]
I got it to work! I disabled the integrated graphics (ouch to my battery, but hey).

If this is a requirement for Nvidia 'customers' you should *document it*. (Possible action item.)

If there are further issues I'll open a new issue.

**Comment by chaim1221** [comment]
Okay so in a related topic, I now cannot get the Nvidia GPU drivers to install at all. I think it's because on this system the integrated graphics are now just reporting to Nvidia (not really sure how it works). In any case I can't use the higher GPU functions and things like civ6 crap out. I'm going to try to enable hybridized graphics in the BIOS again and I'll report back.

**Comment by chaim1221** [comment]
Switching on hybridized graphics post-install: No issues.
Installing nonfree `nvidia-driver` package: No issue, but had to reinstall Plymouth.

Reboot: Works fine.

Only leaving this issue open because I feel like all of these requirements should be documented in the wiki. (If I have time, and find where the wiki is kept, I might submit a PR, otherwise, busy with work).

Thanks!

**Comment by xmuli** [comment]
> 在安装后打开混合图形：没有问题。
> 安装非免费`nvidia-driver`软件包：没问题，但必须重新安装Plymouth。

Your solution may help people in the same situation as you later. (Nice)

**Comment by meiyixiang** [comment]
22/5000 
Hello, now the latest version is not 20.5, you can upgrade your system
