### ISSUE TITLE
[Bug Report] 应用商店最新版微信打开公账号文章显示空白

### ISSUE THREAD

**Issue by shengdexiang** [linuxdeepin/developer-center#1904]
## 缺陷描述

最新版微信(wine)打开公账号文章显示空白

## 复现步骤

1. 打开'微信'
2. 随便打开一个公账号文章
3. 显示空白

## 期望行为

能够正常显示公账号文章内容

## 截图

[APP内看到的微信版本](https://ftp.bmp.ovh/imgs/2020/09/b9b3f91f33f04ed8.png)
[截图录屏_wechat.exe_20200907190706.zip](https://github.com/linuxdeepin/developer-center/files/5185678/_wechat.exe_20200907190706.zip)

### 发行版以及版本

```
OS: Deepin 20
Kernel: x86_64 Linux 5.4.50-amd64-desktop
Uptime: 20h 47m
Packages: 2995
Shell: bash
Resolution: 2720x1024
DE: Deepin 20
WM: KWin
GTK Theme: deepin-dark [GTK2/3]
Icon Theme: bloom
CPU: Intel Core i7-6700 @ 8x 4GHz [27.8°C]
GPU: Mesa DRI Intel(R) HD Graphics 530 (Skylake GT2)
RAM: 5770MiB / 15897MiB
```

### 相关的软件包版本

```
$ deepin-wine --version
wine-2.18
$ apt policy com.qq.weixin.deepin
com.qq.weixin.deepin:i386:
已安装：2.9.5.41deepin2
候选： 2.9.5.41deepin2
版本列表：
*** 2.9.5.41deepin2 500
500 https://community-store-packages.deepin.com/appstore eagle/appstore i386 Packages
100 /var/lib/dpkg/status
```

### 其他内容

打开公账号文章时, 最开始显示正在加载, 还没完全显示完整, 又显示空白, 录屏见附件

**Comment by xmuli** [comment]
保证主功能的情况下，wine 组后面会关注和尝试解决此问题

**Comment by shengdexiang** [comment]
> 保证主功能的情况下，wine 组后面会关注和尝试解决此问题

升级前是不存在此问题的

**Comment by saviorlv** [comment]
sudo apt update
sudo apt-get install ttf-mscorefonts-installer
 安装后重启微信就可解决

**Comment by shengdexiang** [comment]
> sudo apt update
> sudo apt-get install ttf-mscorefonts-installer
> 安装后重启微信就可解决

`ttf-mscorefonts-installer` 我从没装成功过.

**Comment by saviorlv** [comment]
> > sudo apt update
> > sudo apt-get install ttf-mscorefonts-installer
> > 安装后重启微信就可解决
> 
> `ttf-mscorefonts-installer` 我从没装成功过.

那就没办法了

**Comment by xmuli** [comment]
> > sudo apt update
> > sudo apt-get install ttf-mscorefonts-installer
> > 安装后重启微信就可解决
> 
> `ttf-mscorefonts-installer` 我从没装成功过.

刚测试了一下啊，安装最新的 deepin 1002 版本，按照 @saviorlv 的解决哦方案，直接安装  `ttf-mscorefonts-installer` 之后，重启就成功了，如下图；

若是没有安装成功，提示什么信息呢？ 你是如何尝试如何解决的呢？ 希望得到那些方面的帮助呢？


![image](https://user-images.githubusercontent.com/33887845/93185553-25280900-f770-11ea-889d-f0150194204b.png)

**Comment by shengdexiang** [comment]
> > > sudo apt update
> > > sudo apt-get install ttf-mscorefonts-installer
> > > 安装后重启微信就可解决
> > 
> > 
> > `ttf-mscorefonts-installer` 我从没装成功过.
> 
> 刚测试了一下啊，安装最新的 deepin 1002 版本，按照 @saviorlv 的解决哦方案，直接安装 `ttf-mscorefonts-installer` 之后，重启就成功了，如下图；
> 
> 若是没有安装成功，提示什么信息呢？ 你是如何尝试如何解决的呢？ 希望得到那些方面的帮助呢？
> 
> ![image](https://user-images.githubusercontent.com/33887845/93185971-a41d4180-f770-11ea-9b6e-bccdbe6df816.png)

问题现象跟这个一样: https://bbs.deepin.org/forum.php?mod=viewthread&tid=201680&highlight=%E4%BC%81%E4%B8%9A%E5%BE%AE%E4%BF%A1, 但手动下载安装 3.8 安装还是会出现这个现象.

**Comment by xmuli** [comment]
它是 UOS个人版， 你的是社区版。你是说，手动安装 3.8 安装提示成功，但是依旧无法显示错误？你用命令安装试试看，顺便看看截图报错是什么？我明天再看看我安装的版本。

**Comment by shengdexiang** [comment]
> 它是 UOS个人版， 你的是社区版。你是说，手动安装 3.8 安装提示成功，但是依旧无法显示错误？你用命令安装试试看，顺便看看截图报错是什么？我明天再看看我安装的版本。

`> sudo apt-get install --only-upgrade com.qq.weixin.work.deepin 
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
将会同时安装下列软件：
  cabextract ttf-mscorefonts-installer
下列【新】软件包将被安装：
  cabextract ttf-mscorefonts-installer
下列软件包将被升级：
  com.qq.weixin.work.deepin:i386
升级了 1 个软件包，新安装了 2 个软件包，要卸载 0 个软件包，有 1 个软件包未被升级。
需要下载 311 MB 的归档。
解压缩后会消耗 59.9 MB 的额外空间。
您希望继续执行吗？ [Y/n] y
获取:1 https://community-packages.deepin.com/deepin apricot/main amd64 cabextract amd64 1.9-1 [35.0 kB]
获取:2 https://community-packages.deepin.com/deepin apricot/contrib amd64 ttf-mscorefonts-installer all 3.7 [31.3 kB]
获取:3 https://community-store-packages.deepin.com/appstore eagle/appstore i386 com.qq.weixin.work.deepin i386 3.0.23.1604deepin4 [311 MB]
已下载 311 MB，耗时 3分 10秒 (1,636 kB/s)                                                                                                                                         
正在预设定软件包 ...
正在选中未选择的软件包 cabextract。
(正在读取数据库 ... 系统当前共安装有 429703 个文件和目录。)
准备解压 .../cabextract_1.9-1_amd64.deb  ...
正在解压 cabextract (1.9-1) ...
正在选中未选择的软件包 ttf-mscorefonts-installer。
准备解压 .../ttf-mscorefonts-installer_3.7_all.deb  ...
正在解压 ttf-mscorefonts-installer (3.7) ...
准备解压 .../com.qq.weixin.work.deepin_3.0.23.1604deepin4_i386.deb  ...
正在解压 com.qq.weixin.work.deepin:i386 (3.0.23.1604deepin4) 并覆盖 (3.0.20.1618deepin5) ...
正在设置 cabextract (1.9-1) ...
正在设置 ttf-mscorefonts-installer (3.7) ...

These fonts were provided by Microsoft "in the interest of cross-
platform compatibility".  This is no longer the case, but they are
still available from third parties.

You are free to download these fonts and use them for your own use,
but you may not redistribute them in modified form, including changes
to the file name or packaging format.

--2020-09-16 10:21:45--  http://downloads.sourceforge.net/corefonts/andale32.exe
正在解析主机 downloads.sourceforge.net (downloads.sourceforge.net)... 216.105.38.13
正在连接 downloads.sourceforge.net (downloads.sourceforge.net)|216.105.38.13|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 读取文件头错误 (连接被对方重设)。
放弃操作。

--2020-09-16 10:21:46--  http://switch.dl.sourceforge.net/sourceforge/corefonts/andale32.exe
正在解析主机 switch.dl.sourceforge.net (switch.dl.sourceforge.net)... 失败：未知的名称或服务。
wget: 无法解析主机地址 “switch.dl.sourceforge.net”
--2020-09-16 10:21:46--  http://dfn.dl.sourceforge.net/sourceforge/corefonts/andale32.exe
正在解析主机 dfn.dl.sourceforge.net (dfn.dl.sourceforge.net)... 失败：未知的名称或服务。
wget: 无法解析主机地址 “dfn.dl.sourceforge.net”
--2020-09-16 10:21:47--  http://heanet.dl.sourceforge.net/sourceforge/corefonts/andale32.exe
正在解析主机 heanet.dl.sourceforge.net (heanet.dl.sourceforge.net)... 2001:770:18:aa40::c101:c142
正在连接 heanet.dl.sourceforge.net (heanet.dl.sourceforge.net)|2001:770:18:aa40::c101:c142|:80... 失败：网络不可达。
--2020-09-16 10:21:47--  http://jaist.dl.sourceforge.net/sourceforge/corefonts/andale32.exe
正在解析主机 jaist.dl.sourceforge.net (jaist.dl.sourceforge.net)... 2001:df0:2ed:feed::feed, 150.65.7.130
正在连接 jaist.dl.sourceforge.net (jaist.dl.sourceforge.net)|2001:df0:2ed:feed::feed|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 没有接收到数据。
放弃操作。

--2020-09-16 10:24:59--  http://nchc.dl.sourceforge.net/sourceforge/corefonts/andale32.exe
正在解析主机 nchc.dl.sourceforge.net (nchc.dl.sourceforge.net)... 2001:e10:ffff:1f02::17, 140.110.96.69
正在连接 nchc.dl.sourceforge.net (nchc.dl.sourceforge.net)|2001:e10:ffff:1f02::17|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 没有接收到数据。
放弃操作。

--2020-09-16 10:28:09--  http://ufpr.dl.sourceforge.net/sourceforge/corefonts/andale32.exe
正在解析主机 ufpr.dl.sourceforge.net (ufpr.dl.sourceforge.net)... 2801:82:80ff:8000::3, 200.236.31.2
正在连接 ufpr.dl.sourceforge.net (ufpr.dl.sourceforge.net)|2801:82:80ff:8000::3|:80... 失败：网络不可达。
正在连接 ufpr.dl.sourceforge.net (ufpr.dl.sourceforge.net)|200.236.31.2|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 读取文件头错误 (连接被对方重设)。
放弃操作。

--2020-09-16 10:28:12--  http://internode.dl.sourceforge.net/sourceforge/corefonts/andale32.exe
正在解析主机 internode.dl.sourceforge.net (internode.dl.sourceforge.net)... 150.101.135.12
正在连接 internode.dl.sourceforge.net (internode.dl.sourceforge.net)|150.101.135.12|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 读取文件头错误 (连接被对方重设)。
放弃操作。

--2020-09-16 10:28:13--  http://voxel.dl.sourceforge.net/sourceforge/corefonts/andale32.exe
正在解析主机 voxel.dl.sourceforge.net (voxel.dl.sourceforge.net)... 失败：未知的名称或服务。
wget: 无法解析主机地址 “voxel.dl.sourceforge.net”
--2020-09-16 10:28:13--  http://kent.dl.sourceforge.net/sourceforge/corefonts/andale32.exe
正在解析主机 kent.dl.sourceforge.net (kent.dl.sourceforge.net)... 212.219.56.185
正在连接 kent.dl.sourceforge.net (kent.dl.sourceforge.net)|212.219.56.185|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 读取文件头错误 (连接被对方重设)。
放弃操作。

--2020-09-16 10:28:14--  http://downloads.sourceforge.net/corefonts/arialb32.exe
正在解析主机 downloads.sourceforge.net (downloads.sourceforge.net)... 216.105.38.13
正在连接 downloads.sourceforge.net (downloads.sourceforge.net)|216.105.38.13|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 读取文件头错误 (连接被对方重设)。
放弃操作。

--2020-09-16 10:28:14--  http://switch.dl.sourceforge.net/sourceforge/corefonts/arialb32.exe
正在解析主机 switch.dl.sourceforge.net (switch.dl.sourceforge.net)... 失败：未知的名称或服务。
wget: 无法解析主机地址 “switch.dl.sourceforge.net”
--2020-09-16 10:28:15--  http://dfn.dl.sourceforge.net/sourceforge/corefonts/arialb32.exe
正在解析主机 dfn.dl.sourceforge.net (dfn.dl.sourceforge.net)... 失败：未知的名称或服务。
wget: 无法解析主机地址 “dfn.dl.sourceforge.net”
--2020-09-16 10:28:15--  http://heanet.dl.sourceforge.net/sourceforge/corefonts/arialb32.exe
正在解析主机 heanet.dl.sourceforge.net (heanet.dl.sourceforge.net)... 2001:770:18:aa40::c101:c142
正在连接 heanet.dl.sourceforge.net (heanet.dl.sourceforge.net)|2001:770:18:aa40::c101:c142|:80... 失败：网络不可达。
--2020-09-16 10:28:15--  http://jaist.dl.sourceforge.net/sourceforge/corefonts/arialb32.exe
正在解析主机 jaist.dl.sourceforge.net (jaist.dl.sourceforge.net)... 2001:df0:2ed:feed::feed, 150.65.7.130
正在连接 jaist.dl.sourceforge.net (jaist.dl.sourceforge.net)|2001:df0:2ed:feed::feed|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 没有接收到数据。
放弃操作。

--2020-09-16 10:31:27--  http://nchc.dl.sourceforge.net/sourceforge/corefonts/arialb32.exe
正在解析主机 nchc.dl.sourceforge.net (nchc.dl.sourceforge.net)... 2001:e10:ffff:1f02::17, 140.110.96.69
正在连接 nchc.dl.sourceforge.net (nchc.dl.sourceforge.net)|2001:e10:ffff:1f02::17|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 没有接收到数据。
放弃操作。

--2020-09-16 10:34:37--  http://ufpr.dl.sourceforge.net/sourceforge/corefonts/arialb32.exe
正在解析主机 ufpr.dl.sourceforge.net (ufpr.dl.sourceforge.net)... 2801:82:80ff:8000::3, 200.236.31.2
正在连接 ufpr.dl.sourceforge.net (ufpr.dl.sourceforge.net)|2801:82:80ff:8000::3|:80... 失败：网络不可达。
正在连接 ufpr.dl.sourceforge.net (ufpr.dl.sourceforge.net)|200.236.31.2|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 读取文件头错误 (连接被对方重设)。
放弃操作。

--2020-09-16 10:34:38--  http://internode.dl.sourceforge.net/sourceforge/corefonts/arialb32.exe
正在解析主机 internode.dl.sourceforge.net (internode.dl.sourceforge.net)... 150.101.135.12
正在连接 internode.dl.sourceforge.net (internode.dl.sourceforge.net)|150.101.135.12|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 读取文件头错误 (连接被对方重设)。
放弃操作。

--2020-09-16 10:34:39--  http://voxel.dl.sourceforge.net/sourceforge/corefonts/arialb32.exe
正在解析主机 voxel.dl.sourceforge.net (voxel.dl.sourceforge.net)... 失败：未知的名称或服务。
wget: 无法解析主机地址 “voxel.dl.sourceforge.net”
--2020-09-16 10:34:39--  http://kent.dl.sourceforge.net/sourceforge/corefonts/arialb32.exe
正在解析主机 kent.dl.sourceforge.net (kent.dl.sourceforge.net)... 212.219.56.185
正在连接 kent.dl.sourceforge.net (kent.dl.sourceforge.net)|212.219.56.185|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 读取文件头错误 (连接被对方重设)。
放弃操作。

--2020-09-16 10:34:40--  http://downloads.sourceforge.net/corefonts/arial32.exe
正在解析主机 downloads.sourceforge.net (downloads.sourceforge.net)... 216.105.38.13
正在连接 downloads.sourceforge.net (downloads.sourceforge.net)|216.105.38.13|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 读取文件头错误 (连接被对方重设)。
放弃操作。

--2020-09-16 10:34:40--  http://switch.dl.sourceforge.net/sourceforge/corefonts/arial32.exe
正在解析主机 switch.dl.sourceforge.net (switch.dl.sourceforge.net)... 失败：未知的名称或服务。
wget: 无法解析主机地址 “switch.dl.sourceforge.net”
--2020-09-16 10:34:40--  http://dfn.dl.sourceforge.net/sourceforge/corefonts/arial32.exe
正在解析主机 dfn.dl.sourceforge.net (dfn.dl.sourceforge.net)... 失败：未知的名称或服务。
wget: 无法解析主机地址 “dfn.dl.sourceforge.net”
--2020-09-16 10:34:41--  http://heanet.dl.sourceforge.net/sourceforge/corefonts/arial32.exe
正在解析主机 heanet.dl.sourceforge.net (heanet.dl.sourceforge.net)... 2001:770:18:aa40::c101:c142
正在连接 heanet.dl.sourceforge.net (heanet.dl.sourceforge.net)|2001:770:18:aa40::c101:c142|:80... 失败：网络不可达。
--2020-09-16 10:34:41--  http://jaist.dl.sourceforge.net/sourceforge/corefonts/arial32.exe
正在解析主机 jaist.dl.sourceforge.net (jaist.dl.sourceforge.net)... 2001:df0:2ed:feed::feed, 150.65.7.130
正在连接 jaist.dl.sourceforge.net (jaist.dl.sourceforge.net)|2001:df0:2ed:feed::feed|:80... 失败：连接超时。
正在连接 jaist.dl.sourceforge.net (jaist.dl.sourceforge.net)|150.65.7.130|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 302 Found
位置：http://downloads.sourceforge.net/sourceforge/corefonts/arial32.exe?download&failedmirror=jaist.dl.sourceforge.net [跟随至新的 URL]
--2020-09-16 10:35:42--  http://downloads.sourceforge.net/sourceforge/corefonts/arial32.exe?download&failedmirror=jaist.dl.sourceforge.net
正在解析主机 downloads.sourceforge.net (downloads.sourceforge.net)... 216.105.38.13
正在连接 downloads.sourceforge.net (downloads.sourceforge.net)|216.105.38.13|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 读取文件头错误 (连接被对方重设)。
放弃操作。

--2020-09-16 10:35:42--  http://nchc.dl.sourceforge.net/sourceforge/corefonts/arial32.exe
正在解析主机 nchc.dl.sourceforge.net (nchc.dl.sourceforge.net)... 2001:e10:ffff:1f02::17, 140.110.96.69
正在连接 nchc.dl.sourceforge.net (nchc.dl.sourceforge.net)|2001:e10:ffff:1f02::17|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 没有接收到数据。
放弃操作。

--2020-09-16 10:38:55--  http://ufpr.dl.sourceforge.net/sourceforge/corefonts/arial32.exe
正在解析主机 ufpr.dl.sourceforge.net (ufpr.dl.sourceforge.net)... 2801:82:80ff:8000::3, 200.236.31.2
正在连接 ufpr.dl.sourceforge.net (ufpr.dl.sourceforge.net)|2801:82:80ff:8000::3|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 没有接收到数据。
放弃操作。

--2020-09-16 10:42:04--  http://internode.dl.sourceforge.net/sourceforge/corefonts/arial32.exe
正在解析主机 internode.dl.sourceforge.net (internode.dl.sourceforge.net)... 150.101.135.12
正在连接 internode.dl.sourceforge.net (internode.dl.sourceforge.net)|150.101.135.12|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 读取文件头错误 (连接被对方重设)。
放弃操作。

--2020-09-16 10:42:08--  http://voxel.dl.sourceforge.net/sourceforge/corefonts/arial32.exe
正在解析主机 voxel.dl.sourceforge.net (voxel.dl.sourceforge.net)... 失败：未知的名称或服务。
wget: 无法解析主机地址 “voxel.dl.sourceforge.net”
--2020-09-16 10:42:08--  http://kent.dl.sourceforge.net/sourceforge/corefonts/arial32.exe
正在解析主机 kent.dl.sourceforge.net (kent.dl.sourceforge.net)... 212.219.56.185
正在连接 kent.dl.sourceforge.net (kent.dl.sourceforge.net)|212.219.56.185|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 读取文件头错误 (连接被对方重设)。
放弃操作。

--2020-09-16 10:42:09--  http://downloads.sourceforge.net/corefonts/comic32.exe
正在解析主机 downloads.sourceforge.net (downloads.sourceforge.net)... 216.105.38.13
正在连接 downloads.sourceforge.net (downloads.sourceforge.net)|216.105.38.13|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 读取文件头错误 (连接被对方重设)。
放弃操作。

--2020-09-16 10:42:09--  http://switch.dl.sourceforge.net/sourceforge/corefonts/comic32.exe
正在解析主机 switch.dl.sourceforge.net (switch.dl.sourceforge.net)... 失败：未知的名称或服务。
wget: 无法解析主机地址 “switch.dl.sourceforge.net”
`

**Comment by xmuli** [comment]
这是与无法解析这个网址，你设置了代理？ 然后还是全局？ 或者修改或 sources.list？也有可能是你的 dns 解析被污染，常见就这集中错误（直接不是直接在商店下载？ 也无法安装成功，？商店的提示怎么说？）

**Comment by shengdexiang** [comment]
> 这是与无法解析这个网址，你设置了代理？ 然后还是全局？ 或者修改或 sources.list？也有可能是你的 dns 解析被污染，常见就这集中错误（直接不是直接在商店下载？ 也无法安装成功，？商店的提示怎么说？）
1. 没有设置代理 (我手动通过浏览器挂代理到sf能够下载这些字体)
2. sources.list 是系统默认值
```
> cat /etc/apt/sources.list
## Generated by deepin-installer
deb [by-hash=force] https://community-packages.deepin.com/deepin/ apricot main contrib non-free
```
3. 应用商店更新会很慢(估计中间过程跟终端升级安装一样吧), 最后还是提示失败(具体的提示信息不清楚, 因为没从商店更新过)

目前采用安装论坛坛友打的空包后解决了
```
> apt list --upgradable 
正在列表... 完成
com.qq.im.deepin/stable 9.3.2deepin9 i386 [可从该版本升级：9.3.2deepin4]
ttf-mscorefonts-installer/未知,未知 3.7 all [可从该版本升级：0.1-1debug1]
```

**Comment by xmuli** [comment]
恩恩， ~难道是服务器的问题~， 那就暂时关闭此问题的
