### ISSUE TITLE
[Feature Request] Auto Screen Rotation

### ISSUE THREAD

**Issue by chaim1221** [linuxdeepin/developer-center#1906]
## Describe the bug
Any tablet laptop should auto rotate when the screen is moved. However, Deepin does not perform this function, and updating the rotation works but is not a great solution.

## To Reproduce
1. Have a tablet laptop, e.g., Lenovo Yoga.
2. Rotate the screen 180 degrees.
3. Nothing happens!

## Expected behavior
See description.

### Distro & Version
Deepin 20 Beta.

### Additional context
[This thread](https://www.reddit.com/r/deepin/comments/bd4pbp/autorotate_on_deepin/) was opened on Reddit but did not seem to garner any responses.

**Comment by xmuli** [comment]
> 移动屏幕时，任何平板电脑笔记本电脑都应自动旋转。但是，Deepin不会执行此功能，并且更新轮换可以但不是一个很好的解决方案。

I don't think so，This function may be better on a tablet with a touch screen. It may be better when used in a notebook (the screen and keyboard directions are fixed), but it will be a relatively poor setting (the more economical solution is to set it manually)

**Comment by chaim1221** [comment]
Understood. And actually as it happens I'm not using that feature right now. But compare Ubuntu's default tablet setting (yes I know that's a bad word around here 😉 ).

Perhaps a shortcut? Windows has ctrl-alt-shift-{up,down} etc.

**Comment by scroom** [comment]
It would be great if Deepin supported AutoRotate. When I want to write something with the pen on my Thinkpad Yoga, for example, it is always a hindrance to manually adjust the rotation. Other DE do this better.

**Comment by meiyixiang** [comment]
36/5000 
Since we haven't done much development for tablet mode, there will be support for interactive scenarios for tablet mode in the future
