### ISSUE TITLE
[BUG]在线升级最新deepin20后，终端无法通过命令多开终端。

### ISSUE THREAD

**Issue by LittleTurtle2333** [linuxdeepin/developer-center#1907]
https://s1.ax1x.com/2020/09/10/wYphg1.png
https://s1.ax1x.com/2020/09/10/wYp24J.png
https://s1.ax1x.com/2020/09/10/wYp4jx.png

**Comment by LittleTurtle2333** [comment]
目前已回deepin-terminal=5.0.4.1-1，能正常多开

**Comment by xmuli** [comment]
那么，此问题就暂时关闭，请等待新的版本的修复，当然，可也可以体验一下 [deepin-terminal-gtk](https://github.com/linuxdeepin/deepin-terminal-gtk)

ps: 直接将图片拖到拖拽到此框中、markdown 或者 网页标签，都可以直接以图片方式预览
