### ISSUE TITLE
Bug: [File Manager] File copy progress not displayed

### ISSUE THREAD

**Issue by sayoojsamuel** [linuxdeepin/developer-center#1908]
## Description
The popup displaying the file copy progress animation is not poperly displayed.  Only a small portion of the top section is visible.

## Environments
* Distro: Arch Linux
* Kernel: Linux lightsaber 5.8.5-arch1-1 #1 SMP PREEMPT Thu, 27 Aug 2020 18:53:02 +0000 x86_64 GNU/Linux
* File Manager: dde-file-manager 1.8.2
* Deepin Version: Deepin 20 beta

## Screenshots
![image](https://user-images.githubusercontent.com/31436104/92996020-e4d54a80-f525-11ea-8ea2-4deb5aec0d4d.png)

**Comment by peeweep** [comment]
![image](https://user-images.githubusercontent.com/624223/147638224-28fdca6f-bbd4-4a96-963c-46a0133b795e.png)

This problem has been fixed on the latest version of Archlinux `community/deepin-file-manager 1:5.5.1-1`.
I will close it first.

If you still have problems, you can reopen this issue.
