### ISSUE TITLE
Deepin 20 Network Management Problem.

### ISSUE THREAD

**Issue by erickporto86** [linuxdeepin/developer-center#1910]
Deepin's network manager has a network management or DNS bug with high connection packet loss rates over Wi-Fi. In one of my tests installing Wicid and connecting it to my wifi network the internet speed is highly superior to deepin's network manager. Please fix this bug. My internet connection speed is 15 mb. My wifi driver its a QCA 6174. Researching the system I discovered that the geoclue causes this loss of connectivity in the wifi. Please fix this.

![Deepin wifi manager](https://user-images.githubusercontent.com/30264657/93009328-0d753880-f556-11ea-8c4b-fad25bc39938.gif)

Using deepin's network manager

![Wicd](https://user-images.githubusercontent.com/30264657/93009339-20880880-f556-11ea-8747-3ba446d36578.gif)

Using Wicd

Dear friend.

I discovered that it is only necessary to move the geoclue configurations. And modify wifi source as enable = false

sudo dedit /etc/geoclue/geoclue.conf 

![Screen Capture_deepin-editor_20200916100007](https://user-images.githubusercontent.com/30264657/93340836-c4e2a700-f803-11ea-9d42-8ec2d73332fd.png)

**Comment by gokhanyildirimlar** [comment]
I encounter unstable wireless network performance for a long time already. Thanks for the info, I am going to try Wicd in a day.
https://github.com/linuxdeepin/developer-center/issues/1678

**Comment by erickporto86** [comment]
> I encounter unstable wireless network performance for a long time already. Thanks for the info, I am going to try Wicd in a day.
> #1678


Dear friend.

I discovered that it is only necessary to move the geoclue configurations. And modify wifi source as enable = false


sudo dedit /etc/geoclue/geoclue.conf 


![Screen Capture_deepin-terminal_20200915180917](https://user-images.githubusercontent.com/30264657/93340412-29513680-f803-11ea-9800-2ccede4f04ea.png)

![Screen Capture_deepin-editor_20200916100007](https://user-images.githubusercontent.com/30264657/93340768-ab415f80-f803-11ea-830d-8a2eda62bc89.png)

**Comment by gokhanyildirimlar** [comment]
I will give it a try. I was testing by disabling Geoclue service since morning. Thanks for the huge help, @erickporto86. I was facing this from the very beginning of beta and this issue presents on UOS too. Also, lets tag @xmuli to pass this to appropriate team.

**Comment by erickporto86** [comment]
> Deepin's network manager has a network management or DNS bug with high connection packet loss rates over Wi-Fi. In one of my tests installing Wicid and connecting it to my wifi network the internet speed is highly superior to deepin's network manager. Please fix this bug. My internet connection speed is 15 mb. My wifi driver its a QCA 6174. Researching the system I discovered that the geoclue causes this loss of connectivity in the wifi. Please fix this.
> 
> ![Deepin wifi manager](https://user-images.githubusercontent.com/30264657/93009328-0d753880-f556-11ea-8c4b-fad25bc39938.gif)
> 
> Using deepin's network manager
> 
> ![Wicd](https://user-images.githubusercontent.com/30264657/93009339-20880880-f556-11ea-8747-3ba446d36578.gif)
> 
> Using Wicd
> 
> Dear friend.
> 
> I discovered that it is only necessary to move the geoclue configurations. And modify wifi source as enable = false
> 
> sudo dedit /etc/geoclue/geoclue.conf
> 
> ![Screen Capture_deepin-editor_20200916100007](https://user-images.githubusercontent.com/30264657/93340836-c4e2a700-f803-11ea-9d42-8ec2d73332fd.png)

@xmuli

**Comment by xmuli** [comment]
Thanks for your help

**Comment by peeweep** [comment]
https://gitlab.freedesktop.org/geoclue/geoclue/-/issues/129

**Comment by peeweep** [comment]
@erickporto86 @gokhanyildirimlar Do you still have this problem on the latest version of Deepin?

**Comment by gokhanyildirimlar** [comment]
> @erickporto86 @gokhanyildirimlar Do you still have this problem on the latest version of Deepin?

I don't use Deepin anymore but I wasn't experiencing something so dramatic with v20.1 or v20.2 if I remember correctly.

**Comment by peeweep** [comment]
> > @erickporto86 @gokhanyildirimlar Do you still have this problem on the latest version of Deepin?
> 
> I don't use Deepin anymore but I wasn't experiencing something so dramatic with v20.1 or v20.2 if I remember correctly.

Thanks for you feedback.
