### ISSUE TITLE
 [Feature Request] Allow importing / exporting VPN with extension (.ovpn)

### ISSUE THREAD

**Issue by wuniversales** [linuxdeepin/developer-center#1913]
Currently in deepin it only allows importing the vpn through a ".conf" file.

I have been able to verify that renaming any file ".ovpn" to ".conf", the ovpn import works correctly.

Why not allow import / export in both formats? (.conf / .ovpn)

**Comment by meiyixiang** [comment]
36/5000 
Your feedback has been recorded. I will confirm with the product why two formats of import/export cannot be supported

**Comment by meiyixiang** [comment]
Because different VPN types have different restrictions on suffix names, some are limited and some are not limited, so they are applicable to all of them. This is also to simplify operations for those who are unfamiliar with the system
