### ISSUE TITLE
希望dde-file-manager支持自定义标签

### ISSUE THREAD

**Issue by ggsddu4ever** [linuxdeepin/developer-center#1916]
就是目前显示“主目录”“图片”那个位置能自定义添加其它目录到导航标签。
另外：dde-file-manager仓库还不能提issues.

**Comment by ggsddu4ever** [comment]
找到添加自定义书签的功能了。

**Comment by xmuli** [comment]
> 另外：dde-file-manager仓库还不能提issues.

试了一下，可以提，忽略让到 developer-center 的字样即可，后面我会改一下模板的
