### ISSUE TITLE
Bug report 「缺陷报告」

### ISSUE THREAD

**Issue by Dziban-dev** [linuxdeepin/developer-center#1918]
Hi, my issue is, ever since last update v20(1002), i have not been able to start godot game engine (http://https://godotengine.org),  i have reported the issue to godot's official github, but just in case the problem is not related with them I'm reporting it here aswell.

Issue is, godot wont start at all, i tasted with many different versions of godot, and also i reinstalled v20(1002) from scratch.

to try and get more informations about why the program did not execute i tried to run it from command line:
$./godot_v3.2.264 

in this was the output:

Godot Engine v3.2.3.stable.official - https://godotengine.org
Input method doesn't support any styles
free(): invalid pointer
Aborted

$./godot_v3.2.2.64 --verbose
Godot Engine v3.2.3.stable.official - https://godotengine.org
XInput: Refreshing devices.
XInput: Using touch device: Virtual core pointer
Input method doesn't support any styles
free(): invalid pointer
Aborted

so i looked arround the web, to get more context about the "Input method doesn't support any styles" issue, it appears the problem might be related with libx11-dev. which I won't change because deepin uses libx11-dev 2:1.6.7.1-1+dde which i belive is a modified version of the 1.6.7.1-1 the ships with debian 10

**Comment by xmuli** [comment]
> so i looked arround the web, to get more context about the "Input method doesn't support any styles" issue, it appears the problem might be related with libx11-dev. which I won't change because deepin uses libx11-dev 2:1.6.7.1-1+dde which i belive is a modified version of the 1.6.7.1-1 the ships with debian 10

This may be what you are talking about. He has been pushed to fix it last week [# 116](https://gitlab.freedesktop.org/xorg/lib/libx11/-/issues/116)

**Comment by Dziban-dev** [comment]
> > so i looked arround the web, to get more context about the "Input method doesn't support any styles" issue, it appears the problem might be related with libx11-dev. which I won't change because deepin uses libx11-dev 2:1.6.7.1-1+dde which i belive is a modified version of the 1.6.7.1-1 the ships with debian 10
> 
> This may be what you are talking about. He has been pushed to fix it last week [# 116](https://gitlab.freedesktop.org/xorg/lib/libx11/-/issues/116)
 
issue fixed there was an update, and it updated libx11-dev Godot runs again in my system ! :D

https://ibb.co/4875Dt3
