### ISSUE TITLE
Start menu can't launch applications

### ISSUE THREAD

**Issue by KimHono** [linuxdeepin/developer-center#1919]
Hi!
I'm using the dock in  "Beautiful mode" and the start menu with wallpaper slideshow, as showed here:
https://www.deepin.org/wp-content/uploads/2020/09/01-1.png

Since recent update (mid-september 2020):

- The dock works well, and I can launch my docked applications.
- But the wallpaper slideshow shows useless icons... when I click on an application icon, nothing happens ! No application can be launch.

If I toggle the start menu to standard (https://www.deepin.org/wp-content/uploads/2017/07/1_en.jpg), anything works well : I can launch the menu's applications.

What's the problem with the start menu since the update ?

My configuration is:

- deepin-menu 5.0.1-3
- deepin-dock 5.2.0.14-1
- Linux Arch 5.8.9-arch2-1

**Comment by mitchellkrogza** [comment]
YES, latest version and I am now unable to launch ANY application other than what I had already added to my toolbar. Sad to say but Deepin is going down the tubes with NOTHING ever tested !!! I use my computer for actual work but now have to look for another desktop as I find myself wasting entire days trying to fix things after every update.

**Comment by KimHono** [comment]
I'm closing this issue : has been addressed in latest update of deepin-wm 1.9.38-5 or deepin-launcher 5.3.0.16-1.
BTW the ticket was also opened here : [https://github.com/linuxdeepin/dde-launcher/issues/72](url)
