### ISSUE TITLE
File or Folder property behaviour

### ISSUE THREAD

**Issue by darkcyber** [linuxdeepin/developer-center#192]
Hi,

When I select few folder and file let's assume 5 at all and right click and property, it will show dialog for each file or folder. It's nice behaviour since my window view can handle it. 

But the bad behaviour is when I select many file or folder, and right click property, it will show dialog for each file or folder.

Imagine if I select 100 or more file or folder. It will show 100 property dialog too which is bad behaviour.

So maybe it will be good if Deepin have different behaviour when user right click property in many file or folder.

Thanks in advance.

**Comment by hualet** [comment]
@dragondjf @manateelazycat

**Comment by funilrys** [comment]
Same issue here.

**Comment by darkcyber** [comment]
thanks @hualet @funilrys for comment, hope any patch for this.

**Comment by darkcyber** [comment]
what do you think @dragondjf @manateelazycat , is this bug need to patch for 15.4?

**Comment by justforlxz** [comment]
This question has not been answered for too long and will be closed. If there is a need to continue the discussion, it will be reopened.
