### ISSUE TITLE
DDE Control Center crashes in display menu

### ISSUE THREAD

**Issue by benpaulsen-qut** [linuxdeepin/developer-center#1921]
In Deepin control center 5.3.0.24-1 running on Arch Linux (latest), accessing the display menu will instantly crash the application. Running it through the terminal shows the following error message when the crash occurs:

(process:3815): GLib-GIO-ERROR **: 17:04:22.335: Settings schema 'com.deepin.dde.control-center' does not contain a key named 'brightness-enable'

I'm happy to provide further information if needed.

**Comment by Asuranis** [comment]
Hi, I have the same problem on fresh Arch install

**Comment by ch00pa** [comment]
Hello, same bug.

**Comment by TheTBO** [comment]
I have the same issue with display and power menus. 
Also on arch.

**Comment by breizh2944** [comment]
Hi, seems to have been solved in a recent update.
