### ISSUE TITLE
建议：在输入管理员密码后回车不要默认设成显示密码

### ISSUE THREAD

**Issue by asd-a** [linuxdeepin/developer-center#1923]
每次输完密码习惯性回车，然后就被后面的人看见了。。。

**Comment by xmuli** [comment]
什么操作？ 输入密码后显示？

**Comment by asd-a** [comment]
就是在输入后，按回车它默认不是确认，它默认是把密码显示出来
——Archlinux 5.8.10

**Comment by xmuli** [comment]
已经有人在跟进此问题

**Comment by peeweep** [comment]
最新版本的Deepin 已经修复, 如果仍然有问题，可以重新打开这个issue
