### ISSUE TITLE
[Support Reuqest] 建议地址栏参考windows

### ISSUE THREAD

**Issue by oucaijun** [linuxdeepin/developer-center#1925]
建议地址栏参考windows的方式，平时是面包屑形式，当鼠标点击地址栏最右端时，可以获取当前完整路径，可以执行拷贝、复制、粘贴、修改。这可以有效提高用户工作效率。

**Comment by xmuli** [comment]
你点击一下，就是此路径输入框的样式；且为啥要一样？有自己的特点不就挺好？

**Comment by Ernest-su** [comment]
地址栏可以使用CTRL+L 转为完整路径输入框，以获取当前完整路径，可以执行拷贝、复制、粘贴、修改
