### ISSUE TITLE
Old MacBook touchpad maps wrong Deepin 20

### ISSUE THREAD

**Issue by chucksmith** [linuxdeepin/developer-center#1929]
I freshly installed Deepin 20 on my Late 2005 MacBook with 3 GB RAM and my built-in trackpad is acting strangely:

- moving left-right is mapped to up-down
- moving up-down is mapped to scroll up-down
- touchpad click is mapped to move right (MacBooks only have one touchpad button)

I’m guessing I need the right drivers, but as I’m relatively new to Linux, I have no idea where to start (just ran Xubuntu for a few months before this). Any idea on how I could start troubleshooting this?

Here is output from xinput to help with figuring out the issue (I have a wireless Logitech keyboard/trackpad connected, so I can use my computer, thus the reason for those entries here):

$ xinput list
⎡ Virtual core pointer                          id=2    [master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
⎜   ↳ Logitech Performance MX                   id=10   [slave  pointer  (2)]
⎜   ↳ Logitech K400                             id=11   [slave  pointer  (2)]
⎜   ↳ Apple Computer Apple Internal Keyboard / Trackpad id=13   [slave  pointer  (2)]
⎣ Virtual core keyboard                         id=3    [master keyboard (2)]
    ↳ Virtual core XTEST keyboard               id=5    [slave  keyboard (3)]
    ↳ Power Button                              id=6    [slave  keyboard (3)]
    ↳ Video Bus                                 id=7    [slave  keyboard (3)]
    ↳ Power Button                              id=8    [slave  keyboard (3)]
    ↳ Sleep Button                              id=9    [slave  keyboard (3)]
    ↳ Apple Computer Apple Internal Keyboard / Trackpad id=12   [slave  keyboard (3)]
    ↳ Apple Computer Apple Internal Keyboard / Trackpad id=14   [slave  keyboard (3)]
    ↳ Apple Computer, Inc. IR Receiver          id=15   [slave  keyboard (3)]
    ↳ Logitech K400                             id=16   [slave  keyboard (3)]
$ xinput list-props 13
Device 'Apple Computer Apple Internal Keyboard / Trackpad':
        Device Enabled (158):   1
        Coordinate Transformation Matrix (160): 1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
        libinput Natural Scrolling Enabled (295):       1
        libinput Natural Scrolling Enabled Default (296):       0
        libinput Scroll Methods Available (297):        0, 0, 1
        libinput Scroll Method Enabled (298):   0, 0, 0
        libinput Scroll Method Enabled Default (299):   0, 0, 0
        libinput Button Scrolling Button (300): 2
        libinput Button Scrolling Button Default (301): 2
        libinput Middle Emulation Enabled (302):        0
        libinput Middle Emulation Enabled Default (303):        0
        libinput Accel Speed (304):     0.333333
        libinput Accel Speed Default (305):     0.000000
        libinput Accel Profiles Available (306):        1, 1
        libinput Accel Profile Enabled (307):   1, 0
        libinput Accel Profile Enabled Default (308):   1, 0
        libinput Left Handed Enabled (309):     0
        libinput Left Handed Enabled Default (310):     0
        libinput Send Events Modes Available (280):     1, 0
        libinput Send Events Mode Enabled (281):        0, 0
        libinput Send Events Mode Enabled Default (282):        0, 0
        Device Node (283):      "/dev/input/event7"
        Device Product ID (284):        1452, 539
        libinput Drag Lock Buttons (311):       <no items>
        libinput Horizontal Scroll Enabled (312):       1

**Comment by b-rand** [comment]
Any update on this?

**Comment by KDel87** [comment]
I'd also like to add to this, that my Late 2013 Macbook Pro Retina 13" is also having the same issue. 

I'd love to get Deepin installed again on there, but the latest version of Deepin broke my touchpad drivers. :(

**Comment by chucksmith** [comment]
Do I need to provide more information? This seems to be a bug affecting all MacBooks. My mouse recently broke so now my Deepin box is practically useless. Any help would be appreciated... it's been a month now. :(

**Comment by KDel87** [comment]
I was about to ask if there were any updates, but you've answered that before I asked it. 

Hopefully it can get fixed soon or I'll have to go back to Ubuntu for the time being.

**Comment by rechandi** [comment]
I also have the same problem. Old Macbook Unibody 2009  8Gb Ram . 

Installed Deepin 20 beta, and it worked flawlessly. 

Later on, when it was available,  updated to Deepin 20 and as other people mentioned, the trackpad looses it's horizontal movement. Now if you connect an external mouse, it works now left and right plus up and down. But, the clicking on items on the desktop is erratic, the cursor gets stuck on images that don't make sense and some areas can't be clicked. So something was done to the mouse/trackpad driver, if I rollback to the beta version, trackpad and mouse works fine. So it should be fixable.

**Comment by rvaraujo** [comment]
I also have the same problem on a macbook pro late 2013.
Has any update about this issue?

**Comment by Umfs** [comment]
Same problem with 2015 MacBook Pro 13inch

**Comment by ggkameleon** [comment]
Hi ! Same on Deepin 20.1 the last update on my Macbook core 2 duo 2.84ghz Peyrin .
I have test to install Fusima, Xdtool, Touchegg but nothing the trackpad doesn't work only up & down ??? 
They had a solution ? 
Thanks

**Comment by dietrest** [comment]
Same here on MacbookPro 8.1

**Comment by ggkameleon** [comment]
I don't understand why doesn't work because it work fine on Ubuntu 20.04..
But test with old kernel 5.3. How do it ? 
Thanks

**Comment by dietrest** [comment]
just do in terminal:
sudo apt install linux-image-5.3.0-3-amd64-unsigned  linux-headers-5.3.0-3-amd64

**Comment by ggkameleon** [comment]
> just do in terminal:
> sudo apt install linux-image-5.3.0-3-amd64-unsigned linux-headers-5.3.0-3-amd64
> 
> and then on reboot choose deepin advanced options in grub menue. I hope i have remembered right. the normal deepin grub menu item will point to the newest kernel. So you have to choose the old 5.3.0...... manually.

Thank you very much. I had just receive my new SSD and tomorrow the optical bay, great I test in this SSD the Ubuntu 20.04 with Catalina Theme and see if it work more great than Deepin.. But I like so much deepin... 
Have a good day

**Comment by ggkameleon** [comment]
> just do in terminal:
> sudo apt install linux-image-5.3.0-3-amd64-unsigned linux-headers-5.3.0-3-amd64
> 
> and then on reboot choose deepin advanced options in grub menue. I hope i have remembered right. the normal deepin grub menu item will point to the newest kernel. So you have to choose the old 5.3.0...... manually.

Hi ! Yes it work too 😊   I can use the Trackpad great. but there is no problem to use an old Kernel. Thank you. Have a good day

**Comment by KDel87** [comment]
> just do in terminal:
> sudo apt install linux-image-5.3.0-3-amd64-unsigned linux-headers-5.3.0-3-amd64
> 
> and then on reboot choose deepin advanced options in grub menue. I hope i have remembered right. the normal deepin grub menu item will point to the newest kernel. So you have to choose the old 5.3.0...... manually.

Amazing! You're a lifesaver. Thank you so much! :)

**Comment by Dash-L** [comment]
Wow, I've been searching for this issue for a long time, it's happening to me on void linux with a mid 2015 Macbook Pro on linux5.13.18 and void doesn't package the 5.3 kernel, at least as far as I can tell. Has anyone else found a different fix?

**Comment by disburden** [comment]
这个问题没有人跟进一下吗？既然5.3内核能用，应该比较容易找到问题。
早点解决一下，不然好多mbp用户因为这个问题跑去装ubuntu了。

**Comment by disburden** [comment]
1年多过去了,怎么这个小问题一直没人解决啊?
网络上倒是有一些自己从旧的5.3.xx内核拷出驱动,然后自己编译内核的方法,但都说的不详细,对我们小白来说风险很大,有没哪位好心人写个比较完整的教程,让我能愉快的用上mbp.谢谢!

**Comment by rbouma** [comment]
Same problem kernel 5.3 can't be installed.

**Comment by KDel87** [comment]
I'm just going back to Ubuntu. This is silly. The Kernel is so out of date, Deepin is only just updating to a version that's being left by other distros. 

The app store is horribly organised and lacking proper translation. I get it, it's the free version of UOS, a Chinese commercial OS, it's not designed for Western users, but this is just ridiculous at this point. 

It's a shame Deepin, you could've been so good.

**Comment by rbouma** [comment]
@KDel87 @Dash-L  I tried Zorin OS today is pretty good, check: https://zorin.com/os/

**Comment by peeweep** [comment]
We will fix this issue (Apple BCM5974 touchpad) around March 2022 :)

**Comment by disburden** [comment]
> I fixed this problem (Apple BCM5974 touchpad) on my macbook pro 2015 early, the solution will be pushed around in February 2022.

内牛满面啊T_T

**Comment by KDel87** [comment]
> I fixed this problem (Apple BCM5974 touchpad) on my macbook pro 2015 early, the solution will be pushed around in February 2022.

That's amazing thank you so much! <3

**Comment by vabaly** [comment]
> I fixed this problem (Apple BCM5974 touchpad) on my macbook pro 2015 early, the solution will be pushed around in February 2022.

能讲下为什么吗？我理解 deepin 应该是沿用 debian 带的那些驱动，然后自己再新增一些驱动支持？我使用 deiban 是正常的

**Comment by peeweep** [comment]
> > I fixed this problem (Apple BCM5974 touchpad) on my macbook pro 2015 early, the solution will be pushed around in February 2022.
> 
> 能讲下为什么吗？我理解 deepin 应该是沿用 debian 带的那些驱动，然后自己再新增一些驱动支持？我使用 debian 是正常的

目前的结论是因为 BCM5974 驱动加载注册晚于usb 注册, 没有正确probe，我们先把驱动buildin 了

**Comment by disburden** [comment]
听说这周要发布20.4,这个版本能不能把这个修复了?没必要非要等到二月吧

**Comment by peeweep** [comment]
> 听说这周要发布20.4,这个版本能不能把这个修复了?没必要非要等到二月吧

我们仓库已经冻结了，需要等今天发布完20.4 才可以开始集成测试

**Comment by disburden** [comment]
为了笔记本能用,我几乎每天都要来看一下这个bug更新了没有
昨天发现系统有更新,加上上面有人说二月份修复,我以为昨晚那个版本肯定修复这个问题了
结果还是没修复

我就很不理解你们的产品经理是怎么安排的,这个bug基本上也就比会导致电脑会自爆,cpu冒烟稍差一点,属于比较重大的bug,因为这个bug电脑根本就用不了,上面不是很多人因为这个bug改成其他系统了吗?而且修复又不难,为啥不早点修复呢?这触控板能用就是能用,不能用就不能用,都改好了还要发几个月时间测试吗?

哎呦呦...脑阔疼
哎呦呦...心绞痛...不行了....

**Comment by dietrest** [comment]
@peeweep 
Any information about your Fix ?

**Comment by peeweep** [comment]
> @peeweep Any information about your Fix ?

Should be available in next month's kernel update.

**Comment by dietrest** [comment]
great news!

**Comment by dietrest** [comment]
Installing Liqurix Kernel should fix it too. I had the same Trouble in Nitrux. And there the Liquorix Kernel does fix the issue. But dont know wether one runs in other Troubles lateron.

**Comment by disburden** [comment]
@peeweep 有没有可以测试的版本我先试用一下?

**Comment by peeweep** [comment]
> @peeweep 有没有可以测试的版本我先试用一下?

可以给你编一个呀，不过马上就进测试PPA了，也用不了几天。

**Comment by disburden** [comment]
已经3月了,我不懂什么测试PPA
能试用了说一下

**Comment by peeweep** [comment]
> 已经3月了,我不懂什么测试PPA 能试用了说一下

上周已经发你邮箱了

**Comment by disburden** [comment]
我是电子邮件重度用户,基本每天都会翻邮箱.
但是找了一整天了,所有垃圾箱也都翻了,实在找不到邮件:(
能说说准确一点的发布更新的时间吗?不要2月,3月,马上,快了一类的.
我每次看到烹饪教程说加适量的盐,少量的糖我就立马崩溃.

**Comment by peeweep** [comment]
> 我是电子邮件重度用户,基本每天都会翻邮箱.
> 但是找了一整天了,所有垃圾箱也都翻了,实在找不到邮件:(
> 能说说准确一点的发布更新的时间吗?不要2月,3月,马上,快了一类的.
> 我每次看到烹饪教程说加适量的盐,少量的糖我就立马崩溃.
> 
> 

发到你Gmail 了，如果没有收到可以给我发邮件，我会在邮件里回复你。mailto:peeweep@0x0.ee

**Comment by disburden** [comment]
@peeweep 非常感谢!终于可以愉快的躺在被窝里玩电脑了.
不过有个问题可能需要解决一下,就是更新了心内核之后,笔记本自带的无线网卡不能用了,识别不到
还好我有个空闲的无线网卡.乌拉!!!

对了,我是Late 2013 Macbook Pro Retina 13"

**Comment by disburden** [comment]
@peeweep  无线网卡我也搞定了，直接用dkms命令把5.10...内核下的驱动装到新的内核里.完美!!!

小鸟在前面带路,风儿吹向我们.......

**Comment by peeweep** [comment]
> @peeweep  无线网卡我也搞定了，直接用dkms命令把5.10...内核下的驱动装到新的内核里.完美!!!
> 
> 小鸟在前面带路,风儿吹向我们.......

听描述像是你没装对内核头文件的包，我回头也看一下吧。

**Comment by peeweep** [comment]
Fixed since 5.15.24-1 kernel, now available on [dde-apricot](https://proposed-packages.deepin.com/dde-apricot)

Edit /etc/apt/sources.list:
```
deb https://proposed-packages.deepin.com/dde-apricot unstable main
```
Install kernel
```
sudo apt install linux-headers-deepin-stable-amd64 linux-image-deepin-stable-amd64
```

I will close this issue first, if there is any problem, you can continue to discuss.

**Comment by arch-user-france1** [comment]
> I fixed this problem (Apple BCM5974 touchpad) on my macbook pro 2015 early, the solution will be pushed around in February 2022.

Still not working on mine

**Comment by peeweep** [comment]
> > I fixed this problem (Apple BCM5974 touchpad) on my macbook pro 2015 early, the solution will be pushed around in February 2022.
> 
> 
> 
> Still not working on mine
> 
> It's completely messed up - I can't even install deepin, must use an external mouse.
> 
> I also noticed that the GUI breaks if I touch the touchpag and the system would have to be restrarted.

What's your touchpad chipset model?

**Comment by BLumia** [comment]
Hi @arch-user-france1, please consider create a new issue to report so we can better tracking your issue. Thanks!

**Comment by arch-user-france1** [comment]
> > > I fixed this problem (Apple BCM5974 touchpad) on my macbook pro 2015 early, the solution will be pushed around in February 2022.
> > 
> > 
> > Still not working on mine
> > It's completely messed up - I can't even install deepin, must use an external mouse.
> > I also noticed that the GUI breaks if I touch the touchpag and the system would have to be restrarted.
> 
> What's your touchpad chipset model?

I found out that upgrading to kernel 5.15 fixes it. 
The booting with kernel version 1.15 option does not work on the installation media - it doesn't find the kernel, probably missing.

**Comment by Thee-sen-programmer256** [comment]
> 

am having issues, when i run the command they bring this "apt: invalid flag: install" ,   dont know what i can do

**Comment by Thee-sen-programmer256** [comment]
> 

pleas eshare that beta version with me

**Comment by peeweep** [comment]
@Thee-sen-programmer256 Can't understand what you're saying.

**Comment by BLumia** [comment]
For people who have similar issues, please **create a new issue** so we can better track these issues and get it resolved.
