### ISSUE TITLE
No background

### ISSUE THREAD

**Issue by vinipachecov** [linuxdeepin/developer-center#193]
Hi there, I've just intalled deepin Desktop Environment 15.04 in my Archlinux (latest version 03 march) and somehow it doesn't have the wallpaper tab so I can change the wallpaper.
I've installed the wallpaper package for deepin, but somehow it doesn't have the tab. Also I can't open the file manager through the google chrome. How can I proceed?

I loved your Desktop Environment Design by the way. Keep it up with the good work!

![screenshot_2017-03-11_16-52-13](https://cloud.githubusercontent.com/assets/2838834/23826457/5601c28a-067b-11e7-8052-d48d1def544d.png)

**Comment by sonald** [comment]
@vinipachecov what is your video card ? does pressing super+s pops up multitasking mode like below?
![20170313085050](https://cloud.githubusercontent.com/assets/924334/23837882/36ac0972-07ca-11e7-924d-fd55ba9ea1f8.png)

**Comment by felixonmars** [comment]
Please try to right click on the desktop to set wallpaper with latest deepin-desktop 4.0.4-2.

**Comment by gustavodlima** [comment]
@felixonmars Update is not available yet. Will you provide it today yet? I would be glad to test it.

**Comment by vinipachecov** [comment]
My video card is Seymour [Radeon HD 6400M/7400M Series]
![deepinscreenshot20170317210734](https://cloud.githubusercontent.com/assets/2838834/24063013/c3280368-0b55-11e7-9a36-86e0d04cf4ee.png)

**Comment by sonald** [comment]
@vinipachecov does super+s shows blurred background ?

**Comment by vinipachecov** [comment]
@sonald  It freezes the screen forever and a reboot is needed.

**Comment by funilrys** [comment]
@vinipachecov Do you use [catalyst](https://wiki.archlinux.org/index.php/AMD_Catalyst) or [ATI](https://wiki.archlinux.org/index.php/ATI)?

**Comment by sonald** [comment]
@vinipachecov This happens with radeon driver and should be fixed by deepin-mutter 3.20.12 and up.
