### ISSUE TITLE
Bug report: "VERSION_CODENAME" field absent in os-release file

### ISSUE THREAD

**Issue by iamhyc** [linuxdeepin/developer-center#1931]
Until Deepin v20 (1003), `lsb_release -a` would tell `n/a` for "Codename" section.

But actually, it should output **"apricot"** for Deepin v20, where `/usr/lib/os-release` file is to blame for the absence of "VERSION_CODENAME" field.

This section may be helpful when someone (saying a friend of mine :) tries `add-apt-repository` on Deepin, but finds confusing "No template for Deepin/n/a" and wonders what's "/n/a" for.

@hualet @zccrs

**Comment by xmuli** [comment]
@felixonmars   Maybe he can help you explain.

**Comment by peeweep** [comment]
You can't use add-apt-repository to add ubuntu repositories on Deepin, we are based on Debian.

Is there any other use for VERSION_CODENAME?

**Comment by iamhyc** [comment]
> You can't use add-apt-repository to add ubuntu repositories on Deepin, we are based on Debian.
> 
> Is there any other use for VERSION_CODENAME?

As what I have claimed, someone would like to try for a luck and found the confusing "/n/a" postfix after "Deepin".

Not sure what is the codename for v20.3, but back in 2020, you did have "apricot" as the codename for the repo.

**Comment by peeweep** [comment]
> VERSION_CODENAME

Yes, apricot is also the codename of v20.3 now. I want to know if there are other apps that read VERSION_CODENAME, if not, there is no need to add it.

**Comment by iamhyc** [comment]
> > VERSION_CODENAME
> 
> Yes, apricot is also the codename of v20.3 now. I want to know if there are other apps that read VERSION_CODENAME, if not, there is no need to add it.

Not apps, but third-party repos do. For example, nodejs, https://github.com/nodesource/distributions/issues/638.

The current solution now is still to fake yourself as Debian10.

**Comment by peeweep** [comment]
正在处理
```
$ lsb_release -c -s
apricot
```

**Comment by iamhyc** [comment]
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Deepin
Description:    Deepin 20.4
Release:        20.4
Codename:       apricot
```

v20.4 已确认修复，辛苦。
