### ISSUE TITLE
When will deepin-desktop-environment be released for translation in transifex ?

### ISSUE THREAD

**Issue by roxfr** [linuxdeepin/developer-center#1934]
Hi,
When will deepin-desktop-environment be released for translation in transifex ?
Regards,
Roxf

<a href="https://ibb.co/jbGNLhq"><img src="https://i.ibb.co/dj6TQBX/Transifex-deepin-desktop-environment-not-accessible-for-translation.jpg" alt="Transifex-deepin-desktop-environment-not-accessible-for-translation" border="0"></a>

**Comment by xmuli** [comment]
It was here a long time ago. [linuxdeepin](https://www.transifex.com/linuxdeepin/)

**Comment by roxfr** [comment]
Ok thanks but Deepin Log Viewer : rpm-euler--deepin-log-viewer ; Deepin Desktop Environment : klu--dde-polkit-agent, klu--dde-daemonpot, klu--dde-session-ui and pgv--dde-control-center are not accessible for translation in Transiflex.
Is it possible to release them in order to translate them ?

**Comment by xmuli** [comment]
Some projects may not be open access for a while.
