### ISSUE TITLE
Nepali Keyboard Layout (Out Dated) 

### ISSUE THREAD

**Issue by sarojpoudel33** [linuxdeepin/developer-center#1936]
Please Provide latest romanized keyboard layout

**Comment by meiyixiang** [comment]
ok

**Comment by meiyixiang** [comment]
This problem has been recorded and we will synchronize the upstream keyboard layout as soon as possible

**Comment by GeniusMilk** [comment]
> 
@sarojpoudel33  
Hopefully this link will solve your problem.

 [How to switch between Nepali and English keyboard layouts in Linux](https://voidash.github.io/blog/posts/2022/switching-keyboard-layouts-in-linux/)
