### ISSUE TITLE
 Take out its changes when I turn off my screen

### ISSUE THREAD

**Issue by Taz6969** [linuxdeepin/developer-center#1938]
Hello I am writing to you because when I listen to the music I cannot turn off the screen of my computer, otherwise the music cuts. I have 2 screens that of my PC connected in DP and a TV screen in HDMI.
 I select in the advanced Sound parameters "Line out" for my speakers connected to the pc but as soon as I turn off the computer screen the sound output switches to the HDMI and thus cuts the music.
[https://zupimages.net/up/20/41/i2s5.png](url)
 Thank you advanced

**Comment by xmuli** [comment]
repeatable
