### ISSUE TITLE
需求：DSpinnerLegacy

### ISSUE THREAD

**Issue by SuperEndermanSM** [linuxdeepin/developer-center#1939]
dtkwidget关闭了Issue，因此在此报告
新的DSpinner在多处使用的时候颜色比较单一，并不好看
希望可以重新添加旧式的Spinner，三种颜色的

Please do not continue feedback here, Due to model changes, please report errors/suggestions in their respective warehouses; please refer to [Instructions for raising issues](https://github.com/linuxdeepin/developer-center/wiki/Instructions-for-raising-issues)

If you don’t know the type of your problem, please give feedback here.

---

请勿在此继续进行反馈，由于模式的变更，请去各自仓库中报告的错误/建议；请参阅  [提-issues-指南说明](https://github.com/linuxdeepin/developer-center/wiki/%E6%8F%90-issues-%E6%8C%87%E5%8D%97%E8%AF%B4%E6%98%8E)

如果你不知道你的问题是哪一类，请就在此处反馈。

**Comment by xmuli** [comment]
@kegechen  或者他能够回复你此 DTK 的问题.

**Comment by SuperEndermanSM** [comment]
等待进一步回复
希望告知dtk三件套不开放issue的原因

**Comment by xmuli** [comment]
> 等待进一步回复

问了一下, 好像现在变更为活动色的了, 新的设计(设计如此)


> 希望告知dtk三件套不开放issue的原因

看了一下, 只有 dtkwidget 没有开放 已经打开了, 以前没开原因未知.

`qt5integration` `dtkgui` `dtkwidget` `dtkcore`  都是开的了

**Comment by SuperEndermanSM** [comment]
> > 等待进一步回复
> 
> 问了一下, 好像现在变更为活动色的了, 新的设计(设计如此)
> 
> > 希望告知dtk三件套不开放issue的原因
> 
> 看了一下, 只有 dtkwidget 没有开放, 刚已打开了, 以前没开原因未知.
> 
> `qt5integration` `dtkgui` `dtkwidget` `dtkcore` 现在都是开的了

非常感谢
