### ISSUE TITLE
Sound Suggestion「声音建议」

### ISSUE THREAD

**Issue by martinlindelof** [linuxdeepin/developer-center#1942]
Hello, and Thank You! 您好，谢谢！

I have several sound inputs and outputs. Speakers, Headphones and Yeti Mic/Headphone jack.
+several outputs for HDMI Displayports (unused)
**See Image2.**

Switching sound output requires going into Control Center.
What would be nice is able to hide/show certain sound outputs for the System Tray sound menu.
**See Image 1.**

Suggestion 建议
In Control Center, Sound Advanced settings, Output.
Ability to Show some outputs for Sound in System Tray menu.

祝你今天愉快:)

Image 1, Sound Icon Menu in System Tray.
![Screen Capture_select-area_20201008085044](https://user-images.githubusercontent.com/156772/95437399-35896900-0955-11eb-943f-283487c54ffd.jpg)

Image2, Control Center, Sound settings. Multiple outputs.
![Screen Capture_select-area_20201008084929](https://user-images.githubusercontent.com/156772/95437419-391cf000-0955-11eb-9f53-1ec752fc9ea8.jpg)

**Comment by meiyixiang** [comment]
It is now supported
