### ISSUE TITLE
dwidget 「功能需求」 更好的DAboutDialog

### ISSUE THREAD

**Issue by shenmo7192** [linuxdeepin/developer-center#1943]
目前的DAboutDialog仅能满足深度系列应用的需要，对于第三方Dtk应用的需求，就显得不够了
做一下对比

这是自带的深度文件管理器
![图片](https://user-images.githubusercontent.com/47873776/95655728-e2bdd600-0b3b-11eb-817a-aa296ce767c2.png)
显然，对于深度自带应用来说，这已经够了

但是对于第三方还是不太能施展开
例子
![图片](https://user-images.githubusercontent.com/47873776/95655746-0254fe80-0b3c-11eb-8ed4-e1e5d4cfe02e.png)

这是一个第三方Dtk应用，使用了qt原生做About
![图片](https://user-images.githubusercontent.com/47873776/95655708-cf126f80-0b3b-11eb-996e-746e2a58d306.png)

显然，如果dtk原生可以做到更强大的about dialog是更好的事情
希望可以improve下，比如可以添加分页或者按钮

**Comment by xmuli** [comment]
@kegechen ,这个或许能够和舒老师反馈一下, 那样如果 dtk 能够加上的话~, 这样或许会比较方便星火商店的第三方开发者

**Comment by kegechen** [comment]
可以写一个dtk应用， 该应用仅仅就是显示一个AboutDialog, 接收一些命令行参数， 这样就可以通过startprocess传入需要显示内容的参数，show一个dtk的aboutdialog

**Comment by zccrs** [comment]
> 可以写一个dtk应用， 该应用仅仅就是显示一个AboutDialog, 接收一些命令行参数， 这样就可以通过startprocess传入需要显示内容的参数，show一个dtk的aboutdialog

这样会引入很多新的问题，比如Dialog类型的窗口窗口一般是需要“模态”状态，如果aboutdialog是一个命令提供的，那模态实现起来就很麻烦。而且还得考虑调用方的主题风格，比如调用方当期是暗色模式，还有与调用方保持一样的字体设置，这样考虑起来，要加的参数就很多。

**Comment by zccrs** [comment]
如果对AboutDialog有比较大的扩展或者是自定义的需要，可以直接基于 DDialog，这样可以完全控制对话框中的内容，来满足各个应用各不相同的需求。对于封装好的DAboutDialog，我们不希望把它做的太复杂，而且今后dtkwidget会偏向于仅维护，要尽量避免接口新增，所以此建议无法接纳，这个issue就关闭了。另外很感谢你的反馈，今年我们也会推出更灵活的UI开发的方式，它应该能满足你的想法。

**Comment by zccrs** [comment]
![image](https://user-images.githubusercontent.com/13449038/155488677-a726f437-af6a-483d-bb5e-3ca80675dadc.png)

针对这个场景可以提一些具体的建议，比如现在是哪个地方没有满足，看样子是和DTK应用的差不多。
