### ISSUE TITLE
[Arch] Window effects broken since last update

### ISSUE THREAD

**Issue by breizh2944** [linuxdeepin/developer-center#1945]
Hi,

On my setup (Arch), Window effects are broken since last update I received (which included kwin update : 5.20.0-1 -- is this related ?).

I cannot enable the feature : if I try to toggle it on, the screen is blinking but it stays without window effects.

Have you noticed the same issue ?

Thank you.

**Comment by felixonmars** [comment]
![2020-10-16-035350-5639ba](https://user-images.githubusercontent.com/1006477/96179328-4cd2e280-0f63-11eb-967d-7a28e53b5db7.png)

Same here.

**Comment by felixonmars** [comment]
@breizh2944 For now please try to remove `deepin-kwin` and install `deepin-wm` & `deepin-wm` instead.

**Comment by breizh2944** [comment]
OK thank you - I switched to deepin-wm "workaround" as advised.
In this case, I have no Window effect option, which is normal I suppose ?
Transparency is present, but no rounded corner and no option to set transparency level.

PS: The good thing is that multitask view is working with deepin-wn :)

**Comment by felixonmars** [comment]
> OK thank you - I switched to deepin-wm "workaround" as advised.
> In this case, I have no Window effect option, which is normal I suppose ?
> Transparency is present, but no rounded corner and no option to set transparency level.
> 
> PS: The good thing is that multitask view is working with deepin-wm :)

You can try `deepin-wm --replace` to enable window effect, but unfortunately I don't know how to make it persistent. Btw also deepin-dock has rounded corners with deepin-wm.

**Comment by xmuli** [comment]
> , but no rounded corner and no option to set transparency level.

To correct that, small rounded corners and right angles are already available, and will be available soon.

**Comment by breizh2944** [comment]
Great ! Thank you !
I'll give it a try tonight when I'm back at home.

**Comment by breizh2944** [comment]
I may have misunderstood what you said... but I tried to get these parameters, but no luck...

I tried to use `sudo deepin-wm --replace`, but no visual change compared to standard situation.

What am I doing wrong ?

**Comment by felixonmars** [comment]
> I may have misunderstood what you said... but I tried to get these parameters, but no luck...
> 
> I tried to use `sudo deepin-wm --replace`, but no visual change compared to standard situation (still no option for transparency or corners - moreover, multitask view stopped working)
> 
> What am I doing wrong ?

Please do not run it with sudo.

**Comment by breizh2944** [comment]
Thank you for your feedback.
However, sorry, doesn't work either (no new settings for transparency level or corner type)

What exactly should I expect by running this command, compared to standard deepin-wm behaviour ?

**Comment by felixonmars** [comment]
> Thank you for your feedback.
> However, sorry, doesn't work either (no new settings for transparency level or corner type)

Please paste some logs from terminal or I have no idea what doesn't work.

> What exactly should I expect by running this command, compared to standard deepin-wm behaviour ?

(Small) rounded corners, blurred transparent backgrounds, compositing support, etc. I noticed that you have mentioned transparent backgrounds so perhaps it's in use already. No configurable option will be available in the control center, though.

**Comment by breizh2944** [comment]
> (Small) rounded corners, blurred transparent backgrounds, compositing support, etc. I noticed that you have mentioned transparent backgrounds so perhaps it's in use already. No configurable option will be available in the control center, though.

OK, so I can confirm it is working as expected : what you describe is what I get (I don't need to use --replace - it is working like that "out of the box")

So, the screenshot you have shown is what we'll get soon ? With deepin-wm or when deepin-kwin is fixed ?

Thanks again.

**Comment by felixonmars** [comment]
> So, the screenshot you have shown is what we'll get soon ? With deepin-wm or when deepin-kwin is fixed ?

The screenshot I posted in https://github.com/linuxdeepin/developer-center/issues/1945#issuecomment-709556383 is just some debug info for the developers to investigate, since I have no idea what's going on here.

The screenshot posted by @xmuli is a preview version of deepin-kwin, though. Hope someone will work on the fix here.

**Comment by breizh2944** [comment]
Oh sorry, talked about the image from xmuli, yes.
Anyway, thank you for all your work & help around DDE.

**Comment by orarugogerincufelpattano** [comment]
I'm on Manjaro, so I'm not (yet) affected by this bug but I would like to ask something. (Hope you don't mind doing it here.) 
Felix, do you have information as how the base (the window manager) for the Deepin DE will proceed in the future? Will it stay on kwin or will it go back to the Deepin WM? Thanks for any info and especially for your work!

**Comment by felixonmars** [comment]
> Felix, do you have information as how the base (the window manager) for the Deepin DE will proceed in the future? Will it stay on kwin or will it go back to the Deepin WM? Thanks for any info and especially for your work!

It will stay on kwin, and there is some effort to fix support for dde-kwin (the plugin) with vanilla kwin but I am not sure of the progress.

**Comment by orarugogerincufelpattano** [comment]
Okay, thanks for the Info!

**Comment by hbarsaiyan** [comment]
Downgrading the KDE dependecies worked for me. Though it's only a temporary solution you can try this if you want deepin-kwin to work:

`sudo pacman -S downgrade`

```downgrade "kactivities=5.74.0-1" "karchive=5.74.0-1" "kauth=5.74.0-1" "kbookmarks=5.74.0-1" "kcmutils=5.74.0-1" "kcodecs=5.74.0-1" "kcompletion=5.74.0-1" "kconfig=5.74.0-1" "kconfigwidgets=5.74.0-1" "kcoreaddons=5.74.0-1" "kcrash=5.74.0-1" "kdbusaddons=5.74.0-1" "kdeclarative=5.74.0-1" "kded=5.74.0-1" "kglobalaccel=5.74.0-1" "kguiaddons=5.74.0-1" "ki18n=5.74.0-1" "kiconthemes=5.74.0-1" "kidletime=5.74.0-1" "kio=5.74.0-1" "kirigami2=5.74.0-1" "kitemmodels=5.74.0-1" "kitemviews=5.74.0-1" "kjobwidgets=5.74.0-1" "knewstuff=5.74.0-1" "knotifications=5.74.0-1" "kpackage=5.74.0-1" "kservice=5.74.0-1" "ktextwidgets=5.74.0-1" "kwallet=5.74.0-1" "kwayland=5.74.0-1" "kwidgetsaddons=5.74.0-1" "kwindowsystem=5.74.0-1" "kxmlgui=5.74.0-1" "frameworkintegration=5.74.0-1" "networkmanager-qt=5.74.0-1" "plasma-framework=5.74.0-1" "kdecoration=5.19.5-1" "kscreenlocker=5.19.5-1" "kwayland-server=5.19.5-1" "kwin=5.19.5-2"```

**PS: Don't use it if you also have KDE installed alongside.**

**Comment by haonanq666** [comment]
@hbarsaiyan  Thanks for the tips, can confirm, it totally worked!

Note to others who wish to use this fix: For me downgrade wasn't in pacman repositories, so I downloaded from AUR.

**Comment by hbarsaiyan** [comment]
The issue is fixed for me with the latest version of deepin-kwin. Window effects are working for me with the kde update.

**Comment by haonanq666** [comment]
Can confirm, after updating everything is a lot less janky and runs smoother. Also tray icons and other details are now like stock deepin. However am running into issue #1961 (not quite sure what was meant by "try again with 5.3.0.37-1", will ask over there in the appropriate thread) and issue #1848. Beware if these features are important to you.

**Comment by breizh2944** [comment]
Great news, I'll have a look asap.
Regarding #1961, this happens also with deepin-wm (that's my current setup).

**Comment by breizh2944** [comment]
I revert to deepin-kwin and can confirm this issue is solved.
