### ISSUE TITLE
Volume adjustment

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#1947]
In the latest versions, the deepin 20 lost the fine adjustment of the volume by the mouse scroll. Previously, the adjustment was made 1 in 1 (0%, 1%, 2%, 3%...) and currently 10 in 10 (0%, 10%, 20%, 30%...).

Return the previous fine adjustment (1 in 1).

![Screen Capture_select-area_20201016215652](https://user-images.githubusercontent.com/45263160/96324918-96bad780-0ffa-11eb-931d-1d0c23f8abcc.gif)

**Comment by xmuli** [comment]
The design is such that it is desired to move quickly to the desired general area using the pulleys.

**Comment by alexwender1** [comment]
> The design is such that it is desired to move quickly to the desired general area using the pulleys.

Can it be clearer? I do not understand.

**Comment by xmuli** [comment]
Designed so

**Comment by alexwender1** [comment]
I will keep this issue open; because users have lost fine / precise volume adjustment with the mouse scroll.

The problem still persists in deepin 20.1 (1010) - OsBuild=11031.108

**Comment by xmuli** [comment]
Repeat， see [#1769](https://github.com/linuxdeepin/developer-center/issues/1769)

**Comment by aiamuzz** [comment]
@xmuli ...

Any chance Deepin will reintroduce per app volume controls in the volume/sound plugin/applet like it was there in Deepin's earlier versions ?

It was a nice and handy feature with the option to set different volume levels across multiple apps ...

anybody have a screenshot of the feature when it existed in the older versions of Deepin OS ?

Cheers
