### ISSUE TITLE
HDMI not recognized

### ISSUE THREAD

**Issue by WesleySantosMaxtelll** [linuxdeepin/developer-center#1948]
I installed the deepin v20 on my laptop and my HDMI does not recognize when I connect it a second monitor.
I have tested hardware stuff and everything is fine, also, my HDMI was working just before I switch from another linux distro to this one. 

I am using a nvidia gtx 1050 ti mobile.

**Comment by xmuli** [comment]
A reboot may take effect (happened to me too)

**Comment by peeweep** [comment]
Since this problem has not reproduced in the latest version, I will close it first. If you still have problems, you can reopen this issue and provide more details.
