### ISSUE TITLE
有升级时无法忽略某一个软件的某一个版本

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1950]
举个例子，现在系统有更新是netease-cloud-music，让我升级到1.2.1，但是这个版本的软件有问题（不支持高分屏），我不想升级，但是我却无法忽略这个版本
我想如果升级是应用软件可以提供一个功能让忽略应用程序的某一个版本，不升级到某一个版本最好

**Comment by xmuli** [comment]
这是 linux 的包管理器的内容, 和 DDE 是没有关系的. 可以自行google 一下.

**Comment by widon1104** [comment]
linux 的包管理器功能太弱了，建议给上游提意见或者直接给包管理器提交patch，把功能做完善一点

**Comment by xmuli** [comment]
![image](https://user-images.githubusercontent.com/33887845/96723340-0a852780-13e1-11eb-9ce6-44fc24cb3cf5.png)

**Comment by widon1104** [comment]
![截图录屏_选择区域_20201021212414](https://user-images.githubusercontent.com/12093211/96725784-da8b5380-13e3-11eb-8399-af6970c11a45.png)
找到了，使用命令行apt-mark hold xxx就可以使得某个软件版本不变不升级，但是这个感觉太晦涩了，估计很多使用linux的小伙伴都不知道有这个功能，我觉得deepin官方可以收集这种有用的功能，专门做一个app收集类似的功能把他们用界面图形化，方便大家了解使用。
