### ISSUE TITLE
/var/log/Xorg.0.log显示"(EE) failed to set mode: Invalid argument"

### ISSUE THREAD

**Issue by Dreamer-Fantasy** [linuxdeepin/developer-center#1951]
系统是**arch 2020-10**版本
安装了`xorg xorg-server deepin`组
`systemctl enable lightdm`
同样操作的还有`NetworkManager`
也按wiki改了`/etc/lightdm/lightdm.conf`
具体是：

1. 取消了`[Seat:*]`的注释并删除同一行的其它内容
2. 取消了`greeter-session`行首的注释并修改这一行为“`greeter-session=lightdm-deepin-greeter`”（文件中这一行没引号）

现在开机不能进入桌面
还是跳字符
跳出来的没错误，最后止步于“Reached target Grapical Interface”。
但是cat /var/log/Xorg.0.log发现了几个EE：
```
failed to load module "vmware" (module doesn't exist, 0)
failed to load module "fbdev" (module doesn't exist, 0)
failed to set mode: Invalid argument
```

**Comment by xmuli** [comment]
> 也按wiki改了/etc/lightdm/lightdm.conf

实际并不需要修改此文件, 记得在某处的脚本已经被修改了的.  Arch + DDE 可以参考 [ArchLinux + DDE 安装教程](https://xmuli.tech/posts/4bf5e477/). 后面在实体机中也已经测试生效过了.

**Comment by Dreamer-Fantasy** [comment]
我是通过Virtualbox在虚拟机中安装的Arch Linux。更详细的信息位于下方图片：
![vbox——关于](https://user-images.githubusercontent.com/58366528/96605669-0e557300-1329-11eb-8f61-dd0f80c2825a.png)
![宿主机规格](https://user-images.githubusercontent.com/58366528/96605678-10b7cd00-1329-11eb-8aec-6ec33ce7e6b9.png)
![我的vbox上的arch详情](https://user-images.githubusercontent.com/58366528/96605681-11506380-1329-11eb-9e72-d940b487e0b6.png)
我选择通过一位B站UP主推荐的一个安装脚本——Anarchy来安装Arch Linux。我就是照着这个UP的视频原封不动安装下来的。
相关链接：
1. https://www.bilibili.com/video/BV1yD4y127Nu

2. https://anarchyinstaller.org/

接着便开始安装DDE。
收到您的回复后，我立即推倒重来，
严格执行了您发给我的链接教程中的4.2.13和4.2.21两个步骤。
可是我仍不能使系统显示桌面。详述如下：
1. 下载deepin-movie和deepin-music时提示404
![安装不了deepin-movie和deepin-music](https://user-images.githubusercontent.com/58366528/96607901-642b1a80-132b-11eb-947e-a3fe08091cc2.png)
2. 取消下载404包后安装检验阶段系统报告deepin-screen-recorder和deepin-screenshot冲突
![deepin-screen-recorder和deepin-screenshot冲突](https://user-images.githubusercontent.com/58366528/96608299-cab03880-132b-11eb-8f56-176511a9af93.png)
3. 取消下载404包，取消安装冲突包后可顺利进行安装。随后将lightdm添加到开机自启服务。
4. 重启后仍然没有图形化界面出现。
![启动的最终结果](https://user-images.githubusercontent.com/58366528/96608784-604bc800-132c-11eb-94d2-177316a5aa0e.png)
5. 检查xorg日志，直接查找EE提示
![报错](https://user-images.githubusercontent.com/58366528/96608941-85d8d180-132c-11eb-8e17-72731dedca10.png)


这令我很困惑。

**Comment by felixonmars** [comment]
东软镜像最近坏了（有四五天了）。建议使用 tuna/bfsu/ustc 镜像。

**Comment by xmuli** [comment]
参考巨佬, 换一个源 (bfsu/tuna/ustc ), 然后将这几个包重新安装一下.试试

**Comment by Dreamer-Fantasy** [comment]
已经确认无法显示DDE GUI的原因为：没有在我的virtualbox虚拟机上安装显示驱动“xf86-video-vmware”。
安装上述驱动后便能够显示DDE GUI了。

**Comment by Dreamer-Fantasy** [comment]
![deepin-screen-recorder和deepin-screenshot冲突](https://user-images.githubusercontent.com/58366528/96711973-f6d1c500-13d0-11eb-8571-27ad874d7949.png)
arch安装deepin-extra时提示deepin-screen-recorder和deepin-screenshot冲突的问题怎么解决？

**Comment by felixonmars** [comment]
> arch安装deepin-extra时提示deepin-screen-recorder和deepin-screenshot冲突的问题怎么解决？

在仓库中已修复。deepin-screenshot 已从 deepin-extra 移除，deepin-screen-recorder 已标记为和 deepin-screenshot 冲突。

**Comment by xmuli** [comment]
已经三个截图了， 一堆轮子

**Comment by Dreamer-Fantasy** [comment]
目前发现在arch下，搜狐源`mirrors.sohu.com`是最全的，但是速度只有感人的260K上下

**Comment by Dreamer-Fantasy** [comment]
感谢诸位的回复！
