### ISSUE TITLE
[ARCH] Short Cut key for deepin-screen-record/deepin-screenshot stop working

### ISSUE THREAD

**Issue by taolin96** [linuxdeepin/developer-center#1952]
![image](https://user-images.githubusercontent.com/7938311/96698566-c3e7fb00-13e9-11eb-9e1d-0fe27e17f07f.png)

just notice after the recent update, the above short cut keys stop working, checked the journal log and found below error 

> Oct 21 21:59:12 MacPro.fritz.box daemon/keybinding[871]: manager_handlers.go:71: execCmd error: exit status 1

checked short cut key call from this file 

> /usr/share/dde-daemon/keybinding/system_actions.json
![image](https://user-images.githubusercontent.com/7938311/96698769-ff82c500-13e9-11eb-9b01-cc0b1788cc9d.png)

and tried run it manually and it failed with error below
`❯ dbus-send --print-reply --dest=com.deepin.ScreenRecorder /com/deepin/ScreenRecorder com.deepin.ScreenRecorder.stopRecord
Error org.freedesktop.DBus.Error.ServiceUnknown: The name com.deepin.ScreenRecorder was not provided by any .service files `

**Comment by Dreamer-Fantasy** [comment]
I met a problem while installing `deepin-screen-recorder` and `deepin-screenshot` together.
The pacman prompts me that there is a conflict between the two packages, as shown in the picture below.
Could you please show me how to solve the problem above?
Much thanks.

**Comment by taolin96** [comment]
> I met a problem while installing `deepin-screen-recorder` and `deepin-screenshot` together.
> The pacman prompts me that there is a conflict between the two packages, as shown in the picture below:
> ![conflict](https://user-images.githubusercontent.com/58366528/96748650-63ae8480-13fc-11eb-85b5-c736b2745255.png)
> 
> Could you please show me how to solve the problem above?
> Much thanks.

I just removed `deepin-screenshot` as `deepin-screen-recorder` have the screenshot function already

**Comment by felixonmars** [comment]
Fixed in the repository. deepin-screenshot has been removed from deepin-extra and deepin-screen-recorder has been marked as conflicted with deepin-screenshot.

**Comment by taolin96** [comment]
confimed the issue resolved after deepin-screen-recorder update (5.8.0.21-1 -> 5.8.0.22-1)
