### ISSUE TITLE
Mouse's Right Click does NOT work after upgrading to 1003. 升级1003后，鼠标右键失效。

### ISSUE THREAD

**Issue by mal1029** [linuxdeepin/developer-center#1956]
Please help.

**Comment by xmuli** [comment]
已经被修复在内网

**Comment by mal1029** [comment]
在内网被修复，不是很理解。你指的是这个问题在官方论坛里做了处理吧？

我去deepin的官方论坛里看了，只看到有人指出，右键被映射为中键了。

**Comment by micribite** [comment]
Edit file /etc/X11/xorg.conf.d/40-libinput.conf    mapping 1 0 3 ...to 1 3 3 .... this will solve problem individualy. This should solve from developers via update.

**Comment by xmuli** [comment]
> 在内网被修复，不是很理解。你指的是这个问题在官方论坛里做了处理吧？
> 
> 我去deepin的官方论坛里看了，只看到有人指出，右键被映射为中键了。

意思是说, 已经在修复此 bug, 不过提交在内网, 然后会同步到内测地址, 再然后同步到公开地址

**Comment by mal1029** [comment]
> > 在内网被修复，不是很理解。你指的是这个问题在官方论坛里做了处理吧？
> > 我去deepin的官方论坛里看了，只看到有人指出，右键被映射为中键了。
> 
> 意思是说, 已经在修复此 bug, 不过提交在内网, 然后会同步到内测地址, 再然后同步到公开地址

谢谢。
