### ISSUE TITLE
[Feature request] Hide "share connection" if Wi-Fi is off

### ISSUE THREAD

**Issue by wuniversales** [linuxdeepin/developer-center#1959]
I'm talking about the deepin control panel.

I think it would be good to hide the button to share the connection if the wifi is disabled.

Also the button to share the connection would move it and put it under the Wi-Fi button.

As for the Wi-Fi notification button on the taskbar ...

Why not put an option to "share wifi" just below everything, where the wireless networks are shown?

Greetings

**Comment by meiyixiang** [comment]
12/5000 
I'm sorry I didn't catch your meaning

**Comment by meiyixiang** [comment]
您的建议已经记录并反馈给对应的产品
17/5000 
Your suggestions have been recorded and fed back to the corresponding products

**Comment by meiyixiang** [comment]
Thank you for your suggestions. We will fulfill your feedbacks later.

**Comment by meiyixiang** [comment]
Thank you for your suggestion and we will fulfill your feedbacks.

**Comment by meiyixiang** [comment]
这个建议我们已经采纳并排期去实现，但由于需求比较多所以可能会需要一些时间啊
