### ISSUE TITLE
Mouse hang

### ISSUE THREAD

**Issue by darkcyber** [linuxdeepin/developer-center#196]
I face mouse hang after close laptop lid, and then open laptop lid.

What cause this? and how to fix it?

Asus A455LJ

Thanks in advance.

**Comment by darkcyber** [comment]
http://feedback.deepin.org/feedback/detail/2179?token=3gOQl3cnwua2M8xM

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
