### ISSUE TITLE
[Arch] Deepin Control Center crashes on launch

### ISSUE THREAD

**Issue by breizh2944** [linuxdeepin/developer-center#1961]
With release 5.3.0.25-1, the control center crashes at startup.
Cannot access it anymore.

**Comment by breizh2944** [comment]
`dde-control-center: symbol lookup error: dde-control-center: undefined symbol: _ZNK7__Power11ModeChangedERK7QString`

**Comment by felixonmars** [comment]
Sorry for the mismatched version. Please try again with deepin-control-center 5.3.0.37-1.

**Comment by haonanq666** [comment]
@felixonmars 大佬, 控制中心怎么换成 5.3.0.37-1 版本？抱歉新手比较菜。

**Comment by breizh2944** [comment]
It's OK now.
Thank you.
