### ISSUE TITLE
Problem installing Webmin !

### ISSUE THREAD

**Issue by btech-sewing** [linuxdeepin/developer-center#1962]
`Last login: Wed Oct 28 11:05:52 2020 from 192.168.1.20
root@User-PC:~# service webmin stop
root@User-PC:~# service webmin start
Job for webmin.service failed because the control process exited with error code.
See "systemctl status webmin.service" and "journalctl -xe" for details.
root@User-PC:~# systemctl status webmin.service
● webmin.service - LSB: web-based administration interface for Unix systems
   Loaded: loaded (/etc/init.d/webmin; generated)
   Active: failed (Result: exit-code) since Wed 2020-10-28 11:18:47 EET; 40s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 12719 ExecStart=/etc/init.d/webmin start (code=exited, status=139)

окт 28 11:18:47 User-PC systemd[1]: Starting LSB: web-based administration interface for Unix systems...
окт 28 11:18:47 User-PC perl[12720]: pam_deepin_authentication(webmin:auth): Cannot get original tty attributes: Inappropriate ioctl for device
окт 28 11:18:47 User-PC perl[12720]: pam_deepin_authentication(webmin:auth): Password
окт 28 11:18:47 User-PC perl[12720]: pam_deepin_authentication(webmin:auth): Password:
окт 28 11:18:47 User-PC systemd[1]: webmin.service: Control process exited, code=exited, status=139/n/a
окт 28 11:18:47 User-PC systemd[1]: webmin.service: Failed with result 'exit-code'.
окт 28 11:18:47 User-PC systemd[1]: Failed to start LSB: web-based administration interface for Unix systems.
root@User-PC:~# journalctl -xe
-- Стартирането на модул „deepin-elf-verify.service“ завърши.
--
-- Резултатът е: done
окт 28 11:20:06 User-PC deepin-elf-verify[12861]: [ERROR] failed to open: No such file or directory
окт 28 11:20:06 User-PC systemd[1]: deepin-elf-verify.service: Main process exited, code=exited, status=255/EXCEPTION
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit deepin-elf-verify.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 255.
окт 28 11:20:06 User-PC systemd[1]: deepin-elf-verify.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit deepin-elf-verify.service has entered the 'failed' state with result 'exit-code'.
окт 28 11:20:06 User-PC deepin-deepinid-daemon[3939]: [WAR] manager.go:216: skip doSync
окт 28 11:20:09 User-PC systemd[1]: deepin-elf-verify.service: Service RestartSec=3s expired, scheduling restart.
окт 28 11:20:09 User-PC systemd[1]: deepin-elf-verify.service: Scheduled restart job, restart counter is at 344.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Automatic restarting of the unit deepin-elf-verify.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
окт 28 11:20:09 User-PC systemd[1]: Stopped deepin ELF Verify.
-- Subject: Модул „deepin-elf-verify.service“ вече е спрян
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Спирането на модул „deepin-elf-verify.service“ завърши.
окт 28 11:20:09 User-PC systemd[1]: Started deepin ELF Verify.
-- Subject: Модул „deepin-elf-verify.service“ вече е стартиран
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Стартирането на модул „deepin-elf-verify.service“ завърши.
--
-- Резултатът е: done
окт 28 11:20:09 User-PC deepin-elf-verify[12862]: [ERROR] failed to open: No such file or directory
окт 28 11:20:09 User-PC systemd[1]: deepin-elf-verify.service: Main process exited, code=exited, status=255/EXCEPTION
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit deepin-elf-verify.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 255.
окт 28 11:20:09 User-PC systemd[1]: deepin-elf-verify.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit deepin-elf-verify.service has entered the 'failed' state with result 'exit-code'.
lines 4863-4918/4918 (END)`

**Comment by btech-sewing** [comment]
For many people, Webmin is a very important tool for system settings, as well as for observations, because for many things there are no graphical settings. Can you give any guidelines or instructions on how to solve this problem?

**Comment by liuahfy** [comment]
I also encountered this problem, hope the development can be fixed as soon as possible, thanks.

**Comment by peeweep** [comment]
I tried following steps, and webmin.service work fine.
```
echo 'deb [trusted=yes arch=amd64] http://download.webmin.com/download/repository sarge contrib' | sudo tee -a /etc/apt/sources.list
sudo apt update
sudo apt install webmin
sudo systemctl status webmin
```
@btech-sewing @liuahfy I will close this issue. If you still have the problem on the latest version of Deepin, please reopen this issue and provide more log.
