### ISSUE TITLE
Fails to install Deepin 20 on Chuwi Aerobook 15.6 Plus

### ISSUE THREAD

**Issue by ErikDeridder** [linuxdeepin/developer-center#1963]
Dear, i have a new Chuwi Aerobook 15.6 Plus ( I5/16GB Mem ) with an SSD and Intel Iris 550 HD graphics card.
When trying to install from USB i can boot and get into the first screen were i can choose to Install Deepin 20 normal or Safe mode.

Whatever i choose i get a second screen with only the beautyfull desktop and after minutes of waiting a black screen. The system doesn't hang as the LED from the numpad still works

My guess, something wrong with driver support for this Intel Iris 550 HD graphics Controller?

Any help would be nice

**Comment by haonanq666** [comment]
Although I am in no way an expert, have you tried the ```nomodeset``` boot option? With some Nvidia GPUs this needs to be done before the proper drivers are installed. 

---------------------------------------------------------
我要是误人子弟望大佬们指出，删之你发。

**Comment by ErikDeridder** [comment]
Hi and first of all thank you for your reply. It's the first time someone answers :-)
You are correct, that is one option if installations fails but thats allready in the boot script when i choose "Install Deepin in safe mode" then this option nomodeset is set :s

**Comment by peeweep** [comment]
If you still have this problem on the latest version of Deepin, you can reopen this issue.
