### ISSUE TITLE
Touch sensor for Huawei matebook 13

### ISSUE THREAD

**Issue by RyabovJura** [linuxdeepin/developer-center#1965]
Touch sensor dont work Goodix Fingerprint USB Device.

**Comment by haonanq666** [comment]
That's an issue that you should bring up with those at libfprint as there is nothing deepin can do about Goodix drivers. 
https://gitlab.freedesktop.org/libfprint/libfprint/-/issues

**Comment by peeweep** [comment]
For most hardware drivers, we just use some drivers included in the kernel (vanilla kernel plus our patches), and some driver packages provided by the manufacturer or the community.
For most of drivers, we are also users, not developers, and drivers need the support of manufacturers.
If your hardware depends on updated kernel or software, please let us know and we will evaluate the scope of impact. In most cases, we can update to a sufficiently new version.

I will close this issue first, if you still have problems, you can reopen it.
