### ISSUE TITLE
Crash after login [ArchLinux]

### ISSUE THREAD

**Issue by ssilvestri15** [linuxdeepin/developer-center#1967]
Hi all!

I've just installed Arch Linux with this guide [Official Arch Linux Installation Guide](https://wiki.archlinux.org/index.php/installation_guide) so i do these before install dde:

1. pacman -S networkmanager bluez bluez-utils pulseaudio pulseaudio-alsa nvidia nvidia-utils nvidia-settings
2. systemctl enable bluetooth.service 
3. systemctl enable NetworkManager

Now I install dde with:

1. pacman -S deepin deepin-extra

and edit the configuration file of lightdm under the [Seat:*] section:

- greeter-session=lightdm-deepin-greeter and uncomment it

Next I do:

1. systemctl enable lightdm.service
2. reboot

This is my installation, no other packages, only this

When the system reboot I see the graphical login screen, I enter the password and login after it crash and the login screen appear again.

How I can fix? Ty

**Comment by SalahAdDin** [comment]
Actually, i think this is related to the last update of this desktop on Arch, i can't login too after i updated it.

**Comment by felixonmars** [comment]
Please try again with
deepin-desktop-schemas 5.8.0.20-3
startdde 5.6.0.10-2

They broke deepin-wm support yet again.

**Comment by th3raid0r** [comment]
Here's the crash dump for this:

```

**Comment by sunchir** [comment]
> Actually, i think this is related to the last update of this desktop on Arch, i can't login too after i updated it.
what command can fixed it ? i use yay -S deepin-desktop-schemas , look like not have the effect

**Comment by sunchir** [comment]
> Please try again with
> deepin-desktop-schemas 5.8.0.20-3
> startdde 5.6.0.10-2
> 
> They broke deepin-wm support yet again.

could you tell me how to deal with this problem in  manjaro , i find the repo don't has this packages .thank you

**Comment by SalahAdDin** [comment]
@sunchir i used the **AUR**'s `downgrade`package with the `--ala` option to install those packages. No other way in **Manjaro**, i think, since **Manjaro** gelds its packages to a known stable version.

**Comment by sunchir** [comment]
> @sunchir i used the **AUR**'s `downgrade`package with the `--ala` option to install those packages. No other way in **Manjaro**, i think, since **Manjaro** gelds its packages to a known stable version.

it worked, thank you . downgrade --ala-only packageName  // https://github.com/pbrisbin/downgrade
