### ISSUE TITLE
Problems in using the git version of dde

### ISSUE THREAD

**Issue by justforlxz** [linuxdeepin/developer-center#1968]
- [x] dde-launcher not show when use super key
- [ ] unusual font size for greeter
- [ ] using deepin application under non-dde, the style is abnormal
- [ ] many failed logs in startdde
- [x] dde-launcher have large icon
- [ ] dde-control-center args

**Comment by RigoLigoRLC** [comment]
DTK is really binded with DDE. This should be fixed, really :p
