### ISSUE TITLE
Delay with on opening app from do

### ISSUE THREAD

**Issue by alexk136** [linuxdeepin/developer-center#1969]
My PC:
core i5 / 16gb /deepin 20 5.4.50

I noticed what after a while i start having delay after click on working app in doc and app appears on desctop and delay is growing.. Also computer become slower and slower, you can notice it watching youtube.. its freezing. 

Rebooting helps.. 

I fresh installation of deepin 20.

I can provide extra information if it helps.

**Comment by peeweep** [comment]
Disable Window Effect in Control Center -> Personalization -> General would be help a lot.

If you still have this problem on the latest version of Deepin, please provide steps to reproduce.

**Comment by peeweep** [comment]
We recently made some huge performance-related updates. The scene at that time may not be able to reproduce, so I close this issue first.

If you still have problems, you can reopen it.
