### ISSUE TITLE
no mouse pointer when logging in

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/developer-center#197]
When I boot and log in my mouse cursor is invisible. When I then log out and in again, cursor appears and all is well.

**Comment by oberon2007** [comment]
To be precise: When I boot up, there is already no mouspointer when I reach lightdm-deepin-greeter.
Only after logging in and then back out, I get a pointer.

**Comment by wilkmaia** [comment]
Is it a fresh install? Which packages have you installed, exactly?

I've installed Deepin on Arch-Linux (4.10.3-1-ARCH) and had no problem whatsoever.

**Comment by funilrys** [comment]
Same here with:
```
Linux funilrys 4.10.4-1-ARCH #1 SMP PREEMPT Sat Mar 18 19:39:18 CET 2017 x86_64 GNU/Linux
```
@wilkmaia @oberon2007 I think it's specific to manjaro ...

**Comment by oberon2007** [comment]
For me the issue seems to have disappeared - no idea why... :wink:
