### ISSUE TITLE
托盘图标上面右键，菜单会马上消失

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#1970]
我的系统deepin V20 1003更新到最新
我现在发现2个app会出现这种右键菜单消失的情况
1）网易云音乐1.2.0（build0408）, 这个软件托盘图标是不会闪动的，但是我在它的托盘图标上面右键展示菜单的时候，菜单经常自己消失，必须要尝试3次左右菜单才能显示出来不消失
2）微信（就是软件商店安装的微信），如果软件不来消息图标不闪是没问题的，但是如果来了消息，托盘图标开始闪以后，右键托盘图标的中心，菜单会马上消失，这个几乎是必现的

**Comment by justforlxz** [comment]
在最新版本上似乎已经没问题了。

**Comment by widon1104** [comment]
我最近使用发现，这个问题还是存在，只是没有以前那么严重了，比如说网易云音乐这个软件，在这个软件的系统托盘图标上面，我经常需要右键第二次才能弹出菜单来操作网易云音乐。

**Comment by widon1104** [comment]
系统升级到20.2以后，这个问题又出现了，而且比以前还严重，这次网易云音乐都无法关闭了，系统托盘菜单一出来马上消失，只有后台杀进程才行。

**Comment by widon1104** [comment]
![录屏_选择区域_20210401172539](https://user-images.githubusercontent.com/12093211/113274109-e4f53600-930f-11eb-9925-5bd7cf80b1e2.gif)

**Comment by chenzhiwei** [comment]
20.2 的很多地方右击都调不出菜单，比如Dock左侧的应用图标上无法调出右击菜单，不能Pin或UnPin软件。

Chrome 里右击菜单也得两次才行，第一次右击闪现一下就消失了。

每次右击都会响一下，声音和调节音量时的提示音一样，很奇怪的现象。

**Comment by chenzhiwei** [comment]
@widon1104 你试试这个方法可行不，我这里貌似有所缓解：https://github.com/linuxdeepin/developer-center/issues/1956#issuecomment-720890254

**Comment by cabbage89** [comment]
20.2 此问题仍然没有修复，图标会莫名丢失
