### ISSUE TITLE
Deepin 2020.11.13 updates' bugs

### ISSUE THREAD

**Issue by ricosandyca** [linuxdeepin/developer-center#1971]
The bugs i found in the updates
- The updates caused the dock lost. But you can still restore it by disabling "Window Effect" from the control center then reboot/logout. However, you can't get the dock on "Window Effect" anymore
- I'm not sure, but after receiving this update my "appstore.gpg" file broken. It shows
```
W: The key(s) in the keyring /etc/apt/trusted.gpg.d/appstore.gpg are ignored as the file has an unsupported filetype.
```

The keyring errors causes me unable to run `apt update` command
![image](https://user-images.githubusercontent.com/43330562/99139880-36599d00-266f-11eb-814e-1e46f0e489f1.png)

I've checked the keyring list by typing this command `apt-key list`, and yah, it's showing that the `appstore.gpg` file is broken
![image](https://user-images.githubusercontent.com/43330562/99139906-820c4680-266f-11eb-965b-1a509084f7bb.png)

So please, Deepin developers team to address those :)

Btw this is my system info
```
OS Name: Deepin
Version: 20
Ediition: Community (1003)
Type: 64-bit
Kernel: 5.4.70-amd64-desktop
```

**Comment by tanvir-kx** [comment]
I am having the same issues also no "Backup and Restore" option in Control Center.

![image](https://user-images.githubusercontent.com/68131844/99158602-b67b1380-26fe-11eb-986b-9c515b9b3aaa.png)

**Comment by peeweep** [comment]
@tanvir-kx Backup and Restore in System info 
![image](https://user-images.githubusercontent.com/624223/147641702-0b881a29-d10a-4a5f-bea5-10ef5becf80e.png)

**Comment by peeweep** [comment]
@tanvir-kx Reinstall `deepin-keyring`
```
sudo apt install --reinstall deepin-keyring
```

**Comment by peeweep** [comment]
If you still have this problem on the latest version of Deepin, you can reopen this issue.
