### ISSUE TITLE
Not available change input language while install procedure doesn't complete

### ISSUE THREAD

**Issue by iDevPro** [linuxdeepin/developer-center#1972]
Hello,
In Deepin 20 installation Programm I found problems consisted in:
- Select language of product other than English
- Select keyboard layout other than English
- Tried to input English characters for Login and Password

Expects:
- Available change language for input, by keyboard key combination and(or) select by mouse click in Input Language component on some places.

Actual:
- Not available input English name for Login, nor available instruments to do this

**Comment by peeweep** [comment]
@iDevPro Which language did you select? I tried to choose 简体中文(SC) and Français(FR), the english charactor could be input when create account.

**Comment by iDevPro** [comment]
> @iDevPro Which language did you select?
> I tried to choose 简体中文(SC) and Français(FR), English characters can be entered when creating an account.
> Since this problem has not reproduced in the latest version, I will close it first. If you still have problems, you can reopen this issue.

Russian, I tried today when reinstall system from restore :)
I suppose I have old system in restore (Deepen Community 20.1) not 20.5 )
If this fixed in new version, that issue would be close :)

**Comment by BLumia** [comment]
We cannot reproduce this issue on the most recent deepin release, so we suggest you try upgrade the system and check if it's fixed. If this issue still happens on the most recent version you can get, you can create a new issue to report the bug :)
