### ISSUE TITLE
Feature suggestion - kwin, control to disable window highlight

### ISSUE THREAD

**Issue by forsback** [linuxdeepin/developer-center#1974]
It would be nice if you could add a control switch to set window highligth to false in kwinrc. I find the desktop more comfortable with this option set to false. 
(highlightwindowEnabled=false)

**Comment by meiyixiang** [comment]
61/2000 
The current desktop effects are no longer optimized, please wait for our new V23 desktop effects.

**Comment by meiyixiang** [comment]
31/5000 
Can you provide a record screen effect, I tried the feeling there is no obvious change after modification
