### ISSUE TITLE
Feature suggestion - add tree view to file manager

### ISSUE THREAD

**Issue by forsback** [linuxdeepin/developer-center#1975]
I find the Deepin file manager nice but I lack the possibility to have real tree view like in e.g. KDE/Dolphin. In some cases it improves the usability. It could also open up in the left sidepane like in Windows Explorer. This is what most people in the Windows world are used to.

**Comment by xmuli** [comment]
I'm also looking forward to having Deepin and Windows have this feature (tree structure); what confuses me

**Comment by meiyixiang** [comment]
Thank you for your suggestion. This function is being planned but may not realize the function you want at the first time. It is expected that some functions will be supported around May or June 2022
