### ISSUE TITLE
Small menus in LibreOffice with HiDPI display (4k)

### ISSUE THREAD

**Issue by forsback** [linuxdeepin/developer-center#1976]
Noticed during testing of v20 Deepin that LibreOffice (6.1.xx) does not trigger a menu resize with a 4k display. I used a scale factor of 1.5 and 1.75 in the display settings. Menu font and icons are very small. 
(deepin-desktop-community-1002-amd64.iso, clean install)

**Comment by Zeno-sole** [comment]
Please upgrade the icon to try

**Comment by babyfengfjx** [comment]
Thanks for your deedback，I wonder if this issue still exists in the latest version？

**Comment by babyfengfjx** [comment]
Since we have not been in touch for a long time, we will close the issue first. If there is any problem later, you can submit the issue in time. Thanks for your feedback.
