### ISSUE TITLE
Feature request (long term) - display specific fractional scaling

### ISSUE THREAD

**Issue by forsback** [linuxdeepin/developer-center#1977]
This is one of the features I find lacking in all Linux distribution. If for example want to use a 4k display with the laptop lid open (1920x1200), the global scale setting in Deepin was adjusted for the laptop LCD. Same situation arises if a 2k display is combined with a 4k. I do not now if there are some architectural issues in X11 or if this will be possible with Wayland. Windows and Mac can do this today.

**Comment by meiyixiang** [comment]
48/2000 
Hello this requirement I have documented, has been planning in the development of this feature.
