### ISSUE TITLE
The Grand IRONY of Deepin ... a full circle !!! ... Deepin Classic ... RIP ???

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1979]
Hello,

If not for the new setting that lets us control the **UGLY** rounded corners(at least the window and dock corners are controllable ... with the other **UGLY** rounded corner graphics by the truck load thrust everywhere possible in the whole UI still in your face everywhere, login screen, category app drawer) ... I had completely given up on Deepin OS and would never have bothered to write this feedback post !!!

**THE GRAND IRONY : THE DEEPIN STORY THAT DRILLED DEEP ... SO DEEP THAT IT CAME OUT THE OTHER SIDE ALL UGLY AND BRUISED, ABSOLUTELY UNRECOGNIZABLE ... I GUESS THEIR DRILLING BITS DRILLED SO BADLY THAT THEY CAME OUT BLUNT WITH ROUNDED CORNERS EVERYWHERE !!!**

First there where Linux Distro's ... they had their own DE's and standard settings application ... Then Deepin disrupted that mundane UI linux landscape had ... with its Dreamy ... Side-Control-Panel, the Ethereal UI with the Hot corner settings, the smooth as butter transition animations in displaying workspaces and app window previews ... It was Linux Heaven ... 

Then Deepin team hit a brilliant idea of porting this ethereal Linux UI world to all other Linux distros ... They started telling those distro's that this new UI was better than theirs ... an integrated Side-Control-Panel was waaaaay better than their 'Window based Settings Application' ... the hot corners and the animation and the window's effect of Deepin added the much lacking appeal in their own Distro's ...

**Cut to Present ...** Deepin themselves went the way of those Distro's and abandoned the **Dreamy Deepin** with all its Hot Corner's ... its Side Setting's Panel ... Its beautiful center aligned Dock ... in for **UGLY THRUST-EVERYWHERE-YOU-CAN-ROUNDED-CORNER-GRAPHICAL-ELEMENTS-INTO-THE-UI** 
;
;
;
;
;
Is there anyone from Deepin's Glory Story of the past, that can keep the Deepin-Classic UI of (hot-corners, Dock and Side Settings Panel) ALIVE ??? ... after all you did go about fixing other Distro's UI's with these elements ... I guess NOW your own bruised, blunted and rounded UI needs the sharp, dreamy and thereal Deepin-Classic-UI elements applied to its own **UGLY-self** !!!
;
;
;
PS : How difficult/practical would would it be to maintain/continue the DDE-Classic version layered over the currently **UGLY** Deepin ? What a DISSAPPOINTMENT !!! ... Lets see how many ports of the current DDE will get ported to other distro's and will be sought after by their users !!! ... Those STATS will certainly VINDICATE THIS FEEDBACK/IRE POST/THREAD I HAVE WRITTEN !!!

**Comment by Sinofine** [comment]
I truly wish deepin got a design just as rectangular as rectangles!!!

**Comment by aiamuzz** [comment]
> I truly wish deepin got a design just as rectangular as rectangles!!!

If the team really want to undo the damage ... they need to find a way to let users CONTROL the other **rounded-corner-semi-transparent-background-graphic elements** ... and in some cases/areas an option to get ride of them all together !!!

OR

create a theme ... sought of ... that will enable the users to choose a more rectangular corners just like the Deepin-Classic design !!!

**Comment by Y0ngg4n** [comment]
@aiamuzz @Sinofine In my Opinion they caused more damage with the Update from Deepin 15 to Deepin 20 than they may made better. Sadly i am now forced to move to KDE or some other Desktop Environment. The last year with Deepin i was just constantly fixing Bugs and trying to get arround Deepin Bugs and this is really anoying.

**Comment by aiamuzz** [comment]
> @aiamuzz @Sinofine In my Opinion they caused more damage with the Update from Deepin 15 to Deepin 20 than they may made better.

Exactly ... but i guess the glory is gone ... Unless they or somebody else kept the DDE from Deepin 15 alive as DDE-Classic package ... I am no techie ... but techinically it may be difficult or easy i don't know ... if its the latter ... then the DDE from Deepin 15 should be kept alive ... **All the damage done in the process of jumping from 15 - 20 could easily be undone ... through DDE Classic ... the Side Control Setting panel stands to return, along with the hot Corners and the Classic Dock** ... 

**Would really be a dream ...** but given the way the Deepin Team has become insensitive about having carried out such a radical change i am afraid it could just be a dream ...

**I was a big fan of @shule1987 ... their chief designer for Deepin 15 and ealier UI/UX ... but i guess the very same guy has sunk this ship ... by trying to fix/change something that was already perfect ... it neither warranted fixing or changing !!!**

**Comment by meiyixiang** [comment]
这个问题我觉得是吐槽了几年的一个问题，每个操作系统都有自己的设计风格，现在我们正在开发全新的桌面，可以耐心等待。
