### ISSUE TITLE
[arch linux] no right click menu on desktop, cant change wallpaper

### ISSUE THREAD

**Issue by psykotik1** [linuxdeepin/developer-center#198]
using latest deepin on fresh install, no right click menu. cursor theme changes from my theme to deepin momentarily after clicking, but no menu

**Comment by funilrys** [comment]
Same with this computer :+1: 
```
Linux 4.10.1-1-ARCH #1 SMP PREEMPT Sun Feb 26 21:08:53 UTC 2017 x86_64 GNU/Linux
```

**Comment by felixonmars** [comment]
Please try to right click on the desktop to set wallpaper with latest deepin-desktop 4.0.4-2.

**Comment by gustavodlima** [comment]
This is related to issue #193 and can be easily fixed. Try what @felixonmars said, this should work.
