### ISSUE TITLE
deepin Downloader Suggestions

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#1986]
1. Allow the app to create .torrent files; making it possible to add **webseeds**;
2. Allow the app to seed torrents;
3. Allow the app to view other seeders;
4. Add an external list of trackers to assist with the download (as used by [Motrix](https://motrix.app)): https://github.com/ngosang/trackerslist

![image](https://user-images.githubusercontent.com/45263160/100150223-1d769600-2e7e-11eb-9102-b22dd75bda90.png)

downloader 5.2.0.10-1
deepin 20 (1003 Update 1) / OsBuild=11031.106

**Comment by myml** [comment]
This does not seem to be a deepin downloader?
deepin downloader screenshot
![image](https://user-images.githubusercontent.com/13045857/147646994-152162cb-9dcd-48e3-b442-07b2286a4da4.png)

**Comment by lxwndr** [comment]
I'm suggesting that some functionality of the Motrix app be copied by the deepin native app; since it doesn't work properly.
