### ISSUE TITLE
deepin Disk Utility Suggestions

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#1987]
1. Display the partition table (MBR / GPT) of the disks / partitions;
2. Allow the alteration of the partition table (MBR / GPT) of the disks / partitions;
3. Allow formatting of devices in FAT32;
4. Allow resizing of partitions.

deepin-diskmanager 1.1.0.24-1
deepin 20 (1003 Update 1) / OsBuild=11031.106

**Comment by meiyixiang** [comment]
28/5000 
The problem you feedback has been supported, now the latest version has supported the function you feedback

**Comment by lxwndr** [comment]
> 28/5000 The problem you feedback has been supported, now the latest version has supported the function you feedback

What is this version number?

**Comment by meiyixiang** [comment]
123,20.4 supported, 4 in planning
