### ISSUE TITLE
Programs and Dock turns squared instead of round when running AppImage programs

### ISSUE THREAD

**Issue by MG32Codes** [linuxdeepin/developer-center#1991]
When running AppImage programs on Deepin, all programs and dock round edges turn squared. Dock becomes a solid color instead of transparent. Running the newest version as of right now. This has been happening even after updates have came out and I'm guessing no one has reported or cared to report the issue so I hope this gets fixed.

**Comment by aiamuzz** [comment]
> When running AppImage programs on Deepin, all programs and dock round edges turn squared. Dock becomes a solid color instead of transparent. Running the newest version as of right now. This has been happening even after updates have came out and I'm guessing no one has reported or cared to report the issue so I hope this gets fixed.

would be good if you posted a screenshot ... makes things clearer ... 

Open Deepin Screenshot application ... select the full screen ... Ctrl+c ... and paste it here ... the image will directly be attached to your post here ... saves a lot of trouble having to save the screenshot and attaching it here ...

**Comment by MG32Codes** [comment]
Sure thing! Sorry for not doing that earlier.
![image](https://user-images.githubusercontent.com/69671216/100521002-89028100-3166-11eb-8e04-71e1c953d16b.png)

**Comment by MG32Codes** [comment]
Another issue found... I guess. While an AppImage is running, screen recording is disabled.

**Comment by justforlxz** [comment]
![image](https://user-images.githubusercontent.com/12298476/151910509-e4c01c62-62ef-4cc1-b782-c5739838892a.jpeg)

**Comment by justforlxz** [comment]
It has been fixed
