### ISSUE TITLE
Missing git tag for deepin-desktop-base 2020.11.04 release

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#1993]
deepin-desktop-base 2020.11.04 is found in community edition but there is no such tag in the corresponding repository.

The issues tab is disabled in that repo, so I opened this here.

**Comment by justforlxz** [comment]
tag updated.

**Comment by justforlxz** [comment]
issues tab is enabled now.

**Comment by justforlxz** [comment]
tag updated.
