### ISSUE TITLE
[Feature Request] Alt+Tab is too sluggish

### ISSUE THREAD

**Issue by raspin0** [linuxdeepin/developer-center#1996]
I'm heavily utilizing alt+tab to move around applications and I have to tell you, in deepin it's very slow(to a point when it's extremely annoying).
It's not dynamic, it shouldn't show up with any kind of delay and juggling should be remarkably faster. 

Any kind of tweak in the settings would be much appreciated! :)

**Comment by Augustus879** [comment]
There were 300ms delay for key pressing and 200ms animation for highlighter moving. They will change to[ 90ms](https://github.com/linuxdeepin/deepin-kwin/blob/65dfdbd4480211cedb3035e75b502ea9f10460d4/tabbox/tabbox.cpp#L474) and [80ms](https://github.com/linuxdeepin/dde-kwin/blob/444562c6db6bc0b5a057f6906b5b0ac74f2d34b0/tabbox/thumbnail_grid/contents/ui/main.qml#L167).

**Comment by justforlxz** [comment]
> There were 300ms delay for key pressing and 200ms animation for highlighter moving. They will change to[ 90ms](https://github.com/linuxdeepin/deepin-kwin/blob/65dfdbd4480211cedb3035e75b502ea9f10460d4/tabbox/tabbox.cpp#L474) and [80ms](https://github.com/linuxdeepin/dde-kwin/blob/444562c6db6bc0b5a057f6906b5b0ac74f2d34b0/tabbox/thumbnail_grid/contents/ui/main.qml#L167).
> @justforlxz

that's great!

**Comment by vesterlay** [comment]
@Augustus879 It's slightly too fast now. I found what I want to achieve tho. I didn't manage to compile master kwin on my end, so please try slowing it down to 120ms and 110ms and use this command `kwriteconfig5 --file ~/.config/kwinrc --group TabBox --key DelayTime 0` then restart `kwin_x11` https://zren.github.io/kde/#show-alt-tab-popup-as-fast-as-possible

**Comment by myml** [comment]
It seems to have been solved. I can close this issues? @raspin0

**Comment by raspin0** [comment]
Okay, I will close this.
