### ISSUE TITLE
[manjaro] Cannot scale the display more than 1.25

### ISSUE THREAD

**Issue by moham96** [linuxdeepin/developer-center#1997]
Hi,
I have a 4k screen with up to 3840x2160 resolution, I want to scale the desktop to my screen size so after setting the correct resolution in the control-center if I try to use a scale factor of 1.25 it's fine but if I increase it any further like 1.5 or 1.75 then it's not getting saved and returns to 1.25
I'm using manjaro stable with the latest updates from deepin

Regards

**Comment by justforlxz** [comment]
Hi, are you waiting for the adjustment to be completed, there will be a notification. It takes a long time to adjust when the window factor is greater than 1.5.

**Comment by myml** [comment]
Because there is no confirm for a long time, I close it.
