### ISSUE TITLE
LibreOffice 7.0.2 and 7.0.3 icons do not appear on the DDE ARCH and ARCO Linux Rolling start menu and desktop

### ISSUE THREAD

**Issue by serial02** [linuxdeepin/developer-center#2001]
Hello DDE Team

Does anyone know how to fix this situation for LibreOffice 7.02 icons. and 7.0.3 do not appear in the DDE ArchLinux Rolling and DDE ArcoLinux Rolling start menu, much less on the desktop?
Other DDE distributions work normally.

https://twitter.com/edsonmartim/status/1321518018665525252
https://twitter.com/edsonmartim/status/1321937478442487810

**Comment by Cardellino** [comment]
Can only confirm that ....
No more icons are displayed

**Comment by mendiromania** [comment]
+1 after installing kwin lots of the icons from the icon themes went missing

**Comment by Cardellino** [comment]
Also with me with Arch Linux x86_64, kernel 5.11.7-arch1-1.
With LibreOffice 7.1.1-2 no icons are displayed either.

**Comment by babyfengfjx** [comment]
In Deepin this issue is ok , @felixonmars ,Thanks for helping to confirm this problem in arch.

**Comment by serial02** [comment]
Hi,

 After installing from the new Arch DDE 20.2 with Archinstall 220601, the icons were ok, only one or the other was transparent. 

 Most of the time, the menu icon is transparent after any new app installation, but when restarting they were all showing.
 As we install new applications, after restarting a good portion of the installed applications became transparent, including those that continue to be visible.

 There seems to be a predominance of applications being transparent or icons with the Deepin logo appearing, as can be seen in the video below.


https://user-images.githubusercontent.com/32621790/171960914-e016d7e4-559f-44aa-a073-38de44b89523.mp4


I hope that in this log below, the problem that is causing this icon transparency can be identified.


[Log DDE 20.2 Archlinux -journalctl -p 3 --no-pager]( https://pastebin.com/wBeiN25j )

**Comment by serial02** [comment]
Observation:

 In Fedora 36 with DDE 20.2 in Deepin-Kwin mode, this transparency does not occur in the menu icons and in the central search screen, as can be seen in this video below:

 What is different in Fedora and Arch for this anomaly to occur in terms of icon quality?


![Screenshot_Fedora36DDE20 2_2022-06-04_20:44:23](https://user-images.githubusercontent.com/32621790/172029811-cbdac499-df31-4568-9b08-6446d4dd7722.png)



https://user-images.githubusercontent.com/32621790/172029827-1b1b11c4-027a-440c-968d-8ede4d82d408.mp4

**Comment by babyfengfjx** [comment]
I wonder if the problem is still there on the latest version?

**Comment by Cardellino** [comment]
With me under Arch Linux the icons are displayed.
LibreOffice version 7.5.0.3

**Comment by babyfengfjx** [comment]
Are there still issues that cannot be displayed in the DDE ARCH environment? I do not know if the issue can be closed currently?

**Comment by babyfengfjx** [comment]
Based on some friends in the new version of the normal display, this issue is also relatively long ago, we first to close the processing, such as the follow-up of new issues, thanks for continuing to submit issues.
