### ISSUE TITLE
Deepin V20 1003 update for Deepin V20.1 1005-Beta on 12/15/2020 at 21: 53h

### ISSUE THREAD

**Issue by serial02** [linuxdeepin/developer-center#2003]
Hello Deepin V20 1005 Team

Despite some inconsistencies and some errors presented in the journalctl, I want to congratulate the entire team of developers Deepin for the beautiful work of correcting most of the problems presented by all users in the community so far.

In my view, version 1005 is much better than version 1003, at least here a lot that was not working, like keepassxc 2.6.2 via flatpak is back to working normally. I inform you that all installed flatpaks are functioning normally. The Deepin V20.1 version is faster, with no freezes, no errors in the dde-dock and startdde so far, where I hope it stays that way.

Following post-installation report:

During installation, an error was presented, where it is necessary to confirm twice in order to complete the update. Error already known as can be seen here: (https://bbs.deepin.org/post/206401), where I hope that in this version 1005 the same situation is not happening.

Note: I will only know if the problem persists after new package updates for version 1005 come.

![Captura de Tela_select-area_20201215223320](https://user-images.githubusercontent.com/32621790/102355074-209b0880-3f8a-11eb-9f2e-99166285ee32.png)

Error information at the time of installation:
**Failed to preset unit: Unit file /etc/systemd/system/samba-ad-dc.service is masked.**

Below is the complete update report for Deepin V20.1 1005 with 137 updated packages and 6 new packages installed.

**Deepin V20 1003 update for Deepin V20.1 1005-Beta, 12/15/2020 at 9:53 pm**
https://pastebin.com/sEg0CLj8
https://pastebin.com/raw/sEg0CLj8

After restart there is the information that the updates were successfully performed:

![WhatsApp Image 2020-12-16 at 00 03 48](https://user-images.githubusercontent.com/32621790/102355686-f8f87000-3f8a-11eb-85f5-43b76b99293b.jpeg)

The restart occurred normally, where the applications are opening normally.

Here are the apps that apparently have some problems:

Calculator-Deepin does not appear the signs of the buttons +, -, x and ÷.

![Captura de Tela_deepin-calculator_20201215225129](https://user-images.githubusercontent.com/32621790/102355977-60162480-3f8b-11eb-8115-b0707d09c655.png)

The Deepin Log Viewer is not yet able to export Logs, the situation has been previously reported as can be seen in this post (https://bbs.deepin.org/post/204226).

Link to the Deepin Log Viewer GIF image
https://imgur.com/3PswA0h

New version of Recovery does not appear in the GUI on the launcher and in the Control Center.
It can only be opened by the terminal and, once opened, the icon has no worked image and can only be closed by the icon on the taskbar, using the "force exit" option, because if it closes by X or restarts by the open application it will seek the factory restore option.

![Captura de Tela_dde-desktop_20201215225540](https://user-images.githubusercontent.com/32621790/102357191-d7988380-3f8c-11eb-8528-90f12272f9a7.png)

After restarting, no further updates were released.

```
sudo apt update
Senha
[sudo] senha para edson: 
Verificação Bem-sucedida
Atingido:1 https://brave-browser-apt-release.s3.brave.com stable InRelease
Atingido:2 https://community-packages.deepin.com/deepin apricot InRelease                            
Atingido:3 https://community-packages.deepin.com/printer eagle InRelease                             
Atingido:4 https://deb.opera.com/opera-stable stable InRelease                                       
Atingido:5 https://repo.skype.com/deb stable InRelease                                               
Atingido:6 http://packages.microsoft.com/repos/edge stable InRelease                                 
Atingido:7 https://community-store-packages.deepin.com/appstore eagle InRelease                      
Atingido:8 https://linux.teamviewer.com/deb stable InRelease                                         
Atingido:9 https://proposed-packages.deepin.com/dde-apricot unstable InRelease                       
Atingido:10 https://download.sublimetext.com apt/stable/ InRelease                     
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
All packages are up to date.
sudo apt full-upgrade
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
Calculando atualização... Pronto
0 pacotes atualizados, 0 pacotes novos instalados, 0 a serem removidos e 0 não atualizados.
sudo apt dist-upgrade
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
Calculando atualização... Pronto
0 pacotes atualizados, 0 pacotes novos instalados, 0 a serem removidos e 0 não atualizados.
flatpak update
Looking for updates…
Nothing to do.
```

![Captura de Tela_dde-control-center_20201215224451](https://user-images.githubusercontent.com/32621790/102357678-5988ac80-3f8d-11eb-865d-ef0f36ee79a7.png)

The flatpaks problem was solved in this new version of Deepin V20.1 1005-Beta, where the flatpaks I use are evolution, kodi and keepassxc 2.6.2, where they are all working normally without crashes.

Note: The problem that kept keepassxc flatpak in version deepin v20 1003 has been solved in this new version 1005. It is now opening normally \o/.

![Captura de Tela_keepassxc_20201215234727](https://user-images.githubusercontent.com/32621790/102357982-b84e2600-3f8d-11eb-8cec-69a20ce5c2ff.png)

Deepin's screen recorder continues to use 100% CPU when recording full-screen GIF images, as already reported in this post (https://bbs.deepin.org/post/206459). If there is an open browser with several tabs, it will lock the “system” where it only restarts after turning off the computer button.

Here is another GIF image reporting the same problem, after updating this new version Deepin V20.1 1005-Beta.
https://imgur.com/wx2cQqm
https://imgur.com/JmHuXTQ

Here is my configuration data:

```
OS: Deepin 20.1 Beta x86_64
Kernel: 5.8.14-amd64-desktop
Uptime: 3 hours, 41 mins
Packages: 1895 (dpkg), 14 (flatpak) 
Shell: bash 5.0.3 
Resolution: 1920x1080 
DE: Deepin 
WM: KWin 
WM Theme: light/deepin 
Theme: deepin [GTK2/3] 
Icons: bloom [GTK2/3] 
Terminal: deepin-terminal 
Terminal Font: Noto Mono 11 
CPU: Intel i3 540 (4) @ 3.067GHz 
GPU: Intel Core Processor 
Memory: 3324MiB / 7697MiB
```

**After a new restart I am sending new journalctl reports for analysis and action of the inconsistencies and errors that still remain in this new version 1005.**

Deepin V20.1 1005 journalctl -p 3 -xb on 12/16/2020 at 01: 28h
https://pastebin.com/7RyikujJ
https://pastebin.com/raw/7RyikujJ

Deepin V20.1 1005 journalctl -xb -p 3 12/16/2020 at 01: 36h
https://pastebin.com/v5x64ZPs
https://pastebin.com/raw/v5x64ZPs

Deepin V20.1 1005 journalctl -xe on 12/16/2020 at 01: 41h
https://pastebin.com/8WvhWdmf
https://pastebin.com/raw/8WvhWdmf

Deepin V20.1 1005 journalctl -p 3 on 12/16/2020 at 01: 46h
https://pastebin.com/bgFqAtCA
https://pastebin.com/raw/bgFqAtCA

Deepin V20.1 1005 journalctl -p 2 on 12/16/2020 at 01: 53h
https://pastebin.com/GvLhQdwz
https://pastebin.com/raw/GvLhQdwz

Deepin V20.1 1005 DMESG on 12/16/2020 at 09: 38h
https://pastebin.com/5Df9Vzme
https://pastebin.com/raw/5Df9Vzme

The problem of having to confirm twice in order to carry out an update still persists: Example: automatic update of Skype, as shown in the image below:

![Captura de Tela_deepin-terminal_20201216100934](https://user-images.githubusercontent.com/32621790/102360932-66a79a80-3f91-11eb-94f2-3acaafa466d7.png)

If I find any other situation that is relevant I will report at the appropriate time.

Your considerations

**Comment by myml** [comment]
after the new update It seems fixed
