### ISSUE TITLE
[deepin 20.1] Translation problems for pt-BR

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#2006]
The new version of deepin 20.1 (1010) still presents some problems of translation into Brazilian Portuguese.

<br>

**1 Applications (below) need to update the name translation; that is displayed in the launcher:**

> deepin-app-store 6.2.0.30-1
> deepin-boot-maker 5.4.8.3-c1-1
> deepin-editor 5.9.0.24-1
> downloader 5.2.0.22-1
> deepin-screen-recorder 5.8.0.61-1
> deepin-phone-assistant 5.1.0.44-1
> org.deepin.scanner 5.1.0.4-22
> 

![Captura de Tela_dde-launcher_20201228163651](https://user-images.githubusercontent.com/45263160/103367842-d5621900-4aa4-11eb-9e87-ec1faa85ef29.png)

<br>

**2. My country's mirrors are displayed in Chinese. This should be displayed in English (if possible, better in Brazilian Portuguese - pt-BR)**  

![Captura de Tela_select-area_20201228104550](https://user-images.githubusercontent.com/45263160/103367872-e6128f00-4aa4-11eb-8909-a14de2c5927b.png)

<br>

**3. Accented words do not follow the alphabetical order and are displayed at the end. The word "Área" must be displayed in front of all other folders; since it starts with the letter "A".**

![Captura de Tela_select-area_20201229134447](https://user-images.githubusercontent.com/45263160/103367879-eb6fd980-4aa4-11eb-9b49-4a84f2f03e9a.png)

<br>

deepin 20.1 (1010) / OsBuild=11031.108

**Comment by zhuxiujuancindy** [comment]
The first issue has been recorded and will be fixed.
The second issue has been forwarded to the product manager and will be fixed in next versions.
The third one: as Á is not an English letter, so it will not be improved this time.

**Comment by lxwndr** [comment]
I am the Brazilian Portuguese translation coordinator; and some translations have not yet been sent for release. The apps below have problems with the name that is displayed in the launcher.

**Note: The correct name for my language is in parentheses.**

> org.deepin.scanner 5.1.0.4-22 (_Assistente de Digitalização_)
> deepin-editor 5.9.0.49-1 (_Editor de Textos_)
> org.deepin.downloader 5.3.11-1 (_Gerenciador de Downloads_)
> deepin-screen-recorder 5.9.3-1 (_Captura de Tela_)
> org.deepin.browser 5.3.0.47-1 (_Navegador_)
>
> deepin-phone-assistant 5.1.0.44-1 (_Assistente de Telefone_)
>**Note: I cannot install this application on deepin 20.2; it generated some incompatibility with the new version of the system... I couldn't verify if the problem was solved or not.**
> 
> deepin-feedback 5.1.1-1 (_Feedback_)
>**Note: Shouldn't this app be removed from the launch? It is filed on the translation platform.**
>
> Input Method GUI Config Tool
> **Note: I believe that this application should be hidden. It seems to me only suitable for users of the Chinese language... For other languages, it is totally unnecessary. And that is not on the translation platform.**

**The other problems mentioned in the initial post still persist. #nameofmirrors**

![Capturar_dde-launcher_20210401104517](https://user-images.githubusercontent.com/45263160/113584452-4ca5cc80-9601-11eb-8b97-c0560aca6079.png)

![Capturar_dde-launcher_20210401104554](https://user-images.githubusercontent.com/45263160/113584463-50395380-9601-11eb-90c3-f8caca096214.png)

**Comment by hugok79** [comment]
"deepin-phone-assistant 5.1.0.44-1 (Assistente de Telefone)
Note: I cannot install this application on deepin 20.2; it generated some incompatibility with the new version of the system... I couldn't verify if the problem was solved or not."

This application appears in the store but is in Chinese...

![Captura de ecrã de 2021-04-15 11-50-49](https://user-images.githubusercontent.com/16929048/114858030-e11de500-9de0-11eb-9882-01057b447c19.png)
