### ISSUE TITLE
Outdated mirrors at mirrors.json

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#2007]
Currently, there are 3 mirrors in Brazil; and only 1 is correctly described in **/var/lib/lastore/mirrors.json**.

<br>

![Captura de Tela_deepin-editor_20201228105213](https://user-images.githubusercontent.com/45263160/103369796-d34e8900-4aa9-11eb-9b89-9d27d87e9a85.png)

The highlighted address is incorrect; below are all the mirrors in my country:

_Federal University of Amazonas (UFAM)_
http://mirror.ufam.edu.br/deepin

_Federal University of Parana (UFPR)_
https://deepin.c3sl.ufpr.br/deepin

_University of Sao Paulo (USP)_
http://sft.if.usp.br/deepin

<br>

deepin 20.1 (1010) / OsBuild=11031.108

**Comment by justforlxz** [comment]
Iwill update it.

**Comment by lxwndr** [comment]
I forwarded a list of other mirrors to @tinali722; I hope she adds that information to this document.

**Comment by tinali722** [comment]
Yes Alex. Well received. Thanks very much!


Tina




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linuxdeepin/developer-center"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月28日(星期天) 晚上11:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [linuxdeepin/developer-center] [deepin 20.1] Outdated mirrors at mirrors.json (#2007)





 
I forwarded a list of other mirrors to @tinali722; I hope she adds that information to this document.

**Comment by lxwndr** [comment]
The problem still persists in the new deepin 20.2. It seems that absolutely nothing has been done about it. This is tiring :(

deepin 20.2 (1040) / OsBuild=11038.001

![Capturar_deepin-editor_20210401103222](https://user-images.githubusercontent.com/45263160/113301962-f7527e00-92d5-11eb-9326-157d2f889bda.png)

**Comment by tinali722** [comment]
😔🥺 Let me confirm with developer team first Alex. So sorry for this...



发自我的iPhone


------------------ Original ------------------
From: Alex W. ***@***.***&gt;
Date: Thu, Apr 1, 2021 9:42 PM
To: linuxdeepin/developer-center ***@***.***&gt;
Cc: tinali722 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [linuxdeepin/developer-center] [deepin 20.1] Outdated mirrors at mirrors.json (#2007)





 
The problem still persists in the new deepin 20.2. It seems that absolutely nothing has been done about it. This is tiring :(
 
deepin 20.2 (1040) / OsBuild=11038.001

**Comment by myml** [comment]
Thank for your issues. We are reviewing these mirror sources.

**Comment by zccrs** [comment]
> Thank for your issues. We are reviewing these mirror sources.

We should not direct remove it, should use the deepin.c3sl.ufpr.br/deepin to instead of  linuxdeepin.c3sl.ufpr.br/deepin. From @lxwndr :

````
The highlighted address is incorrect; below are all the mirrors in my country:

Federal University of Amazonas (UFAM)
http://mirror.ufam.edu.br/deepin

Federal University of Parana (UFPR)
https://deepin.c3sl.ufpr.br/deepin

University of Sao Paulo (USP)
http://sft.if.usp.br/deepin
````

**Comment by lxwndr** [comment]
Do mirror addresses remain in /var/lib/lastore/mirrors.json? When analyzing this file, it continues to show only 1 (one) mirror from Brazil; there are 3 available here.

![Capturar_deepin-editor_20221121000620](https://user-images.githubusercontent.com/45263160/202955100-b598771a-b447-41cf-ab04-e8081560123c.png)



Note: This mirror is on HTTPS:
**Federal University of Amazonas (UFAM)
https://mirror.ufam.edu.br/deepin**



My system:

![Capturar_deepin-terminal_20221121000635](https://user-images.githubusercontent.com/45263160/202955141-3d4e1f87-15f9-4c84-9802-75e2208b7e62.png)

**Comment by myml** [comment]
@lxwndr Sorry, I shouldn't have closed this issues before, because I used an script to remove unavailable mirrors, but no new ones are added.
