### ISSUE TITLE
deepin-control-center在arch实机下segmentfault

### ISSUE THREAD

**Issue by asd-a** [linuxdeepin/developer-center#2011]
deepin-control-center在arch实机下segmentfault，虚拟机没问题

**Comment by felixonmars** [comment]
请尝试获取 backtrace 以助于分析错误（在我这里它没有崩溃）。

一般在崩溃后运行 `sudo journalctl` 并滚动到底部可以看到。

**Comment by asd-a** [comment]
好的，谢谢

**Comment by justforlxz** [comment]
有什么进展吗？ 一般在终端执行dde-control-center --show可以看到基本的崩溃情况。根据我的经验，大概率是deepin-desktop-schemas没有同步更新导致的。

**Comment by justforlxz** [comment]
No reply for a long time, close the request.
