### ISSUE TITLE
【功能建议】mac电脑解压文件以后，文件管理器会马上打开选中解压出来的文件夹

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2017]
mac电脑解压文件以后，文件管理器会马上打开选中解压出来的文件夹。我觉得mac这个功能非常实用，很多时候我们在deepin（UOS）解压了压缩文件以后都不知道解压出来的文件夹在哪里，**如果加一个弹出文件管理器，自动选中解压出来文件夹的功能**，用户体验会好很多，希望deepin改进。

**Comment by justforlxz** [comment]
这个是压缩工具做的，并不是文件管理器执行的动作。如果你使用我们的压缩工具，在完成解压后可以选择打开文件所在地。

**Comment by widon1104** [comment]
我昨天在deepinV20.1上面，在zip文件上面右键，选择解压到当前文件夹，并没有弹出文件管理器并选中解压文件夹啊，是不是默认没有使用带这种功能的解压工具，如果deepin自己开发的有解压工具，为什么不默认使用呢？

**Comment by widon1104** [comment]
今天晚上我回家试了一下，使用归档管理器解压，最后可以点击查看文件。但是这跟mac的体验非常不一致，mac是不用选择特定的应用程序，解压以后文件管理器就直接弹出选中解压出来的文件夹。
我觉得deepin可以模仿mac来做，这样用户解压文件体验会有提升。

**Comment by widon1104** [comment]
我想了一下，可以这样做，分2种情况
1）用户在压缩文件右键-解压到当前文件夹以后，文件解压到当前文件夹，然后**弹出解压文件夹上一层目录并选中解压出来的文件夹**
2）用户在压缩文件点击打开（或者点击解压），弹出压缩工具，点击解压以后**并不需要用户点击查看文件，就直接弹出文件夹上一层目录并选中解压出来的文件夹**

我觉得deepin应该要开始注重细节，这样可以增加用户粘性

**Comment by justforlxz** [comment]
> 我想了一下，可以这样做，分2种情况
> 1）用户在压缩文件右键-解压到当前文件夹以后，文件解压到当前文件夹，然后**弹出解压文件夹上一层目录并选中解压出来的文件夹**
> 2）用户在压缩文件点击打开（或者点击解压），弹出压缩工具，点击解压以后**并不需要用户点击查看文件，就直接弹出文件夹上一层目录并选中解压出来的文件夹**
> 
> 我觉得deepin应该要开始注重细节，这样可以增加用户粘性

这件事还有待考量，如果压缩包里有多个文件和文件夹，解压到此处的话，是应该创建一个同名的目录，还是直接解压所有的一级内容到当前目录？提出需求很简单，根据已有策略执行也很简单，但是我们毕竟不是apple,我们不能因为mac有，我们就也要有，甚至还要一模一样。

**Comment by widon1104** [comment]
1）我觉得如果压缩包里面有很多文件和文件夹的话，应该创建一个父目录，不创建目录解压到当前目录会很乱。
2）我不是觉得mac有，deepin也要有（mac感觉有些非主流设计不需要抄过来）我只是觉得这种简单又实用的功能可以抄过来

**Comment by justforlxz** [comment]
> 1）我觉得如果压缩包里面有很多文件和文件夹的话，应该创建一个父目录，不创建目录解压到当前目录会很乱。
> 2）我不是觉得mac有，deepin也要有（mac感觉有些非主流设计不需要抄过来）我只是觉得这种简单又实用的功能可以抄过来

那么为什么要根据新的需求再新增一个创建父目录呢？不能为了新功能而添加功能呀

**Comment by meiyixiang** [comment]
这个需求我们暂时不会考虑
