### ISSUE TITLE
【功能建议】deepin(UOS)应该避免让用户自己编写desktop文件

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2018]
现在windows，mac都不需要自己编写desktop，直接拖动图标到面板（或者直接安装）就可以把软件安装到系统，直接使用。
而现在deepin(UOS)如果遇到商店没有收录的软件，或者商店收录的软件版本太低，希望自己下载安装软件的话很可能会碰到需要自己编写desktop文件的情况，我觉得deepin(UOS)应该避免让用户自己编写desktop文件，这很烦，尤其对于大部分小白用户来说。

**Comment by justforlxz** [comment]
用户确实不应该自己创建desktop文件，那是开发者和下游打包者的工作。如果有类似的需求，欢迎在社区呼吁大家开发这样的功能。该issue先关闭了。
