### ISSUE TITLE
Strange conflicts deepin-desktop && deepin-file-manager

### ISSUE THREAD

**Issue by funilrys** [linuxdeepin/developer-center#202]
Can someone explain the following ?

![deepinscreenshot20170321174850](https://cloud.githubusercontent.com/assets/14127285/24159185/ba28b81e-0e5e-11e7-88ae-e14116406a85.png)

**Comment by felixonmars** [comment]
Well, you should answer Y for the first question, which is the default action anyway.

**Comment by funilrys** [comment]
I know, but is it normal to have deepin-desktop in conflict with deepin-file-manager ? 

For me they are two different things ...

**Comment by funilrys** [comment]
Okay just saw the changelog. 

> * 80569bf - Add desktop and debian install files (9 分钟前) <drgondjf>

Closing.

**Comment by felixonmars** [comment]
The commit log in Arch also indicates the merge between the two packages. Also you could search the package database and see it no longer contains a deepin-desktop package.

**Comment by funilrys** [comment]
My first reflex was here first @felixonmars :wink:

**Comment by hualet** [comment]
@felixonmars Merging dde-desktop into dde-file-manager will cause confilicts on Arch?

**Comment by felixonmars** [comment]
It's common approach to set all three arrays (provides/conflicts/replaces) together so user don't end up with an inconsistent state. Generally user will be prompted to replace deepin-desktop with deepin-file-manager in this case, and the default action is yes. Answering yes here will be the only needed action, and the conflict info will only be present if the user refuses to replace.
