### ISSUE TITLE
【功能建议】deepin(UOS)应该避免用户重装系统导致丢失/home的数据

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2020]
现在很多人安装deepin系统都是选择直接安装到硬盘，不自己分区，但是这样很危险，如果/home不单独分区，如果遇到重装系统的情况/home内容会丢失，所有数据包括用户配置都会丢失，用户体验非常不好。

希望deepin安装程序无论用户怎么选/home都单独分区（我觉得只要用户硬盘空间够，/分区只要40G就够了，swap 2～4G，其他都可以分配给/home）。下一次用户再安装deepin，安装程序识别到/home已经单独分区，就不格式化/home，自动挂载/home，只把系统重装到/分区即可。这样用户/home下的数据和配置都不会丢了，用户体验大大提升。

**Comment by justforlxz** [comment]
复用已有的home分区是有这个计划，但是在实施上存在问题:

- 多系统多home如何解决

**约束分区大小**

- 用户硬盘紧张，不希望分区(所以我们才提供手动模式，将决定权交给用户)
- swap分区的大小不应该限制，比如我是16G内存，如果swap小于16G，我将无法休眠系统。
- 同理，你不能要求根分区40G就足够了

在我的环境上，我安装了很多软件，我也跑了很多服务，目前根分区已经接近三百G了，我的home占用了五百G，如果根据你的提案，我完全无法正常使用deepin。

每个人的环境是不一样的，所以我们才只约束了最小。

**Comment by widon1104** [comment]
我的分区提案只是针对大多数用户，如果有特殊需求的用户可以选择自己分区，但是不管怎么样，希望deepin能够解决这个问题，保护用户的数据不丢失。

**Comment by duanyao** [comment]
即使 /home 不单独分区，重装系统也可以有保留 /home 的选项。ubuntu 就是这样的，选择不格式化/分区即可：
https://help.ubuntu.com/community/UbuntuReinstallation

**Comment by meiyixiang** [comment]
44/5000 
Full installation reshipment recognition to/home, will keep the data in the home, you can upgrade the system to experience this feature

**Comment by widon1104** [comment]
> 44/5000 Full installation reshipment recognition to/home, will keep the data in the home, you can upgrade the system to experience this feature

这个我看不懂，能详细解释一下uos&deepin是如何保护用户/home里面的数据的吗？
