### ISSUE TITLE
【bug】面板上面点击关闭所有，软件没被关闭，而且再也关闭不了

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2022]
系统：deepinV20.1 （1030）
复现步骤：打开网易云音乐，开始播放，然后在网易云音乐图标上面点击右键（不是系统托盘右键），这里面你会发现5个选项，点击最后一个关闭所有，这样你会发现音乐照常播放，而且系统托盘上面右键没有反应了，这时候如果想关闭网易云音乐只有注销，或者后台杀进程。

**Comment by myml** [comment]
after the new update It seems fixed
新版本好像修复了

**Comment by myml** [comment]
长时间没确认，这个问题先关闭了

**Comment by widon1104** [comment]
我现在用的uos家庭版，没用deepin，没法测试了，你们测试一下
