### ISSUE TITLE
[bug] the dock panel doesn't respect the ubication in a specific screen device, in a 3 screen device setup

### ISSUE THREAD

**Issue by nahuinlla101131** [linuxdeepin/developer-center#2023]
i have 3 monitors, and i set the dock to specific device, how ever, i don't know why, the dock panel sometimes appears in another monitor, and it doesn't want to appear in the main monitor
![IMG_20210202_153602](https://user-images.githubusercontent.com/19869532/106659442-bd325d80-656c-11eb-92cb-c789642fd36a.jpg)

it's possbie when i set to "smart hide" or "keep hide", and then i work with some developer software, minutes after, the dock panel, appears in another monitor. is annoying

**Comment by kegechen** [comment]
try this
gsettings set com.deepin.dde.dock.mainwindow only-show-primary true

**Comment by xmuli** [comment]
@nahuinlla101131  see [https://bbs.deepin.org/zh/post/202404](https://bbs.deepin.org/zh/post/202404)
