### ISSUE TITLE
Improved notifications

### ISSUE THREAD

**Issue by nandodevs** [linuxdeepin/developer-center#2025]
##### I would like to suggest adding the notification functionality, as shown in the image below.

![Icon](https://static.vecteezy.com/ti/vetor-gratis/p1/600587-icone-de-notificacaoial-quando-as-mensagens-recebidas-enviarem-um-som-e-exibirem-um-alerta-gr%C3%A1tis-vetor.jpg "Icon")

#### Thanks :)

**Comment by justforlxz** [comment]
looks great.

**Comment by meiyixiang** [comment]
Thank you for your advice, have been recorded

**Comment by meiyixiang** [comment]
Thank you for your advice, have been recorded

**Comment by meiyixiang** [comment]
V23 will cancel the notification icon without optimizing the V20 interface
