### ISSUE TITLE
cannot update 15.11

### ISSUE THREAD

**Issue by theoryhack** [linuxdeepin/developer-center#2027]
hello, just installed 15.11
when i perform an update using
sudo apt update i get the below error

Ign:1 http://packages.deepin.com/deepin lion InRelease
Err:2 http://packages.deepin.com/deepin lion Release  
  404  Not Found
Reading package lists... Done
E: The repository 'http://packages.deepin.com/deepin lion Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

kindly assist urgently

**Comment by xmuli** [comment]
the v15 repositories have been removed from memory and all have been merged into the v20 repository.

You can use this official repository in sources.list;
```bash
## Generated by deepin-installer
deb [by-hash=force] https://community-packages.deepin.com/deepin/ apricot main contrib non-free
#deb-src https://community-packages.deepin.com/deepin/ apricot main contrib non-free
```

**Comment by theoryhack** [comment]
very nice sorted thanks

**Comment by xmuli** [comment]
But you may be able to upgrade to v20 if you upgrade the whole disk directly (but it is more recommended to install v20 directly)

**Comment by theoryhack** [comment]
i have upgraded to v20 using the terminal, do i need to change the sources back to v20?, cos now after the upgrade the system theme doesnt look good

**Comment by xmuli** [comment]
> ```shell
> ＃＃由deepin-installer 
> deb生成[by-hash = force] https://community-packages.deepin.com/deepin/杏子主要贡献者免费
> ＃ deb-src https://community-packages.deepin.com / deepin /杏主要成分非免费
> ```

This is the deepin v20 source

**Comment by theoryhack** [comment]
i have deleted v15 sources and replaced with v20 sources and when i do the update i get the below error

E: Malformed line 1 in source list /etc/apt/sources.list (type)
E: The list of sources could not be read.

**Comment by xmuli** [comment]
??? new to linux, non-Chinese user? You can replace the source with, for example, the address of your nearest mirror source

**Comment by theoryhack** [comment]
am a non chinese user guess will ust have to change the distro, thanks for the time

**Comment by xmuli** [comment]
Upload this file of yours? `/etc/apt/sources.list` ?
