### ISSUE TITLE
No weather in Control Center

### ISSUE THREAD

**Issue by funilrys** [linuxdeepin/developer-center#203]
What are the allowed cities ? :smile_cat: 

:-1: 

![deepinscreenshot20170321181225](https://cloud.githubusercontent.com/assets/14127285/24160483/4591aef8-0e62-11e7-9b04-15fa71cc9dc5.png)
![deepinscreenshot20170321181246](https://cloud.githubusercontent.com/assets/14127285/24160486/45991094-0e62-11e7-8f77-e0ae1ef8f8f3.png)
![deepinscreenshot20170321181308](https://cloud.githubusercontent.com/assets/14127285/24160484/4596846e-0e62-11e7-807d-3de008339432.png)
![deepinscreenshot20170321181331](https://cloud.githubusercontent.com/assets/14127285/24160487/459a9de2-0e62-11e7-93b7-436474e9493f.png)
![deepinscreenshot20170321181358](https://cloud.githubusercontent.com/assets/14127285/24160485/4597cd74-0e62-11e7-8aaf-222f0677f59e.png)

**Comment by oberon2007** [comment]
For me this is working now. I can even search for cities, yeah! :laughing: :+1:

**Comment by hualet** [comment]
The geoname API limit is too easy to exceed... I've registered multiple KEYs to reduce the pressure, let's see if the approch works or not in the next release of dde-control-center.

**Comment by funilrys** [comment]
It's working :+1:

**Comment by funilrys** [comment]
@oberon2007 Am I the only one that don't have weather city saved ?

**Comment by oberon2007** [comment]
It works for me. The selected city is remembered when I relog or reboot.
