### ISSUE TITLE
打包好的软件请求上架软件商店

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2030]
论坛地址：https://bbs.deepin.org/zh/post/214937?id=214937&limit=20&offset=0&postId=1208358
软件网盘地址：链接: https://pan.baidu.com/s/1sA0_E5772J_Z1w5kRqSQNw  密码: ctud

这款软件是wine的kindle阅读软件，至今还没有发现明显的bug，几乎完美，使用wine6.3还修复了我以前提的某些电子书图片不显示的问题

稍微有点大，400M+，但是听说作者已经优化过大小，所以请求上架这款软件

**Comment by justforlxz** [comment]
现在我们有一个移植适配的渠道，你可以参加一下。

![deepin众测](https://user-images.githubusercontent.com/12298476/111930243-66b8b880-8af3-11eb-82de-1006efbe2c4f.png)
