### ISSUE TITLE
Bug report Annoying display bug

### ISSUE THREAD

**Issue by MuhannadYT** [linuxdeepin/developer-center#2033]
Hello there is a really annoying bug, where if I turn on custom in display settings it will let me drag windows above my main display.

My setup is like this🖥️___🖥️.    The monitor on 
    The left is _________🖥️🖥️🖥️.       One monitor but it is tall, I tried every thing to fix this bug nothing worked

**Comment by babyfengfjx** [comment]
Currently it is known that there is a problem with the display custom setting function after more than 2 monitors, we will submit the repair as soon as possible.

**Comment by babyfengfjx** [comment]
@xuqi27837288 请在V23尝试使用超过2个显示器的情况，看使用是否正常。

**Comment by xuqi27837288** [comment]
在v23上使用超过2个显示器暂未复现该问题~
