### ISSUE TITLE
Some help: hidden icons [DDE on Arch Linux]

### ISSUE THREAD

**Issue by carlosal1015** [linuxdeepin/developer-center#2034]
## Some help: hidden icons [DDE on Arch Linux]

Hello, I recently removed some Python packages and noticed afterwards that some deepin icons were hidden, for example the icons of programs on the desktop look transparent (see the images below).
I don't know about dependencies, maybe someone knows how to reverse this.

The system works fine, I only post this because I would like to know if there is an unannounced dependency.

![Screen Capture_select-area_20210315174327](https://user-images.githubusercontent.com/21283014/111231086-a09b3380-85b6-11eb-84aa-89873c9e2995.png)

![Screen Capture_select-area_20210315174335](https://user-images.githubusercontent.com/21283014/111231067-99742580-85b6-11eb-9eb7-a90ef541449f.png)

![Screen Capture_select-area_20210315174346](https://user-images.githubusercontent.com/21283014/111231045-8feabd80-85b6-11eb-95a7-d3136f4c5048.png)

![Screen Capture_dde-file-manager_20210315174614](https://user-images.githubusercontent.com/21283014/111231030-895c4600-85b6-11eb-80e2-b602eec9c86c.png)

![Screen Capture_dde-file-manager_20210315174627](https://user-images.githubusercontent.com/21283014/111230989-79dcfd00-85b6-11eb-891d-50ff277cf1eb.png)

![Screen Capture_dde-dock_20210315174637](https://user-images.githubusercontent.com/21283014/111230952-692c8700-85b6-11eb-9403-a40833792a41.png)

After that, I reinstalled the [`deepin`](https://archlinux.org/groups/x86_64/deepin) and [`deepin-extra`](https://archlinux.org/groups/x86_64/deepin-extra) groups and replaced the packages `cogl` by `deepin-cogl` and `clutter` by `deepin-clutter`.

Thanks in advance, I could share more logs if is useful.

**Comment by kreon28** [comment]
Looks like the same issue
https://github.com/linuxdeepin/deepin-icon-theme/issues/38

**Comment by carlosal1015** [comment]
Hi @kreon28, today I do full upgrade and the issue vanished,
![image](https://user-images.githubusercontent.com/21283014/111872078-82895680-895b-11eb-87e7-078256762fe2.png)

I will close the issue soon unless someone mentions with photos that it still features the hidden icons.

**Comment by kreon28** [comment]
I confirm. The issue is gone. The key thing is that kiconthemes has been upgraded to 5.80.0-2 and the problem is solved.
