### ISSUE TITLE
General RTL Languages and Layout Support

### ISSUE THREAD

**Issue by noor-codes** [linuxdeepin/developer-center#2035]
## RTL Languages Support

There is no first-class support for RTL languages like Arabic and Persian. The text looks awkward and it's almost not readble.
![image](https://user-images.githubusercontent.com/28804764/111286880-4a82ca80-8660-11eb-8dcf-20b711c6b62d.png)

**Comment by justforlxz** [comment]
This is an international community, and we recommend using English for communication. I did not understand your request, can you describe the specific problem?

**Comment by Noorullah-Ahmadzai** [comment]
I know it's an international community, I've written everything in English.

Here is what in trying to say:
- There is no support for RTL (right to left) languages.
- The font looks akward.
- The none-English text is written in Arabic in deepin OS which it looks horrible. 

I hope this issue is resolved in the next upgrade.

**Comment by justforlxz** [comment]
> I know it's an international community, I've written everything in English.
> 
> Here is what in trying to say:
> 
> * There is no support for RTL (right to left) languages.
> * The font looks akward.
> * The none-English text is written in Arabic in deepin OS which looks horrible.
> * I took random Arabic words and took a screenshot of it on DeepinOS to show you the problem.
> 
> I hope this issue is resolved in the next upgrade.

I understand, but this requires the software to adapt to different languages. In addition to the issue page of github, are there other software that have such problems?

**Comment by Noorullah-Ahmadzai** [comment]
All the software have the same issue, I don’t know the technical reason behind it. 
Maybe it’s because there is no default good font for RTL languages. 

I have this issue across multiple apps. I can surly say all the apps.

**Comment by Noorullah-Ahmadzai** [comment]
![image](https://user-images.githubusercontent.com/28804764/112881534-0ae8c380-90e1-11eb-85ec-671aea7fe96e.png)
### I tried changing the entire system language to Persian and it still looks awkward!

**Comment by Noorullah-Ahmadzai** [comment]
I believe this is the result of a good rtl default font! 
I visited a few websites today which was looking good.

**Comment by justforlxz** [comment]
I see, the focus is that we use a fixed alignment, but some languages are typeset in other ways, we did not consider. I will submit comments.

**Comment by Noorullah-Ahmadzai** [comment]
I hope this issue is resolved soon... A vast majority of the world is using RTL-based languages. Especially in Asia

**Comment by meiyixiang** [comment]
We don't have a good solution to this problem at present. I will include RTL language support into the requirements, but it may not be well solved in the short term.

**Comment by meiyixiang** [comment]
@zccrs I see the user has suggested a solution here please evaluate and see if it can be solved
