### ISSUE TITLE
Nvidia drivers, but no CUDA - Bug report 「缺陷报告」

### ISSUE THREAD

**Issue by DeadRosebud** [linuxdeepin/developer-center#2037]
Instructions on raising issues link isn't super clear.

But the issue is as the title says.

Cuda doesn't work. There is a script floating around that involves Debian backports, but it didn't work for me. Others have had success apparently.

**Comment by justforlxz** [comment]
hi, I don't understand, you mean you need cuda driver?

**Comment by DeadRosebud** [comment]
Correct.

Usually cuda works after installing the graphics driver. Here it isn't working.

**Comment by justforlxz** [comment]
> Correct.
> 
> Usually cuda works after installing the graphics driver. Here it isn't working.

According to my experience, I installed `nvidia-cuda-toolkit nvidia-profiler nvidia-visual-profiler nvidia-cuda-doc nvidia-cuda-dev`. Under deepin, the nvidia driver usually only contains the display driver and does not provide the cuda driver. , They are in other packages.

here is my test blog: https://blog.justforlxz.com/2018/06/28/%E5%9C%A8DeepinLinux%E4%B8%8B%E4%BD%BF%E7%94%A8nVidia-CUDA/

it's Chinese blog :)

**Comment by DeadRosebud** [comment]
Thanks for your reply, also sorry, I'm an insomniac, and often have problems concentrating enough to be understood. My original post was poorly structured due to a lack of sleep.

I've tried your method, but it isn't working.

I guess I'll be staying on Ubuntu Cinnamon for a while until hopefully a new Deepin release has cuda automatically installed like other distros.

Again thanks for your suggestion.
