### ISSUE TITLE
where can i get libdeepin-pw-check from?

### ISSUE THREAD

**Issue by hillwoodroc** [linuxdeepin/developer-center#2038]
I see deepin-control-center brings a new library libdeepin-pw-check, but i can't find libdeepin-pw-check anywhere. Do you forget release this project?

**Comment by justforlxz** [comment]
This is a new repository, I will release it.

**Comment by xmuli** [comment]
@hillwoodroc Synchronization has been completed, see[deepin-pw-check](https://github.com/linuxdeepin/deepin-pw-check)
