### ISSUE TITLE
newly created user not available for login

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/developer-center#204]
I just created a new user in control-center but in lightdm-deepin-greeter the switch user option is not available.

**Comment by SalahAdDin** [comment]
Is there this bug yet?

**Comment by sbwtw** [comment]
@jouyouyun

**Comment by jouyouyun** [comment]
@oberon2007 What is the version of deepin-daemon?

**Comment by jouyouyun** [comment]
No respond, closed!
