### ISSUE TITLE
Can't make a comment at bbs.deepin.org

### ISSUE THREAD

**Issue by vesterlay** [linuxdeepin/developer-center#2042]
Every time I want to submit a comment I receive this error

![image](https://user-images.githubusercontent.com/39202451/112067456-5f7fc200-8b68-11eb-82b0-020b384f73fb.png)

**Comment by justforlxz** [comment]
hi, what is your id? i will check it!

**Comment by vesterlay** [comment]
It seems it has repaired itself. I didn't get captcha the other day, but as I tried again today everything seems to work alright.
