### ISSUE TITLE
Better UI Proposal for the new "Verify or repair bad sectors feature"

### ISSUE THREAD

**Issue by AcidRain9** [linuxdeepin/developer-center#2045]
**Current UI:** 
![202103241736118372_磁盘管理器（英文）](https://user-images.githubusercontent.com/26188786/112483596-12bb0780-8d71-11eb-808b-75a81adac6e4.jpg)

**Proposal:**
![202103251732239434_proposal4(1)](https://user-images.githubusercontent.com/26188786/112480635-23b64980-8d6e-11eb-8141-6f7686467ac6.jpg)

Great job on the new Disk Manager but I feel the UI can be improved

**For Example:**  

**1.Verifying times is a very ambiguous term I don't understand what does it mean and what will it do.**

 
![202103251522366110_Capture4](https://user-images.githubusercontent.com/26188786/112480960-7132b680-8d6e-11eb-962f-30d4ef0d13bc.PNG)

****2.** Perhaps Verify or repair bad sectors could just be simplified**(renamed) **to Surface Test**
![202103251528556872_Capture6](https://user-images.githubusercontent.com/26188786/112481017-7e4fa580-8d6e-11eb-9fbf-b89f075ef8ca.PNG)

**References:**
EaseUS Partition Master:
![202103251530395214_Capture8](https://user-images.githubusercontent.com/26188786/112481065-8c9dc180-8d6e-11eb-9562-fcf40364d25b.PNG)

 

MiniTool Partition Wizard: 
![202103251531509959_Capture9](https://user-images.githubusercontent.com/26188786/112481116-96bfc000-8d6e-11eb-96a1-7bf6d9d098f7.PNG)

**3.I believe the Sectors Box size is too big and it should be scaled down**
![202103251538351446_Capture10](https://user-images.githubusercontent.com/26188786/112481334-cf5f9980-8d6e-11eb-9210-f39da54199e6.PNG)
![202103251539279921_Capture11](https://user-images.githubusercontent.com/26188786/112481365-d686a780-8d6e-11eb-82a3-cc696af30c87.PNG)
![202103251541147063_Capture13](https://user-images.githubusercontent.com/26188786/112481398-e1413c80-8d6e-11eb-83be-21a66946b3d1.PNG)

 

 

**And some more information about the current progress should be shown such as:** 

Total Sectors, Current Sector, Bad Sectors 
![202103251546481925_Capture14](https://user-images.githubusercontent.com/26188786/112481668-29605f00-8d6f-11eb-9ab2-e9b1eb9a1d41.PNG)

**Comment by meiyixiang** [comment]
翻译问题会在后期的版本中纠正，图形化界面优化与显示问题已经把建议反馈给了对于的产品经理。
