### ISSUE TITLE
【缺陷报告】Chrome浏览器不支持硬解码网络视频

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2049]
系统：deepinV20
Chrome版本：版本 89.0.4389.90（正式版本） （64 位）
打开了：Hardware-accelerated video decode 但是还是不支持硬解码视频
我的CPU是i5-8350U，用的核显hd620

mac和windows上的Chrome都支持硬解码视频，就是linux下的Chrome不支持，我觉得这是linux的劣势

**Comment by xmuli** [comment]
see [https://www.linuxuprising.com/2021/01/how-to-enable-hardware-accelerated.html](https://www.linuxuprising.com/2021/01/how-to-enable-hardware-accelerated.html)

**Comment by widon1104** [comment]
> see https://www.linuxuprising.com/2021/01/how-to-enable-hardware-accelerated.html

这个我早就试过了，不行，没法硬解，只有软解

**Comment by widon1104** [comment]
这个问题咋关了呢，问题还没解决呢

**Comment by widon1104** [comment]
我觉得解决这类问题不能光靠社区,需要linux发行版厂商的努力,

我觉得像统信软件这样的公司如果能解决这样的问题,才真正能够算的是一个操作系统厂商.
