### ISSUE TITLE
2017-03-23 更新系统之后桌面部分图标没了

### ISSUE THREAD

**Issue by choldrim** [linuxdeepin/developer-center#205]
![image](https://cloud.githubusercontent.com/assets/6734555/24228737/0ada5724-0fb1-11e7-8b72-f6a22bf42167.png)

**Comment by felixonmars** [comment]
Cannot reproduce here. Is it still an issue?

**Comment by funilrys** [comment]
Here either ... So, it's not an issue anymore or it's just another random issue :smile_cat:

**Comment by choldrim** [comment]
Oh, because I uninstalled the dde-file-manager by mistake :(
