### ISSUE TITLE
Icons And Pictures In App Store Of Deepin OS Aren't Showing Up :(

### ISSUE THREAD

**Issue by Notsofunny128** [linuxdeepin/developer-center#2054]
So, I just installed Deepin OS on my PC with dual boot windows and when i opened the app store to install some apps, no icons and images were appearing. I waited 10 mins and rebooted but nothing seemed to work. Also when i try to install apps at first it gives a dpkg error and then just randomly gets installed. I have no idea what to do because im new to linux. everything else seems to be fine. Here's some images-
![Screen Capture_dde-desktop_20210329164221](https://user-images.githubusercontent.com/81563862/112828338-ca298400-90b9-11eb-83b6-272f6de280f8.png)
![Screen Capture_deepin-app-store_20210329164123](https://user-images.githubusercontent.com/81563862/112828361-ce55a180-90b9-11eb-8888-3f9d288afddc.png)

**Comment by justforlxz** [comment]
It looks like you are not connected to the server, have you set up a proxy?

**Comment by AcidRain9** [comment]
The AppStore is working great in my case

**Comment by justforlxz** [comment]
Does it still need to be processed?

**Comment by ClayStan** [comment]
Due to no reply for a long time, close the issue, If the problem still exists, you can apply to reopen the issue
