### ISSUE TITLE
After using hdmi connection, audio stoped working

### ISSUE THREAD

**Issue by natan20200679** [linuxdeepin/developer-center#2055]
I'm using deepin version 20.1, and since the first time i started using hdmi connection, the computer only plays audio when using this connection, and even selecting the correct output device, after disconnecting hdmi, the audio does not work.

**Comment by justforlxz** [comment]
run this command in deepin-terminal and upload your output. 

`qdbus --literal com.deepin.daemon.Audio /com/deepin/daemon/Audio com.deepin.daemon.Audio.Cards`
`qdbus --literal com.deepin.daemon.Audio /com/deepin/daemon/Audio com.deepin.daemon.Audio.Sinks`
`qdbus --literal com.deepin.daemon.Audio /com/deepin/daemon/Audio com.deepin.daemon.Audio.Sources`

**Comment by justforlxz** [comment]
any?

**Comment by natan20200679** [comment]
I haven't done the verification yet. As soon as i do, i return. Grateful for the concern.

**Comment by justforlxz** [comment]
> I haven't done the verification yet. As soon as i do, i return. Grateful for the concern.

hi, I need to close this issue, and if there is new progress, I will reopen it.

**Comment by natan20200679** [comment]
Ok friend. Grateful.
