### ISSUE TITLE
【缺陷报告】应用商店里面wine的qq几乎到了不可用的地步了

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2058]
我只是一个qq的基本使用者，基本功能正常就能满足我的要求，但是现在基本功能都有问题
我在deepin论坛发了一个帖子：https://bbs.deepin.org/zh/post/217737
主要有2个大问题：
1）qq收不到消息
2）qq收不到图片
其实我感觉还有丢消息的情况，
所以，希望deepin （UOS）官方升级wine版本，或者什么其他的办法，把wine qq整的稳定可用一点。

**Comment by justforlxz** [comment]
wine管不到应用能不能正常收消息，但这事又不能联系鹅厂。 我在windows上用tim都觉得有问题，你可以试试其他版本的qq.
