### ISSUE TITLE
WiFi drivers for the card rtl8723de

### ISSUE THREAD

**Issue by alvarosamudio** [linuxdeepin/developer-center#2059]
Deepin does not have the WiFi drivers for the card rtl8723de only comes with bluethoot drivers of this card

**Comment by Zeno-sole** [comment]
![截图_选择区域_20220114153021](https://user-images.githubusercontent.com/43427321/149468602-585057f9-ba5f-4f4f-9c13-cd9fc343fe24.jpg)

**Comment by alvarosamudio** [comment]
> Noté que el kernel 5.10 tiene un controlador rtl8723de

at the time it was not working, now it is working correctly.
