### ISSUE TITLE
[arch linux] lightdm background doesnt change with wallpaper selection

### ISSUE THREAD

**Issue by psykotik1** [linuxdeepin/developer-center#206]

**Comment by psykotik1** [comment]
in previous versions of dde the lightdm wallpaper would be the same as the wallpaper selected inside dde, now it does not.

**Comment by Acris** [comment]
Hi, I tested for it, I don't have this problem.

**Comment by hualet** [comment]
@felixonmars ?

**Comment by felixonmars** [comment]
I don't have the problem either :/

**Comment by psykotik1** [comment]
i was under the idea that image files placed in ~/Pictures/wallpaper/ would appear on the login screen when selected as wallpaper since they appeared in the wallpaper selection. copied all my image files to /usr/share/wallpapers/deepin/, now when i select the wallpaper it shows up in the login screen.

**Comment by felixonmars** [comment]
The uri of the image should be put into /var/lib/AccountsService/users/yourname, and since lightdm was run as root it should be able to read that file. You may want to check the content of that file when your change doesn't work.

**Comment by hualet** [comment]
@psykotik1  Do you still have this issue ?

**Comment by funilrys** [comment]
@hualet I think we can close this ...

**Comment by SalahAdDin** [comment]
Where is the `lightdm` wallpaper setting in control center? I want to test this problem.

**Comment by sbwtw** [comment]
@SalahAdDin right click at your desktop and hit "set wallpaper"

**Comment by SalahAdDin** [comment]
@sbwtw Are you speaking about light dm wall paper or about desktop wallpaper?
Antergos lightdm actually have his own system for choose a wallpaper or put ramdom.

**Comment by SalahAdDin** [comment]
@hualet man, I have this issue too, I followed the steps and change the lightdm wall paper, doesn't change, it said that was changed, but after reboot my computer I didn't see the choosed wallpaper. This bug already persist

**Comment by hualet** [comment]
For this feature, you should be using lightdm & lighdm-deepin-greeter to get it work. @SalahAdDin

**Comment by SalahAdDin** [comment]
I'm using both, at least `lightdm-greeter` from deepin. It works very good but I can't change the wallpaper.
