### ISSUE TITLE
Kernel panic after trying to update to 20.02

### ISSUE THREAD

**Issue by vesterlay** [linuxdeepin/developer-center#2060]
While trying to update via appstore the screen just freezes. I tried manually run `apt update && upgrade` on TTY and I received `E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. ` after running dpkg kernel panic appears. It may have something to do with nvidia drivers, because I got some errors while updating

**Comment by xmuli** [comment]
We have received feedback early in the morning and our engineers are working on fixing this issue urgently。

**Comment by vesterlay** [comment]
Looks good. The update has just completed. I got some warnings along the way I screenshot below. 
![image](https://user-images.githubusercontent.com/39202451/113248824-f6155700-92bd-11eb-9623-8bf8101ceb29.png)
![image](https://user-images.githubusercontent.com/39202451/113248833-f9104780-92bd-11eb-8007-83e503bfdec9.png)

**Comment by theoryhack** [comment]
also experiencing the same freezing issue, mine freezing at systemd package after doing sudo dpkg --configure -a
perfroming sudo modprobe -r vfs_monitor there is no response

**Comment by emulienfou** [comment]
Same issue here, tried to execute `sudo modprobe -r vfs_monitor` but seems the resource is busy.

Also tried this without success:
```
sudo rmmod --force vfs_monitor
rmmod: ERROR: ../libkmod/libkmod-module.c:793 kmod_module_remove_module() could not remove 'vfs_monitor': Device or resource busy
rmmod: ERROR: could not remove module vfs_monitor: Device or resource busy
```

**Comment by vesterlay** [comment]
> also experiencing the same freezing issue, mine freezing at systemd package after doing sudo dpkg --configure -a
> perfroming sudo modprobe -r vfs_monitor there is no response
> 

**It's probably a bad idea(do at you own risk),** but as `modprobe` is busy open new terminal window and run `dpkg` simutanousely. After finished update you may have to force reboot `systemctl -i reboot`. That's what did the trick for me.

**Comment by vesterlay** [comment]
Looks like this issue has been resolved. Closing..
