### ISSUE TITLE
Bug report 

### ISSUE THREAD

**Issue by Noorullah-Ahmadzai** [linuxdeepin/developer-center#2063]
# Issue: Bug 

Just upgrade to Deepin 20.2. I am using the community version on Dell 5559!

Bugs: 
- Left click on the taskbar make it disappear!
- Left click on the desktop makes the taskbar disappear! 
- So many packages that used to work is now broken!

How am I supposed to work?

## is there a way to roll back at least?

`Please don't push broken upgrades. I use this OS at work and my team depends on me!`

**Comment by Noorullah-Ahmadzai** [comment]
https://user-images.githubusercontent.com/28804764/113357833-e2b7c980-9359-11eb-805a-4e1e4358421c.mp4

**Comment by Noorullah-Ahmadzai** [comment]
I can't play this video on my OS, count that broken too.

**Comment by AcidRain9** [comment]
> How am I supposed to work?

I suggest that you shouldn't immediately update, there will probably be some issues with a new update you should wait a few weeks before updating.

**Comment by Noorullah-Ahmadzai** [comment]
That's a good idea.
