### ISSUE TITLE
Login Loop 20.2

### ISSUE THREAD

**Issue by pablokere** [linuxdeepin/developer-center#2065]
New update with some problem and finally get a loop in login window

1) enter succesfully login
2) Try get desktop
3) show laptop brand in screen
4) Login screen again

**Comment by pablokere** [comment]
Solved! I removed my .config folder, then I could log again. But I lost all my settings.

**Comment by LuciusSomberlas** [comment]
how did you remove the .config folder?, am experiencing same issues, also how did you upgrade via terminal or iso?

**Comment by pablokere** [comment]
Lucius: CONTROL + F2 to start a command line while you are in login screen. Then you remove your .config folder and then restart.
Upgrade you can do it on the command line too.

**Comment by LuciusSomberlas** [comment]
How to remove the .config folder?
