### ISSUE TITLE
Monitor Multiple Extend! Pretty disaster!

### ISSUE THREAD

**Issue by pablokere** [linuxdeepin/developer-center#2067]
Why you broke display configuration like that, laptop + 2 monitors in extend mode, duplicated 3 screens.

**Comment by justforlxz** [comment]
hi, i'm so sorry. the new setting is not compatible with the old one. Need to reconfigure.

**Comment by justforlxz** [comment]
Can it be closed？

**Comment by ClayStan** [comment]
no reply,closed
