### ISSUE TITLE
Bug report「缺陷报告」Brightness keys stopped working ? (20.2)

### ISSUE THREAD

**Issue by xan105** [linuxdeepin/developer-center#2068]
Brightness can manually be changed in control center but ...
Pressing the fn keys (keyboard) can only reduce and/or increase brightness for **one** level (the popup bar won't move either way)

cf: https://www.reddit.com/r/deepin/comments/mhr6sg/brightness_keys_stopped_working_after_upgrade_to/

Is this a known issue ?

_Deepin 20.2 Kernel 5.11.10
NB: It worked fine with 20.1 and the same kernel_

**Comment by yxsos** [comment]
see : https://github.com/linuxdeepin/developer-center/issues/2075
