### ISSUE TITLE
Bug report on bluetooth

### ISSUE THREAD

**Issue by nextOver** [linuxdeepin/developer-center#2069]
## Issue: Bug report
<br>
After updating deepin to version 20.2 and kernel to 5.10 and 5.11 the bluetooth stopped working, and when investigating I get the message: "Bluetooth: hci0: don't support firmware rome."
Upon returning to the kernel 5.8.14 it works.

<br>

**Comment by justforlxz** [comment]
What is your hardware?  Execute the following command to upload the log.

```
sudo dmesg > /tmp/dmesg.log
sudo journalctl -b > /tmp/journal.log
lspci -v > /tmp/lspci.log
```

the log file in /tmp, dmesg.log journal.log  lspci.log

**Comment by geekkrug** [comment]
Same here. deepin 20.2 came with so many bugs. I have these: 

- Bluetooth stopped working after updating deepin to version 20.2. Readed other users had the same issues.
- Also artifacts on screen when 2-fingers pressed.
- VLC player not working (working with previous versions).

Temporal workaround for bluetooth: install kernel from lvtommy-linux-kernel. 
[lspci.log](https://github.com/linuxdeepin/developer-center/files/6369021/lspci.log)

**Comment by riodarmawan** [comment]
It's same here

[lspci.log](https://github.com/linuxdeepin/developer-center/files/6440295/lspci.log)
[journal.log](https://github.com/linuxdeepin/developer-center/files/6440296/journal.log)
[dmesg.log](https://github.com/linuxdeepin/developer-center/files/6440298/dmesg.log)

**Comment by aiamuzz** [comment]
@justforlxz ...

Same here ... v20 ... has broken inbuilt bluetooth ... same was working in the older Deepin out of the box(works fine on my Windows dual boot)

**Comment by Zeno-sole** [comment]
What model is your bluetooth chipset?

**Comment by nextOver** [comment]
> Qualcomm Atheros QCA9565 / AR9565 Wireless Network Adapter. It has already been fixed with updates.

**Comment by Zeno-sole** [comment]
Thank you for your support, now that the problem has been solved, I think this issue can be closed
