### ISSUE TITLE
Wrong number on click empty trash button

### ISSUE THREAD

**Issue by Acris** [linuxdeepin/developer-center#207]
![DeepinScreenshot20170324140938.png](https://ooo.0o0.ooo/2017/03/24/58d4b9e95fd6f.png)

GIF is here:
![deepin-screen-recorder_dde-file-manager_20170324140838.gif](https://ooo.0o0.ooo/2017/03/24/58d4b9c468823.gif)

**Comment by hualet** [comment]
@dragondjf @zccrs ?

**Comment by Acris** [comment]
It seems to be fixed.
