### ISSUE TITLE
deepin-compressor: Bug report 「缺陷报告」

### ISSUE THREAD

**Issue by latvianization** [linuxdeepin/developer-center#2071]
We are supporting file hosting service where files have permissions only read write. When those files are downloaded in zip and then extracted using built in archive manager they have wrong permissions. Access denied in properties. I have to change them manually. If i unzip same zip via bash, i can open files.

Please fix default archive manager exported file permissions. To always read/write regardless of original permissions

Sample zip: https://files.inbox.lv/ticket/b14eaf92f1e350a7785fd3a629bf481ee73b9ee5/test-permissions.zip

**Comment by z966768** [comment]
Hello, thank you for your feedback, we have made some changes, please pay attention to the follow-up version

**Comment by SuperEffie** [comment]
Due to no reply for a long time, closing this issue for now. If the problem still exists, please contact us and prvoide an another zip file to reopen the issue, or creating another issue.The zip file you provided we cannot download it now.Thank you~
Best wishes!
