### ISSUE TITLE
Screen brightness on laptops

### ISSUE THREAD

**Issue by latvianization** [linuxdeepin/developer-center#2075]
I have thinkpad E460 & Dell G7 both running deepin. On both laptops when I change screen brightness using keyboard shortcuts it changes by one increment and then its stuck. No matter how much i press keyboard shortcuts brightess does not change

**Comment by Malsasa** [comment]
> I have thinkpad E460 & Dell G7 ...
I can confirm exact same issue on ThinkPad T430 ([details here](https://linux-hardware.org/?probe=9a5ad3016a)) with Deepin 20.2.

**Comment by justforlxz** [comment]
it's fixed. https://github.com/linuxdeepin/startdde/commit/642845e485382045504fa8d8f916f7d8c2eeaf42   we will update startdde to 5.8.8

**Comment by Malsasa** [comment]
> it's fixed. [linuxdeepin/startdde@642845e](https://github.com/linuxdeepin/startdde/commit/642845e485382045504fa8d8f916f7d8c2eeaf42) we will update startdde to 5.8.8

Thank you very much, Deepin Developer. Nice to get in touch directly to you.

**Comment by justforlxz** [comment]
Is it solved?

**Comment by latvianization** [comment]
> Is it solved?

Yes! Thanks
