### ISSUE TITLE
LibreOffice 6 Looks Ugly on Deepin 20.2

### ISSUE THREAD

**Issue by Malsasa** [linuxdeepin/developer-center#2076]
I tried to run LibreOffice preinstalled on Deepin 20.2 and it looks ancient like Windows 95 or MSO 2003 unlike it should be. I fixed it by installing `libreoffice-gnome` package. Please include next Deepin releases with this package built-in.

Source: [Ubuntu Buzz](https://www.ubuntubuzz.com/2021/04/fix-libreoffice-looks-ugly-on-deepin-20.html).

Before:
![libreoffice ugly deepin](https://user-images.githubusercontent.com/3586695/115149769-21859900-a055-11eb-98e2-5609b0f23eac.png)

After:
![libreoffice beautiful deepin](https://user-images.githubusercontent.com/3586695/115149796-3e21d100-a055-11eb-992c-413db6f5a6e2.png)

As an addition, the version 7 with the Ribbon user interface also looks normal on Deepin after this fix:
![Screenshot_20210418143230](https://user-images.githubusercontent.com/3586695/115149850-745f5080-a055-11eb-98f2-1d2df803622b.png)

**Comment by eduardomozart** [comment]
In my case I had to install ``ibreoffice-gtk3`` to make it look right into Deepin 20.2.2. You can also install ``libreoffice-kde`` package, as it provides Breeze iconset, that I believe it's more appropriate to a more concise Deepin look'n'feel.

**Comment by justforlxz** [comment]
I don't think it's a problem because libreoffice supports skins, and the debian maintainers don't set a default skin, so the gtk theme won't install.

**Comment by eduardomozart** [comment]
I see, but I believe that the GTK theme should be preinstalled with the distribution as LibreOffice is built in into Deepin distribution.

**Comment by tsic404** [comment]
`libreoffice-gtk3` will be preinstall with the next version release.
