### ISSUE TITLE
Bug - Installing GIMP causes update loop 

### ISSUE THREAD

**Issue by vesterlay** [linuxdeepin/developer-center#2077]
Installing gimp causes an update loop after reboot.

Steps to reproduce: 
1. Install gimp
2. Reboot
3. Run updates from Control Center
4. Run `sudo apt update && sudo apt upgrade`

Updating gimp will bug control center resulting in empty update. Which also will mark gimp as upgradable when it's really not.

**Comment by Zeno-sole** [comment]
Please report your specific error message. In the case of the background update of the control center, apt cannot be updated, and dpkg has a process lock

**Comment by vesterlay** [comment]
Doesn't seem to reproduce anymore
