### ISSUE TITLE
[arch linux] option to disable workspace preview on workspace change

### ISSUE THREAD

**Issue by psykotik1** [linuxdeepin/developer-center#208]

**Comment by psykotik1** [comment]
feature request

**Comment by funilrys** [comment]
I don't think it's a good idea at all ... The previews are what make deepin :smile_cat: 

But an option in control center or dconf will be great for people like you :smile_cat: (Is it a problem with memory ?)

**Comment by wucke13** [comment]
+1

**Comment by hualet** [comment]
Close this issue due to long time no reply from the author of this issue.
