### ISSUE TITLE
support livecd mode

### ISSUE THREAD

**Issue by justforlxz** [linuxdeepin/developer-center#2081]
Livecd mode is not supported now, only the installation system is included. I think this function is necessary.

**Comment by justforlxz** [comment]
To support this operation, the following issues must be resolved first:
- [ ] Do turn off the screen
- [ ] Prohibit to lock the screen, including any means of locking

**Comment by meiyixiang** [comment]
Products include planning, but need some time, relatively complicated functions may be to 23 years.

**Comment by meiyixiang** [comment]
Products include planning, but need some time, relatively complicated functions may be to 23 years.
