### ISSUE TITLE
[Resource Request] Add mechanism for managing hybrid cards

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#2083]
The _PRIME_ technology was created to manage hybrid cards in laptops; allowing, to use the entire system on the integrated graphics card (iGPU) and certain applications on the dedicated graphics card (dGPU).

The Deepin has NEVER supported hybrid cards!

> **Intel / NVIDIA**: Users need to install the proprietary driver (a process that only advanced users know how to do), in order to be able to use the dGPU - while significantly reducing battery life - while keeping the iGPU completely inactive. Or, use the problematic open Bumblebee driver; which generates the same result (uses the dGPU, and inactivates the iGPU).
> 
> **Intel / AMD**: Users have never been able to use AMD's dGPU; as there is no proprietary driver available and the open source driver has installation problems (description below).
> 

The **PRIME GPU Offloading** mechanism allows any interface to do this management through the interface itself. For example, GNOME has been using this mechanism for many years:

![image](https://user-images.githubusercontent.com/45263160/116010230-1d78ee80-a5f4-11eb-940a-786fb605c41a.png)

![16309116421588774164gol1](https://user-images.githubusercontent.com/45263160/116010193-edc9e680-a5f3-11eb-8062-8503ef29bd9b.png)

More information: https://gitlab.freedesktop.org/hadess/switcheroo-control

About AMD's dGPU, an error occurs when installing some video driver packages (Source: https://wiki.debian.org/AtiHowTo):

![Capturar_20210425183836](https://user-images.githubusercontent.com/45263160/116010693-f07a0b00-a5f6-11eb-865d-0d851114b8a7.png)

![Capturar_20210425183843](https://user-images.githubusercontent.com/45263160/116010695-f374fb80-a5f6-11eb-815b-605528176487.png)

deepin 20.2 (1040) / OsBuild=11038.002

**Comment by justforlxz** [comment]
Requirement: Add bumblebee startup menu for the application @meiyixiang 
BUG: Package dependency error @Zeno-sole

**Comment by Zeno-sole** [comment]
You do not need to install firmware-amd-graphics, the system is already pre-installed with linux-firmware

**Comment by meiyixiang** [comment]
Your question has been recorded, such as the late no implementation, may consider by the right way to support function expansion of the plugin
