### ISSUE TITLE
[Resource Request] Allow the App Store to manage apps on AppImage, Flatpak and Snappy

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#2084]
With the advent of containerized packages (AppImage, Flatpak and Snappy) on Linux; users feel the need for a graphical interface to manage these applications.

It is extremely important that the App Store manages the [AppImageHub](https://appimage.github.io/apps), [Flathub](https://flathub.org) and [Snapcraft](https://snapcraft.io/store) services through its interface. The use of the system (application installation) will be more practical and integrated into the system design.

In some distributions, the App Store itself is managing these apps. For example:

![Screenshot from 2021-04-24 16-03-13](https://user-images.githubusercontent.com/45263160/116014045-9d5d8380-a609-11eb-8d2e-ce1cc4075828.png)

![Screenshot from 2021-04-24 16-04-18](https://user-images.githubusercontent.com/45263160/116014049-a189a100-a609-11eb-8be7-818c45a4aea2.png)

![image](https://user-images.githubusercontent.com/45263160/116014088-e0b7f200-a609-11eb-81cf-fa2dc4b3479c.png)

deepin-app-store 6.2.0.39-1
deepin 20.2 (1040) / OsBuild=11038.002

**Comment by lxwndr** [comment]
@probonopd

**Comment by probonopd** [comment]
We are providing a feed at https://appimage.github.io/feed.json in case you would like to integrate that.

**Comment by meiyixiang** [comment]
Your question has been recorded

**Comment by meiyixiang** [comment]
你好这个建议短时间内我们不会纳入规划，如后期有此规划会在Deepin.org进行公示。谢谢你的建议！
