### ISSUE TITLE
apt安装软件，如果因为各种原因依赖关系破坏有没有办法恢复

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2086]
有时候apt安装软件，依赖关系破坏，导致系统安装不起软件了或者软件运行不正常是一件很恼火的事情。
我以前就遇到过依赖关系破坏导致不能安装软件，重装系统的经历。
现在有没有方案恢复呢？
比如说建立软件镜像，如果某一时间依赖关系被破坏可以恢复到以前的某一个时刻，恢复安装软件的功能，让系统不至于崩溃
我举一个例子：
现在系统很多软件依赖libfreetype6这个软件，我不小心卸载了这个软件，那肯定出大问题了，有没有办法敲一个命令自动重新安装这款软件的对的版本，让系统恢复正常
再举一个例子：
deepin系统依赖python这款软件，我不小心把python卸载了，系统开始抽风，有没有办法敲一个命令，系统自动把python给我装好，让系统恢复正常

**Comment by justforlxz** [comment]
这个要看情况，越底层的文件被破坏，越难修复，最极端的情况是只能手动复制文件来恢复功能。

一般情况下可能在你执行的时候就看到会卸载很多软件，你就不应该继续执行了，你需要了解和明白你做的行为，操作系统没办法帮你兜底，它只提供机制，不提供策略。

如果你真的不幸卸载了很多软件包，可以查看`/var/log/apt/history`的内容，将卸载的软件包安装回来。
