### ISSUE TITLE
[Report Issue] The blur is not displayed correctly in the dock

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#2088]
When using the dock in fashion mode, with smart hide active; the dock blur is no longer displayed after the dock is first hidden - the blur is replaced by semi-transparency.

After login (blur):
![Capturar_select-area_20210501090757](https://user-images.githubusercontent.com/45263160/116782133-c80e6880-aa5d-11eb-89d6-b7bc67bb595a.png)

Return from dock after smart hide (semitransparency):
![Capturar_select-area_20210501090840](https://user-images.githubusercontent.com/45263160/116782137-ca70c280-aa5d-11eb-8bfc-5ef5b3d22c3a.png)

dde-dock 5.4.10-1
deepin 20.2 (1040) / OsBuild=11038.002

**Comment by justforlxz** [comment]
what is version of dde-kwin?  `apt-cache policy dde-kwin`

**Comment by lxwndr** [comment]
> apt-cache policy dde-kwin

![Capturar_deepin-terminal_20210507191735](https://user-images.githubusercontent.com/45263160/117513812-ea761980-af68-11eb-9415-c837fdf86b79.png)

Although I use the internal test channel; the problem also occurs on the standard channel.

**Comment by lxwndr** [comment]
This problem seems not to be repeated in recent versions of the system. For this reason, I am closing this issue.
