### ISSUE TITLE
[Bug report] Network discovery does not work and the samba service works partially

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#2089]
When using deepin on the company's internal network, the system does not display the other computers that are visible on the network. I performed the test with another distribution (Zorin OS), and this problem does not occur.

**The deepin does not display computers on the internal network:**

![Capturar_20210505221027](https://user-images.githubusercontent.com/45263160/117228108-bd9df700-adee-11eb-9e5c-1914b56c7f24.png)

**When typing the name (alphanumeric) of the other computer to access it via the network, an error message "_Error when mounting the device_" is displayed:**

![Capturar_dde-file-manager_20210501140709](https://user-images.githubusercontent.com/45263160/117228059-a4954600-adee-11eb-88b1-d88f3e23079a.png)

**When entering the IP (numeric name) of the other computer to access it via the network, the connection is successfully completed:**

![Capturar_20210502095317](https://user-images.githubusercontent.com/45263160/117228053-a101bf00-adee-11eb-8e53-9bccc9f930c3.png)

Allow deepin to display computers visible on the internal network; and that the connection via samba, can be made by the alphanumeric name of the computers - instead of exclusively the IP address number.

samba 2:4.9.5.8-1+security
dde-file-manager 5.2.18-1
deepin 20.2 (1040) / OsBuild=11038.002

**Comment by deepin-CD** [comment]
There were some mistakes on smaba configuration.
The Samba needs to reconfigure to fit your network.

**Comment by deepin-CD** [comment]
We will seriously consider your suggestion. Thanks for your suggestion.

**Comment by lxwndr** [comment]
Can someone help me correctly configure the samba?
