### ISSUE TITLE
Add mandatory D-BUS Protocol message: org.freedesktop.Notifications.GetCapabilities

### ISSUE THREAD

**Issue by BobbyBabes** [linuxdeepin/developer-center#209]
I was told that this was the proper place to report issues.
So I'm referring to this issue that I opened earlier : https://github.com/linuxdeepin/dde-desktop/issues/13

**Comment by jouyouyun** [comment]
@hualet

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
