### ISSUE TITLE
[Bug report] Curved corners are not displayed correctly by Intel Graphics

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#2090]
After installing deepin on a computer with the Intel Core 2 Duo E7500 processor, I noticed that the curved corners are not displayed correctly, despite the "window effect" being active.

The rest of the system's visual effects are displayed correctly.

![photo1620243076](https://user-images.githubusercontent.com/45263160/117233626-deb81500-adf9-11eb-889b-4de80a99b3b7.jpeg)

deepin 20.2 (1040) / OsBuild=11038.002

**Comment by justforlxz** [comment]
try `rm -rf ~/.config/k*rc` in deepin-terminal and `killall kwin_x11`.

**Comment by lxwndr** [comment]
@meiyixiang

**Comment by lxwndr** [comment]
I'm closing this issue due to lack of responses; and also, for no longer using this old hardware.
