### ISSUE TITLE
[问题] deepin20.2 无法安装在 11代intel的电脑上。

### ISSUE THREAD

**Issue by jackyPang10086** [linuxdeepin/developer-center#2091]
今年刚发布的电脑全部无法安装deepin20.2,
你们到底要拖到什么时候才能修复?
这是我在论坛里发布的贴子: https://bbs.deepin.org/zh/post/217848

**Comment by zhboner** [comment]
没有deepin论坛的账号，所以在这里回复你。看到你的描述，感觉是显卡驱动的问题。在grub按e键，linux的那一行加上nomodeset再试试

**Comment by jackyPang10086** [comment]
> 没有deepin论坛的账号，所以在这里回复你。看到你的描述，感觉是显卡驱动的问题。在grub按e键，linux的那一行加上nomodeset再试试

你好，可能我没有描述清楚。
我的情况是：用 ventoy安装 deepin20.2，点击 deepin选项之后，直接黑屏，然后左上角下划线在闪，风扇狂转。根本无法进入 grub中。

**Comment by justforlxz** [comment]
> > 没有deepin论坛的账号，所以在这里回复你。看到你的描述，感觉是显卡驱动的问题。在grub按e键，linux的那一行加上nomodeset再试试
> 
> 你好，可能我没有描述清楚。
> 我的情况是：用 ventoy安装 deepin20.2，点击 deepin选项之后，直接黑屏，然后左上角下划线在闪，风扇狂转。根本无法进入 grub中。

i5 11代是测试过的，grub里我记得有一个safe graphics的选项，尝试用一下这个？

**Comment by jackyPang10086** [comment]
> > > 没有deepin论坛的账号，所以在这里回复你。看到你的描述，感觉是显卡驱动的问题。在grub按e键，linux的那一行加上nomodeset再试试
> > 
> > 
> > 你好，可能我没有描述清楚。
> > 我的情况是：用 ventoy安装 deepin20.2，点击 deepin选项之后，直接黑屏，然后左上角下划线在闪，风扇狂转。根本无法进入 grub中。
> 
> i5 11代是测试过的，grub里我记得有一个safe graphics的选项，尝试用一下这个？

哥，你看明白我贴吧里的描述了吗？
> 直接进入黑屏，还有一个小横杠闪烁，一直闪烁。。。
 根本没法选择其他选项。
你要是说测试过 11代i5。难道是我们这些用 11代i5的电脑都是废了吗？
[intel 的 11代NUC 装不上](https://bbs.deepin.org/zh/post/220111)
[]()
[]()
[]()

**Comment by justforlxz** [comment]
> > > > 没有deepin论坛的账号，所以在这里回复你。看到你的描述，感觉是显卡驱动的问题。在grub按e键，linux的那一行加上nomodeset再试试
> > > 
> > > 
> > > 你好，可能我没有描述清楚。
> > > 我的情况是：用 ventoy安装 deepin20.2，点击 deepin选项之后，直接黑屏，然后左上角下划线在闪，风扇狂转。根本无法进入 grub中。
> > 
> > 
> > i5 11代是测试过的，grub里我记得有一个safe graphics的选项，尝试用一下这个？
> 
> 哥，你看明白我贴子里的描述了吗？
> 
> > 直接进入黑屏，还有一个小横杠闪烁，一直闪烁。。。
> 
> 根本没法选择其他选项。
> 你要是说测试过 11代i5。难道是我们这些用 11代i5的电脑都是废了吗？
> [intel 的 11代NUC 装不上](https://bbs.deepin.org/zh/post/220111)
> [新买HP星14触屏笔记本无法用20.2的启动U盘启动](https://bbs.deepin.org/zh/post/220041)
> [最新 小米笔记本 Pro 如何安装系统?](https://bbs.deepin.org/zh/post/219890)
> [黑屏左上角横岗光标](https://bbs.deepin.org/zh/post/219812)
> [OS not booting, show black screen](https://bbs.deepin.org/zh/post/219635)
> [rog幻15 2021无法安装](https://bbs.deepin.org/zh/post/219325)
> [宏基11代CPU安装deepin成功](https://bbs.deepin.org/217938)
> [deepin 20.2 无法安装](https://bbs.deepin.org/zh/post/217848)
> 这些电脑五花八门，但是全是无法安装的问题。
> 你来说说，你测试11代i5的机子是哪一台？怎们单单就我们这些i5的机子装不了deepin？

关闭安全启动了吗？

**Comment by jackyPang10086** [comment]
> > > > > 没有deepin论坛的账号，所以在这里回复你。看到你的描述，感觉是显卡驱动的问题。在grub按e键，linux的那一行加上nomodeset再试试
> > > > 
> > > > 
> > > > 你好，可能我没有描述清楚。
> > > > 我的情况是：用 ventoy安装 deepin20.2，点击 deepin选项之后，直接黑屏，然后左上角下划线在闪，风扇狂转。根本无法进入 grub中。
> > > 
> > > 
> > > i5 11代是测试过的，grub里我记得有一个safe graphics的选项，尝试用一下这个？
> > 
> > 
> > 哥，你看明白我贴子里的描述了吗？
> > > 直接进入黑屏，还有一个小横杠闪烁，一直闪烁。。。
> > 
> > 
> > 根本没法选择其他选项。
> > 你要是说测试过 11代i5。难道是我们这些用 11代i5的电脑都是废了吗？
> > [intel 的 11代NUC 装不上](https://bbs.deepin.org/zh/post/220111)
> > [新买HP星14触屏笔记本无法用20.2的启动U盘启动](https://bbs.deepin.org/zh/post/220041)
> > [最新 小米笔记本 Pro 如何安装系统?](https://bbs.deepin.org/zh/post/219890)
> > [黑屏左上角横岗光标](https://bbs.deepin.org/zh/post/219812)
> > [OS not booting, show black screen](https://bbs.deepin.org/zh/post/219635)
> > [rog幻15 2021无法安装](https://bbs.deepin.org/zh/post/219325)
> > [宏基11代CPU安装deepin成功](https://bbs.deepin.org/217938)
> > [deepin 20.2 无法安装](https://bbs.deepin.org/zh/post/217848)
> > 这些电脑五花八门，但是全是无法安装的问题。
> > 你来说说，你测试11代i5的机子是哪一台？怎们单单就我们这些i5的机子装不了deepin？
> 
> 关闭安全启动了吗？

关闭了

**Comment by zhboner** [comment]
可以试试直接把iso文件烧录u盘，不用ventoy引导。

**Comment by jackyPang10086** [comment]
> 可以试试直接把iso文件烧录u盘，不用ventoy引导。

哥，我的解决方案写在这了：https://bbs.deepin.org/zh/post/220443。 就是deepin没有适配新硬件的问题。

**Comment by yxsos** [comment]
即将发布的 20.2.2版本 将支持

**Comment by jackyPang10086** [comment]
好的，我在论坛发现 deepin对 新版本的AMD处理器也不支持。请问 deepin 20.2.2 支持吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linuxdeepin/developer-center"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月23日(星期三) 上午10:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [linuxdeepin/developer-center] [问题] deepin20.2 无法安装在 11代intel的电脑上。 (#2091)





 
即将发布的 20.2.2版本 将支持

**Comment by justforlxz** [comment]
> 好的，我在论坛发现 deepin对 新版本的AMD处理器也不支持。请问 deepin 20.2.2 支持吗？
> […](#)

现在 deepin 使用的是 5.15 的内核，支持一部分较新的 amd 平台。
