### ISSUE TITLE
Please don't hardcode paths for library and libexec

### ISSUE THREAD

**Issue by hillwoodroc** [linuxdeepin/developer-center#2092]
On some distributions which are using rpm, paths of libraries and libexec binaries are different from Debian base distributions. Such as Fedora, openSUSE and openEular. Many deepin apps hardcode path for library and libexec. This is not friendly to us. I suggest you use Macro instead.

**Comment by justforlxz** [comment]
I am processing in dtk, hoping to provide a consistent way.
