### ISSUE TITLE
Suggest : DTK  ScrollArea and Scrollbar Style  

### ISSUE THREAD

**Issue by jiangzc** [linuxdeepin/developer-center#2093]
目前发现DTK滚动条的样式有两个问题

1. 滚动条出现的时候会挡住控件右侧的某些内容
![image](https://user-images.githubusercontent.com/13901512/117575529-d53dee00-b114-11eb-8ce3-bab12fcdace3.png)

2. 设置 ScrollBarAlwaysOn，滚动条仍然需要鼠标悬停才会出现。用户看不见滚动条，不知道控件是否可以滚动
```
setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
```

**Comment by kegechen** [comment]
1. 动条悬浮在item上方不占用item的显示区域是设计如此(PM_ScrollView_ScrollBarOverlap return true)， 边缘不容易被点击的问题已经反馈到设计，后续看应该会优化。
2. 滚动条自动隐藏和显示也是风格插件里面做的，可以通过setproperty("_d_dtk_slider_always_show", true); 一直显示滚动条。ScrollBarPolicy的支持后续会考虑加上。

**Comment by justforlxz** [comment]
https://github.com/linuxdeepin/qt5integration/commit/7e5207bd82ffca384010976829c88194df08827e 修复了，停止滚动后隐藏
