### ISSUE TITLE
Deepin-Recovery is installed but entry not listed in Grub Advanced options !!!

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#2094]
Hi,

I installed deepin-recovery on V20.2 as i hadn't installed it before ... turns out the installation went through successfully but the Deepin-Recovery entry is not listed in the Grub kernel list ...

Is Deepin-Recovery supported on V20 ?
or it has been killed just like the so many other great features from Deepin 15 and earlier ?

thanks.

**Comment by justforlxz** [comment]
try `sudo grub-mkconfig -o /boot/grub/grub.cfg && ls /etc/grub.d` ？ and upload output.

**Comment by aiamuzz** [comment]
> try `sudo grub-mkconfig -o /boot/grub/grub.cfg && ls /etc/grub.d` ？ and upload output.

@justforlxz ... please find the sought output pasted below ...

`$ sudo apt-get install deepin-recovery
Password
[sudo] password for muz: 
Verification successful
Reading package lists... Done
Building dependency tree       
Reading state information... Done
deepin-recovery is already the newest version (94.79.cfe13c2).
0 upgraded, 0 newly installed, 0 to remove and 33 not upgraded.
Wed May 26 12:11 PM - muz@A***LLAH77: ~  
$ sudo grub-mkconfig -o /boot/grub/grub.cfg && ls /etc/grub.d
Generating grub configuration file ...
Found theme: /boot/grub/themes/deepin/theme.txt
Found background image: /boot/grub/themes/deepin/background.jpg
Found linux image: /boot/vmlinuz-5.11.1-amd64-desktop
Found initrd image: /boot/initrd.img-5.11.1-amd64-desktop
Found linux image: /boot/vmlinuz-5.10.18-amd64-desktop
Found initrd image: /boot/initrd.img-5.10.18-amd64-desktop
Found linux image: /boot/vmlinuz-5.10.5-amd64-desktop+
Found initrd image: /boot/initrd.img-5.10.5-amd64-desktop+
Found linux image: /boot/vmlinuz-5.4.50-amd64-desktop
Found initrd image: /boot/initrd.img-5.4.50-amd64-desktop
Found Windows Boot Manager on /dev/sda1@/efi/Microsoft/Boot/bootmgfw.efi
Found Deepin 15.11  (15.11) on /dev/sda5
Found Deepin 15.11  (15.11) on /dev/sda9
Adding boot menu entry for EFI firmware configuration
done
00_header        10_linux               20_linux_xen  30_uefi-firmware   40_custom  README
05_debian_theme  11_deepin_ab_recovery  30_os-prober  35_deepin_gfxmode  41_custom
Wed May 26 12:25 PM - muz@A***LLAH77: ~  
`

**Comment by justforlxz** [comment]
Check if live-filesystem is installed.

Now we start pre-installing the feature and it should work fine.
