### ISSUE TITLE
「缺陷报告」系统使用过程中突然黑屏卡死(Deepin 20.2)

### ISSUE THREAD

**Issue by wootifer** [linuxdeepin/developer-center#2097]
### 「问题描述」
在系统正常使用过程中，突然鼠标点击无反应，过几秒后，电脑黑屏死机，还有两三次是在使用浏览器看视频的时候，突然黑屏死机。在上述情况下，做任何操作均无反应，尝试使用另一台电脑使用ssh也无法登录，只能电源键强制关机。
### 「系统版本」
Deepin 20.2 
Linux deepin-PC 5.11.1-amd64-desktop #1 SMP Mon Mar 1 17:09:41 CST 2021 x86_64 GNU/Linux
<p>
### 「软硬件参数配置」
<p>
处理器 : AMD Ryzen 5 4600H with Radeon Graphics (六核 / 十二逻辑处理器)<p>
主板 : LNVNB161216<p>
内存 : 8GB(RMSA3320MJ78HAF-3200 DDR4 3200MHz (0.3ns))/8GB(RMSA3320MJ78HAF-3200  3200MHz (0.3ns))<p>
显示适配器 : NVIDIA Corporation<p>
音频适配器 : Family 17h (Models 10h-1fh) HD Audio Controller/NVIDIA Corporation<p>
存储设备 : SAMSUNG MZVLB512HBJQ-000L2 (512 GB)/WDC WDS100T2B0C-00PXH0 (1.00 TB)/WDC WD5000BMVW-11AJGS4 (500 GB)<p>
电池 : 电池<p>
网络适配器 : RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller/Wi-Fi 6 AX200<p>
鼠标 : USB OPTICAL MOUSE ([Maxxter] USB OPTICAL MOUSE)/MSFT0001:00 04F3:3140 Mouse (MSFT0001:00 04F3:3140 Mouse)/MSFT0001:00 04F3:3140 Touchpad (MSFT0001:00 04F3:3140 Touchpad)<p>
键盘 : ITE Tech. Inc. ITE Device(8910) Keyboard (Integrated Technology Express ITE Device(8910))/HOLDCHIP USB Gaming Keyboard (Holtek USB Gaming Keyboard)/AT Translated Set 2 keyboard (AT Translated Set 2 keyboard)<p>
打印机 : Lenovo-M101DW<p>
图像设备 : Integrated Camera (IMC Networks Integrated Camera)<p>
其他设备 : usb 0x0029<p>
</p>
-----------------------------------------------------------------------------+<p>
| NVIDIA-SMI 460.39       Driver Version: 460.39       CUDA Version: 11.2     |<p>
|-------------------------------+----------------------+----------------------+<p>
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |<p>
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |<p>
|                               |                      |               MIG M. |<p>
|===============================+======================+======================|<p>
|   0  GeForce GTX 1650    Off  | 00000000:01:00.0  On |                  N/A |<p>
| N/A   37C    P8     3W /  N/A |    277MiB /  3911MiB |      9%      Default |<p>
|                               |                      |                  N/A |<p>
+-------------------------------+----------------------+----------------------+<p>
<p>

**Comment by yxsos** [comment]
开始菜单里的日志管理器，抓取一下内核相关的日志

**Comment by hbhgwtf** [comment]
> 开始菜单里的日志管理器，抓取一下内核相关的日志

内核日志链接[https://github.com/hbhgwtf/test/blob/master/%E5%86%85%E6%A0%B8%E6%97%A5%E5%BF%97.txt](url)
抓取了最近一周的日志，着重看一下17号的，昨天更新了20.2.1，又出现了一次黑屏的情况，前些天(20.2版本)也出现了几次，具体时间忘了，如果这些信息不够，下次出现我就抓取上传一下。

**Comment by Zeno-sole** [comment]
日志里有网卡驱动的异常抛出，目前还不确定是不是网卡驱动造成的死机黑屏，等我们Lenovo机器采购到货后我们将持续跟进该问题

**Comment by hbhgwtf** [comment]
> 日志里有网卡驱动的异常抛出，目前还不确定是不是网卡驱动造成的死机黑屏，等我们Lenovo机器采购到货后我们将持续跟进该问题

好的。

**Comment by Zeno-sole** [comment]
5.15内核上还存在这个问题么

**Comment by wootifer** [comment]
> 5.15内核上还存在这个问题么

使用5.15内核后，目前没有出现这个问题，但是最近两个内测版本出现过正常使用时界面卡死的情况，不能进行任何操作，还有就是锁屏后卡死，只有鼠标能够移动，无法输入和进桌面，按ctr+Alt+F2-F12等也没用，这个似乎是电源管理的问题，将电源管理-》使用电源和使用电池-》电脑进入待机模式-》都设为从不，似乎能得到改善，目前没有出现卡死的情况。

**Comment by wootifer** [comment]
> 5.15内核上还存在这个问题么

刚回复完你的问题，机器又卡死了，麻烦看一下日志。
https://github.com/wootifer/test/blob/master/%E5%86%85%E6%A0%B8%E6%97%A5%E5%BF%97-220108.txt
https://github.com/wootifer/test/blob/master/%E7%B3%BB%E7%BB%9F%E6%97%A5%E5%BF%97220108.txt

**Comment by Zeno-sole** [comment]
日志里应该没有导致卡死的地方，是休眠待机等操作后就卡死了么

**Comment by wootifer** [comment]
> 日志里应该没有导致卡死的地方，是休眠待机等操作后就卡死了么

确实，我也看了一下日志文件，找到卡死的那个时间段，没有看到什么异常，难道是显卡驱动的问题吗？因为我安装的是NVIDIA官网的闭源驱动，我自己下载手动安装的，不知道是不是兼容性有点问题。如果是显卡驱动的问题，该如何排查呢？

**Comment by Zeno-sole** [comment]
卡死的日志应该是没有抓取到，可能需要用串口等方式看一下卡死瞬间的日志。

**Comment by Zeno-sole** [comment]
暂时先关闭这个issues,如果您有新的问题可以重新打开
