### ISSUE TITLE
Problems with laptop Elan Touchpad

### ISSUE THREAD

**Issue by donali98** [linuxdeepin/developer-center#2098]
After taping with two fingers, dock crashes and context menu of right click disappears, Bluetooth icon disappears too.

With an external mouse, behavior is completely normal.

I'm using a Lenovo Ideapad 320abr with Deepin 20.2 installed.

I'm wondering if there is a workaround to fix this.

Thanks for your help!

**Comment by justforlxz** [comment]
Is this problem still there?

**Comment by justforlxz** [comment]
Sorry for not getting a reply for a long time, I need to close this issue.
