### ISSUE TITLE
Issues with vmmon vmnet ... on V20.2 or V20 as a whole ... runs fine on the classic V 15.5 !

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#2099]
I am on V 20.2

I am trying to install and run VMware Workstation 15.x and i am finding issues with the above kernel modules ...

started with this error while trying to run a previously installed VM ...

![image](https://user-images.githubusercontent.com/3283676/118159241-67f2cb80-b43a-11eb-8caf-d43958ed2405.png)

I have tried running steps as per instructions found here ...
https://ubuntu-mate.community/t/20-04-vmware-workstation-player-fails-to-build-kernel-modules-vmmon-vmnet/21176

and here ...
https://askubuntu.com/questions/1096052/vmware-15-error-on-ubuntu-18-4-could-not-open-dev-vmmon-no-such-file-or-dire#:~:text=This%20problem%20essentially%20happens%20because,compiled%20modules%20vmmon%20and%20vmnet%20.

but i am ending up at the following error ...

```
$ sudo vmware-modconfig --console --install-all
[AppLoader] GLib does not have GSettings support.
Segmentation fault
```
VMware-Workstation 15.0.4 runs fine on my Deepin 15.5 ... however its not running on V20.2 ... havent tested on V20.1 so i wouldn't know if its V20 problem or V20.2 specific problem ...

thanks in advance.

**Comment by aiamuzz** [comment]
UPgraded to V20.2.1 today ... issue still persists ...

@justforlxz, @BLumia, @hualet ... Can you at least confirm if this is an OS/Kernel issue or not, so i can take this up at the right forum ?

why is it that V15 runs the Vmware just fine but not V20.x.x ???

**Comment by BLumia** [comment]
I don't have deepin v20.x iso images in hand, and I also don't have a legal copy of VMware-Workstation (I use VirtualBox), so I couldn't offer more help about your issue. Sorry about that. Hope people from deepin team could offer more help :)

**Comment by aiamuzz** [comment]
> Sorry about that. Hope people from deepin team could offer more help :)

@blumia ... Oh ... you are no longer on the team ?

Hope someone from the team replies soon ...

**Comment by aiamuzz** [comment]
> I don't have deepin v20.x iso images in hand, and I also don't have a legal copy of VMware-Workstation (I use VirtualBox), so I couldn't offer more help about your issue. Sorry about that. Hope people from deepin team could offer more help :)

@BLumia ... even Virtual Box isn't running facing the following error ... 

`root@A*****LLAH77:/home/muz# /sbin/vboxconfig`

```
vboxdrv.sh: Stopping VirtualBox services.
vboxdrv.sh: Starting VirtualBox services.
vboxdrv.sh: Building VirtualBox kernel modules.
vboxdrv.sh: failed: Look at /var/log/vbox-setup.log to find out what went wrong.

There were problems setting up VirtualBox.  To re-start the set-up process, run
  /sbin/vboxconfig
as root.  If your system is using EFI Secure Boot you may need to sign the
kernel modules (vboxdrv, vboxnetflt, vboxnetadp, vboxpci) before you can load
them. Please see your Linux system's documentation for more information.

```

**Comment by BLumia** [comment]
> you are no longer on the team ?

Yep. Things may change a lot after I leave so you may ask them for help since I'm not really sure what their Open Source workflow is and how things working now.

> ```
> vboxdrv.sh: failed: Look at /var/log/vbox-setup.log to find out what went wrong.
> ```

You may need to do that.

**Comment by BLumia** [comment]
> ... Deepin has lost its shine since V20 ... 

Although DDE is not my cup of tea, there are actually people who prefer the v20 version of DDE more than v15. Let's just hope they can do better :)

> ```
> /tmp/vbox.0/r0drv/linux/memobj-r0drv-linux.c: In function ‘rtR0MemObjLinuxVMap’:
> /tmp/vbox.0/r0drv/linux/memobj-r0drv-linux.c:560:34: error: implicit declaration of function ‘alloc_vm_area’; did you mean ‘find_vm_area’? [-Werror=implicit-function-declaration]
>                  pMemLnx->pArea = alloc_vm_area(pMemLnx->Core.cb, papPtes); /* Note! pArea->nr_pages is not set. */
>                                   ^~~~~~~~~~~~~
>                                   find_vm_area
> ```

*Seems like* the VirtualBox version you got not yet support the kernel version you're using. Check if there is a newer VirtualBox release than what you're using and try the new version if there is, or consider downgrade the kernel *may* works.

**Comment by aiamuzz** [comment]
> Although DDE is not my cup of tea, there are actually people who prefer the v20 version of DDE more than v15. Let's just hope they can do better :)

@BLumia ...
... hahahaha ... You sure ??? ... you don't have to tow the official line you know ... remember you are no longer in the team ... I guess it must be your reflex to jut-out the official statement(after all your contribution to the Deepin project must be unshakeable even though you are no longer in it) ... :smile: :smile: :smile: 

But really V20 over V15 ???

Lets see ... V15 Vs V20 ...

1. **No Hot corners** - very functional and visually appealing (the whole UI and the accompanied animation and effects of the Corner Settings - **and now cut to V20 - DROPPED !!!**

2. **The Control Settings Panel on the Right** - it was one part of UI that was unlike no other(conky like transparent panel) ... the irony is Deepin went about sticking their noses into every other distro offering them the Dreamy Visual Experience in the form of ported DDE's ... basically asking them to see how good our control panel is in comparison to your bland window based System Settings application ... **and now cut to V20 ... They have taken the route of the bland window based system themselves**

3. **A fantastic feature of Volume Control Applet** in the system tray with the ability to control volume at individual application level, hell it was so cool that it gave an option to control volume of more than one media playing in chrome's multiple tabs/windows ... **and now cut to V20 - DROPPED !!!**

4. **The dreamy Dock** which would resize according to the number of icons(docked and open application icons) ... now a bland long dock but actually a panel similar to the windows/mac panel but with a gap below and on either sides ... **and now cut to V20 - DROPPED !!!**

5. **The squarish corners of the Application Windows(thankfully they gave back control of the rounded corners of the application windows in the settings) and the various elements(like selection and other UI elements),** which were so simple(like the Windows Metro UI tiles) amazingly simple hence Elegant - **and now cut to V20 - ugly rounded corners element replacing the elegant squarish one's - Yuck !!!**

6. Hell they've even dropped the "Deepin Application Group" in the Deepin Store ... which had all the Deepin apps grouped conveniently together ... I tried entering Deepin in the search field hopping to find all the Deepin Apps listed ... Bloody hell they've even dropped the Word Deepin from the application name (Deepin Movie, Deepin Editor, ... etc) ... They could have atleast kept the Deepin apps searchable through the keyword 'Deepin' ... at least we didn't have to stare and look for a needle(deepin apps) in the hay stack(in the middle of so many apps) !!!
;
;
;
Just imagine all the above with the power of Debian Stable with the dual kernel(LTS) option ... **Deepin would have been a formidable Linux distro !!!** ... also given that its been bought over by UnionTech(which translates to fund infusion) ... **All deepin needed was good and simple marketing with the classic and elegant UI of V15 and the power packed features of V20 ... What did they do instead ... they tried fixing something that was not broken and in the process broke a Eye Candy OS into a run-of-the-mill new breed of linux distros that have been spawning everywhere ... Duh !!!**

... @BLumia ... need i go on ??? ... on the fall from Grace/Fame of Deepin from V15 to V20 ???
@BLumia ... If you have a NDA signed saying i wouldn't go against the official line ... :wink: :stuck_out_tongue_winking_eye: ... That i can Understand ... But nobody dare tell us old farts of V15 that V20 is better received ... that may be bcos of fresh marketing efforts of Uniontech and the fact that other Distros and their UI / UX lack so much that even this ugly V20 will seem god send to new users ... But when pitted agains the Classic V15 ... V20 is as ugly as an Ogre ... remember Shrek the Ogre ? ... even he is round and round just like the rounded UI of V20 !!!



> _Seems like_ the VirtualBox version you got not yet support the kernel version you're using. Check if there is a newer VirtualBox release than what you're using and try the new version if there is, or consider downgrade the kernel _may_ works.

@BLumia ... **thanks ... that is what i did with VMware ... i jumped to version 16 and it worked just fine out of the box** ... VirtualBox however is another story all together as that was the version available in the Deepin Store ... and its not working ... so a newer version is only possible if one installed directly from the Oracle's websites ...

PS : @BLumia ... drop in a test message on my telegram ID : aiamuzz ... We old farts can reminisce good'ol times from both sides of the fence ... me as a user and you a dev !!!  :stuck_out_tongue_winking_eye: 

PS2 : Deepin Admin ... don't freak out for using a off topic thread to reminisce and vent out my ire towards V20 ... **I know nobody cares about sincere user feedback at Deepin anymore !!!**

Adios !!!

**Comment by Zeno-sole** [comment]
The VirtualBox 6.1.18 version in the warehouse can run normally on 20.2, you can try

**Comment by Zeno-sole** [comment]
Please use VMware Workstation Player 16 version to do a little bit, 20.2 uses 5.10 kernel, 15 version has no features

**Comment by aiamuzz** [comment]
> The VirtualBox 6.1.18 version in the warehouse can run normally on 20.2, you can try

@Zeno-sole ... oh ok ... when i installed from the store this **Version 6.1.16 r140961 (Qt5.15.1)** what was installed ...



> Please use VMware Workstation Player 16 version to do a little bit, 20.2 uses 5.10 kernel, 15 version has no features

Thanks ... You are right **Version 16** ... is what got me out of the pickle ...

**Comment by aiamuzz** [comment]
> The VirtualBox 6.1.18 version in the warehouse can run normally on 20.2, you can try

Sorry still not working after the upgrade ... 

![image](https://user-images.githubusercontent.com/3283676/120681123-ae2ad000-c4b8-11eb-81e6-7473edfac335.png)

```
$ sudo /sbin/vboxconfig 
vboxdrv.sh: Stopping VirtualBox services.
vboxdrv.sh: Starting VirtualBox services.
vboxdrv.sh: Building VirtualBox kernel modules.
vboxdrv.sh: failed: Look at /var/log/vbox-setup.log to find out what went wrong.

There were problems setting up VirtualBox.  To re-start the set-up process, run
  /sbin/vboxconfig
as root.  If your system is using EFI Secure Boot you may need to sign the
kernel modules (vboxdrv, vboxnetflt, vboxnetadp, vboxpci) before you can load
them. Please see your Linux system's documentation for more information.
```

I don't think this is EFI Secure Boot bcos ... VMWare is working just fine ...

**Comment by Zeno-sole** [comment]
20.2 The system does not currently support Secure Boot

**Comment by justforlxz** [comment]
The test report of deepin 20.2.2 shows that the problem has been dealt with.
