### ISSUE TITLE
Disabling Deepin Dock

### ISSUE THREAD

**Issue by BobbyBabes** [linuxdeepin/developer-center#210]
How do I **properly** disable Deepin Dock ?

Right now I'm renaming `dde-dock` : 
```Bash
sudo mv /usr/bin/dde-dock /usr/bin/DISABLED-dde-dock
```

Which results in this mess during every boot  (chopped off because of repetitiveness) : 
```
journalctl -b | grep -ie dock

Mar 25 16:43:49 designbox daemon/loader[785]: loader.go:150: enable module dock
Mar 25 16:43:49 designbox daemon/dock[785]: cache_manager.go:60: load file ok
Mar 25 16:43:49 designbox daemon/dock[785]: cache_manager.go:60: load file ok
Mar 25 16:43:49 designbox daemon/dock[785]: dock_manager_entries.go:61: Get client list failed: GetProperty: No such property '_NET_CLIENT_LIST' on window 4b3.
Mar 25 16:43:49 designbox daemon/dock[785]: dock_manager_xevent.go:80: GetProperty: No such property '_NET_ACTIVE_WINDOW' on window 4b3.
Mar 25 16:43:49 designbox daemon/dock[785]: dock_manager_xevent.go:57: Get client list failed: GetProperty: No such property '_NET_CLIENT_LIST' on window 4b3.
Mar 25 16:43:49 designbox daemon/loader[785]: loader.go:158: enable module dock done, cost 24.123937ms
Mar 25 16:43:49 designbox startdde[722]: session_procese.go:52: Start command '/usr/bin/dde-dock' failed: fork/exec /usr/bin/dde-dock: no such file or directory
Mar 25 16:43:59 designbox dbus-daemon[728]: Activating service name='com.deepin.dde.Dock'
Mar 25 16:43:59 designbox dbus-daemon[728]: Activated service 'com.deepin.dde.Dock' failed: Failed to execute program com.deepin.dde.Dock: No such file or directory
Mar 25 16:43:59 designbox daemon/watchdog[722]: manager.go:76: Launch 'dde-dock' failed: org.freedesktop.DBus.Error.Spawn.ExecFailed:Failed to execute program com.deepin.dde.Dock: No such file or directory
Mar 25 16:44:09 designbox dbus-daemon[728]: Activating service name='com.deepin.dde.Dock'
Mar 25 16:44:09 designbox dbus-daemon[728]: Activated service 'com.deepin.dde.Dock' failed: Failed to execute program com.deepin.dde.Dock: No such file or directory
Mar 25 16:44:09 designbox daemon/watchdog[722]: manager.go:76: Launch 'dde-dock' failed: org.freedesktop.DBus.Error.Spawn.ExecFailed:Failed to execute program com.deepin.dde.Dock: No such file or directory
Mar 25 16:44:19 designbox dbus-daemon[728]: Activating service name='com.deepin.dde.Dock'
Mar 25 16:44:19 designbox dbus-daemon[728]: Activated service 'com.deepin.dde.Dock' failed: Failed to execute program com.deepin.dde.Dock: No such file or directory
Mar 25 16:44:19 designbox daemon/watchdog[722]: manager.go:76: Launch 'dde-dock' failed: org.freedesktop.DBus.Error.Spawn.ExecFailed:Failed to execute program com.deepin.dde.Dock: No such file or directory
Mar 25 16:44:29 designbox dbus-daemon[728]: Activating service name='com.deepin.dde.Dock'
```

**Comment by felixonmars** [comment]
I don't think it's a supported setup to disable the dock atm.

**Comment by BobbyBabes** [comment]
Well, that explains why I couldn't find a way.

I tried with `systemctl stop com.deepin.dde.Dock` which pops an authentication window. But after selecting a user from the dropdown and entering the password I'm dropped back in Deepin Terminal with this message
> Failed to stop com.deepin.dde.Dock.service: Connection timed out
See system logs and 'systemctl status com.deepin.dde.Dock.service' for details.

Executing `systemctl status com.deepin.dde.Dock.service` displays the message
> Unit com.deepin.dde.Dock.service could not be found


Double checking by listing the units with `systemctl list-unit-files` and `systemctl list-units` confirmed that the service doesn't exist. I filtered with ` | grep -ie dock`.

**Comment by felixonmars** [comment]
That won't work, cuz your dock was activated by dde-daemon via dbus.

**Comment by BobbyBabes** [comment]
Yeah, I was just listing my failed attempts.
Didn't know why they failed though. So thanks for explaining.

**Comment by hualet** [comment]
It should be able to disable the session-watcher by 
> gsettings set com.deepin.dde.daemon sessionwatcher false
But it seems to be somehow broken. @jouyouyun

**Comment by jouyouyun** [comment]
@BobbyBabes  Exec `gsettings set com.deepin.dde.watchdog dde-dock false` will disable dde-dock.

**Comment by funilrys** [comment]
@jouyouyun solution tested :+1:

**Comment by BobbyBabes** [comment]
It doesn't work for me. Deepin Dock is still there after a reboot.
It will also first display as one big black block/square at the top left of the screen, before looking like a dock with icons.

**Comment by hualet** [comment]
As you can see it does just what watchdogs should do.

**Comment by BobbyBabes** [comment]
I don't know what you mean.

I opened this issue because I do not want a dock. So I do not want Deepin Dock to start up.
This does not disable Deepin Dock. :
> Exec gsettings set com.deepin.dde.watchdog dde-dock false will disable dde-dock.
It is still started with every login.

**Comment by oberon2007** [comment]
dde-dock is an integral part of the deepin desktop. you cannot disable or replace it afaik @BobbyBabes

**Comment by funilrys** [comment]
Strange cause after `gsettings set com.deepin.dde.watchdog dde-dock false` it's desapear by me on fresh install but when I log on it's back :sweat_smile: :smile_cat:

**Comment by BobbyBabes** [comment]
@oberon2007 @funilrys In the back of my mind I had actually already settled with that it was not possible. And therefore to stick with the renaming workaround.
Though when I saw it, I hoped that the `false` setting would have done the trick. Too bad. It's OK for now.

**Comment by jouyouyun** [comment]
watchdog  only  not start dock when dock crashed. 
If not want dock startup, remove the execucate file `/usr/bin/dde-dock`
