### ISSUE TITLE
How To Enable My Second Monitor With Intel Graphics ..?(Deepin Linux)

### ISSUE THREAD

**Issue by GathsaraH** [linuxdeepin/developer-center#2101]
## Issue: How To Enable My Second Monitor With Intel Graphics

I Have MSI GL63 Gaming Laptop And It's Comes With Intel graphics and GeForce® GTX 1050 Ti with 4GB GDDR5.

My Second Monitor works with Nvidia GPU Only .. when I switched to Intel graphics my second monitor is not working. How can I fix this issue ..? How to enable my second Monitor with Intel graphics ..?

Because of this, My Laptop Heat Increasing every minute.

Please Help Me ..!

Thank You very much ..!

**Comment by justforlxz** [comment]
You need to write your own Xorg configuration file to configure. Like this https://wiki.archlinux.org/title/NVIDIA#Multiple_monitors

But I cannot guarantee that it is working properly.
