### ISSUE TITLE
[Feature Request] Add a toggle to switch theming per app 

### ISSUE THREAD

**Issue by vesterlay** [linuxdeepin/developer-center#2104]
I'd like to stay on full dark theme, however there are some apps that look atrocious on Dark theme. 

Example:
![image](https://user-images.githubusercontent.com/39202451/119192806-fab9e880-ba80-11eb-8e4a-5bc0c64e9e4e.png)

**Comment by justforlxz** [comment]
Sorry, the gtk program cannot add a switch menu.

**Comment by vesterlay** [comment]
Rip
