### ISSUE TITLE
「缺陷报告」deepin论坛又抽风了

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2105]
我想发帖，一直报这个：“系统检测到您当前操作环境异常，可能有违规行为，请稍后再试”
无法发帖，我的论坛账号是：widon1104

**Comment by yxsos** [comment]
已经恢复，如果还出现此异常问题，请清理一下cookies试一下.

**Comment by widon1104** [comment]
刚才试了一下，还没有恢复！清除了cookie也不行，不得不说这个论坛做的实在是太差了

**Comment by widon1104** [comment]
![截图_选择区域_20210524144637](https://user-images.githubusercontent.com/12093211/119307938-fb2fca80-bc9e-11eb-9b8d-2ee01d7d3815.png)
服了这个论坛了，3天一小抽，5天一大抽，把用户的热情都消磨的差不多了
