### ISSUE TITLE
Bug report 「缺陷报告」

### ISSUE THREAD

**Issue by jackyPang10086** [linuxdeepin/developer-center#2107]
## Issue: Bug or suggest report 「问题反馈」 

当前 深度社区存在许多bug，希望社区开发人员能够及时修复。
bug我写在这篇帖子里了：[不！吐！不！快！社区使用十一大痛点](https://bbs.deepin.org/zh/post/220649)

**Comment by justforlxz** [comment]
请不要这样报告bug，谢谢。
