### ISSUE TITLE
[Arch Linux] Why only 7 workspace ?

### ISSUE THREAD

**Issue by funilrys** [linuxdeepin/developer-center#211]
Is it possible to have more workspaces? 
I really need more :smile_cat: 
In other DE we can go from 1 to 99 or 1 to infinite, why deepin only allow us 7 workspaces?

**Comment by sonald** [comment]
@funilrys will you actually open more than 7 workspaces constantly ? deepin-wm has optimized  ui and interaction design with less than 8 workspaces.

**Comment by funilrys** [comment]
When I'm at work I actually use inefficiently all 7 workspaces @sonald that's why I need more ...

**Comment by sonald** [comment]
The logic is bulit into the core of deepin-wm which keeps the fact that no more than 7 workspaces exists in mind. so it's not easy to add more right now.

**Comment by hualet** [comment]
Sorry, @funilrys 
I don't think this is necessary and it's won't be fixed/implemented.

**Comment by funilrys** [comment]
No problem @hualet :) I changed the variable and build my own version on my work computer !

Working perfectly !
