### ISSUE TITLE
Suggestion - Emoji Panel

### ISSUE THREAD

**Issue by dreaddr** [linuxdeepin/developer-center#2111]
Suggestion to include an emoji panel like this https://github.com/GaZaTu/x11-emoji-picker in order to use emojis with the system. Super key + Dot Key (.) preferred as default binding to bring this up.

Thanks, not sure if this the right place to ask for this but I found lots of uncommon issues here so I'm leaving it here.

**Comment by meiyixiang** [comment]
19/5000 
What do you need us to do? Can you describe it in more detail?

**Comment by dreaddr** [comment]
@meiyixiang 

Make a default emoji panel  (or just add a pre-existing one, like mentioned above) on Deepin, just like on Windows or macOS. (Windows one shown here for your reference https://imgur.com/a/BunH87o)

**Comment by meiyixiang** [comment]
Later V23 releases will add emojis to the system, but you may not need to do this alone
