### ISSUE TITLE
Arch版打包问题

### ISSUE THREAD

**Issue by asd-a** [linuxdeepin/developer-center#2114]
deepin组里还用的是旧版deepin-wm，现deepin-kwin在虚拟机环境已无影响使用的bug

**Comment by asd-a** [comment]
仍然会有窗口特效莫名失效的bug

**Comment by felixonmars** [comment]
主要考虑是现在每次 kwin 升级时基本都会坏，然后修复速度无法保障（一般很慢），所以仍然保留 deepin-wm 作为默认。
