### ISSUE TITLE
unable to add outlook IMAP outgoing server in mail

### ISSUE THREAD

**Issue by insanitie** [linuxdeepin/developer-center#2115]
deepin mail will not let me add "-" into outgoing smtp server settings in configuration.
i can set incoming to imap-mail.outlook.com no problem. 
smtp-mail.outlook.com on the other hand, wont be accepted. even copy/paste doesnt work.
you can type smtp.mail.outlook.com but for some reason it will not accept the minus´-´
I have googled and searched for fixes etc, but couldnt find this bug reported anywhere.
![Screenshot_select-area_20210610082542](https://user-images.githubusercontent.com/55153289/121482896-7bf00580-c9c5-11eb-864e-495e4488f2ad.png)

**Comment by Vistaus** [comment]
Can't reproduce this: it works fine for me.

**Comment by justforlxz** [comment]
has been fixed.
