### ISSUE TITLE
community-store-packages.deepin.com is dead 

### ISSUE THREAD

**Issue by vesterlay** [linuxdeepin/developer-center#2116]
![image](https://user-images.githubusercontent.com/39202451/121959419-0ee1c480-cd65-11eb-80c9-cca6709e7436.png)

The https://community-store-packages.deepin.com/appstore/ website is dead 

Can't update nor install any software from the appstore

**Comment by felixonmars** [comment]
It should be fixed now. Please try again.

**Comment by vesterlay** [comment]
Appstore seems to be working
