### ISSUE TITLE
Network Manager does not connect to strongest BSSID

### ISSUE THREAD

**Issue by atar-axis** [linuxdeepin/developer-center#2117]
In my network I am having more than one AP using the same SSID, in fact the network is simply repeated.
Therefore I am having several AP's with the same SSID (name), but different BSSID's. One is stronger than the other, depending on your location.

The problem is:
In Deepin 20 only one of those AP's is showing up. If I connect to it by clicking on it, it does **NOT** connect to the AP with the strongest signal. It is connecting to the "unrepeated" signal - simply the first one.

Possible solutions:
* If there is more than one AP with the same SSID, show all of them in the network manager.
* Even better: connect to the AP with the strongest signal

**Comment by justforlxz** [comment]
NetworkManager supports automatic connection to the best AP, can you upload the contents of the file in `/etc/NetworkManager/system-connections/`?

**Comment by ClayStan** [comment]
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue.
