### ISSUE TITLE
I need some help to establish linuxdeepin on Slackware 15

### ISSUE THREAD

**Issue by slackernetuk** [linuxdeepin/developer-center#2120]
I would like to establish linuxdeepin on Slackware, but I'm not sure where to ask.

I guess the linuxdeepin base packages need to be built in a specific order?

Unfortunately, I couldn't find any information about!

**Comment by vesterlay** [comment]
Take a look at https://github.com/linuxdeepin/package-tag/blob/master/packages-tag-version/packages-tag-20.2-version.md.  I'm not sure if it's worth the time tho. DDE is pretty unstable outside deepin

**Comment by justforlxz** [comment]
Unfortunately, we don't have a clear build tree, you can refer to this list, probably you need to build it from the Internet. 

  - deepin-pw-check
  - dde-qt-dbus-factory
  - dtkcommon
  - dtkcore
  - dtkgui
  - deepin-desktop-base
  - dtkwidget
  - deepin-gettext-tools
  - go-gir
  - go-lib
  - go-dbus-factory
  - go-x11-client
  - dde-api
  - startdde
  - dde-daemon
  - dde-network-utils

**Comment by justforlxz** [comment]
I think this reply has been satisfied, I will close this issue first, if ban is still needed

**Comment by slackernetuk** [comment]
absolutely....thank you very much
