### ISSUE TITLE
[suggest report ]Where is the source code of UOS?

### ISSUE THREAD

**Issue by MasterOfStar** [linuxdeepin/developer-center#2121]
Where is the source code for UOS? I can't find it.
GNU/Linux uses the GPLv2 license and you need to make the source code available to everyone as easily as they can download the iso image.
Or is it all the same kernel as deepin? Without any modifications? If so it should also be stated on the download page, and provide the source code.

**Comment by lxwndr** [comment]
Some parts of UOS are closed source. Only deepin is 100% open source.

**Comment by MasterOfStar** [comment]
> Some parts of UOS are closed source. Only deepin is 100% open source.

BUT where is kernel？It's kernel is 100% as same as deepin?
If not, it is not a GNU project and has no right to use the LINUX kernel.

**Comment by MasterOfStar** [comment]
> > Some parts of UOS are closed source. Only deepin is 100% open source.
> 
> BUT where is kernel？It's kernel is 100% as same as deepin?
> If not, it is not a GNU project and has no right to use the LINUX kernel. Or rather, it is legally infringing.

I know it's a partially closed source commercial project, but at least the Linux kernel should be open source

**Comment by lxwndr** [comment]
The entire base of UOS/deepin is based on debian 10 (Buster). In the case of deepin, the latest kernel versions are manually compiled by the development team; that is, _there is nothing around here that is closed source_ (proprietary).

Regarding UOS, closed code refers to virtual assistant; which belongs to the Chinese company iFlytek. I'm not sure if the same fact is related to the Contacts app - which is unavailable to foreign users (outside of China).

It's important to mention, that the Security Center will bring a third-party antivirus engine; probably from Qihoo360 or Baidu - making it impossible to open code certain parts of the system.

Don't worry about UOS, at this time it's only targeted at the domestic market in China. If you live outside China and want a free system, use **deepin**!

**Comment by MasterOfStar** [comment]
> The entire base of UOS/deepin is based on debian 10 (Buster). In the case of deepin, the latest kernel versions are manually compiled by the development team; that is, _there is nothing around here that is closed source_ (proprietary).
> 
> Regarding UOS, closed code refers to virtual assistant; which belongs to the Chinese company iFlytek. I'm not sure if the same fact is related to the Contacts app - which is unavailable to foreign users (outside of China).
> 
> It's important to mention, that the Security Center will bring a third-party antivirus engine; probably from Qihoo360 or Baidu - making it impossible to open code certain parts of the system.
> 
> Don't worry about UOS, at this time it's only targeted at the domestic market in China. If you live outside China and want a free system, use **deepin**!

>there is nothing around here that is closed source (proprietary).

It's not a matter of worrying, it's a matter of the GPL License that should be followed.
System using linux kernel must be open source, **Deepin** did it, but **UOS** did not.

As far as I know, the kernel of uos has been modified relative to deepin, so it should be open source separately. 
Deepin-wine also uses the GPLv2 License open source code of wine, which should also be open source.

This is a legal issue, and if UOS is not open source, I should probably notify the Free Software Foundation to sue.

**Comment by Rabenda** [comment]
搞的像真的一样 获取源码方式参见
Linux源码是GPL2开源协议的，那自称国产操作系统的统信OS不打算遵循GPL2开放源代码？ - 曾浩的回答 - 知乎
https://www.zhihu.com/question/461113450/answer/1904611799

**Comment by Rabenda** [comment]
https://uos.deepin.cn/uos/pool/main/l/linux/linux_4.19.67.orig.tar.xz

**Comment by MasterOfStar** [comment]
> 搞的像真的一样 获取源码方式参见
> Linux源码是GPL2开源协议的，那自称国产操作系统的统信OS不打算遵循GPL2开放源代码？ - 曾浩的回答 - 知乎
> https://www.zhihu.com/question/461113450/answer/1904611799

依照GPLv2 License，UOS需要在自己的下载页面标注源代码的下载方式。
因为第三条有要求
>3. You may copy and distribute the Program (or a work based on it, under Section 2) in object code or executable form under the terms of Sections 1 and 2 above provided that you also do one of the following:
\
a) Accompany it with the complete corresponding machine-readable source code, which must be distributed under the terms of Sections 1 and 2 above on a medium customarily used for software interchange; or,
b) Accompany it with a written offer, valid for at least three years, to give any third party, for a charge no more than your cost of physically performing source distribution, a complete machine-readable copy of the corresponding source code, to be distributed under the terms of Sections 1 and 2 above on a medium customarily used for software interchange; or,
c) Accompany it with the information you received as to the offer to distribute corresponding source code. (This alternative is allowed only for noncommercial distribution and only if you received the program in object code or executable form with such an offer, in accord with Subsection b above.)
The source code for a work means the preferred form of the work for making modifications to it. For an executable work, complete source code means all the source code for all modules it contains, plus any associated interface definition files, plus the scripts used to control compilation and installation of the executable. However, as a special exception, the source code distributed need not include anything that is normally distributed (in either source or binary form) with the major components (compiler, kernel, and so on) of the operating system on which the executable runs, unless that component itself accompanies the executable.
\
If distribution of executable or object code is made by offering access to copy from a designated place, then offering equivalent access to copy the source code from the same place counts as distribution of the source code, even though third parties are not compelled to copy the source along with the object code.


即应该为任何能获取到副本（即UOS安装镜像）的人以同样（简单）的形式提供源代码。

**Comment by Rabenda** [comment]
依我之见 打在UOS软件源里已经在debian系发行版里比简获取源码的方式了

**Comment by MasterOfStar** [comment]
> 依我之见 打在UOS软件源里已经在debian系发行版里比简获取源码的方式了

但不合规就是不合规，比烂没有意义。
另:基于Debian的Kali直接把源代码链接放在了下载页面，这才是合适的做法。基于Ubuntu的Mint则是在网站底部标注了可以使用`apt-get source`来获取。

所以至少应该对如何获取源代码进行标注才符合要求。哪怕写在文档中心里面也不会有人说啥。

**Comment by justforlxz** [comment]
Hi, emm, this question is really tricky. 

We are promoting all projects to comply with the regulations and open source, but it takes time to review the code.

**Comment by justforlxz** [comment]
But what I need to explain is that this is the open source warehouse of the deepin release, not UOS or Uniontech. It is unreasonable to discuss UOS-related matters here.

**Comment by justforlxz** [comment]
I think there is no need to discuss the UOS code issue here, I need to close the issue.
