### ISSUE TITLE
Bug report - Change keyboard layout doesn't work

### ISSUE THREAD

**Issue by ahmadidev** [linuxdeepin/developer-center#2122]
## Issue: Bug
After upgrading to Deepin 20.2.1 (`sudo apt dist-upgrade`), the keyboard shortcut nor the keyboard notification panel icon doesn't works to change the language.
I think this a critical UX issue because a huge number of users are multilanguage.
Any help is appreciated :)

**Comment by justforlxz** [comment]
We already know this issue and it is still being revised.

**Comment by SalahAdDin** [comment]
@justforlxz I checked it today and it does not work anymore, we even can't see the system language in the dock, why?

**Comment by ClayStan** [comment]
has been fixed,closed
