### ISSUE TITLE
New App Store [Deepin 20.2.2] language set to Chinese and Mobile Applications (android) are empty

### ISSUE THREAD

**Issue by tanvir-kx** [linuxdeepin/developer-center#2124]
New App Store [Deepin 20.2.2] language set to Chinese though my system language is English(US). Also Mobile Applications (android) section is empty or not working. See the screenshot for details. Login with Deepin ID didn't helped either.

![image](https://user-images.githubusercontent.com/68131844/123984011-1ef4d780-d9e6-11eb-9607-50b95b55b297.png)
![image](https://user-images.githubusercontent.com/68131844/123984113-30d67a80-d9e6-11eb-8216-0380076b83b5.png)
![image](https://user-images.githubusercontent.com/68131844/123984416-6da27180-d9e6-11eb-95bf-fa236dbedd4b.png)

**Comment by Vistaus** [comment]
Latest update in the proposed repo changed the language to English.

**Comment by Vistaus** [comment]
And upstream, translations to other languages have also landed now.

**Comment by tanvir-kx** [comment]
Android App menu is just gone now!!!
![image](https://user-images.githubusercontent.com/68131844/128001173-b8013724-7219-4458-b3c9-8189f1a64ebf.png)

**Comment by Vistaus** [comment]
@tanvir-kx Temporarily, yes.

**Comment by tanvir-git** [comment]
any update on android app support in deepin store?

**Comment by ClayStan** [comment]
It should have been fixed. If still have this  problem, please reopen it
