### ISSUE TITLE
Lost the Dock, Quake terminal, Non-functional Shortcuts, not sure what else after today's update !

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#2126]
Luckily the workspace view was accessible through the system shortcuts else i would have pretty much a mute operating system    unable to tell if it was hanging or functional.

Please find screenshots of the running processes ... yet there is no Dock, so many shortcuts aren't working, unable to access app launcher so can't access applications ... quite a few system shortcuts arent working as intended ... 100% of my custom shortcuts aren't working ... 

Luckily i have configured Chrome to run n startup ... so i could access the browser to report this issue

Luckily my desktops had some folders ... that enabled me to access File Manager through the file manager i could launch the Terminal ... and through the terminal i was apple to launch the System Monitor to capture the following screenshots ...

As you can see below Dock & kwin processes seem to be running alright ...

![Screenshot_select-area_20210702135750](https://user-images.githubusercontent.com/3283676/124245728-e10ac700-db3d-11eb-9883-d547b58c4511.png)

![Screenshot_select-area_20210702135720](https://user-images.githubusercontent.com/3283676/124245720-dfd99a00-db3d-11eb-8bec-92a07a058cd1.png)

**Comment by aiamuzz** [comment]
some more anomalies ... memory leakage of the `dde-dock` ???
as you can its bloated to more than 5GB ...

![Screenshot_select-area_20210702234105](https://user-images.githubusercontent.com/3283676/124314306-cf520f80-db8f-11eb-9b8a-69171229274f.png)

**Comment by aiamuzz** [comment]
Closing this as this was some problem with the `dpkg` configuration ... probably an incomplete/broken update !!!

running `sudo dpkg --configure -a` fixed this issue ....

**Comment by 0yanghongwei** [comment]
@aiamuzz Hello, could you please provide me with your dock version number?
