### ISSUE TITLE
「缺陷报告」英伟达显卡电脑安装系统时候选择闭源驱动可能有问题

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2127]
有些电脑是英伟达驱动，但是显卡比较老最新的闭源驱动已经不支持这款显卡，如果这种电脑安装系统的时候选择闭源驱动会发生什么问题？我估计只有重装了

1）我觉得安装时候选择闭源驱动这个选项可以保留，但是镜像里面应该有好几款闭源驱动，分别是最新的驱动和支持老显卡的驱
动，安装的时候自动**智能匹配**安装新驱动还是老驱动，这样才能够规避很多问题，提升用户使用deepin的体验。

2）显卡驱动管理器同时需要加强，不仅要支持安装最新的闭源驱动，也要支持安装老的闭源驱动，最好加入**智能提示**，提示用户安装哪一个合适。

**Comment by widon1104** [comment]
https://bbs.chinauos.com/zh/post/10145?offset=0&postId=45960
这个帖子就是一个使用英伟达老显卡用户使用显卡驱动管理器切换失败的例子，如果这个用户没有较强的动手能力，我看他是无法把闭源驱动装起的，希望官方优化

**Comment by meiyixiang** [comment]
很好的建议，已经向产品反馈。功能开发完成后会在更新日志中提现，请耐心等待。
