### ISSUE TITLE
Screen don’t turn on back from suspension

### ISSUE THREAD

**Issue by teodoroau** [linuxdeepin/developer-center#2128]
I have this problem from deepin 20.1. On my Lenovo G40 When I suspend the computer and then I try to turn on, the mouse and the keyboard turned on but the screen still off the unique way to back the system is rebooting. Anyone have an idea to resolve this problem. I have all updated. I would appreciate the help, I really like Deepin, but not be able to suspend make me bad.

**Comment by Zeno-sole** [comment]
Can you provide kernel logs?

**Comment by Zeno-sole** [comment]
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue

**Comment by teodoroau** [comment]
Sorry I didn't write, I didn't save the kernel log, for the next bug I see I'll save it. Thanks you.
