### ISSUE TITLE
「功能建议」deepin-editor如何不打开以前打开过的老的文档

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2130]
我发现现在deepin-editor打开文档会把以前打开的文档统统打开，这样的话不仅拖慢了文档打开速度，而且占用了宝贵的标签空间，

希望deepin-editor默认不要打开以前打开过的老的文档，干干净净就打开我要打开的文档就可以了，如果非要保留打开老文档的功能，希望提供设置选项，用户需要这个功能，自己勾选。

**Comment by meiyixiang** [comment]
这个需求已经在规划了预计在20.5阶段会实现。

**Comment by widon1104** [comment]
我现在用uos家庭版了，希望修改能够同步到uos家庭版里面
