### ISSUE TITLE
Polish translation dde-file manager

### ISSUE THREAD

**Issue by yarecco70** [linuxdeepin/developer-center#2132]
since 2 editions there is a lack of translation into Polish in context menu of dde-file-manager it looks awful[](url)
![menu](https://user-images.githubusercontent.com/87233662/125164513-8cdd9380-e18a-11eb-90df-23a335ff1075.jpeg)

**Comment by vesterlay** [comment]
Follow-up https://bbs.deepin.org/en/post/217373

**Comment by raspin0** [comment]
I guess this issue can be closed, as it's already fixed in 20.3 
Polish translation got vastly updated internally and should be live within the next release #2156
