### ISSUE TITLE
Bug report 「缺陷报告」Wireless Mouse freezes after suspending OS

### ISSUE THREAD

**Issue by shyamdokka** [linuxdeepin/developer-center#2133]
Dear Team,

I use an external wireless USB mouse on Deepin 20.2.2. It works perfectly but freezes only after, I suspend the OS and get back after a while. I need to remove my USB receiver from the USB port and reconnect for my mouse to respond.

Any suggestions / Fix?

Thanks in advance...!

**Comment by babyfengfjx** [comment]
What is the problem of upgrading to the V20.4 version?

**Comment by babyfengfjx** [comment]
Since we have not been in touch for a long time, we will close the issue first. If there is any problem later, you can submit the issue in time. Thank you for your feedback.
