### ISSUE TITLE
config for lockscreen background

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/developer-center#214]
I am trying to find the configuration of the background image for lightdm-deepin-greeter so I can define a default different from the workspaces background for the next Manjaro edition.
Could someone please tell me where this setting is stored?
Is it somewhere in dconf schemas?
Thank you.

**Comment by hualet** [comment]
@jouyouyun

**Comment by felixonmars** [comment]
IIRC it's the `background-uris` key in /usr/share/glib-2.0/schemas/com.deepin.dde.appearance.gschema.xml

**Comment by oberon2007** [comment]
Thanks lot! :+1:
