### ISSUE TITLE
[Information] Update for debian Bullseye and Wayland

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#2141]
1. When will deepin be upgraded/migrated to the new stable debian (Bullseye)?

2. Are there any plans to migrate DDE to Wayland? If so, will this reach users in 2021?

**Comment by vesterlay** [comment]
For what's worth the next big update will take place in December. https://www.deepin.org/en/developer-community/planning/

**Comment by ClayStan** [comment]
yeah, we have these plans,But the release time has not yet been determined
