### ISSUE TITLE
「缺陷报告」正常使用时突然出现如下错误，听论坛有些人说是掉盘了？

### ISSUE THREAD

**Issue by wootifer** [linuxdeepin/developer-center#2143]
## 现象描述：
正常使用时突然出现如下错误，特别在待机休眠后，启动机器不多久就会出现，大概是在20.2.3后期的某个内测版本开始出现这个问题，重装20.2.4问题依旧。

![111](https://user-images.githubusercontent.com/26326251/138095398-78a667eb-a099-487e-bf2b-9be13512e373.png)

## 配置：拯救者R7000(R5 4600h 、16+512、GTX1650) ，扩展SSD(WD SN 550 1TB)自定义分区安装的deepin

**Comment by zccrs** [comment]
可以试一下 5.15 的内核

**Comment by wootifer** [comment]
> 可以试一下 5.15 的内核

使用5.15.6内核，经过连续两天不关机使用，目前没有出现问题，暂时先关闭此问题。
