### ISSUE TITLE
Bug | Keyboard Layout changes when update is available

### ISSUE THREAD

**Issue by atar-axis** [linuxdeepin/developer-center#2144]
Hey,
unfortunately I dont know to which this problem belongs...

Whenever there is a new system update, the keyboard layout changes from german to english.
This is not visible in the settings, there it is still german. But wherever I type something it is the english one?!

Really strange problem to me. At least I always know when there is a system update available xD

**Comment by babyfengfjx** [comment]
Hi, is this problem still exists in the latest version?What languages do you use by the system language?Is the configured keyboard layout only two kinds of German and English?

**Comment by atar-axis** [comment]
Yeah it still is. I only use German   
  

  

  

  
  
  
  
  
>

**Comment by babyfengfjx** [comment]
Can you help me to send me the system language and keyboard layout screenshot?

**Comment by BLumia** [comment]
Hi, we are on deepin v20.6 now, does this issue still exists? If it does, could you provide a screenshot that @babyfengfjx requested so we could look into it? Thanks!

**Comment by BLumia** [comment]
Closing since no further information provided. For people still have similar issue on the most recent release of DDE/deepin, please create a new issue report with necessary information provided so we can start reproducing the issue and look into it. Thanks!
