### ISSUE TITLE
Bug report [Locked/Freeze after suspend ]

### ISSUE THREAD

**Issue by titobundy** [linuxdeepin/developer-center#2146]
Dear Team,

I recently changed my computer to a HP Pavilion 15-eh0011la with Ryzen 7 processor, I installed the latest version of Deepin 20.2.4, It works perfectly but freezes when I suspend the OS (or closing laptop) and get back after a while. The system is locked with the black screen or windows appear but the system is freeze, only the mouse moves but does not react to anything and **I have to force shutdown and turn on again.**

Any suggestions / Fix?

Thanks in advance...!

More details or specifications here:

https://www.hp.com/cl-es/shop/notebook-hp-pavilion-laptop-15-eh0011la-310h1la.html

**Comment by widon1104** [comment]
Install newer kernel use: 
sudo apt install linux-image-5.13.13-amd64-desktop
then reboot the system and try again...

**Comment by titobundy** [comment]
> Install newer kernel use: sudo apt install linux-image-5.13.13-amd64-desktop then reboot the system and try again...

Thanks, Is it safe to update the kernel if I I have dual boot systems Windows 10 an Deepin ? 

My current kernel
```
uname -r
5.10.60-amd64-desktop
```

**Comment by titobundy** [comment]
I updated the kernel from 5.10.60 to 5.13.13 but it didn't work, also I tried change this

`GRUB_CMLINE_LINUX_DEFAULT="splash quiet acpi=off noapic nolapic"`

and then update grub, but the problem still remains.

this error message appears at startup

![acpi-error-min](https://user-images.githubusercontent.com/37158954/135770804-b962f627-477f-40fd-8139-97e8d8c61008.jpg)

**Comment by Zeno-sole** [comment]
It's a firmware bug. ACPI entries not conforming to the ACPI specifications is an extremely common problem.    You can try to update the firmware to solve
