### ISSUE TITLE
Bug report 「缺陷报告」Chrome点击按键没有反应

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2147]
![点击帖子没有反应](https://user-images.githubusercontent.com/12093211/135843739-9c07b2c2-4179-46e5-bd99-7b02b3e1bc1c.gif)
如上图，我用chrome点击帖子这个按键没有反应（偶先，一旦出现必须重启chrome才行），
我在deepin bbs发了一个帖子：https://bbs.deepin.org/zh/post/217457
这个问题从chrome 89.0.4389.90开始到现在94.0.4606.71，问题依旧没有解决
我对前端不太懂，请问一下这个帖子是什么组件？如果能够告诉我帖子这个是什么组件，我再去google一下，
不知道能不能解决这个问题，希望deepin官方协助解决一下这个问题

**Comment by widon1104** [comment]
这个bug出现的时候，bilibili.com视频网站的视频窗口不可以全屏了

**Comment by widon1104** [comment]
版本 96.0.4664.45（正式版本） （64 位）这个bug还存在

**Comment by myml** [comment]
Bug昨天修了，可以再试试还存在不

**Comment by widon1104** [comment]
> Bug昨天修了，可以再试试还存在不

1）deepin论坛现在暂时正常，但是uos论坛还存在这个bug
2）我觉得这个bug没有那么简单，不是论坛的问题，是chrome底层bug导致的，要根除这个bug还是需要chrome来修复，因为firefox下没有这个bug

**Comment by myml** [comment]
> > Bug昨天修了，可以再试试还存在不
> 
> 1）deepin论坛现在暂时正常，但是uos论坛还存在这个bug 2）我觉得这个bug没有那么简单，不是论坛的问题，是chrome底层bug导致的，要根除这个bug还是需要chrome来修复，因为firefox下没有这个bug

有时候这种是前端未检测浏览器兼容性，实现某些功能在另一个浏览器会工作不正常。deepin论坛现在是单独维护的，uos论坛还存在是正常的，我把这个问题修复同步给相关的开发

**Comment by widon1104** [comment]
> > > Bug昨天修了，可以再试试还存在不
> > 
> > 
> > 1）deepin论坛现在暂时正常，但是uos论坛还存在这个bug 2）我觉得这个bug没有那么简单，不是论坛的问题，是chrome底层bug导致的，要根除这个bug还是需要chrome来修复，因为firefox下没有这个bug
> 
> 有时候这种是前端未考虑浏览器兼容性，实现某些功能在另一个浏览器会工作不正常。deepin论坛现在是单独维护的，uos论坛还存在是正常的，我把这个问题修复同步给相关的开发

我觉得这个bug最好报给chrome官方最好，我不懂前端所以说不清楚，希望你们帮忙报给chrome，你这样修复论坛没有多大用，因为这个bug会影响很多网站，比如说出现这个bug的时候淘宝网的我的淘宝-》已买到的宝贝也没有反应。

**Comment by widon1104** [comment]
Chrome出现这个bug的时候，西瓜视频右上角个人图标弹出来的个人主页点击也没有反应，这个bug影响应该很大，不可能修改所有网站去绕过这个bug

**Comment by widon1104** [comment]
我又发现出现这个bug的时候，所有基于chromium内核的浏览器都不正常了，比如说chrome发现了这个bug以后，我转用龙芯浏览器发现同样存在这个bug，我觉得是chromium内核基于linux的某个包有bug导致的问题

**Comment by widon1104** [comment]
我发现使用chrome看b站的时候，偶尔会出现视频不能全屏，进度条无法拉动的bug，这chrome真是越来越不好用了

**Comment by Zeno-sole** [comment]
96 版本的Chrome还有这个问题么

**Comment by myml** [comment]
我以为是前端代码对按钮的点击时间处理有问题呢，看来可能是浏览器自身的bug。
可以试试用其他的内核版本比较新的浏览器比如Edge，我在用的Brave暂时没遇到这类问题。
谢谢你的反馈，但是这个不属于deepin的问题，所以在这个Issues我先关闭了

**Comment by widon1104** [comment]
我发这个issue是希望deepin能够协助解决这个问题，，
