### ISSUE TITLE
Matebook x PRO(2021) install screen breaks when selecting language

### ISSUE THREAD

**Issue by IvRRimum** [linuxdeepin/developer-center#2148]
Brand new matebook x PRO, bootable USB, I select "Install Deepin", i see language select for few seconds then it shows this:
![photo_2021-10-11 19 18 40](https://user-images.githubusercontent.com/5957079/136823142-a49cfc39-dd32-406d-87ba-f68f73500f4f.jpeg)

Installation when i select "Install Deepin (safe graphics)", but the OS has laggy graphics.

**Comment by Zeno-sole** [comment]
So, if the normal mode has issues use safe graphics instead

**Comment by Zeno-sole** [comment]
Please don't use it if there is no problem in normal mode safe graphics
