### ISSUE TITLE
Bug Report | Launcher doesn't work properly on start-up

### ISSUE THREAD

**Issue by Kevin-A02** [linuxdeepin/developer-center#2149]
Dear Team,

Let me start by saying that English is not my primary language.
I recently installed the latest version of Deepin (20.2.4). 
When the PC start up the "Launcher" doesn't work correctly, I see from the animations that it opens but immediately it closes. Fiddling around a bit, I thought about to start the "Launcher" manually and the problem disappears until I restart the PC.

This is a video of what I mentioned above:
https://user-images.githubusercontent.com/58368842/137889681-25ceac61-8dd2-41f2-a24d-2d875261b507.mp4

**Comment by Zeno-sole** [comment]
Please update the system to the latest version
