### ISSUE TITLE
[Arch Linux] Can't open files from Desktop using keyboard

### ISSUE THREAD

**Issue by gustavodlima** [linuxdeepin/developer-center#215]
I'm not able to open any file from Desktop using keyboard (typing 'Enter'), only clicking on it. I didn't tried before, but currently it doesn't work.

e.g: I have a folder named "test" on my Desktop. If I select it and then hit Enter, folder will not open and it also occurs with files.

**Comment by funilrys** [comment]
Gonna test it when I'm back to my computer 😄 I don't use this method so hope that it's not a random issue 😉

**Comment by funilrys** [comment]
Same here @gustavodlima !

**Comment by hualet** [comment]
Its latest version works well here on deepin, and it wouldn't be long till you get a new version, please try it then :smiley:

**Comment by funilrys** [comment]
Still not working here after update :sweat_smile:

**Comment by gustavodlima** [comment]
@hualet It's working now. Thks!

**Comment by funilrys** [comment]
Forgot my last answer, you can close @gustavodlima after update on my laptop no problem anymore
