### ISSUE TITLE
「建议」建议deepin文件管理器加入uos有的我的手机功能

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2152]
现在deepin下想和手机交互还要使用kde connect，而kde connect安装麻烦，使用也不是很符合国人习惯
希望deepin文件管理器引入uos文件管理器有的我的手机功能，引导deepin用户安装使用统信uos助手来和手机交互

**Comment by disburden** [comment]
有啊,在商店里有个叫"手机助手"的app,我也是最近才发现的,之前也是折腾的够呛

**Comment by widon1104** [comment]
> 有啊,在商店里有个叫"手机助手"的app,我也是最近才发现的,之前也是折腾的够呛
![截图录屏_选择区域_20211124115145](https://user-images.githubusercontent.com/12093211/143171890-2adbab4e-3ffc-4492-8f9b-7e6ce4d9fef2.jpg)
deepin文件管理器应该没有“我的手机”这一项吧

**Comment by meiyixiang** [comment]
当前手机助手未开源，所以没有在社区预装集成。

**Comment by widon1104** [comment]
希望手机助手赶快开源，助力deepin发展，kde connector难以安装难以使用
