### ISSUE TITLE
Manjaro deepin: cannot shutdown when empty passwords

### ISSUE THREAD

**Issue by abda11ah** [linuxdeepin/developer-center#2153]
## Issue: Bug 

Hi, I removed all the passwords prompts on my manjaro install.
I removed passwords prompts from visudo, polkit (globally), lightdm and i ran the commands :
passwd -d username
passwd -d root

Because i'm the only person who use my PC and of course I trust myself. I don't want to type passwords everytime.

But i think this install method was not planned by deepin devs because when i click the shutdown button of the deskbar i get a french message that means "unable to lock the screen"
So the only method that works is to logout/shutdown computer via a terminal window or via a third party app.

**Comment by peeweep** [comment]
>  I removed passwords prompts from visudo, polkit (globally), lightdm

Which files have you edited and what changes have been made?

**Comment by abda11ah** [comment]
"Sudo visudo" command to disable root password prompts
Set an autologin on lightdm (/etc/lightdm.conf)
Disable passwords globally on polkit :
Create the following file as root:

/etc/polkit-1/rules.d/49-nopasswd_global.rules

/* Allow members of the wheel group to execute any actions
 * without password authentication, similar to "sudo NOPASSWD:"
 */
polkit.addRule(function(action, subject) {
    if (subject.isInGroup("wheel")) {
        return polkit.Result.YES;
    }
});

**Comment by peeweep** [comment]
This problem did not reproduce on Deepin, but it did reproduce on Manjaro. We don’t know the reason yet, but we will continue to investigate.

**Comment by peeweep** [comment]
There are no manjaro users within our community developers, it is recommended that you report this bug to the manjaro community.
