### ISSUE TITLE
Bug report 「缺陷报告」

### ISSUE THREAD

**Issue by isuru0766764313** [linuxdeepin/developer-center#2154]
What's wrong with Deepin new release version 20.2.4? 😔

After screen lock I can't login computer again..
I entered the lock screen password correctly..
Then it says certification successful..
But lock screen doesn't disappear..
Then even I tried to start by power buttons..
It doesn't allow me to restart or shutdown..
I had no no option but turn off computer but long pressing laptop physical power button and restart.

It's will damage the HDD..😔😔
Look at this screen shot below👇

![IMG_20211128_163944](https://user-images.githubusercontent.com/73463334/144352356-d91de596-373d-4f96-9037-d4757c121c95.jpg)

Whf going on with this..
Pls anyone help me with this..

Thanks in advance..

**Comment by disburden** [comment]
First press Ctrl + Alt + F2 or F3 to switch to terminal mode
Then press Ctrl + Alt + F1 to switch back to the graphical interface. You should be able to log in

**Comment by justforlxz** [comment]
Still have this problem?

try to press Ctrl Alt F4 to switch tty and login again.

if you can login to tty, try to update system: `sudo apt update && sudo apt dist-upgrade`.

**Comment by justforlxz** [comment]
Sorry for not getting a reply for a long time, I need to close this issue.
