### ISSUE TITLE
「问题」deepin基于debian对硬件较新的电脑支持不好

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2155]
我最近在逛deepin论坛的时候发现，有些用户买了华为或者其他品牌的笔记本以后总会出现各种各样的问题，比如说没有声音，无线或者蓝牙不能连上等等问题，我想出现这样的问题是不是因为deepin基于debian，而debian的包都比较老的原因。我知道支持新的硬件需要时间，但是如果基于debian，支持新的硬件估计要非常久，这其实是一个问题。而deepin的开发者总不能让用户不去买带最新硬件的品牌机吧？

**Comment by justforlxz** [comment]
基于debian 11的deepni已经快准备就绪了。内核我们其实是有单独升级的，兼容性问题我们也一直很关注。

**Comment by nohappiness** [comment]
呃  是 deepin，不是 deepni …… @justforlxz 😄

**Comment by justforlxz** [comment]
> 呃  是 deepin，不是 deepni …… @justforlxz 😄 

手抖😂

**Comment by zccrs** [comment]
其实硬件兼容性问题主要是跟内核版本相关，所以我们专门做了双内核机制，只不过默认不是使用最新版，如果使用最新版内核启动后，还是有这些问题，那即便用了其它发行版一般也是一样。

**Comment by widon1104** [comment]
> 其实硬件兼容性问题主要是跟内核版本相关，所以我们专门做了双内核机制，只不过默认不是使用最新版，如果使用最新版内核启动后，还是有这些问题，那即便用了其它发行版一般也是一样。

硬件兼容问题可不止与内核版本相关，我知道的，如果你用的是11代intel cpu，如果没有升级mesa库，那显卡驱动不能正常工作，那系统不就瘫痪了吗？amd也是一样，所以我觉的光内核保持高版本并不能解决问题

**Comment by zccrs** [comment]
> 

这都是环环相扣的，高版本的mesa往往也会依赖高版本内核。不过显卡方面的兼容性的确要单独考虑，一是太容易出问题了，二是它比较特殊。

**Comment by widon1104** [comment]
> 这都是环环相扣的，高版本的mesa往往也会依赖高版本内核。不过显卡方面的兼容性的确要单独考虑，一是太容易出问题了，二是它比较特殊。

还不止显卡有问题，有些人买了新的笔记本以后，没有声音，但内核是最新5.15，那又是什么问题呢？

**Comment by Zeno-sole** [comment]
linux-firmware 我们已经更新到1.202版本了

**Comment by Zeno-sole** [comment]
@widon1104  linux上的硬件兼容性一直都不是很好，对此你有什么建议？

**Comment by widon1104** [comment]
> 

具体细节我也不太懂，但是我觉得deepin应该研究一下，一些重要的包，比如说支持显卡、硬盘、声卡、无线、蓝牙的包可否单独升级到最高版本，不要跟着debian走

**Comment by Zeno-sole** [comment]
是的，我们有很多组件也没有跟着debian走了，你说的这些包我们会逐步升上来的，请关注我们后续的更新

**Comment by widon1104** [comment]
deepin现在居然连11代CPU的核显都不支持：
[问题求助] 11代i7, 分辨率只有1024×768
https://bbs.deepin.org/post/236753
