### ISSUE TITLE
Deepin lite please

### ISSUE THREAD

**Issue by fcore117** [linuxdeepin/developer-center#2157]
Deepin is amazing fast QT C++ desktop, but please offer barebone edition of Deepin too with lesser disk usage and without any apps that are not part of desktop system. For example, apps like Libreoffice, mail, video and audio player(VLC is aio player or whatever user chooses), zero games like thoseLianLianKan etc.

In the end .iso size would be smaller, disk requirement would be smaller, users could choose whatever extra they want installed.

**Comment by zccrs** [comment]
Good, this is a very significant suggest. Can you tell me, after installing the lite version of deepin, what you will do outside of this, what applications will be installed, and what content do you think is the core of an operating system and is worthy of being included in the ISO?

**Comment by meiyixiang** [comment]
Deepin had the idea, but there are a lot of new users out there who don’t know about Linux applications, so they’ve pre-installed some basic ones. From your perspective, what software would you install if you offered a lightweight system?

**Comment by meiyixiang** [comment]
Now the system, the mirror is relatively large, but for non-system applications can be unloaded

**Comment by zccrs** [comment]
> Deepin had the idea, but there are a lot of new users out there who don’t know about Linux applications, so they’ve pre-installed some basic ones. From your perspective, what software would you install if you offered a lightweight system?

I only hope the "App Store"、"Browser"、"File Manager".

**Comment by fcore117** [comment]
> > Deepin had the idea, but there are a lot of new users out there who don’t know about Linux applications, so they’ve pre-installed some basic ones. From your perspective, what software would you install if you offered a lightweight system?
> 
> I only hope the "App Store"、"Browser"、"File Manager".

Perfect, just barebone Desktop that has everything same except without third party apps.

**Comment by meiyixiang** [comment]
Thank you so much for your advice! There are currently no such plans, and you can uninstall apps you don't need.
