### ISSUE TITLE
Clean the repositories

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/developer-center#2159]
- [x] Move the deprecated repositories to https://github.com/martyr-deepin
- [x] Set the mirrored repositories to readonly
  - [x] Readonly 4kstogram
  - [x] Readonly All-Users
  - [x] Readonly anydesk
  - [x] Readonly appstore
  - [x] Readonly apt
  - [x] Readonly aptly
  - [x] Readonly b1freearchiver
  - [ ] Readonly baka-mplayer
  - [ ] Readonly base-files
  - [ ] Readonly bcmwl
  - [ ] Readonly bcompare
  - [ ] Readonly bitwig-studio
  - [ ] Readonly bluez
  - [ ] Readonly blur-effect
  - [ ] Readonly boostnote
  - [ ] Readonly brackets
  - [ ] Readonly buka
  - [ ] Readonly caret
  - [ ] Readonly casper
  - [ ] Readonly cef
  - [ ] Readonly cef-binary
  - [ ] Readonly changelog
  - [ ] Readonly clutter
  - [ ] Readonly codelobsteride
  - [ ] Readonly com.deepin.Calendar
  - [ ] Readonly com.deepin.demo
  - [ ] Readonly com.deepin.gomoku
  - [ ] Readonly com.deepin.ImageViewer
  - [ ] Readonly com.deepin.lianliankan
  - [ ] Readonly com.deepin.Music
  - [ ] Readonly com.deepin.ScreenShot
  - [ ] Readonly com.deepin.VoiceRecorder
  - [ ] Readonly CompilationDatabase
  - [ ] Readonly crossftp
  - [ ] Readonly dapps
  - [ ] Readonly dbus
  - [ ] Readonly dbus-factory
  - [ ] Readonly dde
  - [ ] Readonly dde-account-faces
  - [ ] Readonly dde-api
  - [ ] Readonly dde-calendar
  - [ ] Readonly dde-clipboard
  - [ ] Readonly dde-control-center
  - [ ] Readonly dde-daemon
  - [ ] Readonly dde-desktop
  - [ ] Readonly dde-device-formatter
  - [ ] Readonly dde-dock
  - [ ] Readonly dde-file-dialog-gtk
  - [ ] Readonly dde-file-manager
  - [ ] Readonly dde-file-manager-integration
  - [ ] Readonly dde-file-manager-menu-oem
  - [ ] Readonly dde-help
  - [ ] Readonly dde-introduction
  - [ ] Readonly dde-kwin
  - [ ] Readonly dde-launcher
  - [ ] Readonly dde-network-utils
  - [ ] Readonly dde-polkit-agent
  - [ ] Readonly dde-preload
  - [ ] Readonly dde-printer
  - [ ] Readonly dde-qt-dbus-factory
  - [ ] Readonly dde-session-shell
  - [ ] Readonly dde-session-ui
  - [ ] Readonly dde-wallpapers
  - [ ] Readonly dde-wayland
  - [ ] Readonly debian_security_checker
  - [ ] Readonly deepin-ab-recovery
  - [ ] Readonly deepin-album
  - [ ] Readonly deepin-anything
  - [x] Readonly deepin-app-store
  - [x] Readonly deepin-app-store-web
  - [x] Readonly deepin-appstore
  - [ ] Readonly deepin-artwork
  - [ ] Readonly deepin-boot-maker
  - [ ] Readonly deepin-browser
  - [ ] Readonly deepin-build-servers
  - [ ] Readonly deepin-calculator
  - [ ] Readonly deepin-calendar
  - [ ] Readonly deepin-camera
  - [ ] Readonly deepin-clone
  - [ ] Readonly deepin-code-release
  - [ ] Readonly deepin-cogl
  - [ ] Readonly deepin-compressor
  - [ ] Readonly deepin-cursor-theme
  - [ ] Readonly deepin-deb-installer
  - [ ] Readonly deepin-default-settings
  - [ ] Readonly deepin-defender
  - [ ] Readonly deepin-desktop-base
  - [ ] Readonly deepin-desktop-schemas
  - [ ] Readonly deepin-devicemanager
  - [ ] Readonly deepin-diskmanager
  - [ ] Readonly deepin-download
  - [ ] Readonly deepin-draw
  - [ ] Readonly deepin-editor
  - [ ] Readonly deepin-emacs
  - [ ] Readonly deepin-faq
  - [ ] Readonly deepin-fcitxconfigtool-plugin
  - [ ] Readonly deepin-feedback
  - [ ] Readonly deepin-font-installer
  - [ ] Readonly deepin-font-manager
  - [ ] Readonly deepin-fprintd
  - [ ] Readonly deepin-gettext-tools
  - [ ] Readonly deepin-graphics-driver-manager
  - [ ] Readonly deepin-grub2-themes
  - [ ] Readonly deepin-gtk-theme
  - [ ] Readonly deepin-icon-theme
  - [ ] Readonly deepin-icon-theme-community
  - [ ] Readonly deepin-icon-theme-tools
  - [ ] Readonly deepin-image-viewer
  - [ ] Readonly deepin-input-method
  - [ ] Readonly deepin-installer
  - [ ] Readonly deepin-installer-reborn
  - [ ] Readonly deepin-kernel
  - [ ] Readonly deepin-kernel-tools
  - [ ] Readonly deepin-keyring
  - [ ] Readonly deepin-kglobalaccel
  - [ ] Readonly deepin-kwin
  - [ ] Readonly deepin-kwindowsystem
  - [ ] Readonly deepin-lang-selector
  - [ ] Readonly deepin-laptop-mode
  - [ ] Readonly deepin-log-viewer
  - [ ] Readonly deepin-manual
  - [ ] Readonly deepin-manual-documents
  - [ ] Readonly deepin-menu
  - [ ] Readonly deepin-metacity
  - [ ] Readonly deepin-movie
  - [ ] Readonly deepin-movie-reborn
  - [ ] Readonly deepin-music
  - [ ] Readonly deepin-mutter
  - [ ] Readonly deepin-notifications
  - [ ] Readonly deepin-on-loongson
  - [ ] Readonly deepin-opensymbol-fonts
  - [ ] Readonly deepin-phone-assistant
  - [ ] Readonly deepin-picker
  - [ ] Readonly deepin-plymouth
  - [ ] Readonly deepin-pw-check
  - [ ] Readonly deepin-qt5config
  - [ ] Readonly deepin-query-system
  - [ ] Readonly deepin-reader
  - [ ] Readonly deepin-remote-assistance
  - [ ] Readonly deepin-repair-tools
  - [ ] Readonly deepin-rlocate
  - [ ] Readonly deepin-scanner
  - [ ] Readonly deepin-screen-recorder
  - [ ] Readonly deepin-screensaver
  - [ ] Readonly deepin-screenshot
  - [ ] Readonly deepin-sdk
  - [ ] Readonly deepin-shortcut-viewer
  - [ ] Readonly deepin-sound-theme
  - [ ] Readonly deepin-store
  - [ ] Readonly deepin-styleguide
  - [ ] Readonly deepin-svgcheck
  - [ ] Readonly deepin-system-monitor
  - [ ] Readonly deepin-terminal
  - [x] Readonly deepin-terminal-gtk
  - [ ] Readonly deepin-testcases
  - [ ] Readonly deepin-theme-bucket
  - [ ] Readonly deepin-tool-kit
  - [ ] Readonly deepin-turbo
  - [ ] Readonly deepin-usermanual
  - [ ] Readonly deepin-voice-note
  - [ ] Readonly deepin-voice-note-old
  - [ ] Readonly deepin-voice-recorder
  - [ ] Readonly deepin-wallpapers
  - [ ] Readonly deepin-wallpapers-nonfree
  - [ ] Readonly deepin-webengine
  - [ ] Readonly deepin-webengine-chromium
  - [ ] Readonly deepin-windows-installer
  - [ ] Readonly deepin-wine-patch
  - [ ] Readonly deepin-wm
  - [ ] Readonly default-settings
  - [ ] Readonly desktop-entry-editor
  - [ ] Readonly develop-manual
  - [ ] Readonly developer-center
  - [ ] Readonly disomaster
  - [ ] Readonly dmidecode
  - [ ] Readonly docker-check-dep
  - [ ] Readonly docker-services
  - [ ] Readonly docs
  - [ ] Readonly dpa-ext-gnomekeyring
  - [ ] Readonly dstore-web-components
  - [ ] Readonly dsystem
  - [ ] Readonly dtk
  - [ ] Readonly dtk-docs
  - [ ] Readonly dtkcommon
  - [ ] Readonly dtkcore
  - [ ] Readonly dtkgui
  - [ ] Readonly dtksettings
  - [ ] Readonly dtktools
  - [ ] Readonly dtkwidget
  - [ ] Readonly dtkwm
  - [ ] Readonly dweb
  - [ ] Readonly fcitx
  - [ ] Readonly fcitx-configtool
  - [ ] Readonly fcitx-qt5
  - [ ] Readonly file
  - [ ] Readonly flatpak-deepin-applications
  - [ ] Readonly flatpak-deepin-runtime
  - [ ] Readonly fprintd
  - [ ] Readonly gerrit-project-creation
  - [ ] Readonly gio-qt
  - [ ] Readonly git-repo
  - [ ] Readonly go-dbus-factory
  - [ ] Readonly go-dbus-generator
  - [ ] Readonly go-gir
  - [ ] Readonly go-gir-generator
  - [ ] Readonly go-lib
  - [ ] Readonly go-x11-client
  - [ ] Readonly gparted
  - [ ] Readonly granite
  - [ ] Readonly grub2
  - [ ] Readonly gsettings-qt
  - [ ] Readonly gtk2.0
  - [ ] Readonly gtk3.0
  - [ ] Readonly huawei-wmi
  - [ ] Readonly im-config
  - [ ] Readonly imagemagick
  - [ ] Readonly init-data
  - [ ] Readonly internal-discussion
  - [ ] Readonly iso-desktop
  - [ ] Readonly kanbanmgr
  - [ ] Readonly lastore-daemon
  - [ ] Readonly lastore-daemon-migration
  - [ ] Readonly libdui
  - [ ] Readonly libqapt
  - [ ] Readonly libqt5xcbqpa-dev
  - [ ] Readonly lightdm
  - [ ] Readonly mintdrivers
  - [ ] Readonly miraclecast
  - [ ] Readonly mirrors_status
  - [ ] Readonly network-manager
  - [ ] Readonly nomachine
  - [ ] Readonly nvidia-prime
  - [ ] Readonly onboard
  - [ ] Readonly only-for-test
  - [ ] Readonly open-with-dialog
  - [ ] Readonly org.deepin.downloader
  - [ ] Readonly os-autoinst
  - [ ] Readonly package-tag
  - [ ] Readonly Patch
  - [ ] Readonly pkg_debian
  - [ ] Readonly plymouth-theme-deepin
  - [ ] Readonly policykit-1
  - [ ] Readonly pulseaudio
  - [ ] Readonly qcef
  - [ ] Readonly qcef-chromium
  - [ ] Readonly qt-patch
  - [ ] Readonly qt5deepintheme-plugin
  - [ ] Readonly qt5integration
  - [ ] Readonly qt5platform-plugins
  - [ ] Readonly qtbase-opensource-src
  - [ ] Readonly qtcreator-template-dtk
  - [ ] Readonly qtdbusextended
  - [ ] Readonly qtmpris
  - [ ] Readonly qttranslations-opensource-src
  - [ ] Readonly repo_usability_for_everyone
  - [ ] Readonly rr_check
  - [ ] Readonly rstudio
  - [ ] Readonly server-status-checker
  - [ ] Readonly shim-review
  - [ ] Readonly shutter
  - [ ] Readonly simple-scan
  - [ ] Readonly software-center-apps
  - [ ] Readonly startdde
  - [ ] Readonly store-nvchecker
  - [ ] Readonly sudo
  - [ ] Readonly sw-go-tools
  - [ ] Readonly sync-transifex
  - [ ] Readonly system-config-printer
  - [ ] Readonly team-robots
  - [ ] Readonly test
  - [ ] Readonly testgerrit
  - [ ] Readonly thirdparty_pkg_debian
  - [ ] Readonly tower-team-reporter
  - [ ] Readonly ttf-deepin-opensymbol
  - [ ] Readonly twolame
  - [ ] Readonly udisks2
  - [ ] Readonly udisks2-qt5
  - [ ] Readonly uos-browser
  - [ ] Readonly vendor-deps
  - [ ] Readonly warm-sched
  - [ ] Readonly xdg-utils
  - [ ] Readonly xorg-server

**Comment by justforlxz** [comment]
These repositories have been transferred to https://github.com/martyr-deepin
<details>
<summary>see all</summary>

```
apt
aptly
arch-deepin
b1freearchiver
baka-mplayer
base-files
bcmwl
bcompare
bitwig-studio
bluez
boostnote
brackets
buka
caret
casper
cef
cef-binary
changelog
clutter
codelobsteride
CompilationDatabase
crossftp
dae
dapps
dbus
dde-dock-applets
dde-workspace
debian_security_checker
deepin-app-store
deepin-app-store-web
deepin-appstore
deepin-artwork-themes
deepin-build-servers
deepin-code-release
deepin-cogl
deepin-compiz
deepin-crash-reporter
deepin-download-service
deepin-emacs
deepin-emacs-old
deepin-file-manager-backend
deepin-game
deepin-gnome-shell
deepin-gnome-shell-extensions
deepin-gsettings
deepin-installer
deepin-installer-reborn
deepin-irc-log
deepin-laptop-mode
deepin-libwm
deepin-media-player
deepin-menu
deepin-metacity
deepin-movie
deepin-nautilus-properties
deepin-notifications
deepin-on-loongson
deepin-os-upgrader
deepin-phone-assistant
deepin-qml-widgets
deepin-remote-assistance
deepin-repair-tools
deepin-rlocate
deepin-scanner
deepin-screenshot
deepin-screenshot-v2
deepin-screenshot-v3
deepin-settings-daemon
deepin-social-sharing
deepin-software-center-data
deepin-store
deepin-store-manager
deepin-storm
deepin-svgcheck
deepin-system-settings
deepin-system-tray
deepin-talk
deepin-terminal
deepin-terminal-gtk
deepin-themes
deepin-tool-kit
deepin-translator
deepin-ui
deepin-user-manual
deepin-usermanual
deepin-utils
deepin-voice-note-old
deepin-webengine
deepin-webengine-chromium
deepin-webkit
deepin-windows-installer
deepin-wm
deepin-wm-switcher
DeepinWin
default-gsettings
delete-django-paste
delete-go-dbus
delete-go-qt5
delete-oauth2app
desktop-plugins
diso
dltk
dmidecode
docker-check-dep
docker-services
docs
dra-chromium
dstore-web-components
dsystem
dtk
dtkwm
dweb
emacs-webkit
fcitx
file
flatpak-deepin-applications
flatpak-deepin-runtime
fprintd
gerrit-project-creation
git-repo
go-dbus-generator
gparted
granite
grub2
gsettings-qt
gtk2.0
huawei-wmi
im-config
imagemagick
init-data
kanbanmgr
lastore-daemon-migration
libdui
liblunar
libqapt
libqt5xcbqpa-dev
lightdm
linuxdeepin-application-development-manual
mintdrivers
miraclecast
mirrors_status
network-manager
nomachine
onboard
only-for-test
openQA
openQA-base
openQA-trigger
openQA-webui
openQA-worker
os-autoinst
package-tag
Patch
pkg_debian
plymouth-theme-deepin
policykit-1
pulseaudio
pypulseaudio
pystorm
python-vte
qcef
qcef-chromium
qml-dde-dock-applet
qml-gettext-plugin
qt-patch
qt5deepintheme-plugin
QtAV
qtbase-opensource-src
qtcreator-template-dtk
qtdbusextended
qtmpris
qttranslations-opensource-src
repos
repo_usability_for_everyone
rr_check
rstudio
server-status-checker
shutter
simple-scan
store-nvchecker
sudo
sw-go-tools
sync-transifex
system-config-printer
team-robots
test
testgerrit
thirdparty_pkg_debian
tower-team-reporter
twolame
udisks2
vendor-deps
warm-sched
xdg-utils
```
</details>
