### ISSUE TITLE
Bug: /var/tmp permission AND its affect to Flatpak downloading

### ISSUE THREAD

**Issue by foresee-io** [linuxdeepin/developer-center#2161]
## Solution
[Deepin Community (Chinese)](https://bbs.deepin.org/post/228388)
``` bash
sudo chmod 1777 /tmp
sudo chmod 1777 /var/tmp
```

## Steps
* Fresh install Deepin 20.3 in UEFI mode.
* Run the following commands.
``` bash
sudo apt update; sudo apt install flatpak;
sudo flatpak --system remote-add --if-not-exists flathub \
  https://flathub.org/repo/flathub.flatpakrepo;
sudo flatpak --system -y install org.flameshot.Flameshot
```
* **Then Flatpak can't just even download packages!** Here's terminal output.
```
        ID                                            Arch             Branch           Remote            Download
 1. [✗] org.kde.Platform                              x86_64           5.15             flathub           < 371.8 MB
 2. [ ] org.freedesktop.Platform.GL.default           x86_64           20.08            flathub           < 106.4 MB
 3. [ ] org.freedesktop.Platform.openh264             x86_64           2.0              flathub             < 1.5 MB
 4. [ ] org.kde.KStyle.Adwaita                        x86_64           5.15             flathub             < 6.6 MB
 5. [ ] org.kde.Platform.Locale                       x86_64           5.15             flathub           < 341.5 MB (partial)
 6. [ ] org.flameshot.Flameshot                       x86_64           stable           flathub           < 863.7 kB

Error: Can't create temporary directory
error: Failed to install org.kde.Platform: Can't create temporary directory
```
* Solution is written above.

### System
  * Fresh installation of `deepin-desktop-community-20.3-amd64.iso`
  * SHA256: `cb22e7360a16f3ab31d827e4ce67f2e0a8bb0092b6473f5e653eb61afa86123b`
  * Kernel 5.15
### Have bug
  * UEFI, Disk, Lenovo Legion Y7000 2019 PG0 (81T0)
  * Legacy, Disk, VMware
### No Bug
  * UEFI/Legacy, LiveCD, Lenovo Legion Y7000 2019 PG0 (81T0)

**Comment by foresee-io** [comment]
It is now fixed in Deepin V23 Nightly (fresh install). 

> deepin-desktop-community-23-nightly-amd64.iso
> SHA256: `dd95d32491e7cdeb378d742ad58bab0808cbe1799b71015988ed7d9f5c362eb8`

**Comment by justforlxz** [comment]
maybe `flatpack repair` can fix it if this problem occurs again.
