### ISSUE TITLE
编译dde-control-center报错

### ISSUE THREAD

**Issue by clcmj** [linuxdeepin/developer-center#2162]
process translations/reset-password-dialog_zh_TW.ts
Updating 'translations/reset-password-dialog_zh_TW.qm'...
    Generated 38 translation(s) (38 finished and 0 unfinished)
OS: uos, Version: 20
Deepin OS Type: Professional
Deepin OS Version: 20
CMake Error at src/frame/CMakeLists.txt:593 (dconfig_meta_files):
  Unknown CMake command "dconfig_meta_files".

**Comment by kt286** [comment]
https://github.com/linuxdeepin/dtkcommon/blob/master/cmake/Dtk/DtkInstallDConfigConfig.cmake

**Comment by zccrs** [comment]
It's depend the dtkcommon

**Comment by clcmj** [comment]
ok,It has been solved
