### ISSUE TITLE
Validity Sensors VFS491 without controllers

### ISSUE THREAD

**Issue by alvarosamudio** [linuxdeepin/developer-center#2164]
the VFS491 validation sensor, used for fingerprint scanning, has no drivers in linux deepin.
for this sensor only proprietary drivers are available https://ftp.hp.com/pub/softpaq/sp84501-85000/sp84530.tar https://github.com/rindeal/libfprint-vfs_proprietary-driver

these drivers work for various models of fingerprint readers used in computers.

**Comment by alvarosamudio** [comment]
![144924537-d8d1cf42-3caf-46f7-bd1e-8faeedbd2418](https://user-images.githubusercontent.com/25090546/146706751-d87505dc-7b15-4160-a193-670c725cb43e.png)
this is the complete hardware of the pc where this sensor is located https://linux-hardware.org/?probe=7752a79879

**Comment by Zeno-sole** [comment]
that this driver is still far from optimal, We won't join for now
