### ISSUE TITLE
[Bug report] double telegram icons in the launcher

### ISSUE THREAD

**Issue by alvarosamudio** [linuxdeepin/developer-center#2165]
![image](https://user-images.githubusercontent.com/25090546/146706814-e9c7476f-677f-4bbe-8e0c-43c5b746e596.png)
installing telegram from the app store creates double icons in the launcher

**Comment by kt286** [comment]
This bug has been recorded, you can run `rm -rf ~/.config/deepin/dde-launcher-app-used-sorted-list.conf` to fix it temporarily.

**Comment by justforlxz** [comment]
Telegram usually generates an icon under `~/.local/share/applications/` in the user directory, which is duplicated with `/usr/share/applications`. I will add a check.

**Comment by alvarosamudio** [comment]
> /usr/share/applications

![image](https://user-images.githubusercontent.com/25090546/147723712-f6169aa9-5db3-418e-9320-1301b973b02b.png)
there are telegram icons on the two routes you mention

**Comment by BLumia** [comment]
It should be fixed now. If you install telegram via the built-in app store, package `org.telegram-desktop` (currently `3.5.2`) will be installed and there are no longer duplicated icons in the launcher.

![image](https://user-images.githubusercontent.com/10095765/178177361-f66b7b44-54e1-4a18-ac41-fe27b665cdb4.png)

If you still have this issue on the most recent release, please feel free to create a new issue so we can look into it. Thanks!
