### ISSUE TITLE
[Suggestion] Concept for choosing a custom color in the deepin control panel

### ISSUE THREAD

**Issue by alvarosamudio** [linuxdeepin/developer-center#2166]
![image](https://user-images.githubusercontent.com/25090546/146718148-3af84579-34d1-4539-af4e-5cba0095d01f.png)
Concept for choosing a custom color in the deepin control panel.
this would increase the persolaization.

**Comment by zccrs** [comment]
@shule1987 It looks good

**Comment by meiyixiang** [comment]
Hello friend, have you implemented this function? We don't have such a plan for our products at the moment but I have recorded your suggestion

**Comment by alvarosamudio** [comment]
it was just a design concept

**Comment by meiyixiang** [comment]
This is a good suggestion, no one is developing it at present, we will consider this feature later. Are you a developer or a designer?

**Comment by alvarosamudio** [comment]
> Esta es una buena sugerencia, nadie la está desarrollando en este momento, consideraremos esta característica más adelante. ¿Eres desarrollador o diseñador?

Yes I am a developer, about the suggestion, I make it because I wonder what could help to increase the customization of the system and that would help.

**Comment by meiyixiang** [comment]
Deep community plans to recruit developers in the future to do something meaningful together. I was wondering if you’d be interested in joining us? There are a lot of good ideas out there, but we don’t have the manpower to make them happen

**Comment by meiyixiang** [comment]
To invite you to join us

**Comment by alvarosamudio** [comment]
> Deep Community planea reclutar desarrolladores en el futuro para hacer algo significativo juntos. Me preguntaba si estaría interesado en unirse a nosotros. Hay muchas buenas ideas, pero no tenemos la mano de obra para hacerlas realidad.

of course, I would like to contribute, I'm part of the deepin community in spanish, I'm one of the members fuders. https://deepinenespañol.org/los-miembros-del-equipo/

**Comment by meiyixiang** [comment]
That's great! We have set up an overseas community exchange group in Telegram, you can participate. We can get involved in the operation and development direction of the community.
