### ISSUE TITLE
[Suggestion] it would be great if the file manager could preview the cover of the songs

### ISSUE THREAD

**Issue by alvarosamudio** [linuxdeepin/developer-center#2167]
![image](https://user-images.githubusercontent.com/25090546/146719028-9b5c761a-8690-4224-9fd1-16ad9a2f18eb.png)

**Comment by meiyixiang** [comment]
Great idea, it will be supported next year

**Comment by alvarosamudio** [comment]
![image](https://user-images.githubusercontent.com/25090546/147291234-254508a5-5c38-4b7f-84fb-77495fde4052.png)
a member of the deepin and spanish community has programmed this function

**Comment by meiyixiang** [comment]
Patch has been submitted, and R & D is evaluating whether it can be connected with the company
