### ISSUE TITLE
[Suggestion] Update Deepin Live System (live care)

### ISSUE THREAD

**Issue by alvarosamudio** [linuxdeepin/developer-center#2168]
it would be a good idea to update deepin live care with the new deepin features and applications such as deepin device manager, deepin disk manager, deepin log viewer, deepin defender and deepin phone assistant.

**Comment by Zeno-sole** [comment]
The interface of mirror installation removes the livecd-installer parameter of grub, or you can directly enter the live system

**Comment by meiyixiang** [comment]
34/5000 
With a plan but no human resources, the current system can solve part of the fix. Thanks for your advice!

**Comment by alvarosamudio** [comment]
> 34/5000 Con un plan pero sin recursos humanos, el sistema actual puede resolver parte del arreglo. ¡Gracias por su consejo!

I understand, I hope to be able to

**Comment by meiyixiang** [comment]
2022年会支持live系统

**Comment by meiyixiang** [comment]
Live will be supported in 2022
