### ISSUE TITLE
heic wallpapers support

### ISSUE THREAD

**Issue by justforlxz** [linuxdeepin/developer-center#2169]
heic is High Efficiency Image File Format, or heif. support sequence pictures.

In the mac system, heic pictures can be used as live wallpapers, that allows the system to switch automatically according to time.

**Comment by meiyixiang** [comment]
抱歉当前没有这个计划，你可以将hice图片转换成deepin支持格式使用

**Comment by meiyixiang** [comment]
Sorry we don't have this plan at the moment, you can convert hice images to deepin supported format for use

**Comment by meiyixiang** [comment]
Unfortunately, the company has no current plans to implement this feature

**Comment by BLumia** [comment]
Also see: https://github.com/linuxdeepin/developer-center/issues/2413 https://github.com/linuxdeepin/developer-center/discussions/2913
