### ISSUE TITLE
deepin-wm should not override keyboard repeat rate/delay on startup

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#217]
This is only a issue for deepin-wm, not deepin-metacity or any other wm.

**Comment by hualet** [comment]
@sonald @jouyouyun

**Comment by sonald** [comment]
@felixonmars  plz ref tower issue

**Comment by jouyouyun** [comment]
@felixonmars  dde-daemon 3.1.6 should have fixed this bug.

**Comment by felixonmars** [comment]
Confirmed the fix. Thanks a lot!
