### ISSUE TITLE
「改进建议」希望deepin&UOS能够让用户安装英伟达闭源驱动变得容易

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2179]
现在英伟达显卡的出货量非常的大，我个人就至少使用过3台使用英伟达显卡的电脑，这3台电脑使用英伟达开源驱动都会偶尔死机。
所以我觉得只要使用英伟达显卡的电脑都应该默认安装闭源驱动，那么如何让用户非常容易的安装英伟达闭源驱动呢？
首先，在安装deepin系统的时候检测到用户使用的是英伟达显卡就应该默认选中闭源驱动，如果用户勾除闭源驱动应该提示“使用开源驱动可能会导致死机”的提示。
对于已经安装好系统的用户，应该推荐使用显卡驱动管理器安装闭源驱动，我个人觉得使用命令行安装闭源驱动是绝对不推荐的，多一条命令就劝退10%的用户，10条命令下来，所有人都跑了。
现在显卡驱动管理器的功能还比较弱，针对显卡驱动管理器我提几个意见：
1）针对很多老的英伟达显卡没有做适配，很多老的显卡不能用新的驱动，但是现在显卡驱动管理器只带了新的驱动，导致驱动安装失败，所以显卡驱动管理器应该支持老的英伟达显卡
2）显卡驱动管理器不够智能，如果发现是内核和驱动不匹配导致驱动无法安装，需要给出建议，甚至直接一键安装合适的内核，但是现状只是报驱动切换失败，用户一脸懵逼
3）对多显卡的适配不是特别给力，性能、节能模式不能任意切换
4）显卡管理器程序不稳定，同样的配置，有时候切换成功，有时候切换失败
5）如果检测到切换失败，应该马上上报错误日志给开发者，让开发者知道问题，以后好加以改进

总的来说，显卡安装针对单显卡来说应该算是比较简单的，无非就是一个驱动和内核匹配的问题，我知道的，有些老显卡只能使用390版本的驱动，那就把和390驱动匹配的内核加入源，安装的时候先从源安装匹配的内核，然后切换到老的内核再安装驱动应该就没有问题了。
至于多显卡问题，如果使用了什么上游组件，遇到切换失败应该马上给上游上报问题有能力甚至可以参加上游开发。

我为什么说那么多呢，因为英伟达显卡闭源驱动安装是deepin&UOS上面一个老大难的问题，劝退了无数用户，我觉得驱动安装本来就是很机械的动作，很适合使用程序来解决的，可是这么多年来，这个问题解决的并不好，希望尽快改进，这应该是优先级最高的事情。

**Comment by widon1104** [comment]
我再补充一点，有用户说安装系统时候选择闭源驱动会导致问题，如无法开机、黑屏等问题
https://bbs.deepin.org/post/226415

问题确实比较多，希望发力解决

**Comment by justforlxz** [comment]
> 我为什么说那么多呢，因为英伟达显卡闭源驱动安装是deepin&UOS上面一个老大难的问题，劝退了无数用户，我觉得驱动安装本来就是很机械的动作，很适合使用程序来解决的，可是这么多年来，这个问题解决的并不好，希望尽快改进，这应该是优先级最高的事情。

其实可以反过来想一想，既然是机械的动作，为什么大家不按照你想的这样，用程序来解决呢？

**Comment by widon1104** [comment]
> > 我为什么说那么多呢，因为英伟达显卡闭源驱动安装是deepin&UOS上面一个老大难的问题，劝退了无数用户，我觉得驱动安装本来就是很机械的动作，很适合使用程序来解决的，可是这么多年来，这个问题解决的并不好，希望尽快改进，这应该是优先级最高的事情。
> 
> 其实可以反过来想一想，既然是机械的动作，为什么大家不按照你想的这样，用程序来解决呢？

我不知道你说的大家指的是什么，我知道的windows下有很多如驱动精灵之类的软件，就简单的点一下就可以安装各种版本的各种驱动，这难道不是在用程序来解决问题。如果deepin&UOS做不到windows的这种易用性，谁还能用deepin，谁还会用deepin呢，linux的市场占有率又怎么能提高呢，要知道linux市占率的提高意味着抢windows和mac的市场，做的没人家好，咋个可能抢人家的市场。

**Comment by widon1104** [comment]
还有一个问题，我想单独提一下，现在用显卡驱动管理器安装英伟达闭源驱动需要重启电脑3次，我觉得重启次数太多了应该优化一下，最好重启一次，最多2次。

**Comment by justforlxz** [comment]
如果能做到一次就足够，当然可以做到一次就足够，你都知道重启这么多次不好，我们难道会故意做恶心人的功能？

我给你解释一下为什么需要重启这么多次。

最开始我们是直接在系统内安装nvidia驱动的，结果测试了很多次，一些机器就是会卡死，然后系统报废。
为了避免安装驱动导致用户的机器无法使用，我们就引入了overlay，第一次重启进入overlay模拟安装，如果没有问题，就写入硬盘。
但是后来测试发现，就算模拟了一遍，重启以后还是有可能无法使用，因为当时安装的时候能用，不代表重启以后仍然可以正常工作，所以为了确保万无一失，就只能三次重启了。

这些问题并不是说我们不想做，或者我们想不到，但是很多时候都是没办法，要么不提供这个功能，要么只能提供这么复杂的操作，虽然很麻烦，但是它目前看起来很管用。

**Comment by justforlxz** [comment]
不要看到其他系统有的功能，就想要求我们必须也去做同样的，linux毕竟是linux，windows毕竟是windows。

**Comment by meiyixiang** [comment]
当前在安装的时候提供了，闭源驱动安装时勾选问题，并不一定是N卡闭源驱动就比开源驱动稳定。

**Comment by widon1104** [comment]
> 当前在安装的时候提供了，闭源驱动安装时勾选问题，并不一定是N卡闭源驱动就比开源驱动稳定。

这个我不同意你的观点，英伟达闭源驱动绝对比开源驱动好很多，开源驱动导致系统僵死的问题数不胜数，而且Chrome也把开源显卡驱动 Nouveau加入了黑名单，使用开源驱动不能进行webgl加速，所以对于英伟达显卡用户，默认使用闭源驱动要稳很多。

**Comment by meiyixiang** [comment]
主要是现在提供了安装闭源驱动的方式，你是觉得应该是怎样的呢？没有很理解？

**Comment by widon1104** [comment]
闭源驱动安装过程中，有时候会卡死这个问题应该认真分析一下，如果这个问题解决不了，那装系统的时候勾选闭源驱动也可能会安装失败导致问题，那就没有意义了

**Comment by meiyixiang** [comment]
明白你的意思，这个问题其实我觉得是你觉得没有一次装成功影响不好。这个我反馈给研发让他们看看。

**Comment by meiyixiang** [comment]
这个问题我反馈给产品和研发了，谢谢你的建议！

**Comment by justforlxz** [comment]
> 闭源驱动安装过程中，有时候会卡死这个问题应该认真分析一下，如果这个问题解决不了，那装系统的时候勾选闭源驱动也可能会安装失败导致问题，那就没有意义了

问题分析了，原因就是老黄的私有驱动不配合 linux 这边的组件，这个问题不值得再浪费时间讨论。我们做驱动管理器或者提供私有驱动预装是为了帮助用户，而不是我们做烂恶心用户。 **使用开源硬件才能更好的使用开源系统**。 我再次声明一下，nvidia 私有驱动目前就是能用且用的状态，不要抱有任何不切实际的幻想，如果哪天老黄想开了，deepin 也会第一时间跟进。 

至于显卡驱动管理器重启多次，我们可以想办法进行优化，但是卡死或者私有驱动崩溃/工作异常带来的一切问题，我们无能为力。

**Comment by widon1104** [comment]
还有一个问题没有讨论，那就是显卡驱动管理器针对很多老的英伟达显卡没有做适配，现在驱动管理器只适配了一款驱动，能够覆盖的显卡范围有限，系统可以尝试多带几款驱动，这样大大增加显卡覆盖范围。
