### ISSUE TITLE
「缺陷报告」网易云音乐不支持高分屏

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2181]
uos&deepin下面，网易云音乐最新版本（1.2.1-1），不支持高分屏，在高分屏下面字体很小，没法看
这个问题出现很久了，网易云音乐也很久没有更新了，希望尽快改进

**Comment by zccrs** [comment]
https://github.com/linuxdeepin/developer-center/issues/2172 这个任务中会进行处理，可以关注它的后续状态。这个issues就关闭了
