### ISSUE TITLE
[Suggestion] Merge Global search functionality with the Launcher

### ISSUE THREAD

**Issue by raspin0** [linuxdeepin/developer-center#2182]
Recently I’ve set up a windows 11 VM and after trying it for a while I noticed how convenient searching was there. I could easily from one place search for apps, files and system settings. On the contrary to deepin where this functionality is divided. I wish deepin could elevate gnome’s approach with all-in-one search bar

**Comment by meiyixiang** [comment]
Global search is a new feature and we are in the process of updating it. Please give us some time
