### ISSUE TITLE
「缺陷报告」报一个wine qq的问题

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2183]
➜  ~ dpkg -l | grep qq
ii  com.qq.im.deepin:i386                            9.4.9.27849deepin5                  i386         Tencent QQ Client on Deepin Wine6
现在我打开了wine qq以后，打开群，然后双击打开一个群里面群友发的图片，图片放大了，然后我按键盘左上角的Esc键，
以为图片会收回去，但是这时候图片没有收回去，而是对话框收到系统托盘里面去了
我的期望是按Esc，图片收回去，对话框不动
这个bug，让我感觉不爽，所以提出来，希望能够解决

**Comment by babyfengfjx** [comment]
soga ,这个问题我们已经反馈，也希望能尽快提供优化后的版本，感谢反馈~

**Comment by babyfengfjx** [comment]
因当前已经有了linux版本的QQ版本，后续的wine版本也不再做迭代了，此issue我们先关闭处理啦～
