### ISSUE TITLE
AMDGPU not working and cannot adjust screen brightness

### ISSUE THREAD

**Issue by thatindianguy004** [linuxdeepin/developer-center#2186]
I am using 
![Screenshot_20220107213910](https://user-images.githubusercontent.com/97303489/148574078-5d467817-5293-4bd8-ab09-02f8dee65c08.png)
![Screenshot_20220107213935](https://user-images.githubusercontent.com/97303489/148574089-c503ffbf-73e9-41ba-ac7c-cd200315adfa.png)
 and screen when booting up 
![IMG_20220107_213544](https://user-images.githubusercontent.com/97303489/148575594-91d8e534-f2b8-47bd-95cc-b513981bca71.jpg)
i tried to install linux-image-deepin-stable-amd64 linux-headers-deepin-stable-amd64
![IMG_20220107_202857](https://user-images.githubusercontent.com/97303489/148576938-3da5edb0-4c68-4c3b-8d6d-18a51cc42c0b.jpg)
NEED HELP

**Comment by Zeno-sole** [comment]
Are you using the nomodeset parameter, we suggest you try removing it

**Comment by thatindianguy004** [comment]
> Are you using the nomodeset parameter, we suggest you try removing it

Yes but then the device is not even booting up

**Comment by Zeno-sole** [comment]
What error occurs after removing the nomodeset parameter?

**Comment by thatindianguy004** [comment]
Nothing just blank screen

**Comment by thatindianguy004** [comment]
> What error occurs after removing the nomodeset parameter?

Nothing just blank screen

**Comment by Zeno-sole** [comment]
Looks like a driver or firmware issue,

**Comment by Zeno-sole** [comment]
You can try adding parameters to grub    modprobe.blacklist=radeon amdgpu.si_support=1 amdgpu.cik_support=1
