### ISSUE TITLE
「缺陷报告」wine qq crash崩溃问题

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2187]
➜  ~ dpkg -l | grep qq
ii  com.qq.im.deepin:i386                            9.4.9.27849deepin5                  i386         Tencent QQ Client on Deepin Wine6

我随便说2个我遇到过的崩溃的情况，应该不是必现，但是出现的频率也不算低
1）点击界面左小角 加好友/群，偶尔会崩溃
2）点击好友动态一栏，偶尔会崩溃

请多测试解决

**Comment by widon1104** [comment]
3) 这个版本，群系统消息弹出的时候也会crash

**Comment by widon1104** [comment]
4) 今天我点击一个很久没有联系的好友，wine qq又crash了，crash的点感觉非常多

**Comment by widon1104** [comment]
今天升级了wine qq，不停的崩溃，没法用了
➜  ~ dpkg -l | grep qq
ii  com.qq.im.deepin:i386                            9.5.3.28008deepin0                  i386         Tencent QQ Client on Deepin Wine6
第一次打开就僵死了，重启然后打开群助手崩溃了，重启打开群助手里面的qq群看了几条消息以后又崩溃了
几乎就是使用30秒之内就会崩溃

**Comment by widon1104** [comment]
➜  ~ ls ~/.fonts 
Fonts  winefonts.tar.gz
➜  ~ ls ~/.wine/drive_c/windows/Fonts 
Fonts  winefonts.tar.gz
说明一下，我的电脑在~/.fonts和~/.wine/drive_c/windows/Fonts 都有windows拷贝下来的字体

**Comment by babyfengfjx** [comment]
- WINE  QQ 崩溃的问题已经做了紧急处理；
- 不过偶现崩溃的问题可能还是会存在，目前也已经反馈研发团队攻关，感谢老铁的问题反馈~

**Comment by babyfengfjx** [comment]
- QQ频繁崩溃的问题，暂时得到解决，此问题我们先做关闭处理，如有其他场景下导致的问题，感谢及时提交；
