### ISSUE TITLE
dde-dock 4.1.8 shows 12-hour clock without AM/PM

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#219]
There is no option to set the clock back to 24-hour clock, or to show AM/PM in 12-hour clock.

**Comment by hualet** [comment]
Right click on the clock item and select "24-hour clock" in the menu?

**Comment by sbwtw** [comment]
because "xx:xx AM" is too long to display when dock size is setting to small.

**Comment by felixonmars** [comment]
@hualet That works, thanks. It would have been great if old behavior would be preserved between upgrades.
