### ISSUE TITLE
dde-dock client side decoration issue on Telegram system tray icon

### ISSUE THREAD

**Issue by chenzhiwei** [linuxdeepin/developer-center#2190]
When switch the Deepin theme between light and dark mode, the Telegram system tray icon does not switch between light and dark.

## Reproduce Steps

1. Install Flatpak
2. Install Telegram Flatpak package
3. Open Telegram Flatpak package
4. Check the Telegram system tray icon
5. Switch the Deepin theme to light or dard
6. Check the Telegram system tray icon(no change)
7. Quit the Telegram and re-open it, the system tray icon changed according to Deepin theme

![image](https://user-images.githubusercontent.com/672668/149071181-b90e955d-341d-40a2-b802-29f5e0825d3b.png)

**Comment by tsic404** [comment]
Duplicate Tray Icons [issue](https://github.com/linuxdeepin/dde-dock/issues/142) has benn fixed

**Comment by chenzhiwei** [comment]
It is not duplicate tray icon issue, it's the tray icon does not change according to deepin theme.

**Comment by chenzhiwei** [comment]
I open multiple telegram instances is used to show the differences of the tray icon color.

**Comment by tsic404** [comment]
I see. this is our problem.

**Comment by tsic404** [comment]
This [commit](https://github.com/linuxdeepin/dde-dock/commit/3e26f1989c0f335ff15c3033de2d03b5cd0e6394) has fixed this issue.
