### ISSUE TITLE
Feature Request: Add quick view window for datetime plugin

### ISSUE THREAD

**Issue by chenzhiwei** [linuxdeepin/developer-center#2191]
As you may already know, the quick view window of datetime indicator is exist in almost all other Linux Desktop Environments and Windows XP+.

This is a very useful feature, allow users quickly viewing the monthly calendar and events without open the calendar application.

The current behavior of clicking the dateitime indicator is to open the calendar application, which users require an extra step to close the calendar application.

With this quick view window, users don't need an extra step to close the calendar window.

![image](https://user-images.githubusercontent.com/672668/149087586-1f785449-c9c3-4c67-88cf-b84bfa5cbca8.png)

**Comment by meiyixiang** [comment]
Thanks for your suggestion. I have given feedback to the product manager about this function.

**Comment by iamhyc** [comment]
> Thanks for your suggestion. I have given feedback to the product manager about this function.

Please also let us know when you are determined :)
Beck to early Deepin v15 version, it was a very convenient function but got removed in the later refactoring work.

**Comment by meiyixiang** [comment]
We have decided to do it, but we are not sure whether it will be in the first half or the second half because we are developing a new version this year. We will announce new features before the release when the time is set
