### ISSUE TITLE
「缺陷报告」关闭窗口特效以后，wine的程序窗口周围会有黑框

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2194]
![image](https://user-images.githubusercontent.com/12093211/150147623-5e58b9bf-fce4-440f-8576-c45ed43850f5.png)

**Comment by zccrs** [comment]
不是所有的wine程序都这样吧，企业微信是OK的

**Comment by babyfengfjx** [comment]
> ![image](https://user-images.githubusercontent.com/12093211/150147623-5e58b9bf-fce4-440f-8576-c45ed43850f5.png)

感谢反馈，目前确认TIM确实有该问题，我们已经记录该问题，会在后续版本修复~

**Comment by widon1104** [comment]
注意，不止TIM有这个问题，Wine qq等软件也有这个问题，你们最好把常用的wine软件都测试一下，应该是共性问题

**Comment by babyfengfjx** [comment]
> 注意，不止TIM有这个问题，Wine qq等软件也有这个问题，你们最好把常用的wine软件都测试一下，应该是共性问题

![image](https://user-images.githubusercontent.com/24642999/150710924-e866601b-6a65-4d38-b892-193851c26c96.png)
嗯，这些WINE应用都做过验证，目前发现只有TIM比较明显，问题已经提交对应研发做分析了~

**Comment by widon1104** [comment]
洛雪音乐助手也是这样：
![截图_选择区域_20220205145739](https://user-images.githubusercontent.com/12093211/152632224-6b28565e-59e3-472d-803d-d01350ba5412.jpg)

**Comment by babyfengfjx** [comment]
> 洛雪音乐助手也是这样： ![截图_选择区域_20220205145739](https://user-images.githubusercontent.com/12093211/152632224-6b28565e-59e3-472d-803d-d01350ba5412.jpg)

收到，已经提交研发分析~thanks老铁~

**Comment by babyfengfjx** [comment]
后续版本我们将主要处理V23版本问题，wine版本相关的应用后续维护力度会减少，当前issue我们先做关闭处理，后续在V23版本发现的新问题随时可以提交新的issue以便跟进。

**Comment by wineee** [comment]
> 洛雪音乐助手也是这样： ![截图_选择区域_20220205145739](https://user-images.githubusercontent.com/12093211/152632224-6b28565e-59e3-472d-803d-d01350ba5412.jpg)


洛雪音乐助手有 linux 原生的，不要用 wine
