### ISSUE TITLE
Bug report upgrading from deepin 20.3 to deepin 20.4 causes packets to be withheld

### ISSUE THREAD

**Issue by alvarosamudio** [linuxdeepin/developer-center#2195]
![image](https://user-images.githubusercontent.com/25090546/150247864-4f7ea7aa-17c5-45d0-b899-9ce6176c0af0.png)
![image](https://user-images.githubusercontent.com/25090546/150247879-6a509048-8301-4f49-b886-0595666e0af5.png)
deepin-image-viewer still has dependencies on libimage-viewer

upgrading from deepin 20.3 to deepin 20.4 causes packets to be withheld

**Comment by Zeno-sole** [comment]
We are aware of this issue, please pay attention to subsequent updates
