### ISSUE TITLE
Deepin 20.4 update bugs

### ISSUE THREAD

**Issue by ricosandyca** [linuxdeepin/developer-center#2198]
Hi Deepin team,
I just upgraded to Deepin 20.4 from 20.3. But I got some bugs which are:

## `deepin-album` upgrading error
I can't go upgrade `deepin-album` after update. I got an error like this
![image](https://user-images.githubusercontent.com/43330562/150473833-df853bbe-3e07-480e-8ff9-97f6732077ec.png)

## Missing the split screen feature into 4 windows
Previously in Deepin 20.3 I could split my screen into 4 windows, which it's not available anymore in Deepin 20.4. Only splitting into 2 windows allowed in Deepin 20.4.

**Comment by tsic404** [comment]
We have fixed deepin-album in the unstable source. It will shown up stable source in sometime.

**Comment by tsic404** [comment]
split screen feature into 4 windows, could you take some screenshots ?

**Comment by ricosandyca** [comment]
@tsic404 I mean like this. Previously this was available in Deepin 20.3, but i don't find it on Deepin 20.4
![image](https://user-images.githubusercontent.com/43330562/150748334-f414290f-0d14-46b1-a8f3-bcbb6ca9b0f5.png)

**Comment by babyfengfjx** [comment]
> @tsic404 I mean like this. Previously this was available in Deepin 20.3 where if you drag the window to the corner you'll get splitting suggestion into 4 windows, but i don't find it on Deepin 20.4. What can i do currently is manually resizing each windows
> 
> ![image](https://user-images.githubusercontent.com/43330562/150748334-f414290f-0d14-46b1-a8f3-bcbb6ca9b0f5.png)

Thanks you for your feedback. It is confirmed that this issue has been shielded in the current version, and it is planned to be online again after optimization in the subsequent version. Please look forward to it

**Comment by babyfengfjx** [comment]
This feature may increase in subsequent versions，we close  this  issue now , any new questions are welcome to feedback~
