### ISSUE TITLE
archlinux 上控制中心语言列表为空

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/developer-center#22]
目前 archlinux 因为 glibc 默认没有按照该文件导致控制中心语言列表为空，无法切换语言。

通过查看 PKGBUILD，发现 archlinux 上 glibc 直接把 SUPPORTED 文件写入到了 **/etc/locale.gen**

```sh
  # create /etc/locale.gen
  install -m644 ${srcdir}/locale.gen.txt ${pkgdir}/etc/locale.gen
  sed -e '1,3d' -e 's|/| |g' -e 's|\\| |g' -e 's|^|#|g' \
    ${srcdir}/glibc-${pkgver}/localedata/SUPPORTED >> ${pkgdir}/etc/locale.gen
```
https://projects.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/glibc

目前正在想办法修复这个问题，有一个疑问是我们自己有没有更改过 SUPPORTED 文件？
@leaeasy @jouyouyun 

https://github.com/fasheng/arch-deepin/issues/212#issuecomment-171527616

**Comment by fasheng** [comment]
经调试，确定和下面的提交有关，奇怪的是没有看到 SUPPORTED 文件相关的变更
https://github.com/linuxdeepin/dde-daemon/commit/33738a0c3d4ff7dade9895d9bd1130238ef913e8

@jouyouyun

**Comment by leaeasy** [comment]
没有改动过这个文件，在/etc/locale.gen 前面有关于这两个文件的解释

**Comment by leaeasy** [comment]
# This file lists locales that you wish to have built. You can find a list
# of valid supported locales at /usr/share/i18n/SUPPORTED, and you can add
# user defined locales to /usr/local/share/i18n/SUPPORTED. If you change
# this file, you need to rerun locale-gen.

**Comment by jouyouyun** [comment]
以前是直接从 support_languages.json 中获取支持的语言列表的，没有用到 SUPPORTED 这个文件。

现在是 support_languages.json 这个文件会给出所有 locale 及其的描述，从 SUPPORTED 文件中获取到系统当前支持的语言列表。

support_languages.json 文件的功能变了

**Comment by fasheng** [comment]
已经修复，下游等待 **dde-api 3.0.4** 新版本即可，同时 **dde-daemon** 需要 rebuild
https://cr.deepin.io/#/c/10635/
