### ISSUE TITLE
Hot corner hints should not pop up in fullscreen applications

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#220]
Right now it shows the hint but does not actually activate.

![2017-04-01-131756-2db2e1](https://cloud.githubusercontent.com/assets/1006477/24576027/c4361118-16e6-11e7-9abe-e35cda3c60e3.png)

**Comment by funilrys** [comment]
That's why I want to disable this functionality ...#167

**Comment by sonald** [comment]
disable it by `qdbus com.deepin.wm /com/deepin/wm  com.deepin.wm.EnableZoneDetected false` dynamically.
This behaviour is by design, I believe what you want is to be able to disable it for fullscreen games not for fullscreen apps.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
