### ISSUE TITLE
Can't find Telegram icon in launcher after upgrade the Telegram Flatpak

### ISSUE THREAD

**Issue by chenzhiwei** [linuxdeepin/developer-center#2201]
## Reproduce Steps

1. Install Flatpak  (apt install flatpak)
2. Install Telegram through flatpak (flatpak install org.telegram.desktop)
3. Upgrade Telegram through flatpak (flatpak update)
4. Can't find Flatpak in launcher
5. Logout & Login, the Telegram icon appears in launcher

There needs some time between step 2 and 3, you need to wait for next Telegram Flatpak update then you will encounter this issue.

## Expected behavior

The Telegram icon should be appeared in launcher and I can't launch it from launcher.

**Comment by tsic404** [comment]
When you first time install flatpak, flakpak will add a profile in your /etc/profile.d/, so you need to relogin to source this profile. This profile will append flatpak install path to XDG_DATA_DIRS which determines the path where the launcher searches for desktop files.

**Comment by chenzhiwei** [comment]
Yes, I know this well.

The issue is the flatpak exported applications path already in the XDG_DATA_DIRS.

When I upgrade Telegram Flatpak app, I lost the Telegram icon.

But when I upgrade the Firefox flatpak app, the Firefox icon still in launcher.

**Comment by babyfengfjx** [comment]
> Yes, I know this well.
> 
> The issue is the flatpak exported applications path already in the XDG_DATA_DIRS.
> 
> When I upgrade Telegram Flatpak app, I lost the Telegram icon.
> 
> But when I upgrade the Firefox flatpak app, the Firefox icon still in launcher.
Thanks for your feedback, this issue has been submitted for optimization.

**Comment by chenzhiwei** [comment]
@tsic404 @babyfengfjx  A possible reason is that the Telegram flatpak desktop file name is `org.telegram.desktop.desktop`.

> /var/lib/flatpak/exports/share/applications/org.telegram.desktop.desktop

As you can see, there are two `.desktop` at the end of filename, please check the dde-launcher logic after a software is updated.

**Comment by chenzhiwei** [comment]
Reproduced this issue with another flatpak that named `org.kiwix.desktop`.

The desktop file name is `org.kiwix.desktop.desktop`.

> /var/lib/flatpak/exports/share/applications/org.kiwix.desktop.desktop

**Comment by tsic404** [comment]
> @tsic404 @babyfengfjx A possible reason is that the Telegram flatpak desktop file name is `org.telegram.desktop.desktop`.
> 
> > /var/lib/flatpak/exports/share/applications/org.telegram.desktop.desktop
> 
> As you can see, there are two `.desktop` at the end of filename, please check the dde-launcher logic after a software is updated.

This issue has been fixed by this [commit](https://github.com/linuxdeepin/dde-daemon/commit/a1e4d3d3d3b90c71a115d3f452c0d144b1e5f107), waiting for new version released.
