### ISSUE TITLE
「缺陷报告」百度网盘,系统托盘右键经常没反应 

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2205]
百度网盘 for linux 4.3.0有问题，就是百度网盘最小化以后，右键点击右下角系统托盘里面的百度网盘图标没有反应，无法弹出退出网盘的列表界面。
重现步骤可以这样：关闭百度网盘再打开，最小化百度网盘，然后右键点击托盘图标看一下有反应不，这时候多半应该是没有反应的。

**Comment by zccrs** [comment]
deepin上有问题吗？

**Comment by babyfengfjx** [comment]
> 百度网盘 for linux 4.3.0在uos家庭版上面有问题，就是百度网盘最小化以后，右键点击右下角系统托盘里面的百度网盘图标没有反应，无法弹出退出网盘的列表界面。 重现步骤可以这样：在uos家庭版中关闭百度网盘再打开，最小化百度网盘，然后右键点击托盘图标看一下有反应不，这时候多半应该是没有反应的。

- 百度网盘这类WINE应用确实会有这类问题，因此应用非项目组维护迁移，对问题的推进解决会存在一定难度；
- 该问题目前已经提交对应研发进行分析，非常感谢反馈~

**Comment by widon1104** [comment]
> > 百度网盘 for linux 4.3.0在uos家庭版上面有问题，就是百度网盘最小化以后，右键点击右下角系统托盘里面的百度网盘图标没有反应，无法弹出退出网盘的列表界面。 重现步骤可以这样：在uos家庭版中关闭百度网盘再打开，最小化百度网盘，然后右键点击托盘图标看一下有反应不，这时候多半应该是没有反应的。
> 
> * 百度网盘这类WINE应用确实会有这类问题，因此应用非项目组维护迁移，对问题的推进解决会存在一定难度；
> * 该问题目前已经提交对应研发进行分析，非常感谢反馈~

都说了是百度网盘 for linux了，是原生软件，不是wine的

**Comment by babyfengfjx** [comment]
> > > 百度网盘 for linux 4.3.0在uos家庭版上面有问题，就是百度网盘最小化以后，右键点击右下角系统托盘里面的百度网盘图标没有反应，无法弹出退出网盘的列表界面。 重现步骤可以这样：在uos家庭版中关闭百度网盘再打开，最小化百度网盘，然后右键点击托盘图标看一下有反应不，这时候多半应该是没有反应的。
> > 
> > 
> > 
> > * 百度网盘这类WINE应用确实会有这类问题，因此应用非项目组维护迁移，对问题的推进解决会存在一定难度；
> > * 该问题目前已经提交对应研发进行分析，非常感谢反馈~
> 
> 都说了是百度网盘 for linux了，是原生软件，不是wine的

确认Linux版本的百度网盘在deepin也有这类问题，之前有发现部分WINE应用也存在这类问题，问题已经提交反馈，待研发分析优化~

**Comment by tsic404** [comment]
> 百度网盘 for linux 4.3.0有问题，就是百度网盘最小化以后，右键点击右下角系统托盘里面的百度网盘图标没有反应，无法弹出退出网盘的列表界面。 重现步骤可以这样：关闭百度网盘再打开，最小化百度网盘，然后右键点击托盘图标看一下有反应不，这时候多半应该是没有反应的。

这个是百度网盘注册的dbus调用有问题，他把更新托盘菜单写在了左键事件里面，你每次打开百度网盘，需要用左键点击托盘，后面右键的菜单都可以显示，在其他DE上比如KDE也是一样的现象。

**Comment by tsic404** [comment]
> > 百度网盘 for linux 4.3.0有问题，就是百度网盘最小化以后，右键点击右下角系统托盘里面的百度网盘图标没有反应，无法弹出退出网盘的列表界面。 重现步骤可以这样：关闭百度网盘再打开，最小化百度网盘，然后右键点击托盘图标看一下有反应不，这时候多半应该是没有反应的。
> 
> 这个是百度网盘注册的dbus调用有问题，他把更新托盘菜单写在了左键事件里面，你每次打开百度网盘，需要用左键点击托盘，后面右键的菜单都可以显示，在其他DE上比如KDE也是一样的现象。

也就是首次启动后，不左键点击托盘，托盘右键菜单是一直不显示的，只有左键点击托盘后，托盘右键菜单就显示正常。

**Comment by widon1104** [comment]
uos下面体验不好，但是使用频繁的一个软件就是QQ，windows下在系统托盘，只需要左键点击一下qq图标，面板马上就显示，可是在uos下面，必须要双击，而且有时候双击面板都不显示。有一个快捷键是ctrl+alt+z可以显示qq面板，但是在uos下面，必须要左键点击一下系统托盘的qq图标，然后按快捷键qq面板才显示，感觉体验不好。

我觉得wine qq的这个问题，是否和百度网盘这个问题有点类似？？？

**Comment by tsic404** [comment]
> 

俩走的机制不一样，不是一个问题。

**Comment by tsic404** [comment]
> > > 百度网盘 for linux 4.3.0有问题，就是百度网盘最小化以后，右键点击右下角系统托盘里面的百度网盘图标没有反应，无法弹出退出网盘的列表界面。 重现步骤可以这样：关闭百度网盘再打开，最小化百度网盘，然后右键点击托盘图标看一下有反应不，这时候多半应该是没有反应的。
> > 
> > 
> > 这个是百度网盘注册的dbus调用有问题，他把更新托盘菜单写在了左键事件里面，你每次打开百度网盘，需要用左键点击托盘，后面右键的菜单都可以显示，在其他DE上比如KDE也是一样的现象。
> 
> 也就是首次启动后，不左键点击托盘，托盘右键菜单是一直不显示的，只有左键点击托盘后，托盘右键菜单就显示正常。

你可以验证一下百度网盘是不是这样的情况，是的话这个就是百度网盘自身问题导致的。

**Comment by babyfengfjx** [comment]
@vivianxf   此问题记得是已经解决的，请在V20和V23分别确认一下该类应用的表现，将相关应用的情况都覆盖一下，如确认已经修复请及时关闭issue，如果没有解决请推进研发处理修复。

**Comment by vivianxf** [comment]
- v20下面目前可以实现右键应用快捷面板打开百度网盘，v23下面在插件面板中右键应用快捷面板打开百度网盘
- v23下从插件面板直接拖动到任务栏，右键无法打开快捷面板，这个会单独跟踪处理
