### ISSUE TITLE
Deepin version of bcmwl-kernel-source does not work with Broadcom BCM4360 Wi-Fi, but Ubuntu version works

### ISSUE THREAD

**Issue by mikebeaton** [linuxdeepin/developer-center#2206]
I have the latest upgrade of Deepin 20.04, running on a MacBookPro10,2. I have a Broadcom BCM4360, which is a standard MacPro Wi-Fi card.

The version of `bcmwl-kernel-source` which is installed with this version of Deepin by default `6.30.223.272+bdcom-deepin` does not work: Wi-Fi appears to be present, but no Wi-Fi networks are shown.

The version of the package available from https://packages.ubuntu.com/focal/amd64/bcmwl-kernel-source/download `6.30.223.271+bdcom-0ubuntu7~20.04.3` (which I found and installed following these instructions https://askubuntu.com/questions/55868/installing-broadcom-wireless-drivers) works correctly.

**Comment by kt286** [comment]
you can try uninstall it on system and install from buster-backports
```
sudo apt autopurge bcmwl-kernel-source broadcom-sta-*
wget http://ftp.cn.debian.org/debian/pool/non-free/b/broadcom-sta/broadcom-sta-dkms_6.30.223.271-17~bpo10+1_all.deb
sudo apt install ./broadcom-sta-dkms_6.30.223.271-17~bpo10+1_all.deb
```

**Comment by Zeno-sole** [comment]
Thanks for your feedback, we will update this driver in subsequent versions

**Comment by Zeno-sole** [comment]
The bcmwl driver has been updated

**Comment by mikebeaton** [comment]
I have run automatic upgrade to `6.30.223.273+bdcom amd64` from `community-packages.deepin.com` and it is working fine. Tyvm.
