### ISSUE TITLE
[BUG?] There is no delay with maximize options on external apps

### ISSUE THREAD

**Issue by raspin0** [linuxdeepin/developer-center#2207]
Video: 

https://user-images.githubusercontent.com/39202451/150690923-1eea88b4-4599-4ace-95e2-567e21870fb2.mp4

**Comment by meiyixiang** [comment]
We use the DTK framework. Third party applications do not use our development framework.

**Comment by raspin0** [comment]
> We use the DTK framework. Third party applications do not use our development framework.

Is it possible to replicate DTK delay on third party applications?
