### ISSUE TITLE
使用一个快捷键后黑屏无法恢复，但感觉运行是正常的。 「缺陷报告」

### ISSUE THREAD

**Issue by zfk999** [linuxdeepin/developer-center#2208]
老工作站装的20.1，使用一切正常。

用的是ACER配的键盘，右边有一列热键（如图），下面几个功能都正常，

手贱按了最上面的一个键，

黑屏了！！！黑屏了！！！黑屏了！！！

而且黑得很彻底，屏上什么东西都没有！！！就跟显示器坏了一样！

然后再也回不来了，但感觉系统运行是正常的。

重启开机后登录前一切正常，登录后就黑屏。

哪位知道什么原因？或者这个热键对应哪个组合键？还能治治吗？

![image](https://user-images.githubusercontent.com/10095765/161200642-94730b2e-ea90-44f7-9ea8-fba6f280d73e.png)

**Comment by kt286** [comment]
这个键好像是投屏键，你再按几次试试

**Comment by justforlxz** [comment]
在tty登录一下，然后看看 ~/.config/deepin/startdde/display.json 也有可能叫 display_v5.json，cat一下内容。

**Comment by zccrs** [comment]
没见过这种按钮，按之前执行下 xev &> ~/xev.log，然后再按（黑屏后不要再按其它按键了，可以先把鼠标放到终端的位置，黑屏后点击下终端再按 Ctrl+C 停止 xev 程序），之后把家目录的 xev.log 文件提取出来看下。

**Comment by BLumia** [comment]
很久没得到进一步答复，就先关掉了。如果您这边仍然有类似问题的话，可以开个新的 issue 来汇报，别忘了按照上面回复里描述的步骤提供下相应的日志内容以便我们进一步确认问题。感谢！
