### ISSUE TITLE
[Translation]  (too) Long translation

### ISSUE THREAD

**Issue by funilrys** [linuxdeepin/developer-center#221]
We may need to do something in the following case :smile_cat: 

It's possible to translate it in shorter sentence but it's already great :stuck_out_tongue_closed_eyes: 

![deepinbildschirmfoto20170401115657](https://cloud.githubusercontent.com/assets/14127285/24577691/e6f5473c-16d2-11e7-9eaa-f1f6b5026515.png)

**Comment by hualet** [comment]
Can you submit a better version on [transifex](https://transifex.com)? or maybe you can refer to liufei@deepin.com, the one in charge of i18n stuff of deepin, for some help?

**Comment by funilrys** [comment]
I was added to transifex but for french (Second motherlanguage) 

This issue is about german (I speak also this language) so it'll be great to be added in German team too ...

![deepinscreenshot20170401182603](https://cloud.githubusercontent.com/assets/14127285/24580462/b0b9bc30-1708-11e7-9b32-385a9691be03.png)

**Comment by funilrys** [comment]
If you can't I'm gonna contact him between two line of code :wink:

**Comment by hualet** [comment]
Yeah, you need to contact HER. 😂

**Comment by funilrys** [comment]
Oops my bad sorry to HER if she read the following :laughing:

**Comment by hualet** [comment]
Any luck? @funilrys

**Comment by funilrys** [comment]
Had too much to do !!

This morning I have time to change the translation! @hualet

**Comment by maggielf** [comment]
Hi funilrys, I' Maggie,  in charge of i18n. Welcome to help us improve translations in transifex, and I just added you in German as the revirewer, then you can correct the wrong ones.
