### ISSUE TITLE
Network card problems model: MPE-AX3000H 

### ISSUE THREAD

**Issue by alvarosamudio** [linuxdeepin/developer-center#2216]
system does not recognize the network card correctly, this makes it unusable, possible driver problems
![image](https://user-images.githubusercontent.com/25090546/151256180-d00aff53-33f3-43d1-99e7-d03628b15843.png)
the network card runs on debian and uses the same iwlwifi drivers as the AX210/AX211/AX411 cards.

**Comment by Zeno-sole** [comment]
What kernel version are you using?

**Comment by alvarosamudio** [comment]
> ¿Qué versión del kernel estás usando?
5.10.83

**Comment by Zeno-sole** [comment]
Can you upgrade the kernel version to 5.15.6? See if this version of the kernel driver is normal

**Comment by alvarosamudio** [comment]
> Can you upgrade the kernel version to 5.15.6? See if this version of the kernel driver is normal

thank you I have already changed the kernel and everything works properly
