### ISSUE TITLE
「缺陷报告」网易云音乐系统托盘右键菜单宽度占满全屏

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2217]
➜  ~ dpkg -l | grep com.163
ii  com.163.music                                    1.2.1-1                             amd64        Netease cloud music player.
![微信图片_20220202110651](https://user-images.githubusercontent.com/12093211/152087143-b72add12-ca2f-41eb-9e3b-97b3cf5fff0c.jpg)

看图可以看出，网易云音乐系统托盘右键，就变成这样了，，
系统uos家庭版，还是必现的

**Comment by widon1104** [comment]
奇怪的是，电脑没有重启，只是锁定过，突然又好了

**Comment by zccrs** [comment]
这类问题应该和系统环境无关，如果重现频率比较高，可以在其它系统环境上试一下同一个版本的网易云。另外可以把问题报到网易那边，这个issue在这放着也无法处理，做关闭处理了。
