### ISSUE TITLE
Deepin Store Search Wrong Receive HTTP 500 code

### ISSUE THREAD

**Issue by massimodellarovere** [linuxdeepin/developer-center#2218]
I search package in Deepin Store not result. Deepin 20.4

![image](https://user-images.githubusercontent.com/5731295/152452969-c8df4aab-0af0-49ae-93ea-ae91fffe2126.png)
![image](https://user-images.githubusercontent.com/5731295/152453051-22c8f9a6-0779-4fe4-bc91-e26b8a34e4f8.png)
![image](https://user-images.githubusercontent.com/5731295/152453101-a4673f50-3015-4a53-bb25-6138d03be5ae.png)
![image](https://user-images.githubusercontent.com/5731295/152453147-0bfa4acb-e447-45ac-8be4-48de43539311.png)

**Comment by babyfengfjx** [comment]
Thanks  for your feedback. We have recently been observed, have not yet reset this problem, don't know if the problem still exists?

**Comment by babyfengfjx** [comment]
> Yes I have problem now. I have deepin last update ... I read same problem in the web for another persons....

What system language do you use?Perhaps it has a certain relationship with this.

**Comment by massimodellarovere** [comment]
> > Yes I have problem now. I have deepin last update ... I read same problem in the web for another persons....
> 
> What system language do you use?Perhaps it has a certain relationship with this.

Spanish

**Comment by babyfengfjx** [comment]
Thank you very much for your feedback. When I switch into Spanish, I really reverted this problem. We will submit a repair as soon as possible. You can use English as a system language to search for the software you need, i feel very sorry to bring you inconvenience.

**Comment by vivianxf** [comment]
Thank you very much for your feedback.We've already fixed this issue,maybe you can try it again.

**Comment by babyfengfjx** [comment]
Since we have not been in touch for a long time, we will close the issue first. If there is any problem later, you can submit the issue in time. Thank you for your feedback.
