### ISSUE TITLE
「缺陷报告」文件管理器列表模式下，最后一个文件有大概率无法点击选中，无法拖动

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2219]
![image](https://user-images.githubusercontent.com/12093211/152632256-1281c7bb-56ec-4079-b6ff-a48ac4e506da.png)

➜  ~ dpkg -l | grep file-man
ii  dde-file-manager                                 5.2.0099.24-1                       amd64        File manager front end
ii  libdde-file-manager:amd64                        5.2.0099.24-1                       amd64        DDE File Manager library

如图，列表模式下，最后一个文件（截图_选择区域_20220205145739）有大概率无法点击选中，无法拖动

**Comment by babyfengfjx** [comment]
> ![image](https://user-images.githubusercontent.com/12093211/152632256-1281c7bb-56ec-4079-b6ff-a48ac4e506da.png)
> 
> ➜ ~ dpkg -l | grep file-man ii dde-file-manager 5.2.0099.24-1 amd64 File manager front end ii libdde-file-manager:amd64 5.2.0099.24-1 amd64 DDE File Manager library
> 
> 如图，列表模式下，最后一个文件（截图_选择区域_20220205145739）有大概率无法点击选中，无法拖动

![image](https://user-images.githubusercontent.com/24642999/153982149-bbbcf93a-b969-4561-968b-db534aee1287.png)
- 看升级到最新版本是否有这个现象？
- 目前使用的新版本文管暂未发现有这个现象；
- 不过，我们仍旧会关注这个点，如果有这类情况我们会及时提交反馈修复；
- 非常感谢您的反馈，希望能接收到您的更多信息哦~

**Comment by widon1104** [comment]
![图片](https://user-images.githubusercontent.com/12093211/154635401-251358eb-e2e5-4d0e-8068-38475ed1dedb.png)
你们可否在uos家庭版上面测试一下

**Comment by babyfengfjx** [comment]
家庭版上也可以正常操作，不知道是否是硬件差异：
![录屏_dde-desktop_20220218162527](https://user-images.githubusercontent.com/24642999/154646177-bd05cdaa-0eb8-46ad-af5a-da2dbdc3874a.gif)

**Comment by disburden** [comment]
这个列表模式还有一个非常无语的问题,就是列表满窗口的情况下没办法新建文件夹
只能非常无奈的切换成图标模式,才能在空白的地方通过鼠标右键来新建文件:(
强烈建议像macOS中finder那样,在顶部标题栏上的菜单中增加一个"新建文件夹"的菜单

**Comment by widon1104** [comment]
> 这个列表模式还有一个非常无语的问题,就是列表满窗口的情况下没办法新建文件夹 只能非常无奈的切换成图标模式,才能在空白的地方通过鼠标右键来新建文件:( 强烈建议像macOS中finder那样,在顶部标题栏上的菜单中增加一个"新建文件夹"的菜单

列表模式满窗口不能新建文件夹的问题早就解决了啊，你的电脑是不是几年没有更新？

**Comment by widon1104** [comment]
这个bug看起来不是必现的，是在特殊情况下出现的，现在我也不能复现这个问题了

**Comment by babyfengfjx** [comment]
> 这个bug看起来不是必现的，是在特殊情况下出现的，现在我也不能复现这个问题了

- 嗯嗯，不过这个现象我们已经做了记录，后续也会持续关注的，感谢老铁的反馈，后续有其他问题也请及时保持沟通~
- 此issue 我们先做关闭处理，如果后续有必现的条件或者新的问题，还辛苦重新提交issue，以便我们能保持紧密的沟通哦~
