### ISSUE TITLE
「缺陷报告」应用预览窗口bug和建议

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2220]
窗口特效打开以后，光标挪到任务栏上面已经打开的app图标上面会有预览窗口出来，如下图：
![截图_20220205202501](https://user-images.githubusercontent.com/12093211/152642121-d445d1f5-dea2-4f59-a796-213c0c68bd6a.jpg)

就针对上面这个图，我有一个bug和一个建议要提
bug是：
光标挪到预览窗口中间以后会显示app的名字，我这个app的名字应该是bc，但是显示是oc
建议是：
现在需要将光标挪到预览窗口中间才会显示app的名字，如果这个app开了很多实例无法快速区分，所以希望把光标挪到app图标上面，预览窗口显示的一瞬间同时把app名字都显示出来，这样一眼就能通过app名字看到自己想选择的实例

我用的系统是uos家庭版（21.1.1），uos论坛冷清，所以在这里面提这个问题

**Comment by meiyixiang** [comment]
你好你反馈的问题已经转给家庭版的产品负责人，他们针对你提出的问题进行解决。

**Comment by wangchunfidel** [comment]
请问一下，其他应用的名称会有被截掉的现象吗？你在家庭版的社群里面吗？

**Comment by widon1104** [comment]
> 请问一下，其他应用的名称会有被截掉的现象吗？你在家庭版的社群里面吗？

1）其他应用名称有没有被截掉需要你们自己测试啊
2）我没有加家庭版的群，只是偶尔在uos论坛发帖

**Comment by meiyixiang** [comment]
可以留下联系方式和家庭版的同学联系。

**Comment by babyfengfjx** [comment]
> > 请问一下，其他应用的名称会有被截掉的现象吗？你在家庭版的社群里面吗？
> 
> 1）其他应用名称有没有被截掉需要你们自己测试啊 2）我没有加家庭版的群，只是偶尔在uos论坛发帖

- 目前针对V20.3，V20.4两个版本进行验证，均未发现有APP的名称展示被截断的现象，覆盖了中英文APP状态下的预览展示，后续我们也会持续关注这个现象点；
- 非常感谢对问题的反馈，可以给我们提供更多的思路和建议~

**Comment by widon1104** [comment]
1)  我用的是uos家庭版
2）这个issue还有一个建议：现在需要将光标挪到预览窗口中间才会显示app的名字，如果这个app开了很多实例无法快速区分，所以希望把光标挪到app图标上面，预览窗口显示的一瞬间同时把app名字都显示出来，这样一眼就能通过app名字看到自己想选择的实例

**Comment by babyfengfjx** [comment]
> 1. 我用的是uos家庭版
>    2）这个issue还有一个建议：现在需要将光标挪到预览窗口中间才会显示app的名字，如果这个app开了很多实例无法快速区分，所以希望把光标挪到app图标上面，预览窗口显示的一瞬间同时把app名字都显示出来，这样一眼就能通过app名字看到自己想选择的实例

嗯，这个地方产品经理已经反馈到家庭版同学了，如果被采纳后面可能会纳入。
