### ISSUE TITLE
deepin-session-shell is not loading on Arch Linux

### ISSUE THREAD

**Issue by carlosal1015** [linuxdeepin/developer-center#2222]
## Issue: deepin-session is not loading on Arch Linux

Hello, after updating the system (`$ sudo pacman -Syyu --noconfirm`), restart the computer, `deepin-session-shell` got stuck (graphic side where user put the password for log in, is not loading).

Work-around:

[Downgrade](https://github.com/linuxdeepin/developer-center/issues/1967#issuecomment-729453580) the packages involved
- [deepin-session-shell-5.4.112-1](https://archlinux.org/packages/community/x86_64/deepin-session-shell)

to

```
local/deepin-session-shell 5.4.58-2 (deepin)
    Deepin desktop-environment - session-shell module
```
and now with this previous versions of `deepin-session-shell`, the user can log in as well.
Optionally,
```
# Pacman won't upgrade packages listed in IgnorePkg and members of IgnoreGroup
IgnorePkg = deepin-session-shell
```

**Comment by justforlxz** [comment]
deepin-session is still under development, if you want to use it, you need to modify the configuration file.

https://github.com/linuxdeepin/dde-session Please read the readme of the project.

**Comment by justforlxz** [comment]
I'm building a new version of dde so I can check out what's wrong.

**Comment by carlosal1015** [comment]
Thank you very much, I really appreciate it very much. I'm not sure if the home directory has some leftovers that could change deepin's environment variables. I am planning to reinstall Arch Linux next month with the deepin desktop environment and try it again.

**Comment by carlosal1015** [comment]
Hi, today I updated to the latest version of [deepin-session-shell](https://archlinux.org/packages/community/x86_64/deepin-session-shell/) 5.5.24-1 from Arch Linux packages and the issue vanished. I noticed that I had a previous file `/etc/lightdm/deepin/qt-theme.ini`, renamed this `/etc/lightdm/deepin/qt-theme.ini.bak` and I updated the system. Thank you.

```diff
diff /etc/lightdm/deepin/qt-theme.ini /etc/lightdm/deepin/qt-theme.ini.bak 
2,3c2
< IconThemeName=deepin
< ScreenScaleFactors=1.50
---
> ScreenScaleFactors=1.25
4a4,9
> IconThemeName=bloom-dark
> FontSize=9.8
> Font=SF Pro Display
> MonFont=Noto Mono
> MonoFont=Consolas
> 
```
