### ISSUE TITLE
「意见建议」deepin&UOS商店评论建议

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2224]
1）现在必须安装软件才可以评论，我觉得这个不合理，我看到评论里面有人提出问题，我知道怎么解决，想告诉他，但是我并不想安装这款软件
2）现在评论不允许回复，希望评论能够回复，回复可以帮助用户解决问题

**Comment by meiyixiang** [comment]
谢谢你的意见，你的建议我将反馈给产品经理

**Comment by meiyixiang** [comment]
第一个我们可能不会做，但第二个有规划
