### ISSUE TITLE
「缺陷报告」显卡驱动管理器安装闭源驱动失败

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2229]
处理器 : Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz (四核 / 四逻辑处理器)
主板 : 0NC2VH
内存 : 16GB(JHD2666U1916JG DDR4 2666MHz (0.4ns))
显示适配器 : GF108GL [Quadro 600]/8th Gen Core Processor Gaussian Mixture Model
音频适配器 : Cannon Lake PCH cAVS/GF108 High Definition Audio Controller
存储设备 : Samsung SSD 850 (500 GB)
网络适配器 : Ethernet Connection (7) I219-LM/Ethernet interface
鼠标 : PixArt Dell MS116 USB Optical Mouse (Dell MS116 USB Optical Mouse)
键盘 : Dell KB216 Wired Keyboard (Dell KB216 Wired Keyboard)
显示设备 : DELL P2421DC(23.8 英寸 (527x296 mm))

我这款显卡，在英伟达官网查看支持的驱动最新版是390.x，如下图：
![图片](https://user-images.githubusercontent.com/12093211/154193329-b896965d-d4d1-4778-a0a2-04a75f7e236e.png)
从图中可以看到，这款驱动的发布时间是2021.12.16日，那说明很有可能这款驱动是适配了新的内核的，
但是为什么显卡驱动管理器只带一款驱动（460.x）,而不带这款390.x驱动，导致我安装闭源驱动失败
我实在是不想自己手动安装英伟达闭源驱动，因为是公司的电脑怕把电脑搞挂了影响工作

**Comment by Zeno-sole** [comment]
麻烦手动安装一下 nvidia-legacy-390xx-driver的驱动包看下
sudo apt install nvidia-legacy-390xx-driver

**Comment by Zeno-sole** [comment]
@babyfengfjx  显卡驱动管理器默认只显示最新版本驱动 应该是设计有问题，看下这个问题，转给对应项目组

**Comment by widon1104** [comment]
> 麻烦手动安装一下 nvidia-legacy-390xx-driver的驱动包看下 sudo apt install nvidia-legacy-390xx-driver

安装成功了，但是发现了诸多问题，我又从新开了一个issue
https://github.com/linuxdeepin/developer-center/issues/2231

**Comment by Zeno-sole** [comment]
这个issues先关闭了
