### ISSUE TITLE
「缺陷报告」命令行安装英伟达闭源驱动的诸多问题

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2231]
➜  ~ nvidia-detect
Detected NVIDIA GPUs:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GF108GL [Quadro 600] [10de:0df8] (rev a1)

Checking card:  NVIDIA Corporation GF108GL [Quadro 600] (rev a1)
Your card is only supported up to the 390 legacy drivers series.
It is recommended to install the
    nvidia-legacy-390xx-driver
package.
nvidia-detect的结果是说我需要安装nvidia-legacy-390xx-driver这个driver，我安装了以后重启，确实切换到了闭源驱动了，
但是问题来了，主要发现了2个问题
1）我现在使用的内核是5.10.x内核，但是由于工作原因我需要使用5.4.x内核，我的电脑已经装了5.10.x和5.4.x 2个内核，现在我在命令行remove了5.10.x内核以后重启（我为什么要remove5.10呢，请看：https://bbs.chinauos.com/zh/post/11216），发现又开始使用开源驱动nouveau了，是因为390 driver不能和5.4.x内核匹配吗？我在命令行remove 干净390驱动以后再安装390驱动，重启，发现又开始使用闭源驱动了，这个显然太麻烦了
2）我现在想安装nvidia-smi来监控一些driver的使用情况，但是最后发现nvidia-smi这个软件居然依赖460.x的驱动，这太死了，460.x的驱动不支持我的显卡啊，这就是说我不能使用nvidia-smi的功能了

**Comment by Zeno-sole** [comment]
你需要安装nvidia-legacy-390xx-smi这个版本的smi才行

**Comment by Zeno-sole** [comment]
remove5.10的原因是启动界面无法选择内核启动么？

**Comment by widon1104** [comment]
> 你需要安装nvidia-legacy-390xx-smi这个版本的smi才行

我安装的是nvidia-legacy-390xx-driver，就出现了我说的2个问题，现在使用状况良好，nvidia-legacy-390xx-smi和nvidia-legacy-390xx-driver有什么区别？

**Comment by widon1104** [comment]
> remove5.10的原因是启动界面无法选择内核启动么？

我remove5.10的原因是我无法便利的切换内核，只有remove掉自己不需要的内核，我感觉不能选择自己想使用的内核版本启动系统是uos把这个功能阉割了，这样导致了不便。

**Comment by Zeno-sole** [comment]
> > 你需要安装nvidia-legacy-390xx-smi这个版本的smi才行
> 
> 我安装的是nvidia-legacy-390xx-driver，就出现了我说的2个问题，现在使用状况良好，nvidia-legacy-390xx-smi和nvidia-legacy-390xx-driver有什么区别？

nvidia-legacy-390xx-driver只是安装了390驱动，安装nvidia-legacy-390xx-smi才能用nvidia-smi的功能

**Comment by widon1104** [comment]
> > > 你需要安装nvidia-legacy-390xx-smi这个版本的smi才行
> > 
> > 
> > 我安装的是nvidia-legacy-390xx-driver，就出现了我说的2个问题，现在使用状况良好，nvidia-legacy-390xx-smi和nvidia-legacy-390xx-driver有什么区别？
> 
> nvidia-legacy-390xx-driver只是安装了390驱动，安装nvidia-legacy-390xx-smi才能用nvidia-smi的功能

这也太坑了吧，谁知道nvidia-legacy-390xx-smi才能用nvidia-smi的功能呢？所以我觉得还是要发展显卡驱动管理器，让管理器替用户选择合适的驱动，不要让用户来选择。

**Comment by Zeno-sole** [comment]
> > remove5.10的原因是启动界面无法选择内核启动么？
> 
> 我remove5.10的原因是我无法便利的切换内核，只有remove掉自己不需要的内核，我感觉不能选择自己想使用的内核版本启动系统是uos把这个功能阉割了，这样导致了不便。

grub界面的高级选项应该是可以切的，家庭版那边的grub也不太清楚是不是去掉了这个功能，我问一下他们团队开发

**Comment by widon1104** [comment]
> > > > remove5.10的原因是启动界面无法选择内核启动么？
> > > 
> > > 
> > > 我remove5.10的原因是我无法便利的切换内核，只有remove掉自己不需要的内核，我感觉不能选择自己想使用的内核版本启动系统是uos把这个功能阉割了，这样导致了不便。
> > 
> > 
> > grub界面的高级选项应该是可以切的，家庭版那边的grub也不太清楚是不是去掉了这个功能，我问一下他们团队开发
> 
> 确认了，家庭版的grub去掉了多内核切换的功能

那么重要的功能，能够随便去掉吗？uos那边人是怎么想的？

**Comment by yxsos** [comment]
正在拉通家庭版沟通。

**Comment by yxsos** [comment]
涉及到商业版-家庭版问题，已拉通内部对应负责人同用户沟通，闭环处理.
