### ISSUE TITLE
Bug report 「缺陷报告」deepin-boot-maker build failed on archlinux

### ISSUE THREAD

**Issue by justforlxz** [linuxdeepin/developer-center#2235]
```/usr/bin/rcc -name translate ../translate.qrc -pass 2 -temp ./qrc_translate.tmp.o -o qrc_translate.o
No data signature found
make[2]: *** [Makefile:620: qrc_translate.o] Error 1
```

**Comment by hillwoodroc** [comment]
You can refer here: https://github.com/linuxdeepin/deepin-reader/issues/23
The same issue on deepin-reader. workaround this issue by disabling LTO.

**Comment by wineee** [comment]
This bug cannot be reproduced

**Comment by justforlxz** [comment]
Does this problem still exist?

**Comment by justforlxz** [comment]
有一个一样的，这个就先关闭了。 https://github.com/linuxdeepin/developer-center/issues/2567
