### ISSUE TITLE
Bug report 「缺陷报告」deepin-image-viewer build failed on archlinux

### ISSUE THREAD

**Issue by justforlxz** [linuxdeepin/developer-center#2237]
```
src/module/view/homepagewidget.cpp:1:10: fatal error: ../libimageviewer/image-viewer_global.h: No such file or directory
    1 | #include "../libimageviewer/image-viewer_global.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by hillwoodroc** [comment]
Confirmed this issue on openSUSE.

**Comment by justforlxz** [comment]
cc @hillwoodroc @felixonmars https://github.com/linuxdeepin/image-editor

**Comment by wineee** [comment]
打包 [image-editor](https://github.com/linuxdeepin/image-editor) 后记得把
`#include "../libimageviewer/image-viewer_global.h"` 换成  `#include "libimageviewer/image-viewer_global.h"`
