### ISSUE TITLE
Blur effect covers only half of tooltip

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#224]
This happens only with today's new tags (dtk, dde-dock, and many others updated):

![2017-04-01-215140-e93cc0](https://cloud.githubusercontent.com/assets/1006477/24579325/92f4a3aa-1725-11e7-9b16-4d11ccede780.png)
![2017-04-01-215155-89b32c](https://cloud.githubusercontent.com/assets/1006477/24579327/96af63ea-1725-11e7-9c9d-20dadf678e55.png)

**Comment by funilrys** [comment]
Same here I was about to signal it :smile_cat:

**Comment by gustavodlima** [comment]
Same here! By mistake, i've created a duplicated issue, but uploaded a footage that shows the isue better. Footage here #227.

**Comment by funilrys** [comment]
@gustavodlima @felixonmars After update it's now solved :)
