### ISSUE TITLE
deepin20.4社区版，显示--屏幕缩放，此功能无法调节

### ISSUE THREAD

**Issue by xiaokentrl** [linuxdeepin/developer-center#2240]
deepin20.4社区版，显示--屏幕缩放，此功能无法调节。
安装的时候把DP线和DHMI线都插上了(自我失误)，在DP模式下字体偏大，
看的眼睛累，希望能再下个版本修复此功能。

**Comment by zccrs** [comment]
无法调节是指啥呀，调了不生效吗，还是给出的调节范围不满足？

**Comment by xiaokentrl** [comment]
> 无法调节是指啥呀，调了不生效吗，还是给出的调节范围不满足？

这个游标拖不动，死的，不能动
![image](https://user-images.githubusercontent.com/97455744/154879476-e84074fb-346d-4aa4-8a5f-e3dee03206ea.png)

**Comment by justforlxz** [comment]
我无法重现这个问题。

**Comment by BLumia** [comment]
😂 我这边也无法复现这个问题。

现在我们已经更新到 v20.6 了，你可以考虑更新下试试看。因为确实无法复现且没有进一步答复，这个 issue 就先关掉了。如果你在 v20.6 仍然能复现这个问题的话，可以开个新 issue 然后我们在新的 issue 里跟进问题。

感谢反馈！
