### ISSUE TITLE
应用商店弄一个板块，用于开发者发布收费软件，促进爱好者开发。  售价低一点，每个应用显示下载总数量。  鉴于爱好，会有一些开发者 开发相关应用，  特别是行业软件，付费也是可以的，毕竟Mac还是有很多人不能满足双系统游戏的。  至于应用商店以外下载的，提示不保障软件安全就行了。    关于第三方软件维护升级的问题，可以收取开发者押金，要求承诺长期维护软件。否则不退押金。签约退出需要满一年才能退押金。

### ISSUE THREAD

**Issue by xiaokentrl** [linuxdeepin/developer-center#2243]
应用商店弄一个板块，用于开发者发布收费软件，促进爱好者开发。

售价低一点，每个应用显示下载总数量。

鉴于爱好，会有一些开发者 开发相关应用，

特别是行业软件，付费也是可以的，毕竟Mac还是有很多人不能满足双系统游戏的。

至于应用商店以外下载的，提示不保障软件安全就行了。

关于第三方软件维护升级的问题，可以收取开发者押金，要求承诺长期维护软件。否则不退押金。签约退出需要满一年才能退押金。

**Comment by justforlxz** [comment]
应用商店已经考虑付费应用的方案了。
