### ISSUE TITLE
[Arch Linux] Sound indicator doesn't work after new updates

### ISSUE THREAD

**Issue by gustavodlima** [linuxdeepin/developer-center#225]
Description
-------------
I'm experiencing multiple new issues after the new updates. One of them is this one with the sound indicator in Dock. It's showing that volume is adjusted to 0% while actually is something up from 0% and there is music and some of other stuff playing. The indicator doesn't respond to any volume control.

Info
-----------
dock package version: `deepin-dock 4.1.8-1`.

updated packages: `deepin-api`;`*-calendar`;`*-daemon`;`*-desktop-schemas`;`*-dock`;`*-file-manager`;`*launcher`;`*-menu`;`*-notifications`;`*-qt5-integration`;`*-session-ui`;`startdde`.

Footage
----------
*Note: that orange thing in the GIF are not present on the system, this is just 'cause of Deepin Screen Recorder*
![deepin-screen-recorder_desktop_20170401104557](https://cloud.githubusercontent.com/assets/14314943/24579287/b8326b8c-16c8-11e7-8a4f-53b1c4089c26.gif)
__________________

**Comment by funilrys** [comment]
Same here @gustavodlima

**Comment by felixonmars** [comment]
The indicator still works correctly here, only the blur effect is not working correctly.

**Comment by funilrys** [comment]
Mine is blocked to 0% never mind the changes from dde-control-center or the button to change volume ...
