### ISSUE TITLE
[Arch Linux] Can't access dde-control-center after updates

### ISSUE THREAD

**Issue by funilrys** [linuxdeepin/developer-center#226]
I get the following after update & reboot on my laptot (I have 3 pc under deepin with this issue :smiling_imp: ) 

```
$ dde-control-center 
dde-control-center: symbol lookup error: dde-control-center: undefined symbol: _ZN10__Miracast7RemovedERK15QDBusObjectPath
```

**Comment by gustavodlima** [comment]
Same here. I've created a duplicate issue (again, saddly), but closed it then. There's a footage of the issue in #228.

**Comment by funilrys** [comment]
@gustavodlima do you have the same output with the command ?

**Comment by gustavodlima** [comment]
@funilrys Yep, same output.

**Comment by felixonmars** [comment]
Please test again with deepin-control-center 4.0.14.20170401-1. (Your mirror may need some time to sync)

**Comment by funilrys** [comment]
I can access `dde-control-center` after the update and you @gustavodlima ?

**Comment by BobbyBabes** [comment]
You guys & gals also can't use Alt+F2 to drop Deepin Terminal's Quake Window ?
And also can't use Ctrl+Alt+T to open Deepin Terminal ?

**Comment by funilrys** [comment]
@BobbyBabes Gonna close this after @gustavodlima answer but you should create separate issue cause those are differents issue:

- > You guys & gals also can't use Alt+F2 to drop Deepin Terminal's Quake Window ?
- > And also can't use Ctrl+Alt+T to open Deepin Terminal ?
- > And only the corner setting for the top left corner (Launcher) works for me. Calling up Corner Settings (right-click on desktop) takes very long to show up. And reconfiguring Corner Settings doesn't change anything.

You should create at least  1 other issue ...

**Comment by gustavodlima** [comment]
@funilrys @felixonmars It's working now. :smile:

**Comment by funilrys** [comment]
Great news @gustavodlima! :+1: :smiley: 

Closing.
