### ISSUE TITLE
dependencies: QT must be 5.10+

### ISSUE THREAD

**Issue by win32asm** [linuxdeepin/developer-center#2260]
`In file included from /usr/include/qt5/QtTest/qtest.h:45,
                 from /usr/include/qt5/QtTest/QTest:1,
                 from /home/vbespalov/source/utils/deepin/dtkcore/tests/dthreadutils/tst_dthreadutils.cpp:23:
/home/vbespalov/source/utils/deepin/dtkcore/tests/dthreadutils/tst_dthreadutils.cpp: In member function ‘void tst_DThreadUtils::testCallInMainThread()’:
/home/vbespalov/source/utils/deepin/dtkcore/tests/dthreadutils/tst_dthreadutils.cpp:51:20: error: ‘qWaitFor’ is not a member of ‘QTest’; did you mean ‘qWait’?
   51 |     QVERIFY(QTest::qWaitFor([&] {
      |                    ^~~~~~~~
/home/vbespalov/source/utils/deepin/dtkcore/tests/dthreadutils/tst_dthreadutils.cpp:78:24: error: ‘qWaitFor’ is not a member of ‘QTest’; did you mean ‘qWait’?
   78 |         QVERIFY(QTest::qWaitFor([&] {
      |                        ^~~~~~~~
make[2]: *** [Makefile:337: tst_dthreadutils.o] Error 1
`
QTest::qWaitFor() is introduced in QT 5.10 - https://doc.qt.io/qt-5/qtest.html#qWaitFor

makes sense to update the dependencies on the main page.

**Comment by BLumia** [comment]
Hi, sorry for the super late response since we're not really looking into issues that were reported outside the developer-center repo. 

The `QTest` is only for unit tests, you don't need to compile the test part if you only want to build the library. But anyway now it's in the Qt6 era and most distros have Qt 5.15 packaged so I guess it makes sense to update the README :)

**Comment by BLumia** [comment]
Updated :)

**Comment by shenmo7192** [comment]
> Hi, sorry for the super late response since we're not really looking into issues that were reported outside the developer-center repo.
> 
> The `QTest` is only for unit tests, you don't need to compile the test part if you only want to build the library. But anyway now it's in the Qt6 era and most distros have Qt 5.15 packaged so I guess it makes sense to update the README :)

我尝试构建dtk 编译docker。为了兼容UOS，采用了ubuntu 18.04，但是附带的qt版本是5.9
dpkg-buildpackage的默认操作会进行测试，从而报错。如何才能跳过测试呢？

**Comment by BLumia** [comment]
> 为了兼容UOS，采用了ubuntu 18.04

主线已经不再支持早期版本的 Qt 了，以及 uos 也会后续更新到新版本的 Qt，所以不必担心 Qt 版本问题，比较建议换 20.04 或者更新一点的 22.04。

另外是疑问的话可以考虑开 discussion 提问，确实遇到 bug 的话可以开新的 issue~
