### ISSUE TITLE
Bug report 「缺陷报告」When setting rounded corner to small, menu still show rounded corner.

### ISSUE THREAD

**Issue by tsic404** [linuxdeepin/developer-center#2264]
## Issue: Bug report 「问题反馈」 When setting rounded corner to small, menu still show rounded corner.

![image](https://user-images.githubusercontent.com/48748112/158932232-ad00d265-2127-4555-a284-1304f1b5a7ca.png)
![image](https://user-images.githubusercontent.com/48748112/158933299-d2a99801-e309-470d-b568-f8a3a3140994.png)

As is shown on above pictures, when setting `Rounded Corner` to small, other window get a non-rounder corner while menu still get a rounded one.
Related to [bbs feedback](https://bbs.deepin.org/en/post/233163)

**Comment by tsic404** [comment]
![image](https://user-images.githubusercontent.com/48748112/158937905-516f1535-f3bc-47ec-b53e-02570ccef96b.png)

**Comment by zccrs** [comment]
https://github.com/linuxdeepin/qt5integration/pull/51

**Comment by zccrs** [comment]
Fix.
