### ISSUE TITLE
manjaro升级deepin桌面V20后，系统托盘不出现U盘等挂载图标

### ISSUE THREAD

**Issue by luosoy** [linuxdeepin/developer-center#2269]
manjaro升级deepin桌面V20后，系统托盘不出现U盘等挂载图标
![深度截图_选择区域_20200603212323](https://user-images.githubusercontent.com/7417434/85251641-68821c80-b48c-11ea-8db8-6d45cff90853.png)

**Comment by justforlxz** [comment]
现在仍然有这个问题吗？

**Comment by justforlxz** [comment]
No response for too long, please re-create the issue if the issue reappears. thanks
