### ISSUE TITLE
dde-file-manager - root mode problem   10/8/2020

### ISSUE THREAD

**Issue by AkibaIllusionLinux** [linuxdeepin/developer-center#2270]
The bug can be done by running dde-file-manager with sudo (root), when you open a file like a simple .txt, dde-file-manager freezes. If it can run deepin-editor, then it freezes too. This bug wasn't it the previous versions of DDE (V20 Beta or UOS too), the console output says that the function AppController::hasLaunchAppInterface makes it freezing.
Data: V20 Beta, dde-file-manager from V20 repos.

**Comment by babyfengfjx** [comment]
Thanks for your feedback,we are very sorry that we did not communicate for a long time, the current issue we found in the latest version of normal, we first close this issue, if there are new issue later,  please feedback to us.
