### ISSUE TITLE
dde-file-manager: Build failures in 5.2.0.36

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#2271]
```
/build/deepin-file-manager/src/dde-file-manager-5.2.0.36/dde-file-manager-lib/configure/global-setting-template-fedora.js:2:13: error: Expected token `,'
    "groups": [
            ^

/build/deepin-file-manager/src/dde-file-manager-5.2.0.36/dde-file-manager-lib/configure/global-setting-template-pro.js:2:13: error: Expected token `,'
    "groups": [
            ^

/build/deepin-file-manager/src/dde-file-manager-5.2.0.36/dde-file-manager-lib/configure/global-setting-template.js:2:13: error: Expected token `,'
    "groups": [
            ^

```

**Comment by BLumia** [comment]
Building `dde-file-manager` with tag 5.5.10 (and also commit https://github.com/linuxdeepin/dde-file-manager/commit/9977208b0fa3913c5e857811dc5c510fdfef4943 on the current main branch `uos`) will no longer have this error, so I'll close this one now.

But building 5.5.10 directly on Arch Linux might still cause segment fault when try to run dde-file-manager or dde-desktop, apply https://github.com/linuxdeepin/dde-file-manager/pull/426 could fix the problem, please track the status there or at https://github.com/linuxdeepin/developer-center/issues/2251.
