### ISSUE TITLE
[deepin 20] File integrity was damaged on gvfs media

### ISSUE THREAD

**Issue by abimagnus** [linuxdeepin/developer-center#2275]
I am getting this error when copying files to my Android phone through USB cable in the V20 file manager. "File integrity was damaged"
It works fine when I use Nautilus !

![Screen Capture_select-area_20201011185145](https://user-images.githubusercontent.com/8939183/95679814-eb251800-0bf2-11eb-849c-854f07c57817.png)

**Comment by tsic404** [comment]
Does this still show in latest version?
