### ISSUE TITLE
dde-file-manager 添加了文件校验后。从本地无法正确考到smb服务目录

### ISSUE THREAD

**Issue by friddle** [linuxdeepin/developer-center#2278]
https://github.com/linuxdeepin/developer-center/issues/1920

**Comment by Zeno-sole** [comment]
由于长时间我们未跟进此问题，当前最新版本无此现象，我们先关闭该 issue。如果问题在最新版本仍然存在则建议您补充详细信息以便我们重开 Issue，或考虑开启新的 Issue 重新进行反馈。
