### ISSUE TITLE
Bug report :dde-file-manager 添加了文件校验后。从本地无法正确考到smb服务目录

### ISSUE THREAD

**Issue by friddle** [linuxdeepin/developer-center#2279]
![深度截图_选择区域_20200919194214](https://user-images.githubusercontent.com/2897690/93666369-3a04e500-fa6d-11ea-9aee-d8e2b7e9b274.png)

从本地无法正确考到smb服务目录。因为无法检验文件。同样点击跳过后就只剩1M文件。所以应该是两个问题解决。跳过也不应该改变文件大小＋smb服务目录需要特殊分支处理下

dde-file-manager 5.2.0.46
Linux friddle 5.7.7-amd64-desktop linuxdeepin/developer-center#75 SMP Mon Aug 24 20:38:46 CST 2020 x86_64 GNU/Linux

这个不需要其他信息了吧。

**Comment by babyfengfjx** [comment]
由于长时间我们未跟进此问题，当前最新版本无此现象，我们先关闭该 issue。如果问题在最新版本仍然存在则建议您补充详细信息以便我们重开 Issue，或考虑开启新的 Issue 重新进行反馈。
