### ISSUE TITLE
[Arch Linux] Control Center doesn't open up

### ISSUE THREAD

**Issue by gustavodlima** [linuxdeepin/developer-center#228]
Description
-----------------
I can't open up Control Center through Hot Corners neither launcher.

Footage
_____________
![control-center-issue](https://cloud.githubusercontent.com/assets/14314943/24579709/ca2097ee-16d0-11e7-94f4-c387ce6828aa.gif)

**Comment by funilrys** [comment]
Duplicates of #226 :smile_cat:

**Comment by BobbyBabes** [comment]
@gustavodlima What did you use to create the gif of your desktop ?

**Comment by funilrys** [comment]
@BobbyBabes If you're under archlinux, you can install `deepin-extras` then you're gonna have access to `deepin-screen-recorder`

**Comment by BobbyBabes** [comment]
@funilrys I'll check it out later today. Thanks.
