### ISSUE TITLE
列表模式下文件多超过一屏以后右键无法调出创建文件夹的窗口

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2280]
文件管理器版本：5.2.0.59
如果文件比较多超过一屏幕，我想在列表模式调用出下面这个窗口，发现不行
![截图录屏_选择区域_20201022200024](https://user-images.githubusercontent.com/12093211/96869109-9d859680-14a1-11eb-9e36-c606c180fccd.png)
几个月之前dde-file-manager好像都还没有这个bug，可是现在这个bug却出现了
windows文件管理器是没有这个bug的，很稳定，希望dde-file-manager向windows文件管理器看齐

**Comment by BLumia** [comment]
![image](https://user-images.githubusercontent.com/10095765/160329779-c0084c20-a4f9-4d02-97fb-cd3e57aad0ce.png)

现在文件管理器 dde-file-manager 5.5.3-1 的列表模式下也可以在右侧空白位置（没有字的地方）直接右键新建文件了。就先关闭这个 issue 了。

如果仍有类似问题的话，可以新开个 issue 进行反馈，这边会协助进行跟进。
