### ISSUE TITLE
[bug]如果一个删除进程正在进行，那么文管在使用快捷键永久删除时候，不会提出确认框，容易导致误删

### ISSUE THREAD

**Issue by shenmo7192** [linuxdeepin/developer-center#2281]
![截图录屏_选择区域_20201024133408](https://user-images.githubusercontent.com/47873776/97068857-ee120680-15fd-11eb-90ab-c377961b33fa.gif)

**Comment by SuperEffie** [comment]
感谢您的反馈，目前在deepin v20.5版本上按照您的步骤进行了操作，未复现到issue里的问题，shift+Delete快捷键使用多次，多次都会有提示框弹出。这个问题在您最新版本系统上是否得到修复呢？如果依然存在，请与我们取得联系，我们会联系研发人员帮忙定位解决该问题。

**Comment by shenmo7192** [comment]
该问题已解决
