### ISSUE TITLE
File System Disks Bug

### ISSUE THREAD

**Issue by noor-codes** [linuxdeepin/developer-center#2287]
## Disk Bug
This bug slows down my computer.
I only have 3 disks. The system disk is ext4 and the remaining 2 is NTFS. The rest of them is randomly added by the file system.

![image](https://user-images.githubusercontent.com/28804764/99906207-7108a880-2cf3-11eb-96d0-b45d1b593019.png)

Here is how a proof in another file system where everything looks normal.

![image](https://user-images.githubusercontent.com/28804764/99906277-cb096e00-2cf3-11eb-9175-f26077db1d7e.png)

**Comment by itsXuSt** [comment]
> > Thanks @itsXuSt , it works after I removed the spaces: `KERNEL=="loop*", ENV{UDISKS_IGNORE}="1"`
> 
> Can't believe it actually worked! Thank You, Guys!
> 
> I'm gonna keep the issue open until it's shipped by default. https://xn--deepinenespaol-1nb.org/en/comunidad/personalizacion/navegador-de-archivos/#post-8807
> 
> `Path` => sudo deepin-editor /usr/lib/udev/rules.d/80-udisks2.rules `Code` => KERNEL=="loop*", ENV{UDISKS_IGNORE}="1"

We have already add a switcher to control whether to show those loop partitions, please update to the latest dde-file-manager release to have a better experission
