### ISSUE TITLE
dde-calendar's window height is not enough

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#229]
After the recent 1.0.4 -> 1.0.5 upgrade, the content in the calendar window goes beyond its window boundary.

![2017-04-02-003810-e4a151](https://cloud.githubusercontent.com/assets/1006477/24580587/ef88a80c-173c-11e7-94cb-960bd71a04e8.png)

**Comment by funilrys** [comment]
Same here @felixonmars

**Comment by hualet** [comment]
@kirigayakazushin

**Comment by hualet** [comment]
should've been fixed
