### ISSUE TITLE
fsearch 的作者请写成原来的名字

### ISSUE THREAD

**Issue by chen244** [linuxdeepin/developer-center#2294]
https://github.com/cboxdoerfer/fsearch
这是作者的地址。。copyright不是你们谢谢
如果是全局替换请立刻替换回去

**Comment by BLumia** [comment]
看上去已于 https://github.com/linuxdeepin/dde-file-manager/commit/2998cc5f3ec88d4b3a3cd978ad24a091ea457a94 中处理...

按理说应该尽可能不内附第三方库，也不该出这种问题。不过无论如何，如仍遇到相关 license 问题欢迎另开 issue 进行反馈，我会协助解决。感谢！
