### ISSUE TITLE
PDF按空格预览，PDF未加载完就关闭预览，崩溃

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#2295]
PDF按空格预览，PDF未加载完就关闭预览，崩溃。
系统：Deepin 20.2
dde-file-manager: 5.2.8
复现：选中PDF文件，按空格后马上按ESC。
如果是桌面，桌面会假死（结束进程无法恢复）或黑屏一次（崩溃自动恢复）。
如果是文管，文管崩溃。

**Comment by babyfengfjx** [comment]
感谢您的反馈，该问题在最新版本中貌似功能完善，请升级到该版本或更高版本再次使用看看，如果问题仍然存在，请考虑开启新的 issue 进行反馈，此issue我们先做关闭处理了。
