### ISSUE TITLE
选中七个或七个以上文件拖动文件夹，文件管理器闪退

### ISSUE THREAD

**Issue by mutgil** [linuxdeepin/developer-center#2298]
同时选中七个或七个以上文件，向同一目录下的某个文件夹里拖动，然后文件管理器(dde-file-manager)就闪退了，重新打开文件管理器查看文件的确也拖过去了。

我的系统是V20.2(Linux version 5.11.1-amd64-desktop)版本

**Comment by BLumia** [comment]
目前在 deepin 社区版 v20.4，深度文件管理器 5.5.3-1 中已不再能复现此问题，就先关掉了。如果后续仍有遇到此问题的话欢迎开新的 issue 进行反馈。
