### ISSUE TITLE
完善项目下的 README/HACKING 文档

### ISSUE THREAD

**Issue by snyh** [linuxdeepin/developer-center#23]
需要两个基本的文档

- README  https://github.com/linuxdeepin/developer-center/wiki/README-Template-en  主要LICENSE需要单独下载
- HACKING 参考 https://github.com/linuxdeepin/lastore-daemon/blob/master/HACKING.org

HACKING 目前没有模板，　不过主要内容有这些点
- 文件布局
- 模块设计
- TODOs (方便其他人加入)
- Workarounds (比较反常的行为，提醒时刻记住)

另外如果有些点是比较重要的可以单独写一个文件作为链接加入 HACKING 里面

**Comment by snyh** [comment]
模块设计可以参考以下方式


1 核心设计

从整体上描述设计内容．内容一般包括,涉及到哪些服务/模块/组件 以及他们的

职责
事件流
异常情况以及对应的事件流
2 图解

通过UML图表的形式来描述设计思想．与"核心设计"配合阐述设计思想的．

常见的图表类型有

用例图 (use case diagram)
类图 (class diagram)
时序图 (sequence diagram)
状态图 (state diagram)
使用哪种图进行描述，可以通过此设计涉及到的关键视角．比如

主题是数据模型的建立，就采用 class diagram + ER diagram
主题是消息/数据的流通，就采用 sequence diagram
主题是部署，配置之类的就采用 deployment diagram
主题是模块之间的关系，就采用 use case diagram
主题是几种状态间的切换，就采用 sate diagram
若是不太熟悉UML的使用，推荐在这里入门 若是没有合适的UML编写工具，推荐使用 plantuml 若是数据库表结构的描述，允许采用ERD进行．

3 异常说明

对本方案无法解决的一些特殊情况进行说明

**Comment by fasheng** [comment]
之前把上面的 CONTRIBUTING 看成了 CONTRIBUTORS :sob: 

还是用 HACKING 作为文件名吧，之前说的歧义是指 HACKING Guide 和 Contribution Guidelines 这两个文档。。。

**Comment by Match-Yang** [comment]
HACKING 参考给出的链接实效了

**Comment by fasheng** [comment]
已经更新，记得名字用 HACKING ;)

**Comment by snyh** [comment]
....  看来我的历史记录里面要有２个很二的Commit了．．．
