### ISSUE TITLE
[BUG] DDE File Managers Issues

### ISSUE THREAD

**Issue by ricfirst** [linuxdeepin/developer-center#2302]
Using the Distro I noticed that:

1. When I click in "save as" button in any software, there is no menu to chose the file type
2. When a folder have a full list of documents in the details mode, there is no space to click whit the right botton of the mouse and select "creat a new folder"
3. Sometimes a shortcut placed in the favorites bar lost the patch and stops to work.
4. There is no button to "new folder" or "new tab" (it would be very useful)

**Comment by meiyixiang** [comment]
31/5000 
You have not replied to this question for a long time. I have closed it first. If there is any problem, please refer to the BILL of lading
