### ISSUE TITLE
Copy files from usb flash drive

### ISSUE THREAD

**Issue by btech-sewing** [linuxdeepin/developer-center#2304]
When copying files from a USB flash drive to the home directory, they are 0777, and should be 0755 for folders and 0644 for files. Now, with rights 0777, the text files are launched with a window whether to run as a program or a preview. Can this be fixed?

**Comment by BLumia** [comment]
Closing since not reproduced and no further information. If you still got this issue on the most recent version you can get, please create a new bug with detailed information provided so we can look into it. Thanks!
