### ISSUE TITLE
Error while trying to copy a file to a samsung device with dde-file-manager

### ISSUE THREAD

**Issue by Charlieras262** [linuxdeepin/developer-center#2315]
## Describe the bug
Can't copy a file from pc to a samsung phone device (A705MN)

## To Reproduce
Just try to copy a file to a samsung phone device.

## Expected behavior
A success file transfer between 2 devices.

## Screenshots
![Screen Capture_dde-file-manager_20200709224415](https://user-images.githubusercontent.com/44990120/87118253-200e8100-c238-11ea-8afa-c086f9d65837.png)

### Distro & Version
Linux Deepin 20 Beta

### Related package version
dde-file-manager v5.1.0.28

**Comment by SuperEffie** [comment]
Does this issue still exist in the newest version on deepin v20.5？Due to no reply for a long time and lack for necessary information.I close this issue firstly. If the issue still exists,you can apply to reopen it.Then we will keep contact with you to deal with it.
