### ISSUE TITLE
[Arch Linux] Deepin-daemon crash bug !

### ISSUE THREAD

**Issue by the57200** [linuxdeepin/developer-center#232]
Hello,

the deepin-deamon have a crash big bug [deepin_error.txt](https://github.com/linuxdeepin/developer-center/files/888517/deepin_error.txt). 
You can see that the deepin-deamon is in inifite loop. Please fix this now because it's impossible to use Deepin Desktop Environnement.

Bug with deepin-deamon version 3.1.6-1
Not bug with any other version.

**Comment by teoten** [comment]
completely unusable.

**Comment by funilrys** [comment]
Do you guys have `iw` installed ?

**Comment by funilrys** [comment]
I just read the bug, please execute 
`pacman -S iw` then reboot !

**Comment by funilrys** [comment]
Any feedback @the57200 @teoten ? I thought it was urgent :smile_cat:

**Comment by funilrys** [comment]
@hualet @felixonmars @jouyouyun Same as #230

We need to fix the dependencies or find a workaround ...

**Comment by the57200** [comment]
Thanks funilrys, it solve the bug and what is this bug ?

**Comment by funilrys** [comment]
@the57200 you can close this issue ... It's because iw is used by miracast to get wirless device.

**Comment by the57200** [comment]
Okay thanks, but why integrate miracast by default because little people use miracast ?

**Comment by funilrys** [comment]
To quote the author:
> Need to exec `iw` to get the wireless device whether supported P2P and AP mode.
We has added `miraclecast` and `wireless hotspot` functions, but maybe I cloud not return an error if `iw` uninstalled.
