### ISSUE TITLE
[btrfs] [dde-file-manager] 'add to bookmarks' fails

### ISSUE THREAD

**Issue by vincenzocaselli** [linuxdeepin/developer-center#2322]
Hi,
with **Deepin File Manager**, when a home subfolder is selected, then right-click, **Add to bookmark**, the result is that the bookmark is created on the left side, but if clicked it doesn't bring you to the target folder.
It is working right instead if one select a system folder (outside home).

To reproduce it, just create a subfolder in home and try to add a bookmark for it.
E.g.
1. go to /home/<user>
2. create a subfolder 'abc'
3. right-click subfolder 'abc' and select **Add to bookmark** action
4. see that on the left side a bookmark 'abc' is created
5. click on newly created bookmark
6. verify that file manager is not working, since it opens location //<user>/abc, instead of /home/<user>/abc

Distro & Version= Manjaro Deepin stable 18.0.2
dde-file-manager v1.8.2

The problem seems related on how the file
**`/home/<user>/.config/deepin/dde-file-manager.json`**
is updated. 
In fact "**locateUrl**" is not written with the correct location:
it is written as 
` "locateUrl": "/<user>/abc",`
instead of
` "locateUrl": "/home/<user>/abc",`

**Comment by babyfengfjx** [comment]
We are very sorry that we did not communicate for a long time, thank you very much for your feedback, the current issue we found in the latest version of normal, we first close this issue, if there are new issue later,  please feedback to us.
