### ISSUE TITLE
偶现dde-file-manager卡顿

### ISSUE THREAD

**Issue by mjchow** [linuxdeepin/developer-center#2324]
两块ssd nvme协议的硬盘组用mdadm组了一个raid0 
然后我电脑上还挂载了4块SATA机械硬盘 1块移动硬盘

raid0正常使用了一个晚上之后，点击打开dde-file-manager 就几乎卡死状态
![202106090828126262_深度截图_选择区域_20210609082541](https://user-images.githubusercontent.com/9709332/121283313-759e5280-c90d-11eb-8a9d-1ad5dcc9945a.png)

但是其他应用可以正常打开，浏览器，设置这种可以正常打开。

**Comment by babyfengfjx** [comment]
不知道该问题在最新版本deepin中是否仍然存在，可以尝试升级到最新版本系统试一下该场景下是否OK~

**Comment by BLumia** [comment]
暂时先关闭了，如果仍然能在最新版中复现的话，请**另开新的 issue 进行反馈**并附带必要的相关信息。
