### ISSUE TITLE
deepin刚开机，桌面图标有概率会剧烈抖动一段时间

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2328]
## 缺陷描述

我在公司的台式电脑，屏幕分辨率1920*1080，开机以后有时候桌面文件夹图标会剧烈抖动，很惊悚

## 复现步骤

不是每次出现，偶尔出现

## 期望行为

不要抖

### 发行版以及版本

deepin15.11

**Comment by BLumia** [comment]
很老的 issue 了，我尝试了一下在 v20.5 未能复现，就先关掉了。

如果你仍然能复现的话，可以开个新的 issue 进行反馈，另附带一些详细的信息以便我们进一步确认问题。感谢。
