### ISSUE TITLE
Add hibernate as optional leave option

### ISSUE THREAD

**Issue by wucke13** [linuxdeepin/developer-center#233]
Sometimes hibernating is required, e.g. on a laptop on low battery. I would love to be able to do so without the terminal. Maybe one could add an option to the settings to  activate hibernation as possible leave option?

**Comment by hualet** [comment]
Hibernating opt to cause too much trouble, so we removed it fromt he leave options.
If you're sure that hibernating is working fine on your computer, you probably can add a shortcut for it ?

**Comment by wucke13** [comment]
Ok, FMI what type of problems did occur? I also had a lot of problems, but it always came down to one of three issues:
* No `resume=UUID=...` kernel parameter
* No resume hook in the mkinitcpio.conf
* Swap not configured correctly
So, I wasn't able to trigger any hibernation issues wich was not caused by one of the above mentionend issues.

**Comment by funilrys** [comment]
@wucke13 please add [Arch Linux] or [Deepin] to your title. 

Your "three issues" are not deepin related if you are under arch ... 

Do you have multiple computer ? Cause in other issue you said
> I can confirm this, using arch too :+1:

**Comment by wucke13** [comment]
@funilrys 
Yes, I have a lot of computers, unfortunately none of them runs deepin. Yes they probably are, someway. Hibernation is a core functionality provided by the kernel/systemd. Most modern linux distros use systemd, and as deepin is based on Ubuntu which uses systemd, the chances are great that deepin uses it too. So, whilst there is a difference between arch and deepin for sure, that difference shouldn't play an important rule in how they both hibernate and what can go wrong by that. 

Just to get this clear, I do not ask for help setting up hibernation! Instead I would like to know what type of problems occurred when you had hibernation as an option in deepin linux?

**Comment by funilrys** [comment]
Clear :) 
@wucke13 your question is interesting... Can we know what are the issue so we may help @hualet ?

**Comment by hualet** [comment]
Well, many users reported that they can't resume their machines from hibernation.

**Comment by wucke13** [comment]
But we don't now what was causing these problems?

**Comment by funilrys** [comment]
Gonna try this night or tomorrow so we may have somewhere to start ...

**Comment by hualet** [comment]
Hardware, swap, graphics card driver and network card driver all may result in failure of resume from hibernation.
