### ISSUE TITLE
dde-file-manager: Build failure on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by hillwoodroc** [linuxdeepin/developer-center#2339]
version 5.2.24

https://github.com/linuxdeepin/dde-file-manager/blob/882fb2189c0d0519ef9339d5d550a3361cba5364/src/dde-file-manager-lib/controllers/dfmrootcontroller.cpp#L104

[  149s] controllers/dfmrootcontroller.cpp: In function 'bool ignoreBlkDevice(const QString&, QSharedPointer<DBlockDevice>, QSharedPointer<DDiskDevice>)':
[  149s] controllers/dfmrootcontroller.cpp:104:13: error: 'class DBlockDevice' has no member named 'hasPartitionTable'; did you mean 'hintPartitionable'?
[  149s]   104 |     if(blk->hasPartitionTable()){ // 替换 FileUtils::deviceShouldBeIgnore
[  149s]       |             ^~~~~~~~~~~~~~~~~
[  149s]       |             hintPartitionable
[  149s] controllers/dfmrootcontroller.cpp:123:35: error: 'DRDOS_sec_extend' is not a member of 'DBlockPartition'
[  149s]   123 |             case DBlockPartition::DRDOS_sec_extend:
[  149s]       |                                   ^~~~~~~~~~~~~~~~
[  149s] controllers/dfmrootcontroller.cpp:124:35: error: 'Multiuser_DOS_extend' is not a member of 'DBlockPartition'
[  149s]   124 |             case DBlockPartition::Multiuser_DOS_extend:
[  149s]       |                                   ^~~~~~~~~~~~~~~~~~~~
[  149s] make[1]: *** [Makefile:6261: dfmrootcontroller.o] Error 1
[  149s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/dde-file-manager-5.2.24/src/dde-file-manager-lib'
[  149s] make[1]: *** Waiting for unfinished jobs....
[  150s] make[1]: Entering directory '/home/abuild/rpmbuild/BUILD/dde-file-manager-5.2.24/src/dde-file-manager-lib'

**Comment by wineee** [comment]
outdate issue
