### ISSUE TITLE
[Arch Linux] Black rectangle instead of dock after fresh login for about 30 seconds

### ISSUE THREAD

**Issue by wucke13** [linuxdeepin/developer-center#234]
The rest of desktop is fully functional from the first second on, but the dock takes very long to load. Got a full blown KDE Plasma on the same machine running from password promt to fully loaded UI in less than 5 seconds, so this should not be a performance issue.

**Comment by sbwtw** [comment]
Fixed with https://cr.deepin.io/#/c/22019/ this commit.
