### ISSUE TITLE
优化：删除大文件不剪切到回收站

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#2340]
删除如果是大文件就不剪切到回收站了，类似Windows回收站的设计，减少IO读写。

**Comment by zccrs** [comment]
文件操作总归是风险很大的，还是建议交给用户自己选择。

**Comment by meiyixiang** [comment]
对于我们的考虑优先还是保证用户数据的安全，虽然现在会增加用户操作，但相对而言是安全的。如果你需要直接删除可以shift+delete.
