### ISSUE TITLE
unresponsive UI while we Enter (open as administrator) 

### ISSUE THREAD

**Issue by sarojpoudel33** [linuxdeepin/developer-center#2342]
Deepin 20.2.3

Screen Goes white...........>

https://user-images.githubusercontent.com/45546591/131598908-1dd806bf-2196-483c-b95a-68b69930ab3d.mp4

**Comment by babyfengfjx** [comment]
Thank you for your feedback.Due to no reply for a long time and lack of necessary information, closing this issue for now. If the problem still exists, please consider prvoide the necessary information to reopen the issue, or creating another issue
