### ISSUE TITLE
文件管理器缺少卸载本机磁盘分区的功能

### ISSUE THREAD

**Issue by danny2jenny** [linuxdeepin/developer-center#2343]
文件管理器中，无法卸载本机的其他分区（如Windows分区）。如果虚拟机直接访问本机磁盘分区，Deepin没有卸载该分区的话，极易造成分区数据丢失。目前只能命令行卸载，很麻烦。

建议增加本机分区的卸载功能（其他发行版都有哦）。

**Comment by itsXuSt** [comment]
这类分区很可能是正在使用的系统分区，如 / 目录、/home 目录等。如果提供这样的操作入口，对普通用户来说可能带来风险。
而动手能力强的用户，似乎也不太需要。

**Comment by meiyixiang** [comment]
这个问题如，itsXust所说，也可能造成普通用户的误操作。你的建议我已经记录，但怎么做或者还有其它更好的方式我们需要综合考虑。
