### ISSUE TITLE
打开方式增加搜索

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#2349]
很多应用时定位更快
![alt](https://s3.bmp.ovh/imgs/2021/10/e440058f79cdf471.png)
https://www.bilibili.com/video/BV1ZP4y1L7JN

**Comment by meiyixiang** [comment]
这是一个很好的建议可能会提升查找时的效率，这个问题我已经记录，但我感觉优先级别不是很高。

**Comment by meiyixiang** [comment]
这个问题我已经记录，单先关掉了。
