### ISSUE TITLE
[Arch Linux] UI bug, partially transparent background of context menu on dock items

### ISSUE THREAD

**Issue by wucke13** [linuxdeepin/developer-center#235]
The transparency on the context menus of dock items is nice, however the usability depends a bit to much on the window/background behind it. Is the grey rectangle which covers the left part of the top item in the list meant to cover the complete background of the list?
![deepinscreenshot20170405023834](https://cloud.githubusercontent.com/assets/20400405/24685095/8f3b355c-19ab-11e7-85fd-7b06682765ff.png)

**Comment by hualet** [comment]
@sonald @zccrs

**Comment by Acris** [comment]
duplicated with #227

**Comment by funilrys** [comment]
Should be closed

**Comment by sonald** [comment]
@hualet My guess is that dock gives wrong property _NET_WM_DEEPIN_BLUR_*. use xprop to spy on this property to debug. 
`xprop -id 0x8c0000f -spy _NET_WM_DEEPIN_BLUR_REGION_ROUNDED` e.g.

**Comment by kirigayakazushin** [comment]
I try to compile the latest code, dde-dock, DTK and deepin-menu, it is normal.

**Comment by funilrys** [comment]
@sonald that's all I get ...
```
$ xprop -id 0x8c0000f -spy _NET_WM_DEEPIN_BLUR_REGION_ROUNDED
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x8c0000f
  Serial number of failed request:  13
  Current serial number in output stream:  13
_NET_WM_DEEPIN_BLUR_REGION_ROUNDED
```

**Comment by Acris** [comment]
Hey guys, it seems like the latest version has fixed this bug.

**Comment by funilrys** [comment]
After update all right :) 

Great work :) @hualet you can close this
