### ISSUE TITLE
BUG : Super+E ... to open Deepin File Manager.

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#2350]
Hi,

I am running the latest Deepin OS upgraded just last night ... Was hoping this issue would get fixed after upgrading last night, but unfortunately it isn't.

Control Center has defaulted the KB shortcut to launch `dde-file-manager` using the keys `Super+E` but unfortunately it isn't opening the intended dde-file-manager instead its opening what seems like unrelated applications, strangely its opening my installed flatpak applications.

I had installed two flatpak file manager apps 'Dolphin' and 'Index' ... the Super+E would first open Dolphin, i thought as they are file managers they had some inherent mapping to Super+E i uninstalled Dolphin. strangely though now it started opening my other file manager flatpak app 'Index' again applying the same logic i uninstalled even that now i was sure dde-file-manager would open but surprisingly even now its opening my other flatpak app 'Visual Studio' ... 

I thought of implementing a custom keyboard shortcut to open `dde-file-manager` using the shortcut `Super+E` but i have encountered another issue ... this command 'dde-file-manager' through the custom shortcut opens the file manager but only 1 instance of it ... pressing Super+E after the first window is open has no effect.

Please help me get the default KB shortcut Super+E mapped to open 'dde-file-manager'

PS : Is there any command that will let me check some log in real time where the keyboard shortcut Super+E is mapped/directed when pressed ?

**Comment by babyfengfjx** [comment]
Due to no reply for a long time and lack of necessary information, closing this issue for now. If the problem still exists, please consider prvoide the necessary information to reopen the issue, or creating another issue.
