### ISSUE TITLE
File manager and control center's font size is too small.

### ISSUE THREAD

**Issue by Acris** [linuxdeepin/developer-center#236]
The file manager and control center's font size is too small
OS: Arch Linux
Screen resolution:  1920 * 1080

I've setting the font size to 16px in control center, but it have no effect on file manager and crontrol center :
![DeepinScreenshot20170405153245.png](https://ooo.0o0.ooo/2017/04/05/58e49db0a0558.png)

This is mine:
![DeepinScreenshot20170405152747.png](https://ooo.0o0.ooo/2017/04/05/58e49c888879e.png)
![DeepinScreenshot20170405153125.png](https://ooo.0o0.ooo/2017/04/05/58e49d5f0b2fd.png)

This is from Deepin website:
![DeepinWebSite](https://www.deepin.org/wp-content/uploads/2017/01/deepin-filemanager1.png)

**Comment by hualet** [comment]
What about log out and log in again?

**Comment by Acris** [comment]
@hualet I tried but no effect.

**Comment by JulianLai** [comment]
@Acris It won't work on antergos, either.

**Comment by JulianLai** [comment]
@Acris I've found a way to solve it, just add `QT_STYLE_OVERRIDE=gtk2` in `/etc/environment`, but you need to logout and login to make it work.

**Comment by zccrs** [comment]
@JulianLai 不建议在dde的Qt程序上使用gtk2 style，这样界面上可能在有些地方看着比较奇怪

**Comment by JulianLai** [comment]
@zccrs 沒辦法，要不然字體實在是太小，只有這樣才能改變字體大小

**Comment by zccrs** [comment]
不使用gtk2 style时，改变字体大小后注销重新进入桌面后字号也不会改变吗？

**Comment by JulianLai** [comment]
@zccrs 是的

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
