### ISSUE TITLE
处于登录界面的触摸板问题

### ISSUE THREAD

**Issue by weclix** [linuxdeepin/developer-center#2365]
系统：deepin社区版
设备：Thinkpad E450 
描述：1、开机后系统处于登录界面时，鼠标移动到按钮上双击并没有效果。
2、当用户登录后锁屏进入登陆界面，鼠标移动至按钮触摸板双击后有效。
3、如果这时切换用户在选择另一用户之后鼠标再使触摸板移动鼠标至任意按钮双击没有效果。
由此，触摸板如果有用户登录是可用双击的，没有用户登录是不可用双击的。也不知道这算不算一个问题？

**Comment by SuperEffie** [comment]
感谢您的反馈，该问题在deepin v20.5版本上已经修复，请升级到该版本再次进行测试。若问题依然存在，请联系我们，我们的研发人员会帮您定位和解决问题。

**Comment by SuperEffie** [comment]
不知道您的问题是否已经修复了，由于您长时间未回复，我将先关闭这个issue。如果您还有其他问题，欢迎您创建新的issue反馈给我们。我们会积极回复的~
