### ISSUE TITLE
Unable to log in to ArchLinux and ArcoLinux DDE Deepin V20 with STARDDE 5.6.0.7.

### ISSUE THREAD

**Issue by serial02** [linuxdeepin/developer-center#2366]
Hello Deepin Linux Team

It is impossible to login to ArchLinux and ArcoLinux DDE Deepin Rolling with STARDDE 5.0.6.7. If someone has a problem with the login screen, just downgrade startdde 63 until they correct this infamous problem.

https://youtu.be/zM7ZRaSqBUE

More information:

https://bbs.deepin.org/post/204752
https://forum.archlinux-br.org/viewtopic.php?id=10689

Your considerations

Serial02

**Comment by BLumia** [comment]
Sorry for the late reply, I'm now on Arch Linux with `startdde 5.8.29-1` and doesn't have this issue now. Does this issue still happen in your environment?

**Comment by BLumia** [comment]
I'll close this one for now since now it works without issue under Arch Linux. If you still have a similar issue, please feel free to create a new issue report and we'll look into it. Thanks!
