### ISSUE TITLE
Enter wrong password at login

### ISSUE THREAD

**Issue by serial02** [linuxdeepin/developer-center#2367]
Hello Deepin Team / UOS V20 1003

Upon entering the rest screen and perhaps entering the wrong password for a number of reasons, the screen simply locks up and does not return with the information that the password is wrong. The situation remains for a long time without being able to enter the correct password again.

Could the login screen just inform you that the password is wrong and simply let the user enter the correct password?

Below is a mp4 image of the login screen problem showing that I am using Deepin V20, so as not to generate absurd questions.

Note: Temporary solution is to enter TTy2 mode and enter "name and password" to unlock this situation so that we can then return to the login screen again.

https://www.youtube.com/watch?v=6hP8pcrt5Gg&feature=youtu.be

![99910860-3725ab00-2ccf-11eb-80be-976027f37025 (1)](https://user-images.githubusercontent.com/32621790/99919798-512ab200-2cfe-11eb-874e-f81c6d5f74a3.png)

**Comment by SuperEffie** [comment]
Sorry for no reply for a long time,and thanks for your feedback.Now our system has been updated to deepin v20.5.There will be a prompt after every time you enter an incorrect password, you also have five chances to enter the password.It seems that the issue you described has been fixed.I have to close this issue at first.If this issue still exists,you can apply to reopen it and Our developers will help you to deal with it.
