### ISSUE TITLE
DDE should source $HOME/.profile

### ISSUE THREAD

**Issue by Vigilans** [linuxdeepin/developer-center#2368]
Reference: https://bbs.deepin.org/post/202021

Currently, only `/etc/profile` is sourced in Xsession in dde:

https://github.com/linuxdeepin/startdde/blob/bed5314817ae4eb60c0045310386e754d162c66f/misc/Xsession.d/01deepin-profile#L1

while some other desktop environments like kde (sddm), gnome (gdm) also source `$HOME/.profile`. Personally I think dde should align with them in the profile settings so as not to cause confusion.

**Comment by tsic404** [comment]
will add it soon
