### ISSUE TITLE
startdde starting is failed on  openSUSE Tumbleweed

### ISSUE THREAD

**Issue by hillwoodroc** [linuxdeepin/developer-center#2369]
ukui@localhost:~/下载/usr/share/dde-daemon/polkit> startdde
<warning> main.go:210: x protocol authentication refused: No protocol specified

**Comment by Zeno-sole** [comment]
I'm sorry we've only started working on these old issues now, is this problem still there?

**Comment by Zeno-sole** [comment]
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue
