### ISSUE TITLE
[Arch Linux] Serious issues regarding control-center and desktop in general

### ISSUE THREAD

**Issue by wucke13** [linuxdeepin/developer-center#237]
In search of a new desktop environment I took a look on deepin and really liked it. So I installed it on my Laptop and it worked well besides of some minor bugs. After I installed it on my Desktop however, I found it barely usable on the desktop. Both desktop and laptop run the same distro and have almost the very same packages installed. I will append a list of things what do not work, the interesting thing about it is: none of this is happening on my laptop, despite beeing almost identical softwarewise.

* Network widget does not spawn
* Only a few keycombos work (like META+<Number> works to switch desktops, but  META+Space or META or CTRL+ALT+T don't do anything)
* I get an error beep on every login
* The dock does not show started apps during the first few minutes after login
* When hovering the mouse over the mainscreen (that one containing the dock) there permanently is the "busy" cursor icon, even after a few hours
* The shutdown menu does not start neither via keycombo or via launcher icon
* I can't start the control center via Dock Icon or hot corner, but when I click on  "Time Settings" in the context menue of the clock, it starts. It does not close again after starting it this way.

I have a few errors in my journal which might be related, these occur multiple times:

```
systemd-coredump[18996]: Process 18992 (dde-file-manage) of user 1000 dumped core.
                                                 
                                                 Stack trace of thread 18992:
                                                 #0  0x00007f6c5f361a10 raise (libc.so.6)
                                                 #1  0x00007f6c5f36313a abort (libc.so.6)
                                                 #2  0x00007f6c5fd04e21 _ZNK14QMessageLogger5fatalEPKcz (l
                                                 #3  0x00007f6c446ca32e _ZN14QXcbConnectionC2EP19QXcbNativ
                                                 #4  0x00007f6c446cd53e _ZN15QXcbIntegrationC1ERK11QString
                                                 #5  0x00007f6c449a79ec _ZN22deepin_platform_plugin20DPlat
                                                 #6  0x00007f6c449a765b _ZN26DPlatformIntegrationPlugin6cr
                                                 #7  0x00007f6c60a489fd _ZN27QPlatformIntegrationFactory6c
                                                 #8  0x00007f6c60a56e0b _ZN22QGuiApplicationPrivate25creat
                                                 #9  0x00007f6c60a5790d _ZN22QGuiApplicationPrivate21creat
                                                 #10 0x00007f6c5feffbdf _ZN23QCoreApplicationPrivate4initE
                                                 #11 0x00007f6c60a5932f _ZN22QGuiApplicationPrivate4initEv
                                                 #12 0x00007f6c611f7089 _ZN19QApplicationPrivate4initEv (l
                                                 #13 0x00007f6c61c165e7 _ZN3Dtk6Widget12DApplicationC1ERiP
                                                 #14 0x00000000004151bc n/a (dde-file-manager)
                                                 #15 0x000000000040aabf main (dde-file-manager)
                                                 #16 0x00007f6c5f34e511 __libc_start_main (libc.so.6)
                                                 #17 0x000000000040c2da n/a (dde-file-manager)
```

Also it appears as not all of deepin process are running:
```
~> ps -aux|grep deepin
root      2869  0.1  0.0 2148772 33940 ?       Sl   13:53   0:12 /usr/lib/deepin-daemon/dde-system-daemon
wucke13  18048  0.0  0.0 424504 26292 ?        Sl   15:45   0:00 /usr/bin/deepin-wm-switcher
wucke13  18049  0.0  0.0 2500948 38740 ?       Sl   15:45   0:01 /usr/lib/deepin-daemon/dde-session-initializer
wucke13  18085  3.2  0.5 1565432 393080 ?      Sl   15:45   0:49 /usr/bin/deepin-wm --replace
wucke13  18122  0.0  0.0 594464 53996 ?        Sl   15:45   0:00 /usr/lib/deepin-menu
wucke13  19347  0.8  0.0 572644 60392 ?        Sl   15:49   0:11 deepin-terminal
wucke13  20836  0.0  0.0  12316  2576 pts/0    S+   16:11   0:00 grep --color=auto deepin
```

The machine this happens to is somewhat special: dual CPU, no swap, large ram, about 7 disks. Normally this shouldn't have an impact, but that is the only big difference to my laptop.

This also happens on a new, blank user!

Is there any addition information I should post?
What could cause these errors? My guess is that parts of the desktop cannot startup properly, but I have no clue why.

**Comment by felixonmars** [comment]
Looks like your dde-session-daemon is not running. Are you using deepin-daemon 3.1.6-2?

Please provide the output of 
```/usr/lib/deepin-daemon/dde-session-daemon -v```

**Comment by wucke13** [comment]
I use `deepin-daemon 3.1.6-2`. Running `/usr/lib/deepin-daemon/dde-session-daemon -v` triggers the error beep. After uninstalling the nvidia proprietary drivers, the network icons do appear after boot. Attached you'l find the output of `/usr/lib/deepin-daemon/dde-session-daemon -v`.

[dde-session-daemon.txt](https://github.com/linuxdeepin/developer-center/files/900168/dde-session-daemon.txt)

I think your guess goes in the right direction, since the daemon quits from itself after a second or so.

**Comment by felixonmars** [comment]
Looks like you are already running a screensaver, and do not have bluez installed. Please try to install bluez first, and see if the daemon manage to startup.

**Comment by wucke13** [comment]
Regarding the installation of bluez:
`warning: bluez-5.44-1 is up to date -- reinstalling` indicates that bluez already was installed but I don't have any bluetooth adapters in this computer, so bluez shouldn't do anything. How could I find any other screensavers? Is `light-locker` considered a screensaver?
Indeed, after `killall light-locker` the daemon kept running. One question what bears my mind is why `light-locker` was running anyway, I did not start it intentionally. Had it for an old TWM setup.

**Comment by felixonmars** [comment]
It puts a desktop entry into /etc/xdg/autostart with `NotShownIn=Gnome;Unity`, so it runs automatically in any other DE.

@jouyouyun Is it possible to continue running the daemon even if the screensaver module failed to load?

**Comment by wucke13** [comment]
The daemon seems to run fine now. Anyway there are still issues left:

* Only a few keycombos work (like META+ works to switch desktops, but META+Space or META or CTRL+ALT+T don't do anything)
* The dock does not show started apps during the first few minutes after login
* When hovering the mouse over the mainscreen (that one containing the dock) there permanently is the "busy" cursor icon, even after a few hours
* The shutdown menu does not start neither via keycombo or via launcher icon
I can't start the control center via Dock Icon or hot corner, but when I click on "Time Settings" in the context menue of the clock, it starts. It does not close again after starting it this way, but when I start the launcher menu.

**Comment by hualet** [comment]
@jouyouyun The conflict of dde-session-daemon against other screensaver is causing much trouble, possible to loose the dependency on that module?

**Comment by jouyouyun** [comment]
@felixonmars cl: https://cr.deepin.io/22072, try it, thanks!

**Comment by joksik** [comment]
wucke13 when it comes to "busy cursor" it unfortunately occurs in several people in this and me. It is quite annoying when the cursor continues to roll itself on the desktop. This has been reported in a separate thread https://github.com/linuxdeepin/developer-center/issues/250

**Comment by wucke13** [comment]
Looks like I have/had a lot of different problems, not one big one

**Comment by SalahAdDin** [comment]
In general, in `Arch` there is a performance problem, eat 3gb of `ram` at hot and control center widget is a few slow, OK, is slow.
