### ISSUE TITLE
Issue with statedde, infinite login loop

### ISSUE THREAD

**Issue by jiaanguo** [linuxdeepin/developer-center#2374]
infinite login loop after upgrading to the latest version 5.8.22

could you please tell me where to find logs?

**Comment by luokai01** [comment]
1、sudo vi /etc/X11/Xsession.d/00deepin-dde-env





2、reboot


3、sudo journalctl -b /usr/bin/startdde




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linuxdeepin/developer-center"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月21日(星期一) 上午10:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;[linuxdeepin/developer-center] Issue with statedde, infinite login loop (#2374)





 
infinite login loop after upgrading to the latest version 5.8.22
 
could you please tell me where to find logs?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by justforlxz** [comment]
Is there still a problem now?

**Comment by justforlxz** [comment]
no reply for a long time, this issue will be closed.
