### ISSUE TITLE
多屏幕调整分辨率和布局后锁屏失败

### ISSUE THREAD

**Issue by delovt** [linuxdeepin/developer-center#2375]
```bash
$ journalctl  -xe

startdde[4722]: startmanager.go:544: dispatcher.NewApp error: mkdir /sys/fs/cgroup/blkio/2@dde: permission denied
```
OS: 20.2.4 社区版 （5.10.60-amd64-desktop）
硬件资源：i7 + 16G RAM
桌面UI：性能模式（大黄蜂方案 NVIDIA）

不太确定是不是因为分辨和屏幕位置调整（用的xrandr进行调整）导致的，主要表现为
-  开始菜单中的电源按钮失效
-  快捷键 Super+L 失效
-  快捷键 Ctrl+Alt+Delete 失效

这个问题持续好几个版本了，一直存在，之前懒得提交，现在受不了给你们提一下

**Comment by SuperEffie** [comment]
感谢您的反馈。您方便给我们提供更多的设备信息、调整分辨率和布局的详细的操作步骤及相关的日志文件吗？
设备信息可以通过终端中输入命令sudo apt install inxi -y && inxi -F后进行截图；相关的日志文件可以通过以下的工具进行获取，解压后打开终端，输入命令sudo chmod 777 dde_get_log和./dde_get_log后即可在桌面获取压缩的日志文件
[dde_get_log.zip](https://github.com/linuxdeepin/developer-center/files/8469225/dde_get_log.zip)

**Comment by delovt** [comment]
原来不是你们复现后修复的嘛…… 我更新后现在已经没有这个问题的困扰了，感谢工作组的付出。
