### ISSUE TITLE
Some icons (I checked places icons) not rendered properly in qt5 apps

### ISSUE THREAD

**Issue by mmetak** [linuxdeepin/developer-center#2377]
I'm not sure if there's something wrong with the icon theme or if it's qt5 related.
In the screenshot on the left side is pcmanfm-qt version and on the right it's pcmanfm gtk3 version.
The gtk3 one shows the icons properly.

![Screenshot_20200508_110906](https://user-images.githubusercontent.com/6218030/81391535-89312580-911d-11ea-930e-afbd8445d8f0.png)

I'm running arch with latest updates.

@felixonmars hi, it's been a long time, I hope you're doing well! ;-)

**Comment by Zeno-sole** [comment]
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue
