### ISSUE TITLE
make fails with no such file or directory cursors-src/loginspinner

### ISSUE THREAD

**Issue by romildo** [linuxdeepin/developer-center#2379]
Building `deepin-icon-theme-2020.05.29`fails with the messages:

```
[...]
cd cursors-src/loginspinner/ && make
/nix/store/81wybawvkr95c7j8gj5ab3y740mq1fli-bash-4.4-p23/bin/bash: line 0: cd: cursors-src/loginspinner/: No such file or directory
make: *** [Makefile:6: cursor] Error 1
```

**Comment by justforlxz** [comment]
@wineee maybe you can help him?

**Comment by wineee** [comment]
Hi, [romildo](https://github.com/romildo), I am trying to [package dde in NixOS](https://github.com/wineee/dde-overlay)， It will take a lot of time.

Thanks for your previous work .

**Comment by romildo** [comment]
Hi. In fact it demands a lot of work and time to package dde in NixOS. I am happy somebody is working on it. Being a member of the deepin development team will certainly make things easier for wineee.
