### ISSUE TITLE
Desktop Preferences ?

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/developer-center#238]
In the launcher I see an entry "Desktop Preferences". When I click on it I receive an Error message:
"Desktop manager is not active".
What is this? I'm I missing anything?

**Comment by hualet** [comment]
Well, there's no such thing in deepin, maybe you installed other desktop manager stuff ?

**Comment by oberon2007** [comment]
Ok, oops! Interesting question! :rofl:
