### ISSUE TITLE
Bug report. Trying to change the screensaver or desktop background crashes the os

### ISSUE THREAD

**Issue by AsmirZukic** [linuxdeepin/developer-center#2384]
I've installed deepin on my arch linux machine. It's a fresh install and doesn't have many packages installed. Right clicking on the desktop brings up the screen saver and wallpaper menu but then disappears. After that i still had video playback in the background but the dock was gone and i couldn't switch workspaces or get another window on the screen. I would be willing to provide more details if anyone can guide me through the process.

**Comment by julian-poidevin** [comment]
Same issue here

**Comment by BLumia** [comment]
Probably the same issue: https://github.com/linuxdeepin/developer-center/issues/2445

**Comment by BLumia** [comment]
Please track the follow-up of this issue at https://github.com/linuxdeepin/developer-center/issues/2283 and https://github.com/linuxdeepin/developer-center/issues/2445. Thanks!
