### ISSUE TITLE
hp probook 455 G7无法识别指纹设备

### ISSUE THREAD

**Issue by AppJ-GS** [linuxdeepin/developer-center#2385]
在fprintd官网的支持设备id里有我的设备id，但是进系统后无法识别出来，用的FS7600

**Comment by BLumia** [comment]
我们之前很少关注汇报在 developer-center 之外的问题，抱歉现在才回复 issue。

现在 deepin 已经更新到 v20.6 了，v20.7 也计划本月月底发布，fprintd 版本应该也会更新，可以先更新下看看问题是否仍在哈。如果仍然存在的话，也可以试试 https://github.com/linuxdeepin/developer-center/issues/3336#issuecomment-1201924914 提供的 fprintd 是否能解决问题。

如果问题在 v20.6 或你能获取到的最新版本中仍在的话，可以开个新的 issue 反馈（无论上面链接的那个新 fprintd 是否解决了问题），我们会在新的 issue 里跟进问题。

再次感谢反馈问题！
