### ISSUE TITLE
请你们重视一下安全问题

### ISSUE THREAD

**Issue by hillwoodroc** [linuxdeepin/developer-center#2399]
两年前 SUSE 安全团队发现了7处 deepin-clone 的安全问题，两年来基本上没得到上游积极相应。作为卖给政府的信创软件产品，希望你们能重视安全，真正做到安全可控。

https://bugzilla.opensuse.org/show_bug.cgi?id=1130388

**Comment by justforlxz** [comment]
剩余的一些问题都在 https://github.com/orgs/linuxdeepin/projects/12 里进行处理。
