### ISSUE TITLE
archlinux 上 launcher 按分类显示内容为空

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/developer-center#24]
记得上次小强修复过 archlinux 上 launcher 图标为空的问题，当时是由于引入 lastore 的新接口导致的，估计这次的原因类似。

 @linuxdeepin/li-liqiang @dragondjf 看下好不好处理。

https://github.com/fasheng/arch-deepin/issues/223

**Comment by fasheng** [comment]
![capturadeepin20160119012557](https://cloud.githubusercontent.com/assets/12741783/12409875/65bc962c-be4d-11e5-9d37-b9d506c3db5b.png)

**Comment by kosl90** [comment]
@dragondjf 我测试了一下，不知道前端是什么情况，后端似乎没什么问题，把/var/lib/lastore/categories.json删除后可以重现，你找时间看看吧

**Comment by fasheng** [comment]
经调试发现，archlinux 上后端 DBus 接口 GetAllCategoryInfos 返回的 category 以小写字母开头，而 Deepin 上则为大写字母，如

[('**development**', 2L, ['ipython3', 'd-feet', 'xoo', 'ipython']),
 ('**reading**', 3L, []),
 ('**game**', 5L, [])]

前端则是直接定义的常量
https://github.com/linuxdeepin/dde-launcher/blob/master/app/global.h#L22

**Comment by kosl90** [comment]
不应该是这个原因，不论是有没有我说的那个文件，返回的都是全小写的

**Comment by fasheng** [comment]
确实是大小写的问题，我把前端的 CategoryKeys 改为全小写后正常
```cpp
const QStringList CategroyKeys{
    "internet",
    "chat",
    "music",
    "video",
    "graphics",
    "game",
    "office",
    "reading",
    "development",
    "system",
    "others"
};
```

**Comment by sbwtw** [comment]
那这个很容易处理呀，比较的时候ignore case就行了

**Comment by fasheng** [comment]
建议前后端均使用小写，否则前端有多处代码要处理 CategroyKeys 大小写问题，容易遗漏。

**Comment by kosl90** [comment]
我把字段看错了，确实是不应该传小写的字符串，是我这边fallback的错。因为以前是用的数字作为分类的id，但是新的软件商店用的是字符串，所以加了一层处理。
前端在处理的时候直接忽略了我传的数字id，其实那个数字才是id，字符串是分类的名字，不应该直接使用。之前有提过这个问题，但是还没有改过来。

**Comment by Iceyer** [comment]
Desktop文件中的Categroy好像有大写的，这里还是要ignore case吧

**Comment by kosl90** [comment]
@Iceyer 跟desktop里面的没关系，这个是我们自己软件商店的分类，这个字段其实使用来显示的，并不是作为key来使用，但是前端没有正确使用这个字段（前端自己处理了国际化，所以后端现在也没有国际化这个字段了），其实这种操作都应该是尽量ignore case的，但是前端没处理我也没办法

**Comment by fasheng** [comment]
我觉得 key/id 这种用于标识的字符串**使用时**还是不要做 ignore case 处理比较好。

不过话说回来，Desktop 文件中的 Categories 应该都是按规范来填写的（即便同时出现 `internet` `Internet` 两种 Category，由后端归类时处理下就可以），所以直接使用原生 Category 名称（前后端均不做任何大小写处理）来做 id 似乎也没问题。

**Comment by kosl90** [comment]
用字符串做id时确实不做ignore case比较好，但是这里返回的字符串**不是做id用的**，**不是做id用的**，**不是做id用的**。因为效率和case等原因，字符串本身一般情况下也不是做id的最好选择。

跟desktop文件里的Categories字段**一毛钱关系都没有**，**一毛钱关系都没有**，**一毛钱关系都没有**
**不要歪楼**，**不要歪楼**，**不要歪楼**

**Comment by fasheng** [comment]
原来如此 :sweat_smile:

**Comment by mseba101** [comment]
hi ive installed arch..and i have the same issue...how can i solve it...
thanks

**Comment by mseba101** [comment]
you are very kind ...thanks for the reply
linux !!

2016-01-27 23:54 GMT-03:00, 李立强 <notifications@github.com>:

**Comment by fasheng** [comment]
Thanks, solved now. Let's just wait for **dde-launcher 3.0.4** and **dde-daemon 3.0.8** in archlinux~

**Comment by mseba101** [comment]
ok im using gnome/cinnamon and plasma 5 on my desktop if deepin hadnt had
that bug it would ve been perfect for my desktop!
arch runs pretty well ..sometimes strange things happen witth my wifi but
its not a soft. issue i think its connected with my ssd hard drive....ill
wait for the packages
                                                thank you !

2016-01-28 23:49 GMT-03:00 Xu Fasheng <notifications@github.com>:
