### ISSUE TITLE
占用过多磁盘io导致系统失去相应

### ISSUE THREAD

**Issue by randoms** [linuxdeepin/developer-center#2400]
系统启动时会自动挂载ntfs磁盘分区，此程序会导致磁盘io被占满。而我的系统和ntfs分区在同一个硬盘（机械硬盘）上，导致整个系统失去响应。

**Comment by BLumia** [comment]
> 此程序会导致磁盘io被占满

“此程序”指的是哪个，文件管理器挂载插件？

**Comment by randoms** [comment]
是一个文件搜索服务，我记得这个issue是在那个服务的代码处提的。好像叫deepin-anything

**Comment by BLumia** [comment]
现在（deepin v20.5）仍然有这个问题吗？或者如果你用的不是 deepin 的话，是哪个发行版，也仍然存在这个问题吗？（建议提供下具体信息，比如版本号什么的，以便我们这边复现确认问题）

**Comment by SuperEffie** [comment]
感谢您的反馈。我们想要复现您的问题，需要您帮忙提供下您的设备信息、复现步骤。您说的系统失去响应，可以具体描述一下是什么表现吗？期待您的回复。

**Comment by randoms** [comment]
已经过去很久了，现在已经不用了。之前的环境是系统装在很大的机械硬盘，3T左右，文件很多，只剩几百G的剩余空间。而这个搜索服务会创建文件索引，建立过程中会有大量的磁盘读取操作，导致系统失去响应。

**Comment by babyfengfjx** [comment]
- 非常感谢您的反馈，针对该现象我们也重点关注下；
- 如果后期再回来使用我们的新版本时，有其他新的问题也请随时反馈，我们将会第一时间做出响应；
- 该问题那我们就先做关闭处理了~
