### ISSUE TITLE
Is this 'deepin-anything-tool' ???

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#2403]
Hi,

I would like to know if this is the `deepin-anything-tool` ?

![image](https://user-images.githubusercontent.com/3283676/138330571-c121d40b-f62c-4a4e-9718-67069eb92f5e.png)

If 'Yes' ... then is there a command that i can configure a custom KB shortcut so i can invoke it with the keyboard ?

I would like to use it just like the windows 'Run' dialog window ... with a shortcut 'Super+r' 

thanks.

**Comment by yxsos** [comment]
It seems that the problem has been processed, follow-up questions, welcome new topics.
