### ISSUE TITLE
[23 BETA] Calculator: Decimal separator and thousands grouper for Brazil

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#2406]
## Describe the bug
In Brazil, the comma (;) is used as a decimal separator; while the period (.) is used as a thousands grouper.

For example, 1 million:
> 
> **1.000.000 or 1000000,00 or 1.000.000,00 <-- Correct**
> 1,000,000 or 1000000.00 or 1,000,000.00 <-- Incorrect
> 

## Screenshots
![Screen Capture_deepin-calculator_20200723002053](https://user-images.githubusercontent.com/45263160/88249294-6c1ae600-cc7a-11ea-830d-e3fdaf2fc55d.png)

It is necessary to display the comma key (;), instead of the period key (.).

### Distro & Version
deepin 20 BETA

### Related package version
deepin-calculator 5.5.9-1

### Additional context
This is an old problem known to Brazilian users. There have been several complaints accumulated in recent years and no one on the development team has responded to those complaints.

**Comment by SuperEffie** [comment]
Thank you for your feedback.This issue has been confirmed to exist in the deepin v20.5.It has been reported to the developer,and you will be noticed here after the fix.

**Comment by lxwndr** [comment]
The problem still persists in version 20.6 (OsBuild=11038.004).

**Comment by SuperEffie** [comment]
Now we have a new issue #3860 for tracking and you can help to track it. Now I will close the issue first.
Welcome to give more feedbacks about deepin system.
