### ISSUE TITLE
Symbols not showing on initial launch in Standard Mode

### ISSUE THREAD

**Issue by andrew-elkins** [linuxdeepin/developer-center#2407]
### Version:
deepin-calculator 5.6.0.10-2 on Debian 11
Kernal: 5.10.0-8-amd64

![image](https://user-images.githubusercontent.com/90867984/135731575-343609f1-e497-4212-9d46-316f7b42d5e6.png)

### Calculator opens with symbols not showing:
![image](https://user-images.githubusercontent.com/90867984/135731522-c1c3ad67-5dc5-43bd-9592-2727823daa5b.png)

After switching the mode to scientific and back to standard the symbols are restored.

![Peek 2021-10-02 15-54](https://user-images.githubusercontent.com/90867984/135731542-6e801a5d-a48f-4eb4-8359-49ec2e10d13f.gif)

Note launching in scientific mode will retain the symbols only launching with the mode set to standard do they not show up.

**Comment by babyfengfjx** [comment]
Thank you very much for your feedback on this issue, I forgot to reply, this issue is fixed in the new version of the deepin system, I don't know if there is a new version in debian that can be updated.

**Comment by babyfengfjx** [comment]
The problem has been fixed, we will close the issue first, if there is a new problem, please feel free to submit.
