### ISSUE TITLE
No square root button on a scientific calculator?

### ISSUE THREAD

**Issue by t3dium** [linuxdeepin/developer-center#2408]
really?

**Comment by meiyixiang** [comment]
![image](https://user-images.githubusercontent.com/75475994/159604691-35d46e8d-d1f2-4a02-a4d2-15a64c79510d.png)
12/5000 
I will inform you to solve this problem quickly

**Comment by meiyixiang** [comment]
This problem we let the product and r & D as soon as possible to solve! Thank you for your feedback

**Comment by meiyixiang** [comment]
I'm going to close the list
