### ISSUE TITLE
UOS安全中心（deepin-defender）严重影响应用新建连接的性能，明显影响网页打开速度

### ISSUE THREAD

**Issue by SwimmingTiger** [linuxdeepin/developer-center#2409]
UOS v20个人体验版默认启用的UOS安全中心（`deepin-defender`软件包）对应用的新建连接性能有明显的负面影响。具体表现为：

1. 网页加载明显变慢，火狐F12开发者工具“网络”标签的请求时间线上出现大片红色“阻塞”，有的甚至长达5秒。对于开启开发者模式后从应用商店之外下载的火狐影响更严重。
2. 我自行开发的一个局域网设备扫描应用，本来在其他Linux系统里一秒内建立100个连接都没问题，但是同样的二进制放在UOS里运行，性能就急剧恶化，变得每秒只能建立约2个连接，慢了50倍！
3. 对从应用商店之外下载的应用的影响远大于从应用商店下载的应用。

我录了两个动态图作为对比，这是卸载安全中心（`deepin-defender`软件包）之前的情况，左侧是应用商店安装的火狐，右侧是从火狐官网自行下载的火狐软件包，都清除了缓存，访问的也是同一个地址（[百度图片：猫](https://image.baidu.com/search/index?tn=baiduimage&ps=1&ct=201326592&lm=-1&cl=2&nc=1&ie=utf-8&word=%E7%8C%AB)）。可以看到，右侧明显慢于左侧。

此外我还测试了我自行开发的局域网设备扫描软件，扫描并发度很低，居然能够看到进度条一点一点上涨。

![卸载前](https://user-images.githubusercontent.com/4986069/82677030-f2ff1280-9c79-11ea-8c7a-64e8caae3de0.gif)

请求完成典型用时：
* 应用商店火狐：600ms
* 非应用商店火狐：2000ms

连接建立用时：
* 内网扫描应用：约 500ms (目测)

----------------

通过`sudo apt purge deepin-defender`命令卸载安全中心后，无论是应用商店的火狐还是自行下载的火狐，页面打开速度都得到了明显提升，虽然右侧还是慢于左侧。

此外，我自行开发的局域网设备扫描软件，扫描并发度也成倍的提高，进度条是一下子涨到100%的。这才是它在其他操作系统内能达到的正常水平。

![卸载后](https://user-images.githubusercontent.com/4986069/82677053-fe523e00-9c79-11ea-8b7f-5a5274a33ebd.gif)

请求完成典型用时：
* 应用商店火狐：200ms，快了3倍。
* 非应用商店火狐：600ms到1000ms。不过，清除缓存后再测，就可以获得200ms的成绩（图中没有体现）。按200ms算，快了10倍。

连接建立用时：
* 内网扫描应用：小于 10ms (目测)，快了50倍。

**Comment by justforlxz** [comment]
这里是 deepin 的社区平台，暂不处理 uos 相关的问题，该问题已经反馈给安全中心开发团队。
