### ISSUE TITLE
对比视频：UOS安全中心对Wine应用性能造成毁灭性影响，暴雪战网客户端安装慢8倍！

### ISSUE THREAD

**Issue by YihaoPeng** [linuxdeepin/developer-center#2410]
UOS安全中心（deepin-defender软件包）对所有通过Wine运行的应用程序有毁灭性的性能影响。

造成的现象包括应用安装/更新时很慢，应用用起来很卡，完全没有在Windows或者非UOS Linux里那样流畅，甚至拖动窗口都不流畅。

所以我专门录制了一个对比视频来证明这一点。对比时系统已经更新到了最新版，所以不是旧版安全中心的问题，而是新版依然有问题。

视频：
https://www.bilibili.com/video/BV1Mk4y1m73t

对比结果：
* 安装前结束deepin-defender开头的安全中心相关进程，安装暴雪战网客户端用时3分32秒。
* 不结束这些进程，安装战网客户端用时26分11秒，慢了8倍！

可能的原因：
* UOS安全中心影响了应用新建连接的速度（#1），导致应用只能一个一个新建连接，不能并发。
* 某些应用安装/更新时需要从服务器下载大量小文件，暴雪战网客户端就是一个典型案例。因为新建连接受影响，本来下载10个文件只要1秒，现在变成10秒，慢了10倍。

因为UOS安全中心（deepin-defender软件包）没有发布源代码，所以我也只能在这里提出issue。希望尽快解决，否则我只能一遍又一遍的提醒想安装暴雪战网客户端的用户，必须结束安全中心相关进程。真的很折磨。

------------------------------

也在论坛发了帖子：
http://bbs.chinauos.com/forum.php?mod=viewthread&tid=1662

希望早日解决啊。

之前的反馈帖：http://bbs.chinauos.com/forum.php?mod=viewthread&tid=1201
你们回复说：
> 安全中心已经推送了更新，修复了此问题，请再次尝试，谢谢！

但是很遗憾，问题没有解决，同志仍需努力啊。

要不然就开源出来给我们看看到底是怎么回事吧。

**Comment by BLumia** [comment]
参见： https://github.com/linuxdeepin/developer-center/issues/2409

抱歉这里是 deepin 的社区平台，暂不处理 UOS 相关的问题。UOS 用户的话走 UOS 的反馈渠道更容易解决问题。
