### ISSUE TITLE
为什么 lastore-daemon 会删除 /etc/apt/sources.list.d/*.list 指定的仓库的包信息？

### ISSUE THREAD

**Issue by duanyao** [linuxdeepin/developer-center#2411]
我在 /etc/apt/sources.list.d/ 下添加了一些第三方仓库，运行 sudo apt update 之后短时间内可以查到第三方仓库里面的软件包，但是过一段时间后就查不到了。
经过调查，发现是因为 lastore-daemon 会定期清除 /var/lib/apt/lists 下面 /etc/apt/sources.list.d/*.list 指定的仓库的包信息，仅保留 /etc/apt/sources.list 指定的仓库。系统日志中可以查到：
```
[Info] [2021-01-25 16:22:34]@apt.go.55 APTSystem RemoveCMD: AptCommand{id:"custom_update", Cancelable:true, CMD:"/bin/sh -c apt-get -y -o APT::Status-Fd=3 custom-update && /var/lib/lastore/scripts/build_system_info -now"} (exitCode:0)
```
为什么要这样做？有办法关闭这个行为吗？

**Comment by myml** [comment]
请问当前的系统版本是多少，添加的list文件名是什么

**Comment by duanyao** [comment]
2021年提交bug的时候，用的是当时的最新的 deepin 社区版，具体版本号不记得了。
我现在用的 deepin 社区版 20.4 已经没有这个问题了。
