### ISSUE TITLE
添加 AVIF 格式支持

### ISSUE THREAD

**Issue by ShuiHuo** [linuxdeepin/developer-center#2417]
请求增加查看 avif 图片的功能。

**Comment by BLumia** [comment]
现在的话建议安装 kimageformats 在你所使用的发行版里所对应的包，是带 avif Qt 图像格式插件的。

**Comment by BLumia** [comment]
这个 issue 的后续可以在 https://github.com/linuxdeepin/developer-center/issues/2053 里跟踪
