### ISSUE TITLE
右键解压 三种方式 有BUG

### ISSUE THREAD

**Issue by pgy866** [linuxdeepin/developer-center#2421]
- 第一种：  功能正常   菜单文字改为 ·「解压到」
- 第二种：  功能错误  解压到当前文件夹，目前行为与第三种一样啦，实际 不应该解压到  以压缩包{文件名} 为目录的文件夹中，而是压缩包当前所在的文件夹中
- 
- 第三种：  功能正常  解压到  以压缩包名为文件夹名的目录下

![截图_选择区域_20220314092045](https://user-images.githubusercontent.com/28694676/158096035-84e20658-f3cb-4aa8-b483-0c9af944fb56.png)

**Comment by SuperEffie** [comment]
感谢您的反馈，您反馈的issue在我们deepin v20.5系统上确实存在，我们已经向开发人员反馈，在修复之后会在此通知您

**Comment by SuperEffie** [comment]
您好，通过和产品及开发人员沟通，他们回复说归档管理器增加“动态右键菜单”需求，因为归档管理器设置有“自动创建文件夹”选项，当此选项勾选后右键选项“解压到当前文件夹”就会创建以压缩包名称命名的文件夹，再把压缩包中文件解压进去此时效果和“解压到XXX文件夹”是一致的；当不勾选“自动创建文件夹”右键“解压到当前文件夹”就是将压缩包中文件解压到压缩包同级文件夹中。主要是为了防止压缩包中文件解压到桌面发生堆叠现象，默认勾选此功能。

**Comment by SuperEffie** [comment]
由于您长时间没有回复，我先将这个issue关闭。您如果还有什么疑惑，欢迎您再次创建issue为我们提供宝贵的建议。
