### ISSUE TITLE
deepin-movie-reborn: Not working on Fedora Gnome

### ISSUE THREAD

**Issue by pedrofleck** [linuxdeepin/developer-center#2433]
Hi, I installed deepin-movie 3.2.24.3 from RPM Fusion repository but it didn't work. I open it and the process start, but I don't get any window and it starts to use a lot of CPU. Then it closes itself. I can't debug it since I don't get any messages when opening it from the terminal.

**Comment by BLumia** [comment]
Closing since no further information provided. If that still happens, please consider create a new issue and provide a coredump/stacktrace via something like `gdb` or `systemd-coredumpd`. Thanks!
