### ISSUE TITLE
Not working in Ubuntu 20.4

### ISSUE THREAD

**Issue by SMMousaviSP** [linuxdeepin/developer-center#2434]
I was using deepin-movie in Manjaro without any problem but after the update, there was a lot of problems, now I'm on Ubuntu 20.4 and I installed deepin-movie from the official repository but I can't even run the program.
this is the terminal output when I'm trying to run it from the terminal:
```
probeHwdecInterop "" ""
"dtkwidget" can not find qm files
"deepin-movie" can not find qm files
configPath "/home/mohammad/.config/deepin/deepin-movie/config.conf"
create config "/home/mohammad/.config/deepin/deepin-movie/config.conf"
[1]    217156 segmentation fault (core dumped)  deepin-movie
```
deepin-movie version: 3.2.7

**Comment by justforlxz** [comment]
Sorry for not replying for a long time, if you confirm that the problem still exists, please re-create the issue, thank you.
