### ISSUE TITLE
Black screen and only audio on Ryzen 7 4800H 

### ISSUE THREAD

**Issue by VladimirCores** [linuxdeepin/developer-center#2437]
Having the problem on Deepin 20.1 (5.10 Linux kernel)
Any video don't show up and only black screen with audio.

**Comment by Zeno-sole** [comment]
Can you report your model information? Do you have the same problem installing version 20.4?

**Comment by Zeno-sole** [comment]
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue
