### ISSUE TITLE
Deepin Movie volume shows as 200% but the volume is very very low in comparison to the 200% volume i find on vlc player ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#2443]
Hi,
Anybody know how to increase Deepin Movie volume ?

Even though the volume on Deepin Movie shows as 200% but the volume is low in comparison to the 200% volume i find on vlc player ...

PS : Deepin Movie volume was working fine and as intended on Deepin before V20 .

**Comment by aiamuzz** [comment]
> Sorry for no reply for so long time, our system has been updated to deepin version 20.5. Does your problem still exist on the latest version?Sorry that we cannot reproduce it.if this issue still exists,you can contact us,we will help to deal with it.

Sorry, still the same after updating to the latest Version 20.5 ...

**Comment by SuperEffie** [comment]
Could you provide us more information? Please take screenshots after enter commands "sudo apt install inxi -y && inxi -F" and "sudo apt policy deepin-movie" and "sudo apt policy vlc"in the terminal.

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/developer-center/issues/3189 provided more details, so I'll close this one and let's track the issue there :)
