### ISSUE TITLE
deepin-wallpapers: Relicense or remove proprietary files

### ISSUE THREAD

**Issue by throwaway1037** [linuxdeepin/developer-center#2447]
The images in `deepin/` are licensed under the proprietary CC BY-NC 3.0 license. The copyright holders should be asked to relicense their works under a [free](https://freedomdefined.org) license. If they do not, and the images remain prorpietary, then they should be removed.

I also propose instating the rule that all works must be free.

**Comment by ClayStan** [comment]
we are processing

**Comment by BLumia** [comment]
Related: https://github.com/orgs/linuxdeepin/discussions/3340
