### ISSUE TITLE
~/.local/share/icons 路径无法解析

### ISSUE THREAD

**Issue by aixiangfei** [linuxdeepin/developer-center#2457]
桌面文件 [Desktop Entry] 中 Icon 的路径解析时，如果图标文件位于 ~/.local/share/icons，会出现无法解析的情况。

Icon 的值如果是 `Icon=MyIcon` 或者 `~/.local/share/icons/hicolor/32x32/apps/MyIcon`，图标都显示不出来，只有写成 `Icon=/home/$my_user_name/.local/share/icons/hicolors/32x32/apps/MyIcon` 才能正常显示

**Comment by Zeno-sole** [comment]
在deepin上建议放到/opt/apps/xxxx/files/usr/share/icons/ 的路径下

**Comment by BLumia** [comment]
[freedesktop 上的 icon-theme-spec](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#directory_layout) 是这么描述的：

> Icons and themes are looked for in a set of directories. By default, apps should look in `$HOME/.icons` (for backwards compatibility), in `$XDG_DATA_DIRS/icons` and in `/usr/share/pixmaps`

`$XDG_DATA_DIRS/icons` 是图标路径。

> If `$XDG_DATA_DIRS` is either not set or empty, a value equal to `/usr/local/share/:/usr/share/` should be used.

默认 DDE 里 `$XDG_DATA_DIRS` 值应该是空的。

**Comment by BLumia** [comment]
确实发现有此问题，默认并未设置 `$XDG_DATA_DIRS`。需要处理一下。
