### ISSUE TITLE
Impossible launch when secondary menu is open

### ISSUE THREAD

**Issue by SalahAdDin** [linuxdeepin/developer-center#2465]
I have this problem:
![deepin-screen-recorder_desktop_20170514161944](https://cloud.githubusercontent.com/assets/5034215/26038722/9af3ba50-3917-11e7-8558-8f6b9efb66ff.gif)

When the secondary menu of whatever application is open is impossible launch the launcher; in `Gnome` the behaviour is close the secondary menu or whatever and open the launcher.

**Comment by BLumia** [comment]
According to @0yanghongwei this issue has been resolved for a while. Due to the long period of time without further information. I'll close this issue.

If you have similar issues, please consider creating another issue with the necessary detailed information so we can look into it. Thanks!

**Comment by SalahAdDin** [comment]
> @SalahAdDin The operation you mentioned should be no problem at present. You can try it and let me know if you have any questions.

I will check it later.
