### ISSUE TITLE
Duplicate Tray Icons

### ISSUE THREAD

**Issue by aksh1618** [linuxdeepin/developer-center#2467]
The dock is duplicating icons in tray for some apps, I suspect this is happening for apps where Deepin is trying to theme the menu. Initially only a single icon (with themed menu) is present, but the duplicate version appears as soon as the icon is clicked, with original, unthemed menu. Screenshots:

![deepinscreenshot_select-area_20190118051034](https://user-images.githubusercontent.com/26065812/51424863-da03ce80-1bf9-11e9-9ba2-a1f226b2720f.png)
![deepinscreenshot_select-area_20190118051050](https://user-images.githubusercontent.com/26065812/51424864-db34fb80-1bf9-11e9-99f3-70890a369c87.png)
![deepinscreenshot_select-area_20190118051102](https://user-images.githubusercontent.com/26065812/51424865-dbcd9200-1bf9-11e9-9ebf-91ca04766d54.png)
![deepinscreenshot_select-area_20190118051124](https://user-images.githubusercontent.com/26065812/51424866-de2fec00-1bf9-11e9-9c74-3c4990341ac8.png)
![deepinscreenshot_select-area_20190118051136](https://user-images.githubusercontent.com/26065812/51424867-e0924600-1bf9-11e9-8641-2bcb5e646a9a.png)
![deepinscreenshot_select-area_20190118051153](https://user-images.githubusercontent.com/26065812/51424869-e2f4a000-1bf9-11e9-92e9-90e6d6cb6bb1.png)

(May be related to linuxdeepin/dde-dock#141)

**Comment by tsic404** [comment]
This has been fixed.

**Comment by andot** [comment]
![image](https://github.com/linuxdeepin/developer-center/assets/232161/962e79e4-9d74-4cbb-8325-dba81094147a)

deepin v23 beta3 仍然存在该问题。

**Comment by HKMV** [comment]
> ![image](https://github.com/linuxdeepin/developer-center/assets/232161/962e79e4-9d74-4cbb-8325-dba81094147a)
> 
> deepin v23 beta3 仍然存在该问题。

是的，挺多软件都有类似的问题

**Comment by zccrs** [comment]
> > ![image](https://github.com/linuxdeepin/developer-center/assets/232161/962e79e4-9d74-4cbb-8325-dba81094147a)
> > deepin v23 beta3 仍然存在该问题。
> 
> 是的，挺多软件都有类似的问题

图中的软件叫什么名字呀

**Comment by BLumia** [comment]
> deepin v23 beta3 仍然存在该问题。

23 已经正式版并且推送了多轮更新了，请一定要先更新下系统再体验哈。

如果当前可更新到的最新版本仍有问题，麻烦开个新的 issue 提供下存在问题的应用的名称，以及你当前系统环境里的 dde-shell 以及 dde-tray-loader 的版本号。

> 图中的软件叫什么名字呀

图示出问题的是 Listen1，在我这边测试是没有问题的了。

**Comment by HKMV** [comment]
@BLumia 有些软件是在点击右键后才会变成两个，比如一些tauri写的软件
