### ISSUE TITLE
Resolution resets to native resolution when rebooting

### ISSUE THREAD

**Issue by m1cm1c** [linuxdeepin/developer-center#247]
Because I'm using a 4 K screen #50 is still open, I tried setting my screen's resolution to 1920x1080. However, after restarting the computer, the resolution always is set to the native resolution, again (3840x2160). Any other distro stores such settings so the user doesn't have to change them each time they boot their computer or use a script which changes the settings automatically.

I'm using a fresh installation of Deepin.

**Comment by jouyouyun** [comment]
If the bug occured, please exec `journalctl /usr/bin/startdde  > /tmp/dde.log` and upload the file `/tmp/dde.log`, thanks!

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
