### ISSUE TITLE
Third party plugin widget resize problem

### ISSUE THREAD

**Issue by SeptemberHX** [linuxdeepin/developer-center#2472]
![image](https://user-images.githubusercontent.com/18042424/82646921-f4afe280-9c47-11ea-911a-b4b820d8fed9.png)

The plugin widget in the RED RECT consists of two QLabel with QVBoxLayout, and the parent widget is a QWidget. The dark rectangle around each QLabel is the border.

It looks everything works fine. But strange things happen when I open a new application(A new icon will be added to the app area, and all the widgets on the dock seem be resized)

![image](https://user-images.githubusercontent.com/18042424/82647221-77d13880-9c48-11ea-85db-2fe234f14a9e.png)

The height of the plugin widget is really strange. Drag the widget and move it to other place will make it look normal again:

![image](https://user-images.githubusercontent.com/18042424/82647413-c1ba1e80-9c48-11ea-8b30-3af24e8deae4.png)

**Comment by justforlxz** [comment]
https://github.com/linuxdeepin/dde-dock/commit/9188fff15bdac20edbd14290bb1e44c1bcef28b5 已经修复以上问题
