### ISSUE TITLE
Problem Don't Show Dock Some Times

### ISSUE THREAD

**Issue by jamkar20** [linuxdeepin/developer-center#2473]
When I Want To Change Wallpaper & Screensaver hide anything and I Press ESC Then Show Desktop and Launcher Work But Dock Don't Show And When I log out and back all things is ok

**Comment by justforlxz** [comment]
Since we use dbus as the IPC method, it is usually asynchronous and slow, there is a certain point in time when other components are responding to the action, but the action has actually been terminated.

We will optimize this process.
