### ISSUE TITLE
全屏运行游戏时按Ctrl/Alt/Shift会弹出Dock

### ISSUE THREAD

**Issue by YihaoPeng** [linuxdeepin/developer-center#2477]
# 系统
* UOS20个人体验版
```
dde-dock/未知,now 5.0.0099.2+c1-1 amd64 [已安装]
```

# 现象
无论玩什么游戏，无论是Wine的还是Linux原生的，无论是Vulkan的还是OpenGL的，只要全屏时按Ctrl/Alt/Shift，必定会弹出Dock，设置“一直隐藏”也没有用。

我录了个视频你们可以看看（如果看不见，就是还没审核通过）：
https://www.bilibili.com/video/BV1yK4y1s7kG/

官方论坛的类似案例：
https://bbs.deepin.org/forum.php?mod=viewthread&tid=196852

# 缓解

为了能正常打游戏，我都已经被逼写出这样的脚本了：
```
cat /usr/local/bin/nodock
```
```
#!/bin/sh
sudo mv /usr/bin/dde-dock /usr/bin/dde-nodock
killall dde-dock
```

```
cat /usr/local/bin/redock
```
```
#!/bin/sh
sudo mv /usr/bin/dde-nodock /usr/bin/dde-dock
```

# 期望

希望早日修复这个问题。

**Comment by tsic404** [comment]
这个问题现在还存在吗？

**Comment by YihaoPeng** [comment]
`dde-dock/未知,now 5.4.73+home amd64`
已经没有这种现象了。
