### ISSUE TITLE
Mouse pointer is big at non-native display resolution

### ISSUE THREAD

**Issue by m1cm1c** [linuxdeepin/developer-center#248]
Because I'm using a 4 K screen #50 is still open, I tried setting my screen's resolution to 1920x1080. When hovering over the dock, the mouse pointer becomes very big. When moving the dock from the bottom edge to the left edge, rebooting, and changing the resolution to 1920x1080, again (see #247), the mouse pointer is very big at all times.

I'm using a fresh installation of Deepin.

**Comment by jouyouyun** [comment]
Please wait deepin 15.5!

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
