### ISSUE TITLE
[Open] After updating the DDE-DOCK taskbar icons disappear

### ISSUE THREAD

**Issue by serial02** [linuxdeepin/developer-center#2483]
Hello Team LinuxDeepin/DDE-DOCK

After updating the DDE-DOCK the taskbar icons disappear and on restart an error message appears with the following error message:

![Screen Capture_20201112175343](https://user-images.githubusercontent.com/32621790/99003232-81af6680-251c-11eb-80a1-676422ff8d65.png)

error message

![Screen Capture_20201112175157](https://user-images.githubusercontent.com/32621790/99003258-912eaf80-251c-11eb-8377-8341f16df7cc.png)

**Comment by BLumia** [comment]
Hi,

Since it's resolved, I'll close this issue for now. If you have similar issues, please consider creating another issue with the necessary detailed information so we can look into it. Thanks!
