### ISSUE TITLE
dde-dock occasionally does not respond

### ISSUE THREAD

**Issue by lidanger** [linuxdeepin/developer-center#2484]
dde-dock occasionally does not respond. Clicking anywhere gives no response, but pressing shortcut keys can open the launcher.
And it's not enough to turn it off in the system monitor with normal operation, it must be forced off to restart.

System Version: latest version of 1003

**Comment by BLumia** [comment]
Closing since no further information provided. Feel free to create another issue if this still happens on the most recent release of Deepin/DDE :)
