### ISSUE TITLE
Weird Artifact Using NVIDIA Drivers

### ISSUE THREAD

**Issue by Mark-Smith-18** [linuxdeepin/developer-center#2489]
I have noticed several weird graphic artifacts while using Nvidia drivers. Pictures attached. I tried using the Nouveau and Nvidia drivers, but no luck.
![Screen Capture_dde-dock_20210214204902](https://user-images.githubusercontent.com/79059240/107887004-d8f21800-6f0b-11eb-9572-6f3cc8d7d21e.png)
![Screen Capture_dde-dock_20210214204829](https://user-images.githubusercontent.com/79059240/107887005-da234500-6f0b-11eb-8a44-5bb06ec3870e.png)
![Screen Capture_20210214204924](https://user-images.githubusercontent.com/79059240/107887007-dbed0880-6f0b-11eb-98f8-0203acc0555b.png)

**Comment by BLumia** [comment]
Closing since there hasn't been a reply for a long time. If you still got similar issue on the most recent version of deepin, please create a new issue with detailed information so we could look into it. Thanks!
