### ISSUE TITLE
Keyboard layout Neo 2 not working

### ISSUE THREAD

**Issue by m1cm1c** [linuxdeepin/developer-center#249]
One of the keyboard layouts Deepin offers is Neo 2. It's a German keyboard layout and can be found appropriately in the German category. It uses 6 layers which can be found at http://neo-layout.org below "Die 6 Ebenen" (German for "The 6 Layers").

At any time, at least on of the layers 2 through 6 doesn't work. It just doesn't produce characters, meaning that at some times you can't even type capital letters.

I tried rebooting several times unsuccessfully.

The layers which don't work change very frequently (10 to 60 seconds).

**Comment by hualet** [comment]
@jouyouyun

**Comment by jouyouyun** [comment]
The outputs for `setxkbmap -query`?

**Comment by m1cm1c** [comment]
@jouyouyun It's:

```
$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     de
variant:    neo
```

On my Ubuntu 16.04 installation, it's:

```
$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     de,us
variant:    neo,
```

I installed Deepin using the standard American keyboard layout (I freshly installed it now because when I installed it the first time, I tried to choose Neo during the installation process but that didn't work and I wanted to be sure the problem isn't because of that.) and then chose Neo in the settings without removing the standard American keyboard layout. On Ubuntu, Neo is active and Neo, the standard American, and the standard German keyboard layouts are added in the settings (so I can `super + space` through them).

**Comment by jouyouyun** [comment]
I do not understand what you mean, the keyboard layout is set to Neo can not work?

**Comment by m1cm1c** [comment]
@jouyouyun Layer 1 (lowercase Latin letters, Arabic numbers) always works. The other layers often don't produce any characters. It's not that the wrong characters are inserted, it's just that nothing happens. But there always are several layers at any time capable of producing characters, as it seems.

**Comment by jouyouyun** [comment]
It can work under Ubuntu?

**Comment by m1cm1c** [comment]
@jouyouyun Yes, it does work under Ubuntu. I have been using it exclusively (except where it's not available like in the BIOS) since 2011 and Ubuntu is my main operating system for even longer. There never was a single character provided by NEO 2 I wasn't able to type.

**Comment by jouyouyun** [comment]
Try exec `setxkbmap  -layout  de,us  -variant  neo,` under deepin, the layout will be same with ubuntu, test whether work? Thanks!

**Comment by snyh** [comment]
The essential difference can be inspect by 
`setxkbmap -print de,us neo | xkbcomp -o de_us_neo.xkb -xkb -`
`setxkbmap -print de neo | xkbcomp -o de_neo.xkb -xkb -`
`vimdiff de_us_neo.xkb de_neo.xkb`

**Comment by m1cm1c** [comment]
I think this issue can be closed because it already has been fixed as the problem seems to not exist in Deepin 15.4. I set the keyboard layout to NEO 2 in my Deepin 15.4 installation and as far as I can tell, it works flawlessly.

**Comment by hualet** [comment]
Weird, we didn't do much about keyborad layouts in 15.4 actually, except we've made super+space more efficient. I'm now very confused. :sweat_smile:

**Comment by m1cm1c** [comment]
@hualet It definitely didn't work with the 1 VM installation nor with the 3 actual installations of 15.3 where I checked. It very notably didn't work. But I can't find anything about it that doesn't work in 15.4 RC.

**Comment by hualet** [comment]
@m1cm1c OK, happy ending anyway.  :joy:
