### ISSUE TITLE
archlinux下，dde-dock开机会卡死半分钟

### ISSUE THREAD

**Issue by ArcheyChen** [linuxdeepin/developer-center#2490]
在全新安装的archlinux系统下，显卡驱动配置：nvidia+optimus-manager，安装了deepin,deepin-extra两个包
开机时，dock栏会卡死半分钟。无法点击任何dock栏上的图标和按钮，网络连接等状态栏也无法加载出来
但是此时桌面是能正常使用的，包括打开桌面图标，右键打开终端等

这是在默认的窗口管理器deepin-wm下的情况，如果换成deepin-kwin就不会出现开机卡的情况。但是会造成无法打开窗口特效。
请问这个问题是本地配置文件的问题，还是说代码中的bug导致的？

**Comment by BLumia** [comment]
Should be fixed after upgrade to `startdde 5.9.32-1` or newer version :)
