### ISSUE TITLE
第三方插件 pluginName() return "datetime" 才能显示在插件列表中

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#2492]
```
const QString WeatherPlugin::pluginName() const
{
    //return "HTYWeather";
    return "datetime";   //插件列表不显示Hack
}
```

**Comment by tsic404** [comment]
最新的dde-dock还有这个问题吗？

**Comment by BLumia** [comment]
我在 deepin 社区版 v20.4，dde-dock 5.5.9-1 上无法复现这个问题（我测试使用的插件是[这个](https://github.com/BLumia/dde-dock-pineappledatetime/)）。

由于这个 issue 比较陈旧了，如果你仍然遇到这个问题，请考虑开新 issue 进行反馈。
