### ISSUE TITLE
Keyboard Layout and Switch Layouts disappear and not work Version 20.2.1

### ISSUE THREAD

**Issue by jobegod** [linuxdeepin/developer-center#2494]
Keyboard Layout disappear from  dock and Switch Layouts(Ctrl+shift or alt+Shift or Super+Space)  not work to change language.

**Comment by SuperEffie** [comment]
Thanks for all your feedback. 
Our system has been updated to deepin v20.5.The function Keyboard Layout, Input Methods and System Language need to be added independently. input method configuration can be switched using hotkeys,while switching keyboard layout and system language need to be done in the control center.You are welcome to create new issues to provide good suggestions.
@Author
[jobegod](https://github.com/jobegod)it seems that your issue has been fixed.Does this problem still exist?

**Comment by VladimirCores** [comment]
Can't switch keyboard layout, any solution for that problem? Key combinations just do not catched by the system. And I have Xmodmap installed, struggle with manual switching language for more than a year, at previous versions it was working no problems, Ctrl+Space switching the language.

**Comment by BLumia** [comment]
Hi @VladimirCores (and for people who still have similar issue on the most recent version of deepin), please consider create a new issue to report with more information provided so we can try to reproduce and look into the issue. There will be an issue template to be filled. Thanks!
