### ISSUE TITLE
Bug report : wireless network  UI  blocking

### ISSUE THREAD

**Issue by jiangzc** [linuxdeepin/developer-center#2495]
无线网络界面经常处于无响应状态，鼠标点击没反应，过一会才能接受用户输入事件。

我怀疑UI主线程中存在长达几秒的耗时操作，导致界面阻塞！

如何复现：快速切换不同的Wifi   
系统版本： deepin  v20.1   
无线网卡型号：intel AC 9560   

![image](https://user-images.githubusercontent.com/13901512/119524238-0c1c3100-bdb0-11eb-878a-938b088518e5.png)

**Comment by BLumia** [comment]
太久没进一步信息，先关掉了。如果仍然遇到问题的话还请开新的 issue 进行反馈，感谢！
