### ISSUE TITLE
必现问题：dde-dock cpu 100%

### ISSUE THREAD

**Issue by honyxiao** [linuxdeepin/developer-center#2497]
## 缺陷描述
在使用 GitAhead 软件查看 repo 仓库时，选择某一条提交文件比较多的记录，
此时 GitAhead 会比较慢/卡，（GitAhead 的 cpu 占用率比较高，直到文件列出后会降下来）
在提交记录间切换一两次
这个时候 dde-dock 的 cpu 也会跟着涨到 100%，dock 无法响应点击，占用率也无法降下来

## 期望行为
GitHead 卡应该不影响 dde-dock 卡

### 相关的软件包版本
GitAhead v2.6.2

**Comment by justforlxz** [comment]
个人感觉是因为窗口属性一直在发生变化，同步的，可能 dde-daemon 也是 cpu. 100%了。

如果验证是这样的问题，会加一层防抖过滤掉这种一直改变的信号。

**Comment by myml** [comment]
问题还有吗？我安装了GitAhead并没有发现会导致dde-dock cpu占用升高
![image](https://user-images.githubusercontent.com/13045857/164157643-04fdb513-0d80-42be-9bb1-d14eafcfebc1.png)

**Comment by myml** [comment]
由于issue时间太久，在新版本未复现，暂时先关闭了。
如果有再次遇到相同问题，可以开启新的 Issue 重新进行反馈
