### ISSUE TITLE
deepin技术文章规划

### ISSUE THREAD

**Issue by snyh** [linuxdeepin/developer-center#25]
之前主要文章都放着docs.deepin.io下．　但问题在于
1. blog和wiki两种性质的内容混合在一起．　导致目标不明确

我提议可以这样分类
1. 单独建立一个blog,类似http://dds.deepin.org 或者采用gitbook的形式
2. developer-center只做wiki，内容需要严格审核以及维护．控制内容数量和质量．　供大家做一个权威性的参考
3. 每个项目下先需要 README和CONTRIBUTE的内容
4. issuse作为专业问题讨论的地方．　类似这样．　我先和@fasheng 讨论后，在这里提出 :)   　其他IM软件只做闲聊或者初步想法的

**Comment by fasheng** [comment]
补充一点
5. docs.deepin.io 下的技术文章会逐步转移到 wiki，文档内容会做调整甚至重写。全部完成后，可以废弃  docs.deepin.io 域名或重定向到 wiki
