### ISSUE TITLE
Panel Will Not Appear With Smart Hide Enabled

### ISSUE THREAD

**Issue by gardotd426** [linuxdeepin/developer-center#2502]
## Describe the bug
So if you go to the panel and right-click, and enable "Smart Hide," once the panel disappears because of a maximized window, mousing over the area does not bring the panel back. The only way to bring the panel back is to hit the Super/Meta key, or un-maximize the window. This isn't intended behavior of "Smart Hide," you're supposed to be able to mouse over the bottom of the screen (or wherever the panel is) and the panel should reappear. 

## To Reproduce
1. On Arch Linux, make sure you're on the deepin package versions listed below
2. Right-click on the Panel and go to "Status"
3. Select "Smart Hide." It does NOT matter whether you're using "Fashion Mode" or "Efficient Mode." Both show the error
4. Maximize any window, like a browser. NOT a full-screen video, just a maximized window. 
5. The panel will disappear as it's supposed to, but you can NOT get it to come back with your mouse, only by un-maximizing or pressing the super key to get the launcher to open. Ordinarily, you should be able to mouse down, and get the panel to reappear. 
-->

## Expected behavior
The panel is able to be re-activated with the mouse. 
## Screenshots
Notice I'm mousing down to the panel, applying plenty of "pressure" (since most smart hide/intellihide panels require a minmal amount of "pressure" for the panel to reveal), and nothing happens until I unmaximize (or press the start/meta key to pull up the launcher:
![panel2](https://user-images.githubusercontent.com/54234607/83557117-137f6600-a4df-11ea-8ee1-1521d2f1d554.gif)

### Distro & Version
Arch Linux x86_64

### Related package version
```
yay -Q | egrep "deepin|dde"
deepin-account-faces 1.0.11-1
deepin-album 5.6.9.13-2
deepin-anything 5.0.1-2
deepin-anything-arch 5.0.1-83
deepin-api 5.1.11.1-1
deepin-boot-maker 5.4.8-1
deepin-calculator 5.5.12-2
deepin-calendar 5.6.4-1
deepin-clone 5.0.3-1
deepin-clutter 1.26.2-2
deepin-cogl 1.22.5-3
deepin-community-wallpapers 1:1.7.7-1
deepin-control-center 5.1.0101.0.20200427-1
deepin-daemon 5.10.0099.2-1
deepin-desktop-base 2:2020.04.12.2-1
deepin-desktop-schemas 5.5.0.5-1
deepin-dock 5.1.0.11-1
deepin-draw 5.8.0.19-2
deepin-editor 5.6.10-1
deepin-file-manager 1:5.1.1.25-2
deepin-gtk-theme 17.10.11-1
deepin-icon-theme 2020.05.29-1
deepin-image-viewer 5.6.3.2-2
deepin-kwin 5.1.0-1
deepin-launcher 5.2.0.0-1
deepin-menu 5.0.1-2
deepin-metacity 3.22.24-1
deepin-movie 1:5.7.6.29-1
deepin-music 6.0.1.8-1
deepin-mutter 3.20.38-4
deepin-network-utils 5.1.0.0-1
deepin-picker 5.0.6-1
deepin-polkit-agent 5.1.0-2
deepin-polkit-agent-ext-gnomekeyring 0.1.0-1
deepin-qt-dbus-factory 5.1.0.1-2
deepin-qt5dxcb-plugin 5.0.11-2
deepin-qt5integration 5.1.0.1-3
deepin-reader 5.6.4-2
deepin-screen-recorder 5.8.0.11-3
deepin-screensaver 5.0.3-1
deepin-screensaver-pp 0.0.4-1
deepin-screenshot 5.0.0-4
deepin-session-shell 5.0.0098.0-2
deepin-session-ui 5.1.0101.0-2
deepin-shortcut-viewer 5.0.2-1
deepin-sound-theme 15.10.6-1
deepin-system-monitor 5.6.3-2
deepin-terminal 5.2.2.20200601-1
deepin-turbo 0.0.3-1
deepin-wallpapers 1:1.7.7-1
deepin-wm 1.9.38-4
startdde 5.4.0.1-1
```

### Additional context
Like I said, just an update or two ago, this was not an issue, I could get the panel to reveal itself while on "Smart Hide" just by mousing over it, indicating I wanted to use it. Having a "Smart Hide" Where you literally can't get the panel to reveal itself without unmaximizing a window is unusable.

**Comment by justforlxz** [comment]
Sorry for not replying for a long time, if you still encounter this problem, you can re-submit the issue, thank you.
