### ISSUE TITLE
Duplicate Icons

### ISSUE THREAD

**Issue by imHamo** [linuxdeepin/developer-center#2504]
i have been using deepin for year.  i was wait this bug get fixed but i guess support don't know about it

**The Bug :** 

Any App that based on **Electron** will show in task bar as 2 Icons And that's really annoying
cause if i use 3 or 4 app based on **Electron**  my bar will be full of icons

A Fix i found : 
if i remove this package
sudo apt remove libappindicator3-1 
issue will be **FIXED** . BUT! 
Any app that use this package will get deleted as well 
important app like ( Discord, Skype , any app use this package) so it's not good fix

i hope support find a way or add tool or something that black list app i want from show duplicate icons

![image](https://user-images.githubusercontent.com/79617976/125206918-e082d680-e289-11eb-9c67-5fbecf5c3d45.png)

**Comment by yxsos** [comment]
Hello, about the questions you mentioned in the community version, please pay attention to the V20.5 version released on March 31, and the UOS home version mentioned in your text, we have notified the relevant responsible person from the internal notice Waiting for follow-upRepair, additional recommendation on the bbs.Chinauos.com website feedback on the family version, so you can get fast and resolved. Thank you。

**Comment by yxsos** [comment]
If there is no other problem, this topic is temporarily closed.
