### ISSUE TITLE
托盘通知气泡和图标位置不对

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#2505]
QSystemTrayIcon->showMessage(QString_title, QString_infomation, QSystemTrayIcon::MessageIcon::Information, milliseconds);
图片浏览器里是Deepin15的。
![alt](https://i0.hdslb.com/bfs/album/b1bd72aa54effbdd79c057e92512caecc03cd59e.png)

**Comment by tsic404** [comment]
这个在最新的dde-dock上还是这样吗？

**Comment by BLumia** [comment]
这个应该不是 bug 吧。`QSystemTrayIcon::showMessage()` 是发通知的。

> Note that display of messages are dependent on the system configuration and user preferences, and that messages may not appear at all. Hence, it should not be relied upon as the sole means for providing critical information.

在 Windows 8+ 应该就已经不是气泡了，会是通知的形式。deepin 里也是通知的形式。
