### ISSUE TITLE
dde-dock卡死，没有任何反应了

### ISSUE THREAD

**Issue by wangwg1** [linuxdeepin/developer-center#2506]
dde-dock卡死，没有任何反应了。kill掉之后就好了。

**Comment by BLumia** [comment]
这边在目前的最新版本（deepin 社区版 v20.4 dde-dock 5.5.9-1）里没有遇到近似情况的问题，就先关掉了。

如果仍然有遇到的话，请考虑新开的 issue 然后提供一些详细的信息（您使用的发行版，dock 版本，日志之类），以便我们确认问题哈。
