### ISSUE TITLE
这个也不知道提到哪，就提到这里了。这个是birdtray，设置的时候其实是有checkbox的，但是在咱们deepin上显示不出来。

### ISSUE THREAD

**Issue by wangwg1** [linuxdeepin/developer-center#2507]
![image](https://user-images.githubusercontent.com/20198809/127108443-c126b1fc-c400-4633-97b3-4193be226240.png)
这个也不知道提到哪，就提到这里了。这个是birdtray，设置的时候其实是有checkbox的，但是在咱们deepin上显示不出来。我提bug到birdtray了，后来我自己改了birdtray源码，把勾选checkbox改为selected了。但是就只能选一行了。
原因应该是deepin和qt的显示有冲突。所以显示不出来checkbox框。这个框应该是treeview还是tableview，好长时间了，给忘了。

**Comment by BLumia** [comment]
这个说的是 thunderbird，不是深度邮箱。不过 thunderbird 似乎目前也不是在用 Qt 了，就暂时先关掉了。

如果目前在最新的 deepin 系统中仍然能复现这个问题的话，欢迎开个新的 issue 进行反馈。developer-center 是正确的反馈位置~

感谢支持！
