### ISSUE TITLE
编译时遇到问题2

### ISSUE THREAD

**Issue by MCredbear** [linuxdeepin/developer-center#2517]
[build_dde-session-ui.log](https://github.com/linuxdeepin/dde-session-ui/files/4338790/build_dde-session-ui.log)
编译环境：linuxmint bioinc x86_64

**Comment by BLumia** [comment]
抱歉我们之前很少留意 developer-center 外的 issue 所以现在才回复...

感觉这个日志好像缺了 stderr 只有 stdout 的样子...不过这个是陈年老 issue 了所以这边就先 close 掉了。如果你在获取最新版本进行构建过程中仍然遇到问题的话，欢迎开新的 issue 进行反馈。
