### ISSUE TITLE
dde-dock 開機時載入很久，並且顯示一大塊黑色方框框

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#252]
![deepinscreenshot20170410150425](https://cloud.githubusercontent.com/assets/20014762/24850386/6e5427c6-1e02-11e7-96b7-6bf77edc3fee.png)

**Comment by JulianLai** [comment]
#218

**Comment by hualet** [comment]
每次都能出现么？正在寻求协助调试者 :joy:

**Comment by JulianLai** [comment]
@hualet 和 busy cursor 一樣每次開機都會，然後不一定是在正下方，有時後是左下角

**Comment by JulianLai** [comment]
最近一次的更新似乎已經解決這問題了
