### ISSUE TITLE
Icon Logo Login Screen on Arch Linux to big/wide

### ISSUE THREAD

**Issue by a6smile** [linuxdeepin/developer-center#2520]
Arch Linux icon logo are appear to wide/big.

**Comment by BLumia** [comment]
Sorry for the late response. I cannot reproduce the issue (or I didn't understand your issue) on the most recent version you can get on Arch Linux. If you still have this issue after updating your packages, please feel free to create another issue with detailed information (if you don't know what's the related package is, a screenshot could be helpful) so we can look into it.
