### ISSUE TITLE
Screen background crash 

### ISSUE THREAD

**Issue by RlZkhere** [linuxdeepin/developer-center#2521]
When i try to change the background of the screen, the DE crash and i've to stop and restart the desktop enviroment or using shortcut to open GUI app.

**Comment by BLumia** [comment]
Sorry we didn't look into issues that were reported outside the developer-center repo, and we are aware of the issue you mentioned. See https://github.com/linuxdeepin/developer-center/issues/2831 for our current plan to address the community support issue.

The issue you were mentioned should no longer exist in our most current release of deepin (deepin v20.5), so I'll close this issue for now. If you still have similar issues on most recent release of deepin or on other distro, feel free to create another issue so we can look into it. Thanks!
