### ISSUE TITLE
[BUG] Notification's actions issues and popup fails

### ISSUE THREAD

**Issue by N1coc4colA** [linuxdeepin/developer-center#2526]
The notifications after they disappear of the screen, they go in the notification centre (idk where in the project), but when you trigger an action after the notification is hidden, the signal ActionInvoked(uint in0, uint in1) of org.freedektop.Notifications isn't triggered. It is problematic if an app wants to use it in a daemon to open a message of someone or such things.
Moreover, the popups sometimes fails, I have to open the notifications plugin and then the popups. It seems to happen randomly :/

**Comment by SuperEffie** [comment]
Sorry for no reply for so long time,and thanks for your feedback.Sorry for that I cannot reproduce it.I close this issue now.If this issue still exists,you can apply to reopen it,and our developers will help to deal with it.
