### ISSUE TITLE
[BUG] Missing icons with notifications and unable to stack/unstack

### ISSUE THREAD

**Issue by N1coc4colA** [linuxdeepin/developer-center#2527]
The close icon is missing, it is replace by an icon of a little flat window design in line art.
Moreover, when I have multiple notifications of a same app, I'm unable to stack them, or they sometimes don't stack themselves, or they are stacked and I can't unstack, I have to close the top one to access the next.

**Comment by meiyixiang** [comment]
Please upgrade to 20.5 with the system. We have fixed this problem
