### ISSUE TITLE
Keyboard layout is changed from English (EE.UU. international with dead keys) to English EE.UU. after suspending or locking the computer

### ISSUE THREAD

**Issue by igatjens** [linuxdeepin/developer-center#2528]
I use the English (EE.UU. international with dead key) keyboard layout, after suspending or locking the computer, the distribution changes to English (EE.UU.) although it is still marked English (US, international with dead key), the dead keys that they are activated with the Alt on the right (AltGr) they do not work, and even if you change the keyboard layout to Spanish and then set it back to English (US, international with dead key), it is still locked in English (US).

The only way I have found it to work well again, is to log out or restart the computer, but as soon as the computer is suspended, I have to log out again so that the keyboard is configured correctly 

It is a very annoying problem because to get back to writing correctly in my language (Spanish), I have to log out or restart the computer.

This problem is old, it was also present in Deepin 15.11. Other related issues but from Deepin 15 are the following.

- [22 Jul 2019](https://github.com/linuxdeepin/internal-discussion/issues/1992)
- [16 Aug 2018](https://github.com/linuxdeepin/dde-session-ui/issues/36)

[Información del dispositivo20200922_114120.txt](https://github.com/linuxdeepin/dde-session-ui/files/5263105/Informacion.del.dispositivo20200922_114120.txt)

de-session-ui version
apt list dde-session-ui 
dde-session-ui/desconocido,now 5.2.0.11-1 amd64 [instalado, automático]
dde-session-ui/desconocido 5.2.0.11-1 i386

**Comment by SuperEffie** [comment]
Sorry for no reply for so long time, and Thanks for your feedback. Now our system has been updated to deepin v20.5 and our dde control-center version has been updated to 5.5.16.2.So far we have removed some keyboard layouts and are unable to reproduce your issue. If your issue still exists, please contact us and we will contact the developers to deal with it.

**Comment by SuperEffie** [comment]
It seems that we have fixed the problem you raised. Since you haven't answered for a long time, I will close this question first. If you have other questions, welcome to creat a new issue.Thank you~
Best wishes!
