### ISSUE TITLE
希望將虛擬桌面加到 hot corner 的選項中

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#253]
目前有「桌面」、「啟動器」、「所有視窗」、「控制中心」、「快速關閉螢幕」這幾個選項，希望可以將「虛擬桌面（multitasking view）」加入到其中。

**Comment by hualet** [comment]
@sonald @jouyouyun 或许我们可以提供一种方式让用户自定义？

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
