### ISSUE TITLE
rounditembutton.h|cpp 在哪里？

### ISSUE THREAD

**Issue by duanyao** [linuxdeepin/developer-center#2532]
dde-shutdown 引用了它，但是源文件并不存在？
https://github.com/linuxdeepin/dde-session-ui/blob/858b92a86ccfaea6cde1dfedbc8f561e2ebb8b0a/dde-shutdown/view/contentwidget.h#L39

**Comment by tsic404** [comment]
最新的dde-session-ui不再包含dde-shutdown
