### ISSUE TITLE
在 Arch Linux 安装的 dde ，无法关闭应用浮动通知。

### ISSUE THREAD

**Issue by forliuyifei** [linuxdeepin/developer-center#2533]
如题👆
*（不知道是否投错仓库）*

**Comment by BLumia** [comment]
Hi, 因为我们之前很少关注在 developer-center 仓库之外汇报的 issue，抱歉现在才答复 issue。

我现在在 Arch Linux `dde-session-shell 5.5.24-2` `dde-session-ui 5.5.6-2` 中测试，通过 `notify-send test` 发送测试通知，是可以正常关闭的。可能是在这一年的更新中已经解决了这个问题。

因为目前看上去已经不再存在这个问题了，就先关闭这个 issue 了。如果遇到近似的问题的话，欢迎开新的 issue 进行反馈。
