### ISSUE TITLE
Deepin File Manager 的 Default Size 對「電腦」這個頁面無作用（附圖）

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#254]
在「電腦」這一頁無作用，每次都必須要手動調整大小
![deepinscreenshot20170411083021](https://cloud.githubusercontent.com/assets/20014762/24887799/4ca0b8da-1e91-11e7-84f7-8d1c4110f2b9.png)

但在其他頁面都正常
![deepinscreenshot20170411083032](https://cloud.githubusercontent.com/assets/20014762/24887792/3fd64da4-1e91-11e7-8d39-47171c32dfe4.png)

**Comment by hualet** [comment]
@zccrs @dragondjf

**Comment by zccrs** [comment]
嗯，这是个bug，下个版本会修复这个问题

**Comment by JulianLai** [comment]
已修復，感謝
