### ISSUE TITLE
Chromium/Chrome Browser Notifications don't disappear

### ISSUE THREAD

**Issue by gardotd426** [linuxdeepin/developer-center#2541]
## Describe the bug
Notifications from apps or the system usually show for about 5 seconds, then fade away. However, browser notifications do not, and you can't make them go away by right-clicking like some notification daemons do, and right now the ONLY way to get the stupid popup to go away is to left-click on it, which opens your browser and goes to the notification in a new tab. This is terrible, if you're playing a game or anything like that it totally ruins it, because you can't get the notification to go away without opening your browser. And as separate bug report says, you can't disable notifications, at all, so there's no other fix. 

EDIT: This does not happen with Firefox, only Chrome/Chromium
## To Reproduce
1. Enable notifications in Chromium, Chrome, Brave Browser, etc. Give a site (e.g. YouTube, GMail) permission to send notifications.
2. Wait for a notification, or if you have GMail notifications enabled, send yourself an email.
3. See the new notification popup.
4. Wait. See error. It ain't going away. Ever. Not unless you reboot, log out, or left-click the notification, which opens your browser whether you want to open it or not.
-->

## Expected behavior
As with all other notifications (both from other apps and system utilities like network connections, etc.), the notification should appear for about 5 seconds, then go away. 
## Screenshots
This gif is my current desktop, this notification has been sitting there for 15 minutes. I've actually gotten other notifications since then, but they've disappeared like they're supposed to.
![Screen Capture_dde-desktop_20200526031647](https://user-images.githubusercontent.com/54234607/82871462-9ca30580-9eff-11ea-9fcd-5461a6f86e5d.gif)

### Distro & Version
Arch Linux, kernel 5.7.0-rc1-1-tkg-pds

### Related package version
`pacman -Q | egrep "dde|deepin"
```
deepin-account-faces 1.0.11-1
deepin-anything 5.0.1-2
deepin-anything-arch 5.0.1-82
deepin-api 5.1.11.1-1
deepin-boot-maker 5.4.8-1
deepin-calculator 5.5.10-1
deepin-calendar 5.6.3-1
deepin-clone 5.0.3-1
deepin-clutter 1.26.2-2
deepin-cogl 1.22.5-3
deepin-community-wallpapers 1:1.7.7-1
deepin-control-center 5.1.0101.0.20200427-1
deepin-daemon 5.10.0099.2-1
deepin-desktop-base 2:2020.04.12.2-1
deepin-desktop-schemas 5.5.0.1-1
deepin-dock 5.1.0.9-1
deepin-draw 5.8.0.19-1
deepin-editor 5.6.9-1
deepin-file-manager 1:5.1.1.25-1
deepin-gtk-theme 17.10.11-1
deepin-icon-theme 2020.05.21-1
deepin-image-viewer 5.6.3.2-1
deepin-kwin 5.0.14.1-3
deepin-launcher 5.2.0.0-1
deepin-menu 5.0.1-1
deepin-metacity 3.22.24-1
deepin-movie 1:5.7.6.29-1
deepin-music 6.0.1.8-1
deepin-mutter 3.20.38-4
deepin-network-utils 5.1.0.0-1
deepin-picker 5.0.6-1
deepin-polkit-agent 5.1.0-2
deepin-polkit-agent-ext-gnomekeyring 0.1.0-1
deepin-qt-dbus-factory 5.1.0.1-1
deepin-qt5dxcb-plugin 5.0.11-1
deepin-qt5integration 5.1.0.1-2
deepin-reader 5.6.4-1
deepin-screen-recorder 5.8.0.11-2
deepin-screensaver 5.0.3-1
deepin-screensaver-pp 0.0.4-1
deepin-session-shell 5.0.0098.0-2
deepin-session-ui 5.1.0101.0-1
deepin-shortcut-viewer 5.0.2-1
deepin-sound-theme 15.10.6-1
deepin-system-monitor 5.6.2-1
deepin-terminal 5.0.4.1-1
deepin-turbo 0.0.3-1
deepin-wallpapers 1:1.7.7-1
deepin-wm 1.9.38-4
startdde 5.3.0.1-3
```

### Additional context
Like I said, there are tons of instances where this can just ruin your day. Some games become completely unplayable when there's another Window open or taking focus, some don't allow alt-tabbing, and even if that weren't the case, it's ridiculous that you HAVE to open your browser just for a stupid notification to go away, especially when you can't disable notifications at all. Right now, Deepin Desktop Environment says "You're getting notifications, whether you like it or not, and you're also opening them, whether you like it or not. Even if the notification has to sit there until the end of time, it's staying there till you click it."

**Comment by justforlxz** [comment]
same https://github.com/linuxdeepin/developer-center/issues/2519
