### ISSUE TITLE
我需要修改登陆界面,但是无法编译lightdm-deepin-greeter,请问还有其他方式吗?

### ISSUE THREAD

**Issue by Nethgul** [linuxdeepin/developer-center#2544]
如题,我需要将登陆修改为刷卡登陆,但是lightdm-deepin-greeter工程在QT中无法正常编译,我已经按照要求安装了所有的依赖项,但是依然无法编译通过,缺少很多头文件,不知道在哪里找,请问还有别的方式可以修改登陆时的界面和流程吗?我尝试过在PAM服务中弹出界面,但是界面总是无法正常弹出!请问有什么办法能够实现刷卡登陆呢? 十分感谢!

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/developer-center/issues/2543
