### ISSUE TITLE
不应在 Wifi 正常连接时不断扫描热点列表

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#2549]
目前 dde-daemon 的 network 模块会每 20 秒扫描一次 AP，扫描时网卡会切换 channel 造成网络波动，严重影响稳定性。

应在用户请求时扫描。

**Comment by hualet** [comment]
这个问题要尽早修复吧

**Comment by justforlxz** [comment]
The issue has been fixed to scan only when the AP list is open.
