### ISSUE TITLE
玻璃特效顏色變黑，畫面撕裂

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#255]
有時使用到一半，畫面會閃動一下，然後 dock 和控制中心的玻璃顏色會變黑，滾動時會有撕裂的問題。
OS: antergos (arch)
GPU: AMD RX460

正常顏色
![normal](https://cloud.githubusercontent.com/assets/20014762/24897494/ab42f382-1ecb-11e7-9878-e8c5b04e8d05.png)

變黑伴隨著撕裂
![black](https://cloud.githubusercontent.com/assets/20014762/24897506/b7e2a3a8-1ecb-11e7-8ed5-48965d4d1dd0.png)

**Comment by zccrs** [comment]
确认一下变黑之后所使用的窗关是deepin-wm还是deepin-metacity

**Comment by JulianLai** [comment]
@zccrs 請問該如何確認呢？
話說要等到下次發生才能夠測試了

**Comment by zccrs** [comment]
那你在变黑之后是怎样再次恢复毛玻璃效果的呢？重启吗？

**Comment by JulianLai** [comment]
@zccrs 註銷再登入

**Comment by zccrs** [comment]
嗯，初步猜测是deepin-wm在使用过程中崩溃了。可以着重注意一下是什么样的行为引起的这个问题。

**Comment by amazingfate** [comment]
deepin-wm的窗口切换是有特效的
super+shift+tab切换窗管看能不能恢复毛玻璃

**Comment by JulianLai** [comment]
@amazingfate 原來可以這樣自由開關啊，關閉了之後就出現剛剛那種黑黑並撕裂的狀況了

**Comment by zccrs** [comment]
基本可以确定是3D窗关崩溃了，常出现吗？

**Comment by sonald** [comment]
@JulianLai 麻烦安装一下systemd-coredump，下次崩溃（就是所谓的变黑后）后，coredumpctl 看看最下面一个是不是deepin-wm，是的话，用coredumpctl gdb 进去，输入bt获取崩溃栈，把输出贴一下看看

**Comment by JulianLai** [comment]
@zccrs 出現滿多次的
@sonald 了解了

**Comment by JulianLai** [comment]
已經很久沒出現，至於撕裂部份可經由設定 20-amdgpu.conf 解決
