### ISSUE TITLE
系统通知缺陷

### ISSUE THREAD

**Issue by RichieChoo** [linuxdeepin/developer-center#2552]
系统通知在关闭之后，会慢慢移入主屏幕上方的扩展屏幕上，然后继续移动到扩展屏幕顶部再消失，每个提示都是，具体如下图：
![截图录屏_选择区域_20200817144130](https://user-images.githubusercontent.com/17178139/90365229-11698400-e098-11ea-8f1b-2c9243619b54.png)

**Comment by babyfengfjx** [comment]
非常感谢您的反馈，抱歉我们长时间未进行沟通，当前问题我们在最新版本中发现正常，我们先关闭此issue,如果该问题仍旧存在，或者有新的问题，还请随时反馈给我们～
