### ISSUE TITLE
dde-session-daemon logging warning in journald log every second, high CPU usage

### ISSUE THREAD

**Issue by taolin96** [linuxdeepin/developer-center#2553]
watching the journald log  using
`journalctl -f`
and warning logged every second

> Sep 07 11:38:20 paymlap451.internal.etsl.co.nz daemon/network[1532]: manager_device.go:395: failed to get interface info: route ip+net: no such network interface
Sep 07 11:38:21 paymlap451.internal.etsl.co.nz daemon/network[1532]: manager_device.go:395: failed to get interface info: route ip+net: no such network interface
Sep 07 11:38:22 paymlap451.internal.etsl.co.nz daemon/network[1532]: manager_device.go:395: failed to get interface info: route ip+net: no such network interface
Sep 07 11:38:23 paymlap451.internal.etsl.co.nz daemon/network[1532]: manager_device.go:395: failed to get interface info: route ip+net: no such network interface
Sep 07 11:38:24 paymlap451.internal.etsl.co.nz daemon/network[1532]: manager_device.go:395: failed to get interface info: route ip+net: no such network interface
Sep 07 11:38:25 paymlap451.internal.etsl.co.nz daemon/network[1532]: manager_device.go:395: failed to get interface info: route ip+net: no such network interface
Sep 07 11:38:26 paymlap451.internal.etsl.co.nz daemon/network[1532]: manager_device.go:395: failed to get interface info: route ip+net: no such network interface
Sep 07 11:38:27 paymlap451.internal.etsl.co.nz daemon/network[1532]: manager_device.go:395: failed to get interface info: route ip+net: no such network interface
Sep 07 11:38:28 paymlap451.internal.etsl.co.nz daemon/network[1532]: manager_device.go:395: failed to get interface info: route ip+net: no such network interface
Sep 07 11:38:29 paymlap451.internal.etsl.co.nz daemon/network[1532]: manager_device.go:395: failed to get interface info: route ip+net: no such network interface
Sep 07 11:38:30 paymlap451.internal.etsl.co.nz daemon/network[1532]: manager_device.go:395: failed to get interface info: route ip+net: no such network interface
Sep 07 11:38:31 paymlap451.internal.etsl.co.nz daemon/network[1532]: manager_device.go:395: failed to get interface info: route ip+net: no such network interface
Sep 07 11:38:32 paymlap451.internal.etsl.co.nz daemon/network[1532]: manager_device.go:395: failed to get interface info: route ip+net: no such network interface
Sep 07 11:38:33 paymlap451.internal.etsl.co.nz daemon/network[1532]: manager_device.go:395: failed to get interface info: route ip+net: no such network interface

and high CPU usage
`top`
and found the 3 process below(dde-session-daemon, NetworkManager,dde-dock) always running high CPU (from 15% to 55%) all the time, and notice the battery drain faster 
![image](https://user-images.githubusercontent.com/7938311/92337791-0d151180-f100-11ea-98e5-7decd6280ec8.png)

**Comment by babyfengfjx** [comment]
Thanks for your feedback,we are very sorry that we did not communicate for a long time, thank you very much for your feedback, the current issue we found in the latest version of normal, we first close this issue, if there are new issue later,  please feedback to us.
