### ISSUE TITLE
UOS专业版1021和deepin V20锁屏以后解锁发现没有声音

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#2557]
## 缺陷描述

这个问题很久以前我在UOS上面发现，https://bbs.deepin.org/forum.php?mod=viewthread&tid=194685&extra=
这个问题我在2020年5月19号在deepin论坛上面报过，显示已记录，
现在过去了差不多3个月，还是没有修复
“系统锁定如果时间比较长的话，解锁以后会发现没有声音，查原因是声音输出从模拟耳机自己改成了HDMI2，这明显不对，我从来都不用HDMI2，系统自动给我改成了HDMI2”

### 发行版以及版本

deepin V20

**Comment by BLumia** [comment]
没有进一步问题就先关闭了。如果你在当前能获取到的最新的版本（目前是 deepin v20.5）上仍能复现这类问题的话，可以再开个新的 issue 反馈，我们会跟进处理。感谢！
