### ISSUE TITLE
Disabling border corners?

### ISSUE THREAD

**Issue by Toop-o** [linuxdeepin/developer-center#257]
Hello. How would one remove the rounded corners in Deepin?

I took a look at the code and set border-radius'es to 0px in every Deepin related package, but that doesn't quite cut it, thumbnails and backgrounds are still drawn with the default radius.

Also saw corner related options in com.deepin.wrap.pantheon.desktop.gala.mask-corners, but it doesn't seem that the wm would be reading those.

Is this hardcoded? If yes, could you please tell me what are the functions called?

**Comment by hualet** [comment]
@zccrs

**Comment by zccrs** [comment]
Yeah, It's hardcoded. See the "qt5integration" project: [https://github.com/linuxdeepin/qt5integration](https://github.com/linuxdeepin/qt5integration)

**Comment by Toop-o** [comment]
Ooh, there it is! Thanks!
