### ISSUE TITLE
查找输入框  没有获得焦点

### ISSUE THREAD

**Issue by jiangzc** [linuxdeepin/developer-center#2571]
系统版本：deepin 1030

问题描述：在查找输入框内选择一行文字后，鼠标移开查找输入框后释放，查找输入框没有获得焦点。

如何复现：鼠标移动到查找输入框右边，按下鼠标左键，从右向左选择文字，鼠标移动到输入框外，松开鼠标左键。结果查找输入框没有获得焦点。

复现频率：100%

注意：当文本框的边框高亮时，文本框才获得焦点

https://user-images.githubusercontent.com/13901512/105634465-044b8f00-5e99-11eb-9559-9fd7e1989d35.mp4

**Comment by BLumia** [comment]
这个问题应该在目前可获取到的最新版本中已经修复了，我这边在 `deepin-editor 5.10.14-1` 不再能复现此问题，可以更新下再试试看。

如果仍然有遇到的话，欢迎开新的 issue 进行反馈~
