### ISSUE TITLE
打开 conf 文件失败

### ISSUE THREAD

**Issue by socay1** [linuxdeepin/developer-center#2572]
### 问题描述：
打开 dkms.conf 文件失败，提示无效文件，如图：
![image](https://user-images.githubusercontent.com/23112809/105856279-f6a12100-5fe0-11eb-9d60-58dd313b7eb2.png)
环境：Deepin GNU/Linux 20.1

dkms.conf 文件内容如下：
![image](https://user-images.githubusercontent.com/23112809/105859698-bd6ab000-5fe4-11eb-90b3-a9719ec7c022.png)

### 问题分析：
定位到是 `bool Utils::isMimeTypeSupport(const QString &filepath)` 函数实现的问题：
1. 该函数首先会调用 `QMimeDatabase().mimeTypeForFile(filepath).name()` 获取 mimeType
2. 如果获取到的 mimeType 是 `text/*`，则认为是文本编辑器所支持的打开类型
3. 否则，在一个已知的列表中查找，看mimeType是否在已知列表。

对于文件上面的 dkms.conf 文件，其第一行内容为 `PACKAGE_VERSION="1.0"`，被识别出来的类型为：`application/x-pak`，不属于 `text/*` 开头，也不在已知的支持列表中。
所以最终函数返回 false，认为是无效的文件类型。

**Comment by BLumia** [comment]
Hi, 抱歉现在才予以回复。

目前 `dkms.conf` 以及 `.gitignore` 在 deepin v20.4 社区版，deepin-editor 5.10.14-1 版本中已都能够正常编辑了，于是就先关掉这个 issue 了。

我们最近在统一处理过于陈旧的未及时答复的 issue（详可参见目前的置顶 issue），如果你在当前所能更新到的最新版本仍会遇到近似的问题，请考虑开个新 issue 并提供下相关详情，以便我们进一步处理问题哈~
