### ISSUE TITLE
没有权限的提示图标错误

### ISSUE THREAD

**Issue by zoze0** [linuxdeepin/developer-center#2576]
## 缺陷描述

编辑器没有权限打开文件时的提示图标显示错误
## 期望行为

显示✖️，而不是✔️
## 截图

![111101](https://user-images.githubusercontent.com/20562449/90899008-dd74c280-e3f9-11ea-9ed0-6e9e2f01d8e3.png)

### 发行版以及版本

deepin20

**Comment by BLumia** [comment]
我在 `deepin-editor 5.10.14-1` 进行了测试，这个提示应该已经移除了，这个问题我就先关掉了。

您可以尝试更新您的软件包然后看下是否仍有类似问题，如果有的话可以开个新的 issue 进行汇报，感谢支持！
