### ISSUE TITLE
文本编辑器会在用户目录下创建很多的.rmlock

### ISSUE THREAD

**Issue by weclix** [linuxdeepin/developer-center#2579]
环境：arch+dde
deepin-editor版本：5.9.0.51
操作：清空~/.config/deepin/deepin-editor目录，在任意位置创建无格式的文本文件，然后使用deepin-editor多次打开。
现象：首次打开文本文件，deepin-editor会在~/.config/deepin/deepin-editor目录中创建名称为“config.conf”的文件，然后关闭文本编辑器，deepin-editor又会在该目录下创建“config.conf.lock”文件；再次打开任意文本文件，此时deepin-editor不会创建文件，然后关闭文本编辑器，deepin-editor会创建名为“config.conf.lock.rmlock”的文件；第三次使用deepin-editor打开任意文本文件然后关闭，deepin-editor会在目录下创建“config.conf.lock.rmlock.rmlock”文件依此类推。使用deepin-editor打开过多少次文件就会在~/.config/deepin/deepin-editor目录创建多少文件。@rekols
![Record_Navigator_20210713100127](https://user-images.githubusercontent.com/42332005/125379407-0d86d480-e3c3-11eb-89c9-f01295d0b04e.gif)
![录屏_dde-file-manager_20210801121715](https://user-images.githubusercontent.com/42332005/127759096-e7b7dd44-1181-40a7-8017-eb4da98a6cdf.gif)

**Comment by SuperEffie** [comment]
感谢您的反馈，目前deepin v20.5上deepin-editor包的版本是5.10.14-1。我们按照相同的步骤操作了一遍，~/.config/deepin/deepin-editor始终只创建了一个config.conf文件。没有复现到您issue里描述的现象，若您的问题依然存在，可以与我们取得联系。我们会联系研发人员定位解决这个问题。

**Comment by weclix** [comment]
问题已解决
