### ISSUE TITLE
在编译deepin-editor时候遇见的问题

### ISSUE THREAD

**Issue by XXTX-TOP** [linuxdeepin/developer-center#2582]
`/home/xxx/DDE/deepin-editor/src/editor/showflodcodewidget.cpp:131:64: warning: ‘int QFontMetrics::width(const QString&, int) const’ is deprecated: Use QFontMetrics::horizontalAdvance [-Wdeprecated-declarations]
  131 |     int textWidth = m_pContentEdit->fontMetrics().width(strText) + 10;
      |                                                                ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h:50,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qframe.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QFrame:1,
                 from /usr/include/libdtk-5.2.2/DCore/../DWidget/dframe.h:28,
                 from /usr/include/libdtk-5.2.2/DCore/../DWidget/DFrame:1,
                 from /home/xxx/DDE/deepin-editor/src/editor/showflodcodewidget.h:23,
                 from /home/xxx/DDE/deepin-editor/src/editor/showflodcodewidget.cpp:21:
/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontmetrics.h:106:9: note: declared here
  106 |     int width(const QString &, int len = -1) const;
      |         ^~~~~
make[1]: *** [CMakeFiles/Makefile2:139：src/CMakeFiles/deepin-editor.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
/home/xxx/DDE/deepin-editor/src/controls/replacebar.cpp: In constructor ‘ReplaceBar::ReplaceBar(QWidget*)’:
/home/xxx/DDE/deepin-editor/src/controls/replacebar.cpp:62:20: error: ‘class Dtk::Widget::DIconButton’ has no member named ‘setEnabledCircle’; did you mean ‘setEnabled’?
   62 |     m_closeButton->setEnabledCircle(true);
      |                    ^~~~~~~~~~~~~~~~
      |                    setEnabled
make[2]: *** [tests/CMakeFiles/deepin-editor-test.dir/build.make:548：tests/CMakeFiles/deepin-editor-test.dir/__/src/controls/replacebar.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:274：tests/CMakeFiles/deepin-editor-test.dir/all] 错误 2
make: *** [Makefile:149：all] 错误 2
`
请问这个怎么办？
是setEnabledCircle 的问题吗？

**Comment by BLumia** [comment]
DTK 应用的 master 分支是开发分支，开发分支可能会依赖其它开发分支的接口。如果只是希望编译的话可以考虑先切换到你所使用的发行版所提供的 tag 再编译，如果是希望构建最新版再考虑把依赖（比如 DTK）也进行更新。

很久没有得到进一步的回复，就暂时先关掉了。若仍有问题建议开新的 issue 或者 discussion~
