### ISSUE TITLE
系统监视器数据不准确

### ISSUE THREAD

**Issue by weclix** [linuxdeepin/developer-center#2586]
运行环境：ArchLinux+dde桌面
软件版本：5.8.7
操作：打开chromium或者firefox浏览器，然后打开系统监视器查看打开软件的资源占用情况。
预期：在应用tab中可以看到用户打开应用的内存和cpu占用情况
结果：无法直接看到用户打开应用的资源占用，必须阿经tab切换到当前用户进程或者所有进程中搜索查看才能看到。
![Record_deepin-system-monitor_20210709113728](https://user-images.githubusercontent.com/42332005/125020151-e5d5fa80-e0aa-11eb-952d-1a6ee0ec10a2.gif)

**Comment by SuperEffie** [comment]
很感谢您的反馈。现在我们社区的系统已经更新至deepin v20.5版本，系统监视器已经更新至5.9.17版本，在最新版本的系统显示器上，数据都校验过是准确的。抱歉无法复现您issue中的问题，请问您的问题是否依然存在呢？若存在，请联系我们，我们会帮助您解决问题。

**Comment by BLumia** [comment]
我在 Arch Linux `deepin-system-monitor 5.8.14-2` 下测试也是没问题的，是个老 issue 了，可能之前存在问题但在版本迭代中得以修复了。您可以尝试下更新系统软件包然后再看看是否仍会出现这个问题，如果仍然出现的话可以开个新的 issue 与我们进行反馈，我们会根据您的最新反馈情况来定位问题。感谢！

**Comment by weclix** [comment]
阿sir,问题并没有解决,chrome/chromium的资源占用情况依旧不准确.相同的情况出现在vscode中
![图片](https://user-images.githubusercontent.com/42332005/165688621-81f09320-cb02-4bec-8a97-743cd8380535.png)
![图片](https://user-images.githubusercontent.com/42332005/165689405-4c0e3478-7199-4171-bf7d-9a71025f7062.png)

**Comment by BLumia** [comment]
> 阿sir,问题并没有解决,chrome/chromium的资源占用情况依旧不准确.相同的情况出现在vscode中 ![图片](https://user-images.githubusercontent.com/42332005/165688621-81f09320-cb02-4bec-8a97-743cd8380535.png) ![图片](https://user-images.githubusercontent.com/42332005/165689405-4c0e3478-7199-4171-bf7d-9a71025f7062.png)

开个新的 issue 进行反馈吧，这样跟进问题会更方便一些，毕竟旧问题和新问题的现象可能相似，但环境和诱因可能是不同的，有必要的话可以在新的 issue 中链接到旧的 issue 里。
