### ISSUE TITLE
系统监视器：uos v20上没法编译

### ISSUE THREAD

**Issue by wslyx** [linuxdeepin/developer-center#2587]
![image](https://user-images.githubusercontent.com/19238483/156726452-951841ea-b87b-46a2-acd0-ca7d574af8a2.png)

**Comment by BLumia** [comment]
这个，字面意思呀，需要的依赖没装齐，建议看下 README 安装相应依赖（也建议直接使用 `apt-get build-dep deepin-system-monitor` 安装构建依赖）

**Comment by BLumia** [comment]
验证了一下，在目前的 deepin v20.4 中拉取 deepin-system-monitor `master` 分支最新（验证时的版本是 https://github.com/linuxdeepin/deepin-system-monitor/commit/c645dc22745b4708068794de6fc2ba6c21840573 ）提交，是可以直接构建的。参考构建步骤（很常规，没什么特别的）

``` shell
$ sudo apt build-dep deepin-system-monitor # 获取构建依赖
$ git clone https://github.com/linuxdeepin/deepin-system-monitor && cd deepin-system-monitor # 获取源码
$ mkdir build && cd build
$ cmake ../
$ cmake --build ./ # 构建，当然你也可以直接使用 make 或 ninja
$ ./src/deepin-system-monitor # 构建完毕的二进制文件位置
```

由于无法复现于是就先关掉 issue 了。如果您仍有相关问题的话，欢迎在 [discussion 讨论版里的 QA 板块](https://github.com/linuxdeepin/developer-center/discussions/categories/q-a-%E9%97%AE%E7%AD%94%E6%9D%BF%E5%9D%97) 提问~

**Comment by wslyx** [comment]
> 验证了一下，在目前的 deepin v20.4 中拉取 deepin-system-monitor `master` 分支最新（验证时的版本是 [linuxdeepin/deepin-system-monitor@c645dc2](https://github.com/linuxdeepin/deepin-system-monitor/commit/c645dc22745b4708068794de6fc2ba6c21840573) ）提交，是可以直接构建的。参考构建步骤（很常规，没什么特别的）
> 
> ```shell
> $ sudo apt build-dep deepin-system-monitor # 获取构建依赖
> $ git clone https://github.com/linuxdeepin/deepin-system-monitor && cd deepin-system-monitor # 获取源码
> $ mkdir build && cd build
> $ cmake ../
> $ cmake --build ./ # 构建，当然你也可以直接使用 make 或 ninja
> $ ./src/deepin-system-monitor # 构建完毕的二进制文件位置
> ```
> 
> （注：由于开发分支可能会用到它依赖的软件包的开发分支版本，所以开发分支不一定总是能直接编译，所以如果是**一般情况**，是建议先切换到一个已发布版本的 tag 上再进行编译的）
> 
> 由于无法复现于是就先关掉 issue 了。如果您仍有相关问题的话，欢迎在 [discussion 讨论版里的 QA 板块](https://github.com/linuxdeepin/developer-center/discussions/categories/q-a-%E9%97%AE%E7%AD%94%E6%9D%BF%E5%9D%97) 提问~

谢了兄弟！
