### ISSUE TITLE
在高分屏幕下左侧图标模糊

### ISSUE THREAD

**Issue by maicsschen** [linuxdeepin/developer-center#2591]
图片：
https://bbs.deepin.org/forum.php?mod=redirect&goto=findpost&ptid=197266&pid=740374&fromuid=90159

**Comment by babyfengfjx** [comment]
可以看下最新V20.8版本这个模糊问题是否得到解决。

**Comment by BLumia** [comment]
我这边验证 v20.8 以及 Archlinux 目前的版本（deepin-launcher 5.6.1-1）是没问题的，就先关闭了。如果后续发现仍有此问题的话，可以开个新的帖子附上版本号反馈，我们会跟进确认和修复 :)
