### ISSUE TITLE
Defect accessibility and user friendly in open menu START.

### ISSUE THREAD

**Issue by korenevskiy** [linuxdeepin/developer-center#2592]
![scrn](https://user-images.githubusercontent.com/6898474/95181110-879e8300-07cb-11eb-95bf-572cb301922c.png)

The angular end zone must also open mouse the menu START. This is accessibility and user friendly. 
The user should essentially be able to open the menu with one mouse stroke to the corner of the screen.
The user may have a problem with the mouse sensor, the mouse may be broken. The user can be with poor vision, the user can be a disabled person or a pensioner.
The user may have poor desk coverage on which the mouse does not work well.
Why should the user closely aim the mouse cursor at the button each time?
30% of the population will suffer because of this: pensioners, disabled people.
...
Other taskbar buttons should also open when the mouse is at the bottom of the screen.

**Comment by meiyixiang** [comment]
The rounded corner problem community has been optimized so you can adjust the rounded corner size

**Comment by korenevskiy** [comment]
> The rounded corner problem community has been optimized so you can adjust the rounded corner size

What does setting the rounding size have to do with accessibility? The extreme pixel must be active at any rounding.
