### ISSUE TITLE
dde-launcher: Fullscreen Background Bug

### ISSUE THREAD

**Issue by N1coc4colA** [linuxdeepin/developer-center#2593]
I spoted the bug yesterday, it is simple and works on latest shiped version of DDE (so 1003B of Deepin, and I updated to last version yesterday). So in fullscreen, in category or list mode, I have an old background image used. I need to change the background to the curent one (reset my wallpaper) to get it updated. And this is recursive, every startup, or login/logout. I'm not sure if it's just from my own configuration but as I have it, some might have it too...

**Comment by babyfengfjx** [comment]
I wonder if the issue is solved on the latest version?

**Comment by babyfengfjx** [comment]
Because the issue has been left for too long, perhaps the problem has been solved, we first close the processing, if there are new problems thanks to submit at any time.
