### ISSUE TITLE
关于列表滚动的问题

### ISSUE THREAD

**Issue by LTreeshu** [linuxdeepin/developer-center#2594]
弹框模式下，列表滚动到3分之一处便会发生卡顿，进行了109次实验，平均的卡顿时间是6秒，希望加以优化，20.1版本仍有此现象。

**Comment by BLumia** [comment]
抱歉现在才予以回复，我们之前很少关注在 developer-center 外开启的 issue。

我现在在 deepin v20.4，dde-launcher 5.5.6-1 上无法复现你的问题（不清楚弹窗模式指的是不是就是非全屏模式的启动器），无论是全屏还是非全屏均未见卡顿现象。如果您提到的问题是 bug 或者优化问题的话，兴许在最新版本中已涵盖了相应的修复。于是目前就先关掉这个 issue 了。

如果你在目前的最新版本仍然有遇到近似的问题的话，请考虑开个新的 issue 并提供一些详情，以便我们复现问题并进一步跟进问题哈~
