### ISSUE TITLE
关于格式化字符串时单引号/双引号的本地化处理

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/developer-center#26]
刚刚 @Arthur2e5 提到了这个问题，格式化字符串时，某些地方的字符串变量中可能包含 单引号/双引号，为了更好的适配国际化，应当提供一个通用的 quote 方法来做下包装，可以参考 Gnulib: [Quoting](https://www.gnu.org/software/gnulib/manual/html_node/Quoting.html)。

@derekdai @snyh 

https://github.com/linuxdeepin/dde-daemon/issues/5#issuecomment-173079402

**Comment by justforlxz** [comment]
This question has not been answered for too long and will be closed. If there is a need to continue the discussion, it will be reopened.
