### ISSUE TITLE
Change the backgroud without deepin-file-manager

### ISSUE THREAD

**Issue by Urgau** [linuxdeepin/developer-center#260]
Hello,

I'm on ArchLinux and I have uninstall deepin-file-manager because I hate it but after the uninstallation I can't not anymore change the background. Can you please fix this without force the installation of deepin-file-manager. Thanks you.

**Comment by hualet** [comment]
deepin-file-manager provides a desktop program, but settings background is not desktop related, it's WM related. Which WM are you using? 

@felixonmars  try this for me ?

**Comment by Urgau** [comment]
I use :

- deepin-wm 1.9.12-1
- deepin-wm-switcher 1.1.0-1

But I thought it's deepin-file-manager because it's after her uninstallation that I can't not anymore change the background.

**Comment by sonald** [comment]
you can use deepin-image-viewer to change background

**Comment by Urgau** [comment]
@sonald Yes, but I don't use deepin-image-viewer and the problem is not here. Normally I can change the background without any apps but It's didn't work with me because the context menu in the desktop doesn't appear.

**Comment by hualet** [comment]
Finally I understand what you are talking about 😅 , the dde-desktop program installed along with dde-file-manager is needed so that you can right click on it and show the context menu.

**Comment by hualet** [comment]
If you just want the background setting program, you can find a binary called dde-wallpaper-chooser which is installed by the package deepin-session-ui in Arch.

**Comment by Urgau** [comment]
Okay thanks, and is it possible to put a option for people which don't have deepin-file-manager because in Arch deepin-file-manager is not required.

**Comment by hualet** [comment]
I don't know, dde-desktop and dde-file-manager are in different packages in deepin, but maybe there're packaging rules or something that makes it impossible to do so ? @felixonmars

**Comment by felixonmars** [comment]
I think @Urgau is asking for a visual option to set wallpaper for those who don't have deepin-file-manager installed. I don't understand your question @hualet

**Comment by Urgau** [comment]
@felixonmars Yes, I would like.
