### ISSUE TITLE
列表滚动超级卡

### ISSUE THREAD

**Issue by thomas-art** [linuxdeepin/developer-center#2603]
无论使用intel核显还是nvdia独显，列表滚动都出奇的卡顿，至少要10秒找到应用并打开，强烈建议优化一下，打开启动器也暂时没有任何动画，启动器真的是deepin中最大的败笔了

**Comment by BLumia** [comment]
是个很陈旧的 issue 了，抱歉我们之前很少关注 developer-center 之外所汇报的 issue，现在才答复您。

在自此 issue 汇报后到现在，deepin 也迭代了不少版本，launcher 也有相应的优化，可以考虑更新到目前最新版本（deepin v20.5）试试看。这个 issue 就先关掉了，如果仍有遇到问题的话可以开启新的 issue 进行反馈，同时会需要附带一些相关的信息，例如出问题的版本，launcher 的版本，您目前所使用系统的大致环境之类，以便我们进一步核对问题。
