### ISSUE TITLE
启动器无法启动

### ISSUE THREAD

**Issue by zkitefly** [linuxdeepin/developer-center#2605]
**点击左下方按钮无法打开启动器，点击之后dde-dock会无法点击，只有在任务管理器中关闭dde-dock之后重启才能使用**

在终端执行 `dde-launcher`或 `dde-launcher --show`指令也无法启动

输入后终端输出了以下日志:

```
terminate called after throwing an instance of 'std::bad_alloc'
what():  std::bad_alloc
已放弃
```

![图片.png](https://storage.deepin.org/thread/202202120902502205_图片.png)

为此我卸载了dde-launcher重新安装，结果还是不行

![图片.png](https://storage.deepin.org/thread/202202120852309843_图片.png)

我直接去/usr/bin打开dde-launcher，但还是输出一样的日志

请问这是怎么回事,我都不能启动软件?!（虽然我可以去/usr/share/applications内打开，但不方便）

QAQ!?

**Comment by BLumia** [comment]
关联一下： https://github.com/linuxdeepin/developer-center/issues/2604

**Comment by BLumia** [comment]
抱歉因为我们之前很少留意 developer-center 之外汇报的 issue，所以现在才回复。

目前在 deepin v20.4 dde-launcher 5.5.6-1 中，这个问题应该已经不再存在了。你可以尝试使用 `dde-launcher --show` 来显示 launcher。来验证是否仍然存在。

如果你仍然有遇到这样的问题对话，请考虑开个新的 issue 并附带相关信息，我这边会协助您进一步确认问题~
