### ISSUE TITLE
[bug report]20.4更新后无法使用方向键选中应用

### ISSUE THREAD

**Issue by shenmo7192** [linuxdeepin/developer-center#2606]
之前的版本中搜索后直接用方向下来选择应用，现在必须用鼠标了，非常难受

https://www.bilibili.com/video/BV16Z4y1r7Dz/

**Comment by babyfengfjx** [comment]
该问题确认在部分设备上可能会存在，已经提交优化了，如果有新的进展将会及时答复,预计在20.5的内测版本中会提交修复。

**Comment by shenmo7192** [comment]
> 该问题确认在部分设备上可能会存在，已经提交优化了，如果有新的进展将会及时答复,预计在20.5的内测版本中会提交修复。

补充：这时候按上下再点击回车是会实际打开应用的，是按照没搜索之前的排序打开的，也就是说光标在搜索之前的页面出现了

**Comment by babyfengfjx** [comment]
> > 该问题确认在部分设备上可能会存在，已经提交优化了，如果有新的进展将会及时答复,预计在20.5的内测版本中会提交修复。
> 
> 补充：这时候按上下再点击回车是会实际打开应用的，是按照没搜索之前的排序打开的，也就是说光标在搜索之前的页面出现了

OK ，到时候更新后，可能还需要您这边核实一下效果咯~

**Comment by BLumia** [comment]
v20.5 已推送，我这边测试是没问题的了。@shenmo7192 试试效果？

**Comment by shenmo7192** [comment]
> v20.5 已推送，我这边测试是没问题的了。@shenmo7192 试试效果？

暂时没出现问题。原来也是随机出现。但是更新后确实没再复现了

**Comment by BLumia** [comment]
好的，那就先关闭这个 issue 了。如果后续再遇到的话开新的 issue 反馈就好~
