### ISSUE TITLE
模糊效果渲染范围错误 / Arch

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#2609]
如图，所有的模糊效果范围均出现了偏移。
![2020-05-02-213149-abc29f](https://user-images.githubusercontent.com/1006477/80865481-5bcb1e80-8cbc-11ea-9466-283391b012bd.png)

**Comment by justforlxz** [comment]
可以吧dde-kwin的blur插件删了，用kwin自己的。
