### ISSUE TITLE
[dde-control-center] Boot menu doesn't work on Archlinux

### ISSUE THREAD

**Issue by Urgau** [linuxdeepin/developer-center#261]
Hello,

I'm on Archlinux and I have see that he have an starting menu (boot menu) but it doesn't display anything. Is it implemented ? What's the problem ?

**Comment by hualet** [comment]
@felixonmars remove this on Arch?

**Comment by felixonmars** [comment]
From the look of its code I still don't know why it's not working. But if you want to remove this on Arch, please provide a flag like "DISABLE_SYS_UPDATE" so we can do that.

**Comment by Urgau** [comment]
But it would be nice if it works, it is a convenient feature.

**Comment by jouyouyun** [comment]
No `update-grub` in arch, replace with `grub-mkconfig -o /boot/grub/grub.cfg`.
 @electricface fix it in `grub2`.

**Comment by electricface** [comment]
fix in https://cr.deepin.io/#/c/22356/

**Comment by jouyouyun** [comment]
Not access the file `/boot/grub/grub.cfg`.

**Comment by SalahAdDin** [comment]
I'll test provisional solution tomorrow; yes, I see the function, is very good, going to be great make works this function.

**Comment by SalahAdDin** [comment]
It works, i test it and is wonderful! It needs use `sudo` for works.

**Comment by SalahAdDin** [comment]
![20170515_011541](https://cloud.githubusercontent.com/assets/5034215/26039195/613d3314-3920-11e7-80ec-2a18f78ef4ea.jpg)

**Comment by JulianLai** [comment]
I still need to type `sudo grub-mkconfig -o /boot/grub/grub.cfg`, will it be fixed??

**Comment by SalahAdDin** [comment]
@JulianLai I'm waiting for it also.

**Comment by SalahAdDin** [comment]
With the las updates i have the next bug: https://github.com/linuxdeepin/dde-session-ui/issues/15.

**Comment by zaplo00** [comment]
It was kind of unexpected to see bootmanager replaced when i installed deepin on Arch (syslinux package overwrote grub..). I think it's better to not include bootmanager in arch, when you just want to install desktop.

**Comment by SalahAdDin** [comment]
@zaplo00 why?

**Comment by hualet** [comment]
Arch DDE dropped the boot settings part, closing.

**Comment by felixonmars** [comment]
No the boot settings are still present, and work correctly if I am not mistaken...

![2018-11-21-162123-010f22](https://user-images.githubusercontent.com/1006477/48827967-8582d500-eda9-11e8-9b0e-f4f84113afb7.png)

**Comment by hualet** [comment]
Oh, sorry...

**Comment by SalahAdDin** [comment]
@hualet, are you working for enabling this feature?

**Comment by hualet** [comment]
> @hualet, are you working for enabling this feature?

I'm not using Arch-DDE, but @felixonmars said it's working correctly, so I'm assuming it's fixed?

**Comment by SalahAdDin** [comment]
Not really, you must to disable/enable themes for GRUB and after that, you must to update the grub yourself, `deepin-desktop`  does not it itself.
