### ISSUE TITLE
Sometimes Graphics Effects cannot be turned on on startup

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#2611]
Note that it's not the same as linuxdeepin/dde-kwin#111 

Sometimes kwin_x11 refuses to turn on compositing even the OpenGLisUnsafe key is false (and cannot be turned on in the control center too):
![2020-06-16-033257-176727](https://user-images.githubusercontent.com/1006477/84698599-a8c03700-af82-11ea-8e41-92d3eb829c1a.png)

Startup logs:
![2020-06-16-033759-70c89a](https://user-images.githubusercontent.com/1006477/84698717-d73e1200-af82-11ea-85a9-9292f1a296c1.png)

But after killing kwin_x11 and wait for it to start up again, compositing is working correctly.

Also it's not reproducible on next reboot (quite randomly).

**Comment by justforlxz** [comment]
啊这，我该怎么处理呢

**Comment by justforlxz** [comment]
现在好像没有再看到类似的报告，我先关闭了。
