### ISSUE TITLE
Window effects shadow borders of inactive windows look weird

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/developer-center#2612]
I don't know, what is triggering it, but at some point, window borders of inactive windows start to look like this:

![image](https://user-images.githubusercontent.com/6298761/67273323-81ca6780-f4be-11e9-9ad2-2b6dfbfed484.png)

![image](https://user-images.githubusercontent.com/6298761/67273373-99a1eb80-f4be-11e9-979f-616d34a3e441.png)

After re-login it is back to normal.

**Comment by justforlxz** [comment]
now it is work again!   

```
deepin-kwin 5.4.26-3
kwin 5.24.5-1
```
