### ISSUE TITLE
arch dde下窗口顶栏最小化失效

### ISSUE THREAD

**Issue by Jontyshaw** [linuxdeepin/developer-center#2614]
窗口最小化按钮第一次点击缩小到dock上后，从dock打开后点击最小化没有反应

**Comment by BLumia** [comment]
抱歉现在才开始处理 GitHub 相关的 BUG 反馈，您描述的问题很可能已经修复了，这个问题相关可以在这里跟进： https://github.com/linuxdeepin/developer-center/issues/2630
