### ISSUE TITLE
No thumbnail in multitasking view

### ISSUE THREAD

**Issue by EspadaRunica** [linuxdeepin/developer-center#2616]
When opening multitasking, the thumbnails are not visible (Deepin 20 (1002)) (Driver 440 privative and 450.66)
![Screen Capture_20200913172343](https://user-images.githubusercontent.com/44514442/93027818-fa11ae00-f5e5-11ea-9120-b1344f2e7f4f.png)

My Hardware...
[Información del dispositivo20200913_173053.txt](https://github.com/linuxdeepin/dde-kwin/files/5215050/Informacion.del.dispositivo20200913_173053.txt)

**Comment by meiyixiang** [comment]
这个问题已经修复了请升级至最新的20.4版本
22/5000 
This issue has been fixed please upgrade to the latest version 20.4

**Comment by meiyixiang** [comment]
This issue has been fixed please upgrade to the latest version 20.4
