### ISSUE TITLE
cannto re-tiling windows

### ISSUE THREAD

**Issue by laradvance** [linuxdeepin/developer-center#2618]
Using Deepin 20 Community testing 1003
When some windows tiled, it cannot be re-tiling until windows maximized an then minimized

**Comment by BLumia** [comment]
Sorry for the super late reply. The issue you mentioned seems no longer exists on the most recent release of deepin (currently `deepin v20.6`). The window can be re-tilled after it's tiled now, so I'll close this issue now.

If you still having this issue on the most recent release of deepin, please feel free to create a new issue so we can look into it. Thanks!
