### ISSUE TITLE
Applications Won't Minimize More Than Once

### ISSUE THREAD

**Issue by Hyperdraw** [linuxdeepin/developer-center#2619]
All applications that are part of the Deepin Desktop Environment (like the file manager, text editor, etc.) can minimize once, but then if you restore them and try to minimize them again, it does nothing. The issue doesn't seem to happen with other applications (e.g. Firefox), but only with DDE applications.

**Comment by BLumia** [comment]
Sorry we didn't take too much attention to issues from non-`developer-center` repo. This issue might already get resolved, but anyway we'll re-verify if this issue still exists. You can keep track this issue at https://github.com/linuxdeepin/developer-center/issues/2630.
