### ISSUE TITLE
Set GTK Theme into QT

### ISSUE THREAD

**Issue by Urgau** [linuxdeepin/developer-center#262]
Hello,

I'm on Archlinux and I used many apps in Qt but there are not the same theme that GTK can you please solve it.

**Comment by hualet** [comment]
If you installed deepin-qt5integration, it should work.

**Comment by Urgau** [comment]
No sorry that didn't work with me.

![Exemple](https://puu.sh/vjQ37/4bf1fb8230.png)
You can see that deepin-qt5integration is installed and the foreground app is in GTK but the background app is in QT and there are not the same theme.

**Comment by hualet** [comment]
It's the application the fault that it just ignore the style plugin suggested by the DE, which is qgtk2style in DDE. I see the appliation specifing fusion style as its style (what the application looks like in your picture) in its source code.

**Comment by JulianLai** [comment]
@hualet How to change the theme to qgtk2style for QT app?

**Comment by hualet** [comment]
https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications#QGtkStyle

**Comment by hualet** [comment]
If you're in DDE, deepin-qt5integration will do that for you.

**Comment by JulianLai** [comment]
@hualet I have to add `QT_QPA_PLATFORMTHEME=gtk2` to `/etc/environment`, otherwise it won't work.

**Comment by felixonmars** [comment]
Qt has removed qgtk2style since 5.7. You need to install qt5-styleplugins from AUR to get that back...
