### ISSUE TITLE
Archlinux dde-kwin undefined symbol: _ZN4KWin6Cursor6s_selfE

### ISSUE THREAD

**Issue by Invincibl-e** [linuxdeepin/developer-center#2620]
Version: 5.2.0.11

```
➜  deepin-kwin kwin_no_scale 
kwin_x11: symbol lookup error: /usr/lib/libkwin-xcb.so.0: undefined symbol: _ZN4KWin6Cursor6s_selfE
```

**Comment by BLumia** [comment]
Seems resolved, closed for now :)

**Comment by BLumia** [comment]
Whoops, PR not merged, sorry :/

**Comment by justforlxz** [comment]
增加了一些选项，用来开关一些功能，现在测试是禁用掉 dde-kwin 的符号覆盖，以及几个没有适配的插件，已经可以正常启动了。

构建的时候加上 `-DUSE_KWIN_NO_SCALE=OFF -DUSE_PLUGINS=OFF -DUSE_WINDOW_TOOL=OFF`

[Uploading dde-kwin.5.4.26.patch.zip…]()

**Comment by felixonmars** [comment]
> Uploading dde-kwin.5.4.26.patch.zip…

还在显示 uploading 的状态时把评论发出去，大家是无法下载到这个文件的……

**Comment by justforlxz** [comment]
> > Uploading dde-kwin.5.4.26.patch.zip…
> 
> 还在显示 uploading 的状态时把评论发出去，大家是无法下载到这个文件的……

[dde-kwin.5.4.26.patch.zip](https://github.com/linuxdeepin/developer-center/files/8403608/dde-kwin.5.4.26.patch.zip)

嘻嘻，没注意到（

**Comment by justforlxz** [comment]
根据我的测试，目前已经可正常工作。
