### ISSUE TITLE
Show multiple icons in taskbar for each instance of an app

### ISSUE THREAD

**Issue by greatkeke** [linuxdeepin/developer-center#2621]
Hi there,
It's glad to have so wondful desktop os.
I've got a bit of hiccups, which is that there is no way to show multiple icons in taskbar for each instance of an app.
Such as, I open chrome and there was an icon in taskbar for it. Then open another instance of chrome, there still was the single icon.Thus, I couldn't locate my expected instance quickly. 
Could you provide a way to support this feature?
Thx & Regards

**Comment by tsic404** [comment]
I don't think we would design it that way
