### ISSUE TITLE
Disable only shadows of windows and not all window effects

### ISSUE THREAD

**Issue by jonalxh** [linuxdeepin/developer-center#2623]
Hi, I'm using the last version of Deepin OS but i want to remove the window shadows without disabling all window effects, that's because I'm used to work with multiple windows in same screen and a piece of the unfocused windows get covered by the shadow of the focused.
Is it possible?

**Comment by justforlxz** [comment]
You can use kde system settings to make advanced settings for kwin's functions, I think it should meet your requirements.

`sudo apt install systemsettings`
