### ISSUE TITLE
Bug report 「缺陷报告」：关于dde-lock会导致闪屏的问题

### ISSUE THREAD

**Issue by thefivestar** [linuxdeepin/developer-center#2626]
我的机器是华硕天选 AMD4800H+1660TI，在我的机器上，锁屏后点亮屏幕可能会导致闪屏，起初，我以为是内核的原因，因为我的机器无法安装内核版本为5.4的deepin/uos,但是可以安装内核版本为5.7.7的deepin/uos，在使用5.7.7内核的deepin上，锁屏后点亮会大概率导致闪屏，于是我将内核升级为5.8.10，但是5.8.10内核的deepin仍然闪屏，随后，我更换5.8.13与5.9.0内核，均会发生闪屏的问题，在此期间，我多次重装系统，包括deepin与uos，且我都安装好了nvidia驱动并配置了prime。但是该问题一直困扰着我，经过多次观察，我发现该问题在系统日志中表现为:
> 级别：错误 进程：polkit-agent-he 时间：2020-10-16 09:43:18 信息：pam_deepin_authentication(polkit-1:auth): Cannot get original tty attributes: Inappropriate ioctl for device 主机名：thefivestar-PC  进程号：19346 
级别：错误 进程：dde-lock 时间：2020-10-16 09:42:28 信息：pam_deepin_authentication(common-auth:auth): Cannot get original tty attributes: 对设备不适当的 ioctl 操作 主机名：thefivestar-PC  进程号：18992 
级别：错误 进程：dde-lock 时间：2020-10-16 09:42:13 信息：pam_deepin_authentication(common-auth:auth): Cannot get original tty attributes: 对设备不适当的 ioctl 操作 主机名：thefivestar-PC  进程号：18992 

即，闪屏必然伴随着 **dde-lock的Cannot get original tty attributes: 对设备不适当的 ioctl 操作** 问题！

**Comment by babyfengfjx** [comment]
非常感谢您的反馈，抱歉我们长时间未进行沟通，当前问题我们在最新版本中发现正常，我们先关闭此issue,如果该问题仍旧存在，或者有新的问题，还请随时反馈给我们～
