### ISSUE TITLE
Minimize button of Deepin apps is broken

### ISSUE THREAD

**Issue by Saduff** [linuxdeepin/developer-center#2628]
## Describe the bug

1. The minimize button only works once. Clicking it next time doesn't do anything.
2. Clicking the minimize button once breaks the maximize button such that the right side of the window is not clickable when maximized.

Related issue: linuxdeepin/developer-center#2321

## To Reproduce

1. Open any Deepin app like control center, terminal, text editor, calendar etc
2. Click the minimize button
3. Bring the app back into focus
4. Click the minimize button again (doesn't work)
5. Click the maximize button
6. Try click on the right side of the window or any buttons (minimize, maximize, close)

## Expected behavior

The app should minimize when the button is pressed and it should not break the maximized window such that the right side of the window is not clickable.

## Actual behavior

The minimize button doesn't do anything and it breaks the maximized window.

### 1. Minimize button

![Screen Capture_select-area_20200715144855](https://user-images.githubusercontent.com/11700507/87543367-4d7e8300-c6ad-11ea-942b-ba9f1887b15e.gif)

### 2. Maximized window problem

![Screen Capture_dde-desktop_20200715150111](https://user-images.githubusercontent.com/11700507/87543434-6b4be800-c6ad-11ea-9934-62b5dcbd1f84.gif)

### Distro & Version

Arch Linux with Deepin v20

### Related package version

```
deepin-account-faces 1.0.11-2 (deepin)
deepin-anything 5.0.1-3 (deepin)
deepin-anything-arch 5.0.1-92
deepin-api 5.3.0.3-1 (deepin)
deepin-boot-maker 5.4.8-1 (deepin-extra)
deepin-calendar 5.7.0.3-1 (deepin)
deepin-clone 5.0.3-1 (deepin-extra)
deepin-clutter 1.26.2-3
deepin-cogl 1.22.5-3
deepin-community-wallpapers 1:1.7.7-2 (deepin-extra)
deepin-control-center 5.2.0.20-1 (deepin)
deepin-daemon 5.11.0.17-1 (deepin)
deepin-desktop-base 2:2020.04.12.2-2 (deepin)
deepin-desktop-schemas 5.6.0.12-1 (deepin)
deepin-dock 5.1.0.11.20200622-1 (deepin)
deepin-editor 5.6.21-1 (deepin-extra)
deepin-file-manager 1:5.1.1.25-4 (deepin)
deepin-gtk-theme 2020.06.10-1 (deepin)
deepin-icon-theme 2020.06.30-1 (deepin)
deepin-image-viewer 5.6.3.2-2 (deepin)
deepin-kwin 5.1.0.4-2 (deepin)
deepin-launcher 5.2.0.13-1 (deepin)
deepin-manual 5.0.0-1 (deepin)
deepin-menu 5.0.1-2 (deepin)
deepin-metacity 3.22.24-2
deepin-movie 1:5.7.6.29-1 (deepin-extra)
deepin-music 6.0.1.8-2 (deepin-extra)
deepin-mutter 3.20.38-4
deepin-network-utils 5.1.0.1-1 (deepin)
deepin-picker 5.0.6-1 (deepin-extra)
deepin-polkit-agent 5.2.0.7-1 (deepin)
deepin-polkit-agent-ext-gnomekeyring 0.1.0-2 (deepin)
deepin-qt-dbus-factory 5.2.0.3-1
deepin-qt5integration 5.1.0.3-1 (deepin)
deepin-qt5platform-plugins 5.0.13-1 (deepin)
deepin-screen-recorder 5.8.0.11-3 (deepin-extra)
deepin-screensaver 5.0.3-1 (deepin)
deepin-session-shell 5.1.0.10-1 (deepin)
deepin-session-ui 5.2.0.11-1 (deepin)
deepin-shortcut-viewer 5.0.2-1 (deepin)
deepin-sound-theme 15.10.6-1 (deepin)
deepin-system-monitor 5.6.12-1 (deepin)
deepin-terminal 5.2.11-1 (deepin-extra)
deepin-turbo 0.0.3-2 (deepin)
deepin-voice-note 5.7.11-1 (deepin-extra)
deepin-wallpapers 1:1.7.7-2 (deepin)
deepin-wallpapers-plasma 5.18.5-1
dtkgui 5.2.2.1-1
dtkwidget 5.2.2.2-1
dtkwm 2.0.12-8
startdde 5.5.0.7-1 (deepin)
```

**Comment by BLumia** [comment]
Sorry we didn't take too much attention to issues from non-developer-center repo. This issue might already get resolved, but anyway we'll re-verify if this issue still exists. You can keep track of this issue at https://github.com/linuxdeepin/developer-center/issues/2630.
