### ISSUE TITLE
Desktop Zoom (Super & + keys) not working properly in Deepin v20

### ISSUE THREAD

**Issue by mmohsinkhan** [linuxdeepin/developer-center#2629]
I am a software developer with eye sight problem, I need screen magnification to use my computer and carry out routine work.

I have been using Deepin 15 as my daily driver for almost a year. Screen magnification works fine on Deepin 15 but now it doesn't seems to work properly on Deepin v20.
Keyboard shortcuts
Zoom In: Super & + keys
Zoom Out: Super & - keys

Desktop zoom does not follow mouse pointer on Deepin v20 plus there is extreme frame drop. All in all desktop zoom in Deepin v20 Beta is not usable.

I want to continue using Deepin and upgrade to v20 but without screen magnification it won't be possible.
Please help.

Best Regards

**Comment by BLumia** [comment]
Hi, sorry for the super late response.

I tested this issue on deepin v20.5 (with deepin-kwin) and also Arch Linux (with deepin-wm) and it seems <kbd>Super + ±</kbd> should now be able to zoom-in and out correctly! Please update your system and see if it's working for you.

If you still have similar issues, please feel free to create another issue with necessary detailed information so we can look into it. Thanks!
