### ISSUE TITLE
Bug with color in context menu.

### ISSUE THREAD

**Issue by Urgau** [linuxdeepin/developer-center#263]
Hello,

I'm on Archlinux and I see this bug when I right click on the menu bar :
![color deepin](https://cloud.githubusercontent.com/assets/3616612/25044463/147fef0a-2127-11e7-84d0-f234069334b6.png)

**Comment by hualet** [comment]
Is this happening every time ?

**Comment by zccrs** [comment]
Which is the application's right-click menu?
Other applications are the same?

**Comment by Urgau** [comment]
It's the right click on the dde-dock.

**Comment by sbwtw** [comment]
please post your package version of dde-qt5integration 
@felixonmars is that name in arch?

**Comment by Urgau** [comment]
@sbwtw No it's deepin-qt5integration.

![Version](https://puu.sh/vmTM6/9583a4eb1f.png)

**Comment by felixonmars** [comment]
Is this still reproducible?

**Comment by Urgau** [comment]
@felixonmars No, a update solve the problem.
