### ISSUE TITLE
窗体无法进行管理（移动、调整大小、切块堆叠层级等等）

### ISSUE THREAD

**Issue by SachieWang** [linuxdeepin/developer-center#2637]
环境：ArchLinux + dde

系统更新后发生上述窗体问题。

尝试运行kwin_no_scale脚本，有如下报错
kwin_x11: symbol lookup error: /usr/lib/libkwin-xcb.so.0: undefined symbol: _ZNK4KWin9Workspace11compositingEv

目前使用kwin_x11 --replace暂时处理，但日志中同样有如上报错。

**Comment by justforlxz** [comment]
已经修好啦，等待更新（

**Comment by wszqkzqk** [comment]
arch上的deepin似乎又坏了？

**Comment by BLumia** [comment]
> arch上的deepin似乎又坏了？
> 
> 现在安装了deepin-kwin也会使用deepin-wm，并且卸载了deepin-wm也不会正常调用deepin-kwin

建议考虑另开个 bug 反馈（或者来 `#dde-port:deepin.org` 讨论），毕竟导致问题的原因应该是和这个原始 issue 不一样的。
