### ISSUE TITLE
How to install dde-clipboard on Deepin?

### ISSUE THREAD

**Issue by sasha-brankovic** [linuxdeepin/developer-center#2640]
Please, could you write steps that needed for install

**Comment by BLumia** [comment]
Hi!

`dde-clipboard` should be pre-installed on Deepin. If you means install it from system package repo, then a regular `apt install dde-clipboard` should work.

**Comment by Ronghzhe** [comment]
### 剪切板项目README 
#https://github.com/linuxdeepin/dde-clipboard/pull/9

**Comment by BLumia** [comment]
Should be resolved now in https://github.com/linuxdeepin/dde-clipboard/pull/9 :)
