### ISSUE TITLE
ISO file not working

### ISSUE THREAD

**Issue by azamalvi** [linuxdeepin/developer-center#2644]
I have Asus ROG Strix G15 G512LI Gaming Laptop and I want to install Deepin 20 in it. Now when I make USB bootable and after I boot from USB it just shows me a black screen with fixed underscore on top left. I have tried different versions of Deepin 20 ISO filesbut same issue. After that I make Ubuntu, Linux Mint, MX Linux and they all are working fine only issue is with Deepin 20 ISO. I tried multiple boot maker applications but same issue. Also I tried it with Deepin 20 Boot Maker but no luck.

**Comment by Zeno-sole** [comment]
It should be that the efi program of the Deepin 20 ISO does not work on your machine, the latest version of the efi program has been updated, does 20.4 work properly on your machine? @azamalvi
