### ISSUE TITLE
Bug report 「缺陷报告」dde-lock: unlock failure on openSUSE

### ISSUE THREAD

**Issue by hillwoodroc** [linuxdeepin/developer-center#2645]
hillwood@localhost:~> rpm -qi deepin-session-shell
Name        : deepin-session-shell
Version     : 5.4.112
Release     : 1.2
Architecture: x86_64
Install Date: 2022年03月20日 星期日 13时21分40秒
Group       : System/GUI/Other
Size        : 1922135
License     : GPL-3.0+
Signature   : RSA/SHA256, 2022年02月20日 星期日 22时44分51秒, Key ID b88b2fd43dbdc284
Source RPM  : deepin-session-shell-5.4.112-1.2.src.rpm
Build Date  : 2022年02月20日 星期日 22时31分58秒
Build Host  : cloud122
Packager    : https://bugs.opensuse.org
Vendor      : openSUSE
URL         : https://github.com/linuxdeepin/dde-session-shell
Summary     : Deepin desktop-environment - Session UI Shell
Description :
This project include those sub-project:

https://user-images.githubusercontent.com/1880237/159498435-84c2fbeb-a526-4e84-98c7-23707b155c58.mp4

**Comment by tsic404** [comment]
Please provide /var/log/daemon.log

**Comment by hillwoodroc** [comment]
5.5.9 fix this issue.
