### ISSUE TITLE
Problem Wake Up After Suspend

### ISSUE THREAD

**Issue by jamkar20** [linuxdeepin/developer-center#2647]
When I Suspend My Laptop and Wake Up It ,Show Desktop Immediately after 2 seconds show lock screen also when enter wrong password input box hang up

**Comment by justforlxz** [comment]
This is a very tricky problem for us, because we don't know when the screen has finished refreshing, and the standby command will freeze the user state immediately, so we can't update the screen to the screen, we are going to use wayland in the future, and then we will This problem can be solved.
