### ISSUE TITLE
dde-session-shell: found an error! Fix!!

### ISSUE THREAD

**Issue by LsMacox** [linuxdeepin/developer-center#2648]
add useravatar.cpp:
#include "qpainterpath.h"
add darrowrectangle.cpp:
#include "qpainterpath.h"

**Comment by tsic404** [comment]
could you give a reason ?

**Comment by BLumia** [comment]
Closing since no future response. If you believe this still need to be fixed in the most recent codebase of dde-session-shell, please feel free to create a new issue so we could look into it. You can also send a Pull Request to us directly and we'll be happy to help you get it merged :)
