### ISSUE TITLE
Deepin Terminal 在 Dock 分別顯示成兩個圖示

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#265]
從啟動器或「Ctrl+T」開啟的 Terminal 顯示成一個圖示，從右鍵選單開啟的 Terminal 會另外跑出一個圖示
https://youtu.be/XJUrnUtjEnE

**Comment by DasJott** [comment]
Same here!

**Comment by hualet** [comment]
cannot reproduce in deepin...
@jouyouyun @electricface

**Comment by electricface** [comment]
重现此bug，然后执行

```
gdbus introspect -p -r -e -d com.deepin.dde.daemon.Dock -o /com/deepin/dde/daemon/Dock
```
把输出结果发一下

是否是没有安装 bamf ？

**Comment by hualet** [comment]
@JulianLai 还有这个问题么？

**Comment by manateelazycat** [comment]
无法重现，有线索欢迎重新打开
