### ISSUE TITLE
Does Version 5.4.9 really need DtkWidget5.5 

### ISSUE THREAD

**Issue by hillwoodroc** [linuxdeepin/developer-center#2650]
https://github.com/linuxdeepin/dde-session-shell/blob/9b9fcb53c6bac7a0fcd867dc5a75a0a79a96104f/CMakeLists.txt#L40
I don't know whether you build it before release. But it can not build on openSUSE. I need to use  "DtkWidget" to replace  "DtkWidget5.5".

**Comment by BLumia** [comment]
Seems no longer need to do the special trick for the current version. :joy: https://github.com/archlinux/svntogit-community/blob/5b8562b42f55ee5cc7a61eb564b250306d16f9ba/trunk/PKGBUILD#L23-L27

Please feel free to create another issue for other porting issues :)
