### ISSUE TITLE
笔记本上登录界面小键盘默认不开启

### ISSUE THREAD

**Issue by zty199** [linuxdeepin/developer-center#2658]
Deepin 20.2.2
和之前版本中一样，登录界面中小键盘总是默认不开启。这个问题从 1003 开始就有了......
请问一下是故意这么设计的吗？

这里不应该是能够读取到用户的 gsettings 设置来改变小键盘初始状态的吗？那 recoveryUserKBState 是不是应该放在外面？
![截图_microsoft-edge-beta_20210703231923](https://user-images.githubusercontent.com/46324746/124359178-6ed9d580-dc56-11eb-9a22-032dfb4c6081.png)

**Comment by tsic404** [comment]
你可以提交pr，我们现在接受pr :)

**Comment by zty199** [comment]
> 你可以提交pr，我们现在接受pr :)

截图的时候和现在的代码已经没啥关系了，现在用户数字键盘开关都不用 gsettings 储存，换成 dde-dconfig 了，目前最新的代码里这个地方也已经被改过了，不需要再提 pr 了......
