### ISSUE TITLE
Hotkey and Audio

### ISSUE THREAD

**Issue by ForumLiker** [linuxdeepin/developer-center#2660]
How to add a hotkey to the configuration file?
How to record audio with video?

**Comment by BLumia** [comment]
Sorry for the super late response.

For adding shortcuts, you can add shortcuts from the system setting app. And in `deepin-screen-recorder 5.10.15-1` you can record audio if you select MP4 or MKV as the output format :)

If you have any other suggestions, feel free to [create a discussion thread on the discussion board](https://github.com/linuxdeepin/developer-center/discussions) :)
