### ISSUE TITLE
Only captures on first monitor

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/developer-center#2661]
Even though I marked a rectangle on my third monitor (where the area was shown correctly all the time during the recording), it captured the same area on the first monitor the whole time.

As there was nothing happening, the result was rather boring...

**Comment by babyfengfjx** [comment]
I wonder if the problem still exists in the latest version?

**Comment by babyfengfjx** [comment]
Because the issue has been left for too long, perhaps the problem has been solved, we first close the processing, if there are new problems thanks to submit at any time.
