### ISSUE TITLE
can not  work for i3-wm

### ISSUE THREAD

**Issue by hellojukay** [linuxdeepin/developer-center#2663]
![image](https://user-images.githubusercontent.com/10371891/65215434-13217500-dae0-11e9-92ee-0772c8af0e30.png)

**Comment by BLumia** [comment]
Sorry for the late reply since we were not checking issues that were reported outside the developer-center repo.

> @weynhamz  surprisingly find deepin-screenshot is abandoned by Deepin team, curious about the reason, any link on this?

It's because deepin-screen-recorder is designed to be both a screenshot tool and a screen recorder tool.

**Comment by SuperEffie** [comment]
Thank you for your feedback.Sorry I can't reproduce your issue.Now our system has updated to deepin v20.5 and we mainly focus the deepin-screen-recorder tool.It works fine under multi-monitor setup.I close this issue at first.If you have any feedback or suggestions.You are welcomed to creat a new issue.
