### ISSUE TITLE
System Tray 裡面某些圖示會有小黑框

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#267]
而且不固定是那一個
![deepin-screen-recorder_select area_20170415115623](https://cloud.githubusercontent.com/assets/20014762/25060550/b2193a86-21d2-11e7-972e-14604c821eb6.gif)
![deepin-screen-recorder_select area_20170415115859](https://cloud.githubusercontent.com/assets/20014762/25060567/f4b1593c-21d2-11e7-8795-ccec0910aaa4.gif)

**Comment by hualet** [comment]
@sbwtw

**Comment by JulianLai** [comment]
@sbwtw 目前沒發生
