### ISSUE TITLE
Pencil tool performance becomes worse with every stroke

### ISSUE THREAD

**Issue by austinpray** [linuxdeepin/developer-center#2671]
After about 16 equal-sized strokes the latency between drawing the strokes and the strokes appearing on the screen becomes really high.

![out-00 00 25 024-00 00 41 708-opt](https://user-images.githubusercontent.com/2192970/85956985-1e4ae080-b94f-11ea-8756-d2f27e38ce06.gif)

Video demo: https://youtu.be/qZOryIccN_A

This is on a minimal install of arch linux. If you cannot reproduce on your machine I can dump more info about my setup.

**Comment by SuperEffie** [comment]
Sorry for no reply for a long time,and thanks for your feedback.We cannot reproduce this issue under deepin v20.5,and the Draw has been updated to version 5.10.6.The issue you described seems to have been fixed.I have to close this issue at first.If this issue still exists,you can apply to reopen it and you are welcomed to give us more suggestions.
