### ISSUE TITLE
Black tilting at recording screen

### ISSUE THREAD

**Issue by SalahAdDin** [linuxdeepin/developer-center#2673]
Hi,

I commonly use this app to record my desktop on **Manjaro Linux**, no problem, but with the last version, I'm getting an odd black tilting recording my screen, as you can see in this [link](https://res.cloudinary.com/dqhx2k8cf/video/upload/v1595506537/Screen_Capture_select_area_20200723143739_e1bba6a3f6.mp4).
I didn't get this problem recording gif, but with video, it is another history.

What's the problem?

Thanks

**Comment by BLumia** [comment]
Does this still happen on the most recent release of `deepin-screen-recorder` you can get?

**Comment by SalahAdDin** [comment]
> Does this still happen on the most recent release of `deepin-screen-recorder` you can get?

I have to check it again, sorry.

**Comment by BLumia** [comment]
I'll close this for now since we can no longer reproduce this issue.

If you can reproduce this on the most recent version you can get, please consider creating a new issue with related information provided so we can look into it. Thanks!
