### ISSUE TITLE
[BUG] Recording screen blocks key strokes on i3wm

### ISSUE THREAD

**Issue by StealthyKamereon** [linuxdeepin/developer-center#2675]
I'm on archlinux+i3wm and recording the screen prevent other programs from getting the key strokes.

Steps to reproduce :
- Start deepin-screen-recorder
- Select "Record"
- Start recording
- Type some text somewhere

What should happen ?
The text should be entered.

What's happening ?
Nothing happens.

**Comment by Zeno-sole** [comment]
Sorry for replying only now, do you still encounter this problem in the latest version?

**Comment by Zeno-sole** [comment]
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue
