### ISSUE TITLE
Doesn't work when Fractional Scaling is active on Gnome3

### ISSUE THREAD

**Issue by thomasesr** [linuxdeepin/developer-center#2677]
If I have scaling factor set below 1, when I open the deepin-screen-recorder the screen gets zoomed in and pixelated and the UI doesn't work.
![image](https://user-images.githubusercontent.com/8300740/99199023-0992ac00-277b-11eb-8879-266cf8b1f3f6.png)

**Comment by babyfengfjx** [comment]
I wonder if similar problems still occur in the recent new version?

**Comment by babyfengfjx** [comment]
Because the issue is a long time ago, we first do to close the processing, such as the follow-up of new issues are welcome to submit at any time .
