### ISSUE TITLE
100% CPU screen recorder Gif

### ISSUE THREAD

**Issue by serial02** [linuxdeepin/developer-center#2678]
Hello Deepin Team

The Gif mode screen recorder on the Deepin V20 1003 is using 100% CPU, causing the entire "system" to crash, making it necessary to turn off the Desktop button, as seen here: https://bbs.deepin.org/ post / 206302 To evidence the above report, follow the image to confirm the above:

https://imgur.com/j2Lfn3A

**Comment by BLumia** [comment]
Hi and in v20.5 this issue should no longer exist. Please consider updating your package and see if that will fix the issue :)

If it still happens on v20.5 or other distro, please open another issue so we can look into it. Thanks!
