### ISSUE TITLE
[dde-control-center] Text too long in the shortcuts

### ISSUE THREAD

**Issue by Urgau** [linuxdeepin/developer-center#268]
Hello,

I'm on Archlinux and I see this bug with the French translation :

![Image](https://cloud.githubusercontent.com/assets/3616612/25062324/c29d6fd8-21ca-11e7-870d-7407447b1f1d.png)

Green - Not see the end of the sentence
Red - Not see the end **and** the start of the sentence

**Comment by hualet** [comment]
@kirigayakazushin Make it two lines ?

**Comment by Urgau** [comment]
Yes.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
