### ISSUE TITLE
Flatpak support to Deepin-Screen-Recorder Version 5.9.1

### ISSUE THREAD

**Issue by serial02** [linuxdeepin/developer-center#2682]
[Flatpak ](https://flatpak.org/)in being wildly adopted by the main Linux desktop project (GNOME), KDE, and several distros are enabling it (some depends almost exclusively on it like [Silverblue](https://silverblue.fedoraproject.org/)).

The main store of Flatpak is [Flathub](https://flathub.org/home). Many people search by new software there (directly at the site or via "app store"). So, if someone has his software in Flatpak + Flathub:

   

> Easier to new users discover it. (By App Store or [Flathub](https://flathub.org/home)).
> Easier to install. Just a click in the App Store (like Gnome/Ubuntu Software), in the same way as their other distro packages (rpm, debs, etc.). So, people don't need to know the site of the developer or the existence of AppImages, etc.
> Automatically updates.
> Better integration with Desktop (we can see it in the software center, with version, license, button to remove, etc.)
> The users don't need to be at the latest Linux distribution release to have the most updated software version (as is the case of a lot of distros).
> As said by autocascade [here](https://old-forum.smplayer.info/viewtopic.php?f=4&t=11124), "Linux is so fragmented it would seem to be a good way to distribute apps".
>

**Comment by Zeno-sole** [comment]
Do you want us to support Flatpak format?

**Comment by serial02** [comment]
> Do you want us to support Flatpak format?

Yes! Numerous Linux Distributions would benefit from this excellent application by making it available to everyone! It's the name Deepin in other distributions, think about IT! The functions you created for this app are magnificent.

**Comment by Zeno-sole** [comment]
Thank you very much for your suggestion, some developers are adapting Flatpak to our application, and it should be gradually adapted in the future

**Comment by Zeno-sole** [comment]
> Thank you very much for your suggestion, some developers are adapting Flatpak to our application, and it should be gradually adapted in the future

https://github.com/ggssh/deepin-calculator-pkg
