### ISSUE TITLE
Don't call dde-daemon when it's not already running

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#2683]
Currently deepin-screen-recorder always launches dde-daemon when running as a standalone application under other desktop environments. dde-daemon will modify system settings and conflict with the respective parts of other desktop environment, rendering deepin-screen-recorder not so usable.

Please consider to not call dde-daemon when it's not already running, so that it's a useful application under other DE. We are sticking to the old deepin-screenshot due to this, for a very long time already.

**Comment by justforlxz** [comment]
大概过了一遍代码，用到 daemon 的地方都做了检查。
