### ISSUE TITLE
Deepin Calendar 找不到可以翻譯農曆節日的地方

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#269]
Transifex 頁面並沒有這些選項

**Comment by hualet** [comment]
@jouyouyun 可以支持其他语言么？

**Comment by jouyouyun** [comment]
农历节日为什么要翻译?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
