### ISSUE TITLE
deepin-graphics-driver-manager: polkit授权窗口问题

### ISSUE THREAD

**Issue by ziqiangxu** [linuxdeepin/developer-center#2697]
现在policy文件直接设置的是/bin/bash，这样如果其它程序使用/bin/bash的话也弹出驱动管理器，不太好。建议新建一个软链接替换/bin/bash

**Comment by BLumia** [comment]
显卡驱动管理器目前已经没有在活跃维护了，所以这个 issue 只能暂时关掉了。以后兴许会有替代项目，所以可以持续关注一下。

关于你提到的问题，如果希望的话您也可以直接发个 PR 分享给社区 :joy:

关联： #3000
