### ISSUE TITLE
屏幕闪烁

### ISSUE THREAD

**Issue by wyy0117** [linuxdeepin/developer-center#2699]
硬件配置：蓝天 准系统 P775TM i7 8700，32G ddr4，gtx1060 6G。
系统默认驱动屏幕显示正常，但是无法调节亮度。安装显卡驱动管理里的必源驱动，开关机几次之后，屏幕会有闪烁的现象发生，使用外接鼠标后，屏幕闪烁较为严重，屏幕会有忽亮忽暗的感觉，一秒钟能闪烁好几下，外接显示器正常。使用Windows系统屏幕正常，使用ubuntu18安装必源驱动（版本390.77）后屏幕正常，不知道是deepin使用的必源驱动版本（390.67）问题还是怎么回事。

**Comment by BLumia** [comment]
这是个很老的 issue 了，抱歉我们之前很少关注在 developer-center 之外所创建的 issue，所以现在才回复您。

这个很可能是之前所用的闭源驱动的问题，不过时间已隔很久了，兴许您现在使用开源驱动也会有不错的显示效果。如果您有意愿的话，可以考虑安装下目前最新的 deepin 试试看。

这个 issue 我们就先关掉了（实在太久远了），如果仍有问题的话建议您新开个 issue 附带可能相关的信息以便我们进一步处理问题。感谢反馈~
