### ISSUE TITLE
Dock 選單破圖

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#270]
目前只發生在「電源選項」和「磁碟機」這兩個選項上，註銷後再登入才恢復正常

缺一角
![deepin 20170415221134](https://cloud.githubusercontent.com/assets/20014762/25064229/9f81138e-2228-11e7-8cbf-c47451888017.png)
點開整個破圖
![deepin 20170415221144](https://cloud.githubusercontent.com/assets/20014762/25064230/9f8a2e74-2228-11e7-9726-e9d56c3c8346.png)

**Comment by hualet** [comment]
能联系到你们的维护者，让帮忙rebuild一下 dde-dock看看么？

**Comment by zccrs** [comment]
这个问题应该是升级了deepin-tool-kit后没有没有rebuild dde-dock引起的

**Comment by hualet** [comment]
@JulianLai 现在还有这个问题么？
