### ISSUE TITLE
deepin-graphics-driver-manager: AMD驱动应该加入官网的amdgpu-pro

### ISSUE THREAD

**Issue by 8ar10der** [linuxdeepin/developer-center#2703]
否则无法支持opencl，vulkan，opengl的特性。
https://amdgpu-install.readthedocs.io/en/latest/install-overview.html

**Comment by BLumia** [comment]
抱歉现在才进行答复，我们之前很少关注 developer-center 之外汇报的 issue...

deepin-graphics-driver-manager 这个项目已经不再活跃维护了，所以就先关掉这个 issue 了。后续也可能会复活这个项目所以还请继续关注 deepin :)

link: #3000
