### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by disburden** [linuxdeepin/developer-center#2707]
Cmake -dcmake_install_prefix:path=/usr .. 

我在执行这个语句的时候遇到了错误
mv: 无法获取'deepin-graphics-driver-manager.desktop.tmp' 的文件状态(stat): 没有那个文件或目录
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
CMake Error at CMakeLists.txt:38 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
See also "/home/disburden/Downloads/deepin-graphics-driver-manager/build/CMakeFiles/CMakeOutput.log".

请问要如何解决？

**Comment by BLumia** [comment]
实在抱歉现在才回复您，我们之前很少留意汇报在 developer-center 之外的 issue。

> Could not find a package configuration file provided by "Qt5Widgets" with
> any of the following names:

字面意思，您的依赖没装齐。在构建之前，建议您先使用 `sudo apt build <软件包名称>` 来安装构建依赖。

如果您有任何其它问题的话，可以考虑[在 discussion 面板的问答板块](https://github.com/linuxdeepin/developer-center/discussions)提问~
