### ISSUE TITLE
Deepin File Manager 的共用資料夾沒作用，而且還會亂更改檔案權限

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#271]
https://youtu.be/csxQmBAeynU
現在家目錄下所有檔案都變成可執行檔了，請問要怎麼一次改回來？

**Comment by JulianLai** [comment]
找到方法改回來了
`find /home/abc -type f -exec chmod 644 {} \;`
但現在頭痛的是不曉得該如何將原本是可執行檔的檔案一次改回來

**Comment by zccrs** [comment]
目录要有可执行权限
这个bug很快就会修复，会随着下个版本更新出去

**Comment by JulianLai** [comment]
@zccrs 還有個問題是選擇「共用資料夾」並不會出現在「共用的電腦」裡

**Comment by zccrs** [comment]
不会出现在“共用的电脑”里是什么意思？

**Comment by JulianLai** [comment]
@zccrs 
![deepin 20170418112951](https://cloud.githubusercontent.com/assets/20014762/25113482/622be348-242a-11e7-8ae2-04b45b708a92.png)
![deepin 20170418112958](https://cloud.githubusercontent.com/assets/20014762/25113483/62682aba-242a-11e7-8b07-808ec7eb3eb5.png)

**Comment by zccrs** [comment]
共享的文件夹会有一个专门的“我的共享”这个目录，也是在侧边栏

**Comment by JulianLai** [comment]
@zccrs 沒有

**Comment by zccrs** [comment]
在地址栏输入：usershare:/// 能进去吗？

**Comment by JulianLai** [comment]
@zccrs 不能

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
