### ISSUE TITLE
控制中心无法打开

### ISSUE THREAD

**Issue by xuyuanbing** [linuxdeepin/developer-center#2712]
控制中心无法打开

问题是：
![深度录屏_Desktop_20200308141813](https://user-images.githubusercontent.com/20234570/76157721-e7ef1880-6147-11ea-80a7-c08a5131f9b7.gif)

**Comment by BLumia** [comment]
抱歉现在才答复，我们之前很少关注在 developer-center 外汇报的 issue。

现在 dde-control-center （我这边当前测试的版本是 `dde-control-center 5.5.11.5-1`）应该已经不会有这个问题了，可以尝试更新到最新版本再看看是否仍会遇到这样的问题。如果仍然遇到的话，欢迎另开 issue 反馈~
