### ISSUE TITLE
Language/locale/fonts issue (incorrect language and locale - correction causes font issue)

### ISSUE THREAD

**Issue by ThornedRose** [linuxdeepin/developer-center#2713]
*OS: Arch Linux x86_64 
Kernel: 5.5.9-arch1-2 
DE: Deepin 
WM: Mutter(DeepinGala) 
Theme: deepin [GTK2/3] 
All packages including Deepin are currently up to date.*

When I first installed Arch, my locale was set to en_NZ.UTF-8 (English New Zealand).
I just discovered that for some reason my locale was being overridden to en_GB. In tracking down the issue, I found that in DDE Control Centre my language was set to British English and there is no option for New Zealand English.
So I manually changed `.dde_env` in /home to:
```
export LANG="en_NZ.UTF-8";
export LANGUAGE="en_NZ";
```
This correctly set my locale.
However after rebooting, my fonts are messed up and have reverted to the fallback font.
![image](https://user-images.githubusercontent.com/239386/77130655-ae120080-6abd-11ea-8697-74a518599eda.png)

And under DDE Control Center > Personalisation > Font > both Noto Sans and Noto Mono show up as "Unsupported". Additionally I cannot change the fonts - when I click on another font, it does nothing as though I haven't clicked at all.

**Comment by Zeno-sole** [comment]
I noticed that the version you are using is already very old. Does the latest version still have this problem?

**Comment by Zeno-sole** [comment]
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue
