### ISSUE TITLE
Any Connect VPN asking for password

### ISSUE THREAD

**Issue by indricilia** [linuxdeepin/developer-center#2714]
I would really like to try out deepin in earnest but unless it allows me to open up an any connect VPN to a site, I can't start enjoying it. 

Every time I try to open up this type of VPN, I am told that there are password issues. When I relogin with any variant of gnome, all is fine.

**Comment by SuperEffie** [comment]
Sorry for not contacting you for a long time.Does this issue still exist and could you provide me some information?
Such as device information, the version of dde-network-manager.

**Comment by SuperEffie** [comment]
Due to no reply and lacking of necessary information,we close this issue now.If the issue still exists,you can apply to reopen it and we will help to deal with it.
