### ISSUE TITLE
Crash when click "System Info" on Gentoo

### ISSUE THREAD

**Issue by zhtengw** [linuxdeepin/developer-center#2716]
dde-control-center terminates with segmentation fault when click "System Info". Could any one give a tip to fix this issue?

Gcc version: 9.3.0
Qt version: 5.14.2
CMake arguments: 
`-DDISABLE_SYS_UPDATE_SOURCE_CHECK=YES -DDISABLE_SYS_UPDATE_MIRRORS=YES -DDISABLE_SYS_UPDATE=YES -DCVERSION=${version_of_dcc}`
Patch for building: [5.0.33-missing-include.patch](https://github.com/zhtengw/deepin-overlay/blob/master/dde-base/dde-control-center/files/5.0.33-missing-include.patch)

[dcc-core-dump.txt](https://github.com/linuxdeepin/dde-control-center/files/4570831/dcc-core-dump.txt)
[dcc-log.txt](https://github.com/linuxdeepin/dde-control-center/files/4570835/dcc-log.txt)

**Comment by BLumia** [comment]
Seems no longer get crashed after upgrading to newer version of dde-control-center (5.5.77 or newer version). I'll close this one for now.

If you still get similar issue, please feel free to create a new bug report. Thanks!
