### ISSUE TITLE
Toggle for data collection resets itself on Manjaro Linux

### ISSUE THREAD

**Issue by benthillerkus** [linuxdeepin/developer-center#2717]
[Here's a gif of the problem](https://cdn.discordapp.com/attachments/658467814755270666/708682086151618560/Screen_Capture_dde-control-center_20200509160614.gif)

**Comment by BLumia** [comment]
Hi, the data collection is only apply to deepin, there won't be a data collection service in Arch. Related menu might be shown by error but it's only meant to be shown in deepin/UOS.

In the most recent version of Control Center app on Arch/Manjaro, this menu should no longer exists :)

If you still got similar issues, please feel free to create another issue to report so we could look into it. Thanks!
