### ISSUE TITLE
Not all maximized windows can be closed by a click in the upper-right corner

### ISSUE THREAD

**Issue by m1cm1c** [linuxdeepin/developer-center#272]
A lot of desktops enable users to close maximized windows by slamming their mouse pointers into one corner of the screen and pressing the left mouse button. This is very quick because the user doesn't have to aim for the button. ([Even MS figured this one out.](https://blogs.msdn.microsoft.com/oldnewthing/20120522-00/?p=7563)) With Deepin, this works for example with Google Chrome. It does, however, not work with other applications like the default file manager. If you just closed a window via this means and then the next one won't close if you do the exact same thing, that's a very irritating inconsistency.

**Comment by JulianLai** [comment]
What do you mean? Like this? https://youtu.be/HA-QoHHbsuM

**Comment by m1cm1c** [comment]
@JulianLai Yes. How did you make it do that? Imho, this should definitely be the standard behavior because of its ease of use and the consistency which comes along with it.

**Comment by JulianLai** [comment]
@m1cm1c I didn't do anything else, it just worked for my PC.

**Comment by m1cm1c** [comment]
@JulianLai I just reinstalled Deepin 15.3 and it still doesn't work.

**Comment by JulianLai** [comment]
@m1cm1c I'm not running Deepin OS, I'm using antergos which is based on Arch Linux, and it offers the latest Deepin 15.4 Desktop.
Maybe you can try the Deepin 15.4 RC?

**Comment by m1cm1c** [comment]
@JulianLai I tried and recorded it with Deepin 15.3 before posting my previous comment. Unfortunately, I'm at a super slow internet connection. That video is uploaded by now and is available at https://www.youtube.com/watch?v=1ekYoOF_9EU.

After your proposal, I installed Deepin 15.4 RC and tried and recorded it again. The video is half-uploaded by now and will be available at https://youtu.be/Fr55ByoQRb4 in about one to one-and-a-half hours from now. It shows that while closing an application when putting the mouse pointer into a corner and clicking M1 *is possible* in Deepin 15.4 RC, it can't be used to close a window *quickly* and without paying much attention to it, which is the entire point of having a the closing button in a corner of the screen.

**Comment by hualet** [comment]
@m1cm1c 15.3 doesn't support the feature. As to 15.4, I think the whole point is that it's not that easy to trigger, right ?

@sonald

**Comment by sonald** [comment]
@m1cm1c how fast is fast enough in your mind ? I can close 5 to 6 windows in a second with this featrue. what's your expectation?

**Comment by m1cm1c** [comment]
@hualet It's one of the most-frequently used features of graphical desktops. Why would you want to artificially delay this? How frequently do you accidentally close windows you didn't mean to close? I mean you have to place your mouse pointer in a specific location and press M1. Of the entire time I have been using computers, I don't recall a single incident of me accidently closing a window.

**Comment by trunapushpa** [comment]
@hualet 15.4.1 still has this unresolved. I support @m1cm1c. Even I think why would you make it difficult for the 'close window hot corner' to trigger. It is really annoying. If that was intentionally done, then is there anything that can be done for it to get easily triggered?

**Comment by sonald** [comment]
I'm not quite sure if it's the problem of not easy to be triggered or just you dont get used to the new way to activate it.  I personally think it's easy enough to trigger right now.

**Comment by trunapushpa** [comment]
It gets triggered only when cursor is moved "slowly" to the upper-right
corner.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
