### ISSUE TITLE
在特效模式下最小化还原后不能再次最小化

### ISSUE THREAD

**Issue by luosoy** [linuxdeepin/developer-center#2720]
当开启特效模式后，deepin的应用如：deepin-terminal  deepin-file-manager 等，最小化还原后不能再次最小化，只能关闭应用后才能再次最小化。但是关闭特效模式后没有这个问题。

[luosoy@luosoy-PC logs]$ screenfetch

 ██████████████████  ████████     luosoy@luosoy-PC
 ██████████████████  ████████     OS: Manjaro 20.0.3 Lysia
 ██████████████████  ████████     Kernel: x86_64 Linux 5.6.19-2-MANJARO
 ██████████████████  ████████     Uptime: 21m
 ████████            ████████     Packages: 1218
 ████████  ████████  ████████     Shell: bash
 ████████  ████████  ████████     Resolution: 1366x768
 ████████  ████████  ████████     DE: GNOME
 ████████  ████████  ████████     WM: KWin
 ████████  ████████  ████████     GTK Theme: Adwaita [GTK2/3]
 ████████  ████████  ████████     Icon Theme: Adwaita
 ████████  ████████  ████████     Font: Cantarell 11
 ████████  ████████  ████████     Disk: 130G / 289G (46%)
 ████████  ████████  ████████     CPU: Intel Core2 Duo T6600 @ 2x 2.2GHz
                                  GPU: GeForce G210M
                                  RAM: 1464MiB / 1984MiB

**Comment by meiyixiang** [comment]
This issue has been fixed please upgrade to the latest version 20.4
