### ISSUE TITLE
Setting not updated when navigating application lists using keyboard arrow

### ISSUE THREAD

**Issue by laradvance** [linuxdeepin/developer-center#2727]
In Notofication setting, when using keyboard arrow to move to anothet apps, the setting tab not change. This make wrong setting
![image](https://user-images.githubusercontent.com/35951442/94795709-4a737300-0410-11eb-9e6e-b93b119191ea.png)

**Comment by meiyixiang** [comment]
Your current version is too low, but I don't find the problem you mentioned

**Comment by meiyixiang** [comment]
10/5000 
The latest version is 20.4
