### ISSUE TITLE
Synaptics, Syndaemon usage

### ISSUE THREAD

**Issue by skiv71** [linuxdeepin/developer-center#2728]
Hi,

I see the latest Deepin 20 detects my install of Synaptics driver (over libinput) and even runs syndaemon with the toggle to disable typing on mouse move.

However, the 2 sec release time is too long...

So... Hey, does anyone know where deepin stores the cli args is starts syndaemon with?

I've hunted throughout the usual places and not found any reference to it.

Is it hard coded?

**Comment by Zeno-sole** [comment]
install  xserver-xorg-input-synaptics ,  syndaemon -i 1 -t -K -R -d    this might help you

**Comment by Zeno-sole** [comment]
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue
