### ISSUE TITLE
Night shift > DDE WM flickering black.

### ISSUE THREAD

**Issue by martinlindelof** [linuxdeepin/developer-center#2729]
Display > Brightness > Night Shift [ENABLED]
Gaming with Steam

After once resizing windows causes black flickering.

Work-around.
Disabling Night Shift, and re-enabling Night Shift solves the problem. (Logout required sometimes)
Bug might be with Night Shift (Redshift Application)

**Comment by SuperEffie** [comment]
Sorry for no reply for so long time, and thanks for your feedback. Our system has been updated to deepin v20.5 and our dde control-center version has been updated to 5.5.16.2. Your issue seemed to have been resolved and we are unable to reproduce it. If your problem still exists, please contact us and we will contact the developers to help deal with it.
