### ISSUE TITLE
Titlebar of Deepin Image Viewer has wrong icon after dragging to restore from maximum

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#273]
Steps to reproduce:

- Maximum the window
- Drag the titlebar down to restore the window
- See the icon is still "restore", which should be "maximum".

**Comment by hualet** [comment]
Should be bug of deepin-image-viewer, dde-file-manager has no similar issue. @pangpangpang3

**Comment by pangpangpang3** [comment]
This bug has been fixed,  please update later. @felixonmars

**Comment by JulianLai** [comment]
@pangpangpang3 請問這個 deepin-image-viewer 造成 Krita 無法開啟的 bug 有解嗎？
```
/usr/lib/qt/plugins/imageformats/libxfreeimage.so from deepin-image-viewer package makes Krita crash (segmentation fault, QIODevice::seek: Invalid pos: -18 ).
（引用自 https://bbs.archlinux.org/viewtopic.php?id=223083）

刪除掉 libxfreeimage.so 後可以正常執行 Krita，但這樣 Deepin Image Viewer 不會有問題嗎？
```
#251

**Comment by pangpangpang3** [comment]
只是会减少对图片格式的支持，一些常用的格式如jpg, png　不会有问题，抱歉那个bug确实存在，后面会找方式解决！
