### ISSUE TITLE
Right click on touchpad not working after Deepin 20 1003 update

### ISSUE THREAD

**Issue by hbarsaiyan** [linuxdeepin/developer-center#2730]
Right click physical button on touchpad is not working after Deepin 20 1003 update. It was working fine on 1002. I have attached the information about touchpad below.

![Screen Capture_deepin-devicemanager_20201030181020](https://user-images.githubusercontent.com/37732050/97706129-2ff9eb80-1adb-11eb-9bee-235fa8def635.png)

**Comment by BLumia** [comment]
Sorry for the super late response since we were not checking issue reports that were created outside the developer-center repo.

Does this issue still happen on your computer with deepin v20.4?

**Comment by hbarsaiyan** [comment]
I don't have that laptop anymore 😅
