### ISSUE TITLE
Sound output selector doesn't work with Bluetooth LDAC output

### ISSUE THREAD

**Issue by benpaulsen-qut** [linuxdeepin/developer-center#2731]
I have installed pulseaudio-modules-bt and libldac to take advantage of the higher audio quality for my Bluetooth headphones. However, when I connect to my headphones they do not appear as an output in Deepin control center or in the dock volume selector. I was able to select the LDAC output and change the volume by installing the pavucontrol tool as shown in the screenshots. It's still annoying though because I can't change the volume with the tray icon because it doesn't show the output even when it is currently in use. If you need more info/clarification I'm happy to help.

![Screen Capture_pavucontrol_20201110193752](https://user-images.githubusercontent.com/64248614/98657420-94476580-238d-11eb-8085-a0051e3f94a3.png)
![Screen Capture_select-area_20201110193733](https://user-images.githubusercontent.com/64248614/98657430-95789280-238d-11eb-8722-5cd8c4b9d95d.png)

I'm running the latest version of Deepin and I installed the high-quality Bluetooth codecs using this script: https://github.com/lagerimsi-ds/debian-buster_bluetooth_aptX-LDAC/

**Comment by Zeno-sole** [comment]
@babyfengfjx  Please verify if our latest version also has this problem

**Comment by SuperEffie** [comment]
Sorry for no reply for so long time, and Thanks for your feedback. Our system has now been updated to 20.5 and our dde control-center version has been updated to 5.5.16.2. Your issue seemed to have been resolved and we are unable to reproduce it. If your problem still exists, please contact us and we will contact the developers to help deal with it.
