### ISSUE TITLE
11月25日更新后DDE控制中心的音频输出设备切换无效

### ISSUE THREAD

**Issue by Fredoong** [linuxdeepin/developer-center#2734]
2020年11月25日Deepin20的1003版本推送了一波更新，更新后dde-control-center(5.3.0.80-1版本)里的音频输出设备Output Device选项切换直接不生效了，而且直接点击dde-dock上声音按钮也无法切换音频设备了。据观察，出现此问题的计算机似乎都是笔记本电脑。
https://bbs.deepin.org/post/206703，官方更新公告下已有多人反映遇到此问题。结合各IM软件的群聊反馈，可以判断这是个大面积出现的问题。希望官方团队尽快修复此BUG，很影响使用。

**Comment by babyfengfjx** [comment]
非常感谢您的反馈，抱歉我们长时间未进行沟通，当前问题我们在最新版本中发现正常，我们先关闭此issue,如果该问题仍旧存在，或者有新的问题，还请随时反馈给我们～
