### ISSUE TITLE
Personalization - Rounded Corner : no effect

### ISSUE THREAD

**Issue by KimHono** [linuxdeepin/developer-center#2736]
Hi!
_Rounded Corner_ in _Personalisation_ menu was almost working on previous version of dde-control-center. User choice had effect but wasn't memorized.
I recently upgraded to `5.3.0.82-1` version. The situation has worsen : now, user choice has no effect. And therefore, it's impossible to verify choice memory.

My system is ARCH : 5.10.5-arch1-1
Kwin version `5.20.5-1`
dde-kwin version `5.2.0.13-1`

**Comment by BLumia** [comment]
Sorry for the late reply. Please track the follow up of this issue at https://github.com/linuxdeepin/developer-center/issues/2508. Thanks!
