### ISSUE TITLE
dde-control-center: after a while it takes a few seconds (~30sec) to open it

### ISSUE THREAD

**Issue by hhaim** [linuxdeepin/developer-center#2737]
logout/login solves the issue. The version is 20.1 latest.

**Comment by BLumia** [comment]
According to https://github.com/linuxdeepin/developer-center/issues/2737#issuecomment-763264940 this issue should be resolved now. Please update related package and see if that still happens.

If you got any similar issues, please consider creating a new issue with necessary detailed information so we can look into it. Thanks!
