### ISSUE TITLE
Can't minimize Deepin apps after selecting "Window effect"

### ISSUE THREAD

**Issue by KimHono** [linuxdeepin/developer-center#2739]
Hi !
I noticed this curious issue in the Control Center:
Go in `Personalization`, select `General`, then activate `Window Effect`.

And now, open any Deepin app (file manager, terminal, PDF reader...): it's possible to minimize this window only 1 time.
Further tries by clicking on "minimize" button will have no effect on this app window !

**Comment by openarun** [comment]
Related to https://github.com/UbuntuDDE/bugs/issues/110

**Comment by babyfengfjx** [comment]
After several versions of comparison, the latest version seems to have no such problems, thank you for your feedback, you can use the latest version to see if the problem is solved.

**Comment by babyfengfjx** [comment]
Not sure if the problem exists in the latest version, if there is still a similar problem in the new version, you are welcome to activate the issue, the current issue we first closed.
