### ISSUE TITLE
控制中心字體大小設定不會套用在 QT 的程式上，目前找到個暫時的解決方法

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#274]
OS: antergos（基於 Arch）

#236 #160 
安裝 qt5-styleplugins
並在 `/etc/environment` 內加入 `QT_STYLE_OVERRIDE=gtk2` 即可

**Comment by hualet** [comment]
实时更改？

**Comment by JulianLai** [comment]
@hualet 結果試了一下，控制中心內調整字體大小並沒有辦法影響 QT 的字體大小，他是由 qt5ct 來決定的

**Comment by JulianLai** [comment]
@hualet 結果發現了一個更簡單的方法，根本就不用安裝 qt5ct，直接在 `/etc/environment` 加入 `QT_STYLE_OVERRIDE=gtk2` 就好，這樣一來連控制中心調整大小都有作用了，雖然還是沒辦法完全實時更改

**Comment by hualet** [comment]
可能是Arch上已经没有了gtk2的style plugin? @felixonmars  正常的话，DDE下的Qt程序默认style就是gtk2才对。

**Comment by hualet** [comment]
我暂时还不知道为什么你那里更改字体大小不生效，正常的话DDE下面Qt程序默认就是gtk2的style。

**Comment by JulianLai** [comment]
#236 和這位 @Acris  同問題

**Comment by felixonmars** [comment]
@hualet 这是在哪里设置的？好像很多人遇到这个问题……

**Comment by hualet** [comment]
duplicate issue with https://github.com/linuxdeepin/developer-center/issues/342#issuecomment-318972115
