### ISSUE TITLE
Fingerprint login and trackpad gestures not working on Huawei MateBook 

### ISSUE THREAD

**Issue by mickystevo85** [linuxdeepin/developer-center#2742]
Hi just raising a future hopefull fix. On my Huawei MateBook 14 2020 AMD edition laptop, the fingerprint login on the power button and trackpad gestures don't work. Hopefully this can be implemented in a future update. Thanks.

**Comment by Zeno-sole** [comment]
@babyfengfjx Please check if the latest version supports it

**Comment by Zeno-sole** [comment]
Sorry, this requires the manufacturer to provide the corresponding driver, we are temporarily unable to adapt
