### ISSUE TITLE
deepin-pw-check: Add a build dependency to the master page

### ISSUE THREAD

**Issue by linuxbuh** [linuxdeepin/developer-center#2747]
Add the build dependency to the main page https://github.com/linuxdeepin/deepin-pw-check

**Comment by BLumia** [comment]
Sorry for the super late response since we were not looking into issues that were reported outside the developer-center repo.

Before we work on the README, you can check the build dependency from [`debian/control` file](https://github.com/linuxdeepin/deepin-pw-check/blob/master/debian/control).

**Comment by BLumia** [comment]
Resolved in https://github.com/linuxdeepin/deepin-pw-check/pull/2 :)
