### ISSUE TITLE
External display does not connect

### ISSUE THREAD

**Issue by LuciusV** [linuxdeepin/developer-center#2752]
When I connect external monitor or projector, it does not appear in monitor section of contror center and projector does not recognize laptop either.

**Comment by SuperEffie** [comment]
Thanks for your feedback.Does this issue still exist on deepin v20.5?If this issue still exists, you can contact with us and give us a screenshot after entering the command 'sudo apt install inxi -y && inxi -F' in the terminal.We will contact with developers to deal with it.

**Comment by Zeno-sole** [comment]
Are you using closed source drivers?

**Comment by LuciusV** [comment]
I am using Intel card. Nvidia card doesn't work for me with any drivers.
(Both nvidia card and external display work on Windows - I have dual boot)

**Comment by Zeno-sole** [comment]
I noticed that your machine has NVIDIA devices. NVIDIA devices usually require closed source drivers to work better on linux. Does the default closed source driver not work with your graphics card?

**Comment by LuciusV** [comment]
If I use NVIDIA close source driver, OpenGL renderer is still Intel, bumblebee fails to use Nvidia card and external display also doesn't work

**Comment by Zeno-sole** [comment]
Even if the intel gpu uses an external display, it should be normal. You can replace the kernel version 5.15 to see if it works normally.

**Comment by Zeno-sole** [comment]
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue
