### ISSUE TITLE
USB Headset stops working after a while

### ISSUE THREAD

**Issue by vincenzocaselli** [linuxdeepin/developer-center#2753]
Hi,
I'm having a problem with my USB headset (Sennheiser PC 8 USB Headband Headset).
When I start the os I usually check the **Control Center / Sound**,  check that **Input** and **Output** are correctly associated to this device.
Then I start a call (Google meet) and very often, at some point in the middle of the conversation, the headset stops working; it even disappears from the Control Center settings (only in the **Output Device** list)
![image](https://user-images.githubusercontent.com/3648713/92298981-c46a2680-ef4e-11ea-9590-4af9e8bc0a21.png)

If I restart the system I can get it back working ok, for a while.
I would exclude a hw problem with the headset since it's working flawlessly in Windows.
(I never had problem instead with a jack headset)
Any suggestions?

**Comment by babyfengfjx** [comment]
Thanks for your feedback,we are very sorry that we did not communicate for a long time,  the current issue we found in the latest version of normal, we first close this issue, if there are new issue later,  please feedback to us.
