### ISSUE TITLE
BUG: When lid is closed and an external monitor is plugged, the integrated monitor still remains on.

### ISSUE THREAD

**Issue by diegosperes** [linuxdeepin/developer-center#2763]
Not sure if it's the righ place to post this bug, I have been seraching in the internet a way to close the laptop lid and turn off only the integrated monitor when a external monitor is plugged, this works fine on ubuntu 20.04 LTS, my current laptop is Dell XPS 9500.

I learned a bit about xrandr a configuration utility that can be used to turn off the integrated monitor, however don't know how LightDM manage the lid closed event, I believe control center should take care of it but I might be wrong.

**Comment by Zeno-sole** [comment]
The monitor can be closed by closing the lid in the control center

**Comment by Zeno-sole** [comment]
由于长时间未收到回复，缺少必要信息，关闭该 issue,如果问题仍然存在可以申请重新打开该 issue

**Comment by vampywiz17** [comment]
This problem is still exist:

https://github.com/linuxdeepin/developer-center/issues/3552

**Comment by BLumia** [comment]
> This problem is still exist:
> 
> #3552
> 
> Please re-open it!

@vampywiz17 let's track this issue in #3552 then :)
