### ISSUE TITLE
添加国际版Firefox为默认浏览器无效

### ISSUE THREAD

**Issue by dreamtale90** [linuxdeepin/developer-center#2765]
控制中心软件版本：
`ii  dde-control-center                            5.4.23-1                                    amd64        New control center for Deepin Desktop Environment,`
火狐版本：应用市场安装
`ii  org.mozilla.firefox-nal                       89.0.1                                      amd64        火狐浏览器国际版`

操作步骤：在控制中心添加"/opt/apps/org.mozilla.firefox-nal/files/firefox"或者添加对应的desktop文件都提示无效，点击URL时只会新启动一个firefox窗口并打开主页，而不是链接url
desktop内容如下：
```
[Desktop Entry]
Exec=/opt/apps/org.mozilla.firefox-nal/files/firefox
Icon=firefox
Name=firefox-nal
Name[zh_CN]=火狐浏览器国际版
Terminal=false
Type=Application
X-Deepin-AppID=firefox-nal
X-Deepin-CreatedBy=com.deepin.dde.daemon.Launcher
X-Deepin-Vendor=user-custom
```

问题怎么解决，是操作方式问题，还是bug？

**Comment by shenmo7192** [comment]
Exec="/opt/apps/org.mozilla.firefox-nal/files/firefox" %U

**Comment by SuperEffie** [comment]
感谢您的反馈，目前deepin v20.5上dde-control-center的最新版本是5.5.16.2-1，控制中心>默认程序>网页目录下，勾选火狐浏览器国际版，即可成功设置火狐浏览器为默认浏览器。您可以尝试操作一下，如果问题依然存在，可以与我们取得联系。我们会联系开发帮您定位解决这个问题。

**Comment by dreamtale90** [comment]
感谢你的回复，目前20.5倒是没有点击URL会打开新窗口的问题了，这也可能是浏览器问题。默认浏览器这个控制中心里添加后还是提示未生效（黄色字体），但在火狐设置过默认浏览器后有效，现在使用没有问题。

**Comment by SuperEffie** [comment]
您方便提供下控制中心添加默认浏览器提示未生效的截图吗？或者提供下详细的操作步骤，我们会进行分析是否是问题。

**Comment by SuperEffie** [comment]
感谢您提供的截图，我们已经跟踪过这类问题，目前开发者定位是第三方应用提供的desktop文件的问题，需要第三方应用来适配我们的系统。目前提交研发团队再次评估，看是否能找到规律，兼容这类应用。问题有后续进展，我们会在这通知您。

**Comment by SuperEffie** [comment]
您提出的问题在deepin v20.6中已经修复了，您可以进行验证，现在我先将该issue关闭。期待您为我们提供更多的建议哦~
![截图_dde-control-center_20220617145347](https://user-images.githubusercontent.com/58986464/174242876-73c10666-aa14-4b41-ab07-55d1d0dc578c.png)
