### ISSUE TITLE
arch系统的控制中心多了一个开发者模式

### ISSUE THREAD

**Issue by weclix** [linuxdeepin/developer-center#2766]
平台：archlinux+dde桌面
 问题描述：dde-control-center中有一个开发者选项，不能点击没什么作用。这个选项应该是UOS的功能建议删除
![image](https://user-images.githubusercontent.com/42332005/125882483-e5cf3816-a244-4894-b460-9a7b23616f47.png)

**Comment by justforlxz** [comment]
内部已提交修改

**Comment by weclix** [comment]
![图片](https://user-images.githubusercontent.com/42332005/165689665-a0a1fc5e-1b08-440a-adda-39b4feeef204.png)

**Comment by BLumia** [comment]
> ![图片](https://user-images.githubusercontent.com/42332005/165689665-a0a1fc5e-1b08-440a-adda-39b4feeef204.png)

主线代码修复了但 Arch 上还没有打包最新版本的控制中心。

有问题建议开新的 issue 哦，这样跟进问题会更方便一些，毕竟旧问题和新问题的现象可能相似，但环境和诱因可能是不同的，有必要的话可以在新的 issue 中链接到旧的 issue 里。
