### ISSUE TITLE
[Bluetooth] Automatic connect not working

### ISSUE THREAD

**Issue by imHamo** [linuxdeepin/developer-center#2773]
After link my headphone bluetooth for first time ever it work fine
then next day when i turn on my bluetooth headphone from power button . deepin bluetooth detect it and connect to it and show " Connected" but it's not connected. it's Fake

i have every time i turn on my bluetooth . i have to go to control center disconnect the headphone then Reconnect manually then it will work fine

Please Watch this video it's explain better . the issue is from Deepin 15.10 and it's never get fixed

- When i turn on my Bluetooth Head phone Deepin automatic show it's connected ( but it's Fake)
- i need to disconnect the headphone from control center
- then i click on connect  again. Every time i decide to use my headphone

Please Watch This video it's explain everything . thanks
https://streamable.com/6pcbs3

**Comment by Zeno-sole** [comment]
Sorry for taking so long to deal with the problem, does the latest 20.5 still have this problem?

**Comment by Zeno-sole** [comment]
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue
