### ISSUE TITLE
There should be a default return function on src/frame/window/protocolfile.cpp Line 142

### ISSUE THREAD

**Issue by hillwoodroc** [linuxdeepin/developer-center#2775]
https://github.com/linuxdeepin/dde-control-center/blob/a3ac54f244d0ae5c6315cba993276570497715cd/src/frame/window/protocolfile.cpp#L142

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/dde-control-center/blob/52c86a908bb79caf6d4c83b321a9cb451d2c10e0/src/frame/window/protocolfile.cpp#L142

应该已经没问题了。顺便，后续欢迎 PR~
