### ISSUE TITLE
接上手機後會彈出怪怪的視窗，並且 Dock 會出現破圖

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#278]
![deepin 20170423100905](https://cloud.githubusercontent.com/assets/20014762/25310317/74161112-2814-11e7-85f3-ee1dd4bec172.png)
![deepin 20170423100930](https://cloud.githubusercontent.com/assets/20014762/25310318/745356bc-2814-11e7-8ee2-3f32b59e8f27.png)

**Comment by felixonmars** [comment]
I believe this is an old issue that was fixed some time ago. Are you able to reproduce it?
