### ISSUE TITLE
[BUG] Searching doesn't work with Polish translation

### ISSUE THREAD

**Issue by raspin0** [linuxdeepin/developer-center#2780]
https://user-images.githubusercontent.com/39202451/150836242-a697291e-9c77-4a6c-905b-49bffa8e7e23.mp4

It does not reproduce with English locales.

**Comment by SuperEffie** [comment]
Thanks for your feedback.The issue has been confirmed to exist in the deepin v20.5 if the system language is Polish,French and Spanish.It has been reported to the developer, and we will inform you after the fix.

**Comment by BLumia** [comment]
@SuperEffie could you check if it also exists in v23 control center? Please let me know if it still exists. Thanks!

**Comment by SuperEffie** [comment]
@BLumia It doesn't exist in v23 control center.
![Zrzut ekranu_dde-desktop_20230306155526](https://user-images.githubusercontent.com/58986464/223053851-15ffd825-341b-4f06-ac59-2083195ab5e7.png)

**Comment by SuperEffie** [comment]
We will not fix this problem in the deepin v20, but the relevant code has been reconstructed in v23, and this problem has been solved. Now I will close this issue first. Welcome to feedback more issues for us.
