### ISSUE TITLE
Common Date Format Types are missing

### ISSUE THREAD

**Issue by DarkPurpleKnight** [linuxdeepin/developer-center#2782]
In the date format setting there are only different variants of the ISO format (_year-month-day_) to choose from. Other common [Date Format Types](https://docs.oracle.com/cd/E41183_01/DR/Date_Format_Types.html) would be _day-month-year_ or US specific _month-day-year_.

**Comment by BLumia** [comment]
Sorry for the late response, please track this issue in https://github.com/linuxdeepin/developer-center/issues/1932, thanks!
