### ISSUE TITLE
升级20.4后控制中心里没有网络配置，托盘也没有网络连接图标

### ISSUE THREAD

**Issue by dreamtale90** [linuxdeepin/developer-center#2783]
![image](https://user-images.githubusercontent.com/15827447/156088784-ccec1836-55fd-430a-9b61-9845fb691027.png)
使用非常不便。

**Comment by Zeno-sole** [comment]
建议用控制中心进行升级, 手动升级可能存在掉推荐依赖的情况

**Comment by dreamtale90** [comment]
> 建议用控制中心进行升级, 手动升级可能存在掉推荐依赖的情况

是因为控制中心升级失败，不能进桌面，然后才命令行手动upgrade的。
