### ISSUE TITLE
bug: glyphs bad renderings

### ISSUE THREAD

**Issue by peteromio** [linuxdeepin/developer-center#2785]
## Describe the bug
Glyphs render incomplete as if it were only their half

## To Reproduce
use some rich text font (nerd font, powerline)

## Expected behavior
I would like them to be rendered like the old terminal
## Screenshots
![image](https://user-images.githubusercontent.com/51345178/94966651-a3eca800-04cb-11eb-87fa-9c87ad757039.png)
### Distro & Version
Deepin v20 1002
### Related package version
dde-terminal 5.2.25

**Comment by BLumia** [comment]
Sorry for the super late response.

I have tested it with [`logo-ls`](https://github.com/Yash-Handa/logo-ls) installed with the patched [Noto variant](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Noto/Mono/complete/Noto%20Mono%20Nerd%20Font%20Complete%20Mono.ttf) of the [`nerd-fonts`](https://github.com/ryanoasis/nerd-fonts). I didn't see the icon text clipped out as your screenshot. So I guess this should no longer exist on deepin v20.5.

If this still happens on the most recent version of deepin, please feel free to create a new issue with the following information provided so we can look into it:

- deepin-terminal version.
- install `qterminal` and do the same thing as you did in `deepin-terminal`, check if `qterminal` also have the same issue.
- the `nerd-font` version and the variant you use (the actual font name) and `logo-ls` version.

Thanks!
