### ISSUE TITLE
mysterious dock entries

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/developer-center#279]
Sometimes after login I see strange dock items like this: 
![ghost_window](https://cloud.githubusercontent.com/assets/11800714/25311443/6e9ab782-2801-11e7-8fd1-8dc02dd033dd.png)
Clicking on it does nothing, but when I click-right and select "close" the desktop goes black and all desktop icons disappear together with the wallpaper.

**Comment by oberon2007** [comment]
Seems like something goes wrong during creation of the dock during startup. Maybe this is also related to https://github.com/linuxdeepin/dde-dock/issues/38 , might even to https://github.com/linuxdeepin/developer-center/issues/250

**Comment by oberon2007** [comment]
To me it looks like the dock thinks that the desktop itself is a running application... 😜

**Comment by cyc0ol** [comment]
i have seen this as well and there's no way to remove it from the dock which is weird

**Comment by oberon2007** [comment]
When you right-click the icon you can quit the mysterious window. This will blackout the desktop but for me it autostarts aftewards and then it's fine...

**Comment by oberon2007** [comment]
Still not solved. I'm still getting these, at least in vbox:
![](http://i.imgur.com/j1NiVKZ.png)

**Comment by hualet** [comment]
Yeah, I've noticed this issue recently. 
It'll be sovled very hopefully if I can reproduce that issue again.

**Comment by oberon2007** [comment]
Someone on the Manjaro forum just caught the issue again. Have a look @hualet if there's maybe some more helpful information for you https://forum.manjaro.org/t/release-candidate-manjaro-deepin-17-0-2/26579/22?u=oberon

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
