### ISSUE TITLE
deepin-terminal -C "" 命令执行一次后，后续的 deepin-terminal -C 命令都没反应了

### ISSUE THREAD

**Issue by duanyao** [linuxdeepin/developer-center#2790]
步骤：
1. 在一个 deepin-terminal 窗口中执行命令 `deepin-terminal -C ""` ，弹出一个新的 deepin-terminal 窗口，旋即消失。
2. 重复上一步多次。

实际结果：

后续的 `deepin-terminal -C ""`  命令都没反应了，没有弹出新的 deepin-terminal 窗口。实际上，-C 的参数不留空也是一样的。

期待的结果：

后续的 `deepin-terminal -C ""`  命令应当与第一次一样，弹出新的 deepin-terminal 窗口。

关闭所有的 deepin-terminal 窗口再重新打开，可以恢复。

deepin-terminal 版本是 5.4.0.6-1 。

**Comment by SuperEffie** [comment]
感谢您的反馈，如果想要输入命令打开新的终端窗口且保持，需要输入命令deepin-terminal -C "" --keep-open即可哦。
若有其它的疑问欢迎给我们留言~

**Comment by duanyao** [comment]
> 感谢您的反馈，如果想要输入命令打开新的终端窗口且保持，需要输入命令deepin-terminal -C "" --keep-open即可哦。 若有其它的疑问欢迎给我们留言~

我的需求就是打开新的终端窗口，执行指定的命令，然后窗口消失，所以不能带--keep-open选项。
不过，我发现deepin-terminal 5.4.39 已经不存在此问题了，所以此issue算是解决了。
