### ISSUE TITLE
执行应用后闪退

### ISSUE THREAD

**Issue by wwyd123456** [linuxdeepin/developer-center#2791]
当执行`deepin-terminal --keep-open -e ls`或者`deepin-terminal --keep-open -e python 1.py`跳出的终端仍然立刻闪退，请问`--keep-open`这个命令有什么作用，有没有类似于konsole的`--hold`命令，在执行完程序后可以不立刻退出。

**Comment by SuperEffie** [comment]
感谢您的反馈，现在我们的系统已经更新至deepin v20.5版本，终端版本更新至5.4.28。您提出的终端执行完命令后立即闪退的问题我们复现不到了，您也可以尝试使用“deepin-terminal --keep-open -C”命令。因为您长时间没有回复，我现在先关闭这个issue。如果您的问题依然存在，可以申请重新打开这个issue。那样我们会联系研发人员帮忙定位解决这个问题。
