### ISSUE TITLE
How to set the number of rows to roll back.

### ISSUE THREAD

**Issue by zhouchuanfu** [linuxdeepin/developer-center#2797]
My terminal log output is very long, but often the ones in front can’t be seen. I don't want to save to file every time. Is there any solution?

**Comment by Zeno-sole** [comment]
You can use the right-click to find function

**Comment by Zeno-sole** [comment]
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue
