### ISSUE TITLE
Incorrect icons for Deepin after change to another icon theme under archlinux

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/developer-center#28]
Hello everyone! :)
Thank you all for you great work on developing Deepin. You are all awesome! :laughing: 
I would like to draw your attention to a little issue with the launcher icon: As soon as you are using a different icontheme this icon in the dock is lost because it seems to only exist in deepin-icon theme and none of the usual themes falls back to deepin-theme of course.
Would it maybe be an option to install the launcher icon to the hicolor directory?

**Comment by oberon2007** [comment]
In the case of the deepin-multitasking-view icon it works perfectly no matter which icontheme I use. So this could serve as a model for a good solution probably :)

**Comment by fasheng** [comment]
Yes, there are hicolor links in deepin-icon-theme under Deepin, but only implemented through the Debian package methods. Anyway, it's not a good style...

**Comment by oberon2007** [comment]
Ah, maybe then it has to be solved in the dock itself? How are the other entries dealing with that? multitasking-view and all the icons in the notification area are always displayed fine. Just the launcher icon has that problem...

**Comment by oberon2007** [comment]
also deepin-music and deepin-movie always use the deepin-icons in another theme.

**Comment by fasheng** [comment]
@oberon2007 Because deepin-musci and deepin-movie put there icons to `/usr/share/icons/hicolor/`~

Why not we use **Makefile** instead of **debian/links** in deepin-icon-theme? :)
@leaeasy @gs342

**Comment by snyh** [comment]
@fasheng  it seems avoid conflicting file with other packages

**Comment by oberon2007** [comment]
You could also have **deepin-launcher** install its own icon or a symlink to hicolor :)
I have worked around this for now by doing that with **deepin-iconthemes-manjaro** package. I would have to remove it from there in time in case you decide to add it to one of the deepin-packages ... ;)

**Comment by fasheng** [comment]
I see, how about support it in Makefile firstly, and will be helpfull for other distros.
BTW: It's not urgency ;)

**Comment by hualet** [comment]
DDE specific icons are also linked to hicolor folders by deepin-icon-theme while deepin Apps specific icons are taken care of by Apps themselves, long over due issue solved :)
