### ISSUE TITLE
Icons on dock not changing

### ISSUE THREAD

**Issue by ag14774** [linuxdeepin/developer-center#280]
The icons on the dock do not change when I change icon theme. Not only that, some applications that used to have icons, e.g Pulse Audio Control appear as shown below:
Dock:
![deepinscreenshot20170424001023](https://cloud.githubusercontent.com/assets/10788242/25318243/972158a6-2882-11e7-9a92-2bc8c13b29f1.png)

Launcher:
![deepinscreenshot20170424001051](https://cloud.githubusercontent.com/assets/10788242/25318245/98eef9b8-2882-11e7-8033-9af0bbfc32f6.png)

Switching to a different icon theme that does have an icon for Pulse Audio still results in the 'gear' icon on the dock

**Comment by oberon2007** [comment]
Are you using **qt5ct** by  any chance? If that's the case you should remove it because it blocks deepins icon settings.

**Comment by ag14774** [comment]
I removed it and now when I change the icon theme, the dock icons change as they should. Pulse audio still doesn't have an icon with the default deepin theme but I guess I can just switch to a another theme

**Comment by ag14774** [comment]
On Flattr Dark, wired connection has no icon at all. It's just a blank space on my dock. Are those icon problems just me or do other have it as well?

**Comment by SalahAdDin** [comment]
You are right, in my case with `gitkraken`: have icon in launcher, but it haven't in the dock. And yes, `deepin icons` is not completely yet.

**Comment by sbwtw** [comment]
It should be fixed in the latest version

**Comment by SalahAdDin** [comment]
@sbwtw when?

**Comment by sbwtw** [comment]
@SalahAdDin please upgrade to deepin 15.5 dde-dock 4.5.9-2

**Comment by SalahAdDin** [comment]
![deepin-dock](https://user-images.githubusercontent.com/5034215/36628922-341ff53a-1960-11e8-979e-89ec2e217dbd.png)
@sbwtw
