### ISSUE TITLE
deepin-terminal dose not respond while rolling the wheel on VIM

### ISSUE THREAD

**Issue by hillwoodroc** [linuxdeepin/developer-center#2801]
The old gtk version work fine.

https://user-images.githubusercontent.com/1880237/130232335-dbd836d2-7930-4d6f-b628-bf9081afb009.mp4

**Comment by BLumia** [comment]
Cannot reproduce this on `deepin-terminal 5.4.28` under Arch Linux and deepin v20.5, maybe fixed in previous updates.

Feel free to create another issue if you still have this issue on the most recent version you can get.
