### ISSUE TITLE
最小化按钮没有反应

### ISSUE THREAD

**Issue by ayasa520** [linuxdeepin/developer-center#2802]
点击窗口右上角的最小化按钮没有反应，其他按钮工作正常。点击托盘中的图标可以正常最小化。

**Comment by BLumia** [comment]
抱歉现在才进行答复，我们之前很少关注 developer-center 之外汇报的 issue...

目前在 deepin-wm 和 deepin-kwin 下都没能复现这个问题，由于是个比较老的 issue 了，可能问题在后续过程的更新中已解决了，所以就先关掉这个 issue 了。

如果这个问题在你所可获得的最新版本仍然存在的话，可以开个新的 issue 报告，并附带下你所使用的窗口管理器的版本号以及别的你觉得有用的信息，以便我们进一步排查问题，感谢！
