### ISSUE TITLE
Bug while finding with CTRL + SHIFT + F

### ISSUE THREAD

**Issue by AghayevAli** [linuxdeepin/developer-center#2809]
As you see at the screen at the bottom nothing happened when I try to find something with ctrl + shift + f.
I like this terminal more than others and this function is so useful for me. Can you please fix it ? 

![image](https://user-images.githubusercontent.com/66011208/145666257-a41f57df-d358-4ae7-9856-84ff95e5348d.png)

**Comment by yxsos** [comment]
I tried in the 20.5 version of the upcoming release, it is normal.Maybe you can update the terminal version after 3.31?

![image](https://user-images.githubusercontent.com/44915039/160557860-4f34cae1-081e-4a34-8e8f-89d1e04abfc2.png)
