### ISSUE TITLE
Opacity settings issue

### ISSUE THREAD

**Issue by jaitra1264** [linuxdeepin/developer-center#2814]
When I open the settings to change the opacity, it's hard to decide the opacity because the terminal window gets a little opaque when the settings window is open but when you close the settings it shows the actual opacity.

**Comment by BLumia** [comment]
Hi, I cannot reproduce this issue on `deepin-terminal 5.4.28-1` under `deepin v20.4`. Does this issue still happens on the most recent version you can get?
