### ISSUE TITLE
远程连接名称没有转义导致配置文件错误 Bug on remote server config file parsing

### ISSUE THREAD

**Issue by ZhongYic00** [linuxdeepin/developer-center#2815]
![image](https://user-images.githubusercontent.com/38401412/155059531-d7c56e3f-1643-4967-91a9-c3bb927ce28d.png)
如图，远程连接的名称中带有"[vnet]"时，由于未对其进行转义，会与配置文件的中括号混淆。
会导致终端远程连接列表中的列表项不断被莫名复制、重复
![image](https://user-images.githubusercontent.com/38401412/155059877-222ab9a2-52b4-47f4-b5eb-7dad373611a9.png)

**Comment by SuperEffie** [comment]
谢谢您的反馈，我已经复现了这个问题并提交bug单给到开发。可能解决这个问题需要花费一段时间，目前计划是在下个版本上修复该问题。如果问题解决了，我会通知到您

**Comment by SuperEffie** [comment]
您issue中提及的问题我们已经在deepin v20.7版本中修复了哈，您方便的话可以帮我们验证一下，现在我先将这个issue关闭了。
欢迎您为我们反馈更多的问题哦～
