### ISSUE TITLE
BUG - Screen flickering 

### ISSUE THREAD

**Issue by raspin0** [linuxdeepin/developer-center#2819]
To reproduce you have to play a game which will disable window effects and then restore it on exit. 
Restarting `kwin_x11` fixes the issue. 
The issue only present with Window Effects ON. 
NVIDIA GPU

https://user-images.githubusercontent.com/39202451/112728397-68d1ab80-8f27-11eb-866a-aac3ea17e67f.mp4

**Comment by BLumia** [comment]
Closing since [it doesn't reproduce anymore](https://github.com/linuxdeepin/developer-center/issues/2820#issuecomment-1083045811). Feel free to create a new issue if you got any other issue while using DDE.
