### ISSUE TITLE
[dde-dock] Bug with desktop entries

### ISSUE THREAD

**Issue by Urgau** [linuxdeepin/developer-center#282]
Hello,

I'm on ArchLinux and I'm using the last version of dde-dock but this bug is for many other version.
When I update a software who are docked into the dock, the desktop entry is rewrite (changement or not) and the dde-dock lose the connection with the software, the software is not anymore docked into the dock.

Can you solve this, it's very exasperating. Thanks you.

**Comment by hualet** [comment]
should've been fixed
