### ISSUE TITLE
BUG - Broken title bar

### ISSUE THREAD

**Issue by raspin0** [linuxdeepin/developer-center#2820]
The way to reproduce is the same as linuxdeepin/deepin-kwin#49, it breaks after leaving a game. 
Restarting `kwin_x11` fixes the issue.
The issue only present with Window Effects ON.
NVIDIA GPU

https://user-images.githubusercontent.com/39202451/112728658-a1be5000-8f28-11eb-860a-21b581436ed7.mp4

**Comment by Zeno-sole** [comment]
Do other programs have the same problem?

**Comment by raspin0** [comment]
https://github.com/linuxdeepin/developer-center/issues/2819 Also doesn't reproduce anymore

**Comment by BLumia** [comment]
Thanks for the follow up. I'll close it for now. Feel free to create a new issue if you got any other issue while using DDE.
