### ISSUE TITLE
Deepin 20.2.2: DAboutDialog can snap to resize and maximize

### ISSUE THREAD

**Issue by RigoLigoRLC** [linuxdeepin/developer-center#2824]
![image](https://user-images.githubusercontent.com/49363666/124343880-8cc91b00-dc01-11eb-991d-2fd0faaeb0d0.png)
![image](https://user-images.githubusercontent.com/49363666/124343883-92266580-dc01-11eb-89c5-c85472454408.png)

**Comment by SuperEffie** [comment]
Because this issue was submitted a long time ago, I will close it first. If it still exists in deepin v20.8, you are welcomed to create a new issue for us.Thank you~
Best wishes!
