### ISSUE TITLE
{BUG} Dock Crashing For No Reason

### ISSUE THREAD

**Issue by ghost** [linuxdeepin/developer-center#2827]
so whenever i try to change the wallpaper the dock crashes and does not come back until the next reboot
i am unable to set the wallpaper too
system
arch linux (x86_64)
4 gb of ram
latest deepin desktop

**Comment by BLumia** [comment]
Closing since reporter account is deleted :/

For people who have similar issues on the most recent version, please consider creating a new issue with the necessary detailed information so we can look into it. Thanks!
