### ISSUE TITLE
Dock Current volume label

### ISSUE THREAD

**Issue by ag14774** [linuxdeepin/developer-center#283]
Sometimes the "Current volume: 50%" label on mouse over on the volume icon is a lot bigger than other times. I can always read the text so it's never smaller than the text. It's not really annoying, I just though I should report this.

![picture](https://cloud.githubusercontent.com/assets/10788242/25458067/554d8c92-2ad0-11e7-97c4-8d5249488ebe.png)
There are times where it's much bigger than this

**Comment by hualet** [comment]
@sbwtw

**Comment by ag14774** [comment]
Do we have any updates on this?

It's not getting any better: lol
![untitled](https://user-images.githubusercontent.com/10788242/27359515-65c04aa2-561c-11e7-96bd-b3b68ded09a9.png)

**Comment by sbwtw** [comment]
lol That's definitely a bug

**Comment by hualet** [comment]
that waiting to be solved by you for so long 😂
石博文 <notifications@github.com>于2017年6月21日 周三18:48写道：

**Comment by hualet** [comment]
@ag14774 how to reproduce this ?

**Comment by ag14774** [comment]
Can't figure out how this happens.

All I can say is that I change the volume by scrolling over the icon. I
also regularly check the volume by putting the cursor above the icon. But I
do not know whether this is what it causes the problem.

Sometimes when I check the volume, it gets a little bit bigger each time

**Comment by ag14774** [comment]
Okay I think this happens when I put the cursor above the icon, wait for the label to appear. Then scroll up to increase the volume a little bit(maybe by 10-15). Move the cursor back and over the icon again. If I am correct, the label will be very slightly bigger. If you keep doing this, you should see the difference

**Comment by hualet** [comment]
@ag14774 problem solved, just a trivial bug :)
see https://cr.deepin.io/23994

**Comment by ag14774** [comment]
Lol that was fast..thanks! I will close this now.
