### ISSUE TITLE
dde-dock 右鍵選單內容會被擋在視窗後面，但如果開啟控制中心就不會

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#285]
OS: antergos
![deepin 20170506234123](https://cloud.githubusercontent.com/assets/20014762/25773746/b02b9978-32b5-11e7-8bce-da743f3621a3.png)
![deepin 20170506234149](https://cloud.githubusercontent.com/assets/20014762/25773748/b0b0fb9a-32b5-11e7-9038-7e45ab1478bd.png)
![deepin 20170506234213](https://cloud.githubusercontent.com/assets/20014762/25773747/b083edc6-32b5-11e7-89d2-23e0e65ca60c.png)

**Comment by JulianLai** [comment]
@hualet 回家後更新了一下這問題就消失了

**Comment by JulianLai** [comment]
@
目前確定是開機完第一次登入一定會發生，必須要重新登入才能解決

**Comment by hualet** [comment]
额……本来说重启测试一下呢，后来干其他的就忘了，明天我到公司再测试一下看看

**Comment by hualet** [comment]
在deepin上并没有出现…… @felixonmars 要不要测试一下git版看看有没有这个问题？

**Comment by felixonmars** [comment]
我这里测试不出来这个问题……
