### ISSUE TITLE
無法複製文字到 GTK 的 APP，反過來則沒問題

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#287]
OS: antergos
https://youtu.be/pQjESj50oX4
不過 Deepin File Manager 內的檔名複製到 Deepin File Manager 內卻可以

（更新）現在觀察到的是無法複製文字到 GTK 的 APP，而 GTK 複製到其他則沒問題

**Comment by JulianLai** [comment]
結果這好像是 Arch 那邊的問題

**Comment by SalahAdDin** [comment]
Is a problem from `Arch` or from `GTK`.

**Comment by SalahAdDin** [comment]
I haven't this problem in Antergos. at least for now.

**Comment by oberon2007** [comment]
This should be fixed with **gtk 3.22.14**
see https://bugs.archlinux.org/index.php?do=details&task_id=54000

**Comment by SalahAdDin** [comment]
@JulianLai Yes, is fixed, i haven't these problem in `gnome 3.24`.
