### ISSUE TITLE
[cppcheck bug repot -- deepin-terminal ]  Problem summary of deepin-terminal  project  

### ISSUE THREAD

**Issue by cmdmspaint** [linuxdeepin/developer-center#2886]
deepin-terminal/3rdparty/terminalwidget/lib/BlockArray.cpp:282:19: error: Memory is allocated but not initialized: buffer1 [uninitdata]                                  
        delete [] buffer1;
 		   
deepin-terminal/3rdparty/terminalwidget/lib/BlockArray.cpp:340:19: error: Memory is allocated but not initialized: buffer1 [uninitdata]                                  
        delete [] buffer1;
                  
deepin-terminal/3rdparty/terminalwidget/lib/BlockArray.cpp:341:19: error: Memory is allocated but not initialized: buffer2 [uninitdata]                                  
        delete [] buffer2;
                  
deepin-terminal/src/remotemanage/serverconfigoptdlg.cpp:495:5: error: Non-local variable 'm_curServer' will use pointer to local variable 'config'. [danglingLifetime]
    m_curServer = &config;
    
deepin-terminal/src/remotemanage/serverconfigoptdlg.cpp:495:19: note: Address of variable taken here.
    m_curServer = &config;
                  
deepin-terminal/src/remotemanage/serverconfigoptdlg.cpp:493:54: note: Variable created here.
void ServerConfigOptDlg::resetCurServer(ServerConfig config)
                                                     
deepin-terminal/src/remotemanage/serverconfigoptdlg.cpp:495:5: note: Non-local variable 'm_curServer' will use pointer to local variable 'config'.
    m_curServer = &config;

**Comment by Echlorine** [comment]
执行命令 `cppcheck --library=qt '/home/echo/GitDownloads/deepin-terminal'`，检出如下3处错误。  
第1，2处，看了源代码感觉也没问题。
```
/home/echo/GitDownloads/deepin-terminal/3rdparty/terminalwidget/lib/kptydevice.h:259:16: error: Returning pointer to local variable 'tmp' that will be invalid when returning. [returnDanglingLifetime]
        return ptr;
               ^
/home/echo/GitDownloads/deepin-terminal/3rdparty/terminalwidget/lib/kptydevice.h:255:19: note: Pointer to container is created here.
            ptr = tmp.data();
                  ^
/home/echo/GitDownloads/deepin-terminal/3rdparty/terminalwidget/lib/kptydevice.h:253:24: note: Variable created here.
            QByteArray tmp;
                       ^
/home/echo/GitDownloads/deepin-terminal/3rdparty/terminalwidget/lib/kptydevice.h:259:16: note: Returning pointer to local variable 'tmp' that will be invalid when returning.
        return ptr;
               ^
```
```
/home/echo/GitDownloads/deepin-terminal/src/remotemanage/serverconfigoptdlg.cpp:495:5: error: Non-local variable 'm_curServer' will use pointer to local variable 'config'. [danglingLifetime]
    m_curServer = &config;
    ^
/home/echo/GitDownloads/deepin-terminal/src/remotemanage/serverconfigoptdlg.cpp:495:19: note: Address of variable taken here.
    m_curServer = &config;
                  ^
/home/echo/GitDownloads/deepin-terminal/src/remotemanage/serverconfigoptdlg.cpp:493:54: note: Variable created here.
void ServerConfigOptDlg::resetCurServer(ServerConfig config)

                                                     ^
/home/echo/GitDownloads/deepin-terminal/src/remotemanage/serverconfigoptdlg.cpp:495:5: note: Non-local variable 'm_curServer' will use pointer to local variable 'config'.
    m_curServer = &config;
    ^
```
第3处不属于源码层面的error
```
/home/echo/GitDownloads/deepin-terminal/tests/src/main/main.cpp:60:5: error: There is an unknown macro here somewhere. Configuration is required. If QTEST_SET_MAIN_SOURCE_PATH is a macro then please configure it. [unknownMacro]
    QTEST_SET_MAIN_SOURCE_PATH
    ^
```
