### ISSUE TITLE
original deepin circle logo

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/developer-center#29]
I am looking for a transparent source of this Deepin logo?
![deepin](https://cloud.githubusercontent.com/assets/11800714/12696753/b4e1ee72-c772-11e5-8b6b-7e0922805c05.jpg)
Can anyone point me to the right place, please?

**Comment by hualet** [comment]
I don't know, but I can ask our designers for one, what will you use it for BTW ?

**Comment by oberon2007** [comment]
that would be great! :) For the plymouth theme I use this square one at the moment but since I think it is not really the commonly known one I thought the round icon would be better:
https://github.com/oberon2007/plymouth-themes-manjaro/blob/master/manjaro-deepin/manjaro-deepin.png
Also I want to spray it on my car - maybe that was a joke ;)

**Comment by hualet** [comment]
OK, I'll talk to our designers tomorrow, so you need to wait a bit. :smile:

**Comment by hualet** [comment]
sorry, closed by accident :P

**Comment by oberon2007** [comment]
It's not urgent ...
![windows_car](https://cloud.githubusercontent.com/assets/11800714/12701643/c4749b3a-c80f-11e5-9306-0b300ff3ad41.jpg)
:stuck_out_tongue_closed_eyes: Thank you!

**Comment by oberon2007** [comment]
OH! Actually you don't have to bother since I just found out that an svg of the logo is included in deepin icon theme ;)

**Comment by hualet** [comment]
Oh, that's great, I don't even know that we have that included in the icon theme :joy:

**Comment by oberon2007** [comment]
:smiley: Here you go:

![new_plymouth](https://cloud.githubusercontent.com/assets/11800714/12706109/ce407ab2-c87d-11e5-93f2-e4538e087dc7.png)

**Comment by hualet** [comment]
Ah, it looks great, except that the 'deepin' is too small ;P

**Comment by oberon2007** [comment]
I knew you'd say that! ;)

**Comment by hualet** [comment]
Just kidding, the logo is big enough anyway. :smile:

**Comment by oberon2007** [comment]
I knew you would say that, too :joy:

**Comment by hualet** [comment]
:angry:
