### ISSUE TITLE
deepin-polkit-agent 無法完全翻譯

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#290]
![deepin 20170528004907](https://cloud.githubusercontent.com/assets/20014762/26523013/79aebf48-433f-11e7-97d9-1b6701b1c822.png)

**Comment by hualet** [comment]
内容的翻译要交给使用polkit的程序提供，所以你上面那个哪个程序进行授权的提示？

**Comment by JulianLai** [comment]
@hualet pamac

**Comment by hualet** [comment]
需要程序提供翻译
