### ISSUE TITLE
[Gentoo Linux] startdde-3.1.9 cannot launch

### ISSUE THREAD

**Issue by zhtengw** [linuxdeepin/developer-center#293]
After upgrading startdde to version 3.1.9 (also upgraded its dependence dbus-factory, dde-api, go-lib  to latest version), I cannot launch startdde. When I executed startdde in a xinit session, I got this log [startdde-log.txt](https://github.com/linuxdeepin/developer-center/files/1051057/startdde-log.txt).

Can any one do me a favor? Thank you very mush.

**Comment by oberon2007** [comment]
> (startdde:356): GLib-GIO-ERROR **: Settings schema 'com.deepin.dde.sound-effect' does not contain a key named 'player'
It's a new key introduced with **deepin-desktop-schemas v3.1.7** (https://github.com/linuxdeepin/deepin-desktop-schemas/commit/94b4661649d8f44627b0bbc4c12832e2ed840750)
Do you have the latest installed?

**Comment by zhtengw** [comment]
@oberon2007 Installed. And there is a key "player" in /usr/share/glib-2.0/schemas/com.deepin.dde.sound-effect.gschema.xml

```
96         <key name="player" enum="com.deepin.dde.sound-effect.Player">
97             <default>'libcanberra'</default>
98             <summary>the event player</summary>
99             <description>The value will influence when the sound effect event playing.</description>
100        </key>
```

**Comment by zhtengw** [comment]
My mistake! I forgot to update schemas cache in ebuild. This issue is solved.
