### ISSUE TITLE
some issues with new wmchooser

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/developer-center#294]
Thank you for introducing this, @kirigayakazushin! I think the wmchooser a good idea. 
As you can see in the screenshot, there are still a few issues with this new feature:

![](http://imgur.com/lymgyVE.png)

* The long Label starting with "System has detected..." is cut off (or hidden behind the buttons?). We can only see the first half of the text.
* In my opinion it would be better to blur the background like for example the launcher does it.
* The language still needs some improvement to become proper English 😉 
May I suggest:
"It has been detected that you are using a Virtual Machine, which will affect the graphical performance.\n
For a smooth experience, it is recommended to select 'Common Mode'."
And then, for the bottom label, why not simply:
"Effect Mode: Gorgeous experience\n
Common Mode: Fast experience"
(I wouldn't use "smooth" as an explanation for 'Effect Mode', since above you have just said that for a smooth experience you are suggesting 'Common Mode' instead... 😆

**Comment by kirigayakazushin** [comment]
@oberon2007  Thanks for your feedback.Translation problems have been collected. I will solve the problem.

**Comment by oberon2007** [comment]
Thank you @kirigayakazushin ! :)

**Comment by hualet** [comment]
should've been fixed.
