### ISSUE TITLE
Wallpaper chooser not displaying

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/developer-center#298]
System: Arch anywhere with Deepin DE

Right click on the desktop, chose "Change Background" does nothing.

**Comment by oberon2007** [comment]
Confirming same bug on Manjaro.

**Comment by DasJott** [comment]
Also the same für Antergos with deepin and deepin-extra installed.

**Comment by felixonmars** [comment]
We need a new dde-file-manager release to fix this.

**Comment by oberon2007** [comment]
I see... I've just tried building latest **develop2.0** but it fails with a quite unspecific message:
```
ln -s libdde-file-manager.so.1.4.0 libdde-file-manager.so
ln -s libdde-file-manager.so.1.4.0 libdde-file-manager.so.1
ln -s libdde-file-manager.so.1.4.0 libdde-file-manager.so.1.4
make[1]: Leaving directory '/home/bernhard/manjaro/community/deepin-manjaro/deepin-file-manager/src/dde-file-manager/dde-file-manager-lib'
==> ERROR: A failure occurred in build().
    Aborting...
```
Any ideas?

**Comment by felixonmars** [comment]
Parallel builds could continue running for a while after the real error. Please look upwards :)

**Comment by felixonmars** [comment]
Should be fixed in deepin-file-manager 1:4.1.5.20170607.

**Comment by DasJott** [comment]
Works great now! Thanks for fixing so fast! :)

**Comment by oberon2007** [comment]
Most likely it didn't build for because of the missing new depends. In any case your new package works fine and fixes the issue. Thank you again!
