### ISSUE TITLE
Bug report 「缺陷报告」深色主题下，终端快捷键设置的显示配色难以看清

### ISSUE THREAD

**Issue by shenmo7192** [linuxdeepin/developer-center#2989]
提交到这里是因为deepin terminal的issue关闭了
![图片](https://user-images.githubusercontent.com/47873776/161005665-3517ffde-5ae1-4e9a-a980-b62d6fa510ab.png)

Original post link : https://bbs.deepin.org/post/233807

**Comment by BLumia** [comment]
跟进了下，这个问题已经修复了但是还没发布修复的版本。等 `dtkwidget  >= 5.5.42` 发布后就能解决了，对应的文字不会再使用活动色。

@babyfengfjx 等相关版本在社区发布后就可以关掉这个 issue 了。

**Comment by kt286** [comment]
20.6 已经修复

**Comment by babyfengfjx** [comment]
在新版本中优化了此处的问题,issue我们先关闭咯：
![image](https://user-images.githubusercontent.com/24642999/174704985-c659f3cf-80a8-454a-8ad2-f476ef7fd6be.png)

**Comment by BLumia** [comment]
注：目前发现控制中心仍有问题，控制中心可能自行覆盖了 dtk 提供的原始样式。因为和此 issue 缘由不同，就不在此 issue 跟踪此问题了，这个我们暂时先内部提单跟踪，若确有必要可另开 issue 跟踪。
