### ISSUE TITLE
问题反馈：系统显示放大后，截图的贴图置顶显示异常

### ISSUE THREAD

**Issue by 157221810** [linuxdeepin/developer-center#2997]
问题：20.5版本，在系统设置里将显示设为放大1.25倍，使用截图的贴图置顶时，置顶的图显示模糊。

**Comment by 157221810** [comment]
![image](https://user-images.githubusercontent.com/97322396/161372043-14c2e114-458d-4b28-ae5a-54fb42720ee3.png)

**Comment by 157221810** [comment]
![image](https://user-images.githubusercontent.com/97322396/161372189-b5fbc69a-202c-4076-91d5-39c041d2232f.png)

**Comment by babyfengfjx** [comment]
- 感谢反馈，该问题我们已经提交研发做优化处理，待问题修复后，会及时答复~

**Comment by kt286** [comment]
https://github.com/linuxdeepin/deepin-screen-recorder/pull/126

**Comment by babyfengfjx** [comment]
目前该问题已经得到修复，可以确认一下截图录屏的版本信息，后续有其他问题也感谢随时反馈，此issue我们先做关闭处理哟：
![Uploading image.png…]()
