### ISSUE TITLE
deepin file manager 翻譯不完全

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#300]
![deepinscreenshot20170607211905](https://user-images.githubusercontent.com/20014762/26880423-f89201f0-4bc6-11e7-8014-58b2039477db.png)

**Comment by zccrs** [comment]
@hualet  这是因为没有升级dtk吧？

**Comment by felixonmars** [comment]
dtk 是 6 月 2 号的 tag 0.2.10

**Comment by JulianLai** [comment]
所以是要等更新釋出？

**Comment by felixonmars** [comment]
我这里测试更新后已经解决了。
