### ISSUE TITLE
[BUG] Control center's search bar does not work

### ISSUE THREAD

**Issue by N1coc4colA** [linuxdeepin/developer-center#3003]
### SUMMARY | 问题概要
I can see the search bar into the title bar of the control center. But whenever I type anything, name of a section (ex.: Sound) or of a subsection (ex.: Power -> "General") nothing happens. Nothing showing up.

### EXPECTED RESULT | 期望的结果
Show something like a completer or a specific page showing possible options available.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息
OS: Deepin 23 Nightly
dde-control-center: ver. 5.5.11.4-1

### ADDITIONAL INFORMATION | 额外补充
I seen this bug since a long time for now but it is still here.

**Comment by BLumia** [comment]
For stable purpose please use v20.x. The nightly version can be very experimental. I'll tag v23 related people and see if they could offer some help.

> I seen this bug since a long time for now but it is still here.

Do you mean v20.x also have this issue? I have tested it under both deepin v20.5 and Arch Linux (with `deepin-control-center 5.4.70-2`) under English and Simplified Chinese locale and both of them works fine.

**Comment by N1coc4colA** [comment]
This is issue is present in 20.x too. I tried switching languages and have been surprised. In Chinese, English, the search bar works properly. In contrast, in French and Spanish, it does not. That seems to be a bug kind of obscure but that's here :/

**Comment by BLumia** [comment]
Thanks for the additional info, We'll check if we could reproduce this and pass this issue to related development team :)

**Comment by SuperEffie** [comment]
Thanks for your feedback.The problem has been confirmed to exist in the v20.x if the system language is French and Spanish.It has been reported to the developer, and we will inform you after the fix.

**Comment by BLumia** [comment]
I found this issue is duplicated with https://github.com/linuxdeepin/developer-center/issues/2780, I'll close this issue and let's track the issue state there :)
