### ISSUE TITLE
Save DDE for Archlinux

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/developer-center#3004]
edited by maintainer:

- [x] dde-desktop / dde-file-manager segment fault: https://github.com/linuxdeepin/dde-file-manager/pull/426
- [x] kwin_no_scale cannot be started: https://github.com/linuxdeepin/developer-center/issues/2637

Only critical issues listed here, for other priority porting related issues please track them here: https://github.com/orgs/linuxdeepin/projects/12/views/1

**Comment by felixonmars** [comment]
Is this going to be a tracking issue for all Arch Linux DDE issues?

**Comment by justforlxz** [comment]
> Is this going to be a tracking issue for all Arch Linux DDE issues?

yes.

**Comment by BLumia** [comment]
For just issue tracking I guess we could use issue label, public project board or milestone for that purpose. We could use Discussion board for general discussion...

**Comment by felixonmars** [comment]
> For just issue tracking I guess we could use issue label, public project board or milestone for that purpose. We could use Discussion board for general discussion...

Yeah, my first thought too.

**Comment by zccrs** [comment]
> Is this going to be a tracking issue for all Arch Linux DDE issues?

This issue is temporary,  just for some problems, the problems broke the DDE for Archlinux. This issue will close after the DDE can runing on Archlinux.
 @justforlxz Add the broke problems to there.

**Comment by zccrs** [comment]
From Mahmoud Elswerky in Telegram "deepin Linux":

```
Yes before I have issue with lightdm , when PC sleep , I doesn't accept password 
But this issue fixed 


But the issue currently I face is : 
Dde-file-manager doesn't open error core dumped segmentation error 
And by this issue , desktop contents doesn't display like icons ,files, folders


Also right menu on desktop doesn't show (in short desktop is frozen 

And by this issue after I boot PC ,dock is frozen then it disappears and reappears 
And sometimes got an alert days dock open in safe mode(sometimes this alert)


-- also the old issue that exists for months you mentioned which is deepin-kwim 

Latest deepin-kwin causes window (maximize, minimize and close)  to disappear in most apps
(I was having temporary fix for this by downgrading 3 pkgs of deepin kwin ( kwin,kde_decoeation,kwayland) ( or not to install deepin-kwim at all on arch installation 

- can't set a shortcut to shift keyboard language , I have to change it every time from dock icon of language 0r from settings ( yes simple bug but with time is annoying and this bug exist for months

- Finally deepin-desktop on arch is too old currently compared to deepin-desktop on deepin Os
Many new features in current deepin-os not present in deepin-desktop on arch like for examples one feature is search icon on dock which on deepin-os for months not exist on deepin-desktop  and by this other features are missing I think on arch-deepin 

And other new apps which haven't got therir sources released like mail and others ( this doesn't mean I need mail specifically I just give example )
Thx.
```

**Comment by BLumia** [comment]
I've created a project board for Arch Linux porting issues: https://github.com/orgs/linuxdeepin/projects/12/views/1

I guess tracking issue there could be a better idea since there still can be new DDE on Arch Linux porting issue in future releases. Individual row of data could be displayed/assigned/tagged/etc. to make issue tracking easier.

**Comment by BLumia** [comment]
So, let's track the high-priority issues that make DDE on Arch not usable here, for other Arch DDE porting issues please add/link to that project board. I'll edit the description of this issue to help track the high-priority issues.

**Comment by BLumia** [comment]
The dde-file-manager project's development branch (master) already contains related fix, although there isn't a tag release yet. We are using a patch under Arch Linux to avoid the crash before the next release lands. So, I'll mark the 1st task as resolved.

Now all DDE components related projects should have already migrated their development workflow to GitHub, I guess we can work on the rest of DDE on Arch Linux issues, and let's tracking these issues at https://github.com/orgs/linuxdeepin/projects/12/views/1 then. Also, feel free to tag me when you need any assistance with a certain issue.
