### ISSUE TITLE
File manager context menu -> compress does nothing

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/developer-center#301]
Clicking on a file and choosing "Compress" does nothing.

Using Arch Anywhere.

**Comment by felixonmars** [comment]
Did you install file-roller? It is an opt-depend.

**Comment by hualet** [comment]
Actually it's not optional if you want the compress function to work @felixonmars

**Comment by DasJott** [comment]
Had to install file roller myself but then it worked!
Maybe should be taken as dependency when installing dde-desktop?

**Comment by felixonmars** [comment]
@hualet It's an opt-depend of the whole package. Opt-depends do not exist for a specific function.

**Comment by hualet** [comment]
I don't know the packaging rules of Arch, maybe you can make it recommended or similar role ? since dde-file-manager hard coded fill-roller to do compress. @felixonmars

**Comment by felixonmars** [comment]
There's no recommended or similar role, sadly. Usually we write these as optdepends and let the user to decide whether to install themselves. I can make it a hard dependency, though.

**Comment by DasJott** [comment]
You should leave out the menu entry then if it is not installed. That way it would not look buggy ;)

**Comment by felixonmars** [comment]
Arch users are expected to read the optdepends notices during installation. But if upstream really want to see it as a hard dependency, we can do it of course...

**Comment by felixonmars** [comment]
It's already a hard dependency now.

**Comment by DasJott** [comment]
Confirmed. Works now out-of-the-box
