### ISSUE TITLE
Cannot login via DDE after update to 20.5

### ISSUE THREAD

**Issue by carneles** [linuxdeepin/developer-center#3011]
### SUMMARY | 问题概要

Cannot login via DDE. No error message, cannot enter the system.

### STEPS TO REPRODUCE | 复现步骤

1. (After update to 20.5 from 20.4) start the system. Login screen appear.
2. Choose user, enter password.
3. Nothing happen. only login screen still appear.

### EXPECTED RESULT | 期望的结果

Can login to the system via DDE

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Deepin 20.5

### ADDITIONAL INFORMATION | 额外补充

This happen after upgrade from Deepin 20.4 to Deepin 20.5.
Tried to login via tty / ssh and can logged in successfully.

**Comment by SuperEffie** [comment]
Thanks for reporting this issue.Could you provide more information about the device ? Please screenshot after entering the command 'sudo apt install inxi -y && inxi -F' and the command 'sudo vim /etc/apt/souce.list' in the terminal. Could  enter into the system properly after rebooting?

**Comment by carneles** [comment]
Hi @SuperEffie thank you for your reply,
let me add more details about the issue. So, basically, after I successfully boot up the computer, it will show the login screen like this:

![cdesktop](https://user-images.githubusercontent.com/16079680/162351243-c1130ab5-f4b6-4f71-8190-b79751d7eb87.jpeg)

After I fill my password and press/click on the arrow button to login, it won't go to the desktop. It seems that the button don't do anything to log me in.

However, I can still log in via another TTY (CTRL+ALT+F2). 
I was thinking that the problem lies on the DDE itself. So I tried to install another desktop (gnome) via tty2. Reboot after installation completed but still the problem persist. I still can't login via login screen.

To go the desktop I do this:
- Go to tty2 (CTRL+ALT+F2)
![ctty2](https://user-images.githubusercontent.com/16079680/162351409-65b57c41-429e-4124-bba8-193472512b90.jpeg)
- login via console in tty2 (enter username and password)
- run desktop using `startx` (I think this command `startx` available after I installed gnome. before that, I tried this way but command startx was not found

So my question is, what can I do to be able to login via Login Screen again (TTY1)?

About the info you asked, here is the result of inxi - F:
`System:
  Host: CarsNUC Kernel: 5.10.101-amd64-desktop x86_64 bits: 64 
  Desktop: Deepin 20.5 Distro: Deepin 20.5 
Machine:
  Type: Desktop System: Intel product: NUC7i7BNH v: J31153-310 
  serial: <root required> 
  Mobo: Intel model: NUC7i7BNB v: J31145-309 serial: <root required> 
  UEFI: Intel v: BNKBL357.86A.0083.2020.0714.1344 date: 07/14/2020 
CPU:
  Topology: Dual Core model: Intel Core i7-7567U bits: 64 type: MT MCP 
  L2 cache: 4096 KiB 
  Speed: 3482 MHz min/max: 400/3500 MHz Core speeds (MHz): 1: 3482 
  2: 3491 3: 3440 4: 3499 
Graphics:
  Device-1: Intel Iris Plus Graphics 650 driver: i915 v: kernel 
  Display: tty server: X.Org 1.20.4 driver: modesetting 
  unloaded: fbdev,vesa resolution: 1366x768~60Hz 
  OpenGL: 
  renderer: Mesa Intel Iris Plus Graphics 650 (Kaby Lake GT3e) (KBL GT3) 
  v: 4.6 Mesa 20.3.4 
Audio:
  Device-1: Intel Sunrise Point-LP HD Audio driver: snd_hda_intel 
  Device-2: Huawei type: USB driver: snd-usb-audio,uvcvideo 
  Sound Server: ALSA v: k5.10.101-amd64-desktop 
Network:
  Device-1: Intel Ethernet I219-V driver: e1000e 
  IF: eno1 state: up speed: 100 Mbps duplex: full mac: 94:c6:91:1a:fa:b3 
  Device-2: Intel Wireless 8265 / 8275 driver: iwlwifi 
  IF: wlp58s0 state: down mac: 68:ec:c5:21:6f:e2 
  IF-ID-1: br-0995ef20a01a state: down mac: 02:42:f0:1b:d1:04 
  IF-ID-2: br-0b61b981ca6d state: down mac: 02:42:0f:11:ed:bc 
  IF-ID-3: br-389af078dd9c state: down mac: 02:42:ba:d0:48:6d 
  IF-ID-4: br-578a68f8e113 state: down mac: 02:42:d1:53:4e:b5 
  IF-ID-5: br-9bb89a711194 state: down mac: 02:42:fa:58:fa:7f 
  IF-ID-6: docker0 state: down mac: 02:42:09:d9:6a:cd 
Drives:
  Local Storage: total: 931.51 GiB used: 675.82 GiB (72.6%) 
  ID-1: /dev/sda vendor: Western Digital model: WDS100T1B0A-00H9H0 
  size: 931.51 GiB 
Partition:
  ID-1: / size: 168.05 GiB used: 45.95 GiB (27.3%) fs: ext4 
  dev: /dev/sda6 
  ID-2: /home size: 143.95 GiB used: 118.83 GiB (82.5%) fs: ext4 
  dev: /dev/sda7 
Sensors:
  System Temperatures: cpu: 48.5 C mobo: N/A 
  Fan Speeds (RPM): N/A 
Info:
  Processes: 303 Uptime: 9m Memory: 31.25 GiB used: 2.78 GiB (8.9%) 
  Shell: bash inxi: 3.0.32 
`

and this is the content of  /etc/apt/souce.list
`## Generated by deepin-installer
deb https://community-packages.deepin.com/deepin/ apricot main contrib non-free
#deb-src https://community-packages.deepin.com/deepin/ apricot main contrib non-free
`

**Comment by SuperEffie** [comment]
Thanks for providing more details about this issue.One user had the same problem and was unable to log in due to the face recognition howdy software installed before the upgrade. After re-installing, the issue was fixed. Have you installed similar software?

**Comment by carneles** [comment]
No, not yet. I just installed standard software that are used for work. Will deactivate face recognition solve the issue? if yes could you please guide me how to do it?

**Comment by carneles** [comment]
Hi @SuperEffie after getting info from you that this is related to the face recognition, I tried to deactivate login screen (in Accounts setting -> set auto login and login without password active). It doesn't solve the login screen issue though, but it helps me a lot so I do not need to login via tty2 anymore.
However, I still hope that this issue will be fixed by Deepin team. I really love the desktop you guys created.

**Comment by SuperEffie** [comment]
Thank you for your support. I would like to provide you with a tool to collect the relevant logs. After logging into the system, enter the command 'sudo chmod R 777 dde_get_log' and '. The packaged logs will be saved on the desktop.Please provid it to us. Our developers staff will locate and fix the issue based on the logs.
[dde_get_log.zip](https://github.com/linuxdeepin/developer-center/files/8450688/dde_get_log.zip)

**Comment by carneles** [comment]
Hi @SuperEffie sorry for late reply. Here is the log generated [https://drive.google.com/file/d/1-AzmIzPkq-q_YxbVbYJ6GTf7bcESfGrX/view?usp=sharing](url)

**Comment by SuperEffie** [comment]
We appreciate it that you provide these logs,and we have submitted these logs to developers.It may take some time to analyze and resolve this issue, if there is a solution, I will inform you here.

**Comment by Zeno-sole** [comment]
Can you backup /var/lib/deepin/authenticate/limit-states.json and delete the source file to try

**Comment by carneles** [comment]
Hi @Zeno-sole , sorry for a late reply. I will try to do that. I'll inform you later the result.

**Comment by carneles** [comment]
Hi @Zeno-sole I just tried your solution above. It doesn't work. I still can't login via login screen. So I deactivate the login screen again.

**Comment by carneles** [comment]
Hi @Zeno-sole , sorry for answering late. No, I never set up multiple keyboard layouts 
![image](https://user-images.githubusercontent.com/16079680/168949712-7a2865dd-3612-4908-9e04-c729e8b9c8b0.png)

**Comment by Zeno-sole** [comment]
Have you installed dde-qt5integration5.5? If installed, you can try to uninstall it

**Comment by Zeno-sole** [comment]
Due to no reply for a long time and lack of necessary information, closing this issue for now. If the problem still exists, please consider prvoide the necessary information to reopen the issue, or creating another issue
