### ISSUE TITLE
No sound on laptop

### ISSUE THREAD

**Issue by srdjanpavlovic** [linuxdeepin/developer-center#3012]
### SUMMARY | 问题概要

No sound, no sound output device, no sound input devices are recognized.

### STEPS TO REPRODUCE | 复现步骤

1. ...
2. ...
3. ...

### ADDITIONAL INFORMATION | 额外补充

[dmesg.txt](https://github.com/linuxdeepin/developer-center/files/8410836/dmesg.txt)
[lsmod.txt](https://github.com/linuxdeepin/developer-center/files/8410837/lsmod.txt)
[lspci.txt](https://github.com/linuxdeepin/developer-center/files/8410838/lspci.txt)
[uname.txt](https://github.com/linuxdeepin/developer-center/files/8410839/uname.txt)

**Comment by srdjanpavlovic** [comment]
I saw this bug on some other places, needs to be fixed soon, a lot of laptops are with those chips
and those users will be without audio when they install 20.5 or when they update to new kernel...

**Comment by titobundy** [comment]
I've the same problem after update to 20.5, laptop's sound not working, only works when I connect my bluetooth headphones.

Pavilion 15-eh0011la AMD Ryzen 7 (Realtek Audio)

![deepin-no-sound](https://user-images.githubusercontent.com/37158954/161787798-933669ef-632a-490b-ab75-cb5c83c463ce.png)

**Comment by srdjanpavlovic** [comment]
If there is any other output other then I already attached in first post, 
that I can post to help solve this issue, just ask and I will post.

**Comment by titobundy** [comment]
I use `sudo modprobe snd_rn_pci_acp3x `to enable mic again, but when i restart the laptop, the changes are lost, and I've to run commands again;

```
sudo modprobe -r snd_rn_pci_acp3x
systemctl --user restart pulseaudio
sudo modprobe snd_rn_pci_acp3x
```

**Comment by BLumia** [comment]
Related: https://bbs.deepin.org/zh/post/234086 (Chinese language)

**Comment by SuperEffie** [comment]
Thanks for you feedback.Did it work after using the method in the upper post?

**Comment by srdjanpavlovic** [comment]
When this will be pushed from testing to main branch?

**Comment by BLumia** [comment]
> When this will be pushed from testing to main branch?

Not sure right now, the latest time could be in the next release cycle (20.6) I guess.

**Comment by snjvm** [comment]
Tried running the script given by @titobundy and no change on system. Still no System devices.
HP ProBook g440
![image](https://user-images.githubusercontent.com/62160616/162245357-2cd17dbf-74d7-4528-8895-f8b79b5af97f.png)
![image](https://user-images.githubusercontent.com/62160616/162245923-8af7da44-8caf-402a-8d71-f36ddd0b5e85.png)

**Comment by titobundy** [comment]
@snjvm Can you show us the the updates details in your screen (red alert) ?, after add the unstable repository you should run apt updates, then install the update packages with apt upgrades or by control center.

**Comment by snjvm** [comment]
![image](https://user-images.githubusercontent.com/62160616/162253818-132417d6-abf5-4061-bb57-8ffb81500193.png)
![image](https://user-images.githubusercontent.com/62160616/162253865-154ff540-5686-4acd-8654-38496a97ad46.png)

**Comment by snjvm** [comment]
Yes i have installed all the updates. Now i don't see the Face Recognition on the Control Center. Still no devices under Sound.
![image](https://user-images.githubusercontent.com/62160616/162364565-f8371565-7815-4a4b-89e4-8600fa3be852.png)
![image](https://user-images.githubusercontent.com/62160616/162364576-588b3d88-648c-41c2-9911-ebc87c415387.png)
 After 20.5 upgrade multiple other issues have started.
1. Shutdown is not happening.
2. Auto start applications take around 4 ~ 5 minutes to start after booting.
3. Device Manager hangs after launch.

**Comment by BLumia** [comment]
> multiple other issues have started.

Please **create separated issues** for those bugs you mentioned, let's focus on the sound problem in this issue. Thanks!

**Comment by snjvm** [comment]
i could see this issue is not present in UbuntuDDE. LiveBoot UbuntuDDE and checked.
![image](https://user-images.githubusercontent.com/62160616/162366633-76868384-e742-488c-85e6-51cadeef1223.png)
![image](https://user-images.githubusercontent.com/62160616/162366690-316ede9d-de95-4538-8e93-258e805cf9d5.png)

**Comment by Zeno-sole** [comment]
Can you export your configuration information in the device manager, we are looking for similar devices to debug this problem

**Comment by snjvm** [comment]
Device Manager hangs after launch and stays like this forever.

![image](https://user-images.githubusercontent.com/62160616/163403058-b81ff0d0-263d-4c1d-9737-a1c1d13f3ff1.png)

**Comment by Zeno-sole** [comment]
lshw -C sound Confirm whether the value of driver= exists, if so, execute lsmod | grep "snd_hda_intel" to check whether the driver is loaded

**Comment by snjvm** [comment]
![image](https://user-images.githubusercontent.com/62160616/163657725-882ed8b0-7119-4839-907d-1803e9a5d4a6.png)
![image](https://user-images.githubusercontent.com/62160616/163657736-4ea7390a-21fe-47c8-b892-9f4fabc86ea2.png)

**Comment by srdjanpavlovic** [comment]
> Device Manager hangs after launch and stays like this forever.
> 
> ![image](https://user-images.githubusercontent.com/62160616/163403058-b81ff0d0-263d-4c1d-9737-a1c1d13f3ff1.png)

You can start it from terminal, and see if there is any useful output for debugging.

**Comment by snjvm** [comment]
Still the same old GUI. Device Manager hangs.
![image](https://user-images.githubusercontent.com/62160616/163657968-897844be-3bed-42c0-9256-85bcc9dbe227.png)

**Comment by srdjanpavlovic** [comment]
Maybe you could start gdb in B terminal after you start device-manager in A terminal, and then try attaching gdb to the process (devicemanager) using its PID...

**Comment by Zeno-sole** [comment]
@snjvm  Did you have no sound before updating to 20.5?

**Comment by snjvm** [comment]
Before upgrading to 20.5 i had Output Devices. No Input Devices. I thought problem with Input Devices would be resolved in 20.5

**Comment by Zeno-sole** [comment]
> Before upgrading to 20.5 i had Output Devices. No Input Devices. I thought problem with Input Devices would be resolved in 20.5

apt policy pulseaudio ,  Execute this under the terminal to see the version of pulseaudio

**Comment by snjvm** [comment]
![image](https://user-images.githubusercontent.com/62160616/163836206-8b6277a4-ccbd-473a-8537-89e5c7fa3e65.png)

**Comment by Zeno-sole** [comment]
https://cdimage.deepin.com/releases/23/   Can you try this version of the mirror to see if the sound is normal? @snjvm

**Comment by snjvm** [comment]
couldn't live boot that release. I'm using Ubuntu Live Boot temporarily. Will reinstall deepin again. Will update the status.

**Comment by Zeno-sole** [comment]
https://drive.google.com/file/d/1JjaH-iplOmQhNF4JYUOztEdKbTeJcwsX/view?usp=sharing  @snjvm  
I updated pulseaudio to version 15.99, but I'm not sure if this works because I don't have device verification, you can install it on version 20.5

**Comment by snjvm** [comment]
![image](https://user-images.githubusercontent.com/62160616/168376308-35b83447-6317-4bd8-96fb-ef5f4089a397.png)

**Comment by Zeno-sole** [comment]
You need to install libpulse0. Before installing these packages, pay attention to backup data. It is easy to cause dependency errors and cause system problems.

**Comment by srdjanpavlovic** [comment]
Still present, still not fixed, this is a major bug....

**Comment by BLumia** [comment]
> Still present, still not fixed

Your feedback is posted during v20.5 and we will push v20.6 today (not released yet, still during the last part of the release cycle), how do you expect a fix if we didn't push any fix...

**Comment by Zeno-sole** [comment]
> Still present, still not fixed, this is a major bug....

I repackaged pulseaudio, you can add my repository, update pulseaudio and try, execute the following command to add the repository `curl -L https://github.com/Zeno-sole/Zeno-sole.github.io/raw/main/repos/gpg-pbuilc.key | sudo apt-key add -`

**Comment by Zeno-sole** [comment]
If there is a problem with 20.6, you can try adding the repository I sent to update pulseaudio

**Comment by Zeno-sole** [comment]
Due to no reply for a long time and lack of necessary information, closing this issue for now. If the problem still exists, please consider prvoide the necessary information to reopen the issue, or creating another issue
