### ISSUE TITLE
KWIN very frequent crashes

### ISSUE THREAD

**Issue by raspin0** [linuxdeepin/developer-center#3015]
Lately KWIN crashes fairly frequently, it's especially annoying while playing games. I hope those logs will help pin pointing an issue. 

https://pastebin.com/TWS8WEeL
https://pastebin.com/tziVJLsz
https://pastebin.com/Neh1gbQR
https://pastebin.com/bWDhLfem

**Comment by BLumia** [comment]
Hi, since you skipped the issue template, could you at least provide what's the distro you're using?

**Comment by raspin0** [comment]
Sorry, I'm using Deepin 20.5. I can't really say how to reproduce it because it's so random. It's happening when I'm playing the game, as it's crashing when I'm alt+tabbing.

**Comment by raspin0** [comment]
```
marcin@marcin-PC:~$ inxi -F
System:    Host: marcin-PC Kernel: 5.10.101-amd64-desktop x86_64 bits: 64 Desktop: Deepin 20.5 Distro: Deepin 20.5 
Machine:   Type: Desktop System: ASUS product: All Series v: N/A serial: <root required> 
           Mobo: ASUSTeK model: Z97-PRO GAMER v: Rev X.0x serial: <root required> UEFI: American Megatrends v: 2203 
           date: 02/26/2016 
CPU:       Topology: Quad Core model: Intel Core i7-4790K bits: 64 type: MT MCP L2 cache: 8192 KiB 
           Speed: 1003 MHz min/max: 800/4500 MHz Core speeds (MHz): 1: 1006 2: 1028 3: 953 4: 1038 5: 948 6: 991 7: 993 
           8: 1052 
Graphics:  Device-1: NVIDIA GM204 [GeForce GTX 970] driver: nvidia v: 470.86 
           Display: x11 server: X.Org 1.20.4 driver: nvidia tty: N/A 
           OpenGL: renderer: NVIDIA GeForce GTX 970/PCIe/SSE2 v: 4.6.0 NVIDIA 470.86 
Audio:     Device-1: Intel 9 Series Family HD Audio driver: snd_hda_intel 
           Device-2: NVIDIA GM204 High Definition Audio driver: snd_hda_intel 
           Device-3: XMOS type: USB driver: hid-generic,snd-usb-audio,usbhid 
           Device-4: C-Media Multimedia Headset [Gigaware by Ignition L.P.] type: USB driver: hid-generic,snd-usb-audio,usbhid 
           Sound Server: ALSA v: k5.10.101-amd64-desktop 
Network:   Device-1: Intel Ethernet I218-V driver: e1000e 
           IF: eno1 state: up speed: 1000 Mbps duplex: full mac: 08:62:66:27:a7:7a 
Drives:    Local Storage: total: 701.76 GiB used: 502.07 GiB (71.5%) 
           ID-1: /dev/sda vendor: Intenso model: SSD Sata III size: 236.00 GiB 
           ID-2: /dev/sdb vendor: Seagate model: ST500LM012 HN-M500MBB size: 465.76 GiB 
Partition: ID-1: / size: 14.70 GiB used: 13.03 GiB (88.6%) fs: ext4 dev: /dev/sda4 
           ID-2: /boot size: 1.45 GiB used: 491.1 MiB (33.2%) fs: ext4 dev: /dev/sda2 
           ID-3: swap-1 size: 16.00 GiB used: 1024 KiB (0.0%) fs: swap dev: /dev/sda7 
Sensors:   System Temperatures: cpu: 29.8 C mobo: 27.8 C gpu: nvidia temp: 52 C 
           Fan Speeds (RPM): N/A gpu: nvidia fan: 0% 
Info:      Processes: 345 Uptime: 10h 22m Memory: 15.58 GiB used: 4.68 GiB (30.0%) Shell: bash inxi: 3.0.32 
```

**Comment by SuperEffie** [comment]
Thanks for your providing these logs.Could you describe your problem in more detail? For example, which game do you play and what kind of performance does kwin have when it crashes? If you can provide more detailed steps, we can more easily reproduce and locate this problem.
Thank you

**Comment by raspin0** [comment]
> Thanks for your providing these logs.Could you describe your problem in more detail? For example, which game do you play and what kind of performance does kwin have when it crashes? If you can provide more detailed steps, we can more easily reproduce and locate this problem. Thank you

KWIN just crashes, there is no performance regression before or afterwards, only a restart. While it's happening I can still use keyboard, the game is still on focus only mouse is disconnected when kwin restarts in the background. I'm playing Apex and League of Legends, but crashes are appearing even without playing anything. 

Example:
Video: https://gofile.io/d/aTEC1c

**Comment by SuperEffie** [comment]
It's so nice to provid us with video, our system is not yet better adapted to games, especially online games.
I wonder how do you install these games like Apex and League of Legends?

**Comment by justforlxz** [comment]
Hi, can you perform these operations in terminal?

```shell
sudo apt install kwin-x11-dbgsym dde-kwin-dbgsym systemd-coredump gdb
export QT_LOGGING_RULES="*.debug=true"
kwin_no_scale --replace > ~/kwin.crash.log 2>&1
```

Then open the game, try to crash kwin. and run this command to get the crash information

```
sudo coredump info /usr/bin/kwin_x11 > ~/.kwin.coredump.log
```

upload `~/kwin.crash.log` and `~/.kwin.coredump.log` files. thanks.

**Comment by raspin0** [comment]
> Hi, can you perform these operations in terminal?
> 
> ```shell
> sudo apt install kwin-x11-dbgsym dde-kwin-dbgsym systemd-coredump gdb
> export QT_LOGGING_RULES="*.debug=true"
> kwin_no_scale --replace > ~/kwin.crash.log 2>&1
> ```
> 
> Then open the game, try to crash kwin. and run this command to get the crash information
> 
> ```
> sudo coredump info /usr/bin/kwin_x11 > ~/.kwin.coredump.log
> ```
> 
> upload `~/kwin.crash.log` and `~/.kwin.coredump.log` files. thanks.


I don't have a command called `coredump`, did you mean `coredumpctl`? 
[Logs.zip](https://github.com/linuxdeepin/developer-center/files/8454147/Logs.zip)

**Comment by raspin0** [comment]
[Logs 2.zip](https://github.com/linuxdeepin/developer-center/files/8457899/Logs.2.zip)

**Comment by justforlxz** [comment]
> > Hi, can you perform these operations in terminal?
> > ```shell
> > sudo apt install kwin-x11-dbgsym dde-kwin-dbgsym systemd-coredump gdb
> > export QT_LOGGING_RULES="*.debug=true"
> > kwin_no_scale --replace > ~/kwin.crash.log 2>&1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then open the game, try to crash kwin. and run this command to get the crash information
> > ```
> > sudo coredump info /usr/bin/kwin_x11 > ~/.kwin.coredump.log
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > upload `~/kwin.crash.log` and `~/.kwin.coredump.log` files. thanks.
> 
> I don't have a command called `coredump`, did you mean `coredumpctl`? [Logs.zip](https://github.com/linuxdeepin/developer-center/files/8454147/Logs.zip)

Thanks a lot, I'll check.

**Comment by raspin0** [comment]
Hello, I'd bump the issue up and report all issues I'm having so far: 
1. Crashes in the background when playing games and sometimes most notably when using virtualbox
2. Blur crashes almost always after suspension and turning on/off window effects 
3. Composition artefacts after suspension in random places. Sometimes black boxes appear all over the place.

**Comment by raspin0** [comment]
The issue doesn't seem to reproduce anymore on deepin 20.8. I'm gonna close the issue
