### ISSUE TITLE
File Manager always copys from window to window

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/developer-center#302]
If I have two windows open and drag'n'drop a file from one to the other, file manager always wants to copy, even if it is on the same drive. 
It moves the file though when dragged and dropped within the same window.

Usind Arch Anywhere.

**Comment by DasJott** [comment]
maybe it should be posted in dde-file-manager?

**Comment by zccrs** [comment]
Hi,  Press the Shift key to move file in a different window when drag'n'drop

**Comment by DasJott** [comment]
Yeah, that works. But it isn't intuitive, is it?
It should by default move as long as it affects the same drive and by default copy when the destination is a different drive.

My opinion ;)

**Comment by zccrs** [comment]
Thank you feedback, We will consider your suggestion.
