### ISSUE TITLE
Can't boot from USB to install Deepin

### ISSUE THREAD

**Issue by Octavian-Q** [linuxdeepin/developer-center#3042]
Steps I do to install Deepin:
1. Write ISO to USB (went fine) 
2. Put USB in desktop PC and select from boot menu the stick 
3. Show classic deepin boot menu (Screenshot 1)
![IMG20220408125013](https://user-images.githubusercontent.com/98664445/162427468-d4d8877e-d661-4be9-8337-bd8ede810182.jpg)

4. I select first option to install deepin
5. Get a screen with some checking writing (Screenshot 2)
![IMG20220408125017](https://user-images.githubusercontent.com/98664445/162427507-e526e06d-2bf3-4f5a-ac9f-30dfa70d5c49.jpg)

6. Screen goes black and stays like that indefinite (Screenshot 3)
![IMG20220408123545](https://user-images.githubusercontent.com/98664445/162427591-83867c90-7547-45ba-a25a-5d43c94d56f1.jpg)

Note: Same effect no matter of Safe Graphics or normal boot option. USB and ISO seems to be fine, on other laptop works 

PC Specs:
CPU: Ryzen 9 5900X
Motherboard: ASrock B550 Taichi
GPU: RX 6800 XT
RAM: 64 GB Kingston hyper X 3600Mhz
Storage: ADATA SSD 128

**Comment by Zeno-sole** [comment]
You can try to use the 5.15 kernel to start, you can choose in the advanced options

**Comment by Octavian-Q** [comment]
> You can try to use the 5.15 kernel to start, you can choose in the advanced options

Thank you with kernel 5.15 worked. I installed Deepin now

**Comment by Zeno-sole** [comment]
Ok, thank you for your use, if you have other questions, you can submit new issues again
