### ISSUE TITLE
switch input  languges keys problem 

### ISSUE THREAD

**Issue by AaBbdev29** [linuxdeepin/developer-center#3053]
### SUMMARY | 问题概要

when I press "Alt + shift  or ctrl space "The language changes but But it has no effect on the Dock
![Screenshot_select-area_20220412192444](https://user-images.githubusercontent.com/89275907/162991753-dddf6bf9-fcb9-4b08-b1ce-7b6709aff775.png)

### STEPS TO REPRODUCE | 复现步骤

1. ...
2. ...
3. ...

### ADDITIONAL INFORMATION | 额外补充

![Screenshot_select-area_20220412192444](https://user-images.githubusercontent.com/89275907/162991930-2f6810eb-a575-4d32-b42e-59d72f77d3cf.png)

**Comment by tsic404** [comment]
which input method you are using ?

**Comment by tsic404** [comment]
you mean switching input but layout indicator do not follow?

**Comment by tsic404** [comment]
same as [this](https://bbs.deepin.org/en/post/234406?id=234406)?, we have do some changes testing it in the [tg group](https://t.me/+4XQCwgnIjCJmZDdl)
