### ISSUE TITLE
桌布設定找不到 greeter 的這張背景圖

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#306]
![p_20170609_172752](https://user-images.githubusercontent.com/20014762/26969812-a1ad0654-4d39-11e7-98a2-07c266517824.jpg)

**Comment by jouyouyun** [comment]
@felixonmars

**Comment by felixonmars** [comment]
这张图不在 deepin-wallpapers 里吧，之前说的合并什么时候改好应该就自动解决了 @hualet

**Comment by felixonmars** [comment]
@JulianLai 这个问题现在应该已经解决了，默认图已经更换并加入了 deepin-wallpapers 包。
