### ISSUE TITLE
「Feature」 support adjust the root partition size

### ISSUE THREAD

**Issue by yxsos** [linuxdeepin/developer-center#3062]
Hello everyone, we pay attention to the full-scale installation of the ISO image, the default root partition size setting does not meet the current needs of the current user's large-capacity hard disk, for this, we plan to change in V20.6 version -[Allow users to support custom root partition size when using full installation options]

大家好，我们关注到在使用ISO镜像进行全盘安装时，默认的根分区大小设置并不能很好的满足当前用户大容量硬盘的需求，为此，我们计划在V20.6版本中进行改变 -- 【允许用户在使用全盘安装选项时支持自定义根分区大小的功能】

**Comment by kt286** [comment]
the 20.6 has been released, this issue can be closed
