### ISSUE TITLE
deepin-browser: browser crash when connecting gamepad

### ISSUE THREAD

**Issue by TheKozax** [linuxdeepin/developer-center#3066]

**Comment by babyfengfjx** [comment]
Does it function properly with other browsers? For example, edge chrome.
What game are you playing and is the handle used a USB type external gamepad?
If you can provide some more detailed information will be more helpful to the analysis of the problem。

And ,in the latest version V20.5, is this problem still present?

**Comment by SuperEffie** [comment]
Due to no reply for a long time and lack of necessary information, we close the issue at first.Now our product has been updated to deepin v20.5. If the problem still exists, you can apply to reopen it.
