### ISSUE TITLE
After using the Roll back option the system always boots with Rootb

### ISSUE THREAD

**Issue by igatjens** [linuxdeepin/developer-center#3069]
After using the Roll back option in GRUB's boot menu, the system only boots with Rootb.

Running `sudo update-grub` does not fix the problem.

![Captura de pantalla_área-de-selección_20201130143833](https://user-images.githubusercontent.com/66392244/100663589-27841300-331c-11eb-9191-5b664e8ca2c4.png)
![Captura de pantalla_área-de-selección_20201130143857](https://user-images.githubusercontent.com/66392244/100663593-281ca980-331c-11eb-822f-f836d9234dde.png)

Attached report generated with deepin-feedback-cli

[deepin-feedback-cli-Deepin-20-all-20201130-143914.tar.gz](https://github.com/linuxdeepin/deepin-ab-recovery/files/5618686/deepin-feedback-cli-Deepin-20-all-20201130-143914.tar.gz)

The problem is that in the GRUB configuration only the uuid of the Rootb partition is set as root. I searched the uuid of Roota and does not appear.

In addition, the restoration with Roll back was from November 20, just before adding the Deepin Internal Testing repository, but after the restoration, the Deepin Internal Testing repository is still in sources.list both in Roota and Rootb.

**Comment by BLumia** [comment]
Does this issue still happen on deepin v20.5?

**Comment by Zeno-sole** [comment]
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue
