### ISSUE TITLE
请问在 Arch 的 deepin-file-manager 怎么使用共享功能？

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#307]
已有安装 samba, gvfs-smb，有输入 sudo systemctl start samba.service，防火墙也有打开 port

https://youtu.be/BjuFDRrrrqY

**Comment by kirigayakazushin** [comment]
You need to configure samba, see [samba](https://wiki.archlinux.org/index.php/Samba#Server_configuration).

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
