### ISSUE TITLE
晃动鼠标时CPU占用太高

### ISSUE THREAD

**Issue by WLYYL** [linuxdeepin/developer-center#3070]
鼠标G102，cpu是i5 5200u，使用htop查看，打开Firefox静止时cpu占用10%，随意鼠标晃动时cpu占用能达到70-80%，其中dde-session-daemon占用最高，而就在deepin上安装的xfce4、plasma桌面，鼠标晃动时占用cpu最高才20%

**Comment by Zeno-sole** [comment]
你的dde-daemon版本多少？

**Comment by Zeno-sole** [comment]
由于长时间未收到回复，缺少必要信息，关闭该 issue,如果问题仍然存在可以申请重新打开该 issue
