### ISSUE TITLE
怎么配置dde.conf中的DICT_PATH 属性？

### ISSUE THREAD

**Issue by DustMerlin** [linuxdeepin/developer-center#3071]
应该是先将WORD_CHECK属性设为1,WORD_CHECK = 1 ,
DICT_PATH = ?   此处要怎么配置，我尝试使用 DICT_PATH = /usr/share/cracklib/pw_dict.pwd,但是设置密码会提示密码不能是常见单词及组合，任何密码都不能通过，都只会报这一问题；如果将 DICT_PATH =  随便给个文件，甚至目录，也是一样的错误。但是如果WORD_CHECK = 1 ，DICT_PATH属性空着的话，控制中心会异常关闭，因为我是使用控制中心添加新用户的，所以不是control-center没有异常处理，就是pw-check没有异常处理

**Comment by Zeno-sole** [comment]
这个问题应该修复了,可以更到20.5版本看看是否还存在

**Comment by Zeno-sole** [comment]
由于长时间未收到回复，缺少必要信息，关闭该 issue,如果问题仍然存在可以申请重新打开该 issue
