### ISSUE TITLE
Track number not available nor shown as an option

### ISSUE THREAD

**Issue by ShadowWarfare** [linuxdeepin/developer-center#3072]
When in Album name mode I can get the albums in the correct order but the tracks are not in the correct order for example on the James Cameron's Avatar music album the bottom is displayed at the top and so are other albums. Please add the option to show the track numbers like the Apple's Music player iTunes which has a track number. If this addition is added then I won't need to use Rhythmbox on Deepin Linux. Deepin Music is a nice player but I want the ability to see the tracks number on the left side of the music player as shown in the iTunes software and Rhythmbox music player.

**Comment by babyfengfjx** [comment]
We are sorry that we did not communicate for a long time, we do not know whether the music player in the latest version of the system can meet your requirements, we will close the issue first If the latest version still can not meet your requirements, please continue to submit issues to us.

**Comment by meiyixiang** [comment]
I'm sorry for replying you so long. You can upgrade to our latest system. During this period, we have optimized the function of music for many times, and we have recorded the feedback problems
