### ISSUE TITLE
Can I add lyrics for less popular music? and how?

### ISSUE THREAD

**Issue by ghost** [linuxdeepin/developer-center#3073]
I have manny of not well known songs, specially songs from my country, wrong lyrics make them look bad on deepin music.

It's similliar to linuxdeepin/developer-center#1047, I'm able to add cover by my own using Picard, but how about music lyric?

Sorry for any grammatical error, English just not my native language :)

**Comment by BLumia** [comment]
Embedding lyrics with Kid3 or similar software should work, using external `.lrc` file for that is also okay.

If you have further questions, please feel free to open a discussion thread in [developer-center repo's discussion board](https://github.com/linuxdeepin/developer-center/discussions) :)
