### ISSUE TITLE
Lyrics are not showing 

### ISSUE THREAD

**Issue by sbuvaneshkumar** [linuxdeepin/developer-center#3077]
Lyrics are not showing for any of the songs, it is used to show when I was using it about a few months back.
Version: deepin-music 3.1
Distro: Fedora 30
No significant messages in the system logs as well.

**Comment by BLumia** [comment]
Sorry for the late reply since we were not checking issues that were created outside the developer-center repo.

If that still happens in the most recent version you can get, please open a new issue in developer-center repo and we'll look into it. Thanks!
