### ISSUE TITLE
20 beta 最新版本, 播放莫名其妙会暂停

### ISSUE THREAD

**Issue by ChrisLiu17** [linuxdeepin/developer-center#3079]
无论是网易云音乐还是浏览器里的音乐或电影，都是这样

**Comment by BLumia** [comment]
很久没有进一步答复，就先关闭 issue 了。如果您更新到我们 deepin 最新版本后仍有类似问题可以再开个新的 issue 来反馈，我们会持续跟进问题。感谢！
