### ISSUE TITLE
添加本地目录卡死

### ISSUE THREAD

**Issue by aoeiuv-liu** [linuxdeepin/developer-center#3080]
添加本地目录卡死的问题2年前就存在，到现在还没修复啊？在论坛提，每次只是已收录，但是没人修啊？

**Comment by BLumia** [comment]
抱歉我们之前很少检查 developer-center 外所汇报的 issue 所以现在才答复您。现在也 2022 年了，您可以尝试下我们最新版本的 deepin-music 是否仍有您遇到的问题，如果仍然有的话，请您在 developer-center 填写 issue 模板开一个新的 issue，我们这边会协助您定位和处理问题。感谢支持！
