### ISSUE TITLE
希望给个appimage格式的包

### ISSUE THREAD

**Issue by ghost** [linuxdeepin/developer-center#3089]
1. ubuntu软件源里deepin-music还是5.0.1版本的，希望更新一下，或者给个appimage格式的包。
2. 然后加载歌词的时候会乱码，歌词文件是utf-8格式的。
![20211018194300](https://user-images.githubusercontent.com/43374299/137723954-ad091503-8002-4491-906d-11504b56e73b.png)

3. 之前用3.0.1有网络歌词搜索功能的，后面的版本就搜索不了了，希望可以把这个功能加上。

**Comment by BLumia** [comment]
原 reporter 销号了，暂时先关闭，这个问题请移步 https://github.com/linuxdeepin/open-source-students/issues/10 跟踪
