### ISSUE TITLE
歌曲数量超过2000时界面会一直闪烁

### ISSUE THREAD

**Issue by WLYYL** [linuxdeepin/developer-center#3090]

**Comment by BLumia** [comment]
@SuperEffie 需要在当前已发布的最新版本中验证一下是否仍有此问题

**Comment by SuperEffie** [comment]
感谢您的反馈，很抱歉我们没能复现到您issue中的问题，我在应用音乐中导入了2000+首歌曲，未出现界面闪烁的情况。请问您在deepin v20.5版本上问题也一直存在吗？是必现问题吗?有没有必现的操作步骤呢？如果方便麻烦为我们提供一个异常界面的录屏。

**Comment by SuperEffie** [comment]
由于您长时间没有回复，并且我们在deepin最新版本上未复现到您issue中提出的问题，暂时将这个issue关闭。若您issue中的问题在新版本系统上依然存在，可以申请重新打开它。若您还有其它问题或建议，欢迎您随时反馈~
