### ISSUE TITLE
bug描述：深度终端无法记住远程管理密码

### ISSUE THREAD

**Issue by shenmo7192** [linuxdeepin/developer-center#3094]
### SUMMARY | 问题概要
深度终端无法记住远程管理密码，关闭后会忘记

### STEPS TO REPRODUCE | 复现步骤

1. 打开深度终端
2. 设置远程服务器密码
3. 关闭

### OBSERVED RESULT | 观察到的结果

 再打开，他忘了

### EXPECTED RESULT | 期望的结果

记住密码

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```
              ............                shenmo@shenmo-PC
          .';;;;;.       .,;,.            OS: Deepin 20.5 apricot
       .,;;;;;;;.       ';;;;;;;.         Kernel: x86_64 Linux 5.15.24-amd64-desktop
     .;::::::::'     .,::;;,''''',.       Uptime: 9m
    ,'.::::::::    .;;'.          ';      Packages: 2376
   ;'  'cccccc,   ,' :: '..        .:     Shell: bash
  ,,    :ccccc.  ;: .c, '' :.       ,;    Resolution: 1920x1080
 .l.     cllll' ., .lc  :; .l'       l.   DE: Deepin 20.5
 .c       :lllc  ;cl:  .l' .ll.      :'   WM: KWin
 .l        'looc. .   ,o:  'oo'      c,   GTK Theme: deepin [GTK2/3]
 .o.         .:ool::coc'  .ooo'      o.   Icon Theme: blossom-light
  ::            .....   .;dddo      ;c    CPU: AMD Ryzen 7 5800H with Radeon Graphics @ 16x 3.2GHz
   l:...            .';lddddo.     ,o     GPU: NVIDIA GeForce RTX 3060 Laptop GPU
    lxxxxxdoolllodxxxxxxxxxc      :l      RAM: 3457MiB / 15469MiB
     ,dxxxxxxxxxxxxxxxxxxl.     'o,      
       ,dkkkkkkkkkkkkko;.    .;o;        
         .;okkkkkdl;.    .,cl:.          
             .,:cccccccc:,.  
```

### ADDITIONAL INFORMATION | 额外补充

录屏：https://www.bilibili.com/video/BV1v34y1v7YX/

**Comment by BLumia** [comment]
在 Deepin v20.5 上简单试了下未能复现。提供下 deepin-terminal 的版本号，以及可以试试装个 seahorse ，然后重新进行一次复现步骤，再在 seahorse 里看看在里面看不看得到对应的信息？

**Comment by shenmo7192** [comment]
> 在 Deepin v20.5 上简单试了下未能复现。提供下 deepin-terminal 的版本号，以及可以试试装个 seahorse ，然后重新进行一次复现步骤，再在 seahorse 里看看在里面看不看得到对应的信息？

```
shenmo@shenmo-PC:~$ apt policy deepin-terminal
deepin-terminal:
  已安装：5.4.28-1
  候选： 5.4.28-1
  版本列表：
 *** 5.4.28-1 500
        500 https://community-packages.deepin.com/deepin apricot/main amd64 Packages
        100 /usr/lib/dpkg-db/status
```

**Comment by shenmo7192** [comment]
> 在 Deepin v20.5 上简单试了下未能复现。提供下 deepin-terminal 的版本号，以及可以试试装个 seahorse ，然后重新进行一次复现步骤，再在 seahorse 里看看在里面看不看得到对应的信息？

无法再次复现了？奇怪

**Comment by shenmo7192** [comment]
> 在 Deepin v20.5 上简单试了下未能复现。提供下 deepin-terminal 的版本号，以及可以试试装个 seahorse ，然后重新进行一次复现步骤，再在 seahorse 里看看在里面看不看得到对应的信息？

可能原因是在解锁的时候钥匙环没被解锁，弹窗提示来着

emmm，面容解锁不能解锁钥匙环的话，面容解锁的意义在哪呢？

**Comment by BLumia** [comment]
> > 在 Deepin v20.5 上简单试了下未能复现。提供下 deepin-terminal 的版本号，以及可以试试装个 seahorse ，然后重新进行一次复现步骤，再在 seahorse 里看看在里面看不看得到对应的信息？
> 
> 可能原因是在解锁的时候钥匙环没被解锁，弹窗提示来着

我没有摄像头可测那个面容解锁，你有可以稳定复现的步骤了吗？

> emmm，面容解锁不能解锁钥匙环的话，面容解锁的意义在哪呢？

（如果确实如此的话）这肯定不是预期行为，显然是 bug。。。

**Comment by shenmo7192** [comment]
> 

在手动清理钥匙环之后再次打开之后无法再次复现
论坛出现过这样的情形，也是手动清除后无法再次复现
甚至在面容解锁出现之前就有了
https://bbs.deepin.org/post/225502
https://bbs.deepin.org/post/233877

---
这显然不是一个深度终端的问题，如果需要，可把这个issue关闭另开了

**Comment by BLumia** [comment]
我这边试了下，手动锁上钥匙环的情况下，在打开深度终端时，以及在点击保存时也都会提示输入密码来解锁钥匙环（这种情况下提示输入密码以解锁钥匙环也是正常的）。假设面容解锁在登录后是没解锁钥匙环的话，也应该会在开深度终端时提示解锁钥匙环才对。

@babyfengfjx 试下开机用面容解锁的情况下能不能复现？

**Comment by babyfengfjx** [comment]
- 楼主应该服务器使用的是centos吧？
- 目前该问题已经提交对应研发进行分析，当前centos系统的服务器是会出现无法记住密码的情况。

**Comment by BLumia** [comment]
> * 楼主应该服务器使用的是centos吧？
> * 目前该问题已经提交对应研发进行分析，当前centos系统的服务器是会出现无法记住密码的情况。

是 deepin 呀，不是也有 screenfetch 吗（`OS: Deepin 20.5 apricot`） 😂

**Comment by shenmo7192** [comment]
> * 楼主应该服务器使用的是centos吧？
> 
>     * 目前该问题已经提交对应研发进行分析，当前centos系统的服务器是会出现无法记住密码的情况。

:laughing:

**Comment by shenmo7192** [comment]
> 我这边试了下，手动锁上钥匙环的情况下，在打开深度终端时，以及在点击保存时也都会提示输入密码来解锁钥匙环（这种情况下提示输入密码以解锁钥匙环也是正常的）。假设面容解锁在登录后是没解锁钥匙环的话，也应该会在开深度终端时提示解锁钥匙环才对。
> 
> @babyfengfjx 试下开机用面容解锁的情况下能不能复现？

现在又稳定复现了，无论是否面容解锁，都会弹
这可能不是一个面容解锁bug

**Comment by BLumia** [comment]
> 现在又稳定复现了，无论是否面容解锁，都会弹

是稳定复现弹出钥匙环输密码的对话框？还是稳定复现终端保存远程管理密码的整个过程中，不会弹出钥匙环对话框并且也无法保存密码？

**Comment by babyfengfjx** [comment]
- 建议两个问题分开提交issue，有时候搞懵了，哈哈~
- 无法保存远程服务器密码的问题，暂时只在服务器是centos的情况下复现过，deepin的服务器还未复现。
- 如果弹出秘钥环的弹框，可能是因为打开过自动登录，而未勾选清除秘钥环导致，可以：sudo rm -rf ~/.local/share/keyrings/*
- 人脸无法解锁秘钥环这个感觉应该是正常的，因为秘钥环是针对其他应用的一个密码认证，比如浏览器自动保存密码的这种，这是默认的会与用户密码一致，实际也可以单独设置，人脸只是一种附属验证方式，这个优先级可能在设计上是低于密码验证的，如果说希望通过人脸来解锁秘钥环密码，可能需要做一些需求上的调研，看是否做上这种需求。

**Comment by shenmo7192** [comment]
> > 现在又稳定复现了，无论是否面容解锁，都会弹
> 
> 是稳定复现弹出钥匙环输密码的对话框？还是稳定复现终端保存远程管理密码的整个过程中，不会弹出钥匙环对话框并且也无法保存密码？

稳定弹出对话框，在登陆进桌面的时候就会谈
如果不输入密码而取消，则深度终端的行为同录屏，无法读取密码且不提示解开钥匙环
如果输入密码，则深度终端能读取密码

**Comment by BLumia** [comment]
> 稳定弹出对话框，在登陆进桌面的时候就会谈

这个建议另开 issue，毕竟不同的问题。

> 如果不输入密码而取消，则深度终端的行为同录屏，无法读取密码且不提示解开钥匙环

如果直接关掉的话，在启动终端以及远程管理输入完密码后点保存的时候都应当会再次弹出解锁钥匙环的密码输入对话框才对，你这边是并不会出现对吗？

**Comment by shenmo7192** [comment]
> > 稳定弹出对话框，在登陆进桌面的时候就会谈
> 
> 这个建议另开 issue，毕竟不同的问题。
> 
> > 如果不输入密码而取消，则深度终端的行为同录屏，无法读取密码且不提示解开钥匙环
> 
> 如果直接关掉的话，在启动终端以及远程管理输入完密码后点保存的时候都应当会再次弹出解锁钥匙环的密码输入对话框才对，你这边是并不会出现对吗？

不会出现
https://www.bilibili.com/video/BV13Z4y117GJ/

**Comment by shenmo7192** [comment]
> > 稳定弹出对话框，在登陆进桌面的时候就会谈
> 
> 这个建议另开 issue，毕竟不同的问题。
> 
> > 如果不输入密码而取消，则深度终端的行为同录屏，无法读取密码且不提示解开钥匙环
> 
> 如果直接关掉的话，在启动终端以及远程管理输入完密码后点保存的时候都应当会再次弹出解锁钥匙环的密码输入对话框才对，你这边是并不会出现对吗？

deepin-terminal:
  已安装：5.4.28-1
  候选： 5.4.28-1
  版本列表：
 *** 5.4.28-1 500
        500 https://community-packages.deepin.com/deepin apricot/main amd64 Packages
        100 /usr/lib/dpkg-db/status

**Comment by shenmo7192** [comment]
> 我这边试了下，手动锁上钥匙环的情况下，在打开深度终端时，以及在点击保存时也都会提示输入密码来解锁钥匙环（这种情况下提示输入密码以解锁钥匙环也是正常的）。假设面容解锁在登录后是没解锁钥匙环的话，也应该会在开深度终端时提示解锁钥匙环才对。
> 
> @babyfengfjx 试下开机用面容解锁的情况下能不能复现？

只要不使用密码解锁就会，比如自动登录或者无密码登录
