### ISSUE TITLE
在壁纸自动轮换时，某些壁纸会覆盖其他壁纸，导致所有壁纸都一样了

### ISSUE THREAD

**Issue by shenmo7192** [linuxdeepin/developer-center#3095]
### SUMMARY | 问题概要
在壁纸自动轮换时，某些壁纸会覆盖其他壁纸，导致所有壁纸都一样了

### STEPS TO REPRODUCE | 复现步骤

1. 设置特定壁纸为自定义壁纸
2. 自动更换

### OBSERVED RESULT | 观察到的结果

当轮换到该壁纸后，当要轮换到下一张壁纸的时候，下一张壁纸被这张壁纸覆盖了

只对用户自定义的壁纸有此行为，不会影响系统内置壁纸

### EXPECTED RESULT | 期望的结果

正常轮换，不出现覆盖

### SOFTWARE/OS VERSIONS | 软件/系统版本信息
```
              ............                shenmo@shenmo-PC
          .';;;;;.       .,;,.            OS: Deepin 20.5 apricot
       .,;;;;;;;.       ';;;;;;;.         Kernel: x86_64 Linux 5.15.24-amd64-desktop
     .;::::::::'     .,::;;,''''',.       Uptime: 22m
    ,'.::::::::    .;;'.          ';      Packages: 2376
   ;'  'cccccc,   ,' :: '..        .:     Shell: bash
  ,,    :ccccc.  ;: .c, '' :.       ,;    Resolution: 1920x1080
 .l.     cllll' ., .lc  :; .l'       l.   DE: Deepin 20.5
 .c       :lllc  ;cl:  .l' .ll.      :'   WM: KWin
 .l        'looc. .   ,o:  'oo'      c,   GTK Theme: deepin [GTK2/3]
 .o.         .:ool::coc'  .ooo'      o.   Icon Theme: blossom-light
  ::            .....   .;dddo      ;c    CPU: AMD Ryzen 7 5800H with Radeon Graphics @ 16x 3.2GHz
   l:...            .';lddddo.     ,o     GPU: NVIDIA GeForce RTX 3060 Laptop GPU
    lxxxxxdoolllodxxxxxxxxxc      :l      RAM: 2815MiB / 15469MiB
     ,dxxxxxxxxxxxxxxxxxxl.     'o,      
       ,dkkkkkkkkkkkkko;.    .;o;        
         .;okkkkkdl;.    .,cl:.          
             .,:cccccccc:,. 
```

### ADDITIONAL INFORMATION | 额外补充

不清楚是否与 https://github.com/linuxdeepin/developer-center/issues/3094 有关

神奇的壁纸文件：https://shenmo.lanzoul.com/iss1Q039p0sb

录屏：
https://www.bilibili.com/video/BV1iA4y197yH/

https://www.bilibili.com/video/BV1ai4y1U7SD/

**Comment by BLumia** [comment]
@SuperEffie 需要验证一下

**Comment by SuperEffie** [comment]
感谢您的反馈，我尝试在我的设备上复现您issue中的问题，但是无法复现。您issue中的问题是必现吗？重启后能恢复吗？有没有什么必现的操作步骤呢？可能是您设备上的单机问题。

**Comment by shenmo7192** [comment]
> 感谢您的反馈，我尝试在我的设备上复现您issue中的问题，但是无法复现。您issue中的问题是必现吗？重启后能恢复吗？有没有什么必现的操作步骤呢？可能是您设备上的单机问题。

必现
重启后不能恢复
有没有可能是总壁纸数量低于6的原因呢？

**Comment by babyfengfjx** [comment]
> 

可以恢复壁纸试试，不过理论上来说不应该有这种效果存在，哪怕是数量小于默认数量的话。

**Comment by shenmo7192** [comment]
> > 
> 
> 可以恢复壁纸试试，不过理论上来说不应该有这种效果存在，哪怕是数量小于默认数量的话。

这确实是令人感到不解的

恢复壁纸的话，就和最开始的需求相违背了。并不是很想在官方的壁纸中轮换

**Comment by SuperEffie** [comment]
即使我将壁纸数量降低至小于6张，自动跟换壁纸时间设置为30s，也无法复现到您描述的问题。后面我们会继续关注这个问题，您有没有做其他的设置呢？您有没有兴趣加入我们的内测群呢？

**Comment by shenmo7192** [comment]
> 即使我将壁纸数量降低至小于6张，自动跟换壁纸时间设置为30s，也无法复现到您描述的问题。后面我们会继续关注这个问题，您有没有做其他的设置呢？您有没有兴趣加入我们的内测群呢？

大概是没有其他设置

内测群号给一下

我现在改用动态壁纸了，吐槽下，这个壁纸轮换真的鸡肋，没法在不获取root权限的情况下关闭内置壁纸进入轮换。。。我都自定义了咋还要塞内置壁纸进来。。。

不支持指定文件夹播放啊。。。

**Comment by SuperEffie** [comment]
您可以关注我们社区论坛中的第一个帖子，扫码加入即可。对于issue中提出的问题，我们会把您的建议反馈给开发者们。

**Comment by shenmo7192** [comment]
> 您可以关注我们社区论坛中的第一个帖子，扫码加入即可。对于issue中提出的问题，我们会把您的建议反馈给开发者们。论坛链接是https://bbs.deepin.org/post/235397

论坛又来了一例同样症状的

https://bbs.deepin.org/phone/zh/post/235574

**Comment by SuperEffie** [comment]
我们把壁纸全部删除后有复现到了您issue中所描述的情况，但是原则上系统自带的壁纸最好是不要删除哦。我们评估后决定暂时不对issue中描述的情况做调整了，很感谢您的建议。现在我要先关闭这个issue了，若您有其他问题欢迎随时反馈~
