### ISSUE TITLE
deepin-wine-stable 6 的run_v4.sh脚本的workaround问题：无法处理路径中带空格的文件

### ISSUE THREAD

**Issue by shenmo7192** [linuxdeepin/developer-center#3097]
### SUMMARY | 问题概要

对于部分有workaround的应用（我浅显理解是workaround吧，对于对应容器打的补丁）（比如本例中的迅读PDF大师 com.fastreadpdf.deepin）（  https://bbs.deepin.org/zh/post/235119  ）
无法处理带空格的文件（比如作为option传入的文件所在目录/文件名中有空格，则出现问题）

### STEPS TO REPRODUCE | 复现步骤

1. 把文件名中带空格的文件拖放到.desktop上

### OBSERVED RESULT | 观察到的结果
把文件名拆开了

### EXPECTED RESULT | 期望的结果

正确打开

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```
deepin-wine-helper:i386:
  已安装：5.1.30-1
  候选： 5.1.30-1
  版本列表：
 *** 5.1.30-1 500
        500 https://com-store-packages.uniontech.com/appstore deepin/appstore i386 Packages
        400 https://d.store.deepinos.org.cn  Packages
        100 /usr/lib/dpkg-db/status
     5.1.29-1 400
        400 https://d.store.deepinos.org.cn  Packages
     5.1.13-1 400
        400 https://d.store.deepinos.org.cn  Packages

```
 $HOME/.deepinwine/deepin-wine-helper/run_v4.sh

### ADDITIONAL INFORMATION | 额外补充
录屏：https://www.bilibili.com/video/BV1Bi4y1U77c/

---

**Comment by babyfengfjx** [comment]
@SuperEffie 这个问题给wine组的人提单帮忙看一下。

**Comment by shenmo7192** [comment]
> @SuperEffie 这个问题给wine组的人提单帮忙看一下。

只加引号在没有参数的时候会传一个空的，又做了个workaround
```

CallFastReadPDF()
{
    #set -- "$1" "${2#file://*}"
    local path=$(urldecode "$2")
    path=${path/file:\/\//}
    set -- "$1" "$path"
	if [ "$path" ];then 
    CallProcess "$@"
	else
	CallProcess "$1"
	fi
}

```

---

顺便告诉一下应用商店组，迅读PDF的Mimetype没写
`MimeType=application/pdf`

**Comment by SuperEffie** [comment]
感谢您的反馈，怎么感觉是deepin自己人呢？我们已经提单给相应的研发的人员，后期研发人员如果有反馈，会在这通知您。

**Comment by shenmo7192** [comment]
> 感谢您的反馈，怎么感觉是deepin自己人呢？我们已经提单给相应的研发的人员，后期研发人员如果有反馈，会在这通知您。

我是社区的版主(
解决对应问题的时候顺着.desktop的exec一路翻脚本发现的

**Comment by shenmo7192** [comment]
> 感谢您的反馈，怎么感觉是deepin自己人呢？我们已经提单给相应的研发的人员，后期研发人员如果有反馈，会在这通知您。

我想问问，deepin-wine6的run_v4脚本中，WINEPREFIX="$HOME/.deepinwine/@public_bottle_name@"

@public_bottle_name@是从哪里获取呢？没有查到bash的这个用法

这个值后续又被覆盖了，很迷惑

**Comment by shenmo7192** [comment]
我对这里进行了一些分析，希望官方可以给出一些指导

https://shenmo7192.gitee.io/categories/spark-dwine-helper%E6%96%87%E6%A1%A3/

**Comment by shenmo7192** [comment]
https://gitee.com/deepin-community-store/spark-wine/releases

一些改进

**Comment by shenmo7192** [comment]
https://gitee.com/deepin-community-store/spark-wine/blob/master/spark-dwine-helper/pkg/opt/deepinwine/tools/spark_run_v4.sh#L480

**Comment by SuperEffie** [comment]
这个问题在deepin v20.8中已经进行修复了哦，您可以验证看看。我们提交的问题单已经闭环，我先将这个issue关闭，若是您验证问题依然存在，可以重新打开它，应@我们哦
感谢您的反馈~
