### ISSUE TITLE
项目的应用名称书写规范问题 

### ISSUE THREAD

**Issue by tsuibin** [linuxdeepin/developer-center#31]
讨论后的任务整理
- [ ] 更新README/HACKING下的文档名称, @fasheng
- [ ] 更新Qt应用中的qApp名称(如有遗失可继续补充), @hualet
   - [ ] dde-control-center
   - [ ] dde-launcher
   - [ ] dde-dock
   - [ ] dde-session-ui
   - [ ] deepin-feedback
- [X] 文档输出, 关联到 https://github.com/linuxdeepin/developer-center/issues/38

-----------------------
比如dcc和launcher 是两种不同风格的命名方式，这块还是建立一个标准吧？

  ```
app.setOrganizationName("deepin");

app.setApplicationName("DDE Control Center");

app.setApplicationVersion("3.0");
```

```
qApp->setOrganizationName("deepin");

qApp->setApplicationName("dde-launcher");

qApp->setApplicationVersion("2015-1.0");
```

**Comment by sbwtw** [comment]
dde 是 deepin desktop environment 的缩写，所以应该大写的

**Comment by snyh** [comment]
这个之前我也这样说．然后有人告诉我．　为啥　gnome　可以小写　....

**Comment by sbwtw** [comment]
gnome 异类，百姓怨声载道

**Comment by snyh** [comment]
这个name还涉及到desktop文件里面的Name
比如控制中心里这个名字其实是， Control Center

**Comment by snyh** [comment]
我推进
命令行统一采用dde-launcher 或者　deepin-movie 这种形式
涉及到需要显示的名称，则采用DDE Launcher,   Deepin Movie 这种形式

使用DDE或者deepin的区别在于　一个是DE组件一个是独立应用(期望其可以脱离DDE运行)

**Comment by fasheng** [comment]
还有 README 里面的 Name，都要统一。不过 desktop 可以特殊点，毕竟是给普通用户看的。

**Comment by fasheng** [comment]
同意 DDE Launcher，Deepin Movie，DDE Control Center 这种形式 :)

**Comment by iceleaf916** [comment]
对用户显示的确实要考虑大小写的问题，程序内部的话，建议不要故意大写和有空格，比如DDE Control Center，可以改为全小写，空格使用减号代替。因此，我的结论是：
1、DDE Launcher，Deepin Movie，DDE Control Center ，用户用户界面文档当说明等
2、dde-launcher，deepin-movie，dde-control-center用于程序内部识别。
3、DMovie比较特殊，当界面显示上使用全称Deepin Movie排版比较难看，或者放不下的时候，就会使用DMovie缩写。

**Comment by Iceyer** [comment]
簡單來說DDE Control Center 這種格式只會出現在tr("DDE Control Center ")或者gettext("DDE Control Center ")中 :question:

**Comment by fasheng** [comment]
涉及到项目名称的地方应该包括下列地方，同时附上我的理解：

1.  用户界面出现的名称，主要指 desktop/gettext/用户帮助文档，应该已经有规范（如 "Control Center"）
2.  git 项目名称，有规范但暂无文档（如 dde-control-center）
3. 生成的命令名称，有规范但暂无文档（如 dde-control-center）
4. 源码中有标志意义的项目名称（建议为 DDE Control Center）
5. README/HACKING 文档中出现的项目名称（建议和 4 相同，也为 DDE Control Center）

**Comment by hualet** [comment]
我的理解跟上面一致，不过我始终觉得都带上DDE很丑，其实去掉我觉得也可以。 Control Center、Launcher、Dock、Desktop 和 Deepin Movie这样子，没啥问题吧？

**Comment by manateelazycat** [comment]
随着我们造的轮子越来越多， deepin 的品牌有了家族体系， 我们可以在代码和标题栏弱化 Deepin，只用在项目和关于我们上写上Deepin， 通过统一的设计风格来强化大家对Deepin品牌的认识， 内部代码可以轻量化一点， 就叫launcher

**Comment by dragondjf** [comment]
系统级软件命名：
1. 要么采用统一的dde-dock、dde-launcher、dde-desktop、dde-control-center、dde-file-manager
2. 要么采用Dock、Launcher、Desktop、Control Center、File Manager

应用级软件命名
         统一Deepin开头，如Deepin Music、Deepin Movie等

关于系统级命名，我个人更喜欢1中的名称，说实话DDE比较丑；

至于项目About和宣传文档当然要更多的突出Deepin名牌。

**Comment by sonald** [comment]
这里其实有两个层次：如果是走国际化，每个组件的确应该自由命名，这比较看起来是独立运作的，体现出它们的独立性。基本上每个DE项目都是这样的吧。只不过每个组件在命名时应该有一定的规范可循，像 @fasheng 和 @iceleaf916 说的那样

**Comment by fasheng** [comment]
还有一种可能，全部使用 Deepin 做前缀，arch 下的包名就这么做的（deepin-control-center，deepin-daemon，deepin-music），其实看着也挺舒服，也有助于品牌宣扬，只是和 git 项目名不一致～
或者最后选用 @dragondjf 的方案，即 4/5 和 1 保持一致即可？

**Comment by hualet** [comment]
项目名称和包名我赞成保持目前的 dde-开头为DE基本组件，deepin-开头为独立应用的方式。用户界面和文档中"Control Center"或者"Deepin Control Center"两者都比"DDE Control Center"。

**Comment by fasheng** [comment]
好的，如果大家没有其他意见，那就决定使用 Control Center，Deepin Music 这种格式（README，qApp Name 与用户文档保持一致），之前 README 中的名称由我来处理，qApp Name 由 @hualet 处理（version 先使用前两位大版本号吧，如 3.0）。文档规范会随后整理。

**Comment by iceleaf916** [comment]
命名是程序员永恒的话题，建议讨论到这里统一了就好了，大家按照 @fasheng 的建议一起处理吧

**Comment by hualet** [comment]
好的。

**Comment by fasheng** [comment]
@hualet 看一楼~
