### ISSUE TITLE
dde-control-center (sound effect).

### ISSUE THREAD

**Issue by sarojpoudel33** [linuxdeepin/developer-center#3101]
This is an Request/Suggestion to adjust sound effect Volume by User.

QnA
1. When we set default volume to 100?
-> sound effect goes scary so, we humbly request you to provided a separated volume slider (as per image) for Sound Effect where user can adjust their volume without changing default Volume Bar. 

![dde-control-center](https://user-images.githubusercontent.com/45546591/163895987-08387e9a-7a10-4129-8008-9e16dceccde8.jpg)

**Comment by sarojpoudel33** [comment]
@BLumia  @hualet @justforlxz

**Comment by BLumia** [comment]
Hi, please use discussion board for feature request :)

Duplicated of https://github.com/linuxdeepin/developer-center/discussions/2926, let's discuss the idea there :)

**Comment by meiyixiang** [comment]
Hello, we have recorded your suggestion
