### ISSUE TITLE
deepin scanner does not show translations into other languages

### ISSUE THREAD

**Issue by alvarosamudio** [linuxdeepin/developer-center#3104]
![image](https://user-images.githubusercontent.com/25090546/142886206-0022500d-22e0-4303-ba25-72ab5c05483d.png)
 deepin scanner does not show translations to other languages, also the "simple scan" package should be replaced by deepin scanner in the ISO.

**Comment by BLumia** [comment]
Hi, the [deepin-scanner](https://github.com/martyr-deepin/deepin-scanner) project is no longer maintained, so I'll close this issue for now. We suggest you use GNOME [simple-scan](https://github.com/GNOME/simple-scan) instead at the moment and we hope we can bring the deepin-scanner project back in the future, and if anyone would like to give the deepin-scanner project some love, please also feel free to fork it, maintain your own fork and share it to the community if you like :)
