### ISSUE TITLE
桌面使用Shift选中文件的行为与预期不符

### ISSUE THREAD

**Issue by shenmo7192** [linuxdeepin/developer-center#3108]
### SUMMARY | 问题概要

在桌面上使用shift+方向键选中，行为同在dde-file-manager中，而不是向上选中

### STEPS TO REPRODUCE | 复现步骤

1. 在桌面上使用shift+方向键选中

### OBSERVED RESULT | 观察到的结果
见视频：选中了左侧所有文件而不是只选中了同列上的

### EXPECTED RESULT | 期望的结果

只选中同列的
### SOFTWARE/OS VERSIONS | 软件/系统版本信息
```bash
shenmo@shenmo-PC:~$ apt policy dde-file-manager
dde-file-manager:
  已安装：5.5.10-1
  候选： 5.5.10-1
  版本列表：
 *** 5.5.10-1 500
        500 https://community-packages.deepin.com/deepin apricot/main amd64 Packages
        100 /usr/lib/dpkg-db/status

```

### ADDITIONAL INFORMATION | 额外补充

desktop虽然也是一个文件夹，但是管理逻辑应当不同于普通的文件夹

普通文件夹的文件堆叠逻辑是从左到右再从上到下，而桌面是从上到下再到从左到右，可以认为是逆时针旋转了90度

从操作逻辑上讲，在desktop上使用shift+↑，逻辑上实质应当与在普通文件夹中按shift+←一直，而shift+←应该和普通文件夹中shift+↑一致。

这可能是一个bug，因为逻辑不对应，也可能是一个 feature request，因为目前一刀切的处理似乎也不算是一个错误

如果这需要被移到Discussioin，就麻烦各位大佬了

录屏：https://www.bilibili.com/video/BV1MS4y1A7xP/

**Comment by BLumia** [comment]
@meiyixiang 需要确认下是设计如此还是 bug = =

**Comment by meiyixiang** [comment]
你好当前你说描述的内容就是这样设计的。

**Comment by meiyixiang** [comment]
是为了保持桌面和文管的组合交互统一

**Comment by shenmo7192** [comment]
> 是为了保持桌面和文管的组合交互统一

简单来说就是反正都是一个组件就不做区分了~
