### ISSUE TITLE
麦克风异常

### ISSUE THREAD

**Issue by Fozei** [linuxdeepin/developer-center#3109]
### SUMMARY | 问题概要

无论使用有线耳机，还是蓝牙耳机，录音，录屏时，输入设备均是机器本身自带的麦克风，而不是耳机上的麦克风。

### STEPS TO REPRODUCE | 复现步骤

1. 插入有线耳机，设置-》声音-》输入设备 没有除系统默认选项之外其他选项
2. 将耳麦拿远，轻轻敲击耳麦，查看系统输入反馈音量，基本无变化，将耳麦接近机器键盘，轻敲耳麦，输入反馈音量，变化明显。
3. 连接蓝牙耳机，设置-》声音-》输入设备 没有除系统默认选项之外其他选项
4. 远离机器键盘，轻轻敲击耳麦，查看系统输入反馈音量，基本无变化，将耳麦接近机器键盘，轻敲耳麦，输入反馈音量，变化明显。

### EXPECTED RESULT | 期望的结果
应该正确识别当前是哪个录入设备，或者在 设置-》声音-》输入增加相应下拉选项，供用户选择

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Deepin 20.5

联想T460

**Comment by justforlxz** [comment]
麻烦使用 deepin-feedback 收集一下日志，然后将压缩包上传吧。

**Comment by Fozei** [comment]
> 麻烦使用 deepin-feedback 收集一下日志，然后将压缩包上传吧。

不用客气，请问下是需要所有类型日志文件吗？那种级别的还是全部？时间范围有要求没？

**Comment by justforlxz** [comment]
> > 麻烦使用 deepin-feedback 收集一下日志，然后将压缩包上传吧。
> 
> 不用客气，请问下是需要所有类型日志文件吗？那种级别的还是全部？时间范围有要求没？

复现该问题，然后去执行命令，主要是想看dmesg,jounal,pulseaudio 和 dde 后端的日志，看看是哪个环节出现了问题。

**Comment by Fozei** [comment]
今早在尝试复现问题时，发现3.5插孔有线二级正常，不能复现了，但是蓝牙耳机能复现。github上传附件有大小限制，传论坛了。https://bbs.deepin.org/post/235462，如果是个例的话，可以关闭issue，如果后续有线耳机再复现的话，我再反馈。

**Comment by justforlxz** [comment]
> 今早在尝试复现问题时，发现3.5插孔有线耳机正常，不能复现了，但是蓝牙耳机能复现。github上传附件有大小限制，传论坛了。如果是个例的话，可以关闭issue，如果后续有线耳机再复现的话，我再反馈。[论坛反馈帖，有附件](https://bbs.deepin.org/post/235462)

没有看到附件呀 😭

**Comment by BLumia** [comment]
😂 论坛确实没看到附件，三个月过去了目前也没看到新的信息补充。deepin 也于前些时间发布了 v20.6 ，我们这边也没复现这个问题，这个就暂时先关闭了。

建议考虑更新到 v20.6 再试试看，如果这个问题现在仍然存在的话，建议开个新的 issue 反馈（有必要的话可以在新 issue 的描述里链接到这个 issue），记得一定要附带相关信息，确保你之外的人能根据你提供的信息复现/定位问题，这样我们才可以真正开始处理问题。
