### ISSUE TITLE
「Feature」Internal test channel optimization

### ISSUE THREAD

**Issue by yxsos** [linuxdeepin/developer-center#3114]
Functional background: The current internal test channel is added to manually add a corresponding source address, and it is not friendly for the novice users of some Linux systems.
Specific changes: Add the internal test channel to the control center to apply for internal test qualifications

功能背景：当前内测通道加入需要手动添加对应源地址,对于部分linux系统的新手用户而言不够友好
具体变更：在控制中心中增加内测开关用以申请加入内测通道

**Comment by shenmo7192** [comment]
内测开始逐渐转为公测了
