### ISSUE TITLE
Freedif mirror - Update location and spec

### ISSUE THREAD

**Issue by karibuTW** [linuxdeepin/developer-center#3117]
Hello
I'm the admin of the Vietnam mirror mirror.freedif.org.
I've changed location and the server is now located in Singapore, on 1 GBPS connection with fresh config (Ryzen)

The link has not changed
https://mirror.freedif.org/Deepin/

and I keep mirroring the deepin and deepin CD.

Would you be able to update your mirror info accordingly?

Thank you

**Comment by yxsos** [comment]
Hi,there:
    We have completed modifications. 
    If you have something new problem，Welcome to create new issue.
![image](https://user-images.githubusercontent.com/44915039/164979231-5698b3ee-2150-40c3-ba1c-58a558325c27.png)
