### ISSUE TITLE
dde-grand-search 构建失败

### ISSUE THREAD

**Issue by msojocs** [linuxdeepin/developer-center#3118]
### SUMMARY | 问题概要

尝试构建`dde-grand-search`但是报错

### STEPS TO REPRODUCE | 复现步骤

1. 按照仓库的构建方式执行命令 https://github.com/linuxdeepin/dde-grand-search
2. 执行`make`后出现报错
3. 报错概要`error: template with C linkage`

### OBSERVED RESULT | 观察到的结果

<details>
<summary>部分报错情况</summary>

[ 30%] Building CXX object src/grand-search/CMakeFiles/dde-grand-search.dir/utils/utils.cpp.o
cd /mnt/disk2/Deepin/dde-grand-search/Build/src/grand-search && /usr/bin/c++ -DENABLE_ACCESSIBILITY -DPLUGIN_PREVIEW_DIR=\"/usr/lib//dde-grand-search/plugins/preview\" -DPLUGIN_SEARCHER_DIR=\"/usr/lib//dde-grand-search-daemon/plugins/searcher\" -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQ_HOST_NAME=\"x86_64\" -DQ_HOST_X86_64 -DQ_OS_MANJARO -DQ_OS_VERSION=\"21.2.6\" -I/mnt/disk2/Deepin/dde-grand-search/Build/src/grand-search -I/mnt/disk2/Deepin/dde-grand-search/src/grand-search -I/mnt/disk2/Deepin/dde-grand-search/Build/src/grand-search/dde-grand-search_autogen/include -I/mnt/disk2/Deepin/dde-grand-search/src -I/usr/include/libdtk-5.5.21/DCore -I/usr/include/libdtk-5.5.21/DGui -I/usr/include/libdtk-5.5.21/DWidget -I/mnt/disk2/Deepin/dde-grand-search/include -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/libmount -I/usr/include/blkid -isystem /usr/include/qt -isystem /usr/include/qt/QtCore -isystem /usr/lib/qt/mkspecs/linux-g++ -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtDBus -g -Wall -Wl,--as-need -fstack-protector-all -z now -Ofast -fPIE -pie -fPIC -std=gnu++14 -MD -MT src/grand-search/CMakeFiles/dde-grand-search.dir/utils/utils.cpp.o -MF CMakeFiles/dde-grand-search.dir/utils/utils.cpp.o.d -o CMakeFiles/dde-grand-search.dir/utils/utils.cpp.o -c /mnt/disk2/Deepin/dde-grand-search/src/grand-search/utils/utils.cpp
In file included from /usr/include/glib-2.0/glib/glib-typeof.h:39,
                 from /usr/include/glib-2.0/glib/gatomic.h:28,
                 from /usr/include/glib-2.0/glib/gthread.h:32,
                 from /usr/include/glib-2.0/glib/gasyncqueue.h:32,
                 from /usr/include/glib-2.0/glib.h:32,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /mnt/disk2/Deepin/dde-grand-search/src/grand-search/utils/utils.cpp:22:
/usr/include/c++/11.2.0/type_traits:56:3: error: template with C linkage
   56 |   template<typename _Tp, _Tp __v>
      |   ^~~~~~~~
/mnt/disk2/Deepin/dde-grand-search/src/grand-search/utils/utils.cpp:21:1: note: ‘extern "C"’ linkage started here
   21 | extern "C" {
      | ^~~~~~~~~~
In file included from /usr/include/glib-2.0/glib/glib-typeof.h:39,
                 from /usr/include/glib-2.0/glib/gatomic.h:28,
                 from /usr/include/glib-2.0/glib/gthread.h:32,
                 from /usr/include/glib-2.0/glib/gasyncqueue.h:32,
                 from /usr/include/glib-2.0/glib.h:32,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /mnt/disk2/Deepin/dde-grand-search/src/grand-search/utils/utils.cpp:22:
/usr/include/c++/11.2.0/type_traits:71:3: error: template with C linkage
   71 |   template<typename _Tp, _Tp __v>
      |   ^~~~~~~~
/mnt/disk2/Deepin/dde-grand-search/src/grand-search/utils/utils.cpp:21:1: note: ‘extern "C"’ linkage started here
   21 | extern "C" {
      | ^~~~~~~~~~
In file included from /usr/include/glib-2.0/glib/glib-typeof.h:39,
                 from /usr/include/glib-2.0/glib/gatomic.h:28,
                 from /usr/include/glib-2.0/glib/gthread.h:32,
                 from /usr/include/glib-2.0/glib/gasyncqueue.h:32,
                 from /usr/include/glib-2.0/glib.h:32,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /mnt/disk2/Deepin/dde-grand-search/src/grand-search/utils/utils.cpp:22:
/usr/include/c++/11.2.0/type_traits:80:3: error: template with C linkage
   80 |   template<bool __v>
      |   ^~~~~~~~
/mnt/disk2/Deepin/dde-grand-search/src/grand-search/utils/utils.cpp:21:1: note: ‘extern "C"’ linkage started here
   21 | extern "C" {
      | ^~~~~~~~~~
In file included from /usr/include/glib-2.0/glib/glib-typeof.h:39,
                 from /usr/include/glib-2.0/glib/gatomic.h:28,
                 from /usr/include/glib-2.0/glib/gthread.h:32,
                 from /usr/include/glib-2.0/glib/gasyncqueue.h:32,
                 from /usr/include/glib-2.0/glib.h:32,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /mnt/disk2/Deepin/dde-grand-search/src/grand-search/utils/utils.cpp:22:
/usr/include/c++/11.2.0/type_traits:91:3: error: template with C linkage
   91 |   template<bool, typename, typename>
      |   ^~~~~~~~
/mnt/disk2/Deepin/dde-grand-search/src/grand-search/utils/utils.cpp:21:1: note: ‘extern "C"’ linkage started here
   21 | extern "C" {
      | ^~~~~~~~~~
In file included from /usr/include/glib-2.0/glib/glib-typeof.h:39,
                 from /usr/include/glib-2.0/glib/gatomic.h:28,
                 from /usr/include/glib-2.0/glib/gthread.h:32,
                 from /usr/include/glib-2.0/glib/gasyncqueue.h:32,
                 from /usr/include/glib-2.0/glib.h:32,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /mnt/disk2/Deepin/dde-grand-search/src/grand-search/utils/utils.cpp:22:
/usr/include/c++/11.2.0/type_traits:94:3: error: template with C linkage
   94 |   template <typename _Type>
      |   ^~~~~~~~
/mnt/disk2/Deepin/dde-grand-search/src/grand-search/utils/utils.cpp:21:1: note: ‘extern "C"’ linkage started here
   21 | extern "C" {
      | ^~~~~~~~~~
In file included from /usr/include/glib-2.0/glib/glib-typeof.h:39,
                 from /usr/include/glib-2.0/glib/gatomic.h:28,
                 from /usr/include/glib-2.0/glib/gthread.h:32,
                 from /usr/include/glib-2.0/glib/gasyncqueue.h:32,
                 from /usr/include/glib-2.0/glib.h:32,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /mnt/disk2/Deepin/dde-grand-search/src/grand-search/utils/utils.cpp:22:
/usr/include/c++/11.2.0/type_traits:98:3: error: template with C linkage
   98 |   template<typename _Tp>
      |   ^~~~~~~~
/mnt/disk2/Deepin/dde-grand-search/src/grand-search/utils/utils.cpp:21:1: note: ‘extern "C"’ linkage started here
   21 | extern "C" {
      | ^~~~~~~~~~
In file included from /usr/include/glib-2.0/glib/glib-typeof.h:39,
                 from /usr/include/glib-2.0/glib/gatomic.h:28,
                 from /usr/include/glib-2.0/glib/gthread.h:32,
                 from /usr/include/glib-2.0/glib/gasyncqueue.h:32,
                 from /usr/include/glib-2.0/glib.h:32,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /mnt/disk2/Deepin/dde-grand-search/src/grand-search/utils/utils.cpp:22:
/usr/include/c++/11.2.0/type_traits:101:3: error: template with C linkage
  101 |   template<typename...>
      |   ^~~~~~~~
.....

</details>

### EXPECTED RESULT | 期望的结果

构建正常通过

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

| 软件 | 版本 |
|--|--|
| OS | Manjaro Linux x86_64 |
| Kernel | 5.15.32-1-MANJARO |
| gio-qt | 0.0.11-1 |
| make | 4.3 |
| cmake | 3.23.0 |
| gcc | 11.2.0 |

### ADDITIONAL INFORMATION | 额外补充

相关报错行：
https://github.com/linuxdeepin/dde-grand-search/blob/c19b7fc441d55d7912ad38c7dd02ea116dd0abb0/src/grand-search/utils/utils.cpp#L22

我尝试对其进行修正，以下代码帮助我构建成功：

修改前：
```
extern "C" {
#include <gio/gio.h>
#include <gio/gdesktopappinfo.h>
#include <ctype.h>
}

#include "utils.h"
```
修改后：
```
extern "C" {
#include <ctype.h>
}
#include <gio/gdesktopappinfo.h>
#include <gio/gio.h>

#include "utils.h"
```
edit: 不知道发生了什么，第二天重新验证发现`gio/gdesktopappinfo.h`也得移出去
执行以上修改后，在我的环境下编译正常，能够正常启动。

**Comment by BLumia** [comment]
欢迎 PR :)

**Comment by Clauszy** [comment]
这个报错可能是在extern "C" {} 中引入了c++的头文件，在你环境中 #include <gio/gdesktopappinfo.h>
#include <gio/gio.h> 这两个文件是否间接引入了c++的头文件？
