### ISSUE TITLE
Commit message 描述中包含 # 会导致 commitlint 失败

### ISSUE THREAD

**Issue by BLumia** [linuxdeepin/developer-center#3122]
### SUMMARY | 问题概要

Commit message 描述中包含 `#` 会导致 commitlint 失败

示例：

```
test: headline

org/repo#123

Log: test log
```

可以使用[我们当前的配置](https://github.com/linuxdeepin/.github/blob/b5a441b9bbf72915dc577d03bcf04aa83e724fc4/commitlint/commitlint.config.js)然后手动进行这种检查（`cat commitmsg.txt | npx commitlint`）

### STEPS TO REPRODUCE | 复现步骤

创建描述中包含 `#` 字符的 commit message，然后发起 PR。

另见：https://github.com/linuxdeepin/dde-grand-search/pull/4

### OBSERVED RESULT | 观察到的结果

```
✖   缺少描述信息 [body-enum]
```

<details>
<summary>完整输出以及此时的 parsed 对象内容</summary>

```
{
  type: 'test',
  scope: null,
  subject: 'headline',
  merge: null,
  header: 'test: headline',
  body: null,
  footer: 'org/repo#123\n\nLog: test log',
  notes: [],
  references: [
    {
      action: null,
      owner: 'org',
      repository: 'repo',
      issue: '123',
      raw: 'org/repo#123',
      prefix: '#'
    }
  ],
  mentions: [],
  revert: null,
  raw: 'test: headline\r\n\r\norg/repo#123\r\n\r\nLog: test log\r\n'
} null
⧗   input: test: headline

org/repo#123

Log: test log
✖   缺少描述信息 [body-enum]

✖   found 1 problems, 0 warnings
ⓘ   Get help:
Commit 信息规范: https://github.com/linuxdeepin/developer-center/wiki/Commit-%E6%8F%90%E4%BA%A4%E4%BF%A1%E6%81%AF%E8%A7%84%E8%8C%83
Commit Information standard en: https://github.com/linuxdeepin/developer-center/wiki/Commit-Information-standard-en
```

</details>

### EXPECTED RESULT | 期望的结果

正常通过检查

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```
    "@commitlint/cli": "^16.2.3",
    "@commitlint/config-conventional": "^16.2.1"
```

### ADDITIONAL INFORMATION | 额外补充

commitlint 是把 `#数字` 当工单号了，然后认为贴工单号是 footer 的行为，就把那行起直到最后的部分视为 footer 了。

commitlint 的这个格式归类好像和我们的预期并不一致，感觉改它的成本好像都够自己纯手写这种检查了....

**Comment by myml** [comment]
咱们现在commit检查还是比较简单的规则，就是怕之后会不会变得复杂

**Comment by BLumia** [comment]
在 https://github.com/linuxdeepin/.github/pull/286 中改用了 [action-conventionalcommits-checker](https://github.com/linuxdeepin/action-conventionalcommits-checker) 作为新的检查工作流。 时间缘故，目前版本[硬编码了一些检查规则](https://github.com/linuxdeepin/action-conventionalcommits-checker/blob/a1f913ad2446314b4366f20ded26339f49ae2bdc/conventionalcommits-checker/checker.go#L25)，规则如下：

1. 标题一行必须符合 conventional commits 规范（包含 type 与 description 即可，scope 与 `!` 为可选）
2. 除标题外的部分不得为空，即至少需包含描述文字
3. 若提交使用了 uniontech 邮箱，则要求添加 `Log:` 脚注（trailer）字段
4. 例外规则：若发现提交为机器人或 GitHub 自动生成的合并提交，则不报错
