### ISSUE TITLE
deepin-mail在firefox下无法处理mailto链接——附带解决方法

### ISSUE THREAD

**Issue by shenmo7192** [linuxdeepin/developer-center#3123]
### SUMMARY | 问题概要

deepin-mail在firefox下无法处理mailto链接，会直接启动而不是进入发信界面

经测试，在Chrome下可行

### STEPS TO REPRODUCE | 复现步骤

见 https://bbs.deepin.org/post/232260

### OBSERVED RESULT | 观察到的结果

在firefox下无法拉起

### EXPECTED RESULT | 期望的结果

正常拉起
### ADDITIONAL INFORMATION | 额外补充

参考了能正常拉起的星火商店/Mailspring应用，发现问题在于.desktop文件

当Exec=后面的参数为 %F 时，无法拉起；当参数为`%U`时，正常拉起

![图片](https://user-images.githubusercontent.com/47873776/164888422-e4e04af3-a494-4a9d-bf19-40b271a9d390.png)

应当写成 %U

![图片](https://user-images.githubusercontent.com/47873776/164888446-80a3c791-5b99-4244-9ec0-c1ecadb6f889.png)
![图片](https://user-images.githubusercontent.com/47873776/164888452-451dc515-2fa5-47b9-83c4-575a97d78c65.png)
![图片](https://user-images.githubusercontent.com/47873776/164888462-a5e86334-4687-4857-b24b-8d4ad82e7727.png)

录屏等 https://bbs.deepin.org/post/232260

手动改`/usr/share/applications`后可以正常拉起

（如果deepin-mail开源了我就去pr了）

**Comment by shenmo7192** [comment]
爽快，终于可以接着用deepin-mail了

**Comment by shenmo7192** [comment]
https://github.com/linuxdeepin/developer-center/discussions/3121

此discussion已无效

**Comment by zccrs** [comment]
是的，理应为 %U

**Comment by yxsos** [comment]
正在联系对应研发处理，最终结果会在这里同步。

**Comment by yxsos** [comment]
已安排研发进行修改，由于涉及系统关联性验证，计划在5.1之后在商店进行推送更新。：）

**Comment by yxsos** [comment]
进展同步：相关项目组已就此问题进行修改，近期会将此修复上架商店。

**Comment by SuperEffie** [comment]
感谢您的反馈，这个问题已经在deepin v20.6上5.4.3版本的邮箱上修复并且推送出去了，您可以进行验证。现在我先将这个issue关闭了。欢迎您为我们提供更多的宝贵建议哦~
