### ISSUE TITLE
dde-file-manager在尝试永久删除某些文件夹（比如wine容器）时无法删除且不报错

### ISSUE THREAD

**Issue by shenmo7192** [linuxdeepin/developer-center#3125]
### SUMMARY | 问题概要

dde-file-manager在尝试永久删除某些文件夹（比如wine容器）时无法删除且不报错

同时`rm`可用

### STEPS TO REPRODUCE | 复现步骤

1. 尝试删除 `~/.deepinwine/`下的任何一个应用容器

### OBSERVED RESULT | 观察到的结果

什么都没有发生

### EXPECTED RESULT | 期望的结果
删除容器或者报错

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```
shenmo@shenmo-PC:~$ dde-file-manager -v
dde-file-manager 5.5.10
```
---
```
              ............                shenmo@shenmo-PC
          .';;;;;.       .,;,.            OS: Deepin 20.5 apricot
       .,;;;;;;;.       ';;;;;;;.         Kernel: x86_64 Linux 5.15.24-amd64-desktop
     .;::::::::'     .,::;;,''''',.       Uptime: 1h 13m
    ,'.::::::::    .;;'.          ';      Packages: 2401
   ;'  'cccccc,   ,' :: '..        .:     Shell: bash
  ,,    :ccccc.  ;: .c, '' :.       ,;    Resolution: 1920x1080
 .l.     cllll' ., .lc  :; .l'       l.   DE: Deepin 20.5
 .c       :lllc  ;cl:  .l' .ll.      :'   WM: KWin
 .l        'looc. .   ,o:  'oo'      c,   GTK Theme: deepin [GTK2/3]
 .o.         .:ool::coc'  .ooo'      o.   Icon Theme: blossom-light
  ::            .....   .;dddo      ;c    CPU: AMD Ryzen 7 5800H with Radeon Graphics @ 16x 3.2GHz
   l:...            .';lddddo.     ,o     GPU: NVIDIA GeForce RTX 3060 Laptop GPU
    lxxxxxdoolllodxxxxxxxxxc      :l      RAM: 5113MiB / 15469MiB
     ,dxxxxxxxxxxxxxxxxxxl.     'o,      
       ,dkkkkkkkkkkkkko;.    .;o;        
         .;okkkkkdl;.    .,cl:.          
             .,:cccccccc:,. 

```

### ADDITIONAL INFORMATION | 额外补充

录屏：https://www.bilibili.com/video/BV1yZ4y117hb/

**Comment by BLumia** [comment]
@babyfengfjx 需要验证一下。

顺便，GitHub 其实是能传 mp4 视频的，方便的话可以考虑直接把视频放到 issue 里，就不用等 b 站审核了 :)

**Comment by shenmo7192** [comment]
> @babyfengfjx 需要验证一下。
> 
> 顺便，GitHub 其实是能传 mp4 视频的，方便的话可以考虑直接把视频放到 issue 里，就不用等 b 站审核了 :)

梯子比较垃，所以上传到github速度一般比较慢
如果你更希望我上传到github，我会这样做的

**Comment by BLumia** [comment]
> 如果你更希望我上传到github，我会这样做的

都可以的，以你方便的方式就行

**Comment by babyfengfjx** [comment]
- 版主这个效果是如何来的，感觉我这操作挺丝滑的：
![录屏_dde-file-manager_20220427161017](https://user-images.githubusercontent.com/24642999/165472479-acfab66b-92f2-4701-b20d-f4947ff4d9b7.gif)

**Comment by shenmo7192** [comment]
> * 版主这个效果是如何来的，感觉我这操作挺丝滑的：
>       ![录屏_dde-file-manager_20220427161017](https://user-images.githubusercontent.com/24642999/165472479-acfab66b-92f2-4701-b20d-f4947ff4d9b7.gif)

直接删除会进入回收站
`shift+delete` 永久删除会出问题

**Comment by SuperEffie** [comment]
感谢您的反馈，这个问题我们已经提交给研发人员分析了，后期会对问题的进展进行跟踪，若开发者们给出解决方案，我们会在这里通知您。

**Comment by kt286** [comment]
貌似不是删除不了，只是速度极慢

**Comment by babyfengfjx** [comment]
> 
有多慢，我这盯着半天好像也没见消失哇……

**Comment by shenmo7192** [comment]
> 貌似不是删除不了，只是速度极慢

对于小文件极多的，因为dde-file-manager删除东西慢，所以要等很久
对于本来直接删除会报错(rm不会报错，不知道为啥dfm会报错）的，会不消失

**Comment by kt286** [comment]
https://github.com/linuxdeepin/dde-file-manager/commit/f4c2d01d633d461e10543bdaa8c82502799fb1e7

不知道这个补丁有没有解决你说的问题

**Comment by kt286** [comment]
内测 5.6.8 版本已经修复
