### ISSUE TITLE
Abnormal size of the kern.log, messages, syslog files

### ISSUE THREAD

**Issue by gustam88** [linuxdeepin/developer-center#3127]
After successfully installed the DeepinOS, the size of the kern.log, messages, syslog files in the var/log directory will increase continuously. Even though I deleted it, the file will re-appear and its size will continue to increase until my HDD is full. How to solve this?

**Comment by Zeno-sole** [comment]
There should be some errors in the continuous output, you can see what the content of the file is reporting the error

**Comment by BLumia** [comment]
Closing due to no response. If you are still facing this issue, please consider providing more details (e.g. error log content) so we can look into it. Thanks!
