### ISSUE TITLE
Dock stops working when running FL Studio with wine

### ISSUE THREAD

**Issue by saimfd** [linuxdeepin/developer-center#313]
I installed FL studio using playonlinux but when I run it, it runs fine but the dock stops working. I cannot click on anything or open any app from it. It just stops responding. When I close fl studio, the docks start working again.

**Comment by sbwtw** [comment]
It looks like FL Studio hangs and no responding.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
