### ISSUE TITLE
控制中心的"系统信息"和二级菜单"快捷键"异常

### ISSUE THREAD

**Issue by weclix** [linuxdeepin/developer-center#3135]
平台:archlinux+dde
版本:控制中心=5.4.70-2
操作:
1、打开控制中心->点击"系统信息"
2、打开控制中心->点击"键盘和语言"->选择"快捷键"
预期和现象:
1、预期:进入"系统信息"页面显示系统信息；现象：无法进入控制中心窗口强制退出
2、预期:进入"快捷键"页面查看和设置快捷键；现象：无法进入控制中心窗口强制退出；
额外信息:
操作1使用终端重复操作,得到如下信息:
` [Warning] [  ] QWidget::setLayout: Attempting to set QLayout "" on dccV20::systeminfo::NativeInfoWidget "ContentWidget", which already has a layout`
操作2使用终端打开控制中心,得到如下信息:
`GLib-GIO-ERROR **: 14:31:41.423: Settings schema 'com.deepin.dde.control-center' does not contain a key named 'color-picker-config'`

**Comment by BLumia** [comment]
关联：https://github.com/linuxdeepin/developer-center/issues/2716

**Comment by BLumia** [comment]
控制中心更新到 

```
名字           : deepin-control-center
版本           : 5.5.77-2
```

后应该已修复，点快捷键不会再崩溃。点系统信息也不再稳定崩溃但还是偶见崩溃现象，后者应该是别的问题导致的了，如果你也能复现后者的话，可以考虑开的新的 issue。

再次感谢反馈问题！
