### ISSUE TITLE
deepin-mail failed to start

### ISSUE THREAD

**Issue by ruleeeer** [linuxdeepin/developer-center#3136]
### SUMMARY | 问题概要

deepin-mail failed to start

### STEPS TO REPRODUCE | 复现步骤

My initial installation of deepin-mail worked fine, but it suddenly flashed when downloading emails, and then I couldn't start deepin-mail successfully.
I'm not sure if the error is caused by the 1000+ emails in my email,

1. ...
2. ...
3. ...

### OBSERVED RESULT | 观察到的结果

![image](https://user-images.githubusercontent.com/70385062/165916876-b891fdcc-0d18-41ed-ac2e-b4450565a1fa.png)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息
deepin-mail: 5.4.1_1-1

![image](https://user-images.githubusercontent.com/70385062/165917182-a46c9232-982f-4e3a-9633-390b8449ad85.png)

**Comment by BLumia** [comment]
Arch Linux 没有 deepin-mail 这个包啊，你哪来的包？

**Comment by ruleeeer** [comment]
I went to check it out and it looks like it's aur and not an official package, so if you aren't going to deal with it you can close the issue first

![image](https://user-images.githubusercontent.com/70385062/165919910-80ef7401-ef0c-4248-ae8b-e74a1c53858e.png)
![image](https://user-images.githubusercontent.com/70385062/165920345-a806e306-c856-4b96-ae7a-b877077a74c8.png)

**Comment by BLumia** [comment]
> it's aur and not an official package

Yes. We don't support binary package from AUR.

By the way, we are working on migrating our development process to GitHub, so maybe we'll release the source code of this project next month so packagers could package it to other distros, and once after that, we'll be able to provide some help about the related packages :)
