### ISSUE TITLE
Window preview is always blank

### ISSUE THREAD

**Issue by ruleeeer** [linuxdeepin/developer-center#3137]
### SUMMARY | 问题概要

Window preview is always blank

### STEPS TO REPRODUCE | 复现步骤

The correct preview of the software is not displayed when the mouse is placed over the application on the dock

1. ...
2. ...
3. ...

### OBSERVED RESULT | 观察到的结果

![Record_select-area_20220429172801](https://user-images.githubusercontent.com/70385062/165919435-ab977c45-429e-4113-8290-464e841e3ec5.gif)

### EXPECTED RESULT | 期望的结果

Display the preview window correctly

### SOFTWARE/OS VERSIONS | 软件/系统版本信息
![image](https://user-images.githubusercontent.com/70385062/165919698-0055efa1-2557-4cad-baed-73332b79eab3.png)

**Comment by BLumia** [comment]
![image](https://user-images.githubusercontent.com/10095765/166852619-883834b1-6d9e-45af-b3cf-58d895498bd3.png)

Cannot reproduce under Arch Linux deepin-wm, but since @ruleeeer is using KWin, please verify if that's exists @justforlxz. Thanks!

**Comment by ruleeeer** [comment]
@SiamSami  Thank you for your reply,but there is no Deepin DE 20.5 in the arch repo yet

**Comment by justforlxz** [comment]
Confirm that the problem exist, I will fix it.

**Comment by justforlxz** [comment]
![image](https://user-images.githubusercontent.com/12298476/167989509-3f2f7359-68bf-42d3-8f27-620ccc1de7a8.jpeg)

i fixed it.
