### ISSUE TITLE
401 unauthorized bug

### ISSUE THREAD

**Issue by Octavian-Q** [linuxdeepin/developer-center#3139]
Hello
As far as I know there is a bug in apt on old Ubuntu based distros and Debian (in others I haven’t noticed it but in Deepin happened to me) I encounter when tried from GitHub to download a kernel, error is: unauthorized 401.
Also, as a suggestion for the future would be Deepin to use the most recent Debian version (some things are from Debian 10 and kind of outdated old)
![6BA181F1-3855-48F1-BC58-1654C3D488B3](https://user-images.githubusercontent.com/98664445/166265709-0eef000d-d1e3-4a3f-bf79-c3ca45361ffd.png)

**Comment by BLumia** [comment]
Hi, since you skipped the issue template, could you please provide the steps to reproduce the issue you've got? Also, 401 basically means you are unauthorized so it's probably not related to deepin.

**Comment by Octavian-Q** [comment]
Sorry, more context. I have Deepin on my surface book (considering is a Microsoft device I wanted to install a surface kernel built specially from the community)
 1. I imported keys to sign packages (command): $ wget -qO - https://raw.githubusercontent.com/linux-surface/linux-surface/master/pkg/keys/surface.asc \
    | gpg --dearmor | sudo dd of=/etc/apt/trusted.gpg.d/linux-surface.gpg
2. Adding repository configuration to apt (command): $ echo "deb [arch=amd64] https://pkg.surfacelinux.com/debian release main" \
	| sudo tee /etc/apt/sources.list.d/linux-surface.list
3. Updating apt (command): sudo apt update
4. Now final step kernel installation and dependencies (command): sudo apt install linux-image-surface linux-headers-surface iptsd libwacom-surface

After  step 4 I get the error 401 mentioned in screenshot and fails installation

**Comment by Zeno-sole** [comment]
It seems that there is a problem with the configuration of the warehouse, it is recommended that you download the deb directly for installation  https://pkg.surfacelinux.com/debian/pool/main/l/linux-surface/

**Comment by Octavian-Q** [comment]
> It seems that there is a problem with the configuration of the warehouse, it is recommended that you download the deb directly for installation https://pkg.surfacelinux.com/debian/pool/main/l/linux-surface/

Both image and headers? (2 links)

**Comment by Zeno-sole** [comment]
This is a bug of the apt tool, we have fixed this problem in the internal test source,

**Comment by Octavian-Q** [comment]
Ok, thank you

**Comment by Zeno-sole** [comment]
https://bbs.deepin.org/post/236139  @Octavian-Q  This is how to join the test
