### ISSUE TITLE
[已发现修复，希望尽快发布] winehq / lutris / proton 等非 deepin-wine 的托盘图标在被 dde-dock 收纳后均无法点击

### ISSUE THREAD

**Issue by SwimmingTiger** [linuxdeepin/developer-center#3140]
### SUMMARY | 问题概要

只要 wine 不是 deepin-wine，生成的托盘图标在被 dde-dock 收纳后就无法点击。只有 deepin-wine 生成的托盘图标可以正常点击。

### STEPS TO REPRODUCE | 复现步骤

1. 从 deepin 应用商店安装 wine 游戏助手，也可从这里下载deb：https://winegame.net/downloads/

2. 打开 https://winegame.net/games/tuo-pan-tu-biao-ce-shi-cheng-xu/

3. 依次安装1到5，安装到不同的目录（比如`~/Games/test1`到`~/Games/test5`）。

   ![image](https://user-images.githubusercontent.com/4986069/166676710-224c03c0-320c-47a7-a9ff-8d891f679629.png)

4. 如果在网页上点“安装”没反应，请执行以下命令进行诊断，并修复来自deepin的错误`.desktop`文件（这种事情曾经发生过）：

   ```
   sudo update-desktop-database -v
   ```

5. 启动前4个测试程序，你会发现只有deepin-wine生成的托盘图标可以点击，其他wine生成的托盘图标均不能点击，鼠标左击和右击均无任何反应。

   ![image](https://user-images.githubusercontent.com/4986069/166677730-5a95dcb3-5ee7-4322-accf-b3cd5bb62444.png)

6. 启动第5个测试程序，此时dde-dock会被以下命令不断杀死，任务栏会消失，所有wine的托盘图标均堆叠在左上角。把它们分开，然后尝试右击每个托盘图标，发现所有托盘图标均能正常交互。

   ```
   #!/bin/bash
   while true; do killall dde-dock; done
   ```

    ![image](https://user-images.githubusercontent.com/4986069/166678138-2c95b29a-7d42-4d6d-b856-74d6950d054e.png)

8. 停止第5个测试程序，然后右击它，选择“执行维护脚本”。此时dde-dock会被以下命令重新启动，任务栏重新出现，除deepin-wine之外的所以wine托盘图标均变回不能点击的状态。

   ```
   #!/bin/bash
   nohup dde-dock &>/dev/null &
   dde-dock &
   ```

### OBSERVED RESULT | 观察到的结果

dde-dock 与除 deepin-wine 之外的所有其他 wine 生成的托盘图标均不兼容，如果这些 wine 生成的托盘图标被 dde-dock 收纳，则用户无法正常与其交互。但是这些托盘图标本身并没有问题，如果结束 dde-dock 进程，则托盘图标可以正常交互。

### EXPECTED RESULT | 期望的结果

dde-dock 收纳其他 wine 的托盘图标后，这些图标可正常交互，就像 deepin-wine 的那样。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

根据我的最新尝试，统信发布的所有使用 dde-dock 的操作系统均存在该问题。UOS家庭版21.2已确认存在该问题，已安装所有更新。Deepin 20.5确认存在该问题，已安装所有更新。deepin 23nightly确认存在该问题，已安装所有更新。很少收到更新的UOS专业版自然也存在该问题。所以修复看起来尚未发布到任何软件源中。

![image](https://user-images.githubusercontent.com/4986069/166679168-1d864cf6-4070-4020-a14b-7e2d935ff753.png)

### ADDITIONAL INFORMATION | 额外补充

deepin-wine 的托盘图标确实可以正常点击，这是好消息，但这远远不够。

dde-dock 与 wine 托盘图标不兼容，靠修补 wine 来解决问题是正确的方法吗？不是。

用户对 wine 的需求（特别是游戏兼容性和游戏性能方面的需求）远比 deepin-wine 能提供的更多。

**Comment by SwimmingTiger** [comment]
我以为我上个issue被删了，原来是转移到这里了：
https://github.com/linuxdeepin/developer-center/issues/2262

看到相关修复：
https://github.com/linuxdeepin/dde-dock/commit/7b625b1ab7bcc32bf15382e01267d096858c89d4

希望这个补丁尽快发布到 UOS / Deepin 发行版中。

**Comment by SwimmingTiger** [comment]
deepin 20.5确认存在该问题，已安装所有更新。

**Comment by SwimmingTiger** [comment]
deepin 23nightly确认存在该问题，已安装所有更新。看起来修复尚未发布到任何软件源中。

**Comment by BLumia** [comment]
> 我以为我上个issue被删了，原来是转移到这里了： #2262

是，因为我们之前很少关注 developer-center 之外汇报的 issue 所以遗漏掉了很多 issue，就都集中到 developer-center 来进行相关的问题处理了。

> 看到相关修复： [linuxdeepin/dde-dock@7b625b1](https://github.com/linuxdeepin/dde-dock/commit/7b625b1ab7bcc32bf15382e01267d096858c89d4)

既然是重复的 issue 并且汇报人都是您这边，那么这个问题的后续进展请移步 https://github.com/linuxdeepin/developer-center/issues/2262 跟进~

> 希望这个补丁尽快发布到 UOS / Deepin 发行版中。

UOS 专业版和 deepin 社区版的发布周期和发布策略是不一样的，进入 master 分支的提交是肯定会有更新的，不过发布时间就无法保证了。

不过作为声明，UOS 是不受我们社区团队支持的，如果有 UOS 存在而 deepin 不存在的问题需要反馈的话，您需要通过 UOS 的问题反馈渠道进行反馈。

> deepin 23nightly确认存在该问题

这个 nightly 其实（至少目前）也不是拿各个项目的 master 分支构建软件包的，目前而言建议以是否有新 tag 来判断是否有版本发布。

因为是重复 issue 就先关掉了，后续请移步 #2262，若有与那个 issue 有差异的新问题的话，再开新的 issue 汇报就好。感谢~
