### ISSUE TITLE
Super L + Space no longer available for shortcuts

### ISSUE THREAD

**Issue by bmr5770** [linuxdeepin/developer-center#315]
I've been using the Kupfer utility attached to 'SuperL+Space' as it's hotkey.  
I've recently upgraded the following packages:
deepin-tool-kit-0.2.10-1-x86_64.pkg.tar.xz
deepin-menu-3.1.3-1-x86_64.pkg.tar.xz
deepin-screenshot-4.0.3-1-x86_64.pkg.tar.xz
deepin-daemon-3.1.10-1-x86_64.pkg.tar.xz
deepin-api-3.1.8-1-x86_64.pkg.tar.xz
deepin-session-ui-4.0.7-1-x86_64.pkg.tar.xz
deepin-desktop-schemas-manjaro-3.1.7-2-any.pkg.tar.xz

Previously, I've had to unset that key combo under the Deepin keyboard shortcuts but I'm no longer seeing it there.  This seems to be a bug where Deepin is holding onto that specific combo (and it shouldn't be if I've unset it). 

Note: I can create a new shortcut within the Deeping shortcuts menu and assign SuperL + Space there, just not outside of direct Deepin control.

**Comment by sbwtw** [comment]
@electricface
