### ISSUE TITLE
Microsoft Edge flickering gap 

### ISSUE THREAD

**Issue by Octavian-Q** [linuxdeepin/developer-center#3151]
Hello,
I have a weird behavior when open browser edge, between window and edge of the screen there is some kind of gap that is flickering 

Steps I do:
1. Microsoft Edge when I close is in full screen window (maximized)
2. When I start it again, it is also in maximized state but there is a gap flickering between screen and window itself
3. This happens almost all the time, even after I first start pc in the day, or after opening many times Edge 

Note:I havent notice this issue happens to any other apps (it may, I am not sure). Edge and most of other apps I always use them in maximized mode (full screen)

Additional information:
3000x2000 screen resolution, device Microsoft Surface Book, Deepin 20.5 kernel 5.15
YoutubeVideo link for visual better representation of the issue: https://youtu.be/TMCXog8rCIw

**Comment by BLumia** [comment]
Not 100% sure but probably a graphics card driver issue?

What if you install `systemsettings` and try set a different rendering backend, will that fix this issue?

![image](https://user-images.githubusercontent.com/10095765/167529649-30442124-7b43-4ab0-ba5d-dbcb89956ec1.png)

**Comment by Octavian-Q** [comment]
I tried all the rendering, its the same flickering in Edge. Also to add I am not using a discrete GPU, its integrated Intel
![Screenshot_deepin-terminal_20220510084845](https://user-images.githubusercontent.com/98664445/167557397-e2610fbf-b51b-4d11-8bdf-07503bdd770a.png)

**Comment by Octavian-Q** [comment]
> Not 100% sure but probably a graphics card driver issue?
> 
> What if you install `systemsettings` and try set a different rendering backend, will that fix this issue?
> 
> ![image](https://user-images.githubusercontent.com/10095765/167529649-30442124-7b43-4ab0-ba5d-dbcb89956ec1.png)

I think I found a solution, for some reason Hardware Acceleration is doing in edge the flickering, if I disable it, window seems to be fin
![Screenshot_select-area_20220512095028](https://user-images.githubusercontent.com/98664445/168009528-3f6f2bcc-59f2-4dc6-ac76-a5f3d154d837.png)
e

**Comment by BLumia** [comment]
Nice catch! Probably a problem with its hardware acceleration support and it seems [it also happening on Chrome](https://askubuntu.com/questions/1271139/chrome-flickering-on-kubuntu-20-04). I guess it's not a deepin issue so I'll close this one for now.

Thanks again for the report and the result :)
