### ISSUE TITLE
希望 dde 虚包可以标注所以软件包的具体版本 

### ISSUE THREAD

**Issue by wineee** [linuxdeepin/developer-center#3155]
项目仓库： https://github.com/linuxdeepin/dde

其 [debian](https://github.com/linuxdeepin/dde/tree/master/debian)/control  文件中，绝大部分软件都没有指定版本，我注意到虚包 dde 是有版本号（tag）的，如果不指定软件具体版本，这个版本号并没有太多意义。

此外,指定版本号可以让其他发行版的dde维护者明白哪些版本是兼容的，避免引入太新的包造成bug, 比如 deepin-anything 在 6.0.0 版本将 deepin-anything-server-lib 变成 deepin-anything-backend 破坏了兼容性，尽管后续在 master 中又改了回来

**Comment by BLumia** [comment]
能够做到在每次进行版本发布时都可以确定一个互相可兼容使用的版本列表是个很好的主意。不过我不是很确定这件事是否应当由 dde 这个虚包来做。debian 中其它的虚包也是指明版本的吗？

> 虚包 dde 是有版本号（tag）的，如果不指定软件具体版本，这个版本号并没有太多意义。

目前的 tag 应该只是对应虚包中的应用列表变更，并不能做到对应出某个版本的所有子应用列表。

> 避免引入太新的包造成bug

避免引入太新的包的意思是建议其它发行版在我们更新 dde 虚包中对应的包的版本号后，再让其它发行版更新这些包吗？这个问题的解决方向感觉反了，如果上层应用做了不兼容的变更，我觉得应该在这些上层应用中进行正确的依赖版本声明，对其依赖的应用做版本限制和检查。

无论是 SemVer（在破坏兼容性变更时需变更首位版本号之类）还是软件包自身的依赖声明都是为了避免”随意更新会 break 掉其它软件包“这样的问题发生的。如果无法避免问题的话，似乎得看下是什么导致了问题，并考虑是否要制定到项目管理/开发规范中。

--------

我不是很清楚虚包做明确的版本罗列是否是常规做法，如果是的话还是值得向常规做法靠拢的，如果不是，但目的是为了解决类如"无法得到互相兼容的软件包版本的列表“的问题的话，我个人觉得考虑别的方案或许更合适一些，比如每次发布时自动生成一个 DDE 软件包的版本列表文件以供后续参照查询之类（之前也确实想做这么个东西来着）。

一点看法，不一定对。

**Comment by wineee** [comment]
也许这些事不一定由这个虚包来做，实际上，我希望的定期维护一个 release notes,  尽管 https://www.deepin.org/zh/2022/03/31/deepin-20-5/ 中说明了 dde 的更新内容，但显然，它是针对 deepin 而非 dde 的，它甚至没有指明这些功能更新/bug修复对应的是影院/音乐/邮箱...哪个版本的变化  

此外，参考其他桌面环境的开发流程， dde 似乎缺少开发版和稳定版之分，（不确定是否可以认为uos的dde是稳定版，deepin的是开发版？） 

比如是否可以在每年某个月，由开发版本分支出来，冻结较大的特性修改，经过几个阶段维护，发布一个稳定版本，并且这个稳定版应该声明生命周期，在此期间保持bug修复等维护。

https://community.kde.org/Schedules/Plasma_5
https://wiki.xfce.org/releng/4.18/roadmap
https://wiki.gnome.org/FortyThree

**Comment by BLumia** [comment]
> 参考其他桌面环境的开发流程， dde 似乎缺少开发版和稳定版之分，（不确定是否可以认为uos的dde是稳定版，deepin的是开发版？）

deepin 社区版（至少目前）是滚动更新版本，（至少目前）没有 LTS，不过一些来自 UOS 专业版的 tag 是可能被推送到社区的，这些 tag 也可以被社区拿来使用。deepin 与 UOS 的关系也更接近 fedora 与 RedHat。

> 比如是否可以在每年某个月，由开发版本分支出来，冻结特性修改，经过几个阶段维护，发布一个稳定版本，并且这个稳定版应该声明生命周期，在此期间保持bug修复等维护。

目前仍然相当于 UOS 的团队属于上游，并且新的大版本是公司内部闭源开发，临近系统大版本发布时才向社区开源的，然后 deepin 是我们社区团队基于这个状态去进行相应的社区版发布。如果是希望 deepin 社区版能有自己的稳定分支并主导后续的新大版本开发的话，在开发流程全向拥抱社区前恐怕很难做到（不过目前也确实有这个意向了，目前在做的事情，包括开发流程迁移至社区之类，也都是为后续的这类工作做准备）。

**Comment by zccrs** [comment]
这种问题的原因主要是：

上游社区打DDE的包时不知道要打哪些组件的哪些版本，原因是好多组件的最新tag都有问题，不能只跟着项目的tag走，这是一个现状。正规的做法是应该组件自己维护好依赖关系，要确保只要这个tag能编译通过，程序就应该正常工作，不过恐怕短时间内还做不到，所以就会出现有需求想知道DDE所对应的各个组件的版本，如果维护了DDE虚包的依赖版本号，那自然是能大致保障虚包上所写的版本是验证过的，对其它社区来说有一定的参考性。不过归根结底还是应该解决tag信任危机。

**Comment by zccrs** [comment]
@Zeno-sole 短期内，我们更新DDE时可以直接写死依赖关系，每次更新DDE都同步更新dde这个虚包。
@BLumia 长期内，要准备一个检测机制，至少保障dde所有组件的最新tag都要能在最新的环境编译通过，并且正常启动，这些事项都可以做成自动化的。

**Comment by Zeno-sole** [comment]
> @Zeno-sole 短期内，我们更新DDE时可以直接写死依赖关系，每次更新DDE都同步更新dde这个虚包。 @BLumia 长期内，要准备一个检测机制，至少保障dde所有组件的最新tag都要能在最新的环境编译通过，并且正常启动，这些事项都可以做成自动化的。

依赖关系是相互的，dde这个虚包就像是树的顶端，分支依赖的版本号不应该在这个dde虚包里写死，各个应用之间的项目依赖应该由应用本身去写

**Comment by Rabenda** [comment]
> > @Zeno-sole 短期内，我们更新DDE时可以直接写死依赖关系，每次更新DDE都同步更新dde这个虚包。 @BLumia 长期内，要准备一个检测机制，至少保障dde所有组件的最新tag都要能在最新的环境编译通过，并且正常启动，这些事项都可以做成自动化的。
> 
> 依赖关系是相互的，dde这个虚包就像是树的顶端，分支依赖的版本号不应该在这个dde虚包里写死，各个应用之间的项目依赖应该由应用本身去写

dde这个虚包可以承担整个仓库的dde版本锁定功能 希望这个虚报可以锁定版本或者 锚定最小组合版本

**Comment by Zeno-sole** [comment]
dde的虚包写得都是应用的依赖，至于开发库的依赖不会去写，建议dde项目组去重新写一个需包去维护整个dde的开发库依赖
