### ISSUE TITLE
Arch Linux Deepin: Dock has a plain black background

### ISSUE THREAD

**Issue by shr70** [linuxdeepin/developer-center#316]
Hi,
after upgrading the deepin packages i keep having a black background in the deepin-dock. Furthermore the Deepin-Terminal is also plain black and the opacity isn't changable. There also is a little black square in the upper left corner. 
Could you please tell me which package is causing this issue so I can downgrade it?
![black-square](https://user-images.githubusercontent.com/13545543/27262660-bc96111c-545b-11e7-9b7f-9568edb1d2fc.png)
![dock](https://user-images.githubusercontent.com/13545543/27262659-bc9533a0-545b-11e7-9f47-24c049a30a32.png)
![terminal](https://user-images.githubusercontent.com/13545543/27262661-bc9806a2-545b-11e7-9c55-b7662718de17.png)

**Comment by felixonmars** [comment]
Looks like compositing is not working. Please confirm that your OpenGL driver is working correctly.

**Comment by shr70** [comment]
Yes the driver should be working.
After some more digging i found out that downgrading deepin-metacity to 3.22.8-1 fixes it. So the error seems to be caused by version 3.22.9-1.

**Comment by felixonmars** [comment]
@sonald Any idea?

**Comment by oberon2007** [comment]
Confirming that when I switch to metacity mode I have no transparency. All good in 3D-mode...

**Comment by keerisamba** [comment]
I had the same issue, First I thought it was because of an update. But then I create a new user account and logged in using the new account into deepin, and the problem was not there with the new account. If that is so, try rename/delete files in ~/.config/deepin*

**Comment by oberon2007** [comment]
Well, I have it on a first boot of a new ISO:
![](http://imgur.com/FG8zAcDl.png)
Maybe you just accidentially switched back to 3D @keerisamba ? Try using Shift+Super+Tab to go back and forth...?

**Comment by oberon2007** [comment]
With **deepin-metacity 3.22.8** transparency is working. **3.22.9** seems broken.

**Comment by sonald** [comment]
@felixonmars @oberon2007 deepin-metacity disables compositing support now by design. It's meant to be used in extreme situations, such as no viable graphics card or proper driver.

**Comment by sonald** [comment]
to force deepin-metacity to use compositing, exec `gsettings set com.deepin.wrap.gnome.metacity compositing-manager true`. There is no guarantee that'll works without problem.

**Comment by hualet** [comment]
There must be something wrong, the latest version of 2D version of DDE should be like this:

![deepinscreenshot_20170626120833](https://user-images.githubusercontent.com/2023967/27524541-553d2506-5a68-11e7-998f-12ba4637a5f1.png)

You see, the background of Dock and Control Center are dark grey instead of black.

**Comment by hualet** [comment]
Anyone can give me the versions of the following packages?

- deepin-dock
- deepin-control-center 
- libdtkwidget
- deepin-qt5integration

**Comment by oberon2007** [comment]
```
deepin-dock 4.2.1-1
deepin-control-center 4.1.2-1
error: package 'libdtkwidget' was not found
deepin-qt5integration 0.1.9-1
```
:)

**Comment by oberon2007** [comment]
**deepin-toolkit** maybe? ** 0.2.10.20170613-1**

**Comment by oberon2007** [comment]
Do we maybe need https://github.com/linuxdeepin/deepin-tool-kit/commit/5e9abd5df8a778cf026ffc4a021fb9bdcc9d651b ? ;)

**Comment by JulianLai** [comment]
It also has the tearing problem.

**Comment by oberon2007** [comment]
With **

**Comment by oberon2007** [comment]
With **v3.22.10** everything seems to be as it should then. By default the features are plain grey as in @hualet 's screenshot, and turning on transparency via **gsettings** works great.
So. no issue, I guess! :smile:

**Comment by arisskz6** [comment]
I met the same problem too,I tried many ways,and when I downgrading **deepin-metacity** from 3.22.10.1 to **3.22.8-1**,a miracle happened，the terminal become  transparent again,thanks  all guru here!

**Comment by Anderneath** [comment]
Try type [Super + Shift + Tab], it's a shortcut called Switch Window Effects. This solved the problem on my system. And if, after that, your Terminal keeps with a plain black background try to change the opacity.

**Comment by xiximitho** [comment]
Thanks @sonald , solved my problem.
