### ISSUE TITLE
使用crossover应用无法从备份数据中导入容器-在Ubuntu中使用正常

### ISSUE THREAD

**Issue by babyfengfjx** [linuxdeepin/developer-center#3164]
- 问题源帖信息：https://bbs.deepin.org/post/237109
 **问题内容描述：**
1. 我用crossover 21在deepin安装了一些win的软件，比如adobe illustrator。Crossover可以把这些安装的软件打包成 archive (export to archive)，这样方便今后恢复（restore archive)

2. 可我发现我的archive无法在deepin恢复（讽刺的是，这些deepin下创建的archives可以在ubuntu下恢复。。。）
3. 具体症状是，我在deepin下选择“import bottle archive"，然后选择archive，crossover没有任何反应。出现一个透明窗口。

4. 我联系了crossover的技术支持，他们建议用/opt/cxoffice/bin/cxfix --auto 检查是否哪个library missing。结果没什么问题。最后他们怀疑是deepin 这个distribution 缺了那些dependencies。

核心问题是该应用在Ubuntu中使用正常，deepin和UOS中无法正常使用，无法打开文件选择窗口。

**Comment by BLumia** [comment]
![image](https://user-images.githubusercontent.com/10095765/169009715-2ae9a4d0-fd25-4d63-a23f-6e40395f72a5.png)

问题应该是文件管理器的打开方式对话框哪里不对。临时 workaround 方案是先关掉这个开关。
