### ISSUE TITLE
DDE无密码用户相关问题 (no-password user)

### ISSUE THREAD

**Issue by foresee-io** [linuxdeepin/developer-center#3165]
### SUMMARY | 问题概要
运行 `sudo passwd --delete user` 使 `user` 变成无密码用户。

通过 tty 或终端 (terminal)， `user` 可以正常登录并使用 `sudo` 等需密码鉴权的功能；但在 DDE 中使用受到了多种阻碍。

**我知道这样做不安全**，测试后将撤销 `user` 的 `sudo` 权限。但这是客观存在的问题，下面列举一二。

### OBSERVED RESULT | 观察到的结果

1. 在登录界面，登录按钮点击之后没有反应。
2. 通过 LightDM 自动登录，可以进入 `user` 的图形界面。终端输入 `loginctl lock-session` ，会弹出通知“锁屏失败”。

### EXPECTED RESULT | 期望的结果

1. 至少要能确保无密码用户的登录。
2. 要支持无密码用户的锁屏，可能可以省电。
3. 问题 1、2 在 GNOME 3 不存在。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

架构：amd64 版本：apricot 疑似关键软件包版本：
dde-session-shell 5.5.14-1
dde-session-ui 5.5.10-1
dde-polkit-agent 5.5.7-1
**deepin-authenticate** 1.3.11-1 # 新增可疑

### ADDITIONAL INFORMATION | 额外补充

此处描述的“无密码用户”是通过 `sudo passwd --delete user` 创造的，并不是控制中心的“无密码登录”。

**我知道这样做不安全**，测试后将撤销 `user` 的 `sudo` 权限。

**Comment by tsic404** [comment]
deepin上删除用户的密码会被认为是禁用用户，deepin的无密码登陆是`nopasswdlogin`用户组，而不是用户没有密码。

**Comment by foresee-io** [comment]
该问题可能涉及多个组件，暂时搁置，待有空再梳理 **其他桌面环境** 对 Passwordless User 的支持度。
