### ISSUE TITLE
Multitasking View shows windows as black in the Desktop preview area

### ISSUE THREAD

**Issue by NjlsShade** [linuxdeepin/developer-center#3170]
### SUMMARY | 问题概要

When entering Multitasking View, the Windows I have open will appear black in the Desktop preview area.

### STEPS TO REPRODUCE | 复现步骤

1. Enter the MulltiTasking View and view the Desktop preview area
![Screenshot_20220520220143](https://user-images.githubusercontent.com/15788214/169632632-3a21c61f-9455-4b7a-90ca-3ee428825569.png)

### OBSERVED RESULT | 观察到的结果

Windows appear black.

### EXPECTED RESULT | 期望的结果

Window content

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Using the latest deepin 20.5 freshly installed and updated, with NVIDIA GeForce RTX 3060 (using proprietary drivers).

**Comment by BLumia** [comment]
I cannot reproduce this, guess it's probably a graphics driver related issue. Could you try using an open-source driver instead and see if that helps? You can also install `systemsettings` package and change the KWin backend there and see if that can fix this issue.

**Comment by NjlsShade** [comment]
It does look to be directly related to the NVIDIA closed source driver. Changing the compositor's renderer does not fix it, so I'll just wait and see if a future driver or KWin version resolves the issue.

Thanks!

**Comment by Octavian-Q** [comment]
I also dont have that issue on my 2 devices one is AMD gpu other intel integrated. so nvidia makes somewhere glitches

**Comment by NjlsShade** [comment]
The Multitasking View's functionality has changed in 20.6 and this issue is no longer relevant.

Updated Multitasking View seems to function as intended now with NVIDIA so this can be closed.
