### ISSUE TITLE
App Store does not use the system language on the App Update page

### ISSUE THREAD

**Issue by NjlsShade** [linuxdeepin/developer-center#3171]
### SUMMARY | 问题概要

The App Store does not seem to be using the correct system language when displaying app names on the App Update page.

### STEPS TO REPRODUCE | 复现步骤

1. With English as your set language, open the App Store and check for updates. If there are any they should be displayed in the wrong language
![Screenshot_20220520214923](https://user-images.githubusercontent.com/15788214/169632857-45ec0ca3-166b-4955-91c3-6187f4fc42f1.png)

### OBSERVED RESULT | 观察到的结果

App updates not displaying in the correct language

### EXPECTED RESULT | 期望的结果

To be displayed in the system set language

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Using the latest deepin 20.5 freshly installed and updated.

**Comment by babyfengfjx** [comment]
Thank you very much for your feedback, we will promote the application language adaptation update as soon as possible.

**Comment by NjlsShade** [comment]
Fresh install of Deepin 20.7.1 (App Store 7.5.2.0007) this issue is mostly resolved, however, it seems some apps are still not using the correct language, even on their own app page.

![Screenshot_20221119_235707](https://user-images.githubusercontent.com/15788214/202886395-c92c3ccb-0a4d-49c1-8cb5-b7062a7a1ad1.png)

![Screenshot_20221119_235817](https://user-images.githubusercontent.com/15788214/202886401-b6eb3cd4-44dd-4887-9b39-5b4f106bff3f.png)

**Comment by vivianxf** [comment]
pms同步处理关单，问题已修复
