### ISSUE TITLE
System update page visual issues

### ISSUE THREAD

**Issue by NjlsShade** [linuxdeepin/developer-center#3172]
### SUMMARY | 问题概要

When an update is available on the "Updates" page in Control Center there seems to be some text missplaced.

### STEPS TO REPRODUCE | 复现步骤

1. Check for updates using the Control Center, if there are updates there should be text misplaced on the page
![Screenshot_20220520213653](https://user-images.githubusercontent.com/15788214/169633031-7359e2e7-b89e-4ef5-81c5-e8a169fc8b0a.png)
![Screenshot_20220520213701](https://user-images.githubusercontent.com/15788214/169633033-78630e57-384f-42c3-a78f-15dd325fa416.png)

### OBSERVED RESULT | 观察到的结果

Text is displayed over an icon, seemingly incorrectly.

### EXPECTED RESULT | 期望的结果

Text should be properly isolated.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Using the latest deepin 20.5 freshly installed and updated.

### ADDITIONAL INFORMATION | 额外补充

The size of the Window does not seem to have any affect on the issue.

**Comment by Octavian-Q** [comment]
I also have that issue, besides, when a notification of update is shown, If I click on it, redirects to control center and shows "System is up to date" which is not and I have to check again for updates to install. 
![Screenshot_dde-control-center_20220515160627](https://user-images.githubusercontent.com/98664445/169645685-c40e49cf-e8a1-49b7-927a-39986ee7137f.png)

**Comment by babyfengfjx** [comment]
Thank you very much for your feedback, the problem we have confirmed and submitted to optimize .Any other questions, please also promptly feedback~

**Comment by NjlsShade** [comment]
Testing with deepin 20.7.1, this issue seems to be resolved.

**Comment by babyfengfjx** [comment]
nice!
