### ISSUE TITLE
WLAN Network could not be found Issue

### ISSUE THREAD

**Issue by Octavian-Q** [linuxdeepin/developer-center#3177]
### SUMMARY | 问题概要
When I want to connect to the phone hotspot, after inserting password which is correct, deepin shows after a short time "WLAN Network could not be found" notification and doesnt connect.

### STEPS TO REPRODUCE | 复现步骤

1.Turn on my laptop and it auto connects to a saved network
2. When I want to switch network for my hotspot or another wifi, I click on other network (password inserted earlier, system knows it)
3. Stays in "connecting" state for a while then says "WLAN Network could not be found" notification

### OBSERVED RESULT | 观察到的结果
Cant switch connection to my wifi hotspot or any other network while already connected to a wifi.
Video for more accurate explanation: https://youtu.be/7_-LZSOBPDM

### EXPECTED RESULT | 期望的结果
Be able to connect to my wifi hotspot and switch easily to another wifi network. 

### SOFTWARE/OS VERSIONS | 软件/系统版本信息
Deepin 20.5 all updates installed

### ADDITIONAL INFORMATION | 额外补充
Network wifi adapter: Marvell Technology Group 88W8897 [AVASTAR]

**Comment by justforlxz** [comment]
There are similar reports internally, it seems that there is a problem with the driver.

**Comment by babyfengfjx** [comment]
See if you can provide information about your NIC device and the output of lspci and lsusb; perhaps you can also try switching to another kernel: sudo apt install linux-image-deepin-stable-amd64 linux-headers-deepin-stable-amd64

**Comment by Octavian-Q** [comment]
> See if you can provide information about your NIC device and the output of lspci and lsusb; perhaps you can also try switching to another kernel: sudo apt install linux-image-deepin-stable-amd64 linux-headers-deepin-stable-amd64

I am running kernel 5.15 and I cant use 5.10 because system wont boot with it, also I kind of dont want to experiment with other more new kernels because is my work machine and needs to be stable. 
I provide info from the terminal, neofetch, lspci and lsusb
![Screenshot_deepin-terminal_20220510084845](https://user-images.githubusercontent.com/98664445/170471262-a2162b25-9471-4b6f-a159-0482abebb9dd.png)
![Screenshot_deepin-terminal_20220526133026](https://user-images.githubusercontent.com/98664445/170471357-2b8e40ae-566d-48a1-af96-4f46c9f0e666.png)
![Screenshot_deepin-terminal_20220526133115](https://user-images.githubusercontent.com/98664445/170471378-e015bd9a-9d52-4bed-a981-87e7504963cc.png)

**Comment by babyfengfjx** [comment]
I wonder if the 5.18 kernel will fix this in the new V20.8 release?
