### ISSUE TITLE
deepin-system-monitor Chinese only

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/developer-center#318]
Not sure if this is a bug of the Archlinux package, or a bug at all or maybe just an unfinished application.
In any case the new **deepin-file-manager** for me shows in Chinese in an English environment... 😉

**Comment by oberon2007** [comment]
I just noticed that the package doesn't even have a .desktop file - so can only be launched from the terminal and isn't visible in the launcher :wink - I guess it's just still experimental?

**Comment by hualet** [comment]
@zccrs @manateelazycat

**Comment by JulianLai** [comment]
@hualet The font size is really small, too.

**Comment by manateelazycat** [comment]
This issue has fixed after deepin-system-monitor 1.0 release.
