### ISSUE TITLE
不能完全卸载

### ISSUE THREAD

**Issue by gongyeheyu** [linuxdeepin/developer-center#3180]
我已经卸载了deepin,也关闭了wsl,但是它还在我的终端里

**Comment by BLumia** [comment]
...? 我没看懂你指的是不能完全卸载什么。如果您跳过了我们的 issue 模板，起码提供点具体信息呀，是 deepin WSL？

**Comment by BLumia** [comment]
长期未提供进一步信息，无法处理，先予以关闭。如果仍然有问题的话，麻烦开个新的 issue 哈~
