### ISSUE TITLE
Disk Utility infinitely loading when attempting to mount BitLocker

### ISSUE THREAD

**Issue by NjlsShade** [linuxdeepin/developer-center#3185]
### SUMMARY | 问题概要

When attempting to mount a BitLocker encrypted drive via Disk Utility it will bring up a loading dialog that loops until it appears to time out (about 2-3 minutes). Nothing is logged to stdout, maybe it's waiting for a password without a proper prompt, or just does not know how to handle a BitLocker drive.

### STEPS TO REPRODUCE | 复现步骤

1. Open Disk Utility and attempt to mount a BitLocker encrypted partition

![Screenshot_select-area_20220526230012](https://user-images.githubusercontent.com/15788214/170621413-747425fd-c258-4410-975b-9f7866945b71.png)

### OBSERVED RESULT | 观察到的结果

A dialog will appear, then stay until it times out a few minutes later.

### EXPECTED RESULT | 期望的结果

Either indicate it does not know how to handle this type of filesystem, or request the encryption key and mount the drive.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Using the latest deepin 20.5. Disk Utility 1.3.3.

### ADDITIONAL INFORMATION | 额外补充

The File Manager can mount BitLocker drives properly, so I feel the Disk Utility should also be able to do so.

**Comment by BLumia** [comment]
I'm not sure about BitLocker support, @babyfengfjx could you take a look if it's a bug or currently unsupported type? Thanks!

**Comment by xuqi27837288** [comment]
@BLumia hello,Your system disk how to install, manual installation, complete encryption installation, complete installation, we want to know the installation of the environment, you send this version does not support logical volume, encryption disk

**Comment by xuqi27837288** [comment]
See the phenomenon, the system disk should be fully encrypted installation, (fully encrypted words implementation logic seems to create logical volume after the creation of encrypted partition)

**Comment by xuqi27837288** [comment]
![企业微信截图_16552836431880](https://user-images.githubusercontent.com/62528742/173788309-20f4d016-aeb7-4d31-92e4-864dce214aa5.png)

**Comment by BLumia** [comment]
> @BLumia hello,Your system disk how to install, manual installation, complete encryption installation, complete installation, we want to know the installation of the environment, you send this version does not support logical volume, encryption disk

You may want to ask @NjlsShade, but as far as I understand, they are have trouble with Windows BitLocker support instead of encryption method offered by deepin installer.

**Comment by xuqi27837288** [comment]
The problem has been reported back to the R&D staff

**Comment by babyfengfjx** [comment]
@xuqi27837288  请在V23版本复现下该问题，如果存在请继续跟踪。

**Comment by xuqi27837288** [comment]
![截图_deepin-diskmanager_20230615102548](https://github.com/linuxdeepin/developer-center/assets/62528742/65dc77ba-863b-4869-9ed9-70e8ad68665b)

复现及分析情况:
windows开启bitlocker加密后,v23上磁盘管理器中可以加载该磁盘,但无法显示磁盘相关的数据使用情况和剩余情况,
在文件管理器访问该加密磁盘输入正确的恢复秘钥后该磁盘可以正常访问
结论:
目前该问题在v23初步判定暂无异常
