### ISSUE TITLE
Screen Capture MKV and MP4 producing corrupt video data

### ISSUE THREAD

**Issue by NjlsShade** [linuxdeepin/developer-center#3186]
### SUMMARY | 问题概要

When capturing a screen recording of mostly static content as MP4 or MKV the resulting video file does not play properly and is missing data in the first ~15 seconds of play.

### STEPS TO REPRODUCE | 复现步骤

1. Record a mostly static area (an opaque terminal window for example) using Screen Capture's MP4 or MKV option, then watch the resulting video.

### OBSERVED RESULT | 观察到的结果

Below is a video I captured of me typing the numbers 1 through 28 ~1 second apart. You can see the video is missing data and does not play properly. After about 15 seconds it seems to play normally.

https://user-images.githubusercontent.com/15788214/170631417-a5a599cf-288e-47c4-ba67-0b79348b4e2d.mp4

When recording the same action alongside dynamic content it seems to function correctly with just a second long stutter. I think the compression you're using may be too aggressive with reusing information (I only count to 9 here as more is not needed).

https://user-images.githubusercontent.com/15788214/170629662-2050671c-ceda-4cff-942e-3526190a9b84.mp4

### EXPECTED RESULT | 期望的结果

The produced video should be reliably captured and played without issue.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Using the latest deepin 20.5. Screen Recorder 5.10.15-1.

### ADDITIONAL INFORMATION | 额外补充

When trying to remux a video recorded with Screen Capture using Avidemux it fails with an error that the timestamps are incorrect, so maybe there is more of an issue than compression?

![Screenshot_avidemux3_qt5_20220527005446](https://user-images.githubusercontent.com/15788214/170631985-12888fd8-fce2-4dc5-882d-b5701c571193.png)

**Comment by NjlsShade** [comment]
When testing some more, even with dynamic content there is still an issue in the first few seconds of playback that can range in length, however, is not as bad as static content still.

**Comment by babyfengfjx** [comment]
In subsequent versions, we have not found similar problems after continuous observation. I wonder whether your problem has been solved in the latest version.

**Comment by babyfengfjx** [comment]
Not sure if the problem exists in the latest version, if there is still a similar problem in the new version, you are welcome to activate the issue, the current issue we first closed.
