### ISSUE TITLE
Multitasking View does not add windows opened externally.

### ISSUE THREAD

**Issue by NjlsShade** [linuxdeepin/developer-center#3187]
### SUMMARY | 问题概要

If an application window spawns while you are in the Multitasking View it is not added to the collection of windows displayed.

### STEPS TO REPRODUCE | 复现步骤

1. Be in Multitasking View while a window is loaded after you entered.

### OBSERVED RESULT | 观察到的结果

In the video below I artificially cause this situation to occur by opening GIMP, then quickly entering Multitasking View with "Ctrl+S" before the window loads. Note that I have run into this issue myself naturally through my workflow, as Unity tends to open and close a lot of windows.

https://user-images.githubusercontent.com/15788214/170634820-5dfceef9-353e-4673-bdfb-5fb520d7cbb9.mp4

### EXPECTED RESULT | 期望的结果

The windows displayed in Multitasking view should be updated in real-time to capture any windows removed or added externally.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Using the latest deepin 20.5.

### ADDITIONAL INFORMATION | 额外补充

Obviously if this is too resource-intensive or something that is one thing, but I've seen other window managers do it so I feel like it's a bug or oversight rather than a performance concern.

**Comment by BLumia** [comment]
@justforlxz could you take a look? Thanks!

**Comment by justforlxz** [comment]
It does not appear to update the data when the number of windows changes.

**Comment by NjlsShade** [comment]
Testing with deepin 20.7.1 this issue looks to be resolved.
