### ISSUE TITLE
Deepin Movie incorrect volume level indication

### ISSUE THREAD

**Issue by NjlsShade** [linuxdeepin/developer-center#3189]
### SUMMARY | 问题概要

There are two issues here. First, when deepin Movie's volume is set to 100% it only outputs at ~50% system volume level, and when set to 200% via the scroll wheel it outputs at 100% system volume.

Second, the only way to raise the volume above 100% is by using the mouse scroll wheel. While this is clever, it can be inconvenient to users who only use the scroll wheel to change audio settings and don't want it to exceed 100%.

### STEPS TO REPRODUCE | 复现步骤

Play a video with sound using a video player such as VLC or Chrome at 100% volume, you will notice that when compared Deepin Movie's 100% volume setting is only about half that of any other video player, however, Deepin Movie's 200% volume is the same as any other players 100% volume.

### OBSERVED RESULT | 观察到的结果

Deepin Movie's volume slider seems to only go from 0% to 100% system volume, despite its reported range being referred to as 0% to 200%.

https://user-images.githubusercontent.com/15788214/170804404-c99fd82c-784b-43bc-a11d-aa85652954d6.mp4

### EXPECTED RESULT | 期望的结果

100% audio in Deepin Movie should be 100% of the system's currently set audio level, and the ability to increase the audio past 100% should be a toggle in Movie's settings and adjustable not only using the scroll wheel but also the GUI slider.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Using the latest deepin 20.5. Deepin Movie 5.10.1.

### ADDITIONAL INFORMATION | 额外补充

This is the same as [2443](https://github.com/linuxdeepin/developer-center/issues/2443), that issue just did not have enough information regarding the problem.

Also, for future reference would you prefer that I had replied to the existing issue with my updated findings, or that I open a new issue like this to properly exclaim the problem as I understand it, then link to the old issue as I did here?

**Comment by BLumia** [comment]
I'm not familiar with the deepin-movie implementation so I'll assign our QA people and see if it's a bug that needs to be fixed :)

> Also, for future reference would you prefer that I had replied to the existing issue with my updated findings, or that I open a new issue like this to properly exclaim the problem as I understand it, then link to the old issue as I did here?

Personally, I suggest you open a new issue if you believe your issue is different from the existing one, or the existing one is already closed/stalled. You can still choose the way you want to do the feedback though. We can help with triage issues and close the duplicated one when needed.

**Comment by NjlsShade** [comment]
Testing with deepin 20.7.1 this issue looks to be resolved

**Comment by BLumia** [comment]
Thx for the info! I'll close this one for now. Feel free to create a new one if anyone get similar issue :)
