### ISSUE TITLE
Deepin File Manager more verbose handling of large selections

### ISSUE THREAD

**Issue by NjlsShade** [linuxdeepin/developer-center#3192]
### SUMMARY | 问题概要

If you select many files at once in the File Manager, then right-click on them to display the context menu it can take a long time to display said menu and it is not clear that the menu is loading at all.

The File Manager should be more verbose when performing small tasks such as selecting all files, or opening context menus. In most cases, these tasks complete fast and a loading indicator is not really needed, but in some situations it needs to be displayed for a more intuitive and fluid UX experience.

### STEPS TO REPRODUCE | 复现步骤

1. Create a folder with around 10,000 files in it (this may vary based on hardware, as I'm not sure how much of it is performance vs optimization based). File sizes should not matter, however, for referencing the files I tested with were all smaller than 30KB.
2. Select all files in said folder via the context menu or key shortcut, then click on Properties.

### OBSERVED RESULT | 观察到的结果

Both the act of selecting all files and opening their context menu causes a large delay where the file manager seems unresponsive.

Here there is no status bar message and the File Manager locks up, preventing use and not intuitively letting you know it's working on your request (It's hard to see in my video exactly when I right-click or press Ctrl+A to select all files, but given how long it takes for these actions to actually process you can infer an approximation):

https://user-images.githubusercontent.com/15788214/170807066-4cfd9f6c-e0fb-462f-9573-275cfdb15728.mp4

### EXPECTED RESULT | 期望的结果

Just as opening a folder with a large file count displays a loading message in the file manager's bottom status bar, so too should selecting large counts of files and opening context menus for them.

In the case of loading a folder with a large number of files, as opposed to freezing up, a status bar is shown with the message "Loading..." and the user is free to cancel the operation by navigating away:

https://user-images.githubusercontent.com/15788214/170806859-10087872-cbaf-42bd-9e74-27bb2770a3fd.mp4

When right-clicking on files or selecting all files, a similar message should display stating "Selecting files..." or "Loading Properties..." or just "Loading..."

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Using the latest deepin 20.5. File Manager 5.5.10.

**Comment by BLumia** [comment]
@babyfengfjx might need to take a look

**Comment by SuperEffie** [comment]
Thank you for your feedback, the problem you raised was reproduced. The developers are now locating and resolving the issue.And it may take some time. We'll let you know here after we fix the issue. We look forward to more feedback from you!

**Comment by SuperEffie** [comment]
We will track this issue on the PMS platform, and we will currently close the issue regarding version v20.9. If you encounter any issues during the use of v23beta,welcome to give us feedback.
The link of pms is https://pms.uniontech.com/bug-view-184821.html
