### ISSUE TITLE
OCR consistency

### ISSUE THREAD

**Issue by NjlsShade** [linuxdeepin/developer-center#3199]
### SUMMARY | 问题概要

When using the OCR tool I find that it often has issues extracting text from very simple image targets, and will instead output seemingly random text like "ME LEE Raa".

### OBSERVED RESULT | 观察到的结果

I made a very simple target image by just typing sample text into deepin Text Editor and the following was the result of OCR:
![Screenshot_deepin-ocr_20220529224937](https://user-images.githubusercontent.com/15788214/170909195-bcbf21e7-d976-4689-95c2-0d0699ae7c4a.png)
![Screenshot_deepin-ocr_20220529225137](https://user-images.githubusercontent.com/15788214/170909201-6d466626-e1fe-41b7-ac1d-5d7a4e3cab76.png)

Here is some text grabbed from elsewhere and the issue still occures:
![Screenshot_deepin-ocr_20220529225240](https://user-images.githubusercontent.com/15788214/170909256-3cf7e884-ab44-401f-af5a-5c2442c9b14f.png)
![Screenshot_deepin-ocr_20220529225416](https://user-images.githubusercontent.com/15788214/170909302-3f564118-0f8a-4c0b-af39-e33d0c4433e7.png)
![Screenshot_deepin-ocr_20220529225507](https://user-images.githubusercontent.com/15788214/170909315-585f78cd-425c-4319-9ddf-38c6f2234724.png)

### EXPECTED RESULT | 期望的结果

Text extraction should be more consistent, this seems like more of a bug than just a bad OCR engine.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Using the latest deepin 20.5.

**Comment by wzyforgit** [comment]
Well, first of all, you must change your system language to Simplify Chinese to enable Simplify Chinese recognition, unfortunately,  this is a feature, not a bug. We will improve this feature in future.

And we use a new OCR engine in Deepin 20.6, you can try it.

**Comment by NjlsShade** [comment]
> Well, first of all, you must change your system language to Simplify Chinese to enable Simplify Chinese recognition, unfortunately, this is a feature, not a bug. We will improve this feature in future.
> 
> And we use a new OCR engine in Deepin 20.6, you can try it.

I was targeting English in the above images, but I'd expect the one image that contains simplified Chinese to have those characters ignored, as it would with any other unreconised markings.

Tested with the new deepin 20.6 and the issue of random strings appearing like "ME LEE Raa" seems to be resolved, however, it still struggles with simple tasks:
![Screenshot_deepin-ocr_20220530211826](https://user-images.githubusercontent.com/15788214/171074358-2470862d-b434-426b-83f7-df23d7f76106.png)

I assume it works better with other languages, It maybe is just a shortcoming with English specifically for the engines you're using. It's a very cool feature as I use Google Keep to do OCR all the time which can be a hassle having to upload images every time I need text extracted. Hope it can be improved in the future.

**Comment by wzyforgit** [comment]
> > Well, first of all, you must change your system language to Simplify Chinese to enable Simplify Chinese recognition, unfortunately, this is a feature, not a bug. We will improve this feature in future.
> > And we use a new OCR engine in Deepin 20.6, you can try it.
> 
> I was targeting English in the above images, but I'd expect the one image that contains simplified Chinese to have those characters ignored, as it would with any other unreconised markings.
> 
> Tested with the new deepin 20.6 and the issue of random strings appearing like "ME LEE Raa" seems to be resolved, however, it still struggles with simple tasks: ![Screenshot_deepin-ocr_20220530211826](https://user-images.githubusercontent.com/15788214/171074358-2470862d-b434-426b-83f7-df23d7f76106.png)
> 
> I assume it works better with other languages, It maybe is just a shortcoming with English specifically for the engines you're using. It's a very cool feature as I use Google Keep to do OCR all the time which can be a hassle having to upload images every time I need text extracted. Hope it can be improved in the future.


![截图录屏_deepin-ocr_20220531093530](https://user-images.githubusercontent.com/15171004/171075853-46a88943-3c5b-4475-bdc8-1f75caea0840.png)

It's seems that our text detect algorithm have some bugs, it cannot process large space between characters.
We will plan to improve it, thanks for your report.

**Comment by xuqi27837288** [comment]
We will plan to improve it, thanks for your report~
