### ISSUE TITLE
Qt开发库完善

### ISSUE THREAD

**Issue by Iceyer** [linuxdeepin/developer-center#32]
初步的讨论结果是将Qt/C++中比较基础的库丢到Dtk这个公共库中去。最开始的模块会有：
**Dtk::Widget **-> 原DUI库，DUI的namespace改名位Dtk
**Dtk::Logger** -> 对cutelogger封装

源码管理上：
girrit/github创建libdtk的仓库,统一管理所有的模块代码

仓库打包时每个不同模块都生成不同的package, 如上面两个模块会生成
libdtkwidget-1.1/libdtkwidget-1.1-dev 
libdtklogger-1.1/libdtklogger-1.1-dev
可以提供一个libdtk-1.1/libdtk-1.1-dev的虚包来安装所有的依赖。

@fasheng @leaeasy @sbwtw @dragondjf @kosl90

**Comment by fasheng** [comment]
那原 libdui 如何处理，直接丢掉？

**Comment by Iceyer** [comment]
會變成 libdtkwidget-1.1/libdtkwidget-1.1-dev ，只是該一下namespace和包名，源碼會保留下來。
libdui這個包名稱的確會丟掉，被替換成為 libdtkwidget

**Comment by Iceyer** [comment]
@dragondjf
今天封装了一下cutelooger，应用的改动应该比较小，你可以看看：
https://github.com/deepin-tool-kit
https://github.com/deepin-tool-kit/dlog
https://github.com/deepin-tool-kit/dtk-example/blob/master/dlog-example/
没啥大问题旧推送到gerrit上进行打包了

**Comment by Match-Yang** [comment]
cutelooger是支持QML的log的，不知道你加了没有

**Comment by Iceyer** [comment]
@Match-Yang 没有诶，这个艰巨的任务交给你 :smile:

**Comment by Match-Yang** [comment]
那后面改吧，现在没项目用到呢

**Comment by hualet** [comment]
@Iceyer 我真建议不要丢掉libdui搞新的，分模块拆包都在原项目上进行过度，namespace如果是按照我之前的要求不直接写死namespace到DUI而是用DUI_USE_NAMESPACE的话，以后就算换也是很方便的，新代码也可以这样用。至于dui还是dtk我个人觉得很无所谓。

**Comment by Iceyer** [comment]
@hualet 并没有搞新的，libdtkwidget和libdui的区别仅仅是namespace做了修改而已

**Comment by hualet** [comment]
我知道啊，就是因为目前只是 库名称 和 namespace的区别，所以才说不要做一个新的项目出来。因为怎么去分模块，怎么去拆包我们连试都没有试过，新项目遇到新的问题再建一个新项目么？我倾向于在libdui上试验一下

**Comment by Iceyer** [comment]
再libdui上如何试验？libdui本来就没什么需要改动的地方了， 其他新项目需要的很多东西都和ui无关，都不可能向liudui的仓库提交代码。

**Comment by hualet** [comment]
我晕，你还纠结这个名字啊。。。我们不是deepin user interface，我们是deepin universal interface :trollface:

**Comment by Iceyer** [comment]
@hualet 要么把libdtkwidget->改成libduiwidget， 要不把libdui的仓库名称改成libdtk，实在不清楚一定要留着libdui的包有什么意义。

**Comment by fasheng** [comment]
目前上游 deepin-tool-kit(libdtkbase, libdtkwidget) 已经替代 libdui 了吧?
@hualet @Iceyer 
@felixonmars

**Comment by Iceyer** [comment]
@fasheng 就 dde-control-center替换完了，其他的还在处理，估计要等@swb回来才能处理完。

**Comment by fasheng** [comment]
好的，记得把 README 里的依赖也做下调整～

**Comment by Iceyer** [comment]
需要替换的项目列表
- [ ] dde-dock
- [ ] dde-desktop
- [ ] dde-session-ui
- [ ] dde-control-center
