### ISSUE TITLE
deepin-image-viewer has a memory leak when switching images

### ISSUE THREAD

**Issue by kt286** [linuxdeepin/developer-center#3206]
### SUMMARY | 问题概要

deepin-image-viewer has a memory leak when switching images

### STEPS TO REPRODUCE | 复现步骤

1. into ~/Pictures/Wallpapers/
2. open a picture
3. switch picture use → key

### OBSERVED RESULT | 观察到的结果

![image](https://user-images.githubusercontent.com/10684972/171313208-d529934b-c6dc-4996-a703-d02c4ae9554c.png)

### EXPECTED RESULT | 期望的结果

deepin-image-viewer uses a small amount of memory when switching images

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin 20.6
deepin-image-viewer      5.9.1-1

**Comment by xuqi27837288** [comment]
#deepin-image-viewer 切换图片时内存泄漏

@kt286 This problem has been confirmed and submitted for optimization. Thank you for your feedback. If you have any other questions, please feel free to feedback~
