### ISSUE TITLE
文件管理器 “计算机” 页面渲染问题

### ISSUE THREAD

**Issue by wootifer** [linuxdeepin/developer-center#3209]
### SUMMARY | 问题概要

在文件管理器 “计算机” 页面，用鼠标拖动右下角改变窗口大小，窗口跟随变化反应迟钝，文件管理器的其他界面渲染是正常。

### STEPS TO REPRODUCE | 复现步骤
演示视频见下面的链接
https://github.com/wootifer/test/blob/master/%E5%BD%95%E5%B1%8F_dde-desktop_20220524223618.gif
https://github.com/wootifer/test/blob/master/%E5%BD%95%E5%B1%8F_dde-desktop_20220601203152.gif

### SOFTWARE/OS VERSIONS | 软件/系统版本信息
![image](https://user-images.githubusercontent.com/26326251/171419965-af9f0125-49df-4468-a2de-cd724d189ab2.png)

**Comment by luodeepin** [comment]
Thank you for your feedback,he problem has been confirmed to exist in the deepin V20.6 version,it has been forwarded to the related development team, and you will be notified here after it get fixed!

**Comment by luodeepin** [comment]
Hello!
On three machines, we have been able to change the size of the window by dragging the bottom right corner with the mouse on the File Manager "Computer" page without any slow response.
What is the model number of the machine you are currently using?

**Comment by myml** [comment]
> Hello! On three machines, we have been able to change the size of the window by dragging the bottom right corner with the mouse on the File Manager "Computer" page without any slow response. What is the model number of the machine you are currently using?


![image](https://user-images.githubusercontent.com/13045857/173982032-7adad90d-04d2-4b90-b893-b700fed92e2b.png)

You can compare ‘computers page’ and ‘home page’, 'computers page' is A little slow repsonse when dragging and cpu will also be higher.

**Comment by luodeepin** [comment]
你好！
请问在 deepin 20.8 最新版本中，你是否还有此问题？

**Comment by luodeepin** [comment]
回归镜像：https://cdimage.deepin.com/releases/20.8/deepin-desktop-community-20.8-amd64.iso
回归版本：文件管理器 5.8.3
回归步骤：用户描述的步骤
回归结论：通过
![录屏_选择区域_20230310094259](https://user-images.githubusercontent.com/96416089/224202070-80f58892-e19a-4e26-a27f-2d91ff11a9e7.gif)

在开启窗口特效和关闭窗口特效两种情况下，均未出现这个问题。
用户也长时间没有确认是否现阶段用户环境是否还存在这个问题，当前先做关闭处理
