### ISSUE TITLE
Effects crash/turn off on 'move window'

### ISSUE THREAD

**Issue by IgnusG** [linuxdeepin/developer-center#321]
I'm running Deepin Desktop Environment on Arch and sometimes when I try to 'move a window' into another workspace, the effects turn off - same as when I turn them off manually via the keyboard shortcut but they can't be turned on again.
 
Result is no animations, black dock and background. 

**Update**
After restart I now have a black strip at the bottom...
**Atnoher Update**
Black bar is gone after another restart - probably just a fluke

#### Specs
Linux 4.11.7-1-ARCH
Deepin-WM (Not sure which package is relevant) 1.9.14-1

*Other than that - pretty amazing DE*

**Comment by hualet** [comment]
@sonald

**Comment by IgnusG** [comment]
Closing down as I can't reproduce it again. Might have been just a glitch

**Comment by sonald** [comment]
Let me know if you experience again.
