### ISSUE TITLE
自定义壁纸

### ISSUE THREAD

**Issue by lcc-666** [linuxdeepin/developer-center#3213]
我删除了deepin存放壁纸的文件夹，然后利用软链接的方式将其链接到我的壁纸文件夹

![截图_选择区域_20220602145913](https://user-images.githubusercontent.com/81516638/171571762-e870ddf9-753e-4d69-a332-85ee45ec38d9.png)
在我的壁纸较少是可以正常使用，但是当壁纸较多是就会在每次开机时出现白屏等待

![截图_选择区域_20220602150132](https://user-images.githubusercontent.com/81516638/171572176-ab2747ac-f3fd-4ca5-bcc7-7ffcca78b36e.png)

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/developer-center/issues/3095 可能相关？

**Comment by babyfengfjx** [comment]
> #3095 可能相关？

这个应该不相关，这个是用户老铁使用了近2W张壁纸，可能系统性能拉不起来，我们先让人分析看看。

**Comment by xuqi27837288** [comment]
系统性能支持此部分比较吃力~
