### ISSUE TITLE
Missing dependencies Deepin v23 Nightly

### ISSUE THREAD

**Issue by Octavian-Q** [linuxdeepin/developer-center#3214]
### SUMMARY | 问题概要
I cant install almost any app form store or outside download .deb file because of broken dependencies. This applies to discord, steam, microsoft teams, etc.

### STEPS TO REPRODUCE | 复现步骤

1. I open the Deepin App Store and want to install an app, discord for example 
2. It shows error that dependencies are broken
![Screenshot_dde-desktop_20220602145322](https://user-images.githubusercontent.com/98664445/171624430-f55f32c9-fdfe-48f3-b3ac-5bac4d95ac06.png)

4. I want to download .deb file, same app. Dependencies broken too
![Screenshot_deepin-deb-installer_20220602145505](https://user-images.githubusercontent.com/98664445/171624384-b61f316b-3995-4887-97be-caa05bfc900d.png)

### OBSERVED RESULT | 观察到的结果

Lack of dependencies, we will solve as soon as possible is the message shown

### EXPECTED RESULT | 期望的结果

Being able to install any app from the store or package .deb without any issues

### SOFTWARE/OS VERSIONS | 软件/系统版本信息
Deepin V23 Nightly 

### ADDITIONAL INFORMATION | 额外补充
As a suggestion is to update Discord app from the Store. It is like from years ago being with year 2020 latest package update date

**Comment by BLumia** [comment]
Could you test if it also happens in the v20 stable release? Since the v23 nightly version is meant to be unstable and we strongly not recommend use it in production.
