### ISSUE TITLE
Pamac 10.4 causing crash when searching for conflicts between applications in ArchLinux DDE 20.2

### ISSUE THREAD

**Issue by serial02** [linuxdeepin/developer-center#3219]
Hello everybody

 When choosing an application to install via pamac, the installation is crashing when there is a conflict between packages.

![Screenshot_archlinuxdde220601_2022-06-03_20:07:21](https://user-images.githubusercontent.com/32621790/171966283-82c0d535-fd31-4acd-b6ff-093a9b0fb8c1.png)

After disabling installation and checking for updates, pamac behaves normally but does not install anything.

![Screenshot_archlinuxdde220601_2022-06-03_20:13:19](https://user-images.githubusercontent.com/32621790/171966393-1cf5b09b-bb82-4100-92a3-6e6bc57b5114.png)

After the above occurrence and when we try to use the terminal to check for updates or install the same package, the following error message appears:

```
sudo pacman -Syu
 Error: Failed to sync all databases (database could not be locked)
 yay-syu
 /var/lib/pacman/db.lck is present.
```

Which denotes that when closing pamac the execution/verification process remains stuck.

![Screenshot_archlinuxdde220601_2022-06-03_20:14:44](https://user-images.githubusercontent.com/32621790/171966613-dcaa2754-3001-4fa1-a84d-cffd843d9164.png)

You have to (terminate the process) and remove with sudo rm -rf /var/lib/pacman/db.lck and access is released again.
 After removal it is possible to install the application normally.

![Screenshot_archlinuxdde220601_2022-06-03_20:17:20](https://user-images.githubusercontent.com/32621790/171966611-8bc33d0d-c99e-4d7b-9ebb-3d09f86c9e57.png)

I hope the log below can indicate what is causing pamac to crash on ArchLinux with DDE 20.2.

[Log DDE 20.2 Archlinux -journalctl -p 3 --no-pager](https://pastebin.com/wBeiN25j)

Note: I installed pamac via yay -S pamac-aur and use yay for most installations, along with sudo pamac -S package_name via terminal.

**Comment by BLumia** [comment]
Hi, pamac is not a project from the deepin team, nor a package offered by Arch Linux (you probably installed it from AUR). You may want to report the related issue to upstream developer, pamac is developed for Manjaro btw.

**Comment by serial02** [comment]
> Hi, pamac is not a project from the deepin team, nor a package offered by Arch Linux (you probably installed it from AUR). You may want to report the related issue to upstream developer, pamac is developed for Manjaro btw.

Thanks for the feedback!
 Team responsible for pamac already informed about this incident.

https://aur.archlinux.org/packages/pamac-aur#comment-868014
