### ISSUE TITLE
Feature request: Shortcut to move window to other output doesn't have an animation

### ISSUE THREAD

**Issue by IgnusG** [linuxdeepin/developer-center#322]
The action of moving windows across outputs doesn't have an animation associated with it.

**Comment by IgnusG** [comment]
Found the shortcuts in `/com/deepin/wrap/gnome/desktop/wm/keybindings/`. Just wanted to point out it doesn't have an animation - so that's what I'm pointing this issue to

**Comment by sonald** [comment]
I'm afraid it's up to the mutter. If gnome3 can do that, then there's no problem of implementing this. plus, what kind of animation do you expect, sliding across the monitors ? it's really weird in my opinion.

**Comment by IgnusG** [comment]
@sonald No rush. My original issue was actually in not being able to assign a shortcut to this action in deepin settings (this should be implemented) - but I found it in dconf. I'm not sure what animation would be best as I too think a sliding animation looks kinda weird (compiz did it). 

Maybe close on one monitor - open on other animation (*Food for thought*)?

**Comment by sonald** [comment]
Leave this opened for now, Gonna think about it later when I got time.

**Comment by logol** [comment]
:+1:
