### ISSUE TITLE
When opening the Control Center and clicking on System Information the window closes automatically

### ISSUE THREAD

**Issue by serial02** [linuxdeepin/developer-center#3220]
Hello everybody

 Using ArchLinux with DDE 20.2 installed by Archinstall 220601, it has been verified that opening the Control Center and clicking on System Information the window ( Control Center ) closes automatically without opening the contents. 

 This fact can be seen in the image below:

https://user-images.githubusercontent.com/32621790/171968669-cd9faf4e-6c97-48f6-abba-10bbe24f2184.mp4

Follow the log below to verify the reason why this window has this strange behavior.

[Log DDE 20.2 Archlinux -journalctl -p 3 --no-pager](https://pastebin.com/wBeiN25j)

**Comment by BLumia** [comment]
It's a known issue. Please track this issue in https://github.com/linuxdeepin/developer-center/issues/2716.

Since you are testing DDE with Arch Linux, you may also see other known issues [here](https://github.com/orgs/linuxdeepin/projects/12/views/1).
