### ISSUE TITLE
Custom display profile doesn't preserve primary screen setting

### ISSUE THREAD

**Issue by IgnusG** [linuxdeepin/developer-center#323]
### Current behavior
When changing display profiles, changing to pre-defined ones (extend ...) and then back doesn't keep the primary monitor setting.

### Expected behavior
Marking a monitor as primary and saving this display configuration results in the monitor being selected as primary if you change to this configuration later in the future.

#### Specs
Arch Linux Distribution
Deepin Desktop Environment

**Comment by jouyouyun** [comment]
Please  exec `journalctl  -f /usr/bin/startdde > /tmp/dde.log`,  then change display profiles, if problem occured, upload the file `/tmp/dde.log`, thanks!
