### ISSUE TITLE
wiki页面渲染错误

### ISSUE THREAD

**Issue by Rabenda** [linuxdeepin/developer-center#3234]
### SUMMARY | 问题概要

https://wiki.deepin.org/zh/Deepin%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/Deepin%E9%85%8D%E7%BD%AEtrojan%E5%AE%A2%E6%88%B7%E7%AB%AF
渲染错误

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/wiki.deepin.org/blob/85d8b57f056e85341050637f9453c0ad029cd964/Deepin%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/Deepin%E9%85%8D%E7%BD%AEtrojan%E5%AE%A2%E6%88%B7%E7%AB%AF.md

页面渲染没问题，原文的 markdown 标记有问题吧，内容的话应该可以直接登录上改或者发 PR 改上面的原文。

另外有兴趣的话可以看下 Wiki 相关的活动（帖子在 https://bbs.deepin.org/post/235494 这里）。Wiki 相关事宜是由 Wiki 兴趣组那边推进的。

**Comment by myml** [comment]
谢谢反馈，我先改了markdown https://github.com/linuxdeepin/wiki.deepin.org/pull/5
