### ISSUE TITLE
Steam games don't work in Deepin 

### ISSUE THREAD

**Issue by Octavian-Q** [linuxdeepin/developer-center#3237]
Steam games don't run in Steam on Deepin. I set the proton compatibility from settings, even tested multiple version and games crash or wont launch. Both DirectX and Vulkan games are affected

### STEPS TO REPRODUCE | 复现步骤

1. Downloaded Steam from App Store
2. Launched it and enabled proton to play with compatibility layer 
![Screenshot_Steam_20220609161933](https://user-images.githubusercontent.com/98664445/172862522-5e1f8eba-6a8a-4165-97e6-5529331b6096.png)
3. Downloaded a game, for example Call of duty modern warfare remastered
4. Launch the game, and it stays like that for few seconds then closes by itself without any message (thats a directX game)
5. Shadow of the tomb raider is a vulkan game, also doesnt work but gives an error 
![Screenshot_select-area_20220609164239](https://user-images.githubusercontent.com/98664445/172863058-31ab1127-86a6-4b9a-8cda-1b5abc520468.png)

### OBSERVED RESULT | 观察到的结果

Games don't run on deepin from the steam.

### EXPECTED RESULT | 期望的结果
Games work normally (same as on other distros)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息
Deepin 20.6 steam from appstore all updates installed

### ADDITIONAL INFORMATION | 额外补充
Steam also doesnt respect scaling of 125% I set in settings 
![Screenshot_Steam_20220609161944](https://user-images.githubusercontent.com/98664445/172863601-e3e46e4b-8b11-4c37-8610-5adc8c96958c.png)

**Comment by BLumia** [comment]
If possible, please consider providing a related error log, but just a FYI, since both the game and steam itself are not open-sourced, I'm not really sure if we can offer too much help :/

**Comment by BLumia** [comment]
btw, according to the screenshot you provided, it's probably a graphics driver issue, you may want to checkout https://steamcommunity.com/app/391220/discussions/0/3288067088114419099/

**Comment by Octavian-Q** [comment]
I researched a bit by myself, and found kind of a fix. Installed Vulkan shaders and mesa drivers, and libraries coming with them, was a bit tricky to restart the drivers and make it work. Maybe worth for the future including mesa drivers and Vulkan shaders as an option on welcome screen as an option:)
