### ISSUE TITLE
Biometric Authentication Issues

### ISSUE THREAD

**Issue by Octavian-Q** [linuxdeepin/developer-center#3247]
### SUMMARY | 问题概要

When I want to login with face, it freeze sometimes for many minutes on the log in screen and  gives me a window when on desktop to type password. If i dont type password cant open any app without getting that prompt. 

### STEPS TO REPRODUCE | 复现步骤

1. Enable biometric authentication and register face
2. Turn off the pc
3. On next turn on, login with face and stays too much (up to minutes on this screen) with loading cursor
![IMG_1784](https://user-images.githubusercontent.com/98664445/173846609-5bb2c49d-5a32-4963-b915-67dd3ea2b5e4.jpg)
4. Finally after done loading, it prompts on desktop with a password window. 
![Screenshot_select-area_20220615145136](https://user-images.githubusercontent.com/98664445/173846830-fb90b68a-6654-46c2-994f-ef06642407b0.png)

### OBSERVED RESULT | 观察到的结果

Biometric authentication with face seems to be failing unlocking the pc

### EXPECTED RESULT | 期望的结果

Face unlock working normally 

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Deepin 20.6 up to date

**Comment by BLumia** [comment]
According to #3099, you can try `rm ~/.local/share/keyrings/*` (do a backup if needed) to clear the keyrings and see if that could fix this issue.

**Comment by Octavian-Q** [comment]
> According to #3099, you can try `rm ~/.local/share/keyrings/*` (do a backup if needed) to clear the keyrings and see if that could fix this issue.

That helps but I am not doing it because for some reasons removes all my accounts log in info and from browser I cant even use password manager, it says empty passwords. (I dont remember all passwords without auto completion)

**Comment by BLumia** [comment]
> > According to #3099, you can try `rm ~/.local/share/keyrings/*` (do a backup if needed) to clear the keyrings and see if that could fix this issue.
> 
> That helps but I am not doing it because for some reasons removes all my accounts log in info and from browser I cant even use password manager, it says empty passwords. (I dont remember all passwords without auto completion)

I'm not sure if clearing keyring could be avoided to resolve the issue.

In case you might need it. You can install `seahorse` as a password manager (it could help you access your existing GNOME keyrings) and maybe use that for backup purpose :)

**Comment by Octavian-Q** [comment]
> > > According to #3099, you can try `rm ~/.local/share/keyrings/*` (do a backup if needed) to clear the keyrings and see if that could fix this issue.
> > 
> > 
> > That helps but I am not doing it because for some reasons removes all my accounts log in info and from browser I cant even use password manager, it says empty passwords. (I dont remember all passwords without auto completion)
> 
> I'm not sure if clearing keyring could be avoided to resolve the issue.
> 
> In case you might need it. You can install `seahorse` as a password manager (it could help you access your existing GNOME keyrings) and maybe use that for backup purpose :)

Well, for v23 maybe there is a mechanism to be invented so that helps solving that :)

**Comment by Zeno-sole** [comment]
I think your issue has been resolved, if you have other issues you can resubmit issues
