### ISSUE TITLE
dde-laucher does not start again after notebook awakes from sleep

### ISSUE THREAD

**Issue by jmwar65** [linuxdeepin/developer-center#3249]
### SUMMARY | 问题概要

dde-laucher does not start again after notebook awakes from sleep.
logfile says : 2022-06-16, 19:16:08.756 [Info   ] [  ] session locked, can not show launcher 
everytime i hit the laucher-icon in the dock.

### STEPS TO REPRODUCE | 复现步骤
Computer : HP 6470b
Boot up - Launcher seems to work normal.
shut down the case - open it again after the machine hast entered sleepmode.
I cant use the icon in the dock nor the windows button to open the launcher.
If you log out and reenter the system, it starts working again.
Seems to me an lockfile or something was not reset in the right way.

1. ...
2. ...
3. ...

**Comment by BLumia** [comment]
Closing as duplicated with https://github.com/linuxdeepin/developer-center/issues/3228. btw, we strongly suggest you fill all the fields of the issue template, for example the SOFTWARE/OS VERSIONS field could be help to let us know if it's happen on deepin or on other distro.
