### ISSUE TITLE
Weird box in multitasking view

### ISSUE THREAD

**Issue by IgnusG** [linuxdeepin/developer-center#325]
A weird box appears when opening the multitasking view. It displays the background image. The box is rendered on top of apps and is rather annoying.

On top of windows
![deepinscreenshot_select-area_20170703152332](https://user-images.githubusercontent.com/6438760/27794768-cfb26530-6003-11e7-9337-8b7ba461312f.png)

On new workspace
![deepinscreenshot_select-area_20170703152050](https://user-images.githubusercontent.com/6438760/27794762-c4e3cd42-6003-11e7-895f-64a0406e8858.png)

**Specs**
OS: Arch
Deepin WM: 1.9.14-1

**Comment by sonald** [comment]
@felixonmars did you experience that ?

**Comment by felixonmars** [comment]
No, I didn't.

**Comment by sonald** [comment]
@IgnusG Can you reproduce this in a easy way ?

**Comment by IgnusG** [comment]
@sonald It’s there every time I open the multitasking view. Not much else I can think of. 

I could try messing with the settings - might have caused it by accident using those.

**Comment by IgnusG** [comment]
@sonald box is no longer there so I presume a glitch of some sorts. Closing...
