### ISSUE TITLE
[Mail] Gmail doesn't work

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#3251]
Deepin Mail app is incompatible with Google Mail (Gmail) service. It has never worked since its release.

Google sets a level of security for third-party applications to access its services; Apps classified as "Less Secure Apps" are not allowed to access Google Account (read Gmail). In my view, the deepin Mail app needs to be curated by Google to be considered a "safe app".

Mozilla Thunderbird normally accesses Gmail! It is important for a developer to go behind the Mozilla team to find out how the Google Account was accessed.

deepin-mail 5.4.3-1
deepin Community 20.6 (OsBuild=11038.004)

More information: https://support.google.com/accounts/answer/6010255?hl=en

![Capturar_deepin-mail_20220617200254](https://user-images.githubusercontent.com/45263160/174414922-f0082164-014f-4e62-83b5-191a5367550e.png)

**Comment by BLumia** [comment]
@babyfengfjx could you take a look? Thanks!

**Comment by a8underscore** [comment]
That is no longer a solution unfortunately. nor is enabling "less secure apps", google has disabled this too.

The mail app needs to use Oauth2 to login to gmail now

**Comment by vivianxf** [comment]
已经提交需求跟踪，https://cooperation.uniontech.com/app/a34a0fa1-2103-480b-ac71-a6d5dc121ee9/61567bd58631a146fc90ea4a/6267be51465d919912641d6d
