### ISSUE TITLE
[Dock] Incorrect date format

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#3252]
The date format for most foreign languages follows the standard: dd/mm/yyyy.

After adjusting the date format in the settings, the system does not adjust to the new date display format.

dde-dock 5.5.38.1-1
deepin Community 20.6 (OsBuild=11038.004)

![Capturar_select-area_20220617214435](https://user-images.githubusercontent.com/45263160/174416184-8aeadf41-6002-4b66-b22a-1ec1ea2ad204.png)

![Capturar_select-area_20220617214536](https://user-images.githubusercontent.com/45263160/174416186-9566a4b5-ce3a-42d1-a665-0728e1908483.png)

**Comment by raspin0** [comment]
There must be an issue with the translation, deepin only supports yyyy-mm-hh format. There are actually a couple of standards https://en.wikipedia.org/wiki/Calendar_date#Usage_map

**Comment by BLumia** [comment]
The current date formatting on dock is hard-coded. I think there is a related plan to ensure the localization support of the time label on dock in deepin V23, could you confirm it? @meiyixiang

**Comment by Octavian-Q** [comment]
Also I have a time problem on the dock, I set for auto timezone from debian servers and if pc is not connected on the internet it shows time on the dock few hours behind of actual real time

**Comment by D8ma** [comment]
Yes, for Europe, the time, date and year are so right. It was difficult for min when I saw such a bug in deepin, everything was wrong.
