### ISSUE TITLE
为 system release 项目提供自动构建 ISO 和自动发布的Action @Zeno-sole

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#3267]

**Comment by Zeno-sole** [comment]
已在内网的Jenkins上部署自动发送构建任务的脚本

**Comment by Zeno-sole** [comment]
> @Zeno-sole 不能在github上面使用actions构建吗？

可以在actions上构建，只是构建的产物不方便存放，我们正在讨论仓库管理如何对外

**Comment by gnuhub** [comment]
@Zeno-sole 可以使用rsync上传到sourceforge,sourceforge适合大文件存放分发

**Comment by Zeno-sole** [comment]
https://cdimage.deepin.com/daily/ 日构建镜像地址
