### ISSUE TITLE
virtual desktop desktop names create the name of the desktops that the user wants.

### ISSUE THREAD

**Issue by D8ma** [linuxdeepin/developer-center#3272]
![20220630_115520.jpg](https://user-images.githubusercontent.com/107427853/176638661-bbcbfb58-f91f-41b0-b1c5-ff6a434a6dbf.jpg)
![IMG_20220630_120902.jpg](https://user-images.githubusercontent.com/107427853/176638971-01464fd9-b7e6-4601-af39-68bb72b54d99.jpg)

**Comment by BLumia** [comment]
Thanks for the feature request.

This feature already exists. You can go to the desktop and change wallpaper and the wallpaper will be independently from each virtual desktop.

Next time please use the discussion board for feature request. Thanks!
