### ISSUE TITLE
Add keyboard shortcuts.Paste you need to put an icon with a keyboard shortcut ctr+v.

### ISSUE THREAD

**Issue by D8ma** [linuxdeepin/developer-center#3275]
![IMG_20220630_135028.jpg](https://user-images.githubusercontent.com/107427853/176659711-696343bc-82f8-47df-bc5e-1781fe310446.jpg)![IMG_20220630_134945.jpg](https://user-images.githubusercontent.com/107427853/176659718-9881da8d-fcf1-4ef3-9e35-a16869257a07.jpg)![IMG_20220630_135406.jpg](https://user-images.githubusercontent.com/107427853/176660368-54629bd7-36b2-42fb-b2a6-88fdd1e3e17e.jpg)

**Comment by BLumia** [comment]
Duplicated with https://github.com/linuxdeepin/developer-center/issues/3276
