### ISSUE TITLE
[Deepin-Terminal]Search is not working

### ISSUE THREAD

**Issue by vizhnu** [linuxdeepin/developer-center#3277]
### SUMMARY | 问题概要
Search in terminal is not working.

### STEPS TO REPRODUCE | 复现步骤

1. Press Ctrl + Shift + F
2. Type any text in the search bar.
3. Press "Enter" or up or down bottons in the searchbar

### OBSERVED RESULT | 观察到的结果
Nothing happens. The keywords are not highlighted even if they are present in the terminal window.

### EXPECTED RESULT | 期望的结果

Occurrences of the keyword in the terminal window should be highlighted, and we should be able to move to next and previous occurraences.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息
OS: Ubuntu 20.04.4 LTS x86_64
Version information is not present in Deepin Terminal 
```
deepin-terminal --version
Deepin Terminal 
Copyright 2011-2017 Deepin, Inc.
```
![DeepinScreenshot_nemo-desktop_20220630220058](https://user-images.githubusercontent.com/29812014/176737111-6d297520-7d60-4de7-b353-1ed9bb455611.png)

### ADDITIONAL INFORMATION | 额外补充

I installed deepin-terminal using apt.

**Comment by BLumia** [comment]
I have tested this on Arch Linux with `deepin-terminal-gtk 5.0.4.3-1` and it seems works fine. Could you provide a screen record so we can see what's probably going wrong?

btw, the GTK version of deepin-terminal is no longer supported by the deepin team so even if it's a bug, we probably won't provide a fix. If you are willing to contribute, please feel free to create a fork and use it if preferred :)
