### ISSUE TITLE
[Deepin-Teminal] Right click menu not closing when left clicking anywhere outside

### ISSUE THREAD

**Issue by vizhnu** [linuxdeepin/developer-center#3278]
### SUMMARY | 问题概要
The popup menu appearing while right clicking does not disapper by clicking outside. It can only be closed by pressing Esc key.

### STEPS TO REPRODUCE | 复现步骤

1.Right click inside terminal window.
2. Left click anywhere else.

### OBSERVED RESULT | 观察到的结果

Menu doesn't close.

### EXPECTED RESULT | 期望的结果

Menu should get closed when clicking outside. This is the normal behaviour.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息
OS: Ubuntu 20.04.4 LTS x86_64

Deepin Terminal is not showing version.
```
**deepin-terminal --version
Deepin Terminal 
Copyright 2011-2017 Deepin, Inc.**
```
![DeepinScreenshot_nemo-desktop_20220630220058](https://user-images.githubusercontent.com/29812014/176739168-c88207fd-ae16-4272-a6de-1faeb0ace9b2.png)

**Comment by BLumia** [comment]
You are probably using the legacy (gtk) version of the terminal which is no longer supported by the deepin team, but anyway here are some information that might be helpful.

The source repo of the GTK/vala version deepin-terminal is [here](https://github.com/martyr-deepin/deepin-terminal-gtk). If you compile it from source, there should be a setting option to make it use the native context menu instead of deepin-menu. See [this commit](https://github.com/martyr-deepin/deepin-terminal-gtk/commit/1d3a33937f8f49d654f654a8fe16e0380c0d36c4) with option `prefer_deepin_menu`.

Let me know if you need any further help :)

**Comment by vizhnu** [comment]
Thank you so much for the reply @BLumia . I had installed deepin-terminal using `apt install deepin-terminal`. I think it is the legacy version. `apt policy deepin-terminal` gives the following output 
```
deepin-terminal:
  Installed: 5.0.0+ds1-1
  Candidate: 5.0.0+ds1-1
  Version table:
 *** 5.0.0+ds1-1 500
        500 http://in.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
        100 /var/lib/dpkg/status

```
Is there a way I can install the latest version, other than compiling from source?

**Comment by BLumia** [comment]
> Is there a way I can install the latest version, other than compiling from source?

Probably not unless there are other 3rd-party ppa that provide a binary package of the GTK version of deepin-terminal. Upstream (debian) already switched to the Qt/DTK version of deepin-terminal so even upgrade your system to 22.04 won't be able to get a newer GTK version of deepin-terminal.

Compile it from source shouldn't be hard, you can use `apt build-dep deepin-terminal` to get all build dependencies installed, and then a regular CMake build steps should be enough to compile (see the README for steps, and use `sudo make install` to install it locally if you want).

**Comment by vizhnu** [comment]
Hi @BLumia, forgive me for my choice of words, by latest version I meant installing the Qt/DTK version of deepin-terminal, not the latest version of the legacy terminal. 

> Upstream (debian) already switched to the Qt/DTK version of deepin-terminal

By this did you mean the official repository has Qt/DTK version? I'm on Ubuntu 20.04 and installed deepint-terminal using the command `apt install deepin-terminal`, and while checking snap store, it is saying deeping-terminal is already installed.
![image](https://user-images.githubusercontent.com/29812014/177004360-00e88b3e-cfc9-4878-9b2d-740f33982bcc.png)

I tried building this https://github.com/linuxdeepin/deepin-terminal project from source, but was getting this error:
```
deepin-terminal/build$ cmake ..
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for one of the modules 'dtkwidget'
-- Checking for one of the modules 'dtkgui'
CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:707 (message):
  None of the required 'dtkgui' found
Call Stack (most recent call first):
  CMakeLists.txt:76 (pkg_search_module)


-- Checking for one of the modules 'dtkcore'
-- Checking for one of the modules 'gobject-2.0'
-- Checking for module 'dframeworkdbus'
--   Found dframeworkdbus, version 2.0
-- Checking for module 'libsecret-1'
--   Found libsecret-1, version 0.20.4
-- Checking for modules 'xcb-ewmh;x11'
--   Found xcb-ewmh, version 0.4.1
--   Found x11, version 1.6.9
-- Keyboard layouts will be installed in: /usr/share/terminalwidget5/kb-layouts
-- Color schemes will be installed in: /usr/share/terminalwidget5/color-schemes
-- Translations will be installed in: /usr/share/terminalwidget5/translations
-- Looking for updwtmpx
-- Looking for updwtmpx - found
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
dtk-settings-tools could not be found at /dtk-settings
-- Found GTest: /usr/lib/x86_64-linux-gnu/libgtest.a  
-- Configuring incomplete, errors occurred!
See also "/home/nuchanger/Software/deepin-terminal/build/CMakeFiles/CMakeOutput.log".
See also "/home/nuchanger/Software/deepin-terminal/build/CMakeFiles/CMakeError.log".
```
I tied installing libdtksettings-dev, as suggested in another discussion thread, but was unsuccessful.

```
sudo apt install libdtksettings-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libdtksettings-dev
```

Once again, thank you for taking the time to reply. This is my first time building a project using cmake.

**Comment by BLumia** [comment]
Oh, my build instruction applies to the legacy GTK version which might be easier to compile.

The DTK version requires a higher version of DTK and other DDE stuff (for example `libdtksettings-dev` in your case) which are not available from Ubuntu 20.04, so if you want to build the DTK version, you need to build all the missing dependencies it requires, which might not be very easy to do.

If you insist on using Ubuntu 20.04, I personally suggest you try to build the last commit of the legacy GTK version, which will provide you the config options you need and nothing more. The DTK version is a completely rewritten so it might be some big differences from the GTK version that you might not expect.

If you still would like to get the Qt/DTK version and upgrading your distro is not an issue, then I suggest you upgrade your distro to Ubuntu 22.04, which is the latest LTS version currently, and you will get a lot of newer packages, which includes the DTK version of deepin-terminal :D

**Comment by vizhnu** [comment]
I tried buliding the GTK version but I am getting this error. I tried checking out to `origin/gtk-debian` branch as well.

```
deepin-terminal-gtk/build$ make;
[  8%] Built target cs
[  8%] Built target he
[  8%] Built target bn
[  8%] Built target es
[  8%] Built target gl_ES
[  8%] Built target ku_IQ
[  8%] Built target tr
[  8%] Built target eo
[  8%] Built target bg
[  8%] Performing build step for 'Vte-0.52'
Making all in src
Making all in .
Making all in app
Making all in bindings
Making all in gir
Making all in vala
 VAPIGEN vte-2.91.vapi
  GEN      app.c
./app.vala:984.5-984.45: warning: the modifier `static' is not applicable to constants
    public static const OptionEntry[] entries = {
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
./app.vala:793.5-793.33: warning: `Gtk.Settings.gtk_enable_mnemonics' has been deprecated since 3.10
./app.vala:796.5-796.31: warning: `Gtk.Settings.gtk_menu_bar_accel' has been deprecated since 3.10
./app.vala:820.3-820.23: error: struct `Test.App.Options' cannot be empty
  public struct Options
  ^^^^^^^^^^^^^^^^^^^^^
./app.vala:649.5-649.15: warning: `Gtk.Menu.popup' has been deprecated since 3.22
./app.vala:562.5-562.42: warning: `Vte.Terminal.set_geometry_hints_for_window' has been deprecated since 0.52
./app.vala:417.5-417.22: warning: `Gtk.Window.resize_to_geometry' has been deprecated since 3.20
./app.vala:765.5-765.22: warning: `Gtk.Window.resize_to_geometry' has been deprecated since 3.20
./app.vala:314.7-314.34: warning: `Gtk.Widget.set_double_buffered' has been deprecated since 3.14
./app.vala:399.17-399.41: warning: `Vte.Terminal.match_add_gregex' has been deprecated since 0.46
./app.vala:428.11-428.24: warning: `Gtk.Window.parse_geometry' has been deprecated since 3.20
./app.vala:435.9-435.26: warning: `Gtk.Window.resize_to_geometry' has been deprecated since 3.20
./app.vala:442.7-442.26: warning: `Gtk.Window.set_default_geometry' has been deprecated since 3.20
./app.vala:454.11-454.29: warning: `Vte.Terminal.spawn_sync' has been deprecated since 0.48
./app.vala:1092.7-1092.34: warning: `Gdk.Window.set_debug_updates' has been deprecated since 3.22
./app.vala:156.7-156.32: warning: `Vte.Terminal.search_set_gregex' has been deprecated since 0.46
Compilation failed: 1 error(s), 15 warning(s)
make[6]: *** [Makefile:850: app.c] Error 1
make[5]: *** [Makefile:452: all-recursive] Error 1
make[4]: *** [Makefile:578: all-recursive] Error 1
make[3]: *** [Makefile:485: all] Error 2
make[2]: *** [CMakeFiles/Vte-0.52.dir/build.make:112: Vte-0.52-prefix/src/Vte-0.52-stamp/Vte-0.52-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:441: CMakeFiles/Vte-0.52.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by BLumia** [comment]
I don't have Ubuntu 20.04 installed so not be able to test it right now, but searching `error: struct `Test.App.Options' cannot be empty` on Google results [this](https://gist.github.com/karimElmougi/5d6613e6300f245a8d0013b77c7d6538) which seems be a vte issue, and deepin-terminal-gtk uses the vendored vte by default.

While executing `cmake`, do you use the `-DUSE_VENDOR_LIB=off` option? If not, I suggest use `cmake ../ -DUSE_VENDOR_LIB=off` instead of just `cmake ../` so it will use the vte from your system instead of the vendored one.

**Comment by vizhnu** [comment]
Thanks, @BLumia, I was able to build it. The search issue seems to be fixed, which was my main problem. But the right-click menu is closing only when the Esc key is pressed, even though the commit you mentioned was included in the build. Anyway, it was not a big problem, I will see if this can be fixed by going through your commit. I was thinking about moving to 22.04 for a long time, I think it is finally time for that. Thank you so much for taking your time, I really appreciate it :)

**Comment by BLumia** [comment]
> But the right-click menu is closing only when the Esc key is pressed, even though the commit you mentioned was included in the build.

Did you edit the config file and set the `prefer_deepin_menu` to correct value? if you did, could you provide the content of the config file? Thanks!

**Comment by vizhnu** [comment]
I forgot to edit the config file the first time I built it, now I edited `lib/config.vala` and set false for `prefer_deepin_menu`and rebuilt using `make`. But the issue is still present.

**Comment by BLumia** [comment]
> I forgot to edit the config file the first time I built it, now I edited `lib/config.vala` and set false for `prefer_deepin_menu`and rebuilt using `make`. But the issue is still present.

You still need to edit the config file (not the source file, it should be located under `~/.config/deepin/deepin-terminal/config.conf` as documented in the README.md), and you need to set the config value here. The source file you edited only provides its default value so it will still keep using deepin-menu if you didn't change the value from the config file.

**Comment by vizhnu** [comment]
Hi @BLumia , I edited the config file `~/.config/deepin/deepin-terminal-gtk/config.conf` and set `prefer_deepin_menu` to false. The menu got changed, and is getting closed when we click ouside :smile:

**Comment by BLumia** [comment]
Good to know, and you can now close this issue if you have no other questions :)
