### ISSUE TITLE
[Archlinux] 深度系统监视器没有图标

### ISSUE THREAD

**Issue by lsblk** [linuxdeepin/developer-center#328]
1、深度的系统监视器在arch下的包没有图标，希望打包时可以先加上一个方便使用。
2、我定义的gnome快捷键指向deepin-system-monitor却无法起作用。快捷键如图
![default](https://user-images.githubusercontent.com/11588373/27920839-7c4a8dda-62a8-11e7-83f3-76ac6903b245.png)

**Comment by felixonmars** [comment]
1、上游还没有图标……我从哪里找 <(=﹁"﹁=)>
2、如果终端中运行没有问题，我不知道我这边怎么解决，或许怪 gnome？（我在 KDE 里测试是没问题的）

**Comment by lsblk** [comment]
额，快捷键的问题是我设置的问题，，如果我不设置C+M+.就行，图标可否先随便找一个方便使用？ @felixonmars

**Comment by felixonmars** [comment]
图标一般 Arch 不会单独去加。这个项目还很新，等上游动作吧 :)

**Comment by lsblk** [comment]
好的，谢谢啦。。
