### ISSUE TITLE
深度文管的回收站有问题

### ISSUE THREAD

**Issue by bigben446** [linuxdeepin/developer-center#3288]
深度文管的删除到回收站貌似是剪切到~/.local/share/Trash文件夹下，这样删除大文件的时候非常慢，特别是几个G的文件的时候不在系统盘的时候。

doublecmd的管理器或者gnome的文件管理器删除的策略是直接剪切到同一个磁盘的.Trash-1000下，由于是同一个磁盘，所以删除起来非常快，https://doublecmd.github.io/

为啥深度文管不采用类似的策略呢，还是第一次碰到删除文件这么慢的，原来是要剪切到不同的磁盘上去，这可费劲了。win删除的策略也是放到同一个磁盘里吧，放到不同的磁盘里面效率太低了。

**Comment by BLumia** [comment]
应该只是之前没这么写，后面又没有提出这样的行为需求吧。 @meiyixiang

**Comment by zccrs** [comment]
这纯粹是没有这样实现而已，理应这样做。算是个bug，不算需求。

**Comment by babyfengfjx** [comment]
这个问题很久前我们有提出过,不仅仅有删除慢的问题,还会导致回收站目录被很快占满的问题,而实际上可能其他分区是有很多空间的,该问题我们先提一个优化需求来跟踪,或许后续版本能采用更优的方案.

**Comment by meiyixiang** [comment]
设个问题前期和子项目组反馈过，产品并没有去定义底层的删除逻辑。这个问题已经反馈过，V23会去优化删除逻辑。

**Comment by meiyixiang** [comment]
但是目前内部评估这个功能逻辑对底层的改动很大，需求我们记录下来，研发会去调研，如果实现会在V23这个周期内去改进，但不会作为我们高优先级的需求去实现。

**Comment by SuperEffie** [comment]
感谢您的反馈。我们会对这个需求进行调研评估的。为了用户的便利，也会不断的对产品进行优化。
那么我先关闭这个issue了，欢迎您为我们提供更多宝贵的意见~
