### ISSUE TITLE
multitaskingview not working with deepin-metacity

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/developer-center#329]
When window effects are turned off, multitasking view doesn't work. Is that by design or a bug?
Manually issuing
```
dbus-send --session --dest=com.deepin.wm --print-reply /com/deepin/wm com.deepin.wm.PerformAction int32:1
```
has no effect and doesn't return any error either.

**Comment by sonald** [comment]
It's disabled by design. All effects are removed from deepin-metacity, which makes it faster and more efficient.

**Comment by oberon2007** [comment]
Ok. thanks! :)
