### ISSUE TITLE
DWaterProgress设置0值不显示

### ISSUE THREAD

**Issue by clcmj** [linuxdeepin/developer-center#3292]
![image](https://user-images.githubusercontent.com/86753262/177260243-0ba3f2a9-d1bb-4447-ae1e-177cb458a13f.png)
![image](https://user-images.githubusercontent.com/86753262/177260383-d96fd55c-36a3-44e4-96c0-773cb2c0f7f1.png)
关闭pBarRun，setValue(0)值后如图未正常显示
![image](https://user-images.githubusercontent.com/86753262/177260729-19bc71bf-5835-4bea-b93a-4cf795081753.png)
源码中d->value初始化为0，value设置为0后直接返回了。

**Comment by justforlxz** [comment]
这个可以用 std::optional 对 d->value 包裹一下，在有赋值的情况下才进行值判断，有兴趣来一个 pr 修复嘛？

**Comment by justforlxz** [comment]
> d->value从初始化就是有值的，如果在有的情况下进行值判断也还是相同的问题吧？

使用 optional 就是为了一开始不赋初始值。

**Comment by BLumia** [comment]
已在 https://github.com/linuxdeepin/dtkwidget/pull/125 中修复 :)
