### ISSUE TITLE
文本编辑器开启多个窗口后，误点关闭，编辑器卡死

### ISSUE THREAD

**Issue by wsq93** [linuxdeepin/developer-center#3293]
### SUMMARY | 问题概要

  我用文本编辑器打开多个TXT文档后，不小心误点右上角的关闭，然后文本编辑器卡死了，任务栏点强制退出也无法立即生效。后来点任务栏的所有窗口才关闭（可能是延时）。这样子关闭后，文本编辑器就再也开不了了。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

- 操作系统：deepin 20.6
- 内核版本：5.15.34-amd64-desktop
- 处理器：Intel Celeron N5095

### ADDITIONAL INFORMATION | 额外补充

  我这里是用的标准账号登录系统使用的。

  技术人员告知终端执行指令`killall deepin-editor`可重新使用文本编辑器了。

**Comment by wsq93** [comment]
### 日志
级别:信息 时间:2022-07-06 11:50:01.376 来源:文本编辑器 信息:"[GRABPOINT] POINT-01 startduration=205ms #(Init app time)" 
级别:信息 时间:2022-07-06 11:50:01.376 来源:文本编辑器 信息:com.iflytek.aiassistant service no registered! 
级别:信息 时间:2022-07-06 11:49:48.133 来源:文本编辑器 信息:"[GRABPOINT] POINT-02 closeduration=6ms #(Close app time)" 
级别:信息 时间:2022-07-06 11:49:44.242 来源:文本编辑器 信息:com.iflytek.aiassistant service no registered! 
级别:信息 时间:2022-07-06 11:49:44.241 来源:文本编辑器 信息:"[GRABPOINT] POINT-01 startduration=206ms #(Init app time)" 
级别:信息 时间:2022-07-06 11:49:36.685 来源:文本编辑器 信息:"[GRABPOINT] POINT-02 closeduration=5ms #(Close app time)" 
级别:信息 时间:2022-07-06 11:49:33.057 来源:文本编辑器 信息:"[GRABPOINT] POINT-01 startduration=209ms #(Init app time)" 
级别:信息 时间:2022-07-06 11:49:33.057 来源:文本编辑器 信息:com.iflytek.aiassistant service no registered! 
级别:信息 时间:2022-07-06 11:43:37.837 来源:文本编辑器 信息:"[GRABPOINT] POINT-02 closeduration=5ms #(Close app time)" 
级别:信息 时间:2022-07-06 11:43:35.264 来源:文本编辑器 信息:com.iflytek.aiassistant service no registered! 
级别:信息 时间:2022-07-06 11:43:35.264 来源:文本编辑器 信息:"[GRABPOINT] POINT-01 startduration=205ms #(Init app time)" 
级别:信息 时间:2022-07-06 11:43:29.565 来源:文本编辑器 信息:"[GRABPOINT] POINT-02 closeduration=7ms #(Close app time)" 
级别:信息 时间:2022-07-06 11:43:26.413 来源:文本编辑器 信息:"[GRABPOINT] POINT-01 startduration=215ms #(Init app time)" 
级别:信息 时间:2022-07-06 11:43:26.412 来源:文本编辑器 信息:com.iflytek.aiassistant service no registered! 
级别:信息 时间:2022-07-06 11:41:33.113 来源:文本编辑器 信息:"[GRABPOINT] POINT-02 closeduration=6ms #(Close app time)" 
级别:信息 时间:2022-07-06 11:38:21.872 来源:文本编辑器 信息:"[GRABPOINT] POINT-01 startduration=207ms #(Init app time)" 
级别:信息 时间:2022-07-06 11:38:21.871 来源:文本编辑器 信息:com.iflytek.aiassistant service no registered! 
级别:信息 时间:2022-07-06 11:37:52.413 来源:文本编辑器 信息:"[GRABPOINT] POINT-02 closeduration=6ms #(Close app time)" 
级别:信息 时间:2022-07-06 11:35:23.441 来源:文本编辑器 信息:"[GRABPOINT] POINT-01 startduration=206ms #(Init app time)" 
级别:信息 时间:2022-07-06 11:35:23.441 来源:文本编辑器 信息:com.iflytek.aiassistant service no registered! 
级别:信息 时间:2022-07-06 11:33:40.609 来源:文本编辑器 信息:"[GRABPOINT] POINT-02 closeduration=5ms #(Close app time)" 
级别:信息 时间:2022-07-06 11:33:34.151 来源:文本编辑器 信息:"[GRABPOINT] POINT-01 startduration=205ms #(Init app time)" 
级别:信息 时间:2022-07-06 11:33:34.151 来源:文本编辑器 信息:com.iflytek.aiassistant service no registered! 
级别:信息 时间:2022-07-06 11:33:32.506 来源:文本编辑器 信息:"[GRABPOINT] POINT-02 closeduration=6ms #(Close app time)" 
级别:信息 时间:2022-07-06 11:33:28.477 来源:文本编辑器 信息:"[GRABPOINT] POINT-01 startduration=222ms #(Init app time)" 
级别:信息 时间:2022-07-06 11:33:28.477 来源:文本编辑器 信息:com.iflytek.aiassistant service no registered! 
级别:信息 时间:2022-07-06 11:33:15.532 来源:文本编辑器 信息:"[GRABPOINT] POINT-02 closeduration=6ms #(Close app time)" 
级别:信息 时间:2022-07-06 11:32:57.143 来源:文本编辑器 信息:"[GRABPOINT] POINT-01 startduration=204ms #(Init app time)" 
级别:信息 时间:2022-07-06 11:32:57.142 来源:文本编辑器 信息:com.iflytek.aiassistant service no registered! 
级别:信息 时间:2022-07-06 11:32:26.967 来源:文本编辑器 信息:"[GRABPOINT] POINT-02 closeduration=6ms #(Close app time)" 
级别:信息 时间:2022-07-06 11:32:13.719 来源:文本编辑器 信息:com.iflytek.aiassistant service no registered! 
级别:信息 时间:2022-07-06 11:32:13.718 来源:文本编辑器 信息:"[GRABPOINT] POINT-01 startduration=208ms #(Init app time)" 
级别:信息 时间:2022-07-06 11:32:12.686 来源:文本编辑器 信息:"[GRABPOINT] POINT-02 closeduration=6ms #(Close app time)" 
级别:信息 时间:2022-07-06 11:31:54.209 来源:文本编辑器 信息:"[GRABPOINT] POINT-01 startduration=203ms #(Init app time)" 
级别:信息 时间:2022-07-06 11:31:54.209 来源:文本编辑器 信息:com.iflytek.aiassistant service no registered! 
级别:信息 时间:2022-07-06 11:31:53.087 来源:文本编辑器 信息:"[GRABPOINT] POINT-02 closeduration=7ms #(Close app time)" 
级别:信息 时间:2022-07-06 11:31:49.843 来源:文本编辑器 信息:"[GRABPOINT] POINT-01 startduration=206ms #(Init app time)" 
级别:信息 时间:2022-07-06 11:31:49.843 来源:文本编辑器 信息:com.iflytek.aiassistant service no registered! 
级别:信息 时间:2022-07-06 11:31:41.295 来源:文本编辑器 信息:"[GRABPOINT] POINT-02 closeduration=6ms #(Close app time)" 
级别:信息 时间:2022-07-06 11:26:23.218 来源:文本编辑器 信息:"[GRABPOINT] POINT-01 startduration=220ms #(Init app time)" 
级别:信息 时间:2022-07-06 11:26:23.217 来源:文本编辑器 信息:com.iflytek.aiassistant service no registered!

**Comment by wsq93** [comment]
当天的日志只有【信息】级别的。

**Comment by BLumia** [comment]
不能稳定复现的话其实目前看到的信息帮助并不大，可以考虑先安装一下 `systemd-coredump` 这个包，下次遇到的时候可以 `coredumpctl info` 看下是不是崩溃了，有没有相关信息之类，会比较有用。

**Comment by wsq93** [comment]
我在这发过信息后，又复现了。但我不确定下次重启之后还能不能复现。

**Comment by babyfengfjx** [comment]
看是否可以按照这个方式抓取一下coredump的日志信息：https://bbs.deepin.org/post/235642

**Comment by wsq93** [comment]
哦噢，我下次试试。
今天启动系统后，这个问题暂时没有再复现。

**Comment by wsq93** [comment]
才说没再复现，刚刚就遇到编辑器启动不了的情况了——真是打脸，偏偏还在普通账号测试没装那个工具。

**Comment by BLumia** [comment]
到目前没有再收到进一步的信息了，目前的信息不足以复现与定位问题，就先关闭了。

如果您这边还能复现的话，可以考虑开个新的 issue 并附带详细信息反馈，或者使用新的内置的深度之家进行反馈 :)
