### ISSUE TITLE
更换键盘布局后可能出现快捷键无法使用的问题

### ISSUE THREAD

**Issue by jouyouyun** [linuxdeepin/developer-center#33]
**jouyouyun:**

更改掉系统的键盘布局，重新登录后快捷键就不可使用了，因为按键的 `keysym` 发生了改变。然后去测试了 `Gnome` 和 `KDE`，发现 `Gnome` 和 `KDE` 则会部分有效(不同的键盘布局有效的快捷键不一样)。

猜测它们是在更改键盘布局之前完成的快捷键的 `grab` 操作，这样就会出现部分快捷键可用的现象。

现在大概想到了以下两种方法
- 设置布局时去设置 `fcitx` ，让键盘布局作为输入法
- 保证 keybinding 在 inputdevices 之前启动完成，就可使部分快捷键有效

或者是有其他更好的方法？

**snyh:**

依赖fcitx在移植的时候会有点坑．

确保模块的启动顺序目前的dde-session-daemon就已经支持了吧．不知道这种做法的弊端具体是？

**hualet:**

```
依赖fcitx在移植的时候会有点坑．确保模块的启动顺序目前的dde-session-daemon就已经支持了吧.不知道这种做法的弊端具体是？
```

切换键盘布局后，部分快捷键能使用，部分不能使用。

**sonald:**

这个标题是啥意思啊，从没考虑过键盘布局的问题，明天看看

**hualet:**

```
这个标题是啥意思啊，从没考虑过键盘布局的问题，明天看看
```

我看俄语的意思是键盘布局切换成俄语以后，所有的快捷键都失效了，嗯。

**jouyouyun:**

@sonald 对于键盘布局更改后，快捷键无法用有没有好的方法处理？

**sonald:**

所以我想是这样的：绑定快捷键用的是XGrabKey么，最终是绑keycode，但是keycode都是从当前layout和keysym获取的。改了layout后，许多键盘按键（按键的keycode不变）对应的keysym（比如键盘上q对应的）发生变化了，wm重新绑定。但还是绑super+q（因为从dconf里读到的还是super+q），q这个字母在新layout里并不是之前键盘上的字母q对应的keysym了，有可能不存在。

所以这个好复杂，感觉是要建立一个映射，记住每个快捷键的keycode组合，layout改了之后重新生成keysym组合的快捷键写到dconf里。。。。

纯属YY

举个例子：dconf里记录了super+a，得到keycode序列133+38，keysym为0xffeb+0x61。layout变为de;ru后，键盘上a的keysym变了，这时候控制中心要知道keysym从0xffeb+0x61变成0xffeb+0x6c1了，重新再做一次快捷键绑定。可行不sweat_smile

**jouyouyun:**

```
看我上面的YY举个例子：dconf里记录了super+a，得到keycode序列133+38，keysym为0xffeb+0x61。layout变为de;ru后，键盘上a的keysym变了，这时候控...
```

这样只会对我们处理的快捷键生效，其他程序的还是无效。

Go 里面当快捷键按下后收到的是 keycode，然后在手动调接口转成 keysym 的，能否在 keycode 转 keysym 那里做处理？在那个地方强制把键盘布局设置为 us，转换完成后再设回去？

不知道是不是所有的快捷键都是英文组合，如果定义了一个俄语组合的快捷键，按上面的方法又会挂。

**sonald:**

```
这样只会对我们处理的快捷键生效，其他程序的还是无效。Go 里面当快捷键按下后收到的是 keycode，然后在手动调接口转成 keysym 的，能否在 keycode 转 keysym 那里做处理？在...
```

其他程序不知道怎么处理，但是wm这边如果只在Go后端处理是不行的吧。因为settings里面写的还是us布局下的符号（比如super+a)，在de;ru下符号变成(super+Cyrillic_a)了。不改settings里面的配置，wm就会绑定错误的快捷键（在de;ru下还去绑super+a，但是a已经不存在l )。

**jouyouyun**

```
其他程序不知道怎么处理，但是wm这边如果只在Go后端处理是不行的吧。因为settings里面写的还是us布局下的符号（比如super+a)，在de;ru下符号变成(super+Cyrillic_a)...
```

这样就需要保证 grab 和 keycode 转 keysym 时都是 us 布局，不过这样改了底层的 XLib 接口可能又会有其他问题。

直接将键盘布局设为输入法，不知道这个方法如何，以前在 fcitx 的 dbus 接口里看到过键盘布局相关的接口的，现在里面没发现了。

**Comment by sonald** [comment]
这里有两层：
+ 跟踪记录keycode <->keysym的变化。感觉可以直接用xkb的api来做。
+ 不管在go daemon端那边处理还是控制中心前端处理，对于用户来说，它看到的东西还是控制中心里呈现的super+a，切换布局后，这里要不要跟着更新为super+Cyrillirc_a。 如果不更新，一是wm会读取错误的keysym组合，得不到正确的keycode来生成快捷键。而且用户此时重设了某个快捷键，显示的就是新layout下的字符串表示。这样两种布局的快捷键字符串表示就混在一起了。乱了。

> 直接将键盘布局设为输入法，不知道这个方法如何，以前在 fcitx 的 dbus 接口里看到过键盘布局相关的接口的，现在里面没发现了。
这个我不太懂：）

@manateelazycat  @hualet  @snyh @jouyouyun 有什么看法。不知道有没有ＤＥ能正确处理这个事情的。

**Comment by snyh** [comment]
这个问题，有没有明确知道用户正确效果应该是怎样的？　
技术方面我觉得还好解决，　主要是多布局的切换行为到底如何算正确行为的理解不够

**Comment by sonald** [comment]
对，就是怎样算合理的处理方式。回到源头，为啥GNOME和KDE都处理不好？会不会是个伪命题，正确的打开方式不是在安装的时候或者初次配置向导里选择好键盘布局，在那里一次性修改了所有配置文件里关于快捷键的定义。运行时切换的需求大么

**Comment by manateelazycat** [comment]
运行时切换键盘布局的需求很简单， 西班牙语， 他们都是直接输入键盘字符的（英文或西班牙字符）， 不需要像我们输入法那样切换。 
所以他们在输入英文和输入西班牙语的时候就是通过快速切换键盘布局来做的， 就像我们中文来切换输入法一样， 会看托盘的图标， 只不过他们是直接输入字符， 不用输入法参与。

**Comment by snyh** [comment]
@manateelazycat 切换布局这个需求大家都能接受理解．　只是在切换时的快捷键处理不明确(至少我个人不能完全理解到底要做什么)
@maggielf 提出的加上日语这类键盘的时候又是个什么情况．

**Comment by hualet** [comment]
已采取在当前的键盘布局后面跟上us布局的方式处理
