### ISSUE TITLE
DDE Control Center crashes in Keyboard and Language/shortcuts on Arch

### ISSUE THREAD

**Issue by carl-krikorian** [linuxdeepin/developer-center#3302]
In Deepin control center 5.4.70-2 running on a freshly installed Arch Linux, accessing the Shortcuts tab in Keyboard and Language menu crashes the app with the error:

(process:3493): GLib-GIO-ERROR **: 20:38:33.877: Settings schema 'com.deepin.dde.control-center' does not contain a key named 'color-picker-config'

Am I maybe missing any packages? If more information is necessary, I'm happy to oblige.

**Comment by BLumia** [comment]
The deepin-control-center package needs to be packaged first. There might be some porting issues need to be resolved that might cause FTBFS on Arch Linux, though.

See also: #3135 #2716

**Comment by BLumia** [comment]
Should be fixed after upgrading to 5.5.77 or newer version, thanks again for the issue report :)
