### ISSUE TITLE
VPN addresses not support domain names

### ISSUE THREAD

**Issue by vampywiz17** [linuxdeepin/developer-center#3304]
### SUMMARY | 问题概要

Not possible to add domain name to VPN address

### STEPS TO REPRODUCE | 复现步骤

1. Create a new VPN connection and try to add a domain name to address field. It say that is error.

### OBSERVED RESULT | 观察到的结果

If i save the settings, get a error message

### EXPECTED RESULT | 期望的结果

save the config without any problem

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Deepin 20.6

**Comment by BLumia** [comment]
@meiyixiang 目前 VPN 地址不能填写域名，只能填写 IP 地址，是设计如此吗？如果是的话，调整成允许输入域名的话是否可以接受呢？

**Comment by zccrs** [comment]
> @meiyixiang 目前 VPN 地址不能填写域名，只能填写 IP 地址，是设计如此吗？如果是的话，调整成允许输入域名的话是否可以接受呢？

应该是bug, 估计是输入框加了ipv4的格式校验

**Comment by BLumia** [comment]
> > @meiyixiang 目前 VPN 地址不能填写域名，只能填写 IP 地址，是设计如此吗？如果是的话，调整成允许输入域名的话是否可以接受呢？
> 
> 应该是bug, 估计是输入框加了ipv4的格式校验

是加了。上面有 link 一个 PR 对应这个行为的，不清楚是不是故意加的 ipv4 的校验，如果是的话应该是之前的需求吧。

**Comment by meiyixiang** [comment]
The current design is so, if we can do it, we can achieve their own support domain name.

**Comment by meiyixiang** [comment]
When the implementation is complete, it can be closed

**Comment by BLumia** [comment]
Already implemented by @kt286 in the linked PR :)
