### ISSUE TITLE
Krita's performances poor in Deepin Arch Linux

### ISSUE THREAD

**Issue by SalahAdDin** [linuxdeepin/developer-center#332]
Related: https://github.com/linuxdeepin/developer-center/issues/251

This issue was solved but with the terrible RAM memory consuption of Deepin Krita all time is crashed: i have to support more than ten desktop exit, i had to close it by force more than five times, i have to wait many time for apply simple move and crop operations in Krita with a image(4096*2048), only for this operations!!!

what is happening?

**Comment by funilrys** [comment]
I don't know what's happening here but I'll suggest you to see what's going with `htop` ...

**Comment by SalahAdDin** [comment]
It is still open?

**Comment by BLumia** [comment]
Seems no longer have this issue. If you have any DDE related issue when using Krita, feel free to open a new issue and provide details so others can help you out.

**Comment by SalahAdDin** [comment]
@BLumia Actually i reopened my old issue because i got the same bug again.
