### ISSUE TITLE
Installation media does not boot kernel 5.15 option

### ISSUE THREAD

**Issue by arch-user-france1** [linuxdeepin/developer-center#3323]
### SUMMARY | 问题概要

The Linux vmlinuz 5.15 is missing

### STEPS TO REPRODUCE | 复现步骤

1. make an installation media
2. try booting with the kernel 5.15
3. see result

### OBSERVED RESULT | 观察到的结果

It says:
couldn't find ...
you must load the kernel first

### EXPECTED RESULT | 期望的结果

It would boot as usual

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Deepin ISO - the newest

### ADDITIONAL INFORMATION | 额外补充

-

**Comment by arch-user-france1** [comment]
1929

**Comment by Zeno-sole** [comment]
Selecting the 5.15 kernel installation prompts that the kernel file cannot be found. It is recommended that you check the integrity of the file. Maybe the iso file is damaged and incomplete.

**Comment by arch-user-france1** [comment]
I did that already, it's fine.

**Comment by Zeno-sole** [comment]
Has your problem been resolved? No other issues I will close this issues

**Comment by arch-user-france1** [comment]
> Has your problem been resolved? No other issues I will close this issues

I don't know - I never used the installation media again. I guess it's the devs fault not including the 5.15 kernel properly.

**Comment by Zeno-sole** [comment]
What method did you use to burn the iso file?

**Comment by arch-user-france1** [comment]
I downloaded it from Google Drive because the deepin server did not respond to my download request and burned it using balena etcher which revalidated the ISO after burning and I also executed an ISO test in the GRUB which seemed ok.

**Comment by Zeno-sole** [comment]
You can try to download the mirror installation from the official channel, and compare the MD5 after downloading.
Download address: https://cdimage.deepin.com/releases/20.6/

**Comment by arch-user-france1** [comment]
Doesn't work - #3324

**Comment by arch-user-france1** [comment]
![image](https://user-images.githubusercontent.com/72965843/181734710-5d18399f-1726-402f-a262-7bdfbae72110.png)

**Comment by Zeno-sole** [comment]
It seems that you cannot access the official cdimage due to network reasons, you can use the mirror site to download the address

**Comment by Zeno-sole** [comment]
> It seems that you cannot access the official cdimage due to network reasons, you can use the mirror site to download the address

http://ftp.jaist.ac.jp/pub/Linux/deepin-cd/20.6/

**Comment by arch-user-france1** [comment]
Is this the same as google drive?
https://drive.google.com/drive/folders/1G6p5_7k97E2dmzHngnh_lbKQTLjstz6c

**Comment by Zeno-sole** [comment]
It is recommended that you check whether the MD5 of the iso is consistent with the official one

**Comment by arch-user-france1** [comment]
> It is recommended that you check whether the MD5 of the iso is consistent with the official one

I cannot download it from google drive anymore, it says your "download quota" was exceeded.
I also don't really want to create a new bootable. Have you checked whether you can boot 5.15 kernel on the installation media or not?

**Comment by arch-user-france1** [comment]
The sum is correct. Your provided ISO cannot boot kernel 5.15, you should investigate this, or whoever maintains the ISO.

**Comment by Zeno-sole** [comment]
We have tested many devices without this phenomenon, I suspect it is the problem of the burning tool

**Comment by arch-user-france1** [comment]
> We have tested many devices without this phenomenon, I suspect it is the problem of the burning tool

You cannot say that the burning tool is the problem, really not. Then it shouldn't have worked at all.
I used etcher. It validated the burnt image which was successful.
The problem must be the ISO, there couldn't have any data corruption happened. The image was copied bit per bit and I also validated my image using the sha256sum from this link: http://ftp.jaist.ac.jp/pub/Linux/deepin-cd/20.6/

**Comment by Zeno-sole** [comment]
Does this also happen when changing other ISO?

**Comment by arch-user-france1** [comment]
I can only get those two ISOs because of a server-failure. Both have the same checksum so they're the same.
Could you test the ISO from the Google Drive or this ISO: http://ftp.jaist.ac.jp/pub/Linux/deepin-cd/20.6/ (they seem to be the same)?
It doesn't work on my systems.

**Comment by Zeno-sole** [comment]
There may be a problem with the BIOS firmware, you can try other images to see if there is the same error

**Comment by Zeno-sole** [comment]
http://ftp.jaist.ac.jp/pub/Linux/deepin-cd/

**Comment by Zeno-sole** [comment]
such as 20.5 or earlier
http://ftp.jaist.ac.jp/pub/Linux/deepin-cd/

**Comment by arch-user-france1** [comment]
Manjaro kernel 5.15 worked just fine so the UEFI is fine.

**Comment by Zeno-sole** [comment]
Manjaro does not provide a dual-core installation method, and I don't think it can verify the problem. You can install the v23 preview version of the image, this version defaults to 5.15 kernel
https://cowtransfer.com/s/55c5d60d83e146   
I am not sure if you can access this link, if not I will upload to google drive

**Comment by arch-user-france1** [comment]
What is dual-core installation?

**Comment by Zeno-sole** [comment]
It is in the form of two versions of the kernel installation provided on the grub interface

**Comment by arch-user-france1** [comment]
Still the UEFI cannot change anything there.
It's grub's job to do this.

**Comment by Zeno-sole** [comment]
Unfortunately I don't have such a machine and can't verify the situation you describe
