### ISSUE TITLE
shift + space does nothing

### ISSUE THREAD

**Issue by arch-user-france1** [linuxdeepin/developer-center#3325]
This is the only desktop environment where shift + space does not jump and the dock appears all the time even if the game is in full screen mode.

I used wine, wine and roblox.

**Comment by BLumia** [comment]
Since you skipped the issue template, please at least provide the basic information to reproduce. Which distro are you using, according to your username, can I assume you are using Arch Linux?

**Comment by arch-user-france1** [comment]
Oh I thought it's not relevant.

1. I am using Arch (Manjaro) Linux and recently updated it.
2. KDE and GNOME work
3. I used the GDM manager to log into deepin (irrelevant?)
4. I used grapejuice for running Roblox (phantom forces)
5. I started it in fullscreen mode but it didn't work without fullscreen mode afterwards (I didn't restart it)
6. The dock appeared all the time even the application (game) was in fullscreen mode (I enabled something so I could move windows under the dock)
7. I installed every package I think.

**Comment by BLumia** [comment]
Which window manager are you using? if you are using Arch Linux (Manjaro is NOT Arch) then by default it will use `deepin-wm`, in this case I suggest try switch to [`deepin-kwin`](https://archlinux.org/packages/community/x86_64/deepin-kwin/).

**Comment by arch-user-france1** [comment]
I did install deepin-kwin because I read it in some guide but it could have misbehaved and not installed deepin-kwin. How can I check if it really uses kein?

**Comment by BLumia** [comment]
> How can I check if it really uses kein?

If you have `neofetch` then it could works, or simply `ps -e | grep kwin`

**Comment by arch-user-france1** [comment]
![image](https://user-images.githubusercontent.com/72965843/181029213-dcc3e0a2-d78f-4707-8741-8af1acff9dd1.png)
![image](https://user-images.githubusercontent.com/72965843/181029274-ecbda5f6-a931-4295-b78e-9054c45befb7.png)

Kwin is definitely running and on the correct tty.

**Comment by arch-user-france1** [comment]
I just noticed that it also does nothing in the terminal which it should (shift + space would be a usual space)

**Comment by arch-user-france1** [comment]
any update @tsic404 ?

**Comment by tsic404** [comment]
shift + space use /usr/libexec/dde-daemon/keybinding/shortcut-dde-grand-search.sh scripts to call grand search writen in https://github.com/linuxdeepin/dde-daemon/blob/master/keybinding/shortcuts/system_shortcut.go#L118

**Comment by tsic404** [comment]
If you want to disable this shortcut, you can use `gsettings set com.deepin.dde.keybinding.system.enable global-search false`

**Comment by arch-user-france1** [comment]
Apparently the same problem now occurs in gnome (I hadn't executed your command) plus shift + super doesn't work. Really, really annoying and I don't know where it's coming from... I'll investigate this.

Could you change the default keybinding to super + space, alt + space or ctrl + space?
I think in general shift + space is a bad keybinding.
MacOS uses super + space (and the super key is where the alt key is on my keyboard, right near space).

**Comment by arch-user-france1** [comment]
and sometimes the super key does not open the gnome application overview :( making me so angry

**Comment by BLumia** [comment]
> The grand search doesn't open on Arch

I think it's because it's not packaged by the Arch Linux packagers currently :)

> Could you change the default keybinding to super + space, alt + space or ctrl + space?

By design, user should be able to change the Grand Search shortcut in the Control Center app, so user could always set to a different shortcut if they like.

I'm not sure if not having the grand-search app installed is the reason why the shortcut is not listed in the Control Center, and in fact, I'm also not sure if that's the reason that caused the issue you have. (I don't play roblox, and really don't want to enable multilib to get wine working, so haven't test it yet).

Also, <kbd>ctrl + space</kbd> is the default shortcut to switch IME state for fcitx users :)

**Comment by arch-user-france1** [comment]
You can test it simply by opening a text editor and typing shift + space, by the way.

**Comment by arch-user-france1** [comment]
ctrl + space works again on gnome

**Comment by tsic404** [comment]
On gnome, using `ps -elf | grep dde-session-daemon` to find is dde-session-daemon is running? which used to handle shortcut.

**Comment by arch-user-france1** [comment]
Why is this running WT*
![image](https://user-images.githubusercontent.com/72965843/182085026-f1d18698-70bb-4a75-938f-e447c172332f.png)
It shouldn't even be running at all.

**Comment by arch-user-france1** [comment]
Still not working after the command is run.

> If you want to disable this shortcut, you can use `gsettings set com.deepin.dde.keybinding.system.enable global-search false`

**Comment by BLumia** [comment]
Sorry for getting back to this issue so late. I can no longer reproduce this issue under Arch linux. Is this issue also gone in your installation?

**Comment by arch-user-france1** [comment]
If you can no longer experience it, let's close it. I didn't use Deepin anymore since quite a while.
