### ISSUE TITLE
[dtkgui] 在源码目录直接打包libdtkgui5-bin打包失败

### ISSUE THREAD

**Issue by gnuhub** [linuxdeepin/developer-center#3328]
![photo_2022-07-25_14-45-36](https://user-images.githubusercontent.com/1329093/180715102-148ffab3-29bd-48b0-a649-f17eda9bc8e1.jpg)

**Comment by kegechen** [comment]
不好意思，忘了删除了。仓库中的代码打包是没有.git目录的，所以没有发现。
