### ISSUE TITLE
Deepin-voice-notes broken toolbar

### ISSUE THREAD

**Issue by raspin0** [linuxdeepin/developer-center#3333]
https://user-images.githubusercontent.com/39202451/181266419-5ac2859b-141b-4950-a165-3dfff094b18a.mp4

version: 5.10.15 deepin 20.6

**Comment by BLumia** [comment]
Hi, could you open a terminal and execute `echo $LANGUAGE` and provide the result? Thanks!

**Comment by raspin0** [comment]
> Hi, could you open a terminal and execute `echo $LANGUAGE` and provide the result? Thanks!

```
morcin@morcin-PC:~$ echo $LANGUAGE
pl_PL
```

**Comment by BLumia** [comment]
I cannot reproduce this issue on my side with `LANGUAGE=pl_PL deepin-voice-note`, do you apply any DPI scale that may cause this issue?

**Comment by babyfengfjx** [comment]
We are unable to reproduce the problem.
Can you help with the following command: ```sudo apt install inxi -y && inxi -F ```and provide a screenshot of the output device information, as well as execute :```dpkg -l > ~/Desktop/version.txt``` and provide the version.txt file generated on the desktop?

We are unable to reproduce the problem.

**Comment by raspin0** [comment]
```
morcin@morcin-PC:~$ inxi -F
System:    Host: morcin-PC Kernel: 5.15.34-amd64-desktop x86_64 bits: 64 Desktop: Deepin 20.6 Distro: Deepin 20.6 
Machine:   Type: Desktop System: ASUS product: All Series v: N/A serial: <root required> 
           Mobo: ASUSTeK model: Z97-PRO GAMER v: Rev X.0x serial: <root required> UEFI: American Megatrends v: 2203 
           date: 02/26/2016 
CPU:       Topology: Quad Core model: Intel Core i7-4790K bits: 64 type: MT MCP L2 cache: 8192 KiB 
           Speed: 4000 MHz min/max: 800/4500 MHz Core speeds (MHz): 1: 4000 2: 4000 3: 4000 4: 4000 5: 4000 6: 4000 7: 4000 
           8: 4000 
Graphics:  Device-1: NVIDIA GM204 [GeForce GTX 970] driver: nvidia v: 510.60.02 
           Display: x11 server: X.Org 1.20.11 driver: nvidia unloaded: fbdev,modesetting,nouveau,vesa tty: N/A 
           OpenGL: renderer: NVIDIA GeForce GTX 970/PCIe/SSE2 v: 4.6.0 NVIDIA 510.60.02 
Audio:     Device-1: Intel 9 Series Family HD Audio driver: snd_hda_intel 
           Device-2: NVIDIA GM204 High Definition Audio driver: snd_hda_intel 
           Device-3: XMOS type: USB driver: hid-generic,snd-usb-audio,usbhid 
           Device-4: C-Media Multimedia Headset [Gigaware by Ignition L.P.] type: USB driver: hid-generic,snd-usb-audio,usbhid 
           Sound Server: ALSA v: k5.15.34-amd64-desktop 
Network:   Device-1: Intel Ethernet I218-V driver: e1000e 
           IF: eno1 state: up speed: 1000 Mbps duplex: full mac: 08:62:66:27:a7:7a 
Drives:    Local Storage: total: 701.76 GiB used: 475.40 GiB (67.7%) 
           ID-1: /dev/sda vendor: Intenso model: SSD Sata III size: 236.00 GiB 
           ID-2: /dev/sdb vendor: Seagate model: ST500LM012 HN-M500MBB size: 465.76 GiB 
Partition: ID-1: / size: 14.70 GiB used: 8.93 GiB (60.7%) fs: ext4 dev: /dev/sda4 
           ID-2: /boot size: 487.9 MiB used: 308.8 MiB (63.3%) fs: ext4 dev: /dev/sda2 
           ID-3: swap-1 size: 16.00 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/sda7 
Sensors:   System Temperatures: cpu: 51.0 C mobo: 27.8 C 
           Fan Speeds (RPM): N/A 
Info:      Processes: 341 Uptime: 34m Memory: 15.58 GiB used: 6.54 GiB (42.0%) Shell: bash inxi: 3.0.32 
```
[version.txt](https://github.com/linuxdeepin/developer-center/files/9219058/version.txt)

**Comment by raspin0** [comment]
> I cannot reproduce this issue on my side with `LANGUAGE=pl_PL deepin-voice-note`, do you apply any DPI scale that may cause this issue?

no

**Comment by xuqi27837288** [comment]
I cannot reproduce this issue on my side with LANGUAGE=pl_PL deepin-voice-note, @raspin0

**Comment by BLumia** [comment]
@raspin0 What's your default font? Could you take a screenshot of the font setting screen in Control Center?

**Comment by raspin0** [comment]
> @raspin0 What's your default font? Could you take a screenshot of the font setting screen in Control Center?

![obraz](https://user-images.githubusercontent.com/39202451/182618209-ea43687b-7f6a-47c4-9667-ba6e38240425.png)

I'm using Ubuntu font(https://design.ubuntu.com/font/), but the issue reproduces with default Noto Sans

**Comment by xuqi27837288** [comment]
You can try again on the latest version to see if the problem persists

**Comment by raspin0** [comment]
> You can try again on the latest version to see if the problem persists

The issue persists on latest version of deepin 20.8 and voice notes `5.10.23`

**Comment by xuqi27837288** [comment]
deepin v20 will not be updated, and this issue will be closed
