### ISSUE TITLE
Deepin doesn't recognize Canon scanners

### ISSUE THREAD

**Issue by Octavian-Q** [linuxdeepin/developer-center#3335]
### SUMMARY | 问题概要

Can't use Canon scanner doesn't seem to be recognized by Deepin applications 

### STEPS TO REPRODUCE | 复现步骤

1. Connected the scanner to the PC
2. Opened the Simple Scan app
3. Scanner is not shown there 
![Screenshot_simple-scan_20220729131523](https://user-images.githubusercontent.com/98664445/181739503-0b417a75-d9a9-44a8-b619-097986d0a0c3.png)

### OBSERVED RESULT | 观察到的结果

![Screenshot_deepin-terminal_20220729131433](https://user-images.githubusercontent.com/98664445/181739388-629eb81f-63f4-4343-b985-b095e3f74954.png)
Apparently, Deepin knows a Canon device is connected to the PC

### EXPECTED RESULT | 期望的结果

Scanner works in Deepin

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Deepin 20.6
Scanner: Canon LiDE 400

**Comment by arch-user-france1** [comment]
You simply don't have any driver for this installed. Please don't open issues if you haven't searched the web before.

https://askubuntu.com/questions/490601/install-canon-scanner
One post suggest installing: sudo apt-get install sane xsane xsane-common sane-utils libsane libsane-common libsane-dbg libsane-dev libsane-extras libsane-extras-common libsane-extras-dbg libsane-extras-dev
Another one says it's incompatible: http://www.sane-project.org/sane-mfgs.html#Z-CANON

**Comment by Octavian-Q** [comment]
> You simply don't have any driver for this installed. Please don't open issues if you haven't searched the web before.
> 
> https://askubuntu.com/questions/490601/install-canon-scanner One post suggest installing: sudo apt-get install sane xsane xsane-common sane-utils libsane libsane-common libsane-dbg libsane-dev libsane-extras libsane-extras-common libsane-extras-dbg libsane-extras-dev Another one says it's incompatible: http://www.sane-project.org/sane-mfgs.html#Z-CANON (you should take a look if your device is supported there)

Those Libraries (libsane-common libsane-dbg libsane-dev libsane-extras libsane-extras-common libsane-extras-dbg libsane-extras-dev) aren't available in Deepin (since you posted from ubuntu maybe there they are) and there is't an easy way to add them (maybe through ppa but that again not the safe way to do it in Deepin). And I opened this as an issue because it is an issue. I am not in Deepin from yesterday but for years, and it really lacks for some libraries to make a proper driver install on Scanners.

**Comment by Zeno-sole** [comment]
You can try installing sane-pixma

**Comment by Octavian-Q** [comment]
> You can try installing sane-pixma http://www.sane-project.org/man/sane-pixma.5.html

With apt package not found, and from GitHub couldn’t build dependencies

**Comment by Zeno-sole** [comment]
You can build from source

**Comment by arch-user-france1** [comment]
> You can build from source

The whole repository should be updated. It's horribly outdated I think. Even Chromium is dangerously outdated I think.

**Comment by arch-user-france1** [comment]
And snap is from whatever version where it makes apparmor consume too much RAM, snap doesn't work at all btw.
Can install things but they won't be start-able. So the command htop couldn't be found even after installation.

**Comment by Zeno-sole** [comment]
You need a higher version of snap, you can try to update the snap
