### ISSUE TITLE
Deepin doesn't recognize fingerprint sensor as a Biometric Authentication device

### ISSUE THREAD

**Issue by Octavian-Q** [linuxdeepin/developer-center#3336]
### SUMMARY | 问题概要

I have a fingerprint sensor connected to the PC and is not detected by Deepin Biometric Authentication settings

### STEPS TO REPRODUCE | 复现步骤

1. Connected fingerprint sensor to the pc
2. Tested if is shown in USB connected devices list (It is) 
![Screenshot_deepin-terminal_20220729132728](https://user-images.githubusercontent.com/98664445/181740900-b2ff7b41-5c88-418e-abaa-d0551ceb8651.png)
(I am not sure exactly what model it is because is purchased from china website without package) 

### OBSERVED RESULT | 观察到的结果

Deepin doesn't show fingerprint sensor as a Biometric Authentication method
![Screenshot_dde-control-center_20220729132746](https://user-images.githubusercontent.com/98664445/181741151-396f2540-3207-40c6-93db-abe0ad93d5e5.png)
 

### EXPECTED RESULT | 期望的结果

Fingerprint sensor work

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Deepin 20.6 up to date 
Kernel 5.15

**Comment by arch-user-france1** [comment]
The fingerprinter is not compatible by default: https://askubuntu.com/questions/1176615/how-to-configure-an-elan-fingerprint-scanner-on-an-asus-ux430a-laptop

**Comment by arch-user-france1** [comment]
You should not buy propietary trash in the future. 
The driver is propietary - look up if it works first, then buy it

https://ubuntuforums.org/showthread.php?t=2368242

**Comment by Octavian-Q** [comment]
> The fingerprinter is not compatible by default: https://askubuntu.com/questions/1176615/how-to-configure-an-elan-fingerprint-scanner-on-an-asus-ux430a-laptop
First, that's Ubuntu (and an old version v18) and Deepin is not Ubuntu. 
Second, did you read the reply at least? It uses old v0.82 default and since 0.99 compatibility was added

**Comment by arch-user-france1** [comment]
1. Deepin is Debian, Ubuntu is Debian. Both is the same, just a tiny bit different.
2. Deepin uses the version 0.8.2-1+eagle

**Comment by raspin0** [comment]
> You should not buy propietary trash in the future. The driver is propietary - look up if it works first, then buy it

That's a bad argument. I won't waste my time searching for deepin compatible hardware. Everything I buy should work out-of-the box, like it does on Windows.

**Comment by BLumia** [comment]
> Everything I buy should work out-of-the box, like it does on Windows.

I've heard UOS (the commercial/paid version of deepin) has the ability to install drivers automately so it may behave like Windows. I don't have it installed since it's non-free.

We do need to update the fprintd package, though.

**Comment by arch-user-france1** [comment]
> > You should not buy propietary trash in the future. The driver is propietary - look up if it works first, then buy it
> 
> That's a bad argument. I won't waste my time searching for deepin compatible hardware. Everything I buy should work out-of-the box, like it does on Windows.

I rather think you have a wrong attitude. You can disturb the company for not making proper Linux drivers - not my problem and not the Linux community's problem at all. Then you wouldn't have to open an issue post.

**Comment by BLumia** [comment]
@arch-user-france1 I don't understand, why a thumb down?

**Comment by arch-user-france1** [comment]
> > Everything I buy should work out-of-the box, like it does on Windows.
> 
> I've heard UOS (the commercial/paid version of deepin) has the ability to install drivers automately so it may behave like Windows. I don't have it installed since it's non-free.
> 
> We do need to update the fprintd package, though.

If there are no drivers they won't get installed and if there is an outdated package it won't get magically refreshed.

The devs must do it, can you assign someone like you usually do?

**Comment by BLumia** [comment]
> If there are no drivers they won't get installed and if there is an outdated package it won't get magically refreshed.

The UOS doesn't share the very same repo as deepin so *maybe* UOS have a proper driver :/

The base package repo is the same, though.

**Comment by Octavian-Q** [comment]
@arch-user-france1 you are making too much waves on proprietary vs open source things. Many distros offer users to install proprietary apps/drivers and what that means? They are bad? No

**Comment by arch-user-france1** [comment]
> @arch-user-france1 you are making too much waves on proprietary vs open source things. Many distros offer users to install proprietary apps/drivers and what that means? They are bad? No

I don't understand what you mean. Of course they are bad.
1. There is no reason to not make code open source unless you want to hide that you are stealing people's data
2. These often don't get updated quickly enough and don't work for newer kernels
3. There is always the risk that the driver is not respecting your privacy
4. Often these drivers don't work with their own hardware such as the Broadcom drivers - on Windows it works but the Linux drivers are bad, or the Nvidia drivers are trash, often there are some refresh rate drops (monitor refresh rate) for no reason.
5. Security vulnerabilities, bugs and mssing features can't be fixed/added to the driver by it's community, another reason to make things open source.

Everything propietary should be called "propietary trash" - Windows is trash too, Apple too....
There are countless things on the market which are trash.

**Comment by Octavian-Q** [comment]
> > @arch-user-france1 you are making too much waves on proprietary vs open source things. Many distros offer users to install proprietary apps/drivers and what that means? They are bad? No
> 
> I don't understand what you mean. Of course they are bad.
> 
> 1. There is no reason to not make code open source unless you want to hide that you are stealing people's data
> 2. These often don't get updated quickly enough and don't work for newer kernels
> 3. There is always the risk that the driver is not respecting your privacy
> 4. Often these drivers don't work with their own hardware such as the Broadcom drivers - on Windows it works but the Linux drivers are bad, or the Nvidia drivers are trash, often there are some refresh rate drops (monitor refresh rate) for no reason.
> 5. Security vulnerabilities, bugs and mssing features can't be fixed/added to the driver by it's community, another reason to make things open source.
> 
> Everything propietary should be called "propietary trash" - Windows is trash too, Apple too.... There are countless things on the market which are trash.
> 
> Since Linux is open source, drivers won't be added to the kernel anyway so they won't work out of the box. There would not be a need to make those installers if drivers would have to be open source.

Alright, if you said so, perhaps you never used in your life Discord, Steam or Spotify because they are trash. Go open source, your opinion is not a general public truth, just your choice. (GitHub is owned by Microsoft by the way)

**Comment by raspin0** [comment]
> > @arch-user-france1 you are making too much waves on proprietary vs open source things. Many distros offer users to install proprietary apps/drivers and what that means? They are bad? No
> 
> I don't understand what you mean. Of course they are bad.
> 
>     1. There is no reason to not make code open source unless you want to hide that you are stealing people's data
> 
>     2. These often don't get updated quickly enough and don't work for newer kernels
> 
>     3. There is always the risk that the driver is not respecting your privacy
> 
>     4. Often these drivers don't work with their own hardware such as the Broadcom drivers - on Windows it works but the Linux drivers are bad, or the Nvidia drivers are trash, often there are some refresh rate drops (monitor refresh rate) for no reason.
> 
>     5. Security vulnerabilities, bugs and mssing features can't be fixed/added to the driver by it's community, another reason to make things open source.
> 
> 
> Everything propietary should be called "propietary trash" - Windows is trash too, Apple too.... There are countless things on the market which are trash.
> 
> Since Linux is open source, drivers won't be added to the kernel anyway so they won't work out of the box. There would not be a need to make those installers if drivers would have to be open source.

I think you've got an ideology bias. There are benefits to proprietary software e.g.: 
1. You can sell the code 
2. You may not want people to use your work for free
3. You don't want increased maintenance expenditures
4. You want to retain absolute ownership over your work
5. You may have secrets/patents to hide

Nonetheless, I'm pretty sure the driver has been reverse-engineered already, deepin just doesn't ship it yet.

**Comment by BLumia** [comment]
Hi, please keep the discussion on-topic. We'll check if we can update the fprintd package next week. Thanks!

**Comment by Zeno-sole** [comment]
[deb.zip](https://github.com/linuxdeepin/developer-center/files/9238431/deb.zip)
I built libfprint version 1.94.2, you can install it and see if it works

**Comment by Octavian-Q** [comment]
> [deb.zip](https://github.com/linuxdeepin/developer-center/files/9238431/deb.zip) I built libfprint version 1.94.2, you can install it and see if it works

Fingerprint sensor still is not recognized (it has some troubles with proprietary drivers on Linux as I researched) by Deepin Biometric Authentication. But, with new library seems my face recognition Logitech Brio camera seems to work better. So, when will be ready its good to roll in release branch too.
