### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by arch-user-france1** [linuxdeepin/developer-center#3338]
### SUMMARY | 问题概要

There is a grammar bug in the main page

### STEPS TO REPRODUCE | 复现步骤

1. Open the main page GitHub.com/linuxdeepin
2. Go to get started with deepin
3. Search for a comma which is wrong.

### OBSERVED RESULT | 观察到的结果

grammar issues

### EXPECTED RESULT | 期望的结果

no grammar issues

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Yeah sure

### ADDITIONAL INFORMATION | 额外补充

It's in 1. ...

**Comment by BLumia** [comment]
Feel free to send a PR to fix that :)

https://github.com/linuxdeepin/.github/blob/master/profile/README.md

**Comment by arch-user-france1** [comment]
I don't want to sign the CLA but I submitted a pull request.

**Comment by BLumia** [comment]
We cannot merge it without signing a CLA. If that's not okay for you then you can close that PR and I'll do the fix next Monday.

Still thanks for the patch tho.

**Comment by arch-user-france1** [comment]
Yeah please do that. It's not worth it reading all that text for me now - the contribution is not large and it might take as long as I needed searching the web for the comma rules after and etc.
It's just the one comma which is a typo and some other "problems". At least the comma should be fixed.

Thanks.

**Comment by arch-user-france1** [comment]
Here's my patch: https://github.com/arch-user-france1/.github/tree/patch-1

**Comment by BLumia** [comment]
Should be fixed now :)
