### ISSUE TITLE
Deepin dock pops up when playing full screen games 

### ISSUE THREAD

**Issue by PCPete68** [linuxdeepin/developer-center#3339]
### SUMMARY | 问题概要

Deepin Dock keeps popping up while in fullscreen games. It doesn’t matter which mode I have the dock set to, always hide, show etc. 

deepin-dock 5.5.9.1-3
kwin 5.25.3-1
Arch

This issue was closed ages ago and was mentioned that upgrading dock would fix it. As you can see mine is a lot more upto date than previous reported but I am still suffeing from the popping up of the dock.

### STEPS TO REPRODUCE | 复现步骤

Play full screen game. Some times the dock pops up when I think the mouse pointer hits the bottom of the screen. Other times I have noticed it pops up with a key press, e, the shift, alt, control key are some keys this happened with. Games are proton / steam non native to linux and just standard wine none native games. Although I have noticed it does not happen with a really old game I play, Dungeons and dragons online. 

### OBSERVED RESULT | 观察到的结果

The dock pops up. Sometimes goes away, sometimes stayed and have to alt tab out of game and back again. 

### EXPECTED RESULT | 期望的结果

Play full screen games with out intrusive dock popping up. 

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin-dock 5.5.9.1-3
kwin 5.25.3-1
Arch

**Comment by arch-user-france1** [comment]
Happens if the mouse is captured.

**Comment by PCPete68** [comment]
> arch-user-france1

I am not sure what you mean. The games should capture the mouse, yes but it is not. Not all games have that option either so in fullscreen games it is usually done automatically. I don't get this problem in other desktop environments, gnome, cinnamon etc.

**Comment by arch-user-france1** [comment]
I didn't mean it is the game fault. I meant that this usually happens if the mouse is captured by the game and moved a little bit.
There's a bug in the Deepin code.

**Comment by PCPete68** [comment]
> I didn't mean it is the game fault. I meant that this usually happens if the mouse is captured by the game and moved a little bit. There's a bug in the Deepin code.

No, no I wasn't implying you did mean that. I just put it in there to help clear up / elaborate on problem. I did assume there was a bug and thats why I posted this in hopes it may get fixed.

**Comment by PCPete68** [comment]
So an update to my situation. 
After some advise from arch wiki forum I was looking at some things on my system and noticed that, deepin-kwin 5.4.26-3 and kwin 5.25.3-1 (plasma) are installed. Is that normal or maybe the cause of my prob?

To experiment, I removed deepin-kwin and the problem was gone. That created other problems for me though as features are now gone that I use a lot, eg: no tiling windows when going to border of screen and missing features in control centre. Re-installing deeping-kwin and the problem raises it head again.

I thought I would put the updated info here as it may point someone that may be able to help, in the right direction. Looking like a bug in deepin-kwin as problem goes when it is not installed.

**Comment by babyfengfjx** [comment]
According to the above problem description, we have not found similar problems on the deepin distribution, there may be some occasional problems on the arch maintenance branch, thank you very much for sharing this information here, maybe in the subsequent version can help us further improve.

**Comment by kreon28** [comment]
> To experiment, I removed deepin-kwin and the problem was gone. That created other problems for me though as features are now gone that I use a lot, eg: no tiling windows when going to border of screen and missing features in control centre. Re-installing deeping-kwin and the problem raises it head again.

To have transparency dock and tiling windows after removing deepin-kwin and dependencies, install deepin-wm.

**Comment by kreon28** [comment]
> According to the above problem description, we have not found similar problems on the deepin distribution, there may be some occasional problems on the arch maintenance branch, thank you very much for sharing this information here, maybe in the subsequent version can help us further improve.

It is constant problem with arch distro. As soon as new packages of plasma-group upgrade are ready, deepin-kwin stops working. Deepin-kwin cannot manage to follow changes with Kwin, and it is due to rolling-distro like arch .

**Comment by babyfengfjx** [comment]
I apologize for the prolonged lack of effective confirmation for this issue. Currently, deepin has entered the V23 version stage, and updates for the V20 version will no longer be provided. Therefore, we will close this issue for now. If you encounter similar or other problems while using the V23 version, please don't hesitate to provide feedback. Thank you very much.
