### ISSUE TITLE
Samba share too slow

### ISSUE THREAD

**Issue by vampywiz17** [linuxdeepin/developer-center#3341]
### SUMMARY | 问题概要

If i open a Mounted Samba share, it too much time to open it.

### STEPS TO REPRODUCE | 复现步骤

1. Mount a samba share
2. Open it with file manager

### OBSERVED RESULT | 观察到的结果

The file manager is slow, 30 sec or more loading time if the folder contain more file.

### EXPECTED RESULT | 期望的结果

Mutch faster working.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Deepin V20.6

### ADDITIONAL INFORMATION | 额外补充

Other Linux distros like Debian or Ubuntu the SMB file share management is mutch faster. I dont know the reason why too slow in Deepin.

**Comment by BLumia** [comment]
It's probably not related to distro but desktop environment. Which DE are you using on Debian or Ubuntu? Also, if you install `nautilus` under deepin and use that to access Samba share, will that become faster than using deepin's `dde-file-manager`?

**Comment by vampywiz17** [comment]
@BLumia 

I'm using Gnome all other Distro.

Now i try with terminal (cifs-utils) and it fast! So yes, it is DE (dde-file-manager) problem

**Comment by BLumia** [comment]
Could you also try `nautilus` (can be installed via `sudo apt install nautilus`) since it's both based on `gio` (and nautilus is the default file manager under GNOME)? If nautilus is fast but dde-file-manager isn't then it's definitely a implementation issue.

**Comment by vampywiz17** [comment]
I make a screen record.

First is the dde-file-manager mounting, the second is same SMB share, but monted with cifs-utils via terminal.

![Felvétel_Terület kiválasztása_20220801123024](https://user-images.githubusercontent.com/14281430/182129773-57dff629-2794-41a9-9a32-f7652cec2cac.gif)

**Comment by arch-user-france1** [comment]
Can you run a speed-test from your notebook and send the output of lscpu?

**Comment by vampywiz17** [comment]
@arch-user-france1 

```
vamp@vamp-Notebook:~$ speed-test 

       Ping   24 ms
   Download   25 Mbps
     Upload   31 Mbps

```

```
vamp@vamp-Notebook:~$ lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       39 bits physical, 48 bits virtual
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               69
Model name:          Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
Stepping:            1
CPU MHz:             1742.742
CPU max MHz:         2900,0000
CPU min MHz:         800,0000
BogoMIPS:            4988.40
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            3072K
NUMA node0 CPU(s):   0-3
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts md_clear flush_l1d
```

**Comment by arch-user-france1** [comment]
@BLumia definitely an implementation issue.

**Comment by SuperEffie** [comment]
Thanks for your feedback. When you open a directory containing multiple files under the smb service, and the response is slow. We have repeated the problem. We will tell the developer to locate or optimize it.

**Comment by SuperEffie** [comment]
We have optimized this issue in v23 beta. You can try using v23 beta to help us verify. Currently, we need to close the issue regarging to v20. If you encounter any issues during the use of v23 beta, please feel free to provide us with more feedback.
The link we tracked in pms is https://pms.uniontech.com/bug-view-184821.html
