### ISSUE TITLE
dde-introduction 缺少社区版本的tag

### ISSUE THREAD

**Issue by Rabenda** [linuxdeepin/developer-center#3346]
### SUMMARY | 问题概要

https://mirrors.tuna.tsinghua.edu.cn/deepin/pool/main/d/dde-introduction/
显示有5.6.35这个版本 但是
https://github.com/linuxdeepin/dde-introduction
最新只有5.6.0.2 这个版本 缺少tag同步

### STEPS TO REPRODUCE | 复现步骤

--2022-08-02 06:57:56--  https://github.com/linuxdeepin/dde-introduction/archive/5.6.35.tar.gz
Resolving github.com... 20.205.243.166
Connecting to github.com|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/linuxdeepin/dde-introduction/tar.gz/5.6.35 [following]
--2022-08-02 06:57:56--  https://codeload.github.com/linuxdeepin/dde-introduction/tar.gz/5.6.35
Resolving codeload.github.com... 20.205.243.165
Connecting to codeload.github.com|20.205.243.165|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-08-02 06:57:57 ERROR 404: Not Found.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

dde-introduction 5.6.35

**Comment by BLumia** [comment]
想起来了个信息，感觉有必要补充到这里（虽然 commitmsg 提到过）：

这个项目之前在 gerrit 开发维护的过程中，可能往里放过单个文件大小大于 100M 的文件（很可能是 introduction 用的视频文件）导致超过了 GitHub 的限制，于是在项目迁移到 GitHub 的过程中选择了 squash merge 的形式合入了那个阶段的记录。

所以这个 tag 对应的 commit 在 GitHub 上是不会找到的了（（（

**Comment by justforlxz** [comment]
5.6.35 这个 tag 是处理压缩前最终一次提交的，对应的提交其实是 https://github.com/linuxdeepin/dde-introduction/commit/18644011fbdef9bd33ebf6272a2c7b9e914ccf02 如果非要打包，可以将这个提交认为是 5.6.35

之后开发会转移到 github 上继续，文件会限制在 github 的允许范围内。
