### ISSUE TITLE
Shortcuts.go produce too many logs

### ISSUE THREAD

**Issue by avently** [linuxdeepin/developer-center#335]
I looked at my system logs and found that this line produce hundreds lines of log https://github.com/linuxdeepin/dde-daemon/blob/master/keybinding/shortcuts/shortcuts.go#L109
Something like this:
shortcuts.go:109: getAccel failed shortcut: stop, pa: XF86Stop, err: not found keycode

Maybe would be a good idea to comment this line because it's hard to find really usefull info in logs with this line

**Comment by avently** [comment]
I'm not 100% sure but maybe that line of code is the cause of slow load after i log in.
So, what i'm doing:
Starting my Manjaro Deepin. Entering password. Then i see wallpaper and nothing more for about 20 seconds. Meanwhile i can see logs in another console:
journalctl --system --user -e 
Every line of log is    shortcuts.go:109: getAccel failed shortcut:   ......

**Comment by hualet** [comment]
@electricface

**Comment by electricface** [comment]
I changed to logger.Debugf
