### ISSUE TITLE
DDE Launcher doesn't show .desktop file at menu

### ISSUE THREAD

**Issue by eduardomozart** [linuxdeepin/developer-center#3355]
### SUMMARY | 问题概要

Hello,
I compiled the ZapZap application through Source Code (instructions here: https://github.com/rafatosta/zapzap/issues/76) and it saves the zapzap binary to ''$HOME/.local/bin".
When I copy the "https://github.com/rafatosta/zapzap/blob/main/share/applications/com.rtosta.zapzap.desktop"  file to "$HOME/.local/share/applications", it doesn't show up at DDE Launcher until I edit the "Exec"  line to include the Full Path to zapzap executable (in my case, "/home/Eduardo/.local/bin/zapzap"), instead, the icon isn't shown at DDE Launcher.
But it's strange because when I create a executable to a Wine application with "Exec=wine /home/eduardo/.wine/drive_c/Outlive/Outlive.exe" (sample here: https://www.vivaolinux.com.br/dica/Alterar-programa-padrao-para-arquivos-no-Deepin), I noticed that the shortcut show up at DDE Launcher just fine. So I'm not sure if DDE Launcher checks if the executable is found at $PATH variable or somewhere to check if the executable at "Exec"  line is available before showing it up at the DDE Launcher menu. I added the line:

``
export PATH="$HOME/.local/bin:$PATH"
``

At the end of "$HOME/.bashrc" file and rebooted the machine. I can run zapzap just fine through the Terminal just calling it (zapzap), but it doesn't show up into the DDE Launcher until I specify the full path to the executable at "Exec"  line. So I would like to know if there's a way for me not specify the full path to an Exec file and if it's a bydefault approach or a bug.

### STEPS TO REPRODUCE | 复现步骤

Create a ".desktop"  file without specifying the full path at "Exec" line to an executable installed to the local user only ($HOME/.local/bin).

### OBSERVED RESULT | 观察到的结果

The DDE Launcher do not show up the shortcut.

### EXPECTED RESULT | 期望的结果

The DDE Launcher should find the executable at $PATH variable and allow it to show up.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Distribution: Deepin 20.6.

### ADDITIONAL INFORMATION | 额外补充

Please let me know if there's any log I can provide.

**Comment by BLumia** [comment]
It's because `$HOME/.local/share/` is not in `XDG_DATA_DIRS`, and it should be fixed in https://github.com/linuxdeepin/startdde/pull/106, will also add this to 20.7 milestone :)
