### ISSUE TITLE
$PATH variable do not include "$HOME/.local/bin" path

### ISSUE THREAD

**Issue by eduardomozart** [linuxdeepin/developer-center#3356]
### SUMMARY | 问题概要

Hello,
I noticed that the Deepin has a "$HOME/.profile" file that attempts to add the "$HOME/.local/bin" folder to the $PATH variable if the path "$HOME/.local/bin" exists, but it doesn't seems to be added to my system, so I had to edit the "$HOME/.bashrc"  file directly to append the "$HOME/.local/bin"  directory to the path variable so I can run the executables that I compiled manually through Terminal to my actual user just calling it's executable name instead of it's full path.

### STEPS TO REPRODUCE | 复现步骤

Compile an application locally (sample: https://github.com/rafatosta/zapzap/issues/76).

### OBSERVED RESULT | 观察到的结果

When I run the executable through Terminal I have to specify full path ($HOME/.local/bin/zapzap) instead of executable name only (zapzap).

### EXPECTED RESULT | 期望的结果

I have to run the executable through the full path manually or append the "$HOME/.local/bin" to $PATH by editing the file "$HOME/.bashrc" directly.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Distribution: Deepin 20.6

### ADDITIONAL INFORMATION | 额外补充

Please let me know if any more information are needed.

**Comment by BLumia** [comment]
Related: https://github.com/linuxdeepin/developer-center/issues/2368
Should be fixed in: https://github.com/linuxdeepin/startdde/pull/107 (no tag release yet so hopefully should be in the next release)

**Comment by eduardomozart** [comment]
Hello @BLumia, I added the fix manually to the /etc/X11/Xsessions.d/01deepin-profile and it works just fine. I removed my customization from $HOME/.bashrc file. Thanks!
