### ISSUE TITLE
Authorization request after log in and language changes

### ISSUE THREAD

**Issue by avently** [linuxdeepin/developer-center#336]
Updated to lastest versions of all Deepin apps from Manjaro's repo. 
Now when i logging in to system a window with authorization request show up (after i already entered a password!). If i click Cancel the system freezes for 1 minute 10 seconds (i counted). I can't do anything.
You added new feature that can help to change language - Shift + Alt shortcut. This feature produce this authorization window too! It insane. If i want to change the language with shortcut i need to enter the password. Even if i enter it correctly the system freezes for 1 minute 10 seconds...
Can you take a look at your code and find this bug?

**Comment by avently** [comment]
I downgrade deepin-daemon to 3.1.11-1 and authorization window dissapeared. But when i try to change keylayout by pressing Shift+Alt the system freezes. Maybe thats why the system freezes after logging in. Deepin tries to change keylayout. If i will remove deepin-daemon then no startup freeze at all! I checked it too.

**Comment by hualet** [comment]
@jouyouyun @electricface

**Comment by jouyouyun** [comment]
Update `deepin-daemon` to `3.1.13`

**Comment by avently** [comment]
@jouyouyun i built dde-daemon from source and the authorization screen dissapeared. But freeze after i log in and after keybourd layout changes still exist.

**Comment by avently** [comment]
Even if i change this value: com.deepin.dde.keyboard.layout  via Dconf system is freezing.
After pressing Super + Shift i see this in log:
авг 02 18:10:30 linux dde-osd[5604]: show osd "DirectSwitchLayout"
авг 02 18:10:30 linux dde-osd[5604]: current layout changed to:  "ru;"

And nothing more about 20 seconds of freeze. Can you suggest me what to do?

**Comment by jouyouyun** [comment]
Update deepin-desktop-schemas, or exec 'killall dde-session-daemon;/usr/lib/deepin-daemon/dde-session-daemon', then paste the outputs.

**Comment by avently** [comment]
@jouyouyun freeze was after this line:
<info> utils_bluez.go:343: bluezWatchRestart &{/org/freedesktop/DBus org.freedesktop.DBus 0xc4203eb5f0 map[] {0 0}}
[log.txt](https://github.com/linuxdeepin/developer-center/files/1200453/log.txt)

**Comment by avently** [comment]
@jouyouyun i had been building dde-daemon without one of the modules. The problem was with inputdevices. When i skipped initialization of this module there was no freeze. But of course language switch is not working.

**Comment by jouyouyun** [comment]
The module `inputdevices` is no problem from your `log.txt`. Have you upgrade `dde-control-center` and `dde-session-ui`?

**Comment by jouyouyun** [comment]
Exec 'killall dde-session-daemon;/usr/lib/deepin-daemon/dde-session-daemon -v' to debug

**Comment by avently** [comment]
@jouyouyun I have deepin-session-ui 4.0.13-3
deepin-control-center 4.2.3-4. There are no updates.

**Comment by jouyouyun** [comment]
`dde-control-center` has new version 4.2.5

**Comment by jouyouyun** [comment]
Try move `/usr/lib/deepin-daemon/dde-osd` to other directory, then test whether freeze again, thanks!

**Comment by avently** [comment]
This is with -v option

[second_log.txt](https://github.com/linuxdeepin/developer-center/files/1203692/second_log.txt)

**Comment by jouyouyun** [comment]
No error found. How about the cpu usage and memory usage when freeze?
I'm in arch, please check your packages version according to my attachment, thanks!
[dde_in_arch.txt](https://github.com/linuxdeepin/developer-center/files/1203709/dde_in_arch.txt)

**Comment by avently** [comment]
Manjaro packages will be updated a little bit later than arch packages.
startdde 3.1.14-1
deepin-daemon 3.1.16-1
deepin-api 3.1.11-1
deepin-desktop-schemas-manjaro 3.1.15-1
deepin-control-center 4.2.3-4
deepin-session-ui 4.0.13-3
deepin-wm 1.9.14-1
deepin-wm-switcher 1.1.2-1
deepin-metacity 3.22.10-1

Hm, i rechecked keylayout change after renaming dde-osd and now there is no freeze and no layout change working. Need to reboot computer to check

**Comment by avently** [comment]
@jouyouyun how will I know cpu usage while screen is freezed? First second after freeze cpu usage is higher. 
And yes, there is no freeze if I use super+shift. If I change layout via settings screen is freezing as before.

**Comment by jouyouyun** [comment]
Open a terminal, then exec `top`, keep the terminal showing, then to change layout in dde-control-center.
And Pay attention to cpu/memory changes in top.

**Comment by avently** [comment]
@jouyouyun when I said freezing I mean I can move mouse cursor but screen is not changing at all. It looks like an image so "top" or "htop" can't help

**Comment by avently** [comment]
new info. I started downloading a file in browser and when 80 mb was downloaded i did: 
killall dde-session-daemon;/usr/lib/deepin-daemon/dde-session-daemon -v

after two or three minutes screen was unfreezed and downloaded size was 160 mb. So the file had been downloading while screen didn't work like it should. I will test this behaviour with Manjaro Deepin livecd. Maybe it is my fault.

**Comment by avently** [comment]
@jouyouyun i'm so sorry. It was a problem with ~/.Xmodmap file. I don't know why this file exist but after deleting it the problem goes away. Now when i'm switching layout there is no freeze but Shift + Alt and Super + Space is not working. I use gxneur that can use Shift + Alt and can change layout. Thank you for you time.

Also i wanted to ask you maybe you can test it on your system. When i use SublimeText, for example, Ctrl + C (or X or V) is not working if russian keylayout is enabled. If i change it to english everything is ok. Also those combinations work not right in Deepin Terminal with russian keylayout. Is it normal in Linux?
