### ISSUE TITLE
[deepin-terminal] get an invalid value when copying sometimes

### ISSUE THREAD

**Issue by kt286** [linuxdeepin/developer-center#3362]
### SUMMARY | 问题概要

get an invalid value when copying sometimes （build with master branchs）

### STEPS TO REPRODUCE | 复现步骤

https://user-images.githubusercontent.com/10684972/182772987-451b0281-6f48-4abb-b3be-4fbcfdb22795.mp4

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin 20.6
deepin-terminal 5.4.32

**Comment by BLumia** [comment]
Not sure if it's caused by the modified qtermwidget. Could you test if `qterminal` or [`dtng`](https://github.com/BLumia/deepin-terminal-ng) also have this issue? Thanks!

**Comment by kt286** [comment]
No problem in qterminal

**Comment by babyfengfjx** [comment]
这终端的版本我们用的最新是5.4.28，这个32版本是从哪里获取得？
暂时5.4.28版本还没发掘有这类问题。

**Comment by kt286** [comment]
编译的 master 分支代码

**Comment by kt286** [comment]
fixed https://github.com/linuxdeepin/deepin-terminal/commit/b5cb5cb2a234698e366cdc48b9f9b2998e05e0c9
