### ISSUE TITLE
文件管理器，多标签页，切换标签页时，会自动刷新文件列表

### ISSUE THREAD

**Issue by linuxlionking** [linuxdeepin/developer-center#3365]
### SUMMARY | 问题概要

如题，在某标签页中，定位到了某个文件。当从其他标签页切回时，列表被刷新，还需重新定位目标文件。

### STEPS TO REPRODUCE | 复现步骤

1 打开2个或以上标签页，在其中一个中，找个包含文件较多的目录，通过滚动条，找到某个文件

2  切换到其他标签页后，再切回刚才标签页

### OBSERVED RESULT | 观察到的结果

文件列表被刷新，刚才找到的文件，需重新定位

### EXPECTED RESULT | 期望的结果

文件列表不变化

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

dde-file-manager/apricot,now 5.6.8-1 amd64 [已安装，自动]

**Comment by babyfengfjx** [comment]
这个现象不知道自己理解对了没，是按照这个模式左边的这个会刷新么？
是否方便也整一个动态图？
![Peek 2022-08-16 15-04](https://user-images.githubusercontent.com/24642999/184818182-4f3d770a-7091-4dd9-a679-ef591306aff8.gif)

**Comment by BLumia** [comment]
> 这个现象不知道自己理解对了没，是按照这个模式左边的这个会刷新么？

看描述应该是【多标签】的情况，Ctrl + T 新建标签，不是两个窗口。

**Comment by babyfengfjx** [comment]
soga  了解，这是个问题，感谢兄台反馈，我们及时跟踪，后续版本优化上：
![222](https://user-images.githubusercontent.com/24642999/184820273-a8f77153-5a6c-4a5b-8664-612633a9626d.gif)

**Comment by vivianxf** [comment]
感谢您的反馈哦，我们已经提单跟踪，欢迎您后续有问题随时反馈

**Comment by vivianxf** [comment]
在pms已经有问题单在跟踪，目前处于需求评审状态，后续有进展同步更新
![image](https://github.com/linuxdeepin/developer-center/assets/96415804/8a07b898-16d2-457b-8cbe-ebf88a70a93c)
