### ISSUE TITLE
DDE 应用构建 option 需要标准化

### ISSUE THREAD

**Issue by wineee** [linuxdeepin/developer-center#3378]
### SUMMARY | 问题概要

# 1. 版本号

大部分项目使用的是 VERSION， 

dde-control-center 使用 CVERSION
gio-qt 使用 PROJECT_VERSION

部分项目写死了 VERSION 但不积极更新：
比如 https://github.com/linuxdeepin/dde-dock/blob/master/CMakeLists.txt#L3

另外很多库的 pkg-config 和 config.cmake 都不重视版本号（无论生成还是导入时），应该维护好版本号，以后 api 变了可以用版本号来判断，而不是让移植开发者编译失败了再去看代码才行。

另外 set (VERSION "1.0.0" CACHE STRING "define project version") 好像不错

# 2. 关闭 WAYLAND 支持的选项

目前 DDE 很多项目 wayland 支持无法在其他发行版编译，需要 option 可选去掉 wayland

 一个例子是 dde-session-shell 使用的 USE_DEEPIN_WAYLAND

- [x] deepin-system-monitor https://github.com/linuxdeepin/deepin-system-monitor/pull/161
- [x] dde-clipboard https://github.com/linuxdeepin/dde-clipboard/pull/110

# 3. 单元测试的选项

image-editor,deepin-album:   DOTEST
deepin-compressor:  USE_TEST
deepin-music 似乎是: ISTEST
...
还有很多项目没有 option

单元测试默认开关每个项目可以自己定，但希望使用一个统一命名的 option 管理单元测试 

# 4 使用 option 而不要直接判断 define

直接判断 define 无论 -DDISABLE_SYS_UPDATE=ON,-DDISABLE_SYS_UPDATE=OFF 实际效果一样，有误导性。而且 cmake 可能会提示没有应用这个参数。

涉及： https://github.com/linuxdeepin/dde-control-center/blob/4345f42b788565b180c98f4cbd6d77969e2c1242/src/frame/CMakeLists.txt#L34-L67

# 5 介绍文档

大多数项目没有介绍编译选项的文档， 尤其是 dde-control-center 这种选项很多的需要

TODO： 可以在 [deepin wiki 写](https://wiki.deepin.org/zh/%E5%BC%80%E5%8F%91%E8%80%85%E6%8C%87%E5%8D%97/DDE%E6%A1%8C%E9%9D%A2%E7%A7%BB%E6%A4%8D/%E5%89%8D%E8%A8%80)

**Comment by BLumia** [comment]
CMake 项目的单元测试选项应该用 `BUILD_TESTING` 吧。[如果使用 CTest 的话，这个选项是默认会提供的选项](https://cmake.org/cmake/help/latest/module/CTest.html)，如果不用 CTest 的话也建议使用这个，尽可能和现有选项保持一致。

**Comment by AppleOfGray** [comment]
deepin wiki文档已经修改位置, 原有链接 404 了
[移植 DDE 桌面环境_新地址](https://wiki.deepin.org/zh/前言)
