### ISSUE TITLE
deepin file manager error

### ISSUE THREAD

**Issue by gionno** [linuxdeepin/developer-center#338]
with a Right click on any of the marked circles causes an error and the file manager closes

![alt text](http://i63.tinypic.com/2e0ussj.png)

this is the error:

`lug 17 18:08:27 vmware-pc kernel: dde-file-manage[1502]: segfault at 8 ip 00007f5b3fa09dc5 sp 00007ffdb55eda50 error 4 in libQt5Widgets.so.5.9.1[7f5b3f8c2000+626000]
lug 17 18:08:27 vmware-pc systemd[1]: Started Process Core Dump (PID 1512/UID 0).
lug 17 18:08:29 vmware-pc systemd-coredump[1513]: Process 1502 (dde-file-manage) of user 1000 dumped core.
                                                  
                                                  Stack trace of thread 1502:
                                                  #0  0x00007f5b3fa09dc5 _ZN7QAction10setEnabledEb (libQt5Widgets.so.5)
                                                  #1  0x00007f5b40b09d33 _ZN12FileIconItem20popupEditContentMenuEv (libdde-file-manager.so.1)
                                                  #2  0x00007f5b3e7018af _ZN11QMetaObject8activateEP7QObjectiiPPv (libQt5Core.so.5)
                                                  #3  0x00007f5b3fa358b6 _ZN7QWidget26customContextMenuRequestedERK6QPoint (libQt5Widgets.so.5)
                                                  #4  0x00007f5b3fa50c01 _ZN7QWidget5eventEP6QEvent (libQt5Widgets.so.5)
                                                  #5  0x00007f5b3fb3360f _ZN6QFrame5eventEP6QEvent (libQt5Widgets.so.5)
                                                  #6  0x00007f5b3e6d189c _ZN23QCoreApplicationPrivate29sendThroughObjectEventFiltersEP7QObjectP6QEvent (libQt5Core.so.5)
                                                  #7  0x00007f5b3fa0de28 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                                  #8  0x00007f5b3fa166d0 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                                  #9  0x00007f5b40644fab _ZN3Dtk6Widget12DApplication6notifyEP7QObjectP6QEvent (libdtkwidget.so.1)
                                                  #10 0x00007f5b3e6d1bd0 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                                  #11 0x00007f5b3fa6b093 n/a (libQt5Widgets.so.5)
                                                  #12 0x00007f5b3fa6d691 n/a (libQt5Widgets.so.5)
                                                  #13 0x00007f5b3fa0de4c _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                                  #14 0x00007f5b3fa15926 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                                  #15 0x00007f5b40644fab _ZN3Dtk6Widget12DApplication6notifyEP7QObjectP6QEvent (libdtkwidget.so.1)
                                                  #16 0x00007f5b3e6d1bd0 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                                  #17 0x00007f5b3f2491e4 _ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE (libQt5Gui.so.5)
                                                  #18 0x00007f5b3f24ad46 _ZN22QGuiApplicationPrivate24processWindowSystemEventEPN29QWindowSystemInterfacePrivate17WindowSystemEventE (libQt5Gui.so.5)
                                                  #19 0x00007f5b3f2224ac _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Gui.so.5)
                                                  #20 0x00007f5b26dadcc1 n/a (libQt5XcbQpa.so.5)
                                                  #21 0x00007f5b3cbd0a57 g_main_context_dispatch (libglib-2.0.so.0)
                                                  #22 0x00007f5b3cbd0c88 n/a (libglib-2.0.so.0)
                                                  #23 0x00007f5b3cbd0d1c g_main_context_iteration (libglib-2.0.so.0)
                                                  #24 0x00007f5b3e72c061 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                                  #25 0x00007f5b3e6cfffb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                                  #26 0x00007f5b3e6d9048 _ZN16QCoreApplication4execEv (libQt5Core.so.5)
                                                  #27 0x000000000040b7f9 main (dde-file-manager)
                                                  #28 0x00007f5b3db1d4ca __libc_start_main (libc.so.6)
                                                  #29 0x000000000040c26a n/a (dde-file-manager)
                                                  
                                                  Stack trace of thread 1503:
                                                  #0  0x00007f5b3dbe0e9d poll (libc.so.6)
                                                  #1  0x00007f5b3b6968e0 n/a (libxcb.so.1)
                                                  #2  0x00007f5b3b698679 xcb_wait_for_event (libxcb.so.1)
                                                  #3  0x00007f5b26d4972a n/a (libQt5XcbQpa.so.5)
                                                  #4  0x00007f5b3e4ee15b n/a (libQt5Core.so.5)
                                                  #5  0x00007f5b3bdd2049 start_thread (libpthread.so.0)
                                                  #6  0x00007f5b3dbeaf0f __clone (libc.so.6)
                                                  
                                                  Stack trace of thread 1504:
                                                  #0  0x00007f5b3dbe0e9d poll (libc.so.6)
                                                  #1  0x00007f5b3cbd0c09 n/a (libglib-2.0.so.0)
                                                  #2  0x00007f5b3cbd0d1c g_main_context_iteration (libglib-2.0.so.0)
                                                  #3  0x00007f5b3e72c061 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                                  #4  0x00007f5b3e6cfffb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                                  #5  0x00007f5b3e4e940e _ZN7QThread4execEv (libQt5Core.so.5)
                                                  #6  0x00007f5b3e4ee15b n/a (libQt5Core.so.5)
                                                  #7  0x00007f5b3bdd2049 start_thread (libpthread.so.0)
                                                  #8  0x00007f5b3dbeaf0f __clone (libc.so.6)
                                                  
                                                  Stack trace of thread 1505:
                                                  #0  0x00007f5b3dbe0e9d poll (libc.so.6)
                                                  #1  0x00007f5b3cbd0c09 n/a (libglib-2.0.so.0)
                                                  #2  0x00007f5b3cbd0d1c g_main_context_iteration (libglib-2.0.so.0)
                                                  #3  0x00007f5b3e72c061 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                                  #4  0x00007f5b3e6cfffb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                                  #5  0x00007f5b3e4e940e _ZN7QThread4execEv (libQt5Core.so.5)
                                                  #6  0x00007f5b3eed5396 n/a (libQt5DBus.so.5)
                                                  #7  0x00007f5b3e4ee15b n/a (libQt5Core.so.5)
                                                  #8  0x00007f5b3bdd2049 start_thread (libpthread.so.0)
                                                  #9  0x00007f5b3dbeaf0f __clone (libc.so.6)
                                                  
                                                  Stack trace of thread 1506:
                                                  #0  0x00007f5b3dbe0e9d poll (libc.so.6)
                                                  #1  0x00007f5b3cbd0c09 n/a (libglib-2.0.so.0)
                                                  #2  0x00007f5b3cbd0d1c g_main_context_iteration (libglib-2.0.so.0)
                                                  #3  0x00007f5b3cbd0d61 n/a (libglib-2.0.so.0)
                                                  #4  0x00007f5b3cbf7ae5 n/a (libglib-2.0.so.0)
                                                  #5  0x00007f5b3bdd2049 start_thread (libpthread.so.0)
                                                  #6  0x00007f5b3dbeaf0f __clone (libc.so.6)
                                                  
                                                  Stack trace of thread 1508:
                                                  #0  0x00007f5b3dbe0e9d poll (libc.so.6)
                                                  #1  0x00007f5b3cbd0c09 n/a (libglib-2.0.so.0)
                                                  #2  0x00007f5b3cbd0d1c g_main_context_iteration (libglib-2.0.so.0)
                                                  #3  0x00007f5b3e72c061 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                                  #4  0x00007f5b3e6cfffb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                                  #5  0x00007f5b3e4e940e _ZN7QThread4execEv (libQt5Core.so.5)
                                                  #6  0x00007f5b3e4ee15b n/a (libQt5Core.so.5)
                                                  #7  0x00007f5b3bdd2049 start_thread (libpthread.so.0)
                                                  #8  0x00007f5b3dbeaf0f __clone (libc.so.6)
                                                  
                                                  Stack trace of thread 1509:
                                                  #0  0x00007f5b3bdd84ed pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                                                  #1  0x00007f5b3e4ef4a1 _ZN14QWaitCondition4waitEP6QMutexm (libQt5Core.so.5)
                                                  #2  0x00007f5b3e4ea586 n/a (libQt5Core.so.5)
                                                  #3  0x00007f5b3e4ee15b n/a (libQt5Core.so.5)
                                                  #4  0x00007f5b3bdd2049 start_thread (libpthread.so.0)
                                                  #5  0x00007f5b3dbeaf0f __clone (libc.so.6)
                                                  
                                                  Stack trace of thread 1507:
                                                  #0  0x00007f5b3dbe0e9d poll (libc.so.6)
                                                  #1  0x00007f5b3cbd0c09 n/a (libglib-2.0.so.0)
                                                  #2  0x00007f5b3cbd0fa2 g_main_loop_run (libglib-2.0.so.0)
                                                  #3  0x00007f5b3d1b8546 n/a (libgio-2.0.so.0)
                                                  #4  0x00007f5b3cbf7ae5 n/a (libglib-2.0.so.0)
                                                  #5  0x00007f5b3bdd2049 start_thread (libpthread.so.0)
                                                  #6  0x00007f5b3dbeaf0f __clone (libc.so.6)`

**Comment by ag14774** [comment]
Same here

**Comment by oberon2007** [comment]
No issue for me. Which version or **deepin-file-manager** are you using?

**Comment by gionno** [comment]
i'm using deepin-file-manager  1:4.1.7.20170713-1 but i have the same problem with previous versions

**Comment by gionno** [comment]
solved with deepin-file-manager  1:4.2.0-2
Thank you! ^_^
