### ISSUE TITLE
trouble with install libgcc-s1 pakage

### ISSUE THREAD

**Issue by AaBbdev29** [linuxdeepin/developer-center#3380]
### SUMMARY | 问题概要

I try to install libgcc-s1 pakage cause a few app need this pakage to install and run , but ,It removes these  packages after installation
"cryptsetup
 cryptsetup-initramfs
 dde dde-desktop
 dde-disk-mount-plugin
 dde-file-manager
 deepin-font-manager
  libdde-file-manager"

### STEPS TO REPRODUCE | 复现步骤

1-installing libgcc-s1
2-remove these apps
 "cryptsetup
 cryptsetup-initramfs
 dde dde-desktop
 dde-disk-mount-plugin
 dde-file-manager
 deepin-font-manager
  libdde-file-manager"
3- Desktop clutter
removing multitasking button 
and file manger ,

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin 20.6 .
libgcc-s1

**Comment by Zeno-sole** [comment]
20.6 will not update the version of gcc, please use the v23 version, this version has libgcc-s1

**Comment by Zeno-sole** [comment]
https://cdimage.deepin.com/releases/23-preview/

**Comment by BLumia** [comment]
Additionally: v23 is still in preview status and not recommend to use in production before the final stable release is out.

**Comment by AaBbdev29** [comment]
beta versions should be much more buggy ?!!

**Comment by BLumia** [comment]
> beta versions should be much more buggy ?!!

That's why it called "beta" or "preview". We'll eventually have a stable release once we're ready :)
