### ISSUE TITLE
deepin在ALT+TAB 切换不同程序出现问题 

### ISSUE THREAD

**Issue by mahmut-Abi** [linuxdeepin/developer-center#3385]
### SUMMARY | 问题概要

deepin20.6
企业微信wine版
在ALT+TAB切换不同窗口时，会出现后台运行的企业微信图标（非最小化），但没有窗口（本就不该有窗口）。
概率性出现，出现概率大概为70%。

### STEPS TO REPRODUCE | 复现步骤

启动企业微信就有，第一次打开什么都不做关闭（最小化）就不会出现，后面就随机出现，概率蛮大，影响工作。

### EXPECTED RESULT | 期望的结果

希望得到改善

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin20.6 所有包都是最新的

**Comment by BLumia** [comment]
deepin wine 版还是普通 wine 的？

**Comment by mahmut-Abi** [comment]
deepin 商店下的企业微信，看进程是deepin-wine6-stable 这个版本的wine

**Comment by mahmut-Abi** [comment]
![image](https://user-images.githubusercontent.com/96514873/185549084-ef84363e-cafe-4fbf-8aa7-eb562d6d34a4.png)

**Comment by BLumia** [comment]
cc @babyfengfjx

**Comment by mahmut-Abi** [comment]
help啊，看着好难受，你们是没法复现么，deepin我重装过几次，问题一直都在

**Comment by mahmut-Abi** [comment]
@babyfengfjx

**Comment by xuqi27837288** [comment]
@mahmut-Abi  请问一下企业微信是用的4.0.16.6007deepin18版本吗？方便的话可以把操作录屏一下，我们本地尝试复现一下这个问题~

**Comment by mahmut-Abi** [comment]
com.qq.weixin.work.deepin/unknown,now 4.0.16.6007deepin18 i386 这个版本。

**Comment by billchenchina** [comment]
同样有这个问题

**Comment by mahmut-Abi** [comment]
![image](https://user-images.githubusercontent.com/96514873/211229451-72c64076-10b4-4e7f-8866-229de931d07b.png)

视频不好录，就是alt+tab切换应用时会出先这个
企业微信版本：com.qq.weixin.work.deepin/unknown,now 4.0.16.6007deepin18 i386
系统版本：20.8 (但应该跟系统关系不大，好几个版本一直都有这个问题)

**Comment by babyfengfjx** [comment]
是说已经关闭了企业微信聊天窗口，但是通过alt+tab切换时，还是会出现企业微信的图标是吧？
这个时候切换并选中企业微信图标，然后放开会有什么现象么？能够有窗口出来不？

**Comment by mahmut-Abi** [comment]
选中放开不会有企业微信弹出来，还是原来的界面，这是个概率性问题，20.6，20.7版本比较频繁，20.8好了很多。
在刚开机和刚打开企业微信的时候出现的比较频繁，如果开机很久再打开企业微信出现频率就没那么高了。

**Comment by xuqi27837288** [comment]
20.8上尝试复现几次，没有频繁的出现，我们先关闭处理，后续有其他问题可以随时提交~谢谢~

**Comment by mahmut-Abi** [comment]
好的
