### ISSUE TITLE
Browser Translation Typo (English)

### ISSUE THREAD

**Issue by tylerslnd** [linuxdeepin/developer-center#3386]
### SUMMARY | 问题概要

In the default Deepin browser, the feature "Internet Explorer Compatibility" has a minor typo when English is system language.

### STEPS TO REPRODUCE | 复现步骤

1. Open Deepin Browser
2. Go to settings  ( chrome://settings )
3. Go to "Advanced" on sidebar
4. Look for "Internt Explorer Compatibility" on options page

### OBSERVED RESULT | 观察到的结果

The feature is spelled "Internt Explorer Compatibility"

### EXPECTED RESULT | 期望的结果

This feature should be spelled "Internet Explorer Compatibility"

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Distribution: Deepin Community 20.6
Browser Version 6.0.5 (Official Build) (64 Bit) (93.0.4577.63)

### ADDITIONAL INFORMATION | 额外补充

Relevant screenshot:
![image](https://user-images.githubusercontent.com/102410084/185607436-96c2329e-e50e-4c7a-b4f9-e209278cf4d0.png)

**Comment by babyfengfjx** [comment]
Thank you for your feedback, we will follow up in a timely manner, and thank you for submitting other questions at any time!

**Comment by SuperEffie** [comment]
Thanks for your feedback. This problem does exist in the browser under version 6.0.5. However, we will release the latest version  at the end of this month.Deepin will be upgraded to v20.7, and the browser will be upgraded to 6.0.14. This problem has been fixed. Please look forward to it.
Welcome to provide us with more feedback~
![6 0 14](https://user-images.githubusercontent.com/58986464/186317259-837bdf78-9fa8-4f8e-94c3-0a07290a7fe2.png)
