### ISSUE TITLE
Deepin File Manager - missing popup fingerprint

### ISSUE THREAD

**Issue by shannara** [linuxdeepin/developer-center#339]
I install Deepin Desktop Environment on fresh Arch Linux, i note that sftp connection not working in Deepin File Manager, but connection work in Terminal.

Tested also on Deepin 15.4.1 in VirtualBox, same workflow :
- try connection in Deepin File Manager, not working
- connection in Terminal, accept only fingerprint
- retry in Deepin File Manager, ask credentials.

Deepin File Manager not show popup to allow fingerprint :/.

![deepin-screen-recorder_desktop_20170723171454](https://user-images.githubusercontent.com/6418090/28500572-f3d88b16-6fca-11e7-8843-fdc97a2399d7.gif)

**Comment by carlosal1015** [comment]
@shannara At this moment [I have transferred files](https://forum.manjaro.org/t/using-sftp-with-port-in-deepin-file-manager/38426) from one place to another and I have no problems.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
