### ISSUE TITLE
2 * pessimizing move

### ISSUE THREAD

**Issue by dcb314** [linuxdeepin/developer-center#3390]
### SUMMARY | 问题概要

A development version of gcc can be made to say:

types/linkinfolist.cpp:86:21: warning: moving a local object in a return statement prevents copy elision [-Wpessimizing-move]

Source code is

    return std::move(info);

types/sinkinfolist.cpp:86:21: warning: moving a local object in a return statement prevents copy elision [-Wpessimizing-move]

Duplicate.

It looks like a code rewrite will make the code go faster.

### STEPS TO REPRODUCE | 复现步骤

Build git version off gcc. Compile package.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Linux fedora 5.18.17-200.fc36.x86_64

**Comment by BLumia** [comment]
Are you report to the wrong place? This is a repo related to deepin (whatever the distro or DDE/DTK apps. Your report seems not related to DDE/DTK or deepin at all.

**Comment by dcb314** [comment]
fedora has two websites to report bugs in deepin-qt-dbus-factory.

First is https://github.com/linuxdeepin/dde-qt-dbus-factory and you think I'm wrong.

Second is http://shuttle.corp.deepin.com/cache/repos/eagle/release-candidate/56qX566h6IGU6LCD5rWL6K-V6aqM6K-BMDUyMTQ5Mg/pool/main/d/dde-qt-dbus-factory/
and that seems dead.

I'd be grateful for any guidance where this bug report should be sent.

**Comment by BLumia** [comment]
You should mention it's related to the `deepin-qt-dbus-factory` package in the issue description :/

This is the correct place to report this issue then :)

**Comment by dcb314** [comment]
Thanks for clearing up my stupidity ;->

I tried to build version 5.4.20. I looked in the git repository and the code looked the same to me.

**Comment by BLumia** [comment]
Should be fixed now in https://github.com/linuxdeepin/dde-qt-dbus-factory/pull/213 thanks to @Rabenda :)
