### ISSUE TITLE
Deepin and Nvidia 390x legacy driver

### ISSUE THREAD

**Issue by FelixFester** [linuxdeepin/developer-center#3394]
### SUMMARY | 问题概要

Deepin is unable to recognize Nvidia GeForce 410M and it install on 410M drivers that's too new for 410M.
Also here is impossible to install that drivers from terminal, because when I tried that, I broke at 1 try whole system that was unable to boot, and grub.

### STEPS TO REPRODUCE | 复现步骤

1. Get the laptop Lenovo B570e.
2. Install Deepin with it's Nvidia default drivers.
3. Wait some days or some reboots.

### OBSERVED RESULT | 观察到的结果

After some days/reboots I'm getting "root account is locked" error with another error, that appears when I'm pressing Enter. And it says something like "Your GPU was ignored by Nvidia 5xx drivers".

### EXPECTED RESULT | 期望的结果

Technically it should work like in Ubuntu 22.04.1. Even Ubuntu 22.04.1 recognize such old GPU and install drivers **that works for this GPU** offline. 

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Deepin Linux 20.6

**Comment by Zeno-sole** [comment]
Are the drivers in the nvidia-graphics-drivers-legacy-390xx repository unavailable?

**Comment by Zeno-sole** [comment]
You can go to the official nvidia to download the corresponding driver  https://www.nvidia.cn/Download/index.aspx?lang=en
