### ISSUE TITLE
Replace libaom To libdav1d for better av1 accelerations

### ISSUE THREAD

**Issue by RuiKenichi** [linuxdeepin/developer-center#3399]
### SUMMARY | 问题概要

The problem is the performance of av1 and h264 is very bad no accelerations on my laptop

### STEPS TO REPRODUCE | 复现步骤

Please Update ffmpeg and enable options libdav1d and disable libaom
And use dav1d library instead of libaom for deepin movie

### OBSERVED RESULT | 观察到的结果

av1 codecs has no hardware accelerations.

### EXPECTED RESULT | 期望的结果

Replace libaom to libdav1d

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Distribution: Deepin v20.6
Package: deepin-movie, ffmpeg

### ADDITIONAL INFORMATION | 额外补充

I hope deepin changes base from debian to fedora or another linux distribution, which has a newer package version.

**Comment by BLumia** [comment]
> I hope deepin changes base from debian to fedora or another linux distribution, which has a newer package version.

I saw you post in the discussion board before. Although I didn't maintain these packages, I can still answer this. The packages in deepin v23 will be more up-to-date than v20 :)
