### ISSUE TITLE
DDE软件包列表

### ISSUE THREAD

**Issue by oahong** [linuxdeepin/developer-center#34]
有没有可能给出这样一个列表：
1. dde有哪些组成部分，及相互之间的依赖关系？
2. deepin应用有哪些？
3. 有哪些deepin开发的库（图形库、动态库等等，是dde或者deepin应用需要的）

**Comment by fasheng** [comment]
文档会有的，同时后面会对 gerrit 仓库进行分类以减少混乱～
目前简陋但直观的办法是：

1. 查看各个以 dde- 为前缀的项目 README，如 https://github.com/linuxdeepin/dde-daemon，或 dde
2. deepin应用列表
```
apps/deepin-feedback
apps/deepin-file-manager
apps/deepin-movie
apps/deepin-music
apps/deepin-screenshot
apps/deepin-terminal
```
3. 我们自己的开发库主要是 libdui(会更名为 libdtk) 和 go-lib，所依赖的其他库可以通过阅读 README 或 dpkg -s pkg 命令来得知

**Comment by tsuibin** [comment]
dde/dde-account-faces
 dde/dde-api
 dde/dde-control-center
 dde/dde-daemon
dde-daemon 
 dde/dde-desktop
 dde/dde-dock
 dde/dde-dock-applets
 dde/dde-file-manager
 dde/dde-help
 dde/dde-launcher
 dde/dde-session-ui
 dde/dde-workspace
 dde/libdui
 dde/startdde
startdde 
 linuxdeepin/dde-daemon
dde daemon	
 linuxdeepin/dde-workspace
