### ISSUE TITLE
Strange dock moving\blinking in autohide mode (modern & effective)

### ISSUE THREAD

**Issue by SaltyCyborg** [linuxdeepin/developer-center#340]
I think my GIF is better than my bad english.

![dock](https://user-images.githubusercontent.com/30511247/28695708-9a5a2d14-737c-11e7-8123-662168e19d7f.gif)

**Comment by electricface** [comment]
说中文就行了

**Comment by electricface** [comment]
不过我没遇到这个问题

**Comment by SaltyCyborg** [comment]
@electricface 奇怪的码头移动\闪烁在自动隐藏模式（现代＆有效）
我认为我的GIF比我的坏中文好。

**Comment by hualet** [comment]
can't reproduce here.
