### ISSUE TITLE
Vintage theme produces GTK Warnings

### ISSUE THREAD

**Issue by cherio** [linuxdeepin/developer-center#3403]
### SUMMARY | 问题概要

Package: deepin-icon-theme
Linux distribution: Arch

This is just a minor bug which does not seem to break anything but simply produces warnings.

====================
Vintage theme produces GTK Warnings as below
`(yad:91571): Gtk-WARNING **: 11:38:19.281: Theme directory apps/256 of theme Vintage has no size field`

I fixed this locally by removing missing directory references from the corresponding "index.theme" file, replacing the line

`Directories=actions/16,actions/22,actions/24,actions/64,apps/16,apps/24,apps/32,apps/48,apps/64,apps/96,apps/128,apps/256,devices/16,devices/24,devices/32,devices/48,devices/64,devices/96,devices/128,devices/256,mimetypes/16,mimetypes/24,mimetypes/32,mimetypes/48,mimetypes/64,mimetypes/96,mimetypes/128,mimetypes/256,places/16,places/22,places/24,places/32,places/48,places/64,places/96,places/128,places/256,status/20,status/48,status/64,emblems/24`

with the line where all */256 entries purged

`Directories=actions/16,actions/22,actions/24,actions/64,apps/16,apps/24,apps/32,apps/48,apps/64,apps/96,apps/128,devices/16,devices/24,devices/32,devices/48,devices/64,devices/96,devices/128,mimetypes/16,mimetypes/24,mimetypes/32,mimetypes/48,mimetypes/64,mimetypes/96,mimetypes/128,places/16,places/22,places/24,places/32,places/48,places/64,places/96,places/128,status/20,status/48,status/64,emblems/24`

### STEPS TO REPRODUCE | 复现步骤

This specific test is performed by simply running a GTK based program in terminal e.g.

`yad`
`geany`
`mousepad`

### OBSERVED RESULT | 观察到的结果

`
(yad:95054): Gtk-WARNING **: 11:58:08.750: Theme directory apps/256 of theme Vintage has no size field

(yad:95054): Gtk-WARNING **: 11:58:08.750: Theme directory devices/256 of theme Vintage has no size field

(yad:95054): Gtk-WARNING **: 11:58:08.753: Theme directory mimetypes/256 of theme Vintage has no size field

(yad:95054): Gtk-WARNING **: 11:58:08.753: Theme directory places/256 of theme Vintage has no size field
`

### EXPECTED RESULT | 期望的结果

No warnings

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Distribution: Arch Linux
Package: deepin-icon-theme 2021.11.24-1

**Comment by BLumia** [comment]
Thanks for the info, I'll test it later. btw, if you are familiar with this sort of issue and would like to help fixing it, please feel free to send a Pull Request :)
