### ISSUE TITLE
20.7 点击电源按钮 选择关机 选择取消 就出现了问题

### ISSUE THREAD

**Issue by 8MiYile** [linuxdeepin/developer-center#3405]
### SUMMARY | 问题概要

我不知道该怎么说 只知道是在要准备关机发现有事情没做完 然后就卡了 于是就Ctrl+Alt+F2再F1切换TTY 就恢复正常了

### STEPS TO REPRODUCE | 复现步骤

1. 点击电源按钮
2. 选择关机
3. 选择取消
4. 就出现了问题

### EXPECTED RESULT | 期望的结果

点击取消应当是返回那5个还是6个按钮的界面 什么关机重启之类的

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

System Deepin 20.7

**Comment by 8MiYile** [comment]
![截图_选择区域_20220902235705](https://user-images.githubusercontent.com/25455400/188192968-fc41bf60-49de-43f9-93f9-df68473a16e7.png)

**Comment by justforlxz** [comment]
是画面卡住了么？

**Comment by 8MiYile** [comment]
> 是画面卡住了么？

如果要解除卡顿 只能Ctrl+Alt F2再F1 才正常

**Comment by 8MiYile** [comment]
问题已在20.7.1解决 关闭
