### ISSUE TITLE
[20.7]文管"连接到远程服务器"无法输入":"符号，导致无法指定端口访问

### ISSUE THREAD

**Issue by AppJ-GS** [linuxdeepin/developer-center#3406]
### SUMMARY | 问题概要

"连接到远程服务器"无法输入":"符号，导致无法指定端口访问
使用浏览器访问正常;且收藏的服务器信息丢失

### STEPS TO REPRODUCE | 复现步骤

1.点击"连接到远程服务器"
2.输入ip地址
3.ip地址末尾输入":"符号
4.无法输入该字符

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

MinorVersion=20.7
OsBuild=11038.007
dde-file-manager                              5.6.9-1                              amd64

### ADDITIONAL INFORMATION | 额外补充

卸载了fcitx4，使用的是fcitx5

https://user-images.githubusercontent.com/39146681/188264811-3458e49b-1a9c-4907-b8ac-36adfce2e5ee.mp4

**Comment by xuqi27837288** [comment]
@AppJ-GS 感谢您反馈的问题，该问题我们已经记录并反馈给研发人员解决优化~
