### ISSUE TITLE
README 拼写错误

### ISSUE THREAD

**Issue by ArielHeleneto** [linuxdeepin/developer-center#3407]
### SUMMARY | 问题概要

[zh-CN](https://github.com/linuxdeepin/deepin-riscv/blob/master/README_zh-CN.md)

[environmen](https://github.com/linuxdeepin/deepin-riscv/blob/master/riscv64-build-environment-zh_CN.md) 该词汇拼写错误，应当拼写为 environment

### STEPS TO REPRODUCE | 复现步骤

不需要复现

### OBSERVED RESULT | 观察到的结果

拼写错误

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

无需系统环境

**Comment by BLumia** [comment]
可以考虑直接发 PR 改 :)

cc @Zeno-sole

**Comment by Zeno-sole** [comment]
[riscv64-build-environment-zh_CN](https://github.com/linuxdeepin/deepin-riscv/blob/master/riscv64-build-environment-zh_CN.md) 并没有拼错呀

**Comment by BLumia** [comment]
> [riscv64-build-environment-zh_CN](https://github.com/linuxdeepin/deepin-riscv/blob/master/riscv64-build-environment-zh_CN.md) 并没有拼错呀

看上去[在 README 里](https://github.com/linuxdeepin/deepin-riscv/blob/master/README_zh-CN.md#%E9%85%8D%E7%BD%AEriscv64-%E7%9A%84%E6%9E%84%E5%BB%BA%E7%8E%AF%E5%A2%83)。

**Comment by Zeno-sole** [comment]
已更新
