### ISSUE TITLE
Txt's not opening at first try from desktop

### ISSUE THREAD

**Issue by SaltyCyborg** [linuxdeepin/developer-center#341]
Another files runs from desktop normally
![deepin-screen-recorder_select area_20170728101308](https://user-images.githubusercontent.com/30511247/28695924-f709cfd2-737d-11e7-891d-cf3fb67c96c2.gif)

**Comment by JulianLai** [comment]
It happened when I was trying to open text file with gedit, too.
I have reported it before, too.
#308

**Comment by ag14774** [comment]
any updates on this?

**Comment by felixonmars** [comment]
No idea yet. Please let me know if you find any clue.

**Comment by JulianLai** [comment]
It has been fixed.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
