### ISSUE TITLE
pyqt5在deepin 20.3上设置窗口透明不起作用

### ISSUE THREAD

**Issue by myFirstway** [linuxdeepin/developer-center#3414]
### SUMMARY | 问题概要

在deepin 20.7上可以看到的效果是窗口透明可以看到窗口下的软件的内容，在deepin 20.3上以及20.3升级到的20.7上窗口是完全没有透明

### STEPS TO REPRODUCE | 复现步骤

执行以下代码:
```
import sys
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QLabel,QWidget,QGraphicsOpacityEffect
class draw_select_win (QWidget):
def init(self, *args, **kwargs):
self.app = QApplication(sys.argv)
super().init(*args, **kwargs)
self.stop = False
self.resize(80, 40)
# self.setWindowFlags(Qt.FramelessWindowHint) # 窗口无边框
self.setWindowOpacity(0.5) # 设置窗口透明度
# self.setAttribute(Qt.WA_TranslucentBackground) # 窗口透明

def mouseRelease(self ,ev):
self.stop = True

def draw(self, x,y,width,height):
print(x,y,width,height)
window.move(x,y)
window.resize(width,height)
window.show()

def show(self):
global window
window = QWidget()
window.move(0, 0)
# window.setWindowFlags(Qt.FramelessWindowHint|Qt.WindowStaysOnTopHint|Qt.ToolTip) # 窗口无边框
# window.setWindowFlags(Qt.FramelessWindowHint|Qt.WindowStaysOnTopHint) # 窗口无边框
window.setStyleSheet("background-color:rgba(255,0,0,0.5);")
window.setWindowOpacity(0.4) # 设置窗口透明度
window.mousePressEvent = self.mouseRelease
window.show()
sys.exit(self.app.exec_())

label = draw_select_win()
label.show()
```

### OBSERVED RESULT | 观察到的结果

![1662709879041](https://user-images.githubusercontent.com/7514693/189300466-f2afe806-c742-42d4-9b73-a7cf578edcbc.png)

![1662709942362](https://user-images.githubusercontent.com/7514693/189300473-51c9331b-bb79-4e27-891a-b3bb32159ac4.png)

### EXPECTED RESULT | 期望的结果

在deepin 20.3上有一下效果

![1662709879041](https://user-images.githubusercontent.com/7514693/189300466-f2afe806-c742-42d4-9b73-a7cf578edcbc.png)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Distribution:deepin v20.3

**Comment by BLumia** [comment]
看到你也开了个 discussion （#3413），并且这个应该不是 bug，所以先关掉 issue 了。
