### ISSUE TITLE
dde 桌面开始菜单全局模式下，搜索软件点开会打开搜索前位置的应用。

### ISSUE THREAD

**Issue by mahmut-Abi** [linuxdeepin/developer-center#3418]
### SUMMARY | 问题概要

dde 桌面开始菜单全局模式下，搜索软件点开会打开搜索前位置的应用。

### STEPS TO REPRODUCE | 复现步骤

dde 桌面开始菜单全局模式下，搜索软件点开会打开搜索前位置的应用。

### EXPECTED RESULT | 期望的结果

得到修复

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

PRETTY_NAME="Deepin 20.7"
NAME="Deepin"
VERSION_ID="20.7"
VERSION="20.7"

**Comment by BLumia** [comment]
全局模式是啥，全屏状态的开始菜单？

如果是的话，我按这个复现步骤在 v20.7 环境下无法复现此问题。

https://user-images.githubusercontent.com/10095765/190296596-05b061f4-b942-4970-b5a8-11a4c938eb06.mp4

请一定好好填写 Issue 模板提供的内容，不然别人没法复现是没法修复的。

**Comment by mahmut-Abi** [comment]
![Record_select-area_20220915101401](https://user-images.githubusercontent.com/96514873/190297474-d36a0a99-c95c-4e96-8c4f-d513bb78d763.gif)

**Comment by mahmut-Abi** [comment]
如果我不搜索，直接找到点开就没事

**Comment by BLumia** [comment]
按你的录屏确实可以复现了，仅限输入的搜索字符只有一个字符时可以复现。所以才一定要好好填写复现步骤，附带尽可能详细的信息，不然别人没法复现是没法处理的 :joy:

恰当的复现步骤描述：

## 复现步骤

1. 点击左下角图标，打开全屏状态的开始菜单屏幕
2. 在此状态下，鼠标悬停在任一已有项目上
3. 在搜索框输入关键词 `a`
4. 在检索到的结果中选择任一条目
5. 观察结果

## 观察到的结果

原本搜索前状态下，悬停的项目被打开

## 期望的结果

搜索后所选择的项目被打开

**Comment by BLumia** [comment]
cc @babyfengfjx

**Comment by SuperEffie** [comment]
感谢您的反馈，这个问题我们已经反馈给研发者了，目前问题较多，暂不能确定修复及推送时间，但我们会不断跟进的。
若问题得到修复，会在这里通知您的，欢迎您为我们提供更多好的建议~

**Comment by mahmut-Abi** [comment]
好的，谢谢

**Comment by Decodetalkers** [comment]
bug定位了下，应该是搜索页面多于一页会返回未搜索前的位置，引入位置在appgridview.cpp 489行，在多于两页返回了空的QModelIndex, 然后页面重置，gridview也响应了一次，前一次页面已经重置了，所以就拿到了鼠标事件在退出搜索页面的软件位置，bug大致定位到了，不过原来维护者为什么如此写什么目的这样写还需要花点时间去分析下。

**Comment by babyfengfjx** [comment]
> 

大佬这个问题是已经帮忙修复了么？我看上面有提交记录。

**Comment by Decodetalkers** [comment]
> > 
> 
> 大佬这个问题是已经帮忙修复了么？我看上面有提交记录。

emm, 但是还没有审。。。我一会儿问下

**Comment by mahmut-Abi** [comment]
大佬们真厉害，那我关issue了啊。

**Comment by Decodetalkers** [comment]
> 大佬们真厉害，那我关issue了啊。

还没解决呢，先别关

**Comment by BLumia** [comment]
我先 reopen 一下，等相关的修改合入后会自动关闭掉的。

**Comment by mahmut-Abi** [comment]
好的

**Comment by Decodetalkers** [comment]
一分钟后合并，你编译验证下
安装依赖后
```bash
cmake -B build
cmake --build build
pkill dde-launcher
./build/dde-launcher
```
然后看看问题应该消失了
消失了你就可以关闭了，这个issue是否关闭应该让你验证

**Comment by BLumia** [comment]
:joy: 标 resolve 就会自动关的，如果验证没修复的话再重打开吧。
