### ISSUE TITLE
arch下字体大小改不了

### ISSUE THREAD

**Issue by xiayesuifeng** [linuxdeepin/developer-center#342]
arch下qt程序的字体大小死活改不了，只能改gtk程序的

**Comment by JulianLai** [comment]
我這邊只有暫時的解決方法，但也不是所有 Qt 程序都會套用，所以還是要等官方解決這個 BUG，不過看來是遙遙無期了

1. 安裝 qt5-styleplugins，如果找不到，在 AUR 有個 qt5-styleplugins-git 可以裝，但記得每次 Qt5 有更新時要重新 build，要不然會出錯
2. 在 `/etc/environment` 中加入 `QT_STYLE_OVERRIDE=gtk2`

之後只要調整完字體大小後重新登入應該就會有效果了，目前知道沒效果的地方有：dock 上面 app 的右鍵選單（譬如在 deepin-file-manager 圖示上按右鍵）、deepin-system-monitor

**Comment by hualet** [comment]
目前能够保证的是Gtk程序实时生效，Qt程序重启后生效；

**Comment by JulianLai** [comment]
@hualet 如果沒安裝 qt5-styleplugins 的話是不會生效的

**Comment by 1377195627** [comment]
@hualet 这个问题存在很久了，而且昨天撸了个环境变量管理器，然后我发现了个变量
![image](https://user-images.githubusercontent.com/8142265/28763979-9bf05f88-7587-11e7-8e0d-2549d719c023.png)
这个变量的值是空的，是不是跟这个有关

**Comment by zccrs** [comment]
@1377195627 QT_QPA_PLATFORM 这个环境变量不用设置，deepin的应用程序一般默认为 dxcb

**Comment by 1377195627** [comment]
@zccrs 我没设置这货，这货在启动qt程序的时候自己冒出来的，终端env压根就没这变量

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Nubia NX563J 发送_

**Comment by felixonmars** [comment]
@zccrs 我理解这个问题是因为

1. 新版 Qt 的 gtk2 主题插件在 AUR 里：qt5-styleplugins 暂时没在依赖里。
2. DDE 不知为何没能成功设置 gtk2 主题，即使安装了上面那个包。

如果 2 能解决，我可以试试去开倒车把 qt5-styleplugins 打回来……

**Comment by 1377195627** [comment]
@felixonmars 给qt设置gtk2主题？这貌似需要装一个啥gtk引擎才行，包名忘了，以前折腾qt5ct的时候给qt设置gtk主题就是要装一个包才行，不然qt没法直接用

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Nubia NX563J 发送_

**Comment by felixonmars** [comment]
@1377195627 请看我刚才说的第一点……

**Comment by 1377195627** [comment]
@felixonmars 额，，，，不是说能解决第2点就行了吗，

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Nubia NX563J 发送_

**Comment by felixonmars** [comment]
请稍微看仔细一点认真一点…

**Comment by zccrs** [comment]
@felixonmars 设置环境变量 QT_QPA_PLATFORMTHEME 为 gtk2 呢？

**Comment by felixonmars** [comment]
@zccrs 可以的，设置 QT_STYLE_OVERRIDE 也可以。

**Comment by JulianLai** [comment]
@zccrs @felixonmars 但我兩個設置後某些程序還是不會套用耶，就如同上面我貼的

**Comment by 1377195627** [comment]
@JulianLai QT_QPA....设置成dxcb事实

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Nubia NX563J 发送_

**Comment by zccrs** [comment]
@JulianLai 比如哪些程序？

**Comment by JulianLai** [comment]
@zccrs 
1. dock 上面 app 的右鍵選單（譬如在 deepin-file-manager 圖示上按右鍵）
![deepinscreenshot_20170731081245](https://user-images.githubusercontent.com/20014762/28758293-0c96c32c-75c8-11e7-810f-b9d2ed3a574f.png)

2. 提示視窗，例如：
![deepinscreenshot_20170731081136](https://user-images.githubusercontent.com/20014762/28758286-e508fe9c-75c7-11e7-84aa-39aca84bd409.png)
![deepinscreenshot_20170731081647](https://user-images.githubusercontent.com/20014762/28758324-a161cd94-75c8-11e7-8ecb-fb61a41d50af.png)

**Comment by hualet** [comment]
上面这些跟程序不响应控制中心字体大小设置不是一回事，这些是因为字体大小写死了；
在DDE里，QT程序的platformtheme应该会自动切到deepin提供的platformtheme（进而设置了gtk2为默认的style）才对；感觉跟上面哪个QT_QPAT_PLATFORMTHEME环境变量被清空有关？

**Comment by felixonmars** [comment]
设置 QT_QPA_PLATFORMTHEME=deepin 也不能正确显示主题，只能设置成 QT_QPA_PLATFORMTHEME=gtk2。看来问题出在 deepin 提供的 platformtheme 没有设置 style 为 gtk2？

**Comment by felixonmars** [comment]
顺着这个思路找到问题了，qt5integration 代码中用的是 Qt 5.6 及以前版本的老 style 名 "GTK+"，新的 qt5-styleplugins 中的 gtk2 主题名叫 "gtk2"，所以设置失败了。

补丁已提交：https://cr.deepin.io/25147

Arch 包已经在 deepin-qt5integration 0.2.2-2 中临时 workaround。

**Comment by felixonmars** [comment]
@JulianLai 对，加到 qt5integration 的直接依赖了，因为代码里直接用到了……

**Comment by jouyouyun** [comment]
@felixonmars is it fixed?

**Comment by hualet** [comment]
已经把几个字体大小写死的地方改了，应该大部分地方都没有问题了（除了ｌａｕｎｃｈｅｒ）

**Comment by JulianLai** [comment]
@hualet 還有這邊
![deepin _20171108174837](https://user-images.githubusercontent.com/20014762/32542324-2c37a212-c4ad-11e7-89a3-3ce45721882d.png)

**Comment by zccrs** [comment]
@JulianLai 是这俩对话框把字号写死了

**Comment by laichiaheng** [comment]
又發生類似狀況了

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
