### ISSUE TITLE
OCR工具页面缺陷

### ISSUE THREAD

**Issue by Winter-is-comingXK** [linuxdeepin/developer-center#3427]
### SUMMARY | 问题概要

![Screenshot_20220917_161832](https://user-images.githubusercontent.com/33370220/190847581-b63e7729-9753-4eab-9aea-21c5d85683cd.png)

如图可见，上方的白条

### STEPS TO REPRODUCE | 复现步骤

deepin-ocr /tmp/spectale/ocr.png

按照正常方式启动即可复现

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

软件:[deepin-ocr](https://github.com/linuxdeepin/deepin-ocr) master分支 [这次](https://github.com/linuxdeepin/deepin-ocr/commit/975040819368158e46c0d4730087efa1305b637d)提交后

系统版本:
![Screenshot_20220917_162408](https://user-images.githubusercontent.com/33370220/190847713-fbb71fa7-d515-4f3c-be2b-96ed68658fd2.png)

**Comment by Decodetalkers** [comment]
这个阴影是使用Qt的theme的，所以使用变色龙以外的主题就无法渲染。。修倒是好修

**Comment by BLumia** [comment]
非 DDE 环境（没使用 chameleon 主题的情况下）应该就会这样，我理解算是个 BUG 吧。

**Comment by BLumia** [comment]
@Decodetalkers 要 assign 给你吗？

p.s. 应该不是[这次](https://github.com/linuxdeepin/deepin-ocr/commit/975040819368158e46c0d4730087efa1305b637d)提交造成的，之前版本也这样。我倒是有个自用的完全去掉 DTK 依赖的版本，不过不急的话建议先等修吧 :joy:

**Comment by Decodetalkers** [comment]
> @Decodetalkers 要 assign 给你吗？
> 
> p.s. 应该不是[这次](https://github.com/linuxdeepin/deepin-ocr/commit/975040819368158e46c0d4730087efa1305b637d)提交造成的，之前版本也这样。我倒是有个自用的完全去掉 DTK 依赖的版本，不过不急的话建议先等修吧 :joy:

之前打算修，但是后来忘记了，不过修复了估计要到下下个版本？

**Comment by Winter-is-comingXK** [comment]
> 

该怎么修捏，我先自己修

**Comment by BLumia** [comment]
> 估计要到下下个版本？

不要紧，可以先准备好 patch/PR，不考虑到底啥时候能带出去。顺便，deepin-tweaks 首次发布的时候估计会带出去一些 dtk 的包，如果这个好修的话兴许很快就能带出去...吧

**Comment by Decodetalkers** [comment]
> > 
> 
> 该怎么修捏，我先自己修

在dtkwidget src/widgets/dshadowline.cpp 第57行

**Comment by Winter-is-comingXK** [comment]
修好了，在```src/mainwidget.cpp:101行```下面插入```mainWindow->setTitlebarShadowEnabled(false);```就可以了
![Screenshot_20220917_180933](https://user-images.githubusercontent.com/33370220/190851587-036eba16-34c6-4161-928a-b9ff0a59dbc6.png)

**Comment by Decodetalkers** [comment]
通过了应该就修好了，不过既然不使用icontheme了，这个文件放置位置也许要变化下

**Comment by Decodetalkers** [comment]
修好了，等dtkwidget更新吧。。
