### ISSUE TITLE
go-lib License被修改后冲突

### ISSUE THREAD

**Issue by ClayStan** [linuxdeepin/developer-center#3438]
### SUMMARY | 问题概要

go-lib 的 License 由 GPLv3+ 修改为 GPLv2，但是代码里的 copyright 段还是 GPLv3, 这产生了冲突 v3 和 v2 only 并不兼容，v3 和 v2+ 兼容后需要修改为 v3 协议发布, 为何需要从 v3 修改为 v2 ， 以及目前的协议冲突请处理

### STEPS TO REPRODUCE | 复现步骤

none

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

none

**Comment by zccrs** [comment]
@KT-lcz

**Comment by KT-lcz** [comment]
https://github.com/linuxdeepin/go-lib/pull/73
已经在上述pr中完成修改
