### ISSUE TITLE
Different copyright licenses in deepin-icon-theme

### ISSUE THREAD

**Issue by openarun** [linuxdeepin/developer-center#3443]
### SUMMARY | 问题概要

Hi there,
I found GPL-3+ in LICENSE file whereas LGPL-3+ in debian/copyright, archlinux/PKGBUILD .
Please acknowledge and let me know.
Thanks!

### STEPS TO REPRODUCE | 复现步骤

LICENSE file.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Distribution: Debian

**Comment by BLumia** [comment]
Should be GPL3+. License information in debian/copyright and archlinux/PKGBUILD now updated to GPL3+ as well :)
