### ISSUE TITLE
deepin-movie-reborn    test_mainwindow 1219 行编译错误。

### ISSUE THREAD

**Issue by wangwg1** [linuxdeepin/developer-center#3455]
### SUMMARY | 问题概要

test_mainwindow.cpp 1219行编译错误。报函数不存在，建议改为：
```
    struct MiracastDevice md;
    md.name = "test";
    md.uuid = "test1111111111111111111111111111111111111111111111111111";
    ItemWidget *item = mircastWgt->createListeItem(md, data, nullptr);
```

### STEPS TO REPRODUCE | 复现步骤

make

### OBSERVED RESULT | 观察到的结果

/data/home/wangwg/workspace/deepin/deepin-movie-reborn/tests/deepin-movie/common/test_mainwindow.cpp:1219:125: error: no matching function for call to ‘MircastWidget::createListeItem(const char [57], QByteArray&, std::nullptr_t)’
     ItemWidget *item = mircastWgt->createListeItem("test1111111111111111111111111111111111111111111111111111", data, nullptr);

### EXPECTED RESULT | 期望的结果

编译通过

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

qt5
deepin:20.7

**Comment by BLumia** [comment]
哪个项目？

**Comment by BLumia** [comment]
看上去已经给出了解决方案，欢迎 PR 哈 :)

**Comment by wangwg1** [comment]
好的，那我提交下。

**Comment by BLumia** [comment]
看到 PR 了，节后我转研发那边看下 :)

ps. commitlint 检查没过的问题，是因为有对 commit message 的格式要求，可以见 [深度百科上的 Commit 提交信息规范 页面](https://wiki.deepin.org/zh/%E5%BC%80%E5%8F%91%E8%80%85%E6%8C%87%E5%8D%97/%E8%A7%84%E8%8C%83%E6%96%87%E6%A1%A3/Commit-%E6%8F%90%E4%BA%A4%E4%BF%A1%E6%81%AF%E8%A7%84%E8%8C%83)。一个示例格式是：

```
fix: failed test at test_mainwindow.cpp

Resolve linuxdeepin/developer-center#3455.
```

**Comment by BLumia** [comment]
我帮你 squash 的形式合并进去了，以便使 commit 信息符合规范。感谢 PR 哈。有兴趣的话也可以来 `https://t.me/deepin_community` 看看 :)
