### ISSUE TITLE
#dtkwidget 

### ISSUE THREAD

**Issue by cheese** [linuxdeepin/developer-center#3456]
### SUMMARY | 问题概要

顶层共享库遵从 SONAME 版本号命名是很基本的共享库安装规范。目前发现一些共享库并没有遵守，希望 Deepin 能进行改进，并且未来引入的新共享库从一开始就按照这种规范来安装。

- [x] dde-control-center 中的 libdccwidgets.so https://github.com/linuxdeepin/dde-control-center/pull/1224
- [x] dde-network-core 中的 libdde-network-core.so https://github.com/linuxdeepin/dde-network-core/pull/140

### STEPS TO REPRODUCE | 复现步骤

编译安装相关软件包。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

- deepin-control-center 5.5.146
- deepin-network-core 1.0.63

**Comment by felixonmars** [comment]
除此之外，dtk 系列库等基础组件库目前虽然有设置 soname，但并没有在引入不兼容修改时更改soname。

建议参考： https://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html

**Comment by BLumia** [comment]
@Decodetalkers 已经在 https://github.com/linuxdeepin/dde-network-core/pull/140 调整过 network-core 的了，应该还差控制中心的

**Comment by Decodetalkers** [comment]
> @Decodetalkers 已经在 https://github.com/linuxdeepin/dde-network-core/pull/140 调整过 network-core 的了，应该还差控制中心的

控制中心很早就做了啊，当时炸了一批插件不是吗，如果是V20的话不在Github上

**Comment by BLumia** [comment]
> 当时炸了一批插件不是吗，如果是V20的话不在Github上

哦哦，我的疏忽。还找得到对应的 PR 或者 commit 吗？

**Comment by Decodetalkers** [comment]
> > 当时炸了一批插件不是吗，如果是V20的话不在Github上
> 
> 哦哦，我的疏忽。还找得到对应的 PR 或者 commit 吗？

https://github.com/linuxdeepin/dde-control-center/pull/1224

那么就差network-core合并就完成了

**Comment by BLumia** [comment]
network-core 的也合入了，就关闭掉了。如有新的项目需要做这件事的话，可以更新到 description 后重新打开此 issue 或者开新的 issue 进行跟进。
