### ISSUE TITLE
dde-file-manager 预览框文字重叠

### ISSUE THREAD

**Issue by wineee** [linuxdeepin/developer-center#3457]
### SUMMARY | 问题概要

![image](https://user-images.githubusercontent.com/22803888/194698183-577e7b4c-aa72-447b-b901-b59b707fe43a.png)

### STEPS TO REPRODUCE | 复现步骤

图片分辨率 503*411，且命名较长
1. 直接选中，空格预览，显示正常
![image](https://user-images.githubusercontent.com/22803888/194698332-699fb1fc-36ac-4915-ba50-5c288f6abad5.png)

2 . 先选中其他图片，空格预览，空格关闭预览，之后立即选中上述图片，空格预览，可以复现此bug

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

dde-file-manager 5.6.4

**Comment by xuqi27837288** [comment]
@wineee Thanks for the feedback problem, which has been recorded and fed back to the R&D staff for analysis and optimization ~
