### ISSUE TITLE
终端-自定义命令框显示不全

### ISSUE THREAD

**Issue by landv** [linuxdeepin/developer-center#3458]
### SUMMARY | 问题概要

终端-自定义命令框显示不全
![image](https://user-images.githubusercontent.com/11452861/194737117-08ebf9cd-99d5-4635-8886-ce17ed1c721f.png)
只有1号区域滚动显示，
2号区域没有占用。
旧版本没有问题，5.4.34有

### STEPS TO REPRODUCE | 复现步骤

终端-自定义命令框显示不全

### OBSERVED RESULT | 观察到的结果

终端-自定义命令框显示不全

### EXPECTED RESULT | 期望的结果

终端-自定义命令框显示完整

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

5.4.34

### ADDITIONAL INFORMATION | 额外补充

![image](https://user-images.githubusercontent.com/11452861/194737111-2ef693e1-718b-431e-8e4b-5c388206fc11.png)

**Comment by Decodetalkers** [comment]
git版本已经修复，不知道从什么地方引入的。。

**Comment by landv** [comment]
> git版本已经修复，不知道从什么地方引入的。。看到这个bug神奇就看了下，不过看起来现在git版本是没有问题了，解决的话就让他们新打个tag吧

用最新的编译了没卵用，编译出来和我现在用着的版本号一致，都是5.4.34。
坐等官方修复～～～

**Comment by Decodetalkers** [comment]
> > git版本已经修复，不知道从什么地方引入的。。看到这个bug神奇就看了下，不过看起来现在git版本是没有问题了，解决的话就让他们新打个tag吧
> 
> 用最新的编译了没卵用，编译出来和我现在用着的版本号一致，都是5.4.34。
> 坐等官方修复～～～

不该啊，我这里没问题

**Comment by landv** [comment]
> > > git版本已经修复，不知道从什么地方引入的。。看到这个bug神奇就看了下，不过看起来现在git版本是没有问题了，解决的话就让他们新打个tag吧
> > 
> > 
> > 用最新的编译了没卵用，编译出来和我现在用着的版本号一致，都是5.4.34。
> > 坐等官方修复～～～
> 
> 不该啊，我这里没问题

你多加几个自定义命令，就会出现这个蛋疼的问题，对了我的系统版本是
```txt
DISTRIB_ID=Deepin
DISTRIB_RELEASE=20.7
DISTRIB_DESCRIPTION="Deepin 20.7"
DISTRIB_CODENAME=apricot

```

**Comment by BLumia** [comment]
如果你俩都是 git HEAD 版的话，麻烦提供下所使用的 deepin-terminal 的 commit SHA，以及 DTK（至少 dtkcore，dtkwidget）版本（如果也是 git HEAD 版的话，commit SHA）？

**Comment by landv** [comment]
> 如果你俩都是 git HEAD 版的话，麻烦提供下所使用的 deepin-terminal 的 commit SHA，以及 DTK（至少 dtkcore，dtkwidget）版本（如果也是 git HEAD 版的话，commit SHA）？

https://github.com/linuxdeepin/deepin-terminal/commit/90731a6b712835d58ea1c8018fc471382b26f526
90731a6b712835d58ea1c8018fc471382b26f526

```shell
landv@win7-PC:/usr/lib/x86_64-linux-gnu$ ls -al libdtk*
lrwxrwxrwx 1 root root      20 6月  16 10:45 libdtkcore.so -> libdtkcore.so.5.5.32
lrwxrwxrwx 1 root root      20 6月  16 10:45 libdtkcore.so.5 -> libdtkcore.so.5.5.32
lrwxrwxrwx 1 root root      20 6月  16 10:45 libdtkcore.so.5.5 -> libdtkcore.so.5.5.32
-rw-r--r-- 1 root root 1136728 6月  16 10:45 libdtkcore.so.5.5.32
lrwxrwxrwx 1 root root      19 6月  16 10:46 libdtkgui.so -> libdtkgui.so.5.5.24
lrwxrwxrwx 1 root root      19 6月  16 10:46 libdtkgui.so.5 -> libdtkgui.so.5.5.24
lrwxrwxrwx 1 root root      19 6月  16 10:46 libdtkgui.so.5.5 -> libdtkgui.so.5.5.24
-rw-r--r-- 1 root root  552144 6月  16 10:46 libdtkgui.so.5.5.24
lrwxrwxrwx 1 root root      22 6月  16 10:47 libdtkwidget.so -> libdtkwidget.so.5.5.22
lrwxrwxrwx 1 root root      22 6月  16 10:47 libdtkwidget.so.5 -> libdtkwidget.so.5.5.22
lrwxrwxrwx 1 root root      22 6月  16 10:47 libdtkwidget.so.5.5 -> libdtkwidget.so.5.5.22
-rw-r--r-- 1 root root 3160168 6月  16 10:47 libdtkwidget.so.5.5.22
```
![image](https://user-images.githubusercontent.com/11452861/194748176-f01f2118-cf20-4952-b1bb-ddac00b0adce.png)

**Comment by Decodetalkers** [comment]
commit 20734b52995942fef45395222d6f5a312306ebf9
![image](https://user-images.githubusercontent.com/60290287/194748253-4d286ef0-4285-4667-b6a6-a01269dad7b9.png)
![image](https://user-images.githubusercontent.com/60290287/194748264-5ef84044-129e-4e2d-9812-e157be6faed6.png)
@BLumia @landv

**Comment by Decodetalkers** [comment]
> > 如果你俩都是 git HEAD 版的话，麻烦提供下所使用的 deepin-terminal 的 commit SHA，以及 DTK（至少 dtkcore，dtkwidget）版本（如果也是 git HEAD 版的话，commit SHA）？
> 
> [linuxdeepin/deepin-terminal@90731a6](https://github.com/linuxdeepin/deepin-terminal/commit/90731a6b712835d58ea1c8018fc471382b26f526) 90731a6b712835d58ea1c8018fc471382b26f526
> 
> ```shell
> landv@win7-PC:/usr/lib/x86_64-linux-gnu$ ls -al libdtk*
> lrwxrwxrwx 1 root root      20 6月  16 10:45 libdtkcore.so -> libdtkcore.so.5.5.32
> lrwxrwxrwx 1 root root      20 6月  16 10:45 libdtkcore.so.5 -> libdtkcore.so.5.5.32
> lrwxrwxrwx 1 root root      20 6月  16 10:45 libdtkcore.so.5.5 -> libdtkcore.so.5.5.32
> -rw-r--r-- 1 root root 1136728 6月  16 10:45 libdtkcore.so.5.5.32
> lrwxrwxrwx 1 root root      19 6月  16 10:46 libdtkgui.so -> libdtkgui.so.5.5.24
> lrwxrwxrwx 1 root root      19 6月  16 10:46 libdtkgui.so.5 -> libdtkgui.so.5.5.24
> lrwxrwxrwx 1 root root      19 6月  16 10:46 libdtkgui.so.5.5 -> libdtkgui.so.5.5.24
> -rw-r--r-- 1 root root  552144 6月  16 10:46 libdtkgui.so.5.5.24
> lrwxrwxrwx 1 root root      22 6月  16 10:47 libdtkwidget.so -> libdtkwidget.so.5.5.22
> lrwxrwxrwx 1 root root      22 6月  16 10:47 libdtkwidget.so.5 -> libdtkwidget.so.5.5.22
> lrwxrwxrwx 1 root root      22 6月  16 10:47 libdtkwidget.so.5.5 -> libdtkwidget.so.5.5.22
> -rw-r--r-- 1 root root 3160168 6月  16 10:47 libdtkwidget.so.5.5.22
> ```
> 
> ![image](https://user-images.githubusercontent.com/11452861/194748176-f01f2118-cf20-4952-b1bb-ddac00b0adce.png)

如果你开了旧版本的terminal, 那么似乎会从/usr/bin/deepin-termianl启动一个新的，所以你测试时候最好把terminal都关掉

**Comment by landv** [comment]
> > > 如果你俩都是 git HEAD 版的话，麻烦提供下所使用的 deepin-terminal 的 commit SHA，以及 DTK（至少 dtkcore，dtkwidget）版本（如果也是 git HEAD 版的话，commit SHA）？
> > 
> > 
> > [linuxdeepin/deepin-terminal@90731a6](https://github.com/linuxdeepin/deepin-terminal/commit/90731a6b712835d58ea1c8018fc471382b26f526) 90731a6b712835d58ea1c8018fc471382b26f526
> > ```shell
> > landv@win7-PC:/usr/lib/x86_64-linux-gnu$ ls -al libdtk*
> > lrwxrwxrwx 1 root root      20 6月  16 10:45 libdtkcore.so -> libdtkcore.so.5.5.32
> > lrwxrwxrwx 1 root root      20 6月  16 10:45 libdtkcore.so.5 -> libdtkcore.so.5.5.32
> > lrwxrwxrwx 1 root root      20 6月  16 10:45 libdtkcore.so.5.5 -> libdtkcore.so.5.5.32
> > -rw-r--r-- 1 root root 1136728 6月  16 10:45 libdtkcore.so.5.5.32
> > lrwxrwxrwx 1 root root      19 6月  16 10:46 libdtkgui.so -> libdtkgui.so.5.5.24
> > lrwxrwxrwx 1 root root      19 6月  16 10:46 libdtkgui.so.5 -> libdtkgui.so.5.5.24
> > lrwxrwxrwx 1 root root      19 6月  16 10:46 libdtkgui.so.5.5 -> libdtkgui.so.5.5.24
> > -rw-r--r-- 1 root root  552144 6月  16 10:46 libdtkgui.so.5.5.24
> > lrwxrwxrwx 1 root root      22 6月  16 10:47 libdtkwidget.so -> libdtkwidget.so.5.5.22
> > lrwxrwxrwx 1 root root      22 6月  16 10:47 libdtkwidget.so.5 -> libdtkwidget.so.5.5.22
> > lrwxrwxrwx 1 root root      22 6月  16 10:47 libdtkwidget.so.5.5 -> libdtkwidget.so.5.5.22
> > -rw-r--r-- 1 root root 3160168 6月  16 10:47 libdtkwidget.so.5.5.22
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/11452861/194748176-f01f2118-cf20-4952-b1bb-ddac00b0adce.png)
> 
> 如果你开了旧版本的terminal, 那么似乎会从/usr/bin/deepin-termianl启动一个新的，所以你测试时候最好把terminal都关掉

好吧确实是其他终端占用问题，3Q
