### ISSUE TITLE
There is Image Retention when deepin-screenshot is opened from Launcher.

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#346]
![deepinscreenshot_ _20170731083147](https://user-images.githubusercontent.com/20014762/28759069-dc1d326e-75ca-11e7-9806-f288a92d1cd4.png)

**Comment by hualet** [comment]
should've been fixed, can you test it for use @JulianLai

**Comment by JulianLai** [comment]
已修復
