### ISSUE TITLE
开启内置音频及麦克风采集时，无法结束录屏

### ISSUE THREAD

**Issue by itsXuSt** [linuxdeepin/developer-center#3464]
### SUMMARY | 问题概要

如标题描述，在录屏时，若开启了内置的音频及麦克风采集，则无法结束录屏。

### STEPS TO REPRODUCE | 复现步骤

1. ctrl + alt + R 触发录屏；
2. 开启麦克风及系统音频采集；
3. 开始录屏；
4. 结束录屏。

### OBSERVED RESULT | 观察到的结果

录屏无法结束；
Videos 文件夹中无录屏文件生成；
状态栏中录制图标持续闪烁或常驻。

### EXPECTED RESULT | 期望的结果

录屏正常结束；
Videos 或指定保存目录中有录屏文件生成；
状态栏常驻图标退出。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

系统版本：deepin 20.7
截图录屏：5.11.8
ffmpeg：4.1.9.5-deepin5

**Comment by xuqi27837288** [comment]
@itsXuSt 感谢反馈的问题，可以将环境和截图录屏工具升级至最新版本后再尝试一下~

**sudo apt update && sudo apt dist-upgrade**

系统版本：deepin 20.7.1
截图录屏：5.11.11-1
ffmpeg：7:4.4.2-1

刚在以上环境下未复现出录屏无法结束的现象~

**Comment by itsXuSt** [comment]
> 截图录屏：5.11.11-1

那就再尝试下连接了手机蓝牙的情况。可能和这个有关系。
![image](https://user-images.githubusercontent.com/50353838/195743277-f78f976d-2119-4a24-bd2b-5a23249aa9a8.png)
我连接蓝牙之后再录屏，录屏选项里的麦克风可选且默认选择，此时录屏就不能结束了。
