### ISSUE TITLE
V20.7.1 无法更改屏幕亮度

### ISSUE THREAD

**Issue by Wing-summer** [linuxdeepin/developer-center#3468]
### SUMMARY | 问题概要

战神笔记本无法修改屏幕亮度，之前一切正常（除了 Deepin V20.7 的最后一次更新）。无论是通过热键还是控制中心都无法控制屏幕的亮度。重装开始的时候屏幕亮度可调，我配置 flatpak 之后某个时间想调节屏幕亮度失败。

### STEPS TO REPRODUCE | 复现步骤

重装系统配置 flatpak 软件之后

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Deepin V20.7.1

### ADDITIONAL INFORMATION | 额外补充

在安装系统中，勾选集成闭源驱动。
通过网上找到缓解措施：使用 brightnessctl 可以控制屏幕亮度。
```bash
┌─[wingsummer][wingsummer-PC][~]
└─➞ sudo brightnessctl s 50%
请输入密码:
验证成功
Updated device 'intel_backlight':
Device 'intel_backlight' of class 'backlight':
        Current brightness: 3750 (50%)
        Max brightness: 7500
```

**Comment by BLumia** [comment]
cc @Zeno-sole @tsic404

**Comment by tsic404** [comment]
是配置flatpak后丢失调节亮度功能？

**Comment by Wing-summer** [comment]
> 是配置flatpak后丢失调节亮度功能？

时间点是的，但不确定是否是 flatpak 导致的。我安装所有 deb 之后，包括配置显卡插件切换之前一切正常。然后配置 flatpak 之后过一段时间我想调整就不行了。

**Comment by tsic404** [comment]
> > 是配置flatpak后丢失调节亮度功能？
> 
> 时间点是的，但不确定是否是 flatpak 导致的。我安装所有 deb 之后，包括配置显卡插件切换之前一切正常。然后配置 flatpak 之后过一段时间我想调整就不行了。

是安装仓库里面的flatpak吗

**Comment by Wing-summer** [comment]
> > > 是配置flatpak后丢失调节亮度功能？
> > 
> > 
> > 时间点是的，但不确定是否是 flatpak 导致的。我安装所有 deb 之后，包括配置显卡插件切换之前一切正常。然后配置 flatpak 之后过一段时间我想调整就不行了。
> 
> 是安装仓库里面的flatpak吗

是的

**Comment by Zeno-sole** [comment]
20.8是否还有这个问题呢？

**Comment by Wing-summer** [comment]
> 20.8是否还有这个问题呢？

问题依旧

**Comment by Wing-summer** [comment]
20.9已修复，前来关个issue
