### ISSUE TITLE
每次锁定屏幕时 xkb option 都会被移除

### ISSUE THREAD

**Issue by no1xsyzy** [linuxdeepin/developer-center#3478]
### SUMMARY | 问题概要

使用 `setxkbmap -option ctrl:swapcaps` 或者 `gsettings set com.deepin.dde.keyboard layout-options '["ctrl:swapcaps"]'` 设置的键盘布局额外设置。

### STEPS TO REPRODUCE | 复现步骤

1. `setxkbmap -option ctrl:swapcaps`
2. 可以看到 Ctrl 和 CapsLock 已经交换
3. 锁定屏幕

### OBSERVED RESULT | 观察到的结果

尝试使用 Ctrl 和 CapsLock，发现不再交换。
此时重新登录也不再交换。
重新输入上述命令又可以正常交换

### EXPECTED RESULT | 期望的结果

Ctrl 和 CapsLock 应当有办法保持交换。
或者重新登录后恢复交换。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Deepin v20.7.1
deepin-session-shell 5.5.81-1

### ADDITIONAL INFORMATION | 额外补充

已在 https://github.com/orgs/linuxdeepin/discussions/3472 确认，应当是 bug

**Comment by babyfengfjx** [comment]
我们先跟进一下，thanks~

**Comment by luodeepin** [comment]
您好！
该问题我们已经反馈给开发人员修复，之后有了具体修复情况结果，我再回复您！
谢谢！

**Comment by Decodetalkers** [comment]
我想应该是解决了，用了比较脏的方法，毕竟这个项目逻辑太复杂了

**Comment by babyfengfjx** [comment]
@Decodetalkers 问题解决后可以在后面提交集成，我们确认后可以提交到内测。

**Comment by Decodetalkers** [comment]
哦，没有，是没有问题的，应该可以集成
