### ISSUE TITLE
File System check in every boot!

### ISSUE THREAD

**Issue by gilbertoferreira** [linuxdeepin/developer-center#3485]
### SUMMARY | 问题概要

Well.
Every time I start/restart the system, I am stuck about 3 minutes in file system check!
Why is that?
Any other Linux which I have had installed I never got this behavior!
![IMG_20221104_233545_063](https://user-images.githubusercontent.com/10462980/200121332-4144957b-bc40-497b-8619-abf44410accc.jpg)

### STEPS TO REPRODUCE | 复现步骤

1 - install deepin linux 2.7
2 - reboot and get the message

### OBSERVED RESULT | 观察到的结果

file system check every time reboot/start

### EXPECTED RESULT | 期望的结果

no file system check at all!

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Deepin Linux 2.7.1

**Comment by BLumia** [comment]
Maybe related: https://askubuntu.com/questions/26299/why-is-my-root-filesystem-always-scanned-at-boot

You can check your fstab to see if check is enabled, and disable it if you want.

**Comment by gilbertoferreira** [comment]
> Maybe related: https://askubuntu.com/questions/26299/why-is-my-root-filesystem-always-scanned-at-boot
> 
> You can check your fstab to see if check is enabled, and disable it if you want.

No way! I use the very same /etc/fstab for numerous others distro, including Debian 11, Ubuntu 22.10!
Everything works ok, but Deepin Linux.

**Comment by BLumia** [comment]
> /dev/sda1 /boot ext4 defaults 0 2

Try change the `passno` (the last digit, `2`) to `0` and see if that fixes your issue.

**Comment by gilbertoferreira** [comment]
> > /dev/sda1 /boot ext4 defaults 0 2
> 
> Try change the `passno` (the last digit, `2`) to `0` and see if that fixes your issue.

Nevermind.
I am back to Kubuntu.
Sorry. Meny bugs.

**Comment by BLumia** [comment]
It's okay to switch to another distro. There are indeed many issues caused by the v20's ancient old packages. btw we will release v23 later (preview in this year and release in the next year) with much up-to-date packages so feel free to check v23 out later if you like :)
