### ISSUE TITLE
Unable to use kdeconnect to browse my phone.

### ISSUE THREAD

**Issue by gilbertoferreira** [linuxdeepin/developer-center#3486]
### SUMMARY | 问题概要

So I managed to connect my phone with kdeconnecta but everytime I try to browse the file system phone, get this message

![Capturar_select-area_20221105100637](https://user-images.githubusercontent.com/10462980/200121482-6b77a8ee-0fef-4098-a808-4c50e4739931.png)

The image says:
A folder named /home/gilberto/.cache/kioexec/krun/16487_0/ already exist!

Pretty annoying to say the least.

### STEPS TO REPRODUCE | 复现步骤

1 - install deepin linux
2 - update
3 - install kdeconnect
4 - successful connection using kdeconnect to the androi phone
5 - tried to browse the phone file system
6 - get stuck

### OBSERVED RESULT | 观察到的结果

message saying 
A folder named /home/gilberto/.cache/kioexec/krun/16487_0/ already exist!

and the file browser never show the phone file system

### EXPECTED RESULT | 期望的结果

I expected the file browser allows me to navegate in the phone file system.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Deepin Linux 2.7.1

**Comment by BLumia** [comment]
deepin 20.7's kdeconnect is probably too old so it will have issue contact with to your android KDE Connect app. Haven't try if the newer version can be built on deepin v20.7, if not, then v23 will eventually fix this issue, I guess.
