### ISSUE TITLE
Configuration Section

### ISSUE THREAD

**Issue by FernandoIV** [linuxdeepin/developer-center#349]
Hi, I don't know if this is only in my case but I don't have full configurations section like wallpaper in Personalization section 
![deepinscreenshot_20170801225621](https://user-images.githubusercontent.com/5061455/28857135-b811151e-770c-11e7-95d1-f89cb6cc5f9c.png)

is this a bug?
How I can get full configuration?

**Comment by SaltyCyborg** [comment]
No, it's ok.

**Comment by FernandoIV** [comment]
No more wallpaper section? How to find the default Deepin Wallpaper? I'm on Arch Linux

**Comment by JulianLai** [comment]
Right click on the desktop, and you will see it.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
