### ISSUE TITLE
在procps-ng升级到4.0.0之后找不到<proc/readproc.h>

### ISSUE THREAD

**Issue by leeffo** [linuxdeepin/developer-center#3492]
### SUMMARY | 问题概要

在openeuler-22.03-LTS-Next，使用deepin-screen-recorder-5.9.13版本，procps-ng版本为4.0.0，编译过程中报找不到<proc/readproc.h>。
![[image](https://build.openeuler.org/build/openEuler:22.03:LTS:Next:Epol/standard_x86_64/x86_64/deepin-screen-recorder/_log)](https://user-images.githubusercontent.com/47093973/201560002-4edd3676-09ff-463a-bffd-40228eef94c1.png)

### STEPS TO REPRODUCE | 复现步骤

1、使用obs进行构建
https://build.openeuler.org/package/show/openEuler:22.03:LTS:Next:Epol/deepin-screen-recorder

### OBSERVED RESULT | 观察到的结果

编译失败

### EXPECTED RESULT | 期望的结果

编译并打包成功

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

os:openEuler-22.03-LTS-Next

**Comment by leeffo** [comment]
请问有啥进展吗？

**Comment by BLumia** [comment]
暂时没有。openEuler 的 readproc 比 Arch Linux 的还新还是有点意外 :joy:

ps. 可以考虑加到 [dde-porting 组](https://github.com/deepin-community/SIG/tree/master/sig/dde-porting#%E4%B8%93%E7%94%A8%E4%BA%A4%E6%B5%81%E6%B8%A0%E9%81%93)来讨论

**Comment by wineee** [comment]
我试了下用 NixOS 编译，居然直接编译过了

看了下有 proc/readproc.h 的几个文件：
src/voice_record_process.h
src/voice_record_process.cpp
src/process_tree.h
src/process_tree.cpp

没有被别人调用，然后直接删了，还是可以编译 （

你可以试试升级，  git 版没有 procps 也可以编译

**Comment by wineee** [comment]
deepin-system-monitor 是确实依赖 procps 的,
procps 4 的 api 变动很大，不太好改

还有就是 USE_DEEPIN_WAYLAND 失效了

**Comment by leeffo** [comment]
> 

首先谢谢提示。不过之前在openeuler上deepin-screen-recoder的版本相对比较早(version: 5.9.13)，对procps-ng是强依赖，取消不了，使用最新tag的删除掉对应的头文件，可以编译成功。

**Comment by BLumia** [comment]
如果有意向的话，可以考虑给 deepin-screen-recoder 提个 PR 删除未使用的头文件 :)

**Comment by wineee** [comment]
顺便说一下，deepin-system-monitor 实际也没有用，只是 cmake 检查了：
```
 substituteInPlace deepin-system-monitor-main/CMakeLists.txt \
      --replace "find_library(LIB_PROCPS NAMES procps REQUIRED)" "" 
 substituteInPlace deepin-system-monitor-plugin-popup/CMakeLists.txt \
      --replace "find_library(LIB_PROPS NAMES procps REQUIRED)" ""
```
@leeffo 你可以验证一下
