### ISSUE TITLE
仓库Review接口设计讨论

### ISSUE THREAD

**Issue by choldrim** [linuxdeepin/developer-center#35]
# 仓库Review接口设计
## Host
https://rr.deepin.io/api/v1  (目前只能内网访问)

## 创建请求
POST  /review

#### headers
- str: Access-Token - 用户token

#### 参数
- str: topic - 对这次合并请求的简单描述
- str: comment - 对这次合并的详细描述
- str: base - 基础仓库（需要填写完整url，如：http://pools.corp.deepin.com/deepin）
- str: base_codename - 基础仓库的代号，如unstable
- str: rpa - ppa仓库（需要填写完整url，如：http://pools.corp.deepin.com/ppa/dstore）
- str: rpa_codename - ppa仓库的代号，如unstable
- str: shell - 暂时为保留字段，直接回复空字符即可

#### 返回数据
```json
{
    "failed": false,
    "result": {"review_id": 23}
}
```

## 获取所有review状态信息
GET /reviews

#### headers
- str: Access-Token - 用户token

#### 参数
无

#### 返回数据
```json
{
    "failed": false,
    "result": {
        "reviews":[{
                "id": 23,
                "topic": "balaba",
                "base": "http://packages.deepin.com/deepin",
                "base_codename": "unstable",
                "rpa": "http://pools.corp.deepin.com/ppa/dstore",
                "rpa_codename": "experimental",
                "status": "open",
                "submit_timestamp": "1456999262"
            },
            {
                "id": 24,
                "topic": "balaba",
                "base": "http://packages.deepin.com/deepin",
                "base_codename": "unstable",
                "rpa": "http://pools.corp.deepin.com/ppa/dstore",
                "rpa_codename": "experimental",
                "status": "open",
                "submit_timestamp": "1456999262"
            }
        ]
    }
}
```

## 获取单个review状态信息
GET /review/:review_id

#### headers
- str: Access-Token - 用户token

#### 参数
无

#### 返回数据
```json
{
    "failed": false,
    "result": {
        "id": 23,
        "topic": "balaba",
        "base": "http://packages.deepin.com/deepin",
        "base_codename": "unstable",
        "rpa": "http://pools.corp.deepin.com/ppa/dstore",
        "rpa_codename": "experimental",
        "comment": "comment",
        "shell": "echo hello world",
        "status": "open",
        "submit_timestamp": "1456999262",
        "comments":[
            {
                "submitter": "choldrim",
                "content": "look good to me ;)",
                "create_timestamp": "1456999262",
                "score": 1
            },
            {
                "submitter": "wangyanli",
                "content": "start testing",
                "create_timestamp": "1456999262",
                "score": 0
            },
            {
                "submitter": "wangyanli",
                "content": "test failed",
                "create_timestamp": "1456999262",
                "score": 0
            }
        ]
    }
}
```

## 评论接口
POST /comment/:review_id

#### headers
- str: Access-Token - 用户token

### 参数
- str: content - 评论内容
- int: score - 评分（-1 | 0 | 1）

#### 返回数据
```json
{
    "failed": false,
    "result": ""
}
```

## 测试结果接口
POST /test_result/:review_id

#### headers
- str: Access-Token - 用户token

### 参数
- str: comment - 评论内容
- bool: passed - 测试结果

#### 返回数据
```json
{
    "failed": false,
    "result": ""
}
```

## 合并
POST /merge/:review_id

#### headers
- str: Access-Token - 用户token

#### 参数
无

#### 返回数据
```json
{
    "failed": false,
    "result": ""
}
```

## 仓库合并结果
POST /merge_result/:review_id

#### headers
- str: Access-Token - 用户token

#### 参数
- bool: passed - 仓库合并通过与否
- str: content - 附加的合并结果展示（可返回跳转到对应地址的url链接）

#### 返回数据
```json
{
    "failed": false,
    "result": ""
}
```

## 丢弃
POST /abandon/:review_id

#### headers
- str: Access-Token - 用户token

#### 参数
无

#### 返回数据
```json
{
    "failed": false,
    "result": ""
}
```

## 重新触发review hook
POST /retrigger_review/:review_id

#### headers
- str: Access-Token - 用户token

### 参数
无

#### 返回数据
```json
{
    "failed": false,
    "result": ""
}
```

**Comment by choldrim** [comment]
@deepinzhangshuang @snyh @xielingyun(名字没找到..)
改进了base 和 rpa 填写的内容
之前是直接填写仓库名，如dstore，改进为填写完整仓库url + codename 的形式，
如：http://pools.corp.deepin.com/ppa/dstore experimental

**Comment by fasheng** [comment]
路过, 之前不是叫 @isolesty ?

**Comment by isolesty** [comment]
咦，他是不知道我的github的id吧

**Comment by choldrim** [comment]
@fasheng  :sweat_smile:  哈哈，刚刚还想问你的，不过我看到连接是生效的，我以为是@到了，所以就没管了

**Comment by isolesty** [comment]
@choldrim 一个RR的shell是准备怎么写？后台处理还是我之前说的创建时给个输入框自己填？

**Comment by choldrim** [comment]
@isolesty 后台先不处理，输入啥就执行啥

**Comment by choldrim** [comment]
@deepinzhangshuang @isolesty 接口更新了一小部分，base 拆分成 base 和 codename 两个字段
base表示 仓库的链接，如：http://packages.deepin.com/deepin，codename表示仓库的codename，如： unstable

**Comment by snyh** [comment]
rpa怎么处理的呢？
base和rpa是同一类数据类型．　如果需要细化应该同等处理．

**Comment by isolesty** [comment]
@snyh 目前是同样的处理，base和rpa

**Comment by choldrim** [comment]
>rpa怎么处理的呢？
>base和rpa是同一类数据类型．　如果需要细化应该同等处理．　
:grin: 漏写了 rpa

**Comment by choldrim** [comment]
改进了 **“获取单个review状态信息”**  接口，因为合并结果可能会多个记录（有可能存在失败的记录），所以将返回的 **merge_result** 对象 改成 **merge_results** 数组
@isolesty @deepinzhangshuang

**Comment by choldrim** [comment]
@isolesty @deepinzhangshuang 增加了部分接口，注意查看

**Comment by choldrim** [comment]
@isolesty 增加 `retrigger_review` 接口，用于重新触发review hooks

**Comment by choldrim** [comment]
@isolesty @wangyingtaodeepin @deepinzhangshuang ^^^
所有的接口都增加了 Access-Token header

**Comment by choldrim** [comment]
API文档移动到 [WiKi Repository-Review-API](https://github.com/linuxdeepin/developer-center/wiki/Repository-Review-API) ，此处展示的API不再更新
@isolesty @snyh @deepinzhangshuang @amazingfate @wangyingtaodeepin
