### ISSUE TITLE
empty space on taskbar and bad translation

### ISSUE THREAD

**Issue by joksik** [linuxdeepin/developer-center#350]
fresh install deepin 15.4.1 on arch 

1) after every reboot on taskbar i have empty space between icons. after install it was good but when i install some apps that use icons in taskbar (pamac, megasync, f.flux) this empty space start appears. i uninstall megasync and f.flux and test with pamac and the bug still exist. uninstall pamac and install octopi and bug exist so i think this bug will appears with every application that use icons in this area

![deepinscreenshot_select-area_20170802132507](https://user-images.githubusercontent.com/11992667/28871703-0cd70a12-7786-11e7-94d6-e290af73373c.png)

i must click on this "empty space" and after that it will gone

![deepinscreenshot_select-area_20170802131205](https://user-images.githubusercontent.com/11992667/28871461-e4c526c2-7784-11e7-976a-b4a467b5c525.png)

2) trash in start menu have correct name in Polish language "Kosz" but when i do shortcut on desktop i have english name "Trash"

![deepinscreenshot_20170802131304](https://user-images.githubusercontent.com/11992667/28871587-8cdf8730-7785-11e7-9355-49997e0d0757.png)

**Comment by joksik** [comment]
i think i fix this bug with "empty space" so when the icon will start before system icons like (power, volume, baterry) then empty space will appear so i add to my apps in ./config/autostart this line:

X-GNOME-Autostart-Delay=5

so now mega, and f.flux and pamac will always start after system icon and i dont have "empty space" on system tray but its only detour of problem so you can fix this with next release ;)

**Comment by JulianLai** [comment]
@joksik There is only one shortcut in ~/.config/autostart/, and it still doesn't work after I add X-GNOME-Autostart-Delay=5 to my shortcut.

**Comment by joksik** [comment]
you're right. I thought I got rid of the error but sometimes it appears again :/ so we can only wait for fix this

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
