### ISSUE TITLE
解压到当前文件夹功能不生效

### ISSUE THREAD

**Issue by ilove737** [linuxdeepin/developer-center#3504]
### SUMMARY | 问题概要

在压缩包文件上右键后点击”解压到当前文件夹“功能不生效。

### STEPS TO REPRODUCE | 复现步骤

1. 选择一个tar.gz文件
2. 在文件上点击”解压到当前文件夹“
3. 效果是并没有解压到当前文件夹，而是多了一层目录。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin-compressor 5.12.8

**Comment by BLumia** [comment]
@babyfengfjx 这个是预期行为吗？

**Comment by xuqi27837288** [comment]
感谢反馈的问题，我使用的5.10.12版本暂未复现出这个问题来，可以尝试升级下版本~
sudo apt install -f deepin-compressor

**Comment by student-ice** [comment]
这个不是修复了吗？
![图片](https://user-images.githubusercontent.com/59855569/203322745-b62da5f8-e8c0-41fb-a3dd-8d12bbc09337.png)

**Comment by ilove737** [comment]
> 感谢反馈的问题，我使用的5.10.12版本暂未复现出这个问题来，可以尝试升级下版本~ sudo apt install -f deepin-compressor @ilove737

我现在的版本是5.12.8

**Comment by student-ice** [comment]
最新的是5.12.10

> > 感谢反馈的问题，我使用的5.10.12版本暂未复现出这个问题来，可以尝试升级下版本~ sudo apt install -f deepin-compressor @ilove737
> 
> 我现在的版本是5.12.8

**Comment by ilove737** [comment]
> 最新的是5.12.10
> 
> > > 感谢反馈的问题，我使用的5.10.12版本暂未复现出这个问题来，可以尝试升级下版本~ sudo apt install -f deepin-compressor @ilove737
> > 
> > 
> > 我现在的版本是5.12.8

我目前用的是deepin。deepin仓库的版本竟然没有uos高吗？

**Comment by babyfengfjx** [comment]
在最新版本中应该是已经得到解决，可以升级后看一下问题是否OK？

**Comment by xuqi27837288** [comment]
刚在最新版本5.12.12上验证了一下,已经修复了该问题~
