### ISSUE TITLE
建议项目 readme 应当写出支持的编译选项

### ISSUE THREAD

**Issue by wineee** [linuxdeepin/developer-center#3510]
### SUMMARY | 问题概要

DDE 有不少项目可以通过编译选项来阉割或启用某项功能，这在适配不同发行版中是非常有用的，因为部分可选功能的依赖在其他发行版可能无法满足。

很多软件的版本号，也是需要通过编译参数设置的，以及单元测试，有些项目使用编译选项配置，但是这没有在 readme 中说明。

对于编译选项比较多的项目，建议在 readme 中列举所以可以使用的选项，方便开发者编译。

比如 dde-file-manager 最近由  DISABLE_ANYTHING 改为 ENABLE_ANYTHING,之前的写法失效了，必须看代码才能明白这个变动。

编译选项比较多的项目
- [ ] dde-file-manager
- [ ] dde-control-center
...

相关：https://github.com/linuxdeepin/developer-center/issues/3378

**Comment by BLumia** [comment]
对于 CMake 项目，`cmake -L` 即可列出所有（非 advanced 的）选项（advanced 选项需要带 `-A`）。这种情况，在工程文件的 option 中给出恰当说明我觉得就足够了，可以不要求加以说明，当然能够在 README 加以说明更好。

对于非 CMake 项目（例如 qmake），似乎没有办法直接得到所有可用的编译选项，这种情况我认为有必要加以说明。

**Comment by wineee** [comment]
dde-file-manager 使用 qmake
 dde-control-center 使用 cmake -LA, 并没有出现我想要的结果，比如 DISABLE_AUTHENTICATION,DISABLE_SYS_UPDATE
