### ISSUE TITLE
关于系统电池管理、功耗、风扇问题

### ISSUE THREAD

**Issue by Wolfdebug** [linuxdeepin/developer-center#3514]
### SUMMARY | 问题概要

目前系统耗电极其离谱，充满电之后大概可以使用一小时，对比安装Windows10系统时可使用五六个小时，这属实是不正常的。个人认为这已经不是功耗问题了，而是电池管理或者其他什么原因存在着严重的问题。其次，系统内存使用超过一半的时候，风扇就会开始呼呼地转起来，发热严重，这大概也是耗电严重的其中一个原因吧，诚恳地希望官方能够针对这一点着重做出优化，提高此问题的解决优先级。希望deepin越做越好～

### STEPS TO REPRODUCE | 复现步骤

没什么多余的步骤，正常使用就是了，多开几个应用

### OBSERVED RESULT | 观察到的结果

耗电极其严重离大谱

### EXPECTED RESULT | 期望的结果

能够正常使用，不要发烫严重，耗电太离谱

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

UOS统信家庭版（21.3.1）
内核版本：5.10.0-amd64-desktop
处理器：Intel(R)Core(TM)i7-10750HCPU@2.60GHz
内存：16GB
电脑：戴尔XPS15 9500

**Comment by BLumia** [comment]
> UOS统信家庭版

我们是 deepin 开源社区，处理 deepin 社区版的问题反馈。如果你希望 UOS 商业版本的问题得到处理，可以考虑反馈到商业版本的反馈渠道。

因为商业版 UOS 和 deepin 所预装/包含的内容也有差异，后台服务、守护进程、安全中心等的差异也可能造成你所描述的问题，所以其实也建议你考虑尝试下 deepin 是否也有近似的问题。如果 deepin 也有类似问题的话，可以[在 Discussion 讨论板](https://github.com/linuxdeepin/developer-center/discussions)开个反馈，我们看看能否进一步定位问题。

感谢支持！

**Comment by Wolfdebug** [comment]
> > UOS统信家庭版
> 
> 我们是 deepin 开源社区，处理 deepin 社区版的问题反馈。如果你希望 UOS 商业版本的问题得到处理，可以考虑反馈到商业版本的反馈渠道。
> 
> 因为商业版 UOS 和 deepin 所预装/包含的内容也有差异，后台服务、守护进程、安全中心等的差异也可能造成你所描述的问题，所以其实也建议你考虑尝试下 deepin 是否也有近似的问题。如果 deepin 也有类似问题的话，可以[在 Discussion 讨论板](https://github.com/linuxdeepin/developer-center/discussions)开个反馈，我们看看能否进一步定位问题。
> 
> 感谢支持！

好的，感谢，商业版的渠道您这边知道吗

**Comment by BLumia** [comment]
可以访问 https://www.chinauos.com/ 了解一下，或者查看一下最初您获取 UOS 时所用的渠道所提供的联系方式~
