### ISSUE TITLE
file manager little visual bug

### ISSUE THREAD

**Issue by gionno** [linuxdeepin/developer-center#352]
if only one file is selected
the status shown is

![alt text](https://s4.postimg.org/ce8i73rul/Deepin_Screenshot_20170822170618.png)

if two or more files are selected
the status is correct

![alt text](https://s4.postimg.org/rocys1cql/Deepin_Screenshot_20170822170840.png)

**Comment by hualet** [comment]
fixed

**Comment by gionno** [comment]
thank you ^_^
