### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【发散测试】【终端】Terminal 终端 Ctrl+S/Q的控制问题

### ISSUE THREAD

**Issue by foresee-io** [linuxdeepin/developer-center#3524]
### SUMMARY | 问题概要

GNU Nano >=3.2 等软件中，Ctrl+S有“保存”功能。目前使用deepin-terminal会针对Ctrl+S键给出错误的提示。

建议：最简单的办法是去除错误的提示语
如果能识别出当前程序是否占用Ctrl+S/Ctrl+Q，则更好

### STEPS TO REPRODUCE | 复现步骤

首先在终端输入
``` bash
cd /tmp;nano `mktemp` #回车,然后自己随便输入一些内容
```
1. 默认设置下
按Ctrl+S
nano正确执行了保存操作
deepin-terminal错误地弹出了提示语
![截图_deepin-terminal_20221223102249](https://user-images.githubusercontent.com/32860378/209258479-fdc34869-15f9-4d5d-8562-92521b00754c.png)

2. 勾选“禁用Ctrl+S和Ctrl+Q控制”选项时
再随便往nano输入一些内容，按Ctrl+S
Ctrl+S被完全地禁用，nano不执行保存操作
![截图_deepin-terminal_20221223102419](https://user-images.githubusercontent.com/32860378/209258486-477a17b5-eea4-44bf-9ebf-ae15deab74db.png)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Distribution: Deepin Community 20.8
Package: deepin-terminal 5.4.39-1

### ADDITIONAL INFORMATION | 额外补充

Update 2024/3/17:
可以参考 KDE Konsole 的实现。它通过 Pty::flowControlEnabled() 函数，判断 Shell 是否处于冻结状态（似乎是直接读取了 Shell 的状态，而不是单纯判断前台程序？）。

**Comment by luodeepin** [comment]
您好！
目前通过终端调用nano，nano编辑器为第三方应用，并不涉及Ctrl S相关命令；
相似的第三方vim编辑器：Ctrl S为锁屏命令，通过Ctrl Q可以解除锁屏

我们已经把你的这个建议反馈给了产品经理，之后有了评估结果，我再向你反馈下咯！

**Comment by ArchieMeng** [comment]
- 首先，nano保存当前内容的快捷键是Ctrl+O．
- 其次，Ctrl+S/Ctrl+Q快捷键可以在 设置-Shell 里面修改．
希望上述信息对您有帮助．

**Comment by luodeepin** [comment]
https://pms.uniontech.com/bug-view-182811.html

子项目反馈这个问题不是终端问题 ， 请重新分析

![image](https://github.com/linuxdeepin/developer-center/assets/96416089/e1923751-266e-4bfc-9156-8971e4fe3798)

**Comment by luodeepin** [comment]
1. 如果按照开发解释的情况，那为什么又会出现 挂起的提示

2. 如果走的nano的 ctrl s 操作，那这个时候应该是执行的nano的保存操作

**Comment by foresee-io** [comment]
@luodeepin 是的，出现（终端的）锁屏与否，要结合第三方程序去考虑，看它们有没有占用 Ctrl+S/Q 按键。
核心问题是 deepin-terminal 会给出错误的 **提示语** ，虽然 **提示语** 不会影响 Ctrl+S/Q 发挥功能，但时机出现得不恰当。

**Comment by ArchieMeng** [comment]
大概明白意思了。在用户那种场景不应该弹出这个提示？

**Comment by foresee-io** [comment]
@ArchieMeng 是的，主要诉求是对 **提示语** 的优化。
打个比方，若实在难以判断第三方应用是否占用 Ctrl+S/Q
- 弹出Toast通知（过一段时间自动消除的那种），“您已按下Ctrl+S，**如果** 终端被锁定，可按Ctrl+Q解锁”，不要长时间霸占屏幕；
- 或者，不要给出任何提示语；
- 或者，讨论一个更优的方案。

**Comment by foresee-io** [comment]
Update 2024/3/17: 
可以参考 KDE Konsole 的实现。它通过 `Pty::flowControlEnabled()` 函数，判断 Shell 是否处于冻结状态（似乎是直接读取了 Shell 的状态，而不是单纯判断前台程序？）。视频示例中，
- GNU Nano 是文本编辑器，它占用了 Ctrl+S 按键来“保存文件”。按下 Ctrl+S 并不会冻结终端；
- 无前台程序或前台程序不占用按键时，按下 Ctrl+S 会冻结终端。

Link: https://invent.kde.org/utilities/konsole/-/blob/v24.02.0/src/Pty.cpp#L143

https://github.com/linuxdeepin/developer-center/assets/32860378/e636ad46-481f-42b7-8946-5294e707c00c

**Comment by foresee-io** [comment]
已经在 v23 修复，但 v20 尚未修复。关闭问题。
相关修复补丁： https://github.com/linuxdeepin/deepin-terminal/commit/d057f5e8d448293ce1285a02b637a929651c4df5
