### ISSUE TITLE
[系统监视器]磁盘图标下有奇怪文字 

### ISSUE THREAD

**Issue by linngc** [linuxdeepin/developer-center#3527]
### SUMMARY | 问题概要

在磁盘图标下面有一个模糊显示的一行奇怪字.

### STEPS TO REPRODUCE | 复现步骤

1.进入[系统监视器]界面
2.选择磁盘，显示磁盘图标
3.磁盘图标头部即可显示异常奇怪的文字 

![如图所示](https://user-images.githubusercontent.com/48039456/209502473-48cca0fd-c3d7-4189-9507-c08f2a6e477f.png)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

系统版本：deepin v20.8

**Comment by SuperEffie** [comment]
感谢反馈哦，并且我们有看到您在论坛中的留言，目前我们还未复现到您issue中提到的系统监视器的问题，可能是部分机器上的问题。我们持续关注下，若有复现环境会及时反馈给开发者们哈～

**Comment by SuperEffie** [comment]
由于您长时间未回复，我先将这个帖子关闭了
关于您提的问题，我们在多台机器上验证后未复现到，这个问题似乎不影响您的使用。后期我们复现到会及时修复。欢迎您为我们反馈更多的问题哟~
