### ISSUE TITLE
gcc-8_8.3.0.3-3+rebuild 没有默认使能pie

### ISSUE THREAD

**Issue by Rabenda** [linuxdeepin/developer-center#3528]
### SUMMARY | 问题概要

gcc 默认应该使能pie 但是因为发行版识别修改成uos/deepin导致默认pie消失了
所以各个项目才不得不强加-pie参数

```
# pie by default --------------------
with_pie :=
ifeq ($(distribution),Debian)
  ifeq (,$(filter $(distrelease),wheezy squeeze jessie))
    pie_archs = amd64 arm64 armel armhf i386 \
		mips mipsel mips64 mips64el mipsn32 mipsn32el \
		mipsr6 mipsr6el mips64r6 mips64r6el mipsn32r6 mipsn32r6el \
		ppc64el s390x sparc sparc64 kfreebsd-amd64 kfreebsd-i386 \
		hurd-i386 riscv64
  endif
  ifeq (,$(filter $(distrelease),wheezy squeeze jessie stretch))
    pie_archs += powerpc ppc64
  endif
else ifeq ($(distribution),Ubuntu)
  ifeq (,$(filter $(distrelease),lucid precise trusty utopic vivid wily))
    pie_archs = s390x
  endif
  ifeq (,$(filter $(distrelease),lucid precise trusty utopic vivid wily xenial))
    pie_archs += amd64 ppc64el
  endif
  ifeq (,$(filter $(distrelease),lucid precise trusty utopic vivid wily xenial yakkety zesty))
    pie_archs += armhf arm64 i386
  endif
  pie_archs += riscv64
endif
ifneq (,$(filter $(DEB_TARGET_ARCH),$(pie_archs)))
  with_pie := yes
endif
ifeq ($(trunk_build),yes)
  with_pie := disabled for trunk builds
endif
```

### STEPS TO REPRODUCE | 复现步骤

```bash
dget -d https://community-packages.deepin.com/deepin/pool/main/g/gcc-8/gcc-8_8.3.0.3-3%2Brebuild.dsc
dpkg-source -x gcc-8_8.3.0.3-3%2Brebuild.dsc
cd gcc-8-8.3.0.3/debian

vim +1237 rules.defs
```

就可以发现没有识别uos/deepin相关的 导致default-pie丢失 与其他发行版行为不一致

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin v20.8
gcc-8_8.3.0.3-3+rebuild

**Comment by Zeno-sole** [comment]
@Rabenda  v23的gcc也有同样的问题吧？

**Comment by Rabenda** [comment]
> @Rabenda v23的gcc也有同样的问题吧？

重新编译的gcc有 现在还没重新编译

**Comment by Zeno-sole** [comment]
@UTsweetyfish  看下这个问题，v23的gcc版本上加一下关于uos/deepin的判断

**Comment by UTsweetyfish** [comment]
v23 已 merge

**Comment by Rabenda** [comment]
> v23 已 merge

sw架构写错

**Comment by UTsweetyfish** [comment]
> > v23 已 merge
> 
> sw架构写错

https://github.com/deepin-community/gcc-11/pull/2

这个吧

**Comment by Rabenda** [comment]
> > > v23 已 merge
> > 
> > 
> > sw架构写错
> 
> [deepin-community/gcc-11#2](https://github.com/deepin-community/gcc-11/pull/2)
> 
> 这个吧

Ok. 还有这个bug在20.8同样存在 未体现修复

**Comment by Zeno-sole** [comment]
> > > > v23 已 merge
> > > 
> > > 
> > > sw架构写错
> > 
> > 
> > [deepin-community/gcc-11#2](https://github.com/deepin-community/gcc-11/pull/2)
> > 这个吧
> 
> Ok. 还有这个bug在20.8同样存在 未体现修复

20.8 转内部处理

**Comment by SuperEffie** [comment]
【验证环境】
【验证镜像】：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230309/ 
【集成链接】：https://github.com/orgs/linuxdeepin/projects/21/views/1?pane=issue&itemId=25057067
【版本信息】：libgcc-11-dev：11.2.0-deepin2+rb1
【测试步骤】：

1. 添加集成仓库后更新
2. 下载devscripts:sudo apt install devscripts
3. 参考issue中复现步骤：
- dget -d https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-intergration-pr-70/testing/gcc-11_11.2.0-deepin2%2Brb1.dsc
- dpkg-source -x gcc-8_8.3.0.3-3%2Brebuild.dsc
- cd gcc-8-8.3.0.3/debian
- vim +1237 rules.defs
【验证结论】：测试通过，截图如下
![pie](https://user-images.githubusercontent.com/58986464/230818174-2cfe9896-1139-49e6-97f1-1578380c9f1a.jpg)

**Comment by babyfengfjx** [comment]
@SuperEffie 请在CI仓库验证通过后，挪动到Integrated列。

**Comment by SuperEffie** [comment]
【验证环境】
【验证镜像】：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230309/
【集成仓库】：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
【版本信息】：libgcc-11-dev：11.2.0-deepin2+rb1
【验证结论】：该包已集成至ci仓库，且升级无冲突
![pie](https://user-images.githubusercontent.com/58986464/231120054-ebf9684b-aff5-4f72-89e9-e4e3bf78b2c0.jpg)

**Comment by Rabenda** [comment]
这都什么验证通过的方式 明显验证用例有问题啊

你在验证pie是否是default的状态 竟然不直接查看gcc-11 -v的输出
和编译test.c这种 去file查看是否是pie的

上面验证什么乱七八糟的东西 怎么允许通过的

**Comment by BLumia** [comment]
这个 issue 描述里的 step to reproduce 不太适合作为测试验证问题是否修复的依据，更多是给研发人员看的。

可以按上面一个 comment 的描述里验证，如果不清楚细节步骤的话我或者 @Zeno-sole 来补充吧。
