### ISSUE TITLE
deepin file manager: double click or press enter issue

### ISSUE THREAD

**Issue by shreyanshk** [linuxdeepin/developer-center#353]
hi guys,
since some 2 weeks I'm facing this weird issue where I have to "double click" twice or press enter twice on a file in deepin file manager to open it with text editor.
any ideas?

**Comment by JulianLai** [comment]
#308 me, too.

**Comment by shreyanshk** [comment]
I'd like to add that for some reason unrelated to this, I switched to Sublime Text and then found out that there is no such problem like this when opening files with sublime text. So, probably gedit is at error here.
