### ISSUE TITLE
linuxdeepin 下OBS上构建有问题的项目

### ISSUE THREAD

**Issue by tsic404** [linuxdeepin/developer-center#3530]
使用OBS构建linuxdeepin下项目时，发现一些项目的debian/下存在一些问题。linuxdeepin下项目OBS的链接地址https://build.deepin.com/project/show/deepin:Develop:dde

[dde](https://build.deepin.com/package/show/deepin:Develop:dde/dde) native的项目使用quilt的版本号规则  **OBS service失败**
[dde-account-faces](https://build.deepin.com/package/show/deepin:Develop:dde/dde-account-faces) 未修改changelog
[dde-api](https://build.deepin.com/package/show/deepin:Develop:dde/dde-api)   changelog与tag存在差距   **阻塞其他构建**
[dde-clipboard](https://build.deepin.com/package/show/deepin:Develop:dde/dde-clipboard) 未修改changelog
[dde-control-center](https://build.deepin.com/package/show/deepin:Develop:dde/dde-control-center) 未修改changelog
[dde-daemon](https://build.deepin.com/package/show/deepin:Develop:dde/dde-daemon) 未修改changelog
[dde-device-formatter](https://build.deepin.com/package/show/deepin:Develop:dde/dde-device-formatter) 未修改changelog
[dde-dock](https://build.deepin.com/package/show/deepin:Develop:dde/dde-dock) 未修改changelog
[dde-grand-search](https://build.deepin.com/package/show/deepin:Develop:dde/dde-grand-search) 未修改changelog
[dde-introduction](https://build.deepin.com/package/show/deepin:Develop:dde/dde-introduction)  changelog为模板     **OBS service失败**
[dde-kwin](https://build.deepin.com/package/show/deepin:Develop:dde/dde-kwin)  changelog不规范，<email>后面缺少空格     **OBS service失败**
[dde-launcher](https://build.deepin.com/package/show/deepin:Develop:dde/dde-launcher) 未修改changelog
[dde-manual-content](https://build.deepin.com/package/show/deepin:Develop:dde/dde-manual-content) 未修改changelog
[dde-network-core](https://build.deepin.com/package/show/deepin:Develop:dde/dde-network-core) changelog严重不规范 内容为空       **OBS service失败**
~~[dde-network-utils](https://build.deepin.com/package/show/deepin:Develop:dde/dde-network-utils) 未修改changelog， quilt使用native格式版本号     **OBS service失败**~~
[dde-polkit-agent](https://build.deepin.com/package/show/deepin:Develop:dde/dde-polkit-agent) 未修改changelog 
[dde-printer](https://build.deepin.com/package/show/deepin:Develop:dde/dde-printer) 未修改changelog
[dde-qt-dbus-factory](https://build.deepin.com/package/show/deepin:Develop:dde/dde-qt-dbus-factory) 未修改changelog       **阻塞其他构建** 
[dde-session-shell](https://build.deepin.com/package/show/deepin:Develop:dde/dde-session-shell) 为修改changelog
[dde-session-ui](https://build.deepin.com/package/show/deepin:Develop:dde/dde-session-ui) 未修改changelog
[dde-wloutput](https://build.deepin.com/package/show/deepin:Develop:dde/dde-wloutput) native使用quilt版本号     **OBS service失败**
[deepin-ab-recovery](https://build.deepin.com/package/show/deepin:Develop:dde/deepin-ab-recovery) 未修改changelog
[deepin-album](https://build.deepin.com/package/show/deepin:Develop:dde/deepin-album) 未修改changelog
[deepin-clone](https://build.deepin.com/package/show/deepin:Develop:dde/deepin-clone) 未修改changelog
[deepin-compressor](https://build.deepin.com/package/show/deepin:Develop:dde/deepin-compressor) 未修改changelog
[deepin-devicemanager](https://build.deepin.com/package/show/deepin:Develop:dde/deepin-devicemanager) 未修改changelog
[deepin-draw](https://build.deepin.com/package/show/deepin:Develop:dde/deepin-draw) 未修改changelog
[deepin-picker](https://build.deepin.com/package/show/deepin:Develop:dde/deepin-picker) 未修改changelog
[deepin-screen-recorder](https://build.deepin.com/package/show/deepin:Develop:dde/deepin-screen-recorder) 未修改changelog
[deepin-shortcut-viewer](https://build.deepin.com/package/show/deepin:Develop:dde/deepin-shortcut-viewer) 未修改changelog
[deepin-system-monitor](https://build.deepin.com/package/show/deepin:Develop:dde/deepin-system-monitor) 未修改changelog
[deepin-voice-note](https://build.deepin.com/package/show/deepin:Develop:dde/deepin-voice-note) 未修改changelog    存在debian/files文件    **OBS service失败**
[startdde](https://build.deepin.com/package/show/deepin:Develop:dde/startdde) 未修改changelog

**OBS service失败**和**阻塞其他构建**的项目希望对应项目组可以尽快解决。
后面各个项目采用修改changelog的方式打tag。

**Comment by wineee** [comment]
dde-network-utils 应该已弃用了 (https://github.com/orgs/linuxdeepin/discussions/3050)

**Comment by tsic404** [comment]
> dde-network-utils 应该已弃用了 (https://github.com/orgs/linuxdeepin/discussions/3050)

那我标注一下，OBS就清理这个项目了

**Comment by wineee** [comment]
- - https://github.com/linuxdeepin/dde-qt-dbus-factory/pull/219

**Comment by tsic404** [comment]
OBS 推送完成

**Comment by wineee** [comment]
[deepin-wallpapers ](https://github.com/linuxdeepin/deepin-wallpapers) 没有推 obs

**Comment by tsic404** [comment]
> [deepin-wallpapers ](https://github.com/linuxdeepin/deepin-wallpapers) 没有推 obs

https://github.com/linuxdeepin/deepin-wallpapers/pull/26
