### ISSUE TITLE
go-lib 中 symlinkIsDir 函数实现有问题

### ISSUE THREAD

**Issue by wineee** [linuxdeepin/developer-center#3531]
### SUMMARY | 问题概要

对应函数 https://github.com/linuxdeepin/go-lib/blob/ae4320a1b55c3db1f7a933f547bbdf69f0659794/utils/file.go#L215
```go
func symlinkIsDir(link string) bool {
	target, err := os.Readlink(link)
	if err != nil {
		return false
	}

	dir := path.Dir(link)
	if len(dir) == 0 {
		return IsDir(target)
	}
	return IsDir(path.Join(dir, target))
}
```
此函数假定了符号链接必须是相对路径，遇到绝对路径判断会出错，必然返回 false

此函数导致 IsDir 函数出错 https://github.com/linuxdeepin/go-lib/blob/ae4320a1b55c3db1f7a933f547bbdf69f0659794/utils/file.go#L77

### STEPS TO REPRODUCE | 复现步骤

在 go/src/go-lib/utils/ 目录下：
任意建立一个软链接：
```
ln -s /usr/local/ testdata/utils
```
为 TestIsDir 函数增加一组数据
```
                {
                        dir: "testdata/utils",
                        ok:  true,
                },
```
执行 go test：

```
go test -timeout 30s -run ^TestIsDir$ github.com/linuxdeepin/go-lib/utils -v
```
![image](https://user-images.githubusercontent.com/22803888/209895506-9818b7a4-21df-4151-95e6-d506f003a8dd.png)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

git 版

### ADDITIONAL INFORMATION | 额外补充

实现 IsDir 函数时，使用 go 的 os.Stat 是可以兼容符号链接的，因此不实现 symlinkIsDir 函数也是可以

**Comment by wineee** [comment]
cc @Decodetalkers

**Comment by wineee** [comment]
cc @Decodetalkers

**Comment by Decodetalkers** [comment]
https://github.com/linuxdeepin/go-lib/pull/80
这样对吗。

**Comment by wineee** [comment]
debian/abi.json 有这个函数，我不确定这个文件是否是手动改的
