### ISSUE TITLE
浏览器UI边缘过于粗糙

### ISSUE THREAD

**Issue by mokapsing** [linuxdeepin/developer-center#3532]
### SUMMARY | 问题概要

浏览器边缘过于粗糙，尤其是在4k屏上的
![image](https://user-images.githubusercontent.com/39441028/209908269-c2ab9504-2b9a-4355-89e4-457e3d497367.png)

### STEPS TO REPRODUCE | 复现步骤

在AMD显卡的机器上安装deepin/uos，打开浏览器(本人仅有amd显卡的设备)

### OBSERVED RESULT | 观察到的结果

浏览器边缘过于粗糙

### EXPECTED RESULT | 期望的结果

浏览器边缘应该圆滑，像MS edge那样

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

OS: Deepin 20.8 x86_64                                                                                             
Host: E500                                                                                                         
Kernel: 5.18.17-amd64-desktop-community-hwe                                                                        
Uptime: 4 hours, 35 mins                                                                                           
Packages: 2155 (dpkg)                                                                                              
Shell: bash 5.0.3                                                                                                  
Resolution: 1920x1080                                                                                              
DE: Deepin                                                                                                         
WM: KWin                                                                                                           
Icons: Deepin2022-Dark [GTK2/3]                                                                                    
Terminal: deepin-terminal                                                                                          
CPU: Intel i7-10700 (16) @ 4.800GHz                                                                                
GPU: AMD ATI Radeon HD 8570 / R7 240/340 / R520 OEM                                                                
Memory: 6620MiB / 15932MiB

**Comment by luodeepin** [comment]
您好！
这个边框边缘显示问题，我们已经提单给开发人员进行修复，之后有了进一步进展我再回复您。
谢谢您的积极反馈！

**Comment by mokapsing** [comment]
> 您好！ 这个边框边缘显示问题，我们已经提单给开发人员进行修复，之后有了进一步进展我再回复您。 谢谢您的积极反馈！

感谢

**Comment by luodeepin** [comment]
已经转入项目经理安排处理，这个问题在v23 beta 环境中依然存在

**Comment by luodeepin** [comment]
在 23 beta上 也存在这个问题，已经反馈尽快修复

**Comment by mokapsing** [comment]
流览器有点落后于uos/deepin整体体验了

**Comment by luodeepin** [comment]
经与设计及相关人沟通，黑边问题转需求处理，由于优先级不高，预计到 V6.3版本后才会处理，当前暂时做关闭处理
