### ISSUE TITLE
Blurred terminal background

### ISSUE THREAD

**Issue by dreszczyk** [linuxdeepin/developer-center#354]
Is this possible? This is my terminal:
![image](https://user-images.githubusercontent.com/5095527/29704553-999c4c04-897a-11e7-9bcb-34324a4ac0b4.png)

I would like to have the blurry background like this:
![image](https://user-images.githubusercontent.com/5095527/29704583-b5c6648c-897a-11e7-8446-56ef44de6b71.png)

**Comment by manateelazycat** [comment]
Has implement: https://github.com/linuxdeepin/deepin-terminal/issues/18
