### ISSUE TITLE
ssh connection via remote servers does not work

### ISSUE THREAD

**Issue by vecinohk** [linuxdeepin/developer-center#3545]
### SUMMARY | 问题概要

Hello everyone,

I have trouble with Deepin Terminal and remote servers. I can add my favorite ssh connections, but when I want to connect, nothing happens. I found that if I look through the history command, there is something like:

`expect -f /tmp/terminal-P91DQA 'root' 10.20.30.1 22 'NoPrivateKeyPath' ''`

### STEPS TO REPRODUCE | 复现步骤

1) I'll add an SSH connection to remote servers.
2) I click on SSH connection but nothing happens. No reaction.
3) Bash **history** command says: `expect -f /tmp/terminal-P91DQA 'root' 10.20.30.1 22 'NoPrivateKeyPath' ''`

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Arch Linux - 6.1.4-arch1-1
deepin-terminal - 5.9.40-1

**Comment by BLumia** [comment]
Can reproduce on Arch, not sure if it can also be reproduced under deepin. cc @babyfengfjx

**Comment by xuqi27837288** [comment]
@vecinohk Thanks for the feedback, the problem has been repeated, submitted and fed back to the R&D staff for optimization

**Comment by ArchieMeng** [comment]
To use remote management function on Arch Linux, packages "expect" and "zssh" are required. However, only "zssh" is listed as optional dependencies while "expect" is not.

**Comment by vecinohk** [comment]
After installing these two packages "**expect**" and "**zssh**" everything works. Thanks @ArchieMeng @xuqi27837288
