### ISSUE TITLE
deepin-launcher build failure on openSUSE

### ISSUE THREAD

**Issue by hillwoodroc** [linuxdeepin/developer-center#3547]
### SUMMARY | 问题概要

[   20s] /home/abuild/rpmbuild/BUILD/dde-launcher-5.6.1/src/launchersys.cpp: In constructor 'LauncherSys::LauncherSys(QObject*)':
[   20s] /home/abuild/rpmbuild/BUILD/dde-launcher-5.6.1/src/launchersys.cpp:29:27: error: expected type-specifier before 'DRegionMonitor'
[   20s]    29 |     , m_regionMonitor(new DRegionMonitor(this))
[   20s]       |                           ^~~~~~~~~~~~~~
[   20s] /home/abuild/rpmbuild/BUILD/dde-launcher-5.6.1/src/launchersys.cpp:36:40: error: reference to 'DRegionMonitor' is ambiguous
[   20s]    36 |     m_regionMonitor->setCoordinateType(DRegionMonitor::Original);
[   20s]       |                                        ^~~~~~~~~~~~~~
[   20s] In file included from /home/abuild/rpmbuild/BUILD/dde-launcher-5.6.1/src/windowedframe.h:26,
[   20s]                  from /home/abuild/rpmbuild/BUILD/dde-launcher-5.6.1/src/launchersys.cpp:8:

### STEPS TO REPRODUCE | 复现步骤

build it on openSUSE

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

5.6.1

**Comment by BLumia** [comment]
这个应该不用在 v23 beta 里处理吧，5.6.1 不是 v23 里用的版本，我从 v23 beta 看板里移除掉吧 😂 

v23 beta 的 tag 也打过了，目前可用 6.0.9。

**Comment by hillwoodroc** [comment]
Comfirm fixed in 6.0.9
