### ISSUE TITLE
文本编辑器撤销和重做问题

### ISSUE THREAD

**Issue by lizipeng0013** [linuxdeepin/developer-center#3554]
### SUMMARY | 问题概要

选中文字后鼠标拖动复制或移动的文字，在多次撤销或重做后无法恢复到原始状态，100%重现（编辑器版本：5.10.40，5.10.41）

### STEPS TO REPRODUCE | 复现步骤

请看：
1.[Deepin文本编辑器的bug（哔哩哔哩视频）](https://www.bilibili.com/video/BV1AP4y167vc) 
2.[深度论坛反馈帖](https://bbs.deepin.org/post/248981) 

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin20.8

**Comment by zccrs** [comment]
@asterwyx

**Comment by asterwyx** [comment]
该问题已经在 linuxdeepin/deepin-editor#206 中解决，请升级到该PR之后的版本 https://github.com/linuxdeepin/deepin-editor/commit/f62dcb6a33c489bd8a9e577e4aa683bcbebf4cc8 。
