### ISSUE TITLE
Can't move deepin-application windows on touchscreen drag

### ISSUE THREAD

**Issue by Prutheus** [linuxdeepin/developer-center#356]
I am running Deepin on archlinux on a touchscreen device. I can move the windows via touchscreen-drag, ok. But I can't move the windows which are from deepin apps, e.g. deepin-terminal, deepin-filemanager ... these are getting maximized or minimized but not moved.
I can move others like gtk windows or gnome windows ... Any ideas?

**Comment by captennemo** [comment]
Have the same problem as Prutheus

**Comment by zccrs** [comment]
I'm sorry. The deepin applications window has not support touchscreen. I'm will as early as possible fix it.

**Comment by x86vk** [comment]
+1，
And it seems that the DDE do not handle the touchscreen event well. After I have used the touchscreen with other application running on DDE like Chrome, there is a chance that DDE do not catch the "click up event" by touchscreen. It will mistakenly see the mouse as always pushed down, though it is not clicked. And clicking the mouse after that do not solve the problem. Have to restart the whole desktop environment.

**Comment by x86vk** [comment]
BTW, I can not move Chrome and wine applications either. But other GTK and Qt applications are okay.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
