### ISSUE TITLE
Can't Change Volume, can't change the wallpaper, "Super"-Key sometimes doesn't react.

### ISSUE THREAD

**Issue by Dyspor** [linuxdeepin/developer-center#3563]
### SUMMARY | 问题概要

**My Notebook**
_PC:_ HP 250 G6 Notebook PC
_DE Version:_ Deepin 20.6
_Kernel:_ 6.1.8-arch1-1

**Volume Issue**
The Volume doesn't change if I press the intended Buttons (f7: - / f8: +)
The Volume Slider in the Settings doesn't react at all, if I try to drag the slider I move the window.

**Brightness Issue**
The Brightness doesn't change if I press the intended Buttons (f2: - / f3: +)

**Wallpaper Issue**
The Wallpaper can't be changed by using RMB on the desktop.
(If you do so; the menu pops up, loads, crashes and makes the desktop unusable for 15 seconds till you can use it properly)

**Super-Key Issue**
When you press the Super-Key its supposed to open the Start-Menu on my Notebook (It is in the settings set so)
Its randomly working but often (can't give situation , it happens too randomly) it doesn't.

### STEPS TO REPRODUCE | 复现步骤

_Volume Issue_
Pressing the Volume buttons, using the Slider in the Settings

_Brightness Issue_
Using the intended buttons

_Wallpaper Setting Issue_
Using RMB on the Desktop for the Menu to appear and than select Wallpaper

_Super-Key_
Using Super-Key (It happens too  random to explain further)

### OBSERVED RESULT | 观察到的结果

_Volume_
No function of intended keys
Slider doesn't work but you can drag the entire window of the Settings

_Wallpaper_
Crashing of the menu, paralysis of the Desktop for 15 seconds

### EXPECTED RESULT | 期望的结果

Fixing or further help of the Issue
Fixing the Slider in the Settings

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

OS: Reborn OS (Archbased)
DE: Deepin 20.6

### ADDITIONAL INFORMATION | 额外补充

GPU: Intel Skylake GT2 [HD Graphics 520]
CPU: Intel i3-6006U (4) @ 2.000GHz

**Comment by BLumia** [comment]
> (f7: - / f8: +)

These should be function buttons that you probably need to use `Fn` key together or turn on `Fn-lock`, or pressing <kbd>F7</kbd> will result... well, <kbd>F7</kbd> get pressed, literally.

You can use `xev` command and then press these keys to check the keycode to see if it's working.

**Comment by BLumia** [comment]
> Wallpaper Issue

This is a known porting issue when not using deepin-kwin. See https://github.com/linuxdeepin/developer-center/issues/3557 and please track this issue in https://github.com/linuxdeepin/developer-center/issues/2283 instead.
