### ISSUE TITLE
deepin-terminal中ctrl-j, ctrl-k, ctrl-l, ctrl-i行为与其他终端不一致

### ISSUE THREAD

**Issue by ckf104** [linuxdeepin/developer-center#3564]
### SUMMARY | 问题概要

deepin-terminal不能正确接收到ctrl-j, ctrl-k, ctrl-l, ctrl-i等按键。

### STEPS TO REPRODUCE | 复现步骤

例如，尝试按下ctrl-v后，按下ctrl-k没有输出，但是在其它终端中（例如xfce4-terminal）能够输出^K。这导致上述涉及上述按键的按键映射不能够在vim中正确工作

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin-terminal 5.4.36

**Comment by zccrs** [comment]
@archiemeng

**Comment by ArchieMeng** [comment]
首先，这个操作的预期结果是：按下Ctrl+v后，按Ctrl+k能够输出 **^K** 吗？
如果是的话，至少5.4.39版本是可以出现这个操作的。

另外，能确认一下两个终端中跑的shell吗？设置中的shell页会显示。或者直接输入
```shell
ps -p $$
```
stty信息也可以看一下，Ctrl+v的操作是pty/tty处理的。
```shell
stty -a
```

**Comment by ckf104** [comment]
抱歉，因为其他原因又重装了一遍系统，重新尝试发现不再出现这个问题了
