### ISSUE TITLE
【deepin_V23_beta】【一般】【有空】【集成测试】【音乐】Deepin Music Freeze on Start with PipeWire

### ISSUE THREAD

**Issue by prometheusAmb** [linuxdeepin/developer-center#3568]
### SUMMARY | 问题概要

Deepin Music 6.2.20 freezes when pipewire with pipwire-pulse is used as backed audio server. It then starts playing after almost a minute. If the track is change the same freeze takes place. When system is in freeze, all UI elements are also frozen and become unresponsive.

On running music from terminal the following messages are shown:

2023-02-03, 13:54:16.822 [Warning] VlcError libvlc Error: "No active input"
2023-02-03, 13:54:16.823 [Warning] VlcError libvlc Error: "No active input"
2023-02-03, 13:54:16.823 [Debug  ] VlcPlayer: m_qvplayer->length() -1
2023-02-03, 13:54:16.823 [Warning] VlcError libvlc Error: "No active input"

Then there is a gap while the app freezes. After some time when the playback begins, the following message is dumped:

2023-02-03, 13:55:12.201 [Debug  ] Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

Other music apps such as VLC media player and SM Player are working fine without any issues.

I can confirm this behaviour started once I installed pipewire and pipewire-pulse from git on Deepin 20.8 community edition. I 

### STEPS TO REPRODUCE | 复现步骤

1. Clean install of Deepin Linux 20.8 CE
2. Pulesaudio does not work with microphone on bluetooth headset. Hence installed pipewire
3. Installed pipewire from git version 0.3.46 because pipewire bundled with deepin packages does not have pipewire-pulse and the latest git version of pipewire does not compile on deepin 20.8 because of dependency issues
4. replaced pulseaudio with pipewire and set up systemctl services at user level
5. pactl info: Server Name: PulseAudio (on PipeWire 0.3.46)
6. Start Deepin Music
7. Select a track
8. click "Play"

### OBSERVED RESULT | 观察到的结果

On doing the above, the UI freezes and there is no sound for several seconds (almost one minute). After this gap, music starts playing the track

### EXPECTED RESULT | 期望的结果

Deepin Music should start playing the track as soon as play is clicked

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Deepin Vesion 20.8
Deepin Music Version 6.2.20

### ADDITIONAL INFORMATION | 额外补充

Same behaviour can be observed if Deepin Music is compiled from git sources

**Comment by Decodetalkers** [comment]
Emm. if vlc is the same? I found that it seems warning is from vlc

**Comment by prometheusAmb** [comment]
Not the same in VLC. VLC media player starts playing the track immediately. So does SMPlayer. I think the real issue is not the vlc error but the Debug message:

_Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken._

**Comment by Decodetalkers** [comment]
pipwire is update to 0.3.65-6, I tried it on plasma, it works well..

**Comment by prometheusAmb** [comment]
The issue is not to do with pipewire. It is to do with deepin music. In my view there is some dbus call which is failing.

**Comment by lzwind** [comment]
deepin-music has fixed this problem later, please try to verify with 7.0.2.

**Comment by prometheusAmb** [comment]
Hello. Thanks for the update. I tried a fresh compile from the git branch. But there is an error:
***
CMake Error at src/music-player/CMakeLists.txt:9 (find_package):
  By not providing "FindDtkDeclarative.cmake" in CMAKE_MODULE_PATH this                                                                                        
  project has asked CMake to find a package configuration file provided by                                                                                     
  "DtkDeclarative", but CMake did not find one.                                                                                                                
                                                                                                                                                               
  Could not find a package configuration file provided by "DtkDeclarative"                                                                                     
  with any of the following names:                                                                                                                             
                                                                                                                                                               
    DtkDeclarativeConfig.cmake                                                                                                                                 
    dtkdeclarative-config.cmake                                                                                                                                
                                                                                                                                                               
  Add the installation prefix of "DtkDeclarative" to CMAKE_PREFIX_PATH or set                                                                                  
  "DtkDeclarative_DIR" to a directory containing one of the above files.  If                                                                                   
  "DtkDeclarative" provides a separate development package or SDK, be sure it                                                                                  
  has been installed. 
*****

What to do? Thanks

**Comment by BLumia** [comment]
> Could not find a package configuration file provided by "DtkDeclarative"

`dtkdeclarative` needs to be installed. You might need a most recent version of DTK as well.

**Comment by prometheusAmb** [comment]
Thanks. I installed dtkdeclarative but now cmake breaks on Qt5Config. i think the versions of qt5 available in Deepin 20.8 is lower than what is required.

**Comment by BLumia** [comment]
I guess the related `-dev` packages are missing. You might use `apt build-dep deepin-music` to get all required dependencies to build. Though that's a major version release for v23 and I'm not sure if it can build under v20, still worth a try IMO :)

**Comment by prometheusAmb** [comment]
apt build-dep says everything is up to date:). Will wait until deepin 23 is released for production use

**Comment by prometheusAmb** [comment]
@BLumia you were right! The dev packages were missing. I installed them with 
sudo apt install qt5-declarative

The project was built. 

The problem has gone away

Many thanks to all developers for fixing this so quickly!!
