### ISSUE TITLE
[Gentoo Linux] Desktop Background is black, and font can not be changed.

### ISSUE THREAD

**Issue by zhtengw** [linuxdeepin/developer-center#359]
The desktop background is only black. Wallpaper selections show nothing. And I can not change both the font type and font size. I have the qt5integration and qtstyleplugins installed. Please give me some tips to debug these issues.
Qt Version: 5.7.1
DDE: all components are the latest github release.

![2017-09-13 11 01 54](https://user-images.githubusercontent.com/3148769/30358063-b0b1e26a-9874-11e7-8f6e-4fecbf990d48.png)
![2017-09-13 11 02 35](https://user-images.githubusercontent.com/3148769/30358070-b9fabb8a-9874-11e7-8b97-ca4fb9fecce5.png)

**Comment by zhtengw** [comment]
The wallpapers issue is solved by building gdk-pixbuf and qtgui with libjpeg. But font type and font size still can not be changed.

**Comment by zhtengw** [comment]
Is there a way to confirm if dde-qt5integration works fine or not?

**Comment by hualet** [comment]
Fonts used by the applications have nothing to do with dde-qt5integration I think.
You can debug loading of Qt plugins by exporting QT_DEBUG_PLUGINS=1

**Comment by zhtengw** [comment]
I consider that the font issue is related to dde-qt5integration and qt5styleplugins because of this issue https://github.com/linuxdeepin/developer-center/issues/342#issuecomment-318972115. But from the plugins debug log, the dde-qt5integration and qt5styleplugins QT plugins are loaded. So are there other reasons of this issue occurring.

[dde-control-center_qtplugin_debug.txt](https://github.com/linuxdeepin/developer-center/files/1324216/dde-control-center_qtplugin_debug.txt)

**Comment by zhtengw** [comment]
The fonts issue disappear after the reinstallation of noto fonts. Can not reproduce now.
