### ISSUE TITLE
【deepin_20.9 】【一般】【有空】【集成测试】【DDE】系统托盘应用图标右键菜单项有概率无法选中,无法高亮

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/developer-center#3596]
### SUMMARY | 问题概要

deepinV20.8 系统托盘应用图标右键菜单项有概率无法选中,无法高亮

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepinV20.8和uos家庭版都有这个问题

### PRE-REQUIREMENT | 预置条件

安装deepinV20或者uos家庭版

### STEPS TO REPRODUCE | 复现步骤

1) 打开一个系统托盘有图标的应用，比如说qq、有道云笔记
2) 查看qq，有道云笔记系统托盘图标右键菜单是否能够正常高亮选中

不保证100%复现，但是出现概率非常大

### OBSERVED RESULT | 观察到的结果

系统托盘应用图标右键菜单项无法选中，无法高亮

### EXPECTED RESULT | 期望的结果

系统托盘应用图标右键菜单项能够选中，能够高亮

**Comment by Decodetalkers** [comment]
dde-dock的最新commit应该就是解决这个的。当初同事发现了后马上就被解决了。我想master版本是修好了的。可能要等发布

**Comment by tsic404** [comment]
关联issue https://github.com/linuxdeepin/developer-center/issues/3541

**Comment by luodeepin** [comment]
【验证环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Alpha2/deepin-desktop-community-23-Alpha2-amd64.iso

仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
     deb https://community-packages.deepin.com/beige/ beige main commercial community
包版本：dde-dock       6.0.12  
       dde-control-center 6.0.11-1
内核：Linux v23-PC 6.1.11-amd64-desktop-hwe #23.01.00.01 SMP PREEMPT_DYNAMIC Mon Feb 27 17:25:36 CST 2023 x86_64 GNU/Linux
【验证步骤】：问题单中描述的步骤

【验证结果】：通过
![录屏_dde-desktop_20230418152353](https://user-images.githubusercontent.com/96416089/232702651-f7d6b7cc-1b61-4842-be0e-cbb399d00e0b.gif)

**Comment by luodeepin** [comment]
在最新环境中验证通过
