### ISSUE TITLE
Deepin-Fix-Init

### ISSUE THREAD

**Issue by apsyhea** [linuxdeepin/developer-center#3609]
### SUMMARY | 问题概要

Deepin 20.8

Kernel 6.1

After updating packages:

```
dpkg: error while processing package deepin-fix-init (--configure):
 installed script subprocess after installing deepin-fix-init package returned error status 1
Errors occurred while processing the following packages:
 Deepin-Fix-Init
E: The /usr/bin/dpkg subprocess returned an error code (1)
```
```
sudo dpkg --configure -a
sudo apt dist-upgrade
sudo apt install -f
```
not worked

### SOFTWARE/OS VERSIONS | 软件/系统版本信息
apt version 5.0.2
aptitude 0.8.11

Dist: Deepin 20.8
Kernel 6.1
Internal Testing Chanel - yes

### PRE-REQUIREMENT | 预置条件

Updating system

### STEPS TO REPRODUCE | 复现步骤

apt update && apt upgrade

### OBSERVED RESULT | 观察到的结果

```
dpkg: error while processing package deepin-fix-init (--configure):
 installed script subprocess after installing deepin-fix-init package returned error status 1
Errors occurred while processing the following packages:
 Deepin-Fix-Init
E: The /usr/bin/dpkg subprocess returned an error code (1)
```

### EXPECTED RESULT | 期望的结果

...

**Comment by Zeno-sole** [comment]
sudo apt install fbterm

sudo dpkg-reconfigure deepin-fix-init

**Comment by Zeno-sole** [comment]
new version fixed

**Comment by apsyhea** [comment]
> new version fixed

Thanks bro )
