### ISSUE TITLE
【deepin_V23_beta】【一般】【有空】【发散测试】【系统】deepinv23-alpha2发布后 还有不规范的软件包版本

### ISSUE THREAD

**Issue by Rabenda** [linuxdeepin/developer-center#3613]
### SUMMARY | 问题概要

还有不规范的软件包版本

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin v23 alpha2

### STEPS TO REPRODUCE | 复现步骤

```bash
curl -s https://community-packages.deepin.com/beige/dists/beige/main/source/Sources.gz | zcat | grep "dsc" | awk '{print $3}' | uniq > deepin-alpha2.txt

cat deepin-alpha2.txt | grep u0
```

### OBSERVED RESULT | 观察到的结果

- [x] #3815
- [x] #3816
- [x] breeze_5.24.3-1+u001.dsc
- [x] brise_0.38.20210909-2+u001.dsc
- [x] coreutils_8.32-4.1+u001.dsc
- [ ] disomaster_5.0.7+u002.dsc
- [x] double-conversion_3.1.7-4+u007.dsc
- [ ] downloadmanager_5.3.69+u001.dsc
- [x] enchant-2_2.3.2-1+u002.dsc
- [x] fcitx-configtool_0.4.10.32-1+u003.dsc
- [x] fcitx-qt5_1.2.6.3-1+u001+deepin1.dsc
- [x] fcitx5-gtk_5.0.13-1+u001.dsc
- [x] fox1.6_1.6.57-1+u001.dsc
- [ ] freeimage_3.18.0+ds2-6+u001.dsc
- [ ] ghc_8.8.4-3+u001.dsc
- [ ] gnustep-base_1.27.0-deepin+u001.dsc
- [x] golang-github-djherbis-atime_1.1.0-2+u001.dsc
- [x] golang-github-miekg-dns_1.0.4+ds-1+u001.dsc
- [x] golang-github-urfave-cli_1.20.0-1+u001.dsc
- [ ] image-editor_1.0.14+u001.dsc
- [x] kcmutils_5.90.0-2+u001.dsc
- [x] kdecoration_5.24.3-1+u001.dsc
- [x] keyman-keyboardprocessor_11.0.101-3+u004.dsc
- [x] kscreenlocker_5.24.3-1+u001.dsc
- [ ] kwayland_5.90.0-1+u036.dsc
- [x] kwayland-server_5.24.3-1+u017.dsc
- [x] kyotocabinet_1.2.79-1+u004.dsc
- [x] libchardet_1.0.4-1+u001.dsc
- [x] libfcgi-perl_0.82+ds-1+u001.dsc
- [x] libfuture-io-perl_0.11-3+u001.dsc
- [x] libgwenhywfar_5.9.0-1+u001.dsc
- [x] libhangul_0.1.0+git20191003-2+u001.dsc
- [x] libkkc_0.3.5-7+u001.dsc
- [ ] libkkc-data_0.2.7-4+u001.dsc
- [x] libmock-sub-perl_1.09-2+u001.dsc
- [x] libskk_1.0.5-2+u001.dsc
- [x] libthumbnailator-java_0.4.17-1+u001.dsc
- [x] libunique_1.1.6-6+u001.dsc
- [x] libyuv_0.0~git20220427.de71c67-1+u001.dsc
- [x] lua-expat_1.3.0-5+u001.dsc
- [x] mesa_21.3.8-1+u004.dsc
- [ ] mozjs60_60.2.3-3+u001.dsc
- [x] #3906
- [x] opencc_1.1.3+ds1-5+u001.dsc
- [ ] org.deepin.note_6.0.0.3+u020.dsc
- [ ] pam_1.4.0-13+u009.dsc
- [ ] python-xlrd_1.2.0-2+u002.dsc
- [ ] python3.10_3.10.5-1+u002.dsc
- [x] qbs_1.22.1-2+u001.dsc
- [ ] seetaface-authorize_1.0.0.1-1+dde+u001.dsc
- [ ] seetaface-boxes_1.0.0.1-1+dde+u001.dsc
- [ ] seetaface-models_1.0.0-1+u002.dsc
- [ ] seetaface-tennis_1.0.0-1+u001.dsc
- [ ] shadow_4.11.1-1+u001.dsc
- [ ] sigscheme_0.9.1-1+u003.dsc
- [ ] skkdic_20210106-2+u002.dsc
- [x] svt-av1_0.9.1+dfsg-1+u001.dsc
- [x] tinycdb_0.78+u001.dsc
- [x] uim_1.8.8-4+deb10u5+u001+deepin1.dsc
- [x] unittest++_2.0.0-3+u001.dsc
- [ ] xine-lib-1.2_1.2.12-1+u005.dsc
- [ ] xorg-server_21.1.3-2+u013.dsc
- [x] xserver-xorg-input-libinput_1.2.1-1+u002.dsc
- [x] xserver-xorg-video-intel_2.99.917+git20210115-1+u001.dsc
- [x] xwayland_22.1.1-1+u006.dsc
- [x] zinnia_0.06-6+u001.dsc

**Comment by hudeng-go** [comment]
这个等obs接入后尝试进行批量处理。

**Comment by ArchieMeng** [comment]
qbs changelog已有PR: https://github.com/deepin-community/qbs/pull/1
@hudeng-go 改一下再合还是？

**Comment by luodeepin** [comment]
![02](https://user-images.githubusercontent.com/96416089/226500425-b7a53849-b697-4b9c-ab6c-1ef3e404dc0d.png)

已经合入的包

**Comment by ArchieMeng** [comment]
libkkc-data的data/models/text3/data.arpa大小超过100MB限制，需要LFS．之后再处理．

**Comment by BLumia** [comment]
> 大小超过100MB限制，需要LFS

libkkc-data 应该是当时因为这个原因而没迁移的包之一（还有几个别的）。当时的讨论结果应该是这类包直接在 obs 维护。 cc @hudeng-go

**Comment by hudeng-go** [comment]
> libkkc-data

done

**Comment by hudeng-go** [comment]
> > 大小超过100MB限制，需要LFS
> 
> libkkc-data 应该是当时因为这个原因而没迁移的包之一（还有几个别的）。当时的讨论结果应该是这类包直接在 obs 维护。 cc @hudeng-go

https://build.deepin.com/package/show/deepin:Develop:main/libkkc-data，已经在obs长创建了对应的project，使用osc工具初始化project源码然后进行更新吧？

**Comment by UTsweetyfish** [comment]
记得确保版本号的新旧关系，不要降级。
