### ISSUE TITLE
【deepin_V23_beta】【一般】【有空】【发散测试】【系统】deepinv23-alpha2发布后 还有kde软件版本不统一的问题

### ISSUE THREAD

**Issue by Rabenda** [linuxdeepin/developer-center#3614]
### SUMMARY | 问题概要

kde软件版本不统一的问题

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin v23 alpha2

### STEPS TO REPRODUCE | 复现步骤

```bash
curl -s https://community-packages.deepin.com/beige/dists/beige/main/source/Sources.gz | zcat | grep "dsc" | awk '{print $3}' | uniq > deepin-stage2.txt

cat deepin-alpha2.txt | grep 5.86
cat deepin-stage2.txt | grep 5.91
```

### OBSERVED RESULT | 观察到的结果

# 5.86
 - [x] baloo-kf5_5.86.0-1.dsc
 - [x] bluez-qt_5.86.0-1.dsc
 - [x] breeze-icons_5.86.0-1.dsc
 - [x] frameworkintegration_5.86.0-1.dsc
 - [x] kactivities-kf5_5.86.0-1.dsc
 - [x] kactivities-stats_5.86.0-1.dsc
 - [x] kcalcore_5.86.0-1.dsc
 - [ ] kcontacts_5.86.0-1.dsc
 - [x] kdav_5.86.0-1.dsc
 - [x] kdeclarative_5.86.0-1.dsc
 - [ ] kded_5.86.0-1.dsc
 - [x] kdnssd-kf5_5.86.0-1.dsc
 - [ ] kemoticons_5.86.0-1.dsc
 - [x] kfilemetadata-kf5_5.86.0-1.dsc
 - [x] kholidays_5.86.0-1.dsc
 - [x] khtml_5.86.0-1.dsc
 - [x] kinit_5.86.0-1.dsc
 - [x] kitemmodels_5.86.0-1.dsc
 - [x] kitemviews_5.86.0-1.dsc
 - [x] kjs_5.86.0-1.dsc
 - [x] kmediaplayer_5.86.0-1.dsc
 - [x] knotifyconfig_5.86.0-1.dsc
 - [x] kparts_5.86.0-1.dsc
 - [x] kpeople_5.86.0-1.dsc
 - [x] kplotting_5.86.0-1.dsc
 - [x] kpty_5.86.0-1.dsc
 - [x] kquickcharts_5.86.0-1.dsc
 - [x] kross_5.86.0-1.dsc
 - [x] ksyntax-highlighting_5.86.0-1.dsc
 - [x] ktexteditor_5.86.0-1.dsc
 - [x] kunitconversion_5.86.0-1.dsc
 - [x] kwidgetsaddons_5.86.0-1.dsc
 - [x] oxygen-icons5_5.86.0-1.dsc
 - [x] prison-kf5_5.86.0-1.dsc
 - [x] purpose_5.86.0-1.dsc
 - [x] qqc2-desktop-style_5.86.0-1.dsc
 - [x] syndication_5.86.0-1.dsc

# 5.91
 - [ ] networkmanager-qt_5.91.0-1.dsc

**Comment by hudeng-go** [comment]
剥离后移到community组件仓库，然后再评估是否继续只维护一个版本？

**Comment by luodeepin** [comment]
![Uploading 截图_选择区域_20230320142237.png…]()

验证通过

**Comment by BLumia** [comment]
@luodeepin 验错了吧，这不就是错误结果吗 :joy:

**Comment by Rabenda** [comment]
> ![截图_选择区域_20230320142237](https://user-images.githubusercontent.com/96416089/226262938-b0c25b19-e180-4385-a363-8f71152adf23.png)
> 
> 验证通过

这明显验收有误 版本没有统一成5.90 怎么就验收通过了呢

**Comment by Zeno-sole** [comment]
networkmanager-qt不是kde系列软件包

**Comment by Zeno-sole** [comment]
目前还没完全更新完毕 只处理了部分

**Comment by Rabenda** [comment]
> 

https://tracker.debian.org/pkg/networkmanager-qt
按照kde组维护 这个应该和kf统一版本

**Comment by Zeno-sole** [comment]
软件包不允许降级，目前决议是升级到5.90版本
