### ISSUE TITLE
【deepin_V23_alpha2】 - the start menu forget the settings after restart

### ISSUE THREAD

**Issue by vampywiz17** [linuxdeepin/developer-center#3617]
### SUMMARY | 问题概要

I set the start menu to a list view and category view, but after restart it full screen again.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Deepin V23 Alpha 2

### STEPS TO REPRODUCE | 复现步骤

1. Set the start menu style
2. Restart
3. It switch back to default

### OBSERVED RESULT | 观察到的结果

It forget the last used settings

### EXPECTED RESULT | 期望的结果

It remember the last used settings

**Comment by BLumia** [comment]
Under `org.deepin.dde.daemon.Launcher1` session bus, `Fullscreen` property seems cannot remember its value.

cc @zsien

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0425镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230425
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
