### ISSUE TITLE
[Dock] Custom icon themes make disk-mount dock icon invisible

### ISSUE THREAD

**Issue by avently** [linuxdeepin/developer-center#362]
Hello. Take a look at screenshot. I installed Paper icon theme on Manjaro and applyed it via QT5 config tool. As you can see disk-mount icon is invisible. It happens with other themes too. How to avoid it? Maybe i can somehow hide this icon from dock?

![deepinscreenshot_20170915234106](https://user-images.githubusercontent.com/7953703/30502620-bed5f974-9a6f-11e7-90eb-a9a08c0a9402.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
