### ISSUE TITLE
terminal opacity config not working

### ISSUE THREAD

**Issue by Dorfeuheinz** [linuxdeepin/developer-center#3631]
### SUMMARY | 问题概要

~/.config/deepin/deepin-terminal/config.conf 
I changed the opacity of the terminal to 80 and rebooted the system. Nothing changed. the terminal is still 100% opaque. please help me

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin v20.8

### STEPS TO REPRODUCE | 复现步骤

1. Download deepin terminal as mentioned on https://github.com/linuxdeepin/deepin-terminal
2. configure opacity to desired value at ~/.config/deepin/deepin-terminal/config.conf 

### OBSERVED RESULT | 观察到的结果

No change. 
completely opaque

### EXPECTED RESULT | 期望的结果

should have been transluscent

**Comment by BLumia** [comment]
Could you check if you enabled "Window Effect" (window manager compositing)? Does your window have a round corner? Could you provide a screenshot including the whole window? Thanks!

**Comment by Dorfeuheinz** [comment]
> 

Here u go.... thanks for the assistance
![Screenshot_20230212140024](https://user-images.githubusercontent.com/79535302/218300799-b89159af-3aa9-498f-b02c-ddecdc50128f.png)

**Comment by BLumia** [comment]
The "Transparency" option in the screenshot you provided refers to the dock bar instead of the terminal, you need to adjust the transparency of the terminal from the terminal's setting page (in-app, not from the dde-control-center)

**Comment by Dorfeuheinz** [comment]
yeah, the option is not available in the terminal, here take a look-
![Screenshot_20230212221825](https://user-images.githubusercontent.com/79535302/218324729-e5365cce-d91b-4ae3-8350-7f1e3a71c4c0.png)

**Comment by wineee** [comment]
Which version of deepin-terminal are you using?

**Comment by Dorfeuheinz** [comment]
> Which version of deepin-terminal are you using?

its v20.8, updated recently, been 4-5 days max

**Comment by BLumia** [comment]
We mean the version of deepin-terminal, not the version of DDE desktop. Try `apt policy deepin-terminal` to get the version.

**Comment by Dorfeuheinz** [comment]
> apt policy deepin-terminal

here u go:

`deepin-terminal:
  Installed: (none)
  Candidate: 5.4.39-1
  Version table:
     5.4.39-1 500
        500 https://com-store-packages.uniontech.com/appstore deepin/appstore amd64 Packages
     5.4.36-1+rb1 500
        500 https://community-packages.deepin.com/deepin apricot/main amd64 Packages
     5.4.35-1 500
        500 https://community-packages.deepin.com/deepin apricot/main amd64 Packages
     5.4.33-1 500
        500 https://community-packages.deepin.com/deepin apricot/main amd64 Packages
     5.4.28-1+rb1 500
        500 https://community-packages.deepin.com/deepin apricot/main amd64 Packages
     5.4.28-1 500
        500 https://community-packages.deepin.com/deepin apricot/main amd64 Packages
     5.4.0.20-1 -1
        100 /usr/lib/dpkg-db/status
`

**Comment by wineee** [comment]
>Installed: (none)

Did you compile the git version?

**Comment by Dorfeuheinz** [comment]
> > Installed: (none)
> 
> Did you compile the git version?

i just followed the exact steps mentioned on their git readme

**Comment by BLumia** [comment]
what if you install from your system repo (`sudo apt install deepin-terminal`) ? instead of build from source? The build from source instruction is for people who may interested hacking into the codebase.

**Comment by Dorfeuheinz** [comment]
> what if you install from your system repo (`sudo apt install deepin-terminal`) ? instead of build from source? The build from source instruction is for people who may interested hacking into the codebase.

let me try to reinstall it then. 
Also what do you mean by- ''The build from source instruction is for people who may interested hacking into the codebase'', could u please elaborate?

**Comment by Dorfeuheinz** [comment]
> what if you install from your system repo (`sudo apt install deepin-terminal`) ? instead of build from source? The build from source instruction is for people who may interested hacking into the codebase.

Btw that did the trick. Thanks so much. Really appreciate the help.
u guys are amazing. 

![Screenshot_20230214101326](https://user-images.githubusercontent.com/79535302/218641709-1fbcca6d-94c7-469f-aa33-be8b729fa119.png)

**Comment by BLumia** [comment]
> Also what do you mean by- ''The build from source instruction is for people who may interested hacking into the codebase'', could u please elaborate?

This means for people who want to contribute to the project by submitting patches or personally preferred to build from source.

> that did the trick.

Glad that fixes the issue. Will close this issue now :)

**Comment by Dorfeuheinz** [comment]
sure. thanku all again for helping me out with this. really appreciate it.
