### ISSUE TITLE
【任务栏】多次随机移动切换插件区域的图标顺序后，部分图标没显示但是有占位

### ISSUE THREAD

**Issue by tsic404** [linuxdeepin/developer-center#3633]
### SUMMARY | 问题概要

多次随机移动切换插件区域的图标顺序后，部分图标没显示但是有占位

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin_V23-alpha2

### PRE-REQUIREMENT | 预置条件

1.已经安装镜像：https://cdimage.uniontech.com/daily-iso/image-beige/20230202/deepin-23-beige-amd64-20230202-151941.iso
2.  将任务栏大小设置为最小
3.  任务栏为时尚模式

### STEPS TO REPRODUCE | 复现步骤

多次随机移动切换插件区域的图标顺序
![file-read-598609](https://user-images.githubusercontent.com/48748112/218355603-4c1c5335-b9b1-4c08-b8bb-086195afdf83.gif)

### OBSERVED RESULT | 观察到的结果

部分图标没显示但是有占位

### EXPECTED RESULT | 期望的结果

插件图标顺序调整正确

**Comment by kegechen** [comment]
1. 图标主题是什么名 （v23-icon ？）消失的图标是什么应用的图标
2. 麻烦提供一下dde-qt5integration 版本（ apt policy dde-qt5integration ）和 任务栏日志 （~/.cache/deepin/dde-dock/dde-dock.log）

**Comment by kegechen** [comment]
图标是作为 editor 放到 dlistview 中，快速拖动时 TrayGridView::onUpdateEditorView ，有概率出现 editor 被 close 但是没有再次open，导致 beginDrag 时indexWidget为空退出，无法开始拖拽。图标也是从 editor （widget）的 icon 获取，所以图标也空了。

**Comment by zccrs** [comment]
@kegechen @zccrs 明天解决

**Comment by tsic404** [comment]
托盘已重构
