### ISSUE TITLE
Cannot Alt-tab from CS:GO to Firefox

### ISSUE THREAD

**Issue by zaplo00** [linuxdeepin/developer-center#364]
When I play CS:GO and have Firefox on second monitor Alt-tab brings preview window and CS shows in it, fully animated. But the window switcher never goes away and you have to Alt-Tab again to "Desktop" and then only desktop is shown and i have to manually open firefox which is minimized.

**Comment by felixonmars** [comment]
You may want to kill deepin-wm-switcher and use kwin as a workaround.

**Comment by hualet** [comment]
@sonald

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
