### ISSUE TITLE
【玲珑】下载器中打开“浏览器”接管设置，重启浏览器后，该设置不生效

### ISSUE THREAD

**Issue by kamiyadm** [linuxdeepin/developer-center#3648]
### SUMMARY | 问题概要

![image](https://user-images.githubusercontent.com/61131058/218954996-da1145b1-a89c-4a8c-8f14-a77109d0970e.png)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

镜像：deepin-v23-alpha2

下载器版本：5.3.69；浏览器版本：6.0.22

### STEPS TO REPRODUCE | 复现步骤

1. 打开下载器，主菜单-设置-接管设置，打开浏览器按钮
2. 打开浏览器，访问网站：https://download.qt.io/community_releases/5.9/5.9.0-rc2/
3. 右键点击文件，选择“使用下载器下载”，能正常弹出下载器下载窗口
4. 重启浏览器，重复步骤2、3中操作，观察界面显示

### OBSERVED RESULT | 观察到的结果

重启浏览器后，重新使用下载器下载，又提示打开浏览器接管而不是弹出下载器窗口

### EXPECTED RESULT | 期望的结果

重启浏览器后，重新使用下载器下载，弹出下载器窗口

**Comment by zccrs** [comment]
这个问题应该要转移给内部团队

**Comment by vivianxf** [comment]
【验证环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Alpha2/deepin-desktop-community-23-Alpha2-amd64.iso
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-intergration-pr-104/testing/ ./
包版本：downloadmanager  ->5.3.70
内核：6.1.11
【验证步骤】：问题单中描述的步骤
【验证现象】：下载器中设置浏览器接管下载后，浏览器中下载可以正常唤起下载窗口
【验证结果】：通过

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0422镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230422
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
