### ISSUE TITLE
【玲珑】音乐和邮箱两个应用无法并存到托盘

### ISSUE THREAD

**Issue by kamiyadm** [linuxdeepin/developer-center#3649]
### SUMMARY | 问题概要

启动多个可以最小化到托盘的玲珑应用时，托盘只会显示一个图标

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

系统：deepin-v23-alpha2
软件: 任意版本org.deepin.music与org.deepin.mail

### STEPS TO REPRODUCE | 复现步骤

1. 打开邮箱，设置最小化到系统托盘，观察托盘图标是否有邮箱
2. 再打开音乐，再设置最小化到系统托盘，观察托盘图标是否有音乐和邮箱

### OBSERVED RESULT | 观察到的结果

托盘只会按启动顺序显示一个图标

### EXPECTED RESULT | 期望的结果

多个应用最小化到托盘时，能同时显示

**Comment by wineee** [comment]
ps:请关注内网镜像进度

**Comment by luodeepin** [comment]
验证环境：https://github.com/linuxdeepin/developer-center/issues/3991
验证结果：不通过
![录屏_选择区域_20230410132258](https://user-images.githubusercontent.com/96416089/230831969-61699613-5784-44c4-a68f-9dfd8cf89a34.gif)

**Comment by kamiyadm** [comment]
玲珑的runtime里有一份qt5integration的so，应该是它把外面的环境盖住了，更新runtime里的 qt5intergration即可

**Comment by babyfengfjx** [comment]
@kegechen  帮忙备注下此问题当前的详细情况，需要测试这边开展的相关活动，以便正确理解和处理当前issue内容。

**Comment by kamiyadm** [comment]
> 玲珑的runtime里有一份qt5integration的so，应该是它把外面的环境盖住了，更新runtime里的 qt5intergration即可

https://cooperation.uniontech.com/app/1c4062ac-cc50-4f6c-9d7d-52906b78a291/62fefa8bfd5cc26af57c4b42/630719e7cf74a8b0029d1256?from=insite

**Comment by kegechen** [comment]
https://cooperation.uniontech.com/public/record/643ca627fa4138fe617814f2 
![image](https://user-images.githubusercontent.com/23466548/232359509-4637e312-e7b6-4d27-a88e-b7b1553e3b7f.png)

**Comment by kegechen** [comment]
详细请看集成单里卖弄的集成说明 @babyfengfjx @luodeepin

**Comment by kamiyadm** [comment]
测试范围说明：
1. 安装linglong-bin
2. 修改仓库地址，ll-cli repo modify http://10.0.36.228:9001 --name develop-snipe
3. 安装org.deepin.music和org.deepin.mail，若应用已存在，安装一个仓库里其他应用即可把runtime引入
4. ll-cli list 查看org.deepin.Runtime 23.0.0.9版本是否已安装
5. 启动邮箱和音乐，观察托盘是否有两个图标存在，存在则bug已修复

**Comment by babyfengfjx** [comment]
@luodeepin   请根据上方修改后的地址开展验证，通过后，即时处理issue状态，并可以同步给研发验证结论信息。

**Comment by vivianxf** [comment]
【验证环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Alpha2/deepin-desktop-community-23-Alpha2-amd64.iso
仓库：ll-cli repo modify http://10.0.36.228:9001/ --name develop-snipe
包版本：org.deepin.music ：7.0.29   org.deepin.mail：5.4.28
内核：6.1.11
【验证步骤】：问题单中描述的步骤
【验证现象】：最小化音乐和邮箱到托盘，可以正常展示两个图标
【验证结果】：通过
