### ISSUE TITLE
[Gentoo Linux] startdde build error: undefined: SettingsBackendLike

### ISSUE THREAD

**Issue by zhtengw** [linuxdeepin/developer-center#365]
With go-gir-generator-1.0.1, startdde will be built failed with "undefined: SettingsBackendLike". A [patch ](https://github.com/zhtengw/deepin-overlay/blob/master/dev-go/go-gir-generator/files/go-gir-generator-1.0.1-SettingsBackendLike.patch) can fix this issue. I know that both Arch and Fedora are using this patch to fix the issue. 

Strangely, in some other's gentoo system, startdde can be built **without** the patch for go-gir-generator, but got errror "undefined: SettingsBackend" **with** the patch. More previous conversation can be found in [this issue](https://github.com/zhtengw/deepin-overlay/issues/28).

I don't know what cause the undefined error. Need someone's help.

**Comment by felixonmars** [comment]
It depends on gobject-introspection's version.

See https://cr.deepin.io/#/c/16880/

**Comment by zhtengw** [comment]
Thank you @felixonmars. You help a lot.
