### ISSUE TITLE
【玲珑】网易音乐云首页“发现音乐““个性推荐”无法访问

### ISSUE THREAD

**Issue by kamiyadm** [linuxdeepin/developer-center#3653]
### SUMMARY | 问题概要

玲珑应用网易云音乐，在“发现音乐”下 “个性推荐”，提示网络不给力，无法访问
![image](https://user-images.githubusercontent.com/61131058/218965641-832ecab7-e94e-4294-a859-d60ffabe6499.png)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

系统：deepin-v23-alpha2
软件：com.163.music/1.2.1

### PRE-REQUIREMENT | 预置条件

通过玲珑正常安装网易云音乐

### STEPS TO REPRODUCE | 复现步骤

 1.  打开网易音乐云，观察首页【发现音乐】是否可以正常展示及浏览

### OBSERVED RESULT | 观察到的结果

“发现音乐”下 “个性推荐”，提示网络不给力

### EXPECTED RESULT | 期望的结果

首页可以正常展示及浏览

**Comment by wineee** [comment]
网易云音乐 api 变了，没有更新 linux 客户端，应该和玲珑无关

**Comment by zccrs** [comment]
> 网易云音乐 api 变了，没有更新 linux 客户端，应该和玲珑无关

@babyfengfjx 测一下非玲珑版本的网易云，确认一下

**Comment by kamiyadm** [comment]
> > 网易云音乐 api 变了，没有更新 linux 客户端，应该和玲珑无关
> 
> @babyfengfjx 测一下非玲珑版本的网易云，确认一下

这个我测过v20的deb版本是没问题的，然后当前玲珑的网易云是用v20 deb转过来的，怀疑是v23系统上某些so不兼容，导致这里跪了

**Comment by zccrs** [comment]
> > > 网易云音乐 api 变了，没有更新 linux 客户端，应该和玲珑无关
> > 
> > 
> > @babyfengfjx 测一下非玲珑版本的网易云，确认一下
> 
> 这个我测过v20的deb版本是没问题的，然后当前玲珑的网易云是用v20 deb转过来的，怀疑是v23系统上某些so不兼容，导致这里跪了

可以试一下V23上装原生deb

**Comment by kamiyadm** [comment]
> > > > 网易云音乐 api 变了，没有更新 linux 客户端，应该和玲珑无关
> > > 
> > > 
> > > @babyfengfjx 测一下非玲珑版本的网易云，确认一下
> > 
> > 
> > 这个我测过v20的deb版本是没问题的，然后当前玲珑的网易云是用v20 deb转过来的，怀疑是v23系统上某些so不兼容，导致这里跪了
> 
> 可以试一下V23上装原生deb

我魔改过v20的deb到v23安装，现象是一样的

**Comment by kamiyadm** [comment]
> > > > 网易云音乐 api 变了，没有更新 linux 客户端，应该和玲珑无关
> > > 
> > > 
> > > @babyfengfjx 测一下非玲珑版本的网易云，确认一下
> > 
> > 
> > 这个我测过v20的deb版本是没问题的，然后当前玲珑的网易云是用v20 deb转过来的，怀疑是v23系统上某些so不兼容，导致这里跪了
> 
> 可以试一下V23上装原生deb

我魔改过v20的deb到v23安装，现象是一样的。如果deb在v23上适配一下再转成玲珑，或者玲珑在安装这种v20应用时带上v20的base环境，应该就能修复

**Comment by babyfengfjx** [comment]
在V20版本就有该问题，一直未作修复：https://pms.uniontech.com/bug-view-171407.html

**Comment by zccrs** [comment]
> 在V20版本就有该问题，一直未作修复：https://pms.uniontech.com/bug-view-171407.html

可以作为一个已知问题跟踪，但是需要厂商解决

**Comment by vivianxf** [comment]
和运营经理沟通得出结论，当前已经与厂商终止合作，无法获取上游更新，issue做关闭处理
在能维持主要功能的基础上，保持应用在架

**Comment by vivianxf** [comment]
刷新状态
