### ISSUE TITLE
【玲珑】新邮件到达的消息通知，点击查看无法唤起邮箱

### ISSUE THREAD

**Issue by kamiyadm** [linuxdeepin/developer-center#3657]
### SUMMARY | 问题概要

点击消息通知，无法唤起邮箱客户端
![image](https://user-images.githubusercontent.com/61131058/218969934-963ee7e9-e69f-42d2-a3ad-8122b89abda9.png)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

系统：deepin-v23-alpha2

### PRE-REQUIREMENT | 预置条件

已设置开启弹窗提醒

### STEPS TO REPRODUCE | 复现步骤

1、点击编写邮件，打开新到达提醒
2、等待系统通知有新到达邮件
3、点击通知弹框上的 查看按钮

### OBSERVED RESULT | 观察到的结果

点击查看无法唤起邮箱客户端

### EXPECTED RESULT | 期望的结果

点击查看可以唤起邮箱客户端

**Comment by zccrs** [comment]
这是玲珑程序的通用问题？

**Comment by kamiyadm** [comment]
是的，通知这块没适配

**Comment by kamiyadm** [comment]
> 这是玲珑程序的通用问题？

是的，通知这块还没适配

**Comment by SuperEffie** [comment]
【验证结论】：验证通过
【录屏信息】:
![录屏_dde-widgets_20230308132927](https://user-images.githubusercontent.com/58986464/223627619-760a9fd9-f44d-49c9-9dfa-9791122a0a14.gif)

**Comment by vivianxf** [comment]
【验证环境】：
镜像地址： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230419/deepin-23-beige-amd64-20230419-132858.iso
仓库地址：
deb https://ci.deepin.com/repo/deepin/deepin-community/stable/ beige main community commercial
deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-intergration-pr-110/testing/ ./
内核：6.1.11
【验证步骤】：问题单中描述的步骤
【验证现象】：可以通过弹出的通知唤起邮箱
【验证结果】：通过

**Comment by kamiyadm** [comment]
当前修改dde-session-ui及dde-widget的方式有问题，将换其他方案
