### ISSUE TITLE
【玲珑】点击浏览器桌面快捷方式图标，无法打开浏览器

### ISSUE THREAD

**Issue by kamiyadm** [linuxdeepin/developer-center#3658]
### SUMMARY | 问题概要

发送桌面图标到桌面后，通过桌面文件无法双击打开浏览器；
浏览器内创建某个网页的快捷方式，创建的快捷方式无法显示正确的图标。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

系统：deepin-v23-alpha2

### PRE-REQUIREMENT | 预置条件

安装玲珑版本浏览器

### STEPS TO REPRODUCE | 复现步骤

1、打开浏览器，在浏览器内打开百度页面
2、点击主菜单，点击更多，点击创建快捷方式，点击创建按钮
3、点击桌面快捷图标
4、检查启动器内快捷图标显示

### OBSERVED RESULT | 观察到的结果

1. 点击桌面快捷图标无反应
2. 启动器内不显示创建的快捷图标

### EXPECTED RESULT | 期望的结果

1. 点击桌面快捷图标，可正常打开
2. 启动器内显示创建的快捷图标

**Comment by xzl01** [comment]
关联issue https://github.com/linuxdeepin/developer-center/issues/3807

**Comment by black-desk** [comment]
这个应该是好了 我尝试一下 昨天看是好的(

**Comment by zccrs** [comment]
注意在提到testing仓库后转给测试验证

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0508镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230508
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0516镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
