### ISSUE TITLE
【deepin_V20.9】【严重】【立即】【子项目集成测试】【输入法】【fcitx5】在启动器中打开 Fcitx5 和 Fcitx5配置，无响应

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#3659]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

镜像地址：https://cdimage.uniontech.com/community/releases/20.8/deepin-desktop-community-20.8-amd64.iso
内核版本：Linux v207-PC 5.18.17-amd64-desktop-community-hwe https://github.com/linuxdeepin/developer-center/issues/20 SMP PREEMPT_DYNAMIC Fri Dec 30 10:04:38 CST 2022 x86_64 GNU/Linux
仓库 deb https://proposed-packages.deepin.com/dde-apricot/ unstable main contrib non-free
fcitx5 5.0.21-1deepin1

### PRE-REQUIREMENT | 预置条件

安装镜像 ： https://cdimage.uniontech.com/community/releases/20.8/deepin-desktop-community-20.8-amd64.iso
添加仓库：deb https://proposed-packages.deepin.com/dde-apricot/ unstable main contrib non-free
升级至最新版本
按照测试建议，安装：sudo apt install fcitx5 fcitx5-chinese-addons fcitx5-frontend-qt5 fcitx5-frontend-qt6 fcitx5-frontend-gtk3

### STEPS TO REPRODUCE | 复现步骤

打开启动器 - 打开 Fcitx5 - 打开 Fcitx5配置

### OBSERVED RESULT | 观察到的结果

无法打开 Fcitx5 和 Fcitx5配置
![录屏_选择区域_20230215162714](https://user-images.githubusercontent.com/96416089/218974181-90756c6e-25f4-444a-b145-aaf20b1b7afa.gif)

### EXPECTED RESULT | 期望的结果

正常打开 Fcitx5 和 Fcitx5配置

**Comment by babyfengfjx** [comment]
@asterwyx 请帮忙优化~

**Comment by Decodetalkers** [comment]
fcitx5是已经在运行了啊。。不然输入窗口哪里来的。。不过configtool没有起来

**Comment by asterwyx** [comment]
请联系输入法团队将fcitx4设置为控制中心输入法插件的强依赖，以便在卸载fcitx4的时候一并卸载控制中心输入法插件。

**Comment by luodeepin** [comment]
请将fcitx4设置为控制中心输入法插件的强依赖，以便在卸载fcitx4的时候一并卸载控制中心输入法插件。

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0425镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230425
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
