### ISSUE TITLE
【deepin_V23_alpha2】【一般】【有空】【发散测试】【输入法】deepin-editor 中不显示预编辑文本

### ISSUE THREAD

**Issue by zsien** [linuxdeepin/developer-center#3667]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

fcix5: 5.0.14.1
deepin-editor: 5.9.14

### PRE-REQUIREMENT | 预置条件

fcitx5 设置中「在程序中显示预编辑文本」选项开启

### STEPS TO REPRODUCE | 复现步骤

1. 打开文本编辑器
2. 切换到拼音
3. 尝试输入

### OBSERVED RESULT | 观察到的结果

预编辑文本的内容

### EXPECTED RESULT | 期望的结果

显示预编辑文本的内容

**Comment by zccrs** [comment]
@zsien 推动今天做一个新版本集成

**Comment by zsien** [comment]
> @zsien 推动今天做一个新版本集成

下周会推一个版本 本地冒烟测试通过 就会集成一波（

**Comment by zsien** [comment]
已集成 deepin-editor 6.0.9
