### ISSUE TITLE
【输入法】缩小输入法高级设置窗口后，控制中心无法再次唤醒

### ISSUE THREAD

**Issue by zsien** [linuxdeepin/developer-center#3670]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin-fcitx5configtool-plugin：5.0.8
fcitx5：5.0.15.5

### STEPS TO REPRODUCE | 复现步骤

1. 打开控制中心-键盘和语言，在输入法配置中点击高级设置按钮
2. 缩小高级设置窗口
3. 控制中心再次点击高级设置按钮
4. 多次点击高级设置按钮

### OBSERVED RESULT | 观察到的结果

1. 缩小输入法高级设置窗口后，控制中心无法再次唤醒 见附件视频
2. 会出现多个高级设置窗口

https://user-images.githubusercontent.com/8380597/219276993-e91ab7e0-df6a-4c11-b288-f813325d5cd9.mp4

### EXPECTED RESULT | 期望的结果

1. 控制中心正常唤醒
2. 只显示一个高级设置窗口

**Comment by zsien** [comment]
同 linuxdeepin/developer-center#3671

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0425镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230425
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
