### ISSUE TITLE
【输入法】多次点击打开高级设置，关闭高级设置时需要重复关闭多遍

### ISSUE THREAD

**Issue by zsien** [linuxdeepin/developer-center#3671]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin-fcitx5configtool-plugin：5.0.8
fcitx5：5.0.15.5

### STEPS TO REPRODUCE | 复现步骤

1. 点击多次高级设置按钮，关闭高级设置按钮

### OBSERVED RESULT | 观察到的结果

1. 需要关闭多次

### EXPECTED RESULT | 期望的结果

1. 关闭一次

**Comment by SuperEffie** [comment]
【验证结论】：问题已修复，多次点击“高级设置”按钮，只需关闭一次窗口
【录屏信息】：


![Image](https://user-images.githubusercontent.com/58986464/223660652-f928fe28-57e3-4b71-a5e4-42da1a4ee334.gif)

**Comment by SuperEffie** [comment]
问题提交集成后，将status改为Done，目前为testing

**Comment by SuperEffie** [comment]
【验证环境】
【镜像地址】：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230425/deepin-23-beige-amd64-20230425-103152.iso
【版本信息】：fcitx5：5.0.23-0deepin1
【验证结论】：测试通过，关闭此issue
【录屏信息】：

https://user-images.githubusercontent.com/58986464/236403182-e174df08-6b71-4f72-b44f-94853d257504.mp4
