### ISSUE TITLE
【deepin_V23_beta】【一般】【有空】【发散测试】【输入法】“ + ”添加 、删除 “ - ” 按钮未与列表右对齐

### ISSUE THREAD

**Issue by zsien** [linuxdeepin/developer-center#3672]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin-fcitx5configtool-plugin：5.0.10

### STEPS TO REPRODUCE | 复现步骤

打开控制中心的输入法设置

### OBSERVED RESULT | 观察到的结果

“ + ”添加 、删除 “ - ” 按钮未与列表右对齐

![圖片](https://user-images.githubusercontent.com/8380597/219278027-757f8ef8-4c60-4af3-8afd-fe9c3eedbabd.png)

### EXPECTED RESULT | 期望的结果

两个按钮整体向右偏移，与列表右对齐

**Comment by zsien** [comment]
linuxdeepin/deepin-fcitx5configtool-plugin#6 已修复

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0425镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230425
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
