### ISSUE TITLE
[linuxdeepin/qt5integration] QSpinBox 上下箭头图标不一致

### ISSUE THREAD

**Issue by Decodetalkers** [linuxdeepin/developer-center#3674]
### SUMMARY | 问题概要

![image](https://user-images.githubusercontent.com/60290287/219279440-5e2abea8-98f6-434e-a6c0-a52287bf99bb.png)

https://pms.uniontech.com/bug-view-182635.html
发现问题的原始bug

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin v20 or v23 alpha

### STEPS TO REPRODUCE | 复现步骤

```cpp
#include "mainwindow.h"

#include <QTimeEdit>

MainWindow::MainWindow(QWidget *parent)
  : QMainWindow(parent)
{
    setCentralWidget(new QTimeEdit);
}

MainWindow::~MainWindow()
{
}
```

### OBSERVED RESULT | 观察到的结果

上下箭头渲染出问题了，拉长时候上面渲染变长了

### EXPECTED RESULT | 期望的结果

一样大

**Comment by Zeno-sole** [comment]
@18202781743  请走流程提交集成，而不是指派到我这里

**Comment by Zeno-sole** [comment]
@18202781743 请提交集成流程 ，参见 [协作流程](https://wiki.deepin.org/zh/05_HOW-TO/06_%E5%8F%82%E4%B8%8Edeepin%E8%B4%A1%E7%8C%AE%E7%9B%B8%E5%85%B3/deepin-community%E5%8D%8F%E4%BD%9C%E6%B5%81%E7%A8%8B)，请指派给 @babyfengfjx

**Comment by babyfengfjx** [comment]
@Zeno-sole 看这个是哪一笔提交包含的修复，关联一下信息。

**Comment by vivianxf** [comment]
【验证镜像】：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
【验证版本】：dde-control-center->6.0.20
【验证步骤】：提单的步骤
【验证现象】：符合预期
【验证结论】：通过
