### ISSUE TITLE
【deepin_V23_beta】【一般】【有空】【发散测试】【控制中心】在商店安装wps office 2019 for Linux后，首次打开通知中心内容全部只剩下wps相关的

### ISSUE THREAD

**Issue by Decodetalkers** [linuxdeepin/developer-center#3677]
### SUMMARY | 问题概要

在商店安装wps office 2019 for Linux后，首次打开通知中心内容全部只剩下wps相关的
![image](https://user-images.githubusercontent.com/60290287/219285962-ad785e87-b5fe-4d91-9414-47f84332e2d7.png)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

【环境信息】

镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/20230117/deepin-23-beige-amd64-20230117-103530.iso
内核 Linux JIM-PC 5.18.17-amd64-desktop-hwe #23.01.00.06 SMP PREEMPT_DYNAMIC Mon Oct 31 17:25:49 CST 2022 x86_64 GNU/Linux
控制中心  6.0.8
wps office  2019 for Linux：11.1.0.11664

### PRE-REQUIREMENT | 预置条件

预置条件】：
1.已经安装镜像：https://cdimage.uniontech.com/daily-iso/image-beige/20230117/deepin-23-beige-amd64-20230117-103530.iso

### STEPS TO REPRODUCE | 复现步骤

【操作步骤】

在应用商店下载安装wps office  2019 for Linux
打开控制中心-通知，查看通知界面内容展示    ---【预期结果】：通知界面展示内容应该包含其他应用

### OBSERVED RESULT | 观察到的结果

【实际结果】：在商店安装wps office  2019 for Linux后，首次打开通知中心内容全部只剩下wps相关的，重启控制中心可以恢复

### EXPECTED RESULT | 期望的结果

正常显示

**Comment by Decodetalkers** [comment]
不能复现。。目前

**Comment by zccrs** [comment]
@babyfengfjx 试试有没有比较稳定的重现方式，testing仓库中可以再测一下

**Comment by babyfengfjx** [comment]
@SuperEffie ,可以提供复现环境。

**Comment by babyfengfjx** [comment]
@SuperEffie  确认当前问题是否已经复现，如复现后，提交环境给研发，并将问题指派到开发名下处理。

**Comment by SuperEffie** [comment]
【验证环境】
【镜像地址】：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230425/deepin-23-beige-amd64-20230425-103152.iso
【版本信息】：dde-control-center：6.0.17
【验证结论】：无法复现，应用通知界面显示正常
【截图信息】：
![通知中心](https://user-images.githubusercontent.com/58986464/236405011-412a27b2-0e4b-459c-a856-715a7dfe4026.jpg)
