### ISSUE TITLE
【输入法】中州韻被显示在「Chinese - unknown」下

### ISSUE THREAD

**Issue by zsien** [linuxdeepin/developer-center#3685]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin-fcitx5configtool-plugin: 5.0.11

### STEPS TO REPRODUCE | 复现步骤

1. 安装 fcitx5-rime
2. 进入添加输入法界面

### OBSERVED RESULT | 观察到的结果

中州韻被显示在「Chinese - unknown」下

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0425镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230425
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
