### ISSUE TITLE
Run on dGPU

### ISSUE THREAD

**Issue by sanchitsamuel** [linuxdeepin/developer-center#369]
This more like feature request, It would be great to have an option to run on dGPU via launcher using PRIME.
Thanks. :)

**Comment by alexwender1** [comment]
Can Deepin Desktop Environment integrate PRIME Offloading into the interface?

For example, in GNOME:
![fedora-25-linux-to-offer-better-dual-gpu-integration-in-the-gnome-3-22-desktop-509680-3](https://user-images.githubusercontent.com/45263160/68035516-8fdc6d00-fca2-11e9-9721-6a0d2ac61232.jpg)

Graphics Driver Manager does not support hybrid configurations (Intel / AMD); and only allow ALL the system to run on Dedicated GPU (generating higher laptop battery consumption).

Although the AMD GPU driver comes bundled with the Linux kernel; users cannot use Dedicated GPU in deepin. The adoption of PRIME Offloading would be most welcome.

@BLumia @hualet

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.

**Comment by lxwndr** [comment]
I open a new topic in #2083
