### ISSUE TITLE
【输入法】两条分割线粗细样式不统一

### ISSUE THREAD

**Issue by zsien** [linuxdeepin/developer-center#3690]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin-fcitx5configtool-plugin：5.0.10

### STEPS TO REPRODUCE | 复现步骤

进入添加输入法界面

### OBSERVED RESULT | 观察到的结果

两条分割线粗细样式不统一
![圖片](https://user-images.githubusercontent.com/8380597/219299058-12d90857-e67d-407e-8cad-02824a860143.png)

**Comment by SuperEffie** [comment]
提示依赖关系不满足：
![Image](https://user-images.githubusercontent.com/58986464/223376844-ba2248d1-fe56-4060-8f18-26401029eb2c.jpg)

**Comment by SuperEffie** [comment]
【添加仓库】：db https://proposed-packages.deepin.com/beige-testing unstable main dde community commercial
【验证结论】：验证通过
【截图信息】：
![Image](https://user-images.githubusercontent.com/58986464/223610940-784de378-e442-4813-8fe5-8a2c37ae42ec.jpg)

**Comment by SuperEffie** [comment]
待提交集成验证后将状态改为Done，目前状态为testing

**Comment by Zeno-sole** [comment]
@18202781743 请提交集成流程 ，参见 [协作流程](https://wiki.deepin.org/zh/05_HOW-TO/06_%E5%8F%82%E4%B8%8Edeepin%E8%B4%A1%E7%8C%AE%E7%9B%B8%E5%85%B3/deepin-community%E5%8D%8F%E4%BD%9C%E6%B5%81%E7%A8%8B)，请指派给 @babyfengfjx

**Comment by SuperEffie** [comment]
【验证环境】
【镜像地址】：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230424/deepin-23-beige-amd64-20230424-121733.iso
【验证结论】：问题已修复，关闭此issue
【截图信息】：
![线](https://user-images.githubusercontent.com/58986464/233937413-e523a2b9-186e-41f4-8eea-ae9ac0315403.jpg)
