### ISSUE TITLE
[控制中心] deepin-face coredump

### ISSUE THREAD

**Issue by Decodetalkers** [linuxdeepin/developer-center#3693]
### SUMMARY | 问题概要

deepin-face有概率存在coredump

coredump 文件 https://cooperation.uniontech.com/recordfile/63c667c76b3284460dbc78bd/undefined

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

    镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/20230117/
    内核版本： 5.18.17-amd64-desktop-hwe #23.01.00.06  
    dde-control-center版本：6.0.8 ；dde-dock：6.0.8.1

### PRE-REQUIREMENT | 预置条件

【预置条件】：社区版镜像，/etc/apt/source.list文件中添加仓库：deb https://pools.uniontech.com/deepin-beige/ beige main commercial community

### STEPS TO REPRODUCE | 复现步骤

    sudo apt install systemd-coredump下载工具
    查看/var/lib/systemd/coredump路径下日志                           --【预期结果】：不存在deepin-face-coredump日志文件

### OBSERVED RESULT | 观察到的结果

【实际结果】：存在deepin-face-coredump日志

### EXPECTED RESULT | 期望的结果

不存在coredump文件

**Comment by Decodetalkers** [comment]
Same Issue: https://github.com/linuxdeepin/developer-center/issues/3699

**Comment by babyfengfjx** [comment]
重复的 #3699 已经解决。
