### ISSUE TITLE
清理不再维护的项目

### ISSUE THREAD

**Issue by snyh** [linuxdeepin/developer-center#37]
初步打算

因为项目非常多，而且历史原因等很多因素，　没有任何人能１００％确定一个项目的性质．

所以
https://github.com/martyr-deepin   快速整理不需要的项目到这里．　　然后周五之前大家在这个组织下如果看到需要留在linuxdeepin组织下的就单独提出．　

然后在linuxdeepin的介绍上给出　https://github.com/martyr-deepin　　　的地址

github 过期项目列表及处理建议:
**直接删除(先移动到martyr-deepin并重命名加上delete)**
- [x] depin-mutter (空项目, 系当初建立时拼写错误)
- [x] deepin-bug-reporter (被 deepin-feedback 替代)
- [x] django-paste （未做任何开发, 且没系统没有用到过)
- [x] oauth2app (未做任何开发, 且系统没有用到过)
- [x] go-qt5　(未做任何开发，　且系统没有用到过)
- [x] go-dbus 代码以及合并到go-lib的dbus目录

**备份后移动到 martyr-deepin**
- [x] DeepinWin, forked from phcole/DeepinWin
- [x] deepin-os-upgrader
- [x] deepin-download-service
- [x] deepin-screenshot-v3
- [x] deepin-themes (被 deepin-icon-theme 替代)
- [x] deepin-ui
- [x] deepin-utils
- [x] deepin-user-manual (老版 manual)
- [x] dde-workspace
- [X] deepin-webkit
- [X] deepin-compiz
- [X] deepin-translator
- [X] dde-dock-applets
- [X] qml-dde-dock-applet
- [X] qml-gettext-plugin
- [X] deepin-game
- [X] deepin-talk
- [X] deepin-media-player
- [X] python-vte
- [X] pystorm
- [X] deepin-storm
- [X] pypulseaudio
- [X] liblunar
- [X] fcitx
- [X] emacs-webkit
- [X] linuxdeepin-application-development-manual
- [X] deepin-system-tray
- [X] deepin-system-settings
- [X] deepin-settings-daemon
- [X] deepin-gsettings
- [X] deepin-gnome-shell-extensions
- [X] deepin-gnome-shell
- [X] deepin-emacs-old
- [X] deepin-crash-reporter
- [X] desktop-plugins
- [X] deepin-software-center-data
- [X] deepin-libwm
- [X] dltk

如果有搞错的地方请及时指出
@linuxdeepin/app-team @linuxdeepin/dde-team @linuxdeepin/system-team

**Comment by cxbii** [comment]
我预感某人已经哭晕在厕所了。
周五后，我给每个活着的项目挨个加简单的介绍。

**Comment by snyh** [comment]
但这种方式潜在的风险是　以前打包如果用到了github地址．　可能会被影响　@leaeasy

**Comment by fasheng** [comment]
同意这种方案, 新老项目的名字容易混淆, 如果非要展现的话, 就放到其他组里吧~

**Comment by derekdai** [comment]
我也讚成, 雖然可以在 README.md 中加說明, 但在項目列表上不好看出來

**Comment by fasheng** [comment]
github 过期项目列表及处理建议:
**直接删除**
- [ ] depin-mutter (空项目, 系当初建立时拼写错误)
- [ ] deepin-bug-reporter (被 deepin-feedback 替代)

**备份后移动到 martyr-deepin**
- [ ] DeepinWin, forked from phcole/DeepinWin
- [ ] django-paste, forked from digitaljhelms/django-paste
- [ ] oauth2app, forked from hiidef/oauth2app
- [ ] go-qt5
- [ ] go-dbus
- [ ] deepin-os-upgrader
- [ ] deepin-download-service
- [ ] deepin-screenshot-v3
- [ ] deepin-themes (被 deepin-icon-theme 替代)
- [ ] deepin-ui
- [ ] deepin-utils
- [ ] deepin-user-manual (老版 manual)
- [ ] dde-workspace
- [ ] deepin-webkit
- [ ] deepin-compiz
- [ ] deepin-translator
- [ ] dde-dock-applets
- [ ] qml-dde-dock-applet
- [ ] qml-gettext-plugin
- [ ] deepin-game
- [ ] deepin-talk
- [ ] deepin-media-player
- [ ] python-vte
- [ ] pystorm
- [ ] deepin-storm
- [ ] pypulseaudio
- [ ] liblunar
- [ ] fcitx
- [ ] emacs-webkit
- [ ] linuxdeepin-application-development-manual
- [ ] deepin-system-tray
- [ ] deepin-system-settings
- [ ] deepin-settings-daemon
- [ ] deepin-gsettings
- [ ] deepin-gnome-shell-extensions
- [ ] deepin-gnome-shell
- [ ] deepin-emacs-old
- [ ] deepin-crash-reporter
- [ ] desktop-plugins
- [ ] deepin-software-center-data
- [ ] deepin-libwm
- [ ] dltk

如果有搞错的地方请及时指出
@linuxdeepin/app-team @linuxdeepin/dde-team @linuxdeepin/system-team

**Comment by fasheng** [comment]
@manateelazycat 不如以后继续维护 python-vte, 然后改名叫 deepin-vte, 这样方便以后移植 deepin-ternminal 到其他发行版~

**Comment by manateelazycat** [comment]
@fasheng 新版终端用vala编写， 通过 gir 直接调用官方的 vte 控件， 以后不会维护我们自己的 vte 控件了。
新版的应该超级容易移植到其他发行版

**Comment by choldrim** [comment]
路过，好奇：martyr-deepin 的 martyr 这个词感觉用得很好，@snyh 是参考哪里的呀？

**Comment by fasheng** [comment]
好, 今天开始清理~

**Comment by fasheng** [comment]
太多鼠标操作手都点麻了, 简单学了些前端自动化测试技术几行代码搞定 ;)

```html
<!doctype html>
<html>
  <head>
    <title>Github Project Transfer</title>
    <link rel="stylesheet" href="http://code.jquery.com/qunit/qunit-1.21.0.css">
    <script src="http://code.jquery.com/jquery-2.2.0.min.js"></script>
    <script src="http://code.jquery.com/qunit/qunit-1.21.0.js"></script>
    <script src="http://cdnjs.w3cbus.com/FuncUnit/2.0.4/funcunit.js"></script>
  </head>

  <body>
    <div id="qunit"></div>
    <div id="qunit-test-area"></div>

    <!-- <script src="demo_04.js"></script> -->
	<script type="text/javascript">
     F.speed = 100;
     F.timeout = 10 * 1000;

     var prjs = ["deepin-webkit",
                 "deepin-compiz",
                 "dltk"];

     module("Modele Transfer");

     test("transfer github projects", function () {
       for(var i=0; i < prjs.length; i++) {
         var prj = prjs[i];
         var header = i + " " + prj + ": ";
         F.open('https://github.com/linuxdeepin/' + prj + "/settings");

         F('input#rename_field[value=' + prj + ']').visible(header + "ready");
         F('button:contains("Transfer")').click();
         F('input#confirm_repository_name').type(prj);

         // remove comments to confirm operation
         // F('input#confirm_new_owner').visible(header + "found input 2");
         // F('input#confirm_new_owner').type("martyr-deepin[enter]");
         // F('.flash-notice').visible(header + "pass"); // Moving repository to martyr-deepin
       }
     });
	</script>
  </body>
</html>
```
btw: 需要在 `chromium --args --disable-web-security` 下执行以允许 js 跨域操作

**Comment by hualet** [comment]
哈哈，厉害

**Comment by choldrim** [comment]
>太多鼠标操作手都点麻了, 简单学了些前端自动化测试技术几行代码搞定 ;)
>...

哈，学习了～

**Comment by derekdai** [comment]
讚

**Comment by snyh** [comment]
漏掉了老版深度商店．　刚手动迁移过去了．

**Comment by snyh** [comment]
gitcafe清理列表 
- [ ] depin-mutter 
- [ ]  deepin-bug-reporter
- [ ]  deepin-os-upgrader
- [ ]  deepin-download-service
- [ ]  deepin-ui
- [ ]  deepin-utils
- [ ]  dde-workspace
- [ ]  deepin-webkit
- [ ]  deepin-compiz
- [ ]  deepin-translator
- [ ]  dde-dock-applets
- [ ]  deepin-game
- [ ]  deepin-talk
- [ ]  deepin-media-player
- [ ]  python-vte
- [ ]  pystorm
- [ ]  deepin-storm
- [ ]  pypulseaudio
- [ ]  liblunar
- [ ]  fcitx
- [ ]  emacs-webkit
- [ ]  deepin-system-tray
- [ ]  deepin-system-settings
- [ ]  deepin-settings-daemon
- [ ]  deepin-gsettings
- [ ]  deepin-gnome-shell-extensions
- [ ]  deepin-gnome-shell
- [ ]  deepin-emacs-old
- [ ]  deepin-crash-reporter
- [ ]  dde-desktop-plugins
- [ ]  deepin-software-center-data
- [ ]  deepin-libwm
- [ ]  dltk
