### ISSUE TITLE
【deepin_V23_beta】【一般】【有空】【集成测试】【DDE】【控制中心】控制中心顶部 tab 背景矩形圆角变形，选中矩形右侧被裁切

### ISSUE THREAD

**Issue by zsien** [linuxdeepin/developer-center#3701]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

dde-control-center: 6.0.9.1-1

### STEPS TO REPRODUCE | 复现步骤

打开控制中心任意带 tab 的界面

### OBSERVED RESULT | 观察到的结果

选项背景矩形圆角变形，选中矩形右侧被裁切
![圖片](https://user-images.githubusercontent.com/8380597/219529587-09a0bafd-ee92-4082-a881-b08ed953a37f.png)

### EXPECTED RESULT | 期望的结果

正常显示圆角

**Comment by Decodetalkers** [comment]
fix in https://github.com/linuxdeepin/dde-control-center/pull/1256

**Comment by SuperEffie** [comment]
【验证环境】
【镜像地址】：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230420/deepin-23-beige-amd64-20230420-102652.iso
【版本信息】：dde-control-center：6.0.15
【验证结论】：问题已修复
【截图信息】：
![输入法圆角](https://user-images.githubusercontent.com/58986464/233821235-2423c19d-7fdd-4519-aaf4-8b68c341765f.jpg)

**Comment by SuperEffie** [comment]
更新状态
