### ISSUE TITLE
[控制中心] 首次进入系统不显示系统监视器

### ISSUE THREAD

**Issue by Decodetalkers** [linuxdeepin/developer-center#3706]
### SUMMARY | 问题概要

首次进入系统时候，控制中心个性化部分没有系统监视器的插件选项

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

[环境]

https://cdimage.uniontech.com/daily-iso/image-beige/20230117/

应用版本：6.0.4

### STEPS TO REPRODUCE | 复现步骤

[前置条件]

[步骤]

1. 正常装机（首次进入系统）

2. 查看控制中心-个性化-任务栏-插件

3. 重启机器

4.再次查看控制中心-个性化-任务栏-插件

### OBSERVED RESULT | 观察到的结果

系统监视器的选项没有

**Comment by tsic404** [comment]
重复issue，记得好像是子项目自己里面做了判断
