### ISSUE TITLE
【输入法】右键输入法托盘图标，点击预测后状态没改变

### ISSUE THREAD

**Issue by zsien** [linuxdeepin/developer-center#3708]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

fcitx5: 5.0.15.6-1

### PRE-REQUIREMENT | 预置条件

切换输入法为拼音

### STEPS TO REPRODUCE | 复现步骤

右键任务栏拼音输入法图标，点击“预测”

### OBSERVED RESULT | 观察到的结果

点击“预测”后，状态没有变化，用户无法从界面判断是否勾选成功

### EXPECTED RESULT | 期望的结果

点击“预测”后，有勾选状态

**Comment by zsien** [comment]
deepin-community/libdbusmenu-qt#1 修复了 dbus menu 菜单项的 icon 未显示。
fcitx5-chinese-addons 文案已经修改，待同步上游。

**Comment by luodeepin** [comment]
https://github.com/linuxdeepin/developer-center/issues/4038
[镜像]
https://cdimage.uniontech.com/community/releases/23-Alpha2/deepin-desktop-community-23-Alpha2-amd64.iso

[仓库]
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-intergration-pr-78/testing/ ./
deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
deb https://community-packages.deepin.com/beige/ beige main commercial community


[环境版本]  
fcitx5-chinese-addons  5.0.17-0deepin+rb2
fcitx5  5.0.23-0deepin+rb3

验证通过，点击预测后 显示 预测禁用/预测启用，启用后可以正常预测后续内容 
![截图_dde-desktop_20230412132138](https://user-images.githubusercontent.com/96416089/231358581-c2760648-3784-4802-8293-64cfbb1da436.png)
