### ISSUE TITLE
rfkill开启蓝牙功能失效

### ISSUE THREAD

**Issue by zsien** [linuxdeepin/developer-center#3713]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

bluez  5.64.2-deepin1
bluez-obexd 5.64.2-deepin1
libbluetooth3 5.64.2-deepin1

### PRE-REQUIREMENT | 预置条件

清华同方E500+蓝牙适配器（ Cambridge Silicon Radio, Ltd Bluetooth Dongle）+爱国者蓝牙耳机

已开启蓝牙，并与蓝牙耳机配对成功

### STEPS TO REPRODUCE | 复现步骤

1. 通过命令关闭蓝牙，参考命令 rfkill block bluetooth
2. 通过命令开启蓝牙，参考命令 rfkill unblock bluetooth
3. 检查蓝牙状态，参考命令  hciconfig dev

### OBSERVED RESULT | 观察到的结果

蓝牙设备状态是down的状态
![圖片](https://user-images.githubusercontent.com/8380597/219535924-ec8e2411-06e1-49e8-8ee9-e851ee09da89.png)

### EXPECTED RESULT | 期望的结果

蓝牙设备状态为UP

**Comment by dengbo11** [comment]
I can't recurrent this bug on the latest v23 image. maybe the problem is related to the device.

**Comment by SuperEffie** [comment]
暂时无法复现，连接FIIL Key蓝牙耳机，使用以上命令，未复现bug单中bug，相关截图如下：
![蓝牙](https://user-images.githubusercontent.com/58986464/220307186-b17834f4-8581-42c7-a82c-252a0d537121.png)
[设备信息20230221_173702.txt](https://github.com/linuxdeepin/developer-center/files/10792055/20230221_173702.txt)

**Comment by babyfengfjx** [comment]
如无法复现，请按照偶现问题跟踪。

**Comment by SuperEffie** [comment]
[问题备注]：v23 beta中依然无法复现该问题，做遗留处理，多版本跟踪
[截图信息]：
![2](https://github.com/linuxdeepin/developer-center/assets/58986464/db702d84-ef54-4fbd-8bbb-cb35e8596ec8)
![1](https://github.com/linuxdeepin/developer-center/assets/58986464/cf4eaa6c-bef3-442f-ba20-a20d298eb0bd)

**Comment by SuperEffie** [comment]
目前无法复现该issue，先将该issue做关闭处理~
