### ISSUE TITLE
[dde-control-center] 输入法插件

### ISSUE THREAD

**Issue by Decodetalkers** [linuxdeepin/developer-center#3720]
### SUMMARY | 问题概要

[步骤]

1.切换系统语言为American English-美国英语，点击注销后重新进入系统;

2.检查键盘和语言中的输入法界面翻译情况

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

1.内核：Linux uos-PC 5.18.17-amd64-desktop-hwe #23.01.00.06
2.社区镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/20230105/
3.社区镜像：deepin-23-beige-amd64-20230105-145449.iso

### PRE-REQUIREMENT | 预置条件

打开控制中心到输入法插件位置

### STEPS TO REPRODUCE | 复现步骤

没有翻译
![image](https://user-images.githubusercontent.com/60290287/219542693-77f59978-fbee-49a2-87d0-fde912b60a75.png)

### OBSERVED RESULT | 观察到的结果

翻译

### EXPECTED RESULT | 期望的结果

翻译

**Comment by Decodetalkers** [comment]
现在似乎是做完了吧。。那关掉？

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0420镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230420
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
