### ISSUE TITLE
[DDE Control Center] 手动设置时间，点击确定和取消都没有反应

### ISSUE THREAD

**Issue by Decodetalkers** [linuxdeepin/developer-center#3723]
### SUMMARY | 问题概要

控制中心时间日期点击确定没有感知到的生效，
原始链接
https://pms.uniontech.com/bug-view-182049.html

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/20221229/deepin-23-beige-amd64-20221229-094359.iso
内核版本： 5.18.17-amd64-desktop-hwe #23.01.00.06        

控制中心 6.0.5

### PRE-REQUIREMENT | 预置条件

【预置条件】：

1. 已经安装镜像：https://cdimage.uniontech.com/daily-iso/image-beige/20221229/deepin-23-beige-amd64-20221229-094359.iso

### STEPS TO REPRODUCE | 复现步骤

进入控制中心 - 时间日期 -  关闭       自动同步配置
手动设置时间，点击 确定                        --【预期结果】：可以正常设置，且能让用户感知动作生效

### OBSERVED RESULT | 观察到的结果

时间可以设置，只是用户感知不到动作生效
![image](https://user-images.githubusercontent.com/60290287/219545029-6c1f337b-c315-415f-9778-c9d643b81aaa.png)

### EXPECTED RESULT | 期望的结果

感知生效

**Comment by Decodetalkers** [comment]
https://github.com/linuxdeepin/dde-control-center/commit/5a8843b6b216714df7512af225c48bdbb4a6e9d0

该commit解决

**Comment by babyfengfjx** [comment]
@xuqi27837288  请在19号最新镜像或升级最新仓库后验证。

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0420镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230420
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
