### ISSUE TITLE
dde-control-center 调节屏幕缩放存在多余无法自动消失的通知信息

### ISSUE THREAD

**Issue by Decodetalkers** [linuxdeepin/developer-center#3729]
### SUMMARY | 问题概要

打开控制中心，调节屏幕缩放
受到两条通知信息，其中多于一条即将设置屏幕缩放

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/20230112/ 
内核版本： 5.18.17-amd64-desktop-hwe #23.01.00.06  
dde-control-center版本：6.0.7.1 ；dde-dock：6.0.7

### STEPS TO REPRODUCE | 复现步骤

打开控制中心，显示中调节屏幕缩放

### OBSERVED RESULT | 观察到的结果

两个通知

### EXPECTED RESULT | 期望的结果

一条通知

### ADDITIONAL INFORMATION | 额外补充

![image](https://user-images.githubusercontent.com/60290287/219566230-55c76e6d-7c0e-4e00-99e4-5fca53d7c807.png)

**Comment by xuqi27837288** [comment]
修复 by 进击的小浣熊~~测试通过~

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0422镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230422
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
