### ISSUE TITLE
No fallback to the primary screen when disconnecting the secondary one

### ISSUE THREAD

**Issue by PoisonousJohn** [linuxdeepin/developer-center#373]
How to reproduce:
- Connect the secondary monitor
- Choose "Second display only" in display settings
- Disconnect secondary monitor.
- Primary monitor remains disabled

Expected behaviour:
Since primary monitor is the only one left upon disconnecting, it should be automatically enabled.

**Comment by hualet** [comment]
@jouyouyun

**Comment by jouyouyun** [comment]
What's the version of startdde? And upload the file generated by command 'journalctl /usr/bin/startdde > /tmp/dde.log', thanks!

**Comment by PoisonousJohn** [comment]
startdde 3.1.16-1, attached log right after disconnecting secondary display

Best regards,
Ivan Fateev.

2017-10-19 10:57 GMT+03:00 wen <notifications@github.com>:

**Comment by jouyouyun** [comment]
Exec `rm ~/.config/deepin/startdde/display.json` and re-login, then try again.

**Comment by jouyouyun** [comment]
@PoisonousJohn is the bug solved?

**Comment by jouyouyun** [comment]
Fixed!

**Comment by PoisonousJohn** [comment]
Sorry for the delay. Yes, it seems to be fixed

Best regards,
Ivan Fateev.

2017-11-21 11:18 GMT+03:00 wen <notifications@github.com>:
