### ISSUE TITLE
DDE 控制中心 部分机型系统信息里面的内存信息显示错误

### ISSUE THREAD

**Issue by Decodetalkers** [linuxdeepin/developer-center#3736]
### SUMMARY | 问题概要

![image](https://user-images.githubusercontent.com/60290287/219573440-49f6649e-1f8b-4dff-851d-3ed251385561.png)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/20230105/deepin-23-beige-amd64-20230105-145449.iso
内核版本：Linux v233-PC 5.18.17-amd64-desktop-hwe #23.01.00.06 SMP PREEMPT_DYNAMIC Mon Oct 31 17:25:49 CST 2022 x86_64 GNU/Linux     
控制中心   6.0.6.3

原始链接: https://pms.uniontech.com/bug-view-182331.html

### PRE-REQUIREMENT | 预置条件

已经安装镜像：https://cdimage.uniontech.com/daily-iso/image-beige/20230105/deepin-23-beige-amd64-20230105-145449.iso

### STEPS TO REPRODUCE | 复现步骤

进入控制中心 - 系统信息 -  查看信息显示情况

### OBSERVED RESULT | 观察到的结果

内存信息显示错误

### EXPECTED RESULT | 期望的结果

显示的所有信息均正确

**Comment by xzl01** [comment]
dtk已经对此进行修改，需要确认是否被修复

**Comment by luodeepin** [comment]
镜像：https://cdimage.uniontech.com/community/releases/23-Alpha/deepin-desktop-community-23-Alpha-amd64.iso

仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/stable/ beige main community commercial
     deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
     deb https://community-packages.deepin.com/beige/ beige main commercial community

内核：Linux v23-PC 6.1.11-amd64-desktop-hwe #23.01.00.10 SMP PREEMPT_DYNAMIC Wed Apr 12 14:44:55 CST 2023 x86_64 GNU/Linux

控制中心 dde-control-center6.0.15
dde-daemon 6.0.15

验证不通过
![截图_dde-desktop_20230421161233](https://user-images.githubusercontent.com/96416089/233581501-beb13b4b-1b15-4e75-9e50-8afdaaf1fa20.png)

**Comment by Decodetalkers** [comment]
之前沟通过了，不用解决，就是一个特性

**Comment by luodeepin** [comment]
用户实际的内存是 16G，对比 V20.9显示的是16G，但是V23 中显示错误为 15G
https://pms.uniontech.com/bug-view-182331.html

**Comment by xzl01** [comment]
讨论认为，应更修改控制中心的文案，显示为可用内存，物理内存大小需要root权限获取。故不应展示（如果确实要展示物理内存大小 需要考虑从有root权限的后端获取

**Comment by luodeepin** [comment]
y

**Comment by luodeepin** [comment]
验证通过
控制中心 6.0.22
![截图_选择区域_20230704104516](https://github.com/linuxdeepin/developer-center/assets/96416089/fab0e87f-7312-45b9-83a7-779331dfa821)
