### ISSUE TITLE
[dde-control-center] UI 个性化，透明度调节和窗口圆角slider没有显示当前比率

### ISSUE THREAD

**Issue by Decodetalkers** [linuxdeepin/developer-center#3737]
### SUMMARY | 问题概要

![image](https://user-images.githubusercontent.com/60290287/219574387-24e24129-c74c-44e1-b782-770bb6eacaee.png)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

dde-control-center：6.0.7
dde-daemon：6.0.9
dde-dock：6.0.7
dde-launcher：6.0.7
dde-appearance：1.0.4

### STEPS TO REPRODUCE | 复现步骤

1. 打开到“个性化”－“桌面版”中，观察透明度调节　和　窗口圆角项的值

2. 分别手动调节设置条到任意位置，，观察透明度调节　和　窗口圆角项值的变化

### OBSERVED RESULT | 观察到的结果

1. 只有设置条的相对位置或进度(0.4)，没有具体对应的当前值或比例显示

2. 设置即时生效，无相应值的变化显示

### EXPECTED RESULT | 期望的结果

1. 设置条的位置或进度正常0.4，右上角分别有对应具体值或比例显示

2. 设置即时生效，右上角分别有对应的具体值跟随变化，显示准确

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0508镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230508
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
