### ISSUE TITLE
[onboard] 屏幕键盘没有完全进行汉化和国际化，需要添加翻译

### ISSUE THREAD

**Issue by Decodetalkers** [linuxdeepin/developer-center#3738]
### SUMMARY | 问题概要

屏幕键盘现在是dde团队维护，但是没有完全进行汉化和国际化，需要添加翻译
![image](https://user-images.githubusercontent.com/60290287/219577643-d644eaa6-a435-4a83-8892-69e712dbae40.png)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin v23
onboard

### PRE-REQUIREMENT | 预置条件

设置语言简体中文

### STEPS TO REPRODUCE | 复现步骤

  1.  屏幕键盘图标上点击鼠标右键   - 进入设置    ---【预期结果】：设置中语言正确

**Comment by xuqi27837288** [comment]
修复 by 呆呆鹅 ~测试通过

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0516镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
