### ISSUE TITLE
【任务栏】预览窗口显示内容花屏

### ISSUE THREAD

**Issue by tsic404** [linuxdeepin/developer-center#3739]
### SUMMARY | 问题概要

应用窗口非最小尺寸时，在任务栏的悬浮框显示模糊

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

内核版本： 5.18.17-amd64-desktop-hwe #23.01.00.06  
dde-control-center版本：6.0.8 ；dde-dock：6.0.9.2

### STEPS TO REPRODUCE | 复现步骤

打开某个应用如控制中心，最小化窗口后，向右拖动窗口
鼠标移动至任务栏控制中心图标上，观察悬浮窗口显示

### OBSERVED RESULT | 观察到的结果

预览窗口花屏显示
![file-read-598545](https://user-images.githubusercontent.com/48748112/219578190-8e58b7be-c37c-4803-979a-baba2bd6232b.gif)

### EXPECTED RESULT | 期望的结果

显示清晰

**Comment by luodeepin** [comment]
【验证环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Alpha2/deepin-desktop-community-23-Alpha2-amd64.iso

仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
     deb https://community-packages.deepin.com/beige/ beige main commercial community
包版本：dde-dock       6.0.12  
       dde-control-center 6.0.11-1
内核：Linux v23-PC 6.1.11-amd64-desktop-hwe #23.01.00.01 SMP PREEMPT_DYNAMIC Mon Feb 27 17:25:36 CST 2023 x86_64 GNU/Linux
【验证步骤】：问题单中描述的步骤

【验证结果】：通过
![截图_选择区域_20230418153850](https://user-images.githubusercontent.com/96416089/232706312-f1171c17-14e8-45a4-a638-927a0790dcce.png)
