### ISSUE TITLE
【任务栏】时尚模式下，任务栏背景框与插件边框不同时跟随控制中心窗口圆角设置而变化

### ISSUE THREAD

**Issue by tsic404** [linuxdeepin/developer-center#3743]
### SUMMARY | 问题概要

时尚模式下，任务栏背景框与插件边框不同时跟随控制中心窗口圆角设置而变化。
关联pms链接：https://pms.uniontech.com/bug-view-184783.html

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

内核版本： 5.18.17-amd64-desktop-hwe #23.01.00.06  
dde-control-center版本：6.0.8 ；dde-dock：6.0.8.1

### STEPS TO REPRODUCE | 复现步骤

控制中心-个性化-桌面版-透明度调节为较低值（0.4左右）
调节个性化-桌面版下窗口圆角，观察任务栏背景框与插件边框圆角显示 

### OBSERVED RESULT | 观察到的结果

任务栏背景框与插件边框圆角跟随控制中心设置变化不同步，且任务栏背景框圆角较大时，插件边框依然为直角状态，显示有些突兀
![file-read-596909](https://user-images.githubusercontent.com/48748112/219581319-d8c7403e-eaa1-4356-b6cc-560a803d74e2.gif)
![file-read-596921](https://user-images.githubusercontent.com/48748112/219581344-a934eb92-930f-4a7a-8c7e-a16cf7263194.png)

### EXPECTED RESULT | 期望的结果

任务栏背景框与插件边框圆角跟随控制中心设置同步变化

**Comment by ComixHe** [comment]
在6.0.9.2中此现象消失，已修复: https://github.com/linuxdeepin/dde-dock/commit/36adcd8fc0b50d6ee6c2925dbc22797eeb4f807c

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0508镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230508
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
