### ISSUE TITLE
【deepin_V23_beta】【一般】【有空】【集成测试】【DDE】【控制中心】 键盘和语言 部分快捷键无法恢复默认快捷键

### ISSUE THREAD

**Issue by Decodetalkers** [linuxdeepin/developer-center#3745]
### SUMMARY | 问题概要

![image](https://user-images.githubusercontent.com/60290287/219584264-852ffb10-9db1-45c0-892c-524be2b47af5.png)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

dde-control-center=6.0.5

### STEPS TO REPRODUCE | 复现步骤

1.打开控制中心-键盘和语言-快捷键，修改部分快捷键为super

2.点击“恢复默认”按钮查看现象

### OBSERVED RESULT | 观察到的结果

部分快捷键不能恢复

### ADDITIONAL INFORMATION | 额外补充

恢复默认是调用org.deepin.dde.Keybinding1的Reset

**Comment by justforlxz** [comment]
无法重现

**Comment by justforlxz** [comment]
deepin-kwin 提供了注册 super+上/下 来最大化/还原窗口的脚本，脚本内容没有更新，里面存在判断是否存在一个全局的 dde 对象，已在 https://github.com/linuxdeepin/deepin-kwin/pull/150/files#diff-32ba152c5216068e17751b82b5dafca1a7b1023765bedf423995eb3f757b2b2a 进行了更新。

**Comment by justforlxz** [comment]
更新了 deepin-wm-dbus 中读取快捷键配置文件的文件名。

但是遇到了控制中心不显示窗口和工作区的快捷键，应该是过滤的id没对上。

**Comment by kegechen** [comment]
确认是否已经修复

**Comment by luodeepin** [comment]
在控制中心 6.0.22中验证通过
