### ISSUE TITLE
【deepin_V23_beta】【一般】【有空】【集成测试】【DDE】【控制中心】 连接不带接收器的蓝牙鼠标，此功能无效，依旧可以通过触摸板控制鼠标

### ISSUE THREAD

**Issue by Decodetalkers** [linuxdeepin/developer-center#3749]
### SUMMARY | 问题概要

使用鼠标蓝牙配对后插入鼠标禁止使用触控板没有启用
![image](https://user-images.githubusercontent.com/60290287/219588375-f9983087-7448-41d9-a6cf-860bb8280c38.png)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/20230117/deepin-23-beige-amd64-20230117-103530.iso
 内核 Linux JIM-PC 5.18.17-amd64-desktop-hwe #23.01.00.06 SMP PREEMPT_DYNAMIC Mon Oct 31 17:25:49 CST 2022 x86_64 GNU/Linux
控制中心  6.0.8

### STEPS TO REPRODUCE | 复现步骤

1. 使用蓝牙连接蓝牙鼠标
2. 进入控制中心 - 鼠标 -开启按钮“插入鼠标时禁用触控板 ”
3. 使用笔记本自带的触控板     

### OBSERVED RESULT | 观察到的结果

触控板正常使用

### EXPECTED RESULT | 期望的结果

【预期结果】：无法使用

**Comment by xzl01** [comment]
复现现象：在v20上表现为鼠标断开后触控板依然不能解除禁用，在v23上表现为鼠标连接无法禁用。建议对鼠标管理改为使用upower,同时提供无线键盘鼠标电量显示支持

**Comment by myml** [comment]
dde-daemon环境太难配置了

**Comment by Decodetalkers** [comment]
要更改为upower后端，绕过dde-daemon，因此是需要重写的部分，工作量相对大，赶不上

**Comment by Decodetalkers** [comment]
emm,新的蓝牙鼠标没有复现。。得拿到复现的鼠标。。daemon实现是没有问题的。。要找到可以复现的。这个不是upower做的事情。。

**Comment by kegechen** [comment]
daemon 相关

**Comment by kegechen** [comment]
@babyfengfjx  暂相关无设备

**Comment by kegechen** [comment]
@SuperEffie  @Decodetalkers 要一下设备测试

**Comment by xuqi27837288** [comment]
多台设备暂未复现到该问题，该问题先进行关闭处理，后续我们再关注一下，有问题再重新提单跟踪~

**Comment by SuperEffie** [comment]
v23 beta2镜像，内测更新至 2023/12/08，无法复现issue中问题，以偶现问题跟踪

**Comment by babyfengfjx** [comment]
@xuqi27837288  作为偶现问题进行跟踪。

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240201
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
