### ISSUE TITLE
【DDE】【控制中心】电池管理的设置没有被记住

### ISSUE THREAD

**Issue by Decodetalkers** [linuxdeepin/developer-center#3768]
### SUMMARY | 问题概要

在电池管理中，开启 显示剩余使用时间及剩余充电时间后，重启或注销电脑，之前设置没有被记住
![image](https://user-images.githubusercontent.com/60290287/219608469-34c789ab-8a37-4993-ae2a-7541d827ccb0.png)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

    镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/20230105/deepin-23-beige-amd64-20230105-145449.iso

    内核版本：Linux v233-PC 5.18.17-amd64-desktop-hwe #23.01.00.06 SMP PREEMPT_DYNAMIC Mon Oct 31 17:25:49 CST 2022 x86_64 GNU/Linux     

    控制中心   6.0.6.3

### STEPS TO REPRODUCE | 复现步骤

进入控制中心 - 电源 - 使用电池
开启 显示剩余使用时间及剩余充电时间    
注销或重启电脑
查看  显示剩余使用时间及剩余充电时间 设置情况    

### OBSERVED RESULT | 观察到的结果

显示剩余使用时间及剩余充电时间为关闭状态

### EXPECTED RESULT | 期望的结果

显示剩余使用时间及剩余充电时间为开启状态

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0420镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230420
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过

**Comment by kobe337** [comment]
【验证环境】：v23 beta
镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
仓库：deb https://community-packages.deepin.com/beige/ beige main commercial community
内核：Linux deepin-PC 6.1.11-amd64-desktop-hwe #23.01.00.14 SMP PREEMPT_DYNAMIC Fri May 12 14:47:29 CST 2023 x86_64 GNU/Linux
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
