### ISSUE TITLE
After updating Deepin the launcher does not work

### ISSUE THREAD

**Issue by Xeers** [linuxdeepin/developer-center#377]
I updated Arch-Deepin and the application launcher does not work. I have rebooted, I have tried many things but the launcher does not show the application icons or anything.
--

**Comment by felixonmars** [comment]
Please try deepin-desktop-schemas 3.1.17.20171013-1

**Comment by dodedodo33** [comment]
@Xeers same issue as https://github.com/linuxdeepin/developer-center/issues/376, should be fixed by felixonmars's update :)
