### ISSUE TITLE
Deepin Topbar

### ISSUE THREAD

**Issue by Xeers** [linuxdeepin/developer-center#378]
Arch-Deepin
System Tray shortcuts do not work if Topbar is enabled.
https://aur.archlinux.org/packages/deepin-topbar/#news

The Disks, Recycle Bin and Cable Connection icons do not appear in the dock.

**Comment by kirigayakazushin** [comment]
sorry, deepin-topbar is a community fan's work.
https://github.com/kirigayakazushin/deepin-topbar/issues

**Comment by Xeers** [comment]
ok
