### ISSUE TITLE
deepin-image-viewer  主线使用了玲珑特有命令

### ISSUE THREAD

**Issue by wineee** [linuxdeepin/developer-center#3786]
### SUMMARY | 问题概要

https://github.com/linuxdeepin/deepin-image-viewer/blob/master/src/com.deepin.imageViewer.service

```
[D-BUS Service]
Name=com.deepin.imageViewer
Exec=/usr/bin/ll-cli run org.deepin.image.viewer --exec deepin-image-viewer
```

这会影响其他系统打包！

这种更改应该使用 patch, 类似 https://github.com/linuxdeepin/deepin-music/tree/master/patches ， 只在玲珑应用

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

.

### STEPS TO REPRODUCE | 复现步骤

.

**Comment by wzyforgit** [comment]
这个问题应该玲珑先改吧，这种写法本来就是为了兼容开发中的玲珑，我记得完整版是要恢复正常写法的

**Comment by wineee** [comment]
github 的 master 应该放的就是完整版而不是玲珑特殊版，类似 deepin-music 那样把不兼容写成 patch 可以接受

**Comment by wzyforgit** [comment]
> 

然而团队内部并没有接到此类要求，你们的信息同步机制存在问题，并没有精确同步到具体的开发者头上

**Comment by black-desk** [comment]
1. 先参考 @wineee 的意见改成patch。
2. 这个问题是玲珑的问题。这个service文件应该由玲珑来patch，而不是在项目中patch。
3. 项目里面直接放着的代码，应当首先考虑的是从源码编译安装，装在宿主机上的场景。无论如何，sudo make install装的应用都应该能正常运行。

**Comment by justforlxz** [comment]
@wzyforgit 主仓库代码可以为多种打包方式进行适配，这种启动命令的都需要在 cmake 里对 in 文件进行变量替换才能安装到系统。

**Comment by wineee** [comment]
https://github.com/linuxdeepin/deepin-image-viewer/pull/130

**Comment by wineee** [comment]
https://github.com/linuxdeepin/deepin-image-viewer/blob/95ab92e386af576d5da866b6ab6ad8f69f801307/qimage-plugins/libraw/CMakeLists.txt#L47

仍然有玲珑相关问题，这个安装位置绝对不合理

**Comment by BLumia** [comment]
> https://github.com/linuxdeepin/deepin-image-viewer/blob/95ab92e386af576d5da866b6ab6ad8f69f801307/qimage-plugins/libraw/CMakeLists.txt#L47
> 
> 仍然有玲珑相关问题，这个安装位置绝对不合理

这个应该是找 Qt 的插件目录吧。不依赖 ECM 的情况下，这个可以确定位置吗？

**Comment by wineee** [comment]
> 这个应该是找 Qt 的插件目录吧。不依赖 ECM 的情况下，这个可以确定位置吗？

@black-desk Qt 的插件在玲珑的规范安装位置是什么？
