### ISSUE TITLE
【deepin_V23_beta】【一般】【有空】【集成测试】【DDE】【任务栏】开启显示最近使用应用后，重启进入桌面，任务栏出现一个名为Deepin Lock的锯齿图标

### ISSUE THREAD

**Issue by tsic404** [linuxdeepin/developer-center#3788]
### SUMMARY | 问题概要

开启显示最近使用应用后，重启进入桌面，任务栏出现一个名为Deepin Lock的锯齿图标

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

控制中心 6.0.6.3
dde-session-ui 6.0.5
dde-session-shell 6.0.5.2 
任务栏   6.0.7

### STEPS TO REPRODUCE | 复现步骤

1.在任务栏空白处，点击右键 进入任务栏设置 - 开启   显示最近使用应用
2. 重启 进入桌面 ，查看任务栏显示情况

### OBSERVED RESULT | 观察到的结果

任务栏出现一个名为Deepin lock的锯齿图标
![file-read-592001](https://user-images.githubusercontent.com/48748112/220511021-2925d5c9-fea0-4295-82a8-1bfc66de2633.png)

### EXPECTED RESULT | 期望的结果

各自的图标都显示正确且清晰(Deepin lock 不应该显示)

**Comment by vivianxf** [comment]
【验证环境】：
镜像地址： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230420/deepin-23-beige-amd64-20230420-102652.iso
仓库地址：
deb https://ci.deepin.com/repo/deepin/deepin-community/stable/ beige main community commercial
deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：6.1.11
【验证步骤】：问题单中描述的步骤
【验证现象】：符合预期
【验证结果】：通过

**Comment by kobe337** [comment]
【验证环境】：v23 beta
镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
仓库：deb https://community-packages.deepin.com/beige/ beige main commercial community
内核：Linux deepin-PC 6.1.11-amd64-desktop-hwe #23.01.00.14 SMP PREEMPT_DYNAMIC Fri May 12 14:47:29 CST 2023 x86_64 GNU/Linux
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
