### ISSUE TITLE
Qt 的字体大小、主题完全失效

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#379]
要在 `/etc/environment` 内加入 `QT_QPA_PLATFORMTHEME=gtk2` 才能解决问题
OS: Antergos
![deepinscreenshot_20171022232409](https://user-images.githubusercontent.com/20014762/31863548-7ab118f8-b781-11e7-97c9-d7233e2d417e.png)
![deepinscreenshot_20171022232623](https://user-images.githubusercontent.com/20014762/31863549-7adda0e4-b781-11e7-970e-f56b42d73044.png)

**Comment by felixonmars** [comment]
你的 deepin-qt5integration 在什么版本？

理论上这个问题在 deepin-qt5integration 0.2.3 就已经修复了：

https://github.com/linuxdeepin/qt5integration/commit/707655c5f8334dbbb79bec9a7db3706358003e58

**Comment by JulianLai** [comment]
@felixonmars 0.2.4.20171017-1 已修復
