### ISSUE TITLE
Use of DFSG incompatible static library in deepin-terminal

### ISSUE THREAD

**Issue by openarun** [linuxdeepin/developer-center#3797]
### SUMMARY | 问题概要

Use of DFSG incompatible static library file (compiled) in deepin-terminal.
https://github.com/linuxdeepin/deepin-terminal/blob/master/FuzzyTest/thirdlib/libFuzzer.a

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Distribution: Debian
Package: deepin-terminal

### STEPS TO REPRODUCE | 复现步骤

DFSG incompatibility

### EXPECTED RESULT | 期望的结果

Use of source code instead of static precompiled static library.

**Comment by ArchieMeng** [comment]
Thank you for your feedback. However, there is another way to solve this issue, which is using the existing ibfuzzer-1?-dev packages as dependency to build deepin-terminal. Anyway, we can discuss about any better solutions.

**Comment by ArchieMeng** [comment]
We just found that FuzzTest was not used at all. It might be removed from deepin-terminal in the future.

**Comment by BLumia** [comment]
> It might be removed from deepin-terminal in the future.

IMHO we can drop it right now if it's not being used at all :)
