### ISSUE TITLE
archlinux 最近更新后很多系统图标不见了，更改theme也没用

### ISSUE THREAD

**Issue by hmilyjeny** [linuxdeepin/developer-center#380]
![deepinscreenshot_select-area_20171023145452](https://user-images.githubusercontent.com/1636657/31875858-91bcccaa-b802-11e7-9356-5d1e9e3a436f.png)
![deepinscreenshot_select-area_20171023145523](https://user-images.githubusercontent.com/1636657/31875869-95e99ff6-b802-11e7-8591-8aed528e6698.png)
![deepinscreenshot_select-area_20171023145720](https://user-images.githubusercontent.com/1636657/31875873-981c28ca-b802-11e7-8832-57ce0f5ad031.png)
谢谢，谁能帮忙解决一下

**Comment by jingle0927** [comment]
https://github.com/linuxdeepin/developer-center/issues/379#issuecomment-338493687

**Comment by hmilyjeny** [comment]
deepin-qt5integration-0.2.4-1

**Comment by jingle0927** [comment]
@felixonmars 回复了的 https://github.com/linuxdeepin/developer-center/issues/379#issuecomment-338493687 0.2.3 上面就修复了

**Comment by victos** [comment]
今天刚更新，这个问题又回来了

**Comment by felixonmars** [comment]
大概找到原因了，请尝试 deepin-qt5integration 0.2.4.20171017-1

**Comment by hmilyjeny** [comment]
已经解决，谢谢！
