### ISSUE TITLE
【玲珑应用】【第三方应用】【火狐浏览器】无法通过驻留在任务栏的图标打开火狐浏览器国际版

### ISSUE THREAD

**Issue by tsic404** [linuxdeepin/developer-center#3802]
### SUMMARY | 问题概要

无法通过任务栏的图标打开火狐浏览器国际版

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin_V23

### STEPS TO REPRODUCE | 复现步骤

1.  浏览器打开  [https://store.linglong.dev ](https://store.linglong.dev) 安装火狐浏览器国际版（firefox nal)
2. 将火狐浏览器驻留在任务栏
3.点击任务栏的图标打开应用

### OBSERVED RESULT | 观察到的结果

无法通过任务栏的图标打开火狐浏览器国际版
![file-read-473621](https://user-images.githubusercontent.com/48748112/220559243-92ada2de-61cf-40d7-a414-0d40ae5b72da.gif)

### EXPECTED RESULT | 期望的结果

火狐浏览器窗口可以正常打开

**Comment by black-desk** [comment]
窗口匹配功能失效 驻留以后desktop文件识别不对

**Comment by tsic404** [comment]
> 窗口匹配功能失效 驻留以后desktop文件识别不对

这个和那个无法点击打开但是命令行却可以打开的是不是有相同的原因？

**Comment by black-desk** [comment]
> > 窗口匹配功能失效 驻留以后desktop文件识别不对
> 
> 这个和那个无法点击打开但是命令行却可以打开的是不是有相同的原因？

完全不是一回事

**Comment by black-desk** [comment]
这个目前有明确的修复方案, 但是不是很好修. 我整理一下稍后评论上来. 和am有关, 需要am使用x在16年左右的一个协议拓展插件来获取正确的窗口pid.

**Comment by black-desk** [comment]
这个问题实际上是好几个问题合起来导致的:

主要有以下两个问题:

1. 运行容器中应用的窗口和pid对应关系识别失败.
2. 以上对应关系识别失败导致desktop文件无法匹配.

这导致了将快捷方式固定在任务栏/发送到桌面之类的功能全部都失效, am出错.

以上两个问题需要一个一个处理:

## 问题1

我们目前am中识别pid依靠x的_NET_WM_PID属性, 但是这个属性是由客户端上报的自己的pid, 跑在容器中的应用因为pid_ns隔离的原因, 无法拿到自己在容器外的真实pid,以玲珑为例,应用会觉得自己的pid是2.

这是x协议设计上的问题, 玲珑无力也不应该尝试解决这个问题.

需要寻找上游的解决方案:

https://gitlab.freedesktop.org/xorg/xserver/-/issues/1022#:~:text=But%20that%20plugin%20you%27re%20working%20on%20could%20instead%20use%20the%20XRes%20extension%20to%20get%20the%20appropriate%20PID%20like%20xrestop%20does%20(and%20compositor%20such%20as%20mutter%20as%20well)%2C%20no%3F

在xorg的issue里面有个x的维护者说可以通过XRes的一个拓展提供的新接口来准确地获得窗口的pid

以下是上述链接中提到的 XResQueryClientIds 这个接口的文档: 
https://www.x.org/releases/X11R7.7/doc/resourceproto/resproto.txt 

然后这里看起来有个使用该接口的例子 https://gitlab.gnome.org/GNOME/metacity/-/merge_requests/13/diffs

v23上该库的版本是足够高的 含有这个拓展.

所以需要修改am的代码, 以获得准确的pid和窗口的对应关系.

目前看起来wayland上并没有这个问题, 估计是因为wayland中这个对应关系本来就是对的.

## 问题2

am需要提供一种机制, 使得开发者可以方便地获取一个应用程序对应的desktop文件的位置.

常见的手段有: 启动应用的时候像gnome-shell一样设置一个指向desktop文件的环境变量等.

这里我建议am提供一个dbus接口. 可以查询cgroup和desktop文件的对应关系.

**Comment by black-desk** [comment]
@zccrs

**Comment by hudeng-go** [comment]
和dbus-proxy没啥关系，我看这感觉和这个有点关系，好像那个dock栏的菜单消息是通过freedesktop的dbus协议传过去的，可能是没正确传递？

**Comment by zccrs** [comment]
> @zccrs

XResQueryClientIds 这个你不是改了吗，能解决问题问题吗

**Comment by black-desk** [comment]
pid拿到了以后窗口识别的逻辑还是有问题.

我在想怎么修, 感觉可能还是得特判一些东西, 不然这个窗口的匹配逻辑很难做.

**Comment by zccrs** [comment]
先用特判的方式临时处理，记得加TODO

**Comment by SuperEffie** [comment]
【验证环境】
【镜像地址】： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230419/deepin-23-beige-amd64-20230419-132858.iso 
【相关集成】：[[Deepin Integration]~[V23-Beta] Integrated for 23 V23-Bata#4097](https://github.com/linuxdeepin/developer-center/issues/4097)
【验证结论】：未完全修复
![显示两个图标](https://user-images.githubusercontent.com/58986464/233035061-78e4a7d6-bd12-49f8-bd19-06f9e07c75a5.gif)
