### ISSUE TITLE
Put the names of the Launcher in Spanish

### ISSUE THREAD

**Issue by Xeers** [linuxdeepin/developer-center#381]
I use Arch-Deepin. In Launcher the following names appear in English: Internet, Music, Video, Graphics, Office, Development, System, Others. I have the operative system in Spanish and from Control Center> Language and Keyboard> System Language> Spanish, but the names of the Launcher are still in English.

**Comment by hualet** [comment]
@sbwtw

**Comment by hualet** [comment]
Please try the latest version 4.2.5, it should've been fixed.

**Comment by Xeers** [comment]
Thanks very much
