### ISSUE TITLE
【社区版】【deepin_V23_beta】【集成测试】【一般】【有空】【DDE】【任务栏】libreoffice，企业微信，dde cooperation无应用图标，打开应用后全部汇合到一个花型图标上

### ISSUE THREAD

**Issue by tsic404** [linuxdeepin/developer-center#3811]
### SUMMARY | 问题概要
相关pms链接：https://pms.uniontech.com/bug-view-183631.html
_No response_

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

dde-dock:6.0.6

### STEPS TO REPRODUCE | 复现步骤

1、启动器打开libreoffice,企业微信，dde cooperation

### OBSERVED RESULT | 观察到的结果

1、三个应用打开后都汇合一个花型图标上
![file-read-587919](https://user-images.githubusercontent.com/48748112/220813126-59ecbe85-263d-48a3-9d9e-8d6fbdac65dc.png)

**Comment by SuperEffie** [comment]
Edge浏览器版本：111.0.1661.24-1打开后，出现相同的情况（在任务栏中的图标呈现锯齿状）
截图如下：
![1](https://user-images.githubusercontent.com/58986464/223031707-79c75f1f-573d-465d-9f2c-f8f74e401b4c.png)

**Comment by dengbo11** [comment]
该问题已修复,请添加这次集成[dde-application-manager](https://github.com/linuxdeepin/developer-center/issues/4097)的仓库进行回归测试.

**Comment by babyfengfjx** [comment]
@SuperEffie  请在最新版本回归验证。

**Comment by SuperEffie** [comment]
【验证环境】
【镜像地址】：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230425/deepin-23-beige-amd64-20230425-103152.iso
【版本信息】：dde-dock：6.0.13
【验证结论】：验证通过。dde-cooperation应用在v23 beta版本中屏蔽，libreoffice、企业微信在任务栏中图标显示正常
【截图信息】：
![任务栏图标1](https://user-images.githubusercontent.com/58986464/236407100-96288bb0-c44a-47fc-b411-b3ba04233229.jpg)
