### ISSUE TITLE
【DDE】【任务栏】任务栏上的声音图标为静音，拖动面板中的音量条无声音输出

### ISSUE THREAD

**Issue by tsic404** [linuxdeepin/developer-center#3812]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

控制中心 6.0.6.3
桌面 dde-session-ui 6.0.5
dde-session-shell 6.0.5.2 

### STEPS TO REPRODUCE | 复现步骤

查看任务栏上声音图标显示，将音量设置为静音
点击声音图标  -  在面板中拖动音量条
![file-read-591481](https://user-images.githubusercontent.com/48748112/220814042-531ae21a-074b-422f-a020-327e376bb23e.gif)

### OBSERVED RESULT | 观察到的结果

任务栏上的声音图标为静音，拖动面板中的音量条无声音输出

### EXPECTED RESULT | 期望的结果

声音图标跟随音量变化，拖动面板中的音量条有声音输出

**Comment by SuperEffie** [comment]
【关联提交信息】：https://github.com/linuxdeepin/dde-dock/pull/787 
【验证结论】：验证通过
【录屏信息】：
![Image](https://user-images.githubusercontent.com/58986464/223327306-da5063a1-4a91-4721-8af7-93a27943c506.gif)

**Comment by luodeepin** [comment]
【验证环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Alpha2/deepin-desktop-community-23-Alpha2-amd64.iso

仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
     deb https://community-packages.deepin.com/beige/ beige main commercial community
包版本：dde-dock       6.0.12  
       dde-control-center 6.0.11-1
内核：Linux v23-PC 6.1.11-amd64-desktop-hwe #23.01.00.01 SMP PREEMPT_DYNAMIC Mon Feb 27 17:25:36 CST 2023 x86_64 GNU/Linux
【验证步骤】：问题单中描述的步骤

【验证结果】：通过
![录屏_dde-desktop_20230418160636](https://user-images.githubusercontent.com/96416089/232716541-d008d43f-7e0c-40ba-8322-66899a0aff14.gif)
