### ISSUE TITLE
[V23 Beta] [Deepin系统升级工具]  软件评估结果页面，快速拖动滚动条，页面展示错位

### ISSUE THREAD

**Issue by l631197874** [linuxdeepin/developer-center#3820]
### SUMMARY | 问题概要

软件评估结果页面，快速拖动滚动条，页面展示错位

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

[环境]

镜像：
[https://cdimage.uniontech.com/community/releases/20.8/](https://cdimage.uniontech.com/community/releases/20.7/)
版本：
deepin-system-upgrade:6.0.2.1

### PRE-REQUIREMENT | 预置条件

已获取镜像，且镜像通过校验

### STEPS TO REPRODUCE | 复现步骤

1.启动升级工具进入软件评估结果页面
2.快速页面右侧拖动滚动条
3.查看页面展示

### OBSERVED RESULT | 观察到的结果

页面展示错位
![file-read-579941](https://user-images.githubusercontent.com/58616982/221132508-a532bcdf-8394-4cce-8247-15a76545e2ad.png)

### EXPECTED RESULT | 期望的结果

页面展示正常；

**Comment by kegechen** [comment]
已经提供修改建议，滚动变化时更新 viewport , 同时提交一个 QFrame 绘制圆角边框的方式 https://github.com/linuxdeepin/qt5integration/pull/144

**Comment by SuperEffie** [comment]
【验证环境】
【镜像地址】： https://packagesupdate.uniontech.com/repo/desktop-apricot/iso-apricot/20.9/20230417/deepin-20.9-apricot-20230417-1754-amd64.iso
【相关集成链接】：https://github.com/linuxdeepin/developer-center/issues/4054
【集成仓库】：deb [trusted=yes] https://aptly.uniontech.com/pkg/apricot/release-candidate/RGVlcGlu5Y2H57qn5bel5YW3MjAyMy0wNC0xMiAxMDo0NToyNg/ unstable main
版本信息: deepin-system-upgrade：6.0.2.5-1
【操作步骤】：
下载“原子更新”：sudo apt install deepin-upgrade-manager
下载“升级工具”：sudo apt install deepin-system-upgrade
修改配置文件：/etc/deepin-system-upgrade/config.yaml 后升级
【验证结论】：测试通过
【截图信息】：

https://user-images.githubusercontent.com/58986464/233552619-0767f35d-c370-4950-b83a-34e2b9774437.mp4

**Comment by SuperEffie** [comment]
状态更新~
