### ISSUE TITLE
[V23 Beta] [Deepin系统升级工具]  系统语言为英正繁体时，升级中Plymouth主题页面未翻译；

### ISSUE THREAD

**Issue by l631197874** [linuxdeepin/developer-center#3821]
### SUMMARY | 问题概要

升级前将系统语言为英、正、繁体时，升级过程中Plymouth主题页面未翻译

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

[环境]

镜像：
https://cdimage.uniontech.com/community/releases/20.7/
版本：
deepin-system-upgrade:6.0.1.4

### PRE-REQUIREMENT | 预置条件

系统语言为英、正、繁体

### STEPS TO REPRODUCE | 复现步骤

1.打开Deepin系统升级工具
2.等待系统重启进入升级中界面
3.查看页面显示

### OBSERVED RESULT | 观察到的结果

![file-read-561719](https://user-images.githubusercontent.com/58616982/221133101-cf2b7246-6cd9-49e4-b871-393015f0faca.png)

### EXPECTED RESULT | 期望的结果

Deepin系统升级工具语言与系统语言同步；

**Comment by zccrs** [comment]
这是程序打开之前？还是程序打开后才修改的语言呀？

**Comment by hudeng-go** [comment]
需要产品设计具体确定，plymouth是单纯的开机动画，没有打通系统当中语言配置，看是否在开机动画中进行多语言的显示，或者打通系统的语言配置关联。

**Comment by zccrs** [comment]
这个界面都是提前准备好的图片，做不到那么语言显示的同步。我建议是改成在这个节目同时显示中英文双语内容，不再管升级前环境里设置的语言。 @meiyixiang

**Comment by meiyixiang** [comment]
和林欣沟通了，在准备一张英文图片，重启时记录系统语言，英文显示英文图片，中文还是显示中文图片。桌面环境是启动应用已经是支持中英文显示的。

**Comment by meiyixiang** [comment]
加中英文双语显示。
