### ISSUE TITLE
[V23 Beta] [Deepin系统升级工具]  【UI】【镜像获取】删除按钮hover样式问题

### ISSUE THREAD

**Issue by l631197874** [linuxdeepin/developer-center#3823]
### SUMMARY | 问题概要

hover按钮下出现了黑框

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

[环境]

V20.7社区版镜像: https://cdimage.uniontech.com/community/releases/20.7/
deb包地址：http://10.20.42.95/Upgrade/pool/

### PRE-REQUIREMENT | 预置条件

进入升级工具镜像导入界面

### STEPS TO REPRODUCE | 复现步骤

升级-检测-检测通过-选择镜像-拖入镜像-hover右上角删除icon

### OBSERVED RESULT | 观察到的结果

1、hover删除按钮后按钮下方出现了黑色底，很僵硬

2、文案和上方图标之间的间距小了

### EXPECTED RESULT | 期望的结果

1、删除icon交互样式按照控件的样式来

2、本地文件图标和下方文案之间间距拉大，参照设计图

**Comment by dengbo11** [comment]
帮忙看下最新版本是否还有此问题, 上传一下问题截图

**Comment by xuqi27837288** [comment]
【验证环境】v20.9
【验证步骤】按照提单步骤
【验证结果】回归测试通过


![截图_选择区域_20240523084750](https://github.com/linuxdeepin/developer-center/assets/62528742/c6edaf1c-2584-44e3-9f5a-1a5267aa85e7)
