### ISSUE TITLE
[V23 Beta] [Deepin系统升级工具] 系统备份后会自动重启，建议给用户一个提示，系统即将重启的消息

### ISSUE THREAD

**Issue by l631197874** [linuxdeepin/developer-center#3827]
### SUMMARY | 问题概要

系统备份后会自动重启，建议给用户一个提示，系统即将重启的消息

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

[环境]

镜像：
https://cdimage.uniontech.com/community/releases/20.7/
版本：
deepin-boot-kit:1.0.11
deepin-upgrade-manager:1.0.11
deepin-system-upgrade:1.0.1

### PRE-REQUIREMENT | 预置条件

用户升级系统进入到系统自动重启阶段

### STEPS TO REPRODUCE | 复现步骤

1.进入系统备份界面
2.检查系统升级

### OBSERVED RESULT | 观察到的结果

1.系统备份过程中系统自动重启，未给出提示消息

### EXPECTED RESULT | 期望的结果

1.建议给用户一个提示，系统即将重启的消息

**Comment by meiyixiang** [comment]
ok，好的这个提示性问题优化会在正式发版时处理。

**Comment by l631197874** [comment]
已转化成需求： https://github.com/linuxdeepin/developer-center/issues/3968
