### ISSUE TITLE
[V23 Beta] [Deepin系统升级工具] 升级检查-检查未通过-重复点击重新检查按钮页面闪烁出现百分比进度图片

### ISSUE THREAD

**Issue by l631197874** [linuxdeepin/developer-center#3828]
### SUMMARY | 问题概要

升级检查-检查未通过-重复点击重新检查按钮页面闪烁出现百分比进度图片

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

[环境]

镜像：[deepin-desktop-community-20.7-amd64.iso](https://cdimage.uniontech.com/community/releases/20.7/deepin-desktop-community-20.7-amd64.iso)

系统版本：deepin-20.7-20220831105644-1_x86_64

内核：Linux deepin-PC 5.15.45-amd64-desktop #1 SMP Tue Jun 7 21:44:04 CST 2022 x86_64 GNU/Linux

应用版本：deepin-system-upgrade:1.0.1

设备:                  IPASON  Desktop Computer 
操作系统:                Deepin 20 Community Linux version 5.15.45-amd64-desktop (deepin@wh-k8snode-70) (gcc (Uos 8.3.0.6-1+dde) 8.3.0, GNU ld (GNU Binutils for Uos) 2.31.1) #1 SMP Tue Jun 7 21:44:04 CST 2022
处理器:                 Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz (四核 / 四逻辑处理器)
主板:                  H310MHP
内存:                  8GB(CT8G4DFS8266.M8FE DDR4 2667MHz (0.4ns))
显示适配器:               Oland [Radeon HD 8570 / R7 240/340 OEM]
音频适配器:               200 Series PCH HD Audio/Oland/Hainan/Cape Verde/Pitcairn HDMI Audio [Radeon HD 7000 Series]
存储设备:                WDC WDS240G2G0A-00JH30 (240 GB)
网络适配器:               RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
鼠标:                  M105 Optical Mouse (Logitech M105 Optical Mouse)
键盘:                  Keyboard K120 (Logitech Keyboard K120)
显示设备:                VIEWSONIC VA2431-H-2(23.8 英寸 (527x296 mm))

### PRE-REQUIREMENT | 预置条件

安装社区版20.7的系统

### STEPS TO REPRODUCE | 复现步骤

条件检查页面重复快速点击“重新检查”按钮；

### OBSERVED RESULT | 观察到的结果

条件检查页面闪烁出现百分比进度图片，见附件;

### EXPECTED RESULT | 期望的结果

点击重新检查按钮，页面刷新显示正常；

**Comment by zsien** [comment]
未复现

**Comment by l631197874** [comment]
新版本已解决

**Comment by SuperEffie** [comment]
【验证环境】
【镜像地址】： https://packagesupdate.uniontech.com/repo/desktop-apricot/iso-apricot/20.9/20230417/deepin-20.9-apricot-20230417-1754-amd64.iso
【相关集成链接】：https://github.com/linuxdeepin/developer-center/issues/4054
【集成仓库】：deb [trusted=yes] https://aptly.uniontech.com/pkg/apricot/release-candidate/RGVlcGlu5Y2H57qn5bel5YW3MjAyMy0wNC0xMiAxMDo0NToyNg/ unstable main
版本信息: deepin-system-upgrade：6.0.2.5-1
【操作步骤】：
下载“原子更新”：sudo apt install deepin-upgrade-manager
下载“升级工具”：sudo apt install deepin-system-upgrade
修改配置文件：/etc/deepin-system-upgrade/config.yaml 后升级
【验证结论】：测试通过
