### ISSUE TITLE
switches in control-center not functional

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/developer-center#383]
In the control-center non of the switches, like 'Enable window effects', 'Wired Network Card' can be moved from their current setting.

dde-control-center v4.2.5.11 on Manjarolinux

**Comment by oberon2007** [comment]
I broken package seems to be **deepin-qt5integration**.
Downgrading to  **0.2.4.20171017** brings functioinality of the switches back!

**Comment by oberon2007** [comment]
The commit that broke it is this one:
https://github.com/linuxdeepin/qt5integration/commit/fa922478741bebb858d2a90f96620862813de46f

**Comment by felixonmars** [comment]
Double-click seems to work here.

@zccrs Any thoughts?

**Comment by oberon2007** [comment]
Fixed with **0.2.6.1**. Thank you.
