### ISSUE TITLE
deepin-system-upgrade-升级工具集成

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#3840]

**Comment by Zeno-sole** [comment]
包名 | 版本
-- | --
deepin-system-upgrade | 6.0.1.6

**Comment by Zeno-sole** [comment]
@l631197874  请备注更新内容、测试范围等

**Comment by l631197874** [comment]
更新说明: 由于升级工具没有集成到V23主仓库，因此上次集成测试需要采用定制镜像的方式，去配合完成在V23上的应用功能。
此次更新将采用从仓库装包的方式，用户可以使用在线下载和本地导入的方式进行升级，升级完成后，需要手动在V23上安装V23子仓库中的升级工具，安装完成后，重启系统，即可自动开始应用迁移。

测试范围：升级到V23之后的应用迁移流程

**Comment by Zeno-sole** [comment]
仓库地址： deb  [trusted=yes] https://aptly.uniontech.com/pkg/beige-v2/release-candidate/RGVlcGlu57O757uf5Y2H57qn5bel5YW3MjAyMy0wMi0yNCAxNzoyMDoyNA/  unstable main      @SuperEffie

**Comment by Zeno-sole** [comment]
已更新 仓库地址： deb https://community-packages.deepin.com/beige/ beige main community commercial
