### ISSUE TITLE
双屏模式开启“窗口移动时启用特效”选项时的显示错误

### ISSUE THREAD

**Issue by vmomenv** [linuxdeepin/developer-center#3845]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Deepin 20.8
[日志文件](https://wwkv.lanzoue.com/irjoO0oz6g2j)

### STEPS TO REPRODUCE | 复现步骤

1.开启“窗口移动式启用透明特效”
2.电脑关机并连接显示器（开机状态下连接不会触发）
3.开机后随意开启一个应用并全屏
[5.触发窗口一直透明的bug,并且关闭窗口后，依然显示画面

### OBSERVED RESULT | 观察到的结果
![image](https://user-images.githubusercontent.com/51269338/222156998-abe44521-f19e-45bc-b0f1-8bd81aa780a3.png)

[复现视频](https://wwkv.lanzoue.com/irjoO0oz6g2j)

**Comment by luodeepin** [comment]
[双屏扩展模式下，开启 窗口移动时启用透明特效，移动全屏窗口时透明特效不消失 的问题](https://pms.uniontech.com/bug-view-191065.html)，我们已经反馈给开发进行修复

**Comment by luodeepin** [comment]
转pms跟踪https://pms.uniontech.com/bug-view-191065.html，
