### ISSUE TITLE
【deepin_V23_beta】【一般】【立即】【子项目集成测试】【终端】在简体中文环境下，设置中的 Ctrl + 鼠标滚轮描述显示为英文

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#3848]
### SUMMARY | 问题概要

本问题对应集成编号为 deepin-terminal-6.0.4集成 # 3838
#3838 

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

镜像：https://cdimage.uniontech.com/community/releases/23-Alpha2/deepin-desktop-community-23-Alpha2-amd64.iso
仓库：deb [trusted=yes] https://aptly.uniontech.com/pkg/beige-v2/release-candidate/ZGVlcGluLXRlcm1pbmFsMjAyMy0wMy0wMSAxMTozMTozNQ/ unstable main
deb https://community-packages.deepin.com/beige/ beige main commercial community
终端  6.0.4

### PRE-REQUIREMENT | 预置条件

1. 系统语言为简体中文

### STEPS TO REPRODUCE | 复现步骤

1. 打开终端 - 设置 - 检查语言显示

### OBSERVED RESULT | 观察到的结果

1. 滚动项下的描述存在英文
![截图_选择区域_20230302111134](https://user-images.githubusercontent.com/96416089/222323221-a013c764-9936-447c-8df4-7cf928b337fc.png)

### EXPECTED RESULT | 期望的结果

1. 在简体中文下，语言显示为简体中文

**Comment by ArchieMeng** [comment]
这个确实没有添加翻译．

**Comment by babyfengfjx** [comment]
请帮忙优化~

**Comment by vivianxf** [comment]
验证镜像：https://cdimage.uniontech.com/community/releases/23-Alpha2/deepin-desktop-community-23-Alpha2-amd64.iso
验证版本：dde-dock：6.0.9.2
验证步骤：提单的步骤
验证现象：符合预期
验证结果：通过

**Comment by xuqi27837288** [comment]
已修复 by 进击的小浣熊~测试通过

**Comment by SuperEffie** [comment]
【验证环境】
【镜像地址】： https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230309/
【集成链接】：https://github.com/orgs/linuxdeepin/projects/21?pane=issue&itemId=23346985
【版本信息】：6.0.5+rb1
【验证结论】：验证通过
【截图信息】：
![截图_deepin-terminal_20230321111450](https://user-images.githubusercontent.com/58986464/226509931-843803df-0187-4f69-93e5-a31b7b39a2f3.jpg)

**Comment by luodeepin** [comment]
终端 6.0.6 中再次复现

![Uploading 截图_选择区域_20230804143805.png…]()

**Comment by ArchieMeng** [comment]
修复PR已经合入，版本6.0.6开始包含。@babyfengfjx看看怎么安排下测试？ https://github.com/linuxdeepin/deepin-terminal/pull/290

**Comment by babyfengfjx** [comment]
@kobe337   请在最新版本回归验证。

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-380/testing/ ./
内核：Linux test-PC 6.1.32-amd64-desktop-hwe #23.01.00.19 SMP PREEMPT_DYNAMIC Wed Aug  2 17:06:10 CST 2023 x86_64 GNU/Linux
验证版本：deepin-terminal:6.0.7
【结论】：
回归测试通过

![zd](https://github.com/linuxdeepin/developer-center/assets/17869922/97bfcdf1-58af-462f-ac4d-fc1a5d2fcb98)

**Comment by babyfengfjx** [comment]
@kobe337   如确认最新版本回归通过，请打上回归通过标签。
