### ISSUE TITLE
desktop icon problem with dde-file-manager 4.3.5

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/developer-center#385]
With latest update the bahaviour of desktop icons has become strange.
There is a spot that cannot be used on the desktop. When trying to move an icon there is either disappears or jumps to the bottom right corner of the screen.
Downgrading dde-file-manager makes the issue go away.
Rebuilding against dtkwidget 2.0.4.2 didn't help.

![deepinscreenshot_select-area_20171031155141](https://user-images.githubusercontent.com/11800714/32234347-7072a080-be54-11e7-8a78-ca60763f0e15.png)

**Comment by hualet** [comment]
@felixonmars  can you reproduce this one ?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
