### ISSUE TITLE
【deepin_V23_beta】【一般】【立即】【子项目集成测试】【终端】雷神窗口动画速度保持默认为慢时，与手动设置为慢时的 速度不一致 

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#3850]
### SUMMARY | 问题概要
https://github.com/linuxdeepin/developer-center/issues/3838 相关 issues
#3838 

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

镜像：https://cdimage.uniontech.com/community/releases/23-Alpha2/deepin-desktop-community-23-Alpha2-amd64.iso
仓库：deb [trusted=yes] https://aptly.uniontech.com/pkg/beige-v2/release-candidate/ZGVlcGluLXRlcm1pbmFsMjAyMy0wMy0wMSAxMTozMTozNQ/ unstable main
deb https://community-packages.deepin.com/beige/ beige main commercial community
终端 6.0.4

### PRE-REQUIREMENT | 预置条件

1. 终端设置中的 雷神窗口动画速度 保持为默认 慢

### STEPS TO REPRODUCE | 复现步骤

1.  按 alt F2键 打开雷神终端
2.  将 雷神窗口动画速度设置为 快 - 再将 雷神窗口动画速度设置为 慢
3.  按 alt F2键 打开雷神终端

### OBSERVED RESULT | 观察到的结果

1. 雷神终端速度缓慢打开
2. 雷神窗口动画速度 设置显示为慢
3. 雷神终端打开速度 与 默认为慢时 不一致
![Uploading Record_select-area_20230302134051.gif…]()

### EXPECTED RESULT | 期望的结果

1. 雷神终端速度缓慢打开
2. 雷神窗口动画速度 设置显示为慢
3. 雷神终端打开速度 与 默认为慢时 一致

**Comment by babyfengfjx** [comment]
请帮忙优化~

**Comment by ArchieMeng** [comment]
@luodeepin 录屏能重新传一下吗？好像没传成功，看不到．

**Comment by xuqi27837288** [comment]
测试通过

**Comment by SuperEffie** [comment]
【验证环境】
【镜像地址】： https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230309/
【集成链接】：https://github.com/orgs/linuxdeepin/projects/21?pane=issue&itemId=23346985
【版本信息】：6.0.5+rb1
【验证结论】：验证通过，默认设置为“慢”与手动设置为“慢”，动效均显示正常
【录屏信息】：
![录屏_dde-desktop_20230321110405](https://user-images.githubusercontent.com/58986464/226509064-3cb2232b-b251-4252-a35b-780306e06dd9.gif)

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0424镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230424
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
