### ISSUE TITLE
[ubuntu22.10] [DTK] 在X11环境下，星火商店的所有窗口只能打开一次，第二次打开就只显示窗口阴影

### ISSUE THREAD

**Issue by uniartisan** [linuxdeepin/developer-center#3859]
### SUMMARY | 问题概要

https://gitee.com/deepin-community-store/spark-store

[ubuntu22.10] [DTK] 在X11环境下，星火商店的所有窗口只能打开一次，第二次打开就只显示窗口阴影
目前在ub22.10的x11下稳定触发，22.04/deepin/uos等os没有此问题。把ub22.10切换到wayland也可以规避这个问题。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

系统 Ubuntu22.10

```
libdtkcommon/kinetic,now 5.5.23-1 amd64 [已安装，自动]
libdtkcommon-dev/kinetic,now 5.5.23-1 amd64 [已安装，自动]
libdtkcore-dev/kinetic,now 5.5.33-1ubuntu2 amd64 [已安装]
libdtkcore5/kinetic,now 5.5.33-1ubuntu2 amd64 [已安装，自动]
libdtkgui-dev/kinetic,now 5.5.25-1build1 amd64 [已安装]
libdtkgui5/kinetic,now 5.5.25-1build1 amd64 [已安装，自动]
libdtkwidget-dev/kinetic,now 5.5.48-1build1 amd64 [已安装]
libdtkwidget5/kinetic,now 5.5.48-1build1 amd64 [已安装，自动]
spark-store/now 4.2.3~test5 amd64 [已安装，本地]

```

### PRE-REQUIREMENT | 预置条件

星火商店所有的窗口第一次打开都没有问题，第二次打开便只有窗口阴影。
由于在其他平台没有出现此问题，故怀疑是dtk在特定平台出现了故障。

### STEPS TO REPRODUCE | 复现步骤

1.打开界面
2.关闭界面
3.重新打开界面

### OBSERVED RESULT | 观察到的结果

![image](https://user-images.githubusercontent.com/31544054/222875436-16f40520-85ec-4925-8d65-3bfdaee21d68.png)
此时仍然可以点击窗口 比如说全屏、最小化等。

### EXPECTED RESULT | 期望的结果

正常显示界面

**Comment by BLumia** [comment]
若单纯建立普通的 DTK 应用程序窗口，也会有相同的问题吗？如果是，建议提供最小可复现示例。如果不是，建议反馈到星火商店进行故障排查。

另，你所提供的 dtk 版本已落后已发布版本很多，所以同时建议考虑更新 dtk。

**Comment by shenmo7192** [comment]
> 若单纯建立普通的 DTK 应用程序窗口，也会有相同的问题吗？如果是，建议提供最小可复现示例。如果不是，建议反馈到星火商店进行故障排查。
> 
> 另，你所提供的 dtk 版本已落后已发布版本很多，所以同时建议考虑更新 dtk。

此版本是Ubuntu 2210提供的版本

内部已确认此问题不是星火商店问题

**Comment by BLumia** [comment]
> 内部已确认此问题不是星火商店问题

> 如果是，建议提供最小可复现示例。

**Comment by uniartisan** [comment]
[DBlurEffectWidgetDemo.zip](https://github.com/linuxdeepin/developer-center/files/10888102/DBlurEffectWidgetDemo.zip)

这个是最小复现单例，在托盘show以后会出现此问题。即：同一窗口第二次打开会出现问题。

**Comment by BLumia** [comment]
在 Archlinux `dtkwidget 5.6.5-1` `dtkgui 1:5.6.5-1` `dtkcore 1:5.6.5-1` `deepin-qt5integration 5.6.5-1` `deepin-qt5platform-plugins 5.6.4-1` 环境下未能复现。

建议尝试在 Ubuntu 中构建并使用更新版本的 DTK 并重新尝试是否仍然存在问题。

**Comment by shenmo7192** [comment]
> 在 Archlinux `dtkwidget 5.6.5-1` `dtkgui 1:5.6.5-1` `dtkcore 1:5.6.5-1` `deepin-qt5integration 5.6.5-1` `deepin-qt5platform-plugins 5.6.4-1` x11 环境下，使用上述最小示例未能复现所述问题。
> 
> 建议尝试在 Ubuntu 中构建并使用更新版本的 DTK 并重新尝试是否仍然存在问题。

个人不准备对此提供修复，下一个Ubuntu LTS应该会有更高版本的DTK，也就修复了这个问题

@uniartisan 怎么看

**Comment by uniartisan** [comment]
> > 在 Archlinux `dtkwidget 5.6.5-1` `dtkgui 1:5.6.5-1` `dtkcore 1:5.6.5-1` `deepin-qt5integration 5.6.5-1` `deepin-qt5platform-plugins 5.6.4-1` x11 环境下，使用上述最小示例未能复现所述问题。
> > 建议尝试在 Ubuntu 中构建并使用更新版本的 DTK 并重新尝试是否仍然存在问题。
> 
> 个人不准备对此提供修复，下一个Ubuntu LTS应该会有更高版本的DTK，也就修复了这个问题
> 
> @uniartisan 怎么看

我先尝试构建更新的dtk看看，因为ubuntu的非lts版本就是给开发者缓冲的时间，有可能是上游对x11相关的代码或者窗管进行了代码维护，引入了新的问题.

>要么这是ubuntu的bug需要fix,要么是dtk出现了兼容问题。

我们需要在lts版本之前提前确定这些问题的原因，当然这个和我个人在使用ubuntu22.10也有一定关系:)

**Comment by uniartisan** [comment]
[录屏 2023-03-04 21-53-54.webm](https://user-images.githubusercontent.com/31544054/222906389-b2b98bfb-a3e3-4e64-a32c-ad0fee4c2c61.webm)
```
dtkwidget-doc/now 5.6.8 amd64 [已安装，本地]
dtkwidget5-examples/now 5.6.8 amd64 [已安装，本地]
libdtkcommon/now 5.6.8 amd64 [已安装，本地]
libdtkcommon-dev/now 5.6.8 amd64 [已安装，本地]
libdtkcore-dev/now 5.6.8 amd64 [已安装，本地]
libdtkcore-doc/now 5.6.8 amd64 [已安装，本地]
libdtkcore5/now 5.6.8 amd64 [已安装，本地]
libdtkcore5-bin/now 5.6.8 amd64 [已安装，本地]
libdtkgui-dev/now 5.6.8 amd64 [已安装，本地]
libdtkgui-doc/now 5.6.8 amd64 [已安装，本地]
libdtkgui5/now 5.6.8 amd64 [已安装，本地]
libdtkgui5-bin/now 5.6.8 amd64 [已安装，本地]
libdtkwidget-dev/now 5.6.8 amd64 [已安装，本地]
libdtkwidget5/now 5.6.8 amd64 [已安装，本地]
libdtkwidget5-bin/now 5.6.8 amd64 [已安装，本地]
spark-store/now 4.2.3.1 amd64 [已安装，本地]

```
包括qt5integration 在内全部从master分支编译出最新版本并安装，样例和星火商店全部重新构建，仍然由此问题

**Comment by BLumia** [comment]
> 包括qt5integration 在内全部从master分支编译出最新版本并安装，样例和星火商店全部重新构建，仍然由此问题

[`qt5dxcb-plugin`](https://github.com/linuxdeepin/qt5platform-plugins) 也重新构建了吗？

**Comment by uniartisan** [comment]
> > 包括qt5integration 在内全部从master分支编译出最新版本并安装，样例和星火商店全部重新构建，仍然由此问题
> 
> [`qt5dxcb-plugin`](https://github.com/linuxdeepin/qt5platform-plugins) 也重新构建了吗？

dde-qt5integration 已经是最新版 (5.6.5)。
dde-qt5wayland-plugin 已经是最新版 (5.6.5)。
dde-qt5xcb-plugin 已经是最新版 (5.6.5)。
dtkwidget5-examples 已经是最新版 (5.6.8)。
dtkwidget-doc 已经是最新版 (5.6.8)。
libdtkcommon 已经是最新版 (5.6.8)。
libdtkcommon-dev 已经是最新版 (5.6.8)。
libdtkcore5 已经是最新版 (5.6.8)。
libdtkcore5-bin 已经是最新版 (5.6.8)。
libdtkcore-dev 已经是最新版 (5.6.8)。
libdtkcore-doc 已经是最新版 (5.6.8)。
libdtkgui5 已经是最新版 (5.6.8)。
libdtkgui5-bin 已经是最新版 (5.6.8)。
libdtkgui-dev 已经是最新版 (5.6.8)。
libdtkgui-doc 已经是最新版 (5.6.8)。
libdtkwidget5 已经是最新版 (5.6.8)。
libdtkwidget5-bin 已经是最新版 (5.6.8)。
libdtkwidget-dev 已经是最新版 (5.6.8)

**Comment by uniartisan** [comment]
> 确实存在这个问题。窗口隐藏再显示之后，xwininfo看状态是 Map State: IsUnmaped 即不可见状态。定位中。

我怀疑是ubuntu 22.10 自身问题，因为 23.04 该问题不再存在。
若23.04稳定版发布后该问题不存在，我认为可以关闭这个issue。 无需为短期支持版本单独修复问题。

**Comment by 18202781743** [comment]
与qt版本有关，具体跟 https://codereview.qt-project.org/c/qt/qtbase/+/235138 这个提交引起的，它加了个延迟处理的逻辑，导致dtk的dde-qt5xcb-plugin插件功能失效，
dde-qt5xcb-plugin 在enabledxcb时，做了个代理window，会将原来的窗口放到自定义的窗口中，此提交会导致处理原来的窗口调用setVisible失效

**Comment by 18202781743** [comment]
cc @zccrs

**Comment by zccrs** [comment]
> > 确实存在这个问题。窗口隐藏再显示之后，xwininfo看状态是 Map State: IsUnmaped 即不可见状态。定位中。
> 
> 我怀疑是ubuntu 22.10 自身问题，因为 23.04 该问题不再存在。 若23.04稳定版发布后该问题不存在，我认为可以关闭这个issue。 无需为短期支持版本单独修复问题。

的确是Ubuntu自身的问题，它的Qt少了 https://codereview.qt-project.org/c/qt/qtbase/+/401815 这个patch。

**Comment by zccrs** [comment]
我的建议是在Ubuntu有问题的这个版本上，加上 D_DXCB_DISABLE 的环境变量。

**Comment by BLumia** [comment]
DTK 一侧已处理完成，予以关闭。
