### ISSUE TITLE
translations not applied to launcher categories

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/developer-center#386]
The category names in the launcher remain in English regardless of language settings.

**Comment by hualet** [comment]
@oberon2007 @felixonmars please try the latest version 4.2.5

**Comment by hualet** [comment]
@oberon2007 ?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
