### ISSUE TITLE
deepin-calculator 计算器应该遵循系统语言的小数点格式

### ISSUE THREAD

**Issue by fengshuo2004** [linuxdeepin/developer-center#3860]
### SUMMARY | 问题概要

deepin-calculator 即计算器应用，应当根据操作系统的 locale 设置，决定使用**逗号为分隔符、句号为小数点**或**句号为分隔符、逗号为小数点**。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Distribution: deepin v23 alpha 2
Package: deepin-calculator

### PRE-REQUIREMENT | 预置条件

系统语言地区为葡萄牙语（巴西）

### STEPS TO REPRODUCE | 复现步骤

1. 打开计算器
2. 计算 10000 + 2000.75

### OBSERVED RESULT | 观察到的结果

`12,000.75`

### EXPECTED RESULT | 期望的结果

`12.000,75` 巴西、法国还有好多其他国家都是这样记数的。
在这些语言环境下，计算器的小数点按钮 `.` 也应该变成 `,` 逗号。

### ADDITIONAL INFORMATION | 额外补充

原帖：https://bbs.deepin.org/en/post/252643

**Comment by BLumia** [comment]
关联： https://github.com/linuxdeepin/developer-center/issues/2406

**Comment by SuperEffie** [comment]
感谢您的反馈哦～
这个问题很早之前在issue #2406[https://github.com/linuxdeepin/developer-center/issues/2406](https://github.com/linuxdeepin/developer-center/issues/2406)提出过，当时已提交研发同学，不过可能这个问题的优先级比较低。因为是重复的issue，我先将这个issue关闭，您可以在以上的issue中跟踪该问题的进展。

**Comment by BLumia** [comment]
> 那记得把国服的搞成每4位一个逗号，我们的数词是万，对应每4位数词前进一下（万，亿），国外用千的才是每3位一个逗号（thousand，million）

确实如此。计算器的行为应当遵循当前系统的 locale 所倾向的设置。作为参考，CLDR 中应当已经提供了相关的数据，其对应的 ICU 库（以及使用它的类如 Intl 模块等）均已包含了相关的支持。

**Comment by babyfengfjx** [comment]
#2406被关闭了，后续以此issue作为跟踪

**Comment by BLumia** [comment]
关联： https://github.com/linuxdeepin/developer-center/issues/3982

**Comment by SuperEffie** [comment]
感谢您的反馈，这个问题我们会在pms平台进行跟踪，但可能优先级较低，目前关于v20.9版本的issue我们将会进行关闭。若是您在使用v23beta过程中遇到问题，也欢迎向我们反馈~
