### ISSUE TITLE
文件管理器在被javafx的文件选择器调用时候会oom

### ISSUE THREAD

**Issue by Decodetalkers** [linuxdeepin/developer-center#3861]
### Discussed in https://github.com/orgs/linuxdeepin/discussions/3837

<div type='discussions-op-text'>

<sup>Originally posted by **lhDream** March  1, 2023</sup>

在V23版本打开javafx的文件选器，文件选择器界面空白，且会导致系统UI卡死，并退出到系统登录界面，再次登录会黑屏，并且无法进入
demo
```java
public void start(Stage primaryStage) throws Exception{
    Button button = new Button();
    button.setOnAction(e->{
        FileChooser fileChooser = new FileChooser();
        fileChooser.showOpenDialog(primaryStage);
    });
    primaryStage.setScene(new Scene(button));
    primaryStage.show();
}
```
![image](https://user-images.githubusercontent.com/41568266/222032983-a9a069b9-9327-45ec-905c-10e5fc6011c3.png)

https://user-images.githubusercontent.com/41568266/222076125-1413502e-c2c0-4cbe-932d-b89891a39b88.mp4

</div>

查询得到最终调用了deepin-dialog-x11后，产生了oom,需要排查如何被调起，以及调起后溢出的原因

**Comment by babyfengfjx** [comment]
@luodeepin 请教研发相关复现方法，提单给文管处理。

**Comment by xzl01** [comment]
> @luodeepin 请教研发相关复现方法，提单给文管处理。

在https://github.com/orgs/linuxdeepin/discussions/3837 提供了一个最小复现案例，可以复现此情况

**Comment by luodeepin** [comment]
该问题我们已经反馈给开发进行修复，之后有结果了，我再回复你！
感谢你的反馈！

**Comment by luodeepin** [comment]
在最新 v23 beta环境中验证通过
![截图_dde-desktop_20230506132511](https://user-images.githubusercontent.com/96416089/236601986-454dd6bb-3c82-4cb2-a8d8-bf3e4bd3a0a2.png)
