### ISSUE TITLE
【deepin_V23_beta】【一般】【有空】【发散测试】【DDE】【控制中心】当个性化主题选择hazy color时，活动用色值异常

### ISSUE THREAD

**Issue by SuperEffie** [linuxdeepin/developer-center#3866]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

1. 镜像地址：https://cdimage.uniontech.com/community/releases/23-Alpha2/deepin-desktop-community-23-Alpha2-amd64.iso
2. 内核 5.18.17-amd64-desktop-hwe
3. 版本信息：dde-control-center:6.0.9.1;dde-dock:6.0.9.2

### STEPS TO REPRODUCE | 复现步骤

打开控制中心-个性化-主题选中hazy color时，观察活动用色值

### OBSERVED RESULT | 观察到的结果

主题选中hazy color时，观察活动用色值为自定义状态
![截图_dde-control-center_20230307152734](https://user-images.githubusercontent.com/58986464/223359717-312bceef-ed5b-485b-a851-486329a8b64f.jpg)

### EXPECTED RESULT | 期望的结果

主题选中hazy color时，活动用色值应选中第一个

**Comment by vivianxf** [comment]
呆呆鹅验证
验证镜像：https://cdimage.uniontech.com/community/releases/23-Alpha2/deepin-desktop-community-23-Alpha2-amd64.iso
验证版本：dde-control-center--6.0.11
验证步骤：提单的步骤
验证现象：符合预期
验证结论：通过

**Comment by SuperEffie** [comment]
【版本信息】：dde-control-center：6.0.20
【验证结论】：问题已修复
【录屏信息】：
![个性化 - 副本](https://github.com/linuxdeepin/developer-center/assets/58986464/9accdcb5-881d-4ffb-ace8-2b5f881c2c96)
