### ISSUE TITLE
open-vm-tools 集成

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#3875]

**Comment by Zeno-sole** [comment]
包名|版本
-- | --
containerd|1.6.18~ds1-1
continuity|0.3.0-1
go-md2man-v2|2.0.2+ds1-1
golang-blackfriday|1.6.0-1
golang-blackfriday-v2|2.1.0-1
golang-ginkgo|1.16.5-3
golang-github-alexflint-go-filemutex|1.2.0-1
golang-github-appc-cni|1.1.2-1
golang-github-benbjohnson-clock|1.3.0-1
golang-github-blang-semver|4.0.0-1
golang-github-checkpoint-restore-go-criu|5.3.0-2
golang-github-chzyer-readline|1.4.39.g2972be2-3
golang-github-cilium-ebpf|0.9.1-1
golang-github-containerd-cgroups|1.0.4-1
golang-github-containerd-console|1.0.3-1
golang-github-containerd-fifo|1.0.0-3
golang-github-containerd-go-cni|1.1.7-2
golang-github-containerd-go-runc|1.0.0-1
golang-github-containerd-typeurl|1.0.2-1
golang-github-containernetworking-plugins|1.1.1+ds1-3
golang-github-containers-ocicrypt|1.0.3-1
golang-github-coreos-bbolt|1.3.6-2
golang-github-coreos-go-iptables|0.6.0-1
golang-github-cyphar-filepath-securejoin|0.2.3-1
golang-github-d2g-dhcp4|0.0~git20150413-4
golang-github-d2g-dhcp4client|1.0.0-2
golang-github-docker-go-events|0.0~git20190806.e31b211-4
golang-github-docker-go-metrics|0.0.1-2
golang-github-docker-go-units|0.4.0-4
golang-github-emicklei-go-restful|3.7.3-1
golang-github-fullsailor-pkcs7|0.0~git20210826.33d0574-2
golang-github-go-kit-log|0.2.1-1
golang-github-go-logr-logr|1.2.3-1
golang-github-gogo-googleapis|1.4.0-2
golang-github-golang-protobuf-1-3|1.3.5-4
golang-github-google-martian|3.3.2-2
golang-github-google-pprof|0.0~git20211008.947d60d-1
golang-github-google-uuid|1.3.0-1
golang-github-googleapis-gax-go|2.0.5-4
golang-github-grpc-ecosystem-go-grpc-prometheus|1.2.0+git20191002.6af20e3-3
golang-github-ianlancetaylor-demangle|0.0~git20200824.28f6c0f-2
golang-github-imdario-mergo|0.3.12-1
golang-github-intel-goresctrl|0.3.0-2
golang-github-klauspost-compress|1.15.12+ds1-3
golang-github-masterminds-semver-dev|3.2.0-1
golang-github-mattn-go-shellwords|1.0.10-2
golang-github-moby-locker|1.0.1-3
golang-github-mrunalp-fileutils|0.5.0-2
golang-github-mwitkow-go-conntrack|0.0~git20190716.2f06839-3
golang-github-networkplumbing-go-nft|0.2.0-2
golang-github-nxadm-tail|1.4.5+ds1-5
golang-github-opencontainers-go-digest|1.0.0-2
golang-github-opencontainers-image-spec|1.1.0~rc2-1
golang-github-opencontainers-selinux|1.10.0+ds1-1
golang-github-opencontainers-specs|1.0.2.118.g5cfc4c3-1
golang-github-prometheus-client-golang|1.14.0-3
golang-github-prometheus-client-model|0.3.0-3
golang-github-prometheus-common|0.39.0-2
golang-github-safchain-ethtool|0.2.0-1
golang-github-seccomp-libseccomp-golang|0.10.0-3
golang-github-urfave-cli|1.22.9-2
golang-github-vishvananda-netlink|1.1.0.125.gf243826-4
golang-go-patricia|2.3.1-1
golang-go-zfs|3.0.0-1
golang-go.opencensus|0.23.0-4
golang-gocapability-dev|0.0+git20200815.42c35b4-2
golang-gogottrpc|1.1.0-3
golang-golang-x-net|1:0.7.0+dfsg-1
golang-golang-x-oauth2|0.3.0-1
golang-golang-x-sys|0.3.0-1
golang-google-api|0.61.0-1
golang-google-cloud|0.56.0-3
golang-google-genproto|0.0~git20200413.b5235f6-3
golang-google-grpc|1.33.3-2
golang-gopkg-inf.v0|0.9.1-2
golang-gopkg-square-go-jose.v2|2.6.0-2
golang-gopkg-tomb.v1|0.0~git20141024.0.dd63297-8
golang-k8s-klog|2.80.1-2
golang-k8s-sigs-structured-merge-diff|4.1.2+ds1-2
golang-k8s-sigs-yaml|1.3.0-1
golang-opentelemetry-otel|1.1.0-2
golang-protobuf-extensions|1.0.1-3
golang-rsc-binaryregexp|0.2.0-3
gotest.tools|3.0.3-1
open-vm-tools|2:12.1.5-3
runc|1.1.4+ds1-1

**Comment by Zeno-sole** [comment]
@UTsweetyfish  请备注更新内容、 影响范围等内容

**Comment by UTsweetyfish** [comment]
## 更新内容

- containerd 及相关依赖
- runc 及相关依赖
- gotest 及相关依赖
- open-vm-tools 及相关依赖

## 构建失败列表

### `golang-google-api` (`0.61.0-1`)

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 sbuild-build-depends-main-dummy : Depends: dh-golang (>= 1.53~) but 1.51 is to be installed
E: Unable to correct problems, you have held broken packages.
```

### `golang-golang-x-net` (`0.7.0+dfsg-1`)

```
# command-line-arguments
./gen.go:361:30: binary.BigEndian.AppendUint32 undefined (type binary.bigEndian has no field or method AppendUint32)
src/golang.org/x/net/publicsuffix/list.go:5: running "go": exit status 2
```

[build.log](https://github.com/linuxdeepin/developer-center/files/10940917/golang-golang-x-net_0.7.0%2Bdfsg-1_amd64-2023-03-10T06.09.16Z.build.txt)

需要更新 golang 1.19。([ref](https://pkg.go.dev/encoding/binary#AppendByteOrder))

### `open-vm-tools` (`12.1.5-3`)

```
/usr/bin/ld: cannot find -labsl_synchronization: No such file or directory
collect2: error: ld returned 1 exit status
make[5]: *** [Makefile:648: libcontainerInfo.la] Error 1
```

缺少 `libabsl-dev` 依赖。(Upstream: https://bugs.debian.org/1032305)

[build.log](https://github.com/linuxdeepin/developer-center/files/10940986/open-vm-tools_12.1.5-3_amd64-2023-03-10T06.13.24Z.build.txt)

**Comment by Zeno-sole** [comment]
https://github.com/linuxdeepin/developer-center/issues/3619#issuecomment-1425127205  关联issues

**Comment by Zeno-sole** [comment]
@babyfengfjx    主要验证以下组件 ，确认是否在v23环境下正常使用安装，测试问题请联系 @UTsweetyfish  进行确认
containerd 及相关依赖
runc 及相关依赖
gotest 及相关依赖
open-vm-tools 及相关依赖

**Comment by xuqi27837288** [comment]
![截图_选择区域_20230314094726](https://user-images.githubusercontent.com/62528742/224882074-a78ec99a-2732-4c80-9afd-20a99e0b5fb4.png)

添加仓库后安装open-vm-tools及相关依赖正常，测试通过

**Comment by UTsweetyfish** [comment]
`libabsl-dev` 依赖的问题上游修了

https://bugs.debian.org/1032305

**Comment by UTsweetyfish** [comment]
open-vm-tools `12.1.5-3` -> `12.2.0-1`。
