### ISSUE TITLE
［终端］Shift+Tab 组合键会切换输入焦点到标题栏按钮

### ISSUE THREAD

**Issue by ArchieMeng** [linuxdeepin/developer-center#3878]
### SUMMARY | 问题概要

终端Shell有时候需要用到Shift+Tab组合键，但终端应用此时会切换焦点到标题栏按钮，影响Shell的使用．

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

- Deepin V23
- deepin-terminal 6.0.4-5-gc569f185

### PRE-REQUIREMENT | 预置条件

无

### STEPS TO REPRODUCE | 复现步骤

光标聚焦到终端Shell时，使用Shift+Tab组合键．

### OBSERVED RESULT | 观察到的结果

输入焦点聚焦到了标题栏按钮上．（最小化，最大化那里）

### EXPECTED RESULT | 期望的结果

提供选项禁用Shift+Tab聚焦到标题栏按钮．

### ADDITIONAL INFORMATION | 额外补充

无

**Comment by zhouchuanfu** [comment]
加油哇，这太影响使用了

**Comment by SuperEffie** [comment]
[集成链接]：https://github.com/linuxdeepin/developer-center/issues/5114
[版本信息]：deepin-terminal：6.0.6
[验证结论]：验证通过，shift + tab组合键切换焦点功能已屏蔽
[录屏信息]：
![聚焦](https://github.com/linuxdeepin/developer-center/assets/58986464/d43cb467-19a0-432d-b5a4-65c367e8ff29)

**Comment by SuperEffie** [comment]
见以上备注，关闭此issue
