### ISSUE TITLE
Text scaling on the fly

### ISSUE THREAD

**Issue by hxss** [linuxdeepin/developer-center#389]
HiDPI display is often installed on modern laptops.
Also today we often use external monitors for HDMI.
Therefore, it is important for us to be able to switch the text scaling on the fly.
In dconf-editor I found key /com/deepin/wrap/gnome/desktop/interface/text-scaling-factor that can change text scaling but only after relogin. Is there a way to apply scale changes on the fly like it doing cinnamon or xfce?

**Comment by jouyouyun** [comment]
If you are an archer, you can set text scale in deepin control center -> display -> display scale.
If you are a deepiner, please wait deepin 15.5.

**Comment by hualet** [comment]
DDE now applies font size settings on the fly, please wait for the release of 15.5.
