### ISSUE TITLE
DCI 图标主题部分图标缺失

### ISSUE THREAD

**Issue by kegechen** [linuxdeepin/developer-center#3891]
【社区版】【deepin_V23-alpha2】【发散测试】【文件管理器】系统主题为oranic glass时，文件管理器主目录的桌面图标没有跟随主题变化

重现步骤
【环境信息】
镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/20230202
内核 Linux v233-PC 5.18.17-amd64-desktop-hwe #23.01.00.06 SMP PREEMPT_DYNAMIC Mon Oct 31 17:25:49 CST 2022 x86_64 GNU/Linux
文件管理器 6.0.9
【前置条件】

【操作步骤】
打开控制中心-个性化-主题
更改系统主题为organic glass
打开文件管理器-主目录
观察桌面图标展示     --【预期结果】：桌面图标跟随主题变化，与主目录下的其他文件夹图标保持一致

【实际结果】：系统主题为oranic glass时，文件管理器主目录的桌面图标没有跟随主题变化
![image](https://user-images.githubusercontent.com/23466548/225249432-57e2e9f1-e126-43b2-b8bc-e9ca0a3baf46.png)

[bug-185317](https://pms.uniontech.com/bug-view-185317.html)

**Comment by kegechen** [comment]
deepin-desktop-theme 资源已经合并。可以用develop仓库测试

**Comment by babyfengfjx** [comment]
@vivianxf 问题需要在testing 确认合入，且回归通过后，进行关闭，并及时挪动看板中的状态。

**Comment by vivianxf** [comment]
【验证环境】：
镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230504
内核：6.1.11
验证步骤：提单的步骤
验证现象：符合预期
【验证结果】：通过
