### ISSUE TITLE
V23 a2 暗色主题对于部分qt应用和gtk应用不生效

### ISSUE THREAD

**Issue by xzl01** [linuxdeepin/developer-center#3892]
### SUMMARY | 问题概要

暗色主题下 gtk应用：vscode qt应用：qtcreator 的标题栏是白色的，影响美观：
![image](https://user-images.githubusercontent.com/31403725/225277262-7d72a58f-8f2f-43eb-88ca-ae420de927a8.png)

![image](https://user-images.githubusercontent.com/31403725/225277337-f08182fd-8ae2-45e3-84ae-9d4060119ce4.png)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin v23 a2

dde-qt5integration:
  已安装：5.6.4
  候选： 5.6.5
  版本列表：
     5.6.5 500
        500 https://ci.deepin.com/repo/obs/deepin:/Develop:/dde/deepin_develop  Packages

### STEPS TO REPRODUCE | 复现步骤

1. 控制中心->个性化->外观->深色
2. 启动vscode 和 qt 应用
3. 启动自研应用

### OBSERVED RESULT | 观察到的结果

自研应用表现正常
qt5应用和gtk应用表现异常

### EXPECTED RESULT | 期望的结果

表现正常 暗色模式

**Comment by justforlxz** [comment]
https://github.com/linuxdeepin/dde-appearance/pull/17 主题设置由 deepin-wm-dbus 对 deepin-kwinrc 更新，kwin 会重载主题配置。
