### ISSUE TITLE
deepin-prime 集成

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#3895]
仓库地址

**Comment by Zeno-sole** [comment]
[附件.zip](https://github.com/linuxdeepin/developer-center/files/10988620/default.zip)

**Comment by Zeno-sole** [comment]
包名| 版本
--|--
deepin-prime | 1.0.1

**Comment by Zeno-sole** [comment]
@babyfengfjx  详情见附件 请安排验证

**Comment by Zeno-sole** [comment]
仓库地址： deb  [trusted=yes] https://aptly.uniontech.com/pkg/beige-v2/release-candidate/ZGVlcGluLXByaW1lMjAyMy0wMy0xNiAxMTozOToyNA/  unstable main

**Comment by SuperEffie** [comment]
测试通过。正常下载deepin-prime工具，6.1版本内核集成nvidia-driver驱动后，可通过命令sudo prime-select nvidia正常切换N卡。请走下一步流程

**Comment by Lichenkass** [comment]
3
