### ISSUE TITLE
导入 github pull request 的临时办法

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/developer-center#39]
目前 github2gerrit 不太能用, 大家可以先手动导入 PR, 以 
https://github.com/linuxdeepin/dde-daemon/pull/6 为例,
```sh
git remote add github https://github.com/linuxdeepin/dde-daemon.git
git fetch github
git ls-remote github
git fetch github pull/6/head:pr-6
git checkout pr-6

# 如果需要 review
git commit --amend # 生成 Change-ID, 如果有多个提交则需要 rebase
git review -r origin release/3.0

# 如果已经在 github 上进行过代码审查, 可以直接 push(需要 owner 权限). 好处是 github 上的 merge 会自动关闭
git push origin HEAD:release/3.0
```

**Comment by hualet** [comment]
:+1:

**Comment by snyh** [comment]
正好测试下 https://github.com/linuxdeepin/dde-daemon/pull/9

**Comment by jouyouyun** [comment]
git review origin release/3.0  这句写错了改成：git review -r origin release/3.0 或者 git review release/3.0
另外在 git review 之前需要执行下 git commit --amend , 用来生成 Change-Id

**Comment by fasheng** [comment]
+1



2016年2月23日 10:08, 10:08，在 wen <notifications@github.com> 已写:
