### ISSUE TITLE
Not access the Control Center.

### ISSUE THREAD

**Issue by Xeers** [linuxdeepin/developer-center#390]
In Arch-Deepin with the latest updates you can not access the control center. The Disks icon in the dock is also not displayed. In the Launcher the text in Spanish does not appear (it only appears in the small menu mode).

**Comment by felixonmars** [comment]
Please try again with deepin-control-center 4.3.1-1.

**Comment by Xeers** [comment]
Control center solved, very fast. Thank you. And the other two problems?

**Comment by Xeers** [comment]
The Disk icon of the dock is only displayed with the original Deepin icons.

**Comment by hualet** [comment]
I just saw another issue opened by you https://github.com/linuxdeepin/developer-center/issues/381 @Xeers, Please don't repeat yourself.
