### ISSUE TITLE
v23 屏幕旋转xorg崩溃

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#3900]
### SUMMARY | 问题概要

v23 屏幕旋转xorg崩溃

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

v23 A2
amd集显

### STEPS TO REPRODUCE | 复现步骤

控制中心设置屏幕方向

**Comment by Zeno-sole** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1009325

**Comment by luodeepin** [comment]
在环境版本：
xserver-xorg   1:7.7+23      
xserver-xorg-video-ati 1:19.1.0.1-3deepin  
xserver-xorg-video-radeon 1:19.1.0.1-3deepin

在控制中心旋转屏幕时，没有出现崩溃的情况
![录屏_选择区域_20230321092653](https://user-images.githubusercontent.com/96416089/226502552-711689e5-6123-48e0-ae81-339f977defe4.gif)
