### ISSUE TITLE
【偶现问题】dock栏托盘弹出时点击非托盘图标区域崩溃

### ISSUE THREAD

**Issue by asterwyx** [linuxdeepin/developer-center#3910]
### SUMMARY | 问题概要

dock栏点击托盘图标弹出托盘，点击非托盘图标时，dde-dock崩溃重启。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Distribution: deepin V23 Alpha2
Package: dde-dock 6.0.9.2+u189

### PRE-REQUIREMENT | 预置条件

存在应用处于托盘区域

### STEPS TO REPRODUCE | 复现步骤

1. 点击打开托盘弹窗；
2. 点击除托盘图标的任意区域；
3. 观察dock是否崩溃重启。

### OBSERVED RESULT | 观察到的结果

dock崩溃，重启。

### EXPECTED RESULT | 期望的结果

dock正常关闭托盘弹窗。

### ADDITIONAL INFORMATION | 额外补充

无

**Comment by ComixHe** [comment]
目前未能复现

**Comment by zccrs** [comment]
只重现过一次

**Comment by babyfengfjx** [comment]
@luodeepin 请尝试复现，如无法复现可作为偶现问题跟踪。

**Comment by asterwyx** [comment]
今天刚刚重现，经过排查coredump发现是少判断了空指针行为，对比源中的代码和最新代码发现已经修复，升级到master最新提交，验证通过。

**Comment by zccrs** [comment]
需要确认是否提交到了testing仓库

**Comment by sany98215** [comment]
我这里经常会出现，自动崩溃重启

**Comment by BLumia** [comment]
>  @sany98215 
> 我这里经常会出现，自动崩溃重启

你的问题应该是 https://github.com/linuxdeepin/developer-center/issues/3598 吧？如果是的话，建议移步那个 issue。这个 issue 与那个是有差异的。

**Comment by asterwyx** [comment]
该问题现在是处于什么状态？最新版本的dock已经不会复现，是不是应该关闭这个issue？

**Comment by BLumia** [comment]
先关闭处理吧。若后续仍然能复现再来 reopen 并提供进一步的详细信息。
