### ISSUE TITLE
CI/CD: 应当为提供单元测试等额外集成检查的仓库提供相应支持

### ISSUE THREAD

**Issue by BLumia** [linuxdeepin/developer-center#3917]
dde-file-manager 相关的仓库使用了原本位于 Jenkins 上的一些单元测试检查，由于 GitHub 目前缺少这些测试的检查，故这些项目仍然在使用 Gerrit 作为开发平台进行开发并不定期进行代码同步。沟通后，当 GitHub 能够提供相应测试时，团队也愿意进行代码迁移。

需要 CI/CD 组为此团队的需求提供相应的支持。

**Comment by hudeng-go** [comment]
单元测试正常可以在构建的时候跑，autotest类的偏cd估计还是要用github action转jenkins任务的方案处理了。

**Comment by BLumia** [comment]
可以和 @max-lvs 沟通下具体需求，以及不太清楚到底多少个项目是有这种额外需求的，以及原本的测试工作流是哪边编写的。如果原本也是研发编写的话，或许可以考虑都转成 GitHub Action 由项目组自己放置自定义的额外工作流。

**Comment by max-lvs** [comment]
我们期望每次 https://github.com/linuxdeepin/dde-file-manager 有新的 PR 在merge 到github master 分支之前，触发CI流程 跑一下 单元测试流程，防止新代码破坏现有仓库产品代码。从目前流程来看，这个流程还未加进来，导致UT 跑不起来。不能对现有产品代码形成保护，请cicd相关同事麻烦处理一下。

**Comment by hudeng-go** [comment]
ok,mark，清明后立马添加支持。

**Comment by max-lvs** [comment]
好的，感谢 登哥

**Comment by hudeng-go** [comment]
@max-lvs 在cmake里面添加ut test支持，编译完成后跑你们的ut test脚本，这个方案ok不，目前最快的实现方案。

**Comment by hudeng-go** [comment]
直接复用目前的obs构建流程。

**Comment by max-lvs** [comment]
可以先跑起试一试，毕竟构建都未成功，跑后续流程是无意义的。

**Comment by hudeng-go** [comment]
目前已经能在构建成功后跑动ut测试，但是有一些测试项不能过，暂时先跳过，待后续由文管那边跟踪处理。

**Comment by BLumia** [comment]
了解，那就 close 掉这个 issue 了 :)
