### ISSUE TITLE
【deepin_V23_beta】【偶现问题 持续跟踪】【一般】【有空】【集成测试】【DDE】【控制中心】pc和手机蓝牙互连接，向手机发送文件时失败

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#3918]
### SUMMARY | 问题概要

pc和手机蓝牙互连接，向手机发送文件时失败

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

镜像地址：https://cdimage.uniontech.com/community/releases/23-Alpha2/deepin-desktop-community-23-Alpha2-amd64.iso
内核版本： 5.18.17
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-intergration-pr-42/testing/ ./
dde-control-center:6.0.9.1

### PRE-REQUIREMENT | 预置条件

手机和PC进行蓝牙互连接

### STEPS TO REPRODUCE | 复现步骤

1.在控制中心-蓝牙-我的设备选择手机右键点击发送文件
2.选择任意图片，选中手机
3.点击下一步
4.观察现象

### OBSERVED RESULT | 观察到的结果

1.向手机设备发送文件失败，提示未找到已连接的设备
![截图_dde-control-center_20230321140411](https://user-images.githubusercontent.com/96415804/226535600-42334523-dab3-4126-b29a-fcbbbc73413c.png)

### EXPECTED RESULT | 期望的结果

1.PC与手机可以互发文件

**Comment by babyfengfjx** [comment]
帮忙分析看该模块是否属于DDE范畴。

**Comment by Decodetalkers** [comment]
暂时找不到如何处理的办法，赶不上beta

**Comment by xzl01** [comment]
这个问题之前也存在过，使用小米手机向deepin系统发送无后缀名文件发送失败

**Comment by ComixHe** [comment]
iphone本身不支持通过蓝牙发送文件

**Comment by ComixHe** [comment]
暂时无法复现

**Comment by zccrs** [comment]
需要 @babyfengfjx 复现方法

**Comment by babyfengfjx** [comment]
请再次尝试复现，如有复现环境可以找开发确认，如无法复现，可作为偶现问题跟踪。

**Comment by vivianxf** [comment]
现多次在不同机器上尝试，均无法复现，作为偶现问题跟踪

**Comment by vivianxf** [comment]
最新版v23beta镜像验证，安卓手机无法复现该问题，经和开发沟通，苹果手机不支持蓝牙传输文件，先关闭此单
