### ISSUE TITLE
chrome&&typewriting was removed

### ISSUE THREAD

**Issue by he1l0world** [linuxdeepin/developer-center#392]
When use chrome with too many windows , laptop began to run slowly .  then it auto reboot, when it's over.
I found that the chrome&& chinese typewriting was gone.

**Comment by hualet** [comment]
Chrome ate too much CPU and got your machine overheated, so it rebooted. You can try to turn on hareware acceleration  in Chrome to see if it's getting better.

As to the typewriting one, I can't actually understand.
