### ISSUE TITLE
Cant exit emergency mode after shutdown

### ISSUE THREAD

**Issue by Dorfeuheinz** [linuxdeepin/developer-center#3922]
### SUMMARY | 问题概要

 This issue has been persisted for way too long now, & honestly its getting on my nerves. Ive reinstalled the OS upto 30 times now, literally, but the issue persists
Whenever I shut down my OS, even though its a safe shutdown, every app has been closed before shutdown, I still always enter into emergency mode upon restarting. & it doesn't allow me to type anything, all I can do is press enter, but nothing happens
Whenever I press enter, the same messages pop up.
Please help me. I cant type any command in emergency mode, all I can do is command line grub but that doesnt help either. I cant exit out of emergency mode

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin v20.8

### STEPS TO REPRODUCE | 复现步骤

Theres no particular step to reproduce this issue other than-
1. Install OS
2. Keep the OS working 24/7 without any shutdowns for several days 
3. Shutdown after 1 month
This arrives me to emergency mode that I cant exit out of for some reason

### OBSERVED RESULT | 观察到的结果

Not being able to type anything while in emergency mode because apparently its read-only

### EXPECTED RESULT | 期望的结果

Should be able to type commands like fsck dev/sdb which might resolve the issue

**Comment by BLumia** [comment]
Duplicated with https://github.com/orgs/linuxdeepin/discussions/3897, let's discuss there before we ensure it's a reproduceable bug :)
