### ISSUE TITLE
dde-wm-chooser not working

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/developer-center#393]
When I try launching deepin-wm-multitaskingview, nothing happens.
Terminal output is just this:
```
dbus-send --session --dest=com.deepin.wm --print-reply /com/deepin/wm com.deepin.wm.PerformAction int32:1
method return time=1509810278.021693 sender=:1.15 -> destination=:1.110 serial=48 reply_serial=2
```

**Comment by oberon2007** [comment]
This actually seems to be a problem with **dde-wm-chooser** in that selecting 'Effect Mode' in the initial dialog in fact does not actually turn on window effects. So even though I have selected Effect Mode in the beginning, multitasking view is not working and also when I look in the control-center 'Enable window effect' (which should actually be labelled 'window effects' with an 's' by the way 😉 ) is turned OFF !
Only when I use the switch there, multitasking view is finally actually switched on.
@sonald @kirigayakazushin

**Comment by oberon2007** [comment]
It looks like **wm-chooser** is using the wrong config path, writing to **~/.config/wm-chooser** instead of **~/.config/wm-switcher**. The onlxy effect the setting there has is, that the chooser will not run on next login, but it doesn't effect the actual wm choice.

**Comment by oberon2007** [comment]
Actually there even seem to be two different config files created for wm-switcher:
One is in **~/.config/wm-switcher**, this one has no effect
The other one, which is actually respected, is located in **~/.config/deepin/wm-switcher**

**Comment by hualet** [comment]
Effect mode turns window effects off, which is actually using deepin-metacity as the window manager, and you can't get multitasking view to run properly in this mode. I don't see any problem here @oberon2007

**Comment by sonald** [comment]
Yes, deepin-wm-switcher have changed config location for consistency, dde-wm-chooser should've  followed this changed.

**Comment by electricface** [comment]
https://cr.deepin.io/#/c/27985/ fixed
