### ISSUE TITLE
【deepin_V23_beta】【一般】【有空】【论坛反馈】【DDE】【桌面】Some systemd services timeout when stopping

### ISSUE THREAD

**Issue by SuperEffie** [linuxdeepin/developer-center#3933]
### SUMMARY | 问题概要

【论坛链接】：[https://bbs.deepin.org/post/254088](https://bbs.deepin.org/post/254088)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

【镜像地址】：https://cdimage.uniontech.com/daily-iso/image-beige/20230207
【版本信息】：dde-session-shell：6.0.6

### STEPS TO REPRODUCE | 复现步骤

1. 终端中输入命令：reboot。查看关机或重启时长
2. 若关机时长超过60s，登录进入桌面后终端中输入命令：journalctl --user -b -l，查看报错信息

### OBSERVED RESULT | 观察到的结果

1. 存在关机时长超过60s的情况
2. 输入命令journalctl --user -b -l后，存在dde-display.service服务超时报错信息，如以下截图：
![1](https://user-images.githubusercontent.com/58986464/227415844-66258fc8-9a89-4a4c-9cf1-4e03700d02c9.jpg)
![2](https://user-images.githubusercontent.com/58986464/227415883-d1a88dd4-7f34-4e3f-942c-b6ebd885e3d7.jpg)

### EXPECTED RESULT | 期望的结果

1. 关机或重启时长不超过60s
2. 且输入命令：journalctl --user -b -l，无dde-display.service服务超时报错信息

**Comment by babyfengfjx** [comment]
请帮忙分析优化~

**Comment by zccrs** [comment]
@justforlxz 今天确认一下是不是还是这个bug

**Comment by justforlxz** [comment]
> @justforlxz 今天确认一下是不是还是这个bug

没有重现该问题。

**Comment by SuperEffie** [comment]
【问题备注】：论坛用户反馈相关链接：https://bbs.deepin.org/post/257734

**Comment by SuperEffie** [comment]
@black-desk 用户反馈该问题与DCM相关，辛苦大佬帮忙优化下该问题~

**Comment by black-desk** [comment]
Update:

Any systemd service timeout to stop will cause similar problem.

For now we check that:
1. somehow some wine processes in container will not response to SIG_TERM;
2. somehow some processes launched by dde-application-manager will not response to SIG_TERM, including some dde-file-manager processes.

**Comment by black-desk** [comment]
Should we update the systemd configuration to update the time limit to, something like 20s (suggested by @zccrs)?

cc @BLumia.

Sounds like we should have some mechanism to let user know what is happening and chose what to do during shutdown.

**Comment by BLumia** [comment]
> Should we update the systemd configuration to update the time limit to, something like 20s

20 or 30s could be enough IMO.

> Sounds like we should have some mechanism to let user know what is happening and chose what to do during shutdown.

also +1 for this :)

**Comment by SuperEffie** [comment]
@black-desk 麻烦评估下后续处理方案，是否转换成需求处理

**Comment by black-desk** [comment]
由于之前 @justforlxz 做的更改. 现在dde的主要组件都由systemd来进行管理.

也许是由于dde的部分service文件写得不对, 部分无法正常退出的systemd服务会阻塞关机过程.

目前有几个修复方向.

1. 明确一下这些无法正常退出的服务阻塞关机过程的原因, 修改系统中systemd服务的依赖关系来修正此错误.

   此方案解决的是问题的根因, 但是如果我们以后还会编辑systemd的服务配置文件的话, 这种解决方案并不能保证未来类似的错误不会再发生.

2. 在控制中心添加一个设置项, 允许用户自己调控systemd停止服务时的超时时间.

   用户如果将这个时间配得比较短, 那么一些能正常退出, 只是处理退出流程较慢的服务可能会被提前杀死而丢失数据.

2. 我们将systemd的默认配置直接改了, 如上面的讨论一样, 直接改成10/20s.

   最快的方案.问题和2 一样.

4. 更改dde中桌面/图像相关服务的配置. 使其不要过早退出. 在关机过程中持续存在. 可以展示当前有哪些尚未退出的systemd服务. 使得用户可以手动地 在图形化的界面中解决这一问题.

   比较耗时.

我目前倾向于先做3, 然后 1 和 2 一起进行. 4 可以排到v23相对来说比较稳定之后再进行.

现在我的问题是:
- 2 有必要转需求么? 还是我们自己处理?
- 1 谁来处理?
- 还有其他的修复思路么?
@BLumia @justforlxz @zccrs

**Comment by BLumia** [comment]
1，2，3都应当做，3 最好做所以其实可以考虑先做 3。1 是无论如何都要做的，2 其实可以考虑放到 tweaks 里（因为从用户角度而言它不一定看得懂这个是什么意思）。

另外 4 的行为，如果用户需要关心的话，按理说是应该和 login1 的 inhibit lock 关联的。如果不是用户需要关心的内容的话，给用户看这个列表反而可能不太好。

**Comment by black-desk** [comment]
???

**Comment by UTsweetyfish** [comment]
fyi 在 #5087 那边有类似的问题，是由 winedevice.exe 导致的，winedevice.exe 有时 SIGTERM 不退出，只能等 90 秒超时后 SIGKILL 掉

**Comment by zccrs** [comment]
> 

我倾向于先做3，2可以规划上，1有时间就分析。

**Comment by black-desk** [comment]
你把所有相关的issue都先在这个issue里面列出来一下吧。 @UTsweetyfish

**Comment by UTsweetyfish** [comment]
今天还遇到一个超时，似乎与 wine 无关？

dde-session=1.1.4 的 systemd/user/dde-session-manager.service 中：

```
ExecStopPost=/usr/libexec/dde-session-ctl --shutdown
ExecStopPost=-/bin/sh -c 'test "$SERVICE_RESULT" != "exec-condition" && systemctl --user unset-environment XDG_CURRENT_DESKTOP'
```

也有概率造成 timeout

<details><summary>systemd 日志</summary>
<p>

```
8月 03 15:46:53 v23-PC systemd[3920]: dde-session-manager.service: State 'stop-post' timed out. Terminating.
8月 03 15:46:53 v23-PC systemd[3920]: dde-session-manager.service: Control process exited, code=killed, status=15/TERM
8月 03 15:46:53 v23-PC systemd[3920]: dde-session-manager.service: Failed with result 'timeout'.
8月 03 15:46:53 v23-PC systemd[3920]: Stopped dde-session-manager service.
8月 03 15:46:53 v23-PC systemd[3920]: dde-session-manager.service: Triggering OnFailure= dependencies.
8月 03 15:46:53 v23-PC systemd[3920]: Removed slice User Core Session Slice.
8月 03 15:46:53 v23-PC systemd[3920]: session.slice: Consumed 6.597s CPU time.
```

</p>
</details>

**Comment by black-desk** [comment]
@UTsweetyfish
我感觉其实重点并不是什么东西导致某个组卡住了。
应该考虑解决的问题是，那个被卡住的组为什么会阻塞住关机事件。

如果随便哪个服务下面随便挂着的一个进程 不吃sigterm 就能导致整个机子关不掉机需要等3分钟 这是相当不合理的设计。

**Comment by UTsweetyfish** [comment]
> 如果随便哪个服务下面随便挂着的一个进程 不吃sigterm 就能导致整个机子关不掉机需要等3分钟 这是相当不合理的设计。

这是很合理的设计吧.. 比如文件保存、socket 关闭一类的，先等待程序退出，再超时强退 是很合理的设计吧？

**Comment by UTsweetyfish** [comment]
> 是由 winedevice.exe 导致的，winedevice.exe 有时 SIGTERM 不退出，只能等 90 秒超时后 SIGKILL 掉

参考了一下 lutris 的代码

https://github.com/lutris/lutris/blob/dd6df02c661d4be1dc67f90003568d48d1c66c7d/lutris/runners/commands/wine.py#L158-L178

可以先尝试运行 `WINEPREFIX="/path/to/prefix" wineserver -k`？

**Comment by UTsweetyfish** [comment]
> 这是相当不合理的设计

windows 下被 notepad.exe 阻塞关机似乎也很常见吧（

**Comment by BLumia** [comment]
> windows 下被 notepad.exe 阻塞关机似乎也很常见吧（

阻塞关机的方式不应当一样。通过 inhibit 阻塞的话系统应当展示阻塞列表。比如我们的深度编辑器在新建文件并输入一些字符时，不关闭编辑器窗口，直接尝试关机，就会看到那个列表。

**Comment by UTsweetyfish** [comment]
> > windows 下被 notepad.exe 阻塞关机似乎也很常见吧（
> 
> 阻塞关机的方式不应当一样。通过 inhibit 阻塞的话系统应当展示阻塞列表。比如我们的深度编辑器在新建文件并输入一些字符时，不关闭编辑器窗口，直接尝试关机，就会看到那个列表。

嗯嗯是的，但是那个其实都没进入 systemd 意义上的关机？只是在关机前通过 dbus 检查了一下有哪些进程可能会丢失数据？

**Comment by BLumia** [comment]
对。那个是 https://www.freedesktop.org/wiki/Software/systemd/inhibit/ 这个东西。我们的意思也是如果 systemd 的真正的关机阶段还能卡住的话，那就一定是非预期的行为，需要我们介入分析原因处理了。

**Comment by BLumia** [comment]
DDE 自身导致这个问题的应该已经处理并合入了。其它导致这个问题的地方如果暂时没比较合理的方案的话，先做下 3 吧，减少因此导致的关机等待时间。

**Comment by BLumia** [comment]
@Zeno-sole 改个 systemd 配置？

**Comment by UTsweetyfish** [comment]
> @Zeno-sole 改个 systemd 配置？

90 秒是上游的默认配置，改成 30 秒或者更短没什么意义（

最好还是不改

**Comment by BLumia** [comment]
这个问题你有别的方案吗，以及这个 90 秒有什么实际的意义吗（

**Comment by UTsweetyfish** [comment]
> 这个问题你有别的方案吗

没有，建议长期跟踪；wine 的问题据说以后可以从窗管还是 AM 解决？
非 wine 的问题的话可以进行解决

> 以及这个 90 秒有什么实际的意义吗（

发行版最好还是不要改 systemd 的默认行为，而且后续涉及软件包更新会不方便；如果有人嫌慢的话就解释吧（

**Comment by Zeno-sole** [comment]
@SuperEffie  请转wine 项目组处理

**Comment by babyfengfjx** [comment]
@kobe337  这个问题请继续跟进一下进展。

**Comment by kobe337** [comment]
#8578 验证通过，目前的需求如下：
现在修改后按这个方式执行，RC先只做到12
背景：当前关机需要90秒时间，影响体验
原因：
1自研应用关机时存在阻塞
2.三方应用阻塞
3.系统阻塞等待时间为90s
解决方案修改阻塞等待时间：
1.调整等待时间am启动相关的为3秒杀死进程（RC处理方案）
2.其他应用阻塞等待时间调整为30s（RC处理方案）
3.自研应用阻塞问题需要排查 （release处理）
4.如通过AM阻塞项需要暴露给用户可进行管理（长期工作）

【环境】：
镜像：Deepin OS-23-20240509035255-1_x86_64
仓库：提测单仓库
内核：Linux deepinb3-PC 6.6.25-amd64-desktop-hwe https://github.com/linuxdeepin/developer-center/issues/23.01.00.25 SMP PREEMPT_DYNAMIC Wed Apr 10 21:20:25 CST 2024 x86_64 GNU/Linux

【结论】：
测试通过，暂无严重问题及影响，开启常用应用，开启wine应用、开启qq,开启预装应用，重启与关机设备，验证通过
