### ISSUE TITLE
Chrome Apps icons now are all like Google Chrome

### ISSUE THREAD

**Issue by dantopa** [linuxdeepin/developer-center#394]
With latest update, all the Chrome Apps (integrated with the desktop) are now showing the same icon, the google chrome icon. In the past, every app recognized their own icon. In fact, if I change the icon theme, switching from deepin to gnome for example, the Chrome Apps recognizes the icon.

**Comment by hualet** [comment]
That's basically because deepin-icon-theme switched from flattr to papirus, but I'm still confused why this change makes difference on chrome app icons since they're all provided additionally by Chrome.
Debugging may take some time.

**Comment by hualet** [comment]
fixed
