### ISSUE TITLE
network-manager集成

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#3940]
仓库地址：  deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-intergration-pr-53/testing/ ./

**Comment by Zeno-sole** [comment]
包名 | 版本
-- | --
network-manager | 1.42.4-1

**Comment by Zeno-sole** [comment]
@ComixHe  请备注更新说明 测试建议 影响范围等

**Comment by ComixHe** [comment]
## 更新内容

同步上游network-manager的版本至1.42.4-1
主要是为了解决热点问题，相关issus: https://github.com/linuxdeepin/developer-center/issues/3732

## 影响范围

所有涉及到使用网络的模块，例如dde-daemon等

## 测试建议

因为本次集成是为了修复热点问题，所以可测试使用不同加密方式的热点其他设备是否能成功连接，上面提到的issue是否成功解决

**Comment by Zeno-sole** [comment]
@babyfengfjx  请安排验证

**Comment by ComixHe** [comment]
这里有一个用户反馈的bug：https://github.com/orgs/linuxdeepin/discussions/3872#discussioncomment-5404958，原因已排查，具体解决方案还没有决定

**Comment by ComixHe** [comment]
最后决定删除此patch, 因为最新版的network-manager已支持wpa3和wifi6

**Comment by ComixHe** [comment]
##更新内容

删除了原先关于wifi6的patch,因为network-manager已经支持了wifi6
新的提交为了解决这个issue: https://github.com/linuxdeepin/developer-center/issues/3732

##影响范围

系统的wifi连接

##测试建议

可以在wifi6下使用不同的加密方式和不同的密码组合来测试连接行为是否正常

**Comment by Zeno-sole** [comment]
@SuperEffie  版本更新 1.42.4-1+rb1 请验证

**Comment by SuperEffie** [comment]
【测试结论】：测试通过，请走下一步流程～
验证issue#3732通过，测试机在打开安全协议为“WPA3个人版”的热点时，电脑手机均可连接该热点；
测试机在打开安全协议为“WPA/WPA2个人版”的热点时，电脑v20、v23系统均可连接该热点，部分安卓手机可正常连接，苹果手机连接该热点出现异常（可能与手机安全加密模式相关，影响不太大）；
正常连接加密和无加密wifi；
USB无线网卡正常连接各种wifi。
