### ISSUE TITLE
docker.io集成

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#3965]

**Comment by Zeno-sole** [comment]
仓库地址： deb [trusted=yes] https://ci.deepin.com/repo/deepin/deepin-community/obs-repos/ beige community

**Comment by Zeno-sole** [comment]
包名|版本
--|--
etcd|3.4.23-4
golang-bugsnag-panicwrap|1.2.0-2
golang-github-akavel-rsrc|1:0.8.0-2
golang-github-armon-go-metrics|0.3.4-1
golang-github-benbjohnson-clock|1.3.0-1
golang-github-bitly-go-simplejson|0.5.0-6
golang-github-bmizerany-assert|0.0~git20120716-4
golang-github-bshuster-repo-logrus-logstash-hook|0.4.1-2
golang-github-bsphere-le-go|0.0~git20170215.0.7a984a8-1.1
golang-github-bugsnag-bugsnag-go|1.7.0-2
golang-github-casbin-casbin|2.60.0-1
golang-github-cilium-ebpf|0.9.1-1
golang-github-cloudflare-cfssl|1.2.0+git20160825.89.7fb22c8-3.1
golang-github-cloudflare-go-metrics|0.0~git20151117.0.6a9aea3-4
golang-github-cloudflare-redoctober|0.0~git20161017.0.78e9720-5
golang-github-cockroachdb-datadriven|1.0.2-6
golang-github-containerd-cgroups|1.0.4-1
golang-github-containerd-console|1.0.3-1
golang-github-containerd-fifo|1.0.0-3
golang-github-containerd-go-runc|1.0.0-1
golang-github-containerd-typeurl|1.0.2-1
golang-github-coreos-bbolt|1.3.6-2
golang-github-coreos-pkg|4-3
golang-github-coreos-semver|0.3.0-1
golang-github-cyphar-filepath-securejoin|0.2.3-1
golang-github-daaku-go.zipexe|1.0.1-2
golang-github-datadog-zstd|1.4.5+patch1-1
golang-github-dghubble-sling|1.3.0-1
golang-github-docker-docker-credential-helpers|0.6.4+ds1-1
golang-github-docker-go|0.0~git20160303.0.d30aec9-3.1
golang-github-docker-go-connections|0.4.0-4
golang-github-docker-go-events|0.0~git20190806.e31b211-4
golang-github-docker-go-metrics|0.0.1-2
golang-github-docker-go-units|0.4.0-4
golang-github-docker-libtrust|0.0~git20150526.0.9cbd2a1-3.1
golang-github-docopt-docopt-go|0.6.2+git20180111.ee0de3b-1
golang-github-dvsekhvalnov-jose2go|1.5-1
golang-github-eapache-go-xerial-snappy|0.0~git20180814.776d571-1
golang-github-fernet-fernet-go|0.0~git20180830.9eac43b-2
golang-github-fluent-fluent-logger-golang|1.9.0-1
golang-github-fvbommel-sortorder|1.0.2-3
golang-github-garyburd-redigo|0.0~git20150901.0.d8dbe4d-2.1
golang-github-geertjohan-go.incremental|1.0.0-2
golang-github-geertjohan-go.rice|1.0.2-1
golang-github-ghodss-yaml|1.0.0+git20220118.d8423dc-2
golang-github-go-kit-kit|0.10.0-1
golang-github-gofrs-uuid|4.3.1-1
golang-github-gogo-googleapis|1.4.0-2
golang-github-golang-jwt-jwt|4.4.3-1
golang-github-golang-protobuf-1-3|1.3.5-4
golang-github-golang-snappy|0.0.2-3
golang-github-google-certificate-transparency|0.0~git20160709.0.0f6e3d1~ds1-3
golang-github-google-go-querystring|1.1.0-2
golang-github-google-shlex|0.0~git20191202.e7afc7f-1
golang-github-google-uuid|1.3.0-1
golang-github-googleapis-gax-go|2.0.5-4
golang-github-googleapis-gnostic|0.2.0-4
golang-github-gorilla-handlers|1.5.1-3
golang-github-gorilla-websocket|1.5.0-2
golang-github-graylog2-go-gelf|0.0+git20191017.1550ee6-1
golang-github-grpc-ecosystem-go-grpc-middleware|1.3.0-1
golang-github-grpc-ecosystem-go-grpc-prometheus|1.2.0+git20191002.6af20e3-3
golang-github-grpc-ecosystem-grpc-gateway|1.6.4-2
golang-github-grpc-ecosystem-grpc-opentracing|0.0~git20180507.8e809c8-2
golang-github-hailocab-go-hostpool|0.0~git20160125.0.e80d13c-1.1
golang-github-hashicorp-go-memdb|1.2.1-1
golang-github-hashicorp-memberlist|0.2.2-2
golang-github-hashicorp-serf|0.9.4~ds1-1
golang-github-imdario-mergo|0.3.12-1
golang-github-ishidawataru-sctp|0.0+git20210707.9a39160-1
golang-github-jmhodges-clock|1.0-3.1
golang-github-jmoiron-sqlx|1.3.5-1
golang-github-jonboulle-clockwork|0.1.0-4.1
golang-github-json-iterator-go|1.1.12-1
golang-github-kardianos-osext|0.0~git20190222.2bc1f35-3
golang-github-kisielk-sqlstruct|0.0~git20150917.0.0b86a3e-2.1
golang-github-klauspost-compress|1.15.12+ds1-3
golang-github-knetic-govaluate|3.0.0+git20171022.9aa4983-2
golang-github-mattn-go-runewidth|0.0.14-1
golang-github-miekg-dns|1.1.50-2
golang-github-mitchellh-hashstructure|1.1.0-1
golang-github-moby-locker|1.0.1-3
golang-github-moby-term|0.0~git20221120.abb1982-1
golang-github-modern-go-reflect2|1.0.2-2
golang-github-morikuni-aec|1.0.0-3
golang-github-mreiferson-go-httpclient|0.0~git20160630.0.31f0106-2.1
golang-github-ncw-swift|1.0.53-2
golang-github-nkovacs-streamquote|1.0.0-5
golang-github-olekukonko-tablewriter|0.0.5-2
golang-github-opencontainers-go-digest|1.0.0-2
golang-github-opencontainers-image-spec|1.1.0~rc2-1
golang-github-opencontainers-selinux|1.10.0+ds1-1
golang-github-opencontainers-specs|1.0.2.118.g5cfc4c3-1
golang-github-opentracing-contrib-go-stdlib|1.0.0-2
golang-github-openzipkin-zipkin-go|0.1.5+git20190103.2fd7f4a-1.1
golang-github-philhofer-fwd|1.1.1-1
golang-github-pierrec-lz4|2.5.2-2
golang-github-prometheus-client-golang|1.14.0-3
golang-github-racksec-srslog|0.0~git20180709.a4725f0-2
golang-github-rcrowley-go-metrics|0.0~git20180125.8732c61-3
golang-github-rivo-uniseg|0.4.2-1
golang-github-samuel-go-zookeeper|0.0~git20180130.c4fab1a-1
golang-github-shopify-logrus-bugsnag|0.0~git20171204.577dee2-3
golang-github-shopify-sarama|1.22.1-1
golang-github-soheilhy-cmux|0.1.5-2
golang-github-stathat-go|0.0~git20130314.0.01d012b-2.1
golang-github-streadway-amqp|0.0~git20200716.e6b33f4-3
golang-github-tinylib-msgp|1.1.6-1
golang-github-tmc-grpc-websocket-proxy|0.0~git20200427.3cfed13-3
golang-github-tonistiigi-units|0.0~git20180711.6950e57-2
golang-github-valyala-bytebufferpool|1.0.0-3
golang-github-valyala-fasttemplate|1.2.2+ds1-1
golang-github-vbatts-tar-split|0.11.2+ds1-1
golang-github-vishvananda-netlink|1.1.0.125.gf243826-4
golang-github-xiang90-probing|0.0.2-2
golang-go-patricia|2.3.1-1
golang-go-zfs|3.0.0-1
golang-go.opencensus|0.24.0-1
golang-go.uber-atomic|1.10.0-2
golang-go.uber-multierr|1.6.0-1
golang-go.uber-zap|1.23.0-1
golang-gocapability-dev|0.0+git20200815.42c35b4-2
golang-golang-x-tools|1:0.5.0+ds-1
golang-google-api|0.61.0-1
golang-google-cloud|0.56.0-3
golang-google-genproto|0.0~git20200413.b5235f6-3
golang-google-grpc|1.33.3-2
golang-gopkg-cheggaaa-pb.v1|1.0.25-1
golang-gopkg-eapache-go-resiliency.v1|1.2.0-1
golang-gopkg-eapache-queue.v1|1.1.0-2
golang-gopkg-inf.v0|0.9.1-2
golang-gopkg-rethinkdb-rethinkdb-go.v6|6.2.1-2
golang-gopkg-yaml.v3|3.0.1-3
golang-k8s-sigs-yaml|1.3.0-1
golang-objx|0.5.0-1
golang-testify|1.8.1-1
golang-uber-goleak|1.2.0-1
gotest.tools|3.0.3-1
gotestsum|1.8.2-1
notary|0.7.0+ds1-2
runc|1.1.4+ds1-1

**Comment by Zeno-sole** [comment]
### 更新说明

相关issues https://github.com/linuxdeepin/developer-center/issues/3928
docker以及相关依赖包集成

测试建议
验证docker基础功能

**Comment by Zeno-sole** [comment]
@UTsweetyfish  看下是否需要额外补充说明

**Comment by Zeno-sole** [comment]
https://github.com/linuxdeepin/developer-center/issues/3932

**Comment by UTsweetyfish** [comment]
> @UTsweetyfish 看下是否需要额外补充说明

没有，其他工作就不在这里做了。

**Comment by vivianxf** [comment]
【测试结论】：测试通过，请走下一步流程～
仓库升级正常，依赖安装正常
sudo apt install dock.io正常安装，基本功能使用正常
