### ISSUE TITLE
deepin-screen-recorder 會把最後幾秒的畫面給切掉

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#397]
譬如這 gif 最後幾秒都不見了
![deepin-screen-recorder_desktop_20171108115652](https://user-images.githubusercontent.com/20014762/32530948-3fff4f06-c47c-11e7-9276-a34479b52dd6.gif)

**Comment by JulianLai** [comment]
原來之前也有人提過
#320

**Comment by manateelazycat** [comment]
https://github.com/linuxdeepin/deepin-screen-recorder/commit/90633232b34478085f664a8da37053f471541d83 已经修复
