### ISSUE TITLE
Integrate dde-network dde-session-shell and dde-widgets

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#3970]
仓库地址： deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-intergration-pr-55/testing/ ./

**Comment by Zeno-sole** [comment]
包名 | 版本
-- | --
dde-network-core | 2.0.5
dde-session-shell | 6.0.7+rb1
dde-widgets | 6.0.10

**Comment by Zeno-sole** [comment]
@18202781743  请备注 更新说明  影响范围 测试建议等内容，备注完成后，转给 @babyfengfjx  安排测试验证

**Comment by 18202781743** [comment]
本次更新包括三个项目，其中dde-network-core依赖dde-session-shell，dde-widgets是独立的

## dde-widgets
### 更新内容
相关Issue: https://github.com/linuxdeepin/dde-widgets/issues/18
       https://github.com/linuxdeepin/dde-session-ui/issues/321

### 影响范围
- 小组件整体背景添加了模糊
- 各组件圆角的锯齿问题，包括编辑面板，显示面板及拖拽场景
- 时钟小组件和内存小组件 切换主题背景显示问题

### 测试用例
- 正常模式下背景无穿透
- 切换主题，分辨率，查看组件背景颜色显示问题，圆角是否存在锯齿

## dde-network-core
### 更新内容
相关https://github.com/linuxdeepin/developer-center/issues/3761
       https://github.com/linuxdeepin/dde-session-ui/issues/321

### 影响范围
- 控制中心无线网络列表无法自动刷新
- 当字体设置为20时文本显示不全

### 测试用例
- 见issue备注

**Comment by babyfengfjx** [comment]
@luodeepin 请开展对应集成验证，确认相关issue都无遗漏。

**Comment by SuperEffie** [comment]
【问题备注】：dde-session-shell ： 6.0.7+rb1 
该版本包集成后，开放了wayland入口，但切换至wayland依然停留在X11桌面

**Comment by asterwyx** [comment]
> 【问题备注】：dde-session-shell ： 6.0.7+rb1 该版本包集成后，开放了wayland入口，但切换至wayland依然停留在X11桌面

@SuperEffie 请将dde-session更新到最新版本，再进行测试，dde-session-shell只负责开启wayland入口，真正的session切换功能在dde-session实现。若出现相关问题，可咨询 @justforlxz。
