### ISSUE TITLE
deepin-kwin 5.25.0集成

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#3971]
更新说明
  - 删除了多任务视图对 dde-dock 的依赖
  - 合并 dde-kwin 提供的配置文件，并增加 `deepin-` 前缀，与上游 kwin 的配置文件做切割
影响范围
  - 更新前设置的个性化配置会无效，需要重新设置，例如合成器的开关、窗口主题、光标主题等。
测试建议
  - 安装后重新登录，并检查用户的目录是否存在 $HOME/.config/deepin-kwinrc 等 deepin-k 开头的配置文件，如果不存在，则测试失败。

**Comment by Zeno-sole** [comment]
仓库地址：  deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-intergration-pr-57/testing/ ./

**Comment by Zeno-sole** [comment]
包名 | 版本
--|--
deepin-kwin | 4:5.25.0-kwin.5.24.3

**Comment by Zeno-sole** [comment]
@justforlxz  请备注 更新说明 影响范围 测试建议等内容，备注完成后，转给 @babyfengfjx 安排测试验证

**Comment by justforlxz** [comment]
> @justforlxz 请备注 更新说明 影响范围 测试建议等内容，备注完成后，转给 @babyfengfjx 安排测试验证

已补充至开头。

**Comment by SuperEffie** [comment]
待startdde更新后进行验证~
