### ISSUE TITLE
dde-launcher 6.0.9 集成

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#3972]
仓库地址： deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-intergration-pr-56/testing/ ./

**Comment by Zeno-sole** [comment]
包名|版本
--|--
dde-launcher | 6.0.9

**Comment by Zeno-sole** [comment]
@BLumia  请备注 更新说明 影响范围 测试建议等内容，备注完成后，转给 @babyfengfjx 安排测试验证

**Comment by BLumia** [comment]
## 更新说明

  * 修正小窗口启动器左侧分类文字颜色的大小与颜色不正确的问题 https://github.com/linuxdeepin/developer-center/issues/3641
  * 全屏启动器中，应用分组的图标调整为最多只显示四个应用的图标（原本是最多 9 个） https://github.com/linuxdeepin/dde-launcher/issues/342
  * 修正应用分组图标未对齐的问题 https://github.com/linuxdeepin/developer-center/issues/3864
  * 优化图标加载逻辑，避免图标加载导致页面与列表滚动不流畅 https://github.com/linuxdeepin/developer-center/issues/3618
  * 修复全屏启动器图标抽屉打开时，背景没有模糊的问题 https://github.com/linuxdeepin/dde-launcher/issues/350
  * 修正小窗口启动器中，切换模式的按钮图标模糊的问题 https://github.com/linuxdeepin/dde-launcher/issues/352
  * 小窗口启动器中，当收藏的应用小于一行时，调整为只展示一行 https://github.com/linuxdeepin/dde-launcher/issues/380

其它相关：

- https://github.com/linuxdeepin/developer-center/issues/3778

## 影响范围

此集成仅会影响 dde-launcher 启动器，不影响 DDE 的其它组件。

## 测试建议

更新说明中已附带相关 Issue 链接，可按照对应 Issue 查看详情。

测试方式为通过测试仓库获取并安装更新。更新安装后，需要手动结束 `dde-launcher` 进程（`killall dde-launcher`）然后再进行测试。

## 其它信息

- 集成申请：https://github.com/deepin-community/Repository-Integration/pull/56
- Changelog 更新 PR 清单
  - https://github.com/linuxdeepin/dde-launcher/pull/383

**Comment by vivianxf** [comment]
【测试结论】：测试通过，请走下一步流程～
仓库升级正常，包升级正常
1.以上comment中issues 验证通过，除 #3618，启动器切换页签仍然不是很流畅，已经跟对应大佬沟通，后续版本继续优化，可能需要大改，当前版本无法实现。
2.提交两个p3 issues,#/3993 #3994 不影响启动器正常使用
3.其他启动器功能都能正常使用无异常
综上所述，本次测试通过
