### ISSUE TITLE
[deepin 23 Beta] Incorrect icon in launcher

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#3977]
### SUMMARY | 问题概要

The launcher icon does not display the distribution's logo; something that is standard in other linux distributions.

In addition to the current icon being very ugly, and not referencing anything; the system logo needs to return to this location.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin 23 Beta (OsBuild=21238.100)
dde-dock 6.0.9.2

### PRE-REQUIREMENT | 预置条件

This information is unnecessary.

### STEPS TO REPRODUCE | 复现步骤

This information is unnecessary.

### OBSERVED RESULT | 观察到的结果

This information is unnecessary.

### EXPECTED RESULT | 期望的结果

Display deepin icon in launcher.

![image](https://user-images.githubusercontent.com/45263160/229363813-f441a086-e7e8-401b-9c0f-7a05079d7b0b.png)

### ADDITIONAL INFORMATION | 额外补充

ALL native icon packs should default deepin icon/logo as app launcher icon.

**Comment by BLumia** [comment]
> The launcher icon does not display the distribution's logo; something that is standard in other linux distributions.

I guess it's the intended behavior since there is a concept called icon theme. See the spec here: https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html

You can install and switch to another icon theme if you are not happy with the current icon theme.
