### ISSUE TITLE
[deepin 23 Beta] Storage space consumption

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#3978]
### SUMMARY | 问题概要

After completing the installation, the system is creating random temporary files, occupying storage space until the system disk is full.

![Capturar_dde-file-manager_20230402125153](https://user-images.githubusercontent.com/45263160/229364461-aac4b744-a282-4a36-b4e2-4dbb08bc0037.png)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin 23 Beta (OsBuild=21238.100)
dde-file-manager 6.0.9.4

### PRE-REQUIREMENT | 预置条件

This information is not required.

### STEPS TO REPRODUCE | 复现步骤

This information is not required.

### OBSERVED RESULT | 观察到的结果

This information is not required.

### EXPECTED RESULT | 期望的结果

It is obviously expected that the system does not randomly create temporary files that cause the disk to fill up quickly.

### ADDITIONAL INFORMATION | 额外补充

When deepin was installed, it was occupying more than 15GB of space (in the stable versions, it was close to 10GB)... After 2 days, it was already at 20GB... and no application was installed.

**Comment by BLumia** [comment]
Probably related:

- https://github.com/linuxdeepin/developer-center/issues/3932

**Comment by SuperEffie** [comment]
Thanks for your feedback~
We have submitted this issue to our developers for repair. You can refer to our issue #3934、#3932 and help us to confirm it.There are a large number of log files in the directory /var/log/.

**Comment by SuperEffie** [comment]
This issue has been fixed in the v23 beta and the dde-file-manager has been upgraded to version 6.0.18. You can help us confirm it. I close this issue at first. If you still have the same problem, you can reopen it.
Welcome to feed more issues to us,thank you!
