### ISSUE TITLE
[deepin 23 Beta] Alphabetical order in launcher

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#3979]
### SUMMARY | 问题概要

The launcher's full-screen display does not allow for automatic alphabetical ordering of icons. In the smaller laucher version, this is already available:

![Capturar_select-area_20230402112335](https://user-images.githubusercontent.com/45263160/229367346-cb0b0955-5fea-4b1b-8964-0315d67da7aa.png)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin 23 Beta (OsBuild=21238.100)
dde-launcher 6.0.8

### PRE-REQUIREMENT | 预置条件

This information is unnecessary.

### STEPS TO REPRODUCE | 复现步骤

This information is unnecessary.

### OBSERVED RESULT | 观察到的结果

This information is unnecessary.

### EXPECTED RESULT | 期望的结果

Let the full screen app launcher sort them alphabetically. The preference for this arrangement is the default, not a selectable option.

**Comment by BLumia** [comment]
Currently it's the designed behavior, thus not a bug. If you are willing to submit this as a feature request, please use the [discussion board](https://github.com/orgs/linuxdeepin/discussions) instead since we only track bugs here :)
