### ISSUE TITLE
開機時 dock 跑到了畫面之外（只發生過一次）

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#398]
![deepin _20171108205941](https://user-images.githubusercontent.com/20014762/32550409-ff517726-c4c7-11e7-8e4a-8699cc0c57da.png)

**Comment by hualet** [comment]
是已知问题，正在尝试解决。

**Comment by JulianLai** [comment]
很久沒發生，當作解決了吧
