### ISSUE TITLE
[deepin 23 Beta] Incorrect Storage Units

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#3980]
### SUMMARY | 问题概要

According to the topic https://github.com/linuxdeepin/developer-center/issues/1815 (20 Beta), some issues were resolved; but the others remain, as I quote below:

deepin Music
![Capturar_deepin-music_20230402140943](https://user-images.githubusercontent.com/45263160/229369869-8b47927b-9b53-456c-8edb-d788fae6ebfa.png)

deepin Movie
![Capturar_deepin-movie_20230402141208](https://user-images.githubusercontent.com/45263160/229369882-1a489346-3991-4cba-afa0-05c5727ad385.png)

deepin Disk Manager
![Capturar_deepin-diskmanager_20230402141135](https://user-images.githubusercontent.com/45263160/229369921-da500845-4c48-4c2c-9984-32ee38218e2a.png)

deepin File Manager
![Capturar_dde-file-manager_20230402144832](https://user-images.githubusercontent.com/45263160/229369973-58a0bd02-09e8-4882-a53d-72aa8858d72f.png)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin 23 Beta (OsBuild=21238.100)

deepin-music 6.2.15
deepin-movie 6.0.1
deepin-diskmanager 1.3.26
dde-file-manager 6.0.9.4

### PRE-REQUIREMENT | 预置条件

This information is unnecessary.

### STEPS TO REPRODUCE | 复现步骤

This information is unnecessary.

### OBSERVED RESULT | 观察到的结果

This information is unnecessary.

### EXPECTED RESULT | 期望的结果

Obviously, correctly display the units of measurement by the international standard.

**Comment by xuqi27837288** [comment]
Thank you for your feedback. We are working on this issue~

**Comment by xuqi27837288** [comment]
该问题在v23 beta 0425镜像中已修复，此issues先进行关闭处理~
