### ISSUE TITLE
[deepin 23 Beta] Decimal separator on calculator

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#3982]
### SUMMARY | 问题概要

Reiterating the previous complaint https://github.com/linuxdeepin/developer-center/issues/2406.

In Brazil, the decimal separator is a comma; however, Calculator displays another symbol as a separator.

![Capturar_deepin-calculator_20230402212534](https://user-images.githubusercontent.com/45263160/229387434-67046402-9116-414a-8eba-48b1126ac08e.png)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin 23 Beta (OsBuild=21238.100)

deepin-calculator 5.7.20

### PRE-REQUIREMENT | 预置条件

This information is unnecessary.

### STEPS TO REPRODUCE | 复现步骤

This information is unnecessary.

### OBSERVED RESULT | 观察到的结果

This information is unnecessary.

### ADDITIONAL INFORMATION | 额外补充

In green: Countries that use a comma as a decimal separator:

![image](https://user-images.githubusercontent.com/45263160/229387063-c0bb5036-8796-43f8-a956-df119b542541.png)

**Comment by BLumia** [comment]
Duplicated with https://github.com/linuxdeepin/developer-center/issues/2406, let's track the issue there :)
