### ISSUE TITLE
[deepin 23 Beta] Old Icon in Firefox

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#3984]
### SUMMARY | 问题概要

When installing Firefox from the Store, it is seen that the old Firefox icon is displayed; Also, the application name is not displayed correctly.

![Capturar_select-area_20230402214110](https://user-images.githubusercontent.com/45263160/229388477-8dc1a6c7-8873-483b-85ba-9c6dce094fff.png)

![Capturar_select-area_20230402214355](https://user-images.githubusercontent.com/45263160/229388712-e0efd2c9-a70c-46fa-a7b4-98d171423bef.png)

However, the Firefox installation itself features the updated icon pack at /opt/apps/org.mozilla.firefox-nal/files/browser/chrome/icons/default:

![Capturar_dde-file-manager_20230402214144](https://user-images.githubusercontent.com/45263160/229388525-10da9583-daff-4390-b1a3-4cd06f0827fa.png)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin 23 Beta (OsBuild=21238.100)

org.mozilla.firefox-nal 111.0.1

### PRE-REQUIREMENT | 预置条件

This information is unnecessary.

### STEPS TO REPRODUCE | 复现步骤

This information is unnecessary.

### OBSERVED RESULT | 观察到的结果

This information is unnecessary.

### EXPECTED RESULT | 期望的结果

Firefox is expected to display the icons from the installation itself, rather than the system icon pack. Also, correctly display the name "Firefox".

**Comment by BLumia** [comment]
> org.mozilla.firefox-nal 111.0.1

Is this from the official apt repo? If not, then the package provider might provide an incorrect `.desktop` file. Could you check the content of that `.desktop` file and see what's in the `Name` field?

About the icon, the one comes from the icon theme might be used. You can also check if switching to other icon theme and see if the icon issue is still there.

cc @babyfengfjx

**Comment by lxwndr** [comment]
Yes, it's the store's software; you identify it as _Firefox Quantum_. If I'm not mistaken, it's software that you repackage.

Another observation to be made, is that since version 70 (released in October 2019), Mozilla no longer uses the name "Quantum" in its browser.

![Capturar_deepin-home-appstore-client_20230403182159](https://user-images.githubusercontent.com/45263160/229662973-48eb0470-0832-4c21-9f80-4f187a3503cd.png)


> About the icon, the one comes from the icon theme might be used. You can also check if switching to other icon theme and see if the icon issue is still there.

Changing the theme does not resolve the issue.


> Is this from the official apt repo? If not, then the package provider might provide an incorrect `.desktop` file. Could you check the content of that `.desktop` file and see what's in the `Name` field?

It looks like the .desktop file is blank:

![Capturar_dde-file-manager_20230403223331](https://user-images.githubusercontent.com/45263160/229663563-4bb60a10-b9d2-48d5-94c0-c60c47e15331.png)

**Comment by BLumia** [comment]
@babyfengfjx 用户反馈，商店中安装 Firefox Quantum(EN) 时，使用的 Logo 与启动器中显示的应用名称不正确。可以尝试是否可复现，看看是不是商店里提供的包的问题以及应该哪边解决。

**Comment by babyfengfjx** [comment]
@vivianxf  可以复现看是否商店应用有问题。

**Comment by vivianxf** [comment]
@BLumia 目前应用名称和图标的问题都在v23可以复现

**Comment by BLumia** [comment]
Hi @lxwndr, is this issue already resolved? We are currently focusing on getting v23 features to be implemented so not checked those not high priority issues. If it's not fixed, please consider reopening the issue so we can still track these issues down later.

Thanks!

**Comment by lxwndr** [comment]
> Hi @lxwndr, is this issue already resolved? We are currently focusing on getting v23 features to be implemented so not checked those not high priority issues. If it's not fixed, please consider reopening the issue so we can still track these issues down later.
> 
> Thanks!

The app icon (from the Store) appears to have been resolved. However, the problem continues with the Flathub.org application (the latter, I will open a complaint on deepin Home).
