### ISSUE TITLE
[deepin 23 Beta] Password locked disk

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#3987]
### SUMMARY | 问题概要

When using a disc created by another deepin installation, an administrative password is required to access it. Even if the new installation has the same user name and password as the other system.

![Capturar_dde-file-manager_20230402112104](https://user-images.githubusercontent.com/45263160/229389584-ae9fc7c4-53fd-4fc7-a01a-dff07ef80cf7.png)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin 23 Beta (OsBuild=21238.100)

dde-file-manager 6.0.9.4

### PRE-REQUIREMENT | 预置条件

This information is unnecessary.

### STEPS TO REPRODUCE | 复现步骤

This information is unnecessary.

### OBSERVED RESULT | 观察到的结果

This information is unnecessary.

**Comment by BLumia** [comment]
Is that an NTFS partition? If so, it's normal to see that you need a password to access it.

**Comment by BLumia** [comment]
> When using a disc created by another deepin installation

This is also normal if it's not an NTFS partition, since EXT4 partition also stores user permission across installation. If that's the case, it's also not a bug.

**Comment by BLumia** [comment]
Could you check if `nautilus` (GNOME's default file manager, you can install it via `sudo apt install nautilus`) also has the same "issue"? If it also has the same "issue", then it's not a bug.

**Comment by lxwndr** [comment]
A repository error is occurring:

![Capturar_deepin-terminal_20230403224752](https://user-images.githubusercontent.com/45263160/229665844-2c9651bc-899a-462f-b247-ed9e5d43181f.png)

Can chmod resolve this permission issue?

**Comment by BLumia** [comment]
@babyfengfjx 这个问题可能需要尝试复现一下，相关的问题：

1. 本机设备上的磁盘（留意此 issue 与下面所链接的 discussion 中的描述），是否会需要额外鉴权才能进行正常挂载？
2. 如果是，自动挂载功能是否因此失效？
3. 如果是，此磁盘挂载需鉴权的问题是否在 v20 也存在？（根据反馈，v20 早期版本没有这个问题，链接见下方）

目前也有收到近似的反馈：

- https://github.com/linuxdeepin/developer-center/discussions/3974#discussioncomment-5512414

判断此 issue 和上面链接到的 issue 可能有相关性。不确定是否是预期的变更还是在版本迭代过程中遗漏了 udisks/polkit 规则所致。

**Comment by babyfengfjx** [comment]
@BLumia   确认这个现象在V20版本不存在，只有V23版本有该问题，上周讨论来看社区成员应该是不知道该变化的来由，目前是提单到文管作进一步分析。

**Comment by babyfengfjx** [comment]
@luodeepin  后续文管这边有相关信息，可以及时同步到该issue。

**Comment by BLumia** [comment]
cc @Zeno-sole 

关联：PMS-194759

**Comment by luodeepin** [comment]
文件管理器 6.0.17版本中，可以自动挂载 windows系统的分区
![截图_选择区域_20230506131133](https://user-images.githubusercontent.com/96416089/236601422-9ce9d01d-9585-4279-b8ce-21b2237d3540.png)
