### ISSUE TITLE
[deepin 23 Beta] Default keyboard error

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#3988]
### SUMMARY | 问题概要

After installing the operating system and choosing the format of the local keyboard, the system continues to behave as if it had an international keyboard (en-US, for example).

By removing the fcitx package, this whole problem is eliminated. It looks like this package has higher privileges than the user's decision/configuration.

The system is in the Brazilian local format (ABNT2), however, it displays the en-US format:

![Capturar_select-area_20220710135356](https://user-images.githubusercontent.com/45263160/229389838-8098b008-ed31-430d-89d2-1d2cfad3f4e9.png)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin 23 Beta (OsBuild=21238.100)

fcitx 4.2.9.32.38

### PRE-REQUIREMENT | 预置条件

This information is unnecessary.

### STEPS TO REPRODUCE | 复现步骤

This information is unnecessary.

### OBSERVED RESULT | 观察到的结果

This information is unnecessary.

**Comment by babyfengfjx** [comment]
@SuperEffie 请确认用户问题。

**Comment by SuperEffie** [comment]
Thanks for feedback.
Your screenshot seems to be an issue with version 20.9. We will track this issue in the v23 beta and the relevant link is https://github.com/linuxdeepin/developer-center/issues/4486.  Let's close this issue first and track it based on the above link.
