### ISSUE TITLE
sysdev第二轮集成

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#3989]
仓库地址: deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-intergration-pr-59/testing/ ./

**Comment by Zeno-sole** [comment]
包名|版本
--|--
edk2 | 2022.11-6
sshpass|1.10-0deepin
openjdk-8|8u362-ga-4deepin1
nemo-qml-plugin-dbus|1.0.0-1

**Comment by Zeno-sole** [comment]
### 更新日志

关联issues https://github.com/linuxdeepin/developer-center/issues/3955 https://github.com/linuxdeepin/developer-center/issues/3619
补充ovmf sshpass openjdk-8 libnemodbus 

测试建议： 请确认是否正在安装卸载
影响范围： 第三方应用

**Comment by Zeno-sole** [comment]
@babyfengfjx 请安排验证

**Comment by SuperEffie** [comment]
【验证结论】：测试通过，终端中可正常安装包sshpass、libnemodbus、openjdk-8-jdk、ovmf，请走下一步流程~
