### ISSUE TITLE
深度终端设置界面左侧的导航栏字体过大

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#399]
左侧文管 vs 右侧终端：

![2017-11-08-212844-366dae](https://user-images.githubusercontent.com/1006477/32551608-10dd718a-c4cc-11e7-9f46-1d1f2f756192.png)

**Comment by JulianLai** [comment]
其實是兩個都太小

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
