### ISSUE TITLE
dtk 5.6.9集成

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#3991]
仓库地址： deb [trusted=yes]  https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-intergration-pr-60/testing/ ./

**Comment by Zeno-sole** [comment]
包名|版本
--|--
dtkcommon|5.6.9
dtkcore|5.6.9
dtkgui|5.6.9
dtkwidget|5.6.9
qt5integration|5.6.9
qt5platform-plugins|5.6.9

**Comment by Zeno-sole** [comment]
@kegechen  请备注 更新说明 影响范围 测试建议等内容，备注完成后，转给 @babyfengfjx 安排测试验证

**Comment by kegechen** [comment]
1. 修改了部分调色板颜色 见： https://github.com/linuxdeepin/dtkgui/issues/142
2. bug-fix： https://github.com/linuxdeepin/dtkwidget/issues/354 https://github.com/linuxdeepin/dtkwidget/issues/358 https://github.com/linuxdeepin/dtkwidget/issues/326 https://github.com/linuxdeepin/dtkwidget/issues/325 https://github.com/linuxdeepin/dtkwidget/issues/324 https://github.com/linuxdeepin/dtkwidget/issues/361 https://github.com/linuxdeepin/developer-center/issues/3914  [部分图标缩放后模糊的问题](https://pms.uniontech.com/bug-view-185279.html)  https://github.com/linuxdeepin/dtkwidget/issues/388  https://github.com/linuxdeepin/developer-center/issues/3649 
3. feat：新增通过DConfig配置DTitleBar的功能 https://github.com/linuxdeepin/dtkwidget/issues/367  
4. feat： 应用水印 https://github.com/linuxdeepin/dtkwidget/issues/393
