### ISSUE TITLE
【deepin_V23_beta】【一般】【有空】【内测反馈】【系统】VMware虚拟机安装VM Tools后虚拟机与实体机之间不能相互复制文件及内容

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#3992]
### SUMMARY | 问题概要

必现问题

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

虚拟机镜像地址：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230309/
实体机镜像win10
VM版本:17.0.0 build-20800274

### PRE-REQUIREMENT | 预置条件

1.安装win10操作系统后，安装vm虚拟机,安装v23 alpha2 0309镜像
2.安装vm tools后重启系统

### STEPS TO REPRODUCE | 复现步骤

将实体机与虚拟机之间相互复制文件,观察是否能够复制成功    

### OBSERVED RESULT | 观察到的结果

无法相互复制文件及内容

https://user-images.githubusercontent.com/62528742/229404943-d29d266d-3a41-4ada-b37d-3ccdd7e3738b.mp4

### EXPECTED RESULT | 期望的结果

可以相互复制文件及内容

### ADDITIONAL INFORMATION | 额外补充

v20系统上可以安装vm tools后,可以正常双向复制文件及内容

**Comment by babyfengfjx** [comment]
@Zeno-sole 请帮忙分析~

**Comment by Zeno-sole** [comment]
@UTsweetyfish  上次提交的vm tools遗留问题，有空看一下

**Comment by UTsweetyfish** [comment]
1. ISO 没有预装 open-vm-tools；
2. open-vm-tools 不在stable源里，需要加 `deb https://proposed-packages.deepin.com/beige-testing/ unstable main community`；
3. open-vm-tools-desktop 缺依赖，正在解决。

**Comment by UTsweetyfish** [comment]
### PRE-REQUIREMENT | 预置条件

添加源

```
deb https://proposed-packages.deepin.com/beige-testing unstable main community dde
deb https://ci.deepin.com/repo/topics/beige/unstable unstable main community
```

`sudo apt update && sudo apt install open-vm-tools-desktop` 后重启

### 测试方法

测试文件夹共享、文件拖拽、剪切板（文字+图片+文件，内对外 外对内）

**Comment by Zeno-sole** [comment]
> open-vm-tools-desktop

@UTsweetyfish open-vm-tools-desktop的依赖补充完成后在 https://github.com/deepin-community/Repository-Integration/pull/72 提交集成申请

**Comment by UTsweetyfish** [comment]
> > open-vm-tools-desktop
> 
> @UTsweetyfish open-vm-tools-desktop的依赖补充完成后在 [deepin-community/Repository-Integration#72](https://github.com/deepin-community/Repository-Integration/pull/72) 提交集成申请

指在 # 72 那个 pr 提交申请还是仓库开个新 pr？

**Comment by Zeno-sole** [comment]
> > > open-vm-tools-desktop
> > 
> > 
> > @UTsweetyfish open-vm-tools-desktop的依赖补充完成后在 [deepin-community/Repository-Integration#72](https://github.com/deepin-community/Repository-Integration/pull/72) 提交集成申请
> 
> 指在 # 72 那个 pr 提交申请还是仓库开个新 pr？

开个新PR 参考这个#72的提交

**Comment by xuqi27837288** [comment]
稍后进行回归测试~

**Comment by babyfengfjx** [comment]
@UTsweetyfish  此问题应该还没得到解决，请继续处理。

**Comment by xuqi27837288** [comment]
该问题论坛有较多用户反馈，麻烦有空时定位看看~谢谢~

**Comment by UTsweetyfish** [comment]
ok 我简单搜了下

> The copy and paste feature requires Linux hosts and guests to run X Windows and Solaris 10 guests to run an Xorg X server and JDS/Gnome.
> https://docs.vmware.com/en/VMware-Workstation-Pro/17/com.vmware.ws.using.doc/GUID-1109A03F-3BD3-4292-AEF6-D943445519B5.html

> Note that Drag-and-Drop and Copy-and-Paste is currently not working with Wayland. Log in with an X11 session instead.
> https://kb.vmware.com/s/article/74671

> Copy from the guest OS and paste into the host OS works as expected.
> Copy from the host OS and paste into the guest OS works only for some X11 (running under xwayland) applications, and does not work at all for native wayland applications.
> https://gitlab.gnome.org/GNOME/mutter/-/issues/1265

不太确定是不是这个原因

**Comment by UTsweetyfish** [comment]
可能需要 wayland 和桌面的大佬来看下（

**Comment by Zeno-sole** [comment]
open-vm-tools使用 x-special/nautilus-clipboard copy 机制，目前怀疑dde-clipboard 未对该行为做处理

**Comment by UTsweetyfish** [comment]
![图片](https://github.com/linuxdeepin/developer-center/assets/124018391/c8b4ee0b-1766-4aa3-9e9c-d904edf8b680)

**Comment by UTsweetyfish** [comment]
> open-vm-tools使用 x-special/nautilus-clipboard copy 机制，目前怀疑dde-clipboard 未对该行为做处理

强制使用 x-special/gnome-copied-files 还是不行

**Comment by xuqi27837288** [comment]
https://pms.uniontech.com/bug-view-256725.html

**Comment by UTsweetyfish** [comment]
v23 rc 环境下，使用 xclip 命令

x-special/gnome-copied-files 与 text/uri-list 均存在

对应文件存在

应为文管问题。

![vm](https://github.com/linuxdeepin/developer-center/assets/124018391/7695a8ec-6add-4766-82b3-ce8af0c32bef)

**Comment by XMuli** [comment]
**ENV:**
Win10 22H2 + VMware17 + Deepin v23 RC

**解决方案如下，两个都要安装即可，即可互相拷贝和拖曳文件**  @UTsweetyfish 
```bash
sudo apt install open-vm-tools
sudo apt install open-vm-tools-desktop
```
<img src="https://github.com/linuxdeepin/developer-center/assets/33887845/a6614b06-34f7-4d85-8fc5-b097f279ee81" width="80%"/>

ps: 直接安装 GUI vmware_tools 是不可以的双向拷贝的；得用开源得这种

**Comment by UTsweetyfish** [comment]
> **ENV:** Win10 22H2 + VMware17 + Deepin v23 RC
> 
> **解决方案如下，两个都要安装即可，即可互相拷贝和拖曳文件** @UTsweetyfish
> 
> ```shell
> sudo apt install open-vm-tools
> sudo apt install open-vm-tools-desktop
> ```

hi @XMuli ，我这里拖拽是可以正常工作的，但是右键复制、右键粘贴是无法工作的。方便证实一下吗？

**Comment by UTsweetyfish** [comment]
我这里基于 VMware 17.5 测试了几个 matrix

|host|guest|result|
|--|--|--|
|deepin v23 (kernel 6.1)|OpenSUSE 15.5 GNOME|:heavy_check_mark:|
|deepin v23 (kernel 6.1)|Arch Linux 2024.05.30 KDE|:heavy_check_mark:|
|deepin v23 (kernel 6.1)|deepin v23|:x:|
|deepin v23 (kernel 6.1)|Ubuntu 24.04|:x:|
|deepin v23 (kernel 6.1)|Arch Linux 2024.05.30 GNOME|:x:|
|Debian 12 (GNOME)|Ubuntu 24.04|:x:|
|UOS v20|Ubuntu 24.04|:x:|
|Ubuntu 20.04|Ubuntu 20.04|:heavy_check_mark:|
|Ubuntu 20.04|Ubuntu 24.04|:x:|

已知信息：deepin v23 rc 的文管处理了 x-special/gnome-copied-files

目前得出的结论：
1.  open-vm-tools 新版本和新版本 GNOME（更详细的，nautiuls）不太兼容。
2. DDE 没有处理 `x-special/nautilus-clipboard` 的逻辑

**Comment by smallaeroplane** [comment]
我也是遇到了一样的问题 头一次用deepin
