### ISSUE TITLE
[V23] 蓝牙模块不可用 

### ISSUE THREAD

**Issue by sany98215** [linuxdeepin/developer-center#3996]
### SUMMARY | 问题概要

系统安装后，蓝牙模块不可用，但设备管理显示驱动正常

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

操作系统版本: V23内测版
电脑：HP 14s青春版

### PRE-REQUIREMENT | 预置条件

新安装，系统提示驱动：Realtek Bluetooth 4.2 Adapter

### STEPS TO REPRODUCE | 复现步骤

新安装

**Comment by sany98215** [comment]
这个问题有重复吗，怎么没人理？

**Comment by Decodetalkers** [comment]
bluetoothctl 试试呢

**Comment by BLumia** [comment]
> 这个问题有重复吗，怎么没人理？

Troubleshooting 类问题其实不建议先开在 issue 里，可以用 discussion 板块反馈。因为 issue 一般只会留确认为 bug 的问题或者确认要做的任务，而 troubleshooting 类的问题很可能不是 bug。

排查过程按 @Decodetalkers  给出的回复看下吧，可能需要配合 rfkill 的结果以及别的发行版关于蓝牙的 wiki 一起看。

**Comment by sany98215** [comment]
[bluetooth]# show
No default controller available
[bluetooth]# list
[bluetooth]# devices
No default controller available

从结果看是没有驱动，我这个好像就是8821ce带的蓝牙驱动，好像用的挺多的

**Comment by sany98215** [comment]
如果有可用驱动源码，我编译一下试试也行

**Comment by sany98215** [comment]
> bluetoothctl 试试呢，我想就是驱动没有的原因

再给点信息呗，让我能在正式发版先先能正常用蓝牙

**Comment by Zeno-sole** [comment]
> [bluetooth]# show No default controller available [bluetooth]# list [bluetooth]# devices No default controller available
> 
> 从结果看是没有驱动，我这个好像就是8821ce带的蓝牙驱动，好像用的挺多的

建议是提交issues到Realtek 让他们提交驱动代码到内核，我们们会跟进集成上游的内核版本

**Comment by sany98215** [comment]
> > [bluetooth]# show No default controller available [bluetooth]# list [bluetooth]# devices No default controller available
> > 从结果看是没有驱动，我这个好像就是8821ce带的蓝牙驱动，好像用的挺多的
> 
> 建议是提交issues到Realtek 让他们提交驱动代码到内核，我们们会跟进集成上游的内核版本

我已经临时解决了，目前临时方法如下，供参考。这个问题也希望官方正常考虑下怎么正常集成，我想懂的人，应该不是特别麻烦。
```
git clone https://github.com/radxa/rtkbt
cd rtkbt
cd usb # 因为驱动是usb设备的
sudo make install
cd ..
sudo cp rtkbt-firmware/lib/firmware/rtl8821* /lib/firmware/
reboot
```

**Comment by Zeno-sole** [comment]
> > > [bluetooth]# show No default controller available [bluetooth]# list [bluetooth]# devices No default controller available
> > > 从结果看是没有驱动，我这个好像就是8821ce带的蓝牙驱动，好像用的挺多的
> > 
> > 
> > 建议是提交issues到Realtek 让他们提交驱动代码到内核，我们们会跟进集成上游的内核版本
> 
> 我已经临时解决了，目前临时方法如下，供参考。这个问题也希望官方正常考虑下怎么正常集成，我想懂的人，应该不是特别麻烦。
> 
> ```
> git clone https://github.com/radxa/rtkbt
> cd rtkbt
> cd usb # 因为驱动是usb设备的
> sudo make install
> cd ..
> sudo cp rtkbt-firmware/lib/firmware/rtl8821* /lib/firmware/
> reboot
> ```

最好的解决方案是集成到上游内核中，不然第三方维护的可能过几个版本就接口变动无法使用了
