### ISSUE TITLE
基于 git tag 的 changelog 实时通知机制

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/developer-center#40]
首先实时获取最新的 git tag 版本号, 可以通过 gerrit 下 `Gerrit Event` 插件实现, 具体需要 @choldrim 研究下
   http://stackoverflow.com/questions/18618809/jenkins-builds-on-tag-pushes-via-gerrit-trigger-plugin

然后根据 git tag 生成 changelog, 这里需要实现一个简单的脚本工具.

最后把 changelog 分发到邮件列表和其他通知途径(尽量通过工具自动实现), 同时有利于 @cxbii 整理升级日志.

 @linuxdeepin/assistant-team @linuxdeepin/system-team @snyh

**Comment by snyh** [comment]
这个事情 之前 @electricface 做过.

**Comment by fasheng** [comment]
记得当时专门生成了 web 页面, 如果是开源项目, 可以直接使用 github compare view:
https://github.com/blog/612-introducing-github-compare-view
https://github.com/linuxdeepin/dde-daemon/compare/3.0.8...3.0.9

**Comment by snyh** [comment]
恩  这个效果不错  而且可以自动生成.     昨天刚在github找这个功能 方便QA测试. 
https://github.com/linuxdeepin/lastore-daemon/compare/0.9.16...0.9.17

**Comment by choldrim** [comment]
>首先实时获取最新的 git tag 版本号, 可以通过 gerrit 下 Gerrit Event 插件实现, 具体需要 @choldrim 研究下
>http://stackoverflow.com/questions/18618809/jenkins-builds-on-tag-pushes-via-gerrit-trigger-plugin
>然后根据 git tag 生成 changelog, 这里需要实现一个简单的脚本工具.
@fasheng 
tag push trigger 已经在使用的了（以前用于DTask推送tag自动生成和更新server的可下载插件版本）
配置也很简单，监听的path设置成 refs/tags/* 即可，如图
![image](https://cloud.githubusercontent.com/assets/6734555/13277050/84a35240-db00-11e5-92a2-c13e245a4045.png)

**Comment by fasheng** [comment]
@choldrim 
这个也可以, 是 jenkin 的插件, 不过貌似要对每个项目都配置一遍...
先来个简单的需求, 只要有新 tag, 就给我发送邮件 ;)

**Comment by choldrim** [comment]
（sorry，没看到github消息）
我测试了一下，jenkins的gerrit trigger插件可以统配到所有项目，并且可以发送邮件的  ;)
![image](https://cloud.githubusercontent.com/assets/6734555/13341281/3f9b6dfe-dc72-11e5-8c10-e426f338139e.png)

**Comment by fasheng** [comment]
:+1:

**Comment by fasheng** [comment]
https://github.com/linuxdeepin/team-robots/tree/master/jenkins-tags-monitor
完成
