### ISSUE TITLE
deepin-home 1.0.20 集成

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#4001]
仓库地址：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-intergration-pr-62/testing/ ./

**Comment by Zeno-sole** [comment]
包名 | 版本 
-- | --
deepin-home | 1.0.20

**Comment by Zeno-sole** [comment]
@myml  请备注 更新说明 影响范围 测试建议等内容，备注完成后，转给 @babyfengfjx 安排测试验证

**Comment by myml** [comment]
Bug-fix：
- https://github.com/linuxdeepin/developer-center/issues/3800
- https://github.com/linuxdeepin/developer-center/issues/3798
- https://github.com/linuxdeepin/developer-center/issues/3801
- https://github.com/linuxdeepin/developer-center/issues/3605

Feat：
- https://github.com/linuxdeepin/developer-center/issues/3799

**Comment by xuqi27837288** [comment]
添加仓库升级后，以上问题单都已验证通过，相关问题均已修复~
