### ISSUE TITLE
快捷面板的电池插件图标和dock上的图标不统一

### ISSUE THREAD

**Issue by ComixHe** [linuxdeepin/developer-center#4004]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

dde-dock <= 6.0.10

### STEPS TO REPRODUCE | 复现步骤

1. 笔记本接入电源
2. 在控制中心打开电池插件
3. 打开快捷面板

### OBSERVED RESULT | 观察到的结果

![issue](https://user-images.githubusercontent.com/54773474/229695265-e82dc5dc-4a62-4a73-acf0-ebb6946eba8b.png)

### EXPECTED RESULT | 期望的结果

图标显示一致，正确响应电池状态变化

**Comment by luodeepin** [comment]
【验证环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Alpha2/deepin-desktop-community-23-Alpha2-amd64.iso

仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
     deb https://community-packages.deepin.com/beige/ beige main commercial community
包版本：dde-dock       6.0.12  
       dde-control-center 6.0.11-1
内核：Linux v23-PC 6.1.11-amd64-desktop-hwe #23.01.00.01 SMP PREEMPT_DYNAMIC Mon Feb 27 17:25:36 CST 2023 x86_64 GNU/Linux
【验证步骤】：问题单中描述的步骤

【验证结果】：通过
![截图_dde-desktop_20230418154151](https://user-images.githubusercontent.com/96416089/232707574-f282cd6c-2e2c-429e-81be-e9e9b1b54e46.png)
