### ISSUE TITLE
add dde-session-ui 6.0.8, dde-clipboard 6.0.3

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#4006]
仓库地址： deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-intergration-pr-65/testing/ ./

**Comment by Zeno-sole** [comment]
包名|版本
--|--
dde-clipboard|6.0.3+rb1
dde-session-ui|6.0.8

**Comment by Zeno-sole** [comment]
dtk 5.6.9 已合入ci/testing 仓库 @BLumia  请备注 更新说明 影响范围 测试建议等内容，备注完成后，转给 @babyfengfjx 安排测试验证

**Comment by BLumia** [comment]
## 更新说明

### dde-session-ui

- 修复 dde-osd 圆角显示异常的问题
  - https://github.com/linuxdeepin/developer-center/issues/3718
  - https://github.com/linuxdeepin/developer-center/issues/3602
- 支持 `XDG_CURRENT_DESKTOP` 值为 DDE 时的对应情况（在 dde-session 更新后正常即可，无 bug 对应）
- 修复玲珑应用点击通知时无法唤起邮箱应用的问题 https://github.com/linuxdeepin/developer-center/issues/3657
- 修复传入空 app name 可能导致 osd 应用崩溃的问题 https://github.com/linuxdeepin/dde-session-ui/pull/331

### dde-clipboard

仅进行了 reuse 开源合规并更新了版本号，无行为变化

## 影响范围

此集成仅会影响 dde-session-ui 中提供顶部通知与抬头显示功能的组件，不影响 DDE 的其它组件。

## 测试建议

更新说明中已附带相关 Issue 链接，可按照对应 Issue 查看详情。

测试方式为通过测试仓库获取并安装更新。可靠起见建议在更新后注销并重新登录一次，然后再开始测试。

## 其他信息

暂无
