### ISSUE TITLE
add deepin-system-monitor 6.0.6

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#4007]
仓库地址： deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-intergration-pr-64/testing/ ./

**Comment by Zeno-sole** [comment]
### 更新日志

关联issues https://github.com/linuxdeepin/developer-center/issues/3747
相关PR  fix: 文管在系统监视器中进程中图标显示错误 https://github.com/linuxdeepin/deepin-system-monitor/commit/5178c6f54cf8c72e986d290dc35f8e76b5578cb7
fix: 部分机型cpu的modelname为空时cpu信息错误 https://github.com/linuxdeepin/deepin-system-monitor/commit/0fd390e72e5020c77f324e2e27140f6959eda131
fix: 开启浏览器并在系统监视器中选择查看命令所在位置时跳转目录错误 https://github.com/linuxdeepin/deepin-system-monitor/commit/70d34ba8125628e86dcab22456285d55d0e5f47a

**测试建议**
验证相关PR issues提到的问题是否修复 点击跳转到PR链接查看PMS单地址

**影响范围**
系统监视器的图标、信息获取

**Comment by babyfengfjx** [comment]
@vivianxf  请在集成仓库回归验证。

**Comment by vivianxf** [comment]
【测试结论】：测试通过，请走下一步流程～
仓库升级正常，包升级正常
1.以上comment中issue 747，bug183667验证通过，bug160309在社区版不涉及，不影响使用
2.系统监视器功能正常使用无异常
综上所述，本次测试通过
