### ISSUE TITLE
登出重新登入、使用 xset dpms force off 關閉螢幕、切換 refresh rate 後，聲音會跳回 HDMI 輸出

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#401]
每切換一次 refresh rate 就要手動把他調回來
可以讓他不要擅自切換輸出裝置嗎？

原本
![deepin _20171110212537](https://user-images.githubusercontent.com/20014762/32660420-c08a525a-c65d-11e7-82a6-4ab1637b073b.png)
執行 `xset dpms force off` 後
![deepin _20171110212548](https://user-images.githubusercontent.com/20014762/32660434-cebf14d2-c65d-11e7-9dea-ba86829f12e8.png)

切換 refresh rate 播放影片的 gif
![deepin-screen-recorder_desktop_20171111003556](https://user-images.githubusercontent.com/20014762/32668428-7cb9f2cc-c678-11e7-9c9c-874809080ec2.gif)

**Comment by JulianLai** [comment]
貌似已修復

**Comment by jouyouyun** [comment]
恩，是的
