### ISSUE TITLE
add deepin-desktop-theme and deepin-icon-theme

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#4010]
仓库地址： deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-intergration-pr-69/testing/ ./

**Comment by Zeno-sole** [comment]
包名|版本
--|--
deepin-desktop-theme|1.0.6
deepin-icon-theme|2023.04.03

**Comment by Zeno-sole** [comment]
@kegechen 请备注 更新说明 影响范围 测试建议等内容，备注完成后，转给 @babyfengfjx 安排测试验证

**Comment by babyfengfjx** [comment]
@SuperEffie  请开展集成验证。

**Comment by Zeno-sole** [comment]
@SuperEffie  issue：https://github.com/linuxdeepin/developer-center/issues/4061 已经修复，请重新验证  若是在旧环境上验证需要 reinstall方式进行

**Comment by SuperEffie** [comment]
【验证结论】：测试不通过，建议修复issue #4077后推送
issue #4061已修复;
高分屏机器下，控制中心-个性化-主题，除了bloom、vintage外的主题，图标显示异常，关联issue #4077
