### ISSUE TITLE
Integrate dde-app-services to 1.0.20

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#4011]
仓库地址： deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-intergration-pr-61/testing/ ./

**Comment by Zeno-sole** [comment]
包名|版本
--|--
dde-app-services|0.0.23

**Comment by Zeno-sole** [comment]
### 更新内容

- 移除root用户启动 https://github.com/linuxdeepin/dde-app-services/pull/28 https://github.com/linuxdeepin/dde-app-services/pull/34
- 减少设置配置后同步到磁盘的时间，由30s每次改为3秒 https://github.com/linuxdeepin/dde-app-services/pull/41

### 影响范围

- dde-dconfig-editor 功能正常使用
- dde-dconfig 功能正常使用
- 各使用到配置策略的应用能正常使用

### 测试用例
- 见 https://github.com/linuxdeepin/dde-app-services/pull/28 备注

**Comment by Zeno-sole** [comment]
@18202781743

**Comment by babyfengfjx** [comment]
@SuperEffie 请梳理该集成相关的内容，弄清楚合入的具体内容及相关影响，并开展集成验证。

**Comment by SuperEffie** [comment]
未检测到待更新的包

**Comment by Zeno-sole** [comment]
仓库版本为 1.0.19.1, 请更新github上的tag @18202781743

**Comment by 18202781743** [comment]
重新集成 1.0.20 @Zeno-sole

**Comment by Zeno-sole** [comment]
@SuperEffie  已经更新版本 请重新验证

**Comment by SuperEffie** [comment]
【测试结论】：验证通过，请走下一步流程
开发者工具dde-dconfig-daemon和dde-dconfig-editor，正常下载、启用，且在dde-dconfig-editor中设置参数正常生效。
关机时长正常，关机10次时长均低于20s
