### ISSUE TITLE
修复窗口圆角调整未实时生效问题

### ISSUE THREAD

**Issue by beier11** [linuxdeepin/developer-center#4014]
### SUMMARY | 问题概要

【1060】【5.8.55】【UI】更多菜单圆角没有跟随系统变化
菜单圆角只是没有随设置动态变化
关闭应用重新打开后，菜单的圆角跟配置的是一致的
![image](https://user-images.githubusercontent.com/130050242/230343284-092b8f27-c867-481f-a612-cc285e6b3d95.png)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

dde-qt5integration	5.6.6-1

### PRE-REQUIREMENT | 预置条件

调节控制中心窗口圆角大小

### STEPS TO REPRODUCE | 复现步骤

调节控制中心窗口圆角大小
![image](https://user-images.githubusercontent.com/130050242/230343686-7ccd1b8a-839a-48a1-8da4-bfa1ba1073e5.png)

### OBSERVED RESULT | 观察到的结果

未实时生效 
重启应用可生效

### EXPECTED RESULT | 期望的结果

圆角设置实时生效

### ADDITIONAL INFORMATION | 额外补充
https://pms.uniontech.com/bug-view-194633.html

应该是菜单只会在第一次显示时才会去设置圆角。这个菜单是dtk提供的（关闭后并不会销毁）

**Comment by FeiWang1119** [comment]
发现窗管对菜单圆角进行了处理，移走dtk 插件之后还能发现圆角。
