### ISSUE TITLE
图形图像组玲珑应用集成

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#4018]
仓库地址： ll-cli repo modify http://10.0.36.228:9001 --name develop-snipe

**Comment by Zeno-sole** [comment]
包名|版本
--|--
org.deepin.manual|6.0.5
org.deepin.draw|6.0.5
org.deepin.album|6.0.2
org.deepin.image.viewer|6.0.1

**Comment by Zeno-sole** [comment]
[附件.zip](https://github.com/linuxdeepin/developer-center/files/11175709/default.zip)
详情参见附件

**Comment by babyfengfjx** [comment]
@luodeepin  请开展集成验证。

**Comment by luodeepin** [comment]
验证通过
申请单中存在根因非子应用的BUG,由于本次更新是手动更新，之后需要关注商店更新的情况
