### ISSUE TITLE
deepin v23 beta deepin-installer 6.0.19

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#4025]
镜像地址： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230407/

**Comment by Zeno-sole** [comment]
仓库地址： deb  [trusted=yes] https://aptly.uniontech.com/pkg/beige-v2/release-candidate/ZGVlcGluLWluc3RhbGxlcumbhuaIkDIwMjMtMDQtMDcgMTU6MjA6NDc/  unstable main

**Comment by Zeno-sole** [comment]
更新日志：
  * feat: 解决“OEM配置自动安装并且设置中文语言后，安装界面部分英文文案未汉化”问题(Bug: 173803)
  * feat: 解决“虚拟机的盘安装页面点击18GB的USB硬盘提示文案不正确”问题(Bug: 175437)
  * feat: 解决“选择时区界面的地图应该换成无国界版本，与设计图保持一致”问题(Bug: 173749)
  * feat: 解决“自定义安装页面编辑swap分区时挂载点显示不正确”问题(Bug: 175275)
  * feat: 解决“全盘加密的重要提示语建议改成醒目的颜色”问题(Bug: 173803)
  * feat: 解决“全盘安装有5个以上的磁盘时，第二排磁盘图标显示不全”问题(Bug: 175679)
  * feat: 解决“创建lvm卷组名可以输入超过20位字符的名称，与提示文案不符”问题(Bug: 175653)
  * feat: 解决“所选分区大小不满足最小系统安装空间的提示文案缺少单位”问题(Bug: 175445)
  * feat: 优化时区地图显示超出范围问题(Task: 134521)
  * fix: 解决“自定义和高级安装界面，根分区前面空闲空间的时候不能装系统”问题(Bug: 221097)
  * feat: 优化安装器三显示器支持场景(Task: 134521)
  * fix: 解决“表格中列与列之间的间距过挤”问题(Bug: 170417)
  * feat: 应用TPM加密全盘加密秘钥功能，下一轮专业版提测时，新增日志，用于判断是不是TPM加解密出现异常(Task: 223877)
  * fix: 修复自定义安装efi引导时，删除efi分区导致创建不了efi分区的问题(Bug: 177397)
  * feat: 优化V23模糊窗体(Task: 213101)
  * feat: 界面多语言和字体大小适配(Task: 226201)
  * feat: 完成“grub黑背景问题”任务(Task: 218799)
  * feat: 处理自绘列表界面的透明模糊效果(Task: 213101)
  * feat: 处理创建用户选择用户图标对话框模糊透明效果(Task: 213101)
  * feat: 处理准备安装界面和插件配置界面的透明模糊效果(Task: 213101)
  * feat: 统一设置透明模糊值(Task: 213101)
  * feat: 优化窗体重叠显示的问题(Task: 213101)
  * feat: 处理live系统下启动新版效果界面黑屏的问题(Task: 213101)
  * feat: 处理创建用户输入栏过透的问题及小屏滚动背景变白的问题(Task: 213101)
  * feat: 处理高级创建lvm列表选中item变白的问题(Task: 213101)
  * feat: 处理协议窗体滚动条区域有留白的问题(Task: 213101)
  * fix: 修复版本标签不显示问题(Task: 134521)
  * feat: 修复部分已知问题(Task: 213101)
  * fix: 修复版本标签显示遮挡问题(Task: 134521)
  * feat: 修复安装进度界面背景不够透明模糊，泛白的问题(Task: 213101)
  * feat: 安装器6.0.19版本提测(Task: 232137)
  * feat: 优化准备安装界面设置不使用初始化备份无效问题(Task: 233283)
  * feat: 优化安装器分区挂载方式，按照目录浅度挂载分区(Task: 233283)
  * feat: 优化全盘加密安装时挂载点异常问题(Task: 233283)
  * feat: 处理字段不存在时，未格式化问题(Task: 236603)
  * fix: 解决mips上校验镜像失败(Task: 183663)
  * feat: 安装器磁盘单位调整-全盘安装和手动安装(Task: 244447)
  * feat:  新增nvidia驱动安装支持 https://github.com/linuxdeepin/developer-center/issues/3943

**影响范围：** 
镜像安装

**Comment by babyfengfjx** [comment]
@xuqi27837288 请下周开展安装器集成测试，重点关注之前用户提的问题是否得到解决。
