### ISSUE TITLE
請問深度檔案的 access time 和 modify time 差別在哪邊呢？

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#403]
我讀取了檔案，但 access time 並沒有變化，除非我存檔
![deepin-screen-recorder_desktop_20171112085104](https://user-images.githubusercontent.com/20014762/32695551-fd3b3df8-c799-11e7-9bf0-7719d4502243.gif)

**Comment by dragondjf** [comment]
access time是文文件最后一次被读取的时间；
modify time是文本本身的内容发生了变化；

 access time没有变化，应该是文件管理器的一个bug；

**Comment by felixonmars** [comment]
现在为磁盘寿命和性能考虑，ext4 等文件系统默认挂载为 relatime，不会在每次读取后更新 atime，而只会在修改后或一段时间后（默认一天）。
