### ISSUE TITLE
[v23] 每次登陆都需要选择特效模式

### ISSUE THREAD

**Issue by sany98215** [linuxdeepin/developer-center#4031]
### SUMMARY | 问题概要

每次登陆都需要选择特效模式，一旦不选择，窗口无法最大化

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

版本：deepinv23 alpha 内测版本

### PRE-REQUIREMENT | 预置条件

系统登陆

### STEPS TO REPRODUCE | 复现步骤

1. 登陆，提示选择特效模式或手工模式，选择特效。
2. 进入系统正常。
3. 下次登陆，仍然提示选择特效模式，不选择。
4. 系统进入后窗口无法最大化等等。

### OBSERVED RESULT | 观察到的结果

同上

### EXPECTED RESULT | 期望的结果

1. 只选择一次模式，自动保存

**Comment by waittingsummer** [comment]
亲，由于V23不稳定，这边建议您优先使用V20呢

**Comment by Decodetalkers** [comment]
看起来似乎是窗管炸掉了。

**Comment by sany98215** [comment]
> 亲，由于V23不稳定，这边建议您优先使用V20呢

哪个系统都一样，都是各取所需，都是一回事。。。主要是小问题有解法就好。。。

**Comment by sany98215** [comment]
> 看起来似乎是窗管炸掉了。

我这里的确dde-docker频繁杀掉，拉起,不稳定，我看有bug,没有提。为了避免使用，我都是shell启动应用，不走正常管理器

**Comment by BLumia** [comment]
alpha2 后随内测更新到最新的版本？目前没有观察到这种现象，不然这应该是会作为紧急问题处理的。

> 系统进入后窗口无法最大化等等。

这个描述应该是窗管炸了。手动启窗管起得来吗？还是说手动切换一下特效模式就正常了？

如果是段错误的话，可以提供下你目前的窗管版本号和段错误的 stacktrace 吗？

cc @justforlxz 看看有没有什么信息是你需要的

**Comment by sany98215** [comment]
> alpha2 后随内测更新到最新的版本？目前没有观察到这种现象，不然这应该是会作为紧急问题处理的。
> 
> > 系统进入后窗口无法最大化等等。
> 
> 这个描述应该是窗管炸了。手动启窗管起得来吗？还是说手动切换一下特效模式就正常了？
> 
> 如果是段错误的话，可以提供下你目前的窗管版本号和段错误的 stacktrace 吗？
> 
> cc @justforlxz 看看有没有什么信息是你需要的

是alpha2 的内测最新版本了。 我现在每次登陆如果没有选择模式，进入后不正常，设置->自定义-》桌面，特效点不了。

必须注销登陆重新选择才可以。

**Comment by sany98215** [comment]
@BLumia 我系统里没有coredump命令

**Comment by BLumia** [comment]
> 我系统里没有coredump命令

请参阅：[Coredump工具使用与日志导出](https://wiki.deepin.org/Coredump%E5%B7%A5%E5%85%B7%E4%BD%BF%E7%94%A8%E4%B8%8E%E6%97%A5%E5%BF%97%E5%AF%BC%E5%87%BA)

**Comment by sany98215** [comment]
@BLumia @justforlxz 我找到复现的方法，如果/home目录不使用独立分区，进入系统就不会提示，可以正常使用。如果将/home使用独立分区时，弹出提示在使用虚拟机，但实际上我并未使用虚拟机，应该是程序判断错误。期待修复

**Comment by BLumia** [comment]
> 如果/home目录不使用独立分区，进入系统就不会提示，可以正常使用。如果将/home使用独立分区时，弹出提示在使用虚拟机，但实际上我并未使用虚拟机，应该是程序判断错误。

@babyfengfjx 可以看下按上面这个描述方式是否可以复现“每次登陆都需要选择特效模式”的问题。可以的话指派给我。

**Comment by sany98215** [comment]
@babyfengfjx 这个问题我觉得和我电脑频繁卡死有一定关系，期待尽快验证解决

**Comment by babyfengfjx** [comment]
@xuqi27837288  请

> > 如果/home目录不使用独立分区，进入系统就不会提示，可以正常使用。如果将/home使用独立分区时，弹出提示在使用虚拟机，但实际上我并未使用虚拟机，应该是程序判断错误。
> 
@xuqi27837288  请按照该方式安装后，尝试复现该问题。

**Comment by sany98215** [comment]
补充一下在X11模式下，会出现这个问题，在Wayland下就不会出现问题

**Comment by xuqi27837288** [comment]
v23 beta版本暂未复现到此问题,该issues先做关闭处理~后续会关注如有此问题再反馈优化~
