### ISSUE TITLE
【deepin_V23_beta】【一般】【有空】【论坛反馈】【社区论坛】将语言设置为 繁体中文时,社区论坛图标显示为简体中文

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#4032]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息
论坛链接：https://bbs.deepin.org/zh/post/254814?offset=0&postId=1448979
镜像： https://cdimage.uniontech.com/community/releases/23-Alpha2/deepin-desktop-community-23-Alpha2-amd64.iso
仓库： deb https://proposed-packages.deepin.com/beige-testing/  unstable dde main commercial community
            deb https://community-packages.deepin.com/beige/ beige main commercial community
内核： Linux test23-PC 6.1.11-amd64-desktop-hwe #23.01.00.01 SMP PREEMPT_DYNAMIC Mon Feb 27 17:25:36 CST 2023 x86_64 GNU/Linux

### PRE-REQUIREMENT | 预置条件

1. 系统语言为 繁体中文
2. 启动器 和 桌面存在社区论坛图标

### STEPS TO REPRODUCE | 复现步骤

1. 查看启动器中的社区论坛语言显示
2. 查看桌面上社区论坛语言显示

### OBSERVED RESULT | 观察到的结果

1. 启动器中的 社区论坛 语言为 简体中文
2. 桌面上的 社区论坛图标语言为 简体中文
![社区论坛](https://user-images.githubusercontent.com/96416089/230815655-dd12d4e3-1140-4778-972a-98586bce7c03.png)

### EXPECTED RESULT | 期望的结果

1. 启动器中的 社区论坛 语言为 繁体中文
2. 桌面上的 社区论坛图标语言为 繁体中文

**Comment by babyfengfjx** [comment]
@myml  帮忙看下是否是论坛这边的这个文件链接需要适配。

**Comment by BLumia** [comment]
> 是否是论坛这边的这个文件链接需要适配。

应该是对应的 .desktop 文件里要提供对应的本地化文案

**Comment by zccrs** [comment]
深度之家中已经有了，这里没必要继续留着。放个“深度之家”的图标

**Comment by Zeno-sole** [comment]
已经移除deepin-forum的预装

**Comment by myml** [comment]
在 https://github.com/linuxdeepin/deepin-home/pull/40 新增了桌面图标安装

**Comment by luodeepin** [comment]
【验证环境】：
镜像： https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230417/deepin-23-beige-amd64-20230417-235543.iso
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
     deb https://community-packages.deepin.com/beige/ beige main commercial community

包版本： deepin-home    1.0.21

内核： Linux v23-PC 6.1.11-amd64-desktop-hwe #23.01.00.01 SMP PREEMPT_DYNAMIC Mon Feb 27 17:25:36 CST 2023 x86_64 GNU/Linux

【验证步骤】：问题单中描述的步骤

【验证结果】：  测试通过
![截圖_dde-desktop_20230418103115](https://user-images.githubusercontent.com/96416089/232655120-0a30f840-69a2-4004-ad54-184467490c0a.png)

**Comment by luodeepin** [comment]
已验证通过
