### ISSUE TITLE
深度文官索引文件磁盘占用超大(12G)，dde-file-manager/index

### ISSUE THREAD

**Issue by pmzgit** [linuxdeepin/developer-center#4034]
### SUMMARY | 问题概要

# 查看制定目录下的目录和文件空间占用排名
du -Sh /home | sort -rh | head -n10
![image](https://user-images.githubusercontent.com/11833302/230824444-fe7475d5-86b3-4de9-b713-f5bd650a8b54.png)

我最近频繁删除（两块硬盘，系统盘是ssd，另外一块是机械，删除的机械上的文件）大的文件夹来着，也清空过回收站

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

升级到当前最新v20.8，并加入内测
内核5.18.x-hwe
filesystem: btrfs
linuxdeepin :ssd 
另外一块是机械，删除的机械上的文件

### PRE-REQUIREMENT | 预置条件

`v20.8 
sudo apt update sudo apt full-upgrade`

### STEPS TO REPRODUCE | 复现步骤

1\最近因打算清理空间，删除了很多机械盘上的文件或文件夹

# 查看制定目录下的目录和文件空间占用排名
`du -Sh /home | sort -rh | head -n10`

### OBSERVED RESULT | 观察到的结果

![image](https://user-images.githubusercontent.com/11833302/230824444-fe7475d5-86b3-4de9-b713-f5bd650a8b54.png)

### EXPECTED RESULT | 期望的结果

dde-file-manager/index 
这个文件是否可以删除？以释放磁盘空间

**Comment by babyfengfjx** [comment]
这个文件可以删除，是因为开启了全文检索功能，这个是生成的索引文件。
![企业微信截图_16811058879314](https://user-images.githubusercontent.com/24642999/230835690-4d8110b5-5e41-48f4-8813-f30dadb9ba88.png)

**Comment by babyfengfjx** [comment]
此功能开启后，如果文件较多，时间久了确实会产生较大文件，这个可以手动删除，开启此功能后，可以提供文本文件内容被搜索到的功能，此issue我们就先作关闭处理了，如后续有其他相关问题也可以随时提交issue。
