### ISSUE TITLE
多媒体键盘问题

### ISSUE THREAD

**Issue by stoforest** [linuxdeepin/developer-center#4036]
### SUMMARY | 问题概要

播放音乐时按键盘的暂停键可以正常暂停但是无法继续播放。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin 20.9
deepin 20.8

### STEPS TO REPRODUCE | 复现步骤

使用多媒体键盘

### OBSERVED RESULT | 观察到的结果

暂停无法恢复

### EXPECTED RESULT | 期望的结果

再按一次恢复播放

**Comment by babyfengfjx** [comment]
@luodeepin  请复现跟进该问题。

**Comment by stoforest** [comment]
可能是在长时间休眠以后唤醒会出现，开机是正常的。

**Comment by luodeepin** [comment]
【验证环境】：
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230426/deepin-23-beige-amd64-20230426-101953.iso
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/stable/ beige main community commercial
deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial

内核：Linux v23-PC 6.1.11-amd64-desktop-hwe #23.01.00.10
【验证步骤】：问题单中描述的步骤

【验证结果】：通过
![录屏_选择区域_20230428101702](https://user-images.githubusercontent.com/96416089/235038423-28dfc0fa-f2f0-47e6-8612-ac816a76df62.gif)
