### ISSUE TITLE
企业微信 WeMail cpu占用100%

### ISSUE THREAD

**Issue by mahmut-Abi** [linuxdeepin/developer-center#4048]
### SUMMARY | 问题概要

![image](https://user-images.githubusercontent.com/96514873/231065851-f53d15b0-1c78-41f1-8e20-2f5c72eda79c.png)
企业微信挂后台，这个进程cpu占用率一直都是100

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

企业微信：com.qq.weixin.work.deepin/unknown,now 4.0.16.6007deepin21 i386
系统:
cat /etc/os-release 
PRETTY_NAME="Deepin 20.8"
NAME="Deepin"
VERSION_ID="20.8"
VERSION="20.8"
VERSION_CODENAME="apricot"
ID=Deepin
HOME_URL="https://www.deepin.org/"
BUG_REPORT_URL="https://bbs.deepin.org/"

### STEPS TO REPRODUCE | 复现步骤

偶然发现，并没有什么规律，以前没注意到

**Comment by babyfengfjx** [comment]
这个现象我们先观察下，这边也可以看看，这种现象会持续多久，对正常使用有没有哪些明显的影响。

**Comment by babyfengfjx** [comment]
@vivianxf   这个可以在后续观察一下，看这个现象是否有什么影响，确认问题后可以提交到wine组进行分析。

**Comment by vivianxf** [comment]
当前暂未复现该情况，持续跟踪

**Comment by vivianxf** [comment]
当前暂未复现该情况，持续跟踪

**Comment by mahmut-Abi** [comment]
那就关了吧，我也是偶尔会遇到，平时都正常。可能那天触发了什么吧。

**Comment by UTsweetyfish** [comment]
这个我经常遇到
