### ISSUE TITLE
[Arch Linux] deepin-file-manager 双击无效

### ISSUE THREAD

**Issue by ryanlycch** [linuxdeepin/developer-center#405]
设置Open File 为 "Double Click", 然后双击任何文件夹或者文件都没有反应。

版本信息：
deepin-file-manager 1:4.4.2-1

桌面环境： XFCE4/Compiz

谢谢！

**Comment by felixonmars** [comment]
在 DDE 下用 xfwm4 可重现。

@dragondjf

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
