### ISSUE TITLE
Launcher doesn't launch

### ISSUE THREAD

**Issue by AllanDaemon** [linuxdeepin/developer-center#406]
I'm using the DDE in Arch Linux, version 15.5beta Desktop (64 bits).

After using a while, the launcher stops working: clicking the super key, the launcher button on the dock or the corner does not open the launcher.

When I restart the system, it works fine, but after a while using it, it stops working.

Also, is there any log, information or thing to test that I can do to help?

**Comment by felixonmars** [comment]
Did you try to kill and launch dde-launcher from a terminal?

**Comment by AllanDaemon** [comment]
> Did you try to kill and launch dde-launcher from a terminal?

Nope. I'm new to DDE. But I tried it now and it worked. Thanks, @felixonmars.

But I would like to investigate why is this happening. As I'm not familiar with DDE, I don't know where I  start looking, like if there are log files and where are they stored.

**Comment by hualet** [comment]
The log can be located at ~/.cache/deepin/dde-launcher/dde-launcher.log

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
