### ISSUE TITLE
【deepin_V23_beta】【一般】【有空】【集成测试】【DDE】【桌面】【DDE Cooperation】应用"多屏协同"显示相关问题

### ISSUE THREAD

**Issue by SuperEffie** [linuxdeepin/developer-center#4064]
### SUMMARY | 问题概要

【关联集成】：https://github.com/linuxdeepin/developer-center/issues/4033

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

1. 镜像地址：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230309/
2. 内核版本： 6.1.11-amd64-desktop-hwe
3. 版本信息：dde-session ： 1.1.0

### PRE-REQUIREMENT | 预置条件

添加以上集成#4033 中集成仓库后升级

### STEPS TO REPRODUCE | 复现步骤

1. 打开启动器，全屏，检查是否有DDE Cooperation图标
2. 启动器窗口模式下，检查DDE Cooperation是否翻译
3. 打开DDE Cooperation，观察其在任务栏上图标显示
4. 观察应用DDE Cooperation中界面显示

### OBSERVED RESULT | 观察到的结果

1. 启动器全屏模式下，没有DDE Cooperation图标
![未有DDE_cooperation](https://user-images.githubusercontent.com/58986464/231430025-68aa0e11-872b-466a-aae0-1111b456baf0.jpg)
2. 启动器窗口模式下，检查DDE Cooperation未翻译，应显示为中文
![需翻译](https://user-images.githubusercontent.com/58986464/231430071-33004343-f7ae-4439-bc6c-135aeb19c622.jpg)
3. 打开DDE Cooperation，其在任务栏上图标显示为锯齿状
4. 应用DDE Cooperation界面，显示位置有误
![图标显示问题](https://user-images.githubusercontent.com/58986464/231430109-464549a2-28f8-448f-9576-885869629d86.jpg)

### EXPECTED RESULT | 期望的结果

1. 启动器全屏模式下，显示DDE Cooperation图标
2. 启动器窗口模式下，检查DDE Cooperation应显示为中文
3. 打开DDE Cooperation，其在任务栏上图标应显示为应用图标
4. 应用DDE Cooperation界面，文字与二维码应居中显示，且应命名为“统信手机助手”

**Comment by babyfengfjx** [comment]
@dengbo11 请帮忙优化~

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0424镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230424
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
