### ISSUE TITLE
【deepin_V20.8】【文件管理器】访问缩略图缓存文件夹时，缩略图无限生成的bug

### ISSUE THREAD

**Issue by KuroB0T** [linuxdeepin/developer-center#4078]
### SUMMARY | 问题概要

开启文件管理器，访问~/.cache/thumbnails/large文件夹。此文件夹下保存着文件管理器为所有访问过的其他文件生成的缩略图。然而文件管理器并不识别这些是缩略图缓存文件，会在同一文件夹下生成缩略图文件的缩略图。这些新生成的缩略图又会识别为文件而进一步生成缩略图，导致缩略图无限生成。过程见如下的录屏。

https://user-images.githubusercontent.com/76643630/231706753-82cbcd0c-6606-4215-859a-1db371019f57.mp4

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Distribution: Deepin V20.8
Package: dde-file-manager 1.0.0

### PRE-REQUIREMENT | 预置条件

文件管理器中，开启“文件预览”和“显示隐藏文件”选项。

### STEPS TO REPRODUCE | 复现步骤

1. 打开文件管理器，开启任意“文件预览”和“显示隐藏文件”选项；
2. 访问任意有可以生成缩略图的文件的目录；
3. 通过左侧边栏目录的“数据盘”访问到主目录（若直接通过“快捷访问”->“主目录”访问，则不会出现这个bug）；
4. 进入.cache/thumbnails/large文件夹。

### OBSERVED RESULT | 观察到的结果

通过“数据盘”访问的主目录下缩略图缓存文件夹中，缩略图无限生成（见如上录屏）。

### EXPECTED RESULT | 期望的结果

应该如同通过“快捷访问”->“主目录”访问所观察到的结果一样，缩略图缓存文件的缩略图就是它们自身，不生成新的缩略图。

![截图_dde-desktop_20230412100558](https://user-images.githubusercontent.com/76643630/231706937-532f4f66-3883-408e-9ab0-49225ee58e99.png)

### ADDITIONAL INFORMATION | 额外补充

如果使用ln命令将其他的文件夹链接到主目录，那么通过这个文件夹所访问的缩略图缓存文件夹也会出现无限生成的bug。

**Comment by SuperEffie** [comment]
感谢您的反馈，该问题及提交的代码我们已经反馈给相应的研发同学，待处理后在这通知您~
