### ISSUE TITLE
The dock appears misplaced and a window of pamac-tray 

### ISSUE THREAD

**Issue by Xeers** [linuxdeepin/developer-center#408]
I use Arch-Deepin with the new 15.5-Beta-Desktop updates when I log in, the screen always appears like this: image
https://i.imgur.com/WJyeTv7.png
The launcher menu continues to appear in English, not in Spanish.
Regards

**Comment by felixonmars** [comment]
@sbwtw @zccrs Dock location issues.
@hualet Translation issues.

**Comment by Xeers** [comment]
The menu is in Spanish and the dock works correctly. Thanks very much. Muchas gracias

**Comment by Xeers** [comment]
The dock keeps coming out erroneously on the screen, it is not on the edge
