### ISSUE TITLE
[Deepin Integration]~[V23-Beta] kernel

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#4082]
### Package information | 软件包信息

包名 | 版本
--  | --
linux-firmware |1.202.9
linux-headers-6.1.11-amd64-desktop-hwe | 23.01.00.10
linux-image-6.1.11-amd64-desktop-hwe | 23.01.00.10
linux-libc-dev | 23.01.00.10

### Package repository address | 软件包仓库地址
deb [trusted=yes] https://ci.deepin.com/repo/deepin/deepin-community/obs-repos/ kernel main

### 更新日志
修复社区版本hwe-6.1内核8852be网卡不能使用问题
https://pms.uniontech.com/bug-view-193935.html

### Test suggestion | 测试建议
验证网络是否异常

### Influence | 影响范围
网卡驱动

**Comment by babyfengfjx** [comment]
@luodeepin  @vivianxf  @xuqi27837288  同步更新该内核，开展其他集成验证。

**Comment by SuperEffie** [comment]
【验证结论】：测试通过，集成后thinkbook14可识别到无线网络，且正常连接使用
