### ISSUE TITLE
[Deepin Integration]~[V23-Beta] Integrated org.deepin.Runtime

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#4091]
仓库地址： ll-cli repo modify http://10.0.36.228:9001/ --name develop-snipe

**Comment by Zeno-sole** [comment]
包名|版本
--|--
org.deepin.Runtime|23.0.0.9

**Comment by Zeno-sole** [comment]
修复 玲珑应用无法在托盘共存，如邮箱和音乐

**Comment by Zeno-sole** [comment]
https://github.com/linuxdeepin/developer-center/issues/3649

**Comment by Zeno-sole** [comment]
明道云集成流转

**Comment by luodeepin** [comment]
明道云集成链接：https://cooperation.uniontech.com/app/1c4062ac-cc50-4f6c-9d7d-52906b78a291/630719e7cf74a8b0029d1256/630719e7cf74a8b0029d1260/row/a6b41d4e-482e-4904-9e37-00b5f959f182

**Comment by vivianxf** [comment]
请处理问题#4099 @kamiyadm

**Comment by kamiyadm** [comment]
> 请处理问题#4099 @kamiyadm

已处理，runtime集成版本现更新为


包名 | 版本
-- | --
org.deepin.Runtime | 23.0.0.10

包含托盘问题和图标显示问题
@Zeno-sole @vivianxf

**Comment by SuperEffie** [comment]
关联pms: https://pms.uniontech.com/bug-view-196445.html
