### ISSUE TITLE
Release notification

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/developer-center#41]
Subscribe this topic to get the latest release notifications for Deepin projects.

@linuxdeepin/app-team @linuxdeepin/dde-team 
@choldrim @leaeasy @hualet @snyh @sonald

**Comment by felixonmars** [comment]
dde-desktop 3.0.5 -> 3.0.6
dde-dock 3.0.6 -> 3.0.7
dde-launcher 3.0.6 -> 3.0.7
dde-session-ui 3.0.8 -> 3.0.9

**Comment by felixonmars** [comment]
dde-control-center 3.0.10
deepin-desktop-base 2016.01.29

**Comment by felixonmars** [comment]
deepin-metacity 3.18.1.11

**Comment by felixonmars** [comment]
deepin-mutter 3.18.2.6

**Comment by fasheng** [comment]
test to catch github reply email address for deepin-jenkins

**Comment by choldrim** [comment]
test

**Comment by choldrim** [comment]
test-again

**Comment by fasheng** [comment]
test from email



2016年7月13日 18:10, 18:10，在 Choldrim <notifications@github.com> 已写:
>

**Comment by justforlxz** [comment]
This question has not been answered for too long and will be closed. If there is a need to continue the discussion, it will be reopened.
