### ISSUE TITLE
Deepin-dock not responding

### ISSUE THREAD

**Issue by lramadhan** [linuxdeepin/developer-center#410]
I've installed deepin for a week and it works fine. But about 2 days ago, i upgrade many application and include the deepin, and found that my dock is not responding and other application such as deepin setting, deepin screenshot, etc, isn't working (or maybe run after couple minutes).

I tried downgrade but no luck.

The only thing that work perfect just deepin launcher now.

OS : Archlinux x64.
and the dock goes plain black like this:
[this](https://user-images.githubusercontent.com/13545543/27262659-bc9533a0-545b-11e7-9f47-24c049a30a32.png)

**Comment by hualet** [comment]
Is deepin-wm or deepin-metacity running?

**Comment by lramadhan** [comment]
@hualet ; I'm new on this, but i try to run the command by typing `deepin-wm` and got `Window manager warning: Display ":0" already has a window manager; try using the --replace option to replace the current window manager.Segmentation fault (core dumped)` and when i type `deepin-metacity` i got `Window manager warning: Screen 0 on display ":0" already has a window manager; try using the --replace option to replace the current window manager.`

Sorry for leak of knowledge of me.

**Comment by felixonmars** [comment]
Please try this:

`xprop -id $(xprop -root -notype | awk '$1=="_NET_SUPPORTING_WM_CHECK:"{print $5}') -notype -f _NET_WM_NAME 8t`

**Comment by lramadhan** [comment]
@felixonmars i got this one
```
_NET_SUPPORTING_WM_CHECK: window id # 0x2c00002
_MUTTER_VERSION = "3.20.3"
_GNOME_WM_KEYBINDINGS = "Mutter"
_NET_WM_NAME = "Mutter(DeepinGala)"
```

**Comment by lramadhan** [comment]
@felixonmars i got this one:
```
_NET_SUPPORTING_WM_CHECK: window id # 0x2c00002
_MUTTER_VERSION = "3.20.3"
_GNOME_WM_KEYBINDINGS = "Mutter"
_NET_WM_NAME = "Mutter(DeepinGala)"
```

**Comment by felixonmars** [comment]
@hualet so it's deepin-wm.

**Comment by sonald** [comment]
the property only means that the last wm running is deepin-wm. It seems like no wm is running.  @lramadhan when it happened, Were you able to use alt+tab to navigate windows ? and try command `xdriinfo` in deepin-terminal.

**Comment by lramadhan** [comment]
Yes, i could it @sonald, the reason i still use it, but i just realised that i didn't install `xorg-xdriinfo` haha

after i run `xdriinfo` here is the result:
```Screen 0: not direct rendering capable.```

**Comment by mcurly** [comment]
hello.

I too have issues with dde-dock:

Here's one dump from it. (Happened on latest boot and sign in)

`nov 21 09:06:58 (hostname) systemd-coredump[19170]: Process 17159 (dde-dock) of user 1000 dumped core.
                              Stack trace of thread 17159:
                             #0  0x00000ab1ffffffff n/a (n/a)
`

If this should be put into another (different issue) feel free to do so.

Best regards

**Comment by lramadhan** [comment]
Update:
I got new update for dock on my Archlinux, but have no luck.

**Comment by lramadhan** [comment]
Update : I reinstalled my OS which is remove all application. And the deepin works as good as the first.

So i guess it caused of some application that i installed (in this case teamviewer) before i got error.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
