### ISSUE TITLE
[Deepin Integration]~[V23-Beta] deepin-installer

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#4102]
仓库地址： deb  [trusted=yes] https://aptly.uniontech.com/pkg/beige-v2/release-candidate/ZGVlcGluLWluc3RhbGxlcumbhuaIkDIwMjMtMDQtMDcgMTU6MjA6NDc/  unstable main

**Comment by Zeno-sole** [comment]
### 更新日志： 

解决镜像安装黑屏问题([14日](https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230414/deepin-23-beige-amd64-20230414-182555.iso)镜像启动黑屏卡LOGO等现象) 
排查根因是由于移除dde-kwin导致，安装器现更改为直接启动deepin-kwin

镜像地址：

**Comment by babyfengfjx** [comment]
@luodeepin   请用上面镜像开展验证。

**Comment by luodeepin** [comment]
此镜像安装系统正常
