### ISSUE TITLE
【deepin_V23_beta】【一般】【立即】【发散测试】【DDE】alt +tab 切换应用界面显示异常，企业微信模糊

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#4103]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

镜像：https://cdimage.uniontech.com/community/releases/23-Alpha2/deepin-desktop-community-23-Alpha2-amd64.iso

仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
     deb https://community-packages.deepin.com/beige/ beige main commercial community
包版本：dde-kwin       5.6.5-1 
内核：Linux v23-PC 6.1.11-amd64-desktop-hwe #23.01.00.01 SMP PREEMPT_DYNAMIC Mon Feb 27 17:25:36 CST 2023 x86_64 GNU/Linux

### PRE-REQUIREMENT | 预置条件

1. 安装镜像：https://cdimage.uniontech.com/community/releases/23-Alpha2/deepin-desktop-community-23-Alpha2-amd64.iso
2. 添加仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial 
3. 将系统更新至最新版本
4. 运行企业微信，文件管理器，浏览器，终端等多个不同的应用

### STEPS TO REPRODUCE | 复现步骤

1. 按快捷键 alt +tab ，切换应用

### OBSERVED RESULT | 观察到的结果

1. 切换窗口展示多个异常图标，存在模糊现象
![1](https://user-images.githubusercontent.com/96416089/232681945-062bbed2-eddc-4b9c-b189-2c74a8aa0cda.png)

### EXPECTED RESULT | 期望的结果

1. 不存在异常图标，界面显示清晰

**Comment by babyfengfjx** [comment]
@BLumia  请帮忙优化。

**Comment by xuqi27837288** [comment]
@baicailio 当前Release版本仍然此问题,企业微信是高频应用,建议优先解决处理~

**Comment by luodeepin** [comment]
验证通过
dde-shell: 0.0.29
https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240722/deepin-23-beige-release-amd64-20240722-104051.iso

![录屏_选择区域_20240722132709](https://github.com/user-attachments/assets/b7c5d092-a4f6-4086-8aee-681534c7d922)
