### ISSUE TITLE
安装器用户信息设置没有用户头像显示

### ISSUE THREAD

**Issue by dengbo11** [linuxdeepin/developer-center#4116]
### SUMMARY | 问题概要

进入系统安装界面,安装器用户信息设置没有用户头像显示

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin v23 beta;

### STEPS TO REPRODUCE | 复现步骤

无

**Comment by dengbo11** [comment]
#4128

**Comment by babyfengfjx** [comment]
@SuperEffie  请开展回归验证。

**Comment by SuperEffie** [comment]
【验证环境】
【镜像地址】：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230420/deepin-23-beige-amd64-20230420-102652.iso
【关联集成】：[#4128](https://github.com/linuxdeepin/developer-center/issues/4128)
【验证结论】：问题已修复，关闭此issue。安装时用户头像正常显示。
