### ISSUE TITLE
bug in command cd

### ISSUE THREAD

**Issue by he1l0world** [linuxdeepin/developer-center#412]
When I use cd in /usr/bin , then just press the "Tab" to automaticl complete, It  will auto add "X11" behind /usr/bin 
like this: cd /usr/bin/(Tab)(Tab)(Tab)(Tab)
it will be like this :/usr/bin/X11/X11/X11......
![Image of bug](http://dawsonchen.oss-cn-beijing.aliyuncs.com/bug.png)

**Comment by felixonmars** [comment]
What's the output of `type /usr/bin/X11`?

**Comment by hualet** [comment]
It seems to have a quite long history.
https://askubuntu.com/questions/191654/why-are-there-infinitely-many-x11-subdirectories-in-usr-bin-x11
