### ISSUE TITLE
截图录屏：录屏结束后无法保存到文件

### ISSUE THREAD

**Issue by pjzbq** [linuxdeepin/developer-center#4127]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Distribution Deepin V23(Beta)

### STEPS TO REPRODUCE | 复现步骤

1.打开截图录屏应用
2.选择区域
3.选择录屏功能
4.点击确认
5.显示正在保存录屏文件
6.对应路径下找不到视频文件

**Comment by babyfengfjx** [comment]
@SuperEffie  可以跟进内部问题：[PMS](https://pms.uniontech.com/bug-view-185915.html)

**Comment by babyfengfjx** [comment]
@kamiyadm  请在对齐问题信息后帮忙备注推进修复。

**Comment by kamiyadm** [comment]
已修复，待集成

**Comment by SuperEffie** [comment]
【关联pms】:https://pms.uniontech.com/bug-view-185915.html

**Comment by zccrs** [comment]
@kamiyadm 今天推动集成一个版本

**Comment by SuperEffie** [comment]
【验证环境】
【镜像地址】：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230511/deepin-23-beige-amd64-20230511-093256.iso
【版本信息】：org.deepin.screen-recorder:6.0.2.60
【相关集成】：https://github.com/linuxdeepin/developer-center/issues/4336
【硬件设备】：huawei Matebook 13(thinkbook 14的声音输入声音已修复正常)
【验证结论】：验证通过，无声音输入设备机器，插入耳机，录取mp4文件时勾选麦克风，录屏文件可正常保存
【截图信息】：
![7](https://github.com/linuxdeepin/developer-center/assets/58986464/afd673c1-6137-4597-b80a-a12ecaf6784c)
