### ISSUE TITLE
v23-Beta 集成 deepin-installer-6.0.21

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#4128]
仓库地址： deb  [trusted=yes] https://aptly.uniontech.com/pkg/beige-v2/release-candidate/ZGVlcGluLWluc3RhbGxlcumbhuaIkDIwMjMtMDQtMDcgMTU6MjA6NDc/  unstable main

**Comment by Zeno-sole** [comment]
### 更新说明：
解决安装器用户信息设置缺少用户头像显示

关联issues： https://github.com/linuxdeepin/developer-center/issues/4116

**Comment by Zeno-sole** [comment]
镜像地址： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230420/deepin-23-beige-amd64-20230420-102652.iso

**Comment by SuperEffie** [comment]
【验证结论】：测试通过
验证安装以上镜像，安装器中用户头像显示正常并可正常选择、切换
