### ISSUE TITLE
【deepin_V23_beta】【一般】【立即】【发散测试】【DDE】【控制中心】在控制中心 - 个性化- 主题 中设置外观为 深色后，等待10分钟，系统外观会变成自动

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#4139]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230420/deepin-23-beige-amd64-20230420-102652.iso
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/stable/ beige main community commercial
deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
deb https://community-packages.deepin.com/beige/ beige main commercial community
包版本：dde-control-center 6.0.11-1

### PRE-REQUIREMENT | 预置条件

1. 安装镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230420/deepin-23-beige-amd64-20230420-102652.iso
2. 添加仓库：eb https://ci.deepin.com/repo/deepin/deepin-community/stable/ beige main community commercial
deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
deb https://community-packages.deepin.com/beige/ beige main commercial community
3. 升级系统到最新版本

### STEPS TO REPRODUCE | 复现步骤

1. 在控制中心 - 个性化 - 主题 - 外观 中设置外观为深色 - 等待 5分钟

### OBSERVED RESULT | 观察到的结果

1. 外观变为 自动
![zidong](https://user-images.githubusercontent.com/96416089/233265272-c2b6c13e-092a-4fa4-bb81-8db6a57ae5a3.gif)

### EXPECTED RESULT | 期望的结果

1. 外观保持 深色

**Comment by xzl01** [comment]
关联issue https://github.com/linuxdeepin/developer-center/issues/4142

**Comment by babyfengfjx** [comment]
@luodeepin  请参考上面关联issue的更新，进行回归验证。

**Comment by luodeepin** [comment]
【验证环境】：
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230426/deepin-23-beige-amd64-20230426-101953.iso

仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
deb https://community-packages.deepin.com/beige/ beige main commercial community

内核：Linux v23-PC 6.1.11-amd64-desktop-hwe #23.01.00.10 
【验证步骤】：问题单中描述的步骤

【验证结果】：通过
![截图_选择区域_20230426104322](https://user-images.githubusercontent.com/96416089/234453176-bd4a724f-7199-4e8c-a25b-b6dc6f59bb8c.png)
