### ISSUE TITLE
Select Wallpaper glitches with display scaling

### ISSUE THREAD

**Issue by colinskow** [linuxdeepin/developer-center#414]
Using Ubuntu 17.10, Deepin Desktop 15.5 installed from `ppa:leaeasy/dde`.
Set wallpaper does not display correctly when display scaling is any value above 1.0.
![deepinscreenshot_select-area_20171122102133](https://user-images.githubusercontent.com/5303269/33143607-48eb8b04-cf6f-11e7-9c0e-7a1ef49e9c0d.png)

**Comment by sbwtw** [comment]
@zccrs

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
