### ISSUE TITLE
【deepin_V23_beta】【一般】【有空】【发散测试】【DDE】【控制中心】使用指纹登陆系统，会弹出 解锁登陆密钥环的弹窗

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#4146]
### SUMMARY | 问题概要

1. 使用自动登陆，无密码登陆时也会出现这个问题

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230420/deepin-23-beige-amd64-20230420-102652.iso
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/stable/ beige main community commercial
deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
deb https://community-packages.deepin.com/beige/ beige main commercial community
包版本 dde-daemon     6.0.13 
      dde-control-center 6.0.11-1
```

### PRE-REQUIREMENT | 预置条件

1. 安装镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230420/deepin-23-beige-amd64-20230420-102652.iso
2. 添加仓库：eb https://ci.deepin.com/repo/deepin/deepin-community/stable/ beige main community commercial
deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
deb https://community-packages.deepin.com/beige/ beige main commercial community
3. 升级系统到最新版本

### STEPS TO REPRODUCE | 复现步骤

1. 安装镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230420/deepin-23-beige-amd64-20230420-102652.iso
2. 添加仓库：eb https://ci.deepin.com/repo/deepin/deepin-community/stable/ beige main community commercial
deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
deb https://community-packages.deepin.com/beige/ beige main commercial community
3. 升级系统到最新版本

### OBSERVED RESULT | 观察到的结果

1. 使用指纹登陆系统，会弹出 解锁登陆密钥环的弹窗
![截图_dde-desktop_20230420143421](https://user-images.githubusercontent.com/96416089/233283650-cb7f40eb-6ddf-4528-82e2-2c792d1ea8bc.png)

### EXPECTED RESULT | 期望的结果

1. 无需解锁密钥环

**Comment by babyfengfjx** [comment]
@BLumia  请帮忙优化~

**Comment by BLumia** [comment]
看看是不是 DA 那边已经处理过了。

另注（测试可无视）：之前的讨论里，这个行为应当是 pam 刻意做的，即安全起见必须使用密码才能完整解锁钥匙环。对于非 deepin 发行版用户，此问题应该是不处理的。

- 可能相关 https://github.com/linuxdeepin/developer-center/issues/3099

**Comment by dengbo11** [comment]
https://github.com/linuxdeepin/developer-center/issues/5218

**Comment by dengbo11** [comment]
@babyfengfjx, 改问题在https://github.com/linuxdeepin/developer-center/issues/5218应该在这次集成中已经修复，请安排下回归测试！

**Comment by babyfengfjx** [comment]
@luodeepin  请开展回归验证。

**Comment by Zeno-sole** [comment]
@luodeepin  内测源缺少依赖包deepin-desktop-environment，已更新至ci testing仓库： deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial

**Comment by luodeepin** [comment]
https://github.com/linuxdeepin/developer-center/issues/3099
回归的时候需要把自动登录，无密码登录，指纹登录，人脸登录的情况都进行验证
然后已经录入过指纹和人脸，还有新录入指纹和人脸的两种场景都需要进行验证

**Comment by babyfengfjx** [comment]
@luodeepin  请在提交新版本集成后，开展回归验证。

**Comment by luodeepin** [comment]
验证失败
操作步骤：

安装镜像 - 在控制中心添加内测 - 升级重启
添加转测仓库，升级重启 - 再录入指纹，重启登录

**Comment by luodeepin** [comment]
验证通过

从来没有使用过生物认证的，首次录入后，重启登录时没有弹框
之前有录入过生物认证的，升级后，需要重新录入新的才在重启登录后没有弹窗
