### ISSUE TITLE
【deepin_V23-beta】【一般】【立即】【集成测试】【DDE】【桌面】任务栏会随机崩溃

### ISSUE THREAD

**Issue by sammy621** [linuxdeepin/developer-center#4148]
### SUMMARY | 问题概要

任务栏随机崩溃
崩溃期间，任务栏消失，桌面应用正常显示但不可打开（双击无反应），正在运行的程序会终止（如网易云音乐、WPS等）；
大概一段时间后（几十秒），会自动启动，应用可正常打开了，但崩溃前运行的程序，此时在任务管理器中都消失了。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin_V23-beta
```

### PRE-REQUIREMENT | 预置条件

1、一直参加内测，从V23 Alpha 2版本升级至最新的 Beta版本

### STEPS TO REPRODUCE | 复现步骤

1、打开网易云音乐听音乐、WPS Sheet 查看编辑文档、打开Edge浏览器查阅资料
2、发生频率大概每小时一次或长或短

### OBSERVED RESULT | 观察到的结果

1、任务栏消失
2、桌面显示正常
3、按微标键调不出启动器
4、Ctrl+e 调不出文件管理器，双击桌面‘计算机’应用也打不开；桌面上任何应用双击都打不开
5、Ctrl+Alt+ t 可以打开终端
6、几十秒后（或一分钟？），任务栏恢复显示；此时系统恢复正常，可正常操作

### EXPECTED RESULT | 期望的结果

dde-dock 运行稳定无异常

**Comment by sammy621** [comment]
预置条件做下补充：
1、一直参加内测，从V23 Alpha 2版本升级至最新的 Beta版本
2、打开wine版本微信、网易云音乐听音乐、WPS 文字、表格 查看编辑文档、打开Edge浏览器查阅资料

**Comment by tsic404** [comment]
相同issue https://github.com/linuxdeepin/developer-center/issues/3598

**Comment by xzl01** [comment]
使用最新的am测试 是否能复现问题？

**Comment by sammy621** [comment]
> [application-manager.zip](https://github.com/linuxdeepin/developer-center/files/11284293/application-manager.zip)

替换安装后，问题仍然存在

**Comment by babyfengfjx** [comment]
@luodeepin  请结合内测用户反馈，确认该问题是否得到彻底修复，继续观测一段时间，如果在后续集成的几次版中均无问题，可以作关闭处理。
同时需要关注其相关的关联issue的处理。

**Comment by luodeepin** [comment]
dde-dock       6.0.18
验证通过
