### ISSUE TITLE
Login animation freezes on Ubuntu 17.10

### ISSUE THREAD

**Issue by colinskow** [linuxdeepin/developer-center#415]
Using Ubuntu 17.10, Deepin Desktop 15.5 installed from `ppa:leaeasy/dde`. The login animation (blue circle on black background) doesn't move while Deepin is starting, just a couple blue dots. Login works fine, but it would be nice to have a fluid animation.

**Comment by sbwtw** [comment]
Yep. Thas a small issue. w'll optimize it.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
