### ISSUE TITLE
【deepin_V23-beta】微信自带截图异常，无法截图，且会导致微信崩溃

### ISSUE THREAD

**Issue by linuxlionking** [linuxdeepin/developer-center#4158]
### SUMMARY | 问题概要

微信自带截图异常，无法截图，且会导致微信崩溃

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
EditionName[zh_CN]=社区版(Beta)
MajorVersion=23
MinorVersion=23
OsBuild=21238.100

com.qq.weixin.deepin/stable,now 3.7.0.30deepin13 i386 [已安装]
```

### STEPS TO REPRODUCE | 复现步骤

使用微信聊天窗口的截图功能，进行截图（是否勾选 隐藏聊天窗口 都可以，都能复现）

### OBSERVED RESULT | 观察到的结果

无法截取，黑屏，且微信主程序退出

### EXPECTED RESULT | 期望的结果

正常截图，微信不退出

**Comment by xuqi27837288** [comment]
暂未复现到此问题，当前版本3.7.0.30deepin24 微信截图功能正常可用，后续持续关注该问题，该issues暂时关闭处理~
