### ISSUE TITLE
Scaling issues. (1.25 and higher)

### ISSUE THREAD

**Issue by heck82** [linuxdeepin/developer-center#416]
Hi Deepin Dev-Team!
At first - Really like Deepin Desktop 15.5 beta with Arch Linux on my 13 inch laptop.
And for efficiency using Display Scale (1.25).
But then appears graphical artifacts (see attachment)

on settings menu - icons becomes sharp,
on dde-file-manager - around icons and some buttons appears frames,
Launcher bar - appears frame (using on top).

Terminal no glitches found
Nautilus - no issues.

Tested on laptop (lenovo710s) and on PC (VirtualBox).

Hoping for a fast resolving. Thanks.

![24-11-2017 15-50-55](https://user-images.githubusercontent.com/17931180/33214102-2d62d9b2-d133-11e7-90cc-0287ce0034fc.jpg)
![24-11-2017 15-51-26](https://user-images.githubusercontent.com/17931180/33214103-2d7efebc-d133-11e7-9cf5-5351ee4ec7b7.jpg)
![24-11-2017 15-52-07](https://user-images.githubusercontent.com/17931180/33214104-2d9a93b6-d133-11e7-8d5d-09f384b06146.jpg)
![24-11-2017 15-55-19](https://user-images.githubusercontent.com/17931180/33214105-2db52b54-d133-11e7-902f-26cac95f330e.jpg)

**Comment by hualet** [comment]
Yeah, we've noticed that it's pretty serious and trying very hard to solve it.

**Comment by dwlsalmeida** [comment]
Deepin 15.8 still has these issues.  All menu icons are distorted when using display scaling, even those inside third party programs

**Comment by hualet** [comment]
what's your distribution? not deepin I guess?
deepin patched Qt to solve the problem, but not for other distributions.

**Comment by hualet** [comment]
> @hualet Arch.
> Can't this be solved in another way? Plenty of people using DDE outside of the Deepin distro, and these distros won't push patched versions of Qt just because of one DE.

Then I suppose we should disable fractional scaling support in other distros? 
Just kidding :) We're working on a new solution, don't rely on our patches on Qt, hope it works in the furture.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
