### ISSUE TITLE
【deepin_V23_beta】【一般】【有空】【集成测试】【原子更新】使用升级工具将系统deepin v20.9升级至v23 beta后，启动菜单中显示不全

### ISSUE THREAD

**Issue by SuperEffie** [linuxdeepin/developer-center#4160]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

【镜像地址】： https://packagesupdate.uniontech.com/repo/desktop-apricot/iso-apricot/20.9/20230417/deepin-20.9-apricot-20230417-1754-amd64.iso
【相关集成链接】：#4054  、 #4096 
【集成仓库】：deb [trusted=yes] https://aptly.uniontech.com/pkg/apricot/release-candidate/RGVlcGlu5Y2H57qn5bel5YW3MjAyMy0wNC0xMiAxMDo0NToyNg/ unstable main
【版本信息】: deepin-system-upgrade：6.0.2.5-1

### STEPS TO REPRODUCE | 复现步骤

【操作步骤】：

1. 下载“原子更新”：sudo apt install deepin-upgrade-manager
2. 下载“升级工具”：sudo apt install deepin-system-upgrade
3. 修改配置文件：/etc/deepin-system-upgrade/config.yaml中url项为“https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230420/deepin-23-beige-amd64-20230420-102652.iso”
4. 注销后，使用升级工具升级（不进行应用迁移）
5. 升级至v23 beta 版本后，重启系统，观察启动菜单中显示

### OBSERVED RESULT | 观察到的结果

启动菜单中只有“系统恢复”和“System Setup”项，且选择“系统恢复”项系统无法恢复。
![5](https://user-images.githubusercontent.com/58986464/233523996-5b0cdee4-1fd1-423b-84f8-0374f5cc0975.jpg)

### EXPECTED RESULT | 期望的结果

启动菜单项显示完整，且系统能正常恢复。
![6](https://user-images.githubusercontent.com/58986464/233524004-6013fc25-7897-44d3-917e-a0b720dede30.jpg)

**Comment by l631197874** [comment]
经排查发现快照仓库的/boot目录中有内核以及initrd文件，但是/boot目录下内核文件和initrd文件缺失

**Comment by l631197874** [comment]
根因：升级到V23后，系统会从V23仓库安装升级工具进行应用迁移，然而目前V23主仓库最新的升级工具属于旧版本了，旧版本升级工具会对包做全量迁移，通过包的安装导致/boot目录下的内核文件被删除，从而导致grub引导项缺失。
临时解决办法： 升级到V23之后，立即关闭自动弹出的升级工具界面，手动安装地址：**deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-intergration-pr-14/testing/ ./** 下的包，然后重启系统重新开始应用迁移
最终解决办法： 等CI那边将**6.0.3**版本的包推送到V23主仓库，升级到V23之后自动弹出的升级工具就是最新的，无需任何操作，等待应用迁移完成即可。

**Comment by SuperEffie** [comment]
【验证环境】
【镜像地址】：https://packagesupdate.uniontech.com/repo/desktop-apricot/iso-apricot/20.9/20230417/deepin-20.9-apricot-20230417-1754-amd64.iso
【集成仓库】：deb [trusted=yes] https://aptly.uniontech.com/pkg/apricot/release-candidate/RGVlcGlu5Y2H57qn5bel5YW3MjAyMy0wNC0xMiAxMDo0NToyNg/ unstable main
【操作步骤】：借鉴以上提单步骤，升级至v23后，加入内测仓库，下载升级工具，进行应用迁移，迁移完成后重启查看启动项
【验证结论】：验证通过，启动项显示完整
