### ISSUE TITLE
Dock applet says No Network, but wireless works. Can't configure wifi

### ISSUE THREAD

**Issue by chdslv** [linuxdeepin/developer-center#417]
Installed Deepin through ppa:leaeasy/dde on Ubuntu 17.10 server edition. I had the ubuntu server installation working with wireless. The installation of Deepin also was done through wireless. In the installed Deepin, I cannot configure wireless. The icon on the dock says "No network." The Deepin control center doesn't show any wireless (Click icon to enable WIFI). 

_The strange thing is, I have the wireless working._ That is, the installed Deepin is connected to wireless. Internet works, can update/upgrade.

**Nothing is there in /etc/NetworkManager/system-connections.** I checked this folder in another Ubuntu install, and there were 2 files for my router. 

>

>  $ iwconfig
> lo        no wireless extensions.
> 
> wlp3s0    IEEE 802.11  ESSID:"My Router"  
>           Mode:Managed  Frequency:2.462 GHz  Access Point: F4:6B:EF:9F:D4:3B   
>           Bit Rate=65 Mb/s   Tx-Power=15 dBm   
>           Retry short limit:7   RTS thr:off   Fragment thr:off
>           Power Management:off
>           Link Quality=62/70  Signal level=-48 dBm  
>           Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
>           Tx excessive retries:0  Invalid misc:103   Missed beacon:0
> 
> enp2s0f2  no wireless extensions.

Edit: Also downloaded the ubuntu deepin iso from Baidu, and in that too, I can't configure wireless at all.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
