### ISSUE TITLE
Deepin Developer Meeting Record - 深度开发者线下会议记录整理

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/developer-center#42]
[深度开发者线下会议](https://github.com/linuxdeepin/developer-center/wiki/developer_month_meeting) 记录

**2016 02 26 第一期**
主题: 
- [仓库Review系统的探讨](https://github.com/choldrim/deepin_offline_developers_meeting)
- [开发者相关规范简介及其他](https://github.com/linuxdeepin/developer-center/files/147845/20160226-.tar.gz)
- [systemtap介绍与deepin上的使用](https://github.com/linuxdeepin/developer-center/files/147851/systemtap_intro.org.tar.gz)
- [开发文档生成与展示](https://github.com/Iceyer/slides/blob/master/doxygen/doxygen.md)
- [DDE 后端概述](https://github.com/linuxdeepin/developer-center/files/147939/dde-backend-outline.tar.gz)
- [代码规范及自动化配置](https://github.com/sbwtw/sbwtw.github.io/raw/master/sliders/code_style.odp)

本次会议除以上主题外还确定了3月份要看到效果的事情．　
1.  　dde-daemon和libdui的文档工作
2.      commit 书写规范
3.      部分项目自动检测代码质量CI上线

**Comment by Iceyer** [comment]
https://github.com/Iceyer/slides/blob/master/doxygen/doxygen.md

**Comment by snyh** [comment]
**2016 03 25**
主题:

- 系统中各种时间的梳理　夏彬

**Comment by wangyingtaodeepin** [comment]
- Phoronix Test Suite 性能自动化测试

**Comment by snyh** [comment]
**2016 04 29 第三期**

**Comment by snyh** [comment]
*2016 05 27 第四期*

**Comment by snyh** [comment]
*2016 06 24 第五期*

- systemd on deepin    snyh
     - unit 与 service, target,slice等核心概念
     - systemd管理下的系统bootup
     - DDE的一些优化思路　(systemd方向)

**Comment by snyh** [comment]
*2016 07 29 第六期*

- sysfs 系统介绍    snyh
    - Linux Driver Mode (LDM) 相关介绍
    - sysfs的一些基本原则
    - udev 与 sysfs
    - driver&&device tips

**Comment by snyh** [comment]
**2016 08 26 第七期**

- xdg thumbnail   dragondjf 
- xinput && xim  snyh
