### ISSUE TITLE
[Arch Linux] How to use ssh-agent?

### ISSUE THREAD

**Issue by diegobernardes** [linuxdeepin/developer-center#420]
Just installed deepin on my arch, works great, very smooth and fast. But got some problem with ssh-agent, gnome handled that for me automatic, how can i start the ssh-agent or any kind of keyring on deepin running on arch? 

It's annoying the git asking for my ssh password all the time.

**Comment by yiip87** [comment]
@diegobernardes if this is still relevant: This works fine for me (I'm using `gnome-keyring`):

`/etc/xprofile`:
```bash
# Start Gnome-Keyring
if [ -n "$DESKTOP_SESSION" ];then
    eval $(gnome-keyring-daemon --start)
    export SSH_AUTH_SOCK
fi
```

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
