### ISSUE TITLE
控制中心修改主题会影响圆角设置

### ISSUE THREAD

**Issue by asterwyx** [linuxdeepin/developer-center#4200]
### SUMMARY | 问题概要

在控制中心切换主题，已经设置的圆角大小会被重置为大圆角。同理，修改圆角大小，控制中心会认为主题变成自定义。圆角设置被考虑进了主题。这两者的设置应该分离，而不应该耦合。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
Distribution: deepin V23 Develop Edition
Packages:
dde-control-center=6.0.17
dde-appearance=1.0.8
```

### PRE-REQUIREMENT | 预置条件

NA

### STEPS TO REPRODUCE | 复现步骤

1. 在当前主题情况下将大圆角切换成中圆角；
2. 切换主题；
3. 观察圆角设置。

### OBSERVED RESULT | 观察到的结果

圆角设置被重置为了大圆角。

### EXPECTED RESULT | 期望的结果

圆角设置保持中圆角。

**Comment by meiyixiang** [comment]
当前的逻辑是，桌面默认提供了6个主题，基于任何 一个主题用户可进行自定义修改，修改后则变为自定义主题状态。用户在选择主题时逻辑上是对所有设置项进行了默认主题的修改。
备注：当前控制中心只有能力针对一个默认主题进行自定义修改，不能够定义自定义主题A\B\C的能力。
现状无问题，设计如此。

**Comment by Decodetalkers** [comment]
我想主题是不是可以不包含圆角的设置。。

**Comment by meiyixiang** [comment]
目前的设计就是这样的，如果你喜欢某一个主题可根据这个主题进行圆角的设置，设置后此主题将衍生成为一个自定义主题，你可以在这个自定义主题下进行设置。但如果你再次切换至其他主题你所设置的圆角将会变为你选择的系统主题的默认圆角大小。这个逻辑就是这样的。

**Comment by dengbo11** [comment]
设计如此, 先关闭处理
