### ISSUE TITLE
deepin-editor搜索功能在只存在与大小写不完全匹配的结果时，搜索结果展示情况不符合预期。

### ISSUE THREAD

**Issue by ZOUYAYI** [linuxdeepin/developer-center#4203]
### SUMMARY | 问题概要

deepin editor搜索bug。搜索功能严格按照大小写匹配的规则。然而，在文档中只存在与搜索关键词大小写不完全匹配的结果时，搜索结果展示情况并不符合预期。
（1）文档中只存在与搜索关键词大小写不完全匹配的结果，文档中无高亮，但搜索框并未变红。
（2）搜索关键字在匹配字符串中重叠出现的情况，高亮情况不符合预期。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
Distribution: Deepin V20.8
Package: deepin-editor
```

### PRE-REQUIREMENT | 预置条件

无

### STEPS TO REPRODUCE | 复现步骤

（1）文档中只存在与搜索关键词大小写不完全匹配的结果。
1）在文档中输入“deepIn”；
2）在搜索框中输入“deepin”，回车。

（2）当搜索关键字在匹配字符串中重叠出现的情况。
1）在文档中输入“deepinInitIni”。
2）在搜索框中输入“Ini”，回车，回车。

### OBSERVED RESULT | 观察到的结果

（1）文档中无高亮，但搜索框并未变红。
![图1](https://user-images.githubusercontent.com/46862498/233943634-981d5d7f-0825-4f5f-8a55-1f5874141738.png)

（2）可以正常选取到两个“Ini”子字符串，然而只有第二个子字符串被高亮，第一个没有被高亮。
![图2](https://user-images.githubusercontent.com/46862498/233943659-3437867a-212c-4c71-84de-4537d29a8ece.png)
![图3](https://user-images.githubusercontent.com/46862498/233943690-15e21455-d766-459e-9374-609828589f0f.png)

### EXPECTED RESULT | 期望的结果

（1）文档中无匹配，应该如下图变红提示。
![图4](https://user-images.githubusercontent.com/46862498/233943767-34eeda0f-9006-49fa-8fe7-ec901b66c751.png)

（2）预期情况是高亮“InitIni”中的两个“Ini”子字符串。然而，搜寻的结果只高亮了后一个“Ini”。

### ADDITIONAL INFORMATION | 额外补充

问题分析：由于“deepinInit”中存在子字符串“inIni”，程序首先搜寻到了“inI”子字符串，然而并不匹配搜寻关键词的大小写。而后由于“I”已经包含在字符串中，高亮部分的程序将其跳过，因此没有高亮到第一个“Ini”。然而，选取部分的程序似乎是正常工作的。处理逻辑存在一定冲突。

**Comment by luodeepin** [comment]
【验证环境】文本编辑器 6.0.9
【验证步骤】提单的步骤
【验证结果】通过
【截图录屏】
![截图_选择区域_20230608101507](https://github.com/linuxdeepin/developer-center/assets/96416089/f6a3fae8-4b57-47ab-a086-93501fca3d80)

【备注信息】
