### ISSUE TITLE
刚开机时的锁屏和键盘输入问题

### ISSUE THREAD

**Issue by lizipeng0013** [linuxdeepin/developer-center#4219]
### SUMMARY | 问题概要

在刚开机时，键盘右边的数字无法输入密码（已开启NumLock），此时重新开关NumLock或鼠标点击一下屏幕就可以输入密码了

键盘左边的数字不受影响，可以正常输入密码

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin 20.9
```

### PRE-REQUIREMENT | 预置条件

刚开机时

### STEPS TO REPRODUCE | 复现步骤

在刚开机时，键盘右边的数字无法输入密码（已开启NumLock），此时重新开关NumLock或鼠标点击一下屏幕就可以输入密码了

**Comment by xuqi27837288** [comment]
* https://github.com/linuxdeepin/developer-center/issues/7460

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240402
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.21-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
