### ISSUE TITLE
【deepin_V23_beta】通知中心中的时间小部件，时差计算错误

### ISSUE THREAD

**Issue by sammy621** [linuxdeepin/developer-center#4226]
### SUMMARY | 问题概要

在通知中心中设置多个城市时间，时间的计算不对。
比如，迪拜的时间应该是比北京时间早4小时，而系统显示的是大4小时
![image](https://user-images.githubusercontent.com/5162723/234202799-207bd98e-2e15-4f99-9c99-b793715adf9e.png)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
Distribution: V23 Beta 内测
```

### STEPS TO REPRODUCE | 复现步骤

1.在通知中心添加世界时钟小组件
2.添加其它时区的城市，如迪拜
3.对比本地城市与迪拜时间，能看到错误

### EXPECTED RESULT | 期望的结果

正确计算时区城市时间

**Comment by wineee** [comment]
[ddewidget.zip](https://github.com/linuxdeepin/developer-center/files/11796408/ddewidget.zip)

**Comment by xuqi27837288** [comment]
验证通过

![截图_选择区域_20230620141539](https://github.com/linuxdeepin/developer-center/assets/62528742/729cf811-02f9-4ffa-a13c-be496ca8ac70)

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0516镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
【截图录屏】：


![截图_选择区域_20230720150903](https://github.com/linuxdeepin/developer-center/assets/62528742/624567cd-e526-4355-9987-f6f4ce82b978)
