### ISSUE TITLE
Shutdown UI is white when using PNG wallpaper on Nvidia GPU

### ISSUE THREAD

**Issue by maxlefou** [linuxdeepin/developer-center#423]
I'm still not sure i'm posting it at the right place...

**What happens:**
- The shutdown interface (the screen with shutdown, reboot, logout buttons and all) appears plain white, making the buttons completely hidden but still clickable. (apparently only happens when using Nvidia non-free drivers and a nvidia gpu)

**How to reproduce the bug:**
- Take a picture in PNG format, right clicking it and "`Define as a wallpaper`",
- Click on the button that activates the shutdown interface.

**How to fix it at the time i'm writing:**
- Use a picture in JPEG format for wallpapers since this format works perfectly right with deepin.

**Comment by ValeTheVioletMote** [comment]
Wow, so that's what this was. Having the same problem! Check out the comments on #1125  .. This may actually be an NVIDIA issue.

**Comment by ValeTheVioletMote** [comment]
https://askubuntu.com/questions/1048274/ubuntu-18-04-stopped-working-with-nvidia-drivers

**Comment by ValeTheVioletMote** [comment]
What worked for me was to just remove the blank image from /var/cache/image-blur

**Comment by maxlefou** [comment]
Indeed i'm using a nvidia gpu. Thanks for reminding me, i forgot to mention it :p

**Comment by BLumia** [comment]
Sorry for the late response, we just migrate our workflow (issue tracking and code review) to GitHub a few month ago..

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
