### ISSUE TITLE
【deepin_V23-beta】【一般】【有空】【集成测试】【DDE】【桌面】alt+tab 快捷键无法调器切换窗口

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#4230]
### SUMMARY | 问题概要

alt+tab 快捷键无法唤起切换窗口

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230424/  
dde-session-shell:6.0.8
```

### STEPS TO REPRODUCE | 复现步骤

1.多开个几个应用窗口
2.使用alt+tab键尝试唤起切换窗口

### OBSERVED RESULT | 观察到的结果

1.可以切换应用，但是无法唤起切换窗口

### EXPECTED RESULT | 期望的结果

1.可以唤起切换窗口

**Comment by babyfengfjx** [comment]
@justforlxz  请帮忙优化~

**Comment by zccrs** [comment]
@justforlxz 明天修复

**Comment by kegechen** [comment]
确认修复

**Comment by vivianxf** [comment]
【验证镜像】：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
【验证版本】：dde-session-shell->6.0.10
【验证步骤】：提单的步骤
【验证现象】：符合预期
【验证结论】：通过
![Screenshot_dde-control-center_20230821112104](https://github.com/linuxdeepin/developer-center/assets/96415804/4a52738e-a796-409d-9313-f2a9961520d1)
