### ISSUE TITLE
Wacom (or any graphic tablet) lag and freezes when moving system app windows (File manager, Mail etc)

### ISSUE THREAD

**Issue by SreckoM** [linuxdeepin/developer-center#4234]
### SUMMARY | 问题概要

When using Wacom, or any other graphic tablet (Huion or XPPen), I am not able to drag windows for most of system apps. Like File manager, Mail, Settings  etc. It starts to move than it freezes everything until I hit Esc key. As workaround I found that if I hold Alt key, it will move windows without freezing. But if I want to drag and drop file, it will not work. Entire using graphic tablet experience seems buggy. 

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
Distribution:Deepin 20.9
```

### PRE-REQUIREMENT | 预置条件

You just need to use graphic tablet on fresh deepin 20.9 install.

### STEPS TO REPRODUCE | 复现步骤

1. Boot to Deepin
2. Move File manager while using Wacom (or any other graphic tablet)

### OBSERVED RESULT | 观察到的结果

Windows start moving than stops. Freezes.

### EXPECTED RESULT | 期望的结果

Should behave same as when you use mouse.

**Comment by babyfengfjx** [comment]
Thank you very much for submitting the issue. As version V20.9 and later will no longer receive updates, we will continue to monitor this issue in deepin V23. If you are able to use V23 in the future and encounter any problems, please feel free to submit them. We will close this issue for now and keep an internal record. Thank you again for your attention.

**Comment by babyfengfjx** [comment]
@luodeepin  请在V23版本尝试复现该问题。
