### ISSUE TITLE
inode/directory mimetype doesn't open dde-file-manager by default

### ISSUE THREAD

**Issue by maxlefou** [linuxdeepin/developer-center#424]
### What happens:
When a program calls `xdg-open` to open a folder, it just opens another program. In my case, it opens Audacious, a music player...
the default query for it returned this to me:
`$ xdg-mime query default inode/directory`
`audacious.desktop`

### What's expected:
`inode/directory` should open the right default file explorer program. For a linux using only Deepin as DE, it should be dde-file-manager.
Eventually, there should be an option to choose what default program to use for folders opening...

### How to fix it while it's corrected:
Use the command below:
`$ xdg-mime default dde-file-manager.desktop inode/directory`

### Specs:
Linux Antergos (Arch) x86_64 
Deepin 15.5

**Comment by hualet** [comment]
I think that has nothing to do with dde-file-manager, apps are free to register mimetype associations and override associations set by other apps in Linux world. In this case I believe it's audacious set it self as the default inode/directory opener over dde-file-manager.

**Comment by maxlefou** [comment]
There still should be a way to set a default folder opening program in the settings. Why there's not one? Not everyone using deepin wants to use dde-file-manager for opening folders. IT's not my case but i have seen alot of forum posts complaining about this (which is how i got the fix for my problem)
