### ISSUE TITLE
[ArchLinux] Terminal Deepin and installation dd command

### ISSUE THREAD

**Issue by Xeers** [linuxdeepin/developer-center#425]
Terminal Deepin failed several times when creating an usb installer (sudo fdisk -l, Example sudo dd if=/home/kdeepin/Desktop/Reborn-OS-2017.12.05-x86_64.iso of=/dev/sdg
With other terminals, like Konsole, on the same pendrive this is done without problems

**Comment by hualet** [comment]
@felixonmars Help !!!

**Comment by felixonmars** [comment]
I can't see how this is related to the terminal emulator. Can you elaborate a bit more on the error messages?

**Comment by Xeers** [comment]
I tried it more than five times with the same pendrive. No error messages come out. With the Konsole program (from KDE) to the first one.

**Comment by felixonmars** [comment]
Well, I still don't think terminal emulator is the problem if you just run dd inside it.
