### ISSUE TITLE
deepin v23 任务栏在窗口最大最小化出现直角与圆角变化

### ISSUE THREAD

**Issue by qq4945286** [linuxdeepin/developer-center#4258]
### SUMMARY | 问题概要

任务栏bug 会随着软件的展开与收缩，任务栏会出现直角与圆角变化
![0003](https://user-images.githubusercontent.com/48000816/234920096-c7595182-7580-4cee-a691-842445125429.gif)
打开文本编辑器时会出现无效文件加系统的用户名
![04](https://user-images.githubusercontent.com/48000816/234920453-84186fa3-08db-444e-9ee5-bcc35efe80fe.gif)
电脑配制与系统信息
![截图_选择区域_20230428000549](https://user-images.githubusercontent.com/48000816/234921809-50fa85de-9139-4b63-8792-4e303f26ab8c.png)
![截图_选择区域_20230428000514](https://user-images.githubusercontent.com/48000816/234921840-1d481f00-4ad5-4d3c-b8c2-857b13bf260d.png)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
操作系统：deepin v23
内核：6.1
```

### STEPS TO REPRODUCE | 复现步骤

一直会出现

**Comment by xzl01** [comment]
cc @justforlxz

**Comment by BLumia** [comment]
> 打开文本编辑器时会出现无效文件加系统的用户名

这个和圆角无关吧？建议另开个 issue 反馈与跟进。

**Comment by justforlxz** [comment]
圆角的问题正在尝试修复： https://github.com/linuxdeepin/deepin-kwin/pull/171

**Comment by justforlxz** [comment]
> 圆角的问题正在尝试修复： [linuxdeepin/deepin-kwin#171](https://github.com/linuxdeepin/deepin-kwin/pull/171)

不过大概率和魔灯插件有冲突，不是很好解决（
