### ISSUE TITLE
Weird keyboard layout with accents

### ISSUE THREAD

**Issue by diegobernardes** [linuxdeepin/developer-center#426]
I have a english keyboard and i'm using the layout `English (US, alt. intl.)`, the problem is, don't know how, after some time the layout is lost. Just have a single keyboard layout defined, but happen with multiple layouts too. 

The thing is can't type anymore some characters with accents (çãéóá). I need to change the layout and go back to type it.

Anyone got anything like this?

**Comment by slinstj** [comment]
I came here for the same cause. Everytime I suspend or turn off my notebook my keyboard layout is lost when I come back! Everytime, no exceptions (since about 2 months ago). The only workaround I can use for now is `SUPER + SPACE` to change the keyboard layout and repeat it again to change back.

**Comment by slinstj** [comment]
Three months ago I had to change back to Ubuntu mainly for sake of this issue. I see no answers or some light till now.

**Comment by cirospaciari** [comment]
Still the same problem in 2020 :/

**Comment by cirospaciari** [comment]
Its working now, after deepin 20 (1002) release :D

**Comment by xmuli** [comment]
> 深度20（1002）发布之后，它现在可以正常工作：D

nice, then I will close this question, if you have any questions, please open it again
