### ISSUE TITLE
dde-file-manager 在移除磁盘介质时，已安全移除的设备仍提示未安全移除

### ISSUE THREAD

**Issue by Huayuluoshi** [linuxdeepin/developer-center#4267]
### SUMMARY | 问题概要

移除磁盘介质提示未安全移除，但是实际上已经安全移除

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin V20.9
dde-file-manager 5.9.2
```

### PRE-REQUIREMENT | 预置条件

任何磁盘

### STEPS TO REPRODUCE | 复现步骤

插入磁盘
在文件管理器右键磁盘
选择安全弹出

### OBSERVED RESULT | 观察到的结果

通知中心提示设备已经安全移除，但是文件管理器提示设备未安全移除

### EXPECTED RESULT | 期望的结果

正常移除设备，文件管理器不提示设备未安全移除
或者直接拔掉磁盘。提示未安全移除

### ADDITIONAL INFORMATION | 额外补充

相关日志已发到深度论坛，链接：https://bbs.deepin.org/zh/post/255496

**Comment by babyfengfjx** [comment]
目前V20.9版本不会进一步更新了，此类问题我们会在V23版本持续关注，感谢提交~
如V23版本也有类似问题，也可以重新提交issue。
