### ISSUE TITLE
[Deepin Integration]~deepin-compatibility-mode

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#4278]
### Package information | 软件包信息

包名 | 版本
--  | --
deepin-compatibility-mode | 0.1.2

### Package repository address | 软件包仓库地址

    deb [trusted=yes] https://ci.deepin.com/repo/deepin/deepin-community/obs-repos/ unstable  main

#### deepin-compatibility-mode (0.1.0) unstable; urgency=medium

  * add patch

### Test suggestion | 测试建议

安装deepin-compatibility-mode软件包以后, 从商店切换至测试实例, 然后安装商店测试实例中的以下包进行基础功能的测试:

- anydesk
- peek
- xpad
- parloe
- gnome calender
- gnome mines
- gnote

### Influence | 影响范围
第三方应用

**Comment by Zeno-sole** [comment]
@black-desk  请补充相关信息，完成后assign给 @xuqi27837288  进行验证

**Comment by vivianxf** [comment]
当前安装peek 运行失败

**Comment by vivianxf** [comment]
参考文档https://doc.uniontech.com/docs/1d3aVlD1lWieRwqg，切换v20兼容环境成功
验证以下应用运行
anydesk，peek，xpad，gnome calender，gnome mines，gnote 可以正常使用，
parloe已经提单https://github.com/linuxdeepin/developer-center/issues/4327，
目前仍然存在打开太慢，每次打开都有英文提示的问题。
整体情况看来可以继续往下优化

**Comment by Zeno-sole** [comment]
打开慢是商店创建符号链接工具性能问题，该问题遗留，先集成到仓库
