### ISSUE TITLE
Right-clicking on the Dock causes Deepin to freeze.

### ISSUE THREAD

**Issue by Xeers** [linuxdeepin/developer-center#428]
[Arch Linux] 
Right-clicking on the Dock causes Deepin to freeze.
You click on the Control Center, it opens but does not recede, it stays fixed. It only closes by clicking on Launcher

**Comment by felixonmars** [comment]
I see, we may need a dde-control-center release. @sbwtw

**Comment by TheDroop** [comment]
Arch linux x64, fresh installation via antergos.
When rightclicking on an item in the dock the menu pops up but it cant be interacted with( or any other item on screen for that matter). Going to tty2 and killing dde-dock I can see the dock restarting but the dialog stays up and I still cant interact with anything at all.
Greetings

**Comment by JulianLai** [comment]
@Xeers @TheDroop Update the deepin-api, and it will be fixed.

**Comment by Xeers** [comment]
Thanks very much

**Comment by zameran** [comment]
Distro: Arch Linux x64
Kernel: Linux 4.14.15-1-ARCH
Deepin Api Version: 3.1.20-1

Right click on flat dock on any icon. Same bug as @TheDroop mentioned.
Deepin logs are clear for that kind of interactions.
Cheers.

**Comment by Josephvb10** [comment]
Yup, still happening to me. Needs to be re-opened @JulianLai

**Comment by lbarbaglia** [comment]
Same thing here

**Comment by felixonmars** [comment]
Please try again with dtkwidget 2.0.6-2 and deepin-qt-dbus-factory 0.4.2-2.

**Comment by zameran** [comment]
Dear @felixonmars, thank you for a ...
Do you really call that fix?!
Just feature disabling = fix?
So. Thank you, anyway.

**Comment by felixonmars** [comment]
Did you really read the diff? What feature was disabled?

**Comment by Xeers** [comment]
Thank you. The dock now seems to work correctly.

**Comment by Xeers** [comment]
Dock options do not appear (pressing right mouse button)

**Comment by Xeers** [comment]
thank you very much

**Comment by CSAndrew** [comment]
It's happening again.
