### ISSUE TITLE
deepin-desktop-theme 警告:  gtk-update-icon-cache: The generated cache was invalid

### ISSUE THREAD

**Issue by wineee** [linuxdeepin/developer-center#4291]
### SUMMARY | 问题概要

报错的具体主题是 /usr/share/icons/flow

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
最新 commit f63dfe84fa8aff61b58ef6a8dae7f99a39ff74a4
```

### STEPS TO REPRODUCE | 复现步骤

gtk-update-icon-cache /usr/share/icons/flow

**Comment by justforlxz** [comment]
已修复。

**Comment by felixonmars** [comment]
Still present in 1.0.8

**Comment by wineee** [comment]
fix in https://github.com/linuxdeepin/deepin-desktop-theme/pull/29
