### ISSUE TITLE
【deepin_V23-beta】【一般】【有空】【集成测试】【dtk】hazy color/flow/macaron主题下文件管理器里桌面图标不跟随主题变换

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#4296]
### SUMMARY | 问题概要

hazy color/flow/macaron主题下文件管理器里桌面图标不跟随主题变换

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230508
libdtkgui5:5.6.10+rb2
```

### STEPS TO REPRODUCE | 复现步骤

1.在控制中心-个性化-主题切换系统主题为hazy color/flow/macaron这三种主题
2.打开文件管理器-计算机目录
3.观察我的目录-桌面图标样式展示

### OBSERVED RESULT | 观察到的结果

hazy color/flow/macaron主题下文件管理器里桌面图标不跟随主题变换

https://user-images.githubusercontent.com/96415804/236741588-0f89555c-0890-4e0a-936d-4aef3263aa40.mp4

### EXPECTED RESULT | 期望的结果

1.所有图标都跟随主题变换

**Comment by kegechen** [comment]
```bash

sudo apt install libdtkgui5-bin
# 切换主题后执行一下一下命令
$(dpkg -L libdtkgui5-bin | grep theme) --find "user-desktop"
```
@vivianxf  回归测试一下，貌似以前的 deepin-desktop-theme 主题包里面有的主题缺文件
```
apt policy deepin-desktop-theme
```

**Comment by vivianxf** [comment]
验证镜像:https://cdimage.uniontech.com/community/releases/23-Beta2/
libdtkgui5-bin:5.6.20
验证步骤:提单的步骤
验证现象:切换任意主题都可以同步图标状态
验证结果:通过
