### ISSUE TITLE
【deepin_V23_beta】【一般】【有空】【发散测试】【玲珑】从V23 alpha 升级到最新的 v23 beta后，启动器中出现多个相同的玲珑应用图标

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#4297]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Alpha/deepin-desktop-community-23-Alpha-amd64.iso
```

### PRE-REQUIREMENT | 预置条件

1. 安装镜像：https://cdimage.uniontech.com/community/releases/23-Alpha/deepin-desktop-community-23-Alpha-amd64.iso
2. 添加仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/stable/ beige main community commercial
deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial

### STEPS TO REPRODUCE | 复现步骤

1. 安装v23 alpha镜像
2. 添加仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/stable/ beige main community commercial
deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
3. 升级到最新的 v23 beta环境
4. 打开启动器 -  查看玲珑应用显示 

### OBSERVED RESULT | 观察到的结果

玲珑应用出现多个相同的图标

### EXPECTED RESULT | 期望的结果

玲珑应用均为唯一图标

**Comment by kamiyadm** [comment]
升级后调试AM和launcher，来自AM的数据是正常的，全屏和小窗口的图标数据是来自于launcher的m_fullscreenUsedSortedList和m_windowedUsedSortedList, 这两个变量初始化的时候会组合来自AM的数据和launcher自身缓存数据，可能会出现重复数据

**Comment by luodeepin** [comment]
【验证环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Alpha/deepin-desktop-community-23-Alpha-amd64.iso
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/stable/ beige main community commercial
deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-55/testing/ ./

包版本：dde-launcher   6.0.11
内核：6.1.11-amd64-desktop-hwe #23.01.00.10
【验证步骤】：问题单中描述的步骤

【验证结果】：通过
