### ISSUE TITLE
[deepin_V23-beta】【严重】【紧急】【发散测试】【DDE】deepin-daemon soundeffect 服务响应缓慢

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#4302]
### SUMMARY | 问题概要

必现问题

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230508
内核信息: Linux test-PC 6.1.11-amd64-desktop-hwe #23 SMP PREEMPT_DYNAMIC Mon Feb 27 17:25:36 CST 2023 x86_64 GNU/Linux
```

### PRE-REQUIREMENT | 预置条件

1、调整缩放后注销系统重新进入系统

### STEPS TO REPRODUCE | 复现步骤

1、第二次调整缩放，观察是否弹出注销的提示信息

### OBSERVED RESULT | 观察到的结果

1、再次调整缩放后无注销的提示信息，系统发生coredump

https://user-images.githubusercontent.com/62528742/236761772-621ba998-a1a0-4804-963a-10ca48582b5e.mp4

![微信图片_20230508151652](https://user-images.githubusercontent.com/62528742/236759810-67f263f2-1fd5-4fd5-8fb8-e8277f255dbf.jpg)

### EXPECTED RESULT | 期望的结果

1、可以正常多次调整缩放和注销系统

**Comment by Decodetalkers** [comment]
其实没有coredump,卡在dbus请求上了

**Comment by dengbo11** [comment]
后端接口测试正常, 需要看下Dbus 调用上

**Comment by BLumia** [comment]
- 关联： https://github.com/linuxdeepin/developer-center/issues/4238

**Comment by BLumia** [comment]
@Decodetalkers 确认相关修复合入并集成后走给测试就行

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0511镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230511
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0516镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
