### ISSUE TITLE
【deepin_V23_beta】【一般】【有空】【发散测试】【DDE】【桌面】双屏扩展模式下，设置壁纸时 副屏幕 白屏

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#4303]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Alpha/deepin-desktop-community-23-Alpha-amd64.iso
dde-session-shell 6.0.8
dde-session-ui 6.0.8
内核：Linux HaoSen-PC 6.1.11-amd64-desktop-hwe #23.01.00.10
```

### PRE-REQUIREMENT | 预置条件

1. 安装镜像：https://cdimage.uniontech.com/community/releases/23-Alpha/deepin-desktop-community-23-Alpha-amd64.iso
2. 仓库： deb https://ci.deepin.com/repo/deepin/deepin-community/stable/ beige main community commercial
deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial

### STEPS TO REPRODUCE | 复现步骤

1. 接入双屏幕 - 设置为扩展模式
2. 在主屏幕 点击鼠标右键 -  点击壁纸与屏保

### OBSERVED RESULT | 观察到的结果

2. 副屏幕白屏
![截图_选择区域_20230508153028](https://user-images.githubusercontent.com/96416089/236764874-14da3e56-6a47-422b-b0d2-968c7064a1de.png)

### EXPECTED RESULT | 期望的结果

副屏幕保持不变

**Comment by zccrs** [comment]
@dengbo11 今天解决

**Comment by dengbo11** [comment]
@luodeepin , 该问题在新版暂未复现, 壁纸和屏保启动慢的问题单独跟踪

**Comment by dengbo11** [comment]
白屏的原因是因为alpha原来设置的壁纸升级到beta后没有了

**Comment by zccrs** [comment]
不要直接关闭，等 @xuqi27837288 回归测试通过后让他关

**Comment by luodeepin** [comment]
deepin-wallpapers-nonfree  1.7.9
deepin-wallpapers 1.7.14
验证通过
![777](https://github.com/linuxdeepin/developer-center/assets/96416089/4261e7c5-5e2f-4d49-be8c-e6b07f116418)
