### ISSUE TITLE
Virtual keyboard

### ISSUE THREAD

**Issue by yunusem** [linuxdeepin/developer-center#431]
You guys may want to have a look at [this](https://github.com/E-Tahta/eta-keyboard) for future plans, it has full qt implementation backend and qml frontend.

Just wanted to inform.

Regards.

**Comment by hualet** [comment]
Thanks, will look into it :)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
