### ISSUE TITLE
【deepin_V23_beta】【一般】【有空】【集成测试】【DDE】【任务栏】dock 隐藏状态下，在控制中心多次添加和取消回收站，导致回收站图标在dock不显示

### ISSUE THREAD

**Issue by SuperEffie** [linuxdeepin/developer-center#4315]
### SUMMARY | 问题概要

关联集成：https://github.com/linuxdeepin/developer-center/issues/4311

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230508/deepin-23-beige-amd64-20230508-104056.iso
版本信息：dde-dock:6.0.14
```

### PRE-REQUIREMENT | 预置条件

任务栏状态设置为“一直隐藏”

### STEPS TO REPRODUCE | 复现步骤

1. 打开控制中心，个性化-桌面-插件区域，勾选、取消回收站两次，再勾选回收站
2. 鼠标移动至任务栏，查看任务栏中回收站图标是否显示

### OBSERVED RESULT | 观察到的结果

任务栏中回收站图标不显示
![回收站图标](https://user-images.githubusercontent.com/58986464/237005968-673ae6da-7067-4d8f-ab90-aa85b313f8d5.gif)

### EXPECTED RESULT | 期望的结果

任务栏中显示回收站图标

**Comment by tsic404** [comment]
dock 已重构，请在最新版本上回归

**Comment by luodeepin** [comment]
验证通过
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240715/deepin-23-beige-rc2-amd64-20240715-011014.iso
dde-shell 0.0.28
dde-launchpad 0.8.0
![截图_选择区域_20240718145306](https://github.com/user-attachments/assets/3903b345-0a0d-4545-a7a7-2041dbc2eae4)
