### ISSUE TITLE
内核6.1| 23.01.00.12 版本集成

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#4318]
deb [trusted=yes] https://ci.deepin.com/repo/deepin/deepin-community/obs-repos/ kernel  main

**Comment by Zeno-sole** [comment]
包名 | 版本
-- | --
linux-upstream | 23.01.00.12

**Comment by Zeno-sole** [comment]
内核配置文件更新支持特定amd平台音频设备 
< CONFIG_SND_SOC_AMD_ACP6x=m
< CONFIG_SND_SOC_AMD_YC_MACH=m

**Comment by xuqi27837288** [comment]
@luodeepin 麻烦验证后反馈下验证结论~

**Comment by luodeepin** [comment]
测试不通过
更新内核后进不了系统

**Comment by luodeepin** [comment]
测试通过
输入声音正常
