### ISSUE TITLE
应用商店部分图标颜色不正常【deepin23内测】【无空】

### ISSUE THREAD

**Issue by wlly-lzh** [linuxdeepin/developer-center#4324]
### SUMMARY | 问题概要

如题所示，部分区域变成黑色

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin23内测版
```

### PRE-REQUIREMENT | 预置条件

打开应用商店搜索软件

### STEPS TO REPRODUCE | 复现步骤

打开应用商店

### OBSERVED RESULT | 观察到的结果

标题栏是黑色的

### EXPECTED RESULT | 期望的结果

保持正常

### ADDITIONAL INFORMATION | 额外补充

无

**Comment by BLumia** [comment]
额...图呢？

**Comment by wlly-lzh** [comment]
---原始邮件---
发件人: "Gary ***@***.***&gt;
发送时间: 2023年5月9日(周二) 晚上11:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [linuxdeepin/developer-center] 应用商店部分图标颜色不正常【deepin23内测】【无空】 (Issue #4324)




 
额...图呢？

**Comment by BLumia** [comment]
好像直接回复邮件并不会上传图片。方便直接在 https://github.com/linuxdeepin/developer-center/issues/4324 提供下相关截图吗？我们没能复现这个问题。

**Comment by BLumia** [comment]
仍然缺少截图，无法在最新环境下复现，关闭处理。若仍然能在最新环境下复现，可开新的 issue 重新反馈。

（ps. 附图的回复请直接从 GitHub 进行回复，不要使用邮件的形式，因为邮件的图不会在 Issue 里显示，大家都看不到）

**Comment by Decodetalkers** [comment]
哦，这个是dtk的问题吧， @kegechen

**Comment by kegechen** [comment]
> 哦，这个是dtk的问题吧， @kegechen , deepinid插件也出现了，不过先上传下图片
> 
> 诶，may啊，那不关联呢，没看到日期

不一定，只是说可能。暂时还没定位呢
