### ISSUE TITLE
File manager Deepin and Smartphone

### ISSUE THREAD

**Issue by Xeers** [linuxdeepin/developer-center#433]
When I select many images of the internal storage of my smartphone and paste them into a folder of the Deepin File Manager, they are never copied all.
This error may also have other file formats.
Example: I select 120 .jpeg on the smartphone, copy and paste, in Deepin File Manager there are only 20

**Comment by Xeers** [comment]
The File Manager of Deepin is very basic, it does not inform when there is little space on the hard disk, it stops copying files on hard drives with 50 Gb free, the informative messages do not appear complete in Spanish, it is very slow when copying files from a hard drive to another, the information it gives is very basic, you can not move the panels of the windows, ....

**Comment by felixonmars** [comment]
Are you copying files using MTP protocol? You might want to confirm if nautilus has the same problem - in such case it is a problem lying somewhere between gvfs/gvfs-mtp/libmtp.

Alternatively, you may want to select USB mass storage mode from your phone which basically works with any PC operational systems.

**Comment by Xeers** [comment]
Yes, I use in the file transfer "Multimedia device (MTP)". select USB mass storage mode from your phone? In BIOS?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
