### ISSUE TITLE
Screen hangs when a dock item is right-clicked

### ISSUE THREAD

**Issue by ashok-arora** [linuxdeepin/developer-center#434]
Hello, 
Every time I right-click on any of the dock items, the whole tty hangs, and I have to switch tty and pkill it. 
All the applications stop working but the cursor can still move around. 
This is the output of uname -a in case it helps!
`Linux manjaro 4.14.5-1-MANJARO #1 SMP PREEMPT Sun Dec 10 21:18:12 UTC 2017 x86_64 GNU/Linux
`

**Comment by felixonmars** [comment]
What's your installed version of deepin-api? This should have been fixed in 3.1.18.1-1 some time ago.

**Comment by Josephvb10** [comment]
Still happening on deepin-api 3.1.20-1

**Comment by felixonmars** [comment]
Please try again with dtkwidget 2.0.6-2 and deepin-qt-dbus-factory 0.4.2-2.

**Comment by hualet** [comment]
Should be fixed now.
