### ISSUE TITLE
图形图像组玲珑应用集成

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#4346]
仓库地址： ll-cli repo modify http://10.0.36.228:9001/ --name develop-snipe

**Comment by Zeno-sole** [comment]
包名|版本
--|--
org.deepin.image.viewer|6.0.2
org.deepin.album|6.0.3
org.deepin.editor|6.0.9

**Comment by Zeno-sole** [comment]
https://github.com/linuxdeepin/developer-center/issues/4222 https://github.com/linuxdeepin/developer-center/issues/4203

**Comment by vivianxf** [comment]
测试结论：验证通过
1.仓库添加成功，包安装成功
2.应用功能正常使用
2.issue #4222 #4203验证通过 新增issue# 不影响功能正常使用
