### ISSUE TITLE
[Deepin-Arch] Steam does not detect usb gamepad 

### ISSUE THREAD

**Issue by Xeers** [linuxdeepin/developer-center#435]
I usually play with the keyboard, but today I was going to play a game of Steam in Deepin-Arch and the gamepad was not detected. In previous occasions the gamepad had always been detected (type Xbox 360).
I have tried to restart, reinstall Steam, try several kernels, install xboxdrv, steamos-xpad-dkms ... but Steam still does not detect it.
Antimicro and jstest-gtk-git (programs to calibrate and assign buttons) detect the gamepad.
The gamepad works perfectly on Steam (Windows), other gamepads are detected correctly on Steam Deepin-Arch.
(gnome-logs) :
xpad 9-4:1.0: xpad_try_sending_next_out_packet - usb_submit_urb failed with result -19

$ modinfo xpad
filename:       /lib/modules/4.14.8-1-ARCH/kernel/drivers/input/joystick/xpad.ko.xz
license:        GPL
description:    X-Box pad driver
author:         Marko Friedemann <mfr@bmx-chemnitz.de>
srcversion:     7BB0CF51690E94B2A225FCD
alias:          usb:v24C6p*d*dc*dsc*dp*icFFisc47ipD0in*
alias:          usb:v24C6p*d*dc*dsc*dp*icFFisc5Dip81in*
alias:          usb:v24C6p*d*dc*dsc*dp*icFFisc5Dip01in*
alias:          usb:v1BADp*d*dc*dsc*dp*icFFisc5Dip81in*
alias:          usb:v1BADp*d*dc*dsc*dp*icFFisc5Dip01in*
alias:          usb:v1689p*d*dc*dsc*dp*icFFisc5Dip81in*
alias:          usb:v1689p*d*dc*dsc*dp*icFFisc5Dip01in*
alias:          usb:v162Ep*d*dc*dsc*dp*icFFisc5Dip81in*
alias:          usb:v162Ep*d*dc*dsc*dp*icFFisc5Dip01in*
alias:          usb:v15E4p*d*dc*dsc*dp*icFFisc5Dip81in*
alias:          usb:v15E4p*d*dc*dsc*dp*icFFisc5Dip01in*
alias:          usb:v1532p*d*dc*dsc*dp*icFFisc47ipD0in*
alias:          usb:v1532p*d*dc*dsc*dp*icFFisc5Dip81in*
alias:          usb:v1532p*d*dc*dsc*dp*icFFisc5Dip01in*
alias:          usb:v146Bp*d*dc*dsc*dp*icFFisc5Dip81in*
alias:          usb:v146Bp*d*dc*dsc*dp*icFFisc5Dip01in*
alias:          usb:v1430p*d*dc*dsc*dp*icFFisc5Dip81in*
alias:          usb:v1430p*d*dc*dsc*dp*icFFisc5Dip01in*
alias:          usb:v12ABp*d*dc*dsc*dp*icFFisc5Dip81in*
alias:          usb:v12ABp*d*dc*dsc*dp*icFFisc5Dip01in*
alias:          usb:v11C9p*d*dc*dsc*dp*icFFisc5Dip81in*
alias:          usb:v11C9p*d*dc*dsc*dp*icFFisc5Dip01in*
alias:          usb:v0F0Dp*d*dc*dsc*dp*icFFisc47ipD0in*
alias:          usb:v0F0Dp*d*dc*dsc*dp*icFFisc5Dip81in*
alias:          usb:v0F0Dp*d*dc*dsc*dp*icFFisc5Dip01in*
alias:          usb:v0E6Fp*d*dc*dsc*dp*icFFisc47ipD0in*
alias:          usb:v0E6Fp*d*dc*dsc*dp*icFFisc5Dip81in*
alias:          usb:v0E6Fp*d*dc*dsc*dp*icFFisc5Dip01in*
alias:          usb:v07FFp*d*dc*dsc*dp*icFFisc5Dip81in*
alias:          usb:v07FFp*d*dc*dsc*dp*icFFisc5Dip01in*
alias:          usb:v0738p*d*dc*dsc*dp*icFFisc47ipD0in*
alias:          usb:v0738p4540d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0738p*d*dc*dsc*dp*icFFisc5Dip81in*
alias:          usb:v0738p*d*dc*dsc*dp*icFFisc5Dip01in*
alias:          usb:v06A3p*d*dc*dsc*dp*icFFisc5Dip81in*
alias:          usb:v06A3p*d*dc*dsc*dp*icFFisc5Dip01in*
alias:          usb:v056Ep*d*dc*dsc*dp*icFFisc5Dip81in*
alias:          usb:v056Ep*d*dc*dsc*dp*icFFisc5Dip01in*
alias:          usb:v046Dp*d*dc*dsc*dp*icFFisc5Dip81in*
alias:          usb:v046Dp*d*dc*dsc*dp*icFFisc5Dip01in*
alias:          usb:v045Ep*d*dc*dsc*dp*icFFisc47ipD0in*
alias:          usb:v045Ep*d*dc*dsc*dp*icFFisc5Dip81in*
alias:          usb:v045Ep*d*dc*dsc*dp*icFFisc5Dip01in*
alias:          usb:v044Fp*d*dc*dsc*dp*icFFisc5Dip81in*
alias:          usb:v044Fp*d*dc*dsc*dp*icFFisc5Dip01in*
alias:          usb:v*p*d*dc*dsc*dp*ic58isc42ip00in*
depends:        usbcore,led-class,ff-memless
intree:         Y
name:           xpad
vermagic:       4.14.8-1-ARCH SMP preempt mod_unload modversions
parm:           dpad_to_buttons:Map D-PAD to buttons rather than axes for unknown pads (bool)
parm:           triggers_to_buttons:Map triggers to buttons rather than axes for unknown pads (bool)
parm:           sticks_to_null:Do not map sticks at all for unknown pads (bool)
parm:           auto_poweroff:Power off wireless controllers on suspend (bool)

**Comment by hualet** [comment]
Sorry @Xeers , it's not the right place to report Arch kernel issues.

**Comment by Xeers** [comment]
I am sorry. I discovered that the problem is in Steam
