### ISSUE TITLE
输入法、文件管理器

### ISSUE THREAD

**Issue by hwch** [linuxdeepin/developer-center#4361]
### SUMMARY | 问题概要

1. 在Wayland模式下无法使用搜狗输入法
2. 在任何模式下无法打开文件浏览器

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
Distributor ID: Deepin                                                     
Description:    Deepin 23                                                  
Release:        23                                                         
Codename:       beige
```

### STEPS TO REPRODUCE | 复现步骤

1. 开始选择Wayland模式进入桌面
2. 在任何输入框都无法使用搜狗输入法
3. 在任何模式下无法打开文件浏览器

**Comment by BLumia** [comment]
首先建议不同的问题开成不同的 issue，不然确实不方便跟进。

其次 搜狗输入法 不是 deepin 的应用，是第三方的闭源应用，所以搜狗的问题我们是没法处理的。

> 在任何模式下无法打开文件浏览器

我在 v23 目前的开发环境下无法复现此问题。可以提供下详细信息吗？对诊断问题有帮助的信息有这些：

1. `dde-file-manager` 版本信息（提供 `apt policy dde-file-manager` 输出即可）
2. 从终端输入 `dde-file-manager` 并回车的形式启动，在输出中可以看到什么异常吗？是否可以提供相关输出？
3. 是崩溃了吗？`coredumpctl list` 中是否存在对应的崩溃信息？有的话，是否可以提供崩溃对应的调用堆栈？

感谢。

**Comment by hwch** [comment]
你好，在又一次更新后，无法打开文件浏览器的问题得到解决。那咱们有自带的中文输入法吗？

**Comment by hwch** [comment]
安装fcitx5，已解决，谢谢
