### ISSUE TITLE
dde-introduction 6.0.6集成

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#4365]
### Package information | 软件包信息

包名 | 版本
--  | --
dde-introduction | 6.0.6

### Package repository address | 软件包仓库地址

deb  [trusted=yes] https://aptly.uniontech.com/pkg/beige-v2/release-candidate/ZGRlLWludHJvZHVjdGlvbjIwMjMtMDUtMTIgMTc6MDE6Mjc/  unstable main

### Changelog | 更新信息

解决欢迎视屏加载卡顿问题

### ADDITIONAL INFORMATION | 额外补充
https://github.com/linuxdeepin/developer-center/issues/3765

**Comment by xuqi27837288** [comment]
【环境】：
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230512
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【结论】：
测试通过，暂无严重问题及影响
