### ISSUE TITLE
【deepin_V23_beta】【一般】【有空】【发散测试】【DDE】【任务栏】快捷面板中的 截图录屏 图标字体与其他图标字体大小不一致

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#4376]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230515/deepin-23-beige-amd64-20230515-160220.iso
dde-dock       6.0.16
```

### PRE-REQUIREMENT | 预置条件

1. 安装镜像：镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230515/deepin-23-beige-amd64-20230515-160220.iso

### STEPS TO REPRODUCE | 复现步骤

1. 点击任务栏上的快捷面板图标 - 查看界面中图标显示

### OBSERVED RESULT | 观察到的结果

1. 快捷面板中的 截图录屏 图标字体与其他图标字体大小不一致
![截图_选择区域_20230515163737](https://github.com/linuxdeepin/developer-center/assets/96416089/a374447f-443c-4459-806a-a30112ed1c56)

### EXPECTED RESULT | 期望的结果

1. 快捷面板中的 截图录屏 图标字体与其他图标字体大小保持一致

**Comment by BLumia** [comment]
发现和下面两个 issue 重复汇报了，但是把这个 issue 里的两个问题分开提出来的：

- https://github.com/linuxdeepin/developer-center/issues/4644
- https://github.com/linuxdeepin/developer-center/issues/4646

我关闭掉这个重复的，在上面链接里的这两个里跟进吧。
