### ISSUE TITLE
【deepin_V23_beta】【一般】【有空】【发散测试】【DDE】【任务栏】缩放在1.25,字体大小为20时，电脑协同的面板中 电脑协同显示不全

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#4382]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230515/deepin-23-beige-amd64-20230515-160220.iso

dde-dock       6.0.16
```

### PRE-REQUIREMENT | 预置条件

1. 安装镜像：镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230515/deepin-23-beige-amd64-20230515-160220.iso
2. 缩放比为 1.25 ， 字体大小为20

### STEPS TO REPRODUCE | 复现步骤

1. 点击任务栏的快捷面板 - 点击 电脑协同 图标 - 查看界面显示

### OBSERVED RESULT | 观察到的结果

1. 界面中的 电脑协同 显示不全
![录屏_选择区域_20230516093816](https://github.com/linuxdeepin/developer-center/assets/96416089/73527935-86f1-479d-b4da-f8a3c73957c9)

### EXPECTED RESULT | 期望的结果

界面内容显示完整且正确

**Comment by Zeno-sole** [comment]
仓库地址： deb [trusted=yes] http://10.20.52.112/test/ unstable main

**Comment by luodeepin** [comment]
验证通过

**Comment by luodeepin** [comment]
![Image](https://github.com/linuxdeepin/developer-center/assets/96416089/2623b1f2-265c-4d29-ac36-0b29ef7c801f)
