### ISSUE TITLE
Deepin-Arch freezes

### ISSUE THREAD

**Issue by Xeers** [linuxdeepin/developer-center#439]
I installed the latest Deepin-Arch updates and now as soon as I click on the Dock, Deepin freezes. I can not use the operating system.I have restarted several times, tested several kernels, the grub does not report errors,...
Regards

**Comment by felixonmars** [comment]
What's your installed version of deepin-api? This should have been fixed quite some time ago. Are you using an outdated mirror?

**Comment by Xeers** [comment]
I can not see it, I'm in Windows but I update Arch-Deepin every day.

**Comment by felixonmars** [comment]
So lemme confirm - you are using Arch, not Manjaro, right?

**Comment by Xeers** [comment]
I use Arch no Manjaro. Deepin api 3.1.18.1-1
Mystery! Now the Dock does not freeze and Deepin works properly again. Mmmm sorry for the inconvenience

**Comment by aiamuzz** [comment]
@Xeers ... hahahaha ... its happened to me too ... there is an issue ... and suddenly for no reason ... the issue disappears on you !
