### ISSUE TITLE
deepin-movie/deepin-screenshot/deepin-terminal svg 资源文件名称问题

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/developer-center#44]
现在有一些包安装了中文的文件名，这会让 bsdtar 解压的时候报错，希望可以处理：
```
community/deepin-movie 2.3.0.20151102-1
usr/share/dman/deepin-movie/en_US/\357\274\237.svg
community/deepin-screenshot 3.1.7-1
usr/share/dman/deepin-screenshot/en_US/icon/\357\274\237.svg
usr/share/dman/deepin-screenshot/zh_CN/icon/\357\274\237.svg
community/deepin-terminal 1.1.4-1
usr/share/dman/deepin-terminal/en_US/icon/\357\274\237.svg
usr/share/dman/deepin-terminal/zh_CN/icon/\357\274\237.svg
```
"\357\274\237" 对应的是中文问号 "？"

以上是 archlinux 上打包遇到的问题，麻烦 @hualet 统一处理下吧

@felixonmars

**Comment by hualet** [comment]
是文档资源的问题，我让蒋文帮忙处理下吧。

**Comment by hualet** [comment]
deepin-screenshot  https://cr.deepin.io/11313
deepin-terminal https://cr.deepin.io/11314

deepin-movie目前两个分支 master是合并了 2.3的内容，我提交了一个 https://cr.deepin.io/11315
release/2.2.2 我提交了一个 https://cr.deepin.io/11316
