### ISSUE TITLE
Booting into Deepin seems like a game of dice ... roll it to see if you boot into it ... Annoyed AND Frustrated !!!

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#440]
Hi,

I have this nagging boot issue ... I am currently on Deepin 15.5 ...
(I started from Deepin 15.4 ... upgraded to to 15.5 Beta through your update pushes ... and now on Deepin 15.5 upgraded through your update pushes)

Earlier my deepin 15.4 ... reboot/start would take me to the point which reads **"You are in emergency mode"** and would not proceed beyond what is seen in the snapshot below ... 

![emergency mode](https://user-images.githubusercontent.com/3283676/34417545-2b1c57ee-ec1f-11e7-8748-1fa7bf09c120.png)

I have to keep hitting Ctrl+Alt+Del every time i get stuck ... it would reboot to the same screen repeatedly unless i was lucky ... some times just hitting Ctrl+D at the above point of boot freeze ... would luckily boot into the OS ... but this(Ctrl+D) no longer works on Deepin 15.5.
;
;
;
Enter new type of error ... After i upgraded to Deepin 15.5 Beta ... i hit a new type of boot error ... this new error persists till date ... and it is making my life miserable ... the boot freezes at this point (as shown in the snapshot) ... at the boot message **' [OK] Started IIO sensor Proxy Service' ...**

![iio sensor freeze](https://user-images.githubusercontent.com/3283676/34417881-e4c0d21e-ec20-11e7-8cd8-78759bdf7f30.jpeg)
;
;
;
things i would do out of desperation every time i am stuck at the above point ... when i have no option boot to reboot the OS either while testing/reporting issues here on Github across your many packages ... or ... after an update is pushed out by you people ... 

1. when repeated attempts by hitting Ctrl+Alt+Del would fail at the stuck boot(at the 'emergency mode' or 'IIO sensor message') ... sometimes it would boot into the OS ... if it doesn't ... this is what i do next.

2. I would boot into my old Ubuntu 14.04 install(Ubuntu would boot without problems with the very same hardware) ... I would restart from inside Ubuntu and surprisingly the system would boot into the Deepin 15.04 which is my defaul OS in grub ... this does not work always ... when this too fails i would try the next method ...

3. Hit 'c' at the grub for the grub command and run the following ...
linux (hd0,gpt4)/boot/vmlinuz ... root=/dev/sda4 foo bar
initrd (hd0,gpt4)/boot/initrd ... 
boot
... If i was lucky i would boot into the Deepin OS ... this too did not work everytime ... When this failed too ... i would have no choice but to keep attempting the above ... and for 'Luck' to shine no me ... 
;
;
;
I keep repeating between the 3 methods i have mentioned above and ONLY when I am lucky ... i would boot into the OS !!!

some boot freeze screenshots i face ... please find them below ...

![emergency mode-2](https://user-images.githubusercontent.com/3283676/34418212-c3cfbb54-ec22-11e7-8b70-5241265e3e80.jpeg)

![emergency mode-3](https://user-images.githubusercontent.com/3283676/34418215-c7105e72-ec22-11e7-98ae-5a3dea9baa22.jpeg)

I seriously like to get this boot nightmare resolved ... As a creature of Habit i tend to put my system on standby for days on end ... its because of this habit ... i have been able to live with Deepin OS for so long .

**PS : I have setup up my entire work environment on the Deepin OS 15.5 ... this is my primary work machine. So i can't afford to reinstall the OS ... so whatever data you want i will provide ... i just can't setup my work machine from scratch. Please keep that in mind while you look into my issue.**

**Comment by aiamuzz** [comment]
> OK, which point did it stuck at BTW, maybe we can help you with it.

above comment from [here](https://github.com/linuxdeepin/developer-center/issues/665#issuecomment-439787845) 

@hualet ... i really hope you help me with this ...

I NEED TO KNOW WHAT THE PROBLEM IS AND HAVE THIS ISSUE FIXED ... I MAY BE THE ONLY ONE FACING THIS ISSUE BUT IF THE 'DEEPIN TEAM' DOES NOT BOTHER LOOKING INTO IT ... 

BY NOT LOOKING INTO THIS ISSUE I FACE ... YOU ARE BASICALLY ASKING ME TO 'GET LOST' ... 'QUITE USING DEEPIN OS' ... ARE YOU ???

FYI ... THIS IS THE LONGEST AND THE MOST IRRITATING ISSUE I HAVE WITH DEEPIN OS ... WHICH IS UNRESOLVED ... THE TEAM IS NOT INTERESTED IN HELPING ME FIX IT OR AT LEAST IDENTIFY IT !!!


@hualet ... as you have PROMISED TO HELP ... PLEASE FIND MY CURRENT STATE OF FRUSTRATION !!!


As you know i have been a regular contributor to Deepin OS in the form of reporting bugs/issues and suggesting features and changes ... in this effort i have installed deepin on 3 partitions ...

1. the Daily driver installation which i have been using since Deepin 15.6 ... upgraded to Deepin 15.7 ... upgraded to Deepin 15.8 ... WHICH IS CURRENTLY STUCK AT BOOT !!!

2. I have cloned this partition from deepin recovery as a backup/testing install ... 

3. Frustrated with this booting ISSUE i re-installed a fresh Deepin 15.8 yesterday ... and FRUSTRATINGLY EVEN THIS IS NOT BOOTING PROPERLY ...

**With 3 Deepin installs on my system ... i have no option but to roll the dice, raise my hands heaven wards and pray that i boot into the OS ... ITS FRUSTRATING .... AND WHAT'S MORE FRUSTRATING IS THAT 'YOUR TEAM' HASN'T BOTHERED TO LOOK INTO THIS ISSUE I FACE !!!

IF YOU WANT ME TO ABANDON DEEPIN OS ... THEN PLEASE TELL ME AND I'LL SWITCH TO SOME OTHER LINUX DISTRO THAT DOES NOT GIVE ME THIS FRUSTRATING ISSUE !!!**

@hualet  .... please find the photo of the recent booting issues ... 

![whatsapp image 2018-11-19 at 12 52 04 pm](https://user-images.githubusercontent.com/3283676/48693008-0f8e3a80-ebfe-11e8-9184-b2f426303ca1.jpeg)

![whatsapp image 2018-11-19 at 12 55 02 pm](https://user-images.githubusercontent.com/3283676/48693011-0f8e3a80-ebfe-11e8-98b3-ff843f185ce5.jpeg)

**Comment by aiamuzz** [comment]
I HAD RAISED THIS ISSUE THE FIRST TIME ON THE FORUM ... BUT NOBODY REALLY HELP BE FIX / RESOLVE IT !!!   This is how long this issue has been frustrating me !!!

https://bbs.deepin.org/forum.php?mod=viewthread&tid=148028&extra=

**Comment by BLumia** [comment]
I do really think [we need a issue reporting guideline / code of condent](http://netiquette.wikia.com/wiki/Rule_number_2_-_Do_not_use_all_caps). @hualet

**Comment by aiamuzz** [comment]
@BLumia  ...  i am not somebody who loses his cool ... but i guess you can imagine ... with 2 partitions of Deepin OS already present and third fresh install last night resulting in the same issue ... and no help from your team for so long ... kind of blew my lid off ... 

A little support is all i have been expecting ... from the team !!! ...
its a nightmare whenever i end up with this issue ... 

Hopefully somebody will help be slay this ... boot madening monster !!!

**Comment by aiamuzz** [comment]
@BLumia ... @hualet ...

I was hoping you could sort of add a tool / application which will collect boot information of even 'failed boots' to help identify the issue ... If you go through all those threads ... you can see that i have tried so many things ... but the log for all those unsuccessful boots aren't recorded ... probably because when i hit Ctrl+Alt+Del in the stuck state or hard boot ... the log for that failed boot is lost and not recorded anywhere ...

Really appreciated your help in fixing this issue ...

**Comment by aiamuzz** [comment]
@BLumia ... @hualet  ...

**Is there any way i can record boot logs, journalctl or any other system of logging that captures fail boots ... by failed boots i mean in my situation where the only option i have is to issue 'Ctrl+Alt+Del' or a Magic Sysrq 'b'(boot) command to get out of the boot freeze ?**

**Comment by hualet** [comment]
@aiamuzz Have you considered that it may be that your hard drive is damaged somehow?

**Comment by aiamuzz** [comment]
> @aiamuzz Have you considered that it may be that your hard drive is damaged somehow?

ok ... If the hard drive is damaged ... how come the Ubuntu Installation that i had on another partition boots 100% ... never have i come across this issue on ubuntu ... 

In fact whenever i have this issue booting into deepin ... i boot into ubuntu and restart the machine from there and deepin boots up almost every time ... If hard disk was the problem even ubuntu should not be booting up isn't it ?

moreover all partitions are mounted and and i am able to access and write data into them ... if hard disk was the problem then shouldn't i have had issues mounting partition and accessing them ?

**Is there any way to disable/skip certain tests on boot ... one by one ... and attempt boot ... that way i could eliminate each hardware and identify the culprit even if its a hard disk ...**

**Comment by aiamuzz** [comment]
i suspect there is some hardware or process that the ubuntu is configured to ignore or consider less critical to stall boot up may be and Deepin may have a tighter screening of the same which may be causing this boot issue ... ?

**Comment by felixonmars** [comment]
You can query the journal using "-b“ switch to fetch logs for individual boots. `journalctl -b -1` will give you the logs of last boot, after you hit C-A-Del and got a successful reboot.

**Comment by aiamuzz** [comment]
> You can query the journal using "-b“ switch to fetch logs for individual boots. journalctl -b -1 will give you the logs of last boot, after you hit C-A-Del and got a successful reboot.

@felixonmars  ... the problem is 'Ctrl+Alt+Del' does not boot into the OS ... like i said its a roll of dice ... there is no way to say how many time the boots fails and how many 'Ctrl+Alt+Del' i may have to hit ... and luckily when i boot into it ... the journal has record of only the last successful boot ... there is absolutely no record of all those boots that have failed ... is there any setting or configuration where i can force the journal to record logs of all failed boots logs before hitting 'Ctrl+Alt+Del' ?

**Comment by felixonmars** [comment]
```
the journal has record of only the last successful boot ... there is absolutely no record of all those boots that have failed```

I really doubt that. Please try a few numbers with the "-b" switch and look into the logs carefully. "-b -1" means last boot, and "-b -2" means the one before last one, so on and so forth.

**Comment by hualet** [comment]
What if you hit Ctrl-C to stop all the file system checks?  Will it boot? And you can also try to remove warm-sched package, and see if it solves the problem.

**Comment by aiamuzz** [comment]
> I really doubt that. Please try a few numbers with the "-b" switch and look into the logs carefully. "-b -1" means last boot, and "-b -2" means the one before last one, so on and so forth.

@felixonmars ... i have tried looking for it ... and going by the time stamps in the log files seems the only logs are for the last boot that was successful ... you know its hard to miss so many failed boots ... but i'll keep an eye on my next boot.

Currently i have not booted ... until i set or change something in this lucky login i currently have ...

> What if you hit Ctrl-C to stop all the file system checks? Will it boot? And you can also try to remove warm-sched package, and see if it solves the problem.

@hualet ... I googled it some where which said ... if i boot with the 'fastboot' flag ... it skips the disk check ... so ideally if it was a hard disk being faulty ... skipping it, should have booted up the system all the time ... but its not happening so ...

Could you elaborate on how do i remove 'warm-sched' package ?

**Comment by aiamuzz** [comment]
@hualet ... @felixonmars  ... if you promise to see this issue through(be responsive) ...

i'll try everything ... i'll reboot my system before i go to bed ... and leave it in the stuck state for the whole night ... just to see if the disk check will really complete and boot up or its some other issue ...

**Comment by hualet** [comment]
> @hualet ... @felixonmars ... if you promise to see this issue through(be responsive) ...
> 
> i'll try everything ... i'll reboot my system before i go to bed ... and leave it in the stuck state for the whole night ... just to see if the disk check will really complete and boot up or its some other issue ...

Sorry, we had a whole-day meeting yesterday. you can remove warm-sched by running this command
> sudo apt purge warm-sched

**Comment by aiamuzz** [comment]
> sudo apt purge warm-sched

How do i run this as i am unable to boot into the upgraded OS ?
Can i run the command from inside the Deepin Recovery boot ? If so do let me know on the procedure to specifically run it on `/dev/sda4` where my upgraded OS resides ... and isn't booting anymore ...

**Comment by aiamuzz** [comment]
@hualet ...

can i run the command `sudo apt purge warm-sched` in emergency mode while attempting to boot into my `dev/sda4` install ?
or 
i have heard of chroot ... will that be another way to run this command into the affected install ?

**Comment by aiamuzz** [comment]
ok ... i attempted to boot into emergency by adding a boot parameter 'single' ... and i booted into 'emergency mode' ... ran the command you suggested ... it says the following packages will be removed ...
i did not go ahead with the removal and hit a Ctrl+D to boot ... and turns out i was lucky and my system booted into my /dev/sda4 install ...

![whatsapp image 2018-11-21 at 11 52 03 pm](https://user-images.githubusercontent.com/3283676/48861512-bd117180-ede9-11e8-8b80-7b013f0bec7f.jpeg)

now that i am logged into the problematic install out of sheer luck ... @hualet  ... Do you want me to uninstall/remove the packages listed in the screenshot ?

**Comment by hualet** [comment]
> ok ... i attempted to boot into emergency by adding a boot parameter 'single' ... and i booted into 'emergency mode' ... ran the command you suggested ... it says the following packages will be removed ...
> i did not go ahead with the removal and hit a Ctrl+D to boot ... and turns out i was lucky and my system booted into my /dev/sda4 install ...
> 
> ![whatsapp image 2018-11-21 at 11 52 03 pm](https://user-images.githubusercontent.com/3283676/48861512-bd117180-ede9-11e8-8b80-7b013f0bec7f.jpeg)
> 
> now that i am logged into the problematic install out of sheer luck ... @hualet ... Do you want me to uninstall/remove the packages listed in the screenshot ?

Yes, that' s the package to be removed. And if you boot into the system please get the system log as @felixonmars had suggested, that will be much more helpful.

**Comment by hualet** [comment]
> ok ... i just ran that command which removed those packages ...
> 
> @felixonmars ... please find the output of journal for the boot entries ... `journalctl -b` after my dice rolled a jackpot ... i couldn't login to `/dev/sda4` installation after i had ran that update ...
> 
> ```
> Nov 22 01:33:55 ALHAMDULILLAH15 systemd[8241]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
> Nov 22 01:33:55 ALHAMDULILLAH15 systemd[8241]: Listening on GnuPG cryptographic agent and passphrase cache.
> Nov 22 01:33:56 ALHAMDULILLAH15 redshift[8941]: Trying location provider `geoclue2'...
> Nov 22 01:33:56 ALHAMDULILLAH15 redshift[8941]: Using provider `geoclue2'.
> Nov 22 01:33:56 ALHAMDULILLAH15 redshift[8941]: `RANDR Query Version' returned error -1
> Nov 22 01:33:56 ALHAMDULILLAH15 redshift[8941]: Initialization of randr failed.
> Nov 22 01:33:56 ALHAMDULILLAH15 redshift[8941]: Trying next method...
> Nov 22 01:33:56 ALHAMDULILLAH15 redshift[8941]: X request failed: XOpenDisplay
> Nov 22 01:33:56 ALHAMDULILLAH15 redshift[8941]: Initialization of vidmode failed.
> Nov 22 01:33:56 ALHAMDULILLAH15 redshift[8941]: Trying next method...
> Nov 22 01:33:56 ALHAMDULILLAH15 redshift[8941]: No more methods to try.
> Nov 22 01:33:55 ALHAMDULILLAH15 systemd[8241]: Listening on GnuPG network certificate management daemon.
> Nov 22 01:33:55 ALHAMDULILLAH15 systemd[8241]: Reached target Paths.
> Nov 22 01:33:55 ALHAMDULILLAH15 systemd[8241]: Reached target Timers.
> Nov 22 01:33:56 ALHAMDULILLAH15 redshift[9209]: Trying location provider `geoclue2'...
> Nov 22 01:33:56 ALHAMDULILLAH15 redshift[9209]: Using provider `geoclue2'.
> Nov 22 01:33:55 ALHAMDULILLAH15 systemd[8241]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
> Nov 22 01:33:55 ALHAMDULILLAH15 systemd[8241]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
> Nov 22 01:33:55 ALHAMDULILLAH15 systemd[8241]: Reached target Sockets.
> Nov 22 01:33:55 ALHAMDULILLAH15 systemd[8241]: Reached target Basic System.
> Nov 22 01:33:55 ALHAMDULILLAH15 systemd[8241]: Started Redshift display colour temperature adjustment.
> Nov 22 01:33:55 ALHAMDULILLAH15 systemd[8241]: Reached target Default.
> Nov 22 01:33:55 ALHAMDULILLAH15 systemd[8241]: Startup finished in 1.926s.
> Nov 22 01:33:56 ALHAMDULILLAH15 systemd[8241]: redshift.service: Main process exited, code=exited, status=1/FAILURE
> Nov 22 01:33:56 ALHAMDULILLAH15 systemd[8241]: redshift.service: Failed with result 'exit-code'.
> Nov 22 01:33:56 ALHAMDULILLAH15 systemd[8241]: redshift.service: Service hold-off time over, scheduling restart.
> Nov 22 01:33:56 ALHAMDULILLAH15 systemd[8241]: redshift.service: Scheduled restart job, restart counter is at 1.
> ```
> I'll try to boot up and see if the issue repeats or i'll be able to boot successfully ...

`journalctl -b` gives the log of good booting which is useless to debug booting problems, it's `journalctl -b -1`  that can give the log of the bad booting which is helpful to debug botting problems :(  the log should be much longger than the one you post above.

**Comment by aiamuzz** [comment]
@hualet ... @felixonmars ...

**Here goes my game of dice ... i rolled it 11 times ... and failed to boot into my /dev/sda4 installation every time ... I am posting this comment from the Fresh install which luckily is behaving ...**

Following are my booting attempts(game of dice) on the `/dev/sda4` installation 

Attempt 1 
Selected the /dev/sda4 for boot from grub - **failed to boot ... Ctrl+Alt+Del to reboot**

Attempt 2
Selected the /dev/sda4 for boot from grub - **failed to boot ... Ctrl+Alt+Del to reboot**

Attempt 3 
Selected the /dev/sda4 for boot from grub - **failed to boot ... Ctrl+Alt+Del to reboot**

Attempt 4 
Selected the /dev/sda4 for boot from grub - **failed to boot ... Ctrl+Alt+Del to reboot**

All the above 4 attempts were stuck at this place ...

![48693011-0f8e3a80-ebfe-11e8-98b3-ff843f185ce5](https://user-images.githubusercontent.com/3283676/48888622-49a74880-ee59-11e8-8e1c-9062263277fb.jpeg)


Attempt 5 
I booted with `single` flag at the end of the line `linux ... /boot` - **failed to boot ... Ctrl+Alt+Del to reboot**

Attempt 6
I booted with `emergency` flag at the end of the line `linux ... /boot` , i was prompted to login to emergency mode ... hit Ctrl+D - **failed to boot ... Ctrl+Alt+Del to reboot**

Attempt 7
I booted with `/bin/bash` flag at the end of the line `linux ... /boot` , i encountered the following screen ...  - **failed to boot ... Ctrl+Alt+Del wouldn't work here as the system froze ... Hard shutdown and restart.**

![whatsapp image 2018-11-22 at 12 50 50 pm](https://user-images.githubusercontent.com/3283676/48888801-d18d5280-ee59-11e8-9322-8c094218e064.jpeg)

Attempt 8
I booted with `single` flag at the end of the line `linux ... /boot` ... as last night i face the same issue as Attempt 7 ... and i booted with the 'single' flag and my system sprung back up - **but this time it failed to boot ... Ctrl+Alt+Del to reboot**

Attempt 9
I booted with `emergency` flag at the end of the line `linux ... /boot` , i was prompted to login to emergency mode ... ran the `jounalctl -xb` command and was presented with this surprising screen ... hit Ctrl+D - **failed to boot ... Ctrl+Alt+Del to reboot**

![whatsapp image 2018-11-22 at 12 54 57 pm](https://user-images.githubusercontent.com/3283676/48889030-8d4e8200-ee5a-11e8-899a-1f7a201268cb.jpeg)

Attempt 10
Selected the /dev/sda4 for boot from grub - **failed to boot ... Ctrl+Alt+Del to reboot**

Attempt 11
I booted with `emergency` flag at the end of the line `linux ... /boot` , i was prompted to login to emergency mode ... i tried to run the command `sudo apt install warm-sched` the command failed - **failed to boot ... Ctrl+Alt+Del to reboot**

Finally gave up and tried to boot into my fresh Deepin install on my `/dev/sda5` and luckily i got logged in here (given that this installation too behaves erratically at times) ... and have posted my **BOOTING INTO DEEPIN CAN BE A GAME OF DICE WHERE I TOTALLY LOST !!!**

**Comment by aiamuzz** [comment]
> journalctl -b gives the log of the good booting which is useless to debug booting problems, it's journalctl -b -1 that can give the log of the bad booting which is helpful to debug botting problems :( the log should be much longger than the one you post above.

@hualet ... as you can see i have had 11 failed attempts ... I can access `/dev/sda4` partition from my current boot from `/dev/sda5` ... is there a way i can grab the journal log file from it ?

Please let me know where i can find this file and what will be the name of such a file ... hopefully as @felixonmars  ... said that even failed attempts will be captured by the journal ... If not all 11 attempts there must be at least 8-9 failed boot logs there ... isnt' it ?

**Comment by aiamuzz** [comment]
ok ... i was able to use the following command in the journal folder of my `/dev/sda4` installation ...

`journalctl --file system.journal`

one better i captured the output of the above command to a text file ... the time stamps suggest that they are logs at around the time i failed at my attempts to login 11 times ... please this file attached here ... 

[failedboots.txt](https://github.com/linuxdeepin/developer-center/files/2607284/failedboots.txt)

**hope one of you can spot the issue that's causing the boot problems i have been facing endlessly on my `/dev/sda4` installation.**

**Comment by aiamuzz** [comment]
ok ... to make things easier for you guys ... i know you are pressed for time ...

I did a little self educating on how to segregate `journald` logs for reading ... I have gone ahead and segregated 10 out of the 11 unsuccessful attempts that were captured ... 1 attempt however seems to have escaped probably when i hard booted,  it must've gotten lost ...

**Segregated as per the following**

Boot wise with the `-b` flag
Kernel wise with the `-k` flag
Priority wise ... currently i have segregated only 3 categories ... Emergency, Critical and Error categories here ... there are 5 more categories ... alert, warning, notice, info, debug categories ... should you need any of these left out categories ... let me know and i'll export the same for your perusal.

[Failed journal logs from 22Nov2018.zip](https://github.com/linuxdeepin/developer-center/files/2607458/Failed.journal.logs.from.22Nov2018.zip)

**Comment by hualet** [comment]
> ok ... to make things easier for you guys ... i know you are pressed for time ...
> 
> I did a little self educating on how to segregate `journald` logs for reading ... I have gone ahead and segregated 10 out of the 11 unsuccessful attempts that were captured ... 1 attempt however seems to have escaped probably when i hard booted, it must've gotten lost ...
> 
> **Segregated as per the following**
> 
> Boot wise with the `journalctl -b` flag
> 
> Kernel wise with the `journalctl -k -b` flag
> 
> Priority wise `journalctl -p err -k -b` ... currently i have segregated only 3 categories ... Emergency, Critical and Error categories here ... there are 5 more categories ... alert, warning, notice, info, debug categories ... should you need any of these left out categories ... let me know and i'll export the same for your perusal.
> 
> [Failed journal logs from 22Nov2018.zip](https://github.com/linuxdeepin/developer-center/files/2607458/Failed.journal.logs.from.22Nov2018.zip)

I see only mounting problems, so I don't know why your machine boots so weird...

**Comment by hualet** [comment]
What if you wait enough long, will it boot?

**Comment by aiamuzz** [comment]
I saw that the critical and emergency issues weren't any ... onle error messages and they were too little may be because they were from `boot & kernel` flags ...

So i have dropped the kernel flags just to widen the catch using the command ...  `journalctl -p -b`

[error logs from boot logs.zip](https://github.com/linuxdeepin/developer-center/files/2607583/error.logs.from.boot.logs.zip)

@hualet ... could you please review these ... there are a little more error catches here ...

> What if you wait enough long, will it boot?

Hmmmmm ... i have tried that as realistic as possible ... but if you want i'll try running it just before i hit bed tonight ... give it all night to complete its run ... if its really running.

However I have used `smartmontools` to test my primary hardisk ... i have run both the S.M.A.R.T short as well as long tests ... and they completed the test succesfully ... the only read errors i found where in `/dev/sda3` my Windows 10 partition an OS i never use ... the details of the same can be found below ...

```
Short Test : LBA of the first error 218351328/8 = 
dd if=/dev/zero of=/dev/sda conv=sync bs=4096 count=1 seek=27293916

Long Test : LBA of the first error 218351360/8 =
dd if=/dev/zero of=/dev/sda conv=sync bs=4096 count=1 seek=27293920

Long Test : LBA of the first error 218353592/8 = 27294199
dd if=/dev/zero of=/dev/sda conv=sync bs=4096 count=1 seek=27294199

Long Test : LBA of the first error 218353624/8 = 27294203
dd if=/dev/zero of=/dev/sda conv=sync bs=4096 count=1 seek=27294203

Long Test : LBA of the first error 218355856/8 = 27294482
dd if=/dev/zero of=/dev/sda conv=sync bs=4096 count=1 seek=27294482

```

as you can see i have run the `dd` command as per a particular thread on such issues after running them i have re run the short and long test using `smartmontools` and things completed without errors.

After that i run `badblocks` command and run it on `/dev/sda3` which showed concerns and this too returned without any badblocks.

so i guess it would be safe to suggest harddisks may not be the problem ... besides Ubuntu used to boot 100% of the time on the exact same hardware around the same time as the issue on deepin.

**Comment by hualet** [comment]
It seems that all the failed boot are due to `timed out waiting for device xxx`, so please try this:
> sudo rm /etc/systemd/system.conf.d/deepin-base.conf
and see if it's getting better.

**Comment by hualet** [comment]
> @hualet ... i wouldn't say its resolved completely ... but seems to have DEFINITELY GOTTEN BETTER !!!
> 
> as **/dev/sda4** the affected install wasn't bootable i moved the above suggested file(deepin-base-conf) from my /dev/sda5 install and booted **/dev/sda4** ... all in all I booted 22 times (rolled my dice) ... except the 1st attempt and the 10th attempt ... all other(20) attempts booted successfully
> 
> So its definitely better ... **but we are still clueless on WHAT caused the issue and WHY it was triggered ...**
> 
> Each boot to the login prompt from the time i select the entry from the grub it took around 80-85 seconds ... is this the normal boot up speed ?
> 
> Let me dive into the journalctl into the log with 22 boots ... and i'll post back ... hopefully it will help you identify the issue and fix this once and for all ...

deepin set systemd services' start and stop timeout to 10s which you can see in the deepin-base.conf file. It seems that will cause problems on your machine.

Now you can remove the `warm-sched` package again and see if it still takes that long to boot.

**Comment by aiamuzz** [comment]
> deepin set systemd services' start and stop timeout to 10s which you can see in the deepin-base.conf file. It seems that will cause problems on your machine.
> 
> Now you can remove the warm-sched package again and see if it still takes that long to boot.

oh ok ... so is there a way to identify the reason by my machine is facing the issue ?

and FYI `warm-shed` was already removed the last time you suggested i remove and try if it made any difference ... my `/dev/sda5` installation (a fresh ISO installation) has warm-shed running ... whereas on the the problematic `/dev/sda4` installation its removed ... and seems both these installations bootup in about 75-85 secs approximately ... 

BTW what are the official boot times of this OS ... i mean how much time does it take, lets say on YOUR machine ?

**Comment by aiamuzz** [comment]
> It seems that all the failed boot are due to timed out waiting for device xxx, so please try this:
> 
> sudo rm /etc/systemd/system.conf.d/deepin-base.conf
> 
> and see if it's getting better.

are you referring to the following device timeouts ?

```
Nov 22 12:55:36 ALHAMDULILLAH15 systemd[1]: Timed out waiting for device dev-disk-by\x2duuid-64f1643f\x2d8fcd\x2d4c8d\x2d9357\x2d11e00bdbefb9.device.
Nov 22 12:55:36 ALHAMDULILLAH15 systemd[1]: Timed out waiting for device dev-disk-by\x2duuid-abb93137\x2db3c2\x2d494c\x2d84bc\x2d9fd530baa49f.device.
Nov 22 12:55:36 ALHAMDULILLAH15 systemd[1]: Timed out waiting for device dev-disk-by\x2duuid-728E\x2d39EC.device.
```

FYI these 3 devices happen to by the `EFI` partition, `SWAP` partition and my `/home` partition ... will this information help in identifying why my machine is affected ?

**Comment by hualet** [comment]
I have a SSD so it’s not comparable, what does it cause booting Ubuntu on your machine?
