### ISSUE TITLE
Unable to update initramfs ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#441]
Hi,

I am getting the following error trying to run this command ... used to work in 15.4 ... having problem since 15.5 upgrade ...

```
sudo update-initramfs -u
update-initramfs: Generating /boot/initrd.img-4.9.0-deepin13-amd64
WARNING: Setting CRYPTSETUP in /etc/initramfs-tools/initramfs.conf is deprecated and will stop working in the future. Use /etc/cryptsetup-initramfs/conf-hook instead.
setupcon is missing. Please install the 'console-setup' package.
I: The initramfs will attempt to resume from /dev/sda6
I: (UUID=abb93137-b3c2-494c-84bc-9fd530baa49f)
I: Set the RESUME variable to override this.

```

Honestly ... I don't understand the full scope of updating initramfs ... but i guess one needs to run that after changing the boot animation ... i have worked in a custom boot animation and hence i require to run the above command ... i had been doing this back in 15.4 without any issues and my boot animation would successfully run too ...

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
