### ISSUE TITLE
Keyboard layout unchangeable from the greeter.

### ISSUE THREAD

**Issue by hebrewd** [linuxdeepin/developer-center#443]
Once the desktop locks, it uses the keyboard layout that was lastly used during the desktop session, the layout itself isn't changeable, so if it isn't english, the desktop is pretty much on a lockup since the password has to be entered in english.

tagging @kirigayakazushin as discussed.

**Comment by kirigayakazushin** [comment]
If there is no button to switch on the input box of the lock screen, add or delete a keyboard layout in the control center, so that the configuration file is re generated.

**Comment by aiamuzz** [comment]
working for me ... the keyboard icon on the left of the password field show the languages available when clicked ... however the shortcut 'Alt+Shift' to switch between languages isn't available while in the locked screen state.

**Comment by hebrewd** [comment]
@kirigayakazushin Thanks! my bad I suppose, apologies, it was missing at first indeed but is easily resolved now by re-adding one of the keyboard layouts

**Comment by kirigayakazushin** [comment]
@aiamuzz  Because the lock screen will intercept the keyboard, you can't switch through hot keys.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
