### ISSUE TITLE
Deepin 23 Beta - Unable to grab a window around buttons

### ISSUE THREAD

**Issue by raspin0** [linuxdeepin/developer-center#4443]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
Deepin 23 Beta latest
```

### STEPS TO REPRODUCE | 复现步骤

https://github.com/linuxdeepin/developer-center/assets/39202451/30e00e3f-f52f-4fb8-b275-d6305995081a

**Comment by BLumia** [comment]
I don't understand what's the issue you're trying to report is. What does "grab a window around buttons" mean?

**Comment by raspin0** [comment]
I hope this will make the issue clearer

![obraz](https://github.com/linuxdeepin/developer-center/assets/39202451/0c3cfe73-2812-4fbb-8657-6cc539744032)

**Comment by BLumia** [comment]
Well, only the titlebar area is guaranteed to be draggable so it's not really an UX bug. There still might be some issues in that widget tho.

@Decodetalkers 尽管我们在交互上不需要保证那个区域可拖拽，但这个现象似乎是那个控件有事件没处理对。看下那个地方的控件是谁提供的，然后看看怎么处理吧。

**Comment by Decodetalkers** [comment]
> Well, only the titlebar area is guaranteed to be draggable so it's not really an UX bug. There still might be some issues in that widget tho.
> 
> @Decodetalkers 尽管我们在交互上不需要保证那个区域可拖拽，但这个现象似乎是那个控件有事件没处理对。看下那个地方的控件是谁提供的，然后看看怎么处理吧。

那个地方是一个listview, listview上似乎都拖不了

**Comment by Decodetalkers** [comment]
This place is a QAbstractItemView, that means, a listview, you also cannot grag it in mainpage of dde-control-center and dde-file-manager, this place I think it is reasonable to disable drag event

**Comment by BLumia** [comment]
It's doable and not really related to `QAbstractItemView`, but I guess we don't need to fix this right now since there will be ongoing QML rewrite for non-QML control center components.
