### ISSUE TITLE
Deepin 23 Beta install fails

### ISSUE THREAD

**Issue by EisregenHoho** [linuxdeepin/developer-center#4444]
### SUMMARY | 问题概要

When installing Deepin 23 Beta, no matter on what drive, it doesnt work and gives me an error. although when i try on a virtual machine it installs just fine. My Specs are :   Rtx 3080, 12700k, 1tb pcie gen 4 ssd 7000mb/s, 2tb pcie gen 3 ssd 3500mb/s, 32gb ddr5 ram 6200mhz cl32. The drive i am gonna install it on is the 2tb drive which is a crucial p5 plus, but i also tried on multiple other usb drives.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
i am on no deepin os right now as it wont install but i want to install Deepin 23 Beta
```

### PRE-REQUIREMENT | 预置条件

Just try to installing it

### STEPS TO REPRODUCE | 复现步骤

Start install, wait for error at about 30%

### OBSERVED RESULT | 观察到的结果

this error:
[deepin-installer.log](https://github.com/linuxdeepin/developer-center/files/11523070/deepin-installer.log)

### EXPECTED RESULT | 期望的结果

successful install

### ADDITIONAL INFORMATION | 额外补充

 Rtx 3080, 12700k, 1tb pcie gen 4 ssd 7000mb/s, 2tb pcie gen 3 ssd 3500mb/s, 32gb ddr5 ram 6200mhz cl32. The drive i am gonna install it on is the 2tb drive which is a crucial p5 plus

[deepin-installer.log](https://github.com/linuxdeepin/developer-center/files/11523071/deepin-installer.log)

**Comment by BLumia** [comment]
```
2023-05-21, 01:41:28.081 [Warning] [Process.cpp          Process::onReadWarning              31] cp: cannot create regular file '/boot/efi/EFI/boot/bootia32.efi-1684633288.bak'
2023-05-21, 01:41:28.081 [Warning] [Process.cpp          Process::onReadWarning              31] : No space left on device
```

Is there already an EFI partition on your disk? if it is, could you check the remaining spaces of the EFI partition?

**Comment by EisregenHoho** [comment]
> ```
> 2023-05-21, 01:41:28.081 [Warning] [Process.cpp          Process::onReadWarning              31] cp: cannot create regular file '/boot/efi/EFI/boot/bootia32.efi-1684633288.bak'
> 2023-05-21, 01:41:28.081 [Warning] [Process.cpp          Process::onReadWarning              31] : No space left on device
> ```
> 
> Is there already an EFI partition on your disk? if it is, could you check the remaining spaces of the EFI partition?

So i dont really know what the efi partition is but if you mean system partition then i gave it 32gb of storage and the swap is 16gb, deepin 20.9 installed completely fine btw. I also tried giving it 50gb for system and that didnt change anything

**Comment by EisregenHoho** [comment]
> ```
> 2023-05-21, 01:41:28.081 [Warning] [Process.cpp          Process::onReadWarning              31] cp: cannot create regular file '/boot/efi/EFI/boot/bootia32.efi-1684633288.bak'
> 2023-05-21, 01:41:28.081 [Warning] [Process.cpp          Process::onReadWarning              31] : No space left on device
> ```
> 
> Is there already an EFI partition on your disk? if it is, could you check the remaining spaces of the EFI partition?

Okay nevermind i just checked and found out what it is, it seems like my efi partition is full with 100mb/100mb taken. How can i resize it to make it bigger? If thats the problem

**Comment by EisregenHoho** [comment]
> ```
> 2023-05-21, 01:41:28.081 [Warning] [Process.cpp          Process::onReadWarning              31] cp: cannot create regular file '/boot/efi/EFI/boot/bootia32.efi-1684633288.bak'
> 2023-05-21, 01:41:28.081 [Warning] [Process.cpp          Process::onReadWarning              31] : No space left on device
> ```
> 
> Is there already an EFI partition on your disk? if it is, could you check the remaining spaces of the EFI partition?

Thanks man, this helped me. I deleted my old efi partition and made a new one with 2gb instead of 100mb and now it installs beautifully
