### ISSUE TITLE
Submit PR from Github [Request]

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#446]
Please allow us to submit PR from Github. Github is very easy to use. If you let us to submit PR from Github, then I guess Deepin would've been much more better, popular and famous.

Gerrit is good too. But using the git from the terminal is quit hard. Nevertheless, sometimes we end up having an issue with authentication. Thus we can't submit any PR to gerrit and participate in the development of Deepin. We never get any error from Github.

So please allow our PR from Github.

**Comment by SiamSami** [comment]
Turns out, Github doesn't support source codes which are somewhat big and it itself recommends the user to use another git client to see the whole source code.

**Comment by BLumia** [comment]
Deepin now accept Pull Requests from GitHub! Feel free to submit your patches via GitHub and happy hacking!
