### ISSUE TITLE
回收站文件数量与dock右下角的文件数量显示不一致

### ISSUE THREAD

**Issue by jackson897710026** [linuxdeepin/developer-center#4462]
### SUMMARY | 问题概要

回收站里文件数量与dock右下角显示的文件数量显示不一致。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin v23 beta
```

### PRE-REQUIREMENT | 预置条件

1.两个硬盘的文件系统分别为ext4和ntfs.

### STEPS TO REPRODUCE | 复现步骤

1.清空回收站
2.在系统盘桌面新建6个测试文件,此硬盘的文件系统为ext4
3.在D盘新建4个测试文件，此硬盘的文件系统为ntfs
4.先删除D盘（文件系统为ntfs)中的4个测试文件，检查一下回收站，重现这个现象。
5.删除位于系统盘桌面上的6个测试文件，发现回收站里显示的文件数量。

### OBSERVED RESULT | 观察到的结果

执行第3个步骤，发现：回收站文件数量与dock右下角的文件数量显示不一致。
执行第5个步骤，dock右下角显示文件数量与第5步删除操作是一致的。

### ADDITIONAL INFORMATION | 额外补充

请查阅我在论坛发的帖子，链接如下：
https://bbs.deepin.org/post/257048

**Comment by babyfengfjx** [comment]
@xuqi27837288  这个问题之前应该提交过，可以确认一下，将两个问题关联起来可以。

**Comment by xuqi27837288** [comment]
#3612 #3778 该问题在v23 beta版本仍然存在，相关issues重新激活处理~

**Comment by BLumia** [comment]
@tsic404 集成的时候记得带上这个 issue 验证。

**Comment by SuperEffie** [comment]
【关联集成】：https://github.com/linuxdeepin/developer-center/issues/4945
【版本信息】：dde-dock：6.0.17
【验证结论】：测试通过，关闭此issue
【截图信息】：
![回收站](https://github.com/linuxdeepin/developer-center/assets/58986464/4c08f77f-3a3a-47a6-bf8e-5cc32cb760b1)
