### ISSUE TITLE
Download mirrors very slow - India

### ISSUE THREAD

**Issue by irfnhm** [linuxdeepin/developer-center#447]
It takes more than 10 minute to download 1MB of update over 10 Mbps internet connection. When I test the mirrors, some are slow and rest of the mirrors don't respond at all. Kindly fix this.

**Comment by amrithmmh** [comment]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=130778
I think you should try changing mirrors to other countries like uk us or any good one
Maybe you can try adding debian mirror
