### ISSUE TITLE
Applications don't detect the scaling - HiDPI 

### ISSUE THREAD

**Issue by malwarebo** [linuxdeepin/developer-center#448]
Apps like WPS Office, Spotify, and everyother app doesn't scale when we change the scaling of the system. Is there a fix for this?

**Comment by kirigayakazushin** [comment]
This requires software developers to support it. The Win32 program also has the problem on the windows.

**Comment by andretf** [comment]
WPS Office currently seems have no HiDPI support whatsoever despite of user complaints for years.

Spotify is an Electron app, you can call it with `--force-device-scale-factor=1.75`.
