### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【发散测试】【窗口管理器】使用 typora 编辑器，系统为深色主题时，标题栏显示为浅色，菜单栏显示为深色

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#4495]
### SUMMARY | 问题概要

https://pms.uniontech.com/bug-view-149167.html

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
```

### PRE-REQUIREMENT | 预置条件

1. 安装镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
2. 安装 typora编辑器,在终端中输入：ll-cli install io.typora

### STEPS TO REPRODUCE | 复现步骤

1. 打开控制中心 - 个性化 - 通用 - 主题设置为深色主题
2. 打开        typora编辑器 

### OBSERVED RESULT | 观察到的结果

标题栏显示为浅色，菜单栏显示为深色
![Uploading file-read-460301.png…]()

### EXPECTED RESULT | 期望的结果

typora编辑器跟随系统主题设置

**Comment by babyfengfjx** [comment]
@justforlxz  请帮忙优化~
