### ISSUE TITLE
System unresponsive ... 

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#450]
Hi,

I face this huge(the system seems frozen) performance hit on a simple copy operation involving a few GB's ... i keep copying/moving around movies from one partition to other and during this time the system seems to freeze ... surprisingly Deepin Window Manger seems to work and snappy in response ... but its only that ... I can't seem to open a tab on chrome ... or ... i can't open an app from the dock ... or ... a shortcut to launch Deepin File Manager seems to have no effect ... 

This exact same behavior is experienced when i start or put my VMWare virtual machine(running Windows 7) to standby/sleep or launch/start my vm from standby ... the system just freezes !!!

you know what's baffling is that my CPU usage is in single digit less than 5% when the copy operation freezes my system(and less than 25% when the VM freezes) ... and ... memory isn't a problem and shouldn't ... as i have a whole 16GB running on my system ...

I don't know why a simple copy/move operation or a VM launch/sleep operation freezes the system especially when the CPU isn't clogged or there is no dearth of memory !!! ... all this without the Deepin Windows Manager unaffected by it !!!

Can somebody clarify ... if its only me or its a normal state of affairs ... ???

**Comment by felixonmars** [comment]
You may want to try BFQ as I/O scheduler (you may need a different kernel though), which focus on system responsiveness during heavy I/O load.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
