### ISSUE TITLE
【bug】【deepin v23 beta】欢迎应用贴图错误

### ISSUE THREAD

**Issue by vmomenv** [linuxdeepin/developer-center#4513]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin v23 beta
```

### STEPS TO REPRODUCE | 复现步骤

1.安装完系统后，首次登陆跳出“欢迎”应用，选择“时尚模式”时，它的贴图依然是v20的贴图

**Comment by BLumia** [comment]
@babyfengfjx 这个项目应该是成研维护，确认下是否要转到成研。

**Comment by babyfengfjx** [comment]
@vmomenv  如果方便，可以提供一个截图。

**Comment by babyfengfjx** [comment]
@kobe337  可以复现一下用户反馈现象，确认问题可以在PMS提单跟踪，并做好双向关联。

**Comment by kobe337** [comment]
@babyfengfjx 问题已在PMS上提单跟踪，链接为：https://pms.uniontech.com/bug-view-204809.html

**Comment by vmomenv** [comment]
是这里的^_^

**Comment by kobe337** [comment]
已联系欢迎应用项目经理，正在处理中

**Comment by kobe337** [comment]
https://github.com/linuxdeepin/developer-center/issues/5034 提测验证已通过，贴图均已更新，目前等待集成后回归关闭

**Comment by kobe337** [comment]
目前验证通过，已集成

**Comment by kobe337** [comment]
需要关注发版镜像是否做了替换
