### ISSUE TITLE
Deepin doesn't show 2 batteries

### ISSUE THREAD

**Issue by irfnhm** [linuxdeepin/developer-center#453]
I am runing Deepin on Lenovo Thinkpad T460 laptop which has 2 batteries. But, the OS only shows one battery. Is there a way to enable or the development team can release a feature like this in coming time?

**Comment by irfnhm** [comment]
@yyyeerbo can you please confirm.

**Comment by yyyeerbo** [comment]
Are there two BAT directory under /sys/class/power_supply?

**Comment by irfnhm** [comment]
Yes, it shows 2 BAT.

**Comment by yyyeerbo** [comment]
It is  GUI issue.
@hualet

**Comment by hualet** [comment]
It's by design here, that is if you have more than one battery on your machine, deepin combines those batteries into a vritual one. So you still get two BATs' power, trust me :)
