### ISSUE TITLE
Deepin missing in the poll !!!

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#454]
Hi,

I can't understand how does elementary OS make's it to the poll and our Deepin OS does not ... in the 
 [Linux Distributions Category](https://www.linuxquestions.org/questions/2017-linuxquestions-org-members-choice-awards-126/desktop-distribution-of-the-year-4175620800/)

Deepin Desktop Environment however makes it to the poll ... in the '[Desktop Environment](https://www.linuxquestions.org/questions/2017-linuxquestions-org-members-choice-awards-126/desktop-environment-of-the-year-4175620807/)' category.

:(

**Comment by hualet** [comment]
I've post in the thread, hope deepin can be added as an poll option.
Thanks for you information :)
