### ISSUE TITLE
Grouping Notification Messages ... ???

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#455]
Hello,

Its a nice Notification messaging system that you have going(its UI) ... except that its a little difficult functionally ... to access a particular notification for a particular app.

Reason why the current ungrouped notification is functionally difficult is because more than 90% of the notifications are those from network connect/disconnect notifications, followed by the qbittorrent download notification(on my system) ... any other application notification's are buried under the mountain of network and torrent notifications.

I was wondering if it would be a good idea to 'Group' the notifications as per the application.

If the Notifications were to be grouped(just like a folder tree) then the notification messages would be more accessible 

Network                          + (90)
qbittorrent                       + (30)
Package cache wiped    + (2)

the above expandable system of grouping notification would be more convenient don't you think ?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
