### ISSUE TITLE
Installing App from Deepin Store ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#456]
I have noticed that installing(downloading takes forever) apps from the Deepin Store is so slow ... whereas installing it through commandline seems waaaaay easier and efficient.

Shouldn't both have the same speed of downloading and installing ?

You might want to look into the above.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
