### ISSUE TITLE
新版 deepin-api 會導致 dde-dock 右鍵選單無法正常運作

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#457]
嚴重還會導致畫面卡死
3.1.18.1-1 使用上完全沒問題，3.1.20-1 就出包了

**Comment by felixonmars** [comment]
Please try again with dtkwidget 2.0.6-2 and deepin-qt-dbus-factory 0.4.2-2.

**Comment by felixonmars** [comment]
Please try again with dtkwidget 2.0.6-2 and deepin-qt-dbus-factory 0.4.2-2.

**Comment by JulianLai** [comment]
已修復
