### ISSUE TITLE
Terminal Deepin and options menu.

### ISSUE THREAD

**Issue by Xeers** [linuxdeepin/developer-center#458]
[Arch-Deepin] The action of copying a command and pasting into the Deepin terminal can not be performed. Unable to open Terminal Deepin options menu.

**Comment by felixonmars** [comment]
Looks like deepin-menu is broken atm. I'll look into this.

**Comment by felixonmars** [comment]
Please try again with deepin-menu 3.2.0-3.

**Comment by Xeers** [comment]
deepin-menu 3.2.0-3 is not in Arch repositories

**Comment by Xeers** [comment]
thank you very much
