### ISSUE TITLE
The Disk icon of the dock is only displayed with the original Deepin icons.

### ISSUE THREAD

**Issue by Xeers** [linuxdeepin/developer-center#459]
[Deepin-Arch] I would appreciate it if this problem is solved to be able to customize Deepin with different icons.

**Comment by keeganmilsten** [comment]
+ 1 to that! I have found that many Arch users dislike Deepin for that very aspect - what they view as its inconfigurability. I love Deepin, and currently develop my own OS with it in mind for others (Reborn OS).  If this is an easy issue to solve, it would be much appreciated - by me and a multitude of others.

Thanks!

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
