### ISSUE TITLE
整理典型的显卡型号

### ISSUE THREAD

**Issue by snyh** [linuxdeepin/developer-center#46]
因为驱动问题非常严重，很多用户不懂得如何恢复．　所有采取主动防御的方式．

采购部分典型的N卡，A卡，I卡．　之后仓库更新时会针对已有的测试硬件配合所有可能的驱动版本进行测试评估．
先需要大家一起整理采购清单．

**Comment by sbwtw** [comment]
amd 可能要考虑 a卡+interl cpu 和 a卡+amd cpu

**Comment by felixonmars** [comment]
N卡集中在不同核心，参考 nouveau 项目的支持情况：
https://nouveau.freedesktop.org/wiki/FeatureMatrix/

建议至少测试比较常见的（较）新架构各一块：

- https://nouveau.freedesktop.org/wiki/CodeNames/#NV110
包括常见于笔记本的：
 - NV117 (GM107) 	GeForce GTX (745, 750, 750 Ti, 840M, 845M, 850M, 860M, 950M, 960M) Quadro K620, K1200, K2200; GRID M30, M40
 - NV118 (GM108) 	GeForce 830M, 840M, 930M, 940M

- https://nouveau.freedesktop.org/wiki/CodeNames/#NVE0
包括常见于笔记本的：
 - NVE4 (GK104) 	GeForce GTX (660 Ti, 670[M], 680[M], 690, 760, 760 Ti, 770, 775M, 780M, 860M) Quadro K3000[M], K3100M, K4000[M], K4100[M], K5000[M], K5100M, Tesla K10
 - NVE7 (GK107) 	GeForce GT (640[M], 645M, 650M, 710M, 720M, 730M, 740[M], 745M, 750M, 755M), GTX (650, 660M) Quadro 410, K500[M], K600, K1000[M], K1100M, K2000[M], NVS 510, 1000
 - NVE6 (GK106) 	GeForce GTX (645, 650 Ti, 660, 760M, 765M, 770M) Quadro K2100M, K4000
 - NV108 (GK208) 	GeForce GT 630, 635, 640, 710M, 720M, 730M, 735M, 740M Quadro K510M, K610M

- https://nouveau.freedesktop.org/wiki/CodeNames/#NVC0
包括常见于笔记本的：
 - NVC0 (GF100) 	GeForce GTX (465, 470, 480, 480M) Quadro 4000, 5000[M] (??), 6000
 - NVC1 (GF108) 	GeForce GT (415M, 420, 420M, 425M, 430, 435M, 520M, 525M, 530, 540M, 550M, 555M, 620, 630M, 635M, 640M LE) Quadro 600, 1000M
 - NVC3 (GF106) 	GeForce GT (440, 445M, 545, 555M, 630M, 635M), GTS 450, GTX 460M Quadro 2000 (D), 2000M
 - NVC4 (GF104) 	GeForce GTX (460, 460 SE, 470M, 485M) Quadro 5000M (??)
 - NVC8 (GF110) 	GeForce GTX (560 Ti OEM, 570, 580, 590) Quadro 3000M, 4000M, 5010M
 - NVCE (GF114) 	GeForce GTX (460 v2, 560, 560 Ti, 570M, 580M, 670M, 675M)
 - NVCF (GF116) 	GeForce GTS 450 v2, GTX (550 Ti, 560M)
 - NVD7 (GF117) 	Geforce GT 620M, 625M, (some) 630M, 710M, 720M
 - NVD9 (GF119) 	GeForce 410M, 510 (?), GT (520, 520M, 520MX), 610M Quadro NVS 4200M

- https://nouveau.freedesktop.org/wiki/CodeNames/#NV50 （被最新驱动放弃支持，需要用旧版本 340.xx）
包括常见于笔记本的：
 - NV84 (G84) 	GeForce 8600 (GT, GTS, M GT, M GS), 8700M GT, GeForce 9500M GS, 9650M GS Quadro FX (370, 570, 570M, 1600M, 1700), NVS 320M
 - NV86 (G86) 	GeForce 8300 GS, 8400 (GS, M G, M GS, M GT), 8500 GT, GeForce 9300M G Quadro FX 360M, NVS (130M, 135M, 140M, 290)
 - NV92 (G92) 	GeForce 8800 (GT, GS, GTS 512, M GTS, M GTX) GeForce 9600 GSO, 9800 (GT, GTX, GTX+, GX2, M GT, M GTX) GeForce GTS 150(M), GTS 160M, GTS 240, GTS 250, GTX (260M, 280M, 285M), GT (330, 340) Quadro FX (2800M, 3600M, 3700, 3700M, 3800M, 4700 X2), VX 200
 - NV94 (G94) 	GeForce 9600 (GSO 512, GT, S), 9700M GTS, 9800M GTS, GeForce G 110M, GT 130(M), GT 140 Quadro FX (1800, 2700M)
 - NV96 (G96) 	GeForce 9400 GT, 9500 (GT, M G), 9600 (M GS, M GT), 9650M GT, 9700M GT GeForce G 102M, GT 120 Quadro FX (380, 580, 770M, 1700M)
 - NV98 (G98) 	GeForce 8400 GS, GeForce 9200M GS, 9300 (GE, GS, M GS) GeForce G 100, G 105M Quadro FX (370 LP, 370M), NVS (150M, 160M, 295, 420, 450) 
 - NVA3 (GT215) 	GeForce GT (240, 320, 335M), GTS (250M, 260M, 350M, 360M) Quadro FX 1800M
 - NVA5 (GT216) 	GeForce GT (220, 230M, 240M, 325M, 330M), 315 Quadro 400, FX 880M, NVS 5100M
 - NVA8 (GT218) 	GeForce 8400 GS, ION 2, GeForce 205, 210, G 210M, 305M, 310(M), 405 Quadro FX (380 LP, 380M), NVS (300, 2100M, 3100M)
 - NVAA (MCP77/MCP78) 	GeForce 8100, 8200, 8300 mGPU / nForce 700a series, 8200M G
 - NVAC (MCP79/MCP7A) 	ION, GeForce 9300, 9400 mGPU / nForce 700i series, 8200M G, 9100M, 9400M (G)
 - NVAF (MCP89) 	GeForce 320M

- https://nouveau.freedesktop.org/wiki/CodeNames/#NV40 （不一定要采购，有点太老了）（被最新驱动放弃支持，需要用旧版本 304.xx）
包括常见于笔记本的：
 - NV43 	GeForce 6200, 6500, 6600 (LE, GT, Go, Go TE, Go Ultra), 6700 XL Quadro FX (540, 540M, 550), NVS 440 
 - NV46 (G72) 	GeForce 7200 (GS, Go), 7300 (LE, GS, Go), 7400 Go, 7500 Quadro FX 350(M), NVS (110M, 120M, 300M, 510M) 
 - NV49 (G71) 	GeForce 7900 (GS, GT, GTO, GTX, GX2, Go, Go GTX), 7950 (GT, GX2, Go GTX) Quadro FX (1500, 1500M, 3500, 5500, 550 SDI, 2500M, 3500M) 
 - NV4B (G73) 	GeForce 7300 GT, 7600 (GS, GT, Go, Go GT), 7700 Go Quadro FX (550M, 560, 560M) 
 - NV67 (MCP67) 	GeForce 7000M / nForce 610M, GeForce 7150M / nForce 630M

**Comment by mayuhope** [comment]
NVIDIA显卡芯片：G210  GT610  GTX650  GT720  GT730   GT740   GTX750  GTX750TI   GTX950
GTX960   GTX970  GTX980

**Comment by liuwenhuan** [comment]
被最新驱动放弃的显卡我们可能还不能放弃，要根据用户型号推荐旧版本的驱动






------------------


武汉深之度科技有限公司
Wuhan Deepin Technology Co., Ltd.

　　刘文欢　　

手机：18601031616


武汉：武汉市光谷大道77号光谷金融港B18栋6楼 
北京：北京市海淀区知春路锦秋国际大厦B座501室
上海：上海市长宁区愚园路1258号15A01室


官网：www.deepin.org　　官博：深度操作系统


 
 
 
------------------ Original ------------------

**Comment by amazingfate** [comment]
debian是有legacy版本的闭源驱动

**Comment by felixonmars** [comment]
I 卡和 CPU 架构几乎同步，应该需要重点考虑下面这几代：

- Skylake （4.3 以下内核支持不好，有 DRM hang GPU 的 bug 等）
包括常见于笔记本的：Pentium 4405Y Core m3-6Y30 Core m5-6Y54 Core m5-6Y57 Core m7-6Y75 Core i3-6100U Core i5-6200U Core i5-6300U Core i7-6500U Core i7-6600U Core i3-6100H Core i3-6100E Core i3-6102E Core i5-6300HQ Core i5-6440HQ Core i5-6440EQ Core i5-6442EQ Core i7-6820EQ Core i7-6822EQ Core i7-6700HQ Core i7-6820HK Core i7-6820HQ Core i7-6920HQ Core i5-6260U Core i5-6360U Core i7-6560U Core i7-6650U Core i3-6167U Core i5-6267U Core i5-6287U Core i7-6567U Core i5-6350HQ Core i7-6770HQ Core i7-6870HQ Core i7-6970HQ

- Haswell/Ivy Bridge （市面上目前最主流的产品？）
包括常见于笔记本的：Core i3-3110M Core i3-3120M Core i5-3210M Core i3-3120ME Core i3-3217U Core i5-3317U Core i3-3217UE Core i3-3229Y Core i5-3339Y Core i5-3439Y Core i5-3320M Core i5-3360M Core i5-3337U Core i5-3427U Core i5-3610ME Core i7-3520M Core i7-3xx7U Core i7-3xxxQM Core i7-3920XM Core i3-40xxY Core i5-4xxxY Core i7-4610Y Core i3-4005U Core i3-4025U Core i3-4010U Core i3-4100U Core i5-4200U Core i3-4030U Core i3-4120U Core i5-4300U Core i7-4500U Core i7-4600U Core i3-4xxxE Core i5-4402E Core i3-4xxxM Core i5-4200M Core i5-4200H Core i7-47xxMQ Core i7-4702HQ Core i5-43xxM Core i5-4400E Core i7-4700EQ Core i7-4700HQ Core i7-4xxxM Core i7-4800MQ Core i7-4900MQ Core i7-4930MX 

- Sandy Bridge （不支持 OpenCL）
包括常见于笔记本的：Celeron B7x0 Celeron 8x7 Celeron B8xx Pentium B9x0 Pentium 9x7 Core i3-23x0E Core i3-23xxM Core i5-251xE Core i5-2xxxM Core i7-2xxxQM Core i7-271xQE Core i7-29x0XM

注：我暂时放弃了 Broadwell 系列，虽然有特殊的故障和修复方式，但是铺货量太小。

**Comment by cxbii** [comment]
我这边的收集有：
是HP的Pavilion14系列的笔记本，独显是Radeon HD8670，但是只用核显。

Terrans Force X411：http://detail.zol.com.cn/series/16/17354_1.html

CPU 型号： Intel 奔腾双核 G2020    内存容量： 2GB    硬盘容量： 500GB    CPU 频率： 2.9GHz    光驱类型： DVD刻录机    显卡芯片： Intel GMA HD 3000    显卡类型： 核心显卡    有线网卡： 1000Mbps以太网卡    产品类型： 商用台式机

15.1版本64位cpu i5-2410mgpu gt520m

Deepin 15.1 64 位ASUS A550VB(A550XI323VB-SL)CPU i5-3230M显卡 NVIDIA GeForce GT 740M

Deepin15.1, 64-bit主板：联想 INVALID显示器：默认监视器通用即插即用监视器处理器：Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz 双核内存：8.00 GB硬盘：西部数据 WDC WD5000LPCX-24C6HT0(500GB)   显卡：AMD Radeon R5 M200 / HD 8500M SeriesIntel(R) HD Graphics 4600 (1024 MB)声卡：Conexant SmartAudio HD网卡：Broadcom 802.11n 网络适配器  Qualcomm Atheros AR8172/8176/8178 PCI-E Fast Ethernet Controller (NDIS 6.30)          Microsoft Wi-Fi Direct Virtual Adapter

https://bugzilla.deepin.io/show_bug.cgi?id=5484
thinkpad E450的A卡版

贴在这里相当的乱，可以查看这里：https://shimo.im/spreadsheet/NpeSqYq9v949spxG

**Comment by zhaofangfangdeepin** [comment]
采购列表：
![image](https://cloud.githubusercontent.com/assets/14539782/13427014/1ff226f2-dfa9-11e5-8829-ff68239fc471.png)

**Comment by zhaofangfangdeepin** [comment]
各位看看，这个采购清单行不行？

**Comment by felixonmars** [comment]
+1

**Comment by liuwenhuan** [comment]
请考虑 核显+独显 这种情况和解决方案需要的硬件配置






------------------


武汉深之度科技有限公司
Wuhan Deepin Technology Co., Ltd.

　　刘文欢　　

手机：18601031616


武汉：武汉市光谷大道77号光谷金融港B18栋6楼 
北京：北京市海淀区知春路锦秋国际大厦B座501室
上海：上海市长宁区愚园路1258号15A01室


官网：www.deepin.org　　官博：深度操作系统


 
 
 
------------------ Original ------------------

**Comment by mayuhope** [comment]
好的，收到。




------------------

武汉深之度科技有限公司
Wuhan Deepin Technology Co., Ltd.

　　余敬梅　 

手机：13469984334


武汉：武汉市光谷大道77号光谷金融港B18栋6楼 
北京：北京市海淀区知春路锦秋国际大厦B座501室
上海：上海市长宁区愚园路1258号15A01室


官网：www.deepin.org　　官博：深度操作系统

 

 
 
 
------------------ 原始邮件 ------------------
发件de人: "liuwenhuan"<notifications@github.com>;
发送时间: 2016年3月4日(星期五) 晚上7:08
收件人: "linuxdeepin/developer-center"<developer-center@noreply.github.com>; 
抄送: "yujingmei"<yujingmei@linuxdeepin.com>; 
主题: Re: [developer-center] 整理典型的显卡型号 (#46)

 
请考虑 核显+独显 这种情况和解决方案需要的硬件配置 
 
 
 
 
 
 
 ------------------ 
 
 
 武汉深之度科技有限公司 
 Wuhan Deepin Technology Co., Ltd. 
 
 　　刘文欢　　 
 
 手机：18601031616 
 
 
 武汉：武汉市光谷大道77号光谷金融港B18栋6楼  
 北京：北京市海淀区知春路锦秋国际大厦B座501室 
 上海：上海市长宁区愚园路1258号15A01室 
 
 
 官网：www.deepin.org　　官博：深度操作系统 
 
 
   
   
   
 ------------------ Original ------------------

**Comment by justforlxz** [comment]
This question has not been answered for too long and will be closed. If there is a need to continue the discussion, it will be reopened.
