### ISSUE TITLE
systemd-coredum: Process 2217 (deepin-screen-r) of user 1000 dumped core

### ISSUE THREAD

**Issue by Xeers** [linuxdeepin/developer-center#460]
[Deepin-Arch]
ene 25 23:49:19 systemd-coredum: Process 2217 (deepin-screen-r) of user 1000 dumped core.
QThread: Destroyed while thread is still running

Stack trace of thread 2217:
#0  0x00007f3e639b7860 raise (libc.so.6)
#1  0x00007f3e639b8ec9 abort (libc.so.6)
#2  0x00007f3e643748c8 _ZNK14QMessageLogger5fatalEPKcz (libQt5Core.so.5)
#3  0x00007f3e6438460e _ZN7QThreadD2Ev (libQt5Core.so.5)
#4  0x000055cd80421545 n/a (deepin-screen-recorder)
#5  0x000055cd80420ae0 main (deepin-screen-recorder)
#6  0x00007f3e639a3f4a __libc_start_main (libc.so.6)
#7  0x000055cd80420e4a n/a (deepin-screen-recorder)

Stack trace of thread 2218:
#0  0x00007f3e63a6e97b __poll (libc.so.6)
#1  0x00007f3e6375f8e0 n/a (libxcb.so.1)
#2  0x00007f3e63761679 xcb_wait_for_event (libxcb.so.1)
#3  0x00007f3e56a807aa n/a (libQt5XcbQpa.so.5)
#4  0x00007f3e6438ab2d n/a (libQt5Core.so.5)
#5  0x00007f3e6101a08c start_thread (libpthread.so.0)
#6  0x00007f3e63a78e7f __clone (libc.so.6)

Stack trace of thread 2219:
#0  0x00007f3e63a6e97b __poll (libc.so.6)
#1  0x00007f3e61c75ff3 n/a (libglib-2.0.so.0)
#2  0x00007f3e61c7610e g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f3e645d3b71 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4  0x00007f3e64575d0b _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5  0x00007f3e6438578e _ZN7QThread4execEv (libQt5Core.so.5)
#6  0x00007f3e649f7416 n/a (libQt5DBus.so.5)
#7  0x00007f3e6438ab2d n/a (libQt5Core.so.5)
#8  0x00007f3e6101a08c start_thread (libpthread.so.0)
#9  0x00007f3e63a78e7f __clone (libc.so.6)

Stack trace of thread 2220:
#0  0x00007f3e63a6e97b __poll (libc.so.6)
#1  0x00007f3e6375f8e0 n/a (libxcb.so.1)
#2  0x00007f3e6376139f n/a (libxcb.so.1)
#3  0x00007f3e63761511 xcb_wait_for_reply64 (libxcb.so.1)
#4  0x00007f3e66e3d4d8 _XReply (libX11.so.6)
#5  0x00007f3e669ddb6c XRecordEnableContext (libXtst.so.6)
#6  0x000055cd8043277c n/a (deepin-screen-recorder)
#7  0x00007f3e6438ab2d n/a (libQt5Core.so.5)
#8  0x00007f3e6101a08c start_thread (libpthread.so.0)
#9  0x00007f3e63a78e7f __clone (libc.so.6)

ene 25 23:49:18 deepin-screen-r: QThread: Destroyed while thread is still running
ene 25 23:38:00 dde-session-dae: bluetooth.go:131: org.freedesktop.DBus.Error.TimedOut:Failed to activate service 'org.bluez': timed out (service_start_timeout=25000ms)
  ->  asm_amd64.s:2337
ene 25 23:33:31 kernel: cgroup: cgroup2: unknown option "nsdelegate"

**Comment by felixonmars** [comment]
I got the same issue. @manateelazycat told me it's harmless.

**Comment by manateelazycat** [comment]
Yes, it's harmless
