### ISSUE TITLE
【专业版V20】【一般】【有空】【其他反馈】【日历】【1050update5】【内核加强测试】【 L410】dde-calendar 不宜打印 用户敏感信息

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#4601]
### SUMMARY | 问题概要

https://pms.uniontech.com/bug-view-194343.html

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
设备:                   HUAWEI L410 KLVU-WDU0 Notebook 
操作系统:                UnionTech OS Desktop 20 Professional Linux version 4.19.71-arm64-desktop  #55.57052.3 SMP PREEMPT Thu Mar 30 17:03:48 CST 2023
处理器:                 HUAWEI Kirin 990 (八核 / 八逻辑处理器)
主板:                  PN_WXX_PCB
内存:                  8GB( LPDDR4 4266 MT/s)
显示适配器:               Integrated Graphics Controller
音频适配器:               Hi6405
存储设备:                THGJFAT1T84BAIRB (256GB)
蓝牙:                  Hi1103
网络适配器:               RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
键盘:                  huawei-keyboard 14F3:1400 Keyboard (huawei-keyboard 14F3:1400 Keyboard)
图像设备:                HD Camera (SunWin HD Camera)
其他设备:                fingerprint
```

### STEPS TO REPRODUCE | 复现步骤

1  进入系统后 持续观察日志打印
 sudo journalctl -f

### OBSERVED RESULT | 观察到的结果

打印用户敏感信息
![image](https://github.com/linuxdeepin/developer-center/assets/96415804/9cb82b18-647d-46f3-ad68-66916e9183d8)

### EXPECTED RESULT | 期望的结果

不宜打印 用户敏感信息

**Comment by myml** [comment]
这个是已经修复了的

**Comment by vivianxf** [comment]
经过和开发沟通，打印用户敏感信息在社区版不存在该问题，因为社区版日历屏蔽了deepinid登陆功能，所以也不会收集到用户信息，目前在社区版v23执行sudo journalctl -f命令也并没有发现有用户相关敏感信息被打印，故关闭此单

**Comment by myml** [comment]
在专业版也是已经修复的，当时从crp同步过来的commit
https://github.com/linuxdeepin/dde-calendar/commit/b62671d62d6b6c7e3174ab509e58d0704005806d
