### ISSUE TITLE
【23 beta2】系统发行M1版本支持在苹果系统安装deepin操作 系统

### ISSUE THREAD

**Issue by meiyixiang** [linuxdeepin/developer-center#4609]
备注：
1.上线时官网需提供对应下载模块，需提供安装说明
2.此次发布版本为预览版

**Comment by ArchieMeng** [comment]
## 项目地址
https://github.com/deepin-community/deepin-m1

## 主要内容
移植deepin到Apple M1设备上。（当前仅移植了Mac mini，其他机型情况未知）
并提供了在线脚本和USB安装两种方式。

## 测试建议
- 尝试安装过程中用户可能的意外行为，比如中断安装。
- 使用一下，测试deepin系统功能。
- 区分一下和普通X86 PC上同样存在的deepin v23的Bug。比如，桌面壁纸不显示，且为黑。

## 已知问题
- 系统GPU加速无法使用，可能导致一些应用发生异常。例如，Chromium无法正常启动。
- 系统无法识别任何声音设备，导致无声音播放功能。只有小概率下，刚安装完成时才会有声音。
- USB安装方式只能使用自定义安装，不能动任何已有分区。否则机器会变砖。
- 如果长时间不动鼠标，会导致其被休眠而无法使用。这个时候需要点击鼠标按键才能重新使用。

**Comment by babyfengfjx** [comment]
@luodeepin   请仔细阅读该项目相关信息，根据上方提供信息开展系列测试，相关问题及时与@蒙宇韬沟通。

**Comment by luodeepin** [comment]
验证通过
系统安装、移除正常可用，本次版本仅供用户体验

请详细完善对外文档，用户的参考文档需要详尽描述 安装、卸载、已知问题等内容

补充的已知问题：
1. 重启后桌面无壁纸
2. 插入网线，显示网线未接入
3. 没有休眠功能
4. 引导界面按键盘无响应
5. 时间显示错误，没有同步时间
6. 没有蓝牙模块，且蓝牙不可用
7. 系统版本为 beta,但是控制中心出现更新 beta版本的发布日志更新
8. 应用商店中无应用
9. 修改亮度无效果
10. 调节色温无效果
11. 无声音输入输出设备
12. 深度之家标题栏错位重叠
13. 无线网络未识别，无法使用
14. 文件管理器中无法挂载其他操作系统的分区
15. 桌面异常卡死
16. 任务栏异常崩溃
