### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【发散测试】【终端】开启 禁用Ctrl + S 和 Ctrl + Q控制后，在终端设置Ctrl + S 为自定义快捷键时会出现设置失败

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#4612]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
终端 6.0.5+rb1
```

### PRE-REQUIREMENT | 预置条件

1. 已经在终端中开启 禁用Ctrl + S 和 Ctrl + Q控制

### STEPS TO REPRODUCE | 复现步骤

1. 将 Ctrl + S 设置为 自定义快捷键

### OBSERVED RESULT | 观察到的结果

设置失败，冲突
![录屏_dde-desktop_20230601163434](https://github.com/linuxdeepin/developer-center/assets/96416089/8ea3fc29-4afa-417c-81ad-ae0e2939fd51)

### EXPECTED RESULT | 期望的结果

当开启了 禁用Ctrl + S 和 Ctrl + Q控制时，可以将 Ctrl + S 和 Ctrl + Q 设置为快捷键

### ADDITIONAL INFORMATION | 额外补充

1.   当开启了 禁用Ctrl + S 和 Ctrl + Q控制时，Ctrl + S 和 Ctrl + Q快捷键在终端中即处于未被占用的情况，那么在终端编辑器中应该是可以将 Ctrl + S 和 Ctrl + Q设置为快捷键；
2.  在设置的时候没有冲突提示，同时也设置不了

**Comment by babyfengfjx** [comment]
@ArchieMeng 郭垚反馈的问题，可以帮忙优化。

**Comment by wineee** [comment]
我测试情况是可以设置

**Comment by asterwyx** [comment]
这个问题还需要再澄清一下，假如允许在关闭流控制之后使用Ctrl+S作为自定义快捷键。那么用户设置了自定义快捷键之后重新开启流控制的行为是什么。

**Comment by luodeepin** [comment]
验证通过
终端 6.0.6

禁用后可以按照shell命令执行
![截图_选择区域_20230804140322](https://github.com/linuxdeepin/developer-center/assets/96416089/5f3a3db9-f7a2-4bfa-9720-fe1310794abb)

**Comment by babyfengfjx** [comment]
@SuperEffie   请在最新版本再次确认此问题的状态，如已经修复集成，请同步issue正确状态。

**Comment by SuperEffie** [comment]
[集成链接]：https://github.com/linuxdeepin/developer-center/issues/5114
[版本信息]：deepin-terminal：6.0.6
[验证结论]：测试通过，取消“禁用Ctrl+S和Ctrl+Q控制”，自定义命令使用Ctrl+S快捷键，可正常设置
[录屏信息]：
![ls](https://github.com/linuxdeepin/developer-center/assets/58986464/207be69e-7f04-47df-8646-a0f75d90e44a)

**Comment by luodeepin** [comment]
验证通过
终端 6.0.6

禁用后可以按照shell命令执行
