### ISSUE TITLE
Deepin Fresh Install ... not booting up ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#462]
Hi,

I just installed Deepin on my nephew's HP laptop UEFI with secure boot disabled(the live USB devices wouldn't pickup with secure boot enabled) ... I installed Kali Linux followed by Deepin OS over a Windows 10 system.

Issues faced : 

1. Kali was installed successfully but failed to boot into Kali grub, i went ahead installing Deepin OS as planned after Kali hoping the Deepin Grub would take control of the system boot. To my surprise even Deepin OS failed to take control of the system Grub.

2. I however checked the Kali Install by booting through EFI Kali entry and i was faced with the Deepin Grub (my God this EFI boot is such a pain, never works in a simple manner) ... i tried booting into the freshly installed Deepin 15.5 ... but it got stuck ... i had to hit Ctrl+Alt+Del ... I tested Kali from the Deepin GRUB assessed through EFI entry ... Kali booted fine ... I retried Deepin on my third attempt, even this attempt i just couldn't boot into Deepin OS ... following is the screen where it was stuck !!!

![Deepin Boot Stuck](https://user-images.githubusercontent.com/3283676/35449146-2ed1b242-02e2-11e8-8b4a-c61a25941021.jpeg)

Beside the never ending boot issues i am already facing with my personal system ... i never expected a fresh install on my nephew's system too would face a boot issue ...

Guys really like one of you to look into the boot issue on my system [as described here](https://github.com/linuxdeepin/developer-center/issues/440) ... and ... this current boot issue i am facing with a fresh install on my Nephew's system ...

its getting really annoying ...

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
