### ISSUE TITLE
Xorg variant removed when session ends

### ISSUE THREAD

**Issue by pyfection** [linuxdeepin/developer-center#463]
I have installed Deepin with Architect on two very different machines and have encountered the same issue. Every time I lock the screen, suspend or otherwise terminate the session, my Programmer Dvorak variant of the US layout gets removed and I have to enable it manually after logging back in with "setxkbmap -variant dvp" after which it works fine again. This is very annoying, so I hope you can fix it or provide me with a work around. Otherwise, Deepin is my favorite DE, so keep up the good work!

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
