### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【论坛反馈】【终端】终端设置为Noto Sans SignWriting字体后,光标无法移动至最后,且删除文字时终端文字展示异常

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#4641]
### SUMMARY | 问题概要

必现问题

https://bbs.deepin.org/post/257766

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
内核信息: Linux test-PC 6.1.11-amd64-desktop-hwe #23 SMP PREEMPT_DYNAMIC Mon Feb 27 17:25:36 CST 2023 x86_64 GNU/Linux

终端:6.0.5+rb1
```

### PRE-REQUIREMENT | 预置条件

在终端中设置字体为Noto Sans SignWriting

### STEPS TO REPRODUCE | 复现步骤

1、输入命令sudo apt update,光标移动至中间后使用方向键→键,观察是否可以将光标移动至结尾处

2、使用退格键，观察删除文字时，终端文字是否展示正常

### OBSERVED RESULT | 观察到的结果

1、光标移动至中间后使用方向键→键,无法将光标移动至结尾处

2、使用退格键，删除文字时，终端文字展示异常

https://github.com/linuxdeepin/developer-center/assets/62528742/811056a1-a60d-4b97-aab6-9ba97397409c

### EXPECTED RESULT | 期望的结果

使用该字体进行以上操作时和其他字体保持一致，能够操作及显示正常

**Comment by babyfengfjx** [comment]
@ArchieMeng  请帮忙优化~

**Comment by SuperEffie** [comment]
[版本信息]：deepin-terminal：6.0.5
[验证结论]：显示依赖关系不满足，待重新提交deb包进行验证

**Comment by SuperEffie** [comment]
[镜像地址]：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516/
[版本信息]：deepin-terminal：6.0.5
[验证结论]：验证通过，屏蔽了Noto Sans SignWriting字体
[截图信息]：
![截图_dde-desktop_20230620141431](https://github.com/linuxdeepin/developer-center/assets/58986464/3932c0c1-de2a-42b3-a03b-da96823fd96e)
