### ISSUE TITLE
文本编辑器编码问题

### ISSUE THREAD

**Issue by lizipeng0013** [linuxdeepin/developer-center#4654]
### SUMMARY | 问题概要

![录屏_dde-desktop_20230604210937](https://github.com/linuxdeepin/developer-center/assets/123794418/3a604548-64e3-4fc2-9249-0589dfd8ebdd)
新建一个文本文档并使用文本编辑器打开，默认编码是utf-8，随便输入几个ASCII字符（英文、数字等），保存后再打开编码就变成了gb18030。
在20.8系统的文本编辑器（版本5.10.39）没有这个问题

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
系统版本：v20.9 软件版本：6.0.8
系统版本：v23 beta 软件版本：6.0.9
```

### STEPS TO REPRODUCE | 复现步骤

新建一个文本文档并使用文本编辑器打开，默认编码是utf-8，随便输入几个ASCII字符（英文、数字等），保存后再打开编码就变成了gb18030。

**Comment by lizipeng0013** [comment]
20.9系统的文本编辑器（版本6.0.8）：
![录屏_dde-file-manager_20230607195927](https://github.com/linuxdeepin/developer-center/assets/123794418/3f96ac83-13ac-40d8-b4b2-0b71b268d7b3)
20.8系统的文本编辑器（版本5.10.39）：
![录屏_dde-desktop_20230607195835](https://github.com/linuxdeepin/developer-center/assets/123794418/e08cf152-5b16-46d4-bf3c-c72ef5536fd9)

**Comment by babyfengfjx** [comment]
@SuperEffie  请复现该问题，分别对V20.9 /V23两个版本进行复合，如确认问题，请及时转移到PMS跟踪。

**Comment by SuperEffie** [comment]
@lizipeng0013  感谢您的反馈！实在是很用心的反馈了。
我们分别在deepin v20.9版本和deepin v23_beta版本上提了单进行跟踪，后期优化后在这通知您，欢迎您为我们反馈更多系统相关问题~

**Comment by SuperEffie** [comment]
> @SuperEffie 请复现该问题，分别对V20.9 /V23两个版本进行复合，如确认问题，请及时转移到PMS跟踪。
已提单：
v20.9版本bug单链接：https://pms.uniontech.com/bug-view-203903.html
v23_beta版本bug单链接：https://pms.uniontech.com/bug-view-203889.html

**Comment by black-desk** [comment]
加个环境变量来控制编码猜测行为算了

照目前这个意思 只要是纯英文的文本全部都会被猜成国标的。

这不扯淡么。

**Comment by SuperEffie** [comment]
子项目对该问题作遗留处理~
![image](https://github.com/linuxdeepin/developer-center/assets/58986464/02a4bba6-2ded-4519-a303-63c379c4c450)

**Comment by lizipeng0013** [comment]
![截图_deepin-home-appstore-client_20230729153318](https://github.com/linuxdeepin/developer-center/assets/123794418/d73f19c5-110b-4675-9186-59c9339bb44c)

纯英文就识别为gb18030真的有大问题

**Comment by UTsweetyfish** [comment]
（非研发意见）似乎 `/usr/share/dsg/configs/org.deepin.editor/org.deepin.editor.json` 可以控制这个行为

**Comment by SuperEffie** [comment]
该问题在deepin v23 beta2中文本编辑器版本6.0.13，该问题已不存在了
