### ISSUE TITLE
v23-Beta2 deepin-screen-recorder 6.0.2.63 集成(玲珑)

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#4655]
仓库地址： ll-cli repo modify http://10.0.36.228:9001/ --name develop-snipe

【应用】截图录屏
【包名】deepin-screen-recorder
【版本】6.0.2.63
【HASH】ed96ca36303b97f1719f5e8da3e076cf823ab8a2
【集成内容】bug修复

**Comment by Zeno-sole** [comment]
[2023-6-1-集成-社区版-V23-多媒体-音视频-截图录屏-测试申请单-20230601.zip](https://github.com/linuxdeepin/developer-center/files/11683181/2023-6-1-.-.-V23-.-.-.-.-20230601.zip)

**Comment by babyfengfjx** [comment]
@xuqi27837288  请开展集成验证。

**Comment by xuqi27837288** [comment]
【环境】：
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【结论】：
测试通过，暂无严重问题及影响
