### ISSUE TITLE
调整分辨率后桌面图标布局会乱

### ISSUE THREAD

**Issue by lizipeng0013** [linuxdeepin/developer-center#4666]
### SUMMARY | 问题概要

在调整分辨率后，需要记住原来的桌面图标布局（只记住曾经设置过的分辨率），有时候只是预览一下不同分辨率（或者不小心点到，只是点击了相应分辨率还没确认），在大的分辨率切换为小的分辨率之后，桌面图标就会重新排列，如果是确认切换了倒没什么，但如果取消不切换分辨率，原来大的分辨率下的桌面图标布局就和确认设置了一样无法恢复了，这个问题很影响使用
此问题是v20开始才有的，v15正常。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
系统版本：v23 beta
```

### STEPS TO REPRODUCE | 复现步骤

在一个大的分辨率（如1440x900）下，在桌面的最下方有桌面图标，切换为小的分辨率（如1024x768）后，最下方的桌面图标会因为分辨率减小而排到下一列，如果恢复到原来的分辨率，这个自动排到下一列的图标不会恢复到原来的位置

**Comment by lizipeng0013** [comment]
v15.9的桌面：
![6月8日 (1)(1)](https://github.com/linuxdeepin/developer-center/assets/123794418/efc901ad-ef6b-410b-9357-65f964b3bc08)
v23 beta的桌面：
![录屏_VirtualBox Machine_20230604155502](https://github.com/linuxdeepin/developer-center/assets/123794418/ee2690b2-fe32-46e8-91ed-91012be104fc)

**Comment by babyfengfjx** [comment]
@SuperEffie  此确认该问题。

**Comment by SuperEffie** [comment]
感谢您的反馈。当前v23beta版本中确实存在以上问题，我们已经提交issue进行跟踪，后续该问题会以issue:[#4674](https://github.com/linuxdeepin/developer-center/issues/4674)进行跟踪。现在我们先将这个issue关闭，您可以留意issue#4674的优化进展。
欢迎您为我们反馈v23beta更多的问题哦~
