### ISSUE TITLE
任务栏上的应用图标显示BUG

### ISSUE THREAD

**Issue by zhang-guanghao** [linuxdeepin/developer-center#4667]
### SUMMARY | 问题概要

任务栏上的图标会出现如下BUG：
1、有时候，一个应用会出现两个图标，如下图 ：
![image](https://github.com/linuxdeepin/developer-center/assets/7907975/9a858702-5a68-456d-b85c-1fea21e38c9f)

2、有时候，已经启动的应用在任务栏无图标。导致应用最小化后，找不到了。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
Distribution: Deepin V23 Bate
```

### STEPS TO REPRODUCE | 复现步骤

偶发

**Comment by BLumia** [comment]
> 已经启动的应用在任务栏无图标。导致应用最小化后，找不到了

这个也是偶发？已知都有哪些应用会触发这个问题？

**Comment by BLumia** [comment]
过久缺少更多信息，无法在新的环境下复现，予以关闭。如果后续仍有类似问题，请开新的 issue 并提供详细的信息进行反馈，以便后续的复现与修复。
