### ISSUE TITLE
Changing background can hang apps

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/developer-center#467]
HOW TO REPRODUCE:
1. Install the app "Variety".
2. Configure it to change background every 1 minute.

RESULT:
- When the background changes the entire desktop lags, and videos and audio play freeze for a second.
- From time to time applications permanently freeze.

LIKELY FIX:
- Set the wallpaper changing as a background process, with low CPU priority.
- Each time you change wallpaper, Deepin places a copy of it in "~/Pictures/Wallpapers". Likely that's the most computational expensive operation.

RELEVANT DETAILS:
- Having a Wallpapers backup folder is also creating [another compatibility issue with Variety](https://github.com/varietywalls/variety/issues/4).

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
