### ISSUE TITLE
在20.9版本中，使用不背单词声音严重失真。

### ISSUE THREAD

**Issue by ghost-turing** [linuxdeepin/developer-center#4672]
### SUMMARY | 问题概要

通过UEngine，安装最新版本的“不背单词”app，无论以哪种模式运行，单词声音严重异常，几乎到了不能使用的地步。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
distribution:deepin v20.9
package:cn.com.langeasy.LangEasyLexis  v5.5.2
```

### STEPS TO REPRODUCE | 复现步骤

1.安装不背单词
2.选择任一词书
3.点击主页左下角“learn”
4.进入单词学习页面后，点击单词，单词朗诵声音速度非常快，完全难以听清说的什么。

### OBSERVED RESULT | 观察到的结果

单词朗诵声音速度非常快，完全难以听清说的什么

### EXPECTED RESULT | 期望的结果

单词朗诵声音速度正常。

**Comment by babyfengfjx** [comment]
@ghost-turing   非常感谢能够反馈问题，对于UEngine 这类非官方支持的应用，目前官方没有人力投入去做分析优化，特别是这类非官方上架的安卓应用，如果是上架安卓应用有此类问题，大概率也只能下架处理。

可以尝试使用其他应用代替现有应用，看是否能满足，此问题也可以在论坛发帖讨论，看是否有坛友有相关解决方案，此issue我们先做关闭处理，如有其他版本问题，可以随时提交issue反馈，再次感谢~
