### ISSUE TITLE
v20.9-锁屏状态下无法使用小键盘输入密码

### ISSUE THREAD

**Issue by crudb0y69** [linuxdeepin/developer-center#4675]
### SUMMARY | 问题概要

系统启动或者在锁屏状态下，小键盘无法输入密码，必须点一下密码输入框才能使用小键盘

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
Deepin GNU/Linux 20.9
```

### STEPS TO REPRODUCE | 复现步骤

1. 锁屏
2. 使用小键盘输入密码解锁

### OBSERVED RESULT | 观察到的结果

小键盘无法输入

### EXPECTED RESULT | 期望的结果

正常输入

**Comment by BLumia** [comment]
与 https://github.com/linuxdeepin/developer-center/issues/4541 重复，请转到那个 Issue 跟进。感谢
