### ISSUE TITLE
[wallpapers] duplicate storage of blurred images ?

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/developer-center#468]
During installation **deepin-wallpapers** stores the blurred versions in **/var/cache/image-blur**
Now I just realized that there are additional copies of blurred images in **~/.cache/dde/deepin-desktop/1/**
At the same time I noticed that on first login displaying of blurred backgrounds takes quite a while as if the blurred versions would just be created.
Can you please explain how this works?
Should I store blurred images directly in $HOME to improve first login speed? Simply copying the content of **/var/cache/image-blur** won't work because the naming convention of files is different there...
Thank you.

**Comment by hualet** [comment]
Blurred version of the wallpapers should be packaged with the wallpapers, I don't know what's really happening here @felixonmars

**Comment by oberon2007** [comment]
Yes, the blurred versions are installed in /var/cache/image-blur as I said, but still!

**Comment by SalahAdDin** [comment]
Related: https://github.com/linuxdeepin/deepin-wallpapers/issues/2

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
