### ISSUE TITLE
文本编辑器bug

### ISSUE THREAD

**Issue by lizipeng0013** [linuxdeepin/developer-center#4680]
### SUMMARY | 问题概要

![录屏_dde-desktop_20230612145236](https://github.com/linuxdeepin/developer-center/assets/123794418/b1b9809f-51c5-4056-8892-ac1f2a400396)
未选中任何文本的情况下，按复制快捷键Ctrl+C后会将之前复制到剪切板的内容清空，再按Ctrl+V就粘贴不了了

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
系统版本：23 beta
软件版本：6.0.9
```

### STEPS TO REPRODUCE | 复现步骤

先复制一段文本，然后在未选中任何文本的情况下，按复制快捷键Ctrl+C

### OBSERVED RESULT | 观察到的结果

此问题在v15.9的文本编辑器已存在

**Comment by xuqi27837288** [comment]
https://pms.uniontech.com/bug-view-204477.html
在pms上已提单跟踪~

**Comment by xuqi27837288** [comment]
待文本编辑器子项目修复后,附上相关处理信息及回归测试该问题单~

**Comment by xuqi27837288** [comment]
待文本编辑器子项目修复后,附上相关处理信息及回归测试该问题单~

**Comment by xuqi27837288** [comment]
待文本编辑器子项目修复后,附上相关处理信息及回归测试该问题单~

**Comment by xuqi27837288** [comment]
待文本编辑器子项目修复后,附上相关处理信息及回归测试该问题单~

**Comment by xuqi27837288** [comment]
待文本编辑器子项目修复后,附上相关处理信息及回归测试该问题单~

**Comment by lizipeng0013** [comment]
deepin V23 RC预装的6.0.16仍未修复此问题
