### ISSUE TITLE
磁盘空间不足时频繁弹窗报警

### ISSUE THREAD

**Issue by fishBone000** [linuxdeepin/developer-center#4685]
### SUMMARY | 问题概要

home空间不足时，屏幕上方频繁弹窗提示：“系统系统空间不足，请及时清理！”，大概一分钟来一次

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin v20.9
```

### PRE-REQUIREMENT | 预置条件

根目录和home目录分开两个分区，其中home分区用df查看占用达到100%

文件系统        容量  已用  可用 已用% 挂载点
/dev/sda2        73G   69G  388M  100% /home

### STEPS TO REPRODUCE | 复现步骤

把home塞满

### OBSERVED RESULT | 观察到的结果

屏幕上方频繁弹窗提示：“系统系统空间不足，请及时清理！”

### EXPECTED RESULT | 期望的结果

至少一两个小时提示一次，或者登录的时候提示

**Comment by BLumia** [comment]
这个不是 bug，预期行为就是这样的。

@meiyixiang 可以看看要不要调整需求。

**Comment by fishBone000** [comment]
建议调整一下……一分钟弹一次太烦了= =

**Comment by black-desk** [comment]
相关的代码在这个位置：

https://github.com/linuxdeepin/dde-daemon/blob/3c69413138c2f87730c297f50e1c4fa3c131ec15/housekeeping/init.go#L53

另外就，只检查家所在的分区是不是有点不合理？

我们不应该会那么关心家的大小？

**Comment by SuperEffie** [comment]
【包下载链接】：https://ci.deepin.com/repo/obs/deepin:/CI:/linuxdeepin:/dde-daemon:/PR-526/deepin_develop/amd64/dde-daemon_6.0.17%2Bu009_amd64.deb
【问题备注】：Home目录下被占满后，文件管理器会崩溃，该问题先做遗留处理

**Comment by BLumia** [comment]
这个 issue 的后续在 https://github.com/linuxdeepin/developer-center/issues/4823 跟进吧，可能是用户在深度之家和 GitHub 两个地方都反馈了所以导致的 Issue 重复。这个就作为重复关闭掉了。

再次感谢反馈，不过后续反馈的话，深度之家和 GitHub Issue 二选一反馈就行了，推荐前者 :)
