### ISSUE TITLE
开机进入命令行，无法登录

### ISSUE THREAD

**Issue by gramer-cn** [linuxdeepin/developer-center#4686]
### SUMMARY | 问题概要

1. 制作linux to go，初始化成功后关机。
2. 拔掉u盘启动windows11，自动进入bitlocker，输入恢复密钥，使windows11可正常使用。
3. 关机重新插上u盘，开机后过完deepin开机动画，黑屏进入命令行，无法进入登录界面（高频），关键提示：WARNING：Unprivileged eBPF is enabled with eIBRS on, data leaks possible via Spectre v2 BHB attacks!
探索过程：
- 该类问题在deepin v20也出现过，可能关键提示不同（不记得了）
- 乌班图会导致windows11也无法启动
- 使用manjaro未出现该问题

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin v23
```

### PRE-REQUIREMENT | 预置条件

笔记本型号：suface laptop go2  操作系统：windows11
u盘：联想X3C Max
使用官方提供的工具，将u盘制作为系统盘
安装选项均为推荐选项

### STEPS TO REPRODUCE | 复现步骤

1. 插上u盘，电源开机
2. 等......

### OBSERVED RESULT | 观察到的结果

同社区该问题：https://bbs.deepin.org/post/246415

### EXPECTED RESULT | 期望的结果

可以登录

**Comment by BLumia** [comment]
> 使用官方提供的工具，将u盘制作为系统盘

这个指的是 deepin-boot-maker 启动盘制作工具？

**Comment by babyfengfjx** [comment]
你说的这个linux  to  go，是你把系统已经安装到了你的U盘上了是吧？
有尝试过直接安装多系统么？不确定V23的驱动是否适配你这块设备，如果不兼容或者某些设置的差异也可能存在一些问题，目前在现有物理设备上没有遇到或者能复现类似问题。

倒是这个报错我在虚拟机中出现过，强行异常关机的时候出现的：
![image](https://github.com/linuxdeepin/developer-center/assets/24642999/09be2327-762e-4e03-a4db-8d77bf9ea14c)

**Comment by gramer-cn** [comment]
对，官网的百度网盘链接下的

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Gary Wang ***@***.***>
发送时间: Tuesday, June 13, 2023 1:15:38 PM
收件人: linuxdeepin/developer-center ***@***.***>
抄送: gramer ***@***.***>; Author ***@***.***>
主题: Re: [linuxdeepin/developer-center] 开机进入命令行，无法登录 (Issue #4686)


使用官方提供的工具，将u盘制作为系统盘

这个指的是 deepin-boot-maker 启动盘制作工具？

―

**Comment by babyfengfjx** [comment]
@gramer-cn   了解，此类现象也咨询了下研发，大概率是一些硬件兼容性不稳定，然后这种linux  to  go  虽然可以装，但是稳定性也是比较差，目前这类问题是没有人能够提供相关分析了，主要有几个客观因素：
1. 此安装方式非推荐安装方式，非正常研发适配场景；
2. 无对应硬件设备，无法复现相关场景；
3. 适配的设备无法复现该场景，不好确定是否属于通用性问题，研发侧无法着手分析；

依当前客观原因，此问题可能无人能跟进，此issue我们先做关闭处理，如果后续在使用V23系统，发现基本功能问题可以随时反馈。

此现象可能也有其他人遇到，可以在论坛发帖讨论，或许其他坛友有相关解决方案。
再次感谢你的反馈~
