### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【发散测试】【DDE】【任务栏】【偶现】连接高分屏，缩放比1.5，高效模式下 微信或企业微信接收到消息时点击托盘图标打不开

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#4688]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
内核 6.1.11-amd64-desktop-hwe #23.01.00.14
dde-dock       6.0.16
```

### PRE-REQUIREMENT | 预置条件

1. 连接高分屏
2. 缩放比为 1.5
3. 任务栏为高效模式
4. 已经登录 微信 或 企业微信

### STEPS TO REPRODUCE | 复现步骤

1. 当微信 或 企业微信 接收到消息时，等待1分钟后  -  点击托盘区域上的 微信 或 企业微信 图标打开微信 或 企业微信

### OBSERVED RESULT | 观察到的结果

1. 高效模式下 微信或企业微信接收到消息时点击托盘图标打不开
![录屏_选择区域_20230613140956](https://github.com/linuxdeepin/developer-center/assets/96416089/d226650b-8c8d-4b95-881a-aafc34aa9cbe)

### EXPECTED RESULT | 期望的结果

1. 点击托盘区域上的 微信 或 企业微信 图标打开微信 或 企业微信

**Comment by babyfengfjx** [comment]
@BLumia  请帮忙优化~

**Comment by tsic404** [comment]
和 @justforlxz 使用 DDE_DISABLE_STATUS_NOTIFIER_WATCHER=1 把SNI禁掉后，这儿的托盘(Xembed)就工作正常了🤣，怀疑是dde-daemon中的问题。

**Comment by ArchieMeng** [comment]
昨天看了下，确定疑似使用XEvent来传递事件的应用都会出现问题，和高分屏无关。必现条件仅为：
- docker高效模式
- 微信，企业微信等会使用XEvent传递事件（鼠标悬停，鼠标点击）
- 开启将多余显示图标收起来的功能
- 将此类应用拖放到收起栏然后又拖出来

**Comment by tsic404** [comment]
高效模式和时尚模式是两份托盘导致。。。。

**Comment by kegechen** [comment]
提测

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0516镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
【截图录屏】：


Uploading 录屏_选择区域_20230825141556.mp4…
