### ISSUE TITLE
Regarding Application Proxy

### ISSUE THREAD

**Issue by sreekanthvk** [linuxdeepin/developer-center#469]
Dear Team,

I am using Manjaro Deepin. I am working an institution where we use proxy. I have set the application proxy with proxy type _http_. and selected pamac-manager to _Open by Proxy_. But unfortunately it could not fetch the things while using AUR in pamac-manager. It works fine with normal updates. It looks like we need to set the proxy type as https rather than http. 
If I call octopi from terminal, (I have set the proxy as per arch standards also, apart from the proxy in control center) I could update the AUR packages, else I am getting connection issues. 

It will be great if you could pour some light on this issue. 

Thanks and Regards,
Sreekanth

**Comment by hualet** [comment]
@electricface

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
