### ISSUE TITLE
Theme icons missing from fresh Arch install.

### ISSUE THREAD

**Issue by kerk12** [linuxdeepin/developer-center#470]
I installed a fresh Arch system an right after, installed the `deepin` and `deepin-extra` groups from the Arch community repo. 

I noticed a lot of icons were missing in the file manager and the dock.

The problem was resolved by installing `deepin-icon-theme` from the community repo.

I posted a thread on the [arch forums](https://bbs.archlinux.org/viewtopic.php?id=234238), detailing the issue.

Screenshot:
[Click here](https://i.imgur.com/8vMSQnI.png).

The issue needs investigation as it affects new Arch installations.

**Comment by felixonmars** [comment]
Indeed. I have uploaded deepin-desktop-schemas 3.2.6-3 to include the missing dependency.

**Comment by kerk12** [comment]
Thank you, sir! 🥇
