### ISSUE TITLE
deepinid云服务模块集成申请

### ISSUE THREAD

**Issue by Keima-lpj** [linuxdeepin/developer-center#4702]
### package information | 软件包信息

包名|版本
-- | --
deepin-sync-daemon | 6.0.23.0
deepin-sync-client | 7.0.0.1
deepin-deepinid-plugin | 2.0.0.2

### Package repository address | 软件包仓库地址

deb  [trusted=yes] https://aptly.uniontech.com/pkg/beige-v2/release-candidate/ZGVlcGluaWTkupHmnI3liqHnrKzkuIDova4yMDIzLTA2LTAyIDE2OjE1OjU3/  unstable main
deb  [trusted=yes] https://aptly.uniontech.com/pkg/nonfree-beige-v2/release-candidate/ZGVlcGluaWTkupHmnI3liqHnrKzkuIDova4yMDIzLTA2LTAyIDE2OjE1OjU3/  unstable non-free

### changelog | 更新信息

<b>集成了专业版最新版本的云服务功能</b>

### test suggestion | 测试建议

1.请参照专业版需求文档进行测试

### Sphere of influence | 影响范围

<b>本次集成后，所有deepinid相关的功能都已就绪。</b>

```[tasklist]
### Tasks
```

**Comment by babyfengfjx** [comment]
@xuqi27837288   请参考@廖璞健提供的需求文档，熟练掌握需求内容，并开展对应的集成测试。

**Comment by Keima-lpj** [comment]
专业版需求文档见  https://doc.uniontech.com/docs/TuOa0ZPKKqIrNNte

**Comment by xuqi27837288** [comment]
冒烟测试不通过,基本功能不可用,相关问题已反馈并提单~测试结论:测试不通过~

https://pms.uniontech.com/bug-view-205223.html
https://pms.uniontech.com/bug-view-205221.html
https://pms.uniontech.com/bug-view-205215.html
https://pms.uniontech.com/bug-view-205209.html
