### ISSUE TITLE
【deepin_V23_beta2】【提示】【有空】【集成测试】【deepin ID】中文环境下控制中心中deepin ID下方提示文字未国际化展示为Union ID

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#4705]
### SUMMARY | 问题概要

必现问题

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
内核信息: Linux test-PC 6.1.11-amd64-desktop-hwe #23 SMP PREEMPT_DYNAMIC Mon Feb 27 17:25:36 CST 2023 x86_64 GNU/Linux

控制中心:6.0.20
```

### PRE-REQUIREMENT | 预置条件

deb [trusted=yes] https://aptly.uniontech.com/pkg/beige-v2/releasecandidate/ZGVlcGluaWTkupHmnI3liqHnrKzkuIDova4yMDIzLTA2LTAyIDE2OjE1OjU3/ unstable main
deb [trusted=yes] https://aptly.uniontech.com/pkg/nonfree-beige-v2/releasecandidate/ZGVlcGluaWTkupHmnI3liqHnrKzkuIDova4yMDIzLTA2LTAyIDE2OjE1OjU3/ unstable non-free

添加以上集成测试仓库

### STEPS TO REPRODUCE | 复现步骤

1、中文环境下进入控制中心，观察deepin ID模块下方文字提示信息

### OBSERVED RESULT | 观察到的结果

文字提示信息展示为:Union ID、cloud sync、shop

![截图_选择区域_20230616102708](https://github.com/linuxdeepin/developer-center/assets/62528742/00d674ae-e0b5-46e2-90c1-2f71e8699d28)

### EXPECTED RESULT | 期望的结果

文字提示信息展示为中文：deepin ID、云同步、应用商店

**Comment by babyfengfjx** [comment]
@xuqi27837288  请转移到PMS跟踪deepin  ID项目问题。
