### ISSUE TITLE
fatal: Authentication failed for 'https://cr.deepin.io/dde/dde-dock/'

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#471]
Whenever I try to send a patch using "git review master", it asks for my gerrit Username and Password. I don't know what's the password, I just enter my github password and I get this message, 
fatal: Authentication failed for 'https://cr.deepin.io/dde/dde-dock/'

How do I fix this?

**Comment by kirigayakazushin** [comment]
Do you follow the requirements of Wiki?

https://github.com/linuxdeepin/developer-center/wiki/Contribution-Guidelines-for-Developers-en

**Comment by SiamSami** [comment]
Yes. But it's okay I don't need it anymore. I didn't knew I could send PR
from Gerrit. So I am gonna send PR from Gerrit.
