### ISSUE TITLE
chromium-codecs-ffmpeg-extra package

### ISSUE THREAD

**Issue by j16180339887** [linuxdeepin/developer-center#472]
I am using opera browser which is chromium-based.

Whenever I open this page https://www.youtube.com/html5

it says I don't have h.264 codecs installed which is really inconvenient.

Videos on sites like https://www.bilibili.com is also unavailable.

Include this package would be really helpful.

非常感謝

**Comment by hualet** [comment]
NO, I don't think it's a good idea since we didn't pay them for the license fees.

**Comment by j16180339887** [comment]
Thank you for clarifying that.
