### ISSUE TITLE
【V23beta2 】neofetch支持

### ISSUE THREAD

**Issue by meiyixiang** [linuxdeepin/developer-center#4728]
【产品现状】： 无法直接从软件仓库里面安装neofetch
【产品期望】： 希望添加neofetch这个包，毕竟这个软件非常常用

**Comment by meiyixiang** [comment]
你有没有什么比较好的工具推荐？

**Comment by xzl01** [comment]
用hyfetch吧，在neofetch出现严重问题前 neodetch也继续被提供

**Comment by xzl01** [comment]
neofetch已经提集成 新打包替代品fastfetch

**Comment by xzl01** [comment]
> neofetch上游维护者已经失踪将近两年以上
> 
> 而且现行的neofetch对loongarch架构支持不正确
> 
> 我希望这个需求可以变成提供neofetch的替代品

这过不正确指的是什么

**Comment by xzl01** [comment]
https://github.com/linuxdeepin/developer-center/issues/4755

**Comment by xuqi27837288** [comment]
安装neofetch成功，验证通过



![image](https://github.com/linuxdeepin/developer-center/assets/62528742/1133d255-0499-4a8a-ac2b-b063512ff7f1)

**Comment by xzl01** [comment]
决议提出使用fastfetch 替换 neofetch 目前状态：其依赖包yyjson打包完成

**Comment by UTsweetyfish** [comment]
决议?

**Comment by babyfengfjx** [comment]
@xuqi27837288 请在最新版本中核实是否已经修复合入，如没有合入请将修复优先级调整为1级，已经修复请关闭问题单。

**Comment by xuqi27837288** [comment]
@Zeno-sole 麻烦帮忙合入后提交集成验证，谢谢~
