### ISSUE TITLE
Controlling system sounds volume ... too loud rips through my music/video volume

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#473]
Hi,

Is there any way i can reduce the system sounds(boot sound, notification sounds, error sounds) ... they are louder than the music and movie sound i usually listen to ... hits hard on your ears !!!

I just want the system sounds to be there in the background !!!

any way i can manually modify the default sound level values ?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
