### ISSUE TITLE
Telegram does not start

### ISSUE THREAD

**Issue by expwez** [linuxdeepin/developer-center#474]
When the application starts, nothing happens. Here is the startup in the terminal:
![image](https://user-images.githubusercontent.com/14634402/36146714-333c542e-10be-11e8-98ce-e4a91bec8593.png)
```(telegram-desktop:2624): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(telegram-desktop:2624): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
QApplication: invalid style override passed, ignoring it.

(telegram-desktop:2624): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplayManager'

(telegram-desktop:2624): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(telegram-desktop:2624): GLib-GObject-CRITICAL **: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
```
Screenfetch:
![image](https://user-images.githubusercontent.com/14634402/36146765-625086a4-10be-11e8-94c6-0b6052b8bd75.png)

**Comment by hualet** [comment]
@felixonmars

**Comment by egorsheff** [comment]
Try this:
`bash -c "XDG_CURRENT_DESKTOP=NONE telegram-desktop — %u"`

**Comment by felixonmars** [comment]
@egorsheff It works for me.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
