### ISSUE TITLE
[Arch Linux] No Background, No window management, loading cursor

### ISSUE THREAD

**Issue by tsiegleauq** [linuxdeepin/developer-center#475]
While using arch with Nvidia (proprietary drivers and 2 active monitors), Deepin does strange things after logging in from (the surprisingly unresponsive) lightdm:

- No background
- No right click on background
- While over the black Background the cursor is in "hourglass mode"
  - While over the dock or the side panel the cursor looks normal
- No Workplace management
- No window management
  - Windows indeed kinda open and close, but you cannot move them or interact with them normally
- dock works
- side panel works

Looks like some issues with the window manager rather than dde

Since I indeed have the dock and the panel working and not having brightness issues, it does not seem to be related to [366](https://github.com/linuxdeepin/developer-center/issues/366) and [213](https://github.com/linuxdeepin/developer-center/issues/213)

**Comment by dodedodo33** [comment]
Sounds like what my laptop does when I have multiple external screens connected, but mine eventually continues to load. If you can start a terminal (ctrl-alt t), then try running `journalctl -r`, maybe there are some interesting error messages or debug messages?

**Comment by tsiegleauq** [comment]
There is indeed. dde-desktop throws some core dumps, but I cannot really figure out what the problem seems to be.
[journalctrl.txt](https://github.com/linuxdeepin/developer-center/files/1738321/journalctrl.txt)

**Comment by dodedodo33** [comment]
Hmm, this might be related to #374.
They say it is fixed on the master branch, some tips are provided in the issue comments how to build the newer packages.
But strange thing is the difference in outcome from the errors as specified in these issues. As for my issue the segfaults show up but the system still continues, be it after about 20 seconds or so. But in your case it doesn't.

I'm not a deepin developer and don't know that much about the project but what stands out to me in your log is the `org.freedesktop.miracle.wifi` issues, where it is complaining about not having the service files. This seems like an incorrectly installed package?
And the other thing: `daemon/launcher[1208]: manager.go:259: queryPkgName failed: Manager.desktopPkgMap is nil`. I don't know if these have any effect on booting, but maybe interesting to look at for the developers.

**Comment by hualet** [comment]
It seems that deepin-wm crashes.
@sonald

**Comment by sonald** [comment]
I see no crash of wm in journalctrl.txt, but the last info is `Feb 19 23:14:23 SeanPC startdde[1152]: startmanager.go:392: exit status 1`, could be an issue of startdde ? @hualet

**Comment by hualet** [comment]
@jouyouyun

**Comment by jouyouyun** [comment]
@sonald it is the normal error output.

**Comment by decfpc** [comment]
I have exactly the same problem. I recently had to restore a full system backup (it was Manjaro 17.0.4 at the time I believe) and then went to upgrade all packages. After a reboot, all symptoms you mentioned (wallpaper is black and cannot be set, windows cannot be moved, some don't even have buttons for minimzing/maximizing/closing) occurred. My machine is a netbook with NVIDIA Optimus technology, using one screen only. 

I don't have any segfaults in journalctl, only the `startdde: startmanager.go:392: exit status 1` comes up like 10 times.

**Comment by hualet** [comment]
The keybindings should be still working, right? Can you please open an terminal and start deepin-wm manually and see what happens?

**Comment by tsiegleauq** [comment]
> The keybindings should be still working, right? Can you please open an terminal and start deepin-wm manually and see what happens?

indeed.
deepin-wm gave me the following issue:

`deepin-wm: error while loading shared libraries: libgranite.so.4: cannot open shared object file: No such file or directory`

on arch, i tried to install the `granite` package which lead to the information that I currently have `granite-bzr` installed.
`granite-bzr` is a dependency of the pantheon desktop ( I installed it in the past using [this repository ](https://wiki.archlinux.org/index.php/Pantheon#Unofficial_repository))

I removed all the *-bzr packages and re-installed `deepin` and `deepin-extra`.
It's working now!

I would advice the deepin-project to check the integrity if the dependencies (e.g. are you REALLY using granite or some fork if granite? If so, throw an error during installation).

**Comment by hualet** [comment]
@felixonmars

**Comment by felixonmars** [comment]
Third-party repositories are not guaranteed to work. The integrity inside official repos are always checked.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
