### ISSUE TITLE
After suspension deepin-wm doesn't start

### ISSUE THREAD

**Issue by FakeFBI** [linuxdeepin/developer-center#477]
`[madman@localhost ~]$ sudo deepin-wm --replace
No protocol specified

(deepin-wm:10924): Clutter-CRITICAL **: Unable to initialize Clutter: Unable to open display ':0'

(deepin-wm:10924): deepin-mutter-WARNING **: Unable to initialize Clutter.`
When I close the lid, deepin-wm doesn't start again until I reboot the computer.
The laptop model is HP Envy 13
System is Arch Linux.

**Comment by hualet** [comment]
Drop the sudo and try again.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
