### ISSUE TITLE
deepin-compressor deb 包插件异常

### ISSUE THREAD

**Issue by wineee** [linuxdeepin/developer-center#4776]
### SUMMARY | 问题概要

![image](https://github.com/linuxdeepin/developer-center/assets/22803888/92544d24-248f-4a7a-8ff8-10fe99b5b4a5)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin v23
deepin-compressor  6.0.0+u030
```

### STEPS TO REPRODUCE | 复现步骤

压缩 解压 7z/zip 格式都会出错

使用 deb 版，非玲珑版本

**Comment by babyfengfjx** [comment]
@luodeepin  调查一下在V23是否还支持deb格式的文档管理器，如支持，复现后需要进一步跟进修复，如不支持，也要清晰答复用户。

**Comment by babyfengfjx** [comment]
@wineee   在V23上是什么场景下玲珑格式的归档管理器无法满足需求，需要使用deb格式的应用吗？

**Comment by wineee** [comment]
> @wineee   在V23上是什么场景下玲珑格式的归档管理器无法满足需求，需要使用deb格式的应用吗？

需要，仅 deb 格式有问题，玲珑版本没有问题

**Comment by luodeepin** [comment]
亲~
我与归档管理器项目组了解到当前在社区版v23上默认是使用的玲珑格式的归档管理器，deb格式的归档管理器没有在 社区版v23上做过适配，也没有计划要适配v23的。当前 玲珑格式的可以正常解压、压缩，是可以满足基本需求的。请问你是出于什么原因要使用deb格式的，因为其实deb格式和玲珑格式的 归档管理器在功能上是一样的

**Comment by wineee** [comment]
反对放弃 deb 适配：

1. 玲珑目前只支持 x86，如果 deepin 未来想要适配 longarch 等架构，deb 包仍是首选
2. apt 是系统第一方包管理器，是最“原生”的选择，玲珑运行环境本身就需要占用不少空间，制作 live cd， wsl 这些情景期望是没有玲珑的
3. 其他系统（比如debian）移植需要
4. deb 仓库提供了此软件，仓库不应该集成有严重 bug 的版本，应该移出仓库或者修复错误，显然后者更好

**Comment by BLumia** [comment]
> deb格式的归档管理器没有在 社区版v23上做过适配，也没有计划要适配v23的。

确认下，这个是最终结论吗？ @babyfengfjx @meiyixiang

**Comment by shenmo7192** [comment]
> 反对放弃 deb 适配：
> 
>     1. 玲珑目前只支持 x86，如果 deepin 未来想要适配 longarch 等架构，deb 包仍是首选
> 
>     2. apt 是系统第一方包管理器，是最“原生”的选择，玲珑运行环境本身就需要占用不少空间，制作 live cd， wsl 这些情景期望是没有玲珑的
> 
>     3. 其他系统（比如debian）移植需要
> 
>     4. deb 仓库提供了此软件，仓库不应该集成有严重 bug 的版本，应该移出仓库或者修复错误，显然后者更好

1. 其实玲珑已经支持了arm...
2. 我同意你的观点，但是是否要这样做，要看官方的决定了。就像Ubuntu推广snap直接把仓库里的包删了
3. 这个其实不成立，最节省精力的移植这些应用的方式就是在Debian上面安装玲珑。主推玲珑包会让跨发行版移植简单很多，这是玲珑的优势
4. 移除仓库还是修复，至少应该做一个，不应该留一个坏的包在仓库里
