### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【内测反馈】【DDE】【桌面】将图片放到 /usr/share/wallpapers/custom-wallpapers目录下，设置为壁纸，重启后桌面壁纸显示为黑色

### ISSUE THREAD

**Issue by SuperEffie** [linuxdeepin/developer-center#4778]
### SUMMARY | 问题概要

【问题备注】：该问题为偶现问题

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516/
内核信息: 6.1.11-amd64-desktop-hwe 
版本信息：dde-session-shell:6.0.9
```

### STEPS TO REPRODUCE | 复现步骤

1. 复制一张图片，“以管理员身份打开”文件管理器，粘贴图片至/usr/share/wallpaper/custom-wallpapers目录下
2. 桌面右键点击，选择“壁纸与屏保”，选择步骤1中图片，点击按钮“同时设置”
3. 重启后登录进入桌面，观察桌面显示

### OBSERVED RESULT | 观察到的结果

桌面壁纸显示为全黑
![黑屏](https://github.com/linuxdeepin/developer-center/assets/58986464/cb65a442-05de-4d93-91fa-db0015d3edf8)

### EXPECTED RESULT | 期望的结果

重启登录桌面后，桌面依然显示为自定义的壁纸

**Comment by babyfengfjx** [comment]
@BLumia  请帮忙优化~

**Comment by dengbo11** [comment]
该问题DDE 显示壁纸已经设置成功，且工作区的壁纸也是正确的，就桌面壁纸存在问题。需要dde-desktop看下为啥设置重启（注销）后壁纸又被恢复了。

**Comment by SuperEffie** [comment]
【镜像地址】：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516/
【版本信息】：dde-session：1.1.5
【关联集成】：[#4912](https://github.com/linuxdeepin/developer-center/issues/4912)
【验证结论】：测试通过，自定义壁纸后，重启，壁纸保持不变
