### ISSUE TITLE
音訊無法切換到線路輸出（PCH）

### ISSUE THREAD

**Issue by laichiaheng** [linuxdeepin/developer-center#478]
使用了 Linux 4.16 核心後加上 amdgpu.dc=1 終於可以使用 HDMI 音效了，但現在無法切換到一般 PCH 的輸出，所以接上耳機也無法從耳機輸出音效。
現在明明顯示在 PCH，聲音卻還是從 HDMI 出來
![deepin _20180221020855](https://user-images.githubusercontent.com/9532105/36440983-30c68bda-16ac-11e8-991a-862b8cbcc2b0.png)

然後這是什麼狀況？
![deepin _20180221020941](https://user-images.githubusercontent.com/9532105/36441024-4ed3db5a-16ac-11e8-838d-19349720c486.png)

集好集滿
![deepin _20180221021513](https://user-images.githubusercontent.com/9532105/36441285-1b936570-16ad-11e8-88c2-295c19fcf087.png)

**Comment by hualet** [comment]
@jouyouyun

**Comment by jouyouyun** [comment]
贴一下 `pacmd list-cards` 和 `pacmd list-sinks` 的输出。

试着安装 `pavucontrol` 看下 '配置' 那一栏，是否有2个，有的话把hdmi的那个跳到 '关闭'

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
