### ISSUE TITLE
Shortcuts pinned to dock gets moved on app update

### ISSUE THREAD

**Issue by Peuczynski** [linuxdeepin/developer-center#480]
In efficiency mode (didn't test in fashion) when there is an app shortcut is pinned to dock in specific spot after update it gets moved.
I.e. I always keep firefox on as the first icon, after update it moves to somewhere in the middle

**Comment by laichiaheng** [comment]
Firefox always disappears when it is updated.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
