### ISSUE TITLE
对于Redmi Book Pro 14 2022的兼容性问题/Compatibility issues with Redmi Book Pro 14 2022

### ISSUE THREAD

**Issue by fangkuairen-steve** [linuxdeepin/developer-center#4804]
### SUMMARY | 问题概要

1. 在合盖休眠后唤醒，内置显示屏无法亮起/The built-in display screen cannot light up if the system wake up after closing the cover and sleeping.

2. 声音输入\输出设备无法识别/The operating system is not able to identify the sound input\output device

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
|---|---|
|distribution | Deepin Community Beta 23|
|theme | Macaron|
```

### PRE-REQUIREMENT | 预置条件

使用来自deepin官方下载站的镜像安装内核为6.1.11的amd64版deepin community beta 23\Install the amd64 version of deepin community beta 23 with kernel 6.1.11 using the image from the official download site

### STEPS TO REPRODUCE | 复现步骤

在任何开机且登录用户时合盖，开盖唤醒

### OBSERVED RESULT | 观察到的结果

内置显示器无法显示图像(外接HDMI显示器正常)

### EXPECTED RESULT | 期望的结果

解决对于Redmi Book Pro 14 2022的兼容性问题

**Comment by BLumia** [comment]
有相关异常输出吗？比如 dmesg / journalctl 的可能相关的日志信息？

**Comment by Decodetalkers** [comment]
声音问题可能是sof-firmware 的问题。

**Comment by BLumia** [comment]
过久未提供进一步信息，予以关闭。
