### ISSUE TITLE
Some of the keyboard shortcuts don't work (gnome wrapped)

### ISSUE THREAD

**Issue by Peuczynski** [linuxdeepin/developer-center#481]
This is very minor issue, but I think it's worth considering

Not listing all of the useful shortcuts to be editable in the control panel is one thing (since it's a personal opinion what is useful and what is not), but editing some of the shortcuts settings have no effect.

Please see the attached image: move-to-monitor-down and move-to-monitor-up don't work regardless of what keys are set

![deepinscreenshot_20180221084837](https://user-images.githubusercontent.com/12342833/36468586-31054bbc-16e4-11e8-850b-e4f8d30970af.png)

**Comment by hualet** [comment]
@sonald

**Comment by sonald** [comment]
This may be a problem of dde-control-center, which leaves a gap between two monitors. @Peuczynski can you paste output of xrandr?

**Comment by Peuczynski** [comment]
@sonald 

Screen 0: minimum 320 x 200, current 1920 x 2161, maximum 8192 x 8192
eDP-1 connected primary 1920x1080+0+1081 (normal left inverted right x axis y axis) 344mm x 193mm
   1920x1080     60.01*+  60.01    59.97    59.96    59.93  
   1680x1050     59.95    59.88  
   1400x1050     59.98  
   1600x900      59.99    59.94    59.95    59.82  
   1280x1024     60.02  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1440x810      60.00    59.97  
   1368x768      59.88    59.85  
   1280x800      59.99    59.97    59.81    59.91  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   640x400       59.88    59.98  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 475mm x 267mm
   1920x1080     60.00*+
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
   720x400       70.08  
DP-2 disconnected (normal left inverted right x axis y axis)

**Comment by sonald** [comment]
> eDP-1 connected primary 1920x1080+0+1081 
this should be eDP-1 connected primary 1920x1080+0+1080. it has been fixed.

**Comment by Peuczynski** [comment]
I can confirm there is not problem with shortcuts. After executing `xrandr --output eDP-1 --pos 0x1080` everything works as expected; the problem is with control center that always leaves 1 pixel gap between monitors when rearraging them in the display settings
