### ISSUE TITLE
音乐播放器似乎会跳过wav音频最后一秒

### ISSUE THREAD

**Issue by fishBone000** [linuxdeepin/developer-center#4816]
### SUMMARY | 问题概要

使用Deepin社区版20.9的 音乐 播放短wav音频（1秒左右）时我注意到播放器只会播放前100毫秒左右的部分。
比如这个页面里的音频：
https://wiki.teamfortress.com/wiki/Spy_voice_commands
对于稍微长一点的，比如2秒的音频，播放器会播放前1秒，而跳过后1秒的部分。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
Deepin 20.9
音乐 6.2.26
```

### STEPS TO REPRODUCE | 复现步骤

1. 访问https://wiki.teamfortress.com/wiki/Spy_voice_commands ，下载网页列表中任一音频
2. 用 音乐 播放

### OBSERVED RESULT | 观察到的结果

最后一秒左右的音频被跳过，音乐 自动切换到下一音频

### EXPECTED RESULT | 期望的结果

音频被完全播放

**Comment by fishBone000** [comment]
我用 VLC 3.0.17.7-deepin1播放，没有出现问题。
这个VLC是通过apt安装的。

**Comment by babyfengfjx** [comment]
@luodeepin   尝试复现下看看，V20和V23都核实一下。

**Comment by luodeepin** [comment]
已经提单跟踪：https://pms.uniontech.com/bug-view-206605.html
在 20.9存在此问题，23上正常
