### ISSUE TITLE
Unable to disable the window effect

### ISSUE THREAD

**Issue by laichiaheng** [linuxdeepin/developer-center#482]
![deepin-screen-recorder_desktop_20180221155318](https://user-images.githubusercontent.com/9532105/36468759-9fb4a69e-171f-11e8-848a-4fbcfede54df.gif)

**Comment by hualet** [comment]
@kirigayakazushin

**Comment by kirigayakazushin** [comment]
```
qdbus --literal com.deepin.WMSwitcher /com/deepin/WMSwitcher com.deepin.WMSwitcher.CurrentWM
```

```
qdbus --literal com.deepin.WMSwitcher /com/deepin/WMSwitcher com.deepin.WMSwitcher.RequestSwitchWM
```

Execute the two commands and tell me what I have exported.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
