### ISSUE TITLE
微信群聊中接收某些动态表情包出现显示问题

### ISSUE THREAD

**Issue by MrRedhat** [linuxdeepin/developer-center#4826]
### SUMMARY | 问题概要

在微信群聊中接收某些动态表情包，表情显示出现问题

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
系统版本：社区版(Beta)(23)
内核版本：Linux version 6.1.11-amd64-desktop-hwe (uos@uos-PC) (gcc (Uos 11.2.0-10) 11.2.0, GNU ld (GNU Binutils for Uos) 2.38) #23.01.00.14 SMP PREEMPT_DYNAMIC Fri May 12 14:47:29 CST 2023
微信版本：3.7.0.30deepin24
```

### PRE-REQUIREMENT | 预置条件

启动微信

### STEPS TO REPRODUCE | 复现步骤

1. 启动微信
2. 进入群聊
3. 接收动态表情，观察接收到的表情显示情况

### OBSERVED RESULT | 观察到的结果

![2023-06-28_16-14](https://github.com/linuxdeepin/developer-center/assets/60538386/1bfcfb8c-4f4f-42fd-ad56-e052d8db169f)
![2023-06-28_16-15](https://github.com/linuxdeepin/developer-center/assets/60538386/0d7e685d-e74f-4f4c-8aa6-2070e7af9ccd)

https://github.com/linuxdeepin/developer-center/assets/60538386/24cee81a-0c4a-4262-abc0-4c18868d3753

### EXPECTED RESULT | 期望的结果

动态表情能够正常显示

### ADDITIONAL INFORMATION | 额外补充

观察到目前为止，该BUG仅在微信群聊中接收到某些特定的动态表情包时出现，私聊或在群聊发送均没有表现。

**Comment by babyfengfjx** [comment]
@vivianxf 请尝试复现，并提交到子项目跟进。

**Comment by vivianxf** [comment]
已经复现,并提交pms问题单跟踪:https://pms.uniontech.com/bug-view-207575.html

**Comment by vivianxf** [comment]
持续跟踪

**Comment by vivianxf** [comment]
持续跟踪中

**Comment by vivianxf** [comment]
等新版半上架验证

**Comment by vivianxf** [comment]
已在新版本3.9.5.80deepin4验证通过关闭
![image](https://github.com/linuxdeepin/developer-center/assets/96415804/3301ed34-7d60-44ab-a443-81fe71126039)
