### ISSUE TITLE
点击任务栏中终端图标无反应

### ISSUE THREAD

**Issue by ora-sun** [linuxdeepin/developer-center#4828]
### SUMMARY | 问题概要

打开一个终端窗口后，将其拖动停靠至屏幕右上方分屏后，再次将其拖回屏幕中央，此时点击其他应用后再次点击任务栏中终端图标，有概率出现无反应（终端窗口不显示）的现象。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
系统版本：社区版(Beta)(23)
```

### PRE-REQUIREMENT | 预置条件

将终端图标驻留在任务栏中

### STEPS TO REPRODUCE | 复现步骤

1. 打开一个终端窗口后，将其拖动停靠至屏幕右上方分屏
2. 再次将其拖回屏幕中央
3. 点击其他应用后再次点击任务栏中终端图标

### OBSERVED RESULT | 观察到的结果

有概率无法显示终端窗口

### EXPECTED RESULT | 期望的结果

点击终端图标后，终端窗口可以显示在所有页面最上方

**Comment by babyfengfjx** [comment]
@kobe337  看是否能复现，复现后转交研发分析。

**Comment by kobe337** [comment]
按照问题单中的步骤进行复现，暂未复现，问题持续跟踪中

**Comment by ora-sun** [comment]
发现bug时点击的“其他应用”是在官网下载的edge浏览器

**Comment by kobe337** [comment]
使用edge浏览器，我这边暂时没有复现，问题持续跟踪中

**Comment by kobe337** [comment]
@ora-sun 请问有其他操作吗，有关联的操作利于我们复现问题哈，如没有，请提供使用的机器信息哈，我们记录一下

**Comment by ora-sun** [comment]
当时出现bug时是在刚启动电脑后，在完成上述操作之前打开了文档查看器查看一个pdf文件，也打开了的deepin自带浏览器，此外没有其他操作，机器信息如下
![21439457abaf13e3d3379c10cf16c73](https://github.com/linuxdeepin/developer-center/assets/92298719/1aafcba3-6aeb-46b2-bd4d-93e8b2e487fa)

**Comment by kobe337** [comment]
@ora-sun 请问后面还有复现这个情况吗，出现问题时，任务栏其他的应用都能够正常打开吗，是否确认了当时任务栏有没有卡死呢

**Comment by ora-sun** [comment]
后面没有再使用过分屏功能，没有出现过这个情况，出现问题时确认任务栏没有卡死，其他应用可以正常打开

**Comment by kobe337** [comment]
根据问题单中的描述，增加左上角和右上角，悬浮分屏四种状态，切换浏览器，再次切换终端，仍未复现，继续跟踪中

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
内核：Linux v23-PC 6.1.32-amd64-desktop-hwe https://github.com/linuxdeepin/developer-center/issues/23.01.00.19 SMP PREEMPT_DYNAMIC Wed Aug 2 17:06:10 CST 2023 x86_64 GNU/Linu
【结论】：
目前未能复现，处于持续跟踪状态

**Comment by kobe337** [comment]
@ora-sun 请问内测更新后，是否有再复现过，目前已经更新了多轮内测了，如不能不复现，暂时以未复现关闭了哈

**Comment by kobe337** [comment]
跟踪多个内测更新版本（三次以上更新内测均未复现），暂时关闭，待后续复现后再行跟踪。
