### ISSUE TITLE
Workspaces animations laggy on intel gpu

### ISSUE THREAD

**Issue by Peuczynski** [linuxdeepin/developer-center#483]
On my Intel GPU (Intel HD630 in i7-7700HQ) since my first deepin installation on this machine a month ago with latest drivers as well the animations are very laggy.

Sometimes they don't lag and I can't figure out when this happens.

There is no problem with any other thing but the workspace animations. Even window animations are ok.
Glxgears are smooth as everything else.

Please let me know what more details can I provide to figure out what the problem is.

**Comment by laichiaheng** [comment]
It happens when it zooms in, I'm using AMD RX460 2G

**Comment by Peuczynski** [comment]
Just to be clear. Workspace switch animation (sliding left/right via super+left or super+right) is what I am worried about since I understand that the workspaces showcase animation can be demanding. But then again, sometimes these is no lags, even on battery

**Comment by sonald** [comment]
@Peuczynski what is the resolution of your monitor? 
@laichiaheng what driver did you use, radeon or fglrx ?

**Comment by Peuczynski** [comment]
@sonald it's FullHD, do you want me to test on lower resolutions?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
