### ISSUE TITLE
deepin任务栏整体消失

### ISSUE THREAD

**Issue by Cdrags** [linuxdeepin/developer-center#4833]
### SUMMARY | 问题概要

deepin任务栏疑似不稳定，会在开启某些应用时整体消失

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin v23 beta
```

### PRE-REQUIREMENT | 预置条件

已开启浏览器、终端等多个应用

### STEPS TO REPRODUCE | 复现步骤

用桌面快捷方式打开qq或其他应用程序

### OBSERVED RESULT | 观察到的结果

无法正常打开应用的同时整个任务栏消失，过一段时间恢复时已开启的应用无碍，但原本要开启的应用（如上述的qq）依旧没能开启

### EXPECTED RESULT | 期望的结果

提高任务栏稳定性

**Comment by wineee** [comment]
这个一般是 dde-application-manager 崩溃导致

**Comment by BLumia** [comment]
这种很模糊的问题描述可以开到 discussion 里，这种描述没法对应到特定的某个问题上，也没法很好的衡量是否已经解决掉。我就先关闭处理吧。

关于现象对应的问题本身，是 dde-application-manager 导致的。beta1 之后已经有一些进一步对这个组件的改善，以及使 dock 不再依赖这个组件提供的接口，会最大程度的避免这种层面导致问题产生。当然相关更新还需要等一段时间才会对当前的发布仓库中进行推送。
