### ISSUE TITLE
deepin-installer-reborn 6.0.25 集成

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#4847]
### package information | 软件包信息
包名|版本
--|--
deepin-installer-reborn | 6.0.25

### Package repository address | 软件包仓库地址
deb  [trusted=yes] https://aptly.uniontech.com/pkg/beige-v2/release-candidate/ZGVlcGluLWluc3RnYWxsZXLlsI-mtaPnhorlm77moIcyMDIzLTA2LTMwIDE1OjI4OjI0/  unstable main

### changelog | 更新信息
默认使用小浣熊头像

### test suggestion | 测试建议
安装镜像，查看安装阶段默认头像是否小浣熊
镜像地址： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230630/

### Sphere of influence | 影响范围
安装器阶段默认头像

### ADDITIONAL INFORMATION | 额外补充
暂无

**Comment by babyfengfjx** [comment]
@luodeepin   请开展集成验证。

**Comment by Zeno-sole** [comment]
@luodeepin   镜像更新 https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230703/ 包含无默认壁纸的修复

**Comment by luodeepin** [comment]
验证通过

新装系统默认的用户图像为 小浣熊
在控制中心新建用户时为随机头像，已经与产品经理确认，在控制中心还是以随机头像为主。

**Comment by xuqi27837288** [comment]
![image](https://github.com/linuxdeepin/developer-center/assets/62528742/d11b6261-6f7e-4b80-9635-a123d60edf4f)
