### ISSUE TITLE
System log me off

### ISSUE THREAD

**Issue by rdehnhardt** [linuxdeepin/developer-center#485]
I have a new installation and Deepin log me off when I try to connect on wifi

**Comment by rdehnhardt** [comment]
It is not only in connection with the wifi, it happens randomly

**Comment by moham96** [comment]
I have the same problem. I'm running manjaro deepin

**Comment by rdehnhardt** [comment]
I fix this with a instalation of drivers, but I need to plug the LAN cable

**Comment by moham96** [comment]
Which drivers? my wifi works fine but I get logged off occasionally

**Comment by rdehnhardt** [comment]
I don't know, I just install all drives listed on driver management

**Comment by TheCodeRunsMe** [comment]
@rdehnhardt Which distro are you using?

**Comment by rdehnhardt** [comment]
@TheCodeRunsMe I'm using Deepin 15.5

**Comment by Faizanf33** [comment]
having the same issue

**Comment by rdehnhardt** [comment]
I'm not using deeping at the moment! Closing this issue
