### ISSUE TITLE
After mounting nfs, everyfile shows as an nfs mountpoint

### ISSUE THREAD

**Issue by moham96** [linuxdeepin/developer-center#486]
I'm running manjaro deepin:

> DISTRIB_ID=ManjaroLinux
> DISTRIB_RELEASE=17.1.6
> DISTRIB_CODENAME=Hakoila
> DISTRIB_DESCRIPTION="Manjaro Linux"

I have a nfs server that I mount on my manjaro machine, but the problem is when i mount it evey file in my system(not inside the nfs mount) shows as an nfs server when I pull the properties menu
As an example this is a file in my home folder

before mounting the nfs:
![deepinscreenshot_dde-file-manager_20180310103142](https://user-images.githubusercontent.com/10559702/37239565-4bff956c-244f-11e8-88bc-9b0b8367f1e7.png)
After mounting the nfs at /media/mohammad/nfs:
![deepinscreenshot_dde-file-manager_20180310103224](https://user-images.githubusercontent.com/10559702/37239574-5ff2497a-244f-11e8-8353-83dfa8033276.png)

My fstab:

```
# <file system>             <mount point>  <type>  <options>  <dump>  <pass>
192.168.88.251:/media/pi/hd1	/media/mohammad/nfs	nfs	user
```

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
