### ISSUE TITLE
deepin-unioncode 初始化cmake编译中文选择不能显示

### ISSUE THREAD

**Issue by Yurri-huang** [linuxdeepin/developer-center#4868]
### SUMMARY | 问题概要

deepin-unioncode 初始化cmake编译中文选择不能显示

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
Linux yurii-PC 5.15.77-amd64-desktop #2 SMP Thu Jun 15 16:06:18 CST 2023 x86_64 GNU/Linux
```

### STEPS TO REPRODUCE | 复现步骤

1. mkdir build
2. cmake -B build -S ./
3. cd build
4. ./deepin-unioncode

### OBSERVED RESULT | 观察到的结果

![Uploading 截图_deepin-unioncode_20230703180014.png…]()

### EXPECTED RESULT | 期望的结果

显示中文

**Comment by Decodetalkers** [comment]
看不见截图，如果要翻译的话你这样编译是不行的吧，deepin的项目都是到/usr/share 下去找qm文件的

**Comment by Yurri-huang** [comment]
非安装模式的cmake编译，按照正常逻辑也需要展示中文吧。尝试切换也没有效果（用户感官上属于功能和操作结果不一致），这可能需要实现相对路径的翻译功能。

**Comment by BLumia** [comment]
所以可以附带下那个没传上来的截图吗（

**Comment by Yurri-huang** [comment]
![截图_deepin-unioncode_20230703180014](https://github.com/linuxdeepin/developer-center/assets/34232854/0578c944-215a-4778-b048-1ff13b895df0)

**Comment by Decodetalkers** [comment]
qt的翻译文件也是安装后才可以查找的啊。

**Comment by BLumia** [comment]
你补的这个截图就是 readme 里的截图吧...

**Comment by Yurri-huang** [comment]
> 你补的这个截图就是 readme 里的截图吧...

昨天测试留的图，今天早上合的readme

**Comment by BLumia** [comment]
> qt的翻译文件也是安装后才可以查找的啊。

取决于产品需求，如果确实希望有这种行为的话，把翻译文件放到资源文件也是解决方案。

------

@Yurri-huang 那你们这边处理 assignment 吧 :)

**Comment by Yurri-huang** [comment]
> > qt的翻译文件也是安装后才可以查找的啊。
> 
> 取决于产品需求，如果确实希望有这种行为的话，把翻译文件放到资源文件也是解决方案。
> 
> @Yurri-huang 那你们这边处理 assignment 吧 :)
可以的 @deepin-mozart

**Comment by deepin-mozart** [comment]
在release模式下支持自动生成qm，建议试一下

**Comment by deepin-mozart** [comment]
@Yurri-huang

**Comment by Yurri-huang** [comment]
> 在release模式下支持自动生成qm，建议试一下
```bash
cmake -B build -S ./ -DBUILD_TYPE=Release
cd build && make -j$(nproc)
./deepin-unioncode
```
依然没有任何改变:
![image](https://github.com/linuxdeepin/developer-center/assets/34232854/8ee27a28-44dd-4b6e-888b-7b2128d3577c)

可能要从代码侧分析了

**Comment by deepin-mozart** [comment]
这一步只是生成了qm，如上面所说，还是需要进行安装后才能使用
