### ISSUE TITLE
NCAR Command Language(NCL)意外的Linux more界面

### ISSUE THREAD

**Issue by jesieleo** [linuxdeepin/developer-center#4869]
### SUMMARY | 问题概要

我在NCL进行print("Hello World")操作时，总是会出现一个需要按q才能退出的Linux more输出模式，最近的Debian12也有这个问题

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin v20.9
```

### STEPS TO REPRODUCE | 复现步骤

使用miniconda 安装NCL=6.6.2=h8482486_9版本的NCL
`conda create -n ncl662 -c conda-forge ncl=6.6.2=h8482486_9`

### OBSERVED RESULT | 观察到的结果

```
Copyright (C) 1995-2019 - All Rights Reserved
 University Corporation for Atmospheric Research
 NCAR Command Language Version 6.6.2
 The use of this software is governed by a License Agreement.
 See http://www.ncl.ucar.edu/ for more details.
ncl 0> print("HELLO WORLD")
(0)     HELLO WORLD





(END)
```
按q之后
```
Copyright (C) 1995-2019 - All Rights Reserved
 University Corporation for Atmospheric Research
 NCAR Command Language Version 6.6.2
 The use of this software is governed by a License Agreement.
 See http://www.ncl.ucar.edu/ for more details.
ncl 0> print("HELLO WORLD")
(0)     HELLO WORLD





ncl 1>
```

### EXPECTED RESULT | 期望的结果

```
Copyright (C) 1995-2019 - All Rights Reserved
 University Corporation for Atmospheric Research
 NCAR Command Language Version 6.6.2
 The use of this software is governed by a License Agreement.
 See http://www.ncl.ucar.edu/ for more details.
ncl 0> print("HELLO WORLD")
(0)     HELLO WORLD
ncl 1>
```

**Comment by BLumia** [comment]
> By default, this procedure precedes every value with an index value. Scalars are preceded with "(0)". To turn this feature off, use the ["-n" option](https://www.ncl.ucar.edu/Document/Manuals/Ref_Manual/NclCLO.shtml) on the NCL command line.
>
> If run at the command line, print invokes a pager for scrolling through the list. The pager is either "more" or whatever the user's PAGER environment variable is set to.
> 
> 引自：https://www.ncl.ucar.edu/Document/Functions/Built-in/print.shtml

不是 bug，故进行关闭。

另注：如果你不清楚一个行为是不是 bug，建议优先考虑在讨论板的故障排查板块发帖讨论。

**Comment by jesieleo** [comment]
> > 默认情况下，此过程在每个值之前都有一个索引值。标量前面带有“(0)”。要关闭此功能，请使用NCL 命令行上的[“-n”选项。](https://www.ncl.ucar.edu/Document/Manuals/Ref_Manual/NclCLO.shtml)
> > 如果在命令行中运行， print 会调用寻呼机来滚动列表。寻呼机可以是“更多”，也可以是用户的 PAGER 环境变量设置的任何值。
> > 引自：https://www.ncl.ucar.edu/Document/Functions/Built-in/print.shtml
> 
> 不是bug，故关闭。
> 
> 另注：如果你的节日行为不是bug，建议优先考虑在讨论板的故障排查板块发帖讨论。
感谢您的建议，我通过在~/.bashrc中设置export PAGER="cat" 解决了这个问题。
