### ISSUE TITLE
Hide window decorations on full screen windows

### ISSUE THREAD

**Issue by hughwilliams94** [linuxdeepin/developer-center#487]
When the panel is used in efficient mode the window title and window controls waste valuable screen real estate on laptops. Can an option be introduced to hide window decorations for maximized windows? A similar option is available in Plasma's kwin if you would like to see an implementation.

![deepinscreenshot_select-area_20180311155157](https://user-images.githubusercontent.com/15379654/37255473-b912d5ba-2544-11e8-936f-18ad00da6e0d.png)

**Comment by alexwender1** [comment]
Firefox has the function of hiding the window border.

**Comment by hughwilliams94** [comment]
I know, but it would be good to have an option that applies to all programs

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
