### ISSUE TITLE
How to disable login sound?

### ISSUE THREAD

**Issue by malwarebo** [linuxdeepin/developer-center#488]
I wanna disable the sound after we login into deepin desktop. Is there any option in the OS or do we have a workaround?

**Comment by aiamuzz** [comment]
even i would like to reduce the volume of system sounds ... like the login sound and other system sounds ...

**Comment by Peuczynski** [comment]
open dConf editor, navigate to /com/deepin/dde/sound-effect
set this up however you like

**Comment by irfnhm** [comment]
Thanks it worked.

**Comment by irfnhm** [comment]
Can you help in this one: https://github.com/linuxdeepin/developer-center/issues/489
I lost all of the sound all of a sudden. It's before this issue was resolved.

**Comment by Faizanf33** [comment]
cannot find the specified path, using deepin edition 15.5

**Comment by roneivni** [comment]
The sounds of the Deepin system are: /usr/share/sounds/deepin/stereo

**Comment by gitawego** [comment]
this doesn't work in 15.7,  neither with dconf, nor with deletion of folder  /usr/share/sounds/deepin/stereo
