### ISSUE TITLE
某些场景下大小写区分有问题

### ISSUE THREAD

**Issue by Cai0000** [linuxdeepin/developer-center#4880]
### SUMMARY | 问题概要

我下载某一文件后，该文件在文件夹中显示为Wonderwall（这是一个desktop），在终端里显示wonderwall，大小写区分有问题

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin v23 beta
```

### STEPS TO REPRODUCE | 复现步骤

1.下载https://github.com/keshavbhatt/WonderWall-Packaging/releases/download/v7.0/Wonderwall-x86_64.AppImage
2.解压Wonderwall-x86_64.AppImage
3.进入解压文件squashfs-root
4.分别观察文件夹和终端里wonderwall.desktop首个字母大小写问题

**Comment by Cai0000** [comment]
![image](https://github.com/linuxdeepin/developer-center/assets/95337497/e0b9404f-9b22-434a-bdcc-2f835fab221b)
以上是bug的显示结果

**Comment by BLumia** [comment]
这不是 bug。文件管理器对 desktop 文件有特殊处理，会优先显示 desktop 内容里的名称字段，并且会优先显示符合你当前系统语言的名称。
