### ISSUE TITLE
problems with virtualbox in Deepin host

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/developer-center#49]
<a href="https://github.com/oberon2007"><img src="https://avatars.githubusercontent.com/u/11800714?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @oberon2007**
_Thursday Dec 31, 2015 at 13:06 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/214_

---

When I try running **Oracle Virtualbox** inside my Deepin installation memory and/or CPU usage  explodes and it's not usable.

**Comment by manateelazycat** [comment]
Can you post a screenshot of your CPU usage? 
Thanks!

**Comment by funilrys** [comment]
@oberon2007 is this actual ? If not @manateelazycat you can close it :)
