### ISSUE TITLE
更新後很多地方字體都變得好小，連主題都變了

### ISSUE THREAD

**Issue by laichiaheng** [linuxdeepin/developer-center#490]
貌似使用 Qt 的程式都變成了這副德行
![deepin _20180315223621](https://user-images.githubusercontent.com/9532105/37469994-82369814-28a1-11e8-88c3-15c21e36ceda.png)
![deepin _20180315223805](https://user-images.githubusercontent.com/9532105/37470022-8d796f12-28a1-11e8-951f-a7bd9c376290.png)
![deepin _desktop_20180315224041](https://user-images.githubusercontent.com/9532105/37470179-e91a168c-28a1-11e8-9d1d-8338816ece21.png)

**Comment by laichiaheng** [comment]
又變成需要手動在 /etc/environment 加上 QT_STYLE_OVERRIDE=gtk2 了

**Comment by laichiaheng** [comment]
來張套用 `QT_STYLE_OVERRIDE=gtk2` 後的圖，差距真是大
![deepin _20180316233146](https://user-images.githubusercontent.com/9532105/37529499-4e94a362-2972-11e8-8ef5-eeafbf4798e5.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
