### ISSUE TITLE
【deepin_V23_beta2】【严重】【紧急】【集成测试】【deepin ID】【服务端】绑定邮箱使用其他账号下已绑定过的手机号码时,无法绑定到当前账户下,导致绑定失败

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#4909]
### SUMMARY | 问题概要

必现问题

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
测试环境:account-pre.deepin.org
```

### PRE-REQUIREMENT | 预置条件

访问account-pre.deepin.org后进行登录操作

### STEPS TO REPRODUCE | 复现步骤

使用一个其他账号下已绑定过的手机号码进行绑定操作,观察是否可以正常绑定成功

### OBSERVED RESULT | 观察到的结果

点击绑定按钮后无响应

https://github.com/linuxdeepin/developer-center/assets/62528742/dc012a47-c9d7-4029-a2d3-cd803bee4064

### EXPECTED RESULT | 期望的结果

使用其他账号下已绑定的手机号码,可以正常切换绑定成功

**Comment by myml** [comment]
已修复

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0516镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
