### ISSUE TITLE
Bluetooth not existing anymore

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/developer-center#491]
Not in the settings panel and nothing happens when executing bluetoothctl 
it gets stuck on `Waiting to connect to bluetoothd...`

Happened after todays update and then restart.

**Comment by DasJott** [comment]
some bluez stuff seems to have been uninstalled during updates. Strange enough...

**Comment by DasJott** [comment]
Nope, Bluetooth is just not existing anymore in the deepin system. After reboot tehre os no bluetooth symbol in settings and bluetoothctl is waiting forever.

bluetooth is started  with systemctl start bluetooth.service

**Comment by DasJott** [comment]
so repoen

**Comment by Faizanf33** [comment]
found any fix on this issue?

**Comment by DasJott** [comment]
This especially happens after suspend.

**Comment by Faizanf33** [comment]
@DasJott i can't find bluetooth at all!

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
