### ISSUE TITLE
【deepin_V23_beta2】【严重】【有空】【内测反馈】【DTK】【玲珑应用】看图/相册/音乐等玲珑应用出现 双标题

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#4923]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
1. 安装镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
libdtkgui5 5.6.12
```

### PRE-REQUIREMENT | 预置条件

1.安装镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
2. 添加内测，升级至最新版本

### STEPS TO REPRODUCE | 复现步骤

1. 打开相册/看图/音乐等，查看界面显示

### OBSERVED RESULT | 观察到的结果

1. 出现双标题
![截图_选择区域_20230710112257](https://github.com/linuxdeepin/developer-center/assets/96416089/c1198a88-a9ac-4200-bd9f-53083923300f)

### EXPECTED RESULT | 期望的结果

1. 标题单显示正常

**Comment by babyfengfjx** [comment]
@kegechen  请帮忙优化~

**Comment by BLumia** [comment]
关联：https://github.com/linuxdeepin/developer-center/issues/4922

**Comment by luodeepin** [comment]
libdtkgui5 5.6.12
验证通过
![image](https://github.com/linuxdeepin/developer-center/assets/96416089/e9d3d1bc-1349-4f1f-a7fb-7c113227d22d)
