### ISSUE TITLE
Deepin blur effect

### ISSUE THREAD

**Issue by alex47** [linuxdeepin/developer-center#493]
Could someone tell me where I can find the source code for the blur effect that is used everywhere in Deepin?

I tried modifying this, but it seems like nothing is using it: https://github.com/linuxdeepin/deepin-wm/blob/master/src/Deepin/DeepinBlurEffect.vala

I tried modifying clutter, but also it seems that this is not the code that is used: https://github.com/sonald/clutter/blob/master/clutter/clutter-blur-effect.c

**Comment by sonald** [comment]
@alex47  
- [meta-blurred-background-actor](https://github.com/linuxdeepin/deepin-mutter/blob/release/3.20/src/compositor/meta-blurred-background-actor.c) this is for static blurry background.
- [meta-blur-actor](https://github.com/linuxdeepin/deepin-mutter/blob/release/3.20/src/compositor/meta-blur-actor.c) this is for dynamically blurry actor. for this to work correctly, you need patched cogl and clutter by deepin.

**Comment by sonald** [comment]
@alex47 you may also take a look at [this](https://github.com/sonald/blur-effect), which use standard gles api with cogl needed.

**Comment by alex47** [comment]
@sonald thanks for answering (and answering my email too)
Looks like I found what I was looking for. I modified, compiled and installed it successfully.

with [this](https://github.com/linuxdeepin/deepin-mutter/blob/release/3.20/src/compositor/meta-blur-effect.c) I have found 4 blur algorithm sources but only 1 is used, it's a bit confusing...

Is [this](https://github.com/sonald/blur-effect) used on the GUI at all or is it just a showcase program?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
