### ISSUE TITLE
libreoffice word 图片末+换行显示为图片前+换行

### ISSUE THREAD

**Issue by Cai0000** [linuxdeepin/developer-center#4940]
### SUMMARY | 问题概要

在libreoffice word文档图片下输入换行时，空白行出现在图片前

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
系统版本：社区版(Beta)(23)
内核版本：Linux 6.1.11-amd64-desktop-hwe x86_64
libreoffice版本：
Version: 7.4.2.3 / LibreOffice Community
Build ID: 40(Build:3)
CPU threads: 16; OS: Linux 6.1; UI render: default; VCL: gtk3
Locale: zh-CN (zh_CN.UTF-8); UI: zh-CN
Debian package version: 1:7.4.2-1
Calc: threaded
```

### STEPS TO REPRODUCE | 复现步骤

/home/admin/Videos/Screen Recordings/录屏.mp4

**Comment by Cai0000** [comment]
https://github.com/linuxdeepin/developer-center/assets/95337497/18ed2ab2-114c-4b91-9652-8d3879d3196b

**Comment by BLumia** [comment]
其它发行版下也是这个行为吗？是的话，应该反馈到 libreoffice。

**Comment by Cai0000** [comment]
对不起，我试了7.5版本的，也存在这个行为

**Comment by Decodetalkers** [comment]
libreoffice 的行为的话应该向上游报bug吧。。emm

**Comment by BLumia** [comment]
libreoffice 上游问题（其实我们甚至都不确定这个是否属于问题还是预期行为），请汇报到上游。
