### ISSUE TITLE
startdde constantly exhausting the CPU

### ISSUE THREAD

**Issue by ekhaled667** [linuxdeepin/developer-center#496]
Since the last update, I noticed the CPU fan  was making a lot of noise, when I checked on the system monitor, I found startdde using 10% of the CPU all the time.

The issue persists on AMD and Intel CPUs.

**Comment by OmarSquircleArt** [comment]
I am having the same issue. Startdde is consuming the processing power of full one thread on my Ryzen 7 1700. This problem started only in the latest update.

I am on Arch Linux. Startdde version: 3.1.26-1, Build Date: Tue 20 Mar 2018 08:52:47 AM EET.

Here is a screen shot of the system monitor right after startx:

![startdde_cpu_usage](https://user-images.githubusercontent.com/25300994/37845851-8ceb969a-2ed4-11e8-9c57-8f104d32b305.png)

**Comment by Jm56Z** [comment]
Hello, I'm having a very similar issue, but on a different level.
I just updated the whole computer on friday, March 30th at 8:45PM UTC.
I am on archlinux, runnig DDE (Obviously...).
Since this update, the startdde process keeps running, using 100% of my CPU
`
top:

%CPU   %MEM  TIME+   PROCESS
100,0  0,5   7:24.49 startdde
`
Wich is quite embarrassing.

**Comment by laichiaheng** [comment]
add `export DDE_DEBUG_LEVEL="debug"` to `/etc/profile`
install perf and reboot.

When the problem happens, enter `sudo perf record -p <startdde pid>`, wait for 10s, and stop.
enter `journalctl /usr/bin/startdde > /tmp/dde.log`, and upload `perf.data` and `/tmp/dde.log` to them

**Comment by ekhaled667** [comment]
[Here you go](https://github.com/linuxdeepin/developer-center/files/1871392/perf_data.tar.gz)

**Comment by felixonmars** [comment]
@electricface @hualet Please have a look.

**Comment by epoiate** [comment]
[Here is mine.](https://github.com/linuxdeepin/developer-center/files/1879916/startdde-log.tar.gz)

**Comment by Peuczynski** [comment]
In my case this does not happen every time I start the system. When it occurs I just reboot and it works.
![deepinscreenshot_20180410075001](https://user-images.githubusercontent.com/12342833/38538387-d6b29a72-3c93-11e8-9be5-a0959fa243f3.png)

**Comment by Jm56Z** [comment]
Here is mine. Time: 2018/04/27 11:00 UTC

[dde.log](https://github.com/linuxdeepin/developer-center/files/1954642/dde.log)

**Comment by Spawnrad** [comment]
No solution? Have same issue since Update

**Comment by jouyouyun** [comment]
Try to edit `/etc/default/grub` to add parameter `vsyscall=emulate`, then exec `grub-mkconfig -o /boot/grub/grub.cfg` to update, then reboot.

**Comment by Spawnrad** [comment]
I have uninstall and reinstall deepin and it work. But now for me i have an issue when i mount my other drive my bottom bar reload lot of times.

**Comment by jouyouyun** [comment]
@sbwtw

**Comment by sbwtw** [comment]
@Spawnrad Seems dde-dock crashed.
do a full upgrade and check version of dde-dock and dde-file-manager.
if stills happen, please install systemd-coredump and wait for next crash, then run `sudo coredump -1 info`

**Comment by jouyouyun** [comment]
:sweat:

**Comment by jouyouyun** [comment]
Have you install `gnome-keyring`?

**Comment by jouyouyun** [comment]
Try this [startdde](https://drive.google.com/file/d/1Uc8Ksb3LEW0BvYuNI5n4Tf6vmWpNK_6M/view?usp=sharing), downloaded and `chmod +x`, then copy to `/usr/bin/startdde`.

**Comment by zhangnew** [comment]
@jouyouyun I use ArchLinux, It's happened everytime I startup linux and start dde. can I try this [startdde](https://drive.google.com/file/d/1Uc8Ksb3LEW0BvYuNI5n4Tf6vmWpNK_6M/view?usp=sharing) ?

**Comment by jouyouyun** [comment]
@zhangnew  Yes! You should update firstly, then copy the above file.

**Comment by sbwtw** [comment]
@electricface @snyh

**Comment by zhangnew** [comment]
@jouyouyun That's solved. Thx.

**Comment by woojay** [comment]
@jouyouyun That worked as well on my Majaro 4.16.8 Deepin 15.5 desktop.  Thanks a bunch.  Back to Deepin since March.

**Comment by jouyouyun** [comment]
Fixed in  `startdde 3.1.30`, please update!

**Comment by NeoTech** [comment]
Not fixed in 3.1.30 i have now 100% cpu useage after each time i come back from putting the computer to sleep.. esiest fix is to kill the startdde process and get thrown out in the process and just login again.

**Comment by jouyouyun** [comment]
@electricface

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
