### ISSUE TITLE
Can't get to login screen on lightdm 

### ISSUE THREAD

**Issue by moda20** [linuxdeepin/developer-center#499]
I just switched to Deeping greeter session in lightdm, enabled lightdm using system to and rebooted, now I am waiting forever to get to login with spinner running on the screen

I am running the arch Linux zen kernel

**Comment by felixonmars** [comment]
Any error logs in journal or lightdm.log?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
