### ISSUE TITLE
【deepin_V23_Release】【严重】【立即】【发散测试】【DTK】文件管理器搜索栏中搜索图标与搜索按钮图标展示大小不一致

### ISSUE THREAD

**Issue by Kakueeen** [linuxdeepin/developer-center#4993]
### SUMMARY | 问题概要

DLineEdit 添加图标 action 后，图标有部分遮挡
![截图_demo_20230714134735](https://github.com/linuxdeepin/dtk/assets/60250462/472f81f2-45df-4115-8215-ec51d2da7cdd)

### DTK VERSIONS | DTK版本信息

dtkgui: 5.6.11
dtkwidget: 5.6.12
dde-qt5integration: 5.6.11

镜像地址：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240514/

文件管理器:6.0.50

进入任意一个磁盘文件夹中，点击搜索按钮观察输入地址左边的搜索图标展示效果

### OBSERVED RESULT | 观察到的效果

DLineEdit 中的图标部分被遮挡

左边的搜索图标大小样式应与进入文件管理器时搜索按钮展示大小不一致，左侧展示的偏小

### EXPECTED RESULT | 期望的设计效果

左边的搜索图标大小样式应与进入文件管理器时搜索按钮展示大小相一致

图标显示效果与 DSearchEdit 一致

### ADDITIONAL INFORMATION | 额外补充
[demo.zip](https://github.com/linuxdeepin/dtk/files/12046697/demo.zip)

[bug-209411#备注6](https://pms.uniontech.com/bug-view-209411.html)

**Comment by kegechen** [comment]
图标没有问题，问题是修复一个旧的问题引入的。。待确定解决办法 @18202781743

**Comment by vivianxf** [comment]
同步pms单子https://pms.uniontech.com/bug-view-219953.html

**Comment by xuqi27837288** [comment]
@18202781743 这个问题麻烦优先看一下,谢谢~

**Comment by 18202781743** [comment]
问题应该解决了,

**Comment by xuqi27837288** [comment]
【验证环境】：v23 Release镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240814
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.9.6-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
