### ISSUE TITLE
hiDPI support in Deepin

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/developer-center#50]
<a href="https://github.com/alexcwyu"><img src="https://avatars.githubusercontent.com/u/3199461?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @alexcwyu**
_Thursday Jan 21, 2016 at 02:22 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/232_

---

I successfully installed Manjaro Deepin to my SurfacePro4.
However, the UI is too tiny in the 12 inch screen with 2,736 x 1,824 resolution.

I couldn't find the HiDPI setting for Deeping from wiki:
https://wiki.archlinux.org/index.php/HiDPI

Is there any HiDPI support in Deepin, so that I can set the scaling-factor 2?
If yes, how can i enable it?
If no, any timeline / roadmap?

I have tried other DE, so far Budgie is the best. The screen scale automatically. Gnome is also very good.
It would be great if Deepin support HiDPI like Budgie / Gnome.
I love Manjaro Deepin UI.

Thanks!

**Comment by jouyouyun** [comment]
Sorry, we do not support this feature now. If you set it by [XResources](https://wiki.archlinux.org/index.php/HiDPI#X_Resources), is it work?

**Comment by acrox999** [comment]
No, it doesn't. Other programs do get scaled after applying it to Xresources. However, Deepin itself does not.

**Comment by hualet** [comment]
DDE components have no hiDPI support yet, but we've been working on the fundamentals. Much work need to be done to get DDE ready for hiDPI support, so please wait.

**Comment by vshatskyi** [comment]
Is there any progress on this issue?

**Comment by vshatskyi** [comment]
`xrandr -s 1920x1080` (you can find the list of resolutions with `xrandr`) scales the DE, but it's not HiDPI anymore. Besides, there are issues with 4x scaling.

**Comment by pingram3541** [comment]
Is it just me or clicking any of the display resolutions in the Deepin control center just highlights the listed resolution only? Are they not supposed the switch resolutions upon click immediately?

I have to use what @vshatskyi suggested above to downgrade my display to 1920x1080 so this is a very anticipated feature.

**Comment by hualet** [comment]
Oh sorry, just been very busy with the 15.4 Alpha stuff and didn't notice the replies here.

15.4 is a big project so we didn't get much time to make the GUI stuff of DDE hiDPI ready yet, but I think it won't take long after the  Spring Festival holiday to get all this done, so please stay tuned 😂 

The issue bothering @pingram3541 needs some investigation, which @jouyouyun can help.

**Comment by pingram3541** [comment]
I'm running Manjaro 16.10.3 build of Arch as well if that helps.  I'm excited for 15.4 too, cheers =)

**Comment by odiin2016** [comment]
Any update? I know people are busy, but I just started using deepin on my Archlinux installs and I really like this. Problem is the one machine uses a 55 inch 4k tv for a monitor.  I can still survice through the greeter, but have to use cinnamon on that machine  as deepin is unusable there. I'm interested to see when this feature is worked in.

**Comment by JLCCI** [comment]
+1 for HiDPI support.

Great UI but a lot of issues on 4K laptop screen.

**Comment by mrchilly0** [comment]
+1 for HiDPI support.  Love the way deepin runs and looks!

**Comment by jouyouyun** [comment]
Exec `gsettings  set  com.deepin.xsettings   scale-factor  <value>` will change DPI, it will increase pixels for gtk apps. Firefox will work after login. 
The value should > 0.

**Comment by vshatskyi** [comment]
@jouyouyun will deepin itself be scaled after this change?

**Comment by odiin2016** [comment]
Definately not a full UI scale, like i would expect from a hidpi 
setting adjustment, just the text. When I set my machine back to 4k 
resolution after this I can read my terminal, ut I can barely see my 
dock, and forget about reading the item titles. Can hardly see the 
mouse, etiher.

**Comment by calden74** [comment]
Sorry but this is really unacceptable, I mean try buying a laptop with a resolution under 1080p today, they're and few. I mean even my new Chromebook is 2K for goodness sakes. HiDPI really should have been on the top of your list as these types of displays are the new standard. I'll guess I'll stick with Gnome, which is really the only Desktop Environment that seems to care about HiDPI displays, even KDE is wonky in this regard. I simply do not understand why Linux disto creators still cannot get their act together when it comes to these types of displays, not everyone wants to use a 5 year old Thinkpad, though it seems I still have to with my T430P. When will this be fixed?

**Comment by hualet** [comment]
Hey guys, cool down, please.
I promised to get hiDPI ready long enough ago, and I know that. But the situation of DDE is getting quit complicated. xserver bugs, driver issues and some pre-installed App issues, that all results in the lag of deepin 15.4, which takes precedence over hiDPI support. Users don't want quit buggy OS over non-hiDPI-support-ready OS after all, right ?

**Comment by mrchilly0** [comment]
Most of us understand that this isn't your paying gig, so thank you for
adding it to your todo list.

**Comment by ggrars** [comment]
Had a huge update to my 15.4 desktop (1100+ packages) today and a lot of the resolution in the display section is no longer available. I have to either at 4K resolution - which is too small to see on a laptop or 1080p - which is easy on the eyes, but big.

Are they planning on addressing the HiDPI issue anytime soon?

**Comment by jouyouyun** [comment]
@ggrars Exec gsettings set com.deepin.xsettings scale-factor <value> will change DPI.
The value should > 0.

**Comment by JGH1000** [comment]
+1 This should really be a big priority given how many people are getting HiDPI screens. Hopefully we will get it soon!

**Comment by ashvinnihalani** [comment]
+1 Basically unusable on the Surface Book

**Comment by fillipefeitosa** [comment]
Lets place a big +1 for HiDPI here. 1080p looks hard to on a 15" display. Cant imagine you guys on a 14" surface display.

**Comment by gbyolo** [comment]
+1 In my opinion you should really care about HiDPI support. It's unusable on 4k 15'' screen.

**Comment by V3XATI0N** [comment]
I have a 4K screen and I just switch it to 1080p, and everything is fine. HiDPI would be nice, I guess, but since many applications on Linux still don't know what to do with themselves on HiDPI screens, it isn't all that helpful for the DE alone to support it.

**Comment by chiarishow** [comment]
+1

**Comment by agauniyal** [comment]
The devs have acknowledged the issue as already stated in the previous comment, theres no need to raise the same set of concerns repeatedly. Just use GitHub reaction on certain message to mark your 👍 :)

**Comment by Filmon97** [comment]
It's possible to contribute for the HiDPI support ?

**Comment by slinstj** [comment]
1920x1080 works fine in my 4k 15.6 notebook screen. I really can "be alive" with this till the most important things get done. Thanks for the developpers for your great overall work!

**Comment by Filmon97** [comment]
I cannot change my display resolution...

**Comment by ElvisPresly** [comment]
when there is a support of hidpi?

**Comment by hualet** [comment]
Still working on it, hopefully the next release (15.5) will hiDPI compatible.

**Comment by tiagolr** [comment]
On Dell XPS 13 FHD,  changing the gsettings scale makes the OS very usable (terminal, chrome, desktop, fonts, etc), thanks for the info, currently using scripts to toggle hidpi/lowdpi like:

```bash
gsettings set com.deepin.xsettings scale-factor 1.25
gsettings set com.deepin.xsettings gtk-cursor-theme-size 30
gsettings set com.deepin.dde.dock icon-size 48
pkill -KILL -u username
```

**Comment by RealAct** [comment]
I love Deepin but I'm really struggling with my 4K monitor, the font rendering and things like dragging Windows etc looks atrocious, if I set the proper 4K resolution then I can't even read anything and the whole UI appears in miniature.

I really can't wait for the 15.5 release.

**Comment by hualet** [comment]
Since deepin 15.5 Beta is in public now,  I think I can finally close this old issue now 😃
