### ISSUE TITLE
[Arch Linux] Login flashes and not able to login 

### ISSUE THREAD

**Issue by gauthamzz** [linuxdeepin/developer-center#500]
I am able to type the password in the login screen, a console comes and returns to the login screen.

I am able to use ttl. 

OS: Manjaro Deepin

**Comment by dodedodo33** [comment]
I'm now having the same issue. It seems that startdde is failing to start.
I've looked into the default system logs but they won't show any applicable errors.

This issue for me occured after upgrading to startdde package version 3.1.27-1. 
I've downgraded startdde to 3.1.26-1 and now it starts correctly, but still with occasional high CPU usage (as seen in #492 #496, after a relog or reboot it mostly works fine again).

**Comment by felixonmars** [comment]
Please try again with deepin-desktop-schemas 3.2.9.20180409-1

**Comment by dodedodo33** [comment]
@felixonmars thanks, seems to be working :)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
