### ISSUE TITLE
deepinid云服务模块集成申请

### ISSUE THREAD

**Issue by Keima-lpj** [linuxdeepin/developer-center#5006]
### package information | 软件包信息

包名 | 版本
-- | --
deepin-sync-client | 7.0.0.3
deepin-deepinid-plugin | 2.0.0.4

### Package repository address | 软件包仓库地址

deb  [trusted=yes] https://aptly.uniontech.com/pkg/beige-v2/release-candidate/ZGVlcGluaWTkupHmnI3liqHnrKzkuozova4yMDIzLTA3LTE5IDEwOjExOjI0/  unstable main
deb  [trusted=yes] https://aptly.uniontech.com/pkg/nonfree-beige-v2/release-candidate/ZGVlcGluaWTkupHmnI3liqHnrKzkuozova4yMDIzLTA3LTE5IDEwOjExOjI0/  unstable non-free

### changelog | 更新信息

修复bug: 

https://pms.uniontech.com/bug-view-205221.html
https://pms.uniontech.com/bug-view-205209.html

**Comment by babyfengfjx** [comment]
@xuqi27837288   请开展集成验证，同步覆盖之前deepin ID所提供的所有内容场景的测试内容。
