### ISSUE TITLE
Increase blur radius

### ISSUE THREAD

**Issue by marcinciarka** [linuxdeepin/developer-center#501]
Is there any way to increase blur radius to 60 or more pixels?

**Comment by sonald** [comment]
there are several different ways blur is used in deepin-wm and DDE. To which part do you refer ? 
due to performance reason, the dynamic background blurring radius is tested and hardcoded into source code. dde-launcher uses an offline blur helper which is configurable.

**Comment by dreszczyk** [comment]
I'm refering to terminal background blur.

**Comment by sonald** [comment]
that's dynamic blurring, and increasing radius will burden the rendering speed a lot. before we get a performance gain, this is impossible.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
