### ISSUE TITLE
用户反馈：“帐户”是错别字，正确写法是“账户”

### ISSUE THREAD

**Issue by BLumia** [linuxdeepin/developer-center#5012]
用户在邮件中反馈：

> 简单讲，“帐户”是错别字，正确写法是“账户”
> 系统中多处都使用了错别字“帐户”，建议修正
>
> ![图片](https://github.com/linuxdeepin/developer-center/assets/10095765/ec723e3c-5e80-44c2-8862-22512999264c)

并在后续提供了一些引据：

> 账户，不是说涉及或者不涉及资金，而是现在根本就没有“帐户”这个词（过去的曾经有过的写法，现在属于错别字）
> 况且某种意义上来说账户也是一种无形资产，和账还是有点关系的，而和帐却是一点关系都没有
>
> 引用：
>
>教育部、国家语委发布的《第一批异形词整理表（2002年3月31日试行）的注释中说，“账”、“帐”二字分工如下：“账”用于货币和货物出入的记载、债务等，如“账本、报账、借账、还账”等；“帐”专表用布、纱、绸子等制成的遮蔽物，如“蚊帐、帐篷、青纱帐比喻用法）”等。
>
> 《现代汉语词典》（2002年增补本）只有“账户”词条，而无“帐户”词条，对“账户”的解释是：会计上指账簿中对各种资金运用、来源和周转过程设置的分类。
>
>经国家语委等修改而成的《图书编校质量差错认定细则》中的第七条列举了“常见的较难界定的别字”，其中有“欠账（帐）、账（帐）簿”等，并特别说明“括号里的字是错的”。
>
> 新华社2002年印发的《新华社采编人员手册》“新闻报道中容易用错的字词”这部分内容中，也明确说明，表示“财物出入的记载”和“债”的义项时，不能写作“帐”。

**Comment by BLumia** [comment]
一些其它参考信息（非反馈人提供，以及下述参考资料均未判定资料本身是否是误用）：

1. Windows 11 与 macOS 上使用的文案均为“帐户” 
![Windows 简体中文环境下，“设置”中的对应导航菜单项目截图](https://github.com/linuxdeepin/developer-center/assets/10095765/2d31dd18-a54a-4e91-830c-4f30669d3321)
2. Wikipedia 中，简体中文环境下，对于“[帐户](https://zh.wikipedia.org/zh-hans/%E5%B8%B3%E6%88%B6)”一词条在 URL 以及词条名称中的写法为“帐户”，但在后续的词条描述中使用的是“账户”
3. Wiktionary 中，繁英条目下，存在[帐户](https://en.wiktionary.org/wiki/%e5%b8%b3%e6%88%b6)与[账户](https://en.wiktionary.org/wiki/%E8%B3%AC%E6%88%B6)两个词条，前者中备注到：`This term, 帳戶, is a variant form of 賬戶.`
4. 现代汉语词典第五至第七版都未直接提供“帐户”词条。现代汉语词典，[第五版](http://bbs.pinyin.thunisoft.com/forum.php?mod=viewthread&tid=31657)与[第七版](https://github.com/CNMan/XDHYCD7th)中，对“帐”的解释为：`【帐】（帳）zhànɡ❶用布、纱或绸子等做成的遮蔽用的东西：蚊～｜营～｜～篷◇青纱～。❷同“账”。`，但在第六版中，包含“**旧**同”的描述 
![现代汉语词典 第六版 实体书照片](https://github.com/linuxdeepin/developer-center/assets/10095765/c2885687-f6a7-4e25-80e7-bf28b9c919d4)。

可采取的方案建议：

1. 若根据教育部、国家语委等部门的新修改的规范，应当调整为使用“账户”一词，即便我们的产品未与用户资产的流动存在相关性。
2. 转而使用“用户”作为文案。对应实际的 `useradd` 等命令中所使用的英文文案。

**Comment by BLumia** [comment]
沟通过程备注：

- 7/18: 原涉及的相关研发人员 C 表示“（自己）曾很早问过这个问题，目前应该是故意用的这个词，上次（原文如此）用错了，发布前还特意改过的”，并建议和 *集成产品经理* 沟通
- 7/18: 集成产品经理 G 答复：账户一般是指跟钱有关的，比如银行账户，或者支付账户，我们的帐户由于没有支付、财产相关的，所以就用的是帐
- 7/20: 收到用户反馈后，和 G 进一步沟通与确认时，G 表示，对于之前的历史沟通已没有可循的存档，并表示“如果现代汉语词典没这词了的话，那我们就得改了，这个需要求证一下”，以及表示了相关功能已移交另一位产品经理 W
- 7/20: 与 W 约定下周进行此问题的讨论，并明确修改范围、发布节点等事宜。

**Comment by BLumia** [comment]
后续：

- 7/25: GNOME 与 KDE 均使用“用户”一词表示桌面环境下可存在与切换的用户。部分其他桌面环境在混用“用户”与“**帐**户”两种写法。
- 7/25: 与 W 沟通认为，可以将文案调整为“用户”，但考虑到帮助手册、宣传资料等都需要调整，估计还需要进一步评估影响。

**Comment by BLumia** [comment]
其它参考资料：

- https://github.com/search?q=%E5%B8%90%E5%8F%B7+%E8%B4%A6%E5%8F%B7&type=pullrequests&s=created&o=desc&p=1
- https://www.ithome.com/0/705/547.htm

**Comment by UTsweetyfish** [comment]
https://codesearch.debian.net/search?q=账户
https://codesearch.debian.net/search?q=帐户

**Comment by myml** [comment]
https://www.google.com/search?q=%E5%B8%90%E5%8F%B7

**Comment by luodeepin** [comment]
验证通过
控制中心 6.0.22
![截图_选择区域_20230817131454](https://github.com/linuxdeepin/developer-center/assets/96416089/dc5364b7-963e-4153-bf6f-2f45db35a2ff)

**Comment by BLumia** [comment]
@luodeepin 别忘了检查 安装器 里是不是也有。有的话需要反馈给安装器组。

**Comment by luodeepin** [comment]
嗯！这个要出镜像看，当前控制中心是按照需求做成用户了
