### ISSUE TITLE
Deepin 23 beta file manager search bug 

### ISSUE THREAD

**Issue by raspin0** [linuxdeepin/developer-center#5015]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
Virtualbox
Daily build: deepin-23-beige-amd64-20230720-173817.iso
Wayland session

doesn't reproduce on x11
```

### STEPS TO REPRODUCE | 复现步骤

https://github.com/linuxdeepin/developer-center/assets/39202451/a3dccd55-9330-4ed5-81ff-ca44de81858d

**Comment by babyfengfjx** [comment]
@SuperEffie  从描述和视频中看，实在wayland下才有的问题，不过具体预期结果是啥，以及现象是否为我们所推测的，可以在观察视频后将理解的问题与用户确认一下。

**Comment by SuperEffie** [comment]
@raspin0  Thanks for your feedback~
It seems like when I edit the address, enter '/etc/' and the information in the address bar disappears.

**Comment by SuperEffie** [comment]
pms链接：[https://pms.uniontech.com/bug-view-213701.html](https://pms.uniontech.com/bug-view-213701.html)

**Comment by SuperEffie** [comment]
问题正在修复中，目前在文件管理器项目组进行qt相关问题排查~

**Comment by SuperEffie** [comment]
定位为kwin wayland下的bug（窗管相关），非qt引起的异常，目前窗管在重新构建中，暂无优化进展，后持续关注该问题。

**Comment by xuqi27837288** [comment]
该问题暂未修复,已有问题单跟踪,该issue先关闭处理
