### ISSUE TITLE
dde-session-daemon takes too much CPU

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/developer-center#502]
Closing the reported issue does not really sove it.

Especially when running on battery this is a really bad bug, because it drains the battery empty very quickly.

Out of a sudden the daemon takes as much cpu.

Arch Linux, Deepin Desktop, Docker running.

Edit: It seems that Docker causes a lot processes to use way more CPU than they should. Cannot explain it but noticed it.

**Comment by DasJott** [comment]
It seems to have something to do with docker. When I stop docker.service the usage goes back to normal. Right on starting docker and having it running, usage goes through the roof.

**Comment by felixonmars** [comment]
I just tried to run docker.service and ran a few containers, but still cannot reproduce any of these :(

**Comment by DasJott** [comment]
What has to happen to bring the dde-session-daemon to such high CPU usage?

I am running a lot containers here (37 right now) and that somehow breaks it.
There seem to be other apps affected though. Rambox for example also freezes from time to time, also `gvfs-udisks2-vo` happens to use much more cpu when running docker....

**Comment by DasJott** [comment]
One important note might be, that most of the docker containers do very much with network.

**Comment by moham96** [comment]
Same problem here :disappointed: after some hours of working the system becomes very unresponsive and then freezes completely, and checking htop I can see that dde-session-daemon is taking 100% CPU I have to restart the session every now and then to workaround this issue

**Comment by jouyouyun** [comment]
@DasJott @moham96 Please run following commands when dde-session-daemon's CPU  usage is abnormal. 
```shell
rm -rf ~/.cache/deepin/dde-daemon/calltrace/
qdbus --literal com.deepin.daemon.Daemon /com/deepin/daemon/Daemon com.deepin.daemon.Daemon.CallTrace 5 30
strace -t -f -p $(pgrep dde-session-dae) 2>daemon_strace.log #Run it about 5 seconds is enough.
sudo perf record -p $(pgrep dde-session-dae)   #Run it about 5 seconds is enough.
```
Then upload the `./daemon_strace.log`, `./perf.data` and the directory `~/.cache/deepin/dde-daemon/calltrace/`, thanks!

**Comment by DasJott** [comment]
Okay, I got it fixed somehow. 
With current kernel on arch you need to set kernel parameter `vsyscall=emulate` in order for docker to run okay. Otherwise all possible parts of the system will go nuts, not only dde-daemon.
Somehow dde was overwriting the default/grub for the parameter to vanish and my sytem ran wild. Now the param is there again, system is okay again and dde-daemon was never using abnormal cpu again by now.

**Comment by jouyouyun** [comment]
@electricface pay attention to this problem.

**Comment by jouyouyun** [comment]
@DasJott Edit `/etc/default/grub` to add parameter `vsyscall=emulate`, then exec `grub-mkconfig -o /boot/grub/grub.cfg` to update.

**Comment by jouyouyun** [comment]
Also see: [docker, nginx container and linux kernel => 4.11](https://github.com/JiscRDSS/rdss-archivematica/issues/65)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
