### ISSUE TITLE
Process 999 (deepin-menu) of user 1000 dumped core.

### ISSUE THREAD

**Issue by Xeers** [linuxdeepin/developer-center#503]
[Arch linux] 
systemd-coredum
Process 999 (deepin-menu) of user 1000 dumped core.

Stack trace of thread 999:
#0  0x00007fdd55c86cc7 _ZN6QMutex4lockEv (libQt5Core.so.5)
#1  0x00007fdd55e8059a _ZN16QCoreApplication9postEventEP7QObjectP6QEventi (libQt5Core.so.5)
#2  0x0000561529d5205b n/a (deepin-menu)
#3  0x0000561529d55eda n/a (deepin-menu)
#4  0x00007fdd55e8e7e3 _ZNK11QMetaMethod6invokeEP7QObjectN2Qt14ConnectionTypeE22QGenericReturnArgument16QGenericArgumentS5_S5_S5_S5_S5_S5_S5_S5_S5_ (libQt5Core.so.5)
#5  0x00007fdd55e90cff _ZN11QMetaObject12invokeMethodEP7QObjectPKcN2Qt14ConnectionTypeE22QGenericReturnArgument16QGenericArgumentS7_S7_S7_S7_S7_S7_S7_S7_S7_ (libQt5Core.so.5)
#6  0x0000561529d51bed n/a (deepin-menu)
#7  0x0000561529d55aae n/a (deepin-menu)
#8  0x0000561529d55bc3 n/a (deepin-menu)
#9  0x00007fdd56307b5d n/a (libQt5DBus.so.5)
#10 0x00007fdd5630cfc9 n/a (libQt5DBus.so.5)
#11 0x00007fdd5630d598 n/a (libQt5DBus.so.5)
#12 0x00007fdd5630fdae n/a (libQt5DBus.so.5)
#13 0x00007fdd55eae062 _ZN7QObject5eventEP6QEvent (libQt5Core.so.5)
#14 0x00007fdd56e91fec _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
#15 0x00007fdd56e999c6 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
#16 0x00007fdd5795dc99 _ZN3Dtk6Widget12DApplication6notifyEP7QObjectP6QEvent (libdtkwidget.so.2)
#17 0x00007fdd55e7ccf0 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
#18 0x00007fdd55e7f956 _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData (libQt5Core.so.5)
#19 0x00007fdd55ed9c54 n/a (libQt5Core.so.5)
#20 0x00007fdd53abae38 g_main_context_dispatch (libglib-2.0.so.0)
#21 0x00007fdd53abb081 n/a (libglib-2.0.so.0)
#22 0x00007fdd53abb10e g_main_context_iteration (libglib-2.0.so.0)
#23 0x00007fdd55ed9241 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#24 0x00007fdd47d35482 n/a (libQt5XcbQpa.so.5)
#25 0x00007fdd55e7b32b _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#26 0x00007fdd55e84728 _ZN16QCoreApplication4execEv (libQt5Core.so.5)
#27 0x0000561529d4b75f main (deepin-menu)
#28 0x00007fdd552a8f4a __libc_start_main (libc.so.6)
#29 0x0000561529d4b92a n/a (deepin-menu)

Stack trace of thread 1019:
#0  0x00007fdd5537397b __poll (libc.so.6)
#1  0x00007fdd53abaff3 n/a (libglib-2.0.so.0)
#2  0x00007fdd53abb10e g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007fdd55ed9241 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4  0x00007fdd55e7b32b _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5  0x00007fdd55c8a72e _ZN7QThread4execEv (libQt5Core.so.5)
#6  0x00007fdd562fc416 n/a (libQt5DBus.so.5)
#7  0x00007fdd55c8facd n/a (libQt5Core.so.5)
#8  0x00007fdd52c5708c start_thread (libpthread.so.0)
#9  0x00007fdd5537de7f __clone (libc.so.6)

Stack trace of thread 1018:
#0  0x00007fdd5537397b __poll (libc.so.6)
#1  0x00007fdd53fa4180 n/a (libxcb.so.1)
#2  0x00007fdd53fa5e4b xcb_wait_for_event (libxcb.so.1)
#3  0x00007fdd47cad82a n/a (libQt5XcbQpa.so.5)
#4  0x00007fdd55c8facd n/a (libQt5Core.so.5)
#5  0x00007fdd52c5708c start_thread (libpthread.so.0)
#6  0x00007fdd5537de7f __clone (libc.so.6)

systemd

**Comment by felixonmars** [comment]
How did you start deepin-menu? It doesn't crash here.
