### ISSUE TITLE
[Deepin Integration]~[V23-Beta2] Integrated for dde-introduction

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#5034]
### package information | 软件包信息

包名 | 版本
-- | --
dde-introduction | 7.0.0

### Package repository address | 软件包仓库地址

deb [trusted=yes] https://ci.deepin.com/repo/deepin/deepin-community/obs-repos/ beige main

### changelog | 更新信息

更新v23背景图

### test suggestion | 测试建议

更新v23背景图   https://pms.uniontech.com/bug-view-204809.html

### Sphere of influence | 影响范围

欢迎程序

**Comment by babyfengfjx** [comment]
请开展集成验证。

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
仓库：deb [trusted=yes] https://ci.deepin.com/repo/deepin/deepin-community/obs-repos/ beige main
内核：Linux n23-PC 6.1.32-amd64-desktop-hwe #23.01.00.17 SMP PREEMPT_DYNAMIC Thu Jul 20 15:20:17 CST 2023 x86_64 GNU/Linux
【结论】：
回归测试通过

发散测试，对欢迎应用中的各个模块进行功能验证，包括介绍模块视频播放与暂停、桌面样式的更改后效果展示、运行模式切换、图标主题的更换均验证通过
![贴图](https://github.com/linuxdeepin/developer-center/assets/17869922/146f30ae-68af-45d3-9eb1-9e192c176f11)
