### ISSUE TITLE
[Deepin Integration]~[V23-Beta2] Integrated for 玲珑音乐

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#5036]
### package information | 软件包信息

包名|版本
--|--
org.deepin.music|7.0.2.83

### Package repository address | 软件包仓库地址

仓库地址： ll-cli repo modify http://10.0.36.228:9001/ --name develop-snipe

### changelog | 更新信息

<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

BUG | 203279 | 【社区版】【deepin_V23_beta2】【内测反馈】【音乐】使用菜单中退出命令退出时,需要二次确认无法直接退出应用程序
-- | -- | --
BUG | 203779 | 【社区版】【deepin_V23_beta2】【发散测试】【音乐】标题栏翻页按钮hover文案显示有误，应为“下一页”
BUG | 205103 | 【社区版】【deepin_V23_beta2】【发散测试】【音乐】通过快捷键“.”将歌曲添加到“我喜欢的歌曲”，但歌单中未显示且喜欢图标未被标记

</body>

</html>

**Comment by babyfengfjx** [comment]
@kobe337  请开展集成验证。

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
仓库： ll-cli repo modify http://10.0.36.228:9001/ --name develop-snipe
内核：
【结论】：
测试通过，暂无严重问题及影响
