### ISSUE TITLE
No CMLists.txt

### ISSUE THREAD

**Issue by ntahlahweh** [linuxdeepin/developer-center#5039]
### SUMMARY | 问题概要

I'm trying to build the deepin-desktop-base base on the Build instructions. However upon step 3 which is the cmake .. steps I encountered this error which stated that the folder does not have CMakeLists.txt in the folder.

Can you help me out?

![image](https://github.com/linuxdeepin/developer-center/assets/48423509/3e4aa666-a333-4d2a-8731-55541f15925c)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
Distribution: Deepin 20.9 Community edition
```

### STEPS TO REPRODUCE | 复现步骤

1. Download deepin-desktop-base repo
2. go to repo folder
3. build required dependencies
4. mkdir build
5. cd build
6. cmake ..

**Comment by Decodetalkers** [comment]
yes, it use makefile

**Comment by ntahlahweh** [comment]
> Well, the README is kinda a copy-paste so the instruction is not correct.
> 
> Since it's sort of a meta-package for deb-based distro, you can use `dpkg-buildpackage` to build the package directly. (`dpkg-buildpackage -uc -us -nc -b` if I remembered correctly)

Thank you for the reply I tried sudo dpkg-buildpackage -uc -us -nc -b command and I got this error instead. Can you guide me on this what went wrong?

![image](https://github.com/linuxdeepin/developer-center/assets/48423509/311c2728-e1e9-4452-a728-7965c8e2e9ed)

**Comment by BLumia** [comment]
Well, you need to install fakeroot but you don't need to invoke fakeroot manually. After you install fakeroot, you can use `dpkg-buildpackage -uc -us -nc -b` to build (if no other development-related packages are missing).

**Comment by ntahlahweh** [comment]
Yeah that solve the current problem! Thank you!
