### ISSUE TITLE
deepinid云服务模块集成申请（第三版）

### ISSUE THREAD

**Issue by Keima-lpj** [linuxdeepin/developer-center#5046]
### package information | 软件包信息

包名 | 版本
-- | --
deepin-sync-client | 7.0.0.3
deepin-deepinid-plugin | 2.0.0.4
deepin-sync-daemon | 6.0.23.0

### Package repository address | 软件包仓库地址

deb [trusted=yes] https://aptly.uniontech.com/pkg/beige-v2/release-candidate/ZGVlcGluaWTkupHmnI3liqHnrKzkuozova4yMDIzLTA3LTE5IDEwOjExOjI0/ unstable main
deb [trusted=yes] https://aptly.uniontech.com/pkg/nonfree-beige-v2/release-candidate/ZGVlcGluaWTkupHmnI3liqHnrKzkuozova4yMDIzLTA3LTE5IDEwOjExOjI0/ unstable non-free
deb [trusted=yes] https://aptly.uniontech.com/pkg/nonfree-beige-v2/release-candidate/ZGVlcGluaWTkupHmnI3liqHnrKzkuIDova4yMDIzLTA2LTAyIDE2OjE1OjU3/ unstable non-free

### changelog | 更新信息

修复bug:

https://pms.uniontech.com/bug-view-205221.html
https://pms.uniontech.com/bug-view-205209.html
https://pms.uniontech.com/bug-view-210763.html
https://pms.uniontech.com/bug-view-205223.html
https://pms.uniontech.com/bug-view-205215.html

**Comment by babyfengfjx** [comment]
@xuqi27837288   请开展集成验证。

**Comment by xuqi27837288** [comment]
【环境】：
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【结论】：
测试通过，暂无严重问题及影响

**Comment by xuqi27837288** [comment]
后面集成中包名有所修改：
deepin-deepinid-client-dbgsym
dcc-deepinid-plugin

**Comment by xuqi27837288** [comment]
![image](https://github.com/linuxdeepin/developer-center/assets/62528742/0ad406b6-d92e-4812-99c4-a49f46cbc9a4)
