### ISSUE TITLE
dde-dock 无法支持freedesktop标准的额外应用动作

### ISSUE THREAD

**Issue by ArchieMeng** [linuxdeepin/developer-center#5058]
### SUMMARY | 问题概要

deepin-terminal应用PR https://github.com/linuxdeepin/deepin-terminal/pull/287 之后，点击dock中终端右键菜单的“新建窗口”和”雷神终端“动作，无法调用。v20的dde-dock是能正常实现调用应用的额外动作的。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
v23 dde-dock: 6.0.18
v23 dde-application-manager: 1.0.19
v20 dde-dock: 5.5.86.1-1

deepin-terminal: git+https://github.com/hotime/deepin-terminal/tree/patch-1
```

### PRE-REQUIREMENT | 预置条件

无

### STEPS TO REPRODUCE | 复现步骤

1. 启动应用了 https://github.com/linuxdeepin/deepin-terminal/pull/287 之后的deepin-terminal
2. 右键点击dock中的deepin-terminal
3. 选择”新建窗口“或”雷神终端“

### OBSERVED RESULT | 观察到的结果

v23中，这两种动作都没反应。v20中有响应。

### EXPECTED RESULT | 期望的结果

v23中这两种动作都有响应。

**Comment by ArchieMeng** [comment]
重启后已解决。

**Comment by SuperEffie** [comment]
[集成链接]：https://github.com/linuxdeepin/developer-center/issues/5114
[版本信息]：deepin-terminal：6.0.6
[验证结论]：测试通过，集成更新后，点击dock中终端右键菜单的“新建窗口”和”雷神终端“动作正常响应
[录屏信息]：
![雷神](https://github.com/linuxdeepin/developer-center/assets/58986464/73b04e46-96bf-4df5-b313-883267e1dd8b)
