### ISSUE TITLE
Launcher not working blur background

### ISSUE THREAD

**Issue by denisoster** [linuxdeepin/developer-center#506]
ArchLinux
Deepin 15.5
![deepinscreenshot_20180418001933](https://user-images.githubusercontent.com/15886355/38898675-3697c1a0-4285-11e8-9125-a581dedefe81.png)

**Comment by Ninjamasque** [comment]
yep got the same on Ubuntu 18.04 the problem seems to be on all distributions 

https://forum.manjaro.org/t/manjaro-deepin-custom-wallpaper-results-in-black-screen-on-launcher-and-logout-screen-solved/44883/5
