### ISSUE TITLE
应用商店8.0.0.0006集成申请

### ISSUE THREAD

**Issue by zty199** [linuxdeepin/developer-center#5065]
### package information | 软件包信息

包名 | 版本
-- | --
deepin-app-store | 8.0.0.0006-1
deepin-home-appstore-daemon | 8.0.0.0003-1

### Package repository address | 软件包仓库地址

deb  [trusted=yes] https://aptly.uniontech.com/pkg/nonfree-beige-v2/release-candidate/56S-5Yy654mIVjIz5bqU55So5ZWG5bqXMjAyMzAxMDYyMDIzLTAxLTA2IDE3OjIyOjQw/  unstable non-free

### changelog | 更新信息

修复 Bug：
1. https://pms.uniontech.com/bug-view-211305.html 修复应用商店安装指定版本软件包安装失败问题
2. 修复应用大小超过 2GB 的应用下载过程没有进度变化的问题
3. 修复商店客户端应用管理中玲珑包安装占用大小显示偏大的问题（现与 info.json 中 size 保持一致）

**Comment by babyfengfjx** [comment]
@vivianxf  请开展集成验证。

**Comment by vivianxf** [comment]
验证通过，请走下一步流程：
验证镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
1.仓库添加成功，系统升级成功，包版本正确
2.验证通过bug
https://pms.uniontech.com/bug-view-211305.html 修复应用商店安装指定版本软件包安装失败问题
修复应用大小超过 2GB 的应用下载过程没有进度变化的问题
修复商店客户端应用管理中玲珑包安装占用大小显示偏大的问题（现与 info.json 中 size 保持一致）
3.应用商店中英文切换正常,基本功能正常,下载卸载功能正常

综上所述，本次集成测试通过～
