### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【内测反馈】【Fcitx5】【输入法】Fcitx5无法安装搜狗细胞词典

### ISSUE THREAD

**Issue by Lichenkass** [linuxdeepin/developer-center#5072]
### SUMMARY | 问题概要

系统自带的Fcitx5无法安装搜狗细胞词典，会卡死
![preview](https://github.com/linuxdeepin/developer-center/assets/88034509/2c431af3-31f6-4d74-8137-bb98a441f642)
![preview](https://github.com/linuxdeepin/developer-center/assets/88034509/1c811771-eb5e-47e7-ad61-6ffa13a2bea1)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
系统版本：Deepin V23 Beta
fcitx5版本：5.0.23-0deepin1
```

### PRE-REQUIREMENT | 预置条件

1.加入内测，并更新最新内测内容
2.使用系统自带的fcitx5

### STEPS TO REPRODUCE | 复现步骤

依次点设置---输入法和语言一高级设置---附加组件一拼音--词典，进入拼音词典管理器，再点击导入选择在线浏览搜狗细胞词典（B），打开搜狗输入法词库首页，选择词库点击下载之后会卡住

### OBSERVED RESULT | 观察到的结果

安装卡住，除了关闭按钮，其他按钮全变灰色，无法点击，

### EXPECTED RESULT | 期望的结果

词典导入成功，点击应用后就可以使用

### ADDITIONAL INFORMATION | 额外补充

词典导入需要libime-bin依赖，系统源内的fcitx5包内Depends内没有这个依赖，建议添加这个依赖
![截图_选择区域_20230731114056](https://github.com/linuxdeepin/developer-center/assets/88034509/ce174cc2-1d6d-4976-919f-7683061cb4d8)

```[tasklist]
### Tasks
```

**Comment by BLumia** [comment]
和 https://github.com/linuxdeepin/developer-center/issues/4793 一回事吗？

**Comment by Lichenkass** [comment]
一回事

**Comment by Lichenkass** [comment]
> 和 https://github.com/linuxdeepin/developer-center/issues/4793 一回事吗？

一回事

**Comment by BLumia** [comment]
那请转到 https://github.com/linuxdeepin/developer-center/issues/4793 跟进后续，就不留着两个重复的 issue 了 :)
