### ISSUE TITLE
No CMakeLists.txt in go-dbus-factory 

### ISSUE THREAD

**Issue by ntahlahweh** [linuxdeepin/developer-center#5073]
### SUMMARY | 问题概要

I'm trying to build the go-dbus-factory  base on the Build instructions. However upon step 3 which is the cmake .. steps I encountered this error which stated that the folder does not have CMakeLists.txt in the folder.

Can you help me out?

![image](https://github.com/linuxdeepin/developer-center/assets/48423509/d8023afe-214c-4477-81c5-30fefe4010ce)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
Distribution: Deepin 20.9 Community edition
```

### STEPS TO REPRODUCE | 复现步骤

1. Download go-dbus-factory
2. go to repo folder
3. build required dependencies
4. mkdir build
5. cd build
6. cmake ..

### OBSERVED RESULT | 观察到的结果
CMake Error: The source directory "/data/home/sysadmin/dde_dtk/go-dbus-factory-master" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by BLumia** [comment]
Hi,

Similar to the [previous issue](https://github.com/linuxdeepin/developer-center/issues/5039), `dpkg-buildpackage -uc -us -nc -b` can be used to build all deepin's packages as long as there is a `debian` folder inside the root of the source folder. The README.md file indeed also needs to be corrected by the go-dbus-factory project maintainer.

**Comment by ntahlahweh** [comment]
That's what I thought beforehand before I asking and I did used the `dpkg-buildpackage -uc -us -nc -b`. However I encountered another error which I thought might be a missing file or component based on this error:

```
root@orientdots:/data/home/sysadmin/dde_dtk/go-dbus-factory-master# sudo make install
mkdir -p /usr/share/gocode/src/github.com/linuxdeepin/go-dbus-factory
for dir in object_manager net.* org.* com.*;do\
        mkdir -p /usr/share/gocode/src/github.com/linuxdeepin/go-dbus-factory/$dir;\
        cp $dir/*.go /usr/share/gocode/src/github.com/linuxdeepin/go-dbus-factory/$dir;\
done
cp: cannot stat 'net.*/*.go': No such file or directory
cp: -r not specified; omitting directory '/usr/share/gocode/src/github.com/linuxdeepin/go-dbus-factory/net.hadess.sensorproxy'
```

Could you assists me on this?

**Comment by Decodetalkers** [comment]
it use debian golang package system to package, so when packaged, this makefile is not used. The makefile is broken, you should not use it.

**Comment by ntahlahweh** [comment]
Hello, when I run this ```dpkg-buildpackage -uc -us -nc -b``` should I proceed with ```sudo make install``` afterwards?

**Comment by Decodetalkers** [comment]
No, just install the deb file, apt install ./xxx.deb

you will see there is deb file in parent folder

**Comment by ntahlahweh** [comment]
Forgive me, I am very new to this.
I tried ```sudo apt install ./xxx.deb``` but I got this error.

```
sudo apt install ./xxx.deb
Reading package lists... Done
E: Unsupported file ./xxx.deb given on commandline
```
What did I do wrong? I tried ```cd Debian``` it also does not work

**Comment by ntahlahweh** [comment]
oh that's settle it! thank you! I learn something new!

**Comment by BLumia** [comment]
Sorry I'm gonna reopen this since `go-dbus-factory` still have incorrect build instruction, which needs to be corrected. Feel free to unsubscribe this issue if you are not interested in fixing the README :)

**Comment by Decodetalkers** [comment]
Ok , I think this can be closed now
