### ISSUE TITLE
【V23 beta2】内核支持amd intel pstate识别

### ISSUE THREAD

**Issue by meiyixiang** [linuxdeepin/developer-center#5080]
需求描述：系统需要识别内存为AMD\intel CPU时，适配其全新的接口，适用于电源管理模式切换。
备注：Beta2配合内核完成此功能适配，下个版本在完成界面上修改，在intel、amd CPU提供4个电源管理选项其他cpu保持3个电源管理模式下个版本完成待需求输出后在对界面进行修改。

**Comment by Decodetalkers** [comment]
@xuqi27837288 这个可以进行回归关闭

**Comment by kobe337** [comment]
需求单已经验证通过
【环境】：
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230908/deepin-23-beige-beta2-amd64-20230908-160331.iso
内核：Linux deepin23-PC 6.4.7 
【结论】：
测试通过，暂无严重问题及影响

pstate已经集成，电源选项由之前的3项增加为4项，GUI变动产品经理已规划
![image](https://github.com/linuxdeepin/developer-center/assets/17869922/1704f2cc-745a-40b2-aa10-cc8be28f8d6b)
