### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【集成测试】【窗口管理器】WPS协议界面显示异常，出现多余 X 图标

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#5081]
### SUMMARY | 问题概要

PMS转github,原PMS链接地址：https://pms.uniontech.com/bug-view-182471.html

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
1. 镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/20230105/deepin-23-beige-amd64-20230105-145449.iso

2. 内核版本：Linux v233-PC 5.18.17-amd64-desktop-hwe #23.01.00.06 SMP PREEMPT_DYNAMIC Mon Oct 31 17:25:49 CST 2022 x86_64 GNU/Linux    

3. WPS  版本11.1.0.11664 2022.06.08
```

### PRE-REQUIREMENT | 预置条件

1. 已经安装镜像：   https://cdimage.uniontech.com/daily-iso/image-beige/20230105/deepin-23-beige-amd64-20230105-145449.iso

2. 已经安装 WPS ： https://wps-linux-personal.wpscdn.cn/wps/download/ep/Linux2019/11664/wps-office_11.1.0.11664_amd64.deb

### STEPS TO REPRODUCE | 复现步骤

1.  在桌面新建表格文件
2. 右键选择使用 WPS打开   

### OBSERVED RESULT | 观察到的结果

WPS协议界面出现多余图标
![file-read-587531](https://github.com/linuxdeepin/developer-center/assets/96416089/ea3649f4-119b-4c78-b124-1984fbe2bf57)

### EXPECTED RESULT | 期望的结果

可以正常打开且WPS协议界面不存在多余图标

**Comment by babyfengfjx** [comment]
@justforlxz 请优先帮忙处理。

**Comment by justforlxz** [comment]
<img width="856" alt="image" src="https://github.com/linuxdeepin/developer-center/assets/12298476/d2ea8e21-9131-470b-b16e-e0af7af4a3f2">

这个X的意思是窗口没设置图标，工作在 x11 环境下的意思。。

在kde下显示的也是同样的，只不过主题里的图标不同。

![image](https://github.com/linuxdeepin/developer-center/assets/12298476/883fd967-b4fd-41e9-b352-4e85a18de4aa)


如果是在 wayland 下，还会显示成这样。

<img width="212" alt="image" src="https://github.com/linuxdeepin/developer-center/assets/12298476/6004f6aa-cf2e-43a4-8abc-52325f3ff0a9">

**Comment by hudeng-go** [comment]
[papirus-icon-theme](https://github.com/deepin-community/papirus-icon-theme/blob/master/Papirus/16x16/apps/xorg.svg)包的如下资源需要被替换
 /usr/share/icons/Papirus/16x16/apps/xorg.svg
 /usr/share/icons/Papirus/64x64/apps/xorg.svg
/usr/share/icons/Papirus/22x22/apps/xorg.svg
/usr/share/icons/Papirus/24x24/apps/xorg.svg
/usr/share/icons/Papirus/48x48/apps/xorg.svg
/usr/share/icons/Papirus/32x32/apps/xorg.svg

@babyfengfjx @meiyixiang 需要设计提供对应的替换资源。

**Comment by hudeng-go** [comment]
@justforlxz 帮忙看看吧？

**Comment by wineee** [comment]
> [papirus-icon-theme](https://github.com/deepin-community/papirus-icon-theme/blob/master/Papirus/16x16/apps/xorg.svg?rgh-link-date=2023-08-04T03%3A33%3A24Z)包的如下资源需要被替换： /usr/share/icons/Papirus/16x16/apps/xorg.svg /usr/share/icons/Papirus/64x64/apps/xorg.svg /usr/share/icons/Papirus/22x22/apps/xorg.svg /usr/share/icons/Papirus/24x24/apps/xorg.svg /usr/share/icons/Papirus/48x48/apps/xorg.svg /usr/share/icons/Papirus/32x32/apps/xorg.svg
> 
> @babyfengfjx @meiyixiang 需要设计提供对应的替换资源。

为什么要替换这几个图标，替换成什么样子？

另外这里应该是预期 WPS 不显示图标，还是显示 wps 的图标？

**Comment by hudeng-go** [comment]
> > [papirus-icon-theme](https://github.com/deepin-community/papirus-icon-theme/blob/master/Papirus/16x16/apps/xorg.svg?rgh-link-date=2023-08-04T03%3A33%3A24Z)包的如下资源需要被替换： /usr/share/icons/Papirus/16x16/apps/xorg.svg /usr/share/icons/Papirus/64x64/apps/xorg.svg /usr/share/icons/Papirus/22x22/apps/xorg.svg /usr/share/icons/Papirus/24x24/apps/xorg.svg /usr/share/icons/Papirus/48x48/apps/xorg.svg /usr/share/icons/Papirus/32x32/apps/xorg.svg
> > @babyfengfjx @meiyixiang 需要设计提供对应的替换资源。
> 
> 为什么要替换这几个图标，替换成什么样子？
> 
> 另外这里应该是预期 WPS 不显示图标，还是显示 wps 的图标？

预期是显示wps的图片，但是商店wps的包没有规范的提供图标路径，导致加载失败，商店应用咱目前也改不了，所以 @babyfengfjx 这边的折中预期就是显示一个好看点的x图标。
![image](https://github.com/linuxdeepin/developer-center/assets/69233028/b8f562ba-de16-409a-b162-7b5021c25b20)

**Comment by luodeepin** [comment]
验证通过
![5081](https://github.com/linuxdeepin/developer-center/assets/96416089/6d6b7c21-2738-4b3e-91c0-b3865730a8cb)
