### ISSUE TITLE
dock entries removed with every pkg update

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/developer-center#510]
This is an old issue that somehow never got fixed. On a rolling release distribution this is quite annoying.
Every time an application receives a package update the dock entry will be removed and it has to be re-added manually.
It would be great if you could provide a proper solution for this.
Thanks.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
