### ISSUE TITLE
[Deepin Integration]~[V23-Beta2] Integrated for linux-firmware & kernel

### ISSUE THREAD

**Issue by matrix-wsk** [linuxdeepin/developer-center#5101]
### package information | 软件包信息

linux-firmware | 1.202.13
linux-headers-6.1.32-amd64-desktop-hwe | 23.01.00.19
linux-image-6.1.32-amd64-desktop-hwe | 23.01.00.19

### Package repository address | 软件包仓库地址

deb [trusted=yes] https://ci.deepin.com/repo/deepin/deepin-community/obs-repos/  kernel main 

### test suggestion | 测试建议

重点关注功能续航优化

### Sphere of influence | 影响范围

功耗续航
更多的硬件驱动兼容PMIC/audio/

**Comment by babyfengfjx** [comment]
@kobe337  重点关注一下续航方面的表现，其中涉及到需要了解的信息，及时与内核组同事沟通。

**Comment by kobe337** [comment]
与研发同事获取本次的内核配置信息项验证通过：
![image](https://github.com/linuxdeepin/developer-center/assets/17869922/fbbd20e0-a872-4106-931f-6c7816f3812f)

**Comment by kobe337** [comment]
![image](https://github.com/linuxdeepin/developer-center/assets/17869922/712ed386-a47a-4b71-97a8-d449fda3153f)
通过续航性能数据采集，根据目前的数据显示，续航较6.1.11版本，有35%的提升。@babyfengfjx @matrix-wsk

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
仓库：deb [trusted=yes] https://ci.deepin.com/repo/deepin/deepin-community/obs-repos/ kernel main
内核：Linux v23-PC 6.1.32-amd64-desktop-hwe #23.01.00.19 SMP PREEMPT_DYNAMIC Wed Aug  2 17:06:10 CST 2023 x86_64 GNU/Linux
【结论】：
测试通过，暂无严重问题及影响

华为设备输出有显示，仍没有声音，与研发同事沟通，本次主要验证续航优化情况。
