### ISSUE TITLE
长时间不动待机黑屏后，再次按键盘，键盘灯亮、屏幕黑屏，睡眠后按开关键可以再次点亮屏幕

### ISSUE THREAD

**Issue by licaide** [linuxdeepin/developer-center#5107]
### SUMMARY | 问题概要

长时间不动待机黑屏后，再次按键盘，键盘灯亮、屏幕黑屏，睡眠后按开关键可以再次点亮屏幕

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
v20.9
```

### STEPS TO REPRODUCE | 复现步骤

长时间不动待机黑屏后，再次按键盘，键盘灯亮、屏幕黑屏，睡眠后按开关键可以再次点亮屏幕

### OBSERVED RESULT | 观察到的结果

长时间不动待机黑屏后，再次按键盘，键盘灯亮、屏幕黑屏，睡眠后按开关键可以再次点亮屏幕

### EXPECTED RESULT | 期望的结果

长时间不动待机黑屏后，再次按键盘屏幕正常点亮

### ADDITIONAL INFORMATION | 额外补充

目前只能吧待机功能关闭

**Comment by xuqi27837288** [comment]
@kobe337 帮忙复现看一下v23是否有该问题存在~

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
内核：Linux deepin23-PC 6.1.32-amd64-desktop-hwe #1 SMP PREEMPT_DYNAMIC Mon Jul 24 11:06:51 CST 2023 x86_64 GNU/Linux
【结论】：
台式机未能复现

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
内核：Linux v23-PC 6.1.32-amd64-desktop-hwe #23.01.00.19 SMP PREEMPT_DYNAMIC Wed Aug  2 17:06:10 CST 2023 x86_64 GNU/Linu
【结论】：
笔记本目前未能复现

**Comment by kobe337** [comment]
目前团队的人力主要覆盖在v23,在v23上目前没有此问题，此问题暂时以关闭处理。
