### ISSUE TITLE
.flatpakref ... files for deepin flatpak apps and other flatpak apps available on Deepin Store ???

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#511]
Hi,

I would like to know if i can download '.flatpakref' files for the various deepin flatpak apps as well as other flatpak apps available on the Deepin Store ?

the reason i need this files so that i can install these apps to a separate flatpak remote which i have created on a separate partition on my harddisk.

Any chance of listing Deepin flatpak apps on flathub store ?

thanks.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
