### ISSUE TITLE
kernel6.4.7

### ISSUE THREAD

**Issue by matrix-wsk** [linuxdeepin/developer-center#5110]
### package information | 软件包信息

linux-headers-6.4.7-amd64-desktop-hwe |6.4.7-1
linux-image-6.4.7-amd64-desktop-hwe | 6.4.7-1
nvidia-driver | 530.41.03-2

### Package repository address | 软件包仓库地址

deb [trusted=yes] https://ci.deepin.com/repo/deepin/deepin-community/obs-repos/ kernel main
deb [trusted=yes] https://ci.deepin.com/repo/obs/home:/zeno:/deepin-system-upgrade/Deepin_23/ ./

### changelog | 更新信息

新增6.4.7内核

### test suggestion | 测试建议

系统启动基本功能测试，网卡、蓝牙、音频、视屏、休眠待机等常用场景测试

### Sphere of influence | 影响范围

对新机型支持比较好

**Comment by vivianxf** [comment]
测试不通过
升级内核报错,修复
![截图_deepin-terminal_20230804144114](https://github.com/linuxdeepin/developer-center/assets/96415804/ea17137f-1f39-478d-a7bd-cf09c4a4570a)

**Comment by Zeno-sole** [comment]
@vivianxf  验证一下nvidia-driver更新后的版本是否失败kernel 6.4

**Comment by Zeno-sole** [comment]
@xuqi27837288  已更新nvidia驱动，请安排重新验证一下

**Comment by xuqi27837288** [comment]
@vivianxf 麻烦重新进行验证并反馈测试结论，谢谢~

**Comment by vivianxf** [comment]
验证通过，请下一步流程:

内核用例提单:https://pms.uniontech.com/bug-view-214207.html (三级问题)

验证镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
1.仓库添加成功，系统升级成功，包版本正确
2.执行[https://pms.uniontech.com/testcase-browse-353--byModule-86663.html 内核用例提单:214207]
3.多种格式的音频视频播放正常
4.网络功能使用正常
5.外设连接:蓝牙耳机,蓝牙鼠标,蓝牙键盘,有线耳机使用均正常
6.更新最新版本内核,打开安全启动,系统正常使用
7.本次内核更新,仅供用户手动下载

综上所述，本次集成测试通过～
