### ISSUE TITLE
Deepin-23内测版 Wayland session启动超级慢,还容易卡死

### ISSUE THREAD

**Issue by LFRon** [linuxdeepin/developer-center#5111]
### SUMMARY | 问题概要

deepin 23最新内测版启动超级慢,不是一般的慢,比KDE Plasma 5.27还慢,加载时移动鼠标还容易卡死

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
Distribution:23-最新内测版
```

### PRE-REQUIREMENT | 预置条件

使用Intel Core i3-4005U和AMD Radeon HD 8550M启动DDE的wayland session

### STEPS TO REPRODUCE | 复现步骤

全新

### OBSERVED RESULT | 观察到的结果

光卡在tty能卡几十秒,进去再黑屏卡住几十秒,然后出现应用图标接着再卡几十秒,然后才能流畅使用
中途移动一下鼠标直接卡死,只能用内核极(Ctrl+PrtSc+r,e,i,s.u,b)紧急重启

### EXPECTED RESULT | 期望的结果

DDE Wayland启动速度能快一些

### ADDITIONAL INFORMATION | 额外补充

大佬们,帮忙修一下,我想玩Waydroid,谢谢!

**Comment by LFRon** [comment]
好不容易等了4分钟启动Wayland session,dock栏还缩成一团,emmm

**Comment by LFRon** [comment]
我今天测了一下,进入速度从3分钟变成2分钟,稍微快了一点,但DDE Dock偶尔无法出现
而且主要在这里卡很久,然后黑屏出现鼠标再过一会,才出现DE可以使用
![Cache_658c39e736d3fad4](https://github.com/linuxdeepin/developer-center/assets/141307807/d49b3528-0512-4351-9954-0debf4e136f9)

**Comment by LFRon** [comment]
提个小建议:是否能将KDE组件升级一下到5.27.5?我用KDE NEON的5.27.5感觉挺稳的,而且5.27也是长期支持版本

**Comment by BLumia** [comment]
> 提个小建议:是否能将KDE组件升级一下到5.27.5?我用KDE NEON的5.27.5感觉挺稳的,而且5.27也是长期支持版本

与原始反馈不相关的反馈请开新的 discussion 讨论。Issue 面板是纯粹用来跟进明确的 BUG 的，展开不相关的讨论会导致这些额外的讨论无法被跟进。

**Comment by BLumia** [comment]
> 好不容易等了4分钟启动Wayland session,dock栏还缩成一团,emmm

> 我今天测了一下,进入速度从3分钟变成2分钟,稍微快了一点,但DDE Dock偶尔无法出现

在仓库毫无变化的情况下，时间差异变化这么大，感觉不太像是目前 wayland session 启动顺序的问题。

无论如何既然有此反馈，麻烦测试人员尝试复现。

**Comment by LFRon** [comment]
刚刚看到我在社区反馈的这个bug已经被确认了,是确认确实有这bug嘛😂

**Comment by BLumia** [comment]
不建议重复投递反馈，深度之家和 Issue 选一个反馈就行了。后者是建议你非常有把握确定你反馈的问题就是 BUG 的时候再使用的。

**Comment by BLumia** [comment]
请转到 https://github.com/linuxdeepin/developer-center/issues/5128 进行跟进，或在深度之家跟进后续。
