### ISSUE TITLE
deepin-desktop-schemas: non-deterministic overrides

### ISSUE THREAD

**Issue by bmwiedemann** [linuxdeepin/developer-center#5117]
### SUMMARY | 问题概要

While working on [reproducible builds](https://reproducible-builds.org/) for [openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds), I found that
building our `deepin-desktop-schemas` twice produced diffs in 4 override files

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin-desktop-schemas-5.10.11
openSUSE-Tumbleweed-20230801
```

### STEPS TO REPRODUCE | 复现步骤

build it twice

### OBSERVED RESULT | 观察到的结果

4 files differed:
* /usr/share/deepin-desktop-schemas/desktop-override
* /usr/share/deepin-desktop-schemas/personal-override
* /usr/share/deepin-desktop-schemas/pro-override
* /usr/share/deepin-desktop-schemas/server-override

```diff
+++ new//usr/share/deepin-desktop-schemas/desktop-override      2022-08-27 00:00:00.000000000 +0000
@@ -2,9 +2,9 @@
 openapi-url='https://openapi.deepin.com'

 [com.deepin.service.sync]
-sync-url='https://sync.deepinid.deepin.com/api/v1'
 client-id='163296859db7ff8d72010e715ac06bdf6a2a6f87'
 redirect-uri='https://sync.deepinid.deepin.com/oauth/callback'
+sync-url='https://sync.deepinid.deepin.com/api/v1'

 [com.deepin.service.push]
```

### EXPECTED RESULT | 期望的结果

It should be possible to get bit-identical outputs in two builds.
Please sort entries during processing.

### ADDITIONAL INFORMATION | 额外补充

My guess is that keyfile dictionaries don't have deterministic ordering in output at
https://github.com/linuxdeepin/deepin-desktop-schemas/blob/master/tools/override/main.go#L156

**Comment by Decodetalkers** [comment]
Thanks for bug report, Now the key is sorted first, can you try this pr? if it works, I think we can merge it

**Comment by Decodetalkers** [comment]
if there is still problems, please open it

**Comment by bmwiedemann** [comment]
I applied 98.patch on 5.10.11 but still get various diffs in .override files:
```diff
 [com.deepin.wrap.pantheon.desktop.gala.animations]
+enable-animations=true
+open-duration=350
 snap-duration=250
 close-duration=300
 menu-duration=150
 minimize-duration=200
 workspace-switch-duration=300
-enable-animations=true
-open-duration=350


 [com.deepin.dde.power]
-line-power-sleep-delay=0
-battery-sleep-delay=0
 ambient-light-adjust-brightness=false
 screen-black-lock=false
+line-power-sleep-delay=0
+battery-sleep-delay=0
```

**Comment by Decodetalkers** [comment]
> ```diff
> com.deepin.wrap.pantheon.desktop.gala.animations
> ```

which file are you looking into? you should try the lastest tag, and look into result folder. the keys should have been sorted

**Comment by bmwiedemann** [comment]
The first diff is from /usr/share/glib-2.0/schemas/90_deepin_base.gschema.override
and then 2nd one from /usr/share/glib-2.0/schemas/91_deepin_product.gschema.override

Is there another patch that I would need to pick?
Adding https://github.com/linuxdeepin/deepin-desktop-schemas/commit/b06881866407215a1129fd0edb9bcbaeaef66ada does not seem to help either.

**Comment by Decodetalkers** [comment]
I don't know what happened, can you try clone the repo , and run make , to see the the target under result folders? the keys are sorted by string, the shouldn't be random

**Comment by bmwiedemann** [comment]
Ah, I just remembered that we build the `override` tool separately, so I ran an unpatched one.

**Comment by bmwiedemann** [comment]
So when testing correctly, it is indeed fixed with the 98.patch. :+1:
