### ISSUE TITLE
WebP support for Deepin Screen Recorder/Screenshot/Image Viewer

### ISSUE THREAD

**Issue by OmarEmaraDev** [linuxdeepin/developer-center#512]
From google's [introduction to the format](https://developers.google.com/speed/webp/):

> WebP is a modern **image format** that provides superior **lossless and lossy** compression for images on the web. Using WebP, webmasters and web developers can create smaller, richer images that make the web faster.

> WebP lossless images are **26%** smaller in size compared to PNGs. WebP lossy images are **25-34%** smaller than comparable JPEG images at equivalent **SSIM** quality index.

It also support animated images, so it serves as an alternative for PNGs, JPEGs and GIFs. And it is getting widely used in the web. Encoding and decoding can be done using the `libwebp` library provided by google or using `ffmpeg`.

From all that, I think it is worth adding support for this format in the Deepin Ecosystem.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
