### ISSUE TITLE
[deepin 23 Beta] Screen brightness adjustment does not work

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#5125]
### SUMMARY | 问题概要

The deepin 23 in _Wayland mode_ does not allow adjusting the brightness of the computer screen.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin 23 (OsBuild=21238.100)
```

### PRE-REQUIREMENT | 预置条件

Launch the interface in Wayland mode.

### STEPS TO REPRODUCE | 复现步骤

1. Launch the interface in Wayland mode;
2. Open the screen tweak on the dock or directly in Control Center.

### EXPECTED RESULT | 期望的结果

It should adjust the screen brightness.

**Comment by meiyixiang** [comment]
此问题是否已经修复，如果在自研的wayland下会进行修复可以回复用户告知

**Comment by lxwndr** [comment]
> 此问题是否已经修复，如果在自研的wayland下会进行修复可以回复用户告知

No, the problem persists.

**Comment by lxwndr** [comment]
I understand that this problem is more of a suggestion. Therefore, I am closing this issue and forwarding it as a suggestion via Deepin Home.
