### ISSUE TITLE
[deepin 23 Beta] Dock doesn't autohide

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#5126]
### SUMMARY | 问题概要

The dock is not automatically hidden when an application is displayed in full screen. The Wayland mode is active.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
dde-dock 6.0.18
deepin 23 (OsBuild=21238.100)
```

### STEPS TO REPRODUCE | 复现步骤

1. It is necessary to open: Control Center > Personalization, and access the Desktop tab; and in dock state, activate the "Smart hide" option.
2. Open any app in full screen and the dock will continue to show.

![Capturar_20230806215354](https://github.com/linuxdeepin/developer-center/assets/45263160/80f0b2b3-334f-4740-a333-aa83ca96ca55)

### EXPECTED RESULT | 期望的结果

When any app is maximized, the dock should auto-hide.

**Comment by meiyixiang** [comment]
这个问题是否已经修复如已经修复请关闭

**Comment by lxwndr** [comment]
> 这个问题是否已经修复如已经修复请关闭

No, the problem still persists.

**Comment by lxwndr** [comment]
The problem remains unresolved, however, I am closing this complaint as I forwarded it again via deepin Home.
