### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【内测反馈】【DDE】【任务栏】安装 jetbrains-toolbox 后点击任务托盘任务栏崩溃

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#5130]
### SUMMARY | 问题概要

安装 jetbrains-toolbox 后点击任务托盘任务栏崩溃

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
版本信息：dde-dock:6.0.18
```

### PRE-REQUIREMENT | 预置条件

https://www.jetbrains.com/products/
下载jetbrains-toolbox
![image](https://github.com/linuxdeepin/developer-center/assets/96415804/6db1e712-8581-41a2-b1eb-1c0ee2cba1c6)

### STEPS TO REPRODUCE | 复现步骤

1.解压缩下载的文件
2.双击运行文件
3.重启系统
4.在任务啦折叠面板点击jetbrains-toolbox
5.观察任务栏展示

### OBSERVED RESULT | 观察到的结果

1.任务栏崩溃重启

https://github.com/linuxdeepin/developer-center/assets/96415804/62db86c8-f12b-4975-9f2b-3693ef370468

### EXPECTED RESULT | 期望的结果

1.jetbrains-toolbox正常运行,任务栏不会崩溃

**Comment by xuqi27837288** [comment]
@vivianxf 应用商店暂无此应用,晓飞后面帮忙回归一下该问题吧~

#5148 
仓库地址:
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-311/testing/ ./

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0516镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
【截图录屏】：

![截图_选择区域_20230810143059](https://github.com/linuxdeepin/developer-center/assets/62528742/94200b5c-41e8-4084-9cad-f362be4fad6a)
