### ISSUE TITLE
V23 wayland 模式下进入桌面时间较长

### ISSUE THREAD

**Issue by chenchongbiao** [linuxdeepin/developer-center#5134]
### SUMMARY | 问题概要

1. dde-file-manager 的里面编写的dde-filemanager-server.desktop 需要删除，dde-filemanager-server.service 文件需要交由dde-session.service管理。需要调整启动顺序在kwin启动之后再启动，并且在dde-session退出之后被dde-session带走。
2. deepin-kwin-wayland 和 dde-apearance 互相调用的问题。
3. deepin-kwin_wayland.service 和 deepin-kwin_x11.service文件需要去除，会妨碍 wayland session的启动。
4. 5.dde-session-daemon 初始化非常慢，使用journalctl -f 可以看到非常多的日志输出与touchpad.go:360 与 touchpad.go:371 刷出 `libinput unsupported palm detect setting` 这段时间触控板和鼠标无法被使用，时间长度大约在10-20秒 。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
v23 ci版本
```

### STEPS TO REPRODUCE | 复现步骤

1. 需要安装 dde-wayland-config 包。打开 wayland 入口。
2. 从lightdm进入wayland桌面，可以使用tty2 使用journalctl -f 观察日志。有概率出现dde-desktop-server codedump 。
3. 会出现一行dbus daemon 报告 deepin-kwin 调用 dde-appearance 大约10秒。
4. 在 kwin 跑完之后会出现daemon出现大量日志，同时输入设备完全失灵，此时可以看到鼠标，但是无法看到背景（dde-filemanager-server已经挂掉）

### EXPECTED RESULT | 期望的结果

wayland 正常进入桌面。

**Comment by chenchongbiao** [comment]
#5128

**Comment by xuqi27837288** [comment]
https://github.com/linuxdeepin/developer-center/issues/5128
验证通过，该问题单关闭
