### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【内测反馈】【日历】在日历中输入deepid id账号密码后无法正常登录deepin id云服务

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#5151]
### SUMMARY | 问题概要

必现问题

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
内核信息: Linux n23-PC 6.1.32-amd64-desktop-hwe #23.01.00.17 SMP PREEMPT_DYNAMIC Thu Jul 20 15:20:17 CST 2023 x86_64 GNU/Linux

日历：5.9.12
```

### PRE-REQUIREMENT | 预置条件

可以正常进入日历

### STEPS TO REPRODUCE | 复现步骤

在日历中登录deepin id

### OBSERVED RESULT | 观察到的结果

输入账号密码后无法正常展示deepin id登录状态及正常登录

https://github.com/linuxdeepin/developer-center/assets/62528742/b9f892c4-4f93-4de0-a304-99ab335a3b73

### EXPECTED RESULT | 期望的结果

登录后可以正常展示用户相关信息

**Comment by vivianxf** [comment]
验证镜像:https://cdimage.uniontech.com/community/releases/23-Beta2/deepin-desktop-community-23-Beta2-amd64.iso
验证版本:dde-calendar:5.11.1
新版本屏蔽所有日历账号功能
验证结果:通过
![截图_dde-desktop_20231215150951](https://github.com/linuxdeepin/developer-center/assets/96415804/1c62a0a6-b037-401c-8d37-557a646c0912)
