### ISSUE TITLE
【deepin_V23-beta】【一般】【有空】【集成测试】【DDE】【启动器】在星火商店下载的redis viewer安装成功后在启动器不显示图标

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#5166]
### SUMMARY | 问题概要

在星火商店下载的redis viewer安装成功后在启动器不显示图标

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230512
dde-launcher:6.0.14
```

### STEPS TO REPRODUCE | 复现步骤

1.在应用商店下载星火应用商店
2.在星火应用商店下载redis viewer应用
3.在启动器查看redis viewer图标

### OBSERVED RESULT | 观察到的结果

1.启动器没有redis viewer图标
![image](https://github.com/linuxdeepin/developer-center/assets/96415804/35d262f8-2eb4-413d-8ec9-5c0387453692)

### EXPECTED RESULT | 期望的结果

1.启动器内可以搜索到redis viewer图标

**Comment by babyfengfjx** [comment]
@BLumia  请帮忙分析~

**Comment by Zeno-sole** [comment]
@kegechen  需要AM这边看下是否有正确识别到desktop文件

**Comment by ComixHe** [comment]
新AM中问题已修复

**Comment by vivianxf** [comment]
验证镜像:https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20231116/
验证版本:dde-launchpad:0.0.2
验证步骤:提单的步骤
验证现象:在星火商店下载的redis viewer在启动器正常显示
验证结果:通过
![截图_dde-launchpad_20231124094512](https://github.com/linuxdeepin/developer-center/assets/96415804/dd56c356-d8f1-4ef0-b8e9-5038ccd8bb25)
