### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【发散测试】【深度之家】无法打开深度之家

### ISSUE THREAD

**Issue by belirux** [linuxdeepin/developer-center#5168]
### SUMMARY | 问题概要

打开深度之家时，中间出现加载动画后，便自动关闭窗口，只剩托盘图标，再次点击现象重复

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
OS: Deepin 23 x86_64
Host: Alienware m15 R7
Kernel: 6.4.7-amd64-desktop-hwe
CPU: 12th Gen Intel(R) Core(TM) i7-12700H (20) @ 4.6 GHz

Package: deepin-home
Version: 1.3.2
```

### PRE-REQUIREMENT | 预置条件

无

### STEPS TO REPRODUCE | 复现步骤

双击打开深度之家

### OBSERVED RESULT | 观察到的结果

卡加载画面 便闪退

### EXPECTED RESULT | 期望的结果

能正常打开，ps：我都没见过深度之家的正常画面

### ADDITIONAL INFORMATION | 额外补充

https://github.com/linuxdeepin/developer-center/assets/138775053/fd7e0951-e6f2-4006-bc35-beb408f67e85

**Comment by BLumia** [comment]
这个终端配色完全看不清输出= =

似乎最后是 coredump 了，可以[提供下 coredump 转储文件或者 stacktrace](https://wiki.deepin.org/Coredump%E5%B7%A5%E5%85%B7%E4%BD%BF%E7%94%A8%E4%B8%8E%E6%97%A5%E5%BF%97%E5%AF%BC%E5%87%BA) 吗？

**Comment by belirux** [comment]
> 这个终端配色完全看不清输出= =
> 
> 似乎最后是 coredump 了，可以[提供下 coredump 转储文件或者 stacktrace](https://wiki.deepin.org/Coredump%E5%B7%A5%E5%85%B7%E4%BD%BF%E7%94%A8%E4%B8%8E%E6%97%A5%E5%BF%97%E5%AF%BC%E5%87%BA) 吗？

```
❯ deepin-home
Load for deepin-home 's plugin path: /usr/lib/x86_64-linux-gnu/dtkdeclarative/qml-app/libdeepin-home-preload.so
load translate "/usr/share/dtk5/DDeclarative/translations/dtkdeclarative_zh_CN"
worker: clean up saved screenshots
Load for deepin-home 's plugin path: /usr/lib/x86_64-linux-gnu/dtkdeclarative/qml-app/libdeepin-home-main.so
qt.qpa.xcb: QXcbConnection: XCB error: 5 (BadAtom), sequence: 454, resource id: 0, major code: 20 (GetProperty), minor code: 0
qml: font_size_t1 40
qml: font_size_t2 30
qml: font_size_t3 24
qml: font_size_t4 20
qml: font_size_t5 17
qml: font_size_t6 14
qml: font_size_t7 13
qml: font_size_t8 12
qml: font_size_t9 11
qml: font_size_t10 10
worker: is login
worker: get message
worker: get language
qml: current route index
Cannot mix incompatible Qt library (5.15.8) with this library (5.15.7)
[1]    10202 IOT instruction (core dumped)  deepin-home
```
```
❯ coredumpctl
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
TIME                          PID  UID  GID SIG     COREFILE EXE                                          SIZE
Fri 2023-08-11 19:49:47 CST  8608 1000 1000 SIGABRT present  /usr/bin/deepin-home                         4.9M
Fri 2023-08-11 23:37:31 CST 15498 1000 1000 SIGABRT present  /usr/bin/deepin-home                         4.9M
Fri 2023-08-11 23:44:28 CST 17134 1000 1000 SIGABRT present  /usr/bin/deepin-home                         4.9M
Fri 2023-08-11 23:46:08 CST 17351 1000 1000 SIGABRT present  /usr/bin/deepin-home                         4.9M
Fri 2023-08-11 23:46:39 CST 17595 1000 1000 SIGABRT present  /usr/bin/deepin-home                         4.9M
Sat 2023-08-12 22:01:44 CST  4703 1000 1000 SIGTRAP present  /opt/uTools/utools                           9.5M
Sat 2023-08-12 22:01:45 CST  4730 1000 1000 SIGABRT present  /usr/bin/dde-file-manager-server             2.4M
Sat 2023-08-12 22:57:39 CST  4651 1000 1000 SIGABRT present  /usr/bin/dde-file-manager-server             2.4M
Sat 2023-08-12 22:57:52 CST 27447 1000 1000 SIGABRT present  /usr/bin/dde-appearance                    772.4K
Sat 2023-08-12 23:00:18 CST 30968 1000 1000 SIGABRT present  /usr/bin/deepin-home                         5.5M
Sat 2023-08-12 23:02:10 CST 37438 1000 1000 SIGTRAP present  /opt/uTools/utools                           9.5M
Sat 2023-08-12 23:02:10 CST 37476 1000 1000 SIGABRT present  /usr/bin/dde-file-manager-server             2.4M
Sat 2023-08-12 23:02:40 CST 41535 1000 1000 SIGTRAP present  /opt/uTools/utools                           9.8M
Sat 2023-08-12 23:02:41 CST 41187 1000 1000 SIGABRT present  /usr/bin/dde-file-manager-server             2.4M
Sat 2023-08-12 23:22:25 CST 46126 1000 1000 SIGTRAP present  /opt/uTools/utools                           9.5M
Sat 2023-08-12 23:22:25 CST 45772 1000 1000 SIGABRT present  /usr/bin/dde-file-manager-server             2.4M
Sun 2023-08-13 10:28:48 CST 18111 1000 1000 SIGSEGV present  /usr/libexec/dde-cooperation/input-grabber 218.1K
Mon 2023-08-14 09:33:17 CST 10202 1000 1000 SIGABRT present  /usr/bin/deepin-home                         5.5M
```
最近的一次日志：
[core.deepin-home.1000.9664a418d20848cdabaf895eda485e91.10202.zip](https://github.com/linuxdeepin/developer-center/files/12330922/core.deepin-home.1000.9664a418d20848cdabaf895eda485e91.10202.zip)

**Comment by Decodetalkers** [comment]
> > 这个终端配色完全看不清输出= =
> > 似乎最后是 coredump 了，可以[提供下 coredump 转储文件或者 stacktrace](https://wiki.deepin.org/Coredump%E5%B7%A5%E5%85%B7%E4%BD%BF%E7%94%A8%E4%B8%8E%E6%97%A5%E5%BF%97%E5%AF%BC%E5%87%BA) 吗？
> 
> ```
> ❯ deepin-home
> Load for deepin-home 's plugin path: /usr/lib/x86_64-linux-gnu/dtkdeclarative/qml-app/libdeepin-home-preload.so
> load translate "/usr/share/dtk5/DDeclarative/translations/dtkdeclarative_zh_CN"
> worker: clean up saved screenshots
> Load for deepin-home 's plugin path: /usr/lib/x86_64-linux-gnu/dtkdeclarative/qml-app/libdeepin-home-main.so
> qt.qpa.xcb: QXcbConnection: XCB error: 5 (BadAtom), sequence: 454, resource id: 0, major code: 20 (GetProperty), minor code: 0
> qml: font_size_t1 40
> qml: font_size_t2 30
> qml: font_size_t3 24
> qml: font_size_t4 20
> qml: font_size_t5 17
> qml: font_size_t6 14
> qml: font_size_t7 13
> qml: font_size_t8 12
> qml: font_size_t9 11
> qml: font_size_t10 10
> worker: is login
> worker: get message
> worker: get language
> qml: current route index
> Cannot mix incompatible Qt library (5.15.8) with this library (5.15.7)
> [1]    10202 IOT instruction (core dumped)  deepin-home
> ```
> 
> ```
> ❯ coredumpctl
> Hint: You are currently not seeing messages from other users and the system.
>       Users in groups 'adm', 'systemd-journal' can see all messages.
>       Pass -q to turn off this notice.
> TIME                          PID  UID  GID SIG     COREFILE EXE                                          SIZE
> Fri 2023-08-11 19:49:47 CST  8608 1000 1000 SIGABRT present  /usr/bin/deepin-home                         4.9M
> Fri 2023-08-11 23:37:31 CST 15498 1000 1000 SIGABRT present  /usr/bin/deepin-home                         4.9M
> Fri 2023-08-11 23:44:28 CST 17134 1000 1000 SIGABRT present  /usr/bin/deepin-home                         4.9M
> Fri 2023-08-11 23:46:08 CST 17351 1000 1000 SIGABRT present  /usr/bin/deepin-home                         4.9M
> Fri 2023-08-11 23:46:39 CST 17595 1000 1000 SIGABRT present  /usr/bin/deepin-home                         4.9M
> Sat 2023-08-12 22:01:44 CST  4703 1000 1000 SIGTRAP present  /opt/uTools/utools                           9.5M
> Sat 2023-08-12 22:01:45 CST  4730 1000 1000 SIGABRT present  /usr/bin/dde-file-manager-server             2.4M
> Sat 2023-08-12 22:57:39 CST  4651 1000 1000 SIGABRT present  /usr/bin/dde-file-manager-server             2.4M
> Sat 2023-08-12 22:57:52 CST 27447 1000 1000 SIGABRT present  /usr/bin/dde-appearance                    772.4K
> Sat 2023-08-12 23:00:18 CST 30968 1000 1000 SIGABRT present  /usr/bin/deepin-home                         5.5M
> Sat 2023-08-12 23:02:10 CST 37438 1000 1000 SIGTRAP present  /opt/uTools/utools                           9.5M
> Sat 2023-08-12 23:02:10 CST 37476 1000 1000 SIGABRT present  /usr/bin/dde-file-manager-server             2.4M
> Sat 2023-08-12 23:02:40 CST 41535 1000 1000 SIGTRAP present  /opt/uTools/utools                           9.8M
> Sat 2023-08-12 23:02:41 CST 41187 1000 1000 SIGABRT present  /usr/bin/dde-file-manager-server             2.4M
> Sat 2023-08-12 23:22:25 CST 46126 1000 1000 SIGTRAP present  /opt/uTools/utools                           9.5M
> Sat 2023-08-12 23:22:25 CST 45772 1000 1000 SIGABRT present  /usr/bin/dde-file-manager-server             2.4M
> Sun 2023-08-13 10:28:48 CST 18111 1000 1000 SIGSEGV present  /usr/libexec/dde-cooperation/input-grabber 218.1K
> Mon 2023-08-14 09:33:17 CST 10202 1000 1000 SIGABRT present  /usr/bin/deepin-home                         5.5M
> ```
> 
> 最近的一次日志： [core.deepin-home.1000.9664a418d20848cdabaf895eda485e91.10202.zip](https://github.com/linuxdeepin/developer-center/files/12330922/core.deepin-home.1000.9664a418d20848cdabaf895eda485e91.10202.zip)

5.15.8你是从哪里装的

**Comment by belirux** [comment]
> 
不知道 我就混了一次ci 源  一直从阿尔法升过来的

**Comment by belirux** [comment]
> > > 这个终端配色完全看不清输出= =
> > > 似乎最后是 coredump 了，可以[提供下 coredump 转储文件或者 stacktrace](https://wiki.deepin.org/Coredump%E5%B7%A5%E5%85%B7%E4%BD%BF%E7%94%A8%E4%B8%8E%E6%97%A5%E5%BF%97%E5%AF%BC%E5%87%BA) 吗？
> > 
> > 
> > ```
> > ❯ deepin-home
> > Load for deepin-home 's plugin path: /usr/lib/x86_64-linux-gnu/dtkdeclarative/qml-app/libdeepin-home-preload.so
> > load translate "/usr/share/dtk5/DDeclarative/translations/dtkdeclarative_zh_CN"
> > worker: clean up saved screenshots
> > Load for deepin-home 's plugin path: /usr/lib/x86_64-linux-gnu/dtkdeclarative/qml-app/libdeepin-home-main.so
> > qt.qpa.xcb: QXcbConnection: XCB error: 5 (BadAtom), sequence: 454, resource id: 0, major code: 20 (GetProperty), minor code: 0
> > qml: font_size_t1 40
> > qml: font_size_t2 30
> > qml: font_size_t3 24
> > qml: font_size_t4 20
> > qml: font_size_t5 17
> > qml: font_size_t6 14
> > qml: font_size_t7 13
> > qml: font_size_t8 12
> > qml: font_size_t9 11
> > qml: font_size_t10 10
> > worker: is login
> > worker: get message
> > worker: get language
> > qml: current route index
> > Cannot mix incompatible Qt library (5.15.8) with this library (5.15.7)
> > [1]    10202 IOT instruction (core dumped)  deepin-home
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > ❯ coredumpctl
> > Hint: You are currently not seeing messages from other users and the system.
> >       Users in groups 'adm', 'systemd-journal' can see all messages.
> >       Pass -q to turn off this notice.
> > TIME                          PID  UID  GID SIG     COREFILE EXE                                          SIZE
> > Fri 2023-08-11 19:49:47 CST  8608 1000 1000 SIGABRT present  /usr/bin/deepin-home                         4.9M
> > Fri 2023-08-11 23:37:31 CST 15498 1000 1000 SIGABRT present  /usr/bin/deepin-home                         4.9M
> > Fri 2023-08-11 23:44:28 CST 17134 1000 1000 SIGABRT present  /usr/bin/deepin-home                         4.9M
> > Fri 2023-08-11 23:46:08 CST 17351 1000 1000 SIGABRT present  /usr/bin/deepin-home                         4.9M
> > Fri 2023-08-11 23:46:39 CST 17595 1000 1000 SIGABRT present  /usr/bin/deepin-home                         4.9M
> > Sat 2023-08-12 22:01:44 CST  4703 1000 1000 SIGTRAP present  /opt/uTools/utools                           9.5M
> > Sat 2023-08-12 22:01:45 CST  4730 1000 1000 SIGABRT present  /usr/bin/dde-file-manager-server             2.4M
> > Sat 2023-08-12 22:57:39 CST  4651 1000 1000 SIGABRT present  /usr/bin/dde-file-manager-server             2.4M
> > Sat 2023-08-12 22:57:52 CST 27447 1000 1000 SIGABRT present  /usr/bin/dde-appearance                    772.4K
> > Sat 2023-08-12 23:00:18 CST 30968 1000 1000 SIGABRT present  /usr/bin/deepin-home                         5.5M
> > Sat 2023-08-12 23:02:10 CST 37438 1000 1000 SIGTRAP present  /opt/uTools/utools                           9.5M
> > Sat 2023-08-12 23:02:10 CST 37476 1000 1000 SIGABRT present  /usr/bin/dde-file-manager-server             2.4M
> > Sat 2023-08-12 23:02:40 CST 41535 1000 1000 SIGTRAP present  /opt/uTools/utools                           9.8M
> > Sat 2023-08-12 23:02:41 CST 41187 1000 1000 SIGABRT present  /usr/bin/dde-file-manager-server             2.4M
> > Sat 2023-08-12 23:22:25 CST 46126 1000 1000 SIGTRAP present  /opt/uTools/utools                           9.5M
> > Sat 2023-08-12 23:22:25 CST 45772 1000 1000 SIGABRT present  /usr/bin/dde-file-manager-server             2.4M
> > Sun 2023-08-13 10:28:48 CST 18111 1000 1000 SIGSEGV present  /usr/libexec/dde-cooperation/input-grabber 218.1K
> > Mon 2023-08-14 09:33:17 CST 10202 1000 1000 SIGABRT present  /usr/bin/deepin-home                         5.5M
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 最近的一次日志： [core.deepin-home.1000.9664a418d20848cdabaf895eda485e91.10202.zip](https://github.com/linuxdeepin/developer-center/files/12330922/core.deepin-home.1000.9664a418d20848cdabaf895eda485e91.10202.zip)
> 
> 5.15.8你是从哪里装的

我要如何处理?

**Comment by BLumia** [comment]
不要混 CI 源。如果你打算用 CI 源的话，就只保留 CI 源，然后把所有东西都更到 CI 源的版本。

**Comment by belirux** [comment]
> 不要混 CI 源。如果你打算用 CI 源的话，就只保留 CI 源，然后把所有东西都更到 CI 源的版本。
我也就尝试一下，  那我现在要降版本，能告诉我怎么降吗

**Comment by BLumia** [comment]
可能直接重装 beta 镜像比较简单。

**Comment by belirux** [comment]
> 可能直接重装 beta 镜像比较简单。

bate2 会有iso吗，如果有 那我等等吧 目前日常使用东西有点多 /home 貌似也得格式化

**Comment by BLumia** [comment]
我这边在 CI 源无法复现打不开的问题。那我就先关闭处理吧。如果确实在内测、稳定、纯 CI 源（均不可混源）有打不开的情况，可以另开 issue。

> bate2 会有iso吗

会有。
