### ISSUE TITLE
There is no place to enter the filename to open a file in Deepin Editor.

### ISSUE THREAD

**Issue by laichiaheng** [linuxdeepin/developer-center#518]
![deepin _20180516183622](https://user-images.githubusercontent.com/9532105/40112300-24544602-5938-11e8-91bc-e9bc32e94843.png)

**Comment by rekols** [comment]
deepin-editor has not yet released, thx.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
