### ISSUE TITLE
[Deepin Integration]~[V23-Beta] atkmm, cairomm, glibmm, gtkmm intergration for V23-Beta2

### ISSUE THREAD

**Issue by UTsweetyfish** [linuxdeepin/developer-center#5185]
### package information | 软件包信息

以下四个包**应在** main 组件；之前集成(#4020)时被集成到了 community 组件。请重新集成并删除 community 组件中软件包。

包名 | 版本
--  | --
atkmm1.6 | [2.28.3-1](https://github.com/deepin-community/atkmm1.6/tree/2.28.3-1)
cairomm | [1.14.4-2](https://github.com/deepin-community/cairomm/tree/1.14.4-2)
glibmm2.4 | [2.66.5-2deepin](https://github.com/deepin-community/glibmm2.4/tree/2.66.5-2deepin)
gtkmm3.0 | [3.24.7-1](https://github.com/deepin-community/gtkmm3.0/tree/3.24.7-1)

### Package repository address | 软件包仓库地址

https://community-packages.deepin.com/beige/pool/community/a/atkmm1.6/
https://community-packages.deepin.com/beige/pool/community/c/cairomm/
https://community-packages.deepin.com/beige/pool/community/g/glibmm2.4/
https://community-packages.deepin.com/beige/pool/community/g/gtkmm3.0/

#### atkmm1.6 (2.28.3-1) unstable; urgency=medium

  [ Jeremy Bicha ]
  * New upstream release
  * debian/control.in: Bump minimum meson and atk
  * debian/control.in: Build-Depend on libxml-parser-perl
  * debian/control.in: Bump Standards-Version to 4.6.1
  * debian/control.in: Set Rules-Requires-Root: no
  * debian/libatkmm-1.6-1v5.docs: README -> README.md
  * debian/rules: Enable maintainer mode to build docs from source
  * debian/watch: Update to only track 2.28.x releases as recommended
    by upstream

  [ Samuel Thibault ]
  * control: Bump Standards-Version to 4.6.0 (no change)

  [ Debian Janitor ]
  * debian/copyright: use spaces rather than tabs to start continuation lines
  * Use secure URI in Homepage field
  * Set upstream metadata fields

#### cairomm (1.14.4-2) unstable; urgency=medium

  [ Debian Janitor ]
  * Use secure URI in Homepage field.
  * Add debian/upstream/metadata

#### glibmm2.4 (2.66.5-2deepin) unstable; urgency=medium

  [ Tianyu Chen ]
  * Switch TEST_FILE from /etc/fstab to /etc/passwd
    /etc/fstab could be empty in some circumstances.

#### gtkmm3.0 (3.24.7-1) unstable; urgency=medium

  * New upstream release
  * debian/rules: Enable maintainer mode to build docs from source
  * debian/control.in: Build-Depend on libxml-parser-perl
  * Bump Standards-Version to 4.6.1

### test suggestion | 测试建议

(无)

### Sphere of influence | 影响范围

无影响

**Comment by Zeno-sole** [comment]
已处理
