### ISSUE TITLE
There is no difference with these 2 themes in Deepin Editor.

### ISSUE THREAD

**Issue by laichiaheng** [linuxdeepin/developer-center#519]
![deepin-screen-recorder_deepin-editor_20180516183953](https://user-images.githubusercontent.com/9532105/40112484-a9f50134-5938-11e8-80f5-43fbb4574855.gif)

**Comment by aksh1618** [comment]
Try saving the file with a suitable extension: `cfile.c`. This will enable syntax highlighting and you'll see the difference.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
