### ISSUE TITLE
The Qt style of DDE isn't correct.

### ISSUE THREAD

**Issue by laichiaheng** [linuxdeepin/developer-center#520]
Shouldn't it be gtk2 by default?

Wrong
--------------------------------------------------------------------
shutdown menu:
(The font size is really small, although I have set the font size to 18)
![no gtk2](https://user-images.githubusercontent.com/9532105/40112836-ee4ba3fa-5939-11e8-9259-d2581116b254.png)
qbittorrent:
![deepin _20180516184840](https://user-images.githubusercontent.com/9532105/40112840-f2eb9014-5939-11e8-81fb-d68da79dc8be.png)
virtualbox:
![deepin-screen-recorder_desktop_20180516185354](https://user-images.githubusercontent.com/9532105/40113018-8cb0f126-593a-11e8-8276-43048bfa9ec7.gif)

Now I have to edit the /etc/environment to make it work:
---------------------------------------------------------------------------------------
![deepin _deepin-terminal_20180516190840](https://user-images.githubusercontent.com/9532105/40113672-d1a806a0-593c-11e8-9203-06b6f156c080.png)

Correct
-----------
![deepin _20180516190949](https://user-images.githubusercontent.com/9532105/40113675-d5a0825a-593c-11e8-9cbd-d97d9229f580.png)
![deepin _20180516191118](https://user-images.githubusercontent.com/9532105/40113708-f00d06ae-593c-11e8-98f0-36b2203872f6.png)

**Comment by felixonmars** [comment]
The real problem here is that XDG_CURRENT_DESKTOP was not set correctly.

@hualet I still think it's better to use the simpler deepin-session script as Exec for xsession, instead of the current lightdm session-wrapper approach.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
