### ISSUE TITLE
I can't drag a file to Deepin Terminal anymore.

### ISSUE THREAD

**Issue by laichiaheng** [linuxdeepin/developer-center#522]
![deepin-screen-recorder_desktop_20180516190209](https://user-images.githubusercontent.com/9532105/40113325-acddbcc6-593b-11e8-8b99-adfab2b43e37.gif)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
