### ISSUE TITLE
【deepin_V23_beta】【一般】【正常】【内测反馈】【系统】【HP EliteBook 845】HP EliteBook 845笔记本未作系统适配

### ISSUE THREAD

**Issue by kobe337** [linuxdeepin/developer-center#5223]
### SUMMARY | 问题概要

HP EliteBook 845笔记本未作系统适配，目前未适配的问题情况为：
1、显示器分辨率不可调
2、无法调整屏幕亮度
3、待机后唤醒不成功

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
内核版本：Linux deepin-PC 6.1.32-amd64-desktop-hwe #23.01.00.19 SMP PREEMPT_DYNAMIC Wed Aug  2 17:06:10 CST 2023 x86_64 GNU/Linux
```

### STEPS TO REPRODUCE | 复现步骤

1. 通过控制中心调整分辨率
2. 调整屏幕亮度
3. 电源设置待机后唤醒

### OBSERVED RESULT | 观察到的结果

与研发同事沟通进行确认，HP EliteBook 845笔记本未作适配，目前未适配的问题情况为：
1、显示器分辨率不可调
2、无法调整屏幕亮度
3、待机后唤醒不成功

### EXPECTED RESULT | 期望的结果

HP EliteBook 845笔记本完成适配，能够：
1. 通过控制中心调整分辨率成功，功能正常
2. 调整屏幕亮度成功，功能正常
3. 电源设置待机后唤醒成功，功能正常

### ADDITIONAL INFORMATION | 额外补充

[问题机型信息]
-------------------------------------------------
设备:                  HP HP EliteBook 845 14 inch G10 Notebook PC (84G22PC#AB2) Notebook 
操作系统:                Deepin 23 Community Linux version 6.2.16-amd64-desktop-hwe (xzl@xzl-PC) (gcc (Deepin 11.2.0-deepin2+rb2) 11.2.0, GNU ld (GNU Binutils for Deepin) 2.38) #1 SMP PREEMPT_DYNAMIC Thu Aug 17 00:17:24 CST 2023
处理器:                 AMD Ryzen 7 PRO 7840HS w/ Radeon 780M Graphics (八核 / 十六逻辑处理器)
主板:                  8B6E
内存:                  16GB(HMCG78AGBSA095N  5600 MT/s)/16GB(HMCG78AGBSA095N  5600 MT/s)
显示适配器:               Phoenix
音频适配器:               Rembrandt Radeon High Definition Audio Controller/Family 17h/19h HD Audio Controller
存储设备:                SK hynix PC801 HFS001TEJ9X101N (1.00 TB)
蓝牙:                  Wireless_Device
鼠标:                  ELAN07A8:00 04F3:31EC Mouse (ELAN07A8:00 04F3:31EC Mouse)/ELAN07A8:00 04F3:31EC Touchpad (ELAN07A8:00 04F3:31EC Touchpad)
键盘:                  AT Translated Set 2 keyboard (AT Translated Set 2 keyboard)
显示设备:                Generic Monitor()
图像设备:                HP 5MP Camera (Chicony Electronics HP 5MP Camera)
其他设备:                usb 0x00f0

**Comment by babyfengfjx** [comment]
@xzl01  请帮忙处理~

**Comment by kobe337** [comment]
如泽龙所说，目前内核6.4.5时按问题单操作显示正常。暂关闭，后续通过冒烟测试指南覆盖。
