### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【发散测试】【DDE】【控制中心】deepin ID中的文案"帐户"为错误文案

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#5229]
### SUMMARY | 问题概要

deepin ID中的文案"帐户"为错误文案

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
dde-control-center:6.0.22
```

### PRE-REQUIREMENT | 预置条件

系统更新到最新内测版本

### STEPS TO REPRODUCE | 复现步骤

1.打开控制中心
2.登陆deepin ID
3.观察所有"帐户"文案展示

### OBSERVED RESULT | 观察到的结果

deepin ID中的文案"帐户"为错误文案
![75201071-081a-414f-bffb-2f8565ea6236](https://github.com/linuxdeepin/developer-center/assets/96415804/938963f9-6f74-4a9c-b7a7-f672e7919c59)

### EXPECTED RESULT | 期望的结果

deepin ID中的文案应该为"账户"

**Comment by babyfengfjx** [comment]
@Decodetalkers  此issue帮忙优先处理，次周推送内测更新，上周只修复了控制中心的文字内容，因此模块上周才交付过来，此问题未得到及时处理。

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0516镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过


![image](https://github.com/linuxdeepin/developer-center/assets/62528742/8bf757df-760e-41da-a69e-0fcb808c0c89)
