### ISSUE TITLE
The default font of Deepin Terminal becomes so ugly.

### ISSUE THREAD

**Issue by laichiaheng** [linuxdeepin/developer-center#523]
![deepin _deepin-terminal_20180516190351](https://user-images.githubusercontent.com/9532105/40113406-f337c72a-593b-11e8-9d20-2dc12dfd9f17.png)

Only Ubuntu Mono is OK:
![deepin _deepin-terminal_20180516190539](https://user-images.githubusercontent.com/9532105/40113489-319754d6-593c-11e8-9544-4e53d580ce17.png)

**Comment by BLumia** [comment]
Cannot reproduce it here, feel free to let us know if that still happens.
