### ISSUE TITLE
【deepin_V23_beta2】【一般】【正常】【内测反馈】【系统】 BCM4360 无线驱动没有适配

### ISSUE THREAD

**Issue by songyeyi** [linuxdeepin/developer-center#5233]
### SUMMARY | 问题概要

v23 beta 没有 BCM4360 无线驱动。
硬件：mackbook air

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
v23 beta 没有 BCM4360 无线驱动。
硬件：mackbook air
```

### PRE-REQUIREMENT | 预置条件

v23 beta 没有 BCM4360 无线驱动。
硬件：mackbook air

### STEPS TO REPRODUCE | 复现步骤

v23 beta 没有 BCM4360 无线驱动。
硬件：mackbook air

### OBSERVED RESULT | 观察到的结果

v23 beta 没有 BCM4360 无线驱动。
硬件：mackbook air

### EXPECTED RESULT | 期望的结果

v23 beta 没有 BCM4360 无线驱动。
硬件：mackbook air

**Comment by xzl01** [comment]
https://wiki.debian.org/bcm43xx  似乎可以由内核提供

**Comment by kobe337** [comment]
@songyeyi 请问有使用过高版本的内核试试吗？比如已经推送的6.4.x的内核，是否能正常使用呢

**Comment by kobe337** [comment]
@songyeyi 请提供邮箱地址，目前已编译对应内核

**Comment by songyeyi** [comment]
已用最新内核6.4.7试过，有蓝牙，没有wifi驱动。



在 2023-08-21 11:42:42，"Star_IMPL" ***@***.***> 写道：

@songyeyi 请提供邮箱地址，目前已编译对应内核

**Comment by kobe337** [comment]
如需要此内核，请发送信息至wubo@uniontech.com ，我将回复以附件信息发送给你哈

**Comment by songyeyi** [comment]
我使用你邮箱发我的内核文件安装后，还是没有wifi驱动。




在 2023-08-21 15:38:27，"Star_IMPL" ***@***.***> 写道：

***@***.*** ，我将回复以附件信息发送给你哈

**Comment by xzl01** [comment]
确定下你的网卡型号 是否为BCM94360cs2 或者 BCM943602CS

**Comment by songyeyi** [comment]
在最新内核6.4.7下，执行 sudo apt install broadcom-sta-dkms wifi可以正常使用了，同时摄像头也可以使用 ，真是一个惊喜
