### ISSUE TITLE
Deepin Control Center is blank.

### ISSUE THREAD

**Issue by laichiaheng** [linuxdeepin/developer-center#524]
![deepin _20180516191629](https://user-images.githubusercontent.com/9532105/40113962-ba011a9a-593d-11e8-826a-78862ebb6417.png)

## It will appear in few seconds:
![deepin _20180516191738](https://user-images.githubusercontent.com/9532105/40113984-cf6158d2-593d-11e8-8d33-b96c37c52b45.png)

**Comment by denisoster** [comment]
I have the same bug.

**Comment by hualet** [comment]
@sbwtw

**Comment by sbwtw** [comment]
What's the version of dde-control-center? in some recent commit, we implements a plugins delay-load feature. but it's not stable and not tested yet.

**Comment by denisoster** [comment]
@sbwtw 
ArchLinux
`deepin-control-center 4.4.4.2-1`

**Comment by denisoster** [comment]
No more problems

**Comment by felixonmars** [comment]
Should have been fixed a while ago. Closing.
