### ISSUE TITLE
【deepin_V23_beta2】【一般】【紧急】【内测反馈】【deepin ID】高分屏缩放下deepin id登录框左上角图标展示模糊不清晰

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#5244]
### SUMMARY | 问题概要

必现问题

https://pms.uniontech.com/bug-view-212453.html

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/20230516
内核版本： Linux test-PC 5.18.17-amd64-desktop-community-hwe #20.01.00.02 SMP PREEMPT_DYNAMIC Thu Nov 10 14:18:31 CST 2022 x86_64 GNU/Linux

控制中心:6.0.20

内测反馈：https://cooperation.uniontech.com/app/6f20cf83-ef8a-4067-bac9-b05c6d6bbcb6/648bfccc0a1f50226a98dbc6/648bfccc0a1f50226a98dbca/row/d589d2c5-25f9-468e-9807-d37f5544d0df
```

### PRE-REQUIREMENT | 预置条件

修改缩放至1.25及以上

### STEPS TO REPRODUCE | 复现步骤

点击登录deepin id按钮, 观察弹出的登录框左上角deepin id图标的展示样式

### OBSERVED RESULT | 观察到的结果

deepin id图标样式展示很模糊不清晰

![image](https://github.com/linuxdeepin/developer-center/assets/62528742/578973cf-5905-4184-8b89-53c28e44fc63)

### EXPECTED RESULT | 期望的结果

deepin id图标样式展示清晰不模糊

**Comment by babyfengfjx** [comment]
@Decodetalkers  请看原单的子项目修复内容，帮忙同步提交PR，并提交集成。
![Uploading image.png…]()

**Comment by Decodetalkers** [comment]
这个弹窗是sync-daemon的部分，这部分没有交界，如果他们修复了，那重新测试下，这个我处理不了，可能要和项目组联系 @babyfengfjx

**Comment by babyfengfjx** [comment]
@xuqi27837288  群内沟通是已经修复了，请在最新集成版本回归验证，并关联上是哪一笔集成。

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0516镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
【截图录屏】：

![企业微信截图_16934504662073](https://github.com/linuxdeepin/developer-center/assets/62528742/b437002a-4e24-4d92-b060-02f42133b317)
