### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【发散测试】【DDE】【控制中心】关闭电脑协同，点击连接设备下拉框，光标会自动跳到 自动调节色温

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#5245]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
控制中心 6.0.22
```

### PRE-REQUIREMENT | 预置条件

1.安装镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
2.加入内测
3.更新系统至最新版本

### STEPS TO REPRODUCE | 复现步骤

1. 关闭电脑协同 - 点击连接设备 下拉按钮 - 等待5秒

### OBSERVED RESULT | 观察到的结果

1. 光标跳到 自动调节色温
![录屏_选择区域_20230821145406](https://github.com/linuxdeepin/developer-center/assets/96416089/4d25d288-1810-4598-9a50-9164c9223f63)

### EXPECTED RESULT | 期望的结果

1. 光标不会自动跳到其他按钮

**Comment by babyfengfjx** [comment]
@BLumia  请帮忙分析优化~

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0516镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
【截图录屏】：


https://github.com/linuxdeepin/developer-center/assets/62528742/5b2a3e0d-20ae-43fc-af94-1b68452ebd99
