### ISSUE TITLE
【deepin_V23_beta2】【一般】【正常】【发散测试】【系统】HP EliteBook 845双屏复制模式下，主屏幕存在异常显示问题

### ISSUE THREAD

**Issue by kobe337** [linuxdeepin/developer-center#5246]
### SUMMARY | 问题概要

HP EliteBook 845双屏复制模式下存在异常显示问题，主屏幕显示不完整，屏幕右边显示为黑屏，屏幕左边为带有阴影的组合异常显示

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
内核版本：Linux deepin23-PC 6.4.7
```

### STEPS TO REPRODUCE | 复现步骤

1. 接入4K显示器，双屏设置复制模式显示，在x11和wayland模式下查看屏幕显示

### OBSERVED RESULT | 观察到的结果

1. HP EliteBook 845双屏复制模式下存在异常显示问题，x11和wayland下查看桌面与锁屏界面，主屏幕显示不完整，屏幕右边显示为黑屏，屏幕左边为带有阴影的组合异常显示，请看下图：
![1eec38110af2e79f91ea3aa305b99dcd](https://github.com/linuxdeepin/developer-center/assets/17869922/d3945271-6978-4a9b-a24b-17c1bd3a42bc)
![image](https://github.com/linuxdeepin/developer-center/assets/17869922/799b5839-b7c7-48f7-b678-db666aa0ebcb)

### EXPECTED RESULT | 期望的结果

 HP EliteBook 845双屏模式下正常显示，双屏功能正常

### ADDITIONAL INFORMATION | 额外补充

硬件为

[问题机型信息]
-------------------------------------------------
设备:                  HP HP EliteBook 845 14 inch G10 Notebook PC (84G22PC#AB2) Notebook 
操作系统:                Deepin 23 Community Linux version 6.2.16-amd64-desktop-hwe (xzl@xzl-PC) (gcc (Deepin 11.2.0-deepin2+rb2) 11.2.0, GNU ld (GNU Binutils for Deepin) 2.38) #1 SMP PREEMPT_DYNAMIC Thu Aug 17 00:17:24 CST 2023
处理器:                 AMD Ryzen 7 PRO 7840HS w/ Radeon 780M Graphics (八核 / 十六逻辑处理器)
主板:                  8B6E
内存:                  16GB(HMCG78AGBSA095N  5600 MT/s)/16GB(HMCG78AGBSA095N  5600 MT/s)
显示适配器:               Phoenix
音频适配器:               Rembrandt Radeon High Definition Audio Controller/Family 17h/19h HD Audio Controller
存储设备:                SK hynix PC801 HFS001TEJ9X101N (1.00 TB)
蓝牙:                  Wireless_Device
鼠标:                  ELAN07A8:00 04F3:31EC Mouse (ELAN07A8:00 04F3:31EC Mouse)/ELAN07A8:00 04F3:31EC Touchpad (ELAN07A8:00 04F3:31EC Touchpad)
键盘:                  AT Translated Set 2 keyboard (AT Translated Set 2 keyboard)
显示设备:                Generic Monitor()
图像设备:                HP 5MP Camera (Chicony Electronics HP 5MP Camera)
其他设备:                usb 0x00f0

![8c1971e4d71a7f9d530cfbb0f3ebd87d](https://github.com/linuxdeepin/developer-center/assets/17869922/65321fd3-e1a7-44aa-a9ab-b8f24277d35d)

**Comment by babyfengfjx** [comment]
@xzl01  请帮忙处理~

**Comment by xzl01** [comment]
目前问题：在wayland以及X11下工作都不正常，尝试ubunut

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240112/deepin-23-beige-beta3-amd64-20240112-130549.iso 
内核：Linux deepin0112-PC 6.1.32-amd64-desktop-hwe #23.01.00.20 SMP PREEMPT_DYNAMIC Thu Jan 11 18:45:10 CST 2024 x86_64 GNU/Linux

【结论】：
beta3集成镜像0112未复现，暂无严重问题及影响,覆盖复制、扩展、单个屏幕切换均没有问题。走未复现流程。

**Comment by kobe337** [comment]
deepinv23 RC版本回归验证通过。覆盖双屏复制模式校验通过。
![ddafec07846805e67cf2ad86bb7d899f](https://github.com/linuxdeepin/developer-center/assets/17869922/73552f05-65cc-4431-a682-4d0f96f5d772)
