### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【发散测试】【DDE】【启动器】】从 v23 alpha 升级到 v23 beta后，启动器里面找不到 截图录屏

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#5248]
### SUMMARY | 问题概要

本单为 Pms： https://pms.uniontech.com/bug-view-200397.html   转化跟踪

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
安装镜像：https://cdimage.uniontech.com/community/releases/23-Alpha/deepin-desktop-community-23-Alpha-amd64.iso
```

### PRE-REQUIREMENT | 预置条件

1. 安装镜像：https://cdimage.uniontech.com/community/releases/23-Alpha/deepin-desktop-community-23-Alpha-amd64.iso
2. 加入内测更新

### STEPS TO REPRODUCE | 复现步骤

打开启动器 查找截图录屏  

### OBSERVED RESULT | 观察到的结果

启动器中没有截图录屏
![file-read-658077](https://github.com/linuxdeepin/developer-center/assets/96416089/c367082a-d3e5-483e-87a3-311f039d1701)

### EXPECTED RESULT | 期望的结果

启动器中存在 截图录屏

**Comment by babyfengfjx** [comment]
@kegechen   此 issue可能需要等AM重构完成后，集成后再打镜像查看结果。

**Comment by babyfengfjx** [comment]
@luodeepin  可以使用最新仓库和镜像确认是否仍旧存在该问题，如果存在则修复优先级提升为1级。

**Comment by kegechen** [comment]
截图录屏也是玲珑应用了，应该是**玲珑应用都无法显示** @luodeepin 确认一下是不是如此

**Comment by kegechen** [comment]
虽然是老的launcher, 不过 AM 的逻辑可能需要改改，截图录屏中有个字段 
`NotShowIn=DeepinTablet` 这个字段导致截图无法显示  
@ComixHe

**Comment by kegechen** [comment]
launchpad 和新版本 AM 中回归

**Comment by luodeepin** [comment]
验证通过
![5248](https://github.com/linuxdeepin/developer-center/assets/96416089/c2307388-b54f-4a56-8eb5-d1f381fc5f01)
