### ISSUE TITLE
Most of the fonts in Deepin Terminal are missing.

### ISSUE THREAD

**Issue by laichiaheng** [linuxdeepin/developer-center#525]
![deepin _deepin-terminal_20180516211340](https://user-images.githubusercontent.com/9532105/40119072-3e7fc522-594e-11e8-88b7-ad0b93756422.png)
![deepin _20180516211356](https://user-images.githubusercontent.com/9532105/40119080-431808a6-594e-11e8-8589-e0692025d626.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
