### ISSUE TITLE
termimal fail

### ISSUE THREAD

**Issue by denisoster** [linuxdeepin/developer-center#527]
I'm run `ngrok http 300`
![image](https://user-images.githubusercontent.com/15886355/40270112-539c308c-5b90-11e8-9d5d-f96baefbaf1c.png)
Fix please this.

**Comment by hualet** [comment]
What if you try another terminal emulator?

**Comment by denisoster** [comment]
![image](https://user-images.githubusercontent.com/15886355/40319493-0180ef34-5d31-11e8-94bc-eb0f1e4b06e6.png)

**Comment by felixonmars** [comment]
Please test if another vte3-based terminal works, like gnome-terminal or xfce4-terminal, etc.

**Comment by denisoster** [comment]
![image](https://user-images.githubusercontent.com/15886355/40379855-08508f52-5e00-11e8-8467-eaa14c3f0bb7.png)

**Comment by felixonmars** [comment]
So it has the same problem? I guess the best place to report is vte3 upstream then...
