### ISSUE TITLE
【deepin_V23_beta2】【一般】【紧急】【集成测试】【deepin ID】deepin id模块图标样式展示不正确

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#5274]
### SUMMARY | 问题概要

必现问题

https://pms.uniontech.com/bug-view-212325.html

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/20230516
内核版本： Linux test-PC 5.18.17-amd64-desktop-community-hwe #20.01.00.02 SMP PREEMPT_DYNAMIC Thu Nov 10 14:18:31 CST 2022 x86_64 GNU/Linux

控制中心:6.0.20
```

### PRE-REQUIREMENT | 预置条件

进入控制中心

### STEPS TO REPRODUCE | 复现步骤

看deepin id的图标展示样式

### OBSERVED RESULT | 观察到的结果

不应该包含uos相关的图标样式

![image](https://github.com/linuxdeepin/developer-center/assets/62528742/c30995f3-61f6-44b4-98bb-63164ec32de3)

### EXPECTED RESULT | 期望的结果

应重新设计图标样式或参考v20图标样式

**Comment by babyfengfjx** [comment]
@kegechen  这个问题可以协调下设计提供资源，做一下替换。

**Comment by Decodetalkers** [comment]
替换了，还没有打tag

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0516镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：6.0.23版本上回归测试通过
【截图录屏】：

![image](https://github.com/linuxdeepin/developer-center/assets/62528742/59c67f2f-08df-4134-b1ce-43ad102020ff)
