### ISSUE TITLE
Deepin V23 Beta更新报错

### ISSUE THREAD

**Issue by Lichenkass** [linuxdeepin/developer-center#5276]
### SUMMARY | 问题概要

终端使用sudo apt update更新报错
![截图_deepin-terminal_20230823141244](https://github.com/linuxdeepin/developer-center/assets/88034509/fe44cb15-0919-4f31-97f9-afeaddf7f307)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin V23 Beta
```

### STEPS TO REPRODUCE | 复现步骤

Deepin V23 终端使用sudo apt update

**Comment by Decodetalkers** [comment]
在同步仓库，不要着急

**Comment by myml** [comment]
请问现在还存在问题吗？

**Comment by myml** [comment]
因为长时间没有回应，这个Issues先关闭了
