### ISSUE TITLE
Dark text in search bar of deepin-file-manager in dark mode

### ISSUE THREAD

**Issue by ghost** [linuxdeepin/developer-center#528]
Hi,
In the new dark theme of deepin-file-manager, the text in the search bar is also dark, making it difficult to see. Please turn it to a lighter color, so that it's clearly visible upon a dark background (just like the sidebar, etc).
![github](https://user-images.githubusercontent.com/36928406/40292207-72d913ea-5ce7-11e8-9989-13caca1b1921.png)

**Comment by denisoster** [comment]
![image](https://user-images.githubusercontent.com/15886355/40319453-e4d2c8c6-5d30-11e8-903d-bbe47faf5e44.png)

**Comment by hualet** [comment]
@zccrs

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
