### ISSUE TITLE
Not working remote access

### ISSUE THREAD

**Issue by denisoster** [linuxdeepin/developer-center#529]
zssh - installed
![image](https://user-images.githubusercontent.com/15886355/40356941-55f28d42-5dc3-11e8-84cf-2e69afe30b64.png)

**Comment by rekols** [comment]
зачем использовать zzsh?

**Comment by denisoster** [comment]
@rekols на скрине видно что к нему пыталось обратиться
![image](https://user-images.githubusercontent.com/15886355/40358811-33f298f8-5dc9-11e8-9ccd-ac48553dcf1c.png)

**Comment by rekols** [comment]
@denisoster 
Я вижу~
что ваше соединение ssh не включено...

**Comment by denisoster** [comment]
@rekols как его включить?

**Comment by rekols** [comment]
Сначала попробуйте подключиться к серверу?

Вот так:   ssh xxxxxx -p xxx

**Comment by denisoster** [comment]
@rekols таким образом подключение проходит

**Comment by rekols** [comment]
Теперь все в порядке?

**Comment by rekols** [comment]
Теперь все в порядке  )

**Comment by denisoster** [comment]
@rekols нет. все еще ошибка

**Comment by rekols** [comment]
вы русский? мне нравится русский язык.   хаха !!!

**Comment by denisoster** [comment]
@rekols да я знаю русский. хорошо что вам нравится язык. Но проблема осталась с remote access.

**Comment by rekols** [comment]
Мне также нравится русский, Может не решить вашу проблему.  ):

**Comment by denisoster** [comment]
@rekols BUG CLOSED
