### ISSUE TITLE
Release notification for manjaro-deepin

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/developer-center#53]
<a href="https://github.com/oberon2007"><img src="https://avatars.githubusercontent.com/u/11800714?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @oberon2007**
_Friday Oct 30, 2015 at 19:17 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/98_

---

@fasheng, @mmetak, @felixonmars I would like to say thank you again for the great effort and the excellent work you have done sofar on making deepin available on Arch and archbased systems.
I am happy to let you all know that I have now managed to put together a really nice version of Deepin based on Manjaro and produced a live environment / install media. If you would like to have a look, here it is: https://sourceforge.net/projects/manjaro-deepin/
The only bug I am facing still is the automatic theme updating when you change wallpapers, icons or xcursor-theme a few times in a row. Then you have to re-log for the changes to apply.
Apart from that everything seems to work really well and I think it shows that the newer more arch-grounded packages are quite a boost in performance. To be able to customize look&feel a bit I had to actually rebuild the majority of the packages because of the interdependencies... ;) In any case I was very keen on keeping the original design and wherever a manjaro-logo appears there is also a deepin-one (plymouth-theme, lightdm-deepin-greeter) next to it. The System Information and Copyright in the Control Center I have left untouched. So I hope that will be ok for everyone like that.
At the moment this ISO is not more than an experiment, but if the development continues like that I will be more than happy to officially anounce a full featured manjaro-deepin release.
best wishes
oberon.

**Comment by oberon2007** [comment]
**Manjaro-Deepin 16.06** has just been [released](https://forum.manjaro.org/t/manjaro-deepin-16-06/)
Thank you all for your impressive work!
I think Deepin has improved incredibly in the last 6 months and become really reliable and stable :+1: 
AWESOME!! :rocket: :laughing:

**Comment by sonald** [comment]
I believe you'll see more updates and new features in the near future :) :smile:

**Comment by oberon2007** [comment]
I'm walking carefully :stuck_out_tongue_winking_eye:

**Comment by hualet** [comment]
And more bugfixes from @sonald . Anyway,  congratulations!!! @oberon2007

**Comment by oberon2007** [comment]
I'm happy to announce that Manjaro-Deepin 16.08, featuring Deepin Desktop 15.3, has just been released :tada:
https://manjaro.org/2016/09/05/manjaro-deepin-16-08/
As always, thank you everybody for your awesome work on this special and beautiful DE and your always kind cooperation! Deepin keeps improving and impressing me. Keep it up!! :+1:

**Comment by fasheng** [comment]
Thanks! Really great job :+1:

**Comment by oberon2007** [comment]
Hm. Unfortunately I had to decide to take the ISOs down temporarily just now, because it seems we have a seriouy issue with network connections... https://github.com/linuxdeepin/dde-dock/issues/19
I hope this can be fixed, soon.
