### ISSUE TITLE
Deepin 桌面更新後桌面全黑，只有桌面的圖示和右鍵選單還有控制中心能顯示

### ISSUE THREAD

**Issue by laichiaheng** [linuxdeepin/developer-center#531]
![deepin _20180523181926](https://user-images.githubusercontent.com/9532105/40418806-ebef1d18-5eb5-11e8-9bc3-2a96696f836e.png)

**Comment by denisoster** [comment]
The same problem.

**Comment by denisoster** [comment]
@felixonmars my version 3.2.12-1

**Comment by denisoster** [comment]
![](https://i.imgur.com/zWy4NlX.jpg)

**Comment by felixonmars** [comment]
There is: https://www.archlinux.org/packages/community/any/deepin-desktop-schemas/

Your mirror may be slow on updates. As a workaround you can download the package from above page.

**Comment by denisoster** [comment]
Thanks
