### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【集成测试】【deepin ID】最新版本6.0.23控制中心下，deepin ID模块没有图片展示

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#5326]
### SUMMARY | 问题概要

最新版本6.0.23控制中心下，deepin ID模块没有图片展示
问题单关联集成:#5319

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
dde-control-center:6.0.23
```

### PRE-REQUIREMENT | 预置条件

控制中心升级到到最新版本
仓库:deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-375/testing/ ./

### STEPS TO REPRODUCE | 复现步骤

1.打开控制中心主界面,查看deepin ID模块

### OBSERVED RESULT | 观察到的结果

1.最新版本6.0.23控制中心下，deepin ID模块没有图片展示
![截图_选择区域_20230828164603](https://github.com/linuxdeepin/developer-center/assets/96415804/6c9815ef-5ed5-4d73-abe3-2d8cdfcc9de4)

### EXPECTED RESULT | 期望的结果

1.deepin id模块有图片展示

**Comment by babyfengfjx** [comment]
@kegechen  请优先安排优化。

**Comment by xuqi27837288** [comment]
6.0.23版本回归测试通过

![image](https://github.com/linuxdeepin/developer-center/assets/62528742/f7142c3c-f0ee-4f75-80e8-2c6ab6b21b30)
