### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【集成测试】【deepin ID】控制中心首页，deepin ID的详细描述中，没有以顿号 、进行分隔

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#5327]
### SUMMARY | 问题概要

本问题对应的集成编号：https://github.com/linuxdeepin/developer-center/issues/5319
本问题单对应需求：https://github.com/linuxdeepin/developer-center/issues/4628

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
控制中心 6.0.23
```

### STEPS TO REPRODUCE | 复现步骤

1. 打开控制中心 ， 查看首页描述信息

### OBSERVED RESULT | 观察到的结果

1. deepin ID的描述没有以顿号、进行分隔
![截图_选择区域_20230829095321](https://github.com/linuxdeepin/developer-center/assets/96416089/cb04859f-458b-4809-ae9d-eae4f6292a29)

### EXPECTED RESULT | 期望的结果

1. 控制中心首页的描述信息以顿号、进行分隔

### ADDITIONAL INFORMATION | 额外补充

参考需求：https://github.com/linuxdeepin/developer-center/issues/4628

**Comment by babyfengfjx** [comment]
@Decodetalkers  请参考需求进行优化，需要讨论的部分请及时与产品、测试沟通。

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0906镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
【截图录屏】：

![截图_选择区域_20230906191746](https://github.com/linuxdeepin/developer-center/assets/62528742/00124c8f-c265-4584-9cc8-e929ddd6fa80)
