### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【集成测试】【deepin ID】最新版本6.0.23控制中心下，deepin ID登陆界面显示为Deepin ID

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#5329]
### SUMMARY | 问题概要

最新版本6.0.23控制中心下，deepin ID登陆界面显示为Deepin ID
问题单关联集成:#5319

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
dde-control-center:6.0.23
deepin-deepinid-client:7.0.1
deepin-deepinid-plugin:1.1.0
```

### PRE-REQUIREMENT | 预置条件

控制中心升级到到最新版本
仓库:deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-375/testing/ ./

### STEPS TO REPRODUCE | 复现步骤

1.打开控制中心-deepin ID
2.点击登录,弹出deepin ID登陆界面
3.观察登录Deepin ID展示

### OBSERVED RESULT | 观察到的结果

1.最新版本6.0.23控制中心下，deepin ID登陆界面显示为Deepin ID
![截图_选择区域_20230828171111](https://github.com/linuxdeepin/developer-center/assets/96415804/e62328cf-6f2a-418f-abd2-7adcaad6bda2)

### EXPECTED RESULT | 期望的结果

1.应该与其他地方保持一致,显示为小写deepin ,deepin ID

**Comment by Decodetalkers** [comment]
弹出的部分并没有交接给我们，它是deepin-sync-daemon的部分。可能要联系deepin-sync-daemon的负责人

**Comment by babyfengfjx** [comment]
@xuqi27837288  请找deepin ID那边确认一下.

**Comment by babyfengfjx** [comment]
@vivianxf   这块可能需要deepin ID子项目那边处理，先确认后可转到PMS上跟踪。
