### ISSUE TITLE
Menu bug

### ISSUE THREAD

**Issue by denisoster** [linuxdeepin/developer-center#533]
Russian language.
Please, fix it:
![deepinscreenshot_ - _20180527150211](https://user-images.githubusercontent.com/15886355/40585660-6bc92f04-61bf-11e8-9476-b093a3030021.png)

**Comment by felixonmars** [comment]
![2018-11-04-110638-46a109](https://user-images.githubusercontent.com/1006477/47959544-c8128680-e021-11e8-93eb-5655d1216513.png)
Looks like fixed in the latest version. Are you still getting it?

**Comment by rekols** [comment]
Эта проблема исправлена, подождите до следующего обновления  :)

**Comment by denisoster** [comment]
CLOSED
