### ISSUE TITLE
Login/Lookscreen bug

### ISSUE THREAD

**Issue by denisoster** [linuxdeepin/developer-center#534]
Please, fix it:
![deepinscreenshot_ - _20180527150433](https://user-images.githubusercontent.com/15886355/40585703-db729778-61bf-11e8-91eb-ba695ef335a1.png)

**Comment by felixonmars** [comment]
Same problem here. @zccrs Any idea?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
