### ISSUE TITLE
【deepin_V23_beta2】【提示】【有空】【论坛反馈】【DDE】【控制中心】使用Ltd Integrated IR Camera型号摄像头时，录入人脸数据时出现异常

### ISSUE THREAD

**Issue by SuperEffie** [linuxdeepin/developer-center#5341]
### SUMMARY | 问题概要

【论坛链接】：https://bbs.deepin.org/zh/post/261459
【问题备注】：特定型号摄像头出现异常

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
版本信息：dde-control-center:6.0.23
```

### STEPS TO REPRODUCE | 复现步骤

打开控制中心-生物认证-添加人脸，观察界面显示

### OBSERVED RESULT | 观察到的结果

录入人脸数据异常
![20230828164615918_image](https://github.com/linuxdeepin/developer-center/assets/58986464/60004866-4a45-42a0-92a3-eb00ea080d6e)

### EXPECTED RESULT | 期望的结果

正常录入人脸

**Comment by babyfengfjx** [comment]
@BLumia  请安排分析优化~

**Comment by kobe337** [comment]
【环境】：
镜像：Deepin OS-23-20240613025136-1_x86_64
内核：Linux deepinrc2-PC 6.6.25-amd64-desktop-hwe #23.01.00.25 SMP PREEMPT_DYNAMIC Wed Apr 10 21:20:25 CST 2024 x86_64 GNU/Linux


【结论】：
测试通过，暂无严重问题及影响，deepin v23 RC2镜像验证通过，人脸识别功能正常，验证设备为联想T480s。
![xjzc](https://github.com/linuxdeepin/developer-center/assets/17869922/d2060527-427d-40b3-8f30-5156f45865d3)
