### ISSUE TITLE
Lockscreen volum button bug

### ISSUE THREAD

**Issue by denisoster** [linuxdeepin/developer-center#535]
Button doesn`t works.
Please, fix it:
![deepinscreenshot_ - _20180527150949](https://user-images.githubusercontent.com/15886355/40585725-1cbb1782-61c0-11e8-88d0-bc6ad1443d7b.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
