### ISSUE TITLE
【deepin_V23_beta2】【一般】【紧急】【集成测试】【deepin ID】开启deepin Cloud同步按钮，系统设置中网络选项图标丢失未展示

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#5351]
### SUMMARY | 问题概要

必现问题：该问题已与 @Decodetalkers 对齐复现

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/20230516
内核版本： Linux test-PC 5.18.17-amd64-desktop-community-hwe #20.01.00.02 SMP PREEMPT_DYNAMIC Thu Nov 10 14:18:31 CST 2022 x86_64 GNU/Linux

控制中心:6.0.23
```

### PRE-REQUIREMENT | 预置条件

进入deepin ID中开启deepin Cloud同步按钮

### STEPS TO REPRODUCE | 复现步骤

点击系统设置菜单观察网络图标的样式展示效果

### OBSERVED RESULT | 观察到的结果

网络图标未展示

![截图_选择区域_20230829164347](https://github.com/linuxdeepin/developer-center/assets/62528742/8b835404-9145-4e24-b216-8bf5ade56fb2)

### EXPECTED RESULT | 期望的结果

网络图标正常展示

**Comment by babyfengfjx** [comment]
@Decodetalkers  请帮忙优化~

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0516镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过

https://github.com/linuxdeepin/developer-center/assets/62528742/4fe0edc4-b68e-4773-917c-454023d252d8
