### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【发散测试】【deepin ID】多次修改用户昵称进行校验时，建议优化提示信息弹框只弹出一次

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#5352]
### SUMMARY | 问题概要

必现问题

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/20230516
内核版本： Linux test-PC 5.18.17-amd64-desktop-community-hwe #20.01.00.02 SMP PREEMPT_DYNAMIC Thu Nov 10 14:18:31 CST 2022 x86_64 GNU/Linux

控制中心:6.0.23
```

### PRE-REQUIREMENT | 预置条件

当天第二次修改用户昵称

### STEPS TO REPRODUCE | 复现步骤

修改后点击确认按钮观察校验时弹出的提示信息对话框的展示效果

### OBSERVED RESULT | 观察到的结果

弹出二次提示信息对话框

![截图_选择区域_20230829165320](https://github.com/linuxdeepin/developer-center/assets/62528742/d7f6942c-c608-4176-a1e9-9e817ca5e925)

### EXPECTED RESULT | 期望的结果

仅弹出一次提示信息的对话框

**Comment by babyfengfjx** [comment]
@Decodetalkers  此问题不急于修复，后期等老梅这边整体需求调整确定后再看，看是否支持在当前客户端界面进行用户信息修改，如果统一跳转到web界面则可能不存在该问题。

**Comment by Decodetalkers** [comment]
消息是这里弹的，可以修。这个行为是有问题

**Comment by xuqi27837288** [comment]
https://github.com/linuxdeepin/developer-center/assets/62528742/ebd8f7ec-fe73-41c9-b416-c51eac849e7b
