### ISSUE TITLE
白盒功能的生物认证相关 Action 名称修复

### ISSUE THREAD

**Issue by chenchongbiao** [linuxdeepin/developer-center#5354]
### package information | 软件包信息

包名 | 版本
--  | --
deepin-keyring-whitebox | 1.0.3.2

### Package repository address | 软件包仓库地址

    deb  [trusted=yes] https://aptly.uniontech.com/pkg/beige-v2/release-candidate/a2V5cmluZy13aGl0ZTIwMjMtMDgtMDIgMTE6MjI6NTI/  unstable main

### changelog | 更新信息

- fix: fix action name

### test suggestion | 测试建议

使用内测源更新后，另外添加白盒的软件源直接升级。

测试下生物认证（人脸、虹膜、指纹）。之前修改的 Action 名称错误。

### Sphere of influence | 影响范围

开启生物认证后弹密钥。

**Comment by chenchongbiao** [comment]
相关issue：
- https://github.com/linuxdeepin/developer-center/issues/4146
- https://github.com/linuxdeepin/developer-center/issues/3099

**Comment by chenchongbiao** [comment]
@luodeepin

**Comment by babyfengfjx** [comment]
@luodeepin  请开展集成验证。

**Comment by luodeepin** [comment]
验证通过

从来没有使用过生物认证的，首次录入后，重启登录时没有弹框
之前有录入过生物认证的，升级后，需要重新录入新的才在重启登录后没有弹窗
