### ISSUE TITLE
【deepin_V23_beta2】【一般】【正常】【内测反馈】【系统】HP 845 g10核显异常，性能低于标准频率

### ISSUE THREAD

**Issue by kobe337** [linuxdeepin/developer-center#5357]
### SUMMARY | 问题概要

HP 845 g10核显异常，性能低于标准频率（基于ubuntu 23.04进行验证）

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
内核版本：Linux deepin-PC 6.1.11-amd64-desktop-hwe #23.01.00.14 SMP PREEMPT_DYNAMIC Fri May 12 14:47:29 CST 2023 x86_64 GNU/Linux
```

### PRE-REQUIREMENT | 预置条件

v23版本最新内测更新

### STEPS TO REPRODUCE | 复现步骤

1. 基于v23环境与ubuntu 23.04版本环境进行glxgear性能测试对比,vbland_mode=0 glxgears

### OBSERVED RESULT | 观察到的结果

HP 845 g10核显异常，性能低于标准频率。

v23环境与ubuntu环境23.04版本，5秒性能帧数对比：
v23 glxgear用户跑分平均800+，ubuntu验证glxgear跑分平均2000+。

用户反馈的跑分平均800+：
![image](https://github.com/linuxdeepin/developer-center/assets/17869922/50107af3-0675-40b9-8ef6-978d24ae799e)
基于ubuntu环境23.04的跑分平均2000+：
![image](https://github.com/linuxdeepin/developer-center/assets/17869922/ba130db7-cbbc-4093-912b-1bf4ccf45782)

### EXPECTED RESULT | 期望的结果

HP 845 g10核显性能不低于标准频率。（基于ubuntu进行对比）

### ADDITIONAL INFORMATION | 额外补充

CPU信息：AMD 锐龙™ 7 PRO 7840U

关联链接：https://cooperation.uniontech.com/public/record/64ee9d8ccc11a7bd3d32c4a6 记录：RDNA3 架构的核显驱动异常

**Comment by babyfengfjx** [comment]
@xzl01  请帮忙分析，看是否能够优化~

**Comment by xzl01** [comment]
可能用户使用省电模式跑分，在我的7840hs上无法复现此情况

**Comment by xzl01** [comment]
amd的用户态驱动工作不正常，持续关注此问题

**Comment by zed7th** [comment]
补充一下在我的设备上的测试结果，我的设备是铭凡 UM780PRO，系统是最新的 V23 Beta 内测通道，内核使用 6.4.7-hwe；Ubuntu 使用 Ventory 引导 23.04 的镜像，然后进入试用模式，分别进行了 vblank_mode=0 glxgears 和 glmark2 测试：

**Comment by xzl01** [comment]
目前可复现此问题：在deepin23中识别AMDGPU型号不正常：pci.ids需要更新，目前内测已经提交集成。
在deepin23中的mesa工作不正常，正在积极寻找原因

**Comment by xzl01** [comment]
排查发现 AMD的用户态驱动部分依赖llvm15提供的新特性，导致目前用户态驱动异常，故需要升级llvm工具链。等待下一步工作完成

**Comment by zed7th** [comment]
> 排查发现 AMD的用户态驱动部分依赖llvm15提供的新特性，导致目前用户态驱动异常，故需要升级llvm工具链。等待下一步工作完成

这个问题等官方发版解决要比较久的时间，我可以自己编译 mesa 解决吗？或者说有没有测试用的包先尝鲜一下

**Comment by Zeno-sole** [comment]
> > 排查发现 AMD的用户态驱动部分依赖llvm15提供的新特性，导致目前用户态驱动异常，故需要升级llvm工具链。等待下一步工作完成
> 
> 这个问题等官方发版解决要比较久的时间，我可以自己编译 mesa 解决吗？或者说有没有测试用的包先尝鲜一下

https://ci.deepin.com/repo/deepin/deepin-ports/deb/mesa-23.1.6/   这里有编译好的版本  你可以试一下

**Comment by zed7th** [comment]
> > > 排查发现 AMD的用户态驱动部分依赖llvm15提供的新特性，导致目前用户态驱动异常，故需要升级llvm工具链。等待下一步工作完成
> > 
> > 
> > 这个问题等官方发版解决要比较久的时间，我可以自己编译 mesa 解决吗？或者说有没有测试用的包先尝鲜一下
> 
> https://ci.deepin.com/repo/deepin/deepin-ports/deb/mesa-23.1.6/ 这里有编译好的版本 你可以试一下

缺少了 llvm15 相关的依赖包，请问能补充一下 llvm15 相关的包吗？

**Comment by zed7th** [comment]
> > > > > 排查发现 AMD的用户态驱动部分依赖llvm15提供的新特性，导致目前用户态驱动异常，故需要升级llvm工具链。等待下一步工作完成
> > > > 
> > > > 
> > > > 这个问题等官方发版解决要比较久的时间，我可以自己编译 mesa 解决吗？或者说有没有测试用的包先尝鲜一下
> > > 
> > > 
> > > https://ci.deepin.com/repo/deepin/deepin-ports/deb/mesa-23.1.6/ 这里有编译好的版本 你可以试一下
> > 
> > 
> > 缺少了 llvm15 相关的依赖包，请问能补充一下 llvm15 相关的包吗？
> 
> 应该是缺了 libllvm15，已上传

辛苦了，libclc-15 libclang-cpp15 libllvmspirvlib15 也缺失

**Comment by xzl01** [comment]
已经完成修复 可以关闭issue单

**Comment by kobe337** [comment]
已通过提供对应依赖包解决了核显性能问题，此单关闭
