### ISSUE TITLE
No icons, notifacation bugs.

### ISSUE THREAD

**Issue by denisoster** [linuxdeepin/developer-center#536]
Notifacation bugs.
No icon app, example: slack,spotify, chromium.
Please fix it:
![deepinscreenshot_ - _20180527152044](https://user-images.githubusercontent.com/15886355/40586260-c3a2c952-61c8-11e8-86fe-bd6cf8feb69a.png)

**Comment by denisoster** [comment]
![deepinscreenshot_ - _20180530174618](https://user-images.githubusercontent.com/15886355/40781021-0e81d838-64e3-11e8-8681-c910d3226ad6.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
