### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【发散测试】【deepin ID】账号或密码输入错误一次后提示账号密码错误已达今日上限，无法通过正常账号密码进行登录

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#5383]
### SUMMARY | 问题概要

偶现问题

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/20230516
内核版本： Linux test-PC 5.18.17-amd64-desktop-community-hwe #20.01.00.02 SMP PREEMPT_DYNAMIC Thu Nov 10 14:18:31 CST 2022 x86_64 GNU/Linux

控制中心:6.0.23
```

### PRE-REQUIREMENT | 预置条件

进入deepin ID模块进行登录操作

### STEPS TO REPRODUCE | 复现步骤

输入错误的账号密码后，再输入正确的账号密码观察是否可以正常登录

### OBSERVED RESULT | 观察到的结果

账号或密码错误已达今日上限，请重置密码再试

![截图_选择区域_20230831154957](https://github.com/linuxdeepin/developer-center/assets/62528742/88185349-09b2-4384-bf75-cbc103abd26a)

### EXPECTED RESULT | 期望的结果

多次（5次左右）输入账号密码错误后再限制登录

**Comment by babyfengfjx** [comment]
@Decodetalkers  请帮忙优化~

**Comment by Decodetalkers** [comment]
这个是sync daemon的部分，不是插件的部分

**Comment by kegechen** [comment]
回归一下，貌似是ok的 @xuqi27837288

**Comment by xuqi27837288** [comment]
考虑安全场景该问题暂不做修复,问题单关闭处理
