### ISSUE TITLE
更新集成的NextTrace

### ISSUE THREAD

**Issue by tsosunchia** [linuxdeepin/developer-center#5392]
### SUMMARY | 问题概要

您好，我是NextTrace开发者，首先非常感谢DEEPIN能将NextTrace集成。
但我看到您加入进来的是NextTrace的v1.1.6版本，不幸的是此版本是最后一个使用我们旧版API的版本，
旧版本API将在一年内停止运行，届时v1.1.6将不能使用，
希望您能考虑将集成的NextTrace版本升级到最新的v1.2.0.1，谢谢。

NextTrace关于停止维护旧版本API的公告：https://github.com/nxtrace/Ntrace-core/issues/159
NextTrace的v1.2.0.1代码：https://github.com/nxtrace/Ntrace-V1/tree/v1.2.0.1

**Comment by YukariChiba** [comment]
感谢您的告知，我们已对此创建了任务（ https://github.com/deepin-community/sig-deepin-sysdev-team/issues/527 ），并将尽快完成版本升级。

**Comment by tsosunchia** [comment]
> 感谢您的告知，我们已对此创建了任务（ [deepin-community/sig-deepin-sysdev-team#527](https://github.com/deepin-community/sig-deepin-sysdev-team/issues/527) ），并将尽快完成版本升级。

麻烦您了，感谢

**Comment by YukariChiba** [comment]
已经完成更新并推送至待发布仓库。
