### ISSUE TITLE
[archlinux] GSettings signal blocked in gccgo under archlinux

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/developer-center#54]
<a href="https://github.com/fasheng"><img src="https://avatars.githubusercontent.com/u/3049011?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @fasheng**
_Thursday Dec 17, 2015 at 01:46 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/185_

----

This will caused many setting issues in control center and dock.

Looks [go-gir-generator](https://github.com/linuxdeepin/go-gir-generator) is ready now, let's use it and will fix such issues.

https://github.com/fasheng/arch-deepin/issues/227
https://github.com/fasheng/arch-deepin/issues/177
https://github.com/fasheng/arch-deepin/issues/120

**Comment by fasheng** [comment]
Our patch was merged to gccgo now and let's wait for the new release of gcc :)
https://go-review.googlesource.com/#/c/18883/

**Comment by snyh** [comment]
The patch has been merged to gcc at 2016/02/24  https://github.com/gcc-mirror/gcc/commit/8aa3d53d57a81604661df063c05425ecce30c257

**Comment by fasheng** [comment]
Finally, we solved it :)
