### ISSUE TITLE
Notification bug

### ISSUE THREAD

**Issue by denisoster** [linuxdeepin/developer-center#540]
Please, fix it:
![deepinscreenshot_ - _20180527165449](https://user-images.githubusercontent.com/15886355/40587363-e2195db6-61d6-11e8-9a5a-8977be74cd8d.png)

**Comment by felixonmars** [comment]
I cannot reproduce this one. Is it broken for all your notifications or just a specific application?

**Comment by denisoster** [comment]
@felixonmars 
Slack and Telegram
![deepinscreenshot_ - _20180528092720](https://user-images.githubusercontent.com/15886355/40600689-16af0eb6-625b-11e8-859c-0921bf1dd8b1.png)
![deepinscreenshot_ - _20180528093930](https://user-images.githubusercontent.com/15886355/40600690-16cf1cf6-625b-11e8-900f-d633ce4ea9d0.png)

**Comment by felixonmars** [comment]
Telegram desktop does not use deepin-notifications in my case. 
![2018-05-28-144537-e65206](https://user-images.githubusercontent.com/1006477/40600984-e69924f2-6285-11e8-998c-bb270340c5a6.png)

**Comment by denisoster** [comment]
![image](https://user-images.githubusercontent.com/15886355/40601035-23855fea-625c-11e8-9869-e73c01e2f056.png)

**Comment by felixonmars** [comment]
![2018-05-28-145150-49df4c](https://user-images.githubusercontent.com/1006477/40601177-b099f75e-6286-11e8-991b-541292fff8f6.png)
There is no such option here...

**Comment by denisoster** [comment]
@felixonmars 
Im using [repo](https://www.archlinux.org/packages/community/x86_64/telegram-desktop/)
![image](https://user-images.githubusercontent.com/15886355/40601291-3641a7a0-625d-11e8-9a21-64d675668d41.png)

Download slack. I send invite on thit email felixonmars@archlinux.org

**Comment by denisoster** [comment]
@felixonmars check bug, please

**Comment by denisoster** [comment]
@felixonmars Do you see what I write in slack?

**Comment by felixonmars** [comment]
Please try deepin-notifications 3.3.1 which resolves the problem for me.

**Comment by denisoster** [comment]
My current version deepin-notifications-3.3.1-1
![image](https://user-images.githubusercontent.com/15886355/40718249-0b6b2d00-6418-11e8-99c0-213308fa6b80.png)

**Comment by denisoster** [comment]
@felixonmars issues closed
