### ISSUE TITLE
【deepin_V23-alpha2】【一般】【有空】【论坛反馈】【DDE】【控制中心】用户头像中 立体风格与平面风格的头像显示错误

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#5411]
### SUMMARY | 问题概要

1. 论坛反馈链接：https://bbs.deepin.org/zh/post/261711
2. 当前平面风格中的头像为 立体风格，当前立体风格的图像为 平面风格

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
1. 控制中心 6.0.23
```

### PRE-REQUIREMENT | 预置条件

1. 加入内测，更新至最新版本

### STEPS TO REPRODUCE | 复现步骤

1. 打开控制中心 - 用户 点击用户头像
2. 查看 头像显示情况

### OBSERVED RESULT | 观察到的结果

2. 用户头像中 立体风格与平面风格的头像显示错误
![截图_选择区域_20230904133824](https://github.com/linuxdeepin/developer-center/assets/96416089/17e0cae8-72b5-427a-ac54-7c742ae514d3)

### EXPECTED RESULT | 期望的结果

2. 平面风格中的头像为 平面风格，立体风格的图像为 立体风格

**Comment by babyfengfjx** [comment]
@luodeepin   请更新 #5407  回归验证。

**Comment by luodeepin** [comment]
验证通过
dde-account-faces 1.0.15 
![image](https://github.com/linuxdeepin/developer-center/assets/96416089/63c5ca95-1f16-4c68-b09d-157930730b24)
