### ISSUE TITLE
Indian Keyboard layout changing automatically

### ISSUE THREAD

**Issue by veerendra-nath** [linuxdeepin/developer-center#542]
If you select the ```English(India, with rupee)``` keyboard , after booting its working fine 
But if the system wake up from the sleep or you enter the system from lock mode, keyboard layout changing to ```Hindi (India)``` even its still sowing  ```English(India, with rupee)``` in option but typing in Hindi ...

**Comment by felixonmars** [comment]
@electricface Does dde-daemon apply input device settings correctly in this case? I have a similar problem when I plug-in my USB keyboard after boot, the repeat-rate settings are not taking effect but the control center still shows the correct value.

**Comment by veerendra-nath** [comment]
keyboard is always connected , when you lock the system and unlocking it then its changing to another language , still it showing as settings i applied

**Comment by vincentporte** [comment]
Hi, I encounter the same problem on my DeepIn/Antergos Distro. After booting, the fr-bepo keyboard layout works fine, but on locked screen, keyboard layout is changed to fr-latin even it's showing fr-bepo.
Using laptop without external keyboard.

**Comment by sdlins** [comment]
I have the same problem as onboard keyboard as wireless one. The only "workaround" I found is set `super` + `space` to switch to english than switch back to pt-br. I have to do this after each unsuspend or after disconnect/connect the wireless keyboard.

Is there any log, information or anything else we could provide to help to solve this problem?

**Comment by Kush0708** [comment]
it still have the same issue whether u use external keyboard or atached(laptops) .....u can go to control panel >keyboard layout  >type 5 it will suggest  u the english  euro 5 layout select it and then edit the layout there as english macintosh (as i tried this one )and deselect  the indian (english with rupee)...
 deepin do also have issues with the themes as it changes automaticaly when the system awake after hiberntion or sleep or whether u login after locking it .
 i could not change the themes as it doesnot respond .

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
