### ISSUE TITLE
deepin-installer 6.0.27版本集成

### ISSUE THREAD

**Issue by ArchieMeng** [linuxdeepin/developer-center#5427]
### package information | 软件包信息

deepin-installer 6.0.27

### Package repository address | 软件包仓库地址

https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20230905/deepin-23-beige-beta2-amd64-20230905-095314.iso

### changelog | 更新信息

  * 修复v23环境下的DGUI编译错误
    现在需要使用DGUI命名空间
  * Fix EFI missing issue on custom install
    使用MBR类型的Ventoy进行V23自定义安装时，由于将Ventoy的EFI分区识别为了可用的EFI分区，删除所有本机硬盘分区后，新增分区不会自动添加新的EFI分区。
  * Fix error "QCommandLineParser was not declared in this scope"
  * Fix black screen on switching TTY
  * lvm分区增加不能编辑提示
  * "创建帐户"文案改为"创建用户"
  * set DI_GRUB_RESOLUTION_CONFIG to auto
  * some code cleanup
  * set GRUB_DISTRIBUTOR defaults to Deepin 23

### test suggestion | 测试建议

1. V23下尝试编译
2. 在UEFI启动模式下，尝试各种安装器下会识别出EFI分区的安装环境，看自定义安装创建新分区是否会自动创建EFI分区并顺利执行下一步。（原出问题环境为MBR分区的Ventoy安装盘。参考链接: https://pms.uniontech.com/bug-view-213903.html ）
（修复检测是基于分区类型信息以及分区文件系统信息的。）
4. 进入安装器界面后，尝试ctrl+alt+F2-F7切换TTY。
5. 检查本机硬盘已有LVM分区时，高级安装中是否会对其进行提示。（参考：https://pms.uniontech.com/bug-view-187413.html）
6. 安装成功后的创建帐户界面，现在标题应该为创建用户。可能的话，检查下是否还有使用帐户文案的地方。

### Sphere of influence | 影响范围

自定义安装，高级安装的LVM，EFI相关功能。
"帐户"文案变化。
安装器Live环境下的主机名，发行版名等名称。

### ADDITIONAL INFORMATION | 额外补充

无

**Comment by babyfengfjx** [comment]
@SuperEffie   此镜像只作为安装器的功能验证测试，不作为系统测试的镜像，请开展安装器相关功能验证。支持的所有安装方式需要覆盖，包括加密，初始化备份，多系统并存等。

**Comment by SuperEffie** [comment]
【验证结论】：测试通过，请走下一步流程
【备注信息】：验证bug:[#213903]( https://pms.uniontech.com/bug-view-213903.html) 、[#187413](https://pms.uniontech.com/bug-view-187413.html)通过，已备注验证结论。安装界面正常切换TTY，安装界面显示为”创建用户“，符合预期。
【遗留bug】: https://github.com/linuxdeepin/developer-center/issues/5436
