### ISSUE TITLE
How to change DPI?

### ISSUE THREAD

**Issue by denisoster** [linuxdeepin/developer-center#543]

**Comment by felixonmars** [comment]
Their is a "Display scaling" slider in the "Display" part of the control center.

**Comment by denisoster** [comment]
@felixonmars sceen please

**Comment by felixonmars** [comment]
![2018-06-21-230555-109e19](https://user-images.githubusercontent.com/1006477/41727761-b5e3825a-75a7-11e8-9703-24a0af6b947f.png)

**Comment by denisoster** [comment]
No, no this display scaling. I need input number DPI, examples 170, 150.

**Comment by aiamuzz** [comment]
> No, no this display scaling. I need input number DPI, examples 170, 150.
@denisoster  ... to my knowledge DPI is a hardware specification ... one can't increase or decrease the hardware dots per inch through a software modification.


> Can you elaborate on the use case? I assume the product team wants to understand the difference.
I am guessing  ... @denisoster ... just got curious about the whole DPI thing from the 15.6 upgrade feature description ...

**Comment by hualet** [comment]
@aiamuzz is correct.
