### ISSUE TITLE
[Deepin Integration]~[V23-Beta2]  zeno@linuxdeepin/deepin-music 玲珑应用

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#5431]
### package information | 软件包信息

【应用名】音乐
【包名】deepin-music
【版本】7.0.3

### Package repository address | 软件包仓库地址

http://10.0.36.228:9001/repos/develop-snipe/refs/heads/linglong/org.deepin.music/7.0.3/

### test suggestion | 测试建议

【回归bug】
https://pms.uniontech.com/bug-view-215039.html

### Sphere of influence | 影响范围

音乐播放

**Comment by babyfengfjx** [comment]
@xuqi27837288  请开展集成回归验证。

**Comment by xuqi27837288** [comment]
【环境】：
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【结论】：
测试通过，暂无严重问题及影响
