### ISSUE TITLE
[Deepin Integration]~[V23-Beta2] zeno@linuxdeepin/deepin-album 玲珑应用

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#5432]
### package information | 软件包信息

【应用名】相册
【包名】deepin-album
【版本】6.0.3.6

### Package repository address | 软件包仓库地址

http://10.0.36.228:9001/repos/develop-snipe/refs/heads/linglong/org.deepin.album/6.0.3.6/

### test suggestion | 测试建议

【回归bug】
https://pms.uniontech.com/bug-view-209283.html
https://pms.uniontech.com/bug-view-185733.html
https://pms.uniontech.com/bug-view-161821.html
https://pms.uniontech.com/bug-view-192999.html
https://pms.uniontech.com/bug-view-170987.html

### Sphere of influence | 影响范围

相册

**Comment by babyfengfjx** [comment]
@xuqi27837288 请开展集成回归验证。

**Comment by xuqi27837288** [comment]
https://pms.uniontech.com/bug-view-217933.html

【环境】：
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【结论】：
测试不通过，安装新版本相册，挂载smb服务后相册闪退，建议后续优化修复后再提交集成
这次集成中的问题单因为闪退的问题阻塞暂时无法验证
