### ISSUE TITLE
deepin-app-store 8.0.0.0007 版本集成

### ISSUE THREAD

**Issue by zty199** [linuxdeepin/developer-center#5448]
### package information | 软件包信息

包名 | 版本
--- | ---
deepin-app-store | 8.0.0.0007-1
deepin-home-appstore-daemon | 8.0.0.0004-1

### Package repository address | 软件包仓库地址

deb  [trusted=yes] https://aptly.uniontech.com/pkg/nonfree-beige-v2/release-candidate/56S-5Yy654mIVjIz5bqU55So5ZWG5bqXMjAyMzAxMDYyMDIzLTAxLTA2IDE3OjIyOjQw/  unstable non-free

### changelog | 更新信息

* 修复 [PMS-182477](https://pms.uniontech.com/bug-view-182477.html) os-version EditionName 变动导致商店登录、匹配模板、应用检查更新异常

### test suggestion | 测试建议

1. 修改 `/etc/os-version` 后，启动客户端，观察页面加载、登录、应用检查更新功能是否受影响

### Sphere of influence | 影响范围

修改网络请求中请求头 platform 字段获取方式：
不再使用 `DSysInfo::uosEditionName(const QLocale &locale)` 接口读取 `/etc/os-version` 文件中 `EditionName` 字段值，改为使用 `DSysInfo::uosEditionType()` 获取系统版本枚举类型，根据已知类型直接赋值对应字符串，避免受影响

### ADDITIONAL INFORMATION | 额外补充

无

**Comment by babyfengfjx** [comment]
@vivianxf  请尽快完成相关验证，确保中英文状态下，系统信息显示正确，且商店所有功能正常使用，文管基本功能不受影响，并适当开展扩展验证。

**Comment by vivianxf** [comment]
验证通过.请及时汇总合入:

1.仓库添加成功,包成功安装,版本正确
2.结合集成#5439 https://pms.uniontech.com/bug-view-182477.html PMS bug 验证通过.英文环境系统信息展示正确
3.文件管理器基本功能使用正常
4.商店可以成功访问,正常下载安装/打开应用,账号登陆/退出,基本功能正常
5.系统基本功能正常

综上所述,本次集成通过.
