### ISSUE TITLE
[dde-file-manager] Home partition not shown in Internal Disk

### ISSUE THREAD

**Issue by aksh1618** [linuxdeepin/developer-center#545]
I'm using DDE in Arch linux. I have separate `/` and `/home` partitions. However, only `/` partition is shown in the *Computer* section of the File manager under *Internal Disk* as *System Disk*. I can get to `/home` from the *Home* section. It would be really nice if the home partition is also shown under *Internal Disk* .

**Comment by zccrs** [comment]
Thank you, We will fix it on version 1.8

**Comment by igorbarkowsky** [comment]
@zccrs is it fixed? It will be useful, to see current home partition free space, for example (now i need to open "disk info" from context menu on Home section every time).

**Comment by BLumia** [comment]
Currently it is by design https://github.com/linuxdeepin/developer-center/issues/992 , maybe we should reconsider about this? @wangjia12

**Comment by aksh1618** [comment]
I would like to second that having `/home` shown in internal disk would be very helpful, and should in fact be shown for completion sake, if nothing else, as it is part of the `internal disk`.

My main takeaway from this would be easily accessible disk space status, like @igorbarkowsky

**Comment by igorbarkowsky** [comment]
> Currently it is by design

Why not to reconsider that internal disk is all partitions of physical disk where current system installed except /media partitions (i.e. removable devices).
So Internal disk will show for user next partitions (for example, system installed on sda):
- /
- /home
- /tmp (if somebody use tmp on dedicated partition)
- windows partition installed on same disk
- other partitions from sda

And External disk will show (example)
- usb-stick
- external hdd-drive
- cdroms

But i see problem. Currently, all partitions from sda mounting to /media. I don't realize how to filtering they.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
