### ISSUE TITLE
多网卡网络环境，关机后再开机IP地址混乱。

### ISSUE THREAD

**Issue by 15035290756** [linuxdeepin/developer-center#5452]
### SUMMARY | 问题概要

我在KVM虚拟机中安装的Deepin20.9版本有三块网卡，通过/etc/network/interfaces.d新建网络配置文件为三块网卡配置了IP地址。三块网络配置文件内容如下：
root@VNCHost:/etc/network/interfaces.d# cat ifcfg-enp1s0 
auto enp1s0
iface enp1s0 inet static
address 10.8.7.7
netmask 255.255.255.0
gateway 10.8.7.254
dns-nameservers 10.8.7.254
root@VNCHost:/etc/network/interfaces.d# cat ifcfg-enp2s0 
auto enp2s0
iface enp2s0 inet static
address 10.8.8.7
netmask 255.255.255.0
#gateway 10.8.7.254
#dns-nameservers 10.8.7.254
root@VNCHost:/etc/network/interfaces.d# cat ifcfg-enp3s0 
auto enp3s0
iface enp3s0 inet static
address 10.8.9.7
netmask 255.255.255.0
#gateway 10.8.7.254
#dns-nameservers 10.8.7.254
配置完成后一切正常，但关机后再开机发现10.8.7.0段地址上的服务无法访问，检查服务正常。检查网络配置文件正常。但执行ip add后发现，10.8.7.0网段地址在enp3s0上，而10.8.9.0网段地址在enp1s0上。以下是ip add执行后的信息。
root@VNCHost:/etc/network/interfaces.d# ip add
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:49:d7:3e brd ff:ff:ff:ff:ff:ff
    inet 10.8.9.7/24 brd 10.8.9.255 scope global noprefixroute enp1s0
       valid_lft forever preferred_lft forever
    inet6 fe80::403c:7f25:df2a:d236/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:7c:0b:5f brd ff:ff:ff:ff:ff:ff
    inet 10.8.8.7/24 brd 10.8.8.255 scope global noprefixroute enp2s0
       valid_lft forever preferred_lft forever
    inet6 fe80::3372:6f54:e963:605b/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
4: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:57:5f:77 brd ff:ff:ff:ff:ff:ff
    inet 10.8.7.7/24 brd 10.8.7.255 scope global noprefixroute enp3s0
       valid_lft forever preferred_lft forever
    inet6 fe80::76a6:3e12:aec4:73dd/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
我认为这是一个BUG，系统为什么不能正确加载网卡配置文件。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
虚拟机
deepin:20.9

宿主机
debian 11.7
libvirt 7.0.0
使用的 API: QEMU 7.0.0
运行管理程序: QEMU 5.2.0
```

### STEPS TO REPRODUCE | 复现步骤

1.为主机添加多块网卡。
2.通过/etc/network/interfaces.d新增网卡配置文件，并配置IP地址。
3.将系统关机。
4.再次开机。

**Comment by babyfengfjx** [comment]
@15035290756  非常感谢反馈。
- 看是否能帮忙把  【2.通过/etc/network/interfaces.d新增网卡配置文件，并配置IP地址。】  这一步新增网卡配置的过程操作详细描述一下。

- 因V20版本对这一块不会再做维护，此现象我们会在后续的V23版本中尝试复现和实验，如果存在相关问题会在V23做进一步跟进，请知悉。

**Comment by babyfengfjx** [comment]
@SuperEffie  目前我们没有多块网卡的设备，后续如果有条件可以尝试一下看看。

**Comment by 15035290756** [comment]
> @15035290756 非常感谢反馈。
> 
> * 看是否能帮忙把  【2.通过/etc/network/interfaces.d新增网卡配置文件，并配置IP地址。】  这一步新增网卡配置的过程操作详细描述一下。
> * 因V20版本对这一块不会再做维护，此现象我们会在后续的V23版本中尝试复现和实验，如果存在相关问题会在V23做进一步跟进，请知悉。

**Comment by 15035290756** [comment]
> @15035290756 非常感谢反馈。
> 
> * 看是否能帮忙把  【2.通过/etc/network/interfaces.d新增网卡配置文件，并配置IP地址。】  这一步新增网卡配置的过程操作详细描述一下。
> * 因V20版本对这一块不会再做维护，此现象我们会在后续的V23版本中尝试复现和实验，如果存在相关问题会在V23做进一步跟进，请知悉。

新增网卡的配置，即通过vim新建网卡配置文件，并写入如下内容。
vim ifcfg-enp1s0
auto enp1s0
iface enp1s0 inet static
address 10.8.7.7
netmask 255.255.255.0
gateway 10.8.7.254
dns-nameservers 10.8.7.254

vim ifcfg-enp2s0
auto enp2s0
iface enp2s0 inet static
address 10.8.8.7
netmask 255.255.255.0
#gateway 10.8.7.254
#dns-nameservers 10.8.7.254

vim ifcfg-enp3s0
auto enp3s0
iface enp3s0 inet static
address 10.8.9.7
netmask 255.255.255.0
#gateway 10.8.7.254
#dns-nameservers 10.8.7.254

现在我发现这个问题似乎是networkmanager引起的，当我将其删除后，再通过网卡配置文件配置网络后，就没有出现IP地址混乱的现象。

**Comment by ComixHe** [comment]
https://askubuntu.com/questions/1786/what-is-the-difference-between-network-manager-and-ifconfig-ifup-etc

**Comment by SuperEffie** [comment]
感谢您的反馈，针对这个问题我们请较了研发同学 @ComixHe，回复说issue中的配置方法与networkmanager不兼容导致异常。并且不建议移除或禁用networkmanager，可能会导致dde的异常。
![image](https://github.com/linuxdeepin/developer-center/assets/58986464/3efaaabf-5633-4523-8a55-3fa2b06fa63d)
若是您还有问题，欢迎在该issue下备注留言，我们会关注并答复您~

**Comment by SuperEffie** [comment]
再次感谢反馈，由于长时间未收到您的回复，我们先将issue关闭。若后续您还有疑问，可以申请重新打开这个issue~
