### ISSUE TITLE
[Deepin Integration]~[V23-Beta2] starhcq@linuxdeepin/deepin-album 玲珑应用

### ISSUE THREAD

**Issue by starhcq** [linuxdeepin/developer-center#5464]
### package information | 软件包信息

【应用名】相册
【包名】deepin-album
【版本】6.0.4

### Package repository address | 软件包仓库地址

http://10.0.36.228:9001/repos/develop-snipe/refs/heads/linglong/org.deepin.album/6.0.4/

### changelog | 更新信息

1. linuxdeepin/deepin-album#169
2. linuxdeepin/deepin-album#170
3. linuxdeepin/deepin-album#171
4. linuxdeepin/deepin-album#173
5. linuxdeepin/deepin-album#176
6. linuxdeepin/deepin-album#177
7. linuxdeepin/deepin-album#178
8. linuxdeepin/deepin-album#179
9. linuxdeepin/deepin-album#180
10. linuxdeepin/deepin-album#181

### test suggestion | 测试建议

【回归bug】
https://github.com/linuxdeepin/developer-center/issues/4393
https://pms.uniontech.com/bug-view-218077.html
https://pms.uniontech.com/bug-view-217933.html
https://pms.uniontech.com/bug-view-209283.html
https://pms.uniontech.com/bug-view-185733.html

### Sphere of influence | 影响范围

相册

**Comment by babyfengfjx** [comment]
@xuqi27837288  请开展集成验证。

**Comment by xuqi27837288** [comment]
【环境】：
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【结论】：
测试通过，暂无严重问题及影响
