### ISSUE TITLE
Multitasking view with dual monitor

### ISSUE THREAD

**Issue by AresAndy** [linuxdeepin/developer-center#547]
Hello,

While running Deepin DE under Manjaro linux with a dual monitor, going in multitask view it displays only windows in one screen (presumibly screen Nr 1)

**Comment by sonald** [comment]
Yes, that's by design

**Comment by AresAndy** [comment]
That's by design? Then how does one control windows placed in monitor other than the primary one?
Sounds like an inconsistency to me. If that is by design, then drop support for more than one monitor altogether.

**Comment by sonald** [comment]
dual monitor is complete supported. all windows from all monitors will be displayed.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
