### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【预发布测试】【深度之家】英文环境下,深度之家名称"Deepin Home"展示 不正确

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#5481]
### SUMMARY | 问题概要

英文环境下,深度之家名称"Deepin Home"展示 不正确

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230906/deepin-23-beige-beta2-amd64-20230906-140445.iso
深度之家:1.3.2
```

### PRE-REQUIREMENT | 预置条件

1.系统为英文环境

### STEPS TO REPRODUCE | 复现步骤

1.英文环境在桌面查看深度之家名称展示

### OBSERVED RESULT | 观察到的结果

1.名称为"Deepin Home"
![Screenshot_select-area_20230906165709](https://github.com/linuxdeepin/developer-center/assets/96415804/e68f4edd-5e68-4b5f-a73b-f96c3fa80f02)

### EXPECTED RESULT | 期望的结果

1.名称应该为"deepin home"

**Comment by babyfengfjx** [comment]
@vivianxf   可以参考这篇wiki：[品牌专有名词指导方针](https://wiki.deepin.org/)   作为与其他名词一起使用组合成的名词，可以使用大写。

**Comment by vivianxf** [comment]
参考品牌专有名词指导方针,深度之家英文范围正确应该为Deepin Home,原设计无问题,此issue作废处理
![image](https://github.com/linuxdeepin/developer-center/assets/96415804/003fd38e-8fe1-4126-b431-e7ab9d707337)
