### ISSUE TITLE
Deepin Flatpak apps listed on Flathub ... or ... at least permission to do so by a third party maintainer ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#549]
Hi,

Don't you think its time deepin started publishing all their Flatpak apps to flathub ?
I think its about time the deepin flatpak apps were made available to other linux distro users as well.

thank.s

**Comment by aiamuzz** [comment]
No response ... been more than 2 months ...

**At least is one allowed to maintain flatpak version of all Deepin apps to be hosted on Flathub ???**

If yes then i can put in a word on the flathub team if anybody would package it separately for Flathub ...

**Comment by hualet** [comment]
@aiamuzz Sorry for the neglection didn't intend to, but just too busy with other stuff. 
I've answered someone in the community that we'll do the job, but now I'm sure that we don't have the time or manpower make it happen if you or other guys are interested, please feel free to do that and we provide any help that we can :)

**Comment by aiamuzz** [comment]
> The issue with Deepin apps is that they need a proper runtime or at least a baseApp. As I don't follow the Deepin dev closely I have no idea what they use and what not.

@hualet ...
could you please shed some light on the above concerns of ... **[Bilelmoussaoui](https://github.com/flathub/linux-store-frontend/issues/148#issuecomment-434412933)** ... an active 3rd party maintainer of flatpak apps on flathub

I was assuming given that you already have flatpak versions of your apps ... there is already an ecosystem for flatpaking your apps for flathub ... and any volunteer will have very little work to repack them for flathub ...

Look forward to your response ... @hualet  ....

**Comment by hualet** [comment]
@Iceyer

**Comment by aiamuzz** [comment]
@hualet ... @Iceyer  ... so this runtime and baseApp that @bilelmoussaoui is talking about ... i am assuming they are already in place as you have hosted flatpak apps in your own repository ... instead of having to create them from scratch ...

**Comment by cheese** [comment]
Since Fedora does not allow official packages use ffmpeg, we hope deepin-movie and the many Deepin apps can be installed from Flathub.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
