### ISSUE TITLE
File manager theming issue

### ISSUE THREAD

**Issue by paramjitrohits** [linuxdeepin/developer-center#550]
After having set dark theme in Deepin file manager, opening the computer folder from the Computer button in start menu, opens a file manager window with both dark and white colors. White colors occur behind the folders and dark background behind the side bar.

![screenshot from 2018-06-11 19-24-02](https://user-images.githubusercontent.com/36928406/41235744-0c64639a-6dad-11e8-8e30-fa01b5ad6c20.png)

**Comment by felixonmars** [comment]
Are you still getting this? I cannot reproduce the problem myself.

**Comment by paramjitrohits** [comment]
It really is strange. I haven't been able to replicate it myself, however many times I tried. Closing this for now.
