### ISSUE TITLE
 Override default window height

### ISSUE THREAD

**Issue by snackk** [linuxdeepin/developer-center#551]
I am trying to override the default window height, so when i maximize a window it look like this:

Wanted Behaviour

![](https://i.stack.imgur.com/Iou6k.png)

Actual Behaviour

![](https://i.stack.imgur.com/aVCeh.png)

Is this possible? What do i have to do to make it work?

**Comment by sonald** [comment]
what is the translucent bar on the top ? if it's written by yourself, you should set _NET_WM_STRUT_PARTIAL to tell wm to leave the top area untouched.

**Comment by snackk** [comment]
I'am using conky with this config file: https://github.com/snackk/arch-config-files/blob/master/conky/conkyrc
I think conky is setting to _NET_WM_WINDOW_TYPE_DOCK instead of _NET_WM_STRUT_PARTIAL.
Or am i missing something??

**Comment by sonald** [comment]
I know nothing about conky, but what keeps wm from occupying an area is the property _NET_WM_STRUT_PARTIAL. I doesn't matter if it's _NET_WM_WINDOW_TYPE_DOCK type of window. use xprop to check the top conky window if _NET_WM_STRUT_PARTIAL is set.

**Comment by snackk** [comment]
That's what i'am going to do then :D.
Thanks you.
