### ISSUE TITLE
Albert - missing icons for some applications

### ISSUE THREAD

**Issue by denisoster** [linuxdeepin/developer-center#552]
![deepinscreenshot_ - _20180612093246](https://user-images.githubusercontent.com/15886355/41273823-b5051910-6e23-11e8-9204-081262530e46.png)

**Comment by haruyukilxz** [comment]
![_ _20180717114542](https://user-images.githubusercontent.com/12298476/42795453-f75dc29a-89b6-11e8-977f-eca4fc131444.png)

It can't be reproduced, and it may be solved now.
