### ISSUE TITLE
Integrated org.deepin.Runtime

### ISSUE THREAD

**Issue by kamiyadm** [linuxdeepin/developer-center#5521]
### package information | 软件包信息

org.deepin.Runtime | 23.0.0.18
-- | --

### Package repository address | 软件包仓库地址

仓库地址：http://10.0.36.228:9001/
更换地址：ll-cli repo modify http://10.0.36.228:9001/ --name develop-snipe

### test suggestion | 测试建议

主要修复截图录屏，子菜单图标异常问题；音乐闪退问题

安装linglong-bin，sudo apt install linglong-bin
修改仓库地址，ll-cli repo modify http://10.0.36.228:9001/ --name develop-snipe
安装或者更新任意玲珑应用，观察runtime是否已更新至23.0.0.18
运行截图录屏，观察子菜单图标是否显示正常；测试音乐是否仍然闪退

### Sphere of influence | 影响范围

#4255 
#5228

**Comment by kamiyadm** [comment]
@babyfengfjx

**Comment by vivianxf** [comment]
验证通过,请即使汇总合入:
1.玲珑应用使用正常
2.系统基本功能正常
3.暂未发现其他新问题
 issue #4255 验证镜像:https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230906/deepin-23-beige-beta2-amd64-20230906-174421.iso
仓库:ll-cli repo modify http://10.0.36.228:9001/ --name develop-snipe
版本:org.deepin.Runtime:23.0.0.15
验证步骤:提单的步骤
验证现象:在1倍,1.25倍 1.5倍.1.75倍缩放下验证,截图录屏"✅"选项大小展示正常
验证结论:通过
![image](https://github.com/linuxdeepin/developer-center/assets/96415804/86940e57-ca78-4e36-97e8-30e8d88f6a72)

**Comment by vivianxf** [comment]
目前最新版本org.deepin.Runtime :23.0.0.15 仍然存在闪退问题,麻烦再看看

**Comment by 18202781743** [comment]
> 目前最新版本org.deepin.Runtime :23.0.0.15 仍然存在闪退问题,麻烦再看看

这个版本还未带上修复的提交，等下一个提测吧，

**Comment by kamiyadm** [comment]
> 目前最新版本org.deepin.Runtime :23.0.0.15 仍然存在闪退问题,麻烦再看看

集成信息已经更新，目前是23.0.0.16, 包含闪退问题的修复

**Comment by vivianxf** [comment]
最新版本org.deepin.Runtime :23.0.0.16验证音乐闪退问题,通过,目前音乐没有复现到闪退问题

**Comment by kamiyadm** [comment]
> 最新版本org.deepin.Runtime :23.0.0.16验证音乐闪退问题,通过,目前音乐没有复现到闪退问题

runtime又更新了一版，新增spdlog库。主要处理系统上未更新dtk时，应用无法启动的问题（缺少libspdlog），现集成到runtime中。

**Comment by kamiyadm** [comment]
@Zeno-sole 集成一下？
