### ISSUE TITLE
deepin-installer 6.0.28 版本集成

### ISSUE THREAD

**Issue by UTsweetyfish** [linuxdeepin/developer-center#5524]
### package information | 软件包信息

deepin-installer 6.0.28

### Package repository address | 软件包仓库地址

https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/chentianyu1/20230907/

### changelog | 更新信息

Revert "fix: set DI_GRUB_RESOLUTION_CONFIG to auto"

### test suggestion | 测试建议

测试安装系统后：

1. /etc/default/grub 的 GRUB_GFXMODE 为 1024x768
2. /boot/grub/grub.cfg 搜索 gfxmode，最后一处出现为 1024x768
3. grub 界面选择系统的 menu 居中，且显示效果合理；忽略高分屏下 图片、字体略糊的问题
4. 输入 c 进入命令行界面，输入 videoinfo，确定分辨率为 1024x768

### Sphere of influence | 影响范围

grub 界面的分辨率

### ADDITIONAL INFORMATION | 额外补充

回退了之前对安装器做的改动，保持之前的行为 指定 grub 分辨率为1024x768

**Comment by babyfengfjx** [comment]
@kobe337   请确认此次回退处理，需要与讨论结论保持一致：当前可以接受放大模糊的效果，但是不能有画面偏移的情况，下个版本做适应的适配优化工作，需要知会老梅这边下需求。

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/chentianyu1/20230907/
内核：Linux v23-PC 6.1.32-amd64-desktop-hwe #23.01.00.19 SMP PREEMPT_DYNAMIC Wed Aug  2 17:06:10 CST 2023 x86_64 GNU/Linux
【结论】：
测试通过，暂无严重问题及影响

下个版本计划做优化的情况，已向老梅反馈。

**Comment by UTsweetyfish** [comment]
link #5436
