### ISSUE TITLE
Display shortcuts of a particular Deepin application !!!

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#553]
Hi,

As most of us may know the shortcut **Shift+Ctrl+?** in the terminal application display's the shortcuts defined for the Terminal Application.

Wouldn't it be great if the whole Deepin Application family of softwares were extended the courtesy of this option ( **Shift+Ctrl+?** ) ... Its definitely a good option for all deepin applications to have an option of displaying the shortcuts defined under it ... don't you think ?

Cheers.

**Comment by hualet** [comment]
That is happening, you can check dde-file-manager.

**Comment by aiamuzz** [comment]
there ... see that's fantastic ... hope all deepin apps will be gettting it !

**how about a** 'Shift+Ctrl+/' **option to show our system wide custom keyboard shortcuts(set in keyboard control settings) ... now the question may arise how ... as it is not specific application.**

How about we hit 'Super+d' to display desktop ... and than a **'Shift+Ctrl+/'** could display our system wide **'custom shortcuts'**  ???

**Comment by hualet** [comment]
I know what you mean, we planned to do that but there're way more important things need us to do 😭

**Comment by aiamuzz** [comment]
> I know what you mean, we planned to do that but there're way more important things need us to do sob
No problem ... as long as you have them on your list of milestones ... we'll get them eventually ...

I hope at least the Deepin Movie & Music is implemented with this **'Shift+Ctrl+/'** just like the File Manager.

sob ... if only i was a coder like you ... i would have certainly worked on these minor things which will enrich the whole operating experience UP quite a few notches ... these things though minor and may not be up the priority list but they are the actual things the customer experiences !!!


:)

**Comment by aiamuzz** [comment]
Hey this is working on Deepin Movies too ... so all in all Deepin Terminal, Deepin File Manager and Deepin Movie has the option **'Shift+Ctrl+/'** functional !!!

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
