### ISSUE TITLE
Scale UP ... Current Upgrade Download speed is Crawling !!!

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#555]
Guys,

the upgrade download speed is crawling ... I couldn't test the pre-release in spite of being on the internal testing team only because i couldn't download the pre-release iso ... my download manager would show estimated time to download running into 55 days ...

An now i have put my system on download via the control panel and its crawling !!!

**Deepin is a great product even at this stage ... i have been an ubuntu user for more than 8 years and i didn't have to even blink towards any other distro or even back at ubuntu for that matter.**

**Please don't screw up on trivial things ... fast download servers is one in significant thing ... but the independent distro reviewers are going to rip you up for your crawling update speeds. ?**

I am sold to your cause & i have been your user for more than 6 months now, but imagine a new guy introduced/referred to by one of us to try out Deepin OS ... **for him a "lightening speed download" is the 'First Impression'**  ... **the current download rate may just spook him so badly that he may decide to keep away !!!**

you need to move to lightening fast servers !!!

**Comment by aiamuzz** [comment]
great ... failed to update !!!
**:( :( :(**

**Comment by hualet** [comment]
We have made contact with our mirrors, most of them have finished syncing.
Next time we'll provide google drive or other ways to download testing ISO, thanks for you advice and patience.

**Comment by aiamuzz** [comment]
a good idea to host the testing iso it on google drive ...

But more importantly the release ISO needs to download in very fast and smoothly ... bcos the new users who may be directed by us to try out deepin will be repelled with slower speeds ... that's the first impression for them ... a good decent speed is key to make it a lasting impression !!!
