### ISSUE TITLE
[Deepin Integration]~[V23-Beta2] rb-union@linuxdeepin/deepin-image-viewer 玲珑应用 

### ISSUE THREAD

**Issue by rb-union** [linuxdeepin/developer-center#5553]
### package information | 软件包信息

【应用名】看图
【包名】deepin-image-viewer
【版本】6.0.3

### Package repository address | 软件包仓库地址

http://10.0.36.228:9001/repos/develop-snipe/refs/heads/linglong/org.deepin.image.viewer/6.0.3/

### changelog | 更新信息

* https://github.com/linuxdeepin/deepin-image-viewer/pull/150
* https://github.com/linuxdeepin/deepin-image-viewer/pull/151
* https://github.com/linuxdeepin/deepin-image-viewer/pull/156

### test suggestion | 测试建议

关联的bug或issue单
1. https://github.com/linuxdeepin/developer-center/issues/4884
2. https://pms.uniontech.com/bug-view-208451.html
3. https://pms.uniontech.com/bug-view-208417.html

### Sphere of influence | 影响范围

高分屏高屏幕缩放下界面按钮显示
右键菜单翻译
右键菜单切换

**Comment by babyfengfjx** [comment]
@SuperEffie  请开展集成验证。

**Comment by SuperEffie** [comment]
【验证结论】：测试通过，请走下一步流程
【备注信息】：issue : #4884 ；bug : [#208451](https://pms.uniontech.com/bug-view-208451.html) 、[#208417](https://pms.uniontech.com/bug-view-208417.html) 以上均验证通过，看图基本功能正常
