### ISSUE TITLE
[Deepin Integration]~[V23-Beta2] rb-union@linuxdeepin/deepin-editor 玲珑应用

### ISSUE THREAD

**Issue by rb-union** [linuxdeepin/developer-center#5556]
### package information | 软件包信息

【应用名】文本编辑器
【包名】deepin-editor
【版本】6.0.13

### Package repository address | 软件包仓库地址

http://10.0.36.228:9001/repos/develop-snipe/refs/heads/linglong/org.deepin.editor/6.0.13/

### changelog | 更新信息

* https://github.com/linuxdeepin/deepin-editor/pull/261
* https://github.com/linuxdeepin/deepin-editor/pull/262
* https://github.com/linuxdeepin/deepin-editor/pull/259
* https://github.com/linuxdeepin/deepin-editor/pull/253
* https://github.com/linuxdeepin/deepin-editor/pull/254
* https://github.com/linuxdeepin/deepin-editor/pull/255
* https://github.com/linuxdeepin/deepin-editor/pull/256
* https://github.com/linuxdeepin/deepin-editor/pull/257
* https://github.com/linuxdeepin/deepin-editor/pull/249
* https://github.com/linuxdeepin/deepin-editor/pull/251

### test suggestion | 测试建议

相关测试bug单
* https://pms.uniontech.com/bug-view-215591.html
* https://pms.uniontech.com/bug-view-210815.html
* https://pms.uniontech.com/bug-view-172681.html
* https://pms.uniontech.com/bug-view-212273.html
* https://pms.uniontech.com/bug-view-196349.html
* https://pms.uniontech.com/story-view-29499.html

### Sphere of influence | 影响范围

1. 新增允许打开toml mod文件
2. 修复一处点击空白区域导致程序无响应问题
3. 修复文本高亮和文档显示冲突问题
4. 修复拖拽文件错误
5. 补充部分遗漏翻译文件
6. 定制需求 ZPD/GB18030 回合兼容主线

**Comment by babyfengfjx** [comment]
@kobe337  请开展集成验证，玲珑应用的测试需要修改仓库地址，然后通过升级方式去测试。

**Comment by rb-union** [comment]
影响范围不仅包含bug单，还涉及PR以及需求更新的内容，没有与bug单一一对应的顺序排列。
此次需求合入主要兼容定制功能，不影响主线功能。

**Comment by kobe337** [comment]
与研发同事确认，主线功能正常即可，定制内容暂不涉及

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
应用版本：org.deepin.editor:6.0.13
内核：Linux deepin-PC 6.4.7-amd64-desktop-hwe #1 SMP PREEMPT_DYNAMIC Thu Aug  3 11:58:54 CST 2023 x86_64 GNU/Linux
【结论】：
测试通过，暂无严重问题及影响
