### ISSUE TITLE
【deepin_V23_beta2】【严重】【正常】【预发布测试】【内核】【LENOVO_MT_82L7_XiaoXinAir 14+ Notebook】小新机器安装v23 beta2镜像触控板无法使用

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#5560]
### SUMMARY | 问题概要

单机必现问题

![image](https://github.com/linuxdeepin/developer-center/assets/62528742/55430e6b-93c7-4fb2-86a0-f66060890f2e)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230908
内核信息: Linux test-PC 6.1.11-amd64-desktop-hwe #23 SMP PREEMPT_DYNAMIC Mon Feb 27 17:25:36 CST 2023 x86_64 GNU/Linux

控制中心：6.0.25
```

### PRE-REQUIREMENT | 预置条件

安装0908镜像

### STEPS TO REPRODUCE | 复现步骤

进入系统后观察触控板是否可以正常使用

### OBSERVED RESULT | 观察到的结果

触控板无法正常使用

### EXPECTED RESULT | 期望的结果

触控板正常可以使用

### ADDITIONAL INFORMATION | 额外补充

[设备信息20230908_172148.txt](https://github.com/linuxdeepin/developer-center/files/12557895/20230908_172148.txt)

**Comment by babyfengfjx** [comment]
@kegechen  请帮忙安排优先分析，需要找到具体原因。

**Comment by kegechen** [comment]
可以执行 `xinput` 列出一下输入设备

**Comment by kegechen** [comment]
备注一下 @Decodetalkers

**Comment by Decodetalkers** [comment]
- https://wiki.archlinux.org/title/Lenovo_XiaoXin_15are_2020#Touchpad
- https://wiki.archlinuxcn.org/wiki/%E8%81%94%E6%83%B3_%E5%B0%8F%E6%96%B0_15are_2020 
上面是中文的翻译
- https://bbs.archlinuxcn.org/viewtopic.php?id=11224
- https://bugzilla.kernel.org/show_bug.cgi?id=20775
这边有详细的信息，可以让内核看一下

**Comment by Decodetalkers** [comment]
@Zeno-sole 详细的信息已经列了，如果有相关patch可以查找下吧。这个不是我们可以修的，有几年了

**Comment by Zeno-sole** [comment]
@babyfengfjx  请使用beta3镜像 6.6 内核验证一下是否还存在问题，若依然存在请转内核方面处理

**Comment by babyfengfjx** [comment]
@xuqi27837288  请在最新镜像确认该问题。

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240102
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.7-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
