### ISSUE TITLE
Deepin File Manager - no auto refresh on file operations

### ISSUE THREAD

**Issue by Drakon74** [linuxdeepin/developer-center#557]
When i perform a file operation (create a file / folder, delete it, rename it, etc.) the file manager is not auto refreshing the folder view. So i manually have to hit F5 so the view gets refreshed and the changes are being showed (a newly created folder for example).

**Comment by hualet** [comment]
@zccrs

**Comment by htarnacki** [comment]
I experience the same behaviour in Deepin 15.9.3

**Comment by hualet** [comment]
@htarnacki Your inotify watches may have been exhausted?

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/developer-center/issues/1075

**Comment by htarnacki** [comment]
thanks it helped ;-)
I did:
`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

so it seems that default value in Deepin is too small: 8192

**Comment by duanyao** [comment]
max_user_watches=8192 is too small for quite a lot of users, please consider increase the default value.
@BLumia

**Comment by BLumia** [comment]
> max_user_watches=8192 is too small for quite a lot of users, please consider increase the default value.

Feel free to open another issue for that request.
