### ISSUE TITLE
[Deepin Integration]~[V23-Beta2] Integrated for kernel 23.01.00.20

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#5579]
### package information | 软件包信息

linux-headers-6.1.32-amd64-desktop-hwe | 23.01.00.20
linux-image-6.1.32-amd64-desktop-hwe | 23.01.00.20

### Package repository address | 软件包仓库地址

deb [trusted=yes] https://ci.deepin.com/repo/deepin/deepin-community/obs-repos/  kernel main 

### changelog | 更新信息

移除rtk_btusb 模块 

### test suggestion | 测试建议

重点蓝牙相关功能，验证rtl系列设备蓝牙在6.1内核上出现蓝牙丢失重启后能否恢复

### Sphere of influence | 影响范围

蓝牙驱动相关

### ADDITIONAL INFORMATION | 额外补充

关联pms、issues
https://pms.uniontech.com/bug-view-215995.html
https://github.com/linuxdeepin/developer-center/issues/5543

**Comment by babyfengfjx** [comment]
@xuqi27837288  请开展集成验证，重点验证蓝牙相关特性。

**Comment by xuqi27837288** [comment]
【环境】：
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【结论】：
测试通过，暂无严重问题及影响
