### ISSUE TITLE
Mouse Back Button not working after Upgrading to 15.6 !!!

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#558]
Hi,

I have 5 button mouse ... and the back / forward buttons aren't working after i upgraded to 15.6 ?

on webpages the cursor is responding to these button with a toggle between the pointer and a text cursor in text field so i know these 2 buttons are being read only the expected action seem to be missing !!!

**Comment by hualet** [comment]
Back/forward buttons support is done by applications, so I need to know which part or application has the regression.

**Comment by aiamuzz** [comment]
I am sorry it hasn't stopped working with regard to any application ... it used to work globally and it isn't working anywhere ... in the Deepin Control Center, In the File manager, in the browser(i use chrome) ... i have gotten used to it ... and now finding it difficult to adjust without it.

PS : To be sure it isn't an issue with my mouse i just ran `'xev'` and the forward/backware clicks are working on my mouse.

**Comment by aiamuzz** [comment]
Is it just me who is facing this problem with the mouse back/forward buttons ?
@hualet  ... is there in workaround that i can try ... its really annoying to have lost its function after having gotten used to it so much.

**Comment by hualet** [comment]
I don't know anyone having the same problem.

**Comment by aiamuzz** [comment]
> I don't know anyone having the same problem.

Could it be because not many of them may have a 5 button mouse ?

**Comment by aiamuzz** [comment]
the backward / forward button of my 5 mouse button hasn't been fixed ... missing it ... hope to see it restored as it was in Deepin 15.5 !!!

**Comment by aiamuzz** [comment]
closing it ... as issue traced back to `imwheel` adoption ...
