### ISSUE TITLE
[Deepin Integration]~[V23-Beta2] Integrated for texlive-lang 2022.20230122-1

### ISSUE THREAD

**Issue by UTsweetyfish** [linuxdeepin/developer-center#5580]
### package information | 软件包信息

包名 | 版本
--  | --
texlive-lang | 2022.20230122-1

### Package repository address | 软件包仓库地址

```
deb [trusted=yes] https://ci.deepin.com/repo/deepin/deepin-community/texlive-lang/ unstable main
deb-src [trusted=yes] https://ci.deepin.com/repo/deepin/deepin-community/texlive-lang/ unstable main
```

### changelog | 更新信息

更新 texlive-lang，解决 texlive 依赖问题

### test suggestion | 测试建议

添加集成源后，安装 texlive-base、texlive-lang-chinese，能够安装即可

### Sphere of influence | 影响范围

仅解决依赖问题，不影响系统

**Comment by babyfengfjx** [comment]
@kobe337  请开展集成验证，确保能正常安装，版本信息正确即可。

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
仓库：deb [trusted=yes] https://ci.deepin.com/repo/deepin/deepin-community/texlive-lang/ unstable main
   deb-src [trusted=yes] https:ci.deepin.com/repo/deepin/deepin-community/texlive-lang/ unstable main
内核：Linux v2398-PC 6.1.32-amd64-desktop-hwe #23.01.00.20 SMP PREEMPT_DYNAMIC Mon Sep 11 14:16:03 CST 2023 x86_64 GNU/Linux
【结论】：
测试通过，没有严重问题和影响。

![tex](https://github.com/linuxdeepin/developer-center/assets/17869922/6a8035e7-41a9-4f25-8e43-952d02a9903e)
