### ISSUE TITLE
[Deepin Integration]~[V23-Beta2] Integrated for dde-introduction 7.0.1

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#5585]
### Package information | 软件包信息

包名 | 版本
--  | --
dde-introduction | [7.0.2]

### Package repository address | 软件包仓库地址

   deb  [trusted=yes] https://aptly.uniontech.com/pkg/beige-v2/release-candidate/44CQ5Zu-5b2i5Zu-5YOPMjIuMTHjgJFWMjMt5YaF6YOo6aqM6K-BMjAyMy0wMi0wMiAxMzoyNzo0OQ/  unstable main

#### dde-introduction (6.0.6) unstable; urgency=medium

  * release dde-introduction 7.0.1

### Test suggestion | 测试建议
FIX https://github.com/linuxdeepin/developer-center/issues/5483 

```
# 安装
sudo apt install dde-introduction
# 执行
dde-introduction
```

### Influence | 影响范围
欢迎应用

**Comment by babyfengfjx** [comment]
@SuperEffie  请开展回归验证。

**Comment by SuperEffie** [comment]
【验证结论】：测试不通过，请开发同学继续优化后提交集成
【录屏信息】：
![欢迎](https://github.com/linuxdeepin/developer-center/assets/58986464/a1448f23-d2e1-4e77-99ec-fe2bad5ee8d8)

**Comment by Zeno-sole** [comment]
@SuperEffie  已更新 dde-introduction | 7.0.2 版本请重新验证

**Comment by babyfengfjx** [comment]
@SuperEffie   请重新更新后验证。

**Comment by SuperEffie** [comment]
【验证结论】：测试通过，请走下一步流程~
【备注信息】：验证issue: #5483 已修复
