### ISSUE TITLE
confusion about wallpaper location

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/developer-center#559]
Apparently with latest updates to DDE 15.6 the default wallpaper path has been modified to **/usr/share/wallpapers/deepin** and it looks like the wallpaper chooser now **only** offers image files located in that location.
Now the question is, what happens to custom additional wallpapers and to files already present in the more common path **/usr/share/backgrounds**?
I don't think it is a good idea for the wallpaper chooser to ignore these and to force users to move all picture files to the new location in order for them to be available as backgrounds.
Some other DEs like Cinnamon or Xfce offer options to define a list of paths for the wallpaper chooser to include.

**Comment by hualet** [comment]
@electricface @jouyouyun

**Comment by felixonmars** [comment]
I believe that change was long before 15.6. The package I made for providing Plasma wallpapers in the wallpaper chooser was made on Oct 2017 which already uses **/usr/share/wallpapers/deepin**.

**Comment by electricface** [comment]
you can use file manager open /usr/share/background directory

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
