### ISSUE TITLE
[archlinux] 全新安装的arch-deepin，似乎没有打包音频和电源方面的管理

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/developer-center#56]
<a href="https://github.com/zhuzilinuser"><img src="https://avatars.githubusercontent.com/u/12298476?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @zhuzilinuser**
_Saturday Mar 05, 2016 at 02:14 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/259_

----

打开控制中心，只有点击音频和电源会卡死，等待数分钟以后，面板切换到音频或电源，里面是空白的。
现在只能先安装其他桌面，才能正常使用deepin。

**Comment by jouyouyun** [comment]
能否贴下以下命令的输出：
```shell
$ pacmd list-sinks
$ pacmd list-sources
$ dbus-send --print-reply --dest=com.deepin.daemon.Audio /com/deepin/daemon/Audio org.freedesktop.DBus.Properties.Get string:"com.deepin.daemon.Audio" string:"Sinks"
$ dbus-send --print-reply --dest=com.deepin.daemon.Power /com/deepin/daemon/Power  org.freedesktop.DBus.Properties.Get string:"com.deepin.daemon.Power" string:"PlanInfo"
$ gsettings get com.deepin.dde.daemon power
$ gsettings get com.deepin.dde.daemon audio
```
如果上面的两个 `dbus-send` 命令返回 `timeout`，麻烦执行下下面的命令，然后贴下输出：
```
$ killall dde-control-center && killall dde-session-daemon && /usr/lib/deepin-daemon/dde-session-daemon enable audio
$ killall dde-session-daemon && /usr/lib/deepin-daemon/dde-session-daemon enable power
```

**Comment by zhuzilinuser** [comment]
缺少pulseAudio这个包，安装以后，控制中心就有了。
![deepinscreenshot20160307110508](https://cloud.githubusercontent.com/assets/12298476/13559936/79100420-e454-11e5-9c36-c957d8d41d95.png)

**Comment by jouyouyun** [comment]
Greate, @fasheng

**Comment by zhuzilinuser** [comment]
安装pulseAudio以后，电源也正常显示了。似乎没什么问题了。

**Comment by fasheng** [comment]
@jouyouyun 你有空把依赖加到 dde-daemon README 里吧～

@felixonmars 呼叫肥猫 ;)

**Comment by felixonmars** [comment]
deepin-daemon-3.0.11-2 uploaded with pulseaudio as a dependency.
