### ISSUE TITLE
Deepin support for the bell character

### ISSUE THREAD

**Issue by moham96** [linuxdeepin/developer-center#560]
Hi,
I'm running Manjaro Deepin 17.1.10, I'm trying to use the [bell character!](https://en.wikipedia.org/wiki/Bell_character) in the terminal but I can't get it to work, I've loaded the `pcspkr` module but no sound is coming.

I've tried the following commands:

`tput bel`

`echo -ne '\007'`

`printf '\a'`

and not one of them produced a beep sound, this problem only happens when running from the terminal emulator in Deepin, if I change to another virtual terminal (ctrl+alt+f3) I can use any of the above commands and it would result in a beeping sound.
Also, there is a program called [beep!](https://www.archlinux.org/packages/extra/x86_64/beep/) which working even in terminal emulator but unfortunately it requires root.
As far as I know, KDE has support for the bell sound.
This would be nice to have in Deepin.
Thanks

**Comment by hualet** [comment]
I don't think deepin-terminal has such feature or plan to support that, sorry.
