### ISSUE TITLE
[feature request] global search in settings

### ISSUE THREAD

**Issue by moham96** [linuxdeepin/developer-center#561]
It would be nice to have a global search field in the control center

**Comment by aiamuzz** [comment]
Not sure if its needed as the control center is not window based a search window is ideal in a window based settings ... As the Deepin control center activates/invoked with a mouse cursor  ... with the mouse already in play its easier to click the required settings then click on the search field and type the setting to search.

just a thought ...

**Comment by hualet** [comment]
Schedule is full :(

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
