### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【预发布测试】【DDE】【控制中心】设置 按电源按钮时 进入关机界面后，按电源按钮时进入到了解锁界面

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#5614]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230908/deepin-23-beige-beta2-amd64-20230908-160331.iso 
 dde-control-center 6.0.26
```

### PRE-REQUIREMENT | 预置条件

1.安装镜像：镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230908/deepin-23-beige-beta2-amd64-20230908-160331.iso

### STEPS TO REPRODUCE | 复现步骤

1. 在控制中心 - 电源管理 - 使用电源中 ，设置 按电源按钮时 进入关机界面
2.  按电源按钮

### OBSERVED RESULT | 观察到的结果

2. 进入到了解锁界面
![录屏_选择区域_20230912141804](https://github.com/linuxdeepin/developer-center/assets/96416089/25885526-3047-40fe-b499-4df3b8abdf45)

### EXPECTED RESULT | 期望的结果

2. 进入关机界面
![image](https://github.com/linuxdeepin/developer-center/assets/96416089/73d38011-d2c8-49c2-93d5-e8c4125ffc3f)

**Comment by babyfengfjx** [comment]
@Decodetalkers  请帮忙优化~

**Comment by luodeepin** [comment]
验证通过
dde-daemon 6.0.22
![录屏_选择区域_20230913135024](https://github.com/linuxdeepin/developer-center/assets/96416089/821b0ec5-8867-4022-b29d-ee22c85f9df7)

**Comment by SuperEffie** [comment]
【验证环境】
【镜像地址】：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230913/deepin-23-beige-beta2-amd64-20230913-170916.iso
【关联集成】：#5645
【验证结论】：测试通过，插入电源时，设置按电源按钮时“进入关机界面”功能正常
【录屏信息】：
![关机界面](https://github.com/linuxdeepin/developer-center/assets/58986464/c18e6fa7-6f49-4fdf-857e-90b393b15f4f)
