### ISSUE TITLE
add support for window action key (window modifier key)

### ISSUE THREAD

**Issue by m47h4r** [linuxdeepin/developer-center#563]
I think the only feature i see lacking in deepin is window hotkey to move or resize windows with. What i mean is to move a window without touching it's window bar and by holding down super key and draggin the window around (any part of it). By the way, thanks for bringing beauty to linux :) i really appreciate your artwork.

**Comment by hualet** [comment]
I think you can enable that feature by setting some gsettings. @sonald  call tell you.

**Comment by m47h4r** [comment]
I don't believe that works, gsettings can be changed from dconf editor i suppose. i checked dconf editor and it was already set to use <super> for window modifier key.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
