### ISSUE TITLE
White Screen on Shutdown Menu

### ISSUE THREAD

**Issue by ibrokemypie** [linuxdeepin/developer-center#565]
When clicking the shutdown button on the dock it simply brings up a blank white screen

**Comment by hualet** [comment]
@kirigayakazushin

**Comment by ibrokemypie** [comment]
Since rebooting, I cannot seem to reproduce this.

**Comment by adrianbeniel** [comment]
Since the last two updates of Deepin, I also have this white screen.

**Comment by mbhtkd** [comment]
I also had the same problem, the solution was very simple so just change the wallpaper and I stop showing the white screen

**Comment by kirigayakazushin** [comment]
We changed some configurations of the wallpapers and did not fully test the upgrade environment.

**Comment by MrMyrmex** [comment]
It needs to be a .jpg wallpaper if you want to avoid the white screen for some reason.

**Comment by Xeers** [comment]
The display manager appears blank when you log in to Deepin-Arch.
When you click on the icon of the dock off, the blank screen also appears.

[]https://i.imgur.com/c9lmxFI.png(url)

**Comment by haruyukilxz** [comment]
Because the default wallpaper is in deepin's default-settings package, but archlinux is not provided, so the screen is white, We need to discuss how to deal with wallpaper issues.

**Comment by felixonmars** [comment]
I have updated some packages to use the deepin-wallpaper package's default wallpaper. Please let me know if it works now.

**Comment by Xeers** [comment]
Thanks.  The display manager works correctly, there is no blank screen.

**Comment by felixonmars** [comment]
I assume it's fixed then. Please reopen if you still get the problem.
