### ISSUE TITLE
v23仓库里fcitx5-pinyin-zhwiki-data这个包提供的词库文件是空的

### ISSUE THREAD

**Issue by debuggerx01** [linuxdeepin/developer-center#5655]
### SUMMARY | 问题概要

v23仓库里fcitx5-pinyin-zhwiki-data这个包提供的词库文件是空的

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
Deepin v23
fcitx5-pinyin-zhwiki-data_0.2.3-1_all
```

### STEPS TO REPRODUCE | 复现步骤

apt download fcitx5-pinyin-zhwiki-data
dpkg -x fcitx5-pinyin-zhwiki-data_0.2.3-1_all.deb ./zhwiki
ls -sh ./zhwiki/usr/share/fcitx5/pinyin/dictionaries/zhwiki.dict

### OBSERVED RESULT | 观察到的结果

![image](https://github.com/linuxdeepin/developer-center/assets/19624835/9f58f7bd-7669-4c57-b34c-6b0b08ebf925)

### EXPECTED RESULT | 期望的结果

正常这个词库文件应该有 40MB 左右

**Comment by xzl01** [comment]
1

**Comment by xzl01** [comment]
https://github.com/linuxdeepin/developer-center/issues/5678

**Comment by xzl01** [comment]
https://github.com/linuxdeepin/developer-center/issues/5678
