### ISSUE TITLE
Text field navigation ... Bug or a Withdrawn feature  ? 

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#566]
Hi,

As we all know `Ctrl + right/left` arrow jumps the cursor one word at a time in a text field in either direction, And holding the Shift key with the above combination selects the words in jumps of subsequent words ... a pretty handy feature to select text faster instead of `Shift+right/left` which selects text one character at a time.

`Ctrl+Shift+ left/right` is no longer selccting text in jumping by each word ... is this a bug or a Withdrawn feature ... if its the latter then kindly revert back this option ... i have had trouble writing this post without that feature forced to use the slower `Shift+left/right` option to select text for formatting on this post as i write.

**Anybody else facing this issue where `Ctrl+Shift+right/left` arrow key failing to select text each word at a time ?**

**Comment by felixonmars** [comment]
It depends on the text input widget IIRC. Are you getting the problem in a web browser or somewhere else?

**Comment by aiamuzz** [comment]
@felixonmars  ... your question is such a reprieve ... seems its not a withdrawn feature ... more of a bug

I am facing it everywhere ... i tested on gedit ... on the browser(text fields and address bar) on ... dde-file-manager address bar ... everywhere !!!

**Comment by felixonmars** [comment]
Since I cannot reproduce it, it's absolutely not a withdrawn feature :)

@zccrs Any ideas about debugging?

**Comment by aiamuzz** [comment]
> Since I cannot reproduce it, it's absolutely not a withdrawn feature :)
> 
> @zccrs Any ideas about debugging?

I am holding this state of the device as means to debug ... I have face this this [problem](https://github.com/linuxdeepin/developer-center/issues/564) ... and facing this [problem](https://github.com/linuxdeepin/dde-dock/issues/99) with the dde-dock as well !!!

**I suspect this could be as a result of the OS roll back and re-upgrading that may have messed up things.**

Habitually i don't shutdown or restart days and weeks on end ... so i can hold of the same should you people want to run debugging on my system to identify any vulnerabilities through my system in its current buggy state !!!

**Comment by aiamuzz** [comment]
@felixonmars ... @zccrs  ... is it just me who is facing this issue ... any workarounds with which i can manage ... finding it very difficult without the this word block copying ...

**Comment by felixonmars** [comment]
Indeed I didn't get another report on this one.

**Comment by aiamuzz** [comment]
:sad ... whats surprising is that the Ctrl+Shift+down/up arrow key is working fine which selects a whole line/paragraph ... its only the whole word selection that isn't working !!!

**Comment by aiamuzz** [comment]
> Try another keyboard ?

@hualet  ... mine is a laptop ... anyways i have a multi-boot system with ubuntu and windows 10 on my system. I booted into both and the word selection is working there ... 

I have however accidentally discovered that it is working in deepin on the login screen ... It works in the password field ... I am able to copy the password entry by Holding Ctrl+Shift+left arrow key ... but once i log into the OS ... it stops working ...

Hope that helps identify where the problem could lie ?

**Comment by aiamuzz** [comment]
@hualet  ... another interesting observation that may help narrow down the issue ... the word selection is working fine in my Windows 7 VMware virtual machine ... Its just not working natively on deepin after logging in ... works fine on the login screen in the password field text selection.

**Comment by aiamuzz** [comment]
really like the word copy was restored just like it was in Deepin 15.5 ... can you please look into this ... its extremely cumbersome to use Shift + right/left arrow to copy text ... a word copy with Ctrl+Shift+ right/left is way more efficient.

the fact that this is working in the password field in the login window should give you enough information to identify this bug which sets in after logging into the system.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
