### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【预发布测试】【深度之家】在控制中心里面退出deepin ID 后，深度之家退出了，但是我的反馈页面没有同步退出，导致页面内容还可见且可操作

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#5661]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230914/deepin-23-beige-beta2-amd64-20230914-163815.iso
深度之家 1.4.0
控制中心 6.0.26
```

### PRE-REQUIREMENT | 预置条件

1. 登录深度之家
2. 当前登录的帐户存在反馈的问题

### STEPS TO REPRODUCE | 复现步骤

1. 打开进入 深度之家 -  点击 BUG反馈 - 点击 我的反馈
2. 打开控制在中心 - 退出登录 deepin ID - 查看 深度之家中 我的反馈 信息页面显示

### OBSERVED RESULT | 观察到的结果

1. 深度之家退出，我的反馈 的 页面内容可见 且可以操作
![录屏_选择区域_20230915134315](https://github.com/linuxdeepin/developer-center/assets/96416089/b5b8a11c-ab61-4be0-ba96-096b016c11f9)

### EXPECTED RESULT | 期望的结果

1. 深度之家退出，反馈信息页面没有内容

**Comment by babyfengfjx** [comment]
@myml  请帮忙优化~

**Comment by myml** [comment]
已经过测试

**Comment by luodeepin** [comment]
验证通过
深度之家 1.5.2
![5661](https://github.com/linuxdeepin/developer-center/assets/96416089/fa781944-1e9c-4ac1-a7b4-9596e87e8cae)
