### ISSUE TITLE
[Deepin Integration]~[V23-Beta2] Integrated for deepin-installer|6.0.29集成

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#5665]
### Package information | 软件包信息

包名 | 版本
--  | --
deepin-installer|6.0.29

### Package repository address | 软件包仓库地址

deb  [trusted=yes] https://aptly.uniontech.com/pkg/beige-v2/release-candidate/bnZpZGlhLWRyaXZlci1saXN0MjAyMy0wOC0wNCAxNDoyMzo1Ng/  unstable main

#### deepin-installer (6.0.29) unstable; urgency=medium

  * 修复选择无对应安装幻灯片的语言时，无幻灯片的问题

### Test suggestion | 测试建议
修复选择无对应安装幻灯片的语言时，无幻灯片的问题 
Bug: https://github.com/linuxdeepin/developer-center/issues/5662

### Influence | 影响范围
镜像安装

### ADDITIONAL INFORMATION | 额外补充
镜像地址： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230914/deepin-23-beige-beta2-amd64-20230914-163815.iso

**Comment by babyfengfjx** [comment]
@vivianxf  请在最新发布镜像中进行回归验证。

**Comment by vivianxf** [comment]
集成验证通过,请及时合入:

1.新镜像安装成功,包版本正确
2.issue#5662验证通过
3.系统功能正常
4.暂时未发现严重问题

综上所述,本次集成通过~

**Comment by vivianxf** [comment]
集成验证通过,请及时合入:

1.新镜像安装成功,包版本正确
2.issue#5662验证通过
3.系统功能正常
4.暂时未发现严重问题

综上所述,本次集成通过~
