### ISSUE TITLE
【deepin_V23_beta2】升级 9.15 日内测版本后，使用截图工具选中区域后弹出工具栏需要较长时间

### ISSUE THREAD

**Issue by zed7th** [linuxdeepin/developer-center#5670]
### SUMMARY | 问题概要

从 9.8 日内测版本升级 9.15 日内测版本后，使用截图工具选中区域后弹出工具栏需要较长时间
![mnggiflab-compressed-mnggiflab-from-video-to-gif-2023_09_15_14_23_21](https://github.com/linuxdeepin/developer-center/assets/52491120/f7760c8d-4ff6-4af4-85f4-2201012a4ffa)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin_V23_beta2 9.15 内测版本
org.deepin.screen-recorder      deepin-screen-recorder          6.0.2.63        x86_64      linglong        runtime     screen recorder for deepin os
```

### PRE-REQUIREMENT | 预置条件

升级至 9.15 内测版本，使用 X11 模式

### STEPS TO REPRODUCE | 复现步骤

1. 打开截图录屏应用
2. 选择一片区域进行截图
3.  等待弹出工具栏

### OBSERVED RESULT | 观察到的结果

工具栏需要 10s 以上才能正常弹出

### EXPECTED RESULT | 期望的结果

在选择完区域后应该马上弹出工具栏进行下一步操作

**Comment by zed7th** [comment]
为了解决升级内测最新版本声音无输出的问题，将系统的音频服务切换为了 pipewire，神奇的是，连带这个截图的问题也一起解决了

**Comment by kobe337** [comment]
反馈已经收到，已联系研发同事帮忙查看下哈 @YukariChiba

**Comment by kobe337** [comment]
@zed7th  麻烦提供下切换的方法，研发同事会看下本次切换是否会影响到系统的其他组件。

**Comment by YukariChiba** [comment]
您好：
1. 对于截图问题：`pipewire` 不仅是音频服务，还管理视频流/图像的输入输出，切换到 `pipewire` 修复截图相关问题属正常状况，在没有 `pipewire` 的情况下的截图问题请转交负责 dde 截图的开发者处理 。
2. 对于音频问题，由于 `pulseaudio` 上游缺乏维护但 `pipewire` 无法对设备实现完全兼容，我们后续将在控制中心加入音频服务器的切换功能。
3. 对于升级问题，`deepin-desktop-environment` 在先前内测的一段时间内将 `pipewire` 设置为了默认音频服务器（`2023.07.13` 和 `2023.09.05` 两个版本之间），而后根据上述原因将默认音频服务器调整回了 `pulseaudio`，之前升级到这些版本之间的内测用户可能会受到影响。
4. 目前从 Beta2 切换至 `pipewire` 的方法是，1. 安装 `pipewire` 2. `systemctl --user mask pulseaudio.service` 3. 注销/重启并重新登录

**Comment by kobe337** [comment]
@zed7th 现在是否已经恢复了正常，如均恢复了正常，此单将关闭哈

与研发同事沟通，背景为后续的音频持续维护方案，在切换过程中，出现了组件版本替换的问题，请参考楼上步骤4进行操作，感谢反馈。

**Comment by zed7th** [comment]
@kobe337 目前切换到 pipewire，音频和截图均恢复正常，暂未发现异常，可关闭此 issue，感谢

**Comment by kobe337** [comment]
与用户确认，问题已解决，此单关闭处理。
