### ISSUE TITLE
Unable to disconnect the Wifi connection !!!

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#568]
Hi,

What i thought is probably an issue with dock which i reported it [here](https://github.com/linuxdeepin/dde-dock/issues/102) ... turns out its an issue of not being able to switch off the wifi connection !!!

unable to switch off from the dock plugin ... not from the control panel ... even going into the connected wifi network and hitting on the **Disconnected** button is not having no effect on the connect wifi

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
