### ISSUE TITLE
Add dde-portals.conf  for xdg-desktop-portal-dde

### ISSUE THREAD

**Issue by wineee** [linuxdeepin/developer-center#5681]
### SUMMARY | 问题概要

https://github.com/flatpak/xdg-desktop-portal/blob/main/doc/portals-conf.rst

kde 
https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/merge_requests/196
https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/merge_requests/218

**Comment by Decodetalkers** [comment]
它有这个feature,但是一直没有正式发布过。。

**Comment by wineee** [comment]
https://github.com/flatpak/xdg-desktop-portal/commit/e7027b7bcc5e29117001351463d479cf03472730

在 1.17.2 发布前已经实现了

**Comment by Decodetalkers** [comment]
> [flatpak/xdg-desktop-portal@e7027b7](https://github.com/flatpak/xdg-desktop-portal/commit/e7027b7bcc5e29117001351463d479cf03472730)
> 
> 在 1.17.2 发布前已经实现了

那是prerelease啊，我一直盯着呢

**Comment by Decodetalkers** [comment]
嘛，先加上好了

**Comment by wineee** [comment]
> > [flatpak/xdg-desktop-portal@e7027b7](https://github.com/flatpak/xdg-desktop-portal/commit/e7027b7bcc5e29117001351463d479cf03472730)
> > 在 1.17.2 发布前已经实现了
> 
> 那是prerelease啊，我一直盯着呢

哦，对的，不过也可以先加上
