### ISSUE TITLE
Boot message ... is it a critical one ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#569]
Hi,

not sure but i think ever since i upgraded i see a particular boot message ...

`**MODIGN : Couldn't get EFI DB list**`

Is it a critical message, anything that i need to do, to rectify the same ?

thanks.

**Comment by hualet** [comment]
I think it's an kernel bug that has been fixed, see https://bugzilla.redhat.com/show_bug.cgi?id=1497559 , we'll update the kernel ASAP.
