### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【发散测试】【DDE】【控制中心】关闭窗口特效后，来回切换点击 更新 时控制中心出现闪烁

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#5693]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
控制中心 dde-control-center 6.0.28
```

### PRE-REQUIREMENT | 预置条件

1. 安装镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
2. 加入内测，更新系统至最新的 23beta2版本；
3.  已经在控制中心 - 个性化 中关闭窗口特效

### STEPS TO REPRODUCE | 复现步骤

1. 打开控制中心 - 来回切换点击 更新 模块，查看控制中心显示

### OBSERVED RESULT | 观察到的结果

1. 控制中心会短暂的闪烁一下
![录屏_选择区域_20230919094159](https://github.com/linuxdeepin/developer-center/assets/96416089/7bae44eb-60e7-4953-8297-71d4e6b4f022)

### EXPECTED RESULT | 期望的结果

1. 控制中心不会出现闪缩等异常情况

**Comment by babyfengfjx** [comment]
@kegechen 请安排优化~

**Comment by kegechen** [comment]
@Decodetalkers 集成测试时带上这个

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta2镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230927
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
【截图录屏】：

![录屏_选择区域_20231129042920](https://github.com/linuxdeepin/developer-center/assets/62528742/00031191-312b-475e-a6e2-88410598b58a)
