### ISSUE TITLE
[archlinux] mouse and touchpad is empty

### ISSUE THREAD

**Issue by zhuzilinuser** [linuxdeepin/developer-center#57]
![20160306170906](https://cloud.githubusercontent.com/assets/12298476/13553276/09acc14e-e3bf-11e5-9461-7f31445a3ef6.png)

I want to disable touchpad when I use usb-mouse.

**Comment by jouyouyun** [comment]
Can you paste the following commands output?
```shell
$ dbus-send --print-reply --dest=com.deepin.daemon.InputDevices /com/deepin/daemon/InputDevice/Mouse  org.freedesktop.DBus.Properties.Get string:"com.deepin.daemon.InputDevice.Mouse" string:"Exist"
$ dbus-send --print-reply --dest=com.deepin.daemon.InputDevices /com/deepin/daemon/InputDevice/TouchPad  org.freedesktop.DBus.Properties.Get string:"com.deepin.daemon.InputDevice.TouchPad" string:"Exist"
$ xinput
```

**Comment by zhuzilinuser** [comment]
➜  ~ dbus-send --print-reply --dest=com.deepin.daemon.InputDevices /com/deepin/daemon/InputDevice/Mouse  org.freedesktop.DBus.Properties.Get string:"com.deepin.daemon.InputDevice.Mouse" string:"Exist"
method return time=1457318625.034356 sender=:1.30 -> destination=:1.51 serial=1940 reply_serial=2
   variant       boolean false
➜  ~ dbus-send --print-reply --dest=com.deepin.daemon.InputDevices /com/deepin/daemon/InputDevice/TouchPad  org.freedesktop.DBus.Properties.Get string:"com.deepin.daemon.InputDevice.TouchPad" string:"Exist"
method return time=1457318633.210317 sender=:1.30 -> destination=:1.52 serial=1962 reply_serial=2
   variant       boolean false
➜  ~ xinput
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ MOSART Semi. 2.4G Keyboard Mouse        	id=12	[slave  pointer  (2)]
⎜   ↳ DLL0652:00 06CB:2985                    	id=14	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Video Bus                               	id=8	[slave  keyboard (3)]
    ↳ Power Button                            	id=9	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=10	[slave  keyboard (3)]
    ↳ MOSART Semi. 2.4G Keyboard Mouse        	id=11	[slave  keyboard (3)]
    ↳ Integrated_Webcam_HD                    	id=13	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=15	[slave  keyboard (3)]
    ↳ Dell WMI hotkeys                        	id=16	[slave  keyboard (3)]
    ↳ MOSART Semi. 2.4G Keyboard Mouse        	id=17	[slave  keyboard (3)]

**Comment by jouyouyun** [comment]
Oh, your device named "MOSART Semi" may be  identified as keyboard. Please paste the outputs to confirm, thanks.
```shell
$ xinput list-props 12
$ xinput list-props 11
$ xinput list-props 17
```
And what is the device named "DLL0652:00 06CB:2985"?

**Comment by zhuzilinuser** [comment]
我用的是usb的无线鼠标。
➜  ~ xinput list-props 12
Device 'MOSART Semi. 2.4G Keyboard Mouse':
	Device Enabled (139):	1
	Coordinate Transformation Matrix (141):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	libinput Accel Speed (275):	0.000000
	libinput Accel Speed Default (276):	0.000000
	libinput Accel Profiles Available (277):	1, 1
	libinput Accel Profile Enabled (278):	1, 0
	libinput Accel Profile Enabled Default (279):	1, 0
	libinput Natural Scrolling Enabled (280):	0
	libinput Natural Scrolling Enabled Default (281):	0
	libinput Send Events Modes Available (259):	1, 0
	libinput Send Events Mode Enabled (260):	0, 0
	libinput Send Events Mode Enabled Default (261):	0, 0
	libinput Left Handed Enabled (282):	0
	libinput Left Handed Enabled Default (283):	0
	libinput Scroll Methods Available (284):	0, 0, 1
	libinput Scroll Method Enabled (285):	0, 0, 0
	libinput Scroll Method Enabled Default (286):	0, 0, 0
	libinput Button Scrolling Button (287):	2
	libinput Button Scrolling Button Default (288):	274
	libinput Middle Emulation Enabled (289):	0
	libinput Middle Emulation Enabled Default (290):	0
	Device Node (262):	"/dev/input/event2"
	Device Product ID (263):	1578, 16641
	libinput Drag Lock Buttons (291):	<no items>
	libinput Horizonal Scroll Enabled (264):	1
➜  ~ xinput list-props 11
Device 'MOSART Semi. 2.4G Keyboard Mouse':
	Device Enabled (139):	1
	Coordinate Transformation Matrix (141):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	libinput Send Events Modes Available (259):	1, 0
	libinput Send Events Mode Enabled (260):	0, 0
	libinput Send Events Mode Enabled Default (261):	0, 0
	Device Node (262):	"/dev/input/event1"
	Device Product ID (263):	1578, 16641
	libinput Horizonal Scroll Enabled (264):	0
➜  ~ xinput list-props 17
Device 'MOSART Semi. 2.4G Keyboard Mouse':
	Device Enabled (139):	1
	Coordinate Transformation Matrix (141):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	libinput Accel Speed (275):	0.000000
	libinput Accel Speed Default (276):	0.000000
	libinput Accel Profiles Available (277):	1, 1
	libinput Accel Profile Enabled (278):	1, 0
	libinput Accel Profile Enabled Default (279):	1, 0
	libinput Natural Scrolling Enabled (280):	0
	libinput Natural Scrolling Enabled Default (281):	0
	libinput Send Events Modes Available (259):	1, 0
	libinput Send Events Mode Enabled (260):	0, 0
	libinput Send Events Mode Enabled Default (261):	0, 0
	libinput Left Handed Enabled (282):	0
	libinput Left Handed Enabled Default (283):	0
	libinput Scroll Methods Available (284):	0, 0, 1
	libinput Scroll Method Enabled (285):	0, 0, 0
	libinput Scroll Method Enabled Default (286):	0, 0, 0
	libinput Button Scrolling Button (287):	2
	libinput Button Scrolling Button Default (288):	274
	libinput Middle Emulation Enabled (289):	0
	libinput Middle Emulation Enabled Default (290):	0
	Device Node (262):	"/dev/input/event2"
	Device Product ID (263):	1578, 16641
	libinput Horizonal Scroll Enabled (264):	0

**Comment by jouyouyun** [comment]
xf86-input-synaptics, xf86-input-mouse, xf86-input-evdev 这些有没有安装？

**Comment by zhuzilinuser** [comment]
都安装了。我直接安装了整个xorg组。

**Comment by jouyouyun** [comment]
Exec `yaourt -Rncs xf86-input-libinput` and reboot.

**Comment by zhuzilinuser** [comment]
xf86-input-libinput这个包是怎么回事，为什么卸载以后dde就显示鼠标的配置了。

**Comment by jouyouyun** [comment]
[libinput](https://freedesktop.org/wiki/Software/libinput/) 是一个处理输入设备的通用库，应该是为 Wayland 开发的，也支持 X.Org。

从目前的情况可以看出 xf86-input-libinput 的优先级很高，安装了它之后输入设备的驱动就会设置成它。

**Comment by zhuzilinuser** [comment]
原来如此，学习了。
