### ISSUE TITLE
 Pulseeffects stops working after manually changing the song.

### ISSUE THREAD

**Issue by shutterPL** [linuxdeepin/developer-center#570]
Here is my issue https://github.com/wwmm/pulseeffects/issues/240 and here is from other user https://github.com/wwmm/pulseeffects/issues/247. Both systems are Manjaro Deepin 17.1.10

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
