### ISSUE TITLE
Major bug on login screen with 15.6 upgrade

### ISSUE THREAD

**Issue by prowwid** [linuxdeepin/developer-center#571]
**So the problem is follwoing:**
with upgrade to 15.6 I faced a major problem on login screen with unability to change language to enter password. 

_When I login first thing I see is my first user and for this user I can swith languages as usual_
![step-1](https://user-images.githubusercontent.com/3070281/42040411-37450aee-7af8-11e8-9062-27bfa0be020f.jpg)

_But when I swith to a primary user I loose ability to select languages._
![step-2](https://user-images.githubusercontent.com/3070281/42040416-39aba680-7af8-11e8-8681-5e778c71ef70.jpg)
**And here comes the problem - really often language changes to a secondary one and you can't switch language because language menu isn't operable and there are no hotkeys awailable to switch language.**  

**Though I found a workaround to log in:**
- first log in to user you see first on the login screen
- than switch user to a second one and change language (menu become operable this way)
- than log out from first user and reboot the PC

After this steps second user's language return to the righ one.

**Another issue I faced is that on login screen I always see the first  created user but not hte one I logged-out last time.** 
So previously after reboot I always had a user I logged out last time on login screen but now not.

**Comment by hualet** [comment]
@kirigayakazushin

**Comment by kirigayakazushin** [comment]
I am thinking about how to support switch to the last logout user after starting greeter. The problem of empty of the keyboard list has been repaired.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
