### ISSUE TITLE
【deepin_V23_beta3】【一般】【有空】【集成测试】【DDE】【控制中心】系统更新，到进度到安装中时，安装进度一直显示为 100%

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#5712]
### SUMMARY | 问题概要

本问题对应的集成单号：https://github.com/linuxdeepin/developer-center/issues/5666

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
dde-session-ui 6.0.10
dde-session-shell 6.0.11
deepin-authenticate 1:2.0.3.1-1
```

### PRE-REQUIREMENT | 预置条件

1. 安装镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
2. 注释掉默认预装仓库

### STEPS TO REPRODUCE | 复现步骤

1. 添加仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-522/testing/ ./
2. 更新 
3. 开启默认仓库，解除默认仓库的注释 -  在控制中心里面更新系统 ，查看更新进度显示

### OBSERVED RESULT | 观察到的结果

3. 安装中的进度一直显示为 100%
![截图_选择区域_20230920131258](https://github.com/linuxdeepin/developer-center/assets/96416089/b4eeb8a4-9666-4e2c-9583-30e7d38c12e3)

### EXPECTED RESULT | 期望的结果

3.进度从 0 - 100% 有准确的进度显示

**Comment by babyfengfjx** [comment]
@asterwyx  请帮忙分析~

**Comment by asterwyx** [comment]
仅仅做了修改仓库的操作，不太可能影响到控制中心这边。这个一直显示100%是从点击更新就开始的吗？如果一安装系统之后什么也不干就开始更新呢？

**Comment by luodeepin** [comment]
当不添加转测仓库，升级对应的包，直接进行升级时到 安装中进度是有 0 -100%的进度提示的，而添加仓库升级了转测后，再进行更新时 在安装中时 就直接显示 100了

**Comment by asterwyx** [comment]
这个可以让控制中心看看，再怎么说包的内容也无法影响包的更新进度

**Comment by Decodetalkers** [comment]
和集成没关系，不要挂在这个集成上，交给控制中心看

**Comment by luodeepin** [comment]
嗯！只是是因为在没有添加这次集成升级时，在安装中时 是有 正常的进度显示的。
但是添加升级后，就出现了 安装中的进度显示的这个问题

**Comment by kegechen** [comment]
稍后回归测试

**Comment by luodeepin** [comment]
在最新环境中没有复现到此问题
