### ISSUE TITLE
kernel 6.5.4

### ISSUE THREAD

**Issue by matrix-wsk** [linuxdeepin/developer-center#5715]
### package information | 软件包信息

包名|版本
--|--
linux-headers-6.5.4-amd64-desktop-hwe | 6.5.4
linux-image-6.5.4-amd64-desktop-hwe | 6.5.4

### Package repository address | 软件包仓库地址

deb [trusted=yes] https://ci.deepin.com/repo/deepin/deepin-community/obs-repos/ kernel main

### changelog | 更新信息

上游stable版本更新
初步支持usb4和wifi7
 Btrfs 的性能进行了改进，以及其他存储优化
 AMD Radeon RX 7000 系列显卡进行了超频支持
 AMD 和英特尔图形驱动进行了各种优化和改进

### test suggestion | 测试建议

1、基本功能验证
系统启动基本功能测试，网卡、蓝牙、音频、视屏、休眠待机等常用场景测试
2、amd pstate支持较好
3、 USB4 v2 和 WiFi 7 的初步支持
4、ASUS ROG Ally 音效优化

**Comment by babyfengfjx** [comment]
@kobe337  请开展集成验证。

**Comment by kobe337** [comment]
已验证基本功能正常，包括内容： 注销、休眠电源管理验证; 控制-显示模块验证; 影音播放;音乐播放、相机等

目前存在问题如下
1、HUAWEI HKD-WXX (C233) Notebook 设备重启黑屏，已提交PMS单-220837; 
2、Dell Inc. XPS 9320 (0C10) Notebook笔记本音频无法识别，已提交PMS单-220679; （现状为音频已解决，相机驱动仍存在问题，相机无法识别）

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Beta2/
内核：Linux deepin918-PC 6.5.4-amd64-desktop-hwe #2 SMP PREEMPT_DYNAMIC Wed Sep 20 11:35:35 CST 2023 x86_64 GNU/Linux
【结论】：
测试不通过，存在问题 https://github.com/deepin-community/kernel/issues/29  https://github.com/deepin-community/kernel/issues/28;  https://github.com/deepin-community/kernel/issues/30
