### ISSUE TITLE
Integrated org.deepin.browser

### ISSUE THREAD

**Issue by kamiyadm** [linuxdeepin/developer-center#5716]
### package information | 软件包信息

org.deepin.browser | 6.0.23
-- | --

### Package repository address | 软件包仓库地址

仓库地址：http://10.0.36.228:9001/
更换地址：ll-cli repo modify http://10.0.36.228:9001/ --name develop-snipe

### test suggestion | 测试建议

将浏览器6.0.22版本，升级至6.0.23。

安装linglong-bin，sudo apt install linglong-bin
修改仓库地址，ll-cli repo modify http://10.0.36.228:9001/ --name develop-snipe
安装浏览器，ll-cli install org.deepin.browser
运行浏览器，测试能否满足日常使用; 如长时间使用是否闪退， 能否正常播放视频等。

**Comment by kamiyadm** [comment]
@babyfengfjx

**Comment by vivianxf** [comment]
验证通过,请及时上到正式环境:

1.仓库升级成功
2.浏览器版本升级成功
3.在浏览器播放音乐,视频,直播均无闪退情况


综上所述,本次集成通过
