### ISSUE TITLE
Deepin snapping/tiling windows

### ISSUE THREAD

**Issue by ag14774** [linuxdeepin/developer-center#573]
I would like to bring your attention to this bug here:
https://forum.manjaro.org/t/deepin-snapping-windows/47720/4

Is what I'm describing there by design or is it a bug?

**Comment by r3r57** [comment]
I also encountered the problem that I am unable to stack properly tiled windows to the left or right, since only one windows seems to be allowed to be tiled to the left or right when using the mouse or touchpad.

On the other hand it's no problem to tile several windows at once to the left or right when using keyboard shortcuts.

**Comment by aiamuzz** [comment]
> On the other hand it's no problem to tile several windows at once to the left or right when using keyboard shortcuts.

@r3r57 ...
are you running Deepin OS ?
could please share how you have setup tiling of windows to the left or right using keyboard shortcuts ?

**Comment by r3r57** [comment]
I'm running Manjaro and set up the key bindings in the dconf editor as described in the link above.
Unfortunately I was wrong. Tiling a window to the left or right using keyboard shortcuts doesn't work if another window is already tiled/snapped to corresponding side.

![](https://login.yoursecurecloud.de/seafhttp/files/e5b5b54d-9012-4bff-89e9-ed7adf71b453/deepin-wm-tiling.gif)

**Comment by sonald** [comment]
@ag14774  This is due to an unfinished new feature called 'interactive dual tiling' (similar to what windows 10 has). only one window will be allowed on either side of screen.

**Comment by ag14774** [comment]
@sonald Is there an option to turn this off? Cause I have Windows 10 and it allows for multiple windows on each side(at least this is the default).

**Comment by ag14774** [comment]
@sonald Ah okay no problem. Thanks

**Comment by ag14774** [comment]
@sonald I hate to make requests, but any chance this can become a priority? It kind of hurts productivity to have unfinished features.

**Comment by ag14774** [comment]
Any updates on this?

**Comment by ag14774** [comment]
Closing this since I am no longer planning on using Deepin. It has gotten worse during the last months. First there was this problem, then the dock started hanging up + its design was changed for the worse. Switched to good old Gnome.

**Comment by igormcoelho** [comment]
@aiamuzz Just to register here, these are the shortcuts I use for Tile Left and Tile Right, that work fine on deepin 15.9.2

Tile Left ( I use shortcut Super + <- )
`qdbus com.deepin.wm /com/deepin/wm com.deepin.wm.TileActiveWindow 1`

Tile Right ( I use shortcut Super + -> )
`qdbus com.deepin.wm /com/deepin/wm com.deepin.wm.TileActiveWindow 2`

Thanks to some random guy on the internet that found these commands.

**Comment by sonald** [comment]
actually, I think I had indicated these dbus operations somewhere, but I can not recall. these dbus operations are not documented since its primary usage is to cooperate with DDE components. 
BTW: you guys can send feature requests directly to the project under linuxdeepin. we have shifted our developing process entirely based on Github.

**Comment by sonald** [comment]
FYI we are moving from deepin-wm to dde-kwin, which is not feature complete yet.

**Comment by aiamuzz** [comment]
> FYI we are moving from deepin-wm to dde-kwin, which is not feature complete yet.

@sonald ...

i was wondering will the users be able to choose between deepin-wm and dde-kwin after its implemented ?

will deepin-wm be developed simultaneously along with dde-kwin ?

I hope deepin-wm will not be removed/deleted ... in the least i hope it will be frozen to its last working release ... so if anybody dislikes dde-kwin they can always go back to deepin's original WM ... ?

I did try briefly kwin on plasma ... and i felt our deepin-wm was much more simpler, efficient and effective ... kwin may have a loooooot of features **but deepin-wm rates highly on the KISS philosophy** ... and the simple things always trump complex things.

I hope deepin-wm is NOT decommissioned fully ... a parallel step-down development would be great but keeping it functional and as an option to the users to at least use its last release would be appreciated !!!

**Comment by sonald** [comment]
@aiamuzz  Thanks for such compliment. I believe dde-kwin will replace deepin-wm as the main wm in the following big release, but no soon. they will co-exist for a long period, and deepin-wm will remain as an option for you.

the truth is I'm working in the middle of something else, and incapable of maintaining deepin-wm for new features now, and so only critical issues will be handled.

**Comment by aiamuzz** [comment]
> they will co-exist for a long period, and deepin-wm will remain as an option for you.
> 
> the truth is I'm working in the middle of something else, and incapable of maintaining deepin-wm for new features now, and so only critical issues will be handled.

@sonald ... great deepin-wm should never be decommissioned because its the original DeepinOS WM ... and we have been drawn to DeepinOS because of its simplicity ... and kwin will never qualify for 'simplicity' ... so you handling only critical issues is more than sufficient ... **I sincerely hope deepin-wm will always be a part of DeepinOS as an additional option !!!**

**Comment by igormcoelho** [comment]
what is dde-kwin, is it a window manager similar to the one currently in use by deepin?
I hope the interface keeps nice as it is... this is the prettiest system I've even seen, and I'm a long time user of linux and most of its families. I convinced my entire university department to shift to deepin because of this awesome window manager, which is quite simple. Congratulations anyway for the good job.

**Comment by sonald** [comment]
@zccrs @hualet  will you plz present some design decisions behind dde-kwin? 
@aiamuzz @igormcoelho  thanks, we appreciate it very much.  when I got time, I'll port deepin-wm and deepin-mutter to utilize the lastest mutter.

**Comment by aiamuzz** [comment]
> I hope the interface keeps nice as it is... this is the prettiest system I've ever seen (and everybody who sees my screen always asks me what is it that I'm using). I convinced my university computing department to shift to deepin in some laboratories because of this awesome window manager, which is quite simple for regular users. Congratulations anyway for the good job.

Exactly ... people often ask that question ... it is the prettiest system ...

> @zccrs @hualet will you plz present some design decisions behind dde-kwin?
> @aiamuzz @igormcoelho thanks, we appreciate it very much. when I got time, I'll port deepin-wm and deepin-mutter to utilize the lastest mutter.

@sonald ... trust me people would not have called the current version of Deepin OS running kwin as the prettiest for sure ...

Deepin Team has to realize that mutter based Deepin WM should be much more than ... "When I got time" ... its your selling point for god sake ... its your face your signature that draws new users ... you can't give that a "When I got time" treatment !!!

mutter based Deepin WM needs to be retained ... kwin can be an additional option until it also can draw similar reactions "its the prettiest" ... until then mutter based DeepinWM SHOULD be the default ... 

**If kwin can help create this exact same look, feel and flow as we have with deepin-WM ... then you need to start work on recreating it ... until then you can't change the face and say the body is the same one !!!**

**A little disappointed with Deepin-Teams major UI/UX changes ... what's the point of a change that renders it unidentifiable completely !!!**
