### ISSUE TITLE
dde-lock & deepin-kwin spam log while screen is locked

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#5738]
### SUMMARY | 问题概要

dde-lock and deepin-kwin are spamming logs while the screen is locked. This is unnecessary and unfriendly to users' hard drives.

<img width="650" alt="image" src="https://github.com/linuxdeepin/developer-center/assets/1006477/45d25309-4fc7-4442-bb08-036bd7c8a740">

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
Arch Linux x86_64
deepin-kwin 5.25.11-1
deepin-session-shell 6.0.9-1
```

### STEPS TO REPRODUCE | 复现步骤

Lock screen and watch journal from another session or SSH.

**Comment by asterwyx** [comment]
Has been fixed.
