### ISSUE TITLE
'Settings' entry in mini-launcher

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/developer-center#575]
I just noticed that, when using the launcher in mini-mode there is an entry 'Settings' and that on Manjaro it does nothing... :wink: 
Could you kindly let us know what it is supposed to launch and how?
Thanks.

**Comment by felixonmars** [comment]
On Arch it pops out the control center.

The journal suggests it's activating the control center via dbus using qdbus command:
```
Jul 13 21:47:18 flygon.felixc.at dbus-daemon[1119]: [session uid=1000 pid=1119] Activating service name='com.deepin.dde.ControlCenter' requested by ':1.318' (uid=1000 pid=23501 comm="/usr/bin/qdbus --literal com.deepin.dde.ControlCen")
```

**Comment by oberon-manjaro** [comment]
Hm. Strange. I can see entries for any application I launch, but for the settings button I get nothing in journal.
What could be different in our environment?

**Comment by oberon-manjaro** [comment]
`/usr/bin/qdbus --literal com.deepin.dde.ControlCen`

A directory **/usr/bin/qdbus** doens't exist on my install! :stuck_out_tongue_winking_eye:

**Comment by oberon-manjaro** [comment]
Ok. Obviously **qt5-tools** needs to be a dependency of one of the Deepin pkgs. It is needed.
When I install it manually, the settings entry works.

**Comment by oberon-manjaro** [comment]
it's a makedepends of several deepin packages but apparently none of them installs is as a depends.

**Comment by oberon-manjaro** [comment]
Thank you! :smiley:
