### ISSUE TITLE
Calculator error

### ISSUE THREAD

**Issue by ghost** [linuxdeepin/developer-center#576]
Hello there! I don't know english very well, but I will try! 🗡 

I'm a DeepinOS user from Brazil. My question and of many other people in here is the problems with Deepin-calculator. When we try to sum or anything, the result is showing an error.

See this link:

https://forum.manjaro.org/uploads/default/original/3X/6/c/6cd0c9b50422f5830b24a830225209c7b988e045.png

**It's not our result pattern!

The result of an sum should be like this:

23,920 + 800 = 823,92 (that's is the right way to show in our country math pattern)

And not like that:

23,920 + 800 = 2,392e+82**

**Comment by felixonmars** [comment]
@haruyukilxz The decimal point needs to support i18n.

**Comment by Whermerson** [comment]
When I use point it's showing the same error!

**Comment by haruyukilxz** [comment]
I can't repeat it.   

![_ _20180716175359](https://user-images.githubusercontent.com/12298476/42752718-5fcb22c8-8921-11e8-8ff9-7d9d4d89c4ca.png)

**Comment by random2324** [comment]
I have exactly the same issue.
![deepinbildschirmfoto_20180716132142](https://user-images.githubusercontent.com/19872920/42756172-4cf4911e-88fb-11e8-9ff9-f8f8a2031e7c.png)

**Comment by random2324** [comment]
![deepinbildschirmfoto_20180723100903](https://user-images.githubusercontent.com/19872920/43064925-9486f606-8e60-11e8-9caa-6f4a07ea174d.png)

Very strange. 1.04 installed by pacman but 1.01 showing in the version info.

**Comment by SoftDicas** [comment]
I found the error! Just install the default deepin-calculator and uninstall the flatpak deepin-calculator.

**Comment by random2324** [comment]
There was a update to 1.06 which fixed the calculation error seeing above. Still two issues:

1) The version of the calculator is still just showing as 1.0.1.

2) The Calculator incorrectly mixes dots and commas.
If you want to display one thousand, the correct result would be 1.000. But the calculator does 1,000 which is just a one.

**Comment by rekols** [comment]
1. r u install flatpak version ?
2. deepin calculator defaults to using a comma as a thousands separator  (

**Comment by rekols** [comment]
thx, so need to customize a thousands separator?

**Comment by random2324** [comment]
It would be great if Deepin could pay some attention to the region where its getting used. 
I think Deepin has no locale setting but it probably needs to implement this.
Maybe it would be also sufficient to guess the locale by the used system language.

Anyway for the calculator you would need to do something like that:
ten thousand = 10.000
ten-thousand and zero point five = 10.000,5

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
