### ISSUE TITLE
deepin WSL 上架微软应用商店前测试

### ISSUE THREAD

**Issue by chenchongbiao** [linuxdeepin/developer-center#5771]
### package information | 软件包信息

包名 | 版本
-- | --
deepin WSL | 1.0.1.0

### Package repository address | 软件包仓库地址

https://github.com/deepin-community/deepin-WSL/releases

### changelog | 更新信息

deepin WSL 使用官方提供启动器编写。
上次测试为 wsldl 第三方工具，https://github.com/deepin-community/deepin-rootfs
本地使用微软官方提供的，项目为 https://github.com/deepin-community/deepin-wsl

比较：
wsldl 新安装一个 WSL 只需要对应的根文件系统，以及重命名一个可执行文件，使用通用工具来运行一个实例。需要自己使用命令导入根文件系统，另外默认使用root用户，需要自己手动配置其他用户来使用。

官方提供的启动器，需要将根文件系统一起打包成 Windows 下的可执行程序，另外用来上架应用商店也需要依赖程序。双击运行可执行程序，安装成功后提示创建一个新用户。

### test suggestion | 测试建议

版本要求：
  - 对于 x64 系统：版本 1903 或更高版本，内部版本 18362 或更高版本。
  - 对于 ARM64 系统：版本 2004 或更高版本，内部版本 19041 或更高版本。
最好直接把 Windows 系统直接更新到最新。

1.测试在 Windows 11 和 Windows 10 是否能正常安装程序。（如果有arm 版的 Windows 系统可尝试安装）。
2.查看 Windows 下菜单栏上的图标是否正常。

步骤：
1.在控制面板，程序开启和关闭，打开“适用于Linux的Windows子系统”和“虚拟机平台”两个可选功能。
2.安装WSL（使用WSL)
```bash
wsl --update
wsl --set-default-version 2
```
3.选择安装 cer 证书，选择选择“本地计算机”和“受信任的根证书颁发机构
4.安装 appxbundle 程序

### Sphere of influence | 影响范围

无

### ADDITIONAL INFORMATION | 额外补充

无

**Comment by babyfengfjx** [comment]
@SuperEffie  请参考上述测试建议，覆盖windows10 和 windows11的使用场景。

**Comment by SuperEffie** [comment]
【测试结论】：测试通过，请走下一步流程~
验证windows 10和windows 11系统中正常安装deepin wsl。具体操作步骤可参考issue:#5802 、#5803
【备注信息】：
1. 若在windows 10 系统中安装deepin wsl，需在设置中将系统更新
2. windows 10与windows 11系统中，均需在控制面板，程序开启和关闭，打开“适用于Linux的Windows子系统”和“虚拟机平台”两个可选功能，后对wsl进行更新：`wsl --update`、`wsl --set-default-version 2`
3. 与研发同学沟通，在deepin wsl上架Microsoft store后，应用下载时会自动完成步骤2

**Comment by babyfengfjx** [comment]
@chenchongbiao  请推进后续流程，商家到微软商店。

**Comment by chenchongbiao** [comment]
已经上架，微软商店了，
帖子：https://bbs.deepin.org/zh/post/263672?id=263672&limit=20&offset=0&postId=1527518
