### ISSUE TITLE
Obfuscated VPN servers

### ISSUE THREAD

**Issue by ag14774** [linuxdeepin/developer-center#578]
I am trying to use an obfuscated VPN server that uses the 'scramble' option in the config file. I found out that I need to install `openvpn` compiled with the XOR patch. I removed `openvpn` and then installed it with the XOR patch. Now, even though I can connect to the server using the terminal and `openvpn` recognizes the 'scramble obfuscate' option in the file, if I import the config file from the control center, I get a connection timed out error. Is the control center using a different `openvpn` binary than the one that is installed?

**Comment by hualet** [comment]
@felixonmars

**Comment by felixonmars** [comment]
@hualet I don't think it's a different binary. But does the control center import the config correctly? Can we examine it somehow?

**Comment by hualet** [comment]
@jouyouyun

**Comment by felixonmars** [comment]
The control center uses networkmanager to manage openvpn connections. Looks like networkmanager-openvpn has a static list of accepted configuration options [1], which won't include obfs. I don't know how dde-daemon managed to import the config, but it doesn't look like supported anyway.

[1] https://gitlab.gnome.org/GNOME/NetworkManager-openvpn/blob/master/properties/import-export.c

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
