### ISSUE TITLE
The checksum links on the download pages should be updated

### ISSUE THREAD

**Issue by Red54** [linuxdeepin/developer-center#5785]
### SUMMARY | 问题概要

![image](https://github.com/linuxdeepin/developer-center/assets/2240638/39615319-991e-483f-9109-6cee265219b3)

The checksum links of deepin V23 Beta2(Unstable) on the download pages (en and zh) are still for deepin V23 Beta(Unstable).

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin V23 Beta2(Unstable)
```

### STEPS TO REPRODUCE | 复现步骤

https://www.deepin.org/en/download/

https://www.deepin.org/zh/download/

**Comment by myml** [comment]
I have addressed the issues and corrected the broken links. Please feel free to let me know if there's anything else that needs attention.

Thanks again for your assistance!
