### ISSUE TITLE
Bug after update

### ISSUE THREAD

**Issue by denisoster** [linuxdeepin/developer-center#579]
ArchLinux + DDE
- After login system loading 2 MINUTES
- Not working hotkeys change keyboard

Last updated package

`[2018-07-20 22:11] [ALPM] upgraded deepin-api (3.1.26-1 -> 3.1.27-1)`
`[2018-07-20 22:11] [ALPM] upgraded deepin-qt-dbus-factory (1.0.2-3 -> 1.0.3-1)`
`[2018-07-20 22:11] [ALPM] upgraded dtkcore (1:2.0.8.1-2 -> 1:2.0.9-1)`
`[2018-07-20 22:11] [ALPM] upgraded dtkwidget (2.0.8.1-4 -> 2.0.9-1)`
`[2018-07-20 22:11] [ALPM] upgraded deepin-qt5integration (0.3.0-3 -> 0.3.1-1)`
`[2018-07-20 22:11] [ALPM] upgraded deepin-sound-theme (15.10.2-1 -> 15.10.3-1)`
`[2018-07-20 22:11] [ALPM] upgraded papirus-icon-theme (20180601-1 -> 20180720-1)`
`[2018-07-20 22:11] [ALPM] upgraded deepin-desktop-schemas (3.2.14-1 -> 3.2.15-1)`
`[2018-07-20 22:11] [ALPM] upgraded deepin-menu (3.3.8-1 -> 3.3.10-1)`
`[2018-07-20 22:11] [ALPM] upgraded deepin-mutter (3.20.30-1 -> 3.20.31-1)`
`[2018-07-20 22:11] [ALPM] upgraded deepin-wm (1.9.28-1 -> 1.9.29-1)`
`[2018-07-20 22:11] [ALPM] upgraded deepin-session-ui (4.4.5-3 -> 4.4.6-2)`
`[2018-07-20 22:11] [ALPM] upgraded deepin-control-center (4.5.5-1 -> 4.6.0-1)`
`[2018-07-20 22:11] [ALPM] upgraded deepin-launcher (4.3.10-3 -> 4.4.1-1)`
`[2018-07-20 22:11] [ALPM] upgraded deepin-dock (4.6.6-2 -> 4.6.7-1)`
`[2018-07-20 22:11] [ALPM] upgraded dtkwm (2.0.8.1-3 -> 2.0.9-1)`
`[2018-07-20 22:11] [ALPM] upgraded deepin-editor (0.0.4-1 -> 0.0.5-1)`
`[2018-07-20 22:11] [ALPM] upgraded deepin-image-viewer (1.2.22-1 -> 1.2.23-1)`
`[2018-07-20 22:11] [ALPM] upgraded deepin-movie (1:3.2.7-1 -> 1:3.2.8-1)`
`[2018-07-20 22:11] [ALPM] upgraded deepin-terminal (3.0.0-2 -> 3.0.1-1)`
`[2018-07-20 22:14] [ALPM] upgraded skypeforlinux-preview-bin (8.26.76.60-1 -> 8.27.76.16-1)
`

**Comment by denisoster** [comment]
cast @felixonmars

**Comment by denisoster** [comment]
Today update

**Comment by felixonmars** [comment]
You may want to lookup the journal to find out what keeps the daemon from loading. For me it was pulseaudio and daemon.audio that takes >20s and blocks other things to load:

```
Jul 21 19:45:55 flygon.felixc.at daemon/audio[1268]: daemon.go:64: Failed to connect pulseaudio server
                                                       ->  module.go:62
                                                       ->  module.go:65
                                                       ->  module.go:77
                                                       ->  loader.go:153
                                                       ->  global.go:71
                                                       ->  daemon.go:120
                                                       ->  daemon.go:129
                                                       ->  main.go:103
                                                       ->  proc.go:198
                                                       ->  asm_amd64.s:2361
Jul 21 19:45:55 flygon.felixc.at daemon/loader[1268]: loader.go:159: enable module audio done, cost 23.93280529s
```

**Comment by denisoster** [comment]
@felixonmars please tell me which commands I should run

**Comment by flubbe** [comment]
I have the same waiting issue after the latest update (also ArchLinux + DDE). The journal reports

`dbus-daemon[859]: [session uid=1000 pid=859] Failed to activate service 'com.deepin.dde.Welcome': timed out (service_start_timeout=120000ms)`

My last (deepin-related) package upgrade:

`[2018-07-20 23:04] [ALPM] upgraded deepin-api (3.1.26-1 -> 3.1.27-1)`
`[2018-07-20 23:04] [ALPM] upgraded deepin-qt-dbus-factory (1.0.2-3 -> 1.0.3-1)`
`[2018-07-20 23:04] [ALPM] upgraded dtkcore (1:2.0.8.1-2 -> 1:2.0.9-1)`
`[2018-07-20 23:04] [ALPM] upgraded dtkwidget (2.0.8.1-4 -> 2.0.9-1)`
`[2018-07-20 23:04] [ALPM] upgraded deepin-qt5dxcb-plugin (1.1.9.1-1 -> 1.1.9.2-1)`
`[2018-07-20 23:04] [ALPM] upgraded deepin-qt5integration (0.3.0-3 -> 0.3.1-1)`
`[2018-07-20 23:04] [ALPM] upgraded deepin-sound-theme (15.10.2-1 -> 15.10.3-1)`
`[2018-07-20 23:04] [ALPM] upgraded deepin-desktop-schemas (3.2.14-1 -> 3.2.15-1)`
`[2018-07-20 23:04] [ALPM] upgraded deepin-menu (3.3.8-1 -> 3.3.10-1)`
`[2018-07-20 23:04] [ALPM] upgraded deepin-mutter (3.20.30-1 -> 3.20.31-1)`
`[2018-07-20 23:04] [ALPM] upgraded deepin-wm (1.9.28-1 -> 1.9.29-1)`
`[2018-07-20 23:04] [ALPM] upgraded deepin-session-ui (4.4.5-3 -> 4.4.7-1)`
`[2018-07-20 23:04] [ALPM] upgraded deepin-control-center (4.5.5-1 -> 4.6.1-1)`
`[2018-07-20 23:04] [ALPM] upgraded deepin-launcher (4.3.10-3 -> 4.4.1-1)`
`[2018-07-20 23:04] [ALPM] upgraded deepin-dock (4.6.6-2 -> 4.6.7-1)`
`[2018-07-20 23:04] [ALPM] upgraded dtkwm (2.0.8.1-3 -> 2.0.9-1)`
`[2018-07-20 23:04] [ALPM] upgraded deepin-editor (0.0.4-1 -> 0.0.5-1)`
`[2018-07-20 23:04] [ALPM] upgraded deepin-image-viewer (1.2.22-1 -> 1.2.23-1)`
`[2018-07-20 23:04] [ALPM] upgraded deepin-movie (1:3.2.7-1 -> 1:3.2.8-1)`
`[2018-07-20 23:04] [ALPM] upgraded deepin-terminal (3.0.0-2 -> 3.0.1-1)`


packages that were removed:

`[2018-07-20 23:04] [ALPM] removed deepin-notifications (3.3.4-2)
`

**Comment by felixonmars** [comment]
Please try again with startdde 3.1.33.20180720-1.

**Comment by denisoster** [comment]
Thank you very much.
Ticket closed.
