### ISSUE TITLE
File Manager shows empty directories everywhere "Folder is empty"

### ISSUE THREAD

**Issue by JKJameson** [linuxdeepin/developer-center#5790]
### SUMMARY | 问题概要

The dde-file-manager shows "Folder is empty" for every possible path.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
Distribution: Arch Linux
Package: 1:6.0.31-2
```

### STEPS TO REPRODUCE | 复现步骤

1. open the file manager
2. click on home directory
3.  folder is empty

### OBSERVED RESULT | 观察到的结果

folder is empty

### EXPECTED RESULT | 期望的结果

files shown

### ADDITIONAL INFORMATION | 额外补充

"recent files" are the only option that shows files

Journalctl log : https://pastebin.com/j8xf7zqi

home directory is mounted

[josh@jjws ~]$ mount | grep home
/dev/mapper/vg1-home on /home type ext4 (rw,relatime)

[josh@jjws ~]$ stat /home
  File: /home
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 254,1   Inode: 2           Links: 4
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-10-05 03:51:47.278099816 +0100
Modify: 2023-10-05 03:31:31.542084141 +0100
Change: 2023-10-05 03:31:31.542084141 +0100
 Birth: 2023-10-05 03:29:53.000000000 +0100

[josh@jjws ~]$ stat /home/josh
  File: /home/josh
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 254,1   Inode: 21757953    Links: 44
Access: (0750/drwxr-x---)  Uid: ( 1000/    josh)   Gid: ( 1000/    josh)
Access: 2023-10-05 18:12:09.670295121 +0100
Modify: 2023-10-05 17:30:52.890228653 +0100
Change: 2023-10-05 17:30:52.890228653 +0100
 Birth: 2023-10-05 03:31:31.542084141 +0100

[josh@jjws ~]$ id
uid=1000(josh) gid=1000(josh) groups=1000(josh)

**Comment by BLumia** [comment]
ref: https://github.com/linuxdeepin/developer-center/issues/5725

**Comment by BLumia** [comment]
Should be fixed in `deepin-file-manager 1:6.0.31-4` :)
