### ISSUE TITLE
[Deepin Integration]~[V23-Beta3] integrate: v23社区版备份还原6.0.16-20231007

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#5794]
### Package information | 软件包信息

包名 | 版本
--  | --
uos-recovery | 6.0.16-1

### Package repository address | 软件包仓库地址

   deb  [trusted=yes] https://aptly.uniontech.com/pkg/nonfree-beige-v2/release-candidate/djIz56S-5Yy654mI5aSH5Lu96L-Y5Y6fNi4wLjE2LTIwMjMxMDA3MjAyMy0xMC0wNyAxMDowMDoyMw/  unstable non-free

#### uos-recovery (6.0.16-1) unstable; urgency=medium

  * bug fix 

### Test suggestion | 测试建议
https://pms.uniontech.com/bug-view-216167.html  
https://pms.uniontech.com/bug-view-216175.html 
https://pms.uniontech.com/bug-view-198055.html   
https://pms.uniontech.com/bug-view-195981.html   
https://pms.uniontech.com/bug-view-167901.html   

### Influence | 影响范围
备份还原相关功能

**Comment by babyfengfjx** [comment]
@xuqi27837288   将备份还原进行系统的测试，覆盖，全盘安装、勾选/不勾选初始备份、多系统安装、多种安装场景。

**Comment by xuqi27837288** [comment]
【环境】：
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230927
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【结论】：
测试通过，暂无严重问题及影响
