### ISSUE TITLE
【deepin_V23_beta3】【一般】【有空】【内测反馈】【DDE】 拖动控制中心窗口后，鼠标划过特定元素时,没有高亮显示

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#5798]
### SUMMARY | 问题概要

 拖动控制中心窗口后，鼠标划过特定元素时,没有高亮显示

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
1.https://cdimage.uniontech.com/community/releases/23-Beta2/deepin-desktop-community-23-Beta2-amd64.iso
2.dde-control-center:6.0.28
```

### STEPS TO REPRODUCE | 复现步骤

1.打开控制中心-电源-通用
2.使用鼠标划过性能模式,观察鼠标划过时每个模块都有高亮提示
3.鼠标选中控制中心窗口,挪动控制中心位置
4.重复步骤2.观察鼠标划过时,模块是否有高亮提示

### OBSERVED RESULT | 观察到的结果

1.拖动控制中心窗口后，鼠标划过特定元素时,没有高亮显示

https://github.com/linuxdeepin/developer-center/assets/96415804/bba9859e-477b-4df1-82f2-969096e66e8f

### EXPECTED RESULT | 期望的结果

1.拖动控制中心窗口后，鼠标划过特定元素时,有高亮显示

**Comment by babyfengfjx** [comment]
@kegechen   请安排优化~

**Comment by kegechen** [comment]
插件改过了，见集成 #6455

**Comment by kegechen** [comment]
回归测试一下 @vivianxf

**Comment by vivianxf** [comment]
验证镜像:https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240108/deepin-23-beige-beta3-amd64-20240108-145003.iso
验证版本:dde-control-center:6.0.37
验证步骤:提单的步骤
验证现象:拖动控制中心窗口后,鼠标划过特定元素可以高亮显示
验证结果:通过
