### ISSUE TITLE
[archlinux] 右上角消息提示有字体大小问题

### ISSUE THREAD

**Issue by zhuzilinuser** [linuxdeepin/developer-center#58]
![deepinscreenshot20160306172428](https://cloud.githubusercontent.com/assets/12298476/13553342/03e513d6-e3c1-11e5-93dc-353d0ca24026.png)
我的字体设置如下，中英我都试过了，我改动字号似乎也没用。会不会是因为kde的某些设置，然后冲突了。
![deepinscreenshot20160306172854](https://cloud.githubusercontent.com/assets/12298476/13553343/040d5256-e3c1-11e5-8268-0bb87bf188e5.png)

**Comment by fasheng** [comment]
我猜测是arch上的问题 ;)
@jouyouyun

**Comment by zhuzilinuser** [comment]
arch的问题，不知道怎么的，又搞好了
