### ISSUE TITLE
(Arch Linux) Firefox default browser

### ISSUE THREAD

**Issue by Xeers** [linuxdeepin/developer-center#580]
I want to set Chromium as my default browser but whenever I log in it changes it to Firefox. (Control center> Default applications> Browser).
------------------------------
After the last updates the display manager to log in takes several minutes to show the Deepin desktop.

---------------------------------
Redshift (Night mode) it does not work correctly. 
"Failed to run Redshift. Trying location provider 'geoclue2'...Waiting for initial location to become available...Unable to start GeoClue client: GDBus.Error:org.freedesktop.DBus.Error.NoReply:Message recipient disconnected from message bus without replying. Unable to get location from provider.

**Comment by felixonmars** [comment]
The loading issue should have been fixed in startdde 3.1.33.20180720-1.
The latter is a known issue of redshift: https://github.com/jonls/redshift/issues/636

**Comment by Xeers** [comment]
Thanks
