### ISSUE TITLE
【deepin_V23_beta3】【严重】【立即】【集成测试】【wsl】windows10系统中，deepin wsl安装失败

### ISSUE THREAD

**Issue by SuperEffie** [linuxdeepin/developer-center#5802]
### SUMMARY | 问题概要

【关联集成】：https://github.com/linuxdeepin/developer-center/issues/5771

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
【系统版本】：windows 10 
【版本信息】：deepin WSL：1.0.1.0
```

### PRE-REQUIREMENT | 预置条件

安装windows系统
下载文件至本地：
1. [deepinWSL-Appx_1.0.1.0_x64.appxbundle](https://github.com/deepin-community/deepin-WSL/releases/download/v1.0.1.0-x64/deepinWSL-Appx_1.0.1.0_x64.appxbundle)
2. [deepinWSL-Appx_1.0.1.0_x64.cer](https://github.com/deepin-community/deepin-WSL/releases/download/v1.0.1.0-x64/deepinWSL-Appx_1.0.1.0_x64.cer)

### STEPS TO REPRODUCE | 复现步骤

1、双击安装cer证书
2、双击安装deepin wsl，观察是否能正常安装

### OBSERVED RESULT | 观察到的结果

显示安装失败
<img width="962" alt="wsl安装失败" src="https://github.com/linuxdeepin/developer-center/assets/58986464/b20b72c8-209d-4e02-aadc-bdfbe0d8d34d">

### EXPECTED RESULT | 期望的结果

成功安装deepin wsl 

### ADDITIONAL INFORMATION | 额外补充

安装cer证书可参考在线文档：[Windows平台下安装证书文件cer的步骤](https://blog.51cto.com/jeecg/3196763#:~:text=%E6%96%B9%E6%B3%95%2F%E6%AD%A5%E9%AA%A4%201%201%20%E4%B8%8B%E8%BD%BD%E5%AE%8C%E6%88%90%E5%90%8E%EF%BC%8C%E5%8F%8C%E5%87%BB%E8%BF%90%E8%A1%8CYanyuCorp.cer%EF%BC%8C%E6%95%88%E6%9E%9C%E5%A6%82%E4%B8%8B%E5%9B%BE%EF%BC%9A%202%202,%E9%80%89%E6%8B%A9%E5%AE%89%E8%A3%85%E8%AF%81%E4%B9%A6%EF%BC%8C%E8%BF%99%E4%B8%AA%E6%97%B6%E5%80%99%E5%92%8C%E4%BD%A0%E7%94%B5%E8%84%91%E4%B8%8A%E5%AE%89%E8%A3%85%E7%9A%84%E5%85%B6%E4%BB%96%E8%BD%AF%E4%BB%B6%E6%B2%A1%E6%9C%89%E5%85%B3%E7%B3%BB%EF%BC%8C%E8%87%B3%E4%BA%8E%E7%88%B1%E5%8D%9A%E9%82%AE%E4%BB%B6%E7%BE%A4%E5%8F%91%E7%B3%BB%E7%BB%9F%E5%92%8C%E7%88%B1%E5%8D%9AEmail%E6%90%9C%E7%B4%A2%E5%9C%A3%E6%89%8B%E6%98%AF%E5%90%A6%E6%98%AF%E6%89%93%E5%BC%80%E7%8A%B6%E6%80%81%E6%B2%A1%E6%9C%89%E4%BB%BB%E4%BD%95%E5%85%B3%E7%B3%BB%E3%80%82%203%203%20%E7%BB%A7%E7%BB%AD%E2%80%9C%E4%B8%8B%E4%B8%80%E6%AD%A5%E2%80%9D%EF%BC%8C%E6%8C%89%E7%85%A7%E4%B8%8B%E5%9B%BE%E6%95%B0%E5%AD%97%E6%A0%87%E7%A4%BA%E7%9A%84%E6%AD%A5%E9%AA%A4%E9%80%89%E6%8B%A9%E8%AF%81%E4%B9%A6%E6%96%87%E4%BB%B6%E7%9A%84%E5%AE%89%E8%A3%85%E4%BD%8D%E7%BD%AE%EF%BC%9A%204%204%20Windows%E4%BC%9A%E5%BC%B9%E5%87%BA%E4%B8%80%E4%B8%AA%E5%AE%89%E5%85%A8%E6%8F%90%E7%A4%BA%E6%A1%86%EF%BC%8C%E5%86%85%E5%AE%B9%E5%A6%82%E4%B8%8B%EF%BC%8C%E9%80%89%E6%8B%A9%E2%80%9C%E6%98%AF%E2%80%9D%E5%8D%B3%E5%8F%AF%E3%80%82)

**Comment by babyfengfjx** [comment]
@chenchongbiao  请优先分析处理。

**Comment by chenchongbiao** [comment]
需要将 win10 系统进行更新到，该版本不支持 wsl2, 另外在设置控制面板

  - 在控制面板，程序开启和关闭，打开“适用于Linux的Windows子系统”和“虚拟机平台”两个可选功能。
  - 需要在Vmware设置中为Windows虚拟机启用嵌套虚拟化，即勾选“启用VT-x/AMD-V”和“启用嵌套分页”选项。
- 安装WSL（使用WSL)
  - `wsl --update`
  - `wsl --set-default-version 2`

**Comment by SuperEffie** [comment]
【操作步骤】：
1. 安装windows 10 系统，设置中更新系统
2. 在控制面板，程序开启和关闭，打开“适用于Linux的Windows子系统”和“虚拟机平台”两个可选功能
3. wsl进行更新：wsl --update、wsl --set-default-version 2
4. 按照cer证书：https://github.com/deepin-community/deepin-WSL/releases/download/v1.0.1.0-x64/deepinWSL-Appx_1.0.1.0_x64.cer
5. 安装deepin WSL：https://github.com/deepin-community/deepin-WSL/releases/download/v1.0.1.0-x64/deepinWSL-Appx_1.0.1.0_x64.appxbundle
【验证结论】：windows 10系统中，deepin wsl安装成功
【截图信息】：
![image](https://github.com/linuxdeepin/developer-center/assets/58986464/7c4a09f8-bf9e-424c-9558-b8fd4292392c)
