### ISSUE TITLE
【deepin_V23_beta3】【严重】【立即】【集成测试】【wsl】windows11系统中，启用deepin wsl后出现报错

### ISSUE THREAD

**Issue by SuperEffie** [linuxdeepin/developer-center#5803]
### SUMMARY | 问题概要

【关联集成】：https://github.com/linuxdeepin/developer-center/issues/5771

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
【系统版本】：windows 11
【版本信息】：deepin WSL：1.0.1.0
```

### PRE-REQUIREMENT | 预置条件

安装windows系统
下载文件至本地：
[deepinWSL-Appx_1.0.1.0_x64.appxbundle](https://github.com/deepin-community/deepin-WSL/releases/download/v1.0.1.0-x64/deepinWSL-Appx_1.0.1.0_x64.appxbundle)
[deepinWSL-Appx_1.0.1.0_x64.cer](https://github.com/deepin-community/deepin-WSL/releases/download/v1.0.1.0-x64/deepinWSL-Appx_1.0.1.0_x64.cer)

### STEPS TO REPRODUCE | 复现步骤

1、双击安装cer证书
2、双击安装deepin wsl，安装完成后启动器中启动deepin WSL，观察界面显示

### OBSERVED RESULT | 观察到的结果

启用deepin WSL后，界面中显示报错
![image](https://github.com/linuxdeepin/developer-center/assets/58986464/092ea997-a669-4404-b4cd-81cc3c00fad3)

### EXPECTED RESULT | 期望的结果

deepin WSL正常运行，可正常创建用户

**Comment by babyfengfjx** [comment]
@chenchongbiao  请进行优化~

**Comment by chenchongbiao** [comment]
上一次修改的构建根文件系统的代码，上传错误，导致根文件系统没上传成功，deepin-wsl 的自动构建，没把根文件系统打包进程序。

- [ ] https://github.com/deepin-community/deepin-rootfs/commit/185b760d864a527ec8dd326e983407d3525ca8b1
- [ ] https://github.com/deepin-community/deepin-WSL/commit/f5c0d88ccd27a0a9e7bc9e1aadcc71b0b580504d

**Comment by chenchongbiao** [comment]
出现该情况了 wsl 没有升级到最新
```bash
wsl --update
wsl --set-default-version 2
```

**Comment by SuperEffie** [comment]
【操作步骤】：
1. windows系统中Microsoft Store商店中下载了适用于Linux的windows子系统应用
2. wsl进行更新：`wsl --update`、`wsl --set-default-version 2`
3. 按照cer证书：https://github.com/deepin-community/deepin-WSL/releases/download/v1.0.1.0-x64/deepinWSL-Appx_1.0.1.0_x64.cer
4. 安装deepin WSL：https://github.com/deepin-community/deepin-WSL/releases/download/v1.0.1.0-x64/deepinWSL-Appx_1.0.1.0_x64.appxbundle
【验证结论】：验证通过，deepin WSL 安装完成
【截图信息】：
![wine11wsl](https://github.com/linuxdeepin/developer-center/assets/58986464/74e83602-0e51-458b-97a0-b31d07cc91af)
