### ISSUE TITLE
Multi user environment has grave shortcomings ... Switching User bugs ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#582]
Hi,

My entire linux using life i have never really used multiple user on my linux machine. With Deepin being my favorite and most user friendly distro, i have been recommending and setting it up to folks who come to me for its clean simple and ease of use.

This prompted me to build a deepin system for my cousin which needs multiple users, this is where i have been pulling my hair from the last 2 days not knowing if its a bug or something else.

**The only user that logs in first from a hard boot mounts all the partition on the system with read/write access.**

every other user logged in after this boot either by switching users or logging of the first user signed in from the hard boot and logged in by the other user fails to give access to the partitions on the system.

Is this a bug ?

An Ideal situation is where the multi user convenience enables separate spaces ... with all resources accessible from inside. which under the current issue i am reporting is untenable ...

**Without access to the partition and data on it, a separate user login is meaningless !!!**

**Comment by hualet** [comment]
I definitely agree with you on this, but we still don't have a proper solution for this :(

**Comment by aiamuzz** [comment]
@hualet ...

> I definitely agree with you on this, but we still don't have a proper solution for this :(

I mean isn't it possible to unmount partitions when logging-off / switching a user ... auto mounting them when a user is logged in ... ???

I know linux has a complex concept of mount points

**Comment by aiamuzz** [comment]
I suspect the difficulty of an elegant solution(given that when a user switches it means his desktop with all his applications and espcially a file manager session in a particular state(open folder) is preserved when he returns back to his login) ... and un-mounting data partitions when user is switched will disrupt the open file manager session ... of the background user logged ...

**I would rather have a disrupted workspace vis-a-vis a 'File Manager' session than not have access at all to all the data partitions on the system ... for the second ... third, n users who may log in.**

**Comment by hualet** [comment]
@BLumia

**Comment by BLumia** [comment]
When switching user, it's still possible that some application is still using the partition(s) we'd mounted, it's hard to judge if a unmount error is caused by accident or something else, so we couldn't just simply force unmount the partitions we'd mounted.

Personally I recommend you simply don't use the auto mount feature if you have multiple user and really need to share a partition. If you are just looking for place to store data for different user, use the home folder. For a tree-based file system, it's not a good way to store common data by dividing your disk to serveal different partitions.

**Comment by aiamuzz** [comment]
@BLumia  ... 
hmmmm ... yeah i understand ... a blind unmounting could mess with applications that may still be using certain partitions.

Is this problem because the partition's are mounted in `**/media/user/**` ???

Is it not possible to mount all partition in `**/media/**` ... and provide all users on a system ownership to this mount folder as a default ?

**Comment by aiamuzz** [comment]
@BLumia  ... is this purely a permission issue or is it something fundamental to linux system that restricts other users from accessing the mounted partitions ?

From what i am trying to understand ... Unix, Linux are all multi-user systems ... and yet a basic access to data partitions seems to be outside this system.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
