### ISSUE TITLE
Multi user environment has grave shortcomings ... User creation bugs ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#583]
Hi,

An ideal situation would be where one could add new user to the deepin system, delete and recreate !!!

But this isn't happening in case i delete a particular user and then try to recreate the same user with the exact same Name, Username & Password. When i try to do that the user just doesn't seem to get created.

another bug ?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
