### ISSUE TITLE
[Deepin Integration]~[V23-Beta3] deepin installer version 6.0.30

### ISSUE THREAD

**Issue by ArchieMeng** [linuxdeepin/developer-center#5837]
### package information | 软件包信息

deepin-installer 6.0.30

### Package repository address | 软件包仓库地址

测试镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20231010/deepin-23-beige-beta2-amd64-20231010-162407.iso

### changelog | 更新信息

需求： 非重庆乌鲁木齐的中国地区使用上海时区 https://cooperation.uniontech.com/app/6f20cf83-ef8a-4067-bac9-b05c6d6bbcb6/650800e20a1f50226ade22ca/650800e20a1f50226ade22cb/row/b15d9b2f-096b-461a-8f98-014ea9b29775
初始化还原后清除旧的用户密钥环 https://github.com/linuxdeepin/developer-center/issues/5784

### test suggestion | 测试建议

参考Issue链接

### Sphere of influence | 影响范围

初次系统启动配置的时区和用户目录配置。

### ADDITIONAL INFORMATION | 额外补充

初次启动时，选择非重庆乌鲁木齐地区时，启动之后控制中心提示为上海时区。

**Comment by babyfengfjx** [comment]
@SuperEffie  请开展需求转测验证。

**Comment by SuperEffie** [comment]
【测试结论】：验证不通过，请走下一步流程~
【备注信息】：
1. 集成后实现的效果为：
  a. 选择非重庆、乌鲁木齐以外的中国内陆地区时如武汉，启动之后控制中心提示为上海时区，edge浏览器插件中时间显示正常
  b. 但选择香港、澳门、台湾地区时，启动之后控制中心提示为香港、澳门、台湾地区，edge浏览器插件中时间显示正常
2. 预期实现的效果为：
   选择中国任一地区，启动之后控制中心提示为对应的地区，除重庆、乌鲁木齐地区外，所有地区底层显示的时间为上海时间，且edge浏览器插件中时间显示正常
