### ISSUE TITLE
Multi user environment has grave shortcomings ... User login screen ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#584]
Hi,

anther very annoying thing i face is that the user login screen does not show contents as expected.

an ideal way would be where the last user who had signed in is the first user to be able to sign into after a reboot. This does not happen currently as the first user created on installation seems to be the default always for the first to login ... this is pretty annoying if the most frequent user of the system is by a user who has been added later after the installation. Every time that user as to click on the bottom right to a screen with all users, then click on his user and login.

pretty annoying ... you might want to fix this by letting the last user to have signed off is the first user to be signed in on a reboot.

thanks.

**Comment by liuwen123** [comment]
已修复
