### ISSUE TITLE
Multi user environment has grave shortcomings ... A superior 'User Management System' linux has ever had ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#585]
Hi,

after scratching my head from the last 2 days over a multi user system, i would say its time the Deepin team looked into a perfect and smooth 'User Management System' just like other deepin softwares which do the job in the best and simplest possible way.

I would love a more evolved 'User Management System' where i can easily add and delete and recreate an exact same user with exact same credentials as the deleted one. be able to assign resources to a particular user like 'sudo' privileges and the option where i could easily assign read/write access to a particular partition to a particular user ... 

the current system is just untenable ... believe me ... in the user management space ... Windows user management seems heaven ... which i hate !!!

I would like Deepin OS to be able to do a better job in this space, with it i can see even layman users can enjoy linux operating system more than any other operating system.

Look forward to your inputs on this request.

cheers.

**Comment by hualet** [comment]
I believe that for a desktop system, the common use case would be to have a user with administrator privilege, I'm not saying that accounts management is not necessary, but I think that an over-worked accounts management system would be a waste.

**Comment by aiamuzz** [comment]
> I believe that for a desktop operating system, the common use case would be to have a single user with administrator privileges, I'm not saying that accounts management is not necessary, but I think that an over-worked accounts management system would be a waste.

@hualet  ...

Oh ... I know in a typical linux setup where the users are mostly self helped a single user system is sufficient.

Honestly don't you think your _**"an over worked accounts management system would be a waste"**_ is a little myopic ?

Why is Windows the most used Operating system ?
Why is Ubuntu / Linux mint OS'es at the very top of the Linux Distro pyramid ?
;
;
Why did Android OS catch up and zoomed ahead to the no. 1 position ?
;
;

Don't you think the above question's ... all have a single answer ?

all have been user friendly and hence widely adopted ...

I consider Deepin OS to be the most appealing, simple and the first user friendly LINUX OS that i think the kids and common folks can be introduced to and they would use it without any problem ...

So if in Deepin's wider vision ... it wants to become a widely used OS(which i feel its on the way to becoming one)  ... then a fully functional 'multi-user' management system HAS to be considered ...

Another thing, is If Deepin considers going forward to introduce 'accessibility features/suite' ... like the windows accessibility features ... for the old and the elderly users.

**So @hualet  ... While i understand you may be busy with other priorities but shooting down things like these like restricting the run of Deepin OS and depriving it from reaching its full potential !!!

You and Project Managers need to seriously thing about that !!! **
