### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【集成测试】【DDE】【dde-launchpad】窗口模式下，使用鼠标向上或向下滚动列表是，左侧的 大写拼音与应用名称重叠覆盖

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#5851]
### SUMMARY | 问题概要

本问题单对应集成单号：#5843

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Beta2/deepin-desktop-community-23-Beta2-amd64.iso
dde-launchpad 0.1.0
```

### PRE-REQUIREMENT | 预置条件

1. 安装镜像：https://cdimage.uniontech.com/community/releases/23-Beta2/deepin-desktop-community-23-Beta2-amd64.iso
2. 加入内测
3. 添加转测仓库，手动安装 dde-launchpad 和 
4. sudo apt install dcc-insider-plugin 安装预览插件
5. 在控制中心 - 更新 - 预览中 选择开启技术预览版

### STEPS TO REPRODUCE | 复现步骤

1. 打开启动器 - 使用鼠标滚轮向下滚动列表，查看列表显示情况

### OBSERVED RESULT | 观察到的结果

1. 列表左侧应用分类下的 拼音大写字母与应用名称重叠
![录屏_选择区域_20231012131132](https://github.com/linuxdeepin/developer-center/assets/96416089/9720d5b8-5cd8-4553-9871-805e7e7707bb)

### EXPECTED RESULT | 期望的结果

2. 滚动时没有重叠的显示情况

beta2上的滚动效果为：
![poiu](https://github.com/linuxdeepin/developer-center/assets/96416089/fb1061eb-ddbe-4180-ad7c-acedf6c951f0)

**Comment by babyfengfjx** [comment]
@BLumia   请优化，目前启动器最终的设计图未确定，当前使用上字母与图表重叠的问题可以先做优化。

**Comment by BLumia** [comment]
0.2.0 集成里包含这个的修复，若验证可关闭的话，可以一并关闭 https://github.com/linuxdeepin/developer-center/issues/5552 （同一个问题）

**Comment by luodeepin** [comment]
验证通过
https://github.com/linuxdeepin/developer-center/issues/6145
dde-launchpad 0.2.0



![5851](https://github.com/linuxdeepin/developer-center/assets/96416089/d714300d-a8c0-4223-9626-0068855f839d)
