### ISSUE TITLE
Custom Shortcut Settings ... where are they stored on the home partition ???

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#586]
Hi,

I know that the custom keyboard shortcuts i have created resides in the `/home` directory(partition in my case) ...

i would like to know the path to the folder that stores this custom shortcuts as i would like to back them up manually so that i can restore them whenever i need ...

cheers.

**Comment by jouyouyun** [comment]
`$HOME/.config/deepin/dde-daemon/keybinding/custom.ini`

**Comment by aiamuzz** [comment]
Thanks guys !!!
