### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【集成测试】【DDE】【dde-launchpad】启动器全屏模式下，点击搜索后，反复点击启动器图标，启动器里面的 hover效果没有消失

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#5860]
### SUMMARY | 问题概要

本问题单对应集成单号：#5856

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Beta2/deepin-desktop-community-23-Beta2-amd64.iso
dde-launchpad 0.1.0
```

### PRE-REQUIREMENT | 预置条件

1.安装镜像：https://cdimage.uniontech.com/community/releases/23-Beta2/deepin-desktop-community-23-Beta2-amd64.iso
2.加入内测
3.添加转测仓库，手动安装 dde-launchpad 和
4.sudo apt install dcc-insider-plugin 安装预览插件
5.在控制中心 - 更新 - 预览中 选择开启技术预览版

### STEPS TO REPRODUCE | 复现步骤

1. 打开启动器全屏 - 先将鼠标启动到应用 - 再输入字符
2. 反复打开启动器，查看启动器显示

### OBSERVED RESULT | 观察到的结果

2. 启动器里面的 hover效果没有消失
![录屏_选择区域_20231012165110](https://github.com/linuxdeepin/developer-center/assets/96416089/01b6a86e-25d1-499c-b24d-9db79c068b85)

![录屏_选择区域_20231012162949](https://github.com/linuxdeepin/developer-center/assets/96416089/6a8de57d-afe9-40dd-9387-2391fd1dcc48)

### EXPECTED RESULT | 期望的结果

2. 当焦点到搜索框后，hover效果就应该消失

**Comment by babyfengfjx** [comment]
@BLumia  请开展优化~

**Comment by 18202781743** [comment]
dde-launchpad(0.5.0)没有复现,

**Comment by babyfengfjx** [comment]
@luodeepin  请在最新版本中确认回归是否还存在。

**Comment by luodeepin** [comment]
验证通过
dde-launchpad 0.6.3
![录屏_选择区域_20240422145708](https://github.com/linuxdeepin/developer-center/assets/96416089/f265fabf-d53e-4ad9-9679-b2128ad2ded9)
