### ISSUE TITLE
(Arch Deepin) mouse arrow

### ISSUE THREAD

**Issue by Xeers** [linuxdeepin/developer-center#589]
The mouse arrow often sticks to an icon that has been punctured. and, sometimes it can not be disengaged. I do not have this problem in other desktops on the same PC

https://i.imgur.com/LT6ugAZ.png

**Comment by hualet** [comment]
Your laptop have a touchscreen ?

**Comment by Xeers** [comment]
No, it's laptop is a PC monitor

**Comment by felixonmars** [comment]
Not sure what happened here, as I can never reproduce this :/

**Comment by hualet** [comment]
Oh, this bug has been fixed before the release of 15.7 for sure, I'll close this issue for now.
