### ISSUE TITLE
【deepin_V23_beta3】【一般】【有空】【集成测试】【DDE】【控制中心】V23Beta2 首次添加自定义头像时，将图片拖拽至指定区域不生效

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#5898]
### SUMMARY | 问题概要

V23Beta2 首次添加自定义头像时，将图片拖拽至指定区域不生效

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Beta2/deepin-desktop-community-23-Beta2-amd64.iso
dde-control-center:6.0.29
```

### STEPS TO REPRODUCE | 复现步骤

1.打开控制中心-用户
2,点击头像,选择自定义头像
3.拖拽图片到自定义头像框
4.观察现象

### OBSERVED RESULT | 观察到的结果

1.V23Beta2 首次添加自定义头像时，将图片拖拽至指定区域不生效
![录屏_选择区域_20231016174157](https://github.com/linuxdeepin/developer-center/assets/96415804/3f99a05d-c5b3-4eb8-9f9a-d472e0b67c03)

### EXPECTED RESULT | 期望的结果

1.自定义拖拽图片可以生成用户头像

**Comment by babyfengfjx** [comment]
@kegechen  请安排优化~

**Comment by dengbo11** [comment]
@Decodetalkers ,看下是不是哪里逻辑出了问题

**Comment by vivianxf** [comment]
集成修复:#5925
仓库:deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-591/testing/ ./
验证步骤:提单的步骤
验证现象:首次将图片拖动到自定义头像框,头像可以立即生效
验证结论:通过
![image](https://github.com/linuxdeepin/developer-center/assets/96415804/60ea4c62-9de5-4b84-a5bf-a0341ecc9eee)
