### ISSUE TITLE
dde-desktop eating up cpu

### ISSUE THREAD

**Issue by femans** [linuxdeepin/developer-center#59]
Suddenly after today update, dde-desktop consumes 100% CPU continuously. 
Sometimes also deepin-file-manager takes upto 100%.
My laptop gets very hot. 

deepin-desktop version 3.0.6-1
arch-linux with lightdm

![deepinscreenshot20160307124542](https://cloud.githubusercontent.com/assets/625851/13568628/d84e61c6-e462-11e5-8eea-b8f3659174ce.png)

**Comment by hualet** [comment]
@femans does this happen every time you login in ?

**Comment by femans** [comment]
Hi @hualet, yes I rebooted a few times to see if it persisted and it did. I also killed off dde-desktop and it would put 100% CPU on the deepin-file-manager, and after a while it would go back to dde-desktop.

If you tell me where I can find a log or if I can generate some output, I'd be happy to supply this to help solve it.

**Comment by hualet** [comment]
Strange, I rebooted trying to reproduce the problem but get nothing wrong. The log file is located at ~/.cache/deepin/dde-desktop/dde-desktop.log

**Comment by femans** [comment]
07-03-2016, 13:09:00.267 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      193] reply finished
07-03-2016, 13:09:00.269 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      199] desktopItems.count() 0 132
07-03-2016, 13:09:25.270 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      193] reply finished
07-03-2016, 13:09:25.272 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      199] desktopItems.count() 0 132
07-03-2016, 13:09:50.273 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      193] reply finished
07-03-2016, 13:09:50.275 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      199] desktopItems.count() 0 132
07-03-2016, 13:10:15.276 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      193] reply finished
07-03-2016, 13:10:15.278 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      199] desktopItems.count() 0 132
07-03-2016, 13:10:40.280 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      193] reply finished
07-03-2016, 13:10:40.282 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      199] desktopItems.count() 0 132
07-03-2016, 13:11:05.283 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      193] reply finished
07-03-2016, 13:11:05.284 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      199] desktopItems.count() 0 132
07-03-2016, 13:11:30.285 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      193] reply finished
07-03-2016, 13:11:30.287 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      199] desktopItems.count() 0 132
07-03-2016, 13:11:55.288 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      193] reply finished
07-03-2016, 13:11:55.290 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      199] desktopItems.count() 0 132
07-03-2016, 13:12:20.291 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      193] reply finished
07-03-2016, 13:12:20.293 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      199] desktopItems.count() 0 132
07-03-2016, 13:12:45.294 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      193] reply finished
07-03-2016, 13:12:45.296 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      199] desktopItems.count() 0 132
07-03-2016, 13:13:10.297 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      193] reply finished
07-03-2016, 13:13:10.299 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      199] desktopItems.count() 0 132
07-03-2016, 13:13:35.299 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      193] reply finished
07-03-2016, 13:13:35.301 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      199] desktopItems.count() 0 132
07-03-2016, 13:14:00.302 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      193] reply finished
07-03-2016, 13:14:00.304 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      199] desktopItems.count() 0 132
07-03-2016, 13:14:25.305 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      193] reply finished
07-03-2016, 13:14:25.307 [Debug  ] [dbuscontroller.cpp
 DBusController::requestDesktopItems      199] desktopItems.count() 0 132

**Comment by hualet** [comment]
@femans it seems that the desktop back end is not serving well, it returns nothing every time desktop trying to request for desktop contents.

**Comment by femans** [comment]
There is nothing in the ~/Desktop folder.

**Comment by femans** [comment]
Is there something I can do?

**Comment by hualet** [comment]
[dde-desktop-test.tar.gz](https://github.com/linuxdeepin/developer-center/files/161302/dde-desktop-test.tar.gz)

Can you build&run this test program and see what does the output say ?

> tar -xvf dde-desktop-test.tar.gz -C .
> cd dde-desktop-test; mkdir build
> cd build; qmake .. CONFIG+=debug; make 
> ./dde-desktop-test

**Comment by femans** [comment]
​desktopLocation  "/home/xor/projects"
normal files count  132
hidden files count 39
then follows a list of stuff in my projects folder. Like:
"hidden file /home/xor/projects/fabric is app group : 0"

There might be something wrong with that my Desktop folder refers to my
projects folder.

**Comment by hualet** [comment]
What does this outputs on your computer ?

> xdg-user-dir DESKTOP

**Comment by femans** [comment]
/home/xor/projects

**Comment by derekdai** [comment]
Hi @femans, can you run commands below to help us to locate where causes high CPU usage?
```
$ sudo apt-get install linux-perf-4.3
$ sudo perf record -a -F 997 -e cycles sleep 5
```

And attach the generated perf.data when you reply, thanks.

**Comment by femans** [comment]
btw, the desktop also used to display the contents of my projects folder,
but now it doesnt. Also clicking on it, either right or left does not work
anymore. However, there are 2 icons displayed, Computer and Trash, which I
am not sure if they respond. I don't think so.
I didn't look at this, because I never use the desktop. Hardly ever see it.

**Comment by hualet** [comment]
@femans try this 
> xdg-user-dirs-update --set DESKTOP ~/Desktop/
hope it can solve your problem.

**Comment by hualet** [comment]
@derekdai I know what causes the problem, his xdg DESKTOP is wrongly set to ~/projects/.  Caused dde-desktop to request for contents from its back end endlessly.

**Comment by femans** [comment]
@hualet Hi, I tried that, and so far it does not seem to fix it.
In the meanwhile there is a new error in the log output: 07-03-2016, 14:29:25.696 [Error  ] [menucontroller.cpp        MenuController::showMenuByUrls           131] register menu fail!

@derekdai I hope I don't dump confidential data online now:
[perf.data.gz](https://github.com/linuxdeepin/developer-center/files/161357/perf.data.gz)

**Comment by hualet** [comment]
@femans No way, I forgot to say that, but you need to logout and re-login after executing the command.

**Comment by femans** [comment]
:/ Could have guessed. Seems indeed to have fixed it :D great.

Anyway, the 2 icons in the desktop have disappeared. I still can't click on
the desktop, so I can't access certain settings. And it might be considered
a bug, that dde eats the cpu when the desktop is not in default location?
Thanks anyway!

**Comment by hualet** [comment]
Uh..this issue, I don't know how to put it, makes me feel up and down from the beginning to the end.

Yeah, it's a bug indeed. But it's just a bug not a serious fault that can stop me from building the ISO, right ?

Anyway, thanks for you cooperation and fast responds @femans. The community needs ones like you. Thanks :+1:

**Comment by femans** [comment]
Sure thing! You too thanks for fast feedback :D and great desktop
