### ISSUE TITLE
[dde-file-manager] Non Respnsive Width in List View

### ISSUE THREAD

**Issue by aksh1618** [linuxdeepin/developer-center#591]
After updating to 15.7 Desktop on Arch, In Deepin File Manager (v1.8 Alpha) the width when display as list is selected remains fixed on maximizing/ changing window size:

![deepinscreenshot_select-area_20180811163201](https://user-images.githubusercontent.com/26065812/43992545-7db4ff94-9d9d-11e8-8dba-8237b95225e5.png)
![deepinscreenshot_dde-file-manager_20180811183134](https://user-images.githubusercontent.com/26065812/43992542-7279443c-9d9d-11e8-9570-9fb3a5d39059.png)

**Comment by zccrs** [comment]
Hi, It is a new design. The width of the list is no longer fixed, now you can change the width of each column by mouse dragging
