### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【集成测试】【终端】双屏扩展模式下，在主屏 Alt F2打开雷神终端,点击屏幕空白处，再将鼠标移动到另一屏幕按 Alt F2时，出现两个雷神终端

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#5927]
### SUMMARY | 问题概要

本问题单对应集成单号：https://github.com/linuxdeepin/developer-center/issues/5904

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
终端 6.0.8
```

### PRE-REQUIREMENT | 预置条件

1.安装镜像：https://cdimage.uniontech.com/community/releases/23-Beta2/deepin-desktop-community-23-Beta2-amd64.iso
2.加入内测
3.添加转测仓库更新终端：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-575/testing/ ./
4. 连接双屏，扩展模式

### STEPS TO REPRODUCE | 复现步骤

1. 在主屏 Alt F2打开雷神终端
2. 在主屏幕点击屏幕空白处
3. 再将鼠标移动到另一副屏幕按 Alt F2

### OBSERVED RESULT | 观察到的结果

3. 出现两个雷神终端

### EXPECTED RESULT | 期望的结果

3. 只存在一个雷射终端

**Comment by babyfengfjx** [comment]
@ArchieMeng  请优化~

**Comment by ArchieMeng** [comment]
修复测试包
http://aptly.uniontech.com/pkg/beige-v2/release-candidate/ZGVlcGluLXRlcm1pbmFsMjAyMy0wMy0wMSAxMTozMTozNQ/

**Comment by luodeepin** [comment]
测试通过
![录屏_选择区域_20231103145209](https://github.com/linuxdeepin/developer-center/assets/96416089/579c0758-79b0-4e46-8d38-40365d5eba15)
