### ISSUE TITLE
lid-closed-sleep in dconf should separated as lid-close-ac-action / lid-close-battery-action （合盖子休眠可否加入插入电源和非电源时候的不同动作）

### ISSUE THREAD

**Issue by ihipop** [linuxdeepin/developer-center#593]
mostly purpose of `lid-closed-sleep` （ known as `com.deepin.dde.power lid-closed-sleep`） is to

1.  Move the laptop with  safety  to another place when lid is close

1.  Just for power saving when lid is close

1.  Want the lid  closed when use an external display 

1. Just run background computer task and saving space.

But:

1. When we connect the AC power for charging, we won't move the laptop `+1`

1. When we connect the AC power for charging, we won't aiming to saving power `+1`

1. Currently,when close the lid,and there is an external display connected, DDE will promote a dialog with count down to let the user make a choice whether to sleep or not,not very convenient,but acceptable . `-1`

1. No way to achive the gole but set `lid-closed-sleep` to `false` manually `+1`

And:
Both Windows/OS X/Gnome Provide the option to have different action when ac is connected or not `+1`

So:
It a `3+1` vs `1` vote

Would you please consider about it?

------------------------------

**Comment by hualet** [comment]
Sounds reasonable, will consider it but with a very low priority, thank you for you suggestion anyway :)

**Comment by CareF** [comment]
Want this feature too!

**Comment by wangjia12** [comment]
Thanks for the suggestion, we will deal with this issue soon.
https://github.com/linuxdeepin/internal-discussion/issues/1147

**Comment by ihipop** [comment]
Released in Deepin 15.11  @CareF
