### ISSUE TITLE
Idea to make alt + tab and switching windows of same app more predictable

### ISSUE THREAD

**Issue by trading-peter** [linuxdeepin/developer-center#594]
## Describe the bug

Following situation: You're a web developer and need to constantly switch between two (or more) windows of your IDE and the browser were you preview the page.

## To Reproduce
Typical workflow would be:
1. Code in the Window A of the IDE, press alt + [key above tab] to quickly switch to window B of the IDE, do some more coding.
2. Now press alt + tab once with the goal to get the browser window. Because alt + [key above tab] changes the history (or stack, or however it's called) of alt + tab you end up in Window A of your IDE.

Other Desktops keep the history of the "switch between windows of current app" and history of alt + tab separate. In Deepin DE I currently need to press alt + tab two times with the workflow as described above. It gets even more difficult when you work with, lets say, 4 windows of your IDE. The amount of alt + tab presses to get to the browser is different nearly every time.

If switching app windows with alt + [key above tab] would not alter the history of alt + tab, a much faster workflow would be possible in IMO.

I hope my example makes it clear what I mean...

**Comment by sonald** [comment]
what `other desktops` are you referring to ?  GNOME or KDE or else ?

**Comment by aiamuzz** [comment]
@pkaske ... i agree ... if Alt+tab ... Alt + ~(key_above_tab) ... had 2 different history/settings ... it would certainly be a very efficient workflow !!! ... If any other linux distro/desktop has this feature already, it would help the team develop/adopt it faster ... please do point to the same.

**Comment by pkaske** [comment]
@sonald @aiamuzz Gnome does it like that. Also macOS. I don't know about KDE.

**Comment by sonald** [comment]
Ok, sounds fair.  Gonna discuss it with our product team.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
