### ISSUE TITLE
Building like explained in the README failed

### ISSUE THREAD

**Issue by DevLenn** [linuxdeepin/developer-center#5943]
This Error belongs to: https://github.com/linuxdeepin/dde-dock/issues

### SUMMARY | 问题概要

CMake Error at CMakeLists.txt:9 (find_package):
  By not providing "FindDtkTools.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "DtkTools",
  but CMake did not find one.

  Could not find a package configuration file provided by "DtkTools" with any
  of the following names:

    DtkToolsConfig.cmake
    dtktools-config.cmake

  Add the installation prefix of "DtkTools" to CMAKE_PREFIX_PATH or set
  "DtkTools_DIR" to a directory containing one of the above files.  If
  "DtkTools" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
latest
```

### STEPS TO REPRODUCE | 复现步骤

$ cd dde-dock
$ mkdir Build
$ cd Build
$ cmake ..

### EXPECTED RESULT | 期望的结果

build successfully

### ADDITIONAL INFORMATION | 额外补充

pls help

**Comment by DevLenn** [comment]
Now I'm getting the following (QT is installed):
process translations/dde-dock_ady.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_af.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_ak.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_am_ET.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_ar_EG.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_ar.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_ast.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_az.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_bg.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_bn.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_bo.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_br.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_ca.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_cgg.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_cs.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_da.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_de_CH.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_de.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_el.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_en_AU.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_en_GB.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_en_US.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_eo.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_es_419.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_es_MX.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_es.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_et.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_eu.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_fa.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_fil.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_fi.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_fr.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_gl_ES.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_gl.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_he.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_hi_IN.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_hi.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_hr.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_hu.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_hy.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_id.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_it.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_ja.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_kab.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_ka.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_kk.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_km_KH.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_kn_IN.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_ko.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_ku_IQ.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_ku.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_ky@Arab.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_ky.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_la.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_lo.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_lt.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_lv.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_ml.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_mn.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_mr.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_ms.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_nb.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_ne.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_nl.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_pam.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_pa.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_pl.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_ps.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_pt_BR.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_pt.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_ro.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_ru.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_sc.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_si.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_sk.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_sl.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_sq.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_sr.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_sv.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_sw.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_ta.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_te.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_th.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_tr.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_tzm.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_ug.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_uk.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_ur.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_uz.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_vi.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_zh_CN.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_zh_HK.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory

process translations/dde-dock_zh_TW.ts
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory
CMake Error at frame/CMakeLists.txt:21 (find_package):
  By not providing "FindQt5X11Extras.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5X11Extras", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5X11Extras" with
  any of the following names:

    Qt5X11ExtrasConfig.cmake
    qt5x11extras-config.cmake

  Add the installation prefix of "Qt5X11Extras" to CMAKE_PREFIX_PATH or set
  "Qt5X11Extras_DIR" to a directory containing one of the above files.  If
  "Qt5X11Extras" provides a separate development package or SDK, be sure it
  has been installed.


-- Configuring incomplete, errors occurred!

**Comment by Decodetalkers** [comment]
You need to install lrelease, dtkcommon, and qt5x11 lib. take a look at debian/controls

**Comment by BLumia** [comment]
Not sure which distro you're using, you need to get all the dependencies before trying to build. If you are using deepin v23, then `sudo apt build-dep dde-dock` could help (might need to enable `deb-src` from your sourcelist file). For other distro, you need to find the associated dependencies and install them first.

btw, it's suggest to create a discussion thread instead of an issue if you're not reporting a bug :)

**Comment by BLumia** [comment]
We are still not sure which distro you're using. Since this is not really a bug but a discussion thread, I'll close this issue for now. If you are still facing a similar issue, please consider creating a discussion thread with more information included so we can offer better help. You can also consider join our Telegram or Matrix chat to get help, checkout [our official website](https://www.deepin.org/) to know all available contact methods :)
