### ISSUE TITLE
[Deepin Integration]~[V23-Beta3]  by kamiyadm: fix io.github.marktext

### ISSUE THREAD

**Issue by kamiyadm** [linuxdeepin/developer-center#5963]
### package information | 软件包信息

包名 | 版本
-- | --
io.github.marktext | 0.17.4

### Package repository address | 软件包仓库地址

Url: http://10.0.36.228:9001  RepoName: develop-snipe

### test suggestion | 测试建议

测试步骤：

1. 修改仓库为开发仓库，ll-cli repo modify http://10.0.36.228:9001 --name develop-snipe

2. 安装应用，ll-cli install io.github.marktext

3. 测试能否打开文件

### Sphere of influence | 影响范围

https://pms.uniontech.com/bug-view-224711.html

**Comment by kamiyadm** [comment]
@Zeno-sole 这个需要集成一下

**Comment by Zeno-sole** [comment]
@babyfengfjx 玲珑软件包 请安排测试验证

**Comment by babyfengfjx** [comment]
@SuperEffie  请开展集成验证。

**Comment by SuperEffie** [comment]
【验证结论】：测试通过，请走下一步流程
【备注信息】：玲珑应用更新后，https://pms.uniontech.com/bug-view-224711.html中问题已修复。已验证关单。
