### ISSUE TITLE
Login screen take a long time

### ISSUE THREAD

**Issue by adierebel** [linuxdeepin/developer-center#597]
After full-upgrade from 15.6 to 15.7, login screen take a long time to show desktop env. Its about 2minutes to load desktop.

So, i start to investigate using `journalctl -b`

```
Aug 25 03:18:16 A43SD startdde[3739]: sound_effect.go:51: PlaySystemSound DesktopLogin
Aug 25 03:18:23 A43SD startdde[3739]: sound_effect.go:56: PlaySystemSound DesktopLogin done
Aug 25 03:20:16 A43SD dbus-daemon[3798]: [session uid=1000 pid=3796] Failed to activate service 'com.deepin.dde.Welcome': timed out (service_start_timeout=120000ms)
Aug 25 03:20:16 A43SD startdde[3739]: main.go:85: Failed to show welcome: org.freedesktop.DBus.Error.TimedOut:Failed to activate service 'com.deepin.dde.Welcome': timed out (service_start_timeout=120000ms)
```

dbus-daemon failed to activate service 'com.deepin.dde.Welcome', and wait **120000ms**?

How i can fix this problem?

Thanks

**Comment by hualet** [comment]
That may because you didn't have a full dist-upgrade ? try sudo apt install dde

**Comment by adierebel** [comment]
Try `sudo apt-get install dde` then `sudo apt-get dist-upgrade`

Thanks, it's work perfectly
