### ISSUE TITLE
【deepin_V23_beta3】【一般】【有空】【内测反馈】【DDE】【控制中心】将光标主题设置为hazy-color后，在登录界面光标主题没有显示为 hazy-color的样式

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#5970]
### SUMMARY | 问题概要

此问题在20.9也存在
内测反馈链接：https://cooperation.uniontech.com/app/6f20cf83-ef8a-4067-bac9-b05c6d6bbcb6/648bfccc0a1f50226a98dbc6/648bfccc0a1f50226a98dbca/row/f161d87a-000d-43a1-9993-7d65059e41a0
![image](https://github.com/linuxdeepin/developer-center/assets/96416089/eb368986-2620-4c80-9966-fea9e67d2e28)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
1.安装镜像：https://cdimage.uniontech.com/community/releases/23-Beta2/deepin-desktop-community-23-Beta2-amd64.iso
2. 控制中心 6.0.28
```

### PRE-REQUIREMENT | 预置条件

1.安装镜像：https://cdimage.uniontech.com/community/releases/23-Beta2/deepin-desktop-community-23-Beta2-amd64.iso
2.加入内测，更新至最新版本

### STEPS TO REPRODUCE | 复现步骤

1. 打开控制中心 - 个性化 - 光标主题 ，将光标主题设置为 hazy-color
2. 重启或注销系统，在登录界面查看 鼠标光标显示样式

### OBSERVED RESULT | 观察到的结果

2. 在登录界面光标主题没有显示为 hazy-color的样式
![hazy-color](https://github.com/linuxdeepin/developer-center/assets/96416089/214b1406-06f0-4b37-9fa6-4222024b0d56)

### EXPECTED RESULT | 期望的结果

2. 在登录界面光标主题显示为当前设置光标的样式

**Comment by xuqi27837288** [comment]
* https://github.com/linuxdeepin/developer-center/issues/5003

该问题之前有提单反馈过，建议与梅毅翔沟通对齐一下~看是否推动优化和修改~ 

@babyfengfjx @meiyixiang

**Comment by babyfengfjx** [comment]
@luodeepin  请确认是否与上述issue反馈问题一致 #5003  ，如果一致可以参考此issue的结论。

**Comment by luodeepin** [comment]
通过:https://github.com/linuxdeepin/developer-center/issues/5003  跟踪处理
