### ISSUE TITLE
[Feature request] Functionality for system profiles

### ISSUE THREAD

**Issue by ghost** [linuxdeepin/developer-center#598]
This might be a bit far out in the future.

KDE has an amazing "Activities" functionality which allows a user to isolate the same users' different interests, etc. Here, I suggest a "System Profiles" functionality for deepin: users set up a system profile (which governs which wifi to connect to, system wallpaper(s), how many workspaces, which sounds are on, etc) and can switch between profiles easily. This would be analogous to mobile OSs in which people set up different "Work" or "Home" profiles.

I could write scripts to emulate the above behaviour, but having a nice integrated option in Deepin would really be a killer feature. Also, I would be happy to write some scripts for this project, but I would need to know how to integrate it with the deepin settings menu.

**Comment by meiyixiang** [comment]
I understand that sounds like isolation between users. Deepin now supports it
