### ISSUE TITLE
Feature Request ... Favorites or most used application category ???

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#599]
Hi,

Can you please add the feature where the full screen launcher has 'most recently used' category above all other categories ... given the [instability_issues_of_15.7](https://github.com/linuxdeepin/developer-center/issues/595) i have been facing currently, seems a recently used category would have made life much more easier in this and

Its an option i have been missing ever since i moved to Deepin ... in a normal use scenario ... shouldn't be difficult given that the compact windows styled launcher already has the recently used listed above the categories entry at the bottom.

 **Hope to see it in 15.8  implemented in the full screen launcher mode as well.**

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
