### ISSUE TITLE
Feature Request : moving the 'color tag' category to the top of the file manager list ???

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#600]
Hi,

Currently Deepin File Manager on the left column currently is in the order ...
User data ...
Computer ...
System Disk ...
All partitions on the system including the external storage device and their partitions ... 
Computer in LAN
;
**User specific Color tagged categories**

Wouldn't it be a good idea to have this User Specific Color tagged list be pushed to the top or may be in between the 

User data ...
**User specific Color tagged categories**
Computer ...
System Disk ...
All partitions on the system including the external storage device and their partitions ... 
Computer in LAN

The whole idea of having a system of tagging is for ease of access ... the bottom placement requires the user to scroll down to the bottom when it would have been easier to access had it been place higher up the order !!!

If its not a major change ... hope to see it implement on 15.8 ...

**Comment by aiamuzz** [comment]
An even better system would have been to provide the option to move the order of the categories based on a users preference ... say if one uses network drives(Computers in LAN) they can drag that category to the top or a position they choose would suit them better.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
