### ISSUE TITLE
平均每注销2-5次之后就会复现dock栏无白色磨砂的效果

### ISSUE THREAD

**Issue by c61292558** [linuxdeepin/developer-center#6012]
### 平均每注销2-5次之后就会复现dock栏无白色磨砂的效果：
此处用了黑色壁纸：
![截图_选择区域_20231025164255](https://github.com/linuxdeepin/developer-center/assets/11317413/178247ba-05da-4707-a850-becc2b706042)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
Distribution：V23 B2截止10月23日前的最后一次的内测更新。
Kernel:6.4.0-xanmod1
```

### PRE-REQUIREMENT | 预置条件

1.开机后的第一次注销后登陆进入系统必定会复现（不确定是否跟开机启动项有关，添加有开机启动项Fclash)
2.然后多次注销后大概率会复现。

### STEPS TO REPRODUCE | 复现步骤

1.开机后的第一次注销后登陆进去必定会复现。
2.多次注销后再登陆进入系统大概率会复现。

### OBSERVED RESULT | 观察到的结果

正常情况下的dock栏（浅色模式）：
正常情况下dock栏会偏白很多，与桌面壁纸对比明显白很多
![image](https://github.com/linuxdeepin/developer-center/assets/11317413/06107f1f-179a-4720-8481-54ed53124b9e)

正常情况下的dock栏（深色模式）：
![image](https://github.com/linuxdeepin/developer-center/assets/11317413/4e1b04cf-4b77-42da-b43c-f84ce9c5e550)

有bug情况下的dock栏：（浅色模式）：
完全就被壁纸“染”色了，尤其是黑色壁纸的情况下，右下角的控制图标根本就看不见了。
![截图_选择区域_20231027172610](https://github.com/linuxdeepin/developer-center/assets/11317413/5f81573a-23d8-4907-bdaf-4ef6f386ad55)

有bug情况下的dock栏：（浅色模式）：
**跟浅色模式一致，无变化。**

### EXPECTED RESULT | 期望的结果

注销不会再次改变dock栏效果。

### ADDITIONAL INFORMATION | 额外补充

![image](https://github.com/linuxdeepin/developer-center/assets/11317413/e7e9cf72-7e6c-46a3-90bc-b97d88129d8a)

**Comment by babyfengfjx** [comment]
@SuperEffie  请尝试复现后跟踪。

**Comment by SuperEffie** [comment]
@c61292558   感谢反馈，这个问题是部分机器上偶现问题，按照issue中描述是注销多次后，任务栏透明度发生了变化，我们暂时未复现到这种情况，会持续观察。
目前v23任务栏在重构，后续发版前会重点关注下该问题~

**Comment by c61292558** [comment]
> @c61292558 感谢反馈，这个问题是部分机器上偶现问题，按照issue中描述是注销多次后，任务栏透明度发生了变化，我们暂时未复现到这种情况，会持续观察。 目前v23任务栏在重构，后续发版前会重点关注下该问题~
是否跟我的内核一致地复现？

**Comment by SuperEffie** [comment]
> > @c61292558 感谢反馈，这个问题是部分机器上偶现问题，按照issue中描述是注销多次后，任务栏透明度发生了变化，我们暂时未复现到这种情况，会持续观察。 目前v23任务栏在重构，后续发版前会重点关注下该问题~
> 
> 是否跟我的内核一致地复现？

任务栏的显示和内核版本应该是没有关系的。

**Comment by tsic404** [comment]
kwin 特效插件加载问题，unload后reload一下kwin的特效插件blur应该就回来了
