### ISSUE TITLE
【deepin-unioncode】deepin v20.9 打开git面板崩溃

### ISSUE THREAD

**Issue by dongchao139** [linuxdeepin/developer-center#6013]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin v20.9
安装master分支。
```

### STEPS TO REPRODUCE | 复现步骤

打开使用git的仓库，打开git面板，崩溃退出。
![截图_选择区域_20231029115433](https://github.com/linuxdeepin/developer-center/assets/35620253/a5d2a147-a6b9-4088-b05f-555287d815b3)

**Comment by BLumia** [comment]
你这个反馈针对的是哪个项目？推测是 deepin-unioncode？

**Comment by dongchao139** [comment]
> 你这个反馈针对的是哪个项目？推测是 deepin-unioncode？

是的

**Comment by deepin-mozart** [comment]
> ### SUMMARY | 问题概要
> _No response_
> 
> ### SOFTWARE/OS VERSIONS | 软件/系统版本信息
> ```
> deepin v20.9
> 安装master分支。
> ```
> 
> ### PRE-REQUIREMENT | 预置条件
> _No response_
> 
> ### STEPS TO REPRODUCE | 复现步骤
> 打开使用git的仓库，打开git面板，崩溃退出。 ![截图_选择区域_20231029115433](https://user-images.githubusercontent.com/35620253/278850091-a5d2a147-a6b9-4088-b05f-555287d815b3.png)
> 
> ### OBSERVED RESULT | 观察到的结果
> _No response_
> 
> ### EXPECTED RESULT | 期望的结果
> _No response_
> 
> ### ADDITIONAL INFORMATION | 额外补充
> _No response_

能看看堆栈信息吗

**Comment by BLumia** [comment]
过久未提供进一步信息，予以关闭。
