### ISSUE TITLE
[Deepin Integration]~[V23-Beta3] deepin installer version 6.0.30

### ISSUE THREAD

**Issue by ArchieMeng** [linuxdeepin/developer-center#6019]
### package information | 软件包信息

deepin-installer 6.0.30

### Package repository address | 软件包仓库地址

测试镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20231030/deepin-23-beige-beta2-amd64-20231030-112131.iso

### changelog | 更新信息

改为和控制中心协调好了的设置时区的方式。

### test suggestion | 测试建议

参考前一个集成测试的内容。https://github.com/linuxdeepin/developer-center/issues/5837

**Comment by babyfengfjx** [comment]
@SuperEffie 请开展集成验证。

**Comment by SuperEffie** [comment]
【验证结论】：测试不通过，请修复后重新提交集成
【遗留issue】: [#6024](https://github.com/linuxdeepin/developer-center/issues/6024)

**Comment by Zeno-sole** [comment]
镜像更新：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20231031/
 集成 https://github.com/linuxdeepin/developer-center/issues/6017 相关内容

**Comment by SuperEffie** [comment]
【验证结论】：测试通过，请走下一步流程
【备注信息】：
验证了以下内容：
1、安装时，默认时区城市是北京，安装完成后控制中心显示的系统时区是北京，系统时间及Edge浏览器插件时间显示正常；
2、步骤1完成后，控制中心中切换系统时区为武汉，系统时间及Edge浏览器插件时间显示正常；
3、安装时选择时区城市为武汉，安装完成后控制中心显示的系统时区是武汉，系统时间及Edge浏览器插件时间显示正常；
4、安装时选择时区城市为乌鲁木齐，安装完成后控制中心显示的系统时区是乌鲁木齐，系统时间及Edge浏览器插件时间显示正常，比北京时间晚2h；
5、安装时选择时区城市为重庆，安装完成后控制中心显示的系统时区是重庆，系统时间及Edge浏览器插件时间显示正常，与北京时间相同；
验证以上场景均符合需求，安装器与控制中心设置时区的方式已同步，验证issue : # 5850 、# 6024 均已修复。验证通过~
