### ISSUE TITLE
【deepin_V23_beta3】【有空】【一般】【集成测试】【输入法】集成deepin-im的1.0.1版本后,deepin ID登录框中无法通过Tab键切换光标位置至下个文本框内

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#6029]
### SUMMARY | 问题概要

必现问题

关联集成:

* https://github.com/linuxdeepin/developer-center/issues/6007

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230927/deepin-23-beige-beta2-amd64-20230927-115418.iso

内核：6.1.32
deepin-im	1.0.1
```

### PRE-REQUIREMENT | 预置条件

deepin-im 1.0.1版本安装后重启进入系统

### STEPS TO REPRODUCE | 复现步骤

 打开deepin ID登录框后使用手机、邮箱、账号等任意方式进行登录操作，观察使用Tab键是否可以切换光标位置至下个文本框内

### OBSERVED RESULT | 观察到的结果

按Tab无反应，无法切换成功

![image](https://github.com/linuxdeepin/developer-center/assets/62528742/6d187b7d-cd37-4b19-bd6b-7628d92a1145)

### EXPECTED RESULT | 期望的结果

可以切换成功

**Comment by babyfengfjx** [comment]
@dengbo11  请优先处理修复~

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240104
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.7-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
