### ISSUE TITLE
Screensaver gets active when it shouldnt

### ISSUE THREAD

**Issue by random2324** [linuxdeepin/developer-center#603]
## Describe the bug

Running the benchmarks Unigine Heaven / Valley sets the screensaver active. I guess it should detect the benchmark as game activity and prevent starting the screensaver.

## To Reproduce

To reproduce just set the value for the screensaver to 1min.

### Distro & Version

Arch Linux.
Deepin packages from today.

**Comment by dusatvoj** [comment]
Try to download [caffeine pkg](https://aur.archlinux.org/packages/caffeine/). It solved my screensaver problem while watching films in VLC

**Comment by random2324** [comment]
Thanks, thats very useful. Now, the question is why cant something like this get built in Deepin by default?

**Comment by dusatvoj** [comment]
You're welcome. IDK, I'm only user, not developer :laughing:

**Comment by random2324** [comment]
Yeah but I think, since no dev replied your input is important to raise the awareness. VLC is more imprtant than some old benchmarks.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
