### ISSUE TITLE
【deepin_V23_beta3】【有空】【一般】【发散测试】光标移至deepin ID用户名文本框后，文本框失去焦点时文本框仍然处于编辑状态

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#6054]
### SUMMARY | 问题概要

必现问题

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230927/deepin-23-beige-beta2-amd64-20230927-115418.iso

内核：6.1.32
```

### PRE-REQUIREMENT | 预置条件

登录deepin ID

### STEPS TO REPRODUCE | 复现步骤

光标移入用户名文本框内后，点击切换至其他选项或文本框外，观察文本框失去焦点后的编辑状态

### OBSERVED RESULT | 观察到的结果

文本框失去焦点后仍然展示为可编辑状态

https://github.com/linuxdeepin/developer-center/assets/62528742/0c794ce6-fc0c-4cf5-9643-38fdeeda7c2e

### EXPECTED RESULT | 期望的结果

文本框失去焦点无法进行编辑操作

**Comment by xuqi27837288** [comment]
@Decodetalkers 该问题之前已沟通，麻烦帮忙抽空优化一下，谢谢~

**Comment by Decodetalkers** [comment]
新需求为了安全要求在网页端设置，所以这个问题不存在了

**Comment by babyfengfjx** [comment]
@xuqi27837288  需要提供需求链接，再进行关闭。

**Comment by xuqi27837288** [comment]
https://doc.uniontech.com/docs/KlkKVZN8m1iMwYqd#anchor-JvqI

该需求在beta3已经完成，该问题单关闭

![截图_选择区域_20231220153244](https://github.com/linuxdeepin/developer-center/assets/62528742/40bcaddb-b9a8-4504-a1d7-fa817bd8f152)
