### ISSUE TITLE
【deepin_V23_beta3】【有空】【一般】【发散测试】deepin ID登录框展示时，任务栏缩略图窗口名称展示为UOS ID

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#6055]
### SUMMARY | 问题概要

必现问题

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230927/deepin-23-beige-beta2-amd64-20230927-115418.iso

内核：6.1.32
```

### PRE-REQUIREMENT | 预置条件

点击登录deepin ID后弹出登录框

### STEPS TO REPRODUCE | 复现步骤

观察任务栏缩略图窗口名称的展示效果

### OBSERVED RESULT | 观察到的结果

展示为UOS ID

![image](https://github.com/linuxdeepin/developer-center/assets/62528742/5e38dcfb-6079-4880-8ffa-cb05db495234)

### EXPECTED RESULT | 期望的结果

展示为deepin ID

**Comment by xuqi27837288** [comment]
@Decodetalkers 该问题之前已拉群一起和deepin ID子项目沟通对齐，麻烦分析一下后进行优化，谢谢~

**Comment by SuperEffie** [comment]
【验证环境】
【镜像地址】：https://packagesupdate.uniontech.com/repo/cdimage/deepin/23/v23-Beta2/deepin-desktop-community-23-Beta2-amd64.iso
【版本信息】：deepin-deepinid-client	7.0.2
【关联集成】：#6216
【验证结论】：问题已修复，关闭此issue
【截图信息】：
![deepin ID](https://github.com/linuxdeepin/developer-center/assets/58986464/3a275625-996b-45bc-a553-cfc4b099170e)
