### ISSUE TITLE
No applications in launcher after switching nvidia drivers.

### ISSUE THREAD

**Issue by AdriaanBoshoff** [linuxdeepin/developer-center#606]
I just switched to the closed source drivers for nvidia and found that the launcher no longer shows any more applications. I had the same issue on my laptop but fixed it by just restarting it. Sadly restarting it is not working. I also thought this was the stable release but doesn't seem to be.

![screenshot](https://user-images.githubusercontent.com/16230645/45559191-1b4a3300-b842-11e8-869b-3c3942095e47.png)
![screenshot launcher](https://user-images.githubusercontent.com/16230645/45559248-3e74e280-b842-11e8-834d-b30904d6b5f0.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
