### ISSUE TITLE
Root Applications Do Not Scale

### ISSUE THREAD

**Issue by 4lcane** [linuxdeepin/developer-center#607]
Hey guys! Been running Manjaro Deepin for a while and absolutely love it! The HiDPI solution of using scaling works great with ALMOST everything. Steam runs in the normal max resolution of 3200x1800 (Steam issue; different problem for another post).

However, I've found that any application ran as root is drawn without scaling. I'm guessing that it's running off of application owner's config file. It's a small issue, but one I felt you would like to hear about. I'll provide any information asked.

**Relevent Info:**
Manjaro 17.1.12
DDE 15.7
Linux4.1469-1

**Setup: Dell XPS 13 9343**
Display:13.3" UltraSharp QHD+ (3200 x 1800) infinity touch display 
Screen Resolution:3200 x 1800
Processor: Core i7-5500U 2.40 GHz
Memory: 8GB Dual Channel DDR3L-RS 1600Mhz
Video:Intel HD Graphics 5500 with shared graphics memory

~I understand this is not a pressing issue 
  so please don't explain how there's more
  important issues... I already know ^_^

**Comment by ToRvaLDz** [comment]
Same problem here, also logging out to change the scale is a waste of time.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
