### ISSUE TITLE
Deepin Image Viewer crashing

### ISSUE THREAD

**Issue by random2324** [linuxdeepin/developer-center#609]
## Describe the bug

If I open a screenshot made with Deepin Screenshot it crashes after some seconds with the following output:

translatePath after feedback: "/usr/share/dtkwidget/translations/dtkwidget2_de"
translatePath after feedback: "/usr/share/deepin-image-viewer/translations/deepin-image-viewer_de"
Setting file: "/home/greg/.config/deepin/deepin-image-viewer/config.conf"
2018-09-20, 10:02:32.809 [Debug  ] [                                                         0] LogFile: "/home/greg/.cache/deepin/deepin-image-viewer/deepin-image-viewer.log"
2018-09-20, 10:02:32.809 [Debug  ] [                                                         0] Deepin Image Viewer is defaultImage!
2018-09-20, 10:02:33.065 [Debug  ] [                                                         0] database is exist!
thread '<unnamed>' panicked at 'assertion failed: rectangle.x1 >= rectangle.x0', rsvg_internals/src/surface_utils/iterators.rs:78:9
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: <unknown>
  38: <unknown>
  39: <unknown>
  40: <unknown>
  41: rsvg_handle_render_cairo_sub
  42: _ZNK3Dtk6Widget19DSvgRendererPrivate8getImageERK5QSizeRK7QString
  43: _ZNK3Dtk6Widget12DSvgRenderer7toImageE5QSizeRK7QString
  44: _ZN13QSvgIOHandler4readEP6QImage
  45: _ZN12QImageReader4readEP6QImage
  46: _ZN12QImageReader4readEv
  47: _ZN15QPlatformPixmap8fromFileERK7QStringPKc6QFlagsIN2Qt19ImageConversionFlagEE
  48: _ZN7QPixmap4loadERK7QStringPKc6QFlagsIN2Qt19ImageConversionFlagEE
  49: <unknown>
  50: _ZN7QWidget5eventEP6QEvent
  51: _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent
  52: _ZN12QApplication6notifyEP7QObjectP6QEvent
  53: _ZN3Dtk6Widget12DApplication6notifyEP7QObjectP6QEvent
  54: _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent
  55: _ZN14QWidgetPrivate14sendPaintEventERK7QRegion
  56: _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore
  57: _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore
  58: _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore
  59: _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore
  60: _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore
  61: _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore
  62: _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore
  63: _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore
  64: _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore
  65: <unknown>
  66: <unknown>
  67: _ZN14QWidgetPrivate16syncBackingStoreEv
  68: _ZN7QWidget5eventEP6QEvent
  69: _ZN11QMainWindow5eventEP6QEvent
  70: _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent
  71: _ZN12QApplication6notifyEP7QObjectP6QEvent
  72: _ZN3Dtk6Widget12DApplication6notifyEP7QObjectP6QEvent
  73: _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent
  74: _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData
  75: <unknown>
  76: g_main_context_dispatch
  77: <unknown>
  78: g_main_context_iteration
  79: _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE
  80: <unknown>
  81: _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE
  82: _ZN16QCoreApplication4execEv
  83: main
  84: __libc_start_main
  85: <unknown>
fatal runtime error: failed to initiate panic, error 5
Abgebrochen (Speicherabzug geschrieben)

### Distro & Version

Arch Linux

### Related package version

deepin-image-viewer 1.2.23-2

The crash does not happen with 1.2.22-1.

**Comment by antechdesigns** [comment]
I have same problem.

**Comment by felixonmars** [comment]
Is this crash still present in latest 1.3.0 release?

**Comment by antechdesigns** [comment]
I get this @felixonmars 
**Deepin Image Viewer (deepin-image-viewer)  1.3.0-2**

`Nov 04 08:46:11 archdeepin systemd-coredump[6762]: Process 6727 (deepin-image-vi) of user 1000 dumped core.
                                                   
                                                   Stack trace of thread 6727:
                                                   #0  0x00007f87dde9fd7f raise (libc.so.6)
                                                   #1  0x00007f87dde8a672 abort (libc.so.6)
                                                   #2  0x00007f87dca60816 n/a (librsvg-2.so.2)
                                                   #3  0x00007f87dca4d791 n/a (librsvg-2.so.2)
                                                   #4  0x00007f87dca4f619 n/a (librsvg-2.so.2)
                                                   #5  0x00007f87dca4f4d4 n/a (librsvg-2.so.2)
                                                   #6  0x00007f87dc8fd277 n/a (librsvg-2.so.2)
                                                   #7  0x00007f87dc89e652 n/a (librsvg-2.so.2)
                                                   #8  0x00007f87dc89d25b n/a (librsvg-2.so.2)
                                                   #9  0x00007f87dcaa7833 n/a (librsvg-2.so.2)
                                                   #10 0x00007f87dcaa6f93 n/a (librsvg-2.so.2)
                                                   #11 0x00007f87dc8a4325 n/a (librsvg-2.so.2)
                                                   #12 0x00007f87dc90a12a n/a (librsvg-2.so.2)
                                                   #13 0x00007f87dc8e8f9b n/a (librsvg-2.so.2)
                                                   #14 0x00007f87dc8a6854 n/a (librsvg-2.so.2)
                                                   #15 0x00007f87dc8eb73a n/a (librsvg-2.so.2)
                                                   #16 0x00007f87dc8a41c1 n/a (librsvg-2.so.2)
                                                   #17 0x00007f87dc90818b n/a (librsvg-2.so.2)
                                                   #18 0x00007f87dc8e8f9b n/a (librsvg-2.so.2)
                                                   #19 0x00007f87dc8a6854 n/a (librsvg-2.so.2)
                                                   #20 0x00007f87dc8eb73a n/a (librsvg-2.so.2)
                                                   #21 0x00007f87dc8a41c1 n/a (librsvg-2.so.2)
                                                   #22 0x00007f87dc90818b n/a (librsvg-2.so.2)
                                                   #23 0x00007f87dc8e8f9b n/a (librsvg-2.so.2)
                                                   #24 0x00007f87dc8a6854 n/a (librsvg-2.so.2)
                                                   #25 0x00007f87dc8eb73a n/a (librsvg-2.so.2)
                                                   #26 0x00007f87dc8a41c1 n/a (librsvg-2.so.2)
                                                   #27 0x00007f87dc90818b n/a (librsvg-2.so.2)
                                                   #28 0x00007f87dc8e8f9b n/a (librsvg-2.so.2)
                                                   #29 0x00007f87dc8a6854 n/a (librsvg-2.so.2)
                                                   #30 0x00007f87dc8eb73a n/a (librsvg-2.so.2)
                                                   #31 0x00007f87dc8a41c1 n/a (librsvg-2.so.2)
                                                   #32 0x00007f87dc90818b n/a (librsvg-2.so.2)
                                                   #33 0x00007f87dc8e8f9b n/a (librsvg-2.so.2)
                                                   #34 0x00007f87dc8a6854 n/a (librsvg-2.so.2)
                                                   #35 0x00007f87dc8eb73a n/a (librsvg-2.so.2)
                                                   #36 0x00007f87dc90aca1 n/a (librsvg-2.so.2)
                                                   #37 0x00007f87dc8a41c1 n/a (librsvg-2.so.2)
                                                   #38 0x00007f87dc909298 n/a (librsvg-2.so.2)
                                                   #39 0x00007f87dc8e8f9b n/a (librsvg-2.so.2)
                                                   #40 0x00007f87dc8a6854 n/a (librsvg-2.so.2)
                                                   #41 0x00007f87dc8a6b65 n/a (librsvg-2.so.2)
                                                   #42 0x00007f87dc897dc2 rsvg_handle_render_cairo_sub (librsvg-2.so.2)
                                                   #43 0x00007f87df778f3e _ZNK3Dtk6Widget19DSvgRendererPrivate8getImageERK5QSizeRK7QString (libdtkwidget.so.2)
                                                   #44 0x00007f87df77901c _ZNK3Dtk6Widget12DSvgRenderer7toImageE5QSizeRK7QString (libdtkwidget.so.2)
                                                   #45 0x00007f87d0e4d742 _ZN13QSvgIOHandler4readEP6QImage (libdsvg.so)
                                                   #46 0x00007f87dea87828 _ZN12QImageReader4readEP6QImage (libQt5Gui.so.5)
                                                   #47 0x00007f87dea87e86 _ZN12QImageReader4readEv (libQt5Gui.so.5)
                                                   #48 0x00007f87deaa0e20 _ZN15QPlatformPixmap8fromFileERK7QStringPKc6QFlagsIN2Qt19ImageConversionFlagEE (libQt5Gui.so.5)
                                                   #49 0x00007f87dea9a466 _ZN7QPixmap4loadERK7QStringPKc6QFlagsIN2Qt19ImageConversionFlagEE (libQt5Gui.so.5)
                                                   #50 0x000055e6f7861404 n/a (deepin-image-viewer)
                                                   #51 0x00007f87df036658 _ZN7QWidget5eventEP6QEvent (libQt5Widgets.so.5)
                                                   #52 0x00007f87deff6e14 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                                   #53 0x00007f87deffe6e1 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                                   #54 0x00007f87df7b2a39 _ZN3Dtk6Widget12DApplication6notifyEP7QObjectP6QEvent (libdtkwidget.so.2)
                                                   #55 0x00007f87de5d9c39 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                                   #56 0x00007f87df02eedc _ZN14QWidgetPrivate14sendPaintEventERK7QRegion (libQt5Widgets.so.5)
                                                   #57 0x00007f87df02f7c6 _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.s>
                                                   #58 0x00007f87df0303fe _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWid>
                                                   #59 0x00007f87df02f43d _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.s>
                                                   #60 0x00007f87df0303fe _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWid>
                                                   #61 0x00007f87df02f43d _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.s>
                                                   #62 0x00007f87df0303fe _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWid>
                                                   #63 0x00007f87df02f43d _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.s>
                                                   
                                                   Stack trace of thread 6732:
                                                   #0  0x00007f87ddf58c21 __poll (libc.so.6)
                                                   #1  0x00007f87db9dcee0 n/a (libglib-2.0.so.0)
                                                   #2  0x00007f87db9dcfce g_main_context_iteration (libglib-2.0.so.0)
                                                   #3  0x00007f87de62cfc9 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                                   #4  0x00007f87de5d88cc _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                                   #5  0x00007f87de421eb9 _ZN7QThread4execEv (libQt5Core.so.5)
                                                   #6  0x00007f87de884ba6 n/a (libQt5DBus.so.5)
                                                   #7  0x00007f87de42bf65 n/a (libQt5Core.so.5)
                                                   #8  0x00007f87dcf9fa9d start_thread (libpthread.so.0)
                                                   #9  0x00007f87ddf63b23 __clone (libc.so.6)
                                                   
                                                   Stack trace of thread 6736:
                                                   #0  0x00007f87dcfa5afc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                   #1  0x00007f87dc95ea42 n/a (librsvg-2.so.2)
                                                   #2  0x00007f87dc9588f4 n/a (librsvg-2.so.2)
                                                   #3  0x00007f87dc959176 n/a (librsvg-2.so.2)
                                                   #4  0x00007f87dc95b05c n/a (librsvg-2.so.2)
                                                   #5  0x00007f87dca64b1a n/a (librsvg-2.so.2)
                                                   #6  0x00007f87dc95aadb n/a (librsvg-2.so.2)
                                                   #7  0x00007f87dca5fceb n/a (librsvg-2.so.2)
                                                   #8  0x00007f87dcf9fa9d start_thread (libpthread.so.0)
                                                   #9  0x00007f87ddf63b23 __clone (libc.so.6)
                                                   
                                                   Stack trace of thread 6728:
                                                   #0  0x00007f87ddf58c21 __poll (libc.so.6)
                                                   #1  0x00007f87dbcb4630 n/a (libxcb.so.1)
                                                   #2  0x00007f87dbcb62db xcb_wait_for_event (libxcb.so.1)
                                                   #3  0x00007f87d4be1c5a n/a (libQt5XcbQpa.so.5)
                                                   #4  0x00007f87de42bf65 n/a (libQt5Core.so.5)
                                                   #5  0x00007f87dcf9fa9d start_thread (libpthread.so.0)
                                                   #6  0x00007f87ddf63b23 __clone (libc.so.6)
                                                   
                                                   Stack trace of thread 6730:
                                                   #0  0x00007f87ddf58c21 __poll (libc.so.6)
                                                   #1  0x00007f87db9dcee0 n/a (libglib-2.0.so.0)
                                                   #2  0x00007f87db9dcfce g_main_context_iteration (libglib-2.0.so.0)
                                                   #3  0x00007f87d2ef4bde n/a (libdconfsettings.so)
                                                   #4  0x00007f87db9a63eb n/a (libglib-2.0.so.0)
                                                   #5  0x00007f87dcf9fa9d start_thread (libpthread.so.0)
                                                   #6  0x00007f87ddf63b23 __clone (libc.so.6)
                                                   
                                                   Stack trace of thread 6737:
                                                   #0  0x00007f87dcfa5afc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                   #1  0x00007f87dc95ea42 n/a (librsvg-2.so.2)
                                                   #2  0x00007f87dc9588f4 n/a (librsvg-2.so.2)
                                                   #3  0x00007f87dc959176 n/a (librsvg-2.so.2)
                                                   #4  0x00007f87dc95b05c n/a (librsvg-2.so.2)
                                                   #5  0x00007f87dca64b1a n/a (librsvg-2.so.2)
                                                   #6  0x00007f87dc95aadb n/a (librsvg-2.so.2)
                                                   #7  0x00007f87dca5fceb n/a (librsvg-2.so.2)
                                                   #8  0x00007f87dcf9fa9d start_thread (libpthread.so.0)
                                                   #9  0x00007f87ddf63b23 __clone (libc.so.6)
                                                   
                                                   Stack trace of thread 6729:
                                                   #0  0x00007f87ddf58c21 __poll (libc.so.6)
                                                   #1  0x00007f87db9dcee0 n/a (libglib-2.0.so.0)
                                                   #2  0x00007f87db9dcfce g_main_context_iteration (libglib-2.0.so.0)
                                                   #3  0x00007f87db9dd022 n/a (libglib-2.0.so.0)
                                                   #4  0x00007f87db9a63eb n/a (libglib-2.0.so.0)
                                                   #5  0x00007f87dcf9fa9d start_thread (libpthread.so.0)
                                                   #6  0x00007f87ddf63b23 __clone (libc.so.6)
                                                   
                                                   Stack trace of thread 6731:
                                                   #0  0x00007f87ddf58c21 __poll (libc.so.6)
                                                   #1  0x00007f87db9dcee0 n/a (libglib-2.0.so.0)
                                                   #2  0x00007f87db9ddf62 g_main_loop_run (libglib-2.0.so.0)
                                                   #3  0x00007f87da5fac28 n/a (libgio-2.0.so.0)
                                                   #4  0x00007f87db9a63eb n/a (libglib-2.0.so.0)
                                                   #5  0x00007f87dcf9fa9d start_thread (libpthread.so.0)
                                                   #6  0x00007f87ddf63b23 __clone (libc.so.6)
                                                   
                                                   Stack trace of thread 6738:
                                                   #0  0x00007f87dcfa5afc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                   #1  0x00007f87dc95ea42 n/a (librsvg-2.so.2)
                                                   #2  0x00007f87dc9588f4 n/a (librsvg-2.so.2)
                                                   #3  0x00007f87dc959176 n/a (librsvg-2.so.2)
                                                   #4  0x00007f87dc95b05c n/a (librsvg-2.so.2)
                                                   #5  0x00007f87dca64b1a n/a (librsvg-2.so.2)
                                                   #6  0x00007f87dc95aadb n/a (librsvg-2.so.2)
                                                   #7  0x00007f87dca5fceb n/a (librsvg-2.so.2)
                                                   #8  0x00007f87dcf9fa9d start_thread (libpthread.so.0)
                                                   #9  0x00007f87ddf63b23 __clone (libc.so.6)
                                                   
                                                   Stack trace of thread 6735:
                                                   #0  0x00007f87dcfa5afc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                   #1  0x00007f87dc95ea42 n/a (librsvg-2.so.2)
                                                   #2  0x00007f87dc9588f4 n/a (librsvg-2.so.2)
                                                   #3  0x00007f87dc959176 n/a (librsvg-2.so.2)
                                                   #4  0x00007f87dc95b05c n/a (librsvg-2.so.2)
                                                   #5  0x00007f87dca64b1a n/a (librsvg-2.so.2)
                                                   #6  0x00007f87dc95aadb n/a (librsvg-2.so.2)
                                                   #7  0x00007f87dca5fceb n/a (librsvg-2.so.2)
                                                   #8  0x00007f87dcf9fa9d start_thread (libpthread.so.0)
                                                   #9  0x00007f87ddf63b23 __clone (libc.so.6)
                                                   
                                                   Stack trace of thread 6733:
                                                   #0  0x00007f87dcfa5afc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                   #1  0x00007f87dc95ea42 n/a (librsvg-2.so.2)
                                                   #2  0x00007f87dc9588f4 n/a (librsvg-2.so.2)
                                                   #3  0x00007f87dc959176 n/a (librsvg-2.so.2)
                                                   #4  0x00007f87dc95b05c n/a (librsvg-2.so.2)
                                                   #5  0x00007f87dca64b1a n/a (librsvg-2.so.2)
                                                   #6  0x00007f87dc95aadb n/a (librsvg-2.so.2)
                                                   #7  0x00007f87dca5fceb n/a (librsvg-2.so.2)
                                                   #8  0x00007f87dcf9fa9d start_thread (libpthread.so.0)
                                                   #9  0x00007f87ddf63b23 __clone (libc.so.6)
                                                   
                                                   Stack trace of thread 6759:
                                                   #0  0x00007f87dcfa5ef6 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                                                   #1  0x00007f87de42c5fd _ZN14QWaitCondition4waitEP6QMutexm (libQt5Core.so.5)
                                                   #2  0x00007f87de424024 n/a (libQt5Core.so.5)
                                                   #3  0x00007f87de42bf65 n/a (libQt5Core.so.5)
                                                   #4  0x00007f87dcf9fa9d start_thread (libpthread.so.0)
                                                   #5  0x00007f87ddf63b23 __clone (libc.so.6)
                                                   
                                                   Stack trace of thread 6734:
                                                   #0  0x00007f87dcfa5afc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                   #1  0x00007f87dc95ea42 n/a (librsvg-2.so.2)
                                                   #2  0x00007f87dc9588f4 n/a (librsvg-2.so.2)
                                                   #3  0x00007f87dc959176 n/a (librsvg-2.so.2)
                                                   #4  0x00007f87dc95b05c n/a (librsvg-2.so.2)
                                                   #5  0x00007f87dca64b1a n/a (librsvg-2.so.2)
                                                   #6  0x00007f87dc95aadb n/a (librsvg-2.so.2)
                                                   #7  0x00007f87dca5fceb n/a (librsvg-2.so.2)
                                                   #8  0x00007f87dcf9fa9d start_thread (libpthread.so.0)
                                                   #9  0x00007f87ddf63b23 __clone (libc.so.6)
`

**Comment by felixonmars** [comment]
I can still very easily reproduce this on 1.3.6-1. @hualet Any hints?

**Comment by random2324** [comment]
The crash went away for me. Thx for fixing this.

**Comment by yech1990** [comment]
error still exist!

```bash
$ sudo pacman -Qi librsvg
Name            : librsvg
Version         : 2:2.44.11-1
Description     : SVG rendering library
Architecture    : x86_64
URL             : https://wiki.gnome.org/Projects/LibRsvg
Licenses        : LGPL
Groups          : None
Provides        : None
Depends On      : gdk-pixbuf2  pango  libcroco
Optional Deps   : None
Required By     : adwaita-icon-theme  dtkwidget  gegl  gimp  graphviz  gtk-update-icon-cache  gtk2  gtk3
Optional For    : gegl02  libmagick  libmagick6
Conflicts With  : None
Replaces        : None
Installed Size  : 5.85 MiB
Packager        : Jan Alexander Steffens (heftig) <jan.steffens@gmail.com>
Build Date      : Mon 31 Dec 2018 12:20:26 AM CST
Install Date    : Sun 06 Jan 2019 03:32:56 PM CST
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```
```bash
sudo pacman -Qi deepin-image-viewer
Name            : deepin-image-viewer
Version         : 1.3.7-1
Description     : Deepin Image Viewer
Architecture    : x86_64
URL             : https://github.com/linuxdeepin/deepin-image-viewer
Licenses        : GPL3
Groups          : deepin
Provides        : None
Depends On      : deepin-qt5integration  libexif  freeimage  libraw  qt5-svg  deepin-shortcut-viewer
Optional Deps   : deepin-manual: view the help manual [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 5.44 MiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Fri 04 Jan 2019 04:53:52 AM CST
Install Date    : Sun 06 Jan 2019 03:25:50 PM CST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```
```bash
deepin-image-viewer
"dtkwidget2" can not find qm files
"deepin-image-viewer" can not find qm files
Setting file: "/home/yc/.config/deepin/deepin-image-viewer/config.conf"
2019-01-06, 15:35:23.822 [Debug  ] [                                                         0] LogFile: "/home/test/.cache/deepin/deepin-image-viewer/deepin-image-viewer.log"
/usr/bin/rm: cannot remove '/home/test/.local/share/deepin/deepin-image-viewer/deepinimageviewer.db': No such file or directory
[1]    3011 segmentation fault (core dumped)  deepin-image-viewer
```

**Comment by SiamSami** [comment]
Apparently, I am getting the same error...

**Comment by hualet** [comment]
> I also got that issue now that I upgraded from 1.3.6 to 1.3.7.
> Previously I only had librsvg updated.
> 
> I think this is a new introduced regression with 1.3.7. so that actually a new issue but still reopening this one.

How can I reproduct that? the same way as it was?

**Comment by hualet** [comment]
anyone can get me a backtrace ?

**Comment by felixonmars** [comment]
@justforlxz What for? The code didn't mention openmp anywhere...

**Comment by felixonmars** [comment]
And I tried to add openmp into the build env. Still the same crash, no difference.

**Comment by felixonmars** [comment]
Fixes with https://cr.deepin.io/#/c/deepin-image-viewer/+/41305/

I'll patch the Arch package for now.

**Comment by random2324** [comment]
This is working now. Thanks!
