### ISSUE TITLE
[archlinux]dde-session-daemon的内存泄露还没修复？

### ISSUE THREAD

**Issue by kirigayakazushin** [linuxdeepin/developer-center#61]
![20160308202922](https://cloud.githubusercontent.com/assets/12298476/13601663/b399407a-e56c-11e5-8b19-5f4af362f43b.png)
开机8小时。

**Comment by snyh** [comment]
什么都没干．．　8小时就这样了??  　是否用deepin-feedback(可以让开发者看到log日志)提交了bug?

**Comment by fasheng** [comment]
gccgo 下的内存泄露问题，公司内其他嵌入台也一直都有。。

**Comment by zhuzilinuser** [comment]
arch貌似还没有deepin-feedback，我知道是gccgo的问题，但是这个。。还要等多久才能解决掉呢。。

**Comment by fasheng** [comment]
重复问题合并
https://github.com/linuxdeepin/developer-center/issues/100
