### ISSUE TITLE
Deepin file manager segfault 

### ISSUE THREAD

**Issue by antechdesigns** [linuxdeepin/developer-center#611]
Segfault in Deepin file manager 

Archlinux 

Just randomly checked dmesg for errors and found this:

`dde_file_manage[1667]: segfault at 8 ip 00007fe28c86e721 sp 00007fe26f3fca40 error 4 in libQt5Core.so.5.11.2[7fe28c68f000+2ac000]`

`Code: c3 e9 56 2c e3 ff 48 89 c3 e9 3c 2c e3 ff 90 66 2e 0f 1f 84 00 00 00 00 00 41 57 41 56 41 55 41 54 55 53 48 81 ec a8 00 00 00 <4c> 8b 7e 08 48 89 7c 24 18 4c 89 fd 64 48 8b 04 25 28 00 00 00 48`

**Comment by felixonmars** [comment]
Is this crash still present in latest 4.6.10 release?
