### ISSUE TITLE
Support higher display scaling (3x)

### ISSUE THREAD

**Issue by AInoob** [linuxdeepin/developer-center#612]
Hi is it possible to support higher display scaling? I have a 4K 15.3 Inch laptop, and on windows I am using 2.5x scaling. So it would be really helpful if deepin supports 2.5 or 3x display scaling.

I tried using:
gsettings set com.deepin.xsettings scale-factor 3
pkill -KILL -u username
And it shows that display scaling is 3, but nothing changed.

**Comment by zccrs** [comment]
I'm sorry, The maximum scale factoy that can be set currently is 2. But, you can setting it manually. Execute the following command: 

1. echo "QT_SCALE_FACTOR=3" >> ~/.pam_environment
2. gsettings set com.deepin.xsettings window-scale 3
3. gsettings set com.deepin.xsettings scale-factor 3

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-control-center/+/40167/

**Comment by liuwen123** [comment]
已修复
