### ISSUE TITLE
icontheme中包含中文图标

### ISSUE THREAD

**Issue by Decodetalkers** [linuxdeepin/developer-center#6129]
### SUMMARY | 问题概要

比如 https://github.com/linuxdeepin/deepin-desktop-theme/blob/master/flow/icons/flow/apps/512/%E5%B0%8F%E7%BA%A2%E4%B9%A6.png

请不要为了闭源软件增加icon,尤其是中文的icon名字。这是不允许的。如果闭源软件需要icon,请在打包时候自己携带，不应该往icon theme里面添加

请商店的开发者确认下商店上架应用是否使用了类似的icon名字

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
Deepin V23
```

### STEPS TO REPRODUCE | 复现步骤

比如 https://github.com/linuxdeepin/deepin-desktop-theme/blob/master/flow/icons/flow/apps/512/%E5%B0%8F%E7%BA%A2%E4%B9%A6.png

**Comment by BLumia** [comment]
关联，需要确认的事情： https://github.com/linuxdeepin/deepin-desktop-theme/pull/24#issuecomment-1725185046

**Comment by Decodetalkers** [comment]
@wineee

**Comment by wineee** [comment]
能不能把所有中文图标拆到单独一个包

**Comment by Decodetalkers** [comment]
> 能不能把所有中文图标拆到单独一个包

不应该有中文图标吧，而且这些都是闭源软件，应该软件自己带

**Comment by BLumia** [comment]
> 而且这些都是闭源软件，应该软件自己带

我们的设计提供了符合我们主题风格的图标而已。只是需要确认为什么设计会认为放中文的图标有效/到底有没有效，是不是真的有地方在生成和使用中文图标名，然后按实际情况决定接下来怎么处理。

如果之前的中文图标压根没地方在用，本身放进去完全没起过作用，那这些图标设计做了不是也白做嘛，这显然不符合设计人员的期望（（（

**Comment by Decodetalkers** [comment]
完成
