### ISSUE TITLE
File picker/chooser different in manjaro 

### ISSUE THREAD

**Issue by grumble9684** [linuxdeepin/developer-center#613]
## Description

The file picker/chooser dialog is different between the deepin distribution and manjaro-deepin. 

## To Reproduce
1. Install deepin distribution (virtual machine is fine)
2. Install Firefox (same with any browser and many other programs but Firefox illustrates the issue)
3. Go to any website that allows file upload and click to upload
4. The file picker offers nice realizable thumbnails and spacebar preview, perfect for large image folders
5. Install manjaro-deepin
6. Install Firefox
7. Go to any website that allows file upload and click to upload
8. The file picker is ugly, with tiny non-resizable thumbnails and very small previews

## Expected behavior

File picker should be the same across distributions when using the same desktop environment and the same programs. 

## Screenshots
Left - the good, clean picker from the deepin distro, opened with firefox. Right - the inferior picker from manjaro-deepin, again firefox
![untitled](https://user-images.githubusercontent.com/5859675/45925281-e5304180-bf1a-11e8-9d1d-91e4dd8252b4.png)

### Distro & Version

Deepin 15.7 with dde-file-manager 4.6.8.4.1 and Firefox 60.0.1-5 VS manjaro-deepin 17.1.12 with dde-file-manager 4.6.8.3.1 and Firefox 62.0.2

### Additional context

I don't believe package versions have a role here, as the differences are small and it's unlikely this issue was affected by recent updates. Note that "native" deepin programs like Deepin Movie use the superior picker even in manjaro.

**Comment by oberon-manjaro** [comment]
I assume Deepin might be using a custom file picker. Does Deepin have a customized version of firefox or some kind of plugin to make it use dde-file-manager?
Will be thankful for any insight here, @felixonmars @zccrs @BLumia :smiley:

**Comment by dwlsalmeida** [comment]
Patched GTK maybe?

**Comment by zccrs** [comment]
@dwlsalmeida Year, The Deepin GTK library is patched. See: https://github.com/linuxdeepin/dde-file-dialog-gtk

**Comment by dwlsalmeida** [comment]
How can I make a PKG for Arch?

**Comment by zccrs** [comment]
>           How can I make a PKG for Arch?

@felixonmars

**Comment by dwlsalmeida** [comment]
@felixonmars I can work on that with some guidance, see if this can get me started https://aur.archlinux.org/packages/gtk3-patched-filechooser-icon-view/

**Comment by keybreak** [comment]
This is highly anticipated by me in Manjaro Deepin! :)

**Comment by keybreak** [comment]
@zccrs @felixonmars 
Any comments / updates on this issue?
Maybe i can ask for help on manjaro forum, if you can give more specifics on why this isn't implemented.

Having very different open / save dialogs across different programs reduces productivity on Arch / Manjaro Deepin a lot...

And it's especially sad, knowing that original Linux Deepin doesn't have this problem.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
