### ISSUE TITLE
Wine seems to break workspace switching

### ISSUE THREAD

**Issue by ErikEklund** [linuxdeepin/developer-center#614]
## Describe the bug

When using Wine to play any game in full screen mode, the workspace commands (super + A / W / S) stops working after a while. When this happens, you will not enter the workspace view and the entire window manager seems to hang - no windows are clickable anymore and only keyboard input works. Seems to require a reboot to recover from.

## To Reproduce

* Start any full screen game through Wine / proton
* Use Super + A / W / S keys to switch to workspace view
* It works at first, but after a few keypresses (usually within seconds) the workspace view does not appear anymore
* Exit game, find that WM has stopped responding

## Expected behavior

That the workspace handling should work fine with Wine too.

### Distro & Version

Antergos, Deepin 15.7, kernel 4.18.9
deepin-wm 1.9.31-1

### Additional context

Tried so far:
journalctl -f shows nothing when the problem occurs. No process increases in CPU usage.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
