### ISSUE TITLE
联系R720  wireless支持

### ISSUE THREAD

**Issue by snyh** [linuxdeepin/developer-center#615]
## Describe the bug
See 
- https://www.jianshu.com/p/d7731e86379b
- https://bbs.deepin.org/forum.php?mod=viewthread&tid=169373

已知有问题的硬件
- 联想E42
- 联系R720

**Comment by licardoY** [comment]
补充:联想小新潮7000
联想小新潮7000有一天也突然不能连无线.用的上面简书的方法打开了

**Comment by snyh** [comment]
@electricface @hualet @zccrs 现在的网络开关是否有兼容  /sys/class/rfkill 的状态?

日志里面看，应该是驱动把wifi的硬件开关关闭了，不过实际情况需要有具体硬件确认

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
