### ISSUE TITLE
system does not go to sleep ... any quick fixes ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#616]
## Describe the bug
system fails to go to sleep ... the sound suggests its going to sleep but the very next moment it wakes up ... with the login screen ...

## To Reproduce

happens intermittently ... so can't reproduce it

### Distro & Version

Linux Deepin 15.7

### Additional context

Is there some service or app that i need to kill or restart that'll fix the sleep bug i keep encountering ... used to happen in ubuntu ... but seems even deepin is prone to the same issue occassionally !!!

**Comment by felixonmars** [comment]
You might have to checkout the journal and see what is waking up your machine. For me bluetooth and thunderbolt were causing such issues.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
