### ISSUE TITLE
【deepin_V23_beta3】【一般】【正常】【发散测试】【DDE】内测更新后，启动器里出现了DTK Exhibition的应用图标

### ISSUE THREAD

**Issue by kobe337** [linuxdeepin/developer-center#6169]
### SUMMARY | 问题概要

内测更新后，启动器里出现了DTK Exhibition的应用图标

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像版本： https://cdimage.uniontech.com/community/releases/23-Beta2/
内核版本：Linux deepin20-PC 6.1.32-amd64-desktop-hwe #23.01.00.20 SMP PREEMPT_DYNAMIC Mon Sep 11 14:16:03 CST 2023 x86_64 GNU/Linux
```

### PRE-REQUIREMENT | 预置条件

内测更新最新版本至20231110

### STEPS TO REPRODUCE | 复现步骤

1. v23版本内测源通过全量更新后，打开启动器进行查看

### OBSERVED RESULT | 观察到的结果

内测更新后，启动器里出现了DTK Exhibition的应用图标，点击无反应
![image](https://github.com/linuxdeepin/developer-center/assets/17869922/94ca7dbf-3fcf-4c6d-9d41-083274cbed3d)
通过命令行打开：
![image](https://github.com/linuxdeepin/developer-center/assets/17869922/18bbbd1d-79cf-4dad-b3c5-23a22fad85c2)
![2f1045e3f8904e2778638725ca9a47eb](https://github.com/linuxdeepin/developer-center/assets/17869922/3c1b19e2-4fd1-46bf-bda7-50b76423557a)

### EXPECTED RESULT | 期望的结果

启动器中不应生成无法点击启动的图标

**Comment by babyfengfjx** [comment]
@kamiyadm  请帮忙分析优化~

**Comment by FeiWang1119** [comment]
@babyfengfjx  麻烦安排测试回归！

**Comment by kobe337** [comment]
将在内测推送更新后，进行回归测试验证

**Comment by luodeepin** [comment]
验证不通过 
1. 这个问题场景有：
新装镜像，进行更新，再加入内测更新时，问题还存在
新装镜像，加入内测更新时，问题不存在
在新的launchpad上也需要看下图标情况
![image](https://github.com/linuxdeepin/developer-center/assets/96416089/02e4259d-35f8-4039-8897-de202dd6a7cc)

**Comment by BLumia** [comment]
launchpad 有个 bug，卸载（或隐藏）的图标在 launchpad 下次启动时才会消失，对应 bug： https://github.com/linuxdeepin/developer-center/issues/6116 。

@luodeepin 可以先验证下手动 killall dde-launchpad 后重新点击 launcher 图标，看看是否仍在，不在的话，dtkdeclarative 的修复就是没问题的。

**Comment by 18202781743** [comment]
玲珑默认有这个，导致am扫到了这个desktop,导致launcher显示有这个，之后玲珑也得提个集成才行，
![企业微信截图_1703231788306](https://github.com/linuxdeepin/developer-center/assets/20967670/a31437c8-3766-45a2-9938-f5ed83b5a706)

**Comment by luodeepin** [comment]
验证通过
org.deepin.Runtime  23.0.0.23
![DTK](https://github.com/linuxdeepin/developer-center/assets/96416089/bd29e7d7-0161-48db-afab-8fcfb9e3c27c)

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240102
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.7-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
【截图录屏】：

![image](https://github.com/linuxdeepin/developer-center/assets/62528742/27fe1048-1810-49e3-83ec-65abbab813fb)
