### ISSUE TITLE
File Manager select file Window does not change Theme

### ISSUE THREAD

**Issue by Faran52** [linuxdeepin/developer-center#617]
Whenever I try to upload the a file the select window does not have dark theme even though the file manager is applied to dark theme from the settings.

![image](https://user-images.githubusercontent.com/34020197/46280650-e0583700-c585-11e8-9397-e1d94a1a046c.png)

**Comment by BLumia** [comment]
ref: https://github.com/linuxdeepin/dde-file-manager/issues/46

**Comment by BLumia** [comment]
Still not resolved, reopening...

@wangjia12

**Comment by wangjia12** [comment]
We will solve this problem when start developing system themes in the future.
https://github.com/linuxdeepin/internal-discussion/issues/657
