### ISSUE TITLE
deepinid云服务模块集成申请（第四版）

### ISSUE THREAD

**Issue by Keima-lpj** [linuxdeepin/developer-center#6170]
### package information | 软件包信息

包名 | 版本
-- | --
deepin-sync-daemon | 6.0.23.2

### Package repository address | 软件包仓库地址

deb  [trusted=yes] https://aptly.uniontech.com/pkg/nonfree-beige-v2/release-candidate/ZGVlcGluaWTkupHmnI3liqHnrKzkuInova4yMDIzLTExLTEzIDEzOjQwOjU4/  unstable non-free

### changelog | 更新信息

修改了服务启动的dbus service，不再依赖StartManager和dbus-send拉起服务

### test suggestion | 测试建议

1. 未修改代码业务逻辑，可大致测试下流程是否正常

**Comment by myml** [comment]
能顺便做下这个功能吗？ https://doc.uniontech.com/docs/KlkKVZN8m1iMwYqd#anchor-JvqI

![企业微信截图_16998566816605](https://github.com/linuxdeepin/developer-center/assets/13045857/890dcf78-ff5b-4784-b85b-74b6482aa777)

**Comment by babyfengfjx** [comment]
@xuqi27837288  请开展集成验证。

**Comment by xuqi27837288** [comment]
【环境】：
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230927
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【结论】：
测试通过，暂无严重问题及影响

**Comment by Keima-lpj** [comment]
> 能顺便做下这个功能吗？把微信登陆和账户登陆换换位置，默认账号登陆 https://doc.uniontech.com/docs/KlkKVZN8m1iMwYqd#anchor-JvqI
> 
> ![企业微信截图_16998566816605](https://user-images.githubusercontent.com/13045857/282379671-890dcf78-ff5b-4784-b85b-74b6482aa777.png)

当时产品下需求的时候，就是要突出扫码登录的便利性，弱化账号密码登录，所以产品要求把扫码登录放到第一个，并且默认选中。
