### ISSUE TITLE
【deepin_V23_beta3】【严重】【紧急】【集成测试】【deepin ID】deepin ID登录框点击后对话框无法正常加载展示，导致无法登录deepin ID云服务

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#6174]
### SUMMARY | 问题概要

偶现问题

关联集成：

* https://github.com/linuxdeepin/developer-center/issues/6170

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/20230516
内核版本： Linux test-PC 5.18.17-amd64-desktop-community-hwe #20.01.00.02 SMP PREEMPT_DYNAMIC Thu Nov 10 14:18:31 CST 2022 x86_64 GNU/Linux

控制中心:6.0.33
```

### PRE-REQUIREMENT | 预置条件

进入控制中心

### STEPS TO REPRODUCE | 复现步骤

点击deepin ID登录按钮，观察是否弹出对话框可以正常进行登录操作

### OBSERVED RESULT | 观察到的结果

对话框无法正常加载展示，导致无法登录deepin ID云服务

https://github.com/linuxdeepin/developer-center/assets/62528742/d284e8b5-c453-4f4e-8b96-700e4c48b7e1

### EXPECTED RESULT | 期望的结果

对话框可以正常加载展示，可以正常登录deepin ID云服务

**Comment by Decodetalkers** [comment]
web 服务炸掉了吧。

**Comment by babyfengfjx** [comment]
@xuqi27837288   先确认是否属于子项目处理，如果是子项目处理，则在PMS上跟踪。

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta2镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230927
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
【截图录屏】：
https://github.com/linuxdeepin/developer-center/assets/62528742/6323e0ad-eeed-4bd3-a691-16b65227af38
