### ISSUE TITLE
System Sleep not working ... system wakes up after a second of screen off ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#618]
## Describe the bug

Off late i am experiencing the system failing to sleep ...

## Expected behavior

System should go to sleep when sleep is invoked

### Distro & Version

Linux Deepin 15.7

### Additional context
Let me know if you want to extract any information to trouble shoot this issue ... i am keeping my system in the sleep fail state for the purpose of trouble shooting ...

Let me know the data you require from this state.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
