### ISSUE TITLE
deepin terminal基于上游qtermwidget的分支版本预集成 终端边距 deepin样式搜索框

### ISSUE THREAD

**Issue by ArchieMeng** [linuxdeepin/developer-center#6199]
### package information | 软件包信息

包名 | 版本
-- | --
deepin-terminal | 6.0.5-dtermwidget

### Package repository address | 软件包仓库地址

源码地址：https://github.com/ArchieMeng/deepin-terminal/tree/update-terminalwidget
[deepin-terminal_6.0.5-dtermwidget.zip](https://github.com/linuxdeepin/developer-center/files/13360724/deepin-terminal_6.0.5-dtermwidget.zip)

### changelog | 更新信息

- 修复没有左右边距的问题
- 实现deepin样式的文本搜索框

### test suggestion | 测试建议

- 观察终端边距
- 测试ctrl + alt + F调起的那个搜索框

### Sphere of influence | 影响范围

全部终端功能

### ADDITIONAL INFORMATION | 额外补充

存在一些已知问题：
- 按Tab或某些键会触发闪退。
- 改变终端大小时，已有历史输出可能不会重排布局。

因为底层改动非常大，所以隐藏问题应该会很多，理解一下。主要测试本次集成实现的功能。

**Comment by babyfengfjx** [comment]
@kobe337  请开展集成验证。

**Comment by ArchieMeng** [comment]
关联Issue: https://github.com/linuxdeepin/developer-center/issues/3849

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Beta2/
源码地址：https://github.com/ArchieMeng/deepin-terminal/tree/update-terminalwidget
[deepin-terminal_6.0.5-dtermwidget.zip](https://github.com/linuxdeepin/developer-center/files/13360724/deepin-terminal_6.0.5-dtermwidget.zip)
内核：Linux deepin23-PC 6.1.32-amd64-desktop-hwe #23.01.00.20 SMP PREEMPT_DYNAMIC Fri May 12 14:47:29 CST 2023 x86_64 GNU/Linux
【结论】：
本次预集成的内容：边距与搜索框验证通过

终端搜索框
![zdss](https://github.com/linuxdeepin/developer-center/assets/17869922/575c197d-af4a-45fa-871d-76265805a29b)
终端文字边距优化
![image](https://github.com/linuxdeepin/developer-center/assets/17869922/8fef9d14-6613-47c0-990b-60ee06e7a676)
与研发同事沟通，本次修改了底层库，类似demo验证，待后续正式集成时，需关注终端闪退问题（执行命令或者使用自定义命令）
