### ISSUE TITLE
"Hide Advanced" button didn't revert to "Show Advanced" when expanding "Sound Effects" submenu

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#62]
Currently on the "Sound" tab of dde-control-center, when I try to expand "Sound Effects" after clicking on the "Show Advanced" button, the advanced controls were hidden while the text on the button is still "Hide Advanced". If I click to fold "Sound Effects", the control panel is still left in an inconsistent state where the text is "Hide Advanced" and the advanced controls are nowhere to find.

A demo:

![hide_advanced](https://cloud.githubusercontent.com/assets/1006477/13637914/c41ab55e-e644-11e5-8312-dc150d1645f4.gif)

**Comment by fasheng** [comment]
@hualet @sbwtw

**Comment by hualet** [comment]
It seems to be easy to fix, so I'll take this one shamelessly :joy:

**Comment by manateelazycat** [comment]
@felixonmars We will implement dde-control-center 3.0 in Deepin 15.4, so all UI problem won't fix.
Thanks for report! ;)
