### ISSUE TITLE
Graphics freeze randomly when using deepin-wm

### ISSUE THREAD

**Issue by carlocastoldi** [linuxdeepin/developer-center#620]
## Describe the bug

I've been experiencing since May 2018, i'd say

Graphics just randomly freeze with deepin-wm even tho i can move the mouse cursor. It can happen for a few mseconds as well as for a few seconds (moving the cursor often helps un-freezing the screen).

This doesn't happen if i'm using deepin-metacity instead.

Even tho it's not restricted to that, it's super annoying while watching videos & films with window effects enabled!
I've experienced it both with AMD graphics and iGPU

## To Reproduce

1. activate deepin-wm with `deepin-wm --replace`
2. Watch a video, play an animation (it can happen when scrolling too, but it's rarer)
3. See the freezes/stutters

### Distro & Version
**System**:    Host: Carlo-ArchLinux Kernel: 4.18.10-arch1-1-ARCH x86_64 bits: 64 compiler: gcc v: 8.2.1 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Desktop: Deepin 15.7 tk: Qt 5.11.2 info: dde-dock wm: DeepinWM dm: LightDM 1.28.0 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Distro: Antergos Linux 
**CPU**:       Topology: Quad Core model: Intel Core i5-6400 bits: 64 type: MCP arch: Skylake-S rev: 3 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;L2 cache: 6144 KiB 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 21704 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Speed: 800 MHz min/max: 800/3300 MHz Core speeds (MHz): 1: 800 2: 800 3: 800 4: 800 
**Graphics**:  Device-1: Intel HD Graphics 530 vendor: ASRock driver: i915 v: kernel bus ID: 00:02.0 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;chip ID: 8086:1912 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Device-2: Advanced Micro Devices [AMD/ATI] Tonga PRO [Radeon R9 285/380] vendor: XFX Pine 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;driver: amdgpu v: kernel bus ID: 01:00.0 chip ID: 1002:6939 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Display: x11 server: X.Org 1.20.1 driver: amdgpu,intel unloaded: fbdev,modesetting,vesa 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;alternate: ati resolution: 1920x1080~60Hz 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;OpenGL: renderer: AMD Radeon R9 380 Series (TONGA DRM 3.26.0 4.18.10-arch1-1-ARCH LLVM 8.0.0) 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v: 4.5 Mesa 18.3.0-devel (git-cb863de626) direct render: Yes 

### Related package version

deepin-wm-1.9.31 (even tho i "think" i started noticing the problem since May 2018 - so it could be from deepin-wm-1.9.25 onward) 

### Additional context

I've tried other Desktop Environments but with neither of them this appened, so i'm pretty sure it's not a driver issue (also because, as already stated above, i've trying both with AMD Graphics R9 360 and iGPU)

**Comment by felixonmars** [comment]
Do you get the freezes only in fullscreen applications? I have a similar issue but only in fullscreen. Disabling window effects (switch to deepin-metacity) helps too, and may be used as a workaround.

@sonald Any ideas?

**Comment by carlocastoldi** [comment]
Nope :\ I get it everywhere there is something that is supposed to "move". Sometime even just scrolling a page

**Comment by felixonmars** [comment]
I see. It might be a different issue then. Does switching off window effects (Ctrl + ` by default) fixes it for you?

**Comment by carlocastoldi** [comment]
> I see. It might be a different issue then. Does switching off window effects (Ctrl + ` by default) fixes it for you?

yeah, as i stated in the first post i only get this on deepin-wm. If i use deepin-metacity i have zero problems with it (apart it being uglier :v)

P.S. isn't shift+super+tab the default shortcut to disable window effects? 🤔

**Comment by sonald** [comment]
> As you can see moving the mouse often helps un-freezing the screen
this is the weird part. normally, if the freeze is caused by X11 operations (like grab), moving the mouse is impossible to help. Is this more like a rendering problem or driver issue ?

**Comment by carlocastoldi** [comment]
If i had to guess i'd say it's more a rendering problem.

Surely is not due to my gpu drivers as i experience these freeze both with the external amd card and the Intel integrated card

**Comment by sonald** [comment]
@carlocastoldi  so gnome environment is fine ?

**Comment by A-Siam** [comment]
same issue here using arch linux w/ dde

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
