### ISSUE TITLE
【deepin_V23_beta3】【一般】【有空】【集成测试】【玲珑应用】更新最新linglong-bin后,无法使用命令ll-cli install xxx安装应用

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#6204]
### SUMMARY | 问题概要

更新最新linglong-bin后,无法使用命令ll-cli install xxx安装应用
关联集成:https://github.com/linuxdeepin/developer-center/issues/6198

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址:https://cdimage.uniontech.com/community/releases/23-Beta2/deepin-desktop-community-23-Beta2-amd64.iso
集成仓库:deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-686:/dde/testing/ ./
```

### PRE-REQUIREMENT | 预置条件

1.临时修改/etc/os-release, /usr/lib/os-release 的id 和name，为debian。（假装这是一个debian系统）
2.观察/etc/profile.d/linglong.sh与/etc/X11/Xsession.d/21linglong文件是否存在。

### STEPS TO REPRODUCE | 复现步骤

1.安装仓库内最新版本linglong-bin
2.重启系统
3.使用命令ll-cli install org.deepin.music
4.观察安装结果

### OBSERVED RESULT | 观察到的结果

1.ll-cli install org.deepin.music安装失败
![image](https://github.com/linuxdeepin/developer-center/assets/96415804/57aeea0f-2afd-498d-8c81-42139ea42e9e)

### EXPECTED RESULT | 期望的结果

1.ll-cli install org.deepin.music安装成功

**Comment by babyfengfjx** [comment]
@kamiyadm  请进行优化~

**Comment by kamiyadm** [comment]
ostree 仓库初始化地址错误

**Comment by vivianxf** [comment]
验证镜像:[https://cdimage.uniontech.com/community/releases/23-Beta2/deepin-desktop-community-23-Beta2-amd64.iso(开启内测升级到最新版本)](https://cdimage.uniontech.com/community/releases/23-Beta2/deepin-desktop-community-23-Beta2-amd64.iso(%E5%BC%80%E5%90%AF%E5%86%85%E6%B5%8B%E5%8D%87%E7%BA%A7%E5%88%B0%E6%9C%80%E6%96%B0%E7%89%88%E6%9C%AC))
linglong-bin:1.3.17-1
验证步骤:提单的步骤
验证结果:通过
![image](https://github.com/linuxdeepin/developer-center/assets/96415804/45a09562-160d-411c-a621-a72a84e2d2ca)
