### ISSUE TITLE
【deepin_V23_beta3】【一般】【有空】【发散测试】【DDE】【launchpad】 搜索框中输入abababab，显示无搜索结果却显示画板图标

### ISSUE THREAD

**Issue by SuperEffie** [linuxdeepin/developer-center#6209]
### SUMMARY | 问题概要

[关联集成]：https://github.com/linuxdeepin/developer-center/issues/6179

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
版本信息：dde-launchpad：0.2.1
```

### STEPS TO REPRODUCE | 复现步骤

1. 使用命令sudo apt install dcc-insider-plugin下载相关包，注销后重新登录进入桌面
2. 控制中心-更新-技术预览选择预览版启动器后重启
3. 点击任务栏中启动器图标，打开启动器，启动器处于窗口模式
4. 搜索框中输入字符“abababab”，观察界面显示

### OBSERVED RESULT | 观察到的结果

界面显示无搜索结果，却显示画板图标
![sousuo](https://github.com/linuxdeepin/developer-center/assets/58986464/da2abbea-70b7-4562-a289-5243b56bf22d)

### EXPECTED RESULT | 期望的结果

界面仅显示无搜索结果，不显示应用图标

**Comment by babyfengfjx** [comment]
@BLumia  请进行优化~

**Comment by BLumia** [comment]
@SuperEffie 在升级 Qt 6 版本的 launchpad 后暂未观察到这个问题，麻烦再复现下试试看，看看是不是还有这个问题。

**Comment by SuperEffie** [comment]
@BLumia Qt6版本的launchapd中暂未复现该问题，全屏模式或窗口模式下均无。持续留意观察一段时间，待发版前验证后关闭此issue
【截图信息】：
![截图_选择区域_20231229111153](https://github.com/linuxdeepin/developer-center/assets/58986464/a90e31a8-cd9c-4ebf-85b0-4b39f9150744)
![截图_选择区域_20231229111134](https://github.com/linuxdeepin/developer-center/assets/58986464/ad24c8cb-f9a7-4400-ad31-0371cc6b1ded)

**Comment by luodeepin** [comment]
验证通过
![6209](https://github.com/linuxdeepin/developer-center/assets/96416089/9fc1edd8-4147-4a38-944c-c7e41d322d4a)

@SuperEffie 请在最新镜像、升级环境后，验证通过后，进行关闭处理
