### ISSUE TITLE
Doesn't change battery icon when charger is plugged or unplugged

### ISSUE THREAD

**Issue by Silvered99** [linuxdeepin/developer-center#621]
## Describe the bug

The battery icon doesn't change when charger is plugged or unplugged in laptop. It stays the same since the boot i.e. it shows charging if the charger was connected at the time of boot else doesn't.

## Enviroments

Distro: [Arch Linux - Deepin Desktop Enviroment]
Version: [15.7]

**Comment by haruyukilxz** [comment]
Is dock a fashion mode?

**Comment by Silvered99** [comment]
No, efficient mode

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
