### ISSUE TITLE
使用自定义pam模块，登录界面无密码输入框

### ISSUE THREAD

**Issue by pinkkmin** [linuxdeepin/developer-center#6244]
### SUMMARY | 问题概要

我正在UOS20 1060系统上编写自定义的pam模块，代码如下（只是一个样例）：
`#include <security/pam_modules.h>
#include <security/pam_ext.h>
#include <string.h>

// PAM模块入口函数，实现用户认证功能
PAM_EXTERN int pam_sm_authenticate(pam_handle_t *pamh, int flags, int argc, const char **argv) {
    const char *username = NULL;
    const char *password = NULL;
    int retval;

    // 获取用户名和密码
    retval = pam_get_user(pamh, &username, "Username: ");
    if (retval != PAM_SUCCESS) {
        return retval;
    }

    retval = pam_get_authtok(pamh, PAM_AUTHTOK, &password, "Password: ");
    if (retval != PAM_SUCCESS || password == NULL) {
        return retval;
    }

    // 进行身份验证
    if (strcmp(username, "test") != 0 || strcmp(password, "123abc") != 0) {
        return PAM_AUTH_ERR;
    }

    return PAM_SUCCESS;
}
`
pam配置文件如下（/etc/pam.d/common-auth）：
auth     [success=done auth_err=die ignore=ignore default=bad]    /usr/lib/security/libtest_pam.so

test@uos-PC:~$ ls /usr/lib/security/
libtest_pam.so pam_udcp.so

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
OS: UOS20 1060 桌面专业版
dde-session-shell 5.6.21-1 
dde-session-ui    5.6.16-1
lightdm           1.26.7.19-1+dde
```

### PRE-REQUIREMENT | 预置条件

使用自定义的pam模块

### STEPS TO REPRODUCE | 复现步骤

1. 修改pam配置文件使用自定义pam
2. 注销或重启

### OBSERVED RESULT | 观察到的结果

登录界面无密码输入框
![Snipaste_2023-11-21_17-34-44](https://github.com/linuxdeepin/developer-center/assets/56376954/80e7f88b-4223-4694-9f2a-8a5b31996e30)

### EXPECTED RESULT | 期望的结果

![Snipaste_2023-11-21_17-34-59](https://github.com/linuxdeepin/developer-center/assets/56376954/d2113ff1-526f-4c4f-8b0c-c0e7fda3f2ab)
![Uploading Snipaste_2023-11-21_17-34-59.png…]()

**Comment by BLumia** [comment]
你好，这里是 deepin 开源社区的缺陷跟踪面板，仅接受 deepin 社区版的缺陷跟踪反馈。UOS 商业版本相关支持请从 UOS 的支持渠道进行反馈。

感谢理解与支持。

**Comment by pinkkmin** [comment]
ok~ 谢谢
