### ISSUE TITLE
DCI 图标缩放时图标尺寸问题

### ISSUE THREAD

**Issue by 18202781743** [linuxdeepin/developer-center#6246]

**Comment by BLumia** [comment]
关联：https://github.com/linuxdeepin/developer-center/issues/6137 （已在 https://github.com/linuxdeepin/dde-launchpad/commit/41515a6822f7f3b10b3ac13eef1439a92663ee40 解决）

**Comment by 18202781743** [comment]
与 https://github.com/linuxdeepin/developer-center/issues/6137 尺寸问题相同
