### ISSUE TITLE
multistrap 打包

### ISSUE THREAD

**Issue by chenchongbiao** [linuxdeepin/developer-center#6259]
一个带有多个存储库支持的debootstrap替代品，使用apt来处理所有依赖问题和冲突。Multistrap包括对本地和外部架构引导环境的支持。外部引导只需要在最终设备上进行最少的配置。还支持清理生成的引导文件系统以删除下载的包和钩子，以便在包被解包后但在配置之前修改引导文件系统中的文件。

**Comment by chenchongbiao** [comment]
pr:
- [ ] https://github.com/deepin-community/multistrap/pull/1

**Comment by UTsweetyfish** [comment]
有时间把 mmdebstrap 打一下？

**Comment by chenchongbiao** [comment]
1
