### ISSUE TITLE
[archlinux] Launcher category style setting is not saved

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#63]
The launcher category style is stuck at "By category (icon)" here. No matter whatever I choose, it reverts to this one on next launch.

Demo:

![category](https://cloud.githubusercontent.com/assets/1006477/13638200/33aafa4a-e646-11e5-83b8-2e97f8ae9748.gif)

**Comment by fasheng** [comment]
Looks gccgo related #54

**Comment by fasheng** [comment]
dde-launcher adjusted UI before and the issue solved now.
