### ISSUE TITLE
My Desktop(with all my wallpapers and icons) disappearing ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#630]
## Describe the bug

I ran and update yesterday from the control center ... and since then i notice that my desktop with all its icon and wallpapers on my workspaces seem to be disappearing on me ... the default wallpaper across all 3 workspaces ad 3 icons of WPS apps are found instead.

When i log in after reboot my desktop is back but as i start working ... it seems to disappear ... no telling on when it is disappearing.

## Expected behavior

my desktop with all its icons and their placements should be as it is.

### Distro & Version

Linux Deepin 15.7

**Comment by aiamuzz** [comment]
some more observations that may help identify the issue ... there is a sequence to it ...

1. disable 'windows effect'
brings back my wallpaper and the desktop icons ... 

2. enable 'windows effect'
makes my desktop icons and wallpaper disappear with the default(out of the box) wallpaper ... I can't switch or change the wallpaper ... however please note the when i activate display windows in a workspace or across all workspace or go in for the workspace view ... the blurred background is that of my wall papers ... out of these view's the wallpaper is the default one ...

3. disable 'windows effect'
no change ... same as 2. ... only without the windows effect.

4.  enable 'windows effect'
my desktop icons are back but not my wallpaper ... default wallpaper continues at this point ... I can't switch or change the wallpaper ... however please note the when i activate display windows in a workspace or across all workspace or go in for the workspace view ... the blurred background is that of my wall papers ... out of these view's the wallpaper is the default one ...

the above 4 sequence of events repeat ... 

hope this above behavior helps identify & fix the issue.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
