### ISSUE TITLE
DDE项目核心平台迁移到 github

### ISSUE THREAD

**Issue by hualet** [linuxdeepin/developer-center#631]
### 目的：
1. 讨论更加开发、透明，让希望了解 deepin 产品设计方向和问题处理的用户可以参与讨论和贡献 idea
2. 加强大家对 github issue 的关注，解决习惯在 github 提交 issue 的贡献者长时间得不到响应的问题
3. 用 github PR 替换 gerrit 的 CL，方便贡献者提交 patch 
4. 熟悉、使用 github 提供的一站式服务，如 wiki、github pages 等，跟社区平台进行统一

### 推进：
- 第一步尝试把系统发布看板中的内容迁移到 github projects， 达到 1、 2 目的；
- 第二步尝试迁移 gerrit 代码审核系统到 github PR，达到 3 目的；
- 4 作为额外目标在使用过程中逐渐受益。

### 时间安排：
- 第一步十月份开始推广使用，到十二月份看效果如何 
- 第二步从15.8发布开始推广使用，也是到十二月份看效果如何

**Comment by hualet** [comment]
基础的 issue 使用说明

- 创建/删除 issue
- 分配 / 标签 / 里程碑
-

**Comment by hualet** [comment]
- 考虑内部 issue 放在单独的一个列表里面

**Comment by felixonmars** [comment]
@hualet

**Comment by yefeifei** [comment]
自己上传的图片看不到，但可以看到别人上传的

**Comment by hualet** [comment]
> 自己上传的图片看不到，但可以看到别人上传的

怎么可能……没有上传成功吧？

**Comment by hualet** [comment]
代码审核迁移 github，需要解决：

- [ ] 关闭 gerrit 上的项目
- [ ] 保护各个项目的 master 分支
- [ ] 建立 CI
- [ ] 更新 crp 项目

**Comment by hualet** [comment]
CI 添加内容：
- [ ] 打包验证
- [ ] 代码风格
- [ ] 拼写检查

**Comment by hualet** [comment]
github 代码审核问题：

- [ ] 如何审核
- [ ] 如何提交 patchset
- [ ] 如何修改别人的 PR

**Comment by fwinac** [comment]
kde有一个开发交流系统，可以去参考一下

**Comment by hualet** [comment]
> kde有一个开发交流系统，可以去参考一下

您具体指哪个？techbase?

**Comment by fwinac** [comment]
> > kde有一个开发交流系统，可以去参考一下
> 
> 您具体指哪个？techbase?

https://community.kde.org/Infrastructure/Phabricator
我以前尝试给他们贡献过kde connect android版的代码。感觉他们发起修改的方式，包括代码的审核都很好。你可以试一下他们贡献代码的流程。

**Comment by BLumia** [comment]
现在在重新逐步进行项目开发迁回 GitHub 的工作过程中。尽管目的是没有变化的，不过目前的状态而言，这个过程和此 issue 讨论时的差异太大了，已经没法再在这个 issue 跟进相关的进度，就暂时先关掉了。

当然后续仍然会尽可能保持社区的开放和透明，相关的资料百科，社区相关的文档会于随后逐渐补充和完善，随后也会考虑将迁移进度同步到此 repo 的 discussion 讨论版中。
