### ISSUE TITLE
时尚模式的任务栏，插件栏中有一个空白的插件

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/developer-center#632]
【测试环境】
dde-dock 4.7.3.3+r21+g6224d76
【预置条件】
任务栏设置为时尚模式
【测试步骤】
1.打开任务栏的托盘列表，查看托盘内的插件显示是否正确。
【预期结果】
1.托盘内的插件显示正确。
【测试结果】
1.存在一个空白的插件。
【问题级别】
提示
【出现概率】
100%

**Comment by justforlxz** [comment]
笔记本的电量显示没刷新图标

**Comment by hualet** [comment]
内部人员提交的 issue 统一到 internal-disscusion
