### ISSUE TITLE
安装器 deepin-installer 6.0.31 版本集成测试

### ISSUE THREAD

**Issue by ArchieMeng** [linuxdeepin/developer-center#6321]
### package information | 软件包信息

包名 | 版本
-- | --
deepin-installer | 6.0.31

### Package repository address | 软件包仓库地址

https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20231129/

### changelog | 更新信息

适配高分屏

### test suggestion | 测试建议

使用各种规格的屏幕进行安装测试，看安装器界面是否符合预期，不过小也不过大。
屏幕规格可以是768P, 1080P, 2K, 4K.

### Sphere of influence | 影响范围

安装器界面缩放大小。

### ADDITIONAL INFORMATION | 额外补充

关联Issue: https://github.com/linuxdeepin/developer-center/issues/6239

**Comment by ArchieMeng** [comment]
镜像链接已更新，可以安排测试了。@babyfjx

**Comment by babyfengfjx** [comment]
@kobe337  请开展回归验证。

**Comment by kobe337** [comment]
使用6.1的内核，安装器显示正常，5.15的内核显示不完整，[#6328](https://github.com/linuxdeepin/developer-center/issues/6328)

**Comment by ArchieMeng** [comment]
已更新镜像解决800x600分辨率屏幕的问题。https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20231130/deepin-23-beige-beta2-amd64-20231130-150850.iso

**Comment by kobe337** [comment]
验证5.15的内核问题仍存在，请修复

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20231201/deepin-23-beige-beta2-amd64-20231201-134104.iso
【结论】：
覆盖1K 2K 4K显示器，使用6.1和5.1的内测均测试通过，暂无严重问题及影响
