### ISSUE TITLE
Cursor Sticking

### ISSUE THREAD

**Issue by Geo-Locale** [linuxdeepin/developer-center#634]
## Describe the bug
I am having trouble with the cursor, it freezes and I have to vigorously shake it or tap it on my mouse pad for it to start moving again. I have never posted so I will probably go about this all wrong and I'm sure some will let me know but I have no idea where the actual cursor settings are nor what to do to make it stop acting the way it does? I am using Manjaro Deepin 15.7 X64. 

*A clear and concise description of what the bug is.*

## To Reproduce

*We can fix a bug faster if we can reproduce the bug, so provide steps to reproduce the bug is very helpful for us.*

## Expected behavior

*A clear and concise description of what you expected to happen.*

## Screenshots

*If applicable, add screenshots to help explain your problem.*

### Distro & Version

[e.g. Linux Deepin 15.7]

### Related package version

[e.g. dde-file-manager v1.7 (4.5.6.2-2)]

*If you are not sure about which package went wrong, you can provide a list of package and it's version which you thinks is probably related with your issue*

### Additional context

*Add any other context about the problem here. It will be very helpful for us to isolate the problem. We will ask for more details when needed so feel free to remove this section if you really don't know what to provide.*

**Comment by hualet** [comment]
Do you use a Bluetooth mouse?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
