### ISSUE TITLE
[Deepin Integration]~[V23-Beta3]  grub: 安装界面grub更新添加 [Safe graphics] 模式说明

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#6358]
### Package information | 软件包信息

包名 | 版本
--  | --
null | 

### Package repository address | 镜像地址

    https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20231205/

### Changelog | 更新信息

安装界面grub添加 [Safe graphics] 模式说明

### Test suggestion | 测试建议
验证 安全启动等安装场景

### Influence | 影响范围
镜像安装，启动

### ADDITIONAL INFORMATION | 额外补充
需求链接 https://cooperation.uniontech.com/app/6f20cf83-ef8a-4067-bac9-b05c6d6bbcb6/650800e20a1f50226ade22ca/650800e20a1f50226ade22cb/row/6551f11a-301e-459d-aa56-fa9e59f4066a 

https://doc.cicd.getdeepin.org/lFN2NbIWS8y_8kjW-8KM-Q

**Comment by babyfengfjx** [comment]
@kobe337  请开展集成验证。

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20231205/
【结论】：
测试通过，暂无严重问题及影响，覆盖场景包含引导界面查看、开启安全启动进行系统安装等
![image](https://github.com/linuxdeepin/developer-center/assets/17869922/5ba408e6-747c-4efe-85ec-f9a2ef51747e)
