### ISSUE TITLE
Can't login: Server error after login on Gitter with github

### ISSUE THREAD

**Issue by dumabg** [linuxdeepin/developer-center#637]
On _Setup for Gerrit_ in _Contribution Guidelines for Developers_
[https://github.com/linuxdeepin/developer-center/wiki/Contribution-Guidelines-for-Developers-en](https://github.com/linuxdeepin/developer-center/wiki/Contribution-Guidelines-for-Developers-en), the first step is _Sign in Gerrit through GitHub account_. After login with Github, the browser redirects to https://cr.deepin.io/oauth?code=cfb9d1f9e01c97e2aa71&state=MgiD1JnJMevYv1C2TIbO8SCnKf-b_EPTZTk6txgtMFg, and appears **Server error**:

![imagen](https://user-images.githubusercontent.com/35224760/47654359-65287780-db69-11e8-8cba-c23dfe98c165.png)

**Comment by hualet** [comment]
It should work after refreshing.
