### ISSUE TITLE
【deepin_V23_beta3】【一般】【有空】【发散测试】【DDE】【通知中心】点击通知中心里面 x 图标，没有关闭通知而是清除消息，图标与实际操作不符

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#6377]
### SUMMARY | 问题概要

经与产品经理沟通，这个 x 图标  存在误导

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
```

### PRE-REQUIREMENT | 预置条件

1. 安装镜像：镜像地址：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
2. 加入内测更新至最新版本

### STEPS TO REPRODUCE | 复现步骤

1. 点击任务栏上的时间日期 - 点击通知中心里面的 x 图标

### OBSERVED RESULT | 观察到的结果

1. 通知信息被清除
![99999999999](https://github.com/linuxdeepin/developer-center/assets/96416089/e5c61ba7-0975-40b8-9d6a-8d9882aab3fd)

### EXPECTED RESULT | 期望的结果

1. 更换成清除的图标

**Comment by meiyixiang** [comment]
此功能实际并非是关闭，将图标替换成扫把图标。功能逻辑与图形化显示内容保值一致。

**Comment by babyfengfjx** [comment]
@luodeepin  这个跟之前提的 图标含义不一致的问题重复 #6367  请标记重复问题，以 #6373 跟踪。
