### ISSUE TITLE
Can't clone repository: Permission denied (publickey)

### ISSUE THREAD

**Issue by dumabg** [linuxdeepin/developer-center#638]
How to clone a project?

For example, on Gerrit deepin-calendar appears this on "Clone this report": git clone ssh://cr.deepin.io:29418/deepin-calendar, but when I execute it, appears this error: Permission denied (publickey).

I've created a ssh key like explain on Settings / SSH Public Keys on cr.deepin.io, but cotinues with the same error: Permission denied (publickey). Even I've configured the public key on github with the same results.

**Comment by deepinzhangshuang** [comment]
you can clone project on github.

**Comment by hualet** [comment]
@dumabg don't clone in that way, you can go projects list and search for dde-calendar, click the project and enter project view, you'll see the cmdline to clone the project, choose "clone with commit-message hook" and "ssh" BTW.
