### ISSUE TITLE
Project ERROR: Failed to generate translation  (deepin-desktop-ts-convert doesn't exist)

### ISSUE THREAD

**Issue by dumabg** [linuxdeepin/developer-center#639]
I've cloned the dde-calendar project and opened the .pro file with Qt Creator.Build gives me this error:
Project ERROR: Failed to generate translation
/home/mabg/dde-calendar/translate_desktop.sh: línea 8: /usr/bin/deepin-desktop-ts-convert: No existe el fichero o el directorio

The file deepin-desktop-ts-convert doesn't exist.

**Comment by hualet** [comment]
you need the build dependecies installed first. 
> sudo apt build-dep dde-calendar

**Comment by dumabg** [comment]
It gives another error:

~$ sudo apt build-dep dde-calendar
Leyendo lista de paquetes... Hecho
E: Debe poner algunos URIs fuente («source») en su sources.list

**Comment by hualet** [comment]
you need to uncomment the line started with deb-src and do `sudo apt update ` before running the command I gave you above.
