### ISSUE TITLE
深度终端 deepin terminal 6.0.9 切换标签页快捷键 预集成测试

### ISSUE THREAD

**Issue by ArchieMeng** [linuxdeepin/developer-center#6392]
### package information | 软件包信息

deepin-terminal 6.0.9

### Package repository address | 软件包仓库地址

deb  [trusted=yes] https://aptly.uniontech.com/pkg/beige-v2/release-candidate/ZGVlcGluLXRlcm1pbmFsMjAyMy0wMy0wMSAxMTozMTozNQ/  unstable main

### changelog | 更新信息

调换切换上下一个标签页快捷键的顺序。（ctrl+tab 切下一个，ctrl+shift+tab切上一个）

### test suggestion | 测试建议

测试切换标签页的快捷键。

### Sphere of influence | 影响范围

快捷键设置

### ADDITIONAL INFORMATION | 额外补充

无

**Comment by babyfengfjx** [comment]
@kobe337  请开展集成验证。

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Beta2/
仓库：deb [trusted=yes] https://aptly.uniontech.com/pkg/beige-v2/release-candidate/ZGVlcGluLXRlcm1pbmFsMjAyMy0wMy0wMSAxMTozMTozNQ/ unstable main
内核：Linux deepin23-PC 6.1.32-amd64-desktop-hwe #23.01.00.20 SMP PREEMPT_DYNAMIC Fri May 12 14:47:29 CST 2023 x86_64 GNU/Linux
【结论】：
测试通过，暂无严重问题及影响,覆盖场景，默认标签页快捷键切换（ctrl+tab 切下一个，ctrl+shift+tab切上一个），自定义标签页快捷键切换。
