### ISSUE TITLE
org.deepin.browser/6.3.9.3 版本集成

### ISSUE THREAD

**Issue by kamiyadm** [linuxdeepin/developer-center#6407]
### package information | 软件包信息

org.deepin.browser | 6.3.9.3

### Package repository address | 软件包仓库地址

repoName: develop-snipe
url: http://10.0.36.228:9001

### changelog | 更新信息

修复使用代理问题
修复网页播放视频问题

### test suggestion | 测试建议

1. 修改仓库为测试仓库， ll-cli repo modify http://10.0.36.228:9001 --name develop-snipe
2. 安装浏览器, ll-cli install org.deepin.browser,  观察版本是否为6.3.9.2版本
3. 设置代理程序，观察浏览器是否能正常访问谷歌

### Sphere of influence | 影响范围
https://github.com/linuxdeepin/developer-center/issues/6485

**Comment by kamiyadm** [comment]
@babyfengfjx

**Comment by babyfengfjx** [comment]
@vivianxf  请优先处理此笔集成。

**Comment by vivianxf** [comment]
更新后浏览器无法打开,验证不通过,请及时修复~

**Comment by kamiyadm** [comment]
> 更新后浏览器无法打开,验证不通过,请及时修复~

已经更新到6.3.0.2版本

**Comment by vivianxf** [comment]
更新最新版本后,设置代理,浏览器仍然无法使用代理,无法访问谷歌,油管等网页

故,验证不通过~

**Comment by kamiyadm** [comment]
> 更新最新版本后,设置代理,浏览器仍然无法使用代理,无法访问谷歌,油管等网页
> 
> 故,验证不通过~

已在另一个集成单下修复
#developer-center/issues/6465

**Comment by kamiyadm** [comment]
新增https://github.com/linuxdeepin/developer-center/issues/6485 问题修复

**Comment by vivianxf** [comment]
集成验证通过,请及时合入:

1.添加仓库升级升级成功,包版本正确
2.issue #6485验证通过
3.系统基本能功能正常

综上所述 本次集成通过~
