### ISSUE TITLE
Feature Request ... Mouse scroll jump increments ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#642]
Hi,

It would be nice to control the number of lines the mouse scroll wheel could be programmed to scroll at ... basically the scroll wheel speed is determined by the number of lines it is set for scroll jumps ...

the current default is a little difficult to browse in the file manager ... its jumping too high(about 9 lines in single tactile scroll) as a result some files in the list are scrolling out of view to fast ... affecting efficiency of use.

**Comment by hualet** [comment]
@BLumia @zccrs

**Comment by aiamuzz** [comment]
@BLumia ... @zccrs ...

until you guys decide to incorporate this feature in the mouse settings ... i wouldn't mind a hack probably with `deconf` or a config file somewher ...  where i can manually enter the number of lines the scroll wheel can

**Comment by zccrs** [comment]
@wangjia12 This feature is not only in dde-file-manager, it should be a system level feature, it is effective for any application. The feature depend the mouse driver(libinput) functions, But the libinput is not support the feature, Maybe by the xserver-xorg-input-mouse can Implement it.
cc @jouyouyun

**Comment by zccrs** [comment]
https://unix.stackexchange.com/questions/307663/change-scroll-speed-with-libinput

**Comment by wangjia12** [comment]
You can try to adjust the mouse scroll speed to 1.This speed should be acceptable.

**Comment by aiamuzz** [comment]
> You can try to adjust the mouse scroll speed to 1.This speed should be acceptable.

@wangjia12  ... by 1 do you mean **1 line** per scroll click ? If so that will be too slow ... if we are talking about lines ... i think between 3-5 lines per scroll click should be practical not to fast not too slow

**Comment by hualet** [comment]
> > You can try to adjust the mouse scroll speed to 1.This speed should be acceptable.
> 
> @wangjia12 ... by 1 do you mean **1 line** per scroll click ? If so that will be too slow ... if we are talking about lines ... i think between 3-5 lines per scroll click should be practical not to fast not too slow

wait a minute, we already have scrolling speed settings in the mouse section, isn't that enough ?

**Comment by aiamuzz** [comment]
> > > You can try to adjust the mouse scroll speed to 1.This speed should be acceptable.
> > 
> > 
> > @wangjia12 ... by 1 do you mean **1 line** per scroll click ? If so that will be too slow ... if we are talking about lines ... i think between 3-5 lines per scroll click should be practical not to fast not too slow
> 
> wait a minute, we already have scrolling speed settings in the mouse section, isn't that enough ?

hahahahahaha ... nobody told me it was already implemented ... i thought @wangjia12 was referring to the scroll speed to 1 to @zccrs link ... and i have been going all over that link and i see percentages ...

this is really a comedy of errors !!!

ok ... this feature request is implemented ... thank you for considering !!!
