### ISSUE TITLE
文件复制对话框中文本内容在特定条件下显示不完整

### ISSUE THREAD

**Issue by dongfengweixiao** [linuxdeepin/developer-center#643]
## 缺陷描述

文件复制对话框在特定条件下显示不完整

## 复现步骤

1. 准备一个比较大的文件，将文件复制到U盘，在复制中途点击停止按钮后关闭复制对话框
2. 复制一个比较大的文件到U盘

> Deepin 15.8 dde-file-manager 1.8.2
> OS: Arch Linux

> 正常状态

![_dde-file-manager_20181102222623](https://user-images.githubusercontent.com/1300822/47921321-428eb980-deef-11e8-9b6f-2a911c5aeabe.png)

> 异常状态

![_dde-file-manager_20181102222757](https://user-images.githubusercontent.com/1300822/47921319-428eb980-deef-11e8-8406-5d068c56b994.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
