### ISSUE TITLE
Deamon network error.

### ISSUE THREAD

**Issue by Urgau** [linuxdeepin/developer-center#644]
## Describe the bug

> daemon/network : utils_dbus_nm.go:817: Scanning not allowed while unavailable or activating
>       ->  manager_device.go:476
>       ->  asm_amd64.s:1333

## To Reproduce

I don't no.

## Expected behavior

No error(s).

### Distro & Version

ArchLinux

### Related package version

dde-deamon ?

### Additional context

Error see in journalctl

**Comment by felixonmars** [comment]
Looks like a temporary state for me. Does networking work for you later?

**Comment by listenerri** [comment]
> Yes, it works without any problem. However, sometimes it happens that the wifi icon looped endlessly while I am connected to the wifi network and this is only happened when I wake up the PC.

this problem is same as https://github.com/linuxdeepin/internal-discussion/issues/194

**Comment by electricface** [comment]
https://cr.deepin.io/#/c/dde/dde-daemon/+/40510
