### ISSUE TITLE
卸载玲珑应用时，未清理 user systemd

### ISSUE THREAD

**Issue by myml** [linuxdeepin/developer-center#6444]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20231205/

linglong-bin: 1.3.17-1
```

### STEPS TO REPRODUCE | 复现步骤

1. 使用 ll-cli uninstall org.dde.calendar 卸载玲珑版日历
2. 使用 apt install dde-calendar 安装 dpkg 版日历

### OBSERVED RESULT | 观察到的结果

在使用apt安装日历时会发生错误：
`Failed to enable unit: Unit file com.dde.calendarserver.calendar.timer does not exist.
Failed to start com.dde.calendarserver.calendar.timer: Unit com.dde.calendarserver.calendar.timer not found.`

查看 `~/.config/systemd/user` 目录，systemd service 未被清理
```txt
lrwxrwxrwx 1 deepin deepin  101 12月14日 09:36 com.dde.calendarserver.calendar.service -> ../../../../../persistent/linglong/entries/share/systemd/user/com.dde.calendarserver.calendar.service
lrwxrwxrwx 1 deepin deepin   99 12月14日 09:36 com.dde.calendarserver.calendar.timer -> ../../../../../persistent/linglong/entries/share/systemd/user/com.dde.calendarserver.calendar.timer
```

### EXPECTED RESULT | 期望的结果

在卸载玲珑应用时应该清理对应 `~/.config/systemd/user` 目录的文件

**Comment by kamiyadm** [comment]
不用清理, dpkg似乎也没这个行为
