### ISSUE TITLE
Deepin-Unioncode 1.2.3-1版本的deb安装包程序运行，任务栏没有图标

### ISSUE THREAD

**Issue by GershonWang** [linuxdeepin/developer-center#6445]
### SUMMARY | 问题概要

链接地址：https://github.com/linuxdeepin/deepin-unioncode/releases/download/1.2.3/deepin-unioncode_1.2.3-1_amd64.deb
使用github下载的deepin-ide，安装运行后，任务栏没有图标
![截图_选择区域_20231214103606](https://github.com/linuxdeepin/developer-center/assets/35024305/c0dccc12-b86b-483b-a1e2-1ed82d1fe517)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
系统版本：deepin v23 Beta2
软件版本：deepin-unioncode_1.2.3-1_amd64.deb
```

### STEPS TO REPRODUCE | 复现步骤

1.下载软件https://github.com/linuxdeepin/deepin-unioncode/releases/download/1.2.3/deepin-unioncode_1.2.3-1_amd64.deb
2.安装并运行
3.程序启动，任务栏没图标

**Comment by babyfengfjx** [comment]
@kobe337  可以确认一下。

**Comment by kobe337** [comment]
根据页面信息显示，此版本目前是在20.9上完成了打包
![image](https://github.com/linuxdeepin/developer-center/assets/17869922/0fd0132d-bb15-4656-b960-3f59e503781f)

**Comment by kobe337** [comment]
@tsl115 请问目前有适配社区v23的版本吗，有用户在反馈希望在v23进行使用哈

**Comment by kobe337** [comment]
@GershonWang 哈喽，经过确认，目前这个版本Deepin-Unioncode 1.2.3-1版本只在v20.9的商店上进行了上架，v23暂时还未适配哈

**Comment by tsl115** [comment]
> @tsl115 请问目前deepin-unioncode有适配社区v23版本的计划吗
现在只在v20.9社区版上了，v23还没,后面应该会弄
