### ISSUE TITLE
Status bar popup

### ISSUE THREAD

**Issue by dusatvoj** [linuxdeepin/developer-center#645]
I have dock in efficient mode at the bottom of my screen. I cannot access to popups as wifi and sound control, because these popups are shown under dock

**Comment by i-curve** [comment]
对的 ，我也遇到了同样的问题，deepin系统的pppoe在wifi下根本无发启动

**Comment by dusatvoj** [comment]
I noticed that it's repaired in the newest version. Thanks guys
