### ISSUE TITLE
iamhyc65 - 15.8反馈

### ISSUE THREAD

**Issue by iamhyc** [linuxdeepin/developer-center#646]
- [x] titlebar样式不统一问题，目前发现：
  - [x] flatpak更新后 title样式+字体 都不对
![_ _20181105162334](https://user-images.githubusercontent.com/9068301/47986272-2705f780-e117-11e8-86a1-e325af85f792.png)
  - [x] 文管预览窗口关闭按钮样式
  - [x] 应用商店`关闭按钮`hover时位移
![_ _20181105162421](https://user-images.githubusercontent.com/9068301/47986323-50268800-e117-11e8-984c-3726c8112a9e.gif)

- [x] 控制中心`通知`底部未对齐，有很宽一条背景（没有blur）(算了算了)
- [x] Grub菜单在ASUS ZX50上位置偏移，偏右下角

持续更新，确认修复后会打钩

**Comment by zccrs** [comment]
文管预览窗口的是那样的没问题

**Comment by zccrs** [comment]
关于控制中心的，能上传个图吗

**Comment by iamhyc** [comment]
almost everything fixed. now close this issue.
