### ISSUE TITLE
Chrome常规窗口无法在最小化后被隐身窗口恢复

### ISSUE THREAD

**Issue by dongfengweixiao** [linuxdeepin/developer-center#647]
复现步骤：

1. chrome 安装此插件https://chrome.google.com/webstore/detail/fatkun-batch-download-ima/nnjjahlikiabnchcpehcpkdeckfgnohf?utm_source=chrome-ntp-icon （其他能打开新的窗口的插件应该也可以）
2. 打开一个隐身模式的 chrome 窗口
3. 点击 fatkun 后点击当前标签，会打开一个新的普通模式的 chrome 窗口
4. 将弹出的窗口最小化
5. 再次点击 fatkun
在 Windows 下，第五步后，最小化的窗口会弹出，且重新获得焦点，但是在 Deepin 中无法弹出。Linux 下的其他 WM 没有测试。

**Comment by hualet** [comment]
@zhaofangfangdeepin 请测试下

**Comment by zccrs** [comment]
@zhaofangfangdeepin 测试一下其它的wm

**Comment by liuwen123** [comment]
没有复现
