### ISSUE TITLE
系统中明明有Maven和JDK，可是IDE识别不到

### ISSUE THREAD

**Issue by 1797890817** [linuxdeepin/developer-center#6471]
### SUMMARY | 问题概要

系统中明明有Maven和JDK，可是IDE识别不到
例如：我已经自己配置了maven及环境变量，为什么不能自动识别呢？JDK也是同样不识别。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
IDE的关于页面不显示任何版本信息！
```

### STEPS TO REPRODUCE | 复现步骤

必现！

**Comment by BLumia** [comment]
这个缺陷汇报缺少的信息太多了：

- 什么系统，v20.9？v23 beta2？其它版本？
- maven 和 JDK 是从哪里装的，是从系统仓库吗？
- 如果 maven/JDK 是手动从网站下载的二进制并手动安装的，那么环境变量等配置是怎么操作的？
- 哪个 IDE，哪个版本的 IDE？

**Comment by BLumia** [comment]
过久无进一步信息，信息不足以复现问题，予以关闭。
