### ISSUE TITLE
【deepin_V23_beta3】【一般】【立即】【内测反馈】【deepin ID】更新升级至1215内测环境后,控制中心中deepin ID模块菜单图标样式展示异常

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#6472]
### SUMMARY | 问题概要

必现问题

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
1.安装镜像：https://cdimage.uniontech.com/community/releases/23-Beta2/deepin-desktop-community-23-Beta2-amd64.iso
```

### PRE-REQUIREMENT | 预置条件

更新至1215内测环境

### STEPS TO REPRODUCE | 复现步骤

进入控制中心,观察控制中心中deepin ID模块的图标样式展示效果

### OBSERVED RESULT | 观察到的结果

图标样式展示异常

![image](https://github.com/linuxdeepin/developer-center/assets/62528742/d6dbe2ba-56d8-4ad0-8ddc-e3ba2a90ba30)

### EXPECTED RESULT | 期望的结果

图标样式展示正常

![image](https://github.com/linuxdeepin/developer-center/assets/62528742/ffa578b2-4932-4f09-b1d2-dd982ba65da8)

**Comment by xuqi27837288** [comment]
@Decodetalkers 麻烦尽快分析一下该问题,谢谢~

**Comment by babyfengfjx** [comment]
@Decodetalkers  可以优先看一下此问题。

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta2镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20231031
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
【截图录屏】：

![image](https://github.com/linuxdeepin/developer-center/assets/62528742/5f186258-2167-4ace-a398-2c0cc80a0de2)
