### ISSUE TITLE
【deepin_V23_beta3】【一般】【立即】【集成测试】【DDE】【控制中心】安装UOS AI后，重启电脑后，在任务栏上没有默认显示uos ai的插件图标

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#6486]
### SUMMARY | 问题概要

关联集成：https://github.com/linuxdeepin/developer-center/issues/6469
在20上安装后，重启电脑是可以显示到任务栏上的

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/community/releases/23-Beta2/deepin-desktop-community-23-Beta2-amd64.iso
内核版本： 6.1.32-amd64-desktop-hwe #23.01.00.20
uos ai 1.1.3-1
```

### PRE-REQUIREMENT | 预置条件

【前置条件】

1. 安装镜像：https://cdimage.uniontech.com/community/releases/23-Beta2/deepin-desktop-community-23-Beta2-amd64.iso

2. 加入内测，更新至最新版本

### STEPS TO REPRODUCE | 复现步骤

1. 添加转测仓库，安装UOS AI
2. 重启电脑，查看uos ai的插件显示情况

### OBSERVED RESULT | 观察到的结果

2. 任务栏上没有 uos ai的插件显示
![image](https://github.com/linuxdeepin/developer-center/assets/96416089/e87af87b-6087-4dc7-a018-06ffef14c7da)

### EXPECTED RESULT | 期望的结果

2. uos ai插件默认显示到任务栏

**Comment by babyfengfjx** [comment]
@kegechen  帮忙看下这个是需要应用自己处理还是我们控制中心处理。

**Comment by kegechen** [comment]
![image](https://github.com/linuxdeepin/developer-center/assets/23466548/6f86be1b-b3f9-4731-9b4c-2c9469fe4634)

![image](https://github.com/linuxdeepin/developer-center/assets/23466548/87d3576c-b165-41a9-aba5-f6229101b875)

@luodeepin

**Comment by kegechen** [comment]
> @kegechen 帮忙看下这个是需要应用自己处理还是我们控制中心处理。

默认不在dock显示，在dock插件管理里面可以看到uosai的图标。不过功能貌似无法正常使用。点击无法正常显示窗口

**Comment by luodeepin** [comment]
嗯！在控制中心 勾选后是可以显示到任务栏，只是重启电脑后，没有默认显示到任务栏插件上。对比20上重启电脑是可以默认显示到 任务栏插件区域的

**Comment by kegechen** [comment]
20 没有 **快捷插件区域** ， 逻辑不一样，23 的默认插件 就是在快捷区域显示，除非拖动或者主动在控制中心设置显示才会在dock栏显示。

**Comment by kegechen** [comment]
非问题， dock默认显示的快捷插件是dock自带的一些插件，在默认配置docnfig文件中有。
`"power", "network", "shutdown", "show-desktop", "multitasking"`
其他插件默认都是在快捷插件区域。见上面备注

**Comment by luodeepin** [comment]
请产品经理评估 UOS ai 是否需要默认显示在任务栏

**Comment by meiyixiang** [comment]
控制中心UOS AI需要默认勾选在任务栏默认展示，此功能为V23beta3重要特性！

**Comment by kegechen** [comment]
dde-dock 6027 尽量带上 @tsic404

**Comment by kegechen** [comment]
https://github.com/linuxdeepin/developer-center/issues/6807 @luodeepin

**Comment by luodeepin** [comment]
验证通过

![6486](https://github.com/linuxdeepin/developer-center/assets/96416089/e58dc102-d0f2-45d2-85e2-643c972f4908)
