### ISSUE TITLE
【deepin_V23_beta3】【一般】【立即】【集成测试】【DDE】【控制中心】安装UOS AI后，重启电脑后，个性化插件中显示的 uos ai插件图标错误

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#6488]
### SUMMARY | 问题概要

关联集成：https://github.com/linuxdeepin/developer-center/issues/6469

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/community/releases/23-Beta2/deepin-desktop-community-23-Beta2-amd64.iso
内核版本： 6.1.32-amd64-desktop-hwe #23.01.00.20
uos ai 1.1.3-1
控制中心 6.0.35
```

### PRE-REQUIREMENT | 预置条件

1.安装镜像：https://cdimage.uniontech.com/community/releases/23-Beta2/deepin-desktop-community-23-Beta2-amd64.iso

2. 加入内测，更新至最新版本

### STEPS TO REPRODUCE | 复现步骤

1.添加转测仓库，安装UOS AI
2.重启电脑，在控制中心- 个性化 桌面的插件中，查看uos ai的插件显示情况

### OBSERVED RESULT | 观察到的结果

2. 插件图标显示错误
![截图_选择区域_20231218135514](https://github.com/linuxdeepin/developer-center/assets/96416089/e55d9c8b-3533-4d5d-8398-0ef980c4d5cc)

### EXPECTED RESULT | 期望的结果

2. 插件图标显示正确

**Comment by babyfengfjx** [comment]
@kegechen  先帮忙看下是否是控制中心这边处理，如需要子项目处理，我们再转PMS跟踪。

**Comment by kegechen** [comment]
插件自行检查是否正确提供图标， 是否正确的实现了以下方法。
```cpp
virtual QIcon icon(const DockPart &dockPart, DGuiApplicationHelper::ColorType themeType = DGuiApplicationHelper::instance()->themeType());
```
dockPart == DockPart::DCCSetting 就是 `dock` 要在 `dcc` 上显示的插件的图标
如果没有提供图标那么将使用这个默认图标 

![dcc_dock_plug_in](https://github.com/linuxdeepin/developer-center/assets/23466548/a7a29530-5a8c-47b8-94d2-ae4cc847510a)

**Comment by kegechen** [comment]
@babyfengfjx 需要子项目自行处理，插件没有提供图标，所以是默认图标

**Comment by luodeepin** [comment]
转PMS跟踪
单号：https://pms.uniontech.com/bug-view-235465.html
