### ISSUE TITLE
【deepin_V23_beta3】【一般】【立即】【集成测试】【DDE】【任务栏】任务栏上显示uos ai插件图标样式变形

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#6489]
### SUMMARY | 问题概要

关联集成：https://github.com/linuxdeepin/developer-center/issues/6469

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/community/releases/23-Beta2/deepin-desktop-community-23-Beta2-amd64.iso
内核版本： 6.1.32-amd64-desktop-hwe #23.01.00.20
uos ai 1.1.3-1
控制中心 6.0.35
任务栏 6.0.25
```

### PRE-REQUIREMENT | 预置条件

1.安装镜像：https://cdimage.uniontech.com/community/releases/23-Beta2/deepin-desktop-community-23-Beta2-amd64.iso
2.加入内测，更新至最新版本

### STEPS TO REPRODUCE | 复现步骤

1.添加转测仓库，安装UOS AI
2.重启电脑，在控制中心- 个性化 桌面的插件中 勾选 uos ai显示到任务栏
3. 在任务栏上查看uos ai的插件显示情况

### OBSERVED RESULT | 观察到的结果

3. 插件图标显示变形
![截图_选择区域_20231218140503](https://github.com/linuxdeepin/developer-center/assets/96416089/e16e5df2-c298-44b0-8075-0eb2e92f2f81)

### EXPECTED RESULT | 期望的结果

3. 插件图标显示正常，没有变形等情况

**Comment by babyfengfjx** [comment]
@tsic404  请帮忙分析~

**Comment by BLumia** [comment]
已和 @tsic404 确认，是 UOS AI 的问题，请转到 UOS AI 一侧进行处理。

**Comment by luodeepin** [comment]
验证通过
https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240109/deepin-23-beige-beta3-amd64-20240109-105853.iso 
![6489](https://github.com/linuxdeepin/developer-center/assets/96416089/aabbb513-9094-4da1-b751-b7d243b35f3b)
