### ISSUE TITLE
deepin-keyring 2023.09.26 集成

### ISSUE THREAD

**Issue by UTsweetyfish** [linuxdeepin/developer-center#6490]
### package information | 软件包信息

包名 | 版本
-- | --
deepin-keyring | 2023.09.26

### Package repository address | 软件包仓库地址

单个 deb 文件

https://ci.deepin.com/repo/obs/deepin:/Develop:/main/standard/all/deepin-keyring_2023.09.26_all.deb

[deepin-keyring_2023.09.26_all.deb.gz](https://github.com/linuxdeepin/developer-center/files/13700434/deepin-keyring_2023.09.26_all.deb.gz)

#### deepin-keyring (2023.09.26) unstable; urgency=medium

  * Switch to 3.0 (native).
  * Depends on gpgv instead of gnupg, make deepin-keyring bootstrapable.

### test suggestion | 测试建议

测试安装后apt update等操作是否正常即可。

### ADDITIONAL INFORMATION | 额外补充

```shell
$ debdiff deepin-keyring_2021.06.07-1_all.deb deepin-keyring_2023.09.26_all.deb 
[The following lists of changes regard files as different if they have
different names, permissions or owners.]

Files in first .deb but not in second
-------------------------------------
-rw-r--r--  root/root   /usr/share/doc/deepin-keyring/changelog.Debian.gz

Control files: lines which differ (wdiff format)
------------------------------------------------
Depends: [-gnupg-] {+gpgv+}
Installed-Size: [-35-] {+34+}
[-Recommends: gpgv-]
Version: [-2021.06.07-1-] {+2023.09.26+}
```

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Beta2/
验证包：https://ci.deepin.com/repo/obs/deepin:/Develop:/main/standard/all/deepin-keyring_2023.09.26_all.deb
内核：Linux deepin-PC 6.1.32-amd64-desktop-hwe #23.01.00.20 SMP PREEMPT_DYNAMIC Mon Sep 11 14:16:03 CST 2023 x86_64 GNU/Linux
【结论】：
测试通过，暂无严重问题及影响，覆盖场景重启后，打开浏览器等场景
![image](https://github.com/linuxdeepin/developer-center/assets/17869922/481f2baa-759c-4b07-be13-d7ddc0209851)
