### ISSUE TITLE
文件管理器打开空目录会发生崩溃

### ISSUE THREAD

**Issue by myml** [linuxdeepin/developer-center#6494]
### SUMMARY | 问题概要

使用文件管理器打开新创建的空目录，文件管理器窗口闪退

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
dde-file-manager: 6.0.37+u033
```

### STEPS TO REPRODUCE | 复现步骤

1. 打开文件管理器
2. 使用鼠标右键菜单 “新建文件夹”
3. 鼠标双击打开创建的 “新建文件夹”

### OBSERVED RESULT | 观察到的结果

打开“新建文件夹时”，文件管理器窗口闪退

### EXPECTED RESULT | 期望的结果

能正常打开空目录

**Comment by myml** [comment]
@babyfengfjx 你知道文件管理器的bug给谁看吗？

**Comment by babyfengfjx** [comment]
@xuqi27837288  请转到PMS跟踪，这个是开发环境提前识别到的问题，已经拉群讨论了。

**Comment by xuqi27837288** [comment]
https://pms.uniontech.com/bug-view-235071.html

**Comment by xuqi27837288** [comment]
转移至PMS由文管团队跟踪处理，该问题单关闭~
