### ISSUE TITLE
Highlighted launcher category icon is wrong when cancelling a search

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#65]
If I cancel a search that started from another category than the first one, the right side of the screen (the applications) will be reset at the top while the left side (the highlighted category icon) is still at its previous location.

Demo:

![wrong_category](https://cloud.githubusercontent.com/assets/1006477/13638653/33d7baec-e648-11e5-92e1-8b930bf74563.gif)

**Comment by fasheng** [comment]
@dragondjf

**Comment by fasheng** [comment]
Looks solved now.
