### ISSUE TITLE
[Deepin Integration]~[V23-Beta3] Auto integrate from ostree by @l631197874 to V23-Beta3 by deepin-ci-robot

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#6519]
### Package information | 软件包信息

包名 | 版本
--  | --
ostree| 2022.4.1-2+dde

### Package repository address | 软件包仓库地址

    deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-795/testing/ ./

#### ostree (2022.4.1-2+dde) unstable; urgency=medium

  * fix: ostree_raw_file_to_content_stream: Make size default to 0

### Test suggestion | 测试建议
修复原子更新备份失败问题

**Comment by l631197874** [comment]
https://github.com/linuxdeepin/developer-center/issues/6429

**Comment by l631197874** [comment]
测试时升级 ostree 和 libostree-1-1 这两个包即可

**Comment by babyfengfjx** [comment]
@xuqi27837288 请优先处理此次集成验证。

**Comment by xuqi27837288** [comment]
【环境】：
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20231031
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【结论】：
测试通过，暂无严重问题及影响
