### ISSUE TITLE
Support wifi.scan-rand-mac-address 待测试

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#652]
## Describe the bug

Wifi passwords are repeatedly re-asked when wifi.scan-rand-mac-address is enabled (which is the default value).

## To Reproduce

Connect to a Wifi network. Disconnect and try to re-connect.

## Expected behavior

It connects.

## Enviroments:

Arch Linux

### Related package version

deepin-daemon 3.4.0-1

### Additional context

There was an issue created before: https://github.com/linuxdeepin/developer-center/issues/246

The resolution is to turn off the option. However this reduces privacy protection and makes the default setup less usable. I would like to revisit the decision and would very much prefer if dde-daemon could be changed to support wifi.scan-rand-mac-address correctly.

**Comment by deepinzhangshuang** [comment]
deepin 开启后似乎有扫描不到wifi的bug

**Comment by jouyouyun** [comment]
控制中心设置wifi链接时不要填入mac-addresses，这样这个链接就是对所有设备有效。
@electricface 处理下

**Comment by hualet** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/362 等这个问题处理了以后，相当于就支持了。
不过到时候还是不能把这个选项默认打开，因为用户里面已经有很多是绑定死了 mac 地址的，需要再过一个版本才能默认打开这个选项。

**Comment by listenerri** [comment]
这个可以测试了, 删除 `/etc/NetworkManager/NetworkManager.conf`文件中的以下内容, 或者将 `no`改为`yes` :
```
[device]
wifi.scan-rand-mac-address=no
```

修改之后重启电脑

**Comment by listenerri** [comment]
我自己测了一下, 还有问题, 好像任何无线网都连不上

**Comment by hualet** [comment]
@jouyouyun

**Comment by listenerri** [comment]
@electricface 这个也看一下吧

**Comment by listenerri** [comment]
@electricface 这个也看一下吧

**Comment by liuwen123** [comment]
已修复

**Comment by SSSSSnail** [comment]
emmmm, archlinux  dde环境下，复现了这个问题
 =，=   
按照https://wiki.archlinux.org/index.php/Deepin_Desktop_Environment_(简体中文)    中的无线网络无法连接处的提示修改，问题解决了
