### ISSUE TITLE
【deepin_V23_beta3】【一般】【有空】【集成测试】【DDE】【launchpad】简体中文环境，电源和控制中心在字母列表界面的提示为 英文

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#6520]
### SUMMARY | 问题概要

关联集成：https://github.com/linuxdeepin/developer-center/issues/6477

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
dde-launchpad 0.3.0
```

### PRE-REQUIREMENT | 预置条件

1.安装镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
2.加入内测，更新系统至最新环境
3.安装 dde-qt6xcb-plugin
4.重启电脑 - 安装：sudo apt install dcc-insider-plugin
5.重启电脑 - 在控制中心 - 更新 - 技术预览中切换模式为 dde-launchpad 技术预览
6. 启动器为窗口模式

### STEPS TO REPRODUCE | 复现步骤

1. 打开启动器 - 点击任意字母，进入字母列表
2. 将鼠标移动到左下角的 电源和控制中心图标上，查看提示语

### OBSERVED RESULT | 观察到的结果

2. 电源和控制中心在字母列表界面的提示为 英文
![录屏_选择区域_20231220111402](https://github.com/linuxdeepin/developer-center/assets/96416089/bbd8aa4c-a604-4f90-a48a-87eb0b2cdc75)

### EXPECTED RESULT | 期望的结果

2. 提示语为 简体中文

**Comment by babyfengfjx** [comment]
@BLumia  请进行优化~

**Comment by luodeepin** [comment]
验证通过
![录屏_选择区域_20240108133640](https://github.com/linuxdeepin/developer-center/assets/96416089/1187f3c0-8e93-465d-8e3c-afc381407023)
