### ISSUE TITLE
Sound and Network tray icon problem

### ISSUE THREAD

**Issue by SoyDiego** [linuxdeepin/developer-center#653]
## Describe the bug

Hi people, I have a problem with Manjaro-Deepin.

Before I could up or down volume with sound tray icon, but now I can’t . I do double clicked and nothing happen.

Before, a sound bar showed up above the sound icon, and there I changed my volume .
I can up or down sound with my keyboard shortcuts or if I going to settings panel.

The same problem with networks .

The others icons works well when I clicked. I have problems only with sound and networks.

Someone with the same issue? Can you help me?

Thanks

## Screenshots

![195625nz493innzioitozh](https://user-images.githubusercontent.com/19764334/48053471-1b641080-e1ab-11e8-871c-89a09028eeb8.png)

**Comment by antechdesigns** [comment]
@SoyDiego Its fixed in 15.8, you will have to wait for Manjaro to release updates, unless you switch to the Manjaro's testing branch.

**Comment by SoyDiego** [comment]
> @SoyDiego Its fixed in 15.8, you will have to wait for Manjaro to release updates, unless you switch to the Manjaro's testing branch.

ohh ok. So i must wait...
Thanks @antechdesigns for your reply :)

**Comment by SoyDiego** [comment]
Today Manjaro was updated and now I have:

Kernel 4.19.1-1-MANJARO and deepin was update also

And is solved the problem :)
