### ISSUE TITLE
Clean install of archlinux with DDE

### ISSUE THREAD

**Issue by antechdesigns** [linuxdeepin/developer-center#654]
## Describe the bug
High CPU usage after login

*A clear and concise description of what the bug is.*

If Enable window effect has been enabled the cpu throttles to nearly 100% (deepin-wm) 
If I turn off window effect CPU is normal (metacity)

## To Reproduce
Install arch linux with deepin desktop & enable window effect

I still have the install, if you would like anymore info let me know.

Thanks for your time and efforts ;)
[Youtube Video](https://youtu.be/WaXpmw5WFO0)

**Comment by felixonmars** [comment]
3D performance in virtualbox is expected to be very slow and resource consuming. I am afraid there is not much we can do here.

**Comment by antechdesigns** [comment]
> 3D performance in virtualbox is expected to be very slow and resource consuming. I am afraid there is not much we can do here.

Fully aware of that and I agree with you, however its the same on hardware, it was easier to show it in  VM instead of fighting my way through the hardware install with all the bugs.

Oh well, I think its time to move on, I seem to be spending more time debugging over the last week, than using my system.
This has happen'd once before with deepin, a perfectly working DE ruined in a couple of update ;(

**Comment by felixonmars** [comment]
@sonald Any hints for debugging?

**Comment by sonald** [comment]
There is no guarantee. the performance is good enough for me when I use virtualbox + deepin-wm. It highly depends on the environment.
