### ISSUE TITLE
文件管理器的可移动设备列表过滤了 loop 设备，但 disk-mount 插件没有过滤

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#655]
## 缺陷描述

本地有挂载的 loop 设备，在文件管理器的设备列表里未显示，但在 disk-mount 插件里仍然显示出来了。

## 复现步骤

挂载 loop 设备（如 iso，或其他 img）后，查看 dock 上的插件列表。

## 期望行为

不显示 loop 设备。

## 截图

![2018-11-09-023510-2a45de](https://user-images.githubusercontent.com/1006477/48219962-f5b45280-e3c8-11e8-8421-0a0a1ed2cd0e.png)
![2018-11-09-023502-d6f71e](https://user-images.githubusercontent.com/1006477/48219964-f64ce900-e3c8-11e8-8f0d-7864852a94cf.png)

```
$ df | grep loop
/dev/loop0      128G  1.8G  125G   2% /var/lib/archbuild
```

### 发行版以及版本

Arch Linux x86_64

### 相关的软件包版本

deepin-file-manager 1:4.6.10-2

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
