### ISSUE TITLE
深度文件管理器的常用目录希望能够自定义

### ISSUE THREAD

**Issue by zyd2001** [linuxdeepin/developer-center#656]
请将下方的缺陷汇报模板中的文字替换为您实际需要汇报的缺陷所对应的描述文字。

## 缺陷描述

我用的是arch 装的deepin桌面环境，所以最初home文件夹下面有我自己建的目录类似Documents这样，深度文件管理器自动创建的中文目录在终端里用起来很难受，而且不能删除和重命名

## 复现步骤

这应该不能算一个bug，不过不知道是不是archlinux打包的问题

## 期望行为

希望能够想Windows把这些目录当做软连接然后可以设置指向的位置

## 截图

![](https://i.loli.net/2018/11/11/5be732eea957e.png) 上面的中文目录就是文件管理器创建的，而且删除，重命名过后只要重开文件管理器就会被自动创建。
![](https://i.loli.net/2018/11/11/5be73511dec03.png)这是文件管理器里看上去的样子

### 发行版以及版本

Archlinux, Deepin 桌面环境，均是滚动的最新版本

### 相关的软件包版本

[deepin-file-manager 1:4.7.1-1](https://www.archlinux.org/packages/community/x86_64/deepin-file-manager/)

**Comment by BLumia** [comment]
这些文件夹是通过 `xdg-user-dir` 生成的，建议简单了解一下。这个并非深度文件管理器的特定行为。

请参见：

 - [Arch Wiki 上的 "XDG user directories (简体中文)" 条目](https://wiki.archlinux.org/index.php/XDG_user_directories_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87))
 - [freedesktop.org 上的相关页面](https://www.freedesktop.org/wiki/Software/xdg-user-dirs/)

**Comment by zyd2001** [comment]
感谢，问题解决了，不过我还是希望能有图形界面的设置，因为我觉得大部分人并不会知道`xdg-user-dir`，就没有办法更改，有一个设置应该不错

**Comment by BLumia** [comment]
@wangjia12

**Comment by wangjia12** [comment]
建议先使用上述方式操作，图形化界面暂时没有开发计划。需求较大的其他功能会优先开发。
