### ISSUE TITLE
【deepin_V23_beta3】【一般】【有空】【内测反馈】【输入法】使用五笔输入法开启Caps Lock键输入字母后,关闭Caps Lock键后无法继续输入汉字

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#6567]
### SUMMARY | 问题概要

必现问题

https://cooperation.uniontech.com/public/record/6588e77b406deda906a59bdf

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
安装镜像： https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20231205/
```

### PRE-REQUIREMENT | 预置条件

切换当前输入法为五笔输入法

### STEPS TO REPRODUCE | 复现步骤

开启Caps Lock键输入字母后,关闭Caps Lock键观察是否可以继续输入汉字

### OBSERVED RESULT | 观察到的结果

无法继续输入汉字

https://github.com/linuxdeepin/developer-center/assets/62528742/d0b0edf4-db89-460c-ba9c-e8677a85ef7c

### EXPECTED RESULT | 期望的结果

可以继续输入汉字

**Comment by babyfengfjx** [comment]
@dengbo11  请进行优化~

**Comment by dengbo11** [comment]
@xuqi27837288 开启Caps Lock键后就进入了快速输入模式，再次按Caps Lock键后此时模式依然是快速输入模式，需要按Enter键先推出快速输入模式，然后就可以正常输入中文了。

**Comment by xuqi27837288** [comment]
该使用场景稍后反馈给用户,让用户知晓~
