### ISSUE TITLE
Is kali Linux officially supported ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#658]
Hi,

Can **'Deepin Desktop Environment'** be installed on Kali Linux ? does deepin team officially support Kali Linux for its deepin applications besides the desktop enviroment ?

**Comment by felixonmars** [comment]
I don't think so. Kali is a Debian derivative and the Debian port is still an ongoing work.

**Comment by aiamuzz** [comment]
oh ... ok ...

I found quite a few deepin applications(screen & voice recorder, movie, terminal, screen capture ...) on kali ... however i couldn't find deepin file manager ... is it because of the delay in the debian port ?

**Comment by felixonmars** [comment]
Yes. You can check the progress of Debian port in their package search page: https://packages.debian.org/search?searchon=names&keywords=deepin

**Comment by BLumia** [comment]
FYI: https://tracker.debian.org/teams/pkg-deepin/

**Comment by aiamuzz** [comment]
Interesting that `dde` ... `dde-file-manager` ... `dde-control-center` ... have still not been created ... will it take time ?

**Comment by felixonmars** [comment]
It will. The Go components are still not ported, which made the core components not portable atm.

**Comment by aiamuzz** [comment]
oh ... :( ... given that Deepin OS is based on debian ... a layman would only think that debian OS would be the first to get(or things will work automatically there) a port of deepin suite of apps !!!

**Comment by aiamuzz** [comment]
I was just wondering if the deb installers will work on Debian OS or Kali OS if the deb installers were downloaded and installed from here ?

will they work or will they be broken because Deepin's debian port is still a WIP ... ?

http://ftp.vim.org/ftp/os/Linux/distr/deepin/pool/main/d/dde/
http://ftp.vim.org/ftp/os/Linux/distr/deepin/pool/main/d/dde-launcher/
http://ftp.vim.org/ftp/os/Linux/distr/deepin/pool/main/d/dde-dock/
http://ftp.vim.org/ftp/os/Linux/distr/deepin/pool/main/d/dde-daemon/
http://ftp.vim.org/ftp/os/Linux/distr/deepin/pool/main/d/dde-control-center/
http://ftp.vim.org/ftp/os/Linux/distr/deepin/pool/main/d/dde-file-manager/
http://ftp.vim.org/ftp/os/Linux/distr/deepin/pool/main/d/ddccontrol/

a deb file should work on any debian based OS'es ... don't they ?

**Comment by hualet** [comment]
It depends, deepin-deb-installer relies on Qt which may be not the same version of deepin, you can't even install it in this circumstance I think.
