### ISSUE TITLE
鼠标多次接入、拔出后，控制中心鼠标设置区域可能显示错乱

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#659]
## 缺陷描述

在鼠标多次接入、拔出后（如蓝牙鼠标连接、断开），控制中心鼠标设置区域显示为多个 panel 重叠在一起。

## 截图

![2018-11-13-173421-4b3ebb](https://user-images.githubusercontent.com/1006477/48404140-9a88b400-e76a-11e8-9f5e-a9e027b96a74.png)

### 发行版以及版本

Arch Linux x86_64

### 相关的软件包版本

deepin-control-center 4.7.4-1

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
