### ISSUE TITLE
deepin-installer|6.0.32 集成

### ISSUE THREAD

**Issue by ArchieMeng** [linuxdeepin/developer-center#6592]
### package information | 软件包信息

deepin-installer 6.0.32

### Package repository address | 软件包仓库地址

TBA

### changelog | 更新信息

适配用户头像新增。

### test suggestion | 测试建议

查看安装后初次启动时，检查账号可选头像列表是否完整。

### Sphere of influence | 影响范围

用户账号头像

### ADDITIONAL INFORMATION | 额外补充
镜像地址： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20231228/deepin-23-beige-beta3-amd64-20231228-104625.iso
相关PR: https://github.com/linuxdeepin/dde-account-faces/pull/34
相关集成：https://github.com/linuxdeepin/developer-center/issues/6571

**Comment by babyfengfjx** [comment]
@kobe337  请开展集成验证。

**Comment by kobe337** [comment]
https://github.com/linuxdeepin/developer-center/issues/6643

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20231228/deepin-23-beige-beta3-amd64-20231228-104625.iso
【结论】：
测试未通过，初次启动进入系统后，控制中心人物分类和创意插图分类中用户头像个数与安装器中数量不一致
