### ISSUE TITLE
A white square border flashes on the close button when clicking on the preview window popup of dock

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#66]
Demo:

![white_square](https://cloud.githubusercontent.com/assets/1006477/13638762/bc202556-e648-11e5-9ee7-c4298c17116b.gif)

**Comment by fasheng** [comment]
@sbwtw @Match-Yang

**Comment by hualet** [comment]
I think this issue is fixed by someone, can't reproduce it here anymore. @felixonmars
