### ISSUE TITLE
(dde-dock) dumped core

### ISSUE THREAD

**Issue by antechdesigns** [linuxdeepin/developer-center#660]
## Describe the bug
Right clicking shutdown icon in system tray crashes dde-dock (beautiful or efficient mode)

*A clear and concise description of what the bug is.*
(dde-dock) dumped core

## To Reproduce
Right click shutdown icon

Right click shutdown icon

## Expected behavior

*A clear and concise description of what you expected to happen.*
Expecting to see a pop up menu to shutdown, reboot, logout etc

### Distro & Version
archlinux Deepin 15.8

### Related package version
deepin-dock  4.7.9-1

Process 1296 (dde-dock) of user 1000 dumped core.

Stack trace of thread 1296:
#0  0x00005651b156112b n/a (dde-dock)
#1  0x00007fa1a0d93bd0 _ZN11QMetaObject8activateEP7QObjectiiPPv (libQt5Core.so.5)
#2  0x00007fa17d614512 _ZNK12PluginWidget18requestContextMenuERK7QString (libshutdown.so)
#3  0x00007fa17d60ad6e _ZN12PluginWidget15mousePressEventEP11QMouseEvent (libshutdown.so)
#4  0x00007fa1a19df13f _ZN7QWidget5eventEP6QEvent (libQt5Widgets.so.5)
#5  0x00007fa1a199ee14 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
#6  0x00007fa1a19a692a _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
#7  0x00007fa1a2092b19 _ZN3Dtk6Widget12DApplication6notifyEP7QObjectP6QEvent (libdtkwidget.so.2)
#8  0x00007fa1a0d69c39 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
#9  0x00007fa1a19a5c11 _ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0_Eb (libQt5Widgets.so.5)
#10 0x00007fa1a19f998c n/a (libQt5Widgets.so.5)
#11 0x00007fa1a19fc5d5 n/a (libQt5Widgets.so.5)
#12 0x00007fa1a199ee14 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
#13 0x00007fa1a19a66e1 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
#14 0x00007fa1a2092b19 _ZN3Dtk6Widget12DApplication6notifyEP7QObjectP6QEvent (libdtkwidget.so.2)
#15 0x00007fa1a0d69c39 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
#16 0x00007fa1a11180dc _ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE (libQt5Gui.so.5)
#17 0x00007fa1a111a066 _ZN22QGuiApplicationPrivate24processWindowSystemEventEPN29QWindowSystemInterfacePrivate17WindowSystemEventE (libQt5Gui.so.5)
#18 0x00007fa1a10f3a3c _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Gui.so.5)
#19 0x00007fa199317dad n/a (libQt5XcbQpa.so.5)
#20 0x00007fa1a0d688cc _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#21 0x00007fa1a0d70bc6 _ZN16QCoreApplication4execEv (libQt5Core.so.5)
#22 0x00005651b153e421 main (dde-dock)
#23 0x00007fa1a07a4223 __libc_start_main (libc.so.6)
#24 0x00005651b153e6ce n/a (dde-dock)

Stack trace of thread 1297:
#0  0x00007fa1a0870c21 __poll (libc.so.6)
#1  0x00007fa1a075c630 n/a (libxcb.so.1)
#2  0x00007fa1a075e2db xcb_wait_for_event (libxcb.so.1)
#3  0x00007fa199281c5a n/a (libQt5XcbQpa.so.5)
#4  0x00007fa1a0bbbf65 n/a (libQt5Core.so.5)
#5  0x00007fa19f27fa9d start_thread (libpthread.so.0)
#6  0x00007fa1a087bb23 __clone (libc.so.6)

Stack trace of thread 1299:
#0  0x00007fa1a0870c21 __poll (libc.so.6)
#1  0x00007fa19f75cee0 n/a (libglib-2.0.so.0)
#2  0x00007fa19f75cfce g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007fa1975c4bde n/a (libdconfsettings.so)
#4  0x00007fa19f7263eb n/a (libglib-2.0.so.0)
#5  0x00007fa19f27fa9d start_thread (libpthread.so.0)
#6  0x00007fa1a087bb23 __clone (libc.so.6)

Stack trace of thread 1298:
#0  0x00007fa1a0870c21 __poll (libc.so.6)
#1  0x00007fa19f75cee0 n/a (libglib-2.0.so.0)
#2  0x00007fa19f75cfce g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007fa19f75d022 n/a (libglib-2.0.so.0)
#4  0x00007fa19f7263eb n/a (libglib-2.0.so.0)
#5  0x00007fa19f27fa9d start_thread (libpthread.so.0)
#6  0x00007fa1a087bb23 __clone (libc.so.6)

Stack trace of thread 1300:
#0  0x00007fa1a0870c21 __poll (libc.so.6)
#1  0x00007fa19f75cee0 n/a (libglib-2.0.so.0)
#2  0x00007fa19f75df62 g_main_loop_run (libglib-2.0.so.0)
#3  0x00007fa19f0d2c28 n/a (libgio-2.0.so.0)
#4  0x00007fa19f7263eb n/a (libglib-2.0.so.0)
#5  0x00007fa19f27fa9d start_thread (libpthread.so.0)
#6  0x00007fa1a087bb23 __clone (libc.so.6)

Stack trace of thread 1301:
#0  0x00007fa1a0870c21 __poll (libc.so.6)
#1  0x00007fa19f75cee0 n/a (libglib-2.0.so.0)
#2  0x00007fa19f75cfce g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007fa1a0dbcfc9 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4  0x00007fa1a0d688cc _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5  0x00007fa1a0bb1eb9 _ZN7QThread4execEv (libQt5Core.so.5)
#6  0x00007fa1a17bcba6 n/a (libQt5DBus.so.5)
#7  0x00007fa1a0bbbf65 n/a (libQt5Core.so.5)
#8  0x00007fa19f27fa9d start_thread (libpthread.so.0)
#9  0x00007fa1a087bb23 __clone (libc.so.6)

dde-dock[797]: segfault at 0 ip 000055d02e85712b sp 00007fff708e3bb0 error 4 in dde-dock[55d02e82e000+4b000]

Code: c4 e9 1e b0 fd ff 90 0f 1f 84 00 00 00 00 00 55 48 8d 15 48 f1 ff ff 48 89 e5 41 57 41 56 41 55 41 54 53 48 81 ec 78 01 00 00 <48> 8b 07 48 89 bd 98 fe ff ff 48 8b 80 c8 01 00 00 64 48 8b 0c 25

**Comment by antechdesigns** [comment]
Fixed!! Good Job ;)

**Comment by BLumia** [comment]
Tip: Wrap the stack trace with the markdown code block markup (or by clicking "Insert code") to avoid referencing current issue to other unrelated issue:

\`\`\`
stack track here, then strings like `#1` won't reference to the 1st issue of current repo.
\`\`\`
