### ISSUE TITLE
The root of all partitions are not recording the column sort order in 'File Manager'

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#661]
## Describe the bug

just upgraded to Deepin 15.8 ... and testing ...

**the root of all partitions are not recording the column sort order in 'File Manager'**

## To Reproduce

set a sort order in the root of any partition, go to another partition and return to the partition you just set a sort order and the sort order settings is gone ...

## Expected behavior

the sort settings of the root of the partition is expected to be saved as per our preference.

### Distro & Version

Linux Deepin 15.8

### Related package version

dde-file-manager 4.7.1.1

**Comment by aiamuzz** [comment]
@hualet ... any progress on this ?

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/41348/
