### ISSUE TITLE
Deepin 15.8 ... the shortcut settings are missing in the latest 'File manager settings'

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#662]
The shortcut settings in the 'File Manager' settings are missing ...

is this a conscious decision ? If so ... how do we modify/edit the shortcuts to suits our preferences ?

I suspect its more of a bug that has failed to populate the shortcut settings !!!

Please fix this ...

PS : the 'Ctrl+Shift+?' displays the list of shortcuts but its just that one can't edit them in the settings window as the same are missing.

**Comment by BLumia** [comment]
@wangjia12

**Comment by wangjia12** [comment]
I'm afraid this feature is not in our plan at the moment, but we will keep it in mind, thanks for your suggestions

**Comment by aiamuzz** [comment]
> I'm afraid this feature is not in our plan at the moment, but we will keep it in mind, thanks for your suggestions

@wangjia12  ...

Didn't the file manager have the shortcuts in the settings window before or it was never there earlier and i  may have mistaken to have seen it ?
was this withdrawn in the latest update ?

**Comment by BLumia** [comment]
> Didn't the file manager have the shortcuts in the settings window before or it was never there earlier

Yes, we never got a shortcut setting for the `dde-file-manager`, some of other deepin apps have, e.g, the deepin editor.

**Comment by aiamuzz** [comment]
ok ... so i mistook it to be present earlier ... sorry ... **false alert !!!**
