### ISSUE TITLE
【deepin_V23_beta3】【一般】【有空】【内测反馈】【玲珑应用】最新版本linglong-bin下,ll-cli ps命令无法执行

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#6639]
### SUMMARY | 问题概要

最新版本linglong-bin下,ll-cli ps命令无法执行
关联集成:https://github.com/linuxdeepin/developer-center/issues/6619

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
[镜像地址]：https://cdimage.uniontech.com/community/releases/23-Beta2/deepin-desktop-community-23-Beta2-amd64.iso
linglong-bin:1.4.0-1
linglong-box:1.3.3.15-1
```

### STEPS TO REPRODUCE | 复现步骤

1.按照上述集成升级系统以及包版本
2.在终端输入命令:ll-cli ps 回车
3.观察现象

### OBSERVED RESULT | 观察到的结果

1.命令执行出来为空(实际有玲珑应用在运行)

### EXPECTED RESULT | 期望的结果

1.ll-cli ps命令可以正常执行,输出当前运行应用结果

**Comment by babyfengfjx** [comment]
@black-desk  请帮忙分析优化~

**Comment by black-desk** [comment]
https://github.com/linuxdeepin/linglong/pull/182

**Comment by vivianxf** [comment]
关联集成:https://github.com/linuxdeepin/developer-center/issues/6619
ps命令可以正常使用
issue验证通过
