### ISSUE TITLE
[Lock Screen] desktop visible when wrong password entered

### ISSUE THREAD

**Issue by mikeehun** [linuxdeepin/developer-center#664]
## Describe the bug

When you're on the lock screen, after entering a wrong password the screen reveals if you press ctrl+a.

## To Reproduce

When you're on the lock screen, after entering a wrong password the screen reveals if you press ctrl+a. Maybe there are other ways to reproduce this.

1. Go to lock screen
2. Enter wrong password
3. Press CTRL+A

## Expected behavior

The text in the input box is selected while the desktop content isn't revaled.

### Distro & Version

mikee@bender ~> lsb_release -a
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	18.0.0
Codename:	Illyria

mikee@bender ~> uname -a
Linux bender 4.19.1-1-MANJARO #1 SMP PREEMPT Sun Nov 4 16:05:34 UTC 2018 x86_64 GNU/Linux

### Related package version

deepin-launcher
(4.5.2-1)
deepin-desktop-base
(2:2018.7.23-1.1)

**Comment by hualet** [comment]
@justforlxz 好像是因为那个报错的 tooltip 造成的吧？

**Comment by liuwen123** [comment]
已修复
