### ISSUE TITLE
【deepin_V23_beta3】【严重】【立即】【集成测试】【玲珑应用】最新版本linglong-bin下,ll-cli upgrade 命令执行报错

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#6642]
### SUMMARY | 问题概要

最新版本linglong-bin下,ll-cli upgrade 命令执行报错
关联集成:https://github.com/linuxdeepin/developer-center/issues/6619

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
[镜像地址]：https://cdimage.uniontech.com/community/releases/23-Beta2/deepin-desktop-community-23-Beta2-amd64.iso
linglong-bin:1.4.0-1
linglong-box:1.3.3.15-1
```

### STEPS TO REPRODUCE | 复现步骤

1.按照上述集成升级系统以及包版本
2.在终端执行命令:ll-cli upgrade org.deepin.music 
3.观察现象

### OBSERVED RESULT | 观察到的结果

1. 执行ll-cli upgrade org.deepin.music 报error

### EXPECTED RESULT | 期望的结果

1. 执行ll-cli upgrade org.deepin.music 成功

**Comment by babyfengfjx** [comment]
@black-desk  请进行优化~

**Comment by black-desk** [comment]
https://github.com/linuxdeepin/linglong/pull/184

**Comment by vivianxf** [comment]
linglong-bin:1.4.0-1
linglong-box:1.3.4-1
最新版本验证ll-cli upgrade命令运行仍然报错,请修复后指派

**Comment by black-desk** [comment]
本次提测后错误信息有发生变化. 与之前的根因不同.

**Comment by black-desk** [comment]
这个bug涉及到代码上比较严重的设计问题 无法快速修复, 预估需要一周以上时间.

先采取一些不太正确的临时方案回避一下.

测试 https://github.com/linuxdeepin/linglong/pull/190 时请务必重点测试反复重启后玲珑的基础功能是否依然正常.
