### ISSUE TITLE
【deepin_V23_beta3】【严重】【紧急】【 预发布测试】【系统】无法安装wine应用，deepin-wine依赖不满足

### ISSUE THREAD

**Issue by SuperEffie** [linuxdeepin/developer-center#6648]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
【镜像地址】：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20231228/deepin-23-beige-beta3-amd64-20231228-104625.iso
【版本信息】：deepin-wine6-stable:6.0.0.64
```

### STEPS TO REPRODUCE | 复现步骤

打开应用商店，下载wine版微信，观察是否能正常下载

### OBSERVED RESULT | 观察到的结果

wine版微信下载失败

### EXPECTED RESULT | 期望的结果

正常下载wine应用

### ADDITIONAL INFORMATION | 额外补充

deepin-wine的依赖不满足，需重新适配deepin v23 beta3

**Comment by babyfengfjx** [comment]
@Zeno-sole  需要持续沟通推进deepin-wine在V23 BETA3的兼容问题。

**Comment by Zeno-sole** [comment]
@kobe337  wine项目组以提供对应版本，请关注后续的商店上架

**Comment by kobe337** [comment]
已确认，需要@ ComixHe解决缩放问题后，一并回归验证

**Comment by Zeno-sole** [comment]
@SuperEffie  请关注后续deepin-wine 商店上架流程

**Comment by SuperEffie** [comment]
【镜像地址】：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240109/deepin-23-beige-beta3-amd64-20240109-145932.iso 
【版本信息】：应用商店：8.0.5.0014
【验证结论】：测试通过，可正常下载wine版微信
【截图信息】：
![wine微信](https://github.com/linuxdeepin/developer-center/assets/58986464/fc8a141e-1a63-4973-a255-40b018b8b1d3)

**Comment by SuperEffie** [comment]
目前企业微信无法正常下载

**Comment by SuperEffie** [comment]
【镜像地址】：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240123/deepin-23-beige-beta3-amd64-20240123-100455.iso 
【版本信息】：deepin-wine8-stable：8.16-deepin11
【验证结论】：测试不通过，安装微信显示依赖报错
【截图信息】：
![wine8](https://github.com/linuxdeepin/developer-center/assets/58986464/449ddf32-bb37-49a7-a315-3e4aeffb84ff)

**Comment by Zeno-sole** [comment]
@SuperEffie @kobe337 wine项目组需要重新编译相关软件包，请对接wine项目组

**Comment by SuperEffie** [comment]
【关联pms】：https://pms.uniontech.com/bug-view-241171.html
【备注信息】：目前企业微信正常下载，微信无法下载，在pms平台进行跟踪，需wine项目组处理
