### ISSUE TITLE
Power management setting

### ISSUE THREAD

**Issue by lloydjharp** [linuxdeepin/developer-center#666]
After start up, monitor blanks at appx. 5 mins., regardless of monitor setting in power management. I've tried resetting the value in PM, only way that works is if I've opened at least one application. Help!!

**Comment by hualet** [comment]
Is it possible that is's set by your hardware?

**Comment by lloydjharp** [comment]
I've had other distros installed (Manjaro, Linux Mint, etc...) with no issues. I seem to be able to get it to observe the settings in Power Management by changing the setting (from never to one hour, then back again). I'm not convinced it's caused by hardware settings. Any other ideas?

**Comment by lloydjharp** [comment]
Logically, it's almost as if the Power Management settings don't load at startup. They only go into effect if: 1) I have a application OPEN, and 2) Then change the setting from "never" to "One hour" and then back to "never".

**Comment by tuxxllo** [comment]
Can I get an update on the progress of this status? I'm still dealing with Power Management issue with my monitor blanking out.

**Comment by hualet** [comment]
@electricface

**Comment by electricface** [comment]
Execute the command `xset q` and look at the timeout of the screen saver.
But I have never encountered such a strange situation.

**Comment by tuxxllo** [comment]
Update - I know this isn't going to tell us why it was happening, but I just ended up doing a clean install of Deepin 15.8... and it seemed to fix the power management issue. Thanks for all your help and effort with this.

**Comment by hualet** [comment]
Now I believe that it's caused by `Power Saving Mode`, the underneath `laptop-mode-tools` changes power management settings separately which conflicts with the settings in Control Center, maybe you can try to disable both `Auto Mode Switch` and `Power Saving Mode`, and see if it will be back to normal.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
