### ISSUE TITLE
【deepin_V23_beta3】【严重】【正常】【预发布测试】【安装器】【LENOVO_MT_82L7_XiaoXinAir 14+ Notebook】小新机器无法安装0102的v23 beta3镜像

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#6690]
### SUMMARY | 问题概要

必现问题

![image](https://github.com/linuxdeepin/developer-center/assets/62528742/edea10d1-9cb6-4c90-b8a3-f1aec7a291cc)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
安装镜像： https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240102

```

### PRE-REQUIREMENT | 预置条件

使用小新机器下载该镜像进行安装

### STEPS TO REPRODUCE | 复现步骤

观察是否可以正常安装成功

### OBSERVED RESULT | 观察到的结果

无法安装成功

### EXPECTED RESULT | 期望的结果

可以安装成功

**Comment by babyfengfjx** [comment]
@Zeno-sole  请帮忙分析一下~

**Comment by Zeno-sole** [comment]
5.15 ， 6.1 等版本内核安装正常，观察现象6.6内核在进行分区操作时卡住

**Comment by opsiff** [comment]
可以通过先安装5.15内核再安装6.6内核再对分区进行parted操作进行复现，分区parted的时候观察对应分区进程/proc/<pid>/stack 看到卡在内核栈wait 和poll中

**Comment by xuqi27837288** [comment]
当前内核版本退回至6.1.32版本，镜像安装正常
