### ISSUE TITLE
[archlinux]切换模式以后，桌面图标重叠

### ISSUE THREAD

**Issue by kirigayakazushin** [linuxdeepin/developer-center#67]
![20160311002807](https://cloud.githubusercontent.com/assets/12298476/13676311/40710c94-e720-11e5-96c4-a6613c1c1084.png)
在论坛看到有人发帖说这个问题了，我就试了一下，结果hhhh。

**Comment by zhuzilinuser** [comment]
不过我这个是切换以后当时没有出现，重启以后才有。

**Comment by fasheng** [comment]
切换的是Dock模式，@hualet 这个是已知问题吗？

**Comment by hualet** [comment]
不是已知问题

**Comment by zhuzilinuser** [comment]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=37954  我是看的这个帖子，然后自己试了一下【顺便提一下，4.4内核用wacom，就立马内核崩溃，，查到了好多人都有这个情况，但是没找到解决办法，我用4.3内核，插上数位板，才能显示鼠标图片，否则看不到鼠标图片【哭

**Comment by Iceyer** [comment]
已经基本定位到原因了，修复中。如果影响使用的话建议在**桌面右键-->排序-->名称**即可。

**Comment by manateelazycat** [comment]
This bug has fixed by iceyer.
