### ISSUE TITLE
Cannot open applictions from system tray by clicking left mouse button

### ISSUE THREAD

**Issue by tribunal2000** [linuxdeepin/developer-center#670]
## Describe the bug

System tray works incorrectly

## To Reproduce

1. Start session with telegram and steam in autostart
2. Their icons are in system tray
3. Try to open them by clicking left mouse button
4. No reaction

## Expected behavior

Applications are opened by clicking left mouse button

### Distro & Version

15.8

**Comment by listenerri** [comment]
This is a known bug, but there is no solution yet. I will continue to track this issue.

**Comment by tribunal2000** [comment]
@listenerri It can be hard to find a solution, cause sometimes clicking works. But more often doesn't

**Comment by listenerri** [comment]
@hualet 
找到原因如下:
在存在 SNI 托盘协议的情况下, 一些应用程序如: `telegram` 或者 `steam` , 它们的托盘图标是通过 `libappindicator` 这个库提供的, 但是这个库并没有提供 SNI 协议的标准接口, 跟这个 Issue 相关的就是 `Activate` 接口, 这是一个已经存在一段时间了的问题, 目前依然没有标准的解决方案.

我尝试了以下两个补丁但没有什么作用:
- https://github.com/archlinuxcn/repo/commit/3732d9e891beed9369141b70c2304a76a45ae0a3
- https://github.com/yuyichao/arch-pkg/blob/facba16172ef6caa7fddd1babb21a9d2d5137f32/pkg/all/libappindicator/activate.patch

还有另外一个方案, 但也没有作用:
- https://github.com/kitsunyan/appindicator-collection

目前可选的解决方案是:
- 当左键点击时显示右键菜单
- 禁用 SNI 协议

**Comment by listenerri** [comment]
Force libappindicator to use xembed protocol:

https://cr.deepin.io/c/Patch/+/40828

**Comment by deepinzhangshuang** [comment]
已经更新到ppa/dde-panda

**Comment by liuwen123** [comment]
+1
