### ISSUE TITLE
【deepin_V23_beta3】【一般】【立即】【 预发布测试】【DDE】微信启动后未跟随系统进行比例缩放

### ISSUE THREAD

**Issue by kobe337** [linuxdeepin/developer-center#6714]
### SUMMARY | 问题概要

PMS关联链接：https://pms.uniontech.com/bug-view-237741.html
微信启动后未跟随系统进行比例缩放

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
安装镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20231229/deepin-23-beige-beta3-amd64-20231229-153318.iso
```

### PRE-REQUIREMENT | 预置条件

应用商店中下载应用微信

### STEPS TO REPRODUCE | 复现步骤

1.双击打开应用，观察应用界面显示

### OBSERVED RESULT | 观察到的结果

微信启动后未跟随系统进行比例缩放
![image](https://github.com/linuxdeepin/developer-center/assets/17869922/b73cd6d7-e52e-4582-a34d-f0f186697484)

### EXPECTED RESULT | 期望的结果

微信界面大小展示正常

### ADDITIONAL INFORMATION | 额外补充

目前wine应用存在这个问题

**Comment by babyfengfjx** [comment]
@ComixHe  请帮忙优化~

**Comment by ComixHe** [comment]
1.1.6集成已修复，可以验证一下 @kobe337

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240112/deepin-23-beige-beta3-amd64-20240112-130549.iso 
内核：Linux deepin0112-PC 6.1.32-amd64-desktop-hwe #23.01.00.20 SMP PREEMPT_DYNAMIC Thu Jan 11 18:45:10 CST 2024 x86_64 GNU/Linux
组件版本：dde-application-manager：1.1.7

【结论】：
beta3集成镜像0112测试通过，暂无严重问题及影响
