### ISSUE TITLE
Samsung galaxy S9+ can't be seen by deepin file manage using a normal way

### ISSUE THREAD

**Issue by tribunal2000** [linuxdeepin/developer-center#672]
## Describe the bug

Samsung galaxy S9+ can't be seen by deepin file manage using a normal way

1. Attach Samsung galaxy S9+ to PC (using file transfer protocol)
2. Open deepin file manager
3. Try to open folder of android device
4. See nothing (empty folder)

## Expected behavior

Android device folder must be opened as it should.

## Screenshots

![default](https://user-images.githubusercontent.com/5699209/48659397-63175180-ea61-11e8-9984-9fe6a778d0fd.png)

1) deepin file manager opened from menu
2) deepin file manager opened using "devices" icon from system tray

### Distro & Version

15.8

### Related package version

deepin file manager 4.7.1.1

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/dde-file-manager/issues/4 not sure if related.

**Comment by tribunal2000** [comment]
Looks like another bug (or a way to fix previous)
As you can see, file manager opened from menu (or from dock) can't work correctly
But if you open it using device icon from tray is opened.

![default](https://user-images.githubusercontent.com/5699209/48659731-b2ac4c00-ea66-11e8-9d14-0be0a2c235c4.png)

**Comment by SiamSami** [comment]
#758
https://github.com/linuxdeepin/dde-file-manager/commit/ef95c920cc7b83f35cf7fddb5a1d51a204a465a4

**Comment by SiamSami** [comment]
This has been fixed https://github.com/linuxdeepin/dde-file-manager/commit/ef95c920cc7b83f35cf7fddb5a1d51a204a465a4.
Please close it. @tribunal2000

**Comment by SiamSami** [comment]
#758

**Comment by SiamSami** [comment]
#758
