### ISSUE TITLE
不能正确显示nvme ssd容量（archlinux dde15.8）

### ISSUE THREAD

**Issue by xiaoc-arch** [linuxdeepin/developer-center#673]

**Comment by BLumia** [comment]
贴一下 `dtkcore` 版本，是否使用了全盘加密，`lsblk -Jlpb -oNAME,KNAME,PKNAME,SIZE` 的输出，以及其它你认为可能相关的信息？

**Comment by xiaoc-arch** [comment]
![_deepin-terminal_20181119180915](https://user-images.githubusercontent.com/44838410/48700281-a0790c00-ec26-11e8-90e4-093155402576.png)
![_ _20181119181148](https://user-images.githubusercontent.com/44838410/48700297-ab33a100-ec26-11e8-8cfc-7ff86df2e2e0.png)
![_deepin-terminal_20181119181327](https://user-images.githubusercontent.com/44838410/48700384-d74f2200-ec26-11e8-88c3-d0612cdfa0bf.png
xiaomi pro (i5 8250u mx150)

**Comment by xiaoc-arch** [comment]
![deepinscreenshot_20181119181608](https://user-images.githubusercontent.com/44838410/48700557-3876f580-ec27-11e8-837f-3d2add35d5a7.png)

**Comment by jouyouyun** [comment]
@electricface 使用 lsblk 来获取 total size 吧, 不再使用 udisks2 了.

代码参考: https://gist.github.com/jouyouyun/b1d40d6b327be1282d8104ce2ae2f9f9

**Comment by zccrs** [comment]
@xiaoc-arch 文件管理器“计算机”的右键菜单打开属性对话框，看一下那里显示的大小对不对

**Comment by zccrs** [comment]
@xiaoc-arch 或者执行一下 /usr/lib/libdtk-2.0.9/DCore/bin/deepin-os-release --all

**Comment by BLumia** [comment]
> 我看你头两天是不是在处理文件管理器的这个问题？

是，如果都使用的是最新版本的话现在控制中心和文管读的都是 dtkcore 的信息拿的容量。

从贴上来的截图看 `lsblk -Jlpb -oNAME,KNAME,PKNAME,SIZE` 拿到的数据也是没问题的，所以还是得确定一下问题在哪。

请贴一下 `deepin-control-center` 的版本，顺带检查一下在文件管理器（ `deepin-file-manager` ）的“系统盘”项目上右键点属性所看到的磁盘容量是不是也是错的，或者按 @zccrs 的做法执行 `/path/to/deepin-os-release --all` 贴一下结果，直接贴输出结果就行，不必贴截图。谢啦

**Comment by xiaoc-arch** [comment]
@BLumia 稍等

**Comment by xiaoc-arch** [comment]
@BLumia 更新deepin-control-center 4.7.6.1-1 之后显示正常了，右键计算机属性显示238.5G,但是系统盘右键属性显示“总容量233.2G，可用227G”；
/path/to/deepin-os-release --all结果：（我的libdtk是2.0.6版本？已经pacman -Syu)

**Comment by xiaoc-arch** [comment]
community/dtkcore 1:2.0.9.9-1 [已安装]
![_ _20181120121439](https://user-images.githubusercontent.com/44838410/48751218-141a2800-ecbe-11e8-9cca-56b96ab486c4.png)
@BLumia

**Comment by BLumia** [comment]
> 更新 deepin-control-center 4.7.6.1-1 之后显示正常了

那就没问题了。

> 系统盘右键属性显示 “总容量 233.2G，可用 227G”

系统盘走的是另一套接口，根据你的描述和预期是一样的，不是 bug。

感谢反馈。顺便建议下次反馈的时候还是填提供的 issue 模板比较好，这样的话预先提供一些可能相关的信息（比如这个 issue 肯定和 deepin-control-center 相关，就可以预先提供它的版本号）以便我们定位 bug。
