### ISSUE TITLE
Video stuttering

### ISSUE THREAD

**Issue by gokhanyildirimlar** [linuxdeepin/developer-center#675]
## Describe the bug
Videos stutter while window effects on. Google Chrome, VLC, Deepin Movie, Popcorn-Time, etc don't matter. Videos stutter on all of them. Sometimes visual freezes and sound keeps playing.

## To Reproduce
1. Go to 'Control center'
2. Enable window effets
3. Play video on Youtube by using Google Chrome or play any video, movie on video players.
or: 
1. Open a terminal window
2. Type deepin-wm --replace and press enter key
3. Play video on Youtube by using Google Chrome or play any video, movie on video players.

## Expected behavior
Video or movies being played smoothly, without any stutter or freeze.

### Distro & Version
Linux Deepin 15.7 and 15.8

### Related package version
deepin-wm
Version: 1.9.33-1 on Linux Deepin 15.8
I don't know the version number on Linux Deepin 15.7

Issue can be related to mesa drivers also, I am not sure.

### Additional context
Disabling window effects fix the problem.
Hardware: CPU: Dual Core Intel Core i5-3210M 
                  GPU: Intel Integrated Graphics, no dedicated video card

Similar issue here:
https://github.com/linuxdeepin/developer-center/issues/620

**Comment by sonald** [comment]
if it's possible, could you please install a gnome environment on deepin and see if it has the same problem ?

**Comment by gokhanyildirimlar** [comment]
> if it's possible, could you please install a gnome environment on deepin and see if it has the same problem ?

I am on it but does gdm or lightdm matter?

**Comment by gokhanyildirimlar** [comment]
Okay, I picked lightdm and ruined the system. I can't do anything via recovery or am not able to drop to tty. Reinstalling.

**Comment by gokhanyildirimlar** [comment]
@sonald Installed Gnome with gdm and no issue here. Appstore doesn't lag also.

**Comment by sonald** [comment]
@gokhanyildirimlar that's interesting. the different is tiny since we both use mutter. I need sometime to figure out this.

**Comment by sonald** [comment]
I made a wrong assumption. gnome on deepin use mutter of version 3.28.2 which has builtin cogl and clutter.  deepin-wm use the fork of mutter 3.20. the chances are this is a rendering problem of cogl.

**Comment by gokhanyildirimlar** [comment]
Today, I have checked if deepin-mutter package installed and I realized that I wasn't installed. I installed it with apt install command but this didn't solve my problem. I am writing to let you guys know that deepin-mutter wasn't installed on my system. @sonald

**Comment by gokhanyildirimlar** [comment]
Youtube videos got much better with the latest update(15.8+2). It freezes when I make video fullscreen for the first time and continues smoothly after that. But it's still freezing and stuttering a lot on other websites such as Twitch.tv.

**Comment by sonald** [comment]
@gokhanyildirimlar  it's perfectly fine to not install deepin-mutter, since deepin-wm use libdeepin-mutter0g only.

**Comment by gokhanyildirimlar** [comment]
@sonald Did you update Intel Graphics Driver with 15.7 version? 
![deepinscreenshot_desktop_20181203114101](https://user-images.githubusercontent.com/45146702/49362820-e5a24100-f6f0-11e8-9b2e-2df78c7ec8e7.png)

**Comment by alexwender1** [comment]
Thanks @gokhanyildirimlar for redirecting me to the correct location. What information do you need?

**Comment by gokhanyildirimlar** [comment]
@alexwender1 Just share your experiences and hardware info in order to help developers to solve this issue. I also have this problem from the 15.7 time.

**Comment by alexwender1** [comment]
The problems noted are exactly the same as reported here.

I have an Intel i5 4210U with a hybrid GPU: Intel HD Graphics 4400 / AMD Radeon R7 M265.

Since I got to Deepin ... in version 15.4 ... the AMD GPU never worked; and the Graphics Driver Manager does not offer configuration options for either Intel or even AMD.

I always keep the system up to date. And so I have the latest packages installed.

**Comment by sonald** [comment]
@deepinzhangshuang  @hualet  so this is more like a driver issue ?

**Comment by sarojpoudel33** [comment]
Dell Inspiron 15 - 3537 Laptop (4th Gen Intel Core I5 4200U - 4GB - 500GB - 15.6 and 
Graphics Processor | AMD Radeon HD 8670M

**Comment by gokhanyildirimlar** [comment]
Compatibility and acceleration mode solves problem but causes screen tearings. Default driver is cool because no tearing with it but video playback problem. I think this is a driver issue.

**Comment by gokhanyildirimlar** [comment]
@sonald It may not be driver issue only since there is no problem with Gnome for example.

**Comment by wthiagos** [comment]
I'm also having the same problem.

My specs:
- Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
- kingston hyper x blu 8gb 1600mhz ddr3 khx1600c10d3
- HD Seagate Barracuda 1TB ST1000DM003 7200RPM 64MB SATA III
- Deepin 15.8.2

Tried 3 available options in Graphics Driver Manager but none of them resolve that

**Comment by lucasfads** [comment]
Same problem here.
My specs:

- Intel Core i5-7400 @ 3.00GHz
- 8GB Ram DDR4
- GTX 650 Ti
- Deepin 15.8

Tried both the open source driver and the default driver.

**Comment by wthiagos** [comment]
Maybe I've found a solution.
The error was happening when sawing Netflix in Chrome for example, I've installed other distro(Elementary OS 5.0) just to test if the error still happens and still does.
After some research a person said that it's because of hardware acceleration. So I've turn off "Continue running background apps when Google Chrome is closed" and "Use hardware acceleration when available" options.
After that the problem, at least watching something on netflix never happened again.
I didn't have  time to test on Deepin, but maybe this is the solution.

Print of options turned off
![screenshot from 2018-12-12 20-34-26](https://user-images.githubusercontent.com/23440252/49903361-1cddc400-fe4e-11e8-83d6-73dea6571fc3.png)

**Comment by gokhanyildirimlar** [comment]
@wthiagos I am playing Vainglory via Wine and it freezes sometimes also. Additionally, videos freeze on VLC, Deepin-Movie while playing offline. So this is related to deepin-wm I guess. There is no problem with deepin-metacity.

**Comment by alexwender1** [comment]
With Hardware Acceleration disabled in Chrome ... the problem is gone!

**Comment by hualet** [comment]
> With Hardware Acceleration disabled in Chrome ... the problem is gone!

I thought it was affecting both online video playing and offline video playing, am I wrong?

**Comment by gokhanyildirimlar** [comment]
@hualet Online/offline video playback and games are affected. After I switched to acceleration driver, issue in browser happens rarely and moving mouse curser fixes the video.

**Comment by sarojpoudel33** [comment]
@hualet  Video play smoothly when we make **Use Intel acceleration mode.**  but sometime screen blurring or tearing while open application.

**Comment by sarojpoudel33** [comment]
Make in China 2025.

**Comment by alexwender1** [comment]
It would be nice to see Deepin with updated drivers!

I have a hybrid configuration (Intel / AMD), but I have no way to choose the best driver for my Intel On-Board. In the Graphics Manager, in the early versions, there were the swap options... later, this screen only appears (image).

![captura de tela_deepin-graphics-driver-manager_20181214102722](https://user-images.githubusercontent.com/45263160/50003619-6849bc80-ff8b-11e8-9881-8bea5b327a37.png)

**Comment by gokhanyildirimlar** [comment]
This can be a driver related issue but I didn't have any problem when I installed Gnome with gdm. The same drivers but no issue. Also, switching to deepin-metacity solves the issue. So, this is about deepin-wm. 
Additionally, disabling hardware acceleration solves the problem on Google Chrome. So this makes me think that this is a driver issue but I don't know.

Maybe there is something wrong with how deepin-wm handles Intel drivers.

**Comment by sonald** [comment]
@gokhanyildirimlar you are right, deepin-wm derived from an old version of mutter (which is the core of Gnome window manager) and was lack of many new fixes coming to the new version. so this problem probably have been workaround in new mutter and it's not easy to port and heavy test it now.

**Comment by gokhanyildirimlar** [comment]
@sonald Thanks for the information, it's nice to know this. I look forward to getting new version then. :)

**Comment by alexwender1** [comment]
I ran Google Chrome (with active graphics acceleration in settings) directly on the dedicated AMD GPU. I used the default driver offered by Deepin (amdgpu).

I did not detect crashes with amdgpu when I accessed Youtube. Only 1 (one) brief freeze.

**Comment by sarojpoudel33** [comment]
May Future Update Help Us

**Comment by alexwender1** [comment]
Any news? Is the problem being fixed? Complaints in the community still persist.

**Comment by hualet** [comment]
> Any news? Is the problem being fixed? Complaints in the community still persist.

NO, but we decided to drop mutter as our Window Manager base and trying to get KWin to work.
I personally switched to Firefox and didn't have this problem anymore, maybe others that don't rely on Chrome can try this for now?

**Comment by lucasfads** [comment]
I've been using Chrome with hardware acceleration deactivated.
Since I don't use Deepin for playing offline videos, that's been enough.

**Comment by alexwender1** [comment]
> I've been using Chrome with hardware acceleration deactivated.
> Since I don't use Deepin for playing offline videos, that's been enough.

The problem with Google Chrome is contoured... Already with other applications, which require hardware acceleration, suffer from it... like Deepin Movie.

It's alright! Let's keep up with the next system news.

**Comment by alexwender1** [comment]
I believe I have come closer to the solution.

I upgraded Mesa Graphics Library (18.0.4) of Deepin, to the latest version available in Debian Unstable (18.3.3). By tests, I did not see any kind of freezing. It seems Mesa native (of Deepin), has some form of incompatibility.

Others need to replicate this process. To confirm my suspicion.

![captura de tela_deepin-terminal_20190210132221](https://user-images.githubusercontent.com/45263160/52536411-3b264a00-2d41-11e9-97fe-a4e76b78edc3.png)

**Comment by riletan** [comment]
> I believe I have come closer to the solution.
> 
> I upgraded Mesa Graphics Library (18.0.4) of Deepin, to the latest version available in Debian Unstable (18.3.3). By tests, I did not see any kind of freezing. It seems Mesa native (of Deepin), has some form of incompatibility.
> 
> Others need to replicate this process. To confirm my suspicion.
> 
> ![captura de tela_deepin-terminal_20190210132221](https://user-images.githubusercontent.com/45263160/52536411-3b264a00-2d41-11e9-97fe-a4e76b78edc3.png)

I just updated to Mesa 18.3.3 too. the animation is smoother and video freezing is gone!.

**Comment by lucasfads** [comment]
> I believe I have come closer to the solution.
> 
> I upgraded Mesa Graphics Library (18.0.4) of Deepin, to the latest version available in Debian Unstable (18.3.3). By tests, I did not see any kind of freezing. It seems Mesa native (of Deepin), has some form of incompatibility.
> 
> Others need to replicate this process. To confirm my suspicion.
> 
> ![captura de tela_deepin-terminal_20190210132221](https://user-images.githubusercontent.com/45263160/52536411-3b264a00-2d41-11e9-97fe-a4e76b78edc3.png)

Newbie here. How do I do that?

**Comment by gokhanyildirimlar** [comment]
> I believe I have come closer to the solution.
> 
> I upgraded Mesa Graphics Library (18.0.4) of Deepin, to the latest version available in Debian Unstable (18.3.3). By tests, I did not see any kind of freezing. It seems Mesa native (of Deepin), has some form of incompatibility.
> 
> Others need to replicate this process. To confirm my suspicion.
> 
> ![captura de tela_deepin-terminal_20190210132221](https://user-images.githubusercontent.com/45263160/52536411-3b264a00-2d41-11e9-97fe-a4e76b78edc3.png)

It didn't solve the issue for me. I guess, I am gonna have to wait for KWin. 

![deepin ekran goruntusu_20190213160620](https://user-images.githubusercontent.com/45146702/52713877-8a6eb380-2fa9-11e9-9154-a3287cc5564d.png)

**Comment by gokhanyildirimlar** [comment]
> > I believe I have come closer to the solution.
> > I upgraded Mesa Graphics Library (18.0.4) of Deepin, to the latest version available in Debian Unstable (18.3.3). By tests, I did not see any kind of freezing. It seems Mesa native (of Deepin), has some form of incompatibility.
> > Others need to replicate this process. To confirm my suspicion.
> > ![captura de tela_deepin-terminal_20190210132221](https://user-images.githubusercontent.com/45263160/52536411-3b264a00-2d41-11e9-97fe-a4e76b78edc3.png)
> 
> Newbie here. How do I do that?

1. Open a terminal and type `sudo apt edit-sources` 
2. Add "deb http://ftp.tr.debian.org/debian/ unstable main contrib non-free
deb-src http://ftp.tr.debian.org/debian/ unstable main contrib non-free" lines to the bottom without quotes and use CTRL+X to save and quit. 
3. Use `sudo apt update` command.
4. Now, you are ready to update Mesa drivers. Give `sudo apt install libegl-mesa0 libegl1-mesa libgl1-mesa-dri libgl1-mesa-glx libglapi-mesa libgles2-mesa libglx-mesa0 mesa-va-drivers` command and restart the pc after it finishes it's job. 

Note: I am giving you the address of Debian Sid repository for Turkey since I am Turkish. This is your own responsibility and no one else is responsible for your system but you. You may need to reinstall it if you break. Lastly, don't update anything else because their dependencies can cause issues or break the system.

**Comment by caglarturali** [comment]
Official sources for unstable branch as follows:
```
#------------------------------------------------------------------------------#
#                   OFFICIAL DEBIAN REPOS                    
#------------------------------------------------------------------------------#

###### Debian Main Repos
deb http://deb.debian.org/debian/ unstable main contrib non-free
deb-src http://deb.debian.org/debian/ unstable main contrib non-free
```

And for those who are having difficulties with desktop AMD graphics and thinking about upgrading mesa from Debian's unstable branch: don't do that. :disappointed:

**Comment by alexwender1** [comment]
> > > I believe I have come closer to the solution.
> > > I upgraded Mesa Graphics Library (18.0.4) of Deepin, to the latest version available in Debian Unstable (18.3.3). By tests, I did not see any kind of freezing. It seems Mesa native (of Deepin), has some form of incompatibility.
> > > Others need to replicate this process. To confirm my suspicion.
> > > ![captura de tela_deepin-terminal_20190210132221](https://user-images.githubusercontent.com/45263160/52536411-3b264a00-2d41-11e9-97fe-a4e76b78edc3.png)
> > 
> > 
> > Newbie here. How do I do that?
> 
> 1. Open a terminal and type `sudo apt edit-sources`
> 2. Add "deb http://ftp.tr.debian.org/debian/ unstable main contrib non-free
>    deb-src http://ftp.tr.debian.org/debian/ unstable main contrib non-free" lines to the bottom without quotes and use CTRL+X to save and quit.
> 3. Use `sudo apt update` command.
> 4. Now, you are ready to update Mesa drivers. Give `sudo apt install libegl-mesa0 libegl1-mesa libgl1-mesa-dri libgl1-mesa-glx libglapi-mesa libgles2-mesa libglx-mesa0 mesa-va-drivers` command and restart the pc after it finishes it's job.
> 
> Note: I am giving you the address of Debian Sid repository for Turkey since I am Turkish. This is your own responsibility and no one else is responsible for your system but you. You may need to reinstall it if you break. Lastly, don't update anything else because their dependencies can cause issues or break the system.

I found a tutorial for this @lucasfads. My installation command is a bit different from yours @gokhanyildirimlar (despite the same result).

To view the MESA version:
sudo apt install mesa-utils

View the current MESA Driver version:
glxinfo | grep "OpenGL version"

Adding the Debian Stretch Repository:
deb http://deb.debian.org/debian stretch-backports main

Update the Package and Program List
sudo apt update

Install the MESA Driver:
sudo apt install -t stretch-backports libegl1-mesa libegl1-mesa-dev libgl1-mesa-dri libgl1-mesa-glx libglapi-mesa libgles2-mesa libllvm5.0

Check the new version of MESA Driver:
glxinfo | grep "OpenGL version"

The first test I did with the Unstable Debian repository... Now, I have the Stretch repository. The current version of MESA Driver 18.2.8 (and again, no freezing!).

**Comment by gokhanyildirimlar** [comment]
@alexwender1, No luck in my case. I used your method but the issue still exists for some reason. I hope KWin update arrives soon.

**Comment by diegopaiva1** [comment]
> > > > I believe I have come closer to the solution.
> > > > I upgraded Mesa Graphics Library (18.0.4) of Deepin, to the latest version available in Debian Unstable (18.3.3). By tests, I did not see any kind of freezing. It seems Mesa native (of Deepin), has some form of incompatibility.
> > > > Others need to replicate this process. To confirm my suspicion.
> > > > ![captura de tela_deepin-terminal_20190210132221](https://user-images.githubusercontent.com/45263160/52536411-3b264a00-2d41-11e9-97fe-a4e76b78edc3.png)
> > > 
> > > 
> > > Newbie here. How do I do that?
> > 
> > 
> > 
> > 1. Open a terminal and type `sudo apt edit-sources`
> > 2. Add "deb http://ftp.tr.debian.org/debian/ unstable main contrib non-free
> >    deb-src http://ftp.tr.debian.org/debian/ unstable main contrib non-free" lines to the bottom without quotes and use CTRL+X to save and quit.
> > 3. Use `sudo apt update` command.
> > 4. Now, you are ready to update Mesa drivers. Give `sudo apt install libegl-mesa0 libegl1-mesa libgl1-mesa-dri libgl1-mesa-glx libglapi-mesa libgles2-mesa libglx-mesa0 mesa-va-drivers` command and restart the pc after it finishes it's job.
> > 
> > Note: I am giving you the address of Debian Sid repository for Turkey since I am Turkish. This is your own responsibility and no one else is responsible for your system but you. You may need to reinstall it if you break. Lastly, don't update anything else because their dependencies can cause issues or break the system.
> 
> I found a tutorial for this @lucasfads. My installation command is a bit different from yours @gokhanyildirimlar (despite the same result).
> 
> To view the MESA version:
> sudo apt install mesa-utils
> 
> View the current MESA Driver version:
> glxinfo | grep "OpenGL version"
> 
> Adding the Debian Stretch Repository:
> deb http://deb.debian.org/debian stretch-backports main
> 
> Update the Package and Program List
> sudo apt update
> 
> Install the MESA Driver:
> sudo apt install -t stretch-backports libegl1-mesa libegl1-mesa-dev libgl1-mesa-dri libgl1-mesa-glx libglapi-mesa libgles2-mesa libllvm5.0
> 
> Check the new version of MESA Driver:
> glxinfo | grep "OpenGL version"
> 
> The first test I did with the Unstable Debian repository... Now, I have the Stretch repository. The current version of MESA Driver 18.2.8 (and again, no freezing!).

Didn't work for me. Updated MESA Driver to 18.2.8 and some web video applications like Twitch.tv keeps freezing until you hover the cursor on (image only). My current solution for this problem is disabling the window effect, then no problems happens.

**Comment by alexwender1** [comment]
With version 15.9.2 Beta (released this week)... which brings the MESA 18.1.9; I did not have any freezing problem.

**Comment by gokhanyildirimlar** [comment]
@alexwender1 Confirmed. I tried after I saw your comment and nothing freezes anymore. I have a problem with the app store but, I guess, this is normal since Deepin is moving its base.

**Comment by gokhanyildirimlar** [comment]
There is no issue with KWin.

**Comment by hualet** [comment]
Good to hear, but kwin has its own issues, sigh 😣

**Comment by alexwender1** [comment]
For me, the problem has been solved.

I just know that by updating the Driver Table, the problems stopped happening... and version 15.10 brings a newer (older :speak_no_evil:) version.

Even kWin being a novelty; I believe the Mesa Driver was responsible for eliminating the problem.

**Comment by gokhanyildirimlar** [comment]
> Good to hear, but kwin has its own issues, sigh

Yes, Deepin Team will solve them later on. Actually, I haven't encountered any major issue until now, just some bugs here and there that doesn't affect daily life.
