### ISSUE TITLE
Visual glitches with HD5000 series 

### ISSUE THREAD

**Issue by caglarturali** [linuxdeepin/developer-center#676]
## Describe the bug
Fresh installation of 15.8 final release causes visual glitches like in the screenshots below.

## Screenshots
![](https://media.giphy.com/media/2A841jdJC7uLZwdEsZ/giphy.gif)
![](https://i.imgfly.me/6AHo4.png)

The screenshots were taken from two different systems, the first one is using HD5450 and the second one is using HD5670. In both cases, the problem has been solved by upgrading from an older release while holding following mesa-related packages back:

```libegl-mesa0 libegl1-mesa libgbm1 libgl1-mesa-dri libgl1-mesa-glx libglapi-mesa libgles2-mesa libglx-mesa0 libxatracker2 mesa-va-drivers```

## To Reproduce
 There is nothing to do to reproduce the bug, except installing an HD5000 series graphics card.

### Distro & Version
Linux Deepin 15.8

### Related package version
Version 18.2.0-1 of the aforementioned mesa packages is causing the bug, while any older version performs fine.

**Comment by hualet** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/462

**Comment by hualet** [comment]
> [linuxdeepin/internal-discussion#462](https://github.com/linuxdeepin/internal-discussion/issues/462)

that is: we will downgrade the mesa version to the previous version and provide a ppa for those who want to try the latest mesa version.

**Comment by caglarturali** [comment]
> > [linuxdeepin/internal-discussion#462](https://github.com/linuxdeepin/internal-discussion/issues/462)
> 
> that is: we will downgrade mesa to the previous version and provide a ppa for those who want to try the latest mesa version.

That would be a fix, cause it's not practical to start from an older release of Deepin and make our way to the latest release while holding mesa packages.

By the way, even though older mesa packages perform well most of the time, Conky still does not work properly for those of us using older AMD graphics cards. It doesn't work properly with the latest mesa packages either.

**Comment by hualet** [comment]
It should've been fixed, close for now, feel free to open it if it's not.

**Comment by caglarturali** [comment]
Yeah, it's been fixed, no need to keep it open. Thanks. :+1:
