### ISSUE TITLE
【deepin_V23_beta3】【严重】【立即】【预发布测试】【AM】 切换登录进入treeland桌面，未启用fcitx服务

### ISSUE THREAD

**Issue by SuperEffie** [linuxdeepin/developer-center#6765]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
【镜像地址】：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240104/deepin-23-beige-beta3-amd64-20240104-134457.iso 
【版本信息】：treeland:0.1.1
```

### STEPS TO REPRODUCE | 复现步骤

1. 打开控制中心-更新-技术预览，点击勾选“ddm/treeland”
2. 重启后，登录进入treeland桌面
3. 使用快捷键“Ctrl+Alt+t”唤起终端，输入命令`ps aux|grep "fcitx"`，观察是否启用fcitx服务

### OBSERVED RESULT | 观察到的结果

未检查到fcitx相关进程，fcitx服务未被拉起，输入法无法使用
![fcitx](https://github.com/linuxdeepin/developer-center/assets/58986464/008356e2-8755-48f8-a198-49bfc8399862)

### EXPECTED RESULT | 期望的结果

AM需适配treeland模式，登录进入treeland桌面后，能自动拉起fcitx服务

**Comment by babyfengfjx** [comment]
@dengbo11  帮忙分析一下这个问题。

**Comment by dengbo11** [comment]
该问题的原因是进入treeland桌面，AM 服务没有被启动，导致/etc/xdg/autostart目录下的应用没能被启动，fcitx5是由里面的im-launch去启动的，im-launch没有被启动，所以导致fcitx5 没能被正常启动。

**Comment by zorowk** [comment]
https://github.com/linuxdeepin/treeland/commit/6cef512d76298b5ac41a2ae4fbfb5b21b4b08281

**Comment by SuperEffie** [comment]
【镜像地址】：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240117/deepin-23-beige-beta3-amd64-20240117-153516.iso
【版本信息】：treeland：0.2.0 dde-shell：0.0.5
【关联集成】：#6828 、#6800
【验证结论】：验证通过，关闭此issue。
【备注信息】：目前登录进入treeland桌面，dde-application-manager服务已被启用，但输入法需默认启用deepin-im。启用deepin-im的问题以issue:  #7018 进行跟踪。
【截图信息】：
![截图_选择区域_20240122143503](https://github.com/linuxdeepin/developer-center/assets/58986464/17929f19-fa51-4e74-b34e-ca4700cb9dcc)
