### ISSUE TITLE
小米pro （i5 8250u 256nvme ssd mx150版本）F4、F5按钮不能调节屏幕亮度？

### ISSUE THREAD

**Issue by xiaoc-arch** [linuxdeepin/developer-center#677]
## Describe the bug
小米pro （i5 8250u 256nvme ssd mx150版本）笔记本安装archlinux+dde15.8之后，当用xinitrc（startx）启动dde之后，F1～F12全部功能正常；
而当使用lightdm启动dde之后，F1～F12只有F4（降低亮度)、F5（增强亮度）按键无效，其余按键正常；

**Comment by zccrs** [comment]
@electricface @justforlxz @jouyouyun

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
