### ISSUE TITLE
Right Clicking A Text Document In Deepin Editor Causes The Program To Close

### ISSUE THREAD

**Issue by praveenpious** [linuxdeepin/developer-center#678]
I just installed deepin-editor-1.1-1 package available from the Arch repos. I find that right clicking a text document after opening it using the Deepin Editor causes the Editor to close. Due to this bug, I am not able to copy-paste from text documents.

**Comment by praveenpious** [comment]
> Try launch `deepin-editor` from terminal and reproduce the bug you've found, and paste the output from terminal you got?

`[praveen@Archlinux ~]$ deepin-editor
"dtkwidget2" can not find qm files
"deepin-editor" can not find qm files
2018-11-20, 08:57:59.142 [Debug  ] [qsettingbackend.cpp  Dtk::Core::QSettingBackend::QSettingBackend 54] create config "/home/praveen/.config/deepin/deepin-editor/config.conf"
2018-11-20, 08:57:59.182 [Debug  ] [                                                         0] Create blank file:  "/home/praveen/.local/share/deepin/deepin-editor/blank-files/blank_file_2018-11-20_08-57-59-182"
No appenders assotiated with category org.kde.ksyntaxhighlighting
[Error  ] <> Repository got deleted while a highlighter is still active!
Segmentation fault (core dumped)
`

**Comment by BLumia** [comment]
After it crash, try `coredumpctl gdb` and enter `bt` after it loads, paste the stacktrace you got. thx.

**Comment by praveenpious** [comment]
> bt

`[praveen@Archlinux ~]$ coredumpctl gdb
           PID: 1782 (deepin-editor)
           UID: 1000 (praveen)
           GID: 985 (users)
        Signal: 11 (SEGV)
     Timestamp: Tue 2018-11-20 10:12:07 IST (4s ago)
  Command Line: deepin-editor
    Executable: /usr/bin/deepin-editor
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (praveen)
       Boot ID: 8f3d5d28f2784c0bad04ce1de16f84b4
    Machine ID: a82b354ab51c497196acc583c37d9be3
      Hostname: Archlinux
       Storage: /var/lib/systemd/coredump/core.deepin-editor.1000.8f3d5d28f2784c0bad04ce1de16f84b4.1782.1542688927000000.lz4
       Message: Process 1782 (deepin-editor) of user 1000 dumped core.
                
                Stack trace of thread 1782:
                #0  0x00007f2735f414ba _ZN7QWidget12insertActionEP7QActionS1_ (libQt5Widgets.so.5)
                #1  0x00007f273607f4c3 _ZN5QMenu9addActionERK7QString (libQt5Widgets.so.5)
                #2  0x0000562e7c15811c n/a (deepin-editor)
                #3  0x00007f2735f4a658 _ZN7QWidget5eventEP6QEvent (libQt5Widgets.so.5)
                #4  0x00007f2735ff0cef _ZN6QFrame5eventEP6QEvent (libQt5Widgets.so.5)
                #5  0x00007f273559294b _ZN23QCoreApplicationPrivate29sendThroughObjectEventFiltersEP7QObjectP6QEvent (libQt5Core.so.5)
                #6  0x00007f2735f0ae04 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                #7  0x00007f2735f12b90 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                #8  0x00007f273678fb19 _ZN3Dtk6Widget12DApplication6notifyEP7QObjectP6QEvent (libdtkwidget.so.2)
                #9  0x00007f2735592c39 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                #10 0x00007f2735f66194 n/a (libQt5Widgets.so.5)
                #11 0x00007f2735f685d5 n/a (libQt5Widgets.so.5)
                #12 0x00007f2735f0ae14 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                #13 0x00007f2735f126e1 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                #14 0x00007f273678fb19 _ZN3Dtk6Widget12DApplication6notifyEP7QObjectP6QEvent (libdtkwidget.so.2)
                #15 0x00007f2735592c39 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                #16 0x00007f273593b0dc _ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE (libQt5Gui.so.5)
                #17 0x00007f273593d066 _ZN22QGuiApplicationPrivate24processWindowSystemEventEPN29QWindowSystemInterfacePrivate17WindowSystemEventE (libQt5Gui.so.5)
                #18 0x00007f2735916a3c _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Gui.so.5)
                #19 0x00007f272e8c4dad n/a (libQt5XcbQpa.so.5)
                #20 0x00007f27355918cc _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                #21 0x00007f2735599bc6 _ZN16QCoreApplication4execEv (libQt5Core.so.5)
                #22 0x0000562e7c14f2bd main (deepin-editor)
                #23 0x00007f2734e51223 __libc_start_main (libc.so.6)
                #24 0x0000562e7c14f6fe n/a (deepin-editor)
                
                Stack trace of thread 1788:
                #0  0x00007f2734f1dc21 __poll (libc.so.6)
                #1  0x00007f2733e9aee0 n/a (libglib-2.0.so.0)
                #2  0x00007f2733e9afce g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007f27355e5fc9 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                #4  0x00007f27355918cc _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                #5  0x00007f27353daeb9 _ZN7QThread4execEv (libQt5Core.so.5)
                #6  0x00007f27353e4f65 n/a (libQt5Core.so.5)
                #7  0x00007f2733b0ca9d start_thread (libpthread.so.0)
                #8  0x00007f2734f28b23 __clone (libc.so.6)
                
                Stack trace of thread 1783:
                #0  0x00007f2734f1dc21 __poll (libc.so.6)
                #1  0x00007f2733f6b630 n/a (libxcb.so.1)
                #2  0x00007f2733f6d2db xcb_wait_for_event (libxcb.so.1)
                #3  0x00007f272e82ec5a n/a (libQt5XcbQpa.so.5)
                #4  0x00007f27353e4f65 n/a (libQt5Core.so.5)
                #5  0x00007f2733b0ca9d start_thread (libpthread.so.0)
                #6  0x00007f2734f28b23 __clone (libc.so.6)
                
                Stack trace of thread 1784:
                #0  0x00007f2734f1dc21 __poll (libc.so.6)
                #1  0x00007f2733e9aee0 n/a (libglib-2.0.so.0)
                #2  0x00007f2733e9afce g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007f2733e9b022 n/a (libglib-2.0.so.0)
                #4  0x00007f2733e643eb n/a (libglib-2.0.so.0)
                #5  0x00007f2733b0ca9d start_thread (libpthread.so.0)
                #6  0x00007f2734f28b23 __clone (libc.so.6)
                
                Stack trace of thread 1786:
                #0  0x00007f2734f1dc21 __poll (libc.so.6)
                #1  0x00007f2733e9aee0 n/a (libglib-2.0.so.0)
                #2  0x00007f2733e9bf62 g_main_loop_run (libglib-2.0.so.0)
                #3  0x00007f2732fd1c28 n/a (libgio-2.0.so.0)
                #4  0x00007f2733e643eb n/a (libglib-2.0.so.0)
                #5  0x00007f2733b0ca9d start_thread (libpthread.so.0)
                #6  0x00007f2734f28b23 __clone (libc.so.6)
                
                Stack trace of thread 1787:
                #0  0x00007f2734f1dc21 __poll (libc.so.6)
                #1  0x00007f2733e9aee0 n/a (libglib-2.0.so.0)
                #2  0x00007f2733e9afce g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007f27355e5fc9 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                #4  0x00007f27355918cc _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                #5  0x00007f27353daeb9 _ZN7QThread4execEv (libQt5Core.so.5)
                #6  0x00007f2736523ba6 n/a (libQt5DBus.so.5)
                #7  0x00007f27353e4f65 n/a (libQt5Core.so.5)
                #8  0x00007f2733b0ca9d start_thread (libpthread.so.0)
                #9  0x00007f2734f28b23 __clone (libc.so.6)
                
                Stack trace of thread 1785:
                #0  0x00007f2734f1dc21 __poll (libc.so.6)
                #1  0x00007f2733e9aee0 n/a (libglib-2.0.so.0)
                #2  0x00007f2733e9afce g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007f272cbecbde n/a (libdconfsettings.so)
                #4  0x00007f2733e643eb n/a (libglib-2.0.so.0)
                #5  0x00007f2733b0ca9d start_thread (libpthread.so.0)
                #6  0x00007f2734f28b23 __clone (libc.so.6)
                
                Stack trace of thread 1789:
                #0  0x00007f2733b12afc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007f27253971ac n/a (i965_dri.so)
                #2  0x00007f2725396ee8 n/a (i965_dri.so)
                #3  0x00007f2733b0ca9d start_thread (libpthread.so.0)
                #4  0x00007f2734f28b23 __clone (libc.so.6)

GNU gdb (GDB) 8.2
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/deepin-editor...(no debugging symbols found)...done.
[New LWP 1782]
[New LWP 1788]
[New LWP 1783]
[New LWP 1784]
[New LWP 1786]
[New LWP 1787]
[New LWP 1785]
[New LWP 1789]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `deepin-editor'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f2735f414ba in QWidget::insertAction(QAction*, QAction*) () from /usr/lib/libQt5Widgets.so.5
[Current thread is 1 (Thread 0x7f272ecd4b40 (LWP 1782))]
(gdb) bt
#0  0x00007f2735f414ba in QWidget::insertAction(QAction*, QAction*) () at /usr/lib/libQt5Widgets.so.5
#1  0x00007f273607f4c3 in QMenu::addAction(QString const&) () at /usr/lib/libQt5Widgets.so.5
#2  0x0000562e7c15811c in  ()
#3  0x00007f2735f4a658 in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#4  0x00007f2735ff0cef in QFrame::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#5  0x00007f273559294b in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#6  0x00007f2735f0ae04 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#7  0x00007f2735f12b90 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#8  0x00007f273678fb19 in Dtk::Widget::DApplication::notify(QObject*, QEvent*) () at /usr/lib/libdtkwidget.so.2
#9  0x00007f2735592c39 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#10 0x00007f2735f66194 in  () at /usr/lib/libQt5Widgets.so.5
#11 0x00007f2735f685d5 in  () at /usr/lib/libQt5Widgets.so.5
#12 0x00007f2735f0ae14 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#13 0x00007f2735f126e1 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#14 0x00007f273678fb19 in Dtk::Widget::DApplication::notify(QObject*, QEvent*) () at /usr/lib/libdtkwidget.so.2
#15 0x00007f2735592c39 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#16 0x00007f273593b0dc in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/libQt5Gui.so.5
#17 0x00007f273593d066 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
    at /usr/lib/libQt5Gui.so.5
#18 0x00007f2735916a3c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Gui.so.5
#19 0x00007f272e8c4dad in  () at /usr/lib/libQt5XcbQpa.so.5
#20 0x00007f27355918cc in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#21 0x00007f2735599bc6 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#22 0x0000562e7c14f2bd in main ()
(gdb) 
`

**Comment by praveenpious** [comment]
> this has been fixed, please update to the latest version.

Latest version already installed..

[praveen@Archlinux Desktop]$ pacman -Qi deepin-editor
Name            : deepin-editor
Version         : 1.1-1
Description     : Simple editor for Deepin
Architecture    : x86_64
URL             : https://github.com/linuxdeepin/deepin-editor
Licenses        : GPL3
Groups          : deepin-extra
Provides        : None
Depends On      : deepin-qt5integration  dtkwm  syntax-highlighting  kcodecs
                  polkit-qt5
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 1821.00 KiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Sun 14 Oct 2018 05:24:41 PM IST
Install Date    : Mon 19 Nov 2018 08:13:59 PM IST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

**Comment by rekols** [comment]
@felixonmars

**Comment by Phraqzy** [comment]
Can reproduce, right click causes the program to crash with the same error.

**Comment by praveenpious** [comment]
Closing the thread because the issue is not present on a fresh Arch Linux installation with Deepin DE. Keep up the good work guys.
