### ISSUE TITLE
Integrated org.deepin.movie

### ISSUE THREAD

**Issue by kamiyadm** [linuxdeepin/developer-center#6787]
### package information | 软件包信息

org.deepin.movie | 6.0.4.15

### Package repository address | 软件包仓库地址

url: http://10.0.36.228:9001 name: develop-snipe

### changelog | 更新信息

修复影院崩溃问题

### test suggestion | 测试建议

将影院升级至6.0.4.15。

安装linglong-bin，sudo apt install linglong-bin
sudo rm /var/lib/linglong/config.yaml
修改仓库地址，ll-cli repo modify http://10.0.36.228:9001/ --name develop-snipe
更新影院，ll-cli install/update org.deepin.movie
运行影院，测试是否闪退，能否正常播放视频等。

### Sphere of influence | 影响范围
https://github.com/linuxdeepin/developer-center/issues/6788

**Comment by kamiyadm** [comment]
@Zeno-sole

**Comment by babyfengfjx** [comment]
@vivianxf  请优先开展回归验证。

**Comment by vivianxf** [comment]
集成验证通过,请及时合入:

1.使用命令修改仓库成功
2.issue#https://github.com/linuxdeepin/developer-center/issues/6788验证通过
3.org.deepin.movie 安装成功
4.影院应用正常打开,播放是视频

综上所述,本次集成通过~

**Comment by Zeno-sole** [comment]
@kamiyadm  请合入9002仓库
