### ISSUE TITLE
Integrated org.deepin.browser

### ISSUE THREAD

**Issue by kamiyadm** [linuxdeepin/developer-center#6789]
### package information | 软件包信息

org.deepin.browser	6.5.0.5

### Package repository address | 软件包仓库地址

仓库地址：http://10.0.36.228:9001/
更换地址：ll-cli repo modify http://10.0.36.228:9001/ --name develop-snipe

### changelog | 更新信息

安装最新版本linglong-bin，sudo apt install linglong-bin
sudo rm /var/lib/linglong/config.yaml
修改仓库地址，ll-cli repo modify http://10.0.36.228:9001/ --name develop-snipe
安装或更新浏览器，ll-cli install org.deepin.browser
回归以下bug

### test suggestion | 测试建议

https://github.com/linuxdeepin/developer-center/issues/6340

**Comment by kamiyadm** [comment]
@Zeno-sole

**Comment by babyfengfjx** [comment]
@vivianxf  请开展集成验证。

**Comment by vivianxf** [comment]
集成验证通过,请及时合入:

1.使用命令修改仓库成功
2.issue#https://github.com/linuxdeepin/developer-center/issues/6340验证通过
3.org.deepin.browser安装成功
4.浏览器正常打开,正常跳转

综上所述,本次集成通过~

**Comment by Zeno-sole** [comment]
@kamiyadm  合入9002后 改成已集成状态
