### ISSUE TITLE
Global shortcut to open Apps on Dock

### ISSUE THREAD

**Issue by hualet** [linuxdeepin/developer-center#679]
For example, if you have VirtualBox, Chrome, QtCreator, Terminal, VSCode on your Dock, you can press Win+1 to open VirtualBox, Win+2 to open Chrome, Win+3 to open QtCreator etc...

We've discussed that before and decided that we didn't want it, but now I think it's a good time to review this decision :)

**Comment by hualet** [comment]
@TechQuery

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
