### ISSUE TITLE
deepin安装器 deepin-installer 6.0.33

### ISSUE THREAD

**Issue by ArchieMeng** [linuxdeepin/developer-center#6804]
### package information | 软件包信息

deepin-installer 6.0.33

### Package repository address | 软件包仓库地址

安装镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240109/deepin-23-beige-beta3-amd64-20240109-145932.iso

### changelog | 更新信息

- 修复高分屏下图标不清晰的问题
- 优化分区4K对齐，提升硬盘性能

### test suggestion | 测试建议

- 展开高分屏，标准屏下的外观测试
- 对比当前更新前的普通镜像，测试各种安装模式下硬盘性能有无变化
关联issues： https://github.com/linuxdeepin/developer-center/issues/6518  (该bug遗留 ，需更新图标资源)
pms: https://pms.uniontech.com/bug-view-194375.html  https://pms.uniontech.com/task-view-267331.html

### Sphere of influence | 影响范围

- 图标显示
- 硬盘分区

### ADDITIONAL INFORMATION | 额外补充

无

**Comment by babyfengfjx** [comment]
@kobe337  请开展集成验证。

**Comment by kobe337** [comment]
4K未对齐的磁盘：
使用beta3集成测试镜像验证：
![0109wdq](https://github.com/linuxdeepin/developer-center/assets/17869922/2c3dcc5f-e770-4c5a-89d2-963bcb4fe47b)
提测镜像验证：
![Uploading 0109wdq2.png…]()

验证未通过，磁盘4K仍未对齐。

**Comment by Zeno-sole** [comment]
镜像更新： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20240111/deepin-23-beige-beta3-amd64-20240111-133842.iso

**Comment by kobe337** [comment]
验证未通过，请确认修复：
本次验证镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20240111/deepin-23-beige-beta3-amd64-20240111-133842.iso
