### ISSUE TITLE
arch+dde15.8 dde-dock 和控制中心（“所有设置界面”）图标、systemmonitor下面偶尔出现横线？

### ISSUE THREAD

**Issue by xiaoc-arch** [linuxdeepin/developer-center#681]
请将下方的缺陷汇报模板中的文字替换为您实际需要汇报的缺陷所对应的描述文字。

## 缺陷描述
当鼠标移动到dock（高效模式）托盘位置时出现竖直线，以及鼠标移动到控制中心“所有设置”界面的图标上时，还有systemmonitor“内存位置”偶尔出现横线下划线

## 复现步骤

鼠标移动到相应位置时

复现步骤为:

1. 打开 'dock高校模式'
2.鼠标在托盘图标之间滑动
4. 缺陷 '托盘图标之间出现竖直线' 发生

## 期望行为
不要出现竖直线

## 截图
![_20181120214102](https://user-images.githubusercontent.com/44838410/48777385-659dd380-ed0d-11e8-9963-201196f8fda6.png)
![_ _20181120214204](https://user-images.githubusercontent.com/44838410/48777444-89611980-ed0d-11e8-87af-71948713ca48.png)
![_ _20181120215123](https://user-images.githubusercontent.com/44838410/48777824-9b8f8780-ed0e-11e8-9777-4407c9bd6af6.png)

### 发行版以及版本
Archlinux+dde15.8

### 相关的软件包版本
deepin-wm 1.9.33-1
deepin-session-ui
deepin-system-monitor 1.4.7-1
deepin-qt5integration 0.3.6-1
deepin-mutter 3.20.35-1
deepin-dock 4.8.0-1
deepin-control-center 4.7.6.1-1

**Comment by hualet** [comment]
这是因为 Arch 的Qt没有打deepin的高分屏支持的patch吧？ @felixonmars

**Comment by felixonmars** [comment]
是的，这个还是需要 patch 被上游支持才好打……

**Comment by xiaoc-arch** [comment]
那该怎么办？@felixonmars

**Comment by hualet** [comment]
> 那该怎么办？@felixonmars

@felixonmars 当然是推荐你用 deepin 咯 :joy_cat:

**Comment by hualet** [comment]
先关闭了

**Comment by felixonmars** [comment]
@zccrs 這個 patch 被上游接受的可能性存在嗎？

**Comment by xiaoc-arch** [comment]
现在arch的qt已经打了deepin的高分屏patch了吗？

**Comment by felixonmars** [comment]
没有……

**Comment by zccrs** [comment]
没有

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by xiaoc-arch** [comment]
吃瓜靠你们了.....

**Comment by xiaoc-arch** [comment]
一直想学如何从源码打arch的包，有没有合适的教程，archwiki写的太简单了
