### ISSUE TITLE
Dock高效模式托盘中无线网络不显示已经连接的网络（怀疑被置顶的SSID覆盖）

### ISSUE THREAD

**Issue by xiaoc-arch** [linuxdeepin/developer-center#682]
请将下方的缺陷汇报模板中的文字替换为您实际需要汇报的缺陷所对应的描述文字。

## 缺陷描述

Dock高效模式托盘中无线网络不显示已经连接的网络（怀疑被置顶的SSID覆盖）

## 复现步骤

复现步骤为:

1. 打开 'dock高效模式'
2. 点击 '托盘中的wifi'
3. 缺陷 '已经连接的网络被置顶的未连接SSID覆盖' 发生

## 期望行为
将未连接的SSID置于已经连接的网络下行

## 截图
![_ _20181120220426](https://user-images.githubusercontent.com/44838410/48778647-c37fea80-ed10-11e8-80f4-2ef5e1cdb164.png)

图中CCN。。。。是未连接的网络，已经连接的被覆盖

### 发行版以及版本
Arch+dde15.8

### 相关的软件包版本

deepin-dock 4.8.0-1

**Comment by zccrs** [comment]
已经链接的是哪一个？列表中没有吗

**Comment by liuwen123** [comment]
WiFi连接显示不一致
![_ _20181207113729](https://user-images.githubusercontent.com/12492745/49626392-a471a000-fa14-11e8-88da-ad0e7ac12abe.png)
![_ _20181207113740](https://user-images.githubusercontent.com/12492745/49626393-a471a000-fa14-11e8-8da4-ffea11a7ae09.png)

**Comment by CareF** [comment]
遇到相同的问题！反复出现。有时候还会出现显示的SSID是上一次连接的WiFi的情况。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
