### ISSUE TITLE
policykit 123-1 测试

### ISSUE THREAD

**Issue by UTsweetyfish** [linuxdeepin/developer-center#6822]
### package information | 软件包信息

| 包名 | 版本 |
| -- | -- |
| policykit-1 | 123-1 |

https://github.com/deepin-community/policykit-1/pull/4

> [!WARNING]
> 本次更新改动较大，升级后**需重启**

影响范围不明确，可能较大。是否推送 Beta 3 视测试效果。

工作还没全部完成，建议测试提前介入

目前我们还有以下 patch:
- deepin_fix_polkit_language_env.patch 设置 /etc/default/locales
- deepin_006_add_external_auth.patch 新增外部认证
- deepin_007_polkitd_common_with_helper.patch helper-deepin
- deepin_009_polkit_work_in_tty.patch 在 tty 可用
- deepin_015_fix_use_difference_authenticate.patch
- fix-016-remove-dependencies.patch 内嵌 libda header
- deepin_018_fix_pkexec_wrong.patch 可rebase
- deepin_019_fix_change_deepin_auth_interface.patch 适配V23

> [!TIP]
> 如果功能炸掉了，可以降级。
> 降级： apt install libpolkit-agent-1-0/beige polkitd/beige libpolkit-gobject-1-0/beige pkexec/beige policykit-1/beige
> 降级后同样建议重启。

### Package repository address | 软件包仓库地址

```
deb [trusted=yes] https://ci.deepin.com/repo/obs/home:/sweetyfish:/branches:/deepin:/stable:/main/stable/ ./
```

### changelog | 更新信息

- 更新 policykit 至 123
- 完全移除 UOS 开发者模式代码
- 移植 policykit 0.105 版本的 deepin-authenticator 支持

### test suggestion | 测试建议

以下为尽可能列举的可能需要测试的点，但仍可能有遗漏。

- 控制中心 dde-control-center
- 磁盘管理 deepin-diskmanager
- 文管 dde-file-manager
- deepin ID 插件 dcc-deepinid-plugin
- uos-recovery(非预装?)
- 日志收集工具 deepin-log-viewer
- 设备管理器 deepin-devicemanager
- dde-daemon
  - UserAdministration
  - ChangeOwnData
  - EnableAutoLogin
  - DisableAutoLogin
  - EnableNoPasswordLogin
  - DisableNoPasswordLogin
  - SetKeyboardLayout
  - Enroll Fingreprint
  - Prepare grub2 gfxmode deletection
- deepin-pw-check?
- dde-permission-manager?
- dde-dock?
- dde-session?
- 网络
- 修改代理?
- 指纹
- deepin-defender?
- deepin-deb-installer?
- deepinid?
- deepin-boot-maker?
- deepin-system-monitor?
- deepin-editor?
- 文管挂载（udisks2）
- pkexec 命令
- flatpak

同时建议尽可能多的测试使用policykit的认证方式，包括（以下列表为代码中出现的项，可能实际不支持）密码、指纹、人脸、AD、UKEY、FINGERVEIN（指静脉？）、IRIS（虹膜？）

### Sphere of influence | 影响范围

影响所有调用polkit进行认证的行为

### ADDITIONAL INFORMATION | 额外补充

如有系统预装应用受到影响则搁置本次集成

**Comment by UTsweetyfish** [comment]
cc @Zeno-sole

**Comment by babyfengfjx** [comment]
@Zeno-sole  看是否需要补充对应内容。

**Comment by babyfengfjx** [comment]
@kobe337  请介入测试，主要覆盖上文提到的授权认证场景，同时覆盖TTY，SSH方面的授权认证等场景。

**Comment by kobe337** [comment]
已验证root进程对下列包的权限,验证通过：

com.deepin.dde.dock.overlay
com.deepin.dde.dock.overlay1
com.deepin.deepin-devicemanager.checkAuthentication
com.deepin.deepin-feedback-cli
com.deepin.diskmanager
com.deepin.filemanager.daemon.AccessControlManager.Chmod
com.deepin.filemanager.daemon.AccessControlManager.DiskPwd
com.deepin.filemanager.daemon.UserShareManager
com.deepin.filemanager.daemon.VaultManager.Create
com.deepin.filemanager.daemon.VaultManager.Remove
com.deepin.filemanager.vault.VerifyKey.RetrievePassword
com.deepin.pkexec.dde-file-manager
com.deepin.pkexec.deepin-deb-installer-dependsInstall
com.deepin.pkexec.deepin-system-monitor.kill
com.deepin.pkexec.deepin-system-monitor.logout
com.deepin.pkexec.deepin-system-monitor.renice
com.deepin.pkexec.deepin-system-monitor.systemctl
com.deepin.pkexec.logViewerAuth
com.deepin.pkexec.logViewerAuth.exportLogs
com.deepin.pkexec.logViewerAuth.exportLogsSelf
com.deepin.pkexec.logViewerAuth.self
com.deepin.pkexec.logViewerTruncate
com.deepin.pkexec.printer.install
net.reactivated.fprint.device.enroll
net.reactivated.fprint.device.setusername
net.reactivated.fprint.device.verify
org.deepin.dde.accounts.change-own-user-data
org.deepin.dde.accounts.disable-auto-login
org.deepin.dde.accounts.disable-nopass-login
org.deepin.dde.accounts.enable-auto-login
org.deepin.dde.accounts.enable-nopass-login
org.deepin.dde.accounts.set-keyboard-layout
org.deepin.dde.accounts.user-administration
org.deepin.dde.airplane-mode.enable-disable-any
org.deepin.dde.authenticate.face.delete-enrolled-face
org.deepin.dde.authenticate.face.enroll
org.deepin.dde.authenticate.face.rename-enrolled-face
org.deepin.dde.authenticate.fingerprint.delete-enrolled-fingers
org.deepin.dde.authenticate.fingerprint.enroll
org.deepin.dde.authenticate.fingerprint.manage
org.deepin.dde.authenticate.fingerprint.rename-enrolled-finger
org.deepin.dde.authenticate.iris.delete-enrolled-iris
org.deepin.dde.authenticate.iris.enroll
org.deepin.dde.authenticate.iris.rename-enrolled-iris
org.deepin.dde.device.unblock-bluetooth-devices
org.deepin.dde.fprintd.delete-enrolled-fingers
org.deepin.dde.fprintd.enroll
org.deepin.dde.fprintd.manager
org.deepin.dde.fprintd.rename-enrolled-finger
org.deepin.dde.grub2
org.deepin.dde.grub2.prepare-gfxmode-detect
org.deepin.dde.locale-helper.manage-locale
org.deepin.dde.passwdconf.modify-config
org.deepin.dde.permission.modify-app-permissions
org.dpkg.pkexec.update-alternatives
org.freedesktop.DisplayManager.AccountsService.ModifyAny
org.freedesktop.DisplayManager.AccountsService.ModifyOwn
org.freedesktop.DisplayManager.AccountsService.ReadAny
org.freedesktop.ModemManager1.Contacts
org.freedesktop.ModemManager1.Control
org.freedesktop.ModemManager1.Device.Control
org.freedesktop.ModemManager1.Firmware
org.freedesktop.ModemManager1.Location
org.freedesktop.ModemManager1.Messaging
org.freedesktop.ModemManager1.Time
org.freedesktop.ModemManager1.USSD
org.freedesktop.ModemManager1.Voice
org.freedesktop.NetworkManager.checkpoint-rollback
org.freedesktop.NetworkManager.enable-disable-connectivity-check
org.freedesktop.NetworkManager.enable-disable-network
org.freedesktop.NetworkManager.enable-disable-statistics
org.freedesktop.NetworkManager.enable-disable-wifi
org.freedesktop.NetworkManager.enable-disable-wimax
org.freedesktop.NetworkManager.enable-disable-wwan
org.freedesktop.NetworkManager.network-control
org.freedesktop.NetworkManager.reload
org.freedesktop.NetworkManager.settings.modify.global-dns
org.freedesktop.NetworkManager.settings.modify.hostname
org.freedesktop.NetworkManager.settings.modify.own
org.freedesktop.NetworkManager.settings.modify.system
org.freedesktop.NetworkManager.sleep-wake
org.freedesktop.NetworkManager.wifi.scan
org.freedesktop.NetworkManager.wifi.share.open
org.freedesktop.NetworkManager.wifi.share.protected
org.freedesktop.accounts.change-own-password
org.freedesktop.accounts.change-own-user-data
org.freedesktop.accounts.set-login-option
org.freedesktop.accounts.user-administration
org.freedesktop.hostname1.get-description
org.freedesktop.hostname1.get-hardware-serial
org.freedesktop.hostname1.get-product-uuid
org.freedesktop.hostname1.set-hostname
org.freedesktop.hostname1.set-machine-info
org.freedesktop.hostname1.set-static-hostname
org.freedesktop.locale1.set-keyboard
org.freedesktop.locale1.set-locale
org.freedesktop.login1.attach-device
org.freedesktop.login1.chvt
org.freedesktop.login1.flush-devices
org.freedesktop.login1.halt
org.freedesktop.login1.halt-ignore-inhibit
org.freedesktop.login1.halt-multiple-sessions
org.freedesktop.login1.hibernate
org.freedesktop.login1.hibernate-ignore-inhibit
org.freedesktop.login1.hibernate-multiple-sessions
org.freedesktop.login1.inhibit-block-idle
org.freedesktop.login1.inhibit-block-shutdown
org.freedesktop.login1.inhibit-block-sleep
org.freedesktop.login1.inhibit-delay-shutdown
org.freedesktop.login1.inhibit-delay-sleep
org.freedesktop.login1.inhibit-handle-hibernate-key
org.freedesktop.login1.inhibit-handle-lid-switch
org.freedesktop.login1.inhibit-handle-power-key
org.freedesktop.login1.inhibit-handle-reboot-key
org.freedesktop.login1.inhibit-handle-suspend-key
org.freedesktop.login1.lock-sessions
org.freedesktop.login1.manage
org.freedesktop.login1.power-off
org.freedesktop.login1.power-off-ignore-inhibit
org.freedesktop.login1.power-off-multiple-sessions
org.freedesktop.login1.reboot
org.freedesktop.login1.reboot-ignore-inhibit
org.freedesktop.login1.reboot-multiple-sessions
org.freedesktop.login1.set-reboot-parameter
org.freedesktop.login1.set-reboot-to-boot-loader-entry
org.freedesktop.login1.set-reboot-to-boot-loader-menu
org.freedesktop.login1.set-reboot-to-firmware-setup
org.freedesktop.login1.set-self-linger
org.freedesktop.login1.set-user-linger
org.freedesktop.login1.set-wall-message
org.freedesktop.login1.suspend
org.freedesktop.login1.suspend-ignore-inhibit
org.freedesktop.login1.suspend-multiple-sessions
org.freedesktop.network1.forcerenew
org.freedesktop.network1.reconfigure
org.freedesktop.network1.reload
org.freedesktop.network1.renew
org.freedesktop.network1.revert-dns
org.freedesktop.network1.revert-ntp
org.freedesktop.network1.set-default-route
org.freedesktop.network1.set-dns-over-tls
org.freedesktop.network1.set-dns-servers
org.freedesktop.network1.set-dnssec
org.freedesktop.network1.set-dnssec-negative-trust-anchors
org.freedesktop.network1.set-domains
org.freedesktop.network1.set-llmnr
org.freedesktop.network1.set-mdns
org.freedesktop.network1.set-ntp-servers
org.freedesktop.packagekit.cancel-foreign
org.freedesktop.packagekit.clear-offline-update
org.freedesktop.packagekit.device-rebind
org.freedesktop.packagekit.package-downgrade
org.freedesktop.packagekit.package-eula-accept
org.freedesktop.packagekit.package-install
org.freedesktop.packagekit.package-install-untrusted
org.freedesktop.packagekit.package-reinstall
org.freedesktop.packagekit.package-remove
org.freedesktop.packagekit.repair-system
org.freedesktop.packagekit.system-network-proxy-configure
org.freedesktop.packagekit.system-sources-configure
org.freedesktop.packagekit.system-sources-refresh
org.freedesktop.packagekit.system-trust-signing-key
org.freedesktop.packagekit.system-update
org.freedesktop.packagekit.trigger-offline-update
org.freedesktop.packagekit.trigger-offline-upgrade
org.freedesktop.packagekit.upgrade-system
org.freedesktop.policykit.exec
org.freedesktop.systemd1.bypass-dump-ratelimit
org.freedesktop.systemd1.manage-unit-files
org.freedesktop.systemd1.manage-units
org.freedesktop.systemd1.reload-daemon
org.freedesktop.systemd1.reply-password
org.freedesktop.systemd1.set-environment
org.freedesktop.timedate1.set-local-rtc
org.freedesktop.timedate1.set-ntp
org.freedesktop.timedate1.set-time
org.freedesktop.timedate1.set-timezone
org.freedesktop.timesync1.set-runtime-servers
org.freedesktop.udisks2.ata-check-power
org.freedesktop.udisks2.ata-secure-erase
org.freedesktop.udisks2.ata-smart-enable-disable
org.freedesktop.udisks2.ata-smart-selftest
org.freedesktop.udisks2.ata-smart-simulate
org.freedesktop.udisks2.ata-smart-update
org.freedesktop.udisks2.ata-standby
org.freedesktop.udisks2.ata-standby-other-seat
org.freedesktop.udisks2.ata-standby-system
org.freedesktop.udisks2.cancel-job
org.freedesktop.udisks2.cancel-job-other-user
org.freedesktop.udisks2.eject-media
org.freedesktop.udisks2.eject-media-other-seat
org.freedesktop.udisks2.eject-media-system
org.freedesktop.udisks2.encrypted-change-passphrase
org.freedesktop.udisks2.encrypted-change-passphrase-system
org.freedesktop.udisks2.encrypted-lock-others
org.freedesktop.udisks2.encrypted-unlock
org.freedesktop.udisks2.encrypted-unlock-crypttab
org.freedesktop.udisks2.encrypted-unlock-other-seat
org.freedesktop.udisks2.encrypted-unlock-system
org.freedesktop.udisks2.filesystem-fstab
org.freedesktop.udisks2.filesystem-mount
org.freedesktop.udisks2.filesystem-mount-other-seat
org.freedesktop.udisks2.filesystem-mount-system
org.freedesktop.udisks2.filesystem-take-ownership
org.freedesktop.udisks2.filesystem-unmount-others
org.freedesktop.udisks2.loop-delete-others
org.freedesktop.udisks2.loop-modify-others
org.freedesktop.udisks2.loop-setup
org.freedesktop.udisks2.manage-md-raid
org.freedesktop.udisks2.manage-swapspace
org.freedesktop.udisks2.modify-device
org.freedesktop.udisks2.modify-device-other-seat
org.freedesktop.udisks2.modify-device-system
org.freedesktop.udisks2.modify-drive-settings
org.freedesktop.udisks2.modify-system-configuration
org.freedesktop.udisks2.open-device
org.freedesktop.udisks2.open-device-system
org.freedesktop.udisks2.power-off-drive
org.freedesktop.udisks2.power-off-drive-other-seat
org.freedesktop.udisks2.power-off-drive-system
org.freedesktop.udisks2.read-system-configuration-secrets
org.freedesktop.udisks2.rescan
org.gtk.vfs.file-operations
org.gtk.vfs.file-operations-helper
org.kubuntu.qaptworker3.cancelforeign
org.kubuntu.qaptworker3.commitchanges
org.kubuntu.qaptworker3.updatecache
org.kubuntu.qaptworker3.writefiletodisk

**Comment by kobe337** [comment]
已验证授权场景：
控制中心 dde-control-center
磁盘管理 deepin-diskmanager
文管 dde-file-manager
deepin ID 插件 dcc-deepinid-plugin
uos-recovery(非预装?)
日志收集工具 deepin-log-viewer
设备管理器 deepin-devicemanager
dde-daemon
UserAdministration
ChangeOwnData
EnableAutoLogin
DisableAutoLogin
EnableNoPasswordLogin
DisableNoPasswordLogin

**Comment by kobe337** [comment]
EnableNoPasswordLogin 
DisableNoPasswordLogin 
SetKeyboardLayout 键盘布局类已验证
Enroll Fingreprint 指纹类暂不可用
Prepare grub2 gfxmode deletection 删除grub2启动引导程序中的图形模式的命令，实际使用范围小

**Comment by kobe337** [comment]
beta3集成镜像0117，提测#6954 验证通过，暂无严重问题及影响

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240119/deepin-23-beige-beta3-amd64-20240119-135339.iso 
内核：Linux deepin0112-PC 6.1.32-amd64-desktop-hwe #23.01.00.20 SMP PREEMPT_DYNAMIC Thu Jan 11 18:45:10 CST 2024 x86_64 GNU/Linux

【结论】：
beta3集成镜像0119测试通过，暂无严重问题及影响
