### ISSUE TITLE
Fresh ISO install of Deepin OS hasn't installed deepin recovery mode !!!

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#683]
Hi,

2 days ago i did a fresh ISO install of Deepin 15.8 version ... i noticed i didn't find Deepin recovery entry in grub ... is it intended or a bug that failed to install deepin recovery when a fresh ISO install was performed ... shouldn't it install it by default ?

PS : I have upgraded(15.7-15.8) version of Deepin on another partition and one more cloned to a 3rd partition. ... both these have recovery mode entry in grub fro their respective location. Only the fresh ISO install entry in grub does not have it.

**Comment by hualet** [comment]
It's intended, people don't really need the recovery mode in most cases, so we removed it from pre-installed apps, you still can install it with:

> sudo apt install live-filesystem

BTW, there's a known issue is that recovery mode's not working with full-disk encryption.

**Comment by aiamuzz** [comment]
> It's intended, people don't really need the recovery mode in most cases, so we removed it from pre-installed apps, you still can install it with:

recovery mode is tool and option ... of course it will be used mostly by device administrators and power users ... normal users will not find a use for it ... but he same normal users when they approach a technician to fix issues and problems ... he will certainly be needing it ... 

and not installing it by default is going to make the work of device administers and technicians that much more difficult ... 

say for example ... if a user has booting issues then a recovery will be the first line of approach in the attempts to resolve that problem ... not being pre-installed means closing that door, the first line of approach dead shut ... and moreover remember deepin iso DOES NOT HAVE ... a live mode where the device administrator or repair technician could fall back on !!!

**Deepin Team should reconsider adding back recovery mode as a pre-installed app. That would be the right thing to do.**

**either pre-install deepin-recovery with the OS or enable LIVE mode on the deepin iso !!!**

**Comment by aiamuzz** [comment]
@hualet ... @BLumia ...

Has Deepin-Recovery been withdrawn ?
