### ISSUE TITLE
【deepin_V23_beta3】【严重】【立即】【集成测试】【窗口管理器】【treeland】设置壁纸窗口中，点击Add Wallpaper按钮无响应

### ISSUE THREAD

**Issue by SuperEffie** [linuxdeepin/developer-center#6835]
### SUMMARY | 问题概要

【关联集成】：#6828 、#6800

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
【镜像地址】：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240109/deepin-23-beige-beta3-amd64-20240109-145932.iso 
【版本信息】：treeland:0.2.0
```

### PRE-REQUIREMENT | 预置条件

添加集成仓库，终端中使用命令sudo apt update && sudo apt install treeland

### STEPS TO REPRODUCE | 复现步骤

1. 使用命令sudo systemctl enable ddm -f，重启后进入treeland登录界面
2. 登录treeland桌面后，Ctrl+Alt+t唤起终端，输入命令/usr/libexec/treeland-wallpaper，唤起壁纸设置窗口
3. 点击窗口中Add Wallpaper按钮，观察是否能唤起文件管理器

### OBSERVED RESULT | 观察到的结果

点击窗口中的Add Wallpaper按钮，无响应

https://github.com/linuxdeepin/developer-center/assets/58986464/621e5320-3a3d-4178-bf2d-d09b8c65a7c2

### EXPECTED RESULT | 期望的结果

点击窗口中的Add Wallpaper按钮能唤起文件管理器

**Comment by babyfengfjx** [comment]
@justforlxz  先安排优化~

**Comment by SuperEffie** [comment]
【镜像地址】：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240117/deepin-23-beige-beta3-amd64-20240117-153516.iso
【关联集成】：issue: https://github.com/linuxdeepin/developer-center/issues/6828
【版本信息】：treeland：0.2.0 dde-shell：0.0.5
【验证结论】：验证已修复，关闭此issue。点击“添加图片”按钮，出现“选择文件”弹框
【录屏信息】：

https://github.com/linuxdeepin/developer-center/assets/58986464/b34162df-f315-4fbe-b845-fd92e5415f77
