### ISSUE TITLE
【deepin_V23_beta3】【严重】【立即】【集成测试】【窗口管理器】【treeland】 设置壁纸窗口中控件缺失

### ISSUE THREAD

**Issue by SuperEffie** [linuxdeepin/developer-center#6837]
### SUMMARY | 问题概要

【关联集成】：#6828 、#6800

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
【镜像地址】：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240109/deepin-23-beige-beta3-amd64-20240109-145932.iso 
【版本信息】：treeland:0.2.0
```

### PRE-REQUIREMENT | 预置条件

添加集成仓库，终端中使用命令sudo apt update && sudo apt install treeland

### STEPS TO REPRODUCE | 复现步骤

1. 使用命令sudo systemctl enable ddm -f，重启后进入treeland登录界面
2. 登录treeland桌面后，Ctrl+Alt+t唤起终端，输入命令/usr/libexec/treeland-wallpaper，唤起壁纸设置窗口
3. 观察壁纸设置窗口中控件是否完整

### OBSERVED RESULT | 观察到的结果

1、标题栏未显示应用图标;关闭、最小化、还原按钮
2、本地壁纸、系统壁纸模块区域显示空白
3、Wallpaper区域中显示空白
![截图_选择区域_20240110142522](https://github.com/linuxdeepin/developer-center/assets/58986464/14fcff08-f7d0-4ec5-8d27-39dd7469c3fe)

### EXPECTED RESULT | 期望的结果

1、标题栏显示应用图标;关闭、最小化、还原按钮
2、显示本地壁纸、系统壁纸模块，且有相应图片显示
3、Wallpaper区域中应显示当前桌面壁纸

**Comment by babyfengfjx** [comment]
@justforlxz  请优先安排处理~

**Comment by SuperEffie** [comment]
【镜像地址】：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240117/deepin-23-beige-beta3-amd64-20240117-153516.iso
【关联集成】：issue: https://github.com/linuxdeepin/developer-center/issues/6828
【版本信息】：treeland：0.2.0 dde-shell：0.0.5
【验证结论】：验证已修复，关闭此issue。点击“添加图片”按钮，出现“选择文件”弹框
【录屏信息】：

https://github.com/linuxdeepin/developer-center/assets/58986464/81448300-a832-4ebd-892a-55d498f25178
