### ISSUE TITLE
Docker not compatible with the apparmor version

### ISSUE THREAD

**Issue by ghost** [linuxdeepin/developer-center#684]
So, when using docker with deepin 15.8, docker cannot bind any ports to the network, or any bridges, it throws an error:

> 2018/11/21 15:34:34 listen tcp :9000: socket: permission denied

For this example, I'll use portainer. I have ran the following command with and without sudo:

    docker run -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer

But I still get the error above. I have followed docker's post installation instructions;

https://docs.docker.com/install/linux/linux-postinstall/

ifconfig:

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/LnkAE.png

**How to temporarily Fix:**

So after doing to digging around, with ```dmesg | tail```

I got an error,

> apparmor="DENIED" operation="create" ....

Which was conflicting with my docker network, so I did the following to fix it:

Temporarily added

```deb http://br.archive.ubuntu.com/ubuntu bionic main```

**to**

```/etc/apt/sources.list```

Then run

    sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 3B4FE6ACC0B21F32 
    sudo apt update 
    sudo apt install apparmor=2.12-4ubuntu5 

Then removed ```deb http://br.archive.ubuntu.com/ubuntu bionic main``` from sources. 

So, can we get an apparmor update for the deepin OS?

**Comment by hualet** [comment]
@felixonmars @snyh

**Comment by snyh** [comment]
Don't simply lock apparmor version at 2.12-4ubuntu5, the problem is just a rule configure.
Debian official disable network accessibility in appamor,  We should inspect the rule diff, and only patch the diff to the upstream version.

**Comment by igormcoelho** [comment]
Related to: https://github.com/docker/for-linux/issues/413

**Comment by dacevedo12** [comment]
still happens on 15.10.1

**Comment by whg517** [comment]
The problem I had when I encountered `socket: permission denied` in Deepin 15.10.1 was that, according to https://github.com/docker/for-linux/issues/413#issuecomment-417995201 I uninstalled `apparmor` , the docker problem was fixed. But then I realized that the tools I installed on snapcraft couldn't connect to the external network. Of course I'm going to use docker mostly, it doesn't matter.

When I upgraded to Deepin 15.10.2, I found that `apparmor` was installed automatically, and my docker container died. I now uninstall `apparmor` again, but the problem is fixed.

But now look, this operation is not a long-term solution, please ask what is a better solution?

**Comment by Tset-Noitamotua** [comment]
AppArmor seems not to be installed or least not active on a fresh install of Deepin (see my [comment here](https://github.com/docker/for-linux/issues/413#issuecomment-521543456))

This isse might be related to installation of snap. Have you installed snap - e.g. `sudo apt intall snapd` before or after installation of Docker?

**Comment by fguisso** [comment]
I'm have the fu@$@#$ some issue, remove apparmor and everything works, and I don't know that is the best option.
@Tset-Noitamotua I'm installed Snapd first, the snaps don't have internet access, then I uninstalled Snapd and install Docker, and vouila, the containers don't have internet access too.

**Comment by Zeno-sole** [comment]
deepin 15已关闭且不在维护中，请使用deepin 20

**Comment by Zeno-sole** [comment]
deepin 15 is closed and is not under maintenance, please use deepin 20
