### ISSUE TITLE
【deepin_V23_beta3】【一般】【立即】【集成测试】【窗口管理器】【treeland】锁屏界面Back To Normal Mode图标异常，且悬浮提示信息未翻译

### ISSUE THREAD

**Issue by SuperEffie** [linuxdeepin/developer-center#6844]
### SUMMARY | 问题概要

【关联集成】：#6828 、#6800

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
【镜像地址】：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240109/deepin-23-beige-beta3-amd64-20240109-145932.iso 
【版本信息】：treeland:0.2.0
```

### PRE-REQUIREMENT | 预置条件

安装以上镜像，选择语言为中文
添加集成仓库，终端中使用命令sudo apt update && sudo apt install treeland

### STEPS TO REPRODUCE | 复现步骤

1. 使用命令sudo systemctl enable ddm -f，重启后进入treeland登录界面
2. 登录treeland桌面后，使用快捷键Super+L进入锁屏界面
3. 鼠标移动悬浮至右下角2上，观察悬浮框中提示信息显示

### OBSERVED RESULT | 观察到的结果

悬浮框中提示信息显示为“Back To Normal Mode”，存在问题：
1. 图标未更改
2. 提示信息未进行翻译
截图如下：
![1](https://github.com/linuxdeepin/developer-center/assets/58986464/d8fbbb8f-0a19-44e2-92db-4b16a0b9e8d9)

### EXPECTED RESULT | 期望的结果

1. 更改为“Back To Normal Mode”按钮图标
2. 提示信息进行翻译为中文

**Comment by babyfengfjx** [comment]
@justforlxz  这个也需要优化一下。

**Comment by SuperEffie** [comment]
【镜像地址】：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240117/deepin-23-beige-beta3-amd64-20240117-153516.iso
【版本信息】：treeland：0.2.0 dde-shell：0.0.5 
【关联集成】：https://github.com/linuxdeepin/developer-center/issues/6828 、https://github.com/linuxdeepin/developer-center/issues/6800
【验证结论】：验证通过，关闭此issue。图标已更改;tooltips已翻译为中文。
【截图信息】：
![截图_选择区域_20240122114329](https://github.com/linuxdeepin/developer-center/assets/58986464/409c2ecf-3c0e-41fb-9577-eed10d6d1e3d)
