### ISSUE TITLE
【deepin_V23_beta3】【一般】【立即】【集成测试】【窗口管理器】【treeland】锁屏界面Back To Normal Mode弹框中显示不完整，且显示为英文

### ISSUE THREAD

**Issue by SuperEffie** [linuxdeepin/developer-center#6846]
### SUMMARY | 问题概要

【关联集成】：#6828 、#6800

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
【镜像地址】：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240109/deepin-23-beige-beta3-amd64-20240109-145932.iso 
【版本信息】：treeland:0.2.0
```

### PRE-REQUIREMENT | 预置条件

安装以上镜像，选择语言为中文
添加集成仓库，终端中使用命令sudo apt update && sudo apt install treeland

### STEPS TO REPRODUCE | 复现步骤

1. 使用命令sudo systemctl enable ddm -f，重启后进入treeland登录界面
2. 登录treeland桌面后，使用快捷键Super+L进入锁屏界面
3. 第一次点击右下角图标2，观察弹框中信息显示

### OBSERVED RESULT | 观察到的结果

1. 提示信息显示不完整，被ok按钮遮挡
2. 窗口中文字显示为英文
![2](https://github.com/linuxdeepin/developer-center/assets/58986464/0a6dceca-7082-4973-9441-b524f7c2b16c)

### EXPECTED RESULT | 期望的结果

1. 提示信息显示完整，不会被按钮遮挡
2. 窗口中文字显示为中文

**Comment by babyfengfjx** [comment]
@justforlxz  可以优化一下。

**Comment by SuperEffie** [comment]
【镜像地址】：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240117/deepin-23-beige-beta3-amd64-20240117-153516.iso
【版本信息】：treeland：0.2.0 dde-shell：0.0.5
【关联集成】：https://github.com/linuxdeepin/developer-center/issues/6828 、https://github.com/linuxdeepin/developer-center/issues/6800
【验证结论】：验证通过，关闭此issue。锁屏界面Back To Normal Mode弹框中显示完整，提示信息已翻译，但确定、取消等按钮未做翻译，发版后取消该弹框，故不作继续优化处理～
【截图信息】：
![截图_选择区域_20240122140213](https://github.com/linuxdeepin/developer-center/assets/58986464/2a84929d-c2f2-440a-8230-ce893258ff45)
