### ISSUE TITLE
deepin-editor Cyrillic encoding problem

### ISSUE THREAD

**Issue by ElectroPositiv** [linuxdeepin/developer-center#685]
There are problems when opening text files in Cyrillic in deepin-editor.

Create a text document in Cyrillic and save it. Then open and see what I mean.

Linux Deepin 15.8
![deepinscreenshot_deepin-editor_20181117143000](https://user-images.githubusercontent.com/11730518/48867236-97369d80-ede6-11e8-8713-373ad67f2bcf.png)

[Тестовый документ.txt](https://github.com/linuxdeepin/developer-center/files/2606854/default.txt)

Corrected. Attached a text file.

**Comment by zccrs** [comment]
Can you upload the text file?

**Comment by ElectroPositiv** [comment]
> Можете ли вы загрузить текстовый файл?

Yes of course.

[Тестовый документ.txt](https://github.com/linuxdeepin/developer-center/files/2606849/default.txt)

**Comment by rekols** [comment]
> > Можете ли вы загрузить текстовый файл?
> 
> Yes of course.
> 
> [Тестовый документ.txt](https://github.com/linuxdeepin/developer-center/files/2606849/default.txt)

thx,I'll fix it.

**Comment by rekols** [comment]
@ElectroPositiv you can try to preview the file by pressing the space in dde-file-manager. is this the same situation?

**Comment by ElectroPositiv** [comment]
> @ElectroPositiv вы можете попробовать просмотреть файл, нажав пробел в dde-file-manager. это та же ситуация?

Yes, everything is the same.
![deepinscreenshot_dde-file-manager_20181122133300](https://user-images.githubusercontent.com/11730518/48897459-35fce180-ee5b-11e8-88ba-992ab03e14e3.png)

**Comment by rekols** [comment]
https://cr.deepin.io/#/c/deepin-editor/+/40071/

**Comment by liuwen123** [comment]
+1

**Comment by ElectroPositiv** [comment]
@rekols Ok, thanks.
