### ISSUE TITLE
[Deepin Integration]~[V23-Beta3] feat: update nvidia-settings to 525.125.06-1 @ deepin-community/nvidia-settings

### ISSUE THREAD

**Issue by UTsweetyfish** [linuxdeepin/developer-center#6851]
### package information | 软件包信息

| 包名 | 版本 |
|--------|--------|
| nvidia-settings | [525.125.06-1](https://github.com/deepin-community/nvidia-settings/pull/1) |

### Package repository address | 软件包仓库地址

V23 Beta 3 仓库

https://ci.deepin.com/repo/deepin/deepin-community/beta3/pool/main/n/nvidia-settings/

### changelog | 更新信息

更新 nvidia-settings 至 525.125.06-1

### test suggestion | 测试建议

#6498

测试 nvidia-settings 功能

**Comment by babyfengfjx** [comment]
@kobe337  请开展回归验证。

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240110/deepin-23-beige-beta3-amd64-20240110-150013.iso
内核：Linux deepin0110-PC 6.6.7-amd64-desktop-hwe #23.01.00.21 SMP PREEMPT_DYNAMIC Thu Dec 14 17:07:54 CST 2023 x86_64 GNU/Linux

【结论】：
beta3集成镜像0110测试通过，暂无严重问题及影响

nvidia-settings是NVIDIA显卡驱动的设置程序，主要用于显示显卡温度与设置显卡工作频率。
![nc](https://github.com/linuxdeepin/developer-center/assets/17869922/ada41c50-439a-4d81-908d-a77a3f20e5fa)
