### ISSUE TITLE
【deepin_V23_beta3】【一般】【立即】【预发布测试】【DDE】【launchpad】按住Shift q不能直接输入搜索

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#6859]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240109/deepin-23-beige-beta3-amd64-20240109-105853.iso
dde-launchpad 0.4.0
```

### PRE-REQUIREMENT | 预置条件

1. 安装镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240109/deepin-23-beige-beta3-amd64-20240109-105853.iso

### STEPS TO REPRODUCE | 复现步骤

1. 打开启动器 - 按住 Shift q输入搜索

### OBSERVED RESULT | 观察到的结果

1. 不能输入大写的 Q
![999](https://github.com/linuxdeepin/developer-center/assets/96416089/9b5b0d77-b988-4ae7-93bb-9ef2b2d98f5b)

### EXPECTED RESULT | 期望的结果

1. 可以输入大写的 Q

### ADDITIONAL INFORMATION | 额外补充

对比 20.9和 V23的老 dde-launcher可以按住  Shift q输入搜索大写的 Q

**Comment by babyfengfjx** [comment]
@BLumia  这个问题可以后面再做修复。

**Comment by BLumia** [comment]
commitmsg关联错issue了，在此备注：

https://github.com/linuxdeepin/dde-launchpad/commit/69eac344c0cd0d539d8b681cefa593748e6df14c 解决了此问题。

**Comment by luodeepin** [comment]
验证通过
![6859](https://github.com/linuxdeepin/developer-center/assets/96416089/77ecefbe-14fa-4315-ba80-2145a85310f8)
