### ISSUE TITLE
自定义右键菜单后，桌面右键菜单出现显示错误

### ISSUE THREAD

**Issue by wjkcs** [linuxdeepin/developer-center#686]
## 缺陷描述

自定义特定种类的右键菜单拓展项后，桌面右键菜单出现显示错误

## 复现步骤

复现步骤为:

1. 打开 /home/用户名/.config/deepin/dde-file-manager/menuextensions/menuextensions.json
2. 加入 MenuType为EmptyArea，Icon为Files的自定义右键菜单拓展项，如：
```
  {
        "MenuType": "EmptyArea",
        "Icon": "Files",
        "Text[zh_CN]": "用vscode打开",
        "Text[zh_HK]": "用vscode打开",
        "Text[zh_TW]": "用vscode打开",
        "Exec": "/usr/share/code/code.sh"
    }
```
3. 切换到桌面，点击右键
4. 右键菜单中的“自动排列”选项位置显示不正常

## 期望行为

桌面右键菜单中的“自动排列”选项位置不受自定义右键菜单拓展项影响

## 截图
![image](https://user-images.githubusercontent.com/26520783/48884362-27182e00-ee5f-11e8-995a-dd61a7aacc07.png)

### 发行版以及版本

Linux Deepin 15.8

### 相关的软件包版本

dde-file-manager 4.7.1.1

**Comment by BLumia** [comment]
等忙完手头的我看下。

顺便，在文管 1.8 以上的版本后支持了 Args 参数，所以可以仿造 https://github.com/linuxdeepin/dde-file-manager/issues/21 这个 issue 中的写法而不必准备你自己的 `/usr/share/code/code.sh` 了。

**Comment by BLumia** [comment]
qt5integration 的问题， @justforlxz 。

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/qt5integration/+/40073/

**Comment by liuwen123** [comment]
已修复
