### ISSUE TITLE
Deepin launcher not all in russian

### ISSUE THREAD

**Issue by activatorr** [linuxdeepin/developer-center#687]
## Describe the bug

Deepin launcher not all translated on russian language

## To Reproduce

1. Go to settings -> keyboard and language -> system language -> "русский"
2. Click deepin launcher -> "Все категории" -> and you see all in English categories
## Expected behavior

That is on Russian.

## Screenshots

https://i.postimg.cc/yWqw2340/deepin-launcher.png

## Enviroments:
DDE
### Distro & Version

Linux Deepin 15.8

### Related package version

dde-launcher

### Additional context

translatePath after feedback: "/usr/share/dtkwidget/translations/dtkwidget2_ru"
translatePath after feedback: "/usr/share/dde-launcher/translations/dde-launcher_ru"
2018-11-22, 11:36:08.067 [Debug  ] [dapplication.cpp     Dtk::Widget::DApplicationPrivate::setSingleInstanceByDbus 203] register service failed: QDBusError("", "")

**Comment by hualet** [comment]
Time to merge translations. @justforlxz
