### ISSUE TITLE
127.0.0.1的链接，打开链接，没有响应。

### ISSUE THREAD

**Issue by aohanhongzhi** [linuxdeepin/developer-center#6888]
### SUMMARY | 问题概要

![image](https://github.com/linuxdeepin/developer-center/assets/37319319/d5a71728-789b-4efe-9018-52891d1abdb6)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin 23 beta2
```

### STEPS TO REPRODUCE | 复现步骤

127.0.0.1的地址

### OBSERVED RESULT | 观察到的结果

无法打开浏览器，其他的链接可以正常打开浏览器。

### EXPECTED RESULT | 期望的结果

能打开浏览器

**Comment by BLumia** [comment]
无法复现。麻烦提供具体信息：

1. 什么终端，深度终端吗？具体哪个版本？
2. 设的什么默认浏览器？firefox？预装的浏览器？以及这个浏览器什么版本？
3. 终端里 `xdg-open http://127.0.0.1:2017` 也无法打开浏览器吗？有无相关输出？

**Comment by aohanhongzhi** [comment]
> 无法复现。麻烦提供具体信息：
> 
> 1. 什么终端，深度终端吗？具体哪个版本？
> 2. 设的什么默认浏览器？firefox？预装的浏览器？以及这个浏览器什么版本？
> 3. 终端里 `xdg-open http://127.0.0.1:2017` 也无法打开浏览器吗？有无相关输出？

1. 深度终端，beta系统最新版的终端
2. edge浏览器

具体资料信息和测试软件输出的链接，在下面提供给你。

https://files.cupb.top/api/file/download?fileUuid=feab95997df4e9d74c203803898913ee

**Comment by babyfengfjx** [comment]
@kobe337  可以按照楼上提供的信息，复现后找研发分析。

**Comment by kobe337** [comment]
@ArchieMeng 用户反馈在终端中无法通过链接唤起默认设置的浏览器，麻烦帮忙看下哈，本地可以复现。

**Comment by Decodetalkers** [comment]
我这边firefox 没有问题，我一直使用这个的

**Comment by ArchieMeng** [comment]
@kobe337 
![image](https://github.com/linuxdeepin/developer-center/assets/12139431/f288c3a5-319a-4e22-904c-0ac0ee743ab9)
看看关于的这个链接你点了有反应不？应该是同样的调起方式。

**Comment by kobe337** [comment]
@ArchieMeng 主页这个地方点击可以唤起浏览器

**Comment by kobe337** [comment]
#7083提测验证通过

**Comment by kobe337** [comment]
@aohanhongzhi 问题已经修复了哈，请在后续终端6.0.10上进行重试哈

**Comment by aohanhongzhi** [comment]
> @aohanhongzhi 问题已经修复了哈，请在后续终端6.0.10上进行重试哈

牛！反应迅速。
