### ISSUE TITLE
文件夹菜单栏拖动卡顿

### ISSUE THREAD

**Issue by aohanhongzhi** [linuxdeepin/developer-center#6889]
### SUMMARY | 问题概要

https://bbs.deepin.org/zh/post/267145
![image](https://github.com/linuxdeepin/developer-center/assets/37319319/eca2f246-12e8-4d96-a6c9-4dc66b1a0ded)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin v23 beta2
```

### STEPS TO REPRODUCE | 复现步骤

1. 打开文件夹，拖动右侧菜单

### OBSERVED RESULT | 观察到的结果

卡顿非常严重

### EXPECTED RESULT | 期望的结果

流畅运行

**Comment by babyfengfjx** [comment]
@xuqi27837288  请尝试在最新版本复现。

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240111
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.7-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
