### ISSUE TITLE
Calculator not showing all characters

### ISSUE THREAD

**Issue by dusatvoj** [linuxdeepin/developer-center#689]
## Describe the bug
Deepin calculator not showing '+', '-' and '='

## Screenshots

![image](https://user-images.githubusercontent.com/11560794/48947924-1b963700-ef33-11e8-9009-405ca314f1eb.png)

Newest update of arch linux 4.19.2-arch1-1-ARCH
deepin-calculator 1.0.10-1

**Comment by hualet** [comment]
what font are you using?

**Comment by dusatvoj** [comment]
@hualet I'm sorry but where can I find that?

**Comment by hualet** [comment]
> @hualet I'm sorry but where can I find that?

Oh, sorry. you can run `fc-match` in the terminal and see the result.

**Comment by dusatvoj** [comment]
NimbusSans-Regular.otf: "Nimbus Sans" "Regular"

**Comment by rekols** [comment]
hello, can you try switching to another font to see that it is correct?  @dusatvoj

**Comment by dusatvoj** [comment]
It's still broken :/
![image](https://user-images.githubusercontent.com/11560794/49145207-9084ba80-f2ff-11e8-8b60-da358874f66b.png)

**Comment by rekols** [comment]
paste " －  ＋" there characters in deepin-editor ?

**Comment by dusatvoj** [comment]
Oh, that's the point.
![image](https://user-images.githubusercontent.com/11560794/49147809-f5431380-f305-11e8-8ba4-51a7b513fb07.png)
What's wrong?

**Comment by hualet** [comment]
@dusatvoj  use noto

**Comment by antechdesigns** [comment]
@hualet @felixonmars  did this ever get looked at? Its still the same when using noto or any other font on archdeepin.

deepin-calculator 1.0.1

![DeepinScreenshot_deepin-calculator_20190317123639](https://user-images.githubusercontent.com/29888048/54490837-60aef200-48b1-11e9-9684-0d3c0fcc86e0.png)

**Comment by hualet** [comment]
> @hualet @felixonmars did this ever get looked at? Its still the same when using noto or any other font on archdeepin.
> 
> deepin-calculator 1.0.1
> 
> ![DeepinScreenshot_deepin-calculator_20190317123639](https://user-images.githubusercontent.com/29888048/54490837-60aef200-48b1-11e9-9684-0d3c0fcc86e0.png)

Sorry, I'll try it on my newly installed Arch-DDE and see what happens tomorrow.

**Comment by dusatvoj** [comment]
@hualet I think it's system wiide error, beacuse I can't see these characters even in browser 
![image](https://user-images.githubusercontent.com/11560794/54493225-a679b380-48cd-11e9-9a56-f9cc3be60a18.png)
I tried several fonts, but same issue.

**Comment by antechdesigns** [comment]
According to @keybreak its fine in Manjaro
@hualet Can you post your pkglist of what you install when doing a clean arch install, could just be me.
Thanks ;)

**Comment by hualet** [comment]
Having no problem on my Arch-DDE.

Here's my package list: 
[packages.txt](https://github.com/linuxdeepin/developer-center/files/2976447/packages.txt)

**Comment by antechdesigns** [comment]
@hualet Thanks

Well it turns out I needed the 

`noto-fonts-cjk` 

However its 308MB!! Really?? 
Surely something needs fixing here? Is there a better way?

Also if this pkg is needed, should it not be pulled in with the deepin pkg??

@felixonmars

**Comment by keybreak** [comment]
@hualet 
I have 2 hypotheses here:
1. There's no **NotoMono-Regular.ttf** inside **noto** folder at least on ant's Arch Deepin, and maybe some of those symbols are used with monospace font.
2. You probably don't see this, because + / - characters was hardcoded with some variant of chinese encoding, therefore you see it, but any other variant of UTF-8 or some other encodings based on non-chinese system language don't actually show them correctly

**Comment by hualet** [comment]
Hmmm...seems that we can't use those mathematic signs since they may not be included in the fonts. We can use images @BLumia @shule1987

**Comment by keybreak** [comment]
@hualet 
Well, probably also not the best option, it's hard to use images everywhere....

Maybe better option would be to install **NotoMono-Regular.ttf** by default with deepin dde, and then froce any program to just fallback to this font, unless character is present in currently selected?

It seems to be a very effective fix, for Manjaro Deepin it works :)

**Comment by antechdesigns** [comment]
@hualet @felixonmars 

Any decision on this yet? 
I want to create a new archdeepin.ISO (April) without having to add 300mb unnecessarily to the ISO

Thanks

**Comment by hualet** [comment]
> @hualet
> Well, probably also not the best option, it's hard to use images everywhere....
> 
> Maybe better option would be to install **NotoMono-Regular.ttf** by default with deepin dde, and then froce any program to just fallback to this font, unless character is present in currently selected?
> 
> It seems to be a very effective fix, for Manjaro Deepin it works :)

I just don't want a simple calculator App replies on a specific font.

@antechdesigns I'll do it next week.

**Comment by keybreak** [comment]
@hualet 
Reasonable :smiley_cat: 

But anyway, it's reported that unless **noto-fonts-cjk** is present, even in Firefox you can't see chinese / japanese / korean language...
So it's a universal problem :)

**Comment by antechdesigns** [comment]
> @hualet
> Reasonable smiley_cat
> 
> But anyway, it's reported that unless **noto-fonts-cjk** is present, even in Firefox you can't see chinese / japanese / korean language...
> So it's a universal problem :)

I can confirm this (archdeepin)

**Comment by antechdesigns** [comment]
note to self: 

Installing `ttf-hannom` 22MBs fixes web browser not showing Chinese fonts, this is a better alternative than installing 300MB `noto-fonts-cjk` at least on arch, may work for Manjaro and other Arch OSes

**Comment by darthcabs** [comment]
> note to self:
> 
> Installing `ttf-hannom` 22MBs fixes web browser not showing Chinese fonts, this is a better alternative than installing 300MB `noto-fonts-cjk` at least on arch, may work for Manjaro and other Arch OSes
> 
> @felixonmars @oberon-manjaro

This kind of fixed for me in Manjaro (+ and - signs are huge compared to the numbers), but I was under the impression by reading this issue that deepin-calculator had been fixed in version 5.0.1 not to rely on the system's font to display those symbols, and since I'm using deepin-calculator 5.0.1-1, I shouldn't be having these problems anymore, no?
