### ISSUE TITLE
[archlinux]在无弹出的情况下拔出usb设备，dock继续保持图标

### ISSUE THREAD

**Issue by zhuzilinuser** [linuxdeepin/developer-center#69]
![20160318121603](https://cloud.githubusercontent.com/assets/12298476/13868407/5a069310-ec96-11e5-9d9e-46008e6a68f8.png)
我的手机是米3，插上以后有个分区里面是安装小米手机助手的，然后会自己弹出来挂载，移除手机以后，dock还是有挂载的图标。而且挂载其他分区以后，显示内容不会更新。

**Comment by jouyouyun** [comment]
@fasheng  gccgo 的问题？收不到信号？

**Comment by fasheng** [comment]
重新编译了下发现确实和gccgo有关, @jouyouyun DiskMount模块是监听udisks
的DBus接口吧, 那这种Bug影响范围就比较大了

类似的问题
https://github.com/linuxdeepin/developer-center/issues/51

**Comment by jouyouyun** [comment]
DiskMount 是通过 glib.VolumeMonitor 或获取磁盘改变的

**Comment by fasheng** [comment]
Solved now.
