### ISSUE TITLE
[Arch Linux] Unable to change desktop environment

### ISSUE THREAD

**Issue by tbhaxor** [linuxdeepin/developer-center#690]
## Describe the bug

*A clear and concise description of what the bug is.*
I am using DDE in arch linux and also KDE Plasma. While logging in when ever i try to change my desktop environment it loop backs to greeter session.

## To Reproduce

*We can fix a bug faster if we can reproduce the bug, so provide steps to reproduce the bug is very helpful for us.*

1. Install lightdm, KDE Plasma and Deepin Desktop Environment
2. Change Desktop Environment to Plasma and Login
3. You will get loop back to greeter session

## Expected behavior

*A clear and concise description of what you expected to happen.*

## Screenshots

*If applicable, add screenshots to help explain your problem.*

### Distro & Version

Linux h3ll 4.19.2-arch1-1-ARCH #1 SMP PREEMPT Tue Nov 13 21:16:19 UTC 2018 x86_64 GNU/Linux

### Related package version

Deepin Desktop Enviroment - Greeter

*If you are not sure about which package went wrong, you can provide a list of package and it's version which you thinks is probably related with your issue*

### Additional context

*Add any other context about the problem here. It will be very helpful for us to isolate the problem. We will ask for more details when needed so feel free to remove this section if you really don't know what to provide.*

**Comment by hualet** [comment]
@felixonmars can you test this one?

**Comment by tbhaxor** [comment]
@hualet what more info may i provide ?

**Comment by hualet** [comment]
@tbhaxor can you try another DE ?

**Comment by tbhaxor** [comment]
> @tbhaxor can you try another DE other than Plasma?

I think i am using lightdm-deepin-greeter instead of lightdm-gtk-greeter.
because when i used gdk this problem was resolved...

maybe its a bug in lightdm-deepin-greeter package :confused:

**Comment by hualet** [comment]
@justforlxz

**Comment by tbhaxor** [comment]
I am closing this issue not because its seems your community members doesnt seem it to be important :disappointed:
