### ISSUE TITLE
更新到15.8.1，dock一直闪烁

### ISSUE THREAD

**Issue by ziqiangxu** [linuxdeepin/developer-center#692]
请将下方的缺陷汇报模板中的文字替换为您实际需要汇报的缺陷所对应的描述文字。

## 缺陷描述

如题

## 截图

*如果适用于你所汇报的缺陷，可以附带截图来帮助描述你所遇到的缺陷（BUG）*

## 复现环境:

*部分缺陷可能需要在特定环境下才能复现，所以请尽可能详细的提供可能导致该缺陷的环境信息*

### 发行版以及版本

[如. Linux Deepin 15.8.1]

### 相关的软件包版本

dde-dock   4.8.0-1 

### 其他内容
![_ _20181124211943](https://user-images.githubusercontent.com/18530271/48968744-d5260280-f02e-11e8-8752-bfcb28b10d6b.gif)
这个是从终端启动dde-dock获得的输出
[dde-dock-normal.txt](https://github.com/linuxdeepin/developer-center/files/2612271/dde-dock-normal.txt)
这个是移除`/usr/lib/dde-dock/plugins/system-tray.so`之后的输出
[dde-dock-system-tray-removed.txt](https://github.com/linuxdeepin/developer-center/files/2612272/dde-dock-system-tray-removed.txt)

**Comment by hualet** [comment]
你这应该是 dde-session-daemon 一直在崩溃吧？ 

终端执行看看有什么输出？
> killall dde-session-daemon;  /usr/lib/deepin-daemon/dde-session-daemon

**Comment by ziqiangxu** [comment]
看了dde-session-daemon的输出
![image](https://user-images.githubusercontent.com/18530271/48995270-1ed33200-f182-11e8-808a-5b86fd8a7896.png)
才这个不是系统更新的锅，是我改/usr/share/dde-daemon/gesture.json的时候傻乎乎地往里面加了注释，好久没关机，更新重启这个问题才暴露出来，把这茬给忘了。
