### ISSUE TITLE
[Deepin Integration]~[V23-Beta3] 2024.01.16 @linuxdeepin/deepin-keyring by UTSweetyfish

### ISSUE THREAD

**Issue by UTsweetyfish** [linuxdeepin/developer-center#6923]
### package information | 软件包信息

deepin-keyring 2024.01.16

### Package repository address | 软件包仓库地址

```text
deb [trusted=yes] https://ci.deepin.com/repo/obs/home:/sweetyfish:/branches:/deepin:/stable:/main:/deepin-keyring:/2024.01.16/stable/ ./
```

### changelog | 更新信息

- Bump debhelper compat to 11
- Remove CHANGELOG.md
- Do not run postinst script

#6533

### test suggestion | 测试建议

场景
- 升级后 apt update
- 打一个新的 ISO，apt update
iso: https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240116/deepin-23-beige-beta3-amd64-20240116-141647.iso
### Sphere of influence | 影响范围

apt 操作

**Comment by babyfengfjx** [comment]
@kobe337  请开展回归验证。

**Comment by kobe337** [comment]
与研发同事沟通，两种方式验证：1、添加仓库升级验证 2、镜像安装验证https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240116/deepin-23-beige-beta3-amd64-20240116-141647.iso
以上均验证通过
![image](https://github.com/linuxdeepin/developer-center/assets/17869922/2f7023f2-8c65-403d-8854-be2bee6e1e7f)
