### ISSUE TITLE
[手势] [建议] 手势动作触发改进

### ISSUE THREAD

**Issue by wanywhn** [linuxdeepin/developer-center#693]
## 缺陷描述

四指左右切换工作空间、三只上下滑触发后，动作直接执行，不能跟随手势的进度而显示动画。

## 期望行为
WIndows与MacOS一样，比如四指切换切换工作空间时，四指向右滑动X距离，工作空间也滑动X距离。

### 发行版以及版本

Linux Deepin 15.8

**Comment by hualet** [comment]
这个是终极目标，但是现阶段应该还达不到 :)

**Comment by ziqiangxu** [comment]
> 这个是终极目标，但是现阶段应该还达不到 :)

四指可以改一下方向吗，现在感觉挺别扭的

**Comment by wanywhn** [comment]
> > 这个是终极目标，但是现阶段应该还达不到 :)
> 
> 四指可以改一下方向吗，现在感觉挺别扭的

更改这个文件/usr/share/dde-daemon/gesture.json

**Comment by ziqiangxu** [comment]
> > > 这个是终极目标，但是现阶段应该还达不到 :)
> > 
> > 
> > 四指可以改一下方向吗，现在感觉挺别扭的
> 
> 更改这个文件/usr/share/dde-daemon/gesture.json

谢谢，这个我知道。但是我觉得最好默认就与当前这种方向反过来，或者加个开关。

**Comment by shule1987** [comment]
> > > > > 这个是终极目标，但是现阶段应该还达不到 :)
> > > > 
> > > > 
> > > > 四指可以改一下方向吗，现在感觉挺别扭的
> > > 
> > > 
> > > 更改这个文件/usr/share/dde-daemon/gesture.json
> > 
> > 
> > 谢谢，这个我知道。但是我觉得最好默认就与当前这种方向反过来，或者加个开关。
> 
> 嗯 我也这样觉得 @wangjia12 @shule1987 @jouyouyun 要不改一下？

这个和鼠标的自然滚动道理是一样的,有些人适应开,有些人适应关, 加个开关可以,  @wangjia12 现在只能加在触控板选项里面, 想个文案吧

**Comment by hualet** [comment]
> > > > > > 这个是终极目标，但是现阶段应该还达不到 :)
> > > > > 
> > > > > 
> > > > > 四指可以改一下方向吗，现在感觉挺别扭的
> > > > 
> > > > 
> > > > 更改这个文件/usr/share/dde-daemon/gesture.json
> > > 
> > > 
> > > 谢谢，这个我知道。但是我觉得最好默认就与当前这种方向反过来，或者加个开关。
> > 
> > 
> > 嗯 我也这样觉得 @wangjia12 @shule1987 @jouyouyun 要不改一下？
> 
> 这个和鼠标的自然滚动道理是一样的,有些人适应开,有些人适应关, 加个开关可以, @wangjia12 现在只能加在触控板选项里面, 想个文案吧

或者那样，复用触摸板的自然滚动设置，如果是自然滚动，那四指左划就是切换到右边的工作区，如果不是自然滚动，则反之。

**Comment by listenerri** [comment]
@electricface

**Comment by abcfy2** [comment]
顶这个需求。希望加入自定义手势的功能，或者加入“鼠标中键”的手势。在windows下印象中默认三指点击是模拟鼠标中键。鼠标中键可以用于后台打开浏览器标签页，以及关闭标签页使用。

我看`/usr/share/dde-deamon/gesture.json`好像没有鼠标中键的定义啊

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
