### ISSUE TITLE
Alot of lag on Archlinux

### ISSUE THREAD

**Issue by InvisibleRasta** [linuxdeepin/developer-center#694]
The DE is quite laggy with  desktop effects on. I am running it on archlinux. Desktop background looks like its flashing a bit. mouse cursor lags and stops for a second onc ein a while, same thing when typing, Ita actually takes like one second for the letters to appear when i type quickly.
With effects off there is no way to resize windows... the border is way too small.

System:    Host: arch Kernel: 4.19.2-arch1-1-ARCH x86_64 bits: 64 Desktop: Deepin 15.8 
           Distro: Arch Linux 
Machine:   Type: Desktop Mobo: ASUSTeK model: TUF Z370-PRO GAMING v: Rev 1.xx serial: 
           UEFI: American Megatrends v: 1704 date: 09/14/2018 
CPU:       Topology: 6-Core model: Intel Core i7-8700 bits: 64 type: MT MCP L2 cache: 12.0 MiB 
           Speed: 800 MHz min/max: 800/4600 MHz Core speeds (MHz): 1: 798 2: 800 3: 800 4: 800 5: 800 
           6: 800 7: 800 8: 800 9: 800 10: 800 11: 802 12: 800 
Graphics:  Device-1: NVIDIA GP104 [GeForce GTX 1070 Ti] driver: nvidia v: 415.18 
           Display: x11 server: X.Org 1.20.3 driver: nvidia unloaded: modesetting,vesa 
           resolution: 2560x1440~60Hz

**Comment by antechdesigns** [comment]
Out of curiosity does turning off /com/deepin/dde/daemon/appearance in dconf-editor help?
I made an archiso two weeks ago and worked perfectly, trying to create one now is totally impossible ;(

**Comment by hualet** [comment]
> The DE is quite laggy with desktop effects on. I am running it on archlinux. Desktop background looks like its flashing a bit. mouse cursor lags and stops for a second onc ein a while, same thing when typing, Ita actually takes like one second for the letters to appear when i type quickly.
> With effects off there is no way to resize windows... the border is way too small.
> 
> System: Host: arch Kernel: 4.19.2-arch1-1-ARCH x86_64 bits: 64 Desktop: Deepin 15.8
> Distro: Arch Linux
> Machine: Type: Desktop Mobo: ASUSTeK model: TUF Z370-PRO GAMING v: Rev 1.xx serial:
> UEFI: American Megatrends v: 1704 date: 09/14/2018
> CPU: Topology: 6-Core model: Intel Core i7-8700 bits: 64 type: MT MCP L2 cache: 12.0 MiB
> Speed: 800 MHz min/max: 800/4600 MHz Core speeds (MHz): 1: 798 2: 800 3: 800 4: 800 5: 800
> 6: 800 7: 800 8: 800 9: 800 10: 800 11: 802 12: 800
> Graphics: Device-1: NVIDIA GP104 [GeForce GTX 1070 Ti] driver: nvidia v: 415.18
> Display: x11 server: X.Org 1.20.3 driver: nvidia unloaded: modesetting,vesa
> resolution: 2560x1440~60Hz

Can you test if GNOME having the same issue for us ?

**Comment by hualet** [comment]
> Out of curiosity does turning off /com/deepin/dde/daemon/appearance in dconf-editor help?
> I made an archiso two weeks ago and worked perfectly, trying to create one now is totally impossible ;(

what do you mean?

**Comment by InvisibleRasta** [comment]
gnome 3.30 is smooth

**Comment by hualet** [comment]
@sonald

**Comment by kwiniarski97** [comment]
for me im running a laptop and needed to change cpu profile to performance

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
