### ISSUE TITLE
国产操作系统Deepin初体验之Windows & Mac or Linux

### ISSUE THREAD

**Issue by fengwenyi** [linuxdeepin/developer-center#695]
## install

在抖音上看到有人安装国产操作系统，然后就搜了一下，感觉不错，就起来安装了，下面说一下体验吧。
1、作为一个老手，很快就搞定了，安装较为简单。
2、从安装开始，我就一直再看百度的介绍，和官网的宣传资料，说实在的，我真的被惊呆了。就想尝试一下，也确实足以让我震惊。

## feel

下面说一下，我遇到的一些问题吧。
1、安装成功后，需要输入用户信息，账号提示我只能小写，不能用昵称和账号吗，昵称用来看，账号用来登录。
2、说是Linux，我也这么认为，但是，外观就是Mac，软件就是Windows，这可槽糕透了。我觉得官网应该考虑下，这到底应该怎么取舍。
3、关于下载，下载的文件居然不是放在~/Download下面，一看，果然又是Windows惹的祸，这一点我还是喜欢Mac的做法。

## me

我是Java程序员，我想试一下Deepin能不能用作服务器，或者用来做开发工作，就目前而言，我在安装jdk上犯难了。

## end

最后的最后，我还是期待国产操作系统越来越好。

**Comment by wanywhn** [comment]
jdk都不会安装还敢自称是一个JAVA程序员？（无恶意哦，勿生气）
你说说安装jdk的步骤

**Comment by justforlxz** [comment]
诶，难道不都是去官网下载jdk放到家目录，然后改path的吗？ windows和mac下我也是这么做的。

**Comment by justforlxz** [comment]
1. 你可能需要掌握一些基本的linux知识，账号体系不是说所有的系统都要求一样的。
2. 外观和系统本身无关吧，只是设计风格不同而已，不太明白你说的软件就是windows是什么意思，可能是跑了几个wine的程序？
3. 下载确实是~/Downloads ，软件也可以主动改另存为的目录，不要什么都拿果子当衡量标准。

**Comment by fengwenyi** [comment]
他不是说是Linux系统吗，我看oracle官网也没有下载说明，就习惯性的用rpm安装。嗯，这个是我的问题。
我们都知道，Windows是看了苹果才开发出来的，后来苹果又反正Windows，所以才有了关闭在左边。
我就不明白，你为啥就怕说是像呢？
我的意思是，界面有mac的影子，软件又是Windows，有点怪怪的感觉。
当然，你要觉得deepin已经无限完美了，那我也就不说什么了。

**Comment by BLumia** [comment]
> 下载的文件居然不是放在~/Download 下面

遵循 xdg-user-dirs 规范的应用程序会把下载的东西放到（在 Deepin 中默认是） `~/Downloads/` 中，如果你下载所使用的应用不遵循标准也不能怪 Deepin 啊...

> 我是 Java 程序员，我想试一下 Deepin 能不能用作服务器，或者用来做开发工作，就目前而言，我在安装 jdk 上犯难了。

如果你有曾使用过任何 Linux 发行版并在上方部署过 JDK ，那么 Deepin 上的操作方式其实是一样的。如果你没有尝试过的话，请参阅 [Debian Wiki 上的 Java 条目，JDK 部分](https://wiki.debian.org/Java#JDK) 。

顺便，Developer-Center 目前是做 bug 反馈类的用途的，初见安装体验之类的主题建议发在 [论坛](https://bbs.deepin.org/) 而不是这里。

无论如何，感谢你的体验。
