### ISSUE TITLE
In the Deepin file manager, if you select several files and view the properties, then several windows with the properties of each selected file open

### ISSUE THREAD

**Issue by ElectroPositiv** [linuxdeepin/developer-center#696]
In the Deepin file manager, if you select several files and view the properties, then several windows with the properties of each selected file open.

1. Open the deepin file manager.
2. Select multiple files
3. Select properties of selected files.
4. See the result
Video here: 
1. https://youtu.be/QCTqZ3RKTjc
2. https://youtu.be/iZFjCBeSDyU

**Comment by BLumia** [comment]
It's designed be like this, not sure why. @shule1987 , @wangjia12 .

**Comment by ElectroPositiv** [comment]
> Это спроектировано так, не знаю почему. @ shule1987 , @ wangjia12 .

It`s not comfortable.

**Comment by aiamuzz** [comment]
True ... the whole idea of selecting multiple files / folders is to view their collective size ... this size however is definitly shown at the bottom of the screen ... the multiply windows are just distracting ... I can't figure out a reason why we would want individual file/folder property window here !

a single property window should suffice in such a situation don't you think ?

**Comment by ElectroPositiv** [comment]
@aiamuzz Yes, one property window for all files is enough.
The implication is that if I select all the files, then I want to see the properties of all the files in one window.

**Comment by shule1987** [comment]
I'm sorry for the inconvenience. This is how we designed, the properties of each file to be displayed separately when the selected files are less than 16,  a combined window  when more than 16. 
This is how we design it because many users need to difference between the reference documents and detailed informations, if you just want to check the size of the selected files, select file(s), and then the status bar can see statistics.

**Comment by aiamuzz** [comment]
> This is how we designed, the properties of each file to be displayed separately when the selected files are less than 16

Oh ... that's great ... didn't know it had a purpose ... for comparing seems a fair option ... 

BTW i didn't know there was a 16 file limit ... just tested it.

**Comment by BLumia** [comment]
Closed, feel free to reopen this issue if you have any further question to ask :)

**Comment by aiamuzz** [comment]
@BLumia ... i have opened 2 separate issues ... you can check them out ... one is a Bug and one is a Suggestion
