### ISSUE TITLE
[Deepin Integration]~[V23-Beta3] Auto integrate from deepin-authenticate  by @dengbo to V23-Beta3 

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#6964]
### Package information | 软件包信息

包名 | 版本
--  | --
deepin-authenticate | 2.0.4
libdeepin-authenticate | 2.0.4
libdeepin-authenticate-dev | 2.0.4

### Package repository address | 软件包仓库地址

    deb [trusted=yes]  http://10.20.64.70/repo-deepin-authenticate/ tmp dde

### Changelog | 更新信息
修复升级中锁屏问题

### Influence | 影响范围
认证 登录

**Comment by babyfengfjx** [comment]
@vivianxf  请开展回归验证。

**Comment by dengbo11** [comment]
- deepin-authenticate 集成验证
- 影响范围：系统密码登录，升级锁屏登录场景

**Comment by Zeno-sole** [comment]
关联集成： https://github.com/linuxdeepin/developer-center/issues/6853

**Comment by dengbo11** [comment]
该集成不带： https://github.com/linuxdeepin/developer-center/issues/6863 这个问题

**Comment by babyfengfjx** [comment]
@xuqi27837288  请开展集成验证。

**Comment by xuqi27837288** [comment]
麻烦帮忙确认一下集成情况,稍后可以开始测试后再将集成指派过来,谢谢~

**Comment by dengbo11** [comment]
- fix: https://github.com/linuxdeepin/developer-center/issues/7001
- 影响范围：系统登录认证，锁屏认证

**Comment by babyfengfjx** [comment]
@xuqi27837288  请开展回归验证，结合 #7021

**Comment by xuqi27837288** [comment]
【环境】：
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240118
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【结论】：
测试通过，暂无严重问题及影响
