### ISSUE TITLE
Deepin 15.8 Grub screen Information ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#697]
Hi,

I see that the new grub screen in Deepin 15.8, and the information at the bottom where it would read ... 'c' for grub command line and press 'e' for editing boot options ... is no longer mentioned ?

Is this information intentionally removed or accidentally missed out ?

**Comment by wangjia12** [comment]
Thank you for your kind advice, but may not be adopted recently.

**Comment by wangjia12** [comment]
We will add it back soon 
@electricface

**Comment by electricface** [comment]
https://cr.deepin.io/#/c/dde/dde-api/+/41341
英文文案：【Use ↑ and ↓ keys to change selection, Enter to confirm, E to edit the commands before booting or C for a command-line】
中文文案：【使用 ↑ 和 ↓ 键移动选择条，Enter 键确认, E 编辑启动命令，C 命令行】
