### ISSUE TITLE
org.deepin.camera集成

### ISSUE THREAD

**Issue by kamiyadm** [linuxdeepin/developer-center#6973]
### package information | 软件包信息

org.deepin.camera | 6.0.6.4

### Package repository address | 软件包仓库地址

url: 10.0.36.228:9001 name: develop-snipe

### test suggestion | 测试建议

修改仓库为测试仓库： ll-cli repo modify http://10.0.36.228:9001 --name develop-snipe
安装或者更新相机： ll-cli install org.deepin.camera 观察版本是否为6.0.6.4
测试基本功能是否正常
在帮助手册里观察相机的手册是否显示正常

### Sphere of influence | 影响范围

https://pms.uniontech.com/bug-view-238775.html
https://pms.uniontech.com/bug-view-240363.html

**Comment by kamiyadm** [comment]
@Zeno-sole

**Comment by babyfengfjx** [comment]
@vivianxf  请开展回归验证。

**Comment by vivianxf** [comment]
测试不通过:
更新到最新版本后,相机打开仍然闪退

**Comment by vivianxf** [comment]
集成验证通过,请及时合入:

1.按照建议修改玲珑仓库,更新应用版本成功
2.bug:pms238775 pms240363验证通过
3.相机功能正常
4.系统功能正常

综上所述,本次集成通过~
