### ISSUE TITLE
deepin安装器 deepin-installer 6.0.33 修复vmware安装黑屏 20240118

### ISSUE THREAD

**Issue by ArchieMeng** [linuxdeepin/developer-center#6977]
### package information | 软件包信息

deepin-installer 6.0.33

### Package repository address | 软件包仓库地址

安装镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20240118/deepin-23-beige-beta3-amd64-20240118-145956.iso

### changelog | 更新信息

- 修复在vmware中安装日更版镜像，选择镜像内核版本后，显示黑屏的问题。

### test suggestion | 测试建议

- 按关联issue环境尝试安装
关联issues：https://github.com/linuxdeepin/developer-center/issues/6661

### Sphere of influence | 影响范围

- 安装器窗口特效

### ADDITIONAL INFORMATION | 额外补充

无

**Comment by babyfengfjx** [comment]
@xuqi27837288  请开展回归验证。

**Comment by xuqi27837288** [comment]
@Zeno-sole 这个下周有新镜像了再进行测试~到时候我们再把5.15和6.1的都看一下~

**Comment by Zeno-sole** [comment]
https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240119/deepin-23-beige-beta3-amd64-20240119-135339.iso   @xuqi27837288  @SuperEffie

**Comment by ArchieMeng** [comment]
@Zeno-sole 更新修复方法 https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20240122/deepin-23-beige-beta3-amd64-20240122-152237.iso

**Comment by Zeno-sole** [comment]
> [@Zeno-sole](https://github.com/Zeno-sole) 更新修复方法 https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240122/deepin-23-beige-beta3-amd64-20240122-162229.iso

镜像更新： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240122/deepin-23-beige-beta3-amd64-20240122-175919.iso

**Comment by Zeno-sole** [comment]
> > [@Zeno-sole](https://github.com/Zeno-sole) 更新修复方法 https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240122/deepin-23-beige-beta3-amd64-20240122-162229.iso
> 
> 镜像更新： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240122/deepin-23-beige-beta3-amd64-20240122-175919.iso

镜像更新： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240124/deepin-23-beige-beta3-amd64-20240124-114109.iso  (更新mesa解决VMware环境下kwin崩溃问题)

**Comment by xuqi27837288** [comment]
【环境】：
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240124
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【结论】：
测试通过，暂无严重问题及影响
