### ISSUE TITLE
新增硬盘之后，文件管理器标签提示被移动或删除<xz1>

### ISSUE THREAD

**Issue by ziqiangxu** [linuxdeepin/developer-center#698]
请将下方的缺陷汇报模板中的文字替换为您实际需要汇报的缺陷所对应的描述文字。

## 缺陷描述

为台式机新增一块硬盘，然后之前在文件管理器添加的书签提示已被移动或删除。

## 复现步骤

为台式机新增一块硬盘

## 期望行为

仍然能找到原来的书签（使用硬盘的UUID应该可以解决这个问题吧）

## 截图

![_ _20181127100327](https://user-images.githubusercontent.com/18530271/49053949-4c28ea00-f22d-11e8-819b-e9c4e159e7d8.jpg)

### 发行版以及版本

[如. Linux Deepin 15.8.1]

### 相关的软件包版本

dde-file-manage 4.7.1.1-1    amd64        File manager front end

**Comment by hualet** [comment]
没有太懂，@Blumia 知道什么意思么？

**Comment by BLumia** [comment]
> 没有太懂，@BLumia 知道什么意思么？

可能是指磁盘设备uuid变了，挂载位置不固定，书签记住的路径也就不对了这样？

给设备分区重命名应该就可以解决这个问题了吧？
