### ISSUE TITLE
org.deepin.Runtime 集成

### ISSUE THREAD

**Issue by kamiyadm** [linuxdeepin/developer-center#6987]
### package information | 软件包信息

org.deepin.Runtime | 23.0.0.29

### Package repository address | 软件包仓库地址

url: 10.0.36.228:9001 name: develop-snipe

### changelog | 更新信息

集成旧版本re2，修复邮箱打不开问题

### test suggestion | 测试建议

修改仓库为测试仓库： ll-cli repo modify http://10.0.36.228:9001 --name develop-snipe
更新或者安装任意应用，观察org.deepin.Runtime版本是否为23.0.0.29
测试邮箱是否能正常打开

### Sphere of influence | 影响范围

https://github.com/linuxdeepin/developer-center/issues/6986

**Comment by kamiyadm** [comment]
@Zeno-sole

**Comment by babyfengfjx** [comment]
@vivianxf  请开展回归验证。

**Comment by vivianxf** [comment]
集成验证通过,请及时合入:

1.切换仓库成功
2.按照测试建议升级org.deepin.runtime版本正确
3.issue:#6989验证通过
4.issue:#6500 重新激活
5.issue:#6991另有集成跟踪##6997
6.重新激活和提交的issue不影响邮箱整体使用
7.玲珑应用基本功能正常

综上所述,本次集成通过~
