### ISSUE TITLE
dde-file-manager: crashes while watching vector images

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/developer-center#699]
[Description](https://youtu.be/WLK-TtZfPbo)
[Log](https://pastebin.com/PEgpeVgD)

**Comment by BLumia** [comment]
Known issue (https://github.com/linuxdeepin/internal-discussion/issues/571)

btw, you can get a related coredump stacktrace by installing `systemd-coredump` and `gdb` and then run `coredumpctl gdb` when the app crashed.

Thanks for reporting the bug.

**Comment by BLumia** [comment]
of course.

**Comment by es20490446e** [comment]
When I have a moment I will do so.

**Comment by es20490446e** [comment]
[Coredump](https://pastebin.com/77Ky0Xw3)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
