### ISSUE TITLE
【deepin_V23_beta3】【一般】【立即】【集成测试】【系统】beta2升级到beta3后,执行sudo apt  dist-upgrade  命令报错

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#7001]
### SUMMARY | 问题概要

beta2升级到beta3后,执行sudo apt  dist-upgrade命令报错
关联集成:#https://github.com/linuxdeepin/developer-center/issues/6964

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://cdimage.uniontech.com/community/releases/23-Beta2/deepin-desktop-community-23-Beta2-amd64.iso
仓库:
deb [trusted=yes]  http://10.20.64.70/repo-deepin-authenticate/ tmp dde
deb [trusted=yes] http://10.20.64.70/beta3/ beige main community commercial
deb [trusted=yes] http://10.20.64.70/deepin-community/beta3-dde/ beige dde
deb [trusted=yes] http://10.20.64.72:82/deepin:/stable:/dde/stable/ ./
deb [trusted=yes] http://10.20.64.70/repo-kernel/ beta3 main
```

### STEPS TO REPRODUCE | 复现步骤

1.添加上述仓库从控制中心升级beta2到beta3(详细步骤参考关联集成https://github.com/linuxdeepin/developer-center/issues/6853)
2.在终端执行命令:sudo apt  dist-upgrade
3.观察命令执行结果

### OBSERVED RESULT | 观察到的结果

1.执行命令报错
![截图_deepin-terminal_20240119140745](https://github.com/linuxdeepin/developer-center/assets/96415804/2442da4f-e562-4545-9c97-795d35068f53)

### EXPECTED RESULT | 期望的结果

1.命令执行无报错

**Comment by babyfengfjx** [comment]
@Zeno-sole  可以优先安排分析。

**Comment by Zeno-sole** [comment]
deepin-authenticate hook脚本执行错误

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240116
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240116
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
