### ISSUE TITLE
Feature request : Multiple Window Tiling to the right/left ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#701]
Currently only one window can be tiled to the right and one to the left ...

In a typical use case this comes handy while dragging files mostly to the browser upload API's ...

Window tiling to the right(tiling to the left is not convinient for this purpose) is preferred ... currently only one window can be tiled ... it would be nice not to have no restrictions on the no. of windows that can be tiled to the right or left ...

**Will this be possible to achieve ... by removing the single window restriction ?**

**Comment by ag14774** [comment]
It used to work ok. Then one day, someone decided "you know what?? it would be really cool if we added a useless restrictions, just for fun". https://github.com/linuxdeepin/developer-center/issues/573

**Comment by hualet** [comment]
it's a planned feature.

**Comment by igormcoelho** [comment]
@aiamuzz this is strange, because it works for me for most windows.
For example, if I tile left the terminal, and my atom editor, both can go to the left or right at the same time (one behind another). But if I tile a browser, chrome or firefox, only one can stay on the left or right.
In fact, dde-file-manager also do not allow tiling at the same side :thinking: I don't know if terminal/atom is the "good" or the "wrong" case now xD

**Comment by aiamuzz** [comment]
> @aiamuzz this is strange, because it works for me for most windows.

hmmmm ... but i think its not happening ... i tried terminal on the left, it worked ... and i tried deepin file manager to left, it didnt' work ... but worked on the right ... after that i tried to push browser to right or left ... wouldn't go as terminal and file manager were already there ... its very inconsistent the way it behaves at one time and behaves differently another time ....

**Comment by igormcoelho** [comment]
> its very inconsistent the way it behaves at one time and behaves differently another time ....

Yep, the combination file manager + browser does not work for me as well... the only one at the same time until now is Atom + Terminal, all the rest cannot combine. Editors like VS Code don't even allow left or right tiling in any case. I that applications have some specifics to allow or not allow these things.
@aiamuzz did it work before on Deepin? Can someone point which commit caused this, perhaps we can discover how to revert this behavior locally.

**Comment by aiamuzz** [comment]
@BLumia ...

this command configured into a shortcut used to tile windows
`qdbus com.deepin.wm /com/deepin/wm com.deepin.wm.TileActiveWindow 2`

now that deepin-wm is switched to kwin ... could you let us know how we can configure a shortcut to tile windows to the right/left ?

**Comment by BLumia** [comment]
cc @zccrs

**Comment by igormcoelho** [comment]
My deepin is 15.10, and shortcuts are still working:
Tile Left (`Super <-`):  `qdbus com.deepin.wm /com/deepin/wm com.deepin.wm.TileActiveWindow 1`
Tile Right (`Super ->`):  `qdbus com.deepin.wm /com/deepin/wm com.deepin.wm.TileActiveWindow 2`

Is 15.10 already kwin?

**Comment by aiamuzz** [comment]
> My deepin is 15.10, and shortcuts are still working:
> Tile Left (`Super <-`): `qdbus com.deepin.wm /com/deepin/wm com.deepin.wm.TileActiveWindow 1`
> Tile Right (`Super ->`): `qdbus com.deepin.wm /com/deepin/wm com.deepin.wm.TileActiveWindow 2`
> 
> Is 15.10 already kwin?

@igormcoelho ... seems like you may be running DeepinWM and not kwin ... FYI the shortcuts work on DeepinWM when installed manually even on 15.11 !

**Comment by amadeubarbosa** [comment]
My DDE is using kwin AFAIK (my `ps aux` said: kwin_x11 -platform dde-kwin-xcb:appFilePath=/usr/bin/kwin_no_scale)

I created some custom keyboard shortcuts for the following and it seems working fine:
```shell
# tile 1/4 left bottom
qdbus com.deepin.wm /com/deepin/wm com.deepin.wm.TileActiveWindow 9
# tile 1/4 right bottom
qdbus com.deepin.wm /com/deepin/wm com.deepin.wm.TileActiveWindow 10
# tile 1/4 left upper
qdbus com.deepin.wm /com/deepin/wm com.deepin.wm.TileActiveWindow 5
# tile 1/4 right upper
qdbus com.deepin.wm /com/deepin/wm com.deepin.wm.TileActiveWindow 6
# tile 1/2 right
qdbus com.deepin.wm /com/deepin/wm com.deepin.wm.TileActiveWindow 2
# tile 1/2 left
qdbus com.deepin.wm /com/deepin/wm com.deepin.wm.TileActiveWindow 1
# tile 1/2 bottom
qdbus com.deepin.wm /com/deepin/wm com.deepin.wm.TileActiveWindow 8
# tile 1/2 upper
qdbus com.deepin.wm /com/deepin/wm com.deepin.wm.TileActiveWindow 7
```

I didn't ever know about qdbus or deepin accepts some commands from DBus. Very nice! I found your discussion by google and I would like to thank you for the tip! Help me a lot! I was using GNOME and gTile extesions, so those commands help me in transition to DDE.

**Comment by meiyixiang** [comment]
Thank you for your advice

**Comment by meiyixiang** [comment]
please update 20.4
