### ISSUE TITLE
Feature/Option request : A shortcut for 'Always on visible Workspace'

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#702]
Hi,

surprisingly i came across this really handy option ... don't know how long this option has been there ... but its really convenient when you are moving between workspaces.

And i am really using it a lot ... Hence this request ... Wouldn't it be a good idea to have this option be enabled with a keyboard shortcut ?

Until you consider ... is there any command that enables / disables this option ?
I could use it by adding a custom shortcut until you decided whether to add such an option to the system shortcuts .

**Comment by hualet** [comment]
I don't know a way/command to do that, perhaps @sonald can help you.

**Comment by aiamuzz** [comment]
@sonald ... thanks the command worked ...

It would be nice to expose this shortcut under the `Keyboard -> Shortcut -> Windows` category ... that way the users will know of it and use the same !!!

**Comment by sonald** [comment]
I'm not sure if this is a common daily frequent operation, so we just put the most needed in the control center. actually, there are tons of keybindings out there, and just tossing them all into the control center is not ideal and practical. :)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
