### ISSUE TITLE
Feature Request : Backup/Restore custom keyboard shortcuts and non-default shortcuts !

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#703]
Hi,

**Wouldn't it be great to have an option to Backup/Restore custom shortcuts as well as those system shorcuts which have been modified to use custom key combinations (Non-default shortcut keys) ?**

Shortcuts are something that add greatly to one's comfort zone in working on their personal systems, hence very important not to break the flow ... also its a long and laborious process to reconfigure all the shortcut keys you have grown so accustomed to. 

So i believe a backup/restore option would absolutely ensure, that one is not disconnected on one's own system !!!

In fact one better would be to have the option of multiple keyboard shortcut profile's(one could carry one's shortcut) ... i know its a stretch ... but a perfectly nice way to make one comfortable on a new system or a shared system ... **remember the shortcuts are for productivity and it gives us the feeling of being in control :) ... A multiple shortcut profile could definitely be a first on any linux distro's ... unless i am wrong**

**Comment by hualet** [comment]
Hmmm...you seem to be proposing too much feature requests in one single issue @aiamuzz :stuck_out_tongue_winking_eye: 

we can do this in the future, but definitely not this year, sorry dude.

**Comment by aiamuzz** [comment]
@hualet ... :stuck_out_tongue_closed_eyes: ... i know ... i just record it when the idea strikes ... wouldn't want to let the idea escape ... :stuck_out_tongue_winking_eye: 

But i am sure you agree that if your custom shortcuts stop working ... it destroys your work on that system ... hence the back/restore  and multiple shortcut profiles something like user workspaces ... 

You know i often find it very discomforting when i set up a new deepin OS for friends and family ... its a pain to use this new system without my usual shortcuts ... a multiple profile would enable me to download one and use it on any system and delete it once i am done.

Its certainly a productivity tool ... if you understand what i mean ... imagine you techies at your company ... a multiple profile on shortcuts will certainly make you guys life a breeze when using each others(colleagues) laptop/systems ...

**Comment by hualet** [comment]
I totally understand what you mean, dude :)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
