### ISSUE TITLE
无法打开文件管理器

### ISSUE THREAD

**Issue by ziqiangxu** [linuxdeepin/developer-center#704]
请将下方的缺陷汇报模板中的文字替换为您实际需要汇报的缺陷所对应的描述文字。

## 缺陷描述

在从另一个工作区切换（`shift + super + left`）过来之后，文件管理停止响应。在dock点击强行退出后无法启动。
![_ _20181128164553](https://user-images.githubusercontent.com/18530271/49139856-c2ad1100-f32d-11e8-8057-4101f5fd02a5.png)

### 发行版以及版本

[如. Linux Deepin 15.8.1]

### 相关的软件包版本

dde-file-manage 4.7.1.1-1    amd64        File manager front end

### 其他内容

其他可能有用的其他信息
![_deepin-system-monitor_20181128165638](https://user-images.githubusercontent.com/18530271/49140223-b2e1fc80-f32e-11e8-9814-802034e4c1bf.png)
窗口管理器cpu占用、和磁盘写入这么高持续的时间已经很久了

**Comment by BLumia** [comment]
通过上述描述无法复现。

通过给出的截图来看，看上去是已经有一个文件管理器实例存在了，但是没有显示出来。可能是窗管或者别的原因导致的。原因根据上述描述无法推测。

遇到这个情况 `killall dde-file-manager` 然后再开应该就没问题了。如果能稳定复现的话可以贴一下复现步骤以及是不是需要什么特定的条件来触发。

**Comment by BLumia** [comment]
哦对了... 我们没有 deepin 15.8.1 这个版本啊... 15.8.1 是个里程碑而已，你版本号怎么来的....

**Comment by ziqiangxu** [comment]
> 哦对了... 我们没有 deepin 15.8.1 这个版本啊... 15.8.1 是个里程碑而已，而且截止目前这个里程碑的相关更新压根没推送啊，你版本号怎么来的....

这个好像是之前一次更新的时候看到的，不过从控制中心看是15.8桌面版

**Comment by BLumia** [comment]
那我就先关掉了，能复现的话可以重新打开并贴一下详细信息 :)
