### ISSUE TITLE
org.deepin.music集成

### ISSUE THREAD

**Issue by kamiyadm** [linuxdeepin/developer-center#7046]
### package information | 软件包信息

org.deepin.music | 7.0.3.5

### Package repository address | 软件包仓库地址

url: 10.20.64.64:9001 name: develop-snipe

### changelog | 更新信息

修复启动闪退问题

### test suggestion | 测试建议

修改仓库为测试仓库： ll-cli repo modify http://10.20.64.64:9001 --name develop-snipe
安装或者更新音乐： ll-cli install org.deepin.music 观察版本是否为7.0.3.5
测试音乐播放功能是否正常

### Sphere of influence | 影响范围

https://github.com/linuxdeepin/developer-center/issues/7043

**Comment by kamiyadm** [comment]
@Zeno-sole

**Comment by babyfengfjx** [comment]
@vivianxf  请开展回归验证。

**Comment by vivianxf** [comment]
集成测试不通过

按照测试建议更新最新版本音乐,音乐应用依然无法打开

**Comment by kamiyadm** [comment]
> 集成测试不通过
> 
> 按照测试建议更新最新版本音乐,音乐应用依然无法打开

缺失的qml组件已经被深度之家引入了，可以等下次镜像重新验证一下
