### ISSUE TITLE
'Recent List' Last Access column sort inconsistent behavior

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#706]
## Describe the bug

the information displayed under the 'Last Access' column of the Recent list seems kind of inaccurate given how its sorted based on the last access times

Also i notice that if i open files from the recent list and close them the files order is not getting changed ... Ideally it should move up the top of the list given i just accessed(opened) it.

## Expected behavior

- The Last Access sorting should be precise to the second
- The files that are opened from the list should immediately get pushed to the top of the recent list

## Screenshots

![deepinscreenshot_select-area_20181129104551](https://user-images.githubusercontent.com/3283676/49200793-57fae480-f3c4-11e8-95f1-b6651bfc3811.png)

### Distro & Version
Linux Deepin 15.8

### Related package version
dde-file-manager v 4.7.1.1

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
