### ISSUE TITLE
最新分支linux-6.6.y，有build error

### ISSUE THREAD

**Issue by pangqiao** [linuxdeepin/developer-center#7077]
### SUMMARY | 问题概要

获取分支
https://github.com/deepin-community/kernel/tree/linux-6.6.y

复现方式：
make allyesconfig
make -j$(nproc)
2.error log:
CC drivers/net/ethernet/pensando/ionic/ionic_lif.o
CC drivers/net/ethernet/pensando/ionic/ionic_rx_filter.o
CC drivers/net/ethernet/pensando/ionic/ionic_ethtool.o
In file included from drivers/net/ethernet/microchip/sparx5/sparx5_dcb.c:7:
./include/net/dcbnl.h:135:9: error: expected specifier-qualifier-list before ‘KABI_RESERVE’
135 | KABI_RESERVE(1)
| ^~~~~~~~~~~~
CC drivers/net/ethernet/pensando/ionic/ionic_txrx.o
CC drivers/net/ethernet/pensando/ionic/ionic_stats.o

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
获取分支
https://github.com/deepin-community/kernel/tree/linux-6.6.y

复现方式：
make allyesconfig
make -j$(nproc)
2.error log:
CC drivers/net/ethernet/pensando/ionic/ionic_lif.o
CC drivers/net/ethernet/pensando/ionic/ionic_rx_filter.o
CC drivers/net/ethernet/pensando/ionic/ionic_ethtool.o
In file included from drivers/net/ethernet/microchip/sparx5/sparx5_dcb.c:7:
./include/net/dcbnl.h:135:9: error: expected specifier-qualifier-list before ‘KABI_RESERVE’
135 | KABI_RESERVE(1)
| ^~~~~~~~~~~~
CC drivers/net/ethernet/pensando/ionic/ionic_txrx.o
CC drivers/net/ethernet/pensando/ionic/ionic_stats.o

这是由最后一个提交引起的
9fc763cab25c (origin/linux-6.6.y) Init kabi reservation for driver and net system (#56)
```

### STEPS TO REPRODUCE | 复现步骤

获取分支
https://github.com/deepin-community/kernel/tree/linux-6.6.y

复现方式：
make allyesconfig
make -j$(nproc)

### OBSERVED RESULT | 观察到的结果

2.error log:
CC drivers/net/ethernet/pensando/ionic/ionic_lif.o
CC drivers/net/ethernet/pensando/ionic/ionic_rx_filter.o
CC drivers/net/ethernet/pensando/ionic/ionic_ethtool.o
In file included from drivers/net/ethernet/microchip/sparx5/sparx5_dcb.c:7:
./include/net/dcbnl.h:135:9: error: expected specifier-qualifier-list before ‘KABI_RESERVE’
135 | KABI_RESERVE(1)
| ^~~~~~~~~~~~
CC drivers/net/ethernet/pensando/ionic/ionic_txrx.o
CC drivers/net/ethernet/pensando/ionic/ionic_stats.o

### EXPECTED RESULT | 期望的结果

Build Pass

### ADDITIONAL INFORMATION | 额外补充

这是最后一个提交引起的。
回退这个提交就可以编译过~
9fc763cab25c (origin/linux-6.6.y) Init kabi reservation  for driver and net system (#56)

或者dcbnl.h 里面引用头文件 #include <linux/kabi.h>

**Comment by Decodetalkers** [comment]
你是说什么项目

**Comment by BLumia** [comment]
deepin-community 组织下的项目请反馈到 deepin-community 组织下的对应项目仓库的 issue 面板中。linuxdeepin 组织只处理第一方项目的缺陷。

烦请移步： https://github.com/deepin-community/kernel/issues

**Comment by pangqiao** [comment]
好的谢谢
