### ISSUE TITLE
Selecting entries in file manager missing a use case scenario 

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#708]
## Describe the bug

the arrow keys missing a use case where its supposed to select file folder entries

## To Reproduce

1.create 2 blank documents/folders in any folder for the purpose of reproducing ...
2. Now use the arrow key to delete one of them ... after you've deleted one
3. Now try selecting the remaining file/folder with your arrow keys ... you'll notice you are just not able to select the file/folder that's left.

## Expected behavior

the arrow key should select the last entry with the up/down arrow key

## Enviroments *(please complete the following information):*

Linux Deepin 15.7 ...
dde-file manager version: v1.8.2]

**Comment by zccrs** [comment]
@BLumia 看一下，如果没问题就测试 @zhaofangfangdeepin

**Comment by BLumia** [comment]
应该是个没修的bug，放下次集中修。

**Comment by aiamuzz** [comment]
@BLumia ...

i guess both issues have relapsed on 15.11 ...

The first post as well as the below ... both bugs have returned ...

> @BLumia ...
> 
> **I think there is a little slip up here ...**
> 
> Yes this above use case has been covered but this also has sort of reset another process ...
> 
> go to a folder create a few file/folder entries ... go to a middle folder and delete it ... now use the up and dows arrow keys to continue scrolling ...
> 
> **Expected behavior :**
> in an ideal situation the scrolling(using the up/down arrow key) should resume either from above the deleted file/folder or from below the deleted file/folder ...
> 
> **Bug :**
> **As you an see somehow the memory of the position of the deleted file/folder seems to be lost and using the up/down arrow key starts the scroll from the beginning of the list (from the first entry at the top) ... this might have to be fixed** !!!

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
