### ISSUE TITLE
Teamviewer与dde-dock存在严重兼容问题

### ISSUE THREAD

**Issue by wjkcs** [linuxdeepin/developer-center#709]
## 缺陷描述

Teamviewer无法正常打开，同时dde-dock陷入假死，较长时间后才能恢复正常

## 复现步骤

复现步骤为:

1. 打开 teamviewer
2. 缺陷 teamviewer和dde-dock失去响应 发生

## 期望行为

teamviewer正常打开运行，同时dde-dock不受影响

### 发行版以及版本

Linux Deepin 15.8

### 相关的软件包版本

teamviewer 14.0.14470
dde-dock 4.8.1-3

**Comment by listenerri** [comment]
最新版 dde-dock (4.8.4) 应该已经解决了这个问题

**Comment by wjkcs** [comment]
新的系统更新已修复这一问题
