### ISSUE TITLE
部分系统组件测试

### ISSUE THREAD

**Issue by UTsweetyfish** [linuxdeepin/developer-center#7095]
### package information | 软件包信息

- src:libcdr
- src:gtk-vnc
- src:network-manager-applet
- src:policykit-1-gnome

### Package repository address | 软件包仓库地址

```
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/stable:/main/stable/ ./
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/stable:/community/stable/ ./
```

### test suggestion | 测试建议

请在升级场景下（Beta 2 -> Beta 3），添加上述仓库后测试

1. 确认安装了 libreoffice，测试未安装 libicu71、或 libicu71 可安全移除
2. 接 1，测试 libreoffice 能够正常，确认 libcdr-0.1-1 版本不为 0.1.6-deepin，版本应为 0.1.6-3+rb4 或 0.1.7-1
3. 安装 virt-manager，确认 libgtk-vnc-2.0-0 与 libgvnc-1.0-0 为 1.3.1-1 版本
4. 安装 network-manager-gnome，确认版本为 1.34.0-2
5. 接 4，安装 network-manager-gnome 后，确认若安装了 policykit-1-gnome，版本应为 0.105-8
6. libnma0 版本为 1.10.6-2

### Sphere of influence | 影响范围

- libreoffice
- virt-manager
- network-manager-applet

**Comment by babyfengfjx** [comment]
@kobe337  请开展集成验证。

**Comment by UTsweetyfish** [comment]
>     4. 安装 network-manager-gnome，确认版本为 1.34.0-2
> 
>     5. 接 4，安装 network-manager-gnome 后，确认若安装了 policykit-1-gnome，版本应为 0.105-8

还应确认 libnma0 版本为 1.10.6-2

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Beta2/
内核：Linux deepinb2-PC 6.1.32-amd64-desktop-hwe #23.01.00.20 SMP PREEMPT_DYNAMIC Thu Jan 11 18:45:10 CST 2024 x86_64 GNU/Linux


【结论】：
beta2发布镜像升级至beta3环境，相关提测包测试通过，暂无严重问题及影响

libicu71
![libicu71](https://github.com/linuxdeepin/developer-center/assets/17869922/344173aa-189c-46e1-b231-28ca2ce590cd)
相关依赖
![yl](https://github.com/linuxdeepin/developer-center/assets/17869922/3c060ae6-6793-4a93-9b30-fef95a19ac9d)
相关依赖
![yl2](https://github.com/linuxdeepin/developer-center/assets/17869922/faa29507-aa75-4a47-a382-163f7381039d)
虚拟系统管理器
![kvm](https://github.com/linuxdeepin/developer-center/assets/17869922/b0b7d5f7-e356-417e-8324-904d42fe62e8)
libreoffice
![libreoffice](https://github.com/linuxdeepin/developer-center/assets/17869922/75bed036-3c05-4280-a4f1-aa5e30454d15)
