### ISSUE TITLE
集成 deepin-desktop-environment

### ISSUE THREAD

**Issue by UTsweetyfish** [linuxdeepin/developer-center#7096]
### package information | 软件包信息

deepin-desktop-environment 2024.01.25

### Package repository address | 软件包仓库地址

```
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/deepin-community:/deepin-desktop-environment:/PR-44/deepin_develop/
```

### changelog | 更新信息

https://github.com/deepin-community/deepin-desktop-environment/pull/44

移除预装 uos-license-content

目前社区版本的许可协议在 deepin-deepinid-client 包里，uos-license-content 是 UOS 的包，不需要预装

### test suggestion | 测试建议

添加CI源，更新 deepin-desktop-environment 至 2024.01.25 后，手动卸载 uos-license-content。

测试控制中心的 最终用户许可协议 与 隐私政策 显示是否正常。

如有余力可发散测试。

### ADDITIONAL INFORMATION | 额外补充

安装器中的协议是自带的，不是系统里的，无需测试。

**Comment by babyfengfjx** [comment]
@kobe337  请开展集成验证。

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240124/deepin-23-beige-beta3-amd64-20240124-114109.iso
内核：Linux deepin0124-PC 6.1.32-amd64-desktop-hwe #23.01.00.20 SMP PREEMPT_DYNAMIC Thu Jan 11 18:45:10 CST 2024 x86_64 GNU/Linux

【结论】：
beta3集成镜像0124测试通过，暂无严重问题及影响，与研发同事沟通，此提测目前是在不影响依赖的情况下remove掉uos-license-content。
![7096](https://github.com/linuxdeepin/developer-center/assets/17869922/0382c5f4-380a-4242-a1cd-0ead88c8fd63)
