### ISSUE TITLE
deepin-editor segfault

### ISSUE THREAD

**Issue by antechdesigns** [linuxdeepin/developer-center#710]
## Describe the bug

right clicking inside a text document with deepin-editor causes segfault

## To Reproduce

open a file with deepin-editor, right click the open document

## Expected behavior

be able to choose a right click menu option

### Additional context

`deepin-editor[3952]: segfault at 8 ip 00007fdd2ade54ba sp 00007ffdadf49af0 error 4 in libQt5Widgets.so.5.11.2[7fdd2ada3000+391000]`

`No appenders assotiated with category org.kde.ksyntaxhighlighting
[Error  ] <> Repository got deleted while a highlighter is still active!
Segmentation fault (core dumped)`

**Comment by rekols** [comment]
@felixonmars
