### ISSUE TITLE
【deepin_V23_beta3】【一般】【有空】【集成测试】【DDE】【任务栏】一直隐藏下，任务栏在左或右 第一次唤起时，任务栏只显示一半

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#7106]
### SUMMARY | 问题概要
关联集成：https://github.com/linuxdeepin/developer-center/issues/7085
_No response_

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240124/deepin-23-beige-beta3-amd64-20240124-114109.iso
任务栏 6.0.32
```

### PRE-REQUIREMENT | 预置条件

1. 安装镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240124/deepin-23-beige-beta3-amd64-20240124-114109.iso
2. 任务栏为最小显示
3. 任务栏设置为一直隐藏

### STEPS TO REPRODUCE | 复现步骤

1. 将任务栏设置为 最小 - 将任务栏 状态 设置为 一直隐藏
2. 在控制中心 - 个性化 - 桌面 中 将 任务栏设置为 左 或 右 ， 将鼠标移动到 屏幕 左 或 右 唤起 任务栏

### OBSERVED RESULT | 观察到的结果

2. 任务栏在左或右 第一次唤起时，任务栏只显示一半
![7040](https://github.com/linuxdeepin/developer-center/assets/96416089/7b59f5bb-0ed1-4d9e-9297-37274987f631)

### EXPECTED RESULT | 期望的结果

2. 唤醒时任务栏显示正常

**Comment by babyfengfjx** [comment]
@tsic404  有空可以优化~

**Comment by tsic404** [comment]
请在新版本上回归验证

**Comment by luodeepin** [comment]
验证通过
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240724/deepin-23-beige-release-amd64-20240724-184123.iso
dde-shell 0.0.30
dde-control-center 6.0.59
dde-launchpad 0.8.1

![录屏_选择区域_20240725152001](https://github.com/user-attachments/assets/c13a53c9-0cb7-461e-9bb5-0eb25984a842)
