### ISSUE TITLE
Cannot move column width in File Manager when there is a search operation underway ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#711]
Hi,

Don't know if its a bug or its a missed out '**use-case**' to implement the option to move the column width or the new double click the column divider to resize.

Currently one cannot alter the column width when the file manager is running a search operation.

**Comment by aiamuzz** [comment]
... didn't make even to 15.11 ... gentle reminder ... :))

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
