### ISSUE TITLE
Character on screen when 'Ctrl+Shift+T' is pressed in the Deepin Terminal app ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#712]
When a command running on the terminal hitting **'Ctrl+Shift+T'** to open a new tab on the terminal results in 2 characters on the current terminal tab ... as shown in the screenshot(character at the bottom left corner) below ...

![deepinscreenshot_select-area_20181130233253](https://user-images.githubusercontent.com/3283676/49306524-68ac7700-f4f8-11e8-98cb-05ebc6c418e9.png)

can't say its a bug or a anomaly ... whether it needs correction is upto you to decide.

**Comment by hualet** [comment]
it should be a bug.

**Comment by aiamuzz** [comment]
reminder ... i guess its missed even 15.11 ... :))

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
