### ISSUE TITLE
集成 deepin-desktop-environment 20240129

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#7128]
### package information | 软件包信息

deepin-desktop-environment 2024.01.29

### Package repository address | 软件包仓库地址

```
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/deepin-community:/deepin-desktop-environment:/PR-45/deepin_develop/
```

### changelog | 更新信息

https://github.com/deepin-community/deepin-desktop-environment/pull/45

移除预装 dcc-insider-plugin，屏蔽控制中心更新目录下“技术预览”模块

### test suggestion | 测试建议

验证新装镜像 控制中心下是否存在技术预览模块
关联issues: https://github.com/linuxdeepin/developer-center/issues/7124
镜像地址： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240129/deepin-23-beige-beta3-amd64-20240129-140553.iso

**Comment by babyfengfjx** [comment]
@SuperEffie  请开展回归验证。

**Comment by SuperEffie** [comment]
【验证结论】：测试通过，请走下一步流程
【备注信息】：控制中心-更新，技术预览入口已屏蔽
【截图信息】：
