### ISSUE TITLE
unable to install unmet dependencies 

### ISSUE THREAD

**Issue by malwarebo** [linuxdeepin/developer-center#713]
Trying to install firefox and I am getting this error.  Is it because the OS is based on unstable Debian? 

`sudo apt install firefox
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 firefox : Depends: libc6 (>= 2.28) but 2.27-3 is to be installed
           Recommends: xul-ext-ubufox but it is not installable
E: Broken packages
`

**Comment by hualet** [comment]
can't reproduce this one, maybe because you're using other PPAs ?

**Comment by irfnhm** [comment]
I think it is because the unstable debian base.

**Comment by hualet** [comment]
> I think it is because the unstable debian base.

can you get the package list you've installed ? 

> dpkg -l 

and the content of `/etc/apt/sources.list` ?
