### ISSUE TITLE
org.deepin.mail集成

### ISSUE THREAD

**Issue by kamiyadm** [linuxdeepin/developer-center#7152]
### package information | 软件包信息

org.deepin.mail | 6.4.7.2

### Package repository address | 软件包仓库地址

url: http://10.20.64.64:9001
name: develop-snipe

### changelog | 更新信息

修复邮件预览异常弹窗问题

### test suggestion | 测试建议

修改仓库为测试仓库： ll-cli repo modify http://10.20.64.64:9001/ --name develop-snipe
安装或者更新邮箱： ll-cli install org.deepin.mail 观察版本是否为6.4.7.2
测试邮箱邮件预览功能是否正常

### Sphere of influence | 影响范围

https://github.com/linuxdeepin/developer-center/issues/6500

**Comment by kamiyadm** [comment]
@Zeno-sole

**Comment by babyfengfjx** [comment]
@vivianxf  请开展回归验证。

**Comment by kamiyadm** [comment]
稍等，还有点问题

**Comment by vivianxf** [comment]
集成验证通过,请及时合入:

1.添加仓库升级成功,包版本正确
2.issue: https://github.com/linuxdeepin/developer-center/issues/6500 验证通过
3.邮箱功能正常使用

综上所述,本次集成通过~
