### ISSUE TITLE
[Deepin Integration]~[V23-Beta3] feat: Architecture Avoid doing kill(-1) by zeno @deepin-community/qtbase-opensource-src by zeno

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#7159]
### Package information | 软件包信息

包名 | 版本
--  | --
qtbase-opensource-src | 5.15.8-1+deepin4

### Package repository address | 软件包仓库地址

    deb [trusted=yes]  https://ci.deepin.com/repo/obs/deepin:/CI:/deepin-community:/qtbase-opensource-src:/PR-21/deepin_develop/  ./

### qtbase-opensource-src (5.15.8-1+deepin4) unstable; urgency=medium

  * Fix loongarch64 Architecture Avoid doing kill(-1) in QProcess destructor

 -- LiChengGang <lichenggang@uniontech.com>  Tue, 30 Jan 2024 09:48:54 +0800

### Test suggestion | 测试建议

修复可能出现的Qt程序fork失败杀死用户会话的问题(现象：进入桌面30秒后用户进程会话被杀死)
上游bug链接：  https://bugreports.qt.io/browse/QTBUG-86285

### Influence | 影响范围

Qt5相关程序

**Comment by babyfengfjx** [comment]
@kobe337  请开展集成验证。

**Comment by kobe337** [comment]
上游修复关键代码：
![上游已做修复](https://github.com/linuxdeepin/developer-center/assets/17869922/7505cc99-e019-429b-bc89-937640f88bbc)
deepin23已做处理：
![deepin23已做处理](https://github.com/linuxdeepin/developer-center/assets/17869922/2ba8d10f-e2f7-4416-b1fe-9ef001133be3)

根据提交信息，与研发同事沟通，得知此次合入主要为龙芯loong64(3A6000台式机) 出现的问题，以上游修复代码，全架构合入。
本次验证，在x86环境，添加仓库全量升级，验证重启后进入系统正常为结论，验证通过。

【环境】：
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240129/deepin-23-beige-beta3-amd64-20240129-140553.iso
内核：Linux deepin0129-PC 6.1.32-amd64-desktop-hwe #23.01.00.20 SMP PREEMPT_DYNAMIC Thu Jan 11 18:45:10 CST 2024 x86_64 GNU/Linux

【结论】：
beta3集成镜像0129测试通过，暂无严重问题及影响
