### ISSUE TITLE
【deepin_V23_beta3】【一般】【立即】【预发布测试】【DDE】【任务栏】开启缩放后，启动器 和 任务栏应用区域与插件区域 和 屏幕底部的间距没有保持一致

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#7186]
### SUMMARY | 问题概要

1. 与设计确认启动器 和 任务栏应用区域与插件区域 和 屏幕底部的间距无论在什么情况下都需要保持一致
2. 开发分析需要任务栏进行修复

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240124/deepin-23-beige-beta3-amd64-20240124-114109.iso
任务栏 6.0.32
```

### PRE-REQUIREMENT | 预置条件

1. 安装镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240124/deepin-23-beige-beta3-amd64-20240124-114109.iso
2. 开启缩放

### STEPS TO REPRODUCE | 复现步骤

1. 检查启动器与任务栏的间距，和 任务栏上的应用区域到插件区域的间距，和任务栏到屏幕底部的间距，三个间距的缝隙间距是否保持一致

### OBSERVED RESULT | 观察到的结果

1. 启动器 和 任务栏应用区域与插件区域 和 屏幕底部的间距没有保持一致
![0o](https://github.com/linuxdeepin/developer-center/assets/96416089/e86db811-6aa0-424c-9e96-061b961bcf23)

### EXPECTED RESULT | 期望的结果

启动器 和 任务栏应用区域与插件区域 和 屏幕底部的间距无论在什么情况下都需要保持一致

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240129
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
