### ISSUE TITLE
Feature Request : File manager multiple select properties option ... file/folder name in clear view !

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#720]
Hi,

I just got to know recently that the option of selecting multiple files/folders and viewing their properties which throws up multiple property windows was for the purpose of comparing the statistics of the items side-by-side.

While this feature may come in handy ... but if we view it in its current form ... i cannot identify the files and their names so i can compare as the multiple windows look all the same ...

I was wondering how about the icon and the filenames switched places and the Name went on top of the Icon in the property window then the purpose of comparison will actually be functional as currently without the name one has to guess the position of the files then want to compare by blindly clicking on all the files to find them.

![deepinscreenshot_dde-file-manager_20181203103338](https://user-images.githubusercontent.com/3283676/49354049-efbf4200-f6e6-11e8-8cc4-c4d2da45d4b7.png)

**Comment by aiamuzz** [comment]
make sure you utilize the **complete space visible** when the full limit of 16 cascading windows is displayed ... the space shown in the screenshot ...

![deepinscreenshot_select-area_20181203103946](https://user-images.githubusercontent.com/3283676/49354240-d074e480-f6e7-11e8-83e0-1f69b5098741.png)

**Comment by shule1987** [comment]
Hi,thanks for your feedback, I will redesign the top area.

**Comment by aiamuzz** [comment]
thanks @shule1987 ... look forward to it ... it will make the provision more functional ... as currently its flying blind with no clue as to which property window belongs to which file ... and if comparing properties of files is the primary objective of the multi window property array than its very important the the file name is visible at first glance across the multiple windows ...

**Comment by shule1987** [comment]
Yes, it make sense.

> 在 2019年1月15日，下午2:32，aiamuzz <notifications@github.com> 写道：
> 
> across

**Comment by wangjia12** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/862
