### ISSUE TITLE
Do you want this features? Better search, resizable workspaces, etc

### ISSUE THREAD

**Issue by avently** [linuxdeepin/developer-center#721]
Hello. I developed some usefull things for myself. I can make PR here if you want all/some of the features:

- (1) better search. Now after you pressed hotkey for search Ctrl+Shift+F and then pressed Enter or next/previous button in search panel the search will not happens. So you need to press something again in a search box to make the search working. I fixed it.
- (2) custom (user-provided) themes support located in ~/.config/deepin/deepin-terminal/themes. The same syntax but in another directory.
- (3) tabbar can be located at the bottom of the screen for tiling WMs. For tiling WMs "close" button in the top right corner is unneeded. So we can place tabbar at the bottom of the screen. I can make it customsizable.
- (4) Gtk.Menu that replace Deepin Menu dependency and have a liiiitle bit different look and feel with different themes.
- (5) refactored CMakeLists. Now you have to add every new *.vala file name to the CMakeLists file. It's not usefull. I did universal CMakeLists. Just take a look on it.
- (6) resizable workspaces. You can use Ctrl+Alt+Left/Right/Top/Bottom buttons to resize workspaces in any direction.

Here is a link for my repo:
https://github.com/avently/terminal/commits/master

Just choose what you want to get and I'll make a PR with one commit per feature.

**Comment by BLumia** [comment]
Haven't take a look at the code but some of the features seems quite awesome to me, but still got some questions to ask:

> 1. Now after you pressed hotkey for search Ctrl+Shift+F and then pressed Enter or next/previous button in search panel the search will not happens.

Just tested it on my machine and it works well, can you still able to reproduce this issue in the most recent released version of deepin-terminal?

> 2. custom (user-provided) themes support located in ~/.config/deepin/deepin-terminal/themes. The same syntax but in another directory.

> 3. tabbar can be located at the bottom of the screen for tiling WMs

Didn't review the patch but let me +1 for this feature, will take a look at your patch later :)

> 4. Gtk.Menu that replace Deepin Menu dependency and have a liiiitle bit different look and feel with different themes.

imo we should have a build-time configuration option for this feature, so Deepin (distro) user will still get a uniform look-n-feel and users who doesn't want the deepin-menu dept can get rid of this dept with the new option.

>5. refactored CMakeLists

The CMakeLists file changed after your patch, feel free to do this if your patch is still working in the current code base.

> 6. resizable workspaces. You can use Ctrl+Alt+Left/Right/Top/Bottom buttons to resize workspaces in any direction.

+1 for this feature, configurable shortcut will be great ;)

Will check out your patches later, it'll be great if you can check the patches can still works well in the most recent version first.

**Comment by aiamuzz** [comment]
> resizable workspaces. You can use Ctrl+Alt+Left/Right/Top/Bottom buttons to resize workspaces in any direction.

How do i use '**Ctrl+Alt+Shift+**' instead of  '**Ctrl+Alt**' for the resize workspace shortcut ? Is it changeable ?

**Comment by avently** [comment]
@BLumia 
search (1) is already merged to master from my commits. That's why it works well for you:)
refactored CMakeLists (5) is already refactored from my commits too. And that file looks good now too.

Most painful patch is a patch for menu. Other patches will be easy to port to new versions.
Just check them out from my repo and if you'll like them I'll update them

Also about menu. deepin-menu is not needed as a dependency for Gtk menu. You said we can use build optiion. OK, what about dependency for the package? How to make a universal dependency? From my point of view, deepin menu should be removed from package dependencies since deepin menu should alredy be present (if user use your other apps) or not present in other situations.
Also I can create a new setting and user can switch between menus on the fly so build option will not be needed.

**Comment by avently** [comment]
@aiamuzz it is changeable (from config file) but it will not work with shift key because Shift Alt fires first and changes a system language.

**Comment by aiamuzz** [comment]
> @aiamuzz it is changeable (from config file) but it will not work with shift key because Shift Alt fires first and changes a system language.

You mean to say it changes the keyboard language or system language ? ... i use the 'Super+Space' to change input language ... or ... you are talking about a whole different thing all together ...

Ctrl+Alt+arrow keys i find is easier to set it for opening horizontal and vertical terminal windows ... and Alt+arrow keys is very convenient to navigate between those multiple terminal windows ... so the only combination left was Ctrl+Alt+Shift+arrow keys to resize those windows ... which config file are you referring to ... could you please provide the path to that config file ?

**Comment by avently** [comment]
@aiamuzz my config for terminal located at ~/.config/deepin/deepin-terminal/config.conf
Take a look inside it. You can change keybindings there and then restart terminal to test.
If you don't use Alt + Shift for changing input language you can bind Ctrl + Alt + Shift for what you want, it should work (but I can't check it)

**Comment by aiamuzz** [comment]
Oh ... ok ...

You are right ... i am unable to set the '**Ctrl+Alt+Shift**' combination cannot be set as a shortcut in the terminal settings ...

**Comment by avently** [comment]
@BLumia 
Take a look at this PR https://github.com/linuxdeepin/deepin-terminal/pull/48
It doesn't have merge conflicts since files in the master branch is the same. So custom themes should work fine even now.
What this PR do is allows to user to provide his own themes in config directory (~/.config/deepin/deepin-terminal/themes). Pretty easy.

**Comment by BLumia** [comment]
> Take a look at this PR linuxdeepin/deepin-terminal#48

Sorry for the late reply, quite busy these days. I'll take a look asap after my current work done.

**Comment by BLumia** [comment]
Hi and do you still have plan to submit your other patches (linuxdeepin/deepin-terminal#48 already merged)?

**Comment by avently** [comment]
@BLumia yes, of course. End of this week, I hope. Can you suggest a good ide for vala?

**Comment by BLumia** [comment]
> @BLumia yes, of course. End of this week, I hope. Can you suggest a good ide for vala?

Well I'm not a pro of vala, for me I use vscode and sometimes vim for editing vala code, but it seems not so good which only provides syntax highlighting. @sonald Any vala IDE suggested?

**Comment by avently** [comment]
@BLumia I uploaded first PR here: https://github.com/linuxdeepin/deepin-terminal/pull/106

Second PR is ready too but it is based on first and you wanted features separated into different PRs so I'm waiting your approval and then will submit this: https://github.com/avently/deepin-terminal/tree/bottomtabbar

**Comment by sonald** [comment]
@BLumia  I just use vim with syntax highlighting only, no fancy features. maybe you can try builder from gnome.

**Comment by hualet** [comment]
I think we can close this issue now, and just left the detail discussion to PRs against each feature.
