### ISSUE TITLE
【deepin_V23_beta3】【一般】【有空】【预发布测试】【DDE】【控制中心】控制中心为列表菜单模式时,deepin ID模块应不展示描述文字,与其他一级菜单风格保持一致

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#7211]
### SUMMARY | 问题概要

必现问题

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240201/

控制中心:6.0.44
```

### PRE-REQUIREMENT | 预置条件

控制中心菜单为列表模式

### STEPS TO REPRODUCE | 复现步骤

观察deepin ID模块一级菜单的展示效果

### OBSERVED RESULT | 观察到的结果

一级菜单下展示有文字描述信息

![截图_选择区域_20240201165158](https://github.com/linuxdeepin/developer-center/assets/62528742/52fa22d8-f542-4abf-acdc-31eb5c3f536c)

### EXPECTED RESULT | 期望的结果

无文字描述信息

**Comment by babyfengfjx** [comment]
@kegechen  这个可以优化一下。

**Comment by kegechen** [comment]
这个是目前设计如此，第一个模块会显示描述信息，对应的图标模式下第一个也图标大一些。
