### ISSUE TITLE
【deepin_V23_beta3】【严重】【立即】【预发布测试】【DDE】【控制中心】deepin ID登陆后退出,无法二次登录

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#7218]
### SUMMARY | 问题概要

deepin ID登陆后退出,无法二次登录

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240201/deepin-23-beige-beta3-amd64-20240201-180524.iso
```

### STEPS TO REPRODUCE | 复现步骤

1.在系统内登录deepin ID(控制中心,应用商店,深度之家)
2.退出deepin ID
3.再次登录
4.观察现象

### OBSERVED RESULT | 观察到的结果

1.deepin ID登陆后退出,无法二次登录

### EXPECTED RESULT | 期望的结果

1.deepin ID登陆后退出,可以重复登录

**Comment by babyfengfjx** [comment]
@dengbo11  这个需要优先分析，我这边是重启系统后账号登录状态就丢失了。

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240201
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
