### ISSUE TITLE
新版2018.12.05使得chrome图标消失

### ISSUE THREAD

**Issue by gitawego** [linuxdeepin/developer-center#722]
请将下方的缺陷汇报模板中的文字替换为您实际需要汇报的缺陷所对应的描述文字。

## 缺陷描述

更新后chrome图标变成默认程序图标 （紫色的两个，一个是chrome，一个是hangout）
![deepinscreenshot_select-area_20181205102229](https://user-images.githubusercontent.com/438120/49505304-c4219080-f87b-11e8-9b0f-2a0a0dd726dd.png)

## 复现步骤

更新后启动chrome

### 发行版以及版本

Linux Deepin 15.8 2018.12.05

**Comment by listenerri** [comment]
请描述你用了什么扩展程序(或其他东西)让chrome有了一个托盘图标 ?

**Comment by BLumia** [comment]
hangout 就能复现

**Comment by listenerri** [comment]
等 linuxdeepin/developer-center#670 里的补丁打了应该可以解决这个问题

不过目前 dock 对 SNI 的图标查找缺了一个 fallback , 这个可以完善一下

**Comment by listenerri** [comment]
@liuwen123 使用谷歌浏览器安装扩展, 搜索hangout, 安装后即可复现这个问题:

https://cr.deepin.io/c/dde/dde-dock/+/40835

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
