### ISSUE TITLE
deepin v23 beta3 依赖问题，无法安装npm

### ISSUE THREAD

**Issue by student-ice** [linuxdeepin/developer-center#7239]
### SUMMARY | 问题概要

依赖问题，无法安装npm
![image](https://github.com/linuxdeepin/developer-center/assets/59855569/10179219-df97-467e-90fc-5b6739bf2577)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin v23 beta3
```

### PRE-REQUIREMENT | 预置条件

全新安装的beta3

### STEPS TO REPRODUCE | 复现步骤

1. 打开终端，输入 `sudo apt install npm`
2. 观察是否能正常安装

### OBSERVED RESULT | 观察到的结果

依赖问题，无法安装

### EXPECTED RESULT | 期望的结果

能够正常安装

**Comment by babyfengfjx** [comment]
@UTsweetyfish  帮忙确认一下。

**Comment by UTsweetyfish** [comment]
node 依赖还差一堆啊

**Comment by UTsweetyfish** [comment]
搞差不多了，但是要等 OBS 构建完，被阻塞了

**Comment by student-ice** [comment]
> 搞差不多了，但是要等 OBS 构建完，被阻塞了

得等下波内测集成吗？

**Comment by UTsweetyfish** [comment]
> 得等下波内测集成吗？

集成 刚搞差不多

**Comment by kobe337** [comment]
https://github.com/linuxdeepin/developer-center/issues/7396 验证通过。

**Comment by UTsweetyfish** [comment]
现在应该可以了

**Comment by student-ice** [comment]
@UTsweetyfish 可以安装了,辛苦了！
