### ISSUE TITLE
[Feature request] used space in Deepin file manager

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#724]
Can you please add "Used space" option in the properties menu of a partition in Deepin file manager?

**Comment by wangjia12** [comment]
"Free space" is more useful information , and perhaps the "Used space"  is repetitive here.

**Comment by hualet** [comment]
> But that won't hurt anything right?
> By the way, most of the modern operating systems have this feature.
> 
> There is also a patch of it in Gerrit : https://cr.deepin.io/41000/

I think most people would like you to tell them who many space's left instead of calculate it by themselves?

**Comment by SiamSami** [comment]
> > But that won't hurt anything right?
> > By the way, most of the modern operating systems have this feature.
> > There is also a patch of it in Gerrit : https://cr.deepin.io/41000/
> 
> I think most people would like you to tell them who many space's left instead of calculating it by themselves?

That is what I was trying to say

**Comment by SiamSami** [comment]
So, when is the feature coming then?

**Comment by KimHono** [comment]
Yes, just something as simple as a progression bar, like offered by the file-manager Nemo !
