### ISSUE TITLE
[Feature Request] Vertical system tray and ability to create folders on the dock

### ISSUE THREAD

**Issue by caglarturali** [linuxdeepin/developer-center#725]
The system tray gets crowded pretty quickly and this can be problematic especially in fashion mode. And if you also have lots of shortcuts on the dock, the situation becomes even more unmanageable. These spacing problems could be fixed by incorporating some structuring abilities. Such as...

**Vertical system tray:**
This one would exclusively go alongside fashion mode. The following mockup clearly demonstrates the advantages of such a feature.
![vertical-dock](http://i64.tinypic.com/24wesls.png)

**Ability to create folders on the dock:**
I don't have a mockup for this one, but it's pretty self-explanatory. :) It would be nice to have such a feature for those of us who have lots of shortcuts on the dock.

**Comment by aiamuzz** [comment]
interesting idea ... would be nice to have vertical drawer for the system tray ... If its not too difficult maybe an option for the user to decide the matrix of this vertical tray ... a single column as shown by @caglarturali  ... or ... a user preferred ... custom row x custom column of user choice

**Comment by aiamuzz** [comment]
> it has the problem that people that need some icons to be always visible will not be satisfied.

@hualet ... then a vertical drawer makes sense in the matrix (rows x columns) format ...

for example ... lets say i need the wifi, sound, disk, and music icons to show always ... that makes 4 icons which will be 4 columns so the vertical drawer will be 4 columns wide and the rows will fill up the other system tray icons stacked vertically above ...

the advantage of this will be that the width of the dock will be under check ... if you notice the current option of either expanding or collapsing is a all visible or nothing ... which isn't very optimized you see.

I certainly like to access the sound and music option always ... and i don't like the all system tray icons spanning over the dock making unnecessarily wide ...

**Comment by hualet** [comment]
> > it has the problem that people that need some icons to be always visible will not be satisfied.
> 
> @hualet ... then a vertical drawer makes sense in the matrix (rows x columns) format ...
> 
> for example ... lets say i need the wifi, sound, disk, and music icons to show always ... that makes 4 icons which will be 4 columns so the vertical drawer will be 4 columns wide and the rows will fill up the other system tray icons stacked vertically above ...
> 
> the advantage of this will be that the width of the dock will be under check ... if you notice the current option of either expanding or collapsing is a all visible or nothing ... which isn't very optimized you see.
> 
> I certainly like to access the sound and music option always ... and i don't like the all system tray icons spanning over the dock making it unnecessarily wide ...

we're working on the version that some icons can be always visible.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
