### ISSUE TITLE
System not responds to clicks and use keyboard

### ISSUE THREAD

**Issue by wysher** [linuxdeepin/developer-center#726]
## Describe the bug

Sometimes Deepin freezes, and not responds to clicks, and most keyboard keys like alt+tab. In this "freeze" state I can hit start button and menu will appear, or with keyboard restart system (using alt+cltr+del then arrow keys + enter), but not further work can be done unless system reboots. 

## To Reproduce
1. Open at least one application - it's icon should show at task bar.
2. Move mouse cursor above this icon and scroll down
3. Just after scrolling click quickly on icon.

## Result: 
Window will minimize, but there will be no way to unminimize it or click elsewhere.

In my case if I'll wait a little bit after scrolling I will get list of all windows. Maybe there is some kind of overlay, which remains after clicking on the same spot?

### Distro & Version
Linux Deepin 15.8 x64

**Comment by sonald** [comment]
@hualet 应该检查下dock在scroll触发显示窗口和预览的竞争情况。

**Comment by sonald** [comment]
@justforlxz  this is most likely a corner case of not correctly canceling window preview, and so without leaving wm in a **grabbed** previewing state.

**Comment by sonald** [comment]
https://cr.deepin.io/#/c/deepin-wm/+/40561

**Comment by sonald** [comment]
@justforlxz 在鼠标滚轮滚动的时候，发送了多大几十个请求，这个要控制啊

**Comment by liuwen123** [comment]
已修复
