### ISSUE TITLE
【deepin_V23_Beta3】【玲珑】 玲珑部分软件创建到应用菜单栏的快捷方式无效 ,但桌面快捷方式有效

### ISSUE THREAD

**Issue by LFRon** [linuxdeepin/developer-center#7262]
### SUMMARY | 问题概要

Deepin v23-beta3下玲珑软件创建到应用菜单栏的快捷方式无效 ,但桌面快捷方式有效
比如GIMP

https://github.com/linuxdeepin/developer-center/assets/141307807/214ff726-d5f0-4dc2-a2b6-4e41c23e7a20

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
OS:Deepin v23-beta3并加入了内测源
```

### STEPS TO REPRODUCE | 复现步骤

1.玲珑里安装GIMP
2.在应用菜单里打开
3.发送快捷方式再打开

### OBSERVED RESULT | 观察到的结果

应用菜单内无法打开,但快捷方式可以

### EXPECTED RESULT | 期望的结果

两个都能打开

### ADDITIONAL INFORMATION | 额外补充

我录的视频发不到深度之家,只好发来这了😂

**Comment by dengbo11** [comment]
@black-desk GIMP玲珑应用的desktop 中的TryExec 为空导致打不开

**Comment by black-desk** [comment]
@kamiyadm

**Comment by LFRon** [comment]
> @black-desk GIMP玲珑应用的desktop 中的TryExec 为空导致打不开

大佬您好,但是我关注到它桌面快捷方式的TryExec也是空的,但是就可以打开😂

**Comment by black-desk** [comment]
> > @black-desk GIMP玲珑应用的desktop 中的TryExec 为空导致打不开
> 
> 
> 
> 大佬您好,但是我关注到它桌面快捷方式的TryExec也是空的,但是就可以打开😂

@ComixHe 瞄一眼

**Comment by ComixHe** [comment]
> > > @black-desk GIMP玲珑应用的desktop 中的TryExec 为空导致打不开
> > 
> > 
> > 大佬您好,但是我关注到它桌面快捷方式的TryExec也是空的,但是就可以打开😂
> 
> @ComixHe 瞄一眼
> 
> 感觉可能是文管那边有fallback

文管fallback了gio launch

**Comment by black-desk** [comment]
@kamiyadm @l631197874 加一个钩子 具体要调什么dbus接口问 @ComixHe

**Comment by black-desk** [comment]
@ComixHe tryexec是空的时候 标准说怎么处理？ 原文引过来一下

**Comment by ComixHe** [comment]
> @ComixHe tryexec是空的时候 标准说怎么处理？ 原文引过来一下

Path to an executable file on disk used to determine if the program is actually installed. If the path is not an absolute path, the file is looked up in the $PATH environment variable. If the file is not present or if it is not executable, the entry may be ignored (not be used in menus, for example).

**Comment by LFRon** [comment]
大佬您好,我近期发现这个问题是在安装了玲珑应用之后立即出现的,我试了一下注销DDE后重新登录,菜单栏里的应用快捷方式就能打开了😂

**Comment by black-desk** [comment]
> 大佬您好,我近期发现这个问题是在安装了玲珑应用之后立即出现的,我试了一下注销DDE后重新登录,菜单栏里的应用快捷方式就能打开了😂

非常感谢

你现在补充的这个现象和上面的分析是吻合的，节后咱会着手修复的。

**Comment by dengbo11** [comment]
类似问题（ https://github.com/linuxdeepin/developer-center/issues/7272 ）

**Comment by ComixHe** [comment]
- https://github.com/linuxdeepin/developer-center/issues/6935 原因相同

**Comment by babyfengfjx** [comment]
@ComixHe  可以修复后一起提交验证。
