### ISSUE TITLE
Glitch with the dark theme in Deepin file manager

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#727]
## Describe the bug
The bug is that after turning on the dark theme if we close the file manager and reopen it, then the computer view will have white colour in the background.

![deepin-screen-recorder_dde-file-manager_20181207175948](https://user-images.githubusercontent.com/33563064/49646794-6f804000-fa4a-11e8-8dcb-ad93a50674ea.gif)

**Comment by BLumia** [comment]
Cannot reproduce here. Is the following reproduce steps correct?

 1. Init state: a single file manager instance in Light theme
 2. Turn the file manager in Dark theme
 3. Close file manager and open file manager
 4. See the result

**Comment by SiamSami** [comment]
Yes, the steps are correct. By the way, I am running Archlinux with the latest version of DDE.

**Comment by BLumia** [comment]
@justforlxz Could you test it on your Arch installation and check if that happens? Thx.

**Comment by jbblack** [comment]
This is happening for me, too. Also on Arch w/ the latest version of DDE.

**Comment by SiamSami** [comment]
Looks like it got fixed...
