### ISSUE TITLE
应用商店及星火商店都自动删除软件安装包，不能自定义保存，重装不方便

### ISSUE THREAD

**Issue by apppoo** [linuxdeepin/developer-center#7271]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
v23 beta3
```

### STEPS TO REPRODUCE | 复现步骤

应用商店及星火商店都自动删除软件安装包，不能自定义保存，重装不方便

**Comment by LFRon** [comment]
用apt download呢

**Comment by BLumia** [comment]
星火商店的行为请反馈到星火那边，星火商店不是 deepin 的第一方组件。第一方的应用商店目前是预期行为，如果你是希望提需求的话建议走 “深度之家” 反馈 :)
