### ISSUE TITLE
文件管理器同个文件夹重复删除出现两个进度条，回收站出现两个

### ISSUE THREAD

**Issue by jay763190097** [linuxdeepin/developer-center#728]

**Comment by BLumia** [comment]
复现步骤？

**Comment by jay763190097** [comment]
文件夹内文件比较多，比如node_modules目录，删除较慢，没删完的时候继续右键删除

**Comment by jay763190097** [comment]
出现两个删除的进度条，回收站也出现两个相同文件夹

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
