### ISSUE TITLE
deepinid云服务模块集成申请（第六版）

### ISSUE THREAD

**Issue by Keima-lpj** [linuxdeepin/developer-center#7282]
### package information | 软件包信息

包名 | 版本
deepin-sync-daemon | 6.0.23.7

### Package repository address | 软件包仓库地址

deb  [trusted=yes] https://aptly.uniontech.com/pkg/nonfree-beige-v2/release-candidate/ZGVlcGluaWTkupHmnI3liqHnrKzkupTova4yMDI0LTAyLTAyIDEzOjE4OjA3/  unstable non-free

### changelog | 更新信息

修复了注销重进的内存泄露问题
将deepin-deepinid-daemon进程修改为非自启动

**Comment by dengbo11** [comment]
- fix: https://github.com/linuxdeepin/developer-center/issues/7218

**Comment by xuqi27837288** [comment]
【环境】：
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240201
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【结论】：
测试通过，暂无严重问题及影响
