### ISSUE TITLE
[Deepin Integration] cross-toolchain-base Build using glibc 2.37-12, linux 6.5.10, binutils 2.41-5

### ISSUE THREAD

**Issue by UTsweetyfish** [linuxdeepin/developer-center#7289]
### package information | 软件包信息

源码包 cross-toolchain-base 67deepin2

### Package repository address | 软件包仓库地址

```
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1031/testing/ ./
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1036/testing/ ./
```

### changelog | 更新信息

#7255 #7279

**Comment by xuqi27837288** [comment]
麻烦重新确认一下后再提交集成测试，谢谢~

**Comment by UTsweetyfish** [comment]
新增一个集成仓库
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1036/testing/ ./
请使用两个仓库一起复测
@xuqi27837288

**Comment by xuqi27837288** [comment]
【环境】：
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240201
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【结论】：
测试通过，暂无严重问题及影响
