### ISSUE TITLE
[Feature request] Shadows in the fonts

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#731]
On the desktop of DDE, if we change the wallpaper to a light one then it is quite difficult for us to read the name of the folders.

I think adding shadows in the fonts is a good idea.

![deepinscreenshot_select-area_20181212064656](https://user-images.githubusercontent.com/33563064/49839550-c2a31b80-fdd9-11e8-8b78-6e3727baaee2.png)

**Comment by wangjia12** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/846

racking in this issue.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
