### ISSUE TITLE
deepin-installer 6.0.36 版本集成

### ISSUE THREAD

**Issue by ArchieMeng** [linuxdeepin/developer-center#7311]
### package information | 软件包信息

包名 | 版本
-- | --
deepin-installer | 6.0.36

### Package repository address | 软件包仓库地址

https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20240301/deepin-23-beige-beta3-amd64-20240301-163825.iso

### changelog | 更新信息

修复分区4K对齐问题 https://github.com/linuxdeepin/developer-center/issues/6833
启用格式化分区按钮 https://github.com/linuxdeepin/developer-center/issues/4447
修复缩放下图标模糊的问题 https://github.com/linuxdeepin/developer-center/issues/6518
优化根分区做引导分区的提示信息 https://pms.uniontech.com/bug-view-222139.html

### test suggestion | 测试建议

参照相关issue描述

### Sphere of influence | 影响范围

格式化分区，图标缩放，分区起始位置

### ADDITIONAL INFORMATION | 额外补充

无

**Comment by babyfengfjx** [comment]
@kobe337  请开展回归验证。

**Comment by ArchieMeng** [comment]
@kobe337  镜像更新了，之前打的版本不对。https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20240301/deepin-23-beige-beta3-amd64-20240301-163825.iso

**Comment by kobe337** [comment]
4k对齐验证通过，尝试使用不同的设备，手动分区为128.9G后，通过命令sudo fdisk -l 查看开始扇区是8的倍数。
![4k（副本）](https://github.com/linuxdeepin/developer-center/assets/17869922/eb0f48be-6987-46f1-8ad5-d9cd938e4959)

**Comment by kobe337** [comment]
4K屏下显示异常
![2024 03 04_15 08 03](https://github.com/linuxdeepin/developer-center/assets/17869922/235bb9b4-8f54-46b8-a312-c41f76fee325)

**Comment by kobe337** [comment]
4k下图标过大，部分图标超出选中框背景
![0e1de46057388b37738a847bdbc17682](https://github.com/linuxdeepin/developer-center/assets/17869922/3466d51c-c35b-45a9-bc84-11db4da069b4)

**Comment by kobe337** [comment]
验证未通过，验证情况如下：
1、安装器4K屏下显示异常
2、4k下图标过大，部分图标超出选中框背景
3、#4447、优化根分区提示验证通过

【环境】：
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20240301/deepin-23-beige-beta3-amd64-20240301-163825.iso

【结论】：
验证未通过。
