### ISSUE TITLE
【deepin_V23_Release】【一般】【正常】【发散测试】【系统升级工具】软件评估结果的兼容应用中Deepin Launcher应用的图标展示异常

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#7323]
### SUMMARY | 问题概要

必现问题

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
初始镜像：https://cdimage.uniontech.com/community/releases/20.9/
升级镜像：https://cdimage.uniontech.com/community/releases/23-Beta3/
系统升级工具版本：6.0.10
```

### PRE-REQUIREMENT | 预置条件

商店下载系统升级工具

### STEPS TO REPRODUCE | 复现步骤

观察软件评估结果中的兼容应用中Deepin Launcher的图标展示效果

### OBSERVED RESULT | 观察到的结果

Deepin Launcher的图标展示异常

![截图_dde-desktop_20240301133334](https://github.com/linuxdeepin/developer-center/assets/62528742/d5077f0d-6b5e-4299-8c6e-f58811c22d58)

### EXPECTED RESULT | 期望的结果

Deepin Launcher的图标展示正常

**Comment by babyfengfjx** [comment]
@dengbo11  请安排优化~

**Comment by dengbo11** [comment]
@rocet92, 升级工具UI 问题,请优化!

**Comment by FeiWang1119** [comment]
这个图标读取的是desktop文件里面的图标，有些应用没有提供图标。

**Comment by FeiWang1119** [comment]
![image](https://github.com/linuxdeepin/developer-center/assets/102005754/e9110c3d-1228-4c9c-8efa-f5f35611ca46)

**Comment by xuqi27837288** [comment]
应用没有提供图标,导致系统升级工具无法读取到图标,当前版本该场景暂不做修复要求,该问题单先关闭处理
