### ISSUE TITLE
【deepin_V23_Release】【严重】【立即】【发散测试】【系统升级工具】v20.9升级至v23 beta3版本升级失败,提示falled to enable linglong app

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#7324]
### SUMMARY | 问题概要

必现问题

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
初始镜像：https://cdimage.uniontech.com/community/releases/20.9/
升级镜像：https://cdimage.uniontech.com/community/releases/23-Beta3/
系统升级工具版本：6.0.10
```

### PRE-REQUIREMENT | 预置条件

商店下载系统升级工具,使用v23 beta3镜像升级

### STEPS TO REPRODUCE | 复现步骤

观察使用镜像方式升级是否可以正常升级至v23 beta3

### OBSERVED RESULT | 观察到的结果

无法升级成功,提示升级失败,falled to enable linglong app

![截图_选择区域_20240301150207](https://github.com/linuxdeepin/developer-center/assets/62528742/b00103a0-2bed-4fde-8dd3-e24feea622fb)

### EXPECTED RESULT | 期望的结果

可以正常升级成功

**Comment by babyfengfjx** [comment]
@dengbo11  请安排优化~

**Comment by dengbo11** [comment]
@kegechen , @rocet92, 先帮忙定位下,如果定位是玲珑的问题, 可以再指回来

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240201
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
