### ISSUE TITLE
密码输入框不可见时圆点点的尺寸过大，间距太小

### ISSUE THREAD

**Issue by Dora1387** [linuxdeepin/developer-center#7335]
### SUMMARY | 问题概要

系统内密码输入框的密码显示不可见时，圆点点的尺寸过大，点点之间的间距过小

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
1070镜像的版本都是
```

### STEPS TO REPRODUCE | 复现步骤

系统登录界面输入密码；或者保险箱界面创建账户时输入密码；或者文件管理器标题栏更多菜单里面设置共享密码等，可以触发密码输入框的操作

### OBSERVED RESULT | 观察到的结果

![截图_选择区域_20240304105446](https://github.com/linuxdeepin/developer-center/assets/150207945/3c05091a-40df-4af7-9200-f99a3bad63c5)
<img width="692" alt="image" src="https://github.com/linuxdeepin/developer-center/assets/150207945/36421948-bfd9-470d-8bc6-9aa9d0ad8796">
如图，密码输入框的点点图标尺寸比较大

### EXPECTED RESULT | 期望的结果

与设计图一致，缩小圆点点尺寸，增加间距（直径为6px，间距为8px）
<img width="1742" alt="image" src="https://github.com/linuxdeepin/developer-center/assets/150207945/a38a23fc-900a-4fba-9429-8399a457c894">

### ADDITIONAL INFORMATION | 额外补充

@kegechen 有细节问题可以随时与我沟通
```[tasklist]
### Tasks
```

**Comment by Dora1387** [comment]
@kegechen

**Comment by kegechen** [comment]
@FeiWang1119 这个应该在dpasswordedit中可以调整

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240201
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
