### ISSUE TITLE
在Dock栏已经打开的软件图标上滚动鼠标，鼠标失灵，键盘按键可用，部分快捷键（组合键）可用

### ISSUE THREAD

**Issue by hbhgwtf** [linuxdeepin/developer-center#734]
请将下方的缺陷汇报模板中的文字替换为您实际需要汇报的缺陷所对应的描述文字。

## 缺陷描述

在Dock已经打开的软件图标上滚动鼠标，鼠标失灵，键盘按键可用，部分快捷键可用。

## 复现步骤

打开一个软件，例如chrome，然后将鼠标移动到Dock中chrome的图标上用滚轮滚动鼠标，鼠标失灵，键盘按键可用，部分组合键可用（例如Ctrl+Alt+delete可用，Ctrl+D就不可用了），注销或者重启系统后恢复正常。

## 期望行为

能够打开该软件的一个或者多个预览窗口。

## 截图

![image](https://user-images.githubusercontent.com/26326251/49937967-6217f980-ff13-11e8-97ea-9af79843348a.png)

## 复现环境:

当鼠标滚动速度设置为1时，问题不存在，否则复现率为100%.

### 发行版以及版本

Linux Deepin 15.8 桌面版

### 相关的软件包版本

dde-file-manager 4.7.1.8

### 其他内容

无

**Comment by BLumia** [comment]
看上去和 #726 是同一个问题

**Comment by hbhgwtf** [comment]
我看了一下726楼的描述，应该是同样的问题。我在深度论坛也看到了别人反馈同样的问题，但是把鼠标滚动速度设置为1时就没有问题了。

**Comment by BLumia** [comment]
进度也可以在 #726 跟进，下周的更新应该就会附带对这个问题的修复。

**Comment by zccrs** [comment]
> 看上去和 #726 是同一个问题

@mmxzmmxz 测一下

**Comment by mmxzmmxz** [comment]
@hbhgwtf 非常感谢您的复现步骤。下述提交已经修复该问题，外网需稍等更新
https://cr.deepin.io/#/c/deepin-wm/+/40561/

**Comment by mmxzmmxz** [comment]
@zccrs 这个15.8.3没有推送出去？？

**Comment by zccrs** [comment]
> @zccrs 这个15.8.3没有推送出去？？

下一次推动才会包含

**Comment by zccrs** [comment]
@hbhgwtf 1.9.35版本中已修复，本周的推动中会包含，

**Comment by aiamuzz** [comment]
@hbhgwtf  ... its a nasty bug ... my system just froze trying to recreate it ... thankfully the windows effect shortcut was accessible ... switching the windows effect off and then back on ... helped me regain the system control back !!!
