### ISSUE TITLE
Bug : Application Windows operating with the Launcher Menu in the background ... 

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#735]
Hi,

Just installed the latest updates pushed on 15.8 ...

I am seeing that the applications are operational on top of the application drawer ...  ideally the application launcher menu should disappear once we use Alt+Tab to go to an open application window ... but the same isn't happening ...

![deepinscreenshot_dde-launcher_20181214122315](https://user-images.githubusercontent.com/3283676/49988128-b070db00-ff9b-11e8-9645-5053e9212328.png)

![deepinscreenshot_dde-launcher_20181214123510](https://user-images.githubusercontent.com/3283676/49988455-bb783b00-ff9c-11e8-88a7-6a10b0058c80.png)

**Comment by aiamuzz** [comment]
This still happens in 15.11 ...

Is this by design or a bug ?

@keybreak ... do you have this on your setup ?

**Comment by keybreak** [comment]
Yes i have this, and i think it should be the bug in terms of usability

**Comment by aiamuzz** [comment]
> Yes i have this, and i think it should be the bug in terms of usability
@keybreak ... thanks for checking ...

yeah it is kind of obtrusive ... it looks like the launcher is opened as a separate application alongside other application windows ... and with that showing in the background it looks ugly !

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
