### ISSUE TITLE
[Deepin Integration]~[v23-Release] qt6-declarative 6.6.1+dfsg-1deepin4

### ISSUE THREAD

**Issue by UTsweetyfish** [linuxdeepin/developer-center#7354]
### package information | 软件包信息

包名 | 版本
--  | --
qt6-declarative | [6.6.1+dfsg-1deepin4](https://github.com/deepin-community/qt6-declarative/commit/0235748bca17dce2570a7680f77d2be4369ca417)

### Package repository address | 软件包仓库地址

     deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1058/testing/ ./

### test suggestion | 测试建议
bug回归  ：
https://github.com/linuxdeepin/developer-center/issues/7052

**Comment by babyfengfjx** [comment]
@luodeepin  请开展回归验证。

**Comment by UTsweetyfish** [comment]
什么情况？

**Comment by luodeepin** [comment]
问题单验证失败

**Comment by FeiWang1119** [comment]
需要 DTK dtk6clarative的集成，正在集成中。。。
