### ISSUE TITLE
【deepin_V23_Release】【严重】【紧急】【集成测试】【DDE】【控制中心】控制中心升级更新至6.0.45版本后,无deepin ID和网络模块展示

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#7361]
### SUMMARY | 问题概要

必现问题

* https://github.com/linuxdeepin/developer-center/issues/7346

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240201/
```

### PRE-REQUIREMENT | 预置条件

更新升级控制中心至6.0.45版本

### STEPS TO REPRODUCE | 复现步骤

进入控制中心,观察是否有网络和deepin ID模块展示

### OBSERVED RESULT | 观察到的结果

无网络和deepin ID模块展示

![截图_选择区域_20240305140832](https://github.com/linuxdeepin/developer-center/assets/62528742/3e2c582b-4d08-4802-832d-08d63620bca8)

### EXPECTED RESULT | 期望的结果

有网络和deepin ID模块展示

**Comment by babyfengfjx** [comment]
@kegechen  请优先处理。

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240201
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
