### ISSUE TITLE
[Deepin Integration]~[v23-Release] chore: bluez  by zeno

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#7363]
### Package information | 软件包信息

包名 | 版本
--  | --
bluez |  5.69-1deepin3

### Package repository address | 软件包仓库地址

    deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1051/testing/ ./

#### bluez (5.69-1deepin3) unstable; urgency=medium

  * Disable auto enable.

### Test suggestion | 测试建议
系统首次安装时默认设置禁用蓝牙

### Influence | 影响范围
蓝牙

### ADDITIONAL INFORMATION | 额外补充
关联issues  https://github.com/linuxdeepin/developer-center/issues/7243
镜像地址： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240229/deepin-23-beige-beta3-amd64-20240229-140529.iso

**Comment by babyfengfjx** [comment]
@xuqi27837288  请开展回归验证。

**Comment by xuqi27837288** [comment]
【环境】：
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240229
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【结论】：
测试通过，暂无严重问题及影响
