### ISSUE TITLE
How to change website of an app using DTK?

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#738]
Can anyone please tell me how to change website link, website logo and acknowledgement link from an app which is made using DTK?

![DTK](https://i.imgur.com/IJYlNM0.png)

**Comment by hualet** [comment]
@SiamSami try DApplication:: setApplicationHomePage and DApplication::setApplicationAcknowledgementPage

**Comment by SiamSami** [comment]
@hualet "DApplication::setApplicationAcknowledgementPage" works but to open the link I have to click on "Acknowledgements".
I want to change "www.deepin.com" to something else.
Also, I want to change the "deepin" icon to something else as well.

**Comment by hualet** [comment]
@SiamSami OK, then you may should construct your own DAboutDialog and set it with DApplication::setAboutDialog, DAboutDialog has more API to control the appearance, you can use DAboutDialog::setWebsiteName to change "www.deepin.org" to something else, and use DAboutDialog::setWebsiteLink to set the actual address of the website to open. Also, you can use DAboutDialog::setCompanyLogo to change the deepin logo to something else.

**Comment by SiamSami** [comment]
Okay, thanks. Closing this issue.
