### ISSUE TITLE
The sound of emptying the trash is annoying

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#739]
The sound of emptying the trash is very annoying. Can you please remove it?

**Comment by iamhyc** [comment]
There will be switches on every sound effect items in the later release.
https://github.com/linuxdeepin/internal-discussion/issues/546
(Maybe 3-4 weeks later?)

**Comment by SiamSami** [comment]
When will that happen?

**Comment by BLumia** [comment]
We already have that switch now.

**Comment by SiamSami** [comment]
@BLumia  Where is it? I can't find it.
