### ISSUE TITLE
ARM镜像测试

### ISSUE THREAD

**Issue by xzl01** [linuxdeepin/developer-center#7398]
镜像地址： http://10.20.64.70/deepin-ports/cdimage/deepin-23-beige-beta3-arm64-20240306-153105.iso 
已知问题： 应用商店，玲珑暂不支持，鲲鹏920因为固件缺失导致无法进行风扇调速，获取温度。部分飞腾处理器网络无法连接。相机应用暂不支持（需要等待集成）
支持设备: 支持UEFI的主线ARM设置
支持显卡：AMD显卡

### changelog | 更新信息

更新内核为主线5.10内核，添加部分驱动支持

**Comment by babyfengfjx** [comment]
@xuqi27837288  请开展ARM镜像的冒烟测试，可以按照冒烟测试指南进行范围覆盖，所有问题直接提交issue记录即可，部分已知问题可以先创建问题单记录，便于后续跟踪。

**Comment by xuqi27837288** [comment]
测试通过,暂无严重问题待解决修复,已记录的问题单后续有计划可进行沟通修复
