### ISSUE TITLE
org.deepin.gomoku集成

### ISSUE THREAD

**Issue by kamiyadm** [linuxdeepin/developer-center#7405]
### package information | 软件包信息

org.deepin.gomoku | 1.0.11

### Package repository address | 软件包仓库地址

url: http://10.20.64.64:9001/
name: develop-snipe

### test suggestion | 测试建议

修改仓库为测试仓库： ll-cli repo modify http://10.20.64.64:9001/ --name develop-snipe
安装或者更新五子棋： ll-cli install org.deepin.gomoku 观察版本是否为1.0.11
测试基础功能是否正常

**Comment by kamiyadm** [comment]
@Zeno-sole

**Comment by babyfengfjx** [comment]
这个可以直接废弃，跟踪 #7364
