### ISSUE TITLE
鼠标移动到dock的微信（有消息闪烁）图标上，微信消息列表闪现一下又消失

### ISSUE THREAD

**Issue by hbhgwtf** [linuxdeepin/developer-center#741]
请将下方的缺陷汇报模板中的文字替换为您实际需要汇报的缺陷所对应的描述文字。

## 缺陷描述

鼠标移动到dock的微信（有消息闪烁）图标上，微信消息列表闪现一下又消失。

## 复现步骤

将鼠标移动到dock栏的微信（有消息闪烁）图标上，微信消息列表闪现一下又消失。

## GIF图展示

https://github.com/hbhgwtf/test/blob/master/%E6%B7%B1%E5%BA%A6%E5%BD%95%E5%B1%8F_%E9%80%89%E6%8B%A9%E5%8C%BA%E5%9F%9F_20181217124613.gif

## 期望行为

将鼠标移动到dock栏的微信（有消息闪烁）图标上，微信消息列表一直显示，当把鼠标移开后消息列表消失。

## 复现概率

100%

### 发行版以及版本

Linux Deepin 15.8 桌面版

### 相关的软件包版本

dde-file-manager 4.7.1.8

### 其他内容

无

**Comment by hualet** [comment]
@linuxdeepin/wine-team 看看？

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
