### ISSUE TITLE
Feature/Enhancement : Adding a sound notification when the system boots into the login screen<xz1>

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#742]
Hi,

Isn't it a good idea to add a sound notification when the system boots into the login prompt/screen ?

My system takes between 90-120 seconds to boot up to the login screen ... i almost dose off in this period :stuck_out_tongue_closed_eyes:  ...

I could surely use a notification the moment the screen is ready to login ... it would certainly wake me off my nap !!!

**Comment by aiamuzz** [comment]
could a a portion of the desktop login sound work for this login screen sound work ?

[login-screen.wav.zip](https://github.com/linuxdeepin/developer-center/files/2683577/login-screen.wav.zip)

**Comment by wangjia12** [comment]
Thank you for your suggestion, we need to discuss it and make a decision.

**Comment by aiamuzz** [comment]
> could a a portion of the desktop login sound work for this login screen sound ?
> 
> [login-screen.wav.zip](https://github.com/linuxdeepin/developer-center/files/2683577/login-screen.wav.zip)

the sound to use a portion of an existing sound was just to make the best out of what's available ... but if your sound expert can come up with a new sound ... that would be great too ...

**Comment by electricface** [comment]
https://cr.deepin.io/#/c/dde/dde-daemon/+/41877

**Comment by liuwen123** [comment]
已修复

**Comment by aiamuzz** [comment]
@liuwen123 ...

thanks for this feature ... but the boot up sound and the actual login screen are 30 seconds apart ... the sound plays first ...   dark screen or Deepin splash screen and 30 seconds later the login screen shows up ...

**The sound playing 2 secs after the login screen APPEARS will be an experience to cherish ... the current one which is 30 seconds blank/splash screen and then the login screen kind of takes away the joy of this nice feature ... could you please look into this ?**
