### ISSUE TITLE
Suggestion/Enhancement : WIP-Sound effect separate switch ... with the option to replace our own custom sounds ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#743]
I came across your WIP on [Sound effect separate switch](https://github.com/linuxdeepin/developer-center/issues/739) ... 

I was wondering if it was a good idea to provide an ability to replace these default sounds with our own custom sound effects for the same items which are currently being provided with a switch to turn on/off ?

Could be more power to the user ... so he can choose his own sound effects for this OS !!!

**Comment by hualet** [comment]
Maybe not, custom theme is probably OK, but definitely not every single one. 
Closing...

**Comment by aiamuzz** [comment]
> Maybe not, custom theme is probably OK, but definitely not every single one.
> Closing...

oh ... is it too much work to implement it ?

**Comment by hualet** [comment]
> > Maybe not, custom theme is probably OK, but definitely not every single one.
> > Closing...
> 
> oh ... is it too much work to implement it ?

NO, not it's hard or too much work to do, but because I think it distracts DDE.
