### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by saifeiLee** [linuxdeepin/developer-center#7437]
### SUMMARY | 问题概要

```
OCR.ocr(str)
```
调用该接口报错

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin 20.9
pdocr-rpc 2023.12.28
```

### STEPS TO REPRODUCE | 复现步骤

调用OCR.ocr()接口

### OBSERVED RESULT | 观察到的结果

解析错误

### EXPECTED RESULT | 期望的结果

解析正常

### ADDITIONAL INFORMATION | 额外补充

分析原因是在源码中对results的解包有错

**Comment by BLumia** [comment]
抱歉这么久才看到。v20 不会再有更新了。v23 暂时还没这个软件包，如果觉得有必要的话可以深度之家反馈下看看会不会有人有意愿打包维护。
