### ISSUE TITLE
[DDE] Weird overlay on screen corner.

### ISSUE THREAD

**Issue by aksh1618** [linuxdeepin/developer-center#744]
## Describe the bug

I am using DDE on Arch and just now, after a system upgrade, a weird overlay has started appearing on top left corner of the screen, which stays on top of all appications:

## To Reproduce

1. Upgrade to latest DDE.
2. Reboot.
3. See error

## Expected behavior

No overlay.

## Screenshots

![deepinscreenshot_select-area_20181216205028](https://user-images.githubusercontent.com/26065812/50055391-44959a80-0174-11e9-8bf3-494af865d85e.png)
![deepinscreenshot_select-area_20181216204507](https://user-images.githubusercontent.com/26065812/50055392-48292180-0174-11e9-9a1e-eb67689864d3.png)

### Distro & Version

Arch and DDE 15.8 
(Everything latest from Arch stable repos as of the time reporting)

### Related package version

deepin-wm | 1.9.34-1
or
deepin-desktop-base | 2:2018.10.29-1
(Not sure)

### Additional context

I upgraded 2-3 days ago, and rebooted today to find a deepin watermark on the desktop and this weird overlay. Upgraded to make sure to have latest version, which made the watermark go away, but the overlay stayed.

**Comment by BLumia** [comment]
> @BLumia The issue hasn't since occurred. You may close this.

Okay, feel free to reopen it if you got this issue again and got more info about this issue ;)
