### ISSUE TITLE
菜单选中对勾图标过大的问题

### ISSUE THREAD

**Issue by Dora1387** [linuxdeepin/developer-center#7446]
### SUMMARY | 问题概要

右键菜单里面出现的对勾图标尺寸过大

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/daily-iso/1070/professional/daily-stable/20240304-stable/
架构：AMD
专业版1070
```

### STEPS TO REPRODUCE | 复现步骤

桌面触发右键菜单勾选自动排列或者开启桌面整理

### OBSERVED RESULT | 观察到的结果

文字前面的对勾图标太大
![截图_选择区域_20240308131217](https://github.com/linuxdeepin/developer-center/assets/150207945/10ecd6f0-bdd3-4438-98da-8a992c48f50d)

### EXPECTED RESULT | 期望的结果

调整对勾图标尺寸为16*16，并适配分辨率的变化
<img width="355" alt="image" src="https://github.com/linuxdeepin/developer-center/assets/150207945/e76a658c-f27f-473f-b4da-df34475aa443">

### ADDITIONAL INFORMATION | 额外补充

如需切图请与我联系提供，不要改变原来图标的大小和比例

**Comment by Dora1387** [comment]
@kegechen

**Comment by FeiWang1119** [comment]
![image](https://github.com/linuxdeepin/developer-center/assets/102005754/a984be0d-4a94-4d8d-a9b6-aa17273f920f)

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240201
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
【截图录屏】：

![image](https://github.com/linuxdeepin/developer-center/assets/62528742/2ff2806a-bc42-439f-8db7-23265760dea7)
