### ISSUE TITLE
[Deepin Integration]~[v23-Release] dpkg 1.22.5deepin1

### ISSUE THREAD

**Issue by UTsweetyfish** [linuxdeepin/developer-center#7447]
### package information | 软件包信息

包名 | 版本
--  | --
dpkg | [1.22.5deepin1](https://github.com/deepin-community/dpkg/commit/7b97d460be2fe105f998b39c07b0fa61363d9425)

### Package repository address | 软件包仓库地址

    deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1104/testing/ ./

### changelog | 更新信息

https://github.com/deepin-community/dpkg/pull/10

https://github.com/deepin-community/Repository-Integration/pull/1104

**Comment by babyfengfjx** [comment]
@luodeepin  请开展集成验证。

**Comment by luodeepin** [comment]
测试通过
1. 包更新成功
2. dpkg命令正常
