### ISSUE TITLE
Deepin V23 Loongarch版本缺少openssl-1.1依赖

### ISSUE THREAD

**Issue by LichenKassYuan** [linuxdeepin/developer-center#7451]
### SUMMARY | 问题概要

Deepin V23 Loongarch版本缺少openssl-1.1依赖

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
Deepin V23 Loongarch版本
```

### STEPS TO REPRODUCE | 复现步骤

安装openssl-1.1

**Comment by UTsweetyfish** [comment]
> ### SUMMARY | 问题概要
> 
> Deepin V23 Loongarch版本缺少openssl-1.1依赖


Hi, openssl 已经为 3.x，不再支持 1.1

**Comment by kobe337** [comment]
@LichenKassYuan 你好，请确认环境上的openssl版本信息，确认无误后请关闭issues,感谢反馈。
