### ISSUE TITLE
Dependency problems 

### ISSUE THREAD

**Issue by Marea-Icons** [linuxdeepin/developer-center#747]

**Comment by Marea-Icons** [comment]
* Discord depend of libc++1 but this depends on libc++1-7 and libc++abi1-7 not present in deepin repo but they are available in debian SID

* libappindicator1 break pyton-appindicator 

* Curl and your dependence libcurl3 continue to break and prevent installing  packages that require libcurl4

**Comment by hualet** [comment]
Thank you @Marea-Icons

**Comment by KaKi87** [comment]
Is it really necessary to wait for Deepin 15.9 release to fix that ?
I tried adding Depian Jessie stable in sources list, but it didn't worked.
Thanks

**Comment by hualet** [comment]
> Is it really necessary to wait for Deepin 15.9 release to fix that ?
> I tried adding Depian Jessie stable in sources list, but it didn't worked.
> Thanks

that's because we've been busy migrating to debian stable, so I'm not sure @deepinzhangshuang is available for this at the moment.

**Comment by KaKi87** [comment]
Why **un**stable ?

**Comment by KaKi87** [comment]
So, I'm on Deepin 15.9.1 now, I still have the same problem.

**Comment by hualet** [comment]
@deepinzhangshuang

**Comment by martinlindelof** [comment]
Discord install from Deepin Store has broken dependencies.
Discord install from Flatpak worked fine! Until latest update 2020-10-22.
Now Discord freezes UI and requires reboot.

**Comment by Zeno-sole** [comment]
deepin 15 is no longer maintained, please use deepin 20, the new version also has Discord, you can install it from the store
