### ISSUE TITLE
跨端协同windows网址提供的包版本不对

### ISSUE THREAD

**Issue by pppanghu77** [linuxdeepin/developer-center#7471]
### SUMMARY | 问题概要

![file-read-858369](https://github.com/linuxdeepin/developer-center/assets/112470972/c447e025-a319-4833-87ea-bc3eb3b0840e)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
v23
```

### PRE-REQUIREMENT | 预置条件

安装跨端协同

### STEPS TO REPRODUCE | 复现步骤

点击右上角

**Comment by babyfengfjx** [comment]
@vivianxf  请开展验证，通过后请转给吴荣杰进行官网的文件替换。
安装文件请前往smb目录下载：\\10.20.64.70\Share\工具\跨端协同windows

**Comment by vivianxf** [comment]
验证通过:

1.附件中新版本在windows安装成功
2.应用展示正常,功能正常
