### ISSUE TITLE
Self created bookmark crashes dde-file-manager

### ISSUE THREAD

**Issue by theinfinityproject** [linuxdeepin/developer-center#748]
## Describe the bug
A self created bookmark in the dde-file-manager will crash the dde-file-manager when user tries to open the bookmark entry on the left side of the dde-file-manager.

## To Reproduce

1. Open dde-file-manager
2.  Go to home dir of user.
3.  Create a folder. 
4. Then make the folder a bookmark via right-click "add to bookmark"
5. Open the bookmark via left-click on the bookmark on the left side panel "bookmarks"

## Expected behavior

Opening a self-created bookmark via the left side panel section bookmark in dde-file-manager should open the dir not crashing the dde-file-manager

### Distro & Version

Manajoro Deepin Comunity edition 18.0

### Related package version

deepin-file-manager 1:4.7.1.7-2
mesa 18.2.6-1

### Additional context

Console-error-msg after attempt to open a bookmark

2018-12-17, 17:00:08.849 [Warning] [dthememanager.cpp    Dtk::Widget::DThemeManagerPrivate::registerWidget 264] can not load qss with out filename Dtk::Widget::DListView(0x7fa5df660730)
dbus[2458]: arguments to dbus_message_new_method_call() were incorrect, assertion "_dbus_check_is_valid_path (path)" failed in file dbus-message.c line 1366.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped)

**Comment by BLumia** [comment]
Bookmark won't require d-bus to work so the log seems not related to your issue. I can't reproduce your issue.

Normally your bookmark will be stored at `~/.config/deepin/dde-file-manager.json`, could you send this file to here so we can check if you don't mind so we can try to reproduce the bug? Thx.

**Comment by theinfinityproject** [comment]
`
    "BookMark": {
        "Items": [
            {
                "created": "2018-12-03T11:48:12",
                "lastModified": "2018-12-03T11:48:12",
                "locateUrl": "/Datenaustausch",
                "mountPoint": "//192.168.178.35/Multimedia/",
                "name": "Datenaustausch",
                "url": "file:///mnt/server/Datenaustausch"
            },
            {
                "created": "2018-12-03T11:48:15",
                "lastModified": "2018-12-03T11:48:15",
                "locateUrl": "/Download",
                "mountPoint": "//192.168.178.35/Multimedia/",
                "name": "Download",
                "url": "file:///mnt/server/Download"
            },
            {
                "created": "2018-12-03T11:48:18",
                "lastModified": "2018-12-03T11:48:18",
                "locateUrl": "/Dunkelkammer",
                "mountPoint": "//192.168.178.35/Multimedia/",
                "name": "Dunkelkammer",
                "url": "file:///mnt/server/Dunkelkammer"
            },
            {
                "created": "2018-12-03T11:48:24",
                "lastModified": "2018-12-03T11:48:24",
                "locateUrl": "/Filme",
                "mountPoint": "//192.168.178.35/Multimedia/",
                "name": "Filme",
                "url": "file:///mnt/server/Filme"
            },
            {
                "created": "2018-12-03T11:48:30",
                "lastModified": "2018-12-03T11:48:30",
                "locateUrl": "/Backup",
                "mountPoint": "//192.168.178.35/Multimedia/",
                "name": "Backup",
                "url": "file:///mnt/server/Backup"
            },
            {
                "created": "2018-12-03T13:05:32",
                "lastModified": "2018-12-03T13:05:32",
                "locateUrl": "/Musik",
                "mountPoint": "//192.168.178.35/Multimedia/",
                "name": "Musik",
                "url": "file:///mnt/server/Musik"
            },
            {
                "created": "2018-12-04T04:15:28",
                "lastModified": "2018-12-04T04:15:28",
                "locateUrl": "home/lars/Nextcloud/Dokumente/Privat",
                "mountPoint": "device:/dev/mapper/luks-9772fa76-82bc-4ba4-a637-d22bb669ac52",
                "name": "Privat",
                "url": "file:///home/lars/Nextcloud/Dokumente/Privat"
            },
            {
                "created": "2018-12-04T04:15:36",
                "lastModified": "2018-12-04T04:15:36",
                "locateUrl": "home/lars/Nextcloud/Dokumente/Uni",
                "mountPoint": "device:/dev/mapper/luks-9772fa76-82bc-4ba4-a637-d22bb669ac52",
                "name": "Uni",
                "url": "file:///home/lars/Nextcloud/Dokumente/Uni"
            },
            {
                "created": "2018-12-04T04:15:43",
                "lastModified": "2018-12-04T04:15:43",
                "locateUrl": "home/lars/Nextcloud/Dokumente/Uni/Bachelor",
                "mountPoint": "device:/dev/mapper/luks-9772fa76-82bc-4ba4-a637-d22bb669ac52",
                "name": "Bachelor",
                "url": "file:///home/lars/Nextcloud/Dokumente/Uni/Bachelor"
            },
            {
                "created": "2018-12-04T04:15:47",
                "lastModified": "2018-12-04T04:15:47",
                "locateUrl": "home/lars/Nextcloud/Dokumente/Uni/Master",
                "mountPoint": "device:/dev/mapper/luks-9772fa76-82bc-4ba4-a637-d22bb669ac52",
                "name": "Master",
                "url": "file:///home/lars/Nextcloud/Dokumente/Uni/Master"
            },
            {
                "created": "2018-12-04T04:15:54",
                "lastModified": "2018-12-04T04:15:54",
                "locateUrl": "home/lars/Nextcloud/Dokumente/Uni/Master/Master/Geschichte",
                "mountPoint": "device:/dev/mapper/luks-9772fa76-82bc-4ba4-a637-d22bb669ac52",
                "name": "Geschichte",
                "url": "file:///home/lars/Nextcloud/Dokumente/Uni/Master/Master/Geschichte"
            },
            {
                "created": "2018-12-17T16:35:20",
                "lastModified": "2018-12-17T16:35:20",
                "locateUrl": "home/lars/Nextcloud",
                "mountPoint": "device:/dev/mapper/luks-9772fa76-82bc-4ba4-a637-d22bb669ac52",
                "name": "Nextcloud",
                "url": "file:///home/lars/Nextcloud"
            }
        ]
    },
    "GenericAttribute": {
        "ShowedHiddenFiles": true
    },
    "SideBar/ItemOrder": {
        "bookmark": [
            "bookmark:file:///mnt/server/Backup#Backup",
            "bookmark:file:///mnt/server/Datenaustausch#Datenaustausch",
            "bookmark:file:///mnt/server/Download#Download",
            "bookmark:file:///mnt/server/Dunkelkammer#Dunkelkammer",
            "bookmark:file:///mnt/server/Filme#Filme",
            "bookmark:file:///mnt/server/Musik#Musik",
            "bookmark:file:///home/lars/Nextcloud#Nextcloud",
            "bookmark:file:///home/lars/Nextcloud/Dokumente/Privat#Privat",
            "bookmark:file:///home/lars/Nextcloud/Dokumente/Uni#Uni",
            "bookmark:file:///home/lars/Nextcloud/Dokumente/Uni/Bachelor#Bachelor",
            "bookmark:file:///home/lars/Nextcloud/Dokumente/Uni/Master#Master",
            "bookmark:file:///home/lars/Nextcloud/Dokumente/Uni/Master/Master/Geschichte#Geschichte"
        ]
    }
}`

**Comment by theinfinityproject** [comment]
> 
    "BookMark": {
        "Items": [
            {
                "created": "2018-12-03T11:48:12",
                "lastModified": "2018-12-03T11:48:12",
                "locateUrl": "/Datenaustausch",
                "mountPoint": "//192.168.178.35/Multimedia/",
                "name": "Datenaustausch",
                "url": "file:///mnt/server/Datenaustausch"
            },
            {
                "created": "2018-12-03T11:48:15",
                "lastModified": "2018-12-03T11:48:15",
                "locateUrl": "/Download",
                "mountPoint": "//192.168.178.35/Multimedia/",
                "name": "Download",
                "url": "file:///mnt/server/Download"
            },
            {
                "created": "2018-12-03T11:48:18",
                "lastModified": "2018-12-03T11:48:18",
                "locateUrl": "/Dunkelkammer",
                "mountPoint": "//192.168.178.35/Multimedia/",
                "name": "Dunkelkammer",
                "url": "file:///mnt/server/Dunkelkammer"
            },
            {
                "created": "2018-12-03T11:48:24",
                "lastModified": "2018-12-03T11:48:24",
                "locateUrl": "/Filme",
                "mountPoint": "//192.168.178.35/Multimedia/",
                "name": "Filme",
                "url": "file:///mnt/server/Filme"
            },
            {
                "created": "2018-12-03T11:48:30",
                "lastModified": "2018-12-03T11:48:30",
                "locateUrl": "/Backup",
                "mountPoint": "//192.168.178.35/Multimedia/",
                "name": "Backup",
                "url": "file:///mnt/server/Backup"
            },
            {
                "created": "2018-12-03T13:05:32",
                "lastModified": "2018-12-03T13:05:32",
                "locateUrl": "/Musik",
                "mountPoint": "//192.168.178.35/Multimedia/",
                "name": "Musik",
                "url": "file:///mnt/server/Musik"
            },
            {
                "created": "2018-12-04T04:15:28",
                "lastModified": "2018-12-04T04:15:28",
                "locateUrl": "home/lars/Nextcloud/Dokumente/Privat",
                "mountPoint": "device:/dev/mapper/luks-9772fa76-82bc-4ba4-a637-d22bb669ac52",
                "name": "Privat",
                "url": "file:///home/lars/Nextcloud/Dokumente/Privat"
            },
            {
                "created": "2018-12-04T04:15:36",
                "lastModified": "2018-12-04T04:15:36",
                "locateUrl": "home/lars/Nextcloud/Dokumente/Uni",
                "mountPoint": "device:/dev/mapper/luks-9772fa76-82bc-4ba4-a637-d22bb669ac52",
                "name": "Uni",
                "url": "file:///home/lars/Nextcloud/Dokumente/Uni"
            },
            {
                "created": "2018-12-04T04:15:43",
                "lastModified": "2018-12-04T04:15:43",
                "locateUrl": "home/lars/Nextcloud/Dokumente/Uni/Bachelor",
                "mountPoint": "device:/dev/mapper/luks-9772fa76-82bc-4ba4-a637-d22bb669ac52",
                "name": "Bachelor",
                "url": "file:///home/lars/Nextcloud/Dokumente/Uni/Bachelor"
            },
            {
                "created": "2018-12-04T04:15:47",
                "lastModified": "2018-12-04T04:15:47",
                "locateUrl": "home/lars/Nextcloud/Dokumente/Uni/Master",
                "mountPoint": "device:/dev/mapper/luks-9772fa76-82bc-4ba4-a637-d22bb669ac52",
                "name": "Master",
                "url": "file:///home/lars/Nextcloud/Dokumente/Uni/Master"
            },
            {
                "created": "2018-12-04T04:15:54",
                "lastModified": "2018-12-04T04:15:54",
                "locateUrl": "home/lars/Nextcloud/Dokumente/Uni/Master/Master/Geschichte",
                "mountPoint": "device:/dev/mapper/luks-9772fa76-82bc-4ba4-a637-d22bb669ac52",
                "name": "Geschichte",
                "url": "file:///home/lars/Nextcloud/Dokumente/Uni/Master/Master/Geschichte"
            },
            {
                "created": "2018-12-17T16:35:20",
                "lastModified": "2018-12-17T16:35:20",
                "locateUrl": "home/lars/Nextcloud",
                "mountPoint": "device:/dev/mapper/luks-9772fa76-82bc-4ba4-a637-d22bb669ac52",
                "name": "Nextcloud",
                "url": "file:///home/lars/Nextcloud"
            }
        ]
    },
    "GenericAttribute": {
        "ShowedHiddenFiles": true
    },
    "SideBar/ItemOrder": {
        "bookmark": [
            "bookmark:file:///mnt/server/Backup#Backup",
            "bookmark:file:///mnt/server/Datenaustausch#Datenaustausch",
            "bookmark:file:///mnt/server/Download#Download",
            "bookmark:file:///mnt/server/Dunkelkammer#Dunkelkammer",
            "bookmark:file:///mnt/server/Filme#Filme",
            "bookmark:file:///mnt/server/Musik#Musik",
            "bookmark:file:///home/lars/Nextcloud#Nextcloud",
            "bookmark:file:///home/lars/Nextcloud/Dokumente/Privat#Privat",
            "bookmark:file:///home/lars/Nextcloud/Dokumente/Uni#Uni",
            "bookmark:file:///home/lars/Nextcloud/Dokumente/Uni/Bachelor#Bachelor",
            "bookmark:file:///home/lars/Nextcloud/Dokumente/Uni/Master#Master",
            "bookmark:file:///home/lars/Nextcloud/Dokumente/Uni/Master/Master/Geschichte#Geschichte"
        ]
    }
}

**Comment by SiamSami** [comment]
"/Download", "/Backup", "/Fileme" ???
How is that possible?
Have you tried reinstalling dde-file-manager?
Also, before reinstalling it, make sure to remove the `~/.config/deepin/dde-file-manager.json` file

**Comment by theinfinityproject** [comment]
> "/Download", "/Backup", "/Fileme" ???
These ones work. All bookmark referring to "url": "file:///mnt/* work. Interestingly all bookmarks referring to ~/* dont work. I dont understand why bookmarks pointing to my user directory are crashing file manager
> Have you tried reinstalling dde-file-manager?
> Also, before reinstalling it, make sure to remove the `~/.config/deepin/dde-file-manager.json` file

Yes and the problem is still persisting. I reinstalled after removing ~/.config/deepin/dde-file-manager.json

**Comment by yoshwx** [comment]
> > "/Download", "/Backup", "/Fileme" ???
> 
> These ones work. All bookmark referring to "url": "file:///mnt/* work. Interestingly all bookmarks referring to ~/* dont work. I dont understand why bookmarks pointing to my user directory are crashing file manager
> 
> > Have you tried reinstalling dde-file-manager?
> > Also, before reinstalling it, make sure to remove the `~/.config/deepin/dde-file-manager.json` file
> 
> Yes and the problem is still persisting. I reinstalled after removing ~/.config/deepin/dde-file-manager.json

The shortcuts of folders mounted on a LUKS container are inaccessible because Deepin creates an erroneous link to them.
To solve the problem, simply change the mounting point of the configuration file here:
`~/.config/deepin/dde-file-manager.json `

Exemple :
Bookmark generated by the file manager
```
"BookMark": {
        "Items": [
            {
                "created": "2019-05-10T11:37:54",
                "lastModified": "2019-05-10T11:37:54",
                "locateUrl": "home/yosh/Developement",
                "mountPoint": "device:/dev/mapper/vg_main-lv_root",
                "name": "Developement",
                "url": "file:///home/yosh/Developement"
            }
        ]
    },
```
Solution (mount point):
```
"BookMark": {
        "Items": [
            {
                "created": "2019-05-10T11:37:54",
                "lastModified": "2019-05-10T11:37:54",
                "locateUrl": "home/yosh/Developement",
                "mountPoint": "home/yosh/Developement",
                "name": "Developement",
                "url": "file:///home/yosh/Developement"
            }
        ]
    },
```

**Comment by theinfinityproject** [comment]
Thanks for the hint! 
it even works when u only specify `/$HOME/$USER/` So this already did the trick:

`{
                "created": "2019-05-19T16:02:27",
                "lastModified": "2019-05-19T16:02:27",
                "locateUrl": "/lars/Nextcloud/Dokumente/Privat",
                "mountPoint": "/home/lars/",
                "name": "Privat",
                "url": "file:///home/lars/Nextcloud/Dokumente/Privat"
            },`

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
