### ISSUE TITLE
icon keeps on moving even if clicked

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#749]
## Describe the bug
If we open a program from the desktop, then in the dock the program's icon keeps on moving even if it is clicked.

## To Reproduce

1. Open a program from the desktop.
2. After opening, take look at the dock.
3. The icon of the program will be moving.
4. If you click on the icon, the icon should stop moving but it doesn't.

## Expected behavior

The icon should stop moving after it has been clicked.

## Screenshots

![deepin-screen-recorder_desktop_20181218090155](https://user-images.githubusercontent.com/33563064/50129936-7f4b2000-02a5-11e9-84dc-05369cec1e17.gif)

### Distro & Version

Archlinux (Latest)

### Related package version

dde-file-manager version 1.8.2 (1:4.7.1.9-1)
dde-dock version 4.8.4-1

**Comment by hualet** [comment]
Do you mean that you want the shaking animation to stop?

**Comment by SiamSami** [comment]
Looks like it got fixed.....
