### ISSUE TITLE
[archlinux] Desktop wallpaper garbled after resuming from suspend

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/developer-center#75]
<a href="https://github.com/ThornedRose"><img src="https://avatars.githubusercontent.com/u/239386?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @ThornedRose**
_Monday Apr 18, 2016 at 01:36 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/261_

----

![deepinscreenshot20160418120809](https://cloud.githubusercontent.com/assets/239386/14591693/a24513d6-0569-11e6-9d63-c2c2e4488ffb.png)

Fresh installation of Deepin on Arch Linux. The only other DE I have is Open Box.

Wallpaper is the default, no custom wallpapers added. Computer is suspended through the Deepin interface. When computer is resumed from suspend (by a keyboard press), the desktop wallpaper looks as per the screenshot.

The wallpaper can be restored by selecting a different wallpaper (which displays fine) and then reselecting the default wallpaper.

 OS: Arch Linux 
 Kernel: x86_64 Linux 4.5.0-1-ARCH
 Uptime: 4h 20m
 Packages: 1250
 Shell: bash 4.3.42
 Resolution: 1920x1200
 WM: Mutter(DeepinGala)
 WM Theme: Adwaita
 GTK Theme: Numix-Frost-Light [GTK2/3]
 Icon Theme: deepin
 Font: DejaVu Sans 10
 CPU: Intel Core2 Quad CPU Q6600 @ 2.4GHz
 GPU: GeForce GTX 650 Ti
 RAM: 2989MiB / 6979MiB

**Comment by fasheng** [comment]
@sonald Looks not a common problem, at least couldn't reproduce here.
```
deepin-mutter 3.18.2.7-1
deepin-wm 1.0.5-1
```

**Comment by sonald** [comment]
It occurs to me that a [wield patch](http://bazaar.launchpad.net/~gala-dev/gala/trunk/revision/503) from gala I came across weeks ago  may fix this, but I have no env to try.
