### ISSUE TITLE
Bug : Ghost applications showing up on the dock ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#750]
## Describe the bug

*There are some unexplained ghost application icons on the dock ... *

## Expected behavior

*Only applications which have docked or are open and running should show up on the dock*

## Screenshots

*Please find a gif recording enclosed*

![deepin-screen-recorder_select area_20181218184729](https://user-images.githubusercontent.com/3283676/50156832-c6f99800-02f5-11e9-81a2-ecd6170528e8.gif)

### Distro & Version

Linux Deepin 15.8

**Comment by hualet** [comment]
what did you do before all those things showing up? 😂

**Comment by SiamSami** [comment]
Can you tell us how we can reproduce the bug?

**Comment by aiamuzz** [comment]
closing it as i am not encountering of late ...
