### ISSUE TITLE
[Deepin Integration]~[V23-Release] boost 1.83, icu 74

### ISSUE THREAD

**Issue by UTsweetyfish** [linuxdeepin/developer-center#7502]
### package information | 软件包信息

包名 | 版本
--  | --
icu | [74.2-1](https://github.com/deepin-community/icu/commit/9ab48daa6b854010e241e071003002e32b75704e)
boost1.74 | [1.74.0+ds1-23](https://github.com/deepin-community/boost1.74/commit/93b20e30e5c8be7cfd872406be15bcbe835a97c4)
boost1.81 | [1.81.0-6](https://github.com/deepin-community/boost1.81/commit/7807ac0e39b1d3924fad210208d302091d558121)
boost1.83 | [1.83.0-2](https://github.com/deepin-community/boost1.83/commit/e57738e99b07dfe7b82a027942530ecefe08f21b)
boost-defaults | [1.83.0.2](https://github.com/deepin-community/boost-defaults/commit/f5236d7ea0a7c97bd1c354d032e81395cacbd366)
brltty | [6.6-4](https://github.com/deepin-community/brltty/commit/63fa1d2033832df29a231fb469178c707e0490bf)
dee | [1.2.7+17.10.20170616-7](https://github.com/deepin-community/dee/commit/ff09bfd237ddcf931b8d36c4c72705b44ef29f94)
evolution-data-server | [3.50.1-1](https://github.com/deepin-community/evolution-data-server/commit/2cd7098a8c724b928eda455567219bae6f3a678b)
firebird3.0 | [3.0.11.33703.ds4-2](https://github.com/deepin-community/firebird3.0/commit/b14278ad760dbce2ee566e31bce0d9e26a9cc567)
freerdp2 | [2.11.2+dfsg1-1](https://github.com/deepin-community/freerdp2/commit/e480d437dffa33ffd2582dfd9624fd475bdc41f0)
gdb | [13.2-1](https://github.com/deepin-community/gdb/commit/49769e7d84594256d858778b7fecb4a463055bdb)
gnustep-base | [1.29.0-7](https://github.com/deepin-community/gnustep-base/commit/8324adecbc96c2e1e272fb4719c208e0a01a1a44)
gspell | [1.9.1-2](https://github.com/deepin-community/gspell/commit/6062d3bf1fcd9400ae03c4cac136de9a28dbdb08)
harfbuzz | [8.0.1-1](https://github.com/deepin-community/harfbuzz/commit/9b258a83d4f5f50c69843678bbefe45009ba433d)
hfst-ospell | [0.5.3-2](https://github.com/deepin-community/hfst-ospell/commit/acf493e87ad960066d0020fb418c071a3f648239)
libcdr | [0.1.7-1](https://github.com/deepin-community/libcdr/commit/45b6faad0c69e9653a3fd36bc7da6c41708d950f)
libe-book | [0.1.3-3](https://github.com/deepin-community/libe-book/commit/dbbc1a69825883abc948869403bf327b24963f21)
libical3 | [3.0.11-deepin](https://github.com/deepin-community/libical3/commit/180b9566762ebaa7c75aa0d8269165e8e95c0b07)
libmspub | [0.1.4-deepin1](https://github.com/deepin-community/libmspub/commit/f8e879921669636f51784064e1af97b7ded696c8)
libphonenumber | [8.12.16-deepin](https://github.com/deepin-community/libphonenumber/commit/56aabdfc0004986fb26636dbf552cb600b111e94)
libqxp | [0.0.2-deepin1](https://github.com/deepin-community/libqxp/commit/687334c78555d8b1cd13b84a95f2dff387a3e8e3)
librime | [1.7.3.1-deepin](https://github.com/deepin-community/librime/commit/66d060241f741a573a07f660197f2ca31fa54eff)
libvisio | [0.1.7-deepin1](https://github.com/deepin-community/libvisio/commit/5a81e5122ffbb85847f34435605e802cdde7ea9b)
libxml2 | [2.9.14+dfsg-1.3](https://github.com/deepin-community/libxml2/commit/16ef1b902459a06a78716c2711dbae7668dcd307)
libzmf | [0.0.2-deepin1](https://github.com/deepin-community/libzmf/commit/0767da49f097c80efb892ffbae6877f0cbe402dd)
littler | [0.3.14-1](https://github.com/deepin-community/littler/commit/a0871438124493328b93cad6f9b312dfb2a2c8c9)
lucene++ | [3.0.8-deepin1](https://github.com/deepin-community/luceneplusplus/commit/f0fb368389a31c90d440080fc9c1f9a0a55bbd4b)
mongo-c-driver | [1.24.3-1](https://github.com/deepin-community/mongo-c-driver/commit/6b977a14a5294983567a3663953ea2369713f51e)
nodejs | [18.19.1+dfsg-3](https://github.com/deepin-community/nodejs/commit/3d45e6dbee4a430926b5a31637eb0cd50d1fab84)
php7.4 | [7.4.21-2+deb11u1](https://github.com/deepin-community/php7.4/commit/33fb6b3a51ef185c37f2b7e6cd822b08ca398ed5)
postgresql-16 | [16.0-2](https://github.com/deepin-community/postgresql-16/commit/ed30c50c453f8c54c4ca551363347d5d0edb6ceb)
qt6-5compat | [6.6.1-2](https://github.com/deepin-community/qt6-5compat/commit/2f992d2df6cbee83168a0b57a356d3792697bab5)
qt6-base | [6.6.1+dfsg-5deepin2](https://github.com/deepin-community/qt6-base/commit/f694411aa6219bed7c8984bd90aea320b572b18b)
qt6-webengine | [6.6.1+dfsg-2deepin1](https://github.com/deepin-community/qt6-webengine/commit/12a34113017d159dfc0bd56c27ace176461e5b3e)
qtbase-opensource-src | [5.15.8-1+deepin5](https://github.com/deepin-community/qtbase-opensource-src/commit/08e182ee40a654438cc57a308e2966071e746c11)
qtlocation-opensource-src | [5.15.8-2deepin1](https://github.com/deepin-community/qtlocation-opensource-src/commit/977db2ad0fe5549e2ad9dac9e164aa3a8449d535)
qtwebengine-opensource-src | [5.15.15+dfsg-3deepin2](https://github.com/deepin-community/qtwebengine-opensource-src/commit/33d7587cb3d97dc2f3e8447db1329f024302c1f6)
qtwebkit-opensource-src | [5.212.0.4~alpha4+deepin-2](https://github.com/deepin-community/qtwebkit-opensource-src/commit/2b18e0a28a15dfee9d9feaf85323df35975233d7)
raptor2 | [2.0.16-3](https://github.com/deepin-community/raptor2/commit/a940c1caf4a6261bfc000f61229e2dcc77b78949)
r-base | [4.3.1-4](https://github.com/deepin-community/r-base/commit/6df4408f1a4b90c89bbc5f2aa2c676236835b899)
rpy2 | [3.4.5-2](https://github.com/deepin-community/rpy2/commit/f6987cf3b44402c92d6ad32e5b64f798b0a5cfe3)
samba | [2:4.19.3+dfsg-2](https://github.com/deepin-community/samba/commit/a5b669c386f7c60e56e86d9d387270f6b623cc0f)
source-highlight | [3.1.9-deepin2](https://github.com/deepin-community/source-highlight/commit/67eaa8dab7c15efc589c1dc9c5c07e3505abcd91)
tesseract | [5.3.0-2deepin1](https://github.com/deepin-community/tesseract/commit/db2ba166b768aa7b10c5db974965435a0e2144aa)
texlive-bin | [2022.20220321.62855-5](https://github.com/deepin-community/texlive-bin/commit/4b02881e210aa120b56856b4cea2c83f491abce1)
unar | [1.10.7+ds1+really1.10.1-2](https://github.com/deepin-community/unar/commit/5b1d35b72760cd3f3134043615d59c35a80d1245)
vte2.91 | [0.75.0-1](https://github.com/deepin-community/vte2.91/commit/ee78e33bb12f1f83a8ab26840283aaf1fe089567)
webkit2gtk | [2.42.2-1](https://github.com/deepin-community/webkit2gtk/commit/bd3832002166a3e2f525f79e1309c34d2e49cf8c)
wpewebkit | [2.42.2-1](https://github.com/deepin-community/wpewebkit/commit/4a755a2e0a6c69bb3bff8165a14d6c68501f1827)
xalan | [1.12-6](https://github.com/deepin-community/xalan/commit/cae777d92781636e718b4cde22d56422f9b8aac4)
xerces-c | [3.2.3.1-deepin](https://github.com/deepin-community/xerces-c/commit/4f2d8da1b1c0ad91c2f3f059693e21111c30c155)
xfsprogs | [5.16.0.1-deepin](https://github.com/deepin-community/xfsprogs/commit/6990eb54038986db57d3b6d2a96b7ae2ee51df19)
recode | [3.6-25](https://github.com/deepin-community/recode/commit/8ce25a1792563e188ade617c24bbb764aadc3e9d)
aptitude | [0.8.13.1-5deepin](https://github.com/deepin-community/aptitude/commit/3d82456027e811c100441c380070b67a14e7e12d)
cryfs | [0.11.4-1](https://github.com/deepin-community/cryfs/commit/6142450c64e5d4f846c96f43d3214dabc1688340)
fcitx5-chinese-addons | [5.1.2-1](https://github.com/deepin-community/fcitx5-chinese-addons/commit/99fb380dcae1c635cb615eca88160c49b12db1aa)
galera-4 | [26.4.16-2](https://github.com/deepin-community/galera-4/commit/aa02590838d3d5512fea19e396b1b89b295dc3dc)
imath | [3.1.9-3](https://github.com/deepin-community/imath/commit/fee953cab4c6e66dcb4896f5eb7b96fc39d162fb)
inkscape | [1.2.2-2](https://github.com/deepin-community/inkscape/commit/9efe6a39f818871970b338156dc6aa0f3b2ff1b9)
ismrmrd | [1.8.0-2](https://github.com/deepin-community/ismrmrd/commit/15f3c0c3a1527296bcaa1b7c63dcd11f1cdff476)
kig | [4:21.08.0-1](https://github.com/deepin-community/kig/commit/028959cd319880b5188a2bcfe94c28ccc771759c)
libappimage | [1.0.4-5-3](https://github.com/deepin-community/libappimage/commit/23c742fa7d5c0e9f9a8aff8474cdfc60c0be8da2)
libcmis | [0.6.2-2](https://github.com/deepin-community/libcmis/commit/beb3cf97483799127782233b6d2194a50f94843a)
libime | [1.1.3-1](https://github.com/deepin-community/libime/commit/0145db897bf39480ebfcefdbff19bea56bd293a3)
liborcus | [0.19.2-3](https://github.com/deepin-community/liborcus/commit/0d49192e2a5a218f036951d7d6d21698e70b1b46)
schroedinger-maeparser | [1.2.4-deepin1](https://github.com/deepin-community/schroedinger-maeparser/commit/f5956d1a90ad6d6c9a320dba7d4abf851728a050)
galera-3 | [25.3.34-1](https://github.com/deepin-community/galera-3/commit/007ed413146a4127c1800d89833436e12c4fe35d)
schroot | [1.6.13-3](https://github.com/deepin-community/schroot/commit/76676e7f7379344567fbfc11b37c46c8d5222e87)
lib2geom | [1.2.2-3](https://github.com/deepin-community/lib2geom/commit/6df7a52ababb06e285b2e16a03e4a8509eb9e724)
ceph | [18.2.1+ds-1deepin1](https://github.com/deepin-community/ceph/commit/c594c95601a5855b7f8171c6ab343739f86f6214)
thrift | [0.19.0-2deepin1](https://github.com/deepin-community/thrift/commit/a5da985bdadadb56f0e242e75cf1025add1889b9)
jaraco.classes | [3.2.1-4](https://github.com/deepin-community/jaraco.classes/commit/0353b7541aa1b5c339709890d4111edbde2e75eb)
python-tz | [2024.1-2](https://github.com/deepin-community/python-tz/commit/839876f9851353125cb0029ce26c8e4cea1e4034)
python-tempora | [5.5.0-1](https://github.com/deepin-community/python-tempora/commit/4166b55610d87bd2184e8e0c932bfbebf114e4c1)
openmpi | [4.1.6-5](https://github.com/deepin-community/openmpi/commit/47f137863f4363ba2515b11b5c9bd8e5383a103b)
dde-control-center | [6.0.45](https://github.com/linuxdeepin/dde-control-center/commit/790546f9cd9a797b7e63ab47b0e839f58d17493c)
dde-file-manager | [6.0.41](https://github.com/linuxdeepin/dde-file-manager/commit/3f6ae0ed4bcec54fc67ea3739eb76a5040ccef65)
dde-grand-search | [5.4.5](https://github.com/linuxdeepin/dde-grand-search/commit/af9d33f33b8a07833de029d7c0a117f877031b47)
deepin-editor | [6.0.16](https://github.com/linuxdeepin/deepin-editor/commit/6c7ece5030d3603e8db8696b0e16dad768d4141b)
deepin-log-viewer | [6.1.13](https://github.com/linuxdeepin/deepin-log-viewer/commit/4cd6b8a423e6b17ead37d7d3bf05744d3b9949de)
deepin-music | [6.2.39](https://github.com/linuxdeepin/deepin-music/commit/96aa815c40c0a52b122e4efcd6eead472285e581)
deepin-pdfium | [1.0.2](https://github.com/linuxdeepin/deepin-pdfium/commit/3abb57fb3ee24b55819b69db3588294ce323d1f7)
deepin-system-monitor | [6.0.15](https://github.com/linuxdeepin/deepin-system-monitor/commit/e578a249f170959ecbde8ac055d0f20bdd7813fe)

### Package repository address | 软件包仓库地址

    deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1046/testing/ ./
    deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1046:/dde/testing/ ./
    deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1046:/community/testing/ ./

### changelog | 更新信息

更新boost默认至1.83
更新icu至74
并大量rebuild

### test suggestion | 测试建议
系统底层库更新，着重验证升级场景，可能存在依赖更新到时第三方应用无法使用(应用商店软件)

_No response_

**Comment by babyfengfjx** [comment]
@kobe337  请开展集成验证，并给其他同学下发同步验证任务，每个人都需要完成此次升级验证，确保其他功能均无影响，最好升级前做好系统备份，以便形成对比，方便问题定位。

**Comment by UTsweetyfish** [comment]
dde 组件：

- dde-control-center
- dde-file-manager
- dde-grand-search
- deepin-editor
- deepin-log-viewer
- deepin-music
- deepin-pdfium
- deepin-system-monitor

建议关注

**Comment by UTsweetyfish** [comment]
已经处理完了，目前已知风险：
1. dde-control-center 6.0.46 在 #7512 中集成，集成后可能需要再次 rebuild
2. LibreOffice 仍依赖 icu73
3. 应用商店

**Comment by kobe337** [comment]
libboost-chrono库验证通过
1、libboost-chrono库验证，打开控制中心-查看日期时间是否正确。
2、命令行查看追踪日志，时间是否正确
3、查看更新后的集成版本，版本核对
以上内容验证通过。

Boost.Chrono，这个组件专门用于处理时间和日期的操作。
![libboost-chrono](https://github.com/linuxdeepin/developer-center/assets/17869922/ac74c12f-974d-40c3-b79f-d1aeb9e7f5df)

**Comment by kobe337** [comment]
libboost-filesystem验证通过
1、查看更新后的集成版本，版本核对
2、环境变量正常，编译与运行正常
3、使用libboost-filesystem创建目录，删除目录
4、打开文管，对文管进行日常使用操作，切换目录、复制文件，重命名目录与文件等
以上场景验证通过
Boost.Filesystem是Boost库的一个重要组件，专门用于文件系统操作，如创建、读取、写入和删除文件或目录。
![libboost-filesystem](https://github.com/linuxdeepin/developer-center/assets/17869922/a393e64d-5d86-4d92-afd5-b14080a43e44)

**Comment by kobe337** [comment]
libboost-exception验证通过
1、查看更新后的集成版本，版本核对
2、环境变量正常，编译与运行正常
3、构建错误场景，验证编译运行结果，提示了详细的报错信息
libboost-exception是Boost库中的一个模块，用于处理C++中的异常处理。
![libboost-exception](https://github.com/linuxdeepin/developer-center/assets/17869922/da9e842d-658c-4857-ab84-bb51f1262b0e)

**Comment by kobe337** [comment]
1、查看更新后的版本，版本核对
2、查看并打开一下应用，正常使用应用，查看应用文字显示
dde-control-center
dde-file-manager
dde-grand-search
deepin-editor
deepin-log-viewer
deepin-music
deepin-pdfium
deepin-system-monitor
以上场景验证通过

libicu为软件应用提供了一系列支持Unicode和全球化的功能，确保跨平台、跨语言的一致性
![icu](https://github.com/linuxdeepin/developer-center/assets/17869922/7023f646-cba9-4f16-8525-bfa684ea3c00)

**Comment by UTsweetyfish** [comment]
dde-control-center 升级至 6.0.47，复测 #7171
原集成 #7512

**Comment by xuqi27837288** [comment]
复测测试通过 * https://github.com/linuxdeepin/developer-center/issues/7171

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Beta3/
仓库：提测仓库
内核：Linux deepinb3-PC 6.1.32-amd64-desktop-hwe #23.01.00.20 SMP PREEMPT_DYNAMIC Thu Jan 11 18:45:10 CST 2024 x86_64 GNU/Linux

【结论】：
测试通过，暂无严重问题及影响
