### ISSUE TITLE
.desktop application open with in all file types in dde-file-manager

### ISSUE THREAD

**Issue by alexandre1985** [linuxdeepin/developer-center#751]
I'm using Manjaro Linux Deepin and this feature request is related to Deepin File Manager (dde-file-manager).
I'm able to contribute to the code, but before I do that I may need some consensus in the type of feature I'm about to add.
## New feature type
I have a .desktop file, and I want it to be able to execute on any given file, inside the file manager menu with a right-click.

## Place for it (inside the Deepin File Manager)
So I believe that the better way for this to be added, would be on the "open with" menu.

## Implementation
- To implement this it could be done with a personalized mimetype (for example, `MimeType=all/all;`) and then the File Manager could interpret it, and if find this, could add the .desktop launcher to all filetypes in the the "open with".
- Another way would be, creating a configuration file that could be read, and would have all the .desktop file paths that we wish to be able to be added to any filetype "open with" menu.

I need some discussion and feedback on this issue before I (or someone) start implementing a patch.

**Comment by BLumia** [comment]
Probably `application/octet-stream` is a better choice? 

ref: [Development/Tutorials/Creating Konqueror Service Menus, The Start of Servicemenu, Tips section](https://techbase.kde.org/Development/Tutorials/Creating_Konqueror_Service_Menus#The_Start_of_Servicemenu)

**Comment by alexandre1985** [comment]
if I put the mimetype `application/octet-stream` it is applying for binary files, but for other files the .desktop app isn't being applied.
Don't know if it only applies to binary files or if the file can only have one mimetype, rejecting this configuration

**Comment by alexandre1985** [comment]
Deepin File Manager isn't delivering the .desktop app with `MimeType=application/octet-stream;` to all files. Maybe that is a kde thing only @BLumia.
Don't know if other GNOME file managers recognizes and applies this mimetype for all files.

**Comment by BLumia** [comment]
> Deepin File Manager isn't delivering the .desktop app with MimeType=application/octet-stream; to all files.

:joy: Ah I forgot it! For current implementation, dde-file-manager will check the file's parent MimeType only if we can't find any matched apps according to the file's MimeType. Related code about finding recommend apps: [`MimesAppsManager::getRecommendedAppsByQio()`](https://github.com/linuxdeepin/dde-file-manager/blob/4.7.1.9/dde-file-manager-lib/shutil/mimesappsmanager.cpp#L464). (simply remove the `if (!recommendApps.isEmpty()) break;` will remove this limit)

As you can see, there is also a `getRecommendedAppsByGio()` here and it calls `g_app_info_get_recommended_for_type()` which Nautilus use, and we found it's not very good in some case so we implement it my ourselves. It can be a bug or an implementation decision thing for GTK.

I asked @zccrs about the current implementation, and the reason why only check parent MimeType if we can't find any matched apps for current MimeType is he worry about the parent MimeType may fill out the recommend apps list with too many matched items. But we haven't tested it so maybe it won't be as bad as that. So we need to discuss about it.

btw, supporting wildcard match will be great too imo ;)

**Comment by alexandre1985** [comment]
My opinion is that removing this limit would be good, if it doesnt give the unwanted result that initially you were preventing.
I think it would solve my problem, dont know, need to test it.

**Comment by alexandre1985** [comment]
I was reading your comment more carefully and I didnt have a grasp of parent mimetype. For what I have read mimetypes are organized into a hierarchy, so one mimetype can have several parent mimetypes.
If this is true I believe that the check made by @zccrs is correct and should be maintained.
What could be done in that check is give an exception to the mimetype `all/all` and any .desktop file that had this mimetype would also be processed.
This mimetype would have to be added to the OS by the user.

**Comment by BLumia** [comment]
> I dont know what you mean by wildcard matching 

Oh I means something like `application/*` or `*/*`, seems valid for the desktop file standard ("any" seems not).

> mimetypes are organized into a hierarchy, so one mimetype can have several parent mimetypes.

Yeah so `application/octet-stream` should be the common base type of all mimetype (for files). So we can use this mimetype to match any file if that's true.

You can remove that check mentions above, compile and try it locally. If that works well, welcome to submit a patch ;)

**Comment by BLumia** [comment]
You'd better query the package version from your distro via the package manager, in your case, use pacman. Try `pacman -Q --info dde-file-manager` (not sure but if the package name is not `dde-file-manager`, replace the name with the actual package name here).

I can't find an online Manjaro package browser / tracker so sorry I'm not sure about which tag version they are using :/

**Comment by alexandre1985** [comment]
I got it compiling. In Manjaro the package name is `deepin-file-manager` ;) . I believe it wont happen any compiling errors now. I want to install the file manager into a different folder (then `/usr/bin`). How can I do that?
Sorry for the newbie questions :beginner:

**Comment by alexandre1985** [comment]
Well... I got a compiling error:
```
/home/daniel/dev/opensource/dde-file-manager/dde-file-manager/translate_ts2desktop.sh: line 7: /usr/bin/deepin-desktop-ts-convert: No such file or directory
mv: impossível analisar 'dde-file-manager.desktop.tmp': No such file or directory
Project ERROR: Failed to generate translation
make: *** [Makefile:53: sub-dde-file-manager-make_first] Error 3
```

**Comment by alexandre1985** [comment]
Ok, I compiled it successfully (needed the `deepin-gettext-tools`).
Now I need to know after doing  `make` how do I install in directory `/home/me/test_install`?

**Comment by BLumia** [comment]
Assume you are using QtCreator, Make sure you are running "dde-file-manager" rather than "dde-desktop". If you wish to run dde-desktop, you need exit the current running dde-desktop process first :)

**Comment by alexandre1985** [comment]
I changed the name of the app to dde-desktop that's why it is saying that about dde-desktop, it's my compiled source code of deepin file manager. Don't know if dde-desktop is a name for another app. May I should change my compiled source app name to dde-file-manager.
I will do that tomorrow

**Comment by BLumia** [comment]
Maybe the current running instance called `deepin-desktop` in manjaro, I'm not sure about that. The desktop process will register a D-Bus connection so if one `dde-desktop`(whatever the name it is) instance is already running, you'll not get another one running.

**Comment by alexandre1985** [comment]
I still get this error. Even when I do a pkill.
Maybe you could test this feature without my help

**Comment by BLumia** [comment]
The daemon will try to restart the desktop program so you should move your installed deepin-desktop to another place to avoid auto restart. fyi you don't need to run deepin-desktop to test this, only run the file manager is okay, and you don't need to install it to someplace to test it btw. Run the file manager from QtCreator directly will works.

Simply comment / remove the `if (!recommendApps.isEmpty()) break;` as I mentioned above should works. Will test it on my side later, quite busy atm, sorry about that.

**Comment by alexandre1985** [comment]
In QtCreator, I couldn't get to run the app. Here is a screenshot of the errors:
![deepinscreenshot_20181228193125](https://user-images.githubusercontent.com/5586308/50526033-4433c280-0ad7-11e9-91a4-14da9612ff68.png)
I believe developing for this project is too bound too deepin OS, not Manjaro. Don't know...
Maybe it could be you doing this test. It shouldn't take long.

**Comment by BLumia** [comment]
:joy: Did you get the correct tag version from your distro? for example, if they are using tag 4.7.1.7, you should do a `git checkout 4.7.1.7 -b new-branch-name-here` first. 

Yeah I can do :joy: I'll do it later since I'm really very busy and this issue priority is not very high.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
