### ISSUE TITLE
【deepin_V23_Release】【严重】【立即】【内测反馈】【系统】设备为UEFI引导且执行sudo update-grub，再重启时直接进入BIOS

### ISSUE THREAD

**Issue by kobe337** [linuxdeepin/developer-center#7523]
**用户反馈链接：https://cooperation.uniontech.com/public/record/65f79e133d37f72615c603ed 记录：V23最新内测，如果是UEFI引导且执行sudo update-grub，再重启直接进BIOS**
### SUMMARY | 问题概要

设备为UEFI引导且执行sudo update-grub，再重启时直接进入BIOS

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Beta3/deepin-desktop-community-23-Beta3-amd64.iso
```

### STEPS TO REPRODUCE | 复现步骤

 1. 加入内测通道后更新内测，重启，然后在终端执行sudo update-grub，再次重启系统

### OBSERVED RESULT | 观察到的结果

发现直接进入BIOS界面

### EXPECTED RESULT | 期望的结果

正常进入桌面环境

**Comment by babyfengfjx** [comment]
@UTsweetyfish  请帮忙紧急分析处理~

**Comment by kobe337** [comment]
论坛反馈链接：https://bbs.deepin.org.cn/post/269519?offset=1&limit=20#comment

**Comment by UTsweetyfish** [comment]
2.04 / 2.06 不支持 fwsetup --is-supported，先把 30_uefi-firmware 里面先撤掉把

**Comment by UTsweetyfish** [comment]
```
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1139/testing/ ./
```

**Comment by UTsweetyfish** [comment]
> ```
> deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1139/testing/ ./
> ```

等待构建完成

**Comment by UTsweetyfish** [comment]
这个之前解决了，没回归

**Comment by kobe337** [comment]
验证通过
【环境】：
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240423/
内核：Linux deepin-PC 6.6.25-amd64-desktop-hwe #23.01.00.25 SMP PREEMPT_DYNAMIC Wed Apr 10 21:20:25 CST 2024 x86_64 GNU/Linux
【结论】：
测试通过，暂无严重问题及影响
1.重启后，查看环境上的grub文件，并执行命令“sudo update-grub”，重启观察进入桌面
2.重启后，在grub界面按C，进入命令行，并检查GRUB命令行功能，如“ls”、“set”等
3.切换高级选项，esc切换会上一级
