### ISSUE TITLE
Deepin tool kit's stylesheet?

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#753]
I think it would be great if you people could make a Qt stylesheet which looks like Deepin Tool Kit.

**Comment by hualet** [comment]
Sorry, but I don't think it's gonna happen, because styles of some widgets in DTK can not be easily done with QSS, that's why we introduced a [style plugin](https://github.com/linuxdeepin/qt5integration/tree/master/dstyleplugin).
