### ISSUE TITLE
【deepin_V23_beta3】【一般】【正常】【发散测试】【深度之家】新建管理员或标准用户登录系统后,桌面出现Deepin Home Daemon多余图标

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#7538]
### SUMMARY | 问题概要

必现问题

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240201

深度之家:1.5.6
```

### PRE-REQUIREMENT | 预置条件

新建管理员或标准用户

### STEPS TO REPRODUCE | 复现步骤

注销切换至新建账户进入系统,观察桌面的图标展示效果

### OBSERVED RESULT | 观察到的结果

桌面出现Deepin Home Daemon多余图标

![截图_选择区域_20240318155720](https://github.com/linuxdeepin/developer-center/assets/62528742/2ec13f84-47a8-49b2-8bdd-9c6f3f5968f6)

### EXPECTED RESULT | 期望的结果

桌面无Deepin Home Daemon图标展示

**Comment by babyfengfjx** [comment]
@myml  请帮忙分析。

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240201
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
【截图录屏】：
