### ISSUE TITLE
Deepin appstore old applications

### ISSUE THREAD

**Issue by activatorr** [linuxdeepin/developer-center#754]
## Describe the bug

In deepin App Store many applications have VERY old versions, some packages not present in and updates software does from terminal.

## To Reproduce

Update applications from store, maybe create updater of applications and installer additions (for example for yandex browser (maybe chrome too) chromium-codecs-ffmpeg-extra and pepperflashplugin-nonfree).

1. Go to App Store
2. Click on App
3. Scroll down to version
4. See version of application - it old

## Expected behavior

Fresh software and clever structure of Deepin Appstore.

## Screenshots
For example: Telegram desktop

https://postimg.cc/gallery/226y50yp4/ (In store it version 1.2.17 but in oficial site and flatpak it 1.5.2)

## Enviroments:
DDE
### Distro & Version

Linux Deepin 15.8

### Related package version

There is some ehat i see without updates
telegram-desktop
teamviewer
yandex-browser-beta
etc.
### Additional context

I dont want use third-party programs to install fresh versions of software, please make in App Store fresh software, auto-updates from store (because i install yandex browser from store, and it outdated, i download fresh deb from official download page deb packer and install, but it adds source to update browser and it updates manualy from terminal, this situation and with teamviewer, install from site deb packet, it makes source in apt and updates manualy from terminal ("sudo apt update && sudo apt upgrade), people who have no ability to learn linux (elderly for example) needs to do all without console. And while i install browser i need to install from terminal pepperflashplugin-nonfree and download from site chromium-codecs-ffmpeg-extra, may it be do direct from App Store?

**Comment by alexwender1** [comment]
I hope Deepin Loja can pull the .flatpak and .snap packages.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
