### ISSUE TITLE
update kernel 6.6.21

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#7540]
### package information | 软件包信息

包名|版本
--|--
linux-headers-6.6.21-amd64-desktop-hwe | 23.01.00.23
linux-image-6.6.21-amd64-desktop-hwe |23.01.00.23
linux-firmware | 1.202.16

### Package repository address | 软件包仓库地址

deb [trusted=yes] https://ci.deepin.com/repo/deepin/deepin-community/obs-repos/ kernel main
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/deepin-community:/linux-deepin-hwe:/PR-6/deepin_develop/ ./

### changelog | 更新信息

 Kernel 6.6.21 重要更新包括：
xxxxx

### Test suggestion | 测试建议
镜像地址:  https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240319/
更新固件以及6.6.21版本内核
fix https://github.com/deepin-community/kernel/issues/90 https://github.com/deepin-community/kernel/issues/92 

### Sphere of influence | 影响范围

硬件外设、系统稳定性等

### ADDITIONAL INFORMATION | 额外补充

6.6内核作为release选项版本，计划预装到release镜像中，请发散各种应用场景验证

**Comment by babyfengfjx** [comment]
@xuqi27837288  请使用该内核进行至少为期半月的测试验证，通知其他同学同步更新内核，采用上文提供的镜像文件，在beta3遗留小新笔记本无法安装的问题进行复测验证。

**Comment by xuqi27837288** [comment]
【环境】：
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240201
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【结论】：
测试通过，暂无严重问题及影响，已测试多个机器的安装和升级场景~
