### ISSUE TITLE
Cannot open access to console, root account is locked

### ISSUE THREAD

**Issue by newtonmunene99** [linuxdeepin/developer-center#755]
## Describe the bug

When I boot up the system I get an error stating 

> Cannot open access to console, root account is locked

![image](https://user-images.githubusercontent.com/29271333/50396331-80cf8900-077a-11e9-947f-8f6cdebe3ac4.png)

When I press enter, the system continues with the boot process normally. After signing in sometimes it just loads forever without showing the desktop and sometimes it shows the desktop and some apps work fine but deepin apps don't work at all. Apps like the launcher, control center etc. I also can't right click on docked applications.

I tried running from the terminal to see if i get any errors. What I get is

`"dtkwidget2" can not find qm files
"dde-launcher" can not find qm files
2018-12-24, 12:52:23.653 [Debug  ] [dapplication.cpp     Dtk::Widget::DApplicationPrivate::setSingleInstanceByDbus 203] register service failed: QDBusError("", "")
`

![image](https://user-images.githubusercontent.com/29271333/50396653-5e3e6f80-077c-11e9-9e27-af8ccfac6a96.png)

## To Reproduce

I really don't know how to reproduce. Just Boot up the system,I guess.

## Expected behavior

System should boot up normally and apps should also open normally.

## Screenshots

![image](https://user-images.githubusercontent.com/29271333/50396744-d9078a80-077c-11e9-9b3a-084c7f6dfe83.png)

![deepinscreenshot_select-area_20181224130219](https://user-images.githubusercontent.com/29271333/50396732-ca20d800-077c-11e9-86a9-15e8a23c01cd.png)

### Distro & Version

Linux Deepin 15.8

### Related package version

All versions

### Additional context

I only installed deepin os two days ago. My system is already the latest stable version.

**Comment by hualet** [comment]
After entering the system, do what it suggested, run `journalctl -xb` to see if there' any clone in the system log.

**Comment by newtonmunene99** [comment]
Here is what i get after running `journallctl -xb`
![image](https://user-images.githubusercontent.com/29271333/50437654-bbacfa80-08fb-11e9-8a8b-77b92a1240b9.png)


This goes on for like thousands of lines.

**Comment by hualet** [comment]
> Here is what i get after running `journallctl -xb`
> 
> ![image](https://user-images.githubusercontent.com/29271333/50437715-04fd4a00-08fc-11e9-8aa8-10dc34254f7d.png)
> 
> This goes on for like thousands of lines.

that's just not enough, I think maybe you need to prepend `sudo` before the command I provided.

**Comment by newtonmunene99** [comment]
Ran it again with `sudo`.
Got the same output, but I scrolled all the way to the end this time,took me almost 15 minutes just holding down the button. It seems to iterate over the following.

![deepinscreenshot_konsole_20181226132444](https://user-images.githubusercontent.com/29271333/50443022-7f38c900-0912-11e9-9a78-4732f17e3860.png)
![deepinscreenshot_konsole_20181226132539](https://user-images.githubusercontent.com/29271333/50443023-7f38c900-0912-11e9-9212-456afa773919.png)
![deepinscreenshot_konsole_20181226132602](https://user-images.githubusercontent.com/29271333/50443026-7fd15f80-0912-11e9-8d61-04cb539e9881.png)

**Comment by hualet** [comment]
what if you remove apparmor?

**Comment by newtonmunene99** [comment]
Did that. Still the same

**Comment by hualet** [comment]
Do you have a file named boot.log in `/var/log/`? if yes please attach the file, so I can see your boot process logs. Otherwise please install `rsyslog` and reboot, and see if the file exists.

**Comment by newtonmunene99** [comment]
Here is boot.log


[boot.log](https://github.com/linuxdeepin/developer-center/files/2714550/boot.log)

**Comment by hualet** [comment]
@newtonmunene99  Please try this https://github.com/linuxdeepin/developer-center/issues/440#issuecomment-441185408

**Comment by newtonmunene99** [comment]
That didn't do it. I actually think that made it worse. Before that I had like maybe 60 % chance of my system booting up and logging in successfully. Now it just shows the loading icon forever after logging in.

**Comment by newtonmunene99** [comment]
Btw the thing where it boots up to emergency mode is now gone. Now it boots up normally to the login screen but after login it just shows the loading cursor forever

**Comment by hualet** [comment]
> Btw the thing where it boots up to emergency mode is now gone. Now it boots up normally to the login screen but after login it just shows the loading cursor forever

Oh, NO, that's totally another thing.
run `journalctl /usr/bin/startdde -b 0` and give me the output plz.

**Comment by newtonmunene99** [comment]
![image](https://user-images.githubusercontent.com/29271333/50515134-e772e080-0ab3-11e9-9877-d01b409e4130.png)

That's the output.

Also found a trick(I guess i'd call it that), not relevant but i thought I should just say it. I have Kodi installed and since it can run as an independent Desktop Environment I opened Kodi then logged out. Then when I logged backed in using Deepin DE everything works fine.

**Comment by hualet** [comment]
> ![image](https://user-images.githubusercontent.com/29271333/50515134-e772e080-0ab3-11e9-9877-d01b409e4130.png)
> 
> That's the output.
> 
> Also found a trick(I guess i'd call it that), not relevant but i thought I should just say it. I have Kodi installed and since it can run as an independent Desktop Environment I opened Kodi then logged out. Then when I logged backed in using Deepin DE everything works fine.

In the screenshot, it seems all components are running correctly...

**Comment by newtonmunene99** [comment]
Like I said, I used the Kodi trick that I mentioned and then everything was working fine. If I reboot normally it will still get stuck after the login and then I'll have no way of running commands since 'emergency mode' is also gone. Best I could do is go into recovery mode and try accessing a terminal from there

**Comment by newtonmunene99** [comment]
HUH, I did that and the output was the same. Tried rebooting at least five times and the issue seems to be gone. My system now boots up and logs in correctly. I'm not sure what exactly fixed it

**Comment by hualet** [comment]
I think what I've suggested did have some good effect, closing for now.
