### ISSUE TITLE
输入框里提示字颜色太深的问题

### ISSUE THREAD

**Issue by Dora1387** [linuxdeepin/developer-center#7554]
### SUMMARY | 问题概要

目前输入框里的提示字颜色比较深，与正常输入文字差别不大，层级不明显

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
1070镜像，专业版
```

### STEPS TO REPRODUCE | 复现步骤

如，打开控制中心账户--创建账户

### OBSERVED RESULT | 观察到的结果

![截图_dde-control-center_20240320110057](https://github.com/linuxdeepin/developer-center/assets/150207945/2c555b77-23ed-4d76-a61e-20eb2f2f7cb3)
输入框里的提示字“必填”、“选填”等，颜色太重

### EXPECTED RESULT | 期望的结果

调整输入框提示字颜色，减淡效果，颜色为#555555，不透明度为40%
<img width="461" alt="image" src="https://github.com/linuxdeepin/developer-center/assets/150207945/64f1114c-1544-4fbd-adcf-1c100953a4db">

```[tasklist]
### Tasks
```

**Comment by Dora1387** [comment]
@kegechen 可哥，帮忙看一下~

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240201
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.32-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
【截图录屏】：

![image](https://github.com/linuxdeepin/developer-center/assets/62528742/cc2995cf-5a22-4cd1-9481-137abdeb6b84)
