### ISSUE TITLE
龙架构Deepin V23深度之家无法登录

### ISSUE THREAD

**Issue by LichenKassYuan** [linuxdeepin/developer-center#7555]
### SUMMARY | 问题概要

Deepin V23 LoongArch版本深度之家无法登陆，点击登录帐号没有反应

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
深度之家版本：1.5.6
系统版本：DeepinV23 Beta3
系统镜像地址：https://ci.deepin.com/repo/deepin/deepin-ports/cdimage/deepin-23-beige-beta3-loong64-20240315-163042.iso
```

### STEPS TO REPRODUCE | 复现步骤

打开深度之家，点击登录帐户

### OBSERVED RESULT | 观察到的结果

点击之后没有反应

### EXPECTED RESULT | 期望的结果

能够正常登录

**Comment by babyfengfjx** [comment]
@kobe337  请确认。

**Comment by kobe337** [comment]
bug已确认，目前loong64架构存在此问题，麻烦帮忙看下哈
@Zeno-sole

**Comment by Zeno-sole** [comment]
@kobe337  已解决，请使用RC2最新镜像验证

**Comment by kobe337** [comment]
deepinv23 loong64架构Preview 验证通过
@LichenKassYuan  请关注公告，在版本发布后进行重试哈，感谢反馈

**Comment by LichenKassYuan** [comment]
> deepinv23 loong64架构Preview 验证通过
> @LichenKassYuan  请关注公告，在版本发布后进行重试哈，感谢反馈

收到
