### ISSUE TITLE
安装器 deepin-installer 6.0.38

### ISSUE THREAD

**Issue by ArchieMeng** [linuxdeepin/developer-center#7557]
### package information | 软件包信息

deepin-installer 6.0.38

### Package repository address | 软件包仓库地址

https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20240320/

### changelog | 更新信息

- 修复4K屏下图标过大超出列表的问题 https://github.com/linuxdeepin/developer-center/issues/6871
- 添加hostname至/etc/hosts, 修复sudo调用过慢的问题 https://github.com/linuxdeepin/developer-center/issues/7227
- 修复初次启动时，"✔"图标过大的问题 https://github.com/linuxdeepin/developer-center/issues/7546

### test suggestion | 测试建议

按描述测试观察

### Sphere of influence | 影响范围

界面，安装后的/etc/hosts配置

### ADDITIONAL INFORMATION | 额外补充

无

**Comment by babyfengfjx** [comment]
@kobe337  请开展回归验证。

**Comment by kobe337** [comment]
1、 #6871 验证未通过，图标展示过大，与产品经理确认，需要修复
2、https://github.com/linuxdeepin/developer-center/issues/7227 使用提测镜像验证通过
3、 #7546 图标大小问题已修复，新增 #7567 问题
