### ISSUE TITLE
系统默认终端不会被应用到文件管理器上

### ISSUE THREAD

**Issue by arslan2012** [linuxdeepin/developer-center#756]
## 缺陷描述

*系统默认终端不会被应用到文件管理器里的open in terminal 功能上*

## 复现步骤
1. 在control center 中的 Default applications 里面设置默认terminal为非deepin-terminal的某一个选项
2. 用文件管理器打开某个文件夹
3. 右键，open in terminal
4. deepin-terminal被打开

## 期望行为

我设置的默认终端是什么就应该打开什么

### 发行版以及版本

[Arch Linux rolling]

### 相关的软件包版本

[deepin-file-manager 1:4.7.1.10-1]
[deepin-control-center 4.8.6-1]
### 其他内容
目前可通过手动重新链接x-terminal-emulator来修复
```bash
sudo rm /usr/bin/x-terminal-emulator
sudo ln -s /usr/bin/kitty /usr/bin/x-terminal-emulator
```

**Comment by BLumia** [comment]
文件管理器的行为其实就是[直接执行 `x-terminal-emulator`](https://github.com/linuxdeepin/dde-file-manager/blob/4.7.1.10/dde-file-manager-lib/controllers/filecontroller.cpp#L826) .

@electricface 确认一下问题？

**Comment by hualet** [comment]
> 在arch 下用 update-alternatives --config x-terminal-emulator 命令修改成 /usr/lib/deepin-daemon/default-terminal

这套好像是 Debian 独有的吧？

**Comment by arslan2012** [comment]
@hualet 对，update-alternatives是 Debian独有的，arch只能手动重新链接
@electricface 而且现在我只要升级一下deepin组件的版本，x-terminal-emulator就会被改回去，我得重新链接一遍

**Comment by electricface** [comment]
那么就可以要求深度文件管理器，打开终端首先查找 /usr/lib/deepin-daemon/default-terminal ，如果存在则运行它，否则还向之前一样运行x-terminal-emulator 。

**Comment by BLumia** [comment]
> 那么就可以要求深度文件管理器，打开终端首先查找 /usr/lib/deepin-daemon/default-terminal ，如果存在则运行它，否则和之前一样运行 x-terminal-emulator 。

`x-terminal-emulator` 是标准里的东西吗？这两个的优先顺序有没有啥说法，比如通过其他非deepin应用设默认终端会不会更新 `/usr/lib/deepin-daemon/default-terminal` 之类

**Comment by felixonmars** [comment]
我记得不是，是 deepin 这边引入的。

**Comment by BLumia** [comment]
> 我记得不是，是 deepin 这边引入的。

https://bbs.archlinux.org/viewtopic.php?id=139238 能搜到似乎也有非 deepin 的应用在用的样子，不过的确没有找到文档或者规范。

**Comment by hualet** [comment]
应该也是debian的alternative系列的东西，直接用 `/usr/lib/deepin-daemon/defaul-terminal` 不行？

**Comment by BLumia** [comment]
> 应该也是 debian 的 alternative 系列的东西，直接用 `/usr/lib/deepin-daemon/defaul-terminal` 不行？

的确没翻到默认终端这样的标准，那就还按 @electricface 的方案，先找 `/usr/lib/deepin-daemon/default-terminal` 用，找不到就用 `x-terminal-emulator` 吧。

**Comment by arslan2012** [comment]
``` bash
 $ pacman -Q deepin-control-center              
deepin-control-center 4.9.1-1
$ pacman -Q deepin-file-manager                
deepin-file-manager 1:4.7.4.4-1
$ /usr/lib/deepin-daemon/defaul-terminal
zsh: no such file or directory: /usr/lib/deepin-daemon/defaul-terminal
$ ls /usr/lib/deepin-daemon
backlight_helper    dde-osd             deepin-boot-maker-service  langselector
dde-authority       dde-session-daemon  default-file-manager       search
dde-authority-pam   dde-suspend-dialog  default-terminal           soundeffect
dde-greeter-setter  dde-system-daemon   desktop-toggle             theme-thumb-tool
dde-lockservice     dde-warning-dialog  dnetwork-secret-dialog
dde-lowpower        dde-welcome         grub2
```

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/41596/

**Comment by liuwen123** [comment]
已修复

**Comment by BLumia** [comment]
一个事情记录一下，并非所有终端都支持 `-e` 参数，深度文件管理器在调用终端执行脚本时用的是 `-e` （并不判断当前调用的到底是哪个终端），如果所设的默认终端不支持此选项或行为不一致，则可能出现问题。

现已知的包含：gnome terminal 可能要废弃 `-e` 参数。
