### ISSUE TITLE
Context menu on second screen

### ISSUE THREAD

**Issue by rafaeldev** [linuxdeepin/developer-center#760]
Hi everyone!

When a try click with right mouse button on desktop empty part the context menu does not appear.
On my desktop screen works fine!

**second screen:**
![deepin-screen-recorder_select area_20181120145004](https://user-images.githubusercontent.com/4596160/48789301-dde7a300-ecd3-11e8-98ac-66cee0208ca8.gif)

**main screen:**
![image](https://user-images.githubusercontent.com/4596160/48789621-9f061d00-ecd4-11e8-89fc-3f582e377b00.png)

Thanks!

**Comment by hualet** [comment]
> Other things which I get now: I can't move shortcut icons on main screen to second screen. It is expected or it is a bug?

it's kind of weird, but it's expected behavior, no content or response on the second screen, so closing.

**Comment by erikdubois** [comment]
Is this going to be solved or is this the expected behavior on the second screen?
No icons and no context menu on second display is normal?
