### ISSUE TITLE
龙芯平台火狐浏览器显示为 x86_64

### ISSUE THREAD

**Issue by zoze0** [linuxdeepin/developer-center#7600]
### SUMMARY | 问题概要

![截图_选择区域_20240323165548](https://github.com/linuxdeepin/developer-center/assets/20562449/a732bcf3-b776-4cea-8979-11ea88a17d07)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin-23-beige-beta3-loong64-20240321-095335.iso 预装的 firefox123.0
```

### STEPS TO REPRODUCE | 复现步骤

`navigator.userAgent` 检测

**Comment by xzl01** [comment]
这个是上游的问题，并且由于部分网站并不认识la的设备，如果以la作为UA头反而会带来兼容性问题：参照arm的mac设备的UA头一般以intel作为架构名上报。
如果你想解决这个问题，可以向firefox汇报，或者自行修改UA
