### ISSUE TITLE
打印机驱动预装集成-镜像提测

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#7608]
**镜像地址：**
https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240325/

**需求链接**
https://cooperation.uniontech.com/app/6f20cf83-ef8a-4067-bac9-b05c6d6bbcb6/659cb107406deda90632107c/65dc23fa406deda9069eb282/row/092b619f-20de-4ced-afc1-0c6faa796a2f

**备注**
具体打印机支持型号询问GPT即可
![image](https://github.com/linuxdeepin/developer-center/assets/43427321/bec16521-3504-4365-b521-7475bd137ff4)

**Comment by Zeno-sole** [comment]
**支持的打印机列表**

以下是我能为您提供的一些打印机驱动程序及其支持的打印机型号列表：

1. printer-driver-brlaser：
   - Brother DCP-L2500D
   - Brother DCP-L2520DW
   - Brother DCP-L2540DN
   - Brother DCP-L2540DW
   - Brother DCP-L2560DN
   - Brother DCP-L2560DW
   - Brother HL-L2300D
   - Brother HL-L2340DW
   - Brother HL-L2360DN
   - Brother HL-L2360DW
   - Brother HL-L2365DW
   - Brother HL-L2380DW
   - Brother MFC-L2700DN
   - Brother MFC-L2700DW
   - Brother MFC-L2720DW
   - Brother MFC-L2740DW

2. printer-driver-c2050：
   - Canon LBP-660

3. printer-driver-c2esp：
   - Kodak ESP 3
   - Kodak ESP 5
   - Kodak ESP 7
   - Kodak ESP 9

4. printer-driver-cjet：
   - HP Color LaserJet 8500
   - HP LaserJet 1100
   - HP LaserJet 4
   - HP LaserJet 4000
   - HP LaserJet 5
   - HP LaserJet 6

5. printer-driver-dymo：
   - DYMO LabelWriter 300
   - DYMO LabelWriter 330
   - DYMO LabelWriter 400

6. printer-driver-escpr：
   - Epson AL-M200
   - Epson AL-M2300
   - Epson AL-M2400
   - Epson AL-M300
   - Epson AL-M400
   - Epson AL-M8100
   - Epson AL-MX200
   - Epson AL-MX300
   - Epson AL-MX400
   - Epson AL-MX700

7. printer-driver-foo2zjs：
   - HP Color LaserJet 2600n
   - HP LaserJet 1000
   - HP LaserJet 1018
   - HP LaserJet 1020
   - HP LaserJet 1022
   - HP LaserJet 1022n
   - HP LaserJet 1022nw
   - HP LaserJet 1022nxi

9. printer-driver-gutenprint：
   - 该驱动程序支持的打印机非常多，包括但不限于：
     - Canon
     - Epson
     - HP
     - Lexmark
     - Xerox

10. printer-driver-hpcups：
    - HP 所有的打印机系列

11. printer-driver-hpijs：
    - HP 所有的打印机系列

12. printer-driver-m2300w：
    - Minolta-QMS magicolor 2300W
    - Minolta-QMS magicolor 2300DL

13. printer-driver-min12xxw：
    - Minolta PagePro 12xxW

14. printer-driver-pnm2ppa：
    - HP PhotoSmart P1000
    - HP PhotoSmart P1100
    - HP PhotoSmart P1215
    - HP PhotoSmart P1218

15. printer-driver-postscript-hp：
    - HP 所有支持 PostScript 的打印机系列

16. printer-driver-ptouch：
    - Brother P-Touch series

17. printer-driver-pxljr：
    - HP Color LaserJet 2600n
    - HP LaserJet 1000
    - HP LaserJet 1018
    - HP LaserJet 1020
    - HP LaserJet 1022
    - HP LaserJet 1022n
    - HP LaserJet 1022nw
    - HP LaserJet 1022nxi

18. printer-driver-sag-gdi：
    - Samsung ML-85G

19. printer-driver-splix：
    - Samsung CLP-300
    - Samsung CLP-500
    - Samsung CLP-510
    - Samsung ML-1510
    - Samsung ML-1520
    - Samsung ML-1610
    - Samsung ML-1710
    - Samsung ML-1740
    - Samsung ML-1750

以上列表中所列的打印机型号并非详尽，仅仅是其中一部分，驱动程序可能支持更多型号。建议查阅官方文档以获取最新信息。本列表由GPT提供

**Comment by babyfengfjx** [comment]
@luodeepin  确保需求中提供的驱动正常安装即可，具体类型如果在论坛发现有覆盖的，可以给予答复，让用户更新此驱动。
