### ISSUE TITLE
深度系统更新（2018.12.27） 更新后 微信 QQ 等聊天软件无法使用深度截图剪贴板的图片

### ISSUE THREAD

**Issue by zazcoder** [linuxdeepin/developer-center#762]
深度系统更新（2018.12.27） 更新后 微信 QQ 等聊天软件无法使用深度截图剪贴板的图片

**Comment by lolimay** [comment]
论坛原讨论贴如下 [2018.12.27日系统更新后QQ的复制粘贴有问题](https://bbs.deepin.org/forum.php?mod=viewthread&tid=172974&page=1#pid549187)

**Comment by lolimay** [comment]
刚刚升级了一下 2018.12.27 的推送更新，更新重启后，发现确实是此次更新带来的新 BUG。

**Comment by zccrs** [comment]
https://github.com/linuxdeepin/dde-daemon/commit/6be92d5b3d29e23263eb5581b12322d5a8e818ce

已经修复了，本周更新后就可以了
