### ISSUE TITLE
代码贡献指南的 Wiki 过期了? 

### ISSUE THREAD

**Issue by CareF** [linuxdeepin/developer-center#763]
https://github.com/linuxdeepin/developer-center/wiki/Contribution-Guidelines-for-Developers#%E9%85%8D%E7%BD%AE-gerrit

第二步 `GitHub->Profile` 并找不到... 也似乎没有办法手动修改邮箱地址.

**Comment by CareF** [comment]
英文页面 https://github.com/linuxdeepin/developer-center/wiki/Contribution-Guidelines-for-Developers-en#setup-for-gerrit
的 this page 也过期了

**Comment by BLumia** [comment]
是过期了，这个地方你只需要在 GitHub 账号设置有至少一个公开的邮箱就行了，那里读的是那个。另外设置完在 gerrit 设置新邮箱的时候可能会提示错误，这时候退出 gerrit 并重新登录就行了。

我们打算逐渐把代码审核和协作平台从 gerrit 迁移到 GitHub （深度终端项目是第一个试水迁移的，其他的还没开始），以后贡献指南应该就是写 GitHub 了（（（
