### ISSUE TITLE
How to switch back to the older launcher icon on the dock ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#765]
Hi,

I see that the launcher icon has been changed ...

current one is ...

![deepinscreenshot_select-area_20181230141114](https://user-images.githubusercontent.com/3283676/50545537-e15c3b80-0c3c-11e9-8c1c-452b7616f369.png)

I like the older one ...

![deepinscreenshot_select-area_20181230141249](https://user-images.githubusercontent.com/3283676/50545543-0d77bc80-0c3d-11e9-993a-b0a2181589f1.png)

Can you please tell me how i can switch back to the older one ?

thank.s

**Comment by aiamuzz** [comment]
even a hack or bypass will do ... if only i knew the location of the image the dock uses for the launcher icon ...

**Comment by hualet** [comment]
You can replace the icon set of `dde-launcher` in deepin icon theme, or also in the hicolor maybe.

**Comment by hualet** [comment]
> > You can replace the icon set of `dde-launcher` in deepin icon theme, or also in the hicolor maybe.
> 
> dde-launcher themes all use the current deepin logo as launcher icon on dock and efficient mode ...
> 
> the icon files in the hicolor folder has many different sizes ... the fashion mode and efficient mode use 2 different sizes of the deepin logo files ... at least can you tell me those 2 sizes used here ... that way i can change only the launcher-icon in the dock and efficient mode panel ... that way the deepin logo of other sizes used on other applications will not be affected !

you can just put an SVG in the scalable folder.

**Comment by aiamuzz** [comment]
> you can just put an SVG in the scalable folder.

@hualet ... 

the launcher icon in the SVG scalable folder is already the old launcher icon ... 
currently the dock (fashion and efficient) is sourcing the deepin logo icon from a place i can't seem to locate ... may be your dock team can tell the exact folder from where its sourcing it !

**Comment by hualet** [comment]
@listenerri
