### ISSUE TITLE
Cannot boot from loop-mounted Live ISO anymore

### ISSUE THREAD

**Issue by probonopd** [linuxdeepin/developer-center#767]
## Describe the bug

Cannot boot from loop-mounted Live ISO anymore with 15.7 and 15.8. It worked before.

## To Reproduce

1. Download `deepin-15.8-amd64.iso`
2. Set up grub to loop-mount and boot the iso (see below)
3. Try to boot

`grub.cfg`

```
menuentry "deepin-15.8-amd64.iso - debian-live 0" --class debian {
        iso_path="/boot/iso/deepin-15.8-amd64.iso"
        search --no-floppy --file ${iso_path} --set
        live_args="for-debian-live-3 --> findiso=${iso_path} live-config.keyboard-layouts=de live-config.locales=en_US.UTF-8 live-config.timezone=Europe/Berlin live-config.username=me live-config.hostname=host max_loop=256"
        custom_args=""
        iso_args="boot=live components quiet splash union=overlay"
        loopback loop ${iso_path}
        linux (loop)/live/vmlinuz ${live_args} ${custom_args} ${iso_args}
        initrd (loop)/live/initrd.lz
}
```

## Expected behavior

The Live ISO boots (like the earlier versions of the Deepin Live ISOs successfully did)

## Screenshots

![screenshot](https://user-images.githubusercontent.com/2480569/50551384-7bd97080-0c77-11e9-82b7-b274bb1008e1.png)

### Distro & Version

Linux Deepin 15.7 and 15.8 (it worked in previous versions)

### Additional context

I am using [SystemImageKit](https://github.com/probonopd/SystemImageKit) to boot multiple distributions and versions, which is especially useful for debugging purposes.

![](https://user-images.githubusercontent.com/2480569/32960053-e1b345d4-cbc3-11e7-9f34-c1cc11b5b1c7.png)

**Comment by probonopd** [comment]
The string "debug is busted" seems to come from overlayroot:
https://github.com/search?q=%22DEBUG_BUSTED%3D1%22&type=Code

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.

**Comment by tsic404** [comment]
Sorry, this issue will be closed soon.Issues on v15 are not being dealt with.

**Comment by probonopd** [comment]
Could you please try to reproduce it on the lastest version and see whether it is working correctly there? Thank you very much.
