### ISSUE TITLE
How to open Image-Viewer in full screen mode every time ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#768]
Hi,

I want image viewer to open in full screen mode every time ... 
or
Is there a way i can launch the image viewer with a full screen command ? Basically i would like to open a GIF file in full screen from the command line ... something like ...

`deepin-image-viewer /path/to/the/GIF/file.gif`

basically a flag that can be added to the above command so it opens into a full screen ... 

Also, Is there a way i can make this GIF window show as always on top ? A command for that will be useful too.

thank.s

**Comment by antechdesigns** [comment]
> Hi,
> 
> I want image viewer to open in full screen mode every time ...
> or
> Is there a way i can launch the image viewer with a full screen command ? Basically i would like to open a GIF file in full screen from the command line ... something like ...
> 
> `deepin-image-viewer /path/to/the/GIF/file.gif`
> 
> basically a flag that can be added to the above command so it opens into a full screen ...
> 
> Also, Is there a way i can make this GIF window show as always on top ? A command for that will be useful too.
> 
> thank.s

There is a .conf file in your home folder: .config/deepin/deepin-image-viewer/config.conf
You could set the width and height to your monitors screen size?

**Comment by aiamuzz** [comment]
> There is a .conf file in your home folder: .config/deepin/deepin-image-viewer/config.conf
> You could set the width and height to your monitors screen size?

i check the config file ... i need fullscreen without the title bar ... setting a height and width will open the window maximized but with the title bar ...

**Comment by zccrs** [comment]
I'm sorry, At least there is no way right now.

**Comment by hualet** [comment]
No way at the moment, but maybe you can write some window script to do that after we move to kwin in the future.
