### ISSUE TITLE
【deepin_V23_Release】【一般】【正常】【论坛反馈】【系统】 Realtek"免驱型"USB无线网卡芯片，被识别成U盘

### ISSUE THREAD

**Issue by kobe337** [linuxdeepin/developer-center#7681]
### SUMMARY | 问题概要

论坛反馈链接：https://bbs.deepin.org/post/269335
 Realtek"免驱型"USB无线网卡芯片，被识别成U盘

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Beta3/
```

### PRE-REQUIREMENT | 预置条件

准备一个USB无线网卡设备

### STEPS TO REPRODUCE | 复现步骤

1.连接USB无线网卡设备，命令行输入lsusb, 观察返回的信息

### OBSERVED RESULT | 观察到的结果

 "免驱型"USB无线网卡芯片，被识别成U盘

### EXPECTED RESULT | 期望的结果

 "免驱型"USB无线网卡芯片能被系统正常识别

**Comment by babyfengfjx** [comment]
请开展回归验证，关联集成： #7678

**Comment by kobe337** [comment]
https://github.com/linuxdeepin/developer-center/issues/7678 已验证通过，待用户端特定设备通过后关闭 https://bbs.deepin.org/post/269335

**Comment by kobe337** [comment]
https://github.com/linuxdeepin/developer-center/issues/7678 验证通过，usb-modeswitch-data的安装校验，检查配置cat /etc/usb_modeswitch.conf 文件
usb_modeswitch通过读取配置文件中的参数并实现所有 USB 设备的初始化和通信，可用于处理没有被切换到正确模式，也就是没有被正确识别的usb设备。
