### ISSUE TITLE
command to switch wm

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/developer-center#769]
For the Manjaro-Deepin edition I am trying to find a way to switch between metacity and deepin-wm via script. So I am looking for a command that would achieve that. If I can do it by editing a config file or overriding a dconf key that would also work for me.
Thank you for any suggestions.

**Comment by BLumia** [comment]
`deepin-metacity --replace` and `deepin-wm --replace` ?

**Comment by oberon-manjaro** [comment]
actually not a bad idea! :stuck_out_tongue_winking_eye: @BLumia !

**Comment by hualet** [comment]
@oberon-manjaro FYI we already have the shortcut  `Super-Shift-Tab`.

**Comment by hualet** [comment]
> @hualet I was not looking for a keyboard command but for a command for scripting.

OK :smile:
