### ISSUE TITLE
[Deepin Integration]~[V23-Release] integrate libreoffice 24.2.0-1

### ISSUE THREAD

**Issue by UTsweetyfish** [linuxdeepin/developer-center#7695]
### package information | 软件包信息

包名 | 版本
-- | --
libreoffice | 24.2.0-1
libzxcvbn | 2.5+dfsg-2

### Package repository address | 软件包仓库地址

    deb [trusted=yes] https://ci.deepin.com/repo/obs/home:/sweetyfish:/deepin:/Testing:/libreoffice/testing/ ./

### changelog | 更新信息

libreoffice 24

因单测失败，未集成 riscv64

### test suggestion | 测试建议

除了 libreoffice 基础功能外，应验证
- [ ] libreoffice-core 不依赖 libboost-locale1.74.0，可以依赖 boost 1.83

**Comment by babyfengfjx** [comment]
@vivianxf  请开展集成验证。

**Comment by vivianxf** [comment]
集成验证通过，请及时合入：

1.添加仓库升级成功，包版本正确
2.libreoffice正常使用
3.libreoffice-core依赖关系正确

综上所述，本次集成通过~
