### ISSUE TITLE
[archlinux] Text cut off in Control Center 

### ISSUE THREAD

**Issue by Nick11358** [linuxdeepin/developer-center#77]

**Comment by fasheng** [comment]
@sbwtw @jouyouyun Font settings issue?

**Comment by sbwtw** [comment]
yes, maybe your font size or font width too large, the word-wrap cant break a word, so "personalization" must be display at single line

**Comment by hualet** [comment]
The font size is fixed if my memory is correct. @sbwtw 
And what font do you use @Nick11358 ?

**Comment by Nick11358** [comment]
I'm sorry about the lateness of my response
This is my current font settings in Personalization

![deepin current font](https://cloud.githubusercontent.com/assets/16515470/14872694/6a0c86b4-0cb4-11e6-9804-d99b45b6f1ae.png)

**Comment by funilrys** [comment]
We (maybe) can close this @hualet

**Comment by hualet** [comment]
Close for now.
