### ISSUE TITLE
Change keyboard layout by right control

### ISSUE THREAD

**Issue by DenisBY** [linuxdeepin/developer-center#770]
I couldn't change a shortcut to change keyboard layout by right control like I have it in KDE. Pressing right control doesn't saved as shortcut. Is it by design or it's a bug?

**Comment by hualet** [comment]
DDE doesn't support single key as shortcut except Super, so I can't tell if it's by design or a bug, I think it's a thing to be enhanced.

**Comment by aiamuzz** [comment]
oh ... you have a single key (right_Control) as a shortcut ... i wonder if its really a good way ... one could just press the right_Control key to perform some operation and then realise they don't ... the fact that the key was pressed abandoned mid way ... would result in a keyboard layout being changed ...

A combination key is the right way ... and deepin already has that in place ... i don't see much value in enhancing it ... my two cents ...

**Comment by DenisBY** [comment]
KDE provides this amount of options for switching layout:
![image](https://user-images.githubusercontent.com/1147703/51034384-e27b5a00-15a6-11e9-8178-d7240b22918c.png)
I'm not saying you should add the same amount, but it would be nice to have more than 3 options.

@aiamuzz I'm not saying you should enable this by default. But user who choosed this type knows what he is doing (like me).

**Comment by aiamuzz** [comment]
> KDE provides this amount of options for switching layout:
> ![image](https://user-images.githubusercontent.com/1147703/51034384-e27b5a00-15a6-11e9-8178-d7240b22918c.png)
> I'm not saying you should add the same amount, but it would be nice to have more than 3 options.
> 
> @aiamuzz I'm not saying you should enable this by default. But user who choosed this type knows what he is doing (like me).

sure ... more power to the user ... user is king !!!
:)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
