### ISSUE TITLE
【deepin_V23_Release】【一般】【有空】【集成测试】【DDE】【任务栏】将鼠标放置在 深度之家/音乐等插件图标上时，没有tips提示

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#7711]
### SUMMARY | 问题概要

关联集成：https://github.com/linuxdeepin/developer-center/issues/7679

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Beta3/deepin-desktop-community-23-Beta3-amd64.iso
```

### PRE-REQUIREMENT | 预置条件

1.安装镜像：https://cdimage.uniontech.com/community/releases/23-Beta3/deepin-desktop-community-23-Beta3-amd64.iso
2.加入内测
3.添加转测仓库,更新至转测环境

### STEPS TO REPRODUCE | 复现步骤

1. 将鼠标放置在插件区域的深度之家/音乐等图标上，查看对应提示

### OBSERVED RESULT | 观察到的结果

深度之家/音乐等插件图标上时，没有tips提示

![7711](https://github.com/linuxdeepin/developer-center/assets/96416089/dcdcc212-adfb-4eac-afd8-08906cc81821)

### EXPECTED RESULT | 期望的结果

有对应tips提示

**Comment by babyfengfjx** [comment]
@tsic404  请进行优化~

**Comment by luodeepin** [comment]
验证通过
dde-shell 0.0.7
![截图_选择区域_20240409145759](https://github.com/linuxdeepin/developer-center/assets/96416089/330c06ec-a96d-40bd-8887-6ae8604fa013)
