### ISSUE TITLE
[Deepin Integration]~[V23-Release] integrate linux kernel 6.6.23

### ISSUE THREAD

**Issue by UTsweetyfish** [linuxdeepin/developer-center#7713]
### package information | 软件包信息

包名 | 版本
-- | --
linux-image-deepin-hwe-amd64 | 6.6.23-hwe
linux-headers-deepin-hwe-amd64 | 6.6.23-hwe
linux-image-6.6.23-amd64-desktop-hwe | 23.01.00.23
linux-headers-6.6.23-amd64-desktop-hwe | 23.01.00.23
linux-libc-dev | 23.01.00.23

### Package repository address | 软件包仓库地址

    deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1046/testing/ ./
    deb [trusted=yes] https://ci.deepin.com/repo/deepin/deepin-community/linux-6.6.23/ kernel main

### changelog | 更新信息

修复amdgpu卡死在登录界面

### test suggestion | 测试建议

https://github.com/deepin-community/kernel/issues/96

https://github.com/deepin-community/kernel/issues/97

**Comment by kobe337** [comment]
6.6.23确认不集成，后续使用6.6.25进行集成验证回归
