### ISSUE TITLE
deepin-installer 安装器 6.0.39 集成

### ISSUE THREAD

**Issue by ArchieMeng** [linuxdeepin/developer-center#7717]
### package information | 软件包信息

包名 | 版本
-- | --
deepin-installer | 6.0.39

### Package repository address | 软件包仓库地址

https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240402/deepin-23-beige-beta3-amd64-20240402-103938.iso

### changelog | 更新信息

- 启用试用模式
- 修复创建已有用户时报未知错误的问题 https://github.com/linuxdeepin/developer-center/issues/7659
- 修复多盘全盘安装界面反复点击保留用户数据选项后磁盘状态始终置灰 https://github.com/linuxdeepin/developer-center/issues/5695
- 更新轮播图

### test suggestion | 测试建议

- 多盘全盘安装保留用户数据按钮好像需要有盘已装系统才会出现。
- 试用模式和轮播图的文档在https://udoc.uniontech.com/apps/editor/832348
- 试用模式下启动的系统安装结果存在和直接启动安装不一样的可能。

### Sphere of influence | 影响范围

- 全盘安装界面按钮
- 可能影响安装流程

### ADDITIONAL INFORMATION | 额外补充

无

**Comment by babyfengfjx** [comment]
@xuqi27837288  请开展回归验证。

**Comment by Zeno-sole** [comment]
@xuqi27837288  打印机驱动预装需求也在次版本合入，顺便一起看一下，详情见 https://cooperation.uniontech.com/app/6f20cf83-ef8a-4067-bac9-b05c6d6bbcb6/659cb107406deda90632107c/65dc23fa406deda9069eb282/row/092b619f-20de-4ced-afc1-0c6faa796a2f

**Comment by xuqi27837288** [comment]
相关问题需要解决修复后再提交集成来进行回归测试,谢谢 ~
