### ISSUE TITLE
Feature Request : Ability to perform other operations when a search operation is under way in the file manager

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#772]
## Describe the bug

Not sure if its bug or a plane missed out use case.

## To Reproduce

Open File Manager ...
Hit `Ctrl+t` to open a new tab ...
HIt `Ctrl+f` to start a search ... when the search is underway try hitting `Ctrl+t` to open a third tab.

## Expected behavior

One open tab ... second tab running a search operation ... Ctrl+t should open a third, fourth, fifth ... tabs

### Distro & Version

Linux Deepin 15.8

### Related package version

dde-file-manager 4.7.1.10

**Comment by zccrs** [comment]
The keyboard focus on the searching tag is at the search line edit widget

**Comment by aiamuzz** [comment]
> The keyboard focus on the searching tag is at the search line edit widget, And the edit widget will be eat the 'Ctrl+t' keyboard event.

You mean to say the focus is on the search line edit widget ... and because of this other operations / events like `Ctrl+t` and resizing column width do not work ?

**Comment by aiamuzz** [comment]
@zccrs ... @hualet ... @BLumia ...

I append this issue to a feature request ...

Wouldn't it be great to see file manager perform all its other operations ... like `Ctrl+t` to launch new tabs , to be able to adjust column width of the tab where search is running ... or any other operation that is blocked due to running search operation ?

Please find that all of the above works features work on 'Nautilus' application ... attaching a screen recording of the same as reference.

![deepin-screen-recorder_nautilus_20190111143758](https://user-images.githubusercontent.com/3283676/51024518-cb8d3580-15af-11e9-9f56-b96a6faa6c03.gif)

**Comment by aiamuzz** [comment]
would like to add that operation `Ctrl+Tab` does not work from the tab where search is running ... however it works one-way from a normal tab to the tab where search is running ... and then it stops responding ... the search edit field takes over i guess ...

**Comment by aiamuzz** [comment]
> The keyboard focus on the searching tag is at the search line edit widget, And the edit widget will be eat the 'Ctrl+t' keyboard event.

@zccrs ... this is not an elegant implementation ... you might want to make it more elegant ...

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
