### ISSUE TITLE
dde-dock plugin 会不会考虑直接支持 PyQt? 考不考虑扫描 ~/ 下的特定路径加载插件? 

### ISSUE THREAD

**Issue by CareF** [linuxdeepin/developer-center#773]
写插件能用 Python 的话, 能吸引更多人的吧? 
在 ~/ 下安装用户自定义插件在权限管理上更安全, 也更容易安装吧?

**Comment by CareF** [comment]
@zccrs 谢回复! 
那考不考虑加载的时候除了扫描 `/usr/lib/dde-dock/plugins/` 之外也扫一下比如 `~/.config/deepin/dock-plugin` 之类的路径呢?

**Comment by zccrs** [comment]
> @zccrs 谢回复!
> 那考不考虑加载的时候除了扫描 `/usr/lib/dde-dock/plugins/` 之外也扫一下比如 `~/.config/deepin/dock-plugin` 之类的路径呢?

可以考虑添加 ~/.local/lib/dde-dock/plugins

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
