### ISSUE TITLE
无法安装韩语输入法<z4>

### ISSUE THREAD

**Issue by ragerma** [linuxdeepin/developer-center#774]
即使把系统语言调成韩语，也一样只有中文输入法。输入法设置工具里也没法添加，软件商店里也搜不到。多语言支持有待提高啊。

**Comment by snyh** [comment]
@electricface @wangjia12 @hualet 

dde-daemon里有一个对应的i18n模块是专门做这个的，但应该是没有配置韩文输入法相关的配置。

**Comment by electricface** [comment]
安装 fcitx-hangul 吗？

**Comment by hualet** [comment]
> 安装 fcitx-hangul 吗？

应该是的

**Comment by electricface** [comment]
我测试了，系统语言切换到韩语 ko 就会安装 fcitx-hangul

**Comment by hualet** [comment]
@ragerma

**Comment by BLumia** [comment]
根据上面的讨论，看上去这个 issue 本身是不存在的，鉴于很久也没有得到进一步的信息反馈，目前这边也没能复现，就先关闭这个 issue 了。

如果你在目前最新版本中仍然有遇到这个问题的话，欢迎开新的 issue 来进行反馈，并附带必要的信息以便我们复现和处理问题~
