### ISSUE TITLE
6.5.1 org.deepin.browser 集成

### ISSUE THREAD

**Issue by hwb55** [linuxdeepin/developer-center#7743]
### package information | 软件包信息

org.deepin.browser 6.5.1

### Package repository address | 软件包仓库地址

[org.deepin.browser_6.5.1-1_amd64.deb](http://aptly.uniontech.com/pkg/nonfree-apricot/release-candidate/YnJvd3NlcjIwMjQtMDMtMjYgMjA6MTA6NDY/pool/non-free/o/org.deepin.browser/org.deepin.browser_6.5.1-1_amd64.deb)

### test suggestion | 测试建议

帐号同步，翻译等问题

### Sphere of influence | 影响范围

社区

### ADDITIONAL INFORMATION | 额外补充

需要进行deb转玲珑包
需要在玲珑下面以--no-sandbox参数运行

**Comment by kamiyadm** [comment]
@Zeno-sole

**Comment by hwb55** [comment]
@Zeno-sole

**Comment by kamiyadm** [comment]
已添加至玲珑测试仓库。

**Comment by kamiyadm** [comment]
@Zeno-sole

**Comment by babyfengfjx** [comment]
@luodeepin  请开展集成验证。

**Comment by luodeepin** [comment]
测试通过
1. 基础功能正常
2. 发散测试未发现严重问题

**Comment by Zeno-sole** [comment]
@kamiyadm  请合入 玲珑 release仓库中

**Comment by kamiyadm** [comment]
> @kamiyadm 请合入 玲珑 release仓库中

已经合入

**Comment by babyfengfjx** [comment]
发现在N卡设备上无法播放视频（B站，腾讯视频等）
