### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【发散测试】【deepin ID】deepin Cloud同步中日历模块名称未国际化,展示为英文

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#7744]
### SUMMARY | 问题概要

必现问题

@myml 

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240402/
内核版本： 
控制中心:6.0.47
```

### PRE-REQUIREMENT | 预置条件

登录deepin ID

### STEPS TO REPRODUCE | 复现步骤

观察deepin Cloud同步中日历模块名称展示

### OBSERVED RESULT | 观察到的结果

日历模块展示为英文,未国际化

![截图_选择区域_20240407104808](https://github.com/linuxdeepin/developer-center/assets/62528742/7b30969b-50fb-4a99-8e15-0e7b09645114)

### EXPECTED RESULT | 期望的结果

deepin Cloud同步中日历模块展示为中文

**Comment by babyfengfjx** [comment]
@myml  请进行优化~

**Comment by dengbo11** [comment]
# 测试步骤:

1. 添加仓库
`deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test- 
 integration-pr-1368:/dde/testing/ ./
 deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1339/testing/ ./
`

**Comment by dengbo11** [comment]
@babyfengfjx 帮忙安排下, 使用玲珑版日历此问题已修复

**Comment by babyfengfjx** [comment]
@vivianxf  请开展回归验证，使用玲珑版本日历。

**Comment by vivianxf** [comment]
验证镜像： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240509/deepin-23-beige-rc-amd64-20240509-120442.iso
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1368:/dde/testing/ ./
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1339/testing/ ./
版本：linglong:1.5.0-1
验证步骤：提单的步骤
验证现象：日历在同步中的名称本地化展示为中文
验证结果：通过
