### ISSUE TITLE
wlan连接正常，图标仍显示感叹号<周二>

### ISSUE THREAD

**Issue by ziqiangxu** [linuxdeepin/developer-center#775]
请将下方的缺陷汇报模板中的文字替换为您实际需要汇报的缺陷所对应的描述文字。

## 缺陷描述

如题

## 截图

*如果适用于你所汇报的缺陷，可以附带截图来帮助描述你所遇到的缺陷（BUG）*

## 复现环境:

*部分缺陷可能需要在特定环境下才能复现，所以请尽可能详细的提供可能导致该缺陷的环境信息*

### 发行版以及版本

Linux Deepin 15.8

### 相关的软件包版本

[如. dde-file-manager v1.7 (4.5.6.2-2)]

*如果你不确定是哪些包出了问题，你也可以考虑提供一个列表来描述那些你认为可能相关联的包以及它们的版本号*

### 其他内容

*描述其他任何和你所要汇报的缺陷相关的内容，以便我们定位问题并进行处理。如果没有其它信息，你也可以移除这个段落，如果必要时我们会根据实际情况询问其它细节*
![_ _20190102210111](https://user-images.githubusercontent.com/18530271/50593113-eede2380-0ed1-11e9-8b38-4498dcbc3d49.png)

**Comment by listenerri** [comment]
过段时间是否会恢复正常图标? 网络连通性的检查是有一些延迟的. 
如果一直是提示网络不正常, 应该是无法访问现在的检查地址导致的, 这个等下次推送更新解决

**Comment by listenerri** [comment]
@deepinzhangshuang 

把 NetworkManager 那个网络链接的补丁改成这个吧:
```
http://packages.deepin.com/misc/check_network_status.txt
```

**Comment by liuwen123** [comment]
已推送
