### ISSUE TITLE
[Deepin Integration]~[V23-Release] lightdm 1.30.0 测试

### ISSUE THREAD

**Issue by UTsweetyfish** [linuxdeepin/developer-center#7759]
### package information | 软件包信息

仅测试，请勿集成

lightdm 1.30.0

### Package repository address | 软件包仓库地址

    deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/deepin-community:/lightdm:/PR-4/deepin_develop/ ./

### ADDITIONAL INFORMATION | 额外补充

LightDM is a free and open-source X display manager that aims to be lightweight, fast, extensible and multi-desktop. It can use various front-ends to draw the user interface, also called Greeters. It also supports Wayland.

**Comment by babyfengfjx** [comment]
@kobe337  请对齐该集成的具体影响内容，以及此次更新的内容，开展对应验证。

**Comment by kobe337** [comment]
验证通过。
环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Beta3/
仓库：提测单仓库
内核：Linux deepinb3-PC 6.6.21-amd64-desktop-hwe #23.01.00.23 SMP PREEMPT_DYNAMIC Mon Mar 18 09:58:09 CST 2024 x86_64 GNU/Linux

【结论】：
测试通过，暂无严重问题及影响，覆盖场景：
1、lightdm版本核对，安装校验
2、无密码登陆
3、锁屏登陆解锁，重启、注销、待机、休眠登陆解锁
4、检查lightdm日志是否存在报错信息
