### ISSUE TITLE
【deepin_V23_Release】【一般】【正常】【发散测试】【日历】sudo apt install dde-calendar安装日历报错

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#7763]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/community/releases/23-Beta3/deepin-desktop-community-23-Beta3-amd64.iso
dde-calendar:5.13.0
```

### STEPS TO REPRODUCE | 复现步骤

1.在终端执行命令sudo apt install dde-calendar
2.观察安装结果

### OBSERVED RESULT | 观察到的结果

1.安装报错
![企业微信截图_1712568136885](https://github.com/linuxdeepin/developer-center/assets/96415804/0e4ce2bc-200a-490c-a093-c53489b392cf)

### EXPECTED RESULT | 期望的结果

1.安装无报错

**Comment by babyfengfjx** [comment]
@myml  请帮忙优先处理~

**Comment by vivianxf** [comment]
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240531/deepin-23-beige-rc2-amd64-20240531-113757.iso
目前最新镜像日历应用为玲珑，可以正常使用ll-cli install org.dde.calendar正常安装，deb版本问题单先关闭处理，后续复现再单独跟踪
