### ISSUE TITLE
千牛工作台无法发送图片

### ISSUE THREAD

**Issue by zazcoder** [linuxdeepin/developer-center#777]
与现在无法使用剪贴板的图片bug 无关，使用任何一个截图工具 都无法在千牛工作台发送图片
聊天界面的 发送图片 按钮也无法使用
总之任何图片都发送不了
现在我们已经全部切换到deepin了 千牛工作台是平时工作必须工具  希望能尽快修复此bug 感谢

**Comment by BLumia** [comment]
这个问题（同 #762 ）已经在 https://github.com/linuxdeepin/dde-daemon/commit/6be92d5b3d29e23263eb5581b12322d5a8e818ce 这个提交中修复了，请等待这周的更新（目前还没有推送），更新之后重启系统（准确的说，只需要重启 `dde-session-daemon` ）即可解决这个问题。

**Comment by zccrs** [comment]
请问千牛是个客户端吗，软件名称叫啥呀

**Comment by zazcoder** [comment]
> 软件我安装试了下，没有找到在那发送图片
> ![default](https://user-images.githubusercontent.com/13449038/50622665-f80ad700-0f49-11e9-9daf-5e62d7341b2a.png)
> 是这里的阿里旺旺图标吗

是千牛工作台 
![image](https://user-images.githubusercontent.com/17716859/51005959-f52c6980-157b-11e9-8d5c-a5f637cd9233.png)

接待客户的时候在聊天窗口无法给用户发送图片， 使用截图或直接在聊天窗口选择发送图片都不行

![image](https://user-images.githubusercontent.com/17716859/51006013-2c027f80-157c-11e9-876d-2645b250ecd2.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
