### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【内部反馈】【DDE】【launchpad】【UI】搜索响应区域，搜索框大小 过小 

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#7774]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://cdimage.uniontech.com/community/releases/23-Beta3/deepin-desktop-community-23-Beta3-amd64.iso
dde-launchpad 0.5.0
```

### PRE-REQUIREMENT | 预置条件

1.安装镜像：https://cdimage.uniontech.com/community/releases/23-Beta3/deepin-desktop-community-23-Beta3-amd64.iso
2.加入内测
3.添加转测仓库,更新至转测环境

### STEPS TO REPRODUCE | 复现步骤

1. 打开启动器 窗口模式 ，查看搜索框长度大小显示

### OBSERVED RESULT | 观察到的结果

1. 搜索框大小长度 过小
![image](https://github.com/linuxdeepin/developer-center/assets/96416089/6c8505ed-4660-4c6b-808d-05b1db490b47)

### EXPECTED RESULT | 期望的结果

1. 对角拉长搜索框，按上图的 红色框间距

**Comment by babyfengfjx** [comment]
@BLumia  请优先处理。

**Comment by BLumia** [comment]
关联： https://github.com/linuxdeepin/dde-launchpad/pull/159 已修复，待集成。

**Comment by luodeepin** [comment]
验证通过
dde-launchpad 0.6.0
![7774](https://github.com/linuxdeepin/developer-center/assets/96416089/19cfb997-70dc-454a-a9aa-a898a4f1598b)
