### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【内部反馈】【DDE】【launchpad】【UI】鼠标放置在搜索框上时，需要出现 hover效果

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#7775]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://cdimage.uniontech.com/community/releases/23-Beta3/deepin-desktop-community-23-Beta3-amd64.iso
dde-launchpad 0.5.0
```

### PRE-REQUIREMENT | 预置条件

1.安装镜像：https://cdimage.uniontech.com/community/releases/23-Beta3/deepin-desktop-community-23-Beta3-amd64.iso
2.加入内测
3.添加转测仓库,更新至转测环境

### STEPS TO REPRODUCE | 复现步骤

1. 打开启动器 ，分别在窗口模式和全屏模式下，将鼠标放置在搜索框上查看效果显示

### OBSERVED RESULT | 观察到的结果

1. 没有hover效果

### EXPECTED RESULT | 期望的结果

1.  显示hover效果

**Comment by babyfengfjx** [comment]
@tsic404  请优先处理。

**Comment by BLumia** [comment]
关联： https://github.com/linuxdeepin/dde-launchpad/pull/159 已修复，待集成。

**Comment by luodeepin** [comment]
验证通过
dde-launchpad 0.6.0
![7775](https://github.com/linuxdeepin/developer-center/assets/96416089/f59f2921-89ce-48fc-82bf-79b824c9c4f2)
