### ISSUE TITLE
连续几天不关机后窗口过渡动画会特别卡

### ISSUE THREAD

**Issue by lolimay** [linuxdeepin/developer-center#778]
## 缺陷描述

电脑长时间不关机和休眠后，打开或关闭一个应用，窗口过渡动画会特别卡，包括除 Chrome 之外的所有应用。特别严重的情况下，还会导致鼠标输入无响应。

简单看了一下内存，内存占用是正常的，空闲内存超过 50% 以上。

## 复现步骤

把电脑待机三四天甚至一周以上后，打开或关闭任意一个除 Chrome 之外的应用， 窗口过渡动画会特别卡。

## 期望行为

长期待机稳定运行

## 截图

*如果适用于你所汇报的缺陷，可以附带截图来帮助描述你所遇到的缺陷（BUG）*

## 复现环境:

*部分缺陷可能需要在特定环境下才能复现，所以请尽可能详细的提供可能导致该缺陷的环境信息*

### 发行版以及版本

15.8

### 系统日志

[deepin-feedback-all-20190103-162026.tar.gz](https://github.com/linuxdeepin/developer-center/files/2723049/deepin-feedback-all-20190103-162026.tar.gz)

**Comment by hualet** [comment]
有看 swap 占用么？多半是这个导致的吧？

**Comment by lolimay** [comment]
好的，我再挂机几天试试尝试复现一下。

**Comment by zwx19981207** [comment]
这个应该和你开机的时间没有关系
