### ISSUE TITLE
使用 AM 启动玲珑软件的到的 cgroup "不正确"

### ISSUE THREAD

**Issue by tsic404** [linuxdeepin/developer-center#7780]
### SUMMARY | 问题概要

调用 AM 接口启动的玲珑软件 cgroup 无法被 AM 正确识别

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin v23
```

### STEPS TO REPRODUCE | 复现步骤

1. 使用 AM 接口启动玲珑软件
2. 调用 `xcb_res_query_client_ids`相关接口获取到程序对应的 PID，查询到玲珑启动后软件的实际的 PID，非`ll-cli`的 PID
3. `cat /proc/$PID/cgroup` 查看软件的 cgroup

### OBSERVED RESULT | 观察到的结果

该 cgroup 为玲珑的，无法被 AM 正确的识别

**Comment by black-desk** [comment]
@myml 就是之前刚跟你讲的那个事情.

**Comment by myml** [comment]
这个已经捷径了
