### ISSUE TITLE
打开微信和QQ系统会自动注销

### ISSUE THREAD

**Issue by jerry79** [linuxdeepin/developer-center#779]
只要开启了微信和QQ，系统就会不定时的自动注销，返回登录界面
而且这个不定时，时间差有可能是几天，有可能是几分钟。新年前有一天下午也是出现了一个下午注销4次，到今天又再次出现了。
这个问题在15.4还是15.5的时候出现过一段时间，后来不知道怎么给解决了。

**Comment by BLumia** [comment]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=173282&extra=  帮你贴一下（（（（

**Comment by hualet** [comment]
下次遇到这种情况，不要急着再次登陆（**切记**），切换到 tty，拿一下 `/var/log/lightdm/`目录的内容和 `~/.xsession-errors` 文件。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
