### ISSUE TITLE
deepin-mail 6.4.7

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#7793]
### package information | 软件包信息

包名 | 版本
-- | --
deepin-mail | 6.4.7
org.deepin.browser | 6.5.1-1
### Package repository address | 软件包仓库地址

deb  [trusted=yes] https://aptly.uniontech.com/pkg/nonfree-beige-v2/release-candidate/ZGVlcGluLW1haWwtMjAyNDA0MDgyMDI0LTA0LTA4IDE3OjQzOjE2/  unstable non-free
deb  [trusted=yes]  https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main community commercial

### changelog | 更新信息

打包deb版本

### test suggestion | 测试建议

参考deepin-mail测试用例
参考browser测试用例

issues:  https://github.com/linuxdeepin/developer-center/issues/7765 https://github.com/linuxdeepin/developer-center/issues/7764

### Sphere of influence | 影响范围

deepin-mail

### ADDITIONAL INFORMATION | 额外补充

无

**Comment by babyfengfjx** [comment]
@vivianxf  请开展集成验证，确保DEB格式的应用功能正常。

**Comment by vivianxf** [comment]
集成测试不通过：提交五个bug,一个严重问题
浏览器：
https://pms.uniontech.com/bug-view-250669.html
https://pms.uniontech.com/bug-view-250661.html
https://pms.uniontech.com/bug-view-250657.html
https://pms.uniontech.com/bug-view-250647.html---严重问题

邮箱：
https://pms.uniontech.com/bug-view-250681.html
