### ISSUE TITLE
【deepin_V23_Release】【一般】【正常】【集成测试】【玲珑应用】ll-cli run org.deepin.compressor报错

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#7795]
### SUMMARY | 问题概要

ll-cli run org.deepin.compressor报错
关联集成： #7757 

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：arm镜像
linglong-bin:1.4.3-1
```

### PRE-REQUIREMENT | 预置条件

1.按照上述集成准备环境

### STEPS TO REPRODUCE | 复现步骤

1.ll-cli install org.deepin.comperssor 安装玲珑版本压缩管理器
2.ll-cli run org.deepin.comperssor 运行
3.观察运行结果

### OBSERVED RESULT | 观察到的结果

1.运行报错
![Uploading 195a6077-ecb5-4f4c-be40-227e8a8fff7b.jpg…]()

### EXPECTED RESULT | 期望的结果

1.压缩管理器成功运行

**Comment by babyfengfjx** [comment]
@dengbo11  请进行优化~

**Comment by vivianxf** [comment]
验证镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240430/
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1368:/dde/testing/ ./
版本：linglong:1.5.0-1
验证步骤：提单的步骤
验证现象：ll-cli run org.deepin.comperssor 正常
验证结果：通过
