### ISSUE TITLE
[Arch Linux] deepin-dock 无法响应对 Wine（非 deepinwine）托盘图标的的鼠标事件

### ISSUE THREAD

**Issue by chenjunyu19** [linuxdeepin/developer-center#781]
## 缺陷描述

无论是左键还是右键 TIM 托盘图标都没有反应。

## 复现步骤

1. 使用 `wine` 加载 `TIM.exe`
2. 点击，dock 托盘上的 TIM 图标
3. 缺陷 对鼠标事件无响应 发生

## 期望行为

TIM 打开主面板或右键菜单。

## 截图

![_ _20190105194709](https://user-images.githubusercontent.com/15167799/50724108-d6b11300-1122-11e9-909f-41196a2c997d.gif)

### 发行版以及版本

Arch Linux + DDE 15.8

### 相关的软件包版本

```
$ pacman -Q wine deepin-dock deepin-wine-tim 
wine 4.0rc4-1
deepin-dock 4.8.6-1
deepin-wine-tim 2.1.5-4
```

### 其他内容

- 用终端运行 `dde-dock`，点击 TIM 图标时无任何输出
- 软件包 `deepin-wine-tim` 是 <https://github.com/countstarlight/deepin-wine-tim-arch>，即原版 Wine + Deepin 的 TIM 容器。
- 另见 <https://github.com/countstarlight/deepin-wine-tim-arch/issues/21https://github.com/countstarlight/deepin-wine-tim-arch/issues/21>。
- 在 `Wine System Tray` 里是可以正常响应的，见下图。

![_ _20190105200416 mp4](https://user-images.githubusercontent.com/15167799/50724249-4aecb600-1125-11e9-9aba-5daeb2da85f1.gif)

**Comment by hualet** [comment]
@listenerri 这个上次不是修复过了？版本不对？

**Comment by listenerri** [comment]
dock 的版本是对的

**Comment by felixonmars** [comment]
最新版仍然可以重现：

deepin-dock 4.8.7.2

**Comment by chenjunyu19** [comment]
> @felixonmars
> deepin-wine-tim 这个包对应 deepin 下的 deepin.com.qq.office 吗?

并不是。`deepin-wine-tim` 这个包是依赖于原版 Wine 的，而 `deepin.com.qq.office` 是依赖 `deepin-wine` 的。

**Comment by listenerri** [comment]
> > @felixonmars
> > deepin-wine-tim 这个包对应 deepin 下的 deepin.com.qq.office 吗?
> 
> 并不是。`deepin-wine-tim` 这个包是依赖于原版 Wine 的，而 `deepin.com.qq.office` 是依赖 `deepin-wine` 的。

在 Arch 下如果 qq 没这个问题的话, 我想并不是 dock 的原因

**Comment by felixonmars** [comment]
我这里其他原来正常的 wine 程序也可以重现。有一个细节是右键时图标会明暗闪烁两次，菜单没有出来。会不会和窗口焦点有关？wine 的菜单在我们的窗管看来有可能会是普通窗口，但是失去焦点就会消失。

**Comment by hualet** [comment]
应该不是窗管的问题，我看在 wine 自己提供的托盘窗口里面点击不是正常的么。
我搞台机器试试吧

**Comment by TTcheng** [comment]
最新版仍然可以重现：

deepin-dock 4.8.9-2

**Comment by amit-gshe** [comment]
最新的4.10.3-1问题依然存在

**Comment by liangyongrui** [comment]
deepin-dock 4.10.3-2 问题依然存在

**Comment by chenjunyu19** [comment]
#1434

**Comment by felixonmars** [comment]
@hualet 在上次小黑框可以解决的思路上，有什么新进展吗？

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
