### ISSUE TITLE
6.5.2 org.deepin.browser V23 集成

### ISSUE THREAD

**Issue by hwb55** [linuxdeepin/developer-center#7813]
### package information | 软件包信息

org.deepin.browser 6.5.2

### Package repository address | 软件包仓库地址

deb [trusted=yes] http://aptly.uniontech.com/pkg/nonfree-apricot/release-candidate/YnJvd3NlcjIwMjQtMDMtMjYgMjA6MTA6NDY/ unstable non-free
### changelog | 更新信息

【社区版】【deepin_V23_Release】【集成测试】【浏览器】浏览器不能正常播放网页视频

### test suggestion | 测试建议

关联集成 https://github.com/linuxdeepin/developer-center/issues/7793

**Comment by hwb55** [comment]
@Zeno-sole

**Comment by baicailio** [comment]
验证结果：爱优腾芒bilibili主流视频网站浏览器播放短视频，长视频均正常
[已解决](https://pms.uniontech.com/bug-view-250647.html---%E4%B8%A5%E9%87%8D%E9%97%AE%E9%A2%98)
