### ISSUE TITLE
安装器 deepin-installer 6.0.41集成

### ISSUE THREAD

**Issue by ArchieMeng** [linuxdeepin/developer-center#7817]
### package information | 软件包信息

deepin-installer 6.0.41

### Package repository address | 软件包仓库地址

https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20240411/deepin-23-beige-beta3-amd64-20240411-100836.iso

### changelog | 更新信息

修复自定义安装和高级安装高分屏下分区编辑按钮无法响应的问题。 https://github.com/linuxdeepin/developer-center/issues/7719

### test suggestion | 测试建议

无

### Sphere of influence | 影响范围

自定义和高级安装界面的按钮响应区域。

### ADDITIONAL INFORMATION | 额外补充

需要高分屏验证

**Comment by babyfengfjx** [comment]
@xuqi27837288  请开展回归验证。

**Comment by xuqi27837288** [comment]
【环境】：
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240411
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.21-amd64-desktop-hwe
【结论】：
测试通过，暂无严重问题及影响
