### ISSUE TITLE
openconnect connecting problem

### ISSUE THREAD

**Issue by xenups** [linuxdeepin/developer-center#782]
the issue pointed that openconnect cant get user name and password in deepin 15.8
seems network manager has a problem in connecting

**Comment by jodevan** [comment]
Not demanding anything but is there any idea when this is going to be fixed?
Thanks!

**Comment by xenups** [comment]
we are still waiting for  fixing this issue

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
