### ISSUE TITLE
更换到NV-PRIME显卡方案后flatpak应用不能用了

### ISSUE THREAD

**Issue by jay763190097** [linuxdeepin/developer-center#784]
显卡信息：
![_ _20190106165351](https://user-images.githubusercontent.com/16317178/50734066-a7a6aa00-11d3-11e9-8947-8e7e30a3e89a.png)
运行日志：
![_ _20190106165317](https://user-images.githubusercontent.com/16317178/50734062-93fb4380-11d3-11e9-9066-9b7e4d1eb014.png)
听说是libGL.so冲突了，so 怎么解决呢？
![_ _20190106165150](https://user-images.githubusercontent.com/16317178/50734054-5f878780-11d3-11e9-8a57-0805b77a658f.png)

**Comment by hualet** [comment]
@Iceyer @deepinzhangshuang

**Comment by Iceyer** [comment]
装一个和你显卡去掉匹配的扩展试试
flatpak remote-ls flathub | grep nvidia
