### ISSUE TITLE
Feature/Enhancement request : Deepin Image Viewer ... An option to open images in full screen

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#785]
Hi,

@hualet ... @zccrs ... in continuation to this [info](https://github.com/linuxdeepin/developer-center/issues/768#issuecomment-451077112) ...

i would like to request for the addition of a full screen(**i mean F11 full screen** ... i am not referring to the window in a maximized state) option to Deepin Image Viewer ... 

currently the application config file allows the 'height and width' option ... i would like to change this to 'fullscreen' so all my images are opened as a fullscreen

thanks.

**Comment by hualet** [comment]
May I ask why do you want that?

**Comment by aiamuzz** [comment]
hahahaha ...
as there is no screen saver option in Linux ...

I have a gif animation file that i have created a shortcut for ... the moment i invoke the shortcut keys the gif animation file opens only in a window ...

if it had the 'full screen' option then ... then the launch would look like a screensaver triggered manually with a shortcut !

**Comment by aiamuzz** [comment]
Just like the option present in the Terminal application below ...

![deepinscreenshot_select-area_20190106172301](https://user-images.githubusercontent.com/3283676/50735595-cd35b280-11d7-11e9-97c9-6560f792ac69.png)

**Comment by hualet** [comment]
> hahahaha ...
> as there is no screen saver option in Linux ...
> 
> I have a gif animation file that i have created a shortcut for ... the moment i invoke the shortcut keys the gif animation file opens only in a window ...
> 
> if it had the 'full screen' option then ... then the launch would look like a screensaver triggered manually with a shortcut !

OK, then there's no need for the current request, because we're preparing a screensaver.

**Comment by aiamuzz** [comment]
oh ... wow ... really ... linux lacks a good screensaver option ... i have tried hours to get `xscreensaver` and `gnome-screensaver` ... with no satisfactory results ... the screen saver collections are ugly ...

**Comment by aiamuzz** [comment]
is there any link to the WIP screensaver you are preparing ... i would love to install and test it ... 

Would you be supporting gif animation to be used as screensavers ... if you did it will become popular pretty easy and fast as creating animated GIF's are pretty easy and widely available.

**Comment by hualet** [comment]
@zccrs

**Comment by hualet** [comment]
> with GIF's supported in your screensaver ... **every GIF animation out there with a dark background will instantly become your screensaver collection** ... providing instant popularity !!!

You think so? I think you need to take care of your tastes now :)

**Comment by aiamuzz** [comment]
> > with GIF's supported in your screensaver ... **every GIF animation out there with a dark background will instantly become your screensaver collection** ... providing instant popularity !!!
> 
> You think so? I think you need to take care of your tastes now :)

hahahaha ... i know what you mean ... crazy GIF's will make it to the screensaver ... but its power to people ... **and some real publicity to linux as a result of their craziness ...** ... you and me can certainly enjoy the fun sitting on the stands ... :wink:  :stuck_out_tongue_winking_eye: :wink: 

as far as my tastes go ... i have a pretty decent GIF that will make a great screensaver ... and you might agree with my taste totally when i share it with you ... but its still a work in progress on sharing it with your team 

@hualet ... least of all i thought you must be pretty clear on my tastes by now ... i am bordering OCD when it comes to visual appeal !!!

**Comment by hualet** [comment]
> > > with GIF's supported in your screensaver ... **every GIF animation out there with a dark background will instantly become your screensaver collection** ... providing instant popularity !!!
> > 
> > 
> > You think so? I think you need to take care of your tastes now :)
> 
> hahahaha ... i know what you mean ... crazy GIF's will make it to the screensaver ... but its power to people ... **and some real publicity to linux as a result of their craziness ...** ... you and me can certainly enjoy the fun sitting on the stands ... wink stuck_out_tongue_winking_eye wink
> 
> as far as my tastes go ... i have a pretty decent GIF that will make a great screensaver ... and you might agree with my taste totally when i share it with you ... but its still a work in progress on sharing it with your team
> 
> @hualet ... least of all i thought you must be pretty clear on my tastes by now ... i am bordering OCD when it comes to visual appeal !!!

Looking forward to that :joy:

**Comment by aiamuzz** [comment]
> Looking forward to that joy

Its under development(not the only the screensaver but a whole suite of what i want to present) ... have been preparing the presentation to your team ... so who is Deepin Head & Project Manager for the OS ... their names and email ID's would help make the pitch/presentation ... you could email it to my github email id ... is there some other mode i can have a private chat with your @hualet ? ... whatsapps or skype ... ?

**Comment by hualet** [comment]
Telegram is fine, I'm available here https://t.me/deepin

The discussion is sort of off-topic now and we probably won't consider the feature request, so closing this issue.
