### ISSUE TITLE
Copying files to an external drive with Drag and Drop doesn't work on Deepin File Manager

### ISSUE THREAD

**Issue by jcfernandez-890825** [linuxdeepin/developer-center#788]
## Describe the bug

When you drag and drop a file/directory to a external drive like this:
![draganddropexternaldrive](https://user-images.githubusercontent.com/28876647/50790035-c9fbfe80-128b-11e9-917f-b3abdd6799b5.png)

It shows this error for files:
![draganddropexternaldrivefileerror](https://user-images.githubusercontent.com/28876647/50791652-79d36b00-1290-11e9-9660-cd05331af95c.png)

And this error for directories:
![draganddropexternaldrivedirectoryerror](https://user-images.githubusercontent.com/28876647/50791774-ccad2280-1290-11e9-9a57-d49b58f30ee2.png)

## To Reproduce

1. Open Deepin File Manager
2. Drag and drop a file/directory to an external drive
3. See error

## Expected behavior

When using drag and drop over a file/directory to an external drive, it should create a copy of such element in the external drive, instead it shows an error

### Distro & Version

Copied from `screenfetch`
```
OS: Deepin 15.8 unstable
Kernel: x86_64 Linux 4.15.0-29deepin-generic
DE: Deepin 15.8
WM: Deepin WM
```

### Related package version

Copied from `apt list dde-file-manager`
`dde-file-manager/panda,now 4.7.1.10-1 amd64`

**Comment by BLumia** [comment]
Can be reproduced here, thank you for reporting this issue!

As a workaround, you can open your external drive in another window and perform a Drag-n-Drop to another window instead of D-n-D to the sidebar. We'll fix it later :)

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
