### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【发散测试】【DDE】【控制中心】因任务栏需求调整，需要隐藏 位置调整选项 和 智能隐藏选项

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#7881]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240415/deepin-23-beige-beta3-amd64-20240415-110758.iso
```

### PRE-REQUIREMENT | 预置条件

1. 安装镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240415/deepin-23-beige-beta3-amd64-20240415-110758.iso

### STEPS TO REPRODUCE | 复现步骤

1. 打开控制中心 - 个性化 -桌面 查看 位置和状态选项

### OBSERVED RESULT | 观察到的结果

1. 位置选项没有隐藏，状态选项中没有隐藏 智能隐藏 选项
![qw](https://github.com/linuxdeepin/developer-center/assets/96416089/8337a3e1-ee74-4eda-a6f4-57a925dc73d0)

### EXPECTED RESULT | 期望的结果

1. 隐藏 位置 选项 ， 状态 中 隐藏 智能隐藏 选项

**Comment by babyfengfjx** [comment]
@kegechen  这个问题优先帮忙处理。

**Comment by meiyixiang** [comment]
上左右做置灰处理，后面大概率还会加回来，此版本不让我用选择即可。
相关需求，智能隐藏此版本不提供。

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240415/deepin-23-beige-beta3-amd64-20240415-150405.iso
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.21-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
