### ISSUE TITLE
How about define a default translate path for applications

### ISSUE THREAD

**Issue by Iceyer** [linuxdeepin/developer-center#79]
默认的翻译文件路径:

/usr/share/{ApplicationName}/translations/{ApplicationName}_{LocaleName}.qm

可以供fallback的路径:
{applicationDirPath}/translations/{ApplicationName}_{LocaleName}.qm
{PWD}/translations/{ApplicationName}_{LocaleName}.qm

再DApplication中提供loadtranslator接口来加载.

**Comment by sbwtw** [comment]
load translator 可以接受个语言列表来做 fallback 比如 zh-cn > zh-tw > en-us，如果没提供的话，再用系统当前语言

**Comment by Iceyer** [comment]
Add new loadTranslator API.
```//! load translate file form system or application data path;
/*!
  \param localeFallback, a list of fallback locale you want load.
  \return load success
*/
bool DApplication::loadTranslator(QList<QLocale> localeFallback)
```

**Comment by snyh** [comment]
fallback列表有点不合理呀。。。　　这个值如何取?  zh-cn,zh-tw肯定不对。
比如一个it语种，　有部分没有对应的翻译，　之前是直接fallback到en, 这个勉强能接受。
现在直接成了fallback到zh-cn?  那对it的用户来说，这个是非常糟糕的体验。　

fallback几乎只能选择en 其他任何语言都不合适。(除了特定地区的工具) 

另外，一个程序可能提供多个翻译文件

**Comment by snyh** [comment]
而且这个fallback到底能解决什么问题?   只有en是可以假设的，其他zh-cn都是没有特殊意义。　不可以去打破这种约定俗成的方式。(找不到的时候fallback到en)  

只要你希望app是国际化/本地化的就不可能出现fallback到en之外的其他语言。　所以完全不理解这个接口的意义

**Comment by Iceyer** [comment]
大概是想给大陆用户提供繁体中文服务吧 @sbwtw

**Comment by snyh** [comment]
。。。　难道初始化的时候
if (zh_CN == "zh_CN" || LANG="zh_TW") {
       DApplication::loadTranslator("zh_CN", "zh_TW", "zh_HK", "en_US");
}

你们也太会玩了吧。。。。。。

**Comment by sbwtw** [comment]
不是呀，你首先肯定是 system language 的，最终肯定是 en_us 的，我的意思是不要一次从 zh_CN fallback 到 en_US，可以 zh_CN -> zh_* -> en_US

**Comment by sbwtw** [comment]
比如用户系统是简体中文，而程序只有繁体中文和英文的情况下，zh_TW 总要比 en_US 靠谱吧
而且不光是中文有 zh_{CN/TW/HK} 其它语言也有这样分的，在同一个语系里面 fallback 能最大程序保证用户能看得懂

**Comment by Iceyer** [comment]
@sbwtw 仔细想了一下：如果一个zh_HK用户，现在提供的翻译有zh_CN和zh_SG, 那么应该fallback到什么语言呢？

**Comment by sbwtw** [comment]
@Iceyer 这种优先级肯定会是个问题，但选哪个也比 en_US 合理吧，感觉在这里只要程序能保持行为一致（比如就粗暴的按字典顺序）就可以了

**Comment by Iceyer** [comment]
@sbwtw 那实际上这个列表参数是不需要的，因为程序内部的回滚逻辑实际上已经确定好了。

**Comment by sbwtw** [comment]
@Iceyer  嗯，这个可以在内部实现上自动处理掉，那这个接口就只接受一个最佳情况就好了
