### ISSUE TITLE
Has the Disk plugin been withdrawn from the dock ... can't see it on the dock/system tray !

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#793]
Hi,

Off late i have noticed that the Disk plugin is no longer present on the dock/system tray ... has it been officially been withdrawn ? or is it some bug that i am encountering !

**Comment by aiamuzz** [comment]
@listenerri ... the issue was closed for the dock system tray module which was rectified ... but turns out the Disks Plugin in system tray is not being loaded ... as a result of this the partitions are failing to automount on startup ... https://github.com/linuxdeepin/developer-center/issues/793 ... https://github.com/linuxdeepin/developer-center/issues/792 ... issues have directed this as an issue with the **dde-dock**

**Comment by listenerri** [comment]
the log file you post in #792 is not for dock

**Comment by listenerri** [comment]
~/.cache/deepin/dde-dock/dde-dock.log

**Comment by BLumia** [comment]
Some info: dde-dock updated it's API version which cause the dde-disk-mount-plugin plugin API version not match, so it won't be loaded unless dde-disk-mount-plugin updated.

We'll push another update later to catch up the API version change.

**Comment by aiamuzz** [comment]
> Some info: dde-dock updated it's API version which cause the dde-disk-mount-plugin plugin API version not match, so it won't be loaded unless dde-disk-mount-plugin updated.
> 
> We'll push another update later to catch up the API version change.

Is my issue as a result of this ... my issue was occurring even before yesterday's system upgrade !!!

**Comment by aiamuzz** [comment]
> ~/.cache/deepin/dde-dock/dde-dock.log

@listenerri ... sorry because of this issue ... https://github.com/linuxdeepin/developer-center/issues/795 ... i am logged into a Deepin 15.7 installation ... i will post the log after the above issue is fixed and i log back into the affected installation.

**Comment by aiamuzz** [comment]
sorry ... closed it by mistake ...

**Comment by aiamuzz** [comment]
@listenerri ... 

I logged into the OS ... i checked with this command to see if the partitions were mounted ...

```
mountpoint /media/muz/Flatpak
mountpoint: /media/muz/Flatpak: No such file or directory
```
as the output suggested that the partitions weren't mounted ... i ran 

`killall dde-dock`

I then rechecked the above command ...

```
mountpoint /media/muz/Flatpak
mountpoint: /media/muz/Flatpak: No such file or directory
```

Then I opened the File Manager ... and there the partitions mounted immediately after the File Manager was opened.

attaching the log that has probably captured the above test ...
[dde-dock.log](https://github.com/linuxdeepin/developer-center/files/2748792/dde-dock.log)

**Comment by listenerri** [comment]
this will be fix after next update

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
