### ISSUE TITLE
Bug : My WWAN module data connection has become inconsistent !!!

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#795]
## Describe the bug

I have a **HP lt2523 Mobile Broadband Device** WWAN (Mobile Broadband) module on my system ... it was working fine untill a few days ago ... 

my preliminary probing has revealed that the port to which this module loads with is the reason i am not able to connect to data (sms is working though only data connection is a problem.

If this module attaches as `ttyUSB0` data works ...

but booting into the OS seems to be currently loading this module as `cdc-wdm0` and when this happens i am unable to connect to data over my WWAN(pppoe) interface.

## Expected behavior

the module should load as `ttyUSB0` and connect to the data and work as it did 4-5 days before !

## Screenshots

this device fails to connect to data ...
![deepinscreenshot_modem-manager-gui_20190107200107](https://user-images.githubusercontent.com/3283676/50880363-2f72fb00-1404-11e9-803e-40978d16645a.png)

this is how it used to connect before ...

![bb issue - deepinscreenshot_modem-manager-gui_20190107152119](https://user-images.githubusercontent.com/3283676/50880362-2eda6480-1404-11e9-945b-103643b6ea22.png)

![bb issue - deepinscreenshot_select-area_20190107143917](https://user-images.githubusercontent.com/3283676/50880434-61845d00-1404-11e9-8b0d-f09fbff8d789.png)

## Enviroments:

Linux Deepin 15.8

### Additional context

Currently i am doing a circus to connect to this module ... i boot into the affected installations(on `/dev/sda5`) ... the device is loaded as `cdc-wdm0` then i reboot into my second cloned deepin installation(on `/dev/sda9`) running 15.7 ... when it boots here it correctly loads as `ttyUSB0` i connect to data on this installation to check connectivity ... then i reboot from this installation(on `/dev/sda9`) back to my orginal installation(on `/dev/sda5`) and then i see that it has loaded the correct `ttyUSB0` module and now i connect data on my daily driver installation(on `/dev/sda5`) ... **quite a circus isn't it ?**

**Comment by aiamuzz** [comment]
@hualet ... @BLumia ... my WWAN module is the only internet i have ... could you please help me connect with somebody who knows how to switch from `cdc-wdm0` to `ttyUSB0` ... 

I just upgraded today and was testing the new screensaver and Hibernate options and the WWAN module isn't helping me test any further ...

I forced to boot into Deepin 15.7 to write this ... i am stuck on this version until you guys assist me !!!

**Comment by hualet** [comment]
@aiamuzz what if you blacklist the `cdc-wdm0` kernel module?

**Comment by aiamuzz** [comment]
> @aiamuzz what if you blacklist the `cdc-wdm0` kernel module?

thanks for the suggestion ... for now i can work with it and boot into my primary installation and test out the new release.

@hualet ... I hope this bypass(blacklist) is considered a temporary alternative ... and **identifying what broke it after the updates is the more permanent way forward here** ... especially when it was working perfectly fine before ! ... with this objective i would be more than willing to discuss it with your networks specialist ... after things cool down a little ... considering the recent upgrades and its followups ...

FYI i will be starting another fresh issue under "Hibernate" as the blacklisting isn't working when system boots out of hibernation ... https://github.com/linuxdeepin/developer-center/issues/804

PS : remember the long standing mouse issue i was facing ... having stayed on course on it helped us identify the issue with `imwheel` ?

**Comment by aiamuzz** [comment]
@hualet ...

sorry need help ... the above black listing isn't working consistently ... please find some journalctl logs captured immediately after boot.

This log is for my primary installation(on /dev/sda5) which is having the problem ... i have run the command `journalctl -f` before i tried to connect my WWAN device ... towards the end i have tried 3 times to reconnect but with no success.

[WWAN_issue_journalctl -f_Log after reboot.txt](https://github.com/linuxdeepin/developer-center/files/2751928/WWAN_issue_journalctl.-f_Log.after.reboot.txt)

;
;
;
;

for comparison i have log which works find on my second installation(on /dev/sda4) ... which is not upgraded to the current version ... pls find the exact same log after boot ... see how the connection was successful ...

[WWAN_issue_journalctl -f_Log after reboot-sda4-successful.txt](https://github.com/linuxdeepin/developer-center/files/2751929/WWAN_issue_journalctl.-f_Log.after.reboot-sda4-successful.txt)


let me know if you need any other readings out of my installations.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
