### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【DDE】【任务栏】需要把任务栏模式改为：应用布局  —靠左、居中

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#7955]
### SUMMARY | 问题概要

根据产品设计评估分析，需要把 任务栏模式 改为：应用布局  —靠左、居中

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240415/deepin-23-beige-beta3-amd64-20240415-110758.iso
```

### PRE-REQUIREMENT | 预置条件

1. 镜像： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240415/deepin-23-beige-beta3-amd64-20240415-110758.iso

### STEPS TO REPRODUCE | 复现步骤

1. 鼠标放置在任务栏上点击右键 - 设置 应用布局  —靠左、居中

### OBSERVED RESULT | 观察到的结果

1. 右键菜单显示为：模式

### EXPECTED RESULT | 期望的结果

1. 应用布局  —靠左、居中

**Comment by meiyixiang** [comment]
应用布局  靠左、居中，字段使用

**Comment by babyfengfjx** [comment]
@tsic404  这个需要优先处理。

**Comment by luodeepin** [comment]
验证通过
dde-shell 0.0.9
![录屏_选择区域_20240418153715](https://github.com/linuxdeepin/developer-center/assets/96416089/ebf510ee-94fb-4e71-830e-1c403164347a)
