### ISSUE TITLE
Feature Request : add disk ... Label : ... /dev/sda1 ... /dev/sda2 ... & Mountpoint : to Disk Info window ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#796]
Hi,

Wouldn't it be great to add the disk **Labels :** ... `/dev/sda1` ... `/dev/sda2` ... `/dev/sda3` ... etc ...  along with **Mountpoint :** info's to the `Disk Info` in file manager ?

if the partition properties could display this info ... it would come real handy ... without this we have to go back to terminal and crunch a few commands ...  saves time and money ... :stuck_out_tongue_winking_eye:

**Comment by wangjia12** [comment]
![_ _20190225104531](https://user-images.githubusercontent.com/34432879/53325029-44a4da00-391d-11e9-9fba-84ca27af6455.png)

**Comment by aiamuzz** [comment]
@wangjia12 ... thanks to you and the team ... glad now one can get the device name quickly without the terminal !!!

**Comment by aiamuzz** [comment]
@wangjia12 ... @BLumia ... 

seems this feature has leaked out of the cracks during the application update ...

![image](https://user-images.githubusercontent.com/3283676/55342978-ab428800-54c7-11e9-993d-4a6ca7018a32.png)

can no longer find the disk label ...

**Comment by BLumia** [comment]
> seems this already implemented feature...

No it's not yet got implemented.

**Comment by BLumia** [comment]
Next update will contain this feature :)

https://github.com/linuxdeepin/dde-file-manager/pull/229
