### ISSUE TITLE
安装器 6.0.42

### ISSUE THREAD

**Issue by ArchieMeng** [linuxdeepin/developer-center#7971]
### package information | 软件包信息

deepin-installer 6.0.42

### Package repository address | 软件包仓库地址

https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20240417/deepin-23-beige-rc-amd64-20240417-114027.iso

### changelog | 更新信息

修复高分屏下自定义和高级安装按钮图标过大的问题 https://github.com/linuxdeepin/developer-center/issues/6871
自定义和高级安装下根分区默认勾选格式化 https://github.com/linuxdeepin/developer-center/issues/7895
回退部分轮播图

### test suggestion | 测试建议

按关联Issue信息进行测试。

### Sphere of influence | 影响范围

自定义和高级安装界面与格式化的勾选逻辑
安装轮播图

### ADDITIONAL INFORMATION | 额外补充

回退的轮播图分别是：桌面环境，跨端协同和deepin V23

**Comment by babyfengfjx** [comment]
@xuqi27837288  请开展回归验证。

**Comment by xuqi27837288** [comment]
【环境】：
镜像：镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240417
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.25-amd64-desktop-hwe
【结论】：
测试通过，暂无严重问题及影响
