### ISSUE TITLE
1月10日更新：系统托盘图标显示异常，并且点击显示或隐藏时过渡动画卡顿

### ISSUE THREAD

**Issue by hbhgwtf** [linuxdeepin/developer-center#798]
请将下方的缺陷汇报模板中的文字替换为您实际需要汇报的缺陷所对应的描述文字。

## 缺陷描述

1月10日更新：系统托盘图标显示异常，并且点击显示或隐藏时过渡动画卡顿,并且QQ和微信来消息时，鼠标hover事件不显示消息框。

## 复现步骤

点击显示或隐藏时过渡动画卡顿，系统托盘图标显示异常

## 期望行为

正常显示打开程序的图标

## 截图

![image](https://user-images.githubusercontent.com/26326251/50968181-435a5200-1515-11e9-95d3-2e3aa931ca01.png)

![image](https://user-images.githubusercontent.com/26326251/50968185-45241580-1515-11e9-8d69-968d0a9d83c7.png)

## 复现环境:

复现率100%

### 发行版以及版本

Deepin 15.8+6 桌面版

### 相关的软件包版本

dde-file-manager 4.7.1.8

### 其他内容

无

**Comment by hbhgwtf** [comment]
哇！好像是应为最新版topbar的问题，topbar设置里面enable dock tray这一项改变后在topbar能够即时生效，但是在系统dock栏必须要注销或者重启才能生效。

**Comment by BLumia** [comment]
确认是 topbar 的问题的话就可以关掉 issue 了 ;-)

cc: @justforlxz

**Comment by justforlxz** [comment]
存在这个情况，看来是时候加一个杀掉dock的功能了

**Comment by justforlxz** [comment]
但是dock的托盘还是会有图标的，dock也有问题。

**Comment by hualet** [comment]
@justforlxz 你topbar是直接抢了 tray manager，还是像dock一样只是显示trayicon？

**Comment by justforlxz** [comment]
> @justforlxz 你topbar是直接抢了 tray manager，还是像dock一样只是显示trayicon？

当时是会立即抢的

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
