### ISSUE TITLE
【日历插件移植】移植日历插件至RC版本

### ISSUE THREAD

**Issue by meiyixiang** [linuxdeepin/developer-center#7991]
### SUMMARY | 问题概要

背景：专业版对在任务栏时点击时间日期后行为进行了优化需求：鼠标在时间日期hover时显示时间日期长格式2.点击时间日期时显示新的日历插件。3.如需打开日历可点击插件中对应打开日历选项开启日历
规划版本

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
1
```

### PRE-REQUIREMENT | 预置条件

1

### STEPS TO REPRODUCE | 复现步骤

1

### OBSERVED RESULT | 观察到的结果

1

### EXPECTED RESULT | 期望的结果

背景：专业版对在任务栏时点击时间日期后行为进行了优化需求：鼠标在时间日期hover时显示时间日期长格式2.点击时间日期时显示新的日历插件。3.如需打开日历可点击插件中对应打开日历选项开启日历
规划版本

### ADDITIONAL INFORMATION | 额外补充

1

**Comment by yixinshark** [comment]
已沟通，暂时预留。

**Comment by tsic404** [comment]
已加载1070时间插件

**Comment by luodeepin** [comment]
验证通过
https://cdimage.uniontech.com/daily-iso/image-beige/release/amd64/deepin-desktop-community-23-amd64.iso
![截图_选择区域_20240819092938](https://github.com/user-attachments/assets/5d55788c-6af0-4827-9dc1-eb6cff64e8ce)
