### ISSUE TITLE
【图标更新】对现有图标资源进行更新

### ISSUE THREAD

**Issue by meiyixiang** [linuxdeepin/developer-center#7997]
### SUMMARY | 问题概要

从girrt,拉取deepin-icon-theme图标资源进行更新。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
1
```

### STEPS TO REPRODUCE | 复现步骤

1

### OBSERVED RESULT | 观察到的结果

1

### EXPECTED RESULT | 期望的结果

1

### ADDITIONAL INFORMATION | 额外补充

1

**Comment by ArchieMeng** [comment]
已更新合入。https://github.com/linuxdeepin/deepin-desktop-theme/pull/31

**Comment by babyfengfjx** [comment]
@luodeepin  请确认具体更新的图标资源是什么样的，然后在对应集成版本后，进行回归验证。

**Comment by luodeepin** [comment]
与设计核对，多个图标没有更换
https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240423/deepin-23-beige-rc-amd64-20240423-100354.iso

![Uploading 企业微信截图_c2ac33bc-da07-4bb7-8f90-5143ff28c845.png…]()

**Comment by ArchieMeng** [comment]
已确认图标资源确实已经更新。问题出在dock接口上。

**Comment by ArchieMeng** [comment]
忘更版本号了，镜像里的是老的图标。更新版本PR https://github.com/linuxdeepin/deepin-desktop-theme/pull/32

**Comment by ArchieMeng** [comment]
@luodeepin 已合入.等新镜像集成即可重新开展测试。届时deepin-desktop-theme版本号将更新为1.0.11

**Comment by luodeepin** [comment]
最新镜像中，没有合入deepin-desktop-theme版本号为1.0.11

请确认合入提交后，在指派给测试验证
@ArchieMeng

**Comment by ArchieMeng** [comment]
已提交集成申请。https://github.com/linuxdeepin/developer-center/issues/8283

**Comment by ArchieMeng** [comment]
可以关单了。

**Comment by luodeepin** [comment]
与设计确认网络图标没有改，图标颜色没有统一

**Comment by ArchieMeng** [comment]
@luodeepin 任务栏的开发说这是临时代码的问题，暂时不会为此问题修改。考虑关闭Bug单或者遗留，之后任务栏重构了直接激活看看还有没有这个问题接着修。

**Comment by luodeepin** [comment]
@ArchieMeng 好的，那就先遗留发版之后再接着优化

**Comment by luodeepin** [comment]
验证通过
https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240813/deepin-23-beige-release-amd64-20240813-224846.iso

![截图_选择区域_20240814141207](https://github.com/user-attachments/assets/67f0b5f8-0ea3-4a7b-9515-3e274e4b0589)
