### ISSUE TITLE
[archlinux] tap-to-click doesn't switch off

### ISSUE THREAD

**Issue by femans** [linuxdeepin/developer-center#80]
On the touchpad, tap to click can't be switch off. There is a setting for it in the control center, but this does not affect the behaviour. 
The issue has reappeared. Previously this was also the case, after whith it was sort of fixed, except that at bootup it would still have tap-to-click behaviour even with the setting switched off, which could be helped with switching on and off again the setting.

**Comment by fasheng** [comment]
I guess you are using arch-deepin now, right? Looks it's the same issue with gccgo gsettings that reported before.

**Comment by femans** [comment]
True, arch linux. Apologies for not specifying.

Op maandag 9 mei 2016 heeft Xu Fasheng <notifications@github.com> het
volgende geschreven:

**Comment by fasheng** [comment]
Thanks, it's the same with https://github.com/linuxdeepin/developer-center/issues/54
