### ISSUE TITLE
Congrats on the HIbernate option ... works great !!!

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#800]
Hi Team ...

Congrats on the newly implemented Hibernate option on Deepin ... works great ... 
I clocked around 20-30 seconds to hibernate and around 30-40 seconds to boot out of it !!!
A nice feature from windows os is now on linux !!!

Cheers.

**Comment by BLumia** [comment]
Thank you for supporting us!

Since this is not an issue, now closing :P

**Comment by aiamuzz** [comment]
@BLumia ... the wake from hibernation with a virtual machine open is really very very very very very slow ... is this a limitation to be expected ?

I have 16GB RAM and i have 16+GB swap ... hibernation seems to work fine ... its the wake up that is slow ... i get the login screen quick enough but its just not usable i can't move the mouse cursor or enter the password to login ... it takes a really looooooooong time to settle so i can use the interface ...
