### ISSUE TITLE
loongarch64 20240418 rc镜像更新

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#8013]
**镜像地址：** https://ci.deepin.com/repo/deepin/deepin-ports/cdimage/deepin-23-beige-rc-loong64-20240418-101310.iso
**更新日志：**  参照[projects/21](https://github.com/orgs/linuxdeepin/projects/21/views/1 )已集成内容 , 所有已集成内容均合入该镜像
**解决问题：**  https://github.com/linuxdeepin/developer-center/issues/8001

**Comment by kobe337** [comment]
验证通过
#8001 #8000 问题已经修复。
【环境】：
镜像：Deepin OS 23 20240418 loongarch64
内核：Linux deepin-PC 6.9.0-rc3-loong64-desktop #3 SMP PREEMPT Mon Apr 15 11:47:00 CST 2024 loongarch64 GNU/Linux

【结论】：
测试通过，暂无严重问题及影响
