### ISSUE TITLE
After update 15.8 + 6, .AppImage stops working.

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#802]
## Describe the bug
AppImage applications stored on a system-independent partition no longer run after the 15.8 + 6 update. I changed the permissions, and no changes occurred.
By moving these executables to any folder of the "/"; the application works normally.

## To Reproduce
Move the .AppImage executable to an HD partition (other than /home) or to some PenDrive; and click on the file to run it.
The application is not executed.

### Distro & Version
Deepin 15.8+6

### Related package version
Balena Etcher 1.4.9.AppImage
Odio 1.4.AppImage
LibreOffice 6.1.4.AppImage

### Additional context
Before the 15.8+6 update, the .AppImage files on different partitions worked normally.

**Comment by BLumia** [comment]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=173529&extra=

We'll consider about this issue, probably will add an option for that.

**Comment by aiamuzz** [comment]
oh ... executables not working on ext4 partitions ... all my flatpak apps are on one such partition !

**Comment by alexwender1** [comment]
Problem solved in today's update 15.8+7.
