### ISSUE TITLE
深度音乐随机播放应保留历史记录

### ISSUE THREAD

**Issue by iovxw** [linuxdeepin/developer-center#803]
## 缺陷描述

随机播放(shuffle) 不应当是 random，需记忆上一曲和下一曲

## 复现步骤

切换模式为随机播放，点击下一曲和上一曲

## 期望行为

上一曲应为“上一曲”

**Comment by iovxw** [comment]
https://cr.deepin.io/#/c/deepin-music/+/41300

我实现了一个，保留播放列表 1/3 长度为历史

**Comment by Iceyer** [comment]
1. 代码格式：https://community.kde.org/Policies/Kdelibs_Coding_Style#Artistic_Style_.28astyle.29_automatic_code_formatting
2. 保留1/3长度效果似乎不是很好，我在一个10首歌的列表上测试还是容易重复，建议保留 完整的列表长度吧。

**Comment by iovxw** [comment]
项目中大部分文件都没有遵循格式，整体格式化的话变动太大，我新开一个 changeset 格式化吧

然后完整列表长度需要修改算法，新算法必须特别处理才能防止同一首歌在刷新时被连续随机到

不过之前的实现也没有避免这个问题，行为是一致的，我会在下个 changeset 里处理

**Comment by wangjia12** [comment]
这个问题现在怎么样了

**Comment by iovxw** [comment]
@wangjia12 等待 review

**Comment by iovxw** [comment]
已合并 👍🎉
