### ISSUE TITLE
Hibernation related Issue/Bug: blacklisted modules are loading up when system wakes out hibernation ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#804]
Hi,

since last weeks update my WWAN module stopped connecting data (Issue reported here ... https://github.com/linuxdeepin/developer-center/issues/795 ) ... as a temporary alternate i blacklisted the problematic kernel module ...

Further when i tested Hibernation ... i discovered that waking from Hibernation is discarding the `blacklist` protocol ...

Hope this helps you to identify and fix so Hibernation respects the `blacklist` protocol on wake !

**Comment by felixonmars** [comment]
Maybe you need to update the initramfs, just a guess.

**Comment by aiamuzz** [comment]
> Maybe you need to update the initramfs, just a guess.

you mean to say every time we add a `blacklist module` updataing initramfs would be good idea ?

**Comment by felixonmars** [comment]
Yes, and that's how it works.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
