### ISSUE TITLE
wifi password not accepted

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/developer-center#805]
Using latest Archlinux packages on Manjaro.
When trying to connect to a password protected wireless network, the correct password is not accepted and connection fails.
The old workaround as described in [this older bugreport](https://github.com/linuxdeepin/developer-center/issues/246) no longer works ...
Please help. Thank you.

**Comment by felixonmars** [comment]
Still works fine here with that workaround. Maybe some any logs/journals will help?

**Comment by oberon-manjaro** [comment]
hm. any idea where to find relevant log entries?

**Comment by dance707** [comment]
This issue was reported in the Deepin GNU/Linux Telegram group on Jan 5
I was not aware there was a previous work-a-around. My work-a-round was to install and enter password in nm-connection-editor. Works on live USB also, but of course need wired connection to install nm-connection-editor.

**Comment by oberon-manjaro** [comment]
I am trying to investigate further what might have changed recently for the **NetworkManager.conf** no longer working on Manjaro.
@dance707 instead of **nm-connection-editor** you can simply use **nmtui** from the terminal, which comes with regular networkmanager package.

**Comment by oberon-manjaro** [comment]
Interesting is that when I use the network settings in the control-center to enter my password, that works without problem, but when I enter the pw in the popup-window it fails! Ideas?
Again here the content of my added config for reference - anything missing there (but as I said before, it used to work a while back with that) 
``
$ cat /etc/NetworkManager/NetworkManager.conf 
[device]
wifi.scan-rand-mac-address=no
``

**Comment by oberon-manjaro** [comment]
The fact that the control-center works and the popup from the systray doesn't seems to suggest that something with the interface / handing-over of the password information is broken in Deepin, doesn't it?

**Comment by dance707** [comment]
My current install is not reproducing the "wrong password" error. A live USB does consistently reproduce the error, and does not prompt for dialog to be installed. So easier to try wifi-menu, nmtui not work either. Installing and using nm-connection-editor WiFi works good.

**Comment by oberon-manjaro** [comment]
For me in the live environment both **nmtui** and using the **control-center** settings both work. For me the only problem is with the password prompt popup window.

**Comment by dance707** [comment]
Your right control-center does work, but not the popup window like it should.

**Comment by oberon-manjaro** [comment]
Seems the issue is solved with update of **deepin-polkit-agent** to **v0.2.3** which just arrived on our unstable branch. I will now build a new ISO and double check and then forward to our testing and stable branches.

**Comment by oberon-manjaro** [comment]
Hm. No, it's not solved but inconsistent - still investigating.
Strangely after logging out and logging in again password input works for me. Also I experience a strange NUM lock issue that screws up my keyboard even in tty only in connection with running lightdm-deepin. It looks like deepin dm somehow messes with my keyboard settings ... very strange, indeed!

**Comment by oberon-manjaro** [comment]
The latest **deepin-session-ui 4.8.5** seems to have fixed the input problem I mentioned.
The problem with wifi password entry via the popup window seems to be only present in the live environment with autologin. After logging out and back in the password is recognized normally in my tests.
I will now also try building an ISO with autologin disabled to find out if normal login with deepin-dm makes the input window functional.

**Comment by hualet** [comment]
Can you take a picture of the popup window? you don't mix password dialog with keyring dialog, right?

**Comment by oberon-manjaro** [comment]
It's definitely the right box 
![screenshot_2019-01-17_10-00-45](https://user-images.githubusercontent.com/11800714/51308124-b6962380-1a41-11e9-8c1c-d0d8fe8295b4.png)
However a connection with deepin-dm keyring handling seems plausible.
Mind that the issue is present on first boot on an ISO with lightdm autologin and it goes away once I log out and then use deepin-dm to log back in.

**Comment by hualet** [comment]
Any error in the log of dde-session-daemon?

**Comment by oberon-manjaro** [comment]
I'm afraid I cannot see any log file for dde-session-daemon. Where would I look for that?
There is nothing in **~/.cache/deepin** ...

**Comment by hualet** [comment]
I think `journalctl /usr/lib/deepin-daemon/dde-session-daemon` will give what we want.

**Comment by oberon-manjaro** [comment]
Thank you @hualet ! The output is attached.
[dde-session-daemon.log](https://github.com/linuxdeepin/developer-center/files/2800470/dde-session-daemon.log)

**Comment by hualet** [comment]
> Thank you @hualet ! The output is attached.
> [dde-session-daemon.log](https://github.com/linuxdeepin/developer-center/files/2800470/dde-session-daemon.log)

Didn't see anything wrong, where can I download the ISO? so I can let @jouyouyun try it.

**Comment by dance707** [comment]
https://osdn.net/projects/manjaro-community/storage/deepin/18.0.2/
https://osdn.net/projects/manjaro-community/storage/deepin/18.0.2/minimal/

**Comment by jouyouyun** [comment]
> https://osdn.net/projects/manjaro-community/storage/deepin/18.0.2/
> https://osdn.net/projects/manjaro-community/storage/deepin/18.0.2/minimal/

After installing the system, I did not reproduce the bug.

But I reproduced it in livecd, but the strange thing is: When I log out and log in again, this problem can't be reproduced.

I will continue to check the cause of the problem.

**Comment by oberon-manjaro** [comment]
Thank you @jouyouyun , that's exactly how I experience the problem, like described above.
Problem is pesent only with auto-login until you have used dde-lightdm once. So re-logging, or manually logging in in the first place it's fine. ... strange.
Looks like somehow this is related to not launching the session via login screen ??

**Comment by jouyouyun** [comment]
@oberon-manjaro Try this [dde-daemon](https://github.com/linuxdeepin/dde-daemon/commit/12bdb6359a045a25796d7011b2f017b1c470f420)

**Comment by oberon-manjaro** [comment]
Thank you @jouyouyun 
Sorry I was away a while. Will try the patch and let you know :+1:

**Comment by oberon-manjaro** [comment]
Thank you. That fixes it! :+1:

**Comment by hualet** [comment]
There's no commit? @jouyouyun

**Comment by jouyouyun** [comment]
> There's no commit? @jouyouyun

cl: https://cr.deepin.io/41573
