### ISSUE TITLE
安装器 6.0.43 集成申请

### ISSUE THREAD

**Issue by ArchieMeng** [linuxdeepin/developer-center#8064]
### package information | 软件包信息

deepin-installer 6.0.43

### Package repository address | 软件包仓库地址

https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20240419/deepin-23-beige-rc-amd64-20240419-142529.iso

### changelog | 更新信息

试用模式下安装Deepin改为小写deepin https://github.com/linuxdeepin/developer-center/issues/7982

### Sphere of influence | 影响范围

试用模式桌面图标

### ADDITIONAL INFORMATION | 额外补充

无

**Comment by babyfengfjx** [comment]
@baicailio  请开展回归验证，并进行扩展验证，确保安装器基本功能正常。

**Comment by baicailio** [comment]
集成测试通过，请及时合入：
验证issuses：＃8064通过
1.试用模式下安装Deepin改为了安装deepin
2.点击安装deepin,选择全盘安装系统正常
