### ISSUE TITLE
arm64 20240419 preview镜像更新

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#8067]
**镜像地址：** https://ci.deepin.com/repo/deepin/deepin-ports/cdimage/deepin-23-beige-preview-arm64-20240419-144720.iso
**更新内容：** 内核更新 (看下面截图，单子去明道云找一下)，系统组件 dde组件更新(参考x86架构)
![企业微信截图_1713257628132](https://github.com/linuxdeepin/developer-center/assets/43427321/4e548589-d113-4dee-86d2-30df308536e9)
**关联issues：**   已集成新dock应该不存在这个问题 https://github.com/linuxdeepin/developer-center/issues/7677 
https://github.com/linuxdeepin/developer-center/issues/7464  https://github.com/linuxdeepin/developer-center/issues/7453   (截图录屏今天有新版本应该解决了 镜像未包含升级测试即可)https://github.com/linuxdeepin/developer-center/issues/7438   
```[tasklist]
### Tasks
```

**Comment by kobe337** [comment]
镜像安装失败，无法进入后配置 #8081

**Comment by Zeno-sole** [comment]
> [@Zeno-sole](https://github.com/Zeno-sole) 镜像安装失败，无法进入后配置 [#8081](https://github.com/linuxdeepin/developer-center/issues/8081) ，请排查一下问题原因哈

镜像更新：  https://ci.deepin.com/repo/deepin/deepin-ports/cdimage/deepin-23-beige-preview-arm64-20240419-172855.iso  解决https://github.com/linuxdeepin/developer-center/issues/8081

**Comment by kobe337** [comment]
@Zeno-sole 还是无法进入后配置，请排查哈

**Comment by Zeno-sole** [comment]
> @Zeno-sole 还是无法进入后配置，请排查哈

已更新内核： 
镜像地址： https://ci.deepin.com/repo/deepin/deepin-ports/cdimage/deepin-23-beige-preview-arm64-20240419-183203.iso

**Comment by kobe337** [comment]
> > @Zeno-sole 还是无法进入后配置，请排查哈
> 
> 已更新内核： 镜像地址： https://ci.deepin.com/repo/deepin/deepin-ports/cdimage/deepin-23-beige-preview-arm64-20240419-183203.iso

安装场景验证通过。

**Comment by kobe337** [comment]
https://github.com/linuxdeepin/developer-center/issues/7464 https://github.com/linuxdeepin/developer-center/issues/7453   https://github.com/linuxdeepin/developer-center/issues/7464 https://github.com/linuxdeepin/developer-center/issues/7438 回归通过
