### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【DDE】【launchpad】列表中的 添加到收藏 选项 需要去掉

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#8086]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240415/deepin-23-beige-beta3-amd64-20240415-110758.iso
dde-launchpad 0.6.3
```

### STEPS TO REPRODUCE | 复现步骤

1. 打开启动器 - 鼠标右键点击应用，查看功能选项

### OBSERVED RESULT | 观察到的结果

1. 显示了添加到收藏 
![录屏_选择区域_20240419171032](https://github.com/linuxdeepin/developer-center/assets/96416089/7095d8c4-d693-426e-b795-9e398b7344db)

### EXPECTED RESULT | 期望的结果

1. 添加到收藏 选项 需要去掉

**Comment by babyfengfjx** [comment]
@BLumia  这个要优先处理。

**Comment by BLumia** [comment]
山哥处理过了，待确认。可能应该已经集成过了。

**Comment by luodeepin** [comment]
验证失败
dde-launchpad 0.6.4
![录屏_选择区域_20240423130630](https://github.com/linuxdeepin/developer-center/assets/96416089/0a8fd6af-94c4-4b0f-957c-7d61ab603a06)

**Comment by luodeepin** [comment]
验证通过
dde-launchpad 0.6.5
![录屏_选择区域_20240423160047](https://github.com/linuxdeepin/developer-center/assets/96416089/b7a962bf-425e-4265-a4f7-dac3dfc7c82d)
