### ISSUE TITLE
登录时键盘输入密码无法登录（与 Numberlock 相关）

### ISSUE THREAD

**Issue by Playhi** [linuxdeepin/developer-center#809]
请将下方的缺陷汇报模板中的文字替换为您实际需要汇报的缺陷所对应的描述文字。

## 缺陷描述
*简明清晰的描述你所需要汇报的缺陷（BUG）*

（笔记本）登录时键盘输入密码无法登录，屏幕键盘可以登录。

## 复现步骤

*描述可以重现缺陷（BUG）的操作步骤，以便我们复现缺陷并进行修复*

（笔记本）登录时键盘输入密码无法登录，屏幕键盘可以登录。

复现步骤为:

1. 启动系统
2. 使用笔记本自带键盘输入密码
3. 密码错误

## 期望行为

*简明清晰的描述你所期望的正确行为*

成功登录

## 截图

*如果适用于你所汇报的缺陷，可以附带截图来帮助描述你所遇到的缺陷（BUG）*

## 复现环境:

*部分缺陷可能需要在特定环境下才能复现，所以请尽可能详细的提供可能导致该缺陷的环境信息*

### 发行版以及版本
2019.1.12 19:50:00 左右更新的
[如. Linux Deepin 15.7]

### 相关的软件包版本
登录
[如. dde-file-manager v1.7 (4.5.6.2-2)]

*如果你不确定是哪些包出了问题，你也可以考虑提供一个列表来描述那些你认为可能相关联的包以及它们的版本号*

### 其他内容

*描述其他任何和你所要汇报的缺陷相关的内容，以便我们定位问题并进行处理。如果没有其它信息，你也可以移除这个段落，如果必要时我们会根据实际情况询问其它细节*

- 在登录界面可以fn+numberlock，就可以登录了（也就是说先前密码输入可能是在启用了Numberlock的情况下），但是先前屏幕键盘登录以后，Numberlock状态为未开启，而再次重启后在 fn+numberlock 后使用笔记本自带键盘成功登录以后，Numberlock状态仍然为未开启。
- 不进行 fn+numberlock 的话，屏幕键盘+笔记本键盘混合输入密码也会错误（估计是键盘输入变成了u-4,o-6等等开启了Numberlock的效果）

**Comment by Playhi** [comment]
其实我昨天那次更新系统的时候就这样了，今天的更新似乎还是没修（好）。

**Comment by Playhi** [comment]
相关论坛主题帖：
- https://bbs.deepin.org/forum.php?mod=viewthread&tid=173532
- https://bbs.deepin.org/forum.php?mod=viewthread&tid=173584

**Comment by Maxximo88** [comment]
Same issue on my laptop.
If I use my keyboard it does not work, but using "Onboard virtual keyboard" I can successful login".
Please fix it.

**Comment by Playhi** [comment]
今天登录的时候，似乎又没问题了（输密码前去tty2玩了一会儿），然后满脸疑惑又重启了一次，还是没问题。【惊】【不知所措】

**Comment by justforlxz** [comment]
这个问题已经在dde-session-ui=4.8.6中解决。

**Comment by hualet** [comment]
> 今天登录的时候，似乎又没问题了（输密码前去tty2玩了一会儿），然后满脸疑惑又重启了一次，还是没问题。【惊】【不知所措】

更新修复了，先关闭了，有问题可以再打开。
