### ISSUE TITLE
[archlinux] lock on suspend only happens after resume, leaving one second of unlocked workstation

### ISSUE THREAD

**Issue by femans** [linuxdeepin/developer-center#81]
When closing the lid of the laptop, it goes into suspend. Deepin is supposed to lock the session. 
However, after opening the lid again, the computer is unlocked, and locks after about a second. Stuff can be seen and clicked. This is both a security issue and an annoyance, because it is so slow to respond after resume from suspend.

**Comment by fasheng** [comment]
Same with https://github.com/linuxdeepin/developer-center/issues/54
