### ISSUE TITLE
[Feature Request] 开放控制中心关于DImageButton的接口

### ISSUE THREAD

**Issue by iamhyc** [linuxdeepin/developer-center#810]
现在dde-control-center的导航实现是使用了DImageButton，取消了原来的插件机制；

能否开放Image Button的绘制接口和事件处理接口，可以实现 动态加载文字图片/滚轮事件/点击事件 等操作，而不只是链接到对应的module；并允许开发者加载自己的module，调整module的顺序？

这样可以在这个导航栏上实现类似插件的功能，比如MPRIS/天气/时钟（好吧其实就是动态磁贴）

**Comment by justforlxz** [comment]
导航使用的是Qt的MVC做的，并不是DImageButton，所以并不好加相关的支持。

**Comment by iamhyc** [comment]
> 导航使用的是Qt的MVC做的，并不是DImageButton，所以并不好加相关的支持。

可是初始化的时候，我看到有connect绑定了DImageButton上的click事件；
不太清楚Qt的MVC实现，但是允许 添加module+自定义DImageButton Event Handler+改变DImageButton内容 应该和导航无关吧？

**Comment by hualet** [comment]
@iamhyc 控制中心正在做新设计，所以我认为现在加这个东西并不是特别好。

**Comment by hualet** [comment]
@shule1987

**Comment by iamhyc** [comment]
还要大改啊，那我先关了这个issue之后再follow :)
