### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【系统】【loongarch64架构】【deepin ID】deepin ID登陆闪退

### ISSUE THREAD

**Issue by kobe337** [linuxdeepin/developer-center#8107]
### SUMMARY | 问题概要

关联提测单链接：https://github.com/linuxdeepin/developer-center/issues/8057  https://github.com/linuxdeepin/developer-center/issues/8062
deepin ID登陆闪退

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像： Deepin OS 23 20240418 loongarch64
内核版本：Linux deepin-PC 6.9.0-rc3-loong64-desktop #3 SMP PREEMPT Mon Apr 15 11:47:00 CST 2024 loongarch64 GNU/Linux
```

### PRE-REQUIREMENT | 预置条件

添加仓库，全量更新，仓库地址：https://github.com/linuxdeepin/developer-center/issues/8057  https://github.com/linuxdeepin/developer-center/issues/8062

### STEPS TO REPRODUCE | 复现步骤

1. 打开控制中心，进入deepin ID模块，执行登陆账号操作

### OBSERVED RESULT | 观察到的结果

deepin ID登陆闪退
https://github.com/linuxdeepin/developer-center/assets/17869922/06c3776c-b507-4916-b897-ccc716d7ae03
![loong64](https://github.com/linuxdeepin/developer-center/assets/17869922/e11d2019-435f-4a69-81c0-69515f90fd58)

### EXPECTED RESULT | 期望的结果

 1. 打开控制中心，进入deepin ID模块，执行登陆账号操作，登陆成功

**Comment by babyfengfjx** [comment]
@Zeno-sole  这个在RC发版后再进行合入。

**Comment by kobe337** [comment]
【环境】：
镜像：Deepin OS 23 20240529 loongarch64
仓库：https://github.com/linuxdeepin/developer-center/issues/8819  提测单仓库
内核：Linux deepin-PC 6.9.2-loong64-desktop #1 SMP PREEMPT Mon May 27 10:23:31 CST 2024 loongarch64 GNU/Linux

【结论】：
测试通过，暂无严重问题及影响,安装校验、版本核对。控制中心查看模块并开启，登陆等校验通过。
![image](https://github.com/linuxdeepin/developer-center/assets/17869922/c01202bb-2d92-4c99-9919-b045fa24c0f5)
![deepinid](https://github.com/linuxdeepin/developer-center/assets/17869922/b1d56f14-0d4c-47f8-83ab-944e0cd38235)
