### ISSUE TITLE
最新一次更新之后，开机无法自动挂载其它 ntfs 分区。

### ISSUE THREAD

**Issue by lolimay** [linuxdeepin/developer-center#811]
## 缺陷描述

最近一次更新之后，开机后直接打开终端无法切换到其它分区，必须要手动打开文件管理器后才能完成挂载，很影响使用体验，希望能够尽快修复。

## 复现步骤

1. 重启电脑
2. Ctrl+Alt+T 打开终端
3. cd /media/Code 提示没有此目录
4. 打开文件管理器，发现其它分区正在挂载
3.  打开终端 cd /media/Code 可以打开

## 期望行为

开机自动挂载其它分区

## 截图

无

## 复现环境:

无

### 发行版以及版本

Deepin 15.8+7?

**Comment by BLumia** [comment]
自动挂载的问题已知，是因为托盘挂载插件没有跟随 dde-dock 更新 API 版本导致因版本不匹配而没能加载托盘挂载插件。

在近期将会推送的更新中将会附带挂载插件的更新，届时会解决这个问题。

**Comment by lolimay** [comment]
#792 #793
