### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【DDE】【启动器】 启动器成功卸载应用后，桌面图标没有消失

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#8115]
### SUMMARY | 问题概要

必现问题

https://pms.uniontech.com/bug-view-252173.html

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240418/deepin-23-beige-rc-amd64-20240418-150502.iso

应用版本：dde-file-manager:6.0.45
```

### PRE-REQUIREMENT | 预置条件

发送一个应用图标到桌面

### STEPS TO REPRODUCE | 复现步骤

卸载该应用，观察桌面图标是否消失

### OBSERVED RESULT | 观察到的结果

启动器成功卸载应用后，桌面图标没有消失

![image](https://github.com/linuxdeepin/developer-center/assets/62528742/78dfc5b3-5e2a-4970-842d-ce827cccdfa7)

![截图_选择区域_20240422105902](https://github.com/linuxdeepin/developer-center/assets/62528742/e9cf2cae-c93e-4d82-bec7-09e6fcc42ba5)

### EXPECTED RESULT | 期望的结果

桌面图标跟随卸载成功消失

**Comment by babyfengfjx** [comment]
@BLumia  文管那边定位说是启动器的问题，这个要优先处理。

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240423
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.25-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
