### ISSUE TITLE
安装器 6.0.44 集成

### ISSUE THREAD

**Issue by ArchieMeng** [linuxdeepin/developer-center#8118]
### package information | 软件包信息

deepin-installer 6.0.44

### Package repository address | 软件包仓库地址

https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20240422/deepin-23-beige-rc-amd64-20240422-150947.iso

### changelog | 更新信息

安装中空间大小显示改为以GiB为单位

### test suggestion | 测试建议

观察安装界面大小单位与安装后分区实际大小。

### Sphere of influence | 影响范围

安装大小显示和计算单位。

### ADDITIONAL INFORMATION | 额外补充

理论上只是显示变化。

**Comment by babyfengfjx** [comment]
@kobe337  请开展回归验证。

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20240422/deepin-23-beige-rc-amd64-20240422-150947.iso

【结论】：
测试通过，暂无严重问题及影响，单位单词检查，安装校验。
![GIB](https://github.com/linuxdeepin/developer-center/assets/17869922/a7035f27-899f-4a71-bc4b-e9d990adf5e6)
