### ISSUE TITLE
drone management software

### ISSUE THREAD

**Issue by alvarosamudio** [linuxdeepin/developer-center#812]
I think that these two software could be added to the deepin store for the control of unmanned aerial vehicles such as drones or UAVs for their acronym in English:

1. https://docs.qgroundcontrol.com/en/getting_started/download_and_install.html
2. http://firmware.ardupilot.org/Tools/APMPlanner/beta/

the number two the beta version of this software is the version that works correctly in deepin.

**Comment by Zeno-sole** [comment]
Please pay attention to our subsequent updates, we plan to put it on the store later

**Comment by tsic404** [comment]
QGroundControl has been in appstore. APMPlanner has umet dependcenies.
