### ISSUE TITLE
Feature Request/Missed Use Case : Launch screensaver during screen lock ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#813]
Hi,

Wouldn't it be great if the screensaver was launched when `Super+L` is invoked or when its locked through the power plugin ?

**Comment by hualet** [comment]
you mean immediately?

**Comment by hualet** [comment]
@zccrs

**Comment by aiamuzz** [comment]
@hualet ...

also i have noticed that the screensaver isn't working all the time ... i can see the screen blank's out but the selected screensaver is not playing ... how can i report such a failure ?

is there any log that clearly show if the selected screensaver is playing or only a blank screen is set in after the wait time settings ?

do you want me to open a separate issue about this ?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
