### ISSUE TITLE
[Feature Request] dde-dock plugin Datetime 显示日期

### ISSUE THREAD

**Issue by CareF** [linuxdeepin/developer-center#815]
默认的 Datetime 并没有显示日期的选项. 
我做了个简单的 hack 加入了这个 feature: https://github.com/CareF/deepin-dock-plugin-datetime

merge 到 dde-dock 上改动很小: https://cr.deepin.io/#/c/dde/dde-dock/+/41288/

考不考虑一下 :)

**Comment by BLumia** [comment]
设计上不加时间的原因不明，可能是因为国际化（不同地区倾向的日期显示方式不同之类的）？还是问一下比较好。

@shule1987 @wangjia12

**Comment by CareF** [comment]
Qt 有时间显示国际化的支持 http://doc.qt.io/qt-5/qdatetime.html#toString
日期和月份哪个在前面也可以通过 Qt 的 i18n 机制实现. 
以及如果有必要的话, 加一个让用户自信输入时间格式的选项也不难.

**Comment by BLumia** [comment]
> 以及如果有必要的话, 加一个让用户自信输入时间格式的选项也不难.

实现都不难，所以需要先搞清楚之前为什么决定不增加这个支持才能讨论到底是否要添加这个特性 :joy:

**Comment by CareF** [comment]
时尚模式我没有动. 高效模式我的 hack 如下: 

![image](https://user-images.githubusercontent.com/11715538/51220708-59e11e80-1904-11e9-9d5d-269af274a59a.png)

![image](https://user-images.githubusercontent.com/11715538/51220689-48981200-1904-11e9-988d-802ceb30ea97.png)

作为可选的话, 嫌弃太占空间可以去掉嘛. 
@shule1987

**Comment by shule1987** [comment]
> 时尚模式我没有动. 高效模式我的 hack 如下:
> 
> ![image](https://user-images.githubusercontent.com/11715538/51220708-59e11e80-1904-11e9-9d5d-269af274a59a.png)
> 
> ![image](https://user-images.githubusercontent.com/11715538/51220689-48981200-1904-11e9-988d-802ceb30ea97.png)
> 
> 作为可选的话, 嫌弃太占空间可以去掉嘛.
> @shule1987

感谢你的热心,但是这无法达到我们的审美标准, 我已经在deepin的下一个大版本设计中解决了这个问题,所以不用担心未来没这个功能,  你的提交我们暂时不会合并, 如果这功能对你很重要的话你可以在你自己电脑上打好这个patch
