### ISSUE TITLE
Logo/Animation Incorrect when Starting Deepin

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#816]
## Describe the bug
The standard logo (stuffing animation) does not appear on my computer. When installing Deepin in VirtualBox - on this same computer - the animation is displayed in Deepin Virtualized normally.

The logo that appears (incorrect) flickering for a few seconds, until the system starts.
 
## To Reproduce
Starting and Stopping the Computer.

## Expected behavior
Showing the correct logo.

## Screenshots

Logo Correct:
![photo5042183750741501944](https://user-images.githubusercontent.com/45263160/51216322-29e94980-190b-11e9-8cb8-3fae0655d7dc.jpg)

Logo Incorrect:
![photo5042183750741501945](https://user-images.githubusercontent.com/45263160/51216333-3372b180-190b-11e9-9871-9ee31e3919c7.jpg)

### Distro & Version
Deepin 15.8+7

### Additional context
1. This Logo / Animation correct was only displayed when I was using Deepin 15.7 Beta.
2. There have been some tutorials in the Community promising to correct this problem. But they did not work when I followed them.

**Comment by hualet** [comment]
Your system's on SSD, right?

**Comment by tribunal2000** [comment]
Same problem here: After installing nvidia-drivers, as you know (and it is a bug!) plymouth is broken completely, but after fixing (by hands from console) it start thinkin that my system is installed at ssd. But it is not true, so I have to use console to switch plymouth.

**Comment by alexwender1** [comment]
> Your system's on SSD, right?

Yes, I've always used Deepin on SSD.

Is this logo dedicated to SSD? Ugly! As the logo appears for a few seconds... it is enough time for the standard logo... of the filling (which is gorgeous)!

**Comment by hualet** [comment]
> Same problem here: After installing nvidia-drivers, as you know (and it is a bug!) plymouth is broken completely, but after fixing (by hands from console) it start thinkin that my system is installed at ssd. But it is not true, so I have to use console to switch plymouth.

nvidia-driver really doesn't  play well with plymouth.

**Comment by hualet** [comment]
> > Your system's on SSD, right?
> 
> Yes, I've always used Deepin on SSD.
> 
> Is this logo dedicated to SSD? Ugly! As the logo appears for a few seconds... it is enough time for the standard logo... of the filling (which is gorgeous)!

Yeah, but it seems to be a bug, will fix it soon I think.

**Comment by alexwender1** [comment]
> > > Your system's on SSD, right?
> > 
> > 
> > Yes, I've always used Deepin on SSD.
> > Is this logo dedicated to SSD? Ugly! As the logo appears for a few seconds... it is enough time for the standard logo... of the filling (which is gorgeous)!
> 
> Yeah, but it seems to be a bug, will fix it soon I think.

Great!

As it is the same subject, I will not open another topic ... The animation of the cursor, needs to pay special attention. The old one (from version 15.6 and earlier, if I'm not mistaken) was well crafted and beautiful.

The current (image) besides "strange"; does not follow Deepin's design.

![img_20190118_024221__01__01](https://user-images.githubusercontent.com/45263160/51366516-2dc4c980-1acd-11e9-9285-8915d2d447c8.jpg)

**Comment by hualet** [comment]
> > > > Your system's on SSD, right?
> > > 
> > > 
> > > Yes, I've always used Deepin on SSD.
> > > Is this logo dedicated to SSD? Ugly! As the logo appears for a few seconds... it is enough time for the standard logo... of the filling (which is gorgeous)!
> > 
> > 
> > Yeah, but it seems to be a bug, will fix it soon I think.
> 
> Great!
> 
> As it is the same subject, I will not open another topic ... The animation of the cursor, needs to pay special attention. The old one (from version 15.6 and earlier, if I'm not mistaken) was well crafted and beautiful.
> 
> The current (image) besides "strange"; does not follow Deepin's design.
> 
> ![img_20190118_024221__01__01](https://user-images.githubusercontent.com/45263160/51366516-2dc4c980-1acd-11e9-9285-8915d2d447c8.jpg)

Oh, yeah, I myself don't believe that's from @shule1987 either who used to build elegant design :stuck_out_tongue_winking_eye:

**Comment by tribunal2000** [comment]
> 
> 
> > Same problem here: After installing nvidia-drivers, as you know (and it is a bug!) plymouth is broken completely, but after fixing (by hands from console) it start thinkin that my system is installed at ssd. But it is not true, so I have to use console to switch plymouth.
> 
> nvidia-driver really doesn't play well with plymouth.

Solution for ubuntu: https://www.onetransistor.eu/2016/03/plymouth-fix-nvidia.html
Solution for fedora: https://www.if-not-true-then-false.com/2015/fedora-nvidia-guide/2/

May be it will help you to fix installing drivers in deepin

**Comment by alexwender1** [comment]
@hualet, is it possible to insert this request in 15.9.2?

**Comment by hualet** [comment]
> @hualet, is it possible to insert this request in 15.9.2?

OK, since you asked :)

**Comment by aiamuzz** [comment]
> @aiamuzz It's not like a spin or progress bar, repeating is not in it's nature I think.
> 
> @shule1987

I did try looking into the folder found that it wasn't really an animation but rather individual progressive images that are being looped(played) in sequence to give it the effect of an animation ...

@hualet ... so its a programmable thing ... i just thought it would be programmed to run in a loop as well ...

**Comment by shule1987** [comment]
> > @aiamuzz It's not like a spin or progress bar, repeating is not in it's nature I think.
> > @shule1987
> 
> I did try looking into the folder found that it wasn't really an animation but rather individual progressive images that are being looped(played) in sequence to give it the effect of an animation ...
> 
> @hualet ... so its a programmable thing ... i just thought it could be programmed to run in a loop as well ...

It's not about wether it's programable or not , a loop effect is just not suitable for our progressive animation. So I don't think this would be a good idea.

**Comment by aiamuzz** [comment]
> > > @aiamuzz It's not like a spin or progress bar, repeating is not in it's nature I think.
> > > @shule1987
> > 
> > 
> > I did try looking into the folder found that it wasn't really an animation but rather individual progressive images that are being looped(played) in sequence to give it the effect of an animation ...
> > @hualet ... so its a programmable thing ... i just thought it could be programmed to run in a loop as well ...
> 
> It's not about wether it's programable or not , a loop effect is just not suitable for our progressive animation. So I don't think this would be a good idea.

oh ... ok ... well my system takes between 90-120 secs and the animation ends very fast ... hence the request ...

@shule1987 ... at least can you modify this script file to run it as a loop ... after sitting idle for 7 seconds on completion and repeating the animation

[deepin-logo.script.txt](https://github.com/linuxdeepin/developer-center/files/2816175/deepin-logo.script.txt)

I can run a customized version on my system ... if an enhancement is not preferred system wide for all ..

thanks.

**Comment by shule1987** [comment]
> > > > @aiamuzz It's not like a spin or progress bar, repeating is not in it's nature I think.
> > > > @shule1987
> > > 
> > > 
> > > I did try looking into the folder found that it wasn't really an animation but rather individual progressive images that are being looped(played) in sequence to give it the effect of an animation ...
> > > @hualet ... so its a programmable thing ... i just thought it could be programmed to run in a loop as well ...
> > 
> > 
> > It's not about wether it's programable or not , a loop effect is just not suitable for our progressive animation. So I don't think this would be a good idea.
> 
> oh ... ok ... well my system takes between 90-120 secs and the animation ends very fast ... hence the request ...
> 
> @shule1987 ... at least can you modify this script file to run it as a loop ... after sitting idle for 7 seconds on completion and repeating the animation
> 
> [deepin-logo.script.txt](https://github.com/linuxdeepin/developer-center/files/2816175/deepin-logo.script.txt)
> 
> I can run a customized version on my system ... if an enhancement is not preferred system wide for all ..
> 
> thanks.

It's not normal that your  system takes more than 90 seconds to boot, that's  defently a bug @hualet

**Comment by aiamuzz** [comment]
> It's not normal that your system takes more than 90 seconds to boot, that's defently a bug @hualet

yep @shule1987 ... that's a fact ... i almost dose off ... :sleeping: ... waiting for the login screen ... hence the looped animation request to keep me awake ... :smile:

**Comment by alexwender1** [comment]
I'll reopen the request.

The logo - not so polished - still present in the 15.10 stable. As well, the cursor animation has not been corrected either.
