### ISSUE TITLE
[Feature request] File Manager 更智能的 auto mount

### ISSUE THREAD

**Issue by CareF** [linuxdeepin/developer-center#817]
使用情景如下: 
双系统, 出于安全考虑没有把 Win 的 C 盘分区写入 fstab. 然而每次打开 file manager 都会索要管理员密码试图挂载 Win 分区. 取消设置中的 auto mount 选项则会不再自动挂载移动设备. 

是不是可能多一个智能选项, 实现: 
1. 只自动挂载移动设备
2. 手动 umount 的设备不再自动挂载
3. 不自动挂载需要额外权限的设备

**Comment by BLumia** [comment]
事实上开机自动挂载的过程中（准确的说，dock 挂载插件）就不会处理需要权限才能挂载的分区（文管的自动挂载则是刻意询问密码的），另外手动卸载的设备不再自动挂载的话，误操作的撤销可能也是需要考虑的地方。交互逻辑应该会复杂很多。

cc: @wangjia12 

---------

@hualet 看板 bot 考虑加一个如果标题有 feat req 字样就自动 assign @wangjia12 的功能？

**Comment by hualet** [comment]
@electricface  ^

**Comment by electricface** [comment]
还是算了吧

**Comment by wangjia12** [comment]
@BLumia 这是前几天你说你需要去调研一下挂载设备的问题吗？如果有结论在这里回复一下。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
