### ISSUE TITLE
Auto mount implementation ! ... Is it a good design ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#818]
Hi,

@hualet ... @BLumia ...

The current implementation of auto-mounting partitions which depends on the disk dock plugin ... Is it a good design ???

As i have come to know recently that that plugins are not forward compatible ... is it a good idea/design to let the auto-mounting of partition disks rely on a plugin ?

**Auto-mounting is a mainstream and important task ... for instance i have 95% of my flatpaks on a separate partition ... also my bash scripts are on a separate partition ... failure in this system will result on failed scripts and programs added to startup.**

Is making a mainstream and important task such as auto-mounting partition disks a slave to a plugin(a sideloaded and unimportant object from the user perspective) a good design decision ? ... PLUS ... given the lack of forward compatibility of the plugin API this issue is bound to repeat every time the plugin API undergoes changes.

**Wouldn't it be a better approach to liberate a mainstream auto-mounting operation/mechanism from having to rely on a secondary system such as a plugin ???**

**Comment by hualet** [comment]
Yeah, it's a thing worth a rethinking.

**Comment by lolimay** [comment]
+1

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
