### ISSUE TITLE
Lack of forward compatibility to perfectly operational plugins against 'plugin API' changes ...  a good design decision ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#819]
@hualet ... @BLumia ...

As i have come to know recently that that plugins are not forward compatible ... meaning perfectly functional plugins will stop working just because the 'plugin API' underwent some changes !

Plugins that are perfectly running being shutdown each time the 'plugin API undergoes changes is not the right way ?

Is it so difficult or impossible to provide compatibility to plugins developed on older versions of the 'plugin API' ?

Sooner or later this may have to be supported ... **we all know plugins are small pieces of software that will not undergo a lot of changes from one version to another ... you can have a perfectly functional plugin which may never have to be developed any further** ... and the current issue of compatibility will decommission it because of the current plugin desgin ecosytem ...not to forget it is unnecessary burden to the plugin devs ... forcing them to redo their code just to accommodate an update to its API will be very discouraging and could impact by depleting the plugin collection in the long run !!!

**Comment by hualet** [comment]
Please see this: https://github.com/linuxdeepin/internal-discussion/issues/840

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
