### ISSUE TITLE
[Deepin Integration]~[V23-Release] docker.io deepin-community/docker.io by zeno

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#8194]
### Package information | 软件包信息

包名 | 版本
--  | --
docker.io | 20.10.25+dfsg1-2deepin1

### Package repository address | 软件包仓库地址

    deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1309/testing/ ./

#### docker.io  (20.10.25+dfsg1-2deepin1) unstable; urgency=medium

  *fix: DM - skip test for pbuilder and OBS: Can't find mount point of /.

**Comment by Zeno-sole** [comment]
**Integration Test Info**
### Test suggestion | 测试建议
docke.io系列软件包，已支持仓库全架构(amd64 arm64 loong64 riscv64 i386)，验证amd64 arm64 loong64 riscv64 架构docker.io常用场景


### Influence | 影响范围
docker.io相关

### ADDITIONAL INFORMATION | 额外补充

**Comment by babyfengfjx** [comment]
@kobe337  请开展集成验证。

**Comment by kobe337** [comment]
amd: 验证通过
1、安装校验、版本核对
2、搜索镜像，拉取官方镜像
3、创建容器，启动容器，官方拉取镜像部署nginx, 映射本地端口为8080,通过网页进行访问
![x86版本信息核对](https://github.com/linuxdeepin/developer-center/assets/17869922/2de6d00b-12e6-4cda-8b81-3baa1ed498e3)
![搜索镜像](https://github.com/linuxdeepin/developer-center/assets/17869922/ec888f4e-e111-4050-a1bb-20eba90065f6)
![拉取镜像](https://github.com/linuxdeepin/developer-center/assets/17869922/32860cb0-8c1e-481d-9f2f-a0e687394fce)
![docker8080](https://github.com/linuxdeepin/developer-center/assets/17869922/6fa191d1-d245-4352-9a1f-ce45af42033c)

**Comment by kobe337** [comment]
loong64: 验证通过
1、安装校验、版本核对
2、拉取镜像、创建容器
3、导入镜像、创建容器、进入容器
![loong64版本信息核对](https://github.com/linuxdeepin/developer-center/assets/17869922/5f9d9577-861c-4409-be11-20e4ea08e83b)
![loong64拉取镜像](https://github.com/linuxdeepin/developer-center/assets/17869922/a391536a-fd46-4faa-822c-e65d006650e3)
![创建容器](https://github.com/linuxdeepin/developer-center/assets/17869922/8e2a11cf-a786-4be7-8232-dab5580775c9)
![导入镜像，创建容器，进入容器](https://github.com/linuxdeepin/developer-center/assets/17869922/680db667-203b-4009-867f-fae4b3f4ab5a)

**Comment by kobe337** [comment]
arm64: 验证通过
【环境】：
镜像：Deepin OS-23-20240419102654-1_aarch_64
仓库：提测单仓库
内核：Linux deepin-PC 5.10.0-arm64-desktop #23.00.00.20 SMP PREEMPT Fri Apr 19 18:05:07 CST 2024 aarch64 GNU/Linux

【结论】：
测试通过，暂无严重问题及影响
1、安装校验、版本核对
2、拉取镜像、创建容器
3、导入镜像、创建容器、进入容器
4、重启设备后，启动容器，查看状态
![arm版本信息](https://github.com/linuxdeepin/developer-center/assets/17869922/7737eb66-2913-4fd2-ade3-b5c3ef2aa7b6)
![arm拉取镜像](https://github.com/linuxdeepin/developer-center/assets/17869922/75b1911e-0256-4869-89ab-145610fe577c)
![arm导入镜像](https://github.com/linuxdeepin/developer-center/assets/17869922/c3203585-acf5-4305-8efb-39dd1273a455)
![armnginx](https://github.com/linuxdeepin/developer-center/assets/17869922/8a9841b9-a1c6-4a51-81d7-ca1391280e99)

**Comment by kobe337** [comment]
riscv64: 验证通过
【环境】：
[Version] 
SystemName=Deepin
SystemName[zh_CN]=深度操作系统
ProductType=Desktop
ProductType[zh_CN]=桌面
EditionName=Community
EditionName[en_US]=Community(Preview)
EditionName[zh_CN]=社区版(Preview)
MajorVersion=23
MinorVersion=23
OsBuild=21235.101

仓库：提测单仓库
内核：Linux deepin-romadc 5.15.0 #1 SMP Thu Sep 21 16:21:19 GMT 2023 riscv64 GNU/Linux

【结论】：
测试通过，暂无严重问题及影响
1、安装校验、版本核对
2、导入镜像、创建容器、进入容器，查看容器状态
![riscv版本信息](https://github.com/linuxdeepin/developer-center/assets/17869922/35a9a9f3-9049-46ce-897a-84a84946e2dc)
![导入镜像](https://github.com/linuxdeepin/developer-center/assets/17869922/e3e274e3-9d67-4692-baff-7e4491136ee8)
