### ISSUE TITLE
blurred backgrounds for greeter and launcher

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/developer-center#82]
Can I please ask for your help and advice with the new way you are using the blurred images for the greeter and launcher background? @fasheng @sbwtw @hualet 
I see that you have now created a new wallpaper package with separate blurred versions...
How does this work?
I have been using a custom manjaro package (of the same name **deepin-wallpapers** ;) ) all the time with most of the Deepin stock wallpapers plus some more.
I am lost about a way to handle this now.
How to create these blurred versions? How does the naming of these files work?
How can users add their own custom wallpapers now? Not at all?
Please help. Thank you.

**Comment by oberon2007** [comment]
Hah, meanwhile since I had the original Deepin wallpaper package installed I realized that blurred versions of new wallpapers are indeed auto-created - it just took very long... :stuck_out_tongue_winking_eye:

**Comment by hualet** [comment]
Ah, it's just the original version, we'll keep optimizing the blurred image generator. @oberon2007

**Comment by oberon2007** [comment]
Ok I see, thanks :smiley:
