### ISSUE TITLE
锁屏界面的多屏支持: 新的屏幕不在锁屏界面

### ISSUE THREAD

**Issue by CareF** [linuxdeepin/developer-center#820]
请将下方的缺陷汇报模板中的文字替换为您实际需要汇报的缺陷所对应的描述文字。

## 缺陷描述

在锁屏界面插上外接显示屏的时候, 外接屏幕会显示桌面内容而不是锁屏界面. 而插着外接屏进入锁屏界面则副屏是模糊桌面. 前面的这个行为疑似设计缺陷. 

## 复现步骤

先将多屏设置为 extend mode
无外接显示器的时候 win+L 进入锁屏界面. 接上外接显示器, 此时副屏上显示锁定之前的内容. 

## 期望行为

在锁屏界面插上外接显示器后, 显示应该和插着外接显示器时进入锁屏界面一样. 

## 复现环境:

extend mode, 外接和笔记本内置屏幕做主屏效果一样. 

### 发行版以及版本

Arch Linux

### 相关的软件包版本

所有相关包都已更新到官方源最新版本

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/41386/

**Comment by liuwen123** [comment]
+1
