### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【DDE】【任务栏】【UI】flow主题 和 bloom主题的，应用和启动器图标显示错误

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#8206]
### SUMMARY | 问题概要

需要开发与设计进行核对，在调试时建议给设计现场查看效果

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
dde-shell 0.0.11
```

### STEPS TO REPRODUCE | 复现步骤

1. 在控制中心 - 个性化 - 设置 主题为 flow主题 和 bloom主题 ，查看任务栏显示的 应用和启动器图标

### OBSERVED RESULT | 观察到的结果

1. 应用和启动器图标显示错误
![企业微信截图_17139438603783](https://github.com/linuxdeepin/developer-center/assets/96416089/517ba210-5607-4d61-98be-d30706b37519)

### EXPECTED RESULT | 期望的结果

1. 应用和启动器图标显示正确

**Comment by babyfengfjx** [comment]
@kegechen  这个设计说发版前要解决，优先安排。

**Comment by kegechen** [comment]
@BLumia dde-shell的launcheritem安装了一个默认dci图标，切换bloom时使用的是这个

**Comment by kegechen** [comment]
@tsic404 集成别忘了写这个

**Comment by tsic404** [comment]
上面机器人带上了

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240425
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.25-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
