### ISSUE TITLE
安装器 6.0.45 集成申请

### ISSUE THREAD

**Issue by ArchieMeng** [linuxdeepin/developer-center#8207]
### package information | 软件包信息

deepin-installer 6.0.45

### Package repository address | 软件包仓库地址

https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20240424/deepin-23-beige-rc-amd64-20240424-155104.iso

### changelog | 更新信息

https://github.com/linuxdeepin/developer-center/issues/7546

### test suggestion | 测试建议

无

### Sphere of influence | 影响范围

创建用户界面的语言勾选

### ADDITIONAL INFORMATION | 额外补充

无

**Comment by xuqi27837288** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240423
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.25-amd64-desktop-hwe
【结论】：
测试通过，暂无严重问题及影响
