### ISSUE TITLE
libappindicator problem

### ISSUE THREAD

**Issue by tribunal2000** [linuxdeepin/developer-center#822]
## Describe the bug

System tray icons of steam and telegram doesn't work correctly

## To Reproduce

Install steam and telegram (seems that steam version is blocking system LMB click)

## Expected behavior

System tray works correctly

Deepin 15.9

### Additional context

It is about RMB click blocks LMB click.
Problem can be fixed with manipulations with libappindicator (solution was found in russian telegram group)

**Comment by mikield** [comment]
LBM click opens context menu of telegram. (the same behavior as RBM click)

**Comment by vasiliu4556789** [comment]
Английским не владею, в общем проблема  в индикаторе который ставится с некоторым софтом. Его функция добавить правый клик ,но он при этом блокирует левый . Подробнее на видео.
https://drive.google.com/file/d/1m4R45XXY6uMr8-Kv1uTOYBZkQVyot_0_/view?usp=sharing

**Comment by tribunal2000** [comment]
Here is my translation:
The problem is in libindicator, that is installed as dependency with some software. His function is to add RMB to software who can't do it from clean install. After it software like steam can use RMB, but it blocks LMB. More info in video

**Comment by vasiliu4556789** [comment]
![2019-01-18_14-56](https://user-images.githubusercontent.com/46813907/51385778-4a92e880-1b31-11e9-978c-4966bd9c99a0.png)
у дебиана  2 зависимости

**Comment by mikield** [comment]
Also.

Arch linux. When i have libindicator installed - I have 2 icons of discord in my tray.

@hualet is that errors related to deepin? :)

**Comment by listenerri** [comment]
> Английским не владею, в общем проблема в индикаторе который ставится с некоторым софтом. Его функция добавить правый клик софту который этого не умеет,но он при этом блокирует левый . Подробнее на видео. Телеграм в ходит в поддержку этого индикатора,хотя давно уже и не нуждается.
> https://drive.google.com/file/d/1m4R45XXY6uMr8-Kv1uTOYBZkQVyot_0_/view?usp=sharing
> https://t.me/deepinru/23368

Deleting library files does not seem to be a good way to solve this problem.
Since telegram can works normally without installing libappindicator(or something like this pkg), maybe we should open an issue to telegram to solve this problem.

**Comment by listenerri** [comment]
In addition, we have already dealt with similar problems, since libappindicator does not work normally under the newer tray protocol: [SNI](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/), such as clicking the left mouse button does not respond, we patched libappindicator to make it no longer provide SNI support on our system(only deepin).
As a result, a right-click menu will pop up when clicking with the left mouse button, so this has not completely solved the problem. : (

**Comment by tribunal2000** [comment]
> Not sure, have you tried that on other DEs support SNI, Plasma for example?

Tested in Kubuntu 18.10 with Plasma 15.4
libindicator and libappindicator doesn't installed at all

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
