### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【DDE】【任务栏】多任务视图的 tips提示显示错误

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#8225]
### SUMMARY | 问题概要

关联集成：https://github.com/linuxdeepin/developer-center/issues/8210

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
dde-shell 0.0.12
```

### STEPS TO REPRODUCE | 复现步骤

1. 将鼠标放置在任务栏多任务视图图标上，查看tips提示

### OBSERVED RESULT | 观察到的结果

1. 提示为 打开工作区
![8225](https://github.com/linuxdeepin/developer-center/assets/96416089/31febea9-cc7b-42a7-acfc-b922bd1c4d60)

### EXPECTED RESULT | 期望的结果

1. 提示为多任务栏视图

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240425
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.25-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
