### ISSUE TITLE
【deepin_V23_Release】【严重】【立即】【预发布测试】【DDE】【任务栏】任务栏点击多任务视图 高概率发生系统卡死

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#8227]
### SUMMARY | 问题概要

任务栏点击多任务视图 高概率发生系统卡死

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240423/ 
版本：dde-shell:0.0.10
```

### PRE-REQUIREMENT | 预置条件

安装上述最新镜像

### STEPS TO REPRODUCE | 复现步骤

1.打开任意应用窗口
2.在任务栏点击多任务视图
3.观察系统现象

### OBSERVED RESULT | 观察到的结果

1.任务栏点击多任务视图 高概率发生系统卡死

Uploading video(47).mp4…

### EXPECTED RESULT | 期望的结果

1.多任务视图正常点击，系统不会卡死

**Comment by babyfengfjx** [comment]
@tsic404  这个要优先处理。

**Comment by justforlxz** [comment]
![wecom-temp-8136358-e61ae2208bd16a99124680fdd4225c8b](https://github.com/linuxdeepin/developer-center/assets/12298476/d11b78f1-db41-4463-880e-b4b3a853f3f9)

**Comment by baicailio** [comment]
镜像1：https://cdimage.uniontech.com/community/releases/23-Beta3/ 升级到最新的RC内测版本(2024.04.30)
镜像2：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240430/
仓库：
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1363:/dde/testing/ ./
验证步骤：提单步骤
验证现象：任务栏打开多任务视图正常（持续一周时间观察），此单关闭
验证结果：回归通过
