### ISSUE TITLE
[Feature request] 增加对 IPv6 镜像源的支持

### ISSUE THREAD

**Issue by lolimay** [linuxdeepin/developer-center#823]
高校用户校园网 IPv4 限速，使用 IPv6 镜像源速度要快十几倍。deepin 控制中心的镜像源暂无 IPv6 镜像源，只好自己修改 source.list 文件:
````bash
## Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin panda main contrib non-free
# 清华IPv6镜像源
deb [by-hash=force] https://mirrors6.tuna.tsinghua.edu.cn/deepin panda main contrib non-free 
deb-src http://packages.deepin.com/deepin panda main contrib non-free
````
希望官方能够原生支持 IPv6 镜像源，并且**智能镜像源**功能要考虑到 IPv6 镜像源通常更适合高校用户使用。

More info, see：
1. [清华大学开源软件镜像站 - IPV6](https://mirrors6.tuna.tsinghua.edu.cn/)
2. [USTC Open Source Software Mirror - IPv6](http://ipv6.mirrors.ustc.edu.cn/)
3. [上海交通大学镜像站 - IPv6](http://ftp6.sjtu.edu.cn/)
4. [北京理工大学开源镜像站 -IPv6](http://mirror.bit6.edu.cn/web/)
5. [浙江大学开源镜像站 - IPv4+IPv6](http://mirrors.zju.edu.cn/)
6. [兰州大学开源镜像站 - IPv4+IPv6](http://mirror.lzu.edu.cn/)
7. [北京交通大学 - IPv4+IPv6](https://mirror.bjtu.edu.cn/)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
