### ISSUE TITLE
【deepin_V23_Release】【一般】【有空】【预发布测试】【DDE】【任务栏】多次修改任务栏状态时，一直隐藏和一直显示均显示 勾

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#8231]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
dde-shell 0.0.12
```

### STEPS TO REPRODUCE | 复现步骤

1. 将任务栏状态设置为 一直隐藏 ， 在设置为一直显示，再设置为一直隐藏，查看状态勾选显示

### OBSERVED RESULT | 观察到的结果

一直隐藏和一直显示均显示 勾
![录屏_选择区域_20240425142527](https://github.com/linuxdeepin/developer-center/assets/96416089/a8d08c62-b26e-418d-b64a-51d1e170a6dc)

### EXPECTED RESULT | 期望的结果

只有一直隐藏显示 勾

**Comment by babyfengfjx** [comment]
@tsic404  有余力分析处理。

**Comment by tsic404** [comment]
应该同 https://github.com/linuxdeepin/developer-center/issues/8038

**Comment by luodeepin** [comment]
验证通过
dde-shell 0.0.15
![录屏_选择区域_20240507132850](https://github.com/linuxdeepin/developer-center/assets/96416089/af97fb7b-4ea3-4102-b7eb-821fb11b76fc)
