### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【 窗口管理器】影院播放时，边角均新增了透明的角

### ISSUE THREAD

**Issue by kobe337** [linuxdeepin/developer-center#8236]
### SUMMARY | 问题概要

影院播放时，边角均新增了透明的角

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240425/
```

### STEPS TO REPRODUCE | 复现步骤

1. 使用影院应用播放视频，查看界面展示

### OBSERVED RESULT | 观察到的结果

影院播放时，边角均新增了透明的角
![圆角1](https://github.com/linuxdeepin/developer-center/assets/17869922/13cc0ad8-44d3-486f-b2ba-335c24f73797)

### EXPECTED RESULT | 期望的结果

影院播放时，边角正常展示

**Comment by babyfengfjx** [comment]
@justforlxz  这个优先看一下。

**Comment by justforlxz** [comment]
无复现该问题。

**Comment by kobe337** [comment]
镜像验证存在问题，后续使用集成镜像进行验证

**Comment by kobe337** [comment]
验证通过
【环境】：
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240509/deepin-23-beige-rc-amd64-20240509-120442.iso 
内核：Linux deepinb3-PC 6.6.25-amd64-desktop-hwe #23.01.00.25 SMP PREEMPT_DYNAMIC Wed Apr 10 21:20:25 CST 2024 x86_64 GNU/Linux

【结论】：
回归测试通过，暂无严重问题及影响，打开影院播放视频，观察界面状态正常
