### ISSUE TITLE
【deepin_V23_Release】【严重】【立即】【预发布测试】【 DDE】uos-ai未在任务栏上进行展示

### ISSUE THREAD

**Issue by kobe337** [linuxdeepin/developer-center#8247]
### SUMMARY | 问题概要

uos-ai未在任务栏上进行展示

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240425/
```

### STEPS TO REPRODUCE | 复现步骤

1. 进入桌面环境，查看任务栏上插件区域，检查uos-ai的状态

### OBSERVED RESULT | 观察到的结果

uos-ai未在任务栏上进行展示
![uos-ai](https://github.com/linuxdeepin/developer-center/assets/17869922/f5801787-8b54-4dec-891b-cca4dd730b6f)
使用命令uos-ai-assistant -c可以唤起
![symlkyhq](https://github.com/linuxdeepin/developer-center/assets/17869922/2bdb9097-24b8-468e-a001-44156b448864)

### EXPECTED RESULT | 期望的结果

uos-ai在任务栏上进行展示

**Comment by ssk-wh** [comment]
插件未进行适配移植

**Comment by luodeepin** [comment]
@kobe337 请在 https://github.com/linuxdeepin/developer-center/issues/8302 中进行回归验证

**Comment by kobe337** [comment]
验证通过
【环境】：
镜像：Deepin OS-23-20240425052752-1_x86_64
仓库：[#8302](https://github.com/linuxdeepin/developer-center/issues/8302) 提测单仓库
内核：Linux deepin-PC 6.6.25-amd64-desktop-hwe #23.01.00.25 SMP PREEMPT_DYNAMIC Wed Apr 10 21:20:25 CST 2024 x86_64 GNU/Linux

【结论】：
测试通过，暂无严重问题及影响
![uos-ai（副本）](https://github.com/linuxdeepin/developer-center/assets/17869922/e1cc82e4-3cf0-49b1-bd33-654426d821cd)
