### ISSUE TITLE
【deepin_V23_Release】【一般】【正常】【预发布测试】【 DDE】【控制中心】语言和区域中的弹框数据与外面的显示页面数据不一致

### ISSUE THREAD

**Issue by baicailio** [linuxdeepin/developer-center#8248]
### SUMMARY | 问题概要

语言和区域中的区域格式数据与外面的显示页面数据不一致

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240425/
```

### PRE-REQUIREMENT | 预置条件

无

### STEPS TO REPRODUCE | 复现步骤

1.语言设为中文简体，点击语言和区域，观察弹框数据

### OBSERVED RESULT | 观察到的结果

弹框数据显示的是英文时区，外面的页面显示的是中文时区，详见图中标注的2和3
![时区问题](https://github.com/linuxdeepin/developer-center/assets/166582166/8d1e4a57-0d24-49f9-81a1-e2beaa6640a2)

### EXPECTED RESULT | 期望的结果

弹框数据与外面页面的数据一致

**Comment by babyfengfjx** [comment]
@kegechen  有余力可以处理。

**Comment by xuqi27837288** [comment]
【验证环境】：v23 RC镜像
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240514
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.25-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
