### ISSUE TITLE
【deepin_V23_Release】【严重】【立即】【预发布测试】【玲珑】ll-cli install 安装的玲珑应用在启动器没有图标显示

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#8249]
### SUMMARY | 问题概要

ll-cli install 安装的玲珑应用在启动器没有图标显示
关联集成：#8190

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240425/
版本：dde-shell:0.0.10
```

### PRE-REQUIREMENT | 预置条件

安装上述最新镜像

### STEPS TO REPRODUCE | 复现步骤

1.升级linglong-bin到1.0.5-1
2.ll-cli search . (搜索可以安装的玲珑应用)
3.ll-cli linstall org.videolan.vlc
4.安装成功后在启动器查找vlc应用图标

### OBSERVED RESULT | 观察到的结果

1.ll-cli install 安装的玲珑应用在启动器没有图标显示
![截图_选择区域_20240425164938](https://github.com/linuxdeepin/developer-center/assets/96415804/9cf0e403-e43c-4f5a-ba41-708b931977e4)

### EXPECTED RESULT | 期望的结果

1.应用在启动器有图标展示

**Comment by babyfengfjx** [comment]
@dengbo11  这个要优先处理。

**Comment by kamiyadm** [comment]
已经修复，推送至内网 old仓库

**Comment by vivianxf** [comment]
验证镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240430/
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1368:/dde/testing/ ./
版本：linglong:1.5.0-1
验证步骤：提单的步骤
验证现象：ll-cli install 安装的应用有图标显示
验证结果：通过
![截图_选择区域_20240507133646](https://github.com/linuxdeepin/developer-center/assets/96415804/43bdd8a4-abb9-4722-a679-d5bb5f98536a)
