### ISSUE TITLE
文件管理器删除文件的问题（多块硬盘）

### ISSUE THREAD

**Issue by FurryWolfX** [linuxdeepin/developer-center#826]
## 缺陷描述

多块硬盘情况下，当第二块硬盘删除文件，文件会移动到系统盘 `/home/username/.local/share/Trash/files` 里面。

这样做移动文件的效率很低，而且会导致系统盘占用越来越大，为什么不移动到当前硬盘的回收站？

## 复现步骤

非系统盘删除文件时出现

## 期望行为

移动到当前硬盘的回收站

### 发行版以及版本

Linux Deepin 15.9

### 相关的软件包版本

dde-file-manager 4.7.4.4

**Comment by FurryWolfX** [comment]
还有个问题，多块硬盘自动挂载时，自动挂载参数中包含（noexec），导致第二块硬盘上的应用无法执行！

**Comment by BLumia** [comment]
移动硬盘回收站这个是已知的，后续会改这个行为。感谢报告问题。

`noexec` 是之前特意加的，我们已经在 Deepin 15.9 的更新中移除了这个特性，请及时更新系统。另外为了帮助缺陷可以更方便的跟踪，请尽可能保证一个 issue 里只讨论特定的一个问题，如果有多个问题可以开多个 issue ;-)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
