### ISSUE TITLE
【deepin_V23_Release】【严重】【立即】【预发布测试】【玲珑】ll-cli install 安装的应用用ll-cli run命令启动报错

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#8262]
### SUMMARY | 问题概要

ll-cli install 安装的应用用ll-cli run命令启动报错
关联集成：https://github.com/linuxdeepin/developer-center/issues/8190
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240425/
版本：dde-shell:0.0.10
```

### PRE-REQUIREMENT | 预置条件

安装上述最新镜像

### STEPS TO REPRODUCE | 复现步骤

1.ll-cli linstall org.xfce.gigolo
2.安装成功后ll-cli run org.xfce.gigolo 运行
3.观察结果输出

### OBSERVED RESULT | 观察到的结果
io.githubtictactoe 启动失败

1.ll-cli install 安装的应用用ll-cli run命令启动报错
![截图_选择区域_20240426112800](https://github.com/linuxdeepin/developer-center/assets/96415804/50786d78-a520-496f-a465-ab973f99f5f7)

### EXPECTED RESULT | 期望的结果

1.安装成功的程序运行成功

**Comment by dengbo11** [comment]
@myml, 看下是不是foundation 里面的glibc 版本不对

**Comment by chenchongbiao** [comment]
使用的 org.deepin.foundation 版本存在问题，使用 org.deepin.foundation=23.0.0.25 的版本后正常，需要 ll-cli uninstall org.xfce.gigolo 卸载旧应用，ll-cli install org.xfce.gigolo,就会重新拉取新版本的应用。需要等玲珑仓库同步到外网。

**Comment by vivianxf** [comment]
玲珑仓库同步到外网后，指派验证

**Comment by vivianxf** [comment]
验证镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240430/
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1368:/dde/testing/ ./
版本：linglong:1.5.0-1
验证步骤：提单的步骤
验证现象：ll-cli run 应用可以成功启动
验证结果：通过
