### ISSUE TITLE
dde-open 需支持 trash:// 与 computer:// 协议

### ISSUE THREAD

**Issue by BLumia** [linuxdeepin/developer-center#8266]
相关 Issue 关联：

- https://github.com/linuxdeepin/developer-center/issues/8180
- https://github.com/linuxdeepin/developer-center/issues/8146

相关问题（下面列出的是实质完全相同的问题）：

- 从 launchpad 点左侧的文管相关图标打开文管时，任务栏图标不正确
- 使用 DTKGui 提供的 showFolder() 接口打开文件夹，任务栏图标不正确
- 使用 freedesktop filemanager1 dbus 打开文件夹，任务栏图标不正确

处理方案建议：

~~1. 文管打开回收站、计算机的快捷方式从使用 gio-open 调整为使用 xdg-open~~
~~2. dde-open 主动支持 `trash://` 与 `computer://` 协议，正确唤出当前默认的文管来显示文件~~

请参阅 https://github.com/linuxdeepin/developer-center/issues/8266#issuecomment-2081408335

**Comment by tsic404** [comment]
一、 DBUS 适配

  - 从 launchpad 点左侧的文管相关图标打开文管时，任务栏图标不正确
  - 使用 DTKGui 提供的 showFolder() 接口打开文件夹，任务栏图标不正确
  - 使用 freedesktop filemanager1 dbus 打开文件夹，任务栏图标不正确
  
  三者 是由于文官进程是通过一个 dde-filemanger-server的 dbus 进程拉起。所以文管的dbus激活方式需要适配新的AM。
  
  步骤（参考[控制中心适配方式](https://github.com/linuxdeepin/dde-control-center/commit/ec9eb61bbf751be5485642359aec1adf79c5bf63)）：
  1. 将 server 的激活方式从 dbus 拉起，改成通过 systemd 拉起。
  2. 使用 systemd 激活对应的 dbus 集成时的服务名与 desktopId (desktopfile name) 保持一致。

二、desktop文件适配

  dde-open 添加 trash:/// 和 computer:/// 的支持，是为了（文管/回收站/计算机）desktop文件的适配，需要将原有的 `gio open trash:///` 或者 `gio open computer:///` 改成 `xdg-open trash:///` `xdg-open computer:///`
  
  文管修改desktop文件后，需要20系统`dde-open`也添加上面协议的支持，否则文管需要为20/23分别维护desktop文件。

**Comment by asterwyx** [comment]
已完成。
