### ISSUE TITLE
【deepin_V23_Release】【一般】【有空】【预发布测试】【玲珑】ll-builder build 拉代码时，进度展示不稳定，乱跳

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#8268]
### SUMMARY | 问题概要

ll-builder build 拉代码时，进度展示不稳定
关联集成：https://github.com/linuxdeepin/developer-center/issues/8190

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240425/
版本：dde-shell:0.0.10
```

### PRE-REQUIREMENT | 预置条件

安装上述最新镜像

### STEPS TO REPRODUCE | 复现步骤

1.sudo apt install linglong-builder
2.ll-builder build
3.观察拉取进度展示

### OBSERVED RESULT | 观察到的结果

1.ll-builder build 拉代码时，进度展示不稳定

https://github.com/linuxdeepin/developer-center/assets/96415804/d4e94bf8-753c-4522-b252-442ad8dfd912

### EXPECTED RESULT | 期望的结果

1.ll-builder build 拉代码时，进度展示保持稳定，持续递增

**Comment by dengbo11** [comment]
@kamiyadm , 这个问题帮忙看下

**Comment by kamiyadm** [comment]
实际上没有乱跳，只是拉了两个东西，但是没有区分https://github.com/linuxdeepin/linglong/pull/399

**Comment by vivianxf** [comment]
验证镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240722/
验证仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1785/testing/ ./
linglong-bin:1.5.8-1
验证步骤：提单的步骤
验证现象：进度条展示正常
验证结果：通过
![截图_选择区域_20240725135246](https://github.com/user-attachments/assets/0eae4e8c-76ff-41c1-a8e2-e0679e0ed5db)
