### ISSUE TITLE
切换主屏幕时, dock 并没有立刻重新绘制

### ISSUE THREAD

**Issue by CareF** [linuxdeepin/developer-center#827]
## 缺陷描述

将外接显示器设置为主屏幕. 在插入外接显示器后, 其他主屏幕上的窗口转移到外接显示器上, 主屏幕上 dock (未设置隐藏) 的空间留出来了, dock 本身出现在原来的位置, 直到鼠标划过 dock. 疑似 dock 没有正确处理主屏幕切换事件. 

## 复现步骤

同上. 将外接显示器设置为主屏幕后插入外接显示器. 
Dock 为高效模式, 从不隐藏. 

## 期望行为

dock 应该和其他窗口一起转移到主屏幕显示. 

## 截图

*如果适用于你所汇报的缺陷，可以附带截图来帮助描述你所遇到的缺陷（BUG）*
![image](https://user-images.githubusercontent.com/11715538/51334813-9c167700-1a4e-11e9-94b8-7c6cfe347e2e.png)

(dock 在另一个屏幕上)

## 复现环境:

Arch Linux 20190117

### 发行版以及版本

Arch Linux 20190117

### 相关的软件包版本

软件包均已更新到最新

### 其他内容

无

**Comment by CareF** [comment]
@wangjia12 不是很确定应该找谁.. 但这个看上去不像是应该很难定位的 bug...

**Comment by listenerri** [comment]
这是个已知问题，不过一直很难重现，以前尝试修复的时候就无法重现，所以当时只是改动了可疑未知的代码，尽量避免这个问题，看来是没有完全解决的

@CareF 你那里是稳定复现的吗？

**Comment by CareF** [comment]
是的。每次启用外接显示器都是这样，从不例外。我能提供什么帮助复现？

**Comment by listenerri** [comment]
> 是的。每次启用外接显示器都是这样，从不例外。我能提供什么帮助复现？

麻烦你再把复现步骤描述一下

**Comment by CareF** [comment]
外接显示器是默认设置 (应该是自动记忆上一次设置的), 所以现在插入HDMI的时候, 会自动发生主屏幕切换. 

deepin-control-center 4.9.6-1
deepin-dock 4.9.0-1

**Comment by CareF** [comment]
![image](https://user-images.githubusercontent.com/11715538/54207852-4fc93f80-44b1-11e9-9cd8-e9a71c9307c8.png)
If it may help.

**Comment by CareF** [comment]
![image](https://user-images.githubusercontent.com/11715538/54220485-e4d73300-44c7-11e9-9457-a6c058e0133c.png)

**Comment by listenerri** [comment]
@CareF 我这边 deepin 的机器按照你的方法设置依然不能重现，等下我找个 arch 试一试

**Comment by CareF** [comment]
会不会是和显卡驱动有关系...?

**Comment by listenerri** [comment]
> 会不会是和显卡驱动有关系...? 可能相关的驱动包括:
> xf86-video-intel 1:2.99.917+860+g3a2dec17-1
> xf86-video-vesa 2.4.0-2
> 
> i7-6600U 的核显 (HD Graphics 520)

应该不会是跟显卡驱动有关，否则不能解释鼠标再去触碰 dock 时，会让其位置变正确

**Comment by CareF** [comment]
奇怪.. 前两天突然症状消失了, 无论如何复现不出来.. 
今天又出现了...

**Comment by CareF** [comment]
现在变成了拔掉作为主显示器的外接显示器后, dock就消失了.. 但dock显示的位置还留着 
@listenerri

**Comment by wangjia12** [comment]
@zccrs @justforlxz 你们帮忙继续跟一下这个问题吧

**Comment by CareF** [comment]
之前某次更新之后, 这个问题不再稳定复现了. 
然后最近又非常稳定地出现...

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
