### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【DDE】【任务栏】【UI】 任务栏图标显示问题，图标挤压在一起

### ISSUE THREAD

**Issue by wangruoxuan3782** [linuxdeepin/developer-center#8274]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
任务栏 0.0.13
```

### STEPS TO REPRODUCE | 复现步骤

1.打开控制中心
2.个性化-桌面-设置任务栏大小

### OBSERVED RESULT | 观察到的结果

图标挤压在一起
![截图_选择区域_20240426134810](https://github.com/linuxdeepin/developer-center/assets/162073918/35fef0a2-26a7-4054-baf9-13d110029d30)

### EXPECTED RESULT | 期望的结果

图标大小正常显示，不会重叠在一起

**Comment by tsic404** [comment]
QML 缓存导致

**Comment by luodeepin** [comment]
验证通过
dde-shell 0.0.15
![录屏_选择区域_20240507133628](https://github.com/linuxdeepin/developer-center/assets/96416089/80f975c1-11f0-49e7-a69a-f1c4b1f0d705)

**Comment by luodeepin** [comment]
回归不通过
dde-shell 0.0.16
![8274](https://github.com/linuxdeepin/developer-center/assets/96416089/ef02c354-c720-43ec-8910-d7055682a764)

**Comment by luodeepin** [comment]
验证通过
dde-shell 0.0.17
![录屏_选择区域_20240510140048](https://github.com/linuxdeepin/developer-center/assets/96416089/f0e22468-878e-43b5-a9e3-c4149947b7b1)
