### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【DDE】【任务栏/启动器】【UI】 启动器、多任务视图图标hover时，图标变化的问题

### ISSUE THREAD

**Issue by wangruoxuan3782** [linuxdeepin/developer-center#8275]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
任务栏0.0.13
```

### STEPS TO REPRODUCE | 复现步骤

1.hover启动器、多任务视图图标

### OBSERVED RESULT | 观察到的结果

启动器的图标hover时，图标颜色明显变淡；多任务视图的图标hover时图标底部出现一圈白色的背景
![截图_选择区域_20240426133347](https://github.com/linuxdeepin/developer-center/assets/162073918/1dc21a4a-d5bb-45a2-b67b-9cdf54192159)

### EXPECTED RESULT | 期望的结果

应用图标hover时候 图标本身无变化

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240430
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.25-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
