### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【DDE】【任务栏/启动器】【UI】  多桌面中，hover和press的区域大小不统一

### ISSUE THREAD

**Issue by wangruoxuan3782** [linuxdeepin/developer-center#8278]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
任务栏 0.0。12
```

### STEPS TO REPRODUCE | 复现步骤

hover任务栏左侧多桌面

### OBSERVED RESULT | 观察到的结果

多桌面可hover的面积过大，目前鼠标悬停在桌面图标外 ，图标也会有hover效果，但点击效果是只有桌面图标才有

![截图_选择区域_20240426133415](https://github.com/linuxdeepin/developer-center/assets/162073918/724922a5-9350-4ca2-8389-3217ecde1571)

### EXPECTED RESULT | 期望的结果

press和hover的区域应该是保持统一的，标注的红色区域为hover和press的生效区域

```[tasklist]
### Tasks
```

**Comment by wangruoxuan3782** [comment]
![WX20240426-152638@2x](https://github.com/linuxdeepin/developer-center/assets/162073918/a203ce59-4764-4c7e-bf31-58c683b95d01)

**Comment by luodeepin** [comment]
验证通过
经设计确认已经修复
dde-shell 0.0.14
![截图_选择区域_20240428170239](https://github.com/linuxdeepin/developer-center/assets/96416089/b0f78f05-2e99-4bc3-a92e-031809657f22)
