### ISSUE TITLE
深度编辑器打开大文件会卡死

### ISSUE THREAD

**Issue by FurryWolfX** [linuxdeepin/developer-center#828]
## 缺陷描述

深度编辑器打开大文件会卡死

## 复现步骤

比如打开5000行的CSS文件就已经有明显的卡顿。打开更大的文件，比如输入法的码表，直接卡死。
但是用VS Code打开相同的文件就不会卡顿。

## 期望行为

不会卡死

### 发行版以及版本

Linux Deepin 15.7

### 相关的软件包版

deepin-editor 1.2.6.2-1

**Comment by liuwen123** [comment]
打开大文件会卡死的问题确实存在，暂时找不到更好的优化方法
可以试试kwrite和kate

**Comment by BLumia** [comment]
注：上次触屏滚动优化导致的负面影响，由 https://github.com/linuxdeepin/deepin-editor/commit/5aa5d53dda07ee37895decf4019d8db34dfba861 引入。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
