### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【DDE】【任务栏/启动器】【UI】   显示桌面的分割线没有适配深浅模式

### ISSUE THREAD

**Issue by wangruoxuan3782** [linuxdeepin/developer-center#8284]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
任务栏0.0.13
```

### STEPS TO REPRODUCE | 复现步骤

任务栏调整到深色模式

### OBSERVED RESULT | 观察到的结果

深色模式下，分割线颜色偏灰色了
![截图_选择区域_20240426133604](https://github.com/linuxdeepin/developer-center/assets/162073918/28fd58fc-883a-40bf-8322-0561896620e6)

### EXPECTED RESULT | 期望的结果

1.浅色模式下分割线颜色为黑色+20%不透明度 ；深色色模式下为白色+20%不透明度
2.分割线粗细不跟随高分屏幕变化
![WX20240426-160846@2x](https://github.com/linuxdeepin/developer-center/assets/162073918/867bd110-d669-4b55-933d-ec4d8a54d81d)

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240430
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.25-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
