### ISSUE TITLE
在某些软件下标题栏过高不美观，比如jetbrains系列

### ISSUE THREAD

**Issue by FurryWolfX** [linuxdeepin/developer-center#829]
不算什么重要的缺陷，但希望deepin越来越完美。

## 缺陷描述

在某些软件下标题栏过高不美观，比如jetbrains系列，firefox等。

## 期望行为

方案1：可以自适应软件的主题色，尽量融为一体避免突兀。
方案2：最大化时隐藏或简化标题栏。

## 发行版以及版本

Linux Deepin 15.9

**Comment by jay763190097** [comment]
菜单栏选项行高也有点大！！！

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
