### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【 DDE】任务栏预览显示卡顿

### ISSUE THREAD

**Issue by kobe337** [linuxdeepin/developer-center#8293]
### SUMMARY | 问题概要

任务栏预览显示卡顿

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240425/
内核版本：Deepin OS-23-20240425052752-1_x86_64
应用版本：dde-shell: 0.0.13
```

### STEPS TO REPRODUCE | 复现步骤

1. 桌面环境，在任务栏上右键点击文件管理器新建窗口两次及以上，鼠标移动到文件管理器图标上，查看预览显示状态

### OBSERVED RESULT | 观察到的结果

任务栏预览显示卡顿
![预览卡顿](https://github.com/linuxdeepin/developer-center/assets/17869922/7f097045-2b62-4565-8a6c-521dc2eb6d18)

### EXPECTED RESULT | 期望的结果

任务栏预览显示流畅

**Comment by tsic404** [comment]
关联： https://github.com/linuxdeepin/dde-shell/pull/276

**Comment by babyfengfjx** [comment]
@tsic404  提交集成后，可以直接走单回归。

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Beta3/
回归应用版本：dde-shell ：0.0.15
内核：Linux deepinb3-PC 6.6.25-amd64-desktop-hwe #23.01.00.25 SMP PREEMPT_DYNAMIC Wed Apr 10 21:20:25 CST 2024 x86_64 GNU/Linux

【结论】：
回归测试通过，暂无严重问题及影响，验证bug操作步骤，覆盖文件管理器、终端等应用。
