### ISSUE TITLE
DDE Dock Plugin 如何编译？

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#83]
开发文档不够详细，貌似QT5？

**Comment by fasheng** [comment]
是的, Deepin Qt版本是5.5.1, 确实项目README没有具体描述dock-plugins, 你具体什么编译错误呢? 如果使用的是Deepin, 可用用`apt-get build-dep dde-control-center` 自动安装编译依赖
https://github.com/linuxdeepin/dde-control-center

**Comment by sbwtw** [comment]
dock plugin 现在比较分散，一部分在 dde-dock 这个项目，更多的是在 dde-control-center 这个项目，编译的话，你在编译这两个项目的同时，就会编译插件，libdde-dock-*-plugin.so

**Comment by sonichy** [comment]
apt-get build-dep dde-control-center
报错：您必须在您的 sources.list 写入一些“软件源”的 URI

**Comment by snyh** [comment]
build-dep是需要 deb的source包，因此需要添加 
deb-src [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
