### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【玲珑】 保留玲珑应用配置，升级用户无感替换deb版本应用

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#8301]
### SUMMARY | 问题概要

针对升级用户从玲珑应用deb应用

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://cdimage.uniontech.com/community/releases/23-Beta3/deepin-desktop-community-23-Beta3-amd64.iso
```

### PRE-REQUIREMENT | 预置条件

针对beta3升级用户

### STEPS TO REPRODUCE | 复现步骤

1. 保留玲珑应用配置，升级用户无感替换deb版本应用

### OBSERVED RESULT | 观察到的结果

1.保留玲珑应用配置，升级用户无感替换deb版本应用

### EXPECTED RESULT | 期望的结果

1. 保留玲珑应用配置，升级用户无感替换deb版本应用

**Comment by chenchongbiao** [comment]
玲珑使用的用户配置和deb安装的用户配置不同，无法保留配置，浏览器和邮箱继续保留玲珑应用，后续发帖子说明如何迁移。

**Comment by babyfengfjx** [comment]
@vivianxf  该问题可以跟进发帖的内容即可。

**Comment by luodeepin** [comment]
验证通过
1. 修复工具可以使用
2. 运营已发帖：https://bbs.deepin.org/post/272355
