### ISSUE TITLE
dock items removed when application updated

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/developer-center#831]
This has been an issue since as long as I know Deepin - and that's a while... :stuck_out_tongue_winking_eye: 
When an application is attached to the dock, the icon will be removed from there with every update of the application. This is really annoying.
Any hope this can be resolved?

**Comment by felixonmars** [comment]
I actually have an idea here.

@jouyouyun is it possible to provide a pair of "suspend/resume" dbus api for dde-daemon's application change detection? if it has to rescan all the locations each time anyway, we can use a pacman hook so that the upgrading process won't fool the deamon.

**Comment by keybreak** [comment]
Please fix this, it's really annoying in Manjaro Deepin)

**Comment by jouyouyun** [comment]
This is a known bug and we are still working on it.

**Comment by electricface** [comment]
https://cr.deepin.io/#/c/dde/dde-daemon/+/41749

**Comment by oberon-manjaro** [comment]
:champagne: :tada: :rocket:

**Comment by keybreak** [comment]
Confirmed with Firefox / Sublime Text 3 on Arch Deepin and Manjaro Deepin, suppose it can be closed :)

Finally, thank you @jouyouyun & @electricface !!! :+1:
