### ISSUE TITLE
External monitor issues

### ISSUE THREAD

**Issue by dusatvoj** [linuxdeepin/developer-center#833]
## Describe the bug

I have a laptop with external monitor (with higher resolution than laptop)... There are 3 issues with it.
 1. External monitor can't be centered with laptop's monitor because of corner locking.
 2. Deepin tries to set monitor brightness same as on laptop but it's not working as well (external monitor usually stays in 3 brightness states 0%, cca 20%, 100%) and it's bullshit too, because external monitor has it's own brightness settings in control panel. (It happens mainly when I boot with external monitor connected... But sometimes it happens when I connect my external monitor later too.)
 3. I haven't found any way to do a screenshot of both monitors.

### Screenshots

![image](https://user-images.githubusercontent.com/11560794/51425225-78336c80-1bd9-11e9-9784-1d483438d07a.png)

## Expected behavior

I expect 2 things:
 1. Disabling brightness on non-laptop monitors.
 2. Enabling organization of monitors not only trough corners.
 3. Some screenshot enhacement

## Enviroments:

 - HP Laptop
 - External monitor connected via VGA

### Distro & Version

 - Newest arch with Deepin DE

**Comment by sdlins** [comment]
I have a completely related issue: when adjusting the brightness, even although I see two sliders, one for each monitor, both only adjust the main monitor (laptop) not affecting the external one. I just can adjuts its brightness using `xrandr` command.

**Comment by dusatvoj** [comment]
@sdlins I have another problem... When I adjust second monitor to 100% (using the slider for VGA) It's on 100% brightness for a few second and then it drops down to cca 20% of brightness again :disappointed: ... I'm ussualy rebooting and disconnecting and connecting VGA until it works ... Like a windows :nauseated_face:

**Comment by dusatvoj** [comment]
Hey, does anyone care about this?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
