### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【DDE】【启动器】【UI】  应用组应用名清除后返回，应用组名称显示为空的问题

### ISSUE THREAD

**Issue by wangruoxuan3782** [linuxdeepin/developer-center#8334]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
启动器 6.0.19
```

### STEPS TO REPRODUCE | 复现步骤

1.清除应用组名称

### OBSERVED RESULT | 观察到的结果

清除后返回，应用组名称显示为空
![截图_选择区域_20240426134952](https://github.com/linuxdeepin/developer-center/assets/162073918/3b3e89df-0531-42d6-a918-faf8a37f1c2f)

### EXPECTED RESULT | 期望的结果

如果名称为空，返回后应该操作不生效，应用组始终是有名称的

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240430
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.25-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
