### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【DDE】【启动器】【UI】   1.应用组名称超长时，显示问题 2.缺少tooltips

### ISSUE THREAD

**Issue by wangruoxuan3782** [linuxdeepin/developer-center#8336]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
启动器 6.0.19
```

### STEPS TO REPRODUCE | 复现步骤

将应用组名称修改的比较长

### OBSERVED RESULT | 观察到的结果

1.退出编辑后查看应用组，应用名称显示不下时，没有省略号显示
2.应用组名称超长时，缺少tooltips效果
3.应用组名称超长时，文字显示的间距小了
![Uploading WX20240429-165210@2x.png…]()
![Uploading WX20240429-165232@2x.png…]()

### EXPECTED RESULT | 期望的结果

1.退出编辑后查看应用组，应用名称显示不下时，省略号显示
2.应用组名称超长时，hover时补充tooltips效果
3.应用组名称超长时，文字显示和背景的间距加到30px
![WX20240429-165910@2x](https://github.com/linuxdeepin/developer-center/assets/162073918/5f196e32-b93a-4f56-822a-5fbeed3247e5)

**Comment by mhduiy** [comment]
测试要求将小窗口的title margin改为20,大窗口为30不变

**Comment by kegechen** [comment]
@xuqi27837288 回归

**Comment by wangruoxuan3782** [comment]
dde-launchpad 0.7.1
UI已验证
