### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【DDE】【启动器】【UI】   窗口启动器应用组的圆角过大，hover颜色深了

### ISSUE THREAD

**Issue by wangruoxuan3782** [linuxdeepin/developer-center#8338]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
启动器6.0.19
```

### STEPS TO REPRODUCE | 复现步骤

打开窗口启动器-打开应用组

### OBSERVED RESULT | 观察到的结果

窗口启动器背景圆角大了，hover时的背景颜色深了
![截图_选择区域_20240429144053](https://github.com/linuxdeepin/developer-center/assets/162073918/ebb3fefe-0ca6-4702-9b44-e3eb9ac1146a)

### EXPECTED RESULT | 期望的结果

圆角大小为12，hover时不透明度为10%，和窗口启动器hover效果保持一致
<img width="521" alt="image" src="https://github.com/linuxdeepin/developer-center/assets/162073918/144595e1-69a5-4413-86fc-165b72471e7b">

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240430
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.25-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
