### ISSUE TITLE
待机唤醒不输密码不会重新进入待机状态

### ISSUE THREAD

**Issue by jay763190097** [linuxdeepin/developer-center#834]
## 缺陷描述

其实我也不知道怎么被莫名唤醒了，而且出现频率也有点高。睡觉前待机，起来屏幕一直是亮的。

### 发行版以及版本

deepin一直有这个问题，都升级很多版本了，可能15左右一直都有吧。

### 总之

deepin已经越来越好用了。

**Comment by jay763190097** [comment]
@hualet 这个比较重要的bug什么时候修复啊

**Comment by electricface** [comment]
唤醒之后要重新等待空闲时间，比如设置了空闲30分钟后待机，就必须再把电脑空闲 30分钟后，才会自动待机。如果有需要立即待机，推荐手动待机。

**Comment by jay763190097** [comment]
@electricface 有两个问题，第一个莫名唤醒，第二个唤醒在锁屏界面不会自动重新进入待机。你闲置30个小时，都不会进入待机

**Comment by electricface** [comment]
第一个莫名唤醒，你把鼠标和键盘都断开连接试试。
第二个锁屏界面不能待机，锁屏并不会干扰空闲时长的判定，测试发现并有这个问题。

**Comment by jay763190097** [comment]
@electricface 有这个问题就好。不用再给我推荐了，因为一直在用。

**Comment by electricface** [comment]
给你推荐什么了？

**Comment by jay763190097** [comment]
@electricface “唤醒之后要重新等待空闲时间，比如设置了空闲30分钟后待机，就必须再把电脑空闲 30分钟后，才会自动待机。如果有需要立即待机，推荐手动待机。”你的原话，能不能先验证一下，再告诉我怎么操作。。。。

**Comment by electricface** [comment]
我自己测试了没有问题呀

**Comment by jay763190097** [comment]
@electricface 能锁屏能自动待机？
我发现6小时自动唤醒，然后在锁屏界面永远都不会重新进入待机

**Comment by electricface** [comment]
我自己测试锁屏可以自动待机，你的现象确实很奇怪。

先设置 待机需要的空闲时间为 30s，在终端执行命令：
```
gsettings set com.deepin.dde.power line-power-sleep-delay 30
gsettings set com.deepin.dde.power battery-sleep-delay 30
```

然后再收集日志，在终端执行命令：
```
killall dde-session-daemon;env DDE_DEBUG_MATCH=power /usr/lib/deepin-daemon/dde-session-daemon > ~/dde-session-daemon.txt
```
如果运行 dde-session-daemon 一次没有成功，就再试一次。然后上传 ~/dde-session-daemon.txt 给我看。

**Comment by jay763190097** [comment]
好的，我回去验证

**Comment by hualet** [comment]
```
$ cat /proc/acpi/wakeup | grep -i enabled
```
看看有哪些设备是开启唤醒了的？

**Comment by jay763190097** [comment]
```
jay@jay-PC:~$ cat /proc/acpi/wakeup | grep -i enabled
XHC	  S3	*enabled   pci:0000:00:14.0
PWRB	  S4	*enabled   platform:PNP0C0C:00
```
收集的日志
```
<info> main.go:125: Log level is none and debug env exists, so ignore cmd.loglevel
<info> manager.go:137: LidIsPresent true
<debug> manager.go:139: HasAmbientLightSensor: false
<debug> manager_ambient_light.go:8: call claimOrReleaseAmbientLight
<debug> manager_ambient_light.go:25: hasAmbientLightSensor: false, autoAdjustEnabled: false, session active: true, lidSwitchState: 0 -> shouldClaim: false
<debug> sleep_inhibit.go:69: Block sleep
<debug> manager_events.go:66: handleBatteryDisplayUpdate
<debug> manager_stub.go:45: set batteryDisplay percentage 94.0%
<debug> manager_stub.go:58: set BatteryDisplay status Charging 1
<debug> submodule.go:38: New submodule: LidSwitchHandler
<debug> submodule.go:38: New submodule: PowerSavePlan
<info> submodule.go:58: submodule PowerSavePlan start
<debug> power_save_plan.go:121: OnBattery: false
<debug> power_save_plan.go:113: Use OnLinePower plan
<debug> power_save_plan.go:243: update(screenSaverStartDelay=900s, screenBlackDelay=60s, sleepDelay=30s)
<debug> power_save_plan.go:310: set ScreenSaver timeout to 30
<debug> power_save_plan.go:303: task sleep: 30s
<debug> power_save_plan.go:301: task screenBlack will not run
<debug> power_save_plan.go:301: task screenSaverStart will not run
<info> submodule.go:58: submodule LidSwitchHandler start
```

**Comment by electricface** [comment]
https://www.thomasmonaco.com/prevent-usb-devices-waking-ubuntu-sleep/

用root权限执行命令：
```
echo HCI > /proc/acpi/wakeup
```
可以禁止 HCI 引起电脑唤醒。

**Comment by jay763190097** [comment]
昨天拿deepin的备份软件从一个分区（外接A磁盘）克隆到另一个分区（外接B磁盘），最后时刻死机重新进入桌面。后面发现EFI分区被损坏了，现在deepin进不去了，但是win10能进去。EFI也挂载不了，用磁盘工具扫描，第一个点有坏道。也不能格式化，里面文件都没了，不知道怎么恢复中。。。。。。。。后悔没有再live下使用备份功能。

**Comment by jay763190097** [comment]
不好意思，手误

**Comment by electricface** [comment]
没有机会测试了？

**Comment by jay763190097** [comment]
@electricface 等我想办法恢复启动再测，哈哈

**Comment by jay763190097** [comment]
@hualet @electricface 帮忙看下，EFI格盘后恢复启动文件，一直都是进入下面这个界面。可以通过grub命令手动引导进入系统，但是不知道还有哪个文件有问题。
![143347l0kjxazmmdmt32a0](https://user-images.githubusercontent.com/16317178/53314463-6d1add00-38f9-11e9-9489-d85324a6d521.jpg)

论坛地址：https://bbs.deepin.org/forum.php?mod=viewthread&tid=174925&extra=

**Comment by electricface** [comment]
用grub命令进入系统，然后执行 `sudo  update-grub` 试试。

**Comment by jay763190097** [comment]
@electricface 还是没能解决

**Comment by hualet** [comment]
进入系统以后再安装一次grub，然后再update-grub

**Comment by jay763190097** [comment]
@electricface @hualet 恢复好了，原因是1、恢复EFI的时候干掉了文件夹ubuntu
2、用了3楼从安装文件ISO提取的文件
