### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【DDE】【任务栏/启动器】【UI】 任务栏和启动器的描边问题

### ISSUE THREAD

**Issue by wangruoxuan3782** [linuxdeepin/developer-center#8342]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
任务栏0.0。14
```

### STEPS TO REPRODUCE | 复现步骤

查看任务栏、启动器、快捷面板的描边

### OBSERVED RESULT | 观察到的结果

描边都显示不一致
![Uploading 截图_选择区域_20240429154129.png…]()

### EXPECTED RESULT | 期望的结果

描边显示一致

浅色模式：
外描边 0.15 不透明度黑色
内描边 0.2 不透明度白色

深色模式：
外描边不透明度 = 窗口不透明度 + 20 / 255
内描边不透明度 = 窗口透明度 + 10 / 255

```[tasklist]
### Tasks
```

**Comment by mhduiy** [comment]
![企业微信截图_17187029125889](https://github.com/linuxdeepin/developer-center/assets/73688594/1d9f9c30-602a-4ded-962f-38bf8fd36189)

**Comment by mhduiy** [comment]
需要 
deepin-kwin-x11 >= 5.27.2.202
dde-launchpad > 0.7.3
dde-shell > 0.0.24

**Comment by baicailio** [comment]
设计说剪切板的不透明度调整有问题，单子重新激活

**Comment by wangruoxuan3782** [comment]
剪贴板、通知中心描边没有问题
任务栏描边不能跟随透明度实时变化，需要手动调整一下任务栏高度才会更新，任务栏在拖动高度的过程中描边时有时无

**Comment by baicailio** [comment]
按上述设计要求重新修改，单子激活

**Comment by mhduiy** [comment]
修改深色模式下窗口外边框的不透明度为 系统不透明度 + 20%

**Comment by xuqi27837288** [comment]
【验证环境】：v23 RC2镜像
镜像：https://cdimage.uniontech.com/community/releases/23-RC2/amd64/deepin-desktop-community-23-RC2-amd64.iso
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.35-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
