### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【DDE】【任务栏/启动器】【UI】   窗口启动器应用组的图标显示问题

### ISSUE THREAD

**Issue by wangruoxuan3782** [linuxdeepin/developer-center#8343]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
启动器6.0.19
```

### STEPS TO REPRODUCE | 复现步骤

查看窗口启动器应用组图标

### OBSERVED RESULT | 观察到的结果

图标中间有一条黑色的线
![截图_选择区域_20240429144031](https://github.com/linuxdeepin/developer-center/assets/162073918/f34eee43-fd70-410b-bdc8-79266c6bfc81)

### EXPECTED RESULT | 期望的结果

图标正常显示
<img width="665" alt="image" src="https://github.com/linuxdeepin/developer-center/assets/162073918/27c74243-6367-4a9c-9888-5fb52b7c7a90">

**Comment by babyfengfjx** [comment]
@kegechen  看这个是否好处理。

**Comment by kegechen** [comment]
- 没有跟随图标主题，这个要看看文件夹的图标名生成逻辑
- folder 这种图标在places目录下，之前只处理的 apps 目录下的图标可以转一下

 grep -ir "<feGaussianBlur*" /usr/share/icons/bloom/places | awk -F: '{print $1}'

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240430
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.25-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
