### ISSUE TITLE
Edge in Transparent Image

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#835]
## Describe the bug
Images that do not have a rectangular shape and have a transparent background ... you can see a rectangular border.

## To Reproduce
Generate image (other than square) and transparent background.

## Expected behavior
Transparent images without borders.

## Screenshots
![captura de tela_selecionar area_20190119213802](https://user-images.githubusercontent.com/45263160/51433842-6a163800-1c3b-11e9-8392-1028093a2941.png)

![captura de tela_selecionar area_20190119213906](https://user-images.githubusercontent.com/45263160/51433843-6d112880-1c3b-11e9-8d57-565257b9f4fd.png)

### Distro & Version
Deepin 15.9

### Additional context
This "feature" has always existed in Deepin.

**Comment by shule1987** [comment]
@zccrs 我之前也想提这个问题, png和svg这两个格式都应该去掉这个边框

**Comment by alexwender1** [comment]
Still not resolved.

**Comment by BLumia** [comment]
Hello and update on this issue, this issue will be fixed after the v20 release of DDE :)

**Comment by alexwender1** [comment]
> since v20 release still need a lot of work

@BLumia will deepin 20 be released in November? Or will we have the possible deepin 20 Beta in November?

**Comment by BLumia** [comment]
> > since v20 release still need a lot of work
> 
> @BLumia will deepin 20 be released in November? Or will we have the possible deepin 20 Beta in November?

Beta in November is possible :)
