### ISSUE TITLE
赶紧修复休眠失败无法唤醒的问题

### ISSUE THREAD

**Issue by AppJ-GS** [linuxdeepin/developer-center#836]
## 缺陷描述

睡眠无法唤醒，任意按键点击后主板不断发出提示音

## 复现步骤

每次自动睡眠/手动睡眠

复现步骤为:

1. 点击 '睡眠'
2.重新唤醒
3.唤醒失败，只有电源运行

## 期望行为

希望尽快改进

## 复现环境:

自动睡眠或手动点击睡眠

### 发行版以及版本

[ Linux Deepin 15.9]

**Comment by AppJ-GS** [comment]
> 休眠时需要按电源键重启的，只是重启后能恢复到休眠前的状态

是睡眠成功后，只有屏幕熄灭了，其他还在运行，但是唤醒不了了

**Comment by liuwen123** [comment]
唤醒不了就是内核问题

**Comment by lolimay** [comment]
这个论坛有很多反馈，希望官方能够给予重视，See:
- [Deepin freezes after suspend](https://bbs.deepin.org/forum.php?mod=viewthread&tid=171259&extra=)
- [更新deepin15.9,启用休眠，直接睡死](https://bbs.deepin.org/forum.php?mod=viewthread&tid=173826)

**Comment by cccxu** [comment]
16年就有反馈这个问题的了，估计这辈子修复不了了。真的难受，这个BUG太致命了。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
