### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【 DDE】启动器中item被选中时的背景位置异常，有的居中，有的偏下

### ISSUE THREAD

**Issue by kobe337** [linuxdeepin/developer-center#8361]
### SUMMARY | 问题概要

启动器中item被选中时的背景位置异常，有的居中，有的偏下

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Beta3/
```

### PRE-REQUIREMENT | 预置条件

内测更新至20240430

### STEPS TO REPRODUCE | 复现步骤

1.打开启动器查看每个item的背景元素效果

### OBSERVED RESULT | 观察到的结果

启动器中item被选中时的背景位置异常，有的居中，有的偏下
![pianx](https://github.com/linuxdeepin/developer-center/assets/17869922/66621fea-af6e-4bb1-99bb-d74cebbdc05d)

### EXPECTED RESULT | 期望的结果

启动器中item被选中时的背景位置保持一致，均居中显示

**Comment by babyfengfjx** [comment]
@BLumia  这个要优先处理。

**Comment by 18202781743** [comment]
这个问题我瞅瞅吧, Item的高度还不一致,

**Comment by kobe337** [comment]
验证通过
【环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Beta3/
应用版本：dde-launchpad 0.6.9
内核：Linux deepinb3-PC 6.6.25-amd64-desktop-hwe #23.01.00.25 SMP PREEMPT_DYNAMIC Wed Apr 10 21:20:25 CST 2024 x86_64 GNU/Linux

【结论】：
内测更新至20240430测试通过，暂无严重问题及影响, 打开启动器，查看item之间的间距，验证通过
![itemjz](https://github.com/linuxdeepin/developer-center/assets/17869922/43e56208-d905-4c2c-80be-e4500b8d7cde)
