### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【 DDE】启动器全屏模式下，点击翻页按钮无效

### ISSUE THREAD

**Issue by kobe337** [linuxdeepin/developer-center#8363]
### SUMMARY | 问题概要

启动器全屏模式下，点击翻页按钮无效

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Beta3/
应用版本：dde-launchpad: 0.6.8
```

### PRE-REQUIREMENT | 预置条件

内测更新至20240430
启动器设置为全屏模式

### STEPS TO REPRODUCE | 复现步骤

1. 启动器中将应用拖动到应用组中，点击翻页按钮

### OBSERVED RESULT | 观察到的结果

启动器全屏模式下，点击翻页按钮无效
![djwxl](https://github.com/linuxdeepin/developer-center/assets/17869922/e550b643-c68b-404c-8107-9c3c1b19fab6)

### EXPECTED RESULT | 期望的结果

启动器全屏模式下，点击翻页按钮功能正常

**Comment by babyfengfjx** [comment]
@BLumia  请优先处理。

**Comment by BLumia** [comment]
已确认是 Qt BUG，尝试了绕过方案但看上去不可行，具体 Qt 内问题原因尚在确认中，已汇报至上游。

上游汇报： https://bugreports.qt.io/browse/QTBUG-125139

**Comment by yixinshark** [comment]
是不是可以屏蔽点击切换页面，就当显示用。

**Comment by kobe337** [comment]
#https://github.com/linuxdeepin/developer-center/issues/8491 验证未通过，dde-launchpad	[0.6.10] 问题还是存在

**Comment by kobe337** [comment]
验证通过
【环境】：
镜像：镜像： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240509/deepin-23-beige-rc-amd64-20240509-120442.iso
仓库：提测单仓库 https://github.com/linuxdeepin/developer-center/issues/8491
内核：Linux deepinb3-PC 6.6.25-amd64-desktop-hwe https://github.com/linuxdeepin/developer-center/issues/23.01.00.25 SMP PREEMPT_DYNAMIC Wed Apr 10 21:20:25 CST 2024 x86_64 GNU/Linux

【结论】：
测试通过，暂无严重问题及影响，根据issues描述进行操作，验证通过
