### ISSUE TITLE
【deepin_V23_Release】【严重】【立即】【预发布测试】【 DDE】启动器全屏模式，点击右键删除的应用非预期删除应用

### ISSUE THREAD

**Issue by kobe337** [linuxdeepin/developer-center#8366]
### SUMMARY | 问题概要

启动器全屏模式，点击右键删除的应用非预期删除应用

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Beta3/
应用版本：dde-launchpad: 0.6.8
```

### PRE-REQUIREMENT | 预置条件

libreoffice已通过命令remove
全屏模式

### STEPS TO REPRODUCE | 复现步骤

1. 右键点击删除应用组中的应用（将libreoffice相关应用全部放入一个应用组中，选择应用组展示的第一个进行右键删除操作）

### OBSERVED RESULT | 观察到的结果

启动器全屏模式，点击右键删除的应用非预期删除应用
![sccw](https://github.com/linuxdeepin/developer-center/assets/17869922/bfa99f1c-2a5f-4dda-ab48-15e6baba239d)

### EXPECTED RESULT | 期望的结果

启动器全屏模式，点击右键删除的应用应为预期删除应用

**Comment by babyfengfjx** [comment]
@robertkill  这个需要优先处理。

**Comment by kobe337** [comment]
验证通过
【环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Beta3/
仓库：提测单仓库 https://github.com/linuxdeepin/developer-center/issues/8389
内核：Linux deepinb3-PC 6.6.25-amd64-desktop-hwe https://github.com/linuxdeepin/developer-center/issues/23.01.00.25 SMP PREEMPT_DYNAMIC Wed Apr 10 21:20:25 CST 2024 x86_64 GNU/Linux

【结论】：
内测更新至20240430测试通过，暂无严重问题及影响，安装libreoffice-办公套件，将相关应用加入应用组，删除其中一个，查看弹出对话框显示。验证通过
