### ISSUE TITLE
【deepin_V23_Release】【严重】【立即】【预发布测试】【 DDE】启动器全屏模式，应用组内清空后，存在空应用组

### ISSUE THREAD

**Issue by kobe337** [linuxdeepin/developer-center#8367]
### SUMMARY | 问题概要

启动器全屏模式，应用组内清空后，存在空应用组

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Beta3/
```

### PRE-REQUIREMENT | 预置条件

内测更新至20240430
应用组内放置libreoffice的相关应用

### STEPS TO REPRODUCE | 复现步骤

1.启动器全屏模式， 将应用组内的应用全部卸载 （libreoffice）

### OBSERVED RESULT | 观察到的结果

启动器全屏模式，应用组内清空后，存在空应用组
![kyyz](https://github.com/linuxdeepin/developer-center/assets/17869922/387c5dd4-3276-4ee7-aecf-5d057064a666)

### EXPECTED RESULT | 期望的结果

启动器全屏模式，应用组内清空后，应用组被销毁

**Comment by babyfengfjx** [comment]
@robertkill  这个可以优先处理。
