### ISSUE TITLE
【deepin_V23_Release】【一般】【正常】【升级测试】【 DDE】【启动器】中文环境，采集日志的通知消息显示英文

### ISSUE THREAD

**Issue by baicailio** [linuxdeepin/developer-center#8369]
### SUMMARY | 问题概要

中文环境，采集日志的通知消息显示英文

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Beta3/
仓库：升级到最新RC内测版本
```

### PRE-REQUIREMENT | 预置条件

无

### STEPS TO REPRODUCE | 复现步骤

1.打开日志收集工具，点击启动日志右上角的帮助按钮，选择反馈
2.查看消息通知

### OBSERVED RESULT | 观察到的结果

中文环境，采集日志的通知消息显示英文
![采集日志](https://github.com/linuxdeepin/developer-center/assets/166582166/28e33dc9-7b28-4ee8-b55f-6a351436d014)

### EXPECTED RESULT | 期望的结果

中文环境，采集日志的通知消息显示中文

**Comment by babyfengfjx** [comment]
@kegechen  有余力可以安排优化~

**Comment by kegechen** [comment]
deepin-feedback 这个项目可能发送通知没有翻译

**Comment by mhduiy** [comment]
![image](https://github.com/linuxdeepin/developer-center/assets/73688594/3c342de1-fc22-4e50-b1f7-890a9df9bbd9)

**Comment by kegechen** [comment]
重复问题
https://github.com/linuxdeepin/developer-center/issues/7889

**Comment by baicailio** [comment]
https://github.com/linuxdeepin/developer-center/issues/7889 跟踪，此单关闭
