### ISSUE TITLE
【deepin_V23_Release】【严重】【立即】【预发布测试】【 DDE】【启动器】重启系统后，启动器全屏模式应用创建文件夹，移动应用等操作被重置

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#8370]
### SUMMARY | 问题概要

重启系统后，启动器全屏模式应用创建文件夹，移动应用等操作被重置

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240430/ 
dde-launchpad:0.6.7
```

### PRE-REQUIREMENT | 预置条件

1.安装上述最新镜像

### STEPS TO REPRODUCE | 复现步骤

1.启动器打开全屏模式
2.在启动器内拖动应用创建文件夹
3.移动应用到其他标签页
4.重启系统，观察现象

### OBSERVED RESULT | 观察到的结果

1.重启系统后，启动器全屏模式应用创建文件夹，移动应用等操作被重置
![image](https://github.com/linuxdeepin/developer-center/assets/96415804/d8f208fe-73b5-41a4-9ad3-28e1e7164cd8)
![image](https://github.com/linuxdeepin/developer-center/assets/96415804/20def0fb-c0e8-44d0-81fc-8e0b5162c412)

### EXPECTED RESULT | 期望的结果

1.启动器修改得到保存，不会被重置

**Comment by babyfengfjx** [comment]
@robertkill  需要优先处理。

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240430
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.25-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
