### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【DDE】【启动器】【UI】 窗口启动器下左侧图标显示问题

### ISSUE THREAD

**Issue by wangruoxuan3782** [linuxdeepin/developer-center#8376]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
dde-launchpad  0.6.8
dde-shell 0，0，15
```

### STEPS TO REPRODUCE | 复现步骤

切换主题，打开窗口启动器

### OBSERVED RESULT | 观察到的结果

窗口启动器侧边栏图标和文管侧边栏图标不配套
![企业微信截图_17170338402330](https://github.com/linuxdeepin/developer-center/assets/162073918/f43bda09-2fa6-4ef5-9023-c8665d0ff201)

### EXPECTED RESULT | 期望的结果

图标显示正确，窗口启动器侧边栏图标和文管侧边栏图标样式保持一致，和对应的主题配套

vintage、organic glass、hazy color、macaron（organic glass的文管和窗口启动器侧边栏图标换成bloom那套）

**Comment by yixinshark** [comment]
最新代码未有复现。

**Comment by wangruoxuan3782** [comment]
有问题的主题有：organic glass、hazy color、macaron
这三个主题的窗口启动器侧边栏图标风格显示不一致，看起来显示桌面和文档读取的是主题包里的图标，另外几个又读取的是默认主题的
期望效果：更换不同主题时，窗口启动器左侧图标风格是一直的而不是杂乱的

**Comment by xuqi27837288** [comment]
![截图_选择区域_20240606100059](https://github.com/linuxdeepin/developer-center/assets/62528742/2f00c5ac-3d69-47c9-9629-1ecc6353cb9f)

**Comment by xuqi27837288** [comment]
【验证环境】：v23 RC2镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240613
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.25-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过

**Comment by xuqi27837288** [comment]
在9010集成回归测试通过

**Comment by wangruoxuan3782** [comment]
dde-shell 0.0.27 UI已验证
