### ISSUE TITLE
文件夹内新建或重命名后焦点失效

### ISSUE THREAD

**Issue by YLXDXX** [linuxdeepin/developer-center#838]
新建一个文本文件输完文件名字后回车，此时刚建的文件没有进入被选中的状态，不能再直接回车打开，需要鼠标再点击一次才可以使用回车打开，重命名一个文件或文件夹也是如此

注：在桌面没有此情况发生，文件管理器里面存在

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/41486/

**Comment by liuwen123** [comment]
+1
