### ISSUE TITLE
【deepin_V23_Release】【一般】【有空】【预发布测试】【 DDE】设置主题bloom-dark，启动器与回收站图标显示不协调

### ISSUE THREAD

**Issue by kobe337** [linuxdeepin/developer-center#8381]
### SUMMARY | 问题概要

设置主题bloom-dark，启动器与回收站图标显示不协调

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Beta3/
```

### PRE-REQUIREMENT | 预置条件

内测更新至20240430

### STEPS TO REPRODUCE | 复现步骤

1.打开控制中心，设置个性化-主题-图标主题设置为bloom-dark，查看界面展示

### OBSERVED RESULT | 观察到的结果

设置主题bloom-dark，启动器与回收站图标显示不协调
![sx](https://github.com/linuxdeepin/developer-center/assets/17869922/717ed526-adbe-47e6-85c0-402b057ad27c)

### EXPECTED RESULT | 期望的结果

建议修改主题bloom-dark中启动器与回收站的图标为亮色系

**Comment by babyfengfjx** [comment]
@asterwyx  可以优先处理。

**Comment by kobe337** [comment]
验证通过
【环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Beta3/
仓库：提测单仓库 https://github.com/linuxdeepin/developer-center/issues/8389
内核：Linux deepinb3-PC 6.6.25-amd64-desktop-hwe #23.01.00.25 SMP PREEMPT_DYNAMIC Wed Apr 10 21:20:25 CST 2024 x86_64 GNU/Linux

【结论】：
更新至20240430测试通过，暂无严重问题及影响。
