### ISSUE TITLE
【deepin_V23_Release】【严重】【立即】【预发布测试】【 DDE】【控制中心】系统休眠后唤醒，关闭的蓝牙被重新打开

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#8386]
### SUMMARY | 问题概要

系统休眠后唤醒，关闭的蓝牙被重新打开

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240430/ 
dde-control-center:6.0.52
```

### STEPS TO REPRODUCE | 复现步骤

1.打开蓝牙连接有效设备
2.关闭蓝牙，系统进入休眠
3.唤醒系统，观察蓝牙状态

### OBSERVED RESULT | 观察到的结果

1.系统休眠后唤醒，关闭的蓝牙被重新打开
![截图_dde-desktop_20240506171056](https://github.com/linuxdeepin/developer-center/assets/96415804/83462a49-d2b4-493c-8dde-cfdd1ac71422)

### EXPECTED RESULT | 期望的结果

1.系统休眠唤醒后，关闭的蓝牙不会被重新打开

**Comment by babyfengfjx** [comment]
@kegechen  这个优先处理。

**Comment by kegechen** [comment]
帮忙看看 @zsien

**Comment by vivianxf** [comment]
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240430/
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1383/testing/ ./
验证步骤：提单的步骤
验证现象：休眠唤醒后，蓝牙状态不变
验证结果：通过
