### ISSUE TITLE
Wifi crashes after some minutes or after lock screen

### ISSUE THREAD

**Issue by sdlins** [linuxdeepin/developer-center#839]
Hi,

My wifi is frequently crashing. Sometimes it occurs after 5 minutes. Other times after 30. Yet other times it occurs just after back from lock screen. There is no standard. The only way to make it work again is **restart** the computer. 

I tried many things I found in internet: modprobe, ifup/ifdown, network-manager, networkctl, etc. I tried even disable "N" mode of my router even althoug in `/etc/modprobe.d/iwlwifi.conf` it is already disabled: `options iwlwifi 11n_disable=1 bt_coex_active=0 power_save=0 swcrypto=1`. But nothing resolved the problem.

By "crashing" I mean that my network wifi connection is lost (obviously internet stop working) and its icon in the dock dissappears completely. The only way to use internet again is via wired connection or restarting the computer to be able to use wifi again (till it crashes again). It never happened when using Ubuntu 18.04 so my hardware is fine.

These are my machine/OS info:

- Chassis: laptop
- Operating System: Deepin 15.8
- Kernel: Linux 4.15.0-29deepin-generic
- Architecture: x86-64

These are my relevant logs:

- [1-logs-when-wifi-is-working-fine.txt](https://github.com/linuxdeepin/developer-center/files/2776815/1-logs-when-wifi-is-working-fine.txt)

- [2-logs-just-after-wifi-crashing.txt](https://github.com/linuxdeepin/developer-center/files/2776816/2-logs-just-after-wifi-crashing.txt)

- [3-general-information.txt.txt](https://github.com/linuxdeepin/developer-center/files/2776824/3-general-information.txt.txt)

**Comment by jouyouyun** [comment]
Have the package of `firmware-iwlwifi` installed? If installed, try to install [intel official driver](https://www.intel.com/content/www/us/en/support/articles/000005511/network-and-i-o/wireless-networking.html)

**Comment by sdlins** [comment]
I will check and post the results here. Thank you.

**Comment by sdlins** [comment]
@jouyouyun Unfortunately, it didn't work. I had already `firmware-iwlwifi` and I installed the drives from intel (see below) but this is still crashing.,

```
modinfo iwlwifi | grep firmware
firmware:       iwlwifi-100-5.ucode
firmware:       iwlwifi-1000-5.ucode
firmware:       iwlwifi-135-6.ucode
firmware:       iwlwifi-105-6.ucode
firmware:       iwlwifi-2030-6.ucode
firmware:       iwlwifi-2000-6.ucode
firmware:       iwlwifi-5150-2.ucode
firmware:       iwlwifi-5000-5.ucode
firmware:       iwlwifi-6000g2b-6.ucode
firmware:       iwlwifi-6000g2a-6.ucode
firmware:       iwlwifi-6050-5.ucode
firmware:       iwlwifi-6000-6.ucode
firmware:       iwlwifi-7265D-29.ucode <<<< THIS *****************
firmware:       iwlwifi-7265-17.ucode <<<< AND THIS ****************
firmware:       iwlwifi-3168-29.ucode
firmware:       iwlwifi-3160-17.ucode
firmware:       iwlwifi-7260-17.ucode
firmware:       iwlwifi-8265-34.ucode
firmware:       iwlwifi-8000C-34.ucode
firmware:       iwlwifi-9260-th-b0-jf-b0-34.ucode
firmware:       iwlwifi-9260-th-a0-jf-a0-34.ucode
firmware:       iwlwifi-9000-pu-a0-jf-b0-34.ucode
firmware:       iwlwifi-9000-pu-b0-jf-b0-34.ucode
firmware:       iwlwifi-9000-pu-a0-jf-a0-34.ucode
firmware:       iwlwifi-QuQnj-a0-hr-a0-34.ucode
firmware:       iwlwifi-QuQnj-a0-jf-b0-34.ucode
firmware:       iwlwifi-QuQnj-f0-hr-a0-34.ucode
firmware:       iwlwifi-Qu-a0-jf-b0-34.ucode
firmware:       iwlwifi-Qu-a0-hr-a0-34.ucode
parm:           fw_restart:restart firmware in case of error (default true) (bool)
parm:           fw_monitor:firmware monitor - to debug FW (default: false - needs lots of memory) (bool)
```

**Comment by jouyouyun** [comment]
Please pasted `sudo dmesg` outputs after wifi not worked, thanks!

**Comment by sdlins** [comment]
Last crash (right now). The session lasted only 10 minutes till the crashing.

[dmesg.log](https://github.com/linuxdeepin/developer-center/files/2800533/dmesg.log)

**Comment by jouyouyun** [comment]
> Last crash (right now). The session lasted only 10 minutes till the crashing.
> 
> [dmesg.log](https://github.com/linuxdeepin/developer-center/files/2800533/dmesg.log)

Try to update kernel to 4.20 from here: https://kernel.ubuntu.com/~kernel-ppa/mainline/v4.20.5/

**Comment by sdlins** [comment]
@jouyouyun we are using the new kernel for 4 day now with no problems anymore. I think the new kernel solved this issue. Thank you for your help. Closing for now.
