### ISSUE TITLE
deepin v23 WSL 默认没有做usrmerge

### ISSUE THREAD

**Issue by foresee-io** [linuxdeepin/developer-center#8393]
### SUMMARY | 问题概要

从 https://www.microsoft.com/store/productId/9P6HT7L0QGRH 下载安装的deepin WSL，默认没有做 usrmerge，例如将 /lib 链接到 /usr/lib。

**为什么建议默认做 usrmerge？**
- 为便于用户之后手动启用 systemd init
- systemd 使用 dbus，而 dbus 依赖于 usr-is-merged 软件包，“硬性要求”将 /lib 等目录改成软链接

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
Package: deepin WSL (deepin.deepinWSL_1.0.1.0_x64__66b9yfcxhz0dy) 1.0.1.0
```

### STEPS TO REPRODUCE | 复现步骤

略

### EXPECTED RESULT | 期望的结果

官方构建WSL、docker等镜像时，有开箱即用的 usrmerge，即：一开始就将 /lib, /bin 等目录改成软链接。

### ADDITIONAL INFORMATION | 额外补充

```
Package: dbus
Status: install ok installed
Priority: standard
Section: admin
Installed-Size: 181
Maintainer: Utopia Maintenance Team <pkg-utopia-maintainers@lists.alioth.debian.org>
Architecture: amd64
Multi-Arch: foreign
Version: 1.14.10-3
Provides: dbus-system-bus (= 1.14.10-3), default-dbus-system-bus
Depends: dbus-bin (= 1.14.10-3), dbus-daemon (= 1.14.10-3), dbus-system-bus-common (>= 1.14.10-3), usr-is-merged (>= 38~), libc6 (>= 2.34), libdbus-1-3 (= 1.14.10-3), libexpat1 (>= 2.1~beta3), libsystemd0
```

**Comment by UTsweetyfish** [comment]
> 从 https://www.microsoft.com/store/productId/9P6HT7L0QGRH 下载安装的deepin WSL，默认没有做 usrmerge，例如将 /lib 链接到 /usr/lib。

感谢反馈！deepin-wsl [1.2.0](https://github.com/deepin-community/deepin-rootfs/releases/tag/v1.2.0) 已经[做了 usrmerge](https://github.com/deepin-community/deepin-rootfs/commit/326c661b1d2e3abc2362983d22284dbf1e78f49a#diff-4d2a8eefdf2a9783512a35da4dc7676a66404b6f3826a8af9aad038722da6823R26)，但是还没有上传到应用商店。

如果需要使用的话，安装 usrmerge 即可；下一次上传到微软商店后应该就默认 usrmerge 了。

cc @chenchongbiao

**Comment by UTsweetyfish** [comment]
https://bbs.deepin.org/zh/post/272777

**Comment by UTsweetyfish** [comment]
我这里从微软应用商店下载了一下，已经 usrmerge 了。
