### ISSUE TITLE
安装编译环境报错

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/developer-center#84]
apt-get build-dep dde-control-center
报错：E: 您必须在您的 sources.list 写入一些“软件源”的 URI

**Comment by sbwtw** [comment]
源不对

**Comment by snyh** [comment]
如果需要用build-depin或者source指令　请在/etc/apt/sources.list中自行开启对应的src字段。
具体来说需要增加

deb-src [by-hash=force] http://packages.deepin.com/deepin unstable main contrib non-free
这么一行。

没有默认开启是因为大部分用户不需要。开启后对导致update增加一倍的数据量。

**Comment by snyh** [comment]
deb-src 相当于一个新的source   加入后需要执行下　apt-get update
