### ISSUE TITLE
dock not rendering properly on fashion mode

### ISSUE THREAD

**Issue by joaomarccos** [linuxdeepin/developer-center#841]
## Describe the bug

Dock not rendering properly on fashion mode

## To Reproduce

Set the dock mode to fashion mode and activate smart hide.

1. try use the dock

## Expected behavior

*Fluid transition with no trash on screen*

## Screenshots

![deepin-screen-recorder_select area_20190120145451](https://user-images.githubusercontent.com/7428221/51443169-79d95f00-1cc3-11e9-875d-e1b091411f96.gif)

## Enviroments:

![image](https://user-images.githubusercontent.com/7428221/51443175-970e2d80-1cc3-11e9-81aa-d6607dc226fd.png)

### Distro & Version

[Linux Deepin 15.9]

### Related package version

[dde-dock 2.0]

### Additional context

*the bug is happening in all positions of screen*

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
