### ISSUE TITLE
【deepin_V23_Release】【一般】【有空】【预发布测试】【玲珑】ll-cli run 命令启动应用时有大片警告信息

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#8411]
### SUMMARY | 问题概要

ll-cli run 命令启动应用时有大片警告信息
关联集成：#8382

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
验证镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240430/
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-linglong:1.5.0-1
```

### PRE-REQUIREMENT | 预置条件

安装上述最新镜像

### STEPS TO REPRODUCE | 复现步骤

1.升级linglong-bin到1.5.0-1
2.ll-cli search . (搜索可以安装的玲珑应用)
3.ll-cli linstall org.videolan.vlc
4.ll-cli run org.videolan.vlc 观察终端输出

### OBSERVED RESULT | 观察到的结果

1.ll-cli run 命令启动应用时有大片警告信息
![截图_选择区域_20240507140413](https://github.com/linuxdeepin/developer-center/assets/96415804/0efc3539-3ab1-4709-97ca-386e7b5ae4c6)

### EXPECTED RESULT | 期望的结果

1.ll-cli run 命令启动应用没有警告，正常执行

**Comment by babyfengfjx** [comment]
@dengbo11  请安排优化~

**Comment by dengbo11** [comment]
@black-desk , 这个错误信息帮忙优化下

**Comment by vivianxf** [comment]
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1483:/dde/testing/ ./
验证步骤：提单的步骤
验证现象：ll-cli run 命令启动应用正常显示没有大片警告信息（应用正常运行）
验证结果：通过
