### ISSUE TITLE
【deepin_V23_Release】【一般】【有空】【预发布测试】【玲珑】ll-cli install 命令安装的部分应用在启动器为黑图标

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#8413]
### SUMMARY | 问题概要

ll-cli install 命令安装的部分应用在启动器为黑图标
关联集成：https://github.com/linuxdeepin/developer-center/issues/8382

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
验证镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240430/
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-linglong:1.5.0-1
```

### STEPS TO REPRODUCE | 复现步骤

1.升级linglong-bin到1.5.0-1
2.ll-cli search . (搜索可以安装的玲珑应用)
3.ll-cli linstall org.videolan.vlc
4.观察启动器图标展示

### OBSERVED RESULT | 观察到的结果

1.ll-cli install 命令安装的部分应用在启动器为黑图标
![截图_选择区域_20240507133646](https://github.com/linuxdeepin/developer-center/assets/96415804/479a9880-5449-4ee1-affd-c9d96810fbcb)

### EXPECTED RESULT | 期望的结果

1.ll-cli install 命令安装的部分应用在启动器图标正常显示

**Comment by babyfengfjx** [comment]
@kegechen  看这些玲珑应用的图标问题是属于哪边处理，如果需要邓博这边处理，可以备注下帮忙转交。

**Comment by kegechen** [comment]
https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html
图标安装应该放到合适的位置，不要直接放到 `/usr/share/icons/ ` 顶层目录 至少需要放到 `hicolor`

如 `/usr/share/icons/hicolor/96x96/apps/wemeet.svg`

相关规范 
- https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html

**Comment by dengbo11** [comment]
> https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html 图标安装应该放到合适的位置，不要直接放到 `/usr/share/icons/ ` 顶层目录 至少需要放到 `hicolor`
> 
> 如 `/usr/share/icons/hicolor/96x96/apps/wemeet.svg`
> 
> 相关规范
> 
> * https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html

参考这个改下

**Comment by dengbo11** [comment]
看下这个(https://github.com/linuxdeepin/developer-center/issues/8407)是不是一类问题

**Comment by kamiyadm** [comment]
只能挨个应用修了，至于没有图标是不是应该显示个默认图标，而不是直接是黑的

**Comment by kegechen** [comment]
> 只能挨个应用修了，至于没有图标是不是应该显示个默认图标，而不是直接是黑的

黑的就是默认图标

**Comment by kegechen** [comment]
给 dde-shell  中加上一个 `QIcon::setFallbackSearchPaths` 增加 icons 查找的 fallback 目录到 `/xxx/share/icons/` 顶层目录 可以解决。 在dtk中加不太好。。

**Comment by xuqi27837288** [comment]
【验证环境】：v23 RC2镜像
镜像：https://cdimage.uniontech.com/community/releases/23-RC2/amd64/deepin-desktop-community-23-RC2-amd64.iso
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.25-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过

![截图_选择区域_20240625152029](https://github.com/linuxdeepin/developer-center/assets/62528742/ae9c7594-1aaf-4b6d-9ec2-6bf37c7a59e4)
