### ISSUE TITLE
Feature Request : Kinetic pointer Movement ... just give a nudge/push to the pointer on the touchpad and the pointer glides in that direction !

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#842]
## Summary

Kinetic pointer Movement ... just give a nudge/push to the pointer on the touchpad and the pointer glides in that direction !!!

I believe its similar kinetic scroll except that instead of the page gliding(scrolling down as if it was spun on a wheel) the cursor moves/glides across the screen.

## Feature details

I remember this worked on my synaptic touchpad(with their driver) in windows ... one had to just push the cursor using the touchpad and the pointer would glide in that direction ... there was an option to control the sensitivity / friction level ... lower the friction the faster the cursor would glide on the screen covering a longer distance ...

## Affected Hardware

I remember this is possible on a Synaptic hardware/driver

## Implementation in Other Systems

a few Kinetic scroll implementation are available for certain browser ... all android smartphones have this kinetic scroll across the device and application. Except that i am requesting for the cursor movement in place of the screen movement.

I have raised this request even at the `libinput` [project page](https://gitlab.freedesktop.org/libinput/libinput/issues/227) ...

Given that Deepin Team is dishing out features and applications that are hard to find on linux ... i guess this could be something you could consider ... 

**I believe this kinetic pointer/cursor movement will make the UX will complement the eye candy(glassy) UI of deepin !!!**

**Comment by aiamuzz** [comment]
@jouyouyun ... @hualet ... @BLumia ... @wangjia12 ...

seems the libinput team resources are limited spread thin(as what their project page suggests) ... **but this feature could exponentially improve the UX and complement our OSeS eye candy UI !!!** ... Don't you think ?

**Comment by jouyouyun** [comment]
> @jouyouyun ... @hualet ... @BLumia ... @wangjia12 ...
> 
> seems the libinput team resources are limited/spread thin(as what their project page suggests) ... **but this feature could exponentially improve the UX and complement our OSeS eye candy UI !!!** ... Don't you think ?

Do you mean the pointer acceleration speed?

**Comment by aiamuzz** [comment]
> > @jouyouyun ... @hualet ... @BLumia ... @wangjia12 ...
> > seems the libinput team resources are limited/spread thin(as what their project page suggests) ... **but this feature could exponentially improve the UX and complement our OSeS eye candy UI !!!** ... Don't you think ?
> 
> Do you mean the pointer acceleration speed?

no @jouyouyun  ... its not cursor acceleration speed ...

Imagine a perfectly flat table(this is our laptop touchpad) with a 'flat disk'(this is our cursor pointer) ... now imagine if you just put your finger on this flat disk and and moved a little and lifted your finger ... notice how the disk slides across this flat table ? I am referring to this movement of the disk on the table ... which keeps moving depending on the amount of force applied before lifting the finger ...

If you just make small flicks on the touchpad the cursor will glide in the direction of the push ... and putting the finger back on the touchpad will stop the glide of the cursor instantly !!!

Please go through [this thread](https://ubuntuforums.org/archive/index.php/t-1009310.html) ... i believe they have tried to hack their way into this functionality !!!

**Comment by aiamuzz** [comment]
I believe its called ... Pointer -> Momentum settings ... for synaptic touchpad ...

https://www.youtube.com/watch?v=xKsN4FoGQR4

**Comment by aiamuzz** [comment]
some more info on this ...

https://github.com/IOrot/ggglide

**Comment by aiamuzz** [comment]
@jouyouyun ... where you able to understand this feature i am talking about ?
let me know if its still not clear ... i'll see if i can find a video of this pointer movement action ...

**Comment by jouyouyun** [comment]
@aiamuzz See [here](https://wayland.freedesktop.org/libinput/doc/latest/faqs.html#kinetic-scrolling-does-not-work), the kinetic-scrolling needed the GUI libraries to implement.
There is a [patch](https://gist.github.com/craigcabrey/32bce9ee830f076cd1a32b2df2fee9b3) for gtk 3.20 from [here](https://askubuntu.com/questions/849714/libinput-scrolling-behaviour-config), you can try.

Alse see [libinput scrolling](https://wayland.freedesktop.org/libinput/doc/latest/scrolling.html#scroll_sources)

We will investigate and discuss this feature.

@wangjia12

**Comment by aiamuzz** [comment]
> @aiamuzz See [here](https://wayland.freedesktop.org/libinput/doc/latest/faqs.html#kinetic-scrolling-does-not-work), the kinetic-scrolling needed the GUI libraries to implement.
> There is a [patch](https://gist.github.com/craigcabrey/32bce9ee830f076cd1a32b2df2fee9b3) for gtk 3.20 from [here](https://askubuntu.com/questions/849714/libinput-scrolling-behaviour-config), you can try.
> 
> Alse see [libinput scrolling](https://wayland.freedesktop.org/libinput/doc/latest/scrolling.html#scroll_sources)
> 
> We will investigate and discuss this feature.
> 
> @wangjia12

hahahaha ... its very easily confused ... while i don't mind ... kinetic scrolling ... If this option was implemented as well on deepin.

But what i have requested is for 'Kinetic Pointer Movement' ... 'Kinetic Scrolling' is another feature ... i wouldn't mind both ...

Please find the 'Kinetic Pointer Movement' in the following screen grab ... notice how the mouse pointer keeps moving all be itself and slowly comes to stop ... even though the finger is not on the touchpad ... a small push lifting the finger away the cursor travel the distance of the push ... also notice how the cursor rolls/moves in a straight line ...  

![momentumrecord](https://user-images.githubusercontent.com/3283676/51955123-af6f0c80-2468-11e9-9c75-343f63aeb564.gif)

If i am not wrong ... this thread discusses that ... https://ubuntuforums.org/archive/index.php/t-1009310.html ... and this is probably the code that is being discussed in this thread ... https://ubuntuforums.org/archive/index.php/t-1009310.html

**Comment by aiamuzz** [comment]
@jouyouyun ... come to think of it ... given how deepin and all other new age linux distros that have been developed post the Android era, with UI's and UX's inspired from android UI/UX ... kinetic movement/motions should have already been implemented right from the start as android sroll is kinetic right from the begining ... :smile: ...

**Comment by BLumia** [comment]
Hmm, just curious, do you think this feature is useful at least to *you*?

**Comment by BLumia** [comment]
> @BLumia ... you should try it yourself ... if you have a windows machine close by ... use it for 2 days and the 3rd day working on your favorite Deepin OS will look and feel primitive !!!

Actually I didn't found "Kinetic Pointer Movement" on my Windows 10 (Home) installation. Does this feature on windows got another name than "Kinetic Pointer Movement"?

**Comment by aiamuzz** [comment]
> > @BLumia ... you should try it yourself ... if you have a windows machine close by ... use it for 2 days and the 3rd day working on your favorite Deepin OS will look and feel primitive !!!
> 
> Actually I didn't found "Kinetic Pointer Movement" on my Windows 10 (Home) installation. Does this feature on windows got another name than "Kinetic Pointer Movement"?

oh ... i am sorry ... on windows 10 go to ... mouse & pointer settings -> Advanced settings link on the right ... find the touchpad driver ... double click or click on properties ... you'll get the synaptic touchpad settings control window ... click on the advanced tab ... you should find 'momentum' setting somewhere there ...

If you don't try this regedit hack ... https://www.youtube.com/watch?v=YetEUbv_7ps

**Comment by aiamuzz** [comment]
> > @BLumia ... you should try it yourself ... if you have a windows machine close by ... use it for 2 days and the 3rd day working on your favorite Deepin OS will look and feel primitive !!!
> 
> Actually I didn't found "Kinetic Pointer Movement" on my Windows 10 (Home) installation. Does this feature on windows got another name than "Kinetic Pointer Movement"?

oh ... you found it ?
I don't know about other hardware ... but for Synaptic Touch pad hardware the settings is called 'Momentum' setting which needs to be checked ... you can find the GUI for the same ...

![deepinscreenshot_select-area_20190130143200](https://user-images.githubusercontent.com/3283676/51970015-d7c42e80-249b-11e9-975f-8e31767b2ea5.png)
![deepinscreenshot_select-area_20190130143142](https://user-images.githubusercontent.com/3283676/51970016-d85cc500-249b-11e9-923c-6a38e181f800.png)

**Comment by BLumia** [comment]
No I don't have this driver, nor this driver property menu.

But imo I don't think this will be a useful feature, it may *looks* cool, but not as useful as other features like "Kinetic Scrolling" you've mentioned above.

**Comment by aiamuzz** [comment]
> No I don't have this driver, nor this driver property menu.

so you were not able to try it out ?

 
> But imo I don't think this will be a useful feature, it may _looks_ cool, but not as useful as other features like "Kinetic Scrolling" you've mentioned above.

Well you can't tell its not useful until you actually try ... :smile: ... you need to try it to understand how convenient it is(take me up on a 2 day use challenge) ... its an honest challenge to convince people who think it may not be useful ... and its usage even on Windows isn't high ... its buried so deep in the settings that its difficult to find and enable it ... an average user will not even know if its existence when its hidden so deep inside ...

Come to think of it ... linux community has never had this as a straight forward option to check and unheck ... it was always complicated to get it up and working ... so linux users as usual just accept its absence !!!

PS : it was a daily settings when i was on windows ... after i moved to linux ... it was a compromise due to non availability ... almost all linux users are open to the idea of accepting the non-availability of certain options and functionalities ...

**Comment by BLumia** [comment]
> have you tried looking for it in this option ? ... **Additional Settings** will throw a window ... in that you have tabs for the synaptic touchpad driver ... and the properties button will take you to the above 1 of 3 settings window from my earlier post ...

My touchpad is a HID-compliant touchpad, not a Synaptic touchpad, so of course I don't have a Synaptic-only device setting tab.

**Comment by aiamuzz** [comment]
@BLumia ... @jouyouyun ... @hualet ...

Weekend is here ... time to take me up on my dare ... go ahead and try the kinetic pointer movement (Momentum) setting ... on your Windows 10 OS ... hopefully after that you'll know what i am talking about and how nice of a feature/enhancement that could prove to be !!!

**Comment by wangjia12** [comment]
Isn't this way difficult to accurately control where the mouse is?

**Comment by aiamuzz** [comment]
> Isn't this way difficult to accurately control where the mouse is?

you need to use it to know it ... @wangjia12 ... use it for a day and then let me know if it was difficult to control accurately ? ... :smile:

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
