### ISSUE TITLE
【窗口管理器】三方应用在窗口未识别到正确图标时不显示图标。

### ISSUE THREAD

**Issue by meiyixiang** [linuxdeepin/developer-center#8427]
### SUMMARY | 问题概要

![企业微信截图_17151392429471](https://github.com/linuxdeepin/developer-center/assets/75475994/d637850d-4989-4dad-97ff-5bb310c86a2f)
如：wps应用窗口在无法识别到WPS时，采用了设计提供图标显示。
用户反馈此图标无法理解，对此问题进行修改，无法识别到图标时不显示代替图标，没有时则不显示。

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
1
```

### PRE-REQUIREMENT | 预置条件

1

### STEPS TO REPRODUCE | 复现步骤

1

**Comment by baicailio** [comment]
镜像1：https://cdimage.uniontech.com/community/releases/23-Beta3/ 升级到最新的RC内测版本(2024.04.30)
仓库：
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1363:/dde/testing/ ./
验证步骤：提单步骤
验证现象：WPS许可协议左上角不显示图标
![wps](https://github.com/linuxdeepin/developer-center/assets/166582166/760efeeb-4bf8-437e-86b8-5fa256efcd0e)
验证结果：回归通过
