### ISSUE TITLE
Last update Bricked my System

### ISSUE THREAD

**Issue by antechdesigns** [linuxdeepin/developer-center#843]
Just updated my archlinux with deepin desktop

**Packages (23)** 
deepin-api-3.16.0-1  
deepin-control-center-4.9.2-1  
deepin-daemon-3.22.0-1  
deepin-desktop-schemas-3.11.0-1
deepin-dock-4.8.9-1  
deepin-file-manager-1:4.7.5-1  
deepin-image-viewer-1.3.8-1  
deepin-launcher-4.6.4-1
deepin-metacity-3.22.24-1  
deepin-movie-1:3.2.19-1  
deepin-music-3.1.14-1  
deepin-network-utils-0.0.9-1
 deepin-polkit-agent-0.2.4-1  
deepin-qt5dxcb-plugin-1.1.23-1  
deepin-screenshot-4.1.7-1
deepin-session-ui-4.8.7-1  
deepin-system-monitor-1.4.8.1-1  
deepin-terminal-3.2.1-1  
dtkcore-1:2.0.9.15-1
dtkwidget-2.0.9.15-1  
lib32-libdrm-2.4.97-1  
mongo-c-driver-1.13.1-1  
startdde-3.11.0-1

Now I can not boot into system, just flashing boot up text, I cant even get into a tty to roll back ;(

**Comment by dance707** [comment]
Same here, I managed to get tty in my other kernel. Disabled lightdm, installed and enabled sddm. Boots fine now, though there is strange beep.

Jan 26 02:17:42 a755.localdomain systemd-coredump[3805]: Process 3792 (lightdm-deepin-) of user 620 dumped core.
                                                         
                                                         Stack trace of thread 3792:
                                                         #0  0x00007f4830cf46a3 _Unwind_Resume (libgcc_s.so.1)
                                                         #1  0x0000561cc2da1ac3 n/a (lightdm-deepin-greeter)
                                                         #2  0x0000561cc2dfc15e n/a (lightdm-deepin-greeter)
                                                         #3  0x0000561cc2da4f24 main (lightdm-deepin-greeter)
                                                         #4  0x00007f4830b41223 __libc_start_main (libc.so.6)
                                                         #5  0x0000561cc2da528e n/a (lightdm-deepin-greeter)

**Comment by dance707** [comment]
upgraded deepin-session-ui (4.8.7-1 -> 4.8.7-2)
lightdm okay now, and beep fixed too

**Comment by antechdesigns** [comment]
Whats best way to fix this for me, I can not get to a tty, all I get is flashing boot up text.

Thanks
Ant

**Comment by felixonmars** [comment]
You may try to login into single-user mode (appending "single" after the kernel line in grub) if you have set a root password.

Otherwise you can try the "init=/bin/bash" hack and temporarily disable lightdm.

**Comment by antechdesigns** [comment]
I managed to fix it, did chroot and downgraded to deepin-session-ui- to 4.8.6-1

That was scary, please don't do that again ;)

**Comment by felixonmars** [comment]
I'll restore the [community-testing] phase for DDE.

**Comment by antechdesigns** [comment]
@felixonmars 
should 'deepin-session-ui-4.8.7-2' be in the repos? I don't see it, or do we have to wait?
If you need help with the community-testing count me in ;)

**Comment by dance707** [comment]
> I'll restore the [community-testing] phase for DDE.

Community-testing for DDE is something other than deepin internal testing ?

**Comment by felixonmars** [comment]
@antechdesigns You may need to find a mirror that updates more often.

@dance707 Yes, serve as a safe guard for unstable packages.

**Comment by dance707** [comment]
> @antechdesigns You may need to find a mirror that updates more often.
> 
> @dance707 Yes, serve as a safe guard for unstable packages.

Okay Thank You, contact me at  QQ, or TG or email if you need help there.
