### ISSUE TITLE
org.deepin.browser 6.5.3版本

### ISSUE THREAD

**Issue by hwb55** [linuxdeepin/developer-center#8430]
### package information | 软件包信息

org.deepin.browser  6.5.3

### Package repository address | 软件包仓库地址

deb [trusted=yes] http://aptly.uniontech.com/pkg/nonfree-apricot/release-candidate/YnJvd3NlcjIwMjQtMDMtMjYgMjA6MTA6NDY/ unstable non-free
 
### changelog | 更新信息

修复新标签页会概率出现搜索框搜索引擎无图标的情况

**Comment by hwb55** [comment]
@Zeno-sole

**Comment by babyfengfjx** [comment]
@baicailio  请开展集成验证。

**Comment by babyfengfjx** [comment]
@dengbo11  转成玲珑格式后再转测。

**Comment by dengbo11** [comment]
# 浏览器和邮箱转玲珑提测

## 测试步骤:
1. 安装最新版本的玲珑;
2. 修改玲珑仓库*`ll-cli repo modify https://repo-dev.cicd.getdeepin.org --name old`*
3. 安装浏览器和邮箱;
4. 测试浏览器和邮箱功能使用是否正常

**Comment by babyfengfjx** [comment]
@baicailio  请开展集成验证。

**Comment by myml** [comment]
@baicailio  还有日历也会以玲珑包的方式集成到镜像，仓库也是 old，安装方式 ll-cli install org.dde.calendar

**Comment by baicailio** [comment]
邮箱，日历，浏览器，0509的镜像都安装失败  https://github.com/linuxdeepin/developer-center/issues/8471

**Comment by dengbo11** [comment]
测试步骤:
1. 全新镜像安装最新版本玲珑
2. 回归以下问题:
   - https://github.com/linuxdeepin/developer-center/issues/8474
   - https://github.com/linuxdeepin/developer-center/issues/8471

**Comment by baicailio** [comment]
0509镜像上述2个问题单已验证通过
