### ISSUE TITLE
【deepin_V23_Release】【一般】【正常】【预发布测试】【 DDE】个性化主题，设置图标主题为ePapirus时，任务栏上控制中心与应用商店显示为小黑块

### ISSUE THREAD

**Issue by kobe337** [linuxdeepin/developer-center#8436]
### SUMMARY | 问题概要

个性化主题，设置图标主题为ePapirus时，任务栏上控制中心与应用商店显示为小黑块

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-Beta3/
应用版本：dde-shell: 0.0.16
```

### STEPS TO REPRODUCE | 复现步骤

1. 打开控制中心-个性化-主题，设置图标主题为ePapirus,查看图标显示状态

### OBSERVED RESULT | 观察到的结果

个性化主题，设置图标主题为ePapirus时，任务栏上控制中心与应用商店显示为小黑块
![kzzxyysd](https://github.com/linuxdeepin/developer-center/assets/17869922/e4a21f38-c904-4a7b-94ff-6709cc52fb2a)

### EXPECTED RESULT | 期望的结果

个性化主题，设置图标主题为ePapirus时，任务栏上控制中心与应用商店图标能够正常展示

**Comment by babyfengfjx** [comment]
@kegechen  这个可以优先处理。

**Comment by kegechen** [comment]
![image](https://github.com/linuxdeepin/developer-center/assets/23466548/ece2efad-01ea-4d1c-9d70-1cb2cb5747b2)

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240509
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.25-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
