### ISSUE TITLE
在文件管理器中双击deb包无法正常调用软件包管理器完成安装

### ISSUE THREAD

**Issue by lolimay** [linuxdeepin/developer-center#844]
## 缺陷描述
1. 在文件管理器中双击deb包无法正常调用软件包管理器完成安装
2. 打开软件包管理器，将deb包拖动到软件包管理器窗口上可以完成安装

## 复现步骤

复现步骤为:

1. 打开文件管理器
2. 点击 `code-insiders_1.31.0-1548404281_amd64.deb`
3. 光标开始转圈
4. 未成功调用软件包管理器

## 期望行为

双击deb包，成功调用软件包管理器。

## 截图

![peek 2019-01-26 14-26](https://user-images.githubusercontent.com/32427260/51783547-80118480-2176-11e9-8207-dbe0630d3b2c.gif)

## 复现环境:

复现率100%

### 发行版以及版本

deepin 15.9

### 相关的软件包版本

deepin-deb-installer 1.2.9

**Comment by liuwen123** [comment]
能否上传一下deb包呢？

**Comment by lolimay** [comment]
通过看日志，找到原因了，原来是deb包的默认打开方式被修改成其它应用了，而不是软件包管理器，所以导致无法正常调用 😂

打扰了！
