### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【安装器】【UI】正在配置电脑 图片替换

### ISSUE THREAD

**Issue by Z-Araio** [linuxdeepin/developer-center#8448]
### SUMMARY | 问题概要

- [ ] 电脑图片阴影问题，替换图片

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
6.0.47
```

### PRE-REQUIREMENT | 预置条件

4k  2.5k

### STEPS TO REPRODUCE | 复现步骤

配置电脑

### OBSERVED RESULT | 观察到的结果

<img width="1494" alt="image" src="https://github.com/linuxdeepin/developer-center/assets/169126733/e83702a0-c832-4d7f-9157-2ae3aa5bc13b">

**Comment by baicailio** [comment]
镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20240520/deepin-23-beige-rc-amd64-20240520-150833.iso
验证步骤：提单步骤
验证现象：4K屏上述页面已按照上述设计要求修改
验证结果：回归通过
