### ISSUE TITLE
多屏下有时会出现窗口缺失

### ISSUE THREAD

**Issue by lolimay** [linuxdeepin/developer-center#845]
## 缺陷描述

经过长期使用发现，仅 `Chrome` 和 `VS Code` 会偶尔出现其窗口缺失闪烁的现象，具体现象描述请看GIF。

## 复现步骤

1. HDMI1
打开 Chrome
2. eDP1
打开 VS Code 或 Chrome

    操作 HDMI1 屏幕的 Chrome，VGA1屏幕的 Chrome 会有小概率出现屏幕缺失闪烁的情况。

## 期望行为

不要出现窗口缺失闪烁情况

## 截图
![result](https://user-images.githubusercontent.com/32427260/51790673-884bdd00-21d3-11e9-9437-17a79ecdf856.gif)

![anim-opt](https://user-images.githubusercontent.com/32427260/51785925-1efaa880-2198-11e9-8ba6-4add4bcb159c.gif)

## 复现环境:

- 屏幕布局

![_ _20190126182854](https://user-images.githubusercontent.com/32427260/51785935-3fc2fe00-2198-11e9-9c7c-b661406ad06b.png)

### 发行版以及版本

Deepin 15.9

### 相关的软件包版本
- deepin-desktop-base/panda,panda,now 2019.01.16-1 
- deepin-desktop-schemas/panda,now 3.10.0-1 amd64

### 其他内容
- 猜测: 和 webkit 有关? 因为到目前为止只发现了 chrome 和 VS Code 有这种问题
- 和多屏绝对有关系，难道又是显卡驱动的锅? 不是很懂这块，问题排查或许很麻烦，但我会全程配合，估计要麻烦深度的工程师了 >_<

**Comment by lolimay** [comment]
我把窗管特效关了用几天试试，这个BUG复现率不是很高。



---
![peek 2019-01-30 15-31](https://user-images.githubusercontent.com/32427260/51965377-51f8b100-24a4-11e9-9b40-9170b2fdb806.gif)

（逃...

**Comment by lolimay** [comment]
测试了几天之后，把特效关闭了确实不会有窗口抖动、缺失的问题。应该是窗口特效的锅?

**Comment by hualet** [comment]
大概是的

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
