### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【安装器】【UI】 全盘安装界面问题

### ISSUE THREAD

**Issue by Z-Araio** [linuxdeepin/developer-center#8452]
### SUMMARY | 问题概要

- [x] 1.磁盘内容区太小了，多数磁盘名称显示不全，宽度加大，保证大多数名称可以显示完整
- [x] 2.磁盘内容区选中效果太重了，选中效果弱化 用灰色
- [ ] 3.磁盘内容区背景圆角小了
- [x] 4.系统盘 数据盘选项框左右没有和上方背景对齐，宽度要保持一致
- [x] 5.系统篇下拉框背景圆角没有重合
- [x] 6.调整系统盘icon距离操作区太远，建议放到选项框旁边

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
6.0.47
```

### PRE-REQUIREMENT | 预置条件

4k 2.5k

### STEPS TO REPRODUCE | 复现步骤

全盘安装

### OBSERVED RESULT | 观察到的结果

<img width="1793" alt="image" src="https://github.com/linuxdeepin/developer-center/assets/169126733/9ed9f975-592c-4e03-a653-2dec90d8eaa4">

### EXPECTED RESULT | 期望的结果

<img width="822" alt="image" src="https://github.com/linuxdeepin/developer-center/assets/169126733/d881e234-98ce-4626-b87d-54ba84438943">
<img width="1280" alt="image" src="https://github.com/linuxdeepin/developer-center/assets/169126733/cf7c5715-97e1-470f-b921-cea8ea989517">

**Comment by baicailio** [comment]
镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20240520/deepin-23-beige-rc-amd64-20240520-150833.iso
验证步骤：提单步骤
验证现象：第3条和第5条没改，其余验证通过
验证结果：回归通过
