### ISSUE TITLE
Network Error in Store

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#846]
## Describe the bug

The Store displays the "Network Error" message. Not allowing access.

## To Reproduce

The problem starts randomly (after formatting, cleaning the system and/or "suddenly").

## Expected behavior

Deepin Store working perfectly.

## Screenshots
Error Displayed:
![captura de tela_20190127211918](https://user-images.githubusercontent.com/45263160/51808293-3bbadd00-2279-11e9-9521-5bc2beb01bf4.png)

Before Cleaning:
![captura de tela_deepin-deepinid-client_20190127201557](https://user-images.githubusercontent.com/45263160/51808309-61e07d00-2279-11e9-90a1-6bdc0a9db02c.png)

Now, it looks like it connects to Deepin ID ... but it does not access the data:
![captura de tela_20190127212217](https://user-images.githubusercontent.com/45263160/51808333-a79d4580-2279-11e9-8358-768a6e580ef2.png)

### Distro & Version
Deepin 15.9

### Related package version
deepin-appstore 5.2.0.4-1

### Additional context
When the Lodge did not carry; I did the cleaning process:
1. "Clear the Cache" in the Store Application;
2. Triggered all cleaning media offered by Deepin Repair.
3. Force cleanup via Terminal, via "sudo apt autoremove && sudo apt remove && sudo apt autoclean";
4. And loaded the new cache, via "sudo apt update && sudo apt dist-upgrade".
And the Lodge was working again. But this time, there was no success. I restarted the computer several times during the process.

For some time now, a few other users have reported the same problem. Many opted for another Linux distribution (even formatting Deepin again, the error persisted) ... and another specific one, when restoring the system, returned to normal.

In my case, I was doing the cleaning with BleachBit (from Deepin Store) - the only function I did not use, was "free space cleanup". I do not think it's the cause of the problem... Well, I've done it several times and it's never happened. And there are a few other users, with different types of usage... and the same problem.

[deepin-feedback-cli-Deepin-15.9-all-20190127-222152.tar.gz](https://github.com/linuxdeepin/developer-center/files/2800977/deepin-feedback-cli-Deepin-15.9-all-20190127-222152.tar.gz)

**Comment by alexwender1** [comment]
A little more than 2 hours passed ... and Store was working again.

**Comment by alexwender1** [comment]
> @alexwender1 still having this issue?

The problem disappeared after a few hours. During that time I left my computer idle, unused.
In my SourceList I have 2 mirrors from my country.

Really, I do not know what happened. But everything is working normally, again!

The first reports I saw ... These users found it easier to swap the Linux distribution, instead of having patience and waiting.

**Comment by hualet** [comment]
There's always something that worth waiting for :)
Closing...

**Comment by Am86Shekari** [comment]
I have this problem in new Deepin 20.2.2 app store

**Comment by Am86Shekari** [comment]
![image](https://user-images.githubusercontent.com/80213487/125195302-5414eb80-e26a-11eb-9b43-8306574dc395.png)

**Comment by Am86Shekari** [comment]
but my internet it's OK and opening the sites
