### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【DDE】【任务栏/启动器】【UI】 快捷面板部分 问题

### ISSUE THREAD

**Issue by wangruoxuan3782** [linuxdeepin/developer-center#8470]
### SUMMARY | 问题概要

- [x] 音乐打开时，文件类型的角标黑了
- [ ] 亮度-显示设置button样式不对
- [ ] 面板拖动时，背景太实了
- [ ] 拖动后图标在任务栏显示不完全且有白色的背景
- [ ] 蓝牙面板背景没有透明模糊效果
- [ ] 声音-设备选中时候，背景不需要变蓝色 其他的也是
- [ ] 返回图标太小
- [ ] 声音图标没有适配深色模式
- [ ] 快捷面板内部小面板描边太实了
- [ ] - [ ]快捷面板面板图标下圆圈背景颜色不对
- [ ] 退出音乐应用后，音乐面板没消失
- [x] 屏幕键盘的图标不对
- [ ] 网络、蓝牙的图标也换成最新的

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
dde-shell 0.0.16
```

### STEPS TO REPRODUCE | 复现步骤

查看快捷面板

### OBSERVED RESULT | 观察到的结果

![编组 25](https://github.com/linuxdeepin/developer-center/assets/162073918/80100a66-9901-4188-beac-5f0989ea381d)
![编组 31](https://github.com/linuxdeepin/developer-center/assets/162073918/b6e32e8f-97bd-4f14-84dd-4225cf1802c7)
![编组 26](https://github.com/linuxdeepin/developer-center/assets/162073918/722c7ffb-20ce-463b-95cd-b943f4a2bc10)
![截图_选择区域_20240509132705 2](https://github.com/linuxdeepin/developer-center/assets/162073918/cc609929-5451-44b7-a6bf-55e37714d6fc)
![编组 28](https://github.com/linuxdeepin/developer-center/assets/162073918/cbde3142-affd-43e9-b78d-10f7f8dc53ae)
![编组 27](https://github.com/linuxdeepin/developer-center/assets/162073918/154495b4-99fa-4403-8972-75c7a4373701)
![编组 32](https://github.com/linuxdeepin/developer-center/assets/162073918/b2be6ca8-c151-4b24-997c-425a17dc906b)
![编组 33](https://github.com/linuxdeepin/developer-center/assets/162073918/b79e1149-6540-4134-a0ab-8660f59ce68a)
![编组 30](https://github.com/linuxdeepin/developer-center/assets/162073918/990266bb-06d5-47cf-ba96-be08b9c78ec4)

### EXPECTED RESULT | 期望的结果

<img width="406" alt="image" src="https://github.com/linuxdeepin/developer-center/assets/162073918/e01ee1ef-aacd-4c9f-9abf-d415dae4d2f7">

**Comment by luodeepin** [comment]
验证通过
dde-shell 0.0.20
![截图_选择区域_20240514104821](https://github.com/linuxdeepin/developer-center/assets/96416089/dce55403-71be-4c61-a031-dd6dc0f4d1d0)

**Comment by luodeepin** [comment]
设计确认存在多处没有修复
![image](https://github.com/linuxdeepin/developer-center/assets/96416089/6896e259-097b-485c-bad1-fdbca24ccdf6)

**Comment by tsic404** [comment]
请在新版快捷面板上回归

**Comment by wangruoxuan3782** [comment]
快捷面板样式与1070同步，相关UI问题已另外提单
