### ISSUE TITLE
[Feature Request] 深度终端tab标题仅显示当前目录名

### ISSUE THREAD

**Issue by lolimay** [linuxdeepin/developer-center#848]
默认情况下，深度终端的 tab 标题是**完整路径名**，如下图所示:

![_ _20190128161122](https://user-images.githubusercontent.com/32427260/51822765-3d87ad80-2318-11e9-8684-80f5b1ad2ec3.png)

这样做的好处是，能让用户快速地识别出这个标签页，如对于两个标签页，标题分别为 `~/Web/Projects/AnSpeed` 和 `~/Downloads`，用户仅看标题名就指导两个tab分别是干嘛的(第一个用于Web项目的开发，第二个是编辑下载目录下的文件)。
但是，当目录的 `path` 过深时，这种优势荡然无存，看下图:

![_ _20190128162553](https://user-images.githubusercontent.com/32427260/51823500-98220900-231a-11e9-8748-8dee0cc5aa60.png)

这三个标签页的标题几乎完全一样，我无法一眼分辨出哪个是我想要切换的标签页。如果，深度终端的 tab 页标题仅显示**当前目录名**，如下图所示:

![_ _20190128163829](https://user-images.githubusercontent.com/32427260/51823770-50e84800-231b-11e9-88ed-cb20b121e0d3.png)

这样，则简洁清爽很多，而且没有损失过多的信息。

------
楼下哥们提到的 `user@machine`，我其实也觉得比较占空间，尤其是当终端窗口宽度很小时，这种问题特别突出，如下图。

![_ _20190128164538](https://user-images.githubusercontent.com/32427260/51824051-3bbfe900-231c-11e9-99e1-b154bd7ad42f.png)
以我的情况为例，`lolimay@lolimay-PC:` 足足占了 19 个字符宽度，如果可以换成**箭头**(或者普通用户是 `$`，root 用户是 `#`，这也比较符合大部分用户的习惯)，则可以省下 18 个字符宽度。而且大部分情况下，我们都是本地操作，`lolimay@lolimay-PC:`  这个信息不是很有必要。
但是当远程 ssh 时， `user@machine` 这个信息又是必不可少的。更深入的话，有必要单独开个 issue 讨论下。

**Comment by aiamuzz** [comment]
> I found an approach that can change the terminal title whenever we switch the workspace, see
> 
> ```shell
> cd()
> {
>     builtin cd "$@"
>     # ls
>     path=`pwd`
>     echo -ne '\033]2;'${path##*/}'\007' # change terminal title to the current workspace
> }
> ```

@lolimay ... is this a script we need to run every time, or is it a permanent change to be made in a configuration file ?

can you please help us implement this ?

**Comment by aiamuzz** [comment]
thanks @lolimay ... this works perfectly for me after adding it to the `.bashrc` as a permanent feature ...

```
# Reduce the actual path terminal prompt to a short $ prompt

PS1="\[\033[1;32m\]$ \[\033[0m\]"

# Terminal showing only the current folder name in the terminal title bar
cd()
{
    builtin cd "$@"
    # ls
    path=`pwd`
    echo -ne '\033]2;'${path##*/}'\007' # change terminal title to the current workspace
}
```

**Comment by lolimay** [comment]
@aiamuzz You're welcome :)

**Comment by aiamuzz** [comment]
> @aiamuzz You're welcome :)

seems you have an excellent helper here ... http://ezprompt.net/

**Comment by lolimay** [comment]
> > @aiamuzz You're welcome :)
> 
> seems you have an excellent helper here ... http://ezprompt.net/

Wow, it's a very useful online tool for generating PS1 content!

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
