### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【 AM】文件管理器默认打开的是主目录而不是计算机

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#8482]
### SUMMARY | 问题概要

文件管理器默认打开的是主目录而不是计算机

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240509/deepin-23-beige-rc-amd64-20240509-120442.iso 
应用版本：dde-file-manager:6.0.50
```

### STEPS TO REPRODUCE | 复现步骤

1.安装最新镜像后，打开文件管理器 

### OBSERVED RESULT | 观察到的结果

文件管理器默认打开的是主目录而不是计算机
![录屏_dde-desktop_20240509153337](https://github.com/linuxdeepin/developer-center/assets/96415804/77e70ed1-33ee-44de-86b7-2839e8f24119)

### EXPECTED RESULT | 期望的结果

文件管理器默认打开计算机目录

**Comment by babyfengfjx** [comment]
@FeiWang1119   跟 #8481  看是不是一样原因。

**Comment by xuqi27837288** [comment]
【验证环境】：v23 beta3镜像
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240509
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.25-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
