### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【DDE】打开uos-ai, 输入框被任务栏完全遮挡

### ISSUE THREAD

**Issue by kobe337** [linuxdeepin/developer-center#8490]
PMS关联链接： https://pms.uniontech.com/bug-view-254503.html
### SUMMARY | 问题概要

打开uos-ai, 输入框被任务栏完全遮挡

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240509/deepin-23-beige-rc-amd64-20240509-120442.iso
```

### STEPS TO REPRODUCE | 复现步骤

1. 任务栏上点击uos-ai插件，观察弹出界面展示

### OBSERVED RESULT | 观察到的结果

打开uos-ai, 输入框被任务栏完全遮挡
![srkmyzs](https://github.com/linuxdeepin/developer-center/assets/17869922/5e2ba437-9f7a-4bfd-b56f-2d0b6f04e0aa)

### EXPECTED RESULT | 期望的结果

打开uos-ai, 输入框正常展示

**Comment by babyfengfjx** [comment]
@tsic404  看这个是我们的问题还是应用的问题。

**Comment by kobe337** [comment]
转PMS跟踪链接：https://pms.uniontech.com/bug-view-254503.html

**Comment by kobe337** [comment]
与研发同事确认，为uos-ai应用的问题，转PMS跟踪
