### ISSUE TITLE
Converting Debian to Deepin

### ISSUE THREAD

**Issue by spavikevik** [linuxdeepin/developer-center#85]
I would like to know if it's possible to convert a Debian system to Deepin by changing the default repositories to Deepin repos and then installing all Deepin packages.

And what is the Debian base version for Deepin 15.1.1?

Thank you.

**Comment by snyh** [comment]
deepin 15.1.1   based on debian sid.

But it's very likely wouldn't work if just switch the repository source list from debian to deepin.
