### ISSUE TITLE
Enhancement / Feature Request : Deepin App Store ... create a section for plugins in the app store !!!

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#852]
Hi,

1. Shouldn't the app store have a separate section for users to find and install plugins for the dock and efficient mode panel ?

Doing this will encourage dev's to create serious plugins that have functionality that users can definitely use !!!

the possibilities for plugins are many ... a look at extensions.gnome.org is a good example of the various utilities that certainly help users increase productivity.

A few things have to be streamlined on the way to a similar deepin extensions/plugins collection ...

2. the most important of them al is thel forward compatibility of the plugins the older plugins need to work even when the plugin-API is changed/updated (i guess discussions are already on on this subject)

3.  given that there is very little real-estate(space) on the dock for plugins ... the deepin team needs to throw the docks **collapsible/expandable system-tray API** open to third party developers. This i hope will enable the users to have their own plugin collections with the option of collapsing and expanding their plugin panel ... Also the WIP on providing users the option to choose to always show certain sys-tray items will work well even for users with these collapsible/expandable plugin containers.

With these 3 features in place i believe a good stage will be set for active plugin development making the whole Deepin OS UX highly productive !!!

**Comment by aiamuzz** [comment]
@CareF ... @sonichy ... you could join this discussion ... as you are the only plugin dev's i know of ...

**Comment by sonichy** [comment]
1. Add category of dock plugin, agreed, official have 5, I have 2.
2. Qt is easy to crash, maybe deepin do not want to courage unofficial plugin to cause dock crash.
3. It will be funny to scroll to plugin when message comes !

**Comment by aiamuzz** [comment]
@hualet ... @BLumia ... @wangjia12 ... 

i had no idea of sonichy's weather plugin ... as i didn't know where to look for ... I guess @hualet ... responded to one issue here and pointed us to sonichy's weather plugin ...

**Comment by CareF** [comment]
I am using deepin DE with Arch Linux, not deepin distribution. I am not a user of the App Store so I am probably not a good one to provide any idea, unless deepin wants to make it available for developers under other distributions.

**Comment by hualet** [comment]
We've discussed similar topics, we all agree that we need some sort of ways to help users to discover things like Dock plugins, Wallpapers, Themes, and Screensavers, etc. but I still don't think it's a good idea to put so many categories in the App Store, so we may finally offer similar functions as enhanced search.

**Comment by aiamuzz** [comment]
> We've discussed similar topics, we all agree that we need some sort of ways to help users to discover things like Dock plugins, Wallpapers, Themes, and Screensavers, etc. but I still don't think it's a good idea to put so many categories in the App Store, so we may finally offer similar functions as enhanced search.

Software | Dock/Panel Plugins | Themes | Screensavers | Wallpapers ... How about these being designed as as  tabs instead of an enchanced search  ... the categories inside these tabs could be template for every label(tab) !!!

something like this ??? ... i have centered the categories on the left to a vertical center (in line with the launcher category UI)

![deepin-store-tabs](https://user-images.githubusercontent.com/3283676/51963088-5dd67a00-2488-11e9-9335-d44a86362029.png)

**Comment by hualet** [comment]
@aiamuzz Maybe NOT, categories are tabs we don't need tabs in another dimension.

**Comment by aiamuzz** [comment]
> @aiamuzz Maybe NOT, categories are tabs we don't need tabs in another dimension.

hmmmmm ... i was more looking at fast implementation least amount of efforts ... you already have a set template for software duplicating that style in separate tabs is efficient ...

@hualet ... i however didn't get the 'enhanced search approach' ... how does it work ?

**Comment by lolimay** [comment]
> > We've discussed similar topics, we all agree that we need some sort of ways to help users to discover things like Dock plugins, Wallpapers, Themes, and Screensavers, etc. but I still don't think it's a good idea to put so many categories in the App Store, so we may finally offer similar functions as enhanced search.
> 
> Software | Dock/Panel Plugins | Themes | Screensavers | Wallpapers ... How about these being designed as-as tabs instead of an enhanced search ... the categories inside these tabs could be a template for every label(tab) !!!
> 
> something like this ??? ... I have centered the categories on the left to a vertical center (in line with the launcher category UI - if the tea approves this change could also go as an enhancement)
> 
> ![deepin-store-tabs](https://user-images.githubusercontent.com/3283676/51963088-5dd67a00-2488-11e9-9335-d44a86362029.png)

Amazing design! But smaller border radius may be better :D
- Origin
![image](https://user-images.githubusercontent.com/32427260/51966424-6ab69600-24a7-11e9-9771-0d0a3c7df8aa.png)
- Smaller radius
![image](https://user-images.githubusercontent.com/32427260/51967186-9e92bb00-24a9-11e9-902e-db40810b1a99.png)

**Comment by sonichy** [comment]
@lolimay Tab is better than left side list item?

**Comment by aiamuzz** [comment]
> @lolimay Tab is better than left side list item?

a left side list item for ... **plugin | screensaver | wallpaper | themes** will clutter it all ... a tab system will be more cleaner as all the above can have their own sub categories like the most popular, editors choice, deepin collection, etc ... also they can have their own 'downloading' and 'Uninstall' items ... a tab is much more cleaner than any other way ... as it will have its own format and style with regard to subcategories in future ...

**Comment by meiyixiang** [comment]
Plug-in modules for the store of new without the function of planning, but have you submitted to the corresponding product manager feedback suggestion. But we are against the research
