### ISSUE TITLE
deepin-wine QQ 崩溃

### ISSUE THREAD

**Issue by lolimay** [linuxdeepin/developer-center#853]
## 缺陷描述

点击 QQ 主面板**验证消息**，有一定概率会卡死然后闪退，具体请见截图和 QQ 生成的日志。

## 复现步骤

打开 QQ 主面板，点击验证消息，QQ 卡死退出。

## 期望行为

打开 QQ 主面板，点击验证消息，QQ 正常工作。

## 截图

![_ _20190129080039](https://user-images.githubusercontent.com/32427260/51874529-520d8980-239c-11e9-8777-6ac4e782c70a.png)

## 复现环境:

QQ 版本 9.0.4 (23780)

### 发行版以及版本

deepin 15.9

### 相关的软件包版本

````bash
deepin-wine --version # wine-2.18
wine --version # wine-3.0.1 (Debian 3.0.1-2)
````

### 日志文件

[QQ34998a5.tar.gz](https://github.com/linuxdeepin/developer-center/files/2805452/QQ34998a5.tar.gz)

**Comment by hualet** [comment]
@zhaofangfangdeepin @liuwen123 有遇到过么？

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
