### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【DDE】【启动器】【UI】 启动器外描边的问题

### ISSUE THREAD

**Issue by wangruoxuan3782** [linuxdeepin/developer-center#8530]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
dde-launchpad 0.6.8
```

### STEPS TO REPRODUCE | 复现步骤

查看窗口启动器

### OBSERVED RESULT | 观察到的结果

发现启动器背景外描边较粗
外描边看起来有两个像素 深色主题比较明显
![企业微信截图_17153937116704](https://github.com/linuxdeepin/developer-center/assets/162073918/cf5305c6-2f8f-4b31-b9c9-549c935df7eb)

### EXPECTED RESULT | 期望的结果

外描边1px，内描边1px，描边粗细不跟随高分屏缩放

**Comment by kegechen** [comment]
@xionglinlin

**Comment by mhduiy** [comment]
本单解决内描边在高缩放下变粗的问题

**Comment by wangruoxuan3782** [comment]
dde-launchpad 0.7.4 
描边粗细不跟随高分屏缩放问题 UI已验证
