### ISSUE TITLE
IntelliJ idea全屏模式（view-->enter full screen）查找类失效

### ISSUE THREAD

**Issue by chenhaubin** [linuxdeepin/developer-center#854]
请将下方的缺陷汇报模板中的文字替换为您实际需要汇报的缺陷所对应的描述文字。

## 缺陷描述
1、正常模式下查找类（ctrl+n），查找文件（ctrl+shift+n）earchEverywhere双击shift，run anything双击ctrl都正常
2、进入全屏模式，查找类（ctrl+n），查找文件（ctrl+shift+n）都失效，SearchEverywhere双击shift，run anything双击ctrl都失效，注意不是快捷键失效，点菜单上功能也失效
3、退出全屏模式恢复正常。
通过在deepin15.8下测试也是如此
DataGrip 2018.3.2同样存在这个问题
## 复现步骤

复现步骤为:
进入全屏模式（view-->enter full screen）

## 期望行为
全屏模式下，正常使用

## 复现环境:

*部分缺陷可能需要在特定环境下才能复现，所以请尽可能详细的提供可能导致该缺陷的环境信息*

### 发行版以及版本

Linux Deepin 15.9

### 相关的软件包版本
IntelliJ idea 2018.3.3
DataGrip 2018.3.2

### 其他内容
经过测试和论坛调查，都可以重现这个问题，Ubuntu18.10下正常。

**Comment by listenerri** [comment]
@zccrs 
应该是我们窗管的问题, 使用 kwin --replace 之后就正常了

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
