### ISSUE TITLE
闭源驱动屏幕闪烁

### ISSUE THREAD

**Issue by wyy0117** [linuxdeepin/developer-center#855]
## 缺陷描述

使用显卡驱动管理器安装闭源驱动后，屏幕闪烁严重，驱动版本为390.67-3deepin，使用开源驱动无法调节亮度。

## 复现步骤

重装15.9系统后，更新系统到最新，然后安装闭源驱动，重启后即可出现屏幕闪烁的情况，开机使用几个小时后，闪烁情况有所缓解，再重启之后的几分钟内，闪烁特别严重，使用几个小时候，闪烁有所缓解。

## 期望行为

期望屏幕不要有闪烁。

## 复现环境:

硬件信息：电脑型号为蓝天p775tm准系统，cpu：i7 8700，显卡：gtx1060 6g，内存：16G*2，主板硬件屏蔽核显。

### 发行版以及版本

 Linux Deepin 15.8,15.9

### 其他内容

使用Ubuntu18.4默认开源驱动也无法调节亮度，安装闭源驱动，屏幕不会闪烁，显卡驱动版本为390.77.使用win10系统屏幕不会闪烁。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
