### ISSUE TITLE
deepin-home-appstore-daemon 8.0.6.0024 集成申请

### ISSUE THREAD

**Issue by zty199** [linuxdeepin/developer-center#8553]
### package information | 软件包信息

包名 | 版本
--- | ---
deepin-home-appstore-daemon | 8.0.6.0024-1

### Package repository address | 软件包仓库地址

```
deb  [trusted=yes] https://aptly.uniontech.com/pkg/nonfree-beige-v2/release-candidate/5bqU55So5ZWG5bqXZGFlbW9uMjAyNDA1MTMyMDI0LTA1LTEzIDE0OjMyOjQ4/  unstable non-free
```

### changelog | 更新信息

deepin-home-appstore-daemon 8.0.6.0024:
1. 修改 preinst，去除删除商店仓库密钥操作，保证升级异常中断时 apt update 商店仓库不会报错
2. 修改 postinst，将 mv 操作修改为 cp，保留源文件，保证 dpkg-reconfigure 可以正常执行

### test suggestion | 测试建议

1. 相关修改不涉及代码逻辑，无具体测试建议
2. 修改主要针对 20240510 内测推送更新后，部分用户升级中断，尝试执行 apt update 发现商店仓库报错现象。集成该版本后，用户升级过程中如果中断，此时执行 `sudo apt update`，商店仓库应正常拉取。

### Sphere of influence | 影响范围

系统升级异常中断时，影响用户访问商店仓库

### ADDITIONAL INFORMATION | 额外补充

该修复由 https://github.com/linuxdeepin/developer-center/issues/8532 延伸

**Comment by vivianxf** [comment]
集成验证通过，请及时合入：

1.添加仓库升级成功
2.执行sudo apt update 正常无报错
3.应用商店基本功能正常

综上所述，本次集成通过～
