### ISSUE TITLE
Tray icon of telegram-desktop is not shown

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#857]
## Describe the bug

There is no tray icon in the dock notification area with the "Tray Icon" box checked in the app. 

## To Reproduce

Install telegram-desktop and run it. See that the tray icon is missing.

### Distro & Version

Arch Linux

### Related package version

deepin-dock 4.8.9-1
telegram-desktop 1.5.8-1

**Comment by aiamuzz** [comment]
I confirm this bug ... i didn't report it thinking it must've been a bug with the Telegram app and as i don't use it much ... just ignored it !!!

**Comment by dance707** [comment]
Seems to be a random problem, I had issues in past. Currently I have two Arch deepin's, and on both the telegram-desktop-1.5.8-1 show up in system tray area okay.

**Comment by aiamuzz** [comment]
@dance707 ... you are right ... seems random ... i am running Deepin OS and the app is showing now in the tray ...

**Comment by xd003** [comment]
Hello , i am facing this issue currently on arch with dde 20 beta
i can confirm this issue exists
i have already enabled the show tray icon in desktop settings but that didnt helped

this issue is so old  , i hope it would be brought to attention now

**Comment by xmuli** [comment]
@xd003 I don’t have this problem on archlinux + DDE, I hope the following can help you

![image](https://user-images.githubusercontent.com/33887845/91008360-cf4cbf00-e610-11ea-959c-0fcebd154879.png)

**Comment by alissonlauffer** [comment]
I were having this issue too, but after updating deepin-dock from 5.1.0.14-1 to 5.2.0.14-1, looks like this issue is solved.
