### ISSUE TITLE
【deepin_V23_Release】【一般】【有空】【发散测试】【玲珑】运行ll-cli ps查看日历进程时，输出有两条记录

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#8579]
### SUMMARY | 问题概要

运行ll-cli ps查看日历进程时，输出有两条记录

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
linglong-bin:1.5.1-1
```

### PRE-REQUIREMENT | 预置条件

1.更新玲珑到最新版本

### STEPS TO REPRODUCE | 复现步骤

1.在终端执行ll-cli run org.deepin.calendar打开日历
2.在终端执行ll-cli ps 查看正在运行的容器
3.观察现象

### OBSERVED RESULT | 观察到的结果

1.运行ll-cli ps 时，日历有两条记录
![截图_选择区域_20240514141552](https://github.com/linuxdeepin/developer-center/assets/96415804/0b2367b5-0212-4e13-818d-5b1ffca10d08)

### EXPECTED RESULT | 期望的结果

1.日历运行时，只创建一个容器，只有一条记录才对

**Comment by ComixHe** [comment]
已修复
