### ISSUE TITLE
使用自定义壁纸后，点击关机按钮，屏幕变全白

### ISSUE THREAD

**Issue by zazcoder** [linuxdeepin/developer-center#858]
使用自定义壁纸后，点击关机按钮，屏幕变全白
![image](https://user-images.githubusercontent.com/17716859/52028940-0c8fbe80-254c-11e9-8fca-4d15db66c779.png)

![image](https://user-images.githubusercontent.com/17716859/52028934-07327400-254c-11e9-8a91-1cbc22aa433d.png)

**Comment by hualet** [comment]
@justforlxz 好像确实容易出现这种问题呀。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
