### ISSUE TITLE
【deepin_V23_Release】【一般】【有空】【发散测试】【玲珑】运行 ll-cli enter  ${APP} ，无法进入正在运行的应用的容器内

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#8580]
### SUMMARY | 问题概要

运行 ll-cli enter  ${APP} ，无法进入正在运行的应用的容器内

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
linglong-bin:1.5.1-1
```

### PRE-REQUIREMENT | 预置条件

1.更新玲珑到最新版本

### STEPS TO REPRODUCE | 复现步骤

1.在终端执行ll-cli run org.deepin.calendar打开日历
2.在终端执行ll-cli ps 查看正在运行的容器
3.在终端执行 ll-cli enter  ${APP}
4.观察是否能进入日历容器

### OBSERVED RESULT | 观察到的结果

1.运行 ll-cli enter  ${APP} ，无法进入正在运行的应用的容器内
![截图_选择区域_20240514141515](https://github.com/linuxdeepin/developer-center/assets/96415804/f841ad3a-0da5-4145-a996-da64f234e404)

### EXPECTED RESULT | 期望的结果

1.1.运行 ll-cli enter  ${APP} ，可以进入正在运行的应用的容器内

**Comment by ComixHe** [comment]
已解决，等后续集成再次验证

**Comment by ComixHe** [comment]
https://github.com/linuxdeepin/linglong/pull/444

**Comment by vivianxf** [comment]
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1483:/dde/testing/ ./
验证步骤：提单的步骤
验证现象：ll-cli kill 命令可以正常关闭正在运行的应用的容器
验证结果：通过
