### ISSUE TITLE
【deepin_V23_Release】【一般】【有空】【发散测试】【玲珑】运行执行 ll-cli kill ${APP}，无法关闭正在运行的应用的容器

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#8581]
### SUMMARY | 问题概要

运行执行 ll-cli kill ${APP}，无法关闭正在运行的应用的容器

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
linglong-bin:1.5.1-1
```

### PRE-REQUIREMENT | 预置条件

1.更新玲珑到最新版本

### STEPS TO REPRODUCE | 复现步骤

1.在终端执行ll-cli run org.dde.calendar打开日历
2.在终端执行ll-cli ps 查看正在运行的容器
3.在终端执行 ll-cli kill ${APP}
4.观察是否能关闭日历容器

### OBSERVED RESULT | 观察到的结果

1.运行执行 ll-cli kill ${APP}，无法关闭正在运行的应用的容器
![截图_选择区域_20240514141601](https://github.com/linuxdeepin/developer-center/assets/96415804/56275d14-3b80-448b-ad80-45484823c4ce)

### EXPECTED RESULT | 期望的结果

运行执行 ll-cli kill ${APP}，可以关闭正在运行的应用的容器

**Comment by dengbo11** [comment]
看下是不是功能去掉了

**Comment by ComixHe** [comment]
其实kill的功能是好的，等容器复用的功能写了就正常了

**Comment by ComixHe** [comment]
https://github.com/linuxdeepin/linglong/pull/444

**Comment by ComixHe** [comment]
已修复

**Comment by vivianxf** [comment]
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1483:/dde/testing/ ./
验证步骤：提单的步骤
验证现象：ll-cli kill 命令可以正常关闭正在运行的应用的容器
验证结果：通过
![截图_deepin-terminal_20240524152222](https://github.com/linuxdeepin/developer-center/assets/96415804/2e9000bd-79e9-4f8a-a599-2fbb13baea88)
