### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【发散测试】【玲珑】deepin Cloud同步中日历模块名称未国际化,展示为英文

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#8589]
### SUMMARY | 问题概要

必现问题

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240514
```

### PRE-REQUIREMENT | 预置条件

登录deepin ID

### STEPS TO REPRODUCE | 复现步骤

观察日历模块的展示效果

### OBSERVED RESULT | 观察到的结果

未国际化展示为英文

![企业微信截图_17156776247738](https://github.com/linuxdeepin/developer-center/assets/62528742/488bf9f8-f4ed-4398-a509-a6a4593e69b4)

### EXPECTED RESULT | 期望的结果

展示为中文

**Comment by FeiWang1119** [comment]
日历是deepin-sync-daemon从deb 路径下desktop的generic_name / name 字段获取的, 日历改成了玲珑应用,找不到desktop.需要deepin-sync-daemon适配玲珑应用

**Comment by kegechen** [comment]
需要推进一下 deepin-sync-daemon 改 @babyfengfjx

**Comment by babyfengfjx** [comment]
@xuqi27837288  确认一下最终处理人，需要子项目处理的转单到PMS跟踪。

**Comment by xuqi27837288** [comment]
https://pms.uniontech.com/bug-view-256219.html
