### ISSUE TITLE
[Feature Request] deepin draw 剪贴板支持

### ISSUE THREAD

**Issue by CareF** [linuxdeepin/developer-center#859]
直接复制图片到 deepin draw 编辑美滋滋..

**Comment by BLumia** [comment]
deepin draw 现在并没有官方支持，Deepin 发行版内甚至都没有官方发布这个软件，尽管内测过一次（（（

其实这个特性我试着加过一次，但是看代码似乎设计不太合理的样子，我的实现也不是很干净就没合直接丢掉了。有兴趣的话你也可以试着自己加进去这个功能。

**Comment by aiamuzz** [comment]
> deepin draw 现在并没有官方支持，Deepin 发行版内甚至都没有官方发布这个软件，尽管内测过一次（（（
> 
> 其实这个特性我试着加过一次，但是看代码似乎设计不太合理的样子，我的实现也不是很干净就没合直接丢掉了。有兴趣的话你也可以试着自己加进去这个功能。

I remember having tested it ... i liked whatever i saw(but needed more work) ... I was looking forward to it ... thought it was under development and will be released in future ... just like how deepin-editor was first tested and released subsequently ...

@BLumia  ... does it mean its abandoned ? Will never be completed ?

**Comment by hualet** [comment]
> > deepin draw 现在并没有官方支持，Deepin 发行版内甚至都没有官方发布这个软件，尽管内测过一次（（（
> > 其实这个特性我试着加过一次，但是看代码似乎设计不太合理的样子，我的实现也不是很干净就没合直接丢掉了。有兴趣的话你也可以试着自己加进去这个功能。
> 
> I remember having tested it ... i liked whatever i saw(but needed more work) ... I was looking forward to it ... thought it was under development and will be released in future ... just like how deepin-editor was first tested and released subsequently ...
> 
> @BLumia ... does it mean its abandoned ? Will never be completed ?

It'll be finished in this year or abandoned completely.

**Comment by hualet** [comment]
如果做得话到时候肯定会支持这个功能的，先关闭了。

**Comment by aiamuzz** [comment]
hope its not abandoned ... need a simple program for working on image files ... the available ones are complicated ...
