### ISSUE TITLE
deepin-installer 安装器 6.0.50

### ISSUE THREAD

**Issue by ArchieMeng** [linuxdeepin/developer-center#8595]
### package information | 软件包信息

deepin-installer 6.0.50

### Package repository address | 软件包仓库地址

https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20240514/deepin-23-beige-rc-amd64-20240514-193520.iso

### changelog | 更新信息

更新V23发布的轮播图

### test suggestion | 测试建议

观察是否替换。

### Sphere of influence | 影响范围

轮播图

### ADDITIONAL INFORMATION | 额外补充

无

**Comment by luodeepin** [comment]
测试通过
