### ISSUE TITLE
[archlinux]开机dde-dession-daemon内存占用472M

### ISSUE THREAD

**Issue by kirigayakazushin** [linuxdeepin/developer-center#86]
每次开机都会,手动结束进程以后,似乎不会再出现了.
![20160522084051](https://cloud.githubusercontent.com/assets/12298476/15451518/ad37b478-1f8c-11e6-9f38-0b451ccd74ae.png)

**Comment by fasheng** [comment]
重复问题合并
https://github.com/linuxdeepin/developer-center/issues/100
