### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【loongarch64架构】【系统】loong64架构，RX 400/500 系列显卡，在显卡高负载下，会出现报错崩溃

### ISSUE THREAD

**Issue by kobe337** [linuxdeepin/developer-center#8603]
反馈来源： 白铭骢
### SUMMARY | 问题概要

loong64架构，RX 400/500 系列显卡，在显卡高负载下，会出现报错崩溃

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
Deepin OS 23 20240418 loongarch64
```

### PRE-REQUIREMENT | 预置条件

使用RX 400/500 系列显卡的设备

### STEPS TO REPRODUCE | 复现步骤

1. 在系统环境上，使用显卡3D压测脚本进行压测，或者使用命令 for  i in `seq 1 32`; do glmark2 --run-forever & done，在运行时随意拖动或切换窗口，或者使用有显卡加速的浏览器看 4K 视频

### OBSERVED RESULT | 观察到的结果

loong64架构，RX 400/500 系列显卡，在显卡高负载下，会出现报错崩溃

![image](https://github.com/linuxdeepin/developer-center/assets/17869922/c018ed90-008b-4a3a-893e-e3fbf0bbba0c)

### EXPECTED RESULT | 期望的结果

loong64架构，RX 400/500 系列显卡，在显卡高负载下，不会出现报错崩溃

**Comment by babyfengfjx** [comment]
@Zeno-sole  有余力可以分析。

**Comment by Zeno-sole** [comment]
loongarch64平台硬件问题

**Comment by MingcongBai** [comment]
已报交 Deepin LoongArch SIG 调查此问题

**Comment by MingcongBai** [comment]
目前此问题已有确切缘由调查报告，但考虑到修复方式是龙架构专属，可能需要进一步讨论可行性

详见 AOSC 同事编撰的报告 https://github.com/AOSC-Dev/newsroom/blob/master/coffee-break/20240623/loongarch-amdgpu-fix.zh_CN.md

**Comment by MingcongBai** [comment]
> 目前此问题已有确切缘由调查报告，但考虑到修复方式是龙架构专属，可能需要进一步讨论可行性
> 
> 详见 AOSC 同事编撰的报告 https://github.com/AOSC-Dev/newsroom/blob/master/coffee-break/20240623/loongarch-amdgpu-fix.zh_CN.md

目前 6.6/6.9 内核均包含规避修复，请择时重新测试

**Comment by kobe337** [comment]
目前已经开始进行显卡负载压力测试

**Comment by kobe337** [comment]
【环境】：
镜像：Deepin OS 23 20240725 loongarch64
内核：Linux deepin-PC 6.6.40-loong64-desktop-hwe #23.01.00.33 SMP PREEMPT Thu Jul 25 15:49:17 CST 2024 loongarch64 GNU/Linux

【结论】：
回归测试通过，暂无严重问题及影响, 运行图形化压力测试3*24小时，未崩溃，验证通过
