### ISSUE TITLE
【deepin_V23_Release】【严重】【立即】【预发布测试】【系统】手动修改hostname, 注销后，无法进入系统桌面

### ISSUE THREAD

**Issue by kobe337** [linuxdeepin/developer-center#8611]
内测反馈用户：hotime
### SUMMARY | 问题概要

手动修改hostname, 注销后，无法进入系统桌面

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240514/deepin-23-beige-rc-amd64-20240514-213855.iso
```

### STEPS TO REPRODUCE | 复现步骤

1. 手动修改hostname,编辑sudo vim /etc/hostname , 执行注销操作

### OBSERVED RESULT | 观察到的结果

设备1、手动修改hostname, 注销后，无法进入系统桌面
设备2、手动修改hostname, 注销后，登陆界面输入密码，一直无法加载出系统桌面
![kz](https://github.com/linuxdeepin/developer-center/assets/17869922/82ea0cc9-9bd7-49c8-929d-dea2df0e2b5b)

### EXPECTED RESULT | 期望的结果

手动修改hostname, 执行注销操作，仍能正常进入系统桌面

**Comment by UTsweetyfish** [comment]
### 观测到的现象

T-0s 用户开始注销，日历服务收到 SIGTERM
T-15s 用户输入密码，登陆
T-30s 日历服务没有退出，`systemd --user` 向日历发送 SIGKILL

此时 `systemd --user` 没有退出，用户无法登陆。而即使 T-30s 日历服务退出了，用户依然因为 `systemd --user` 的状态是不完整的，导致无法进入桌面。

请分析 @kegechen

**Comment by ECQZXC** [comment]
greeter报错
![企业微信截图_17183366562273](https://github.com/linuxdeepin/developer-center/assets/26087505/6897e2a4-eae0-4a1b-b039-f2622546df1e)
继续查看日志发现
![企业微信截图_17185939597779](https://github.com/linuxdeepin/developer-center/assets/26087505/912d1931-840f-488f-842b-d99f72d3fcf0)
查看libx11代码，发现报错内容是socket问题
![企业微信截图_17185939693677](https://github.com/linuxdeepin/developer-center/assets/26087505/b441bcdb-8c7c-4671-8cf1-eb01bea4a8c5)
需要xorg模块协助调查

**Comment by kegechen** [comment]
见备注，这种方式修改不是常见的修改方式，建议非问题关闭。如果是用户提的，可以回复一下用户

**Comment by kobe337** [comment]
情况已回复用户，已验证提供的两个场景：
1、vim修改hostname文件，重启验证
2、使用命令设置 hostnamectl set-hostname 新的主机名  ，然后注销验证
均验证通过。此issue关闭。
