### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【玲珑】控制中心-deepin ID下没有玲珑浏览器同步选项

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#8615]
### SUMMARY | 问题概要

控制中心-deepin ID下没有玲珑浏览器同步选项

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240514/deepin-23-beige-rc-amd64-20240514-213855.iso
```

### PRE-REQUIREMENT | 预置条件

1.安装上述最新镜像

### STEPS TO REPRODUCE | 复现步骤

1.打开控制中心-deepin ID 登录
2.打开同步
3.观察同步选项是否有浏览器

### OBSERVED RESULT | 观察到的结果

1.控制中心-deepin ID下没有玲珑浏览器同步选项
![企业微信截图_17157578305292](https://github.com/linuxdeepin/developer-center/assets/96415804/b81a5286-b57b-4ea0-acfb-9f3c46723af5)

### EXPECTED RESULT | 期望的结果

1.控制中心-deepin ID下存在玲珑浏览器同步选项

**Comment by babyfengfjx** [comment]
@dengbo11  这个优先分析确认。

**Comment by myml** [comment]
已通过更改服务端配置解决

**Comment by vivianxf** [comment]
验证镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240715/
验证版本：org.deepin.browser->6.5.5.0
验证步骤：提单的步骤
验证现象：控制中心下，包含浏览器同步选项
验证结果：通过
![截图_选择区域_20240719163026](https://github.com/user-attachments/assets/d51ea647-45fd-4b0a-9db2-435167a2e6d6)
