### ISSUE TITLE
dde-dock 插件接口 pluginproxyinterface, 加一个 removeValue 吧?

### ISSUE THREAD

**Issue by CareF** [linuxdeepin/developer-center#862]
保持设置文件的干净, 并且能快速恢复到默认设置

**Comment by electricface** [comment]
@listenerri

**Comment by listenerri** [comment]
@electricface 后端先加吧

**Comment by electricface** [comment]
https://cr.deepin.io/#/c/dde/dde-daemon/+/41567/

**Comment by CareF** [comment]
@listenerri 
谢谢通知! 
所以对于其他发行版的 DDE, 云端同步和 deepin 自家发行版会有什么区别? 
另外关于插件接口和实现的更新, 能不能提供一个邮件列表自动获取通知啊?

**Comment by BLumia** [comment]
> @listenerri
> 谢谢通知!
> 所以对于其他发行版的 DDE, 云端同步和 deepin 自家发行版会有什么区别?
> 另外关于插件接口和实现的更新，能不能提供一个邮件列表自动获取通知啊?

参考 https://github.com/linuxdeepin/internal-discussion/issues/840 ，有什么好想法也可以跟一下。另外目前来看下次变更API应该不会导致向下兼容问题，不过也不好说。

当然这个话题是另外的事情了，和这个 issue 的主题无关了（

**Comment by CareF** [comment]
> > @listenerri
> > 谢谢通知!
> > 所以对于其他发行版的 DDE, 云端同步和 deepin 自家发行版会有什么区别?
> > 另外关于插件接口和实现的更新，能不能提供一个邮件列表自动获取通知啊?
> 
> 参考 [linuxdeepin/internal-discussion#840](https://github.com/linuxdeepin/internal-discussion/issues/840) ，有什么好想法也可以跟一下。另外目前来看下次变更API应该不会导致向下兼容问题，不过也不好说。
> 
> 当然这个话题是另外的事情了，和这个 issue 的主题无关了（

已经关注这个了. 然而并没有提云端的事情哎..

**Comment by hualet** [comment]
哪个讨论主要是接口兼容性的问题，你想知道关于云同步神马事情？

**Comment by listenerri** [comment]
接口的变动请跟踪下面这个 issue:
https://github.com/linuxdeepin/internal-discussion/issues/739

**Comment by ihipop** [comment]
> @electricface 后端先加吧
> 
> @CareF
> 在云同步功能发布后 dock 的所有插件配置都将不再保存在 `/home/.config/deepin/dde-dock.config` 文件中, 而是通过 dbus 通信保存在 dde-daemon 里(daemon好像使用的 gsetting 进行存储数据), 如果你比较关心 dock 插件配置的内容, 请自行留意这一改动.

如果想修改一些UI上没提供的配置，（比如 https://github.com/linuxdeepin/internal-discussion/issues/867 ）是有通过dbus操作 dde-daemon里面的配置的接口还是需要用gsetting找key修改？
