### ISSUE TITLE
更新过后，音乐播放器不能自动加载歌词，也无法搜索歌词

### ISSUE THREAD

**Issue by YLXDXX** [linuxdeepin/developer-center#864]
将新歌添加进去，音乐播放器不能自动加载歌词，使用歌词搜索也没有反应

**Comment by YLXDXX** [comment]
今天正常了

**Comment by BLumia** [comment]
FYI: 这次更新中并没有任何关于获取网络歌词这方面功能的调整。

另外请尽可能在报 bug 的时候把能提供的细节和环境附带上来，保证除了你之外的另外的人可以按照你的描述重现 bug 的程度即可。

所以先关掉了。
