### ISSUE TITLE
文件管理器bug，存在文件但搜索不到

### ISSUE THREAD

**Issue by YLXDXX** [linuxdeepin/developer-center#865]
目录下的文件存在，却搜索不到
已录屏
[深度录屏_dde-file-manager_20190201214200.mp4.zip](https://github.com/linuxdeepin/developer-center/files/2821797/_dde-file-manager_20190201214200.mp4.zip)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
