### ISSUE TITLE
Feature Request / Enhancement : Expand Kinetic Scrolling to other applications !

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#866]
Hi,

@BLumia ... @jouyouyun ... 

I just realized you already have a nice **Kinetic Scroll**(not **Kinetic pointer movement**) implemented in the control center scrolling ... the touchpad scroll is really smooth(the mouse scrolling is not as smooth needs improvement)

Wouldn't it be a great idea to expand this Kinetic Scroll implementation to other applications and other places on the Deepin UI ... this will greatly improve the UX !!!

Application Launcher, Deepin File Manager, Music player(playlist scrolling), Movies Player(playlist scrolling) ... Terminal (scrolling the terminal command output history ) ... Browsers ... all these places could really enhance the whole UX ... taking the Deepin user experience to a whole new level !!!

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
