### ISSUE TITLE
【deepin_V23_Release】【一般】【正常】【内测反馈】【DDE】启动器中搜索“ter”, “计算机”排列在“终端”前面

### ISSUE THREAD

**Issue by kobe337** [linuxdeepin/developer-center#8669]
### SUMMARY | 问题概要

反馈来源： 白铭骢
启动器中搜索“ter”, “计算机”排列在“终端”前面

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像版本：Deepin OS-23-20240514132558-1_x86_64
内核版本：Linux deepin-PC 6.6.25-amd64-desktop-hwe #23.01.00.25 SMP PREEMPT_DYNAMIC Wed Apr 10 21:20:25 CST 2024 x86_64 GNU/Linux
```

### STEPS TO REPRODUCE | 复现步骤

1.打开启动器，搜索"ter"字符，查看搜索结果

### OBSERVED RESULT | 观察到的结果

启动器中搜索“ter”, “计算机”排列在“终端”前面
![截图_dde-shell_20240520120123](https://github.com/linuxdeepin/developer-center/assets/17869922/079c71d2-6f9e-415c-ac32-7ba44b2553a3)

### EXPECTED RESULT | 期望的结果

搜索英文匹配，terminal终端应该排列在Computer前面

**Comment by babyfengfjx** [comment]
@BLumia  这个可以优先分析。

**Comment by BLumia** [comment]
- compu*ter*
- *ter*minal

C 在 T 前面

**Comment by kobe337** [comment]
转PMS链接https://pms.uniontech.com/bug-view-271527.html
