### ISSUE TITLE
[Feature Request] Tidier launcher icons with the drawer system for system tray

### ISSUE THREAD

**Issue by gokhanyildirimlar** [linuxdeepin/developer-center#867]
Some people may want to arrange icons like on mobile operating systems. Deepin has a drawer for system tray icons at fashion mode and we can expand it to see icons. The same thing can be applied to launcher icons to have tidier multiple icons with a folder-like approach. 

![image](https://user-images.githubusercontent.com/45146702/52169182-78894700-2745-11e9-8e71-ae25111ff250.png)

Imagine this approach for program launchers. People can create drawers for multimedia, development, chat, etc. and put program icons they want, in it. It could be a useful feature for people to keep them tidier and for people who don't want to open launcher all the time to launch a program. It can be applied to both fashion and efficient mode.

**Comment by hualet** [comment]
we've done that before, but we don't think there're many people really using that,  so we just cut it off.

**Comment by aiamuzz** [comment]
> we've done that before, but we don't think there're many people really using that, so we just cut it off.

I think its time to bring it back @hualet  ... as you've confirmed in some other thread that you are coming up with the feature where we can choose icons from the system tray to show always even when the system tray is collapsed(shut) ... 

Now if this feature of grouping icons on dock where to get the additional option of expanding & collapsing the group just like the current system tray ... along with the above option to choose certain icons in that group to show always when the group they belong to is closed(collapsed) ... we can pack more icons on the dock and at the same time keep the dock width to a size that continues to be attractive!

**Comment by aiamuzz** [comment]
along with the ones we have chosen to show always outside the group ... the applications that are open can automatically be shown out of the group with the group in a (collapsed) closed state ... that way one will be able to click on the open icons to switch between the open app windows(instances)

**Comment by gokhanyildirimlar** [comment]
@hualet, I don't know how many people will use it but some people definitely will like it not only on the dock but also in efficient mode.

**Comment by shule1987** [comment]
I don't think this would be a good idea.  This  will cause many problems and the UX will be very complicated.

**Comment by aiamuzz** [comment]
> I don't think this would be a good idea. This will cause many problems and the UX will be very complicated.

@shule1987 ... if a dock extends(widens) more than 80% of the screen width it starts to look ugly ... it kind of loses its dock appeal ... what do you think ?

**Comment by shule1987** [comment]
> > I don't think this would be a good idea. This will cause many problems and the UX will be very complicated.
> 
> @shule1987 ... if a dock extends(widens) more than 80% of the screen width it starts to look ugly ... it kind of loses its dock appeal ... what do you think ?

Well, it defently will look ugly when the dock gets very crowed. But sometime we have to choose between beauty and efficient when these two things can't be together. Yes, the dock will be less crowed when the app icons is collapsed, but how will you switch to a minimized and collapsed windows if there are lot of windows on your screen,or even between screens ? I kown ALT+TAB can do this , but except this , is there a more convenient way?  Most normal people just use their mouse or just touchpad.

**Comment by aiamuzz** [comment]
> > > I don't think this would be a good idea. This will cause many problems and the UX will be very complicated.
> > 
> > 
> > @shule1987 ... if a dock extends(widens) more than 80% of the screen width it starts to look ugly ... it kind of loses its dock appeal ... what do you think ?
> 
> Well, it defently will look ugly when the dock gets very crowed. But sometime we have to choose between beauty and efficient when these two things can't be together. Yes, the dock will be less crowed when the app icons are collapsed, but how will you switch to a minimized and collapsed window if there are lot of windows on your screen,or even between screens ? I kown ALT+TAB can do this , but except this , is there a more convenient way? Most normal people just use their mouse or just touchpad.

@shule1987 ...

as far as complicating the UX ... i think we can simplify it with a set of rules define for the grouped icon behavior ...

1. Define an 80% width of the screen as the maximum for the dock ... this will ensure the visual appeal of the dock is locked.

2. Any application that has an open window will show outside the group(when its group is in a collapsed state), doing this will ensure the user will save having to open the groups to use the additional right click controls available.

3. Only one group can be open at any given time on the dock, this rule will greatly simplify the UX ... 

hope fully these rules can address much of the concerns you may have with regard to the UX ...

**Comment by aiamuzz** [comment]
> > > I don't think this would be a good idea. This will cause many problems and the UX will be very complicated.
> > 
> > 
> > @shule1987 ... if a dock extends(widens) more than 80% of the screen width it starts to look ugly ... it kind of loses its dock appeal ... what do you think ?
> 
> Well, it defently will look ugly when the dock gets very crowed. But sometime we have to choose between beauty and efficient when these two things can't be together. Yes, the dock will be less crowed when the app icons are collapsed, but how will you switch to a minimized and collapsed window if there are lot of windows on your screen,or even between screens ? I kown ALT+TAB can do this , but except this , is there a more convenient way? Most normal people just use their mouse or just touchpad.

When we design great UI's its also our responsibility to safeguard the aspects of our design from turning ugly and losing its visual appeal ... this will ensure that our UI aesthetics last longer ... may be even make them timeless ...

**Comment by shule1987** [comment]
> > > > I don't think this would be a good idea. This will cause many problems and the UX will be very complicated.
> > > 
> > > 
> > > @shule1987 ... if a dock extends(widens) more than 80% of the screen width it starts to look ugly ... it kind of loses its dock appeal ... what do you think ?
> > 
> > 
> > Well, it defently will look ugly when the dock gets very crowed. But sometime we have to choose between beauty and efficient when these two things can't be together. Yes, the dock will be less crowed when the app icons are collapsed, but how will you switch to a minimized and collapsed window if there are lot of windows on your screen,or even between screens ? I kown ALT+TAB can do this , but except this , is there a more convenient way? Most normal people just use their mouse or just touchpad.
> 
> @shule1987 ...
> 
> as far as complicating the UX ... i think we can simplify it with a set of rules define for the grouped icon behavior ...
> 
> 1. Define an 80% width of the screen as the maximum for the dock ... this will ensure the visual appeal of the dock is locked.
> 2. Any application that has an open window will show outside the group(when its group is in a collapsed state), doing this will ensure the user will save having to open the groups to use the additional right click controls available for open application icons.
> 3. Only one group can be open at any given time on the dock, this rule will greatly simplify the UX ...
> 
> hope fully these rules can address much of the concerns you may have with regard to the UX ...

These rules sound great,   but there are still many problems to fix:
1.It's hard to remember where is my app icon when groups are more than 3 or 5.
2.Drag a file to a collapsed group to open may not be very convenient.
3.The dock will become crowed again when all apps in grounps are opened.

I think you have a lot ideas in your mind ,I can hear you out. And if you have a picture in your mind , it would be perfect.

**Comment by shule1987** [comment]
> > > > > I don't think this would be a good idea. This will cause many problems and the UX will be very complicated.
> > > > 
> > > > 
> > > > @shule1987 ... if a dock extends(widens) more than 80% of the screen width it starts to look ugly ... it kind of loses its dock appeal ... what do you think ?
> > > 
> > > 
> > > Well, it defently will look ugly when the dock gets very crowed. But sometime we have to choose between beauty and efficient when these two things can't be together. Yes, the dock will be less crowed when the app icons are collapsed, but how will you switch to a minimized and collapsed window if there are lot of windows on your screen,or even between screens ? I kown ALT+TAB can do this , but except this , is there a more convenient way? Most normal people just use their mouse or just touchpad.
> > 
> > 
> > @shule1987 ...
> > as far as complicating the UX ... i think we can simplify it with a set of rules define for the grouped icon behavior ...
> > 
> > 1. Define an 80% width of the screen as the maximum for the dock ... this will ensure the visual appeal of the dock is locked.
> > 2. Any application that has an open window will show outside the group(when its group is in a collapsed state), doing this will ensure the user will save having to open the groups to use the additional right click controls available for open application icons.
> > 3. Only one group can be open at any given time on the dock, this rule will greatly simplify the UX ...
> > 
> > hope fully these rules can address much of the concerns you may have with regard to the UX ...
> 
> These rules sound great, but there are still many problems to fix:
> 1.It's hard to remember where is my app icon when groups are more than 3 or 5.
> 2.Drag a file to a collapsed group to open may not be very convenient.
> 3.The dock will become crowed again when all apps in grounps are opened.
> 
> I think you have a lot ideas in your mind ,I can hear you out. And if you have a picture in your mind , it would be perfect.

**Comment by shule1987** [comment]
> > > > I don't think this would be a good idea. This will cause many problems and the UX will be very complicated.
> > > 
> > > 
> > > @shule1987 ... if a dock extends(widens) more than 80% of the screen width it starts to look ugly ... it kind of loses its dock appeal ... what do you think ?
> > 
> > 
> > Well, it defently will look ugly when the dock gets very crowed. But sometime we have to choose between beauty and efficient when these two things can't be together. Yes, the dock will be less crowed when the app icons are collapsed, but how will you switch to a minimized and collapsed window if there are lot of windows on your screen,or even between screens ? I kown ALT+TAB can do this , but except this , is there a more convenient way? Most normal people just use their mouse or just touchpad.
> 
> When we design great UI's its also our responsibility to safeguard the aspects of our design from turning ugly and losing its visual appeal ... this will ensure that our UI aesthetics last longer ... may be even make them timeless ...
> 
> > I don't think this would be a good idea. This will cause many problems and the UX will be very complicated.
> 
> **So i guess this becomes a matter of necessity than just an idea ... don't you think ???**

All ideas are precious to us, we will consider them very seriously before they become real features.  And thank you for your enthusiasm, we need it very much.

**Comment by aiamuzz** [comment]
> These rules sound great, but there are still many problems to fix:
> 1.It's hard to remember where is my app icon when groups are more than 3 or 5.

That's not a an issue of the UI/UX designer ... that depends on the user's intelligence ... in the hands of a smarter user this will never be an issue.

> 2.Drag a file to a collapsed group to open may not be very convenient.

This is upto the coders to work it out ... a drag on the group and stay for a second on it should open the group so the drop can be completed ... this implementation can be delayed subject to the coders to achieving it programmatically.

> 3.The dock will become crowed again when all apps in grounps are opened.

**my rule No 3** takes care of this issue, remember ... ONLY one group can be in an open state ... please note system tray group is not part of this rule(which translates to only 2 group can be open in a dock) ... 

imagine a use case where there is one group which is open, if a user clicks on another group, this open group will close and the new group which the user clicked will be expand.

as far as the dock getting over crowded that's unavoidable ... that's bound to happen no matter what ... but with this system of groups ... users will be able to have more applications on the dock than they can currently ... and currently the dock is getting crowded faster without them !!!

**Remember this grouping of icons feature will become a necessity going forward** ... when the independent developer community for plugins grows eventually ... for productivity having only 4 plugins will not be sufficient ... the plugins too would need a group with the yet to release option of choosing 'always show icons in system tray' ... this type of expandable / collapsible group for plugins also will become a necessity ...

This is one of our plugins ... https://github.com/CareF/deepin-dock-plugin-neoweather ... and we have  plans for a couple more ... i have teamed up with @careF ... and assisting him in the UI/UX of the same. ... without the grouping option for plugins the dock does not have space currently.

**Comment by aiamuzz** [comment]
> All ideas are precious to us, we will consider them very seriously before they become real features. And thank you for your enthusiasm, we need it very much.

Happy to be involved ... being a professional designer myself ... i greatly value your eye for design assuming you are the principal designer for Deepin UI/UX right from its first prototype ... 

As creative people we often encounter a 'creator's block' and the best way to fight it is to bouncing ideas off other designers and users(borrow their eyes), this i have experienced personally, will greatly increase productivity and the over all appeal of the elements we design ... so many times i myself am stuck with a 'creators block' not sure if something will look good or not ... a second opinion or an extra set of eyes have eased up things for me !!!

**Comment by shule1987** [comment]
> > These rules sound great, but there are still many problems to fix:
> > 1.It's hard to remember where is my app icon when groups are more than 3 or 5.
> 
> That's not a an issue of the UI/UX designer ... that depends on the user's intelligence ... in the hands of a smarter user this will never be an issue.
> 
I don't agree with you here ,we should not discriminate wether user is smart or not. The simpler the better.
> > 2.Drag a file to a collapsed group to open may not be very convenient.
> 
> This is upto the coders to work it out ... a drag on the group and stay for a second on it should open the group so the drop can be completed ... this implementation can be delayed subject to the coders to achieving it programmatically.
I know we can do this , but it's simply too slow.
> 
> > 3.The dock will become crowed again when all apps in grounps are opened.
> 
> **my rule No 3** takes care of this issue, remember ... ONLY one group can be in an open state ... please note system tray group is not part of this rule(which translates to only 2 group can be open in a dock) ...
> 
"Any application that has an open window will show outside the group" this meas all opened applications in groups would show outside, the dock will become crowed. If only one group can be open, there will be issues that I metioned above " how will you switch to a minimized and collapsed window if there are lot of windows on your screen,or even between screens"

> imagine a use case where there is one group which is open, if a user clicks on another group, this open group will close and the new group which the user clicked will be expand.
> 
> as far as the dock getting over crowded that's unavoidable ... that's bound to happen no matter what ... but with this system of groups ... users will be able to have more applications on the dock than they can currently ... and currently the dock is getting crowded faster without them !!!
> 
> **Remember this grouping of icons feature will become a necessity going forward** ... when the independent developer community for plugins grows eventually ... for productivity having only 4 plugins will not be sufficient ... the plugins too would need a group with the yet to release option of choosing 'always show icons in system tray' ... this type of expandable / collapsible group for plugins also will become a necessity ...
> 
> This is one of our plugins ... https://github.com/CareF/deepin-dock-plugin-neoweather ... and we have plans for a couple more ... i have teamed up with @CareF ... and assisting him in the UI/UX of the same. ... without the grouping option for plugins the dock does not have space currently.

How many applications will you usually use?  Why you need so many icons on dock even if not every icon is necessary?

I know our screen space is limited , something is showed  means somethingelse is hide. I agree we can hide those icons that are not so important, since you have kept so many icons on dock , I  don't think them should be treat differently.   Beside that  ,there are many hidden point on dock rather than one , the user experience is too complicate.  Think about this , applications can be group together on desktop in IOS longtime ago, but how come the dock  have no this feature?

**Comment by gokhanyildirimlar** [comment]
> I don't agree with you here ,we should not discriminate wether user is smart or not. The simpler the better.

I disagree with this. User doesn't have to add or use this system if he/she doesn't want to. So, it doesn't make ui complicated for people who value simplicity. Also, do people look for an app on their phone? No, they know which folder includes which app.

> "Any application that has an open window will show outside the group" this meas all opened applications in groups would show outside, the dock will become crowed.

It can expand upwards, I think. 

> Think about this , applications can be group together on desktop in IOS longtime ago, but how come the dock have no this feature?

Who cares about iOS? It limits the user all the time, all areas. This is not simplicity but limiting. Do people confuse when they use folders on the dock? No, they already have tons of folder on the screen. That is Apple that doesn't give this feature, it's not about simplicity. Take Android to hand, there is this feature on the dock, and it works very well.

I wanna add something to this topic. Maybe I should open another issue for this one but I wanna ask here first. Another feature, something like Albert would be great too. Using Albert is fine and enough but I am talking about something shares the same design language with DDE.

**Comment by aiamuzz** [comment]
> How many applications will you usually use? Why you need so many icons on dock even if not every icon is necessary?

@shule1987 ... judge for yourself ... :)

![image](https://user-images.githubusercontent.com/3283676/53221120-fe861700-368d-11e9-8064-f7965c462c88.png)

1. Launcher (Fixed).
2. Multitasking view.
3. Personal app(Utility)
4. Store
5. Terminal
5. File Manager
6. Personal(Browser app)
7. Personal(Browser app)
8. Personal(Dev app)
9. Personal(Dev app)
10. Control Center

System Tray & its icons

1 personal plugin.

**I have only 5 personal apps and 1 personal plugin ... so i have 6 icons of my choice and the dock width is already 80% ...**

@shule1987 ... now you know why we are requesting for a expandable / collapsible options for apps as well as for plugins.

> Think about this , applications can be group together on desktop in IOS longtime ago, but how come the dock have no this feature?

let's not even go there ... apple is a service which is highly restrictive ... its for people who forfeit their freedom ... Android is a better reference point ... i agree with @gokhanyildirimlar ...

With  ...

1. Only one one group open at any time ... 
2. Open applications should show outside the group so one can easily access the open application 'right-click' menu ...

will pretty much take care of crowding and any complexities with regard to UX ...

grouping of icons in the app section and a plugin section is fast becoming a necessity ... currently i have only one custom plugin ... i would like at least another 3-4 plugins ... without icon grouping there is no way ... except at the cost of the visual appeal(a crowded and uglyly wide dock !!!

**Comment by aiamuzz** [comment]
If i imagine ... i would probably have the following groups ...

1. Deepin Family apps(4-6 apps)
2. Dev Tools(3-5 apps)
3. Internet/Browser(5-6)

4. Custom Plugins(3-4)

that would enable me to have at lest double the apps then i currently have ...

@shule1987 ... if you look at it positively ... Deepin would never have caught so many people's attention if not for your greal visual UI ... by adding groups you are getting more ways to throw your beautiful UI's at the user ... increasing its applet ... 

When we are talking about visual appeal ... you are The best person to judge if a horizontal expand/collapse animation will give a higher appeal or a vertical popup(like the plugin popup) and arranging the icons in an array (rows x column's) will appeal better !!!

It will in the least make your Dock more interesting and appealing !!!

**Comment by gokhanyildirimlar** [comment]
By the way, we all talk about dock but think about this for the efficient mod too, for system tray and launcher icons. The only reason that people don't put many stuff, is they know they can't. 

@aiamuzz, what are you thinking about something like Albert but made by Deepin according to DDE design language?

**Comment by aiamuzz** [comment]
> @aiamuzz, what are you thinking about something like Albert but made by Deepin according to DDE design language?

@gokhanyildirimlar ... sorry ... what is Albert ... can you post a link to it ?

**Comment by BLumia** [comment]
> I wanna add something to this topic. Maybe I should open another issue for this one but I wanna ask here first. Another feature, something like Albert would be great too. Using Albert is fine and enough but I am talking about something shares the same design language with DDE.

Yeah you should open another issue for this feature request since this is sort of off-topic in this issue.

**Comment by gokhanyildirimlar** [comment]
@aiamuzz, I opened a new issue for this.

@BLumia, done. Thanks for navigating me.

**Comment by gokhanyildirimlar** [comment]
This is not gonna happen. So, there is no need for further discussion.
