### ISSUE TITLE
dock栏wifi图标状态显示不正确

### ISSUE THREAD

**Issue by lolimay** [linuxdeepin/developer-center#868]
## 缺陷描述

连上wifi后，网络实际上是连通的，但是dock栏显示的却是网络未连通的图标。

## 复现步骤

1. 从学校回家
2. 开机
3. 连接上家中的移动wifi
4. dock栏wifi状态显示不正确
5. 等待半个小时候再次查看，图标仍然未更新

## 期望行为

正确显示dock栏wifi图标

## 截图

![image](https://user-images.githubusercontent.com/32427260/52171231-40f5bb80-2794-11e9-9016-9dec01030459.png)

## 复现环境:

之前宽带运营商: 教育网/中国联通
当前宽带运营商: 中国移动

### 发行版以及版本

deepin 15.9+1

### 相关的软件包版本

dde-dock 4.8.9-1

<details>
<summary>PS. 为什么 dde-dock --version 和 apt search dde-dock 显示的版本号不一样?</summary>

````bash
➜ dde-dock --version
load translate "/usr/share/dtkwidget/translations/dtkwidget2_zh_CN"
load translate "/usr/share/dde-dock/translations/dde-dock_zh_CN"
dde-dock 2.0
➜ apt search dde-dock
正在排序... 完成
全文搜索... 完成  
dde-disk-mount-plugin/panda,now 4.7.5-1 amd64 [已安装]
  plugin of dde-dock

dde-dock/panda,now 4.8.9-1 amd64 [已安装]
  deepin desktop-environment - dock module
````

</details>

**Comment by lolimay** [comment]
update: 试了万能重启大法，发现这个问题还是存在。

**Comment by listenerri** [comment]
http://packages.deepin.com/misc/check_network_status.txt

目前检查网络连通性是通过上面这个地址测试的，你使用 wget 或 curl 测试下看能不能访问？

**Comment by lolimay** [comment]
你这让我想起来了，我在家的时候的官方仓库的软件源([packages.deepin.com](http://packages.deepin.com))是连不上的，后来自行改成了清华源([https://mirrors4.tuna.tsinghua.edu.cn/deepin](http://mirrors4.tuna.tsinghua.edu.cn/deepin))才能正常安装软件包。

刚回学校，现在dock栏的wifi图标显示已经正常了。应该是家里的宽带无法访问([packages.deepin.com](http://packages.deepin.com))这个服务器。

**Comment by felixonmars** [comment]
从 ipip 等在线服务测试，目前没有发现移动网络访问服务器存在有普遍问题。

请尝试在家的时候 ping packages.deepin.com 并贴一下返回结果。

**Comment by lolimay** [comment]
好的，下次回去的时候注意下。
<s>PS. 原来肥猫大哥也是个夜猫子( ⊙ o ⊙ )呀</s>
