### ISSUE TITLE
[archlinux]程序无响应被强制退出以后,dock上依旧保持图标

### ISSUE THREAD

**Issue by zhuzilinuser** [linuxdeepin/developer-center#87]
![20160522110633](https://cloud.githubusercontent.com/assets/12298476/15451915/706256de-1fa0-11e6-8a3c-5e20af015a06.png)
任何程序都有,目前只截图了qtcreator的.

**Comment by fasheng** [comment]
好像确实是有这个问题...

**Comment by sbwtw** [comment]
@electricface

**Comment by electricface** [comment]
试试最新版的，我不能重现这个bug

**Comment by zhuzilinuser** [comment]
现在没这个问题了

**Comment by fasheng** [comment]
:+1: @electricface
