### ISSUE TITLE
[Feature request] animations

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#870]
I think deepin desktop would look much better with some cool animation effects.

**Comment by aiamuzz** [comment]
> I think deepin desktop would look much better with some cool animation effects.

hmmmmm ... windows manager already has some nice animation ... where else you feel there is possibility of having more without making it look forced or cheap ?

**Comment by SiamSami** [comment]
animations of right clicking on the desktop...

**Comment by aiamuzz** [comment]
> animations of right-clicking on the desktop...

oh ... you mean screen savers ?

**Comment by lolimay** [comment]
Can you make some animation demonstrations to show the cool effects(eg. animations of right-clicking on the desktop)?

I can not intuitively feel it with you texts:D

**Comment by SiamSami** [comment]
no, I meant this,
![deepin-screen-recorder_select area_20190203191013](https://user-images.githubusercontent.com/33563064/52177171-5f38d700-27e7-11e9-90ef-e806a7eb0085.gif)

**Comment by aiamuzz** [comment]
oh ... the pointer animations ?

**Comment by SiamSami** [comment]
yes....

**Comment by aiamuzz** [comment]
ok ... from where did you get your pointer animation ... is it present in the deepin OS ... ?
i never came across it ...

**Comment by aiamuzz** [comment]
> ... honestly, I didn't understand what you meant by "pointer animation". I'm talking about the animation of right-clicking

i thought you were referring to the blue animation of the mouse cursor in your screencast ... are you referring to the animation where the menu's are drawn ?

**Comment by SiamSami** [comment]
> i thought you were referring to the blue animation of the mouse cursor in your screencast ... are you referring to the animation where the menu's are drawn ?
yes!!!!!

**Comment by aiamuzz** [comment]
> > i thought you were referring to the blue animation of the mouse cursor in your screencast ... are you referring to the animation where the menu's are drawn ?
> 
> yes

you mean blue mouse cursor animation ?

**Comment by SiamSami** [comment]
> you mean blue mouse cursor animation ? ... I don't see any animation in the menu draw ...

I mean the opening of the right-click menu

**Comment by aiamuzz** [comment]
> > you mean blue mouse cursor animation ? ... I don't see any animation in the menu draw ...
> 
> I mean the opening of the right-click menu

oh ... is there an animation there currently ?
I thought it was pretty standard menu draw ...

@SiamSami ... do you have any example menu draw animations on other linux distros or on windows and mac ... why don't you post a link to those animations ?

**Comment by SiamSami** [comment]
In KDE, if you right click on the desktop then you get a menu with a fine animation.
And no, there is no animation currently. It's a feature request.

**Comment by aiamuzz** [comment]
ok ...

i think you are talking about these ...
https://www.youtube.com/watch?v=a_JDhssrsMI
https://www.youtube.com/watch?v=yFRPUcbXieo

**Comment by SiamSami** [comment]
yes, I was talking about those.

**Comment by aiamuzz** [comment]
> yes, I was talking about those.

but they lack the finesse of deepin's animation ... deepin's WM windows view animation are simplistic and elegant  ... the animations on KDE Plasma seems more there because they are available ... Its low on aesthetics ... It isn't a great idea to have animations just because its achievable !!!

I liked only 2 of those effects ...

1. one was the Blur control slider (Deepin currently has the ability to switch off blur)
to turn blur off
`gsettings set com.deepin.wrap.gnome.mutter dynamic-blur false`
to turn blur ON
`gsettings set com.deepin.wrap.gnome.mutter dynamic-blur false`

2. The inserting animation while switching the desktop application windows.

**Comment by SiamSami** [comment]
By the way, I am not talking about that either. I am talking about the animation of opening the menu.

**Comment by alexwender1** [comment]
@hualet The order is valid. But Deepin should have the option of not displaying animations KEEPING transparency on the interface. Microsoft Windows lets you turn off effects (without turning off Windows Aero)... making the system faster and less cumbersome to the processor.

**Comment by SiamSami** [comment]
`deepin-kwin` has some cool animations so closing it for now...
