### ISSUE TITLE
【deepin_V23_Release】【一般】【有空】【预发布测试】【玲珑】"ll-builder create test"创建的yaml文件中显示文件路径为“org.deepin.demo”

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#8709]
### SUMMARY | 问题概要

"ll-builder create test"创建的yaml文件中显示文件路径为“org.deepin.demo”

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240514/deepin-23-beige-rc-amd64-20240514-213855.iso
```

### PRE-REQUIREMENT | 预置条件

1.系统内安装linglong-builder 
命令：sudo apt install linglong-builder

### STEPS TO REPRODUCE | 复现步骤

1.ll-builder create test 创建玲珑测试项目
2.进入文件夹，cat yaml
3.观察文件内路径名称显示

### OBSERVED RESULT | 观察到的结果

1."ll-builder create test"创建的yaml文件中显示文件路径为“org.deepin.demo”
![截图_deepin-terminal_20240521175634](https://github.com/linuxdeepin/developer-center/assets/96415804/d1054d6a-b742-40be-86eb-54fec3250c4e)

### EXPECTED RESULT | 期望的结果
1."ll-builder create test"创建的yaml文件中显示文件路径为“test”
_No response_

**Comment by babyfengfjx** [comment]
@dengbo11  请安排优化~

**Comment by dengbo11** [comment]
现在这个command 选项不与文件名关联了，统一显示hello world

**Comment by vivianxf** [comment]
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1483:/dde/testing/ ./
验证步骤：提单的步骤
验证现象：![截图_deepin-terminal_20240524151437](https://github.com/linuxdeepin/developer-center/assets/96415804/d0f722e9-7d13-444b-9ded-5765396dc912)
验证结果：通过
![截图_deepin-terminal_20240524151437](https://github.com/linuxdeepin/developer-center/assets/96415804/8ea60c86-1553-43ca-a53c-12e5f11cd7a3)
