### ISSUE TITLE
Feature Request / Enhancement : Add Blur slider just like we currently have a Transparency Slider !

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#871]
Hi,

It would be great value add if you could implement a Blur Slider just like how you have implemented the Transparency Slider ... I just saw this implementation on KDE Plasma !!!

I have been wanting to request for this feature from a long time now ... but hesitated thinking that the blur effect was static ... but after seeing it on KDE Plasma ... I now know that the Blur effect can be a dynamic one ... and hence a slider is implementable.

FYI ... i currently know that we can turn off blur ... which i have been using for quite some time now ...

If anybody is interested to try it ... here is the command to run in the terminal ...

Switch OFF : `gsettings set com.deepin.wrap.gnome.mutter dynamic-blur false`
Switch ON : `gsettings set com.deepin.wrap.gnome.mutter dynamic-blur true`

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
