### ISSUE TITLE
【deepin_V23_Release】【一般】【有空】【预发布测试】【玲珑】"ll-builder create 111"创建项目文件中的 yaml权限设置错误

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#8710]
### SUMMARY | 问题概要

"ll-builder create 111"创建项目文件中的 yaml权限设置错误

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像： https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240514/deepin-23-beige-rc-amd64-20240514-213855.iso
```

### PRE-REQUIREMENT | 预置条件

1.系统内安装linglong-builder 
命令：sudo apt install linglong-builder

### STEPS TO REPRODUCE | 复现步骤

1.ll-builder create 111 创建玲珑测试项目
2.进入111文件夹
2.在当前目录下执行ls -la 查看yaml文件权限

### OBSERVED RESULT | 观察到的结果

1.ll-builder create xxx 目录下linglong.yaml 权限为 444，当前用户不可编辑
![截图_deepin-terminal_20240521175709](https://github.com/linuxdeepin/developer-center/assets/96415804/5dc37c8a-9501-4864-8864-2492571b6b4f)

### EXPECTED RESULT | 期望的结果

1.ll-builder create xxx 目录下linglong.yaml 权限应该为 644，当前用户可以编辑

**Comment by babyfengfjx** [comment]
@dengbo11  请安排优化~

**Comment by dengbo11** [comment]
已修复

**Comment by vivianxf** [comment]
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1483:/dde/testing/ ./
验证步骤：提单的步骤
验证现象：检查yaml权限为644
验证结果：通过
![截图_deepin-terminal_20240524151741](https://github.com/linuxdeepin/developer-center/assets/96415804/9f7b22e2-4c02-4918-aed5-b4f105598625)
