### ISSUE TITLE
[Feature request] show wine programs in dde-launcher

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#872]
It would be great if deepin-menu showed wine programs as well

**Comment by aiamuzz** [comment]
> It would be great if deepin-menu showed wine programs as well

I believe its upto the Wine frontend application(for eg. playonlinux) to drop `.desktop` files into folders that populate launcher entries and you'll find them in it ... unless i am wrong ...

**Comment by SiamSami** [comment]
> I believe its upto the Wine frontend application(for eg. playonlinux) to drop .desktop files into folders that populate launcher entries and you'll find them in it ... unless i am wrong ...

but KDE and GNOME can show installed wine programs.

**Comment by SiamSami** [comment]
By thw way, installed wine programs' .desktop files are located in `/home/toor/.local/share/applications` and in `/home/toor/.local/share/applications/wine/Programs`

**Comment by electricface** [comment]
Which program's menu are you talking about?

**Comment by SiamSami** [comment]
> Which program's menu are you talking about?

@electricface I'm talking about this,
![deepin-screen-recorder_desktop_20190213212210](https://user-images.githubusercontent.com/33563064/52722273-7c368c80-2fd5-11e9-8584-b276f73de642.gif)

**Comment by aiamuzz** [comment]
@electricface ... he mean he wants the wine application to show up in the deepin launcher !!!

**Comment by electricface** [comment]
The desktop files in the folder `~/.local/share/applications` and `~/.local/share/applications/wine/Programs` can be displayed in the dde launcher.

**Comment by electricface** [comment]
I think it may be caused by the failure of the Exec field parsing of the desktop file.

**Comment by electricface** [comment]
https://cr.deepin.io/#/c/go-lib/+/41615/

**Comment by liuwen123** [comment]
已修复
