### ISSUE TITLE
[bug] Doesn't switch to the window opened by another program

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#873]
## Describe the bug

If a program opens another program, then Deepin doesn't switch to it automatically.

*A clear and concise description of what the bug is.*

## To Reproduce

*We can fix a bug faster if we can reproduce the bug, so provide steps to reproduce the bug is very helpful for us.*

1. Open any program that has the ability to open another program.
2. Click on any link or any other thing that opens another program.
3. The program is opened but we are not switched to it.

## Expected behavior

We are supposed to get switched to that new window.

## Enviroments:

Distro: Archlinux
Desktop: Deepin DE 15.9

**Comment by aiamuzz** [comment]
may not be a bug ... just not implemented i guess ... will go as more of an enhancement i believe !

**Comment by hualet** [comment]
Issue confirmed, but I can't reproduce that repeatedly. I tested that with File Manager, BTW.

**Comment by jouyouyun** [comment]
@SiamSami What's the program name?

**Comment by SiamSami** [comment]
@hualet Any update on this?

**Comment by BLumia** [comment]
Did you still have this issue?

**Comment by SiamSami** [comment]
@BLumia I don't have the problem with GTK+ programs anymore. But I still have it with Qt programs.

**Comment by BLumia** [comment]
> @BLumia I don't have the problem with GTK+ programs anymore. But I still have it with Qt programs.

Tested with dde-file-manager and it seems works without problem, what's the program you used which can reproduce this issue? and what WM you are using, dde-kwin or deepin-wm?

**Comment by SiamSami** [comment]
@BLumia I'm using dde-kwin and I'm using Okular which has this issue.

**Comment by SiamSami** [comment]
So, apparently the problem was with `deepin-mutter`. I don't see any such bug with `deepin-kwin`.
Closing.
