### ISSUE TITLE
[Feature Request] Always on top feature for Deepin Terminal

### ISSUE THREAD

**Issue by gokhanyildirimlar** [linuxdeepin/developer-center#874]
Always on top feature is a must on a terminal for some people. It becomes annoying when it goes to the background when it shouldn't for some work types. It'd be great to pin it on the foreground for all the working time.

**Comment by aiamuzz** [comment]
@gokhanyildirimlar ... its already there ... not just for terminal ... you have the option to all application windows in DeepinOS

![image](https://user-images.githubusercontent.com/3283676/52205273-83a2bb00-289c-11e9-8157-c1487b7eda2f.png)

**Comment by aiamuzz** [comment]
In fact you have one better ... you can make your terminal follow you around when you switch your workspaces ... with these 2 options checked !

![image](https://user-images.githubusercontent.com/3283676/52205393-f1e77d80-289c-11e9-826b-7764a628e728.png)

**Comment by SiamSami** [comment]
> ... its already there ... not just for terminal ... you have the option to all application windows in DeepinOS

I don't see it in Archlinux

**Comment by aiamuzz** [comment]
> > ... its already there ... not just for terminal ... you have the option to all application windows in DeepinOS
> 
> I don't see it in Archlinux

Oh ... then i guess it could only be a system wide feature on Deepin OS ... 
and I am guessing if its implemented in this fashion here ... then i am further guessing its upto the windows manager of your OS ... 

@hualet ... can probably confirm on my guess ... :)

**Comment by gokhanyildirimlar** [comment]
> @gokhanyildirimlar ... its already there ... not just for terminal ... you have the option to all application windows in DeepinOS
> 
> ![image](https://user-images.githubusercontent.com/3283676/52205273-83a2bb00-289c-11e9-8157-c1487b7eda2f.png)

Wait, where can I see those options actually? That's something new to me. I was using wmctrl.

**Comment by aiamuzz** [comment]
> Wait, where can I see those options actually on terminal? That's something new to me. I was using wmctrl for terminal. I can just right click and choose from those options on everyhting else but it doesn't work on Deepin Terminal. How did you manage to make it work?

works out of the box ... I guess you need to be on Deepin OS and not on DDE over other distro ... as @SiamSami ... confirmed he has ArchLinux with DDE ...

`Alt+Spacebar` will give you the above windows menu ... which has those options.

**Comment by gokhanyildirimlar** [comment]
@aiamuzz I am on Deepin but I didn't know about Alt+Space. Right click brings this menu for other Deepin programs but not on terminal. That's why I was using wmctrl. So it's not consistent then.

**Comment by aiamuzz** [comment]
> @aiamuzz I am on Deepin but I didn't know about Alt+Space. Right click brings this menu for other Deepin programs but not on terminal. That's why I was using wmctrl. So it's not consistent then.

hmmmm ... that's interesting ... 

can you open a terminal and hit alt+spacebar and send a screenshot of the same ? ... just curious ...
also could you post a similar snapshot for say a file manager and a browser too ... just can't believe your terminal has been turned an outcast ... :)

**Comment by gokhanyildirimlar** [comment]
@aiamuzz Alt+Space bar combo works just fine. I just didn't know about it and it's not written on shortcuts list. Thanks for letting me know. :) 

Additionally, we can use "right click" option for this menu on other programs but it doesn't work on terminal. I meant this by saying it's not consistent.

**Comment by SiamSami** [comment]
> works out of the box ... I guess you need to be on Deepin OS and not on DDE over other distro ... as @SiamSami ... confirmed he has ArchLinux with DDE ...

> `Alt+Spacebar` will give you the above windows menu ... which has those options.

`Alt-Spacebar` works for me. Thanks by the way.

**Comment by aiamuzz** [comment]
I have set this key combo as shortcut (Shift+Super+S) ... to toggle show on all workspaces option if anybody is interested ...

just run this command ...
`gsettings set com.deepin.wrap.gnome.desktop.wm.keybindings toggle-on-all-workspaces "['<Shift><Super>S']"`

**Comment by hualet** [comment]
@gokhanyildirimlar windows unmanaged by window manager(like Deepin Terminal) won't show the context menu on right clicks on the title bar ATM, you can just use the shortcut.

Looks like the problem is solved by @aiamuzz , thank you guys :)

**Comment by aiamuzz** [comment]
@hualet ... i believe this is no longer working now that kwin has replaced deepin-wm ?
