### ISSUE TITLE
[Feature Request] Option to hide program in the Launcher

### ISSUE THREAD

**Issue by DenysMb** [linuxdeepin/developer-center#876]
Hi, it'll be nice if we have the option to hide a especific program from the launcher or even some kind of "Deepin Menu Editor", like Alacarte and MenuLibre (or maybe a compatibility with one of these two).

**Comment by aiamuzz** [comment]
@DenysMb ... how do you intend/hope to launch the app after hiding it in the Launcher ?

**Comment by BLumia** [comment]
MenuLibre should works fine. Did you got any problem/issue while using that? i.e. You hide an item via menu-libre but the desktop entry still got displayed from the dde-launcer?

**Comment by DenysMb** [comment]
@aiamuz maybe with an option to see the hided programs or to unhide, like in Plasma. The option to hide programs is just to hide unwanted programs that you cannot unninstall.

@BLumia I use Deepin in Arch Linux, when I try to open Alacarte or MenuLibre they give me a error telling they can't find "application.menu", something like that

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
