### ISSUE TITLE
deepin-home-appstore-daemon 8.0.6.0025 集成请求

### ISSUE THREAD

**Issue by zty199** [linuxdeepin/developer-center#8762]
### package information | 软件包信息

包名 | 版本
--- | ---
deepin-home-appstore-daemon | 8.0.6.0025-1

### Package repository address | 软件包仓库地址

```
deb  [trusted=yes] https://aptly.uniontech.com/pkg/nonfree-beige-v2/release-candidate/5bqU55So5ZWG5bqXZGFlbW9uMjAyNDA1MTMyMDI0LTA1LTEzIDE0OjMyOjQ4/  unstable non-free
```

### changelog | 更新信息

deepin-home-appstore-daemon (8.0.6.0025) stable; urgency=medium

  * 修复 daemon 启动初始化可更新应用数据时异常提示玲珑应用可更新问题

### test suggestion | 测试建议

已知 #8378 集成的 daemon 版本中存在异常提示玲珑应用存在更新问题
复现方式：
1. 安装任意玲珑应用（如百度网盘，外网已上架玲珑包）
2. 关闭客户端
3. 执行 `systemctl stop com.home.appstore.daemon.service` 停止 daemon 进程
4. 重新打开客户端，等待一段时间后，左边栏显示存在应用更新，点击后显示百度网盘存在更新；再次关闭并重新打开客户端，百度网盘更新消失

### Sphere of influence | 影响范围

从商店安装的玲珑应用存在异常提示更新问题

### ADDITIONAL INFORMATION | 额外补充

无，可联系研发进行复现操作

**Comment by babyfengfjx** [comment]
@vivianxf  请开展集成验证，主要会解决该帖子上的提示更新问题：https://bbs.deepin.org.cn/post/273063

**Comment by vivianxf** [comment]
集成验证通过，请及时合入：

1.添加仓库升级成功，包版本正确
2.更新版本后，商店不存在玲珑应用更新信息
3.商店基本功能保持正常

综上所述，本次集成测试通过～
