### ISSUE TITLE
File manager does not recognize drag when uing Wacom tablet<xz2>

### ISSUE THREAD

**Issue by SreckoM** [linuxdeepin/developer-center#878]
When I use Wacom, File manager does not recognize left click drag action. So resizing and moving of window is buggy. You can not rectangular select icons. Can not drag icons.

Everything works ok when using mouse.

Using latest Deepin 15.9.1

**Comment by hualet** [comment]
@electricface please have a look at that.

**Comment by electricface** [comment]
This should be a problem with dtk.

**Comment by SreckoM** [comment]
This is still issue with 15.9.2

**Comment by hualet** [comment]
@justforlxz

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
