### ISSUE TITLE
安装器 6.0.53 集成

### ISSUE THREAD

**Issue by ArchieMeng** [linuxdeepin/developer-center#8783]
### package information | 软件包信息
|包名|版本|
|---|---|
|deepin-installer|6.0.53|
|dtkwidget|02a6f776da9d1f96077eb5b04d624f0247852272|

### Package repository address | 软件包仓库地址

[TBA](https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20240527/deepin-23-beige-rc-amd64-20240527-181533.iso)

### changelog | 更新信息

https://github.com/linuxdeepin/developer-center/issues/8443
https://github.com/linuxdeepin/developer-center/issues/8426
https://github.com/linuxdeepin/developer-center/issues/8418
https://github.com/linuxdeepin/developer-center/issues/8627
https://github.com/linuxdeepin/developer-center/issues/8434
https://github.com/linuxdeepin/developer-center/issues/8431

### test suggestion | 测试建议

参考链接并与设计确认。

### Sphere of influence | 影响范围

- 所有弹窗
- 全盘安装界面
- 创建用户界面

### ADDITIONAL INFORMATION | 额外补充

"清除Icon被截断"的问题需要DTK修复，本次不做验证。
![image](https://github.com/linuxdeepin/developer-center/assets/12139431/b1d2da9b-6a09-4606-a0f7-2f68e84d7471)
安装器部分修复需要DTK提交配合。该提交已被打入镜像。

**Comment by ArchieMeng** [comment]
@babyfengfjx 可以开展测试了。

**Comment by babyfengfjx** [comment]
@baicailio  请开展回归验证。

**Comment by baicailio** [comment]
新镜像所有的安装页面缩放都显示有问题：https://github.com/linuxdeepin/developer-center/issues/8797
上述问题单只有一个完全验证通过（https://github.com/linuxdeepin/developer-center/issues/8434），其余问题单里面有部分修改，部分未修改，集成打回
