### ISSUE TITLE
[Feature Request] deepin Voice Note

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#879]
Allow the application to capture internal audio from the system (without using the microphone)... streaming audio.

The applications that exist for this purpose, require many configurations and do not work in Deepin.

I ask that the Voice Recorder receive improvements; delivering this functionality natively.

**Comment by wangjia12** [comment]
This requirement has been included. We will determine whether to adopt it in the next requirement discussion.
https://pms.deepin.cn/index.php?m=story&f=view&storyID=293

**Comment by alexwender1** [comment]
The functionality has not yet become available...

**Comment by alexwender1** [comment]
Was the application killed?

**Comment by felixonmars** [comment]
> Was the application killed?

Yes. It was replaced by Deepin Voice Note.

**Comment by felixonmars** [comment]
Re-opening because I think it's a valid feature request for the replacement software too.

**Comment by meiyixiang** [comment]
Voice Recorder is not maintained now, please consider whether Voice notepad and screen recording can support this function.

**Comment by meiyixiang** [comment]
I have written this down
