### ISSUE TITLE
no desktop icons

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/developer-center#88]
With the latest packages I do not see any desktop items anymore.
They are present in **~/Desktop** and have the rocket emblem in the launcher but not visible on the desktop, no matter if fashion/efficient/classic mode, both metacity and gala/mutter WMs.
Is this a **nautilus** issue maybe?

**Comment by fasheng** [comment]
But it works for me in archlinux, here is
```
deepin-daemon 3.0.13-1
deepin-desktop 3.0.8-1
```

**Comment by oberon2007** [comment]
Hm. Bad news for me I guess :stuck_out_tongue_closed_eyes: 
Will have to find a way how I could investigate this further... :sweat_smile:

**Comment by hualet** [comment]
Hi @oberon2007 , please check if the dde-desktop process is running first :joy: and check whether your  desktop locations is set correctly to ~/Desktop 
`xdg-user-dir DESKTOP`

**Comment by oberon2007** [comment]
Thank you both - it was apparently a gsettings issue on my end :stuck_out_tongue:
