### ISSUE TITLE
含"&"的无线网络SSID显示问题

### ISSUE THREAD

**Issue by CJ6922G1CH** [linuxdeepin/developer-center#880]
## 缺陷描述

Dock栏中的无线网络列表无法正确显示含"&"的SSID，会给"&"后的字母加一个下划线。控制中心中的无线列表则正常。

## 复现步骤

扫描一个带"&"的SSID即复现。

## 截图

![1](https://user-images.githubusercontent.com/47511859/52543865-f6a1b980-2de7-11e9-8649-dda0fd4c258e.png)
![2](https://user-images.githubusercontent.com/47511859/52543893-38326480-2de8-11e9-82f5-ae8a916eec3f.png)

### 发行版以及版本

各个版本中均存在，包括15.9

**Comment by listenerri** [comment]
QPushButton 会将 `&`符号看作是设置快捷键的标识

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/41597

用 QLabel 替换了 QPushButton, 应该算是方案3 :)

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
