### ISSUE TITLE
[Feature request] Could add the option " move to folder " "copy to folder" in deepin file manager?

### ISSUE THREAD

**Issue by ghost** [linuxdeepin/developer-center#881]
Could add the option " move to folder " "copy to folder" in deepin file manager?
is very useful for move or copy files
examples:
![uzidl](https://user-images.githubusercontent.com/26883220/52548471-7fdad100-2d93-11e9-9657-7a4031b817de.png)

![nautilus-58a5f4153df78c345b50a2fd](https://user-images.githubusercontent.com/26883220/52548486-9719be80-2d93-11e9-95fa-f10beb7b6920.png)

**Comment by wangjia12** [comment]
https://pms.deepin.cn/index.php?m=story&f=view&storyID=292

This requirement has been included.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
