### ISSUE TITLE
org.deepin.mail 集成

### ISSUE THREAD

**Issue by kamiyadm** [linuxdeepin/developer-center#8818]
### package information | 软件包信息

org.deepin.mail | 6.4.7.4

### Package repository address | 软件包仓库地址

name: old  url: http://repo-dev.cicd.getdeepin.org

### test suggestion | 测试建议

1. 修改玲珑仓库，ll-cli repo modify http://repo-dev.cicd.getdeepin.org --name old
2. 安装或者更新 org.deepin.mail
3. 检查 /var/lib/linglong/entries/share/applications/deepin-mail.desktop 文件内Exec 后面是否含%U

### Sphere of influence | 影响范围

https://github.com/linuxdeepin/developer-center/issues/8817

**Comment by kamiyadm** [comment]
@Zeno-sole

**Comment by dengbo11** [comment]
- fix: https://github.com/linuxdeepin/developer-center/issues/8817

**Comment by babyfengfjx** [comment]
@vivianxf  请开展回归验证。

**Comment by vivianxf** [comment]
集成验证通过，请及时合入：

1.ll-cli repo modify http://repo-dev.cicd.getdeepin.org/ --name old 修改仓库成功
2.ll-cli upgrade org.deepin.mail更新邮箱成功
3.cat //var/lib/linglong/entries/share/applications/deepin-mail.desktop 配置文件exec字段包含%U
4.玲珑基本功能保持正常

综上所述，本次集成测试通过

**Comment by dengbo11** [comment]
已集成到玲珑仓库
