### ISSUE TITLE
登录窗口无法聚焦

### ISSUE THREAD

**Issue by kexul** [linuxdeepin/developer-center#882]
## 缺陷描述
在虚拟机里面看电影，然后过一段时间屏幕关掉了，然后重新进去，结果登录界面没法输入密码。没有光标在那个窗口里面闪烁，怎么都没法得到焦点。

## 复现步骤
在虚拟机里面看电影，然后熄屏。

**Comment by hualet** [comment]
只有虚拟机会出现这个问题？

**Comment by kexul** [comment]
是的@hualet

**Comment by hualet** [comment]
@zhaofangfangdeepin @mmxzmmxz 有遇到过么？

**Comment by hualet** [comment]
@yefeifei @liuwen123

**Comment by kexul** [comment]
重新试了一下，只要虚拟机处于全屏状态，锁屏之后登录窗口就没法获得焦点了。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
