### ISSUE TITLE
Unable to upgrade packages ... risk of breaking packages !!!

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#883]
@BLumia ... @hualet ...

Is there no way we can upgrade the following packages on Deepin ?

flatpak_1.2.2-1_amd64.deb
libc6_2.28-7_amd64.deb
locales_2.28-7_all.deb
libc-bin_2.28-7_amd64.deb

I hope Deepin comes close to the latest packages ... after moving to debian stable ... will it ?

**Comment by aiamuzz** [comment]
would be nice to have latest packages just like how Debian updates their repo's ... all the above packages i have downloaded from https://packages.debian.org/sid/flatpak ...

**Comment by BLumia** [comment]
https://wiki.debian.org/DontBreakDebian

FYI, we are still working on migrating to debian stable, but currently it's still WIP. Current deepin (distro) release is a (sort of) snapshot version of debian sid around few month ago, with some packages vendor/managed by deepin and some 3rd party package maintainer.

In other words, Deepin (distro) has its own independent package repository maintained by the package maintainer from Deepin, it is always NOT recommended to download and install package from other place outside the official repository, like the debian wiki said. Once you do that, you should take your own risk for what you're doing.

**Comment by aiamuzz** [comment]
`In other words, Deepin (distro) has its own independent package repository maintained by the package maintainer from Deepin, it is always NOT recommended to download and install package from other place outside the official repository, like the debian wiki said. Once you do that, you should take your own risk for what you're doing.`

@BLumia  ... Will this be the case even after Deepin moves to the Stable Debian Branch ... or ... the packages will continue to be behind ?

**Comment by BLumia** [comment]
> @BLumia ... Will this be the case even after Deepin moves to the Stable Debian Branch ... or ... the packages will continue to be behind ?

I'm not sure (cc: @deepinzhangshuang), but whatever it will be, it's always recommend to use the package provided by the official repository. [Don't suffer from shiny new stuff syndrome](https://wiki.debian.org/DontBreakDebian#Don.27t_suffer_from_Shiny_New_Stuff_Syndrome).

If you find any package provided by the official repository which caused a dept breaking, feel free to fire an new issue.

**Comment by aiamuzz** [comment]
@BLumia ... i had one question ... now that Deepin has moved to debian stable (currently in Beta) ... 

any chance the packages from here ... https://packages.debian.org/sid/flatpak ...will be part of this stable branch ?

**Comment by BLumia** [comment]
> any chance the packages from here ... https://packages.debian.org/sid/flatpak ...will be part of this stable branch ?

["Repositories that can create a FrankenDebian if used with Debian Stable: Debian *unstable* release (also known as *sid*)"](https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian)
