### ISSUE TITLE
【deepin_V23_Release】【一般】【正常】【内测反馈】【玲珑】使用“ll-pica convert -c test.deb -w testname -b”转制应用时,-b参数报错

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#8833]
### SUMMARY | 问题概要

关联集成： #8776 
使用“ll-pica convert -c test.deb -w testname -b”转制应用时,-b参数报错

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/community/releases/23-RC/amd64/deepin-desktop-community-23-RC-amd64.iso
linglong-bin:1.5.2-1
linglong-pica:1.1.1-1
```

### PRE-REQUIREMENT | 预置条件

参考文档：https://linglong.dev/guide/ll-pica/convert.html

### STEPS TO REPRODUCE | 复现步骤

1.升级到最新版本玲珑环境
2.apt download com.baidu.baidunetdisk
3.ll-pica convert -c com.baidu.baidunetdisk_4.17.7_amd64.deb -w w -b
4.观察输出

### OBSERVED RESULT | 观察到的结果

1.使用“ll-pica convert -c test.deb -w testname -b”转制应用时,-b参数报错
![image](https://github.com/linuxdeepin/developer-center/assets/96415804/e4531a58-82a1-49e3-82e9-dddcf44237b5)

### EXPECTED RESULT | 期望的结果

1.使用“ll-pica convert -c test.deb -w testname -b”转制应用时,-b没有报错，可以成功转制

**Comment by babyfengfjx** [comment]
@dengbo11  请进行分析优化~

**Comment by vivianxf** [comment]
测试不通过，执行ll-pica convert -c com.baidu.baidunetdisk_4.17.7_amd64.deb -w w -b，-b参数还是报错
![截图_deepin-terminal_20240621165729](https://github.com/linuxdeepin/developer-center/assets/96415804/864e2a5a-d3dd-4831-a6e6-b7a2ddc45dc7)

**Comment by chenchongbiao** [comment]
```bash
# 加入内测，更新到新版本的 linglong-builder 测试下。
sudo apt install deepin-unstable-source
sudo apt install linglong-builder
```

**Comment by vivianxf** [comment]
测试不通过，执行ll-pica convert -c com.baidu.baidunetdisk_4.17.7_amd64.deb -w w -b，-b参数还是报错
![截图_deepin-terminal_20240701160722](https://github.com/linuxdeepin/developer-center/assets/96415804/f2c523af-bf15-4ecb-a907-76f8d26281c7)

**Comment by vivianxf** [comment]
验证镜像：镜像地址：https://cdimage.uniontech.com/community/releases/23-RC2/amd64/deepin-desktop-community-23-RC2-amd64.iso
linglong-bin:1.5.7
验证步骤：提单的步骤
验证现象：使用“ll-pica convert -c test.deb -w testname -b”转制应用时无报错
验证结果：通过

![image](https://github.com/linuxdeepin/developer-center/assets/96415804/8ca21895-d9eb-4952-9f4e-25732084ca98)
