### ISSUE TITLE
[WINE] 15.9运行微信开发者工具导致系统dock栏崩溃

### ISSUE THREAD

**Issue by FurryWolfX** [linuxdeepin/developer-center#884]
## 缺陷描述

15.9运行微信开发者工具导致系统dock栏崩溃

## 复现步骤

打开微信开发者工具->关闭微信开发者工具->dock栏闪动，变为不可点击（假死），影响系统正常操作。

## 期望行为

微信开发者工具不会导致dock栏崩溃，不影响系统正常使用。

## 复现环境:

deepin 15.9

### 相关的软件包版本

不管是商店的微信开发者工具还是github最新的微信开发者工具，都存在该问题。

**Comment by listenerri** [comment]
经测试商店的 "微信Web开发者工具" 不会导致 dock 出问题

请给一下你使用的 github 上的仓库地址?

另外安装 systemd-coredump 和 dde-dock-dbgsym 并重现一下你说的 bug, 然后执行:
sudo coredumpctl dump dde-dock

**Comment by FurryWolfX** [comment]
![深度截图_选择区域_20190221130607.png](https://i.loli.net/2019/02/21/5c6e336947e67.png)
![深度截图_选择区域_20190221131006.png](https://i.loli.net/2019/02/21/5c6e336949636.png)

录屏：<https://github.com/FurryWolfX/Attachment/blob/master/%E6%B7%B1%E5%BA%A6%E5%BD%95%E5%B1%8F_Desktop_20190221130405.mp4?raw=true>

**Comment by listenerri** [comment]
执行下面的命令看一下相关程序的版本:
```
apt-cache policy dde-dock dde-daemon
```

**Comment by listenerri** [comment]
![default](https://user-images.githubusercontent.com/7995379/53145926-33866100-35dd-11e9-9ef3-d28c826c9c8c.png)

上面这个图片里的进程是哪个? 你把名称那一列拉的长一点, 如下图:


![_ _20190221133347](https://user-images.githubusercontent.com/7995379/53145967-6892b380-35dd-11e9-8c3f-119520827586.png)

**Comment by FurryWolfX** [comment]
```
dde-dock:
  已安装：4.8.9-1
  候选： 4.8.9-1
  版本列表：
 *** 4.8.9-1 500
        500 http://packages.deepin.com/deepin panda/main amd64 Packages
        100 /var/lib/dpkg/status
dde-daemon:
  已安装：3.22.0-1
  候选： 3.22.0-1
  版本列表：
 *** 3.22.0-1 500
        500 http://packages.deepin.com/deepin panda/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by FurryWolfX** [comment]
![深度截图_选择区域_20190221133845.png](https://i.loli.net/2019/02/21/5c6e39afd058d.png)
![深度截图_选择区域_20190221133908.png](https://i.loli.net/2019/02/21/5c6e39afcbf1f.png)

每秒30mb左右的速度增长，不得不手动终止

**Comment by listenerri** [comment]
执行以下命令看是不是后端在不断崩溃:
```
sudo coredumpctl list
```

**Comment by listenerri** [comment]
另外请上传一下 dock 的日志:
```
~/.cache/deepin/dde-dock/dde-dock.log
```

**Comment by FurryWolfX** [comment]
<https://github.com/FurryWolfX/Attachment/blob/master/dde-dock.log.tar.gz?raw=true>

**Comment by listenerri** [comment]
> 执行以下命令看是不是后端在不断崩溃:
> 
> ```
> sudo coredumpctl list
> ```

看日志像是后端在不断崩溃重启, 你执行下上面的命令看看

**Comment by FurryWolfX** [comment]
> > 执行以下命令看是不是后端在不断崩溃:
> > ```
> > sudo coredumpctl list
> > ```
> 
> 看日志像是后端在不断崩溃重启, 你执行下上面的命令看看

只展示2个东西

```
wolfx@wolfx-linux:~/Desktop$ sudo coredumpctl list
TIME                            PID   UID   GID SIG COREFILE  EXE
Thu 2019-02-21 13:03:37 CST   20390  1000  1000   6 present   /usr/bin/deepin-screen-recorder
Thu 2019-02-21 13:04:33 CST   21000  1000  1000   6 present   /usr/bin/deepin-screen-recorder
```

**Comment by listenerri** [comment]
@electricface 看起来跟 https://bbs.deepin.org/forum.php?mod=viewthread&tid=174680&page=1#pid562440 是一个问题

**Comment by listenerri** [comment]
@electricface 说已经修过了

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
