### ISSUE TITLE
[DOCK] 托盘区域对于相同程序的不同进程无法显示多个图标

### ISSUE THREAD

**Issue by ypingcn** [linuxdeepin/developer-center#885]
## 缺陷描述 description

1. 托盘区域对于相同程序的不同进程无法显示多个图标
The tray area cannot display multiple icons for different processes of the same program

2. 槽函数中以下代码将无法重启程序修改语言 （pid 是已经更改了的
The following code in the slot function will not restart the program to modify language

DApplication * app;
app->quit();
QProcess::startDetached(app->arguments()[0]);

## 复现步骤

问题 1 的复现

 - 安装 https://github.com/ypingcn/BingWallpaper/releases 或 qmake && make
 - 在终端的两个窗口中中执行  ./OneClickBingwallpaper

问题 2 的复现

 - 仅在一个终端中执行  ./OneClickBingwallpaper
 - 右键菜单中选择非当前语言进行切换

## 期望行为

问题 1 的期望

 - 出现两个图标

问题 2 的期望

 - 程序图片短暂消失后再次出现，且右键菜单语言能正确切换

### 发行版以及版本

Linux Deepin 15.9.1

### 相关的软件包版本

libdtkcore-dev/panda,now 2.0.9.15-1 amd64 [已安装，自动]
libdtkcore2/panda,now 2.0.9.15-1 amd64 [已安装]
libdtkwidget-dev/panda,now 2.0.9.16-1 amd64 [已安装]
libdtkwidget2/panda,now 2.0.9.16-1 amd64 [已安装]
libdtkwm2/panda,now 2.0.9-2 amd64 [已安装]

### 其他内容

cinnamon 没有这个问题，满足期望行为，故向 deepin 反馈是否为 dde 的问题

**Comment by listenerri** [comment]
第一个问题是 dde 的 bug, 目前对托盘程序的判断使用了 SNI 协议中的 id 字段, 就你的程序来看多个实例启动的话这个 id 是相同的, dock 处理新托盘时给去重了, 因此没有添加上来

**Comment by ypingcn** [comment]
@listenerri 问题 2 描述已修改 还请留意

**Comment by listenerri** [comment]
> @listenerri 问题 2 描述已修改 还请留意

问题2在其他桌面环境下可以正常工作吗?

**Comment by ypingcn** [comment]
> > @listenerri 问题 2 描述已修改 还请留意
> 
> 问题2在其他桌面环境下可以正常工作吗?

我主用 linuxmint 的 cinnamon ，是可以的，其他的 de 我试试

**Comment by ypingcn** [comment]
在 deepin 上装了这几个桌面环境，测试如下
gnome 不显示图标
kde mate xfce 托盘相应图标闪烁，第一次点击不切换，第二次点击后切换

其他信息

xfce 4.12

kde plasma 5.12.5
kde 框架版本 5.46.0
Qt 版本 5.10.1
内核版本 4.15.0-29deepin-generic

**Comment by listenerri** [comment]
问题在这个任务里处理了： https://github.com/linuxdeepin/internal-discussion/issues/1072 

你可以尝试下相关的代码提交能否修复你的问题，或者等下次更新推送后进行测试。
另外麻烦你将测试结果回复在这里，届时如果已经修复，请关闭 issue。

**Comment by ypingcn** [comment]
两个问题已修复，15.9.3 中程序只需要一次重启即可更换语言，相同程序的不同实例也能显示两个图标，感谢大佬们
