### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【RC2镜像测试】【DDE】0531镜像中,deepin ID模块登录对话框展示双图标

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#8853]
### SUMMARY | 问题概要

必现问题

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240531/deepin-23-beige-rc2-amd64-20240531-113757.iso
```

### PRE-REQUIREMENT | 预置条件

点击deepin ID登录按钮

### STEPS TO REPRODUCE | 复现步骤

观察deepin ID登录对话框的图标展示效果

### OBSERVED RESULT | 观察到的结果

登录对话框出现双图标

![截图_选择区域_20240531133512](https://github.com/linuxdeepin/developer-center/assets/62528742/9347b5e2-236e-46c6-b4ca-293e56644b60)

### EXPECTED RESULT | 期望的结果

仅展示一个图标

**Comment by babyfengfjx** [comment]
@kegechen  需要优先处理。

**Comment by kegechen** [comment]
有点奇怪，qt6 引入webengineview之后dtk的无标题设置失败。

**Comment by xuqi27837288** [comment]
【环境】
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240531/
【验证结论】
验证通过

![截图_选择区域_20240604095107](https://github.com/linuxdeepin/developer-center/assets/62528742/a1352344-c0f6-4200-95ab-40f1b678ad67)
