### ISSUE TITLE
multi user accounts

### ISSUE THREAD

**Issue by antechdesigns** [linuxdeepin/developer-center#886]
## Describe the bug

Missing user login icon at boot (more than one account)

## To Reproduce

create a new user, shutdown/reboot, can only log in with last user account

## Expected behavior

get to pick user to login at boot

### Distro & Version
archlinux deepin (latest)

### Related package version

Probably lightdm (something I need to edit in lightdm.conf ?)

Once logged in at boot and log out the select user icon is visable (bottom right)

@felixonmars

**Comment by justforlxz** [comment]
Can you execute this command?

```
qdbus --literal --system com.deepin.daemon.Accounts /com/deepin/daemon/Accounts com.deepin.daemon.Accounts.UserList
```

**Comment by antechdesigns** [comment]
> Can you execute this command?
> 
> ```
> qdbus --literal --system com.deepin.daemon.Accounts /com/deepin/daemon/Accounts com.deepin.daemon.Accounts.UserList
> ```

@justforlxz If this is suppose to add multi user icon at boot ( bottom right login screen ), it does not :(

**Comment by justforlxz** [comment]
The internal test found the opposite problem,  single user showed toggle button. I need to review  code further.

**Comment by antechdesigns** [comment]
> The internal test found the opposite problem, single user showed toggle button. I need to review code further.

Just to clarify, logging out shows toggle button, just at boot 'no toggle button'

**Comment by antechdesigns** [comment]
wow good job guys, fixed!! ;)
