### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【RC2镜像测试】【DDE】【launchpad】在应用文件夹内，使用右键 点击右键菜单中的发送到桌面时，不停弹出右键菜单后窗口返回上一级

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#8862]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://cdimage.uniontech.com/community/releases/23-RC/amd64/deepin-desktop-community-23-RC-amd64.iso
dde-launchpad 0.6.12
```

### STEPS TO REPRODUCE | 复现步骤

1. 点击打开应用文件夹 - 在任意图标上点击右键 - 右键多次单机发送到桌面

### OBSERVED RESULT | 观察到的结果

1. 不停弹出右键菜单后窗口返回上一级
![录屏_选择区域_20240531150356](https://github.com/linuxdeepin/developer-center/assets/96416089/b7c53b6c-60d6-4263-8178-b84016133786)

### EXPECTED RESULT | 期望的结果

1. 右键点击无响应

**Comment by babyfengfjx** [comment]
@BLumia  请优先处理。

**Comment by BLumia** [comment]
关联  https://github.com/linuxdeepin/dde-launchpad/commit/9a4c4e28698038235f538fe76e77ab2e70b9a871

**Comment by luodeepin** [comment]
验证通过
dde-launchpad 0.7.1
![录屏_选择区域_20240606094840](https://github.com/linuxdeepin/developer-center/assets/96416089/c64b1a97-f010-436e-a20b-313aa311094f)
