### ISSUE TITLE
Shortcut Key  in WPS OFFICE

### ISSUE THREAD

**Issue by xenups** [linuxdeepin/developer-center#887]
shortcut keys such as Ctrl+V doesnt work in WPS Office in another languages.
Deepin 15.9

**Comment by hualet** [comment]
you changed your keyboard layout?

**Comment by amirlesani** [comment]
Yes , in Persian layout

**Comment by hualet** [comment]
I don't think we have a proper way to handle that situation at the moment  @jouyouyun @electricface

**Comment by electricface** [comment]
This should be a problem with wps.

**Comment by amirlesani** [comment]
So the solution is that going back to libre office 😅

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
