### ISSUE TITLE
华为开源镜像站

### ISSUE THREAD

**Issue by jingle0927** [linuxdeepin/developer-center#888]
https://mirrors.huaweicloud.com/

https://mirrors.huaweicloud.com/deepin-cd/
https://mirrors.huaweicloud.com/deepin

@hualet @deepinzhangshuang

**Comment by hualet** [comment]
@21wmd 可以加进去吧？

**Comment by lolimay** [comment]
那个我之前提到的那些IPv6镜像站，官方可以考虑一下吗？

#823

(可怜兮兮

**Comment by jingle0927** [comment]
http://deepin.xfree.com.ar/deepin
http://deepin.xfree.com.ar/deepin-cd

还有一个阿根廷的
