### ISSUE TITLE
Window resize lags / stutters

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#890]
## Description
Resize any window by right-bottom angle and everything is fine & smooth, but if you resize it by any other 3 angle - it’s always visibly laggy.

## To Reproduce
1. Start resizing window by any angle, except right-bottom.

## Screenshots
https://i.imgur.com/38PZyzD.mp4

## Enviroments:
OS: Manjaro 18.0.2 Illyria
Kernel: x86_64 Linux 4.19.20-1-MANJARO
Shell: bash 5.0.0
DE: Deepin 15.9
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
bits: 64
compiler: gcc
v: 8.2.1
tk: Qt 5.12.0
dm: LightDM

### Distro & Version
Manjaro Deepin 18.0.2

### Related package version
I'd like to provide something, but really not sure what caused it.

### Additional context
Most important thing - it seems to happen only on Nvidia.
Probably it's hardware related since i have Quadro P5200 card, which on it's own is not the most usual nvidia.
But i suspect it will happen on any nvidia machine with proprietary drivers.
Tested on another test-machine with Intel card - it doesn't happen, on VM it also doesn't happen.

Here's my machine specs **inxi -Fxxz**:
```
System:    Host: x133-pc Kernel: 4.19.20-1-MANJARO x86_64 bits: 64 compiler: gcc v: 8.2.1 Desktop: Deepin 15.9 tk: Qt 5.12.0 
           wm: DeepinWM dm: LightDM Distro: Manjaro Linux 
Machine:   Type: Laptop System: Dell product: Precision 7730 v: N/A serial: <filter> Chassis: type: 10 serial: <filter> 
           Mobo: Dell model: 0VC5H3 v: A00 serial: <filter> UEFI: Dell v: 1.6.0 date: 12/25/2018 
Battery:   ID-1: BAT0 charge: 94.1 Wh condition: 94.1/97.0 Wh (97%) volts: 13.0/11.4 model: BYD DELL GW0K986 serial: <filter> 
           status: Full 
CPU:       Topology: 6-Core model: Intel Core i9-8950HK bits: 64 type: MT MCP arch: Kaby Lake rev: A L2 cache: 12.0 MiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 69720 
           Speed: 941 MHz min/max: 800/4800 MHz Core speeds (MHz): 1: 1394 2: 1178 3: 1685 4: 932 5: 1846 6: 1592 7: 1606 
           8: 4449 9: 1065 10: 1483 11: 1038 12: 1672 
Graphics:  Device-1: NVIDIA GP104GLM [Quadro P5200 Mobile] vendor: Dell driver: nvidia v: 415.27 bus ID: 01:00.0 
           chip ID: 10de:1bb5 
           Display: x11 server: X.Org 1.20.3 driver: nvidia resolution: 3840x2160~60Hz 
           OpenGL: renderer: Quadro P5200/PCIe/SSE2 v: 4.6.0 NVIDIA 415.27 direct render: Yes 
Audio:     Device-1: Intel Cannon Lake PCH cAVS vendor: Dell driver: snd_hda_intel v: kernel bus ID: 00:1f.3 
           chip ID: 8086:a348 
           Device-2: NVIDIA GP104 High Definition Audio vendor: Dell driver: snd_hda_intel v: kernel bus ID: 01:00.1 
           chip ID: 10de:10f0 
           Sound Server: ALSA v: k4.19.20-1-MANJARO 
Network:   Device-1: Intel Ethernet I219-LM vendor: Dell driver: e1000e v: 3.2.6-k port: efa0 bus ID: 00:1f.6 
           chip ID: 8086:15bb 
           IF: eno1 state: down mac: <filter> 
           Device-2: Intel Wireless-AC 9260 driver: iwlwifi v: kernel port: 3000 bus ID: 6f:00.0 chip ID: 8086:2526 
           IF: wlp111s0 state: up mac: <filter> 
Drives:    Local Storage: total: 267.35 GiB used: 39.24 GiB (14.7%) 
           ID-1: /dev/nvme0n1 vendor: Samsung model: PM981 NVMe 256GB size: 238.47 GiB speed: 31.6 Gb/s lanes: 4 
           serial: <filter> 
           ID-2: /dev/sda type: USB vendor: Kingston model: DataTraveler 3.0 size: 28.88 GiB serial: <filter> 
Partition: ID-1: / size: 54.30 GiB used: 10.05 GiB (18.5%) fs: ext4 dev: /dev/nvme0n1p3 
Sensors:   System Temperatures: cpu: 59.0 C mobo: N/A gpu: nvidia temp: 61 C 
           Fan Speeds (RPM): cpu: 1688 fan-2: 1681 
Info:      Processes: 261 Uptime: 3m Memory: 62.75 GiB used: 1.17 GiB (1.9%) Init: systemd v: 239 Compilers: gcc: 8.2.1 
           Shell: bash v: 5.0.0 running in: deepin-terminal inxi: 3.0.30
```

Guys from Manjaro forum suggested that it's mutter / theme related, but i'm really not sure where to go with it, hope it's fixeable!

**Comment by felixonmars** [comment]
I can reproduce this on Arch too. @sonald @zccrs Any hints?

**Comment by sonald** [comment]
Does `any window` includes legacy x11 apps and gtk apps, e.g  xterm, gedit?

**Comment by keybreak** [comment]
@sonald 
Correct, i've tested pamac, gedit

**Comment by keybreak** [comment]
@sonald 
Please take a look at this:
https://aur.archlinux.org/packages/mutter-781835-workaround/?comments=all&O=180&PP=10

**dglt** from Manjaro forums:
> i dont use deepin but one thing i did notice in the short time using it was the complete lack of compositor options, i also have not read the other feature requests but i thought i would throw it out there. IIRC right now its just blur and not blur? they use a modified mutter that i could never find the actual configuration for and i dont think it can be replaced by the nvidia tweaked version of mutter that fixes the excessive stuttering issue with deepin/nvidia

Seems that this is a food for thought in right direction, if you're not onto it already :)

**Comment by zccrs** [comment]
Have you tested other window managers, such as kwin?

**Comment by keybreak** [comment]
If you mean with Deepin than no...I personally not really know how

If you mean other OS on the same machine i've tested Ubuntu, Fedora 29 and Manjaro KDE which have something different all of them was good without this weird stuff described in issue.

**Comment by felixonmars** [comment]
Some test results when resizing for top-left corner:

dde-file-manager window:
- deepin-wm: No flickering, lag heavily.
- mutter: Flickering border, no lag (not very smooth either).
- kwin: Flickering border, very smooth.
- deepin-metacity: Flickering border, no lag.

gedit window:
- deepin-wm: No flickering, lag sometimes.
- mutter: No flickering, no lag (not very smooth either).
- kwin: Flickering border, very smooth.
- deepin-metacity: Broken graphics/flickering heavily (not usable), no lag.

**Comment by keybreak** [comment]
deepin-metacity is the one which is used when **window effect** turned off?

According to your test best option is to go with kwin and tweak it somehow, so there's no flickering border...

But still, i assume you have tested those only with nvidia?
If it's gonna be changed from mutter, have to be heavily tested on intel / nvidia / amd.
I personally have Quadro P5200 and Mobile Intel GM45 Express available for tests.

In general i'm in love with all current animations, look and feel (some of it comes from modded mutter, if i understood correctly), and this issue with resizing on Nvidia is the only one i have against it, which ruins overall smooth experience.

So maybe trying just those patches would be enough?

Also @antechdesigns https://github.com/linuxdeepin/developer-center/issues/946 experimenting with Compiz, from the looks of it in terms of resizing windows, animation etc it looks very smooth (though i'd like to use vanilla Deepin animations configured, if ti comes to it one day).

**Comment by felixonmars** [comment]
I tested these with Intel & mesa. There is some ongoing effort to make a new wm based on kwin in the DDE team.

**Comment by keybreak** [comment]
wow, then i really hope it will go better than mutter! :)
Good luck & keep me posted

**Comment by keybreak** [comment]
Also, please read this:

**Troubleshooting / Performance problems** section
https://tutorials.renoise.com/wiki/Linux_FAQ

And this post:
https://forum.renoise.com/t/linux-renoise-and-choppy-sound/30407

They discuss how different compositors affect audio / general performance (which is huge deal for me), some of this info are little bit dated, but still worth read.

I personally can't say that i've had any audio issues with deepin-mutter, but seems that they value performance of both openbox and kwin

**Comment by aiamuzz** [comment]
do you mean the jumpy animation while trying to 

> wow, than i really hope it will go better than mutter! :)
> If it will bring resize lags down and still have all the blur / beautiful animations and feel of Deepin - i'm down with this change))
> 
> Plus, if i understand correctly also it will allow us to experiment with Wayland (which is good for the future)
> 
> Good luck & keep me posted

![deepin-screen-recorder_google-chrome_20190715124259](https://user-images.githubusercontent.com/3283676/61200240-64873f80-a6fe-11e9-9944-30db8967b2e0.gif)

@keybreak ... @BLumia ...

I think it continues to stutter on kwin as well ... might want to reopen this issue thread !

**Comment by keybreak** [comment]
Not exactly.

But yes - i also confirm what you show, on kwin it's even worse (but on kwin it's noticeable that now it's only Deepin programs), usual qt / gtk which are not part of DE is pretty smooth...

I think it's probably caused by how shadow is made (at least it looks that corners are most laggy parts of any interaction with window)

**Comment by BLumia** [comment]
> I think it's probably caused by how shadow is made (at least it looks that corners are most laggy parts of any interaction with window)

There are update of dde-kwin but still not released yet. It will be released after the QA peroid(should be done in today or tomorrow).

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
