### ISSUE TITLE
Impossible to Login when Login without password active

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#891]
## Describe the bug
**Enter** button doesn't work when **Login without password** option is active.

## To Reproduce
1. Settings / Accounts - Login without password
2. Suspend or Lock or Log out
3. Attempt to Login back to system - can’t do absolutely nothing except hard reset:
    1) Login button is completely inactive, no matter what you do
    2) Shutdown / Reset options also do nothing in this screen

## Expected behavior
Would very much like for all Login / Shutdown / Reset buttons to work as they should when **Login without password** enabled. 

## Enviroments:
OS: Manjaro 18.0.2 Illyria
Kernel: x86_64 Linux 4.19.20-1-MANJARO
Shell: bash 5.0.0
DE: Deepin 15.9
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
bits: 64
compiler: gcc
v: 8.2.1
tk: Qt 5.12.0
dm: LightDM

### Distro & Version
Manjaro Deepin 18.0.2

### Additional context
Manjaro Deepin only, on all of my real test machines & VM.
Deepin doesn't have this bug.

**Comment by keybreak** [comment]
@electricface 
Maybe this is also connected to https://github.com/linuxdeepin/developer-center/issues/893 and autologin problems?

**Comment by antechdesigns** [comment]
Same on arch for like 3 months....

**Comment by aeropatron** [comment]
I am using manjaro deepin, and I still have this annoying bug, please fixed!
Not nice need to hardware reset my computer every time my session locks, by the way I never did not selected locks after screen is off option...

**Comment by cheese** [comment]
I met a similar problem on Fedora when creating the DDE LiveISO. A user was created with no password and autologin. The user can login session at boot. But if the screen is locked, the user cannot resume from deepin-lock since it does not acept empty password.

**Comment by electricface** [comment]
The passwordless login feature is not working properly under arch linux because the pam configuration file is missing a line.
```
auth    sufficient      pam_succeed_if.so user ingroup nopasswdlogin
```

**Comment by cheese** [comment]
> The passwordless login feature is not working properly under arch linux because the pam configuration file is missing a line.
> 
> ```
> auth    sufficient      pam_succeed_if.so user ingroup nopasswdlogin
> ```

Same on Fedora, adding this line to `deepin-auth` pam rule does not help.

**Comment by RailRanger** [comment]
I am experiencing this issue on Manjaro Feeling, hopefully this gets fixed.

**Comment by keybreak** [comment]
Here's @aeropatron's Manjaro story:
https://forum.manjaro.org/t/i-can-not-login/94203

-1 Deepin DE user....
Maybe it's about time to fix this :smiley_cat:

**Comment by Kristien68** [comment]
Hi everyone !

I have the same issue, I had to create a new user to be able to use my computer.
Can you tell me how to solve this issue ?
How can I use my usual user account or how can I remove the no password login option ?

Thanks for your help !
Best regards,
Kristien

**Comment by rshanule** [comment]
Can confirm that Arch Deepin also has this bug, except it does not matter whether or not "Login without password" is active. Logging in the first time on boot works fine. But locking and entering your password again to unlock it simply does not work. The password field gives a neat little scanning animation, then clears, and nothing happens. If you click the button manually to unlock it, the text field becomes no longer typable at all.

**Comment by tsic404** [comment]
for supporting nopasswordlogin, deepin add a [patch](https://github.com/martyr-deepin/lightdm/blob/master/debian/patches/add_nopasswdlogin.patch) for lightdm.

**Comment by tsic404** [comment]
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue
