### ISSUE TITLE
Settings open/close animation little buggy

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#892]
## Describe the bug
When opening settings animations is a bit buggy on the right.

## To Reproduce
1. Open / Close Settings

## Expected behavior
I want all animations to be perfectly smooth & beautiful no matter what (perfectionist's hell) ! :)

## Screenshots
At the start of video on opening (noticeable to the right):
https://i.imgur.com/VAg4jyp.mp4

## Enviroments:
OS: Manjaro 18.0.2 Illyria
Kernel: x86_64 Linux 4.19.20-1-MANJARO
Shell: bash 5.0.0
DE: Deepin 15.9
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
bits: 64
compiler: gcc
v: 8.2.1
tk: Qt 5.12.0
dm: LightDM

### Distro & Version
Manjaro Deepin 18.0.2

### Additional context
Happens on Manjaro Deepin 18.0.2 (Tested on 2 real machines & VM) / Deepin 15.9.1 on VM

**Comment by antechdesigns** [comment]
@keybreak 

Its great your keen to report bugs etc....

Is this not a Manjaro problem? 
Bare in mind Manjaro will be behind on some versions of software, waste of time reporting bugs for older versions. Most of these issues will probably be fixed when they release the next ISO. 

All I can suggest is wait for the next manjaro ISO. If you want to report bugs, either install archlinux with the deepin desktop or deepin original, then you have the latest packages ;)

I have an archdeepin iso with installer on sourceforge, if your interested?

Thanks ;)

**Comment by keybreak** [comment]
Yeah i know about your Arch .iso man, thx & respect for your work!
I'll probably try it later, but there are few specific reasons why i choose Manjaro now :)

And i'm really looking forward to make both Deepin and Manjaro / Arch better.

> Is this not a Manjaro problem?

Doubt it, please note that **Additional content** section says this bug is reproduceable in Deepin 15.9.1 on VM, so)

**Comment by oberon-manjaro** [comment]
Manjaro uses the same package versions,  actually same packages as Archlinux. Being a rolling release it makes no difference if you wait for a new ISO or install an old one and update the install.

**Comment by antechdesigns** [comment]
Sorry @keybreak @oberon-manjaro 
I just thought you guys held back some updates!?

**Comment by felixonmars** [comment]
I can always reproduce this. @zccrs

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
