### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【发散测试】【DDE】deepin ID应用程序左上角及任务栏图标展示不正确

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/developer-center#8952]
### SUMMARY | 问题概要

必现问题

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240607
```

### PRE-REQUIREMENT | 预置条件

点击deepin ID模块

### STEPS TO REPRODUCE | 复现步骤

观察弹出的对话框及任务栏上的图标展示效果

### OBSERVED RESULT | 观察到的结果

图标展示不正确

![截图_选择区域_20240611093739](https://github.com/linuxdeepin/developer-center/assets/62528742/244e42b9-1cc5-4e31-9273-80b0a83da832)

### EXPECTED RESULT | 期望的结果

图标展示与设计图保持一致

![截图_选择区域_20240611132119(1)](https://github.com/linuxdeepin/developer-center/assets/62528742/a5ed5eba-ba28-4bc6-9839-d54ef6cb74ac)

**Comment by babyfengfjx** [comment]
@mhduiy  请优先分析。

**Comment by xuqi27837288** [comment]
请按预期结果中图标样式优化修改,谢谢~

**Comment by kegechen** [comment]
图标没问题，只是deepinid-client 切换到 Qt6 之后用到了 Qtsvg 渲染图标，对svg渲染出问题了
简单处理可以将图标转换成 png 或者 dci 格式

**Comment by xuqi27837288** [comment]
【验证环境】：v23 RC2镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240613
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.25-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
