### ISSUE TITLE
ref_path歧义导致代码跳转显示问题

### ISSUE THREAD

**Issue by feng9797** [linuxdeepin/developer-center#8959]
### SUMMARY | 问题概要

https://github.com/feng9797/0530
我这个仓库当前现状，分支 main  有 dev/dev 目录，新建tag main/dev 后，当前页面无法打开分支 main 下的 dev 文件夹，会跳转至tag main/dev

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
windows 10
21H2
浏览器访问与系统无关
```

### STEPS TO REPRODUCE | 复现步骤

仓库存在分支 main  有 dev/dev 目录
新建tag main/dev 
页面点击打开分支 main 下的 dev 文件夹

### OBSERVED RESULT | 观察到的结果

跳转至tag main/dev

### EXPECTED RESULT | 期望的结果

正常分支 main 下的 dev 文件夹

**Comment by BLumia** [comment]
你的仓库和 deepin 有啥关系？或者说你是反馈某个特定应用加载你仓库的时候的问题？是的话，哪个应用？
