### ISSUE TITLE
安装器 deepin-installer 6.0.56

### ISSUE THREAD

**Issue by ArchieMeng** [linuxdeepin/developer-center#8961]
### package information | 软件包信息

deepin-installer 6.0.56

### Package repository address | 软件包仓库地址

https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20240611/deepin-23-beige-rc2-amd64-20240611-112919.iso

### changelog | 更新信息

- 试用模式键盘配置 （修改/etc/default/keyboard文件，而非控制中心的那个）
- 修复单独使用deepin-installer-first-boot时，没有配置文件的Bug

### test suggestion | 测试建议

测试试用模式键盘设置和检查安装后配置创建用户界面的情况。
键盘设置有条件可以用真的非标准US布局的其他类型键盘来测试。

### Sphere of influence | 影响范围

试用模式和安装后配置

### ADDITIONAL INFORMATION | 额外补充

无

**Comment by babyfengfjx** [comment]
@baicailio  请开展回归验证，与研发确认清楚，具体修改的BUG内容，已经相关可能影响范围。

**Comment by ArchieMeng** [comment]
@baicailio 已更新键盘布局设置测试建议，有条件还是弄个不同布局键盘试一试。

**Comment by baicailio** [comment]
验证场景：
1.试用模式安装时选择日语，键盘选择日语，检查创建用户界面键盘和语言，检查控制中心键盘与语言
2.非试用模式安装时选择日语，键盘选择日语，检查创建用户界面键盘和语言，检查控制中心键盘与语言
3.试用模式和非试用模式系统安装成功
4.修复单独使用deepin-installer-first-boot时，没有配置文件的Bug：影响点为创建用户页面，用户的头像显示，创建用户界面头像显示正常
