### ISSUE TITLE
Deepin file manager inconsistencies

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#899]
## Description
**Screenshot 1**
1. Light theme, **root** Deepin file manager's background is grey, unlike usual file manager, i think it should match with full white it looks better matching status panel.
2. **Root** Deepin file manager still have RMB - **Open in new window as admin**, should be hidden, since it can't do nothing anyway and misleading.
3. ~~Light theme, **root** Deepin file manager's search & filter icon (when filter panel was opened) are invisible (most likely white icon on white background, as in dark theme)~~

**Screenshot 2**
1. Light theme, Deepin file manager's search & filter icon hover state should be white on blue background, following design language of other buttons :)

**Screenshot 3**
1. This is applicable only for Arch / Manjaro Deepin file manager about page, which says version 1.8.2 but actual package is **deepin-file-manager 1:4.7.5-1**, that's really confusing :)

**Screenshot 4**
Now that's probably personal and only applies to Deepin file manager, but it's only thing that still holds me from subconciously to not use dark theme yet.
Please note that left is original and right is quick raw Photoshop sketch, so i might loose some perspective on legibility.
I was just following light theme's sense of depth and common sense, which is in my opinion as a designer myself is **PERFECT**!
1. Left panel should be darker, i used color of current statusbar
2. Path of the top bar should match left panel color (maybe slightly lighter than i used, to compensate human eyesight tricking it to percieve as darker)
3. Statusbar should be borderless and match background color

## Screenshots
**Screenshot 1**
![screenshot 1](https://i.imgur.com/vu4UX46.png)

**Screenshot 2**
![screenshot 2](https://i.imgur.com/8iRtEz3.png)

**Screenshot 3**
![screenshot 3](https://i.imgur.com/jhDrISg.png)

**Screenshot 4**
![screenshot 4](https://i.imgur.com/EaN97Nh.png)

## Enviroments:
OS: Manjaro 18.0.2 Illyria
Kernel: x86_64 Linux 4.19.20-1-MANJARO
Shell: bash 5.0.0
DE: Deepin 15.9
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
bits: 64
compiler: gcc
v: 8.2.1
tk: Qt 5.12.0
dm: LightDM

### Distro & Version
Manjaro Deepin 18.0.2

### Related package version
deepin-file-manager 1:4.7.5-1

### Additional context
All of the above is basically on all Deepin variants available right now.
Tested on Manjaro Deepin 18.0.2 both of my real test-machines & VM and Linux Deepin 15.9.1 on VM.

**Comment by aiamuzz** [comment]
@keybreak ...

on the point 1 ... never noticed but isn't a some dissimilarities in the GUI good to help distinguish between a root window and a normal window ?

**Comment by keybreak** [comment]
I don't know, for me personally muted b/w aestetics of accents is pretty noticeable difference already, doesn't have to be background also, besides dark theme backgrounds are same for usual & root file manager :)

**Comment by keybreak** [comment]
Updated with **Screenshot 4**, i think it'd improve dark theme a lot :)

**Comment by BLumia** [comment]
> *. Light theme, **root** Deepin file manager's background is grey, unlike usual file manager, i think it should match with full white it looks better matching status panel.

Yep it's designed to be like this. cc @shule1987 .

> *. Light theme, Deepin file manager's search & filter icon hover state should be white on blue background, following design language of other buttons :)

Yes this is a bug, will look into it later.

> *. This is applicable only for Arch / Manjaro Deepin file manager about page, which says version 1.8.2 but actual package is **deepin-file-manager 1:4.7.5-1**, that's really confusing :)

Will look into it later. btw, I'm not quite familiar with Manjaro, did Manjaro got an issue tracking board or something for packages inside their official repo since not all bug caused by upstream and it can be easier to check if the issue caused by the upstream code or not?

> I was just following light theme's sense of depth and common sense, which is in my opinion as a designer myself is **PERFECT**!

For the UI design thing, maybe different designer have different taste. The designer provide a design reference sheet and we implement it as-is, so maybe you need to persuade the designer so the UI change can happens.

@hualet @shule1987 maybe we should public the UI design guidelines online then everyone can take a look at it and can discuss it when needed?

btw, feel free to open multiple issue for different problem, that can make issue tracking much easier.

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/41640/

Should fix 1-3.

About 2-1, cc @shule1987 .

**Comment by keybreak** [comment]
> btw, feel free to open multiple issue for different problem, that can make issue tracking much easier.

Ok, i will :) Just thought those are pretty close-related and minor, sorry)

> btw, I'm not quite familiar with Manjaro, did Manjaro got an issue tracking board or something for packages inside their official repo since not all bug caused by upstream and it can be easier to check if the issue caused by the upstream code or not?

If even you don't know, then i also don't)
Just started Linux journey couple of months before)

As far as i understand it, they don't have upstream, and their process is basically:
https://wiki.manjaro.org/index.php?title=Manjaro:_A_Different_Kind_of_Beast

So they base on Arch repos (week+ for testing packages before releasing on Stable branch)
Therefore shouldn't really be that different from Arch...
But seems that @felixonmars doesn't have some bugs reported by me, which is at the very least weird...

I've wasted more than month on their forum support reporting bugs, to check if it's Manjaro or Deepin:
https://forum.manjaro.org/c/support-for-community-editions
Not much result in there, so i came here.

I guess Manjaro's approach is just repacking Arch / de, and for the most part not giving a crap about 'their errors', unless it's breaking (though for me this one was really breaking on all of my machines, and they have 0 input. https://github.com/linuxdeepin/developer-center/issues/893)

Maybe you should try to contact someone in Manjaro to make it work better?
Basically my idea of how it should work: latest vanilla Deepin DE with all it's features, programs and up to date (and tweak **only** things that absolutely should be tweaked, like https://github.com/linuxdeepin/developer-center/issues/901 or https://github.com/linuxdeepin/developer-center/issues/903), based on all the Manjaro Kernel / Hardware goodies :)

I've met a lot of enthusiastic people in their forums, who would like to use it with Deepin DE and help make it better, they maybe just less enthusiastic / experienced than me to getting that far, and Manjaro doesn't necessarily help them in solving DE issues.

btw, i would absolutely use Linux Deepin itself, since i very much agree with you on **don't break what's working paradigm**, but there are few specific needs that i have and basically which force me to use Manjaro for this exclusive features:
1. Kernel management (i need latest Kernels for some really new hardware like DELL Precision 7730 with i9 and Nvidia Quadro P5200) + preferably RT kernels, for music.
2. Driver management and ability to easily install latest nvidia proprietary (for this machine i need at least v415 and even than i still reported few bugs to nvidia, because it's too untested yet)
3. Cutting edge software and AUR (not really a thing, i can live without it, but still plus)

For pure Arch i wasn't ready before, but i guess should try now, at least to compare of Deepin DE on Arch / Manjaro before reporting stuff.

> For the UI design thing, maybe different designer have different taste.

Sure) He'll see this now, maybe will agree)

> maybe we should public the UI design guidelines online then everyone can take a look at it and can discuss it when needed?

Generally, in my experience it's a bad idea...
It can lead to big mess and unwanted changes most times not for the better, for users who love Deepin already :)

Since rest of design is really perfect and i proposed just a minor inconsistencies (more subconcious, as design closely follows depth feel already, except dark theme just a little off)

This is by far best OS Design i have seen ever, so you did really great @shule1987 !)

**Comment by felixonmars** [comment]
@keybreak Arch ships mostly vanilla DDE, and manjaro actually customized the packages a bit. For example the customized packages deepin-desktop-schemas-manjaro, deepin-iconthemes-manjaro, deepin-artwork-themes-manjaro are not present on Arch.

In the past customizing deepin-desktop-schemas led to some problems that are not present on either Deepin or Arch. I am not sure how it's handled nowadays. @oberon-manjaro may have a better idea here.

**Comment by keybreak** [comment]
Yeah, i've noticed that vanilla wallpapers and icons is not up to date in Manjaro, compared with Linux Deepin, which is bad.

I think custom stuff for Manjaro should be updated and repacked with their additional stuff following Arch updates.

> In the past customizing deepin-desktop-schemas led to some problems that are not present on either Deepin or Arch.

Looks like pretty much same, situation now, i suspect this bug https://github.com/linuxdeepin/developer-center/issues/890 for example could be caused by repacked **deepin-desktop-schemas**, since it have stuff like dde-daemon, dde-workspace, deepin-metacity, deepin-mutter

**Comment by keybreak** [comment]
@felixonmars hmm...actually i went to install https://sourceforge.net/projects/archdeepin/ and it seems to use all your latest Arch packages.
Seems you don't have up to date icons either, check for example Linux Deepin have red .db icons for a lot of time, and Arch / Manjaro Deepin don't.

**Comment by felixonmars** [comment]
I don't think I did anything to the icon theme when packaging, as we always use latest vanilla versions. The screensavers will be packaged soon.

**Comment by keybreak** [comment]
Confirmed **1-3** is fixed in all Deepin editions! :+1: 

@BLumia @felixonmars 
What about 1-2 and 3?

As i've stated in few other threads, 3 really worries me, not for the aesthetic / incosistency, but more from the perspective that it's clearly means that Arch / Manjaro version of **dde-file-manager** and **depin-editor** for example, are not indentical to vanilla Deepin which can potentially lead to some more hardcore bugs for Arch / [Manjaro](https://github.com/linuxdeepin/developer-center/issues/898) only.

@shule1987 
Please comment on:
1-1
2
4

**Comment by BLumia** [comment]
> This is applicable only for Arch / Manjaro Deepin file manager about page, which says version 1.8.2 but actual package is deepin-file-manager 1:4.7.5-1

We already using the `QMAKE_VERSION` as the displayed version string (related source code:[main.cpp#L113](https://github.com/linuxdeepin/dde-file-manager/blob/4.7.7.2/dde-file-manager/main.cpp#L113), [dialogmanager.cpp#L703](https://github.com/linuxdeepin/dde-file-manager/blob/4.7.7.2/dde-file-manager-lib/dialogs/dialogmanager.cpp#L703)), maybe it should be a packaging issue? @felixonmars ([PKGBUILD#n34](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/deepin-file-manager#n34))

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
