### ISSUE TITLE
【deepin_V23_Release】【一般】【正常】【RC2镜像测试】【DDE】成功加入内测后，通知中心高概率出现不通知“testing Channel”安装成功的消息

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#8996]
### SUMMARY | 问题概要

成功加入内测后，通知中心高概率出现不通知“testing Channel”安装成功的消息

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240612/deepin-23-beige-rc2-amd64-20240612-151650.iso
```

### PRE-REQUIREMENT | 预置条件

1.安装上述最新镜像

### STEPS TO REPRODUCE | 复现步骤

1.打开控制中心-更新-更新设置-内测通道开关
2.跳转到浏览器，登录论坛账号同意相关协议
3.收到提示成功加入内测
4.观察通知中心是否有“成功 安装testing Channel”的消息

### OBSERVED RESULT | 观察到的结果

1.成功加入内测后，通知中心高概率出现不通知“testing Channel”安装成功的消息
![截图_org deepin browser_20240612164755](https://github.com/linuxdeepin/developer-center/assets/96415804/8adcf8fa-ac98-4866-9b8f-4c3d347c1b79)

### EXPECTED RESULT | 期望的结果

1.每次成功加入内测后，都能弹出通知“testing Channel”安装成功的消息，退出内测时，也会弹出“testing Channel”卸载成功

**Comment by babyfengfjx** [comment]
@kegechen  有余力可以安排优化。

**Comment by vivianxf** [comment]
验证镜像：https://cdimage.uniontech.com/community/releases/23/amd64/
验证步骤：提单的步骤
验证现象：最新版本下打开内测，每次都会有提醒，后续复现在pms跟踪
验证结果：通过
