### ISSUE TITLE
default wallpaper shows up during login. (Archlinux) 

### ISSUE THREAD

**Issue by antechdesigns** [linuxdeepin/developer-center#902]
## Describe the bug

No matter what wallpaper I choose I still get the default wallpaper showing up at boot or login,logout.

## To Reproduce
Choose any wallpaper reboot, login, logout and you will see the default wallpaper pop up until your logged in.

## Expected behavior
Able to see the wallpaper I choose, not the default (below)

## Screenshots
![deepinscreenshot_deepin-image-viewer_20190214150437](https://user-images.githubusercontent.com/29888048/52795627-147e5100-306a-11e9-921d-06a4e5a7f44a.png)

### Distro & Version
arch deepin latest

### Additional context
I have tried to find the problem myself, but I can not figure it out.

My custom wallpapers I put in here so that they show up in the wallpaper chooser: .config/deepin/dde-daemon/appearance/custom-wallpapers

This directory:  /usr/share/backgrounds/deepin has desktop.jpg which is linked to /usr/share/wallpapers/deepin/hummingbird.jpg

However the hummingbird.jpg never shows up

Thanks

**Comment by guanghwang** [comment]
The lock screen has its own setting. When you change the wallpaper, you may choose to change both.

**Comment by guanghwang** [comment]
Here is the screenshot on Deepin . ![image](https://user-images.githubusercontent.com/12839553/52805988-decf6d00-3055-11e9-9d57-100c96381730.png)

**Comment by antechdesigns** [comment]
@guanghwang 

Yes the lock screen works, its just when its logging in, it shows the default wallpaper, for about 2 secs

**Comment by antechdesigns** [comment]
Only happens if you choose a custom wallpaper found in: .config/deepin/dde-daemon/appearance/custom-wallpapers

**Comment by keybreak** [comment]
@BLumia @hualet 
Here's demo of this bug.

Problem is in the transition after login.

1. Set new wallpaper
2. Set it for locksreen too
3. Try to logout and login
4. Right after you login, transition goes like this:
lock-screen wallpaper -> **some cached default one** -> desktop wallpaper.

Problem is in the cached default one, because it doesn't change no matter what, reboot set another one etc.

Video demo (transition bug shown on 00:18):
https://i.imgur.com/JaBWma4.mp4

**Comment by keybreak** [comment]
@BLumia 
Please reopen this and solve, so it wouldn't get lost.

**Comment by BLumia** [comment]
> @BLumia
> Please reopen this and solve, so it wouldn't get lost.

If I remember correctly there was some fix related to this issue (not maintained by me so not quite sure about which commit did the fix), did you still have this issue in the most recent version? Thanks.

**Comment by keybreak** [comment]
Yes, it still exists on latest Arch (today's updates)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
