### ISSUE TITLE
UOS AI V1.3.0 集成请求

### ISSUE THREAD

**Issue by toberyan** [linuxdeepin/developer-center#9023]
### package information | 软件包信息

| 包名 | 版本|
| --------- | --------- |
| uos ai | 1.3.0 |
| deepin-ai-daemon | 1.1.0.19 |
| deepin-modelhub | 0.0.10 |
| deepin-systemassistant-knowledge | 0.0.2 |
| dde-grand-search | 5.5.0 |
| BAAI_bge-large-zh-v1.5 | 0.0.2 |
| uos-ai-rag | 1.0.1 |

### Package repository address | 软件包仓库地址

deb  [trusted=yes] https://aptly.uniontech.com/pkg/beige-v2/release-candidate/44CQVU9TIEFJ44CR5omT5YyF5rWL6K-V5Li76aKYLTA1MDcyMDI0LTA1LTA3IDIwOjI0OjQ4/  unstable main

### changelog | 更新信息

为应用提供向量化数据能力，安装后，可使用UOS AI玩机助手、个人知识助手，全局搜索AI智能搜索等AI能力。
1、通用大模型接入适配：支持OpenAI格式的API接口。
2、Deepin玩机助手：支持通过智能助手对Deepin系统FAQ问题进行回复；
3、个人知识助手：支持自定义AI知识库，并基于自定义数据，进行AI问答和内容生成。

### test suggestion | 测试建议

1、模型运行时的资源占用
2、添加个人知识库看是否会导致机器卡顿
3、uos-ai添加自定义模型功能

### Sphere of influence | 影响范围

无

### ADDITIONAL INFORMATION | 额外补充

无

**Comment by luodeepin** [comment]
测试通过
1. 新增一个严重问题在点击添加知识库时，偶现整个桌面卡死或uos ai 卡死的情况。此问题与机型和运行时系统CPU和内存使用环境，且是低概率偶现。先做通过处理
2. 发散测试其他功能正常
