### ISSUE TITLE
[Arch Linux] Programs menu Uninstall options doesn't work

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#903]
## Describe the bug
Uninstall option in programs menu doesn't work, throwing an error.

## To Reproduce
1. Open menu
2. Try to remove any program with right mouse click

## Expected behavior
Should either have pacman hook, or be removed / hidden in Arch / Manjaro.

## Screenshots
https://i.imgur.com/tznZjn6.mp4

## Enviroments:
OS: Manjaro 18.0.2 Illyria
Kernel: x86_64 Linux 4.19.20-1-MANJARO
Shell: bash 5.0.0
DE: Deepin 15.9
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
bits: 64
compiler: gcc
v: 8.2.1
tk: Qt 5.12.0
dm: LightDM

### Distro & Version
Manjaro Deepin 18.0.2

**Comment by BLumia** [comment]
By saying "menun", did you means the launcher(`dde-launcher`)?

The "Uninstall" option only works under Deepin (distro), and this option will be hide in next update :)

https://cr.deepin.io/#/c/dde/dde-launcher/+/41579/

**Comment by keybreak** [comment]
> By saying "menu", did you means the launcher(`dde-launcher`)?

Yes, most likely (this thing where you launch categorised programs, like Start in windows), i was unsure package name or how to reference it correctly, now i know thx)

**Comment by felixonmars** [comment]
The Uninstall menu item should be hidden in Arch Linux since 4.6.4-2. Maybe Manjaro needs some time to sync the change.

**Comment by keybreak** [comment]
Confirm, Manjaro synced today - solved with deepin-launcher 4.6.4-2

Closing issue
