### ISSUE TITLE
【deepin_V23_Release】【严重】【立即】【集成测试】【系统】【网络】连接网络认证的 网络时，无法进入认证页面，无法访问互联网

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#9030]
### SUMMARY | 问题概要

关联集成：https://github.com/linuxdeepin/developer-center/issues/8993

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
networkmanager-qt	5.103.0-1deepin2
```

### STEPS TO REPRODUCE | 复现步骤

1. 连接有线网络 ，访问互联网
2. 连接需要输入密码的无法网络访问互联网
3. 连接需要进行网络认证的 uniontech-m 网络 ,访问认证页面，访问互联网

### OBSERVED RESULT | 观察到的结果

3. 无法进入认证页面，无法访问互联网
![8993](https://github.com/linuxdeepin/developer-center/assets/96416089/e9b1c3ec-9a25-4e78-b754-2ae2b44ded30)

### EXPECTED RESULT | 期望的结果

3. 正常认证和访问互联网

**Comment by babyfengfjx** [comment]
@fly602  可以优先分析处理。

**Comment by luodeepin** [comment]
验证通过
libkf5networkmanagerqt6 5.103.0-1deepin2
![截图_选择区域_20240617153056](https://github.com/linuxdeepin/developer-center/assets/96416089/e25dd521-5da4-4103-8834-6d0632307e5c)
