### ISSUE TITLE
Programs menu animation in compact mode

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#904]
## Describe the bug
1. Programs menu animation (in compact mode) on first launch have appearing outline, and only then after some time menu kicks in.
2. On next launch it works ok, but in my opinion should also have some fade-in | fade-out animation, just as full menu shown at 0:09 (but obviously faster, since compact menu is smaller)

## Expected behavior
Nice & Smooth animations! :)

## Screenshots
https://i.imgur.com/IV6U2HP.mp4

## Enviroments:
OS: Manjaro 18.0.2 Illyria
Kernel: x86_64 Linux 4.19.20-1-MANJARO
Shell: bash 5.0.0
DE: Deepin 15.9
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
bits: 64
compiler: gcc
v: 8.2.1
tk: Qt 5.12.0
dm: LightDM

### Distro & Version
Manjaro Deepin 18.0.2

### Additional context
Happens on both of my real test-machines and in VM on Manjaro Deepin + on Linux Deepin on VM.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
