### ISSUE TITLE
[软件包投递] bat - A cat(1) clone with wings.

### ISSUE THREAD

**Issue by lolimay** [linuxdeepin/developer-center#905]
【软件包名称】bat
【描述】A cat(1) clone with wings.
【主页】https://github.com/sharkdp/bat
【下载地址】https://github.com/sharkdp/bat/releases
【投递说明】现代化的 cat，自动高亮令人非常舒适。作者已经打好deb 包了，希望官方能够添加进源中。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
