### ISSUE TITLE
File Manager 处理网络位置极其卡顿

### ISSUE THREAD

**Issue by CareF** [linuxdeepin/developer-center#906]
## 缺陷描述
sshfs, cifs 等方式挂载的网络地址, 用 deepin file manager 打开时, 滚轮, 选中等许多操作都十分卡顿. 疑似没有做好异步. 

## 复现步骤
N/A

## 期望行为
网络地址不应该使 UI 本身卡主. 加载过程中应该有加载的提示信息. 

### 发行版以及版本
Arch Linux

### 相关的软件包版本
dde-file-manager v1.8.2

**Comment by CareF** [comment]
@BLumia ?

**Comment by BLumia** [comment]
:joy: 太忙了（（（（（（
手头的搞完了再看

**Comment by BLumia** [comment]
合并到 linuxdeepin/internal-discussion#551 处理吧，应该是一回事。

**Comment by CareF** [comment]
辛苦了！
