### ISSUE TITLE
【deepin_V23_Release】【一般】【有空】【内测反馈】【DDE】【任务栏】clash 图标显示极小

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#9070]
### SUMMARY | 问题概要

![image](https://github.com/linuxdeepin/developer-center/assets/96416089/070eaa5f-a489-4116-9264-2d929dcbe079)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240607/deepin-23-beige-rc2-amd64-20240607-182059.iso
```

### PRE-REQUIREMENT | 预置条件

1. 安装clash

### STEPS TO REPRODUCE | 复现步骤

1. 打开clash 查看任务栏上图标显示

### OBSERVED RESULT | 观察到的结果

clash 图标显示极小
![截图_选择区域_20240617163921](https://github.com/linuxdeepin/developer-center/assets/96416089/190afde5-bf26-44de-a242-60036fa6e904)

![po](https://github.com/linuxdeepin/developer-center/assets/96416089/117490f0-e69c-465b-b905-989217cbd32d)

### EXPECTED RESULT | 期望的结果

clash 图标显示大小和其他图标保持一致

**Comment by babyfengfjx** [comment]
@kegechen  这个应该都是图标异常一类的问题，之前可能也有类似问题，到时修复可以一并转回验证。

**Comment by zsien** [comment]
这次是 qml 的 DciIcon 没有处理 png 缩放了

**Comment by kegechen** [comment]
```
 /usr/share/icons/hicolor/128x128/apps/clash-verge.png
 /usr/share/icons/hicolor/256x256@2/apps/clash-verge.png
 /usr/share/icons/hicolor/32x32/apps/clash-verge.png
```
应用提供的图标只有 32 128 256 这些大小， dock 上图标是 64 这时获取到的图标是 32 的大小。
对于 32 的图标大小有两种处理，要么缩放填充会导致 **模糊**， 要么显示原始大小会导致 **图标显小**

![image](https://github.com/linuxdeepin/developer-center/assets/23466548/47e2dd1e-83f6-472d-af36-8a9b66cf0278)

**Comment by luodeepin** [comment]
转PMS跟踪：https://pms.uniontech.com/bug-view-271309.html
