### ISSUE TITLE
统信有墨打印驱动依赖包集成申请

### ISSUE THREAD

**Issue by winexw** [linuxdeepin/developer-center#9077]
### package information | 软件包信息

# package information | 软件包信息

| 包名 | 版本号 |
| :--: | :--: |
| bisheng-engine | 2.0.13-1 |
| bisheng-engine-i386 | 2.0.13-1 |
| bisheng-sim-box64 | 2.0.3-4 |
| bisheng-sim-box86 | 2.0.3-3 |
| com.deepin-wine-runtime.deepin | 1.1deepin4 |
| deepin-amd64-runtime | 0.1.8 |
| deepin-wine-runtime | 0.1.9 |
| bisheng-filter | 2.0.12-1 |

### Package repository address | 软件包仓库地址

# Package repository address | 软件包仓库地址

```
deb  [trusted=yes] https://aptly.uniontech.com/pkg/nonfree-beige-v2/release-candidate/44CQ5q-V5piH546v5aKD44CRYmlzaGVuZ18wNjE3MjAyNC0wNi0xNyAxODoxMToyMQ/  unstable non-free
```

### changelog | 更新信息

添加有墨环境依赖包

### test suggestion | 测试建议

* 1、x86版本测试有墨wine方案驱动能够正常安装  [有墨wine方案驱动](https://aptly.uniontech.com/pkg/nonfree-eagle-1071/release-candidate/44CQ6amx5Yqo562-5ZCN44CR5rWL6K-V5Li76aKYMjAyNC0wNi0xNyAxNzowMDoyOA/pool/non-free/p/printer-driver-bisheng-canon-ip1800-series/printer-driver-bisheng-canon-ip1800-series_2.0.5_all.deb)
* 2、ARM架构测试有墨wine方案驱动和有墨模拟器方案驱动能够正常安装  [有墨wine方案驱动](https://aptly.uniontech.com/pkg/nonfree-eagle-1071/release-candidate/44CQ6amx5Yqo562-5ZCN44CR5rWL6K-V5Li76aKYMjAyNC0wNi0xNyAxNzowMDoyOA/pool/non-free/p/printer-driver-bisheng-canon-ip1800-series/printer-driver-bisheng-canon-ip1800-series_2.0.5_all.deb)   [有墨模拟器](https://aptly.uniontech.com/pkg/nonfree-eagle-1071/release-candidate/44CQ6amx5Yqo562-5ZCN44CR5rWL6K-V5Li76aKYMjAyNC0wNi0xNyAxNzowMDoyOA/pool/non-free/p/pantum/pantum_1.1.106-2deepin0_arm64.deb)

### Sphere of influence | 影响范围

验证集成包是否有冲突

**Comment by babyfengfjx** [comment]
@luodeepin  请开展集成验证，先弄清楚整个项目的来龙去脉，此集成说是依赖包，那最终这个项目如何使用，使用场景有哪些需要弄清楚。

**Comment by luodeepin** [comment]
测试通过
1. 分别在X86和ARM镜像上测试安装成功
2. 与专业版开发和测试核对当前主要测试对应包环境安装
3. 此包没有图形环境
