### ISSUE TITLE
Cannot increase desktoo zoom factor over three Super+= key combination presses

### ISSUE THREAD

**Issue by pavarinb** [linuxdeepin/developer-center#909]
## Describe the bug
As I’n visually impaired, I’d like to increase the desktop zoom factor over three Super+= key combination presses, but the current deepin system won’t allow me to zoom in any further.

## To Reproduce
1. Press Super + = three times.
2. Press Super + = again.
3. Nothing happened. The system would refuse to zoom in any further.

## Expected behavior
The desktop zoom factor should continue to increase.

### Distro & Version
Linux Deepin 15.9

**Comment by AndBrilliant** [comment]
Anyone fix this, its a useless desktop for me without this one single feature

**Comment by tsic404** [comment]
the zoom factor has reached the maximum, this still not big enough?

**Comment by tsic404** [comment]
This issue will close.
