### ISSUE TITLE
[archlinux]无法编辑网络

### ISSUE THREAD

**Issue by kirigayakazushin** [linuxdeepin/developer-center#91]
点右箭头,就返回了.

**Comment by sbwtw** [comment]
是说崩溃了？我这里没有问题

**Comment by fasheng** [comment]
这个是因为dde-daemon缺少gnome-keyring依赖导致, 安装后测试正常
@felixonmars

**Comment by felixonmars** [comment]
是需要 gnome-keyring，还是仅仅 libgnome-keyring？后者可以使用其他 keyring 后端。

**Comment by fasheng** [comment]
需要 gnome-keyring，因为用到了DBus service

**Comment by felixonmars** [comment]
libgnome-keyring 可以用其它兼容同一个 freedesktop secrets dbus service 的后端，不一定要用 gnome-keyring 呀……

**Comment by fasheng** [comment]
文件`/usr/share/dbus-1/services/org.freedesktop.secrets.service`存在于gnome-keyring包里...

**Comment by felixonmars** [comment]
其他 implementation 可以在运行中声明这个接口的，不需要有这个文件 :)

**Comment by fasheng** [comment]
可能是被名字混淆了 ;)
我了解的情况是这样, gnome-keyring 和 libgnome-keyring 不一样, 仓库也是分开的, libgnome-keyring 大概两年前被 libsecret 替代, 基本已经弃用, 而 gnome-keying 是 libsecret 的最新实现, 所以肯定是要依赖 gnome-keyring 这个包
https://github.com/GNOME/libgnome-keyring/commit/6a5adea4aec931708d2b16decff7405fb0ae67c3

**Comment by fasheng** [comment]
当然有些程序会只依赖 libsecret，但它只是一个抽象接口，如果系统中没有具体实现进程如 gnome-keyring-daemon 也是不行的。

**Comment by felixonmars** [comment]
我知道，主要是考虑到这个 DBus 接口有其他的实现，如
https://community.kde.org/KDE_Utils/ksecretsservice

**Comment by fasheng** [comment]
如果是考虑gnome-keyring与ksecrets的冲突问题，那应该没有好办法吧，毕竟Arch上libsecrets包自己没有做相关处理



2016年5月23日 14:06, 14:06，在 Felix Yan <notifications@github.com> 已写:

**Comment by felixonmars** [comment]
嗯，暂时只能这样了。我稍后加上这个依赖。
