### ISSUE TITLE
No GUI to increase cursor size

### ISSUE THREAD

**Issue by pavarinb** [linuxdeepin/developer-center#910]
## Describe the bug

As I’m visually impaired, I’d like to increase the cursor size, but I cannot find any settings in fhe Control Center that would allow me to do so.

## To Reproduce

1. Go to Control Center.
2. You won’t find any settings that allow you to change the cursor size.

## Expected behavior

There should be a setting that allows one to increase the cursor size.

### Distro & Version

Linux Deepin 15.9

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
