### ISSUE TITLE
[蓝牙增强] 支持对需要配对码的设备的配对支持

### ISSUE THREAD

**Issue by lolimay** [linuxdeepin/developer-center#911]
## 需求描述
目前 deepin 控制中心的蓝牙管理器不支持需要配对码的设备(如蓝牙键盘)，因此无法直接配对成功并使用。
暂时的解决方案是依靠第三方蓝牙管理器 `blueman` 或 `bluetoothctl` 进行配对使用。
````bash
sudo service bluetooth start # 打开系统蓝牙
bluetoothctl # 进入bluetoothctl
power on
agent on
default-agent
scan on # 扫描其它蓝牙设备
pair YourDeviceMacAddress # 与设备配对（请把 YourDeviceMacAddress 换成你蓝牙键盘的 MAC 地址）
# 在键盘上输出配对码后回车 (!!! deepin 原生蓝牙管理器暂不支持这一步)
trust YourDeviceMacAddress # 信任该设备
connect YourDeviceMacAddress # 连接该设备
````
## 预期表现
点击配对时，若当前设备需要配对码，则提示用户在键盘上输入配对码后，再进行下一步。

**Comment by listenerri** [comment]
目前应该是支持自动商定配对码的, 如下图:

![20190218152023](https://user-images.githubusercontent.com/7995379/52934273-
e6ae4a80-3390-11e9-9766-af7582d479c3.png)

这种方式不能满足所有需求吗?

**Comment by lolimay** [comment]
抱歉，无法正常查看截图。

**Comment by listenerri** [comment]
> 抱歉，无法正常查看截图。

已更新

**Comment by electricface** [comment]
确实不完整，有待改进。

**Comment by lolimay** [comment]
控制中心的窗口置顶，录屏软件无法捕捉到，只能手拍，请看视频:

[video.m4v.tar.gz](https://github.com/linuxdeepin/developer-center/files/2874451/video.m4v.tar.gz)

**Comment by lolimay** [comment]
我的意思就是这个，如果有个弹窗就好了:
![image](https://user-images.githubusercontent.com/32427260/52935230-d186eb00-3393-11e9-8aa6-c792c111d02a.png)

实际上 deepin  控制中心的蓝牙管理器，功能还是不是很稳定。比如与 airpods 断开连接之后，需要重新连接，控制中心会提示 `设备不在范围内`。而使用 blueman 则会直接连上。可能判断已配对的蓝牙设备是否在连接范围之内，这块逻辑也有点问题。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
