### ISSUE TITLE
[Feature Request] Mount .ISO in the Deepin File Manager

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#912]
Allow the Deepin File Manager to mount the .ISO images.

The user by right clicking on the .ISO ... will see the option: "Mount". As it occurs in Microsoft Windows.
With the image already mounted ... the "Dismount" option will appear when you right click.

![captura de tela_selecionar area_20190216102400](https://user-images.githubusercontent.com/45263160/52899778-fed96a80-31d4-11e9-9370-60f1bc8a1612.png)

**Comment by keybreak** [comment]
Totally agree!

While there is **Open as - Disk image mounter** which do the job technically...
Separate option for all mounteable type files (.iso .mds .ccd .cue .bwt .cdi .nrg .pdi .b5t .isz) would imporve usability a lot!

And i guess also it would be a good practive to have some configuration file with all those filetypes listed, where you can add formats for this rmb option to show **Mount** (in case some new format will come out, or we missed something)

**Comment by BLumia** [comment]
This is a planned feature, probably will be implemented in the next update. please keep an eye on that.

You can track this feature in this issue: https://github.com/linuxdeepin/internal-discussion/issues/455  :)

**Comment by alexwender1** [comment]
> This is a planned feature, probably will be implemented in the next update(no promise now). please keep an eye on that.
> 
> You can track this feature in this issue: [linuxdeepin/internal-discussion#455](https://github.com/linuxdeepin/internal-discussion/issues/455) :)

Thanks for the guidance. I'll be following...
