### ISSUE TITLE
GTK Theme no minimize icon

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#913]
## Describe the bug
GTK Theme have no minimize icon, only maximize icon. That affects all non-deepin programs.

## To Reproduce
1. Maximize / Minimize any non-deepin program

## Expected behavior
Should have minimize icon, just as deepin programs! :)
Interface must be consistent.

## Screenshots
All programs:
https://i.imgur.com/Z08v4s2.mp4

Deepin programs (how it should be):
https://i.imgur.com/H62dwne.mp4

## Enviroments:
OS: Manjaro 18.0.2 Illyria
Kernel: x86_64 Linux 4.19.20-1-MANJARO
Shell: bash 5.0.0
DE: Deepin 15.9
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
bits: 64
compiler: gcc
v: 8.2.1
tk: Qt 5.12.0
dm: LightDM

### Distro & Version
Manjaro Deepin 18.0.2

### Related package version
deepin-gtk-theme  17.10.10-1

### Additional context
Tested in Manjaro Deepin, Arch Deepin, Linux Deepin.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
