### ISSUE TITLE
Deepin file manager minor glitch

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#914]
## Describe the bug
Pretty often, when you navigate from usual directory to **computer** there is fast, but noticeable jump, caused by briefly appearing vertical / horisontal scrollbars.

## To Reproduce
1. Navigate any folder
2. Go back to Computer, via left panel, back button or back button of your mouse

## Expected behavior
No visible jumps

## Screenshots
https://i.imgur.com/HIpNQ1c.mp4

## Enviroments:
OS: Manjaro 18.0.2 Illyria
Kernel: x86_64 Linux 4.19.20-1-MANJARO
Shell: bash 5.0.0
DE: Deepin 15.9
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
bits: 64
compiler: gcc
v: 8.2.1
tk: Qt 5.12.0
dm: LightDM

### Distro & Version
Manjaro Deepin 18.0.2

### Additional context
Reproducible in Manjaro Deepin, Arch Deepin, Linux Deepin.

That's really minor, and probably even desirable behaviour in terms of performance, so if fixing this will get in any form on the way of performance / stability - just close this bug)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
