### ISSUE TITLE
复制大文件到U盘上出现输入/输出错误

### ISSUE THREAD

**Issue by lolimay** [linuxdeepin/developer-center#915]
## 缺陷描述

复制大文件到U盘上出现输入/输出错误，请看截图。
## 复现步骤

1. 插入 U盘
2. 复制一个超过4G的ISO镜像文件
3.出现输入输出错误
## 期望行为

成功复制文件
## 截图

![image](https://user-images.githubusercontent.com/32427260/52912630-e78ea000-32ee-11e9-87db-777948e8e5b7.png)

### 发行版以及版本

deepin 15.9+1
### 相关的软件包版本

dde-file-manager/panda,now 4.7.5-1 amd64 [已安装]
### 其他内容

复制文件的原始磁盘是 SSD
目标盘是 32G U盘

**Comment by felixonmars** [comment]
U盘的文件系统是否是 FAT32？

**Comment by lolimay** [comment]
![image](https://user-images.githubusercontent.com/32427260/52935560-af419d00-3394-11e9-988f-6392eb3a16e8.png)
文件系统是 NTFS， 如果是 FAT32大于 4G 的文件应该无法复制。(后来使用 `mv` 命令直接复制的)
