### ISSUE TITLE
[Improvement] cannot change size of rows in dde-file-manager

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#916]
If we try to search for something using dde-file-manager and if the pathname is very big, then we can't see the whole path. Also, we can't change the size of the rows to see the pathname.
![deepin-screen-recorder_dde-file-manager_20190217184858](https://user-images.githubusercontent.com/33563064/52913199-f3c22f80-32e5-11e9-9028-8d50eb9d810f.gif)

**Comment by SiamSami** [comment]
Sorry, it's my mistake. We can change the size of the rows.

**Comment by keybreak** [comment]
Not while search in progress
