### ISSUE TITLE
[Arch Linux] Deepin launcher programs change categories on update / install / uninstall

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#917]
## Describe the bug
If you use launcher in compact mode or categories mode, you'll notice that programs all the time mix up categories.

For example Deepin movie can go from Movies to Musc, HexChat can move from Internet to Messengers etc. This can happen to all programs.

As far as i can tell it's getting triggered by any of those actions:
- Update system
- Install programs
- Uninstall programs

## To Reproduce
1. Install VLC, check it's category
2. Install HexChat, check it's category
3. Update system
4. Reboot
Most likely after this something in some categories will change.

## Expected behavior
Programs should never change categories or anything else, unless you specifically tell them by changing .desktop files! :)

## Enviroments:
OS: Manjaro 18.0.2 Illyria
Kernel: x86_64 Linux 4.19.20-1-MANJARO
Shell: bash 5.0.0
DE: Deepin 15.9
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
bits: 64
compiler: gcc
v: 8.2.1
tk: Qt 5.12.0
dm: LightDM

### Distro & Version
Manjaro Deepin 18.0.2

### Related package version
deepin-launcher  4.6.4-1

### Additional context
Happens a lot in Manjaro Deepin on both of my test-machines and VM, also confirmed in Arch Deepin on  VM.
Doesn't happen on Linux Deepin and Fedora Deepin.

I was thinking maybe .desktop files changes after it happens, but doesn't seems so...

Please solve this soon, or people with OSD & paranoid control-freaks won't use Arch / Manjaro Deepin anymore! :yum:

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
