### ISSUE TITLE
Feature Request/Enhancement : Extend recently used app list from the compact launcher to the fullscreen launcher

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#918]
Hi,

@hualet ... @BLumia ... This is a case of missing out a use case ... its a great feature and implemented in one place but missing in another !!!

![image](https://user-images.githubusercontent.com/3283676/52914348-320f1d00-32ed-11e9-9085-4b4e0d0fd6b4.png)

as we can see in the compact launcher the most recently/frequently used apps show up on the launcher list directly ... saving any efforts to search the required apps ... one could directly click on the frequently used apps.

As we all agree its convenient ... i am surprised why this frequently used/recent app list missing from the full screen launcher ?

Could this convenience be extended to the full screen launcher too please ??? It is cumbersome to have to type(search) each time we have to open a frequently used app from the launcher ... this list will help us launch our favorite apps faster and more efficiently !!!

**Comment by keybreak** [comment]
> As we all agree its convenient ...

Not all, i don't )

For example, when i use fullscreen mode, i admire programs to be on expected places, just as in compact i always use categories...

Though maybe an additional option on top left (as icon near category icon) for fullscreen to show recent programs would be cool for some people)

But i personally would vote strongly against making it default :)

Maybe it's a good idea to have someday Settings option to choose between default mode as Recent / Ordered

**Comment by aiamuzz** [comment]
> > As we all agree its convenient ...
> 
> Not all, i don't )
> 
> For example, when i use fullscreen mode, i admire programs to be on expected places, just as in compact i always use categories...
> 
> Though maybe an additional option on top left (as icon near category icon) for fullscreen to show recent programs would be cool for some people)
> 
> But i personally would vote strongly against making it default :)
> 
> Maybe it's a good idea to have someday Settings option to choose between default mode as Recent / Ordered

@keybreak ... thanks for you inputs ... Then i guess a switch(option) to enable/disable 'Recent application list' in both the compact and fullscreen launchers will resolve everyone's needs !!!

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
