### ISSUE TITLE
Feature Request/Enhancement : Right-Click Menu Option in Launcher to switch app categories/custom category ???

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#919]
Hi,

Would it be possible to add an option to switch a particular app's category in the launcher's right-click-menu ?

Currently we have the following options ...

Open
Send to Dock
Send to Desktop
Add to Startup
Uninstall

would be nice to have another option 'Change App Category' ... **with the option to create our own custom categories** ?

**Comment by gokhanyildirimlar** [comment]
Brilliant, I'd love that too.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
