### ISSUE TITLE
go1.6下编译的dde-daemon运行时直接panic

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/developer-center#92]
由于go1.6对go传递至c的指针做了更加严格的检测，gir生成的go绑定代码无法正常运行（不保证其他c代码没有问题），官方给出的临时解决办法是编译前使用下面的环境变量：
```
export GODEBUG=cgocheck=0
```
错误日志：
```
panic: runtime error: cgo argument has Go pointer to Go pointer
goroutine 1 [running]:
panic(0xdf9c00, 0xc82019b840)
        /workspace/local/gocode/gvm/gos/go1.6.2/src/runtime/panic.go:481 +0x3e6
gir/gobject-2%2e0._cgoCheckPointer0(0xc55520, 0xc82019b820, 0xc82019b830, 0x1, 0x1, 0x20)
        ??:0 +0x4d
gir/gobject-2%2e0.(*Object).Connect(0xc82022e010, 0xc820245300, 0x12, 0xcd4740, 0xc82019b810)
        /workspace/code/gocode/src/gir/gobject-2.0/gobject.go:2401 +0x1a7
```
https://groups.google.com/forum/#!searchin/golang-nuts/cgo$20argument$20has$20Go$20pointer$20to$20Go$20pointer/golang-nuts/gnH0nhPf36I/4Shly3gxEwAJ
https://github.com/go-gl/gl/issues/31

@snyh @leaeasy @felixonmars

**Comment by oahong** [comment]
这个有修复的计划吗？

**Comment by snyh** [comment]
Fixed in https://github.com/linuxdeepin/go-gir-generator/commit/f7baf89deb000f5f63b7361a3f79c9cbdef41865
