### ISSUE TITLE
Deepin file manager selection rectangle draw

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#920]
## Describe the bug
Selection rectangle can draw after releasing mouse in Deepin file manager.

## To Reproduce
1. Start select something
2. Try to match rectangle parallel lines as on video below
3. After releasing selection lines stick, until:
    - Next left / right click
    - Select any file 2 times
    - Change directory
    - Scroll on directories which have vertical scroll
    - move window

## Screenshots
 https://i.imgur.com/XvmznBS.mp4

## Enviroments:
OS: Manjaro 18.0.2 Illyria
Kernel: x86_64 Linux 4.19.20-1-MANJARO
Shell: bash 5.0.0
DE: Deepin 15.9
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
bits: 64
compiler: gcc
v: 8.2.1
tk: Qt 5.12.0
dm: LightDM

### Distro & Version
Manjaro Deepin 18.0.2

### Additional context
Happens on all versions: Arch / Manjaro / Fedora / Linux Deepin

While this can be considered more as funny feature, than bug...
I still think it worth mentioning here, maybe understanding what caused it can lead to prevent / solve future real bugs :smile_cat:

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
