### ISSUE TITLE
GTK Theme buggy buttons on Firefox without title bar

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#921]
## Describe the bug
Firefox, when using without title bar, **Minimize** / **Maximize** / **Close** buttons look like they just have been cutted out, and have incorrect spacing which makes them harder to use, and looks a bit off.

## To Reproduce
1. Customize...
2. Disable **Title bar** (at the bottom left)

## Expected behavior
Should either have exact style as with title bar, or be at least closer in style and have proper spacing.

## Screenshots
https://i.imgur.com/JiqhHPx.png

## Enviroments:
OS: Manjaro 18.0.2 Illyria
Kernel: x86_64 Linux 4.19.20-1-MANJARO
Shell: bash 5.0.0
DE: Deepin 15.9
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
bits: 64
compiler: gcc
v: 8.2.1
tk: Qt 5.12.0
dm: LightDM

### Distro & Version
Manjaro Deepin 18.0.2

### Related package version
deepin-gtk-theme 17.10.10-1

### Additional context
Happens on Arch / Manjaro Deepin, Linux Deepin, Fedora Deepin

**Comment by keybreak** [comment]
btw, maybe someone know reason why historically Firefox by default do not use wihtout title bar on Linux?
It's such a waste of space, so just wondering)

**Comment by hualet** [comment]
> btw, maybe someone know reason why historically Firefox by default do not use wihtout title bar on Linux?
> It's such a waste of space, so just wondering)

Because it's not polished at all under Linux, it's just window removed WM decorations, which means it's not product ready I think.

**Comment by keybreak** [comment]
> Because it's not polished at all under Linux, it's just window removed WM decorations, which means it's not ready I think.

Huh...Interesting, thank you!
I thought there should be some native mechanism to do such things in a less harmfull fashion)

Though still it can be considered as inconsistency on Deepin side, since at least Cinnamon, Gnome, KDE handles this case with properly styled buttons :yin_yang:

**Comment by BLumia** [comment]
Hi and did deepin-kwin also have this issue?

**Comment by keybreak** [comment]
Yes, it's easy to test.

More than that - on deepin-kwin also title bar doesn't hide at all (even though additional buttons are shown) 
![image](https://user-images.githubusercontent.com/47599989/62023608-4d565080-b1da-11e9-89fa-092afe2ac984.png)

**Comment by BLumia** [comment]
> More than that - on deepin-kwin also title bar doesn't hide at all (even though additional buttons are shown)

https://github.com/linuxdeepin/developer-center/issues/1460

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
