### ISSUE TITLE
Flatpak版深度影院/音乐/日历字体不跟随系统

### ISSUE THREAD

**Issue by CJ6922G1CH** [linuxdeepin/developer-center#922]
## 缺陷描述
Flatpak版深度影院、深度音乐和深度日历的字体不随系统字体改变，并且不能设置大小。

## 复现步骤
打开深度影院/音乐/日历。

## 截图

![image](https://user-images.githubusercontent.com/47511859/52924404-a5ee0b80-3367-11e9-8702-e94610d75443.png)
深度影院
![image](https://user-images.githubusercontent.com/47511859/52924428-c027e980-3367-11e9-9b8b-ccc6e5c4bc61.png)
深度音乐
![image](https://user-images.githubusercontent.com/47511859/52924445-d59d1380-3367-11e9-83e9-fc08b77a4d79.png)
深度日历

![image](https://user-images.githubusercontent.com/47511859/52924482-fa918680-3367-11e9-8ec3-2c7d13ae0532.png)
作为对比，文管字体不存在问题
### 发行版以及版本
Linux Deepin 15.9.1

### 相关的软件包版本
deepin-fpapp-org.deepin.flatdeb.deepin-movie 3.2.18
deepin-fpapp-org.deepin.flatdeb.deepin-music 3.1.14
deepin-fpapp-org.deepin.flatdeb.deepin-calendar 1.2.6
在最近几个月的版本中问题一直存在，不限于上面的版本。

**Comment by CJ6922G1CH** [comment]
我一直把Windows的字体复制到Deepin里面用，不知是否与问题有关。
我复制字体的步骤是：
1、把Windows\Fonts目录下的*.ttf和*.ttc字体复制到/usr/share/fonts/myfonts目录下
2、用fc-cache命令刷新字体缓存

**Comment by CJ6922G1CH** [comment]
试了下，把从Windows复制来的字体删除后，再打开深度影院，字体有变化，但依然不是系统字体。
![image](https://user-images.githubusercontent.com/47511859/53168880-a95aee80-3616-11e9-876d-c73fdc7e6eab.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
