### ISSUE TITLE
[需求]隐藏 .deepin.db、.deepin.lft、.deepin.num等文件

### ISSUE THREAD

**Issue by lolimay** [linuxdeepin/developer-center#923]
在 Windows 资源管理器中隐藏文件是分系统隐藏文件和普通隐藏文件两种的，一般用户显示隐藏文件不需要在文件管理器中显示.deepin.db、.deepin.lft、.deepin.num 这些文件(搜索加速用的?)。

建议 deepin 在文件管理器中增加一个选项

- [x] 显示隐藏文件
- [ ] 显示系统隐藏文件

若仅钩选显示隐藏文件，则文件管理器只会显示普通隐藏文件(.开头的文件或目录，但会忽略 .deepin.* 这些文件)，只有用户勾选显示系统隐藏文件后，才显示这些系统文件。

**Comment by keybreak** [comment]
That's interesting idea, i'd also consider this.

And add that **lost+found** directories can also be in **System hidden files**, since most casual users don't need to see this anyway)

**Comment by lolimay** [comment]
Add **System Volume Information** and **$RECYCLE.BIN** these directories to system hidden files maybe better :)

**Comment by BLumia** [comment]
个人不太认可这种做法，这些点开头的文件本身已经是刻意隐藏的了，那些点开头的目录和文件也都可以被理解为某种程度上的 “系统隐藏文件” ，只不过某些文件可能对某种程度上的高级用户来说比较常用而已。

没有相对来说特别好的方法来决定什么是这个概念上的“系统隐藏文件”，如果用户希望的话，自己维护这个列表决定什么文件需要彻底在深度文件管理器中隐藏会更合理一些？

**Comment by lolimay** [comment]
如果能让用户维护一个隐藏路径列表也是一个不错的策略。

**Comment by BLumia** [comment]
> 如果能让用户维护一个隐藏路径列表也是一个不错的策略。

[教大家几招文件管理器隐私管理的奇技淫巧](https://bbs.deepin.org/forum.php?mod=viewthread&tid=172237) by @zccrs  :)

**Comment by lolimay** [comment]
Thanks.

**Comment by keybreak** [comment]
He should also translate this on english (if not already) for international audience, some usefull stuff in there! :)

**Comment by lolimay** [comment]
You can 

> He should also translate this on english (if not already) for international audience, some usefull stuff in there! :)

Hi, you can add exclude rules by simply put an json file named `dde-file-manager.obtusely.json` under `~/.config/deepin` folder. And its content can be like this:
````json
{
    "PrivateFiles": {
        "Hide deepin system files": "^\\.__deepin.+",
        "Hide System Volume Information": "System Volume Information",
        "Hide $RECYCLE.BIN": "\\$RECYCLE\\.BIN",
        "Hide .Trash-1000": "\\.Trash-1000"
    }
}
````

**Comment by keybreak** [comment]
Thx, i understand)

I mean on forum, for those who don't know chinese or google translate :)
But now they can find it here anyway, so it's good! :)
