### ISSUE TITLE
不知道这个问题是否是dde的锅，麻烦看一下

### ISSUE THREAD

**Issue by YLXDXX** [linuxdeepin/developer-center#925]
看了对方的回复，似乎是在注销或者重启时没有给应用发送相应会话，导致的数据没有保存从而记录丢失
地址：https://github.com/goldendict/goldendict/issues/1124
不知道是不是dde的锅，麻烦看一下

**Comment by hualet** [comment]
应该是因为DDE没有Session Manager的原因。

**Comment by electricface** [comment]
https://en.wikipedia.org/wiki/X_session_manager

**Comment by zccrs** [comment]
嗯，DDE环境现在还没有支持session manager

**Comment by hualet** [comment]
@electricface 你看看实现起来麻烦不麻烦？

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
