### ISSUE TITLE
功能建议：影院拖放加载字幕

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#927]
目前深度影院支持从文件管理器拖放影片立即播放。如果拖放字幕文件，则目前没有任何效果。建议增加拖放字幕文件添加并立刻启用。

**Comment by aiamuzz** [comment]
Yes it would be convenient if a drag drop was implemented ... 

As most of the subtitle serving websites provide zip(archive) files for subtitles ... **wouldn't it be better if deepin-movies supported the drag and drop of these archive(zip) files(besides the subtitle formats) directly** ... that way the user will save additional steps of having to ... **download ... go to download folder ... extract the subtitle file ... and then drag it to the movie player ...**  ... with the zip file drag'n'drop supported one could pull the downloaded subtitle file directly from the chrome footer where the downloaded file is visible !!!

**Comment by zccrs** [comment]
这是一个好的建议

**Comment by shule1987** [comment]
这个应该支持

**Comment by wangjia12** [comment]
以前的需求没有写拖拽，而且载入时有限制要求： 字幕文件名和播放影片文件名一致；字幕文件和影片文件在同一目录下；
更新为：拖拽也及时生效载入，去掉上面的限制要求。
