### ISSUE TITLE
Feature Request/Enchancement : Making DeepinOS and Applications UI's 100% keyboard controllable / navigable

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#928]
Hi,

It would be great if the Deepin Team addressed this long over due UX across Deepin OS and all Deepin Applications.

every UI of the DeepinOS, DDE and Deepin application user interfaces should be made 100% keyboard controllable and navigable !!!

User must be able to access every control, button, field in the UI through their keyboards ... This is possible in Windows OS and was possible in before Ubuntu 16.06 !!!

If one has to imagine ... then imagine that the laptop/computer has no mouse or touchpad only keyboard ... given this the user should continue to be able to work on the computer/laptop just fine ... **With a combination of the `Tab` & `Shift+Tab` to navigate ... and ... keyboard accelerator options across the entire Deepin ecosystem.**

Please look at the examples below to understand what i am trying to say ...

I don't know if anybody else has been missing these options ... people who use their systems often are habituated to them ... without them the workflow is slower and cumbersome.

If ease of use and user friendliness are the primary objectives then ... the Deepin Team should consider bringing this back to their users ...

![image](https://user-images.githubusercontent.com/3283676/53104633-bb288d00-3555-11e9-9a8f-792ede357e7e.png)

These options can be made universal across DeepinOS and Deepin apps and their menu's and UI's ... 

Any UI that has a button, a field to navigate into and take control of the items inside ... should be easily accessible through these keyboard accelerators(**the underlined alphabets in the menu's**) ...

**Comment by aiamuzz** [comment]
chrome menu has these keyboard accelerators ... 

![image](https://user-images.githubusercontent.com/3283676/53105046-689ba080-3556-11e9-84ff-a9cead66f98f.png)

file save dialogue boxes have it ...

![image](https://user-images.githubusercontent.com/3283676/53105109-8963f600-3556-11e9-9301-e264d47dc29b.png)

**Comment by keybreak** [comment]
I absolutely agree that would be huge plus.

Actually wanted to started topic that shows that some existing stuff like for example dialog opening when launching executable file doesn't have focus state for keyboard (which should be same as mouse hover in this case)

**Comment by aiamuzz** [comment]
> I absolutely agree that would be huge plus.
> 
> Actually wanted to start request that shows some existing stuff like for example dialog opening when launching executable file doesn't have focus state for keyboard (which should be same as mouse hover in this case)

@keybreak ... thanks ...

yes the focus is completely off in dialogue boxes (file chooser for example) ... One couldn't operate it without a mouse/touchpad ...

**Comment by es20490446e** [comment]
Showing keyboard shortcuts by their menu options looks like a quite good idea to me.

**Comment by BLumia** [comment]
cc @wangjia12

**Comment by aiamuzz** [comment]
> cc @wangjia12

on Deepin OS this is long over due ... reaching for the mouse, or the trackpad is just ineffecient when each finger has its own memory(your fingers know where is each key is) & working with the keyboard controls and shortcuts, is the most efficient of all input channels ...

making the OS a 100% compliant at controlling every aspect of the UI/UX with it through visual(showing shortcuts besides the menu's) cues and the keyboard is highly essential ...

Its not that Deepin OS and Applications don't have it all together ... in fact some UI's do have it ... Its just that its not done systematically and does not cover all areas of the OS and App GUI's is why this thread has been started !!!

@BLumia ... @wangjia12 ... just discuss this with the team and if its approved we could start off this whole exercise with the Deepin Applications first ...

**Comment by keybreak** [comment]
I would say it's not about showing shortcuts combinations near menu options (which in most cases is bad thing that will clutter interface and kill whole feeling of experience ease, **Ctrl**+**Shift**+**?** should be enough).

Deepin is already very intuitive in most places for keyboard navigation and use pretty much all known key combos, except few places in UI are still not ready for full keyboard experience, like those focus states when you open executable files, for example.

**Comment by keybreak** [comment]
@es20490446e 

> If putting shortcuts in the menus will clutter them, an alternative could be making the list of shortcuts more discoverable. For example, by putting it in the application menu.

Well, here i would agree, maybe add **Show shortcuts** to this menu or something:
![изображение](https://user-images.githubusercontent.com/47599989/55790608-66b97c80-5ac5-11e9-9449-75efcfecc47a.png)

@aiamuzz 
It's impossible to have both fast & easy readability of menus like now and not cluttering UI further when there are lot more information present :smiley: 

This compromise is for a reason, good UI is an art of balance - i say overall Deepin is in a really good place now, which is easy to break.

**Comment by es20490446e** [comment]
"Ctrl+Shift+?" is not very discoverable right now, and having the shortcuts on the menus instead of in a long list is more intuitive.

If Google chose to put the shortcuts by the menu options, probably they thought about the topic thoroughly way before us.

**Comment by aiamuzz** [comment]
> It's impossible to have both fast & easy readability of menus like now and not cluttering UI further when there are lot more information present 
> 
> This compromise is for a reason, good UI is an art of balance - i say overall Deepin is in a really good place now, which is easy to break.

I know its tricky ... 

but we need to remember Deepin users are not virgin users ... they are users who have been using other OSes with standard protocols for years ... when such users try out Deepin ... we would not be able to have them pick up the the 'art of balance' ... they'll look for pre-existing standards they are so accustomed to ... if they don't find them ... then they decide between a higher learning curve and quitting  ... more experienced users will plainly quite ... as they are behind efficiency ... its only new users or non-serious users who will stick longer picking up the learning curve ...

**Remmber, its always a good strategy and design to have the age old standards in place first ... then we can entice the users with the special deepin specific value features !!!** ...

if we continue to hold that philosophy of balance we would be losing more users than gaining ... 

Remember our fingers and brains have gotten accustomed to standard work flows ... and its a kind of addiction which takes place in a sub conscious state ... its best to enable it and then entice the user with the glitz and glamour of Deepin's eye candy UI/UX !!!

**Comment by keybreak** [comment]
@es20490446e 
I would have to disagree, don't mind google as a Greatest wisdom of UI.

They're full of :hankey: actually. Like at least 15 years ago i was huge advocate for making dark themes for websites and programs UI (because of the ease on the eyes, therefore people will perceive client's information easily & longer i must add), and all my clients was like 'ooh, but Google do dark text on white backgrounds, they must have already thought of it, so do it like everyone!'.

And now, mighty Google corporation UI genius discovered same thing i've done 15 years ago + fact that dark modes eating way less battery. Guess what, now everyone is making dark UI like crazy! :smiley: 

So, i think we shouldn't really rely on those giants, besides Deepin have balanced many different practices and philosophies to get this far in terms of beauty - i'd say it's a very good UI balance now.

Far more important is to cover areas where keyboard only navigation is not yet complete.
___

@aiamuzz 
In terms of stuff like keyboard shortcuts near menu options - it's a very long time practice (way before Google), but a big trade-off in making clean modern UI (especially considering the fact that people now born with CTRL+C / CTRL+V / CTRL+S / CTRL+P / CTRL+F in blood), but that's just my personal impression & experience as a professional on that topic.

Those are universal shortcuts for every OS / Program this days, so i really doubt anyone will drop Deepin just because they don't see standard shortcut near menu item...

Other thing is non-standard shortcuts, here i think CTRL+SHIFT+? doing a good job, but @es20490446e got the point - it could be more discoverable, through menu perhaps...

**Comment by es20490446e** [comment]
I don't think dark themes are a good idea, because they have too much contrast with pages that are white. Like websites and documents.

A better alternative is to be able to easily adjust monitor brightness, as it happens on Deepin.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
