### ISSUE TITLE
深度终端: 在bash中确定使用的是普通模式还是雷神模式

### ISSUE THREAD

**Issue by CareF** [linuxdeepin/developer-center#929]
比如说我在 .bashrc 里用了 screenfetch (or neofetch), 但是不希望雷神模式也启动这个, 希望能用 bash 确定是不是雷神模式.. 用这样的命令可以知道我在用什么终端: 

```
ps -h -o comm $(ps -h -o ppid -p $$)
```

可惜的是并没有办法确定是普通模式还是雷神模式.. 

不知道这个功能有没有实现, 如果没有的话, 能不能在比如说启动雷神模式的时候定义一个 bash 变量?

**Comment by listenerri** [comment]
可以写个 shell 脚本替换 /usr/bin/deepin-terminal
在脚本里检测是否传入了参数 `-q` 或者 `--quake-mode`, 有的话表示要启动雷神模式, 这时就使用 env 或者 export 设置一个变量, 你试试看是否可行

**Comment by CareF** [comment]
@listenerri 可行! 多谢... 不过可能官方支持这个功能吗? 

in case 之后有人遇到同样的问题: 
```
#!/bin/bash
for i in "$@"; do
    case $i in 
        -q|--quake-mode)
            QUAKE=1 /usr/bin/deepin-terminal-real "$@"
            exit
    esac
done
/usr/bin/deepin-terminal-real "$@"
```
