### ISSUE TITLE
[archlinux]dde-session-daemon内存泄露，你们是不是不管了 = =

### ISSUE THREAD

**Issue by kirigayakazushin** [linuxdeepin/developer-center#93]
![20160529230805](https://cloud.githubusercontent.com/assets/12298476/15634281/89a12d2e-2585-11e6-9d52-8895a2374564.png)
十几分钟就这么多，基本上啥都干不了，分分钟内存爆炸，我总不能真的去写个脚本一直杀进程吧。

**Comment by hualet** [comment]
竹基表激动，gccgo编译的版本就是内存泄露比较严重，但是这个真得不好调哇哇哇%>_<% @felixonmars @fasheng

**Comment by zhuzilinuser** [comment]
@hualet   唉，还是早点想办法解决吧

**Comment by fasheng** [comment]
重复问题合并
https://github.com/linuxdeepin/developer-center/issues/100
