### ISSUE TITLE
[Enhancement] Highlight/Shade on Window Buttons

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#930]
Improve window button finishing (minimize, maximize, and close).

Currently, the close button has a circle behind it (kind of shadow). My suggestion is that this (colored?) circle only appears when the cursor is over the buttons.

Suggestion:
![deepin-screen-recorder_select area_20190220173749](https://user-images.githubusercontent.com/45263160/53122835-688ba880-3536-11e9-9350-d9d8041019ba.gif)

**Comment by aiamuzz** [comment]
@alexwender1 ...

what you are suggesting is generic ...

I think the current implementation of block(square) spanning the entire height of the window bar is unique and different to a generic implementation !!!

**Comment by alexwender1** [comment]
> @alexwender1 ...
> 
> what you are suggesting is generic ...
> 
> I think the current implementation of block(square) spanning the entire height of the window bar is unique and different to a generic implementation !!!

My criticism is about that circle in the "close" ... It seems to be something not finalized.

I just suggested that they complete what they were doing ... or remove (as you suggested).

![captura de tela_selecionar area_20190220191506](https://user-images.githubusercontent.com/45263160/53139414-588cbc80-3568-11e9-8802-86e9a170f4df.png)

**Comment by aiamuzz** [comment]
@alexwender1 ... oh ok ... i get it now ... you are right ...

@shule1987 ... don't you think the grey background for only the the close button seems an aberration ... may be getting rid of that great background altogether should be better ...

**Comment by shule1987** [comment]
> @alexwender1 ... oh ok ... i get it now ... you are right ...
> 
> @shule1987 ... don't you think the grey background for only the the close button seems an aberration ... may be getting rid of that great background altogether should be better ...

We have removed the grey background of the close button long time ago, why it's still exist ?
@zccrs

**Comment by aiamuzz** [comment]
> > @alexwender1 ... oh ok ... i get it now ... you are right ...
> > @shule1987 ... don't you think the grey background for only the the close button seems an aberration ... may be getting rid of that great background altogether should be better ...
> 
> We have removed the grey background of the close button long time ago, why it's still exist ?
> @zccrs

oh ... its still there for me(file manager)

![image](https://user-images.githubusercontent.com/3283676/53147257-06ca4d80-35cd-11e9-99b3-66700e7b6440.png)

**Comment by keybreak** [comment]
Yep, confirm all versions of Deepin distros have this background

**Comment by alexwender1** [comment]
> > @alexwender1 ... oh ok ... i get it now ... you are right ...
> > @shule1987 ... don't you think the grey background for only the the close button seems an aberration ... may be getting rid of that great background altogether should be better ...
> 
> We have removed the grey background of the close button long time ago, why it's still exist ?
> @zccrs

But it's not available in the public version...

Deepin 15.9.1
Deepin File Manager 4.7.5

**Comment by zccrs** [comment]
Fix https://github.com/linuxdeepin/dtkwidget/commit/dfe278ce26ba6652bfc42cff92b620e332a45e13

**Comment by keybreak** [comment]
Fixed in all Deepin apps in Arch, but GTK theme still have this background)

**Comment by alexwender1** [comment]
@zccrs Should today's update (15.9.2) fix this?

My AppImage applications (which use the system's title bar and border) continue to display this "circular shadow".

On the left ("broked") ... LibreOffice, Inkscape and GIMP (both AppImage). On the right, the Deepin File Manager.

![Captura de Tela_selecionar área_20190311092802](https://user-images.githubusercontent.com/45263160/54124999-98fe8e00-43e2-11e9-8508-bb94d9fcaefd.png)

**Comment by keybreak** [comment]
Yep, that's what i was refferring to - only native Deepin programs got this patched, GTK theme is still old style)

**Comment by felixonmars** [comment]
deepin-gtk-theme needs some adjustments it seems. @zccrs

**Comment by keybreak** [comment]
In fact a lot of adjustments + on Arch / Manjaro in most programs (except qt) there are complete absence of Deepin GTK theme for open/save dialogs https://github.com/linuxdeepin/developer-center/issues/613, which ruins whole experience :)
