### ISSUE TITLE
dde-system-daemon instances for user root running when logged out

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/developer-center#931]
## Describe the bug
After log out and log in, it takes a very long time until desktop icons appear. The dock never appears and I have to kill the session from a tty.
When running htop in the tty I can see that instances of dde-session-daemon and dde-filemanager-daemon are still running for user root !!??
After killing these processes, log in works again normally.

### Distro & Version
Manjaro with latest packages

### Related package version
deepin-daemon 3.22.0

**Comment by oberon-manjaro** [comment]
![20190221_005140](https://user-images.githubusercontent.com/11800714/53133370-33ea1200-3573-11e9-8ddd-29dbb428f3cb.jpg)

**Comment by electricface** [comment]
it is dde-system-daemon

**Comment by oberon-manjaro** [comment]
I have uploaded an ISO built with current packages. You can download it from [here](https://osdn.net/projects/manjaro-community/storage/deepin/.18.0.4/)
Please try this: From the first launch autologin-session log out, then log back in (password is manjaro)
It takes minutes before desktop icons appear and the dock starts.
When on the other hand you kill the above mentioned processes while being logged out, the next session will start normally. ...
I am stuck here.

**Comment by oberon-manjaro** [comment]
Anyone?
I have currently suspended releasing a new version of Deepin Manjaro for this issue. When logging out and back in the session takes forever to fully load, showing a black screen for a while, then the empty wallpaper and only then becomes usable.

**Comment by electricface** [comment]
dde-system-daemon won't quit at logout, it's the design.

**Comment by oberon-manjaro** [comment]
But apparently it causes serious problems on re-login. Or at least it looks like login works normally when a kill dde-system-daemon.
Should I look elsewhere for the root of the problem or will this simply be accepted and not addressed?

**Comment by keybreak** [comment]
@BLumia 
We need to resolve this one, it's last big obstacle for upcoming Manjaro Deepin .iso which is already heavily delayed because of few Deepin bugs...

**Comment by electricface** [comment]
I use manjaro Linux and then use the command `pacman -Syu` Upgrade to the latest, and did not encounter this problem.

**Comment by electricface** [comment]
Do I need to download this iso to test it?
https://osdn.net/projects/manjaro-community/storage/deepin/18.0.4-rc/manjaro-deepin-18.0.4-rc-testing-x86_64.iso/

**Comment by electricface** [comment]
I installed manjaro deepin 18.04 rc completely, and then I can't reproduce this bug.

**Comment by oberon-manjaro** [comment]
so you only have the issue in vbox?

**Comment by electricface** [comment]
My test machine is not a virtual machine.
yes, I log out and back in without a major delay.

**Comment by oberon-manjaro** [comment]
@keybreak my understanding was that you have these problems on real hardware? Misunderstanding on my side?

**Comment by keybreak** [comment]
@oberon-manjaro 
Yep, i'm afraid so:
> I’ll test rc on VM today, will report back if anything sticks out.

(c) @keybreak  https://forum.manjaro.org/t/manjaro-deepin-18-0-4-rc-testing-branch/78550/4

So it's only VM?
Still bad though)

**Comment by electricface** [comment]
I can reproduce the problem.
Failed to activate service 'org.ayatana.bamf': timed out (service_start_timeout=120000ms)

**Comment by electricface** [comment]
Should be user-1000.slice does not exit immediately after logging out

**Comment by oberon-manjaro** [comment]
Thanks for your investigation, @electricface 

> or remove this line of the /usr/lib/systemd/user/bamfdaemon.service file

So do you think this is actually a bug in **bamf**?

**Comment by electricface** [comment]
The bamf daemon should have no bugs.
 After logging out, `systemd --user` repeatedly starts the bamf daemon, but since there is no X server, the bamf daemon fails to run and then exceeds the limit.
If you can let user-1000.slice end immediately after logging out, it should be fine.

**Comment by oberon-manjaro** [comment]
> If you can let user-1000.slice end immediately after logging out

Where would that have to be accomplished? Shouldn't the be the DM's job?

**Comment by electricface** [comment]
This tag 3.13.2 fixes this problem

**Comment by oberon-manjaro** [comment]
Thanks a lot! Will verify as soon as the update arrives :+1:

**Comment by oberon-manjaro** [comment]
The lag when re-loggin is gone with **3.13.2**. Thank you again, @electricface ! :tada: :balloon:
