### ISSUE TITLE
非系统硬盘的展示优化建议

### ISSUE THREAD

**Issue by FurryWolfX** [linuxdeepin/developer-center#932]
目前多块硬盘的情况下，非系统盘的展示方式与USB设备的展示方式相同（即可以随时弹出，且在dock上展示为USB设备的图标）。

但是实际上，我的硬盘不是USB设备，而是接在SATA上的硬盘，不应该和USB设备用同样的展示方式（也最好不要让用户随意弹出，毕竟可能在上面执行程序）。

希望能改进展示方式。

**Comment by zccrs** [comment]
关于图标那个有截图吗，可以上传个图片

**Comment by licardoY** [comment]
十分赞同!

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
