### ISSUE TITLE
deepin-installer 安装器 6.0.57

### ISSUE THREAD

**Issue by ArchieMeng** [linuxdeepin/developer-center#9347]
### package information | 软件包信息

deepin-installer 6.0.57

### Package repository address | 软件包仓库地址

https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20240618/deepin-23-beige-rc2-amd64-20240618-114444.iso

### changelog | 更新信息

- https://github.com/linuxdeepin/developer-center/issues/8994
- 修复：SW架构安装后，重启无法进入系统 https://pms.uniontech.com/bug-view-190493.html
- 默认选择英语语言 https://doc.uniontech.com/docs/loqeWONl96TXGdAn
- https://github.com/linuxdeepin/developer-center/issues/8826

### test suggestion | 测试建议

- 按照Issue和需求文档展开测试。
- SW架构安装问题修复是Zeno提出带入的，看要不要找台测试一下。

### Sphere of influence | 影响范围

UI界面，保存错误日志的弹窗。

### ADDITIONAL INFORMATION | 额外补充

无

**Comment by babyfengfjx** [comment]
@xuqi27837288  请开展回归验证。

**Comment by Zeno-sole** [comment]
@xuqi27837288  @kobe337  https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240618/   需验证arm64 amd64 loongarch64架构镜像

**Comment by Zeno-sole** [comment]
> @xuqi27837288 @kobe337 https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240618/ 需验证arm64 amd64 loongarch64架构镜像

测试看下默认的x86 arm架构下默认的启动项应该是deepin(除非有特殊固件情况)，本次加入--force-extra-removabl参数主要是解决loongarch64 部分机器安装后无法引导的问题（加参数后默认的启动项应该是boot 预期行为），由于该参数对全架构生效需一起验证其他架构

**Comment by xuqi27837288** [comment]
【验证环境】：v23 RC2镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240618
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.25-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：集成测试通过,已验证其他架构的安装、amd下安全启动场景
