### ISSUE TITLE
[Feature Request] A keyboard launcher with DDE design language

### ISSUE THREAD

**Issue by gokhanyildirimlar** [linuxdeepin/developer-center#937]
Using different keyboard launchers is fine but they don't quite fit with the design language of DDE. So, doing quick math; searching for a folder, a software or a bookmark etc. are okay but the point is unified design language. Also, I personally know many people use this kind of software to make things quicker and simpler. Just hit the key combination to launch it, search what you want and there it is. No need to navigate between things, It's a simplistic approach in my opinion.

[Github link to Albert as instance](https://github.com/albertlauncher/albert)

**Comment by keybreak** [comment]
Well i don't know, now you can press **SUPER** key and start search, or **CTRL**+**ALT**+**T** to get terminal )

**Comment by aiamuzz** [comment]
Didn't really know about this package ...

Is this by any chance the option in Unity(Ubuntu) where one can search terms and the result will show for apps, documents or anything else that matches the search term ?

**Comment by gokhanyildirimlar** [comment]
@keybreak, you can only search for software and nothing more by that way.

**Comment by gokhanyildirimlar** [comment]
@aiamuzz yes, I don't remember Unity exactly but the idea is more or less that. Files, folders, apps, simple calculations, bookmarks, commands etc. All in one keyboard launcher.

**Comment by aiamuzz** [comment]
> @aiamuzz yes, I don't remember Unity exactly but the idea is more or less that. Files, folders, apps, simple calculations, bookmarks, commands etc. All in one keyboard launcher.

ok ... i remember ... simple calculations, bookmarks ... i know there were some gnome extensions which would enable one to enter the terms or calculations in the launcher search window and you'd get the result below ...

**Comment by keybreak** [comment]
@gokhanyildirimlar
Oh ok it's cool )

@wangjia12 
I only wanted to ask, if it's gonna be implimented please make it as separate package, so it can be easily turned off / removed, without messing system core components :)

**Comment by felixonmars** [comment]
I have added albert to [community] repository of Arch. The "Numix Rounded" theme fits very nice for me.

**Comment by wangjia12** [comment]
This feature has been in our plan, but there are more important features ahead of its priority. Your suggestions will be seriously considered.

**Comment by gokhanyildirimlar** [comment]
@wangjia12 Thanks, I will look forward to. I am waiting only for KWin update for now. Others can take as long as you want.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
