### ISSUE TITLE
Latest update bricks system (again)

### ISSUE THREAD

**Issue by antechdesigns** [linuxdeepin/developer-center#938]
No desktop after latest update, I give up !!

**Comment by keybreak** [comment]
That's weird man, i use your Arch on VM, seems to run ok

**Comment by antechdesigns** [comment]
Packages (5) 
deepin-api-3.17.0-1  
deepin-daemon-3.23.0-2  
deepin-qt-dbus-factory-1.0.9-1  
deepin-session-ui-4.8.10-1  
startdde-3.12.0-1

Did you update to these @keybreak 
no I don't use autologin

**Comment by keybreak** [comment]
Hmm...Actually not yet, maybe my repos haven't synced yet, will wait to report once those are ready

**Comment by oberon-manjaro** [comment]
The problem seems to be with **deepin-daemon**. I can install all the other latest packages from Arch fine, but when I upgrade deepin-daemon the dock will not start.

**Comment by felixonmars** [comment]
@oberon-manjaro I missed deepin-desktop-schemas from moving, and fixed some time after that. Please update also that package and deepin-daemon would work fine.

**Comment by oberon-manjaro** [comment]
Yes, I confirm! With **deepin-desktop-schemas 3.12.0** installed, all is good. :tada: 
Thank you, @felixonmars

**Comment by felixonmars** [comment]
@antechdesigns Really sorry for the trouble. I decided to release new packages to [community-testing] this time, and after making sure it works fine I missed one package when moving the batch...

**Comment by oberon-manjaro** [comment]
No problem! :smile: Thank you for your effort!

**Comment by keybreak** [comment]
Updated just now, haven't bricked me (since it seems to be quickfixed), but i have this errors in Ant's Arch Deepin:
**sudo journalctl -p3 -xb**
```
Feb 23 09:47:30 x133 daemon/dde-system-daemon[4371]: main.go:67: name "com.deepin.daemon.Daemon" already has t>
                                                       ->  proc.go:201
                                                       ->  asm_amd64.s:1333
Feb 23 09:47:30 x133 daemon/bluetooth[4215]: bluetooth.go:236: Unit dbus-org.bluez.service not found.
                                               ->  bluetooth.go:211
                                               ->  asm_amd64.s:1333
```

Guys please check it, and test a little harder next time :)

**Comment by antechdesigns** [comment]
@keybreak 
To get rid of the bluetooth error, you can turn off (/com/deepin/dde/daemon/bluetooth) in dconf-editor, assuming you don't use bluetooth.

@felixonmars I have set up a VM specifically for testing, whats the procedure for testing deepin updates before release? thank you ;)

**Comment by keybreak** [comment]
@felixonmars
While @antechdesigns suggestions works, shouldn't it be default behaviour to disable it, on machine / VM that physically doesn't have bluetooth?

**Comment by felixonmars** [comment]
@keybreak The error should be harmless though, it just tries to enable a feature and found it's not available. I'm not sure what exactly should be improved here.

@antechdesigns I mostly only test packages that gets updated. IMHO we have few packaging errors and most issues are actually from upstream.

**Comment by keybreak** [comment]
@felixonmars
Correct me if i'm wrong, but **sudo journalctl -p3 -xb** is suppose to give only errors, and since you're saying it's not an actual error, more like warning or even info, than it shoud be marked so it wouldn't go to -p3 -xb, where actual errors usually situated...

**Comment by felixonmars** [comment]
@electricface So our friend here would like to hide some errors or at least lower the level.
