### ISSUE TITLE
deepin-m1 RC2 版本测试

### ISSUE THREAD

**Issue by ArchieMeng** [linuxdeepin/developer-center#9388]
### package information | 软件包信息

| 软件包    | 版本    |
| ---- | ---- |
| deepin-m1系统环境     |  RC2 (20240614日构建)    |
| linux-image-asahi	| 6.8.9-6|
| m1n1 | 1.4.14 |
| uboot | asahi-v2024.04-1|
| mesa | 24.1.0-asahi-20240228 |

### Package repository address | 软件包仓库地址

https://ci.deepin.com/repo/deepin/deepin-ports/deepin-m1/
USB安装盘打包: https://github.com/ArchieMeng/deepin-m1/actions/workflows/build-usb-installation.yml

### changelog | 更新信息

- 系统组件除M1平台专用的部分，其他增加到和完整的deepin v23 arm64 preview一致。
- 系统环境更新至RC2版本
- 新增自动构建的rootfs和USB安装盘内容打包
- 取消默认用户，支持安装后初次启动配置用户，语言，键盘布局和时区。https://github.com/linuxdeepin/developer-center/issues/4723
- 默认支持GPU加速
- 修复系统启动菜单无法使用键盘的问题
- 修复USB设备自动睡眠的问题

### test suggestion | 测试建议

- 主要针对 https://github.com/linuxdeepin/developer-center/issues/4609 中，Beta2版本时发现的问题进行回归验证。
- 发散验证其他可能问题。
- 可以的话，区分和X86_64平台上的表现。

### Sphere of influence | 影响范围

系统环境，安装流程

### ADDITIONAL INFORMATION | 额外补充

已知无法安装chromium,无法验证该浏览器相关问题。
已知当前版本还是没有声音支持

**Comment by babyfengfjx** [comment]
@luodeepin  请开展验证，确保系统基本功能能正常使用，发现的问题提交issue关联该集成即可，不做深入验证。

**Comment by luodeepin** [comment]
测试通过
1. 问题单回归通过
2. 发散测试没有新增严重问题
3. 声音插件相关是已知问题，因此未做重复关注
