### ISSUE TITLE
Do not update deepin-daemon for Arch! 最新升级使 dde 许多功能崩了.. 

### ISSUE THREAD

**Issue by CareF** [linuxdeepin/developer-center#939]
更新了: 
start-dde-3.12.0
deepin-daemon-3.23.0
deepin-api-3.17.0

dde-dock 不能正常启动, Fn 按键失效, ctrl-cap 键位替换失效, Win 打开 launcher 失效. 
top 命令显示 dde-dock 和 systemd-journal 有大量 CPU 占用. 
通过该桌面图标可以政策启动 filemanager 和终端. 终端内手动 pkill dde-dock; dde-dock 会看到大量重复的: 

```
org.kde.StatusNotifierWatcher SNI watcher daemon started, register dock to watcher as 
SNI Host
```

然后出现段错误死掉了. -x 不加载插件不能解决问题. 
回滚后恢复正常...

**Comment by CareF** [comment]
start-dde 和 deepin-api 手动安装更新后正常. 
问题应该是在 deepin-daemon 上.

**Comment by felixonmars** [comment]
抱歉，手误在移包时漏掉了 deepin-desktop-schemas，现已修复。
如果镜像尚未更新，您可以在 https://www.archlinux.org/packages/community/any/deepin-desktop-schemas/ 页面点击 "Download from mirror" 下载到新版包。

**Comment by CareF** [comment]
felix 老师深夜修 bug! 辛苦了!
