### ISSUE TITLE
[archlinux]启动器的模糊能不能调整以下，眼要瞎了。。

### ISSUE THREAD

**Issue by kirigayakazushin** [linuxdeepin/developer-center#94]
![-4ccb16270783f43](https://cloud.githubusercontent.com/assets/12298476/15648861/cfc067e0-2632-11e6-932f-c0b04867edec.jpg)
![20160530194848](https://cloud.githubusercontent.com/assets/12298476/15648862/cfc0bd80-2632-11e6-980f-7ffef4dd3510.png)

不调整模糊度的话，把模糊的结果调暗一些也行。。亮色壁纸能直接瞎眼。
上面的搜索也看不到了 = =
放一张osx的来做对比。

**Comment by hualet** [comment]
这是我的锅，我来领了……

**Comment by zhuzilinuser** [comment]
@hualet  哈哈^_^

**Comment by sonald** [comment]
@hualet 可以计算模糊壁纸的主色，然后更改对比度

**Comment by hualet** [comment]
那计算量太大了吧？应该还不如直接跟一层浅灰色合成一下……

**Comment by snyh** [comment]
主色的计算量非常小～

**Comment by snyh** [comment]
but.  主色是没有用的。　　　　launcher或者desktop的背景图本身就有一定要求。

一般通过HSV色彩空间　去限制背景图的效果吧。　　比如亮度绝对不能超过50

**Comment by hualet** [comment]
我试试

**Comment by manateelazycat** [comment]
已经针对浅色壁纸进行了暗度调整， 现在浅色壁纸不会导致眼睛瞎了。 ;)

谢谢您的反馈！ ;)
