### ISSUE TITLE
Settings on top of screensaver

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#941]
## Describe the bug
If you open settings and wait for screensaver to come up - settings will be on top of screensaver.

## To Reproduce
1. Set any screensaver for 1 minute
2. Open settings, wait for screensaver

## Expected behavior
Screensaver should either force to close settings, or be on top of everything on screen :)

## Enviroments:
OS: Manjaro 18.0.3 Illyria
Kernel: x86_64 Linux 4.19.24-1-MANJARO
Shell: bash 5.0.0
DE: Deepin 15.9
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
bits: 64
compiler: gcc 8.2.1
tk: Qt 5.12.1
dm: LightDM

### Distro & Version
Manjaro Deepin 18.0.3

**Comment by aiamuzz** [comment]
Well there are multiple cases of overlapping and inconsistencies around this subject ... 

1. Click on the plugin applet (disks, wifi, weather ...) and hit `Alt + Tab` and switch to any application window and you'll still see the plugin applet overlapping the application window ...

2. open the Movie application and play something in full screen mode ... the control center corner settings is blocked in full screen mode ... So hit `Alt + Tab` and choose File Manager ... now invoke the control corner setting ... as soon as the control settings draws out ... it over laps the movie full screen window ... when it should have overlapped over the File Manager ...

**Comment by aiamuzz** [comment]
![whatsapp image 2019-02-24 at 11 11 25 pm](https://user-images.githubusercontent.com/3283676/53302897-b0d5fe00-3889-11e9-8a0c-df5356abdab3.jpeg)

another inconsistence ... a qBittorrent right click menu showing on top of the screen saver ...

I guess the screensaver has to be flagged of as 'Always on Top' ... may not the be the case for issues faced in my last post !

**Comment by keybreak** [comment]
Yeah it's all the same, just flagging screensavers with somehing as **Always on top of even always on top** should solve all this issues :)

**Comment by keybreak** [comment]
@BLumia 
Should be easy to fix this, just force screensaver to always top of everything...
I want my screen to be actually saved))

\+ Another z-index issue

![Image of Yaktocat](https://i.imgur.com/FjqXyRV.png)

This is right click on deepin file manager icon, when starter open - should be on top of it, just like right click on taskbar itself which is actually on top now :smile_cat:

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
