### ISSUE TITLE
[Feature resquest] Used space in Deepin File Manager

### ISSUE THREAD

**Issue by KimHono** [linuxdeepin/developer-center#942]
Just something as simple as a progression bar : it would be nice !
As example, take a look at the file-manager Nemo.

**Comment by BLumia** [comment]
#724 cc: @wangjia12

**Comment by BLumia** [comment]
![_ _20190225104531](https://user-images.githubusercontent.com/34432879/53325029-44a4da00-391d-11e9-9fba-84ca27af6455.png)

from #796 , the new design will cover the both feature request :)

**Comment by keybreak** [comment]
That's perfect!

**Comment by KimHono** [comment]
Thanks !
