### ISSUE TITLE
rpm 版本 linglong 测试 (Open Euler 24.03 LTS Eur )

### ISSUE THREAD

**Issue by kamiyadm** [linuxdeepin/developer-center#9424]
### package information | 软件包信息

linglong |1.5.6-1

### Package repository address | 软件包仓库地址

https://eur.openeuler.openatom.cn/coprs/kamiyadm/linglong/repo/openeuler-24.03_LTS/kamiyadm-linglong-openeuler-24.03_LTS.repo

### changelog | 更新信息

新增Open Euler  eur, 为24.03版本的Open Euler系统提供linglong 的rpm 版本安装包

### test suggestion | 测试建议

1. 安装[OpenEuler 24.03 LTS](https://www.openeuler.org/zh/download/?version=openEuler%2024.03%20LTS)版本系统
2. 安装任意桌面环境，如[dde](https://docs.openeuler.org/en/docs/22.03_LTS_SP1/docs/desktop/installing-DDE.html)
3. 将eur仓库配置文件导入系统
     `sudo curl -o /etc/yum.repos.d/linglong.repo -L https://eur.openeuler.openatom.cn/coprs/kamiyadm/linglong/repo/openeuler-24.03_LTS/kamiyadm-linglong-openeuler-24.03_LTS.repo`
5. 更新仓库，并安装rpm版本玲珑
     `sudo dnf update`
     `sudo dnf install linglong-bin`
6. 使用ll-cli 安装软件包，百度网盘和QQ
7. 测试软件包是否能正常启动

### ADDITIONAL INFORMATION | 额外补充

本次集成只用于验收迭代任务

**Comment by babyfengfjx** [comment]
@vivianxf  请开展集成验证。

**Comment by vivianxf** [comment]
集成测试通过：

1.eulr系统安装成功，dde桌面环境安装成功
2.eur仓库配置文件导入系统成功
3.rpm安装linglong-bin，linglong-builder成功
4.ll-cli install com.baidu.baidunetdisk,ll-cli install linux.qq.com 安装应用成功，运行正常，卸载成功
5.ll-builder create创建，ll-builder build构建，ll-builder run运行应用成功
6.基本玲珑功能正常
7.提交三级issue #9445 ，不影响整体玲珑功能

综上所述，本次集成通过～
