### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【发散测试】【玲珑】ll-builder build 构建应用失败

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#9427]
### SUMMARY | 问题概要

ll-builder build 构建应用失败

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://packagesupdate.uniontech.com/repo/cdimage/deepin/23/v23-RC2-1/amd64/deepin-desktop-community-23-RC2-amd64.iso
linglong-builder:1.5.6-1
```

### PRE-REQUIREMENT | 预置条件

sudo apt install linglong-builder

### STEPS TO REPRODUCE | 复现步骤

1.终端执行：apt download com.baidu.baidunetdisk
2.终端执行：ll-pica convert -c com.baidu.baidunetdisk_4.17.7_amd64.deb -w w 
3.终端执行：cd /w/package/com.baidu.baidunetdisk 
4.终端执行：ll-builder build 
5.观察结果

### OBSERVED RESULT | 观察到的结果

1.ll-builder build 构建应用失败
![截图_deepin-terminal_20240625162126](https://github.com/linuxdeepin/developer-center/assets/96415804/64b11571-fb7d-49ff-948b-b27ecc5c58b6)

### EXPECTED RESULT | 期望的结果

1.ll-builder build构建应用成功

**Comment by babyfengfjx** [comment]
@dengbo11  请安排优化~

**Comment by kamiyadm** [comment]
是linglong.yaml里面的构建规则失败了，不是玲珑本体的问题

**Comment by vivianxf** [comment]
验证镜像：镜像地址：https://cdimage.uniontech.com/community/releases/23-RC2/amd64/deepin-desktop-community-23-RC2-amd64.iso
linglong-bin:1.5.7
验证步骤：提单的步骤
验证现象：ll-builder build构建成功
验证结果：通过

![image](https://github.com/linuxdeepin/developer-center/assets/96415804/a711a0c8-7ae0-447c-91b1-3dc537bf2423)
