### ISSUE TITLE
【deepin_V23_Release】【一般】【正常】【发散测试】【玲珑】ll-builder 转制appimage应用时，下载应用路径错误导致应用构建失败

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#9428]
### SUMMARY | 问题概要

ll-builder 转制appimage应用时，下载应用路径错误导致应用构建失败

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://packagesupdate.uniontech.com/repo/cdimage/deepin/23/v23-RC2-1/amd64/deepin-desktop-community-23-RC2-amd64.iso
linglong-builder:1.5.6-1
```

### PRE-REQUIREMENT | 预置条件

sudo apt install linglong-builder

### STEPS TO REPRODUCE | 复现步骤

1.终端执行：ll-builder convert --url "https://github.com/makebrainwaves/BrainWaves/releases/download/v0.15.1/BrainWaves-0.15.1.AppImage" --hash "04fcfb9ccf5c0437cd3007922fdd7cd1d0a73883fd28e364b79661dbd25a4093" --name "io.github.brainwaves" --id "io.github.brainwaves" --version "0.15.1" --description "io.github.brainwaves" -v
2.观察输出结果

### OBSERVED RESULT | 观察到的结果

1.ll-builder 转制appimage应用时，下载应用路径错误导致应用构建失败
![截图_deepin-terminal_20240625173933](https://github.com/linuxdeepin/developer-center/assets/96415804/46a8c30c-63b9-4b4d-a2e8-9e87407c7f0f)

### EXPECTED RESULT | 期望的结果

1.ll-builder 转制appimage应用时，应用构建成功

**Comment by babyfengfjx** [comment]
@dengbo11  请安排优化~

**Comment by dengbo11** [comment]
- fix: https://github.com/linuxdeepin/linglong/pull/544

**Comment by vivianxf** [comment]
验证镜像：镜像地址：https://cdimage.uniontech.com/community/releases/23-RC2/amd64/deepin-desktop-community-23-RC2-amd64.iso
linglong-bin:1.5.7
验证步骤：提单的步骤
验证现象：ll-builder 转制appimage应用成功
验证结果：通过
![image](https://github.com/linuxdeepin/developer-center/assets/96415804/3877a9a8-31d5-4f17-b0d3-b2bf43e3471e)
