### ISSUE TITLE
安装器 deepin-installer 6.0.58 集成

### ISSUE THREAD

**Issue by ArchieMeng** [linuxdeepin/developer-center#9436]
### package information | 软件包信息

deepin-installer 6.0.58

### Package repository address | 软件包仓库地址

https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20240626/deepin-23-beige-rc2-amd64-20240626-120010.iso

### changelog | 更新信息

- 试用模式时区配置 https://doc.uniontech.com/docs/loqeWONl96TXGdAn
- https://github.com/linuxdeepin/developer-center/issues/9378
- https://github.com/linuxdeepin/developer-center/issues/9359

### test suggestion | 测试建议

参考文档和对应Issue开展测试

### Sphere of influence | 影响范围

- 试用模式
- 安装新建分区

### ADDITIONAL INFORMATION | 额外补充

无

**Comment by babyfengfjx** [comment]
@baicailio  请开展回归验证。

**Comment by baicailio** [comment]
#9359 #9378 验证通过
备注：
1.安装器图标在任务栏缩略图问题，另提单跟踪：https://github.com/linuxdeepin/developer-center/issues/9461
2.live模式默认语言与产品沟通改为中文，另提单跟踪：https://github.com/linuxdeepin/developer-center/issues/9462
此集成通过
