### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【论坛反馈】【DDE】【控制中心】创建vpn OPenconnect时，当网关带端口时无法保存

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#9437]
### SUMMARY | 问题概要

1. 论坛反馈链接：https://bbs.deepin.org/post/274180
2. 对比在 20.9上同样操作可以正常保存

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
控制中心 6.0.56
```

### STEPS TO REPRODUCE | 复现步骤

1. 打开控制中心 - 网络 - vpn - 点击 + 号 
2. 在 VPN 类型中选择  OPenconnect , 输入网关 ，填写其他必填项后 保存

### OBSERVED RESULT | 观察到的结果

2. 报无效网关无法保存
![截图_选择区域_20240626211301](https://github.com/linuxdeepin/developer-center/assets/96416089/6798ca83-f278-4044-84bb-acfd4b9147eb)

### EXPECTED RESULT | 期望的结果

2. 保存成功

**Comment by babyfengfjx** [comment]
@kegechen  请优先处理~

**Comment by mhduiy** [comment]
与产品沟通, 去掉对网关的校验, 与v20专业版和20.9保持一致, 若用户输入错误的网关, 会有连接失败的提示

**Comment by xuqi27837288** [comment]
镜像：https://cdimage.uniontech.com/community/releases/23-RC2/amd64/deepin-desktop-community-23-RC2-amd64.iso
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.35-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
