### ISSUE TITLE
[Feature Request] Settings / Sound - Advanced options

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#944]
### Volume overdrive
Toggle switch to turn on / off volume overdrive systemwide.
Effectively when it's off it should mean that volume never ever go over 100%.

Important points for implementation:

- Don't make mistake in code about volume overdrive off. Shouldn't be off even slightly.
This is super-important feature for any audio professional, just for understanding, as a rule of thumb process of mixing / mastering digitally is more or less:
    1. Eliminate any OS level mixing out of equation by setting it to 100% (0 dB)
    2. Set master fader of DAW to 0 dB
    3. Control actual volume only through mixing / hardware audio interface.
- If overdrive was on, and volume was set for let's say 115%. After overdive switch turned off, it should **FORCE** to go 100%.
- There is laptop keyboard volume switch graphics, i suppose the line means 100% and everything to the right of it is overdrive. 
![Volume](https://i.imgur.com/Uz86riJ.png)
So if Volume overdrive was set off, there should be graphic without this line and 100% = all the way to right.
- Design wise should be somewhere under speaker toggle (see **Screenshot 1**) or inside Advanced options (see **Screenshot 2**).

- That's most likely out for debate, but i suggest it should be default to **OFF** for all new users. It's personal and sometimes situational, but in the first place i suppose overdrive was historically on for very very weak volume devices / audio sources, there's not much left this days.

### Advanced options
Systemwide options for chosen output:
1. Bit depth
2. Sample rate
3. Channels (not necessary, but why not)

As far as i understand it's equivalent of /etc/pulse/daemon.conf, sure you can do this with pulseaudio interfaces or jack, but why if you can have it beautifully done in Deepin DE interface :)

Important points for implementation:
- Should be relative to selected audio output (because different hardware have different capabilities).
Design of something like network settings should be suitable (see **Screenshot 2**).

## Screenshots
**Screenshot 1**
![Screenshot 1](https://i.imgur.com/O0YXohF.png)

**Screenshot 2**
![Screenshot 2](https://i.imgur.com/PKGMacR.png)

## Description
Everybody should benefit from all of this, but especially people who work with professional audio.

I suspect a lot people will flee from Windows & Mac for all of the obvious reasons like instability, privacy etc. And i would like beautiful Linux Deepin to be goto option for this kind of people :)

**Comment by damian101** [comment]
The option to manually choose the channel layout of a device would be actually very useful for me.
I use an audio interface with two stereo outputs, but on Linux it is always detected as a 4-channel surround device. When I watch a movie with surround audio then everything happening on the rear speakers is completely lost.
I don't know if reducing channel count for a device is even possible, ALSA and PulseAudio might have their limitations. Not an expert there.

**Comment by keybreak** [comment]
@damian101 
Wow that's weird...
Not even sure if it's ALSA bug or maybe something device specific, what audio interface do you use?

**Comment by damian101** [comment]
@keybreak I have the Behringer U-Phoria UMC404HD. I just found that this channel mapping "bug" is the device's fault. Without the specific Windows driver installed it is shown as a quadrophonic setup in Windows. So ALSA is innocent. :)
Maybe I should buy another pair of my studio monitors so I have a surround setup. ;)
The daemon.conf file entries already were identical to yours.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
