### ISSUE TITLE
org.deepin.browser 集成

### ISSUE THREAD

**Issue by myml** [linuxdeepin/developer-center#9444]
### package information | 软件包信息

org.deepin.browser | 6.5.3.2

### Package repository address | 软件包仓库地址

name: old  url: http://repo-dev.cicd.getdeepin.org

### test suggestion | 测试建议

1. 修改玲珑仓库，ll-cli repo modify http://repo-dev.cicd.getdeepin.org --name old
2. 安装或者更新 org.deepin.browser
3. 启动后快速输入中文验证问题是否解决

### Sphere of influence | 影响范围

- https://github.com/orgs/linuxdeepin/discussions/8830
- https://github.com/linuxdeepin/developer-center/issues/9409

### ADDITIONAL INFORMATION | 额外补充

输入法漏字母的问题是由于gtk应用没有正确配置fctix插件导致的，目前不准备将gtk放到runtime中，所以在应用侧解决，需要一个一个的处理

**Comment by babyfengfjx** [comment]
@xuqi27837288  请开展回归验证。

**Comment by Zeno-sole** [comment]
@myml  玲珑格式包 请走玲珑仓库推送流程
