### ISSUE TITLE
【deepin_V23_Release】【一般】【正常】【集成测试】【玲珑】ll-cli enter 进入容器失败

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#9445]
### SUMMARY | 问题概要

ll-cli enter 进入容器失败
关联集成：https://github.com/linuxdeepin/developer-center/issues/9424

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://packagesupdate.uniontech.com/repo/cdimage/deepin/23/v23-RC2-1/amd64/deepin-desktop-community-23-RC2-amd64.iso
linglong-builder:1.5.6-1
```

### PRE-REQUIREMENT | 预置条件

sudo apt install linglong-bin

### STEPS TO REPRODUCE | 复现步骤

1.运行一个玲珑应用：ll-cli install org.dde.calendar
2.查看正在运行的玲珑进程：ll-cli ps
3.进入正在运行的玲珑应用容器：ll-cli enter main:org.dde.calendar/5.13.1.1/x86_64 
4.观察输出结果

### OBSERVED RESULT | 观察到的结果

1.ll-cli enter 进入容器失败
![Screenshot_deepin-terminal_20240626183411](https://github.com/linuxdeepin/developer-center/assets/96415804/9846ccc9-a2fa-479b-b819-3839192072e2)
![Screenshot_deepin-terminal_20240626183411](https://github.com/linuxdeepin/developer-center/assets/96415804/d6f17f24-ed7e-42c3-b912-b74b9eeb3f35)

### EXPECTED RESULT | 期望的结果

1.ll-cli enter可以成功进入容器

**Comment by babyfengfjx** [comment]
@dengbo11  请安排优化~

**Comment by vivianxf** [comment]
验证镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240722/
验证仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1785/testing/ ./
linglong-bin:1.5.8-1
验证步骤：提单的步骤
验证现象：ll-cli enter id ，可以进入相关应用容器内
验证结果：通过
