### ISSUE TITLE
Compiz on archdeepin

### ISSUE THREAD

**Issue by antechdesigns** [linuxdeepin/developer-center#946]
I installed compiz on my archdeepin ISO just to test it out, I was quite surprised at the results ;)

Whilst most things seem to work I have a few bugs that I'd like help with.

1. dock - if I right click an icon in the dock the pop up menu is to far away from the dock, like it has some sort of padding/margin

![screenshot from 2019-02-26 11-28-26](https://user-images.githubusercontent.com/29888048/53409776-c77b7280-39b9-11e9-94bb-aae638159bbb.png)

2. dock - thumbnail previews hovering over a minimised icon in the dock doesn't show the thumbnail in the pop up, if I enable ( Keep previews of minimised windows ) in ( workarounds ) it works but introduces another bug, were if I minimise the browser ( chromium or firefox ) its like the browser is still on the desktop even though its minimised. 

Compiz on archdeepin: https://youtu.be/-piX6UfJ7es

I know compiz is not officially supported in deepin but any help would be appreciated!!

Thanks in advance
Ant

**Comment by antechdesigns** [comment]
As suspected there is a padding when using metacity WM, any way of removing it?
If you change from deepin-wm to metacity you can see the padding for a split second when it changes. (dark border around the window)

Thanks
Ant

**Comment by felixonmars** [comment]
IIRC this is part of an incomplete implementation. @sonald and @zccrs may have a better idea here.

**Comment by antechdesigns** [comment]
Thanks for the reply @felixonmars Hopefully @sonald or @zccrs will shed some light on the situation ;)

**Comment by antechdesigns** [comment]
![deepinscreenshot_deepin-terminal_20190301104235](https://user-images.githubusercontent.com/29888048/53633273-ed4d8500-3c0e-11e9-8895-ce7789ee76f8.png)

After more research looks like its the shadows bounding box that's causing the problem when using Metacity, I think?

Anyway to turn them off??

@felixonmars @sonald @zccrs

**Comment by zccrs** [comment]
Maybe you can use kwin, We will support it in the near future.

**Comment by antechdesigns** [comment]
> Maybe you can use kwin, We will support it in the near future.

@zccrs not sure how this removes shadows from the deepin apps?
