### ISSUE TITLE
【deepin_V23_Release】【严重】【有空】【内测反馈】【DDE】【launchpad】【低概率偶现】拖动图标翻页 或者 拖动图标新建页 多次重复 拖动到任意位置时，启动器显示空白

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#9463]
### SUMMARY | 问题概要

![image](https://github.com/linuxdeepin/developer-center/assets/96416089/f3e3c7c1-f0a7-46d1-a966-20045dac772f)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://cdimage.uniontech.com/community/releases/23-RC2/amd64/deepin-desktop-community-23-RC2-amd64.iso
dde-launchpad 0.7.3
```

### STEPS TO REPRODUCE | 复现步骤

拖动图标翻页 或者 拖动图标新建页 多次重复 拖动到任意位置

### OBSERVED RESULT | 观察到的结果

启动器显示空白
![录屏_选择区域_20240627144510](https://github.com/linuxdeepin/developer-center/assets/96416089/5a43b4e2-563c-4f39-a6ca-84a6865d0ab3)

### EXPECTED RESULT | 期望的结果

能够拖动到任意位置，且启动器显示正常

**Comment by babyfengfjx** [comment]
@kegechen  请安排优化~

**Comment by luodeepin** [comment]
转PMS跟踪：https://pms.uniontech.com/bug-view-271297.html
