### ISSUE TITLE
Deepin image viewer info dialog doesn't resize with main window

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#947]
## Describe the bug
Deepin image viewer info dialog doesn't resize with main window.

## To Reproduce
1. Open Deepin image viewer info dialog
2. Resize window

## Expected behavior
Deepin image viewer window resize should also trigger info panel resize

## Screenshots
https://i.imgur.com/kXZSPn8.mp4

## Enviroments:
OS: Manjaro 18.0.3 Illyria
Kernel: x86_64 Linux 4.19.24-1-MANJARO
Shell: bash 5.0.0
DE: Deepin 15.9
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
bits: 64
compiler: gcc 8.2.1
tk: Qt 5.12.1
dm: LightDM

### Distro & Version
Manjaro Deepin 18.0.3

### Additional context
All Deepin versions: Linux Deepin, Arch Deepin, Manjaro Deepin, Fedora Deepin.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
