### ISSUE TITLE
【deepin_预览版】【严重】【立即】【集成测试】【treeland】终端点击右键菜单后，输入不了文字

### ISSUE THREAD

**Issue by baicailio** [linuxdeepin/developer-center#9473]
### SUMMARY | 问题概要

终端点击右键菜单后，输入不了文字
关联集成：#9457

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://packagesupdate.uniontech.com/repo/cdimage/deepin/23/v23-RC2-1
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1656:/dde/testing/ ./
```

### STEPS TO REPRODUCE | 复现步骤

点击终端的右键菜单，再在终端输入文字

### OBSERVED RESULT | 观察到的结果

点击终端的右键菜单，再在终端输入文字，输入不了
![image](https://github.com/linuxdeepin/developer-center/assets/166582166/50b72f92-c276-4507-862e-3aab4bacf870)

### EXPECTED RESULT | 期望的结果

点击终端的右键菜单，再在终端输入文字，可以正常输入文字

**Comment by Groveer** [comment]
fixed in https://github.com/linuxdeepin/treeland/pull/346

**Comment by baicailio** [comment]
镜像：https://packagesupdate.uniontech.com/repo/cdimage/deepin/23/v23-RC2-1
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1656:/dde/testing/ ./
重装包：sudo apt install treeland libwaylib libqwlroots1 --reinstall
验证步骤：提单步骤
验证现象：点击窗口的右键菜单后，在终端可以输入文字
验证结果：回归通过
