### ISSUE TITLE
【deepin_预览版】【一般】【立即】【集成测试】【treeland】任务栏应用的右键菜单显示在窗口顶部

### ISSUE THREAD

**Issue by baicailio** [linuxdeepin/developer-center#9477]
### SUMMARY | 问题概要

任务栏应用的右键菜单显示在窗口顶部
关联集成：#9457

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://packagesupdate.uniontech.com/repo/cdimage/deepin/23/v23-RC2-1
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1656:/dde/testing/ ./
```

### STEPS TO REPRODUCE | 复现步骤

点击任务栏应用的右键菜单

### OBSERVED RESULT | 观察到的结果

任务栏应用的右键菜单显示在窗口顶部
![image](https://github.com/linuxdeepin/developer-center/assets/166582166/28160228-1b79-4c16-a30f-0431f834fff2)

### EXPECTED RESULT | 期望的结果

任务栏应用的右键菜单显示在任务栏

**Comment by Groveer** [comment]
同https://github.com/linuxdeepin/developer-center/issues/9484

**Comment by babyfengfjx** [comment]
@Groveer 请安排优化~

**Comment by Groveer** [comment]
fixed: https://github.com/linuxdeepin/treeland/pull/349

**Comment by baicailio** [comment]
镜像：https://packagesupdate.uniontech.com/repo/cdimage/deepin/23/v23-RC2-1
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1656:/dde/testing/ ./
重装包：sudo apt install treeland libwaylib libqwlroots1 --reinstall
验证步骤：提单步骤
验证现象：任务栏右键菜单打开显示正常
验证结果：回归通过
