### ISSUE TITLE
【deepin_预览版】【一般】【严重】【集成测试】【treeland】鼠标hover到任务栏，任务栏一直抖动

### ISSUE THREAD

**Issue by baicailio** [linuxdeepin/developer-center#9478]
### SUMMARY | 问题概要

鼠标hover到任务栏，任务栏一直抖动
关联集成：#9457
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://packagesupdate.uniontech.com/repo/cdimage/deepin/23/v23-RC2-1
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1656:/dde/testing/ ./
```

### STEPS TO REPRODUCE | 复现步骤

鼠标hover到任务栏

### OBSERVED RESULT | 观察到的结果

任务栏抖动
[video(84).zip](https://github.com/user-attachments/files/16023272/video.84.zip)

### EXPECTED RESULT | 期望的结果

鼠标hover任务栏，任务栏不抖动

**Comment by babyfengfjx** [comment]
@Groveer  请安排优化~

**Comment by baicailio** [comment]
镜像：https://cdimage.uniontech.com/community/releases/23/amd64/deepin-desktop-community-23-amd64.iso
升级到最新内测（0830）
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1793:/dde/testing/ ./
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1793:/commercial/testing/ ./
验证步骤：提单步骤
验证现象：任务栏不抖动
验证结论：验证通过
