### ISSUE TITLE
输入法崩溃以后自动重启的输入法无法用于奔溃前开启的wine程序

### ISSUE THREAD

**Issue by ihipop** [linuxdeepin/developer-center#948]
## 缺陷描述
输入法崩溃以后自动重启的输入法无法用于奔溃前开启的wine程序

## 复现步骤
正常开启deepin-wine程序，然后正常使用输入法，然后把 运行的好好的搜狗/fcitx用kill命令模拟他奔溃掉，然后 搜狗/fcitx 会自动恢复.然后会发现恢复的输入法不能用于奔溃前开启的deepin-wine程序（需要杀掉deepin-wine后重新开启），原生程序不受影响。

## 期望行为
和原生程序一致

### 发行版以及版本
当前使用  Deepin 15.9.1

### 相关的软件包版本
所有从我开始使用deepin开始的版本

### 其他内容

https://bbs.deepin.org/forum.php?mod=viewthread&tid=156019

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
