### ISSUE TITLE
【deepin_预览版】【一般】【立即】【集成测试】【treeland】选择文件，右键选择打开方式的菜单显示在了窗口的左上角

### ISSUE THREAD

**Issue by baicailio** [linuxdeepin/developer-center#9484]
### SUMMARY | 问题概要

选择文件，右键点击打开方式的菜单显示在了窗口的左上角
#9457

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://packagesupdate.uniontech.com/repo/cdimage/deepin/23/v23-RC2-1/amd64/deepin-desktop-community-23-RC2-amd64.iso
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1656:/dde/testing/ ./
```

### STEPS TO REPRODUCE | 复现步骤

选择一个文本文件，右键选择打开方式

### OBSERVED RESULT | 观察到的结果

选择打开方式后的菜单显示在了窗口左上角
![image](https://github.com/linuxdeepin/developer-center/assets/166582166/749a41ed-024a-4ac0-a279-ad3a5ec505c5)

### EXPECTED RESULT | 期望的结果

打开方式的菜单参考下图
![image](https://github.com/linuxdeepin/developer-center/assets/166582166/c9b9959d-e9ab-41ae-bc21-1d5ba66a5fee)

**Comment by babyfengfjx** [comment]
@Groveer  请安排优化~

**Comment by Groveer** [comment]
fixed: https://github.com/linuxdeepin/treeland/pull/349

**Comment by baicailio** [comment]
镜像：https://packagesupdate.uniontech.com/repo/cdimage/deepin/23/v23-RC2-1
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1656:/dde/testing/ ./
重装包：sudo apt install treeland libwaylib libqwlroots1 --reinstall
验证步骤：提单步骤
验证现象：应用右键菜单打开显示正常
验证结果：回归通过
