### ISSUE TITLE
[Feature Request] deepin store

### ISSUE THREAD

**Issue by ghost** [linuxdeepin/developer-center#949]
Hi ,could you add flathub applications to deepin store?

https://flathub.org/home

some important desktop environments have already implemented in their software centers , like Gnome (GNOME Software) and discover (KDE)

**Examples :** 
![45797149-9f008700-bc69-11e8-990e-8a04e8c5b2e5](https://user-images.githubusercontent.com/26883220/53544136-a6ff0580-3aea-11e9-814e-68b6345a5e72.png)

![gnome-software-source-drop-down-1024x723](https://user-images.githubusercontent.com/26883220/53544239-f9d8bd00-3aea-11e9-8873-658785fda76f.png)
![flatpaks-in-linux-mint-18 3](https://user-images.githubusercontent.com/26883220/53544296-31e00000-3aeb-11e9-9907-46f570b3ac54.png)

**Comment by alexwender1** [comment]
Great idea! And I go beyond... We must also include the AppImage applications in the store.

I think this is the best AppImage cataloger:
https://www.appimagehub.com/browse

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
