### ISSUE TITLE
【deepin_预览版】【一般】【立即】【集成测试】【treeland】窗口右键菜单选择移动至左右的工作区，实际窗口移动的工作区相反

### ISSUE THREAD

**Issue by baicailio** [linuxdeepin/developer-center#9490]
### SUMMARY | 问题概要

窗口右键菜单选择移动至左右的工作区，实际窗口移动的工作区相反
关联集成：#9457
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://packagesupdate.uniontech.com/repo/cdimage/deepin/23/v23-RC2-1/amd64/deepin-desktop-community-23-RC2-amd64.iso
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1656:/dde/testing/ ./
```

### STEPS TO REPRODUCE | 复现步骤

1.窗口右键菜单选择移动至左边的工作区，进入多任务视图查看
2.窗口右键菜单选择移动至右边的工作区，进入多任务视图查看

### OBSERVED RESULT | 观察到的结果

1.窗口右键菜单选择移动至左边的工作区，进入多任务视图查看，窗口被移动到了右边的工作区
2.窗口右键菜单选择移动至右边的工作区，进入多任务视图查看，窗口被移动到了左边的工作区
![image](https://github.com/linuxdeepin/developer-center/assets/166582166/bd9725a8-3c06-461a-b614-7118d745d518)

### EXPECTED RESULT | 期望的结果

1.窗口右键菜单选择移动至左边的工作区，进入多任务视图查看，窗口被移动到左边的工作区
2.窗口右键菜单选择移动至右边的工作区，进入多任务视图查看，窗口被移动到右边的工作区

**Comment by babyfengfjx** [comment]
@Groveer 请安排优化~

**Comment by zorowk** [comment]
https://github.com/linuxdeepin/treeland.private/commit/cd4604cb0c0d68978f049f7f7011b3f37f53a553

**Comment by baicailio** [comment]
镜像：https://cdimage.uniontech.com/community/releases/23/amd64/deepin-desktop-community-23-amd64.iso
升级到最新内测（0830）
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1793:/dde/testing/ ./
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1793:/commercial/testing/ ./
验证步骤：提单步骤
验证现象：窗口移动至左右工作区，按照预期结果移动
验证结论：验证通过
