### ISSUE TITLE
[archlinux]窗口焦点问题

### ISSUE THREAD

**Issue by kirigayakazushin** [linuxdeepin/developer-center#95]
如果有窗体，打开启动器以后，窗口会在最前，但是焦点在启动器。只有使用win键启动会有这个情况，鼠标点击启动器按钮则没有。
![20160530232513](https://cloud.githubusercontent.com/assets/12298476/15653176/d5d4295a-2650-11e6-838d-23aea3b4ee5f.png)
![20160530232520](https://cloud.githubusercontent.com/assets/12298476/15653177/d616bac2-2650-11e6-891a-6bf9b1874591.png)

**Comment by felixonmars** [comment]
可以试试切换到 2D 窗管还能不能重现。方法：运行 `deepin-metacity --replace`

**Comment by hualet** [comment]
@sonald 有没有可能是跟那个vala版本有关系？

**Comment by kirigayakazushin** [comment]
@felixonmars   2d下也是一样

**Comment by sonald** [comment]
不像，跟之前测试报的类似。应该是launcher启动app的问题，我在查

**Comment by sonald** [comment]
但是我无法重现。。。

**Comment by kirigayakazushin** [comment]
最新的一个问题是，，启动器这里焦点问题没事了，但是有些窗体的焦点就。。目前我发现的问题是鹦鹉螺和深度终端同时显示，直接用鼠标点击二者任意一个窗体，无法将点击的窗体移动到顶层，并有焦点，只能点击标题栏，不然焦点还是在当前的窗体上。

**Comment by sonald** [comment]
最近似乎反馈nautilus和深度终端同时出现就有焦点问题的有好几个，我正在追，但是还没发现诱因是什么

**Comment by deepinzhangshuang** [comment]
可能真与上游更新有些关系，因为一直用上游最新版本，好像没有这个问题？
 




------------------


武汉深之度科技有限公司
Wuhan Deepin Technology Co., Ltd.

　　张爽　　Island

手机：18771057362


武汉：武汉市光谷大道77号光谷金融港B18栋6楼 
北京：北京市海淀区知春路锦秋国际大厦B座501室
上海：上海市长宁区愚园路1258号15A01室


官网：www.deepin.org　　官博：深度操作系统


   
 

 
 
 
------------------ 原始邮件 ------------------
发件人: "Sian Cao"; 
发送时间: 2016年6月5日(星期天) 晚上8:24
收件人: "linuxdeepin/developer-center"; 
主题: Re: [linuxdeepin/developer-center] [archlinux]窗口焦点问题 (#95)

 


最近似乎反馈nautilus和深度终端同时出现就有焦点问题的有好几个，我正在追，但是还没发现诱因是什么
 
&mdash;
