### ISSUE TITLE
[Discussion] New addressbar / breadcrumbs style

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#952]
## Description
I've noticed Arch have updated with new changes to Deepin file manager's breadcrumbs.
Than have read internal discussion to understand some reasoning behind this changes...

I don't know, feels less intuitive and a little sloppy to me, i really liked windows-styled input breadcrumbs, it was more straight froward and intuitive.

Though i understand the need for rmb menu in case of breadcrumbs overflow, but in general that's one click more to start editing address (if you're that kind of person).

And main reason for change (as i understood from discussion) that it would be hard to drag window...
Old way was pretty good, since if you just press lmb and start moving even on top of input - it will drag & drop window.

If it's not set in stone yet and work in progress, maybe discussion of reasoning behind this changes is good, in case someone else also feels something weird about it, like me :)

**Comment by BLumia** [comment]
> main reason for change (as i understood from discussion) that it would be hard to drag window...

Actually the reason why it changed is, for the old design some user doesn't know they can drag the address bar to move the window.

> Old way was pretty good

I agree, so in fact there is a hidden config option to get the old behavior back. We would like to hear the voice from community about this design change, so keep an eye on it and let's see what will happened.

FYI the config file located at `~/.config/deepin/dde-file-manager.json`, and the config option is under `"GenericAttribute"`, add `"ShowCsdCrumbBarClickableArea": true,` and the behavior will changed after next time you launch the file manager.

For dde-file-manager users who found this thread, feel free to comment on this issue to let us know about your opinion :)

cc: @wangjia12

**Comment by keybreak** [comment]
> Actually the reason why it changed is, for the old design some user doesn't know they can drag the address bar to move the window.

Wow, really?
You had users that said they don't understant how to drag window?)
Werid, coz in all OSes i've seen it's pretty generic approach...

My personal first contact with Deepin file manager was "Let's try to drag with left icon...Cool, how about address bar? Cool!"

> I agree, so in fact there is a hidden config option to get the old behavior back.

Great, at least i'm not alone! :)

> We would like to hear the voice from community about this design change, so keep an eye on it and let's see what will happens.

Fair enough, though enforcing new behaviour in manner of updates maybe not the best way to test stuff for lots of users who already in love with Deepin ways of design / UI))

> That's why I think make the deepin design guideline public is a good idea.

Sure, now i see what you mean :)
Though, in my mind it's first questionable decision Deepin made to design, feels a little like duct tape)

Thank you for the config, i really appreciate it! :+1: 

In case people will find this new breadcrumbs better / more useful, i 'd propose couple of changes:
1. Have dropdown option in settings to switch it without config
2. If user have chosen Efficient mode after installation - keep the old way (more like Windows), if user chose Beautiful - keep new way (coz it's kinda Mac'y)

This level of initial config / control would resolve a lot of questions i think )

**Comment by keybreak** [comment]
Oh, and speaking of design - don't you guys ever dare to change double-click test cat in settings!! :smiley_cat: 
He's my best friend, now i'm never alone!! ))

**Comment by keybreak** [comment]
> I prefer the old style too.
Yeah, it would be preferable if you quote me or something as I do not have a Github account.

(c) **TerminalLinux** [Manjaro forums](https://forum.manjaro.org/t/deepin-hidden-features-design-discussion/78748/3)

**Comment by BLumia** [comment]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=175531

**Comment by keybreak** [comment]
Well, obviously just as with every change)

Still doesn't make a change better though! :smile_cat: 
Nothing will ever beat double-click full access to both addressbar and search, in my opinion)

Have you also created thread for discussion in international section?

**Comment by keybreak** [comment]
btw, as far as i understand someone asked to display not only icon of a disc but either hardware name like sda1 nvme0n1p1 or even name of a disk?

I believe that while the question is perfectly valid, solution of doing so would be too overkill, expecially in non-chinese languages it would eat too much of precious space, better compromise would be to have some notification on mouse-hover for quick look :)

Besides, again with previous design knowing your disk was a matter of double-click :laughing:

**Comment by wangjia12** [comment]
Thank you for your attention.
Each design will solve some problems and bring some problems to other people. We have chosen this option this time.
You can also post in the international  to let more people make suggestions. We hope to collect your suggestions.

**Comment by keybreak** [comment]
Here's international:
https://bbs.deepin.org/forum.php?mod=viewthread&tid=175734&page=1&extra=#pid567371

But regardless of public discussion, @wangjia12 please don't get me wrong, i respect your work and effort to please people that had some struggle with previous design (and there are a lot of your design proposals in internal discussion that i'm actually in love with)!

But still, as user & UI designer, i believe that:
- This is very radical change, which is actually step back and for the worse (because for me this was one of the most important "selling points" to use Deepin in the first place, since i use dde-file-manager a lot, and i really hate a lot of file managers on Linux that have it this non-effective, non-intuitive way)
- This also breaks core philosophy of Deepin design, which was pretty established for some years:
   1. Get best elements from all existing OS Worlds (Win / Mac / Linux)
   2. Simple
   3. Beautiful
   4. Effective
   I d' say here 1,3,4 is broken the way it is now.

- While we live in incredibly fast and social world, sometimes (actually a lot of times) it's better to leave untouched what's proven to be good, effective and beautiful just as it is (and i believe Deepin team knows this, judging even by the fact of moving to Debian stable) :smile_cat: Because it's really hard to please everyone, especially newcomers to tech world.

The most important things to consider, while making any change to such important component of the system - are asking two questions:
- Can i use it effectively **only** with keyboard?
   For both designs answer is yes, having **Ctrl**+**L** shortcut is a really good thing.
- Can i use it effectively **only** with mouse?
   1. For new design clearly answer is no, because you can't beat double-click access to both addressbar and search.
   2. Also with new design you need to **RMB click** - **Edit address**, which is two actions instead of one (and it's even harder because you have to use two different mouse buttons and choose menu - which causes some cognitive dissonance each time).
   3. One valid point - yes with new design it's easier to understand that blank drag area (at least if it's not overflown with breadcrumbs, then i'm sure there will be trouble for those who asked initial requests). But, is it really overweight all the previous points? Reasonable answer is strong no.

As i've stated before there could be only one good compormise to please everyone:
1. Have dropdown option in settings to switch between two options (while i argue that previous design should be default)
2. If user have chosen Efficient mode after installation - keep the old way (more like Windows), if user chose Fashion - keep new way (kinda Mac'y way)

But that way you'd probably have to do twice work for maintaining both variants...

**Comment by keybreak** [comment]
Also i've noticed that sadly it's really hard to get some opinions even in Linux world, outside of tech/dev community (doesn't matter if it's positive or negative).

Sadly majority of people are just going with the flow without any understanding of actually having a freedom of choise...
And it's also applicable for much more important things like privacy / mass-surveilance, what should we say about design desicions :crying_cat_face:

**Comment by BLumia** [comment]
> This is very radical change, which is actually step back and for the worse 

Although I prefer the old design, I still cannot tell which one is "bad" or not, and maybe we should know why there are around 50% of people in that thread think that's a good change. Nautilus removed the ability to enter address editing state too, I'm not sure but probably they got the same reason?

> Can i use it effectively only with mouse?

Ahh, the thing is, when you trying to enter some address, you probably always need to use the keyboard to do the input job :)

**Comment by keybreak** [comment]
> and maybe we should know why there are around 50% of people in that thread think that's a good change. Nautilus removed the ability to enter address editing state too, I'm not sure but probably they got the same reason?

While i'm not sure reality is 50%, but that's interesting point to check out Nautilus, let's try to find out reason for the change. Though, in general i'd argue to avoid Gnome's design desicions, because for years they was making UI for aliens, not for humans, so it's not good idea to follow them strictly :laughing: 

Quick search lead me only to same questions, like this one:
https://unix.stackexchange.com/questions/154106/show-address-bar-w-full-path-in-nautilus-instead-of-breadcrumbs-bar

Let's dig deeper. Do you know which version of Nautilus introduced this change?

> Ahh, the thing is, when you trying to enter some address, you probably always need to use the keyboard to do the input job :)

True, but it depends on the task, if you need to copy or paste new path you can still use mouse (though yeah, most of people probably will use **CTRL**+**C** / **CTRL**+**V**)

**Comment by keybreak** [comment]
They call it **path bar** here:
https://gitlab.gnome.org/GNOME/nautilus/blob/master/NEWS

Probably this one:
Major changes in 3.31.90:
* New path bar design that improves discoverability of buttons (Carlos Soriano)

Also, i've remembered that since Gnome started to use Wayland there was a time, when they got some problems with existing elements (some dropdowns / inputs for example), because Wayland was too raw yet, probably reason for the change was caused by this purely technical problems?

**Comment by keybreak** [comment]
Look, they've actually stuck with the whole idea of implementing design of addressbar + breadcrumbs + search, and state as not possible. While Deepin and Windows had for long time:
https://askubuntu.com/questions/324064/use-path-bar-and-address-bar-in-nautilus

**Comment by BLumia** [comment]
I can totally understand why you don't like the new behavior and me nether, but when we talking about design philosophy, each designer may got very different idea about how things should works. Someone may like a design and someone may not. Their idea may not perfect suitable for everyone, so it's not reasonable to argue for change just because someone like you and me just don't like the design.

You don't need to prove something like "hey look, there are someone don't like the idea", I know that and that's why the config variable is there, but only a few people in our team complain about the design change and use that config variable to take the behavior back, so that's the major reason I really like to see what community think about this change.

But anyway, I can't make change just because there are people don't like it ( but hidden config variable is possible, since it doesn't need to let PM/designer know :D ). And there will be no more CSD titlebar if I can make the decision :)

> around 50%

Yeap, the result from that (Chinese) thread, and around 80% people in our team doesn't think the new design is bad (I am in that 20% though).

> double-click access to both addressbar and search.

DFM never got feature like double-click to enter address editing mode, for the old design, single click is okay, for new design, double click is for maximum the window, and it's part of the reason why they want to make the drag-able area larger.

Double-click on a crumb to enter editing mode sounds good though :)

> if you need to copy or paste new path or copy / cut parts of path, you can still use mouse.

"Edit address" is for that.

> Look, at least in Ubuntu fork...

Actually there are peoples doesn't like the new GNOME design at all, and there are some GNOME 2 fork  (like caja and nemo) which IMO is much better than the GNOME 3 one. But I still think they got enough. reason for their design.

**Comment by keybreak** [comment]
> Someone may like a design and someone may not. Their idea may not perfect suitable for everyone, so it's not reasonable to argue for change just because someone like you and me just don't like the design.

I agree with you, our collective goal is to get more data from people based on presented **plus** and **minus** arguments for the change (not all of which people may even think of / know in the first place from usability perspective). Who knows, maybe in the process something better will be proposed.
And preferably that should be prior to actually making change (on proposal stage) :smile: 

> You don't need to prove something like "hey look, there are someone don't like the idea"

Believe me, i'd love not do this, but the guy i've quoted here from Manjaro forum was the ONLY one who actually told his opinion everywhere i've asked for international auditory except you and me (Manjaro / Deepin forums, here).
Actually it's really good to see that chinese side of Deepin forum are much more active! :smiley_cat: 

> And there will be no more CSD titlebar if I can make the decision :)

Wow, really? Just for the interest, can i ask why? I thought that it's what really revolutionized Deepin programs design :smile: 

> Double-click on a crumb to enter editing mode sounds good though :)

Now that is actually a really good idea if you will stick to new design! (sorry i previously misused, and meant single-click to enter edit mode for previous design)

> But I still think they got enough. reason for their design.

Wish we could know precise reasons, because lot of their designs is hated by a lot of people))

P.S. Please take a look at gitter, there's a guy from Manjaro Deepin forum asked if there's hidden config  for Settings to always open as initial state https://gitter.im/linuxdeepin/users

**Comment by es20490446e** [comment]
What about double clicking on the buttons to show the address bar?

**Comment by aiamuzz** [comment]
i agree with @keybreak  and @es20490446e  ...
yes double clicking the folder buttons providing access to editable address bar is the most simple of all them ...

**Comment by keybreak** [comment]
Well, technically i've meant the whole addressbar.
Breadcrumbs are buttons in addressbar, which represent device / folders :smiley:

**Comment by BLumia** [comment]
> Just for the interest, can i ask why?

I prefer: https://www.haiku-os.org/docs/userguide/en/gui.html#stack-tile

> double clicking on the buttons to show the address bar?

Seems good but currently to busy to working on this, patches are welcome :)

**Comment by es20490446e** [comment]
I have a better suggestion, which is just to indicate the shortcuts for each menu option when you right click on the address-bar.

**Comment by keybreak** [comment]
@es20490446e 
What do you mean?

**Comment by es20490446e** [comment]
https://youtu.be/UeAr4J0TTxw

**Comment by aiamuzz** [comment]
> https://youtu.be/UeAr4J0TTxw

@es20490446e ... i think we can close this thread ... i've already opened this one here where what you seek is already part of the idea presented here ... https://github.com/linuxdeepin/developer-center/issues/928

**Comment by keybreak** [comment]
@es20490446e 
Well...I don't know, i think it would clutter interface, so i would vote against it.
Besides there is **Ctrl**+**Shit**+**?** in any Deepin program, which shows all shortcuts!

**Comment by es20490446e** [comment]
Features should be discoverable without external help, in the interface itself.

If putting shortcuts in the menus will clutter them, an alternative could be making the list of shortcuts more discoverable.

**Comment by aiamuzz** [comment]
> @es20490446e
> Well...I don't know, i think it would clutter interface, so i would vote against it.
> Besides there is **Ctrl**+**Shit**+**?** in any Deepin program, which shows all shortcuts!

yes we have that `Ctrl+Shift+?` 

but having it on the menu will still be the best way ... 
![image](https://user-images.githubusercontent.com/3283676/55790432-f701bc80-5ad9-11e9-964c-f290e779ee1f.png)

as you can see in Chrome's menu ... its more of a UI/UX **standard** ... i am sure @shule1987 ... can work his magic to make it visually appealing ...

**Comment by es20490446e** [comment]
Plus with "Ctrl+Shift+?", in the File Manager, I don't see the shortcut for typing right away into the address bar.

**Comment by aiamuzz** [comment]
> @es20490446e
> Well...I don't know, i think it would clutter interface, so i would vote against it.
> Besides there is **Ctrl**+**Shit**+**?** in any Deepin program, which shows all shortcuts!

one can only remember only so many shortcuts ... finding them contextually when the menu is invoked is far more efficient than have it all listed in one place ... `Ctrl+Shift+?` ... is an added bonus

**Comment by es20490446e** [comment]
Probably if shortcuts were on the menus, "Ctrl+Shift+?" won't be needed.

**Comment by keybreak** [comment]
Please, let's use more appropriate @aiamuzz thread for this discussion

**Comment by es20490446e** [comment]
I thought we were already there. Sorry!

**Comment by aiamuzz** [comment]
> Probably if shortcuts were on the menus, "Ctrl+Shift+?" won't be needed.

its a nice UI ... adds value to the whole transparent Deepin signature UI

We should view it as ... Keyboard complaince, and menu's with Shortcuts has been a standard much before Deepin was even conceptualized ... once that is achieved ... the `Ctrl+Shift+?` is the Deepin Signature touch ... so new users will get the time and tested standard way of operation as well as introduced to Special Deepin specific value additions !!!

**Comment by damian101** [comment]
I think a single click on the already active "folder button" in the path bar would be more intuitive than a double click on one of the folder buttons.
Anyway, one or both of these ways to edit the path bar should be implemented.
I myself didn't think at all of doing a right click on the path bar, so I thought editing the path bar wouldn't be possible at all.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
