### ISSUE TITLE
笔记本接外接屏幕时，锁屏、登陆等界面在两边屏幕均不显示

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#953]
第一次运行能看到界面控件一闪而过然后消失，只剩下模糊的背景。输入密码可以正常进入/解锁。
如果拔掉外接屏幕，则立刻恢复正常。

系统是 Arch Linux，dde-session-ui 在最新的 tag。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
