### ISSUE TITLE
20240702系统组件更新合并集成

### ISSUE THREAD

**Issue by UTsweetyfish** [linuxdeepin/developer-center#9536]
### package information | 软件包信息

本集成为以下集成的合并集成。

| 包名 | 原集成单 |
| -- | -- |
| whois | #9514 |
| thefuck | #9515 |
| screen | #9516 |
| sed | #9517 |
| osinfodb (**topic**) | #9518 |
| ostree | #9519 |
| json-c | #9520 |
| libfido2 | #9521 |
| json-glib | #9522 |
| iproute2 | #9523 |
| hwdata | #9524 |
| iptables | #9525 |
| geoip-database | #9526 |
| fish | #9527 |
| firewalld | #9528 |
| findutils | #9529 |
| ethtool | #9530 |
| extra-cmake-modules | #9531 |
| iso-codes | #9532 |
| iputils | #9533 |

### Package repository address | 软件包仓库地址

```
# whois https://github.com/linuxdeepin/developer-center/issues/9514
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1683/testing/ ./
# thefuck https://github.com/linuxdeepin/developer-center/issues/9515
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1684:/community/testing/ ./
# screen https://github.com/linuxdeepin/developer-center/issues/9516
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1686/testing/ ./
# sed https://github.com/linuxdeepin/developer-center/issues/9517
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1685/testing/ ./
# osinfodb https://github.com/linuxdeepin/developer-center/issues/9518
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1689/testing/ ./
# ostree https://github.com/linuxdeepin/developer-center/issues/9519
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1688/testing/ ./
# json-c https://github.com/linuxdeepin/developer-center/issues/9520
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1692/testing/ ./
# libfido2 https://github.com/linuxdeepin/developer-center/issues/9521
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1690/testing/ ./
# json-glib https://github.com/linuxdeepin/developer-center/issues/9522
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1691/testing/ ./
# iproute2 https://github.com/linuxdeepin/developer-center/issues/9523
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1695/testing/ ./
# hwdata https://github.com/linuxdeepin/developer-center/issues/9524
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1697/testing/ ./
# iptables https://github.com/linuxdeepin/developer-center/issues/9525
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1696/testing/ ./
# geoip-database https://github.com/linuxdeepin/developer-center/issues/9526
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1698/testing/ ./
# fish https://github.com/linuxdeepin/developer-center/issues/9527
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1699/testing/ ./
# firewalld https://github.com/linuxdeepin/developer-center/issues/9528
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1700/testing/ ./
# findutils https://github.com/linuxdeepin/developer-center/issues/9529
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1701/testing/ ./
# ethtool https://github.com/linuxdeepin/developer-center/issues/9530
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1703/testing/ ./
# extra-cmake-modules https://github.com/linuxdeepin/developer-center/issues/9531
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1702/testing/ ./
# iso-codes https://github.com/linuxdeepin/developer-center/issues/9532
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1694/testing/ ./
# iputils https://github.com/linuxdeepin/developer-center/issues/9533
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1693:/community/testing/ ./
```

### changelog | 更新信息

1. whois 更新至 5.5.23（.sc, .新加坡 (.xn--yfro4i67o, Singapore) 和 .சிங்கப்பூர் TLD 服务器）
2. thefuck 更新至 3.32-0.1
3. screen 更新至 4.9.1-1
4. sed 更新至 4.9-2
5. osinfo-db 更新至 20240701，并更新 osinfo-db-tools 与 libosinfo 至 1.11.0（virt-manager 数据源）
6. ostree 更新至 2024.6-1（建议测试升级、备份还原）
7. json-c 更新至 0.17-1（JSON 的 C 语言库）
8. libfido2 更新至 1.15.0-1（FIDO 认证库）
9. json-glib 更新至 1.8.0-2（json glib 库）
10. iproute2 更新至 6.9.0-1（命令行下 ip 命令、tc 命令等）
11. hwdata 更新至 0.383-1
12. iptables 更新至 1.8.10-4
13. geoip-database 更新至 20240403-1
14. fish 更新至 3.7.1-1
15. firewalld 更新至 2.1.2-1（防火墙）
16. findutils 更新至 4.10.0-2（find 命令、locate 命令）
17. ethtool 更新至 6.9-1（以太网工具）
18. extra-cmake-modules (ecm) 更新至 6.1.0-1（Cmake 开发库）
19. iso-codes 更新至 4.16.0-1（ISO 语言、货币数据）
20. iputils 更新至 20240117-1（ping、arping）

**Comment by babyfengfjx** [comment]
@kobe337  请开展集成验证。

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-RC2/
仓库：提测单仓库
内核：Linux deepin 6.6.36-amd64-desktop-hwe #23.01.00.29 SMP PREEMPT_DYNAMIC Tue Jul  2 13:48:43 CST 2024 x86_64 GNU/Linux

【结论】：
测试通过，暂无严重问题及影响，安装校验，版本核对，基本功能验证通过。
whois验证通过：
![whois](https://github.com/linuxdeepin/developer-center/assets/17869922/5412dd82-4fca-411d-97a2-4d1ca4ccf83d)
thefuck验证通过：
![thefuck](https://github.com/linuxdeepin/developer-center/assets/17869922/5f526ee0-1e6d-4b77-8597-0983c88aaeb6)
screen验证通过：

https://github.com/linuxdeepin/developer-center/assets/17869922/46d1c3c2-f0aa-4fd4-8dec-b870d7e8794d

**Comment by kobe337** [comment]
sed验证通过：
![sed](https://github.com/linuxdeepin/developer-center/assets/17869922/957b53f2-72a5-40f7-ba71-b9fd834ae5a4)
osinfodb验证通过：
![osinfo-db-tools2](https://github.com/linuxdeepin/developer-center/assets/17869922/34b0ea31-2100-47ec-981d-180c293ec39d)
ostree验证通过：通过控制中心升级验证通过

**Comment by kobe337** [comment]
json-c验证通过：
![json-c](https://github.com/linuxdeepin/developer-center/assets/17869922/6116d3eb-96e8-49a4-b0eb-a561343a2968)
libfido2验证通过：
![fido2-tools](https://github.com/linuxdeepin/developer-center/assets/17869922/85fe7b92-6723-4ae8-a83b-cba91fcf1039)
json-glib验证通过：
![json-glib-tools](https://github.com/linuxdeepin/developer-center/assets/17869922/ef8374e4-1598-4ef2-bcf8-5fedc7cf72a6)
iproute2验证通过：
![iproute2](https://github.com/linuxdeepin/developer-center/assets/17869922/49811e5b-7048-455d-ae4b-1ad299588f5c)
hwdata验证通过：
![hwdata](https://github.com/linuxdeepin/developer-center/assets/17869922/1a7cb867-641e-4020-bd65-e0ed6f9d369f)
iptables验证通过：
![iptables](https://github.com/linuxdeepin/developer-center/assets/17869922/2b62649d-69c1-493c-a6c7-125903de0d21)
geoip-database验证通过：
![geoip-databse](https://github.com/linuxdeepin/developer-center/assets/17869922/7b0675d9-dfc5-4ddb-9d29-03b5418c40d6)
fish验证通过：
![fish](https://github.com/linuxdeepin/developer-center/assets/17869922/728a0cfc-9850-4ae9-9270-adb4320fd233)
firewalld验证通过：
![firewalld](https://github.com/linuxdeepin/developer-center/assets/17869922/5ed24015-f6a2-41c1-aa42-d789397d9f94)

**Comment by kobe337** [comment]
findutils验证通过：
![findutils](https://github.com/linuxdeepin/developer-center/assets/17869922/d5d7cf31-cc5b-4f92-bf03-f4a7c8c5bd3d)
ethtool验证通过：
![ethtool](https://github.com/linuxdeepin/developer-center/assets/17869922/4e862ccf-ac58-46ed-881a-491c5a8570b2)
extra-cmake-modules验证通过：
![extra-cmake-modules](https://github.com/linuxdeepin/developer-center/assets/17869922/868b362f-9512-43d7-8cea-6ca598b4ddf3)
iso-codes验证通过：
![iso-codes](https://github.com/linuxdeepin/developer-center/assets/17869922/a43852bf-43f9-46f0-878c-b8b46485f55b)
iputils验证通过：
![iputils](https://github.com/linuxdeepin/developer-center/assets/17869922/232c5d28-c398-4fee-b18a-989eadc6e4e6)
