### ISSUE TITLE
[缺陷报告]系统屏幕缩放大于2.0时，DeepinWine - QQ、DeepinWine - TIM等无法正常使用

### ISSUE THREAD

**Issue by Playhi** [linuxdeepin/developer-center#954]
## 缺陷描述

系统缩放大于2.0时，QQ、TIM等打开后登录界面一闪而过，很平滑的出现了，又很平滑的滑走了。

## 复现步骤
复现步骤为:
1. 屏幕缩放设置到大于2.0；
2. 尝试运行 DeepinWine - QQ、DeepinWine - TIM等软件；
3. 登录界面很平滑的出现了，又很平滑的滑走了。

## 期望行为
正常使用

## 截图
无

## 复现环境:
屏幕缩放大于2.0

### 发行版以及版本
Deepin 15.9.1

### 相关的软件包版本
Deepin 15.9.1

### 其他内容
https://bbs.deepin.org/forum.php?mod=viewthread&tid=174547&page=1#pid559943
https://bbs.deepin.org/forum.php?mod=viewthread&tid=173425

**Comment by Playhi** [comment]
似乎直到现在仍然没有解决呢 :cry:

**Comment by lq95v5** [comment]
我测试过未复现，可以试试删除~/. deepin-wine下的wine qq和Tim 的文件夹试一下，操作前请先备份。

**Comment by Playhi** [comment]
> 我测试过未复现，可以试试删除~/. deepin-wine下的wine qq和Tim 的文件夹试一下，操作前请先备份。

还是不行，而且更新到15.10.1以后，禁用屏幕缩放也没用了 :cry: 

将Deepin给的QQ手动更新到最新版本QQ以后的话，密码框无法输入（不闪掉了），二维码无法加载（一直转圈圈），论坛搜的话，能发现最近还是有人提出过这个问题，估计特定环境下会爆出来，我另一台电脑没事，2.0+能正常使用。

> playhi@playhi-PC:\~$ /opt/deepinwine/apps/Deepin-QQ/run.sh
2019年 06月 20日 星期四 12:42:17 CST:Run Deepin-QQ 8.9.19983deepin23
2019年 06月 20日 星期四 12:42:17 CST:run Deepin-QQ progress pid 
Gtk-Message: 12:42:18.030: GtkDialog mapped without a transient parent. This is discouraged.
总用量 0
lrwxrwxrwx 1 playhi playhi 10 6月  20 12:42 c: -> ../drive_c
lrwxrwxrwx 1 playhi playhi 10 6月  20 12:38 com1 -> /dev/ttyS0
lrwxrwxrwx 1 playhi playhi 10 6月  20 12:38 com10 -> /dev/ttyS9
lrwxrwxrwx 1 playhi playhi 11 6月  20 12:38 com11 -> /dev/ttyS10
lrwxrwxrwx 1 playhi playhi 11 6月  20 12:38 com12 -> /dev/ttyS11
lrwxrwxrwx 1 playhi playhi 11 6月  20 12:38 com13 -> /dev/ttyS12
lrwxrwxrwx 1 playhi playhi 11 6月  20 12:38 com14 -> /dev/ttyS13
lrwxrwxrwx 1 playhi playhi 11 6月  20 12:38 com15 -> /dev/ttyS14
lrwxrwxrwx 1 playhi playhi 11 6月  20 12:38 com16 -> /dev/ttyS15
lrwxrwxrwx 1 playhi playhi 11 6月  20 12:38 com17 -> /dev/ttyS16
lrwxrwxrwx 1 playhi playhi 11 6月  20 12:38 com18 -> /dev/ttyS17
lrwxrwxrwx 1 playhi playhi 11 6月  20 12:38 com19 -> /dev/ttyS18
lrwxrwxrwx 1 playhi playhi 10 6月  20 12:38 com2 -> /dev/ttyS1
lrwxrwxrwx 1 playhi playhi 11 6月  20 12:38 com20 -> /dev/ttyS19
lrwxrwxrwx 1 playhi playhi 11 6月  20 12:38 com21 -> /dev/ttyS20
lrwxrwxrwx 1 playhi playhi 11 6月  20 12:38 com22 -> /dev/ttyS21
lrwxrwxrwx 1 playhi playhi 11 6月  20 12:38 com23 -> /dev/ttyS22
lrwxrwxrwx 1 playhi playhi 11 6月  20 12:38 com24 -> /dev/ttyS23
lrwxrwxrwx 1 playhi playhi 11 6月  20 12:38 com25 -> /dev/ttyS24
lrwxrwxrwx 1 playhi playhi 11 6月  20 12:38 com26 -> /dev/ttyS25
lrwxrwxrwx 1 playhi playhi 11 6月  20 12:38 com27 -> /dev/ttyS26
lrwxrwxrwx 1 playhi playhi 11 6月  20 12:38 com28 -> /dev/ttyS27
lrwxrwxrwx 1 playhi playhi 11 6月  20 12:38 com29 -> /dev/ttyS28
lrwxrwxrwx 1 playhi playhi 10 6月  20 12:38 com3 -> /dev/ttyS2
lrwxrwxrwx 1 playhi playhi 11 6月  20 12:38 com30 -> /dev/ttyS29
lrwxrwxrwx 1 playhi playhi 11 6月  20 12:38 com31 -> /dev/ttyS30
lrwxrwxrwx 1 playhi playhi 11 6月  20 12:38 com32 -> /dev/ttyS31
lrwxrwxrwx 1 playhi playhi 10 6月  20 12:38 com4 -> /dev/ttyS3
lrwxrwxrwx 1 playhi playhi 10 6月  20 12:38 com5 -> /dev/ttyS4
lrwxrwxrwx 1 playhi playhi 10 6月  20 12:38 com6 -> /dev/ttyS5
lrwxrwxrwx 1 playhi playhi 10 6月  20 12:38 com7 -> /dev/ttyS6
lrwxrwxrwx 1 playhi playhi 10 6月  20 12:38 com8 -> /dev/ttyS7
lrwxrwxrwx 1 playhi playhi 10 6月  20 12:38 com9 -> /dev/ttyS8
lrwxrwxrwx 1 playhi playhi 12 4月   7 23:08 d:: -> /dev/mmcblk1
lrwxrwxrwx 1 playhi playhi 23 6月  20 12:38 e: -> /media/playhi/9C33-6BBD
lrwxrwxrwx 1 playhi playhi 14 4月   7 23:08 e:: -> /dev/mmcblk1p1
lrwxrwxrwx 1 playhi playhi  1 6月  20 12:42 z: -> /
2019年 06月 20日 星期四 12:42:18 CST:CallApp Deepin-QQ  
2019年 06月 20日 星期四 12:42:18 CST:kill QQ.exe block
2019年 06月 20日 星期四 12:42:18 CST:No wine process found
2019年 06月 20日 星期四 12:42:18 CST:start running...
playhi@playhi-PC:\~$ wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine version: 2.18
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  4 (RenderCreatePicture)
  Serial number of failed request:  265
  Current serial number in output stream:  301
^C
playhi@playhi-PC:~$ 


无法正常使用的电脑的显卡驱动方案：
![image](https://user-images.githubusercontent.com/13196475/59819127-30b43680-9359-11e9-9256-92238caa3001.png)

**Comment by Playhi** [comment]
补充：我能正常运行的那边，不会出现这段

> X Error of failed request: BadMatch (invalid parameter attributes)
Major opcode of failed request: 139 (RENDER)
Minor opcode of failed request: 4 (RenderCreatePicture)
Serial number of failed request: 265
Current serial number in output stream: 301

我觉得大概和这有关系

**Comment by lq95v5** [comment]
@zccrs @felixonmars

**Comment by Playhi** [comment]
录屏感觉有点怪怪的，有需要的话我可以手机拍了再发一下
[a.zip](https://github.com/linuxdeepin/developer-center/files/3558464/a.zip)

**Comment by Playhi** [comment]
今天突然发现能用了！最近系统环境变更只有apt更新过最新版的deepin-wine、卸载了搜狗输入法换成了讯飞，不知道是deepin修好了还是搜狗的锅～[震惊]+[兴奋]

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
