### ISSUE TITLE
【deepin_预览版】【一般】【立即】【集成测试】【treeland】同一应用开启多个窗口，窗口完全重合了，没有错开排列效果

### ISSUE THREAD

**Issue by baicailio** [linuxdeepin/developer-center#9540]
### SUMMARY | 问题概要

同一应用开启多个窗口，窗口完全重合了，没有错开排列效果
关联集成：#9457

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://packagesupdate.uniontech.com/repo/cdimage/deepin/23/v23-RC2-1/amd64/deepin-desktop-community-23-RC2-amd64.iso
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1656:/dde/testing/ ./
```

### STEPS TO REPRODUCE | 复现步骤

终端新建多个窗口

### OBSERVED RESULT | 观察到的结果

从第二个窗口开始，窗口完全重合了，没有错开排列效果,下图左侧的窗口有3个完全重合了
![b8730c4ad0d658ec94be2cc9ef17f541](https://github.com/linuxdeepin/developer-center/assets/166582166/541ff70a-1eee-464a-a6c3-02c79f71a676)

### EXPECTED RESULT | 期望的结果

同一应用开启多个窗口，显示错开排列效果

**Comment by babyfengfjx** [comment]
@Groveer  请安排优化~

**Comment by baicailio** [comment]
镜像：https://cdimage.uniontech.com/community/releases/23/amd64/deepin-desktop-community-23-amd64.iso
升级到最新内测（0830）
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1793:/dde/testing/ ./
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1793:/commercial/testing/ ./
验证步骤：提单步骤
验证现象：同一个应用开启多个窗口，窗口有错开排列效果
验证结论：验证通过
