### ISSUE TITLE
[Deepin Integration]~[V23-release] 毕昇驱动提测

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#9547]
### package information | 软件包信息

 详情见附件

### Package repository address | 软件包仓库地址

```
deb [trusted=yes] https://ci.deepin.com/repo/deepin/deepin-community/driver/ driver non-free
```

### test suggestion | 测试建议
合入毕昇驱动包，请与项目组联系获取测试用例

**Comment by Zeno-sole** [comment]
[list.txt](https://github.com/user-attachments/files/16076766/list.txt)

**Comment by babyfengfjx** [comment]
@xuqi27837288  请跟研发获取具体测试建议，弄清楚该集成的相关内容，并开展集成验证。

**Comment by xuqi27837288** [comment]
![截图_dde-file-manager_20240704093320](https://github.com/linuxdeepin/developer-center/assets/62528742/1c0edb7c-9b30-4471-9a80-f5a23999abcb)

![截图_dde-printer_20240704093516](https://github.com/linuxdeepin/developer-center/assets/62528742/7a895c14-a04c-45f8-a7ae-b43929a67e32)

**Comment by xuqi27837288** [comment]
![截图_dde-file-manager_20240704133335](https://github.com/linuxdeepin/developer-center/assets/62528742/c9eb81fe-5c75-4962-bf40-e9202e1d13d2)

**Comment by xuqi27837288** [comment]
【验证环境】：v23 RC2镜像
镜像：https://cdimage.uniontech.com/community/releases/23-RC2/amd64/deepin-desktop-community-23-RC2-amd64.iso
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.35-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：集成测试通过
