### ISSUE TITLE
【deepin_V23_Release】【一般】【正常】【集成测试】【玲珑】重复执行“ll-builder create org.dde.demo”创建命令时，系统无任何提示

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#9555]
### SUMMARY | 问题概要

重复执行“ll-builder create org.dde.demo”创建命令时，系统无任何提示
关联集成： https://github.com/linuxdeepin/developer-center/issues/9534

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://cdimage.uniontech.com/community/releases/23-RC2/amd64/deepin-desktop-community-23-RC2-amd64.iso
linglong-bin:1.5.7
```

### STEPS TO REPRODUCE | 复现步骤

1.在终端多次执行：“ll-builder create org.dde.demo”创建命令
2.观察终端输出

### OBSERVED RESULT | 观察到的结果

1.同一目录下，多次提交创建，系统没有任何提示
![image](https://github.com/linuxdeepin/developer-center/assets/96415804/93d4868d-a866-48e0-88d7-003b1cfdc6ef)

根目录下创建也没有任何提示
![image](https://github.com/linuxdeepin/developer-center/assets/96415804/944261b6-2d9a-4991-85b5-fa00f0dd0d4c)

### EXPECTED RESULT | 期望的结果

1.同一目录下，多次提交创建，提示类似“重复的创建”，或者文件夹已存在时不允许重复创建

**Comment by babyfengfjx** [comment]
@dengbo11  请安排优化~

**Comment by vivianxf** [comment]
验证镜像：https://cdimage.uniontech.com/community/releases/23-RC2/amd64/deepin-desktop-community-23-RC2-amd64.iso
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1734:/community/testing/ ./
linglong-bin:1.5.8
验证步骤：提单的步骤
验证现象：重复提交同一创建，会提醒创建已经存在
验证结果：通过
![image](https://github.com/linuxdeepin/developer-center/assets/96415804/74de0fe6-95ec-4a05-ac0f-c01b321862f5)
