### ISSUE TITLE
【deepin_V23_Release】【一般】【正常】【集成测试】【玲珑】使用“ll-pica convert -c test.deb -w testname -b”转制应用时,目标目录下没有生成layer文件

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#9556]
### SUMMARY | 问题概要

使用“ll-pica convert -c test.deb -w testname -b”转制应用时,目标目录下没有生成layer文件
关联集成： https://github.com/linuxdeepin/developer-center/issues/9502

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://cdimage.uniontech.com/community/releases/23-RC2/amd64/deepin-desktop-community-23-RC2-amd64.iso
linglong-bin:1.5.7
linglong-pica：1.2.1
```

### STEPS TO REPRODUCE | 复现步骤

1.升级到最新版本玲珑环境
2.apt download com.baidu.baidunetdisk
3.ll-pica convert -c com.baidu.baidunetdisk_4.17.7_amd64.deb -w w -b
4.ls /w/package/com.baidu.baidunetdisk
5.查看目标目录下是否有.layer文件

### OBSERVED RESULT | 观察到的结果

1.使用“ll-pica convert -c test.deb -w testname -b”转制应用时,目标目录下没有生成layer文件
![-b](https://github.com/linuxdeepin/developer-center/assets/96415804/a56f4a8a-967a-4baf-bb33-eda34d383cac)

### EXPECTED RESULT | 期望的结果

1.使用“ll-pica convert -c test.deb -w testname -b”转制应用时,目标目录下生成layer文件，同步修改帮助文档信息
![image](https://github.com/linuxdeepin/developer-center/assets/96415804/09abfce9-e9d3-469e-afbe-b8284f62f2d5)

**Comment by babyfengfjx** [comment]
@dengbo11  请安排优化~

**Comment by dengbo11** [comment]
看是在pica增加另外一个参数导出uab, -b 参数还是导出layer文件

**Comment by vivianxf** [comment]
等修改完文档再回归

**Comment by chenchongbiao** [comment]
ll-pica convert -c com.baidu.baidunetdisk_4.17.7_amd64.deb -w w -b 默认构建导出 uab
ll-pica convert -c com.baidu.baidunetdisk_4.17.7_amd64.deb -w w -b --exportFile layer 构建导出 layer

**Comment by vivianxf** [comment]
验证镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240722/
验证仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1785/testing/ ./
linglong-bin:1.5.8-1
验证步骤：提单的步骤
验证现象：按照上述备注命令可以导出对应格式文件
验证结果：通过
