### ISSUE TITLE
Deepin file manager no hover states until next click, after drag & drop

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#956]
## Describe the bug
When Deepin file manager's window is dragged, right after this any icon / button on top panel have no hover states, until you click again anywhere on window.

## To Reproduce
1. Drag Deepin file manager window
2. Right after this try to hover any icon on top panel
3. Click anywhere on Deepin file manager window, to make hover active again

## Expected behavior
Should hover icons / buttons after drag & drop was finished, not after next click.

## Screenshots
https://i.imgur.com/EArmcX4.gifv

## Enviroments:
OS: Manjaro 18.0.3 Illyria
Kernel: x86_64 Linux 4.19.24-1-MANJARO
Shell: bash 5.0.0
DE: Deepin 15.9
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
bits: 64
compiler: gcc 8.2.1
tk: Qt 5.12.1
dm: LightDM

### Distro & Version
Manjaro Deepin 18.0.3

### Additional context
Test this on both real test-machines with Manjaro Deepin, on Arch Deepin VM and Linux Deepin VM.

**Comment by Iiari** [comment]
Verified here...

**Comment by antechdesigns** [comment]
Same here... arch deepin

**Comment by BLumia** [comment]
Did that only happened under deepin-wm? Tested with dde-kwin and works file here.

**Comment by antechdesigns** [comment]
Just done a new install of archdeepin file-manager seems fine now under deepin-wm 
deepin-system-monitor still has the bug

I will check deepin-kwin later unless someone confirms before then.

**Comment by keybreak** [comment]
@BLumia 
Yes, under **deepin-wm** happens from day 1 i'm using Deepin.
It happens only for deepin programs (with some exceptions, like deepin-movie is fine), usual qt / gtk programs are fine.

Under **deepin-kwin** i can only test Arch Deepin VirtualBox VM right now - but there it still happens for me..

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
