### ISSUE TITLE
Edge浏览器集成申请

### ISSUE THREAD

**Issue by myml** [linuxdeepin/developer-center#9566]
### package information | 软件包信息

com.browser.softedge.stable | 126.0.2592.68

### Package repository address | 软件包仓库地址

name: old url: http://repo-dev.cicd.getdeepin.org/

### changelog | 更新信息

更新edge浏览器为商店最新版本，修复输入法漏字母的问题

### test suggestion | 测试建议

1. 修改玲珑仓库，ll-cli repo modify http://repo-dev.cicd.getdeepin.org --name old
2. 安装或者更新 com.browser.softedge.stable
3. 启动后快速输入中文验证问题是否解决

### Sphere of influence | 影响范围

- https://github.com/linuxdeepin/developer-center/issues/9469

因为使用了商店最新版本的edge， 麻烦全面测试下功能

### ADDITIONAL INFORMATION | 额外补充

输入法漏字母的问题是由于gtk应用没有正确配置fctix插件导致的，目前不准备将gtk放到runtime中，所以在应用侧解决，需要一个一个的处理

**Comment by xuqi27837288** [comment]
【验证环境】：v23 RC2镜像
镜像：https://cdimage.uniontech.com/community/releases/23-RC2/amd64/deepin-desktop-community-23-RC2-amd64.iso
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.35-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：集成测试通过
