### ISSUE TITLE
Deepin editor incorrect encoding auto-detection

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#957]
## Describe the bug
Deepin editor changes file's encoding based on system language (most likely).

## To Reproduce
1. On machine which have russian system language, create and save file with Deepin editor: cyrillic encoding, UTF-8
2. Transfer this file with USB NTFS drive to another machine which have english system language
3. Open it with Deepin editor - it will open as ISO-8859-5 and will be unreadable, until you manually change it again to UTF-8 and resave

## Expected behavior
File should always open with encoding it was saved with, no matter what circumstances.

## Enviroments:
OS: Manjaro 18.0.3 Illyria
Kernel: x86_64 Linux 4.19.24-1-MANJARO
Shell: bash 5.0.0
DE: Deepin 15.9
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
bits: 64
compiler: gcc 8.2.1
tk: Qt 5.12.1
dm: LightDM

### Distro & Version
Manjaro Deepin 18.0.3

### Related package version
deepin-editor  1.2.6.3-1

**Comment by keybreak** [comment]
Also, it's most likely not connected, but still package is 
deepin-editor 1.2.6.3-1
but About page says 1.2.2

just as Deepin file manager as said in here https://github.com/linuxdeepin/developer-center/issues/899

So...Is it fair assumption that if program's about page says different versions from actual, that means it's not identical to vanilla deepin program versions already (even though it's small difference), and maybe some of Arch / Manjaro only bugs caused by some not so obvious inconsistencies?

**Comment by BLumia** [comment]
FYI plain text file itself does not save the information about which encoding which this file used, so we can only try to detect the encoding by reading and guessing. We give each of the possible encoding a weight, and the language which your system are using will affact the weighting. It's not possible to detect the encoding 100% correct :-/

And when we saying "detect", the editor itself doesn't "change" anything from the file, it just display the content with the encoding it detected, if it's not correct, choose the correct one is okay, and you also do not need to re-save it since the file itself does not changed at all :)

**Comment by keybreak** [comment]
@BLumia 
Oh wait, so you're saying on Linux not saving plain text with encoding is a rule of thumb, or is it Deepin editor design choise?

This way surely it's not possible to 100% auto-detect encoding correctly...
Do you think that's wise approach?

I can only guess, that's made to be so it wouldn't ruin file unreadable permanently (like on Windows if you choose really wrong encoding and save)

My example file also have pretty mixed content...

Problem is that same file opened with Gedit, Kate, Sublime Text, WPS Office, LibreOffice Writer...
Which says in my mind, even it's not bug technically now, at least it can be improved :)

**Comment by keybreak** [comment]
Also i've tested same scenario with only cyrillic characters file - it opens up with ISO-8859-5 and unreadable as well (kinda weird, since recepient machine system language is English, and it should be in this case lean towards something like UTF-8 or close)

P.S. I've also seen this encoding first time in my life, turns out it's really old tryout for encoding cyrillic symbols, which is not used for some technical reasons...

https://en.wikipedia.org/wiki/ISO/IEC_8859-5

> The 8-bit encodings KOI8-R and KOI8-U, CP866, and also Windows-1251 are far more commonly used. Another possible way to represent Cyrillic is Unicode.

**Comment by BLumia** [comment]
> Oh wait, so you're saying on Linux not saving encoding on plain text is a rule of thumb, or is it Deepin editor design choise?

Plain text file itself does not include any information about which encode the file is using (whatever OS you are using, but there are exception as well, like [BOM](https://en.wikipedia.org/wiki/Byte_order_mark)). It's not deepin's choise, it is the fact, otherwish it won't called "plain" :)

Use UTF-8 only is recommended, but if you found any file which the deepin-editor detected the wrong result, feel free to provide the file here and it can help us improve the encode detection algorithm.

**Comment by keybreak** [comment]
Ok, thank you for explanation)

Sure, please consider my observations & tests about cyrillic encodings wiki in post above:
http://mystore.to/dl/vq6PECFLUk

This file on system with English language should open jsut as system with Russian language as UTF-8 to be read correctly.

**Comment by BLumia** [comment]
Thx, could you update the issue title btw?

**Comment by keybreak** [comment]
Like so?

**Comment by keybreak** [comment]
Please note, that i by no means an expert in encodings and judge only based on end user human reaadability of simple text...

From what i've heard before: cyrillic, chinese, japanese encoding historically is pretty complicated matter, and some files (for example with scientific or special symbols, or mixed language can probably open incorrectly even with UTF-8, though it's clearly more advanced case, than my casual example)

So if you have someone who are an expert on cyrillic encoding, that would help a lot not to make some bad mistakes)

I knew one man who was an expert, but sadly he have passed not so long ago :(

**Comment by BLumia** [comment]
> ...can probably open incorrectly even with UTF-8

It's definitely a bug, we know that :)

**Comment by keybreak** [comment]
Also reported for polish language, thought you might need to know:
https://bbs.deepin.org/forum.php?mod=viewthread&tid=173143&extra=page%3D1

**Comment by BLumia** [comment]
Should be fixed now, please wait for next release or build by yourself :)

**Comment by keybreak** [comment]
@BLumia 
Thanks!

Once i'll test it in Arch & Manjaro i'll feedback :+1:

**Comment by keybreak** [comment]
Confirm, works now on Arch Deepin & Manjaro Deepin after 2019.04.04 update!

Thanks for good work! :smiley:
