### ISSUE TITLE
安装器 deepin-installer 6.0.59 集成

### ISSUE THREAD

**Issue by ArchieMeng** [linuxdeepin/developer-center#9575]
### package information | 软件包信息

deepin-installer 6.0.59

### Package repository address | 软件包仓库地址

https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/mengyutao/20240705/deepin-23-beige-rc2-amd64-20240705-164644.iso

### changelog | 更新信息

- https://github.com/linuxdeepin/developer-center/issues/9462
- https://github.com/linuxdeepin/developer-center/issues/9461
- https://github.com/linuxdeepin/developer-center/issues/8960

### test suggestion | 测试建议

参照Issue内容展开测试

### Sphere of influence | 影响范围

- 安装器应用程序（GUI进程）名称
- 安装器所有类型的语言选择默认选项
- 安装出错时，导出日志到移动硬盘的功能

### ADDITIONAL INFORMATION | 额外补充

关联vtoydump集成Issue，和导出日志到Ventoy盘的功能相关 https://github.com/linuxdeepin/developer-center/issues/9563

**Comment by babyfengfjx** [comment]
@xuqi27837288  请开展回归验证。

**Comment by xuqi27837288** [comment]
【验证环境】：v23 RC2镜像
镜像：https://cdimage.uniontech.com/community/releases/23-RC2/amd64/deepin-desktop-community-23-RC2-amd64.iso
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.35-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
