### ISSUE TITLE
更新在V23 rc2上出现的bisheng引擎不可用问题

### ISSUE THREAD

**Issue by yangkun0219** [linuxdeepin/developer-center#9580]
### package information | 软件包信息

bisheng-engine | 2.0.14-1
bisheng-engine-i386 | 2.0.14-1

### Package repository address | 软件包仓库地址

deb  [trusted=yes] https://aptly.uniontech.com/pkg/nonfree-apricot/release-candidate/44CQ5q-V5piH5byV5pOO44CR56S-5Yy654mI5Y2H57qnMjAyNC0wNy0wOCAwOTo1Njo0NQ/  unstable non-free

### changelog | 更新信息

解决 https://bbs.deepin.org/post/274660

### test suggestion | 测试建议

在v23 rc2上测试bisheng引擎，安装任意bisheng打印驱动后可正常打印到文件

### Sphere of influence | 影响范围

所有bisheng打印相关

**Comment by babyfengfjx** [comment]
@luodeepin  请开展集成验证，可以尝试联系用户让其反馈一下。
