### ISSUE TITLE
deepin-app-store  8.0.7.0003 集成申请

### ISSUE THREAD

**Issue by mhduiy** [linuxdeepin/developer-center#9587]
### package information | 软件包信息

包名|版本号
-|-
deepin-app-store|8.0.7.0003

### Package repository address | 软件包仓库地址

```bash
deb  [trusted=yes] https://aptly.uniontech.com/pkg/nonfree-beige-v2/release-candidate/56S-5Yy654mIVjIz5bqU55So5ZWG5bqXMjAyNC43Ljjmj5DmtYsyMDI0LTA3LTA4IDExOjIzOjA0/  unstable non-free
```

### changelog | 更新信息

- fix: 应用反馈上传图片时崩溃(Issue: https://github.com/linuxdeepin/developer-center/issues/9496)
- fix: 修复应用更新页面宽度最低时按钮显示不完整问题

### test suggestion | 测试建议

测试Issue：
- https://github.com/linuxdeepin/developer-center/issues/9496

### Sphere of influence | 影响范围

应用反馈时不会崩溃

### ADDITIONAL INFORMATION | 额外补充

需配合DTK集成进行测试：
- https://github.com/linuxdeepin/developer-center/issues/9584

**Comment by xuqi27837288** [comment]
【验证环境】：v23 RC2镜像
镜像：https://cdimage.uniontech.com/community/releases/23-RC2/amd64/deepin-desktop-community-23-RC2-amd64.iso
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.6.35-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
