### ISSUE TITLE
[Feature Request] Settings / Display - Advanced options (Color bit depth / Monitor bpc / per-monitor scaling)

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#959]
### Color bit depth
Ability to swtich 16 / 24 / 24+ bit on OS level, like on Windows / Mac.

This is very debatable, i understand that Linux **should** always force highest possible, especially i assume that Deepin with all it's transparnecy & blur wouldn't work at all if it wasn't 32 bit (Linux refers to as 24 bit, which is super confusing).

Why have it?
- In some rare cases Linux actually doesn't seem to force highest 24+ bit, which leads to noticeable postarization, gradient ladders, so this would be useful at least for the peace of mind to have this setting on OS level, at least to easily exclude all others things.
- Should be easier for end-user than bury yourself in configs / drivers etc
- Should be easier to determine if using 24 bit or 24 bit + 8 bit alpha, which now is really hard.

### Monitor bpc (bits per channel)
8 / 10 / 12 bpc

Important points for implementation:

- Should be persistent in some config file for all monitors used by PC

This is very important for some of designers / photographers, who happen to have professional monitors like NEC SpectraView. Now there's also a lot more consumer grade monitors and even TVs having 10-12 bits.

I know this is even harder request, and it could be done only in conjunction with video-driver manufactureres / maintaners, and most likely requires a lot of Linux software include even Deepin itself to evolve up to high bpc standarts.

Thing is that this is future, and this is how it must work on OS level even now, easy for all monitors! :)
This is one of things, that holds a lot of professionals to migrate Linux & probably also evolve Adobe products to Linux.

### per-monitor scaling
By default should use main scaling setting, but in case you have for example 4k laptop, which connected to normal dpi monitor, we should have an ability to set scaling separately.

Again, i know that this is super-hard in today's reality of drivers...But this is how we should work one day in Linux. Even Windows got it right, which is shame))

**Comment by KaKi87** [comment]
Hey, there's [another issue on dde-control-center ](https://github.com/linuxdeepin/dde-control-center/issues/84) for per-display scaling but totally inactive today so +1 for this issue, please someone give news ! Thanks

**Comment by KaKi87** [comment]
up
