### ISSUE TITLE
【deepin_V23_Release】【一般】【正常】【发散测试】【玲珑】arm架构下，ll-cli run 命令启动应用失败

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#9594]
### SUMMARY | 问题概要

arm架构下，ll-cli run 命令启动应用失败

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://cdimage.uniontech.com/community/releases/23-RC2/arm64/deepin-desktop-community-23-preview-arm64.iso
```

### PRE-REQUIREMENT | 预置条件

arm架构安装以上镜像

### STEPS TO REPRODUCE | 复现步骤

1.ll-cli install linux.qq.com安装玲珑应用
2.ll-cli run linux.qq.com 运行玲珑应用

### OBSERVED RESULT | 观察到的结果

1.arm架构下，ll-cli run 命令启动应用失败

### EXPECTED RESULT | 期望的结果

1.arm架构下，ll-cli run 命令启动应用成功

**Comment by babyfengfjx** [comment]
@dengbo11  请安排优化~

**Comment by vivianxf** [comment]
layer的情况下会有这个问题

**Comment by vivianxf** [comment]
验证仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1785/testing/ ./
linglong-bin:1.5.8-1
验证步骤：提单的步骤
验证现象：arm架构下 ll-cli run 可以成功运行应用
验证结果：通过
