### ISSUE TITLE
[archlinux] UTC+00：00无法删除

### ISSUE THREAD

**Issue by kirigayakazushin** [linuxdeepin/developer-center#96]
![20160531144326](https://cloud.githubusercontent.com/assets/12298476/15665498/1310b2a4-26d1-11e6-9e27-7d5fa08bff93.png)
我看15.2的更新说明，已经修复这个问题了啊，，

**Comment by sbwtw** [comment]
删除 ~/.config/deepin/dde-control-center-datetime.conf 试试

**Comment by kirigayakazushin** [comment]
@sbwtw  ok了，删除这个文件搞定了。

**Comment by xflcx1991** [comment]
我从2015.1 dist-upgrade 升级到2015.2也遇到这个问题，不过重启后再选择东8区，然后就可以删除+0区了。
