### ISSUE TITLE
[Feature Request] Settings / Display - Color profiles

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#960]
### Color profiles (for each connected monitor separately)

- Ability to choose ICC profile
- Ability to add / load ICC profile
- Separate program to calibrate monitor (but this is really optional, since there are a lot of reliable software for this already, no real need for Deepin system-level program, maybe just GUI for some existent)

Important points for implementation:

- Default should be Monitor's own profile, if not chosen some other
- ICC profile should be persistent in some config file for all monitors used by PC

A really good example of implimentation and how it should work in Linux world is Linux Mint.

This is important system level feature for professional designers / photographers, should be reliable & easy to use.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
