### ISSUE TITLE
[Feature Request] Deepin image viewer / Settings

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#961]
### Window size
Dropdown:

- Normal
- Maximized
- Remember (Should restore previous state which include maximized state!)

Why:
Because if you like me, always after opening Deepin image viewer and then press maximized this is annoying and time-consuming as it is now.

### Window position
Dropdown:

- Normal
- Remember

Why:
Because sometimes you need to open iamge viewer with specific (non-fractional) size / position on screen, especially if it's big screen, and i want it to always reopen in same place and width & height.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
