### ISSUE TITLE
[Feature Request] Deepin image viewer - Image info

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#962]
### Image information
All images should have ( in rmb - **Image info** menu):

- File's ICC profile (if file doesn't have embedded ICC profile - should explicitly say **none**)
- File's Color depth (which is 8 / 16 / 32 bpc when you save it for example in Adobe Photoshop)

### Keyboard shortcut
Image info menu should also have keyboard shortcut (Something like **Ctrl**+**I** would be cool).

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
