### ISSUE TITLE
[Feature Request] Deepin image viewer - next / prev methods

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#963]
### Methods of next / prev picture
- Mouse side **next** / **prev** buttons
- **Ctrl**+**Mouse wheel** as stated here https://github.com/linuxdeepin/deepin-image-viewer/issues/20 but that's really optional hidden feature for those who like it also this way...

P.S. I was absolutely astonished to note, that mouse next / prev buttons are not implemented yet, this is absolute must for mouse only experience (equally as important, as having this in Deepin file manager, which we already have) - please make it happen! :)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
