### ISSUE TITLE
玲珑应用 com.qq.music 集成

### ISSUE THREAD

**Issue by kamiyadm** [linuxdeepin/developer-center#9632]
### package information | 软件包信息

com.qq.music| 1.1.5.3

### Package repository address | 软件包仓库地址

name: old url: http://repo-dev.cicd.getdeepin.org/

### test suggestion | 测试建议

修改玲珑仓库为开发仓库，ll-cli repo modify http://repo-dev.cicd.getdeepin.org --name old
安装或者更新 com.qq.music， 查看版本是否为1.1.5.3
运行应用，检查播放音乐是否有声音

### Sphere of influence | 影响范围

https://github.com/linuxdeepin/developer-center/issues/8780

**Comment by babyfengfjx** [comment]
@vivianxf  请开展集成验证。

**Comment by vivianxf** [comment]
layer文件地址：/media/vivian/smbmounts/smb-share:server=10.20.64.70,share=share/LXF/com.qq.music_1.1.5.1_x86_64_binary.layer
用户名：smbuser
密码：1

**Comment by vivianxf** [comment]
集成验证通过，请及时合入：

1.修改仓库成功，可以安装最新版本玲珑QQ音乐
2.QQ音乐正常播放声音，图标正常
3.提交的issue: #9645 不影响QQ音乐主体功能
4.玲珑基本能功能正常

综上所述，本次集成通过～

**Comment by Zeno-sole** [comment]
@kamiyadm  请推送完毕后走回来
