### ISSUE TITLE
[Feature Request] Deepin image viewer - files color depth (bpc) / .tiff support

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#964]
### Full support of files with all color depth (bpc)
- In Photoshop create and save image with Image - Mode - 8 / 16 / 32 bpc
A good example for test would be some colorfull image saved as:
1. .jpg 8 / 16 bpc
2. .png 8 / 16 bpc
3. .tiff 8 / 16 / 32 bpc

    In all cases images should look pretty much same as 8 bit original, opened in Deepin image viewer (no articacts, no serious color deviations etc.)

### .tiff support

- Should open all .tiff files (even though it says `This file contains multiple pages, please use Evince...` warning, not really true coz it also says so for single layered and it doesn't matter anyway)
- Deepin file manager should have previews for .tiff files, since it's image file

**Important note:**
Deepin image viewer should be powerfull instrument in all of the above cases, because may i say even old as hell Windows 7's photo viewer covers all the above cases, and Deepin image viewer sadly don't....Please, fix this :+1:

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
