### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【集成测试】【玲珑】ll-cli install com.qq.music安装应用时，模糊匹配安装了com.qq.music.linyaps

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#9645]
### SUMMARY | 问题概要

ll-cli install com.qq.music安装应用时，模糊匹配安装了com.qq.music.linyaps
关联集成：#9632

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://cdimage.uniontech.com/community/releases/23-RC2/amd64/deepin-desktop-community-23-RC2-amd64.iso
linglong-bin:1.5.8
```

### STEPS TO REPRODUCE | 复现步骤

在终端执行：
1.ll-cli install com.qq.music
2.安装成功后ll-cli list 观察列表展示

### OBSERVED RESULT | 观察到的结果

1.ll-cli install com.qq.music安装应用时，模糊匹配安装了com.qq.music.linyaps
![截图_deepin-terminal_20240710175804](https://github.com/linuxdeepin/developer-center/assets/96415804/d379d9a3-afe3-4280-9af2-769bd11c092e)

### EXPECTED RESULT | 期望的结果

1.执行ll-cli install com.qq.music,实际安装就是com.qq.music

**Comment by babyfengfjx** [comment]
@dengbo11  请进行优化~

**Comment by vivianxf** [comment]
验证镜像：https://cdimage.uniontech.com/community/releases/23-RC2/amd64/deepin-desktop-community-23-RC2-amd64.iso
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1746/testing/ ./
linglong-bin:1.5.8
验证步骤：提单的步骤
验证现象：ll-cli install com.qq.music安装应用时不会模糊匹配别的应用安装
验证结果：通过
![截图_dde-desktop_20240712132014](https://github.com/user-attachments/assets/d5a5497c-acf3-49b0-b981-2b2c60116d24)
