### ISSUE TITLE
[Feature Request] Deepin movie - DVD / BLU-RAY

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#965]
### DVD / BLU-RAY

- Full support for DVD / BLU-RAY playback
- Ability to manually choose disc / folder
- Support of interactive menus (Good implementation example on Linux is VLC)
- **Remember playback position** option should also remember DVD / BLU-RAY, not only works for files

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
