### ISSUE TITLE
[Feature Request] Deepin movie / Sound - Track

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#966]
### Sound - Track
Track choice should look like this:
- English (ac3, 48000 Hz, 5.1, 384 kb/s) [default]
- German (PCM, 44100 Hz, 2.0, 1411 kb/s)

Why:
Because now 90% of times on all of my tested files & movies sound tracks named like 'default', 'audio stream' which is non-sense.

Necessary parameters to make sensible choise of track should be: language, format, channels, quality.
Now it's more like trial and error :)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
