### ISSUE TITLE
【deepin_V23_Release】【一般】【正常】【集成测试】【玲珑】运行uab格式应用时，报/run/user/1000/linglong/monitor failed

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#9660]
### SUMMARY | 问题概要

运行uab格式应用时，报/run/user/1000/linglong/monitor failed
关联集成： #9651 

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://cdimage.uniontech.com/community/releases/23-RC2/amd64/deepin-desktop-community-23-RC2-amd64.iso
linglong-bin:1.5.8
```

### PRE-REQUIREMENT | 预置条件

系统安装linglong-builder

### STEPS TO REPRODUCE | 复现步骤

1.构建一个uab应用，并运行
ll-builder create org.dde.demo
cd org.dde.demo
ll-builder build
ll-builder export
./*.uab
2.观察运行结果

### OBSERVED RESULT | 观察到的结果

1.运行uab格式应用时，报/run/user/1000/linglong/monitor failed
![截图_org deepin browser_20240712135415](https://github.com/user-attachments/assets/32ccc0bd-8ee3-409e-9b28-4ec89f611669)

### EXPECTED RESULT | 期望的结果

1.1.运行uab格式应用时，没有报错

**Comment by babyfengfjx** [comment]
@dengbo11  请优先处理~

**Comment by vivianxf** [comment]
验证镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240715/
仓库：deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-1755/testing/ ./
验证步骤：提单的步骤
验证现象：直接运行uab格式文件没有关于/run/user/1000/linglong/monitor failed 报错
验证结果：通过
![截图_deepin-terminal_20240716141948](https://github.com/user-attachments/assets/91515bec-86df-4802-9743-f641a62a089f)
