### ISSUE TITLE
[Feature Request] Deepin movie - File info / Playback statistic

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#968]
### File info
- File info with all the technical & metadata of movie (good example of such info would be Windows MPC's MediaInfo)
- Should have design like **Deepin image viewer** RMB - Image info (Transparent side panel)
- Should have keyboard shortcut, for example **Ctrl**+**I**

### Playback statistic
- Realtime playback statistic: decoded, shown, skipped frame of audio & video, actual playback color depth (8 / 10 / 12 bit)
- Should have keyboard shortcut, for example **I**

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
