### ISSUE TITLE
UOS AI V1.3.1 集成请求

### ISSUE THREAD

**Issue by toberyan** [linuxdeepin/developer-center#9681]
### package information | 软件包信息

包名 | 版本
-- | --
uos ai | 1.3.2
deepin-ai-daemon | 1.1.0.22

### Package repository address | 软件包仓库地址

deb  [trusted=yes] https://aptly.uniontech.com/pkg/beige-v2/release-candidate/44CQVU9TIEFJ44CR5omT5YyF5rWL6K-V5Li76aKYLTEuMy0xLjRfMjAyNDA3MjAyNC0wNy0xMiAxMDo0NDoxMA/  unstable main

### changelog | 更新信息

为应用提供向量化数据能力，安装后，可使用UOS AI玩机助手、个人知识助手，全局搜索AI智能搜索等AI能力。
1、适配新任务栏样式

### test suggestion | 测试建议

1、验证新任务栏样式相关效果

### Sphere of influence | 影响范围

无

### ADDITIONAL INFORMATION | 额外补充

无

**Comment by babyfengfjx** [comment]
@luodeepin  请开展集成验证，确保插件基本功能和控制中心、任务栏显示功能正常。

**Comment by luodeepin** [comment]
https://pms.uniontech.com/bug-view-264789.html

**Comment by luodeepin** [comment]
测试不通过
1. 更新完成后，控制中心和任务栏上都没有uos-ai的图标
