### ISSUE TITLE
【deepin_V23_Release】【严重】【立即】【集成测试】【DDE】【任务栏】时间和显示桌面 重叠

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#9696]
### SUMMARY | 问题概要
https://github.com/linuxdeepin/developer-center/issues/9593
_No response_

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240715/deepin-23-beige-rc2-amd64-20240715-011014.iso
dde-shell 0.0.28
```

### STEPS TO REPRODUCE | 复现步骤

1. 新装镜像 -  进入系统 ， 查看任务栏 时间显示

### OBSERVED RESULT | 观察到的结果

时间和显示桌面 重叠
![截图_选择区域_20240715102516](https://github.com/user-attachments/assets/54427a4c-4273-487c-9e0d-cb74a7ceacd8)

### EXPECTED RESULT | 期望的结果

时间和显示桌面 不重叠

**Comment by babyfengfjx** [comment]
@yixinshark  请安排优化~

**Comment by yixinshark** [comment]
有重复单子。

**Comment by luodeepin** [comment]
验证失败
dde-launchpad 0.8.0
dde-shell 0.0.29
https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240722/deepin-23-beige-release-amd64-20240722-104051.iso

![截图_选择区域_20240723101217](https://github.com/user-attachments/assets/c681df0a-76d6-4130-9ef4-9a20bb294cb9)

**Comment by luodeepin** [comment]
验证通过
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240724/deepin-23-beige-release-amd64-20240724-184123.iso
dde-shell 0.0.30
dde-control-center 6.0.59
dde-launchpad 0.8.1

![截图_选择区域_20240725145118](https://github.com/user-attachments/assets/9074bc10-19fe-410d-9d72-7e3ef7106854)
