### ISSUE TITLE
Fresh 15.2 32bit installed, but nearly nothing will open, including the terminal

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/developer-center#97]
<a href="https://github.com/XC3me"><img src="https://avatars.githubusercontent.com/u/19862903?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @XC3me**
_Friday Jun 10, 2016 at 19:55 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/262_

----

I installed deepin 15.2 32bit twice but I'm having the same issue where chrome, firefox, the terminal and many other applications won't open, or close just after starting. When I tried running the driver manager, the error message i got was "Unable to copy the user's Xauthorization file."

I can open system settings, Deepin Music, the store and things like that.

Could my computer be just too weak to run deepin?

**Comment by fasheng** [comment]
I guess it's the `~/.Xauthority` issue, but dont't know why it occured, maybe related with the deepin-installer.

And please take some time to check the permission, user name and user group of .Xauthority(you could type such commands in a terminal or login and switch to a tty by pressing Ctrl-Alt-F6, Ctrl-Alt-F7 will come back to DDE):
```
ls -la ~/.Xauthority
xauth info
```

If the .Xauthority doesn't exists or owns the wrong permmission, please report it. And the solved method is:
```
mv .Xauthority old.Xauthority
xauth generate :0 . trusted
```
Then have a try again after re-login.

**Comment by XC3me** [comment]
Wow, that fixed it. That was a much simpler solution than I expected.
Thanks alot! I've gotta admit, Deepin is the most beautiful OS I've used yet.
It's also the fastest OS I've installed on this computer.

**Comment by fasheng** [comment]
Glade to hear it~
So `~/.Xauthority` exists before and just owns the wrong permission?

**Comment by fasheng** [comment]
我不清楚Xauthority导致应用程序无法启动的问题之前有没有遇到过，如果是文件权限错误导致的，可能和安装器有关，比如通过sudo配置samba、ssh。
@leaeasy @hualet

**Comment by hualet** [comment]
@snyh 遇到过吧？我刚才在想会不会是以前遇到的session内的进程都以root启动，导致这个文件权限不对，但是好像都只是读，没有写吧？

**Comment by snyh** [comment]
sudo 运行一些程序。　然后这些程序如果去读了　写了就会出问题呀。
什么程序导致的还真不知道。　　之前只遇到gconf被natuils给搞挂了。（因为修改配置的时候会进行写操作)
这个问题和之前的/var/lib/ligthdm/.XAuthority　可以统一用fixme的方式快速检测并修复过来。

**Comment by fasheng** [comment]
还有一个办法，如果定位不到原因，在最后把~/.XAuthority（如果存在）删除也可以。

**Comment by leaeasy** [comment]
直接用sudo跑会出现类似的问题
