### ISSUE TITLE
[Feature Request] Open / Save dialog - Window size

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#970]
### Window size
Should save window size globally for all Open / Save dialogs after close, like Deepin file manager does.

Why:
If you have big screen and wish to see way more files at once than default size - first thing you would do is make dialog bigger, but now you have to do this each time again & again, which is time consuming and frustrating.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
