### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【集成测试】【DDE】【任务栏】网络图标显示傍边多了个 点 或 感叹号

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#9700]
### SUMMARY | 问题概要

关联集成：https://github.com/linuxdeepin/developer-center/issues/9593

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240715/deepin-23-beige-rc2-amd64-20240715-011014.iso
dde-shell 0.0.28
```

### STEPS TO REPRODUCE | 复现步骤

1. 查看 网络图标显示 -  将任务栏位置设置为左 或 右 ， 查看网络图标显示

### OBSERVED RESULT | 观察到的结果

网络图标显示傍边多了个 点 或 感叹号
![截图_选择区域_20240715111258](https://github.com/user-attachments/assets/cc8954ea-0b1d-4752-b0c5-74e0fef57e33)

### EXPECTED RESULT | 期望的结果

网络图标显示正确

**Comment by babyfengfjx** [comment]
@yixinshark  请优先安排处理~

**Comment by yixinshark** [comment]
正在解决中。。。

**Comment by luodeepin** [comment]
验证通过
dde-shell: 0.0.29
https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240722/deepin-23-beige-release-amd64-20240722-104051.iso

![截图_选择区域_20240722151831](https://github.com/user-attachments/assets/1b4d5491-554f-46a1-b029-7dca38e15979)
