### ISSUE TITLE
【deepin_V23_Release】【严重】【立即】【集成测试】【DDE】【任务栏】将鼠标放置在部分插件（如：显示插件/声音和快捷面板/网络插件）上时 ，没有 tips提示

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#9720]
### SUMMARY | 问题概要

关联集成：https://github.com/linuxdeepin/developer-center/issues/9593

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240715/deepin-23-beige-rc2-amd64-20240715-011014.iso
dde-shell 0.0.28
控制中心 6.0.58
```

### STEPS TO REPRODUCE | 复现步骤

将鼠标放置在部分插件（如：显示插件/声音和快捷面板/网络插件）上插件tips提示

### OBSERVED RESULT | 观察到的结果

没有 tips提示
![录屏_选择区域_20240715134637](https://github.com/user-attachments/assets/3f014b07-dd0e-40fc-8dde-493f2827977f)

### EXPECTED RESULT | 期望的结果

tips提示显示正确

**Comment by babyfengfjx** [comment]
@yixinshark  请安排优化，应该是tips没弹出来 ![企业微信截图_17210218244211](https://github.com/user-attachments/assets/54a8bd9c-ad3d-4690-a5b9-7e80b9b839bf)

**Comment by 18202781743** [comment]
在图标区域,没有复现这个问题, 
边缘区域,不会有tooltip,

**Comment by luodeepin** [comment]
验证失败
部分插件没有tips提示
dde-launchpad 0.8.0
dde-shell 0.0.29
https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240722/deepin-23-beige-release-amd64-20240722-104051.iso

![录屏_选择区域_20240723093538](https://github.com/user-attachments/assets/ffb0bf44-d3d7-4acd-9f2e-de62fba45226)

**Comment by yixinshark** [comment]
请在7.24后的镜像之中验证。

**Comment by luodeepin** [comment]
验证失败
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240724/deepin-23-beige-release-amd64-20240724-184123.iso
dde-shell 0.0.30
dde-control-center 6.0.59
dde-launchpad 0.8.1

![录屏_选择区域_20240725143724](https://github.com/user-attachments/assets/746782bd-c1b2-4053-8788-530e6c6790da)

**Comment by luodeepin** [comment]
验证通过
https://github.com/linuxdeepin/developer-center/issues/9937
![录屏_选择区域_20240726102342](https://github.com/user-attachments/assets/4f129b23-35dd-48db-9c9c-6f4e93922383)
