### ISSUE TITLE
[BUG] Volume free space line indicator shows wrong value in deepin-file-manager

### ISSUE THREAD

**Issue by iamthevoid** [linuxdeepin/developer-center#974]
## Describe the bug
Looks like volume free space indicator shows wrong value despite of text representation is correct.

## To Reproduce
I'm not sure that I correct, but I think that the bug can be reproduced with copy-to-volume/remove-from-volume operations. Looks like indicator line based on first and last non-zero byte at volume, but not on the real fullness. 
1) open deepin-file-explorer
2) open "Computer" tab
3) select grid representation mode
4) there are volumes shortcuts in bottom of window with text and line representation of free space.
5) select volume to test (i saw this bug only at ntfs and exfat fs volumes, never at ext4, but i have no long experience, than maybe ext4-fs suitable too)
6) move to volume and delete from volume files with big size for better visibility
7) Line indicator under volume shortcut doesn't match text free space representation

## Expected behavior
Line indicator under volume shortcut matches text free space representation and also mathes real volume fullness

## Screenshots
![image](https://user-images.githubusercontent.com/10224366/53842091-900b5800-3faf-11e9-90e1-83d4feca4e02.png)

## Enviroments:
OS: Manjaro 18.0.3 Illyria
Kernel: x86_64 Linux 4.19.24-1-MANJARO
Resolution: 3840x2160 (scaling 200% is set in 'Display' block of 'settings' panel)
 DE: Deepin 15.9
 WM: Deepin WM
 WM Theme: Adapta-Eta-Maia
GTK Theme: Adapta-Eta-Maia [GTK2/3]
Icon Theme: deepin-dark

### Related package version
Deepin File Manager (deepin-file-manager) 1:4.7.6-2

**Comment by iamthevoid** [comment]
When i looked to screenshot i thought that it can be scaling problem. Because I see no round corners at edges of full line, but see these guys at yellow line. As if full line wider than the space for it.

**Comment by keybreak** [comment]
Confirmed on Manjaro Deepin VM, there's definetly some heavy leaning toward right side of line-indicator.

**Comment by keybreak** [comment]
Not as problematic as @iamthevoid case, but also pretty weird (it's ext4 system volume):
![Image of Yaktocat](https://i.imgur.com/kwwXN5V.png)

Looks like absolute 0, even though it's not...So it's confusing / not informative now :smile_cat:

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
