### ISSUE TITLE
[Bug] vs [Feature Request] Hot Corners require a LOT of pressure to activate

### ISSUE THREAD

**Issue by Iiari** [linuxdeepin/developer-center#976]
## Describe the bug
The hot corners in Deepin seem to require "pressure" applied "pushing" the cursor into the corner.  Even with the delay sent in dconf to 0, it takes effort and time to activate hot corner actions, especially viewing all windows.  It renders it almost unusable for me.  Decreasing (or eliminating) the pressure threshold or having it be a settings on-off option in the hotcorners menu would be great.  

## To Reproduce
Just the standard way hotcorners works...

## Expected behavior
I would like to just move the cursor into the corner and for the action to immediately happen without the "push" of the cursor into the corner to generate "pressure."  It sometimes registers, sometimes doesn't, and sometimes it registers it twice as I "push" so it undoes the action nearly as fast as it happens. 

## Screenshots
None
## Enviroments:
Deepin 19.3

### Distro & Version
Manjaro 18.0.3

### Related package version
??

### Additional context
KDE offers immediate hot corners if set that way.  Docks, like Plank or in the Budgie DE, offer in config sliders for Pressure vs no pressure being needed for actions.  The Budgie applet for hot corners also doesn't require pressure and is instantaneous.  Thank you for considering it!  Decreasing (or eliminating) the pressure threshold or having it be a settings on-off option in the hotcorners menu would be great.

**Comment by keeganmilsten** [comment]
I can concur! I actually like the current pressure it has, but I will attest to the fact that it requires more effort than most other DEs I have come across such as GNOME or even KDE

**Comment by keybreak** [comment]
I'm not user of this feature, but assume that best way out would be is to have this parameter customisable in Settings / some config file :yin_yang:

**Comment by axelmeunier** [comment]
Has this been fixed in the latest version of Deepin or is there any developement planned for the future ? This is refraining me from installing Deepin, as I use the window overview constantly. Thanks for any update.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
