### ISSUE TITLE
【deepin_V23_Release】【严重】【立即】【集成测试】【DDE】【任务栏】将鼠标放置在快捷面板中的 声音图标上右键点击静音后，声音没有静音且图标显示没变化

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#9761]
### SUMMARY | 问题概要

关联集成：https://github.com/linuxdeepin/developer-center/issues/9593

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240715/deepin-23-beige-rc2-amd64-20240715-011014.iso
dde-shell 0.0.28
控制中心 6.0.58
```

### PRE-REQUIREMENT | 预置条件
1. 当前设备有多个声音输出设备
_No response_

### STEPS TO REPRODUCE | 复现步骤

1. 打开控制中心 - 声音 - 切换输出设备
2. 打开快捷面板 - 鼠标右键点击 声音图标 ，选择静音

### OBSERVED RESULT | 观察到的结果

声音没有静音且图标显示没变化
![录屏_选择区域_20240716110356](https://github.com/user-attachments/assets/dc9c1854-e1f6-4b55-b59b-96f2ca0bc66a)

### EXPECTED RESULT | 期望的结果

声音静音，图标显示为静音图标

**Comment by babyfengfjx** [comment]
@yixinshark  请安排优先处理~

**Comment by yixinshark** [comment]
同样bug: https://github.com/linuxdeepin/developer-center/issues/9684

**Comment by yixinshark** [comment]
还有右键菜单没有更新：静音（执行后) -> 取消静音。

**Comment by yixinshark** [comment]
还要查看sink导出问题。

**Comment by fly602** [comment]
新版本暂无复现

**Comment by luodeepin** [comment]
验证通过
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240724/deepin-23-beige-release-amd64-20240724-184123.iso
dde-shell 0.0.30
dde-control-center 6.0.59
dde-launchpad 0.8.1

![录屏_选择区域_20240725140154](https://github.com/user-attachments/assets/4dcc75e8-d23b-4d8c-b819-e8f0c35d737e)
