### ISSUE TITLE
[BUG] Deepin Screenshot issue with 2 screens

### ISSUE THREAD

**Issue by saymoncoppi** [linuxdeepin/developer-center#977]
## Describe the bug
Hey guys!
Could you check this [bug](https://bbs.deepin.org/forum.php?mod=viewthread&tid=175109&page=1#pid563462), maybe the fix come faster :)
ALT + PrtSc Doesnt work whem we using 2 monitors.

https://bbs.deepin.org/forum.php?mod=viewthread&tid=175109&page=1#pid563462

I have other things to share about deepin screenshot. If someone from dev team wanna know , pls let me know.

See u guys!

**Comment by saymoncoppi** [comment]
Hello Guys!
thank you for everything you ve been doing!

I realise that we are missing something on the feature to get the active screen for an app like a Alt + PrtSc for MS Windows.
![image](https://user-images.githubusercontent.com/22059715/54499309-05035980-48ef-11e9-80bc-339f19f0dcaf.png)


I dont know if someone already ask this, but it doenst work at all.
The key shortcut is there but every call to  Screenshot tool returns the allscreen option or a selected area.
  
![image](https://user-images.githubusercontent.com/22059715/54499314-10ef1b80-48ef-11e9-866b-5346ec1d990f.png)

Another setting that i guess conveniente is how to setup the filename pattern.  
![image](https://user-images.githubusercontent.com/22059715/54499317-19dfed00-48ef-11e9-8c66-b4532e45768b.png)
  
I mentioning this bc in portuguese the name has spaces and I wanna decrease the file name lenght.

**Comment by saymoncoppi** [comment]
Wow! I discovered when this issue happens!!! Lucky...  Alt + PrtSc works perfectly when im using only one monitor.

When i wrote the last message i was at the office with extended screen. 

So thats the same, a litle BUG here.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
