### ISSUE TITLE
对非系统盘的.Trash-1000文件夹的疑问

### ISSUE THREAD

**Issue by lolimay** [linuxdeepin/developer-center#978]
使用VSCode不小心删除文件后，很自然地去回收站寻找被删除的文件，但意外地没有找到丢失的文件。网上的解释是在Linux系统挂载盘（非系统盘）中删除的文件会自动被移动到该盘根目录的`.Trash-1000/files`目录下，果然找到了被删除的文件。
我的想法的是，能不能把`.Trash-1000/files`中的文件映射到系统回收站（类似于软链接），从而能够让我们能够通过回收站直接管理在非系统盘中删除的文件，当被删除的文件被还原或被彻底删除后，也会删除`.Trash-1000/files`中对应的文件。

**Comment by BLumia** [comment]
深度文件管理器暂时没有完整的实现标准的回收站相关功能（实现不完整），按理说应该优先实现这些的其实。

以后应该会完善这方面的支持，近期大概还没有时间去做 :-/

cc @wangjia12

**Comment by lolimay** [comment]
谢谢回复，我会保持关注的 :)

**Comment by wangjia12** [comment]
> 深度文件管理器暂时没有完整的实现标准的回收站相关功能（当前的实现不完整），按理说应该优先实现这些的其实。
> 
> 以后应该会完善这方面的支持，近期大概还没有时间去做 :-/
> 
> cc @wangjia12

15.11你可以优先提出来，如果足够重要会延后一些功能开发的。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
