### ISSUE TITLE
[new-feature] Deepin Screenshot - Remember last folder

### ISSUE THREAD

**Issue by saymoncoppi** [linuxdeepin/developer-center#979]
Hi it's me again! I am a heavy user of Screenshot tool...
I'm doing a project doc and I should take a lot of screenshots. But its hard to rename each file and choose the right folder to save them.

If I select "Save at specific folder buttom" the tool allow me to t**ype a new file name** and **choose a folder**
So a hunble suggestion is: Why we dont could keep the last folder as a recent folder when i have to click again on "Save at specific folder buttom" ?

So this way the users doesnt need to click all path again to select the desired folder. He just type a new name if they want.

I guess its too easy bc you already keept the target folder as a recent path when we choose "Save automatically buttom"

If this trick make sense for you pls let me know

=) 
Best regards!

**Comment by wangjia12** [comment]
Thanks for your suggestion, it is a very good proposal, we will adopt it soon.
https://github.com/linuxdeepin/internal-discussion/issues/1144

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
