### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【DDE】【UI】快捷面板小模块hover 和press时的背景颜色不对

### ISSUE THREAD

**Issue by wangruoxuan3782** [linuxdeepin/developer-center#9799]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
dde-shell 0.0.28
```

### STEPS TO REPRODUCE | 复现步骤

打开快捷面板-hover小模块

### OBSERVED RESULT | 观察到的结果

hover和press时颜色显示不对
<img width="491" alt="image" src="https://github.com/user-attachments/assets/dc6d3c86-cb3b-4e9e-b9e6-00d9c81137cf">

### EXPECTED RESULT | 期望的结果

调整小模块hover、press时的效果
<img width="1641" alt="image" src="https://github.com/user-attachments/assets/4ca8e537-a7d4-4c62-a4ea-6f0331e4d2f3">

**Comment by yixinshark** [comment]
这个设计帮忙看看还有此问题吗

**Comment by wangruoxuan3782** [comment]
之前加了这个效果的，新的仓库上效果没了

**Comment by wangruoxuan3782** [comment]
UI已验证
