### ISSUE TITLE
(archlinux) dde-desktop icons visible on desktop after cutting...

### ISSUE THREAD

**Issue by mmetak** [linuxdeepin/developer-center#98]
It seems that ~/.config/deepin/dde-desktop.conf file is not being updated when files are moved from desktop.
How to reproduce:
- right click on desktop and create new folder
- right click on folder, click cut and paste it in file manager home folder for example
Now we get this new folder in home directory and there's still an icon left on the desktop.
When cutting files with file manager it works as it should.

https://bbs.archlinux.org/viewtopic.php?pid=1633976#p1633976

**Comment by fasheng** [comment]
Hi, metak, glade to see you :smiley:

**Comment by fasheng** [comment]
Yes, I reproduced it just now in archlinux, but works fine in deepin. I'm not sure the reasone because they owns the same version:
```
deepin-desktop 3.0.10-1 
deepin-daemon 3.0.16-1
```
I found that the source folder is still in "~/Desktop/" even it was cut to another place, not just a display issue, we could check it under terminal. So it looks really strange, any idae?
@hualet @sbwtw

**Comment by mmetak** [comment]
Hey fasheng. ;-) I'm mostly using i3wm and not dde, but I try to help out with deepin related issues on archlinux forum. Don't have any idea what could be causing this.

**Comment by hualet** [comment]
@fasheng @mmetak It's a bug of Nautilus 3.20+. I fixed it before on loognson, but forgot to merge it back to x86 version. :(

**Comment by fasheng** [comment]
:sweat_smile:

**Comment by manateelazycat** [comment]
@hualet This issue can close now?

**Comment by hualet** [comment]
It plays well with Deepin file manager, and since it's the default file manger of DDE now, we decided not to patch Nautilus.
