### ISSUE TITLE
[Bug] Unstable System Monitor

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#980]
## Describe the bug
System Monitor shows abnormal operation when using other Deepin Applications.
With System Monitor running... when opening Deepin Movie or Deepin Image Viewer; Monitor is closed suddenly.
When you leave the Movie or Image Viewer running, and try to open the System Monitor... it does not run. When you close the Movie or Image Viewer... the System Monitor opens normally.

## Screenshots
I recorded the screen showing the error (of the 2 ways described above).

[Screen Recorder.zip](https://github.com/linuxdeepin/developer-center/files/2948669/Screen.Recorder.zip)

### Distro & Version
Deepin 15.9.1

### Related package version
Deepin System Monitor 1.4.8.1-1
Deepin Movie 3.2.18 (Flatpak)
Deepin Image Viewer 1.3.8 (Flatpak)

### Additional context
@hualet asked me to install systemd-coredump and deepin-system-monitor-dbgsym, to collect the backtrace of the crash.
Since then, I'm having difficulty generating the backtrace; because I have no experience with it.

**Comment by BLumia** [comment]
Install the `systemd-coredump` and `deepin-system-monitor-dbgsym` package, and then reproduce this issue on your machine. After it crashed, run `coredumpctl info > coredump.log` and you will get `coredump.log`. Provide that file here is okay, and you can also run `coredumpctl info` to see the content directly to ensure you get the correct coredump info :)

**Comment by keybreak** [comment]
@BLumia 
For me it also crashes randomly sometimes on all Deepin editions, really hard to catch or make sense of what caused it :(

**Comment by alexwender1** [comment]
I will upload 4 files, corresponding to each error.

System Monitor is suddenly closed when opening the Deepin Movie:
[coredump.log](https://github.com/linuxdeepin/developer-center/files/2949541/coredump.log)

System Monitor is suddenly closed when opening the Deepin Image Viewer:
[coredump1.log](https://github.com/linuxdeepin/developer-center/files/2949544/coredump1.log)

System Monitor does not run with Deepin Movie running:
[coredump2.log](https://github.com/linuxdeepin/developer-center/files/2949545/coredump2.log)

System Monitor does not run with Deepin Image Viewer running:
[coredump3.log](https://github.com/linuxdeepin/developer-center/files/2949546/coredump3.log)

**Comment by alexwender1** [comment]
With Deepin Movie and Deepin Image Viewer NOT FLATPAK... The problem does not occur.

**Comment by hualet** [comment]
@alexwender1 what are the versions of those flatpk packages?
You can query that with `dpkg -l | grep -i fpapp`.

**Comment by hualet** [comment]
Oh, and the version of deepin-system-monitor of course, `apt policy deepin-system-monitor`.

And chould try run `deepin-system-monitor` in terminal, open Deepin Image Viewer or Deepin Movie to reproduce the problem,  and see if there's anything useful in the output?

**Comment by alexwender1** [comment]
> @alexwender1 what are the versions of those flatpk packages?
> You can query that with `dpkg -l | grep -i fpapp`.

Image Viewer 1.3.8
Movie 3.2.20 (updated yesterday)

![Captura de Tela_selecionar área_20190313095548](https://user-images.githubusercontent.com/45263160/54280519-79986a00-4576-11e9-9a25-d208ba0c7647.png)

**Comment by alexwender1** [comment]
> Oh, and the version of deepin-system-monitor of course, `apt policy deepin-system-monitor`.
> 
> And chould you try running `deepin-system-monitor` in terminal, open Deepin Image Viewer or Deepin Movie to reproduce the problem, and see if there's anything useful in the output?

The first capture is trying to run the System Monitor with the Image Viewer already running ... the second command is with the Movie.

The same problem occurs. System Monitor does not start running.

![Captura de Tela_selecionar área_20190313101013](https://user-images.githubusercontent.com/45263160/54281812-50c5a400-4579-11e9-8f43-874ac1fe0002.png)

In the second capture, the System Monitor is already running ... on the first command, the Image Viewer is executed; and as expected, System Monitor closes (the red marking only appears after the System Monitor closes).

On the second command, the Movie is played and the System Monitor closes again (the red mark appears after the System Monitor has suddenly closed).

![Captura de Tela_selecionar área_20190313101309](https://user-images.githubusercontent.com/45263160/54281820-54592b00-4579-11e9-9cd6-c16e9261eb7a.png)
