### ISSUE TITLE
【deepin_V23_Release】【一般】【有空】【内测反馈】【DDE】【launchpad】使用命令ll-cli install io.github.YesPlayMusic ，安装玲珑版Yesplaymusic，启动器中图标为锯齿图标

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#9801]
### SUMMARY | 问题概要

![image](https://github.com/user-attachments/assets/8b2d7ed1-09d1-47bf-beec-fe88f035f66c)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240715/deepin-23-beige-rc2-amd64-20240715-011014.iso
dde-shell 0.0.28
控制中心 6.0.58
```

### STEPS TO REPRODUCE | 复现步骤

1. 打开终端使用命令ll-cli install io.github.YesPlayMusic ，安装玲珑版Yesplaymusic -  在启动器中查看图标显示

### OBSERVED RESULT | 观察到的结果

启动器中图标为锯齿图标

![截图_选择区域_20240716152828](https://github.com/user-attachments/assets/c0955051-3ea8-4339-b7ee-335b1f4a8ae1)

### EXPECTED RESULT | 期望的结果

启动器中图标正常

**Comment by babyfengfjx** [comment]
@dengbo11  可以安排分析下看是打包的问题还是什么情况。

**Comment by luodeepin** [comment]
转PMS跟踪：https://pms.uniontech.com/bug-view-271281.html
