### ISSUE TITLE
多任务预览页面显示bug

### ISSUE THREAD

**Issue by CareF** [linuxdeepin/developer-center#981]
## 缺陷描述
只有激活的窗口会显示, 其他的都会以图标的形态出现在屏幕左上角外侧. 

## 复现步骤
点击 dock 上的多任务预览图标或者快捷键

## 期望行为
所在桌面上的各个窗口都应该排列在屏幕上

## 截图

![deepin-screen-recorder_Desktop_20190309181454](https://user-images.githubusercontent.com/11715538/54078524-7318a280-4297-11e9-81d0-2dd49482c595.gif)

### 发行版以及版本
Arch Linux 2019-03-09

**Comment by keybreak** [comment]
I also confirm this one.

Right now there's all kinds of bugs with this feature :(

Most likely it's also connected to https://github.com/linuxdeepin/developer-center/issues/973

**Comment by CareF** [comment]
问题仍然存在. 
The problem is still here.

**Comment by sonald** [comment]
[1.9.38](https://github.com/linuxdeepin/deepin-wm/pull/50) will release soon

**Comment by CareF** [comment]
It's fixed! 
撒花!
