### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【DDE】【任务栏/启动器】【UI】 任务栏内外描边无需跟随高分屏缩放

### ISSUE THREAD

**Issue by wangruoxuan3782** [linuxdeepin/developer-center#9811]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
dde-shell 0。0.28
```

### PRE-REQUIREMENT | 预置条件

3840*2160 2倍缩放

### STEPS TO REPRODUCE | 复现步骤

查看任务栏启动器描边

### OBSERVED RESULT | 观察到的结果

外描边明显比内描边粗
![image](https://github.com/user-attachments/assets/1726d4c7-3c69-455b-ba5d-9668a6210a33)

### EXPECTED RESULT | 期望的结果

内外描边保持1px，不跟随高分屏缩放

**Comment by babyfengfjx** [comment]
@yixinshark  请安排处理~

**Comment by mhduiy** [comment]
窗口外描边有多余像素 
![image](https://github.com/user-attachments/assets/fcb14ccf-aae1-4770-800e-091c27698e18)

**Comment by mhduiy** [comment]
Demo: 
[Demo.zip](https://github.com/user-attachments/files/16521262/Demo.zip)

**Comment by mhduiy** [comment]
外描边是窗管处理的，但是窗管无法复现Bug， 我们是稳定复现的， 手动修改了borderWidth为1, 理论上不会跟随屏幕进行缩放，待下次验证

**Comment by mhduiy** [comment]
窗管在此提交已经修复：

https://github.com/linuxdeepin/deepin-kwin/commit/c1600f5a6436e8198d61922d6487623f8937884d

**Comment by wangruoxuan3782** [comment]
UI已验证
窗管 4:5.27.2.207-deepin207-1
