### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【预发布测试】【DDE】【UI】 浏览器的图标在启动器和任务栏上显示错误

### ISSUE THREAD

**Issue by wangruoxuan3782** [linuxdeepin/developer-center#9812]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin-icon-theme 2024.07.10
```

### PRE-REQUIREMENT | 预置条件

3840*2160 1.5倍缩放

### STEPS TO REPRODUCE | 复现步骤

在任务栏和启动器查看浏览器图标

### OBSERVED RESULT | 观察到的结果

在任务栏和启动器查看浏览器图标
<img width="505" alt="image" src="https://github.com/user-attachments/assets/adc7ee52-2293-47c2-b93d-8f6970379aca">

### EXPECTED RESULT | 期望的结果

图标和窗口左上角的应用图标保持一致

**Comment by babyfengfjx** [comment]
@yixinshark  请安排优化~

**Comment by wangruoxuan3782** [comment]
dde-shell 0.0.31
UI已验证

**Comment by xuqi27837288** [comment]
【验证环境】：v23 RC2镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240729/
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.9.6-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
