### ISSUE TITLE
deb版本linglong 测试（debian 12 ）

### ISSUE THREAD

**Issue by kamiyadm** [linuxdeepin/developer-center#9822]
### package information | 软件包信息

linglong | 1.5.6-1

### Package repository address | 软件包仓库地址

deb [trusted=yes] https://download.opensuse.org/repositories/home:/kamiyadm/Debian_12/ .

### changelog | 更新信息

新增独立仓库, 为debian12提供linglong 的deb版本安装包

### test suggestion | 测试建议

1. 安装[debian 12](https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/)版本系统, 选择任意桌面环境的镜像，如gnome
2. 将独立仓库配置文件导入系统
`sudo bash -c "echo 'deb [trusted=yes] https://download.opensuse.org/repositories/home:/kamiyadm/Debian_12/ ./' > /etc/apt/sources.list.d/linglong.list"`
3. 更新仓库，并安装deb版本玲珑
`sudo apt update`
`sudo apt install linglong-bin`
4. 使用ll-cli 安装软件包，百度网盘和QQ
5. 测试软件包是否能正常启动

### ADDITIONAL INFORMATION | 额外补充

本次集成只用于验收迭代任务

**Comment by vivianxf** [comment]
验证通过：

1.按照建议步骤添加仓库，升级成功
2. 玲珑环境安装正常
3. qq,百度网盘玲珑版本应用安装成功
4. 正常运行，卸载，查询进程，杀掉进程
5. 基本功能正常

综上所述，本次集成通过~
