### ISSUE TITLE
最新版15.9 vscode使用过程中导致系统卡顿，再次点击其他应用程序导致系统注销

### ISSUE THREAD

**Issue by zazcoder** [linuxdeepin/developer-center#983]
最新版15.9 vscode使用过程中导致系统卡顿，再次点击其他应用程序导致系统注销，这不是某一个应用程序的问题，我之前也遇到过一次，是其他应用程序使用过程中导致系统卡顿，这是系统问题，不是程序问题

这个自动注销的行为很危险，如果码代码没保存，或者有没保存的文档或数据，那就惨了

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
