### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【集成测试】【DDE】【DTK】相册中的搜索框中 搜索图标和文字显示颜色不一致

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#9831]
### SUMMARY | 问题概要

关联单：https://pms.uniontech.com/bug-view-254125.html
![截图_选择区域_20240717154548](https://github.com/user-attachments/assets/e73cfe2e-340d-4e1c-a40b-000cd7cd8d12)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240715/deepin-23-beige-rc2-amd64-20240715-011014.iso
```

### STEPS TO REPRODUCE | 复现步骤

1. 打开相册 - 查看搜索框显示

### OBSERVED RESULT | 观察到的结果

搜索图标和文字显示颜色不一致
![截图_选择区域_20240717153104](https://github.com/user-attachments/assets/d6c0917d-f58e-4237-b55f-7815b77de0e6)

### EXPECTED RESULT | 期望的结果

搜索文本颜色与搜索图标颜色一致，且颜色需要 较深

**Comment by babyfengfjx** [comment]
@kegechen  可以安排处理~

**Comment by luodeepin** [comment]
转PMS跟踪：https://pms.uniontech.com/bug-view-271269.html
