### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by ghost** [linuxdeepin/developer-center#984]
A few features that I beleive would make it even better:

- Symlink a wallpaper folder in ``~/Pictures/wallpapers`` so we don't have to go to ``/usr/share/wallpapers/deepin``
- Add more default applications in the control panel (allow us to change default file editor) 
- Maybe start thinking about introducing a bespoke topbar that will fit in with the OS, showing program menus in the upper left corner, like macos (GTK)
- GTK theme for all the deepin applications, I currently use a mac theme, but that doesn't apply to deepin apps.
- Grouping icons in to folders in the menu:

<img src="https://www.maketecheasier.com/assets/uploads/2015/08/Launchpad-Featured.jpg">

**Comment by antechdesigns** [comment]
Put wallpapers in your home 
`.config/deepin/dde-daemon/appearance/custom-wallpapers`
 they will show up in wallpaper chooser, putting them in 
`/usr/share/wallpapers/deepin` 
will get overwritten if you get a deepin wallpaper update.

Totally agree with the theming, GTK/Deepin apps not matching, however its still the best looking DE for linux, I did read they are switching to kwin in the near future so hopefully that may change ;)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
