### ISSUE TITLE
Auto Scrolling Issue In File Manager. 

### ISSUE THREAD

**Issue by sarojpoudel33** [linuxdeepin/developer-center#985]

**Comment by sarojpoudel33** [comment]
[Scrolling Bug.mp4.zip](https://github.com/linuxdeepin/developer-center/files/2951642/Scrolling.Bug.mp4.zip)
@hualet @BLumia

**Comment by aiamuzz** [comment]
> Scrolling Bug.mp4.zip

@sarojpoudel33 ... downloading the zip file ... extracting ... and watching is too much of an overhead ...

You might want to record the screen using GIF format ... and add the gif file directly here ... we can watch it directly here without any overheads ...

**Comment by sarojpoudel33** [comment]
> > Scrolling Bug.mp4.zip
> 
> @sarojpoudel33 ... downloading the zip file ... extracting ... and watching is too much of an overhead ...
> 
> You might want to record the screen using GIF format ... and add the gif file directly here ... we can watch it directly here without any overheads ...

Sorry!  Next time i will make GIF.

**Comment by keybreak** [comment]
I confirm this, though you can actually pull back and then forward again to continue, but still it would be good to have more easy and smooth mouse-selection scroll, like in another file manager)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
