### ISSUE TITLE
Feature/Enchancement : Deepin File Manager ... address bar (path) easy access options !

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#986]
Hi,

Just upgraded the system with the latest release ... noticed you have withdrawn the ability to click on the address bar which would give us an editable field ... from where we could copy the path or paste a new path as a quick navigation option.

I also noticed that we could copy the path or select from the right click menu on the folder in the addressbar ... or select 'edit address' option ...

**Could you please add ... a mouse double click on the current folder label in the address bar along with a keyboard shortcut 'Alt+D' similar to the shortcut option  chrome or any other browser has to access the 'edit address' option ?**

**Comment by keybreak** [comment]
I assume you can also dive in discussion here https://github.com/linuxdeepin/developer-center/issues/952 :)

**Comment by BLumia** [comment]
`Ctrl+L` works for both firefox, chromium, (KDE) dolphin, (GNOME) nautilus, (Windows) explorer, and also works in dde-file-manager, so why `Alt+D`? btw you can always press `Ctrl + Shift + ?` to see all available shortcuts.

Feel free to let us know your opinion about this design change, and post your idea to #952 . Closing since this issue is duplicated with #952 ...

**Comment by aiamuzz** [comment]
@BLumia ... oh didn't know of the `Ctrl+L` worked on the browsers just like how `Alt+D` works ... i was used to `Alt+D`

So dde-file-manager works with Ctrl+L ... you might want to add Alt+D too just like how the browsers have 2 ways to do the same thing ... and moreover the `Alt+D` combination is a split second faster to invoke compared to `Ctrl+L` ... :smile: ...

Is there a way i can change `Ctrl+L` to `Alt+D` ... i guess dde-file-manager settings does not provide a way to edit its shorcuts ... any config file where i can do a dirty switch of the shortcut combination ?
