### ISSUE TITLE
All windows on the top-left corner of the screen in "exposè" mode

### ISSUE THREAD

**Issue by morrolinux** [linuxdeepin/developer-center#987]
Since a couple of weeks, when using the "all windows" or "exposè" view of the opened applications, all non-foreground windows are being placed outside of the screen so that I can't actually switch between them (see the attached gif)

### Distro & Version
Deepin Desktop Environment on Archlinux

### Related package version
deepin-desktop-base  2:2019.03.06-1
![Peek 11-03-2019 18-08](https://user-images.githubusercontent.com/20294254/54143073-5c09ba00-4429-11e9-98c3-cd3429a0127d.gif)

**Comment by BLumia** [comment]
#987

**Comment by sonald** [comment]
fixed in https://github.com/linuxdeepin/deepin-wm/pull/50
