### ISSUE TITLE
【deepin_V23_Release】【一般】【正常】【集成测试】【DDE】deepin ID登陆界面自动弹出，页面空白无内容展示

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#9870]
### SUMMARY | 问题概要

deepin ID登陆界面自动弹出，页面空白无内容展示
关联集成： #9860 

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240721/
```

### STEPS TO REPRODUCE | 复现步骤

1.更新系统到最新集成，正常使用
2.观察系统变化

### OBSERVED RESULT | 观察到的结果

1.deepin ID登陆界面自动弹出，页面空白无内容展示，随后又会自动消失
![截图_dde-desktop_20240722103910](https://github.com/user-attachments/assets/c72d2f9a-3f37-4693-9162-b0d6a1a12324)

### EXPECTED RESULT | 期望的结果

1.deepin ID登陆界面不会自动弹出

**Comment by babyfengfjx** [comment]
@myml  这个现象在开机启动时，网络未正常连接的时候会出现，看这块逻辑是不是有变化，理论上不应该每次启动时去弹这个框，即使不联网的情况下。

**Comment by myml** [comment]
deepinid客户端现在是dde组在解决

**Comment by vivianxf** [comment]
https://pms.uniontech.com/bug-view-271685.html
