### ISSUE TITLE
deb版本linglong 测试（openkylin 2.0rc)

### ISSUE THREAD

**Issue by kamiyadm** [linuxdeepin/developer-center#9872]
### package information | 软件包信息

linglong | 1.5.8-1 （实际代码版本1.5.6）

### Package repository address | 软件包仓库地址

deb [trusted=yes] https://ci.deepin.com/repo/obs/linglong:/multi_distro/openkylin2.0_repo/ ./

### test suggestion | 测试建议

1. 安装[openkylin 2.0rc](https://www.openkylin.top/downloads/index-en.html)版本系统
2. 将独立仓库配置文件导入系统
```sudo bash -c "echo 'deb [trusted=yes] https://ci.deepin.com/repo/obs/linglong:/multi_distro/openkylin2.0_repo/ ./' > /etc/apt/sources.list.d/linglong.list"```
3. 更新仓库，并安装deb版本玲珑
```sudo apt update```
```sudo apt install linglong-bin```
4. 使用ll-cli 安装软件包，百度网盘和QQ
5. 测试软件包是否能正常启动

### ADDITIONAL INFORMATION | 额外补充

本次集成仅用于验收迭代任务

**Comment by vivianxf** [comment]
集成验收通过：

1.安装对应系统，添加仓库成功
2.更新成功，玲珑安装成功
3.玲珑应用安装，运行，卸载成功
4.玲珑基本功能正常

综上所述，本次集成通过~
