### ISSUE TITLE
Control Center Broken

### ISSUE THREAD

**Issue by antechdesigns** [linuxdeepin/developer-center#988]
@felixonmars 

After latest update one of these pkgs has broken deepin-control-center:

efitools-1.9.2-1
gvfs-1.38.2-1
ldb-1:1.4.6-1
libwbclient-4.9.5-1
libxcomposite-0.4.5-1
libxcursor-1.2.0-1
libxdamage-1.1.5-1
smbclient-4.9.5-1
talloc-2.1.16-1
tdb-1.3.18-1
tevent-1:0.9.39-1

I’m guessing deepin control center needs rebuilding against one or more of those updates!?

Thanks
Ant

**Comment by keybreak** [comment]
Cofirm, for me after this updates:
![Image of Yaktocat](https://i.imgur.com/QfVoxIC.png)

I can't open settings at all after them, before it was fine.

**Comment by keybreak** [comment]
Cofirmed, after this updates Settings doesn't open at all:
![Image of Yaktocat](https://i.imgur.com/QfVoxIC.png)

**Comment by keybreak** [comment]
Confirmed, after this update i can't open Settings at all:
![Image of Yaktocat](https://i.imgur.com/QfVoxIC.png)

**Comment by LinuxUserGD** [comment]
Is there any workaround, e. g. open control center in terminal?

**Comment by keybreak** [comment]
Nope as far as i can see

**Comment by felixonmars** [comment]
Please try again with deepin-control-center-4.9.6-2.

**Comment by LinuxUserGD** [comment]
@felixonmars Where can I download it? I'm on Arch Linux (Antergos).

**Comment by felixonmars** [comment]
There is a "download from mirror" link on the package info page:
https://www.archlinux.org/packages/community/x86_64/deepin-control-center/

**Comment by antechdesigns** [comment]
That's fixed it!!
Thanks @felixonmars ;)

**Comment by keybreak** [comment]
Fixed, cool :)

**Comment by LinuxUserGD** [comment]
It's working now :+1:
