### ISSUE TITLE
【deepin_V23_Release】【严重】【立即】【集成测试】【DDE】【控制中心】控制中心登陆deepin ID后没有刷新账号登陆，并且无法再次点击登录

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#9891]
### SUMMARY | 问题概要

控制中心登陆deepin ID后没有刷新账号登陆，并且无法再次点击登录
关联集成： #9860

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
1.https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240722/
```

### PRE-REQUIREMENT | 预置条件

安装上述最新镜像

### STEPS TO REPRODUCE | 复现步骤

1.打开控制中心-deepin ID
2.登录deepin ID账号，观察是否刷新登录

### OBSERVED RESULT | 观察到的结果

1.控制中心登陆deepin ID后没有刷新账号登陆，并且无法再次点击登录

### EXPECTED RESULT | 期望的结果

1.控制中心登陆deepin ID后刷新账号登陆

**Comment by babyfengfjx** [comment]
@myml  请帮忙优先分析。

**Comment by myml** [comment]
deepinid客户端和控制中心的deepinid插件现在不是我负责，应该指派给dtk组的陈可

**Comment by babyfengfjx** [comment]
@vivianxf  这应该是由于被攻击后，后端服务出问题导致，目前应该已经恢复，再回归验证。

**Comment by vivianxf** [comment]
验证镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240724/
验证步骤：提单的步骤
验证结果：新版本问题不存在
![image](https://github.com/user-attachments/assets/2d5a6bd4-4cdc-4094-92f6-8c5d45b08165)
