### ISSUE TITLE
Arch Linux DDE weird behaviour of wm

### ISSUE THREAD

**Issue by ShellbackII** [linuxdeepin/developer-center#99]
Hello!

I have a little problem that is anoying me a little.

When I have more than one window open and click inside one that is not in focus, that window will have focus, I can use it like normal, but it does not rise up above other windows. The only way I have to raise it is to click on the titlebar of the windows. Only then will the window get raised.

I have tried to set different settings in dconf-editor without any success. I can though set focus to follow the mouse, and then windows will rise as fast I hoover the mouse over them, but that is not my prefered way.

I have also tried to make a new user, but still nothing different :(

Does anyone have a clue?

(if you whant more info/data, just ask ;)

**Comment by fasheng** [comment]
How about this:
```
gsettings set com.deepin.wrap.gnome.desktop.wm.preferences raise-on-click true
```

**Comment by felixonmars** [comment]
or something like https://github.com/linuxdeepin/developer-center/issues/95

**Comment by sonald** [comment]
It is weirder that it never occurs on my laptop, and there are so many focus problems since the gtk update. It may related to that.

**Comment by ShellbackII** [comment]
fasheng: That is one of those settings I have checked in dconf-editor. It is set to true, I have even tried to set it to false and back again to se if it changes anything but to no luck :(

felixonmars: I don't understand that page. Think that I'm missing support (and knowlege) of the language used.

**Comment by hualet** [comment]
Several users complained the focus issue to me on Telegram yesterday.

**Comment by felixonmars** [comment]
@ShellbackII You can try to switch to the 2D window manager, which some user used to workaround this.

**Comment by fasheng** [comment]
I must say, it's fine in my archlinux. Btw, I use the `deepin` gtk theme.

**Comment by felixonmars** [comment]
@fasheng It works fine at start, but could be weird after a certain amount of time. Still not sure what happened during the period.

**Comment by ShellbackII** [comment]
@felixonmars I have now tried to switch to deepin-metacity, but that didn't make any difference either I'm afraid :(

**Comment by sonald** [comment]
then It indicated that the focus problem is not related to mutter at all. it's deep down in the gtk probably.

**Comment by hualet** [comment]
@felixonmars  Have you seen similar issues reported to GNOME Shell ?

**Comment by felixonmars** [comment]
No as far as I know.

**Comment by ShellbackII** [comment]
The update of deepin-mutter to 3.20 arrived to me today, and with that the problem got solved.

Probably something with gtk and the previous version of the wm that didn't play well enough together. Anyway, problem solved!

**Comment by fasheng** [comment]
Great job!
