### ISSUE TITLE
【deepin_V23_Release】【严重】【立即】【集成测试】【DDE】【控制中心】控制中心登陆deepin ID后，有多余“未激活”提醒

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#9904]
### SUMMARY | 问题概要

控制中心登陆deepin ID后，有多余“未激活”提醒
关联集成：#9860

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
1.https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240722/
```

### STEPS TO REPRODUCE | 复现步骤

1.打开控制中心，登录deepin ID
2.观察登录后页面右上角的“？”提示

### OBSERVED RESULT | 观察到的结果

1.控制中心登陆deepin ID后，有多余“未激活”提醒
![企业微信截图_17217122609486](https://github.com/user-attachments/assets/60490577-3205-454e-b0b8-7b6774bf5f4c)

### EXPECTED RESULT | 期望的结果

1.控制中心登陆deepin ID后，没有多余提醒

**Comment by babyfengfjx** [comment]
@yixinshark  请安排优先处理~

**Comment by ArchieMeng** [comment]
@Zeno-sole 毙啦. /etc/deepin-version 香咗
![image](https://github.com/user-attachments/assets/e9b851b6-65f2-486e-8eaf-7631681cf2b2)

**Comment by vivianxf** [comment]
验证镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240724/
验证步骤：提单的步骤
验证结果：新版本问题不存在
![截图_dde-control-center_20240725155037](https://github.com/user-attachments/assets/2c2bfb8e-5df3-4927-b486-ee146ad5dc43)
