### ISSUE TITLE
Safety remove drives illegible / wrong icon variant in Settings notifications

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#991]
## Describe the bug
There's new type of notification for **Safely remove drives** in Settings, which have wrong black icon (or doesn't have apropriate variant yet?)

## Expected behavior
All other icons in notifications are big and colorfull, should have such variant for this action also). Now it's kinda illegible.

## Screenshots
![Image of Yaktocat](https://i.imgur.com/HHKOPvu.png)

## Enviroments:
OS: Manjaro 18.0.4 Illyria
Kernel: x86_64 Linux 4.19.28-1-MANJARO
Shell: bash 5.0.0
DE: Deepin 15.9.2
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
bits: 64
compiler: gcc 8.2.1
tk: Qt 5.12.1
dm: LightDM

### Distro & Version
Manjaro Deepin 18.0.4

### Additional context
It's same for Linux Deepin, Arch Deepin, Manjaro Deepin

**Comment by BLumia** [comment]
For your info this icon is from your icon theme, maybe @shule1987 would like to design a suitable icon for this request :joy:

**Comment by keybreak** [comment]
I know, but since themes i use are **deepin** and **deepin-dark** it would be logical to design those icons from start :laughing:

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
