### ISSUE TITLE
[Feature Request] Deepin file manager - System disk rename

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#992]
### System disk rename

System disk should also be renamable in Deepin file manager from default "System Disk".
For example, if i were to use it with non-english language, i would just want it to be renamed to SYSTEM.

**Comment by BLumia** [comment]
Other info:

Now actually we are treating "System Disk" as a virtual entry of user's system. And there are no standalone device item for `/home` partition even if `/home` is using different partition with `/`. So if we treat it as a virtual entrance of `/`, so we cannot let it display the label of `/` partition. Another thing is, if we treat it as a virtual entrance of `/`, the size of "System Disk" should probably also include the size of `/home`, but that can still be misleading.

cc @wangjia12

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
