### ISSUE TITLE
【deepin_V23_Release】【一般】【立即】【集成测试】【DDE】【任务栏】【偶现】企业微信收到消息时，鼠标放置到消息闪动的企业微信上，桌面闪烁 且消息弹框还跑到左上角

### ISSUE THREAD

**Issue by luodeepin** [linuxdeepin/developer-center#9922]
### SUMMARY | 问题概要

关联集成：https://github.com/linuxdeepin/developer-center/issues/9860

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
dde-launchpad  0.8.0
dde-shell 0.0.29
https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240722/deepin-23-beige-release-amd64-20240722-104051.iso
```

### STEPS TO REPRODUCE | 复现步骤

1. 企业微信收到消息时，鼠标放置到消息闪动的企业微信上

### OBSERVED RESULT | 观察到的结果

桌面闪烁 且消息弹框还跑到左上角
![录屏_选择区域_20240724093454](https://github.com/user-attachments/assets/b02e45ba-d8c8-4991-ba90-d66d43d41e12)

### EXPECTED RESULT | 期望的结果

桌面没有闪烁异常 且消息弹框在图标上方

**Comment by babyfengfjx** [comment]
@yixinshark  可以优先安排分析处理~

**Comment by yixinshark** [comment]
暂时没有复现，请在最新包0.0.32包上验证。

**Comment by yixinshark** [comment]
请帮忙验证此问题。

**Comment by luodeepin** [comment]
验证通过
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20240813/deepin-23-beige-release-amd64-20240813-224846.iso
![录屏_选择区域_20240814114516](https://github.com/user-attachments/assets/217ef735-3391-49ce-ab00-14f0abf5d3af)
