### ISSUE TITLE
【deepin_V23_Release】【一般】【正常】【集成测试】【玲珑】日历没有启动，ll-cli ps 查看正在运行的应用进程时展示日历进程

### ISSUE THREAD

**Issue by vivianxf** [linuxdeepin/developer-center#9929]
### SUMMARY | 问题概要

日历没有启动，ll-cli ps 查看正在运行的应用进程时展示日历进程
关联集成：#9915

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20240722/
```

### PRE-REQUIREMENT | 预置条件

升级集成或者新安装0722镜像

### STEPS TO REPRODUCE | 复现步骤

1.升级到最新版本玲珑
2.终端执行ll-cli ps 查看正在运行的应用进程

### OBSERVED RESULT | 观察到的结果

1.日历没有启动，ll-cli ps 查看正在运行的应用进程时展示日历进程
![截图_选择区域_20240724132715](https://github.com/user-attachments/assets/49ac3b59-54c9-45c5-9bd0-2d77ba5ed47a)

### EXPECTED RESULT | 期望的结果

1.日历没有启动，ll-cli ps 查看正在运行的应用进程时，没有日历进程展示

**Comment by babyfengfjx** [comment]
@dengbo11  请安排优化~

**Comment by myml** [comment]
日历的后台要给托盘提供接口调用, 日历自身也需要后台运行来保证日程提醒, 所以日历会一直运行着 不管窗口是否启动

**Comment by babyfengfjx** [comment]
@vivianxf  请确认。

**Comment by vivianxf** [comment]
经过内部沟通，非问题，关闭处理
![image](https://github.com/user-attachments/assets/c71e2fa8-8a5e-4638-9041-6baaad3c86a0)
