### ISSUE TITLE
Selection in deepin file manager

### ISSUE THREAD

**Issue by mythio** [linuxdeepin/developer-center#993]
## Buggy selection in file manager
While making a selection in the file manager using mouse, selecting the items, makes a continuous selection of the items in the entire row.

## To Reproduce
1. Open 'dde-file-manager'
2. Make sure the display type is set to 'icon' instead of 'list'
3. Start making a selection

## Expected behavior
The selection is expected to select only the files we have hovered the mouse pointer on.

## Screenshots
![bug](https://i.imgur.com/5xKWUpW.png)

### Distro & Version
Linux Deepin 15.9.2

### Related package version
dde-file-manager (4.7.7.1)

**Comment by keybreak** [comment]
It's not buggy, use SHIFT + Selection to select other way. Actually it's pretty good, just not obvious option)
