### ISSUE TITLE
Hot corners must be on the main screen

### ISSUE THREAD

**Issue by ToRvaLDz** [linuxdeepin/developer-center#994]
## Describe the bug

With a dual screen environment the hot corners must be on the first screen

## To Reproduce

Attach a second screen, setup as extender screen on the right, you will find the right hot corners on the right screen.

## Expected behavior

The hot corners must be on the main screen

### Distro & Version

Manjaro 18.0.3

**Comment by aiamuzz** [comment]
@ToRvaLDz ... by 'main screen' to you mean 'workspace' ? ... but hot corners work on all workspaces ...
... unless you mean main monitor

**Comment by ToRvaLDz** [comment]
@aiamuzz Yes, I mean main monitor, the hot corners goes to the second monitor, while I think they must be on the main one.

**Comment by saymoncoppi** [comment]
I really agree with this point. The hot corners should apear only the main screen.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
