### ISSUE TITLE
Screen getting locked intermittently when Deepin Movie is playing ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#995]
Hi,

After the latest update from a couple of days ... i notice that the screen is getting locked while Deepin Movie is playing ... 

at times the movie is playing and when i move the cursor the lock screen sets in with the movie continue to play behind the locked screen ...

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
