### ISSUE TITLE
右键菜单出现黑线

### ISSUE THREAD

**Issue by cctfc** [linuxdeepin/developer-center#996]
点出右键菜单后，将光标在菜单上移动会出现横着的黑线；另外，在控制中心移动光标会出现横着的白线。

**Comment by fwinac** [comment]
![black_line](https://user-images.githubusercontent.com/38755949/54469281-02124700-47d1-11e9-95f4-44ab0a71f2b6.png)

**Comment by fwinac** [comment]
![白线](https://user-images.githubusercontent.com/38755949/54469307-561d2b80-47d1-11e9-97f2-5725fe5ad06b.png)

**Comment by BLumia** [comment]
可能和 #681 重复，是 Arch 用户吗？

另外请在提 issue 尽可能详细的提供可能相关的信息，如果不清楚需要提供哪些信息的话，还请不要跳过创建 issue 时提供的 issue 模板，感谢理解。

**Comment by fwinac** [comment]
> 可能和 #681 重复，是 Arch 用户吗？
> 
> 另外请在提 issue 尽可能详细的提供可能相关的信息，如果不清楚需要提供哪些信息的话，还请不要跳过创建 issue 时提供的 issue 模板，感谢理解。

不是Arch用户，我旧的电脑(2K屏幕)没有问题，换了新电脑(1080P)，缩放到1.25就有问题了。另外，当我使用manjaro deepin时，就没有这个黑线。感觉很玄学。

**Comment by fwinac** [comment]
@BLumia

**Comment by fwinac** [comment]
缩放到1.20到1.30之间的时候会有许多白线、黑线，1.20的时候最多；但是缩放到1.50的时候就没有黑线了，白线基本没有。@BLumia

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
