### ISSUE TITLE
dde-calendar 集成申请

### ISSUE THREAD

**Issue by myml** [linuxdeepin/developer-center#9963]
### package information | 软件包信息

org.dde.calendar | 5.14.1.1

### Package repository address | 软件包仓库地址

name: old url: http://repo-dev.cicd.getdeepin.org/

### changelog | 更新信息

1. 修改玲珑仓库，ll-cli repo modify http://repo-dev.cicd.getdeepin.org --name old
2. 安装或者更新 org.dde.calendar
3. 验证bug是否解决

### Sphere of influence | 影响范围

- https://github.com/linuxdeepin/developer-center/issues/7495

**Comment by babyfengfjx** [comment]
@vivianxf  请开展回归验证。

**Comment by vivianxf** [comment]
验证不通过，更新日历后，日历应用无法打开
