### ISSUE TITLE
[Feature Request] 重新设计应用窗口的标题栏和应用弹出的提示框

### ISSUE THREAD

**Issue by fwinac** [linuxdeepin/developer-center#997]
deepin在开启特效的时候，大部分区域都是现代的“模糊设计”。但是，标题栏和弹出的提示框却是比较过时的设计；重新设计这两个部分以使ui更连贯。原来的设计则可以保留在关闭特效后。

**Comment by lolimay** [comment]
> deepin在开启特效的时候，大部分区域都是现代的“模糊设计”。但是，标题栏和弹出的提示框却是比较过时的设计；重新设计这两个部分以使ui更连贯。原来的设计则可以保留在关闭特效后。

可以贴几张张你预期的设计吗？或者相关的截图对比也行。文字描述似乎不是很直观。

**Comment by fwinac** [comment]
我也不知道该设计成怎么样子。我只说一下我认为的问题。我认为，第三方应用和系统自带的应用（如文件管理器）的标题栏的样式存在明显不一致，而在，Mac OS和Windows在这方面是一致的。

**Comment by lolimay** [comment]
> 我也不知道该设计成怎么样子。我只说一下我认为的问题。我认为，第三方应用和系统自带的应用（如文件管理器）的标题栏的样式存在明显不一致，而在，Mac OS和Windows在这方面是一致的。

原来你讨论的是标题栏与应用的一致性啊...这是一个先有鸡还是先有蛋的问题。emmm...在Windows下开发普通窗体开发者一般是无法修改标题栏的，大部分开发者为了省事是会去用巨硬封装好的API来直接开坑的（除非是无边框的窗体）；Mac 做得更狠，你的应用 UI 做得不合格，直接不给在 App Store 上架，分分钟让你没钱赚；Linux 呢，没有标准，发行版、桌面环境一堆，开发者开发应用随心所欲，使用的技术千奇百怪，有用 GTK 的、Qt 的甚至还有头铁的自己绘制标题栏的（一般都很丑，上个世纪的风格），没有规范，一个应用一个风格。所以说，在大部分开发者还没有使用 dtk-widget （deepin UI库）开发 Linux 应用的这个时代，你得再忍忍。这个是仅修改标题栏样式解决不了的。

那么问题来了，为什么 deepin 全家桶的应用风格如此一致（consistent）呢? 因为他们用的都是 [dtkwidget](https://github.com/linuxdeepin/dtkwidget) 呀😎
