### ISSUE TITLE
Deepin file manager | Computer overflow situations / folders vertical alginment

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#998]
## Describe the bug
Deepin file manager have some real problems with how **computer:///** handles longer worded languages and overflow situations.

1. **Screenshot 1** is a default icon size view, shows situation where 'System disk' overflows to more than 1 line, disk size indicators goes down and disappears
2. **Screenshot 2** is a smaller icon size view, shows same situation + 'Desktop' and 'Images' folder drops down when overflown, and breaks the consistency of vertical alignment (in other folders it works good, unlike in **Computer**).

## To Reproduce
1. Test it with any longer worded language, like any cyrillic

## Expected behavior
I belive both cases are connected, but:
1. Should never loose disk size indicators, as it is very important, not sure how exactly, but even something like 'System d...' with indicator shown would be better in my opinion.
2. Not sure how to phrase it, but using analogy from css folders on top should use: **vertical-align: top;**

## Screenshots
Screenshot 1:
![Image of Yaktocat](https://i.imgur.com/UH7GZSx.png)

Screenshot 2:
![Image of Yaktocat](https://i.imgur.com/Tk4fZfC.png)

## Enviroments:
OS: Manjaro 18.0.4 Illyria
Kernel: x86_64 Linux 4.19.28-1-MANJARO
Shell: bash 5.0.0
DE: Deepin 15.9.2
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
bits: 64
compiler: gcc 8.2.1
tk: Qt 5.12.1
dm: LightDM

### Distro & Version
Manjaro Deepin 18.0.4

### Related package version
deepin-file-manager 1:4.7.7.2-1

### Additional context
All Deepin editions always had & still has this.

I believe this issue extends already existing context of https://github.com/linuxdeepin/internal-discussion/issues/1014 but please take in account everything above while fixing it :smile_cat:

**Comment by SiamSami** [comment]
https://github.com/linuxdeepin/dde-file-manager/pull/182

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
