### ISSUE TITLE
[New-Feature] HotCorners + Shortcuts to Apps

### ISSUE THREAD

**Issue by saymoncoppi** [linuxdeepin/developer-center#999]
Hello Guys!
What do you think to offer a new feature at the Hotcorners settings like an option to choose a shortcut to a command or an app?

Its really similar a custom commands from Deepin Terminal or Keyboard shortcuts from Deepin Control Center or Xdotoll Setup ( take a look there https://www.youtube.com/watch?v=r4iSPrCpBRE).

I drawed a draft just to explain the concept:
![HotCorners_Suggestion](https://user-images.githubusercontent.com/22059715/54403980-bbc5c680-46b0-11e9-8bd2-0cb506c5e5db.png)

In that draft I added at the very right bottom corner a new option "Shortcut".

So when the user click on that option the system displays a form at the center screen to type/choose an Application (GUI) or Command line with parameters.

**GUI Sample Application**
![image](https://user-images.githubusercontent.com/22059715/54405627-1281cf00-46b6-11e9-93a7-ff761d0363ab.png)

**Command line** 
![image](https://user-images.githubusercontent.com/22059715/54405104-43f99b00-46b4-11e9-8d4a-41b218bde5f0.png)

What do you think about this on next releases?
See you!!!
:)

**Comment by wangjia12** [comment]
Thank you for your suggestion, we need to seriously consider it. You will be replied to the results.

**Comment by saymoncoppi** [comment]
Great! tks for your attention... 
I realised another issue with HotCorner when we use 2 screens. I'll open another case for this, ok? Can I mark you?

**Comment by wangjia12** [comment]
Sorry, after the discussion, the functions related to the HotCorners will not increase for the time being.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
